### ISSUE TITLE
Allow to upload a video from a URL

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#100]
Support:
 - Raw URLs (points directly to the video file)
 - All youtube-dl [supported sites](https://rg3.github.io/youtube-dl/supportedsites.html)

**Comment by rigelk** [comment]
Shouldn't we support to the full extent of the platforms supported by `youtube-dl`, if that's the backend used to retrieve the RAW url anyway?

**Comment by Chocobozzz** [comment]
:+1: I edited the issue

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/fbad87b0472f574409f7aa3ae7f8b54927d0cdd6
