### ISSUE TITLE
Block and hide an actor

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#1008]
Another good tool for #718 is also being able to ban remote users. Right now, I've just got a list of users in a text file that I occasionally check on to make sure I've blacklisted any new videos.

**Comment by kyrahabattoir** [comment]
Why not stop following the instance that hosts them?

**Comment by rigelk** [comment]
@kyrahabattoir it's not just about seeing their videos, it's also about preventing their comments to show under your videos too (and really any other kind of interaction independant from the admin).

**Comment by kyrahabattoir** [comment]
Understandable but from an ideological standpoint, I'm not sure you should be able to "pick apart" a given instance instead of taking it as a whole, because it gives too much power to administrators to build a walled garden.

My two cents.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/65b21c961c69c4a63c7c0c34be3d6d034a1176c7 & https://github.com/Chocobozzz/PeerTube/commit/b44164bb567fe7c9f65f1ac2908d44990a8ccc8e

This is muting and not blocking. If you are interested in the blocking feature, please create another issue.
