### ISSUE TITLE
DoS Youtube-dl a live

### ISSUE THREAD

**Issue by Jorropo** [Chocobozzz/PeerTube#1010]
* **PeerTube version or URL:**
Beta.11

* **What is the expected behaviour?**
A user can't use all the cpu and/or block import.
* **What do you see instead?**
If you import a running live on youtube youtube-dl will start an ffmpeg (not niced so on my node it makes my server un responsive) and will run until live finish and live fully transcoded.
That block other import.

**Comment by Chocobozzz** [comment]
Nice catch @Jorropo, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1a893f9c704737e9e19d24cf9d9a7afb041302c3
