### ISSUE TITLE
import youtube subtitles 

### ISSUE THREAD

**Issue by PhieF** [Chocobozzz/PeerTube#1016]
Hi !
it seems possible to import youtube subs
https://github.com/rg3/youtube-dl/#subtitle-options

but I guess peertube doesn't do it, do you think it could be added ?

Thanks !

**Comment by Booteille** [comment]
Is integrating this feature planned anytime soon?
I often have to import subtitles manually actually, that's a bit annoying.

**Comment by Chocobozzz** [comment]
@Booteille No sorry

**Comment by Booteille** [comment]
Okay! Thanks for the answer!

**Comment by benpro** [comment]
For reference, this is how you do it with youtube-dl.

```
youtube-dl "https://www.youtube.com/watch?v=XXX" --all-subs --skip-download
```

I must say, auto-downloading and importing YT subtitles would be nice. Some language detection should be done too.

**Comment by drzraf** [comment]
May #2473 + #2474 be sufficient to resolve this one their own?

**Comment by Chocobozzz** [comment]
Implemented by @kimsible in https://github.com/Chocobozzz/PeerTube/commit/50ad0a1c1699fb1799c9ba2a99bf888894f88df4
