### ISSUE TITLE
Add video from torrent file

### ISSUE THREAD

**Issue by tcitworld** [Chocobozzz/PeerTube#102]
- [ ] Input torrent directly from ~URL~ Magnet URI
- [ ] Upload torrent file

**Comment by jibe-b** [comment]
Suggestion of use case: serve [Internet Archive CC licensed videos](https://archive.org/details/bittorrent)

**Comment by rigelk** [comment]
@jibe-b @voronoipotato just note that importing from a torrent and keeping seeding it are two different things, as keeping sharing poses a few questions/problems:

- keep the original file after transcoding is not something we do yet
- do we share it over WebRTC when only its transcoded version will be streamed in PeerTube?
- if we only share alone (without WebRTC only the server will share the file), then why implement it in PeerTube when there are dedicated clients?

**Comment by Chocobozzz** [comment]
Implemented https://github.com/Chocobozzz/PeerTube/commit/ce33919c24e7402d92d81f3cd8e545df52d98240 & https://github.com/Chocobozzz/PeerTube/commit/990b6a0b0c4fbebc165e5cf7cec8fbc1cbaa6c66
