### ISSUE TITLE
When opening a remote channel, the user's account link redirects to a local user who doesn't exist

### ISSUE THREAD

**Issue by pericoloso69** [Chocobozzz/PeerTube#1021]
* **PeerTube v1.0.0-beta.11**

* **What is the expected behaviour?**

When browsing a remote user's channel, the link to it's account points to a remote user.
Eg. : https://tube.pericoloso.ovh/accounts/myuser@myinstance

* **What do you see instead?**

The link to the user account points to a local user.
Eg. : https://tube.pericoloso.ovh/accounts/myuser

**Comment by Jorropo** [comment]
@Chocobozzz  this bug is fixed in develop branch (see on [my instances](https://peertube.jorropo.ovh/))

**Comment by rigelk** [comment]
Indeed, fixed yesterday :smirk:
