### ISSUE TITLE
Can't read the text in the forms, with Firefox dark theme, because the text is white on white.

### ISSUE THREAD

**Issue by ParleurA** [Chocobozzz/PeerTube#1023]
* **PeerTube version or URL: 1.0.0-beta11**
* **Browser name/version: Firefox 62.0/Linux**

* **What is the expected behaviour?**
Just see the text in the forms!

* **What do you see instead?**
White on white text.

Basically, all the problem is in the subject.

When I want to fill any form, using Firefox with a dark theme, the text in the forms is white on white, and so, its imposibble to read it, unless highlighting it.

It's *very* annoying.

**Comment by rigelk** [comment]
isn't it caused by your browser theme? I don't see how we can act on this.

**Comment by ParleurA** [comment]
Partially, for sure. However, I didn't have the problem with the same browser theme and the previous version of Peertube.

**Comment by Chocobozzz** [comment]
What is your theme so we can reproduce?

**Comment by ParleurA** [comment]
Firefox uses default system theme, which is Adwaita-dark.

**Comment by rigelk** [comment]
In the meantime there is always https://github.com/DmitriK/darkContrast

**Comment by ParleurA** [comment]
Thank you very much for the tip with the firefox plugin ; it'll help for a couple of others website with the same problem. :)

**Comment by rigelk** [comment]
You're welcome!

The problem should be fixed in https://github.com/Chocobozzz/PeerTube/commit/20c3a59e2c81bb00be943ccc51efe175c08eaa4e.
