### ISSUE TITLE
Error 400 while uploading from windows using the API

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#1024]
* **PeerTube version or URL:** v1.0.0-beta11 on https://videos.lecygnenoir.info/about/instance
* **Browser name/version:** Peertube API
* **NodeJS version:** v8.11.3

Hello!

I have a user (@zykino) trying to upload a video using the Peertube API via [Prismedia](https://git.lecygnenoir.info/LecygneNoir/prismedia) script in python, but he gets an odd 400 error from Peertube.

Usually, peertube logs tells what is missing in the request and why the 400 occurs, but I am unable to found it this time, even in debug mode.

We think it could comes from some encoding problem between windows and Linux as there are special chars in the video description, but Peertube logs show correct information without encoding, and the 400 appears oddly some times after the upload start, instead of directly crashed at the start of the upload.

Tests shows that video upload, and the 400 appears at the moment Peertube do its post upload tasks (inserting in BDD, or creating transcoding job?), but without more details.

If we upload using a web browser on Windows, it works perfectly. If we upload using Prismedia on Linux, no problem either.

Do you have some idea what parameters could cause problem?

The error in logs just says:

```
{"message":"XXX.XXX.XXX.XXX - - [02/Sep/2018:15:49:50 +0000] \"POST /api/v1/videos/upload HTTP/1.0\" 400 57 \"-\" \"python-requests/2.19.1\"\n","level":"info","label":"videos.lecygnenoir.info:443","timestamp":"2018-
09-02T15:49:50.256Z"}
```

Here are the parameters extracted from peertube logs:

```
{"parameters":{"name":"4 - Test avec des accents","licence":1,"description":"En rentrant du travail une voiture nous renverse. Un homme habillé en mafieux avec un œil rouge brillant nous dit que nous sommes un gar
dien de cimetière. Où suis-je vraiment ? En quelle année ? Comment retrouver ma bien aimée ?\nSi ce jeu vous intéresse, vous pouvez l'acheter en [utilisant mon lien partenaire sur Humble Bundle](https://www.humble
bundle.com/store/graveyard-keeper?partner=zykino&charity=137859).","nsfw":false,"channelId":103,"tags":["GraveyardKeeper","RPG"],"category":7,"language":"fr","privacy":3,"commentsEnabled":true},"files":{"videofile
":[{"fieldname":"videofile","originalname":"Episode4.mp4","encoding":"7bit","mimetype":"video/mp4","destination":"/var/www/peertube/storage/videos/","filename":"1a490609162dae4bd3b5886d2caeff4e.mp4","path":"/var/w
ww/peertube/storage/videos/1a490609162dae4bd3b5886d2caeff4e.mp4","size":574889000}],"thumbnailfile":[{"fieldname":"thumbnailfile","originalname":"Episode4.jpg","encoding":"7bit","mimetype":"image/jpeg","destinatio
n":"/var/www/peertube/storage/thumbnails/","filename":"f2bcb622efdc851760de9a61e03cbee9.jpg","path":"/var/www/peertube/storage/thumbnails/f2bcb622efdc851760de9a61e03cbee9.jpg","size":292813}],"previewfile":[{"fiel
dname":"previewfile","originalname":"Episode4.jpg","encoding":"7bit","mimetype":"image/jpeg","destination":"/var/www/peertube/storage/previews/","filename":"73c1c334dee70d5669b6285530a98613.jpg","path":"/var/www/p
eertube/storage/previews/73c1c334dee70d5669b6285530a98613.jpg","size":292813}]},"level":"debug","message":"Checking videosAdd parameters","label":"videos.lecygnenoir.info:443","timestamp":"2018-09-02T15:49:50.247Z
"}
```

You could eventually found some more info on this [prismedia issue](https://git.lecygnenoir.info/LecygneNoir/prismedia/issues/9)

Thanks for any help you could provide :-)

Regards

**Comment by Chocobozzz** [comment]
What is the HTTP response? (contains the error descriptions).

**Comment by LecygneNoir** [comment]
I was unable until there to have this information in the HTTP response from python lib, but I'll try to get this :-)

**Comment by Zykino** [comment]
Here is what I got : `{u'error': u'Unknown video video channel for this account.'}`

**Comment by LecygneNoir** [comment]
Mmmh this is even more strange. channelId is 1, it should be your default channel :-/

**Comment by LecygneNoir** [comment]
woops no, my screen cut the logs juste on the bad track -_-

ChannelId 103, mmmh, there is no way currently in Prismedia to specify a channelid, it's currently in deployment for a future release.

Sorry @Chocobozz, it seems I have missed something here :-/
It could very well be a prismedia bug on this one. I'll check that deeply and close the issue if needed!

**Comment by Zykino** [comment]
So it was not a Peertube error. Thank you for the help.

If I could just share my opinion on your error messages: "Unknown video video channel for this account." does not sound really english. Maybe quote the name so it's easier to know what it's all about => "Unknown video `video channel` for this account."

**Comment by LecygneNoir** [comment]
Sorry for the useless issue, I am closing it now, thank you for the help Chocobozz! :kissing_heart:
