### ISSUE TITLE
Automatically generate translations

### ISSUE THREAD

**Issue by Jorropo** [Chocobozzz/PeerTube#1027]
Translation is one version late cause it is uploaded each release.
Maybe with travis's stage we can do a test and after in deploy a generate-i18n, zanata push (and use global [travis env variable](https://docs.travis-ci.com/user/environment-variables/) for verify that is develop branch) to add translation, cause right now we will have to wait beta.13 for have all translation of subscription, ...

**Comment by Chocobozzz** [comment]
I'll update translations more often. I prefer to do it manually so see potential errors etc.
