### ISSUE TITLE
Import from youtube creates non streamable files

### ISSUE THREAD

**Issue by zeograd** [Chocobozzz/PeerTube#1032]
* **PeerTube version or URL:**
beta11
* **Browser name/version:**
N/A
* **NodeJS version:**
8.10.0

* **What is the expected behaviour?**
When importing a youtube url as new peertube video, I would expect a streamable file (moov atom before mdat) so that native resolution video can stream immediately
* **What do you see instead?**
imported file ( https://www.youtube.com/watch?v=VSE8Ea8HVkA ) had moov atom after mdat and couldn't be streamed.
I add to manually fix the file with qtfaststart and import it locally to solve this.

Since it can be fixed with ffmpeg (which is already a dependency), could we imagine that upon file import, ffmpeg is used to fix streamability before proceeding to transcoding other resolution and so on ?
( using codec copy in ffmpeg with option `-movflags +faststart` )

**Comment by rigelk** [comment]
Are you using the cli tool or the web interface?

**Comment by zeograd** [comment]
It was using the web interface.

I double checked older import done with the CLI and it seems like they were streamable (I don't recall manually fixing anything after the CLI import and they are streamable now)

**Comment by rigelk** [comment]
Just to be sure: do you have transcoding enabled on your instance?

**Comment by zeograd** [comment]
Yes it is.
But, correct me if I'm wrong, if the imported video is in one of the target resolution (1080p in this case), transcoding only creates the missing target resolutions below it (and transcoding indeed forces +faststart).
The original video is used to serve content for its native resolution.

**Comment by rigelk** [comment]
Indeed. I've gone rapidly through the web import code (which I'm not very familiar with), and it seems we assume at least the original video is streamable. Or is it @Chocobozzz ?

**Comment by Chocobozzz** [comment]
No we transcode the files, in the same way as we do for video upload: https://github.com/Chocobozzz/PeerTube/blob/develop/server/lib/job-queue/handlers/video-import.ts#L200

Please retry you import, and copy/paste the`video-file` jobs (created when the import is finished).

**Comment by zeograd** [comment]
It seems that the received file is indeed transcoded
the video-file job created upon import is
`{
  "videoUUID": "c531b620-d4f4-4148-8606-d6a3d8eb9a93",
  "isNewVideo": true
}`
and ffmpeg is transcoding to the native resolution, not for lower ones only as I expected.

To avoid spending CPU and degrading video quality, maybe we could add an advanced option at import time "don't transcode to h264" so that we use `-vcodec copy` instead of `-vcodec libx264 ....`. The ffmpeg call would still fix the moov atom position as it's doing now.
(That'd require a separate issue if you think it makes sense)

I apologize for misundertanding that the remote import workflow was a bit different from the local import.
