### ISSUE TITLE
Blank page on "Overview" tab

### ISSUE THREAD

**Issue by nvivant** [Chocobozzz/PeerTube#1039]
Hello,
On my instance, the "Overview" tab displays a blank page instead of random channels/videos.
No error within the logfile. Weird messages within HTML code though...
Thanks for your help!

* **PeerTube version or URL:**
https://fontube.fr/videos/overview
* **Browser name/version:**
Firefox Quantum 62.0 (64 bits) for Ubuntu
* **NodeJS version:**
v8.11.4
* **What is the expected behaviour?**
Random categories/tags/channels and videos
* **What do you see instead?**
Blank page

**Comment by nvivant** [comment]
**Workaround in the meantime:**
Hide the "Overview" tab using custom CSS.

https://peertubeinstance/admin/config/edit-custom
.panel-block > a[href="/videos/overview"] {
display: none !important;
}

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/860cfb31e343f2317416da738f7155803ef4fe75 & https://github.com/Chocobozzz/PeerTube/commit/7348b1fd84dee869b3c36554aea6797f09d4ceed
