### ISSUE TITLE
Build from source, error with sequelize

### ISSUE THREAD

**Issue by PhieF** [Chocobozzz/PeerTube#1041]
For one of my instances, I build peertube from sources (because my left menu isn't exactly the same), but... when building, I get this error
```
 79% chunk modules optimization ModuleConcatenationPluginserver/models/video/video.ts:1179:31 - error TS2339: Property 'random' does not exist on type 'Sequelize'.

```

Any ideas on how to get rid of it ?

thanks !

perhaps it comes from my code

**Comment by Chocobozzz** [comment]
Try to `rm node_modules/ client/node_modules && yarn install --pure-lockfile`

**Comment by PhieF** [comment]
Worked ! Thanks !
