### ISSUE TITLE
Possibility to use the name of an user that has been deleted

### ISSUE THREAD

**Issue by FirePowi** [Chocobozzz/PeerTube#1042]
* **PeerTube version or URL:** bêta.11

* **What is the expected behaviour?**
When an user has been deleted, possibility to re-use their name.

* **What do you see instead?**
No go.

The issue is that one user stole the identity of someone publicly known and that someone can no longer use her name on QueerTube because of that identity theft. It would be really cool if she could use her own name.
Have you got a solution that works for now ?

**Comment by Chocobozzz** [comment]
See https://github.com/Chocobozzz/PeerTube/issues/870

Go in the database, and remove the row (see `preferredUsername` column) in the `actor` table.

**Comment by Nutomic** [comment]
Run `SELECT * FROM actor WHERE preferredUsername=theuser`, and make sure it outputs the correct account. Then run `DELETE FROM actor WHERE preferredUsername=theuser`.

**Comment by m333w** [comment]
Thank you very mutch @Nutomic but i have excute your comand and the user seen to be still there. To be sure i have restart the instance but i cant still recreate the user 

> Another actor (account/channel) with this name on this instance already exists or has already existed.

I have excute the comand like this : 

```
sudo -u postgres psql
\c peertube_prod;
SELECT * FROM actor WHERE preferredUsername=anko
DELETE FROM actor WHERE preferredUsername=anko
```
I am missing something ?

Best regards.

**Comment by m333w** [comment]
I missing `;` at the end of the two comand you give me ?

**Comment by Chocobozzz** [comment]
`SELECT * FROM actor WHERE "preferredUsername"="anko"`
`DELETE FROM actor WHERE "preferredUsername"='anko'`
