### ISSUE TITLE
Editing "Support" text doesn't apply on older videos on the channel

### ISSUE THREAD

**Issue by FirePowi** [Chocobozzz/PeerTube#1046]
* **PeerTube version or URL:** bêta.11

* **What is the expected behaviour?**
When 

* **What do you see instead?**

* **Browser console log if useful:**
* **Server log if useful (journalctl or /var/www/peertube/storage/logs):**

**Comment by Chocobozzz** [comment]
Duplicate of https://github.com/Chocobozzz/PeerTube/issues/827
