### ISSUE TITLE
Blacklisted videos are shown on the overview page.

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#1049]
Peertube version : beta 12. 
I just blacklisted a video on my instance : https://www.yiny.org/videos/watch/0159317d-5bf1-45ed-ae64-d0c9a82f5abf

But on the overview page, it is still listed, even when I'm not logged in as an admin.
https://www.yiny.org/videos/overview
(the video is called «Sepultura - Territory [OFFICIAL VIDEO]»)

**Comment by Chocobozzz** [comment]
@JohnXLivingston It's because the overview route is cached for 1 hour.

**Comment by rigelk** [comment]
@Chocobozzz maybe we should invalidate the overview cache upon moderation?

**Comment by Chocobozzz** [comment]
Yes, so I think this we should keep this issue opened :)

**Comment by realityfabric** [comment]
Is this also why muting an account doesn't remove the account's videos from the Overview page?

**Comment by realityfabric** [comment]
After 2 hours, videos from an account I muted are still on the Overview page, so it would seem I was wrong about these things being connected.

**Comment by Chocobozzz** [comment]
Overviews page is global, and does not take into account muted accounts. We should definitely change this behaviour.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/764a965778ac89e027fd05dd35697c6763e0dc18 & https://github.com/Chocobozzz/PeerTube/commit/111fdc267b36201cf1be1fdf91017005102b4a5e
