### ISSUE TITLE
Change/reset actor's password as admin

### ISSUE THREAD

**Issue by FirePowi** [Chocobozzz/PeerTube#1052]
- Possibility for admin to change once's password and automaticaly send the new one to the user
    - Set it as random-no-see so that the admin don't see it.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/328c78bc4a570a9aceaaa1a2124bacd4a0e8d295 & https://github.com/Chocobozzz/PeerTube/commit/a3342ce250936c30dc6df7563f4e984c172f61c1 & https://github.com/Chocobozzz/PeerTube/commit/2c2baef6f30625794cf1f4f72c184527a4d82562 & https://github.com/Chocobozzz/PeerTube/commit/67b1d3fed765278bdc876cce393ef56d56942df0 & https://github.com/Chocobozzz/PeerTube/commit/b426edd4854adc6e65844d8c54b8998e792b5778
