### ISSUE TITLE
Cannot Delete Channels (Default one or newly created channel)

### ISSUE THREAD

**Issue by ZiiX** [Chocobozzz/PeerTube#1055]
PeerTube v1.0.0-beta.12
ALL
NodJS v 8.10.0

Channels should delete.
When typing in the exact name and hitting delete I get - "Error: Video Channel Not Found"

Thank you for your help and time! Loving peertube!

**Comment by Chocobozzz** [comment]
Thanks for the issue @ZiiX. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/4035d2b6e937e13cd10cf88ed0e89cb579dd86ee
