### ISSUE TITLE
View counter doesn't work anymore

### ISSUE THREAD

**Issue by nvivant** [Chocobozzz/PeerTube#1058]
* **PeerTube version or URL:**
v1.0.0-beta.12

* **Browser name/version:**
 Firefox Quantum 62.0 (64 bits) for Ubuntu

* **NodeJS version:**
 v8.11.4

* **What is the expected behaviour?**
Increase counter when video is viewed

* **What do you see instead?**
Counter is not updated

Those 2 videos were tested all day long from different IP addresses and counters don't increase : 
- https://fontube.fr/videos/watch/1aed3a4d-dd0d-4221-8c84-b1bb6054cc1a
- https://peertube.koehn.com/videos/watch/958cb2fd-920b-4d7c-8070-261059c869d0 (nice music btw, enjoy!)

**Comment by Chocobozzz** [comment]
I think https://github.com/Chocobozzz/PeerTube/commit/9431cabf8a92f602cf3b4626e12f23b0910f52a8 should fix your issue. 

Thanks for the issue @nvivant

**Comment by Nutomic** [comment]
@Chocobozzz Hmmm the view counter still seems broken on my instance. I watched this video twice and it still has 0 views: https://peertube.social/videos/watch/09424c90-9a80-4e66-a306-a8bd95b83006 Other videos are also at 0: https://peertube.social/videos/local

**Comment by Nutomic** [comment]
@rigelk Do you have any idea how I could fix the problem? I can provide logs if needed.

**Comment by Midek** [comment]
I have noticed that after upgrading to beta.13 view counter on my instance is broken as well.
It usually stays at zero, while it should be at least a couple.
Somehow, for one video it did increase to 1 though (this one had over 40 views judging from nginx access logs)

**Comment by Chocobozzz** [comment]
Views are processed with a 24 hours delay. It's fixed on develop by https://github.com/Chocobozzz/PeerTube/commit/6f0c46be8c9f4690d5e5cb758c4df6164b006f83
