### ISSUE TITLE
Subscribe/unsubscribe from all of a user's channels at once

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#1059]
Right now, you have to individually subscribe to a user's channels (which is a good feature). So, it's completely possible to do this in the current release, but time consuming if they have lots of channels.

I'm thinking of a second subscribe button that says something like, "Subscribe to all channels" by the user's full handle on the video page and their main profile.

**Comment by DeeJayBro** [comment]
Can i take this issue?

**Comment by Chocobozzz** [comment]
:+1:

**Comment by PhieF** [comment]
Hi,
I'm sorry to bump this but I'm doing it in case it has been forgotten :P 
a subscribe to account option would be great ! :)

Thanks as always for peertube, it's a really really good platform

**Comment by Chocobozzz** [comment]
Implemented by @rigelk
