### ISSUE TITLE
Add user setting to not play automatically videos

### ISSUE THREAD

**Issue by imtube** [Chocobozzz/PeerTube#106]
Some customers don't want the video to autoplay, is there any way to make it not play automatically ?

**Comment by zeealiawan** [comment]
can you please guide to install it on centos, i contact the author by email but still no response. if you can help to do so?

**Comment by Chocobozzz** [comment]
@zeealiawan Please don't spam issues.

@imtube Maybe a setting would be interesting.

**Comment by Letiteuf55** [comment]
Maybe a user setting will be better than a server setting.

**Comment by Chocobozzz** [comment]
Agreed. I updated the title.

**Comment by dedesite** [comment]
Hi, I start working on this issue and add a migration file for adding an "autoPlayVideo" column in User table but notice that there was no devDependencie for `sequelize-cli`, so how do you apply those migration ?

Another problem : don't know why but `npm run dev:client` doesn't work anymore. I clean up my `node_modules` dir and rebuild everything but when I go to `localhost:3000/` I got nothing.
No errors in the console, just the regular debug print of the SQL requests. 

For now, I can work with `npm run dev:server` but it's not optimal.

**Comment by dedesite** [comment]
I found that we should manually update `LAST_MIGRATION_VERSION` in `server/initializers/constants.ts.ts`

**Comment by dedesite** [comment]
My first _real_ PR, tell me if it is what you wanted :)

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/pull/159

Thanks @dedesite

**Comment by dedesite** [comment]
Glad I could help ! Wish I had more time to work on PeerTube :).
