### ISSUE TITLE
default.yaml set suffix as _dev

### ISSUE THREAD

**Issue by FirePowi** [Chocobozzz/PeerTube#1060]
* **PeerTube version or URL:** bêta.13

* **What is the expected behaviour?**
in default.yaml in bêta.13, there should be `suffix: '_prod'`
* **What do you see instead?**
`suffix: '_dev'`

**Comment by Chocobozzz** [comment]
No, it's the production yaml file that sets the suffix to `prod`.

**Comment by FirePowi** [comment]
Owh. Okkkkkk ! ::o:
