### ISSUE TITLE
Moderations tools accessible at the page of the user

### ISSUE THREAD

**Issue by FirePowi** [Chocobozzz/PeerTube#1061]
When I need to ban/delete an actor, I have to find them on the users list for now.
Often, I see comments or videos of an actor that disrespects the terms of my instance so I click on the username and it leads me to their userpage.

That's, I guess, a place where I should find a button to `ban`/`delete`/`modify` an user.
And for every actor, I guess I should also be able to `delete all their videos` as #1053 .

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/79bd2632d62f2f600d663815fcc00a01ca981aa1
