### ISSUE TITLE
Mass moderation tools for videos

### ISSUE THREAD

**Issue by FirePowi** [Chocobozzz/PeerTube#1062]
As a really important (I guess) tool for #718, I think the mass moderation tools is one that's really missing in PeerTube.

First issue : Videos moderation.

Moderate video by video is really really annoying, I guess, as in many email client, we could have (as admin) a checkbox next to every videos and a massive moderation as `delete videos`, `blacklist videos`.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/3cfa817672657df18260ece5b354efa0f3b6e317
