### ISSUE TITLE
Mass moderation tools for users

### ISSUE THREAD

**Issue by FirePowi** [Chocobozzz/PeerTube#1063]
*As a really important (I guess) tool for #718, I think the mass moderation tools is one that's really missing in PeerTube.*

Second issue : Users moderation.

Same as #1062 , but for users in `/admin/users/list` : having a checkbox for every user and having `delete`, `ban`, `set Video Quota to…`, `set Role as Moderator`, `set Role as Administrator`

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/791645e620fb98c6e7c32271d91d91ff7e41b892 (delete, ban and unban)

Could you open separate issues for the `set video quota to...` etc please?
