### ISSUE TITLE
captions and speed not show in mobile 

### ISSUE THREAD

**Issue by uschana123** [Chocobozzz/PeerTube#1065]
PeerTube v1.0.0-beta.12
https://youtu.be/FZ4GznKk0NM
Browser safari , google chrome ,Firefox 
Os : iOS 11.4.1

**Comment by uschana123** [comment]
> 
> 
> @uschana123 what browser and OS version did you try that with?
Browser safari , google chrome ,Firefox
Os : iOS 11.4.1

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/b335ccec49b450052e3520f66f9acb6670e669f8

Thanks for the issue @uschana123
