### ISSUE TITLE
Organize video listing

### ISSUE THREAD

**Issue by qsypoq** [Chocobozzz/PeerTube#107]
![capture](https://user-images.githubusercontent.com/15003491/31890131-625f5d42-b802-11e7-81ca-ebcfee9671d5.PNG)

I liked the display on Framasoft's peertube, being able to organize video by categories with custom input would be cool.

Maybe it can be managed with something like pod's own playlists ?
It would be killing two birds with one stone. (#14)

**Comment by Chocobozzz** [comment]
Yes, I think playlists will do the job. Maybe the pod administrator could choose which playlists are displayed on the homepage.
