### ISSUE TITLE
Admin should be able to filter lists

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1070]
This goes for basically all lists in the admin section. It should be possible to filter/search the following:

- [x] users by name or email
- [ ] following/followers instances by host

And maybe these too (but lower priority):
- video abuses and blacklisted videos by video name or user name
- jobs (by full text search on the expandable text?)

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/b014b6b9c7cb68d09c52b44046afe486c0736426 & https://github.com/Chocobozzz/PeerTube/commit/24b9417cec5cc785a57b2fe169a1ae88b88801a4
