### ISSUE TITLE
Search for @username fails

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1071]
These searches work fine:
https://peertube.social/search?search=@chrisweredigital@share.tube
https://peertube.social/search?search=chrisweredigital

But this one fails with an error:
https://peertube.social/search?search=@chrisweredigital

* **PeerTube version or URL:** https://peertube.social
* **Browser name/version:** Firefox 62
* **NodeJS version:** v8.11.4

I can check for logs if you need.

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/2ff83ae2923aa93ccefb0fa989ae0bf138a46d77
