### ISSUE TITLE
Peertube daemon doesn't listen on IPv6 localhost

### ISSUE THREAD

**Issue by jadjay** [Chocobozzz/PeerTube#1072]
* **All**
* **NodeJS 8x**

* **What is the expected behaviour?**
Peertube daemon listening on all (ipv4/ipv6) localhost addresses : 127.0.0.1 AND ::1

* **What do you see instead?**
When choosing localhost as listening address : peertube only listen on 127.0.0.1

This is confusing, for most programs now localhost is not ipv4 : it's default to ipv6

* **Browser console log if useful:**
Nginx : 
*57 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1X.XX, server: peertube.rXXXXXXX.fr, request: "GET /api/v1/oauth-clients/local HTTP/1.1", upstream: "http://[::1]:9000/api/v1/oauth-clients/local", host: "peertube.rXXXXXX.fr", referrer: "https://peertube.rXXXXX.fr/login"

**Comment by rigelk** [comment]
Specifying `::1` instead of `localhost` seems to bind the server to both ipv6 and ipv4 adresses. Maybe we just need to replace localhost this way.

**Comment by Chocobozzz** [comment]
It's specified by the admin, not by us: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L2

**Comment by jadjay** [comment]
I agree, it's system configuration stuff,
