### ISSUE TITLE
upgrade to beta 13

### ISSUE THREAD

**Issue by m333w** [Chocobozzz/PeerTube#1075]
Hi all, 

I have upgrade 2 instance just now, and on one instance i got the following error : 

`Sep 16 19:14:03 debian peertube[31352]: > peertube@1.0.0-beta.13 start /var/www/peertube/versions/peertube-v1.0.0-beta.13
Sep 16 19:14:03 debian peertube[31352]: > node dist/server
Sep 16 19:14:03 debian peertube[31352]: /var/www/peertube/versions/peertube-v1.0.0-beta.13/node_modules/config/lib/config.js:203
Sep 16 19:14:03 debian peertube[31352]:     throw new Error('Configuration property "' + property + '" is not defined');
Sep 16 19:14:03 debian peertube[31352]:     ^
Sep 16 19:14:03 debian peertube[31352]: Error: Configuration property "search.remote_uri.users" is not defined`

Can someone help me please ?

Best regards.

**Comment by jadjay** [comment]
Yes : You need to copy the file peertube-latest/config/defaults.yml in your config/ directory (next to your production.yml)

**Comment by m333w** [comment]
Thx @jadjay you solve my problem, i think i have forget this comand 

`sudo -u peertube cp /var/www/peertube/versions/peertube-${VERSION}/config/default.yaml /var/www/peertube/config/default.yaml`

when i have try to update.

Best regards
