### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#1077]
Some features cannot make it into the core of PeerTube ; that doesn't mean they don't have their place in the PeerTube ecosystem. A plugin system should be create to provide enough extensibility for at least a few of PeerTube's functionalities.

Looking at existing plugin systems, one that stands out by its development and maintenance is [architect](https://github.com/c9/architect). You can see an example of application in [c9/core](https://github.com/c9/core) itself, but also in third party applications like [servicebot](https://github.com/service-bot/servicebot/tree/master/plugins) (notice the plugin directory and the plugin definitions).

On the long run, we could even think of developing core features as default plugins (much like [c9/core does](https://github.com/c9/core/tree/master/plugins)).

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/1959
