### ISSUE TITLE
Require old password at password change

### ISSUE THREAD

**Issue by mkoppmann** [Chocobozzz/PeerTube#1081]
* **What is the expected behaviour?** When a user wants to change the account’s password, the current password needs to be also submitted, to prevent attackers from changing it, if they get access to the user’s session.
* **What do you see instead?** The current password is not needed to change it.

* **Reference:** [OWASP](https://www.owasp.org/index.php/Testing_for_weak_password_change_or_reset_functionalities_(OTG-AUTHN-009)#Test_Password_Change)

**Comment by Chocobozzz** [comment]
Implemented by @BO41 in 3805ce3 & be1206b & a890d1e
