### ISSUE TITLE
Import break links in description

### ISSUE THREAD

**Issue by FirePowi** [Chocobozzz/PeerTube#1085]
* **PeerTube version or URL:** Bêta.13
* **Browser name/version:** Firefox 62.0
* **NodeJS version:** v8.11.4

* **What is the expected behaviour?**
The whole description.
* **What do you see instead?**
The links are broken in description importing from Youtube (didn't test it with other plateforms)

**Comment by Chocobozzz** [comment]
Please copy/paste the youtube url so we can reproduce the bug

**Comment by FirePowi** [comment]
Oh I just tried with :
https://www.youtube.com/watch?v=LyHI0tnsXrY
It totally break the description in our instance.

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/c39e86b898370a55c147ed1958db00723b0364e4
