### ISSUE TITLE
Cache folder seperate from Videos folder

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1086]
Peertube should have a seperate folder for storing cached videos. This would allow us to use slow, cheap storage for the majority of videos, and only store popular videos on fast, expensive storage. The cache should contain all redundant videos (#1054). Additionally, it should apply the same algorithm to videos from the local instance, and copy them to the cache. This cache could also be used for video transcoding (#765).

Edit: To clarify a bit, here is how I imagine this to work. Peertube generates two video folders under `/var/www/peertube/storage/`:
`videos/`, contains:
- all videos that were uploaded to the instance (except videos waiting for transcoding)
`videos-cached/`, contains:
- redundantly stored videos from other instances
- videos being transcoded, or waiting for transcoding
- popular videos from the local instance (they are also kept in `videos/` at the same time)

The server would serve files from `videos-cached/` if possible, and fall back to `videos/` if the video is not cached. Ideally there should also be a configurable size limit for `videos-cached/`, and videos are deleted if the folder gets too big. By default, both are normal folders, but it would be easy to mount `videos/` on HDD or remote storage, and mount `videos-cached/` on a fast SSD.

**Comment by scanlime** [comment]
What kinds of storage do you see this applying to? SSD for cache and spinning for the main storage? or local vs remote storage?

(I'm asking partly because I'm having a hard time seeing good ways to use storage other than spinning disks for peertube- SSD seems overkill so far, and cloud storage on the other end seems like it wouldn't be a good cost tradeoff as long as it's possible to add more local disks)

**Comment by Nutomic** [comment]
I think it makes sense in all cases where you have different kinds of storage. Could be local SSD + remote storage, or SSD + HDD, or anything else. 

My instance is hosted on a VPS, and I'm using cheap, slow remote storage for videos. But I also have some free space on the local SSD, which is completely unused at the moment.

**Comment by Nutomic** [comment]
Okay I implemented this in a different way, by using the Nginx proxy_cache directive. Inside the main server block, change this:

```
  location /static/webseed {
    ....
    # comment this line out:
    # alias /var/www/peertube/storage/videos;
    proxy_pass http://localhost:1234;
    proxy_cache peertube_videos;
  }
```

And at the end of the file, outside any server blocks, add this:
```
proxy_cache_path /var/cache/peertube/videos/ levels=1:2 keys_zone=peertube_videos:10m
    max_size=15g inactive=7d use_temp_path=off;
proxy_cache_valid 200 60m;

server {
  listen localhost:1234;
  location /static/webseed {
    alias /var/www/peertube/storage/videos;
  }
}
```

The parameters and setup are explained here: https://www.nginx.com/blog/nginx-caching-guide/

As far as I'm concerned, this solves the caching issue, so feel free to close this.

**Comment by Nutomic** [comment]
@rigelk Is there a good place for this in the documentation or wiki? Then there would be no need to implement it in Peertube.

**Comment by McFlat** [comment]
What if you wanted to cache multiple different types of content, say thumbnails and videos? they would all just end up in the same cache directory. 

This is good stuff, but more fine tuning would be required

**Comment by Nutomic** [comment]
@McFlat You can also set different caches for different paths. Check the blog post I linked above.

**Comment by roipoussiere** [comment]
I might be interesting to automatically move some videos to the cache when the number of views per day or week exceeds a fixed limit. And similarly, move them from the cache to the regular storage when this number fall below an other fixed limit.

**Comment by Nutomic** [comment]
@roipoussiere There are some pretty detailed configuration options in Nginx, check out the [article I linked above](https://www.nginx.com/blog/nginx-caching-guide/).

Closing this issue because @rigelk already added it to the documentation: https://docs.joinpeertube.org/lang/en/docs/cache.html
