### ISSUE TITLE
Moderator cannot view admin page

### ISSUE THREAD

**Issue by AutomCoding** [Chocobozzz/PeerTube#1089]
**PeerTube version or URL:**

PeerTube v1.0.0-beta.13

**Browser name/version:**
* Firefox 62.0 (64 bit) on Windows 7
* Chrome 69.0.3497.100 (64 bit) on Windows 7
* Chrome 69.0.3497.100 (32 bit) on Android tablet

**What is the expected behaviour?**

The administration page should be displayed when a logged in moderator clicks the ”Administration” link in the menu panel. The link points to /admin/video-abuses.

**What do you see instead?**

The message ”Sorry, but we couldn't find the page you were looking for.”

**Browser console log if useful:**

No errors in the browser console.

**Comment by Nutomic** [comment]
Instance is https://peertube.social btw. I couldn't find anything relevant in the server logs (but maybe I looked in the wrong place).

**Comment by Chocobozzz** [comment]
Thanks for the issue @AutomCoding, it's fixed in https://github.com/Chocobozzz/PeerTube/commit/ad76628b17ff8f25d3402d6d669b274116bbf76c
