### ISSUE TITLE
Add Persian (fa) to locales list

### ISSUE THREAD

**Issue by ehsaan-me** [Chocobozzz/PeerTube#1091]
Hello there.

Plase add Persian (fa) locale to the list so we can begin the translation process.

Best.

**Comment by kousha1999** [comment]
Hello
Please add Persian (fa) locale to the list
We have a community to help during the process.

**Comment by Chocobozzz** [comment]
Afghanistan or Iran? (we make alias but we prefer to keep the entire locale)

**Comment by BlackSuited** [comment]
As far as I know, there are two locales for each country (fa_IR & fa_AF) and a general locale (fa).
However, we're from Iran and intend to translate to Iranian Farsi.

**Comment by Chocobozzz** [comment]
Added https://trad.framasoft.org/iteration/view/peertube/develop/languages/fa-IR :+1: 

Thanks!
