### ISSUE TITLE
web app manifest not found

### ISSUE THREAD

**Issue by BO41** [Chocobozzz/PeerTube#1092]
* **PeerTube version or URL: **
- https://peertube2.cpy.re/ PeerTube v1.0.0-beta.13

* **What is the expected behaviour?**
- `/manifest.json` should be found and be respected by the browser
* **What do you see instead?**
- `/manifest.json` is not found although it is linked.

ALSO:
>Note: The .webmanifest extension is specified in the Media type registration section of the specification.

https://developer.mozilla.org/en-US/docs/Web/Manifest

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/65be133b909ad9c14b7474f3bdfcc4eed2199e26
