### ISSUE TITLE
Wrong link in overview list

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#1094]
I'm using Beta 13.
In the overview page, I have this link for a tag section : https://www.yiny.org/search?tagOneOf=punk%20rock

The parameter seems not right. The resulting page has no filter.
The correct link should be : https://www.yiny.org/search?tagsOneOf=punk%20rock
(there is a missing 's')

**Comment by rigelk** [comment]
It has already been fixed in https://github.com/Chocobozzz/PeerTube/commit/cfc16a6db88378f83fa3a501170fa0fc5e7d6636 - thanks for spotting the error!
