### ISSUE TITLE
Tag search is case sensitive, and it should not be

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#1095]
Using beta 13.

Tag search is case sensitive, it should not be.
Example:
https://www.yiny.org/search?tagsOneOf=Clip => 1 result
https://www.yiny.org/search?tagsOneOf=clip => no result

**Comment by bristow** [comment]
Same thing here on PT 1.1.0

https://tube.ac-lyon.fr/search?search=SNT > 2 results
https://tube.ac-lyon.fr/search?search=snt > 0 results

Thanks !

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/4b1f1b810a50829be8d8998cdd4d296143e34f2e
