### ISSUE TITLE
(suggestion) Moving to GitLab or FramaGit or ...? Here is how RedoxOS is doing it (the right way, IMHO)

### ISSUE THREAD

**Issue by Zig-03** [Chocobozzz/PeerTube#1096]
So [RedoxOS](https://www.redox-os.org/) keeps only their releases on [github](https://github.com/redox-os/redox) but are doing their active development on [GitLab](https://gitlab.redox-os.org/redox-os/redox). I think this is a great solution. They support the users who still wanna use github but also they support FOSS by using GitLab. So maybe peertube can do the same?

**Comment by Chocobozzz** [comment]
We already use Gitlab: https://framagit.org/chocobozzz/PeerTube/
