### ISSUE TITLE
Dark theme broblem

### ISSUE THREAD

**Issue by manuelviens** [Chocobozzz/PeerTube#1097]
* **PeerTube version or URL: peertube.social (PeerTube v1.0.0-beta.13)
* **Browser name/version: FF 62.0 64bit

Problem with the dark theme : when uploading a file, the tags editor (before hiting Enter) is white on white. Tabs are white on white too.
Here is a screenshot : https://i.postimg.cc/QC2cpWzT/peertubedarktheme.jpg

**Comment by rigelk** [comment]
I fixed both in 1fd3ef3f.
