### ISSUE TITLE
Production Mode ?

### ISSUE THREAD

**Issue by fredhampton** [Chocobozzz/PeerTube#11]
Can you let me know what the minimum configuration for Production Mode is ?

Thanks !

**Comment by Chocobozzz** [comment]
Hi @fredhampton 

If you mean PeerTube configuration you have an example production file in the `config` directory: https://github.com/Chocobozzz/PeerTube/blob/master/config/production.yaml.example

**Comment by fredhampton** [comment]
Are there any suggestions for what to do for scaling 1000+ users ?


On October 4, 2016 at 11:43:10 PM, Bigard Florian (notifications@github.com) wrote:

Hi @fredhampton

If you mean PeerTube configuration you have an example production file in the config directory: https://github.com/Chocobozzz/PeerTube/blob/master/config/production.yaml.example

**Comment by Chocobozzz** [comment]
No sorry, I did not test PeerTube with so many users.

But it would be awesome if you could provide feedbacks.

**Comment by fredhampton** [comment]
Ok … Thanks so much … I will provide the feedback !!!


On October 5, 2016 at 6:53:01 AM, Bigard Florian (notifications@github.com) wrote:

No sorry, I did not test PeerTube with so many users.

But it would be awesome if you could provide feedbacks.

**Comment by fredhampton** [comment]
Has anything changed as far as configuring peertube for production ?

**Comment by Chocobozzz** [comment]
@fredhampton The only things that changed is the [name of the videos directory](https://github.com/Chocobozzz/PeerTube/commit/b3d92510157f9066ea7fa82c303bea7a10eb55b6).

You could make a `mv uploads videos` or add `videos: 'uploads/'` in your `production.yaml`. 

This will be the last breaking change in PeerTube (the future breaking change will be handle by migration scripts).

Let me know if you have any other questions.
