### ISSUE TITLE
No other videos listed

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#1101]
* **PeerTube version or URL:**
https://dialup.express/videos/watch/b6bc2665-39fc-4c07-b7a7-7b7e0889cf7b
* **NodeJS version:**
v8.11.2

* **What is the expected behaviour?**
A functioning view counter and other videos listed.
* **What do you see instead?**
Only zero views (I've watched it a couple times and so have other people). There's a blank where the other videos should be listed.

* **Server log if useful (journalctl or /var/www/peertube/storage/logs):**
https://pastebin.com/ZHiUA0Ac

**Comment by Chocobozzz** [comment]
For the view issue see https://github.com/Chocobozzz/PeerTube/issues/1058#issuecomment-421919157

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/01fe5bd721ae99569f776ad362ebdaa5ba8f494f
