### ISSUE TITLE
unable to start client side

### ISSUE THREAD

**Issue by BO41** [Chocobozzz/PeerTube#1102]
I was trying to start the client side for developing.
Maybe I missed something, or it is not configured right. But after running `npm run dev:client` I get an error: `Redis connection to localhost:6379 failed`.

I was able to solve it by starting a redis server with `redis-server` in a different terminal.
I think this should be automated.

Running Arch (4.18.8-arch1-1-ARCH)

**Comment by rigelk** [comment]
I'm not sure automating external tools would make a lot of sense when their names vary depending on the OS, something we are already tracking with our dependency guide.

By the way, being on archlinux you can start `redis.service` (again as documented in the dependency guide) via `systemctl start redis` and not have to keep a terminal in foreground with `redis-server` running.

**Comment by BO41** [comment]
okay, but if I read correctly, it was never mentioned that the redis server needs to be started.
Not even in the dependency guide.

I think this should be mentioned as everyone needs this. Or am I wrong?

**Comment by rigelk** [comment]
Sure, why not be more verbose.

**Comment by BO41** [comment]
@rigelk nice! thanks.
Now it is **much** better
