### ISSUE TITLE
video show counter not incrementing

### ISSUE THREAD

**Issue by ReK2Fernandez** [Chocobozzz/PeerTube#1107]
I uploaded a video 12 hours a go and I know for a fact that at least 20+ people have seen it but it says 0 still.
```
Published hace 9 horas - 0 views 
```
https://video.hispagatos.org/videos/watch/fba2e157-2a33-483d-a0c2-f515381c512a
what could be the issue? everything else seems ok.

**Comment by BO41** [comment]
I think this is a duplicate to https://github.com/Chocobozzz/PeerTube/issues/1101 which should be solve here https://github.com/Chocobozzz/PeerTube/issues/1058#issuecomment-421919157

**Comment by rigelk** [comment]
Closing as per previous answer :)
