### ISSUE TITLE
No more line breaks when the long description is displayed

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#1108]
* **PeerTube version or URL:** 1.0.0-beta.13

* **What is the expected behaviour?**
width of the html long description in video watch view should be responsive.

* **What do you see instead?**
There is no more line breaks when the long description is displayed.
The div takes the width of the longest sentence.

short : 
<img width="1314" alt="capture d ecran 2018-09-23 a 11 53 07" src="https://user-images.githubusercontent.com/9108457/45926767-e5830980-bf27-11e8-8899-3cfb960c1296.png">

long : 
<img width="1348" alt="capture d ecran 2018-09-23 a 11 53 25" src="https://user-images.githubusercontent.com/9108457/45926768-e9169080-bf27-11e8-9a2f-cae230540a21.png">

**Comment by rigelk** [comment]
Hi @gegeweb! #1056 already covers this and solved the problem.
