### ISSUE TITLE
Proper way to shutdown an instance

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#1113]
Hello!

This a question, not a bug or issue :-)
I am planning to migrate my instance to another domain, and even if there are tools in peertube to do that now, I realized that it could cause problem in the federation.

Indeed, old URL will be unavailable, but still exist in instances following me. 
The same problem appears if you stop your instance definitely.

So I have the question: is there any way to "shutdown" properly an instance?  
Something to do to send to the federation "hey, I am leaving, you do not need to show my videos anymore"?
Do the instance following the old URL try to reach it even if it does'nt answer?

Thanks you!

Regards

**Comment by rigelk** [comment]
Ensure it answers 404 (not just a timeout), and it should be fine.

**Comment by Chocobozzz** [comment]
Removing all your user videos so other instances stop showing them would be useful too :+1:
