### ISSUE TITLE
Youtube Import: stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by roere** [Chocobozzz/PeerTube#1114]
I got in  cases a "stdout maxBuffer exceeded" error when trying to import Youtube-Videos over the web interface. Both videos could be imported on the third or fourth try.
The example videos:
https://www.youtube.com/watch?v=-uX3eJZe8v0
https://www.youtube.com/watch?v=kYKTnHAFoAQ

Log entry:
> Sep 24 17:05:25 Wotan peertube[24554]: [widemus.de:443] 2018-09-24 17:05:25.249 #033[31merror#033[39m: Cannot execute job 8 in queue video-import. {
Sep 24 17:05:25 Wotan peertube[24554]:   "meta": {
Sep 24 17:05:25 Wotan peertube[24554]:     "payload": {
Sep 24 17:05:25 Wotan peertube[24554]:       "type": "youtube-dl",
Sep 24 17:05:25 Wotan peertube[24554]:       "videoImportId": 8,
Sep 24 17:05:25 Wotan peertube[24554]:       "thumbnailUrl": "https://i.ytimg.com/vi/kYKTnHAFoAQ/maxresdefault.jpg",
Sep 24 17:05:25 Wotan peertube[24554]:       "downloadThumbnail": true,
Sep 24 17:05:25 Wotan peertube[24554]:       "downloadPreview": true
Sep 24 17:05:25 Wotan peertube[24554]:     },
Sep 24 17:05:25 Wotan peertube[24554]:     "err": {
Sep 24 17:05:25 Wotan peertube[24554]:       "stack": "Error: stdout maxBuffer exceeded\n    at Socket.onChildStdout (child_process.js:329:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:246:13)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at Pipe.onread (net.js:601:20)",
Sep 24 17:05:25 Wotan peertube[24554]:       "message": "stdout maxBuffer exceeded",
Sep 24 17:05:25 Wotan peertube[24554]:       "cmd": "/var/www/peertube/versions/peertube-v1.0.0-beta.13/node_modules/youtube-dl/bin/youtube-dl -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best -o /var/www/peertube/storage/videos/1a5b1e3d8358f4e1be5aaeeb15315aa2c66ea735f4e45e364eaf4b79624f8cbd-import.mp4 http://www.youtube.com/watch?v=kYKTnHAFoAQ"
Sep 24 17:05:25 Wotan peertube[24554]:     }
Sep 24 17:05:25 Wotan peertube[24554]:   }
Sep 24 17:05:25 Wotan peertube[24554]: }
Sep 24 17:05:33 Wotan peertube[24554]: [widemus.de:443] 2018-09-24 17:05:33.362 #033[32minfo#033[39m: 84.44.232.36 - - [24/Sep/2018:15:05:33 +0000] "GET /api/v1/users//me/videos?start=0&count=5&sort=-publishedAt HTTP/1.0" 304 - "https://widemus.de/my-account/videos" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
Sep 24 17:05:36 Wotan peertube[24554]: [widemus.de:443] 2018-09-24 17:05:36.042 #033[32minfo#033[39m: 84.44.232.36 - - [24/Sep/2018:15:05:36 +0000] "GET /api/v1/users//me/videos?start=5&count=5&sort=-publishedAt HTTP/1.0" 200 1698 "https://widemus.de/my-account/videos?sort=-publishedAt&page=1" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
Sep 24 17:05:42 Wotan peertube[24554]: [widemus.de:443] 2018-09-24 17:05:42.364 #033[32minfo#033[39m: 84.44.232.36 - - [24/Sep/2018:15:05:42 +0000] "GET /api/v1/users//me/videos/imports?start=0&count=10&sort=createdAt HTTP/1.0" 200 10089 "https://widemus.de/my-account/video-imports" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"

 

PeerTube version or URL: v1.0.0-beta13
Browser name/version: Firefox (Linux) 61.01 
NodeJS version: 8.12

**Comment by rigelk** [comment]
Sounds like a problem with how we use `child_process.exec`. As said by the [documentation](http://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback), the stdout `maxBuffer` is 200K. And…

> `maxBuffer` specifies the largest amount of data allowed on stdout or stderr - if this value is exceeded then the child process is killed.

…which lead to the current situation, I guess. We should probably increase the buffer size, like this:

```typescript
exec(command, {maxBuffer: 1024 * 500}, cb) // for 500KB
```

**Comment by rigelk** [comment]
Now, maybe we should use `child_process.spawn` instead. It returns a stream instead of a buffer, and doesn't suffer from the size limitation for that very reason. It seems to be the recommended way of handling large command outputs too.

**Comment by Chocobozzz** [comment]
@rigelk Infortunately we are not the ones who use the `execFile` function, but our youtube-dl dependency.

Should be fixed in https://github.com/Chocobozzz/PeerTube/commit/cc68049424c2a7fc7fb919bc39a43f169e128780
