### ISSUE TITLE
Add strings to Zanata

### ISSUE THREAD

**Issue by AutomCoding** [Chocobozzz/PeerTube#1121]
* **PeerTube version or URL:**
PeerTube v1.0.0-beta.14

* **What is the expected behaviour?**
The *State* column values (*accepted* and *pending*) at the pages ```/admin/follows/following-list``` and ```/admin/follows/followers-list``` should be translatable.

* **What do you see instead?**
They are currently displayed in English in all language versions, and the strings are not listed in Zanata.

**Comment by Chocobozzz** [comment]
Thanks, should be fixed in https://github.com/Chocobozzz/PeerTube/commit/3827c3b3488845f4235714e92eea439423df2909
