### ISSUE TITLE
Yunohost upgrade failing for version 1.0.0-beta.15

### ISSUE THREAD

**Issue by anmol26s** [Chocobozzz/PeerTube#1124]
Peertube is failing on upgrade to 1.0.0-beta.15 on Yunohost
```
Sep 26 18:41:53 example.com peertube[16942]: > peertube@1.0.0-beta.15 start /var/www/peertube
Sep 26 18:41:53 example.com peertube[16942]: > node dist/server
Sep 26 18:41:54 example.com peertube[16942]: /var/www/peertube/node_modules/config/lib/config.js:203
Sep 26 18:41:54 example.com peertube[16942]:     throw new Error('Configuration property "' + property + '" is not defined');
Sep 26 18:41:54 example.com peertube[16942]:     ^
Sep 26 18:41:54 example.com peertube[16942]: Error: Configuration property "redundancy.videos.check_interval" is not defined
Sep 26 18:41:54 example.com peertube[16942]:     at Config.get (/var/www/peertube/node_modules/config/lib/config.js:203:11)
Sep 26 18:41:54 example.com peertube[16942]:     at Object.<anonymous> (/var/www/peertube/dist/server/initializers/constants.js:200:63)
Sep 26 18:41:54 example.com peertube[16942]:     at Module._compile (module.js:653:30)
Sep 26 18:41:54 example.com peertube[16942]:     at Object.Module._extensions..js (module.js:664:10)
Sep 26 18:41:54 example.com peertube[16942]:     at Module.load (module.js:566:32)
Sep 26 18:41:54 example.com peertube[16942]:     at tryModuleLoad (module.js:506:12)
Sep 26 18:41:54 example.com peertube[16942]:     at Function.Module._load (module.js:498:3)
Sep 26 18:41:54 example.com peertube[16942]:     at Module.require (module.js:597:17)
Sep 26 18:41:54 example.com peertube[16942]:     at require (internal/module.js:11:18)
Sep 26 18:41:54 example.com peertube[16942]:     at Object.<anonymous> (/var/www/peertube/dist/server/initializers/index.js:6:10)
Sep 26 18:41:54 example.com peertube[16942]: npm ERR! code ELIFECYCLE
Sep 26 18:41:54 example.com peertube[16942]: npm ERR! errno 1
Sep 26 18:41:54 example.com peertube[16942]: npm ERR! peertube@1.0.0-beta.15 start: `node dist/server`
Sep 26 18:41:54 example.com peertube[16942]: npm ERR! Exit status 1
Sep 26 18:41:54 example.com peertube[16942]: npm ERR!
Sep 26 18:41:54 example.com peertube[16942]: npm ERR! Failed at the peertube@1.0.0-beta.15 start script.
Sep 26 18:41:54 example.com peertube[16942]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Sep 26 18:41:54 example.com systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE

```
nodejs -v
v8.12.0
npm -v
6.4.1
yarn -v
1.9.4
redis-server -v
Redis server v=3.2.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=c9ca860b301a190d

**Comment by rigelk** [comment]
You are missing a new configuration key introduced for the redundancy feature

**Comment by anmol26s** [comment]
I am sorry, but were the has to configured?

**Comment by rigelk** [comment]
It is in `config/production.conf`
See https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md

**Comment by Chocobozzz** [comment]
@anmol26s Do you copy the default.yaml configuration file at each upgrade? https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#manually

**Comment by Chocobozzz** [comment]
Yes, as it is specified in the upgrade guide I linked above

**Comment by anmol26s** [comment]
But I see this line in the default.yaml  **YOU SHOULD NOT UPDATE THIS FILE, USE production.yaml instead**. So it should not change by itself. I have not copied it from previous versions, so what should I do now? Filling the values in upgrade script will make it work? I have previous backpup of peertube, I see that the file had nothing changed in it  and the peertube was working.

**Comment by Chocobozzz** [comment]
The `default.yaml` file contains default configuration values. It is overloaded by the `production.yaml` file. So you don't have to do anything, just copy the `default.yaml` configuration file at each upgrade so PeerTube as a value foreach configuration key it needs.

**Comment by anmol26s** [comment]
But as I delete the main directory every time and create the peertube folder with new sources on each upgrade, it should come by itself by new sources as I see here its already there in /config folder https://github.com/Chocobozzz/PeerTube/blob/v1.0.0-beta.15/config/default.yaml. Correct me if I am wrong, please.

**Comment by Chocobozzz** [comment]
It depends on the value of your NODE_CONFIG_DIR env variable. For example in our [systemd template](https://github.com/Chocobozzz/PeerTube/blob/develop/support/systemd/peertube.service#L8), it is not located inside the extracted peertube directory but outside (so we keep the produciton.yaml file at each upgrade, since we move the directories).
