### ISSUE TITLE
Unfollowing a remote instance does not delete their videos

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#1126]
Running 1.0.0-beta14. When I unfollow a remote instance, the videos disappear from the UI listing, but the files are still in disk and in the database.

Even after unfollowing all remote instances, the database has what seems to be all remote videos still, if I `select uuid from "video" where remote = 'y'`

**Comment by Chocobozzz** [comment]
Yes we don't remove the data when you unfollow an instance because maybe your users follow a channel of this instance, or another one searched a specific video of this instance.

**Comment by rigelk** [comment]
Not for every piece of content, but at least the content followed by your users so that they can keep watching and get informed of new content. It's not related to redundancy to of the videos themselves but to caching metadata.

> Is there a requirement that remote servers have for hosts which offer mirrors? If so, how would deleting the videos from the database via unfollowing need to be different from, for example, the same former peer disappearing due to network trouble or hardware failure?

Would you care to clarify?
