### ISSUE TITLE
update problem

### ISSUE THREAD

**Issue by prolibre** [Chocobozzz/PeerTube#1129]
Je le fais en français pour aller plus vite.
Si j'utilise le script d'upgrade il me rétrograde en beta.13 :-) 

Ce qui est logique en lisant ici : 
https://api.github.com/repos/chocobozzz/peertube/releases/latest

cdl

**Comment by BO41** [comment]
it would be great if could make your issue in English, so that everyone can understand and help you :)
Even translated with google-translator would be fine

**Comment by aerogus** [comment]
Versions beta.14 and beta.15 are "just" pre-release and not really released (but I don't know why)
Look at : https://github.com/Chocobozzz/PeerTube/releases

**Comment by rigelk** [comment]
As @aerogus said, they are pre-releases and are ignored by the script. Hopefully no issue should occur by downgrading :)

**Comment by Nutomic** [comment]
This is fixed by #1128.
