### ISSUE TITLE
Add ability to edit video's preview/thumbnails

### ISSUE THREAD

**Issue by qsypoq** [Chocobozzz/PeerTube#113]
Actually the only method to do that is manually. (edit `video_name.jpg` file in /thumbnails)

- Allow user to choose the thumbnail from his computer when uploading the video

- Allow him to do it in the `update` menu too

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/6de36768980ef6063b8fcd730b59fa685dd2b99c
