### ISSUE TITLE
code style question

### ISSUE THREAD

**Issue by BO41** [Chocobozzz/PeerTube#1130]
Angular supports if statements like `*ngIf` and it also supports an else case.

```html
<div *ngIf="title; else login">
    The user is logged in.
</div>
<ng-template #login>Please login to continue.</ng-template>
```

like in this example.

Is there a reason this project is not using this? Is it faster or something like this?
I guess it could be faster or at least better to look at.

**Comment by BO41** [comment]
I am talking about using the else statement, instead of another inverted if statement

**Comment by rigelk** [comment]
Well for instance I didn't know about that style :smiley: I'll try this technique

**Comment by BO41** [comment]
@rigelk other question: is there a reason return types are not set?
wouldn't it be better, so that the compiler and the ide can show an error if I return or expect something different than a method would give me?

for example:
```ts
getResolutionKey (resolution: string) {
    return 'transcodingResolution' + resolution
  }
```

should be


```ts
getResolutionKey (resolution: string): string {
    return 'transcodingResolution' + resolution
  }
```

**Comment by rigelk** [comment]
@BO41 the return type is implied by the cast. Ambiguous cases (especially with branched returns) should by explicitly typed.
