### ISSUE TITLE
Angular configuration options (still missing noImplicitAny)

### ISSUE THREAD

**Issue by BO41** [Chocobozzz/PeerTube#1131]
The angular/ts allows some settings that might be good to change (for better performance):

- [`"noImplicitAny": true,`](https://angular.io/guide/typescript-configuration#noimplicitany-and-suppressimplicitanyindexerrors)
    >When the noImplicitAny flag is true and the TypeScript compiler cannot infer the type, it still generates the JavaScript files, but it also reports an error. Many seasoned developers prefer this stricter setting because type checking catches more **unintentional errors** at compile time.

- [`--build-optimizer`](https://angular.io/guide/deployment#optimize-for-production) (I guess this is not used; but may be enabled by default)
   >You may further **reduce bundle sizes** by adding the build-optimizer flag.

- [`strictInjectionParameters`](https://angular.io/guide/aot-compiler#strictinjectionparameters)
    >When set to true, this options tells the compiler to report an error for a parameter supplied whose injection type cannot be determined. When this option is not provided or is false, constructor parameters of classes marked with @Injectable whose type cannot be resolved will produce a warning.
Note: It is **recommended** to change this option explicitly to **true** as this option will default to true in the future.

- [`fullTemplateTypeCheck`](https://angular.io/guide/aot-compiler#fulltemplatetypecheck)
    >This option tells the compiler to enable the binding expression validation phase of the template compiler which uses TypeScript to validate binding expressions.
This option is false by default.
Note: It is **recommended** to set this to **true** because this option will default to true in the future.

please ignore everything that is already in use

**Comment by Chocobozzz** [comment]
> --build-optimizer (I guess this is not used; but may be enabled by default)

https://github.com/Chocobozzz/PeerTube/blob/develop/client/angular.json#L44

I enabled the other options in https://github.com/Chocobozzz/PeerTube/commit/07524e229fa88a0d01af9d52ce124760f8ca5fa4

For the `noImplicitAny` it would be nice, but requires more work.

**Comment by BO41** [comment]
@Chocobozzz okay. seems like either I didn't knew all the ways to activate options or angular changed since the last time I used it.
good to know that `--build-optimizer` was already in use.

I could open an PR for `noImplicitAny`. should be easy to fix, just take some time and work

**Comment by Chocobozzz** [comment]
:+1:
