### ISSUE TITLE
Wrong update

### ISSUE THREAD

**Issue by m333w** [Chocobozzz/PeerTube#1132]
Hi all, 

I think something wrong with the "check" about update, i whas lauching 

`VERSION=$(curl -s https://api.github.com/repos/chocobozzz/peertube/releases/latest | grep tag_name | cut -d '"' -f 4) && echo "Latest Peertube version is $VERSION"`

But the output whas : 

`Latest Peertube version is v1.0.0-beta.13` 

I whas in v14, i follow this guide for [update](https://framagit.org/chocobozzz/PeerTube/blob/develop/support/doc/production.md#upgrade)

I have just change the version for 15 everything is fine, but i open this issue to notify if may be they are a problem with the check version. 

Best regards.

**Comment by Nutomic** [comment]
This is because the Github API only returns the latest *stable* release with that API call. To upgrade to a pre-release version, you can set the version manually with `VERSION=v1.0.0-beta.13`. #1128 is related to this.

**Comment by rigelk** [comment]
Hi @m333w - nothing wrong here, it's just that we switched beta.14 and beta.15 to pre-release due to instabilities with the new features. Nothing critical but we didn't want to have everyone on them either. Sorry about the rough change though, we shouldn't be doing that again anytime soon.
