### ISSUE TITLE
Ability to reorganize videos in a channel

### ISSUE THREAD

**Issue by anoadragon453** [Chocobozzz/PeerTube#1133]
Is this possible? If we're treating channels like playlists then we should be able to reorganize the videos in the list.

Currently I have a SRT of videos that were uploaded out of order, and there doesn't seem to be any way to put them in order short of re-uploading all the videos :/

**Comment by Chocobozzz** [comment]
Hello,

No sorry it's not possible. You'll have to wait the playlist feature :) See https://github.com/Chocobozzz/PeerTube/issues/14
