### ISSUE TITLE
Fail2ban for peertube + lock root account 

### ISSUE THREAD

**Issue by anmol26s** [Chocobozzz/PeerTube#1138]
As the default admin username is root , it can be attacked by bots. 
Is there a way to lock root account or change the username to something else?
Further fail2ban implementation for the login page would be good.

**Comment by Chocobozzz** [comment]
We have a rate limiter on the login endpoint: https://github.com/Chocobozzz/PeerTube/blob/develop/server/controllers/api/users/index.ts#L44

So you should not need to lock the root account or have a fail2ban rule.
