### ISSUE TITLE
Can create duplicate username

### ISSUE THREAD

**Issue by Dryusdan** [Chocobozzz/PeerTube#114]
Hello
I test new PeerTube image and I create 3 accounts.
When account username is the same (case sensitive) with another, the error message is `[object Object]` ^^ 

But, if I create two accounts (for exemple Dryusdan && dryusdan). It's work.

Regard

**Comment by Chocobozzz** [comment]
Username are case insensitive now. When the admin creates a user, it has to be in lowercase (to avoid errors).

See https://github.com/Chocobozzz/PeerTube/commit/563d032e97cc62de50281e6413a8a03ed37a3d3b
