### ISSUE TITLE
Clicking on the grey publish button generate errors

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#1143]
Hello!

* **PeerTube version or URL:** 1.0.0-beta14
* **Browser name/version:** Firefox 62
* **NodeJS version:** v8

* **What is the expected behaviour?** 
When uploading video, the publish button is deactivated. So when clicking on the button, it should do nothing.  

* **What do you see instead?**
It generates a red error in the interface saying "Video not found!", and a false update in the logs:

```
[videos.pair2jeux.tube:443] 2018-09-28 19:03:22.875 debug: Checking videosUpdate parameters {
  "meta": {
    "parameters": {
      "name": "[FR] EUIV - Puissance Africaine - Ep25 - Stratégie d'avenir",
      "category": null,
      "licence": null,
      "language": null,
      "support": null,
      "description": null,
      "channelId": 2,
      "privacy": 3,
      "tags": null,
      "nsfw": false,
      "waitTranscoding": false,
      "commentsEnabled": true,
      "thumbnailfile": "",
      "previewfile": "",
      "scheduleUpdate": null
    }
  }
}
[videos.pair2jeux.tube:443] 2018-09-28 19:03:23.147 info: 37.169.119.227 - - [28/Sep/2018:19:03:23 +0000] "PUT /api/v1/videos/0 HTTP/1.1" 404 27 "https://videos.pair2jeux.tube/videos/upload" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
```

Note the 404 for the PUT line

These errors appears even if the loading bar is not full, just need to click on publish when uploading is running.

Thanks!

**Comment by Chocobozzz** [comment]
Thanks, should be fixed in https://github.com/Chocobozzz/PeerTube/commit/59c9c5d9bb383cff118c4d8086cf3e3f43774404
