### ISSUE TITLE
Too long processing reinit the upload and upload videos multiple times

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#1145]
Hello!

* **PeerTube version or URL:** 1.0.0-beta14
* **Browser name/version:** Firefox 62
* **NodeJS version:** 8

* **What is the expected behaviour?** Processing video at the end of the upload take the necessary time, and the publish button get activated to publish the video

* **What do you see instead?** After some time (around 2 minutes), the processing seems to fail, the loading bar came back to 0% and the upload restarts.  
After some time, there logs appears that the fist video is inserted in the database, and the encode begins, even if the load bar is still loading for the second upload.  
And then it re-happens. Processing too long, the upload bar restart, during the third upload the second is created in the BDD, and so on until either the processing part succeed or I cancel the upload.

When canceling, launched encoding continue to runs, and I find 2 identical videos in my account. 

* **Browser console log if useful:** Nothing particular, there is no new upload request when the loading bar restart. If needed, do not hesitate to ask what is needed (perhaps getting more logs with special module?)  
* **Server log if useful (journalctl or /var/www/peertube/storage/logs):**

```
[videos.pair2jeux.tube:443] 2018-09-28 19:09:11.712 debug: Executing (c11be786-67f2-48a5-a195-59528b8ed2bb): INSERT INTO "video" ("id","uuid","name","category","licence","language","privacy","nsfw","description","support","duration","views","likes","dislikes","remote","url","commentsEnabled","waitTranscoding","state","publishedAt","channelId","createdAt","updatedAt") VALUES (DEFAULT,'8e3064b8-7c41-49d8-91c2-917a21e4c695','[FR] EUIV - Puissance Africaine - Ep25 - Stratégie d''avenir',NULL,NULL,NULL,3,false,NULL,NULL,2260,0,0,0,false,'https://videos.pair2jeux.tube/videos/watch/8e3064b8-7c41-49d8-91c2-917a21e4c695',true,true,2,'2018-09-28 19:02:54.471 +00:00',2,'2018-09-28 19:09:11.696 +00:00','2018-09-28 19:09:11.696 +00:00') RETURNING *; # First video inserted

[videos.pair2jeux.tube:443] 2018-09-28 19:09:11.829 info: Video with name [FR] EUIV - Puissance Africaine - Ep25 - Stratégie d'avenir and uuid 8e3064b8-7c41-49d8-91c2-917a21e4c695 created. # First video created  (second has already begins to upload)

[videos.pair2jeux.tube:443] 2018-09-28 19:17:55.256 debug: Checking videosAdd parameters {
  "meta": {
    "parameters": {
      "name": "[FR] EUIV - Puissance Africaine - Ep25 - Stratégie d'avenir",
      "privacy": 3,
      "nsfw": false,
      "commentsEnabled": true,
      "waitTranscoding": true,
      "channelId": 2
    },
    "files": {
      "videofile": [
        {
          "fieldname": "videofile",
          "originalname": "[FR] EUIV - Puissance Africaine - Ep25 - Stratégie d'avenir.mp4",
          "encoding": "7bit",
          "mimetype": "video/mp4",
          "destination": "/data/videos/",
          "filename": "48a17966492f6ad343cb9c620995b854.mp4",
          "path": "/data/videos/48a17966492f6ad343cb9c620995b854.mp4",
          "size": 1128650177
        }
      ]
    }
  }
} # Second video added


[videos.pair2jeux.tube:443] 2018-09-28 19:24:31.385 debug: Executing (3f367dd7-28b8-43fa-bc68-6ddfd61966b7): INSERT INTO "video" ("id","uuid","name","category","licence","language","privacy","nsfw","description","support","duration","views","likes","dislikes","remote","url","commentsEnabled","waitTranscoding","state","publishedAt","channelId","createdAt","updatedAt") VALUES (DEFAULT,'ee3df701-3abf-409c-8ee7-7d5c13ede433','[FR] EUIV - Puissance Africaine - Ep25 - Stratégie d''avenir',NULL,NULL,NULL,3,false,NULL,NULL,2260,0,0,0,false,'https://videos.pair2jeux.tube/videos/watch/ee3df701-3abf-409c-8ee7-7d5c13ede433',true,true,2,'2018-09-28 19:17:55.555 +00:00',2,'2018-09-28 19:24:31.372 +00:00','2018-09-28 19:24:31.372 +00:00') RETURNING *; # Second video added in database
```

I have discovered this bug because of users with high bandwidth, uploading 1GB video in less than 1 minutes, and thus too quick for Peertube :(

I guess the main problem is the interface does not waiting for the processing to finish. I do not know what exactly the processing part do, as the file is created on the disk (I have checked that), and the insertion in the database occurs long time after..

Perhaps I am missing something about this part. Is this something that could block the processing, or slow it?

I am open to any tests if you have ideas about that :-)

Thank you for the job on Peertube!

Regards

**Comment by Chocobozzz** [comment]
Please try this [patch](https://github.com/Chocobozzz/PeerTube/commit/8b917537af2217ad0c87d49fd2ffa693d46a499c)

**Comment by Chocobozzz** [comment]
Are you sure about the IO? We generate the torrent file, check the video metadata etc so the CPU/IO should be "high". Closing, feel free to comment after your tests!
