### ISSUE TITLE
Support two factor authentication

### ISSUE THREAD

**Issue by mkoppmann** [Chocobozzz/PeerTube#1146]
It would be great to have support for 2FA. Preferably TOTP and U2F.

Maybe I will have some time to implement this feature.

**Comment by mkoppmann** [comment]
What would be a good starting point for implementing this? Should this be implemented as a middleware?

In the first run TOTP should work together with some fallback recovery codes. Also a function for admins to remove 2FA for specific users if they can prove somehow, that they lost access to their token generator and recovery codes.

Later U2F support can be added.

**Comment by andyrtr** [comment]
There should be TOTP, U2F and WebAuthn support available over all fediverse network. Every project has similar open issues while some already have TOTP two factor authentication implemented.

**Comment by Githubuxer** [comment]
Any updates on this? I use 2Fa with Mastodon and Pixelfed, using FreeOTP app by RedHat.

Would feel better having secure account as just joined and worried about credential leak.

**Comment by test2a** [comment]
@Githubuxer i am not sure 2fa protects against credential leaks, although it is useful incase you are locked out of your account due to you forgetting the password, someone doing man in the middle attack and in those cases, you have something physical to authenticate yourself with

**Comment by kimsible** [comment]
Is there any work to implement this ? It would be a very nice feature, especially to secure admins or moderators accounts.

**Comment by OddHouseGames** [comment]
Looking forward to the implementation of this functionality. It's one of my only digital accounts that lacks any kind of 2FA.

**Comment by dwbit** [comment]
Hey there! Is this one being considered as an upcoming roadmap item? It is one of the only services that I use, that isn't protected by an additional layer of security.

**Comment by Chocobozzz** [comment]
Implemented OTP in https://github.com/Chocobozzz/PeerTube/commit/56f47830758ff8e92abcfcc5f35d474ab12fe215 https://github.com/Chocobozzz/PeerTube/commit/d12b40fb96d56786a96c06a621f3d8e0a0d24f4a https://github.com/Chocobozzz/PeerTube/commit/2166c058f34dff6f91566930d12448805d829de7 https://github.com/Chocobozzz/PeerTube/commit/a69ea13086273fc6659c153be93f0f5b37aad733 https://github.com/Chocobozzz/PeerTube/commit/a3e5f804ad821f6979e8735b0569b1209986fedc

**Comment by DiamantTh** [comment]
Hi there,

I know they say it's done when it's done. 

What is the current status of Fido2/WebAuthN? 

Greetings go out.
