### ISSUE TITLE
Adding optional ad-free monetization through Coinhive (or similar)

### ISSUE THREAD

**Issue by vavanade** [Chocobozzz/PeerTube#1149]
For on-platform monetization of content the most succesfull video sharing platform YouTube uses ads which are annoying. However having a monetization option for content is IMHO useful to compensate creator's time and effort.

A solution coming to mind is having creators take computer resources from their viewers to mine cryptocurrencies instead of running ads. I haven't done the math whether it's viable or not but I think it is an interesting idea to have on a platform like this. Coinhive already provides code for JS mining of Monero (see https://coinhive.com).

What do you think of that?

**Comment by BO41** [comment]
I like your idea of having _some_ monetization. And something new and better than ads is also nice.

But I think the whole crypto currency hype is over. Also, I am not sure if it is worth with having an video average of probably 10min.
But do some maths and tells us some numbers.

Also, if I know this correctly, coinhive takes a cut from it and you need to reach a big goal to get anything in the first place.

**Comment by rigelk** [comment]
I suggest you add a link in the "Support" section of your video to your mining platform. This way users will mine _knowing_ what they are doing.

That being said, integrating CoinHive wouldn't make it to the core of PeerTube, mainly because we don't want to maintain such an integration. You should take part in the discussion for the design of our plugin system, though.

**Comment by SerCom-KC** [comment]
In one word, that's why I choose PeerTube instead of something like https://github.com/dtube/dtube or https://github.com/ipbc-dev/bittube.
Personally but also seriously, no more cryptocurrency please.

**Comment by vavanade** [comment]
Ok, it is probably not viable as stated by Coinhive FAQ (https://coinhive.com/info/faq):

**What amount of XMR can I expect for my site?**
We currently pay 0.000037 XMR per 1Million hashes. If you have 1 Million visits a month, assume a user makes 30 hashes/s (mid range laptop) and remains on your site for 5 minutes:

(1000000 visits per month * 30 hashes/s * 5 minutes * 60 seconds)/1000000 * 0.000037 xmr = 0.333 xmr / month.

At current rate that's about 35 USD a month so more direct support of creators through something like Patreon is probably much more viable.
