### ISSUE TITLE
Add limitation video time

### ISSUE THREAD

**Issue by Dryusdan** [Chocobozzz/PeerTube#115]
Hey :)
Today, I upload video on my server and... BAM, limitation 7200s... It's very cool if we can change this limitation :)  

Regard

**Comment by Chocobozzz** [comment]
In fact I don't remember why I put this limitation. Now we have user quota I don't see any use case for this feature.

**Comment by Dryusdan** [comment]
Ok, so, you delete this feature ? ^^  
Question, user quota is per video or total storage ?

**Comment by Chocobozzz** [comment]
I think, just let this issue opened a few days if someone else has a valid use case.

User quota is for all uploaded videos by the user.

**Comment by Dryusdan** [comment]
Okay :) 

Thank for answers :)

**Comment by qsypoq** [comment]
Even on per-video storage quota it isn't valid since, depending on encoding and stuffs, a video can be shorter and still heavier than another.

Only use case i see is if a sort of ad video feature is implemented. Then you can use this to limit the ad time allowed.

**Comment by Chocobozzz** [comment]
Max duration constraint does not exist anymore: https://github.com/Chocobozzz/PeerTube/commit/c60774b05b12d262ed27d8efeb0905ac283eeebb
