### ISSUE TITLE
Upload canceled when changing Language

### ISSUE THREAD

**Issue by erdmark** [Chocobozzz/PeerTube#1150]
* **PeerTube version or URL:**
PeerTube v1.0.0-beta.15
* **Browser name/version:**
Mozilla/5.0 (X11; Linux i686 on x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
* **NodeJS version:**

* **What is the expected behaviour?**
When changing language during an upload the upload should not abort. There could be a question if I want to wait for the upload or change the language instead
* **What do you see instead?**
When changing language during an upload the upload stops at once

* **Browser console log if useful:**
* **Server log if useful (journalctl or /var/www/peertube/storage/logs):**

**Comment by Chocobozzz** [comment]
We should use `onbeforeunload` instead of a angular hook to ask the user if he really wants to leave the upload page.

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/674a66bbda7ceb7aed3c2e6aefddc2793207d94b
