### ISSUE TITLE
Problem with changing the domain

### ISSUE THREAD

**Issue by CamilleKaze** [Chocobozzz/PeerTube#1151]
* **PeerTube version or URL:** v1 beta 15
* **NodeJS version:** v8.12.0

Hi, I just installed a Peertube instance and I want to change the domain (from domain.tld to peertube.domain.tld) without starting all over again. So I changed it in /var/www/peertube/config/production.yaml and now I get : 

`warn: It seems PeerTube was started (and created some data) with another domain name. This means you will not be able to federate! Please use NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run update-host to fix this.`

Which was expected. But when i do : 
```
NODE_CONFIG_DIR=/var/www/peertube/config
NODE_ENV=production
npm run update-host
```
I get : 

```
admin@vps:/var/www/peertube/config$ NODE_CONFIG_DIR=/var/www/peertube/config
admin@vps:/var/www/peertube/config$ NODE_ENV=production
admin@vps:/var/www/peertube/config$ sudo npm run update-host
npm ERR! path /var/www/peertube/config/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/var/www/peertube/config/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-30T16_42_52_295Z-debug.log
admin@vps:/var/www/peertube/config$
```
And I get the same when I try `sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run update-host`

Here is the debug.log : 
```
  GNU nano 2.7.4           File: /var/www/peertube/.npm/_logs/2018-09-30T16_44_52_336Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'update-host' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose stack Error: ENOENT: no such file or directory, open '/var/www/peertube/config/package.json'
5 verbose cwd /var/www/peertube/config
6 verbose Linux 4.9.0-7-amd64
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "update-host"
8 verbose node v8.12.0
9 verbose npm  v6.4.1
10 error path /var/www/peertube/config/package.json
11 error code ENOENT
12 error errno -2
13 error syscall open
14 error enoent ENOENT: no such file or directory, open '/var/www/peertube/config/package.json'
15 error enoent This is related to npm not being able to find a file.
16 verbose exit [ -2, true ]
```

Can someone help me please ? I have no clue. Thank you in advance.
(btw I'm a novice, trying to learn little by little...)

**Comment by rigelk** [comment]
You are trying to execute a npm command from the wrong directory. `npm run` executes commands defined in `./package.json`. Change directory to `/var/www/peertube` where the `package.json` lies.

**Comment by CamilleKaze** [comment]
Thank you for your help. I get the same error. I can't find this file, I only have this : 
```
peertube@vps586938:~$ cd /var/www/peertube/
peertube@vps586938:~$ ls -a
.   .bash_history  .bashrc  config   .node-gyp  peertube-latest  .rnd     versions    .yarn
..  .bash_logout   .cache   .config  .npm       .profile         storage  .wget-hsts  .yarnrc
```

**Comment by CamilleKaze** [comment]
I did this : 
```
admin@vps:/var/www/peertube/peertube-latest$ sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run update-host

> peertube@1.0.0-beta.15 update-host /var/www/peertube/versions/peertube-v1.0.0-beta.15
> node ./dist/scripts/update-host.js

Updating actors.
Updating actor https://www.libedia.com/video-channels/root_channel
Updating actor https://www.libedia.com/accounts/root
Updating actor https://www.libedia.com/accounts/peertube
Updating video shares.
Updating video comments.
Updating video and torrent files.
```
So maybe it's resolved but I'm not sure because I still have :
` warn: It seems PeerTube was started (and created some data) with another domain name. This means you will not be able to federate! Please use NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run update-host to fix this.`

**Comment by rigelk** [comment]
Oh. Oh right, I assumed `/var/www/peertube` was the root of the peertube code, but you followed the production guide, sorry.

**Comment by Chocobozzz** [comment]
@CamilleKaze Please tell us:
 * What was you old domain
 * What is your new domain
 * Pastebin your production.yaml
 * Pastebin your actor table urls (in the database)

**Comment by CamilleKaze** [comment]
That's my final changes : 
Old domain : libedia.com
New domain : www.libedia.com
production.yaml : https://pastebin.com/raw/C2uqZF6g (I haven't set up smtp yet)
I'm not sure if I downloaded the right thing but here's "public.actor" from the peertube_prod database (csv format) : https://pastebin.com/raw/zWdae5sh

Thanks for your help.

**Comment by Chocobozzz** [comment]
And you still have the warning at startup? Because your urls seem okay.

**Comment by CamilleKaze** [comment]
Oh I just noticed that the logs displayed at startup include old logs... Ok so the problem is solved ^^' Thanks !
