### ISSUE TITLE
Unable to reset admin user password

### ISSUE THREAD

**Issue by FlatEarthTruther** [Chocobozzz/PeerTube#1152]
v1.0.0-beta.13

* **Browser name/version:**
Not applicable

* **NodeJS version:**
root@v1:/var/www/peertube/peertube-latest# node -v
v8.12.0

* **What is the expected behaviour?**
Admin user password resets and be able to login with admin user, in this case "root" from the web interface.

* **What do you see instead?**

root@v1:/var/www/peertube/peertube-latest# cd /var/www/peertube/peertube-latest && NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run reset-password -- -u root

> peertube@1.0.0-beta.13 reset-password /var/www/peertube/versions/peertube-v1.0.0-beta.13
> node ./dist/scripts/reset-password.js "-u" "root"

New password?
{ TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/var/www/peertube/versions/peertube-v1.0.0-beta.13/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
    at Timeout.bound (/var/www/peertube/versions/peertube-v1.0.0-beta.13/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) name: 'TimeoutError' }

* **Browser console log if useful:**
Not applicable

* **Server log if useful (journalctl or /var/www/peertube/storage/logs):**
Nothing in the logs about this issue.

**Comment by Chocobozzz** [comment]
What is your PostgreSQL version?

**Comment by FlatEarthTruther** [comment]
I have re-installed the server since then, and it seems to be working fine now.
PostgreSQL 9.6

When I had it hooked up to RDS instance the error was happening
PostgreSQL 10.4

**Comment by FlatEarthTruther** [comment]
Not sure if this is still an issue, I think it's safe to close this for now.
