### ISSUE TITLE
Import downloads torrents with more than one video, error prevents deletion

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#1153]
Peertube version : PeerTube v1.0.0-beta.13 (https://www.yiny.org)

I found this in my `/var/www/peertube/storage/videos` folder:
```
drwxr-xr-x  2 peertube peertube 4.0K Sep 29 16:45 Sicario Day Of The Soldado (2018) [BluRay] [1080p] [YTS.AM]
drwxr-xr-x  2 peertube peertube 4.0K Sep 29 16:48 Riverdale.S01E01.Chapter.One.The.Rivers.Edge.1080p.NF.WEBRip.DD5.1.x264-NTb[rarbg]
```

It seems someone used my peertube instance to seed (illegal) torrents file....

In my peertube logs: 
```
Sep 29 16:42:50 yiny peertube[1695]: [www.yiny.org:443] 2018-09-29 16:42:50.304 info: Processing torrent video import in job 22.
Sep 29 16:42:50 yiny peertube[1695]: [www.yiny.org:443] 2018-09-29 16:42:50.355 info: Importing torrent video magnet:?xt=urn:btih:2F200765BBFA5802AC2AFDF0CB71865714E833A2&dn=Sicario%3A+Day+of+the+Soldado+%
Sep 29 16:42:52 yiny peertube[1695]: [www.yiny.org:443] 2018-09-29 16:42:52.758 info: Creating job to broadcast delete of video https://www.yiny.org/videos/watch/1692d309-a668-4924-aeb3-93a17edef0e5.
Sep 29 16:42:52 yiny peertube[1695]: [www.yiny.org:443] 2018-09-29 16:42:52.820 info: Removing files of video https://www.yiny.org/videos/watch/1692d309-a668-4924-aeb3-93a17edef0e5.
Sep 29 16:42:52 yiny peertube[1695]: [www.yiny.org:443] 2018-09-29 16:42:52.894 error: Cannot execute job 22 in queue video-import. {
Sep 29 16:42:52 yiny peertube[1695]:   "meta": {
Sep 29 16:42:52 yiny peertube[1695]:     "payload": {
Sep 29 16:42:52 yiny peertube[1695]:       "type": "magnet-uri",
Sep 29 16:42:52 yiny peertube[1695]:       "videoImportId": 22,
Sep 29 16:42:52 yiny peertube[1695]:       "magnetUri": "magnet:?xt=urn:btih:2F200765BBFA5802AC2AFDF0CB71865714E833A2&dn=Sicario%3A+Day+of+the+Soldado+%282018%29+%5B1080p%5D+%5BYTS.AG%5D&tr=udp%3A%2F%2Fglo
Sep 29 16:42:52 yiny peertube[1695]:     },
Sep 29 16:42:52 yiny peertube[1695]:     "err": {
Sep 29 16:42:52 yiny peertube[1695]:       "stack": "Error: The number of files is not equal to 1 for magnet:?xt=urn:btih:2F200765BBFA5802AC2AFDF0CB71865714E833A2&dn=Sicario%3A+Day+of+the+Soldado+%282018%2
Sep 29 16:42:52 yiny peertube[1695]:       "message": "The number of files is not equal to 1 for magnet:?xt=urn:btih:2F200765BBFA5802AC2AFDF0CB71865714E833A2&dn=Sicario%3A+Day+of+the+Soldado+%282018%29+%5B
Sep 29 16:42:52 yiny peertube[1695]:     }
Sep 29 16:42:52 yiny peertube[1695]:   }
Sep 29 16:42:52 yiny peertube[1695]: }
```

My users quota are limited to 500Mo, and these files use up to 4Go. 
The used quota of the user I suspect doing this is 0. Theses videos are not counted.

I just disabled torrent importation. 
How can I clean up my storage ? By using the prune-storage batch ?

I don't know if my server is still seeding this torrent... How can I know ?

**Comment by rigelk** [comment]
@JohnXLivingston if you deem this is a security issue please use the damn https://github.com/Chocobozzz/PeerTube/blob/develop/SECURITY.md and don't disclose it publicly but rather let us time to organise the patching and updating procedure…

**Comment by JohnXLivingston** [comment]
Oops, sorry. Can you delete this issue ? I will send an email

**Comment by rigelk** [comment]
@JohnXLivingston no, I can't. Maybe @Chocobozzz can, but it's likely we have to contact GitHub now.

**Comment by Nutomic** [comment]
@rigelk You can just edit the original post and delete the text.

**Comment by rigelk** [comment]
@Nutomic versions of the text are public…

**Comment by Nutomic** [comment]
Oh that's right, I'm pretty sure Chocobozzz can't delete that either. You should go ahead and contact Github.

Also, you should add a note to the issue template regarding security problems (how to report them).

**Comment by rigelk** [comment]
Okay. Reviewing the issue, the bug cannot be leveraged to seed the imported files: the job fails halfway through and doesn't create an accessible entry. However it's clearly an annoyance as the files should be removed lest the check doesn't work (which it should).

@Nutomic that's a good idea :+1:

**Comment by Chocobozzz** [comment]
> How can I clean up my storage ? By using the prune-storage batch ?

Yes

> I don't know if my server is still seeding this torrent... How can I know ?

At the end of the import, peertube stops seeding the file.

I think the issue regarding the files deletion when the torrent files !== 1 is already fixed in `develop`. But I just fixed the files deletion when the quota is reached in https://github.com/Chocobozzz/PeerTube/commit/e95e0463d8ef0d0a690e716df93c3c78b74737af

**Comment by JohnXLivingston** [comment]
I just check my bandwidth monitoring. During 24 hours, my server was uploading nearly 100mbps. It stopped when I restarted the peertube service yesterday (after cutting off the torrent import feature). 
Are you sure that peertube stops seeding the file after import ? Even in my case : multiple files in the torrent, so it can't be imported correctly.

**Comment by JohnXLivingston** [comment]
![image](https://user-images.githubusercontent.com/38844060/46279905-b80f0f00-c56a-11e8-8462-cbacac390d9b.png)
Here is the bandwidth graph.
Torrents were uploaded the 29th September, at 16:42. And I restarted the service the 30th at 22PM approximatly.

**Comment by Chocobozzz** [comment]
No, versions <= 13
