### ISSUE TITLE
Unable to create user with same email address, error Object Object

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#116]
Hello !

When creating new user on instance (https://peertube.drycat.fr), if I use same email address for both users, creation failed (which could be normal), but error is not obvious: [Object Object]

I think error message could be improved?

Thank you!

Regards

**Comment by qsypoq** [comment]
The [object object] error is happening with many user-input errors, maybe we can use this issue to list them all ?

**Comment by LecygneNoir** [comment]
At the moment, bug #114 has the same error

Have you seen other location with it?

**Comment by Chocobozzz** [comment]
Thanks. You're right @qsypoq, I'll fix it.

**Comment by Chocobozzz** [comment]
Should be fixed on latest develop: https://github.com/Chocobozzz/PeerTube/commit/f73544839586d5e50529617f3649a84ac9e0ab86
