### ISSUE TITLE
Dark theme: shedule agenda is difficult to read

### ISSUE THREAD

**Issue by Zykino** [Chocobozzz/PeerTube#1160]
* **PeerTube version or URL:** PeerTube v1.0.0-beta.13
* **Browser name/version:** Firefox Stable (62.0, 64bits)
* **NodeJS version:** ???

* **What is the expected behavior?**
When using the dark theme and scheduling a publication, I should be able to see the calendar and select easily the day I want.
* **What do you see instead?**
![calendar with wight background AND text](https://user-images.githubusercontent.com/3809938/46313689-c855d700-c5c8-11e8-8154-8eba9e56fece.png)

**Comment by tomamplius** [comment]
maybe same issue on page list
![selection_033](https://user-images.githubusercontent.com/6951820/50106847-41acaf80-0231-11e9-8843-95c8cf5b6482.jpg)
![selection_034](https://user-images.githubusercontent.com/6951820/50106848-41acaf80-0231-11e9-908a-d32adee7f26e.jpg)

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/aa87909287c4f4d38696244e32828265b040c7d5
