### ISSUE TITLE
Update user info reset password

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#117]
Hello !

Server is : https://peertube.drycat.fr
For what I know, it runs the latest peertube version
(Should I create test user on demo server to validate?)

* Browser name/version: Vivaldi 1.10 (tested also with firefox 55)

Problem is, once I update my user information through the "Update my informations" field, it resets the password which is in another field

It seems that using the update button apply all fields, even if password is empty, and doing so, invalidate credentials as it is impossible to log in with empty password.

Please tell if I can provide more details or are unclear in my description :-)

Thank you for this precious project!

Regards,

**Comment by Chocobozzz** [comment]
Thanks for the report. Should be fixed in last develop: https://github.com/Chocobozzz/PeerTube/commit/59557c4663814b05fb3b2209c486c73a432a65b5
