### ISSUE TITLE
Import video script - tags/description/NSFW

### ISSUE THREAD

**Issue by hellomotow** [Chocobozzz/PeerTube#1170]
Is it possible to add tags, description or if the video is NSFW with the import script? 

node dist/server/tools/peertube-import-videos.js

**Comment by Chocobozzz** [comment]
Nope

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/1205823fece15f249e0dbad42e096cf9b81c3ba5
