### ISSUE TITLE
Version is printing unknown version with rc.1

### ISSUE THREAD

**Issue by Jorropo** [Chocobozzz/PeerTube#1176]
* **PeerTube version or URL:**
rc.1
https://peertube.jorropo.ovh/
* **Browser name/version:**
Firefox 62

* **What is the expected behaviour?**
In the bottom of the page it should print current version
* **What do you see instead?**
Unknown is printed

**Comment by rigelk** [comment]
Yes, we are on it :) rc.2 should follow right after

**Comment by rigelk** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/499d9015955c0cedd094fbe814dee6235e639627.
