### ISSUE TITLE
Can't install everytime something missing...

### ISSUE THREAD

**Issue by 15w34r0n3D4y** [Chocobozzz/PeerTube#118]
An unexpected error occurred: "https://registry.yarnpkg.com/asn1.js/-/asn1.js-4.10.0.tgz: Request failed \"404 Not Found\""....

**Comment by Chocobozzz** [comment]
Please retry with the latest develop branch.

**Comment by 15w34r0n3D4y** [comment]
I try develop branc and it works, thank you.

**Comment by anmol26s** [comment]
I still have this issue.

**Comment by Chocobozzz** [comment]
With the develop branch?

**Comment by anmol26s** [comment]
The default branch is not the dev branch ?
