### ISSUE TITLE
Remove instances from followers list

### ISSUE THREAD

**Issue by techknowlogick** [Chocobozzz/PeerTube#1180]
Followers can't currently be removed via the admin interface.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/0e9c48c2edbb3871b0ca3ccd6718f2c99f9760b6 & https://github.com/Chocobozzz/PeerTube/commit/0dc647775881eb1378b213a530996cd096de24ea
