### ISSUE TITLE
Number of views is different for each instance

### ISSUE THREAD

**Issue by Angedestenebres** [Chocobozzz/PeerTube#1181]
Hello,

After a reporting of one of our users, I checked and see the same thing.
I did a search on opened and closed tickets and I fount this one: https://github.com/Chocobozzz/PeerTube/issues/548

We will take [this video](https://video.tedomum.net/videos/watch/55664db5-69f8-42c3-a722-ed7d70dca8dd) as example but this issue also happens with other videos.

On our instance ([TeDomum one](https://video.tedomum.net/videos/trending)), the number of view is currently 184 :

![capture d ecran_2018-10-03_17-21-50](https://user-images.githubusercontent.com/21110485/46421722-01aa5600-c733-11e8-846b-f8330fa1ab0b.png)

On  [exode.me](https://exode.me/) instance, it's 263 :

![exode](https://user-images.githubusercontent.com/21110485/46421738-12f36280-c733-11e8-92e6-2241467e302b.png)

and on [Datamol TV](https://tv.datamol.org/), we have 172 :

![datamol](https://user-images.githubusercontent.com/21110485/46421759-1edf2480-c733-11e8-9731-e69f35a44a5d.png)

Is the number of views related to the instance and not the federated number of views? 

Thanks in advance for your answer.

**Comment by Angedestenebres** [comment]
In case you need an example of video hosted by another instance, you can check with this one : https://video.tedomum.net/videos/watch/616d645b-7c99-4b76-ba77-3c4c29bf5d22

On our instance 237 views :

![ff](https://user-images.githubusercontent.com/21110485/46422884-9615b800-c735-11e8-9a60-c55752d8fc6f.png)

And on Datamol TV 213 views :

![ff-datamol](https://user-images.githubusercontent.com/21110485/46422945-b0e82c80-c735-11e8-86c2-c6a43550d82e.png)

**Comment by Chocobozzz** [comment]
Thanks for the issue.

Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/030177d246834fdba89be9bbaeac497589b47102
