### ISSUE TITLE
mobile css is strange

### ISSUE THREAD

**Issue by BO41** [Chocobozzz/PeerTube#1183]
the search bar gets bigger on the last media query
![screenshot_2018-10-03 test 1](https://user-images.githubusercontent.com/29450609/46428374-12af9300-c744-11e8-961f-393f4c59cece.png)
~190px at >600px width
![screenshot_2018-10-03 test 2](https://user-images.githubusercontent.com/29450609/46428375-12af9300-c744-11e8-9640-135d3e505b10.png)
~215px at < 600px width

this is strange and forces the logo to go away if the window keeps getting smaller

**Comment by BO41** [comment]
as you see, there is rather a big search bar, than the PeerTube logo

![image](https://user-images.githubusercontent.com/29450609/46430342-ffeb8d00-c748-11e8-9d0b-291fe8119d11.png)

**Comment by buoyantair** [comment]
Do you think having a larger Input element on mobile devices is better though? Given that most of them are touch based? :thinking:

**Comment by rigelk** [comment]
this was recently fixed in https://github.com/Chocobozzz/PeerTube/commit/8a979d73c3343ecf07b4e6411fa2a6783cd0a3b0.
