### ISSUE TITLE
Replace References to 'Mastodon'

### ISSUE THREAD

**Issue by zcdunn** [Chocobozzz/PeerTube#1184]
PeerTube version or URL: PeerTube v1.0.0-beta.16
Browser name/version: Firefox
NodeJS version: ?

* **What is the expected behaviour?**
UI says 'Subscribe with a fediverse account:'
* **What do you see instead?**
UI says 'Subscribe with a Mastodon account:'

PeerTube federates with ActivityPub so it should use 'ActivityPub' or 'fediverse' to reference non PeerTube accounts, since users can interact from software other than PeerTube and Mastodon.

![image](https://user-images.githubusercontent.com/7121969/46431098-dfa3da00-c718-11e8-9b31-1da0dbfa152d.png)

**Comment by rigelk** [comment]
Actually the first version was very platform-neutral :) but user tests showed most people didn't understand what ActivityPub was, or tried to use their PeerTube handle, which isn't (yet) possible...

**Comment by headache-booth** [comment]
Maybe "Subscribe with other fediverse software" might be a good option then?

**Comment by rigelk** [comment]
As soon as PeerTube supports it, we'll try again

**Comment by rosbeef** [comment]
follow with mastodon is not clear. 
follow with activitypub was better maybe somthing like follow with activitypub (mastodon,pleroma, ...)

or simpler follow with and a list of socials activitypub logo

-----------------------
| follow with :       |
| Mas | Ple | PTB |
| textbox              |
______________

It could be interesting to be able to follow with an other peertube instance account.

**Comment by kingemir** [comment]
So the reviewer of the proposed pull request https://github.com/Chocobozzz/PeerTube/pull/3334 wishes that the redirection to subscription is tested with all ActivityPub platforms before he can acknowledge such a change in the wording. 
I can confirm that the redirection to subscription works for following platforms: **Hubzilla** (Versions 5.0.1 and 5.0.2)

**Comment by moussieri** [comment]
Redirection to subscription to peertube a channel works also for following platforms: Zap (Zot protocol) Version 20.11.23

**Comment by Chocobozzz** [comment]
Done in https://github.com/Chocobozzz/PeerTube/pull/3598
