### ISSUE TITLE
Watch history page

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#1199]
In a dedicated page, see the videos we (as a user) watched.

**Comment by McFlat** [comment]
+1 This would be a nice feature to have, so that users don't have to go find a video they saw some months ago but is on their mind and they can't remember the name of it etc.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/8b9a525a180cc9f3a98c334cc052dcfc8f36dcd4 & https://github.com/Chocobozzz/PeerTube/commit/80bfd33c0bf910e2cfdd3270b14ba9eddd90e2e8
