### ISSUE TITLE
Ability to set a custom footer to override the default footer

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#1208]
There needs to be a way to set a custom Footer, just like setting custom CSS and custom JavaScript.

Admins may want a clean way to override the default footer which has the software version and commit hash in it with their own footer for security reasons.

**Comment by rigelk** [comment]
Showing the version you run is quite important for users to have an idea of the code running. It's important for the transparency of the service, which could be improved by linking to your repository, if you maintain a small fork for instance.

Now, correct me if I'm wrong, but I think hiding the commit is security by obscurity. Showing it is not really asking for hacking either. And the version and commit number are at least also shown in the `/api/v1/config` endpoint, too. My point is, we gain little to loose transparency :slightly_smiling_face:

**Comment by McFlat** [comment]
What about the ability to add your own message in the footer, like a link to the root of the site or a link to the privacy policy or terms of service. What if someone wants to hide the footer altogether, the api still exposes all version numbers anyway, most users don't need to see them and if they want to see it they can look at the api response.

**Comment by McFlat** [comment]
If we add this and the ability to customize the logo and the colors and fonts then it would be better to separate out this stuff into a `Customizations` tab, instead of keeping it in the `Advanced configuration` tab.

**Comment by McFlat** [comment]
Here is how I'm currently hiding the footer, but a user can still view-source in order to see it, still I wish I could just replace the footer with my own footer instead of just hiding it.

```
footer.row a{display: none;} footer.row {visibility: hidden;}
```

**Comment by ldidry** [comment]
Just mentionning #1235 as it may lead to footer removal.

**Comment by Chocobozzz** [comment]
You can use the plugin system or custom JS/CSS fields to override the current footer.
