### ISSUE TITLE
Divergent version number

### ISSUE THREAD

**Issue by nicolashmln** [Chocobozzz/PeerTube#1209]
**What happened?**
I use the docker `production-stretch` for my peertube instance. The version shown on the website is beta 9 but I have functionalities from upper version (dark mode and redundancy for example). I looked on the [instance list](https://instances.joinpeertube.org/instances), it says beta 14 for mine. I looked in the docker container and the `package.json` says rc1.
Any thoughts?

**Additional information**
* PeerTube URL: https://megatube.lilomoino.fr/

**Comment by Chocobozzz** [comment]
Hello,

The last production image build failed (rc2). I just triggered another build. Retry to pull tomorrow or use the rc2 image :)
