### ISSUE TITLE
Error "ICE failed, add a TURN server"

### ISSUE THREAD

**Issue by arxcode** [Chocobozzz/PeerTube#121]
When I try to watch https://peertube.cpy.re/videos/watch/d2a5ec78-5f85-4090-8ec5-dc1102e022ea, I receive an intimidating red error box: "Error / Connection error: Ice connection failed."

The video seems to stream normally, though.

The console log shows "ICE failed, add a TURN server and see about:webrtc for more details".

Do you need access to the about:webrtc data as well? If so, let me know and I can email it (it contains my and other people's IP addresses, so I don't want to upload it publicly).

* Browser name/version: Firefox 57.0 (64-bit) on Windows 10
* Console log if useful (Gist/Pastebin...): "ICE failed, add a TURN server and see about:webrtc for more details"

**Comment by Chocobozzz** [comment]
Hi,

Yes I have the same error and especially with Firefox. I need to check why.

But the user does not care of this error, so I'll just hide it on the UI (will be still available from the console though).

**Comment by Chocobozzz** [comment]
Fixed: https://github.com/Chocobozzz/PeerTube/commit/7dbdc3bace5fce434d59ccb76b2e8c699cd07c1c
