### ISSUE TITLE
Ability to set main colors and fonts to override the default colors and fonts

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#1216]
There needs to be a way to set a custom colors and fonts, just like setting custom CSS and custom JavaScript.

Admins may want a clean way to override the default colors, instead of using JavaScript or CSS to change them.

```
body {
  /*** theme ***/
  // now beware node-sass requires interpolation
  // for css custom properties #{$var}
  --mainColor: #{$orange-color};
  --mainHoverColor: #{$orange-hoover-color};
  --mainBackgroundColor: #{$bg-color};
  --mainForegroundColor: #{$fg-color};
  --menuBackgroundColor: #{$menu-background};
  --menuForegroundColor: #{$menu-color};
  --submenuColor: #{$sub-menu-color};
  --inputColor: #{$input-background-color};
  --inputPlaceholderColor: #{$input-placeholder-color};

  font-family: $main-fonts;
  font-weight: $font-regular;
  color: var(--mainForegroundColor);
  font-size: 14px;
}
```

Would be nice to allow admins to modify the mainColor and mainHoverColor, etc.

**Comment by McFlat** [comment]
Here is the custom CSS I'm having to apply in order to change the main color. Kind of funky, but it works, I wish there was a better way without modifying to core sass styles and build to achieve it.

```
document.body.style.setProperty('--mainColor', '#E8252D');
document.body.style.setProperty('--mainHoverColor', '#B52325');
```

**Comment by Chocobozzz** [comment]
If you want to override variables, it should be 

```
body#custom-css {
  --mainColor: #{$orange-color};
  --mainHoverColor: #{$orange-hoover-color};
  --mainBackgroundColor: #{$bg-color};
  --mainForegroundColor: #{$fg-color};
  --menuBackgroundColor: #{$menu-background};
  --menuForegroundColor: #{$menu-color};
  --submenuColor: #{$sub-menu-color};
  --inputColor: #{$input-background-color};
  --inputPlaceholderColor: #{$input-placeholder-color};
}
```

We should improve the help tooltip

**Comment by McFlat** [comment]
But does that mean I have to override them in the `sass/include_variables.scss` and then compile those assets?

**Comment by Chocobozzz** [comment]
Oup's sorry I edited my comment

**Comment by rigelk** [comment]
@McFlat no, that can be done in the custom CSS box in the administration menu, in the advanced settings.

**Comment by Chocobozzz** [comment]
Documented in https://framagit.org/framasoft/peertube/documentation/commit/4359d9ae9cc0719e33b19eef97f028e76c086b2f
