### ISSUE TITLE
Ability to add custom pages and menus

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#1218]
There needs to be a way to allow admins to create custom pages. A custom page could be created by placing html code into a TextArea and associated with a routing endpoint. Which would then show up in the menu on the left, below the other menu items, maybe having a whole other menu section would be better in this case. If adding custom pages, then would have to add custom menus and allow admins to re-arrange the order of the menu items and what pages are in the menu and what the Menu header would say, unless it would just all go into the `More` menu near the `About` menu item. Initially if we add pages would be nice, and then later if we add menus that would be a plus.

Let me know what you think. I hope to be able to help you guys make this software better for everyone who uses it.

**Comment by scanlime** [comment]
This seems really handy; while I'm sure the PeerTube devs would rather not be maintaining an entire content management system, a simple way to display perhaps a few Markdown documents with instance rules and information seems key to having a healthy community!

**Comment by McFlat** [comment]
I thought of something else this morning that would be required for the custom pages, the ability to have translated custom pages, to allow the admin to have separate translations for the custom pages. If anything the admin can just create more pages with the language code in the route for the page. Something like `/pages/${custom_page_route_path}` and the `custom_page_route_path` could be prefixed with the language code `en/privacy-policy` or `fr/privacy-policy` or even deeper nesting of the route path `en/privacy/policy` or `en/report/abuse` and `fr/report/abuse`.

The pages could all be markdown entered into a textarea, no editor functionality required, the admins can jut prepare the markdown in an external markdown editor and paste the text in for the initial version of this feature. Just would be nice to have the ability to name the pages and associate a custom route for them, under the top level `/pages/` route. Also if the name wouldn't be the actual name the user sees, but only for admin to know the different between the pages, the admin would just add the title in the text etc.

**Comment by McFlat** [comment]
Also would be nice to just set a name and url, so to be able to just add a page that can possibly be another subdomain or another site altogether. So if the page markdown text is empty then require a url, or if url is empty require markdown text.

Fields could be something along these lines:
- Name (visible only to admin)
- Title (visible to public) as the text of the link to the route or url they will navigate to
- url (this field can be either a route or a full url to another subdomain or another site)
- markdown text (the markdown to parse to make up the body of the page, in this case it would be a route and no url to some other site or subdomain)

**Comment by Chocobozzz** [comment]
Closing in favour of https://github.com/Chocobozzz/PeerTube/issues/3582 and https://github.com/Chocobozzz/PeerTube/issues/2665
