### ISSUE TITLE
Admin should limit video history size

### ISSUE THREAD

**Issue by Jorropo** [Chocobozzz/PeerTube#1220]
An admin should place a limit on viewed video history size to prevent db size to grow to much.

**Comment by Chocobozzz** [comment]
Limiting by date is fine, users would better understand why their history stopped 6 months ago for example

**Comment by McFlat** [comment]
I think it would be better if the admin sets a hard limit on the history while users can either disable history or enable it to any value up to the hard limit that the admin set.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/8f0bc73d7d5f4c88cbc5588a0ece12b3855c8f98
