### ISSUE TITLE
Report length limit too small and inconsistently enforced

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#1225]
Noticed this issue on peertube.social, running PeerTube v1.0.0-rc.2

The report description length claims to be limited to 300 characters. This seems unnecessarily small, and I was already running into this limit just trying to link to three places where a video was reposted:

![screen shot 2018-10-08 at 11 15 28 am](https://user-images.githubusercontent.com/923812/46626307-cd94b380-caeb-11e8-8d38-85101aea3b70.png)

Then I tried shortening the message, and it failed with an internal server error, indicating that perhaps the length limits enforced by the client vs the server are inconsistent. After shortening it even further, the submit succeeded.

**Comment by Nutomic** [comment]
Did you submit it with newlines? Cause it seems they got lost somewhere along the way:

![screenshot_20181008_134208](https://user-images.githubusercontent.com/1044450/46627429-12c2e080-cb00-11e8-85a0-db1149d41437.png)

It might also be a good idea if users could report multiple videos at once (or report an entire account).

**Comment by scanlime** [comment]
Yes, I included newlines. Is it interpreting the box as plain HTML i wonder, rather than some kind of preformatted text?

**Comment by Nutomic** [comment]
That seems to be it, if I inspect the HTML directly, it has newlines.

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1506307f2f903ce0f80155072a33345c702b7c76
