### ISSUE TITLE
run docker image 

### ISSUE THREAD

**Issue by adtrytech** [Chocobozzz/PeerTube#1227]
Hi,

**What happened?**
I run the below command :
"docker run --publish=9000:9000 chocobozzz/peertube"
(docker version: 18.06.1-ce)
Then, I can browse the web ui by visiting the "http://hostIP:9000".
But, I can't login to it(root/sasajoku) and there is an error message shows:
(the password "sasajoku" is got from Console output when I launch this docker image)
"Error 
Cannot retrieve OAuth Client credentials: Server error. . Ensure you have correctly configured PeerTube(config/ directory), in particular the "webserver" section"

**What do you expect to happen instead?**
I hope that I can upload, browse and view the videos within the Peertube service.
Is there a tutorial or user guide that can help me to use this docker image to launch a Peertube service?

Thank you very much.

**Comment by adtrytech** [comment]
Hi ,

I also follow the "https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/docker.md" guide to install the Peertube on my machine. But I still couldn't succeed.

Dump the error message and hope someone can help me to resolve it. Finally, I need to use the "docker stack deployment ..." command to deploy the Peertube in my Swarm cluster.

Thanks again!

[message]
# docker-compose up
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating peertube_postgres_1      ... done
Creating peertube_redis_1         ... done
Creating peertube_reverse-proxy_1 ... done
Creating peertube_peertube_1      ... done
Attaching to peertube_redis_1, peertube_postgres_1, peertube_reverse-proxy_1, peertube_peertube_1
redis_1          | 1:C 09 Oct 06:38:03.677 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1          | 1:C 09 Oct 06:38:03.677 # Redis version=4.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1          | 1:C 09 Oct 06:38:03.677 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1          | 1:M 09 Oct 06:38:03.679 * Running mode=standalone, port=6379.
redis_1          | 1:M 09 Oct 06:38:03.679 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
postgres_1       | 2018-10-09 06:38:03.841 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1       | 2018-10-09 06:38:03.841 UTC [1] LOG:  listening on IPv6 address "::", port 5432
redis_1          | 1:M 09 Oct 06:38:03.679 # Server initialized
redis_1          | 1:M 09 Oct 06:38:03.679 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
postgres_1       | 2018-10-09 06:38:03.854 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1       | 2018-10-09 06:38:03.879 UTC [20] LOG:  database system was interrupted; last known up at 2018-10-09 06:32:40 UTC
postgres_1       | 2018-10-09 06:38:04.244 UTC [20] LOG:  database system was not properly shut down; automatic recovery in progress
redis_1          | 1:M 09 Oct 06:38:03.679 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1          | 1:M 09 Oct 06:38:03.679 * DB loaded from disk: 0.000 seconds
redis_1          | 1:M 09 Oct 06:38:03.679 * Ready to accept connections
postgres_1       | 2018-10-09 06:38:04.249 UTC [20] LOG:  redo starts at 0/17CFB10
postgres_1       | 2018-10-09 06:38:04.249 UTC [20] LOG:  invalid record length at 0/17CFBF0: wanted 24, got 0
postgres_1       | 2018-10-09 06:38:04.249 UTC [20] LOG:  redo done at 0/17CFBB8
postgres_1       | 2018-10-09 06:38:04.282 UTC [1] LOG:  database system is ready to accept connections
peertube_1       |
peertube_1       | > peertube@1.0.0-rc.2 start /app
peertube_1       | > node dist/server
peertube_1       |
reverse-proxy_1  | time="2018-10-09T06:38:05Z" level=error msg="Unable to obtain ACME certificate for domains \"<MY DOMAIN>\" : cannot get ACME client acme: Error 400 - urn:ietf:params:acme:error:invalidEmail - Error creating new account :: not a valid e-mail address"
postgres_1       | 2018-10-09 06:38:06.138 UTC [27] FATAL:  role "postgres_user" does not exist
peertube_1       | [domain.tld:443] 2018-10-09 06:38:06.161 error: Cannot start application. {
peertube_1       |   "meta": {
peertube_1       |     "err": {
peertube_1       |       "stack": "SequelizeConnectionError: role \"postgres_user\" does not exist\n    at connection.connect.err (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:128:24)\n    at Connection.connectingErrorHandler (/app/node_modules/pg/lib/client.js:123:14)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:123:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:601:20)",
peertube_1       |       "message": "role \"postgres_user\" does not exist",
peertube_1       |       "name": "SequelizeConnectionError",
peertube_1       |       "parent": {
peertube_1       |         "stack": "error: role \"postgres_user\" does not exist\n    at Connection.parseE (/app/node_modules/pg/lib/connection.js:553:11)\n    at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:378:19)\n    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:119:22)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:601:20)",
peertube_1       |         "message": "role \"postgres_user\" does not exist",
peertube_1       |         "name": "error",
peertube_1       |         "length": 105,
peertube_1       |         "severity": "FATAL",
peertube_1       |         "code": "28000",
peertube_1       |         "file": "miscinit.c",
peertube_1       |         "line": "504",
peertube_1       |         "routine": "InitializeSessionUserId"
peertube_1       |       },
peertube_1       |       "original": {
peertube_1       |         "stack": "error: role \"postgres_user\" does not exist\n    at Connection.parseE (/app/node_modules/pg/lib/connection.js:553:11)\n    at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:378:19)\n    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:119:22)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:601:20)",
peertube_1       |         "message": "role \"postgres_user\" does not exist",
peertube_1       |         "name": "error",
peertube_1       |         "length": 105,
peertube_1       |         "severity": "FATAL",
peertube_1       |         "code": "28000",
peertube_1       |         "file": "miscinit.c",
peertube_1       |         "line": "504",
peertube_1       |         "routine": "InitializeSessionUserId"
peertube_1       |       }
peertube_1       |     }
peertube_1       |   },
peertube_1       |   "err": {
peertube_1       |     "stack": "SequelizeConnectionError: role \"postgres_user\" does not exist\n    at connection.connect.err (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:128:24)\n    at Connection.connectingErrorHandler (/app/node_modules/pg/lib/client.js:123:14)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:123:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:601:20)",
peertube_1       |     "message": "role \"postgres_user\" does not exist",
peertube_1       |     "name": "SequelizeConnectionError",
peertube_1       |     "parent": {
peertube_1       |       "stack": "error: role \"postgres_user\" does not exist\n    at Connection.parseE (/app/node_modules/pg/lib/connection.js:553:11)\n    at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:378:19)\n    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:119:22)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:601:20)",
peertube_1       |       "message": "role \"postgres_user\" does not exist",
peertube_1       |       "name": "error",
peertube_1       |       "length": 105,
peertube_1       |       "severity": "FATAL",
peertube_1       |       "code": "28000",
peertube_1       |       "file": "miscinit.c",
peertube_1       |       "line": "504",
peertube_1       |       "routine": "InitializeSessionUserId"
peertube_1       |     },
peertube_1       |     "original": {
peertube_1       |       "stack": "error: role \"postgres_user\" does not exist\n    at Connection.parseE (/app/node_modules/pg/lib/connection.js:553:11)\n    at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:378:19)\n    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:119:22)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:601:20)",
peertube_1       |       "message": "role \"postgres_user\" does not exist",
peertube_1       |       "name": "error",
peertube_1       |       "length": 105,
peertube_1       |       "severity": "FATAL",
peertube_1       |       "code": "28000",
peertube_1       |       "file": "miscinit.c",
peertube_1       |       "line": "504",
peertube_1       |       "routine": "InitializeSessionUserId"
peertube_1       |     }
peertube_1       |   }
peertube_1       | }
peertube_1       | npm ERR! code ELIFECYCLE
peertube_1       | npm ERR! errno 255
peertube_1       | npm ERR! peertube@1.0.0-rc.2 start: `node dist/server`
peertube_1       | npm ERR! Exit status 255
peertube_1       | npm ERR!
peertube_1       | npm ERR! Failed at the peertube@1.0.0-rc.2 start script.
peertube_1       | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
peertube_1       |
peertube_1       | npm ERR! A complete log of this run can be found in:
peertube_1       | npm ERR!     /home/peertube/.npm/_logs/2018-10-09T06_38_06_177Z-debug.log
reverse-proxy_1  | time="2018-10-09T06:38:08Z" level=error msg="undefined backend 'backend-peertube-peertube' for frontend frontend-Host-domain-tld-0. Skipping frontend frontend-Host-domain-tld-0..."

**Comment by Aldarone** [comment]
Don't mind me

**Comment by adtrytech** [comment]
Hi ,

I also follow the "https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/docker.md" guide to install the Peertube on my machine. But I still couldn't succeed.
Finally, I need to use the "docker stack deployment ..." command to deploy the Peertube in my Swarm cluster.

Problem:
1.
I can't use the account(root/duvelexuveliweqa) get from running messages to login to the http://hostIP:9000  (I had mapped port 9000 to 9000)
peertube_1       | [domain.tld:443] 2018-10-09 07:09:21.085 info: Username: root
peertube_1       | [domain.tld:443] 2018-10-09 07:09:21.085 info: User password: duvelexuveliweqa

2.
When I browse the Peertube Web page, it popup an error message at the right-down corner
"Error  Cannt retrieve OAuth Client credentials:.Ensure you have correctly configured PeerTube(config/directory), in particular the webserver section"

Thanks again!

Dump the message and hope someone can help me to resolve it. 
run command " docker-compose up" and get following messages:-------------------------------------
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating peertube_reverse-proxy_1 ... done
Creating peertube_postgres_1      ... done
Creating peertube_redis_1         ... done
Creating peertube_peertube_1      ... done
Attaching to peertube_redis_1, peertube_postgres_1, peertube_reverse-proxy_1, peertube_peertube_1
postgres_1       | The files belonging to this database system will be owned by user "postgres".
postgres_1       | This user must also own the server process.
postgres_1       |
postgres_1       | The database cluster will be initialized with locale "en_US.utf8".
redis_1          | 1:C 09 Oct 07:09:17.368 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1          | 1:C 09 Oct 07:09:17.368 # Redis version=4.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1          | 1:C 09 Oct 07:09:17.368 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
postgres_1       | The default database encoding has accordingly been set to "UTF8".
redis_1          | 1:M 09 Oct 07:09:17.370 * Running mode=standalone, port=6379.
postgres_1       | The default text search configuration will be set to "english".
postgres_1       |
postgres_1       | Data page checksums are disabled.
postgres_1       |
redis_1          | 1:M 09 Oct 07:09:17.370 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1          | 1:M 09 Oct 07:09:17.370 # Server initialized
redis_1          | 1:M 09 Oct 07:09:17.370 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1          | 1:M 09 Oct 07:09:17.370 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1          | 1:M 09 Oct 07:09:17.370 * Ready to accept connections
postgres_1       | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1       | creating subdirectories ... ok
postgres_1       | selecting default max_connections ... 100
postgres_1       | selecting default shared_buffers ... 128MB
postgres_1       | selecting dynamic shared memory implementation ... posix
postgres_1       | creating configuration files ... ok
postgres_1       | running bootstrap script ... ok
postgres_1       | performing post-bootstrap initialization ... sh: locale: not found
postgres_1       | 2018-10-09 07:09:17.858 UTC [28] WARNING:  no usable system locales were found
peertube_1       |
peertube_1       | > peertube@1.0.0-rc.2 start /app
peertube_1       | > node dist/server
peertube_1       |
postgres_1       | ok
postgres_1       | syncing data to disk ... ok
postgres_1       |
postgres_1       | Success. You can now start the database server using:
postgres_1       |
postgres_1       |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1       |
postgres_1       |
postgres_1       | WARNING: enabling "trust" authentication for local connections
postgres_1       | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1       | --auth-local and --auth-host, the next time you run initdb.
postgres_1       | waiting for server to start....2018-10-09 07:09:18.481 UTC [32] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1       | 2018-10-09 07:09:18.508 UTC [33] LOG:  database system was shut down at 2018-10-09 07:09:18 UTC
postgres_1       | 2018-10-09 07:09:18.512 UTC [32] LOG:  database system is ready to accept connections
postgres_1       |  done
postgres_1       | server started
postgres_1       | CREATE DATABASE
postgres_1       |
postgres_1       |
postgres_1       | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1       |
postgres_1       | waiting for server to shut down....2018-10-09 07:09:18.847 UTC [32] LOG:  received fast shutdown request
postgres_1       | 2018-10-09 07:09:18.850 UTC [32] LOG:  aborting any active transactions
postgres_1       | 2018-10-09 07:09:18.850 UTC [32] LOG:  worker process: logical replication launcher (PID 39) exited with exit code 1
postgres_1       | 2018-10-09 07:09:18.850 UTC [34] LOG:  shutting down
postgres_1       | 2018-10-09 07:09:18.872 UTC [32] LOG:  database system is shut down
postgres_1       |  done
postgres_1       | server stopped
postgres_1       |
postgres_1       | PostgreSQL init process complete; ready for start up.
postgres_1       |
postgres_1       | 2018-10-09 07:09:18.961 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1       | 2018-10-09 07:09:18.961 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1       | 2018-10-09 07:09:18.968 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1       | 2018-10-09 07:09:18.991 UTC [43] LOG:  database system was shut down at 2018-10-09 07:09:18 UTC
postgres_1       | 2018-10-09 07:09:18.994 UTC [1] LOG:  database system is ready to accept connections
reverse-proxy_1  | time="2018-10-09T07:09:19Z" level=error msg="Unable to obtain ACME certificate for domains \"<MY DOMAIN>\" : cannot get ACME client acme: Error 400 - urn:ietf:params:acme:error:invalidEmail - Error creating new account :: not a valid e-mail address"
peertube_1       | [domain.tld:443] 2018-10-09 07:09:19.920 info: Database peertube is ready.
peertube_1       | [domain.tld:443] 2018-10-09 07:09:20.555 info: Creating application account.
peertube_1       | [domain.tld:443] 2018-10-09 07:09:20.594 info: Generating a RSA key...
peertube_1       | [domain.tld:443] 2018-10-09 07:09:20.702 info: Creating a default OAuth Client.
peertube_1       | [domain.tld:443] 2018-10-09 07:09:20.709 info: Client id: 3qb7lz2lhcbsbi23iunsh4kaeajuu35g
peertube_1       | [domain.tld:443] 2018-10-09 07:09:20.710 info: Client secret: Hk5wFi5nN6ZYWbruIRIYGpJFs4MOyqAP
peertube_1       | [domain.tld:443] 2018-10-09 07:09:20.714 info: Creating the administrator.
peertube_1       | [domain.tld:443] 2018-10-09 07:09:20.850 info: Generating a RSA key...
peertube_1       | [domain.tld:443] 2018-10-09 07:09:20.969 info: Generating a RSA key...
peertube_1       | [domain.tld:443] 2018-10-09 07:09:21.085 info: Username: root
peertube_1       | [domain.tld:443] 2018-10-09 07:09:21.085 info: User password: duvelexuveliweqa
peertube_1       | [domain.tld:443] 2018-10-09 07:09:21.087 error: Cannot use SMTP server because of lack of configuration. PeerTube will not be able to send mails!
peertube_1       | [domain.tld:443] 2018-10-09 07:09:21.102 info: Server listening on 0.0.0.0:9000
peertube_1       | [domain.tld:443] 2018-10-09 07:09:21.103 info: Web server: https://domain.tld
peertube_1       | [domain.tld:443] 2018-10-09 07:09:41.268 info: 172.17.10.171 - - [09/Oct/2018:07:09:41 +0000] "GET / HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
peertube_1       |
peertube_1       | [domain.tld:443] 2018-10-09 07:09:43.268 info: Getting client tokens for host 172.17.8.218:9000 is forbidden (expected domain.tld).
peertube_1       | [domain.tld:443] 2018-10-09 07:09:43.269 info: 172.17.10.171 - - [09/Oct/2018:07:09:43 +0000] "GET /api/v1/oauth-clients/local HTTP/1.1" 403 - "http://172.17.8.218:9000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
peertube_1       |
peertube_1       | [domain.tld:443] 2018-10-09 07:09:43.292 info: 172.17.10.171 - - [09/Oct/2018:07:09:43 +0000] "GET /api/v1/config/ HTTP/1.1" 304 - "http://172.17.8.218:9000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"

**Comment by Chocobozzz** [comment]
Did you change the `.env` file? If your app listens on `172.17.8.218:9000`, the `PEERTUBE_WEBSERVER_HOSTNAME` should be `172.17.8.218` and `PEERTUBE_WEBSERVER_PORT` should be `9000`

**Comment by adtrytech** [comment]
Hi Chocobozzz,
Thanks for your help. The Peertube was launched successfully and I can upload a video to it.
But, I encounter another issue that I can't play the uploaded video and it always shows
"Sorry, but this video is not available because the remote instance is not responding. Please try again later."

Do you have any advice. Thank you!

**Comment by Chocobozzz** [comment]
> Thanks for your help. The Peertube was launched successfully and I can upload a video to it.
But, I encounter another issue that I can't play the uploaded video via the http://hostIP connection and it always shows "Sorry, but this video is not available because the remote instance is not responding. Please try again later."

You enabled https on your instance? If yes, you should do a redirect http -> https

> I only use one standalone host to install the Peertube now.
By the way, is it possible that I can use the Swarm Stack mechanism with a compose file and exclude the "reverse-proxy"(traefik) service to deploy the Peertube service in my cluster? Any example?

I don't known docker-swarm, but yes you can remove the reverse proxy from the docker compose file (this is just a template).

**Comment by adtrytech** [comment]
Hi CHocobozzz,

Sorry, I can't catch your points about the "enable https" and "redirect http->https"
If I use **https://hostIP**, I can play the uploaded video. Does this means that I already enable the https?

If I remove the reverse proxy, I couldn't play the uploaded video via the https://hostIP.
Provide the compose and ".env" files below and hope this could help to clarify my problem.
[compose file]:
version: "3.3"
services:
  peertube:
    image: chocobozzz/peertube:production-stretch
    env_file:
      - .env
    ports:
      - "80:9000"
      - "443:443"
    volumes:
      - ./docker-volume/data:/data
      - ./docker-volume/config:/config
    depends_on:
      - postgres
      - redis
    restart: "always"

  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "peertube"
    volumes:
      - ./docker-volume/db:/var/lib/postgresql/data
    restart: "always"

  redis:
    image: redis:4-alpine
    volumes:
      - ./docker-volume/redis:/data
    restart: "always"

[.env]
PEERTUBE_DB_USERNAME=postgres_user
PEERTUBE_DB_PASSWORD=postgres_password
PEERTUBE_WEBSERVER_HOSTNAME=172.17.8.218
PEERTUBE_WEBSERVER_PORT=443
PEERTUBE_WEBSERVER_HTTPS=true
PEERTUBE_TRUST_PROXY=127.0.0.1
PEERTUBE_SMTP_USERNAME=
PEERTUBE_SMTP_PASSWORD=
PEERTUBE_SMTP_HOSTNAME=
PEERTUBE_SMTP_PORT=25
PEERTUBE_SMTP_FROM=noreply@domain.tld
PEERTUBE_SMTP_TLS=true
PEERTUBE_SMTP_DISABLE_STARTTLS=false
PEERTUBE_ADMIN_EMAIL=admin@domain.tld
# /!\ Prefer to use the PeerTube admin interface to set the following configurations /!\
#PEERTUBE_SIGNUP_ENABLED=true
#PEERTUBE_TRANSCODING_ENABLED=true


Thank you !
