### ISSUE TITLE
Is it safe to deploy PeerTube on multiple nodes behind a load balancer?

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#1229]
I am thinking to deploy my instance on multiple nodes, but before I go that route I need to know if the code will be able to handle this case, to place multiple servers running the instance code behind a load balancer, making it use a central Redis server and a central Postgres Database server. The only thing I'm not how it will work is the transcoding, will both servers start transcoding the same video or will one server do the transcoding of the video. Possibly there just needs to be a central transcoding only server for this, right? Or a cluster(multiple nodes) of transcoding servers. 

This is the only thing that is stopping me right now from deploying it on multiple server behind a load balancer.

Possibly I could even have the frontend code hosted on S3 as a website and an EC2 instance for the backend, but ideally I would like to be able to have multiple servers so that load is balanced between the servers, then later I can add or remove servers as needed, or configure autoscaling to do that automatically.

Would this be possible with the current codebase? and if not then, what modifications would need to be made in order to run this type of architecture? is it only the transcoder that is the blocker or is there something else I'm missing?

**Comment by Chocobozzz** [comment]
Sorry but peertube does not support load balancing. If you plan to have many users, you should consider creating different instances (to promote decentralization).

**Comment by kontrollanten** [comment]
Two years later, is the answer the same, @Chocobozzz ? Is transcoding the only obstacle? Maybe an upcoming solution of https://github.com/Chocobozzz/PeerTube/issues/947 would solve this then?

**Comment by Chocobozzz** [comment]
Hello,

Yes the answer is the same. There are many obstacles in the peertube core that was not designed to be on multiple nodes. But if you spot peertube limitations at your scale, we can discuss about mitigations/solutions.

**Comment by kontrollanten** [comment]
Currently we're having an OpenStack architecture with a load balancer but only one PeerTube instance behind. The relevant storage folders are on a mounted s3 bucket and the database is on a separate server, so we can destroy and create PeerTube instances without downtime. [Here's a draw.io diagram of the current architecture.](https://viewer.diagrams.net/?highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.drawio#R1VnbcpswEP0aP6bD3fZj7MRNp0mb1plJ8yjDBtTKEhHCNvn6SkYYML7mYpInpKOj2%2B6eHUl07OF08ZWjOLphAZCOZQSLjn3RsSzTsA35UUiWI26%2FlwMhx4EmlcAYP0PRU6MpDiCpEQVjROC4DvqMUvBFDUOcs3md9shIfdYYhdAAxj4iTfQeByLSqOc6ZcMV4DAqpja9ft4yRQVbbyWJUMDmFci%2B7NhDzpjIS9PFEIiyXmGYvN9oS%2BtqZRyoOKTD8Ppy%2BP15dGUldHJj%2FLrz778tzvQoM0RSveOfMdCxQP4%2FvWqRFbbgLKUBqNGMjj2YR1jAOEa%2Bap1L70ssElMia6YsIoJDKssEHuXqBjPgAkuznmtYMMXXk8s2WGzdlbmylYwyYFMQPJMU3cFxtXl1gNmers9Ld3kFFlU8ZRcdkQ6RcDV2aURZ0HY8wqb9huUgkEGlq4yLiIWMInJZooO6bUvONVOGWlr0LwiRaYWgVLC6vROBuDhXES8Bn6AkwX4BjzApaPnS1Hp221sun6Xchx3btLQcEQ9B7OA5m%2F3HgSCBZ%2FV1bPLFsqvcGcoqhJhhKpLKyLcKKMOi262HheusieM4vizkKyijYrWVlweK1RBfx%2FKIkkuAZ7UI8p5SlSYGtVKov8seSYxogV0zFMjuE0QQ9YEXFLnGKqsCL6cr0DdU%2FRvou2vXHeMYTX2b1gZ9e%2B8lb9NrXd%2BUUVgTt%2FG24nYOFLfptqFuz1xTq%2BvuVPce%2Fvuo29mt7u3yvQXgd%2BkEirYJL1rO5Hj3MFEOBD47WtkHza7m%2BA0BTj532jC6dY9bbttpo9dG2pDm4tmfauVBDfbFLaoXCz14Xst07cDjBNCgSZLg%2B5w43BOdOF7lZ%2FfFsmeJCDkkT%2BRTK6%2FXX8u17SvPaLhkwCYfzW6uVbfbhnvMic1mt5qwKjnqodr2uoT1htnIPPQCZBqbHX%2BafGQ6rR9XP5Y7rFa90bzzDS9%2BfPRctHqOay8ZdVuP4i2XrtMegcxDz0Dma8P8RRczc%2B0ZxTrFM4rZPHKd348lMLY3X6ESwbh697VGMUlDTJO9NA4zDPO9PA6BjDhE%2FWwfMxEc0BTT8CwmKCM4EXsHF1E6nVCEyX4m4yqy9vJmOACWfLTk01t78OluyD29DblnFXtHJB%2Fls9UDfB6P5X8M%2B%2FI%2F)

Maybe we'll try to separate it a bit more, I'll keep you updated if then.

**Comment by Saddamus** [comment]
@kontrollanten  can you share some information about the traffic you are able to handle with your deployment ? I have similar depployment on kubernetes, but under heavier load it stucks on database transactions - not sure if this is the reason or a result of the stress.

**Comment by kontrollanten** [comment]
> @kontrollanten can you share some information about the traffic you are able to handle with your deployment ? I have similar depployment on kubernetes, but under heavier load it stucks on database transactions - not sure if this is the reason or a result of the stress.

We're handling about 10-20k views per day with ~5 000 users that makes ~80 comments per day. How does you traffic look like? Do you have multiple PT instances running in parallel?

**Comment by Saddamus** [comment]
We host several instances, but they are all separate. So far we are testing what  load we can achieve with them. Today i found butleneck, which is NFS storage. With 5 000 concurrent views, network I/O about 1Gbps, atop says, that disk is not going to cooperate, which at the end is good news, as first I thought that software is not capable to handle heavy traffic.
Anyway, its a pitty that peertube is not designed to run in replicas - federation is not compensating the benefit of replicas.

**Comment by kontrollanten** [comment]
> We host several instances, but they are all separate. So far we are testing what load we can achieve with them. Today i found butleneck, which is NFS storage. With 5 000 concurrent views, network I/O about 1Gbps, atop says, that disk is not going to cooperate, which at the end is good news, as first I thought that software is not capable to handle heavy traffic.

Do you have the ability to point the `/static` and `/lazy-static` paths directly to a S3 bucket? Then it shouldn't drag down your server. On top of that you could also add a CDN, then the scaling of views shouldn't be a problem at all. We haven't tried the CDN with live videos yet though.

**Comment by Saddamus** [comment]
Does this matter whether storage is NFS / S3 / ceph or whatever else if same physical disk stands behind it ?
Can you ping me on Skype: adamobuchowski ? I would like to ask some questions.

**Comment by swoop2003** [comment]
what errors are expected during implementation 
1) DNS balancing . example.com - 2 diferent IP
2) Two peertube instanse node (with diferent public IP)
3) folder ~/storage as nfs, connect 2 instance
4) central Postgres Database server

**Comment by ROBERT-MCDOWELL** [comment]
would be nice if postgres can be replaced by cockroachDB which is posttgresql compatible and decentralized,
for folder replicating csync2 can be used in real time.
