### ISSUE TITLE
TCP/IP Tuning for multi-instance Peertube on Yunohost

### ISSUE THREAD

**Issue by anmol26s** [Chocobozzz/PeerTube#1232]
Hi
Yunohost can install multiple Peertube instances on same server. 
I would like to know if TCP/IP tuning is required for each multiple instance on server or it would be ok to have one TCP/IP tuning file for all the instances on the yunohost server?

**Comment by rigelk** [comment]
hi @anmol26s!

TCP/IP tuning is a system-wide setting, like everything that goes with `sysctl`. So just keep one ;)
