### ISSUE TITLE
Open video in a remote instance

### ISSUE THREAD

**Issue by nbrucy** [Chocobozzz/PeerTube#1234]
This is a idea of new feature : adding a button to open a video or a account profile on its home instance, and better on any remote instance.

Sometimes when I bump into a nice video or channel in Peertube, I may want to see it in its home instance because I think they may be other similar videos on it. Today the only way to do that I think is to copy the link in the adress bar and search for the content.

Another use case would be if I followed a link or see an embed Peertube video, I may want to see it in my favorite Peertube instance.

Thanks for your good work !

**Comment by Nutomic** [comment]
The [Peertubify](https://gitlab.com/Ealhad/peertubeify) browser addon covers some of this functionality.

**Comment by abakkk** [comment]
Why not just add a link to remote instance homepage in video attributes (after description) ?

**Comment by Chocobozzz** [comment]
> Why not just add a link to remote instance homepage in video attributes (after description) ?

We now have this kind of link in the video watch page.
