### ISSUE TITLE
Remove footer on infinite scroll pages

### ISSUE THREAD

**Issue by ldidry** [Chocobozzz/PeerTube#1235]
A footer is useless and frustrating when you have infinite scroll.

Please put PT's version number and copyleft elsewhere on page with infinite scroll.

What about a [question circle](https://forkawesome.github.io/Fork-Awesome/icon/question-circle/) icon, bottom left? Or the [PeerTube](https://forkawesome.github.io/Fork-Awesome/icon/peertube/) icon, bottom left? With the information displayed on hover.

**Comment by Chocobozzz** [comment]
What about the about page? :)

**Comment by scanlime** [comment]
I really like the suggestion of a question circle link in the sidebar, and redundancy could be okay sometimes if we want information to be easy to find

**Comment by McFlat** [comment]
A footer on the about PeerTube page makes sense, but everywhere else doesn't make sense to clutter the interface. You don't see iOS or Android put their footer and version number everywhere, except for only on the settings about page.

**Comment by ldidry** [comment]
Ping!

**Comment by rigelk** [comment]
Since the version is now in the features table, and the license in the "PeerTube" about page, why not remove the footer altogether?

**Comment by Chocobozzz** [comment]
The footer is useful for better indexation of joinpeertube website by crawlers. I removed the version from the footer: https://github.com/Chocobozzz/PeerTube/commit/0a9131f9615e0aa26ec26c1739fce3aca9fca43f
