### ISSUE TITLE
Issue with nginx when uploading video with POST

### ISSUE THREAD

**Issue by codevirtuel** [Chocobozzz/PeerTube#1236]
**What happened?**
I've used the API to upload a .mp4 into my peertube node.
And nginx return a "414 Request-URI Too Large".
I've tried to increase the header size but that resulted to a "502 Bad Gateway"

**What do you expect to happen instead?**
A successful upload with 200 code and json

**Steps to reproduce:**

1. Use the API POST /videos/upload (with channelId, name and videofile parameters)

2. Send request

**Additional information**
* PeerTube version or URL: https://peertube.osureplayviewer.xyz
* Browser name/version: Firefox 62.0.3
* NodeJS version: v8.12.0

**Comment by codevirtuel** [comment]
All my request are done with a python script :
![github](https://user-images.githubusercontent.com/12038808/46820084-993c2400-cd85-11e8-9bb3-54530c622bc7.PNG)

And here my results : 
![github2](https://user-images.githubusercontent.com/12038808/46820128-bb35a680-cd85-11e8-80fd-75d24f1754b6.PNG)

**Comment by Chocobozzz** [comment]
I'm not a python expert, but I think it's `requests.post(url = API_URL, data = PARAMS, headers = headers)`

You could take inspiration from [the prismedia script](https://git.lecygnenoir.info/LecygneNoir/prismedia/src/branch/develop/lib/pt_upload.py) maintained by @LecygneNoir

**Comment by codevirtuel** [comment]
The prismedia script work a lot better, my script doesn't work but that fine ;)
Thank you @Chocobozzz for the recommandation
