### ISSUE TITLE
External link error problem

### ISSUE THREAD

**Issue by zzoozzo1122** [Chocobozzz/PeerTube#1238]
v1.0.0-rc.2

Embed
<iframe width="560" height="315" sandbox="allow-same-origin allow-scripts" src="https://peertube.cpy.re/videos/embed/d2a5ec78-5f85-4090-8ec5-dc1102e022ea" frameborder="0" allowfullscreen></iframe>

We tested the stomach images.
It works well on PCs, Androids.
It does not work on iPhones and iPads (Safari, Chrome, and Firefox).

Please amend.
The old version was played in the form of HTTP.

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I can't reproduce. Could you retry? Maybe peertube2 was being updated

**Comment by Chocobozzz** [comment]
> No screens are available on iPhone and iPad.

What is the iOS and Chrome version?

**Comment by zzoozzo1122** [comment]
iphone  ios 11.2.2  Chrome 69.0.3497.105
ipad  ios 10.3  Chrome 69.0.3497.105
not played.
The identity of the sample site is your site address.

**Comment by Chocobozzz** [comment]
Unfortunately we cannot support iOS 10 :/

However I tried with iOS 11 (iPhone 6S, Safari) and it worked well.
