### ISSUE TITLE
Night Mode : Unreadable stuffs

### ISSUE THREAD

**Issue by FirePowi** [Chocobozzz/PeerTube#1243]
PeerTube Version : v1.0.0

I saw some unreadable stuffs while activating the Night mode as in 
PEERTUBEINSTANCE/admin/config/edit-custom

Background of `.nav-pills .nav-link.active, .nav-pills .show > .nav-link` is white instead of black. (For exemple)

**Comment by rigelk** [comment]
![screenshot_2018-10-11 edit custom configuration - peertube](https://user-images.githubusercontent.com/6329880/46807433-2cfff700-cd6a-11e8-9a30-887413188c08.png)

:thinking: are you referring to these nav-pills? They don't show up with a white background here.

**Comment by FirePowi** [comment]
![image](https://user-images.githubusercontent.com/14030913/46964538-a409f800-d0a8-11e8-9140-2222d3011142.png)
The "Prévisualisation Complète" button.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/f2fab901df31a0e7081f4bb225f28e98798950b0
