### ISSUE TITLE
install fails on debian stretch

### ISSUE THREAD

**Issue by samvermeulenpro** [Chocobozzz/PeerTube#1244]
Hi,

On jessie the install is working.
But on Stretch, the install fails at yarn process.

This is Yunohost logs but same problem for classical install

https://paste.yunohost.org/raw/urayarateg

My config  :
* Kimsufi OVH serveur
* Debian 9.5
* nodejs 8.12
* yarn 1.10

Great Thanks

**Comment by Chocobozzz** [comment]
Hello,

It seems to be a duplicate of https://github.com/Chocobozzz/PeerTube/issues/830

Please try the @anmol26s workaround https://github.com/Chocobozzz/PeerTube/issues/830#issuecomment-425942717

**Comment by samvermeulenpro** [comment]
it's working #830 

Great Thanks
