### ISSUE TITLE
[i18n] translations non imported

### ISSUE THREAD

**Issue by Quenty31** [Chocobozzz/PeerTube#1245]
Bonjour,
j'ai remarqué que les traductions dataient de 13 jours au mieux lors de la sortie de la version v1.
Certaines chaînes ont été ajouté depuis, et traduites sûrement aussi.
La version en français n'est pas complément disponible entre autres.

**Comment by BoFFire** [comment]
Hi,
We would like to know if there’s some sync between translation plateform and Github so that every release will include new translated strings :)

As @Quenti31 said may be some new strings were introduced but not piller/merged in the latest release.
Keep up the nice work :)

**Comment by Chocobozzz** [comment]
@BoFFire Not yet :) https://github.com/Chocobozzz/PeerTube/issues/1027

The V1 has been frozen for some days it's the reason why latest strings were not included in the final release.

**Comment by Quenty31** [comment]
Donc on peut penser que ça sera réglé pour la prochaine sortie ?
