### ISSUE TITLE
Storing videos thumbnails data etc differently to scale for large amounts of data

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#1246]
We need to store videos under subdirectories for users and possibly for channels of those users. Sure we will have to copy videos around when there is an ownership change, but it will allow us to better organize videos and better to know from the hard drive what videos belong to who. Also there is some limits on filesystems that limit the amount of files or subdirectories in a directory that we will avoid. Sure XFS filesystem doesn't have these limits, and there is a way to remove the limits for EXT4 filesystem, but the admin of the server has to make sure to setup the server this way.

```
It depends on the file system. ext3 support ~32000 subdirectories (not files!) in a given directory, with ext4 it's 64000 by default. xfs has no limit to my knowledge.

Ext4 has no limit if the dir_index and dir_nlink features are set. (They are the default for new file systems.) Old directories need to be upgraded to dir_nlink by running e2fsck -f -D
```
source: https://serverfault.com/questions/506465/is-there-a-hard-limit-to-the-number-of-files-a-directory-can-have

The way that I've been downloading and storing video personally is inside subdirectories by the name of the user who uploaded those videos. I think that instead of just storing videos in the main `storage/videos` directory we should start to store videos in subdirectories, say if the persons username is `somecooluser` then all this their videos would be stored in `storage/videos/somecooluser`. In the case that `somecooluser` decides to do ownership change to `anothercooluser` for some videos, those videos upon acceptance by `anothercooluser` will be transferred over in the database to `anothercooluser` and the videos will be moved on the hard drive to their videos directory `storage/videos/anothercooluser`. This way say if the admin wanted to backup videos and stuff they can do it on a per user and be able to segment or partition the operation instead of just do it all without knowledge from the uuid what videos belong to who without cross referencing them with the database.

This would be a really nice thing to have and would make the system overall much better as a whole, I personally need this a lot, it's a must for me, having many TB of videos I have a hard time wanting to really start putting all on them on my instance until this is implemented.

Also when imports happen we know a users username and so we can just store the videos under their videos directory. Only during ownership change will we have to copy the videos around between directories, other than that it's not that major of a change internally.

**Comment by McFlat** [comment]
Maybe just use the users channel id instead of the username for the subdirectory. I'll look around the codebase to see what this will all require and if anything I'll make a pull request. I know for me this is a must have, not sure if they ret of you guys are working with close to 100TB of videos but I am.

**Comment by McFlat** [comment]
In that case it would be best to just store all the data for a channel or user under their id.

so instead of storing all there directories under `storage/`
```
avatars cache  captions  previews  thumbnails  torrents  videos
```

we would store them under `storage/users/<userid>` and `storage/channels/<channel_id>`

**Comment by McFlat** [comment]
I think this is a prerequisite before I start working on the imports script to be much better.

**Comment by McFlat** [comment]
I'm just trying to avoid a big mess that would have to be cleaned up in the future once lots of data is in the directories. It's easier to just manage the stuff as needed instead of all at once later, just make the app behave the way we need right away so it takes care of it. Maybe for an instance with only 1TB of videos it seems like no big deal but when you get to 10TB you start to see the need for this, and when you get to 50TB you can't do without it, and by then when you grow to that amount of data it's no easy task to clean up the mess. So that's why we need to just do it the right way now so it can scale better.

**Comment by McFlat** [comment]
```
const uuidv5 = require('uuid/v5');
uuidv5(<user_channel_id>, <user_actor_id>)
```
we can make the channel_id private like this, so the `getChannelId()` would return a uuid for the channel instead of it's actual id which is meant for internal use.

**Comment by Jorropo** [comment]
> Using multiple hard drive to store your data?

If you are using multiple hard drive you don't have any reason to put in multiple directory, a raid (software (which is free and disponible for each new linux) or material) is lot more better for you. (faster, dynamic, redundancy)

**Comment by McFlat** [comment]
The main use case is to be able to from the hard drive to know what videos belong to different users. and to have separation of users data in subdirectories, instead of having everything all in a single directory for all users. This will allow to make admin tasks easier to do in the future. Some configurations can have a NFS mount with a large volume and some may have multiple hard drives, in my case I have a single large NFS volume to store everything, but I like to store everything in that volume organized on a per channel/user basis.

**Comment by McFlat** [comment]
I'm not sure I know how to get the VideoChannel and Actor for a VideoModel just yet, trying to figure it all out. Also there are probably many places in the code that would need an update to make these changes work smoothly, but I guarantee you it's worth it, after working for so many big companies in my days and making things scale for higher load and to be better organized I can tell you we need this.

**Comment by McFlat** [comment]
I could see how it would be used with multiple drives too, you'd mount some user directories on drive1 and some other user directories on drive2. That could come in handy for later one a site grown. This is an early version of the software, but no doubt once time goes by admins will want this.

**Comment by rigelk** [comment]
Isn't it something that should be left to distributed filesystems? (that's pretty much the same thing as the RAID suggested by @Jorropo - minus the redundancy which is out of scope here)

**Comment by McFlat** [comment]
the thing with depending only on the filesystem is that the content(videos, avatars, thumbnails, etc) are all thrown into a single directory without any kind of organization, sure the filesystem does it's own thing, but on top of the filesystem we need a layer that has better organization of all the resources, in order to manage all the stuff better/easier at scale.

**Comment by McFlat** [comment]
Distributed architecture and filesystems do things in general terms, but for the specific level of the application there needs to be better organization.

**Comment by McFlat** [comment]
If you take a look at this article about Wasabi maybe it will give you an idea as to why we need this, it's best to not totally depend on the OS or filesystem to do all the stuff for us, in fact if you want things done right you have to do it yourself, always. 

I understand that he's talking about disks, heads bits and filesystems, here but the same principals apply to everything practically.

> “If you’re relying on Linux or Windows or some operating system to control how the bits are physically written to disk, you’re never going to get to our price or our performance,” he said. “This is why it took three years to build this product, after having spent 10 years building a previous version at Carbonite. You have to go in and take control of the heads on the disk drives. And you have to write the data to disks the way you want to write it to disk, not the way Microsoft or Linux wants to write it to disks. Those operating systems were not specifically designed to do the kind of data storage that we do. They were designed for a variety of things that go on inside of a PC.

https://www.enterprisetech.com/2017/08/10/3-months-launch-wasabis-assault-s3-said-plan/

**Comment by Chocobozzz** [comment]
>  but on top of the filesystem we need a layer that has better organization of all the resources, in order to manage all the stuff better/easier at scale.

I disagree. What if tomorrow you want to organize videos by categories? And then languages? The API connected to the database has this kind of purpose.

Files must be organized according to peertube internal technical needs.
