### ISSUE TITLE
When the video player switches resolution, it briefly seeks back to the beginning

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#1249]
I've been noticing this in every version of PeerTube I've used so far, and I thought I saw it in the bug tracker already but this doesn't seem to exist. Apologies if it's already been filed.

The video player client will automatically change resolutions in response to changing network bandwidth conditions. This is great! But when it does so, it will briefly go back to the beginning of the video, then seek to approximately where it left off. This is unfortunately really disruptive.

The best behavior would be for no noticeable interruption at all during a resolution switch. Next best would be a brief pause or brief glitch. But the current behavior is quite distracting, and it's unclear in the moment whether the player will in fact seek back to the proper location or whether the user needs to seek, leading to more annoyance.

**Comment by McFlat** [comment]
I wonder if mediaelement.js would work better, I really like mediaelement better personally https://www.mediaelementjs.com/

**Comment by scanlime** [comment]
McFlat, i don’t see anything in the docs from mediaelement.js to indicate that it supports multiple resolutions/streams. Am i missing that?

**Comment by Chocobozzz** [comment]
Should be better with https://github.com/Chocobozzz/PeerTube/commit/fe05c3acbd48c72ac7e503bebde91830121a0bf1
