### ISSUE TITLE
Post-1.0.0 Milestones

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#1253]
Hi Everyone,

The bug tracker is full of many potential things to work on now that 1.0.0 is out, and I was wondering if this could be a good way to discuss post-1.0.0 priorities and start re-triaging the remaining bugs.

There's a lot to do, including some big ones like GDPR compliance 😅

And I'm also interested in getting a general sense for how much developers expect that the current architecture is stable vs. in flux. Will we see changes that completely break the protocol, for example? Are the encoded videos in a stable format? Will we have a way to support livestreams, etc? I'm interested to know what the development priorities are going forward!

**Comment by Chocobozzz** [comment]
Hello @scanlime,

Until the end of the year we'll work on v1 support/bugfixes. We'll improve some moderation tools (muting an account/instance, search filters in tables, bulk actions on users etc) with the idea of releasing a 1.1 version in December. Then we'll discuss about post 1.0.0 milestones.

> And I'm also interested in getting a general sense for how much developers expect that the current architecture is stable vs. in flux.

It's stable

> Will we see changes that completely break the protocol, for example?

No, but some new versions may not be able to federate with older versions (probably very rare).

> Are the encoded videos in a stable format?

Yes

**Comment by gled-rs** [comment]
Please consider releasing admin tools before december. At least increments of it.

It is not sustainable to host a public instance those days without minimum tooling to keep the instance safely running.

**Comment by rigelk** [comment]
@gled-rs there should be one next thursday, but edges will still be rough.

**Comment by Chocobozzz** [comment]
We created a project regarding the issues we plan to implement in 2019: https://github.com/Chocobozzz/PeerTube/projects/4
