### ISSUE TITLE
PeerTube YellowPaper?

### ISSUE THREAD

**Issue by klueq** [Chocobozzz/PeerTube#1255]
There are a few notes here and there about how this works, but I couldn't find a comprehensive description of its architecture.

**Comment by rigelk** [comment]
We don't have a _yellow paper_, but we should definitely rewrite our [ARCHITECTURE.md](../blob/develop/ARCHITECTURE.md) to be more comprehensive and explain the different APIs/ActivityPub objects involved.

**Comment by rigelk** [comment]
I'll close the issue for now - and notify you once this has been better documented :wink: 

If you have suggestions of what to include, don't hesitate to answer here.
