### ISSUE TITLE
Russian language translation of PeerTube

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#1266]
I will create an account at https://trad.framasoft.org/account/register and get the process started/finished for adding translations in the Russian language for PeerTube.

**Comment by McFlat** [comment]
The Russian translation looks complete but the status is showing otherwise.

**Comment by McFlat** [comment]
Not sure how I missed it couple days ago but seems like there's 55% not translated yet, I blame the interface for missing it.

**Comment by rigelk** [comment]
If the language exists in the interface then no need for an issue :)

**Comment by rigelk** [comment]
If the language exists in the interface then no need for an issue :)
