### ISSUE TITLE
(joinpeertube.org) menu button doesn't work on mobile

### ISSUE THREAD

**Issue by luntik2012** [Chocobozzz/PeerTube#1269]

**Comment by Nutomic** [comment]
Please put some explanation for your issues. The title alone is not enough to figure out what you mean, and the issue template is there for a reason.

**Comment by luntik2012** [comment]
mobile version of website has menu button. it doesn't work

**Comment by luntik2012** [comment]
ff, Android

**Comment by Nutomic** [comment]
The same goes for #1270 and #1271. Your other issue (#1268) is probably clear.

**Comment by BO41** [comment]
@luntik2012 could you provide a screenshot of the button, and maybe the text it has?

**Comment by rigelk** [comment]
![screenshot_2018-10-14 take back control of your videos joinpeertube](https://user-images.githubusercontent.com/6329880/46917501-430af300-cfc8-11e8-9b69-30a9a507793c.png)

**Comment by Chocobozzz** [comment]
Closing now the issue has been created on the appropriate repository: https://framagit.org/framasoft/peertube/joinpeertube/issues/2
