### ISSUE TITLE
Peertube doesn't work with NAT/LAN

### ISSUE THREAD

**Issue by SoniEx2** [Chocobozzz/PeerTube#1274]
**What happened?**

Peertube doesn't benefit from a LAN's internal links, instead being limited to the internet connection speed.

**What do you expect to happen instead?**

Peertube should benefit from local peers, just like torrents.

**Steps to reproduce:**

1. Setup a LAN on a dial-up (56kbps) connection

2. Install peertube on a remote server

3. Access that peertube from multiple computers in the LAN

**Comment by McFlat** [comment]
I wonder if this is a bug in one of the upstream dependencies, like webtorrent for instance

**Comment by SoniEx2** [comment]
Nope. It's just that there's no Local Peer Discovery on the web, you have to have a tracker.

**Comment by Chocobozzz** [comment]
Related to https://github.com/webtorrent/webtorrent/issues/1136?

**Comment by scanlime** [comment]
fwiw, WebRTC can work between clients on the local LAN if you are willing to establish those connections via a remote tracker. I'd expect that normally we don't publish RFC1918 (private) IPs to the tracker, even if WebRTC makes this information available to the client, but it could be useful to publish that info in such a way that clients behind the same public IP (same NAT, presumably) can find other RFC1918 IPs on that network.

**Comment by SoniEx2** [comment]
if that can be done, please do

my dial-up will thank you

**Comment by Chocobozzz** [comment]
So I think it's more a [WebTorrent issue](https://github.com/feross/webtorrent/)
