### ISSUE TITLE
Optimize Website Load Speed

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1277]
Out of curiosity I just run some loading speed tests on peertube.social, and it seems there is some room for improvement. Here are the tests I tried:

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpeertube.social%2F&tab=desktop
https://gtmetrix.com/reports/peertube.social/fcff8bfY
https://www.uptrends.com/tools/website-speed-test
https://developers.google.com/web/tools/lighthouse/

The main suggestions are:
- [ ] get rid of render-blocking Javascript and CSS
- [x] specify browser caching for static files
- [ ] <strike>enable compression for json (seems like this would be a risk for [BREACH](http://breachattack.com/), and anyway would only save 26 KB out of 912 KB)</strike>

**Comment by Chocobozzz** [comment]
> get rid of render-blocking Javascript and CSS

PeerTube HTML is built by JavaScript so I'm not sure we can do anything here (or use server side rendering but it's quite difficult).

> specify browser caching for static files

Do you have the URLs?

> enable compression for json (seems like this would be a risk for BREACH, and anyway would only save 26 KB out of 912 KB)

Yep, we do not enabled it on JSON endpoints for this reason

**Comment by rigelk** [comment]
Maybe we can improve the lazy-loading of the JS and CSS?

**Comment by BO41** [comment]
one other thing I was wondering about:
using `'use strict';` in JavaScript can make the code [run faster](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode)(2. Point).
So shouldn't the transpiled typescript contain this string?

I am not sure if there is already an option in typescript or angular. But if I understand it correctly, there should be one (so probably needs a fix upstream).

any thoughts on this?

**Comment by rigelk** [comment]
@BO41 Typescript has a `strict` option, which enables `noImplicitAny` and `strictNullChecks` and generates the `'use strict'` you refer to. So a prerequisite would be to make our code compatible with these two options.

**Comment by Nutomic** [comment]
@Chocobozzz Here are the files listed by gtmetrix.com:
```
/api/v1/config/ (expiration not specified)
/api/v1/oauth-clients/local (expiration not specified)
/api/v1/videos/categories (expiration not specified)
/api/v1/videos/languages (expiration not specified)
/api/v1/videos/licences (expiration not specified)
/api/v1/videos/privacies (expiration not specified)
/client/assets/images/favicon.png (2 hours)
/client/en_US/language.e569b5463ef1c0ef2b34.png (2 hours)
```
This list is most likely incomplete, as it only considers the main page. And maybe not all of these files are actually cacheable (or only for a short time).

**Comment by McFlat** [comment]
As per webpagetest.org the only thing missing is the CDN for static files like images, JavaScript and CSS.

https://www.webpagetest.org/result/181015_D4_3badf8626dd3c36f7e9969bae979f674/

<img width="976" alt="screen shot 2018-10-15 at 1 16 12 pm" src="https://user-images.githubusercontent.com/43896676/46969761-b5d5a600-d07c-11e8-9a68-6b98411abae0.png">

**Comment by Booteille** [comment]
Isn't using a CDN the opposite of the goal of the project (decentralizing services)?
I can understand why we could make this an option though.

**Comment by McFlat** [comment]
@Booteille No it's not, the purpose of this project is to decentralize video content, while CDN's allow for better scaling and performance to serve the content

**Comment by Chocobozzz** [comment]
@McFlat Please edit your comment instead of adding a new one each time to avoid spamming watchers  :)

**Comment by McFlat** [comment]
Ok I'll keep that in mind, thanks

**Comment by BO41** [comment]
>### Application Performance
>Continuing our focus on performance, we analyzed common mistakes across the ecosystem. We discovered that many developers were including the `reflect-metadata` polyfill in production, which is only needed in development.

[source](https://blog.angular.io/version-7-of-angular-cli-prompts-virtual-scroll-drag-and-drop-and-more-c594e22e7b8c)
it seems like we are doing this [too](https://github.com/Chocobozzz/PeerTube/pull/1306/files#diff-ddbfe834d8d4aa567d1a15674b8d343aL54). My PR to update to angular7 will remove this polyfill.

This should improve performance/download size as well

**Comment by BO41** [comment]
@rigelk 
>To fix this, part of the update to v7 will automatically remove this from your `polyfills.ts` file, and then include it as a build step when building your application in JIT mode, removing this polyfill from production builds by default.

sounds to _me_ that there is nothing else involved after updating. But you probably know this better than me

**Comment by rigelk** [comment]
ah right, my fix was just for the v6.

**Comment by BO41** [comment]
>enable compression for json (seems like this would be a risk for BREACH, and anyway would only save 26 KB out of 912 KB)

as far as I know, this is only a problem if you have a secret on a page. Like a clear text password.
And you need to be vulnerable to CSRF

<hr>
one other thing:
why are thumbnails so huge in size? I was loading video.blender.org where they uploaded a lot of new videos, and you could see all thumbnails slowly loading

![2018-10-28-154119_624x372_scrot](https://user-images.githubusercontent.com/29450609/47617507-1d054880-dac8-11e8-8282-3279aec197a2.png)
the image is displayed `200x110`, but the thumbnail is `1280x720`.

**Comment by Chocobozzz** [comment]
@BO41 Maybe a bug, please create an issue

**Comment by Chocobozzz** [comment]
Closing now we have cache for static endpoints in nginx config, and we can't do anything regarding JS/CSS blocking.

**Comment by Nutomic** [comment]
I just checked a couple of different instances, and none of them have have the client path completely cached. The nginx config has png, svg types missing. On some instances it even fails to cache js and css files, but maybe they are not using the default nginx config.

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fframatube.org%2F&tab=desktop
https://developers.google.com/speed/pagespeed/insights/?url=pe.ertu.be&tab=desktop

Personally, I would really prefer if these cache headers were set directly by Peertube, because it is really hard to apply the default nginx config while using Docker.

**Comment by Chocobozzz** [comment]
@Nutomic I'll add them

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/commit/c928e1364fbdff87f27fd982710b95426a250491 & https://github.com/Chocobozzz/PeerTube/commit/cd4cb177e6e35f69832304366c6f9df96600fb9e
