### ISSUE TITLE
Slow dowload when video playing on Firefox for Android

### ISSUE THREAD

**Issue by ivan386** [Chocobozzz/PeerTube#1283]
**What happened?**
Download slow when video playing. When i stop it download speedup. 

**What do you expect to happen instead?**
Downloading and playing video at the same time.

**Steps to reproduce:**

1. Open https://peertube.mastodon.host/videos/watch/d275c1b8-143b-42d0-b0bc-e7585034015b

2. Play it

3. Video dowload slowdown and stops.

**Additional information**
* PeerTube version or URL: PeerTube v1.0.0
* Browser name/version:  Firefox 62.0.3 for Android

* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by BO41** [comment]
sounds like you are just having a slow internet connection.
what speed do you have? are you using wifi or mobile data?

**Comment by Chocobozzz** [comment]
I think it's because you have slow device (maybe with a small CPU): when the video is playing, there is less CPU to download the chunks and so the download is slow. You could try with another web browser. I know firefox mobile is not very efficient (for now, they are working on this).

**Comment by ivan386** [comment]
Tested in Opera 47.3.2249.130976
When not playing player show 400KB max
When playing player show from 0 to 20KB
