### ISSUE TITLE
mimeType is not a supported element name in the ActivityStreams vocabulary. mediaType is.

### ISSUE THREAD

**Issue by redmatrix** [Chocobozzz/PeerTube#1284]
**What happened?**

Parsed ActivityPub object in the Osada ActivityPub server, looking for an item in the url array with a supported (video) **mediaType** . Nothing was found. 

**What do you expect to happen instead?**

The 'url' array returns items with the 'mimeType' I am looking for, but 'mimeType' is not defined in the ActivityPub vocabulary, nor in the @context array which will be an important consideration for LDSignatures. 'mediaType' is a defined element which provides exactly what we are looking for. 

I believe these elements need to be renamed to 'mediaType' to be compatible with the ActivityPub specification. I realise this presents a compatibility issue with existing software. Perhaps both element names could be used for a transition period(?). I'll leave that to you. 

**Steps to reproduce:**

1. View the structure of a Video Activity object

**Additional information**
* PeerTube version or URL: 1.0.0-rc2

**Comment by scanlime** [comment]
On the subject of MIME types, if this indeed will introduce a compatibility-affecting change...

Could we be more specific about what kind of data is *inside* the torrent? I'm thinking about futureproofing related to livestreams and such, and we might want different kinds of media inside a torrent, for example a single mp4 file vs. an HLS-style playlist and segments.

**Comment by Chocobozzz** [comment]
Thanks for the bug report @redmatrix 

>  Perhaps both element names could be used for a transition period(?). I'll leave that to you.

:+1: 

Should be fixed: https://github.com/Chocobozzz/PeerTube/commit/e27ff5da6ed7bc1f56f50f862b80fb0c7d8a6d98

I think I have fixed all the cases. You can try the patch on https://peertube2.cpy.re

https://peertube2.cpy.re/videos/watch/5a6133b8-3e0c-40dc-b859-69d0540c3fe5

@scanlime The data expected is 1 video file (mp4, webm etc).

**Comment by scanlime** [comment]
@chocobozzz, i understand this is currently the case, but you’re squatting on the entire mime type for “a torrent” to mean a specific usage of torrents. It’s like using the ZIP mime type when you mean JAR. This would have been a chance to improve future federation prospects right now for no additional compatibility cost
