### ISSUE TITLE
Define expiration time for API routes

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#1288]
_Originally posted by @Nutomic in https://github.com/Chocobozzz/PeerTube/issues/1277#issuecomment-429927618_

```
/api/v1/config/ (expiration not specified)
/api/v1/oauth-clients/local (expiration not specified)
/api/v1/videos/categories (expiration not specified)
/api/v1/videos/languages (expiration not specified)
/api/v1/videos/licences (expiration not specified)
/api/v1/videos/privacies (expiration not specified)
/client/assets/images/favicon.png (2 hours)
/client/en_US/language.e569b5463ef1c0ef2b34.png (2 hours)
```

This list is most likely incomplete, as it only considers the main page. And maybe not all of these files are actually cacheable (or only for a short time).

**Comment by Chocobozzz** [comment]
Every API route should not have cache, except "static" ones (values don't change very often):
 * `/api/v1/videos/categories`
 * `/api/v1/videos/languages`
 * `/api/v1/videos/licences`
 * `/api/v1/videos/privacies`

Maybe ~24 or 48 hours

**Comment by rigelk** [comment]
Is there a way to specify not to have cache for a route, then?

**Comment by McFlat** [comment]
Would it be possible to configure the caching from the frontend in the administrator settings? If this is not in the NGINX conf?

**Comment by Nutomic** [comment]
@McFlat The caching should work automatically, adding more options will just make things more complicated without much benefit.

**Comment by Chocobozzz** [comment]
Seems to not be an issue anymore in gtmetrix.com report.
