### ISSUE TITLE
Option to conditionaly delete videos after a grace period

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#1289]
_This is originally an idea from @LecygneNoir after a quick draft that took place a [while ago on Mastodon](https://miaou.drycat.fr/@rigelk/100700857828249693). What follows is most likely an incomplete synthesis of our exchange_

## Problem outline

Some instances upload content for long term storage and even archival, but some are dealing with more short-lived content. The admins (and users too!) might want to automatically clean things after a while.

## Suggested response

Create a "_grace period_" or "retention period of video data" after which the video(s) are deleted.

## Impacted areas in the application

- admin -> can set default grace period
- admin -> can set per user grace period
- admin -> can set if user is subject to grace period at all
- user -> can set a date at which the video is meant to be destroyed (overridden by grace period if the latter is shorter)

## Improved response

We could implement it so that other types of actions can be taken following this period of time: instead of deleting the videos, move them to a cheaper storage. Or delete a few of the resolutions (keep the highest resolution only, or the lowest depending on the scope…). 

We could implement it so that we can set a few "actions after some time" like this.

**Comment by McFlat** [comment]
This could be a useful feature for users no doubt.

**Comment by Booteille** [comment]
And maybe delete the less used resolutions.

I think the whole idea is good!

**Comment by maxdrash** [comment]
+1
Requested by users.

**Comment by Chocobozzz** [comment]
Moved issue in https://framagit.org/framasoft/peertube/official-plugins/-/issues/12

(but if someone else want to implement such plugin, please do it!)

**Comment by candidexmedia** [comment]
This would be a fantastic plugin or feature!

It would be great for things like festivals or streaming, where the licensing rights expire after a certain number of weeks / months / years. It would make managing these a lot more efficient.

The videos could either be deleted, or move to private / unlisted/ password-protected
