### ISSUE TITLE
Ability for users to add ad videos to play with their uploaded videos.

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#1291]
Users could use a way to add advertisement videos that would play in the beginning or start after a certain amount of time after the video plays to play a single video ad or out of a list of video ads the user uploaded. This way users can make money from uploading videos and perhaps transition from a day job to spending time making good videos if visitors are willing to buy whatever products they are promoting. 

The user could have a list of ads they upload and then specify which ad starts where at what time and on what videos. If they have promotors they can assign a video ad to play before the video and after a certain amount of time the video plays. Giving the user full control of when a promotion comes up for a device or product they are unboxing or are doing a video about, etc.

This would work by using a VAST video ad spec. VideoJS has a plugin for that.
https://github.com/theonion/videojs-vast-plugin

**Comment by scanlime** [comment]
yes, use these, it seems like my firewall and adblocker already know about this library :D

**Comment by XenonFiber** [comment]
Ads are actually in the FAQ: https://github.com/Chocobozzz/PeerTube/blob/develop/FAQ.md#are-you-going-to-support-advertisements

And you can't use them ethically anyway.

**Comment by XenonFiber** [comment]
@McFlat I still think that's going to be pretty annoying for the viewer to have to deal with unwanted content before they can actually get to/finish up the video they clicked on. I'm assuming they'll be somewhere around 5-30 seconds?

**Comment by McFlat** [comment]
@XenonFiber What we can do for that then is have an option in the user settings to skip user ads. Users can select either to watch the user ad or to not watch it, we wouldn't force it on them, we can have an option for that, and not make them pay for it to skip the ads.

**Comment by XenonFiber** [comment]
@McFlat Ads aren't a good addition to a project meant to improve on the problems with YouTube (and it's clones).

If it's something important to the creator and their video, it should really be in the video (or description). I'm sure there's people who'd still run ads and sponsored material anyway, and the ability skip those ads would only be possible if they were specifically set apart like this, but if we don't want capitalistic sponsored content to be the default, it shouldn't be built into the software.

**Comment by DavidLibeau** [comment]
I'm really an anti-ad guy. But I think that we better need a configurable preroll video ad rather than a fixed ad in the content that is there forever. It will be better if we can have this ad for a limited time and don't touch the content.

**Comment by Bugsbane** [comment]
Having ads be defined rather than built into the content also allows options like "click to skip" and blocking by ad blockers. If the ads are built into the video content itself, it actually gives the viewers less autonomy to skip them. Ironically, if the default on PeerTube becomes for ads to be in the video content itself, then ironically people who have ad blockers installed would see *more* ads on PeerTube than on YouTube...

**Comment by drequivalent** [comment]
User-defined pre-roll videos might be useful not really as advertisements, but for example as temporary announcements.
Like, if the creator that makes a periodical videoblog about, I dunno, tech, but wants to announce to their audience that they'll be leaving for the next week, they might a preroll announcement to their latest video. As soon as this anouncement becomes irrelevant, they just remove it leaving the content clean and on-point.

**Comment by buoyantair** [comment]
I don't think ads are a sane way to support your content creators. Ads are one of the reasons why the internet is the way it is today (Look at Google, Facebook). I think we should set the new grounds and learn from the disasters of Youtube. Monthly subscription model makes sense. A Patreon / Librepay like model makes sense.

**Comment by IvanlokoBR** [comment]
HELLO, I met the system recently but I think it is essential to have ads because people create content to earn money like youtubers and create a website that does not generate profit for the host or for the user, he will just ignore the platform and use another one. Summing up for the growth of Peertube, something flashy is necessary and even if ads are bad, servers are expensive and so far I don't see the advantage of paying a server to store Peertube while keeping costs out of my pocket.

**Comment by Chocobozzz** [comment]
You can now develop a plugin that adds ads to the player.

**Comment by maltfield** [comment]
Is there any plugin available for this yet?

**Comment by maltfield** [comment]
> Ads are actually in the FAQ: https://github.com/Chocobozzz/PeerTube/blob/develop/FAQ.md#are-you-going-to-support-advertisements

This link is dead. It looks like this is the current FAQ question that addresses this

 * https://joinpeertube.org/faq#what-is-peertube-s-policy-about-content-monetization
