### ISSUE TITLE
When uploads fail, progress at editing metadata is abruptly interrupted and lost

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#1292]
**What happened?**

An upload failed for some reason, yet to be determined. As a result of this failure, the UI switched from the metadata editing form back to the file selection page, displayed a momentary "Unknown error" popup which disappears too quickly, and leaves you with your progress at writing the video description and setting the metadata erased.

**What do you expect to happen instead?**

1. Errors with the upload should be displayed until dismissed. I probably won't be watching the upload every second, if it's a big file, and in the current code if I miss the momentary error it just seems like I have a browser window pointed at a fresh upload page.

2. The user is putting in a bunch of effort to fill out the video metadata as it uploads, and it is not okay to just destroy that work without warning. Even if it isn't possible for the server to save metadata on a video that doesn't yet exist, leave the data on-screen so users can copy it to a new upload window; or better yet, give a way to retry the upload or select a different file without losing the metadata progress.

**Steps to reproduce:**

1. Pick a file that can't be processed for any reason; bad encoding, too large, etc.

2. Upload it.

3a. Leave the upload alone, it fails, you come back and the window is unhelpfully blank.

3b. Work on metadata only to have your effort self-destruct

**Additional information**
* PeerTube version or URL: 1.0.0
* Browser name/version: Firefox 62.0.3
* NodeJS version: 8.12.0

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Should be better with https://github.com/Chocobozzz/PeerTube/commit/7373507fa830b0f18cb4cd95dfd923b1600e501d
