### ISSUE TITLE
Confusing term for Delete abuse

### ISSUE THREAD

**Issue by quentinDupont** [Chocobozzz/PeerTube#1295]
Hello !

As an administrator, I receive a report abuse.
I find confusing the term "Delete" 

![image](https://user-images.githubusercontent.com/9005817/47108943-46fb7700-d24d-11e8-9a78-9249a80c5736.png)

Apparently it deletes the abuse, but we can think that it deletes the video.
Maybe juste change the term to "Delete the abuse" ?

**Comment by rigelk** [comment]
I would rather say "Delete the report". WDYT?

**Comment by quentinDupont** [comment]
Indeed !
Perfect for me :+1:

**Comment by barbeque** [comment]
I have started on this, but still need to do the internationalization.
