### ISSUE TITLE
Let's Encrypt Certbot on Docker

### ISSUE THREAD

**Issue by crouthamela** [Chocobozzz/PeerTube#1297]
What is the recommended method for using Certbot with the Docker image? Could you add a recommended image to the docker-compose.yml?

**Comment by McFlat** [comment]
When it comes to docker-compose we could just link another docker container that does all the certificates stuff with certbot. There's a pretty solid docker image made by a French guy we could use for this https://hub.docker.com/r/pierreprinetti/certbot/

**Comment by Chocobozzz** [comment]
>  Could you add a recommended image to the docker-compose.yml?

We do, there is a traefik section in the template: https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/docker-compose.yml#L5

For certbot: https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/config/traefik.toml#L35
