### ISSUE TITLE
Doesn't work in Brave browser on Android

### ISSUE THREAD

**Issue by sixohsix** [Chocobozzz/PeerTube#130]
Brave (https://brave.com/) is an Android web browser using Chromium as a backend, but blocking ads.

Brave can't play any videos on PeerTube. The same videos play fine on Chrome for Android, on the same device.

Weirdly, in Brave I can see the data being transferred from the peers, but for some reason the video refuses to play. I tried changing various privacy options in Brave but could not get the video to function.

Unfortunately I don't know how to open a console on any Android browser, so I can't provide more information.

![screenshot_20171129-080124](https://user-images.githubusercontent.com/40615/33363630-80cdefcc-d4e1-11e7-9214-d2141db63c60.png)

* Browser name/version:
 - Brave on Android

* Console log if useful (Gist/Pastebin...):

**Comment by rigelk** [comment]
probably related to #218 and thus not specific to any platform Brave targets.

**Comment by Chocobozzz** [comment]
Fixed with HTTP fallback: https://github.com/Chocobozzz/PeerTube/commit/bf5685f0b7b1f23a1a3a972fc4d66061f31f9510
