### ISSUE TITLE
Hide viewcounts from viewers by default

### ISSUE THREAD

**Issue by japhir** [Chocobozzz/PeerTube#1302]
As per [my reddit comment](https://www.reddit.com/r/linux/comments/9p28tw/peertube_10_released/e7yk5pn/), I'd like to request that we hide viewcounts from end-users by default. Content creators should still be able to see their own viewcounts.

The reason for this is probably a bit vague, but is well-explained by two professional YouTubers in the podcast [Hello Internet Episode 109](https://www.reddit.com/r/CGPGrey/comments/9gyx0x/hi_110_love_monkey/) at the 1:37:49 mark. My sloppy summary consists of two arguments: (1) View counts are very visible on YouTube and knowing how popular something is can influence whether you watch it or not. There aren't view counts on Netflix or hulu, just a recommendation percentage, which is based on your viewing habits. (2) Content creators are all aware of each other's view counts when they meet up, creating a lot of social pressure for more views, or an explicit ranking of how well people are doing, resulting in people [burning out](https://www.polygon.com/2018/6/1/17413542/burnout-mental-health-awareness-youtube-elle-mills-el-rubius-bobby-burns-pewdiepie).

**Comment by McFlat** [comment]
I very much like this idea. We should make this feature as a setting, on a per channel basis and allow the channel owner/video uploader to override it on a per video basis.

**Comment by scanlime** [comment]
Great idea. One of my favorite differences between Mastodon and Twitter is that on masto the engagement metrics aren't in your face as much; more movement in this direction would be great.

And for creators, I've always been frustrated with the single 'views' number we're expected to use. I've found it much more useful to have data about how much people watch specific parts of that video, and YouTube makes this available to creators as a per-video graph. I'd love to have this info available more at-a-glance, seeing perhaps a small heat-map under each thumbnail showing which parts of the timeline get the most views and how much that compares with your own other content.

**Comment by rigelk** [comment]
Should we tie the display toggle of the view count to that of the like/dislike bar? A user suggested that on Mastodon.

**Comment by XenonFiber** [comment]
@rigelk I'd like that. Honestly, the like/dislike bar as a concept feels like something dragged over from YouTube without a real reason.

**Comment by scanlime** [comment]
Another user on my instance suggested this, and I've been thinking more seriously about it.

One solution is to use view counts not as a directly visible metric, but as a way of explaining other choices the UI makes. For example, #1341 may want to explain the "trending" page sort by showing (in a tooltip or other non-default-visible place?) the recent views. And the tools for a creator/uploader could include some metrics that help creators decide what content is popular and what content isnt- but that doesn't necessarily have to take the form of a single number like we have now. View counts over a unit of time (like 'trending') and graphs showing view count history both may be more useful and less problematic than a youtube-style single view number.

**Comment by Zig-03** [comment]
@rigelk 
> Should we tie the display toggle of the view count to that of the like/dislike bar? A user suggested that on Mastodon.

YESSSS please! I was just about to suggest this as well. Would be great not transforming PeerTube into yet another social media ([my source](https://www.youtube.com/watch?v=YjbyDU0WzYI) of inspiration).

**Comment by Chocobozzz** [comment]
We added identifiers to the views elements in https://github.com/Chocobozzz/PeerTube/commit/9ea6541488ae06c21cae3b9026728c52e11991cb, so every admin can easily hide them (using custom CSS, a specific theme or a plugin):

```
.views { display: none; }
```

Same for the like/dislike buttons & bar.

**Comment by wobblywob** [comment]
> We added identifiers to the views elements in [9ea6541](https://github.com/Chocobozzz/PeerTube/commit/9ea6541488ae06c21cae3b9026728c52e11991cb), so every admin can easily hide them (using custom CSS, a specific theme or a plugin):
> 
> ```
> .views { display: none; }
> ```
> 
> Same for the like/dislike buttons & bar.

How can I implement this? I've tried adding in Administration - Configuration - Advanced - Customizations - CSS:

`.views { display: none; }` or `#custom-css .views { display: none; }` or `body#custom-css .views { display: none; }` and none worked.

**Comment by Chocobozzz** [comment]
@wobblywob I suggest you to give a try to [peertube-plugin-ungamify plugin](https://framagit.org/rigelk/peertube-plugin-ungamify)

The selector changed, try `#custom-css my-video-views-counter { display: none; }`

**Comment by wobblywob** [comment]
> @wobblywob I suggest you to give a try to [peertube-plugin-ungamify plugin](https://framagit.org/rigelk/peertube-plugin-ungamify)
> 
> Or you still want to use custom css: the selector changed, try `#custom-css my-video-views-counter { display: none; }`

I was just about to comment that some other settings worked. #custom-css my-video-views-counter { display: none; }` works.

Thanks a lot for the help, the plugin and all the work you do here!
