### ISSUE TITLE
update to angular 7

### ISSUE THREAD

**Issue by BO41** [Chocobozzz/PeerTube#1305]
a new version of angular just got [released](https://blog.angular.io/version-7-of-angular-cli-prompts-virtual-scroll-drag-and-drop-and-more-c594e22e7b8c).
There is an [update guide](https://update.angular.io/) on how to update easily.
>but thanks to the work we did in v6, updating to v7 should be one command for most developers

The new version does not seem to change too much, an definitely nothing breaking.
I think this isn't high priority, but keeping up to date is always a good thing

**Comment by BO41** [comment]
it includes updates to rxjs, node and typescript. so many bug fixes will come as well

**Comment by BO41** [comment]
>Package "angular2-hotkeys" has an incompatible peer dependency to "rxjs" (requires "^5.5.0", would install "6.3.3").
Incompatible peer dependencies found. See above.

**Comment by Chocobozzz** [comment]
Tips with Angular upgrades: always await a few weeks :p
