### ISSUE TITLE
Standalone video embeds broken

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#1307]
This seems to be an issue on develop, likely related to change c199c427d4ae586339822320f20f512a7a19dc3f

The videojs player fails to construct, and we end up with an exception that 'default' is not a callable function. This happens in the compiled webpack code here:

```
this.player = o.default(this.videoContainerId, p, function ( ... ))
```

In this case 'o' is in fact the videojs constructor, not the entire module. There's no "default" member.

**Comment by rigelk** [comment]
Mhm I can't reproduce with both node LTS (carbon) and node current (dubnium) :worried:

**Comment by scanlime** [comment]
Oh hmm. Interesting... I'll keep looking for a problem on my end.

**Comment by Chocobozzz** [comment]
Thanks for the report. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/e0628695c3425bf69b5d7a46b24dcdf31892d9b6

**Comment by Nutomic** [comment]
Confirmed working, thanks :+1:
