### ISSUE TITLE
Erronous .ass caption upload

### ISSUE THREAD

**Issue by mfr-itr** [Chocobozzz/PeerTube#1308]
**What happened?**

I added a .ass subtitle file to a video. A .vtt was created on the server, but the content was in the .ass format, which obviously doesn't work in the player.

**What do you expect to happen instead?**

Either:
- error message ".ass files are not supported"
- Proper .ass -> .vtt conversion (ffmpeg can do it)
- Proper support of the .ass format, see #845 (long term)

**Steps to reproduce:**

1. Add a .ass subtitle file to a video

**Additional information**
* PeerTube version or URL: 1.0.0
* Browser name/version: Firefox latest
* NodeJS version: 8

**Comment by Chocobozzz** [comment]
Thanks, I added the error message in https://github.com/Chocobozzz/PeerTube/commit/b5487ff4a5c0bb2acaca79ee00df26a83886c889
