### ISSUE TITLE
Can't click on any channel name

### ISSUE THREAD

**Issue by Zig-03** [Chocobozzz/PeerTube#1309]
**What happened?**
Can't click on any channel name

**What do you expect to happen instead?**
open the channel

**Steps to reproduce:**

1. visit https://peertube2.cpy.re/videos/watch/a8ea95b8-0396-49a6-8f30-e25e25fb2828

2. try to click on the channel's name "By root@ peertube.cpy.re"

**Comment by Zig-03** [comment]
solved itself somehow...

**Comment by McFlat** [comment]
the javascript hasn't fully loaded in that case, refreshing the page probably fixed it
