### ISSUE TITLE
Video's creation date should use upload starting date

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#131]
Hello!

Here is a feature request, if it is even possible :-)
When uploading some videos simultaneously, for example to upload episodes for a series, the created date for the video is the date when the video finish its upload
I use Firefox 57 browser with 4 tabs opened to upload 4 videos at the same time.

But, if some episodes are smaller than other, thus upload faster, it breaks the real series order.

For example, upload 4 videos at the same time give something like that after uploading all episodes and sorting by created date: 
Ep1, Ep3, Ep2, Ep5, Ep6, Ep4, etc etc

If possible, it should be best to use as created date the date when the video is added to the queue?
Upload's beginning instead of ending?

Thank you!

**Comment by nzachow** [comment]
I did some poking around in the code trying to find where is the relevant code but I could not get very far.

During my search however I noted that the video has two dates, specifically *createdAt* and *updatedAt*.
Knowing that and given your description my hypothesis is that the sorting is done with the *"wrong"* attribute.
Another possibility is that both values are set at the same time, at the end of the upload.

If someone could give me some pointers on where this code lives or even if my hypothesis are reasonable I could look more into this issue.

**Comment by Chocobozzz** [comment]
@nzachow The `createdAt`/`updatedAt` attributes are set automatically when [we build video object](https://github.com/Chocobozzz/PeerTube/blob/develop/server/controllers/api/videos/index.ts#L186).

To resolve this issue, you could create a middleware before [reqFiles](https://github.com/Chocobozzz/PeerTube/blob/develop/server/controllers/api/videos/index.ts#L94) that set the actual time in `res.locals.startReqDate` for example. Then in the `videoData` object just set `createdAt: res.locals.startReqDate`.

**Comment by dedesite** [comment]
I'm interested in working on simple issues for peertube but this one raise a question for me.
The createAt attribut shouldn't be editable ? This way a user could specify when the video was actually created (it is the case on Youtube for example).

We could maybe create two attributs : one for real creation date and on for the upload ?

**Comment by Chocobozzz** [comment]
No, the `createdAt` should not be editable because it represents the object creation date in database.

What you want is a date when the video is automatically set from `private` to `public`, which would be another issue.

**Comment by dedesite** [comment]
Ok, but I was talking about the date the video has really been made. For example, the date you shoot the video. But I realize it's not exactly what @LecygneNoir wanted...

**Comment by LecygneNoir** [comment]
Mmmh I guess adding a "shooting date" is also interesting, but for me the point here is more a way to classify the video.

In this way, using the "CreatedAt" seems more useful (or easier to code?) as it is already existing and present an information ready to be used to sort videos mare naturally.

Perhaps it could be valuable to add some manual sort (with some sort of ordered playlist?) but I think it represents lot of work regarding this particular issue :-)

Hope it clarify! And big thanks for your help

**Comment by Chocobozzz** [comment]
Since we have a `publishedAt` field now, I'm closing this issue.
