### ISSUE TITLE
PeerTube destroys ASCII hearts, only supports Unicode hearts

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#1311]
Okay, I couldn't resist the title, but I think this is actually about comments having "<" characters stripped as if they were HTML tags rather than converting them to &lt; entities.

**What happened?**

I commented, saying something very simple of the form "timecode <3",
posted the comment,
and the resulting comment had only the timecode.

**What do you expect to happen instead?**

Expected to see both the timecode and "<3" afterwards. Since that was the last thing in the comment, I'm not sure if it stripped the entire remainder of the comment, just that token, or what.

**Additional information**
* PeerTube version or URL: diode.zone, PeerTube v1.1.0-alpha.1...42b63aa7 (recent develop commit from yesterday)
* Browser name/version: Firefox 62.0.3
* NodeJS version: 8.12.0

**Comment by Chocobozzz** [comment]
Blocked by https://github.com/punkave/sanitize-html/issues/79

**Comment by Chocobozzz** [comment]
Does not seem an issue anymore.
