### ISSUE TITLE
OpenID support

### ISSUE THREAD

**Issue by unmellow** [Chocobozzz/PeerTube#1316]
I was wondering if you plan to let people use openID to create / login to there account's
if not I'd like to request this feature

**Comment by unmellow** [comment]
I read this https://hacks.mozilla.org/2018/10/dweb-identity-for-the-decentralized-web-with-indieauth/
and it seems perfect for activitypub websites in general like i can make an account for one instance and login to another using the same account for example

**Comment by Chocobozzz** [comment]
Implemented in a plugin: https://framagit.org/framasoft/peertube/official-plugins/-/tree/master/peertube-plugin-auth-openid-connect

Only available in the next peertube release (2.2) at the end of May
