### ISSUE TITLE
Post-registration message is not visible enough

### ISSUE THREAD

**Issue by andzdroid** [Chocobozzz/PeerTube#1317]
The registration procedure currently looks like this:

Homepage -> Create an account -> Fill in form and submit -> Homepage

In the last step, the user is not logged in and the page looks exactly the same as the first visit to the homepage, except a small, easily-missed and temporary notification in the bottom right of the screen, the exact opposite corner of where all the buttons/links/sign up form/attention is.

If you miss the notification, it looks like nothing happened after submitting the registration form, and that the user was brought back to the previous page.

The message letting the user know to confirm their email should be more visible, and persistent.

If there is no email confirmation on the instance, the user should just be logged in immediately after completing the sign up form (issue already exists here: #763).

**Comment by scanlime** [comment]
as an aside, I really really don't like the temporary notification system; maybe the notification system itself needs some work to be more visible and less easily missed?

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/d8c9996ce2b4de3ef1f2d36f63e461006bab58ed
