### ISSUE TITLE
Searching for video is broken

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#132]
Hello!

After uploading some videos to test instance (peertube.drycat.fr) it seems that the research by username is broken

When a user search for video with pseudo, nothing is found: 
https://peertube.drycat.fr/videos/list;field=account;search=lecygnenoir;sort=-createdAt

Same seems to happens on the demo server, here a search with chocobozzz: 
https://peertube.cpy.re/videos/list;field=account;search=chocobozzz;sort=-createdAt

I have not seen this one in the feature list, so I create the issue to be sure I have not missed something

I tried to have feedbacks from my (pretty few) viewers, hope it could help!

Again good job with peertube, love it <3

**Comment by Chocobozzz** [comment]
Search feature is completely broken.

**Comment by Chocobozzz** [comment]
Now, we only search on the video name field. See https://github.com/Chocobozzz/PeerTube/issues/60 for a better search module.
