### ISSUE TITLE
Do not simply copy the remote AP object

### ISSUE THREAD

**Issue by lanodan** [Chocobozzz/PeerTube#1320]
Hi, filling this one as a pleroma dev (on my own).

Remote video url is https://peertube.social/videos/watch/81cbb572-3caf-499d-8fc8-aefb2651556c
Original video url is https://peertube.servebeer.com/videos/watch/81cbb572-3caf-499d-8fc8-aefb2651556c

**What happened?**
Getting https://peertube.social/videos/watch/81cbb572-3caf-499d-8fc8-aefb2651556c via ActivityPub return an id on another domain ( https://peertube.servebeer.com/videos/watch/81cbb572-3caf-499d-8fc8-aefb2651556c ), which is invalid (at least for us).

**What do you expect to happen instead?**
To have a Create/Announce activity to it instead of what is treated as an error (id and url isn’t matching, and it’s on different domains).

Also this might have been fixed/tagged in another issue but it would be neat if Peertube would show the original url somewhere (potentially creating less dead links).

**Comment by Chocobozzz** [comment]
We could do like Mastodon, that returns a 302 pointing to the origin url

**Comment by lanodan** [comment]
That should also work.

**Comment by Chocobozzz** [comment]
Okay so thanks for the issue @lanodan, it should be fixed with https://github.com/Chocobozzz/PeerTube/commit/8d1fa36ad22a21a9b0fb6bf51a27d09954220013
