### ISSUE TITLE
"Preview" and "Thumbnail" probably shouldn't be different

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#1321]
Right now we have separate images and separate uploads for a "preview" and a "thumbnail", but:

1. The difference between these two is not communicated to uploaders at all
2. Videos with different previews/thumbnails or unset preview/thumbnail will look different on mobile vs desktop in the main listing view

This behavior doesn't really seem intuitive and desirable. If there's a good reason for preview and thumbnail to be separate, I think we should make that clearer to uploaders and make it easier to set both to the same image in the case when that's what you want. If they don't need to be separate, let's use a database migration to consolidate them into a single item.

**Comment by Chocobozzz** [comment]
We need two different files because they have different sizes. But yes, it would be simpler if the user only uploads 1 image file, and then we generate the preview and the thumbnail from it.
