### ISSUE TITLE
Choose thumbnail/preview from a video frame

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#1322]
This is a feature request for an alternative way of setting the preview/thumbnail image from the video itself, by choosing a particular frame. For many videos a manually chosen frame provides a great compromise between effort and legibility, when you don't want to make something completely custom but want a more interesting frame than something arbitrarily chosen.

A simple implementation might choose several frames automatically, then allow creators to select one. A better implementation would allow scrubbing through the video on an embedded player, capturing whatever frame you hilight. An even better implementation might use some basic computer vision to find interesting candidate frames first.

**Comment by Sabilon** [comment]
And then, an API call to build a thumbnail based on a timecode would be great !
Like `put /videos/{id}/thumbnail` `"timecode": "string"`

**Comment by tilllt** [comment]
Absolutely would love to see this feature. If the mechanism to select a thumbnail through the player is too complex , letting ffmpeg sample several frames, distributed over the videos length on initial thumbnail selection would probably be a great intermediate solution. (http://debuggable.com/posts/FFMPEG_multiple_thumbnails:4aded79c-6744-4bc1-b30e-59bccbdd56cb)

**Comment by mroswell** [comment]
This request has been open for four years. A **very** important feature for people who share video content. Does anyone know a little JavaScript way of doing this in the meantime?

**Comment by kntndrsn** [comment]
Hello all, I have a rough draft of the frame selection user interface. Any initial feedback would be appreciated.

[My PeerTube fork](https://github.com/kntndrsn/PeerTube)

I've updated the Edit button and labeled it Upload. The "Select from video" button will cause a video-js player to be loaded with the video.

![Screenshot from 2024-02-27 18-53-31](https://github.com/Chocobozzz/PeerTube/assets/6994260/11495ad2-5f25-4b47-aa13-82b91a839634)


The user will play the video, finding the frame they want. From there, they can select "Use frame" to pass the timestamp.

![image](https://github.com/Chocobozzz/PeerTube/assets/6994260/afff6c1c-3840-4c3f-aa5a-e013b799577c)

**Comment by Chocobozzz** [comment]
This is an interesting solution but unfortunately it won't work with videos that are not compatible with the web browser (and they are many!).

I don't think we can do such feature without using the server, and so waiting for the video to be uploaded.

**Comment by kntndrsn** [comment]
@Chocobozzz Thanks for the feedback. The prototype in this case is pulling the video file from the server via the video service. This is similar to the mechanism used by the video-watch component. Is that what you mean or am I missing something?

If I'm missing a scenario, anything you can suggest pointing me in the right direction would be appreciated.

**Comment by Chocobozzz** [comment]
Thanks to @kntndrsn that implemented this feature. An embed player can be displayed to choose set a thumbnail from a specific frame.

![screen_2024-05-30-16_36_21](https://github.com/Chocobozzz/PeerTube/assets/5180488/d7429993-469d-484e-9c62-dd37ee601d4d)

(the feature is only available when you *Update* the video)
