### ISSUE TITLE
canonical URL for videos & accounts

### ISSUE THREAD

**Issue by stom79** [Chocobozzz/PeerTube#1323]
Hi there

**What happened?**
When using Pleroma, I can't fetch Peertube URL correctly.  I follow a peertube instance and I fetch results for videos with there UUID.

For instance, let's take this UUID: "81cbb572-3caf-499d-8fc8-aefb2651556c"

I would like to fetch this URL but it will fail if I use: https://peertube.social/videos/watch/81cbb572-3caf-499d-8fc8-aefb2651556c where peertube.social is the instance I am following, and the URL should be:
https://peertube.servebeer.com/videos/watch/81cbb572-3caf-499d-8fc8-aefb2651556c

But I don't get this canonical URL in [results](https://peertube.social/api/v1/videos/81cbb572-3caf-499d-8fc8-aefb2651556c). 

**What do you expect to happen instead?**

It would be really confortable that videos and accounts contain in results a  Fediverse-unique resource ID containing the original host.
Currently, I need to build it by using the "host" value attached to the account that published the video.

I opened an issue on Pleroma too.

**Comment by Nutomic** [comment]
Isn't this the same as #1320?

**Comment by stom79** [comment]
My bad. Sorry, I didn't notice that @lanodan opened the issue... Yes it's a duplicate of #1320
