### ISSUE TITLE
Infinite scroll doesn't remember position of last position

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#1325]
Would it be possible to add a tracking of the last scrolled to position or page in the infinite scroll of pages? So that if a visitor scrolls thru 10 pages to watch a video then navigates back to the previous page they won't have to scroll thru all those videos again to get to the video they clicked on and can proceed to the rest of the videos.

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/489290b8b16bede6ddfb773adad55dee6471ccfd
