### ISSUE TITLE
Error 500 in a refreshed install using an apache configuration

### ISSUE THREAD

**Issue by galcalde** [Chocobozzz/PeerTube#1326]
**What happened?**

Error 500 in a refreshed install using an apache configuration

**What do you expect to happen instead?**

Peertube instance running and being accesible

**Steps to reproduce:**

1. Installing according to the production guide
https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md

2. Using this apache configuration
https://gist.github.com/rigelk/07a0b8963fa4fc1ad756374c28479bc7

**Additional information**
* PeerTube version or URL: v1.0.1
* Browser name/version: Firefox
* NodeJS version: 8.12

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

* output of the access.log 

91.121.80.67 - - [21/Oct/2018:12:04:48 -0300] "POST /inbox HTTP/1.1" 500 4103
148.251.134.157 - - [21/Oct/2018:12:06:37 -0300] "POST /inbox HTTP/1.1" 500 4103
10.251.98.3 - - [21/Oct/2018:12:09:21 -0300] "GET / HTTP/1.1" 500 4657
148.251.134.157 - - [21/Oct/2018:12:09:23 -0300] "POST /inbox HTTP/1.1" 500 4103
206.212.243.124 - - [21/Oct/2018:12:10:05 -0300] "GET /.well-known/webfinger?resource=acct:peertube@videos.pueseso.club HTTP/1.1" 500 4098
206.212.243.124 - - [21/Oct/2018:12:10:06 -0300] "GET /.well-known/webfinger?resource=acct:peertube@videos.pueseso.club HTTP/1.1" 500 962
164.132.195.207 - - [21/Oct/2018:12:10:08 -0300] "GET /.well-known/webfinger?resource=acct:peertube@videos.pueseso.club HTTP/1.1" 500 4098
164.132.195.207 - - [21/Oct/2018:12:10:09 -0300] "GET /.well-known/webfinger?resource=acct:peertube@videos.pueseso.club HTTP/1.1" 500 962
159.69.113.20 - - [21/Oct/2018:12:10:18 -0300] "GET /api/v1/instance HTTP/1.1" 500 4098
159.69.113.20 - - [21/Oct/2018:12:10:19 -0300] "GET /api/v1/instance HTTP/1.1" 500 4098
164.132.195.207 - - [21/Oct/2018:12:10:25 -0300] "GET /.well-known/webfinger?resource=acct:peertube@videos.pueseso.club HTTP/1.1" 500 962
164.132.195.207 - - [21/Oct/2018:12:10:26 -0300] "GET /.well-known/webfinger?resource=acct:peertube@videos.pueseso.club HTTP/1.1" 500 962

**Comment by McFlat** [comment]
Why not use NGINX instead of Apache? Are you not in control of the server? NGINX is faster at serving pages so far as I'm aware. Would make you site faster then. Do the docs even have Apache Server setup instructions? I didn't see them there.

**Comment by galcalde** [comment]
I have a nextcloud installation there. but maybe I could back all up, uninstall apache and install ngnix. I'll try.

**Comment by McFlat** [comment]
Cool, yeah I'd recommend NGINX instead

**Comment by galcalde** [comment]
it worked. thanks.
