### ISSUE TITLE
create dat:// website

### ISSUE THREAD

**Issue by unmellow** [Chocobozzz/PeerTube#1329]
if you heard of [dat://](https://datproject.org/) it's a p2p data sharing protocol
that [beaker browser](https://beakerbrowser.com/) is pushing for the web
sense video streaming is already p2p to relieve the load on servers it seems like a good idea 
to serve the website itself like that

it may be a better idea to have a separate web app for this
but I feel like integrating dat would offer benefits and give way
to ideas, I can't yet perceive

**Comment by McFlat** [comment]
I'm willing to bet the direction the web is going, soon we will be able to smell and taste a website

**Comment by joshmorel** [comment]
How does this differ from [Tim's Solid](https://solid.mit.edu/)? They seem to be aiming for same purpose? Might be a worthwhile related project for the willing to investigate.

**Comment by rigelk** [comment]
@unmellow dat support in the browser is marginal, and we already use the more widely supported webtorrent to alleviate the load of video sharing. I don't think it's worth complexifying PeerTube-core with dat right now, sorry.

**Comment by unmellow** [comment]
@joshmorel solid doesn't seem like the same thing dat is a protocol like http https etc
solid seems to be a mix of things including a database
