### ISSUE TITLE
Security Issue : mails visibility in API

### ISSUE THREAD

**Issue by arthurlacoste** [Chocobozzz/PeerTube#133]
First, thank you to work on this YouTube alternative !

I've started to explore differents entrypoints of the API, and this one seems to have a security issue : https://peertube.cpy.re/api/v1/users

Right now, we can see every mails, of each users. It's a real problem.

**Comment by Chocobozzz** [comment]
Fixed: https://github.com/Chocobozzz/PeerTube/commit/86d13ec2aa94ec10810ddf9c8b33314bd4968791

Thanks for the report
