### ISSUE TITLE
Search for video UUID should return that video

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#1330]
**What happened?**

Pasted a video UUID into search (verified that the UUID worked when constructing a URL with it), no results returned.

**What do you expect to happen instead?**

Expected a search for any exact identifier for that video to return the video.

**Steps to reproduce:**

1. Paste UUID into search

**Comment by McFlat** [comment]
When you search for the whole uri, including the protocol(http/s) it works.

I can probably fix this issue today.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/3cf53828db9b1f0d65e91a07d2a65f2f4ad82270
