### ISSUE TITLE
/api/v1/instances with more parameters

### ISSUE THREAD

**Issue by stom79** [Chocobozzz/PeerTube#1331]
Hi,

**What happened?**
I would like to add a helper with [Mastalab](https://gitlab.com/tom79/mastalab) to choose peertube instances for the follow instances feature.
I noticed that there is a call to an API on `instances.joinpeertube.org` through `api/v1/instances` with 2 parameters: **start** & **count**
Are they some other parameters available?

**What do you expect to happen instead?**

Use `instances.joinpeertube.org` through `api/v1/instances`  and have the ability to fetch instances with parameters like with [instances.social](https://instances.social/api/doc/)

**Comment by Chocobozzz** [comment]
Wrong repository :) https://framagit.org/chocobozzz/instances-peertube

But yes, there are `healthy` and `signup` parameters. For example, we use https://instances.joinpeertube.org/api/v1/instances?start=0&count=100&signup=true&healthy=true on https://joinpeertube.org/
