### ISSUE TITLE
More parameters to fetch instances

### ISSUE THREAD

**Issue by stom79** [Chocobozzz/PeerTube#1332]
Hi,

**What happened?**
I would like to add a helper with [Mastalab](https://gitlab.com/tom79/mastalab) to pick up peertube instances.
I found this API to fetch Peertube instance: `instances.joinpeertube.org/api/v1/instances`
Unfortunately, there are two parameters: **start** & **count**

**What do you expect to happen instead?**
More available parameters, example for Mastodon: [instances.social](https://instances.social/api/doc/)

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/issues/1331#issuecomment-431822266
