### ISSUE TITLE
Current page no refreshing when clicking on the same route in the menu

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#1335]
When you have a tab open in the browser and uploaded/imported videos in another tab, then go back to this tab which could be `trending` or `recently-added` etc. and you try to click the link to refresh the videos list it doesn't refresh because it's on the current page. 

We should probably do a `window.document.location = document.location` on click if the page clicked is the current page being viewed.

**Comment by Chocobozzz** [comment]
Implemented by https://github.com/Chocobozzz/PeerTube/pull/3066
