### ISSUE TITLE
Video imports in frontend happen differently than from tools scripts

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#1337]
We need to make the `server/tools/peertube-import-videos.ts` to work the same as the imports from the web interface. So that it stores the `targetUrl` in the `videoImport` table. Currently the tools don't do that.

https://github.com/Chocobozzz/PeerTube/issues/754

**Comment by Chocobozzz** [comment]
The CLI script is a local tool, so you can use it even if your instance disabled import. See https://github.com/Chocobozzz/PeerTube/issues/754 and https://github.com/Chocobozzz/PeerTube/issues/1438 that should fit your needs
