### ISSUE TITLE
New design for a better world

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#134]

**Comment by SirCmpwn** [comment]
Can you elaborate on this?

**Comment by ucodi** [comment]
You should consider a logo before working on a redesign to have a style guide (colors, fonts, ...)

**Comment by Chocobozzz** [comment]
Scroll at the bottom of https://framatube.org/#en (image in the laptop).

Thanks to [Olivier Massain](https://twitter.com/omassain)

**Comment by ucodi** [comment]
It's a little simple in my opinion, and I don't think purple and orange are a good choice for a video platform.

I'll work on some alternative and submit them to you.

Plus, I can help building mockup for the new design 😉

**Comment by SirCmpwn** [comment]
I like it, good shit.

**Comment by Chocobozzz** [comment]
@ucodi I really appreciate but please don't spend time for this for now. Just wait the beta (in march) and then we could imagine a theming engine so everybody could be satisfied.

I love this new design and I need to move on because I have a lot of work :)

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/fada8d75550dc7365f7e18ee1569b9406251d660

**Comment by 1000i100** [comment]
https://github.com/Chocobozzz/PeerTube/issues/1766
