### ISSUE TITLE
Remove remote video when blacklisting a local video

### ISSUE THREAD

**Issue by prolibre** [Chocobozzz/PeerTube#1347]
When a video is in blacklist (defamation complaint in my case) it always works on other instances and my instance continues to broadcast the streams for other instances.
To completely block the video (without deleting it) I had to create a redirection (error 403) in the configuration of my web server.

The video in question (which no longer works thanks to my rewrite) : 
https://peertube2.cpy.re/videos/watch/761cbb61-d711-41c1-a53c-7ed3baac0541

**Additional information**
* PeerTube version or URL: https://peertube.heraut.eu (PeerTube v1.0.1)

**Comment by prolibre** [comment]
For the record, I put the content back online (I don't have enough evidence of its defamatory content)

**Comment by Chocobozzz** [comment]
Blacklisting is currently a local instance action.

We could add a checkbox to the blacklist modal if the video is owned, to send a `Delete` activity to remote instance.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/5abb9fbbd12e7097e348d6a38622d364b1fa47ed
