### ISSUE TITLE
Broken Embeds for Wordpress (Gutenberg Editor)

### ISSUE THREAD

**Issue by DeadSuperHero** [Chocobozzz/PeerTube#1350]
Hello, PeerTube team! I am currently maintaining a Wordpress installation that ships with a new and improved version of the Wordpress editor called [Gutenberg](https://github.com/WordPress/gutenberg).

![edit_post_ _we_distribute_ _wordpress](https://user-images.githubusercontent.com/401560/47535520-c0f4b700-d870-11e8-8d20-b68e155a5684.png)

One neat aspect of Gutenberg is that it can support many different types of embeds out of the box, and adding them into an article is very, very easy. All the user has to do is provide a URL of the media they intend to embed.

This problem may actually be more related to Wordpress instead of PeerTube, but I wanted to bring this up in case there was a problem with how PeerTube was providing the embed for videos.

**What happened?**

If I try to put in the URL of a PeerTube video into the embed box, I end up with a black embed frame and no player. This is the URL I used: https://video.deadsuperhero.com/videos/embed/916a048f-19f1-4d49-841b-eddeb66bed15

![edit_post_ _we_distribute_ _wordpress](https://user-images.githubusercontent.com/401560/47535583-02856200-d871-11e8-9279-2d9818b3cac1.png)

What should happen is that Wordpress should correctly grab the embed: https://video.deadsuperhero.com/videos/embed/916a048f-19f1-4d49-841b-eddeb66bed15

Unfortunately, when I try to provide the embed URL instead, I get the error message `Sorry, we could not embed that content.`

To be clear, this problem does *not* affect iframe embedding. If I take the embed code from PeerTube and put it into the Gutenberg editor, it works pretty well. But if I try to use the native embed type, I get the black static frame.

**Comment by Chocobozzz** [comment]
I think you have to whitelist video.deadsuperhero.com domain for oembed in wordpress configuration

**Comment by DeadSuperHero** [comment]
Thanks for the insight, @Chocobozzz !

According to [the Wordpress Oembed documentation](https://codex.wordpress.org/Function_Reference/wp_oembed_add_provider), I would need to do something like

`<?php wp_oembed_add_provider( 'http://site.com/watchvideo/*', 'http://site.com/oembedprovider' ); ?>`

I tried to follow some examples, and put this together in my blog theme's function.php file (formatting looks funky in the comment, but it's much cleaner in my theme). [You can see the output on a test article here.](https://staging.wedistribute.org/2018/11/video-embed-test/)

```
function dsh_video_embed() {
	wp_oembed_add_provider('https://video.deadsuperhero.com/videos/watch/*',
'https://video.deadsuperhero.com/videos/embed/', false);
}
add_action('init', 'dsh_video_embed');
```
I end up with a black rectangle. If I enable some hidden HTML, it shows the error message `Sorry`.

![video_embed_test__ _we_distribute](https://user-images.githubusercontent.com/401560/48518059-383cbb80-e81d-11e8-913b-d64d95ef82d4.jpg)

![video_embed_test__ _we_distribute](https://user-images.githubusercontent.com/401560/48518240-cdd84b00-e81d-11e8-99ce-226a57bdb015.jpg)

I looked into the console output and got this:

```
TypeError: "f is undefined". 
initCore https://video.deadsuperhero.com/client/standalone/videos/video-embed.f0504240b49b7fe07ce4.bundle.js:1:374164a
https://video.deadsuperhero.com/client/standalone/videos/video-embed.f0504240b49b7fe07ce4.bundle.js:1:368315a
https://video.deadsuperhero.com/client/standalone/videos/video-embed.f0504240b49b7fe07ce4.bundle.js:1:367633s
https://video.deadsuperhero.com/client/standalone/videos/video-embed.f0504240b49b7fe07ce4.bundle.js:1:367166 video-embed.f0504240b49b7fe07ce4.bundle.js:1:372827
e.prototype.init/</<
https://video.deadsuperhero.com/client/standalone/videos/video-embed.f0504240b49b7fe07ce4.bundle.js:1:372827
a/</<
https://video.deadsuperhero.com/client/standalone/videos/video-embed.f0504240b49b7fe07ce4.bundle.js:1:368315
a/<
https://video.deadsuperhero.com/client/standalone/videos/video-embed.f0504240b49b7fe07ce4.bundle.js:1:367633
a
https://video.deadsuperhero.com/client/standalone/videos/video-embed.f0504240b49b7fe07ce4.bundle.js:1:367212
```

Any ideas on how I might be able to work around this?

**Comment by Chocobozzz** [comment]
Should be fixed in https://github.com/Chocobozzz/PeerTube/commit/6385c0cb7f773f5212a96807468988e17dba1d6d

**Comment by gerhardbeck** [comment]
Actually the embed doesn't work yet (WP 5.6). It still says it can't embed the link.
It works if you offer Wordpress the download link with the mp4 ending and without access token.
WP can embed this link without problems.

**Comment by Chocobozzz** [comment]
@gerhardbeck  Please create a dedicated issue with appropriate web browser logs

**Comment by gerhardbeck** [comment]
Ok

29.12.2020 18:12:19 Chocobozzz <notifications@github.com>:
