### ISSUE TITLE
workaround to fix permission denied to local-production.json

### ISSUE THREAD

**Issue by EndeavourAccuracy** [Chocobozzz/PeerTube#1352]
**Problem**

With PeerTube v1.1.0-alpha.1, and node v8.12.0.
Pressing "Update configuration" results in an Error "Server error. Please retry later."
With 'journalctl -u peertube' showing
"err": "Error: EACCES: permission denied, open '/etc/peertube/local-production.json'"

**Workaround**

Create an empty
/etc/peertube/local-production.json
with the `touch` command, and then giving the file peertube.peertube ownership with `chown`.

**Comment by rigelk** [comment]
This is more an administration task than something related to the PeerTube code itself. If you think the documentation is lacking regarding the installation, feel free to make a PR to add the details :slightly_smiling_face:
