### ISSUE TITLE
Autoplay next video

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#1355]
A nice feature would be an autoplay button, that automatically play the next video listed in "other videos" (as on youtube).

**Comment by BO41** [comment]
does anyone really use this?
personally I am not a fan of this, and it makes only sense for music.

just my opinion :)

**Comment by Booteille** [comment]
I think it can be a good option when you watch some chronicles and want to see a lot of them in a the same row.

**Comment by JohnXLivingston** [comment]
My instance is dedicated to music, so it make sense :)

**Comment by DavidLibeau** [comment]
Please not autoplaying by default 😄

**Comment by rigelk** [comment]
Plus, autoplaying by default if considered an addictive UX pattern, isn't it? So I doubt it would be enabled by default.

**Comment by Booteille** [comment]
Sure! I would prefer it to be opt-in too.

**Comment by BO41** [comment]
would be great if someone could take a look at my PR.
I am having a small problem. Fixing this should make the whole issue solved :)

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/2137
