### ISSUE TITLE
New feature request : admin view that list unlisted (and private?) videos

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#1356]
Hello,

My peertube instance is dedicated to music videos. But we have a strict policy regarding licences. 
Despite this, some people are uploading videos that have nothing to do with music, or for which they have no legal rights. As long as these videos are public, I can moderate them.
But when there are unlisted, or private, I can't... 
I have to check in the storage/videos folder, find new videos uuids, and manually go to the video page. 

If people are uploading illegal videos, as unlisted or private, and share them on social networks for example, my responsability can be engaged.

An administration view, listing these videos, will be helpfull.

**Comment by Nutomic** [comment]
This is already possible on the "local videos" page. On the top right there's a checkbox "Display unlisted and private videos".\

**Comment by JohnXLivingston** [comment]
I have version 1.0.1 and I can't see this checkbox. Is this a feature from 1.1.0-alpha1 ?
