### ISSUE TITLE
Error 499 on large uploads (with nginx)

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#1359]
**What happened?**

When I upload a large file (4Go), the progress bar says "processing...", then I got a 499 http error code on server side (Client Closed Request).

**Additional information**
* PeerTube version or URL: https://www.yiny.org (version 1.0.1, on nginx)
* Browser name/version: Firefox 63

* browser console log:
Backend returned code 0, errorMessage is: Unknown error. main.1572864908cc797acead.js:1:423429

![image](https://user-images.githubusercontent.com/38844060/47677297-02fa6180-dbbf-11e8-9f6c-765feca453f4.png)

* nginx access logs:
[29/Oct/2018:20:00:05 +0000] "POST /api/v1/videos/upload HTTP/2.0" 499 0 "https://www.yiny.org/videos/upload" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0"

* peertube logs:
Oct 29 20:00:05 yiny peertube[15813]: [www.yiny.org:443] 2018-10-29 20:00:05.875 info: 82.124.0.0 - - [29/Oct/2018:20:00:05 +0000] "POST /api/v1/videos/upload HTTP/1.0" - - "https://www.yiny.org/videos/upload" "Firefox"

After that, the following file is in my storage/videos folder:
-rw-r--r--  1 peertube peertube 2.2G Oct 29 20:00 f8edb67880a043bcf6cf077418168572.mp4
(Note that it is only 2.2G, but the browser uploaded 3.71G)

The prune-storage script want to remove this file. 

There is no failed job.

The server is a little VM. I notice that during the upload, the processor is running hard.

**Comment by JohnXLivingston** [comment]
If I use the "import from an url" feature, and paste a direct link to this video file, it works. It's only the upload process who fails.

**Comment by poka-IT** [comment]
You have to change in your nginx configuration (/etc/nginx/sites-enabled/peertube) the client_max_body_size : 
```
  location / {
#    proxy_pass http://localhost:9000;
    proxy_pass http://tubep2p;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # For the video upload
    client_max_body_size 2G;
    proxy_connect_timeout       600;
    proxy_send_timeout          600;
    proxy_read_timeout          600;
  }
```

**Comment by JohnXLivingston** [comment]
It's already done:

`  location / {
    proxy_pass http://localhost:9000;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # Hard limit, PeerTube does not support videos > 8GB
    client_max_body_size 8G;
    proxy_connect_timeout       600;
    proxy_send_timeout          600;
    proxy_read_timeout          600;
    send_timeout                600;
  }
`

**Comment by scanlime** [comment]
Are you sure the failure is server-side rather than client-side? The last time I was debugging a very similar problem, it led me to this patch to remove a hardcoded 8GB limit on the client side: https://github.com/Chocobozzz/PeerTube/pull/1293

If the problem is server-side and you're already using a large enough client_max_body_size, the other thing to check is that your temporary storage for nginx POST body data (by default /var/lib/nginx) has enough temporary space for all the uploads you plan to have simultaneously.

I've been uploading very large files (largest so far is like 46 GB) without trouble since fixing these issues on my instance.

**Comment by JohnXLivingston** [comment]
My temporary storage is large enough: it is on the main partition, and there is more than 100Go free. 

I tried to increase all timeout in the nginx config (my server is slow). Didn't work.

I don't know what else I can try.

**Comment by JohnXLivingston** [comment]
I attached a screenshot from the browser network inspector. The browser didn't receive the request status... The 499 status is only visible in the nginx access logs. 
A web search says that the 499 status is specific to nginx.
I will try the tcpdump, but not today, I have no time.

**Comment by Chocobozzz** [comment]
I think it's the same issue than https://github.com/Chocobozzz/PeerTube/commit/8b917537af2217ad0c87d49fd2ffa693d46a499c

@JohnXLivingston try to increase to 20 minutes (directly on the server) to confirm it

**Comment by gegeweb** [comment]
I think it is the same as #1460
I had this error to, it seems using this setting fix this error with large video : 
`proxy_next_upstream         off;`

I just successfully uploaded a large video with which I had this error before adding this line in the proxy section.

**Comment by gegeweb** [comment]
> I had this error to, it seems using this setting fix this error with large video :
`proxy_next_upstream off;`

Unfortunatly, no, that doesnt fix this error.
I'll reopen an issue, unless someone can reopen it or the #1460 wich is a duplicate.

@JohnXLivingston Increasing the processing phase to 20 minutes doesn't fix it.
It seems that the log 499 of nginx appear when the client close connection before waiting a reply.
So increasing the reply delay on server side, doesn't fix, we don't have the 408 reply from the server.
But in this case, the client can be the proxy, not the browser.
And nothing in the Peertube logs or nginx logs when this error occurs.
Only the nginx 499 log a few seconds after the client side error.

I have always this error with large files/videos. A few rare times, it can work.
And I have this with Firefox, Safari and Chrome. And I have a 100 Mb/s fiber connexion.

I cannot say that this error was not present before the switch to 1.0.0 and following.

The server is a FreeBSD 11.2 in full zfs :
```
CPU: Intel(R) Atom(TM) CPU  C2338  @ 1.74GHz (1750.04-MHz K8-class CPU)
real memory  = 6442450944 (6144 MB)
avail memory = 4056580096 (3868 MB)
FreeBSD/SMP: Multiprocessor System Detected: 2 CPUs
FreeBSD/SMP: 1 package(s) x 2 core(s)
ada0: 600.000MB/s transfers (SATA 3.x, UDMA6, PIO 8192bytes)
```

**Comment by gegeweb** [comment]
I forgot that I tried to download with a wired and wireless connection. Same problem.

**Comment by JohnXLivingston** [comment]
I just upgraded my instance's server. And now it works. There must be a timeout or a memory limit somewhere...

**Comment by rdp** [comment]
Are you on AWS? I assume not behind a load balancer?  How long before it would fail, how long does it now take to succeed? Just curious on the outcome...

**Comment by JohnXLivingston** [comment]
> Are you on AWS? I assume not behind a load balancer? How long before it would fail, how long does it now take to succeed? Just curious on the outcome...

No AWS, no load balancer. I don't remember the details, it works now (with a new server, with more RAM and more CPUs).

**Comment by zimnyx** [comment]
In my case, when upload files larger then ~200MB was failing with 499, this fixed the issue:
# nginx config:
proxy_request_buffering off;

hope it helps.
