### ISSUE TITLE
Delete video not delete physicly

### ISSUE THREAD

**Issue by Dryusdan** [Chocobozzz/PeerTube#136]
Hello :)
Today, I delete to video on my peertube instance. But, the video doesn't delete, but the extension was erased. For exemple, after supression, video called : c7b7b6726a8326873fe8fc32804a2afbundefined

Regard

**Comment by Chocobozzz** [comment]
I'm sorry I can't reproduce. Please try to upload a new video, check the files created and delete it.

**Comment by Dryusdan** [comment]
🤔 
My bad, when I delete video with admin access (not own video) this delete video also...
But yesterday, I have 3 videos with not extension, just name finish by undefined

**Comment by Chocobozzz** [comment]
Seems to be another bug (maybe due to migrations?).

**Comment by Dryusdan** [comment]
I have not conserve video during migration (full reset ;) )
