### ISSUE TITLE
Connect OBS to peertube server

### ISSUE THREAD

**Issue by magicvince** [Chocobozzz/PeerTube#1364]
It could be nice if we could add a peertube server to server parameters in Obs Studio (hope there's obs users in this place to echo this request in obs dev forums)

**Comment by magicvince** [comment]
An easy way to upload screencast on peertube instance i.e. configuring obs to record a course and "podcast" it at the end of the captation on a peertube server. A kind of video podcast workflow

**Comment by rigelk** [comment]
Is it already a kind of 'workflow' that exists on OBS?

**Comment by Strit** [comment]
To me this sounds like a feature for streaming. Like Twitch.

**Comment by rigelk** [comment]
@magicvince I get it the idea, but unfortunately that suggestion is blocked by #151. OBS will probably be one of the first software we test it with once it is implemented though, judging by its widespread use in the live streaming community.

**Comment by magicvince** [comment]
Thanks

**Comment by liotier** [comment]
> @magicvince I get it the idea, but unfortunately that suggestion is blocked by #151. OBS will probably be one of the first software we test it with once it is implemented though, judging by its widespread use in the live streaming community.

[PeerTube now offers Live streaming](https://github.com/Chocobozzz/PeerTube/pull/3250 )... I saw the announcement on Reddit and immediately thought "Hey, I could use this instead of Twitch !" - looks like others have thought about it years before me...

**Comment by gytisrepecka** [comment]
According to [OBS discussion](https://ideas.obsproject.com/posts/1202/peertube-livestream-support), PeerTube should approach OBS with details (API endpoints and such) which would be reviewed and possibly added to OBS.

I think having PeerTube among other streaming services within OBS would give platform a great boost since OBS is preferred option for streaming.

**Comment by Utopiah** [comment]
Even though making steamers more aware of PeerTube is great I'm not sure how that's going to be practically easier than the existing `Custom...` service. All PeerTube servers are different. That's the beauty of being decentralized, unlike incumbents like YouTube or Twitch.
