### ISSUE TITLE
Error 400 on large file upload

### ISSUE THREAD

**Issue by MonsieurPoutounours** [Chocobozzz/PeerTube#1373]
**What happened?**

Trying to upload a large video file (4 GB), i get a "400 Error - Bad request" in the browser after the upload bar has completed.
My peertube instance is a Debian 9 setup trough production documentation. Web server is nginx.

I tried setting a higher value for client_max_body_size in nginx, with no result.

**What do you expect to happen instead?**

Upload successful.

**Steps to reproduce:**

1. Setup a Debian 9 instance with production documentation

2. Upload a + 4 GB video file

3. Wait until the upload is complete and be prepared to see the error, which disappear quickly.

**Additional information**
* PeerTube version or URL: 1.0.1
* Browser name/version: Firefox 63 for Windows
* NodeJS version: 11.1.0

* Link to browser console log if useful: 
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): 1.2.3.4 - - [04/Nov/2018:08:02:53 +0000] "POST /api/v1/videos/upload HTTP/2.0" 400 232 "https://tube.poutounours.me/videos/upload" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0"

**Comment by scanlime** [comment]
if I'm understanding correctly, this is failing *after* nginx has received the file, and the peertube server is then rejecting it for an unspecified reason.

we definitely need better error reporting in this part of the server. I've seen this happen for media files that were truncated somehow, or for files that are in formats or with extensions that the server isn't happy with.

also double-check you have sufficient temporary space in /var/lib/nginx for the upload

**Comment by Chocobozzz** [comment]
@MonsieurPoutounours Keep the console opened while your upload the video, you should have the error details displayed. And the network tab should help us to see what's going on too.
