### ISSUE TITLE
Can't join instances after renaming of mine

### ISSUE THREAD

**Issue by maxdrash** [Chocobozzz/PeerTube#1376]
**What happened?**
Hello.

I renamed my PeerTube instance and since that renaming, I can no longer make the federation work via ActivityPub.

Please, find the log with:
"myoldinstancename00.net" was the old name.
"myinstance01.net" the current new name
"theirinstance02.net" the instance that i want to join.

I'm not sure how to fix this, do you have any idea?

Thank you.

![screenshot_2018-11-05 following list](https://user-images.githubusercontent.com/17526713/48012321-0e4f0f00-e122-11e8-9673-404a1d959e92.png)

[acp_new_instance.txt](https://github.com/Chocobozzz/PeerTube/files/2549613/acp_new_instance.txt)

**Additional information**
* PeerTube version or URL: v1.0.1
* Browser name/version: Firefox 63.0
* NodeJS version: 8.12.0

**Comment by rigelk** [comment]
There is a band aid for that kind of situation: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#update-hostjs
