### ISSUE TITLE
Add manual video validation by a moderator

### ISSUE THREAD

**Issue by Dryusdan** [Chocobozzz/PeerTube#138]
Hello
After two bad upload today (ru serie without copyright >< ), I thing is good to validate video on upload ... (And add option "validate all video or check each video" ?). After, it's cool to etablish a reputation for each user.
For exemple, if user upload 10 good vidéos, after it doesn't not need validate. :)

I think, my english is very bad tonight :(

Regard

**Comment by Chocobozzz** [comment]
What do you mean by "validation"?

**Comment by Dryusdan** [comment]
A step between upload and publication :)

**Comment by Chocobozzz** [comment]
By an human person to check copyrighted videos or by the client to check the mime/type or...?

**Comment by Dryusdan** [comment]
By an human person to check copyright, nsfw etc... :)

**Comment by rigelk** [comment]
@Nutomic I will tackle the issue as soon as I get some time!

**Comment by Chocobozzz** [comment]
@Nutomic https://github.com/Chocobozzz/PeerTube/commit/017c3dcadf71aef4c1a854e4867b77931747f06e & https://github.com/Chocobozzz/PeerTube/commit/1cd3facc3de899ac864e979cd6d6a704b712cce3 should help you to moderate videos of your instance

**Comment by joshmorel** [comment]
I agreed to take this one on! My approach will be to split this into 2 PRs. I'll detail components/process to confirm my assumptions. If I've got anything wrong please chime in.

PR 1 - Video Quarantine Feature:

* Add config option `quarantine.enabled` set to `false` by default
* If enabled, for normal users (moderators/admins will be exempt) prior to `Published` state videos will be put in `Quarantined` state in which they cannot be viewed by public 
* Moderators will have list of quarantined videos to view and publish or, if there is an issue, then blacklist/delete
* To facilitate timely publishing moderators will be emailed whenever a video reaches quarantined state

PR 2 - "Whitelisted" Users:

* Not sure what to call this yet (whitelisted?), but it would be an attribute for normal users to bypass video quarantine
* Can be enabled/disabled by admins in manage user list
* Alternately through configured threshold, if they have published *X* videos they will be "whitelisted" automatically

**Comment by joshmorel** [comment]
@Nutomic  / @Dryusdan  With the holidays over aiming to get this done this month. 

I'm working on UI design right now, as moderator reviewing "quarantined" videos, if you do not release the video for public viewing, would the alternate be to just delete the video, or to blacklist the video with a reason (e.g. to give user opportunity to flag as NSFW) or perhaps either?

**Comment by Nutomic** [comment]
@joshmorel Maybe you could give options to delete the video (with message), ask user to update the video (with message and new review afterwards). It might also be useful to block or delete a user account directly.

**Comment by joshmorel** [comment]
@Nutomic - Getting close. I'm proposing that instead of messaging the user to change video for release use the blacklist video feature. Part of the reason is selfish - I can reuse existing code - but more importantly it seems like a natural flow achieving the same thing. Is not the point of blacklist that the video should not be displayed for some reason?

Although I'm curious what are the scenarios where a video would be inappropriate (and therefore blacklisted) but then updated and now appropriate. Is lack of NSFW flag the only thing? If something is copywrited or just really nasty then I assume it could never be changed to somehow be appropriate. Maybe something else would be spoilers without an appropriate warning (e.g. "[SPOILERS] ..." title).

**Comment by Nutomic** [comment]
@joshmorel Late comment regarding blacklisting: even when done on the origin instance, videos are still federated and watchable on other instances. So its not a solution to unpublish a video.

**Comment by Chocobozzz** [comment]
@joshmorel In 1.2, you can unfederate videos you blacklist.

**Comment by joshmorel** [comment]
@Nutomic I put in a PR #1637 with this feature so hopefully it will be in a release soon.

An overview of the feature: 

* This feature is disabled by default but can be enabled in config file or custom config page   
![peertube-quarantine-video-config](https://user-images.githubusercontent.com/10546720/52884723-c5552080-313c-11e9-88f9-daf0273dd2b2.png)
* Moderators have "bypass quarantine" right so they won't need to release their own videos 
* When a user uploads a video, moderators will receive notification as part of new web/email notifications system ![peertube-quarantine-notification](https://user-images.githubusercontent.com/10546720/52884804-1533e780-313d-11e9-8cb1-662fbb347f38.png)
* The video will be in "quarantine" and cannot be viewed by anyone except moderator or own user (even with direct link). It will also not be federated to following instances until released ![peertube-quarantined-video-views](https://user-images.githubusercontent.com/10546720/52884814-1e24b900-313d-11e9-88ea-c08183b1258d.png)
* The quarantined video list will be under Administration>Moderation. You can multi-select and quickly release videos if you feel confident based on name/thumbnail/user. If you feel the video requires further review you can click through to watch it and release it there OR take another action based on already implemented features - e.g. delete the video, delete the user ![peertube-quarantine-list](https://user-images.githubusercontent.com/10546720/52884837-30065c00-313d-11e9-8e5d-14764166ba56.png)

> ask user to update the video (with message and new review afterwards).

The new notification feature actually help a lot here. For this situation I propose using comments section as per the example below. Both user and moderator will get notifications so will know when to follow-up:

![peertube-quarantine-release-discussion-flow](https://user-images.githubusercontent.com/10546720/52883302-76a58780-3138-11e9-897b-13bf7850a59b.png)

Once this in production we can get a better idea of most significant workflow improvement opportunities. One thing I can envision is a "bypass quarantine" right for normal "trusted users" but this can be added later.

**Comment by Nutomic** [comment]
@joshmorel Awesome! One option I would like to see is an option to validate videos automatically once one (or two or three) videos by a user have been approved. So only the first videos by a user would need manual validation. But of course that can be added later.

**Comment by Chocobozzz** [comment]
> One thing I can envision is a "bypass quarantine" right for normal "trusted users" but this can be added later.

Implemented in https://github.com/Chocobozzz/PeerTube/commit/1eddc9a74f9a80fa5d0cb25fceb3fc47a1a3c14a
