### ISSUE TITLE
Display frame of the current time when buffering

### ISSUE THREAD

**Issue by Booteille** [Chocobozzz/PeerTube#1380]
**What happened?**
When the video is buffering, instead of staying on the current frame, the player is showing the first frame of the video.

**What do you expect to happen instead?**
I would expect the player to display the actual frame of the video.

**Steps to reproduce:**

1. Start a video

2. Wait until you have to buffer (Easier to check on bad networks, I suppose.)

**Additional information**
* PeerTube version or URL: Tried on https://peertube.mastodon.host/
* Browser name/version: Firefox Developper 64.0b6
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Please could you try to reproduce on https://peertube2.cpy.re/videos/watch/1221d84f-5ace-4108-b286-d199c97a5025 to see if our new player fixes this issue?

**Comment by Booteille** [comment]
Hi!

It seems to be good. Thanks!
