### ISSUE TITLE
Add Welsh/Cymraeg (cy) locale

### ISSUE THREAD

**Issue by carlmorris** [Chocobozzz/PeerTube#1381]
Please add Welsh/Cymraeg (cy) locale.

Thanks.

(Sorry for the duplicate issue which was created in error, and now closed.)

**Comment by carlmorris** [comment]
Merci Ididry :slightly_smiling_face:

**Comment by rigelk** [comment]
Thanks for the faster-than-light addition @lucas-dclrcq :relaxed:

**Comment by ldidry** [comment]
You're welcome 😊
