### ISSUE TITLE
Unable to subscribe to a channel from Pleroma

### ISSUE THREAD

**Issue by lord-re** [Chocobozzz/PeerTube#1383]
**What happened?**
From Pleroma when you try to follow a channel you are forever waiting : "pending request"

**What do you expect to happen instead?**
It should be accepted (by probably returning a valid **Accept** activity back).

**Steps to reproduce:**

1. Send a follow request to any peertube channel

**Additional information**
* PeerTube version or URL: Every Peertube instances i tested act the same
It works well with a mastodon account.

**Comment by Chocobozzz** [comment]
> It should be accepted (by probably returning a valid Accept activity back).

Are you sure we don't return an `Accept`? Because following a channel seems to work on Mastodon, and from the code I can see we send back the `Accept`: https://github.com/Chocobozzz/PeerTube/blob/develop/server/lib/activitypub/process/process-follow.ts#L55

**Comment by lord-re** [comment]
I created an isuse on pleroma's bug tracker and that's what i've been told : https://git.pleroma.social/pleroma/pleroma/issues/364

**Comment by Chocobozzz** [comment]
@lord-re Does it work if you try to follow a peertube account?

**Comment by Chocobozzz** [comment]
For example framasoft@framatube.org

**Comment by lord-re** [comment]
I have the same behavior. In my logs i see that i'm sending the request but no answer then : 

```
17:38:47.259 request_id=2lnl9cs7dncbhaat10000063 [info] POST /api/friendships/create.json
17:38:47.323 [info] Relaying https://pleroma.lord.re/activities/6af80923-66c4-437c-8039-ea64a34d77ac out
17:38:47.323 [info] Sending https://pleroma.lord.re/activities/6af80923-66c4-437c-8039-ea64a34d77ac out via AP
17:38:47.327 [info] Federating https://pleroma.lord.re/activities/6af80923-66c4-437c-8039-ea64a34d77ac to https://framatube.org/inbox

**Comment by Chocobozzz** [comment]
Thanks. I was able to check the logs. 

It seems Pleroma does not sign the Date header in http signature, which is mandatory for PeerTube.

**Comment by DeadSuperHero** [comment]
@Chocobozzz Date headers in http signatures are now signed: https://git.pleroma.social/pleroma/pleroma/merge_requests/847

![local_videos_-_deadsuperhero_video](https://user-images.githubusercontent.com/401560/53191866-d8934080-35c1-11e9-8bc4-8d4fa6235df2.png)


After some testing, I was able to generate a follow notification from Pleroma to PeerTube, but the Pleroma end still says that the request is awaiting approval.

**Comment by Chocobozzz** [comment]
@DeadSuperHero Send it to root@peertube3.cpy.re so I can check the logs

**Comment by DeadSuperHero** [comment]
@Chocobozzz done! Follow request sent from sean@social.deadsuperhero.com

**Comment by Chocobozzz** [comment]
The accept was sent by peertube at Feb 22, 2019, 5:57:27 PM (UTC+1):

```
{
  "uri": "https://social.deadsuperhero.com/users/sean/inbox",
  "signatureActorId": 2,
  "body": {
    "type": "Accept",
    "id": "https://social.deadsuperhero.com/users/sean/accepts/follows/2",
    "actor": "https://peertube3.cpy.re/accounts/root",
    "object": {
      "type": "Follow",
      "id": "https://social.deadsuperhero.com/users/sean/follows/2",
      "actor": "https://social.deadsuperhero.com/users/sean",
      "object": "https://peertube3.cpy.re/accounts/root"
    }
  }
}
```

Do you have something in your logs at this time?

**Comment by buoyantair** [comment]
I have also not been able to subscribe to a lot of peertube channels just because I am using Plemora. Although I don't have anything else to add to this conversion but that when I click subscribe, it attempts to redirect me to plemora (permissions page I assume), and then nothing happens.

**Comment by ealgase** [comment]
I'm also having this issue with Mastodon as of late.

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/c28bcdd10a5a0d661e51c96345bbd6c4dcc43bc9

Pleroma does not seem to support `acct:my_account@host` keyId. Ping @lanodan

**Comment by lanodan** [comment]
> Pleroma does not seem to support acct:my_account@host keyId.

AFAIK Pleroma only supports WebFinger to get an ActivityPub actor, using WebFinger in the rest of the protocol is really weird, specially as WebFinger is even less than optionnal in the ActivityPub specification.
So I don’t think this is a bug on pleroma’s side.

**Comment by Chocobozzz** [comment]
I don't think it's a bug so either. It was just to let you know

**Comment by tusooa** [comment]
> The accept was sent by peertube at Feb 22, 2019, 5:57:27 PM (UTC+1):
> 
> ```
> {
>   "uri": "https://social.deadsuperhero.com/users/sean/inbox",
>   "signatureActorId": 2,
>   "body": {
>     "type": "Accept",
>     "id": "https://social.deadsuperhero.com/users/sean/accepts/follows/2",
>     "actor": "https://peertube3.cpy.re/accounts/root",
>     "object": {
>       "type": "Follow",
>       "id": "https://social.deadsuperhero.com/users/sean/follows/2",
>       "actor": "https://social.deadsuperhero.com/users/sean",
>       "object": "https://peertube3.cpy.re/accounts/root"
>     }
>   }
> }
> ```
> 
> Do you have something in your logs at this time?

This looks really problematic to me.
- `id` (of Accept) and `actor` have to have the same host
- the Follow's id has to be what Pleroma sends, which is in the format of https://xxx/activities/xxxxx .

**Comment by Chocobozzz** [comment]
@tusooa You're commenting a 3/4 years old message. I don't think it's the case anymore.
