### ISSUE TITLE
Add தமிழ் (ta) in the Locale

### ISSUE THREAD

**Issue by balogic** [Chocobozzz/PeerTube#1384]
Please add தமிழ் (ta) in the Locale

**Comment by ldidry** [comment]
தமிழ் has been added to Zanata: https://trad.framasoft.org/iteration/view/peertube/develop/languages/ta
The documentation on how use Zanata is on https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/translation.md.

Happy translating 🙂
