### ISSUE TITLE
Federated video that is blacklisted at source, isn't removed from federated instance 

### ISSUE THREAD

**Issue by techknowlogick** [Chocobozzz/PeerTube#1387]
**What happened?**
Video from Instance **A** that has been federated to instance **B** was blacklisted on Instance **A**, however is still viewable on instance **B**

**What do you expect to happen instead?**
Once the video is blacklisted on Instance **A**, then instance **B** is told and can remove it.

**Additional information**
* PeerTube version or URL: 1.0.0

**Comment by JohnXLivingston** [comment]
This bug is already reported here : https://github.com/Chocobozzz/PeerTube/issues/1347
