### ISSUE TITLE
keep the original file for download

### ISSUE THREAD

**Issue by tomamplius** [Chocobozzz/PeerTube#1388]
Thanks fro your work on peertube.

We want for our instance keep the original file just for download.
In our case, the video format is better than the video format for web view. 
But we want that user can download this file (available under Creative Commons ) with the better quality for rework or public projection.
It is possible to keep the video like /storage/videos/[uuid]-original.mp4 and allow to download it

thanks a lot

**Comment by Chocobozzz** [comment]
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/733

**Comment by rzr** [comment]
Off course this should work with LibreJS enabled too:
https://github.com/Chocobozzz/PeerTube/issues/1254#issuecomment-484594148#
