### ISSUE TITLE
Not Found error when refreshing a paginated channel page

### ISSUE THREAD

**Issue by Booteille** [Chocobozzz/PeerTube#1389]
**What happened?**
I watched a video I found on a specific channel then I used the "previous" button of Firefox.
Instead of getting the last page (the list of videos of the channel), I got a Not Found error:  `Sorry, but we couldn't find the page you were looking for. `
The error appared when trying to go on this page: https://peertube.mastodon.host/video-channel/c2fbac48-b069-42dd-b24c-7969c14a1374/videos?sort=publishedAt&page=1

After that, I just went back to the user page (https://peertube.mastodon.host/accounts/datagueule@peertube.datagueule.tv/videos), then to the channel page () and tried to figure how to reproduce the bug. I just had to scroll down until I get this url: 
Then, I just tried to refresh the page and the error was back.

Seems related to  #787

**What do you expect to happen instead?**
I would expect to be able to refresh the page containing pagination without getting any error.

**Steps to reproduce:**

1. Go to a channel page: https://peertube.mastodon.host/video-channels/c2fbac48-b069-42dd-b24c-7969c14a1374@peertube.datagueule.tv/videos

2. Scroll down until you get an URL with pagination: https://peertube.mastodon.host/video-channel/c2fbac48-b069-42dd-b24c-7969c14a1374/videos?sort=-publishedAt&page=1

3. Refresh the page (ctrl + r)

**Additional information**
* PeerTube version or URL: https://peertube.mastodon.host/ v1.1.0-alpha.2
* Browser name/version: Firefox Developper Edition v64.0b8
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Booteille** [comment]
Actually, I found that the url is not updating correctly when using pagination:

It should be:

> https://peertube.mastodon.host/video-channels/c2fbac48-b069-42dd-b24c-7969c14a1374@peertube.datagueule.tv/videos?sort=-publishedAt&page=1

instead of

> https://peertube.mastodon.host/video-channel/c2fbac48-b069-42dd-b24c-7969c14a1374/videos?sort=-publishedAt&page=1

Note the missing `s` at `video-channel` and the missing `@peertube.datagueule.tv` at channel ID.

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed in https://github.com/Chocobozzz/PeerTube/commit/8cf998733496d44fa564e2e252356b871756c984
