### ISSUE TITLE
display bug when you downgrade useraccess

### ISSUE THREAD

**Issue by Dryusdan** [Chocobozzz/PeerTube#139]
Hey
THis is a little bug, when you set a user admin or modo, and when you remove this access and set users. The account can't access on admin area but icone is display (it vanished after logout / login).

**Comment by rigelk** [comment]
Bug is still reproducible on the development branch. It can easily be reproduced by using an Administrator account and remove your own admin rights in the web interface. Somehow the rights change do not update the interface (until the next login cycle as said).

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/f8b8c36b2a92bfee435747ab5a0283924be76281

We forbid admin to change `root` role and we remove the user token after changing a user role.
