### ISSUE TITLE
Add a "creation date" input in the "Update" video options

### ISSUE THREAD

**Issue by klorydryk** [Chocobozzz/PeerTube#1391]
As the "creation date" can be very different of the "upload date", to have an input in the "Update" video options and to add this "creation date" in the video information is important for the visitor to know. And to understand the content (I think about political and activism communication, mainly).

**Comment by McFlat** [comment]
For sure they are two different things, and PeerTube community could benefit from having both `creation date` and `upload date`, and a `modified date` perhaps.

**Comment by BO41** [comment]
isn't this a duplicate to https://github.com/Chocobozzz/PeerTube/issues/946? which already has some people working on it
