### ISSUE TITLE
Installing on OpenBSD 6.4

### ISSUE THREAD

**Issue by 22decembre** [Chocobozzz/PeerTube#1392]
**What happened?**

I am trying to install PeerTube on a fresh installed OpenBSD 6.4 (latest stable at date of report).

If I use prebaked install zip (eg : following the production guide), I get linking errors, eventhough I use Clang, as shown [here](https://github.com/Chocobozzz/PeerTube/issues/160). :

```
node:/usr/lib/libstdc++.so.57.0: /usr/lib/libc++abi.so.0.1 : WARNING: symbol(_ZTVN10__cxxabiv116__enum_type_infoE) size mismatch, relink your program
node:/usr/lib/libstdc++.so.57.0: /usr/lib/libc++abi.so.0.1 : WARNING: symbol(_ZTVN10__cxxabiv120__function_type_infoE) size mismatch, relink your program
node:/usr/local/lib/libvips-cpp.so.51.1: /usr/lib/libc++abi.so.0.1 : WARNING: symbol(_ZTVN10__cxxabiv117__class_type_infoE) size mismatch, relink your program
node:/usr/local/lib/libvips-cpp.so.51.1: /usr/lib/libc++abi.so.0.1 : WARNING: symbol(_ZTVN10__cxxabiv120__si_class_type_infoE) size mismatch, relink your program
[localhost:9000] 2018-11-11 12:31:20.224 error: uncaughtException: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 }
Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 }
    at Connection.parseR (/var/www/peertube/versions/vanilla/node_modules/pg/lib/connection.js:441:9)
    at Connection.parseMessage (/var/www/peertube/versions/vanilla/node_modules/pg/lib/connection.js:357:19)
    at Socket.<anonymous> (/var/www/peertube/versions/vanilla/node_modules/pg/lib/connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peertube@1.0.0 start: `node dist/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

(Yarn can run all the way with Clang apparently.)

If trying to compile from source, it won't build the "dist" repository.

NB : I needed to install some extra packages not described in dependencies: gyp, postgresql-contrib, and I built libvips from source. I think it should be written in install doc if relevant.

**What do you expect to happen instead?**

That either building from source or prebaked tarball would run.

**Additional information**
* PeerTube version or URL: v1.0.1
* Browser name/version: Not relevant
* NodeJS version: v8.12.0

**Comment by 22decembre** [comment]
Tried again. I compiled with the 1.0.1 source. Did the double *yarn*. When I try to run, I get that :

`> peertube@1.0.1 start /var/www/peertube/versions/PeerTube-1.0.1
> node dist/server

module.js:550
    throw err;
    ^

Error: Cannot find module '/var/www/peertube/versions/PeerTube-1.0.1/dist/server'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peertube@1.0.1 start: `node dist/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

And indeed, there is no *dist* directory.

**Comment by Chocobozzz** [comment]
@22decembre You should not have to compile manually peertube. Just download, extract the zip and install yarn modules. If you were able to install yarn modules in 1.0.1 using the source files, you should be able to install yarn modules with the compiled tarball too.

**Comment by 22decembre** [comment]
But when I do that, as you say (download and extract the zip, install yarn modules) I get the errors described at the top of the thread (linking errors apparently).

**Comment by 22decembre** [comment]
Maybe I should not use clang but gcc/g++ instead. But then I need to install it from source as the packaged version is too old (4.9). Sounds fun. I tell you more when I know.

**Comment by 22decembre** [comment]
So installing with gcc 6 is still wrong (linking errors).

Any suggestions ?

**Comment by Chocobozzz** [comment]
I'm sorry but I can't really help here. So unfortunately we don't support OpenBSD.
