### ISSUE TITLE
Allow users to change their email address

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1393]
It looks like only mods can change the email address for a user, but there is no way for the user to change it themselves.

**Comment by McFlat** [comment]
This would be a good feature, for sure

**Comment by bristow** [comment]
Okay, but in the admin panel, we need to be able to disable this feature.

**Comment by rigelk** [comment]
@bristow why might you want to disable it?

**Comment by bristow** [comment]
Because we use Peertube with french colleges and lycees. We send login and password to the institution's email address and it is the 'digital' referent who uses this login. He must not be able to modify this official email.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/0ba5f5baade94a051710d9d9d408ac8083c14ac6 & https://github.com/Chocobozzz/PeerTube/commit/d1ab89deb79f70c439b58750d044d9cadf1194e5

@bristow You can hide the block with CSS

**Comment by bristow** [comment]
> @bristow You can hide the block with CSS

Thanks. Can you tell me what is the CSS code ?

**Comment by Chocobozzz** [comment]
@bristow 

```
.change-email {
  display: none;
}
```
