### ISSUE TITLE
searching for tags is case sensitive

### ISSUE THREAD

**Issue by erdmark** [Chocobozzz/PeerTube#1397]
**What happened?**
When searching for a tag you have to spell it case sensitive.

**What do you expect to happen instead?**
I think searching should be case insensitive

**Steps to reproduce:**

1. Go to https://peertube.social/search?search=Alternative
-> 47 Results

2. Go to https://peertube.social/search?search=alternative
-> 163 Results

**Comment by BO41** [comment]
*https://peertube.social/search?search=alternative

**Comment by JohnXLivingston** [comment]
Already reported here: https://github.com/Chocobozzz/PeerTube/issues/1095
