### ISSUE TITLE
Automatic YouTube channel mirroring

### ISSUE THREAD

**Issue by LoveIsGrief** [Chocobozzz/PeerTube#1398]
Hello, first of all thanks for writing this awesome software and making a change on this planet.

For further adoption, with the release of the [Peertubify addon](https://gitlab.com/Ealhad/peertubeify), I think it would be interesting to add the option for instances to mirror selected channels Youtube --> Peertube and vice versa. Seperate issues could be created for different websites e.g mirroring between vimeo, dailymotion and whatever other website exists.

This would allow content providers to have one entry / distribution point and for users to find more content on peertube.

**Comment by BO41** [comment]
as far as I know, you can already import videos directly from youtube.
I think this makes it easy enough to use/switch to peertube

**Comment by LoveIsGrief** [comment]
Am I mistaken to assume the existing feature is manual and done with the CLI and not the UI?

**Comment by rigelk** [comment]
@LoveIsGrief it is indeed one way (only importing videos), but it is also available in the UI.

**Comment by Nutomic** [comment]
I think the intention with this issue is that any new videos from a specific Youtube channel get automatically imported to Peertube. Afaik the current functionality only lets you import specific videos )so you would have to do it manually every time).

**Comment by LoveIsGrief** [comment]
@Nutomic is correct. 

Additionally it could be in both directions. Sending videos from peertube to youtube (and possibly other websites in the future) might be appealing for content creators. One free, unified distribution point. But maybe that's out of scope, I dunno.

**Comment by LoveIsGrief** [comment]
Indeed, it is! I searched for mirroring, that's why I couldn't find it.

Even the rationale is the same. I'll close this :slightly_smiling_face:

**Comment by mister-monster** [comment]
I actually found this issue (and multiple others) after i had almost completed a Python tool to do this, so i figured i would comment about it here.

https://github.com/mister-monster/YouTube2PeerTube

This is a tool that watches YouTube channels, and when new videos are found it mirrors them to a PeerTube channel.

@Nutomic
