### ISSUE TITLE
Playlists support

### ISSUE THREAD

**Issue by christophehenry** [Chocobozzz/PeerTube#14]
I open this issue to discuss the working of playlists. My proposition follows.
### DB model
1. a playlist belongs to one and only one user,
2. a user has zero or more playlists,
3. a playlist contains zero or more ordered videos,
4. a video belongs to zero or more playlists (maybe not?)
5. a playlist has only one name,
6. a playlist has only one creation date,
7. a playlist has only one update date (maybe not?)
### API routes
1. `get /playlist/:id`: get informations about playlist (author, name, creation date, etc.)
2. `delete /playlist/:id` suppress a playlist
3. `get /playlist/:id/videos`: get videos in the playlist
4. `put /playlist/:id/video/:id`: add a video to the playlist
5. `delete /playlist/:id/video/:id`: remove a video from the playlist
6. `patch /playlist/:id/name/:name`: rename the playlist

We need to discuss about reordering the playlist, too.

**Comment by Chocobozzz** [comment]
For the DB model, I would add a playlist visibility: public/private.

I like the reordering API of Spotify: https://developer.spotify.com/web-api/reorder-playlists-tracks/

My opinion:
 * A playlist belongs to one user so I would prefix each route with `/users/userId/`. 
 * `playlist` -> `playlists` to keep coherency
 * Add a video to the playlist throught the POST method and body parameters
 * Suppress a video from the playlist throught the DELETE method and body parameters
 * Rename a playlist is part of the modify playlist route

**API route**

0. `get /users/:userId/playlists/` &rarr; get user playlists
1. `get /users/:userId/playlists/:id` &rarr; get playlist information (videos too?)
2. `delete  /users/:userId/playlists/:id` &rarr; suppress a playlist
3. `get /users/:userId/playlists/:id/videos` &rarr; get videos of the playlist
4. `post /users/:userId/playlists/:id/videos` &rarr; add video(s) to the playlist
5. `put /users/:userId/playlists/:id/videos` &rarr; reorder playlist
6. `delete /users/:userId/playlists/:id/videos` &rarr; delete video(s) from the playlist
7. `put /users/:userId/playlists/:id` &rarr; change playlist informations (name, visibility?)

For the MongoDB schema I think it would be better to create a sub document in `Users`.
Something like: 

    {
      createdDate: {
        type: Date,
        default: Date.now
      },
      password: String,
      username: String,
      role: String,
      playlists: [
        {
          name: String,
          visibility:{
            type: String,
            enum: ['PUBLIC', 'PRIVATE']
          },
          createdDate: {
            type: Date,
            default: Date.now
          },
          updatedDate: {
            type: Date,
            default: Date.now
          },
          videos: [
            {
              id: Videos.ObjectID
              position: number
            }
          ]
        }
      ]
    }

**Comment by christophehenry** [comment]
I would use `PATCH` to reorder the playlists as it is it's definition: 

> The PATCH method applies partial modifications to a resource.

**Comment by Chocobozzz** [comment]
Now we use a relational DBMS, the database scheme is changed.

My proposal:

    playlistTable:
      {
        name: String,
        visibility: {
          type: String,
          enum: ['PUBLIC', 'PRIVATE']
        },
        createdAt: {
          type: Date,
          default: Date.now
        },
        updatedAt: {
          type: Date,
          default: Date.now
        },
        userId -> references the user that own the playlist
      }

    playlistVideoTable:
      {
        // Position of the video in the playlist
        position: {
          type: Number,
          default: 0
        },
        videoId -> references a video
        playlistId -> references a playlist
      }

**Comment by DimitriGilbert** [comment]
I was wondering about channel's playlist (or even playlists for videos like what is hacked here https://youtu.be/5NJSCRPeNpU?t=11m0s  the annotation link bottom rigth of the video)
For this reason I suggest to replace `userId` by something like `ownerId` and `ownerType`. It would make the playlist system very versatile at a very reasonnable cost (the GUI for it could come later but everything would be in place for it to work in the future)

**Comment by Chocobozzz** [comment]
I updated my comment to replace `userId` by `actorId`. An actor is a user or a channel.

**Comment by DimitriGilbert** [comment]
works for me :)

**Comment by 6543** [comment]
Any progress at the moment?

**Comment by Chocobozzz** [comment]
@6543 https://github.com/Chocobozzz/PeerTube/tree/feature/playlists

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/1708

**Comment by 6543** [comment]
Tanks for the great work!

**Comment by rzr** [comment]
is this feature released in any version ? Apparently not in current version:

https://github.com/Chocobozzz/PeerTube/releases/tag/v1.2.1

**Comment by 6543** [comment]
@rzr   Pre-Release v1.3.0-rc.1
