### ISSUE TITLE
PeerTube refuses to work on Pale Moon browser

### ISSUE THREAD

**Issue by ajhcasual** [Chocobozzz/PeerTube#1401]
**What happened?**

I tried to visit https://video.blender.org/ which was in a TorrentFreak article about how Youtube censorship glitches blocked the Blender project channel.

I am still trying to wrap up my personal summer project to boycott and replace all Google products I have been using.  I received an email article from DuckDuckGo's mailing list which reminded me that PeerTube is a good candidate for boycotting YouTube as both a viewer and content creator.  I wanted to quickly see how PeerTube looks and feels this morning.

Anyway, so I see a blank page with:

"We are sorry but it seems that PeerTube is not compatible with your web browser.
Please try with the latest version of Mozilla Firefox.
If you think this is a mistake, do not hesitate to report it."

I'm pretty sure it is just an unrecognized browser label string.  If this is the case and PeerTube is otherwise fine running on Pale Moon, then please mark this as a feature request to recognize "Pale Moon" instead of throwing an error.  I use Pale Moon because I don't get any sound from Firefox on my netbook running Lubuntu.  This is the case since Mozilla (stupidly, in my opinion) removed support for ALSA and therefore screwed all Lubuntu users, and users of Linux distros which run without the heavier PulseAudio daemon (which only works on top of ALSA anyway, per my understanding).  I am somebody who likes to hear sound from on-line multimedia!

**What do you expect to happen instead?**

To be able to view the PeerTube install on that site.

**Steps to reproduce:**

1.  Install Pale Moon (27.9.4 32-bit) on Ubuntu (specifically Lubuntu 14.04.5 32-bit).  I used a personal DEB repository of an OpenSUSE member, my sources.list line is:
`deb http://download.opensuse.org/repositories/home:/stevenpusser/xUbuntu_14.04/ /`

1a.  Adblock Latitude 5.0.1 is my only installed and active browser extension.  This might be related or not.

1b. Preferences: Advanced: General tab: set "User Agent Mode" to "Firefox Compatibility"

2. Visit https://video.blender.org/

3. Observe the aforementioned error page.  On a side note, the error page linking to create a new github issue directly was very convenient :)

**Additional information**
* PeerTube version or URL: https://video.blender.org/
* Browser name/version: Pale Moon 27.9.4 32-bit
* NodeJS version:  (I am not the operator of that instance of peertube)

* Link to browser console log if useful: https://pastebin.com/Q28LjLJd
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): N/A

**Comment by Nutomic** [comment]
Could you try to change your user agent to verify that it causes the problem? There should be various plugins to do that.

**Comment by rigelk** [comment]
Per #257, Pale Moon up to version 27 doesn't work with PeerTube because of its broken Javascript parser. Version 28 is reported to work though.
