### ISSUE TITLE
Installation Problem: [title]

### ISSUE THREAD

**Issue by ycharbi** [Chocobozzz/PeerTube#1402]
Hello,

**Which operating system are you using:**
Debian Stretch

**Which version of the package are you using:**
That of the deposit of the page https://docs.joinpeertube.org/lang/en/docs/install.html#debian-stable to 14/11/2018 (1.0.0~beta13-0).

**Please describe the steps you took when trying to install PeerTube and what went wrong:**
I do all the root commands:
```
curl -sS https://pkg.rigelk.eu/pubkey.gpg | apt-key add -
echo "deb https://pkg.rigelk.eu/debian/ stable main" > /etc/apt/sources.list.d/peertube.list
apt update
apt install peertube
```
**What is the problem:**
The service does not start.

After installation, the service is not started automatically:
`service peertube status`                                                                                                                                                                         
```
● peertube.service - PeerTube daemon                                                                                                                                                                                 
   Loaded: loaded (/usr/lib/systemd/system/peertube.service; disabled; vendor preset: enabled)                                                                                                                       
   Active: inactive (dead) 
```
A `service peertube start` gives a failure:
```
● peertube.service - PeerTube daemon
   Loaded: loaded (/usr/lib/systemd/system/peertube.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-11-14 22:22:28 CET; 13s ago
  Process: 11246 ExecStart=/usr/bin/npm start (code=exited, status=255)
 Main PID: 11246 (code=exited, status=255)

nov. 14 22:22:28 Stretch-pxe systemd[1]: peertube.service: Failed with result 'exit-code'.
nov. 14 22:22:28 Stretch-pxe systemd[1]: peertube.service: Service hold-off time over, scheduling restart.
nov. 14 22:22:28 Stretch-pxe systemd[1]: Stopped PeerTube daemon.
nov. 14 22:22:28 Stretch-pxe systemd[1]: peertube.service: Start request repeated too quickly.
nov. 14 22:22:28 Stretch-pxe systemd[1]: Failed to start PeerTube daemon.
nov. 14 22:22:28 Stretch-pxe systemd[1]: peertube.service: Unit entered failed state.
nov. 14 22:22:28 Stretch-pxe systemd[1]: peertube.service: Failed with result 'exit-code'.
```
Relaunching the same command gives a success...
```
● peertube.service - PeerTube daemon
   Loaded: loaded (/usr/lib/systemd/system/peertube.service; disabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-11-14 22:25:36 CET; 1s ago
 Main PID: 11316 (npm)
    Tasks: 21 (limit: 4915)
   CGroup: /system.slice/peertube.service
           ├─11316 npm
           ├─11326 sh -c node dist/server
           └─11327 node dist/server

nov. 14 22:25:36 Stretch-pxe systemd[1]: Started PeerTube daemon.
nov. 14 22:25:37 Stretch-pxe peertube[11316]: > peertube@1.0.0-beta.13 start /var/www/peertube
nov. 14 22:25:37 Stretch-pxe peertube[11316]: > node dist/server
nov. 14 22:25:37 Stretch-pxe peertube[11316]: WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
nov. 14 22:25:37 Stretch-pxe peertube[11316]: WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
```
A `ss -ltnp` shows that the service does not listen on any port:
```
State       Recv-Q Send-Q                                                             Local Address:Port                                                                            Peer Address:Port
LISTEN      0      128                                                                    127.0.0.1:6379                                                                                       *:*
users:(("redis-server",pid=10568,fd=4))
LISTEN      0      128                                                                            *:22                                                                                         *:*
users:(("sshd",pid=546,fd=3))
LISTEN      0      128                                                                    127.0.0.1:5432                                                                                       *:*
users:(("postgres",pid=10459,fd=6))
LISTEN      0      128                                                                           :::22                                                                                        :::*
users:(("sshd",pid=546,fd=4))
LISTEN      0      128                                                                          ::1:5432                                                                                      :::*
users:(("postgres",pid=10459,fd=3))
```
This shows that it is useless to continue on the reverse proxy until this step does not work.

So what does it take to fully install Peertube? The documentation is very sweet and we are released to ourselves.
Did I miss a documenting page? Usually to configure this kind of service, just install the package, type the IP server and go through a WEB configuration step (sometimes touch a few PHP files but no more) but here I have feel that it is much more complicated than that.

Can you redirect me to a complete procedure using the deposits please?

If you want, I can help make a more complete documentation when it will work with this method.

I am available if you need clarification (i am French).
Thank you.

**Comment by rigelk** [comment]
Hi - you are using a community-made packaging of PeerTube. In case it doesn't work, you can always fall back to the production guide install which is the only one we can fully support here.

In the specific case of the debian package, I'm the one at fault for not releasing a more recent package. See https://github.com/Chocobozzz/PeerTube/issues/1314#issuecomment-431572868 | note that there is a warning about it in the documentation…

As for your issue, it's related to your lack of a `production.yaml` as the error log says. You can refer to https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#peertube-configuration but indeed, a proper page in the documentation explaining how to configure the file and read its comments would help.

**Comment by ycharbi** [comment]
Thank you for your reply. I tried with the link you provided me and it still does not work. The problem seems to come from npm. Here are are log.
[2018-11-15T15_37_29_892Z-debug.log](https://github.com/Chocobozzz/PeerTube/files/2586004/2018-11-15T15_37_29_892Z-debug.log)
I systematically test on Debian installations virgins to limit the problems.
Do you have an idea ?

**Comment by EricThi** [comment]
Hello,

I have the same case on my fresh install on ArchLinux. I follow this official guide :
https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md

I only change ndd to my ndd and adapt log nginx on other folder.

On launch :

> 

systemctl restart peertube && journalctl -fu peertube
-- Logs begin at Tue 2016-02-23 10:20:10 CET. --
Mar 29 13:28:46 peertube peertube[2994]: npm ERR!     /var/www/peertube/.npm/_logs/2019-03-29T12_28_46_785Z-debug.log
Mar 29 13:28:46 peertube systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
Mar 29 13:28:46 peertube systemd[1]: peertube.service: Failed with result 'exit-code'.
Mar 29 13:28:46 peertube systemd[1]: peertube.service: Service RestartSec=100ms expired, scheduling restart.
Mar 29 13:28:46 peertube systemd[1]: peertube.service: Scheduled restart job, restart counter is at 5.
Mar 29 13:28:46 peertube systemd[1]: Stopped PeerTube daemon.
Mar 29 13:28:46 peertube systemd[1]: peertube.service: Start request repeated too quickly.
Mar 29 13:28:46 peertube systemd[1]: peertube.service: Failed with result 'exit-code'.
Mar 29 13:28:46 peertube systemd[1]: Failed to start PeerTube daemon.
Mar 29 13:29:24 peertube systemd[1]: Started PeerTube daemon.
Mar 29 13:29:24 peertube peertube[3023]: > peertube@1.2.1 start /var/www/peertube/versions/peertube-v1.2.1
Mar 29 13:29:24 peertube peertube[3023]: > node dist/server
Mar 29 13:29:25 peertube peertube[3023]: /var/www/peertube/versions/peertube-v1.2.1/dist/server/initializers/constants.js:705
**Mar 29 13:29:25 peertube peertube[3023]:     return objs.map(obj => {**
Mar 29 13:29:25 peertube peertube[3023]:                 ^
Mar 29 13:29:25 peertube peertube[3023]: TypeError: objs.map is not a function
Mar 29 13:29:25 peertube peertube[3023]:     at buildVideosRedundancy (/var/www/peertube/versions/peertube-v1.2.1/dist/server/initializers/constants.js:705:17)
Mar 29 13:29:25 peertube peertube[3023]:     at Object.<anonymous> (/var/www/peertube/versions/peertube-v1.2.1/dist/server/initializers/constants.js:212:25)
Mar 29 13:29:25 peertube peertube[3023]:     at Module._compile (internal/modules/cjs/loader.js:805:30)
Mar 29 13:29:25 peertube peertube[3023]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
Mar 29 13:29:25 peertube peertube[3023]:     at Module.load (internal/modules/cjs/loader.js:672:32)
Mar 29 13:29:25 peertube peertube[3023]:     at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
Mar 29 13:29:25 peertube peertube[3023]:     at Function.Module._load (internal/modules/cjs/loader.js:604:3)
Mar 29 13:29:25 peertube peertube[3023]:     at Module.require (internal/modules/cjs/loader.js:711:19)
Mar 29 13:29:25 peertube peertube[3023]:     at require (internal/modules/cjs/helpers.js:14:16)
Mar 29 13:29:25 peertube peertube[3023]:     at Object.<anonymous> (/var/www/peertube/versions/peertube-v1.2.1/dist/server/initializers/index.js:6:10)
Mar 29 13:29:25 peertube peertube[3023]: npm ERR! code ELIFECYCLE
Mar 29 13:29:25 peertube peertube[3023]: npm ERR! errno 1
Mar 29 13:29:25 peertube peertube[3023]: npm ERR! peertube@1.2.1 start: `node dist/server`
Mar 29 13:29:25 peertube peertube[3023]: npm ERR! Exit status 1
Mar 29 13:29:25 peertube peertube[3023]: npm ERR!
Mar 29 13:29:25 peertube peertube[3023]: npm ERR! Failed at the peertube@1.2.1 start script.
Mar 29 13:29:25 peertube peertube[3023]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Mar 29 13:29:25 peertube peertube[3023]: npm ERR! A complete log of this run can be found in:
Mar 29 13:29:25 peertube peertube[3023]: npm ERR!     /var/www/peertube/.npm/_logs/2019-03-29T12_29_25_120Z-debug.log
Mar 29 13:29:25 peertube systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
Mar 29 13:29:25 peertube systemd[1]: peertube.service: Failed with result 'exit-code'.

> 

cat /var/www/peertube/.npm/_logs/2019-03-29T12_29_25_120Z-debug.log

> 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.9.0
3 info using node@v11.13.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle peertube@1.2.1~prestart: peertube@1.2.1
6 info lifecycle peertube@1.2.1~start: peertube@1.2.1
7 verbose lifecycle peertube@1.2.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle peertube@1.2.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/peertube/versions/peertube-v1.2.1/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin
9 verbose lifecycle peertube@1.2.1~start: CWD: /var/www/peertube/versions/peertube-v1.2.1
10 silly lifecycle peertube@1.2.1~start: Args: [ '-c', 'node dist/server' ]
11 silly lifecycle peertube@1.2.1~start: Returned: code: 1  signal: null
12 info lifecycle peertube@1.2.1~start: Failed to exec start script
13 verbose stack Error: peertube@1.2.1 start: `node dist/server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:193:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:193:13)
13 verbose stack     at maybeClose (internal/child_process.js:1001:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
14 verbose pkgid peertube@1.2.1
15 verbose cwd /var/www/peertube/versions/peertube-v1.2.1
16 verbose Linux 5.0.4-arch1-1-ARCH
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v11.13.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error peertube@1.2.1 start: `node dist/server`
22 error Exit status 1
23 error Failed at the peertube@1.2.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

> 

Eric

**Comment by Chocobozzz** [comment]
@EricThi See https://github.com/Chocobozzz/PeerTube/issues/1709#issuecomment-470849734

**Comment by EricThi** [comment]
Thank you, and don't see this comment.
