### ISSUE TITLE
How URL scheme work on PeerTube?

### ISSUE THREAD

**Issue by Medow** [Chocobozzz/PeerTube#1404]
Hello:
I am going to upload some video using CLI using some bash script i wrote.
After uploading the video i should extract the video URL link to submit it on other platform for other use.
How can I grab the video URL link after upload?
Thanks.

**Comment by rigelk** [comment]
Hi @Medow - you can see the [documentation of the upload](https://docs.joinpeertube.org/api.html#tag/Video/paths/~1videos~1upload/post) endpoint. It returns a `VideoUploadResponse` object:

```json
{
  "video": {
    "id": 0,
    "uuid": "string"
  }
}
```

It holds the video UUID, which you can append to the `https://<DOMAIN>/videos/watch/` scheme (`https://<DOMAIN>/videos/watch/<UUID`).

**Comment by Medow** [comment]
@rigelk 

> Hi @Medow - you can see the [documentation of the upload](https://docs.joinpeertube.org/api.html#tag/Video/paths/~1videos~1upload/post) endpoint. It returns a `VideoUploadResponse` object:
> 
> ```json
> {
>   "video": {
>     "id": 0,
>     "uuid": "string"
>   }
> }
> ```
> 
> It holds the video UUID, which you can append to the `https://<DOMAIN>/videos/watch/` scheme (`https://<DOMAIN>/videos/watch/<UUID`).

@rigelk , Thanks for help.
this is clear.
