### ISSUE TITLE
Add ability to add link relations in descriptions

### ISSUE THREAD

**Issue by Booteille** [Chocobozzz/PeerTube#1407]
I was trying to add a link with a relation ([rel="me"](url)) to my account description but I was not able to do it because of actual Markdown configuration.

Would it be possible to add something like [markdown-it Attrs](https://www.npmjs.com/package/markdown-it-attrs) or [markdown-it Link Attributes](https://www.npmjs.com/package/markdown-it-link-attributes) to dependencies so we could use this attribute?

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/891bc2ffadd5dedae316fcc80856ff859e6f8336
