### ISSUE TITLE
Hide videos from the homepage that are not in the same language as the language set for my browser

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#1408]
English is my browser's default language, yet when I visit a peertube instance (without logging into an account) I see videos which are not in English. This is a bad user experience.

Solution: To show only language-relevant videos **on the homepage** and show **all videos when using the search feature**.

When I say homepage I mean "trending", "local" etc... 

**edit:** we shouldn't forget about the "Other Videos" section, which also doesn't have to show us videos in a language we don't understand.

**Comment by pqhf5kd** [comment]
Great idea, although are many videos tagged with the correct language?

**Comment by Zig-03** [comment]
> Great idea, although are many videos tagged with the correct language?

people should be able to flag videos that aren't as described and then the Host should "take care" of them. I don't think we should worry too much about this.

**Comment by unmellow** [comment]
this should also be optional but set to on by default

**Comment by Quix0r** [comment]
Also an option in profile: "Preferred language 1" and "Preferred language 2" should be included, so you can find videos everywhere quickly. I found it hard to dig through tons of videos not matching my languages I understand (German and English). And making it fully browser-dependent is maybe not what you want. It should be the first "filter" being applied (and described to the user like "Your browser has indicated that you prefer videos in language X." If this is not want you want, you can change it here:" and provide a language selection box that's value will be stored in local storage or session cookie.

Registering an account will make it being "permanent" and when login, it will be restored.

**Comment by robinkooli** [comment]
Remember to account for subtitles too, so if video has a English subtitles it isn't being hid from home for English speaking people.

**Comment by Zig-03** [comment]
I guess there could be concerns about the limited number of videos available in one language or another. For such situation we can show them videos in English **after** all the other videos in their native language have ended. For example, a user with its browser language set to Italian, after landing on a peertube instance will first see ~40 videos in Italian, and after further scrolling, he'll see videos in English.

What kind of workaround do you see here?

**Comment by DontUseGithub** [comment]
We now have [160k+](https://instances.joinpeertube.org/instances/stats) videos on the fediverse, perhaps that's plenty for this feature to be implemented? The lack of this feature drastically worsens the user experience, especially for new users.

**Comment by Chocobozzz** [comment]
Users have a setting to display videos of specific languages.

**Comment by DontUseGithub** [comment]
What about unregistered users? Which also represent all the new users who are having their first ever interaction with peertube. And the first impression is always very important.
When such a new user visits this [instance](https://vloggers.social), for example, on his screen he will see 24 videos, out of which only 1 will be in English.

**Comment by Quix0r** [comment]
> Great idea, although are many videos tagged with the correct language?

Then maybe also include un-tagged (no language tag included) videos in any language because it is not determinable. Maybe people then can report the actual (spoken) language so it can be manually fixed.

**Comment by Chocobozzz** [comment]
Anonymous users can now have access to a quick settings modal, to set video languages settings (thanks @rigelk)

![screen_2020-04-15-15:14:42](https://user-images.githubusercontent.com/5180488/79341294-d9a4d100-7f2b-11ea-98b2-aa77b4b1516e.png)

**Comment by DontUseGithub** [comment]
This is great but IMO it doesn't address the main point of this issue which is: improve the default user experience by showing the first videos in a language that the user understands.

**Comment by rigelk** [comment]
@DontUseGithub it's true, but detecting the language of a user is unreliable (i.e. Tor Browser users). Maybe I have wrong assumptions, but a wrong language detected will have a greater negative impact on the UX.

Maybe we could suggest such a filter on the first visit in a top message, but I don't think we should impose that on the user (?).

**Comment by DontUseGithub** [comment]
> but detecting the language of a user is unreliable (i.e. Tor Browser users). 

Tor uses English as the default one, which is understood by many, and whoever knows about Tor, probably knows some English too. Can you think of any other situations where this feature could do more harm than good? I personally don't see any problems in adopting it, because **we're not** using the IP to determine the language (which would be very wrong, especially for those who use VPNs, TOR, etc.) but we're using the browser's language. Why would anyone set the browser language to a language they don't understand? In a browser you "Open a new Tab", "Save Image As", "Bookmark", etc so you need to understand all these words in order to use a browser.

**Comment by Chocobozzz** [comment]
I created a dedicated issue: https://github.com/Chocobozzz/PeerTube/issues/2642
