### ISSUE TITLE
The "Trending" page needs a visible filter saying "For the past 7 days" and give a few more options

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#1409]
When opening the trending page we can see in the top left corner an icon with the class `class="icon icon-syndication"` so somewhere there can be a text that would say "For the past 7 days" and then an arrow which once clicked will give you some more options like:

- "For the past 24 hours"
- "For the past 3 days"
- "For the past 14 days"
- "For the past month"
- "custom"

note: all these dates serve as an example, feel free to change them to whatever you feel like

**Comment by Zig-03** [comment]
Checking https://peertube.social/ it seems that the feature isn't working. It says "Trending for the last 7 days" but lists videos that are a few months old. 

There also isn't a button that will allow the user to change a different date range like 

>     "For the past 24 hours"
>     "For the past 3 days"
>     "For the past 14 days"
>     "For the past month"
>     "custom"

**Comment by Nutomic** [comment]
You seem to misunderstand how trending works (but it should probably be explained better). Trending shows the videos that have the most views in the last 7 days (or any different interval). It doesnt matter when the video was uploaded. So if a video was uploaded 1 month ago, but suddenly got 1000 views yesterday, it would be included in trending. Views more than 7 days ago (in this example) are not counted towards the trending calculation.

**Comment by Zig-03** [comment]
@Nutomic I see. But this is making it harder for new & interesting content to potentially show up on the Trending page. This also may cause the same content to stay in Trending _for months_ and at some point people will just not visit the Trending page since it will not provide any **new** value to them. 

I'd suggest opting in for a regular trending system i.e. videos with most views for the past 7 days.

**Comment by Chocobozzz** [comment]
Closing now we have other trending algorithms (hot, best...)
