### ISSUE TITLE
[graphical bug] pixel perfect on name

### ISSUE THREAD

**Issue by Dryusdan** [Chocobozzz/PeerTube#141]
Hey (i'm a borring man, I know ^^ )
It's a very little bug (graphical bug them) so...
When I hide left menu, the logo "peertube" shrink... A little (1 or two pixel).

I have a screen, resolution 1920x1080, on 17,4" 

:)

**Comment by Chocobozzz** [comment]
Will be fixed by https://github.com/Chocobozzz/PeerTube/issues/134

**Comment by Dryusdan** [comment]
Okay, right ^^
