### ISSUE TITLE
Create user API expects role as string but requires integer

### ISSUE THREAD

**Issue by c-prompt** [Chocobozzz/PeerTube#1411]
**What happened?**
Created a CURL to create a new user via the [Creates User API](https://docs.joinpeertube.org/api.html#tag/User/paths/~1users/post). Spec indicates "role": "string." However, if you use `&role=User`, you receive the response error:

`string(102) "{"errors":{"role":{"location":"body","param":"role","value":"User","msg":"Should have a valid role"}}}" `

Instead, if you use `&role=2` (for user), the user is properly created. This might be working as intended; if so, the documentation should be updated (as it took some time to track down the issue).

* PeerTube version: v1.0.1
* NodeJS version: v10.13.0

**Comment by rigelk** [comment]
Hi @c-prompt - you're perfectly right, the value should be one of [0, 1, 2](https://github.com/Chocobozzz/PeerTube/blob/develop/shared/models/users/user-role.ts#L4-L8) (int). I'll modify the spec accordingly.
