### ISSUE TITLE
Video does not play, but is loading

### ISSUE THREAD

**Issue by dlang9159** [Chocobozzz/PeerTube#1413]
**What happened?**
I uploaded a video to my instance, but the video does not play, but loads in the background.
Transcoding is enabled. 
**What do you expect to happen instead?**

**Steps to reproduce:**

1. Upload this video: https://nc.kircheneuenburg.de/index.php/s/midTeGTqcZe6ZGn to Peetube with transcoding enabled.

2. Open video after transcoding: https://pt.kircheneuenburg.de/videos/watch/e33ad15d-40be-4815-9dac-212efa8cd54f

3. Video does not play.

Video does play, when embedding in a plain <video> tag in a simple html page.

**Additional information**
* PeerTube version or URL: 1.0.1 / pt.kircheneuenburg.de
* Browser name/version: Firefox
* FFMPEG version: 3.4.4-1~16.04.york0
* NodeJS version: 8.12.0

**Comment by Chocobozzz** [comment]
It seems the file misses `decSpecificInfo` in mp4 headers, resulting in an invalid mime type. 

Should be fixed with https://github.com/Chocobozzz/PeerTube/commit/64e3e27053a5881fa9efca32f5a0debace617ced

Ping @rigelk

**Comment by dlang9159** [comment]
@Chocobozzz What tools do you use to debug such problems? Reason for asking: I still got some unplayable videos even with this patch and I'd like to research for myself, so you don't have to do all the work

**Comment by Chocobozzz** [comment]
@dlang9159 I mainly use these tools: https://www.bento4.com/
