### ISSUE TITLE
Sensitive Media Changes

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#1416]
Tangentially related to #1158 but mostly asking for improvements to the existing marking of media as sensitive.

First, when you choose to show sensitive videos with blurred thumbnails on the timelines, the video titles themselves are also blurred, meaning you have no clue what the contents of the video will be. This could be a bug, but it's not clear if it is. Example screenshotted below.
![screenshot_20181120-154448](https://user-images.githubusercontent.com/15249812/48801918-9b29c900-ecdb-11e8-9fb3-d2b039de462b.png)

Secondly, when you open a sensitive video, the description does not load, only the title, with a popup overtop of it. It may make more sense to replace the video player with a message indicating continuing will reveal sensitive content, and obscure mainly comments as well as the video until you choose to go through (That way, the description can be used to outline why the video is sensitive.)
 
**Additional information**
* PeerTube version or URL: dialup.express
* Browser name/version: Firefox 63 for Ubuntu
* NodeJS version: ??

**Comment by Chocobozzz** [comment]
I think we should implement the confirmation buttons directly in the player, like Facebook does for example.

**Comment by Chocobozzz** [comment]
Closing this issue in favour of https://github.com/Chocobozzz/PeerTube/issues/6144
