### ISSUE TITLE
VideoResolution doesn't know about resolutions higher than 1080p

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#1419]
4K videos get the same maximum bitrate as 1080p videos, which likely isn't what we want. (The current scheme is flawed, but devices with 4K displays are also going to be capable of decoding h264 faster and the user will expect higher network requirements)

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/ad3405d087b306efa5eb62a69c9b797b04eab4ce
