### ISSUE TITLE
Youtube import : "stdout maxBuffer exceeded" error, but weird json output by youtube-dl

### ISSUE THREAD

**Issue by MoffTigriss** [Chocobozzz/PeerTube#1421]
I have an issue with a "stdout maxBuffer exceeded" error, when importing a youtube video.
Seems totally similar to https://github.com/Chocobozzz/PeerTube/issues/1114 and https://github.com/Chocobozzz/PeerTube/issues/295, but there is something weird with the json output.

Working video, success import, json size 40 416KB : https://www.youtube.com/watch?v=tRbFbGRQr6E
Video generating an error, json size 348 168KB : https://www.youtube.com/watch?v=3u7zcOLM9sI

The json is full of weird data, like 
` {"duration": 5.12, "path": "sq/114/dur/5.120"}, {"duration": 5.12, "path": "sq/115/dur/5.120"}, {"duration": 5.12, "path": "sq/116/dur/5.120"}, {"duration": 5.12, "path": "sq/117/dur/5.120"}, {"duration": 5.12, "path": "sq/118/dur/5.120"}, {"duration": 5.12, "path": "sq/119/dur/5.120"}, {"duration": 5.12, "path": "sq/120/dur/5.120"}, {"duration": 5.12, "path": "sq/121/dur/5.120"}`

The buffer size seems to be 10MB, if i read the patches correctly, so even if weird, a 350KB json shouldn't be a problem.

I'm looking in the Youtube-dl repo, but nothing interesting so far.

Debian Stretch
Peertube 1.0.1
Node 8.12
youtbe-dl 2018-11-18

Here is the line in the log :

`moff@debian-peertube:/tmp$ cat /var/www/peertube/storage/logs/peertube1.log | grep 3u7zcOLM9sI
{"level":"info","message":"Cannot fetch information from import for URL https://www.youtube.com/watch?v=3u7zcOLM9sI.","label":"peertube.mindpalace.io:443","meta":{"err":{"stack":"Error: stdout maxBuffer exceeded\n    at Socket.onChildStdout (child_process.js:329:14)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:246:13)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at Pipe.onread (net.js:601:20)","message":"stdout maxBuffer exceeded","cmd":"/var/www/peertube/versions/peertube-v1.0.1/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -j --flat-playlist http://www.youtube.com/watch?v=3u7zcOLM9sI"}},"timestamp":"2018-11-21T13:56:53.725Z"}
`

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed in https://github.com/Chocobozzz/PeerTube/commit/9fa0ea41aaa511bed3aa179dacc312fad6170c21
