### ISSUE TITLE
Changing Nginx temporary buffer default location

### ISSUE THREAD

**Issue by MoffTigriss** [Chocobozzz/PeerTube#1423]
On my first installation, I used a iSCSI mount for /var/www/peertube/storage. My objective was to use a Freenas installation, sharing a large volume via iSCSI, for easy backups, future moving, and playing with decentralized redundancy.

The partitioning for the Debian host was small. And sometimes, videos stopped during upload, at different progression time. No sign of anything on the system, and the filesystem indicated free space.

Nginx use a temporary file in **/var/lib/nginx/body/** to store the upload buffer. The file is not visible, because listed as "deleted" in file descriptors. You can view the current file, when uploading, with `sudo lsof -p NGINXPID`, and the size increasing. When finished, the file is moved to the upload location. If nginx stop the upload process or crash, the file is immediately lost, so there is no remains, whatever happen.

Having a, potentially, <= 8GB file not documented somewhere on the filesystem can be a problem with small installs. And even more if you/guest upload multiple videos at the same time.

**Proposition:**

Nginx allow the relocation of that temporary folder, in a `location` context with the directive `client_body_temp_path`, so it can be configured specifically for `location /` :
http://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_temp_path

Moving the cache folder somewhere in **/var/www/peertube/.cache/** or **/var/www/peertube/storage/cache/** will allow to keep big files in the same place, and not having problem with a small install/partitioning.

Current installs works fine, but changing the default configuration and update the documentation to reflect where Nginx create his buffer could be nice for future users.

**Comment by Nutomic** [comment]
Great find! You should make a PR to set this path in the [sample Nginx config](https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube). 

It might also be a good idea to put this in `/var/www/peertube/storage/videos/uploads` or so, for people like me who only mount the video folder with a large partition.

**Comment by JohnXLivingston** [comment]
Have you any idea about this issue ? https://github.com/Chocobozzz/PeerTube/issues/1359
I think it can be related to this kind of nginx configuration. (it is on a slow VM... only one CPU)

**Comment by Nutomic** [comment]
@JohnXLivingston Sorry no idea, I didn't hear about any problems with uploading on my instance (it's on a fast SSD).

**Comment by iwascraig** [comment]
I have this problem also .. not related to CPU size.. the problem is related to upload file size...
my /var/lib/nginx/body folder is on a system volume that is only 10GB in size... when I try to upload a 15GB file (research data, often this large or larger) I run out of space and client gets error.

**Comment by rdp** [comment]
@iwascraig did the nginx error log show a 499?  Just curious...

**Comment by Chocobozzz** [comment]
I added a comment in our nginx template: https://github.com/Chocobozzz/PeerTube/commit/7b7d4e2a6adde8a8aa0b4c0048bddd448a6a0093
