### ISSUE TITLE
Document PeerTube's ActivityPub vocabulary

### ISSUE THREAD

**Issue by tcitworld** [Chocobozzz/PeerTube#1424]
It's always nice when namespaces return documentation.
[`https://joinpeertube.org/ns`](https://joinpeertube.org/ns) should link a page where `CacheFile` and eventual future properties are documented

**Comment by rigelk** [comment]
It's a work in progress, but I've documented them at https://docs.joinpeertube.org/lang/en/devdocs/federation.html

**Comment by tcitworld** [comment]
Added the redirection, thanks!
