### ISSUE TITLE
Can we increase the simultaneous webseed size ? 

### ISSUE THREAD

**Issue by uschana123** [Chocobozzz/PeerTube#1428]
# Bypass PeerTube webseed route for better performances
  location /static/webseed {
    # Clients usually have 4 simultaneous webseed connections, so the real limit is 3MB/s per client
     limit_rate 800k;

    if ($request_method = 'OPTIONS') {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
      add_header 'Access-Control-Max-Age' 1728000;
      add_header 'Content-Type' 'text/plain charset=UTF-8';
      add_header 'Content-Length' 0;
      return 204;
    }

    if ($request_method = 'GET') {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

      # Don't spam access log file with byte range requests
      access_log off;
    }

    alias /media/sf_Drive/videos;
  }

Can we increase the simultaneous webseed size ? 
 4 simultaneous  to 8 simultaneous

**Comment by Nutomic** [comment]
For what reason specifically? Are videos downloading too slowly for you?

**Comment by uschana123** [comment]
> @uschana123 do you have an example video that loads too slowly for you?
all video on server
http://cloud.allplayer.tk

**Comment by uschana123** [comment]
> @uschana123 do you have an example video that loads too slowly for you?
@rigelk 
https://cloud.allplayer.tk/videos/watch/6d4a3381-e48c-410c-b00a-0074518e9a54

**Comment by ldidry** [comment]
Directly downloading a video says the same thing: not enough bandwidth.
Tested with
```
wget https://cloud.allplayer.tk/download/videos/6d4a3381-e48c-410c-b00a-0074518e9a54-1080.mp4 -O /dev/null
```
I couldn't reach more than ±450KB/s, and it was mostly around 250KB/s.

Even the connection to the server is slow: doing a simple HEAD request (that asks for the headers returned if the request was a GET, without the body (here, without the video)) is slow:
```
time curl -I https://cloud.allplayer.tk/download/videos/6d4a3381-e48c-410c-b00a-0074518e9a54-1080.mp4
=> curl -I   0,01s user 0,00s system 0% cpu 7,878 total
```
Almost 8 seconds
You can try with Framatube to see the difference:
```
time curl -I https://framatube.org/download/videos/fff79bf3-99c8-4601-9a05-f64561d97d09-720.mp4
=> curl -I   0,02s user 0,00s system 6% cpu 0,352 total
```
Almost a third of a second.

I think this is not only the bandwidth that is low, I think the hardware is culprit too. A RaspberryPi maybe?

**Comment by uschana123** [comment]
My server keeps all videos on google drive file stream access to the first video may be a little slow.
The server may be far from where I live, so it's slow to load because I rent another server to test it.

**Comment by Nutomic** [comment]
If you are using Nginx, you can configure it to cache videos locally. I'm also using this for my instance (though with a much faster storage backend).

https://docs.joinpeertube.org/lang/en/docs/cache.html
