### ISSUE TITLE
Add a category

### ISSUE THREAD

**Issue by webafrancois** [Chocobozzz/PeerTube#1429]
**What happened?** We just want to ad a new category, that does'nt exist.

**What do you expect to happen instead?** : impossible to create anyone

**Additional information**
* PeerTube version or URL:1.0.1 / https://videos.cemea.org

**Comment by BO41** [comment]
I think categorys need to be added to the code. #1261 
So either open a PR to this project, or make the change on your fork

**Comment by rigelk** [comment]
Categories can be understood as fixed tags. Adding new ones is a heavy operation since it is part of the federated metadata about the video. In the meantime I suggest you use a specific tag.

Otherwise, as said @BO41, please open a PR with your suggestion of category :)

**Comment by Chocobozzz** [comment]
A plugin system could extend categories I guess

**Comment by EBendinelli** [comment]
This is not an answer at all but if you want to replace an existing category by one of your own I wrote a [quick and dirty way to do this](https://gist.github.com/EBendinelli/c3c77b97dcd84d0c6e7a98f243a5ff5a).

Will only work for your own instance but it did the trick for my organisation.

**Comment by Chocobozzz** [comment]
You can now create a plugin to add or delete categories: https://github.com/Chocobozzz/PeerTube/commit/ee286591a5b740702bad66c55cc900740f749e9a

**Comment by dausruddin** [comment]
I am wondering if anyone made a plugin yet. Last time I checked weeks ago there is none.

**Comment by jb-alvarado** [comment]
Manipulation (create/update/delete) the categories over the API would be nice to.

**Comment by Chocobozzz** [comment]
> Manipulation (create/update/delete) the categories over the API would be nice to.

You can develop a plugin that registers a route to create/update/delete categories :)

**Comment by jb-alvarado** [comment]
You know any plugin which are already do API stuff, so I have a reference?

**Comment by Chocobozzz** [comment]
You could check the documentation: https://docs.joinpeertube.org/contribute-plugins?id=add-custom-routes

And an example: https://framagit.org/framasoft/peertube/official-plugins/-/blob/master/peertube-plugin-hello-world/main.js#L148
