### ISSUE TITLE
Configure the overview page by the administrator

### ISSUE THREAD

**Issue by webafrancois** [Chocobozzz/PeerTube#1430]
**What happened?**
When we are looking to the overview page, we see 2 categories, 2 tags and 2 channels

**What do you expect to happen instead?** We can't choose our favorite categories or favorite channels.
It would be nice to choose some channels to push on the top of the overview. Thanks.

**Comment by realityfabric** [comment]
A whitelist of tags that can be promoted would also be nice. Making it so that the algorithm can still choose tags to feature, but only if they've been approved by the moderators/admins first, similar to how Trending Tags on Mastodon works.

**Comment by pprw** [comment]
Also why 2 categories, 2 tags and 2 channels?

Instance administrator would perhaps have 6 channels and nothing else, or only tags, etc.

I think current overwiew page could be ok for generalist instances which don't really care about which contents will be prioritized.

But for specialized instances, administrators should be able to decide exactly which tags/channels/categories should be put in the front.

For example, if an instance is dedicated to teaching mathematics. The overview page could/should be configured with (I guess) Algebra, Geometry, ... categories and displays maybe the main channel which hosts the teaching videos.

I think PeerTube should add overview page management tools and it deserves perhaps a higher priority than low :-).

**Comment by Chocobozzz** [comment]
Hello,

I'm closing this issue now admins can design their own homepage, selecting videos they want based on many criteria (category, language etc)
