### ISSUE TITLE
close Download Video popup after validation

### ISSUE THREAD

**Issue by roipoussiere** [Chocobozzz/PeerTube#1436]
When we click on *Download Video*, a popup appears with several options. After clicking *Download*, the download starts but the popup remains here. This is a little bit disturbing because we may think that the action failed. Maybe this button should close this popup.

**Comment by juliencrepin62** [comment]
I will edit the file to close the pop-up when the the user clicks on the download button.

**Comment by buoyantair** [comment]
@juliencrepin62 Hey, just wanted to checkup on this issue

**Comment by rokamoto30** [comment]
Is this issue still active? I'm a new programmer looking into open source projects and I was wondering how I could start contributing to this project.

**Comment by Chocobozzz** [comment]
@rokamoto30 Yes you can take it. Or any "good first issue": https://github.com/Chocobozzz/PeerTube/labels/good%20first%20issue%20%3Abeginner%3A

**Comment by Chocobozzz** [comment]
Implemented by @LeoMouyna in https://github.com/Chocobozzz/PeerTube/commit/11b3f14c758e57f9cb5f32d8140fa043094bb3d7
