### ISSUE TITLE
Overall PeerTube's UI Design

### ISSUE THREAD

**Issue by Zig-03** [Chocobozzz/PeerTube#1441]
Is there a full UI redesign planned? Perhaps the guys from libreart.info can help? ~AFAIK they are the ones who did the design for purism and mastodon and I love their work!~ [I got it wrong](https://forums.puri.sm/t/new-website-launched-in-2018), apparently Eugen Rochko (from Mastodon) did the design for both Purism and Mastodon _(obviously)_.

I could make some suggestions myself, but in my opinion this is the kind of work that has to be done by an experienced professional which knows everything about UI, UX etc. Opinions?

**Comment by Booteille** [comment]
I think this could be a good idea to find someone to start to work on this soon. With a bit of luck we could have a redesign in some months.

**Comment by Chocobozzz** [comment]
A peertube redesign is not planned.

Closing this issue in favour of https://github.com/Chocobozzz/PeerTube/issues/484
