### ISSUE TITLE
flatmap-stream-0.1.1 404 Not Found while upgrading from v1.0 to  v1.1.0-rc.1

### ISSUE THREAD

**Issue by vincib** [Chocobozzz/PeerTube#1444]
**What happened?**

I had the following error message when I upgraded from 1.0 to 1.1.0~rc1 : 

```
yarn install v1.5.1
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "@types/bluebird@3.5.21" is incompatible with requested version "@types/bluebird@3.5.18"
[3/5] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/flatmap-stream/-/flatmap-stream-0.1.1.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/var/www/peertube/versions/peertube-v1.1.0-rc.1/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**What do you expect to happen instead?**

I expected yarn to be able to download the requested package

**Additional information**
* PeerTube version or URL: video.lqdn.fr
* NodeJS version: v8.10

**Comment by vincib** [comment]
I just tested it after upgrading yarn to 1.12.3 
the flat-stream part seemed to work, but I had another issue later on : 

```
yarn install v1.12.3
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "@types/bluebird@3.5.21" is incompatible with requested version "@types/bluebird@3.5.18"
[3/5] Fetching packages...
error https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by rigelk** [comment]
This is normal since the package has been nuked on npm. You can do a `yarn remove nodemon && yarn add nodemon` to bypass the problem until the next release properly addresses the problem next week.

**Comment by vincib** [comment]
worked like a charm, thanks ! 
note: if you use the upgrade.sh script it won't work since it's re-downloading the package.
just launch upgrade.sh, wait until it fails, and launch the commands from rigelk in the peertube-latest folder.
