### ISSUE TITLE
Comment posted negative seconds ago

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#1445]
I assume there may be a small time desynchronization between server and client, but in any case i don't think this is what we want to be displaying:

![screen shot 2018-12-02 at 11 11 24 am](https://user-images.githubusercontent.com/923812/49343693-351a3b80-f623-11e8-8867-4ad3af43f76c.png)

I'd expect we could solve this by rounding any times more recent than a couple seconds to "just now" or something, ignoring negative values effectively.

**Comment by Poslovitch** [comment]
I may work on this one this weekend

**Comment by Poslovitch** [comment]
It seems it happens when publishing videos as well...
![image](https://user-images.githubusercontent.com/20014332/49675209-f64a1280-fa74-11e8-97db-6673976e01d1.png)

**Comment by Chocobozzz** [comment]
@Poslovitch any news on this? :)

**Comment by Poslovitch** [comment]
@Chocobozz hi, sorry, I'll have to dismiss my contribution. I don't feel confident enough with this language. Sorry again :(

**Comment by zacharystenger** [comment]
Hi, I'd like to fix this issue. I believe I've got a proper fix [here](https://github.com/zacharystenger/PeerTube/tree/negative-seconds). It uses Math.max to make a negative seconds result equal to zero instead. It also gets rid of a redundant Math.floor operation.

**Comment by rigelk** [comment]
@zacharystenger thanks ! Please make a pull request.

**Comment by Chocobozzz** [comment]
Fixed by @zacharystenger in https://github.com/Chocobozzz/PeerTube/commit/ec24796ea83dbe15863c4f074844abbb4cdd5e08
