### ISSUE TITLE
Problem whit cerbot

### ISSUE THREAD

**Issue by federicosanchez18** [Chocobozzz/PeerTube#1446]
hi i have a problem whit cerbot 

$ sudo systemctl stop nginx
$ sudo vim /etc/nginx/sites-available/peertube # Comment ssl_certificate and ssl_certificate_key lines
$ sudo certbot --authenticator standalone --installer nginx --post-hook "systemctl start nginx"
$ sudo vim /etc/nginx/sites-available/peertube # Uncomment ssl_certificate and ssl_certificate_key lines
$ sudo systemctl reload nginx

in this tape , my problem is this : 
when i execute this line :+1: 
$ sudo certbot --authenticator standalone --installer nginx --post-hook "systemctl start nginx"
i have this problem 
failed authorization procedure , peertube.example.com (http-01 ) : urn:ietf:params:acme:error:dns: :: DNS problem : nxdomain looking up a for peertube.example.com 

sorry mi english

**Comment by Chocobozzz** [comment]
Replace in you nginx template `peertube.example.com` with your real peertube domain name
