### ISSUE TITLE
Folders to organize videos

### ISSUE THREAD

**Issue by meaz** [Chocobozzz/PeerTube#1447]
I've just tried peertube and I find it awesome.

As a user (I'm not the admin of the instance I use), I would love to be able to create folders in order to organize the videos I've uploaded.
At the moment, I just see the list of the videos I've uploaded in a chronological order. I guess that will start to be a bit messy when I have lot of videos.

**Comment by Poslovitch** [comment]
There is basically the ability to create "sub channels" right now, but these can't be a viable long-term alternative to playlists or folders

**Comment by Chocobozzz** [comment]
Thanks for the issue, but I think what you want is playlist support: https://github.com/Chocobozzz/PeerTube/issues/14
