### ISSUE TITLE
Problem certificated

### ISSUE THREAD

**Issue by memx6** [Chocobozzz/PeerTube#1449]
When I request the certificates, this error appears ...

Failed authorization procedure. fegoma.com (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://fegoma.com/.well-known/acme-challenge/oc9Qils9ITwLXQCNH-ZPDVTfiFZUAYA4X18bDyOZ8M8: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\r\n<HTML><HEAD><TITLE>\ufffd\u07b7\ufffd\ufffd\u04b5\ufffd\ufffd\ufffd\u04b3</TIT"

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: fegoma.com
   Type:   unauthorized
   Detail: Invalid response from
   http://fegoma.com/.well-known/acme-challenge/oc9Qils9ITwLXQCNH-ZPDVTfiFZUAYA4X18bDyOZ8M8:
   "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"
   \"http://www.w3.org/TR/html4/strict.dtd\">\r\n<HTML><HEAD><TITLE>�\u07b7��ҵ���ҳ</TIT"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

The server you use for certificates is "sudo certbot --nginx -d fegoma.com"

in the configuration of the nginx just modify the fields where "peertube.example.com" appeared

I can not find a step by step explanation of the changes that must be made on the server, I would appreciate if you can help me.

**Comment by memx6** [comment]
I am using Ubuntu 18.04. I have the most recent version and each dependency complies with the required ones.
probably it's let's encrypt, but I can not find documentation that indicates the changes in the peertube file in / etc / nginx / sites-avaliable / peertube

**Comment by Chocobozzz** [comment]
I'm sorry but I don't know what's going on here. As @Nutomic said, try on the let's encrypt support forum
