### ISSUE TITLE
Control bar is transparent

### ISSUE THREAD

**Issue by kalterkrieg** [Chocobozzz/PeerTube#145]
Hello,
The control bar on videos is always transparent, I don't think this is intended.

https://github.com/Chocobozzz/PeerTube/blob/492fd28167f770d79a430fc57451b5a9e075d8e7/client/src/sass/video-js-custom.scss#L107
https://github.com/Chocobozzz/PeerTube/blob/492fd28167f770d79a430fc57451b5a9e075d8e7/client/src/sass/video-js-custom.scss#L108

Removing this last line fixes the issue

**Comment by Chocobozzz** [comment]
Please tell me if it's fixed with the new player: https://peertube2.cpy.re/videos/watch/5a6133b8-3e0c-40dc-b859-69d0540c3fe5

**Comment by kalterkrieg** [comment]
This is fixed indeed

**Comment by Chocobozzz** [comment]
Thanks. Will be merged in a few weeks.
