### ISSUE TITLE
Seperate redundancy video from local video

### ISSUE THREAD

**Issue by Kazer67** [Chocobozzz/PeerTube#1450]
The idea is to use different folder from local video and redundancy video.

For backup purpose, it make sense to backup our video, but not the video from other instance

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/6040f87d143a5fa01db79867ece8197c3ce7be47 & https://github.com/Chocobozzz/PeerTube/commit/b9fffa297f49a84df8ffd0d7b842599bc88a8e3e
