### ISSUE TITLE
Replace the rating system w/ favorites

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#1451]
It feels like ratings only exist in PeerTube because YouTube had them. Personally, I've never seen them used in a constructive way that would actually benefit the creator or community, just fueling hostility and negativity or standing in for what should be moderator action. Favorites here would be similar to other AP software where you'd hit the button and be able to view that list of posts later.

**Comment by Chocobozzz** [comment]
Or just allow uploaders/admin to hide the dislike button.

**Comment by XenonFiber** [comment]
@Chocobozzz I think that's a good feature, but I still don't see the point of ratings. They don't solve any problems or add any real functionality.

**Comment by XenonFiber** [comment]
My own instance's CSS is setup like this right now actually. 
![image](https://user-images.githubusercontent.com/28912578/49913012-9f1bb780-fe51-11e8-9684-706c437c40af.png)
It acts the same way as the rest of the Fediverse since likes are already considered the same as favorites in PT. It looks pretty nice and doesn't bring in anything unnecessary from YouTube.

**Comment by Serkan-devel** [comment]
Sometimes forced positivity wouldn't be good. Something like YouTube rewind 2018 would be seen by a viewer as positive and like the video as well.

At least for me, dislikes would make me want to assess more about what's wrong about the video.

If one disables ratings, one should disable both likes and dislikes. People who only see like counts and don't think that critically, might spread fake news even faster.

**Comment by Serkan-devel** [comment]
Actually, how are down votes even transmitted over the fediverse?

**Comment by XenonFiber** [comment]
@Serkan-devel They aren't. Only other PeerTube instances can see them.

**Comment by realityfabric** [comment]
@Serkan-devel if you want feedback regarding things that are wrong with a video, there is a comment section which allows for far more than a vague thumbs down.

**Comment by Chocobozzz** [comment]
With the current plugin & theme system, you can now easily replace the like button with a star to represent a "favorite" and hide the dislike button.
