### ISSUE TITLE
Password is mandatory to execute the import script

### ISSUE THREAD

**Issue by roipoussiere** [Chocobozzz/PeerTube#1452]
**What happened?**

Executed the import script peertube-import-videos.js as described [here](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#peertube-import-videosjs), without filling password (because I don't want it printed in my bash history), but I got:

>     --password field is required.

**What do you expect to happen instead?**

The script asking me the password, as explained in the documentation:

> - `PEERTUBE_PASSWORD` : password of your PeerTube account (if omitted, you will be prompted for it)

**Steps to reproduce:**

Simply execute the script without filling the password field:

    node dist/server/tools/peertube-import-videos.js -u "<peertube url>" -U "<peertube user>" -t "<Youtube channel>"

**Additional information**
* PeerTube version or URL: v1.0.1 (commit 06471769)
* Browser name/version: -
* NodeJS version: v8.14.0

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/5b036b8ef2f15c30afe6cddfe9bcfc5816b08bba

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/e8a739e880593c3ffd07a634d5ff62690ed844f6

**Comment by SaraSmiseth** [comment]
I followed the steps [here](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#installation) and when I omit the password it just fails and does not ask me. I just cloned the repo and am at commit dc48fdbe68e9dd3a3a6028181e61d8595d98e654.
