### ISSUE TITLE
Import script: option to publish videos before transcoding finished

### ISSUE THREAD

**Issue by roipoussiere** [Chocobozzz/PeerTube#1456]
Importing a full channel with the import script take a very, very long time. It appears that this is due to videos transcoding: this long task need to be finished before publishing each video, which is may take more than a week when importing dozens of videos.

We could use an option like `--publish-directly` or something similar to tell PeerTube to publish videos before transcoding them.

**Comment by Chocobozzz** [comment]
Done/fixed in https://github.com/Chocobozzz/PeerTube/commit/891bc2ffadd5dedae316fcc80856ff859e6f8336
