### ISSUE TITLE
Video upload fails with "Unknown Error"

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1460]
When I try to upload a specific video file to my instance, it fails every time. I tried to force reload the page and even restart the server, but nothing helped. The browser console only shows:
```
Backend returned code 0, errorMessage is: Unknown error.
```
I didn't have time to check the server logs yet.

I could upload the video without problems after running `ffmpeg -i old.mp4 new.mp4`.

Video file: https://nextcloud.nutomic.com/index.php/s/qrCW4m6cREL7faB

* PeerTube version or URL: https://peertube.social
* Browser name/version: Firefox 63

**Comment by Chocobozzz** [comment]
Could you paste logs related to your upload please?

**Comment by Nutomic** [comment]
Hmm I tried it again, but this time the same video was uploaded without any problems. And unfortunately, it seems systemd was (by default) configured not to store logs persistently. Unfortunately I don't have any info now, but I will reopen if I get the problem again.

**Comment by gegeweb** [comment]
I had this error too with large videos.
On client side only an « unknown error » reported. An empty response for the POST xhr request.
No error on the Peertube's logs.

But there is a '499' response from nginx (no error in nginx log).
`2a03:4980:104:100:59e7:766:990a:c818 - - [16/Dec/2018:10:11:54 +0100] "POST /api/v1/videos/upload HTTP/2.0" 499 0 "https://peertube.gegeweb.eu/videos/upload" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0"`

I can always reproduce with large video.

I think we must reopen this… 

I've found this about the '499' nginx response :
https://stackoverflow.com/questions/15613452/nginx-issues-http-499-error-after-60-seconds-despite-config-php-and-aws

<img width="1680" alt="capture d ecran 2018-12-16 a 09 16 02" src="https://user-images.githubusercontent.com/9108457/50051968-a0343980-011c-11e9-961e-78ce2ab26bb7.png">

**Comment by gegeweb** [comment]
I increased the timeout timeout for the proxy (600 -> 1800), same unknown error on the client side.
And we are redirected back to the upload page.

**Comment by gegeweb** [comment]
That is always a 499 response from nginx when it's occur.
Always after the user quota request.

```
2a03:4980:104:100:59e7:766:990a:c818 - - [16/Dec/2018:10:34:35 +0100] "GET /api/v1/users//me/video-quota-used HTTP/2.0" 304 0 "https://peertube.gegeweb.eu/videos/upload" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0"
2a03:4980:104:100:59e7:766:990a:c818 - - [16/Dec/2018:10:41:23 +0100] "POST /api/v1/videos/upload HTTP/2.0" 499 0 "https://peertube.gegeweb.eu/videos/upload" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0"
```

**Comment by gegeweb** [comment]
Found this : 
https://serverfault.com/questions/523340/post-request-is-repeated-with-nginx-loadbalanced-server-status-499

i'll try this solution (second answer), and I go back…

```
location / {
  proxy_read_timeout 120;
  proxy_next_upstream error;
  proxy_pass http://$backend;
}
```

**Comment by gegeweb** [comment]
If that help… (not sure)

> 499 is logged by nginx if client closes connection before nginx
was able to send anything to client.

https://forum.nginx.org/read.php?2,213789,213793#msg-213793

**Comment by gegeweb** [comment]
So… at this time, I can't upload large video files on my instance… :(

**Comment by gegeweb** [comment]
As mentioned in the #1359 comments, It seems that adding `proxy_next_upstream off;` in the proxy section of nginx config resolves this error.
