### ISSUE TITLE
Number of views is different for each instance

### ISSUE THREAD

**Issue by Angedestenebres** [Chocobozzz/PeerTube#1468]
Following this ticket : https://github.com/Chocobozzz/PeerTube/issues/1181

After checking, it seems the issue is still there.

On TeDomum : https://video.tedomum.net/videos/watch/55664db5-69f8-42c3-a722-ed7d70dca8dd

![tedomum](https://user-images.githubusercontent.com/21110485/49675615-b97f1b00-fa76-11e8-85b6-bde8e911263a.png)

And on peertube.video : https://peertube.video/videos/watch/55664db5-69f8-42c3-a722-ed7d70dca8dd

![capture d ecran_2018-12-07_23-21-52](https://user-images.githubusercontent.com/21110485/49675661-ed5a4080-fa76-11e8-85bc-b7756ed80455.png)

Both instances got updated in 1.1.0.

**Comment by Zig-03** [comment]
video.tedomum -

>  PeerTube v1.1.0 - CopyLeft 2015-2018

peertube.video -

> PeerTube v1.1.0 - CopyLeft 2015-2018

that fix was applied starting with the version v1.1.0-rc.1

**Comment by Zig-03** [comment]
I see 219 on both of them

**Comment by Angedestenebres** [comment]
You are right! Now I see 219 views too.

However, after checking I found another instance with a different number of view : https://peertube.duckdns.org/videos/watch/55664db5-69f8-42c3-a722-ed7d70dca8dd

![capture d ecran_2018-12-08_15-48-22](https://user-images.githubusercontent.com/21110485/49687257-deb86b80-fb00-11e8-8dec-698a7de2d9ab.png)

Maybe it needs some times to update the number of views ?

**Comment by Angedestenebres** [comment]
Ok, after checking again, now there is 219 views, I think I'm cursed :S

**Comment by Chocobozzz** [comment]
> Maybe it needs some times to update the number of views ?

Yes, federation is not instantaneous, and not perfect too (some messages are lost etc).
