### ISSUE TITLE
Improve upgrade script

### ISSUE THREAD

**Issue by Vertux** [Chocobozzz/PeerTube#1469]
**What happened?**

My installation environment does not exactly match the recommended installation, I have chosen a different installation path and a different database name. If I run the upgrade script, it complains about the missing path and database. 

**What do you expect to happen instead?**

I would expect, that the upgrade script uses the configuration values of the actual installation, database password included. It could make use of the related environment variables or parse the actual configuration file.

**Steps to reproduce:**

Just start the upgrade script.

**Additional information**
* PeerTube version or URL: v1.0.1

**Comment by Chocobozzz** [comment]
> but the issue with the installation path still persists

We could use `${scriptDirectory}/../..` as default variable [here](https://github.com/Chocobozzz/PeerTube/blob/develop/scripts/upgrade.sh#L5) :thinking:

**Comment by quentinDupont** [comment]
I also have differences in configuration files.
The script echoes the differences then end. It doesn't echo these last words : 
```

echo ""
echo "==========================================="
echo "==   Don’t forget to restart PeerTube!   =="
echo "==========================================="
```

**Comment by Chocobozzz** [comment]
You can use `PEERTUBE_PATH` to specify your installation directory.
