### ISSUE TITLE
Default Homepage Inconsistency on PWA

### ISSUE THREAD

**Issue by Fidgetcetera** [Chocobozzz/PeerTube#1472]
**What happened?** When logged into a progressive web app version of the peertube instance I am on (in firefox on Android, with the "add to homescreen" option), the page the PWA opens to is the "trending" timeline. When logged in and opening my peertube instance the "normal" way (opening any browser, including firefox on android, and going to the instance url), it defaults to the "local" timeline.

**What do you expect to happen instead?** The two views should be consistent with eachother.

**Steps to reproduce:**

1. Add a peertube instance with differing logged in/logged out views to homescreen.

2. Open, log in, and close it and reopen to the default view.

3. Compare to being logged into the instance in a normal web browser.

**Additional information**
* PeerTube version or URL: https://dialup.express/ 1.1.0
* Browser name/version: Firefox 63.0.2 on Android 9.0
* NodeJS version: -shrugs-

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by rigelk** [comment]
Indeed it's hardcoded in the webmanifest that defines A2HS applications: https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/manifest.webmanifest#L46

**Comment by Chocobozzz** [comment]
Should be fixed in https://github.com/Chocobozzz/PeerTube/commit/e2a095bc96dc3dfadba8c3d8487f3a18bc2b7a03

Thanks @Fidgetcetera for the issue
