### ISSUE TITLE
MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1486]
This error brought down my instance, as Peertube kept repeating the same error every time it was restarted by systemd. I finally fixed it by restarting the Peertube service manually.

Peertube logs are here:
https://gist.github.com/Nutomic/047bf1cc14e45be2ffa961c639799bf2

This is running Peertube 1.1.0 on Ubuntu 18.04, with Redis installed directly from the Ubuntu repos. I haven't changed anything related to Redis since I first set up the instance. I didn't find any errors in the Redis logs either, so it seems like a problem in Peertube.

**Comment by Nutomic** [comment]
Actually, I missed the error, it was this in Redis:
```
Write error saving DB on disk: No space left on device
```

This shouldn't put Peertube into an endless restart loop though.

**Comment by Nutomic** [comment]
Uh, is there any reason we need `/var/www/peertube/.cache/` and `/usr/local/share/.cache/, which together have 4.6 GB on my instance? Note that those are hidden folder, so it's pretty easy to miss that they're eating so much disk space.

Peertube is also spamming the logs a lot, my `/var/log/syslog` has another 4 GB.

**Comment by Nutomic** [comment]
Okay it turns out there was a problem with my logrotate, for some reason it hadn't rotated my logs for a couple of months. Hopefully that's fixed now.

Guess this can be closed.

**Comment by rigelk** [comment]
@Nutomic that's a side effect of using yarn: https://yarnpkg.com/lang/en/docs/cli/cache/
