### ISSUE TITLE
Add an option for language: "This video has no language"

### ISSUE THREAD

**Issue by multimob** [Chocobozzz/PeerTube#1489]
(enhancement)
If one does not fill the language drop-down box, the video language will be shown as "Unknown".

I suggest to add an extra "language" in the list, something that would say "No language".  To be used for instrumental music or any video with no words in the audio track.

Why?
1. Some people might want to filter videos and select only languages they understand
-- "Unknown" = possibly a foreign language I do not know → default could be not to show.
-- "No language" = universally understandable → default could be to show.
2. Instance admins could easily spot whether there are videos with missing information; today they cannot see whether it was intentionally left blank or whether the uploader forgot to fill the information.

My PeerTube version: v1.1.0

**Comment by r4dh4l** [comment]
> I suggest to add an extra "language" in the list, something that would say "No language". To be used for instrumental music or any video with no words in the audio track.

As mentioned in https://github.com/Chocobozzz/PeerTube/issues/2299:

It would be great to have additional options to specify "multiple languages" selection:
- Main language: (dropdown)
- With contributions in following languages:
(1st dropdown)
+ (2nd dropdown)
+ (3rd dropdown)
...

**Comment by n76** [comment]
This issue is nearly two years old but I’d like to add a vote for implementing this.
