### ISSUE TITLE
Move to sequelize-typescript

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#149]
https://github.com/RobinBuschmann/sequelize-typescript

**Comment by Chocobozzz** [comment]
Done: https://github.com/Chocobozzz/PeerTube/commit/3fd3ab2d34d512b160a5e6084d7609be7b4f4452

Thanks @RobinBuschmann for your awesome work. The life will be much more easier now :)

**Comment by RobinBuschmann** [comment]
Happy to hear that :)
