### ISSUE TITLE
Privacy selection randomly shows up different text entries for "public" (german)

### ISSUE THREAD

**Issue by Vertux** [Chocobozzz/PeerTube#1491]
**What happened?**
**What do you expect to happen instead?**
If I want to upload a video the web interface (german language selected) shows randomly (I cannot reproduce this issue) different text entries for public uploads. Most of the time the selections box under privacy (in german: Sichtbarkeit) shows "Jeder kann dieses Video sehen" but sometimes it shows "Öffentlich", which should be the expected and recommended text.
The meaning of the two different entries in german is the same, but the long text is more like an info text, which often shows up when you hover the mouse over an option/button.

![bildschirmfoto 2018-12-15 um 18 29 00](https://user-images.githubusercontent.com/10457918/50045942-ccf43c80-009b-11e9-8ca3-11e0926574be.png)

![bildschirmfoto 2018-12-15 um 18 24 37](https://user-images.githubusercontent.com/10457918/50045944-d2518700-009b-11e9-810f-d192bc6d265e.png)

**Steps to reproduce:**

I cannot reproduce this issues by will, because at the moment I can't tell what it triggers. For me it happens randomly 

**Additional information**
* PeerTube version or URL: v1.1.0
* Browser name/version: Safari Version 12.0.3 (14606.4.2), MacOS v10.14.3 (Beta)

**Comment by Vertux** [comment]
I took some new screenshots, which show the complete selection (now PeerTube v1.2.1) 

![short desc](https://user-images.githubusercontent.com/10457918/55683036-43fb5c80-593b-11e9-8a32-f40947649c32.png)

![long desc](https://user-images.githubusercontent.com/10457918/55683039-4fe71e80-593b-11e9-8db8-dd13fcb6925e.png)

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/71d00bfd7ff72923e5f76d851629786a56256d1e
