### ISSUE TITLE
Impossible to load local videos

### ISSUE THREAD

**Issue by tomdereub** [Chocobozzz/PeerTube#1495]
I can't load local videos anymore, while videos of other instances are working well.

**Steps to reproduce:**
You can try with this video : https://tube.plaf.fr/videos/watch/79cb7904-1f9c-499a-9c8e-983ed8b84def

**Additional information**
Installed on Yunohost 3.2.
* Browser name/version: Firefox 64

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): I found some logs in /home/yunohost.app/peertube/storage/logs, but it doesn't seem relevant : https://plaf.fr/zerobin/?03a336b00e3fb419#rRcBBJRdz9F6jbSde7VL1/OH39idofQuDV/G0CgnF6M=

**Comment by tomdereub** [comment]
I just tried to download the video and it worked for me... Clicking on the link you give doesn't work, but clicking on direct download on peertube work (seems to be the same link, so I don't understand what's happening).

**Comment by rigelk** [comment]
@tomdereub what is your Nginx configuration?

**Comment by tomdereub** [comment]
@rigelk : here : https://plaf.fr/zerobin/?9a29fc9d973eda82#nNQhoRzoRFH9vNVvmWqZap70TA9ofRqRispID0lee18=

**Comment by Chocobozzz** [comment]
@tomdereub there is a mistake in your configuration at this line: https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube#L141

**Comment by tomdereub** [comment]
Ok thanks, after removing "/videos" it's now working again !
