### ISSUE TITLE
Is there really a need for blurr if we can still understand what is being blurred?

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#1497]
From your [F.A.Q.](http://joinpeertube.org/en/faq/):

> Moreover, each administrator decides with which instances he wants to federate: he has the full control of the content he wants to display on his instance. It's up to him to choose the policy regarding this kind of videos. He can decide to:
> - Display them
> - Blur the title and thumbnail
> - Hide them

Do we really need the second option - `Blur the title and thumbnail`? Isn't it redundant?

If we intensify the blurr this means you can't see anything and thus it's the same as the 3rd option - `Hide them`. If we leave it as it is, then it's as if you would show it - `Display them`

So no matter which way we modify the blurr, it's always gonna be one or another. I can see blurr being useful when it's a direct link. You send someone a direct link, a person opens it and he sees a highly blurred thumbnail so he knows it's a NSFW video and then he decides if he wants to play it or not.

Also, is it possible to hide those instances that display NSFW videos from this page instances.joinpeertube.org/instances?

**Comment by XenonFiber** [comment]
I brought up something similar to how Mastodon deals with it in #1158. You could read exactly what the video's contents are rather than having a complete blur.

**Comment by Zig-03** [comment]
@XenonFiber I read that a few times and I honestly couldn't understand it, how would that practically work? And how does that overlap with this suggestion? I don't understand the difference between CW and NSFW.

**Comment by XenonFiber** [comment]
@Zig-03 A CW would let you specify what the content is and exactly how the thumbnail should be displayed.  It overlaps because if you don't think the thumbnail blur is useful, this could be a good replacement or something to include in addition.

**Comment by FirePowi** [comment]
Well, it might look something like that :
![image](https://user-images.githubusercontent.com/14030913/58465962-09db5980-8139-11e9-86b8-14fafbc97183.png)

**Comment by Chocobozzz** [comment]
Closing this inactive discussion. I think the blur system is fine because guessing is not seeing. And with the title on hover + the blurred image it can help to choose if you want to click on the video or not.

Regarding the CW system, there is a dedicated issue: https://github.com/Chocobozzz/PeerTube/issues/1158
