### ISSUE TITLE
Add a visible outline for donations

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#150]
Reading again the comments (especially [this one](https://framacolibri.org/t/framatube-peertube-posez-nous-vos-questions/1965/65), an important factor for future adoption to a wider audience (yet not the mainstream ones) of creators will be for them to show their donations page(s). Of course they still have the video description, but a glorified button/set of buttons for donations might help.

I think that outline should be configurable at the account level, with per-video override. Graphics should be given for most of the services we accept, and no information (unless you can ensure the service doesn't track you back) should be pulled like a donation count.

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/07fa4c97ca50b83b0bee9230da97d02401b4e05f
