### ISSUE TITLE
Search engine to search simultaneously in all instances

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#1500]
Hello,

Currently, the instance search engine searches only in the instance and the ones that are federated to it. For the rest, i have to search on dozen instances to have a chance to find an user/video. Il would be more ergonomic and user-friendly to be able to search in all existing instances at the same time, but i don't know if it is technically possible.

**Comment by rigelk** [comment]
Hi @stemy2! Please look out for related issues before creating one, as issue #824 already covers this. You can then detail further your use case there.
