### ISSUE TITLE
Search field is not working in the followers list.

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#1502]
**What happened?**

Search field is not working in the followers list.

**Steps to reproduce:**

1. Go on /admin/follows/followers-list

2. Type something in the search field

**Additional information**
* PeerTube version or URL: https://www.yiny.org/ (version 1.1.0)
* Browser name/version: Firefox

**Comment by Chocobozzz** [comment]
Thanks for the issue @JohnXLivingston, it has been fixed in https://github.com/Chocobozzz/PeerTube/commit/16c07398f2ed884b9223b3e18c5e541cf9ab8469
