### ISSUE TITLE
Subscribe help button text hidden

### ISSUE THREAD

**Issue by MayeulC** [Chocobozzz/PeerTube#1503]
**What happened?**
The helper text from https://github.com/Chocobozzz/PeerTube/pull/533 appears behind the subscription panel, as pictured below:
![screenshot_20181221_084650](https://user-images.githubusercontent.com/3952726/50330835-fa5a4380-04fc-11e9-97ae-df80bb33ce87.png)

**What do you expect to happen instead?**
The help text should either be overlayed above the subscription dropdown from #1100, or displayed aside. In both cases, it should be fully readable.

**Steps to reproduce:**

1. Go to a video page

2. Click the subscribe button

3. Click the help ("?") button next to the remote subscribe button

**Additional information**
* PeerTube version or URL: https://peertube.cpy.re and others (1.1.0)
* Browser name/version: Firefox 64

**Comment by buoyantair** [comment]
Hi I'll be happy to help with this smal lbug @rigelk :)

**Comment by Chocobozzz** [comment]
@buoyantair any news on this? :)

**Comment by buoyantair** [comment]
@Chocobozzz A little busy right now, if anyone wants to grab it, please do!

**Comment by Chocobozzz** [comment]
I think it has been fixed somewhere because I can not reproduce any more
