### ISSUE TITLE
Add an avatar picture while channel creation

### ISSUE THREAD

**Issue by Vertux** [Chocobozzz/PeerTube#1506]
This enhancement suggestion is related to #539

I am missing the option to directly select an avatar picture while creating a new channel. 

At the moment it looks like that:

![bildschirmfoto 2018-12-26 um 08 54 10](https://user-images.githubusercontent.com/10457918/50438031-8f3db200-08ec-11e9-9032-c4fd25315439.png)

 But it should look like that:

![bildschirmfoto 2018-12-26 um 08 54 48](https://user-images.githubusercontent.com/10457918/50437955-35d58300-08ec-11e9-99c7-caddb743f6c9.png)

**Comment by Chocobozzz** [comment]
Done in https://github.com/Chocobozzz/PeerTube/commit/27ec473f5306621643fcb169be7cfe6b15136265
