### ISSUE TITLE
[Arch Linux]  Problem with Node.js or documentation missing steps

### ISSUE THREAD

**Issue by ajhcasual** [Chocobozzz/PeerTube#1508]
**What happened?**
Using Arch Linux 64-bit
Peertube failed to start.  I ran `systemctl start peertube`
Then I ran `journalctl -feu peertube` per the production instructions.
The first time it failed, the error was "Error: Cannot find module 'bcrypt'"
I solved this running `npm install bcrypt`
Second time, the error was "Error: Cannot find module 'create-torrent'" (as the peertube user)
I solved this running `npm install create-torrent`

And so on for:
Error: Cannot find module 'pem'
...
Error: Cannot find module 'lodash'
...
Error: Cannot find module 'body-parser'
...
Error: Cannot find module 'express'
...
Error: Cannot find module 'morgan'
...
Error: Cannot find module 'cors'
...
Error: Cannot find module 'cookie-parser'
...
Error: Cannot find module 'helmet'
...
Error: Cannot find module 'useragent'
...
Error: Cannot find module 'ip-anonymize'
...
Error: Cannot find module 'config'
...
Error: Cannot find module 'multer'
...
Error: Cannot find module 'validator'
...
Error: Cannot find module 'fs-extra'
...
Error: Cannot find module 'winston'
...
Now I get an error that is not a missing module: "Error: Configuration property "listen.port" is not defined"

**What do you expect to happen instead?**
I expect that these modules would have already been installed automatically, OR that the documentation would instruct to do so.  I don't know which is intended, it is either a documentation problem, or a problem with npm on Arch Linux, I suppose.

**Steps to reproduce:**

Follow the "Dependencies" section for Arch Linux (https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/dependencies.md#arch-linux)
-the Fedora section has some items that Arch needed, but was not listed:
-systemctl enable postgresql
-systemctl enable nginx.service
-systemctl enable redis.service

Follow the Production guide, with a few references specific to Arch:
-https://wiki.archlinux.org/index.php/Nginx

1.

2.

3.

**Additional information**
* PeerTube version or URL:
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/dependencies.md#arch-linux is just one step from the production guide: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#dependencies

You have to follow the next steps

**Comment by ajhcasual** [comment]
I have followed all of the steps in the production.md guide.  There is nothing in production.md that would appear to solve these issues with nodejs modules.
