### ISSUE TITLE
Better instance rules/administrator responsability

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#1509]
* Ask some basic questions when the administrator login for the first time to its instance: 
   * Who moderates the instance? 
   * What is the policy regarding NSFW videos? (upload and display)
   * How long this instance is expected to be maintained?
   * Who is behind this instance? (a non profit? a single person?)
   * What is the business model?
   * What is/are the themes of the instance? (I think we should us PeerTube categories here)
   * Code of conduct
   * Terms
   * Main instance languages
   * Why did I/we create this PeerTube instance?
   * ...?
 * Display the answers in the signup form and about page

**Comment by roipoussiere** [comment]
> What is the policy regarding NSFW videos?

Related to #664 (Mark whole instance as NSFW)

**Comment by Booteille** [comment]
Could we add a form to select themes of the instance? "General", "Organization", "Ecology", "Technology", "Pornography", etc?
I often see people asking which instance should, which one has which themes, etc. If we could add filters on Instances API we could easily answer to these questions.

**Comment by Chocobozzz** [comment]
Thanks @Booteille, I edited the issue.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/2091
