### ISSUE TITLE
Export subscribed channels

### ISSUE THREAD

**Issue by pinage404** [Chocobozzz/PeerTube#1511]
# Feature request

Export the list of channels to which the user is subscribed

Maybe a step for https://github.com/Chocobozzz/PeerTube/issues/226 and https://github.com/Chocobozzz/PeerTube/issues/549

## Story

Today, the instance where i watch the videos has been down for somes minutes, i imagined that could be permanent

I haven't backuped the channels that i subscribed to

So, i would like to have a feature to export subscribed channels' list, to be able to go in another instance and find the vidéos that i want to watch

## Steps

1. **export subscribed channels** only
2. import system
3. export / import watched videos
4. export / import liked / disliked videos

**Comment by Altonss** [comment]
This feature is really important and would be super useful :) Are there any news about it ?

**Comment by freelancePerfexCrmDeveloper** [comment]
Contact Me for installation or setup on vps
https://wa.me/+919782533298
skype : ersonusaini

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/6215
