### ISSUE TITLE
Improved Search/Filter GUI

### ISSUE THREAD

**Issue by Vertux** [Chocobozzz/PeerTube#1514]
I think the search/filter interface could be more user friendly. If you switch between the different pages of the web interface, you always see the search input field, but you are not aware, that there is a filter option too. If you type in a keyword and hit enter you get the search results:

![bildschirmfoto 2018-12-28 um 13 19 25](https://user-images.githubusercontent.com/10457918/50515221-affc3800-0aa3-11e9-80d4-da42639d646a.png)

As you can easily see, it is not obvious that "Filters" provides additional functionality. Till today I totally overlooked this option, which was pretty misleading.
Beside the fact, that the dark theme makes it even harder to see the additional symbol in front of the "Filter" text.

![bildschirmfoto 2018-12-28 um 13 54 04](https://user-images.githubusercontent.com/10457918/50515964-3286f680-0aa8-11e9-948c-8a511dd7a786.png)

Because Filter and Search are totally different concepts, I would recommend to decouple them and **always** show e.g. a Filter Button on any page, which lists videos "My videos", "Local videos", "Popular videos" etc. - like that:

![bildschirmfoto 2018-12-28 um 13 34 52](https://user-images.githubusercontent.com/10457918/50515506-71677d00-0aa5-11e9-9c38-9010d16cb1cb.png)

Bear in mind, that most people do expect, that the search does only effect the currently displayed content, but that's not the case (yet). So a search does not give them the result they expecting, but a filter would do, which makes it even more important to always show the filter option.

**Additional remark:** For me it was pretty confusing too, that I can initiate a search by clicking on the magnifying glass symbol without to type in any keyword before - that makes not really sense. Nevertheless even if you got a large search result, it should show the exact number of hits 
e.g. "**3.436 Ergebnisse**" but not this:

![bildschirmfoto 2018-12-28 um 13 43 58](https://user-images.githubusercontent.com/10457918/50515879-9eb52a80-0aa7-11e9-9f02-70c27eb284fb.png)

**Additional information**
* PeerTube version or URL: v1.1.0, https://peertube.togart.de
* Browser name/version: Safari Version 12.0.3 (14606.4.3) - (Mac)

**Comment by rigelk** [comment]
The top search bar was reworked recently, and will continue to be with something taking from the following mockup: https://codepen.io/rigelk/pen/qBdoKQM?editors=1100

**Comment by Chocobozzz** [comment]
Closing this old and inactive discussion. Feel free to comment if you want it to be reopened.
