### ISSUE TITLE
How can I directly enter into the database?

### ISSUE THREAD

**Issue by AmesianX** [Chocobozzz/PeerTube#1515]
docker exec -it peertube_peertube_1 nodejs a.js

1. case-1
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13
Executing (default): INSERT INTO video (id, uuid, name, category, licence, language, privacy, nsfw, description, support, duration, views, likes, dislikes, remote, url, state, commentsEnabled) values ('8', '75535cf8-98cd-4e19-a227-cbff891a7991', 'Title', '13', '7', 'ko', '1', 'false', 'test, 'test', '3492', '0', '0', '0', 'false', 'https://example.net/videos/watch/75535cf8-98cd-4e19-a227-cbff891a7991', '1', true)

Unhandled rejection SequelizeDatabaseError: column "commentsenabled" of relation "video" does not exist

2. case-2
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13
Executing (default): INSERT INTO video (id, uuid, name, category, licence, language, privacy, nsfw, description, support, duration, views, likes, dislikes, remote, url, state) values ('8', '75535cf8-98cd-4e19-a227-cbff891a7991', 'Title', '13', '7', 'ko', '1', 'false', 'test', 'test', '3492', '0', '0', '0', 'false', 'https://example.net/videos/watch/75535cf8-98cd-4e19-a227-cbff891a7991', '1')

Unhandled rejection SequelizeDatabaseError: null value in column "commentsEnabled" violates not-null constraint

3. How can I directly enter into the database?
I uploaded the video file in a different way first. And we need a method that can input directly into the database. And I need a way to create additional torrent files. I am using it in the docker, but none of the management tools work properly.
 
cat a.js

`const Sequelize = require('sequelize');
const sequelize = new Sequelize('peertube', 'postgres_user', 'postgres_password', {
    dialect: "postgres",
    host: "peertube_postgres_1",
    port: 5432
});
sequelize.query("INSERT INTO video (id, uuid, name, category, licence, language, privacy, nsfw, description, support, duration, views, likes, dislikes, remote, url, state, commentsEnabled) values ('8', '75535cf8-98cd-4e19-a227-cbff891a7991', 'Title', '13', '7', 'ko', '1', 'false', 'test', 'test', '3492', '0', '0', '0', 'false', 'https://example.net/videos/watch/75535cf8-98cd-4e19-a227-cbff891a7991', '1', 'true')").then(myTableRows => { console.log(myTableRows) });
`

Why are commentsEnabled errors?

**Comment by Chocobozzz** [comment]
You have to use "" to name your columns: `INSERT INTO "video" ("id", ..., "commentsEnabled", ...)`
