### ISSUE TITLE
Please implement support for Blind Key Rotation (privacy feature)

### ISSUE THREAD

**Issue by kaniini** [Chocobozzz/PeerTube#1516]
### Background

Blind Key Rotation is a mitigation for the problem that JSON-LD Linked Data Signatures are irrevocable.  It is also useful (albeit less so) in the context of HTTP Signatures, since HTTP Signatures only sign headers and not the object itself, and are also detached from the object.

Because PeerTube implements support for JSON-LD Linked Data Signatures, implementing Blind Key Rotation is important for solving trust & safety issues (lack of future deniability) with this signature scheme!

### Implementation - receiving objects

Supporting Blind Key Rotation in the validation pipeline is simple enough: if a signature validation fails, refetch the remote actor and recheck the signature accordingly.

### Implementation - deleting objects

Supporting Blind Key Rotation to enhance the deniability of deleted objects is also simple enough: send the `Delete` signed with the original key and then silently replace the keypair.  The new keys will be fetched when the user publishes new content.

### Questions?

Contact me on fediverse: https://pleroma.site/kaniini

**Comment by Chocobozzz** [comment]
Hello,

It should already be implemented.
