### ISSUE TITLE
Incomplete video upload results in unused private video

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1517]
**Steps to reproduce:**

1. click on upload button

2. upload a video file

3. wait for file upload to complete

4. don't click "publish"

5. close the tab or leave `/videos/upload` by going somewhere else, eg `/videos/trending`

**What happened?**

The uploaded video is stored under `/my-account/videos`, without the user being aware of this. I had multiple of these videos on my account, and they are doing nothing but taking up space.

**What do you expect to happen instead?**

- Delete these videos after some timeout, eg after one week.

- Delete the video immediately when the user leaves the upload page (this would also save transcoding time).

- Prompt the user what to do with them (and encourage the user to delete it if it won't be used).

**Additional information**
* PeerTube version or URL: https://peertube.social

**Comment by Chocobozzz** [comment]
Related to https://github.com/Chocobozzz/PeerTube/issues/1150

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/674a66bbda7ceb7aed3c2e6aefddc2793207d94b
