### ISSUE TITLE
CC doesn't work in HTTP fallback

### ISSUE THREAD

**Issue by Gr33nEyes** [Chocobozzz/PeerTube#1519]
Capture Captions don't work in HTTP (WebSeed)

**Comment by Chocobozzz** [comment]
I'm sorry I don't understand. Please fill the issue template.

**Comment by Chocobozzz** [comment]
@filmaidykai Oh yes, see https://github.com/webtorrent/webtorrent/issues/1556#issuecomment-448056435 for more information

**Comment by filmaidykai** [comment]
So how I can see now we have to wait for new chrome version

**Comment by Gr33nEyes** [comment]
I mean, subtitles don't work in HTTP

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/c32bf839c11557cac527ca5f181d1ce39fc80974
