### ISSUE TITLE
How to upgrade without git?

### ISSUE THREAD

**Issue by anmol26s** [Chocobozzz/PeerTube#152]
Hi
I want to upgrade without git. Can you please specify which directories and files are needed to backed up and restored other then the `config/production.yaml` ?

**Comment by Chocobozzz** [comment]
You can't for now because there was no release yet.

I think that only directories in storage section of your production.yaml should be backed up.

**Comment by anmol26s** [comment]
But where are the videos and thumbnails stored? They are needed to be backup and restored too.

**Comment by Chocobozzz** [comment]
This is specified in your production.yaml file: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L19
