### ISSUE TITLE
Advertisement

### ISSUE THREAD

**Issue by DonCorleone9** [Chocobozzz/PeerTube#1521]
I want to create a PeerTube instance where i wish to host my videos.. I have around 3000 of them and have been creating them since a long time. I dont want others to make accounts on the website but merely wish to use peertube to make a video site..
I wanted to know how to add adblocks to the site. I find it illogical to not ALLOW ads. I mean this is open - source and hence people should be able to add advertisements if they wish to.

The logic mentioned is that only 3% creators on YT can make money that way.. But what about those with an existing audience which is loyal and dont want to charge them and just want to have an independent website and run videos with ads ?

Please can anyone help me with how to use adverts with this ?

**Comment by Serkan-devel** [comment]
What advertising platform do you want to even use?

**Comment by DonCorleone9** [comment]
Adsense, Adsterra there are many..

But i plan on starting with Adsterra

**Comment by Serkan-devel** [comment]
I think many federated instances might block your instance for using a poprietary ad-system, they don't really want their instances to be tracked by google and such

**Comment by Zig-03** [comment]
There are other ways of doing it while preserving user's privacy. For example, embed the ad into the video, or add a link in your video description and such. Just find a company that would like to sponsor you.

**Comment by buoyantair** [comment]
I'm thinking that instead of advertisements, there can be an implementation of payments system which gives a commission to the instance owners for every donation being made by a viewer to a channel. I think this would be much better than relying on other centralized services like patreon etc to support the individual. We can maybe also have a slider to choose how much money can go to the instance owner and how much money can go to the channel etc and this would provide even more freedom to the user to choose whom to support and how. 

At the end of the day, if the user depends on a centralized service like patreon, there's no guarantee that he will not get banned for his/her views etc.

**Comment by tilda** [comment]
A problem with this is how would payment work? Cryptocurrency? Using a external (proprietary possibly) payment processor?

**Comment by Serkan-devel** [comment]
Maybe link it to something, like [OpenBazaar](https://openbazaar.org/)

**Comment by obaviet** [comment]
> Một vấn đề với điều này là thanh toán sẽ hoạt động như thế nào? Tiền điện tử? Sử dụng bộ xử lý thanh toán bên ngoài (độc quyền có thể)?

Crypto like bit.tube

**Comment by Quix0r** [comment]
reviveAds is FLOSS, integration is possible.

**Comment by trymeouteh** [comment]
Why can't Peertube create its own advertising platform were the ads can be posted and managed on a peertube instance

**Comment by tilda** [comment]
If I'm thinking correctly about the idea, that means a centralized platform would need to be hosted, which doesn't make PeerTube decentralized anymore IMO

**Comment by trymeouteh** [comment]
> If I'm thinking correctly about the idea, that means a centralized platform would need to be hosted, which doesn't make PeerTube decentralized anymore IMO

It will still be decentralized. I thinkkany peertube instance should be able to have an ads platform or the ability to create a peertube ads platform instance. Which means anyone can setup an instance and upload ads for a price.

**Comment by rigelk** [comment]
> Why can't Peertube create its own advertising platform were the ads can be posted and managed on a peertube instance

It arguably out of the scope of PeerTube, which is about streaming videos, not ads. We have [a section of our FAQ](https://github.com/Chocobozzz/PeerTube/blob/develop/FAQ.md#are-you-going-to-support-advertisements) dedicated to it. That is also why we labeled this issue as a problem meant to be solved with plugins: you can develop your own solution that integrates with PeerTube, but we won't develop an ads management system *in* PeerTube.
