### ISSUE TITLE
[Ubuntu 16.04] 502 Bad Gateway with Nginx after following guides

### ISSUE THREAD

**Issue by ajhcasual** [Chocobozzz/PeerTube#1522]
**What happened?**

502 bad gateway
(Github puked up my more detailed report with a connection timeout, so I am writing a basic one because I don't want to write it twice and Chocobozzz will just tell me to re-read the docs and close it anyway.)

**What do you expect to happen instead?**

For it to work

**Steps to reproduce:**

1.  Install Ubuntu 16.04 server 64-bit

2.  Follow dependencies.md

3.  Follow production.md

**Additional information**
* PeerTube version or URL: v1.1.0
* Browser name/version: N/A
* NodeJS version: v11.6.0

* Link to browser console log if useful: N/A
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): N/A

**Comment by ajhcasual** [comment]
Some stuff from my detailed report:

production.yaml https://pastebin.com/ww97eBqw
nginx https://pastebin.com/R2JS6n4H

**Comment by fflorent** [comment]
Could you take a look at and provide here `/var/log/nginx/tube1.tnkr.space.error.log` and `/var/log/nginx/tube1.tnkr.space.access.log` (taking care of removing sensible information)?

**Comment by ajhcasual** [comment]
/var/log/nginx/tube1.tnkr.space.access.log: https://pastebin.com/i8ygnHu0

It does not present any explanation unless the '253' is meaningful.

**Comment by ajhcasual** [comment]
I have worked with user rjkmelb in the IRC and when I followed the instructions once again, this time on a server running Ubuntu 18.04, there are no errors and PeerTube webpage displays correctly.

It appears that with the "502 Bad Gateway" nginx is configured properly and working fine.  But while PeerTube _appears_ to be running - no errors, and the service remains active, so it hasn't died, it is not really working properly.

In the instance that worked on my 18.04 server, there are some additional strings in the log that did not show in the Arch Linux instance or the Ubuntu 16.04 instance.  rjkmelb has advised me to make extra sure to confirm what I have observed, search for an existing issue here on github and if it is not already reported, to report it concisely in a new issue.

The logging information that is present only in a "healthy" instance of PeerTube consists of the following:

> Creating a default OAuth Client.
> Creating application account.
> Creating the administrator.
> Client id: 
> Generating a RSA key...
> Generating a RSA key...
> Generating a RSA key...
> Username: root
> User password: 

I hope I can help to get PeerTube working on the Arch Linux and Ubuntu 16.04 OSes just like it does on Ubuntu 18.04.

**Comment by Lecquio** [comment]
Had same error on Ubuntu 16.04.
I get 502 bad gateway error after follow the peertube production guide peertube.
I check the nginx error log and I had this:

[error] 2204#2204: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 123.45.3.111, server: srv.mydomain.net, request: "GET / HTTP/2.0", upstream: "http://127.0.0.1:9000/", host: "srv.mydomain.net"

I could solved it editting the peertube nginx conf file, changing localhost:9000 to my server IP and reloading nginx.
