### ISSUE TITLE
Views count is not updated

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#1523]
**What happened?** 
Despite viewing videos on my computer, the views count is not incremented.

**What do you expect to happen instead?**

**Steps to reproduce:**
1. I viewed this video entirely, using Private mode in Firefox: https://skeptikon.fr/videos/watch/6b3c78bb-230d-4d0c-8452-bc917d744d0c
1. The views number remained at 0
1. Same using Tor-Browser
1. The views number remained at 0

The interesting thing is that I did the same with a video of another instance, much shorter (more convenient if you want to test by your own), and I got the same result: https://peertube.mastodon.host/videos/watch/55c2a088-dd6b-4fc0-bb4e-5c4fee6ef9e4

NB: If I may ask to get attention on this issue, I would be very grateful. Indeed, I host video makers who pay a great attention on views counts as a metric for popularity.

**Additional information**
* PeerTube version or URL: v1.1.0
* Browser name/version: Firefox / Tor-Browser
* NodeJS version: v8.14.0

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Views are buffered, and now the video has 18 views so it seems to work.

**Comment by fflorent** [comment]
I see, thanks!

**Comment by tele81** [comment]
where can I set the interval?
