### ISSUE TITLE
Order channels by last upload videos

### ISSUE THREAD

**Issue by Folaht** [Chocobozzz/PeerTube#1525]
I want to be able to organize my channels in case I change my mind and find one channel to be more or less important than the other.

**Comment by Chocobozzz** [comment]
What to you mean by "reorganize"? Changing the order in the channels page? (https://framatube.org/accounts/framasoft/video-channels)

**Comment by Folatt** [comment]
Yes. My main channel should be on top.
So if I delete my main channel's name in order to change it's name 
from kanal to sjehn_duh_folaht,
I would want to have the ability to move it above my music channel.

http://pix.toile-libre.org/upload/original/1546486441.png

**Comment by acebesmonte** [comment]
Please forgive my noob question. How can i make this video `https://video.valme.io/videos/watch/b27904fc-ce1d-40dd-b2bb-228f0d49e0ce` be searchable in `https://framatube.org`?

**Comment by alcalyn** [comment]
About reorganizing channel videos, I think this is a behaviour I don't expect. Let's explain me.

For example we can already reorganize a playlist, because playlists are videos picked from anywhere, and are just a list of videos.

Channels are more like a stream, with new videos that are posted. So I expect the latest video of a channel is simply the newest.

In your case, why creating a playlist would not satisfy your need ?

**Comment by realityfabric** [comment]
@alcalyn I believe it's the channels themselves, not the videos in the channels, which would be rearranged.

**Comment by alcalyn** [comment]
Oh, I get it ! That makes sense.

We can also think about how to display shared channels order when it will be implemented: #699 :p

**Comment by pprw** [comment]
+1

To have the ability to organize channels by hand would be nice. 

Even without implementing that, I think the default order should not following the dates of channel creation (which does not mean necessary anything). IMHO, channels should be ordered according to the last videos uploaded. If you uploaded something to a channel this channel will be on top. If you upload to another channel, the previsous channel will get down to second place, etc.

Therefore, old dead channels are always to the bottom, and visitors can access quickly to what new.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/e024fd6a7494b37251da1d59470324305cdb4129 & https://github.com/Chocobozzz/PeerTube/commit/dc2b2938c293bae271a27a6c823f66496998b4d3
