### ISSUE TITLE
Cannot recreate channel under same name.

### ISSUE THREAD

**Issue by Folatt** [Chocobozzz/PeerTube#1526]
**What happened?**

I deleted a channel because I wanted another channel to be on top of the list.

I receive the error message: « Ce nom existe déjà sur cette instance. »

[Also, the address of the first label overlaps with the second label](http://pix.toile-libre.org/upload/original/1546410752.png)

**What do you expect to happen instead?**

A newly created channel with the same old name.

**Steps to reproduce:**

1. Create channel

2. Delete channel

3. Create channel with same name.

* PeerTube version or URL: 1.1.0
* Browser name/version: Falkon/3.0.1
* NodeJS version: v11.6.0

**Comment by Chocobozzz** [comment]
Unfortunately you cannot recreate a channel that was deleted to prevent identity problems in the federation. But we should warn users when they try to delete their channel.

**Comment by Folatt** [comment]
Identity problems in the federation?
What is that supposed to mean?

One should be able to completely purge the channel name.
I deleted mine only because I wanted the other one to be on top.

**Comment by Chocobozzz** [comment]
@Folatt See https://github.com/Chocobozzz/PeerTube/issues/870

**Comment by Folatt** [comment]
Found it! It's in actors.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/b4593cd7ff34b94b60f6bfa0b57e371d74d63aa2

**Comment by leanderlindahl** [comment]
> Well I still want to be able to recreate it. Where can I find the used names in the database?
> 
> I tried peertube_peertube.videoChannel, but those contain the current channels.
> 
> [update]
> 
> Found it! It's in actors table.

I have the exact same issue. If the channel was created on the same peertube instance, there can't be a problem with recreating the same can there? I agree that this is not a very good rule.

**Comment by Chocobozzz** [comment]
> I have the exact same issue. If the channel was created on the same peertube instance, there can't be a problem with recreating the same can there? I agree that this is not a very good rule.

It can cause issues in the federation. You can create a dedicated issue where we can give the choice to the admin to force-recreate a channel.
