### ISSUE TITLE
Why is there a service for a twitter account? Why not for mastodon instead?

### ISSUE THREAD

**Issue by Folatt** [Chocobozzz/PeerTube#1527]
Twitter is centralized.
Mastadon is decentralized.

**Comment by JohnXLivingston** [comment]
It is required to enable the embeded video player on twitter. See the help button next to the "Instance whitelisted by Twitter" checkbox.

**Comment by rigelk** [comment]
Mastodon has no problem integrating PeerTube embeds, so we don't need extra configuration, unlike Twitter...
