### ISSUE TITLE
Problem connecting to database server

### ISSUE THREAD

**Issue by cclem25** [Chocobozzz/PeerTube#153]
Today I try to update on the develop branch and i can't start the server.

- OS: Debian 9
- Git clone from scratch
- Update nodejs to 8.X
- PostgreSQL database on another server 
- The production.yaml file has the right database server IP
- Connection through psql work like a charm

This is the bug when I try the production npm start
I also included the npm version output after.

https://pastebin.com/gZNyx1yW

if you need more tests just ask :)

Thank for the good job you do !

**Comment by Chocobozzz** [comment]
Oup's. Should be fixed :https://github.com/Chocobozzz/PeerTube/commit/228077efd73485a2832bb6211c9fa923158c2112

Please tell me if it is ok for you now.

**Comment by cclem25** [comment]
Thanks for the quick reply and update !
Yes it works great now, I close the issue :)

If you need human testing, just ask, it would be a pleasure to serve a great project
