### ISSUE TITLE
Support account subscriptions

### ISSUE THREAD

**Issue by stom79** [Chocobozzz/PeerTube#1530]
**What happened?**
I am currently integrating Peertube to Mastalab. I was abled to follow an account that was not a channel. 

Follow worked well with a POST call to `/api/v1/users/me/subscriptions` with the payload: `{uri: "xxxxx@peertube.social"}`

But the DELETE call to `/api/v1/users/me/subscriptions/xxxxx@peertube.social` gives `{"error":"Subscription xxxxx@peertube.social not found."}`

I can give the account in a private messages for tests?

---Edit

I checked with the web app with this account and the button to unfollow is not displayed. I also noticed that the call to check the relationship is not called: `/api/v1/users/me/subscriptions/exist`

OK. I have no issues with channels (I can follow and unfollow them). But I can only follow accounts (unfollowing them results in an account not found).

**Comment by Chocobozzz** [comment]
In theory we don't support accounts follow. But I'll add the fix to support accounts unfollow.

**Comment by Chocobozzz** [comment]
For consistency, I disabled subscription of accounts support in https://github.com/Chocobozzz/PeerTube/commit/2c0ccd4b3f5ec5633879e6b42cd5175e4de207cc
