### ISSUE TITLE
[API] Token is invalidated after a while

### ISSUE THREAD

**Issue by stom79** [Chocobozzz/PeerTube#1534]
**What happened?**
I am running two accounts with Mastalab and for both accounts, their token was invalidated after a while (I can't exactly say the delay of validity).
**What do you expect to happen instead?**
Have token not expiring after x days.
**Steps to reproduce:**

1. Install Mastalab 1.63.0-beta-1

2. Login with a Peertube account

3. Wait (some hours/days).

**Additional information**
* PeerTube version or URL: https://peertube.social
* Browser name/version: https://gitlab.com/tom79/mastalab/tags/1.63.0-beta-1
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

` fr.gouv.etalab.mastodon.client.HttpsConnection$HttpsConnectionException: {"error":"Token is invalid.","code":"invalid_token"}`

**Comment by stom79** [comment]
OK, they have 24h of validity:

`{"access_token":"xxxxxxxxxxxx","token_type":"Bearer","expires_in":86399,"refresh_token":"yyyyyyyyy"}`

**Comment by stom79** [comment]
I will implement the refresh token part on my side.

**Comment by stom79** [comment]
I am surprised because the token expired today and now I get:

`{"error":"Invalid grant: refresh token is invalid","code":"invalid_grant"}`

with:

params: `{refresh_token=xxxxxxxxxxxxxxxx, grant_type=refresh_token,  client_id=lalalalla, client_secret=lililili}` on `/api/v1/users/token`

**Comment by sunknudsen** [comment]
@stom79 Noticed that when I request `access_token` using `grant_type=refresh_token`, a  `refresh_token` is returned and the `refresh_token` used for the request is invalidated.

@Chocobozzz Is that expected behavior?

**Comment by Chocobozzz** [comment]
@sunknudsen yes it is

**Comment by sunknudsen** [comment]
@Chocobozzz Thanks for the follow-up... why? Isn't this unusual? I am developing [tube-manager](https://www.npmjs.com/package/tube-manager), a command line utility to manage and syndicate content between YouTube and PeerTube (see https://peertube.sunknudsen.com/videos/watch/c7233230-2890-49ad-a07d-2428a74516e2).

For security reasons, I prefer to store refresh tokens in my password manager and enter them when running tube-manager.

It's my understanding that refresh tokens are intended as long lived and access tokens as short lived.

**Comment by Chocobozzz** [comment]
Because it's safer to have a refresh token that could be used only once, and it simplifies our backend code. I understand that this causes an issue in your use case, but I'm not sure we'll have time to change the tokens architecture in PeerTube
