### ISSUE TITLE
postgresql container not named

### ISSUE THREAD

**Issue by adrian-amaglio** [Chocobozzz/PeerTube#1536]
**What happened?**
The postgresql container is not named and therefore not found wen doing `docker-compose up`. The command line displays : ` "err": "SequelizeHostNotFoundError: getaddrinfo ENOTFOUND db db:5432`

**What do you expect to happen instead?**
The postgresql container should be found

**Steps to reproduce:**
Following the docker compose installation documentation

**Fix**
Add a container_name field in docker-compose.yml
```
  postgres:
    image: postgres:10-alpine
    container_name: db
```

**Comment by adrian-amaglio** [comment]
I opened a pull request #1537

**Comment by rigelk** [comment]
Are you running with the default support files?

What container specifically uses the "db" name to reach the `postgres` container? In https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/config/production.yaml#L21 you can see the hostname used is the default name, not `db`.

**Comment by adrian-amaglio** [comment]
That’s wierd, I’m using this file [https://raw.githubusercontent.com/chocobozzz/PeerTube/master/support/docker/production/docker-compose.yml](https://raw.githubusercontent.com/chocobozzz/PeerTube/master/support/docker/production/docker-compose.yml)
found in the instructions here [https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/docker.md](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/docker.md)
Is this document outdated ?

**Comment by Chocobozzz** [comment]
> Is this document outdated ?

No, @rigelk linked the PeerTube **configuration** file, not the docker compose file. 

Try to re pull/re build your docker image first, we are in v1.1.0 now. Then, paste the content of your`.env` file if it still does not work.
