### ISSUE TITLE
[API] PUT /videos/{id}

### ISSUE THREAD

**Issue by stom79** [Chocobozzz/PeerTube#1541]
**What happened?**
I can't update tags.
**What do you expect to happen instead?**
Sending tags in an array and get them updated.

In the documentation: https://docs.joinpeertube.org/api.html#tag/Video/paths/~1videos~1{id}/put

tags parameter is defined as a String.

tags | (String) Video tags
-|-

But the web app uses an array

tags[i] | value
-|-
tags[0] | my_tag0
tags[1] | my_tag1
.. |..
tags[n] | my_tagn

I tried several ways to send them as array. I don't get errors but they are not updated. I am not sure to understand what is going wrong.

Tested values:

`&tags[0]=my_tag0&tags[1]=my_tag1&tags[2]=my_tag2`

`&tags[]=my_tag0&tags[]=my_tag1&tags[]=my_tag2`

**Comment by Chocobozzz** [comment]
Thanks, I updated the documentation: https://github.com/Chocobozzz/PeerTube/commit/1fd12c7cfa636d046d9f77293ad1d958763f67da

With the update endpoint, if you don't update the preview/thumbnail you can just send a JSON.

**Comment by stom79** [comment]
Thanks. But I am curious, why is it working for all parameters and not this one for tags. Also, I am not getting a malformed query.

**Comment by Chocobozzz** [comment]
I don't know sorry. Do you send a FormData body?

Closing since the documentation is fixed.

**Comment by stom79** [comment]
Yes, what's strange, every other parameters work. I will try to see with peertube.social admin if he can help me with logs.
