### ISSUE TITLE
Embed Links Don't Work on Behance.net

### ISSUE THREAD

**Issue by davidpgil** [Chocobozzz/PeerTube#1542]
I recently tried to embed my PeerTube video in Behance.net which is a site for artists to share their portfolio of artworks. Apparently it does not work. Here is a screenshot of the error:

![image](https://user-images.githubusercontent.com/41744832/50989195-ae3b6700-14dc-11e9-8295-60ff508a22c5.png)

**Comment by rigelk** [comment]
Behance.net whitelists embed domains to the list you can see in the screenshot. Inherently, this prevents decentralized software from having working embed :pensive:

**Comment by davidpgil** [comment]
@rigelk hehe, seems like we need to make a decentralized "Behance.net" 😜 ... For now, Vimeo it is...
