### ISSUE TITLE
NSFW videos are not blurred during a search

### ISSUE THREAD

**Issue by bristow** [Chocobozzz/PeerTube#1543]
**What happened?**

NSFW videos are not blurred during a search

**What do you expect to happen instead?**

NSFW videos should be blurred on the results list

**Steps to reproduce:**

1. Click on this link : https://tube.kdy.ch/search?search=charline or other word

2. See the NSFW videos from this user hardx@pornlap.com

3. His videos are blurred here : https://tube.kdy.ch/accounts/hardx@pornlap.com/videos

**Additional information**
* PeerTube version or URL: v1.1.0
* Browser name/version: Firefox
* NodeJS version:

**Comment by Chocobozzz** [comment]
Thanks @bristow, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/033bc0efc2ab2c517b4d7d53d09930b85f092b50
