### ISSUE TITLE
Error when uploading video from Android

### ISSUE THREAD

**Issue by stom79** [Chocobozzz/PeerTube#1544]
**What happened?**
Videos still show as transcoding when uploaded via Mastalab.
I use this library: https://github.com/gotev/android-upload-service

**Additional information**
* PeerTube version or URL: https://peertube.social/
* Browser name/version:  Mastalab

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): https://gist.github.com/Nutomic/954b9dfc942fd12edd0e8d55370a0643

**Comment by Nutomic** [comment]
This is the video in question: https://peertube.social/videos/watch/ef8bd89b-fe3d-4777-9947-0efbb4af8673

I don't think it has anything to do with Mastalab, but probably something is wrong with the video file itself (as Peertube shows it having 90000 fps).

**Comment by Chocobozzz** [comment]
Thanks for the issue.

Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/ef04ae20fe4155f516ab41959e312de093f98d0e
