### ISSUE TITLE
Cannot execute migration 0005

### ISSUE THREAD

**Issue by BigMayo** [Chocobozzz/PeerTube#1545]
**What happened?**
error: Cannot execute migration 0005.
**What do you expect to happen instead?**
Successful start
**Steps to reproduce:**

1. Follow all install directions

2. Get to systemd step

3. receive error message

**Additional information**
* PeerTube version or URL: peertube-v1.1.0
* Browser name/version: Chrome
* NodeJS version: v11.6.0

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Please paste the server logs.
