### ISSUE TITLE
Ability to Silence Specific Channels

### ISSUE THREAD

**Issue by techknowlogick** [Chocobozzz/PeerTube#1546]
As a regular non-admin user of PeerTube, there are some channels, that are totally fine, and don't break any rules but I would not like to see the content from due to the subject matter, and so I'd like to be able to hide them, and have the silence be effective just for me (others can chose to silence the channel as well).

General case: Imagine there is a cooking channel on a peertube instance, to most, including others on same instance, that would be fine, however I could be someone who due to various reasons would prefer not to see it. This is where I'd like to be able to just for me hide all content from this specific channel (other channels from this user are ok for me).

**Comment by Chocobozzz** [comment]
I'm sorry but adding muting feature adds complexity to the UI, our SQL queries and to the code. We already have 2 granularities that are instance muting and account muting, and I think it's enough (we always want more, but we have to make choices :) ).
