### ISSUE TITLE
Federate Reports

### ISSUE THREAD

**Issue by techknowlogick** [Chocobozzz/PeerTube#1547]
Right now reports are only sent to the admins of the instance that I report the videos from, could there be a way of federating these reports to the admins of the instance that the video is hosted on? Sometimes the remote instances have signups disabled meaning that I would be unable to create an account to report a video.

Here are related discussions/PRs from mastodon where they discuss pros/cons, how it should be implemented, and an example UI: https://github.com/tootsuite/mastodon/issues/2176 https://github.com/tootsuite/mastodon/pull/6570

**Comment by Chocobozzz** [comment]
Hello,

Video abuses are already federated to origin instances.
