### ISSUE TITLE
Add bandwidth settings

### ISSUE THREAD

**Issue by UgoM** [Chocobozzz/PeerTube#155]
Hi,
When using a torrent client, it is always possible to manually set how much download/upload you want. It could be nice to have such settings too. For example, I don't want my internet to get down for other people in my house just because I'm loading a big video. 
It could be an answer to https://github.com/Chocobozzz/PeerTube/issues/75.
Thanks for the amazing work,

**Comment by Chocobozzz** [comment]
Related to https://github.com/webtorrent/webtorrent/issues/163

**Comment by conferences-gesticulees** [comment]
This really needs to be as automatic as possible. On an ADSL link, a maxed out upload queue usually break the network for any other connected computers. VoIP applications are the most impacted. Unlike a torrent client, it'll be hard for users to make the connection between watching a video and killing the connection for their roomate.

Manual settings would not work well with PeerTube decentralized aspect. It would be a PITA to have to adjust bandwidth settings on every instance.

**Comment by Chocobozzz** [comment]
Based on real test usage and users feedback, with the new HLS player I don't think we need this kind of setting. If you're behind an ADSL link, most of the time you won't upload data. Feel free to comment if you want to discuss about it.
