### ISSUE TITLE
Dual/Multi Audio Tracks.

### ISSUE THREAD

**Issue by Empathetic** [Chocobozzz/PeerTube#1552]
Is there anyway that Peertube could add multiple audio track support for the same video source? I have 100s  of videos that I have already transcoded/muxed for friends and family with multiple language audio tracks with the same video source in sync. I really would like a web tube player that can switch to different audio tracks with the same video source just like regular media players. This would make peertube unique from youtube and a lot of other video hosting sites and would be amazing at giving you guys even more exposure for being unique.

**Comment by rigelk** [comment]
This is probably a duplicate of #939.
