### ISSUE TITLE
After down, some servers won't send updates

### ISSUE THREAD

**Issue by PhieF** [Chocobozzz/PeerTube#1553]
Hi,

on PeerTube v1.1.0
 I've noticed that some servers aren't sending me their new videos since about a week and I think it is because my peertube instance went down at this time (one week ago)

Do you think it could be the reason why ? It was down for 2 days (Friday to sunday)

Thanks !

**Comment by Chocobozzz** [comment]
@PhieF Which instances?

**Comment by Chocobozzz** [comment]
@PhieF lostpod still have followers: https://lostpod.space/api/v1/server/followers?search=mastodon.host

But exode.me does not have followers anymore: https://exode.me/api/v1/server/followers

Did you restore the database or delete some entries in there?

**Comment by PhieF** [comment]
Well, trying to fix the bug I've talked about, I deleted every server of the server table, then readded them. Stupid as I am I thought it was only the "follow" list but I guess it also removed the followers, do you know if I could restore them through an old dump ? Restoring only new data ? (which table are concerned by the follow list ?)

but the problem is also on lostpod : for example with this channel https://lostpod.space/video-channels/4f090d91-70e5-470f-bbd2-9ef73b1091ea@peertube.mastodon.host/videos

**Comment by Chocobozzz** [comment]
> Stupid as I am I thought it was only the "follow" list but I guess it also removed the followers, do you know if I could restore them through an old dump ? Restoring only new data ? (which table are concerned by the follow list ?)

If you just want to restore your followers, maybe: server, actor, account, videoChannel, actorFollow, avatar.

> but the problem is also on lostpod : for example with this channel https://lostpod.space/video-channels/4f090d91-70e5-470f-bbd2-9ef73b1091ea@peertube.mastodon.host/videos

What is exactly the problem with this channel? Some videos are not federated? It lost some followers?

**Comment by PhieF** [comment]
I don't have the latest videos, and this is not the first time I've got this issue. As if I had to remind the servers that mine is back online, I guess this is how it works: they send me new videos ? It seems that some don't send them to me anymore, then

Is it possible to force sync like the first time we follow them ?

**Comment by PhieF** [comment]
But unfollowing will delete user's subscription ?

**Comment by Chocobozzz** [comment]
@PhieF No, users subscriptions are not related to instances subscriptions
