### ISSUE TITLE
All-in-one Docker container

### ISSUE THREAD

**Issue by taohansen** [Chocobozzz/PeerTube#1554]
An all-in-one container would greatly simplify deployment and administration for instance owners. Funkwhale is in the process of migrating to an all-in-one which I have had great success deploying: https://github.com/thetarkus/docker-funkwhale

**Comment by Chocobozzz** [comment]
Hi,

How is that better than docker-compose?

**Comment by taohansen** [comment]
One container is easier to manage than a few. See the LinuxServer project
for examples of unified Docker containers that make it easy for anyone to
run.

On Thursday, January 17, 2019, Chocobozzz <notifications@github.com> wrote:
> Hi,
>
> How is that better than docker-compose?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/N2jKpxHiae775XNDkH4BAIXDTpL4bjrLwetOTYrVKLvi3uPKzGp-d03DK5dfR4zIl3T4Q9NH0yh0sCTQrTKXfrNx4lWn-N8per4Czi1MzqBhjwJvUh8cHKpk_ZZH5VpxIEdAm_gm1gtyWKu0UWdgVPQWTQ=s0-d-e1-ft#https://github.com/notifications/beacon/AIMBl_-0FxGdFeeSmj5nOSqOwH3jdq1Aks5vEG4hgaJpZM4aFAtm.gif>

**Comment by Chocobozzz** [comment]
I don't want to maintain another docker image, but feel free to create your own :)

**Comment by Serkan-devel** [comment]
Having only one docker image might cause a single point of failure instead of having each program their own container

**Comment by taohansen** [comment]
Which makes it even easier to blow up and start over.

On Thursday, January 17, 2019, Serkan-devel <notifications@github.com>
wrote:
> Having only one docker image might cause a single point of failure
instead of having each program their own container
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/a1IeZlmeXDuS80YytI0ro5_m1O2doxD2MyLmYfNUqS1aphFOeys7dUywTWtkhbR6h0Q7nRQbOC6b76iMO4bvxbLnJS9_I8BcymhrWs3CqSr2QnLnuwcmo4y5lvgPCi9tgEQCNMbxw0bykf4hhTrxadkxFw=s0-d-e1-ft#https://github.com/notifications/beacon/AIMBl3-mXoUcfcFj_dqowqA9RXjrXawJks5vEKzdgaJpZM4aFAtm.gif>
