### ISSUE TITLE
[API] - URL to accounts in notifications don't use the domain v1.2.0-rc.1 

### ISSUE THREAD

**Issue by stom79** [Chocobozzz/PeerTube#1555]
**What happened?**
Currently, notifications don't use the domain of the instance in the link.

For example, if I receive a follow notification the link is: 
https://peertube.social/accounts/tom79/videos 
But that will fail, it should have been:
https://peertube.social/accounts/tom79@ins.mastalab.app/videos
Also, it could mislead users, because the link can potentially refer to an existing account that were not at the origin of the action.

**What do you expect to happen instead?**
The API should return for `actorFollow` -> `follower` -> `name` -> name@example.net (if from a remote instance)

**Steps to reproduce:**

1. Make an action with an account A to an account B not on the same instance

2. Check notifications on the account B

3. Follow the link for the account A from notifications of the account B

**Comment by Chocobozzz** [comment]
Thanks for the issue. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/38967f7b73cec6f6198c72d62f8d64bb88e6951c
