### ISSUE TITLE
Add danish (da / da-DK) locale to Zanata

### ISSUE THREAD

**Issue by 22decembre** [Chocobozzz/PeerTube#1558]
I wish to begin translation in danish.

**Comment by ldidry** [comment]
Here you go, it's activated on https://trad.framasoft.org/project/view/peertube (main project), https://trad.framasoft.org/project/view/join-peertube (joinpeertube.org web site) and https://trad.framasoft.org/project/view/docs-peertube (documentation site).

You first need to create an account on https://trad.framasoft.org and join the `da` or `da-DK` language team.

Thank you :slightly_smiling_face:

**Comment by 22decembre** [comment]
I already signed up. Will begin translations soon.
