### ISSUE TITLE
Support m4v file format

### ISSUE THREAD

**Issue by aerogus** [Chocobozzz/PeerTube#1559]
peertube v 1.1.0

**What happened?**

Uploading a video with .m4v extension failed with error message : 

{"path":"/api/v1/videos/upload","err":{"videofile":{"location":"body","param":"videofile","msg":"This file is not supported or too large. Please, make sure it is of the following type: .mp4, .ogv, .webm"}},"level":"warn","message":"Incorrect request parameters","label":"videos.adhocmusic.com:443","meta":{"path":"/api/v1/videos/upload","err":{"videofile":{"location":"body","param":"videofile","msg":"This file is not supported or too large. Please, make sure it is of the following type: .mp4, .ogv, .webm"}}},"timestamp":"2019-01-20T15:46:34.130Z"}

m4v and mp4 beeing technically very similar, can you allow the upload of this kind of file ?
when I rename m4v with mp4, the file is well uploaded and processed correctly.

Another suggestion would be to generate a warning client side, ***before upload***, when an extension is not allowed.
I know the label explicitly mention "mp4 + ogv + webm" but m4v is a very popular in Apple World (one of output format in Final Cut)

**What do you expect to happen instead?**

Beeing able to upload a .m4v video in peertube

**Comment by Chocobozzz** [comment]
m4v support in https://github.com/Chocobozzz/PeerTube/commit/c37a52b046a419a7f2b69c7a98904b15db9786d9
