### ISSUE TITLE
Add some strings to Zanata

### ISSUE THREAD

**Issue by AutomCoding** [Chocobozzz/PeerTube#1560]
The strings in [/client/src/assets/player/theater-button.ts](https://github.com/Chocobozzz/PeerTube/blob/7b95f31385eca59ac18197539de30268acc18986/client/src/assets/player/theater-button.ts) have not been mared as translateable.

Also, some strings are marked as translateable in the sorce files, but have not been added to Zanata:
* All three strings in [/client/src/assets/player/webtorrent-info-button.ts](https://github.com/Chocobozzz/PeerTube/blob/c199c427d4ae586339822320f20f512a7a19dc3f/client/src/assets/player/webtorrent-info-button.ts)
* Line 231, "Copy magnet URI", in [/client/src/assets/player/peertube-player.ts](https://github.com/Chocobozzz/PeerTube/blob/7b95f31385eca59ac18197539de30268acc18986/client/src/assets/player/peertube-player.ts) is not in Zanata, but all other marked strings in the file are

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/16f88ee5e6d671e51dd002b1f5e59db89f61172c
