### ISSUE TITLE
Dep installation fails due to unexpected request failure

### ISSUE THREAD

**Issue by buoyantair** [Chocobozzz/PeerTube#1561]
**What happened?**
I am trying to setup Peertube for local development, when I came across this error while installing via yarn.
**What do you expect to happen instead?**
Installation should finish without errors
**Steps to reproduce:**

1. Follow the steps at [doc/dependencies](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/dependencies.md#arch-linux)

2. Follow steps at [contributing.md](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/CONTRIBUTING.md#develop)

3. When you run `yarn install --pure-lockfile` the installation fails due to a 404 request being sent back from yarnpkg

**Additional information**
* PeerTube version or URL:
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):  https://hastebin.com/volesebazi.sql

**Comment by Chocobozzz** [comment]
From which commit do you try to install these modules?

**Comment by buoyantair** [comment]
@Chocobozzz 71607e4a65d3a8904bcd418ab7acbc2f34f725ff 
This is the current HEAD on my repo on branch `develop`

**Comment by buoyantair** [comment]
My local HEAD was extremely outdated. Sorry for bothering.
