### ISSUE TITLE
Unable to upload .mkv file

### ISSUE THREAD

**Issue by Granddao** [Chocobozzz/PeerTube#1563]
**What happened?**
Unable to upload MKV file, getting the message 

> This file is not supported or too large. Please, make sure it is of the following type: .mp4, .ogv, .webm, .mkv, .mov, .avi, .flv

**What do you expect to happen instead?**

Upload to succeed

**Steps to reproduce:**

1. Try uploading the .mkv file

2. Get the error message

**Additional information**
* PeerTube version or URL: v1.2.0-rc.1 / https://tube.moedesu.ga
* Browser name/version: Firefox/64.0.2
* NodeJS version: v10.15.0

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
https://pastebin.com/p4d6V4du

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/307902e2b3248073aeb677e420aafd8b5e041117

**Comment by Nutomic** [comment]
@Granddao https://docs.joinpeertube.org/lang/en/docs/install.html#git-stable
