### ISSUE TITLE
More info about notifications type

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#1565]
**What happened?**
In notification objects, there is a parameter `type` which is an integer. I didn't notice any ways to connect it to something human readable. I guessed some values:
10 -> follow
6 -> video published (owner)
1 -> video from a following has been published
2 -> New comment
**What do you expect to happen instead?**
It could be nice that the API returns a json object for notifications, like it's done for `categories`, `languages`, etc.

**Comment by Chocobozzz** [comment]
Until it is implemented, you can get the info here: https://github.com/Chocobozzz/PeerTube/blob/develop/shared/models/users/user-notification.model.ts#L1

**Comment by Poslovitch** [comment]
Couldn't get it to work since `UserNotificationType` is a `const enum`. Am I allowed to "de-const" it?

**Comment by Chocobozzz** [comment]
@Poslovitch I think we should put this info in the API documentation instead of creating an endpoint for it

**Comment by Poslovitch** [comment]
Alrighty!

**Comment by Poslovitch** [comment]
The Swagger editor shows the notification object.
![image](https://user-images.githubusercontent.com/20014332/147074889-d8a233f5-3a21-4276-958c-2f4aa0f76905.png)

But the live api documentation does not. Is that an option that must be toggled on?

**Comment by Chocobozzz** [comment]
The doc API seems to work well on my side :) 

![screen_2021-12-23-10:07:22](https://user-images.githubusercontent.com/5180488/147216556-7f5b96c6-7478-490e-a911-9a9885dfcd43.png)

**Comment by Poslovitch** [comment]
Indeed, it works. I wasn't aware I had to "unroll" the `data` attribute in the response json.
👍
