### ISSUE TITLE
Matroska (.mkv) Video Problem

### ISSUE THREAD

**Issue by Granddao** [Chocobozzz/PeerTube#1570]
**What happened?**
Unable to run compiled peertube from another machine to the current machine

**What do you expect to happen instead?**
Able to run it

**Steps to reproduce:**

1. Compile the peertube develop using another distro (debian)

2. See the problems in the current machine peertube is running 

**Additional information**
* PeerTube version or URL: peertube-develop
* NodeJS version: 11.7.0 vs 10.5.0

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
>Jan 25 14:11:40 moedesu.ga systemd[1]: Started PeerTube daemon.
Jan 25 14:11:40 moedesu.ga peertube[24467]: > peertube@1.2.0-rc.1 start /var/www/peertube/versions/moetube
Jan 25 14:11:40 moedesu.ga peertube[24467]: > node dist/server
Jan 25 14:11:41 moedesu.ga peertube[24467]: internal/modules/cjs/loader.js:718
Jan 25 14:11:41 moedesu.ga peertube[24467]:   return process.dlopen(module, path.toNamespacedPath(filename));
Jan 25 14:11:41 moedesu.ga peertube[24467]:                  ^
Jan 25 14:11:41 moedesu.ga peertube[24467]: Error: The module '/var/www/peertube/versions/moetube/node_modules/bcrypt/lib/binding/bcrypt_lib.node'
Jan 25 14:11:41 moedesu.ga peertube[24467]: was compiled against a different Node.js version using
Jan 25 14:11:41 moedesu.ga peertube[24467]: NODE_MODULE_VERSION 67. This version of Node.js requires
Jan 25 14:11:41 moedesu.ga peertube[24467]: NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
Jan 25 14:11:41 moedesu.ga peertube[24467]: the module (for instance, using `npm rebuild` or `npm install`).
Jan 25 14:11:41 moedesu.ga peertube[24467]:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
Jan 25 14:11:41 moedesu.ga peertube[24467]:     at Module.load (internal/modules/cjs/loader.js:599:32)
Jan 25 14:11:41 moedesu.ga peertube[24467]:     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
Jan 25 14:11:41 moedesu.ga peertube[24467]:     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Jan 25 14:11:41 moedesu.ga peertube[24467]:     at Module.require (internal/modules/cjs/loader.js:637:17)
Jan 25 14:11:41 moedesu.ga peertube[24467]:     at require (internal/modules/cjs/helpers.js:22:18)
Jan 25 14:11:41 moedesu.ga peertube[24467]:     at Object.<anonymous> (/var/www/peertube/versions/moetube/node_modules/bcrypt/bcrypt.js:6:16)
Jan 25 14:11:41 moedesu.ga peertube[24467]:     at Module._compile (internal/modules/cjs/loader.js:689:30)
Jan 25 14:11:41 moedesu.ga peertube[24467]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
Jan 25 14:11:41 moedesu.ga peertube[24467]:     at Module.load (internal/modules/cjs/loader.js:599:32)
Jan 25 14:11:41 moedesu.ga peertube[24467]: npm ERR! code ELIFECYCLE
Jan 25 14:11:41 moedesu.ga peertube[24467]: npm ERR! errno 1
Jan 25 14:11:41 moedesu.ga peertube[24467]: npm ERR! peertube@1.2.0-rc.1 start: `node dist/server`
Jan 25 14:11:41 moedesu.ga peertube[24467]: npm ERR! Exit status 1
Jan 25 14:11:41 moedesu.ga peertube[24467]: npm ERR!
Jan 25 14:11:41 moedesu.ga peertube[24467]: npm ERR! Failed at the peertube@1.2.0-rc.1 start script.
Jan 25 14:11:41 moedesu.ga peertube[24467]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Jan 25 14:11:41 moedesu.ga peertube[24467]: npm ERR! A complete log of this run can be found in:
Jan 25 14:11:41 moedesu.ga peertube[24467]: npm ERR!     /var/www/peertube/.npm/_logs/2019-01-25T19_11_41_284Z-debug.log
Jan 25 14:11:41 moedesu.ga systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
Jan 25 14:11:41 moedesu.ga systemd[1]: peertube.service: Unit entered failed state.
Jan 25 14:11:41 moedesu.ga systemd[1]: peertube.service: Failed with result 'exit-code'.
Jan 25 14:11:41 moedesu.ga systemd[1]: peertube.service: Service hold-off time over, scheduling restart.
Jan 25 14:11:41 moedesu.ga systemd[1]: Stopped PeerTube daemon.
Jan 25 14:11:41 moedesu.ga systemd[1]: peertube.service: Start request repeated too quickly.
Jan 25 14:11:41 moedesu.ga systemd[1]: Failed to start PeerTube daemon.
Jan 25 14:11:41 moedesu.ga systemd[1]: peertube.service: Unit entered failed state.
Jan 25 14:11:41 moedesu.ga systemd[1]: peertube.service: Failed with result 'exit-code'.

**Comment by tcitworld** [comment]
Node version isn't the same on both machines.
Try `npm rebuild bcrypt` and retry.

**Comment by Granddao** [comment]
@tcitworld thanks! was able to fix it but now the .mkv thing is still broken?
Getting this when uploaded the file? 
https://imgur.com/a/cSDPsQ1

**Comment by Chocobozzz** [comment]
@Granddao "The video is being transcoded, it may not work properly"
