### ISSUE TITLE
Report Emails not working with v1.2.0-rc.1

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1571]
I am not getting emails for new reports any more with v1.2.0-rc.1. Seems like this broke when notifications were added in Peertube? At least I didnt see any config option for this, and "forgot password" emails are still working.

**Comment by Chocobozzz** [comment]
Do you receive the web notification? Do you have the email enabled on this notification type in your settings? (should be the default)

**Comment by Chocobozzz** [comment]
Try to report a video, and check your logs to see if there is an error in the email job process. You could also check the job admin table to see if the email job was created.

**Comment by Chocobozzz** [comment]
Any news on this @Nutomic?

**Comment by Nutomic** [comment]
Sorry I dont have time to reproduce this myself. But the problem is definitely still occuring with v1.2.0

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/1ed9b8ee69ba42b2be70512eb8df239be4676674
