### ISSUE TITLE
Delete an user in the actor table.

### ISSUE THREAD

**Issue by m333w** [Chocobozzz/PeerTube#1572]
Hi all, 

I am sorry to create a new issue for that, but i whas asking on closed issue so i think the visibility is null. 
I have accidentally delete an user from the admin panel and i want to recreate it. @Chocobozzz say you have to delete the entry in the actor table. 

@Nutomic give me some help, and say to do : 

`SELECT * FROM actor WHERE preferredUsername=theuser`
`DELETE FROM actor WHERE preferredUsername=theuser`

But i am not able to recreate the user. 

Here is my comand : 

`sudo -u postgres psql`
`\c peertube_prod;`
`SELECT * FROM actor WHERE preferredUsername=anko`
`DELETE FROM actor WHERE preferredUsername=anko`

I am desperate to find a solution, i dont undestand how to do, i have read a lot from google. But i am still not able to perform this action. 

Please does anyone can help me to solve this problem? 
I am really inconvenient because the account i have delete is the account who is the admin of the instance ... I mean whe have still `root` but the user i have delete whas the `second` admin of the instance :(

Best regards.

(sorry for my bad english)

Edit: Or if more easy, is it possible to rename the user `root` with the user i have delete ?

**Comment by Chocobozzz** [comment]
See my answer: https://github.com/Chocobozzz/PeerTube/issues/1042#issuecomment-457897953

**Comment by m333w** [comment]
Good morning, 

Thank you very mutch @Chocobozzz. I will try this this afternoon when i am back at home. 

Thx again ;)

**Comment by m333w** [comment]
Work perfectly. Thank you very Mutch ;)
