### ISSUE TITLE
Zanata : several questions

### ISSUE THREAD

**Issue by 22decembre** [Chocobozzz/PeerTube#1573]
Sorry, I don't know where to ask those, so here it is. I will gladly follow any link to documentation you provide.

I am translating to danish. I have some sentences in english that would make sense to join in a single one in danish. How do I do that ?

How can I see the final result/text that I am translating (in draft mode, before publication) ? It's not finished, but I need to see if I am consistent.

There are sentences that I translate several times, for example in JoinPeerTube "Hugo" and "Master", they look to share a lot of strings. Is that ok ? Same with develop -> which one is the good one ?

Some strings refer to pre-v1, and the contribution campain. Should I translate them ?

Thanks for help.

**Comment by Chocobozzz** [comment]
Hi (and sorry for the late). I'm not a zanata expert but I'll try to answer.

> I am translating to danish. I have some sentences in english that would make sense to join in a single one in danish. How do I do that ?

I don't think you can

> How can I see the final result/text that I am translating (in draft mode, before publication) ? It's not finished, but I need to see if I am consistent.

You can use the "Needs work" selection 
![screen_2019-04-01-14:47:35](https://user-images.githubusercontent.com/5180488/55328647-23d82300-548d-11e9-9dd2-c026fbc452c2.png)

> There are sentences that I translate several times, for example in JoinPeerTube "Hugo" and "Master", they look to share a lot of strings. Is that ok ? Same with develop -> which one is the good one ?

You should not update Hugo translations. I put it in readonly mode to avoid this kind of confusion.
