### ISSUE TITLE
[API] - Role label

### ISSUE THREAD

**Issue by stom79** [Chocobozzz/PeerTube#1574]
**What happened?**
I want to introduce some moderation features with Mastalab.

**What do you expect to happen instead?**
I would like a clarification with some values. Currently with my account I can see:
```
role: 2
roleLabel: "User"

```
What are all possible values? Depending of that I will display an entry for moderation inside the app.

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/blob/develop/shared/models/users/user-role.ts

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/63d17405d0ddc0029e8f7ebb4b4ac4b4933e57ea
