### ISSUE TITLE
Ability to increase captions size limit

### ISSUE THREAD

**Issue by Granddao** [Chocobozzz/PeerTube#1575]
**What happened?**
Unable to upload captions bigger than 2MB

**What do you expect to happen instead?**
Able to modify the size limit of captions

**Additional information**
* PeerTube version or URL: develop branch
* NodeJS version: 10.15.0

**Comment by Chocobozzz** [comment]
What's the size of your caption?

**Comment by Granddao** [comment]
Never mind It was a borked .srt that failed conversion from .ass and had extra data and tags into it that increased it's size.
