### ISSUE TITLE
Miniatures?

### ISSUE THREAD

**Issue by lelibreauquotidien** [Chocobozzz/PeerTube#1578]
Bonjour.
J'aimerai savoir si on peu ajouter une miniature dans une video

Llaq.

**Comment by Chocobozzz** [comment]
Yes, in the "Advanced settings" tab: 
![screen_2019-01-28-09 43 57](https://user-images.githubusercontent.com/5180488/51823993-59bc2800-22e1-11e9-9661-848d50ad2756.png)

**Comment by lelibreauquotidien** [comment]
Ok.Thank you.

    Le lundi 28 janvier 2019 à 09:45:15 UTC+1, Chocobozzz <notifications@github.com> a écrit :  
 
 
Yes, in the "Advanced settings" tab:
