### ISSUE TITLE
[Firefox for Android] Unable to scroll in menu 

### ISSUE THREAD

**Issue by wascardev** [Chocobozzz/PeerTube#1579]
In Firefox for Android, i can't scroll in the menu to activate night mode.

**Steps to reproduce:**

1. Open Menu

2. Try to scroll down

**Additional information**
* PeerTube versions: v1.2.0-rc.1 and v1.1.0
* Device : Huawei P8 Lite 2017 on Android 8.0
* Browser name/version: Firefox 64 for Android and Chrome 71 for Android

**Comment by wascardev** [comment]
This is issue also exists on Chrome for Android

**Comment by Granddao** [comment]
On my android, its working perfectly? 
https://files.catbox.moe/lq878g.mp4
Maybe it has to do something with screensize?

**Comment by wascardev** [comment]
I think it's related.

https://files.catbox.moe/muava2.jpg

**Comment by Chocobozzz** [comment]
Thanks for the issue. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/4afcdcfad88fbc75acd7f689cca3378421c681d1
