### ISSUE TITLE
Handle video player format loading errors

### ISSUE THREAD

**Issue by tcitworld** [Chocobozzz/PeerTube#1585]
For instance, if the uploaded video is encoded with a format that can't be read by browsers (say `.mkv), the video player won't be able to load it and we should handle this case properly.

**Comment by tcitworld** [comment]
This is a follow-up from https://github.com/Chocobozzz/PeerTube/issues/1570#issuecomment-457745677

**Comment by Chocobozzz** [comment]
Hi,

I think we now have better error messages when the player is not able to read the video. Closing but don't hesitate to comment this issue if you still have weird error messages :)
