### ISSUE TITLE
Please implement Apereo's CAS for authentication

### ISSUE THREAD

**Issue by WingsLikeEagles** [Chocobozzz/PeerTube#1587]
Please implement <a href="https://www.apereo.org/projects/cas">Apereo's CAS Authentication</a>.  This will resolve several authentication requests/issues and should be easy to implement (I hope). (LDAP, database, X.509, 2-factor) (CAS, SAML, OAuth, OpenID)

NextCloud uses it and it works nicely.

**Comment by WingsLikeEagles** [comment]
This could potentially resolve issues
<a href="https://github.com/Chocobozzz/PeerTube/issues/371">#371</a>
<a href="https://github.com/Chocobozzz/PeerTube/issues/1146">#1146</a>

**Comment by unmellow** [comment]
just wanted to mention my issue sense they're related #1316

**Comment by Chocobozzz** [comment]
With https://github.com/Chocobozzz/PeerTube/pull/2721 implemented, you can now develop your own auth plugin.
