### ISSUE TITLE
No peertube activity from Hubzilla

### ISSUE THREAD

**Issue by Xanthec** [Chocobozzz/PeerTube#1589]
Hello

I'm opening this issue encountered by many people : 
https://diaspodon.fr/@bob/101471729570749326
https://osada.app/display/b64.aHR0cHM6Ly9vc2FkYS5hcHAvaXRlbS9kYjY1YjYzYy0wOGMyLTQzY2EtOTBiNS02YWZjZDIyY2M4M2Q

It's seems that we can add a peertube contact from Hubzilla, but we can't see his news posts.
Unfortunately, I don't have any logs to help debug this, but I'm available for more tests.

**Comment by Chocobozzz** [comment]
Did you open an issue on Osada side?

**Comment by elvecio** [comment]
what I ask myself: just work with mastodon, or other networks, other than mastodon, which use that protocol, can communicate with peertube?

**Comment by rigelk** [comment]
@elvecio please open an issue dedicated to your question, or ask it directly in the IRC/Matrix channel.
