### ISSUE TITLE
Add a 'PeerTube' meta tag

### ISSUE THREAD

**Issue by libertysoft3** [Chocobozzz/PeerTube#1590]
I work on a news aggregation site like Reddit, and it would be great if we could detect that a particular html page is for a PeerTube video. Adding something like this would allow us to detect PeerTube video pages:

    <meta property="og:platform" content="PeerTube" />

As a workaround, one could string match stuff on page like "We are sorry but it seems that PeerTube is not compatible with your web browser." but that's not a great solution.

**Comment by Chocobozzz** [comment]
Implemented by @buoyantair
