### ISSUE TITLE
Fill support field from peertube-import-videos script

### ISSUE THREAD

**Issue by gnouts** [Chocobozzz/PeerTube#1593]
**What happened?**
The Support button is not showing up on new videos upload (even after 5days). Support text area is properly filled.
I upload videos only from YouTube (either using cli peertube-import-videos.js or gui without touching others parameters).

**What do you expect to happen instead?**
Support button should appear automatically (or even after a short amount of time due to broadcast limitation I guess, but automatically)

**Workaround**
If I go to the uploaded video, click Update, change nothing and save : support button appears !

**Steps to reproduce:**

1. Fill Support area in your channel

2. Upload a video (I only tested with YouTube import)

3. Go to the video, Support button is missing

**Additional information**
* PeerTube version or URL: v1.1.0 (installed with Yunohost)
* Browser name/version: Firefox 64.0.2, 64bits, Linux
* NodeJS version: v8.10.0

**Comment by gnouts** [comment]
I have uBlockOrigin installed but it's disabled for my peertube domain.
I just tested with Chrome without any adblock or extension whatsoever -> same result, no Support button.

**Comment by Chocobozzz** [comment]
Hello,

We don't fill the support field in the `peertube-import-videos.js` script. But from GUI it should work :thinking:

**Comment by gnouts** [comment]
You're right. I just tested it again from GUI and it works. Don't know what was wrong (I cleared my cache recently which I don't do often ?), sorry...
Maybe rename this to "Fill support field from cli script" ?

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/1205823fece15f249e0dbad42e096cf9b81c3ba5
