### ISSUE TITLE
Unable to edit existing translations

### ISSUE THREAD

**Issue by jiru** [Chocobozzz/PeerTube#1595]
I'd like to review and fix issues with the existing French translation. I signed up on trad.framasoft.org and joined the French team. However I cannot edit anything in [the editor](https://trad.framasoft.org/webtrans/translate?dswid=-7963&iteration=develop&project=peertube&locale=fr-FR&localeId=fr-FR#view:doc;doc:angular) as it looks like the French translation is set to read-only.

**Comment by Chocobozzz** [comment]
You need to join the `fr-FR` team language (and not just the `fr`)

**Comment by jiru** [comment]
Thank you! ^^
