### ISSUE TITLE
Batch upload?

### ISSUE THREAD

**Issue by Granddao** [Chocobozzz/PeerTube#1597]
Hello,

Is there any way to upload multiple files at once? using either CLI or the web interface? 

Thanks!

**Comment by Extarys** [comment]
That would be good for people converting from Youtube to PeerTube and wish to upload a video collection.

**Comment by rigelk** [comment]
No, and it's not planned anytime soon since it requires to completely refactor the way we describe the file (title, tags, description, etc.) afterwards.

You can however script your upload via the CLI tool.

**Comment by Chocobozzz** [comment]
> Is there any way to upload multiple files at once? using either CLI or the web interface?

https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#peertube-import-videosjs ?

**Comment by Granddao** [comment]
@rigelk I think its inefficient to not be able to upload multiple videos at once, I would like that as a feature in the web interface. I don't know maybe you guys could provide a way upload multiple files and edit the metadata at the same time? Like a concurrent upload list and you either publish/cancel and edit the metadata at the same time?

@Chocobozzz Getting this error while running...

> dao@moe:~/moetube$ node dist/server/tools/peertube-upload.js --help
> internal/modules/cjs/loader.js:583
>     throw err;
>     ^
> 
> Error: Cannot find module 'commander'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.<anonymous> (/home/dao/moetube/dist/server/tools/peertube-upload.js:11:17)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>

**Comment by Chocobozzz** [comment]
@Granddao https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#remote-tools :)

**Comment by sreekanthgs** [comment]
Was trying to upload multiple videos using remote tools one by one. Having authentication errors after a few. Is there some throttling by default?

**Comment by Chocobozzz** [comment]
> Was trying to upload multiple videos using remote tools one by one. Having authentication errors after a few. Is there some throttling by default?

What is the status code sent by your server?

**Comment by capsload2** [comment]
Still no plans?

**Comment by satonotdead** [comment]
Okay I share what I did for batch uploading. I have full respect for the mantainers and contributors and I understand this app is made by devs to devs (at least for the moment).

I'm not consider myself a dev but I like to self-host almost everything, so here is my first humble contribution to this giant project.

## How to batch upload using [peertube-cli](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#remote-tools)

1. ``node --version # Should be >= 20.x`` so if you are using nvm and need to have different node versions for different apps, just type ``nvm use 20``.
2. ``sudo npm install -g @peertube/peertube-cli``
3. ``peertube-cli auth add -u 'PEERTUBE_URL' -U 'PEERTUBE_USER_EMAIL' --password 'PEERTUBE_PASSWORD'``
4. Upload them using their filenames as names as this:
```
for file in /absolute/path/*.mp4; do
  filename=$(basename "$file" .mp4)
  peertube-cli upload --video-name "$filename" --file "$file"
done
```
