### ISSUE TITLE
reset-password shows the password when it is invalid

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#1598]
**What happened?**
`NODE_ENV=production npm run reset-password -- -u root` shows the password entered when it is invalid.

**What do you expect to happen instead?**
It should not

**Steps to reproduce:**

1. Run NODE_ENV=production npm run reset-password -- -u root
2. When asked for "New password?", enter foo

The following error message is displayed:
```
{ SequelizeValidationError: Validation error: "foo" is not a valid user password.
    …
```

**Additional information**
* PeerTube version or URL: v1.1
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Thanks.

Fixed in https://github.com/Chocobozzz/PeerTube/commit/e1fa0266753446b79c76b584321fec2e722b80c2
