### ISSUE TITLE
Duplicate video published notification with scheduled video

### ISSUE THREAD

**Issue by joshmorel** [Chocobozzz/PeerTube#1601]
**What happened?**

![peertube-duplicate-publish-notification](https://user-images.githubusercontent.com/10546720/52176471-30881580-2781-11e9-9013-67a83b26476f.png)

**What do you expect to happen instead?**

Only one notification - at the scheduled publish time.

**Steps to reproduce:**

1. Upload a video
2. Select Scheduled under Privacy
3. Set published date in future
4. Receive two notifications - one at transcoding finished, one at scheduled date

**Additional information**
* PeerTube version or URL: Develop - 9fb6cfc49b38d006d1d25e09efedf15f87c44310
* Browser name/version: N/A - server side issue
* NodeJS version: 8.12.0

```
peertube_dev=> SELECT "v"."createdAt" "video_createdAt", "publishedAt", "n"."createdAt" "notification_createdAt"  FROM "video" v INNER JOIN "userNotification" n ON v.id = n."videoId"  WHERE v.id = 30;      video_createdAt       |        publishedAt         |   notification_createdAt   
----------------------------+----------------------------+----------------------------
 2019-02-03 06:42:53.476-05 | 2019-02-03 06:48:03.815-05 | 2019-02-03 06:43:38.668-05
 2019-02-03 06:42:53.476-05 | 2019-02-03 06:48:03.815-05 | 2019-02-03 06:48:03.849-05
```

**Comment by joshmorel** [comment]
Adding a conditional in the two `*Success` functions here will fix this - https://github.com/Chocobozzz/PeerTube/blob/develop/server/lib/job-queue/handlers/video-file.ts. 

My in progress feature needs to update logic here too so unless you've already started assign me and I will fix this first.

**Comment by Chocobozzz** [comment]
@joshmorel :+1:
