### ISSUE TITLE
Can't federate with others instances

### ISSUE THREAD

**Issue by ktux** [Chocobozzz/PeerTube#1602]
I try to federate my instance mplayer.demouliere.eu with other instances whose framatube.org and video.lqdn.fr.

I add these domain names in subscribe from panel administration. My requests stay waiting and are not never validated. For framatube.org, i contact the support and they said there is a bug and they advised me to open an issue.

My instance is installed on Debian 9 stable. The peertube version i'm using is 1.2.0-rc1. 
There are my logs files when i try to federate with other instance : 

/var/www/peertube/storage/logs/peertube3.log

{"message":"X.X.X.X - - [00/Feb/2019:XX:XX:XX +0000] \"GET /api/v1/server/following HTTP/1.0\" 200 2350 \"-\" \"curl/7.55.1 federation-crawler 1.0\"\n","level":"info","label":"mplayer.demouliere.eu:443","timestamp":""}

{"message":"X.X.X.X - - [00/Feb/2019:XX:XX:XX +0000] \"GET /api/v1/server/following?start=0&count=10&sort=createdAt HTTP/1.0\" 304 - \"https://mplayer.demouliere.eu/api/v1/server/following?start=0&count=10&sort=createdAt\" \"Edge\"\n","level":"info","label":"mplayer.demouliere.eu:443","timestamp":""}

/var/log/nginx/access.log

X.X.X.X - - [03/Feb/2019 +0100] "GET /nodeinfo/2.0.json HTTP/1.1"
 200 496 "-" "reqwest/0.9.9"
X.X.X.X - - [03/Feb/2019  +0100] "GET /api/v1/server/following HTT
P/1.1" 200 2347 "-" "curl/7.55.1 federation-crawler 1.0"
X.X.X.X  - - [03/Feb/2019 +0100] "GET /api/v1/server/following HTT
P/1.1" 200 2347 "-" "reqwest/0.9.9"
X.X.X.X - - [03/Feb/2019 +0100] "GET /nodeinfo/2.0.json HTTP/1.1"
 200 496 "-" "reqwest/0.9.9"
X.X.X.X  - - [03/Feb/2019 +0100] "GET /api/v1/server/following HTT
P/1.1" 200 2347 "-" "reqwest/0.9.9"

/var/log/nginx/error.log

nothing

Any ideas ?

**Comment by Chocobozzz** [comment]
What is the value of the `https` field of your production configuration file? https://github.com/Chocobozzz/PeerTube/blob/master/config/production.yaml.example#L7?

**Comment by ktux** [comment]
I'm surprising because i do not have the configuration file production.yaml. But, when i installed Peertube, i followed the installation documentation (https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#database). I'm sure i generated a good configuration file production.yaml

There is a few days, i launched the upgrade script /var/www/peertube/peertube-latest/scripts/upgrade.sh for migrate from 1.1.0 to 1.2.0-rc1. This upgrade may have reset configuration files ?

Actualy, in my config repository, i have a default.yaml file and production.yaml.example with default values.

In default.yaml

webserver:
  https: false
  hostname: 'localhost'
  port: 9000

In production.yaml.example

webserver:
  https: true
  hostname: 'example.com'
  port: 443

I'm going to try generate a new valid configuration file production.yaml and renew a subscription to other instance.

**Comment by ktux** [comment]
I generate a new production.yaml with these values : 

webserver:
  https: true
  hostname: 'mplayer.demouliere.eu'
  port: 443

I try to subscribe again to others instances and show my logs files.

In /var/www/peertube/storage/logs/peertube3.log : 

{"message":"X.X.X.X - - [04/Feb/2019 +0000] \"GET /accounts/peertube/following HTTP/1.0\" 200 972 \"http://mplayer.demouliere.eu/accounts/peertube/following\" \"-\"\n","level":"info","label":"mplayer.demouliere.eu:443","timestamp":"2019-02-04T"}
{"message":"X.X.X.X - - [04/Feb/2019 +0000] \"GET /accounts/peertube/following HTTP/1.0\" 200 972 \"http://mplayer.demouliere.eu/accounts/peertube/following\" \"-\"\n","level":"info","label":"mplayer.demouliere.eu:443","timestamp":"2019-02-04T"}
{"level":"info","message":"Updating 1 good actor follows and 0 bad actor follows scores in cache.","label":"mplayer.demouliere.eu:443","timestamp":""}
{"level":"info","message":"Updating 1 good actor follows and 0 bad actor follows scores in cache.","label":"mplayer.demouliere.eu:443","timestamp":""}
{"level":"info","message":"Updating 1 good actor follows and 0 bad actor follows scores in cache.","label":"mplayer.demouliere.eu:443","timestamp":""}

**Comment by ktux** [comment]
Today, the problem is not solved. The subscriptions are always still waiting on my administration panel and i can't federate with other instances despite the changes made.

**Comment by Chocobozzz** [comment]
Run https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#update-hostjs to update your internal URLs, that are still in HTTP.

**Comment by ktux** [comment]
I use this script and i renew the subscriptions. It work fine now. Thanks a lot.
