### ISSUE TITLE
Add a remote video

### ISSUE THREAD

**Issue by roipoussiere** [Chocobozzz/PeerTube#1605]
It could be interesting to add a specific video hosted on a remote instance (and not federate the whole instance).

To be discussed: is it a admin-related or user-related feature?

I see 2 distinct behaviors:

1. this process belongs to the instance federation, and only instance administrators chose which video to federate, as they chose which instance to federate;
2. this process belongs to the import tool, so any user could add to their channel a remote video, as they can import a new video from other platform, except that in that case, the video is note very imported but only federated. Note that the video must keep its authorship and license.

This last behavior could open the possibility to create *aggregation channels*. For example, as a cat lover, I could analyze the whole fediverse looking for cats video, and add each of them to my Cat channel, so other cat lovers could easily find many cat video (please replace the word *cat* to your favorite topic).

**Comment by Chocobozzz** [comment]
> this process belongs to the instance federation, and only instance administrators chose which video to federate, as they chose which instance to federate;

So, as an admin, instead of following another instance you add manually the video you want right? Then we could merge this issue in https://github.com/Chocobozzz/PeerTube/issues/1520: an admin could decide to "Share" a video to display it like all the other federated videos.

> This last behavior could open the possibility to create aggregation channels. For example, as a cat lover, I could analyze the whole fediverse looking for cats video, and add each of them to my Cat channel, so other cat lovers could easily find many cat video (please replace the word cat to your favorite topic).

I think you can create a playlist for this specific use case.

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/1520
