### ISSUE TITLE
Unable to disconnect for long name

### ISSUE THREAD

**Issue by webafrancois** [Chocobozzz/PeerTube#1606]
**What happened?**
If your name is too long, you can't disconnect and your avatar is cut on the screen , because the user account is center on the left bar.
**What do you expect to happen instead?**
The user account should be aligned to the left and the name should be cut with the "…"  to disconnect Peertube.
**Steps to reproduce:**

1. Log in with your account

2. Change your name with a long or very long name. Save it.

3. Try to disconnect on the left menu.
The long name is a problem : 
![capture_selection-20190205-e7c0](https://user-images.githubusercontent.com/19719849/52308496-c1d3d380-299d-11e9-93a0-123ab6877305.png)
And short name isn't : 
![capture_selection-20190205-4344](https://user-images.githubusercontent.com/19719849/52308499-c6988780-299d-11e9-8760-2e1f083434eb.png)

**Additional information**
* PeerTube version or URL:https://videos.cemea.org/
* Browser name/version: Firefox 65
* NodeJS version:
Screen in 1366x768

* Link to browser console log if useful: 
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Thanks, should be fixed in https://github.com/Chocobozzz/PeerTube/commit/d4804eead75bfaf41c3150d19e380ff4229d6226
