### ISSUE TITLE
Display the channel's name instead of the owner one below the thumbnail

### ISSUE THREAD

**Issue by TimotheeGreg** [Chocobozzz/PeerTube#1609]
* **PeerTube version or commit: PeerTube v1.1.0**
* **What is the expected behaviour?**
Channel's name should be displayed below the thumbnail

* **What do you see instead?**
Account name is displayed

More details:
I recently proposed to a Youtuber to put his videos on Peertube, he agreed and I created a channel for his videos on my account. My problem is that when the thumbnails are displayed (for exemple here: https://video.antopie.org/video-channels/8bb69260-c7f5-4cf5-9cac-4d2d300e7394/videos?sort=-publishedAt&page=1) it is my nickname ("skeptim") which is displayed below and not his channel's name ("Monsieur Phi").
Would it be possible to display the channel's name (at least when it is not the default one "Main [pseudo] channel") ?

**Comment by rigelk** [comment]
No, otherwise that would lead to easier occurences of impersionation. The only option is to display both, and there is only so much space to be used in miniatures.

**Comment by TimotheeGreg** [comment]
Ok, no problem, thanks for the fast answer !
