### ISSUE TITLE
Chunked uploads.

### ISSUE THREAD

**Issue by m333w** [Chocobozzz/PeerTube#1611]
Hi all,

I hope i am in the right place for that, if not i am realy sorry and admin can move my post to the good place.

Would it be possible to set up a "cutting" system so that videos over 100mo can be uploaded under instances using cloudflare?

I think this featur can be realy cool to bypass some restriction. 

Best regards.

**Comment by Chocobozzz** [comment]
Hi,

> I hope i am in the right place for that, if not i am realy sorry and admin can move my post to the good place.

It's the appropriate place :+1: 

> Would it be possible to set up a "cutting" system so that videos over 100mo can be uploaded under instances using cloudflare?

Honestly I don't think it's a good idea. Put peertube behind a CDN does not make a lot of sense because you re centralize something decentralized.

**Comment by m333w** [comment]
Hi @Chocobozzz, 

`Put peertube behind a CDN does not make a lot of sense because you re centralize something decentralized` so true i havent considered this point. Thank you for this remarque, otherwise i think i can upload a big video using the torrent featur. Normely its gona work, i gona try when i am back to home. 

Thank for your time and replay. 

Best regards.
