### ISSUE TITLE
Tests youtube-dl import 404

### ISSUE THREAD

**Issue by joshmorel** [Chocobozzz/PeerTube#1612]
**What happened?**  

youtube-dl related tests fail unexpectedly. 

I also tested manual import of the video resource - https://www.youtube.com/watch?v=msX3jv1XdvM OR https://youtu.be/msX3jv1XdvM

Other videos succeed so I'm wondering if this is some kind of rate limiting from YouTube related to this video since we've been using it in tests? 

Can we switch to mocking youtube-dl related instead of using external resource?  

**What do you expect to happen instead?** Import of the video succeeds.

**Steps to reproduce:**

1. Import with URL https://youtu.be/msX3jv1XdvM

2. Get error:

> Command failed: /home/USER/git/peertube/PeerTube/node_modules/youtube-dl/bin/youtube-dl -i -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best -o /home/USER/git/peertube/PeerTube/storage/tmp/72539ef7a35c395ade6d596b2c8b5eab8ae9c6a36953bef53126bb907fc99737-import.mp4 https://youtu.be/msX3jv1XdvM
> ERROR: unable to download video data: HTTP Error 404: Not Found
> 

**Additional information**
* PeerTube version or URL: develop at 552dd33
* Browser name/version: n/a
* NodeJS version: n/a - doesn't work with youtube-dl binary either 
* youtube-dl version (installed via `yarn --pure-lockfile`):

```bash
$ ~/git/peertube/PeerTube/node_modules/youtube-dl/bin/youtube-dl --version
2018.12.03
```

**Comment by Chocobozzz** [comment]
Reinstall node modules to update the youtube-dl binary, that is outdated

**Comment by joshmorel** [comment]
I get it now. Up-to-date package but stale binary ick... This solved it.
