### ISSUE TITLE
As moderator can't access to Muted servers

### ISSUE THREAD

**Issue by salvadorpla** [Chocobozzz/PeerTube#1615]
**What happened?**

As moderator can´t access to muted servers. It throws me to login form.

**What do you expect to happen instead?**
View muted servers 

**Steps to reproduce:**

1. See [video](https://peertube.cat/videos/watch/1f417921-3150-4996-a248-0e69f9c2af4c) of the failure.

2.

3.

**Additional information**
* PeerTube version or URL: 
v1.2.0, peertube.cat
* Browser name/version:
Opera / 57.0.3098.116
* NodeJS version:
v8.10.0
* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Thanks, should be fixed in https://github.com/Chocobozzz/PeerTube/commit/bf12db2497689cb3fcf648ef6fc07a699d1b20d8
