### ISSUE TITLE
Action/message upon quota exceeded

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#162]
* Browser name/version: Firefox 59.0a1 (2017-12-14) (64-bit)
* When: when uploading a video whose size makes you exceed the allotted quota.

![2017-12-19-230955_592x191_scrot](https://user-images.githubusercontent.com/6329880/34181399-ef5f3972-e509-11e7-854f-b01cc7a2c277.png)

Exceeding the user quota should at least show a button to re-upload a modified version in place. This way the information written (description, title, tags, etc.) doesn't need to be written all over again.

The green div remains shown (something my browser can't display?).

We should display user quotas if possible on the upload page/profile.

Maybe we could check *quota left* against *file size* upon selection of the file and have a warning before actually uploading anything. That would same bandwidth and time.

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/ce5496d6a31b9617aba67970f5dc135e73335234
