### ISSUE TITLE
Getting notification for mention of other user.

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1621]
My account is `@root@peertube.social`, and I just got a notification for a mention that was meant for `@root@pe.ertu.be`. I think the problem is that the user who did the mention is also on the same instance, so they correctly mentioned `@root`. But other instances assume that this refers to the local root account on their instance, not the root account on pe.ertu.be. I assume that every Peertube admin got this notification.

[link on peertube.social](https://peertube.social/videos/watch/d4f0b61e-5bdc-4130-8761-2f082a615ba5;threadId=5012)
[link on pe.ertu.be](https://pe.ertu.be/videos/watch/d4f0b61e-5bdc-4130-8761-2f082a615ba5)

![screenshot_20190211_131352](https://user-images.githubusercontent.com/1044450/52562685-9880d080-2dff-11e9-8caf-a1d282c0982b.png)

**Comment by Chocobozzz** [comment]
Thanks, should be fixed in https://github.com/Chocobozzz/PeerTube/commit/6e8cf67a6f7c20f9e43dd7bfc111f6b494e11c50
