### ISSUE TITLE
Twitter thumbnail preview is not the one specified for the video

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#1622]
**What happened?**
In this tweet: https://twitter.com/Tranxen1/status/1094651599526481920

The thumbnail being shown is not the one being specified in the video options:

![image](https://user-images.githubusercontent.com/371705/52564177-c2d48d00-2e03-11e9-9b1d-451991487141.png)

Is it a bug or something configurable?

**Additional information**
* PeerTube version or URL: v1.2.0
* Browser name/version: Firefox 66 (beta)
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
I think the image was updated and twitter keeps the old image in its cache

**Comment by fflorent** [comment]
So I can try posting a new post and see if the image is different or not. Would it help investigating?

**Comment by Chocobozzz** [comment]
Only if it is a different video yes

**Comment by fflorent** [comment]
After discussing with the user, you are right. I close the issue unless a future video has the issue without that explanation.

Thanks!

Florent
