### ISSUE TITLE
Email sent from the admin contact form should use the host email domain, not the user's

### ISSUE THREAD

**Issue by bnjbvr** [Chocobozzz/PeerTube#1627]
Steps to reproduce
===

- Go to the contact form of any instance, on `/about/instance`.
- Enter "somebody@example.com" in "your email", with any text.
- Submit.

Observed
===

The email actually sent by Peertube has the address-from field set to the email entered by the user, as if the user has sent the email themselves (so the email seems to come from "somebody@example.com"). This is quite bad, because there's a lot of chances that the domain name used in the user's email address doesn't match the Peertube's outgoing SMTP domain. In fact, this will classify all these emails as potential spam, and will decrease the reputation of the Peertube server to all spam checkers, resulting in the server landing in blacklists (if it's repeatedly done, that is, if the form is used several times).

I think instead that:

- the email should be sent from the address set in the `PEERTUBE_SMTP_FROM` env variable (? I'm using Docker, so this env variable is a thing, but it might not be in other contexts).
- the reply-to field in the email could be set to the user address, so an admin clicking reply on their web interface would directly answer to the user.

(I think this is severe enough that it would justify a minor release just for this :/)

**Comment by bnjbvr** [comment]
Down the rabbit hole: this line should be changed https://github.com/Chocobozzz/PeerTube/blob/d3e56c0c4b307c99e83fbafb7f2c5884cbc20055/server/lib/emailer.ts#L364

Then, I don't know if passing a `replyTo` will just work, or if something else is needed.

**Comment by Chocobozzz** [comment]
Thanks @bnjbvr, fixed in https://github.com/Chocobozzz/PeerTube/commit/7a338188f3ce6c3aa53054afaa936aa807d65fd8

Released in https://github.com/Chocobozzz/PeerTube/releases/tag/v1.2.1

**Comment by bnjbvr** [comment]
Thanks!
