### ISSUE TITLE
Suggestion: Publish .torrent / magnet links 

### ISSUE THREAD

**Issue by wioxjk** [Chocobozzz/PeerTube#1629]
Hi,

Please excuse me if this question/suggestion is unfitting or just stupid.
But is there a way for people to help instances by "reseeding" the torrents?

It would be great to help out instances without actually watching the videos or setting up a peertube instance.

Would this be a good idea?

**Comment by rigelk** [comment]
Hi @wioxjk

You can already get the metainfo file or the magnet in the download modal accessible in the watch page, or using the API, or using the syndication feed.

Bear in mind that sharing with a torrent client that doesn't support WebTorrent will have a very limited effect helping seed the video.
