### ISSUE TITLE
youtube-dl default originallyPublishedAt is variable to local time

### ISSUE THREAD

**Issue by joshmorel** [Chocobozzz/PeerTube#1636]
**What happened?** Following test fails

```
  Test video imports
    ✓ Should import videos on server 1 (2384ms)
    ✓ Should list the videos to import in my videos on server 1
    ✓ Should list the videos to import in my imports on server 1
    1) Should have the video listed on the two instances

  3 passing (48s)
  1 failing

  1) Test video imports
       Should have the video listed on the two instances:

      AssertionError: expected '2019-01-14T05:00:00.000Z' to equal '2019-01-13T23:00:00.000Z'
      + expected - actual

      -2019-01-14T05:00:00.000Z
      +2019-01-13T23:00:00.000Z
```

But succeeds when I change my localtime to UTC+1 (Central European Time) 

The reason this happens is because `setHours` used in `server/helpers/youtube-dl.ts/buildoriginallyPublishedAt` uses localtime.

**What do you expect to happen instead?**

default `originallyPublishedAt` to be consistent across timezones. I would recommend UTC so the test video would be 2019-01-14T00:00:00.000Z consistent with what is displayed on YouTube regardless of localtime (https://www.youtube.com/watch?v=msX3jv1XdvM). 

I can put in PR in a if the recommended solution makes sense

**Steps to reproduce:**

1.  Set local time to Canada/Eastern (e.g. on Linux `sudo ln -sf /usr/share/zoneinfo/Canada/Eastern /etc/localtime`)

2. Run tests in file `tests/api/video/video-imports.ts`

**Additional information**
* PeerTube version or URL: Develop at 7f40ce53243be994a3cf093e07eb1d460f696b10
* Browser name/version: n/a
* NodeJS version: 8.15.0

**Comment by Chocobozzz** [comment]
Hi,

I think I fixed it in https://github.com/Chocobozzz/PeerTube/commit/17036be5bc2f14dc4e66053087e39887599df4de

**Comment by joshmorel** [comment]
Oh wow - that was recent. I didn't expect it so didn't re-pull. 

It does fix the tests in UTC+ and UTC- time zones.

The underlying cause is still there so this _might_ cause confusion or bugs later but maybe not? For example in Moscow time on YouTube it is Feb 14, 2019 but the `originallyPublishedAt` default date ends up as `2019-01-13T21:00:00.000Z`.

I think if you just change `setHours(0,0,0,0)` to `setUTCHours(0,0,0,0)` in `buildOriginallyPublishedAt`  you can avoid any potential other issues. But I'll leave you to decide to change it or not.

**Comment by Chocobozzz** [comment]
I think youtube-dl returns the date corresponding to the client timezone. But I'm not really sure :thinking: Let's close this issue and if we notice a date bug in imports we'll reopen it.
