### ISSUE TITLE
Unable to upload a video from another node app

### ISSUE THREAD

**Issue by charjac** [Chocobozzz/PeerTube#1638]
Hi, i am writing a small typescript peertube client
I am not able to upload a video using standard node library.
The server respond with 500 Internal server error.
I also tried with postman and  and it fail the same way.

```js
import FormData from 'form-data';
import fs from 'fs';
import fetch from 'node-fetch';
import path from 'path';

const formData = new FormData();
formData.append(
  'videofile',
  fs.readFileSync(path.join(__dirname, 'foo.mp4'), { encoding: 'binary' }),
);

formData.append('name', 'foo.mp4');
formData.append('channelId', 2674);

fetch('https://peertube.fr/api/v1/videos/upload', {
  method: 'POST',
  headers: {
    Authorization: 'Bearer mytoken',
  },
  body: formData,
})
  .then(res => res.json())
  .then(console.log)
  .catch(console.error);

```
same thing if i pass a stream to form-data.

I also tried it in a browser with a file input, and get the same 500 error.

if i try to change my user's avatar using the same approach it works just fine.

**Additional information**
* PeerTube version or URL: https://peertube.fr v1.2.1
* Browser name/version: Firefox 66.0b8
* NodeJS version: v11

**Comment by Chocobozzz** [comment]
I'm sorry but I can't help without server logs. Could you try to run peertube on localhost?

**Comment by charjac** [comment]
Sure, i will do this. I thought about it but was lazy :D
Thx for the answer
