### ISSUE TITLE
Redundancy of video (not instance)

### ISSUE THREAD

**Issue by weber-s** [Chocobozzz/PeerTube#1639]
Hello,  
As a peertube admin, I would like to mirror only specifics video, not whole instance. It may be for several purpose: 

- technical: disk space, bandwidth,
- political: disagreement with other video of this instance,

For now, it is only possible to make the redundancy of whole instance, or having finer rules such as "min_views", "trending", etc. But being able to copy/paste the magnet of a video we want to mirror would be nice!

My whish list:

- selecting specific video for mirroring
- list all video we are mirroring
- a link to "stop mirroring" the video in the list above

Thanks for peertube!

**Comment by grondinm** [comment]
I was going to submit a issue/request but i think i'll tag it on to this as it's small and fits with this. On the Following list page it would be nice to see the size of videos from each instance that have been mirrored.

Also maybe another part but also a question. The limit set is it by instance or total for all instances that we provide redundancy for? If total it would be nice to set by instance.

Thank you for peertube!!

**Comment by Chocobozzz** [comment]
> The limit set is it by instance or total for all instances that we provide redundancy for? If total it would be nice to set by instance.

The limit is total for all instances. I think you can create separate issues for the limit per instance and for the display of the redundancy size per instance

**Comment by grondinm** [comment]
Wow thanks for the quick reply. I shall submit new issues for both.

Thanks again.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/b764380ac23f4e9d4677d08acdc3474c2931a16d

See https://github.com/Chocobozzz/PeerTube/pull/2427
