### ISSUE TITLE
Edit videos of another users

### ISSUE THREAD

**Issue by skid9000** [Chocobozzz/PeerTube#164]
Hi,

Could it be possible to add a option to (as a Administator) flag a video as NSFW ?
You can do it for your own videos on your pod but you can't do it for the others local users.

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/6221f311de0eb8f2a9e7e4a77b8cb0ecbde6dfcd
