### ISSUE TITLE
PeerTube scammed bounty  participants ? 

### ISSUE THREAD

**Issue by Inkognito222** [Chocobozzz/PeerTube#1647]
Admins, now I can make post on BTT that PeerTube scammed bounty 
participants ?

**Comment by Nutomic** [comment]
What bounty are you talking about?

**Comment by rhaamo** [comment]
I think it is making references to some crypto thing launched called "PeertubeCrypto", who also use "peertubeproject" as org name on github, and everything looks super scammy:
- Coin announce https://bitcointalk.org/index.php?topic=5077228 (https://web.archive.org/web/20190214191021/https://bitcointalk.org/index.php?topic=5077228 for images currently broken)
- Bounty announce https://bitcointalk.org/index.php?topic=5079350.0
- The Github of the coin https://github.com/peertubeproject

**Comment by rigelk** [comment]
@Inkognito222 the PeerTube project has nothing to do with the "PeerTubeCrypto" project/announce/bounty/coin that you (probably, judging by the reference to BTT/bitcointalk) mention.

@rhaamo thanks for the links!

**Comment by Nutomic** [comment]
Lmao these people gave money to a project that has nothing but a copy of the Bitcoin source code, and some marketing.
