### ISSUE TITLE
Make RSS Feeds links <a href.. links

### ISSUE THREAD

**Issue by mattcoxonline** [Chocobozzz/PeerTube#1648]
**What happened?**
Every single instance of the RSS feed links I encounter seem to be constructed in some weird way, which means I click it (in Firefox) and it opens a dialog asking me to save the file.

I right-click it and you don't get the standard context menu for a link - with options such as "Copy link to clipboard" - because the way it's constructed is not a link.

This means I am currently unable to subscribe to any RSS feeds.

**Additional information**
* PeerTube version or URL: https://peertube.fr/video-channels/chrisweredigital@share.tube/videos
* Browser name/version: Firefox, latest stable, Mac OS

**Comment by rigelk** [comment]
@mattcoxonline what version of Firefox do you have?

**Comment by mattcoxonline** [comment]
Ah, now I am on a Windows PC - using Firefox - and I see how it's meant to behave:

<img src="https://user-images.githubusercontent.com/673542/53042296-3e7aad80-3486-11e9-99f7-c80050736070.png" alt="A screenshot of the RSS dropdown on PeerTube" width="250" />

On Firefox Mac, this didn't happen. On the mac, I didn't see the dropdown. It just brought up a dialog box like this:

<img src="https://user-images.githubusercontent.com/673542/53042609-f14b0b80-3486-11e9-8d12-b09a9984c2e6.png" alt="A screenshot of the RSS dropdown on PeerTube" width="250" />

As you can see, I can replicate this on Firefox for Windows - but this time via this menu:

<img src="https://user-images.githubusercontent.com/673542/53042502-b47f1480-3486-11e9-9ba3-b105e9cf2141.png" alt="A screenshot of the RSS dropdown on PeerTube" width="250" />

I guess both the RSS icon and the option in the Subscribe dropdown should react in the same way / give the same options?

**Comment by buoyantair** [comment]
@mattcoxonline  The "Subscribe via RSS" clearly states to subscribe _via_ RSS. Instead I think it would be better to have a subscribe button which pulls up a dropdown list.

**Comment by rigelk** [comment]
@buoyantair that's already a dropdown in a dropdown. UI-wise, it's not great.

**Comment by buoyantair** [comment]
@rigelk Right... How about just a popup that allows you to select the subscription medium? We can use the popup to replace the other dropdown too.

**Comment by frankstrater** [comment]
The problem here (and also on other web applications) is the routing with using file extensions for format selection. See examples below:
```
https://peertube.cpy.re/feeds/videos.{format}

https://peertube.cpy.re/feeds/videos.xml
https://peertube.cpy.re/feeds/videos.atom
https://peertube.cpy.re/feeds/videos.json
```
The browser sees this as links to files and will result to a popup to download it as a file, which is not how you want to subscribe as a user. You want to copy this a link which you can use in your RSS reader.

In my opinion it would be better to make the links as below with query parameters:

```
https://peertube.cpy.re/feeds/videos?format={format}

https://peertube.cpy.re/feeds/videos?format=xml
https://peertube.cpy.re/feeds/videos?format=atom
https://peertube.cpy.re/feeds/videos?format=json
```

**Comment by Chocobozzz** [comment]
With https://github.com/Chocobozzz/PeerTube/pull/2145, we replaced the buttons with a link so you can easily copy it. See https://github.com/Chocobozzz/PeerTube/issues/2216 for download XML issue.
