### ISSUE TITLE
Dont resume music videos

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1649]
The resume functionality in Peertube is generally really useful. However, it absolutely sucks for music videos. 

For example, I might watch a music video (or just listen to a song), but not finish it. Then some time later, I come back and watch the same video again. Now Peertube decides to start in the middle of the song, and I have to manually go to the beginning to listen to the full song. 

One solution might be to disable resume for videos under 5 minutes (or a similar value). Alternatively, Alternatively, it could be an option for viewers or uploaders to disable it, but that seems to complicated.

**Comment by Chocobozzz** [comment]
I created a hook so you can do this easily in https://github.com/Chocobozzz/PeerTube/commit/3d9a63d3d824e753e95292b5e1343e1ebf9eaf71

`filter:internal.video-watch.player.build-options.result`

See [hello-world plugin](https://framagit.org/framasoft/peertube/official-plugins/blob/master/peertube-plugin-hello-world/client/video-watch-client-plugin.js#L39) to have an example
