### ISSUE TITLE
Problem during migration

### ISSUE THREAD

**Issue by Dryusdan** [Chocobozzz/PeerTube#165]
Hello 
When I update PeerTube by update Dockerfile, the migration have a ploblem : 

```
> peertube@0.0.1 start /PeerTube
> node dist/server

debug: [peertube.drycat.fr:443] Executing (default): SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type LIKE '%TABLE' AND table_name != 'spatial_ref_sys';
debug: [peertube.drycat.fr:443] Executing (default): SELECT "migrationVersion" FROM "Applications"
debug: [peertube.drycat.fr:443] Executing (default): SELECT "migrationVersion" FROM "application"
info: [peertube.drycat.fr:443] Begin migrations.
info: [peertube.drycat.fr:443] Executing 0140-actor-url.js migration script.
debug: [peertube.drycat.fr:443] Executing (9f9530b6-f263-4544-abac-5a121b154a8a): START TRANSACTION;
debug: [peertube.drycat.fr:443] Executing (9f9530b6-f263-4544-abac-5a121b154a8a): SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
debug: [peertube.drycat.fr:443] Executing (default): UPDATE video SET url = replace("url", 'peertube.drycat.fr:443', 'peertube.drycat.fr')
debug: [peertube.drycat.fr:443] Executing (default): UPDATE actor SET url = replace("url", 'peertube.drycat.fr:443', 'peertube.drycat.fr'), "inboxUrl" = replace("inboxUrl", 'peertube.drycat.fr:443', 'peertube.drycat.fr'), "outboxUrl" = replace("outboxUrl", 'peertube.drycat.fr:443', 'peertube.drycat.fr'),
      "sharedInboxUrl" = replace("sharedInboxUrl", 'peertube.drycat.fr:443', 'peertube.drycat.fr'), "followersUrl" = replace("followersUrl", 'peertube.drycat.fr:443', 'peertube.drycat.fr'),
      "followingUrl" = replace("followingUrl", 'peertube.drycat.fr:443', 'peertube.drycat.fr')
debug: [peertube.drycat.fr:443] Executing (default): UPDATE server SET host = replace(host, ':443', '')
debug: [peertube.drycat.fr:443] Executing (9f9530b6-f263-4544-abac-5a121b154a8a): ROLLBACK;
error: [peertube.drycat.fr:443] Cannot execute migration 0140. SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/PeerTube/node_modules/sequelize/lib/dialects/postgres/query.js:318:18)
    at query.catch.err (/PeerTube/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
    at tryCatcher (/PeerTube/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/PeerTube/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/PeerTube/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/PeerTube/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/PeerTube/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/PeerTube/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/PeerTube/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/PeerTube/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

Have you got this problem ?

**Comment by Chocobozzz** [comment]
Now we the `:443` in the host is implicit. It seems that you have in your table `remotehost.com:443` **and** `remotehost.com` which is weird. I suggest you to remove `remotehost.com`.

**Comment by Dryusdan** [comment]
Perfect, thank :)

**Comment by papaeng** [comment]
Hello, i have same error 
{"level":"debug","message":"Executing (default): SELECT \"migrationVersion\" FROM \"Applications\"","timestamp":"2018-01-11T22:59:53.274Z"}
{"level":"debug","message":"Executing (default): SELECT \"migrationVersion\" FROM \"application\"","timestamp":"2018-01-11T22:59:53.303Z"}
{"level":"info","message":"Begin migrations.","timestamp":"2018-01-11T22:59:53.310Z"}
{"level":"info","message":"Executing 0140-actor-url.js migration script.","timestamp":"2018-01-11T22:59:53.320Z"}
{"level":"debug","message":"Executing (ec656447-1e6f-4f77-aab7-3ee2661eec01): START TRANSACTION;","timestamp":"2018-01-11T22:59:53.338Z"}
{"level":"debug","message":"Executing (ec656447-1e6f-4f77-aab7-3ee2661eec01): SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;","timestamp":"2018-01-11T22:59:53.359Z"}
{"level":"debug","message":"Executing (default): UPDATE video SET url = replace(\"url\", 'video.migennes.net:443', 'video.migennes.net')","timestamp":"2018-01-11T22:59:53.476Z"}
{"level":"debug","message":"Executing (default): UPDATE actor SET url = replace(\"url\", 'video.migennes.net:443', 'video.migennes.net'), \"inboxUrl\" = replace(\"inboxUrl\", 'video.migennes.net:443', 'video.migennes.net'), \"outboxUrl\" = replace(\"outboxUrl\", 'video.migennes.net:443', 'video.migennes.net'),\n      \"sharedInboxUrl\" = replace(\"sharedInboxUrl\", 'video.migennes.net:443', 'video.migennes.net'), \"followersUrl\" = replace(\"followersUrl\", 'video.migennes.net:443', 'video.migennes.net'),\n      \"followingUrl\" = replace(\"followingUrl\", 'video.migennes.net:443', 'video.migennes.net')","timestamp":"2018-01-11T22:59:53.513Z"}
{"level":"debug","message":"Executing (default): UPDATE server SET host = replace(host, ':443', '')","timestamp":"2018-01-11T22:59:53.535Z"}
{"level":"debug","message":"Executing (ec656447-1e6f-4f77-aab7-3ee2661eec01): ROLLBACK;","timestamp":"2018-01-11T22:59:53.553Z"}
{"message":"Cannot execute migration 0140.","stack":"SequelizeUniqueConstraintError: Validation error\n    at Query.formatError (/home/peertube/PeerTube/node_modules/sequelize/lib/dialects/postgres/query.js:318:18)\n    at query.catch.err (/home/peertube/PeerTube/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)\n    at tryCatcher (/home/peertube/PeerTube/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/peertube/PeerTube/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/home/peertube/PeerTube/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/home/peertube/PeerTube/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/home/peertube/PeerTube/node_modules/bluebird/js/release/promise.js:689:18)\n    at Async._drainQueue (/home/peertube/PeerTube/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/home/peertube/PeerTube/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/home/peertube/PeerTube/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:789:20)\n    at tryOnImmediate (timers.js:751:5)\n    at processImmediate [as _immediateCallback] (timers.js:722:5)","name":"SequelizeUniqueConstraintError","errors":[{"message":"host must be unique","type":"unique violation","path":"host","value":"peertube.cpy.re","origin":"DB","instance":null,"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}],"fields":{"host":"peertube.cpy.re"},"parent":{"name":"error","length":188,"severity":"ERROR","code":"23505","detail":"Key (host)=(peertube.cpy.re) already exists.","schema":"public","table":"server","constraint":"pods_host","file":"nbtinsert.c","line":"432","routine":"_bt_check_unique","sql":"UPDATE server SET host = replace(host, ':443', '')"},"original":{"name":"error","length":188,"severity":"ERROR","code":"23505","detail":"Key (host)=(peertube.cpy.re) already exists.","schema":"public","table":"server","constraint":"pods_host","file":"nbtinsert.c","line":"432","routine":"_bt_check_unique","sql":"UPDATE server SET host = replace(host, ':443', '')"},"sql":"UPDATE server SET host = replace(host, ':443', '')","level":"error","timestamp":"2018-01-11T22:59:53.557Z"}
{"level":"debug","message":"Executing (default): SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type LIKE '%TABLE' AND table_name != 'spatial_ref_sys';","timestamp":"2018-01-11T23:00:13.292Z"}

you suggest you to remove remotehost.com but what table ?

Je suis un peu perdu là ?

**Comment by Chocobozzz** [comment]
This should work: `DELETE FROM "server" WHERE host = 'remotehost.com'`

**Comment by papaeng** [comment]
Thanks, it's ok for me
