### ISSUE TITLE
Miniature hover appearance improvements

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#1650]
Seen on https://www.wixtube.net/, that makes it clear what kind of interaction the user can expect when clicking the miniature.

![wixtube-vignette](https://user-images.githubusercontent.com/6329880/53026676-a075eb80-3463-11e9-8e46-26066742e81f.gif)

What do you think?

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/1aabcae7e36bb113c2887bd7180dad2916ecaaf2
