### ISSUE TITLE
[API] Add import endpoint

### ISSUE THREAD

**Issue by Booteille** [Chocobozzz/PeerTube#1651]
Hi!

Would be great if we could have an endpoint to import videos from http and torrent with the API!

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/28c8e63e55cad24b024fc1d05aa1cfc0257434e5

https://docs.joinpeertube.org/api.html#tag/Video/paths/~1videos~1imports/post

**Comment by Booteille** [comment]
Thanks!
