### ISSUE TITLE
The media playback was aborted

### ISSUE THREAD

**Issue by Booteille** [Chocobozzz/PeerTube#1652]
**What happened?**
I tried to play the video https://peertube.social/videos/watch/4c9d6a7f-ccff-4e56-8998-158996e247a6 and got the following error:

`The media playback was aborted due to a corruption problem or because the media used features your browser did not support.`

**What do you expect to happen instead?**
I expect the video to play normally.

**Steps to reproduce:**

1. Open https://peertube.social/videos/watch/4c9d6a7f-ccff-4e56-8998-158996e247a6

2. Play the video.

**Additional information**
* PeerTube version or URL: PeerTube v1.2.1 - peertube.social
* Browser name/version: Firefox Developper Edition v66.0b8.
* NodeJS version:

* Link to browser console log if useful: https://framabin.org/p/?acb87a369e6cbee4#qy2HCEhMQjixySC9dVrL/gMoabJMNPfqDFonJEbhYWs=
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
The video does not exist any more and I forgot to download it. Closing this issue.
