### ISSUE TITLE
Improve display of votes

### ISSUE THREAD

**Issue by Booteille** [Chocobozzz/PeerTube#1653]
Actually, votes are hard to see :

![](https://screenshotscdn.firefoxusercontent.com/images/840979c5-7b03-45e5-b9ff-f78db3ac9dea.png)

There is just a tiny bar, glued to the bottom line.

Can we make it more visible? Just enough that we can easily pass our mouse hover and check the number of votes?

**Additional information**
* PeerTube version or URL: 1.2.1

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/0d3a9be9f13c2642cb6cf26fdebc5edf5217bbbc
