### ISSUE TITLE
Provide audiostreams with bitrates for music & speech 

### ISSUE THREAD

**Issue by gloschtla** [Chocobozzz/PeerTube#1655]
If the video uploader puts the video into the category SPEECH or MUSIC, then the audiostream of the video should be automatically extracted and hosted as maximum 32kbps audio stream for speech, or 96-192kbps audiostream for music. This enables the users to reduce the data transfer to the necessary minimum, because they can choose to not load the video, but only the audiostream. Furthermore podcasts can be listened without WWW costs, when throttled mobile data is for free. This idea is inspired by NewPipe's download function.
 This would allow PeerTube to be interesting for webradio channels, and also for users with slow internet access.

**Comment by ealgase** [comment]
I think it would also be interesting to support audio only uploads that have higher resolution audio (up to FLAC).

**Comment by Chocobozzz** [comment]
We now support videos with audio only and audio upload.
