### ISSUE TITLE
Feature Request: Manual backups for automated redirects

### ISSUE THREAD

**Issue by gloschtla** [Chocobozzz/PeerTube#1656]
Is it possible to watch youtube through peertube clients? 
This would let grassroots vloggers choose to use most popular video platform as primary host and PeerTube for backups. So videos of grassroot movements can be discovered to the masses via video suggestions on most popular video plattforms. And, in the case that the primary channel is deleted, then the peertube client automatically redirects the users to the decentralized backup channel. This might be helpful for the transition process, to let Peertube become the most popular video plattform.

**Comment by Chocobozzz** [comment]
Hello,

No sorry it is not possible and not planned. With PeerTube, our main goal is to decentralize video hosting.

But feel free to create another client that fetch videos from YouTube, Vimeo, PeerTube etc and display them in the same interface.
