### ISSUE TITLE
Add ActivityPub implementation report

### ISSUE THREAD

**Issue by cwebber** [Chocobozzz/PeerTube#166]
Hello!  It would be super nice to list PeerTube on the [ActivityPub implementations report page](https://activitypub.rocks/implementation-report/)!  You can [generate such a report](https://test.activitypub.rocks/) and submit it!

**Comment by Chocobozzz** [comment]
:+1:

**Comment by Chocobozzz** [comment]
https://github.com/w3c/activitypub/issues/287
