### ISSUE TITLE
Latest European directive on copyright

### ISSUE THREAD

**Issue by maxdrash** [Chocobozzz/PeerTube#1694]
The latest European Parliament text on copyright requires that any content be filtered and rejected before publication.
The host becomes responsible if content is published and penalties are provided.
Can you give us some details about the technical possibilities that Peertube can offer us regarding pre-publication approval and possible ways of knowing if a content is copyrighted ?

Thank you.

**Comment by ealgase** [comment]
Peertube instances aren't corporate so they aren't subject to Article 13.

**Comment by StefanCristian** [comment]
@maxdrash if peertube would make money out of centralized uploaded works, which are under their control legally, then yes

Otherwise, nope. Article 13 is for businesses that run public upload-based platforms

**Comment by maxdrash** [comment]
Ok thank you for your answer.

**Comment by Chocobozzz** [comment]
Hi,

This directive is very confusing but some instances could be subject to Article 13/17. 

> Can you give us some details about the technical possibilities that Peertube can offer us regarding pre-publication approval and possible ways of knowing if a content is copyrighted?

With https://github.com/Chocobozzz/PeerTube/pull/1637 you'll be able to automatically blacklist new videos. Then it's up to you to decide if a video can be unblacklisted or not. You can also use an automatic tool to do that (using PeerTube REST API). But we won't implement/add an automatic filter in PeerTube core.

**Comment by StefanCristian** [comment]
@Chocobozzz I apologize to interfere once more, but I'm most sure that you will not affected, unless your site makes profit out of uploaded works, and ads
If you hold any servers that users can upload anything that's publicly available, then yes, you might be affected

Other than that, the directive is very clear, there are no interpretations or doubts based on it
The few conditions that require you to be affected are also very clear:
-> Small businesses will be affected only after 3 years of activity
-> Users can upload stuff on your servers, and your servers uploaded stuff must be available to the public
-> Open code based businesses are not affected

These are the conditions

**Comment by ealgase** [comment]
>Open code based businesses are not affected

Seems like we're definitely not affected, then.
