### ISSUE TITLE
Details in video page

### ISSUE THREAD

**Issue by 22decembre** [Chocobozzz/PeerTube#1695]
More details should be provided in the video page :

- size of the video file
- format of video ? (webm, mp4... ? ) of audio ?
- Date of upload. This might be more accurate than "X months ago". Both data can be provided.

**Comment by alcalyn** [comment]
> - size of the video file

I guess we should display the original video file size ? (i.e not the size of generated 480p or 240p)

**Comment by realityfabric** [comment]
It would be nice to have a setting to toggle between relative and absolute dates. Are the size / format relevant when you're not downloading the video (instead of streaming)?

**Comment by Nutomic** [comment]
Size might be important for users with a data cap.

**Comment by Chocobozzz** [comment]
Implemented by @rigelk in https://github.com/Chocobozzz/PeerTube/pull/2411
