### ISSUE TITLE
How can I get seeding activity of each user?

### ISSUE THREAD

**Issue by dkitdev** [Chocobozzz/PeerTube#1696]
I want to display how much megabyte each User is seeding at the moment.

I am not sure if peertube already supports this feature.

Would you please tell me about this problem?

**Comment by Zig-03** [comment]
May I ask why would you need this data, how is it gonna be useful to you?

**Comment by buoyantair** [comment]
@wmqsoft But given that the user only seeds for the amount of time the video plays (or until tab is closed i guess?) which anywhere between 10-60mins for the majority of the videos...
