### ISSUE TITLE
Feed content is truncated

### ISSUE THREAD

**Issue by tcitworld** [Chocobozzz/PeerTube#1698]
Using ATOM/RSS, the `content` field for an entry is truncated just like the `description` field. Same goes for `html_content` and `summary` in the case of JSON.

Version 1.2

Rather strange, given:
https://github.com/Chocobozzz/PeerTube/blob/cef534ed53e4518fe0acf581bfe880788d42fc36/server/controllers/feeds.ts#L128-L129

**Comment by Chocobozzz** [comment]
We don't federate the entire videos description, so for a remote video we may not have the full description.
