### ISSUE TITLE
Refreshing browser changes page

### ISSUE THREAD

**Issue by AutomCoding** [Chocobozzz/PeerTube#1699]
Sometimes a new page is displayed when refreshing the browser window, as described below.

**Steps to reproduce**
1. Open a new browser window or tab.
2. Enter a PeerTube address like ```peertube.domain.exaple``` or ```https://peertube.domain.exaple/```.
3. The instance's trending page should now be displayed.
4. Refresh the browser window or enter the same address in the address bar.
5. Note that the address bar shows the same address, but now the local videos page is displayed.

**Version information**
I tested a large selection of instances and they behave like described above on the following PeerTube versions:
* 1.0.1
* 1.2.1

They do, however, behave normally on the following versions:
* 1.0.0-rc.2
* 1.1.0
* 1.2.0

Browser: Firefox 65.0.1 (64-bit)

**Comment by Chocobozzz** [comment]
Isn't the same issue than https://github.com/Chocobozzz/PeerTube/issues/504?

**Comment by AutomCoding** [comment]
Yes, it most likely is! I must have missed it.
