### ISSUE TITLE
Upload audio file

### ISSUE THREAD

**Issue by Aluriak** [Chocobozzz/PeerTube#170]
Considering that:

- some videos are mostly sound with a finite number of images (sometimes, none or just 1)
- that user may want to only listen to a video, not watch the image
- that transmitting only the sound may be bandwith saving

What about allowing user to disable/enable image, while keeping alive the sound ?
What about auto-disabling/enabling of image based on tab focus ?

**Comment by Chocobozzz** [comment]
I'm sorry I don't understand. What do you mean by "disable a video"? I guess the auto disabling video on tab unfocus is the web browser job.

**Comment by Aluriak** [comment]
Problem was about the difference of meaning between video and video. Now fixed using video for video as a image + sound media, and image for video as a image alone media.

**Comment by Chocobozzz** [comment]
I think it would be overkill. Video codecs are very good in compression if the image is static. And I guess web browser optimize things when the player is on another tab.

If you want to discuss this further, please comme on IRC (#peertube on freenode).

**Comment by rigelk** [comment]
Apparently there seems to be some interest [on framacolibri] around using PeerTube for music - not changing the interface too much but rather providing a way to upload music formats directly.

[on framacolibri]: https://framacolibri.org/t/peertube-de-la-video-et-du-son/2639/

> si tu as un [format] son[ore], il est beaucoup plus simple de le téléverser directement que chercher […] un logiciel qui mette tous ça dans le même conteneur [video].

> encoder brièvement une vidéo avec une image fixe ou bien garder juste l’audio et représenter les ondes de manière fixe aussi sur les instances qui implémenteraient l’audio

> l’urgence reste malgré tout le dev des fonctionnalités “ordinaires” de peertube : chaîne, playlists

Since [YouTube is cracking on music listening](https://news.ycombinator.com/item?id=16642675), we can expect this practice to move with its userbase.

**Comment by steckerhalter** [comment]
I wanted to suggest the addition of plain audio, so I'm glad this is already here. Someone suggested that it could be extended to all kinds of media formats, like images, documents, slide shows etc. What do you think about that?

**Comment by rigelk** [comment]
@steckerhalter I don't think we will extend to all media formats. Plain audio is already a stretch.

**Comment by steckerhalter** [comment]
@rigelk hmm, in what way is it a stretch if I may ask? A decentralized network for media, why limit it to just video and not go beyond the youtube model to do what youtube would never imagine? Of course audio is like the most obvious extension, then people could ditch soundcloud etc. From that proceed to  images (people can ditch flickr etc.), then documents (start with pdfs maybe, ditch scribd), then slides (ditch slideshare.net) and on and on...

**Comment by rigelk** [comment]
@steckerhalter a reason could be that the interface is centered around videos. Adding other media types will force an interface change to some extent. You won't be ditching soundcloud anytime soon even with audio support in PeerTube, since the interface will only be adapted to videos. We don't have the notion of albums or interprets to group musics together, nor do we have a player bar staying through your browsing for instance.

I'm not saying this isn't possible. Someone might very well come with a design proposal that fits all use cases, or we might have multiple interface layouts that the user can switch to depending on the media type he's looking for. I'm actually really thinking this is possible, but not anytime soon, and certainly not with our resources.

**Comment by steckerhalter** [comment]
> You won't be ditching soundcloud anytime soon even with audio support in PeerTube, since the interface will only be adapted to videos. We don't have the notion of albums or interprets to group musics together, nor do we have a player bar staying through your browsing for instance.

Yes, but essential would be that someone can post music. I don't think the rest is that important.

I'm not saying it should happen soon or even that you should do it. It's just something to consider.

**Comment by steckerhalter** [comment]
for sound support I think the interface could be left almost as is if the image would be a spectral analysis like mediagoblin does it: https://mediagoblin.org/images/tour/audio_screenshot_cropped.png

**Comment by rigelk** [comment]
> I'm not saying it should happen soon or even that you should do it. It's just something to consider.

Definitely.

I had never seen the spectral view of mediagobelin. Looks nice. Either that or putting a predefined image. Any other visualisation ideas?

**Comment by Aluriak** [comment]
There is some other ways. [Here](http://nbviewer.jupyter.org/github/bmcfee/librosa/blob/master/examples/LibROSA%20demo.ipynb) is a usage example for a python lib that is an accidental roadmap around these methods.

**Comment by steckerhalter** [comment]
@rigelk I guess it could work taking an iterative approach:

first just accept audio and put an audio placeholder image (something of this kind: https://openclipart.org/detail/168846/audio-speaker)

later add more possible options:

- waveform: generate the waveform and put it as image, later evolve the interface and make the waveform interactive like https://wavesurfer-js.org/
- image: add option to choose custom image
- waveform + image combined: image is on the left ("cover"), waveform on the right

**Comment by Insoleet** [comment]
Ideally, an audio-only player could be cool for dumbphones. On this phone, if you want to listen to a conference, you have to remain with the screen turned on even if you don't watch it but only listen. If you turn off the screen, the video pauses.

NewPipe an "audio backend mode" for youtube videos, I think it would be great if it was native to Peertube.

**Comment by EmilJacobs** [comment]
I'll add my 2 cents and would love podcast support. I'm making a podcast myself and something like PeerTube looks very interesting.While I have to create a pseudovideo for publication on YouTube and could recycle that video... it would be much more natural to expect an audio-only medium to be audio-only.

**Comment by zacharystenger** [comment]
I'm interested in implementing or helping implement this functionality. I've already got a quick hack that works with mp3 files, tested on Firefox and Chrome.

**Comment by Chocobozzz** [comment]
Hi @zacharystenger,

I prefer to merge the preview file with the audio file uploaded by the user, so we still play videos on the front end. And it will be simpler :)

**Comment by zacharystenger** [comment]
Hey @Chocobozzz, 

I will look into the preview file code.  If anyone wanted to see how I got it to work by treating the audio file like a video file, check out [this branch](https://github.com/zacharystenger/PeerTube/tree/audio-upload). As far as I can tell it works just like a video would, there's is just a blank screen instead of images. 

Disclaimer: this code was quickly hacked together just to see if this would work.

**Comment by xTpx** [comment]
+1

**Comment by Simon-L** [comment]
I would also be interested in audio support, I looked at the source code last year.
I'm particularly curious to see how well the torrent-based system would hold up to music : smaller files, arranged in groups (album) based on metadata, even though it would make Peertube very similar to Funkwhale (https://funkwhale.audio/) feature-wise.
That is probably way more changes than what you are initially planning, maybe it could be made into a plugin? (also on the roadmap!)

As for visualization, Soundcloud waveform display is probably what most users are used to.
Also, Moodbar from Amarok/Clementine: https://en.wikipedia.org/wiki/Moodbar

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/536598cfafab1c5e24e881db1c528489f804fb6b & https://github.com/Chocobozzz/PeerTube/commit/7b992a86b107fc2917b993127df8e95a66ae94db

It has to be explicitly enabled by the admin. The user can then upload the audio file and peertube will merge the audio with the preview file to create the video.

**Comment by bristow** [comment]
> Implemented in [536598c](https://github.com/Chocobozzz/PeerTube/commit/536598cfafab1c5e24e881db1c528489f804fb6b) & [7b992a8](https://github.com/Chocobozzz/PeerTube/commit/7b992a86b107fc2917b993127df8e95a66ae94db)
> 
> It has to be explicitly enabled by the admin. The user can then upload the audio file and peertube will merge the audio with the preview file to create the video.

Hi @Chocobozzz 

I don't see this button in admin interface. Can we upload audio file in PT v1.3.1 ?

Thanks for your hard job !

**Comment by Nutomic** [comment]
@bristow This seems to be the relevant option: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L200

**Comment by bristow** [comment]
hum, i don't have this option :

https://framapic.org/4cJb4tUYNqcl/ZXGfvDB8PdE7.png

**Comment by Nutomic** [comment]
It seems to be only in the config file (see my link above), not in the web interface.

**Comment by Chocobozzz** [comment]
> I don't see this button in admin interface. Can we upload audio file in PT v1.3.1?

No it will be in v1.4. We don't release additional features in patch versions, only bug fixes.
The option will be in the config file and the web interface.

**Comment by bristow** [comment]
Nice :+1:

**Comment by Dennis-Volk** [comment]
So Peertube is converting audio to video basically. The question is, how is the bitrate of the audio treated when transcoding. If a video is, say, 144, is the audio quality reduced? thank you.
