### ISSUE TITLE
Apple TV app

### ISSUE THREAD

**Issue by exrector** [Chocobozzz/PeerTube#1700]
Do you have a plan to create an app for apple tv?

**What happened?**

**What do you expect to happen instead?**

**Steps to reproduce:**

1.

2.

3.

**Additional information**
* PeerTube version or URL:
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Hello,

No sorry but PeerTube is built around a REST API so anybody can create an application for Apple TV.
