### ISSUE TITLE
Notification e-mail doesn't work

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#1701]
**What happened?**

I receive no notification e-mail.

**What do you expect to happen instead?**

Receive e-mail on account creation, new followers, ...

**Steps to reproduce:**

1. Activate e-mail notification for each kind of events

2. Wait for a new follower, or a new account creation

3. I don't receive notification e-mail. There is no error log.

**Additional information**

The contact form and account verification e-mail are working. So the problem is not my instance's configuration.
I checked my spam folder, there is nothing.

* PeerTube version or URL: https://www.yiny.org (v1.2.1)
* Browser name/version: Firefox
* NodeJS version: 8.15.0 and 8.15.1

* server log:

`{"message":"90.63.0.0 - - [01/Mar/2019:16:24:17 +0000] \"POST /api/v1/users/me/subscriptions HTTP/1.0\" 204 - \"https://www.yiny.org/search?search=john%20liv\" \"Firefox\"\n","level":"info","label":"www.yiny.org:443","timestamp":"2019-03-01T16:24:17.756Z"}
{"level":"info","message":"Processing ActivityPub follow in job 19.","label":"www.yiny.org:443","timestamp":"2019-03-01T16:24:17.759Z"}
{"level":"info","message":"Notifying user johnlivingston of new follower: YinY.org.","label":"www.yiny.org:443","timestamp":"2019-03-01T16:24:17.846Z"}
`

**Comment by JohnXLivingston** [comment]
PS: web notifications are ok.

**Comment by Nutomic** [comment]
Might be the same issue as #1571

**Comment by Chocobozzz** [comment]
What is the output of this SQL query?

```
select "userNotificationSetting".* from "userNotificationSetting" inner join "user" ON "user".id = "userNotificationSetting"."userId" where "user".username = 'johnlivingston'
```

**Comment by JohnXLivingston** [comment]
`id | newVideoFromSubscription | newCommentOnMyVideo | videoAbuseAsModerator | blacklistOnMyVideo | myVideoPublished | myVideoImportFinished | newUserRegistration | newFollow | commentMention | userId |          createdAt           |         updatedAt         
 22 |                        3 |                   3 |                     3 |                  3 |                3 |                     3 |                   3 |         3 |              3 |      6 | 2019-02-07 11:51:07.56784+00 | 2019-02-26 16:14:19.57+00
`

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1ed9b8ee69ba42b2be70512eb8df239be4676674
