### ISSUE TITLE
Unable to post a comment through Mastodon if the video has been private before being published

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#1702]
### What happened

Hygiène Mentale posted a video privately first before publishing it to everyone. The video in question is this one: https://skeptikon.fr/videos/watch/7871daaa-cba2-4db7-8582-a15b884aeb15

But when I look at his account through Mastodon, I cannot see his last video:
![image](https://user-images.githubusercontent.com/371705/53665707-7f37ab00-3c6c-11e9-8742-85bdb33b2068.png)

Also I cannot post a comment using my Mastodon account.

### Steps to reproduce
**Prerequisites**: Have a Mastodon account following the Peertube instance and account.

1. Upload a video on Peertube and select "Only people with the private link can see this video"
2. When the transcoding is finished, change the privacy to "anyone can see  this video"
   → On Mastodon, you see no post of it
3. Try to comment by interacting remotely with Mastodon
    → You have this error:

![image](https://user-images.githubusercontent.com/371705/53665843-dd648e00-3c6c-11e9-809a-370529355a00.png)

**Comment by Chocobozzz** [comment]
I think it's the Mastodon cache that remembers the 403 status page. It's not really a peertube bug, and I guess that after one day or two the cache will be invalidated. 

Closing this issue, but don't hesitate to comment if you think it's a bug.
