### ISSUE TITLE
Magnet link never starts download

### ISSUE THREAD

**Issue by strypey** [Chocobozzz/PeerTube#1703]
**What happened?**

I tried to download a video from a PT instance using a magent link, but the download never started. It never found any peers, nor downloaded any metadata.

**What do you expect to happen instead?**

I expected the metadata to be downloaded from the PT instance, and a BitTorrent download to begin, just as it does it I download the .torrent file.

**Steps to reproduce:**

1. Click 'Download' to bring up the 'Download video' modal, choose 'Torrent (magnet llnk)', and click the orange 'Download' button.

2. Look at BitTorrent client so see that although it has responded to the magnet link and tried to start a download, no peers are being found, and no metadata being downloaded, even after half an hour.

**Additional information**
* PeerTube version or URL: https://vidcommons.org/videos/watch/8464f77b-31f4-4d02-a473-afa288f64506
* Browser name/version: ABrowser 64.0 (32-bit)
* BitTorrent client name/version: Transmission: 2.84
* OS name/version: Trisquel 8 (32-bit)

I have tried this numerous times over the last couple of months, on a variety of PT sites, always with the same outcome.

**Comment by buoyantair** [comment]
@strypey Hi, I tried the same thing over https://instant.io/ . It seems to work for me and the torrent client was able to download metadata & start the download. Can you verify if it works this way or not?

**Comment by Serkan-devel** [comment]
I think you seem to confuse webtorrent with regular bittorrnent. It needs a webtorrent client to download from those magnet links.

**Comment by strypey** [comment]
Yes @buoyantair , the magnet link from Vidcommons.org worked on instant.io.

@Serkan-devel 

>  It needs a webtorrent client to download from those magnet links.

Are you sure? Nothing in the UI indicates that, nor anything in the discussion at #639 about introducing the magnet links to the UI. The .torrent file available from the same modal works as normal on Transmission, it's just the magnet link that doesn't.

**Comment by Chocobozzz** [comment]
Transmission does not support `xs` parameter in magnet uris: https://github.com/transmission/transmission/issues/317

**Comment by Zig-03** [comment]
I've tested this with 

- Deluge 1.3.13 and it doesn't work.
- qbittorrent 3.3.7 and it's stuck at "retrieving metadata..."
- ktorrent 4.14.26 doesn't work
- Tixati 2.58 stuck at "Fetching meta-info..."

**Comment by ealgase** [comment]
Works for me in aria2c.

**Comment by Serkan-devel** [comment]
Again, magnet links from webtorrents don't work on regular bittorrent clients.

You can list tests with more bittorrent clients with the same result.

Unless it has been routed through a hybrid client which supports both webtorrent and bittorrent

**Comment by rigelk** [comment]
@Serkan-devel it has nothing to do with webtorrent, but everything to do with how clients parse the magnet links fed to them.

**Comment by ealgase** [comment]
@Serkan-devel aria2c does not support WebTorrent (https://github.com/aria2/aria2/issues/595) but the download works.  It just doesn't download or seed WebTorrent peers.

**Comment by ivan386** [comment]
> Transmission does not support `xs` parameter in magnet uris: [transmission/transmission#317](https://github.com/transmission/transmission/issues/317)

@Chocobozzz But they and others bittorrent clients support 'ws'. 

https://github.com/transmission/transmission/blob/a440981571220731c3e91683743464c47174a267/libtransmission/magnet.c#L196

**Comment by Chocobozzz** [comment]
@Jorropo No, if transmissions get the torrent file (with the `xs` parameter) it will be able to download the video via webseed and other TCP/UDP peers because peertube tracker supports HTTP too.

**Comment by Serkan-devel** [comment]
@ealgase maybe you were able to download through that specific magnet link because someone probably had a hybrid-client which can communicate with bittorrent and webtorrent

https://webtorrent.io/desktop/
![image](https://user-images.githubusercontent.com/16866642/53826800-d645c480-3f79-11e9-898b-eff98d454d1e.png)

And can't find any dependency which hints traditional bittorrent support.

**Comment by Serkan-devel** [comment]
Also to note:

> ## Can I seed videos with my classic BitTorrent client (Transmission, rTorrent...)?
> Yes you can, but you won't be able to send data to users that watch the video in their web browser. The reason is they connects to peers through WebRTC whereas your BitTorrent client uses classic TCP/UDP. To check if your BitTorrent client supports WebTorrent you can see this issue: https://github.com/webtorrent/webtorrent/issues/369

src: https://github.com/Chocobozzz/PeerTube/blob/master/FAQ.md#can-i-seed-videos-with-my-classic-bittorrent-client-transmission-rtorrent

**Comment by ealgase** [comment]
@Serkan-devel no one was seeding with bittorrent or webtorrent, it was downloaded directly from the server (as a webseed).

**Comment by Jorropo** [comment]
@Chocobozzz, you are right, U didn't thinked about that but, using transmission to download over http is overkill.

**Comment by Chocobozzz** [comment]
Since most of bittorrent clients are not able to parse our magnet URI, maybe we should remove it from the download modal (and just keep DDL/torrent file).

**Comment by strypey** [comment]
From a user POV that it would be better to have no magnet link, than to
have a magnet link that  often doesn't work as expected. So removing it
may be the best short term solution, but I hope you would continue
experimenting with it in a dev branch, and communicating with the BT
client devs about how to get it to work reliably.

Ideally, if and when you can do that, the best place to put magnet links
would be directly under the video embed on the video page. What I
suggest is to add a button to the settings menus that allow admins to
toggle downloads off for their instance, and allow users to toggle
downloads off for their channel. You'd need to set this up so that it
also either a) prevented their videos being mirrored on other instance,
or b) prevented downloads from the video page of mirrored copies.

Doing it that way means that video hosts worried about unauthorized
copying can prevent it by completely disallowing downloads. Those who
want to allow downloads can do so and all the download buttons can be
right there on the video page, rather than hidden away in a pop-up.

**Comment by ealgase** [comment]
> What I suggest is to add a button to the settings menus that allow admins to toggle downloads off for their instance, and allow users to toggle downloads off for their channel. 

I really suggest against this.  Unless Peertube employs obfuscation, it will be easy to rip the streams, and just annoy legitimate users who want to watch the videos in a player other than the web client.

**Comment by strypey** [comment]
@ealgase as a legitimate user, it annoys me that the download options for PT videos are obscured and inconvenient to use. This is OT for this issue but since it keeps coming up, I have opened an issue for it (#1797).

**Comment by ealgase** [comment]
Yeah, download buttons should be easier to access.  However, I don't think having an admin option to remove them would be a good choice.

**Comment by Chocobozzz** [comment]
Closed by https://github.com/Chocobozzz/PeerTube/commit/7c51916a61d53526c594a2115f1c0e6051a895d9
