### ISSUE TITLE
Can't upload a video >4Go

### ISSUE THREAD

**Issue by sachaz** [Chocobozzz/PeerTube#1704]
When I'm uploading a video >4Go I got a sort of timeout, the video upload finishing whithout any message.

The issue comes from my nginx conf for the peertube site (/etc/nginx/sites-available/peertube):

    # Hard limit, PeerTube does not support videos > 8GB
    client_max_body_size 8G;
    proxy_connect_timeout       600;
    proxy_send_timeout          600;
    proxy_read_timeout          600;
    send_timeout                600;
    limit_rate 800k;

 \>4Go video at 800K/s doesn't fit in 600seconds

**Comment by Chocobozzz** [comment]
Please paste error logs from nginx, and client console logs.

We don't have a limit rate in our nginx template for the upload endpoint: https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube#L93

**Comment by sachaz** [comment]
Yes it was due to our webserver configuration, sorry for the schcouiiiiiittt noise.
