### ISSUE TITLE
Audio desyncronized in web version

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#1705]
**What happened?**
There is a delay between video and audio, but only in web version (not in the app Thorium).

**What do you expect to happen instead?**
A video plying normally.
**Steps to reproduce:**

1.Go to the website with a desktop/mobile browser.

2. Play any video, no matter from wich instance.

3.

**Additional information**
* PeerTube version or URL:
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by rigelk** [comment]
I do not experience this on my mobile. Please fill in additional information as demanded by the issue template.
