### ISSUE TITLE
updating from v1.2.0-rc1 to v1.2.0 or v1.2.1 results in blank (white) screen in browser

### ISSUE THREAD

**Issue by stefan240** [Chocobozzz/PeerTube#1706]
**What happened?**
After upgrading my peertube-instance from v1.2.0-rc1 to either v1.2.0 or v1.2.1 the browser just shows a blank white screen.
**What do you expect to happen instead?**
The peertube instance to start normally with version 1.2.0 or 1.2.1
**Steps to reproduce:**

1. update peertube instance according to guide in the production guide. 

2. start browser and surf to mhtube.de

**Additional information**
* PeerTube version or URL: mhtube.de (version 1.2.1)
* Browser name/version: Firefox 65
* NodeJS version: 11.10.0

* Link to browser console log if useful: https://pastebin.com/yJMWjQcH
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): https://pastebin.com/8AH1x3hS

I tested this on my both my maschines I have running at home. one running ubuntu (Main Server) and the other one running arch (Test and production masschine) The install of peertube on the arch-maschine was fresh there was no webserver on this maschine before. Installing and running the version v1.2.0-rc1 (the one running on the ubuntu-server) is working as expected. 
I had a friend test acess from win 10 and chrome too with the same result. 

If can provide more info to you please let me know.

**Comment by Chocobozzz** [comment]
If you use https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#auto-minor-versions-only, you need to restart peertube after the upgrade

**Comment by stefan240** [comment]
I didnt use the automatic upgrade. I did use the manual method found here: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#manually

Also that wouldn't really explain why it isnt working on a fresh install on my arch system either. On my Ubuntu-Server restarting the Service didn't help. Still the same thing sadly. Maybe my configuration is somehow borked I don't really know, but since v1.2.0-rc1 is working it is odd.

**Comment by Chocobozzz** [comment]
Please give me an URL of a blank page instance (new one or upgrade mhtube.de) so I can investigate

**Comment by stefan240** [comment]
Right now I rolled it back to v1.20-rc1 so that it will accesible. I will upgrade it once I get home on the ubuntu-server. 

I will let you know when all is set up today in the afternoon. If you need anything else, feel free to ask. Thank you for the quick response.

**Comment by stefan240** [comment]
> Please give me an URL of a blank page instance (new one or upgrade mhtube.de) so I can investigate
@Chocobozzz alright all done the ubuntu-server now is running v1.2.1 again issue still persists. You can find the blank page under mhtube.de

**Comment by Chocobozzz** [comment]
https://mhtube.de/client/fr_FR/styles.791b9e6485b9c522d99b.css -> 403

Please pastebin your nginx configuration, and your peertube directory tree

**Comment by stefan240** [comment]
I will do so once I get home again this afternoon. One quick question on the directory tree. My instance is a bit split like follows:
Peertube itself is located in /var/www/peertube
The videos themselves are stored on the other harddrives mounted at /var/data (the videos are stored in the respective subdirectory peertube/storage/...) 

Do you need a directory-tree for both of them or is /var/www/peertube sufficent?

**Comment by stefan240** [comment]
@Chocobozzz here are the requested files. 
nginx-conf: https://pastebin.com/4mpaHquB
[peertube-tree.txt](https://github.com/Chocobozzz/PeerTube/files/2932299/peertube-tree.txt)

I had to attach the tree to this response since it was to big for pastebin and hastebin somehow is bugging out for me. Hope thats okay.

**Comment by Chocobozzz** [comment]
@stefan240 please check peertube-latest file owners/rights. You can also read the nginx error log to know why it answers 403

**Comment by stefan240** [comment]
@Chocobozzz 
Checking Permissions did the trick here. basically the /var/www/peertube/versions/peertube-v1.2.1 folder had the wrong permissions set. they were set as rwxr----- (740) instead of rwxr-x--- (750). I dont know why though really. I wil test again and report back.

**Comment by stefan240** [comment]
@Chocobozzz 
Sorry for the bit spammy replies. The "fix" for seems a bit odd. I am testing this with v1.1.0. 
unzipping the .zip reveales that the permissions seem fine (750) as should be. In this state it isnt running at all. error as above. 
chaning permssions with chmod -R 755 peertube-v1.1.0 makes it work fine as far as visibility of the instance is concerned and all seems work fine. Maybe my config somehow odd, I guess since I am not that experienced with administrating a server or setting it up really.

**Comment by Nutomic** [comment]
@stefan240 maybe you are extracting the zip with the wrong user? Files should be owned by the peertube user normally.

**Comment by stefan240** [comment]
@Nutomic I quickly checked the owner and group. All the files inside /var/www/peertube are owned by the user peertube and the group peertube so seems right to me. But you may be right that something might be odd in that regard. My "fix" in the post above just modifies the rwx values not the owner. but 755 adds rx permissions to everyone basically. So something has to be off, I just dont know what really.
