### ISSUE TITLE
How to add a channel to subscriptions list ?

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#1707]
Hello,

I don't understand how to add channels to my subscriptions list, i don't see anywhere any option that does a such thing. Did i searched wrong or is the functionality not yet implemented ?

**Comment by buoyantair** [comment]
@stemy2 Did you mean `how to subscribe to a channel?` ? You just open a channel's page and subscribe to it, alternatively you can find the channel subscription button right below it's videos.

As of now I don't think there's any kind of input to enter a channel to subscribe to, you can search for the channel though and then subscribe.

**Comment by stemy2** [comment]
Ok, i see the button now, but for some reason, it wasn't the case right before i opened this issue. Thanks anyway.
