### ISSUE TITLE
mastodon + peerube 

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [Chocobozzz/PeerTube#1711]
i want to change my "mastodon" bio but not know how, i already changed my bio in peertube but it no want to change in mastodon

photos:
https://media.mstdn.io/mstdn-media/media_attachments/files/005/495/877/original/996487e28a2777d1.png
https://media.mstdn.io/mstdn-media/media_attachments/files/005/495/878/original/d0d00107a59748a1.png

EDIT: it took too long like more than month & i already talked with mods, thats why im here

**Comment by Chocobozzz** [comment]
Hi,

It's not  a peertube issue. But I think you just have to wait some days, mastodon will refresh the account info.

**Comment by EsmailELBoBDev2** [comment]
> It's not a peertube issue

mastodon then ?
