### ISSUE TITLE
no 'subscribe' button when uBlock Origin is active

### ISSUE THREAD

**Issue by Fipaddict** [Chocobozzz/PeerTube#1714]
Still "uBlock Origin" add-on on firefox, the button to subscribe or unsuscribe to a channel is not visible
When I deactovate ublock and reload peertube page, the subscribe button is enable.

- instance : peertube.fr
- firefox : 65.0.1
  - add on : uBlock Origin release 1.18.4
  - ...
- Linux Mint : 18.3

**Comment by Booteille** [comment]
Which account do you want to subscribe to?

**Comment by Fipaddict** [comment]
The problem was found with all channels I tested

**Comment by Zig-03** [comment]
I just tested, I don't have this issue. Maybe it's one of your custom filters?

**Comment by bristow** [comment]
I don't have this issue too, on my instance and on peertube.fr

**Comment by Fipaddict** [comment]
I don't know if it's helping you but I finded which uBlocks specifics filters ("esthetic filter" ) were causing the problem :
- Fanboy's Social Blocking List
- Fanboy's Annoyance List
Apparently for the same reason : The usage of "subscribe-button"

Therefore, I'm not really the problem is on peertube side or on filter side.

**Comment by Quix0r** [comment]
You can find out which rule causes this by opening the logger and click the reload button. Then you can see which request is blocked and which rule has caused this. Then you can report your findings to Fanboy and let him/her/them fix it on their side. Meanwhile you can use a whitelisting approach by clicking on the right (not left, that will whitelist all requests) green button.

**Comment by Quix0r** [comment]
Anyway, if you trust that peertube instance, you can use the left green button to fully whitelist it.

**Comment by Quix0r** [comment]
@Fipaddict so your thumb-up means you understood what I mean? good, thank you. :)
