### ISSUE TITLE
after file changes, not reload or refresh server and frontend automatically.

### ISSUE THREAD

**Issue by dreamhero418** [Chocobozzz/PeerTube#1715]
when I change client code for customizing UI, it doesn't reload or refresh page automatically.
I saw this http://prntscr.com/mw4wdz in contributing.md,
but never worked.

**Comment by Chocobozzz** [comment]
Please do a fresh clone from develop, install modules using yarn and run `npm run dev`.

If you update [this line](https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/sass/application.scss#L42) for example, do you notice changes? If not, please paste the content of your web browser console + network tab.
