### ISSUE TITLE
subs spdy for http2 before deprecation

### ISSUE THREAD

**Issue by ReK2Fernandez** [Chocobozzz/PeerTube#172]
Whas thinking in doing a pull request but unless I find more stuff I just add it here
issue:
```
root@video:/etc/nginx/sites-enabled# nginx -t
nginx: [warn] invalid parameter "spdy": ngx_http_spdy_module was superseded by ngx_http_v2_module in /etc/nginx/sites-enabled/peertube:9

```

solution:
you need to change the nginx config to:
...
listen 443 ssl http2; # or http2
...

from
...
listen 443 ssl spdy; # or http2
...

you guys have it as an option but soon will be deprecated... do not wait :)

**Comment by Chocobozzz** [comment]
PR welcome :)

**Comment by ReK2Fernandez** [comment]
@Chocobozzz haha ok maybe when I finish the install/setup etc :)

**Comment by ReK2Fernandez** [comment]
BTW @Chocobozzz where do I download Peeror? I want to copy all my current videos from youtube to my peertube setup automatically, so I dont have to do it manually one by one.. also whats the default user/pass to log in? I just literally start it the app for the first time

**Comment by ReK2Fernandez** [comment]
@Chocobozzz fuck I just saw this:
```
The output from starting peertube for the first time will include the credentials for your instance's administrative account, and this information will not be repeated. Make note of it.
```
but I missed this because I was fixing a bcrypt issue.. where is the log/pass now? can I change it?

**Comment by ReK2Fernandez** [comment]
ok I think I may have found it let me test.

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/pull/175
