### ISSUE TITLE
Auto Deleting a video after it expires

### ISSUE THREAD

**Issue by maxdrash** [Chocobozzz/PeerTube#1723]
Users request.
To have the possibility to set an expiration on a video through either user interface and the API.

Example: auto deleting after hours, days or date.

Thank you for this project :+1: 

**Additional information**
* PeerTube version or URL: v1.2.1

**Comment by Chocobozzz** [comment]
Thanks for this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1289
