### ISSUE TITLE
Question: reset IP/domain

### ISSUE THREAD

**Issue by stone212** [Chocobozzz/PeerTube#1725]
I read this too late: `PeerTube does not support webserver host change. Keep in mind your domain name is definitive after your first PeerTube start.`

**What happened?**

I started the service before editing config/production.yaml

**What do you expect to happen instead?**

I expected not to be so stupid

How can I re-set?  Or is this now a permanent addition to the node tables and I need a new IP address?

**Comment by Nutomic** [comment]
Did you already upload videos or create user accounts? If not, you can delete the postgres database and peertube files to start from a fresh installation.

**Comment by Chocobozzz** [comment]
You can use https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#update-hostjs too

**Comment by stone212** [comment]
@Chocobuzz

When I log in as `peertube` user I run and get this:

```
~$ NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run update-host
npm ERR! path /var/www/peertube/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/var/www/peertube/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

If I log on as sudo user and run the full command (`sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run update-host`) I get the same error.  Is `update-host.js` current?

**Comment by stone212** [comment]
@Nutomic Thank you, I did this and it is working.  Recommend you comment out `example.com` etc. in the default production.yaml file.

@Chocobozzz The utility you sent me to didn't work for me (message above).  Do you want me to open a new Issue report?

**Comment by rigelk** [comment]
@stone212 yes it is current. However the commands needs to be run in the same directory than your PeerTube directory, otherwise it won't find the package.json.

**Comment by Chocobozzz** [comment]
@stone212 "These scripts should be run on the server, in peertube-latest directory."
