### ISSUE TITLE
Channel/User actor naming problem

### ISSUE THREAD

**Issue by drequivalent** [Chocobozzz/PeerTube#1726]
Hello,

There's a problem in correlation in naming of channels and users on Peertube server.

For example, the user l13tl3@tube.linc.systems creates a "games" channel and it gets an address of games@tube.linc.systems.

Only one user can post into games@tube.linc.systems channel, so it belongs solely to them.

And then nobody can create a "games" channel on this server.

So, a user can create a lot of channels, and hog up all the good names on the server. This is potentially catostrophic.

I think we have to separate users and channels somehow, preferably so that one can clearly see what the user channel belongs to.

I'd propose prefixing the channel name with the username (l13tl3_games@tube.linc.systems)

**Comment by wiz** [comment]
BTW, email has a nice notation for related accounts: `username+something@hostname.tld`.

**Comment by AutomCoding** [comment]
A viable alternative is to use a randomized string. That could allow the creator to change the name of the channel without contributing to link rot.

**Comment by drequivalent** [comment]
> A viable alternative is to use a randomized string. That could allow the creator to change the name of the channel without contributing to link rot.

a so-so solution to be honest. I'd rather have a tractrable name, so other people could easily remember and follow.

**Comment by Chocobozzz** [comment]
A user cannot create an unlimited amount of channels in peertube 2.1. Having channels without a suffix/prefix does not seem to be an issue right now (even if this is not a bad idea).
