### ISSUE TITLE
Tell the user what tags are enabled in video description

### ISSUE THREAD

**Issue by ReK2Fernandez** [Chocobozzz/PeerTube#173]
Hello, Im testing my install, and trying to use markdown for the video explanation because I saw on front page that it was done, but is not working... trying to create a list with * or - even + with no success

**Comment by Chocobozzz** [comment]
Only links are enabled in description markdown to not break the watch page design. Maybe we could add lists too.

Either way, we need to add a small text to tell the user which tags are enabled.

**Comment by ReK2Fernandez** [comment]
@Chocobozzz yeah def list will be nice.. because as of now it all wraps into long lines and looks very ugly.. :)  thanks.

**Comment by ReK2Fernandez** [comment]
@Chocobozzz how hard is to implement this? do you guys use a markdown library and enable pieces of it?

**Comment by Chocobozzz** [comment]
It's not, we use a module: https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/videos/shared/markdown.service.ts#L10

We would just enable list and add a small link to explain what tags are enabled. The link could be a popover or a popup for example. It's a good first issue.

**Comment by ReK2Fernandez** [comment]
@Chocobozzz cool, but we need enought tags to be able to make long explanations come out neat like in youtube.. as of now all videos I upload with more than 4-5 lines with links and lists or topics etc  are terrible.. :/  example check the video desc: https://video.hispagatos.org/videos/watch/47d2abea-9818-4c6d-9de6-ec3a60b74f7b  is all super uggly..

**Comment by Chocobozzz** [comment]
It's markdown so just add an empty line to go back to line:

```
line1

line2
```

**Comment by LecygneNoir** [comment]
In fact you could use an empty line to create a new paragraph, or 2 spaces at the end of the line to create a new line :-)

```
line1
line2
```

versus

```
line 1

line2
```

As shown in this description for example (please notice the 2 paragraph with new line inside each)
https://peertube.drycat.fr/videos/watch/439d83c9-8a9d-43ee-bb25-151cb527bbba

I guess you can "trick" the list using some " -" at the beginning of the line, and terminating the line with 2 spaces : 

```
 - item1[space][space]
 - item2[space][space]
```

**Comment by ReK2Fernandez** [comment]
@Chocobozzz @LecygneNoir THANK YOU this did the trick and the list trick works like a charm <3

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/8a8e02a43e346b9b777c8192a7c5cbdccb928b11 https://github.com/Chocobozzz/PeerTube/commit/621d99f53f47a11919ec243e05273ecf5907b444
