### ISSUE TITLE
Notification - Add a button to mark as read inside the popup

### ISSUE THREAD

**Issue by Booteille** [Chocobozzz/PeerTube#1730]
I think this could be a good thing to have the ability to mark notifications as read directly from the popup. Actually, we have to go on `/my-account/notifications` and then click on the dedicated button.

**Comment by Nutomic** [comment]
You can do that by clicking on the background (outside of the text). But I agree that this is not good UX, a button would be better. Or mark it as read automatically when the link is clicked or when the video is opened.

**Comment by Booteille** [comment]
It's already marked as read automatically by clicking on the link. But yeah. There are some UX improvements to do here.

**Comment by Chocobozzz** [comment]
Do you have suggestions regarding this button?

**Comment by Booteille** [comment]
I am not an expert in UI, I would rather let anyone more familiar with it express his/her opinion.

Personnaly I would prefer to automatically mark notifications as read once the pop-up is opened. But if it's not something wantef, just a simple eye button close to the settings button would do the job.

**Comment by therahedwig** [comment]
For me, it was not at all obvious that the notifications could be clicked in the first place. Maybe either a 'hover over' color change or a small icon somewhere that invites the user to press it so that people can discover the clicking behaviour.

**Comment by rigelk** [comment]
@therahedwig to adress the UI understandability issue your raise, I am considering changing the notification popup trigger from the user's profile picture to a dedicated button in the top right-hand corner of the interface, in between the search bar and the upload button. In the meantime, a temporary solution could be to have a bell icon display on hover over the profile picture.
