### ISSUE TITLE
DEV:  Localization for Forks

### ISSUE THREAD

**Issue by own3mall** [Chocobozzz/PeerTube#1731]
Is it possible to use Zanata for GitHub forks of PeerTube?  If so, is there a guide on how to make that work?  I'd like to localize some new constants I've put in my branch which I've been told will never be merged into the main branch, which I totally understand, but just in case someone else wants Google Recaptcha support, they could have a semi-proper implementation of it.  Though, I will admit I'm not a great angular, typescript, or node.js developer (and have little interest in using such a structured and locked down series of frameworks).

**Comment by Chocobozzz** [comment]
Hello,

No sorry trad.framasoft.org can't be used by peertube forks. But you can use another Zanata instance if you want
