### ISSUE TITLE
Localization in the Server API

### ISSUE THREAD

**Issue by own3mall** [Chocobozzz/PeerTube#1732]
Would it be possible to add localization support to the server-side components of PeerTube?

It looks like there aren't any messages being sent back currently, but it could come in handy for the future.  I'm using a message here that should be localized one day:

https://github.com/own3mall/PeerTube/blob/develop/server/controllers/api/users/index.ts#L250

If there's an easy way to import the same structure used by the client for the server, that would also be good to know.

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/1122
