### ISSUE TITLE
Release Instructions

### ISSUE THREAD

**Issue by own3mall** [Chocobozzz/PeerTube#1733]
The developer guide (https://github.com/Chocobozzz/PeerTube/blob/develop/.github/CONTRIBUTING.md) is great for testing, but would it be possible to add instructions on how to create a release similar to the way it's done in the official PeerTube repository?  If the instructions could also include how you would then deploy the new release over an official existing version of PeerTube, that would also be super helpful.

**Comment by Chocobozzz** [comment]
Done in https://github.com/Chocobozzz/PeerTube/commit/39e6a5cbec21d5fa2e29be3e6f1c3e88726136ec
