### ISSUE TITLE
When account creation is disabled, we should give an explanation

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#1734]
I get lots of feedback regarding the complexity of creating an account on Skeptikon, which doesn't offer account creation. People have to guess how Peertube works and create an account on another Peertube instance (or on Mastodon if they know it).

Rather than leaving new users on their own, we'd rather give them explanation, and even suggest them a list of instance they may sign in and subscribe to the instances channels.

Florent

**Comment by Zig-03** [comment]
joinpeertube.org needs a complete rework too, we should bring it to the level of joinmastodon.org, in terms of UI, UX, usability etc.

**Comment by Chocobozzz** [comment]
Closing this issue since we made a lot of improvements since then:
 * We reworked the signup form
 * We added information in the login form if signups are disabled
 * We added many fields in the admin configuration form, available in the `About` page
