### ISSUE TITLE
Recommanded server bandwidth

### ISSUE THREAD

**Issue by simia-zaru** [Chocobozzz/PeerTube#1735]
I am considering to open an instance somewhere in the future, and was looking for information about recommanded server specifications. [Hardware recommendations are already addressed](https://github.com/Chocobozzz/PeerTube/blob/develop/FAQ.md#should-i-have-a-big-server-to-run-peertube) in the FAQ, but nothing is said about the serveur bandwidth, apart from "don't install it behind an ADSL link" on the install guide.

**What "minimum" bandwith would you recommand to have available for any given instance?**

**Comment by Chocobozzz** [comment]
~ 100Mbps
