### ISSUE TITLE
Client Server Service loadConfig Timing Issue when Using Specific URL on First Page Load

### ISSUE THREAD

**Issue by own3mall** [Chocobozzz/PeerTube#1737]
1.  Clear browser cache.
2.  Visit /signup page (without visiting any other page) using direct URL (https://myinstance/signup)
3.  loadConfig API XHR is made, but it doesn't complete in time before checks such as `return this.serverService.getConfig().signup.requiresEmailVerification` are made.

Default config options are returned on first page load because loadConfig hasn't completed, and the settings have not yet been cached in localStorage.  Thus, the page doesn't respect your settings since the database configuration settings weren't loaded in time.

Not sure how to fix this, but you can't assume that every user is going to hit the home page of https://myinstance/ to save the config settings in local storage.  This could throw off functionality on many pages.

**Comment by own3mall** [comment]
The way I handle this in PHP is that global settings are loaded from a MySQL database in a blocking synchronous call which get stored in a session variable as cache.  The settings are then loaded from the session cache (server side) for a while, but every 5th request or so, I reload settings from the database and override what is stored in the session cache.  This helps prevent users from continuing to use invalid setting values if they are changed by an admin while their session is active. 

In PeerTube, the `loadConfig` call needs to complete before the application should continue doing anything since many pages rely on these settings and can render differently depending on the setting.  However, I can't find a way to make the http.get request synchronous in angular because it goes against what angular stands for, and this is why frameworks like angular suck.  They're not flexible for every scenario.

Global server settings really need to be handled on the server side... not the client side.

**Comment by own3mall** [comment]
Ok, I fixed this in my branch:

Key commits:

https://github.com/own3mall/PeerTube/commit/8834eb3a5999e94efabeacd23867335ad0de7763
https://github.com/own3mall/PeerTube/commit/6de02a05bea600e5da2a10f7f708e1c6e54c5da4

Range of commits for 3/29/2019:

https://github.com/own3mall/PeerTube/commits/develop

I think this piece should be integrated in your branch ASAP and will prevent future problems like this.  Besides, in my branch, it is imperative for my implementation of Recaptcha.

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/f3ae606caf74c8a173ce44bf3f913f1488f97d7f
