### ISSUE TITLE
production server not working due to OAuth issue

### ISSUE THREAD

**Issue by wesson09** [Chocobozzz/PeerTube#1738]
**What happened?**
 "Error Cannot retrieve OAuth Client credentials: . [...]" pops when connecting to server
  any login attempt then fail with "Invalid client: client is invalid"

**What do you expect to happen instead?**
 normal operation

**Steps to reproduce:**

Used a fresh installation of Debian 

Distributor ID: Debian
Description:    Debian GNU/Linux 9.8 (stretch)
Release:        9.8
Codename:       stretch

1. Followed all the production.md guide steps

2. Entered the URL of my instance - any browser reproduce

**Additional information**
* PeerTube version or URL: 1.2.1
* Browser name/version: chrome, yandex, firefox, Edge - not important
* NodeJS version: v11.12.0 (also tried with V8)

* Link to browser console log if useful: not useful
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
see attached
[peertube.log](https://github.com/Chocobozzz/PeerTube/files/3015725/peertube.log)

**Comment by wesson09** [comment]
Here it is, renamed to txt to be accepted by GH

[production.yaml.txt](https://github.com/Chocobozzz/PeerTube/files/3017266/production.yaml.txt)

**Comment by wesson09** [comment]
I'm not using docker. Straight deployment

listen:
  hostname: 'localhost'
  port: 9000

# Correspond to your reverse proxy server_name/listen configuration
webserver:
  https: true
  hostname: 'video.discord-insounis.fr'
  port: '443'

# Proxies to trust to get real client IP
# If you run PeerTube just behind a local proxy (nginx), keep 'loopback'
# If you run PeerTube behind a remote proxy, add the proxy IP address (or subnet)
trust_proxy:
  - 'loopback'

# Your database name will be "peertube"+database.suffix
database:
  hostname: 'localhost'
  port: 5432
  suffix: '_prod'
  username: 'peertube'
  password: 'xxxxxxxxxxxx'
  pool:
    max: 8

# Redis server for short time storage
# You can also specify a 'socket' path to a unix socket but first need to
# comment out hostname and port
redis:
  hostname: 'localhost'
  port: 6379
  auth: null
  db: 0

**Comment by JohnXLivingston** [comment]
You named your instance video.discord-insou**ni**s.fr , but it has to be video.discord-insou**m**is.fr

**Comment by wesson09** [comment]
silly me !
