### ISSUE TITLE
Column quota sortable in user list ?

### ISSUE THREAD

**Issue by bristow** [Chocobozzz/PeerTube#1741]
It would be very convenient to be able to sort users by quota used, like 'created' and 'username' columns.

I think it's an issue for the label "Good First Issue" :)

**Comment by darnuria** [comment]
Hi, @rigelk would you mentor me on this issue ? I can start working on it tomorrow.

**Comment by rigelk** [comment]
@darnuria of course!

**Comment by darnuria** [comment]
@rigelk hi! Is that the right componnent to edit: `client/src/app/+admin/users/user-list/user-list.component.html` ? I am new to AngularJS.

**Comment by Chocobozzz** [comment]
@darnuria yes, but you'll also have to update the [backend](https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/constants.ts#L42) (just add `videoQuota` to the array)

**Comment by darnuria** [comment]
Shall we continue the discussion inside the merge request or here?

**Comment by Chocobozzz** [comment]
in the mr

**Comment by Chocobozzz** [comment]
Implemented by @darnuria in https://github.com/Chocobozzz/PeerTube/commit/4511437e19d2ce521e28f8417512d47773207da4 & https://github.com/Chocobozzz/PeerTube/commit/aa3796bda5a6776e0d21048239f25d385a8e7545
