### ISSUE TITLE
Using the upload video endpoint without a `privacy` field results in an error 500

### ISSUE THREAD

**Issue by magopian** [Chocobozzz/PeerTube#1742]
**What happened?**
Using the [upload video with its metadata](https://docs.joinpeertube.org/api.html#tag/Video/paths/~1videos~1upload/post) endpoint results in a server 500 error if the `privacy` field isn't provided.

For the record, this field isn't displayed as `required`, and nor is it present in the example code.

**What do you expect to happen instead?**
The documentation should display this field as `required`, and not return a 500 error if it's missing.

**Steps to reproduce:**
Here's an example curl request that fails:

```
http -v --form POST https://peertube.scopyleft.fr/api/v1/videos/upload videofile@~/Downloads/video_short-720p.mp4  channelId=3 name=video_short-720p "Authorization:Bearer <redacted>"
```

Adding `privacy=1` returns a 200 and the video is uploaded.
**Additional information**
* PeerTube version or URL: v1.2.1 https://peertube.scopyleft.fr/
* Browser name/version: firefox nightly

**Comment by Tristramg** [comment]
What would be the expected behaviour?

I’m not confident at looking at the code,

In `server/helpers/custom-validators/videos.ts` shouldn’t this do the trick?
```
 function isVideoPrivacyValid (value: number) {
-  return validator.isInt(value + '') && VIDEO_PRIVACIES[ value ] !== undefined
+  return value === null || validator.isInt(value + '') && VIDEO_PRIVACIES[ value ] !== undefined
 }
```

Also I didn’t look hard enough to know where to fix the documentation

**Comment by magopian** [comment]
I'm not sure: it could either use a default privacy setting (private by default? Public by default?), or return a proper error code, but returning a 500 seems incorrect.

**Comment by Chocobozzz** [comment]
Thanks for the issue. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/2b4dd7e26d93c2d9bef4f365cb03c511eff4ca8f

**Comment by Tr4sK** [comment]
Thank you. Got a hard time to figure out how to deal with that one
