### ISSUE TITLE
[feature] a webextension to recommend videos from peertube

### ISSUE THREAD

**Issue by jibe-b** [Chocobozzz/PeerTube#1743]
There could be a webextension that adds video recommendations to the UI of youtube and other centralized services. The recommended videos would indeed be videos available through peertube instances.

This way, when the user gets interested by a video hosted on a peertube instance, the person would be redirected to a peertube instance.

**Comment by rigelk** [comment]
It [already exists](https://gitlab.com/Ealhad/peertubeify) :slightly_smiling_face:

**Comment by jibe-b** [comment]
So cool! Thanks @rigelk!

**Comment by Booteille** [comment]
And you have diffferent parameters, check in the settings of the extension!
