### ISSUE TITLE
How to search videos with unknown language

### ISSUE THREAD

**Issue by lishoujun** [Chocobozzz/PeerTube#1746]
Hi there,
  In Thorium(a peertube-android app) ,I can filter videos by language ,it use a  languageOneOf PARAMETERS of REST API.
  But,there is not a language id for unknown. if I just want videos in english/chinese/unknown.

**Comment by Chocobozzz** [comment]
Hello, and sorry for the late.

`_unknown` is the language code for unknown video language.

**Comment by lishoujun** [comment]
Thanks！
