### ISSUE TITLE
Muted notifications not removed

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#1747]
Mutes don't remove the affected account(s) from your notifications if it's already been received.

**Additional information**
* PeerTube version or URL: https://dialup.express
* Browser name/version: Firefox 66.0.1
* NodeJS version: v8.15.1

**Comment by Chocobozzz** [comment]
Done in https://github.com/Chocobozzz/PeerTube/commit/ea3674d04dd0a67962224073256dc7d4173527a5
