### ISSUE TITLE
Trusted sources to enable P2P or not

### ISSUE THREAD

**Issue by paulcable** [Chocobozzz/PeerTube#1750]
Due to some of my concerns about P2P (I'm talking here about situation when someone uploads a "shady" video and everybody who watches this video (with P2P feature ON) becomes a distributor of it) I'd like to ask you to implement a feature allowing each user to create a personal **list of trusted sources on Peertube (for P2P) by channel**. Let's say if you subscribe to a particular channel (and you trust this person) you can help them to distribute content adding them to your list. 
Technically it should eliminate awkward situations with bad videos and improve distribution. 

https://linuxrocks.online/@10X/101847771443375164

**Comment by JohnXLivingston** [comment]
You only distribute the video the time you are watching it. So you just have to close your browser tab to stop seeding.

**Comment by pabloweb10X** [comment]
> You only distribute the video the time you are watching it. So you just have to close your browser tab to stop seeding.

Hahah, good one.
It doesn't solve the problem. When Peertube becomes a bigger thing it'll be the way people get sued (because of bad actors).

**Comment by Chocobozzz** [comment]
Hello,

Thanks for this issue but it's out of the scope of PeerTube for now (too complex to implement/would confuse classic users).
