### ISSUE TITLE
Comment reporting

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#1751]
There's no report option for video comments.

**Comment by ahangarha** [comment]
I just got my first spam comment

![image](https://user-images.githubusercontent.com/11241315/80923162-1596bd80-8d97-11ea-8f5c-bbf9920fd662.png)

and I am shocked that neither I can delete it nor report!

**Comment by Chocobozzz** [comment]
@ahangarha Fixed in https://github.com/Chocobozzz/PeerTube/commit/fde37dc99c0ca43021ac3d1b3537f095ee6114b7

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/2947
