### ISSUE TITLE
Media could not be loaded message after uploading mp4 exported from Photoshop

### ISSUE THREAD

**Issue by rubahness** [Chocobozzz/PeerTube#1753]
Note: I am not fully confident in the quality of mp4s that Photoshop creates, but VLC was able to play it, and I was able to upload and watch it on YouTube.  In the case that it is malformed, I believe that the error message should be displayed before successfully saving video metadata and being shown the video URL.

**What happened?**
After uploading, when viewing the video https://peertube.video/videos/watch/f758eb78-d84f-431a-9fa0-4b71a2fd4077 see the message "The media could not be loaded, either because the server or network failed or because the format is not supported." displays, cannot view video in Firefox or Chrome

**What do you expect to happen instead?**
Handle the file properly, or if it truly is corrupt in some way, indicate that at the upload step and do not allow the upload. 

**Steps to reproduce:**

1. Export mp4 from Photoshop CS5.5 (e.g. http://www.snowy-day.net/stuff/others/lola-tail-twitch5.mp4 )

2. Upload mp4 to peer tube instance

3. Save video metadata and view video

**Additional information**
* PeerTube version or URL: peertube.video
* Browser name/version: Firefox 52, Chrome (latest I think)
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
I can play the video now so maybe transcoding fixed the issue?
