### ISSUE TITLE
CLI installation - npm error : Failed build:server script.

### ISSUE THREAD

**Issue by quentinDupont** [Chocobozzz/PeerTube#1754]
**What happened?**
Error launching CLI installation

<--- JS stacktrace --->

==== JS stack trace =========================================

`   0: ExitFrame [pc: 0x158b43d4fc5d]
Security context: 0x2d196ae1d9b1 <JSObject>
    1: checkTypeRelatedTo(aka checkTypeRelatedTo) [0x16089f959741] [/home/quentin/PeerTube/node_modules/typescript/lib/tsc.js:~34822] [pc=0x158b4493c91f](this=0x3add303825b1 <undefined>,0x104d635ea231 <Type map = 0x77b39a3ce01>,0x0bf53378e091 <Type map = 0x77b39a566c1>,0x16089f950fa1 <Map map = 0x77b39a03ec1>,0x3add303825b1 <undefined>,0x3add303825b1 <undefi...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20190402.212240.23086.001.json
Node.js report completed
 1: 0x9590c0 node::Abort() [node]
 2: 0x959d66 node::OnFatalError(char const*, char const*) [node]
 3: 0xb39fae v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb3a1e4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xf39832  [node]
 6: 0xf39938 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [node]
 7: 0xf46058 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xf46b6b v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xf498a1 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
10: 0xf13ad4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
11: 0x11c9dde v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
12: 0x158b43d4fc5d 
/home/quentin/PeerTube/scripts/build/server.sh: line 7: 23075 Aborted                 npm run tsc
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! peertube@1.2.1 build:server: `scripty`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the peertube@1.2.1 build:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/quentin/.npm/_logs/2019-04-02T19_22_40_827Z-debug.log`

**Steps to reproduce:**

1. Follow CLI installation steps

2. Launch  npm run build:server

**Additional information**

Peertube seems to work well otherwise (http://hitchtube.fr/)

**Comment by tcitworld** [comment]
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

Could it be "just" a memory issue?

**Comment by Chocobozzz** [comment]
> Could it be "just" a memory issue?

Yes it is. How many memory do you have?

**Comment by quentinDupont** [comment]
> > Could it be "just" a memory issue?
> 
> Yes it is. How many memory do you have?
In my server ?
3.83G

**Comment by Chocobozzz** [comment]
@quentinDupont On the computer on which you try to build CLI tools. What is your NodeJS version?

**Comment by quentinDupont** [comment]
v11.12.0

**Comment by quentinDupont** [comment]
v11.12.0

I try to launch CLI tools on my peertube server, according to doc, it's possible right ?

**Comment by gnouts** [comment]
I have a similar issue, `out of memory`. Stacktrace is different though.
I'm using OVH ks7 with 16Go ram. I was able to build peertube in the past on this machine.
I pulled tag v1.2.0. (because I need this version, though 1.2.1 is not successful either)

```

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2bd7954a5891 <JSObject>
    1: set(this=0x1a3e945574d9 <Map map = 0x3cde93384989>,0xdf9358f0f51 <String[7]: 1360073>,0x3080b26b289 <Type map = 0x3cde933df6e9>)
    2: createTypeReference(aka createTypeReference) [/home/nouts/peertube-import/PeerTube/node_modules/typescript/lib/tsc.js:~32707] [pc=0x2b96163cbbcf](this=0x28ab87822d1 <undefined>,target=0x2911dca783b9 <Type map = 0x3cde933ed2e9>,typeArguments=0xdf9358f01d1 ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x8cd14c [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocate(v8::internal::Isolate*, int, v8::internal::PretenureFlag) [node]
 7: v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehash(v8::internal::Handle<v8::internal::OrderedHashMap>, int) [node]
 8: v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::EnsureGrowable(v8::internal::Handle<v8::internal::OrderedHashMap>) [node]
 9: v8::internal::Runtime_MapGrow(int, v8::internal::Object**, v8::internal::Isolate*) [node]
10: 0x2b96159042fd
/home/nouts/peertube-import/PeerTube/scripts/build/server.sh: line 7: 24306 Aborted                 npm run tsc
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! peertube@1.2.0 build:server: `scripty`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the peertube@1.2.0 build:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-29T19_08_42_296Z-debug.log

```
```
(.env) nouts@alttube:~/peertube-import$ free -m
              total        used        free      shared  buff/cache   available
Mem:   16029        2551      6310      344      7167           12803
Swap:     510         0            510
```

**Comment by Chocobozzz** [comment]
@gnouts Please try with peertube 1.3. If it still does not work, try https://coderwall.com/p/jevsig/increasing-typescript-memory-limit-allocation-failed-process-out-of-memory

**Comment by gnouts** [comment]
@Chocobozzz  yep ! I updated yesterday, just tested today. had no issue.
