### ISSUE TITLE
videoView not incrementing

### ISSUE THREAD

**Issue by SMJ** [Chocobozzz/PeerTube#1755]
**What happened?**
Installed v1.2.1, clean install.  Invited several users to upload videos.  Videos show up, are playable but videoView does not seem to be updating.

**What do you expect to happen instead?**
Upon completion of viewing a video the view counter will increment by 1

**Steps to reproduce:**

1. Install v1.2.1 cleanly

2.upload a video 

3.view the video

4. see that the videoView is 0

**Additional information**
* PeerTube version or URL:  https://toobnix.org
* Browser name/version:  safari, edge, firefox, chrome
* NodeJS version: 8.15.0

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Nutomic** [comment]
How long did you wait? Iirc view counters are updated every hour or so.

**Comment by SMJ** [comment]
We waited 2 weeks and continued uploading videos.  Does videoView need to be initialized?

**Comment by Chocobozzz** [comment]
@SMJ No, you don't have to do anything. Please search errors in your logs

**Comment by SMJ** [comment]
There is an error about 'too much pending tasks' in the error log.  It appears 1,241 times and looks like this:

{"err":{"stack":"Error: Too much pending tasks\n    at AsyncLock.acquire (/home/mastodon/peertube/node_modules/async-lock/lib/index.js:141:15)\n    at /home/mastodon/peertube/dist/server/middlewares/cache.js:21:28\n    at Generator.next (<anonymous>)\n    at /home/mastodon/peertube/dist/server/middlewares/cache.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/home/mastodon/peertube/dist/server/middlewares/cache.js:3:12)\n    at /home/mastodon/peertube/dist/server/middlewares/cache.js:18:16\n    at /home/mastodon/peertube/dist/server/middlewares/async.js:13:32\n    at Layer.handle [as handle_request] (/home/mastodon/peertube/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/mastodon/peertube/node_modules/express/lib/router/index.js:317:13)\n    at /home/mastodon/peertube/node_modules/express/lib/router/index.js:284:7\n    at param (/home/mastodon/peertube/node_modules/express/lib/router/index.js:354:14)\n    at param (/home/mastodon/peertube/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/home/mastodon/peertube/node_modules/express/lib/router/index.js:410:3)\n    at next (/home/mastodon/peertube/node_modules/express/lib/router/index.js:275:10)\n    at cors (/home/mastodon/peertube/node_modules/cors/lib/index.js:188:7)\n    at /home/mastodon/peertube/node_modules/cors/lib/index.js:224:17\n    at originCallback (/home/mastodon/peertube/node_modules/cors/lib/index.js:214:15)\n    at /home/mastodon/peertube/node_modules/cors/lib/index.js:219:13\n    at optionsCallback (/home/mastodon/peertube/node_modules/cors/lib/index.js:199:9)\n    at corsMiddleware (/home/mastodon/peertube/node_modules/cors/lib/index.js:204:7)\n    at Layer.handle [as handle_request] (/home/mastodon/peertube/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/mastodon/peertube/node_modules/express/lib/router/index.js:317:13)\n    at /home/mastodon/peertube/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/home/mastodon/peertube/node_modules/express/lib/router/index.js:335:12)\n    at next (/home/mastodon/peertube/node_modules/express/lib/router/index.js:275:10)\n    at Function.handle (/home/mastodon/peertube/node_modules/express/lib/router/index.js:174:3)\n    at router (/home/mastodon/peertube/node_modules/express/lib/router/index.js:47:12)\n    at Layer.handle [as handle_request] (/home/mastodon/peertube/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/mastodon/peertube/node_modules/express/lib/router/index.js:317:13)\n    at /home/mastodon/peertube/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/home/mastodon/peertube/node_modules/express/lib/router/index.js:335:12)\n    at next (/home/mastodon/peertube/node_modules/express/lib/router/index.js:275:10)\n    at /home/mastodon/peertube/node_modules/express/lib/router/index.js:635:15\n    at next (/home/mastodon/peertube/node_modules/express/lib/router/index.js:260:14)\n    at Function.handle (/home/mastodon/peertube/node_modules/express/lib/router/index.js:174:3)\n    at router (/home/mastodon/peertube/node_modules/express/lib/router/index.js:47:12)\n    at Layer.handle [as handle_request] (/home/mastodon/peertube/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/mastodon/peertube/node_modules/express/lib/router/index.js:317:13)\n    at /home/mastodon/peertube/node_modules/express/lib/router/index.js:284:7","message":"Too much pending tasks"},"level":"error","message":"Cannot serve cached route.","label":"toobnix.org:443","meta":{"err":{"stack":"Error: Too much pending tasks\n    at AsyncLock.acquire (/home/mastodon/peertube/node_modules/async-lock/lib/index.js:141:15)\n    at /home/mastodon/peertube/dist/server/middlewares/cache.js:21:28\n    at Generator.next (<anonymous>)\n    at /home/mastodon/peertube/dist/server/middlewares/cache.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/home/mastodon/peertube/dist/server/middlewares/cache.js:3:12)\n    at /home/mastodon/peertube/dist/server/middlewares/cache.js:18:16\n    at /home/mastodon/peertube/dist/server/middlewares/async.js:13:32\n    at Layer.handle [as handle_request] (/home/mastodon/peertube/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/mastodon/peertube/node_modules/express/lib/router/index.js:317:13)\n    at /home/mastodon/peertube/node_modules/express/lib/router/index.js:284:7\n    at param (/home/mastodon/peertube/node_modules/express/lib/router/index.js:354:14)\n    at param (/home/mastodon/peertube/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/home/mastodon/peertube/node_modules/express/lib/router/index.js:410:3)\n    at next (/home/mastodon/peertube/node_modules/express/lib/router/index.js:275:10)\n    at cors (/home/mastodon/peertube/node_modules/cors/lib/index.js:188:7)\n    at /home/mastodon/peertube/node_modules/cors/lib/index.js:224:17\n    at originCallback (/home/mastodon/peertube/node_modules/cors/lib/index.js:214:15)\n    at /home/mastodon/peertube/node_modules/cors/lib/index.js:219:13\n    at optionsCallback (/home/mastodon/peertube/node_modules/cors/lib/index.js:199:9)\n    at corsMiddleware (/home/mastodon/peertube/node_modules/cors/lib/index.js:204:7)\n    at Layer.handle [as handle_request] (/home/mastodon/peertube/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/mastodon/peertube/node_modules/express/lib/router/index.js:317:13)\n    at /home/mastodon/peertube/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/home/mastodon/peertube/node_modules/express/lib/router/index.js:335:12)\n    at next (/home/mastodon/peertube/node_modules/express/lib/router/index.js:275:10)\n    at Function.handle (/home/mastodon/peertube/node_modules/express/lib/router/index.js:174:3)\n    at router (/home/mastodon/peertube/node_modules/express/lib/router/index.js:47:12)\n    at Layer.handle [as handle_request] (/home/mastodon/peertube/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/mastodon/peertube/node_modules/express/lib/router/index.js:317:13)\n    at /home/mastodon/peertube/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/home/mastodon/peertube/node_modules/express/lib/router/index.js:335:12)\n    at next (/home/mastodon/peertube/node_modules/express/lib/router/index.js:275:10)\n    at /home/mastodon/peertube/node_modules/express/lib/router/index.js:635:15\n    at next (/home/mastodon/peertube/node_modules/express/lib/router/index.js:260:14)\n    at Function.handle (/home/mastodon/peertube/node_modules/express/lib/router/index.js:174:3)\n    at router (/home/mastodon/peertube/node_modules/express/lib/router/index.js:47:12)\n    at Layer.handle [as handle_request] (/home/mastodon/peertube/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/mastodon/peertube/node_modules/express/lib/router/index.js:317:13)\n    at /home/mastodon/peertube/node_modules/express/lib/router/index.js:284:7","message":"Too much pending tasks"}},"timestamp":"2019-04-04T01:30:09.157Z"}

**Comment by Chocobozzz** [comment]
What is your OS and redis version?

**Comment by SMJ** [comment]
Debian Linux 8.11 3.16.0-7-amd64 #1 SMP Debian 3.16.59-1 (2018-10-03) x86_64 GNU/Linux
Redis server v=2.8.17 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=5b70b85861dcf95e

**Comment by Chocobozzz** [comment]
@SMJ Please try to update redis >= 2.8.18

**Comment by SMJ** [comment]
Redis server v=3.2.8 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=bb0ba4e36835f109
is now installed and peertube has been restarted.  Waiting "an hour or so" for videoView to update.

**Comment by scanlime** [comment]
re "an hour or so", video views are updated at the top of each hour, it's not irregular.

**Comment by Chocobozzz** [comment]
@SMJ Any news on this?

**Comment by ealgase** [comment]
Videos there appear to be getting views so it looks like it's fixed.
![image](https://user-images.githubusercontent.com/11603778/56900866-de474f80-6a64-11e9-9332-78055e72b362.png)
