### ISSUE TITLE
Setting the SMTP server in the configuration isn't enough to enabled the emails

### ISSUE THREAD

**Issue by magopian** [Chocobozzz/PeerTube#1758]
**What happened?**

I was having the message "We are sorry, you cannot recover you password because your instance administrator did not configure the PeerTube email system." when asking for a password reset.

Setting up the `SMTP` in the configuration (and having the confirmation from the logs that I was `Successfully connected to SMTP server.`) didn't do the trick.

**What do you expect to happen instead?**

I thought setting the `SMTP` configuration was enough, and didn't find any reference to the following configuration that is needed:

```
email:
  enabled: true
```

**Steps to reproduce:**

Do not set the above configuration, and ask for a password reset.

**Additional information**
* PeerTube version: v1.2.1...3a0fb65c

**Comment by Chocobozzz** [comment]
Maybe related to https://github.com/Chocobozzz/PeerTube/issues/1737 :thinking:

**Comment by Chocobozzz** [comment]
Hope this will be fixed by https://github.com/Chocobozzz/PeerTube/commit/f3ae606caf74c8a173ce44bf3f913f1488f97d7f
