### ISSUE TITLE
View private or unlisted video in account or channel page

### ISSUE THREAD

**Issue by victor-doucet** [Chocobozzz/PeerTube#1760]
I think it could be useful for admins to be able to see unlisted and private videos on the account page or channel page.
I'm seeing users on my instance that are using it to store copyrighted media and use the “embed player” on an external streaming website.
In the admin page I'm seeing users that have several Gigabits of data but there is no video when I click on their profile, so I can't know if their storing media that are illegal regarding the local law or our terms and condition.
I know this feature is already available on the “Local videos” page but it's not very friendly when we're searching for a specific user's media.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/0aa52e170727ac6bdf441bcaa2353ae0b8a354ed
