### ISSUE TITLE
HLS files are being re-transcoded instead of remuxed

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#1761]
Running the latest develop as of commit 32157c0892ed000d15ad8fbc89e90fd005a5f4e8, to test out the new HLS functionality

**What happened?**

Added some example videos to a test image, with HLS enabled. After the usual transcodes, I started seeing HLS transcoding jobs like this one:

```/usr/local/bin/ffmpeg -i /var/www/peertube/peertube-latest/storage/videos/3dc0386f-80bd-419b-9f04-ed5d5c5780c8-1080.mp4 -y -acodec libfdk_aac -aq 5 -vcodec libx264 -r 30 -filter:v scale=w=trunc(oh*a/2)*2:h=1080 -f mp4 -level 3.1 -b_strategy 1 -bf 16 -pix_fmt yuv420p -map_metadata -1 -movflags faststart -maxrate 5800000 -bufsize 11600000 -g 60 -threads 1 -hls_time 4 -hls_list_size 0 -hls_playlist_type vod -hls_segment_filename /var/www/peertube/peertube-latest/storage/streaming-playlists/hls/3dc0386f-80bd-419b-9f04-ed5d5c5780c8/3dc0386f-80bd-419b-9f04-ed5d5c5780c8-1080-fragmented.mp4 -hls_segment_type fmp4 -f hls -hls_flags single_file /var/www/peertube/peertube-latest/storage/streaming-playlists/hls/3dc0386f-80bd-419b-9f04-ed5d5c5780c8/1080.m3u8```

Unfortunately, this is unnecessarily re-compressing both the audio and the video, leading to a lot of extra power consumption and decreased quality.

**What do you expect to happen instead?**

I expect the video to be transcoded exactly once per resolution. To generate the HLS playlist and fragmented mp4, I expect ffmpeg to be called with "-c:v copy -c:a copy" or equivalent.

I also expect a way to bring existing videos into conformance with an upgraded PeerTube's requirements without additional loss in quality.

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/14aed608f540b587b3ab2529d06690815214d232
