### ISSUE TITLE
Contact button not clear in french in small screen 

### ISSUE THREAD

**Issue by quentinDupont** [Chocobozzz/PeerTube#1762]
**What happened?**
Instance contact button is not clear in french :

![image](https://user-images.githubusercontent.com/9005817/55686520-a025a700-5962-11e9-9a0b-bad82008b6e8.png)

**What do you expect to happen instead?**

Maybe just display "Contact" in small screen

**Steps to reproduce:**

1. Go to https://my.instance.truc/about/instance

2. Have a small screen / window

**Comment by Chocobozzz** [comment]
Seems to have been fixed somewhere because I cannot reproduce: https://peertube2.cpy.re/about/instance
