### ISSUE TITLE
"low visibility" moderation tag

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#1767]
This 'tool' is to be used to tag videos or instances that don't necessarily break any rules but which the instance owner may not think it's appropriate to have highlighted on the front page of his peertube instance or to appear as a recommended video in the right sidebar (Other videos).

**For example:**
Instance A doesn't like the content of instance B and the content of instance B doesn't necessarily go against any principles/rules of instance A but at the same time instance A wouldn't like the content of instance B to be highly visible on its instance, so instance A tags the whole instance B (or only some videos) with this "low visibility" tag, which would mean that those videos would never appear on the homepage, or trending, or as a recommended video (right sidebar) etc.. and will only be discoverable via SEO, instance search, if embedded in a website and direct link.

**Why?** 
Inevitably some content that today we consider as normal (mostly controversial subjects) in time will be considered by "the majority" as unacceptable or offensive or something else and most instances will ban these "controversial" instances or videos. And this is a kind of censorship that PeerTube isn't protected against.
With this tool instance owners will have to distinguish content that actually is harmful or that goes against their rules **vs** content that they personally don't like but wouldn't mind people watching it. 

Ideas, opinions, suggestions? Thank you.

**edit:** With this tool, some instances may consider "grouping" their rules into two categories: 

- **Important rules** - the main rules that once broken the user or instance will get banned.
- **Additional rules** - rules that once broken, the user or instance will get tagged with this "low visibility" tag.

**Comment by FirePowi** [comment]
As it has been labeled as a Enhancement, you may remove "Suggestion: " in the title :)

**Comment by MarionMoseby** [comment]
This is the same as silencing a mastodon instance right? Maybe things could be done the same way, so as to keep compatibility?

**Comment by Zig-03** [comment]
I'm having a hard time searching for what this "silencing" feature on Mastodon does, can you drop a link please?

**Comment by MarionMoseby** [comment]
It is basically a shadowban: you cannot see messages sent by people from those instances, but if a user boosts it, it becomes visible, but not the answers. You can see it in this issue: https://github.com/tootsuite/mastodon/issues/5694 although maybe it is not exactly what ypu are looking for hehe

-------- Mensaje original --------

**Comment by Zig-03** [comment]
@MarionMoseby "low visibility" moderation tag is more of an attempt to protect peertube against censorship. 
This tool should empower instance owners to allow more content that they don't necessarily like, but that otherwise if not present, people would think that the instance owner is censoring that kind of content. 
For example, the owner of instance A may not like videos that talk about "xyz" and if he removes all "xyz" content, people would complain that he is censoring them, so instead of banning/removing "xyz" content completely, he just tags it with the "low visibility" moderation tag. This way he is happy that he isn't actively/visibly promoting "xyz" content on his instance and at the same time people are happy that if they search for "xyz" content they will find it, so they will feel "protected".

**Comment by FirePowi** [comment]
Does it stand in "Host" case ?
Will the owner of an instance still be a host or will they be an editor ?

**Comment by Zig-03** [comment]
> will the owner of an instance still be a host or will they be an editor ?

All instance owners are automatically moderators as well, and this is a moderation tool for them.

**Comment by Chocobozzz** [comment]
Hello,

We have different actions for this purpose:
 * Blacklist
 * Removal
 * Account/instance muting

I know it is not exactly what you're asking for, but we can't really implement too much possibilities: it would overload the code and the UI, and we don't have many developers on PeerTube.

And I think it could be a feature a PeerTube plugin can implement.
