### ISSUE TITLE
peertube-upload.js issue with name value

### ISSUE THREAD

**Issue by BigMayo** [Chocobozzz/PeerTube#1771]
**What happened?**
Error: .field(name, val) val can not be empty

**What do you expect to happen instead?**
Upload video

**Steps to reproduce:**

1. node ./dist/server/tools/peertube-upload.js -u "https://tube.server.com" -U user -p password --video-name "You Can Take an Arrow to the Knee and Still Be an Adventurer" -f /media/Software/Tutorials/STUFF/THINGS/STUFF_Videos_downloaded/THINGS_Vault_-_You_Can_Take_an_Arrow_to_the_Knee_and_Still_Be_an_Adventurer.mp4

2. 
Uploading You Can Take an Arrow to the Knee and Still Be an Adventurer video...
Error: .field(name, val) val can not be empty
    at Test.RequestBase.field (/home/magnopus/PeerTube/node_modules/superagent/lib/request-base.js:401:11)
    at Object.<anonymous> (/home/magnopus/PeerTube/dist/shared/utils/videos/videos.js:257:14)
    at Generator.next (<anonymous>)
    at fulfilled (/home/magnopus/PeerTube/dist/shared/utils/videos/videos.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

3.

**Additional information**
* PeerTube version or URL: peertube 1.2.0-rc.1
* Browser name/version: Command line tools
* NodeJS version: nodejs v8.15.1

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
{"message":"172.16.0.211 - - [15/Apr/2019:17:16:48 +0000] \"GET /api/v1/oauth-clients/local HTTP/1.0\" 200 99 \"-\" \"node-superagent/3.8.3\"\n","level":"info","label":"magtube.magnopus.com:443","timestamp":"2019-04-15T17:16:48.968Z"}
{"message":"172.16.0.211 - - [15/Apr/2019:17:16:49 +0000] \"POST /api/v1/users/token HTTP/1.0\" 200 159 \"-\" \"node-superagent/3.8.3\"\n","level":"info","label":"magtube.magnopus.com:443","timestamp":"2019-04-15T17:16:49.144Z"}
{"message":"172.16.0.211 - - [15/Apr/2019:17:16:49 +0000] \"GET /api/v1/users/me HTTP/1.0\" 200 2884 \"-\" \"node-superagent/3.8.3\"\n","level":"info","label":"magtube.magnopus.com:443","timestamp":"2019-04-15T17:16:49.261Z"}

**Comment by BigMayo** [comment]
Same issue occurs in peertube v1.2.1

**Comment by Chocobozzz** [comment]
Thanks for the issue. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/fc8c024a1b1b1e439ef8f5b34513033920852b82
