### ISSUE TITLE
API Video channel not found

### ISSUE THREAD

**Issue by Moudex** [Chocobozzz/PeerTube#1772]
With the API, got error "Video channel not found" for some channels.

I start to list videos channel for an instance :
`https://peertube.social/api/v1/video-channels`

Then try to view a channel:
`https://peertube.social/api/v1/video-channels/2d0635d2-68cf-4204-81ef-8bcb49a091d8`

And got the error "Video channel not found".

Reproduce on lot of instances but on peertube.cpy.re, some channels seem work.

**Comment by Moudex** [comment]
I think I got it !

The doc said :

> https://docs.joinpeertube.org/api.html#tag/Video-Channel/paths/~1video-channels~1{id}/get
> The video channel id or uuid

But this may be a mistake, the parameter is the name (@host if the channel is not local).

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/9ce3d3027ed7253fbd4fe46787eda58c51549444
