### ISSUE TITLE
Création d'une instance

### ISSUE THREAD

**Issue by emmanuellehaddou** [Chocobozzz/PeerTube#1774]
Bonjour

Y a t il des sociétés ou des particuliers qui accepteraient d etre rémunérés pour créer une instance pour une personne ignare en informatique

Je cherche quelqu'un ou une entreprise en mesure de me créer mon instance sur peertube

Merci beaucoup de m indiquer le coût de votre travail

Bien cordialement

**Comment by Chocobozzz** [comment]
Please use the french forum instead: https://framacolibri.org/c/qualite/peertube
