### ISSUE TITLE
Video files are not cacheable

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1777]
I am not using the default Peertube installation where nginx has direct access to video files on the local disk. Instead, I am requesting all files through Peertube. In this setup, I noticed that fragments of video files were never cached. Turns out this is because Peertube is sending the following header:
```
cache-control: public, max-age=0
```

To verify, you can run the following request (you can use network tools in Firefox to copy the request from your own instance):
```
curl 'https://peertube.social/static/webseed/610a67fe-df2a-482d-ad9a-aeb57433187b-720.mp4' -H 'range: bytes=2031616-2097151' -I
``` 

I would expect that the cache-control header is set to `immutable`, or to a very long `max-age`.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
https://stackoverflow.com/a/1383359

Edit: To be clear, I only checked headers for the webseed folder, but this problem might also affect files in the redundancy folder.

**Comment by JohnXLivingston** [comment]
Is it really immutable ? When the video is transcoded, I think it can keep the same filename, but it is no more the same file.

**Comment by Chocobozzz** [comment]
The thing is that if some chunks are cached, but the file changed (because of transcoding), you won't be able to play the video because the torrent will have different pieces hash.

And do web browser really cache videos?

**Comment by Nutomic** [comment]
Right, transcoding is problematic. Its not about web browsers, I configured nginx to cache videos on the server side so clients don't have to access the backend for every request. At the moment, I configured it to ignore the cache-control header.

Ideally, we would set `must-revalidate` for files that still have to be transcoded, and `immutable` for everything else.

**Comment by Nutomic** [comment]
Okay I just had a look at the code. Video files are served statically, so we cant really set headers conditionally in the current setup. One workaround would be moving newly uploaded files to a seperate folder, so we can easily set different headers on video files that still have to be transcoded. This might also simplify things in other places if we can assume that files in `videos/` are always immutable. The easier option would be to set `cache-control: must-revalidate` for all video files.

By the way, the default installation that routes video files directly from nginx doesnt set any cache-control header. It would be a good idea to add the same header there.

**Comment by Chocobozzz** [comment]
Closing since we can't really cache video files, and I don't think it would be useful for web browsers.

**Comment by Nutomic** [comment]
Okay it turns out I didn't really explain why I'm requesting this. Imagine a setup where the video files are stored on a network drive, where latency and bandwidth are not great. But there is also a small ssd that could be used to cache frequently accessed video fragments. With this setup, it should be possible to get great performance for most videos, at a low storage price for the majority of videos that are rarely watched.

This is really easy to configure with nginx. All that's missing is to have immutable video files, so the cache doesn't break things.

**Comment by kontrollanten** [comment]
Another use case is when putting a CDN in front of PeerTube. I'm only using HLS and as I understand the files immutable.

Before the video has been transcoded it's served from `/static/webseed/{id}-{res}.mp4` and after transcoding from `/static/streaming-playlists/hls/{id}-{res}-fragmented.mp4`. I don't really see how the playlist are delivered when server from /static/webseed, but I guess it's not the same as from streaming-playlists.
