### ISSUE TITLE
Intro markers and the ability to auto-skip intros

### ISSUE THREAD

**Issue by SoniEx2** [Chocobozzz/PeerTube#1779]
When watching a lot of videos from the same user, which may contain intros, it'd be nice to be able to auto-skip the intros. There should be a way for the uploader to set an intro marker, and maybe an outro marker as well but I'm not sure of the usefulness of the latter.

**Comment by Zig-03** [comment]
Nice idea :+1:

**Comment by Chocobozzz** [comment]
Hello,

This is out of the scope of PeerTube core. But a PeerTube plugin could do the job (for example using the video description, and then automatically seeking the video).
