### ISSUE TITLE
UI inconsistency when uploading a video with non supported format

### ISSUE THREAD

**Issue by bnjbvr** [Chocobozzz/PeerTube#178]
Steps to reproduce
===

- log in
- try to upload a `mkv` video

Observed
===

The metadata form is shown, with an error at the top (red panel) showing: `Backend returned code 400, body was: This file is not supported. Please, make sure it is of the following type : .mp4, .ogv, .webm`.

There's also an empty green panel below.

![screenshot-2018-1-6 upload a video - peertube](https://user-images.githubusercontent.com/1180019/34641441-937f742e-f304-11e7-8908-d76fde4a3558.png)

Expected
===

The metadata form shouldn't be shown at all. The green panel shouldn't show up if it's empty.

**Comment by Chocobozzz** [comment]
Yes, and we should use notifications to display errors.

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/ce5496d6a31b9617aba67970f5dc135e73335234#diff-817a2882d60fde6c591ed4f5ab24c53aR148
