### ISSUE TITLE
Feature - change mail for user root

### ISSUE THREAD

**Issue by EricThi** [Chocobozzz/PeerTube#1782]
**What happened?**
Change mail adresse for user root

**Additional information**
* PeerTube version or URL:
Version 1.2.1
https://peertube.eric.ovh
* Browser name/version:
Firefox 67
* NodeJS version:
node -v
v11.13.0

npm -v
6.9.0

Thank you, Eric

**Comment by Chocobozzz** [comment]
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1393

**Comment by EricThi** [comment]
Hum sorry, i miss to check for simple user... my bad
