### ISSUE TITLE
Statistics in player

### ISSUE THREAD

**Issue by GameMaster2030** [Chocobozzz/PeerTube#1788]
I would like to see an option when you right click on the player you can enable a window in the player that shows:
- fps
- Dropped frames
- Buffer health

**Comment by AutomCoding** [comment]
I think it would be more logical to use `,` and `.` for framestepping, as their keys are next to oneother in most (possible all?) keyboard layouts, including the non-latin and Dvorak-based ones. Also, I haven't found any layout where you need to press shift for `,` and `.`, but a few with `<` and/or `>` in the upper case and some where they share key (like my Swedish keyboard).

**Comment by AutomCoding** [comment]
A button for clearing notifications is being discussed in #1730.

**Comment by GameMaster2030** [comment]
> I think it would be more logical to use `,` and `.` for framestepping, as their keys are next to oneother in most (possible all?) keyboard layouts, including the non-latin and Dvorak-based ones. Also, I haven't found any layout where you need to press shift for `,` and `.`, but a few with `<` and/or `>` in the upper case and some where they share key (like my Swedish keyboard).

Oh yeah, I meant `,` and `.`, let me update it.

**Comment by GameMaster2030** [comment]
> A button for clearing notifications is being discussed in #1730.

Oh, ok
