### ISSUE TITLE
I can't upload my transation on Zanata

### ISSUE THREAD

**Issue by gunchleoc** [Chocobozzz/PeerTube#1790]
Hi,

I used the "Translate offline" button in Zanata and have finished translating 3 of the files, but it seems like I lack the necessary privileges to upload my translation.

My Zanata profile is https://trad.framasoft.org/profile/view/gunchleoc?dswid=-626 and I am translating into Scottish Gaelic https://trad.framasoft.org/language/view/gd?dswid=-626

Who has the power to give me those privileges? Translating online is not an option for me, because it will deprive me of my translation memory.

Also, is there support for plural forms? Example:

* 2 subscriptions = 2 fho-sgrìobhadh
* 3 subscriptions  = 3 fo-sgrìobhaidhean

**Comment by ldidry** [comment]
Scottish Gaelic (gd) wasn’t activated, only Scottish Gaelic United Kingdom (gd-GB) was. I activated gd, it should be ok now.

For the plural forms, I have no idea. Ping @Chocobozzz

**Comment by gunchleoc** [comment]
Thanks! We don't expect separate translations for the 2 locales, so maybe it would make sense to switch gd_GB off.

**Comment by gunchleoc** [comment]
Now I have another problem: I am not allowed to replace my own translations when I'm uploading to Zanata. So, my translation is blocked again. I have unchecked the "Merge" checkbox, because I want my corrections to override whatever I uploaded previously.

**Comment by Chocobozzz** [comment]
Sorry for the late @gunchleoc 

> Also, is there support for plural forms? Example:

    2 subscriptions = 2 fho-sgrìobhadh
    3 subscriptions = 3 fo-sgrìobhaidhean

No sorry there is no such support yet

> Now I have another problem: I am not allowed to replace my own translations when I'm uploading to Zanata

Did you manage to upload your translations?

**Comment by gunchleoc** [comment]
Not if I remove the tick from the "Merge?" checkbox, which I want to do to ensure that I always overwrite my older translations with my newer, corrected translations, e.g. when I have fixed a typo.

**Comment by Chocobozzz** [comment]
We don't use Zanata anymore. Please try with weblate :) https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#create-import-video-file-jobjs

**Comment by gunchleoc** [comment]
Thanks! My translation is now at 100% on https://hosted.weblate.org/projects/peertube/
