### ISSUE TITLE
Remove source code from translation markup

### ISSUE THREAD

**Issue by gunchleoc** [Chocobozzz/PeerTube#1794]
We have a number of translation entities that look like this:

`\n        <x id="START_TAG_MY-GLOBAL-ICON" ctype="x-my-global-icon" equiv-text="<my-global-icon>"/><x id="CLOSE_TAG_MY-GLOBAL-ICON" ctype="x-my-global-icon" equiv-text="</my-global-icon>"/>\n\n        <x id="START_TAG_DIV" ctype="x-div" equiv-text="<div>"/>\n          Your video <x id="START_LINK" ctype="x-a" equiv-text="<a>"/><x id="INTERPOLATION" equiv-text="{{ notification.video.name }}"/><x id="CLOSE_LINK" ctype="x-a" equiv-text="</a>"/> has been unblacklisted\n        <x id="CLOSE_TAG_DIV" ctype="x-div" equiv-text="</div>"/>\n`

Despite the instruction on the translators howto page, these are still problematic:

1. Translation errors can break the sites (critical)
2. It is hard to find the translatable bits in those strings
3. Makes use of translation memories harder for translators

It would be great if they could look somewhat like this:

`{{ x-my-global-icon }} Your video {{ notification.video.name }} has been unblacklisted`

if translators need control over the icon position, or even:

`Your video {{ notification.video.name }} has been unblacklisted`

if they don't.

**Comment by Chocobozzz** [comment]
It should be better with https://github.com/Chocobozzz/PeerTube/commit/ee2b7df045fd629109bb4cfc1b11457af25d0688
