### ISSUE TITLE
Cannot change configuration.  The button was greyed out and showed "It seems the configuration is invalid"

### ISSUE THREAD

**Issue by fweng322** [Chocobozzz/PeerTube#1795]
**What happened?**
I just created the instance and login with root.  When trying to change the configuration (like enabling registration and set quota ... etc), the submit button was greyed out and showed "It seems the configuration is invalid.  Please search potential errors in the different tabs'.  However I tried to enable/disable most options without success.

**What do you expect to happen instead?**
At least it should tell me what's wrong.

**Steps to reproduce:**

1.Follow the instructions from  https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md
to install an instance

2. login the instance and change to the configuration

3. It showed the error messages without changing anything.

**Additional information**
* PeerTube version or URL: 1.2.1, https://peertube.slat.org
* Browser name/version: Google-chrome 74.0
* NodeJS version: 8.11.1

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): 
https://pastebin.com/vFBwnxJF

**Comment by fweng322** [comment]
I then found that I need to manually change the configuration file "production.yaml" to make it unlocked.  It seemed that I set the register limit to -1 AND(?) disabled register by default. 

I'd still like to ask for having a clear description of problem, not only "It seems the configuration is invalid".

**Comment by buttle** [comment]
Hi,

I think I've got a similar problem.

> It seems like the configuration is invalid. Please search for potential errors in the different tabs.

I've tried to disable/enable things, but no luck.

Where should I look?

Thank you :)

**Comment by Chocobozzz** [comment]
@buttle Hi, check the index URL that be filled. It's a bug introduced in pt 2.2

**Comment by buttle** [comment]
Yep!! that fixed it :)

**Comment by cclloyd** [comment]
> @buttle Hi, check the index URL that should be filled. It's a bug introduced in pt 2.2
> 
> **EDIT:** You'll have to enable _Automatically follow instances of a public index_ checkbox first, fill the input and re disable the checkbox

Should this not be reopened and fix it so that you don't have to enable it first?  Why is a URL required if that feature isn't enabled?  It also doesn't support http urls, only https.

**Comment by Chocobozzz** [comment]
> Should this not be reopened and fix it so that you don't have to enable it first? 

It's already fixed in develop.

> Why is a URL required if that feature isn't enabled?

Because this is a bug

>  It also doesn't support http urls, only https.

Yes, peertube does not support HTTP without TLS in production.

**Comment by gramakri** [comment]
@Chocobozzz Do you know when a patch release (2.2.1) will be available with this fix? Thanks!

**Comment by Chocobozzz** [comment]
The fix will be released in 2.3 (July)

**Comment by mpfaff** [comment]
What should the index URL be?

**Comment by sunknudsen** [comment]
@Chocobozzz Same question as @mpfaff... I believe this is the last thing I need to sort out before launching my own instance. 😊

**Comment by Chocobozzz** [comment]
You can put any URL to fix this bug. If you want to auto follow an index, please see https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L380

**Comment by 22decembre** [comment]
Hi. May I add that the whole thing should not erase the configuration you put in place previously, like all your ToS and other stuff. Thanks.

**Comment by imc67** [comment]
Hoped this bug was in the latest 2.3.0 fixed but it seems it's not. After install you get the setup-wizard bringing you to Configuration > Instance Information. After filling in all the fields and press save .... it's all empty again.

**Comment by gramakri** [comment]
1. Admin -> Configuration
2. Make changes and save. It seems that `local-production.json` is created/updated
3. The UI does not seem get values from the `local-production.json`

**Comment by gramakri** [comment]
@imc67 This was a bug in the Cloudron package. I misread https://github.com/lorenwest/node-config/wiki/Configuration-Files and the package was using both yaml and json files (the yaml gets precedence). The fix was simple - https://git.cloudron.io/cloudron/peertube-app/-/commit/62eefb5582489905668c54d1f77b4593ccfe62a6

**Comment by mpfaff** [comment]
For anyone still wondering what to put for the index url if you want it to be disabled, you can just put any url in there, it doesn't have to lead to a real index, and then you can disable it and save the configuration.

**Comment by Chocobozzz** [comment]
Admin config error display improved in https://github.com/Chocobozzz/PeerTube/commit/45ba09fef3b970fb916ffb1b0ac7509db7bbdde6
