### ISSUE TITLE
UX improvement: put download links directly under videos, with admin option to remove completely 

### ISSUE THREAD

**Issue by strypey** [Chocobozzz/PeerTube#1797]
The best place to put download links would be directly under the video embed on the video page. 

The download options for PT videos are currently inconvenient to use. To download a video, a user has to know to click the ... button, then click the 'download' button that pops up, then choose options from a pop-up that requires 3 clicks to begin. When asked in issue #639 why the download options are obscured in this way, @rigelk commented:
> the download button, on the other hand, is hidden because some people think it encourages people to pirate videos (whatever that means). It's a middle ground to not have to add an option to hide it.

This seems like a compromise that serves nobody. Downloads are not prevented, and UX quality is reduced. This is a poor solution to both problems (allowing downloads and preventing unauthorized copying).

What I suggest is to add a button to the settings menus that allow admins to toggle downloads off for their instance, and allow users to toggle downloads off for their channel. Doing it that way means that video hosts who want to allow downloads can do so and all the download buttons can be right there on the video page, rather than hidden away. Those who don't want their videos to be downloaded have an easy way to remove the download options in the PT interface completely. You'd need to set this up so that toggling downloads off also either a) prevented their videos being mirrored on other instances/ channels, or b) prevented downloads from the video page of mirrored copies too.

**Comment by ealgase** [comment]
Anyone who wants to download the video could easily use ytdl-org/youtube-dl.  Obscuring the functionality of downloading is an anti-user choice.

**Comment by Chocobozzz** [comment]
There is already a setting for uploaders to disable the download button.

We put it in the `...` because it's an option we consider less used than `Share` or `Save to` and we miss space in this area. IMHO PeerTube is a video streaming application, not a video download application so 3 clicks to download a specific video is acceptable.

**Comment by strypey** [comment]
@Chocobozzz:

> We put it in the `...` because it's an option we consider less used than `Share` or `Save to` and we miss space in this area.

For mobile browsers, you could put the download icon where the "..." is
now, and link it directly to the download modal. It would take up
exactly the same screen space. For desktop browsers, you could do the
same thing, but with a mouse-over saying "download" if the user hovers
their pointer over the download icon. This would be both quicker and
less confusing.

Looking at a video page on Vidcommons.org, I can see a 'Share' button,
but no 'Save to' (they are running PT 1.2.1 according to the
[JoinPeerTube instances
page](https://instances.joinpeertube.org/instances)). Is this only
visible to logged in users?

**Comment by Chocobozzz** [comment]
> Is this only visible to logged in users?

Yes.

We don't have space to put the download button outside the `...`, and I think it's fine for a video streaming platform to click 3 times to download a video file.

**Comment by Cambridgeport90** [comment]
Hover wouldn't be all that proficient for those using assistive technology such as screen readers. Remember that. They have some facilities for that, but none of them are very good.
