### ISSUE TITLE
Unable to follow peertube account from mastodon (connection refused)

### ISSUE THREAD

**Issue by fweng322** [Chocobozzz/PeerTube#1798]
**What happened?**
I tried to follow my peertube channel.  I clicked subscribe on peertube and input my mastodon account franklin@social.slat.org.  However the mastodon always gives "Unfortunately, there was an error looking up the remote account".
I tried with another mastodon instance (fosstodon.org) but gives the same error.  I saw "connection refused" error in my nginx log, wondering if it is peertube's problem.

May be related to #1792 but our error seems not the same.

**What do you expect to happen instead?**
I should be able to subscribe peertube channel from mastodon

**Steps to reproduce:**

1. Login peertube and list my channel

2. Subscribe the channel and input my mastodon account

3. It showed "Unfortunately, there was an error looking up the remote account." error from mastodon.

**Additional information**
* PeerTube version or URL: https://peertube.slat.org/
* Browser name/version: Google chrome 74.0
* NodeJS version: 8.11.1~dfsg-2~bpo9+1

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
peertube.log: https://pastebin.com/3qW949Vy
nginx error.log: 
```
2019/05/04 10:42:30 [error] 9306#9306: *104 connect() failed (111: Connection refused) while connecting to upstream, client: 114.43.26.171, server: peertube.slat.org, request: "GET /api/v1/users/me HTTP/2.0", upstream: "http://[::1]:9000/api/v1/users/me", host: "peertube.slat.org", referrer: "https://peertube.slat.org/video-channels/freddy.and.eddy/videos"
```

**Comment by gbip** [comment]
I do have the same issue using Peertube v1.2.1(gouttedeau.space) and Mastodon v2.8.2 (mastodon.tetaneutral.net).
Trying to comment raises the same issue.

**Comment by Chocobozzz** [comment]
Could you try with [this channel](https://peertube3.cpy.re/video-channels/ecf59e86-a51c-438f-bfbc-1d6f995c6ff9)?

**Comment by gbip** [comment]
I tried again, with my mastodon account (gbip@mastodon.tetaneutral.net) and it failed again.
Here is a screenshot of the error page : ![2019-05-24-174655_2560x1440_scrot](https://user-images.githubusercontent.com/15819864/58340359-f6d03d00-7e4b-11e9-9791-22183afe2ff8.png)

**Comment by Chocobozzz** [comment]
Thanks. Since it's the same issue than https://github.com/Chocobozzz/PeerTube/issues/1528, closing this one.
