### ISSUE TITLE
Add "Copy to clipboard" button to URLs

### ISSUE THREAD

**Issue by ldidry** [Chocobozzz/PeerTube#18]
When displaying URLs to share, it would be useful to have a "Copy to clipboard" button. A snippet to do that: https://framagit.org/luc/lutim/blob/master/themes/default/templates/partial/lutim.js.ep#L77

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/c7e1e432b0e5d321ff2331cf3ddff56c43500788

Thanks @sticmac
