### ISSUE TITLE
Can't upload the Sintel trailer

### ISSUE THREAD

**Issue by bnjbvr** [Chocobozzz/PeerTube#180]
Steps to reproduce
===

- download the Sintel trailer from http://peertube.cpy.re/.
- upload it on another (my?) peertube instance, without touching the file.

Observed
===

A red panel shows up with "Cannot update the video.", and the browser devtools console shows 

```
Backend returned code 404, body was: Video not found
{ body: Object { error: "Video not found" }
message: "Video not found"
status: 404 }
```

Server logs showed something about an unexpected ffmpeg error, without any more indication. Unfortunately, I can't find it anymore because of the DB hammering bug.

Here's my version of ffmpeg, just in case:

ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers 

I think there are several (some independent) ways forward:

- indicate in the README etc what's the minimum version of ffmpeg that's needed
- print ffmpeg errors in the console (if that's not already done)
- try different ffmpeg options when there's an error
- try not to re-encode the video? (I don't know if that's feasible; maybe PeerTube will encode them in lower bandwith / different codecs, to ensure maximum support from all the browsers)

What do you think?

**Comment by Chocobozzz** [comment]
Do you have the stack trace? 

Transcoding is disabled by default: https://github.com/Chocobozzz/PeerTube/blob/develop/config/default.yaml#L47
But we use ffmpeg (ffprobe in fact) to get the video duration on upload.

**Comment by bnjbvr** [comment]
Strange, today I could upload it without any problem. Closing, but there might be something going on here.
