### ISSUE TITLE
Add mute checkbox in ban modal

### ISSUE THREAD

**Issue by FirePowi** [Chocobozzz/PeerTube#1803]
**What happened?**
I banned an user, uploaded videos are still watchable

**What do you expect to happen instead?**
When an user is being banned, delete their videos.

**Steps to reproduce:**

1. Create a fake account

2. Upload videos

3. Ban this user as an admin

**Additional information**
* PeerTube version or URL: 1.2.1

**Comment by Chocobozzz** [comment]
We can add a checkbox in the ban modal to also mute the account so videos don't show anymore (but they will not be deleted). We can't really delete all user videos on banishment, because it's a reversible action.

If you want to delete user videos, then delete the user.

**Comment by FirePowi** [comment]
Well what's better with "banning" tool is that :
We can keep traces.
We still have the username and mail on our database. We can still find them.

If we delete an user, I guess they can re-use their mail address ?
I wish we could have irreversible ban that delete videos and comments (/keep them for at least 1 year if law ask for it) => A way of deleting an account but keeping informations.

But yep, a checkbox for temporary ban to mute videos would be cool.
Also… A ban can be due to video contents and comments so maybe, on ban, be able to delete some videos and comments.
Something like that (but graphically better ^^) :
![image](https://user-images.githubusercontent.com/14030913/57453509-dd819b00-7266-11e9-8bd7-e078b80ca1a5.png)

**Comment by Poslovitch** [comment]
Working on this.

**Comment by SimplyCorbett** [comment]
> 
> 
> Working on this.

Looking forward to this!
