### ISSUE TITLE
Public playlists not visible for guests

### ISSUE THREAD

**Issue by kerenon** [Chocobozzz/PeerTube#1804]
**What happened?**

Opening the "video-playlists" page on a server with public playlist(s) containing public video(s) as a guest, results in an empty page, no playlists are shown. Problem is not browser dependent.

**What do you expect to happen instead?**

A list of public playlists, like the one for logged in users

**Steps to reproduce:**

1. Browse to (incognito mode): /video-channels/[channel]/video-playlists

**Additional information**
* PeerTube version or URL: 1.2.1
* Browser name/version: Chrome 74.0.3729.131 (Official Build) (64-bit)
* NodeJS version:v 8.16.0

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): https://pastebin.com/N63e16xP

**Comment by Chocobozzz** [comment]
Thank you @kerenon, should be fixed in https://github.com/Chocobozzz/PeerTube/commit/1acd784cf984bb91d39c37a248805a7f96ea6643
