### ISSUE TITLE
Add instance in instances.joinpeertube.org

### ISSUE THREAD

**Issue by ufm** [Chocobozzz/PeerTube#1805]
Hi!

I have peertube server on https://peertube.lol

When I try to add my server on the page https://instances.joinpeertube.org/instances/add I get the error 'unable to verify the first certificate'

I do not have any problems with the certificate when I go to my site with firefox or chrome.

**Comment by tcitworld** [comment]
Probably linked to `Chain issues: Incomplete` on https://www.ssllabs.com/ssltest/analyze.html?d=peertube.lol
An extra download seems to be needed for the `Sectigo RSA Domain Validation Secure Server CA`, which is probably not handled by the JPT website.

**Comment by ufm** [comment]
Yes. Change ssl fix this trouble. Thanx!
