### ISSUE TITLE
Missing hot keys in cheat sheet

### ISSUE THREAD

**Issue by pinage404** [Chocobozzz/PeerTube#1807]
**What happened?**

The [cheat sheet of keyboard shortcuts](https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/core/hotkeys/hotkeys.component.ts#L11) is not exhaustive, some keyboard shortcuts are missing :

* `M` to mute
* `1`, `2`, `3` ... and so on to go to 10%, 20%, 30% ... of the video
* `F` to toggle fullscreen :
https://github.com/Chocobozzz/PeerTube/blob/c342726ad4ccbb90b8ff29f1cc1c89f9f7e8d98f/client/src/assets/player/peertube-player-manager.ts#L302
* Maybe others

**What do you expect to happen instead?**

I would like to see all hot keys

**Steps to reproduce:**

1. open the cheat sheet by taping `?`

**Additional information**
* PeerTube version or URL: PeerTube v1.2.1 https://peertube.mastodon.host/
* Browser name/version: Vivaldi 2.4 / Firefox Developer Edition 66.0b7
* NodeJS version: N/C

* Link to browser console log if useful: N/C
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): N/C

**Comment by Chocobozzz** [comment]
Done in https://github.com/Chocobozzz/PeerTube/commit/941c5eac1751ef93500d6afa58c4575f777dbff9
