### ISSUE TITLE
No scrollbar on hot keys cheat sheet

### ISSUE THREAD

**Issue by pinage404** [Chocobozzz/PeerTube#1808]
**What happened?**

I browse on PeerTube on a small window, i opened the cheat sheet of the keyboard shortcuts and i can't see all the list

**What do you expect to happen instead?**

I would like to have a scrollbar to be able to see all the list

The `display: table` can't have a scrollbar even with `overflow: auto`

https://github.com/Chocobozzz/PeerTube/blob/c342726ad4ccbb90b8ff29f1cc1c89f9f7e8d98f/client/src/app/core/hotkeys/hotkeys.component.scss#L2

https://github.com/Chocobozzz/PeerTube/blob/c342726ad4ccbb90b8ff29f1cc1c89f9f7e8d98f/client/src/app/core/hotkeys/hotkeys.component.scss#L4

**Steps to reproduce:**

1. open a small window
2. open the cheat sheet by taping `?`

**Additional information**
* PeerTube version or URL: PeerTube v1.2.1 https://peertube.mastodon.host/
* Browser name/version: Vivaldi 2.4 / Firefox Developer Edition 66.0b7
* NodeJS version: N/C

* Link to browser console log if useful: N/C
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): N/C**

**Comment by Chocobozzz** [comment]
Thanks, should be fixed in https://github.com/Chocobozzz/PeerTube/commit/187a00f0852e82580574aa0a37eae2fcb969db23
