### ISSUE TITLE
Webseed, Hotlink Block

### ISSUE THREAD

**Issue by filmaidykai** [Chocobozzz/PeerTube#1809]
**What happened?** Trying to block webssed links for domains

**What do you expect to happen instead?** one guy just start stealing and using from my instance hotlink so he is taken 1080p resolution and he have good traffic on his page so need to block it

**Additional information**
* PeerTube version or URL: PeerTube v1.2.1
* Browser name/version: Chromium, Opera, Firefox

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

So I found a  [Lesson](https://atulhost.com/hotlink-protection-nginx) and here what I done [Screen](http://ipix.lt/images/6d6f87f77643ae5284926346bbbc61c7.png)  but after that webseed is not working anywhere where Im doing wrong?

**Comment by Chocobozzz** [comment]
I don't think we can prevent hotlinking, since other peertube domains need to access to the videos file. But, if you want to forbid a specific host to access to your videos, you can blacklist the referer in nginx.

**Comment by filmaidykai** [comment]
So what I wanna to say that guy using static/webseed links what Im trying to do just leave webseed links work with domain player possible to do something like that?  Or one more thing just change direct link like webseed1 but if Im doing like that so after player cant get traffic from server.
