### ISSUE TITLE
Subtitles for some languages (at least one) does not work

### ISSUE THREAD

**Issue by xmgz** [Chocobozzz/PeerTube#1811]
**What happened?**
subtitles feature does not work for particular language selection (galician). Others work fine.

**What do you expect to happen instead?**
show galician subtitles as it happens with other languages

**Steps to reproduce:**

Example: <https://peertube.social/videos/watch/c1181dcf-978a-4118-a318-995e8492f52b>

1. I've created 3 .srt files with the same syntax (checked). Spanish, Galician and (fake)Chinese. Chinese.srt is just the galician one but uploaded using ·"chinese" as language for further syntax check.

2.  Both spanish and fake-chinese are shown as expected

3. when I select galician subtitles it doesn't work

4. I have not tested using other language selection.

**Additional information**

* PeerTube version or URL:

https://peertube.social/about/instance

* Browser name/version:
firefox

* * *
**Thanks** for your help and let me know if you need more info to dig into this problem or more extensive description.

**Comment by Chocobozzz** [comment]
Hi,

I'm sorry but I can't reproduce. When I select galician it show subtitles

**Comment by xmgz** [comment]
Thank you. After reading your message I went to another computer and YOU'RE RIGHT, it works fine.

So it might be some problem with the cached version of the file I first uploaded. I had refreshed the page tho.

Please feel free to close (or even delete) this issue.

Thanks again for your fast attention.
