### ISSUE TITLE
No option reorder the playlist

### ISSUE THREAD

**Issue by Tr4sK** [Chocobozzz/PeerTube#1812]
**What happened?**
Trying the new playlist features in v1.3.0-rc.1
Here is the [playlist](https://tube.tr4sk.me/videos/watch/playlist/b89ffdba-f4fe-4dbb-b27e-4b9fc009bdfd)
In the playlist edit view https://tube.tr4sk.me/my-account/video-playlists/b89ffdba-f4fe-4dbb-b27e-4b9fc009bdfd
I can drag and drop items to reorder them. But, there is no way to save the new order.

**Additional information**
* PeerTube version or URL: v1.3.0-rc.1
* Browser name/version: Firefox 66.0.5 (64 bits)

**Comment by Tr4sK** [comment]
Here is a trick to reorder the playlist.
Drag and Drop one item, then click on “Edit starts/stops at” and click on Save button.
You have to do it each time you drop an item.

**Comment by Chocobozzz** [comment]
The reorder is automatically saved, but it seems there is a bug when we try to move element of position `n` to position `n-1`. Can you confirm you reproduced this bug? Or is it another one?

**Comment by Chocobozzz** [comment]
Okay, I think it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/b767c4a74aa5ce44c7b6a89962cb153ecb3ace07

Thanks for the issue @Tr4sK
