### ISSUE TITLE
Problem with install PeerTube

### ISSUE THREAD

**Issue by nitro2010** [Chocobozzz/PeerTube#1816]
Hello,

**What happened?**
I get error when I want execute this command
`cd ./peertube-latest && sudo -H -u peertube yarn install --production --pure-lockfile`

**What do you expect to happen instead?**
success after compile, build peertube

**Steps to reproduce:**

1. Execute commands from: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/dependencies.md (success)

2. Execute commands from: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md

3. Stopped at command:
`cd ./peertube-latest && sudo -H -u peertube yarn install --production --pure-lockfile`

**Additional information**
* PeerTube version or URL:  v1.2.1
* Browser name/version: -
* NodeJS version:  v12.2.0

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
https://pastebin.com/CWJRrCJA

OS: Ubuntu 18.04 x64

**Comment by Chocobozzz** [comment]
Please try with NodeJS 10
