### ISSUE TITLE
Can't add video to Playlists

### ISSUE THREAD

**Issue by 6543** [Chocobozzz/PeerTube#1817]
Reproduce:
1. go to an video you like
2. add it to an playlist
3. klik on a other Video to "Other Videos" on the right site
-> now if you klik to save it is already marked like the video bevore
-> how you corect it: reload page/[F5] ... then the information is aktualiced

Peertube Version: v1.3.0-rc.1 (pre-relese)

**Comment by Chocobozzz** [comment]
Thanks for the issue @6543, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1c8ddbfaa03e241c782201343d424748efc191c1
