### ISSUE TITLE
Add ability to search on playlists

### ISSUE THREAD

**Issue by 6543** [Chocobozzz/PeerTube#1818]
Peertube Version: v1.3.0-rc.1 (pre-relese):

How I tested it:

1. creat playlist "test Pls"
2. search for "test Pls"
-> nothing found

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/4197

**Comment by 6543** [comment]
@Chocobozzz thanks and kudos to you :)
