### ISSUE TITLE
Suggest Playlist(s) at "Other Videos"

### ISSUE THREAD

**Issue by 6543** [Chocobozzz/PeerTube#1819]
What do you think about suggest playlists in wich the aktual video is in?

**Comment by Chocobozzz** [comment]
Hello,

Closing as it does not seem to be widely requested. The custom homage can address the "discover playlist" issue: https://github.com/Chocobozzz/PeerTube/issues/3582

**Comment by 6543** [comment]
@Chocobozzz thanks for the update 👍
