### ISSUE TITLE
Any reason why videos I upload wont play?

### ISSUE THREAD

**Issue by ReK2Fernandez** [Chocobozzz/PeerTube#182]
I can play the ones from the beta servers on my instance but not the ones I personally upload to my instance. https://video.hispagatos.org/
click on for example:
https://video.hispagatos.org/videos/watch/67e6d38f-69da-47b9-8ed8-6f82d47fb259

just keeps trying but is like if something is missing..
iptables is dissabled, and nothing is blocking anything at the moment.. unles the ISP is?

**Comment by Chocobozzz** [comment]
There is 404 for the static mp4 file: https://video.hispagatos.org/static/webseed/67e6d38f-69da-47b9-8ed8-6f82d47fb259-1080.mp4

I guess a bad configuration in nginx: https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube-https#L49

**Comment by ReK2Fernandez** [comment]
ahhh ok thanks yes I was missing one line
```
  #alias /your/installation/PeerTube/videos;
    alias /var/www/PeerTube/videos;
```
