### ISSUE TITLE
Build Docker releases on Framagit and push to Docker Hub

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1820]
Builds on [Docker Hub](https://hub.docker.com/r/chocobozzz/peertube) are very slow, I've been waiting for two days already to get the latest release. Right now it's just an annoyance, but it would be a real problem if there is a security issue.

It would be cool if we could setup an automated build for releases on [Framagit](https://framagit.org/framasoft/peertube/PeerTube) (or somewhere else) that builds the Docker images and pushes them to Docker Hub. 

I would be happy to set this up if you agree with the idea.

**Comment by Chocobozzz** [comment]
Done in https://github.com/Chocobozzz/PeerTube/commit/4ba5632266d0cdd54e8e09ac7416c2aa415eed65

**Comment by Nutomic** [comment]
Thanks!
