### ISSUE TITLE
Custom icons/SVGs

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#1821]
v1.3.0-rc.1 has no way to override icons. I used to input them through the custom CSS but that's not possible anymore.

I'm thinking there should be a way to replace them from the admin panel so recompiling for these minor changes isn't necessary.

**Comment by Chocobozzz** [comment]
I created a hook so you can change the SVG icons: https://github.com/Chocobozzz/PeerTube/commit/c2023a9f027deb310248ad751cc96a21a8e1ed03

`filter:internal.common.svg-icons.get-content.result`

See the [hello world plugin](https://framagit.org/framasoft/peertube/official-plugins/blob/master/peertube-plugin-hello-world/client/common-client-plugin.js#L49) for an example
