### ISSUE TITLE
Unable to follow peertube account from mastodon (Incorrect activity parameters)

### ISSUE THREAD

**Issue by kerenon** [Chocobozzz/PeerTube#1822]
**What happened?**
Following a peertube account from a mastodon instance, results in a "warn: Incorrect activity parameters" entry in the peertube log. Mastodon shows "Awaiting approval", and canceling the request creates another "warn" in the logs.

**What do you expect to happen instead?**
Account would be followed

**Steps to reproduce:**

1. Follow any peertube user from a mastodon instance

**Additional information**
* PeerTube version or URL: 1.3.0-rc.1 (didn't work on 1.2.1 either)
* Mastodon version: 2.8.2 (works with version 2.6.1)
* NodeJS version: v8.16.0

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): https://pastebin.com/6qwTQymu

**Comment by Chocobozzz** [comment]
Thanks for the issue @kerenon. It's fixed in https://github.com/Chocobozzz/PeerTube/commit/4550872bcc8f9ef46183463c7b7b74a90cb6d17c
