### ISSUE TITLE
[Enhancement] Download audio only

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#1824]
Hello,

It's cool to be able to download videos, but it would be cooler to be able to domnload audio only too (for musical videos, for example).

**Comment by rigelk** [comment]
Hi! Please look out for related issues before creating one, as #1437 already covers this. You can then detail further your use case there.

**Comment by zicmama** [comment]
You could build your [REC] Machine from https://www.copylaradio.com
