### ISSUE TITLE
Upgrade Process Docs?

### ISSUE THREAD

**Issue by stone212** [Chocobozzz/PeerTube#1825]
FAQ.md does not mention "upgrade".  

Wiki does not mention "upgrade".

**What happened?**

- I saw a new version is out.  I wanted to upgrade.

**What do you expect to happen instead?**

- I expected a doc that says "Upgrade Steps"

I am not trying to be rude.  I just wonder what the correct process is to upgrade please.  It is an Issue if there is no doc for this.

**Comment by ldidry** [comment]
It’s in the [production guide](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#upgrade).

**Comment by ldidry** [comment]
But well, indeed, it could be specifically linked.

**Comment by Chocobozzz** [comment]
Thanks for the issue @stone212 

It should be better with https://framagit.org/framasoft/peertube/documentation/commit/c28151892ba1d2ecf7f44b250bd681c7e1b74157 & https://github.com/Chocobozzz/PeerTube/commit/fe419518d09d25596ff33954fee9ccb2c79b7cde

**Comment by stone212** [comment]
@Chocobozzz @ldidry 

> But well, indeed, it could be specifically linked.

Well that's not the solution.  The solution is that it should be on https://docs.joinpeertube.org (because that's where the docs are!)
