### ISSUE TITLE
Peertube 1.3.0-rc1 fails to draw complete video library

### ISSUE THREAD

**Issue by Elrondo46** [Chocobozzz/PeerTube#1826]
On peertube 1.3.0-rc1

Video library of the users are incomplete and not watching all, just videos since two monthes ago, this bug not exist in 1.2.0.
I can modify video by searching locals video but that's not correct have to do this

**Comment by Chocobozzz** [comment]
Please provide the library URL and the missing video URLs.

**Comment by Elrondo46** [comment]
It's difficult because it's in the "my account" section "my videos" and you need to have my account to watch the bug.

My instance: https://peertube.pcservice46.fr

**Comment by Elrondo46** [comment]
I can send you screenshots

**Comment by Chocobozzz** [comment]
Yes please (my email is on my github profile)

**Comment by Chocobozzz** [comment]
Thanks for your video. It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/8c6781e95641fcb3d4a747ba4a37ef8efb1ad1bc
