### ISSUE TITLE
Wise use of root account

### ISSUE THREAD

**Issue by numero-744** [Chocobozzz/PeerTube#1828]
`Hello world !`

As a viewer I think that using the `root` account to post videos is irrelevant: "Published by root" makes no sense.
What more, as Peertube is federated, notably with other services (such as Mastodon), there are lots of active `root` accounts…
Would it be possible to encourage admins through design to use another account to post videos?

For example by suggesting creating an account to post videos as soon as the software is installed, and/or by displaying a short message about this issue.

Thanks for your attention.

**Comment by Chocobozzz** [comment]
I added a warning in the upload form in https://github.com/Chocobozzz/PeerTube/commit/cd3d847d63239802553b19f359c290a08fa0850c
