### ISSUE TITLE
countingViews blocked since v1.3.0-rc.1

### ISSUE THREAD

**Issue by DJeremyy** [Chocobozzz/PeerTube#1829]
Hi,
I notice a problem counting views since the update to version 1.3.0-rc.1. This problem does not seem isolated and occurs in multiple instances.
In database, nothing is added to the table since this update was done.

**Additional information**
* PeerTube version or URL: v1.3.0-rc.1 (pe.ertu.be)
* Browser name/version: FirefoxESR 60.0.2

**Comment by Chocobozzz** [comment]
Thank you @DJeremyy, it's fixed by https://github.com/Chocobozzz/PeerTube/commit/63dc589865fa1882d38f1d9e0050d2341869d487
