### ISSUE TITLE
Uploading/editing video private send invisible status to activitypub

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#183]
Hello,

(Edit: according to @Dryusdan@miaou.drycat.fr peertube server is on develop branche, so it hould use activitypub :-) )

I use the peertube server : https://peertube.drycat.fr.
Activitypub user is : @lecygnenoir@peertube.drycat.fr

I have uploaded 3 videos in private to test the new notification system, and it seems that each upload or edit has sent invisible (possibly, private ?) notification to the user.

You can see that user @lecygnenoir@peertube.drycat.fr has 13 status, but none are visible.

I am not sure why there are these status and what are their level (private? unlisted? direct?) but no subscribers have seen them.

Videos are : 
https://peertube.drycat.fr/videos/watch/1efa0445-4da7-4b8b-a9f0-b31a198d7f5b
https://peertube.drycat.fr/videos/watch/f0b4ea53-9de4-48ee-be56-da37ec319ae3

Here are the steps I have followed for the three videos : 
 - upload video in private status
 - while video upload, edit all fields
 - publish video once uploaded, still in private status
 - Do some edit (license, description, ...) while in private status
 - Finally edit the video to set public status

I have done that a couple of time for each video, creating 13 'shadow' status on the activitypub.

Hope it could helps, do not hesitate to tell me if I can do more tests or provide details!

Thank you

Regards,

**Comment by Chocobozzz** [comment]
Should be fixed: https://github.com/Chocobozzz/PeerTube/commit/9fb3abfdac5c4bffe9992a457e5210d3aa743952

Thanks for the report!
