### ISSUE TITLE
Dark theme's background color doesn't cover entire window

### ISSUE THREAD

**Issue by muesli** [Chocobozzz/PeerTube#1831]
When opening peertube.social in a browser window that's too small to display the entire page's width, the background of the dark theme only covers the initial width of the window. Resizing the window reveals a white background to the right.

Screenshot:
![image](https://user-images.githubusercontent.com/146378/58131367-c8b9e580-7c1e-11e9-8412-686c1b779995.png)

**Comment by Nutomic** [comment]
Can you reproduce this problem after a reload with Ctrl+F5? I was restarting the instance a couple times and switching between Peertube versions, so that might have caused the problem.

**Comment by muesli** [comment]
@Nutomic I can. I think it started about a week ago.

**Comment by Nutomic** [comment]
Okay then its probably a bug in 1.3.0

**Comment by Chocobozzz** [comment]
Is it still an issue in the peertube v2?

**Comment by muesli** [comment]
No offense, but why don't you just try it? It literally takes 10 seconds:

![image](https://user-images.githubusercontent.com/146378/69821822-feaad880-1204-11ea-9205-c33858ea45bf.png)

**Comment by Chocobozzz** [comment]
I tried but I did not reproduce :thinking:

**Comment by muesli** [comment]
@Chocobozzz Did you try reducing the window's size to a size that requires it to show a horizontal scrollbar? The white background starts as soon as you scroll to the right.

**Comment by Chocobozzz** [comment]
Arf sorry. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/cdbfd2b00324705a172a1985b8da218f1a67fc7d

**Comment by muesli** [comment]
Awesome, thank you!
