### ISSUE TITLE
Double entry at "add video to Playlists"

### ISSUE THREAD

**Issue by 6543** [Chocobozzz/PeerTube#1832]
Version: 1.3.0-rc.2

![Bildschirmfoto zu 2019-05-22 11-11-14](https://user-images.githubusercontent.com/24977596/58162556-b1acdf00-7c82-11e9-9261-7691c4b7cbdd.png)

I think it has to do with changes from
https://github.com/Chocobozzz/PeerTube/issues/1817

It apears:
1. Klik to "Overview"
2. Choos a Video
-> now you see a it twice at the add menue

what works now:
klik to sugested videos and the error disapears

**Comment by Chocobozzz** [comment]
Thanks @6543, it's fixed by https://github.com/Chocobozzz/PeerTube/commit/b6e342d5c6c265a93ad1cf63a00dcf6ececebede
