### ISSUE TITLE
Imported videos are missing 1080p versions

### ISSUE THREAD

**Issue by kerenon** [Chocobozzz/PeerTube#1834]
**What happened?**
Imported videos (by URL) are missing 1080p versions. Transcoding is enabled, 1080p is enabled in the settings/configs. Uploading the same video file, to the same server generates the 1080p file, just as expected, importing it, does not.

**What do you expect to happen instead?**
The server to generate all resolutions enabled in the config

**Steps to reproduce:**

1. Import any video by URL, with transcoding enabled, and 1080p selected

2. Wait for transcoding to finish

3. 1080p is missing

**Additional information**
* PeerTube version or URL: v1.3.0-rc.2
* NodeJS version:

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): https://pastebin.com/uNTZixzt
* Sample (upload): https://peertube.kerenon.com/videos/watch/17e17122-16a7-4254-b5b4-5585f188667f
* Sample (import): https://peertube.kerenon.com/videos/watch/7c45be4f-02f4-4014-b91e-fd113aeddb1b

**Comment by JohnXLivingston** [comment]
Last week I had the same problem with one of my user (peertube version 1.2.1). It was because the user didn't wait enough after uploading the video to youtube before importing it on my peertube instance. So the only available resolution on youtube was 360p. Retrying later worked.
Perhaps you have the same issue ?

**Comment by kerenon** [comment]
No. All transcoding jobs have finished, all other resolutions are available for playback. The 1080p versions are simply not generated.

**Comment by kerenon** [comment]
OK, I'm not sure what's happening. I had a test video. It's been on youtube for months. Imported it using the import feature, and the 1080p version is missing. Downloaded the same video, uploaded it back to my webserver root, imported it again into peertube, and now it has an 1080p version.

**Comment by kerenon** [comment]
Found the culprit. It seems youtube had/has some backend problems. Right now i'm still unable to download some of my own videos. The import works from everywhere else, so I'm closing this for now.
