### ISSUE TITLE
Cannot find channel

### ISSUE THREAD

**Issue by chopin2712** [Chocobozzz/PeerTube#1835]
**What happened?**
I was watching an interesting video when I was logged out (on another instance), so I decided to log in at my instance (https://peertube.nogafa.org). I just search the channel, I didn't find it (just a clone, not on the same instance, and not all videos were on; obviously not the original), I search the exact name of the video, nothing too, the instance, trying to copy and paste the URL, but I had an error 404 (not found). After that, I supposed it is a bug so I tried to search 2 another's channels with 3 different instances. And yes, I didn't find it with the exact same name on every instance. 

**Steps to reproduce:**
1. Open 3 new tabs with the following URLs :
- https://peertube.mastodon.host/
- https://peertube.nogafa.org/
- http://sikke.fi/
2. Search in the search bar, one after one : 
- chopin
- chocobozz
- L'école du chat noir
- L'ANARCHIE C'EST PAS CE QUE TU CROIS (épisode n°2)
- ecoleduchatnoir_channel@sikke.fi
3. You can see that you don't have the same results on the 3 tabs, and you didn't find the correct item.

**Additional information**

PeerTube version or URL: 

- https://peertube.mastodon.host/
- https://peertube.nogafa.org/
- http://sikke.fi/

Browser name/version: Firefox latest

NodeJS version: ???

**Comment by chopin2712** [comment]
PS : same thing with framatube.org

**Comment by Zig-03** [comment]
What's the instance name that the video you were watching was uploaded on? It could be that these three instances don't follow the instance hosting the video you were watching.

**Comment by chopin2712** [comment]
> On what instance was uploaded the video you were watching? It could be that these three instances don't follow the instance hosting the video you were watching.

The video was uploaded on sikke.fi

**Comment by Zig-03** [comment]
https://peertube.mastodon.host/ and https://peertube.nogafa.org/ instances don't follow the http://sikke.fi/ instance, this is why you couldn't watch that video from any of these two instances.

**Comment by chopin2712** [comment]
> https://peertube.mastodon.host/ and https://peertube.nogafa.org/ instances don't follow the http://sikke.fi/ instance, this is why you couldn't watch that video from any of these two instances.
> Every instance can choose to follow any other instances they like, thus the different search results.

Sorry for the late answer, but I don't understand why it didn't follow and why I can't find my channel on other channels.

**Comment by Zig-03** [comment]
This is what "decentralized" means. Every instance does whatever it wants. Some instances decided to follow the instance where your channel is at, others decided to do otherwise.

**Comment by chopin2712** [comment]
> This is what "decentralized" means. Every instance does whatever it wants. Some instances decided to follow the instance where your channel is at, others decided to not follow it.

Ok but If me I want to create an instance, do all instances will be followed by default?

**Comment by Chocobozzz** [comment]
No, each administrator decides what other instances they want to follow. When you setup your instance, nobody follows your instance and your instance does not follow other instances.

See https://docs.joinpeertube.org/#/admin-following-instances

**Comment by chopin2712** [comment]
> No, each administrator decides what other instances they want to follow. When you setup your instance, nobody follows your instance and your instance does not follow other instances.
> 
> See https://docs.joinpeertube.org/#/admin-following-instances

So there are no instances who follow all other instances? If I want to sign up to an instance just to subscribe, like and comment, how can I do it?
