### ISSUE TITLE
Encourage users to upload video format that needs no transcoding

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1836]
Followup issue for #1785. If the video matches some criteria (eg correct codecs, acceptable bitrate), Peertube does not need to transcode it. This saves a lot of transcoding time. We should encourage users to upload their videos in this format. Video import should also be configured to prefer this format.

The specific criteria are [here in the code](https://github.com/Chocobozzz/PeerTube/blob/develop/server/helpers/ffmpeg-utils.ts#L190). Most of it is pretty straightforward, but the maximum video bitrate depends on the video resolution and framerate of the video.

**Comment by Chocobozzz** [comment]
This is not something we would like to implement in PeerTube core to not overload the UI with information that most users do not understand. This is not a bad idea for some instance, though. I think a peertube plugin would be a way to implement your idea.
