### ISSUE TITLE
Updating video from private to public does not generate public mastodon status

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#184]
Hello,

This problem is possibly linked with #183 
Using https://peertube.drycat.fr as peertube server
Mastodon user is @lecygnenoir@peertube.drycat.fr

When I update a video to made it public, the user does not show a public status.

There is a new status (status number increments) but it is not visible for subscribers.

To reproduce : 
 - upload video in private status
 - publish video once uploaded still in private status
 - edit video to set public status
 - the user has no new public status :-)

Thank you!

Regards,

**Comment by Chocobozzz** [comment]
I need `peertube.drycat.fr` logs. Please ask you administrator to send me the log file by email.

**Comment by LecygneNoir** [comment]
No problem I'll see with him, thank you!

**Comment by LecygneNoir** [comment]
Hello @Chocobozzz 

I join the server log : 
We have tried to upload a fresh video, in private status, then edit it to public status after publishing.

The new video id (to identify in the log) is : https://peertube.drycat.fr/videos/watch/439d83c9-8a9d-43ee-bb25-151cb527bbba

Hope it could help :-)

[drycat_peertube.log](https://github.com/Chocobozzz/PeerTube/files/1611662/drycat_peertube.log)

**Comment by LecygneNoir** [comment]
I should add that last errors (about the "Unknown replied comment") is out of scope : I mention the peertube account inside a direct message for the admin, and so I guess it is normal that peertube found no reference about it ^^'

**Comment by Chocobozzz** [comment]
Should be fixed: https://github.com/Chocobozzz/PeerTube/commit/9fb3abfdac5c4bffe9992a457e5210d3aa743952

Thanks for the report!
