### ISSUE TITLE
Playlist iframe/Embed

### ISSUE THREAD

**Issue by filmaidykai** [Chocobozzz/PeerTube#1841]
**What happened?** trying to find solution how to share playlist with embed/iframe

**Steps to reproduce:**

1. I done playlist for test https://peertube.servebeer.com/my-account/video-playlists/c3f91f70-bdb5-415b-a374-b1bca14bc0dd so if you are not register on this instance you cant see it

2.If I share it like this link so you can see it https://peertube.servebeer.com/my-account/video-playlists/c3f91f70-bdb5-415b-a374-b1bca14bc0dd

3.so what I want to ask possibe to make proper iframe/embed like for single link https://peertube.servebeer.com/videos/watch/8366c5a7-b8cd-4e5a-8e2a-366e209003be

**Additional information**
* PeerTube version or URL: PeerTube v1.3.0-rc.1
* Browser name/version: Any

**Comment by bristow** [comment]
I saw that the new version 2.1 added the sharing of a link to a playlist, it's a very good start!

Having an embed code for a playlist would be very useful from a pedagogical point of view for our courses and training materials.

So, a big plus 1 for this improvement :)

**Comment by xmgz** [comment]
yes, it's a good point.

it'd be nice if in future releases this issue  is taken into consideration: playlist iframe(d).

thank you!

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/3038
