### ISSUE TITLE
blank page when blocking all JS

### ISSUE THREAD

**Issue by Zig-03** [Chocobozzz/PeerTube#1842]
When you visit a peertube instance while blocking all JS all you see is a blank page. I think we should change that and show at least some text like "Please enable JavaScript to view this PeerTube instance". 

Ideally a user should be able to navigate the website at least at a basic level, but this is a different issue and is being discussed here https://github.com/Chocobozzz/PeerTube/issues/917

Update: There is actually a warning _"You are blocking Javascript, and we totally get that. However..."_ but it isn't triggered when blocking JS via custom uBlock origin rules. So I assume it is a uBlock Origin issue. Closing.

**Comment by bkil** [comment]
Yes, it is an interference in browser plugins. It partially reevaluated `<script>`'s to be able to enable inline scripting, and (sometimes?) this causes `<noscript>` to not trigger on a page.

A developer can work around this issue by not using `<noscript>` for full unblanking, but rather just use progressive enhancement. It works for me, but I haven't decided whether this should be considered  a recommended web development practice or an ugly hack.

An example would be to use CSS to make the JavaScript-only layout hidden and the noJS text visible at the start, and then flip that rule (or remove a class on `<html>`, etc) with a single line of JavaScript in `<head>`.

Actually, this kind of makes sense if you consider that selective JavaScript blockers exist that only block certain JavaScript files or snippets (see LibreJS or some tracker-related blockers might also exist) In such a case, using `<noscript>` is not a binary all on nothing question - it really boils down to whether your script got executed or not. Which is precisely what progressive enhancement was invented for.
