### ISSUE TITLE
How does "muting" function?

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#1844]
When a user or instance is muted, what is functionally happening? How does this compare with suspension in Mastodon based software?

**Comment by realityfabric** [comment]
From what I can tell (as a user):

**When Muting:**
- causes a red badge to appear on their profile *(there is a bug where it disappears on refresh, see #1748)*

**Viewing from Pages:**
- Account Page: Videos Hidden
- Local Page: Videos Hidden
- Subscriptions Page: Videos Hidden
- Trending Page: Videos Hidden
- Overview Page: Videos Visible *(this seems like a mistake, is there an issue submitted for this?)*

**If muting a user you are subscribed to:**
- hides videos from your subscriptions page
- does not unsubscribe you from their channel *(this is good imo)*

Tested with Open.Tube on Firefox 60.7.0esr.

**Comment by realityfabric** [comment]
Forgot to mention:
- hides channel avatars
- does not hide channel comments *(this is bad imo)*

**Comment by realityfabric** [comment]
**If an instance mutes an account:**

- no videos from the account will be listed on their profile (when viewed from the muting instance)
- videos can still be watched from the muting instance, as if they were private videos.

v1.4.0-rc.1, Chrome 76.0

I'd be curious to know if this behavior is consistent with when an instance mutes an instance.

**Comment by Chocobozzz** [comment]
Documented in https://framagit.org/framasoft/peertube/documentation/commit/0cc88bd761b8e62ccc4225c92e536f7f50c45692
