### ISSUE TITLE
Allow uploading a new version of a video

### ISSUE THREAD

**Issue by 12people** [Chocobozzz/PeerTube#1845]
I've been wanting to create videos summarizing certain topics that are continually updated as more news on the topic comes in. This is unusual for videos, as Youtube has never allowed such a thing, but common for blog posts.

I would really appreciate an "Upload new version" feature, which would replace the video in question with another video, maintaining the same link and the same comments. Older versions could be archived and available from a screen listing previous versions.

**Comment by Krafting** [comment]
good idea!

**Comment by dedesite** [comment]
+1. I've got this problem with Youtube also. For example, I uploaded a video, then share it with a link and then realize that I forgot something or that something was wrong in the "cut" etc. On youtube, you need to upload a new video and share the new link, which is a shame for "marketing".

**Comment by Chocobozzz** [comment]
Video file updates are generally not allowed because there can be abuses: for example a viral cat video can be replaced with some kind of propaganda etc. We could however add the ability to specify a link to the new version of the video, so users are redirected with a confirm modal: *A new version of this video is available, would you like to watch it?* or something like that.

**Comment by dedesite** [comment]
> Video file updates are generally not allowed because there can be abuses: for example a viral cat video can be replaced with some kind of propaganda etc.

Oh, I never though about that ! That's kind of a problem indeed.

> We could however add the ability to specify a link to the new version of the video, so users are redirected with a confirm modal: _A new version of this video is available, would you like to watch it?_ or something like that.

It seems to be a great idea :D

**Comment by 12people** [comment]
@Chocobozzz 

The downside I see with a redirect dialog is that, by submitting a new version, you suddenly lose all conversations under a video as well as all ratings. The uploader then has to make a choice whether correcting a simple fact in a video or adding new content as an update on a situation is worth losing all of that.

I agree that there is potential for abuse. The way that social networks have dealt with this is by adding an "Edited" date to the post. The way blog posts often deal with this is by prefacing content with details on what was changed and how.

I think that, if it was clearly stated under the video when the latest version was uploaded, and older versions of the video were still accessible from an "Older versions" page, that would go a long way toward curbing abuse

Along with that, instance admins could have a rule against uploading new versions that vastly differ from the original, and abuse of that rule could be treated the same way as rules against spam, porn, and offensive content. As older versions would be publicly accessible, anyone could report abuse.

**Comment by therahedwig** [comment]
Perhaps you could send a notification to users who liked and did other things to the video(like adding to a playlist, commenting) whenever the video updates. Maybe have a user config option that if they'd like every update will invalidate the actions they did with it(might need some coordination with other Fediverse software). This is mostly necessary for likes and playlists, comments might do with 'this was for an older version of the video' added to them...

For embedded things, what you could do is that an embedded video will try to point at the version that is at the moment of embedding the last, and that getting the latest version always will explicitely require using a specific url or option or something. That way embeds that are pointing at a viral cat video will keep pointing to the cat video and not to the update with questionable content, while embeds that the embedder explicitely wanted to point at the last version(like the creator's blog) will use the last possible version.

Maybe take a look at how other Fediverse stuff implements updates. Like, Mastodon doesn't, but I recall others do handle updates.

**Comment by silvernode** [comment]
Maybe there can be multiple additional uploads to a single video page that you can add on later. They just autoplay in sequence of the upload date to make 1 stream of content.

**Comment by lsde** [comment]
While I understand concerns regading video authenticity, there should be a method for an admin to replace a video though.. Maybe just a script to do it manualy?

From my poking around it should be something like:
- manually create a new torrent and infoHash from a new file as per:
https://github.com/Chocobozzz/PeerTube/blob/29d4e1375fdac88595347184c3d1b214804794b0/server/models/video/video.ts#L1816
- update "videoFile" set infoHash="blabla" where "videoId"=5537; (also other fields if necessary)
- replace an original file with a new version in data/videos

Im I right or is something missing? @Chocobozzz 
thx

**Comment by Chocobozzz** [comment]
@lsde Admins can already do it: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#create-import-video-file-jobjs

**Comment by lsde** [comment]
Aha! thx @Chocobozzz

**Comment by fflorent** [comment]
> @lsde Admins can already do it: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#create-import-video-file-jobjs

@Chocobozzz It doesn't seem to work anymore. Should I create a dedicated issue?

**Comment by Chocobozzz** [comment]
Yes please with server logs, job logs, CLI options and video mode (HLS or not?)

**Comment by fflorent** [comment]
My issue is now fixed, the new video file replaced the old one.

As I use Docker, might be fixed thanks to https://github.com/Chocobozzz/PeerTube/issues/2613

**Comment by hexydes** [comment]
You could make this an administrator option. For example, I might want to run a community with limited creators where there is a lot of moderation of the content (and user uploads turned off by default). In this case, it might be a HUGE draw to getting creators on the instance over YouTube, where replacing your video is basically a death-sentence for traffic.

Definitely understand the potential for abuse, and on a wide-open instance it's a terrible idea. But I can definitely present a case where it'd be a huge benefit and attraction point over YouTube.

**Comment by jeena** [comment]
I think at least a error message in the UI when a video upload failed would be a good first step. I was confused for hours about it because the UI just goes back to the "Please choose a file" state and then I thought I accidentally closed the tab (uploading takes about one hour and I keep using my browser). But when I looked in the browser console there are error messages about it. The wifi seems really flaky here at the hotel so it happens often that I need to reupload a video 5 or 7 times before it really appears on my instance. This means a full day of trying to upload a 20 minutes video over and over manually.

![error](https://user-images.githubusercontent.com/151764/99893276-50bff600-2cc1-11eb-8641-91adf271f16d.png)

**Comment by fenarinarsa** [comment]
@Chocobozzz
Note that all professional services allow uploading a new version of a video (like Vimeo and all private SVOD services).
This is not allowed on YouTube on YouTube for the reasons you already listed.

IMO it should be possible to do that from the web interface for the administrator and a selected group of users (maybe a new role?)

**Comment by kontrollanten** [comment]
@Chocobozzz Would you accept a PR where it's possible to upload a new version in the web interface, a feature that the admin has to enable by config or web interface?

**Comment by SimplyCorbett** [comment]
I personally wouldn't want my users to be able to replace videos; too many possibilities for abuse. But linking to a new video would be fine with me.

**Comment by kontrollanten** [comment]
> I personally wouldn't want my users to be able to replace videos; too many possibilities for abuse. But linking to a new video would be fine with me.

Our case is different since we know all the users allowed to upload videos. But it may be possible to have a solution where the admin can choose between allowing users to do either a "hard" and "soft" replacement, where the former means replacing the video and the latter linking to a new video.

**Comment by jeena** [comment]
I also know every single user on my instance personally because it is a family instance. I would also appreciate a way for my dad to reupload a new version if he can fix some audio issues later, etc.

**Comment by fenarinarsa** [comment]
> I personally wouldn't want my users to be able to replace videos; too many possibilities for abuse. But linking to a new video would be fine with me.

As I said before it's allowed on nearly ever pro or pay SVOD/streaming service.

IMO it should be possible to do it, but it also must be possible to enable it or disable it for a whole instance or per user.

At the very least, the admin should be able to do it for any video from the UI.

**Comment by telemillevaches** [comment]
My organisation is transitioning from Vimeo Pro to Peertube, and we depend on this feature for our workflow. Use cases : 

1. a work in progress is published for review in private mode, then updated several times before the final version is approved and made public, all on the same URL.
2. a film is published and made public just in time for its deadline, and later improved or corrected, once the URL is known in the wild.

I would suggest, as a minimum : 
- make it an option for administrator to enable "replace videos" at instance level
- if enabled at instance level, moderators are granted to do it and may grant any user to do it
- with defaults to "disabled"

**Comment by lstamellos** [comment]
I also believe that replacing the video file with a new version in the same URL/ID via the web inteface should be possible. It is a feature very helpful to content creators and has a lot of legitimate use cases to support it, as was explained above. 

Abuse cases should be dealt with by moderators. And the audience can help by submitting reports in case the video was substantially altered in a malicious manner. 

Also, there could be a mechanism that, in order to replace the video with a new version in the same URL, you would have to keep the original video file too, otherwise the new video gets a new ID/URL. This would help uncover and prove malicious intent and also function as an "extra cost" for the editing that would discourage abuse.

**Comment by gilou** [comment]
Hi, it seems it's indeed "easy" to achieve using the CLI, but maybe it'd be good to have the option in the UI, the main use-case I'm considering here is to upload a proper edition of the live video after a live show, so we can keep the same URL both for the live and the playback!

**Comment by Chocobozzz** [comment]
Video edition is being implemented in https://github.com/Chocobozzz/PeerTube/pull/4805

So I'm renaming this issue to only keep the "upload new version" feature

**Comment by fenarinarsa** [comment]
> Hi, it seems it's indeed "easy" to achieve using the CLI

As a matter of fact, I've never succeeded to make it work correctly.

Currently in 4.2 the import job + transcoding jobs are successfully created (with two command lines) but once done, the video is not replaced.

In previous versions I often ended up with errors while trying to play videos, or sometimes with video qualities I never asked for.

**Comment by lcaylat** [comment]
Hi,
Since the Studio function already exists, it is possible to hijack it to replace a video by uploading the new version as credits and cutting the old version at 0 seconds.
It would still be nice to have an official video replacement feature rather than hijacking the Studio feature, wouldn't it?

**Comment by lonesomewalker** [comment]
I still wonder why this simple feature is still discussed...? (and not solved)

I also have now to make the decision between Vimeo and Peertube.
Since i like open source software, i would have chosen Peertube.
But under this circumstances... i mean, yes, with the credits hack it is possible to "cheat" this.
Is it that hard to let users replace their own videos with different ones?

**Comment by lonesomewalker** [comment]
Already asked at Framasoft, no response so far :P
Yes, there were other solutions, but since PeerTube has quite an active community... was not a hard choice so far ;-)

**Comment by Chocobozzz** [comment]
Hi,

This feature is planned in our 2023 roadmap: https://joinpeertube.org/news/roadmap-v6
If you want to help to fund this feature, you can make a donation on https://support.joinpeertube.org

**Comment by Chocobozzz** [comment]
This feature has been implemented in https://github.com/Chocobozzz/PeerTube/commit/12dc3a942a13c7f1489822dae052da197ef15905 and https://github.com/Chocobozzz/PeerTube/commit/f42fcb4b58f146c2e5ace236548a99d361ade55f. It will be available in PeerTube 6 planned at the end of the year 🎉

It has to be explicitly enabled by the admin:

![screen_2023-10-12-16_15_56](https://github.com/Chocobozzz/PeerTube/assets/5180488/de7eb950-95cd-4b7f-96e7-1d48cde911fe)

The update file button is available in the video update page:

![screen_2023-10-12-16_16_31](https://github.com/Chocobozzz/PeerTube/assets/5180488/fd6bcd58-ba7b-42df-89b4-5057b576ead9)

We display the date where the video has been re-uploaded below the video player:

![screen_2023-10-12-16_17_25](https://github.com/Chocobozzz/PeerTube/assets/5180488/a8bf5db5-1b69-432c-bb54-723345895ac1)

Transcoding runs again with the current instance transcoding settings, and not using the video current state (can be a feature request). The replace video file button has not a beautiful UX, but we plan to redesign the video management page next year (update/studio/stats etc).

**Comment by EricGuic** [comment]
Hi, thanks for this great features.
I understand that if the instance is set to transcode only HLS, and we have manually trigger a webtorrent transcoding, then the replacement will only create new HLS files, but not new webtorrent, right ?
If so, I would have to manually delete the old webtorrent files and trigger a new transcoding, right ?

Is the name of the new uploaded files correctly displayed in the Edit section ?

If I can make a suggestion : it would be great to have a prompt during the process to ask the user the reason of the replacement, and to store this info in database and display it next to the re-upload date.
