### ISSUE TITLE
Texts in brackets are not displayed in short video description

### ISSUE THREAD

**Issue by roipoussiere** [Chocobozzz/PeerTube#1847]
**What happened?**

It seems that everything in brackets `[...]` is not rendered in short video description, but appears when we extend the description.

**What do you expect to happen instead?**

Texts in brackets should be rendered in the short description.

**Steps to reproduce:**

Open this [this video](https://tube.postblue.info/videos/watch/4c5214e1-eb91-4716-abe2-aa5aa81b4d18), and read the description:

> Le seul **son peut** s’écrire de 12 manières différentes

Then click on *Show more* button and read again:

> Le seul **son [s] peut** s’écrire de 12 manières différentes

**Additional information**

* PeerTube version or URL: https://tube.postblue.info
* Browser name/version: Firefox 66

I'm not the owner of the instance above so I can't provide server-side information.

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/f5b72c3937c721258c569ee783503adb379c42ab
