### ISSUE TITLE
Hide front page menu burger box

### ISSUE THREAD

**Issue by valinux** [Chocobozzz/PeerTube#1849]
**What happened?**
I want to be able to hide the opened menu burger box.
**What do you expect to happen instead?**
be able to be flexible with new themes and able to edit front end a bit easier.

**Comment by Chocobozzz** [comment]
Could you explain your use case?

**Comment by Chocobozzz** [comment]
You can hide the menu using something like:

```
document.querySelector('my-menu').style.display = 'none'
document.querySelector('#content').classList.add('expanded')
```
