### ISSUE TITLE
Peertube interface should show "mastodon" subscribers

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#185]
Hello,

I have noticed that when people subscribe to the mastodon account linked to peertube, peertube itself does not show these subscribers.

Here I have 0 subscribers on Peertube vs 6 subscribers on the mastodon account :  

  - ![Subscribers from peertube](https://user-images.githubusercontent.com/7755000/34663699-511a82d6-f458-11e7-8e5f-76411b10dd44.png)  
  - ![Subscribers from Mastodon](https://user-images.githubusercontent.com/7755000/34663709-619bad2e-f458-11e7-87f2-c68c30df824b.png)

I do not know if possible, but I think Peertube should show mastodon subscribers? Or subscribers in Peertube is dedicated to Peertube instances?

And again (I'lll never say it enough) thank you for this project!

Regards

**Comment by ReK2Fernandez** [comment]
@LecygneNoir how do you link a already mastodone account to one in peertube? Im interested in this. thanks.

**Comment by Bat41** [comment]
@ReK2Fernandez search for the complete user id (like `foo@bar.com`)

**Comment by LecygneNoir** [comment]
@ReK2Fernandez Yep at the moment you cannot link a account, but you can search for the peertube name in any federated instance, and you should see the peertube account like a mastodon one.
And thus have the possibility to follow it, answer its comments, ...

Possibility to link and/or manage this account inside Mastodon is I think pretty complicated at the time, but perhaps will be possible (open a new feature?)

**Comment by ReK2Fernandez** [comment]
@LecygneNoir ok thanks, I just got confused by the original post, I already know I can friend a peertube user, but though after reading above that we could "link" them so when I post a video it comes out of the o ther user status.. but I guess not..

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/32b2b43c06621e384c0bd1610ef0bb9f23399be7
