### ISSUE TITLE
Error when search string contains @

### ISSUE THREAD

**Issue by AutomCoding** [Chocobozzz/PeerTube#1853]
**What happened?**
I typed an @ in front of a username I was searching for, which resulted in an error message popping up.

![username-search](https://user-images.githubusercontent.com/40275136/58439977-69a11880-80d7-11e9-85f8-fe6f9a7312d3.png)

**What do you expect to happen instead?**
A search should not result in an error, perhaps except when an ASCII control character, emoji modifier or similar is in the search string. Since usernames often are displayed preceded by an @ symbol in the Fediverse, it is quite probable a visitor will put an @ in front of a username in the search form.

**Steps to reproduce:**
1. Serarch for anything containing an @ symbol

**Additional information**
* PeerTube version or URL: PeerTube v1.3.0-rc.2
* Browser name/version: Firefox 67.0
* Browser console log:
Backend returned code 500, errorMessage is: Serverfel, försök gärna igen om en stund. main.7bdce30d73632e5344c5.js:1:481228
    handleError https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    searchVideoChannels https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    error https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    _error https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    error https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    _error https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    error https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    _error https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    error https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    notifyError https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    _error https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    error https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    _error https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    error https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    notifyError https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    _error https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    error https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    o https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    _trySubscribe https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    subscribe https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    f https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    i https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    error https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    s https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    invokeTask https://peertube.social/client/sv_SE/polyfills.2981491f4ede2518a62c.js:1
    onInvokeTask https://peertube.social/client/sv_SE/main.7bdce30d73632e5344c5.js:1
    invokeTask https://peertube.social/client/sv_SE/polyfills.2981491f4ede2518a62c.js:1
    runTask https://peertube.social/client/sv_SE/polyfills.2981491f4ede2518a62c.js:1
    invokeTask https://peertube.social/client/sv_SE/polyfills.2981491f4ede2518a62c.js:1
    m https://peertube.social/client/sv_SE/polyfills.2981491f4ede2518a62c.js:1
    b https://peertube.social/client/sv_SE/polyfills.2981491f4ede2518a62c.js:1

**Comment by Chocobozzz** [comment]
Thanks for the issue @AutomCoding. It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/c56b774d0594bb33917a9f1080deb2b8814079d7
