### ISSUE TITLE
Support LBRY

### ISSUE THREAD

**Issue by ghbjklhv** [Chocobozzz/PeerTube#1854]
**Feature**: Support LBRY videos.
**Why?** LBRY is already utilized by many popular content creators like [@KhanAcademy](https://beta.lbry.tv/@KhanAcademy/), [@lunduke](https://beta.lbry.tv/@Lunduke/), [@MinutePhysics](https://beta.lbry.tv/@MinutePhysics/), [@TheLinuxGamer](https://beta.lbry.tv/@TheLinuxGamer/), being some of the more notable additions.
Adding support would make it so that users wouldn't need to switch protocols to view these.
**How?** I would recommend utilizing [lbry.tv](https://beta.lbry.tv/) as this would make it so that every PeerTube instance wouldn't need to install the LBRY client. 

Other [Fediverse](https://www.wikipedia.org/wiki/Fediverse) applications do something similar, like [Friendica](https://www.wikipedia.org/wiki/Friendica#Features) supports [diaspora*](https://www.wikipedia.org/wiki/Diaspora_(social_network)), [Quitter](), [GNU Social](https://www.wikipedia.org/wiki/GNU_social), among others.

________________
Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/74726521-feature-support-lbry)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

**Comment by Chocobozzz** [comment]
They just have to support ActivityPub to communicate with PeerTube instances
