### ISSUE TITLE
Opt-In anonymous player statistics

### ISSUE THREAD

**Issue by unfa** [Chocobozzz/PeerTube#1855]
One thing I miss in PeerTube is analytics.

Analytics are a great tool for content creators to see how their work performs, and how they can improve it.

I believe there is an ethical and transparent way to do this.

For example - the users could get a checkbox for "Sending anonymous statistics".

This should be only opt-in, so nobody is going to be using this by default, but I guess it'd be good to make people understand that enabling this will help creators improve their content.

What do you think?

**Comment by Zig-03** [comment]
https://github.com/Chocobozzz/PeerTube/issues/1385

**Comment by Chocobozzz** [comment]
@unfo Could you explain/make a list of what are these "statistics"?

**Comment by unfa** [comment]
I'm @unfa  :D

It'd be a list of things about the viewer:

1. Coarse location (country, city if possible)
2. Viewing OS (Linux, Mac OS X, , iOS, Windows, Android, other?)
3. What parts of the video were played? What parts were replayed? What parts were skipped? On YouTube this is known as viewer retention. YouTube shows both an absolute and a normalized curve for this (difference from an overall average on the whole platform I guess).
4. Viewer origin (search box? direct link? "featured page"? linked from another video? Linked from a comment?)
5. Did the viewer subscribe the channel while/right after watchig this video?
6. Did the viewer click on "Support" while/right after watching this video?
7. Did the viewer watch another video from the same channel after this one?
8. Did the viewer check any links provided by the author of the video?

I don't know how many are possible to track.
The viewer retention and location are probbly the most useful ones.
The viewer retention allows the creator t osee what parts engaged the viewers the most, and what parts made them skip or quit viewing. With a lot of views this data can reveal some problems in the creative process and help creators "debug" their work.

The other starts would show overall engagement and interest the video caused in the viewers - did they seek for more of my stuff? Did they engage in comments or other feedback? Did they share the video?

This helps creators see which videos of theirs worked best (despite the obvious view count) - it helps them see when they do great content, so they can learn from that experience.

**Comment by TILvids** [comment]
Sorry to drag up a zombie, but I'm running into this hard. I don't even need user-level analytics (i.e. location, device, etc), I just need video-level statistics. Things like views over time, retention during viewing, etc. This lets me know which types of videos I should be finding more of, less of, advice to give creators about length of video, etc. I don't need to know anything about my users, but I definitely would like to know, in aggregate, what is happening with videos so that I can improve the quality of content on the site.

**Comment by unfa** [comment]
I understand features like this might go against FramaSoft's idea of "not messing with the creation dynamic" - but a lot of content is made for an audience, and knowing how the audience interacts with the content helps creators satisfy their audience better.

As a creator I don't find much satisfaction in making stuff nobody enjoys. I do it for others, not myself. And the best reward I get is seeing that what I made has value for others - such anonymous analytics are helpful in understanding what the viewers like.

**Comment by Chocobozzz** [comment]
Hello,

We added some video stats in [4.2](https://joinpeertube.org/news#release-4.2). I suggest to create dedicated issue if you need other metrics.
