### ISSUE TITLE
Audio truncated

### ISSUE THREAD

**Issue by kerenon** [Chocobozzz/PeerTube#1857]
**What happened?**

Uploading any audio file, and pressing "Publish" before the transcoding process finishes, kills the transcoding thread, and the resulting file is a truncated version of the original upload.

**What do you expect to happen instead?**

Transcoding to finish

**Steps to reproduce:**

1. Upload any kind of audio file (I've tried Flac and mp3)

2. Wait for the upload to finish

3. Press publish before the transcoding thread finishes

**Additional information**
* PeerTube version or URL: git develop (e6b04e0e796c1b36d15fbe732e89ef4820dcabd9)
* Browser name/version: Chrome/Firefox/Edge latest
* NodeJS version: v8.16.0

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): https://pastebin.com/Y06smxAH

**Comment by raphgilles** [comment]
Same issue for me !

**Comment by Chocobozzz** [comment]
This issues has been fixed. See https://github.com/Chocobozzz/PeerTube/issues/2153#issuecomment-543696178 :)
