### ISSUE TITLE
On mobile, going full screen should automatically switch screen to landscape (with a button to switch back to portrait) 

### ISSUE THREAD

**Issue by christophehenry** [Chocobozzz/PeerTube#1858]
Défaut behaviour of YouTube. Very useful. Most of videos are filmed in landscape. Going fullscreen currently displays videos with black stripes above and below the video. User has to pivot screen themselves.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/e98ef69d1c8d4e39e45a52b04b3abf5fd1af3b2c
