### ISSUE TITLE
PeerTube Storage Limit ?

### ISSUE THREAD

**Issue by MrTeeXD** [Chocobozzz/PeerTube#1862]
Hello, since this is my first issue with a Question which is, Does PeerTube have a Storage limit or is the Limit the Video Size?

**Comment by Zig-03** [comment]
Different peertube instances have different limits (quotas), for example this instance https://peertube.servebeer.com/about/instance has a video quota of 20 GB (2 GB per day) while this instance https://peertube.social/about/instance has unlimited video quota but has an upload limit of 500 MB per day. The full list of instances can be found here https://instances.joinpeertube.org/instances

**Comment by MrTeeXD** [comment]
Ohhhhhh so each server gets 2GB per day, thats crazy

**Comment by Zig-03** [comment]
Each user not server, and until one reaches the 20GB quota and only ont hat specific instance - https://peertube.servebeer.com. 
It seems like you're very new to PeerTube, take your time to read this F.A.Q. https://joinpeertube.org/en/faq

**Comment by MrTeeXD** [comment]
Yea, im kinda new so i will read the FAQ and will i no longer be able to upload if i reach the Quota?

**Comment by Chocobozzz** [comment]
>  i no longer be able to upload if i reach the Quota?

yes
