### ISSUE TITLE
Wrong video duration and no caps generated after upload

### ISSUE THREAD

**Issue by mrflos** [Chocobozzz/PeerTube#1863]
**What happened?**
Hello, for some reasons, the last videos uploaded on https://video.coop.tools
![image](https://user-images.githubusercontent.com/124845/58782211-3fbb8a80-85de-11e9-8855-2eaea3d227e5.png)

**What do you expect to happen instead?**
Real duration and screenshots!

**Steps to reproduce:**

if i download the video and re-upload it, it seems ok, but is there a way to avoid it?

**Additional information**
* PeerTube version or URL: Docker version 1.1.0 https://video.coop.tools
* Browser name/version: Mozilla Firefox 67
* NodeJS version: 

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Please send me one of the problematic videos

**Comment by mrflos** [comment]
hey @Chocobozzz ! Thanks for you help! I suppose you'll need the original one, i'm contacting the author, have a nice day and start of week!

**Comment by Chocobozzz** [comment]
Any news on this?

**Comment by mrflos** [comment]
nope..  
And i destroyed the instance meanwhile after upgrading to debian buster, so it's no more reproductible..  
I could bypass the problem by re-uploading the video, so nothing to worry anymore, i will close this issue.  

Cheers!
