### ISSUE TITLE
white page if no cookie allowed.

### ISSUE THREAD

**Issue by sletort** [Chocobozzz/PeerTube#1864]
**What happened?**
The peertube instance is a white page, no content displayed.

**What do you expect to happen instead?**
The site content should be readable.  
Or at least a message should appear explaining that cookies from this site have to be allowed.

**Steps to reproduce:**

1. do not allow cookie (only tested on firefox) (you should not already have cookie from the site)

2. go to a peertube instance.

**Additional information**
* PeerTube version or URL: V1.3.0
 https://video.calculate-linux.org/
 https://peertube.touhoppai.moe/

* Browser name/version: Firefox Quantum 67.0
* NodeJS version: don't know.

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by ealgase** [comment]
Works fine for me.
![image](https://user-images.githubusercontent.com/11603778/58922919-29f7b380-870b-11e9-9c39-41999ec3cd67.png)

**Comment by sletort** [comment]
Ok, that should comes from an extension. Indeed, on a fresh FF profile it works fine without cookie.
Already tested µbloc & noscript, not in cause.
I'll report when I found the pb.
thanks.
