### ISSUE TITLE
Use larger chunks for torrents

### ISSUE THREAD

**Issue by ealgase** [Chocobozzz/PeerTube#1865]
PeerTube currently uses 16kb chunks of videos.
![image](https://user-images.githubusercontent.com/11603778/58831045-bc1f8f00-8619-11e9-89fe-da45d23ba424.png)
However, HTTP requests have a non-insignificant overhead, and loading so many small chunks is a significant load on CPU, causing videos to stutter.  Increasing size to 2MB or so shouldn't cause any issues, will still allow almost anyone to seed videos, and will vastly improve the user experience.

**Comment by dedesite** [comment]
I have no deep knowledge in video streaming but a 2MB wouldn't increase the time to see the first image on screen ?
I mean, with 16kb chunk video can start quicker than with 2MB chunk which correspond roughly to ~15s of video (at 720p).

**Comment by ealgase** [comment]
2MB should download on almost any connection capable of streaming video smoothly in under 1s.

**Comment by Chocobozzz** [comment]
See https://torrentfreak.com/how-to-make-the-best-torrents-081121/

> After a number of years toying around, the optimum number of pieces seems to be between 1200 and 2200. Most torrent creators will only allow piece-sizes in multiples of 16kb, so you should, with few exceptions, find a size that fits in that range. A 700Mb torrent should be 512Kb pieces (giving 1400 total) and similarly, 350Mb would be better with 256kb. A 4.5Gb torrent would have 2,250 pieces, roughly, with a 2Mb piece-size. Or 1,125 with 4Mb. Either way would be fine, but 256kb pieces would mean 17,500+ pieces, and is too many.

I don't think we should modify the chunk sizes. The HLS player is the way to go (segments are larger).

**Comment by ealgase** [comment]
Really?  Most videos are a few hundred MB at least, so a 256KB size would make sense.

**Comment by Nutomic** [comment]
Does Peertube always use the same chunk size? It would probably make more sense to set the chunk size depending on the total video size.

**Comment by ealgase** [comment]
> Does Peertube always use the same chunk size? It would probably make more sense to set the chunk size depending on the total video size.

It appears to always use 16KB from all videos I've checked.

**Comment by JohnXLivingston** [comment]
If HTTP2 is enabled, i'm not sure there is a big overhead with small chunks

**Comment by ealgase** [comment]
There's still a decent overhead, and making that many requests slows down my browser (especially while using an extension like uBlock Origin that filters network requests).

**Comment by endokai** [comment]
This is definitely a clear difference. I can get a lot of improvements when accessing a single Full file after closing WebTorrent. I think at least several times the block size should be increased instead of just a few tens of kb. Any one know how to increase the torrent block size?

**Comment by endokai** [comment]
> I have no deep knowledge in video streaming but a 2MB wouldn't increase the time to see the first image on screen ?
> I mean, with 16kb chunk video can start quicker than with 2MB chunk which correspond roughly to ~15s of video (at 720p).

I don't know why you think so. Even if it's 100 g video files, the browser won't wait until it's downloaded. On the contrary, you won't get a speed boost after splitting the video file.

**Comment by ivan386** [comment]
>I don't think we should modify the chunk sizes. 

16 kb maximum chunk size is important only for bittorrent protocol because data and control messages in one stream. For HTTP GET can be used piece size or several pieces.

**Comment by Chocobozzz** [comment]
> 16 kb maximum chunk size is important only for bittorrent protocol because data and control messages in one stream.

Sure, and it's the reason why I don't think we should change the chunk sizes in the torrent.

> For HTTP GET can be used piece size or several pieces.

The sequentials blocks is an interesting concept. You could open an issue in the [webtorrent](https://github.com/webtorrent/webtorrent) repository.

**Comment by Chocobozzz** [comment]
Closing since the issue has been created on the webtorrent repository + we'll progressively switch to our now HLS player.
