### ISSUE TITLE
subscription button hidden by "Fanboy’s Annoyance List​​​​​​​​​" and "Fanboy’s Social Blocking List​​​​​​​​​"

### ISSUE THREAD

**Issue by bolikahult** [Chocobozzz/PeerTube#1866]
**What happened?**
Was impossible to see the subscribe button of any channel or account on any peertube instances. Disabling "Fanboy’s Annoyance List​​​​​​​​​" **and** "Fanboy’s Social Blocking List​​​​​​​​​" on ublock origin's options resolved the problem.
(I spent 30m understanding the problem, thinking on a new feature of manual aprovement for the videasts, etc...)

**What do you expect to happen instead?**
Enabling this lists should not disable the subscription feature. Subscribe a channel is not an annoyance, nor a social feature, on my mind...

**Steps to reproduce:**

1. install ublock origin on Firefox

2. add at least one of the 2 lists concerned on the filter page of ublock origin's options

3. try to subscribe a channel on Peertube

**Additional information**
* Browser name/version: Firefox 67.0

It appears that the lists are blocking various "shemes" recognized on webpages like "##.subscribe-button" (or others similar - finded on my local definition of the lists)

**Comment by Chocobozzz** [comment]
You'll have to contact the maintainers of these lists. We can't really do anything on our side.
