### ISSUE TITLE
Video available only by private link invisible in playlist

### ISSUE THREAD

**Issue by ufm** [Chocobozzz/PeerTube#1867]
Hi!

If you add a video that is available only by a private link in the playlist or change the existing in playlist video access to "only by link", the playlist will show that the video is in it, but will not be in the playlist itself.

Expect see video in playlist alvays.

peertube 1.3.0

**Comment by ufm** [comment]
How to reproduce:
1. Upload video
2. Set "Privacy" to "Only people with the private link can see this vieo"
3. Add video to any playlist ("Watch later", for example)
4. Enter into "Watch later" playlist

Playlist look like in attached photo 
![pict](https://user-images.githubusercontent.com/381111/59045774-62250080-8889-11e9-83dd-582a098dd025.png)

**Comment by bn4t** [comment]
Can confirm. Happened to me too.

**Comment by maxdrash** [comment]
Confirmed here too: v1.3.1
