### ISSUE TITLE
Open Graph informations missing on playlists

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#1869]
**What happened?**

When sharing a playlist on facebook (for exemple), we got this :

![image](https://user-images.githubusercontent.com/38844060/58911876-266b2900-8719-11e9-8702-5b2b2ef51993.png)

If I look the html, there is no opengraph element.

**What do you expect to happen instead?**

There should be open graph tags.

**Steps to reproduce:**

1. Paste https://www.yiny.org/videos/watch/playlist/35c6e28e-2bf3-4795-93b5-4967951b6bf5 on Facebook (or any other social network)

**Additional information**
* PeerTube version or URL: 1.3.0

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/2996
