### ISSUE TITLE
Double-clicking the video player should maximize it

### ISSUE THREAD

**Issue by bnjbvr** [Chocobozzz/PeerTube#187]
STR
===

- open any video page
- double click the video player

Expected
===

The video player should open maximized, i.e. the full window should contain the video.

Observed
===

(Firefox nightly user here) It doesn't do this. I wonder if the video player behavior's have been overridden? Anyways, it's a recurring behavior on many websites and I find it quite convenient. Could we have this for PeerTube please?

**Comment by rigelk** [comment]
It's because the 'video.js' player used doesn't feature this kind of functionality by default. However there are plugins for it, and a lot of people seem to go by [ctd1500/videojs-hotkeys](https://github.com/ctd1500/videojs-hotkeys).

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/d77014491b339b4dcfab95c05507dd5f579a6d7d
