### ISSUE TITLE
Change wording of "Video uploads require manual validation by moderators	"

### ISSUE THREAD

**Issue by ealgase** [Chocobozzz/PeerTube#1870]
All other fields are X when users are restricted and checked when users are not.  However, having manual approval is a restriction.

Currently:
![image](https://user-images.githubusercontent.com/11603778/58922978-835fe280-870b-11e9-9995-e37531058112.png)

Ideally (with same config):
![image](https://user-images.githubusercontent.com/11603778/58923017-c15d0680-870b-11e9-8b8e-e8a3cc339303.png)

**Comment by Jorropo** [comment]
I think both choice are bad and good in their own way (they both makes a judjment).
Personaly I think we should allways display the green validation and update the message, the actual one when this is on and the new proposition from @ealgase when this is off.

**Comment by Zig-03** [comment]
Why not substitute the icons with words (without colors):
:x:  - No
:heavy_check_mark: - Yes

**Comment by Jorropo** [comment]
@Zig-03 yes that way better than actualy because it remove the good/bad aspect.
I still find my idea more equal but your is more clear. (`no` even that just about somethings done are not done and not somethings implemented like with ❌ is still a little bit negative).

**Comment by bolikahult** [comment]
Other idea : make complete sentences for both option in each line concerned, example : 

Default NSFW/sensitive videos policy **are displayed** / **are not displayed**
User registration **is allowed** / **is not allowed**
Video uploads **require** / **don't require** manual validation by moderators
You **can transcode** / **can't transcode** your videos in multiple resolutions

No judgment ! :)

These lines could stay like that :
HTTP import (YouTube, Vimeo, direct URL...) | ✔️
Torrent import | ✔️
P2P enabled | ✔️
Video quota | ✔️

**Comment by Chocobozzz** [comment]
We changed how we display this information. It should be better now

![screen_2019-12-03-11:36:35](https://user-images.githubusercontent.com/5180488/70043701-388f2c80-15c1-11ea-8485-3ac7940646b2.png)
