### ISSUE TITLE
Incorrect legend when history is disabled

### ISSUE THREAD

**Issue by AutomCoding** [Chocobozzz/PeerTube#1871]
**What happened?**
The legend for the history toggle switch (page: /my-account/history/videos) reads “History enabled” when history is disabled.

![toggle-history](https://user-images.githubusercontent.com/40275136/58946761-dfb41800-8786-11e9-82b6-6b4abe1e8c5f.png)

**What do you expect to happen instead?**
The text should be replaced with “History disabled”. Alternatively, the text could be something along "Video history" and the toggle switch could talk for itself. I would prefer the latter, but any would do.

**Additional information**
PeerTube version or URL: PeerTube v1.3.0

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/349be1eaa9a61b2e2acaa24db58acb95774c0d20
