### ISSUE TITLE
Unable to save scheduled video on 1.3

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#1872]
**What happened?**
When I try to schedule a video, the "update" button does not work.
Clicking on it does nothing visually, and the browser console shows an error

```
ERROR TypeError: "can't convert null to object"
    onValueChanged https://videos.pair2jeux.tube/client/fr_FR/main.42204721eb4b57c97ccd.js:1
    forceCheck https://videos.pair2jeux.tube/client/fr_FR/main.42204721eb4b57c97ccd.js:1
    checkForm https://videos.pair2jeux.tube/client/fr_FR/28.84f5859e2f8387d89643.js:1
    update https://videos.pair2jeux.tube/client/fr_FR/28.84f5859e2f8387d89643.js:1
    O https://videos.pair2jeux.tube/client/fr_FR/28.84f5859e2f8387d89643.js:1
    handleEvent https://videos.pair2jeux.tube/client/fr_FR/main.42204721eb4b57c97ccd.js:1
    handleEvent https://videos.pair2jeux.tube/client/fr_FR/main.42204721eb4b57c97ccd.js:1
    Tg https://videos.pair2jeux.tube/client/fr_FR/main.42204721eb4b57c97ccd.js:1
    rm https://videos.pair2jeux.tube/client/fr_FR/main.42204721eb4b57c97ccd.js:1
    V https://videos.pair2jeux.tube/client/fr_FR/main.42204721eb4b57c97ccd.js:1
    invokeTask https://videos.pair2jeux.tube/client/fr_FR/polyfills.2981491f4ede2518a62c.js:1
    onInvokeTask https://videos.pair2jeux.tube/client/fr_FR/main.42204721eb4b57c97ccd.js:1
    invokeTask https://videos.pair2jeux.tube/client/fr_FR/polyfills.2981491f4ede2518a62c.js:1
    runTask https://videos.pair2jeux.tube/client/fr_FR/polyfills.2981491f4ede2518a62c.js:1
    invokeTask https://videos.pair2jeux.tube/client/fr_FR/polyfills.2981491f4ede2518a62c.js:1
    m https://videos.pair2jeux.tube/client/fr_FR/polyfills.2981491f4ede2518a62c.js:1
    b https://videos.pair2jeux.tube/client/fr_FR/polyfills.2981491f4ede2518a62c.js:1
```

When the video is set to private (without schedule), or public, the button works.

**What do you expect to happen instead?**
We should be able to schedule a video

**Steps to reproduce:**

1. Use an instance on Peertube 1.3

2. Upload a video, or edit an existing private video

3. Try to schedule the video. Once you have configured your schedule, it's not possible to save the modifications any more

**Additional information**
* PeerTube version or URL: Peertube 1.3 on https://videos.pair2jeux.tube
* Browser name/version: firefox 67.0

Bug confirmed on another instance: https://miaou.drycat.fr/web/statuses/102218463534286550

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): There is nothing inside the server logs. It seems to be localized inside internal JS on the browser.

Do not hesitate to tell me if more details are needed!

Thanks!

**Comment by l00ptr** [comment]
indeed I confirm I can reproduce this issue :)

**Comment by Chocobozzz** [comment]
Thanks for the issue. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/4adf26735fae8caeb8172c909afd0f3ca32d695f
