### ISSUE TITLE
Cannot import from youtube with 'New videos of users automatically blacklisted' enabled in 1.3

### ISSUE THREAD

**Issue by Midek** [Chocobozzz/PeerTube#1873]
**What happened?**
When trying to import video with URL after i turned on "New videos of users automatically blacklisted", i am getting an error:
```
Jun 05 16:22:30 peertube peertube[12307]:   "err": "TypeError: Cannot read property 'hasRight' of undefined\n    at Object.<anonymous> (/var/www/peertube/versions/peertube-v1.3.0/dist/server/lib/video-blacklist.js:20:18)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v1.3.0/dist/server/lib/video-blacklist.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/var/www/peertube/versions/peertube-v1.3.0/dist/server/lib/video-blacklist.js:3:12)\n    at Object.autoBlacklistVideoIfNeeded (/var/www/peertube/versions/peertube-v1.3.0/dist/server/lib/video-blacklist.js:17:12)\n    at /var/www/peertube/versions/peertube-v1.3.0/dist/server/controllers/api/videos/import.js:198:33\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v1.3.0/dist/server/controllers/api/videos/import.js:4:58)\n    at <anonymous>"
```
Video did not get imported.

**What do you expect to happen instead?**
Video to be imported successfully.
 
**Steps to reproduce:**

1. Turn on "New videos of users automatically blacklisted enabled"

2. Import any youtube URL (tried on https://www.youtube.com/watch?v=NyF-iyL7IsE for example)

**Additional information**

* PeerTube version or URL:
v1.3.0, https://tube.midov.pl/
* Browser name/version:
Chromium 74, Firefox 67, qutebrowser 1.6.2
* NodeJS version:
8.16
* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
https://cloud.midov.pl/s/bDQpLzm43g3SppE

**Comment by Chocobozzz** [comment]
Thanks for the issue @Midek 

Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/03371ad9d049bab79445a1b35da44cb1272f6c28

**Comment by JohnXLivingston** [comment]
When have you planned to release this fix ?
My instance is under a huge spam campaign, I had to close subscriptions. I'd like to enable the "automatically blacklist" feature, but my users need youtube's import.
Thanks
