### ISSUE TITLE
Missing download link for not logged in visitor

### ISSUE THREAD

**Issue by Darathor** [Chocobozzz/PeerTube#1874]
**What happened?**
On a version 1.3 instance, when I view, without being logged in, a video for which download is allowed, I don't have a download link available.

**What do you expect to happen instead?**
The link should appear as soon as the download is allowed, as was the case with version 1.2.

**Steps to reproduce:**
1. if you are logged on the instance, log out
2. open the detail page of a video for which downloading is allowed
3. note that no download link is available

**Additional information**
* PeerTube version or URL: 1.3 ( examples : https://thinkerview.video/videos/watch/75756f68-c0fa-4bc1-858f-5f0d6fb37f68 and https://videos.pair2jeux.tube/videos/watch/406fc3d3-ae3c-49c0-893e-18a27b8b6360 )

**Comment by Chocobozzz** [comment]
Thanks @Darathor 

This is fixed by https://github.com/Chocobozzz/PeerTube/commit/f238aec54f93bf6ef73ef17be23159ecd1d83f96

**Comment by Darathor** [comment]
\o/ 

Thanks for the fix!
