### ISSUE TITLE
Show real date/time additionally to / instead of relative time in metadata

### ISSUE THREAD

**Issue by IzzySoft** [Chocobozzz/PeerTube#1878]
For publication date, PT currently used kind of "Joda Time" only – i.e. showing how much time has passed since publication, like "Published 3 months ago". The real **date** is not shown anywhere. The older a video is, the less accurate this gets: say today I see a video "Published 2 years ago", the exact date could be anything in a frame of almost an entire year. Which I find really inconvenient (especially for technical documentations of e.g. a piece of software as I had no way to tell if the feature I'm looking for was already published when the video was made).

Would it be possible to at least embed that information into the `title` attribute? For example:

    <div _ngcontent-c11="" class="video-info-date-views" title="2019-03-24"> Published 3 months ago - 27 views </div>

That way it'd show on hover, which would be quite helpful.

Thanks in advance!

**Comment by Chocobozzz** [comment]
The date is now displayed on hover.

**Comment by IzzySoft** [comment]
Thanks a lot!
