### ISSUE TITLE
"500 MB (2 GB per day)" bug  and a small UI bug

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#1879]
**I've found 2 small issues on this page https://videofed.com/about/instance**:

1- it says _500 MB (2 GB per day)_ which is impossible because 500MB is maximum
2- next to that _500 MB (2 GB per day)_ is a question mark in a circle, when clicked it goes to the right and extends the browser, instead of opening normally.

**Additional information**
* PeerTube version or URL: 1.3
* Browser name/version: Firefox

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/34dd7cb4ca4807e61a8c1d584b047c2cb383fe5a
