### ISSUE TITLE
install requires node v 8

### ISSUE THREAD

**Issue by Falgn0n** [Chocobozzz/PeerTube#188]
Installing on _Debian 9 Stretch_ following the [guide](https://github.com/Chocobozzz/PeerTube/wiki/Debian-Jessie-production-installation-guide)

Command: `peertube@libre1:~/PeerTube$ yarn install`   
Error:   
```
yarn install v1.3.2
[1/5] Validating package.json...
error peertube@0.0.1: The engine "node" is incompatible with this module. Expected version ">=8.x".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I am tempted to update my node version, but worried that it might break something else. Just thought I should share this in the meantime, just in case there's something there.

(I realise the guide is for Debian 8 "Jessie", and not for Debian 9 "Stretch", which is what I am installing on)

**Comment by Chocobozzz** [comment]
Yes, we require Node 8. I updated the wiki.
