### ISSUE TITLE
Add an option to displays videos to registered users only

### ISSUE THREAD

**Issue by armandfardeau** [Chocobozzz/PeerTube#1884]
I was wondering if it's possible to add an option to allow users to list and watch videos only if they are registered.

My need is that I would like to make an instance to share videos without everyone seeing them. The option "share with users with private link" is not 100% satisfactory because users can share videos with each other. This would allow sensitive content to be shared with a list of trusted users.

**Comment by Chocobozzz** [comment]
Thanks for the issue but I think it's a duplicate of https://github.com/Chocobozzz/PeerTube/issues/520

**Comment by armandfardeau** [comment]
@Chocobozzz Absolutely a duplicate, my bad. Is this something you were thinking about?

**Comment by Chocobozzz** [comment]
Yes, but I don't have time to implement this soon.
