### ISSUE TITLE
Different number of comments for the same video across different instances

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#1887]
**I have checked the same video across 4 different instances:**

On these instances:
https://peertube.fedi.quebec/videos/watch/d9bd2ee9-b7a4-44e3-8d65-61badd15c6e6
https://peertube.amiensweb.fr/videos/watch/d9bd2ee9-b7a4-44e3-8d65-61badd15c6e6
you can see the video has 1 comment

On these instances:
https://peertube.social/videos/watch/d9bd2ee9-b7a4-44e3-8d65-61badd15c6e6
https://peertube.public.cat/videos/watch/d9bd2ee9-b7a4-44e3-8d65-61badd15c6e6
you can see the video has more than 1 comment

This observation might help you debug the issue: peertube.fedi.quebec and peertube.amiensweb.fr (the first pair of servers) allow user registration while peertube.social and peertube.public.cat (the second pair of servers) don't.

Let's check another server, https://peertube.peshane.net/videos/watch/d9bd2ee9-b7a4-44e3-8d65-61badd15c6e6 - has more than 1 comment **but not as many as there really are** (like on peertube.social) - weird! So it isn't related to whether the instance allow user registration or not.

**Additional information**
* PeerTube version or URL: 1.3
* Browser name/version: FireFox 60

**Comment by Zig-03** [comment]
@Chocobozzz How come? Here's another example, same video different number of comments:
https://peertube.social/videos/watch/84d8155d-3ed0-42ad-bc90-aaa17f07ec35 - 2 comments
https://video.ploud.fr/videos/watch/84d8155d-3ed0-42ad-bc90-aaa17f07ec35 - 0 comments

**Comment by Chocobozzz** [comment]
Closing this old issue. open.tube could be muted on video.ploud.fr, and without server logs I can't really help.
