### ISSUE TITLE
Initial admin user password

### ISSUE THREAD

**Issue by Falgn0n** [Chocobozzz/PeerTube#189]
Suggestion / Feature Request

There should be a way to specify the administrator user/password during the setup, maybe?

Finding the password in the npm logs was kind of a challenge for a noob like me

**Comment by Chocobozzz** [comment]
Sure, maybe we could set it in config files.

**Comment by WanTanFao** [comment]
Just out of interest: is there now a way to set the password upfront? Tooling around with PeerTube on swarm and as mentioned in other issues: it's nasty to get a password from logs for automated deployment :(

**Comment by Chocobozzz** [comment]
I updated the documentation: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#reset-passwordjs

**Comment by WanTanFao** [comment]
Neat, but still interactive, right? I want to run PeerTube as a Docker Swarm Stack so it would be nice to be able to bootstrap the user with a given password (via ENV at best).

**Comment by rigelk** [comment]
I will be mentoring the issue to an external contributor in the following days.

**Comment by darnuria** [comment]
Can I volunteer on the issue? :)

PS: I @rigelk, sorry for the delay I had some rust code on my way.

**Comment by Chocobozzz** [comment]
@darnuria sure

**Comment by darnuria** [comment]
Hi @rigelk, I openned a pull request to begin the discussion https://github.com/Chocobozzz/PeerTube/pull/1814, am I in the right file? :)

**Comment by Chocobozzz** [comment]
Implemented by @darnuria in https://github.com/Chocobozzz/PeerTube/commit/3daaa1927474869f8dbaddd6b94b4c071e314e10
