### ISSUE TITLE
Error upgrade to 1.3.0 yarn install (EACCESS permission denied)

### ISSUE THREAD

**Issue by quentinDupont** [Chocobozzz/PeerTube#1892]
**What happened?**
While upgrading to the version 1.3.0 from 1.2.1
I tried to upgrade automatically but i've got an error. Same error manually after this command

`cd /var/www/peertube/versions/peertube-${VERSION} && sudo -H -u peertube yarn install --production --pure-lockfile`

`yarn install v1.15.2
[1/5] Validating package.json...  
[2/5] Resolving packages...  
[3/5] Fetching packages...
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > marked-man@0.4.2" has unmet peer dependency "marked@^0.5.2".
[5/5] Building fresh packages...
[1/7] ⠂ bcrypt
[2/7] ⠂ bufferutil
[3/7] ⠂ utf-8-validate
[4/7] ⠂ rdf-canonize
warning Error running install script for optional dependency: "/var/www/peertube/versions/peertube-v1.3.0/node_modules/bufferutil: EACCES: permission denied, mkdir '/tmp/yarn--1560274415946-0.1965670021034165'"
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "/var/www/peertube/versions/peertube-v1.3.0/node_modules/utf-8-validate: EACCES: permission denied, mkdir '/tmp/yarn--1560274415947-0.544738390672163'"
`
Don't know what to do to fix it in the good way, thanks !!

**Comment by Chocobozzz** [comment]
Try `chmod 777 /tmp`

**Comment by quentinDupont** [comment]
I don't even tried that.. thanks, I'm in 1.3.0 now !
