### ISSUE TITLE
add rates_limit support for registrations.

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#1893]
This week-end, my instance was under a spam attack. A few IPs created many accounts, and uploaded fake blockbuster files.

In peertube 1.3.0, we can configure rate limits on login and ask_send_email. It can be usefull to add this on the registration endpoint.

**Comment by JohnXLivingston** [comment]
I found this related issue: https://github.com/Chocobozzz/PeerTube/issues/672
It was closed, but there is no rate limit on register endpoint. I'm I wrong ?

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/c1340a6ac35f924161e6ec2a1d728e20c89e55c8
