### ISSUE TITLE
[Feature request] Live streaming

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#1894]
Hello,

It would be cool to add a live streaming feature. Is it technically possible/not too difficult ?

**Comment by Zig-03** [comment]
https://github.com/Chocobozzz/PeerTube/issues/151

**Comment by Chocobozzz** [comment]
Thanks for the issue but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/151 :)
