### ISSUE TITLE
Broken link in imported video's description

### ISSUE THREAD

**Issue by gnouts** [Chocobozzz/PeerTube#1895]
**What happened?**

If a YouTube video contains an url in its description, import can sometime truncate the link in the PeerTube description if an `&` char is present.

Example : 
Youtube video with an url (containing an `&`) : https://www.youtube.com/watch?v=rcgxY__YXEc
PeerTube video imported from YouTube : https://alttube.fr/videos/watch/3aa91af8-2bb3-4e68-ae6a-938166f21eb5

Link is already truncated in the peertube editor/preview.
Bug also happens when using cli import.

**What do you expect to happen instead?**

Link should be full, like in the original YouTube description.

**Additional information**
* PeerTube version or URL: v1.2.0, v1.2.1 and v1.3.0

**Comment by Chocobozzz** [comment]
I'm sorry but I don't understand.

The issue is that the link `Instagram : http://bi... ` is cut off?

**Comment by gnouts** [comment]
Wooho sorry, I missed some sleep....
Everything is working fine. I misread the link display on hover by youtube (which look like that `https://www.youtube.com/redirect?q=https%3A%2F%2Fteespring.com%2Fstores%2Fdirtybiology-3&redir_token=3osE-Q02SS38Nl7Y4tCS1DQzeYF8MTU2MDUxNjE2NUAxNTYwNDI5NzY1&v=rcgxY__YXEc&event=video_description`) and the actual link (which is only `https://teespring.com/stores/dirtybiology-3`)
Forgive me ^^
