### ISSUE TITLE
Add the ability to block e-mail domains (like YopMail)

### ISSUE THREAD

**Issue by leonekmi** [Chocobozzz/PeerTube#1896]
To prevent users from using temp e-mails such as YopMail, PeerTube should provide a tool to ban e-mail domains.

It can be an instance setting such as "Whitelist/Blacklist e-mails domain".

**Comment by robinkooli** [comment]
What does it matter if they use one?

**Comment by leonekmi** [comment]
When we activate e-mail confirmation, it generally means that we don't want to get temp e-mails.

**Comment by rigelk** [comment]
There is now https://www.npmjs.com/package/peertube-plugin-glavlit which allows you to ban email domains, among other things.
