### ISSUE TITLE
No «subscribe» button in abrowser

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#1897]
Hello,

The «subscribe» button doesn't appears in abrowser, but is present on any other browser. I desactivated all adblockers.

**Additional information**
* PeerTube version or URL: 1.3.0
* Browser name/version: Abrowser 67
* NodeJS version: Unknown

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Hi,

I'm sorry but I can't reproduce. Are you sure you disabled all your extensions? I know that some adblocks have a list that hide this button.

**Comment by stemy2** [comment]
Yes, all my blockers are desactivated. That said, the unsubscribe button appears without problem.
