### ISSUE TITLE
Autoplay not working when coming from an iframe in mastodon

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#1898]
**What happened?**

I was on mastodon (instance: mamot.fr). I searched my peertube account, which I follow on mastodon. I launched the video in the mastodon's iframe. After a few seconds, I clicked on the "peertube" button in bottom right corner of the iframe.
It opened this url: https://www.yiny.org/videos/watch/c4f55728-e994-40da-857b-add977660098?autoplay=1&auto_play=1&start=9s

There are autoplay and auto_play parameters. But the video did not auto play. Moreover, there is a loading animation behind the play button.

![image](https://user-images.githubusercontent.com/38844060/59369472-ca1f8f00-8d40-11e9-8b77-dc674497befc.png)

Same thing if I am logged, or not (even in a private navigation tab)

**What do you expect to happen instead?**

The video should auto play

**Steps to reproduce:**

1. Open https://www.yiny.org/videos/watch/c4f55728-e994-40da-857b-add977660098?autoplay=1&auto_play=1&start=9s

**Additional information**
* PeerTube version or URL: 1.3.0
* Browser name/version: Firefox

**Comment by JohnXLivingston** [comment]
There are error logs in my firefox's console :+1: 

`DOMException: "The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission." 5.6cb384c1ac1757dc419f.js:1:312368
    Qt https://www.yiny.org/client/fr_FR/5.6cb384c1ac1757dc419f.js:1
    invoke https://www.yiny.org/client/fr_FR/polyfills.2981491f4ede2518a62c.js:1
    run https://www.yiny.org/client/fr_FR/polyfills.2981491f4ede2518a62c.js:1
    F https://www.yiny.org/client/fr_FR/polyfills.2981491f4ede2518a62c.js:1
    invokeTask https://www.yiny.org/client/fr_FR/polyfills.2981491f4ede2518a62c.js:1
    runTask https://www.yiny.org/client/fr_FR/polyfills.2981491f4ede2518a62c.js:1
    d https://www.yiny.org/client/fr_FR/polyfills.2981491f4ede2518a62c.js:1
`

**Comment by JohnXLivingston** [comment]
So it's firefox the problem. But the error should be catched, and the loading animation removed.

**Comment by Chocobozzz** [comment]
Does it happen with the new player?

**Comment by JohnXLivingston** [comment]
Seems to be ok. I close the issue.
