### ISSUE TITLE
Let uploaders decide of resolutions for their videos

### ISSUE THREAD

**Issue by ufm** [Chocobozzz/PeerTube#1899]
Hi!

1. The ability to specify for the video at the time of loading for which video resolutions to do transcoding.

2. The ability to add/delete resolutions for the video after loading.

**Comment by Jorropo** [comment]
Hi, you could allready add a resolution after video uploading with the create transcoding job script.

**Comment by ufm** [comment]
> Hi, you could allready add a resolution after video uploading with the create transcoding job script.
I simple user on peertube node, for example.

**Comment by rigelk** [comment]
Deleting resolutions of your video will impact users (i.e.: low resolutions for low bandwidth). Usually the choice of impacting the quality of service by choosing which resolutions to do is left to the instance administrator.

**Comment by ufm** [comment]
It's my video, and I know better about needed resolution.
For example - I upload video about SMD soldering and give acces only by direct link.
In any case - I do not do worse for node or node admin.

**Comment by Jorropo** [comment]
Maybe but that not the point, adding more resolution is a cost to the admin not you.
Even if you don't use the more resolution you don't have any reason to delete them, just don't use them.
If admin gived you this space that his choice, he made you a gift but nothings force you to use.
And if you want do the reverse things (enabling some not enabled res) that not a good things, your admin may try to save some space or CPU time.

**Comment by ufm** [comment]
But I have reason do not use unwanted resolutions for speedup upload (i want upload 10 videos, each - 5 hours). Without unwanted transcoding.
And in any case - the node admin allows you to use node resources. But the owner of the video must decide how it is better for him to use these resources.
Оtherwise, we must prohibit the deletion of the video for video owner. Why delete, resources on the node is enough.

**Comment by Jorropo** [comment]
First : upload doesn't takes longer with more resolution, only transcoding.
Then you may want to looks at #1192
And in far far future distributed transcoding is planned.

**Comment by ufm** [comment]
Not convinced.
I still think that the owner of the video has the right to decide what resolutions he needs for this particular video. Similarly, the video owner decides which description, which tags and which access.
This feature does not create additional loads on the nodes. Does not create additional inconvenience for admins of nodes.

**Comment by realityfabric** [comment]
Some instances have a data cap. If having your video in multiple resolutions counts against your cap, then it is definitely in the interest of the users to be able to decide which resolutions they want their videos in.

But also... shouldn't we let the users control their own content? Even if it doesn't make sense for someone to have only a 4k version of their video... why not let them? What's the point of preventing people from controlling their data?

**Comment by LoveIsGrief** [comment]
As a user, I'm against this anti-feature. It just introduces an arbitrary limitation for the viewers. I don't want to end up with a video with 4k and 360p. The uploader doesn't know what's best for me. I know what's best for me.

Furthermore, I don't want to end up having video A transcoded with 16:9, video B with 4:3 and video C with 1:1. That would mess up the user experience entirely.

> shouldn't we let the users control their own content

Uploading something to somebody else's computer doesn't constitute as "controlling their own content". If they really wanted to control their own content, they would have their own server with their own instance where they have the choice on which resolutions to allow.

**Comment by Chocobozzz** [comment]
If you want to decide what resolutions you want for your video, you can directly contact your peertube admin or become your own peertube admin :)
