### ISSUE TITLE
External links warning

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#1900]
If the server admins turn this feature on then:

Every time a user on that instance clicks on an external link, he will see a modal window that will say something like:
"You are about to be redirected to an external website, would you like to proceed?"
Then display the link in full length for the user to see where he's about to go. _(Also, what can we do about shortened links like bit.ly/example? Shortened links kinda defeat the purpose of this feature.)_
"Yes/No" buttons
and a checkbox that says: "Never ask me again"

**Comment by robinkooli** [comment]
Also, make other PeerTube instances exception?

**Comment by Jorropo** [comment]
Also add a checkbox, never ask me again for this site.

**Comment by realityfabric** [comment]
> Also, make other PeerTube instances exception?

How would this work? Can you be sure you're navigating to a PeerTube instance? If you can, I think there should still be a warning. These warnings are typically to prevent you from entering your credentials into a place you shouldn't be entering them, right?

**Comment by Chocobozzz** [comment]
Moving this issue on https://framagit.org/framasoft/peertube/official-plugins/-/issues/7
