### ISSUE TITLE
Distributive moderation

### ISSUE THREAD

**Issue by Jorropo** [Chocobozzz/PeerTube#1904]
Moderation is a big work but together we are better,
admin should be able to add a list of trusted instances, when a trusted instance blacklist a video or a channel, this video/channel should be sended to the black box for manual verification.
Notes:
- Depending of how we implement this this is maybe not required to add follow of all trusted instances.
- By default all instances should share an on endpoint their ban, but that could be restricted to following instances or desactivated (with a message for the admin about how he could help the network).
- When an instances validate a ban from his black box or gray box, this ban is shared to all black/gray box of all instances trusting this one.
- If you have already approved a video/comment (positivly or negativly) this choice should be remembered and the video/comment should never appear again.
- N reports to the same content from multiple instances or due to multiple reason should aggreate as one in the list.
- If a content is in gray and black box (because it was been reported by 2 instances with different trust level) should only appear in the black box with in the list of reporter the instance with a gray level added here.
- Only these content is compatible with distributive moderation, and for each trusted instance, admin can choose the trust level :
  - Video
  - Playlist (you could give it a bad name)
  - Comment
  - Channel
  - User
  So for example to a trusted instance you could choose to put evrythings black except channel and user wich you set to gray because blocking user and channel is more problematic. (don't forget, this settings is set by admin to each trusted instance).

**EDIT1**:
Admin could choose for each trusted instance 3 level, black box, gray box and white box (white box is do nothing, default) they are both validation list and require validation from an admin or moderator of your instances (not trusted one) but black box temporaly mask the video while gray box does nothing while any validation is made.

**Comment by Zig-03** [comment]
This implies trust and thus makes this a dangerous tool. _I'd vote against._

Trust is something that centralized platforms mostly use, not the decentralized ones.
I can see quite a lot of risks here, one being that many instance admins out their laziness will just pick "as their trusted instance" an instance that is "well established" and forget about moderation, thus giving more "central power" to the instance he chose as "the trusted one".

**Comment by Nutomic** [comment]
This sounds like a great idea, especially if it is combined with stricter rate limits and basic captchas. I think those together could completely solve the spam problem we currently have.

@Zig-03 Instance admins would have to enable this explicitly, and they would give other instance mods the ability to blacklist all videos. So I dont think that they would enable it for another instance without talking to them first. As another measure, we could make it so that both instances have to confirm, so it is unlikely that it would be concentrated.

**Comment by Jorropo** [comment]
@Zig-03 
> Trust is something that centralized platforms mostly use

yes but that not a full control, and I will personaly remove my trust from an instance if they ban random things to stop verification of use less things.

I'll add an edit, you makes me think about somethings thx.

> one being that many instance admins out their laziness will just pick "as their trusted instance"

You are totaly right about that except the "many" part, I think that will not be very present on the network. And if we don't do that all these instances will just not have any moderation. So what is best ? 10-30% instances with no moderation or 10-30% of the network with moderation made by some else ?
And 30% is in the worst case I can imagine, I will personaly bet on 10-15% (probably more 15).

**Comment by Chocobozzz** [comment]
Hi,

This distributive moderation feature can be developed in a plugin: https://docs.joinpeertube.org/contribute-plugins

You have helpers/hooks for video blacklist
