### ISSUE TITLE
tsc errors when running npm run build:server

### ISSUE THREAD

**Issue by anoadragon453** [Chocobozzz/PeerTube#1905]
**What happened?**

Unable to start my peertube instance.

**What do you expect to happen instead?**

It should start :D

**Steps to reproduce:**

1. npm i (successful)

2. npm start (fails)

3. npm run build:server (fails)

**Additional information**
* PeerTube version or URL: v1.3.0
* NodeJS version: v11.15.0

Output of `npm start`:

```
$ npm start

> peertube@1.3.0 start /var/www/peertube/versions/peertube-v1.3.0
> node dist/server

internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module '/var/www/peertube/versions/peertube-v1.3.0/dist/server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peertube@1.3.0 start: `node dist/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@1.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ops/.npm/_logs/2019-06-14T01_53_32_451Z-debug.log
$ 
```

Output of `npm run build:server`: https://gist.github.com/anoadragon453/2bec0b2767343de8207dc7f00fff89a9

**Comment by Chocobozzz** [comment]
Please follow [the contributing guide](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/CONTRIBUTING.md#prerequisites)

You should not use `npm i`

**Comment by anoadragon453** [comment]
Sorry, I wasn't too clear. I'm trying to run a production server, not set up a development environment, which may have been why the steps I was using wasn't bringing success.

I've just followed the upgrade guide to upgrade to v1.3.0 again and now everything starts as it should.
