### ISSUE TITLE
Prevent hotlinking

### ISSUE THREAD

**Issue by filmaidykai** [Chocobozzz/PeerTube#1908]
So I was thinking if I will make dissable download button in advanced settings so no one can't  download that file but i was wrong who is not stupid they know where and what need to change so that thing is bad when you trying download file with torrent or magnet link you can get max speed from webseed 3MBps or if u using download link like this one https://peertube.link/download/videos/3200e6cb-228a-427f-ab42-fdf53f07dbaa-720.mp4 (link is fake)  its unlimited so i wanna make it limited where and what i have to change it?  

PS and if i will add video in to blacklist who already using webseed link that still available possible to dissable it as well?

Cheers

**Comment by shirshak55** [comment]
yea provision should be there to prevent hotlinking. Downloading torrent wont hurt but some people are simply stealing hotlink and branding as their tv site. This need to be stopped. Ip prevention wont work as they can use infinite proxy.

**Comment by filmaidykai** [comment]
There must be a function to make the stream work just in the peertube community and block possibility  use hotlinks out from that or something like that anyway peertube using specific player so maybe make stream just in to that

**Comment by shirshak55** [comment]
Yea its a serious issue actually . I found some people are using hot link and streaming on their own website. I do filter by ip but each time they come with new ip so its impossible . I think we should be able to turn off hot link directly

**Comment by Chocobozzz** [comment]
You can't disable hotlinking by default since other PeerTube instances use it. But you can easily blacklist some domains (for example: https://stackoverflow.com/a/27782852)

**Comment by shirshak55** [comment]
@Chocobozzz may be we don't want other peertube instances to use it ? Because some people are just stealing the bandwidth from hotlink not even using webseed traffic . Anyway to fix it? 

Most people are developer and clever so they know how to bypass that easily.

**Comment by filmaidykai** [comment]
Or maybe best idea just make key generator for hotlinks?

**Comment by shirshak55** [comment]
Or there should be provision like for hotlinking they should use password etc. ? Anyway we know there are bad players in internet so we need to think about it :)

**Comment by ealgase** [comment]
> @Chocobozzz may be we don't want other peertube instances to use it ? Because some people are just stealing the bandwidth from hotlink not even using webseed traffic . Anyway to fix it?
> 
> Most people are developer and clever so they know how to bypass that easily.

Don't federate, then.

**Comment by shirshak55** [comment]
@ealgase u are not getting what i mean. I don't want him to use our bandwidth I am find he if takes from decentralize bandwidth (weebseed bandwidth). Did u get it?

**Comment by ealgase** [comment]
@shirshak55 you realize that webseed bandwidth is your bandwidth, correct?

**Comment by shirshak55** [comment]
Its part of my bandwidth.

**Comment by Chocobozzz** [comment]
If you want to prevent hotlinking, just update your reverse proxy configuration. But it will break PeerTube federation.
