### ISSUE TITLE
Remember resolution when watching a new video

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1909]
1. watch video A
2. change resolution to something other than "auto"
3. watch video B

-> resolution is back at "auto"

I expect Peertube to remember the last resolution, and use it for all videos that are watched afterwards.

**Comment by buoyantair** [comment]
Nice catch. I think this is pretty neat feature. A small cookie or setting in localStorage should do it and regardless of how many times the user visits the website, their preferred resolution is set. I think there can be more to this. If a user is logged in, this data can be saved into their account. Now, regardless of which computer, network or device the user uses, they will always have their preferred settings enabled. I think youtube does a terrible job at this as I have been using their "dark mode" feature all the time and it always resets back.

**Comment by maxdrash** [comment]
I think that's not necessarily a good idea.
80% of the traffic is on mobile and the majority of these users will argue Peertube for being a bad product because the videos will not load properly.
While it's the quality of their connection due to their mobility that is the real problem.
Peertube must keep the auto quality by default.

**Comment by realityfabric** [comment]
It could be set to auto by default, but then allow users to set their preferred default in their settings. That should satisfy most people.

It is kind of odd that I'm constantly getting defaulted to 240 or 360 when my internet is pretty decent, but having to manually change it let's me know to expect a bit of buffering.

**Comment by maxdrash** [comment]
Many users will complain when they will just forgot to turn the auto mode back on.
The best way to satisfy the most people is to let the instance administrator of activation for users to choose if users can set the reading quality in persistent static mode.

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/6108
