### ISSUE TITLE
Quick account action in comments

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#1910]
Add the account dropdown in comment section to easily mute spammers.

**Comment by rigelk** [comment]
The addition of the "Options" dropdown next to comments in release 2.1.0 allows to mute the account for a user/admin at different levels.

i.e. as a moderator, you see that kind of dropdown for comments:
![Screenshot_2020-04-11 UWwVx62](https://user-images.githubusercontent.com/6329880/79048023-84f71280-7c1a-11ea-9d01-ed2fecff9af0.png)
