### ISSUE TITLE
Infinite scroll of local/trending videos fails if the first 25 fit on the screen

### ISSUE THREAD

**Issue by thombles** [Chocobozzz/PeerTube#1912]
**What happened?**

When I open the "Local" page on my 27" monitor, 25 videos are shown in 5 rows. The content is not large enough to create a scrollbar. Therefore I cannot scroll down to trigger the loading of more videos - it appears fully loaded with only 25 results.

I can work around it by making my window smaller so that a scrollbar appears.

**What do you expect to happen instead?**

Additional content should be loaded until either a scrollbar is created or we run out of videos to display.

Or a simpler fix that would probably also work - load more initial content by default.

**Steps to reproduce:**

1. Have an instance with more than 25 videos on it.

2. Open a large browser window (e.g. maximised on 2560x1440) and visit the Local page

3. Only 25 videos are shown and is no way to see the others.

**Additional information**
* PeerTube version or URL: https://scitech.video/videos/local (v1.3.1)
* Browser name/version: Firefox 67.0

**Comment by impalex** [comment]
BTW - /my-account/history/videos, /my-account/videos - similar issue. Only first 5 videos available.

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/ad453580b20056fd80b3245d4db554f5ca1a5e29
