### ISSUE TITLE
Add link to instances 

### ISSUE THREAD

**Issue by bristow** [Chocobozzz/PeerTube#1914]
**What happened?**

In this page : admin/follows/followers-list, we have a list of instances that follow us but there is no link to consult this instance

**What do you expect to happen instead?**

I would like to have a link in order to see the content of these instances

**Additional information**
* PeerTube version or URL: 1.3.1
* Browser name/version: Firefox
* NodeJS version: ?

Thanks

Maybe we can put label 'Good for first issue' :)

**Comment by NassimBounouas** [comment]
Hi,

From what I see in my local instance, in the page admin/follows/followers-list we are listing all type of followers (peertube or mastodon). In [this commit](https://github.com/NassimBounouas/PeerTube/commit/a5e973407421b38a52707ffbf4bbc831e281746e) I wrapped the name displayed in a link pointing to the url stored on [ActorModel](https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/shared/actor/actor.model.ts#L7).

Is it the behavior that you were expecting ?

**Comment by bristow** [comment]
I think you are right.

For example, i have peertube@video.ploud.jp and i'd like to have a link (on this follower) in order to visit instance https://video.ploud.jp

Thanks @NassimBounouas :)

**Comment by NassimBounouas** [comment]
You're welcome @bristow, with this modification, in your example the link is to pointing to : [https://video.ploud.jp/accounts/peertube/videos](https://video.ploud.jp/accounts/peertube/videos)

I'll create a PR for this issue and the reviewer will tell us if something needs to be modified !

**Comment by bristow** [comment]
i'd prefer to go on https://video.ploud.jp/ (a lot of videos) instead of https://video.ploud.jp/accounts/peertube/videos (0 video) because this is for moderation (delete or not this follower).

**Comment by Chocobozzz** [comment]
> You're welcome @bristow, with this modification, in your example the link is to pointing to : https://video.ploud.jp/accounts/peertube/videos

In your PR and the latest dev, using `https://video.ploud.jp/accounts/peertube` as URL will redirect to `https://video.ploud.jp/local` so it should be fine.

**Comment by NassimBounouas** [comment]
Thank you @Chocobozzz for correction. I didn't see this behavior, where this redirection has been implemented ? (I didn't find it in the lastest commits)

**Comment by Chocobozzz** [comment]
@NassimBounouas https://github.com/Chocobozzz/PeerTube/commit/1a03bea0c42fa1064ce4770157b4fd2e3edd5565

Implemented by @NassimBounouas in https://github.com/Chocobozzz/PeerTube/commit/e1a1f9c623bfbbc7e38b36047926338f2e1c61d9

**Comment by bristow** [comment]
Thanks @NassimBounouas 

I still have some requests in progress if you want to do the hand :)

https://github.com/Chocobozzz/PeerTube/issues/created_by/bristow

**Comment by bristow** [comment]
I saw the commit in action on https://peertube2.cpy.re/ and this is not really the expected need. Why not go directly to the root of the instance?

Because, if i take an example, i'm going here : https://video.ploud.jp/accounts/peertube/videos or here https://tube.govital.net/accounts/peertube/videos and there is no videos :(

Thanks

**Comment by Chocobozzz** [comment]
As I said [here](https://github.com/Chocobozzz/PeerTube/issues/1914#issuecomment-503898012), when video.ploud.jp will be in 1.4 you'll be redirected to https://video.ploud.jp/videos/local.

We can't redirect directly to the instance root URL, because your instance is not necessarily followed by another peertube instance (it could be a mastodon account etc).

**Comment by bristow** [comment]
Sorry  @Chocobozzz , i did not undestand it was for PT 1.4.

All is fine :+1:
