### ISSUE TITLE
"Contact administrator" form should have a "subject" field

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1915]
Its not very helpful to have dozens of emails all with the subject "[PeerTube] Contact form submitted".

![Screenshot_20190619_005650](https://user-images.githubusercontent.com/1044450/59725230-70293880-921c-11e9-8ef3-e34d9c0bfe1a.png)

On the other hand, we could easily remove the field "your name" from the contact form. From what I can see, that is only used for the line "user sent you a message" in the email, and that line is pretty useless.

**Comment by Chocobozzz** [comment]
Implemented by @NassimBounouas
