### ISSUE TITLE
Overview Page has videos from muted channels

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#1918]
**What happened?**
When I mute a channel, its videos still appear in the Overview page.

**What do you expect to happen instead?**
I expect videos from muted channels to be hidden.

**Steps to reproduce:**
1. Log into a PeerTube account
2. Go to the Overview page
3. Mute the channel of any video which appears on the overview page.
4. Reload the Overview page. All videos are still visible, including videos from muted channels.

**Additional information**
* PeerTube version or URL: Open.Tube
* Browser name/version: Chrome 75.0 and Firefox 60.7.1esr

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/764a965778ac89e027fd05dd35697c6763e0dc18 & https://github.com/Chocobozzz/PeerTube/commit/111fdc267b36201cf1be1fdf91017005102b4a5e

**Comment by stom79** [comment]
I am still getting that bug Version: 2.4.0

**Comment by rigelk** [comment]
@stom79 how long after the action?

**Comment by stom79** [comment]
Currently more than 20 minutes

**Comment by rigelk** [comment]
@stom79 sounds like caching on the server side is preventing the overview page from reflecting your change.

**Comment by stom79** [comment]
OK. I didn't think api calls would be impacted. It works for other timelines, but the overview one is quite different I guess.

**Comment by Chocobozzz** [comment]
The overview endpoint should not be cached anymore. I think there is just a bug here

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/52a350a15c34aa13bffaeedeb39de37cb0534fde. Thanks @stom79
