### ISSUE TITLE
Torrented Videos have original title as filename

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#1919]
**What happened?**
After editing the title of one of my videos, I started downloading it via .torrent file.

The video file's filename contained the original title.

**What do you expect to happen instead?**
The video file should instead have the edited title, not the original title.

**Steps to reproduce:**
1. Upload a video and set the title. (example: `Test Video`)
2. Publish the video.
3. Edit the video title. (example: `Changed the Title`)
4. Download the torrent file. (if downloading 1080p, will be `Changed the Title-1080p.torrent`
5. Use a torrent application to torrent the video file.
6. Check the video's filename. (will be `Test Video 1080p.mp4`)

**Additional information**
* PeerTube version or URL: https://Open.Tube
* Browser name/version: Firefox 60.7.1esr

It's been at least a few days since I edited the title. 
This may be related to #444, but is a separate issue.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/38d69d65012c8bf01bceb672be99f94fe414f275
