### ISSUE TITLE
Add a information banner

### ISSUE THREAD

**Issue by maxdrash** [Chocobozzz/PeerTube#1921]
Hello team !

It would be very useful to insert a information banner on the top of peertube to inform users and visitor of any latest quick info about the host or whatelse.
This option will have to be customize with a checkbox for the visibility in the admin panel.

Thank you !

**Comment by StalinEXE** [comment]
I think that banner is superfluous.
BUT developers can expand About page.

Here is a screenshot from one of the Mastodon instances

![request-2](https://user-images.githubusercontent.com/1181085/62151108-42014300-b308-11e9-91d0-bc93b4d343da.png)

Amount of users and videos, information about Administrator, some contact info, etc.

I think that it is more beneficial use of space and resources.

**Comment by maxdrash** [comment]
There is already a "about" page.
We can ask that the statistics of the instance be included in it.
But an information banner, clickable to close it or disappears after several seconds would be a plus.
Developed as a plugin does not bother me.
