### ISSUE TITLE
Follow service base application URL pointing to wrong endpoint

### ISSUE THREAD

**Issue by NassimBounouas** [Chocobozzz/PeerTube#1924]
Hi,

While I was working on an issue I found nothing weird. The base application url is hard coded to `https://peertube2.cpy.re` [there](https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/shared/instance/follow.service.ts#L12). I guess that this should be replaced by `environment.apiUrl` like [there](https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/shared/instance/instance.service.ts#L10).

If someone (maybe @Chocobozzz) can confirm it to me, I'll  be happy to correct it and provide a PR.

**Comment by Chocobozzz** [comment]
:man_facepalming: 

Thanks @NassimBounouas, it's fixed in https://github.com/Chocobozzz/PeerTube/commit/ac84064a6cd21026ed66c53aa830817404c2de3c
