### ISSUE TITLE
Notification screen broken when a user has been deleted

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#1927]
**What happened?**

I banned a user from my account, because it was spamming comments. But banning the user doesn't delete his comments. So I deleted the user afterwards.
Since then, my notification screen is broken.

![image](https://user-images.githubusercontent.com/38844060/59857947-49811400-937a-11e9-81bf-8f2e9f788c9f.png)

In my firefox console, I have the following error :
`ERROR TypeError: "e.parent.context.$implicit.actorFollow is undefined"`

**Additional information**
* PeerTube version or URL: 1.3.1
* Browser name/version: Firefox

**Comment by Chocobozzz** [comment]
Please open the web browser console, in the network tab find the notification `id`. Then go inside your database, and paste the result of `select * from "userNotification" where id = ...`

**Comment by JohnXLivingston** [comment]
`peertube_prod=> select * from "userNotification" where id = 1494;                                                                                                                              
  id  | type | read | userId | videoId | commentId | videoAbuseId | videoBlacklistId | videoImportId | accountId | actorFollowId |         createdAt          |         updatedAt          
------+------+------+--------+---------+-----------+--------------+------------------+---------------+-----------+---------------+----------------------------+----------------------------
 1494 |   13 | t    |      6 |         |           |              |                  |               |           |           284 | 2019-06-17 18:14:21.296+00 | 2019-06-20 14:35:46.563+00
(1 row)
`

**Comment by JohnXLivingston** [comment]
![image](https://user-images.githubusercontent.com/38844060/62306110-82d09780-b481-11e9-950b-df3029c0ae36.png)

**Comment by JohnXLivingston** [comment]
I thinks it is this notification, but I'm not sure.

**Comment by JohnXLivingston** [comment]
I think I made a mistake. It should be this one :
![image](https://user-images.githubusercontent.com/38844060/62306841-e0b1af00-b482-11e9-93db-1c4ad5fcb0fe.png)

peertube_prod=> select * from "userNotification" where id = 1600;
  id  | type | read | userId | videoId | commentId | videoAbuseId | videoBlacklistId | videoImportId | accountId | actorFollowId |         createdAt          |         updatedAt          
------+------+------+--------+---------+-----------+--------------+------------------+---------------+-----------+---------------+----------------------------+----------------------------
 1600 |   10 | t    |      6 |         |           |              |                  |               |           |           285 | 2019-06-19 22:32:09.537+00 | 2019-06-20 14:35:46.563+00
(1 row)

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/44b88f180bc9ec692885e7db08757a43b3e2df79
