### ISSUE TITLE
Password Reset Link expires without warning

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#1928]
**What happened?**
I used the "Forgot My Password" feature. I received an email with the link, but I did not open the link until 20+ minutes after I had received it. (The email had been sent to spam)

When attempting to reset my password, I was able to fill in the password and confirm password fields, but received an error message when I clicked to submit.

I tested multiple lengths of password, just in case I was using a password that was too long.

I used the feature again and used the new link almost immediately (less than 3 minutes) and was able to change my password and login without any errors or issues.

**What do you expect to happen instead?**
I expected to be able to change my password. I think a timeout is a good idea, but there should be a warning *before* filling out the password reset form. Either in the email, or on the reset form itself (preferably not even showing the form if the link is expired), and ideally both places. At the very least the error message should be more clear about why the submission isn't working.

**Steps to reproduce:**
1. Be logged out of any PeerTube accounts.
2. Go to the login page.
3. Click "I forgot my password"
4. Enter your account email address
5. Confirm that you received an email, and wait 20+ minutes (possibly less)
6. Follow the link in the email. You will be taken to a password reset form.
7. Fill out the password reset form (with a new password and the password confirmation)
8. Click submit. You will receive an error message.
9. Try various passwords if you want, they should all receive the same error message.

**Additional information**
* PeerTube version or URL: https://peertube.social
* Browser name/version: Firefox 60.7.1esr

**Comment by NassimBounouas** [comment]
Hi @realityfabric,

I'm working on your issue. I found that there is a life time of 5 minutes set [there](https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/constants.ts#L474).

What I'm suggesting as a first step is to add this life time on the reset form as you requested and add it to the email sent to the user.

Then it could be interesting to call a validator inspired by [this one](https://github.com/Chocobozzz/PeerTube/blob/develop/server/middlewares/validators/users.ts#L318) when the user is using the reset link in the email. By doing this, we can display him/her an error message instead of a reset form.

Question to @Chocobozzz : Currently the `USER_PASSWORD_RESET_LIFETIME` is hard coded to 5 minutes. It could be interesting to retrieve this value from the configuration to let the instance owner to increase or decrease it. What do you think about this idea ?

**Comment by Nutomic** [comment]
Anyway 5 minutes seems way too short for this. I think it would be fine to set the timeout to one hour or more.

**Comment by NassimBounouas** [comment]
Yes @Nutomic, you are right that's why I was suggesting to let instance owner to set it.

**Comment by realityfabric** [comment]
I think the customized expiration time could be good (an hour seems excessive, but 5 minutes is pretty short), but that should be an entirely different issue imo so that these two things aren't confused.

**Comment by NassimBounouas** [comment]
In my last commit @realityfabric the password reset life time is not hardcoded and fits what you were suggesting [there](https://github.com/NassimBounouas/PeerTube/commit/232863422f0b2d16c0ddf33498d71b81516b77a8#commitcomment-34040666).

**Comment by NassimBounouas** [comment]
Hi @Chocobozzz I can't link you in a comment if it's posted on my github account. Please, can you give me your feedback on [this](https://github.com/NassimBounouas/PeerTube/commit/13e638ae7560bdfd534b5c24e70962812d9616cd?diff=split#r34051844).

I firstly used the restExtractor but 403 and 404 case aren't handle by the `handleError` function.

Thank you

**Comment by Chocobozzz** [comment]
> Question to @Chocobozzz : Currently the USER_PASSWORD_RESET_LIFETIME is hard coded to 5 minutes. It could be interesting to retrieve this value from the configuration to let the instance owner to increase or decrease it. What do you think about this idea ?

Hardcode it to 1 hour. Adding another key in the config file is an extra job (we need to update the tests etc) that does not worth it for now. As @realityfabric said, if we'll need to customize it in the future we'll create another issue.

@NassimBounouas Do not hesitate to create WIP PR, so we can easily comment your work :)

**Comment by NassimBounouas** [comment]
Hi @Chocobozzz,

Thank you for your reply.  I'll create a PR to exchange with you about the part you said you didn't understand on my commit.

About the USER_PASSWORD_RESET_LIFETIME I will revert my commit about a customizable one and I will hardcode it to 1 hour.

Thanks !

**Comment by Chocobozzz** [comment]
Any news on this @NassimBounouas?

**Comment by NassimBounouas** [comment]
Hi @Chocobozzz,

Thank you for the reminder, I over postoned my RP and I finally forgot to do it. I'm creating it now but I think I'll need to rework it since the develop branch has changed a lot.

**Comment by Chocobozzz** [comment]
Fixed by @NassimBounouas in https://github.com/Chocobozzz/PeerTube/commit/f88ee4a9523bf3c4a61a45832963c558aed4d0b1
