### ISSUE TITLE
Subscribing sometimes causes flood of notifications

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#1929]
**What happened?**
I followed a channel, and was then flooded with notifications for every video that channel has ever posted as if they had just posted it.

This image shows notifications, all of which are about the same channel:
![image](https://user-images.githubusercontent.com/8910652/59866509-92b47200-9340-11e9-9176-4280c5e231a9.png)

This has only happened to me twice, once Open.Tube and once on PeerTube.social, with different channels. On Open.Tube it was caused by subbing to a channel on PeerTube.fr and on PeerTube.social it was caused by subbing to a channel on Open.Tube.

**What do you expect to happen instead?**
I expect not to receive any notifications of video uploads unless videos are uploaded *after* I follow the channel. Previous uploads should not cause notifications.

**Steps to reproduce:**
Honestly, I don't know how to reproduce the issue other than to follow a bunch of channels until it happens again.

**Additional information**
* PeerTube version or URL: https://Open.Tube and https://PeerTube.social
* Browser name/version: Chrome 75.0 and Firefox 60.7.1esr

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1198edf4bb06ce5f1668b97cf9ca8fb483fe3f41
