### ISSUE TITLE
What can I do to maintain my torrent seed?

### ISSUE THREAD

**Issue by zzoozzo1122** [Chocobozzz/PeerTube#193]
hi .
To keep seeds of multiple videos registered after setting "PeerTube" web server
It works normally.
If there are more and more images, there is a load on the server.
I want to generate a lot of seeds for that time.

https://webtorrent.io/desktop/
I downloaded the desktop program for windows and kept the seed file to keep the seed.

The seed is not maintained.

Only the person who played the video seems to be keeping up.
How do I maintain a steady seed on multiple military servers?

I want to distribute a lot of video traffic through several server computers.

2.The Manage follows on the admin page is exactly what it does
Please provide a sample address of how to add an Internet address.

**Comment by Chocobozzz** [comment]
Hi, webtorrent Desktop should add seeds but it really depends of your network (NAT, firewall...) and it could not work.

I think what your really want is https://github.com/Chocobozzz/PeerTube/issues/123

**Comment by zzoozzo1122** [comment]
So, it's not updated yet.
Is there no way?

If you can utilize it as one server,
Server performance 
Can we have 10,000 concurrent users?

**Comment by Chocobozzz** [comment]
PeerTube is not designed to accept 10000 concurrent users. It's designed to be federated. If you want to propose PeerTube to 10000 users, create ~100 instances that follow each other.

But please keep in mind that it's still a WIP, with a beta in march. There might be some performance improvements in the future after real world tests.

**Comment by zzoozzo1122** [comment]
"instances that follow"

How do I set this?
I don't know because I'm a beginner.
Please teach me a lot.

**Comment by zzoozzo1122** [comment]
To create one instance.
Where do I have to correct it?
Or which server should I add? ?

**Comment by zzoozzo1122** [comment]
Thank you for your answer.
