### ISSUE TITLE
Sidebar overlaps videos when using playlists

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#1930]
**What happened?**
When watching playlists, the sidebar covers part of the video, including the Play/Pause controls and video time, as below:
![image](https://user-images.githubusercontent.com/8910652/59941712-c5c73600-9412-11e9-810d-3506f6b7a76e.png)

In contrast, the same video when not viewed from a playlist:
![image](https://user-images.githubusercontent.com/8910652/59889335-bb5c5c00-9380-11e9-9ec3-b1b641af11df.png)

**What do you expect to happen instead?**
What I expected to happen was to be able to see the entire video, with no overlap.

**Steps to reproduce:**
1. Log into PeerTube
2. Add a video to a playlist (can be private, unlisted, or public)
3. Open the playlist and start watching any of the videos in it.
4. Adjust the browser window (if necessary) so that it is square, but still wide enough that the navigation sidebar and playlist sidebar are to the left and right respectively. The left portion of the video will be covered by the sidebar.

**Additional information**
* PeerTube version or URL: https://PeerTube.social
* Browser name/version: Firefox 60.7.1esr (I also used Incognito mode with addons disabled)

The mobile site (on Firefox) does not have this problem.

**Comment by realityfabric** [comment]
It looks like this bug is caused because my monitor is square. The closer to a square the browser window is the worse the overlap gets. The wider your browser window is (relative to the height) the less overlap there is.

The overlap only happens if the browser is wide enough to allow both the navigation sidebar and the playlist sidebar.

**Comment by AutomCoding** [comment]
I have the exact same issue on a 1366×768 (16:9) monitor. The viewport height doesn't matter until it limits the player height (at which point the player shrinks, "fixing" the problem).

**Comment by Chocobozzz** [comment]
Thanks, I think it will be fixed by https://github.com/Chocobozzz/PeerTube/commit/58f3c3f1095de8d1f8bad3fbf61efb4366ae41fc
