### ISSUE TITLE
Muting an instance has a confusing Mute Badge

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#1932]
**What happened?**
I muted an instance (as a user) and the badge that appeared said "Muted by your instance".

![image](https://user-images.githubusercontent.com/8910652/59939229-19825100-940c-11e9-9ce4-730f5d63b656.png)

**What do you expect to happen instead?**
If the instance was not muted by my instance then I expect the badge to say something like "You muted this instance"

If the instance is muted by my instance then I expect not to see the videos in the first place.

**Steps to reproduce:**
1. Log into PeerTube. 
2. Visit an account page for an account not hosted on your own instance.
3. Mute the instance. A badge will appear that says "Muted by your instance".
4. On refresh the badge will disappear due to issue #1748.

**Additional information**
* PeerTube version or URL: https://PeerTube.social
* Browser name/version: Firefox 60.7.1esr

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/075942b212ff02aebf2f6668322407d40a0b91e5
