### ISSUE TITLE
Mastodon account bio html tags are not parsed 

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#1933]
**What happened?**
Federation Bot followed me, and I was able to view its Bio via the account "About" page. The bio is not parsed as HTML, so the tags and html character codes are not translated properly. 
![Screenshot_20190621-202038](https://user-images.githubusercontent.com/8910652/59958933-2aaa7c80-9463-11e9-8477-027f05a8a112.png)

**What do you expect to happen instead?**
I expected the output to be human readable, with formatting respected (not simply stripping the tags, but actually formatting the bio) 

**Steps to reproduce:**
1. Log into a Mastodon account (possibly other platforms as well) which has a Bio
2. Follow a PeerTube account you can log into
3. Log into your PeerTube account 
4. View notifications and open the account page for the account you followed from
5. Visit the "About" page. The html tags will be visible. 

**Additional information**
* PeerTube version or URL: https://Peertube.social 
* Browser name/version: Firefox for Android

**Comment by realityfabric** [comment]
It looks like this is 
where the description is presented to the user https://github.com/Chocobozzz/PeerTube/blob/c1109b45f6d6ed8024908df2340f8c06ae4c5db7/client/src/app/%2Baccounts/account-about/account-about.component.html#L2-L5

and it's getting the account description with
https://github.com/Chocobozzz/PeerTube/blob/c1109b45f6d6ed8024908df2340f8c06ae4c5db7/client/src/app/%2Baccounts/account-about/account-about.component.ts#L38-L42

I'm trying to find where accounts are instantiated (it might be under [/server/models/account/account.ts](https://github.com/Chocobozzz/PeerTube/blob/57cfff78858b2360d9e038e2a504b761cb51da47/server/models/account/account.ts#L85)). I think this might be a problem with sanitization, although I'd much rather have it prevent any HTML from working than have it allow all HTML.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/7e049ea4673f05cbb90b37199bb93713cc0d5611
