### ISSUE TITLE
Can't schedule video on mobile device 

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#1936]
**What happened?**
Tried to schedule a video for publishing at a later time, but the calendar pops up underneath the on screen keyboard and disappears if you try to adjust the screen.

**What do you expect to happen instead?**
I expect the calendar to pop up on the visible screen, either by popping up above the keyboard or by not triggering the key board popping up. I also expect the calendar not to disappear when scrolling up or down. 

Another thing that would be nice is placeholder text with an example datetime so that users can type it out if/when the calendar fails. I don't know if it will accept text input, but it would be an effective (if inconvenient) workaround. 

**Steps to reproduce:**
1. Log into PeerTube on Firefox for Android 
2. Upload a video
3. Set the privacy setting to "Schedule" 
4. Click in the box to set the date. The calendar pops up, partially obscured by the keyboard. 
5. Try to scroll to get the calendar to be visible. It will disappear. 

**Additional information**
* PeerTube version or URL: Peertube.social 
* Browser name/version: Firefox for Android, on a Motorola G7 (not sure if the screen size will have an effect)

**Comment by Chocobozzz** [comment]
Closing as the keyboard can be hidden using the back button now
