### ISSUE TITLE
Add multiple fallback trackers to torrent or magnet

### ISSUE THREAD

**Issue by LoveIsGrief** [Chocobozzz/PeerTube#1941]
**What happened?**

Couldn't play [video](https://video.ploud.fr/videos/watch/1837b1c8-3a3f-4426-aa13-cc8c121d60e4) because tracker was down.

**What do you expect to happen instead?**

Alternative tracker should've been provided and used in order to retrieve the video

**Steps to reproduce:**

1. Find a video that doesn't load ([example](https://video.ploud.fr/videos/watch/1837b1c8-3a3f-4426-aa13-cc8c121d60e4))

2. Open console

3. Find error logs

`Firefox kan geen verbinding maken met de server op wss://tube.kdy.ch/tracker/socket`

**Additional information**

* PeerTube version or URL: PeerTube v1.3.0...1f20622f
* Browser name/version: 67.0.3 (64-bits)
* NodeJS version:

* Link to browser console log if useful: 
[client.log](https://github.com/Chocobozzz/PeerTube/files/3317937/client.log)

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
In fact you could not play the video because the origin server was down, and so unable to serve the torrent file. To add a fallback we need to duplicate the torrent files/HLS playlist files (in addition to the video files) when using redundancy. We could also add a tracker fallback but it's less important IMHO.

**Comment by LoveIsGrief** [comment]
So, if I'm understand this right, the plan is for every server to mirror the torrents of the servers it's listening to and add itself to the list of trackers?

**Comment by Chocobozzz** [comment]
> So, if I'm understand this right, the plan is for every server to mirror the torrents of the servers it's listening to and add itself to the list of trackers?

Yes, except that it will be the origin server that will update the torrent file to add the mirror server to the list of trackers (the origin server already updates the torrent to add the mirror server to the list of webseeds).

**Comment by LoveIsGrief** [comment]
What happens if the origin server doesn't update to include this fix?

**Comment by martinambrus** [comment]
Hi guys, is this feature being worked on or planned? I've run into the same issue now that the primary server actually went down and I can't play any video on my own redundancy server via the web UI.

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/3431
