### ISSUE TITLE
Missing autocomplete attribute on user's form fields

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#1943]
**What happened?**

As an administrator, when I edit a user to change his quota, my browser keep the e-mail in memory, and propose it to me on other websites login forms.

**What do you expect to happen instead?**

You should add an autocomplete="off" on fields. I'm not quite sure it is enought (see https://developer.mozilla.org/fr/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields)

**Additional information**
* PeerTube version or URL: 1.3.1
* Browser name/version: Firefox

**Comment by robinkooli** [comment]
Autocomplete attribute isn't supported on Chromium based browsers.

**Comment by JohnXLivingston** [comment]
> Autocomplete attribute isn't supported on Chromium based browsers.

I think it is supported on input fields.
https://developer.mozilla.org/fr/docs/Web/HTML/Attributs/autocomplete

**Comment by robinkooli** [comment]
Chromium developers intentionally don't respect autocomplete="off":
https://bugs.chromium.org/p/chromium/issues/detail?id=914451
