### ISSUE TITLE
Add stats page

### ISSUE THREAD

**Issue by bristow** [Chocobozzz/PeerTube#1944]
It would be useful for admins to have a page with stats : 

- number of users
- number of videos (local and others)
- number of total views
- disk usage / ram usage
- number of comments
- number of followers
- ...

I think a lot of informations are already presents on instance because we have this page : https://instances.joinpeertube.org/instances

what do you think about that ?

**Comment by JohnXLivingston** [comment]
You can find some informations on this api endpoint: /api/v1/server/stats (for example: https://www.yiny.org/api/v1/server/stats).

For disk and ram usage, you should use monitoring systems (for example munin). Peertube should not give this kind of information.

**Comment by bristow** [comment]
So, implementing this page could be made easier.

What is 'totalLocalVideoFilesSize' ?

**Comment by jonathanpatate** [comment]
It's not the purpose of Peertube to show disk usage / ram usage informations, is a part for a monitoring tool. Besides Munin, check about phpSysInfo.
https://github.com/phpsysinfo/phpsysinfo

**Comment by Chocobozzz** [comment]
In fact I think we could put this information in the about page (maybe in another tab).

> What is 'totalLocalVideoFilesSize' 

It represents the total video bytes that your instance stores (does not take into account redundancy). Used in https://instances.joinpeertube.org/instances/stats

**Comment by JohnXLivingston** [comment]
I think this issue can be closed with the version 2.0.0

**Comment by bristow** [comment]
Yes :+1:
