### ISSUE TITLE
Documentation contains broken links

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#1945]
**What happened?**
When clicking some links (e.g. `/support/doc/api`) it leads to a 404 page.

It seems like these were not intended to be actual links.

![image](https://user-images.githubusercontent.com/8910652/60051216-5ad26500-9687-11e9-8d7e-8f2afafe7e72.png)

**What do you expect to happen instead?**

I expect links I click on to lead somewhere (preferably somewhere useful). When I clicked on `/support/doc/api` I expected to be taken to the API support docs.

If these were not intended to be links, then I expect them not to be links.

**Steps to reproduce:**
1. Visit PeerTube docs "Getting Started" page. (https://docs.joinpeertube.org/#/contribute-getting-started?id=write-documentation)
2. Click on a link starting with /

**Additional information**
* Browser name/version: Google Chrome Version 75.0.3770.100 (no extensions)

**Comment by realityfabric** [comment]
After looking into editing the documentation, it looks like the links are intentional.

They are written as `[/support/doc/api](/support/doc/api)`.

**Comment by Chocobozzz** [comment]
Unfortunately I did not find a way to alias these links using docsify (in the [documentation repository](https://instances.joinpeertube.org/instances/stats)). We should probably remove the links, or use absolute github links.

**Comment by LoveIsGrief** [comment]
A more complicated but generic solution would be writing a [docsify hook](https://framagit.org/framasoft/peertube/documentation/blob/master/index.html#L83) that replaces relative links in aliased with their absolute equivalent.

But maybe that's overkill, I dunno.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/0ceadb3578bf8197308d803446eaaefc01830e08
