### ISSUE TITLE
sleep update for channel import tools 

### ISSUE THREAD

**Issue by valinux** [Chocobozzz/PeerTube#1949]
**What happened?**
when you import channels that youtube content creators allow you to 
while using the import command when you upload 5-8 videos it breaks the server.
**What do you expect to happen instead?**
sleep for every 3-4 videos imported sleep for 40 mins then import 3-4 more videos
**Steps to reproduce:**

How to I add sleep so that I can just screen and detach from screen session and every 3 imports it sleeps for 30-60 mins.

1.

2.

3.

**Additional information**
* PeerTube version or URL:
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Hi,

What do you mean by "it breaks the server"?
