### ISSUE TITLE
When uploading, warn when the user quits the page

### ISSUE THREAD

**Issue by tcitworld** [Chocobozzz/PeerTube#195]
When the browser is still uploading a video or if it's not published yet, the app should warn the user if : 
* the user tries to access another section of the app
* the user closes the tab or browser window

**Comment by Chocobozzz** [comment]
It's a good first issue :)

(use https://angular.io/api/router/CanDeactivate)

**Comment by Chocobozzz** [comment]
Implemented by @DimitriGilbert: https://github.com/Chocobozzz/PeerTube/commit/529479f924b1849423fb087f9699f8ecb20610ca
