### ISSUE TITLE
Show video length somewhere in the description

### ISSUE THREAD

**Issue by mmuman** [Chocobozzz/PeerTube#1954]
When the browser disables autoplay, the video area only shows the preview image and the play button. Nowhere else on the page is the length of the video. (same for the peer stats btw)

**Comment by rigelk** [comment]
This appears to not only be related to the embed, but any instance where the browser doesn't allow videos to start automatically. In that case, peer stats are irrelevant since the WebTorrent client is not even initialized.

**Comment by mmuman** [comment]
Yes, it's not only when embedding.

**Comment by Poslovitch** [comment]
Shouldn't this issue be closed?
