### ISSUE TITLE
Translation of units

### ISSUE THREAD

**Issue by AutomCoding** [Chocobozzz/PeerTube#1957]
How will this line be displayed to the user, and can the word “bytes” be translated?

https://github.com/Chocobozzz/PeerTube/blob/73b3aa6429dfb2e31628fa09a479dce318289d7d/client/src/app/shared/images/preview-upload.component.html#L12

In Swedish, we always (with a few exceptions such as units of time less than a year) use the singular form of units even if the numerical value is greater than one.

**Comment by Chocobozzz** [comment]
Hi,

It will be displayed like this: 
![screen_2019-07-25-14:19:01](https://user-images.githubusercontent.com/5180488/61873841-31576400-aee7-11e9-93e7-9bfd42f9ada3.png)

`bytes` is a JS function so you don't have to translate it :)
