### ISSUE TITLE
Channel API returns only 15 videos

### ISSUE THREAD

**Issue by MaximilianKindshofer** [Chocobozzz/PeerTube#1961]
**What happened?**

Calling the API for /video-channels/{channelHandle}/videos returns only the first 15 entries

**What do you expect to happen instead?**

Calling the API should return all entries

**Steps to reproduce:**

1. got to [https://framatube.org/api/v1/video-channels/bf54d359-cfad-4935-9d45-9d6be93f63e8@framatube.org/videos]

2. Collapse all, then open data

3. Count entries

I guess it is related to this [https://github.com/Chocobozzz/PeerTube/issues/844],
but the references in the Issue are gone.

**Comment by JohnXLivingston** [comment]
You are right, it is related to #844. You have to use the start parameter to paginate through the results.

It seems the new documentation isn't up to date, and doesn't list query parameters for this endoint.
The start parameters works with your query.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/6676056a316a09557b8445cf6c0583ff8c588339
