### ISSUE TITLE
suggestion for increasing content

### ISSUE THREAD

**Issue by Rik44444** [Chocobozzz/PeerTube#1964]
hi all,
big fan of Peertube, thank you all for creating this ! 
i have a suggestion for increasing the content of Peertube (thus attracting more users): have you considered copying the most viewed Creative Commons videos on Youtube? here they are: 
https://www.youtube.com/results?filters=video&lclk=video&search_query=a%7Cb%7Cc%7Cd%7Ce%7Cf%7Cg%7Ch%7Ci%7Cj%7Ck%7Cl%7Cm%7Cn%7Co%7Cp%7Cq%7Cr%7Cs%7Ct%7Cu%7Cv%7Cw%7Cx%7Cy%7Cz%7C1%7C1%7C2%7C3%7C4%7C5%7C6%7C7%7C8%7C9%7C0&search_sort=video_view_count&sp=CAMSBBABMAE%253D

**Comment by Nutomic** [comment]
There is an instance for this: https://vidcommons.org

(certificate seems to be expired, i already told the admin)

**Comment by Rik44444** [comment]
ah great!

**Comment by Zig-03** [comment]
I had no idea there are **that many** CC videos! 
We definitely need them all on the PeerTube network! :smiley:

**Comment by Chocobozzz** [comment]
Hi,

Yes it would be very interesting. But we just develop the software (with some demo instances with not enough storage). You could ask some instance admins/non profit/host providers instead :)

**Comment by emansom** [comment]
Browsing the search results, there does seem to be a lot of copyrighted material (music videos, television show fragments) labeled as Creative Commons incorrectly. If Framasoft (or any other non-profit) would host mirrors of these videos themselves, that'd open them up rightful DMCA claims.

This is a good strategy in principle, but it'd have to be a manual-checked list. Having some mechanism to manually verify or blocklist during the syncing phase could aid in this.
