### ISSUE TITLE
[Feature] Add Private Mode/Instances

### ISSUE THREAD

**Issue by ggg27** [Chocobozzz/PeerTube#1967]
**Feature**: Add privacy-enhanced toggle to disable IP leaking.
**Why?**: WebTorrent leaks your IP by design, instances and users should be able to choose turn this off by default. Especially, until https://github.com/webtorrent/webtorrent/issues/465 is fixed.

_______________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/76917409-feature-add-private-mode-instances)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=76917409)](https://www.bountysource.com/issues/76917409-feature-add-private-mode-instances)

**Comment by Chocobozzz** [comment]
Admins can already disable the tracker and users can disable P2P in their settings.
