### ISSUE TITLE
Admin option to disable a particular video privacy

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1969]
From a moderation perspective, unlisted videos are very hard to handle, because they are mainly shared with external users, who are less likely to report rules violations. This makes them ideal for people who want to upload eg pirated videos. At the moment, the only countermeasure against this (on a public instance) is having mods regularly check new uploads and making sure that nothing bad was uploaded. This could all be avoided if the admin can choose to disable unlisted videos.

**Comment by realityfabric** [comment]
Would this convert existing unlisted videos to private videos?

**Comment by Chocobozzz** [comment]
I don't think admins options with side effects is a good idea. If you enable this options, it will only affect new uploads. And if you want to update old unlisted videos to private, just do it manually (or with a script).

**Comment by grinapo** [comment]
How simple would be to write a plugin to actually reject private videos? I have some simple plugins but would be neat to know where PT gives info on whether the video was chosen to be private or not.
I run an instance but it's stritly for public interests, so I don't allow private unless I gave permission for az exeption, if ever.

**Comment by Chocobozzz** [comment]
@grinapo https://docs.joinpeertube.org/#/contribute-plugins?id=spammoderation-plugin might interest you

I added helpers to delete privacies you want using a plugin in https://github.com/Chocobozzz/PeerTube/commit/b3af2601da92a6c0835cb2473b4c7a41a0d86e98
