### ISSUE TITLE
Change video kind of fails

### ISSUE THREAD

**Issue by tcitworld** [Chocobozzz/PeerTube#197]
On https://peertube.cpy.re, clicking a « related video » changes the title of the video but not the player. Comments are also not loaded.

Error message
```
t.player.setVideoFiles is not a function
```

**Comment by Chocobozzz** [comment]
Thanks!

Fixed: https://github.com/Chocobozzz/PeerTube/commit/339632b4a3f94a6ebee3767054ef6c701858a785
