### ISSUE TITLE
Playlist thumbnails are pushed off-screen by title

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#1970]
**What happened?**

When viewing my playlists on my phone (Motorola G7) some of the thumbnails are pushed partially offscreen. The viewport will not scroll or resize so that the thumbnails are entirely on-screen, either. This appears to happen because of titles which are longer than the space that would normally be to the right of the thumbnail. Playlists with short titles do not have thumbnails in the wrong position.

**What do you expect to happen instead?**

I expect thumbnails to be lined up in a standard layout and be fully visible.

**Steps to reproduce:**

1. Create a playlist with a long title, and a playlist with a short title.
2. View your list of playlists.

**Additional information**
* PeerTube version or URL: https://peertube.social
* Browser name/version: Firefox for Android

It's possible that this is a CSS issue and that my narrow viewport doesn't play nice with the existing styles. Testing with wider phones may not have the same results as what I'm having, which is why I mentioned what kind of phone I have.

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/b63331ec38eef16bf3e6f44e0b3e81b357607e71
