### ISSUE TITLE
Search results are cut in half (vertically) in mobile browser

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#1971]
**What happened?**

![screenshot of search results, where results are impossible to read because of their position on the screen](https://user-images.githubusercontent.com/8910652/61254669-213aca00-a71a-11e9-8787-0b83ab7188a9.png)

When I do a search on my phone (Motorola G7) the search results are halfway off the screen. I cannot scroll to get any more of it onto the screen. The best I can do is tilt my phone sideways to landscape view, which is obnoxious and only fits one result at a time on my screen.

![screenshot of search results in landscape view, where results are visible but only one is visible at a time](https://user-images.githubusercontent.com/8910652/61254791-b50c9600-a71a-11e9-8972-09810d7bfc0d.png)

**What do you expect to happen instead?**

I expect to be able to see the search results no matter which orientation I have my phone, but especially in portrait mode.

**Steps to reproduce:**
1. Do a search with a thin viewport.

**Additional information**
* PeerTube version or URL: https://peertube.social
* Browser name/version: Firefox for Android

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/dd570a34ff731a6cd98ef8f8bf83f234e804f6c1
