### ISSUE TITLE
Account Joined Date from other platforms is wrong

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#1972]
**What happened?**

Someone followed me from Mastodon. They've had an account for a while now, but when I looked at their "About" page from my instance it said that they joined on today's date (the date they followed me).

**What do you expect to happen instead?**

I expect their "joined" date to be accurate, or if that's not possible I expect it to indicate that it can't be determined.

**Steps to reproduce:**
1. Have an account on Mastodon for more than 24 hours.
2. Follow a PeerTube account that you control.
3. Follow the PeerTube account from the Mastodon account.
4. Check your notifications and click the username for the Mastodon account that followed you.
(is there another way to see who is following you? that might be nice)
5. Navigate to their "About" page and look at the "stats" section.

**Additional information**
* PeerTube version or URL: 1.3.1 (https://peertube.social)
* Browser name/version: Firefox 60.8.0esr

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/a66c2e3252d6cca8958959966f42494ded564023
