### ISSUE TITLE
Avia law in France, The end of PeerTube in France ?

### ISSUE THREAD

**Issue by Jorropo** [Chocobozzz/PeerTube#1974]
I'm very to sad to have to write these line but an important part of peertube community live in France.
There is 395 peertubes instances and 48.1% are hosted in France so somethings like that important. [source](https://instances.joinpeertube.org/)

So, France recently voted a law about hate on internet. (to know what kind of content is in you can find this on [laquadrature.net](https://www.laquadrature.net/2019/07/02/resume-de-la-loi-haine-avant-le-vote-de-demain/) section "Contenus censurés" (french))
But, this law isn't only fancy text and things to do, this also require some technical update 
So what change :
- [ ] An clearly illegal reported content have to be censored 24h after it was signaled (a lawyer of [laquadrature.net](https://laquadrature.net/) told me that even 1h for some specific category). (plus nothing define clearly what is clearly illegal)
     Since we can't ask all administrator to have someone 24/24h 7/7d waiting for report I think we can automaticaly censor all content 23h50m after the report (or 50m if that an 1h report content) and the content is uncensored if the admin/moderator says "that okay !". (I know that an horrible solution but if you have better one, you can find comment bellow) (why 10m and not 1m or 1s ? because activity pub isn't so fast so with 10m we are totaly sure to be on time)
- [ ] Blocking the reposting of banned content. (this is illegal for EU law so we can still hope for some people attacking France on EU courts)
      This is damn fucking hard to do without giants server for scanning the video, because law isn't clear about is reposting, for example does the same video with an other hash ? (maybe due to different keyframe, or just a smaller part) (here again there is comment below)
- [ ] Creating of cooperation tools for fighting hate. (Creating a giant fingerprint DB for searching for illegal content) (#1904 ?)
- [ ] Reporting IP Address and meta data of user posting illegal content. (We will see but maybe we will have to implement an API for that (and I bet that will be very badly written and an horror to implement))
- [ ] Mirroring some illegal content could also make your instances been shutdown (bye bye reprovider)

So that a brief (and incomplete) summery of what I have understand and what I think that important for peertube, also I'm not a lawyer so if you speak French I can just advise you to go read article of [laquadrature.net](https://www.laquadrature.net/2019/07/09/lassemblee-nationale-adopte-et-aggrave-la-loi-haine/) (that mostly my source), this is an 1901 law association fighting for protection of net neutrality, censorship on internet, private data, ...

If you found an error, please report here in comment I'll correct it, I'm not a lawyer.

## The question is do we do now ?
- Do we not implement anythings of that and ask all user to move out side of France and ask all French users to use tor or i2p (because if an website doesn't follow french law it couldn't be shutdown but could be blocked (may depends of EU jurisdiction)), this is simply moving to Holland like VPN ?
- Do we follow French law ?
- Do we move to i2p, ipfs, ... (or any anonymous DHT based solution) ?
- Something else ?

**Comment by TemporaryUsername12481** [comment]
These laws are mainly meant to target big corporations, I doubt that small PeerTube instances would get prosecuted as long as they make a good-faith effort to remove illegal content.

**Comment by Jorropo** [comment]
@TemporaryUsername12481 no, as you can see here :
http://www.assemblee-nationale.fr/dyn/15/amendements/2062/AN/272 (french)
amendement signed by : M. Dunoyer, M. Gomès, Mme Auconie, M. Becht, M. Benoit, M. Guy Bricout, M. Brindeau, M. Christophe, Mme de La Raudière, M. Demilly, Mme Descamps, M. Meyer Habib, M. Herth, M. Lagarde, Mme Lemoine, Mme Magnier, M. Morel-À-L'Huissier, Mme Sanquer, M. Vercamer et M. Zumkeller

You can read :
```
les « géants du web » étant par ailleurs déjà signataires de chartes de bonne conduite en la matière, et disposés à coopérer avec l’État sur la lutte contre la haine, à l’inverse de plus petits opérateurs, moins scrupuleux, mais très actifs dans la propagation des contenus haineux sur internet.
```
Which in English means (not 100% accurate translation) :
```
The " giants of the web " have already signed some charters of good conduct about this and they are willing to cooperate with the state about fighting hate on internet, unlike smaller operators, less scrupulous, but very active in the spread of hate content on the internet.
```
PeerTube full fill at 100% this description (lot of small instances)

**Comment by TemporaryUsername12481** [comment]
Hmm, ok.  I'm not hugely knowledgeable in French politics, but if that's the case, that's really unfortunate.  Censorship will be the downfall of the internet.

Anyway, hope this stuff can get implemented, or the law can be modified to be more fair.

**Comment by Chocobozzz** [comment]
No it's not "the end of PeerTube in France" 
 * There are many different ways to use PeerTube, other than opening registrations to anyone
 * If you correctly moderate your instance, it's unlikely that you would receive this kind of report (yes it probably means self-censorship)
 * I think that dealing with a report in less than 24 hours is possible, if you have a moderation team. Of course it's our job to make the process as efficient as possible . Less than 1 hour is another thing, though 
 * The law is still being discussed. Let's wait for the beginning and end of the vote
