### ISSUE TITLE
Download video if it is private

### ISSUE THREAD

**Issue by diroots** [Chocobozzz/PeerTube#1975]
**What happened?**
i'm connected as a user. 
for the videos which I set to private, the download link shows an error : 

```
error | "Token is invalid."
code | "unauthorized_request"
```

this happens for direct download or torrent download. 
if I switch the visibility of the video to not listed, I can download the video 

one more information, this happened with videos imported from youtube, but I believe it may be the same with an uploaded video. 

**What do you expect to happen instead?**
As I am connected as the user who uploaded the video, I should be able to download it even if it's set to private. 

**Steps to reproduce:**

1. upload a video (or import it from youtube)

2.set visibility to private

3. stay connected and try to download the video

**Additional information**
* PeerTube version or URL:1.3.0
* Browser name/version:firefox  60 / chromium
* NodeJS version:

* Log : 
warn[17/07/2019 à 17:24:59] Cannot authenticate. { "err": { "statusCode": 401, "status": 401, "code": 401, "message": "Unauthorized request: no authentication given", "name": "unauthorized_request", "stack": "unauthorized_request: Unauthorized request: no authentication given\n at new UnauthorizedRequestError (/var/www/peertube/versions/peertube-v1.3.0/node_modules/oauth2-server/lib/errors/unauthorized-request-error.js:28:14)\n at AuthenticateHandler.getTokenFromRequest (/var/www/peertube/versions/peertube-v1.3.0/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:132:9)\n at AuthenticateHandler.<anonymous> (/var/www/peertube/versions/peertube-v1.3.0/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:68:19)\n at AuthenticateHandler.tryCatcher (/var/www/peertube/versions/peertube-v1.3.0/node_modules/oauth2-server/node_modules/bluebird/js/release/util.js:16:23)\n at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v1.3.0/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:512:31)\n at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.3.0/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:569:18)\n at Promise._settlePromiseCtx (/var/www/peertube/versions/peertube-v1.3.0/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:606:10)\n at Async._drainQueue (/var/www/peertube/versions/peertube-v1.3.0/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:138:12)\n at Async._drainQueues (/var/www/peertube/versions/peertube-v1.3.0/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:143:10)\n at Immediate.Async.drainQueues (/var/www/peertube/versions/peertube-v1.3.0/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:17:14)\n at runCallback (timers.js:810:20)\n at tryOnImmediate (timers.js:768:5)\n at processImmediate [as _immediateCallback] (timers.js:745:5)" } }
info[17/07/2019 à 17:24:59] 83.155.194.38 - - [17/Jul/2019:15:24:59 +0000] "GET /download/videos/a8a51ff0-0033-4715-8f99-1b826db0e7f8-720.mp4 HTTP/1.0" 401 59 "https://peer.diroots.info/videos/watch/a8a51ff0-0033-4715-8f99-1b826db0e7f8" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"

**Comment by bristow** [comment]
Download our private videos can be used in order to have compressed video (the server does the job for us)

**Comment by JohnXLivingston** [comment]
Same error here. Peertube v1.4.0.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/eccf70f020cb8b0d9ceddc2561713ccfddb72095
