### ISSUE TITLE
Playlists can have "stuck" videos...

### ISSUE THREAD

**Issue by JigmeDatse** [Chocobozzz/PeerTube#1978]
I don't know what causes this, but I think it is probably something like this:

video gets added to the playlist
video gets removed from the instance
video stays in same position

My "Watch later" playlist starts at video 60, and this results in an issue where when the video number is greater than the number of videos in the playlist, the playlist stops at the end of each video.  (two separate issues I think).

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/pull/1998
