### ISSUE TITLE
About the unsustainable use of online video

### ISSUE THREAD

**Issue by sbernard31** [Chocobozzz/PeerTube#1979]
Regarding last report of [shift project](https://theshiftproject.org) about _**“Climate crisis: the unsustainable use of online video”**_, streaming is a real problem ! :sob: 

Here the report :page_facing_up: :
:gb: : https://theshiftproject.org/en/article/unsustainable-use-online-video/
:fr: : https://theshiftproject.org/article/climat-insoutenable-usage-video/

**Peertube** could follow some simple rules to try to limit its impacts :earth_africa: :
**a)** do not download video if user don't really want to watch it.
**b)** encourage usage of best encoding format like H.264.
**c)** encourage user to use low resolution.

This rules could be declined in features like :
1. for a) no autostart !
2. for b) forbid worst encoding format.
3. for b) add some advice or notation system about encoding format at upload time to nudge user to the right format and resolution. (CO²/bandwish/storage saved if it used a better encoding format)
4. for c) let instance owner define the max resolution.
5. for c) encourage instance owner to use a max resolution as lower as possible.
6. for c) about resolution choice,  auto mode could prefer the lower one.
7. for c) if it exist a resolution lower than the one chosen, a message could be displayed with the CO² saved if the lower resolution was chosen.
8. for c) add an audio only mode.

This features list is just some ideas to illustrate my point, this is not a real TODO list. 
Up to you(we) to find the better feature which will help to follow the above rules.

(**If you vote down, please try to explain why** in a constructive way. Maybe your point of view makes sense and it could be valuable to share it)

**Comment by lapineige** [comment]
Another idea for a) : don't load the full video when you connection is fast enough to load the missing part when watching it.
If you open a video, start to watch it, but pause it and come back later, maybe you will stop and close the tab for some reason. But the player would load the full video anyway.
Instead, the player could load the next (for instance) 10%, or 2min, and then stop until the user resume the playback (or come back to the tab ?)

(this is especially relevant for long videos, talks, movies…)

**Comment by Chocobozzz** [comment]
@lapineige This will be fixed with the HLS player

**Comment by lapineige** [comment]
What does it changes ?

**Comment by Chocobozzz** [comment]
It has a max buffer size, so it won't load the entire video

**Comment by njean42** [comment]
+1 on no autostart (possibly configurable by user?)
+1 on audio-only play mode

**Comment by sbernard31** [comment]
There is an extension for firefox called [Carbonalyser](https://addons.mozilla.org/fr/firefox/addon/carbonalyser/) which help to see your internet carbon footprint.

[This is extension released over MIT license](https://github.com/supertanuki/Carbonalyser).
Reuse [the calculate way ](https://github.com/supertanuki/Carbonalyser/blob/master/popup/popup.js)could help to add some indicator about the video resolution or format impact. 

(see [shitfproject article](https://theshiftproject.org/en/carbonalyser-browser-extension/) for more details)

**Comment by rigelk** [comment]
> I suggest that autoplay should be an option on the video page, and should be disabled after each video session. That means users would have to actively choose to enable autoplay every time they open a video.

@Nutomic That's what I ended up implementing in 88a7f93f8e5666f44121a2e3cf9d33d74c472aa7 for regular videos. By default only playlists go to the next video automatically (can be disabled too).

**Comment by lapineige** [comment]
Sounds like a very good choice :)

**Comment by rigelk** [comment]
I created an eponym tag to help you continue the discussion on more targeted issues, which is the preferred way to adress problems in PeerTube (all-encompassing issues are hard to track over time for us). Please open them as needed, and I will tag them as such.

**Comment by unfa** [comment]
Now I feel bad as a content creator trying to deliver higher quality videos :(

**Comment by njean42** [comment]
> Now I feel bad as a content creator trying to deliver higher quality videos :(

You don't have to. The choice should be in the hands of viewers.
Depending on their connection speed, personal preferences for quality/environment etc., they will select the right video quality for them.
