### ISSUE TITLE
activitypub(Webseed).I have a question.

### ISSUE THREAD

**Issue by zzoozzo1122** [Chocobozzz/PeerTube#198]
hi,guy!

activitypub(Webseed).I have a question.

I set up two test servers to keep the Web seed.

1. https://test4.dv7.co ,[mainserver]
2. https://test2.dv7.co ,[For secondary web seed support]

It was confirmed that both servers of No1 and No2 can log in as administrator after normal setup, 
and that they operate normally when uploading video, respectively.

NO1.server
$yarn install
$npm run build
Upgrade
# systemctl stop peertube
$ npm run upgrade-peertube
# systemctl start peertube
$npm run build:server
So, the setup is complete

NO2,WEB-Seedserver
$yarn install
$npm run build
Upgrade
# systemctl stop peertube
$ npm run upgrade-peertube
# systemctl start peertube
$npm run build:client
So, the setup is complete

Next, go to test4.dv7.co, Administrator's Page - Manage follows-Sachs from
Added test2.dv7.co

Following, Followers In the display area,
State : activated

The same applies for servers at test2.dv7.co

If you upload the mp4 file from the test4.dv7.co main server, you have a problem.
Problems arise!!

At test2.dv7.co the same server, only image files are uploaded.
Mp4 files don't seem to be copied.

test4.dv7.co displays video as peer=1.
If normal, peer=2  I am marked peer=1.

What part setting is wrong? Or is it not yet. Is it the case?
Images, which are synchronized, are
Image files and seeds are not synchronized.
* Firewall has been turned off.

**Comment by Chocobozzz** [comment]
Everything works on my side (videos are played + seeds).

If I watch the same video on server 1 and on server 2, I have two peers:
 * peer 1 that is the webseed server
 * peer 2 that is the other web browser viewer

**Comment by zzoozzo1122** [comment]
Do you mean server number 1 and server number 2 are normal?
Is it working normally?

**Comment by Chocobozzz** [comment]
Yes they are working as expected.
