### ISSUE TITLE
Change the folder of my instance

### ISSUE THREAD

**Issue by raphgilles** [Chocobozzz/PeerTube#1981]
Hello,

I try to change the folder of my instance.

Initially, it was the default folder "/var/www/peertube" and I want to move it to "/home/peertube".

I changed the path in my the production.yaml file, nginx configuration, peertube.service, but I got an error when I try to launch the service : 

> sudo journalctl -feu peertube
juil. 21 06:29:30 ns540724 systemd[14281]: peertube.service: Changing to the requested working directory failed: No such file or directory
juil. 21 06:29:30 ns540724 systemd[14281]: peertube.service: Failed at step CHDIR spawning /usr/bin/npm: No such file or directory
juil. 21 06:29:30 ns540724 systemd[1]: peertube.service: Main process exited, code=exited, status=200/CHDIR
juil. 21 06:29:30 ns540724 systemd[1]: peertube.service: Failed with result 'exit-code'.
juil. 21 06:29:30 ns540724 systemd[1]: peertube.service: Service hold-off time over, scheduling restart.
juil. 21 06:29:30 ns540724 systemd[1]: peertube.service: Scheduled restart job, restart counter is at 5.
juil. 21 06:29:30 ns540724 systemd[1]: Stopped PeerTube daemon.
juil. 21 06:29:30 ns540724 systemd[1]: peertube.service: Start request repeated too quickly.
juil. 21 06:29:30 ns540724 systemd[1]: peertube.service: Failed with result 'exit-code'.
juil. 21 06:29:30 ns540724 systemd[1]: Failed to start PeerTube daemon.

Have you an idea what I can do ?

Thank you !

**Comment by Chocobozzz** [comment]
Hi,

Yes I think you should comment https://github.com/Chocobozzz/PeerTube/blob/develop/support/systemd/peertube.service#L33

**Comment by raphgilles** [comment]
By doing that I always have the same mistake, and this one more:

> juil. 23 14:44:29 ns540724 systemd[1]: Started PeerTube daemon.
juil. 23 14:44:30 ns540724 peertube[12401]: > peertube@1.3.1 start /home/peertube/versions/peertube-v1.3.1
juil. 23 14:44:30 ns540724 peertube[12401]: > node dist/server
juil. 23 14:44:30 ns540724 peertube[12401]: module.js:550
juil. 23 14:44:30 ns540724 peertube[12401]:     throw err;
juil. 23 14:44:30 ns540724 peertube[12401]:     ^
juil. 23 14:44:30 ns540724 peertube[12401]: Error: Cannot find module '/home/peertube/versions/peertube-v1.3.1/dist/server'
juil. 23 14:44:30 ns540724 peertube[12401]:     at Function.Module._resolveFilename (module.js:548:15)
juil. 23 14:44:30 ns540724 peertube[12401]:     at Function.Module._load (module.js:475:25)
juil. 23 14:44:30 ns540724 peertube[12401]:     at Function.Module.runMain (module.js:694:10)
juil. 23 14:44:30 ns540724 peertube[12401]:     at startup (bootstrap_node.js:204:16)
juil. 23 14:44:30 ns540724 peertube[12401]:     at bootstrap_node.js:625:3
juil. 23 14:44:30 ns540724 peertube[12401]: npm ERR! code ELIFECYCLE
juil. 23 14:44:30 ns540724 peertube[12401]: npm ERR! errno 1
juil. 23 14:44:30 ns540724 peertube[12401]: npm ERR! peertube@1.3.1 start: `node dist/server`
juil. 23 14:44:30 ns540724 peertube[12401]: npm ERR! Exit status 1
juil. 23 14:44:30 ns540724 peertube[12401]: npm ERR!
juil. 23 14:44:30 ns540724 peertube[12401]: npm ERR! Failed at the peertube@1.3.1 start script.
juil. 23 14:44:30 ns540724 peertube[12401]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
juil. 23 14:44:30 ns540724 peertube[12401]: npm ERR! A complete log of this run can be found in:
juil. 23 14:44:30 ns540724 peertube[12401]: npm ERR!     /home/peertube/.npm/_logs/2019-07-23T14_44_30_219Z-debug.log
juil. 23 14:44:30 ns540724 systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
juil. 23 14:44:30 ns540724 systemd[1]: peertube.service: Failed with result 'exit-code'.
juil. 23 14:44:30 ns540724 systemd[1]: peertube.service: Service hold-off time over, scheduling restart.
juil. 23 14:44:30 ns540724 systemd[1]: peertube.service: Scheduled restart job, restart counter is at 1.
juil. 23 14:44:30 ns540724 systemd[1]: Stopped PeerTube daemon.
juil. 23 14:44:30 ns540724 systemd[1]: Started PeerTube daemon.
juil. 23 14:44:30 ns540724 peertube[12456]: > peertube@1.3.1 start /home/peertube/versions/peertube-v1.3.1
juil. 23 14:44:30 ns540724 peertube[12456]: > node dist/server
juil. 23 14:44:30 ns540724 peertube[12456]: module.js:550
juil. 23 14:44:30 ns540724 peertube[12456]:     throw err;
juil. 23 14:44:30 ns540724 peertube[12456]:     ^
juil. 23 14:44:30 ns540724 peertube[12456]: Error: Cannot find module '/home/peertube/versions/peertube-v1.3.1/dist/server'
juil. 23 14:44:30 ns540724 peertube[12456]:     at Function.Module._resolveFilename (module.js:548:15)
juil. 23 14:44:30 ns540724 peertube[12456]:     at Function.Module._load (module.js:475:25)
juil. 23 14:44:30 ns540724 peertube[12456]:     at Function.Module.runMain (module.js:694:10)
juil. 23 14:44:30 ns540724 peertube[12456]:     at startup (bootstrap_node.js:204:16)
juil. 23 14:44:30 ns540724 peertube[12456]:     at bootstrap_node.js:625:3
juil. 23 14:44:30 ns540724 peertube[12456]: npm ERR! code ELIFECYCLE
juil. 23 14:44:30 ns540724 peertube[12456]: npm ERR! errno 1
juil. 23 14:44:30 ns540724 peertube[12456]: npm ERR! peertube@1.3.1 start: `node dist/server`
juil. 23 14:44:30 ns540724 peertube[12456]: npm ERR! Exit status 1
juil. 23 14:44:30 ns540724 peertube[12456]: npm ERR!
juil. 23 14:44:30 ns540724 peertube[12456]: npm ERR! Failed at the peertube@1.3.1 start script.
juil. 23 14:44:30 ns540724 peertube[12456]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
juil. 23 14:44:30 ns540724 peertube[12456]: npm ERR! A complete log of this run can be found in:
juil. 23 14:44:30 ns540724 peertube[12456]: npm ERR!     /home/peertube/.npm/_logs/2019-07-23T14_44_30_764Z-debug.log
juil. 23 14:44:30 ns540724 systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
juil. 23 14:44:30 ns540724 systemd[1]: peertube.service: Failed with result 'exit-code'.
juil. 23 14:44:31 ns540724 systemd[1]: peertube.service: Service hold-off time over, scheduling restart.
juil. 23 14:44:31 ns540724 systemd[1]: peertube.service: Scheduled restart job, restart counter is at 2.
juil. 23 14:44:31 ns540724 systemd[1]: Stopped PeerTube daemon.
juil. 23 14:44:31 ns540724 systemd[1]: Started PeerTube daemon.
juil. 23 14:44:31 ns540724 peertube[12510]: > peertube@1.3.1 start /home/peertube/versions/peertube-v1.3.1
juil. 23 14:44:31 ns540724 peertube[12510]: > node dist/server
juil. 23 14:44:31 ns540724 peertube[12510]: module.js:550
juil. 23 14:44:31 ns540724 peertube[12510]:     throw err;
juil. 23 14:44:31 ns540724 peertube[12510]:     ^
juil. 23 14:44:31 ns540724 peertube[12510]: Error: Cannot find module '/home/peertube/versions/peertube-v1.3.1/dist/server'
juil. 23 14:44:31 ns540724 peertube[12510]:     at Function.Module._resolveFilename (module.js:548:15)
juil. 23 14:44:31 ns540724 peertube[12510]:     at Function.Module._load (module.js:475:25)
juil. 23 14:44:31 ns540724 peertube[12510]:     at Function.Module.runMain (module.js:694:10)
juil. 23 14:44:31 ns540724 peertube[12510]:     at startup (bootstrap_node.js:204:16)
juil. 23 14:44:31 ns540724 peertube[12510]:     at bootstrap_node.js:625:3
juil. 23 14:44:31 ns540724 peertube[12510]: npm ERR! code ELIFECYCLE
juil. 23 14:44:31 ns540724 peertube[12510]: npm ERR! errno 1
juil. 23 14:44:31 ns540724 peertube[12510]: npm ERR! peertube@1.3.1 start: `node dist/server`
juil. 23 14:44:31 ns540724 peertube[12510]: npm ERR! Exit status 1
juil. 23 14:44:31 ns540724 peertube[12510]: npm ERR!
juil. 23 14:44:31 ns540724 peertube[12510]: npm ERR! Failed at the peertube@1.3.1 start script.
juil. 23 14:44:31 ns540724 peertube[12510]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
juil. 23 14:44:31 ns540724 peertube[12510]: npm ERR! A complete log of this run can be found in:
juil. 23 14:44:31 ns540724 peertube[12510]: npm ERR!     /home/peertube/.npm/_logs/2019-07-23T14_44_31_478Z-debug.log
juil. 23 14:44:31 ns540724 systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
juil. 23 14:44:31 ns540724 systemd[1]: peertube.service: Failed with result 'exit-code'.
juil. 23 14:44:31 ns540724 systemd[1]: peertube.service: Service hold-off time over, scheduling restart.
juil. 23 14:44:31 ns540724 systemd[1]: peertube.service: Scheduled restart job, restart counter is at 3.
juil. 23 14:44:31 ns540724 systemd[1]: Stopped PeerTube daemon.
juil. 23 14:44:31 ns540724 systemd[1]: Started PeerTube daemon.
juil. 23 14:44:32 ns540724 peertube[12565]: > peertube@1.3.1 start /home/peertube/versions/peertube-v1.3.1
juil. 23 14:44:32 ns540724 peertube[12565]: > node dist/server
juil. 23 14:44:32 ns540724 peertube[12565]: module.js:550
juil. 23 14:44:32 ns540724 peertube[12565]:     throw err;
juil. 23 14:44:32 ns540724 peertube[12565]:     ^
juil. 23 14:44:32 ns540724 peertube[12565]: Error: Cannot find module '/home/peertube/versions/peertube-v1.3.1/dist/server'
juil. 23 14:44:32 ns540724 peertube[12565]:     at Function.Module._resolveFilename (module.js:548:15)
juil. 23 14:44:32 ns540724 peertube[12565]:     at Function.Module._load (module.js:475:25)
juil. 23 14:44:32 ns540724 peertube[12565]:     at Function.Module.runMain (module.js:694:10)
juil. 23 14:44:32 ns540724 peertube[12565]:     at startup (bootstrap_node.js:204:16)
juil. 23 14:44:32 ns540724 peertube[12565]:     at bootstrap_node.js:625:3
juil. 23 14:44:32 ns540724 peertube[12565]: npm ERR! code ELIFECYCLE
juil. 23 14:44:32 ns540724 peertube[12565]: npm ERR! errno 1
juil. 23 14:44:32 ns540724 peertube[12565]: npm ERR! peertube@1.3.1 start: `node dist/server`
juil. 23 14:44:32 ns540724 peertube[12565]: npm ERR! Exit status 1
juil. 23 14:44:32 ns540724 peertube[12565]: npm ERR!
juil. 23 14:44:32 ns540724 peertube[12565]: npm ERR! Failed at the peertube@1.3.1 start script.
juil. 23 14:44:32 ns540724 peertube[12565]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
juil. 23 14:44:32 ns540724 peertube[12565]: npm ERR! A complete log of this run can be found in:
juil. 23 14:44:32 ns540724 peertube[12565]: npm ERR!     /home/peertube/.npm/_logs/2019-07-23T14_44_32_231Z-debug.log
juil. 23 14:44:32 ns540724 systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
juil. 23 14:44:32 ns540724 systemd[1]: peertube.service: Failed with result 'exit-code'.
juil. 23 14:44:32 ns540724 systemd[1]: peertube.service: Service hold-off time over, scheduling restart.
juil. 23 14:44:32 ns540724 systemd[1]: peertube.service: Scheduled restart job, restart counter is at 4.
juil. 23 14:44:32 ns540724 systemd[1]: Stopped PeerTube daemon.
juil. 23 14:44:32 ns540724 systemd[1]: Started PeerTube daemon.
juil. 23 14:44:32 ns540724 peertube[12617]: > peertube@1.3.1 start /home/peertube/versions/peertube-v1.3.1
juil. 23 14:44:32 ns540724 peertube[12617]: > node dist/server
juil. 23 14:44:32 ns540724 peertube[12617]: module.js:550
juil. 23 14:44:32 ns540724 peertube[12617]:     throw err;
juil. 23 14:44:32 ns540724 peertube[12617]:     ^
juil. 23 14:44:32 ns540724 peertube[12617]: Error: Cannot find module '/home/peertube/versions/peertube-v1.3.1/dist/server'
juil. 23 14:44:32 ns540724 peertube[12617]:     at Function.Module._resolveFilename (module.js:548:15)
juil. 23 14:44:32 ns540724 peertube[12617]:     at Function.Module._load (module.js:475:25)
juil. 23 14:44:32 ns540724 peertube[12617]:     at Function.Module.runMain (module.js:694:10)
juil. 23 14:44:32 ns540724 peertube[12617]:     at startup (bootstrap_node.js:204:16)
juil. 23 14:44:32 ns540724 peertube[12617]:     at bootstrap_node.js:625:3
juil. 23 14:44:32 ns540724 peertube[12617]: npm ERR! code ELIFECYCLE
juil. 23 14:44:32 ns540724 peertube[12617]: npm ERR! errno 1
juil. 23 14:44:32 ns540724 peertube[12617]: npm ERR! peertube@1.3.1 start: `node dist/server`
juil. 23 14:44:32 ns540724 peertube[12617]: npm ERR! Exit status 1
juil. 23 14:44:32 ns540724 peertube[12617]: npm ERR!
juil. 23 14:44:32 ns540724 peertube[12617]: npm ERR! Failed at the peertube@1.3.1 start script.
juil. 23 14:44:32 ns540724 peertube[12617]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
juil. 23 14:44:33 ns540724 peertube[12617]: npm ERR! A complete log of this run can be found in:
juil. 23 14:44:33 ns540724 peertube[12617]: npm ERR!     /home/peertube/.npm/_logs/2019-07-23T14_44_33_000Z-debug.log
juil. 23 14:44:33 ns540724 systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
juil. 23 14:44:33 ns540724 systemd[1]: peertube.service: Failed with result 'exit-code'.
juil. 23 14:44:33 ns540724 systemd[1]: peertube.service: Service hold-off time over, scheduling restart.
juil. 23 14:44:33 ns540724 systemd[1]: peertube.service: Scheduled restart job, restart counter is at 5.
juil. 23 14:44:33 ns540724 systemd[1]: Stopped PeerTube daemon.
juil. 23 14:44:33 ns540724 systemd[1]: peertube.service: Start request repeated too quickly.
juil. 23 14:44:33 ns540724 systemd[1]: peertube.service: Failed with result 'exit-code'.
juil. 23 14:44:33 ns540724 systemd[1]: Failed to start PeerTube daemon.

In the logs : 

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v8.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle peertube@1.3.1~prestart: peertube@1.3.1
6 info lifecycle peertube@1.3.1~start: peertube@1.3.1
7 verbose lifecycle peertube@1.3.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle peertube@1.3.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/peertube/versions/peertube-v1.3.1/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle peertube@1.3.1~start: CWD: /home/peertube/versions/peertube-v1.3.1
10 silly lifecycle peertube@1.3.1~start: Args: [ '-c', 'node dist/server' ]
11 silly lifecycle peertube@1.3.1~start: Returned: code: 1  signal: null
12 info lifecycle peertube@1.3.1~start: Failed to exec start script
13 verbose stack Error: peertube@1.3.1 start: `node dist/server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid peertube@1.3.1
15 verbose cwd /home/peertube/versions/peertube-v1.3.1
16 verbose Linux 4.15.0-54-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.16.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error peertube@1.3.1 start: `node dist/server`
22 error Exit status 1
23 error Failed at the peertube@1.3.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Chocobozzz** [comment]
What is the output of `ls -l /home/peertube`, `ls -l /home/peertube/versions/peertube-v1.3.1/` and `ls -l /home/peertube/versions/peertube-v1.3.1/dist`?

**Comment by raphgilles** [comment]
For `ls -l /home/peertube` I have :

> root@ns540724:~ ls -l /home/peertube
total 16
drwxr-xr-x  2 peertube peertube 4096 juil. 21 06:15 config
drwxr-xr-x  2 root     root     4096 juil. 21 10:03 node_modules
lrwxrwxrwx  1 peertube peertube   24 juil. 21 06:13 peertube-latest -> versions/peertube-v1.3.1
drwxr-xr-x 12 peertube peertube 4096 juil. 18 15:07 storage
drwxr-xr-x  3 peertube peertube 4096 juil. 21 06:13 versions
root@ns540724:~

For `ls -l /home/peertube/versions/peertube-v1.3.1/` I have : 

> root@ns540724:~ ls -l /home/peertube/versions/peertube-v1.3.1/
total 524
drwxr-xr-x    4 peertube peertube   4096 juil. 21 06:15 client
drwxr-xr-x    2 peertube peertube   4096 juin  17 06:25 config
-rw-r--r--    1 peertube peertube  12894 juin   3 07:31 CREDITS.md
-rw-r--r--    1 peertube peertube  10298 juin  17 06:25 FAQ.md
-rw-r--r--    1 peertube peertube  34520 avril 10 14:38 LICENSE
drwxr-xr-x 1025 peertube peertube  36864 juil. 21 10:05 node_modules
-rw-r--r--    1 peertube peertube   2589 juil. 22 10:29 npm-debug.log
-rw-r--r--    1 peertube peertube   6734 juin  17 06:38 package.json
-rw-r--r--    1 peertube peertube  22282 juin  17 06:25 README.md
drwxr-xr-x    9 peertube peertube   4096 juin  17 06:25 scripts
drwxr-xr-x    9 peertube peertube   4096 sept. 11  2018 support
-rw-r--r--    1 peertube peertube    582 juin  17 06:25 tsconfig.json
-rw-r--r--    1 peertube peertube 374445 juin  17 06:25 yarn.lock
root@ns540724:~# 

And for `ls -l /home/peertube/versions/peertube-v1.3.1/dist` I have : 

> root@ns540724:~ ls -l /home/peertube/versions/peertube-v1.3.1/dist
ls: cannot access '/home/peertube/versions/peertube-v1.3.1/dist': No such file or directory
root@ns540724:~

**Comment by raphgilles** [comment]
OK.

Resolved by deleting everything but the database and the production.yaml file and by reinstalling all the package.

That's works.

Thank you for your help !

**Comment by seg-faulty** [comment]
@raphgilles

Why on earth would I want to delete everything and reinstall? That isn't "resolving" it, it's just giving up.

Having the same issue right now and your response feels like a punch in my face.

**EDIT:** Changing both `Environment=NODE_CONFIG_DIR` and `WorkingDirectory` in `/etc/systemd/system/peertube.service` to point to the new path and then running `systemctl daemon-reload` as root worked for me. Though the OP says he changed it and it didn't work.
