### ISSUE TITLE
update to angular 8

### ISSUE THREAD

**Issue by BO41** [Chocobozzz/PeerTube#1984]
A new version of angular got [released](https://blog.angular.io/version-8-of-angular-smaller-bundles-cli-apis-and-alignment-with-the-ecosystem-af0261112a27).
There is an [update guide](https://update.angular.io/) on how to update easily.

The new version allows a `save 7–20% of their bundle size`, a new TypeScript version and some other nice features. Nothing should break.
I think this isn't high priority, but keeping up to date is always a good thing.

At the moment [`ngx-qrcode2`](https://github.com/techiediaries/ngx-qrcode) is **not** compatible with angular8 :(

**Comment by Chocobozzz** [comment]
Upgraded in https://github.com/Chocobozzz/PeerTube/commit/f36da21e40104a50acb00132920b835240cebb38
