### ISSUE TITLE
Android/Ios Version planned? 

### ISSUE THREAD

**Issue by SplatHaxUser3** [Chocobozzz/PeerTube#1988]
Heya! I always wanted to change from YouTube to this platform and I'm already enjoying it on Pc but wouldn't it be nice if you can watch PeerTube Videos on the go? And I think much more people would join our Community if there was a Handy application!

**Comment by rigelk** [comment]
You can watch PeerTube videos from Fedilab on Android for instance.

**Comment by realityfabric** [comment]
You can already use PeerTube with your mobile browser (Firefox, Chrome, etc). There are other apps compatible with PeerTube as well.

I use PeerTube most often on my phone in Firefox, and other than a few bugs (which I've reported, and which I suspect most people won't even experience) it works well.

iirc there is no desire to create an Official PeerTube Mobile Application, see #250
