### ISSUE TITLE
Feature Request: Add multiple videos from one torrent file

### ISSUE THREAD

**Issue by StalinEXE** [Chocobozzz/PeerTube#1989]
Is it possible to add an abillity to import multiple videos from one torrent file?
It is very usefull in some scenarios.

For example:

One creator on YouTube made a serie of a good videos, but he removed them with his channel some years later. One user saved each video and uploaded to local torrent tracker. It is a good way to import videos together to PeerTube instance and add them to one Playlist. 

I think that PeerTube should have this function: import torrent file with multiply videos, give an abillity for user to chose what to upload and create playlist for these videos. IMHO it is a great way to backup some YouTube channels, fan translations, fan movies or serials, "how to", let's plays, etc. using popular torrent trackers.

**Comment by Chocobozzz** [comment]
No sorry, it's too much work: just create one torrent per video. Or use the PeerTube API to create your own torrent importer
