### ISSUE TITLE
When the first release?

### ISSUE THREAD

**Issue by ReK2Fernandez** [Chocobozzz/PeerTube#199]
Also, should we create a matrix/riot channel? so we can help people, and answer this questions :) 
my server is pulling from "master" but I notice all the daily updates goes into development.. should I pull from development instead? or when are you guys planning to merge with master?

Cheers <3

**Comment by rigelk** [comment]
There is already a [forum subject](https://framacolibri.org/t/framatube-peertube-posez-nous-vos-questions/) for non-dev users to ask questions. Maybe we could setup some IRC channel.

So far some of us have been running on 'development' just fine, but that's a choice and it can break anytime.

**Comment by Chocobozzz** [comment]
There is an IRC channel on freenode #peertube. see the badge on README, but I think nobody see it so maybe we could add a little sentence about this.

We plan to release a beta in march. And before that some alpha.

So in the future, the master branch will be up to date with the latest release (production branch) and the develop branch is the branch we work on so it might break at anytime (especially for migrations).

**Comment by strypey** [comment]
@rigelk 
> There is already a forum subject for non-dev users to ask questions.

That link seems to be broken.

**Comment by rigelk** [comment]
@strypey corrected :) you can find it [here](https://framacolibri.org/c/qualite/peertube) instead.

**Comment by strypey** [comment]
Cool, thanks @rigelk is there a way to get an english version, or filter the posts for English (otherwise I'm going to spend a lot of time dropping copypasta into a machine translator).

**Comment by rigelk** [comment]
@strypey I'm afraid there's no english version, or way to filter posts (since there is no way for authors to tag with a language) by language. The forum wasn't meant for an international audience, but that doesn't mean you can't post in english there.
