### ISSUE TITLE
peertube-import-videos doesn't import video description

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#1992]
**Steps to reproduce:**
1. Run `node dist/server/tools/peertube-import-videos.js` with `-u` `-U` `--password` `--target-url` and [`--since`](https://github.com/Chocobozzz/PeerTube/pull/1991) parameters on a YT channel (ensure at least one video is being uploaded)
2. Go to the newly uploaded video, read the description

**What happened?** 
The description is filled with `my super description`

Also tags are not correctly imported neither.

![image](https://user-images.githubusercontent.com/371705/62026379-24828b00-b1db-11e9-9128-d3fefd6cb524.png)

**What do you expect to happen instead?**
The description should be filled with the YT video description.

**Useful information**
 - Also you can check the `description` property in the `videoInfo` object. It is filled correctly.
 - FWIW, the value `my super description` must come from this line: https://github.com/Chocobozzz/PeerTube/blob/7545a0941c2a41c65e567ed8bf181f98d0f6f633/shared/extra-utils/videos/videos.ts#L344
 - I am quite sure that's a regression
 - I can spend some time investigating more or fixing it. If you miss time and do not hurry, I would be glad to help!

**Additional information**
* PeerTube version or URL: v1.3.1
* Browser name/version: N/A
* NodeJS version: v10.16.0

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
I'll fix this.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/6f530096cbceda09377c2e8e235cf02c36226989
