### ISSUE TITLE
Provide links to mobile apps inside Peertube

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#1993]
Mastodon has a link to mobile apps (on [this page](https://mastodon.social/about), at the bottom right). The list is [here](https://joinmastodon.org/apps).

For Peertube there is a list in the [documentation](https://docs.joinpeertube.org/#/use-third-party-application), but this is very hard to discover for users.

**Comment by Chocobozzz** [comment]
I added a link to the documentation in https://github.com/Chocobozzz/PeerTube/commit/d8232bac6abfb70953229a4164395f05cec90b35
