### ISSUE TITLE
Don't assume /config is writable in Docker image

### ISSUE THREAD

**Issue by iMartyn** [Chocobozzz/PeerTube#1994]
**What happened?**

When mounting a read-only config (in this case a configmap from kubernetes), the docker image will not start up because the startup script assumes a writable /config directory

**What do you expect to happen instead?**

Allow a read-only config to be mounted in /config

**Steps to reproduce:**

1. mount a readonly filesystem on /config in your docker startup

2. observe failure of script

**Comments**

I would suggest a warning be printed if you do this but not a total failure.

**Additional information**
* PeerTube version or URL: master
* Browser name/version: n/a
* NodeJS version: n/a

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
```
cp: cannot create regular file '/config/default.yaml': Read-only file system
```

**Comment by Chocobozzz** [comment]
This command is useful, and should be considered as a failure since people won't understand why their PeerTube does not work correctly after an upgrade.
