### ISSUE TITLE
Multi Language Title and Description

### ISSUE THREAD

**Issue by StalinEXE** [Chocobozzz/PeerTube#1995]
Can you add an abillity to translate titles and descriptions to another languages for multi language support? It will be great addition for [#939](https://github.com/Chocobozzz/PeerTube/issues/939)

[Feature on YouTube, En](https://support.google.com/youtube/answer/6289575?hl=en)

**Comment by robinkooli** [comment]
YouTube has made it extremely easy to make subtitles for videos. 👍

**Comment by Chocobozzz** [comment]
Duplicate of https://github.com/Chocobozzz/PeerTube/issues/2992
