### ISSUE TITLE
Replace Username with Channel Name (or add nearly) in Overview

### ISSUE THREAD

**Issue by StalinEXE** [Chocobozzz/PeerTube#1996]
It is IMHO, open for discussion and not necessary, but may you replace user's name in Overview with Channel Name? I think it will be better for UX.

Please, take a look at my simple picture, where I take screenshots of YouTube and PeerTube pages.

![Request](https://user-images.githubusercontent.com/1181085/62142076-550b1780-b2f6-11e9-93f0-278dce144e4d.jpg)

RVV Spoony - name of channel
kuzokol - name of user

IMHO, two ways will be great:

1) Just replace
2) Add username to parentheses. 

Example: 
channel_name [by username]
RVV Spoony [by kuzokol]

**Comment by StalinEXE** [comment]
Also, I think that it will be good to replace username with channel name under videos on another pages too, like Accaunt -> Videos. Easily to understand in what channel it was uploaded.

**Comment by Chocobozzz** [comment]
We now display channel in miniatures
