### ISSUE TITLE
PeerTube service fails with: Cannot find module bcrypt_lib.node

### ISSUE THREAD

**Issue by Coonzoba** [Chocobozzz/PeerTube#1997]
**What happened?**
After following the documentation for CentOS and Ubuntu (followed by the "all OS" steps) both installs ended up stuck on this error.

The bcrypt module seems to be there but the file is missing. I'm hesitant to do any of the solutions online as I'm not sure they would build into the correct directory. I'm completely new to Node.JS so I don't want to further break it doing something stupid.

**What do you expect to happen instead?**
PeerTube service to run.

**Steps to reproduce:**

1. Follow this for CentOS 7.6 or Ubuntu 18.04 https://docs.joinpeertube.org/#/dependencies

2.Follow this https://docs.joinpeertube.org/#/install-any-os

**Additional information**
* PeerTube version or URL: v1.3.1
* Browser name/version: Firefox on Fedora 30
* NodeJS version: 12.7.0
* OS : Ubuntu 18.04
* G++ : 7.4.0

```
Jul 31 01:36:57 video systemd[1]: Started PeerTube daemon.
Jul 31 01:36:58 video peertube[1954]: > peertube@1.3.1 start /var/www/peertube/versions/peertube-v1.3.1
Jul 31 01:36:58 video peertube[1954]: > node dist/server
Jul 31 01:36:58 video peertube[1954]: internal/modules/cjs/loader.js:628
Jul 31 01:36:58 video peertube[1954]:     throw err;
Jul 31 01:36:58 video peertube[1954]:     ^
Jul 31 01:36:58 video peertube[1954]: Error: Cannot find module '/var/www/peertube/versions/peertube-v1.3.1/node_modules/bcrypt/lib/binding/bcrypt_lib.node'
Jul 31 01:36:58 video peertube[1954]: Require stack:
Jul 31 01:36:58 video peertube[1954]: - /var/www/peertube/versions/peertube-v1.3.1/node_modules/bcrypt/bcrypt.js
Jul 31 01:36:58 video peertube[1954]: - /var/www/peertube/versions/peertube-v1.3.1/dist/server/helpers/core-utils.js
Jul 31 01:36:58 video peertube[1954]: - /var/www/peertube/versions/peertube-v1.3.1/dist/server.js
Jul 31 01:36:58 video peertube[1954]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
Jul 31 01:36:58 video peertube[1954]:     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
Jul 31 01:36:58 video peertube[1954]:     at Module.require (internal/modules/cjs/loader.js:683:19)
Jul 31 01:36:58 video peertube[1954]:     at require (internal/modules/cjs/helpers.js:16:16)
Jul 31 01:36:58 video peertube[1954]:     at Object.<anonymous> (/var/www/peertube/versions/peertube-v1.3.1/node_modules/bcrypt/bcrypt.js:6:16)
Jul 31 01:36:58 video peertube[1954]:     at Module._compile (internal/modules/cjs/loader.js:777:30)
Jul 31 01:36:58 video peertube[1954]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
Jul 31 01:36:58 video peertube[1954]:     at Module.load (internal/modules/cjs/loader.js:643:32)
Jul 31 01:36:58 video peertube[1954]:     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
Jul 31 01:36:58 video peertube[1954]:     at Module.require (internal/modules/cjs/loader.js:683:19) {
Jul 31 01:36:58 video peertube[1954]:   code: 'MODULE_NOT_FOUND',
Jul 31 01:36:58 video peertube[1954]:   requireStack: [
Jul 31 01:36:58 video peertube[1954]:     '/var/www/peertube/versions/peertube-v1.3.1/node_modules/bcrypt/bcrypt.js',
Jul 31 01:36:58 video peertube[1954]:     '/var/www/peertube/versions/peertube-v1.3.1/dist/server/helpers/core-utils.js',
Jul 31 01:36:58 video peertube[1954]:     '/var/www/peertube/versions/peertube-v1.3.1/dist/server.js'
Jul 31 01:36:58 video peertube[1954]:   ]
Jul 31 01:36:58 video peertube[1954]: }
Jul 31 01:36:58 video peertube[1954]: npm ERR! code ELIFECYCLE
Jul 31 01:36:58 video peertube[1954]: npm ERR! errno 1
Jul 31 01:36:58 video peertube[1954]: npm ERR! peertube@1.3.1 start: `node dist/server`
Jul 31 01:36:58 video peertube[1954]: npm ERR! Exit status 1
Jul 31 01:36:58 video peertube[1954]: npm ERR!
Jul 31 01:36:58 video peertube[1954]: npm ERR! Failed at the peertube@1.3.1 start script.
Jul 31 01:36:58 video peertube[1954]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Jul 31 01:36:58 video peertube[1954]: npm ERR! A complete log of this run can be found in:
Jul 31 01:36:58 video peertube[1954]: npm ERR!     /var/www/peertube/.npm/_logs/2019-07-31T01_36_58_303Z-debug.log
Jul 31 01:36:58 video systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
Jul 31 01:36:58 video systemd[1]: peertube.service: Failed with result 'exit-code'.
Jul 31 01:36:58 video systemd[1]: peertube.service: Service hold-off time over, scheduling restart.
Jul 31 01:36:58 video systemd[1]: peertube.service: Scheduled restart job, restart counter is at 5.
Jul 31 01:36:58 video systemd[1]: Stopped PeerTube daemon.
Jul 31 01:36:58 video systemd[1]: peertube.service: Start request repeated too quickly.
Jul 31 01:36:58 video systemd[1]: peertube.service: Failed with result 'exit-code'.
Jul 31 01:36:58 video systemd[1]: Failed to start PeerTube daemon.
```

**Comment by Chocobozzz** [comment]
Retry the yarn install command, and check if there are errors

**Comment by Coonzoba** [comment]
Thanks for the quick reply Chocobozzz,

When I rerun the yarn install there was indeed errors I'd not noticed before. The issue seems to be that downloading this link, which now gives a 404 error;
https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.5/bcrypt_lib-v3.0.5-node-v72-linux-x64-glibc.tar.gz

The repo author only has v3.0.6 downloads now. I've looked for where I can change this, but can't find it.

**Comment by Chocobozzz** [comment]
Try with NodeJS 8 or 10

**Comment by Coonzoba** [comment]
That worked! There is a bunch of warnings about unmet dependencies though. Will any of these effect PeerTube's functionality?

warning " > file-loader@3.0.1" has unmet peer dependency "webpack@^4.0.0".
warning " > raw-loader@1.0.0" has unmet peer dependency "webpack@^4.3.0".
warning " > sass-loader@7.1.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
warning " > terser-webpack-plugin@1.2.3" has unmet peer dependency "webpack@^4.0.0".
warning " > @angular/core@7.2.11" has incorrect peer dependency "zone.js@~0.8.26".
warning " > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
warning " > css-loader@2.1.1" has unmet peer dependency "webpack@^4.0.0".
warning " > extract-text-webpack-plugin@4.0.0-beta.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
warning " > html-webpack-plugin@3.2.0" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > ngx-qrcode2@0.0.9" has incorrect peer dependency "@angular/core@^6.0.3".
warning " > ngx-qrcode2@0.0.9" has incorrect peer dependency "zone.js@^0.8.26".
warning " > webpack-cli@3.3.0" has unmet peer dependency "webpack@4.x.x".

Would it be better to clear /var/www/peertube and build again?

**Comment by Chocobozzz** [comment]
Nope it should work
