### ISSUE TITLE
When opening new tabs, you don't stay logged in

### ISSUE THREAD

**Issue by LoveIsGrief** [Chocobozzz/PeerTube#2000]
**What happened?**

When opening a new tab in while logged in, the new tab wasn't logged in.

**What do you expect to happen instead?**

To be logged in in new tab

**Steps to reproduce:**

1. Went to https://peertube.live/videos/recently-added
2. Logged in
3. Opened a video in a new tab
4. Wasn't logged in in new tab

**Additional information**
* PeerTube version or URL: https://peertube.live/videos/recently-added
* Browser name/version: Firefox 68.0.1 (64-bits)
* NodeJS version:

* Link to browser console log if useful: [browser.log](https://github.com/Chocobozzz/PeerTube/files/3458108/browser.log)

![afbeelding](https://user-images.githubusercontent.com/2829538/62316172-31cb9e00-b497-11e9-9bce-e7055d968bba.png)

**Comment by bristow** [comment]
I can't reproduce on my instance.

Isn't it because of add-ons on your Firefox ? Could you test again on other browser or without add-ons ?

**Comment by LoveIsGrief** [comment]
I was finally able to reproduce it.

It's dead-simple: activate deletion of cookies when firefox closes. You can do it on a clean profile to test.

The relevat preference should then be `network.cookie.lifetimePolicy=2`

**Comment by Chocobozzz** [comment]
Then it's the intended behaviour

**Comment by LoveIsGrief** [comment]
I'm sorry but no, I strongly disagree. Peertube is the **only** website this is happening to that I've come across. Cookies are deleted at the end of the session. A tab isn't a session. This isn't by any means "normal".

8 aug. 2019 09:19 door notifications@github.com:

**Comment by Aluriak** [comment]
> the **only** website

TBH, some merchant websites have that kind of behavior, but it's mostly a bug that they don't bother to fix. I got few exchanges with the support of some of these websites: they prefer to offer a reduction to the occasional unsatisfied client instead of paying someone to fix the bug.

**Comment by LoveIsGrief** [comment]
Would you accept a PR to fix this @Chocobozzz ?

**Comment by Chocobozzz** [comment]
sure

**Comment by LoveIsGrief** [comment]
The issue seems to be with the localstorage which turns into sessionstorage with the preference activated in firefox. I'm creating a bug on firefox's bugzilla to see if that's expected behavior.

Would you accept a pullrequest that moves to cookies instead of localstorage for authentication? I can't conceive of a simple fallback method localstorage -> cookie, hence the suggestion

**Comment by Chocobozzz** [comment]
> Would you accept a pullrequest that moves to cookies instead of localstorage for authentication

No, we don't want to send this kind of information to the server.

**Comment by LoveIsGrief** [comment]
Understood.

Then I'll have to wait for a response from the firefox devs on the issue ([localStorage transformed into sessionStorage by network.cookie.lifetimePolicy=2](https://bugzilla.mozilla.org/show_bug.cgi?id=1572700)).

I'll leave it up to you whether to close this or not.

Thanks for your time

**Comment by AutomCoding** [comment]
FYI: It has now been fixed in the latest beta release of Firefox.
