### ISSUE TITLE
Missing streaming-playlists folder in nginx config file

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2001]
I think you forgot to add the streaming-playlists folder in the nginx config, in the location ^/static/(webseed|redundancy)/

Consequently, the limit_rate don't apply.

* PeerTube version or URL: 1.3.1

**Comment by Chocobozzz** [comment]
We don't need the limit rate because the HLS library only downloads what it needs (unlike webtorrent, that downloads the entire video as fast as it can).

**Comment by JohnXLivingston** [comment]
Oh yes, you are right. 
But, if I understand how it works, the request goes through peertube. So It is not optimal. I'm I right ?

**Comment by Chocobozzz** [comment]
I think it's fine because HLS segments are much larger, so the client does not make many requests (unlike webtorrent, and it was the reason why we bypass peertube with nginx).

**Comment by JohnXLivingston** [comment]
Ok. I close the issue.

**Comment by Nutomic** [comment]
I think it might still be good to have a rate limit, for custom clients that try to download as fast as possible. Its never good to rely on the client behaving well.
