### ISSUE TITLE
Allow setting a date for originallyPublishedAt when importing video

### ISSUE THREAD

**Issue by frankstrater** [Chocobozzz/PeerTube#2006]
**What happened?**

Importing a video through the API with [POST /videos/imports](https://docs.joinpeertube.org/api-rest-reference.html#tag/Video/paths/~1videos~1imports/post) takes the date of the video file as a value for originallyPublishedAt.

**What do you expect to happen instead?**

I would expect that you can set a value for originallyPublishedAt, just like with POST /videos/upload and only use the date of the video file if it's not posted as a value.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/8a86e5dc4f04d7fb07d012fbe2cb7ab3baadbf19
