### ISSUE TITLE
Feature Request: Allow editing multiple videos

### ISSUE THREAD

**Issue by LoveIsGrief** [Chocobozzz/PeerTube#2009]
**What happened?**

Uploaded multiple videos and forgot to specify the license for all of them. Also wanted to sort them into playlists. Had to edit them all individually.

**What do you expect to happen instead?**

To select multiple videos and edit their license, language and add them to playlists.

**Steps to reproduce:**

1. Go to /my-account/videos

2. Select multiple videos

**Additional information**
* PeerTube version or URL:  https://video.ploud.fr/my-account/videos
* Browser name/version: Firefox 68

**Comment by Chocobozzz** [comment]
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1980

**Comment by LoveIsGrief** [comment]
I didn't find the right keywords to find the other one.

Thank you.
