### ISSUE TITLE
Allow admin to tag the instance for /config/about API

### ISSUE THREAD

**Issue by LoveIsGrief** [Chocobozzz/PeerTube#2010]
Related to #430 , it would be great if the `/config/about` API included a string array field "tags".

Example usecases could be:

 - filtering https://instances.joinpeertube.org/instances by tag
 - further down the road following or blocking instances by tag

**Comment by Chocobozzz** [comment]
We were thinking of adding themes (that would be video categories: https://github.com/Chocobozzz/PeerTube/issues/1509#issue-394140762)

**Comment by LoveIsGrief** [comment]
If it's semantically the same, then I guess this issue can be closed without regard, otherwise it'd be nice to add it to the list of requirements for that issue and then close this one :slightly_smiling_face:
