### ISSUE TITLE
HLS bug ?

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2011]
**What happened?**

HLS file sizes are weird.
For example for this video:
![image](https://user-images.githubusercontent.com/38844060/62696437-b60eab80-b9d8-11e9-8a81-c5b264ab4f84.png)

The 480-fragmented file size is as big as the original 1080 file. Is this normal ?

**Additional information**
* PeerTube version or URL: 1.3.1

**Comment by Chocobozzz** [comment]
Hi,

Yes you're right it's a bug I fixed last week: https://github.com/Chocobozzz/PeerTube/commit/29d4e1375fdac88595347184c3d1b214804794b0 :)

**Comment by JohnXLivingston** [comment]
Is there a way to fix these files ?

**Comment by Chocobozzz** [comment]
no sorry

**Comment by JohnXLivingston** [comment]
Have you planned to release the fix shortly ?
Is there a way to remove buggy hls files (as if the video is not available in hls)
