### ISSUE TITLE
HLS videos don't resume

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2013]
**What happened?**

I'm not 100% sure, but it seems that hls videos don't resume, and start at the beginning every time. 

**Additional information**
* PeerTube version or URL: https://www.yiny.org (v1.3.1)
* Browser name/version: Firefox

**Comment by AutomCoding** [comment]
It works fine for me in the latest version of Firefox (no plugins) and same PeerTube version. Do you have video history enabled on your account?

**Comment by JohnXLivingston** [comment]
Yes I have video history enabled.
I made more tests today. And sometime it works, sometime note. Can't figure out why.

**Comment by JohnXLivingston** [comment]
It seems that for this video:
https://www.yiny.org/videos/watch/50b09965-59e6-4e1d-aa31-227828fcb7f1
It always start at the beginning.
But for this one:
https://www.yiny.org/videos/watch/9e63d435-9bd9-43e6-9a21-601d913c3ba6
It resumes well.

**Comment by JohnXLivingston** [comment]
Here is a link that should start at 48s. But for me, it starts always at 0.
https://www.yiny.org/videos/watch/50b09965-59e6-4e1d-aa31-227828fcb7f1?start=48s

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed in https://github.com/Chocobozzz/PeerTube/commit/e028d983727f7826f5aebfe84770c5c37a712b4d

**Comment by JohnXLivingston** [comment]
Thanks !
