### ISSUE TITLE
Search request stay stuck in PGSQL

### ISSUE THREAD

**Issue by maxdrash** [Chocobozzz/PeerTube#2015]
Hi.

I encounter a bug when searching in Peertube.
Just enter a keyword and the request gets stuck in postgresql for more than 20 minutes, which creates an overload on the server.
The workers are 100% as long as the request remains stuck, which makes many problems.

Do you have any ideas to fix this problem?

**Steps to reproduce:**

1. Just searching for a word
2. Wait and wait.

**Additional information**
* PeerTube version or URL: 1.3.1
* NodeJS version: v10.15.2
* PostgreSQL version: 11.5
* Link to browser console log if useful:
https://pastebin.com/FC1d6dBV
and after 30 minutes:
https://pastebin.com/Mt2JDYWA

Thank you.

**Comment by maxdrash** [comment]
While waiting to investigate the origin of the problem, I placed "statement_timeout" in the pgsql conf.
The problem does not happen again, whereas I restarted pgsql about twenty times today to look for the trouble.

I don't understand why ...

**Comment by maxdrash** [comment]
I can't reproduce the problem since the opening of this issue.
Server is performing as before.
A physical check has been completed: nothing to report.
The logs have been reviewed: nothing to report.

🤷‍♂️

**Comment by maxdrash** [comment]
I close this issue.

**Comment by diazepan** [comment]
I'm having the same issue since I upgraded my database from psql 9.6 to psql 11
