### ISSUE TITLE
Difference in describing upload limit

### ISSUE THREAD

**Issue by bartart3d** [Chocobozzz/PeerTube#2017]
**What happened?**
Confusion about upload limit due to limited description on user info page. An upload failed because it exceeded the upload limit. My bad, the video was rendered too big, but after checking my info page I read : _Video Quota 70MB / unlimited_, so I assumed my limit had dropped to 70MB, while I thought it was 500MB as mentioned on the 'about' of the instance.
The '70M' actually meant I had in a previous upload already uploaded 70MB. The text does not refer to 'already uploaded'.

**What do you expect to happen instead?**
I expect to read "Uploaded amount", perhaps even: "Already uploaded amount (Daily): 0MB and Already uploaded 70MB (total)" or something similar to make it clear these numbers talk about 'already uploaded amount'.

Another idea would make a full sentence of it, such as:

> Today you have already uploaded 0MB of video, in total you have uploaded 70MB of unlimited. (Your daily limit is 500MB and your total limit is unlimited.)

**Steps to reproduce:**

1.

2.

3.

**Additional information**
Used peertube instance was peertube.social
* PeerTube version or URL:
v1.3.1
* Browser name/version:
* NodeJS version:
* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/66fd15160e633d98fd7933ffe4abb6c55fcd1755
