### ISSUE TITLE
Handle bad sort error in admin tables

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#2019]
**What happened?**

When using the moderation tools, if you change the field used to sort the data and then try to view any other section (e.g. sorting by username under the users section and then clicking on the moderation link) it will display an error message in the lower right corner: "Should have correct sortable column"

In order to view the section without an error (which prevents any data from displaying) I have to go back and sort by the default column again.

**What do you expect to happen instead?**

I expect it to display the section I'm trying to view without an error message. It looks like the API is being asked to sort by a column that doesn't exist (see the logs section below)... in this case, I expect it to ignore the sort request and sort by the default.

Or, possibly even better, leave out the sort argument from the API when following a link.

**Steps to reproduce:**

1. Log into an account with admin/moderation privileges.

2. Visit the administrator panel.

3. Sort by username.

4. Click the link to the section for moderation. It will throw an error. This will happen if you sort by pretty much any field other than a date/time field and then try to view another section.

**Additional information**
* PeerTube version or URL: v1.3.1
* Browser name/version: Google Chrome v76.0 64-bit
* Link to browser console log if useful:

This is the only thing I think is useful from the console logs (domain stripped):

``` javascript
Backend returned code 400, errorMessage is: Should have correct sortable column
```
and
``` javascript
GET https://[domain]/api/v1/videos/blacklist?start=0&count=10&sort=username 400
```

**Comment by Chocobozzz** [comment]
You just need to change the sort of the videos blacklist table (this is the origin of your error)

**Comment by Chocobozzz** [comment]
I fixed an issue about admin table sort. Just reorder the table using the column, and the bug should not happen anymore on this specific table.
