### ISSUE TITLE
Almost impossible to view likes/dislikes on mobile

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#2020]
**What happened?**

Any feature that utilizes a hover attribute is pretty much impossible to use with a touch screen. The likes/dislikes feature is pretty subtle even on a desktop/laptop, but on a phone you can't view the numbers unless you're really lucky.

**What do you expect to happen instead?**

I expect to be able to view the number of likes/dislikes on a video on my phone or any other touch screen device.

**Steps to reproduce:**

1. Use PeerTube on a phone.

2. Find a video with likes and/or dislikes.

3. Try your best to see the number. Tapping might make the numbers flash up for a split second.

**Additional information**
* PeerTube version or URL: v1.3.1
* Browser name/version: Firefox for Android

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/0d3a9be9f13c2642cb6cf26fdebc5edf5217bbbc
