### ISSUE TITLE
Transcoding CLI only creates one resolution with HLS enabled

### ISSUE THREAD

**Issue by Findus23** [Chocobozzz/PeerTube#2021]
Maybe related to https://github.com/Chocobozzz/PeerTube/issues/2011

**What happened?**

I wanted to try out HLS, enabled the option, re-transcoded one video, but only one resultion was created. 

**What do you expect to happen instead?**

Use HLS with all resultions that are enabled on the server

**Steps to reproduce:**

The config is the following (same in the admin UI (all checked))
```yaml
transcoding:
  enabled: true
  threads: 1
  allow_additional_extensions: true
  resolutions:
    240p: true
    360p: true
    480p: true
    720p: true
    1080p: true
  hls:
    enabled: true
```

After updating to 1.4.0-rc.1 I wanted to try out the HLS feature. So I enabled it in the config, restarted Peertube, took an [old video](https://video.lw1.at/videos/watch/29fa7c87-aed0-40db-9d07-22c1890ed855) and ran transcoding for it again:
```bash
sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run create-transcoding-job -- -v 29fa7c87-aed0-40db-9d07-22c1890ed855
```

But only the 1080 has been created:
```
➜  /var/…/peertube-latest/scripts l ../../../storage/streaming-playlists/hls/29fa7c87-aed0-40db-9d07-22c1890ed855/
Permissions Size User     Date Modified Name
.rw-r--r--  1.9M peertube 13 Aug 19:28  29fa7c87-aed0-40db-9d07-22c1890ed855-1080-fragmented.mp4
.rw-r--r--   523 peertube 13 Aug 19:28  1080.m3u8
.rw-r--r--   106 peertube 13 Aug 19:28  master.m3u8
.rw-r--r--   314 peertube 13 Aug 19:28  segments-sha256.json
```

The video plays fine using HLS, but the quality selector also only shows 1080 as a possibility.
The error log shows `Error: dest already exists` (see below).

**Additional information**
* PeerTube version or URL:  1.4.0-rc.1 (https://video.lw1.at/)
* NodeJS version: v10.16.2

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
```
info[13/08/2019, 19:28:00] Processing video file in job 66.
info[13/08/2019, 19:28:01] Creating torrent /var/www/peertube/storage/torrents/29fa7c87-aed0-40db-9d07-22c1890ed855-1080.torrent.
info[13/08/2019, 19:28:01] Resolutions computed for video 29fa7c87-aed0-40db-9d07-22c1890ed855 and origin file height of 1080. { "resolutions": [ 480, 360, 720, 240 ] }
info[13/08/2019, 19:28:01] Transcoding jobs created for uuid 29fa7c87-aed0-40db-9d07-22c1890ed855. { "resolutionsEnabled": [ 480, 360, 720, 240 ] }
info[13/08/2019, 19:28:01] Creating job to update video https://video.lw1.at/videos/watch/29fa7c87-aed0-40db-9d07-22c1890ed855.
info[13/08/2019, 19:28:01] Processing ActivityPub broadcast in job 198.
info[13/08/2019, 19:28:01] Processing video file in job 67.
info[13/08/2019, 19:28:05] Updating 55 good actor follows and 9 bad actor follows scores in cache.
error[13/08/2019, 19:28:06] Cannot execute job 67 in queue video-transcoding. { "payload": { "type": "new-resolution", "videoUUID": "29fa7c87-aed0-40db-9d07-22c1890ed855", "resolution": 480 }, "err": { "stack": "Error: dest already exists.\n at pathExists (/var/www/peertube/versions/peertube-v1.4.0-rc.1/node_modules/fs-extra/lib/move/move.js:41:31)\n at fn.apply.then.r (/var/www/peertube/versions/peertube-v1.4.0-rc.1/node_modules/universalify/index.js:23:46)", "message": "dest already exists." } }
info[13/08/2019, 19:28:06] Processing video file in job 68.
error[13/08/2019, 19:28:10] Cannot execute job 68 in queue video-transcoding. { "payload": { "type": "new-resolution", "videoUUID": "29fa7c87-aed0-40db-9d07-22c1890ed855", "resolution": 360 }, "err": { "stack": "Error: dest already exists.\n at pathExists (/var/www/peertube/versions/peertube-v1.4.0-rc.1/node_modules/fs-extra/lib/move/move.js:41:31)\n at fn.apply.then.r (/var/www/peertube/versions/peertube-v1.4.0-rc.1/node_modules/universalify/index.js:23:46)", "message": "dest already exists." } }
info[13/08/2019, 19:28:10] Processing video file in job 69.
error[13/08/2019, 19:28:18] Cannot execute job 69 in queue video-transcoding. { "payload": { "type": "new-resolution", "videoUUID": "29fa7c87-aed0-40db-9d07-22c1890ed855", "resolution": 720 }, "err": { "stack": "Error: dest already exists.\n at pathExists (/var/www/peertube/versions/peertube-v1.4.0-rc.1/node_modules/fs-extra/lib/move/move.js:41:31)\n at fn.apply.then.r (/var/www/peertube/versions/peertube-v1.4.0-rc.1/node_modules/universalify/index.js:23:46)", "message": "dest already exists." } }
info[13/08/2019, 19:28:18] Processing video file in job 70.
error[13/08/2019, 19:28:21] Cannot execute job 70 in queue video-transcoding. { "payload": { "type": "new-resolution", "videoUUID": "29fa7c87-aed0-40db-9d07-22c1890ed855", "resolution": 240 }, "err": { "stack": "Error: dest already exists.\n at pathExists (/var/www/peertube/versions/peertube-v1.4.0-rc.1/node_modules/fs-extra/lib/move/move.js:41:31)\n at fn.apply.then.r (/var/www/peertube/versions/peertube-v1.4.0-rc.1/node_modules/universalify/index.js:23:46)", "message": "dest already exists." } }
info[13/08/2019, 19:28:21] Processing video file in job 71.
info[13/08/2019, 19:28:22] Creating job to update video https://video.lw1.at/videos/watch/29fa7c87-aed0-40db-9d07-22c1890ed855.
info[13/08/2019, 19:28:22] Processing ActivityPub broadcast in job 199.
info[13/08/2019, 19:28:23] Updating 56 good actor follows and 8 bad actor follows scores in cache. 
```

**Comment by Findus23** [comment]
@Chocobozzz You are right, this seems to be purly a CLI bug. I just uploaded a new video and it got properly converted into all resolution.

**Comment by Findus23** [comment]
Okay, I have a few more details:
I guessed that the move from the log was this one:
https://github.com/Chocobozzz/PeerTube/blob/d636ab58d042494ef9d17b2d9c4c841bae01c897/server/lib/video-transcoding.ts#L172
So I added a `console.log(transcodingPath, outputPath)`

This has printed the following paths:
```
/var/www/peertube/storage/tmp/29fa7c87-aed0-40db-9d07-22c1890ed855-240.mp4 
/var/www/peertube/storage/videos/29fa7c87-aed0-40db-9d07-22c1890ed855-240.mp4
```
I guess the issue is that it refuses to overwrite the existing file.

**Comment by Findus23** [comment]
Renaming the `/var/www/peertube/storage/videos/29fa7c87-aed0-40db-9d07-22c1890ed855-*` files (apart fro the 1080 one) just makes everything worse as the database still has the records and therfore we get constrains: `SequelizeUniqueConstraintError`, `videoId must be unique`, `duplicate key value violates unique constraint \"video_file_video_id_resolution_fps\"`.

I guess there isn't a trivial fix.

**Comment by JohnXLivingston** [comment]
Just for the record, I reproduced the error (and had the log `Error: dest already exists`)

**Comment by Chocobozzz** [comment]
Please, can you reproduce with the current develop branch? I updated this script.

**Comment by McFlat** [comment]
Not sure if this should go in a separate issue. Thank you guys for all your hard work on this project!

I'm having a lot of `video-transcoding` `failed` errors.

<img width="1032" alt="Screen Shot 2020-01-01 at 3 41 43 PM" src="https://user-images.githubusercontent.com/43896676/71646397-8163ff00-2cad-11ea-8cb4-6698e9d8aaf3.png">

{   "type": "hls",   "videoUUID": "deaf53e2-c64b-48d3-b90a-e378de6bedd0",   "resolution": 720 }
--
Error: ffmpeg exited with code 1: Unrecognized option 'hls_segment_type'. Error splitting the argument list: Option not found      at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v2.0.0/node_modules/fluent-ffmpeg/lib/processor.js:182:22)     at ChildProcess.emit (events.js:210:5)     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

**Comment by Chocobozzz** [comment]
@McFlat check your ffmpeg version: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L236
