### ISSUE TITLE
Can't list plugins and themes

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2022]
**What happened?**

After upgrading to v1.4.0-rc.1, I went to the new plugin/theme page.
I got the following error:
```error[14/08/2019 à 00:49:06] Cannot list available plugins from index https://packages.joinpeertube.org/api/v1/plugins. { "err": { "stack": "TypeError: Cannot read property 'data' of undefined\n at /var/www/peertube/versions/peertube-v1.4.0-rc.1/dist/server/lib/plugins/plugin-index.js:44:32\n at Generator.next (<anonymous>)\n at /var/www/peertube/versions/peertube-v1.4.0-rc.1/dist/server/lib/plugins/plugin-index.js:7:71\n at new Promise (<anonymous>)\n at __awaiter (/var/www/peertube/versions/peertube-v1.4.0-rc.1/dist/server/lib/plugins/plugin-index.js:3:12)\n at addInstanceInformation (/var/www/peertube/versions/peertube-v1.4.0-rc.1/dist/server/lib/plugins/plugin-index.js:43:12)\n at Object.<anonymous> (/var/www/peertube/versions/peertube-v1.4.0-rc.1/dist/server/lib/plugins/plugin-index.js:32:19)\n at Generator.next (<anonymous>)\n at fulfilled (/var/www/peertube/versions/peertube-v1.4.0-rc.1/dist/server/lib/plugins/plugin-index.js:4:58)", "message": "Cannot read property 'data' of undefined" } } ```

But if I open https://packages.joinpeertube.org/api/v1/plugins in my browser, it seems to be correct.

**Additional information**
* PeerTube version or URL: v1.4.0-rc1
* NodeJS version: v10.15.2

**Comment by Chocobozzz** [comment]
Thanks and sorry about that. It should work now

**Comment by McFlat** [comment]
Getting Error 404 from https://packages.joinpeertube.org
