### ISSUE TITLE
Show/Hide Title button for sensitive videos instead of hovertext

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#2024]
**What happened?**

Hovering over an `<a>` section which has a title results in the title being displayed in something similar to a tool-tip.

This happens even with NSFW content which is blurred out.

![image](https://user-images.githubusercontent.com/8910652/62993849-08533080-be0e-11e9-9846-27e4f9535b39.png)
 
**What do you expect to happen instead?**

While the ability to selectively show/hide titles and thumbnails would be nice, I expect that if the video title is hidden then it shouldn't pop up when hovering over the video thumbnail.

A possible solution would be to simply remove the title attribute when blurring the video, or to change the title to indicate that the contents are being hidden due to the NSFW flag.

**Steps to reproduce:**

1. Set your NSFW video settings to "blur" (as opposed to hide or show)
2. Find a video marked as NSFW which is blurred out.
3. Hover over the video thumbnail. The title should pop up and be visible in the 'tool-tip'.

**Additional information**
* PeerTube version or URL: v1.3.1 (tested on two servers of the same version)
* Browser name/version: Google Chrome v76.0 64bit

* HTML attribute copied from the Inspect Element tools:

```
<a _ngcontent-c18="" class="video-thumbnail" title="Game of disappoints (spoilers)" href="/videos/watch/33f5bd00-dc94-45ad-a957-5b97abec48eb"><img _ngcontent-c18="" alt="" class="blur-filter" aria-labelledby="Game of disappoints (spoilers)" src="https://betamax.video/static/thumbnails/33f5bd00-dc94-45ad-a957-5b97abec48eb.jpg"><div _ngcontent-c18="" class="video-thumbnail-duration-overlay">00:17</div><div _ngcontent-c18="" class="play-overlay"><div _ngcontent-c18="" class="icon"></div></div><!----></a>
```

I modified the title attribute and the hover changed to match.

**Comment by Chocobozzz** [comment]
I kept this title attribute so you don't have to click on the video to know what i's about

**Comment by realityfabric** [comment]
Okay, so it was intentional. I can understand that, but I don't think it's the best way to handle it. A "Show/Hide Title" or similar option would be better, so that users have to intentionally opt into reading the title, instead of accidentally seeing it because they put the mouse cursor in the wrong place.

This also prevents mobile users from using that feature, because mobile users can't hover.

**Comment by kyrahabattoir** [comment]
I figured i would give my two cents but the tooltip is kind of important for browsing.
![firefox_2021-01-20_18-52-01](https://user-images.githubusercontent.com/598409/105214833-cecd3b80-5b50-11eb-9e29-0454c5ae836f.png)

I agree with @Chocobozzz it's pretty unbearable to browse with blur enabled otherwise.

**Comment by realityfabric** [comment]
Hover isn't available on mobile, so mobile users have to click on the video to find out what it is. As someone who uses the internet primarily through my phone this is unbearable.

A "Show Title" button solves this problem and is far more intuitive than a hover. You lose nothing by adding this, and make the site more usable on mobile, and more intuitive in general.

**Comment by realityfabric** [comment]
I changed the title to reflect that this is no longer a bug report and is instead a feature request. Hopefully this will avoid misunderstandings.

**Comment by Chocobozzz** [comment]
Closing this issue in favour of https://github.com/Chocobozzz/PeerTube/issues/6144
