### ISSUE TITLE
Can't update playlist thumbnail

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#2025]
**What happened?**

I tried to edit an existing playlist to add a custom thumbnail, but the thumbnail is still the one it had before. This isn't a problem with new playlists.

**What do you expect to happen instead?**

I expect to be able to change the thumbnail on my playlists.

**Steps to reproduce:**

1.  Create a playlist. You can either add a thumbnail when creating the playlist, or add videos to the playlist without adding a custom thumbnail. Either will reproduce this problem.
2. Edit the playlist and upload a different thumbnail.
3. Save the playlist... the thumbnail will not have changed.

**Additional information**
* PeerTube version or URL: v1.3.1
* Browser name/version: Chrome 76.0 64bit

**Comment by realityfabric** [comment]
It's possible there's some sort of delay in it being updated, because when I opened my playlists tab just now the thumbnail had updated. 

I tried to change it again, and it hasn't changed yet. I thought maybe it updated because I had closed my browser and reopened it, but restarting my browser didn't do anything. The thumbnail updated to what I set it as last night on both my desktop (Chrome 76.0) and my phone (Firefox for Android) as of now.

I'll check again later to see if the one I just uploaded appears.

**Comment by realityfabric** [comment]
Okay, it seems like it's a delay. The thumbnail is updating, it just takes a while for it to happen. Maybe it's a caching problem?

**Comment by Nutomic** [comment]
Right, I set up a caching reverse proxy on peertube.social. So static assets are cached, timeout is 2 hours afaik (set by Peertube). Is this a big problem? It is reducing CPU load from Peertube a lot, because otherwise it would have to deal with a lot of requests .

**Comment by realityfabric** [comment]
Other than having no warning that there may be a delay I'd say there's no problem at all. It's a minor inconvenience that I doubt most people will even notice.

**Comment by Nutomic** [comment]
No idea how you would go warning about that. Should probably be inside Peertube then?
