### ISSUE TITLE
Thumbnail preview doesn't work when editing playlists

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#2026]
**What happened?**

When creating or editing playlists, the thumbnail preview shows a broken image icon instead of a preview of the uploaded thumbnail.

**What do you expect to happen instead?**

The uploaded thumbnail should be visible so that it can be viewed before changes are saved and are visible to the playlist audience.

**Steps to reproduce:**
1. Begin creating a playlist. 
    No thumbnail exists, so no error message appears in console logs (see below in console log section).
2. Upload a thumbnail. 
    Error is logged to the console indicating security policy violation. 
    Broken image icon appears where the preview of the thumbnail should be.
3. Save the playlist.
4. Edit the playlist. 
    Error message appears in console log, broken image icon where thumbnail preview should be.
5. Attempt to upload a new thumbnail. 
    Another error in the console log, still no preview.

**Additional information**

* PeerTube version or URL: v1.3.1
* Browser name/version: Chrome 76.0
* Link to browser console log if useful:

```
Refused to load the image 'blob:https://[domain]/[UUID] because it violates the following Content Security Policy directive: "img-src 'self' data:".
```

(this log output is repeated with a different UUID each time you edit the playlist or attempt to upload a new thumbnail)

**Comment by Chocobozzz** [comment]
Please try when you instance will be upgraded to 1.4

**Comment by realityfabric** [comment]
Okay, I'll get back to you when my instance has upgraded.

**Comment by realityfabric** [comment]
Still receiving the same error message in the console log after upgrading to v1.4.0-rc.1

```
Refused to load the image 'blob:https://[DOMAIN]/[UUID]' because it violates the following Content Security Policy directive: "img-src 'self' data:".
```

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/ebe7f5872617311e33dbca1f7f0d2556932c01a0
