### ISSUE TITLE
Allow using Finnish language on PeerTube

### ISSUE THREAD

**Issue by robinkooli** [Chocobozzz/PeerTube#2028]
I've translated 70.82% of PeerTube to Finnish on Zanata past few months on my spare time and I think it has enough translated to be added to PeerTube.

Rest of the untranslated strings are mainly things that show to administrators or are edge cases.

**Comment by Chocobozzz** [comment]
Done in https://github.com/Chocobozzz/PeerTube/commit/820546916cad3ae4cc51eab408aef7bbaff3632f. Thanks!
