### ISSUE TITLE
Migration to the new production guide

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#203]
The production installation/upgrade was updated: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md

The goal is to use Github releases in order to avoid administrators building the client themselves (long process).

If you used the old production guide to test PeerTube, you'll need to make some manual steps:

Create `peertube` user if not already exists:

```
sudo useradd -m -d /var/www/peertube -s /bin/bash -p peertube peertube
```

Prepare PeerTube directories:
```
VERSION=$(curl -s https://api.github.com/repos/chocobozzz/peertube/releases/latest | grep tag_name | cut -d '"' -f 4) && \
    cd /var/www/peertube && \
    sudo -u peertube mkdir config storage versions && \
    cd versions && \
    sudo -u peertube wget "https://github.com/Chocobozzz/PeerTube/releases/download/${VERSION}/peertube-${VERSION}.zip" && \
    sudo -u peertube unzip peertube-${VERSION}.zip && sudo -u peertube rm peertube-${VERSION}.zip && \
    cd ../ && sudo -u peertube ln -s versions/peertube-${VERSION} ./peertube-latest && \
    cd ./peertube-latest && sudo -u peertube yarn install --production --pure-lockfile
```

Copy your old production configuration to the new emplacement:

```
sudo cp /old/peertube/directory/config/production.yaml /var/www/peertube/config
sudo chown peertube:peertube /var/www/peertube/config/production.yaml
```

Check your have all the configuration keys: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example

Update storage part (prepend with `/var/www/peertube/storage`:
```
sudo -u peertube vim /var/www/peertube/config/production.yaml
```

Example:

```
storage:
  avatars: '/var/www/peertube/storage/avatars/'
  videos: '/var/www/peertube/storage/videos/'
  logs: '/var/www/peertube/storage/logs/'
  previews: '/var/www/peertube/storage/previews/'
  thumbnails: '/var/www/peertube/storage/thumbnails/'
  torrents: '/var/www/peertube/storage/torrents/'
  cache: '/var/www/peertube/storage/cache/'
```

Move old storage to the new storage. We use the move instead of the copy because the `videos/` directory could be big. But you can use `cp` if your prefer:

```
sudo mv /var/www/PeerTube/avatars /var/www/PeerTube/videos /var/www/PeerTube/logs /var/www/PeerTube/previews /var/www/PeerTube/thumbnails /var/www/PeerTube/torrents /var/www/PeerTube/cache  /var/www/peertube/storage
sudo chown -R peertube:peertube /var/www/peertube/storage 
```

Edit the nginx configuration (`alias` directive inside `/static/webseed` location to `/var/www/peertube/storage/videos`):

```
sudo vim /etc/nginx/sites-enabled/peertube
```

Edit peertube service (`User` and `Group` to `peertube`, add `Environment=NODE_CONFIG_DIR=/var/www/peertube/config` and change `WorkingDirectory` to `/var/www/peertube/peertube-latest`):

```
sudo vim /etc/systemd/system/peertube.service
```

It should results in something like:

```
[Unit]
Description=PeerTube daemon

[Service]
Type=simple
Environment=NODE_ENV=production
Environment=NODE_CONFIG_DIR=/var/www/peertube/config
User=peertube
Group=peertube
ExecStart=/usr/bin/npm start
WorkingDirectory=/var/www/peertube/peertube-latest
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=peertube
Restart=always

[Install]
WantedBy=multi-user.target
```

Reload systemd configuration, reload nginx, restart peertube and check the logs:

``` 
sudo systemctl daemon-reload
sudo systemctl reload nginx
sudo systemctl restart peertube
sudo journalctl -fu peertube
```

**Comment by ReK2Fernandez** [comment]
doing this migration now.. crap I almost missed it almost did the git pull like I was doing until now.

**Comment by j1mc** [comment]
Hi all - Thanks for your work on this. I was curious about the choice to install so much to a peertube home directory. I'm not used to installing to a home dir in this way (preferring /srv or /var . . . were other directories considered instead of /home?

**Comment by Chocobozzz** [comment]
@j1mc Put peertube home in `/var/www/peertube`, should be better than `/home/peertube`. I'll the guide :)
