### ISSUE TITLE
[Discussion] WebRTC-free Version?

### ISSUE THREAD

**Issue by ggg27** [Chocobozzz/PeerTube#2030]
**Discussion**: Aye, would it be possible to launch a proxy or something for users blocking WebRTC (like TOR)? Maybe allow them to route through some centralized BitTorrent proxy server?

_______________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/78753365-discussion-webrtc-free-version)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/BountySource).

**Comment by Chocobozzz** [comment]
Why? The "centralized BitTorrent server" is the PeerTube server

**Comment by ggg27** [comment]
> Why? The "centralized BitTorrent server" is the PeerTube server

My understanding is that PeerTube leaks the end-users IP.
This is potentially a violation of privacy.

**Comment by Chocobozzz** [comment]
If you disable P2P or WebRTC your IP won't be sent to other peers.
