### ISSUE TITLE
Installing local plugin (theme) fails

### ISSUE THREAD

**Issue by robinkooli** [Chocobozzz/PeerTube#2031]
**What happened?**

Made small css edit and trying to iinstall it as a plugin locally, but npm just spews error messages. I tried peertube cli also, but it reports errors too.

PeerTube is a new installation from the pre-release on a new VPS.

**What do you expect to happen instead?**

Have the plugin be installed successfully.

**Steps to reproduce:**

1. Make a local plugin.

2. Try to install it with commands given in official documentation.

3. Errors

**Additional information**
* PeerTube version or URL: v1.4.0-rc.1
* Distro: Debian 10 Buster
* Browser name/version: Terminal
* NodeJS version: 10.16.2 LTS

* Link to browser console log if useful:

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
https://gist.github.com/robinkooli/ce82fe06eed54f60fc024d7352fb9e1a (no npm script added to package.json)
https://gist.github.com/robinkooli/cfbb5384be360732fca8c4ff2bb64d7a (with npm script manually added to package.json)

**Comment by Chocobozzz** [comment]
Please paste the command you ran

**Comment by robinkooli** [comment]
Command is ran from /var/www/peertube/peertube-latest/

`sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run npm run plugin:install -- --plugin-path /var/www/peertube/randomstuff/plugins/peertube-theme-test`

**Comment by Chocobozzz** [comment]
There is typo (you duplicated `npm run`). It should be: 

```
NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production sudo -u peertube npm run plugin:install -- --plugin-path /var/www/peertube/randomstuff/plugins/peertube-theme-test
```

**Comment by robinkooli** [comment]
Fixed the typo and now it emits following:

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'plugin:install',
1 verbose cli   '--',
1 verbose cli   '--plugin-path',
1 verbose cli   '/var/www/peertube/randomstuff/plugins/peertube-theme-test' ]
2 info using npm@6.9.0
3 info using node@v10.16.2
4 verbose run-script [ 'preplugin:install', 'plugin:install', 'postplugin:install' ]
5 info lifecycle peertube@1.4.0-rc.1~preplugin:install: peertube@1.4.0-rc.1
6 info lifecycle peertube@1.4.0-rc.1~plugin:install: peertube@1.4.0-rc.1
7 verbose lifecycle peertube@1.4.0-rc.1~plugin:install: unsafe-perm in lifecycle true
8 verbose lifecycle peertube@1.4.0-rc.1~plugin:install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/peertube/versions/peertube-v1.4.0-rc.1/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle peertube@1.4.0-rc.1~plugin:install: CWD: /var/www/peertube/versions/peertube-v1.4.0-rc.1
10 silly lifecycle peertube@1.4.0-rc.1~plugin:install: Args: [ '-c',
10 silly lifecycle   'node ./dist/scripts/plugin/install.js "--plugin-path" "/var/www/peertube/randomstuff/plugins/peertube-theme-test"' ]
11 silly lifecycle peertube@1.4.0-rc.1~plugin:install: Returned: code: 255  signal: null
12 info lifecycle peertube@1.4.0-rc.1~plugin:install: Failed to exec plugin:install script
13 verbose stack Error: peertube@1.4.0-rc.1 plugin:install: `node ./dist/scripts/plugin/install.js "--plugin-path" "/var/www/peertube/randomstuff/plugins/peertube-theme-test"`
13 verbose stack Exit status 255
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid peertube@1.4.0-rc.1
15 verbose cwd /var/www/peertube/versions/peertube-v1.4.0-rc.1
16 verbose Linux 4.19.0-5-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "plugin:install" "--" "--plugin-path" "/var/www/peertube/randomstuff/plugins/peertube-theme-test"
18 verbose node v10.16.2
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 255
22 error peertube@1.4.0-rc.1 plugin:install: `node ./dist/scripts/plugin/install.js "--plugin-path" "/var/www/peertube/randomstuff/plugins/peertube-theme-test"`
22 error Exit status 255
23 error Failed at the peertube@1.4.0-rc.1 plugin:install script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 255, true ]
`

**Comment by robinkooli** [comment]
Content of plugin's package.json:

```
{
  "name": "peertube-theme-test",
  "version": "0.0.1",
  "description": "Test theme for PeerTube",
  "engine": {
    "peertube": ">=1.3.0"
  },
  "keywords": [
    "peertube",
    "test",
    "theme"
  ],
  "homepage": "",
  "author": "Robin",
  "bugs": "",
  "staticDirs": {},
  "css": [
    "assets/style.css"
  ],
  "clientScripts": [],
  "translations": {}
}

```

**Comment by Chocobozzz** [comment]
Should be fixed with https://github.com/Chocobozzz/PeerTube/commit/d1c0a964a214e861f1106e69c62b1aec1b3d55a9
