### ISSUE TITLE
Share one video out of a playlist

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2036]
**What happened?**

I'm watching a playlist. I'd like to share the current video i'm watching, but the share modal only propose to share the playlist:
![image](https://user-images.githubusercontent.com/38844060/63153239-1e2f4400-c00e-11e9-9824-d821a9d82b32.png)

**What do you expect to happen instead?**

It would be nice to have the 2 urls : the one with the playlist, and the direct link to the current video.

**Additional information**
* PeerTube version or URL: 1.4.0-rc1

**Comment by Chocobozzz** [comment]
Fixed/Improved in https://github.com/Chocobozzz/PeerTube/commit/3a1fed11c52705002cbf2a17294509fb5a89237c
