### ISSUE TITLE
Reports from Mastodon users are never seen by PeerTube mods

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#2037]
**What happened?**

I sent some reports from Mastodon ([v2.9.2radical](https://github.com/cambrian-era/mastodon/releases/tag/v2.9.2radical)) to PeerTube (v1.3.1, and then again with v1.4.0-rc.1).

These reports were received on Mastodon, but on PeerTube it was as if no report had been sent.

I reported one video and comment for v1.3.1 and a different video and comment for 1.4.0-rc.1.

**What do you expect to happen instead?**

When I reported the videos I expected to receive abuse reports, just like if another PeerTube instance user had reported a video on my instance.

When I reported the comments I hoped to receive abuse reports, but I didn't expect to receive them because PeerTube doesn't support reporting comments natively (yet).

**Steps to reproduce:**
1. Either on your own Mastodon instance or with the help of a Mastodon instance admin/mod:
    Report a video with a Mastodon account and make sure to toggle "Send to [host instance]" so that it is forwarded.
2. Check the moderator panel on PeerTube. There will not be any reports.
3. You can repeat this with comments as well following the same steps.

**Additional information**
* PeerTube version or URL: v1.3.1 AND v1.4.0-rc.1
* Browser name/version: Firefox for Android

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/0b5c385b4529f3bef8f9523de3f9470ffa58f5f5
