### ISSUE TITLE
Add mimetype requirement for caption uploads to docs

### ISSUE THREAD

**Issue by LoveIsGrief** [Chocobozzz/PeerTube#2038]
**What happened?**

Uploaded a .srt using the api using `text/plain` as the mimetype. Got an error `This caption file is not supported or too large. Please, make sure it is of the following type : .vtt, .srt`

**What do you expect to happen instead?**

The caption upload to succeed or for the docs to state the specific mimetype to use, since the [list does exist](https://github.com/Chocobozzz/PeerTube/blob/2b65c4e53511ccb85b17479cb1c62717afb8511c/server/initializers/constants.ts#L406). It does work with the correct mimetype.

**Steps to reproduce:**

1. Upload a video (normally or with the API)

2. PUT a caption-file (with the API) and use "text/plain" as the mimetype

**Additional information**
* PeerTube version or URL: https://video.ploud.fr

**Comment by frankstrater** [comment]
I did adress this in a pull request to improve the OpenAPI document. See: https://github.com/Chocobozzz/PeerTube/pull/2053

Personally I think the OpenAPI document should describe the API 'as is', including restrictions. I'll leave it to the main developers to decide if they will allow `text/plain` for caption files.
