### ISSUE TITLE
Accounts' video listings overflow

### ISSUE THREAD

**Issue by AutomCoding** [Chocobozzz/PeerTube#2039]
**What happened?**
The video listings for accounts with multiple channels overflow under the following channels.

Full screen width:
![pt_blender](https://user-images.githubusercontent.com/40275136/63185767-2792cd80-c05b-11e9-9a58-aef866bab879.png)

Slichtly narrower viewport:
![pt_blender2](https://user-images.githubusercontent.com/40275136/63185766-2792cd80-c05b-11e9-864f-8ef88eed641a.png)

**What do you expect to happen instead?**
All channels neatly stacked one after the other.

**Steps to reproduce:**
I don't know, as I cannot make it look properly on the screens I have at home.

**Additional information**
* PeerTube version or URL: v1.4.0-rc.1
* Browser name/version: Firefox: latest stable, beta and nightly

**Comment by realityfabric** [comment]
I have the same problem on mobile when my screen is horizontal, but not when my screen is vertical.

Firefox for Android

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/6eb62c33908025d877a28f1cfbc527c511ae3103
