### ISSUE TITLE
unexpect warning on Peertube 1.4.0-rc.1 

### ISSUE THREAD

**Issue by tundahain** [Chocobozzz/PeerTube#2040]
**What happened?**
I want take a view on *peertube.social*, so i got a strange warning.  "We are sorry but it seems that PeerTube is not compatible with your web browser. Please try with the latest version of Mozilla Firefox."

If you think this is a mistake, do not hesitate to report it.
older Peertube-Versions works fine. Chronium works fine also Peertube 1.4.0-rc.1.
**What do you expect to happen instead?**

**Steps to reproduce:**

1. open firefox

2. open address whit a instance who use *Peertube 1.4.0-rc.1*, every instance with this version have the same phenomena. 

3.

**Additional information**
* PeerTube version or URL: **Peertube 1.4.0-rc.1**
* Browser name/version: 60.8.0esr (64-Bit)
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Nutomic** [comment]
I'm getting a lot of reports about this issue, so I really hope this will be fixed in the next rc version.

**Comment by Sciss** [comment]
Same here. JS console just has this line (source code is minimised, so not readable):

> SyntaxError: expected expression, got keyword 'import'[Learn More]

**Comment by JohnXLivingston** [comment]
I did not reproduce, but I have one user who had that bug.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/0c503f5c87ec0fbd764ece910a5b11809303cb79
