### ISSUE TITLE
Missing field in /api/v1/videos

### ISSUE THREAD

**Issue by gbip** [Chocobozzz/PeerTube#2041]
When querying the API for the list of video, the returned Json is missing the field `waitTranscoding`, the field `state`,and the field `blacklisted`.

You can reproduce this bug by executing : `curl https://peertube2.cpy.re/api/v1/videos | jq .` and inspecting the data manually.

[The relevant API section](https://docs.joinpeertube.org/api-rest-reference.html#tag/Video/paths/~1videos/get)

**Comment by Chocobozzz** [comment]
It's fixed now
