### ISSUE TITLE
Suddenly can't open peertube with Debian 10, Firefox 60.8.0esr (64-bit)

### ISSUE THREAD

**Issue by hhassey** [Chocobozzz/PeerTube#2042]
**What happened?**
while trying to open peertube I get this message:

We are sorry but it seems that PeerTube is not compatible with your web browser.

**What do you expect to happen instead?**
open the videos page 

**Steps to reproduce:**
Open peertube.social with Debian 10 and Firefox 60.8.0esr (64-bit)

**Additional information**
* PeerTube version or URL:
* Browser name/version:
Firefox 60.8.0esr (64-bit)
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by hhassey** [comment]
It seems like it is a peertube.social issue only

**Comment by Chocobozzz** [comment]
Try to disable your extensions.

And without console logs I can't really help
