### ISSUE TITLE
Can't Create User Accounts as Moderator

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#2046]
**What happened?**

I attempted to make a user account, but received an error saying `You can only create users (and not administrators or moderators` [sic].

As you can see in the screenshot, the user type I'm trying to assign *is* User, not moderator or admin, and there aren't any other options in the drop down menu.

![image](https://user-images.githubusercontent.com/8910652/63214159-8abb4900-c0c9-11e9-814a-f5a9eeb37639.png)

**What do you expect to happen instead?**

Assuming that the error message is correct, I expect to be able to create User accounts.

If my administrator is mistaken and I do not actually have Account Creation powers then I expect the error message to indicate that, instead.

The error message also is missing a parenthesis.

**Steps to reproduce:**

1. Be a moderator.
2. Attempt to create a user account.

**Additional information**
* PeerTube version or URL: v1.4.0-rc.1
* Browser name/version: Chrome 76.0 64-bit

* Link to browser console log if useful:

```
POST https://[DOMAIN]/api/v1/users/ 403
```
```
Backend returned code 403, errorMessage is: You can only create users (and not administrators or moderators
```

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/dea16773dfcc4e38e48c2980731af6e2a17a7aa6
