### ISSUE TITLE
Can't remove videos from playlists

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#2048]
**What happened?**

Tried to remove a video from a playlist The checkmark disappeared, but no success message was displayed. On refresh the video is still in the playlist. 

Unchecking the box for the playlist and then rechecking it brings up an error message saying the video is already in the playlist.

I tested this with a few playlists, with the same results. I've had no issues adding videos to playlists, and removing videos from playlists was not an issue in v1.3.1.

**What do you expect to happen instead?**

I expect the video to be successfully removed from the playlist when I uncheck the box for that playlist.

**Steps to reproduce:**
1. If you don't have any playlist created, create one.
2. Add a few videos to the playlist.
3. Uncheck the box to remove it from the playlist. The checkmark should disappear, but nothing else should happen.
4. Click to check the checkbox again. It should bring up an error message.

I tried this from inside the playlist and from the video page itself (both worked in v1.3.1).

**Additional information**
* PeerTube version or URL: v1.4.0-rc.1
* Browser name/version: Firefox for Android

**Comment by realityfabric** [comment]
Additionally, once you uncheck and then recheck the box for it to be in the playlist, you can no longer uncheck the box and just receive the error message.

**Comment by realityfabric** [comment]
When I'm on the desktop site and open the playlist (without opening any of the videos) I can use the triple dot drop-down menu to delete the video from the playlist. Doing this results in the video being removed and the success message popping up.

The other way of doing it is still unsuccessful, same results on desktop as mobile.

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/a3671f0709f3f423819fcfed47a4d4879cf82780
