### ISSUE TITLE
HLS file serving should be subject to rate limits and static optimizations

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#2049]
**What happened?**

With HLS, the fragmented mp4 files and playlist are not subject to the rate limits and the proxy bypass that nginx usually provides for video files.

**What do you expect to happen instead?**

I expect the HLS fragmented video files to be served on the fast path just like the original flavor.

I've been using the equivalent of this patch on my instance but I'm not sure if it's your preferred solution:

https://github.com/scanlime/PeerTube/commit/d7c5ecff10a3f7ef7bd98f54ef9043052ae7d734

**Comment by JohnXLivingston** [comment]
We discussed it here: https://github.com/Chocobozzz/PeerTube/issues/2001

**Comment by scanlime** [comment]
Thanks for linking the earlier discussion. I'm not sure I understand the rationale for spending the CPU unnecessarily to route video through the web app. I definitely want a bandwidth limit too, even if it's quite high like my current setting of 100 Mbit per connection.

**Comment by Chocobozzz** [comment]
Added in https://github.com/Chocobozzz/PeerTube/commit/f37db8966d60403c7483d4597007830ee3d05ca9 & https://github.com/Chocobozzz/PeerTube/commit/63247475a1e300e378f604f70580070a120d9b96
