### ISSUE TITLE
Publish OpenAPI clients

### ISSUE THREAD

**Issue by LoveIsGrief** [Chocobozzz/PeerTube#2052]
Since the API documentation is generated by OpenAPI and the tool is able to generate clients, it'd be nice to have those published to the corresponding indices. If that's not possible, it'd be great for them to be at least generated and available for download from the [documentation website](https://docs.joinpeertube.org/api-rest-reference.html).

**Comment by rigelk** [comment]
Indeed, that would be nice, but it's a tool more to maintain - that you can generate by yourself in the meantime.

A way to contribute could be to find a way to [generate/publish SDKs on release](https://openapi-generator.tech/docs/integrations.html). Then we could think about generating official packages.

**Comment by rigelk** [comment]
Clients are now available at https://framagit.org/framasoft/peertube/clients, and are generated during releases thanks to the work of @LoveIsGrief. Each language has its own repository, and there is also a note in the documentation about them.

If anyone has use cases to support more languages, please open an issue requesting their generation.
