### ISSUE TITLE
Peertube does not work with PaleMoon.

### ISSUE THREAD

**Issue by OneWingedShark** [Chocobozzz/PeerTube#2054]
**What happened?**
Got an error message saying the site was incompatible with the browser.

**Steps to reproduce:**

1. Download/install Pale Moon browser.

2. Open a link to the website; eg: https://peertube.social/videos/watch/b83e8c78-f3d6-4833-80fc-b73ec8ddbacf

3. Observe the error message

**Additional information**
* PeerTube version or URL: https://peertube.social/videos/watch/b83e8c78-f3d6-4833-80fc-b73ec8ddbacf
* Browser name/version: Pale Moon [28.1.0]
* NodeJS version: Unknown

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by rigelk** [comment]
Hi @OneWingedShark ! Please look out for related issues before creating one, as #257 already covers this.

**Comment by Nutomic** [comment]
I think that this one is actually a duplicate of #2040 (assuming that Pale Moon is based on Firefox ESR).
