### ISSUE TITLE
Seeing double video players

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#2055]
**What happened?**

I was trying to watch a video and it was loading slowly. I'm not sure what I did to trigger this but at some point I ended up with a second video player, neither of which was working.

**What do you expect to happen instead?**

Video playback, once

**Steps to reproduce**

Not sure yet. Screenshot attached.

![Screenshot_20190819-083003](https://user-images.githubusercontent.com/923812/63278657-8bd0af80-c25c-11e9-8890-49da13ea1d10.png)

**Additional information**
* PeerTube version or URL: 1.3.1
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by JohnXLivingston** [comment]
I had the same issue several times with firefox mobile. When I slide the video progress bar, sometimes it triggers the double video player.
Peertube version: 1.4.0-rc1.

**Comment by frankstrater** [comment]
I experienced something similar with continuing watching a video from my history (when it jumps to a certain start time). Not sure if its related, but I was trying out the HLS=true configuration. @scanlime Are you using HLS in 1.3.3?

**Comment by Chocobozzz** [comment]
I think this should be fixed in 1.4
