### ISSUE TITLE
New plugin hook request on registrations

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2056]
For many peertube administrators, spam is a pain in the a**.
It would be nice to have some plugin hooks on the registration form.
So we can, for example:
- Block registration for some countries (possibility to replace the form by a custom page, or block the submit based on the client IP)
- Add a captcha field
- Add a field in the registration form, with a question that we can configure (https://github.com/Chocobozzz/PeerTube/issues/1078)
- ...

**Comment by Chocobozzz** [comment]
We added a hook to block registration with a plugin in https://github.com/Chocobozzz/PeerTube/commit/4ce7eb71ba28a563336c07d10c182ff89461c72b

For the captcha and the additional fields, there are already existing issues.
