### ISSUE TITLE
Backing out of NSFW videos doesn't close the confirmation dialog

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#2057]
**What happened?**

On the Trending page:

Clicked on a NSFW video. I did not click "confirm" or "cancel", but instead clicked the Back button to navigate away. The confirmation dialog box was still visible.

Clicking "cancel" after going back causes the page to be completely reloaded. Clicking "confirm" changes the page title to the video title as if you were on the video page, but does not reload the page (allowing you to continue scrolling from where you left off).

**What do you expect to happen instead?**

Clicking the "back" button should behave like if you backed out of any other video: the dialog should disappear automatically and you shouldn't lose your place in the feed.

**Steps to reproduce:**
1. Make sure NSFW videos are not hidden from the feed. I have them set to Blur.
2. Scroll down the Trending timeline until you find a NSFW video.
3. Click on the video. It should prompt you to either confirm or cancel.
4. Click "Back" without clicking confirm or cancel. The dialog will still be there.
5. Click "Cancel". It will place you at the top of the Trending page and strip the URL.
6. Repeat, but skip step 5 and instead click "Confirm". It will keep your place but change the page title.

**Additional information**

* PeerTube version or URL: v1.4.0-rc.1
* Browser name/version: Chrome 76.0 64-bit
* Link to browser console log if useful:

When clicking "cancel":

`Redirecting to /videos/trending...`

When clicking "confirm":

`VIDEOJS: WARN: The element supplied is not included in the DOM`

**Comment by Chocobozzz** [comment]
Thanks, the modal should close itself with https://github.com/Chocobozzz/PeerTube/commit/4334445d043252661e62cf97f76b67a2c43e3750 and cancel should redirect to your last page with https://github.com/Chocobozzz/PeerTube/commit/60c2bc80b82c71bd63bdb1fcf64d4d49491ce5c8
