### ISSUE TITLE
1080p videos aren't converted to 720p

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#2058]
**What happened?**

I've uploaded a number of mp4 videos in 1080p60 and 1080p, and they haven't been converted to 720p60 or 720p. Other qualities don't seem to have any issues.

720p is enabled. Not everyone on my instance has this problem, there are recent 1080p videos posted by others which have 720p versions available.

**What do you expect to happen instead?**

I expect my 1080p videos to have a 720p version available.

**Steps to reproduce:**
1. Be on an instance with 720p conversion enabled. (My instance has 240p, 360p, 480p, 720p, and 1080p enabled).
2. Upload an mp4 in 1080p or 1080p60.
3. Wait for the video to be transcoded.
4. View the video, and check to see which resolutions are available. In my case, 240p, 360p, 480p, and 1080p are available (or 1080p60 if that's what I uploaded) but not 720p or 720p60.

**Additional information**
* PeerTube version or URL: v1.4.0-rc.1 and v1.3.1 (https://peertube.social)
* Browser name/version: Firefox for Android

(EDIT: I forgot to mention that this was a problem as far back as v1.3.1)

**Comment by Chocobozzz** [comment]
Please paste the URL of your instance, check the transcoding job and potential errors in your server logs

**Comment by Nutomic** [comment]
This is one of the affected videos, I already grepped the logs for that video id and didnt find any errors.

https://peertube.social/videos/watch/5820d913-54df-4e5c-8b3f-845f30bae4e8

**Comment by realityfabric** [comment]
I just uploaded another test video (about 5 seconds long) in 1080p60, and it does have a 720 version, but it's listed as 720p59 (and 1080p59). Weird bug. No errors in the log for that video, either.

![image](https://user-images.githubusercontent.com/8910652/63447728-5c9f7700-c3f1-11e9-8dbc-03406c23819d.png)


I'm looking through all of my videos and 50% of my videos which were uploaded as 1080p[60] were not converted to 720p[60].

None of the videos I recorded on my desktop have issues, but more than 70% of the videos I recorded on my phone don't convert to 720p[60].

**Comment by Nutomic** [comment]
By the way, are the transcoding logs from ffmpeg stored anywhere? That would be useful to debut cases like this, but so far I never saw it anywhere.

**Comment by Chocobozzz** [comment]
Error logs from ffmpeg should be displayed in the job admin panel.

**Comment by Nutomic** [comment]
So I have to look at failed jobs for that? Would be nice if it could be filtered by job type, because right now its hard to find anything but activitypub jobs.

**Comment by Chocobozzz** [comment]
Do you still have the issue?
