### ISSUE TITLE
White background in plugins and themes in dark mode

### ISSUE THREAD

**Issue by Elrondo46** [Chocobozzz/PeerTube#2059]
**What happened?**

White background in plugins and themes in dark mode

**What do you expect to happen instead?**

Colours will be fixed

**Steps to reproduce:**

1. Just put your instance in Dark Mode and go to Plugins/Themes section

**Additional information**
* PeerTube version or URL: Peertube 1.4.0-rc1
* Browser name/version: Firefox (68.0.1)
* NodeJS version: 10

Screenshot on imgur
[https://i.imgur.com/CDZv7rq.png](url)

**Comment by Chocobozzz** [comment]
Thanks, it's fixed by https://github.com/Chocobozzz/PeerTube/commit/f9e387ed05d79d3f88f95056720fb244d04805d2
