### ISSUE TITLE
Add docker production image

### ISSUE THREAD

**Issue by Dragnucs** [Chocobozzz/PeerTube#206]
Thank you for your effort.

In production guide, please document how to deploy PeerTube using Docker and Probably Docker Compose too. This would be extremely helpful. There is already a working Dockerfile hidden in code files and shedding light on it would be beneficial to most of us.

**Comment by bnjbvr** [comment]
Thanks for opening this issue: I think having a production ready Dockerfile / docker-compose would be useful too. (I might even work on it, who knows)

Just to let you know: the Dockerfile in support/docker/dev/ is just there for development purposes and shouldn't be used in production at all.

**Comment by rigelk** [comment]
As far as I know [Dryusdan](https://miaou.drycat.fr/@Dryusdan) has a nice [docker image](https://git.drycat.fr/Dryusdan/docker-peertube/src/branch/master/Dockerfile) to run PeerTube and it is updated regularly. Might be changed to update automatically upon releases though.

**Comment by bnjbvr** [comment]
Nice image! I think the postgresql database/user still need to be created, but that looks promising 👍

**Comment by Dryusdan** [comment]
The postgresql is on a other container, and we need create the roles peertube and the database peertube_prod on postgresql

I'll document when I have time.

**Comment by Chocobozzz** [comment]
Like @bnjbvr said, the actual docker image we have is only for development.

Feel free to add a production docker image with docker-compose. I renamed the issue.

**Comment by Dryusdan** [comment]
Hey
But hum... I think is better to make a Docker image on other repository... I dislike have a "docker" folder in code ^^
What do you think ? :)

**Comment by Chocobozzz** [comment]
I disagree, I prefer to have it in the same repository so I could easily run unit tests when the code change (dependency for example...).

**Comment by Dragnucs** [comment]
I agree with @Chocobozzz, since you can run locally on the same working directory.

**Comment by rigelk** [comment]
Implemented since e8395f027b6c3e3f757c740e35b20e76c51b03bd.
