### ISSUE TITLE
Dont notify when an instance mod creates a report

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#2061]
If a mod finds problematic content on another instance, they need to create a report to let the mods on that instance know about it. However, there is no need for other mods on the first instance to be aware of these reports. Essentially, this just creates a lot of spam for all mods.

This could be solved by putting a checkbox with "dont notify local mods" into the report dialog. This checkbox should only be visible to mods. Whether it should be checked or unchecked by default, I dont know.

This is the frequency with which I get report emails from a very active mod:

![Screenshot_20190820_205343](https://user-images.githubusercontent.com/1044450/63376119-94200c00-c37c-11e9-9aa9-b71c2f26c769.png)

**Comment by realityfabric** [comment]
Maybe have a setting to allow daily digests? I think it's still important to see what other mods may be doing, and that would vastly reduce the number of emails while still allowing you to keep an eye on things.

I do think it should be possible to turn off email from mod activity entirely, as well.

**Comment by Nutomic** [comment]
Daily digest also sounds like a good idea. But for user reports, it would be good if mods get them as soon as possible.

**Comment by Chocobozzz** [comment]
Is there a reason why your moderator does not directly blacklist the videos?

**Comment by Nutomic** [comment]
One reason is that the remote instance does not get a report when a video is blacklisted (afaik). Also, it is not possible to enter a reason for blacklisting accounts or instances (#2029).

**Comment by realityfabric** [comment]
An alternative solution would be to allow mods to forward a report to the original instance when blacklisting a video (or when marking a remote video as NSFW locally, #680), which could bypass local reports entirely and simplify the task of moderation.

**Comment by Chocobozzz** [comment]
Finally fixed by https://github.com/Chocobozzz/PeerTube/commit/9e847c17f968076287025c798b87506a8d50bb93
