### ISSUE TITLE
Ability for a plugin to add custom routes and backend code

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2062]
It would be very nice if in a plugin we can add some specific routes associated to custom backend code.

I'll give an example.

Yesterday, I quickly developped a "simple-logo" plugin: https://framagit.org/Livingston/peertube-plugin-simplelogo

The idea of this plugin is to permit to use custom files for the logo or the favicon.
I was inspired by the framasoft logo plugin.

But there is a problem... Before inserting the logo/favicon url in the dom, I have to wait for a peertubeHelpers.getSettings() (which will give me the logo url that is configured in the plugin settings). So, the original peertube logo first load and display itself, then my plugin can override. Doing so, it makes unecessary requests.

A better way of doing this would be to have an unvariant url in the plugin's css (something like: /plugin/simplelogo/logo.png). Thus my plugin could declare the route "logo.png" (in a specific plugin namespace), and I could had some backend code to check if there is a custom file, and do a http redirect to the custom file, or to the peertube default file. (or instead the redirect, serving directly the custom file or the original file).

**Comment by JohnXLivingston** [comment]
Just for the record, the final goal of my plugin should be to:
- upload a file in the plugin's settings page
- automatically resize the file, and generate a file for the favicon and a file for the logo
- serve these files

But the peertube plugin system seems not complete enough for now to do so.

**Comment by JohnXLivingston** [comment]
An other possibility would be to have a server Hook for when the plugin's settings are saved. So, I could for example download the file, and store it in the plugin static directory. Then I can overwrite the plugin css file.

**Comment by JohnXLivingston** [comment]
Perhaps the registerSetting method can take a callback function, that would be called when the user submit the form?

**Comment by Chocobozzz** [comment]
Plugins can now add custom routes with https://github.com/Chocobozzz/PeerTube/commit/5e2b2e2775421cd98286d6e2f75cf38aae7a212c
