### ISSUE TITLE
Remove request to google fonts

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#2063]
Hello,

It would be a good idea remove the request to google fonts, or at least explain how can i do it myself (i searched and didn't found). It is not mandatory (i know it, i block it with a browser add-on without any problem) and not privacy friendly.

**Comment by Findus23** [comment]
Hi,

I don't think Peertube is doing any requests to Google Fonts. Can you show where you are seeing it?

**Comment by Nutomic** [comment]
@stemy2 Which instance are you using?

**Comment by stemy2** [comment]
This is really strange. I don't see the request in the developer's tools, but my umatrix add-on says that it blocked a request to google fonts.

**Comment by JohnXLivingston** [comment]
Which browser ?

**Comment by stemy2** [comment]
abrowser

**Comment by Chocobozzz** [comment]
We don't use google fonts.
