### ISSUE TITLE
How to update a plugin?

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2064]
How can I update a plugin in production environment?
Have I to uninstall it, and then reinstall?

* PeerTube version or URL: v1.4.1-rc1

**Comment by Chocobozzz** [comment]
If a new plugin version is available, there will be a button to update in the administration.

You can also use the CLI: https://docs.joinpeertube.org/#/maintain-tools

**Comment by JohnXLivingston** [comment]
Ok. Yesterday I updated my peertube-plugin-simplelogo from 0.0.2 to 0.0.3.
In the installed plugin list, I had no update button (with v0.0.2), but is the plugin search view it showed v0.0.3.
Today the update button is here.

**Comment by Chocobozzz** [comment]
PeerTube checks the available new versions periodically https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L164
