### ISSUE TITLE
Blacklisted video titles display for a short time

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#2068]
**What happened?**

I was testing the behavior of blacklisted videos when visiting their URL and noticed that the tab title displays the title of the video for a split second when the page is loading, before changing it to "Not Found".

**What do you expect to happen instead?**

I expect the title to never display and the user to have no indication that the video exists.

**Steps to reproduce:**
1. Get the URL of a blacklisted video.
2. Open a private browser tab. I used Chrome Incognito.
3. Navigate to the URL of the blacklisted video. The tab title will display the video title for a split second.

**Additional information**

* PeerTube version or URL: v1.4.0-rc.1
* Browser name/version: Chrome 76.0 (Incognito)
* Link to browser console log if useful:

```
ERROR {message: "Unauthorized", status: 401, body: "Unauthorized"}
```

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): *No useful logs*

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/d636ab58d042494ef9d17b2d9c4c841bae01c897 (won't be in 1.4)
