### ISSUE TITLE
What does Accepting or Rejecting a report do?

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#2069]
I cannot find documentation on the function of this feature. You can accept or reject reports, which puts a checkmark or an x next to the report, but does it have any other explicit purpose?

**Comment by Chocobozzz** [comment]
No it does not have side effects, it's just an indicator for other moderators to know that you rejected or accepted the report.

**Comment by realityfabric** [comment]
Would it be possible to streamline moderator action by aggregating reports for specific videos (or comments whenever that gets implemented) and asking the mod which actions they'd like to take when accepting?

Example:
1. Mod clicks accept report
2. Pop-up asks if mod would like to blacklist, mute account, and/or mute instance
3. Mod selects options and then submits them
4. All actions are handled, accepted checkbox is checked
5. Maybe send a notification to the people who reported the video/comment letting them know their report was accepted (Twitter does this)

Or, if the mod clicks reject, then the reports would simply be marked as rejected as is the case now.

I'll see about updating the documentation for it's current behavior.

**Comment by realityfabric** [comment]
For the documentation, where should I put this information? I don't think there's a page dedicated to moderator actions like muting and blacklisting.

**Comment by Chocobozzz** [comment]
You could create a section "moderation" in the "Administer PeerTube" section

**Comment by Chocobozzz** [comment]
Documented in https://framagit.org/framasoft/peertube/documentation/commit/df78459e4f903dfea9c6962546d11a49d8079832
