### ISSUE TITLE
eMail configuration

### ISSUE THREAD

**Issue by Lokizzle** [Chocobozzz/PeerTube#2070]
Hi There, 
i wanted to activate notification emails. 
Before i start, i was wondering if there is a "how-to", for setting it up.

Or would this 3 steps be enough?

1.  install postifx (just like explained here: https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-postfix-as-a-send-only-smtp-server-on-ubuntu-14-04)

2. change email account name in "production.yaml"  for example: admin@domainname.com

3. sudo systemctl daemon-reload
    sudo service peertube restart

**Additional information**
* PeerTube version or URL: PeerTube v1.3.1

**Comment by frankstrater** [comment]
You also have to update the 'smtp' part in production.yaml

I have written a small "how-to" with an alternative setup at https://github.com/beeldengeluid/peertube-docs/blob/master/configuration.md

**Comment by Lokizzle** [comment]
> 
> 
> You also have to update the 'smtp' part in production.yaml
> 
> I have written a small "how-to" with an alternative setup at https://github.com/beeldengeluid/peertube-docs/blob/master/configuration.md

Hi Frank, 
thanks a lot, ill try your "how-to" asap!

**Comment by frankstrater** [comment]
My previously small "how-to" is outdated, but will be replaced by some examples as shown here: https://github.com/beeldengeluid/extending-peertube/issues/7
