### ISSUE TITLE
Video playback performance metrics

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#2075]
I've been asking my users about their experience a lot, and while a lot of people seem to have a good time with PeerTube, I still hear that some folks are having playback problems. In order to understand which videos and network and software conditions cause the problem, it would be really useful to have some kind of reporting.

I'm not sure if other folks already have plans in this direction. Since the client already sends "watching" messages frequently, I was thinking it might be useful to add some quality tracking to these existing messages. Perhaps the client could keep a count of playback stalls, and counts of played/buffering/paused time, and send that in the existing messages. The messages already include client info in the user agent, which might be sufficient.

Personally I'd want to get these stats hooked into a real-time metrics platform like InfluxDB so I can identify problems quickly.

**Comment by JohnXLivingston** [comment]
If we do so, I think we should ask permission to users. Because it is very intrusive.
It can be a «report stats» button in user prefs, disabled by default (and if a user has problems, ask him to activate this setting).

Or, just the front-end client which accumulate these data, and propose a «send report» button which sends these logs.

**Comment by scanlime** [comment]
I'm not sure how it's "very intrusive" to report errors? This has no additional privacy implications. The server could already figure out which videos the user is watching, I'm just asking if we could have the client indicate how successful playback has been. The whole point here is that I'm already asking users directly but that gets only a small piece of the picture.

**Comment by scanlime** [comment]
I like the idea of a report button. I just don't want to rely on that as an exclusive way to report failures, if we can also have the "watching" event indicate "hey, i've been getting tons of buffer underruns and btw these peers are slow", you know?

**Comment by JohnXLivingston** [comment]
It can give you some informations on bandwidth quality, what part of the video is viewed, etc.
Of course, your server can log this type of information. But it usually don't (in nginx logs, you have not such information).

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/1855
