### ISSUE TITLE
What is the maximum videos?

### ISSUE THREAD

**Issue by LWFlouisa** [Chocobozzz/PeerTube#2076]
What is the maximum amount of videos one can upload on Peertube? It says I exceeded my quota, but I can't find specifically where to find out which videos are apparently the biggest offenders size wise.

Deleted some extra videos that weren't needed, and the quota is still not going down. This issue needs to be fixed before people will use this platform extensively.

You guys knows as much as anyone else how many videos people upload to youtube.

**Comment by LWFlouisa** [comment]
Seriously though, 2GB is ridiculously easy to accidentally exceed, you only have to post lots of 3 minute videos.

**Comment by Nutomic** [comment]
FYI the upload limit is different on each instance. You could always sign up on a different instance with a higher limit.

https://joinpeertube.org/en/#register
