### ISSUE TITLE
Menu & Scrollbars - Display could be better :)

### ISSUE THREAD

**Issue by Angedestenebres** [Chocobozzz/PeerTube#2077]
**What happened?**
When I'm logged to my account I get two scrollbars (one horizontally and one vertically) in the menu.
My screen display is 1600 x 900.

![Capture d’écran de 2019-08-23 22-26-19](https://user-images.githubusercontent.com/21110485/63623202-4c59e880-c5f9-11e9-8613-cdfc2a0dceec.png)

If I'm not logged, there is no scrollbar at all.
The horizontal one appears due to the fact that the size of the menu got reduced with the vertical scrollbar.

**What do you expect to happen instead?**
Have only one scrollbar.

**Steps to reproduce:**

You can easily reproduce that by just reducing the window, i.e:

![Capture d’écran de 2019-08-23 23-08-57](https://user-images.githubusercontent.com/21110485/63623871-1289e180-c5fb-11e9-938f-55383d77e65c.png)

**Additional information**
* PeerTube version or URL: 1.3.1
* Browser name/version: FF / Chromium latest version

**Comment by frankstrater** [comment]
Just wanted to add that this problem is since the addition of 'Playlists' in the menu.

**Comment by scanlime** [comment]
This looks really broken, fwiw.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/606793b917412de56f67bddd829bffee46868980
