### ISSUE TITLE
Installation on OpenBSD 6.5

### ISSUE THREAD

**Issue by 22decembre** [Chocobozzz/PeerTube#2079]
**What happened?**

I managed to compile (partly - issue about "dist" below) on OpenBSD 6.5. But I still face (at least) two troubles :
- the repository "dist" is not built at installation, despite npm claiming install' was successfull. As a temporary solution, I copied this repo from a running instance.
- when launching the service, it's still peertube_dev that is called as database, so I cannot tell if the config is parsed.

**What do you expect to happen instead?**

- that "dist" is built.
- that config is parsed and connection is done to peertube_prod

**Additional information**
* PeerTube version or URL: v1.4.0-rc.1
* NodeJS version: v10.15.3

* Link to console log if useful:
(Where I try to launch the thing with npm or node)

https://pastebin.com/dpvZEdMh

NB : I think warnings in the first lines about libc++ can be ignored.

**Comment by Chocobozzz** [comment]
> the repository "dist" is not built at installation, despite npm claiming install' was successfull

`npm install` does not compile PeerTube, you need to run `npm run build`: https://docs.joinpeertube.org/#/install-unofficial?id=git

> that config is parsed and connection is done to peertube_prod

Add `NODE_ENV=production` env variable

**Comment by 22decembre** [comment]
Ok so actually, at start, I used (apparently) sources. Now I installed again using 1.4.0.zip and I have the "dist" repo, no trouble.

BUT ! I cannot manage for it to use production DB. When I start it with the prod variable or not, it will still use peertube_dev.

I passed on the user _peertube, and here is what happens when I launch it :

```
blackblock$ HOME=/var/www/peertube NODE_CONFIG_DIR=$HOME/config NODE_ENV=production USER=_peertube node dist/server  
/var/www/PeerTube/versions/peertube-v1.4.0/node_modules/config/lib/config.js:182
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "database.pool.max" is not defined```

**Comment by Chocobozzz** [comment]
Copy `default.yaml` in your config directory

**Comment by 22decembre** [comment]
Okay, I am going on. Things are moving. Nice !

Now, I can almost start it ! Almost.

https://pastebin.com/E7ZQW58R

**Comment by Chocobozzz** [comment]
You need to specify a valid webserver host in your configuration file
