### ISSUE TITLE
Support for volume normalization on playback

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#2080]
This is a feature request for automatic audio volume normalization. During transcoding (initial or optimization) we would compute a gain based on the peak loudness or some other appropriate metric. This metric would be stored along with the video, and used for amplification at playback time.

I understand that this wouldn't be necessary if everyone mastered their videos properly, but since YouTube supports volume normalization it's easy to end up importing vids that may need a gain boost to sound loud enough.

It's possible we could do the normalization at transcoding time, but storing a gain and applying it at playback seems like a more flexible and future-proof solution.

**Comment by maxdrash** [comment]
Youtube does the volume normalization at the client side not server side, right ?

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/3651
