### ISSUE TITLE
Add option to disable webtorrent for uploads from specific users

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#2081]
There are many political organizations that are using Peertube, or are interested in using it. However, it is a problem for them that an adversary could potentially identify many of their members and supporters via the IP addresses that are seeding videos for a channel.

For this reason, I believe it would be a good idea to add an option which disables webtorrent for all videos uploaded by a user. I dont know about other instances, but mine is only using 1 tb of traffic per month out of 20 tb available, so this would be no problem at all.

It might be a good idea to make this option available for mods or admins only, so they can ensure only users that really need it have the option enabled.

**Comment by Chocobozzz** [comment]
Users already have an option to disable P2P when they are watching videos. Admins already have an option to disable P2P on their instance. Is another option to disable P2P on videos of a specific user is really needed?

**Comment by Nutomic** [comment]
I dont think there is any option for users who dont have an account to disable p2p. Or am I missing that? And even if there was, they would probably still connect via p2p for at least a few seconds, until they manually disable it.

**Comment by hambibleibt** [comment]
If there is alreay the option for users to choose if they want p2p or not the issue would be solved thought. But I haven't saw that when watching video on peertube. Do admins have to enable that option? 

Related on that issue, I just wrote the following: 
https://github.com/Chocobozzz/PeerTube/issues/355#issuecomment-524792683

**Comment by JohnXLivingston** [comment]
A user who wants to privatly watch videos should use Tor Browser.

**Comment by Eskuero** [comment]
On Firefox under about:config you could set media.peerconnection.enabled to false

**Comment by Nutomic** [comment]
@Eskuero This issue is about disabling webtorrent on the server side for all videos uploaded by a particular user.

**Comment by Eskuero** [comment]
I'd say its better to let the users decide whether they want that exposure or not

**Comment by realityfabric** [comment]
If uploaders can disable webtorrent, then wouldn't it be up to the uploader to decide if their video needs that precaution? It would be good to allow user defined defaults, but is this something admins need to be deciding?

Not that it's necessarily a bad feature.

**Comment by Eskuero** [comment]
I'm not saying that it's a bad feature. Some kind of granular option to allow disabling p2p on certain videos before it starts even if the user is not registered would be nice but I think it should fall on users hands.

Maybe another privacy setting for videos like "Anyone can see but torrenting must be confirmed", then nag the user about enabling peering for that video and save that preference in a cookie for a year.

I grow real tired of people choosing what's best for me so I'd rather have the chance to make an informed decision than getting protection without knowing what's going on.

**Comment by hambibleibt** [comment]
> A user who wants to privatly watch videos should use Tor Browser.

this is irrelevant to the use of WebRTC, as WebRTC is exposing ones real IP adress while using tor. That is why tor browser has disabled it. If you use tor over another browser, WebRTC will work, but on the risk of revealing your ip. 
afaik

> I grow real tired of people choosing what's best for me so I'd rather have the chance to make an informed decision than getting protection without knowing what's going on.

this is what I want. Once peertube has this, I will start to promote peertube within our movments. Befor I can only consider it a security issue. 

Question: Or has in the meantime something changed?

**Comment by Chocobozzz** [comment]
We now have a dedicated option to disable P2P by anonymous users, thanks to @rigelk 

![screen_2020-04-17-15:20:12](https://user-images.githubusercontent.com/5180488/79573456-f9b8c980-80be-11ea-9011-0bd89bcb72f8.png)
