### ISSUE TITLE
V1.4 - CSS problem in registration page 

### ISSUE THREAD

**Issue by quentinDupont** [Chocobozzz/PeerTube#2086]
**What happened?**
Text is hidden in new registration page in french language (and language with long translations)
![image](https://user-images.githubusercontent.com/9005817/63802782-a4ebf700-c913-11e9-85df-32f4e8e3f8e8.png)

**Additional information**
* PeerTube version or URL: Version 1.4 https://hitchtube.fr/signup
* Browser name/version: Firefox

**Solution ?**
Just with a css rule : max-width: 50px;
I'm not sure it's the more beautiful solution but that's works
![image](https://user-images.githubusercontent.com/9005817/63803001-2ba0d400-c914-11e9-8463-74f4065f7a27.png)

**Comment by quentinDupont** [comment]
Fyi, I didn't succeed to get easily the first .step-label for the moment to apply a css rule in admin panel.

**Comment by Chocobozzz** [comment]
I chose to rename the steps in https://github.com/Chocobozzz/PeerTube/commit/5eb9bde8aa50951c7896d5278d0788dda541c475, I think it's better like that :)

![screen_2019-09-04-15:09:19](https://user-images.githubusercontent.com/5180488/64257723-1afce900-cf26-11e9-9043-4a2310dcd40e.png)

**Comment by quentinDupont** [comment]
Perfect :+1:
