### ISSUE TITLE
videoPlaylistElement.position for playlists may not start at 1

### ISSUE THREAD

**Issue by JigmeDatse** [Chocobozzz/PeerTube#2087]
This is an issue which I haven't really looked at at much depth as I thought there probably was a fix for this.  I'm not really sure what to make of this to be honest, because I kind of understand why it may be there, but it feels like it is probably prone to breaking:

Well, it seems like it is, if I look at:

# select "id", "position", "videoPlaylistId" from "videoPlaylistElement" where "videoPlaylistId"=2 order by "position"; 
   id   | position | videoPlaylistId 
--------+----------+-----------------
 136875 |       75 |               2
 138054 |       76 |               2
 138055 |       77 |               2
 138058 |       78 |               2
 138060 |       79 |               2
 138061 |       80 |               2
 138062 |       81 |               2
 138063 |       82 |               2
 138064 |       83 |               2
 138065 |       84 |               2
 138066 |       85 |               2
 138067 |       86 |               2
 138068 |       87 |               2
 138069 |       88 |               2
 138070 |       89 |               2
 138071 |       90 |               2
 138072 |       91 |               2
 138073 |       92 |               2
 138075 |       93 |               2
 138076 |       94 |               2
 138077 |       95 |               2
 138081 |       96 |               2
 138082 |       97 |               2
 138083 |       98 |               2
 138084 |       99 |               2
 138085 |      100 |               2
 138086 |      101 |               2
 138087 |      102 |               2
 138088 |      103 |               2
 138089 |      104 |               2
 138090 |      105 |               2
 138091 |      106 |               2
 138092 |      107 |               2
 138093 |      108 |               2
 138094 |      109 |               2
 138095 |      110 |               2
 138096 |      111 |               2
 138097 |      112 |               2
 138098 |      113 |               2
 138099 |      114 |               2
 138100 |      115 |               2
 138101 |      116 |               2
 138103 |      117 |               2
 138104 |      118 |               2
 138105 |      119 |               2
 138110 |      120 |               2
(46 rows)

you can see that there are no position values less than 75.  

I'd rather not have to manually fix this, as I'm not entirely sure how the position value is being used, and it does end up causing problems, because if where I am in the playlist is greater than the number of items in the playlist, then the playlist will not advance.  

#1978 is related to this, but I'd thought that might have been addressed.  There is a fix to the problem that this seems to be the cause of, and it certainly has gotten a lot better, but it still is not resetting the playlist to 1, which I'd like to be able to do.  

I *think* that a workaround *might* be to remove all items from a playlist, and then re-add them.  I don't see any reason this wouldn't work.

**Comment by Chocobozzz** [comment]
> #1978 is related to this, but I'd thought that might have been addressed.

This fix does not reset your old "broken" playlists. But it should not happen anymore with your new playlists
