### ISSUE TITLE
Improve API videos GET performance

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#2089]
A while ago, I noticed that someone was running a crawl on my instance, doing about 50 requests per second to the `/api/v1/videos/` API endpoint for different video IDs. This caused 100% CPU usage, and slowed down requests from actual users. 

I reported this issue to Chocobozzz so Peertube has a rate limit built in now. To reproduce the problem now, you have to increase the API rate limits in your config, and run these commands:
```
$ sudo apt install apache2-utils
$ ab -c 20 -t 100 https://your.instance/api/v1/videos/*some-video-id*
```

The problem remains that API calls are way too resource intensive. If a Peertube video was linked from a popular website like Reddit, the traffic might bring the entire instance down. A DDoS is also very easy. 

According to Chocobozzz, the problem is caused by the time it takes [Sequelize](https://github.com/sequelize/sequelize) to build the SQL query.

Some possible solutions:

1. allow caching of API requests via `cache-control` header for users that are not logged in (even just for a few minutes or seconds)
2. optimize the Sequelize code
3. cache query objects in Peertube

**Comment by JohnXLivingston** [comment]
If I understand well, peertube is running only one instance of expressjs to handle requests.
Would it be possible to launch multiple instances ?
https://expressjs.com/en/advanced/best-practice-performance.html#run-your-app-in-a-cluster

**Comment by McFlat** [comment]
Varnish can improve performance but its only yet another layer

**Comment by kontrollanten** [comment]
@JohnXLivingston If it's the SQL queries that's time consuming, then more express instance won't do any effect, or am I missing something?

@Nutomic When you propose that one solution can be to optimize the sequelize code, are you thinking about anything particular?

I'm working with a client that's interested in using PeerTube, but they've 60 000 subscribers and thousands of people watching videos simultaneously so I need to be sure that PeerTube can handle the performance. But if it's only about the GET requests Varnish should help a lot.

**Comment by JohnXLivingston** [comment]
> @JohnXLivingston If it's the SQL queries that's time consuming, then more express instance won't do any effect, or am I missing something?

You said: «According to Chocobozzz, the problem is caused by the time it takes Sequelize to build the SQL query.»
The building of the SQL query is made by node. So having multiple instances can improve performances.

**Comment by Chocobozzz** [comment]
We improved this endpoint since the creation of this issue. If you still notice performance bottlenecks, please create dedicated issues. For example we can replace some sequelize code by raw queries, or create cached endpoints (for embed for example) but I haven't had too much perf feedback yet.
