### ISSUE TITLE
Another logical bug?

### ISSUE THREAD

**Issue by frankstrater** [Chocobozzz/PeerTube#2090]
@Chocobozzz 

Not sure if this is also a bug or not. Haven't tested it. 

https://github.com/Chocobozzz/PeerTube/blob/b1b7f7160b02e64dd53faea96e748dd816895495/server/controllers/api/videos/index.ts#L189

**Comment by Chocobozzz** [comment]
Thanks: https://github.com/Chocobozzz/PeerTube/commit/3155c8606cff211f495bf71c75c56cae85a5430f
