### ISSUE TITLE
Report Sent To Wrong Video in Playlist

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#2093]
**What happened?**

I was watching a video in a playlist which I decided to report. I opened the report form, and while filling it out the video ended and the next video opened. When I sent the report, it reported the new video, not the one I opened the form to report.

When testing this out again, I noticed that if the domain of the videos are different then it will change, but if the domain is the same then there is no indication that the report is going to the wrong video.

**What do you expect to happen instead?**

I expect the report to be sent for the video the report form was opened for. Either pause the video when the form is opened, prevent a new video from loading, or ensure that even when a new video loads (while the form is open) the form is still pointing to the correct video.

**Steps to reproduce:**
1. Create or open a playlist with multiple videos from different instances.
2. Play a video that isn't the last video.
3. Open the report form, but do not submit it.
4. Wait until the next video loads. The form will change if the instance is different.
5. If you receive notifications for reports you can submit the report, but that's probably going to annoy people. I think the instance domain changing in the form is proof enough.

**Additional information**

* PeerTube version or URL: v1.4.0
* Browser name/version: Chrome 76.0

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/689a4f6946e47ddf4871fd43bbd1284a4dc79e68
