### ISSUE TITLE
Please add an auto reject function for abuse report

### ISSUE THREAD

**Issue by Elrondo46** [Chocobozzz/PeerTube#2094]
**What happened?**

Some trolls reports a mass of false abuses from address owned by an other instance, the silent account function not masking abuse reports.

**What do you expect to happen instead?**

An auto reject abuses from slient account 

**Additional information**
* PeerTube version or URL: 1.4.0

**Comment by Elrondo46** [comment]
Thanks

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/f0a47bc92aa20b91b46197a4d3fc430aea962848
