### ISSUE TITLE
Most liked Videos

### ISSUE THREAD

**Issue by fwn0** [Chocobozzz/PeerTube#2095]
I am missing a category in the navigationbar for most liked videos.
Trending category is nice feature, but it does list only most viewed videos, not the rank of the best videos rated by users.
Is is possible to implemend this function in the navigationbar ?

**Comment by Chocobozzz** [comment]
Implemented by @alcalyn in https://github.com/Chocobozzz/PeerTube/commit/c07eb946531dd190ae50624832e1147c8ccf3692
