### ISSUE TITLE
Playback issues

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#2098]
**What happened?**
-Buffering happens too often while playing, despite of a decent internet connection.
-Transcoding affects heavily the video quality.
**What do you expect to happen instead?**
-Server using the nighest upload speed available.
-Limited loss of quality when transcoding.
**Steps to reproduce:**

1. Upload a [video without transcoding](https://peertube.stemy.me/videos/watch/658e7979-0531-439f-a446-abdd6ec4049e)

2. Upload a [video with transcoding](https://peertube.stemy.me/videos/watch/ce366a70-6226-4eaf-98ca-17a5f22f883f)

3. Play it

**Additional information**
* PeerTube version or URL: peertube.stemy.me
* Browser name/version: Firefox 68.0.2
* NodeJS version: 4.8.2

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by rigelk** [comment]
Could you post a [mediainfo](https://mediainfo.js.org/) of the original file?

**Comment by stemy2** [comment]
```
General
Complete name: VID_20180312_141713.mp4
Format: MPEG-4
Format profile: Base Media / Version 2
Codec ID: mp42 (isom/mp42)
File size: 125 MiB
Duration : 52s 666ms
Overall bit rate: 20.0 Mbps

Video
ID: 1
Format: AVC
Format/Info: Advanced Video Codec
Format profile: Baseline@L4
Format settings, CABAC: No
Format settings, ReFrames: 1 frame
Format settings, GOP: M=1, N=30
Codec ID: avc1
Codec ID/Info: Advanced Video Coding
Duration: 52s 666ms
Bit rate: 20.0 Mbps
Width: 1 920 pixels
Height: 1 080 pixels
Display aspect ratio: 16:9
Frame rate mode: Constant
Frame rate: 30.000 fps
Color space: YUV
Chroma subsampling: 4:2:0
Bit depth: 8 bits
Scan type: Progressive
Bits/(Pixel*Frame): 0.321
Stream size: 125 MiB (100%)
Title: VideoHandle
mdhd_Duration: 52666
```

**Comment by scanlime** [comment]
20 Mbit is quite high for internet streaming, you may need to check your nginx configuration for a high enough rate limit, and you may need to use the network inspector to see if the client is downloading parts fast enough. If you really want to serve video at 20 megabits.

**Comment by scanlime** [comment]
For what it's worth i've also been dissatisfied with the default video quality; my instance increases the rates at all resolutions. As far as I can tell the rates that are checked in were measured as averages but written into the ffmpeg parameters as a maximum, so the actual bit rate ends up being lower than expected.

**Comment by Chocobozzz** [comment]
@scanlime You can make a PR to discuss these rates
