### ISSUE TITLE
Temporarily squashed comment avatars

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#2099]
**What happened?**

I've seen this happen a few times; when a video loads, some of the comment avatar icons appear horizontally "squashed". This is temporary, and any window resize will correct the layout.

One example screenshot after the page load but before resizing:

![Screen Shot 2019-08-30 at 2 31 47 PM](https://user-images.githubusercontent.com/923812/64052378-1eadfb80-cb33-11e9-95c6-64d8f8be94c6.png)

And after resizing:

![Screen Shot 2019-08-30 at 2 31 52 PM](https://user-images.githubusercontent.com/923812/64052386-240b4600-cb33-11e9-95ee-842af7dca3eb.png)

**What do you expect to happen instead?**

I expect aspect ratio of the icons to always be circular, and I expect the layout to remain stable.

**Steps to reproduce:**

Not sure; i've seen this happen on videos with multiple comments. The first N comments seem fine, the rest are squished. Have not narrowed it down further yet.

**Additional information**
* PeerTube version or URL: diode.zone, 1.4.0
* Browser name/version: Firefox 68.0.2 Mac OS
* NodeJS version: v10.16.3

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Findus23** [comment]
I could very shortly reproduce this on the same page (Firefox 68.0.2 Debian), but I'd even suspect a Firefox bug as just disabling and reenabling one CSS line (and I guess the repaint) fixed it.

**Comment by Chocobozzz** [comment]
I think it will be fixed by https://github.com/Chocobozzz/PeerTube/commit/6051946e444d095cbd845cae2c96e10b74405fdf
