### ISSUE TITLE
Manually install a plugin/theme on a production instance?

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#2101]
I read the new plugin/theme documentation and converted my custom CSS into an actual theme, but it seems to only explain how to test it on a dev instance. How would I manually install it on a production instance, avoiding publishing to NPM?

**Comment by Chocobozzz** [comment]
You can use https://docs.joinpeertube.org/#/maintain-tools?id=plugin-installuninstall on the server
