### ISSUE TITLE
Pending Status  follow instances

### ISSUE THREAD

**Issue by Anubys** [Chocobozzz/PeerTube#2102]
Hi

You have a problem with added follow instances, in the administration panel:

When added new followers to administration panel with follow tab, in the new tab "following" appear the URL  in  state "pending" permanent. The logs not show none  error.

**Additional information**
* PeerTube version 1.3.1

Thanx

**Comment by Chocobozzz** [comment]
What is your instance URL and that is the instance URL you try to follow?

**Comment by Anubys** [comment]
Hi
Our instance URL is --> https://videos.elbinario.net 
The URL follow list is:

peertube.video | Pending | Jul 13, 2019, 10:15:43 PM |   |  
-- | -- | -- | -- | --
3 | pe.ertu.be | Pending | Jul 13, 2019, 10:15:43 PM |   |  
4 | tube.4aem.com | Pending | Jul 13, 2019, 10:15:44 PM |   |  
5 | tube.p2p.legal | Pending | Jul 13, 2019, 10:17:05 PM |   |  
6 | peertube.uno | Pending | Jul 13, 2019, 10:18:45 PM |   |  
7 | visionon.tv | Pending | Jul 13, 2019, 10:20:13 PM |   |  
8 | peertube.linuxrocks.online | Pending | Jul 13, 2019, 10:22:12 PM |   |  
9 | sikke.fi | Pending | Jul 15, 2019, 1:16:47 AM |   |  
10 | framatube.org | Pending | Aug 19, 2019, 7:29:37 PM |   |  
11 | peertube.cat | Pending | Aug 19, 2019, 7:56:00 PM |  
 12 video.blender.org | Pending | Sep 2, 2019, 9:28:55 AM
-- | -- | --
Thanx for reply ;)

**Comment by Chocobozzz** [comment]
You started peertube without the right domain, so federation is broken. Try to use https://docs.joinpeertube.org/#/maintain-tools?id=update-hostjs to fix this

**Comment by Anubys** [comment]
Fixed !

Thanx ;)
