### ISSUE TITLE
Themes don't appear until the page is loaded

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#2104]
The default PeerTube theme is visible until the page finishes loading. The custom CSS box used to have this bug before it was fixed.

v1.4.0
Firefox 68.0.02

**Comment by Chocobozzz** [comment]
Should be better with https://github.com/Chocobozzz/PeerTube/commit/a2ffd046d61fb6424825f183af195ce1df2e156f
