### ISSUE TITLE
Getting followed as a small instance.

### ISSUE THREAD

**Issue by TheChymera** [Chocobozzz/PeerTube#2105]
I would like to run my own instance to be in perfect control on my content. But based on what I understand so far about peertube, people won't see my videos unless the admin of the instance they are on adds me to the followed list. As I would just be serving my content (20-30 videos right not) and likely not having any users except a handful of firends, it will make it very hard to be discovered, right?

Why don't you make your software auto-federate with everybody and let admins decide if they want to stay with that, whitelist, or blacklist (feliverse social media software does this)?

In the meantime, do you have any advice for a small instance to get noticed?

**Comment by Chocobozzz** [comment]
You can add your instance in the index website: https://instances.joinpeertube.org/

We also just implemented the auto follow feature: https://github.com/Chocobozzz/PeerTube/pull/2107
