### ISSUE TITLE
Auto-blacklisted videos not displaying due to JS error after v1.4.0

### ISSUE THREAD

**Issue by thombles** [Chocobozzz/PeerTube#2106]
**What happened?**

1. Visit the "auto-blacklisted videos" moderator page `/admin/moderation/video-auto-blacklist/list` when there is at least one auto-blacklisted video
2. The listing of videos never appears
3. Errors are shown in the console log:

```
ERROR TypeError: "e is undefined"
    videoById https://scitech.video/client/en_US/main-es2015.0de123bcac5c2b836eef.js:1
    check https://scitech.video/client/en_US/main-es2015.0de123bcac5c2b836eef.js:1
    diff https://scitech.video/client/en_US/main-es2015.0de123bcac5c2b836eef.js:1
    ngDoCheck https://scitech.video/client/en_US/main-es2015.0de123bcac5c2b836eef.js:1
    Gy https://scitech.video/client/en_US/main-es2015.0de123bcac5c2b836eef.js:1
    Gy https://scitech.video/client/en_US/main-es2015.0de123bcac5c2b836eef.js:1
    Gy https://scitech.video/client/en_US/main-es2015.0de123bcac5c2b836eef.js:1
    bC https://scitech.video/client/en_US/main-es2015.0de123bcac5c2b836eef.js:1
    w https://scitech.video/client/en_US/6-es2015.34aa8a3586db54a425c8.js:1
    updateDirectives https://scitech.video/client/en_US/main-es2015.0de123bcac5c2b836eef.js:1
```

**What do you expect to happen instead?**

The list of videos should display along with the control to unblacklist.

Workaround: Get the id from the response JSON, then perform a manual fetch to the blacklist DELETE endpoint with the correct authorisation header.

**Additional information**
* PeerTube version or URL: v1.4.0
* Browser name/version: Firefox 68.0.2
* NodeJS version: v10.16.3

**Comment by Chocobozzz** [comment]
Thanks @thombles, it should be fixed in https://github.com/Chocobozzz/PeerTube/commit/dedc7abb7beccb0b3a4a4fa4e8ccfef8ceecd5a6
