### ISSUE TITLE
Thai language not listed in Join PeerTube translation page

### ISSUE THREAD

**Issue by ppnplus** [Chocobozzz/PeerTube#2108]
**What happened?**
I would like to translate the Join PeerTube website into Thai, but the language isn't listed in the translation page.
**What do you expect to happen instead?**
I expect that Thai language would be listed.
**Steps to reproduce:**

1. Go to joinpeertube.org

2. Click on Language -> Translate

3. I can't find Thai language in the list.

**Additional information**
* PeerTube version or URL: This report is not associated to PeerTube software or instance.
* Browser name/version: Firefox 69.0 on Windows 10 Build 1903
* NodeJS version: -

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
I enabled it. Thanks!
