### ISSUE TITLE
Description shouldn't be truncated but the overflow hidden

### ISSUE THREAD

**Issue by tcitworld** [Chocobozzz/PeerTube#211]
For instance here : https://peertube.cpy.re/videos/watch/e8a1af4e-414a-4d58-bfe6-2146eed06d10

The link targets a youtube user page but is truncated to youtube.com, so I suggest either :
* truncate the rendered text and not the markdown / html
* abandon the idea of truncating and just hide the overflowing content (which seems best)

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/63c4b44961aa86ed4dabf039e495879103f9d729
