### ISSUE TITLE
Video uploads require manual validation by moderators - not for private video

### ISSUE THREAD

**Issue by EricThi** [Chocobozzz/PeerTube#2110]
**What happened?**

Hello, I report' for me, a little issue with video moderator.

I enable Video uploads require manual validation by moderators on my instance (for spam on film upload on my instance...)

This day, a new user upload a private video, i receive a notification for check this video.
For me, private video don't need to autoblacklist (it's only for user). Just, need to check if change private to public

=> it's possible to check for if private => don't blacklist, and if switch to public => auto blacklist if enable on instance ?

**Additional information**
* PeerTube version or URL: 1.3.1 - https://peertube.eric.ovh/about/instance
* Browser name/version: Firefox 69.0b
* NodeJS version: 
node --version
v11.15.0
npm --version
6.9.0

**Comment by Chocobozzz** [comment]
Hello,

We decided to include private videos in auto blacklist to give full control to admins/moderators.

The auto blacklist feature could also be abused if a user share its credentials to broadcast the video.

A plugin could override this default behaviour (we have dedicated hooks for the blacklist function).
