### ISSUE TITLE
enable to start peertube service

### ISSUE THREAD

**Issue by mrglobule** [Chocobozzz/PeerTube#2111]
**What happened?**

Hello, i cannot start service peertube, thank you in advance for your help.

**What do you expect to happen instead?**

**Steps to reproduce:**

1.service peertube start

2.service peertueb status

3.* peertube.service - PeerTube daemon
   Loaded: loaded (/etc/systemd/system/peertube.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-09-05 09:05:06 CEST; 1s ago
  Process: 9963 ExecStart=/usr/bin/npm start (code=exited, status=226/NAMESPACE)
 Main PID: 9963 (code=exited, status=226/NAMESPACE)

Sep 05 09:05:06 MVPEERTUBE-GEM systemd[1]: peertube.service: Service RestartSec=100ms expired, scheduling restart.
Sep 05 09:05:06 MVPEERTUBE-GEM systemd[1]: peertube.service: Scheduled restart job, restart counter is at 5.
Sep 05 09:05:06 MVPEERTUBE-GEM systemd[1]: Stopped PeerTube daemon.
Sep 05 09:05:06 MVPEERTUBE-GEM systemd[1]: peertube.service: Start request repeated too quickly.
Sep 05 09:05:06 MVPEERTUBE-GEM systemd[1]: peertube.service: Failed with result 'exit-code'.
Sep 05 09:05:06 MVPEERTUBE-GEM systemd[1]: Failed to start PeerTube daemon.

**Additional information**
* PeerTube version or URL: peertueb 1.4.0
* Browser name/version: chrome
* NodeJS version: 10.15.2

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Please paste the content of the peertube log file

**Comment by mrglobule** [comment]
here two logs?
[varlogdaemon.log](https://github.com/Chocobozzz/PeerTube/files/3578009/varlogdaemon.log)

[varwwwpeertubestoragelogspeertube.log](https://github.com/Chocobozzz/PeerTube/files/3578011/varwwwpeertubestoragelogspeertube.log)

**Comment by Chocobozzz** [comment]
Seems the error is `Failed at step NAMESPACE spawning /usr/bin/npm: Permission denied`

What it the output of `which npm`?

**Comment by mrglobule** [comment]
root@MVPEERTUBE-GEM:~# which npm
/usr/bin/npm

**Comment by Chocobozzz** [comment]
In fact `Failed to set up mount namespacing: Permission denied` seems to be the error.

On what type of server/OS do you try to install peertube? Do you use LXC or something like that?

**Comment by mrglobule** [comment]
yes it's a VM on LXC (proxmox)

**Comment by Chocobozzz** [comment]
Then I'm sorry I can't help you.

There are many bug reports about systemd in lxc, maybe you'll find a way to figure it out (for example: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916639)

**Comment by mablr** [comment]
Hello,
first of all I'm sorry to bring this up again.
I had the same problem as @mrglobule .
To solve it, just use the unprivileged LXC containers from Proxmox.
