### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#2114]
**What happened?**
Upload fails with the message «Unknown error».
**What do you expect to happen instead?**
Upload succeeded
**Steps to reproduce:**

1. Try to upload a video, no matter the size.

2. Wait until processing.

3.

**Additional information**
* PeerTube version or URL: peertube.stemy.me
* Browser name/version: Firefox 63
* NodeJS version: 8.16.1

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): No trace in logs.

**Comment by Chocobozzz** [comment]
Please paste the server logs when you upload the video.

**Comment by stemy2** [comment]
OK, it failed again. And didn't leave any trace in the logs.

**Comment by maxdrash** [comment]
Can you bring to us the browser error ?
You have to find this in browser's dev tools or F12.

**Comment by stemy2** [comment]
I found that when a such problem occurs, the video is actually published, but changes during upload are not saved and the video is set as private. I can update video infos after this, but this is a bit annoying.

**Comment by Chocobozzz** [comment]
Please paste the server logs when you upload the video.

**Comment by stemy2** [comment]
It didn't leave any trace in the logs.

**Comment by Chocobozzz** [comment]
> It didn't leave any trace in the logs.

Enable debug logs, I can't help if I don't see what peertube does. Console logs and network client logs could also help.

**Comment by stemy2** [comment]
The error happened again, how do i enable debug logs ?

**Comment by Chocobozzz** [comment]
In your config file: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L97
