### ISSUE TITLE
SRT captions strip unescaped text that looks like HTML tags

### ISSUE THREAD

**Issue by thombles** [Chocobozzz/PeerTube#2116]
**What happened?**

* Attached an SRT captions file with the following line:

```
85
00:08:22,680 --> 00:08:29,200
or a MyValue<String> like before and it doesn't
matter what type it is as long as it implements
```

* It renders like this in the player (notice that `<String>` is missing):

![Screen Shot 2019-09-08 at 12 47 19 pm](https://user-images.githubusercontent.com/5511175/64482539-ff9c2180-d236-11e9-8132-2d421a8b2381.png)

**What do you expect to happen instead?**

PeerTube should automatically perform whatever escaping is necessary for this to display correctly.

Workaround: Manually ensure tag-like text is replaced with `&lt;` and `&gt;` before uploading

**Additional information**
* PeerTube version or URL: v1.4.0
* Browser name/version: Firefox v69.0
* NodeJS version: v10.16.3

I did a bit of research into how this is supposed to work and it's ambiguous.

When I download SRT captions from YouTube it gives me text containing bare < and >, as in the example above.

It is generally agreed that certain [HTML tags can be used to provide basic formatting](http://forum.doom9.org/showthread.php?s=3fdc5c275a7f11a0dc0a5e3685743285&p=470941#post470941) in the SRT file, but it is not clear whether other tags should be stripped or passed verbatim.

The WebVTT specification [requires that they are escaped](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API#Cue_payload) in that format, which is not SRT but based upon it:

<blockquote>
A cue text payload cannot contain the string "-->", the ampersand character (&), or the less-than sign (<). Instead use the escape sequence "&amp;" for ampersand and "&lt;" for less-than. It is also recommended that you use the greater-than escape sequence "&gt;" instead of the greater-than character (>) to avoid confusion with tags.
</blockquote>

It seems I am not the first person to come across this issue - I found another service [which offers escaped or unescaped modes](https://help.smartling.com/hc/en-us/articles/360007894874-SubRip-SRT) for handling SRT files.

In PeerTube's case I think it makes the most sense to always escape things, especially if it will be provided to WebVTT.

**Comment by AutomCoding** [comment]
The root problem is that SRT doesn't specify which HTML tags can be used. The most common is &lt;b&gt;, &lt;i&gt;, &lt;u&gt; and similar, but I have also seen non-HTML ones like &lt;left&gt; and &lt;right&gt; (used like &lt;center&gt; for text alignment) and some new from  HTML5 like &lt;del&gt;, &lt;strong&gt; and &lt;em&gt;. Most SRT decoders therefore hide all tag looking things they don't support.

Displaying all the tags PeerTube's SRT parser doesn't recognice would in my opinion not be the best option as I reckon there to be far more cases of unsupported tags than cases of users wanting to display tag looking constructs.

**Comment by thombles** [comment]
> Displaying all the tags PeerTube's SRT parser doesn't recognice would in my opinion not be the best option as I reckon there to be far more cases of unsupported tags than cases of users wanting to display tag looking constructs.

Fair analysis, you've convinced me! The workaround is somewhat technical but not difficult for someone who realises what happened. In this case the current behaviour is fine, so I'll close the issue until somebody has a compelling reason to revisit it.
