### ISSUE TITLE
Video loading but not playing

### ISSUE THREAD

**Issue by mrglobule** [Chocobozzz/PeerTube#2118]
**What happened?**
Video loading, but never play
**What do you expect to happen instead?**
video playing
**Steps to reproduce:**

1.I upload a video, it'ok, i can see te thumbnail

2.i see the loading circle video, but it's never play video

3.

**Additional information**
* PeerTube version or URL: peertube v1.4.0
* Browser name/version: chrome
* NodeJS version: v10.15.2
[peertube2.log](https://github.com/Chocobozzz/PeerTube/files/3589310/peertube2.log)

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Please paste your console logs and your network logs (F12 when you are watching the video)

**Comment by mrglobule** [comment]
Goodmorning Chocobuzz,
Tha,nks for you help.
[133.1.25.178-console.log](https://github.com/Chocobozzz/PeerTube/files/3599394/133.1.25.178-console.log)
[133.1.25.178-network.log](https://github.com/Chocobozzz/PeerTube/files/3599398/133.1.25.178-network.log)

**Comment by Chocobozzz** [comment]
I think here is something wrong in your server configuration: `http://133.1.25.178:443/static/torrents/c976ea5d-cb2b-4ebe-8018-0ec177c82eda-480.torrent`. It should be port 80 no?

**Comment by mrglobule** [comment]
here are my two conf files

[peertube.txt](https://github.com/Chocobozzz/PeerTube/files/3599500/peertube.txt)
[nginx.conf.txt](https://github.com/Chocobozzz/PeerTube/files/3599506/nginx.conf.txt)

**Comment by Chocobozzz** [comment]
I meant to say your peertube configuration file :)

https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L7 should be `true`. Then to upload another video, and check if it plays correctly.

**Comment by mrglobule** [comment]
OK, sorry, the .yaml was set to false, i set it to true and it's OK
Great thanks
Great Job
Regards
