### ISSUE TITLE
Missing default-audio-background.jpg after upgrade

### ISSUE THREAD

**Issue by gbarre** [Chocobozzz/PeerTube#2120]
**What happened?**
After upgrading from 1.3.1 to 1.4.1 (not tested on fresh install), adding an audio file without background image failed.

**What do you expect to happen instead?**
A default image should be given to audio file.

**Steps to reproduce:**

1. (may be not necessary) upgrade from 1.3.1 to 1.4.1

2. Add audio file without background image.

**Additional information**
* PeerTube version or URL: 1.4.1 (local install)
* Browser name/version: Firefox 69.0
* NodeJS version: v10.16.3

Logs seems clear : 
error[11/09/2019 à 10:43:57] Cannot execute addVideo with many retries. { "err": { "stack": "Error: ENOENT: no such file or directory, open '/var/www/peertube/versions/peertube-v1.4.1/server/assets/default-audio-background.jpg'", "message": "ENOENT: no such file or directory, open '/var/www/peertube/versions/peertube-v1.4.1/server/assets/default-audio-background.jpg'", "errno": -2, "code": "ENOENT", "syscall": "open", "path": "/var/www/peertube/versions/peertube-v1.4.1/server/assets/default-audio-background.jpg" } }
error[11/09/2019 à 10:43:57] Error in controller. { "err": "Error: ENOENT: no such file or directory, open '/var/www/peertube/versions/peertube-v1.4.1/server/assets/default-audio-background.jpg'" } 

By the way, the directory "server" in peertube/versions/peertube-v1.*.1/ does not exist. I might missed something ?

**Comment by Chocobozzz** [comment]
> By the way, the directory "server" in peertube/versions/peertube-v1.*.1/ does not exist. I might missed something ?

No, I think it's a bug

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/fff2183df6129362ad50941d4d1979d4aa292801

Thanks for the issue @gbarre
