### ISSUE TITLE
Instance down after tons of database errors

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#2121]
No idea whats going on here. Running Peertube 1.4.1 via Docker. `docker-compose restart` failed with errors, I had to reboot the server to fix the issue.

Here are the last 100 lines of Postgres and Peertube logs, I also have the full logs in case you need more info.

https://gist.github.com/Nutomic/3c546223fdf4dc6664a1eb52c90f144c

I did a short downgrade to Peertube 1.4.0, could that have something to do with the error?

**Comment by Chocobozzz** [comment]
> I did a short downgrade to Peertube 1.4.0, could that have something to do with the error?

I don't think so. Maybe check your system logs?

**Comment by Chocobozzz** [comment]
Closing this issue, since I think it is not related to PeerTube, but rather a system error.
