### ISSUE TITLE
Policy on servers that run ads?

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#2122]
**What happened?**

I just noticed a new follow from a server, and then noticed this server included advertising code,

https://peervideo.net/about/instance

The site client has been modified to include an obfuscated click hijacker:

https://gist.github.com/scanlime/8ec1ff88b1467434c46143a75704305d

**What do you expect to happen instead?**

- in accordance with the AGPL, the client should match the provided code

- administrators can create and share lists, possibly with automated reporting, of sites that include malicious modifications

**Steps to reproduce:**

1. Visited peervideo dot net

2. Click any link and you get a popup, if your browser doesnt block it

3. View source

**Additional information**
* PeerTube version or URL:
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Findus23** [comment]
I also got them as a new follower, tried to read the about page and got redirected to a weird ad-website. After seeing how many third-party domains they embed, I simply removed them as a follower.
Which is weird, as it is the instance also used by stabbot (see also https://gitlab.com/juergens/stabbot/issues/28)

**Comment by Chocobozzz** [comment]
With PeerTube 2, administrators can now explain how they pay the server. You're free to maintain a list of instances that run ads: we have a dedicated mailing list for peertube administrators https://framalistes.org/sympa/subscribe/peertube-admin
