### ISSUE TITLE
Make features available without app defined context right click

### ISSUE THREAD

**Issue by Golutazem** [Chocobozzz/PeerTube#2125]
Relying upon using the context (usually right) mouse click creates a conflict and usability problem. Re-definition of that button may be forbidden by the user's configuration or a browser menu may open over it.

All functions which are available in a PeerTube defined context menu should be otherwise available.

I see 2 functions which are currently only available by the PeerTube context menu:
- URL at current time
- magnet URI
The other 2 features are otherwise accessible.

**Comment by Chocobozzz** [comment]
> URL at current time 

It's available in the share modal

> magnet URI

We removed it from the download modal since most of bittorrent applications do not support a parameter we use in it

**Comment by Golutazem** [comment]
So far, I use the special WebTorrent client when downloading WebTorrents.  I guess that is one of the ones which work, but I am unable to test because
no browser copies the magnet -- not even ones where I think they have the default configuration. -- a matter for another issue.
I hope that removal of the magnet URI will be reverted or it otherwise made available again.

**Comment by ChanoSan** [comment]
I'd like to second this request. Having access to the magnet URI could be useful, and at least people can find a way to hack around it. At the very least, an option in settings to enable in with a default disabled state would avoid needless confusion by most users while allowing others to tinker with it.

**Comment by Chocobozzz** [comment]
> I hope that removal of the magnet URI will be reverted or it otherwise made available again.

No sorry we won't. We had too many reports that the magnets in PeerTube were not working. We'll gladly add it when popular torrent clients supports the `xs` parameter. See https://github.com/Chocobozzz/PeerTube/issues/1703#issuecomment-469760948 for more information

**Comment by Golutazem** [comment]
Transmission feature request for xs or as parameter
https://github.com/transmission/transmission/issues/317
