### ISSUE TITLE
Add share buttons for Pinterest, Whatsapp, Telegram, Instagramm ...

### ISSUE THREAD

**Issue by maxlinux2000** [Chocobozzz/PeerTube#2127]
As I say in the title, it would be nice to have the possibility to share our videos on PeerTube, using the commercial platforms to our advantages.

I know that we are trying to create a Confederate network outside of Google, but this does not mean that we cannot use their networks for the distribution of our videos in Peertube.

Therefore I propose to add in the web version for mobile, the buttons of Pinterest, Whatapp, Telegram, facebook, twitter, but also Mastondon, Diaspora ...

And in the computer version, only some possible by not having the apps.

**Comment by maxdrash** [comment]
By a plugin way.

**Comment by maxlinux2000** [comment]
This plugins already exists? Where?

**Comment by maxdrash** [comment]
I don't think this already exists, but a plugin would be the best way.

**Comment by Poopooracoocoo** [comment]
#2160

**Comment by Chocobozzz** [comment]
Can be implemented in plugins (see for example https://www.npmjs.com/package/peertube-plugin-social-sharing)
