### ISSUE TITLE
Improvements: Wordpress plugins in PeerTube.

### ISSUE THREAD

**Issue by maxlinux2000** [Chocobozzz/PeerTube#2129]
Wordpress has its API to make plugins communicate with the Core.
PeerTube does the same thing but in a different way.

Since you are at an early stage of development, it would be nice if PeerTube can communicate with the plugins using a Wordpress compatible API.

What would be earned with this? Well, Wordpress plugins would work with Peertube ... or at least some of them. In this way we will build a huge amount of plugins perfectly developed and maintained by the wordpress community.
Clearly not all plugins would work, but many would.

I see more advantages than disadvantages.
The word to PeerTube programmers.

**Comment by Findus23** [comment]
Hi, 
Just for your information, WordPress (and WordPress plugins) are written in PHP unlike PeerTube which uses NodeJS. So just by this it is not possible to use Wordpress plugins in Peertube.

But even if we ignore this, as a WordPress plugin can modify every aspect of WordPress, creating a "Wordpress compatible API" would be pretty much the same as creating all of WordPress from scratch.

**Comment by JigmeDatse** [comment]
I am pretty sure that Findus is largely correct based on the concept that, "Wordpress plugins would work."  

To me, a better goal would be to develop a Wordpress plugin which would interact with PeerTube, or a PeerTube plugin which would interact with WordPress.  This would be a way to DRY in a very real way.  I'm not sure if there are said plugins in either way.  

My thinking would be either would be useful.  But if I want PeerTube content in Wordpress, I probably want a Wordpress plugin.  

And I'm not sure if I can think of much reason to have a PeerTube plugin.  Though the idea that kind of makes sense to me would be a plugin which would put the comments on the WordPress site onto PeerTube.  Of course that would lead to federating those comments.  

But then, WordPress is starting to work more with something similar anyway.

**Comment by Chocobozzz** [comment]
As @Findus23 said. Closing this issue.
