### ISSUE TITLE
Video chat / conference between users.

### ISSUE THREAD

**Issue by maxlinux2000** [Chocobozzz/PeerTube#2130]
Imagine that 2 or more users can discuss and see each other (I know there are whatsapp, but maybe people don't want to share their phone number with a stranger)

The solution is to use jitsi!
https://jitsi.org/downloads/
(or other opensource similar projects)

In this way, 2 or more users want to talk (and see each other) press the call button (near the avatar of the other user), and a window opens with jitsi where they can discuss, without sharing sensitive data.

The programming part in PeerTube is quite simple I think. It is about adding a telephone call button to each user, and when pressed, is redirected to the connection to a jetsi instance on the same (or other) server.
It is necessary to give the user the possibility to choose whether the conversation is private or public, so that other users can enter the video conference or not.

The server administrator has to install jitsi and maybe coturn for android clients.
But this is very simple.

This would be a way to add a feature to PeerTube that YouTube does not have.
I do not say that it will be used often, but surely users will find a way to use it ... such as giving private lessons to one or more people, or solving a doubt, or ....

**Comment by Findus23** [comment]
Honestly I think with the same argument one could argue that every website should have a jitsi button. And if one wants to add something to every website it might be easier to simply do it at the other end of the HTTP connection and simply write a browser extension that allows to start a videochat-room for every website.

But of course writing a peertube plugin that does this shouldn't be that hard.

**Comment by JigmeDatse** [comment]
This feels like a great example of something which would be good to implement in a plugin.  I don't really think it should be a core feature to be honest.  Any interaction which goes between different services I think should be a plugin.  But, I think as a plugin that this really makes sense...

**Comment by ZenoArrow** [comment]
This may be a nice feature to have, but I'd just like to suggest that Jitsi is not the only player in this space, and it's worth looking at what Matrix are offering as well:

https://matrix.org/

**Comment by DontUseGithub** [comment]
I also agree that it'd be better if implemented as an addon. 
I don't think tho that we should use jitsi but rather Matrix.org and XMPP which both are very popular decentralized IMs.
Both Matrix.org and XMPP are full of features including e2e encryption and voice calling.

**Comment by discapacidad5** [comment]
I do not see much advantage to this since in the case of matrix, with the person placing his Matrix URL in his profile, he can allow other people to contact him

  I see more future to create live broadcasts that can incorporate two people to the same broadcast to discuss live in a video broadcast

**Comment by Chocobozzz** [comment]
Closing as it's out of the scope of PeerTube
