### ISSUE TITLE
Peertube 1.4 and Chrome 77 unable to load video

### ISSUE THREAD

**Issue by mrglobule** [Chocobozzz/PeerTube#2132]
**What happened?**

The video don't play with chrome 77
It was OK with chrome 76 and it's OK with Firefox 60.4ESR
**What do you expect to happen instead?**
I expected the watching the video
**Steps to reproduce:**
click on video and i got just the circle only with chrome 77
1.

2.

3.

**Additional information**
* PeerTube version or URL: on LAN, Peertube 1.4.0
* Browser name/version: chrome 77
* NodeJS version: 10.15.2

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
[peertube.log](https://github.com/Chocobozzz/PeerTube/files/3621271/peertube.log)

**Comment by Findus23** [comment]
Hi,

Can you please post any error from the browser console (you can open the browser developer tools with <kbd>F12</kbd>)

**Comment by mrglobule** [comment]
58f5f3e8-970f-4057-8335-fa3700a8f43b:1 Uncaught (in promise) TypeError: Method Promise.prototype.then called on incompatible receiver [object Object]
    at I.then (<anonymous>)

**Comment by mrglobule** [comment]
I upgrade v1.4.0 to v1.4.1
I update chrome to 77.0.3865.90
And i have the same problem

**Comment by filmaidykai** [comment]
The problem is with chrome not peertube so we have wait for a proper fix from google chrome team...

**Comment by Nutomic** [comment]
This sounds really similar to #2126, except that its Chrome, not Firefox. Do you have Content Security Policy enabled?

**Comment by mrglobule** [comment]
Thanks for answer,
What is "Content Security Policy"? In chrome 77?

**Comment by Nutomic** [comment]
Its a setting on the server, search the config for "csp".

**Comment by Findus23** [comment]
@mrglobule 
Does the issue occur only on your server or on every peertube instance?

**Comment by mrglobule** [comment]
i test the site:
https://video.greenmycity.eu/videos/watch/906d5538-cc02-4d77-b78d-575c3aa1eae3

And i have the same problem

**Comment by mrglobule** [comment]
> Its a setting on the server, search the config for "csp".

i try but no effect

**Comment by Findus23** [comment]
I have set up a Windows VM with Chrome 77.0.3865.90 and tested it on my peertube instance.

HLS videos work perfectly fine.
Non-HLS videos stay black and the error mentioned above is shown in the console:
```
Uncaught (in promise) TypeError: Method Promise.prototype.then called on incompatible receiver [object Object]
at I.then ()
```
I'll try to set up a dev peertube instance to find out where exactly the error is thrown.

**Comment by Findus23** [comment]
I can't get it set up right so I can access the server from the VM, so I'll have to wait until chromium 77 is available for debian until I can further test this.

**Comment by mrglobule** [comment]
Thanks a lot for answer
I set HLS to true on my server instance, but video don't play with my chrome....
So i set back HLS to false

**Comment by JohnXLivingston** [comment]
The HLS settings only applies for new videos. Old video are not converted in HLS.

**Comment by mrglobule** [comment]
Thanks a lot,
I apply HLS to true, and i upload a new video, but chrome cannot be able to read the video????

**Comment by swdee** [comment]
Running Peertube 1.3.1 currently and have the same problem when upgrading to Chrome v77.

I get the same JS error

```
Uncaught (in promise) TypeError: Method Promise.prototype.then called on incompatible receiver [object Object]
    at e.then (<anonymous>)
```

**Comment by swdee** [comment]
This issue reported is similar to one reported here https://github.com/angular/angular/issues/32802

Based on the discussion in that issue I confirm that Chrome Version 77.0.3865.90 is not working (does not play video) but Beta Version 78.0.3904.34 or earlier versions (Chrome v76 and older) do work.

**Comment by Chocobozzz** [comment]
Thanks @swdee, so it's a chrome bug and it won't be backported https://bugs.chromium.org/p/chromium/issues/detail?id=1008376

We just have to wait the next chrome release

**Comment by insurrectus** [comment]
This was fixed in Chromium 78
https://chromium.googlesource.com/chromium/src/+/2c47467c5f28a93d77349492683e6994cd96ef33

**Comment by florentbolo** [comment]
Is someone found a temporary fix for this ?
thx
