### ISSUE TITLE
Possible bug with youtube-dl and youtube (rate limiting from youtube?)

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2136]
It seems that youtube changed the video format for some videos (I think that they use HLS now). The youtube-dl version used by peertube (v1.4.1) failed to download these files.

Here are some examples:
- https://www.youtube.com/watch?v=pFxCLgsD_LU
- https://www.youtube.com/watch?v=t5XB3kz_a28

With an up-to-date version of the youtube-dl CLI (version 2019.08.13), the dowload works.

How can I update the youtube-dl used by my peertube instance ?

**Comment by Findus23** [comment]
It seems like Peertube uses youtube-dl packaged for npm:
https://github.com/Chocobozzz/PeerTube/blob/210709a9076ac152dd377234866b8e9b9108382a/package.json#L162

And it seems like this `node-youtube-dl` downloads youtube-dl either on the npm install (so in case of peertube when the release is built) or it can be set up to update during runtime:
https://github.com/przemyslawpluta/node-youtube-dl/blob/2d43374e6a41aae92edece92dc1c8fbc8361a1f8/package.json#L185
https://github.com/przemyslawpluta/node-youtube-dl#update

**Comment by Findus23** [comment]
You could of course try to replace the `/var/www/peertube/peertube-latest/node_modules/youtube-dl/bin/youtube-dl` yourself, but at least according to the `details` file in the same directory
```json
{
  "version": "2019.09.12.1",
  "path": "/var/www/peertube/versions/peertube-v1.4.1/node_modules/youtube-dl/bin/youtube-dl",
  "exec": "youtube-dl"
}
```
the version bundled in peertube 1.4.1 is pretty new (`2019.09.12.1`)-

**Comment by JohnXLivingston** [comment]
Weird... `/var/www/peertube/versions/peertube-v1.4.1/node_modules/youtube-dl/bin/youtube-dl "https://www.youtube.com/watch?v=pFxCLgsD_LU"` work fine, but from peertube it doesn't work.

Maybe its a peertube bug ? With this video format, the final file is rename into .mkv. Perhaps peertube does not find the file because of this ?

**Comment by JohnXLivingston** [comment]
[youtube] t5XB3kz_a28: Downloading video info webpage
[youtube] t5XB3kz_a28: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[dashsegments] Total fragments: 150
[download] Destination: GARAGE LOPEZ CIRQUE ELECTRIQUE 13_09_2019 PARIS-t5XB3kz_a28.f299.mp4
[download] 100% of 509.57MiB in 00:18
[dashsegments] Total fragments: 77
[download] Destination: GARAGE LOPEZ CIRQUE ELECTRIQUE 13_09_2019 PARIS-t5XB3kz_a28.f251.webm
[download] 100% of 11.23MiB in 00:13
[ffmpeg] Merging formats into "GARAGE LOPEZ CIRQUE ELECTRIQUE 13_09_2019 PARIS-t5XB3kz_a28.mkv"
Deleting original file GARAGE LOPEZ CIRQUE ELECTRIQUE 13_09_2019 PARIS-t5XB3kz_a28.f299.mp4 (pass -k to keep)
Deleting original file GARAGE LOPEZ CIRQUE ELECTRIQUE 13_09_2019 PARIS-t5XB3kz_a28.f251.webm (pass -k to keep)

**Comment by JohnXLivingston** [comment]
My bad. `/var/www/peertube/versions/peertube-v1.4.1/node_modules/youtube-dl/bin/youtube-dl "https://www.youtube.com/watch?v=pFxCLgsD_LU"` **does not work**.
The download is stuck.

**Comment by JohnXLivingston** [comment]
I tried to update youtube-dl with `npm run update`, but it seems that youtube-dl is up to date.

I just remember that I had to install youtube-dl with a snap package on my computer (version 2019.08.13). I think the bug is on youtube-dl. I close this issue. Thanks.

**Comment by Chocobozzz** [comment]
PeerTube automatically update `youtube-dl` every 24 hours

**Comment by Findus23** [comment]
```
➜  ~ time /var/www/peertube/versions/peertube-v1.4.1/node_modules/youtube-dl/bin/youtube-dl "https://www.youtube.com/watch?v=pFxCLgsD_LU"
[youtube] pFxCLgsD_LU: Downloading webpage
[youtube] pFxCLgsD_LU: Downloading video info webpage
[youtube] pFxCLgsD_LU: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[dashsegments] Total fragments: 36
[download] Destination: Clip chambre à air-pFxCLgsD_LU.f248.webm
[download] 100% of 24.70MiB in 00:05
[dashsegments] Total fragments: 20
[download] Destination: Clip chambre à air-pFxCLgsD_LU.f140.m4a
[download] 100% of 2.78MiB in 00:01
[ffmpeg] Merging formats into "Clip chambre à air-pFxCLgsD_LU.mkv"
Deleting original file Clip chambre à air-pFxCLgsD_LU.f248.webm (pass -k to keep)
Deleting original file Clip chambre à air-pFxCLgsD_LU.f140.m4a (pass -k to keep)
 "https://www.youtube.com/watch?v=pFxCLgsD_LU"  4.08s user 0.74s system 44% cpu 10.847 total
➜  ~ /var/www/peertube/versions/peertube-v1.4.1/node_modules/youtube-dl/bin/youtube-dl --version
2019.09.12.1
```

And when importing in peertube, I had to wait less than 15s for the video to be watchable.

So I guess the issue is either with your server or Google is limiting your IP-Address or the Address-range that you are in.

**Comment by JohnXLivingston** [comment]
Thanks. This is weird...

**Comment by JohnXLivingston** [comment]
I just tried again and today it worked.
