### ISSUE TITLE
Unable to add video to a specific playlist if more than 15 playlists exist

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#2138]
Hello!

**What happened?**
I have created more than 15 playlist (28 in total), but I am unable to add videos to the first playlists as only 14 are showed in the "register menu" in the video view.

Same problem with the API, which report 28 playlists but show only 15 : 
![Capture d’écran de 2019-09-19 11-59-28](https://user-images.githubusercontent.com/7755000/65234633-3a267980-dad5-11e9-96aa-8c61f03bb188.png)

I have not found any parameters to get more than 14 playlist int the API, is this exist?

**What do you expect to happen instead?**
It should be possible to add video to any playlist. Perhaps by expending the list to more than 15, or adding a parameters to get all existing playlist?
**Steps to reproduce:**

1. Create 16 playlist

2. Open a video

3. Try to register your video to the first playlist created (or the oldest modified), it does not appear in the list

**Additional information**
* PeerTube version or URL: Peertube 1.4.0
* Browser name/version: Firefox
* NodeJS version: node 10

Does not hesitate to tell me if anything is missing or if I could give you more details

Thanks!

**Comment by LecygneNoir** [comment]
Hello!

As suggested on IRC, I have rebuilt an image after modifying this line:
https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/constants.ts#L26

I change 15 to 30, and it indeed solves the problem by displaying 30 playlists instead of 15 :+1: 
![Capture d’écran de 2019-09-29 16-36-21](https://user-images.githubusercontent.com/7755000/65834042-54333980-e2d7-11e9-9850-aee1252a7dde.png)


Dunno if this is acceptable for production but does the job as workaround.

Perhaps an option (from user profile?) to change this value could be an idea? But it would be not really instinctive :-/

As an idea, on youtube, playlists list offer recent playlists (as Peertube does) and also a field to search for older playlists if they are not visible. Is it something possible?

Please feel free to ask if some more test could help :pray: 

Thanks!

**Comment by Chocobozzz** [comment]
> a field to search for older playlists if they are not visible. Is it something possible?

Yep, this is a very good idea.

**Comment by LecygneNoir** [comment]
While I think about it, an option in the API to allow getting all playlist could be a good addition too :thinking: 

At the moment it seems to be controlled by the same constant pagination.count.default than the UI (on my instance I get 30 max when listing playlists)

**Comment by rigelk** [comment]
I fixed the overflow in 223b24e618146f85b20b5bf365bc18d14a5964cd.

**Comment by rigelk** [comment]
I added a search input and search option in the API for a user's playlists:

![Screenshot_2019-12-26 UWwVx62](https://user-images.githubusercontent.com/6329880/71473240-80772d00-27d6-11ea-9de5-a8ea1d1e6105.png)
