### ISSUE TITLE
Download option: sound only 

### ISSUE THREAD

**Issue by 6543** [Chocobozzz/PeerTube#2144]
option to choose sound only (could be added as option to resolution dropdown menue)?

**Comment by Chocobozzz** [comment]
Needs https://github.com/Chocobozzz/PeerTube/issues/1437 first

**Comment by kevATin** [comment]
As someone who likes having thumbnails for their music files I'd very much welcome if there was also the option to download mp3 files with the video thumbnail/preview embedded (in full size ideally).

**Comment by Chocobozzz** [comment]
Now https://github.com/Chocobozzz/PeerTube/issues/1437 is implemented, you can download a mp4 containing only the audio track (if the admin enabled the audio-only option).
