### ISSUE TITLE
Is it possible to ban future instance subscribe asking ?

### ISSUE THREAD

**Issue by Elrondo46** [Chocobozzz/PeerTube#2146]
**What happened?**
Already refused instances, spam my instance of subscribe asking 

**What do you expect to happen instead?**

Possibility to ban instances and no more have subscribe asking from these instances

**Additional information**
* PeerTube version or URL: 1.4.1

**Comment by Findus23** [comment]
Sounds like what I described in https://github.com/Chocobozzz/PeerTube/issues/2143
