### ISSUE TITLE
Detailed tooltip for formatted counters

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#2147]
It's a bit frustrating when we have this formatted views counter (below, "1K views") without the real (detailed) number :
![image](https://user-images.githubusercontent.com/371705/65747052-b84fd500-e100-11e9-91a9-13a80744bd86.png)

I suggest to add a tooltip over the formatted number so we can have this information.

**Additional information**
* PeerTube version or URL: 1.4
* Browser name/version: Firefox

**Comment by fflorent** [comment]
I guess that is an easy contribution to do. But I identified some pitfalls, things to clarify:
 - these are already localized strings. Should we break those (asking all localizer to work again on them)?
 - should we display the tooltip when the string is not formatted? (I guess no)
 - what about other formatted counters (account / channel subscribers, …)? Should we generalize it anyways to any formatted numbers?

:)

**Comment by Chocobozzz** [comment]
> these are already localized strings. Should we break those (asking all localizer to work again on them)?

I'm not sure to understand what string we would break if we add this feature

> should we display the tooltip when the string is not formatted? (I guess no)

I don't think so either

> what about other formatted counters (account / channel subscribers, …)? Should we generalize it anyways to any formatted numbers?

It could be a good idea: we could create a dedicated "counter" component

**Comment by fflorent** [comment]
> I'm not sure to understand what string we would break if we add this feature

I am not familiar with Angular, but I suspect it would break, indeed.

Considering this part of the watch component (`client/src/app/videos/+video-watch/video-watch.component.html`):
```html
            <div i18n class="video-info-date-views">
              Published {{ video.publishedAt | myFromNow }} - {{ video.views | myNumberFormatter }} views
            </div>
```

The translation key includes both the publication date and the number of views. Yet, we need a tooltip for the latest only.

Cheers!
Florent

**Comment by Chocobozzz** [comment]
Okay then it's not important if we break some strings :)

**Comment by byrw** [comment]
@Chocobozzz May I work on this? 
I'm thinking about creating a counter component and removing the logic from html.
Is that a good idea?

**Comment by rigelk** [comment]
@byrw why create a counter component? This seems overkill when you can just add a `title` attribute to the view counter in the `video-miniature` and `video-watch` compontents.

**Comment by byrw** [comment]
@rigelk thank you for answering.

Now to answer your question, seems like the logic to count the number is repeated in some parts of the code, and the idea to create a new component was from @Chocobozzz.

But I can create a PR with just the title if you want.

**Comment by Poslovitch** [comment]
@rigelk Since #3173 is closed, should this one be closed too?

**Comment by rigelk** [comment]
@Poslovitch definitely! Thanks for spotting it.
