### ISSUE TITLE
Script to generate missing resolutions/formats of all local videos

### ISSUE THREAD

**Issue by BenLubar** [Chocobozzz/PeerTube#2148]
It would be nice to have a script that would queue transcoding jobs for missing resolutions and HLS versions after settings were changed.

**Comment by ParleurA** [comment]
I'd like this very much too!

**Comment by stevenmcastano** [comment]
+1 for getting this done... it would be great! Or at least some way per video to trigger it even if its 1 at a time through the UI. It's better than deleting and uploading again.

**Comment by bikubi** [comment]
+1 & would like to add: it would be great if this script also _deleted_ unneeded/deactivated resolutions & esp. formats, like all webtorrents after I switch to HLS-only.

**Comment by Chocobozzz** [comment]
Hello,

You can now select in administration videos that are in a specific format (hls/webtorrent) and delete/create transcoding jobs in bulk which is much more flexible than a script. So with the ability to display 100 results per page, I think we can close this issue.
