### ISSUE TITLE
Cannot enable HLS

### ISSUE THREAD

**Issue by n76** [Chocobozzz/PeerTube#2150]
**What happened?**
Upgraded ffmpeg from 3.4.6 to 4.2.1.
Upgraded peertube from 1.4.0 to 1.4.1 per documentation at http://docs.joinpeertube.org/#/install-any-os?id=upgrade

After restart, I could not find an option in the UI to enable HLS

**What do you expect to happen instead?**
Option some place in the configuration pages of the UI to enable HLS encoding. Most likely spot would be on the "Advanced Configuration" page near the resolution check boxes.

**Steps to reproduce:**

1.

2.

3.

**Additional information**
* PeerTube version or URL: 1.4.1
* Browser name/version: Macintosh Safari 13.0.1
* NodeJS version: v10.16.3
* Server: Ubuntu 18 LTS

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

* Other:
1. No mention of HLS in documentation at http://docs.joinpeertube.org/#/ (might be because this option is listed as experimental in the config YAML comments).

2. No mention of HLS or how to set it up in FAQ.md

I assume this is an operator error as I see others have been able to enable HLS, but am a loss to figure out what I've done wrong.

**Comment by JohnXLivingston** [comment]
For now you have to enable it by modifying the config file.

**Comment by n76** [comment]
Did that (edited both config/default.yaml and config/production.yaml with a restart of ngnix and peertube after). Since the current configuration actually seems to be in config/local-production.json thought some indication of that would show up there but it hasn't.

So the only way to see if it is working is to upload a new video? And once I do that what should I look for to see if it is working?

**Comment by JohnXLivingston** [comment]
Yes, you have to upload a new video. You can find HLS files in this directory after transcoding: /var/www/peertube/storage/streaming-playlists/hls/

**Comment by n76** [comment]
Apparently I've done something wrong. A new video upload leaves that directory empty.

My default.yaml has:
```
file
  allow_audio_files: true
  threads: 1
  resolutions: # Only created if the original video has a higher resolution, uses more storage!
    240p: false
    360p: false
    480p: false
    720p: false
    1080p: false
    2160p: false
  # /!\ EXPERIMENTAL /!\
  # /!\ Requires ffmpeg >= 4
  # Generate HLS playlists and fragmented MP4 files. Better playback than with WebTorrent:
  #     * Resolution change is smoother
  #     * Faster playback in particular with long videos
  #     * More stable playback (less bugs/infinite loading)
  # /!\ Multiplies videos storage by 2 /!\
  hls:
    enabled: true

```

My production.yam has:
```
file
  allow_audio_files: true
  threads: 1
  resolutions: # Only created if the original video has a higher resolution, uses more storage!
    240p: false
    360p: false
    480p: false
    720p: false
    1080p: false
    2160p: false
  # /!\ EXPERIMENTAL /!\
  # /!\ Requires ffmpeg >= 4
  # Generate HLS playlists and fragmented MP4 files. Better playback than with WebTorrent:
  #     * Resolution change is smoother
  #     * Faster playback in particular with long videos
  #     * More stable playback (less bugs/infinite loading)
  # /!\ Multiplies videos storage by 2 /!\
  hls:
    enabled: true

```
There is no hint of hls in my local-production.json

I am currently running a v4.2.1 of ffmpeg:
```
root@localhost:/var/www/peertube/config# which ffmpeg 
/usr/bin/ffmpeg
root@localhost:/var/www/peertube/config# ffmpeg -version
ffmpeg version 4.2.1-0york0~18.04 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
configuration: --prefix=/usr --extra-version='0york0~18.04' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-nonfree --enable-libfdk-aac --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
root@localhost:/var/www/peertube/config# 

```
Suggested debugging steps?

**Comment by Chocobozzz** [comment]
@n76 Please provide the URL of your instance

**Comment by n76** [comment]
https://video.fitchfamily.org

**Comment by Chocobozzz** [comment]
[This video](https://video.fitchfamily.org/videos/watch/d5f5b77b-55ac-47b3-ad69-c6ecec7c4828) uses HLS, so maybe you don't look into the right directory?

**Comment by n76** [comment]
Pretty sure I looked at /var/www/peertube/storage/streaming-playlists/hls/ before. But you are correct, there are fragment mp4 and m3u8 files there now.
