### ISSUE TITLE
/dist/server/tools/ missing ?

### ISSUE THREAD

**Issue by ddeenniiss** [Chocobozzz/PeerTube#2152]
The directory /var/www/peertube/versions/peertube-v1.3.1/dist/server/tools which contains the import scripts is no longer present in version 1.4.x
```

ls /var/www/peertube/versions/peertube-v1.4.1/dist/server/
controllers  helpers  initializers  lib  middlewares  models  static  tests  typings
```

**Comment by Chocobozzz** [comment]
Yes, you need to run `npm run setup:cli` to install tools scripts

See https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#installation
