### ISSUE TITLE
Unable to start peertube service

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#2156]
**What happened?**
Since the last time i powered on my server, peertube service refuses to start.
**What do you expect to happen instead?**
Peertube service start
**Steps to reproduce:**

1.Power on the server

2. Type «systemctl start peertube» or «service peertube start»

**Additional information**
* PeerTube version or URL: peertube.stemy.me
* NodeJS version: 8.16.1
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): https://stemy.me/zerobin/?7f96eb35dd752a2c#uEaG6IukI+YkLTCLXNI+Qu2ySKvB9W7RDE7mPw/YFig=

**Comment by maxdrash** [comment]
Please, upgrade your peertube to the latest version with the upgrade script.
Take care to upgrade your NodeJS to 10.

**Comment by stemy2** [comment]
I can't upgrade nodejs, it says «nodejs is already the newest version (8.16.1-1nodesource1)».

**Comment by tcitworld** [comment]
If you are using a Debian-like distro, you need to upgrade the apt repo.
See https://github.com/nodesource/distributions/blob/master/README.md#deb

**Comment by stemy2** [comment]
Upgraded nodejs to v.12. Nothing changed.

**Comment by robinkooli** [comment]
Node.js 10 is supported, not 12.

**Comment by stemy2** [comment]
I downgraded it to the v.10. Still no changes.

**Comment by Findus23** [comment]
Keep in mind that you have to run yarn install after you are running the right node version as during the install process prebuilt binaries are fetched that only work with that specific node version

**Comment by stemy2** [comment]
Launched command yarn install. Still no changes.

Actually, i'm on yunohost and the newest version of peertube is 1.3.1

**Comment by JohnXLivingston** [comment]
For yunohost support, try here: https://github.com/YunoHost-Apps/peertube_ynh/issues
