### ISSUE TITLE
Tag capitalization should be ignored

### ISSUE THREAD

**Issue by n76** [Chocobozzz/PeerTube#2159]
**What happened?**
Click on tag on a video to see other videos with the same tag. Tags with alternate capitalization were not shown. For example if the tag clicked on is "california" then videos with the tag "California" are not shown.

**What do you expect to happen instead?**
All videos should be shown.

**Steps to reproduce:**

1. Set a tag on a video. Set same tag on another video but with different capitalization.

2. Select one video and click on the tag to find other videos.

3. Video with alternate capitalization is not shown.

**Additional information**
* PeerTube version or URL: 1.4.1
* Browser name/version: Mac Safari 13.0.1
* NodeJS version: 10.16.3

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by DanielHeath** [comment]
Not just capitalization - normalization in general (eg: for latin-derived-language servers, ascii-folding is needed for the same reason; also spaces vs dashes vs underscores in tag names).

**Comment by kevATin** [comment]
Possibly slightly off topic, but
Pixiv supports tag translation; you can search for a tag in latin characters or kanji and it usually gives the same results. I haven't looked into how they do it (automated, paid translators, crowd-sourced, etc) but I'm sure this would be useful for PeerTube too.

**Comment by Chocobozzz** [comment]
Already implemented in https://github.com/Chocobozzz/PeerTube/commit/4b1f1b810a50829be8d8998cdd4d296143e34f2e (will be included in next peertube release).

Regarding tags normalization, see https://github.com/Chocobozzz/PeerTube/issues/352
