### ISSUE TITLE
use the web share api

### ISSUE THREAD

**Issue by Poopooracoocoo** [Chocobozzz/PeerTube#2160]
**What happened?**

**What do you expect to happen instead?**

**Steps to reproduce:**

1.

2.

3.

**Additional information**
* PeerTube version or URL:
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by rigelk** [comment]
Since this is still an unofficial w3c standard and its support is low (only Safari as reported in  https://caniuse.com/#search=web%20share ), I don't think it is worth the implementation. We should consider it later, once the situation has evolved.

**Comment by Poopooracoocoo** [comment]
@rigelk but Chrome for Android is a lot of market share. Also, Microsoft Edge Spartan and Anaheim both support the Web Share API (which may be miniscule but if it lands in Chromium that would be a lot more too).

**Comment by Booteille** [comment]
I think it's better to follow standards and not just what Chrome does.

**Comment by Poopooracoocoo** [comment]
I believe the web share API is a standard but there's only a draft I think. Google drives standards tbh
