### ISSUE TITLE
Recommendations: 

### ISSUE THREAD

**Issue by chopin2712** [Chocobozzz/PeerTube#2162]
Hello!

This is some recommendations about your platform I dream to have : )

First of all keeping in cookies the mastodon link. Yes because when I browse an instance I need to always COPY, PASTE my Mastodon profile into this instance. I don't want to create an account on the instance because I browse multiple instances at the same time.

Then I don't understand how instances are following others, is there any instances that follows every other instances on the network? It could be very enjoyable, because for me the main advantage of Peertube is to be able to have the simplicity of YouTube to find videos at the same place even if they are not in reality. I already posted an issue about this topic and you answered me that instances are following what they want to follow. 

Finally this is a very big point that I don't really need but what would be very cool: Live. I don't have any ideas on how does it works but anyway, let's dreaming.

Hope that you will care about my recommendations, leave me yours and react : )

Have  a nice day!

Chopin42

**Comment by bolikahult** [comment]
Hello !
For the first and second "dream" :) , I suggest you to create separates issues. The third exist already here : [https://github.com/Chocobozzz/PeerTube/issues/151](url)

**Comment by chopin2712** [comment]
> Hello !
> For the first and second "dream" :) , I suggest you to create separates issues. The third exist already here : [https://github.com/Chocobozzz/PeerTube/issues/151](url)

I've done it ! #2164 #2163 thanks for the recommendation!

**Comment by chopin2712** [comment]
#2164
