### ISSUE TITLE
Is there instances that follows every other instances

### ISSUE THREAD

**Issue by chopin2712** [Chocobozzz/PeerTube#2163]
Hello!

Few months ago I posted an issue about an instance who can't follow other instances so this is my question: can we have instances that follows every other Peertube instances not only the "majority" but all? Is there a setting?

I don't know lots about instance creation so excuse me if this topic is stupid but I talk as a normal user, not an admin.

Thanks to care about this issue

Bye

PS: I've already tried to create an instance but never succeed, if you can help me on this topic too it is very nice : )

**Comment by Nutomic** [comment]
> can we have instances that follows every other Peertube instances not only the "majority" but all? Is there a setting?

It is possible, but then you as admin will have a lot of problems with piracy, untagged porn, fascism and so on.

You could try my setup with ansible + docker, it should be pretty easy if you know bash.

https://gitlab.com/Nutomic/peertube-compose/

**Comment by chopin2712** [comment]
> > can we have instances that follows every other Peertube instances not only the "majority" but all? Is there a setting?
> 
> It is possible, but then you as admin will have a lot of problems with piracy, untagged porn, fascism and so on.
> 
> You could try my setup with ansible + docker, it should be pretty easy if you know bash.
> 
> https://gitlab.com/Nutomic/peertube-compose/

Ok, I am on your GitLab and tring to install yours. I just don' t understand the "configure the hosts you want to work with." What is it ? Is it the list of instances I follow ?

Also I think about the untagged porn, fascism and so on. Why not having lists on Peertube of approved instances to create ours? It could be good because if I create my instances others will not be able to watch content from it, so creating an instance becoms harder than ever because peoples will need to watch your videos from your instances until it becomes as popular to be added on popular instances following list.

**Comment by Findus23** [comment]
@chopin2712 Are you aware of https://instances.joinpeertube.org and the auto-follow feature introduced in #406/#2107?

> What is it ? Is it the list of instances I follow ?

I think it is the list of servers you want to install peertube on (as it is using ansible to automatically do so).

A centralized "approved instances" list goes a bit against the spirit of decentralization (and will cause endless fights and discussions as everyone naturally has a bit different definition of what is acceptable). Instead, everyone can decide this for themself and only follow these instances.

> until it becomes as popular to be added on popular instances following list.

Your instance doesn't really need to be popular for others to follow it. My instance has less than 50 views total (so not popular), but over 50 following instances.

**Comment by chopin2712** [comment]
> @chopin2712 Are you aware of https://instances.joinpeertube.org and the auto-follow feature introduced in #406/#2107?
> 
> > What is it ? Is it the list of instances I follow ?
> 
> I think it is the list of servers you want to install peertube on (as it is using ansible to automatically do so).
> 
> A centralized "approved instances" list goes a bit against the spirit of decentralization (and will cause endless fights and discussions as everyone naturally has a bit different definition of what is acceptable). Instead, everyone can decide this for themself and only follow these instances.
> 
> > until it becomes as popular to be added on popular instances following list.
> 
> Your instance doesn't really need to be popular for others to follow it. My instance has less than 50 views total (so not popular), but over 50 following instances.

Thanks for your answer.
I already thought about the problem of the instance list but I mean with that to create a collaborative list of instances. Like that new beginner instances will be able to create instances by taking a new list that they agree with that. 

This could be like a "forum" or something to discuss about channels. So the list would be created by communities themselves. Or maybe a new tab in "about" to add new instances and vote propositions of others like Reddit. It could also make discovering new instances!

What do you think? 

PS: I never heard about this "auto-follow" feature it sounds interesting but I don't really understand how it works.

**Comment by Findus23** [comment]
I think the only way this might work without too many discussions is if you make it obvious that the list is opinionated and instead make a curated list of which instances you personally recommend (maybe grouped by topic) kind of like the trunk site (https://communitywiki.org/trunk).

**Comment by chopin2712** [comment]
@Findus23 This is not really what I am talking about. Because here it works only in English with request. But I am talking about an built in feature to submit instances like reddit.

So could have a tab in "About" to give the instance URL and it displays the list of instances submitted so the admin could accept or reject the follow request.

**Comment by Chocobozzz** [comment]
Hi,

It's out of scope to include this feature in PeerTube core. But it's interesting, so we could build these kind of lists on the [official forum](https://framacolibri.org/c/peertube) or another website and referencing it in the [documentation website](https://docs.joinpeertube.org/#/admin-following-instances)
