### ISSUE TITLE
Cookies to remember the Mastodon account

### ISSUE THREAD

**Issue by chopin2712** [Chocobozzz/PeerTube#2164]
Hi

I had lost my Peertube instance account and don't wanted to get the password back so I connected myself with Mastodon to subscribe to a nice channel. Every thing worked excepted that I was surprised that the "subscribed" state was not displayed to replace the subscribe button. So I supposed that Peertube was not using Cookies for this...

Then I wanted to post a comment, and the same thing again, let's copy and paste the id. I was browsing the different channels and videos and this is very annoying to copy and paste every time I wanted to subscribe or post a comment.

It would be  a good idea to remember the Mastodon account in a next upgrade of Peertube.

Thanks for reading this issue, if anybody with more skills than me to create web app could create a pull request it would be kind from you : ) I will like it.

Have  a nice day!

Chopin42

**Comment by rigelk** [comment]
Just to be sure, the "subscribe"/"subscribed" button that you are talking about is in the interface of the PeerTube video you watch, right? You are not talking about the same button in your Mastodon interface?
