### ISSUE TITLE
HELP NEEDED: Creating a Peertube instance is damn complex ! 

### ISSUE THREAD

**Issue by chopin2712** [Chocobozzz/PeerTube#2168]
Hey!

I love Peertube and I wanted to create a new Peertube instance because of CHALLENGE. So I started to get documentation and more. And according at who I am I know that I can't install Peertube on my local computer (I broke it 5 times). I've also tried using YunoHost but you need a domain name and I don't have one.

So the only remaining option was docker. But I don't really understand the docker instructions about PostgreSQL for example. 

Also I followed the docker instructions but I don't get the point. I got this error and I don't know how to solve it. The error occurs when I want to run the server for the same time with docker-compose up:
I got this output:

```
Creating network "peertube_default" with the default driver
ERROR: Pool overlaps with other one on this address space
```

This topic is not really about the error but about the lack of documentation about Peertube. I've not found one tutorial, one forum about errors that peoples have, only the official documentation which is not enough for me. 

I also knows that other peoples who wanted to create a docker instance had the same problem. 

So it is sad that peoples not being able to create their Peertube instance because they don't have enough knowledge. 

It would be very nice to have a Virtual Box image or at least an disk image for Raspberry Pi.

Thanks !

Chopin42 (A beginner Peertube user)

**Comment by 6543** [comment]
> ... but you need a domain name ...
if you dont have a own domain your instance cant be followed by other instances so all the videos you are put on wont be seen by anyone and if you like to just have a own acout you can look at instances that hafe public registration or ask a admin to add you ...

**Comment by chopin2712** [comment]
> > 
> 
> if you dont have a own domain your instance cant be followed by other instances so all the videos you are put on wont be seen by anyone!!

Yes but it could seems weird, I just want to do it for fun. I don't want to buy a domain name to do it. I just want to see how it works and how to install it. My goal is not to be followed by other peoples.

Maybe I will create a more "pro" instance later but now I just want to check if I CAN install a Peertube instance.

Is there anyway to do it using public IP address then?

Thanks in advance

Chopin42

**Comment by 6543** [comment]
Hi Chopin42

ok i get it.
1. you can use a DynDNS to let your instance speac to the world ... ([free dynDNS](https://www.ionos.co.uk/digitalguide/server/tools/free-dynamic-dns-providers-an-overview/))

2. just follow the install guid step by step
https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#installation

for me it works (3. times tested on diferent systems at PeerTuber Version 1.4.0)

**Comment by chopin2712** [comment]
@6543 Thanks for your answer but I don't really understand what is dynDNS. I just understand it works using multiple providers but I don't know which one I should choose. 

And does Peertube works on Ubuntu 18.04?

Thanks for your help!

Chopin42

**Comment by 6543** [comment]
# Own Domain:
1. you have a Public IP addres wich **doesn change**  (business interent conection / computer center / ...)
2. you configure your domain / a subdomain (like video.mydomain.com) to you IP address

# DynDNS
1. you have a normal internet conection so IP address changes by day
2. you choose a DynDNS profider (wich one is not importand) witch only task is to point with a domain-name to the public IP adress you have right now

# Home Setup
1. setup a computer with PeerTube
3. make a portforward on your route from:
   - 80 -> <PC IP>:80
   - 443 -> <PC IP>:443

2. use Caddy as reverse proxy (you get ssl with no knowlage :+1: )

**Comment by chopin2712** [comment]
@6543 Thanks you! When installing dependencies (at certbot) using nginx, I got a weird error (can't get you the error code, it says nginx restart failed but I cannot copy the error because I use Virtual Box so I can't copy and paste.). Should I choose :
Either get and install your certificates... 
or
Or, just get a certificate 
on the webpage: https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx

Thanks you for your help

Chopin42

**Comment by 6543** [comment]
You cant get a certificate!
if you dont have a domain / dyndns

You can install a http version or use a self generatet certificate

But lets close this issue and contact me on discord/mail/... (som IM)

**Comment by chopin2712** [comment]
Thanks for your help, my mail is julien.lejoly2712@gmail.com what's yours?

**Comment by 6543** [comment]
> Thanks for your help, my mail is [julien.lejoly2712@gmail.com](mailto:julien.lejoly2712@gmail.com) what's yours?

have send you an email

**Comment by chopin2712** [comment]
ok
