### ISSUE TITLE
peertube-theme-dark: some UI components are not supported and show white on white

### ISSUE THREAD

**Issue by 6543** [Chocobozzz/PeerTube#2169]
* you can not see the text "See all your notifications" at the end of the notification box
 * cant see checkbox-frame of playlists on "Save To .. playlist"

to fix: make color of this objects black

**Comment by 6543** [comment]
created the issue here becaues no reaction on https://framagit.org/framasoft/peertube/official-plugins/issues/1

**Comment by 6543** [comment]
![Bildschirmfoto vom 2019-10-05 um 23 23 48](https://user-images.githubusercontent.com/24977596/66261072-717c7200-e7c7-11e9-9795-1d1f4ea2b3d8.png)

**Comment by 6543** [comment]
![Bildschirmfoto vom 2019-10-05 um 23 26 42](https://user-images.githubusercontent.com/24977596/66261090-bc968500-e7c7-11e9-98b7-bfadafe76b2f.png)

**Comment by therahedwig** [comment]
There's also the playlist er... 'footer' underneath the video which has this issue.

**Comment by alcalyn** [comment]
Also I'd say that all the `<hr>` lines are too contrasted, i.e under video title. It should be darker.

**Comment by Chocobozzz** [comment]
Please create issues directly on https://framagit.org/framasoft/peertube/official-plugins, and don't hesitate to make MR :)
