### ISSUE TITLE
Use nexe to ship prebuild binarys

### ISSUE THREAD

**Issue by 6543** [Chocobozzz/PeerTube#2170]
How hard is it to build a binary out of TypeScript NodeJS Apps?

For JS NodeJS Apps it seems to work quit well.

If we get it to work (me personlay does know to less about NodeJS apps) we could easely distribute PeerTube via Package Managers with this binary too ... and so on

... and we could use framagit's CI to automate builds?  ...

**Comment by rigelk** [comment]
@6543 nexe doesn't show any complex app bundling. I've had more interesting results with https://github.com/zeit/pkg

However there are still a lot of things not working after packaging even just the CLI tools with pkg, especially with aliases and dynamic imports… and frankly, this would just be a lot of work to rewrite all the imports.
