### ISSUE TITLE
Ability to subscribe only to an account or a channel

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#2171]
Skeptikon is an instance dedicated to a specific subject: critical thinking and scientific methodology.

There are some users from other instances we would like to subscribe so we can share their videos on our instance. But these instances are for some of them open to everyone and often not dedicated to the same subject as ours. AFAICT, an instance can only subscribe to another instance (and display **all** of its videos) and there is no way to only subscribe (follow) specific user accounts for that purpose.

That would be a nice feature for us :).

**Comment by chopin2712** [comment]
What do you mean? I don't understand you can subscribe to another channel. I am actually subscribed to "Le chat sceptique" AKA Nathan. But I am not on Skeptikon I am on peertube.fr. I can only subscribe to Nathan and not other peoples on the instance. I don't understand what you mean. What's your instance?

**Comment by Findus23** [comment]
I think what @fflorent is proposing is the following (which I also find interesting).

I maintain my peertube instance video.lw1.at. I try to only follow instances where videos are posted that I personally find interesting. So I don't follow instances with thousands of videos as they would make it hard to see my videos and the ones on the smaller instances I follow in Discover/Trending/Recently Added.
But let's say I find an amazing peertube channel `test` on the large instance `example.com`. I (as in my instance, not as in my user) can't follow `example.com` as that would add thousands of videos I am not interested in to my peertube server. So it would be great if I (my server) could just follow this one user and only their videos are shown on my peertube site.

I don't know enough about ActivityPub to estimate if this is trivial or really complicated and I'm afraid that adding this feature will confuse user about the act of subscribing.

**Comment by fflorent** [comment]
That's exactly what @Findus23 says.

> I don't know enough about ActivityPub to estimate if this is trivial or really complicated and I'm afraid that adding this feature will confuse user about the act of subscribing.

When you say "the user", do you mean "the administrators" or "the video consumers"?

**Comment by JohnXLivingston** [comment]
I think that's a duplicate of: https://github.com/Chocobozzz/PeerTube/issues/1604
(and it is a great idea!)

**Comment by fflorent** [comment]
Indeed, thanks!
