### ISSUE TITLE
Error on yarn install: `The engine "node" is incompatible with this module`

### ISSUE THREAD

**Issue by raym** [Chocobozzz/PeerTube#2172]
Following the steps for manual installation, I got to the ["Install PeerTube"](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#prepare-peertube-directory) step and got a failure on the `yarn install`:
```
/var/www/peertube/peertube-latest$ sudo -H -u peertube yarn install --production --pure-lockfile
yarn install v1.19.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error execa@2.0.3: The engine "node" is incompatible with this module. Expected version "^8.12.0 || >=9.7.0". Got "8.10.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

PeerTube version `1.4.1` was downloaded via the previous steps
```
/var/www/peertube/peertube-latest$ ls ..
peertube-v1.4.1
```

```
$ node -v
v10.16.3
```

**Comment by raym** [comment]
I feel silly.

I was using `nodenv` to manage versions, and since I'm not used to thinking about production, I forgot that it's encouraged to just install the desired node version at the system level for a production instance.

All it took was an upgrade to node 10 (from node `8.10.0`), as follows:

```
$ curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
$ sudo apt-get install -y nodejs
$ node -v
v10.16.3
```

**Comment by lavanyascyberlife** [comment]
i had same issue when i was adding router plugin to vue-cli with npx and yarn as well.. In pyhton virtual environment i have updated node version from 8.x.x to 16.x.x and used command nvm use 16.x.x but still problem persists .. i was actually executing command as root .. so nvm is using node version as 8.x.x only ..

after long time i realised executing command with sudo was the issue and then executed as a normal user...

this solution worked for me !!!
