### ISSUE TITLE
PeerTube issue when running on Docker

### ISSUE THREAD

**Issue by xaoseric** [Chocobozzz/PeerTube#2173]
**What happened?**
When running in docker, there is a sequalize error

**What do you expect to happen instead?**
run in docker and try to use a postgres docker 

**Steps to reproduce:**
1. Run with docker-compose up

**Additional information**
* PeerTube version or URL:
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
https://gist.github.com/xaoseric/fbbe6914bf5af30819a21f66e17b7f86

**Comment by Chocobozzz** [comment]
Did you follow https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/docker.md#production?

**Comment by xaoseric** [comment]
Yes, I followed it. However, the instructions are incorrect for it. Traefik configuration is incorrect as it now uses 2.0 by default (https://hub.docker.com/_/traefik), needed to specify traefik:v1.7. Additionally for postgresql, I needed to edit copy default.yaml `/data/peertube/config/default.yaml` to `/data/peertube/config/production.yaml` and tell it to use `_prod` for the suffix. Also I seem to be getting a bad gateway or 404. I am going to play around with seeing if i can get an nginx letsencrypt solution working.

**Comment by Nutomic** [comment]
You could try my setup for docker-compose + ansible.

https://gitlab.com/Nutomic/peertube-compose/

**Comment by Chocobozzz** [comment]
> Additionally for postgresql, I needed to edit copy /data/peertube/config/default.yaml to /data/peertube/config/production.yaml and tell it to use _prod for the suffix.

You should not have to do that. PeerTube automatically copy the appropriate configuration file at startup: https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/docker-entrypoint.sh#L6

Please paste your `docker-compose.yml` and your `docker-volume/config/production.yaml` files

**Comment by claudehohl** [comment]
I tried to run the docker-compose as outlined in https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/docker.md - and I get this error:

>  reverse-proxy_1  | 2019/10/28 18:20:22 command traefik error: flag needs an argument: -docker

**Comment by Chocobozzz** [comment]
Please download again the docker compose file. We updated it in https://github.com/Chocobozzz/PeerTube/commit/f1b38883922fd59b36f093e44a5091e090d20862
