### ISSUE TITLE
Stay logged option

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#2174]
Hello,

It seems impossible to stay connected when changing page. There's no such option on the login page and no «stay logged» cookie seems to exist. Could you add one ?

**Comment by Chocobozzz** [comment]
PeerTube remembers your login when you change pages. Check your console and server logs.

**Comment by stemy2** [comment]
Okay, it's right. Actually, it disconnect me when i close its tab, unlike many other sites.

**Comment by Chocobozzz** [comment]
What is your cookie policy? Please try with another web browser to see if it's related to your browser configuration/extensions

**Comment by stemy2** [comment]
All my cookies are enabled for my peertube instance. The connection stay if i load another page in the same tab, but is vanished if i close the said tab.

**Comment by Chocobozzz** [comment]
> The connection stay if i load another page in the same tab, but is vanished if i close the said tab.

It seems caused by an autodelete extension. Did you test with another web browser?

**Comment by stemy2** [comment]
I don't have autodelete extention, and it happens with any browser.

**Comment by Chocobozzz** [comment]
What is your instance URL?

**Comment by stemy2** [comment]
The problem seems to be solved, maybe by the last upgrade.
