### ISSUE TITLE
Videos uploaded with YUV444 pixel format retain that format, causing compatibility issues

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#2175]
**What happened?**

I uploaded a few videos that were recorded using ffmpeg in its yuv444p format. These play fine in VLC but Firefox doesn't seem to natively support them, and playing them in Chrome seems jittery.

**What do you expect to happen instead?**

I expect PeerTube's transcode to force the pixel format to yuv420p for compatibility.

**Steps to reproduce:**

1. Sample videos:

https://diode.zone/videos/watch/b5cb91f2-e981-40fe-b997-76377bdaf521

https://diode.zone/videos/watch/e7556ae0-2fc6-407c-8980-24aa886e1208

https://diode.zone/videos/watch/87c5f086-a760-4373-a812-60edfac18d09

**Additional information**
* PeerTube version or URL: diode.zone
* Browser name/version: Firefox 69.0.2
* NodeJS version: 10.16.3

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/f6e0de3f48993b2c0ef9bd2c24d2d7443acc6ace
