### ISSUE TITLE
Brave Browser

### ISSUE THREAD

**Issue by ReK2Fernandez** [Chocobozzz/PeerTube#218]
Hello, just wondering, any plans on supporting the Brave browser? most of us in my community are switching from firefox to brave and just wondering if there is plans, or if this is something brave browser needs  to fix/support? thanks

**Comment by Chocobozzz** [comment]
I think it's a Brave issue: https://github.com/brave/browser-laptop/issues/10672

**Comment by avenirperma** [comment]
up up windows 8.1
i saw one issue that was closed elsewhere about that, but it isn't solved for me!

**Comment by rigelk** [comment]
@avenirperma then document your case in the upstream issue in Brave's tracker.
