### ISSUE TITLE
GItpod is not working

### ISSUE THREAD

**Issue by Knackie** [Chocobozzz/PeerTube#2181]
**What happened?**

i can't use gitpod, when it's build, i've some problems
![image](https://user-images.githubusercontent.com/43431712/67044829-6a415680-f12d-11e9-9a00-c05559a5a402.png)

**Comment by Chocobozzz** [comment]
Sorry for the late. It's fixed by https://github.com/Chocobozzz/PeerTube/commit/44daca1f4108e72b49281fb232be006c11ffab3a
