### ISSUE TITLE
Inaccurate timezone

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#2182]
**What happened?**
The app timezone is not the same as the server's timezone, a job began at 10:35 PM, but the app says it began at 8:35 PM.
**Additional information**
* PeerTube version or URL: 1.4.1
* Browser name/version: Firefox 68
* NodeJS version: 10

**Comment by Chocobozzz** [comment]
The app timezone is the one defined in your web browser.

**Comment by stemy2** [comment]
I don't understand. I never had to define any timezone in my web browser, and i didn't fount any config point that remotely looks like that. The timezone is correctly set on my Local PC and my server.

**Comment by Chocobozzz** [comment]
Please paste the server request response when you are in the admin panel, in the job tab, of the problematic job (using the network developer tool).
