### ISSUE TITLE
Use "allow-same-origin" in embed code ?

### ISSUE THREAD

**Issue by brouillon** [Chocobozzz/PeerTube#2183]
Hello,

Thank for this software, I just want to know why the "sandbox" attribute contains "allow-same-origin" in embed snippet ? Is there a technical reason ?
```<iframe width="560" height="315" sandbox="allow-same-origin allow-scripts" src="https://peertube.eric.ovh/videos/embed/9c9de5e8-0a1e-484a-b099-e80766180a6d" frameborder="0" allowfullscreen></iframe>```

Thank

**Comment by rigelk** [comment]
Hi @brouillon - the use of `allow-same-origin` for the embed's `sandbox` attribute value essentially boils down to allowing the embed to access the browser's IndexedDB, which the PeerTube player uses to store video chunks.
