### ISSUE TITLE
docker image production-stretch is out of date

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#2184]
Docker image production-stretch is out of date here: https://hub.docker.com/layers/chocobozzz/peertube/production-stretch/images/sha256-89a6e795442f0ea7c9848bf00dd3bcd72d529b9cb51bb7c238676f33d79a5e0d

Version 1.4.1 has been released. Would you mind updating this reference? Thanks :).

**Comment by Chocobozzz** [comment]
Sorry for the late, it's done. And it should be built automatically with https://github.com/Chocobozzz/PeerTube/commit/2e2c02b4f1882e79cf4145d8de4c9cde584eed7d
