### ISSUE TITLE
Traefik v2 has been released and breaks docker-compose

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#2185]
Traefik has released version 2.0 and breaks our current docker-compose.yml.

If one pulls the docker images, the reverse proxy doesn't work (error: `2019/10/18 06:26:50 command traefik error: flag needs an argument: -docker`).

Sorry, I am a bit in a hurry. Don't hesitate to ask for clarification!

**Comment by gmeks** [comment]
I can confirm

**Comment by Chocobozzz** [comment]
Thanks, it's fixed by https://github.com/Chocobozzz/PeerTube/commit/f1b38883922fd59b36f093e44a5091e090d20862
