### ISSUE TITLE
Search filter bug with language preferences

### ISSUE THREAD

**Issue by popindavibe** [Chocobozzz/PeerTube#2186]
**What happened?**
When I am signed in, my language preferences are enforced when searching videos, and the filter bar shows `1` filter active. 
For unknown reason, this gives me 0 results (testing with _facebook_ search, which I checked, does have videos marked with my language preferences). 
If I select blank in the `Language` search filter and search again, this removes all filters and I am getting appropriate search results.

Incidentally, if I run another search again, my language preferences filter comes back and again no results. This is not a bug or an issue as such, but it may be nice to keep you last search filter somewhere in cache with a way to quickly reset the search filters than resetting on every new search.

**What do you expect to happen instead?**
It's good that the language preference is used for search, but it should give actual results.

**Steps to reproduce:**

1. Sign in with a user and set language preferences to 2 or more languages

2. Do a search on _facebook_, get `no results`
ex: `https://peertube.nomagic.uk/search?search=facebook&languageOneOf=fr&languageOneOf=en`

3. Expand the search filters and select 'Blank' or 'English' for language and search again: you get results
ex: `https://peertube.nomagic.uk/search?search=facebook&languageOneOf=en`

**Additional information**
* PeerTube version or URL: 
version 1.4.1
https://peertube.nomagic.uk
* Browser name/version:  Firefox
* NodeJS version: 10

- Raised first in Matrix official Peertube support room: https://riot.im/app/#/room/!BZXSzdvTmoFEHBAvBq:matrix.org/$15713899153OWlvV:matrix.nomagic.uk
- I could reproduce this on another instance

**Comment by Chocobozzz** [comment]
Thanks for the issue. It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/baeb429d06d101f69c677fdb70c3da2eb9d3823d
