### ISSUE TITLE
Buffering brutally interrupted

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#2187]
**What happened?**
I was watching a local video, when buffering suddenly stopped, so did the video. The download speed and the number of peers fell unexplicably to 0.
**What do you expect to happen instead?**
Being able to watch it to the end.
**Steps to reproduce:**

1. Play a local video.

**Additional information**
* PeerTube version or URL: 1.4.1
* Browser name/version: Firefox 68
* NodeJS version: 10.16.3

**Comment by Chocobozzz** [comment]
Please provide console logs, server logs and a link to the problematic video.

**Comment by tomdereub** [comment]
Hi!
I would like to re-open this issue as I have the exactly same problem. When I play local videos, buffering often stops at some point. If I reload the page or change quality, the buffering starts again and I can then watch the video until the end.
Here is one local problematic video : https://tube.plaf.fr/videos/watch/aa3569d5-27bd-44e9-a7ad-04ad1bbb79a2

I could reproduce it on various computers using firefox (I didn't try other web browsers).
Here are browser console logs : https://plaf.fr/zerobin/?30a9528511a044da#ESRkrhqA97yZJqMnaGffzQMREE4wYiciTKZvBAB1ExcY
In the server logs, I don't find errors about it, just lines like that : https://plaf.fr/zerobin/?74e4129605a18dd5#2A13xJkY1GSGEsg23ME7UdsBQLhj4NdGSyovv92HQNa1

Instance infos : 
    PeerTube version : 2.1.1 on yunohost 3.7
    Browser name/version: Firefox 75

Thanks !

**Comment by Chocobozzz** [comment]
@tomdereub Hello, we have known issues with our webtorrent player. Try to enable HLS in the admin and reupload the video.

**Comment by tomdereub** [comment]
Ok, I'll try that.
One question about HLS, if it's not using webtorrent, it means that only the server is streaming the videos ?
Thanks for your rapid answer !

**Comment by Chocobozzz** [comment]
> One question about HLS, if it's not using webtorrent, it means that only the server is streaming the videos

No, like with webtorrent we use P2P and redundancy. We just not use the webtorrent protocol to send the segments to other web browsers.

**Comment by tomdereub** [comment]
Ok cool ! So if HLS is better, is webtorrent to be progressively abandoned ? Is there an interest to keep it active on the server ? It seems that it's useful only to keep federation with older instances ?
