### ISSUE TITLE
French version of Zanata set on read only - XML code appears in sign up procedure in french language

### ISSUE THREAD

**Issue by AlphaShadows77** [Chocobozzz/PeerTube#2192]
**What happened?**
There is `<x id="LINE_BREAK" ctype="lb" equiv-text="<br/>"/>"` that appears in a visible text at the **2nd step** of the **register** procedure. It only appears in **french language**

**Steps to reproduce:**

1. **Change the language to french** with the button at the button left.

2. Click on the button "Créer un compte" and follow the procedure until the 2nd step

**--Edit--**
    I can't change it by myself because of the read only mode of the french version of Zanata
**--Edit--**

**Additional information**
* PeerTube version or URL: v1.4.0, v1.4.1
* Useragent: Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0

**Tested servers**
[Iriseden](https://peertube.iriseden.eu/signup)
[Libre.Video](https://libre.video/signup)
[AnjaraTube](https://tube.anjara.eu/signup)

**Images**
[French language - 1st server](https://prnt.sc/pmcocb)
[Spanish language - 2nd sever](https://prnt.sc/pmcpr2)
[English language - 3rd server](https://prnt.sc/pmcpyk)

**Comment by Chocobozzz** [comment]
Thanks, I fixed it in zanata and pulled the translation again: https://github.com/Chocobozzz/PeerTube/commit/009d581e2df3ea865c052f69001a33876c3fd945
