### ISSUE TITLE
No translation for the 2nd paragraph of the 2nd step of the sign up procedure

### ISSUE THREAD

**Issue by AlphaShadows77** [Chocobozzz/PeerTube#2195]
**What happened?**
The 2nd paragraph of the 2nd step of the sign up procedure is not translated in any other language than english.

**Steps to reproduce:**

1. Choose a language other than english like french.

2. Follow the sign up procedure until the 2nd step

3. See that the 2nd paragraph is not translated: http://prnt.sc/pmdsil

**Possible ways to solve**
Found why there is no "section" for this paragraph in any `client/src/locale/target/angular_**_**.xml`
[Example of a "section" for a paragraph](https://prnt.sc/pmdqa8)

**Additional information**
* PeerTube version or URL: v1.4.1

**Tested servers**
[Iriseden](https://peertube.iriseden.eu)
[Libre.Video](https://libre.video)

**Comment by Findus23** [comment]
I can't see a difference between that sentence and the one before:
https://github.com/Chocobozzz/PeerTube/blob/210709a9076ac152dd377234866b8e9b9108382a/client/src/app/%2Bsignup/%2Bregister/register-step-channel.component.html#L3-L12

**Comment by AlphaShadows77** [comment]
I don't really know how the translation is working but so if the 2 sentence have the same id, the translation is just missing in the language file

**Comment by Chocobozzz** [comment]
I updated the translation and re pushed them on zanata. Now you can translate them :)

**Comment by AlphaShadows77** [comment]
I can't, Zanata is set in read only mode ^^' [!Screenshot](https://tof.cx/image/qn7Dpe)

**Comment by Chocobozzz** [comment]
You need to follow the guide: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/translation.md

Join the correct language team first (`fr-FR` for example).
