### ISSUE TITLE
peertube will not start and cannot be upgraded

### ISSUE THREAD

**Issue by SMJ** [Chocobozzz/PeerTube#2196]
**What happened?**

peertube server will no longer start, cannot be upgraded.

Server reports:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peertube@1.2.1 start: `node dist/server`
npm ERR! Exit status 1

When trying to do an upgrade to 1.4.1:

yarn install v1.9.4
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ test -n "$NOCLIENT" || (cd client && yarn install --pure-lockfile)
yarn install v1.9.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error @angular-devkit/build-angular@0.802.0: The engine "node" is incompatible with this module. Expected version ">= 10.9.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**What do you expect to happen instead?**

The server should start up and should be upgradable

**Steps to reproduce:**

1. Try starting server

2. Try scripts/upgrade.sh

**Additional information**
* PeerTube version or URL:  https://toobnix.org
* Browser name/version: safari 
* NodeJS version:  v8.16.2

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by AlphaShadows77** [comment]
Hey !
> error @angular-devkit/build-angular@0.802.0: The engine "node" is incompatible with this module. Expected version ">= 10.9.0".
I think that you have to update NodeJS to a version upper or equal than 10.9.0 ^^

**Comment by SMJ** [comment]
Thank you, I did this:

  nodejs -v
  v8.16.2
  sudo npm cache clean -f
  sudo npm install -g n
  sudo n stable
  node -v 
  v12.13.0

scripts/upgrade.sh gets along but has this problem:

yarn install v1.9.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 0/1153(node:3713) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > marked-man@0.6.0" has unmet peer dependency "marked@^0.6.2".
[5/5] Building fresh packages...
[-/6] ⠐ waiting...
[-/6] ⠐ waiting...
[-/6] ⠐ waiting...
[4/6] ⠐ rdf-canonize
error /peertube/versions/peertube-v1.4.1/node_modules/rdf-canonize: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /peertube/versions/peertube-v1.4.1/node_modules/rdf-canonize
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.13.0 | linux | x64
gyp info find Python using Python version 2.7.9 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/peertube/versions/peertube-v1.4.1/node_modules/rdf-canonize/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/peertube/.cache/node-gyp/12.13.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/peertube/.cache/node-gyp/12.13.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/peertube/.cache/node-gyp/12.13.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/peertube/versions/peertube-v1.4.1/node_modules/rdf-canonize',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/peertube/versions/peertube-v1.4.1/node_modules/rdf-canonize/build'
  CXX(target) Release/obj.target/urdna2015/lib/native/IdentifierIssuer.o
  CXX(target) Release/obj.target/urdna2015/lib/native/MessageDigest.o
  CXX(target) Release/obj.target/urdna2015/lib/native/NQuads.o
  CXX(target) Release/obj.target/urdna2015/lib/native/addon.o
../lib/native/addon.cc:28:11: error: ‘v8::Handle’ has not been declared
 using v8::Handle;
           ^
../lib/native/addon.cc: In member function ‘virtual void Urdna2015Worker::HandleOKCallback()’:
../lib/native/addon.cc:64:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated (declared at ../../nan/nan.h:1740) [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
../lib/native/addon.cc: At global scope:
../lib/native/addon.cc:74:27: error: ‘Handle’ does not name a type
   Dataset& dataset, const Handle<Array>& datasetArray);
                           ^
../lib/native/addon.cc:74:33: error: expected ‘,’ or ‘...’ before ‘<’ token
   Dataset& dataset, const Handle<Array>& datasetArray);
                                 ^
../lib/native/addon.cc:77:9: error: ‘Handle’ does not name a type
   const Handle<Object>& object,
         ^
../lib/native/addon.cc:77:15: error: expected ‘,’ or ‘...’ before ‘<’ token
   const Handle<Object>& object,
               ^
../lib/native/addon.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Main(Nan::NAN_METHOD_ARGS_TYPE)’:
../lib/native/addon.cc:96:3: error: ‘Handle’ was not declared in this scope
   Handle<Object> object = Handle<Object>::Cast(info[0]);
   ^
../lib/native/addon.cc:96:16: error: expected primary-expression before ‘>’ token
   Handle<Object> object = Handle<Object>::Cast(info[0]);
                ^
../lib/native/addon.cc:96:18: error: ‘object’ was not declared in this scope
   Handle<Object> object = Handle<Object>::Cast(info[0]);
                  ^
../lib/native/addon.cc:96:40: error: expected primary-expression before ‘>’ token
   Handle<Object> object = Handle<Object>::Cast(info[0]);
                                        ^
../lib/native/addon.cc:96:41: error: ‘::Cast’ has not been declared
   Handle<Object> object = Handle<Object>::Cast(info[0]);
                                         ^
../lib/native/addon.cc:103:15: error: expected primary-expression before ‘>’ token
   Handle<Array> datasetArray =
               ^
../lib/native/addon.cc:103:17: error: ‘datasetArray’ was not declared in this scope
   Handle<Array> datasetArray =
                 ^
../lib/native/addon.cc:104:17: error: expected primary-expression before ‘>’ token
     Handle<Array>::Cast(object->Get(New("dataset").ToLocalChecked()));
                 ^
../lib/native/addon.cc:104:18: error: ‘::Cast’ has not been declared
     Handle<Array>::Cast(object->Get(New("dataset").ToLocalChecked()));
                  ^
../lib/native/addon.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE MainSync(Nan::NAN_METHOD_ARGS_TYPE)’:
../lib/native/addon.cc:133:3: error: ‘Handle’ was not declared in this scope
   Handle<Object> object = Handle<Object>::Cast(info[0]);
   ^
../lib/native/addon.cc:133:16: error: expected primary-expression before ‘>’ token
   Handle<Object> object = Handle<Object>::Cast(info[0]);
                ^
../lib/native/addon.cc:133:18: error: ‘object’ was not declared in this scope
   Handle<Object> object = Handle<Object>::Cast(info[0]);
                  ^
../lib/native/addon.cc:133:40: error: expected primary-expression before ‘>’ token
   Handle<Object> object = Handle<Object>::Cast(info[0]);
                                        ^
../lib/native/addon.cc:133:41: error: ‘::Cast’ has not been declared
   Handle<Object> object = Handle<Object>::Cast(info[0]);
                                         ^
../lib/native/addon.cc:140:15: error: expected primary-expression before ‘>’ token
   Handle<Array> datasetArray =
               ^
../lib/native/addon.cc:140:17: error: ‘datasetArray’ was not declared in this scope
   Handle<Array> datasetArray =
                 ^
../lib/native/addon.cc:141:17: error: expected primary-expression before ‘>’ token
     Handle<Array>::Cast(object->Get(New("dataset").ToLocalChecked()));
                 ^
../lib/native/addon.cc:141:18: error: ‘::Cast’ has not been declared
     Handle<Array>::Cast(object->Get(New("dataset").ToLocalChecked()));
                  ^
../lib/native/addon.cc: At global scope:
../lib/native/addon.cc:162:49: error: ‘Handle’ does not name a type
 static bool fillDataset(Dataset& dataset, const Handle<Array>& datasetArray) {
                                                 ^
../lib/native/addon.cc:162:55: error: expected ‘,’ or ‘...’ before ‘<’ token
 static bool fillDataset(Dataset& dataset, const Handle<Array>& datasetArray) {
                                                       ^
../lib/native/addon.cc: In function ‘bool fillDataset(RdfCanonize::Dataset&, int)’:
../lib/native/addon.cc:174:27: error: ‘datasetArray’ was not declared in this scope
   for(size_t di = 0; di < datasetArray->Length(); ++di) {
                           ^
../lib/native/addon.cc:175:5: error: ‘Handle’ was not declared in this scope
     Handle<Object> quad = Handle<Object>::Cast(datasetArray->Get(di));
     ^
../lib/native/addon.cc:175:18: error: expected primary-expression before ‘>’ token
     Handle<Object> quad = Handle<Object>::Cast(datasetArray->Get(di));
                  ^
../lib/native/addon.cc:175:20: error: ‘quad’ was not declared in this scope
     Handle<Object> quad = Handle<Object>::Cast(datasetArray->Get(di));
                    ^
../lib/native/addon.cc:175:40: error: expected primary-expression before ‘>’ token
     Handle<Object> quad = Handle<Object>::Cast(datasetArray->Get(di));
                                        ^
../lib/native/addon.cc:175:41: error: ‘::Cast’ has not been declared
     Handle<Object> quad = Handle<Object>::Cast(datasetArray->Get(di));
                                         ^
../lib/native/addon.cc:179:18: error: expected primary-expression before ‘>’ token
     Handle<Object> subject =
                  ^
../lib/native/addon.cc:179:20: error: ‘subject’ was not declared in this scope
     Handle<Object> subject =
                    ^
../lib/native/addon.cc:180:20: error: expected primary-expression before ‘>’ token
       Handle<Object>::Cast(quad->Get(subjectKey));
                    ^
../lib/native/addon.cc:180:21: error: ‘::Cast’ has not been declared
       Handle<Object>::Cast(quad->Get(subjectKey));
                     ^
../lib/native/addon.cc:181:18: error: expected primary-expression before ‘>’ token
     Handle<Object> predicate =
                  ^
../lib/native/addon.cc:181:20: error: ‘predicate’ was not declared in this scope
     Handle<Object> predicate =
                    ^
../lib/native/addon.cc:182:20: error: expected primary-expression before ‘>’ token
       Handle<Object>::Cast(quad->Get(predicateKey));
                    ^
../lib/native/addon.cc:182:21: error: ‘::Cast’ has not been declared
       Handle<Object>::Cast(quad->Get(predicateKey));
                     ^
../lib/native/addon.cc:183:18: error: expected primary-expression before ‘>’ token
     Handle<Object> object =
                  ^
../lib/native/addon.cc:183:20: error: ‘object’ was not declared in this scope
     Handle<Object> object =
                    ^
../lib/native/addon.cc:184:20: error: expected primary-expression before ‘>’ token
       Handle<Object>::Cast(quad->Get(objectKey));
                    ^
../lib/native/addon.cc:184:21: error: ‘::Cast’ has not been declared
       Handle<Object>::Cast(quad->Get(objectKey));
                     ^
../lib/native/addon.cc:185:18: error: expected primary-expression before ‘>’ token
     Handle<Object> graph =
                  ^
../lib/native/addon.cc:185:20: error: ‘graph’ was not declared in this scope
     Handle<Object> graph =
                    ^
../lib/native/addon.cc:186:20: error: expected primary-expression before ‘>’ token
       Handle<Object>::Cast(quad->Get(graphKey));
                    ^
../lib/native/addon.cc:186:21: error: ‘::Cast’ has not been declared
       Handle<Object>::Cast(quad->Get(graphKey));
                     ^
../lib/native/addon.cc: At global scope:
../lib/native/addon.cc:217:9: error: ‘Handle’ does not name a type
   const Handle<Object>& object,
         ^
../lib/native/addon.cc:217:15: error: expected ‘,’ or ‘...’ before ‘<’ token
   const Handle<Object>& object,
               ^
../lib/native/addon.cc: In function ‘bool createTerm(RdfCanonize::Term*&, int)’:
../lib/native/addon.cc:222:8: error: ‘object’ was not declared in this scope
   if(!(object->Has(termTypeKey) && object->Get(termTypeKey)->IsString())) {
        ^
../lib/native/addon.cc:222:20: error: ‘termTypeKey’ was not declared in this scope
   if(!(object->Has(termTypeKey) && object->Get(termTypeKey)->IsString())) {
                    ^
../lib/native/addon.cc:229:23: error: ‘object’ was not declared in this scope
   Utf8String termType(object->Get(termTypeKey));
                       ^
../lib/native/addon.cc:229:35: error: ‘termTypeKey’ was not declared in this scope
   Utf8String termType(object->Get(termTypeKey));
                                   ^
../lib/native/addon.cc:238:20: error: ‘datatypeKey’ was not declared in this scope
     if(object->Has(datatypeKey)) {
                    ^
../lib/native/addon.cc:239:7: error: ‘Handle’ was not declared in this scope
       Handle<Object> datatype =
       ^
../lib/native/addon.cc:239:20: error: expected primary-expression before ‘>’ token
       Handle<Object> datatype =
                    ^
../lib/native/addon.cc:239:22: error: ‘datatype’ was not declared in this scope
       Handle<Object> datatype =
                      ^
../lib/native/addon.cc:240:22: error: expected primary-expression before ‘>’ token
         Handle<Object>::Cast(object->Get(datatypeKey));
                      ^
../lib/native/addon.cc:240:23: error: ‘::Cast’ has not been declared
         Handle<Object>::Cast(object->Get(datatypeKey));
                       ^
../lib/native/addon.cc:250:22: error: ‘valueKey’ was not declared in this scope
         termTypeKey, valueKey, datatypeKey, languageKey)) {
                      ^
../lib/native/addon.cc:250:45: error: ‘languageKey’ was not declared in this scope
         termTypeKey, valueKey, datatypeKey, languageKey)) {
                                             ^
../lib/native/addon.cc:260:20: error: ‘languageKey’ was not declared in this scope
     if(object->Has(languageKey)) {
                    ^
../lib/native/addon.cc:272:41: error: ‘valueKey’ was not declared in this scope
   term->value = *Utf8String(object->Get(valueKey));
                                         ^
urdna2015.target.mk:119: recipe for target 'Release/obj.target/urdna2015/lib/native/addon.o' failed
make: Leaving directory '/peertube/versions/peertube-v1.4.1/node_modules/rdf-canonize/build'
make: *** [Release/obj.target/urdna2015/lib/native/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 3.16.0-7-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /peertube/versions/peertube-v1.4.1/node_modules/rdf-canonize

**Comment by SMJ** [comment]
and we attempting to start the v1.2.1 server:

NODE_ENV=production npm start

> peertube@1.2.1 start /peertube
> node dist/server

/peertube/dist/server/helpers/custom-jsonld-signature.js:18
jsig.use('jsonld', jsonld);
     ^

TypeError: jsig.use is not a function
    at Object.<anonymous> (/peertube/dist/server/helpers/custom-jsonld-signature.js:18:6)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/peertube/dist/server/helpers/peertube-crypto.js:13:35)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/peertube/dist/server/helpers/activitypub.js:13:27)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/peertube/dist/server/models/activitypub/actor.js:17:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peertube@1.2.1 start: `node dist/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@1.2.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /peertube/.npm/_logs/2019-10-21T20_12_10_232Z-debug.log

**Comment by Nutomic** [comment]
Peertube only supports node 10.x at the moment.

**Comment by SMJ** [comment]
OK, I've installed v10.16.3 in the peertube user's home directory and updated its PATH.  I could not start the old v1.2.1 server, however, I could complete a script/upgrade.sh /peertube this time and started the server after copying the production.yaml config from the v1.2.1 to the peertube-latest/config directory.

I made a new config/production.yaml and put in details from the old v.1.2.1 config

The server is running, and I see some activity after:
[toobnix.org:443] 2019-10-21 21:29:28.154 info: Server listening on localhost:9000
[toobnix.org:443] 2019-10-21 21:29:28.154 info: Web server: https://toobnix.org

I can login, see recent video thumb nails .. all seems to be there, but if I try to play a video it
never starts playing

**Comment by Nutomic** [comment]
Check your nginx logs (assuming you use that), you probably have a path wrong.

**Comment by SMJ** [comment]
after waiting some time the videos are streaming now.
