### ISSUE TITLE
Generating nightly fails on processing angular de-DE

### ISSUE THREAD

**Issue by robinkooli** [Chocobozzz/PeerTube#2200]
**What happened?**
Generating nightly fails on processing angular de-DE.

**What do you expect to happen instead?**
Generating nightly to succeed.

**Steps to reproduce:**

1. Clone latest develop branch
2. yarn install --pure-lockfile
3. Generating nightly fails on processing angular de-DE. (/scripts/nightly.sh)

**Additional information**
* PeerTube version or URL: Github latest develop branch from the time of this post
* Browser name/version: -
* NodeJS version: v10.17.0

* Link to browser console log if useful: -
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): -

**Comment by Chocobozzz** [comment]
Thanks, fixed in https://github.com/Chocobozzz/PeerTube/commit/4e0c3c74d64c996cfb0728f84719fae129f3def0
