### ISSUE TITLE
Migrate to weblate instead of Zanata

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#2201]
Zanata is dead, bugged, and very slow. We are currently testing Weblate with joinpeertube and it works very well. Let's try to use it with PeerTube!

**Comment by bristow** [comment]
If we don't have to translate again, go for it !

**Comment by Chocobozzz** [comment]
Done in https://github.com/Chocobozzz/PeerTube/pull/2239

New translation URL: https://weblate.framasoft.org/projects/peertube
