### ISSUE TITLE
French translation error in «follow» section.

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#2202]
**What happened?**
«Followers» and «following» are wrongfully translated as «abonnés» and «abonné-e-s».
**What do you expect to happen instead?**
«Translated as «abonné-e-s» and «abonnements».

**Additional information**
* PeerTube version or URL: 1.4.1
* Browser name/version: Firefox 68
* NodeJS version: 10.17

**Comment by bristow** [comment]
Thanks for report.

This issue can be closed, it's fixed in PT 2.0 RC1.
You can see here : https://peertube3.cpy.re/about/follows

**Comment by Chocobozzz** [comment]
Thanks @bristow
