### ISSUE TITLE
How do you Install it? No Click to Install for Mac

### ISSUE THREAD

**Issue by XenoXeno** [Chocobozzz/PeerTube#2203]
**What happened?**

No clear and simple install directions for non-coders. Downloaded latest version, unzipped. I see a folder peertube-v1.4.0. There is no installer. Not link to install directions in the READ.ME file. The downloaded file:///.../peertube-v1.4.0/client/dist/en_US/index.html is just a blank page. I watched the video about how it works but there was no install direction. Looked at some command line options on https://docs.joinpeertube.org/#/install-any-os?id=installation but nothing seemed to apply to the files I downloaded. Gave up.

**What do you expect to happen instead?**

If anyone wants PeerTube to be a YouTube alternative, make it simple to install. 

**Steps to reproduce:**

1. Download latest version.

2. Unzip latest version.

3. Be puzzled about how to install. 

**Additional information**
* PeerTube version or URL:
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Findus23** [comment]
Installing peertube on a non-server (so a computer that isn't online 24/7) isn't that useful as federation doesn't work if other instances can't reach you.

If you are using Mac OS on the server the instructions from https://docs.joinpeertube.org/#/install-any-os?id=installation should work. You don't need to download peertube for this as this is the second step in the `Prepare PeerTube directory` section anyway.

If you don't know how to install ffmpeg, nodeJS, and yarn or configure PostgreSQL and redis, you can either use the docker container, or try to find a beginner-friendly guide on how to get familier with them.

**Comment by XenoXeno** [comment]
Got it. Thanks. Sounds like PeerTube is only for use by people who run their own server that is online 24/7 especially for those with good fast connections.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Chocobozzz** [comment]
Yep. And non coders can try [yunohost](https://yunohost.org/#/)
