### ISSUE TITLE
Subtitles Blank selection box onchanging to another language

### ISSUE THREAD

**Issue by george110765** [Chocobozzz/PeerTube#2204]
**What happened?**

**What do you expect to happen instead?**

**Steps to reproduce:**

1.

2.

3.

**Additional information**
* PeerTube version or URL:
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by george110765** [comment]
Subtitle selection box is blank i.e. no text visiable as in this previous bug  https://github.com/Chocobozzz/PeerTube/issues/860

we should see 3 or four languages or more available to choose from

this occurs when after selecting one lanaguage we go back and select a different language
First time round works fine but if we selected wrong language or wished to change to a different lanaguage on opening subtitle menu second time selection box is blank.

our url : https://tube.rebellion.global/
chrome Version 76.0.3809.100 (Official Build) Built on Ubuntu , running on LinuxMint 18.1 (64-bit)

This is easily reproduceable and gives same effect of empty subttile selection box every time it is reopened. First selection works but further selection will not display subtitles. 
Workaround is to reload webpage.

**Comment by george110765** [comment]
opps closed by error.

**Comment by Chocobozzz** [comment]
Thanks, should be fixed in https://github.com/Chocobozzz/PeerTube/commit/42aac9fcfc837ddd60ac304a6e0f54b6e0e7a8e0
