### ISSUE TITLE
After reseting password and loging in, you're asked to reset password again

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#2205]
(originally reported by a user)

**Steps to reproduce**
1. Ask for a password reset
2. Click on the link received by mail to reset your password
3. Change the password
    ⇒ The user is redirected to the login page
4. Enter credentials and login

**What happened?**
The user is asked to reset their password once again. It's very confusing.

**What do you expect to happen instead?**
The user should be redirected to the Peertube home page.

**Additional information**
* PeerTube version or URL: 1.4.1
* Browser name/version: Firefox 72
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed in https://github.com/Chocobozzz/PeerTube/commit/f003ef1b54c3eedcc722e00c6a526f2368dd5885

**Comment by fflorent** [comment]
Thanks!
