### ISSUE TITLE
Remove Additional Extension Dependency On Transcoding Enabled

### ISSUE THREAD

**Issue by MrGiga** [Chocobozzz/PeerTube#2209]
**What happened?**
Transcoding must be enabled for additional file type extensions to be uploaded through API. Front end will allow the upload, API will reject it completely.

**What do you expect to happen instead?**
Additional extensions shouldn't be dependent on transcoding being enabled. It should be up to the owner to determine if they want to risk not having all their video play properly.

**Steps to reproduce:**

1. Set Transcoding to False

2. Set Additional Extensions to True

3. Verify that you can only upload the default extensions through API

**Additional information**
* PeerTube version or URL:
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
> Additional extensions shouldn't be dependent on transcoding being enabled. It should be up to the owner to determine if they want to risk not having all their video play properly.

I strongly disagree:
 * People will complain that *video x* does not work, and therefore that PeerTube does not work properly
 * As a user, when I click on a video I expect it to work (and will be very sad if it does not)
 * Most people don't know what video format will work or not

**Comment by MrGiga** [comment]
> Basically you are suggesting to make the video upload more complicated, and didn't provide any explanation why.

This would not make it more complicated. It would be an api that is available only to super users. I could even build it but I just don't want to spend my time on something that will be ultimately rejected. 

My reason: I have an instance of Peertube running on a local network. My audience is very small and all devices have been shown to work with the original file formats thus I don't need transcoding. Since transcoding is off, I cannot upload files with extensions such as .mkv.

**Comment by Chocobozzz** [comment]
For your use case you can use [this script](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#create-import-video-file-jobjs)
