### ISSUE TITLE
RSS subscribe button downloads the XML file instead of opening it in a new tab on mobile 

### ISSUE THREAD

**Issue by christophehenry** [Chocobozzz/PeerTube#2216]
This prevents easy RSS subscription on mobile. Plus, the link is not an actual link so it is impossible to just copy the target.

**Comment by frankstrater** [comment]
Partially fixed in the upcoming release by making the link in an actual link. See: https://github.com/Chocobozzz/PeerTube/pull/2145

**Comment by Chocobozzz** [comment]
Why just partially?

**Comment by frankstrater** [comment]
If you click the button some browsers still want to download the XML file instead of displaying it inline (compare Chromium with Firefox to see the difference). By making it an actual link you can copy the target (on desktop: right-click 'copy link location).

**Comment by frankstrater** [comment]
This is the result of (mis)using file-extension like .xml on non-file content, like dynamically generated RSS feeds. If you want to do this properly, you have to do some webserver configuration, where you force display inline.

**Comment by frankstrater** [comment]
I would prefer that you would drop the RSS urls that end with a file extension and replace them by normal RSS subscription urls (like: http://example.com/id/rss). That would solve all problems, probably also the RSS autodiscovery "bug" in https://github.com/rigelk/PeerTube/issues/2 and any future problems with RSS subscription and discovery etc.

**Comment by Chocobozzz** [comment]
@frankstrater I think we can add other feed routes, and use them in the client if your think it will fix these issues

**Comment by frankstrater** [comment]
@Chocobozzz Yes, I'm pretty sure it will fix these and other future issues as well.

**Comment by christophehenry** [comment]
> If you click the button some browsers still want to download the XML file instead of displaying it inline (compare Chromium with Firefox to see the difference). By making it an actual link you can copy the target (on desktop: right-click 'copy link location).

Or you can add a button that adds the link to your clipboard.

**Comment by albjeremias** [comment]
this is a bug, not an enhancement.. besides if users can't subscribe to peertube channels with the podcast clients... peertube becomes useless for a huge crowd.. please upgrade the priority of this issue

**Comment by Chocobozzz** [comment]
@frankstrater I tried with `/feeds/xml/videos` route, but firefox still wants to download the resource :thinking:

**Comment by christophehenry** [comment]
@Chocobozzz Just add a *Copy link to clipboard* button, man.

**Comment by albjeremias** [comment]
same here

**Comment by frankstrater** [comment]
> 
> 
> @frankstrater I tried with `/feeds/xml/videos` route, but firefox still wants to download the resource 🤔

You might need to add something to the nginx configuration for this new route then. In my experience with Apache this would have worked, but it's probably something which is default base config for Apache relating to mimetype handling.

**Comment by rigelk** [comment]
The mimetype served by the server is `application/rss+xml`, which while being the *most correct* per the RSS spec, is also the least supported by clients. Go figure. `application/xml` proves the most compatible and shows inline xml as asked.

**Comment by DontUseGithub** [comment]
what about `text/xml`?
https://stackoverflow.com/questions/595616/what-is-the-correct-mime-type-to-use-for-an-rss-feed/36708174#36708174
