### ISSUE TITLE
Duplicates in the list of contributers

### ISSUE THREAD

**Issue by AutomCoding** [Chocobozzz/PeerTube#2221]
Some usernames are listed twice in the translators section of [CREDITS.md](https://github.com/Chocobozzz/PeerTube/blob/develop/CREDITS.md#translation-contributors). It looks like this began in [back in January](https://github.com/Chocobozzz/PeerTube/commit/93f85e90ffa27453e2c909406b62bef65963b8ad?short_path=1ae3456#diff-1ae3456a0d122cc2071fa9f6c6a26189).

**Comment by bristow** [comment]
Yes me :)

**Comment by Chocobozzz** [comment]
Thanks, should be fixed in https://github.com/Chocobozzz/PeerTube/commit/ebd316d142d1619ded87277c274ea39df2eb21c2
