### ISSUE TITLE
Support more than 20 channels

### ISSUE THREAD

**Issue by MrGiga** [Chocobozzz/PeerTube#2224]
**What happened?**
Channel List drop down is limited to 20 channels, theres no way to select a channel that has been kicked off the list when uploading a file. User Channel List on User Page is also limited.
**What do you expect to happen instead?**
All channels should appear in the drop down and under the user's "My Channels" section
**Steps to reproduce:**

1. Create more then 20 channels
2. Upload file and try to select the first channel you created
3. Go to "My Channel" List and try to pull up the oldest channel.

**Comment by MrGiga** [comment]
This seems like a bug rather then an enhancement. You can currently make an unlimited amount of channels but only 20 will be selectable when uploading videos, and when looking at your own user channel list. I don't believe this is an issue when looking at others, and they appear when searching

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/a3ce4ae847b749d4cb2ebebb4134264b7c58dcc5
