### ISSUE TITLE
Custom Theme Not Taking Effect

### ISSUE THREAD

**Issue by MrGiga** [Chocobozzz/PeerTube#2225]
**What happened?**
According to the documents adding #custom-css in the css file, will cause the default class to be overridden. This is not the case after I install my test plugin where the header color background is set to red. The background is not red

**What do you expect to happen instead?**
The header background should be red.

Package.json
```
{
  "name": "peertube-theme-quickstart",
  "version": "0.0.2",
  "description": "PeerTube theme quickstart",
  "engine": {
    "peertube": ">=1.3.0"
  },
  "keywords": [
    "peertube",
    "theme"
  ],
  "homepage": "https://framagit.org/framasoft/peertube/peertube-theme-quickstart",
  "author": "Chocobozzz",
  "bugs": "https://framagit.org/framasoft/peertube/peertube-theme-quickstart/issues",
  "staticDirs": {
    "images": "public/images"
  },
  "css": [
    "assets/style.css"
  ],
  "clientScripts":[],
  "translations": []
}
``` 
assets/style.css
```                                                  
#custom-css .header {
    background-color: red;
}
```

**Comment by Chocobozzz** [comment]
Did you select this theme in your settings? What is your instance URL?

**Comment by MrGiga** [comment]
I tried to activate it and did a hard refresh but nothing changed. I even went to the Plugin/Themes section, installed all of those that appeared, after activating there was no changes. Is redis caching something that I am not aware of?

Its a private instance that's only accessible internally.

**Comment by Chocobozzz** [comment]
> Edit 3: Found the issue. I didn't realize I had to activate it at the user level too if I am logged in

:+1:

**Comment by alcalyn** [comment]
> I had to activate it at the user level too if I am logged in

I don't understand what it means, what do we have to do ? I also enabled the dark theme but nothing happens

**Comment by alcalyn** [comment]
Ooh ok, I went to Sidebar "Administration" > Tab "Configuration" > Tab "Basic configuration" > Section "Theme"

I selected the theme in the select option.
