### ISSUE TITLE
Warning in server logs after empty search

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#2226]
Is it really necessary to log a warning in the server logs every time someone makes an empty search? Seems like pointless noise.

`warn[11/7/2019, 9:35:14 PM] Incorrect request parameters { "path": "/api/v1/search/videos?search=", "err": { "search": { "value": "", "msg": "Should have a valid search", "param": "search", "location": "query" } } } 
`

To reproduce:
1. focus the search box
2. press enter
3. check server logs

Tested in Peertube 1.4.1

**Comment by Chocobozzz** [comment]
I think someone else tries to use the API, but does not correctly set the search parameter. The PeerTube client does not set the search parameter if it is empty.

I think this warning is useful, to see if someone does not correctly use the API (it helps debug etc).

**Comment by Nutomic** [comment]
Wouldnt it make more sense to send the warning as a response to the request, instead of putting it in the server logs?

**Comment by Chocobozzz** [comment]
They are already sent in the response, but most of the time users don't report this kind of issues and they don't have the network tab opened. As an admin, you report some warnings you see in the logs so we can fix issues your users have.
