### ISSUE TITLE
Setting limit for comments

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#2229]
I wonder if there is any option to increase the limit of characters for comments. If it doesn't exist, is this possible to add it?

PS : I wonder if this is technically possible. Correct me if I am wrong, but comments are stored in the database, which requires a limit for texts (VARCHAR). 

PS2 : I am a bit in a hurry, so don't hesitate to ask for clarification. Thanks :)

**Comment by Chocobozzz** [comment]
Hello, and sorry for the late.

I think that updating `VIDEO_COMMENTS.TEXT` would work. Do your users need more than 3000 characters for comments?

**Comment by fflorent** [comment]
> Do your users need more than 3000 characters for comments?

Yeah, ideally. Some of them can create long texts (like [metadechoc in this thred](https://skeptikon.fr/videos/watch/d32930c6-2e62-4165-98ae-cff3e28e6e8d;threadId=1128)).

We can workaround this issue by posting several answers one after another.

> I think that updating `VIDEO_COMMENTS.TEXT` would work.

If that's the only option, it doesn't seem ideal (especially in a docker environment). I think I'd prefer live without this option.

**Comment by Chocobozzz** [comment]
I think we can increase the limit to 10000

**Comment by Chocobozzz** [comment]
Limit increased in https://github.com/Chocobozzz/PeerTube/commit/298b3fd31529c047e87d34d397af3b08833bd8d0

**Comment by fflorent** [comment]
Thanks!
