### ISSUE TITLE
PeerTube-0.0.13-alpha install error

### ISSUE THREAD

**Issue by zzoozzo1122** [Chocobozzz/PeerTube#223]
* **PeerTube version or commit:**  PeerTube-0.0.13-alpha
* **Browser name/version:** Chrome
* **NodeJS version:** 8.9   , npm ver 5.6
* **PostgreSQL version:** 9.5

* **What is the expected behaviour?**

After installing the previous version normally
I have tested it.
However, PeerTube-0.0.13-alpha
Can not be installed. What I did wrong
I would like to know.

Even though I didn't see any symptoms of the sullership.
An error message was displayed at the end.

2018-01-20T21_29_08_195Z-debug.log
[2018-01-20T21_29_08_195Z-debug.log](https://github.com/Chocobozzz/PeerTube/files/1649289/2018-01-20T21_29_08_195Z-debug.log)

It works well on a new installation.
It's been solved.
Thank you.

**Comment by rigelk** [comment]
Hello @zzoozzo1122, please follow the [issue template](https://raw.githubusercontent.com/Chocobozzz/PeerTube/develop/.github/ISSUE_TEMPLATE.md) and use a Gist/Pastebin to link your log/debug output.

**Comment by zzoozzo1122** [comment]
I have just modified my report.

**Comment by bnjbvr** [comment]
Hi @zzoozzo1122! One error says that there's something wrong with permissions, the other one means a package isn't there (probably a symptom of the same issue).

I see you've used `sudo` during the installation process (which means all the created directories are owned by root) and the service unit specifies that the process is run by `peertube`.

Can you try the following:

```bash
sudo chown -R peertube /home/peertube
```

and retry thereafter please?

**Comment by ReK2Fernandez** [comment]
I have it running with letsscript just fine, but I had to manually change some nginx options. also did the upgrade and everything is working..  but I did not install on /home because as a system admin this is a BAD thing to do.. it should be on /var/www with the "user" peertube permissions... :) this is what happends when you let developers rule the production instalation :P

**Comment by zzoozzo1122** [comment]
Thank you for your help.
If you try again, one error message will be displayed.
I have corrected the error message.

2018-01-20T21_29_08_195Z-debug.log
[2018-01-20T21_29_08_195Z-debug.log](https://github.com/Chocobozzz/PeerTube/files/1649287/2018-01-20T21_29_08_195Z-debug.log)
