### ISSUE TITLE
Hosting Multiple source of videos on S3 compatible locations.

### ISSUE THREAD

**Issue by shleeable** [Chocobozzz/PeerTube#2232]
**What happened?**
There has been discussion previously, #147, about hosting content on s3 and mounting that locally as storage... I'm not speaking about that

I'd love to be able to use S3-compatible hosted storage. AWS/DigitalOcean/Wasabi or locally hosted minio etc etc -- 1 or more as mirrored online storage... this plays into the idea of having videos updated at multiple locations and around the world and will download the video from multiple locations and remove the network/disk IO load from the peertube server by offloading it to the S3 storage.

Thanks a lot :)

**Comment by rigelk** [comment]
@shleeable would load-balancing different buckets (assuming balanced buckets) work? In that case I invite you to review/try https://github.com/Chocobozzz/PeerTube/pull/2530

**Comment by shleeable** [comment]
I really feel like this should be passive (like a seedbox). 1000 people host instances and 100 other peope could host mirrorboxes to strengthen the popular videos 

like an activitypub CDN

**Comment by rigelk** [comment]
@shleeable well, instances are already capable of mirroring videos passively or explicitly, from instances they follow and selected to be mirrored, to individual videos. They act as a WebSeed that gets added to the list of servers capable of serving the file on the origin server, by send it a FileCache Activity.

Isn't that already a form of ActivityPub CDN?

**Comment by KonoromiHimaries** [comment]
https://ipfs.github.io/public-gateway-checker/

**Comment by pierreozoux** [comment]
@Chocobozzz [you say that](https://framagit.org/framasoft/peertube/documentation/commit/f4c5c55632b2bbb5436541046f46ba0882842167) "PeerTube does not support S3 buckets, but you can easily mount a S3 bucket via FUSE."

I really think that it would ease hosting by natively supporting s3 compatible api.

Popular open source software like gitlab, RocketChat and Nextcloud do support these options and it is really useful to be able to scale horizontally and have high availability.

**Comment by rigelk** [comment]
@pierreozoux have you tried https://docs.joinpeertube.org/#/admin-remote-storage though? Is it not enough?

**Comment by pierreozoux** [comment]
I never tried fuse, but in my environment (kubernetes) I'll not try that, it is not made for that.

On top, s3 fuse will just be with poor performance.

**Comment by rigelk** [comment]
@pierreozoux files are served directly via s3, only the sync after upload is done through fuse. So performance-wise, you won't see the difference.

**Comment by pierreozoux** [comment]
I'd like you reopen the issue.

A lot of people have voiced for that.

And if you could make an estimation, then we can all donate to frama, with the label :) And once you have enough for the feature, then boom! :)
(I'd like to donate without that of course, currently we don't use this that much, but yeah with live, it starts to become really interesting :) )

I'm available to explain why this is important also :)

**Comment by rigelk** [comment]
> I'm available to explain why this is important also :)

Please open your own issue to explain it then.
