### ISSUE TITLE
French localisation problem for v2.0.0

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2233]
**What happened?**

Some localisation segments are not ok for french in the new instance's statistic screen.
![image](https://user-images.githubusercontent.com/38844060/68690129-cc954780-0571-11ea-84dc-05031e3439a8.png)

- «7 commentaires de la video» should be «7 commentaires de vidéo» (bad syntax, and «video» / «vid**é**o»

- «116GB de la vidéo hébergée» should be «116GB de vidéos hébergées»

**Additional information**
* PeerTube version or URL: v2.0.0 (https://www.yiny.org)

**Comment by bristow** [comment]
Thanks for report.

Currently, the PeerTube project on Zanata is read-only. Probably due to the migration to Weblate that is being prepared....

**Comment by Chocobozzz** [comment]
Thanks, it's fixed in https://github.com/Chocobozzz/PeerTube/commit/193a327f59ed0c410e5931b3f12f20164a99999c

@bristow Yep, but now weblate is ready: https://weblate.framasoft.org/projects/peertube
