### ISSUE TITLE
About/Follows shows too much

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2234]
**What happened?**

The page https://www.yiny.org/about/follows shows followers of your instance. Even if the follower is a mastodon account. It shows only the domain, not the mastodon account. But if there are two followers on the same mastodon instance, they appears twice.
For example, on my instance page, there are two lines with mamot.fr, two with pawoo.net, etc.

Moreover, the sort order is not good (I think it use the username)

**What do you expect to happen instead?**

I'm not sure there is an interest for showing activityPub user accounts that follows an instance. I think only other (peertube?) servers should be shown.

**Steps to reproduce:**

1. Use mastodon accounts to follow @peertube@your_instance.tld

2. Go to your_instance.tld/about/follows

3. Mastodon accounts are listed, showing only the domain name (and then you have duplicates)

**Additional information**
* PeerTube version or URL: v2.0.0

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/97ecddae104f4013d261f0e9645e8b319ff0f1a6
