### ISSUE TITLE
Docker hub README contains broken links

### ISSUE THREAD

**Issue by remram44** [Chocobozzz/PeerTube#2236]
**What happened?**

I visited the Docker Hub page for the image: https://hub.docker.com/r/chocobozzz/peertube

I found broken links in there, so as:
* redundancy guide `https://docs.joinpeertube.org/lang/en/devdocs/architecture.html#redundancy-between-instances`
* FAQ `https://hub.docker.com/r/chocobozzz/FAQ.md`
* contributing guide `https://hub.docker.com/.github/CONTRIBUTING.md`
* community packages `https://docs.joinpeertube.org/lang/en/docs/install.html`
* Docker `https://hub.docker.com/support/doc/docker.md`
* user documentation `https://docs.joinpeertube.org/lang/en/userdocs/`
* admin documentation `https://docs.joinpeertube.org/lang/en/docs/`
* ... and others. You get it, it's out of date, and the relative links which work on GitHub don't work there

Also anchors:
* Create an instance `#package-create-your-own-instance`

Those links redirect and should be updated (both on the GitHub README and Docker Hub):
* WebTorrent `https://github.com/feross/webtorrent`

**Comment by Chocobozzz** [comment]
Thanks, should be fixed in https://github.com/Chocobozzz/PeerTube/commit/53a6d0a348162fdc712835e1c2b03186a90da188 & https://github.com/Chocobozzz/PeerTube/commit/4053ba6f6e261453ae98dac0eb60cde318007f01
