### ISSUE TITLE
Cannot view statistics with dark theme enabled

### ISSUE THREAD

**Issue by derekslenk** [Chocobozzz/PeerTube#2237]
**What happened?**
Cannot view statistics when theme is set to dark. Seems the text is white on a white text box

**What do you expect to happen instead?**
Be able to view the statistics

**Steps to reproduce:**

1. Install the dark theme from the theme search. 

2. After install, set your theme to dark in your profile.

3. Click on About in the left menu

**Additional information**
* PeerTube version or URL: https://peerwatch.xyz/about/instance (2.0.0)
* Browser name/version: Firefox 70, Chrome 78
* NodeJS version: 10.17.0

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/pull/2227 by @alcalyn
