### ISSUE TITLE
List of playlists on channel page looks bad, when more than 6 (six)

### ISSUE THREAD

**Issue by filin2009** [Chocobozzz/PeerTube#2238]
Hello!

**What happened?**
List of video-playlists on video-channel page looks bad,
when playlists count more than 6 (six). 
Playlist pics are not sending to second line/row.
Only one line is presented.
What if I'd like to create more than 6 playlists on same channel?
Other playlists are sending out of screen.
see for example
https://video.ploud.fr/video-channels/rtg_tv_hd/video-playlists

**What do you expect to happen instead?**
List of video-playlists on video-channel page looks same
as list of videos (Videos from your subscriptions, for example):
five (or six) pictures in a row (depends on user-screen resolution).
And three or four rows (horizontal lines) of pictures/videos.

**Steps to reproduce:**
1. Create 7 playlists in same channel
1. Go to https:// `PeerTube-Instance` /video-channels/ `channel-name`/video-playlists
for example https://video.ploud.fr/video-channels/rtg_tv_hd/video-playlists
or Playlists - My channels. Select channel. Video playlists.

Additional information:

1. PeerTube version or URL: Peertube 1.4.1
1. Browser name/version: Firefox

Does not hesitate to tell me if anything is missing or if I could give you more details

Thanks!

**Comment by filin2009** [comment]
Same thing on PeerTube v2.0.0
See for example
https://peertube.dk/video-channels/rtg_tv_hd/video-playlists

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/1689176a7bff6edd90d162994cccec2e4bfe9a45
