### ISSUE TITLE
Application for Invite

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#2242]
I thought there was already an issue for this, but apparently not.

The idea is this: Instead of having registration completely open, add a form where the user needs to enter their reason for signing up. Mods can then accept or deny the user. This is a very effective way to prevent signups from bots, or from users that are not welcome on a particular instance. This is already implemented in Mastodon (in https://github.com/tootsuite/mastodon/pull/10250) and works really well.

I think this is really a mandatory feature. Right now, instances with open signups are getting flooded with spam accounts and videos. That means it is impossible for a new user to find a good instance where they can sign up. And if people cant create an account, it will be impossible for Peertube to grow.

**Comment by Chocobozzz** [comment]
This is an interesting feature.

> I think this is really a mandatory feature. Right now, instances with open signups are getting flooded with spam accounts and videos.

I'm not sure to understand why this feature is much more efficient than setting autoblacklist to true and add an exception to the account after 1 or 2 valid uploads.

**Comment by JohnXLivingston** [comment]
> I'm not sure to understand why this feature is much more efficient than setting autoblacklist to true and add an exception to the account after 1 or 2 valid uploads.

A bot can also spam comments.

**Comment by WonderingDane** [comment]
I would like to see some kind of captcha at least, when users are registering. Luckily I haven't had to deal with bots yet though.

If an instance is closed for signups, it should be stated on joinpeertube.org or maybe even hidden. It's only going to confuse people, if they go to an instance, but can't sign up.

I know peertube.social says under "about" that you can just message the administrator for an account, but people aren't gonna look under "about". So having the register button there, but have it invite only would be better.

**Comment by GauthierPLM** [comment]
I am also interested by this: I am adopting PeerTube for a small education institution and as such we would like to restrict access to our instance: only registered users can watch videos and users must be invited/approved to watch them.

Manually approving users would ensure that only people approved can fully use the instance and add their own videos or participate on the instance.

**Comment by tio-trom** [comment]
I will add my comment here since my issue was a duplicated of this one. But briefly, in 2022, after having a public peertube for more than a year, I can say with certainty that many many many bots manage to bypass the captcha system and register to only post spam comments on other videos on the entire peertube network. One way to try and stop them is to ask for a reason for registration. Usually the bots fill up this with generic text and seems easy to spot them. Now they register daily on my instance and I cannot tell them apart from normal users.

It is worth a try with this feature for registrations...

**Comment by JohnXLivingston** [comment]
@tio-trom , I made 2  plugins that can help to limit bot account creation (it is not 100% bullet proof, but if it can help you...)

- https://github.com/JohnXLivingston/peertube-plugin-georegister : allow or disallow registration based on user's IP country
- https://github.com/JohnXLivingston/peertube-plugin-filterregistrations : add pattern to forbid in username, mail, IP, ...

**Comment by Chocobozzz** [comment]
This has been implemented in https://github.com/Chocobozzz/PeerTube/pull/5544. Details of the feature and screens are in the PR.

Basically if the admin enable signup that require approval, the user that wants to register has to fill a *Registration reason* textarea.
