### ISSUE TITLE
About/Instance Statistics are not readable when using Dark theme

### ISSUE THREAD

**Issue by grondinm** [Chocobozzz/PeerTube#2244]
Just upgraded my instance to v2. Looking great so far. Only issue is simply the stats are not readable when using the dark theme.

https://pixelfed.social/p/mgrondin/100574420690669568

Thank you

**Comment by Chocobozzz** [comment]
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/2237

**Comment by grondinm** [comment]
Of course this was already reported and fixed. My apologies for not looking at the fixed issues before submitting. Thank you for all your work.
