### ISSUE TITLE
Can't copy magnet link from Peertube Player

### ISSUE THREAD

**Issue by iagovar** [Chocobozzz/PeerTube#2245]
**What happened?**

Tried to copy magnet link from several videos, couldn't do it, the action just does nothing. Copying URL or insertion code works though:

**What do you expect to happen instead?**

Copy the magnet link

**Steps to reproduce:**

1. Go to https://framablog.org/2019/11/12/peertube-has-worked-twice-as-hard-to-free-your-videos-from-youtube/

2. Press play

3. Right click -> Copy magnet link

**Additional information**

It would be nice to display the magnet link as text in the info box of video instances. 

* PeerTube version or URL: https://framablog.org/2019/11/12/peertube-has-worked-twice-as-hard-to-free-your-videos-from-youtube/
* Browser name/version: Firefox and Chrome last versions on 15/11/2019
* NodeJS version: Don't have an instance, just an user

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by alcalyn** [comment]
We can see the error in js console (F12):

    VIDEOJS: ERROR: TypeError: "this.webtorrent(...).getCurrentVideoFile is not a function"

**Comment by Chocobozzz** [comment]
Thanks, fixed in https://github.com/Chocobozzz/PeerTube/commit/aedf50d142c8dce94aba6ad118b242fb826660a4
