### ISSUE TITLE
Confirmation mails not delivered

### ISSUE THREAD

**Issue by mpfau** [Chocobozzz/PeerTube#2246]
**What happened?**
Your confirmation mails get rejected and not delivered to the mailboxes of the one who signed up.

**What do you expect to happen instead?**
Delivery of confirmation mails

**Steps to reproduce:**
1. create a mail account on mail.tutanota.com
2. signup for a new peertube account
3. wait for the confirmation mail

**Additional information**
You did not configure the reverse DNS entry. There are many providers besides Tutanota who do not accept such mails nowadays.

**Comment by Nutomic** [comment]
This sounds like a problem with a particular instance, not with Peertube. Which instance are you using?

**Comment by mpfau** [comment]
peertube.linuxrocks.online

**Comment by Nutomic** [comment]
You should tell that to the instance admin. The Peertube project has nothing to do with that instance. But maybe the documentation can be improved.

**Comment by mpfau** [comment]
You are right! But you should probably add a contact section to peertube including a mail address. Currently, I do not see a way to contact the admins of this instance.

**Comment by Findus23** [comment]
The about page allows you to send a message to the instance admin:
![image](https://user-images.githubusercontent.com/6266037/68882098-ce484200-070e-11ea-8903-862132a60108.png)

**Comment by mpfau** [comment]
How did I miss that? :innocent:

I submitted the message to them. Sorry for any inconvenience!
