### ISSUE TITLE
Broken Embed player in v2.0.0

### ISSUE THREAD

**Issue by aerogus** [Chocobozzz/PeerTube#2249]
**What happened?**

Embedded player with integration code doesn't work in PeerTube 2.0.0: 

- black screen
- js error

**What do you expect to happen instead?**

A working embedded player like in v1

**Steps to reproduce:**

Choose a video, grab its embed url like :

- https://videos.adhocmusic.com/videos/embed/0c20e037-b7a5-42c7-bf94-4a91755edcd8
- https://video.ploud.fr/videos/embed/f3cb1945-a8f7-481f-a465-946c6f884e50​

**PeerTube version or URL:**

2 differents instances of PeerTube v2.0.0

- https://videos.adhocmusic.com/videos/embed/0c20e037-b7a5-42c7-bf94-4a91755edcd8
- https://video.ploud.fr/videos/embed/f3cb1945-a8f7-481f-a465-946c6f884e50​

**Browser name/version:**

MacOS Catalina 10.15.1, Firefox 70.0.1 and Safari

**Link to browser console log if useful:**

same error for both instances :

```
TypeError: "e[t] is undefined"
    r https://videos.adhocmusic.com/client/standalone/videos/video-embed.3f569feada70ac019c63.bundle.js:2
```

```
TypeError: "e[t] is undefined"
    r https://video.ploud.fr/client/standalone/videos/video-embed.3f569feada70ac019c63.bundle.js:2
```

**Comment by Chocobozzz** [comment]
It's weird, I can't reproduce using browser stack :thinking: What is your Safari version?

**Comment by aerogus** [comment]
I have cleaned my cookie/cache in Firefox and the bug disappear for the adhocmusic instance, even in no private navigation mode.

**Comment by Chocobozzz** [comment]
It seems there is an issue only with video.ploud.fr, that is broken with all the web browsers.

**Comment by aerogus** [comment]
It seems so. I close the issue. Thx again for the reactivity and this v2 !
