### ISSUE TITLE
Link to original URL of the video

### ISSUE THREAD

**Issue by ldidry** [Chocobozzz/PeerTube#2250]
Could we have a link to the original URL of the video on the video page, please? For example, it would be useful for copyright holders to know where to ask for deleting a video they own, or any other complaint.

The link could be in the "three dots" menu, like « Original link of the video », or under the "Published at" text. Or you could add something like "Published at XXX on original_instance_domain" with the link on the `original_instance_domain`.

**Comment by WonderingDane** [comment]
Shouldn't it just be under "report" and the report should go to instance that hosts the video?

**Comment by Chocobozzz** [comment]
@WonderingDane We already send the report to the instance that hosts the video

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/c910f667d29bf2ff1f1c954c6d8b5044cb54a1a6
