### ISSUE TITLE
API GET /videos Invalid number of videos returned

### ISSUE THREAD

**Issue by gbip** [Chocobozzz/PeerTube#2251]
When trying to query the Peertube API to fetch video metadata (`GET /video`), it seems that the `count` parameter of the query is not respected when it is over 100.

For instance, running `curl https://vid.lubar.me/api/v1/videos\?count\=100000 | jq '.data' | jq length` yields `100` while `curl https://vid.lubar.me/api/v1/videos\?count\=100000 | jq '.total' returns `13819`.

If this behavior is intentional it would be great to document it ! :smile:

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/6676056a316a09557b8445cf6c0583ff8c588339
