### ISSUE TITLE
Transfer between instances : video's license and language tags are not transfered

### ISSUE THREAD

**Issue by Jeanneavelo** [Chocobozzz/PeerTube#2252]
**What happened?**

My actual instance will soon be shut down so I want to transfer my videos to another one.
Using the "import with URL" function everything's fine except for the license and language tags who are not displayed. I have to pick them manually.

**What do you expect to happen instead?**

License and language tags should be automatically transfered.

**Steps to reproduce:**

1. Select a video URL from a Peertube instance

2. Use the "import with URL" function on another instance

3. Watch license and language tags stay empty

**Additional information**
* PeerTube version or URL: https://open.tube/fr-FR
* Browser name/version: Mozilla Firefox 70.0.1
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
For the language we can't really do anything since it's not provided by youtube-dl, the tools we use to import remote videos.

**Comment by Jeanneavelo** [comment]
Maybe we could choose a language by default in a PeerTube account (regarding import)?

**Comment by Chocobozzz** [comment]
Thanks to the work of @3risian on https://github.com/ytdl-org/youtube-dl/pull/23657 we now support language and licence import with https://github.com/Chocobozzz/PeerTube/commit/86ad0cde9e7e7cbe86dfd7642c9d9b807e17c172

**Comment by Jeanneavelo** [comment]
> Thanks to the work of @3risian on [ytdl-org/youtube-dl#23657](https://github.com/ytdl-org/youtube-dl/pull/23657) we now support language and licence import with [86ad0cd](https://github.com/Chocobozzz/PeerTube/commit/86ad0cde9e7e7cbe86dfd7642c9d9b807e17c172)

That's great! Many thanks!
