### ISSUE TITLE
Language Filter setting doesn't work on Trending

### ISSUE THREAD

**Issue by realityfabric** [Chocobozzz/PeerTube#2253]
**What happened?**

Changed my video language preferences to English and Spanish only. Visited the Trending Videos page and videos which were listed as in French were still listed.

This is not a problem on the Local Videos or Recent Videos feeds. I did not test the Overview page.

**What do you expect to happen instead?**

Only videos in the languages selected in the preferences should be listed.

**Steps to reproduce:**

1. Change your language preferences to any language other than French (I chose English and Spanish). Getting rid of French seems most useful since most videos are in French.
2. Save these settings.
3. Visit the Trending page. Tons of videos in French.

**Additional information**
* PeerTube version or URL: https://peertube.social (v2.0.0)
* Browser name/version: Firefox 68.2.0 ESR

**Comment by Chocobozzz** [comment]
I'm sorry I can't reproduce. Could you paste the request URL when you are on the recently added video page, and when you are on the trending video page?

**Comment by realityfabric** [comment]
Is the Request URL different from the URL in the navigation bar?

If not:
- Recently Added: https://peertube.social/videos/recently-added
- Trending: https://peertube.social/videos/trending

That's with the filters enabled. When I do an empty search (nothing in the search box) the URL I get is: https://peertube.social/search?search=&languageOneOf=en&languageOneOf=es

I'm still seeing French videos in Trending when French should be filtered.

I just tested by filtering for only Spanish videos and the Recently Added includes Japanese, Spanish, English... but it does filter out some videos, I'm just not sure what its criteria are.

**Comment by Chocobozzz** [comment]
> Is the Request URL different from the URL in the navigation bar?

Yes it is different, you need to open the developer console to see the network requests PeerTube makes.

> I just tested by filtering for only Spanish videos and the Recently Added includes Japanese, Spanish, English... but it does filter out some videos, I'm just not sure what its criteria are.

Please give me the URL of a video that should not be in your trending page.

**Comment by realityfabric** [comment]
Okay, I set the filter to only show videos in Spanish:

Recently Added: 
- https://peertube.social/api/v1/videos/?start=0&count=25&sort=-publishedAt&languageOneOf%5B%5D=es

Trending: 
- https://peertube.social/api/v1/videos/?start=0&count=25&sort=-trending&languageOneOf%5B%5D=es

And the very first video in Trending when filtering for only Spanish videos: 
- https://peertube.social/videos/watch/9c9de5e8-0a1e-484a-b099-e80766180a6d

**Comment by Chocobozzz** [comment]
[this video](https://peertube.social/videos/watch/9c9de5e8-0a1e-484a-b099-e80766180a6d) has spanish subtitles

**Comment by realityfabric** [comment]
Oh, yes, that would explain it. Every video I'm checking that isn't marked as whatever language I'm testing has subtitles for that language.

Could we make that more explicit in the settings page? Currently it just says where the filter will be applied (Trending, Recently Added, and Local). Other than that... looks like it's not a bug after all, my mistake.

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/commit/20f1ec8d9d356bf961d3672c3ec771745fd4ce36
