### ISSUE TITLE
'About' page lists pending instance follows

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#2255]
I just upgraded to v2.0.0 and noticed that list of instance followers on the 'about' page lists pending instance when it shouldn't be. I assume the follow list does the same, but I have no pending follows, so I can't verify this

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/b8f4167fb6fa448125aeecff80b201d74e27fe6a
