### ISSUE TITLE
Sharp 0.23.2 not compiling on FreeBSD

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#2257]
**What happened?**
Sharp 0.23.2 will not compile on FreeBSD.

To upgrade from Peertube 1.4.1 to Peertube 2.0.0 edit package.json to use sharp 0.22.1 instead of sharp 0.23.2 before installing modules with yarn.

**Comment by Chocobozzz** [comment]
You should not have this error anymore in the future: https://github.com/lovell/sharp/commit/1b401b1195427a425b15450601cf89e6da6c9a1d

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/a5a254c4b867b97d98978bd506f0af95adb51886
