### ISSUE TITLE
Insufficient error handling if the upload file size exceeds the permissible limit

### ISSUE THREAD

**Issue by Vertux** [Chocobozzz/PeerTube#2259]
**What happened?**
File upload failed without error message

**What do you expect to happen instead?**
Peertube should check the file size, inform me about the too big file size and deny the upload.

**Steps to reproduce:**
1. Upload an audio/video file which exseeds the allowed file size (webserver configuration)
2. When the upload (green bar filling up) should start Peertube shows a malformed page without any error message:

![Bildschirmfoto 2019-11-17 um 10 33 33](https://user-images.githubusercontent.com/10457918/69005771-fd390080-0926-11ea-88fc-9a7e58dc7536.png)

3. If you go back one page in the browser history an error message pops up:

![Bildschirmfoto 2019-11-17 um 10 44 39](https://user-images.githubusercontent.com/10457918/69005820-92d49000-0927-11ea-9aed-c83cbd7de9c7.png)

**Additional information**
* PeerTube version or URL: v2.0
* Browser name/version: Firefox v.70.0.1 MacOS

**Edit:** It is pretty weird that this error happens at all, because the file size of the upload is 170MB (audio file) `20646#0: *4295448 client intended to send too large body: 172046239 bytes`
and PHP/Nginx/Apache are configured as follows:

- post_max_size 2G

- upload_max_filesize 1500M

- client_max_body_size 0 (check disabled)

- LimitRequestBody 2147483647

**Comment by Chocobozzz** [comment]
Please paste your nginx configuration. Also, we don't use PHP and don't support Apache.

**Comment by Vertux** [comment]
> Please paste your nginx configuration. Also, we don't use PHP and don't support Apache.

I am running Peertube with Apache - the error message is misleading. I was not aware that Apache is not officially supported, thank you for the hint. I guess I am gonna reconfigure my installation next weekend with Nginx.

**Comment by Vertux** [comment]
Just for reference I am using @rigelk [apache configuration ](https://gist.github.com/rigelk/07a0b8963fa4fc1ad756374c28479bc7)
