### ISSUE TITLE
Faulty URL import of MP3 audio files

### ISSUE THREAD

**Issue by Vertux** [Chocobozzz/PeerTube#2260]
**What happened?**
An audio file (MP3) which was imported by URL (compatible with youtube-dl) is not playable

**What do you expect to happen instead?**
The URL / file type should not be accepted if it is not probably supported. The info window is misleading:

![Bildschirmfoto 2019-11-17 um 12 00 30](https://user-images.githubusercontent.com/10457918/69006818-1f397f80-0935-11ea-938c-e52cf147d806.png)

**Hint:** The same audio file is playable without any issues if you upload it directly as file. On the server it looks like this. It is not the same file as below, but is does not matter. The point is, the files seem to be treated different `-480.mp4`vs `-150.mp4`

![Bildschirmfoto 2019-11-17 um 12 40 43](https://user-images.githubusercontent.com/10457918/69006984-cd462900-0937-11ea-88fd-332c68ca925f.png)

**Steps to reproduce:**

1. Import an (audio) URL e.g. `http://media.libsyn.com/media/omegataupodcast/omegatau-35-moderneELoksBombardierTRAXX.mp3`

2. If you try to play the imported audio (MP3) file in the browser/web-player, it seems to work (you get no error) but you do not hear anything. That's what the file looks like on the server:

![Bildschirmfoto 2019-11-17 um 12 30 46](https://user-images.githubusercontent.com/10457918/69006923-c4088c80-0936-11ea-86dc-613a050b19a7.png)

**Edit:** If I download the audio file, VLC plays it without any issues.

**Additional information**
* PeerTube version or URL: v2.0
* Browser name/version: Firefox v70.0.1 MacOS

**Comment by Chocobozzz** [comment]
Audio file imports should now work.
