### ISSUE TITLE
Add a channel filter to search results

### ISSUE THREAD

**Issue by AlphaShadows77** [Chocobozzz/PeerTube#2262]
Hey !
When we are searching a channel in the search bar, the search results can show some of the corresponding channels mixed with the videos and the channel we are searching can be unfindable and it become hard to find this searched channel.
Currently, there is many filters for the search results but no filters for channels.

![Filters for the search results](https://tof.cx/images/2019/11/17/c048948c6f0f8614fcb83d0216759f79.png)
I think that a filter for channel could be a good idea to add because it can be more simple to share a channel name than a channel id. For example, if we want to talk about a peertube channel to someone who does not know this channel, we could just say the name of the channel to allow him to find it.
With this filter, we could know if a person/company/association/... has a peertube channel without searching everywhere in their website, their social media account, ...

I know that there is a disadvantage to what I said above. If the person who are searching an entity is not on the same instance and his instance does not follow the entity's instance, he will not be able to find the entity's channel. I think that it is not really a problem because many instances follow enough instances to allow their members to find a lot of people through his search bar.

Thank you for reading, let's talk about it !

**Comment by DontUseGithub** [comment]
relevant https://github.com/Chocobozzz/PeerTube/issues/2464

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/8cf43a6524d354fbfa0f0eaf789e8d4756bd25d6
