### ISSUE TITLE
Browser console log Undefined error with remote subscribe

### ISSUE THREAD

**Issue by Alexconquer** [Chocobozzz/PeerTube#2264]
Hello,

**What happened?**

I can not subscribe on forms on other instances.

**What do you expect to happen instead?**

subscribe to other instances.

**Additional information**
* PeerTube version or URL:

V2.0 https://video.conquerworld.fr/
external nginx proxy

* Browser name/version:

Brave 1.0 same problem on firefox

* NodeJS version:

Docker ?

* Link to browser console log if useful:

In next step user validation (well-know/webfinger) Undefined error
the webfinger data : 

{"subject":"acct:alexconquer@video.conquerworld.fr","aliases":["https://video.conquerworld.fr/accounts/alexconquer"],"links":[{"rel":"self","type":"application/activity+json","href":"https://video.conquerworld.fr/accounts/alexconquer"}]}

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

No error on log server

**Comment by Chocobozzz** [comment]
Please try to follow peertube3.cpy.re, and send me your server logs by email (in my github profile)
