### ISSUE TITLE
PeerTube's nginx serves .js files as html

### ISSUE THREAD

**Issue by think222** [Chocobozzz/PeerTube#2265]
**What happened?**
PeerTube's nginx configuration will serve `.js` files with the mime type of `text/html`. This breaks any modern browser.

**What do you expect to happen instead?**
The mime type to be `.js`

**Steps to reproduce:**
This is the relevant bit of config:
```
location ~ ^/client/(.*\.(js|css|png|svg|woff2|otf|ttf|woff|eot))$ {
  add_header Cache-Control "public, max-age=31536000, immutable";

  alias /var/www/peertube/peertube-latest/client/dist/$1;
}
```

If I remove that from the provided nginx config, everything works.

**Additional information**
* PeerTube version or URL: 2.0.0
* Browser name/version: All
* NodeJS version: v10.17.0

Fresh install on Arch Linux following the production guide verbatim.

**Comment by think222** [comment]
To supplement this, it appears that anything that followed the comment `# Bypass PeerTube for performance reasons. Could be removed` wasn't working. When I removed all of these, video streaming and thumbnails and js files start working.

**Comment by Chocobozzz** [comment]
Please paste your instance URL

**Comment by think222** [comment]
@Chocobozzz https://nona.li. Do note the problem I was referring to is not reproducible now as I just removed the `# Bypass PeerTube` sections from my nginx configuration.

**Comment by Chocobozzz** [comment]
What is the content of `/var/www/peertube/peertube-latest/client/dist/`?

**Comment by think222** [comment]
```
assets
ca_ES
cs_CZ
de_DE
el_GR
en_US
eo
es_ES
eu_ES
fi_FI
fr_FR
gd
it_IT
ja_JP
locale
manifest.webmanifest
nl_NL
oc
pl_PL
pt_BR
pt_PT
ru_RU
standalone
sv_SE
zh_Hans_CN
zh_Hant_TW
```

**Comment by Chocobozzz** [comment]
Please don't comment the bypass section, and check your nginx logs. And what are the contents of the js files nginx serve? Is it an html content?

**Comment by think222** [comment]
It appears that the permissions of `/var/www/peertube` had the permissions of `700` rather than `755`, which made nginx incapable of reading the files, and somehow lead to nginx serving the js files as HTML.

For googlability, here is a paste of one of the browser console log error messages:
`Loading module from "filename.js" was blocked because of a disallowed MIME type ("text/html")`
