### ISSUE TITLE
Embed scope for plugins

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#2267]
So far, there is no way for a plugin to alter the embed. It would be nice if it had the same hooks as for the watch page, with similar passed parameter. That would allow plugins affecting the player to function in embeds with little modification.

**Comment by cabaleiro8** [comment]
I found this after creating my own issue :disappointed: But I'll leave it open and maybe somebody cares about it :laughing: https://github.com/Chocobozzz/PeerTube/issues/2458

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/3112
