### ISSUE TITLE
Helper to know if the user is logged-in for plugins

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#2269]
From a plugin, being able to know if a visitor is in fact an authenticated user would allow differentiated features for logged-in and anonymous users.

I don't know if it is desirable to expose user information to plugins yet, but just knowing if we are in an authenticated session could be interesting.

**Comment by JohnXLivingston** [comment]
I'd like the user's IP in order to block registration via IP's geolocalization. 
See: https://github.com/Chocobozzz/PeerTube/issues/2056

**Comment by rigelk** [comment]
@JohnXLivingston that works only for the registration hook (it is in the `params` parameter of the hook), but I implemented it in ba7b7e572f0634e534320a057f4cc0a95f2a541d

**Comment by JohnXLivingston** [comment]
Thanks @rigelk . I saw your commit the other day :)

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/eb8f702c8398b7f51461c8e967c7bc7de3c10c16
