### ISSUE TITLE
Watch-later list

### ISSUE THREAD

**Issue by bnjbvr** [Chocobozzz/PeerTube#227]
The idea is the same as on Youtube: create a list of videos to watch later, once when the user signs up (for instance), so that one can just jump on PeerTube, save a video and close the tab.

We can imagine variations of this feature, like automatic removal of videos to watch later that have been watch, etc. But just having a list precreated by default for users would be a great start, in my opinion!

**Comment by Chocobozzz** [comment]
I think "Watch later" is just a playlist. So maybe we could merge this issue in https://github.com/Chocobozzz/PeerTube/issues/14?

**Comment by bnjbvr** [comment]
I think I agree that Watch later is just a playlist; what I specifically suggest here is that this playlist be automatically pre-created for each user (at the time they sign up). Once #14 is implemented, it should be a breeze to do so.

**Comment by Chocobozzz** [comment]
:+1:

So this issue is blocked by https://github.com/Chocobozzz/PeerTube/issues/14

**Comment by bkfox** [comment]
also, what it would be really cool is we can bookmark at specific timestamp in the video easily (in a more  generic way, it could be cool for playlist creation too)

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/1708

It's missing the miniature icon (https://github.com/Chocobozzz/PeerTube/issues/1716) though

**Comment by stom79** [comment]
I got errors 403 when I want to watch a video at the root of my play-lists. If I add them into a play-list that I created, the list is empty for the same purpose.

`{"error":"Cannot get this private video playlist."}`

It seems related to the private status of my play-lists

**Comment by rigelk** [comment]
@stom79 please create a dedicated issue.
