### ISSUE TITLE
Changing language results in a blank page

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2272]
**What happened?**
if you change the language you get a blank page
**What do you expect to happen instead?**
to see the page in the language I pick
**Steps to reproduce:**

1. video.tedomum.net

2. click the language icon

3. change language

**Additional information**
* PeerTube version or URL: 2.0
* Browser name/version: FF 70

**Comment by Chocobozzz** [comment]
Please paste the URL of your instance

**Comment by DontUseGithub** [comment]
not my instance, but the instance I've tested this on 
video.tedomum.net

**Comment by DontUseGithub** [comment]
what's also interesting is that after removing `/es-ES` from the url the page still remains blank.

**Comment by Chocobozzz** [comment]
I think there is something wrong on their side (maybe they forgot to reload their front end or ). Try to contact them.
