### ISSUE TITLE
Left sidebar text goes beyond the sidebar

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2274]
Visit this page https://video.ploud.fr/es-ES and look at the **Anadidos recientemen**... from the sidebar. 

**Additional information**
* PeerTube version or URL: 2.0
* Browser name/version: FF 70

**Comment by Chocobozzz** [comment]
Thanks, should be fixed in https://github.com/Chocobozzz/PeerTube/commit/24e0d90069e16b7005d78d0d8fa3c8d80fe25b14
