### ISSUE TITLE
Infinite scroll for the Discover page

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2275]
IMO there isn't much sense for someone to visit a single page just to scroll a little and then be forced to leave it because there's not much content. 
The idea behind the Discover page is nice and we should make it continue load new hashtags, channels etc indefinitely.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/764a965778ac89e027fd05dd35697c6763e0dc18 & https://github.com/Chocobozzz/PeerTube/commit/111fdc267b36201cf1be1fdf91017005102b4a5e
