### ISSUE TITLE
Notify admin on available plugin update

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#2276]
Right now no notification is displayed on new updates for plugins: the admin has to check the plugins page to see if a plugin has an update available.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/2f0bacfc8a22de710fcb6b62d8f69ee3dee82224

**Comment by rigelk** [comment]
thanks a bunch @Chocobozzz!
