### ISSUE TITLE
Possiblity to change video orientation

### ISSUE THREAD

**Issue by gbraad** [Chocobozzz/PeerTube#2278]
For some video that start recording in Portrait (as this seems to feel natural) but actually get recorded in Landscape, the video orientation is wrong as this does not get updated in the metadata.

It would be great if Peertube could be told (before transcoding, or update) to change the orientation to force a video in the 'correct' orientation.

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/3094
