### ISSUE TITLE
Are there a few more step by step instructions for the docker install?

### ISSUE THREAD

**Issue by yangnom** [Chocobozzz/PeerTube#2281]
**What happened?**
I couldn't install the docker container of peertube

**What do you expect to happen instead?**
To follow the instructions

**Steps to reproduce:**

1.  Read the directions [here](https://github.com/Chocobozzz/PeerTube/blob/master/support/doc/docker.md)

2. Fail at installing it myself on a VPS

**Additional Information**
I know this is entirely my fault but the steps on the previously linked page have 

```
Update the reverse proxy configuration:

$ vim ./docker-volume/traefik/traefik.toml
```

```
Tweak the docker-compose.yml file there according to your needs:

$ vim ./docker-compose.yml
```
and 

```
Then tweak the .env file to change the environment variables:

$ vim ./.env
```

I'm sure the step by step instructions for those parts vary enough that it's not as simple as copy and paste certain things in certain places, but if `traefil.toml` `docker-compose.yml` and `.env` had some comments somewhere remarking where I should put my ip and other such information it would be of great help!

If anyone can link me to some kind of more in depth how-to, I'd be very grateful, and I wouldn't mind writing a more in-depth how to for docker installation (so a complete novice could install an instance more easily) if I ever figure this out.

Thanks very much!

**Comment by Nutomic** [comment]
You could try my Ansible based config instead, for that you only need to edit a single local file.

https://framagit.org/Nutomic/peertube-compose

**Comment by rigelk** [comment]
> I couldn't install the docker container of peertube

What is your error?
