### ISSUE TITLE
Custom Video Preview Not Appearing Outside of Video Player

### ISSUE THREAD

**Issue by MrGiga** [Chocobozzz/PeerTube#2287]
**What happened?**
The custom video preview that I upload with videos is only appearing after selecting the video. When browsing selection of videos, a random image is being used but once I pick a video and load it, the video player shows the custom image that I uploaded.

**What do you expect to happen instead?**
Custom video preview image should be shown at all times.

I am probably overlooking something, but I did notice that my custom previews were appearing with the searches but after awhile it switched to a random image. Is there a job that I can run that will update all my videos to show the proper video preview at all times?

**Comment by Chocobozzz** [comment]
The thumbnails are cached for ~2 hours

**Comment by MrGiga** [comment]
Does this mean after two hours they will reset or that they will change to the custom image after two hours?

**Comment by MrGiga** [comment]
They seem to be appearing correctly on mobile but not on desktop.

**Comment by Chocobozzz** [comment]
> Does this mean after two hours they will reset or that they will change to the custom image after two hours?

No, I mean your web browser should cache the thumbnail during ~2 hours. Please give me a video URL with an incorrect thumbnail
