### ISSUE TITLE
[META] - Ghosted content on GitHub is hidden - we may be losing valuable contributions

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2289]
This is what the Privacytools.io team have realized:

> We have multiple issues that have important information within, but as the user has stopped using GitHub or otherwise gotten their GitHub account deleted, they cannot be found using the search. 

https://github.com/privacytoolsIO/privacytools.io/issues/1379

And a similar thing happens in Chocobozzz/PeerTube. We can't find issues and perhaps other form of contributions from 'ghost' users. What should we do? How should we best approach this situation?

**Comment by Chocobozzz** [comment]
We don't loose their contributions since the issues are kept. Regarding the search, it could be an issue. You may report it to github. The ghost label is a good idea though. You can link the problematic issues here so we can add the label.

**Comment by DontUseGithub** [comment]
Here's one solution: to skim through [these](https://www.google.com/search?source=hp&ei=FzkaXrKHBJKWkwX754BY&q=site%3Agithub.com%2FChocobozzz%2FPeerTube%2Fissues+ghost&oq=site%3Agithub.com%2FChocobozzz%2FPeerTube%2Fissues+ghost&gs_l=psy-ab.3...404.404..867...0.0..0.95.95.1......0....2j1..gws-wiz.W8beU_Uglpc&ved=0ahUKEwjy7oCNuvzmAhUSy6QKHfszAAsQ4dUDCAU&uact=5) search results and see what has been omitted.
