### ISSUE TITLE
Thumbnail ratio

### ISSUE THREAD

**Issue by sanpii** [Chocobozzz/PeerTube#229]
* **PeerTube version or commit:** v0.0.13-alpha
* **Browser name/version:** firefox 57
* **NodeJS version:** 5.6.0
* **PostgreSQL version:** 10

The thumbnail ratio is not preserved.

The thumbnail:
![dgnwnmeg](https://user-images.githubusercontent.com/113045/35199057-a06664f4-fef8-11e7-84cd-3b2c9aa69a1a.jpg)

The video preview:
![screenshot-2018-1-21 3d zoetrope found at 34c3](https://user-images.githubusercontent.com/113045/35199061-a5085a80-fef8-11e7-8f5e-079ea984eb62.png)

See the problem on my instance: https://tube.homecomputing.fr/videos/watch/89e15f9b-96a1-4356-a2ea-8262686c0310

**Comment by Chocobozzz** [comment]
Fixed: https://github.com/Chocobozzz/PeerTube/commit/266707202c2ffcb8a1b7649ec29106dd444f4a77

**Comment by sanpii** [comment]
@Chocobozzz Thank you. How can I regenerate thumbnails?

**Comment by Chocobozzz** [comment]
Sorry you can't. But you could update the video thumbnail by uploading a new image file.
