### ISSUE TITLE
You can subscribe to your own channel

### ISSUE THREAD

**Issue by cyberchief1984** [Chocobozzz/PeerTube#2291]
So, you make an account on an instance, and make your channel.

You can subscribe to the channel you have made. This shouldn't be possible.

**Comment by alcalyn** [comment]
Why is it a bug ? It could be useful if want to see my own videos on my thread, among other videos from others account I follow.

Even on blocking that, I'll still be able to follow my PeerTube channel with my Mastodon account

**Comment by cyberchief1984** [comment]
The Competitor doesn't let you do this.

**Comment by Chocobozzz** [comment]
I don't think it's a bug either. It can be useful to see how a notification is displayed when someone else follows your channel.
