### ISSUE TITLE
Add a chat feature by integrating Matrix or XMPP into PeerTube

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2295]
Both Matrix.org and XMPP are very popular decentralized IMs. We could pick one (or both) and integrate into PeerTube's interface and thus create a "chatting feature" for PeerTube users.

**Comment by rigelk** [comment]
Hi @DontUseGithub ! Please look out for related issues before creating one, as #2130 already covers this. You can then detail further your use case there.
