### ISSUE TITLE
Improve Media-RSS support

### ISSUE THREAD

**Issue by azmeuk** [Chocobozzz/PeerTube#2298]
Since #23 Peertube has a basic support for the [Media-RSS extension](http://www.rssboard.org/media-rss). This is great, however I think some things might be improved. Here is an [extract of feed](https://framatube.org/feeds/videos.xml?accountId=3):
```xml
<item>
    <title><![CDATA[3.5. Le Collectif des Hébergeurs Alternatifs Transparents Ouverts Neutres et Solidaires (CHATONS)]]></title>
    <link>https://framatube.org/videos/watch/0e651828-4b48-4f65-835b-b0eb43b99a2e</link>
    <guid>https://framatube.org/videos/watch/0e651828-4b48-4f65-835b-b0eb43b99a2e</guid>
    <pubDate>Mon, 02 Dec 2019 12:46:39 GMT</pubDate>
    <description><![CDATA[MOOC CHATONS#1 - Internet : pourquoi et comment reprendre le contrôle ?
        Séquence 3. C'est quoi les solutions ?
        Vidéo 5. Le Collectif des Hébergeurs Alternatifs Transparents Ouverts Neutres et Solidaires (CHATONS)]]></description>
    <content:encoded><![CDATA[MOOC CHATONS#1 - Internet : pourquoi et comment reprendre le contrôle ?
        Séquence 3. C'est quoi les solutions ?
        Vidéo 5. Le Collectif des Hébergeurs Alternatifs Transparents Ouverts Neutres et Solidaires (CHATONS)]]></content:encoded>
    <dc:creator>Framasoft</dc:creator>
    <enclosure type="application/x-bittorrent" url="https://framatube.org/static/torrents/0e651828-4b48-4f65-835b-b0eb43b99a2e-1080.torrent" length="216831843">
    </enclosure>
    <media:group>
        <media:content type="application/x-bittorrent" url="https://framatube.org/static/torrents/0e651828-4b48-4f65-835b-b0eb43b99a2e-1080.torrent" isDefault="true">
        </media:content>
        <media:content type="application/x-bittorrent" url="https://framatube.org/static/torrents/0e651828-4b48-4f65-835b-b0eb43b99a2e-480.torrent">
        </media:content>
        <media:content type="application/x-bittorrent" url="https://framatube.org/static/torrents/0e651828-4b48-4f65-835b-b0eb43b99a2e-360.torrent">
        </media:content>
        <media:rating>nonadult</media:rating>
    </media:group>
    <media:thumbnail url="https://framatube.org/static/thumbnails/0e651828-4b48-4f65-835b-b0eb43b99a2e.jpg" height="122" width="223">
    </media:thumbnail>
</item>
```

Among all the different tags that Media-RSS provides, Peertube feeds only use the "thumbnail" one. IMHO there could be some more:

- `<media:title>`: The video title.
- `<media:description>`: The video description.
- `<media:rating>`: Is the video safe for everyone or adults only?
- `<media:keywords>`: The video tags.
- `<media:category>`: The video category.
- `<media:hash>`: The video hash. I am not sure how it is useful, but at least it seems easy to do :)
- `<media:player>`: Link to the video page.
- `<media:community><media:statistics>`: The number of views
- `<media:comments>`: The video comments, however I am not sure it is pertinent to include this one.
- `<media:license>`: The video license.
- `<media:subtitle>`: The video subtitles.
- `<media:credit>`: The video credits.

Despite its age and being edited by the RSS board, Media-RSS is not a very popular format among the RSS feed readers. However I think that feed provider softwares giving a good implementation of the standard will encourage feed reader software to do it also.
Moreover it might be simple to do, so it could be a good starter issue.

What do you think?

**Comment by rigelk** [comment]
hi @azmeuk,

PeerTube relies on https://github.com/rigelk/feed (`pfeed` on npmjs.org) to deal with MRSS. I invite you to port your issue to that repository to help it implement what the properties currently missing. Once it gets implemented there, we can care about its use in PeerTube.

---

Side note: I saw you [question the MRSS support client-side](https://linuxfr.org/users/azmeuk/journaux/mediarss-le-mal-aime) and am honestly grateful for the work you did shedding light on their issues with MRSS. Without it, implementing MRSS is done pretty much in the dark regarding its usefulness.

**Comment by rigelk** [comment]
Looking at the `<media:license>` and `<media:comments>`, the former is hard for us since we don't have a 1:1 binding between our license system and a full-text of the license. The latter would require loading comments, which could be costly (of course). @Chocobozzz wdyt?

**Comment by azmeuk** [comment]
Plus, the `<media:comment>` tag is [limited to the comment content](http://www.rssboard.org/media-rss#media-comments). There is no interesting information such as the author or the date.

**Comment by Chocobozzz** [comment]
Let's skip the `<media:comment>` tag :+1:

**Comment by azmeuk** [comment]
Thank you for your work!
