### ISSUE TITLE
Add RSS and syndication feeds

### ISSUE THREAD

**Issue by dadall** [Chocobozzz/PeerTube#23]
It could be awesome to get the content of a PT instance via a RSS feed, even better with a RSS feed per tags.

---

### Implemented in 244e76a552ef05a5067134b1065d26dd89246d8c:

- [x] instance-wide RSS feed
  - [X] json
  - [X] rss
  - [X] atom
  - [X] mrss
- [X] account-wide RSS feed
  - [X] json
  - [X] rss
  - [X] atom
  - [X] mrss

### Delayed for later implementation

- [ ] channel-wide RSS feed
  - [ ] json
  - [ ] rss
  - [ ] atom
  - [ ] mrss
- [ ] per-tag RSS feed (as seen by an instance *and* local to an instance) -> BLOCKED until #60 gets done.

**Comment by gouessej** [comment]
@dadall What about using Atom instead of RSS?

**Comment by yannicka** [comment]
Or maybe a [JSON Feed](https://jsonfeed.org/)? (in replacement or as an alternative to RSS)

**Comment by gouessej** [comment]
@yannicka Thank you, I didn't know JSON Feed.

**Comment by ReK2Fernandez** [comment]
Atom/RSS is good because most podcast players need this.. json fine but first Atom/RSS IMO

**Comment by gouessej** [comment]
@ReK2Fernandez I agree with you. I studied a bit JSON feed, it's not really standard. If I wanted to use JSON, I would rather stick to a jsonified version of Atom than a JSON format trying to imitate both RSS and Atom.

**Comment by Openmedianetwork** [comment]
This is a core feature that needs to be in ASP as it allows easy setup of home seeboxes based on a torrent app downloading all content and seeding it.
Atom/RSS and what ever... just use a standard libeary.

**Comment by rigelk** [comment]
Seems like https://github.com/jpmonette/feed and https://github.com/dylang/node-rss are the two main libraries dealing with that in Node.

**Comment by prysme01** [comment]
yes please add feed to peertube it would be great !

**Comment by qwertygc** [comment]
I'We can add a feed by account user for follow a channel.

**Comment by veretcle** [comment]
Second that, would be great to have an rss feed.

**Comment by rigelk** [comment]
Since we aim to syndicate rich multimedia content, we should maybe have a look at http://www.rssboard.org/media-rss#description

**Comment by rigelk** [comment]
I've actually ended up forking [jpmonette/feed](https://github.com/jpmonette/feed) to [rigelk/feed](https://github.com/rigelk/feed), published as [pfeed](https://www.npmjs.com/package/pfeed).

- added torrent enclosure support: https://github.com/rigelk/feed/commit/687fae94d44e45d7f2f1f016edd79f5cd9836567
- added MRSS peerLink support: https://github.com/rigelk/feed/commit/83b3e5a68e3b17d7375fa85002ad13b3ef86b5a6

**Comment by Chocobozzz** [comment]
Implemented the video channel feed: https://github.com/Chocobozzz/PeerTube/commit/e0ea4b1d550d20271a74f1b84e7b3babeec9e0b3

I don't think per-tag feed would be interesting, but if you really want it create another issue :)

**Comment by ashledombos** [comment]
Hello,

not sure if I should open a specific issue for this, and if it's appropriate, but can you please provide also some syndication feed for [peertube's blog](https://joinpeertube.org/en/news/) :) (Atom would be a better tribute to Aaron Schwartz though ;) )

**Comment by Chocobozzz** [comment]
@ashledombos Hi, I created the issue on the appropriate repository: https://framagit.org/framasoft/peertube/joinpeertube/issues/23 :)

**Comment by trymeouteh** [comment]
Please allow Peertube accounts to have a RSS feed for their own subscribe channels.

**Comment by mj-saunders** [comment]
Given that [#60](https://github.com/Chocobozzz/PeerTube/issues/60) is now dealt with, is there anything holding back implementing RSS feed for tags?

**Comment by rigelk** [comment]
@mj-saunders not that I can think of

**Comment by mj-saunders** [comment]
> Implemented the video channel feed: [e0ea4b1](https://github.com/Chocobozzz/PeerTube/commit/e0ea4b1d550d20271a74f1b84e7b3babeec9e0b3)
> 
> I don't think per-tag feed would be interesting, but if you really want it create another issue :)

Apologies for continuing this here. Have opened [#3430](https://github.com/Chocobozzz/PeerTube/issues/3430)
