### ISSUE TITLE
Automatically close hamburger menu on mobile

### ISSUE THREAD

**Issue by sanpii** [Chocobozzz/PeerTube#230]
* **PeerTube version or commit:** v0.0.13-alpha
* **Browser name/version:** firefox 57
* **NodeJS version:** 5.6.0
* **PostgreSQL version:** 10

I think (it’s just my opinion after seeing another person navigate on peertube on a mobile phone) the menu should be close automatically after selecting an item.

**Comment by Chocobozzz** [comment]
You're right :)

**Comment by Chocobozzz** [comment]
Merged in https://github.com/Chocobozzz/PeerTube/issues/233 :)
