### ISSUE TITLE
"InvalidHeaderError: bad param format" errors in peertube log when receiving activitypub messages from other instances

### ISSUE THREAD

**Issue by Lab-8916100448256** [Chocobozzz/PeerTube#2300]
**What happened?**
Since upgrade to to version 2.0.0. I see lots of "InvalidHeaderError: bad param format" errors in the log.
And I not longer see any new video from the other instances that my instance is following.
At first I though this was happening because of federated instances that had not yet upgraded to version 2.0.0 (an incompatibility is mentioned in the release notes). But this is actually happening also for nstances that have upgraded to 2.0.0

**What do you expect to happen instead?**
* No error
* New videos from federated instances showing up on my instance.

**Steps to reproduce:**
This is happening all the time on my peertube instance since the upgrade to version 2.0.0
Don't know if/how this can be reproduced on other instances.

**Additional information**
* PeerTube version or URL: https://tube.crapaud-fou.org/
* Browser name/version: N.A.
* NodeJS version: v10.17.0
* Link to browser console log if useful: N.A.
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): see attached file [syslog_peertube.log.gz](https://github.com/Chocobozzz/PeerTube/files/3916244/syslog_peertube.log.gz)

**Comment by Chocobozzz** [comment]
Do you run a reverse proxy in front of peertube?

**Comment by Lab-8916100448256** [comment]
Peertube is installed more or less as in the doc https://docs.joinpeertube.org/#/install-any-os
with a few minor (I think) changes like the install folder that is different.
nginx config : 
[nginx-peertube-config.txt](https://github.com/Chocobozzz/PeerTube/files/3916894/nginx-peertube-config.txt)

**Comment by Chocobozzz** [comment]
Try to put [proxy_pass_request_headers](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass_request_headers) to `on` before `proxy_pass` in `location /` block.

**Comment by Lab-8916100448256** [comment]
I have added the proxy_pass_request_headers : 
```
  ...
  location / {
    proxy_pass_request_headers on;
    proxy_pass http://127.0.0.1:9000;
    ...
```
and restarted everything : Errors are still there.

**Comment by Chocobozzz** [comment]
What is the output of `cat node_modules/http-signature/package.json | grep version`?

**Comment by Lab-8916100448256** [comment]
"_where": "/opt/peertube/versions/peertube-v2.0.0",
  "version": "1.3.1"

**Comment by Chocobozzz** [comment]
There is something wrong with your installation. 

Reinstall the modules: `rm -r ./node_modules && yarn install --pure-lockfile`. This module should be in version 1.2.0: https://github.com/Chocobozzz/PeerTube/blob/develop/yarn.lock#L3052

**Comment by Lab-8916100448256** [comment]
I had some errors/warnings when re-installing packages.  : 
[reinstall-node-packages.txt](https://github.com/Chocobozzz/PeerTube/files/3920760/reinstall-node-packages.txt)

After restarting peertube and waiting a little bit I do see new videos from federated instances now. :)

There are still errors in the log. But these look different than before : 
[peertube.log.gz](https://github.com/Chocobozzz/PeerTube/files/3920842/peertube.log.gz)

**Comment by Chocobozzz** [comment]
Try to re follow other instances, your issue should be fixed now.

**Comment by Lab-8916100448256** [comment]
Yes things seem to be back to normal.
Thanks a lot for your prompt support @Chocobozzz !
