### ISSUE TITLE
Not video language causes video not be shown under "local"

### ISSUE THREAD

**Issue by r4dh4l** [Chocobozzz/PeerTube#2308]
**What happened?**

The admin of my PT instance mentioned that I video I've uploaded didn't appear under "Local" (https://peertube.social/videos/local) if a video has no language selection.

**What do you expect to happen instead?**

A video without language selection should appear under "Local" as well.

**Steps to reproduce:**

1. Upload a video without setting a language for the video.
2. The video is not listed under "Local".
3. Set a language for the video.
4. The video appears under "Local".

**Additional information**
* PeerTube version or URL: https://peertube.social/
* Browser name/version: Firefox

**Comment by Chocobozzz** [comment]
What is your video URL?

**Comment by r4dh4l** [comment]
> What is your video URL?

https://peertube.social/videos/watch/e86dd44e-ade1-436c-9264-2ac0eaa0758f

**Comment by Chocobozzz** [comment]
I can see it 
![screen_2019-12-05-16:03:24](https://user-images.githubusercontent.com/5180488/70246954-d547fa80-1778-11ea-98ad-a291d6a7bf26.png)

Do you have video languages preferences?

**Comment by r4dh4l** [comment]
> I can see it

Yes, now it is visible becaue the owner of the PT instance changed the language one time to "german" and then removed it again, but before it was not visible.

> Do you have video languages preferences?

Yes, there are video language preferences.

**Comment by Nutomic** [comment]
When I noticed that the video was not shown, I had a couple of languages selected, but not "unknown language". Honestly I was surprised that there is such an option as unknown language. But with that option selected, videos without language are shown just fine. So this is not a bug, but more of a UX problem.

**Comment by Chocobozzz** [comment]
"Unset language" would be better?

**Comment by Nutomic** [comment]
Well, an option like that is not something I expect to see inside a list of languages. I think it would make more sense to turn it into a seperate checkbox, outside of that list.

**Comment by Chocobozzz** [comment]
> I think it would make more sense to turn it into a seperate checkbox, outside of that list.

I personally think we should keep this option in the select, because you explain using this select the videos you want to display regarding their language settings. This list is not only a list of languages, it's a list of the video language available settings. If your issue is not consistency, but more that you did not see the `Unknown language` entry in the select, maybe we can emphasize it using CSS.
