### ISSUE TITLE
Show count of videos next to subscribers in section "My Channels"

### ISSUE THREAD

**Issue by r4dh4l** [Chocobozzz/PeerTube#2309]
Currently "My Channels" just list the count of subscribers of a channel. Would it be possible to show the count of containing videos as well?
The is helpful for the case you want to move videos from one channel to another so you could monitor the progress of moved videos better.

Used PT instance: https://peertube.social/

**Comment by sam-cross** [comment]
Just found this issue the other day and I like the idea. If I can get the hang of PeerTube's data structures I'll work on this. Leaving it free for anyone else though in case I can't figure it out!

**Comment by sahmed007** [comment]
Hi, is this still up for grabs? If so, I'd like to work on it.

**Comment by rigelk** [comment]
@sahmed007 yes, I can assign it to you :)

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/1ba471c55fdbf05ef2c10152b3e4b0c5d8da3213

**Comment by r4dh4l** [comment]
> Implemented in 1ba471c

Thank you all! :)
