### ISSUE TITLE
About instance page

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#231]
Pretty much self-explanatory. Instances might want to present themselves or explain their admission policy, like on Mastodon instances and their about page.

I would suggest an 'About' entry in the footer or in the left menu (or both). I could be interesting to link to it on the registration page too.

**Comment by Chocobozzz** [comment]
👍 

I see two different keys:
 * `about`: instance description
 * `terms`: general terms of use


We'll put them in the settings (with the possibility to update them in the config admin panel).

**Comment by ReK2Fernandez** [comment]
Can we add to the about instance page an option to link to a mastodon server? like we host a mastodon server and a peertube server... not sure in which way or what but just something to think about...

**Comment by Chocobozzz** [comment]
I think we could accept markdown and you would just add a link inside your description.

**Comment by ReK2Fernandez** [comment]
@Chocobozzz good idea :)

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/36f9424ff192b0584a433bc196bced6fcf265808
