### ISSUE TITLE
Blacklist for auto following 

### ISSUE THREAD

**Issue by nr23730** [Chocobozzz/PeerTube#2312]
**What happened?**
I host a PeerTube instance for a while now. The feature in v2.0 to automatically follow instances on the index is very nice and really encourages federation with other instances.

As the index is not moderated there are a few instances that host content like porn or neo-nazi propaganda that I (and probably many others) won't like to show up on their instances.
Even after unfollowing those instances my instance will automatically start following those instances again.

I know that it's possible to block those instances, so that users won't see the videos but the instance will still be in my following list and my instance will be listed in the followers of the other instance.

**What do you expect to happen instead?**
What I'd like to see is an option to exclude certain instances from the auto following process. This would ideally be something like a regex that also allows to block keywords like _porn_ or _xxx_.

**Comment by n76** [comment]
I was just going to submit an issue on this. . . There is already one so I'd to add my opinion that this should be high priority.

Not sure about a list regex, though that could work. I was thinking of a list of banned instances so my work flow would be something like:
1. Auto follow.
2. Periodically check my notifications for newly followed instances.
3. Check those instances for suitability by my own criteria.
4. If I decide to drop them from my following, have an option to simultaneously add them to a block list so they do not get auto followed again.

**Comment by Chocobozzz** [comment]
Hello,

Since we improved the auto following feature so you can use a custom index/raw json file maintained by anybody, and we clean up the peertube public index (posteriori moderation) we don't plan to implement this feature.
