### ISSUE TITLE
npm ERR! Failed at the peertube@2.0.0 start script - 502 Bad Gateway

### ISSUE THREAD

**Issue by rpifreng** [Chocobozzz/PeerTube#2318]
Hi. just after a fresh install, i launch  'systemctl start peertube'
I have "502 Bad Gateway"

**What happened?**
Failed at the peertube@2.0.0 start script

**What do you expect to happen instead?**
hmm... Success ?  ^^

Here are the logs:

`journalctl -feu peertube`

déc. 09 23:54:04 debian systemd[1]: peertube.service: Main process exited, code=exited, status=255/EXCEPTION
déc. 09 23:54:04 debian systemd[1]: peertube.service: Failed with result 'exit-code'.
déc. 09 23:54:05 debian systemd[1]: peertube.service: Service RestartSec=100ms expired, scheduling restart.
déc. 09 23:54:05 debian systemd[1]: peertube.service: Scheduled restart job, restart counter is at 30.
déc. 09 23:54:05 debian systemd[1]: Stopped PeerTube daemon.
déc. 09 23:54:05 debian systemd[1]: Started PeerTube daemon.
déc. 09 23:54:06 debian peertube[13613]: > peertube@2.0.0 start /var/www/peertube/versions/peertube-v2.0.0
déc. 09 23:54:06 debian peertube[13613]: > node dist/server
déc. 09 23:54:08 debian peertube[13613]: npm ERR! code ELIFECYCLE
déc. 09 23:54:08 debian peertube[13613]: npm ERR! errno 255
déc. 09 23:54:08 debian peertube[13613]: npm ERR! peertube@2.0.0 start: `node dist/server`
déc. 09 23:54:08 debian peertube[13613]: npm ERR! Exit status 255
déc. 09 23:54:08 debian peertube[13613]: npm ERR!
déc. 09 23:54:08 debian peertube[13613]: npm ERR! Failed at the peertube@2.0.0 start script.
déc. 09 23:54:08 debian peertube[13613]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
déc. 09 23:54:09 debian peertube[13613]: npm ERR! A complete log of this run can be found in:
déc. 09 23:54:09 debian peertube[13613]: npm ERR!     /var/www/peertube/.npm/_logs/2019-12-09T22_55_24_810Z-debug.log

`cat /var/www/peertube/.npm/_logs/2019-12-09T22_55_24_810Z-debug.log`

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.11.3
3 info using node@v10.17.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle peertube@2.0.0~prestart: peertube@2.0.0
6 info lifecycle peertube@2.0.0~start: peertube@2.0.0
7 verbose lifecycle peertube@2.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle peertube@2.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/peertube/versions/peertube-v2.0.0/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle peertube@2.0.0~start: CWD: /var/www/peertube/versions/peertube-v2.0.0
10 silly lifecycle peertube@2.0.0~start: Args: [ '-c', 'node dist/server' ]
11 silly lifecycle peertube@2.0.0~start: Returned: code: 255  signal: null
12 info lifecycle peertube@2.0.0~start: Failed to exec start script
13 verbose stack Error: peertube@2.0.0 start: `node dist/server`
13 verbose stack Exit status 255
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid peertube@2.0.0
15 verbose cwd /var/www/peertube/versions/peertube-v2.0.0
16 verbose Linux 4.19.0-6-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.17.0
19 verbose npm  v6.11.3
20 error code ELIFECYCLE
21 error errno 255
22 error peertube@2.0.0 start: `node dist/server`
22 error Exit status 255
23 error Failed at the peertube@2.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 255, true ]

**Additional information**
* Debian Buster amd64 (Install from Official .iso netinstall and up to date)
* PeerTube version or URL: LATEST version 2.0.0 - URL private (dev only for the moment On VirtualBox)
* https - and Domain OK
* Browser name/version: Firefox Developer 72.0b4 (64 bits)
* NodeJS version: v10.17.0
*  which npm: /usr/bin/npm
* yarn version 1.19.2

_PS: j'écris en anglais, mais il me semble que tu es français si je ne me trompe pas._
Merci d'avance

**Comment by Chocobozzz** [comment]
Run `cd /var/www/peertube/peertube-latest && NODE_ENV=production NODE_CONFIG_DIR=/var/www/peertube/config node dist/server` and paste the output please

**Comment by rpifreng** [comment]
`cd /var/www/peertube/peertube-latest && NODE_ENV=production NODE_CONFIG_DIR=/var/www/peertube/config node dist/server`

nothing happen

`cd /var/www/peertube/peertube-latest && NODE_ENV=production NODE_CONFIG_DIR=/var/www/peertube/config node dist/server | tee log_node`
`ls`
client	CREDITS.md  FAQ.md   log_node	   package.json  scripts  tsconfig.json
config	dist	    LICENSE  node_modules  README.md	 support  yarn.lock
`cat log_node`

 nothing...

**Comment by Chocobozzz** [comment]
What do you mean by nothing happens? The process exits? Or gets stuck?

**Comment by rpifreng** [comment]
I mean, it doesn't change anything.
As root or user, here is the screenshot:

![](https://framapic.org/MceHpIkFm9fW/KSTWtyEIRP7f)

**Comment by Chocobozzz** [comment]
How do you connect into your VM terminal? I had this "non output" error once using docker with an non-interactive shell.

Also, can you paste the output of `echo $?` so I can see what is the exit code returned by the node process?

**Comment by rpifreng** [comment]
**All right, forget it, don't worry about it.**
When I read your open and closed issues, I find that I am the only one with this problem,
and therefore **I conclude that the problem comes from me and that Peertube is not for me.**
I give up the idea of wanting to install my instance, I've been on the setup for a week now, and after 6 attempts I always find myself with the same problem.

So I'm dropping the case. Good luck for the future...
