### ISSUE TITLE
Publish a new release? (2.0.1)

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#2319]
I would like to get the benefits of this commit 47f6cb31d78f83d5734b11285b11147b0b42e191, which changes the way the notifications are sent (everyone are sent an individual mail instead of a mail with everyone in CC). It is important enough for a new patch release (if you agree on this).

Thanks! :)
Florent

**Comment by Chocobozzz** [comment]
We don't plan to release a 2.0.1 version of PeerTube. You can patch your instance by replacing the `dist/server/lib/emailer.js` file with [emailer.js.zip](https://github.com/Chocobozzz/PeerTube/files/3972356/emailer.js.zip)
