### ISSUE TITLE
New design tweaks, consistency, alignment (can someone PR this?)

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2320]
I'm not a programmer so I can't PR this myself, but hopefully someone who likes this will submit a PR.
![peertube1](https://user-images.githubusercontent.com/57924087/70530289-3b5ac600-1b5b-11ea-864e-0c1ebb80d6f7.png)

Changelog:
- reworked Upload button (top right corner)
- the search box aligned up with the videos:
![aligned](https://user-images.githubusercontent.com/57924087/70530860-74476a80-1b5c-11ea-9ada-751ded41bb68.png)
- Magnifying Glass icon (from the search box) got a new (softer) color
- Left sidebar has consistent menus and submenus, a few icons got changed

Two other color variations:
![peertube2](https://user-images.githubusercontent.com/57924087/70531121-f59efd00-1b5c-11ea-90a2-300baff6d5e2.png)
and
![peertube3](https://user-images.githubusercontent.com/57924087/70531128-fa63b100-1b5c-11ea-8d68-9aa85b971b33.png)

I got the icons from this place https://icons8.com/line-awesome?search=login

Two more variations without the ACCOUNT menu:
- [1](https://user-images.githubusercontent.com/57924087/70532231-4c0d3b00-1b5f-11ea-8517-00a8960e70ff.png)
- [2](https://user-images.githubusercontent.com/57924087/70532025-d903c480-1b5e-11ea-9a06-d0cb966cb615.png)

Another idea would be to group Language and Keyboard shortcuts into a single submenu called Settings.

Also, as discussed here https://github.com/Chocobozzz/PeerTube/issues/2338#event-2882709463 we need to remove the orange underlines from all words that have them, such as: "comments", "Local videos" (when clicking on Local videos) etc.

**Comment by rigelk** [comment]
Some of the modifications suggested (the orange underlines in the video listings and watch view) were implemented.

I think the other changes are enough a question of taste to have their place as a theme rather than mainline - thus closing the issue.
