### ISSUE TITLE
Escaping problem in plugin search

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2322]
**What happened?**

When searching a plugin, we've got:

`2 results for "<x id="INTERPOLATION_1" equiv-text="logo"/>" `

![image](https://user-images.githubusercontent.com/38844060/70563382-67dc0580-1b8e-11ea-80aa-74035278fead.png)

**Additional information**
* PeerTube version or URL: 2.0.0

**Comment by Chocobozzz** [comment]
Thanks for the issue, but it's already fixed in the latest develop 
![screen_2019-12-11-09:05:14](https://user-images.githubusercontent.com/5180488/70602749-672a8a00-1bf5-11ea-8a5a-bec3bf4672bb.png)

**Comment by JohnXLivingston** [comment]
Oops, sorry!
