### ISSUE TITLE
can't add mkv files

### ISSUE THREAD

**Issue by sokoow** [Chocobozzz/PeerTube#2327]
**What happened?**

I'm getting this when tryingto upload .mkv file:

```

debug: [peertube.company.org:443] Checking videosAdd parameters 
{ parameters: 
   { name: 'test',
     category: '1',
     nsfw: 'false',
     licence: '1',
     language: '1',
     description: 'test' },
  files: 
   { videofile: 
      [ { fieldname: 'videofile',
          originalname: 'wrongside.mkv',
          encoding: '7bit',
          mimetype: 'video/x-matroska',
          destination: '/home/peertube_user/PeerTube/videos/',
          filename: 'ac10fbd77eada7fe4f5a916d902eb6c3.',
          path: '/home/peertube_user/PeerTube/videos/ac10fbd77eada7fe4f5a916d902eb6c3.',
          size: 81815996 } ] } }
warn: [peertube.company.orgl:443] Incorrect request parameters 
{ path: '/api/v1/videos',
  err: 
   [ { param: 'videofile',
       msg: 'Should have a valid file',
       value: undefined } ] }
```

fun fact is that I can see uploaded file in my data/video dir, and I have transcoding enabled. 

**What do you expect to happen instead?**

Video either starting transcoding, or upload to succeed.

**Steps to reproduce:**

Install recent peertube from helm chart.

**Additional information**
* PeerTube version or URL: latest docker image
* Browser name/version: chrome latest

**Comment by Chocobozzz** [comment]
> PeerTube version or URL: latest docker image

Please provide your instance URL or your instance version (in the footer)

**Comment by sokoow** [comment]
I'm using chocobozzz/peertube:latest, it says ... PeerTube - CopyLeft 2015-2017 :/ Thanks for quick reply btw :)

**Comment by Chocobozzz** [comment]
We don't have such image: https://hub.docker.com/r/chocobozzz/peertube/tags. You container is very old. Try `chocobozzz/peertube:production-stretch`

**Comment by sokoow** [comment]
Yeah, noticed that lol :) thanks
