### ISSUE TITLE
Playback controls pause when a mouse button is released over the video

### ISSUE THREAD

**Issue by Fidgetcetera** [Chocobozzz/PeerTube#2328]
**What happened?**
When clicking and holding the left or middle mouse button anywhere on the page, the click registers when released if the cursor is over the player.

**What do you expect to happen instead?**
Only to play/pause a video when the click is both pressed down and released over the video.

**Steps to reproduce:**

1. Hold left or middle mouse button anywhere outside the video (eg, selecting the title text of the video to copy it, or using middle mouse button scrolling)

2. Move cursor over the video player

3. Release mouse button

**Additional information**
* PeerTube version or URL: dialup.express, 2.0
* Browser name/version: Firefox 70.0.1
* NodeJS version: ?

* Link to browser console log if useful: n/a
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): n/a

**Comment by Chocobozzz** [comment]
I think it's a videojs "bug"

**Comment by Chocobozzz** [comment]
See https://github.com/videojs/video.js/issues/4346
