### ISSUE TITLE
How long does Peertube store user's IP addresses?

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#2329]
I didnt find any documentation about this, so I am asking here. It is clear that Peertube is storing the IP addresses of users, at least in the webtorrent tracker and as a way to calculate video views. But I would like to know if these IPs are stored forever, or if they are deleted after some time. And if so, how long is that time?

**Comment by Chocobozzz** [comment]
* They are stored in the tracker memory as long as the user is connected to it.
 * They are stored in Redis memory/storage for video views during ~ 1 hour
 * They are stored in the log file during an undetermined amount of time (peertube keeps the last 20 log files and then rotates them)

**Comment by Nutomic** [comment]
Thanks! But on my instance, I'm seeing more than 100 log files, going back as far as May. Is there any chance we can get a config option to limit the number of log files?

**Comment by bootlicker** [comment]
oh!

my quick kludge that i would implement would be a cron job to run a bash
script to just... delete the logs once certain conditions are met, lol

**Comment by Nutomic** [comment]
Actually, Peertube also logs to stdout (going to journalctl or docker logs). So I think the only way to solve this is a config option to anonymize logs in Peertube. See #2335.

**Comment by bootlicker** [comment]
ffwhoa i would have done that differently...

**Comment by Chocobozzz** [comment]
> Thanks! But on my instance, I'm seeing more than 100 log files, going back as far as May.

Weird, but I know winston (our logger library) had some bugs. I would suggest to remove all log files to fix this.

>  Is there any chance we can get a config option to limit the number of log files?

Yes, please create a dedicated issue.
