### ISSUE TITLE
Better mobile version

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#233]
- [x] Thumbnails take all the width
  - [ ] Dedicated search component
  - [x] Menu takes all the width
  - [x] Close menu when clicking on a link

Demo video (by Olivier Massain): https://peertube2.cpy.re/videos/watch/d107698e-b473-4134-b491-24710e6e7b30

**Comment by Chocobozzz** [comment]
Videos list improvement mockup (see https://github.com/Chocobozzz/PeerTube/issues/509#issuecomment-416980798) by @mattcoxonline

![alt](https://user-images.githubusercontent.com/673542/44795449-fe0f3680-abaa-11e8-9d8b-0871f52e6dd4.png)

**Comment by aschaap** [comment]
Is full-screen search as pictured in the linked video (screenshotted below for convenience) still desired? I noticed there is a dropdown that asks whether to search this instance or on Sepia Search.

And I assume full-width thumbnails are not desirable in "My Library" -> "Videos" ?

![fullscreen-search](https://user-images.githubusercontent.com/8865084/113890582-48f57f80-9792-11eb-8d6c-922daf3fdae8.png)

**Comment by Chocobozzz** [comment]
I think we can close this outdated issue, and rework on a better mobile version for specific pages/components in dedicated issues.
