### ISSUE TITLE
Migration 0450 is too slow to do all at once

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#2331]
I'm trying to update a server that uses HLS to Peertube 2.0.0 and this migration 0450 is hashing every HLS file before the server can start. This equates to significant downtime with no warning.

**Comment by scanlime** [comment]
fwiw, torrent hashing in general is much too slow to do at server startup on a sizeable server. It would help a lot if this could be a deferred background task, especially if it can use multiple CPU cores.

On my server this has been going for about 5.5 hours and it is at file 2716 out of 4688.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/907b8f9347cca117c77a83cbea27140a10e3311e
