### ISSUE TITLE
New HLS torrent files use incorrect server URL

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#2332]
I'm updating diode.zone to Peertube 2.0.0 and the migration 0450 which is taking ages to create new HLS torrents also seems to be producing incorrect output.

The new HLS torrents have a URL like:

https://diode.zone/var/www/peertube/storage/streaming-playlists/hls/67a78705-240c-48cd-877a-eb1086eadef2/67a78705-240c-48cd-877a-eb1086eadef2-720-fragmented.mp4

By contrast, the normal webtorrent URLs are like:

https://diode.zone/static/webseed/68840bf4-a62b-43ed-96e5-1363895e0b4b-720.mp4

Please advise. I plan to let the migration finish but it is taking a long time and the results do not appear to be usable.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/907b8f9347cca117c77a83cbea27140a10e3311e

> Please advise.

We'll advise this in the changelog, as we have been doing since the beginning.
