### ISSUE TITLE
Server startup fails with actor_preferred_username SequelizeUniqueConstraintError

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#2333]
During the update to 2.0.0 the server entered an error/restart loop, each time failing to insert the actor_preferred_username index. In my case there was a user and a channel with the same preferredUsername.

I was in a hurry to get the server back up so I used psql to rename the group to something trivially different, but I suspect this leaves the channel broken from the activitypub side, please advise how this should be fixed and how we could prevent this error on other servers.

**Comment by Chocobozzz** [comment]
When you update from the develop branch, I suggest you to read the commits: https://github.com/Chocobozzz/PeerTube/commit/77e0851758595de2642b405cff8960f02ced60eb

I'll delay this index for PT 2.2, and communicate about this for the PT 2.1 release: https://github.com/Chocobozzz/PeerTube/commit/458218d2baf286835754c666cfc635cce467c24e
