### ISSUE TITLE
Config Option to anonymize IP addresses in logs

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#2335]
Followup for #2329. As mentioned there, user's IP addresses are stored in Peertube logs, and these are also saved by journalctl, docker or other tools depending on the setup. Deleting all these logs can be complicated, and might not be desired because getting error information becomes more complicated.

One alternative might be to pass anonymized IP addresses to Peertube, but that will break the torrent tracker and the view counter. So doing it inside Peertube is the only real option. 

I propose to handle this by setting the last part of the IP address to zero, eg `1.2.3.4` becomes `1.2.3.0`.

**Comment by rigelk** [comment]
@Nutomic it is already something that I implemented, albeit only when a request declares DNT. It should be trivial for you to add this option. see https://github.com/Chocobozzz/PeerTube/blob/907b8f9347cca117c77a83cbea27140a10e3311e/server.ts#L144-L157

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/2f6b5e2d6ebcac88d9005ea2654ffa77907d5db2

**Comment by Nutomic** [comment]
That was really fast, thanks!
