### ISSUE TITLE
The --since option of peertube-import-videos.js should prefilter videos information to fetch

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#2337]
The --since option of peertube-import-videos.js should take advantage of youtube-dl option `--datebefore DATE` and `--dateafter DATE` in order to limit information requests from youtube. This should make the script a lot faster with this option.

https://github.com/ytdl-org/youtube-dl

I may make a pull request soon for this. I need it for automatic youtube channel synchronization.

Florent

**Comment by drzraf** [comment]
AFAICT, `--datebefore DATE` and `--dateafter DATE` do **not** prefilter **Youtube** videos because YT channels do not provide this information.
Eg: `youtube-dl -j --flat-playlist https://www.youtube.com/channel/` does not provide the `upload_date` information.

**Comment by fflorent** [comment]
Yup, I also discovered that. I guess we should close the issue, unfortunately I don't know if we can solve the need.
