### ISSUE TITLE
Show the number of comments each video has and remove the orange underline from the word "comments"

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2338]
The end result:
![11](https://user-images.githubusercontent.com/57924087/70825289-bf77ac80-1dec-11ea-98a6-5a1602002ad2.png)
or
![12](https://user-images.githubusercontent.com/57924087/70819424-e62ee680-1dde-11ea-8084-bd4198d71a89.png)

If there are no comments, what and how should we display?

**Comment by rigelk** [comment]
The orange bar is a global style for elements bearing the `.title-page` class - a kind of section header of sorts. Since it affects all sections, I guess the idea to remove orange bars needs more thought than just making the comment section header an exception.

**Comment by DontUseGithub** [comment]
> I left aside the orange bar change: the orange bar is a global style for elements bearing the `.title-page` class - a kind of section header of sorts. Since it affects all sections, I guess the idea to remove orange bars needs more thought than just making the comment section header an exception.

Thank you. Yeah I understand. "The orange" issue could maybe be addressed when this issue will be solved https://github.com/Chocobozzz/PeerTube/issues/2320 - it also involves some theme tweaking.
