### ISSUE TITLE
docker instance cannot follow any other server:  Error: Cannot fetch remote actor

### ISSUE THREAD

**Issue by holywen** [Chocobozzz/PeerTube#2339]
**What happened?**
Docker installation instance cannot follow any other server, but it can be followed by other servers.

**What do you expect to happen instead?**
it should be able to follow other servers.

**Steps to reproduce:**

1.create a docker instance according to : https://docs.joinpeertube.org/#/install-docker

2. in adminsitration->manage follows, add new host to follow

3. get error messages in administration->system->logs
`peertube_1       | [peertube.globetvs.cn:443] 2019-12-14 09:52:59.113 info: Processing ActivityPub follow in job 8.
peertube_1       | [peertube.globetvs.cn:443] 2019-12-14 09:53:00.150 info: Fetching remote actor https://p0.pm/accounts/peertube.
peertube_1       | [peertube.globetvs.cn:443] 2019-12-14 09:53:01.296 error: Cannot execute job 8 in queue activitypub-follow. {
peertube_1       |   "payload": {
peertube_1       |     "host": "p0.pm:443",
peertube_1       |     "name": "peertube",
peertube_1       |     "followerActorId": 1
peertube_1       |   },
peertube_1       |   "err": {
peertube_1       |     "stack": "Error: Cannot fetch remote actor https://p0.pm/accounts/peertube\n    at Object.<anonymous> (/app/dist/server/lib/activitypub/actor.js:58:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/dist/server/lib/activitypub/actor.js:4:58)\n    at <anonymous>",
peertube_1       |     "message": "Cannot fetch remote actor https://p0.pm/accounts/peertube"
peertube_1       |   }
peertube_1       | }`

but actually when I run "curl -vvv https://p0.pm/accounts/peertube" in the docker container, it worked.
 
**Additional information**
* PeerTube version or URL: 2.0.0
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful: 
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by holywen** [comment]
peertube.log:

`{"level":"info","message":"Fetching remote actor https://p0.pm/accounts/peertube.","label":"peertube.globetvs.cn:443","timestamp":"2019-12-14T14:05:11.220Z"}
{"level":"error","message":"Cannot execute job 10 in queue activitypub-follow.","label":"peertube.globetvs.cn:443","payload":{"host":"p0.pm:443","name":"peertube","followerActorId":1},"err":{"stack":"Error: Cannot fetch remote actor https://p0.pm/accounts/peertube\n    at Object.<anonymous> (/app/dist/server/lib/activitypub/actor.js:58:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/dist/server/lib/activitypub/actor.js:4:58)\n    at <anonymous>","message":"Cannot fetch remote actor https://p0.pm/accounts/peertube"},"timestamp":"2019-12-14T14:05:13.886Z"}




{"level":"info","message":"Processing ActivityPub follow in job 9.","label":"peertube.globetvs.cn:443","timestamp":"2019-12-14T14:05:46.965Z"}
{"level":"info","message":"Fetching remote actor https://videos.globetvs.com/accounts/peertube.","label":"peertube.globetvs.cn:443","timestamp":"2019-12-14T14:05:47.980Z"}
{"level":"error","message":"Cannot execute job 9 in queue activitypub-follow.","label":"peertube.globetvs.cn:443","payload":{"host":"videos.globetvs.com:443","name":"peertube","followerActorId":1},"err":{"stack":"Error: Cannot fetch remote actor https://videos.globetvs.com/accounts/peertube\n    at Object.<anonymous> (/app/dist/server/lib/activitypub/actor.js:58:23)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/dist/server/lib/activitypub/actor.js:4:58)\n    at <anonymous>","message":"Cannot fetch remote actor https://videos.globetvs.com/accounts/peertube"},"timestamp":"2019-12-14T14:05:49.112Z"}`

**Comment by holywen** [comment]
docker -v
Docker version 19.03.5, build 633a0ea838

 docker-compose  -v
docker-compose version 1.25.1-rc1, build d92e9bee

**Comment by Chocobozzz** [comment]
Hi,

What is your instance URL? Because I can't get peertube.globetvs.cn

**Comment by holywen** [comment]
Just started it, and you can access it with user test/test123

**Comment by Chocobozzz** [comment]
Your instance is running an old PeerTube version (1.3). Please use the latest (2.0)

**Comment by Chocobozzz** [comment]
Use `docker-compose pull` to update your image

**Comment by holywen** [comment]
Thanks I finally find out that it's because of I used a docker image mirror which cached an old version of the image.
