### ISSUE TITLE
"Unknown Error" on unstable Connection

### ISSUE THREAD

**Issue by tilllt** [Chocobozzz/PeerTube#2344]
**What happened?**
 "Error / Unknown Error" message pops up while browsing my Peertube instance on an unstable network connection (aka internet on the subway in Germany). Seems like the infinite scrolling immediately throws an error when receiving no data.

**What do you expect to happen instead?**
Either the error should be more specific i.e. "Error receiving additional data, try again later." and / or the timeout should be longer to avoid this message in the first place. The problem is that a big red dialog with "Error! Unknown Error!" could come across as a serious problem while in reality it is no problem at all.

**Steps to reproduce:**

1. Establish shitty unstable network connection

2. Browse peertube

3.error message

**Additional information**
* PeerTube version or URL:
Docker with stretch-production
* Browser name/version:
Chrome on Android

**Comment by Chocobozzz** [comment]
Thanks, should be better with https://github.com/Chocobozzz/PeerTube/commit/f27a885a4368776ffb8158c917c6e3f3d21ef670
