### ISSUE TITLE
npm run setup:cli errors aka server/tools omitted from tarball

### ISSUE THREAD

**Issue by drzraf** [Chocobozzz/PeerTube#2347]
**What happened?**

`peertube-v2.0.0/scripts/setup/cli.sh: 10: cd: can't cd to ./server/tools`

**What do you expect to happen instead?**

tools installed

**Steps to reproduce:**

1. `npm run setup:cli`

**Additional information**
* PeerTube version or URL: 2.0.0
* NodeJS version: v10.18.0

**Other**

Commenting the script:
```sh
set -eu

NOCLIENT=1 yarn install --pure-lockfile

# Why? It does not exist (not part of the tarball)
rm -rf ./dist/server/tools/

(
   # This does not exist (not part of the tarball)
    cd ./server/tools
    yarn install --pure-lockfile
)

# This does not exist. But does at the root directory.
npm run tsc -- --build ./server/tools/tsconfig.json
cp -r "./server/tools/node_modules" "./dist/server/tools"
cp "./tsconfig.json" "./dist"
```

**Comment by Chocobozzz** [comment]
Please follow the guide: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#installation

You need to clone the peertube repository first (and not use the release tarball)

**Comment by drzraf** [comment]
But import-tools are useful for users of the tarball tool. Providing a separate tarball/binary/bundle for the tools would be a nice alternative.

**Comment by Chocobozzz** [comment]
> Providing a separate tarball/binary/bundle for the tools would be a nice alternative.

Yes, but providing tarball is not as simple than doing a `git pull` to update the tools + it requires more work for maintainers. It's the reason why we chose to use git for this particular purpose.

**Comment by drzraf** [comment]
I a separate tarball is not possible (although I still think it's "just" a matter of webpack outputs), at least providing compiled tools in the release could be done?
See also above (probable dup') report.

**Comment by rigelk** [comment]
> I a separate tarball is not possible (although I still think it's "just" a matter of webpack outputs), at least providing compiled tools in the release could be done?

The tarballs are not generated via webpack, but via https://github.com/Chocobozzz/PeerTube/blob/develop/scripts/release.sh

**Comment by drzraf** [comment]
`release.sh` does not exclude `dist/server/tools` explicitly. As such, this should be included as there is a mention of [dist](./scripts/release.sh#L79)

Maybe the directory has been removed by a run of `npm run setup:cli` or `npm run dev:cli` by the time `release.sh` is executed?
