### ISSUE TITLE
when importing, publishedAt should be set to originalPublishedAt

### ISSUE THREAD

**Issue by drzraf** [Chocobozzz/PeerTube#2348]
**What happened?**

All videos appear to be published `some minutes ago` on the channel page.

**What do you expect to happen instead?**

Videos get the exact same set of metadata
 
**Steps to reproduce:**

1. import a Youtube channel using `node dist/server/tools/peertube-import-videos.js `

**Additional information**
* PeerTube version or URL: 2.0.0

**Others**
Import is currently the narrowest features to real `mirroring`. And also extra-metadata can be used to keep track of original source/channel, I think that most if not all "standard" metadata should be copied over as-is. In particular the `published date`. That's what users expect.

**Comment by drzraf** [comment]
/edit I saw that even the metadata API does not offer a way to change the published date. Even though I maintain the suggestion in the OP, at least a workaround could be to `display` and `sort` the channel by `originalPublishedAt`.

**Comment by Chocobozzz** [comment]
The published date is automatically set by peertube, and cannot be updated by the users so we have a reliable attribute. We added `originalPublishedAt` to not lose the original publication date information. You can filter with this attribute in the search page

**Comment by frankstrater** [comment]
The Peertube API offers a way to change the `originalPublishedAt` by placing a PUT on the imported video. It's a workaround and needs an extra API call, but it works. See this Python example script at:

https://github.com/beeldengeluid/peertube-docs/blob/master/api/videos-imports.py

lines 138- 153

**Comment by drzraf** [comment]
But the `originalPublishedAt` which is what is actually useful when importing, is not used in the UI.
Neither on the channel/trending pages. I'd expect a channel's option to use it a the first choice (and use `publishedAt` as a default)

**Comment by Chocobozzz** [comment]
I think there is a UI/UX addition that could be made so users can change the sort of some videos pages (channels videos, local videos...). Ping @rigelk

**Comment by Chocobozzz** [comment]
I added ability to sort by `originallyPublishedAt` in https://github.com/Chocobozzz/PeerTube/commit/2fd59d7d89d1c389446ee67838c821e2622fc8ca

A plugin can hook the videos list sort API call to replace `publishedAt` by `originallyPublishedAt` if your want

**Comment by kontrollanten** [comment]
I've created a plugin for this; [peertube-plugin-sort-originally-published-at](https://framagit.org/kontrollanten/peertube-plugin-sort-originally-published-at) PeerTube package repository should've indexed it within 24 hours.
