### ISSUE TITLE
Convert 50fps videos to 25fps instead of 30fps

### ISSUE THREAD

**Issue by jean-emmanuel** [Chocobozzz/PeerTube#2350]
Converting 50fps videos to 30fps produces a jerky result. This could be avoided by setting the fps limit for low resolutions to 25fps is this case. What do you think ?

**Comment by Chocobozzz** [comment]
Could you send a problematic video so I can reproduce and apply a fix please?

**Comment by jean-emmanuel** [comment]
Thanks for getting back to me on this ! Here is the video that made me spot the issue, it's especially noticeable on slow motion shots:  https://videos.domainepublic.net/videos/watch/ae6690a9-08d2-4743-99a9-8961ec3ae924

**Comment by rigelk** [comment]
@jean-emmanuel what makes you think reducing the fps will yield a video with less distortion?

**Comment by jean-emmanuel** [comment]
Say we have a 50fps shot played at 50% speed in our video. At 50 fps, the result look like this:
`AABBCCDDEEFFGGHH` (where each letter represent a frame)
The frame distribution is even, the result is smooth.

Converted to 25 fps, the video would look like this:
`ABCDEFGH`
The frame distribution is even, the result is smooth.

At 30fps however, we end up with a mix of single frames and double frames, something like:
`ABCCDEFGHH`
That's probably not the exact frame distribution, but you see the idea : it's uneven and thus yields a jerking result.

**Comment by tilllt** [comment]
Is Peertube the Framerates of Videos at all? If a 50fps video is transcoded to 30fps without any very specific reason (i.e. to be played back on NTSC equipment) from a video engineering perspective, this is an error. not desirable behaviour. 30 fps has no place in Europes TV standards. 30fps is an NTSC thing which is relevant in Japan and the US.

**Comment by jean-emmanuel** [comment]
I think converting 60fps to 30fps (and 50 to 25) is relevant for lower end devices & slow bandwidth situations.

**Comment by tilllt** [comment]
You can absolutely convert 60 to 30fps and 50 to 25fps (or with a slight speed change even 24fps) but unless you have a very specific reason you don't convert 60 to 25fps.

**Comment by jean-emmanuel** [comment]
Agree, but converting 60 to 25 fps has not been suggested here.

**Comment by rigelk** [comment]
@jean-emmanuel we are already capping fps to 30 for resolutions below 720

**Comment by jean-emmanuel** [comment]
Yes, and that's an issue when the original video is at 50fps, as described above.

**Comment by tilllt** [comment]
@jean-emmanuel quoting you: "Converting 50fps videos to 30fps produces a jerky result. This could be avoided by setting the fps limit for low resolutions to 25fps is this case. "

that sure does sound as if you saw peertube doing exactly that. or i dont get your point ;)

**Comment by jean-emmanuel** [comment]
Sorry if I didn't make my point clear, I'll try to sum it up here: Peertube _does_ currently convert 50fps videos as well as 60fps videos to 30fps below 720p. While converting 60fps to 30fps is fine, converting 50 to 25 is problematic. This could be fixed by setting the fps limit below 720p to 25fps instead of 30fps **if** the original video is at 50fps.

**Comment by tilllt** [comment]
So it DOES convert 50fps to 30fps? Independently of any "limit" in fps, framerates should NEVER be transcoded to an uneven divisions, thats not how video works.

**Comment by rigelk** [comment]
@jean-emmanuel @tilllt is having a denominator more important than being strictly 25/30fps? I'm inclined to think so. To support any source fps, that would translate in `while (not below/equal 30fps) { divide fps by 2 }`.

**Comment by tilllt** [comment]
Also depends on what the player is technically capable of playing back. Theoretically a video can have any framrate, including 12fps or 17fps, in practice a lot of players will just play back the standardized framerates, being 24/25/29.79/30/50/60fps

**Comment by rigelk** [comment]
@tilllt do you mean support for a non-standard framewerate is browser-dependent, platform-dependent, or something PeerTube-dependent (like [videojs](https://videojs.com))?

**Comment by tilllt** [comment]
It might even be codec dependent, but I don't know the h264 specs by heart. The "industry standard" intermediate codecs (prores and dnxhd) allow all framerates. But EVEN if the codec specs allow it, the playback implementation (playback codec and / or player) do not necessarily support non standard framerates. Afaik YouTube and Vimeo conform everything to one of the standard framerates

**Comment by tilllt** [comment]
Since the different browsers use different codec implementations I think that's not a trivial task to research...

**Comment by tilllt** [comment]
I think if it was my decision I would just reject non standard framerates instead of Transcoding them into something which potentially looks shitty. There are plenty of free & open source video Transcoding tools so I think people should be able to get their framerates right.

**Comment by rigelk** [comment]
@tilllt thank you for the precisions. I went for 24, 25, and 30 fps as possible framerates since they seem to be the most standard.

**Comment by tilllt** [comment]
I guess its reasonable to just support 24 / 25 / 30 fps (although 50p and 60p are regular HD standard framerates) the question is rather how to deal with a non standard upload. Reject it and tell the user to convert it to a supported framerate or forcefully transcode it. I'd rather reject it and tell the users that the video needs to have 24, 25 or 30fps and let them handle the conversion themselves.

**Comment by jean-emmanuel** [comment]
Great ! Thank you for the PR @rigelk
