### ISSUE TITLE
Scenarios for web browsers without JavaScript 

### ISSUE THREAD

**Issue by githubgnulinux** [Chocobozzz/PeerTube#2351]
Please advise how to contribute for a version without ecmascript.
Scenario
Subscribe to atom feed (e.g. https://peertube.social/feeds/videos.atom?sort=-trending) via newsreader (e.g. newsbeuter)
Open feed via text-mode web browser (e.g. lynx)
Open video hyperlinks from lynx using 'mpv'

**Comment by rigelk** [comment]
Third party clients like [Thorium](https://github.com/sschueller/peertube-android) typically make use of our API: https://docs.joinpeertube.org/api-rest-reference.html. We will not build an extra interface. The beauty of the JavaScript-based web UI is that it reuses the same API as all other apps, so things don't need to implemented multiple times in JS (server-side, client-side).

We'll add them to a page similar to https://joinmastodon.org/apps and advertise it from the noscript message.
