### ISSUE TITLE
Support text not consistent with  advanced page text to update

### ISSUE THREAD

**Issue by cr1ptal** [Chocobozzz/PeerTube#2352]
**What happened?**
I updated the support text on one of my channels. The support texts for already up videos did not update - that can be a design choice. Nonetheless, there is an inconsistency regarding the text displayed in support pop-up and the text displayed in the advanced page text to update.

**What do you expect to happen instead?**
There are two options. Or the already updated support text is overridden. Or there is a warning message displayed specifying the text was reloaded from the new channel text and it will override the old support text. Without a message, it is no very clear what has changed.

**Steps to reproduce:**
1) Have a channel with published videos in, having advanced support text saved.
2) Update the channel's support text
3) Update the metadata of a video, the new channel support text is silently replaced in the advance page.

**Additional information**
* PeerTube version or URL: v2.0.0
* Browser name/version: Firefox 71.0 Linux
* NodeJS version: ?

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
I don't understand. If a support text is already set in an old video, we won't replace it in the advanced tab. For example, you could have set a custom support text for a particular video.

But there is a checkbox in the video channel update form so you can bulk update the support text of old videos.

**Comment by cr1ptal** [comment]
I didn't notice the bulk update checkbox. Nonetheless, it appears unnatural to me to click on support button and to see the old text, and then to click on update and see another support text (inherited from the channel) without any explanation. It is a "sort" of silent error, as for me.

**Comment by Chocobozzz** [comment]
Oh okay I understood. It should be fixed in https://github.com/Chocobozzz/PeerTube/commit/6f79be110d31f4f751b989fe36b9de0d0f259fe0
