### ISSUE TITLE
the "PeerTube" button from embedded videos doesn't work

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2353]
**What happened?**
the "PeerTube" button from embedded videos doesn't work
**What do you expect to happen instead?**
when clicking the "PeerTube" button from embedded videos to redirect you to the instance that hosts that video
**Steps to reproduce:**

1. play the video from this page https://kde.org/announcements/plasma-5.17.0.php
2. click the peertube button

**Additional information**
* PeerTube version or URL: 2.0
* Browser name/version: FF 71

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/f2aa2c3cca2433d89ba80b1c2b64ea6c4b95fe66

But they will have to update their iframe code.
