### ISSUE TITLE
allow to download subtitles from PeerTube

### ISSUE THREAD

**Issue by bikepunk** [Chocobozzz/PeerTube#2354]
I somehow didn't find the way to download subtitles from PeerTube when present. It's a pitty

**Comment by Findus23** [comment]
Hi,

While I don't think there is a button for it in the API, it is still pretty easy to do:
Go to `https://peertube.social/api/v1/videos/9c9de5e8-0a1e-484a-b099-e80766180a6d/captions` (of course replacing domain and videoID with the video you mean.

You should see a response like this:
```json
{
  "total": 13,
  "data": [
    {
      "language": {
        "id": "ca",
        "label": "Catalan"
      },
      "captionPath": "/static/video-captions/9c9de5e8-0a1e-484a-b099-e80766180a6d-ca.vtt"
    },
    {
      "language": {
        "id": "cs",
        "label": "Czech"
      },
      "captionPath": "/static/video-captions/9c9de5e8-0a1e-484a-b099-e80766180a6d-cs.vtt"
    },
[...]
  ]
}
```

If you follow the `captionPath` URLs, you can download the subtitles as vtt files: e.g.
`https://peertube.social/static/video-captions/9c9de5e8-0a1e-484a-b099-e80766180a6d-de.vtt`

**Comment by bikepunk** [comment]
thanks for the trick ;-)

Still I believe it would be nice to have a button to downloads subs.
