### ISSUE TITLE
case sensitive search in the "default search"

### ISSUE THREAD

**Issue by bikepunk** [Chocobozzz/PeerTube#2355]
I think that the "default search" shall not be case sensitive.
I mean https://tube.aquilenet.fr/search?search=ffdn and https://tube.aquilenet.fr/search?search=FFDN should give the same results while they don't.

**Comment by Chocobozzz** [comment]
Done in https://github.com/Chocobozzz/PeerTube/commit/227eb02f9ac100e1314cab4c4751e450bbe14d21
