### ISSUE TITLE
Import from ok.ru - YoutubeDL download timeout

### ISSUE THREAD

**Issue by filin2009** [Chocobozzz/PeerTube#2357]
Hello!

**What happened?**
When uploading videos from https://ok.ru/ there are many errors like
"YoutubeDL download timeout."

**What do you expect to happen instead?**
When uploading videos from https://ok.ru/ there are no errors
and State = Success

**Steps to reproduce:**
1. https://video.ploud.fr/videos/upload
2. Import with URL
3. Insert https://ok.ru/video/2001049487949 in URL
4. Push Import
5. Category=Travel (doesn't matter)
   Licence = Public Domain (doesn't matter)
   Language=Russian (doesn't matter)
6. Push Update
7. Wait 1 hour
8. Go to https://video.ploud.fr/my-account/video-imports
or Playlists -> My Library - My Imports
and see 
Target= https://ok.ru/video/2001049487949
State = Failed
Error=YoutubeDL download timeout.

**Additional information**
1
It starts after 13-11-2019
2
This error depends on version of PeerTube.
When uploading same videos on  https://us.tv (PeerTube version = 1.3.1)
it is ok
3
This error is not YoutubeDL error.
when downloading videos on PC
youtube-dl https://ok.ru/video/2001049487949
it is ok
4
This error can be reproduced on other PeerTube instances.
See same errors on 
https://peertube.co.uk/my-account/video-imports

* PeerTube version or URL:
URL https://video.ploud.fr 
PeerTube version 2.0.0
* Browser name/version: Firefox 71 x64
* NodeJS version: -
* Link to browser console log if useful: -
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): -

See screenshots in attach
1
![pload upload fail_1](https://user-images.githubusercontent.com/14137869/71430502-e7142200-26d4-11ea-9256-9eb3a11d2f9f.JPG)
2
![pload upload fail_2](https://user-images.githubusercontent.com/14137869/71430503-ebd8d600-26d4-11ea-81a3-4900e0f40b02.JPG)

**Comment by Chocobozzz** [comment]
Maybe ok.ru has a rate limit or the ploud instance has some server issues. I don't think it's a peertube bug

**Comment by filin2009** [comment]
Maybe 1
"ok.ru has a rate limit"
see Additional information #3 
when downloading videos on PC
youtube-dl https://ok.ru/video/2001049487949
it is ok

Maybe 2
"ploud instance has some server issues"
see Additional information #2 - there are many PT2-instances with same errors
https://peertube.co.uk/my-account/video-imports

So, 
I think it's a peertube bug. And it seems it's new peertube v2.0 bug,
because (see Additional information #2)
When uploading same videos on https://us.tv (PeerTube version = 1.3.1)
it is ok

How can I proove it?

**Comment by Chocobozzz** [comment]
Using youtube-dl on my computer, it requires ~2/3h to download your video. The timeout on peertube is 1h. I don't think it depends on the peertube version, but rather the localization of the server (ploud -> France, peertube.co.uk -> United Kingdom, us.tv -> Netherlands).

**Comment by McFlat** [comment]
@Chocobozzz where can we change the peertube timeout of 1h to another value? long time bro

**Comment by Chocobozzz** [comment]
> @Chocobozzz where can we change the peertube timeout of 1h to another value?

In `constants.ts`.
