### ISSUE TITLE
Official dark theme makes instance statistics unreadable

### ISSUE THREAD

**Issue by Ju5ti** [Chocobozzz/PeerTube#2358]
**What happened?**
The "official" dark theme currently makes the instance statistics unreadable.
**What do you expect to happen instead?**
That the font goes from white to black to be readable ;)
**Steps to reproduce:**

1. Install the "official" dark theme (https://framagit.org/framasoft/peertube/official-plugins/tree/master/peertube-theme-dark)

2. Activate it 

3. Statistics became unreadable because the font is still white

**Additional information**
* PeerTube version or URL: 2.0.0 / dark theme version 0.0.2 (also newest)
* Browser name/version: FireFox 71 (also tested other browsers, same result)

How it looks currently:

![x](https://user-images.githubusercontent.com/48654834/71441906-d929c580-2703-11ea-9e56-3e7fb8146b62.png)

By marking the content I figured out its just a white instead of needed black font:

![xx](https://user-images.githubusercontent.com/48654834/71441951-01b1bf80-2704-11ea-9e67-7a9e2dabb3f2.png)

Thank you in advance!

**Comment by alcalyn** [comment]
Hi, this has been fixed and will be release in next release.

Until the next release, if you are the admin of the instance, a workaround is to add this:

``` css
.card {
  background-color: var(--mainBackgroundColor);
  border-color: #dee2e6;
}
```

in administration > configuration > advanced > CSS

Duplicated issue: https://github.com/Chocobozzz/PeerTube/issues/2244
