### ISSUE TITLE
Save video to playlist needs infinite scroll and/or search

### ISSUE THREAD

**Issue by Ju5ti** [Chocobozzz/PeerTube#2359]
**What happened?**
I created created over 20 playlists for my videos on my channel. The option to save the video into playlists only shows 15 playlists to choose or to create a new one.

Currently the workaround is to edit the playlists if they aren't showing to appear at the top, than to assign a video into it.

**What do you expect to happen instead?**
There would be 2 solutions, I would implement both ;)

1. Make the list infinite scroll, show all your playlists instead of only the 15 newest/last edited.

2. Create a search field to search for the right playlist.

Optional: Maybe a server or client side option to tweak the setting on how many playlists to list?

**Steps to reproduce:**

1. Create more than 15 playlists

2. Assign video into a playlist which is under the 15 last playlists you created or edited

**Additional information**
* PeerTube version or URL: 2.0.0 (newest)
* Browser name/version: Firefox 71

Thank you in advance!

**Comment by rigelk** [comment]
I'm already working on it. That issue was already reported by @lecygnenoir.
