### ISSUE TITLE
Add forgot password mechanism

### ISSUE THREAD

**Issue by Dryusdan** [Chocobozzz/PeerTube#236]
* **PeerTube version or commit:**
Peertube 5ec081e

* **Browser name/version:**
Firefox 57.0.4 Windows 10

* **NodeJS version:**
NodeJS 8
* **PostgreSQL version:**
Postgres 10

Hello
Today, a user of my instance ask me a new password... But, I couldn't make it work with `npm run reset-password` 
So, It's possible to create a page "forgot password", a button on admin page to reset password ?

Thank :)

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/ecb4e35f4e6c7304cb274593c13cb47fd5078b75
