### ISSUE TITLE
Move zh-Hant-TW langauage files to zh-Hant

### ISSUE THREAD

**Issue by s8321414** [Chocobozzz/PeerTube#2360]
**What happened?**
Traditional Chinese (Taiwan) can't show correct language code on Weblate.
**What do you expect to happen instead?**
Show correct language code on Weblate.
**Steps to reproduce:**

1. Open https://weblate.framasoft.org/languages/zh_HANT-TW/

2. Check language name.

3. It should be 漢語（正體字） instead of 漢語（簡體字）(zh_HANT-TW)

**Comment by Chocobozzz** [comment]
Does the chinese languages are correct on https://peertube2.cpy.re? Is it just the language display on weblate that is wrong?

**Comment by s8321414** [comment]
> Are the chinese languages correct on https://peertube2.cpy.re? Is it just the language display on weblate that is wrong?

It shows correct 繁體中文（台灣） on demo site (but still zh-Hant-TW in its URL). On Weblate it shows wrong localized name (and for weblate itself, wrong language code) just like above.

**Comment by Chocobozzz** [comment]
> (but still zh-Hant-TW in its URL).

It's just that peertube prefers to work with complete locales, but it should not hurt because we have aliases: https://github.com/Chocobozzz/PeerTube/blob/develop/shared/models/i18n/i18n.ts#L44

**Comment by s8321414** [comment]
So we only need to modify zh-Hant-TW to zh-Hant on Weblate to make it show correct language name :sweat_smile: 
BTW, I found there is same issue for "What is PeerTube" video translation on same Weblate instance.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/WeblateOrg/language-data/pull/1.

Now we have to wait a weblate update ;)
