### ISSUE TITLE
thumbnails not diplay and video not play

### ISSUE THREAD

**Issue by noellaby** [Chocobozzz/PeerTube#2361]
Hello

I encounter two major problem with my Peertube instance (https://wandatube.foongon.com) namely:
- the thumbnails of the videos on pc are not displayed, but the thumbnails on android phone are displayed

- the videos do not play either on pc or on mobile phone

Thanks everyone

**Comment by Chocobozzz** [comment]
Hi,

How did you install your peertube install? Using docker?

**Comment by noellaby** [comment]
> Hi,
> 
> How did you install your peertube install? Using docker?

Thank you for your quick response, I do not use docker
Thank you

**Comment by Chocobozzz** [comment]
Please paste your nginx config.
Also, in which directory did you install peertube?

**Comment by noellaby** [comment]
> Please paste your nginx config.
> Also, in which directory did you install peertube?

Thank you for your quick response.

i install peertube in directory : /var/www/peertube/peertube-latest , [https://i.imgur.com/SC2gF2n.png](url)

my nginx configuration is : 

`<pre>upstream backend_peertube {
    server 127.0.0.1:9000;
    #server unix:/var/run/php/php7.2-fpm.sock;
}

server {
    if ($host = wandatube.foongon.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


  listen 80;
  listen [::]:80;
  server_name wandatube.foongon.com;

  access_log /var/log/nginx/wandatube.foongon.com.access.log;
  error_log /var/log/nginx/wandatube.foongon.com.error.log;

  location /.well-known/acme-challenge/ {
    default_type &quot;text/plain&quot;;
    root /var/www/certbot;
  }
  location / { return 301 https://$host$request_uri; }


}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name wandatube.foongon.com;

  # For example with certbot (you need a certificate to run https)
  #ssl_certificate      /etc/letsencrypt/live/wandatube.foongon.com/fullchain.pem;
  #ssl_certificate_key  /etc/letsencrypt/live/wandatube.foongon.com/privkey.pem;
  ssl_certificate       /etc/letsencrypt/live/wandatube.foongon.com/fullchain.pem; # managed by Certbot
  ssl_certificate_key   /etc/letsencrypt/live/wandatube.foongon.com/privkey.pem; # managed by Certbot

  # Security hardening (as of 11/02/2018)
  ssl_protocols TLSv1.2; # TLSv1.3, TLSv1.2 if nginx &gt;= 1.13.0
  ssl_prefer_server_ciphers on;
  ssl_ciphers &apos;ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256&apos;;
  # ssl_ecdh_curve secp384r1; # Requires nginx &gt;= 1.1.0, not compatible with import-videos script
  ssl_session_timeout  10m;
  ssl_session_cache shared:SSL:10m;
  ssl_session_tickets off; # Requires nginx &gt;= 1.5.9
  ssl_stapling on; # Requires nginx &gt;= 1.3.7
  ssl_stapling_verify on; # Requires nginx =&gt; 1.3.7

  # Configure with your resolvers
  # resolver $DNS-IP-1 $DNS-IP-2 valid=300s;
  # resolver_timeout 5s;

  # Enable compression for JS/CSS/HTML bundle, for improved client load times.
  # It might be nice to compress JSON, but leaving that out to protect against potential
  # compression+encryption information leak attacks like BREACH.
  gzip on;
  gzip_types text/css application/javascript;
  gzip_vary on;

  # Enable HSTS
  # Tells browsers to stick with HTTPS and never visit the insecure HTTP
  # version. Once a browser sees this header, it will only visit the site over
  # HTTPS for the next 2 years: (read more on hstspreload.org)
  #add_header Strict-Transport-Security &quot;max-age=63072000; includeSubDomains&quot;;

  access_log /var/log/nginx/wandatube.foongon.com.access.log;
  error_log /var/log/nginx/wandatube.foongon.com.error.log;

  location ^~ &apos;/.well-known/acme-challenge&apos; {
    default_type &quot;text/plain&quot;;
    root /var/www/certbot;
  }

  # Bypass PeerTube for performance reasons. Could be removed
  location ~ ^/client/(.*\.(js|css|png|svg|woff2|otf|ttf|woff|eot))$ {
    add_header Cache-Control &quot;public, max-age=31536000, immutable&quot;;

    alias /var/www/peertube/peertube-latest/client/dist/$1;
  }

  # Bypass PeerTube for performance reasons. Could be removed
  location ~ ^/static/(thumbnails|avatars)/ {
    if ($request_method = &apos;OPTIONS&apos;) {
      add_header &apos;Access-Control-Allow-Origin&apos; &apos;*&apos;;
      add_header &apos;Access-Control-Allow-Methods&apos; &apos;GET, OPTIONS&apos;;
      add_header &apos;Access-Control-Allow-Headers&apos; &apos;Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type&apos;;
      add_header &apos;Access-Control-Max-Age&apos; 1728000;
      add_header &apos;Content-Type&apos; &apos;text/plain charset=UTF-8&apos;;
      add_header &apos;Content-Length&apos; 0;
      return 204;
    }

    add_header &apos;Access-Control-Allow-Origin&apos; &apos;*&apos;;
    add_header &apos;Access-Control-Allow-Methods&apos; &apos;GET, OPTIONS&apos;;
    add_header &apos;Access-Control-Allow-Headers&apos; &apos;Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type&apos;;

    # Cache 2 hours
    add_header Cache-Control &quot;public, max-age=7200&quot;;

    root /var/www/peertube/PeerTube-master/storage;

    rewrite ^/static/(thumbnails|avatars)/(.*)$ /$1/$2 break;
    try_files $uri /;
  }

  location / {
    proxy_pass http://backend_peertube;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # This is the maximum upload size, which roughly matches the maximum size of a video file
    # you can send via the API or the web interface. By default this is 8GB, but administrators
    # can increase or decrease the limit. Currently there&apos;s no way to communicate this limit
    # to users automatically, so you may want to leave a note in your instance &apos;about&apos; page if
    # you change this.
    #
    # Note that temporary space is needed equal to the total size of all concurrent uploads.
    # This data gets stored in /var/lib/nginx by default, so you may want to put this directory
    # on a dedicated filesystem.
    #
    client_max_body_size 8G;

    proxy_connect_timeout       600;
    proxy_send_timeout          600;
    proxy_read_timeout          600;
    send_timeout                600;
  }

  # Bypass PeerTube for performance reasons. Could be removed
  location ~ ^/static/(webseed|redundancy)/ {
    # Clients usually have 4 simultaneous webseed connections, so the real limit is 3MB/s per client
    limit_rate 800k;

    if ($request_method = &apos;OPTIONS&apos;) {
      add_header &apos;Access-Control-Allow-Origin&apos; &apos;*&apos;;
      add_header &apos;Access-Control-Allow-Methods&apos; &apos;GET, OPTIONS&apos;;
      add_header &apos;Access-Control-Allow-Headers&apos; &apos;Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type&apos;;
      add_header &apos;Access-Control-Max-Age&apos; 1728000;
      add_header &apos;Content-Type&apos; &apos;text/plain charset=UTF-8&apos;;
      add_header &apos;Content-Length&apos; 0;
      return 204;
    }

    if ($request_method = &apos;GET&apos;) {
      add_header &apos;Access-Control-Allow-Origin&apos; &apos;*&apos;;
      add_header &apos;Access-Control-Allow-Methods&apos; &apos;GET, OPTIONS&apos;;
      add_header &apos;Access-Control-Allow-Headers&apos; &apos;Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type&apos;;

      # Don&apos;t spam access log file with byte range requests
      access_log off;
    }

    root /var/www/peertube/peertube-latest/storage;

    rewrite ^/static/webseed/(.*)$ /videos/$1 break;
    rewrite ^/static/redundancy/(.*)$ /redundancy/$1 break;

    try_files $uri /;
  }

  # Websocket tracker
  location /tracker/socket {
    # Peers send a message to the tracker every 15 minutes
    # Don&apos;t close the websocket before this time
    proxy_read_timeout 1200s;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection &quot;upgrade&quot;;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_pass http://backend_peertube;
  }

  location /socket.io {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;

    proxy_pass http://backend_peertube;

    # enable WebSockets
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection &quot;upgrade&quot;;
  }

    #ssl_certificate /etc/letsencrypt/live/wandatube.foongon.com/fullchain.pem; # managed by Certbot
    #ssl_certificate_key /etc/letsencrypt/live/wandatube.foongon.com/privkey.pem; # managed by Certbot
}

</pre>`

thanks

**Comment by noellaby** [comment]
My nginx file had an error in **root /var/www/peertube/PeerTube-master/storage;** , i put **root /var/www/peertube/storage;**


after correcting this the thumbnails will appear.

remains the problem of videos that do not play

**Comment by Chocobozzz** [comment]
I think it should be `root /var/www/peertube/storage` instead of `root /var/www/peertube/peertube-latest/storage;`

**Comment by noellaby** [comment]
> I think it should be `root /var/www/peertube/storage` instead of `root /var/www/peertube/peertube-latest/storage;`

already updated, the thumbnails are displayed . 
But the videos are not playing?

Thanks

**Comment by Chocobozzz** [comment]
@noellaby It's on another line (`Bypass PeerTube for performance reasons. Could be removed` section)

**Comment by noellaby** [comment]
> @noellaby It's on another line (`Bypass PeerTube for performance reasons. Could be removed` section)

this is my new nginx configuration

upstream backend_peertube {
    server 127.0.0.1:9000;
    #server unix:/var/run/php/php7.2-fpm.sock;
}

server {
    if ($host = wandatube.foongon.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


  listen 80;
  listen [::]:80;
  server_name wandatube.foongon.com;

  access_log /var/log/nginx/wandatube.foongon.com.access.log;
  error_log /var/log/nginx/wandatube.foongon.com.error.log;

  location /.well-known/acme-challenge/ {
    default_type "text/plain";
    root /var/www/certbot;
  }
  location / { return 301 https://$host$request_uri; }


}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name wandatube.foongon.com;

  # For example with certbot (you need a certificate to run https)
  #ssl_certificate      /etc/letsencrypt/live/wandatube.foongon.com/fullchain.pem;
  #ssl_certificate_key  /etc/letsencrypt/live/wandatube.foongon.com/privkey.pem;
  ssl_certificate       /etc/letsencrypt/live/wandatube.foongon.com/fullchain.pem; # managed by Certbot
  ssl_certificate_key   /etc/letsencrypt/live/wandatube.foongon.com/privkey.pem; # managed by Certbot

  # Security hardening (as of 11/02/2018)
  ssl_protocols TLSv1.2; # TLSv1.3, TLSv1.2 if nginx >= 1.13.0
  ssl_prefer_server_ciphers on;
  ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
  # ssl_ecdh_curve secp384r1; # Requires nginx >= 1.1.0, not compatible with import-videos script
  ssl_session_timeout  10m;
  ssl_session_cache shared:SSL:10m;
  ssl_session_tickets off; # Requires nginx >= 1.5.9
  ssl_stapling on; # Requires nginx >= 1.3.7
  ssl_stapling_verify on; # Requires nginx => 1.3.7

  # Configure with your resolvers
  # resolver $DNS-IP-1 $DNS-IP-2 valid=300s;
  # resolver_timeout 5s;

  # Enable compression for JS/CSS/HTML bundle, for improved client load times.
  # It might be nice to compress JSON, but leaving that out to protect against potential
  # compression+encryption information leak attacks like BREACH.
  gzip on;
  gzip_types text/css application/javascript;
  gzip_vary on;

  # Enable HSTS
  # Tells browsers to stick with HTTPS and never visit the insecure HTTP
  # version. Once a browser sees this header, it will only visit the site over
  # HTTPS for the next 2 years: (read more on hstspreload.org)
  #add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";

  access_log /var/log/nginx/wandatube.foongon.com.access.log;
  error_log /var/log/nginx/wandatube.foongon.com.error.log;

  location ^~ '/.well-known/acme-challenge' {
    default_type "text/plain";
    root /var/www/certbot;
  }

  # Bypass PeerTube for performance reasons. Could be removed
  location ~ ^/client/(.*\.(js|css|png|svg|woff2|otf|ttf|woff|eot))$ {
    add_header Cache-Control "public, max-age=31536000, immutable";

    alias /var/www/peertube/peertube-latest/client/dist/$1;
  }

  # Bypass PeerTube for performance reasons. Could be removed
  location ~ ^/static/(thumbnails|avatars)/ {
    if ($request_method = 'OPTIONS') {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
      add_header 'Access-Control-Max-Age' 1728000;
      add_header 'Content-Type' 'text/plain charset=UTF-8';
      add_header 'Content-Length' 0;
      return 204;
    }

    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
    add_header 'Access-Control-Allow-Headers' 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

    # Cache 2 hours
    add_header Cache-Control "public, max-age=7200";

    root /var/www/peertube/storage;
 

    rewrite ^/static/(thumbnails|avatars)/(.*)$ /$1/$2 break;
    try_files $uri /;
  }

  location / {
    proxy_pass http://backend_peertube;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # This is the maximum upload size, which roughly matches the maximum size of a video file
    # you can send via the API or the web interface. By default this is 8GB, but administrators
    # can increase or decrease the limit. Currently there's no way to communicate this limit
    # to users automatically, so you may want to leave a note in your instance 'about' page if
    # you change this.
    #
    # Note that temporary space is needed equal to the total size of all concurrent uploads.
    # This data gets stored in /var/lib/nginx by default, so you may want to put this directory
    # on a dedicated filesystem.
    #
    client_max_body_size 8G;

    proxy_connect_timeout       600;
    proxy_send_timeout          600;
    proxy_read_timeout          600;
    send_timeout                600;
  }

  # Bypass PeerTube for performance reasons. Could be removed
  location ~ ^/static/(webseed|redundancy)/ {
    # Clients usually have 4 simultaneous webseed connections, so the real limit is 3MB/s per client
    limit_rate 800k;

    if ($request_method = 'OPTIONS') {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
      add_header 'Access-Control-Max-Age' 1728000;
      add_header 'Content-Type' 'text/plain charset=UTF-8';
      add_header 'Content-Length' 0;
      return 204;
    }

    if ($request_method = 'GET') {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

      # Don't spam access log file with byte range requests
      access_log off;
    }

    root /var/www/peertube/storage;

    rewrite ^/static/webseed/(.*)$ /videos/$1 break;
    rewrite ^/static/redundancy/(.*)$ /redundancy/$1 break;

    try_files $uri /;
  }

  # Websocket tracker
  location /tracker/socket {
    # Peers send a message to the tracker every 15 minutes
    # Don't close the websocket before this time
    proxy_read_timeout 1200s;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_pass http://backend_peertube;
  }

  location /socket.io {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;

    proxy_pass http://backend_peertube;

    # enable WebSockets
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }

    #ssl_certificate /etc/letsencrypt/live/wandatube.foongon.com/fullchain.pem; # managed by Certbot
    #ssl_certificate_key /etc/letsencrypt/live/wandatube.foongon.com/privkey.pem; # managed by Certbot
}

Video not play always , what this problem ?

thanks

**Comment by Chocobozzz** [comment]
I can play your video https://wandatube.foongon.com/videos/watch/e63f056e-a342-4028-8dd7-9c10962764fd

**Comment by noellaby** [comment]
Thank you for all the help you have given me.
