### ISSUE TITLE
Add a time-frame for the "Most Liked" page (similar to the Trending page)

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#2369]
The "Most Liked" page is not really interesting right now because the content is almost always the same. To make it more interesting we could add a dropdown button https://github.com/Chocobozzz/PeerTube/issues/2368 (similar to the Trending page) that would allow the user to choose a different time-frame:
Most Liked Videos for the last:

- 7 days
- month
- 6 months
- etc..

**Comment by ajayyy** [comment]
https://github.com/alextanhongpin/go-rate

**Comment by Chocobozzz** [comment]
Closing now we have the hot algorithm that seems to fix the original issue (lack of interesting/fresh content on the trending page).
