### ISSUE TITLE
Issue with Player on Mastodon

### ISSUE THREAD

**Issue by Letiteuf55** [Chocobozzz/PeerTube#237]
* **Browser name/version: Chrome**

* **What is the expected behaviour?**
See a video in mastodon https://mastodon.crazypanda.fr/web/statuses/99405555204330336
* **What do you see instead?**

> Les requêtes vers le serveur ont été bloquées par une extension.

* **Browser console log if useful (Gist/Pastebin...):**

> Refused to frame 'https://peertube.drycat.fr/' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.

![capture d ecran 2018-01-24 a 17 24 29](https://user-images.githubusercontent.com/23027090/35343878-007eedd6-012c-11e8-9ca8-bf111dfa2b87.png)
https://peertube.drycat.fr/videos/watch/2847afae-665a-4afc-bbdd-d16b156f7f8e

**Comment by Chocobozzz** [comment]
It seems to be a Mastodon issue: https://github.com/Chocobozzz/PeerTube/issues/104#issuecomment-347562154

**Comment by Letiteuf55** [comment]
But i don't find any information about that... How can i make it work on my instance ?

**Comment by bnjbvr** [comment]
Note the issue might be that CSP protections are too strong (viz. blocking everything) on the Mastodon instance you're using (or the PeerTube instance). Probably something related to the reverse proxy server?

**Comment by Letiteuf55** [comment]
ok, so i have to check with my nginx conf. thanks.

**Comment by PhieF** [comment]
Hi,

I'm also having an issue with the player, see an example between framatube and framapiaf 

https://framapiaf.org/@Phoenamandre/99716605835529883

though the error isn't the same, should I open a new issue ?

**Comment by Letiteuf55** [comment]
@PhieF it's the same issue.

**Comment by Chocobozzz** [comment]
@PhieF Thanks! It's fixed :)

**Comment by Letiteuf55** [comment]
@Chocobozzz can you provide the setup to fix that ? i can't find the right setup to change in my mastodon instance...

**Comment by Chocobozzz** [comment]
It was a nginx bad configuration on the peertube side (we had to remove `add_header X-Frame-Options DENY;` parameter)

**Comment by Letiteuf55** [comment]
Oh ok, thanks
