### ISSUE TITLE
Remove the message that warns about IP exposure if the p2p player is disabled on a certain video or server

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2370]
**I don't know if this is an actual issue since I can't find a video/instance to test this**. But in case this is an issue then we should remove this message (from video embeds as well) "Watching this video may reveal your IP address to others" and other similar when the p2p player isn't being used. 

Again, sorry if this is a non-issue.

**Comment by Chocobozzz** [comment]
Added in https://github.com/Chocobozzz/PeerTube/commit/c469c05b0f19c8ba6a7383ed89ce30b577146ebe

**Comment by DontUseGithub** [comment]
Thank you! Will this apply to embeds as well?
