### ISSUE TITLE
can't upload png only jpg or jpeg

### ISSUE THREAD

**Issue by albjeremias** [Chocobozzz/PeerTube#2373]
**What happened?**
When I set a preview image for a video, i tried to upload a .png file, but peertube won't accept it!

**What do you expect to happen instead?**
I expect that peertube accepts pngs, jpg, jpegs and maybe gifs?

**Steps to reproduce:**

1. Upload a video

2. Setup a preview image using a png

peertube 2.0.0

**Comment by Findus23** [comment]
I think this is similar to https://github.com/Chocobozzz/PeerTube/issues/1953

**Comment by rigelk** [comment]
@Findus23 indeed! Thanks
