### ISSUE TITLE
Restart video upload on fail

### ISSUE THREAD

**Issue by albjeremias** [Chocobozzz/PeerTube#2374]
**What happened?**
When I am uploading a large video, and the upload fails (because of bad internet connection), I loose all the description, tags, title of my video, because peertube automatically closes the form when the upload fails...

**What do you expect to happen instead?**
When I am uploading a large video, and the upload fails (because of bad internet connection), I expect that there is a new way to upload a video again with the same attributes.

peertube 2.0.0

**Comment by ldexterldesign** [comment]
Hi @albjeremias,

I suggest this issue is closed and discussion moved [here]

If you agree then please close this issue

Sincerely

[here]: https://github.com/Chocobozzz/PeerTube/issues/324
