### ISSUE TITLE
Subtitles are not updated

### ISSUE THREAD

**Issue by r4dh4l** [Chocobozzz/PeerTube#2378]
**What happened?**

I've uploaded a video and added subtitles: https://peertube.social/videos/watch/3d5bc800-4170-42e3-8643-e5716ecb4747?subtitle=ko

After adding something to the subtitles I've deleted the uploaded one and added the new file but the old subtitle version is still shown.

**What do you expect to happen instead?**

The new subtitle version should be shown.

**Steps to reproduce:**

1. Upload a video and add subtitles-v1.vtt.

2. Delete subtitles and add the edited subtitle file subtitles-v2.vtt.

3. Reload the video. There is still the content of subtitles-v1.vtt shown.

**Comment by r4dh4l** [comment]
Oh, just noticed: On another machine the intended subtitles are shown. Maybe a cache problem?

**Comment by Chocobozzz** [comment]
Indeed, there is a cache so you may not see your update. I think we can improve this in peertube by changing the name of the video caption (to invalidate the cache).

**Comment by Chocobozzz** [comment]
This issue should be fixed, we now generate a new caption name so the cache is invalidated.
