### ISSUE TITLE
Missing @context in JSON-LD responses

### ISSUE THREAD

**Issue by puckipedia** [Chocobozzz/PeerTube#238]
The ActivityPub responses do not contain the required `@context` that explains how to parse the JSON-LD document. you should probably set it to `"@context": "https://www.w3.org/ns/activitystreams"`

**Comment by Chocobozzz** [comment]
Should be fixed: https://github.com/Chocobozzz/PeerTube/commit/d6e99e5322209a692cc3d870ddb5dcedbda69f2a

Thanks @puckipedia!
