### ISSUE TITLE
server error when "No compatible source was found for this media"

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2380]
My OS doesn't have any proprietary codecs so I can't watch PeerTube videos on this PC. So I get this message inside the player "No compatible source was found for this media." which is fine. 
But every time I refresh the page I also get the red warning at the bottom right corner, and the more I scroll down, the more of these pop ups I get (see in the screenshot).
![Screenshot_2020-01-03 What is PeerTube (english subtitles)](https://user-images.githubusercontent.com/57924087/71725437-82776680-2e3c-11ea-88dc-31ba8c168ee6.png)

it happens on this latest dev instance - https://peertube2.cpy.re

on this instance https://share.tube/videos/watch/85ed39d8-64c2-4353-96a6-e33ca688b028 (v2.0) this doesn't happen

**Comment by Chocobozzz** [comment]
peertube2.cpy.re has a bug that I fixed today in https://github.com/Chocobozzz/PeerTube/commit/562724a1ed13fe93aba08ca1a0f8e029819e9f32
