### ISSUE TITLE
New theme I created is not showing up in the search results

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#2381]
**What happened?**

I created a theme for peertube for my site, a couple themes actually, but am not able to see them in the Admin nor am I able to activate/install them. But when I go in the terminal to the plugin directory and run yarn, after adding the themes to the plugin/package.json file it installs them just fine. Though they aren't usable or viewable in the admin of the site.

**What do you expect to happen instead?**

Expect to see the newly created themes that have also been published to npm as packages with a name starting with peertube-theme-*

**Steps to reproduce:**

1. Create a theme

2. Publish it to NPM

3. Notice it doesn't come up in the search results in the Admin where you go to install a theme.

https://github.com/TrooTube/peertube-dark-theme-troo.tube-blue
https://github.com/TrooTube/peertube-dark-theme-troo.tube-red

Both of the theme's I created are not showing up in the results so I can install the themes. There seems to be more other bugs in the plugin/theme functionality. I'm unable to install a theme again after uninstalling it, I'll have to create another issue for that and other things that are happening with plugins and themes not working.

**Additional information**
* PeerTube version or URL: 2.0.0 https://troo.tube
* Browser name/version: Chrome/79
* NodeJS version: 12.13.1

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by JohnXLivingston** [comment]
The documentation says you have to wait a few hour before your themes and plugins are available. When have you published them?

**Comment by Chocobozzz** [comment]
It should start with `peertube-theme`. We also don't accept `.` in npm names for now but I changed the regex in develop branch: https://github.com/Chocobozzz/PeerTube/commit/c10b638c4b52e9766ef68b58849ee0728647988f

**Comment by McFlat** [comment]
cool, I was just about to add the warning here. I'll have to update the code to install the theme then. 

```warn[1/10/2020, 8:30:32 AM] Incorrect request parameters { "path": "/api/v1/plugins/install", "err": { "npmName": { "value": "peertube-theme-dark-troo.tube-red", "msg": "Should have a valid npm name", "param": "npmName", "location": "body" } } }```
