### ISSUE TITLE
128 bit ipv6 address is not correct write from log

### ISSUE THREAD

**Issue by ne-vlezay80** [Chocobozzz/PeerTube#2382]
**What happened?**
128 bit address is incorrect write from logs

**What do you expect to happen instead?**
Correct display with ipv6 address from log.

**Steps to reproduce:**

1. Access to instance with 128 bit ipv6 address (Example: yggdrasil network)

**Additional information**
* PeerTube version or URL: 1.4.1
* Browser name/version: Generic
* NodeJS version: 11.15.0

* Link to browser console log if useful: http://[301:fd1:86e3:521c::13]/
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
```
{"message":"200:: - - [09/Dec/2019:16:05:32 +0000] \"GET /api/v1/accounts/dimka511@[301:fd1:86e3:521c::13]:80/video-playlists?sort=-updatedAt HTTP/1.0\" 200 670 \"http://[301:fd1:86e3:521c::13]/videos/watch/1dd10cce-016f-453b-8445-7a0c6752a8d6\" \"Firefox\"\n","level":"info","label":"[301:fd1:86e3:521c::13]:80","timestamp":"2019-12-09T16:05:32.075Z"}
{"message":"200:: - - [09/Dec/2019:16:07:04 +0000] \"GET /api/v1/accounts/dimka511@[301:fd1:86e3:521c::13]:80/video-playlists?sort=-updatedAt HTTP/1.0\" 304 - \"http://[301:fd1:86e3:521c::13]/videos/watch/cc3967c5-52c8-43b0-9b6a-52c53a0228e0\" \"Firefox\"\n","level":"info","label":"[301:fd1:86e3:521c::13]:80","timestamp":"2019-12-09T16:07:04.161Z"}

```

**Comment by Chocobozzz** [comment]
We anonymize IP from logs when web browsers have `DNT` enabled or your enabled the option in your configuration: https://github.com/Chocobozzz/PeerTube/blob/develop/server.ts#L142
