### ISSUE TITLE
PeerTube doesn't compile since ac0868bcc0259d4ff14265d9ae403e10869a13aa

### ISSUE THREAD

**Issue by BenLubar** [Chocobozzz/PeerTube#2384]
This function shouldn't require `MyUser`:

https://github.com/Chocobozzz/PeerTube/blob/32c68d67d9125df62ead71668efca4da30132786/client/src/app/core/auth/auth-user.model.ts#L145

**Comment by rigelk** [comment]
Fixed in a6051ba746b15bab5679b5908b06009e3e950cee
