### ISSUE TITLE
Being able to subscribe to a user in addition to channel

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#2389]
Hello!

Following a discussion on Mastodon, here is a suggestion about subscription on Peertube: it would be very useful for a user to be able to subscribe to another user, instead of subscribing only to channels one by one.

Indeed, currently the "subscribe" button are displayed next to channel on a user profile, so when you have a Peertube account, it's only possible to subscribe to channels.

If the user create new channel after that (or if the user has numerous channel), it's possible to miss video, and/or we need to check subscription regularly to subscribe to new channel.

But, if one has a mastodon account, it's possible to subscribe to the Peertube account directly using the "activity pub nomination" eg: `lecygnenoir@videos.pair2jeux.tube`

In this case, the mastodon account will receive notification for any video published, regardless the channel used, which is very convenient.

In addition to that, it increase the "subscriber" count for the account instead of increasing counter for each channel  
(By the way it is the only way I know to change this account counter, please do not hesitate to tell me if there is any other way)

I think it would be useful to have this possibility inside Peertube too!

As discussed a possibility would be to add a button to subscribe all existing channels in one click, but I think we could have some problems with this solution:

 - If new channels are created, we need to resubscribe to them
 - If we already subscribe some channel, this button should not resubscribe (or manage duplicated subscription?)
 - Currently when subscribed to a channel, button change to grey and display "unsubscribe", but this new button will need to work differently (proposing to unsubscribe in sub menu? Grey until new channel are created?)

However this is totally opened to discussion, as I just noticed this feature missing but am unaware about the work needed to realize it 😅 

Anyway, thanks again for your wonderful work on Peertube!

**Comment by rigelk** [comment]
> - If we already subscribe some channel, this button should not resubscribe (or manage duplicated subscription?)
> - Currently when subscribed to a channel, button change to grey and display "unsubscribe", but this new button will need to work differently (proposing to unsubscribe in sub menu? Grey until new channel are created?)

That is the core question, UI-wise. I would say, so long as some channels are unsubscribed, display the "Subscribe all" button, along with a counter of how many channels are subscribed/aren't. Then unsubcribe becomes "Unsubscribe all".

---

> In addition to that, it increase the "subscriber" count for the account instead of increasing counter for each channel (by the way it is the only way I know to change this account counter, please do not hesitate to tell me if there is any other way)

Ah right! I had forgotten about that counter. Maybe more a side-issue, but instead of displaying just an account's subscribers, we could display unique aggregated subscribers (account + channel unique subscribers).

**Comment by LecygneNoir** [comment]
Great start indeed :heart_eyes: 

The counter to see how many channel are already subscribe is cool!

In this case, the button for each subscribed channel will be gray? 

```
Ah right! I had forgotten about that counter. Maybe more a side-issue, but instead of displaying just an account's subscribers, we could display unique aggregated subscribers (account + channel unique subscribers).
```
Indeed it's a side-issue, it's a question that came to me when writing this issue :-D  
Your solution seems great, if you want I may create another issue later depending how this current one is solved, let's get this point out for now ^^

**Comment by rigelk** [comment]
> In this case, the button for each subscribed channel will be gray?

Yes, the subscribe button switches to gray with the label "Unsubscribe" for channels already subscribed.

> > Ah right! I had forgotten about that counter. Maybe more a side-issue, but instead of displaying just an account's subscribers, we could display unique aggregated subscribers (account + channel unique subscribers).
> 
> Indeed it's a side-issue, it's a question that came to me when writing this issue :-D

Could you open an issue about it?

**Comment by LecygneNoir** [comment]
Thanks a lot for your reactivity! :hugs: 

@rigelk as asked, here is the issue about counter: https://github.com/Chocobozzz/PeerTube/issues/2398
