### ISSUE TITLE
Announces are invalid format

### ISSUE THREAD

**Issue by puckipedia** [Chocobozzz/PeerTube#239]
If you get an `Announce`, it gets rehosted into a local format. This should not be done and clients will not properly accept this. (e.g. https://peertube.drycat.fr/videos/watch/2847afae-665a-4afc-bbdd-d16b156f7f8e/announces/264 should be https://framapiaf.org/users/inso/statuses/99406176381077270/activity)

Alternatively, you seem to be `Announce`ing an object with the same `id` but actually being a `Create` of the `Video`. this is really quite invalid. The `object` of the `Announce` should either be an exact copy of the `Video`, or (preferably) if a remote object, just the `id` of the `Video`.

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed: https://github.com/Chocobozzz/PeerTube/commit/7acee6f18aac99e359360fc4f2362d5405135a79

Now the activity looks like to this:

```
{
  "type": "Announce",
  "to": [
    "http://localhost:9000/accounts/peertube/followers",
    "http://localhost:9000/video-channels/67b2e72e-8f1d-4738-9061-96a9fbd5f733/followers",
    "http://localhost:9000/accounts/florian56/followers"
  ],
  "cc": [],
  "id": "http://localhost:9000/videos/watch/98d84dc0-6945-4813-9e3e-6cccbcac136f/announces/1",
  "actor": "http://localhost:9000/accounts/peertube",
  "object": "http://localhost:9000/videos/watch/98d84dc0-6945-4813-9e3e-6cccbcac136f",
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/v1",
    {
      "RsaSignature2017": "https://w3id.org/security#RsaSignature2017",
      "Hashtag": "as:Hashtag",
      "uuid": "http://schema.org/identifier",
      "category": "http://schema.org/category",
      "licence": "http://schema.org/license",
      "nsfw": "as:sensitive",
      "language": "http://schema.org/inLanguage",
      "views": "http://schema.org/Number",
      "size": "http://schema.org/Number",
      "commentsEnabled": "http://schema.org/Boolean"
    }
  ]
}
```

Do not hesitate if you see other inconsistencies :)

**Comment by puckipedia** [comment]
Do you also still rehost announces from other servers?

**Comment by Chocobozzz** [comment]
If I understand correctly, you mean that `https://peertube.drycat.fr/videos/watch/2847afae-665a-4afc-bbdd-d16b156f7f8e` should have the `shares` collection containing `https://framapiaf.org/users/inso/statuses/99406176381077270/activity` instead of `https://peertube.drycat.fr/videos/watch/2847afae-665a-4afc-bbdd-d16b156f7f8e/announces/264`?

**Comment by puckipedia** [comment]
Yep

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed too: https://github.com/Chocobozzz/PeerTube/commit/4ba3b8ea1be85d95a508ac479f26b96ceea15971
