### ISSUE TITLE
Number of comments bug

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2391]
**What happened?**
it doesn't show the real number of comments a video has, you have to scroll down the page and then the number will autoupdate itself to (perhaps) the correct one
**What do you expect to happen instead?**
to show the real number of comments a video has without the user having to scroll down
**Steps to reproduce:**

1. visit https://peertube2.cpy.re/videos/watch/217eefeb-883d-45be-b7fc-a788ad8507d3

2. only scroll down a little until you see "10 Comments"

3. then scroll down to the end of the page

4. then go back up and you'll see "30 Comments" (IDK if this is actually the correct number of comments)

**Additional information**
* PeerTube version or URL: https://peertube2.cpy.re
* Browser name/version: FF 71

**Comment by rigelk** [comment]
Thanks for spotting this @DontUseGithub!

**Comment by DontUseGithub** [comment]
> Thanks for spotting this @DontUseGithub!

Np! Thanks for setting up that peertube server - it's really helpful at avoiding **future bugs** :)

**Comment by rigelk** [comment]
@DontUseGithub indeed! it gets updated every Friday night btw

**Comment by DontUseGithub** [comment]
the About page says "every business day, 8pm CET" hmm ok, thanks for clarifying this

**Comment by rigelk** [comment]
@DontUseGithub my mistake, that's every business day as stated, sorry.
