### ISSUE TITLE
Set a default background color for account avatar

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2392]
Here https://peertube2.cpy.re/videos/watch/04af977f-4201-4697-be67-a8d8cae6fa7a we can see
![1d1](https://user-images.githubusercontent.com/57924087/71962885-211c1280-3203-11ea-8342-8c010f3264fc.png)
 that it doesn't look good when the channel avatar is visible through the account avatar

**Comment by DontUseGithub** [comment]
@rigelk the fix has worked, but it might have caused another glitch
![aqd](https://user-images.githubusercontent.com/57924087/72137594-c0700f80-3393-11ea-9fdb-fb75d835ec9a.png)
https://peertube2.cpy.re/videos/watch/04af977f-4201-4697-be67-a8d8cae6fa7a

**Comment by rigelk** [comment]
@DontUseGithub the fix is too simple to have caused that.

@Chocobozzz any idea about it? the image `src` attribute seems null.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/62fca05de45848f3241c1b078df51d79692ebfee
