### ISSUE TITLE
When the video is deleted or not exist,  not 404 status code returned

### ISSUE THREAD

**Issue by endokai** [Chocobozzz/PeerTube#2394]
**What happened?**
After deleted video, visiting the original video page (example: https://example.com/videos/watch/11111111-1111-1111-1111-111111111111) still returns 200 status response code. And not only that, if enter a random text (example: https://example.com/videos/watch/aaaaaabbb), the watch page will be always 200 status code.
For users, although a "Not found" prompt will be show at load finished, but it is not the correct behavior for SEO and browsers. I observed Mastodon, Mastodon will return a 404 status code on a non-existing toot page.

**What do you expect to happen instead?**
Correctly return 404 status code

**Steps to reproduce:**

1.Delete a video and visit the original URL. Or enter random text
(example: https://example.com/videos/watch/aaaaaabbb)

2.Return 200 status response code. 

**Additional information**
* PeerTube version or URL: v2.0.0
* Browser name/version: Chromium 78.0.3904.63
* NodeJS version: v10.16.3

**Comment by Chocobozzz** [comment]
Thanks, fixed in https://github.com/Chocobozzz/PeerTube/commit/c08579e14fe712cb2264a25daea956e682574335
