### ISSUE TITLE
Impossible login due to underscore commited to dot.

### ISSUE THREAD

**Issue by lionelaubert** [Chocobozzz/PeerTube#2395]
**What happened?**
I've opened an account in 2018 and posted more than 20 videos (I mean, I know how to do)
My login name contains an underscore character : _
Now, when I log in, with success, my account is commuted to a dot one instead of the underscore.

**What do you expect to happen instead?**
I should log to the initial account, with an underscore instead of a dot.

**Steps to reproduce:**

1. Look at the account : https://peertube.mastodon.host/accounts/lionel_a/videos
You notice the account with an underscore is existing, and I have been able to post videos 4 months ago.

2. Look at the account : https://peertube.mastodon.host/accounts/lionel.a/videos
You notice the account seems exist but without any video.

3. I succeed to log in with the "lionel_a" username, but straight after my account is commuted to "lionel.a".
I've posted some details and screen shots : https://framapiaf.org/@lionel_a/103432820668312760

**Additional information**
* PeerTube version or URL: 1.4.0
* Browser name/version: Firefox 71.0
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Do you login using the username or an email?

**Comment by Chocobozzz** [comment]
I found the bug. Thanks for the issue. Should be fixed with https://github.com/Chocobozzz/PeerTube/commit/c4a1811ea888fa98fe7cd6932d82b3d63d366f28

**Comment by lionelaubert** [comment]
Merci beaucoup Chocobozzz pour la rapidité de la réponse !

De mon côté, le bug se poursuit, mais je pense que c'est normal, il faut juste que j'attende que le serveur soit mis à jour.
----Par contre, pour ne pas attendre pour rien, parmi les fichiers qui ont été corrigés, l'un concerne la fonction getContributorsBlacklistEst-ce que mon blocage serait dû à un éventuel blacklistage ?C'est pour m'éviter d'attendre inutilement,
Encore merci,lionel



    Le jeudi 9 janvier 2020 à 14:01:37 UTC+1, Chocobozzz <notifications@github.com> a écrit :  
 
 
Closed #2395.

**Comment by Chocobozzz** [comment]
> l'un concerne la fonction getContributorsBlacklistEst-ce que mon blocage serait dû à un éventuel blacklistage

Nope, it's not related to your bug

**Comment by lionelaubert** [comment]
Ouf !
Thanks, so I'm going to wait the upgrade 😃

(je repasse en français si ça dérange pas)
Et encore un très très grand merci pour avoir développé PT !
Pour l'anecdote, la vidéo que je voulais poster mentionnait à la fin d'utiliser PT à la place de YT... mais paradoxalement j'ai réussi à la poster sur YT mais pas sur PT 😕Pas grave, je vais attendre la MàJ
Bonne journéelionel



    Le jeudi 9 janvier 2020 à 15:17:13 UTC+1, Chocobozzz <notifications@github.com> a écrit :  
 
 

l'un concerne la fonction getContributorsBlacklistEst-ce que mon blocage serait dû à un éventuel blacklistage


Nope, it's not related to your bug
