### ISSUE TITLE
Add Followers and Followings count (UI) in the About page and a button to reveal the full lists

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#2397]
Add Followers and Following count (UI) in the About page:
![adwq](https://user-images.githubusercontent.com/57924087/72138053-9ec35800-3394-11ea-8067-de2bbdd49e19.png)

Add a button to reveal the full lists:
I'd suggest showing only the first 20, 25 urls and then where the list ends, add a button that says - "show full list"
![full-list](https://user-images.githubusercontent.com/57924087/72138920-7a687b00-3396-11ea-9363-73563d5dc270.png)

**Comment by Chocobozzz** [comment]
Why?

**Comment by DontUseGithub** [comment]
> Add Followers and Following count (UI) in the About page

Makes the page more insightful. Later maybe we could also add a way to sort the lists by different factors such as age, nr. of local videos each instance has, etc.


> Add a button to reveal the full lists

The long lists don't look very appealing UI/UX-wise

**Comment by MahdiTurki** [comment]
Hi, is this still not done? If not, may I work on it?

**Comment by Chocobozzz** [comment]
@MahdiTurki yep you can work on it :+1:

**Comment by MahdiTurki** [comment]
This seems more complicated than I thought. 
I am sorry, I have tried but I can't do it.

**Comment by MahdiTurki** [comment]
I am having difficulties, I can't figure out how to create instances so that I can test what I have done. Since there are no actual instances in my database.

**Comment by Chocobozzz** [comment]
Use https://peertube2.cpy.re in https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/environments/environment.hmr.ts#L4

**Comment by MahdiTurki** [comment]
I managed to make the 'show full list' works so that when the users clicks on it it displays all the followers or followings. However I did not find a way to display the number of followers and followings.
I thought about importing all the followers and followings on init but that may take too long to load and it does not seem convenient.
