### ISSUE TITLE
Cannot subscribe peertube channel with mastodon account (webfinger 404 error)

### ISSUE THREAD

**Issue by fweng322** [Chocobozzz/PeerTube#2399]
**What happened?**

Though issue #1528 is marked as fixed, but I still get the same error "Unfortunately, there was an error looking up the remote account." when trying to subscribe a peertube account (channel?) with the "remote subscribe" in the context menu beside the subscribe button.

Peertube channel: https://peertube.slat.org/accounts/mwopus/video-channels
I opened the context menu beside the subscribe button and input the Mastodon account: 
franklin@social.slat.org

It showed the error.

Then I looked at the log and found:

36.227.77.15 - - [10/Jan/2020:21:42:55 +0800] "GET /.well-known/webfinger?resource=acct:aa_space@peertube.slat.org HTTP/1.1" 404 169 "-" "http.rb/3.3.0 (Mastodon/3.0.1; +https://social.slat.org/)"
36.227.77.15 - - [10/Jan/2020:21:42:55 +0800] "GET /.well-known/host-meta HTTP/1.1" 404 169 "-" "http.rb/3.3.0 (Mastodon/3.0.1; +https://social.slat.org/)"

Besides [this page](https://docs.joinmastodon.org/spec/webfinger/) from mastodon document, I couldn't find any document telling us how to configure webfinger for a peertube instance (even that page didn't explain how to configure webfinger for a mastodon instance).

I succeeded to subscribe the peertube channel 
https://peertube2.cpy.re/videos/watch/d107698e-b473-4134-b491-24710e6e7b30
with the same mastodon account.  So I think it should be a configuration problem rather than a bug.  If so, please tell me how to make it work correctly.

**What do you expect to happen instead?**
I should be able to subscribe peertube channel with a mastodon account

**Steps to reproduce:**

1. Open https://peertube.slat.org/accounts/mwopus/video-channels

2. Remote subscribe with a mastodon account (in my case franklin@social.slat.org)

3. It appeared the error "Unfortunately, there was an error looking up the remote account."

**Additional information**
* PeerTube version or URL: 2.0, https://peertube.slat.org/
* Browser name/version: Chromium 78.0, Firefox-esr 68.4.1
* NodeJS version: 10.15.2~dfsg-2

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

log in logs/peertube.log
{"message":"36.227.77.15 - - [10/Jan/2020:13:42:55 +0000] \"GET /video-channels/aa_space HTTP/1.0\" 200 2693 \"-\" \"http.rb/3.3.0 (Mastodon/3.0.1; +https://social.slat.org/)\"\n","level":"info","label":"peertube.slat.org:443","timestamp":"2020-01-10T13:42:55.921Z"}

At the same time log in mastodon access.log
36.227.89.157 - - [10/Jan/2020:21:42:55 +0800] "GET /authorize_interaction?uri=https%3A%2F%2Fpeertube.slat.org%2Fvideo-channels%2Faa_space HTTP/2.0" 200 3910 "https://peertube.slat.org/videos/watch/d2a7c88e-3712-4afe-9596-74ea1e1a18d0" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"

Both 200 OK.

**Comment by fweng322** [comment]
It's the nginx setting problem.  I added alias for /.well-known/ for certbot (at that time no --nginx argument yet) so it affected the webfinger features.  Removing that part of settings works.

**Comment by l1quid8** [comment]
thank you! ive been looking for this fix for a few days now. I appreciate ya
