### ISSUE TITLE
importing video's that are already transcoded

### ISSUE THREAD

**Issue by whohoho** [Chocobozzz/PeerTube#2401]
Is it possible to import video's that are already transcoded in the right formats?

**Comment by rigelk** [comment]
@whohoho the original video can be used as-is, if it matches format, codec, fps and bitrate criteria of one of the activated resolutions. It doesn't allow, however, to upload other resolutions of the video since there is no way to check the resultions you uploaded are effectively of the same video.

**Comment by whohoho** [comment]
How would i do it when i know they are in the right format (on my own instance as the admin)?

I am thinking on how to integrate a live video streaming setup (where i can set the transcoder settings to match those of peertube)

Other usecase would be moving video's from 1 peertube instance i control to another.

**Comment by Chocobozzz** [comment]
@whohoho You could use https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#create-import-video-file-jobjs
