### ISSUE TITLE
Make import job concurrency configurable

### ISSUE THREAD

**Issue by whohoho** [Chocobozzz/PeerTube#2402]
To change the job concurrency, you need to change constants now: https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/constants.ts#L134

It would be nice if that could be configured in the config file.

**Comment by Chocobozzz** [comment]
Some of them cannot be configured because we don't support concurrency in some jobs. What jobs do you want to increase concurrency?

**Comment by whohoho** [comment]
Video transcoding and video import.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/3717
