### ISSUE TITLE
Automatically disable user registration when the number of users reaches a certain threshold

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2403]
How I see it working:
the instance admin sets a limit of users that he wants to have on his instance - for example 2000 users and chooses what happens when the limit is being reached:

1. disable registration completely
2. disable registration but allow registrations via invites

I believe we should somehow encourage server admins to enable this feature because this is how the fediverse should work - many small instances instead of a few big ones.

**Comment by JohnXLivingston** [comment]
Hello,
There is already a subscription limit in the basic configuration. 
The invite system is missing, and is a good idea.

**Comment by rigelk** [comment]
Nice catch @JohnXLivingston 

And since #1212 already exits, I invite you to contribute there.

**Comment by rigelk** [comment]
Nice catch @JohnXLivingston 

And since #1212 already exits, I invite you to contribute there.
