### ISSUE TITLE
Support more markdown features such as code blocks

### ISSUE THREAD

**Issue by NilsIrl** [Chocobozzz/PeerTube#2404]
**What happened?**

I tried putting a code block in the description of a video.

**What do you expect to happen instead?**

The formatting was a little strange. The tooltip doesn't report code blocks as being a feature.

**Additional information**
* PeerTube version or URL: `PeerTube v2.0.0` hosted at `peertube.co.uk`

Features:

- [ ] codeblocks

**Comment by Chocobozzz** [comment]
Hi,

I'm not sure we want to include code blocks in our simple markdown renderer:
 * It changes the many CSS properties (background, typo, overflow...) and can lead to some issues in the way we want to display the video descriptions
 * It's not used by many people, especially to describe a video
 * I don't think many other federated software have code blocks support to render markdown or html

**Comment by mpfaff** [comment]
I'd really appreciate more markdown support. Even code blocks without any highlighting whatsoever would be great!

**Comment by mfuhrmann** [comment]
I just had the same idea.
In my case I wanted to publish guitar tabs, so a `codeblock` would be awesome to write something like

```
  Am	    Fmaj7      C         G
e|-----0---|-----0----|-----0---|-----| 
B|-------1-|-------1--|-------1-|-0-0-| 
G|---2-----|---2------|---0-----|-0-0-| x2
D|---------|-3--------|---------|-----| 
A|-0-------|----------|-3-------|-----| 
E|---------|----------|---------|-3---| 
```

But this could also be solved with an "attach file function" and adding the text file into the post. Ofc, maybe this is rarely used. But attaching a file with a lot of those tabs might be a better solution than spamming the description.
