### ISSUE TITLE
Hide videos with 0 peers until at least 1 peer shows up

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2406]
An example of a video with 0 peers https://peertube2.cpy.re/videos/watch/3767c90c-6c7a-474a-9503-fda9195b4805

IMO it's bad UX if a user clicks on such a video and nothing happens.

We should temporarily hide such videos form all places such as Search, Recommended, Trending etc... and show them again when those videos have at least 1 peer.

**Comment by rigelk** [comment]
> IMO it's bad UX if a user clicks on such a video and nothing happens.

That would be the case if "0 peers" in the player indicator meant no source for the video. But that indicator only counts the number of WebRTC peers, not WebSeeds (servers mirroring the video, of which the server of origin is always part).

**Comment by DontUseGithub** [comment]
But the user still can't watch the video. Should I change the title of the issue? To something like:

> Hide videos that are unplayable until they become playable

**Comment by rigelk** [comment]
@DontUseGithub this video was playable for me, so the issue must lie somewhere else. What is your browser/version?

**Comment by DontUseGithub** [comment]
I've tried it with Firefox 68.3
Firefox 68.4
Firefox 72
Other videos play just fine. Weird.
