### ISSUE TITLE
cant follow peertube account from mastodon

### ISSUE THREAD

**Issue by georgkrause** [Chocobozzz/PeerTube#2408]
**What happened?**

I try to follow an Peertube Account or Channel from Mastodon or Pleroma. They tell me, the request got sent. I even get a notification at peertube that I have a new follower

**What do you expect to happen instead?**

I expect the information that the follow was successful. 

**Steps to reproduce:**

1.

2.

3.

**Additional information**
* PeerTube version or URL: 2.0.0
* Browser name/version: Firefox 72.01
* NodeJS version: ?

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by georgkrause** [comment]
From pinafore I get some more information: 

```
Error: "Request failed: 400"
```

**Comment by georgkrause** [comment]
I can't even follow a channel on my own instance.

**Comment by rigelk** [comment]
What is the PeerTube instance of the channel you are trying to follow?

**Comment by georgkrause** [comment]
https://tube.netzspielplatz.de

Channel is here: https://tube.netzspielplatz.de/video-channels/unfa00/videos

**Comment by Chocobozzz** [comment]
I can reproduce for this channel, but not on other peertube instances. I would need tube.netzspielplatz.de error logs when you try to follow the channel (there is probably an error)
