### ISSUE TITLE
Store and get data in user session

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2417]
In order to develop a captcha plugin using https://www.npmjs.com/package/svg-captcha, I have to store somewhere the generated text. Storing it with PluginStorageManager.storeData doesn't seem to be a good idea.
The best solution is probably to store it in the user session. So we need a mecanism for plugin to get and store data in the session (under their namespaces)

**Comment by JohnXLivingston** [comment]
Hum, I just realized that it won't be enough. Because of Angular, there is no backend entry point called when the signup form is displayed. I'll also need this: https://github.com/Chocobozzz/PeerTube/issues/2062

**Comment by Chocobozzz** [comment]
It's the use case of `PluginStorageManager.storeData` that can handle JSON. So just put user data in `users -> [userId] -> {... }`

Then, you can fetch the data using `storageManager.getData('users.123')`

**Comment by JohnXLivingston** [comment]
How can I get the userId in a plugin?
And it won't work in my case (captcha system for signup). Because the user has not signup yet. I can use the IP as a key (and store multiple captcha, in case there are several users with the same IP). But it seems overrated. 

Additional question: how can I delete a date stored? storeData(key, null)?

**Comment by Chocobozzz** [comment]
> Because the user has not signup yet. I can use the IP as a key

You can generate a string in the client and put it in the body when you requests the captcha, as a unique identifier.

> Additional question: how can I delete a date stored? storeData(key, null)?

I don't know, you could test and create an issue so we develop a dedicated function.
