### ISSUE TITLE
Don't receive anymore videos from the instance i subscribed

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#2418]
**What happened?**
I subscribed to another instance, but the last video i received from the said instance is older than the last video actually published on it (1 month ago vs 1 week ago).
**What do you expect to happen instead?**
The video appears the same time on the instance and on mine.
**Steps to reproduce:**

1.Subscribe to an instance.

2.Receive videos from the instance.

3.Your instance don't receive any other video from the remote instance.

**Additional information**
* PeerTube version or URL: 2.0.0
* NodeJS version:10.17.0

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by rigelk** [comment]
Hello, could you please provide more information about your instance and the one you are following? Version and URL in particular.

**Comment by stemy2** [comment]
My instance: peertube.stemy.me
The one i'm following: skeptikon.fr

**Comment by JohnXLivingston** [comment]
Your instance is not listed here: https://skeptikon.fr/about/follows
Maybe try to follow it again?

**Comment by stemy2** [comment]
This is strange. skeptikon is actually in my following list and its state is accepted. How can it be in my following list without me being in its followers list ?

**Comment by JohnXLivingston** [comment]
Was your server offline for a while ? Perhaps it was offline, and your score on skeptikon decreased too much.

**Comment by stemy2** [comment]
No, it wasn't. Anyway, i desubscribed then resubscribed and it solved everything.
