### ISSUE TITLE
High-res video pre-loading (before clicking play) doesn't stop

### ISSUE THREAD

**Issue by SamantazFox** [Chocobozzz/PeerTube#2419]
**What happened?**

Max resolution version of the video starts to load in the background, even before clicking on "play"

**What do you expect to happen instead?**

Do either of the following, until I press "play":
 * Load only the first few seconds of the video (like invidio.us does)
 * Do not load anything

This is meant for people (like me) with metered connection.
If I leave the page open and go to the bathroom, I can have a few gigs out if the video proposed is 1080p or more.

**Steps to reproduce:**

0. Autoplay is disabled in the browser's options
1. Without an account, access an instance
2. Click on any video
3. Look at network stats (under the browser's "developer tools")
4. There is a continuous stream of XHR request loading the video chunks

**Additional information**

* PeerTube version or URL:
  tested on:
  - https://peertube.cpy.re/
  - https://video.latavernedejohnjohn.fr/

* Browser name/version:
  Firefox v69.0.1 (64-bit) on Linux

Here is an example, on a 1080p video, after ~50s of page stand-by.
![region_1579306512](https://user-images.githubusercontent.com/52980486/72654476-0890c280-3990-11ea-9f45-f5fb0f90b609.png)

**Comment by Chocobozzz** [comment]
Yes you're right, web browsers block autoplay but webtorrent still downloads all video data. It's not the case with our new HLS player where the video is buffered. This new player is enabled for new uploaded videos on instances that enabled this option (that will be the default in the future).
