### ISSUE TITLE
Remote subscribe should respect path in webfinger

### ISSUE THREAD

**Issue by annando** [Chocobozzz/PeerTube#2422]
**What happened?**

I tried to remotely follow a Peertube account with my Friendica account.

**What do you expect to happen instead?**

I got an error that the page "authorize_interaction" doesn't exist on my Friendica server.

**Steps to reproduce:**

1. Go to "subscribe"

2. Enter the Friendica handle.

3. Go to "remote subscribe"

I saw PR https://github.com/Chocobozzz/PeerTube/pull/1498 which should perform a webfinger request to fetch the correct endpoint. However I saw no webfinger requests at my server. In which version this was included? Possibly the used server is old.

**Additional information**
* PeerTube version or URL: https://video.blender.org

**Comment by Chocobozzz** [comment]
Hi,

The blender instance version is very old. Please could you try with https://peertube2.cpy.re/video-channels/a75cbdf4-acf2-45c0-a491-e9b28939f8db/videos?

**Comment by annando** [comment]
Seems to work. Only problem is that my browser (Firefox) is blocking the popup, so that I have to permit it, to open the remote login. (But this is another problem)
