### ISSUE TITLE
Grab From YouTube Before Using Peertube Copy

### ISSUE THREAD

**Issue by trymeouteh** [Chocobozzz/PeerTube#2423]
If a video is uploaded to Peertube that is from YouTube. I think Peertube should not dish our the peertube copy of the video but grab the video from YouTube but block the ads and tracker and not webtorrent the video. Now if Peertube cannot grab the YouTube video because it has been taken down from YouTube, it will fallback and use the Peertube copy and webtorrent the Peertube copy.

I think this will reduce the bandwidth drastically since YouTube will dish out the bandwidth. Many of us dislike YouTube, but minus well let them pay for dishing out the bandwidth whenever we can. Invidious is built on this model since Invidious is a alternative YouTube front end but relies on YouTube to dish out the video and Invidious blocks the ads and trackers. So your privacy is respected, less bandwidth required from a peertube instance and Google is the one having to provide the video and pay for the bandwidth. Why not make Google pay for bandwidth when we have nothing to lose.

**Comment by rigelk** [comment]
Hi! Please look out for related issues before creating one, as #1045 already covers this. You can then detail further your use case there, and upvote the issue to help us triage it.
