### ISSUE TITLE
API doesn't give inReplyToCommentId with a comment-thread request

### ISSUE THREAD

**Issue by B0pol** [Chocobozzz/PeerTube#2425]
**What happened?**
With api, inReplyToCommentId always give null, even with comments that have replies.
**What do you expect to happen instead?**
Give the parent comment id
**Steps to reproduce:**

1. Make an API request to a video, which have comments, and comments with reply
For example, let's take [What is PeerTube? — API v1](https://framatube.org/api/v1/videos/9c9de5e8-0a1e-484a-b099-e80766180a6d/comment-threads)

2. Remark that the API reply tells us no comments have inReplyToCommentId different from null. Even though some comments have totalReplies ≥ 0

3. Go on [What is PeerTube? — framatube.org](https://framatube.org/videos/watch/9c9de5e8-0a1e-484a-b099-e80766180a6d) and remark that two comments have replies: the one from ``e@spacepub.space`` & the one from ``voelpool@video.ploud.fr``

**Additional information**
* PeerTube version or URL: API v1, PeerTube v2.0.0
* Browser name/version: Firefox 72

# Related issue
threadId is always giving comment's id. Shouldn't it give the thread id, which would be the same for each replies of a comment?

**Comment by Chocobozzz** [comment]
I don't think there is an issue here. `inReplyToCommentId` tells you if the comment **is** a reply, and to **which comment** it is a reply. Threads (that are in fact a reply to a video) are not a reply to comments, so this field is `null`.

> With api, inReplyToCommentId always give null, even with comments that have replies.

There is a misunderstanding: `inReplyToCommentId` is used to find the parent comment, not the children comments.

**Comment by B0pol** [comment]
> There is a misunderstanding: inReplyToCommentId is used to find the parent comment, not the children comments.

That's exactly what I understood, read again:
> What do you expect to happen instead?
> Give the parent comment id

In fact, I found out the API doesn't give comment replies with the ``instance/api/v1v/videos/video_id/comment-threads`` request.
[video](https://framatube.org/videos/watch/9db9f3f1-9b54-44ed-9e91-461d262d2205) & [api request](https://framatube.org/api/v1/videos/9db9f3f1-9b54-44ed-9e91-461d262d2205/comment-threads)
This video has only 5 primary response. API also say 5: 
![image](https://user-images.githubusercontent.com/58657617/73064004-1b2b6000-3e98-11ea-82fd-41fcb1984c96.png)

But the video has one comment with 2 replies:
![image](https://user-images.githubusercontent.com/58657617/73064142-6e051780-3e98-11ea-993d-7b176eb2f2ea.png)
the comment from emabgd
How do I get comment replies with API then?

**Comment by Chocobozzz** [comment]
Use https://docs.joinpeertube.org/api-rest-reference.html#tag/Video-Comment/paths/~1videos~1{id}~1comment-threads~1{threadId}/get

So https://framatube.org/api/v1/videos/9db9f3f1-9b54-44ed-9e91-461d262d2205/comment-threads/186

**Comment by B0pol** [comment]
Ok, thank you for the help, and sorry the inconvenience.
