### ISSUE TITLE
Change the video grid from 6 columns to 5

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#2428]
The current grid has 6 columns of videos https://peertube2.cpy.re/videos/most-liked and in my opinion it makes it harder to view the page. You feel lost because too much content in being shown to you. I don't know how to better describe it :) But if we take a look at [youtube](https://www.youtube.com/)'s grid then we see that they have 4 columns, which looks good too, tho 5 may be enough.

**Comment by frankstrater** [comment]
It has 4 columns on my laptop, so it depends on your screen size. I guess you mean it should have a maximum of 4 columns, but I don't presume every user is happy with that. I would suggest to don't change anything in PeerTube (or add your own CSS) and just use your browser zoom.

**Comment by DontUseGithub** [comment]
> I guess you mean it should have a maximum of 4 columns

5 (not 4) but yes, that's the idea behind this issue

**Comment by rigelk** [comment]
@DontUseGithub I guess that by reducing the number of columns, you also expect miniatures to scale up to fill the space?

**Comment by DontUseGithub** [comment]
Hi @rigelk 
yes

**Comment by rigelk** [comment]
@DontUseGithub then the issue is a bit more complex. Miniatures currently have a fixed size, and the grid keeps enough margins to cope with toggling the menu.

**Comment by Chocobozzz** [comment]
We implemented dynamic miniature sizes some weeks ago.
