### ISSUE TITLE
Audio-only is available even for video which are not encoded in audio-only mode

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2429]
**What happened?**
After upgrading to v2.1.0-RC1, if I watch an old video (uploaded before this version), the player has the option «audio-only» while the audio-only file does not exist. And it continues to play the video with the previous resolution.

**What do you expect to happen instead?**
The «audio-only» option should not be displayed

**Steps to reproduce:**

1. Peertube v2.0.0, upload a video

2. Upgrade to v2.1.0-RC1

3. Activate the «audio-only» option in administration page.

4. Go on the video, and open the quality selector

**Additional information**
* PeerTube version or URL: https://videos.globenet.org
* Browser name/version: Firefox
* NodeJS version: v10.15.2

**Comment by Chocobozzz** [comment]
Thanks for the issue. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/8ff604c7e300eec5c0b29644292d6399521a1930
