### ISSUE TITLE
Chromecast support

### ISSUE THREAD

**Issue by trading-peter** [Chocobozzz/PeerTube#2430]
Hello,

My question would be is there any plans to support Chromecast?

Thanks for this awesome project and all the time and effort put into it.

**Comment by Chocobozzz** [comment]
I don't know the Chromecast protocol but you can try using Firefox Android: https://support.mozilla.org/en-US/kb/use-firefox-android-send-videos-chromecast

Or using our CLI script: https://docs.joinpeertube.org/#/maintain-tools?id=peertube-watchjs

**Comment by rigelk** [comment]
Also note that there is a videojs plugin adding some Chromecast integration, so you can create a plugin easily.

**Comment by pkaske** [comment]
Thanks for the feedback. I will look into it.

**Comment by Tak** [comment]
For what it's worth, I took a stab at creating a peertube plugin that uses `@silvermine/videojs-chromecast`, but it seems nontrivial, partially because the chromecast plugin has a bunch of requirements for videojs core options to be injected at setup time.
Web dev isn't my area, though, maybe I'm just missing something that should be obvious?

**Comment by StarFang208** [comment]
Sounds great, so people could watch a peertube channel from their TVs.

Also, Kodi and Amazon Fire support could be even better.

**Comment by rigelk** [comment]
@StarFang208 there is already a PeerTube app on Kodi: https://peertube.cpy.re/videos/watch/f8a4b32d-0bf1-48ed-af9f-d8c5d87efedb

**Comment by StarFang208** [comment]
@rigelk Sorry, I didn't see that.

Although, more media centers support could be better for expanding the audience.

**Comment by kontrollanten** [comment]
@Tak I'm interested in this as well. How did it with your plugin? I'm quite experience web dev so hopefully I can help. Do you have any repo with your code so far?

**Comment by Tak** [comment]
I eventually gave up entirely.
With the direct-integration approach, I was able to get the cast button showing in the player toolbar, and connecting to the chromecast, but then there would be an infinite progress bar and the video wouldn't actually play.
I've pushed the final result of my experimentation to https://github.com/Tak/PeerTube/tree/cast-hackery (on top of peertube 2.4.0), so you can take a look if you're interested.
If I recall correctly, it also requires some additional copying of image resources after the build is done, as documented at https://github.com/silvermine/videojs-chromecast/blob/master/README.md

**Comment by Chocobozzz** [comment]
Hello,

Using peertube plugin hooks I think you can add chromecast support to the player using/by adapting this code: https://github.com/silvermine/videojs-chromecast/blob/master/src/js/index.js

**Comment by Tak** [comment]
Hi, please don't dismiss this issue as trivial **unless you have done it**

**Comment by Chocobozzz** [comment]
We don't plan to do it.

**Comment by rigelk** [comment]
> Using peertube plugin hooks I think you can add chromecast support to the player using/adapting this code: https://github.com/silvermine/videojs-chromecast/blob/master/src/js/index.js

Can confirm the plugin system allows deploying videojs plugins, as was done in previous plugins (i.e. https://framagit.org/rigelk/peertube-plugin-koukoku).

**Comment by Tak** [comment]
No, that's clear, what I mean is that it is not as straightforward as it might look, and it is **_not_** as simple as other videojs plugins, although I guess I don't know what point there is in discussing it if you've decided not to support it.

**Comment by Chocobozzz** [comment]
We never said it was straightforward or trivial to create this plugin. Just that we think the peertube plugin system can handle this use case. If not then create a dedicated issue with the API you need to create such plugin.
