### ISSUE TITLE
Cyrillic support

### ISSUE THREAD

**Issue by Cooliq** [Chocobozzz/PeerTube#2431]
I can’t name the video or add a description in Russian language. I recieve error "Server error. Please try again later."

Steps to reproduce:
1. Upload or edit video
2. Write Title or Description on Cyryllic
3. Save

Additional information:
- PeerTube v2.0.0
- Error code

`error[29.01.2020, 10:31:51] Cannot execute updateVideo with many retries. { "err": { "stack": "TypeError: video.VideoChannel.Account.toFormattedSummaryJSON is not a function\n at Object.videoModelToFormattedJSON (/var/www/peertube/versions/peertube-v2.0.0/dist/server/models/video/video-format-utils.js:44:45)\n at self.toFormattedJSON (/var/www/peertube/versions/peertube-v2.0.0/dist/server/models/video/video.js:851:37)\n at Object.videoModelToFormattedDetailsJSON (/var/www/peertube/versions/peertube-v2.0.0/dist/server/models/video/video-format-utils.js:75:33)\n at self.toFormattedDetailsJSON (/var/www/peertube/versions/peertube-v2.0.0/dist/server/models/video/video.js:854:37)\n at /var/www/peertube/versions/peertube-v2.0.0/dist/server/controllers/api/videos/index.js:209:83\n at Generator.next (<anonymous>)\n at /var/www/peertube/versions/peertube-v2.0.0/dist/server/controllers/api/videos/index.js:8:71\n at new Promise (<anonymous>)\n at __awaiter (/var/www/peertube/versions/peertube-v2.0.0/dist/server/controllers/api/videos/index.js:4:12)\n at updateVideo (/var/www/peertube/versions/peertube-v2.0.0/dist/server/controllers/api/videos/index.js:206:12)\n at callback (/var/www/peertube/versions/peertube-v2.0.0/dist/server/helpers/database-utils.js:7:25)\n at Timeout.retryAttempt [as _onTimeout] (/var/www/peertube/versions/peertube-v2.0.0/node_modules/async/retry.js:132:9)\n at ontimeout (timers.js:436:11)\n at tryOnTimeout (timers.js:300:5)\n at listOnTimeout (timers.js:263:5)\n at Timer.processTimers (timers.js:223:10)", "message": "video.VideoChannel.Account.toFormattedSummaryJSON is not a function" } }
error[29.01.2020, 10:31:51] Error in controller. { "err": "TypeError: video.VideoChannel.Account.toFormattedSummaryJSON is not a function\n at Object.videoModelToFormattedJSON (/var/www/peertube/versions/peertube-v2.0.0/dist/server/models/video/video-format-utils.js:44:45)\n at self.toFormattedJSON (/var/www/peertube/versions/peertube-v2.0.0/dist/server/models/video/video.js:851:37)\n at Object.videoModelToFormattedDetailsJSON (/var/www/peertube/versions/peertube-v2.0.0/dist/server/models/video/video-format-utils.js:75:33)\n at self.toFormattedDetailsJSON (/var/www/peertube/versions/peertube-v2.0.0/dist/server/models/video/video.js:854:37)\n at /var/www/peertube/versions/peertube-v2.0.0/dist/server/controllers/api/videos/index.js:209:83\n at Generator.next (<anonymous>)\n at /var/www/peertube/versions/peertube-v2.0.0/dist/server/controllers/api/videos/index.js:8:71\n at new Promise (<anonymous>)\n at __awaiter (/var/www/peertube/versions/peertube-v2.0.0/dist/server/controllers/api/videos/index.js:4:12)\n at updateVideo (/var/www/peertube/versions/peertube-v2.0.0/dist/server/controllers/api/videos/index.js:206:12)\n at callback (/var/www/peertube/versions/peertube-v2.0.0/dist/server/helpers/database-utils.js:7:25)\n at Timeout.retryAttempt [as _onTimeout] (/var/www/peertube/versions/peertube-v2.0.0/node_modules/async/retry.js:132:9)\n at ontimeout (timers.js:436:11)\n at tryOnTimeout (timers.js:300:5)\n at listOnTimeout (timers.js:263:5)\n at Timer.processTimers (timers.js:223:10)" } `

**Comment by Chocobozzz** [comment]
Could you enable debug logs in your peertube configuration and paste it?

**Comment by Cooliq** [comment]
> 
> 
> Could you enable debug logs in your peertube configuration and paste it? And what is your instance URL?

https://aoca.ru

[debug.txt](https://github.com/Chocobozzz/PeerTube/files/4127016/debug.txt)

**Comment by Chocobozzz** [comment]
Thanks.

```
"SequelizeDatabaseError: character with byte sequence 0xd0 0x9d in encoding \"UTF8\" has no equivalent in encoding \"LATIN1\"
```

Could you go in your DB using psql (`sudo -u postgres psql peertube_prod`) and run ` \l peertube_prod`? I don't really understand why postgresql tries to convert the string in LATIN1.

**Comment by Cooliq** [comment]
> 
> 
> Thanks.
> 
> ```
> "SequelizeDatabaseError: character with byte sequence 0xd0 0x9d in encoding \"UTF8\" has no equivalent in encoding \"LATIN1\"
> ```
> 
> Could you go in your DB using psql (`sudo -u postgres psql peertube_prod`) and run ` \l peertube_prod`? I don't really understand why postgresql tries to convert the string in LATIN1.

`List of databases
     Name      |  Owner   | Encoding | Collate | Ctype | Access privileges
---------------+----------+----------+---------+-------+-------------------
 peertube_prod | peertube | LATIN1   | en_US   | en_US |
(1 row)
`

**Comment by Chocobozzz** [comment]
You need to update your database encoding. Try https://tutorials.technology/tutorials/How-to-change-postgresql-database-encoding-to-UTF8-from-SQL_ASCII.html

I'll update the documentation to add `-E utf8` to the `createdb` command

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/commit/0539dba824bc3b964faaba358d8e7836e006b899
