### ISSUE TITLE
[Feature] Channel Directory

### ISSUE THREAD

**Issue by DeadSuperHero** [Chocobozzz/PeerTube#2434]
One thing that PeerTube currently struggles with involves the discovery of channels and videos. Although some measures have been taken, such as the Joinpeertube relay and third-party solutions like Peertube Index, it remains difficult to discover people making original videos for the fediverse, both on local instances as well as across the known network.

A solution that I'm proposing would be to add a Directory feature to PeerTube. Channels opt-in to be seen by the Directory, which lists:

* Local channels the instance knows about
* Remote channels the instance knows about, based on what remote instances are being followed by the local one

In each case, the Directory only shows channels that agree to opt-in to this discovery feature. The Directory then shows:

* Channel Name
* Channel Thumbnail
* Brief Channel Description
* Keywords relating to channel (if available)
* Number of uploaded videos

Users can search the directory based on names or keywords, or can also sort alphabetically or by number of uploads.

**Comment by DeadSuperHero** [comment]
As an example of prior art, [Hubzilla](https://Hubzilla.org) is one such fediverse system that offers a searchable federated directory.

![directory-search](https://user-images.githubusercontent.com/401560/73387257-e5221d80-4295-11ea-9cd2-483c69e45815.jpg)

In Hubzilla's case, the Directory shows local and federated accounts, and seems to share address book entries between connected instances, making an even bigger directory. I'm not sure we necessarily want a directory system that automatically populates results based on the contents of your friends' directories, but populating a directory based on who is on your local instance, and who is on the instances your instance is following, seems like it could be a safe choice.

**Comment by rigelk** [comment]
Hi! Please look out for related issues before creating one, as #1465 already covers this. You can then detail further your use case there, and upvote the issue to help us triage it.
