### ISSUE TITLE
Docker instructions lead to 404

### ISSUE THREAD

**Issue by Darkknight33** [Chocobozzz/PeerTube#2436]
**What happened?**

Installed Peertube via docker installation method referenced here: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/docker.md After installation completes accessing peertube leads to a 404 page. 

**What do you expect to happen instead?**
Peertube to be accessible after startup via the IP address directly or via the domain I set. 

I believe the issue is with Traefik's redirect. The logs indicate successful server startup. I have tried exposing port 9000 and disabling traefik to see if I can contact peertube directly, but this also doesn't work. 

Traefik's container logs are empty even with debug enabled in the .toml file. 

Maybe more detailed instructions in the 'tweak traefik.toml file might be helpful? The instructions seem to have a lot of holes around configuring peertube during setup i.e. "Tweak the settings" is written in place of actual documentation detailing which specific lines need to be edited and how. While I believe I have edited these correctly, clearly there is some problem with what I'm doing. 

I'd like to be able to contact peertube directly to isolate the issue to traefik or not. Uncommenting the port in docker-compose.yml leads to a port conflict with traefik. Changing it from 80:9000 to 81:9000 stops the conflict but doesn't fix the access problem. Changing traefik.enable: "true" to false didn't work. Altering production.yml to disable https and change the port to 81 doesn't work. 

I've been struggling with this for a while and can't make any headway. I had peertube running in the past, though that was a manual install. Usually using dockers is a bit more straight-forward, but this has been a headache. 

Server log: (actual domain & password censored)

> root@debian:~/peertube# docker-compose up
Starting peertube_redis_1         ... done
Starting peertube_reverse-proxy_1 ... done
Starting peertube_postgres_1      ... done
Starting peertube_postfix_1       ... done
Recreating peertube_peertube_1    ... done
Attaching to peertube_reverse-proxy_1, peertube_redis_1, peertube_postgres_1, peertube_postfix_1, peertube_peertube_1
redis_1          | 1:C 29 Jan 21:10:58.299 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1          | 1:C 29 Jan 21:10:58.299 # Redis version=4.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1          | 1:C 29 Jan 21:10:58.299 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1          | 1:M 29 Jan 21:10:58.301 * Running mode=standalone, port=6379.
redis_1          | 1:M 29 Jan 21:10:58.301 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1          | 1:M 29 Jan 21:10:58.301 # Server initialized
redis_1          | 1:M 29 Jan 21:10:58.301 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1          | 1:M 29 Jan 21:10:58.301 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1          | 1:M 29 Jan 21:10:58.301 * DB loaded from disk: 0.000 seconds
redis_1          | 1:M 29 Jan 21:10:58.301 * Ready to accept connections
postgres_1       |
postgres_1       | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1       |
postgres_1       | 2020-01-29 21:10:58.671 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1       | 2020-01-29 21:10:58.672 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1       | 2020-01-29 21:10:58.679 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1       | 2020-01-29 21:10:58.709 UTC [20] LOG:  database system was shut down at 2020-01-29 21:10:29 UTC
postgres_1       | 2020-01-29 21:10:58.720 UTC [1] LOG:  database system is ready to accept connections
peertube_1       |
peertube_1       | > peertube@2.0.0 start /app
peertube_1       | > node dist/server
peertube_1       |
postfix_1        | Starting Postfix Mail Transport Agent: postfix.
postfix_1        | rsyslogd:  [origin software="rsyslogd" swVersion="8.1901.0" x-pid="121" x-info="https://www.rsyslog.com"] start
postfix_1        | postfix/master[120]: daemon started -- version 3.4.7, configuration /etc/postfix
peertube_1       | [xxxxxxxxxxxxxxxx:443] 2020-01-29 21:11:02.049 warn: Directory of streaming_playlists should not be in the production directory of PeerTube. Please check your production configuration file.
peertube_1       | [xxxxxxxxxxxxxxxx:443] 2020-01-29 21:11:02.739 info: Database peertube is ready.
peertube_1       | [xxxxxxxxxxxxxxxx:443] 2020-01-29 21:11:02.989 info: Using postfix:25 as SMTP server.
peertube_1       | [xxxxxxxxxxxxxxxx:443] 2020-01-29 21:11:02.991 info: Testing SMTP server...
postfix_1        | postfix/smtpd[126]: connect from peertube_peertube_1.peertube_default[172.18.0.5]
peertube_1       | [xxxxxxxxxxxxxxxx:443] 2020-01-29 21:11:03.030 info: Connection established to 172.18.0.4:25 {
peertube_1       |   "component": "smtp-connection",
peertube_1       |   "sid": "xxxxxxxxxxx",
peertube_1       |   "tnx": "network",
peertube_1       |   "localAddress": "172.18.0.5",
peertube_1       |   "localPort": 50206,
peertube_1       |   "remoteAddress": "172.18.0.4",
peertube_1       |   "remotePort": 25
peertube_1       | }
postfix_1        | postfix/smtpd[126]: disconnect from peertube_peertube_1.peertube_default[172.18.0.5] ehlo=1 quit=1 commands=2
peertube_1       | [xxxxxxxxxxxxxxxx:443] 2020-01-29 21:11:03.040 info: Successfully connected to SMTP server.
peertube_1       | [xxxxxxxxxxxxxxxx:443] 2020-01-29 21:11:03.059 info: Cleaning HTML cache.
peertube_1       | [xxxxxxxxxxxxxxxx:443] 2020-01-29 21:11:03.080 info: Connection closed {
peertube_1       |   "component": "smtp-connection",
peertube_1       |   "sid": "xxxxxxxxxxx",
peertube_1       |   "tnx": "network"
peertube_1       | }
peertube_1       | [xxxxxxxxxxxxxxxx:443] 2020-01-29 21:11:03.108 info: Server listening on 127.0.0.1:9000
peertube_1       | [xxxxxxxxxxxxxxxx:443] 2020-01-29 21:11:03.108 info: Web server: https://xxxxxxxxxxxxx

**Comment by Chocobozzz** [comment]
Try to put `0.0.0.0` in your configuration file: https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/config/production.yaml#L2

**Comment by Darkknight33** [comment]
It was on 0.0.0.0 also tried 127.0.0.1. My current config file is identical to the linked file except for the hostname & admin email being defined.

**Comment by Darkknight33** [comment]
Solved the issue: Hostname on the system hostname/hosts file and the hostname listed in the peertube config files didn't match exactly. Once I corrected those, I stopped getting the 404. Reset my peertube configs to default with the only change being adding port 9000 mapping for access in my internal network.
