### ISSUE TITLE
Allow to remove root user if there are other admins

### ISSUE THREAD

**Issue by tcitworld** [Chocobozzz/PeerTube#244]
Following #243, I had to create another user and set it as admin manually. I can't remove the old `root` account though.

**Comment by Chocobozzz** [comment]
I disagree, `root` is like a superadmin and nobody should change his role or remove him. This way the person who installed peertube keeps the entire control of his instance, even if there are other administrators.

**Comment by tcitworld** [comment]
What are the powers of the superadmin that regular admins don't have ? Is the root username hardcoded somewhere or can I change it ?
