### ISSUE TITLE
(v2.1.0-rc.1) "If you are looking for an account… Currently this instance doesn't allow for user registration" [BUG]

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2441]
**What happened?**

This message:
> If you are looking for an account…
> Currently this instance doesn't allow for user registration, but you can find an instance that gives you the possibility to sign up for an account and upload your videos there.
> Find yours among multiple instances at https://joinpeertube.org/instances. 

appears even when an instance allows users to sign up.

**What do you expect to happen instead?**

The message should not appear when an instance allows users to sign up.

**Steps to reproduce:**

1. visit https://vloggers.social

2. Click the upload button (top right)

**Comment by DontUseGithub** [comment]
weird. 
on their about page https://vloggers.social/about/instance 
the **User registration allowed** field - has an :x:  which means that they don't allow that but they have the "**create an account**" button (top left).

**Comment by Chocobozzz** [comment]
It was just a cache issue.

**Comment by stemy2** [comment]
So...ican i solve it myself or have i to wait for the publication of a patch ?
