### ISSUE TITLE
Video compression options

### ISSUE THREAD

**Issue by IvanlokoBR** [Chocobozzz/PeerTube#2442]
Hello, I would like to suggest that the possibility to choose the video quality be added to the admin panel.

Preset: from very fast to very low as this would save a lot of space by compressing the video and if possible use CRF which is more efficient because I kept the video all in the same quality avoiding squarely from somewhere.

As it uses FFMPEG it already has these functions I believe it is something that everyone would like because it saves space and traffic everyone wants!

**Comment by kenshin33** [comment]
Hello,
I'd add maybe concider the values set by the admin as an upper limite or the default and let the users set the values --up to or less what the admin has set--when uploading??

**Comment by IvanlokoBR** [comment]
@kenshin33  Insert in the administrator panel the possibility to modify the FFMPEG option CRF and Preset, CRF = quality / preset = conversion time vs size in megs. Example CRF 23 very low preset would result in extremely compressed videos with excellent quality sacrificing processor usage but those with weak processor only change the preset to fast but sacrificing size in megs. Something I found an error is not converting the source file, peertube uses it as the highest resolution and converts the lowest ones should convert the source file too and delete it after keeping only the converted ones.

sorry for the writing i'm brazilian i'm using google translator

Brazil 
Inserir no painel administrador a possibilidade de modificar o FFMPEG opção CRF  e Preset,  CRF = qualidade / preset = tempo de conversão vs tamanho em megas. Exemplo CRF 23 preset very low resultaria em videos extremamente compactados com excelente qualidade sacrificando uso do processador porém quem possui processador fraco só mudar o preset para fast porém sacrificando tamanho em megas. Algo que achei um erro é não converter o arquivo  de origem, peertube usa o mesmo como resolução mais alta e converte as mais baixa deveria converte o arquivo de origem também e excluir o mesmo depois mantendo só o convertidos.

**Comment by Chocobozzz** [comment]
In the next release, you'll be able to create plugins to change transcoding options/encoders: https://docs.joinpeertube.org/contribute-plugins?id=add-new-transcoding-profiles
