### ISSUE TITLE
Can't watch any video on some instances

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#2443]
**What happened?**
I tried to watch some videos in many instances, but some of it are not working for whatever reason. The buffering icon is spinning, but the download stops after a couple of seconds and the time indicator shows "0:00/-:--". But when i paste the direct video URL on a media player, it works fine.
**What do you expect to happen instead?**
Being able to watch a video.
**Steps to reproduce:**

1. Go to a random instance.

2. Click on a video

3.

**Additional information**
* PeerTube version or URL: peertube.stemy.me, skeptikon.fr (2 examples of not working instances)
* Browser name/version: Firefox
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by DontUseGithub** [comment]
Can you share a few specific links that didn't work for you?

**Comment by stemy2** [comment]
https://peertube.stemy.me/videos/watch/9be29e16-f8d4-47bf-a026-af803dbffb72
https://peertube.stemy.me/videos/watch/fa100d4e-2c39-4853-8be0-ba82f50a74d5

**Comment by stemy2** [comment]
Maybe the problem is my local connection because i tried with the videos here above with my 4G and it works without problem. But i don't understant why not all instances -and video sharing website- have this problem.

**Comment by Jean-Jelly** [comment]
> 
> 
> https://peertube.stemy.me/videos/watch/9be29e16-f8d4-47bf-a026-af803dbffb72
> https://peertube.stemy.me/videos/watch/fa100d4e-2c39-4853-8be0-ba82f50a74d5

Hi, Both links work for me, I can watch both videos without problems. I use a normal internet connection, without lte or similar.

**Comment by stemy2** [comment]
Actually, it was my connection.
