### ISSUE TITLE
Error, if i'm trying to upload a flac file

### ISSUE THREAD

**Issue by Jean-Jelly** [Chocobozzz/PeerTube#2444]
**My Problem:**
Hi, I'm trying to upload my audio files as flac to my peertube instance, but when I upload the file the upload seems to work, but as soon as it is finished the progress bar shows me 100%, but after that I don't get a completion message. Then when I go to videos, the file is not uploaded and I get a popup with "server error" on the side.

**I made a short video so that you can better understand the process I describe above:**
[Video](https://mytube.levijataner.net/videos/watch/e440f07f-f73b-4313-a7d3-f26452c2d307)

**What I did to reproduce it:**
1. I changed the file name.

2. I uploaded the same file in mp3 and ogg, then it works.

3. I restarted the instance and tried different channels that I created on my instance.

4. When uploading, I tried to select private and public once.

**What do you expect to happen instead:**
That the audio file is uploaded correctly and without errors, as with all other formats, and that I can play it back on my peertube instance as usual.

**Additional information:**
* PeerTube version or URL: PeerTube v2.0.0 (for url, see videolink)
* Browser name/version: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:72.0) 
* NodeJS version: v10.15.2
* ffmpeg version 4.1.4-1~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 8 (Debian 8.3.0-6)
* Debian Buster, Linux version 5.3.13-2-pve (build@pve) (gcc version 8.3.0 (Debian 8.3.0-6)) 
(its a lxc container, that running on my linux server, proxmox)

**Log of my peertube instance, under administration -> logs:**
[Log - Pastebin](https://pastebin.com/pcJCtM49)

**Comment by Jean-Jelly** [comment]
**Addition:**
The files I wanted to upload as audio files were converted from a .wav to a .flac using FormatFactory. Now I took a completely different flac that was not converted by me, now the upload worked, but when I want to play the audio file, it shows me the message: "No compatible source could be found.

When I retrieve the video list, it has been saying "Waiting for transcoding" for more than 10 minutes.

**In the log, it now says:**
[Pastebin](https://pastebin.com/4MW3WsUC)

**Comment by Chocobozzz** [comment]
Please could you send me the two bugged FLAC files?

**Comment by Jean-Jelly** [comment]
> 
> 
> Please could you send me the two bugged FLAC files?

Can I send the files to you via e-mail? One of the two files is copyrighted and I do not have the permission to upload it publicly.

**Comment by Chocobozzz** [comment]
Yes, see my email in my github profile

**Comment by Chocobozzz** [comment]
Thanks for your email. I think the bug should be fixed by https://github.com/Chocobozzz/PeerTube/commit/cef4e38f1c9f62c83caa26525a94742ee086f6f1.

But since I don't use Windows, could you try to remove this line from the server build and restart peertube?

**Comment by Jean-Jelly** [comment]
> 
> 
> Thanks for your email. I think the bug should be fixed by [cef4e38](https://github.com/Chocobozzz/PeerTube/commit/cef4e38f1c9f62c83caa26525a94742ee086f6f1).
> 
> But since I don't use Windows, could you try to remove this line from the server build and restart peertube?

Hello and thank you,
how can i find this line, is it in the server folder where peertube is installed?

**Comment by Findus23** [comment]
@Jean-Jelly 
It should be somewhat similar to `/var/www/peertube/peertube-latest/dist/server/initializers/constants.js`

**Comment by Jean-Jelly** [comment]
> 
> 
> @Jean-Jelly
> It should be somewhat similar to `/var/www/peertube/peertube-latest/dist/server/initializers/constants.js`

Yes, thank you very much,
i've found it.


> 
> 
> > Thanks for your email. I think the bug should be fixed by [cef4e38](https://github.com/Chocobozzz/PeerTube/commit/cef4e38f1c9f62c83caa26525a94742ee086f6f1).
> > But since I don't use Windows, could you try to remove this line from the server build and restart peertube?

So, i have changed the line and now i have new error:
![newer3333999](https://user-images.githubusercontent.com/60580980/73967692-a8e76080-4918-11ea-9214-e61f98c76616.png)

Log says: [Log](https://pastebin.com/4KeZvqex)

The flac is the same: [flac](https://mycloud.levijataner.net/index.php/s/PQ7LDkKGEEZ5CgE)

**Comment by Chocobozzz** [comment]
Sorry, try https://github.com/Chocobozzz/PeerTube/commit/26469f9ed85f5e7d67ccecaa820f33e37179b76a instead

**Comment by Jean-Jelly** [comment]
> 
> 
> Sorry, try [26469f9](https://github.com/Chocobozzz/PeerTube/commit/26469f9ed85f5e7d67ccecaa820f33e37179b76a) instead

Hi, now it won't start and when i type journalctl -feu peertube i see error
[Log](https://pastebin.com/5UL2cm6E)

**Comment by Chocobozzz** [comment]
Please the section of the updated file (10 lines before and 10 lines after the line you updated for example)

**Comment by Jean-Jelly** [comment]
> 
> 
> Please the section of the updated file (10 lines before and 10 lines after the line you updated for example)

Ah, sorry, i overlooked that.

Yes, everything's working fine now, thank you very much. I can upload the flac file and play it back without any error messages, great. Thanks :D
