### ISSUE TITLE
Use HTML for description

### ISSUE THREAD

**Issue by busshimoe** [Chocobozzz/PeerTube#2450]
**What happened?**
Remote instances (e.g. Pleroma) should see a description with rich text.
**What do you expect to happen instead?**
Remote instances see Markdown source code.
**Steps to reproduce:**

1. Upload a video

2. Use Markdown in the video description

3. Load the post on a remote Pleroma instance

example: https://tube.blob.cat/videos/watch/5f6966d9-4e88-4770-aa02-b4477aa65f94 https://udongein.xyz/notice/9raisoVpXvCbi79VAm

(note: only the short description is included in the object - the long form should be included instead)

**Additional information**
* PeerTube version or URL: v.2.0.0

**Comment by Chocobozzz** [comment]
See https://github.com/Chocobozzz/PeerTube/issues/2488
