### ISSUE TITLE
Assertion failure and crash in GetImageMagick

### ISSUE THREAD

**Issue by ltning** [Chocobozzz/PeerTube#2451]
**What happened?**
```
[peertube.anduin.net:443] 2020-02-04 00:18:48.176 info: Fetching remote video https://peertube.dk/videos/watch/561e7f57-24c8-4642-
bfb0-6428b563d825.
Assertion failed: (magick != (const unsigned char *) NULL), function GetImageMagick, file MagickCore/magick.c, line 302.`
```
After this peertube crashes and needs a restart

**What do you expect to happen instead?**
No such crash

**Steps to reproduce:**
1. Install (on FreeBSD)
2. Follow `peertube.dk`
3. Watch as a number of videos from there (but not only there) causes a crash

**Additional information**
* PeerTube version or URL: https://peertube.anduin.net/
* Browser name/version: Irrelevant
* NodeJS version: 13.6.0

**Comment by Chocobozzz** [comment]
Please enable debug logs in your config

**Comment by ltning** [comment]
```
[peertube.anduin.net:443] 2020-02-05 03:01:12.266 debug: Processing image /peertube/storage/tmp/pending-561e7f57-24c8-4642-bfb0-64
28b563d825.jpg to /peertube/storage/thumbnails/561e7f57-24c8-4642-bfb0-6428b563d825.jpg.
Assertion failed: (magick != (const unsigned char *) NULL), function GetImageMagick, file MagickCore/magick.c, line 302.
```
I cannot find the referenced files anywhere, but can only presume they were broken and ImageMagick choked on them?
Source of the video in question is `https://peertube.dk/videos/watch/561e7f57-24c8-4642-b
fb0-6428b563d825`, according to the log.

**Comment by Chocobozzz** [comment]
I think this is a [sharp](https://github.com/lovell/sharp/) issue, because on a GNU/Linux OS sharp throws a `Error: Input buffer contains unsupported image format` error (so peertube does not crash).

**Comment by Chocobozzz** [comment]
What is the version of image magick?

**Comment by mkoppmann** [comment]
Not OP, but I ran into the same issue on FreeBSD 12.1. Had to temporarily unfollow all instances to reduce the risk of running into this crash. ImageMagick was installed from the quarterly binary releases. The version is `7.0.8.57_1`.

**Comment by Chocobozzz** [comment]
And what is your version of `vips`?

**Comment by mkoppmann** [comment]
`vips`, also the generic binary release, is at version `8.8.3_1`.

**Comment by lovell** [comment]
Please see https://github.com/libvips/libvips/pull/1642

**Comment by rigelk** [comment]
For reference, the switch from Sharp to Jimp rendered the issue obsolete.
