### ISSUE TITLE
Pressing Enter to search on iOS devices doesn't work

### ISSUE THREAD

**Issue by ppnplus** [Chocobozzz/PeerTube#2452]
**What happened?**
After entering the keyword, pressing Enter/return did not initiate search on Safari in iOS 13.3.1.
**What do you expect to happen instead?**
Pressing Enter/return to search should work.
**Steps to reproduce:**

1. Visit one of PeerTube instances below.

2. Search for Peertube, then press return on the on-screen keyboard.

3. Nothing happened apart from Shift key reappearing as white, and I had to tap on the search button to search.

**Additional information**
* PeerTube version or URL: 2.0.0 (might also include pre-release versions); tested on framatube.org, peertube.cpy.re and peertube2.cpy.re instances.
* Browser name/version: Tested on Safari on iOS 13.3.1 (iPhone XS Max) and iOS 13.3 (iPad mini 5th gen)
* NodeJS version:
* My keyboard had English (US), Thai and Emoji keyboards enabled on both devices.

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Hello,

Sorry for the late fix. Should be resolved by https://github.com/Chocobozzz/PeerTube/commit/5bd427e01c89e178ceaba357ab1f392553c259bb
