### ISSUE TITLE
Add Thai localization into PeerTube

### ISSUE THREAD

**Issue by ppnplus** [Chocobozzz/PeerTube#2454]
**What happened?**
I've translated enough strings for PeerTube in Thai. Strings that have been translated are primarily from user-related sections (e.g. Trending, About, Sign up, Upload, Profile) so that users can now navigate and use PeerTube instances in Thai, with most of administrator-related sections (e.g. Admin control panel and moderation-related interfaces) to be completed later.

I think there are enough strings so that it can now be available to PeerTube servers and open to PeerTube users. Thank you!

**Comment by Chocobozzz** [comment]
Thanks for your contribution! I pulled the weblate changes in develop. Thai will be added in PeerTube 2.2 (2.1 is already in RC).
