### ISSUE TITLE
New Action - Hook with embed player

### ISSUE THREAD

**Issue by cabaleiro8** [Chocobozzz/PeerTube#2458]
**What happened?**

      I'm trying to implement a plugin to add a watermark to my embed videos. As example, I'm using the original peertube-plugin-player-watermark (https://framagit.org/rigelk/peertube-plugin-player-watermark). This plugin is using "action:video-watch.video.loaded" && "action:video-watch.player.loaded" to hook up with videojs and the player itself. But looks like this hook is only for 'video-watch' page, and it's not linking with embed player. My intention was to add the watermark ONLY for embed player.

**What do you expect to happen instead?**

     I just need a new action, to be able to hook up with embed player, as I can do with the regular player.

**Additional information**

  My suggested names would be: 
     "action:embed-video.video.loaded" and "action:embed-video.player.loaded" 

* PeerTube version or URL:
     2.1.0-rc.1
* Browser name/version:
     ALL
* NodeJS version:
     v13.6.0

Thanks in advance!

**Comment by rigelk** [comment]
Hi! As you mentioned, closing in favor of #2267 which already covers this.
