### ISSUE TITLE
New filter for the Search

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#2464]
I'd suggest adding a new filter called **Type** that should help search for a specific **type** of thing:

- channel
- account
- video
- audio
- GIF/Image (https://github.com/Chocobozzz/PeerTube/issues/2463)
- something else?

When choosing a specific kind of **type**, some other filters should be disabled (grayed out). For example, if **type** is Channel, then _Tags_, _Duration_, _License_ and other irrelevant options should be disabled (grayed out).

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/2262
