### ISSUE TITLE
The Search reports less videos than the About page

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2466]
https://vid.lubar.me/search?search= - top left corner it says 2k results
https://vid.lubar.me/about/instance -  bottom left corner it says 51727 videos

If anything, the number should be higher in the Search because it also takes into account channels, accounts, etc. I suppose there is a bug either in the search or the about page.

**Comment by 3risian** [comment]
Interestingly: https://vid.lubar.me/search?search=a returns 3k results

`https://vid.lubar.me/api/v1/search/videos?search=a` states there are 2573 results
`https://vid.lubar.me/api/v1/search/videos` states there are 2964 (`?search=` without a value is invalid)

So for some reason, it appears as if 2964 rounds to 2k but 2573 rounds up to 3k?

Also worth considering:

 * Is an empty search meant to list everything? I think it should but that isn't its actual purpose
 * Are unlisted/NSFW videos counted? (I doubt there are 50 thousand of them though...)

**Comment by Chocobozzz** [comment]
The stats are not accurate (we should count total videos depending on the instance follows).

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/baab47ca81742deae15acd671e8c332a4e1d6eb7
