### ISSUE TITLE
Ability to store the original video URL a meta for imports

### ISSUE THREAD

**Issue by drzraf** [Chocobozzz/PeerTube#2467]
**What happened?**

When importing a video, this line tests for title equality.
https://github.com/Chocobozzz/PeerTube/blob/a15871560f80e07386c1dabb8370cd2664ecfd1f/server/tools/peertube-import-videos.ts#L140

This is suboptimal
1. Because title can change at the source of the destination, resulting in duplicates.
2. Because Peertube imported video does not hold the original location/unique id of the source which may be useful (for establishing a mapping for example)

**What do you expect to happen instead?**
The importer could fill-in a meta like "Original URL" or "Original ID" containing the Youtube/Vimeo/... URL/ID.

**Additional information**
* PeerTube version or URL: 2.0.0

**Comment by Dif13** [comment]
Will be better, if column will be "originUrl"  like "commentsEnabled" or "waitTranscoding"

**Comment by mawkler** [comment]
With a feature like this it would be really cool if Piped could play the video from PeerTube instead of the one from YouTube, when available, or at least give me the option to do so.

**Comment by FireMasterK** [comment]
> With a feature like this it would be really cool if Piped could play the video from PeerTube instead of the one from YouTube, when available, or at least give me the option to do so.

Author of Piped here, that's exactly the plan if such a feature was to be integrated to PeerTube :)
We used to do that with Odysee/LBRY, when that was still a thing

Comparing titles (like what many redirector extensions) is something that I want to avoid at all costs currently.

**Comment by Chocobozzz** [comment]
I'm sorry but we had to remove this unmaintained script, so I'm closing this issue. Please use the built-in [channel sync](https://docs.joinpeertube.org/use/channel-sync) instead! (has to be enabled by your admin)

**Comment by FireMasterK** [comment]
Hi, does the PeerTube API allow querying for videos by video id or URL from the channel sync feature?

**Comment by Chocobozzz** [comment]
I though there was, but in fact no so I created a new issue on https://github.com/Chocobozzz/PeerTube/issues/6013
