### ISSUE TITLE
Browse "Local videos" from another instance while being connected

### ISSUE THREAD

**Issue by gnouts** [Chocobozzz/PeerTube#2470]
This is a feature request.

My use case : 
I have an account on one instance. I like to browse PeerTube network by instances and looking at the "Local videos" page to discover new videos.
It's annoying to have to switch back to my instance (for following or just put a Like).
So I'd like to be able to browse Local videos from other instances directly from my instance, connected to my account.

Maybe, somewhere in a remote user page, or a remote channel page, add "browse videos from that instance" in a menu (like the admin menu for muting users)

Downwards : It might not be user friendly, so maybe make it an option disable by default ?

**Comment by xundeenergie** [comment]
It would be a good improvement, if i can add the Instance-url in the searchfield of my instance, and get a list of all channels on the other instance, with a follow-button.
the same as when i search for a specific channel.

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/1142
