### ISSUE TITLE
TypeError: this.myAccountPlaylistCache is undefined

### ISSUE THREAD

**Issue by bristow** [Chocobozzz/PeerTube#2475]
**What happened?**

This error appears when I create a public playlist :

> TypeError: this.myAccountPlaylistCache is undefined

**What do you expect to happen instead?**

No error

**Steps to reproduce:**

1. Go here : https://peertube2.cpy.re/

2. Go to playliste and create a playlist

3. And clic on create. Error appears but playlist seems to be created.

**Additional information**
* PeerTube version or URL:  https://peertube2.cpy.re/

* Browser name/version: Firefox 72.0.2
* NodeJS version: ?

* Link to browser console log if useful: https://framabin.org/p/?6b1fe7243c4cd970#AsOH3kmX50upjEiLwRFUi6kt2lntrSVz0cfqlcc/tUw=
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
-

Thanks :)

**Comment by JohnXLivingston** [comment]
I have the same bug on https://videos.globenet.org

**Comment by CorpulentBrony** [comment]
I also am getting this error.  Also receive the error when I try to delete a playlist, though it appears playlists do get deleted.

**Comment by Chocobozzz** [comment]
Thanks for the issue. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/ec10e8ed5b903b0a4d7af5c4a1f03c5f2e89c6b1
