### ISSUE TITLE
Not compatible with avatars from Mastodon or Pleroma

### ISSUE THREAD

**Issue by busshimoe** [Chocobozzz/PeerTube#2478]
**What happened?** Mastodon and Pleroma users show up without an avatar in comments.

**What do you expect to happen instead?** PeerTube should fetch remote avatars from Mastodon and Pleroma.

**Steps to reproduce:**

1. Leave a comment on a PeerTube video from Mastodon or Pleroma

2. Load the video on the PeerTube instance

3. Commentor's avatar does not show up

**Additional information**
* PeerTube version or URL: v2.0.0 (example: https://tube.blob.cat/videos/watch/8e08bbf4-5a40-4252-8d15-4b926662b057 PeerTube avatars work, Pleroma avatars don't)

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/c6de3a85eebbdef3029769ea6225277419ffbe00
