### ISSUE TITLE
HLS script failed at auth to Postgresql

### ISSUE THREAD

**Issue by 22decembre** [Chocobozzz/PeerTube#2481]
**What happened?**

Updated to peertube 2.1.0. That's good. Then wanted to apply script to allow HLS. This failed while trying to auth in the postgresql DB.

**What do you expect to happen instead?**

That the script would do its thing.

**Steps to reproduce:**

1. Update the instance. Start it. All running fine.

2. launch dist/scripts/migrations/peertube-2.1.js as described

**Additional information**
* PeerTube version or URL: 2.1.0
* NodeJS version: v12.13.1
* OS : OpenBSD 6.6 (running well)

* Log of operation : https://pastebin.com/FAQGL70z

**Comment by Chocobozzz** [comment]
Please paste the command you use to run peertube, and your migration command

**Comment by 22decembre** [comment]
To run the server, I have this in my rc script (far from perfect) :

`HOME_DIR="/var/www/peertube"
CONF_DIR="${HOME_DIR}/config/
daemon="HOME=${HOME_DIR} NODE_CONFIG_DIR=${CONF_DIR} NODE_ENV=production USER=${daemon_user} /usr/local/bin/node ${HOME_DIR}/peertube-latest/dist/server" `

migration was from /var/www/peertube/peertube-latest/ :

`NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production doas -u _peertube node dist/scripts/migrations/peertube-2.1.js`

**Comment by Chocobozzz** [comment]
I don't know `doas` but did you try `doas -u _peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production node dist/scripts/migrations/peertube-2.1.js`?

**Comment by 22decembre** [comment]
Doas is OpenBSD replacement for sudo. It has this thing as it believes the first thing you give it is a command. Here it would be NODE_CONFIG_DIR=/var/www/peertube/config.

The right order (normaly) it to initiate env', then doas followed immediately by comands (node...).

But yes, I tried that one in the first place. And it failed. Because it was trying to execute config as a command.

**Comment by rigelk** [comment]
@22decembre as I understand it, the issue is resolved since it pertains to your understanding of `doas`'s behaviour when translating our example that uses `sudo`. 

Please reach out to your OpenBSD community for further help with `doas` as we can't help with it - or try running our script with `sudo` - or avoid both with `su`.

**Comment by 22decembre** [comment]
Running it as root made it work indeed. (For now.)
