### ISSUE TITLE
Upgrade to Peertube 2.1.0: Cannot generate torrent of /var/www/peertube/versions/peertube-v2.1.0/storage/streaming-playlists/hls/ID_OF_THE_VIDEOS-fragmented.mp4: file does not exist.

### ISSUE THREAD

**Issue by pokapow** [Chocobozzz/PeerTube#2483]
**What happened?**
After upgrade script using to Peertube 2.1.0: 
`cd /var/www/peertube/peertube-latest && sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production node dist/scripts/migrations/peertube-2.1.js`

This error for all torrent of this instance:

`[tube.p2p.legal:443] 2020-02-12 19:34:23.436 info: Processing /var/www/peertube/versions/peertube-v2.1.0/storage/streaming-playlists/hls/ee1585f5-9a3f-4485-9fca-956259d5912d/ee1585f5-9a3f-4485-9fca-956259d5912d-240-fragmented.mp4.`

**What do you expect to happen instead?**
No errors ...

**Steps to reproduce:**

1. Migrate Peertube from 2.0.0 to 2.1.0

2. launch `dist/scripts/migrations/peertube-2.1.js`

**Additional information**
* PeerTube version or URL: https://tube.p2p.legal/
* Browser name/version: Chromium Version 79.0.3945.79 (Build officiel) Built on Ubuntu , running on LinuxMint 19.3 (64 bits)
* NodeJS version: v10.16.3

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): https://paste.ofcode.org/eEhpp562hRgvaXiddfXHcm

**Comment by Chocobozzz** [comment]
PeerTube seems to have created HLS entries in the database but the files don't exist on the disk. Did you remove them? Or maybe you changed the streaming playlist directory target?

**Comment by pokapow** [comment]
No I didn't anything like this, everything is by default on server side. 

And everything is working well actually, just theses errors when executing the migration script.

**Comment by Chocobozzz** [comment]
Go inside your database and run:

```
select "videoFile".id as id, "videoFile".resolution as resolution, "video".uuid as uuid from "videoFile" inner join "videoStreamingPlaylist" ON "videoStreamingPlaylist".id = "videoFile"."videoStreamingPlaylistId" inner join video ON video.id = "videoStreamingPlaylist"."videoId" WHERE video.remote IS FALSE
```

Then, remove rows when the file does not exist on your `streaming-playlists/hls/uuid` directory.
