### ISSUE TITLE
Channel follow pending with manual approval of new instance followers enabled

### ISSUE THREAD

**Issue by Lesterpig** [Chocobozzz/PeerTube#2489]
Cheers, thanks for v2.1.0! 👍

**What happened?**

User A on instance A.
User B on instance B, configured with "Manually approve new instance followers".

User A on instance A loads a video from User B's channel, and then subscribe to User B's channel.
In databases of both instances, the `followActor` from A to B is set to `pending`.

**What do you expect to happen instead?**

I would expect that the follow would be automatically `accepted`.
(This is not an "instance-wide" follow, so it should not require manual approval).

**Steps to reproduce:**

(see above)

**Additional information**
* PeerTube version: v2.1.0
* Browser name/version: Firefox 73
* NodeJS version: 10

**Probable culprit:**

https://github.com/Chocobozzz/PeerTube/blob/release/2.1.0/server/lib/activitypub/process/process-follow.ts#L57

➡️  I'm not 100% sure if this is the expected behavior or not. I can open a pull request if needed 😃 
I believe the `pending` state would block some outbound federation (?)

**Comment by Lesterpig** [comment]
Might be related to https://github.com/Chocobozzz/PeerTube/issues/1764 but I see no description 😛

**Comment by Chocobozzz** [comment]
Nice catch @Lesterpig! I will fix that

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/7d233f1dd9c5be8d7beba7ec5b92029888e0c91c
