### ISSUE TITLE
Import local files

### ISSUE THREAD

**Issue by tcitworld** [Chocobozzz/PeerTube#249]
It would be nice to select a folder where existing video files are already present.

**Comment by tcitworld** [comment]
Related to https://github.com/Chocobozzz/PeerTube/issues/102

**Comment by Chocobozzz** [comment]
I'm sorry but I don't understand. Could you elaborate/give us a use case?

**Comment by tcitworld** [comment]
I already have video files on the same server that hosts PeerTube.
I would expect one of the following : 
* copying the files inside the `videos` directory of Peertube automatically suggests me to create a Peertube upload
* navigating inside my server's filesystem to find the files and import them

**Comment by Chocobozzz** [comment]
Okay so a CLI command 👍

**Comment by bnjbvr** [comment]
Could it be just an external command that uses the PeerTube API? I think that not only the PeerTube instance provider would want to do so, and I can imagine other usages to this external program (e.g. import from YouTube, etc.)

**Comment by tcitworld** [comment]
Seems fine to me.

**Comment by tcitworld** [comment]
If it's a cli command, it could be like https://github.com/Chocobozzz/PeerTube/blob/develop/server/tests/real-world/tools/upload.ts

**Comment by zicmama** [comment]
This is the feature I am looking for ;)

**Comment by Chocobozzz** [comment]
See https://github.com/Chocobozzz/PeerTube/blob/develop/server/tools/upload.ts

Usage: `node dist/server/tools/upload.js --help`

Example: `node dist/server/tools/upload.js -u http://localhost:9000 -U root -p test -f /home/me/file.mp4 -n 'my super video'`

Not sure if all options are working, PR welcome ;)

**Comment by aerogus** [comment]
Note that the upload.js script is missing dependencies if installed in production environnement because it depends on "supertest" and "chai" packages (and maybe others).
I have to`yarn install production=false` in order to make it work

**Comment by Chocobozzz** [comment]
@aerogus Yes, this is specified in the documentation :) https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#installation
