### ISSUE TITLE
Peertube Shared mirrors/seedboxes

### ISSUE THREAD

**Issue by shleeable** [Chocobozzz/PeerTube#2490]
Is there a plan to support mirror nodes or "seedboxes" for the videos? I'd love to see a bunch of sister boxes that mirrors videos (including popular videos) in a passive way?

If I hosted my own peertube instance, I'd love to launch 2-3 "peer mirror" instances that would take a copy of all of the popular videos on federation wide videos... I think people would be willing to host these boxes all over the place

Bonus feature would be open an s3 bucket in a bunch of different services - aws/digitalocean/wasabi and mirror videos in multiple places managed by the mirror seedbox...

**Comment by Chocobozzz** [comment]
Yes, you can use the "redundancy feature" of PeerTube. See https://docs.joinpeertube.org/#/admin-following-instances?id=instances-redundancy
