### ISSUE TITLE
Python missing in production-buster docker image

### ISSUE THREAD

**Issue by mkody** [Chocobozzz/PeerTube#2491]
**What happened?**
Since I upgraded my instance running in docker to 2.1.0 with the `production-buster` image, I can't use imports anymore. I'm using the API but it's the same from the browser.  
And opening the logs, I see the error that it can't find python.

**What do you expect to happen instead?**
Peertube importing my video. 😛 

**Steps to reproduce:**

1. Set `chocobozzz/peertube:production-buster` for the service `peertube` in docker-compose

2. Pull image and restart stack

3. Try to import a video (in this case from Twitch)

**Additional information**
* PeerTube version or URL: v2.1.0
* Browser name/version: REST API, Chrome 79
* NodeJS version: v10.19.0

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): https://gist.github.com/mkody/79eff40c23561fed53c99566eae3092d

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/c5621bd23bce038671cd81149a0aa5e238558b67
