### ISSUE TITLE
Audio-only issue with HLS

### ISSUE THREAD

**Issue by raphgilles** [Chocobozzz/PeerTube#2492]
Hello,

I tested the audio-only mode with the HLS format activated. In the choice of resolutions, the audio file is displayed like a duplicate of the maximum available resolution. For example "1080p". And the video is not "empty" but very badly encoded.

Here is an example:
https://peertube.club/videos/watch/d51284f6-5061-4563-b639-cb880f9bf32d

**Additional information**
* PeerTube version or URL: https://peertube.club/
* NodeJS version: v10.19.0
* FFMPEG version: v4.2.2
// nothing in logs.

**Comment by Chocobozzz** [comment]
Hello and sorry for the late.

Do you reproduce this issue every time your upload an audio file?

**Comment by raphgilles** [comment]
Sorry it took me so long to answer.

This does not happen with an audio file but with a video file (like the link for example).

**Comment by Chocobozzz** [comment]
Do you reproduce every time you upload a video file or was it an issue with only this particular upload?

**Comment by raphgilles** [comment]
Everytime. With my two instances.

**Comment by xcffl** [comment]
> Do you reproduce every time you upload a video file or was it an issue with only this particular upload?

sounds like #2554?

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/1c3206736743646d41a667c03f3e499cc3e3373f
