### ISSUE TITLE
Unable to change avatar since v2.1.0

### ISSUE THREAD

**Issue by raphgilles** [Chocobozzz/PeerTube#2493]
Hello,

Since the version 2.1.0 I have a problem on both my instances: it is impossible to update the avatar.
I can send one to a new account. But not replace it. When I do, the message "Avatar updated" appears, but nothing.

If I downgrade to the v2.0.0 it works.

Thank you !

**Additional information**
* PeerTube version or URL: https://peertube.club/ & https://vloggers.social/
* NodeJS version: v10.19.0
* FFMPEG version: v4.2.2
// nothing in logs.

**Comment by DontUseGithub** [comment]
Maybe it's also related to server cache https://github.com/Chocobozzz/PeerTube/issues/2501#issuecomment-586682728, try **ctrl+shift+R** (on firefox) then repeat the steps.

**Comment by raphgilles** [comment]
It's not due to the cache. The file name still the same also when I publish a png unstead a jpg/

**Comment by Chocobozzz** [comment]
Thanks for the issue. Should be fixed in https://github.com/Chocobozzz/PeerTube/commit/1c5fbed2093c0462e40a092d49d761a043c50e98

**Comment by raphgilles** [comment]
It still don't work on my two instances @Chocobozzz.

**Comment by Chocobozzz** [comment]
How did you apply the patch?

**Comment by raphgilles** [comment]
> 
> 
> How did you apply the patch?

I used the upgrade script.  

> cd /var/www/peertube/peertube-latest/scripts && sudo -H -u peertube ./upgrade.sh

**Comment by Chocobozzz** [comment]
The patch is not released yet.

**Comment by highvoltage** [comment]
I still have this issue on 2.1.1, I guess the patch didn't make it?

**Comment by stefanor** [comment]
@highvoltage: It did, and I think we're getting a follow-on bug. I filed #2562.
