### ISSUE TITLE
When importing video video description with newlines get cut off after first line

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#2496]
**What happened?**
trying to import videos using peertube upload but when given video-description everything after the first line gets cut off
**What do you expect to happen instead?**
I expect the whole description to be populated to the video when being uploaded with peertube upload tool
**Steps to reproduce:**

1. peertube upload a video with a description that has newlines

        description="$(echo "*ID:* ${id} **URL:** ${video_url} _CHANNEL:_ ${channel_url} __TAGS:__ ${tags} *UPLOAD DATE:* ${upload_date} **DESCRIPTION:** ${description}")";
              echo "${description}";

2. notice only the first lines made it

3.
        output="$(peertube upload \
                    --url "${PEERTUBE_URL}" \
                    --username "${USERNAME}" \
                    --password "${PASSWORD}" \
                    --video-name "$fulltitle" \
                    --thumbnail "${thumbnail_file}" \
                    --video-description "${description}" \
                    ${OPTIONS} \
                    --file "$(realpath "./$FILENAME")" 2>&1)";

**Additional information**
* PeerTube version or URL: 2.0.0
* Browser name/version: N/A
* NodeJS version: 12.13.1

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
https://troo.tube

**Comment by 3risian** [comment]
Is this importing PeerTube videos to PeerTube?

I know there is an issue with the youtube-dl extractor for PeerTube, as it gets the truncated description instead of the full description. I have submitted [a pull request](https://github.com/ytdl-org/youtube-dl/pull/23657) that fixes this but it keeps getting (rightfully) knocked back for quality control.

**Comment by Chocobozzz** [comment]
I'm sorry I can't reproduce. Can you tell me where the description is truncated?
