### ISSUE TITLE
Video embed loads all subtitle files even before playback is started

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#2498]
Here are the steps to reproduce:

1. visit https://joinpeertube.org/
2. open network tools in the browser console
3. filter requests for .vtt
4. notice 13 different requests for subtitle files

It would be better to load only the subtitle for the language that is actually configured in the browser. Or better yet, wait with loading until the playback is started.

**Comment by Chocobozzz** [comment]
We are waiting for a stable videojs release: https://github.com/videojs/video.js/releases/tag/v7.7.0

**Comment by Chocobozzz** [comment]
Waiting https://github.com/videojs/video.js/pull/6685 (or another fix for this bug)

**Comment by Chocobozzz** [comment]
Finally fixed in https://github.com/Chocobozzz/PeerTube/commit/93f30abf2809327aa7bf637691baa2a125bba5fa
