### ISSUE TITLE
I allowed registration, but the "Currently this instance doesn't allow for user registration" banner is still there

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#2501]
**What happened?**
After a long time of not allowing registrations, i decided to enable it, but i still have the banner saying "Currently this instance doesn't allow for user registration" on the login page. Additionally, instance metadatas are not accurate.
**What do you expect to happen instead?**
Disappearing of the banner.
**Steps to reproduce:**

1. Disable registration for long time.

2. Upgrade instance.

3. Enable registration.

4. Go to login page.

**Additional information**
* PeerTube version or URL: 2.1
* Browser name/version: Firefox 58
* NodeJS version: 10.17.0

**Comment by DontUseGithub** [comment]
it probably has something to do with cache

I've encountered this issue https://github.com/Chocobozzz/PeerTube/issues/2465 on many instances, including on https://peertube2.cpy.re to this day. The only solution is to do **ctrl+shift+R** in firefox. On [some instances](https://video.lono.space/about/instance), the about page doesn't update it's info, for example it says "version unknown" and then you do a **ctrl+shift+R** and everything gets sorted out.
For how long does cache live? I've observed these issues on https://peertube2.cpy.re for at least 1 week.

**Comment by stemy2** [comment]
It works ! Thanks.

**Comment by DontUseGithub** [comment]
Doing **ctrl+shift+R** is only a temporary (client-side) solution. Remove website data + cookies from your browser, restart it and you're problems will come back :)

**Comment by stemy2** [comment]
> Doing **ctrl+shift+R** is only a temporary (client-side) solution. Remove website data + cookies from your browser, restart it and your problems will come back :)

Right. :(

Isn't there a definitive solution ?

**Comment by stemy2** [comment]
Redundant with [](https://github.com/Chocobozzz/PeerTube/issues/2502)
