### ISSUE TITLE
Instance metadatas are not accurate

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#2502]
**What happened?**
The options i just activated are showed as disabled in the metadatas. For examples the videos are showed as "Automatically published" even when auto-blacklisting is enabled, and i still have the banner "Currently this instance doesn't allow for user registration" even when registrations are actually enabled.
**What do you expect to happen instead?**
Accurate metadatas.
**Additional information**
* PeerTube version or URL: 2.1
* Browser name/version: Firefox 58
* NodeJS version: 10.17.0

**Comment by stemy2** [comment]
Found a solution [here](https://github.com/Chocobozzz/PeerTube/issues/2501#issuecomment-586682728).

**Comment by stemy2** [comment]
ctrl+shift+R can solve it, but temporarly and only on client-side.

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/017fbe1855a9b3aea601595b10e62c681fbcdb17
