### ISSUE TITLE
YouTube import should download max available resolution

### ISSUE THREAD

**Issue by raphgilles** [Chocobozzz/PeerTube#2505]
Hello,

This a suggestion : Actualy PeerTube support 2160p resolution (that's awesome !) but can't import only max-1080p videos from YouTube. Also I think the maximum available resolution should be downloaded and not only up till 1080p :)

Keep the good work !

**Comment by JohnXLivingston** [comment]
I think it should be the case. These options are passed to youtube-dl: `bestvideo[ext=mp4]+bestaudio[ext=m4a]/best`

**Comment by raphgilles** [comment]
But it's not. Surely because YouTube don't purpose 4K resolution in mp4

**Comment by rigelk** [comment]
Maybe we should switch to `bestvideo+bestaudio`.

**Comment by rigelk** [comment]
@raphgilles @JohnXLivingston I'll be taking the issue. However we need to test how stable the feature is, because unlike `mp4` files that contain both audio and video, YT tends to separate streams on higher resolutions of different containers due to the almost null cost of remuxing them.

If you have a few *short* videos that have non-`mp4` best resolutions, that would be great to help me test the stability of switching to that format selector.

**Comment by JohnXLivingston** [comment]
Maybe Big Buck Bunny? "only" 10 minutes.
https://www.youtube.com/watch?v=aqz-KE-bpKQ
I have no other idea. If needed, I can try to make a UHD video with my phone (3840*2160 60fps).

**Comment by raphgilles** [comment]
And why don't download audio and video separately and assemble them next with FFMPEG ?

**Comment by rigelk** [comment]
@raphgilles because that's extra work? 😅

**Comment by hexydes** [comment]
Just some feedback, I'd want the YouTube importer to download the highest resolution THAT I HAVE SET on the server. So if I have transcoding set to 1080p and 480p, I'd want to pull in the 1080p version, not the 4k version. This would cause a ton of storage issues on my server to have a 4K, 1080p, AND 480p video. I'd only want 1080p and 480p.

**Comment by AnonymousWebHacker** [comment]
@rigelk Is there any parameter for the youtube-dl import to be queued, in case of internet interruption?

**Comment by rigelk** [comment]
This issue conflicts with https://github.com/Chocobozzz/PeerTube/issues/3513, which settled on another solution.
