### ISSUE TITLE
Translation of title tooltips

### ISSUE THREAD

**Issue by AutomCoding** [Chocobozzz/PeerTube#2506]
Is it possible to make a tags' title attributes translatable? Like [this one](https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/login/login.component.html#L50), for example.

**Comment by rigelk** [comment]
@AutomCoding yes, using `i18n-title` tag.

**Comment by AutomCoding** [comment]
@rigelk I'm searching through the code for more instances of this, will make a PR soon.
