### ISSUE TITLE
CSP breaks embeds in Peertube 2.1.0

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#2509]
The content security policy in the latest Peertube version is broken, so that embeds are not working. See the following link for an example. Trying to play the video results in an error message "Blocked by Content Security Policy".

https://radical.town/@felix/103689965787653294

To reproduce:
1. in the instance config, set csp enabled: true
2. embed a video on some other site (eg by posting a peertube link on mastodon)
3. try to play the video

**Comment by djoerd** [comment]
Can confirm, for instance here: 
  https://djoerdhiemstra.com/2018/welcome-to-foundations-of-information-retrieval/

**Comment by Chocobozzz** [comment]
Thanks for the issue. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/dfab4fa9c6d5b6f12ac844b191a51282b002d3f5
