### ISSUE TITLE
Private messaging

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#2513]
Hello,

It would be cool to be able to communicate privately with peertube users.

**Comment by DontUseGithub** [comment]
I think we should look at how lemmy does it https://github.com/dessalines/lemmy/issues/244#issuecomment-568801556

**Comment by Chocobozzz** [comment]
Until the feature is implemented, you can contact the user by email :)

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/6523
