### ISSUE TITLE
Update 2.1 no more thumbnails and videos

### ISSUE THREAD

**Issue by ddeenniiss** [Chocobozzz/PeerTube#2515]
**What happened?**
After the update in 2.1. The site no longer displays thumbnails and videos

https://videos.domainepublic.net/videos/local
https://videos.domainepublic.net/videos/watch/19290f65-c818-4038-a359-5325bdbee4b1

**What do you expect to happen instead?**

**Steps to reproduce:**

1.

2.

3.

**Additional information**
* PeerTube version or URL: 2.1 
* Browser name/version: ALL
* NodeJS version: v10.16.3

All actives conf  are the same of (peertube-latest/support/nginx/peertube  and peertube-latest/config/production.yaml.example)  except for the storage (production.yaml)

>   tmp: '/data/peertube/storage/tmp/' # Use to download data (imports etc), store uploaded files before processing...
>   avatars: '/data/peertube/storage/avatars/'
>   videos: '/data/peertube/storage/videos/'
>   streaming_playlists: '/data/peertube/storage/streaming-playlists/'
>   redundancy: '/data/peertube/storage/redundancy/'
>   logs: '/data/peertube/storage/logs/'
>   previews: '/data/peertube/storage/previews/'
>   thumbnails: '/data/peertube/storage/thumbnails/'
>   torrents: '/data/peertube/storage/torrents/'
>   captions: '/data/peertube/storage/captions/'
>   cache: '/data/peertube/storage/cache/'
>   plugins: '/data/peertube/storage/plugins/'

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): https://pads.domainepublic.net/p/Peertube_2.1

**Comment by ddeenniiss** [comment]
thumbnails are OK on Android (Firefox-Chrome-Thorium)

**Comment by Chocobozzz** [comment]
Check the thumbnails path in your nginx config

**Comment by ddeenniiss** [comment]
I don't see a difference with peertube-latest/support/nginx/peertube

>   location ~ ^/static/(thumbnails|avatars)/ {
>     if ($request_method = 'OPTIONS') {
>       add_header 'Access-Control-Allow-Origin' '*';
>       add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
>       add_header 'Access-Control-Allow-Headers' 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
>       add_header 'Access-Control-Max-Age' 1728000;
>       add_header 'Content-Type' 'text/plain charset=UTF-8';
>       add_header 'Content-Length' 0;
>       return 204;
>     }
> 
>     add_header 'Access-Control-Allow-Origin' '*';
>     add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
>     add_header 'Access-Control-Allow-Headers' 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
> 
>     add_header Cache-Control "public, max-age=7200";
> 
>     root /var/www/peertube/storage;
> 
>     rewrite ^/static/(thumbnails|avatars)/(.*)$ /$1/$2 break;
>     try_files $uri /;
>   }

**Comment by ddeenniiss** [comment]
OK, if i change this, i can play videos but i don't have thumbnails

> root /var/www/peertube/storage;

to 

> root /data/peertube/storage;
