### ISSUE TITLE
Videos hanging after a specific time, or seemingly waiting forever to encode

### ISSUE THREAD

**Issue by Fishounet** [Chocobozzz/PeerTube#2521]
**What happened?**
I am an user of a Peertube Instance, and a specific video I uploaded couldn't play in the webplayer after a specific time (1h11min38sec), the link is `https://videos.pair2jeux.tube/videos/watch/51b51432-19e0-4f0f-9849-c1e2752424d1` and someone I know gave me permission to use this log they gathered from another instance playing it `https://0bin.net/paste/bazLdCo9-R0CDbLG#ek30DHt8N+8RbJ0SNMZXSD3Q2wUPiV+R+Eky-TIkHkJ`, please note that downloading it still works, and using fedilab also works.

I then re-encoded it, just in case, but it seems to await encoding forever, and while it can be played, playing it results in a temporary inaccessibility of the entire instance for a few minutes, link of the re-encoded one is `https://videos.pair2jeux.tube/videos/watch/0d9b72f2-0484-4979-94f9-cb0c0f583dea` (if this is another issue, please let me know so I can open another one if needed)
**What do you expect to happen instead?**
I expected the video to be played in the web-player of Firefox without issues
**Steps to reproduce:**

1. Go to `https://videos.pair2jeux.tube/videos/watch/51b51432-19e0-4f0f-9849-c1e2752424d1` on Firefox (I tested on Linux Mint)

2. Go a bit before 1h11min38sec and wait for it to play until that timestamp

3.Watch it stop while still downloading content and buffering

**Additional information**
* PeerTube version or URL: 2.1.0 according to `https://videos.pair2jeux.tube/about/instance`
* Browser name/version: Mozilla Firefox for Linux Mint 73.0.1 (64 bits)
* NodeJS version:

* Link to browser console log if useful: `https://0bin.net/paste/bazLdCo9-R0CDbLG#ek30DHt8N+8RbJ0SNMZXSD3Q2wUPiV+R+Eky-TIkHkJ` (not sure if it is that, but could be useful)
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

Thanks for your patience, have a good day.

**Comment by Chocobozzz** [comment]
Thanks for the issue.

> I am an user of a Peertube Instance, and a specific video I uploaded couldn't play in the webplayer after a specific time (1h11min38sec), the link is https://videos.pair2jeux.tube/videos/watch/51b51432-19e0-4f0f-9849-c1e2752424d1 and someone I know gave me permission to use this log they gathered from another instance playing it https://0bin.net/paste/bazLdCo9-R0CDbLG#ek30DHt8N+8RbJ0SNMZXSD3Q2wUPiV+R+Eky-TIkHkJ, please note that downloading it still works, and using fedilab also works.

It seems a videostream issue. Not sure if I can fix this. You can ask your administrator to generate the HLS version for this specific video using https://docs.joinpeertube.org/#/maintain-tools?id=create-transcoding-jobjs

> I then re-encoded it, just in case, but it seems to await encoding forever, and while it can be played, playing it results in a temporary inaccessibility of the entire instance for a few minutes, link of the re-encoded one is https://videos.pair2jeux.tube/videos/watch/0d9b72f2-0484-4979-94f9-cb0c0f583dea (if this is another issue, please let me know so I can open another one if needed)

Please ask your administrator if the transcoding job is running, waiting or if it failed

**Comment by LecygneNoir** [comment]
Hello,

As an admin of pair2jeux instance, I may add that for the second file (the one stucking the instance), the encoding crashes with this error:

```
{   "type": "optimize",   "videoUUID": "0d9b72f2-0484-4979-94f9-cb0c0f583dea",   "isNewVideo": true }
--
SequelizeConnectionAcquireTimeoutError: Operation timeout     at pool.acquire.catch.error (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:282:52)
```

The optimize of the first video apparently works (no error), and was done before the upgrade to v2.1.0 (was v2.0.0), even if resolution enabled are 460p, 720p and 1080p.

Hope it may help!

**Comment by LecygneNoir** [comment]
Ow @Chocobozzz you read my mind :D

I have already tried to relaunch the transcoding and it generates the error below. But I have not checked HLS in admin panel, and still use webtorrent, could be linked?

**Comment by Chocobozzz** [comment]
> But I have not checked HLS in admin panel, and still use webtorrent, could be linked?

Nope, you can disable HLS for every uploaded videos but generate an HLS version for a specific video using the script. Your bug is related to your database. Maybe an upgrade to 2.1.1 would fix this issue.

**Comment by LecygneNoir** [comment]
Ok, I have planned to update to 2.1.1 today (probably in the afternoon), I'll try to relaunch the encoding after that and update the issue :+1:

**Comment by LecygneNoir** [comment]
Just to be sure, the documentation says `To generate an HLS playlist for a video:`, but it'll create a transcoding job, nothing to do with the playlist feature, right?

**Comment by Chocobozzz** [comment]
Yes, HLS playlists (m3u8 files) are different from PeerTube playlists.

**Comment by LecygneNoir** [comment]
Great, I have updated to 2.1.1. and transcoded again the initial video ([https://videos.pair2jeux.tube/videos/watch/51b51432-19e0-4f0f-9849-c1e2752424d1](https://videos.pair2jeux.tube/videos/watch/51b51432-19e0-4f0f-9849-c1e2752424d1) , and it works, the video could be played after 1.11.38s timestamp

It's also possible to navigate in the video even after this timestamp :tada: 

So it was only a temporary transcoding error, thank a lot for the help!

@Fishounet you may test the video and confirm it works (also on fedilab?), then close the issue if everything is ok?

**Comment by Fishounet** [comment]
I tested it, it works on both firefox and fedilab, thanks a lot ^^, will close now
