### ISSUE TITLE
Player.ready() endless pending (@peertube/embed-api)

### ISSUE THREAD

**Issue by kantegory** [Chocobozzz/PeerTube#2522]
**What happened?**  

PeerTubePlayer.ready is stuck in endless pending, embed-API doesn't work for this reason.

**What do you expect to happen instead?**  

I expect that I'll be able to control the embed player using @peertube/embed-api (pause, play, getVolume, setVolume, etc.). But readyPromise getting stuck in pending.

**Steps to reproduce:**

1. I follow docs instructions (https://docs.joinpeertube.org/#/api-embed-player?id=quick-start).
My code:
```javascript
import { PeerTubePlayer } from '@peertube/embed-api'
async function peertube_player() {
        let player = new PeerTubePlayer(document.querySelector('iframe'))
        console.log(player.ready)
        await player.ready // wait for the player to be ready

        player.addEventListener('pause', function(){
                var volume = player.getVolume()
                console.log(volume)
        })
}
peertube_player();
```

2. readyPromise getting stuck in pending.

console:

```javascript
Promise { <state>: "pending" }
```

3. I already try to remove async/await. Using .then() instead of async/await, but it's not a solution for this problem.

**Additional information**
* PeerTube version or URL: 2.1.0
* Browser name/version: Firefox 68 on Linux
* NodeJS version: v10.16.0

**Comment by Chocobozzz** [comment]
Did you add `api=1` to the embed query parameters?

**Comment by kantegory** [comment]
Thanks a lot. Now everything is OK!
