### ISSUE TITLE
Next button in a playlist goes to «other videos»

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2523]
**What happened?**
I'm watching a playlist, I click on the next button in the video player, and it don't go on next playlist video, but on the first «other videos» suggestion.

**What do you expect to happen instead?**
Go to next playlist video.

**Steps to reproduce:**

1. Open a playlist. For example: https://www.yiny.org/videos/watch/playlist/35c6e28e-2bf3-4795-93b5-4967951b6bf5?videoId=67dc764a-491b-4858-9be9-6d159f14fbd7&resume=true

2. Click on the next button in the video player

**Additional information**
* PeerTube version or URL: v2.1.1
* Browser name/version: Firefox

**Comment by rigelk** [comment]
Yes, it's a known shortcoming. I didn't have the time to make the button playlist-aware 🙃

**Comment by JohnXLivingston** [comment]
Okay :)
