### ISSUE TITLE
CSP breaks redundancy

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2524]
**What happened?**

With CSP enabled, I think redundancy is broken (not 100% sure, and I have no time to investigate more right now).

**Steps to reproduce:**

1. Go to https://peertube.cpy.re/videos/watch/f8a4b32d-0bf1-48ed-af9f-d8c5d87efedb

2. See errors in browser console

`Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://video.omniatv.com/static/redundancy/f8a4b32d-0bf1-48ed-af9f-d8c5d87efedb-480.mp4. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant.`

**Additional information**
* Browser name/version: Firefox

**Comment by rigelk** [comment]
It is more a misconfigured reverse proxy on the redunding instance part.

**Comment by JohnXLivingston** [comment]
Are you sure? I saw it on 3 or 4 different redundancy servers.

**Comment by rigelk** [comment]
I'm more than sure, the error tells it is CORS that is misconfigured (in that case, "l’en-tête CORS « Access-Control-Allow-Origin » est manquant"/"missing cors header « Access-Control-Allow-Origin »" [on the remote].

CSP is basically for the site you directly access to tell you what is safe to load and run, and CORS is basically for remote servers to tell if they accept to answer requests from you at that site.
