### ISSUE TITLE
Opt-in autoplay after direct click in UI

### ISSUE THREAD

**Issue by cadadr** [Chocobozzz/PeerTube#2525]
(I'm not sure if the decision is yours or instance admins, but I tried a random sample from https://instances.joinpeertube.org/instances and all had autoplay so I thought it'd be appropriate to suggest this here. Sorry if that isn't the case.)

Autoplay is a user hostile feature that should be opt-in rather than opt-out. Among the undesirable aspects of autoplay there is the possibility of incurring unexpected data charges and unexpected sound output from the device. Furthermore PeerTube does not respect the user setting to disable autoplay in browsers, which is not good netiquette.

Therefore I suggest that autoplay be made an opt-in feature and users' browser settings regarding it not be overridden without consent.

**Comment by rigelk** [comment]
Hi @cadadr - thanks for bringing the issue to light. While I share your thoughts on autoplay, I can't reproduce the following on my end, where autoplay is properly disabled according to the browser setting:

> Furthermore PeerTube does not respect the user setting to disable autoplay in browsers, which is not good netiquette.

What is your browser?

**Comment by cadadr** [comment]
Firefox 73 on Debian Stable & Firefox 68 on Android. An important thing I forgot to mention: no-autoplay setting is respected when link is opened in new tab (middle-click), but not when you just click through within the same tab (left-click).

**Comment by PhieF** [comment]
Also when opening any peertube link, the video start playing even in private navigation, and it is muted. Which means we always loose the beginning of the video

**Comment by Chocobozzz** [comment]
>  Furthermore PeerTube does not respect the user setting to disable autoplay in browsers

It's not to websites to respect web browser autoplay setting. Web browsers decide to play or not the video. If you're not happy with the current behaviour, your could check your settings or report an issue in your web browser bug tracker.

**Comment by cadadr** [comment]
> It's not to websites to respect web browser autoplay setting.

Isn't it to ethical websites to not circumvent it tho?  My browser already enforces autoplay settings, nothing besides YouTube and PeerTube can autoplay anything.  The direct click in the UI circumvents, intentionally or not, users' non-consent to autoplaying videos.
