### ISSUE TITLE
Short 4K video not working, because of small chunk size

### ISSUE THREAD

**Issue by NexonSU** [Chocobozzz/PeerTube#2526]
**Wrong chunk size in 4K videos**

**Chunk size must be based on filesize**

**Steps to reproduce:**

1. Open long 4K video https://peertube.nexon.su/videos/watch/77018a76-6daf-4d2a-9cab-c553b301c612

2. Open short 4K video https://peertube.nexon.su/videos/watch/3358ccbf-cfc1-448b-bf69-d7ee37f48fb7

3. Compare chunk sizes

**Additional information**
* PeerTube version or URL: 2.1.1 https://peertube.nexon.su/
* Browser name/version: Google Chrome 80.0.3987.122
* NodeJS version: v10.19.0

As you can see, short 4K video not even working with 32KB chunk size.

**Comment by Chocobozzz** [comment]
Hello,

Yes but unfortunately we can't really do anything with our webtorrent player. But the HLS player should not have this issue.

**Comment by NexonSU** [comment]
@Chocobozzz thanks for reply. How can I force HLS player by default?

**Comment by Chocobozzz** [comment]
Enable HLS on your instance or use [this tool](https://docs.joinpeertube.org/#/maintain-tools?id=create-transcoding-jobjs) to generate HLS version for specific videos.

**Comment by NexonSU** [comment]
Yep, HLS working a lot better, thank you.
