### ISSUE TITLE
Missing comment notification

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2527]
**What happened?**
There were replies to one of my comment, via mastodon. I did not receive any notification. Neither email, neither web. There is no email job on the server.

See this screenshot:
![image](https://user-images.githubusercontent.com/38844060/75598412-c1701400-5a9b-11ea-9bad-655da4f034b7.png)
There were replies 6 hours ago, but there is nothing in my notifications.

I can't see any error in server logs

**Additional information**
* PeerTube version or URL: v2.1.1

**Comment by Chocobozzz** [comment]
Could you try to reproduce using your mastodon account? With debug logs enabled on your server?

**Comment by JohnXLivingston** [comment]
I can't reproduce. I close the ticket.
