### ISSUE TITLE
Events .pause(), .play() don't work in embed-api

### ISSUE THREAD

**Issue by kantegory** [Chocobozzz/PeerTube#2528]
**What happened?**
player.addEventListener('pause', function() {});
player.addEventListener('play', function() {});

Don't work in embed-api. I can't just handle this events and print them in console.

Also, I have already used event playbackStatusChange for these purposes. But I think it's not a right case for this event.

**What do you expect to happen instead?**
I expected the play and pause events to work correctly. But they are not working.

**Additional information**
* PeerTube version or URL: 2.1.1
* Browser name/version: Firefox 68 on Linux
* NodeJS version: v13.9.0

**Comment by Chocobozzz** [comment]
Hello,

The documentation is wrong. On `play` or `pause` we fire a `playbackStatusChange` event. I fixed the documentation in https://github.com/Chocobozzz/PeerTube/commit/5ab994fe8e131c83a81d40ee86e86737de911e17
