### ISSUE TITLE
No way to register

### ISSUE THREAD

**Issue by Copen-08** [Chocobozzz/PeerTube#253]
* **PeerTube version or commit:**
The demo site linked in this GitHub.
* **Browser name/version:**
Firefox 58.0
* **NodeJS version:**
Whatever your demo uses?
* **PostgreSQL version:**
Whatever your demo uses?

* **What is the expected behaviour?**
Having a "Register" button under login.
* **What do you see instead?**
No "Register" button under login.

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

**Comment by Chocobozzz** [comment]
PeerTube is still in alpha and the demo servers don't accept public users.

We'll create a website to find an instance (like joinmastodon for example), but before we need to release the beta :)

See this list if your want to test peertube on other servers: https://github.com/Chocobozzz/PeerTube/wiki#other-peertube-servers

**Comment by Copen-08** [comment]
Thank you for the response.
I have checked out  https://video.hispagatos.org and they do not have registering available, so I'm assuming that the best ways to test out PeerTube is to setup my own server, or contact a server admin to get them to make me a account on their server manually.

Since a lot of good YouTube content creators aren't also developers I think it would be a good idea to include the line "Currently PeerTube does not support public registration, but you can contact a PeerTube server admin and ask them to make you an account! Here is a list of PeerTube servers: https://github.com/Chocobozzz/PeerTube/wiki#other-peertube-servers "

This will give people looking at this as a possible video platform to use in the future a lead on how to do better testing, and since they'll know the ins and outs of YouTube better then anyone they will be able to give you far better end user feedback, and maybe even UI feedback then random FLOSS users who only have 1k followers on YouTube.

**Comment by Chocobozzz** [comment]
It's a good idea, I will!

**Comment by bnjbvr** [comment]
Can we imagine something like Mastodon has, that is, having an option to open registrations to everyone (if true, anyone can sign up on the given instance; otherwise, only works the current way it does, or by invites)?

**Comment by Chocobozzz** [comment]
Something like that https://github.com/Chocobozzz/PeerTube/blob/develop/config/default.yaml#L37?

**Comment by bnjbvr** [comment]
Haha, exactly, yes! So I guess the issue being discussed here is getting a block of markdown that would be displayed as text on the login page when registering is disabled? (stealing another Mastodon idea :))
