### ISSUE TITLE
Comments not being shown

### ISSUE THREAD

**Issue by cabaleiro8** [Chocobozzz/PeerTube#2532]
**What happened?**
Videos with several comments does not show all of them

**What do you expect to happen instead?**
Have a load more button, load more comments on scroll or some other approach to be able to see ALL comments

**Steps to reproduce:**
1. https://bittube.video/videos/watch/a29e7fdb-2fa5-4973-92bc-dfa5dd13e4c7
In this URL you can notice that there are 16 comments but only 10 are shown

2. https://peervideo.club/videos/watch/f3cb1945-a8f7-481f-a465-946c6f884e50
In this URL there are 30 comments, but only 20 are shown (if you include replies as comments, there are 28 comments)

**Additional information**
* PeerTube version or URL: 2.1.1
* Browser name/version: Chrome (did not test others)

**Comment by DontUseGithub** [comment]
https://github.com/Chocobozzz/PeerTube/issues/1887

**Comment by Chocobozzz** [comment]
Fixed by @ipbc-dev in https://github.com/Chocobozzz/PeerTube/pull/2535
