### ISSUE TITLE
Unable to update an image over a sound

### ISSUE THREAD

**Issue by webafrancois** [Chocobozzz/PeerTube#2533]
**What happened?**
I upload a sound, and before upload, I choose an associated image.
I upload it and I can see my image and ear my sound.
But if I want to change my image, I can choose and add a new jpg < 2Mo.
It appears in the backoffice. But when I play it, My new image appears, but the old replace it immediatly.

**What do you expect to happen instead?**
The new image should replace the old.

**Steps to reproduce:**
1. upload a sound and add image
2. update a new image
3. play the sound

**Additional information**
* PeerTube version or URL: 2.1.1
* Browser name/version: Firefox 73
* NodeJS version: 10.19.0-1nodesource1 on Debian 10.

* Link to see it :
https://videos.cemea.org/videos/watch/b699a475-ccf8-4f31-b357-4bb620a320c2
(Private link)

**Comment by rigelk** [comment]
The image you choose is most likely the one for the thumbnail, right?

Thing is, the image shown while playing is now part of the video file, and changing it involves transcoding the video again, which is not implemented.

**Comment by webafrancois** [comment]
The sound was imported is a mp3 without include any image.
In the web upload page, i choose an image while uploading.
like here :

And then, after loading and playing, I change my image to another, like here :

But the new image is not update.

**Comment by 3risian** [comment]
I cannot see the images in your reply, but I think I understand.

When you upload originally without any image, PeerTube asks for a 'Video background image' to put in the background. It is then turned into a video. Videos cannot be changed, you may want to delete the video and then reupload, choosing a new image.

It sounds like you are changing the Video Preview (Prévisualisation de la vidéo), which is showing to me as a person on a boat. This is the image shown in menus and other pages to help users see what your video is about. It is separate to the video and will not affect it.

**Comment by webafrancois** [comment]
I update my previous post with the good link.
That's it. And I inderstand.
But the interface looks like that the result will be the same.

When I upload a sound without image, I will not be able to change it.

**Comment by Chocobozzz** [comment]
I think it is clear enough when you upload your video:
![screen_2020-03-12-15:12:13](https://user-images.githubusercontent.com/5180488/76530336-e2f5d600-6473-11ea-9d2b-1ea9c3fc6c42.png)

**The chosen image will be definitive and cannot be modified.**
