### ISSUE TITLE
Use libre formats for video transcoding of 480p and below & fallback to 480p when no proprietary formats are available

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2534]
From what I understood from [here](https://github.com/Chocobozzz/PeerTube/issues/481#issuecomment-587242969) (thank you @tuxayo) we can actually use libre formats for video transcoding of 480p, 360p, 240p and 144p without any issues and without the need of having them in h264 as well. So we're not wasting any extra space or anything.

This is important for at least 2 reasons:
- this will enable those who only use FOSS to start using PeerTube. With this implemented + https://github.com/Chocobozzz/PeerTube/issues/1254 and who knows, maybe even the FSF will start to publicly promote PeerTube.
- some people are technically limited and can only watch videos that are using a FOSS format. This includes people who use completely FOSS OS such as Trisquel, PureOS, Debian (without tweaks), Fedora (without tweaks) etc.. These people currently get this error when trying to watch a video _"No compatible source was found for this media."_ and I think everyone would rather watch that video in 480p than see that error and close that page.

**Comment by Chocobozzz** [comment]
There is already an issue regarding FOSS transcoding.

> without any issues

Incompatibility with iOS and Safari is an issue for us.

**Comment by rigelk** [comment]
Note that tuxayo's assumption regarding < 720p videos only works with the addition of ogv.js, and doesn't work with HLS.

**Comment by rigelk** [comment]
Note that tuxayo's assumption regarding < 720p videos only works with the addition of ogv.js, the most recent/high-end apple devices, and doesn't work with HLS.

**Comment by tuxayo** [comment]
@DontUseGithub
> From what I understood from here (thank you @tuxayo) we can actually use libre formats for video transcoding of 480p, 360p, 240p and 144p without any issues and without the need of having them in h264 as well

Sorry for the confusion, I was only talking about hardware compat which puts constraints regardless about the used browser and OS version. This assumed to run a browser/OS that support libre formats.

Which isn't even possible with iOS if I recall correctly. As even Firefox for iOS has to use Safari engine and I assume can't provide libs for AV1, VP9, Opus, OGG, etc like it does on other platforms.

**Comment by tuxayo** [comment]
At this point my only hope is that there is or will be a regulation in the EU or the US that can force Apple to improve interoperability, like it did for the phone chargers (except for Apple...). OGG isn't even supported even though it existed before the first iOS version...
