### ISSUE TITLE
Recommendation about the search bar

### ISSUE THREAD

**Issue by chopin2712** [Chocobozzz/PeerTube#2536]
Hello, I would like to open an issue again to talk about something with the search bar of Peertube.

On Mastodon, if I search a user that is not known by the list of instances I will find it anyway even if this user will not appear in the “federated feed” of the instance. This is maybe not correct I am a newbie on Mastodon but this is not the point.

So I was wondering if there is or will be an “upgraded search bar”, for example  :

1. I would search @ecoleduchatnoir_channel@sikke.fi in the search bar
2. My server will ask sikke.fi to get the user's channel
3. Sikke.fi gives the information and my instance gives them to me.

So I would be able to access to these videos on an unrecognized instance and maybe be also able to subscribe, like and comment as well.

I don't know how hard this would be but this would be SO easier! If there is not this system there would be 3 different accounts:

1. One to upload videos
2. Another to watch videos because they do not appear on the first one and to interact with it (like, comment)
3. A mastodon account to link with the second Peertube instance to be able to subscribe to the channel. 

And more if there is new other channels that are not recognized.

What do you think, is this implemented yet? If it is the case, how can we solve the problem of different versions of Peertube that could cause errors?

**Comment by chopin2712** [comment]
Linked to #2163 and #1835

**Comment by chopin2712** [comment]
PS: This problem cannot be reproduced with the instance's name I gave you because the sikke.fi is dead.

**Comment by rigelk** [comment]
This is already possible, too provided your instance administrator didn't disable it.

**Comment by 3risian** [comment]
Correct me if I am wrong, but I believe this only works if your instance follows the other channel's instance. This issue is asking if:

* InstanceA does not follow InstanceB
* InstanceA user searches "@channelname@InstanceB"

I understand why this can be annoying (I've created new accounts just to comment on certain instances, despite me already having another PeerTube account to upload videos) but I think this is a part of federation. If you want to view, subscribe, like and comment on videos from an instance, then your instance has to federate with them.

**Comment by Chocobozzz** [comment]
You can search for videos URL or channels URL/handle outside your instance federation if your admin enabled it: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L98

**Comment by JohnXLivingston** [comment]
> PS: This problem cannot be reproduced with the instance's name I gave you because the sikke.fi is dead.

Sorry for the off-topic, just to mention that the channel on your example as migrated here: https://www.yiny.org/video-channels/ecoleduchatnoir/videos (in case you were looking for)

**Comment by 3risian** [comment]
Can you provide a concrete example of this working? I have tried searching for my channel on many 2.1.1 instances and only those following my instance have provided a result.

**Comment by rigelk** [comment]
@3risian the default setting is to enable the functionality only to registered users of an instance, so unless you have an account on them, the test will probably fail.

**Comment by JohnXLivingston** [comment]
It works when searching a video url, but it seems it does not work with a channel handle or url.

**Comment by rigelk** [comment]
Also of note: the new search UI will try to explain what is possible and not possible to search, including content from "any instance". You can see it in action (although not logged-in) at https://peertube2.cpy.re/

**Comment by JohnXLivingston** [comment]
> Also of note: the new search UI will try to explain what is possible and not possible to search, including content from "any instance". You can see it in action (although not logged-in) at https://peertube2.cpy.re/

Searching my handle johnlivingston@www.yiny.org (or @johnlivingston@www.yiny.org) also isn't working on peertube2.cpy.re.

**Comment by rigelk** [comment]
@JohnXLivingston ah, of course. The results UI can only display videos or channels. User accounts own channels but are not channels, and thus don't show in the results.

I'll change the text of the hint.

**Comment by JohnXLivingston** [comment]
If I go here: https://peertube.cpy.re/video-channels/1fccb6e4-863c-4538-a4db-770c464f06a1/videos
The channel ID is 1fccb6e4-863c-4538-a4db-770c464f06a1. When I click on "copy", I get the same ID. The instance url is not copied. If a search just the ID on the other instance, peertube2.cpy.re, I have no result. I have to manually add the instance url : 1fccb6e4-863c-4538-a4db-770c464f06a1@peertube.cpy.re

**Comment by 3risian** [comment]
That new search is great! 

With that alert for 'only followed instances', maybe it could be a hyperlink to the `about/follows/` page.

**Comment by rigelk** [comment]
@3risian ah.. erm, the hint is not clickable at the moment. I'll look into it once that is.

**Comment by chopin2712** [comment]
I got the same problem with the search in peertube2 instance. I need to write the exact same URL to find the instance so it is quite annoying. Also, I wonder if I could like, comment or subscribe to a channel that is not in the following list and found by this way.

PS: This nightly version is looking really nice!

**Comment by Chocobozzz** [comment]
Closing this issue since we answered to the first comment. https://github.com/Chocobozzz/PeerTube/issues/824 could help
