### ISSUE TITLE
Peertube start fails - log shows webserver.https property not defined

### ISSUE THREAD

**Issue by OceanTechie** [Chocobozzz/PeerTube#2537]
**What happened?**

Installed Peertube on Ubuntu 18.04 after installing all dependencies.  After starting peertube, the journal shows error saying webserver.https property is not defined.

I suspect some version thing where this property was introduced but something in my "stack" is wrong version?

**What do you expect to happen instead?**
a log with no errors after running sudo journalctl -feu peertube

**Steps to reproduce:**

1. run sudo systemctl start peertube
2. run sudo journalctl -feu peertube
3. see the below:

Mar 04 03:42:11 ip-172-31-31-175 systemd[1]: Started PeerTube daemon.
Mar 04 03:42:12 ip-172-31-31-175 peertube[27755]: > peertube@2.1.1 start /var/www/peertube/versions/peertube-v2.1.1
Mar 04 03:42:12 ip-172-31-31-175 peertube[27755]: > node dist/server
Mar 04 03:42:12 ip-172-31-31-175 peertube[27755]: /var/www/peertube/versions/peertube-v2.1.1/node_modules/config/lib/config.js:182
Mar 04 03:42:12 ip-172-31-31-175 peertube[27755]:     throw new Error('Configuration property "' + property + '" is not defined');
Mar 04 03:42:12 ip-172-31-31-175 peertube[27755]:     ^
**Mar 04 03:42:12 ip-172-31-31-175 peertube[27755]: Error: Configuration property "webserver.https" is not defined**
Mar 04 03:42:12 ip-172-31-31-175 peertube[27755]:     at Config.get (/var/www/peertube/versions/peertube-v2.1.1/node_modules/config/lib/config.js:182:11)

**Additional information**

* PeerTube version or URL:

v2.1.1

* Browser name/version:
* NodeJS version:
10.19
* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Please paste the content of your systemd service and `/var/www/peertube/config` directory

**Comment by OceanTechie** [comment]
peertube/config directory contains 1 file - production.yaml - i'll paste entire contents in next comment.

My systemd unit file has this for peertube:

[Unit]
Description=PeerTube daemon
After=network.target postgresql.service redis-server.service

[Service]
Type=simple
Environment=NODE_ENV=production
Environment=NODE_CONFIG_DIR=/var/www/peertube/config
User=peertube
Group=peertube
ExecStart=/usr/bin/npm start
WorkingDirectory=/var/www/peertube/peertube-latest
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=peertube
Restart=always

; Some security directives.
; Mount /usr, /boot, and /etc as read-only for processes invoked by this service.
ProtectSystem=full
; Sets up a new /dev mount for the process and only adds API pseudo devices
; like /dev/null, /dev/zero or /dev/random but not physical devices. Disabled
; by default because it may not work on devices like the Raspberry Pi.
PrivateDevices=false
; Ensures that the service process and all its children can never gain new
; privileges through execve().
NoNewPrivileges=true
; This makes /home, /root, and /run/user inaccessible and empty for processes invoked
; by this unit. Make sure that you do not depend on data inside these folders.
ProtectHome=true
; Drops the sys admin capability from the daemon.
CapabilityBoundingSet=~CAP_SYS_ADMIN

[Install]
WantedBy=multi-user.target

**Comment by OceanTechie** [comment]
my entire systemd units -   

 UNIT                                             LOAD   ACTIVE SUB       DESCRIPTION
  proc-sys-fs-binfmt_misc.automount                loaded active waiting   Arbitrary Executable File Formats File System Automount Point
  sys-devices-platform-serial8250-tty-ttyS1.device loaded active plugged   /sys/devices/platform/serial8250/tty/ttyS1
  sys-devices-platform-serial8250-tty-ttyS2.device loaded active plugged   /sys/devices/platform/serial8250/tty/ttyS2
  sys-devices-platform-serial8250-tty-ttyS3.device loaded active plugged   /sys/devices/platform/serial8250/tty/ttyS3
  sys-devices-pnp0-00:06-tty-ttyS0.device          loaded active plugged   /sys/devices/pnp0/00:06/tty/ttyS0
  sys-devices-vbd\x2d768-block-xvda-xvda1.device   loaded active plugged   /sys/devices/vbd-768/block/xvda/xvda1
  sys-devices-vbd\x2d768-block-xvda.device         loaded active plugged   /sys/devices/vbd-768/block/xvda
  sys-devices-vif\x2d0-net-eth0.device             loaded active plugged   /sys/devices/vif-0/net/eth0
  sys-devices-virtual-block-loop0.device           loaded active plugged   /sys/devices/virtual/block/loop0
  sys-devices-virtual-block-loop1.device           loaded active plugged   /sys/devices/virtual/block/loop1
  sys-devices-virtual-block-loop2.device           loaded active plugged   /sys/devices/virtual/block/loop2
  sys-devices-virtual-block-loop3.device           loaded active plugged   /sys/devices/virtual/block/loop3
  sys-devices-virtual-misc-rfkill.device           loaded active plugged   /sys/devices/virtual/misc/rfkill
  sys-devices-virtual-tty-ttyprintk.device         loaded active plugged   /sys/devices/virtual/tty/ttyprintk
  sys-module-configfs.device                       loaded active plugged   /sys/module/configfs
  sys-module-fuse.device                           loaded active plugged   /sys/module/fuse
  sys-subsystem-net-devices-eth0.device            loaded active plugged   /sys/subsystem/net/devices/eth0
  -.mount                                          loaded active mounted   Root Mount
  dev-hugepages.mount                              loaded active mounted   Huge Pages File System
  dev-mqueue.mount                                 loaded active mounted   POSIX Message Queue File System
  run-user-1000.mount                              loaded active mounted   /run/user/1000
  snap-amazon\x2dssm\x2dagent-1480.mount           loaded active mounted   Mount unit for amazon-ssm-agent, revision 1480
  snap-amazon\x2dssm\x2dagent-1566.mount           loaded active mounted   Mount unit for amazon-ssm-agent, revision 1566
  snap-core-8268.mount                             loaded active mounted   Mount unit for core, revision 8268
  snap-core-8689.mount                             loaded active mounted   Mount unit for core, revision 8689
  sys-fs-fuse-connections.mount                    loaded active mounted   FUSE Control File System
  sys-kernel-config.mount                          loaded active mounted   Kernel Configuration File System
  sys-kernel-debug.mount                           loaded active mounted   Kernel Debug File System
  var-lib-lxcfs.mount                              loaded active mounted   /var/lib/lxcfs
  acpid.path                                       loaded active running   ACPI Events Check
  systemd-ask-password-console.path                loaded active waiting   Dispatch Password Requests to Console Directory Watch
  systemd-ask-password-wall.path                   loaded active waiting   Forward Password Requests to Wall Directory Watch
  init.scope                                       loaded active running   System and Service Manager
  session-340.scope                                loaded active running   Session 340 of user ubuntu
  accounts-daemon.service                          loaded active running   Accounts Service
  acpid.service                                    loaded active running   ACPI event daemon
  apparmor.service                                 loaded active exited    AppArmor initialization
  apport.service                                   loaded active exited    LSB: automatic crash report generation
  atd.service                                      loaded active running   Deferred execution scheduler
  blk-availability.service                         loaded active exited    Availability of block devices
  cloud-config.service                             loaded active exited    Apply the settings specified in cloud-config

 cloud-final.service                              loaded active exited    Execute cloud user/final scripts
  cloud-init-local.service                         loaded active exited    Initial cloud-init job (pre-networking)
  cloud-init.service                               loaded active exited    Initial cloud-init job (metadata service crawler)
  console-setup.service                            loaded active exited    Set console font and keymap
  cron.service                                     loaded active running   Regular background program processing daemon
  dbus.service                                     loaded active running   D-Bus System Message Bus
  ebtables.service                                 loaded active exited    ebtables ruleset management
  getty@tty1.service                               loaded active running   Getty on tty1
  grub-common.service                              loaded active exited    LSB: Record successful boot for GRUB
  keyboard-setup.service                           loaded active exited    Set the console keyboard layout
  kmod-static-nodes.service                        loaded active exited    Create list of required static device nodes for the current kernel
  lvm2-lvmetad.service                             loaded active running   LVM2 metadata daemon
  lvm2-monitor.service                             loaded active exited    Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling
  lxcfs.service                                    loaded active running   FUSE filesystem for LXC
  lxd-containers.service                           loaded active exited    LXD - container startup/shutdown
  networkd-dispatcher.service                      loaded active running   Dispatcher daemon for systemd-networkd
  nginx.service                                    loaded active running   A high performance web server and a reverse proxy server
● peertube.service                                 loaded failed failed    PeerTube daemon
  polkit.service                                   loaded active running   Authorization Manager
  postgresql.service                               loaded active exited    PostgreSQL RDBMS
  postgresql@10-main.service                       loaded active running   PostgreSQL Cluster 10-main
  redis-server.service                             loaded active running   Advanced key-value store
  rsyslog.service                                  loaded active running   System Logging Service
  serial-getty@ttyS0.service                       loaded active running   Serial Getty on ttyS0
  setvtrgb.service                                 loaded active exited    Set console scheme
  snap.amazon-ssm-agent.amazon-ssm-agent.service   loaded active running   Service for snap application amazon-ssm-agent.amazon-ssm-agent
  snapd.seeded.service                             loaded active exited    Wait until snapd is fully seeded
  snapd.service                                    loaded active running   Snappy daemon
  ssh.service                                      loaded active running   OpenBSD Secure Shell server
  systemd-journal-flush.service                    loaded active exited    Flush Journal to Persistent Storage
  systemd-journald.service                         loaded active running   Journal Service
  systemd-logind.service                           loaded active running   Login Service
  systemd-machine-id-commit.service                loaded active exited    Commit a transient machine-id on disk
  systemd-modules-load.service                     loaded active exited    Load Kernel Modules
  systemd-networkd-wait-online.service             loaded active exited    Wait for Network to be Configured
  systemd-networkd.service                         loaded active running   Network Service
  systemd-random-seed.service                      loaded active exited    Load/Save Random Seed
  systemd-remount-fs.service                       loaded active exited    Remount Root and Kernel File Systems
  systemd-resolved.service                         loaded active running   Network Name Resolution
  systemd-sysctl.service                           loaded active exited    Apply Kernel Variables
  systemd-timesyncd.service                        loaded active running   Network Time Synchronization
  systemd-tmpfiles-setup-dev.service               loaded active exited    Create Static Device Nodes in /dev
systemd-tmpfiles-setup.service                   loaded active exited    Create Volatile Files and Directories
  systemd-udev-trigger.service                     loaded active exited    udev Coldplug all Devices
  systemd-udevd.service                            loaded active running   udev Kernel Device Manager
  systemd-update-utmp.service                      loaded active exited    Update UTMP about System Boot/Shutdown
  systemd-user-sessions.service                    loaded active exited    Permit User Sessions
  ufw.service                                      loaded active exited    Uncomplicated firewall
  unattended-upgrades.service                      loaded active running   Unattended Upgrades Shutdown
  user@1000.service                                loaded active running   User Manager for UID 1000
  -.slice                                          loaded active active    Root Slice
  system-getty.slice                               loaded active active    system-getty.slice
  system-postgresql.slice                          loaded active active    system-postgresql.slice
  system-serial\x2dgetty.slice                     loaded active active    system-serial\x2dgetty.slice
  system.slice                                     loaded active active    System Slice
  user-1000.slice                                  loaded active active    User Slice of ubuntu
  user.slice                                       loaded active active    User and Session Slice
  acpid.socket                                     loaded active running   ACPID Listen Socket
  dbus.socket                                      loaded active running   D-Bus System Message Bus Socket
  dm-event.socket                                  loaded active listening Device-mapper event daemon FIFOs
  iscsid.socket                                    loaded active listening Open-iSCSI iscsid Socket
  lvm2-lvmetad.socket                              loaded active running   LVM2 metadata daemon socket
  lvm2-lvmpolld.socket                             loaded active listening LVM2 poll daemon socket
  lxd.socket                                       loaded active listening LXD - unix socket
  snapd.socket                                     loaded active running   Socket activation for snappy daemon
  syslog.socket                                    loaded active running   Syslog Socket
  systemd-initctl.socket                           loaded active listening /dev/initctl Compatibility Named Pipe
  systemd-journald-audit.socket                    loaded active running   Journal Audit Socket
  systemd-journald-dev-log.socket                  loaded active running   Journal Socket (/dev/log)
  systemd-journald.socket                          loaded active running   Journal Socket
  systemd-networkd.socket                          loaded active running   Network Service Netlink Socket
  systemd-rfkill.socket                            loaded active listening Load/Save RF Kill Switch Status /dev/rfkill Watch
  systemd-udevd-control.socket                     loaded active running   udev Control Socket
  systemd-udevd-kernel.socket                      loaded active running   udev Kernel Socket
  uuidd.socket                                     loaded active listening UUID daemon activation socket
  basic.target                                     loaded active active    Basic System
  cloud-config.target                              loaded active active    Cloud-config availability
  cloud-init.target                                loaded active active    Cloud-init target
  cryptsetup.target                                loaded active active    Local Encrypted Volumes
  getty.target                                     loaded active active    Login Prompts
  graphical.target                                 loaded active active    Graphical Interface
  local-fs-pre.target                              loaded active active    Local File Systems (Pre)
  local-fs.target                                  loaded active active    Local File Systems
  multi-user.target                                loaded active active    Multi-User System
 systemd-journald.socket                          loaded active running   Journal Socket
  systemd-networkd.socket                          loaded active running   Network Service Netlink Socket
  systemd-rfkill.socket                            loaded active listening Load/Save RF Kill Switch Status /dev/rfkill Watch
  systemd-udevd-control.socket                     loaded active running   udev Control Socket
  systemd-udevd-kernel.socket                      loaded active running   udev Kernel Socket
  uuidd.socket                                     loaded active listening UUID daemon activation socket
  basic.target                                     loaded active active    Basic System
  cloud-config.target                              loaded active active    Cloud-config availability
  cloud-init.target                                loaded active active    Cloud-init target
  cryptsetup.target                                loaded active active    Local Encrypted Volumes
  getty.target                                     loaded active active    Login Prompts
  graphical.target                                 loaded active active    Graphical Interface
  local-fs-pre.target                              loaded active active    Local File Systems (Pre)
  local-fs.target                                  loaded active active    Local File Systems
  multi-user.target                                loaded active active    Multi-User System
  network-online.target                            loaded active active    Network is Online
  network-pre.target                               loaded active active    Network (Pre)
  network.target                                   loaded active active    Network
  nss-lookup.target                                loaded active active    Host and Network Name Lookups
  nss-user-lookup.target                           loaded active active    User and Group Name Lookups
  paths.target                                     loaded active active    Paths
  remote-fs-pre.target                             loaded active active    Remote File Systems (Pre)
  remote-fs.target                                 loaded active active    Remote File Systems
  slices.target                                    loaded active active    Slices
  sockets.target                                   loaded active active    Sockets
  swap.target                                      loaded active active    Swap
  sysinit.target                                   loaded active active    System Initialization
  time-sync.target                                 loaded active active    System Time Synchronized
  timers.target                                    loaded active active    Timers
  apt-daily-upgrade.timer                          loaded active waiting   Daily apt upgrade and clean activities
  apt-daily.timer                                  loaded active waiting   Daily apt download activities
  certbot.timer                                    loaded active waiting   Run certbot twice daily
  fstrim.timer                                     loaded active waiting   Discard unused blocks once a week
  motd-news.timer                                  loaded active waiting   Message of the Day
  systemd-tmpfiles-clean.timer                     loaded active waiting   Daily Cleanup of Temporary Directories

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

145 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.

**Comment by OceanTechie** [comment]
just in case useful, my production.yaml

listen:
  hostname: 'localhost'
  port: 9000

# Correspond to your reverse proxy server_name/listen configuration
webserver:
  http: true
  hostname: 'www.mywebsite.com'
  port: 80

rates_limit:
  api:
    # 50 attempts in 10 seconds
    window: 10 seconds
    max: 50
  login:
    # 15 attempts in 5 min
    window: 5 minutes
    max: 15
  signup:
    # 2 attempts in 5 min (only succeeded attempts are taken into account)
    window: 5 minutes
    max: 2
  ask_send_email:
    # 3 attempts in 5 min
    window: 5 minutes
    max: 3

# Proxies to trust to get real client IP
# If you run PeerTube just behind a local proxy (nginx), keep 'loopback'
# If you run PeerTube behind a remote proxy, add the proxy IP address (or subnet)
trust_proxy:
  - 'loopback'

# Your database name will be "peertube"+database.suffix
database:
  hostname: 'localhost'
  port: 5432
  suffix: '_prod'
  username: 'peertube'
  password: 'xxxxxx'
  pool:
    max: 5

# Redis server for short time storage
# You can also specify a 'socket' path to a unix socket but first need to
# comment out hostname and port
redis:
  hostname: 'localhost'
  port: 6379
  auth: null
  db: 0

rest unchanged from defaul

**Comment by Chocobozzz** [comment]
There is a mistake in your production.yaml. It's `webserver.https` and not `webserver.http`

**Comment by OceanTechie** [comment]
ahhhh, newbie...i modified and restarted peertube - it gets past that error but seems to go into a loop now trying to restart over and over (and I tried changing to port 443 too - same thing).

I had noticed i installed node.js 13.x instead of 10.x - but i removed and installed 10.x and confirmed. I then re-ran install peertube steps - but perhaps this did not do a recompile using node 10.x?  Is there a "remove" or uninstall for peertube and I should retry the whole installation again?

Here is log message:


Mar 05 09:12:47 ip-172-31-31-175 peertube[27805]: > peertube@2.1.1 start /var/www/peertube/versions/peertube-v2.1.1
Mar 05 09:12:47 ip-172-31-31-175 peertube[27805]: > node dist/server
Mar 05 09:12:49 ip-172-31-31-175 peertube[27805]: [www.sharevrpeerdv.com:80] 2020-03-05 09:12:49.445 error: uncaughtException: The module '/var/www/peertube/versions/peertube-v2.1.1/node_modules/bcrypt/lib/binding/bcrypt_lib.node'
Mar 05 09:12:49 ip-172-31-31-175 peertube[27805]: was compiled against a different Node.js version using
Mar 05 09:12:49 ip-172-31-31-175 peertube[27805]: NODE_MODULE_VERSION 79. This version of Node.js requires
Mar 05 09:12:49 ip-172-31-31-175 peertube[27805]: NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
Mar 05 09:12:49 ip-172-31-31-175 peertube[27805]: the module (for instance, using `npm rebuild` or `npm install`).
Mar 05 09:12:49 ip-172-31-31-175 peertube[27805]: Error: The module '/var/www/peertube/versions/peertube-v2.1.1/node_modules/bcrypt/lib/binding/bcrypt_lib.node'
Mar 05 09:12:49 ip-172-31-31-175 peertube[27805]: was compiled against a different Node.js version using
Mar 05 09:12:49 ip-172-31-31-175 peertube[27805]: NODE_MODULE_VERSION 79. This version of Node.js requires
Mar 05 09:12:49 ip-172-31-31-175 peertube[27805]: NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
Mar 05 09:12:49 ip-172-31-31-175 peertube[27805]: the module (for instance, using `npm rebuild` or `npm install`).

**Comment by Chocobozzz** [comment]
Remove node_modules folder and rerun the yarn command

**Comment by OceanTechie** [comment]
Thanks, did that but now fail is saying password authentication failed for user peertube per below.

I do have a unix account called peertube and a postgresql user named peertube and I can connect to the peertube_prod database using that account (in its own command shell) (there are no tables btw).

I've matched the password for the "peertube" user for both ubuntu account of "peertube" and postgresq user "peertube".   I've also set postgresql pg_hba.conf to md5 per below below


Mar 06 00:44:59 ip-172-31-31-175 peertube[14818]: [www.sharevrpeerdv.com:443] 2020-03-06 00:44:59.008 warn: Emailer is disabled so the contact form will not work.
Mar 06 00:44:59 ip-172-31-31-175 peertube[14818]: [www.sharevrpeerdv.com:443] 2020-03-06 00:44:59.527 error: Cannot start application. {
Mar 06 00:44:59 ip-172-31-31-175 peertube[14818]:   "err": {
Mar 06 00:44:59 ip-172-31-31-175 peertube[14818]:     "stack": "SequelizeConnectionError: password authentication failed for user \"peertube\"\n    at connection.connect.err (/var/www/peertube/versions/peertube-v2.1.1/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:182:24)\n    at Connection.connectingErrorHandler (/var/www/peertube/versions/peertube-v2.1.1/node_modules/pg/lib/client.js:194:14)\n    at Connection.emit (events.js:198:13)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v2.1.1/node_m

Here is pg_hba.conf

# Database administrative login by Unix domain socket                                                                                                           local   all             postgres                                md5                                                                                          local   all             peertube                                md5
                                                                                                                                                             # TYPE  DATABASE        USER            ADDRESS                 METHOD
                                                                                                                                                             # "local" is for Unix domain socket connections only
  local   all             all                                     md5                                                                                       # IPv4 local connections:                                                                                                                                      host    all             all             127.0.0.1/32            md5
# IPv6 local connections:                                                                                                                                      host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the                                                                                           # replication privilege.                                                                                                                                       local   replication     all                                     md5                                                                                          host    replication     all             127.0.0.1/32            md5                                                                                          host    replication     all             ::1/128                 md5

**Comment by OceanTechie** [comment]
Sorry that pg_hba.conf was a mess formatting.  here is cleaner copy

# Database administrative login by Unix domain socket                                                                                                           
local   all             postgres                                md5
local   all             peertube                                md5
# TYPE  DATABASE        USER            ADDRESS                 METHOD
# "local" is for Unix domain socket connections only
local   all             all                                     md5
# IPv4 local connections:
 host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
 host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the                                                                                           # replication privilege.
 local   replication     all                                     md5
host    replication     all             127.0.0.1/32            md5                                                                                          host    replication     all             ::1/128                 md5
