### ISSUE TITLE
Add Hungarian translation

### ISSUE THREAD

**Issue by urbalazs** [Chocobozzz/PeerTube#2543]
Hello,

can you please add Hungarian language to PeerTube? I think, there is enough strings translated, since it is 100% now on [Weblate](https://weblate.framasoft.org/languages/hu/peertube/).

Please, also add Hungarian translation for [joinpeertube.org](https://joinpeertube.org/). It is only partially translated yet, but the main page is fully translated. I'm continue to translate it.

Thanks!

**Comment by Chocobozzz** [comment]
Hello,

Hungarian will be available in the next release: https://peertube2.cpy.re/

I added hu locale on JPT: https://framagit.org/framasoft/peertube/joinpeertube/-/commit/ca2525b2a5439b58a9875bb8b2b54a4a2a800670

Thanks for your contribution!
