### ISSUE TITLE
Peertube won't start - permission denied, scandir

### ISSUE THREAD

**Issue by OceanTechie** [Chocobozzz/PeerTube#2544]
**What happened?**

peertube won't start - getting error when looking at log using sudo journalctl -feu peertube

global error - permission denied, scandir  and refers to /home/peertube/.npm
in my case .npm does not exist - i created the peertube user based on past errors that peertube is expecting a ubuntu user called peertube matching password of the peertube postgresql user

log says to use chmod to modify permissions on /home/peertube/.npm, yet when i run this, it says that file does not exist

**What do you expect to happen instead?**

clean start of peertube

Steps:

Installed peertube using ubuntu user (which i log into with pem, not session password)

Does peertube require a peertube user and run install as that user??  Did my installation not create directories and contents required?

I see no instructions to remove peertube so I might start over on the installation and retry this.

**Additional information**
* PeerTube version or URL:
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by rigelk** [comment]
PeerTube doesn't require a specific user name.

What installation guide did you follow, and which steps did you take ?

**Comment by OceanTechie** [comment]
I followed this set of instructions:

https://docs.joinpeertube.org/#/install-any-os

The dependencies included nginx install, redis, certbot, nodejs - and I found others dependent of those.  Thing was first pass on this, i made mistake and had nodejs 13.x which is not supported.  I removed and installed nodejs 10.x per another issue feedback and re-ran the yarn "build"

I kept getting sql connection error with no success connecting the peertube credentials in my production.yaml.  on few retries, i got past that (and had to have pswd same as username, unless some co-incidence there.  

I followed peer tube installation steps - i have ubuntu 18.04 so skipped the sections Free BSD

I did not do the Open RC section

I think i skipped the step under "Administrator" - as I took it to be part of Open RC which I skipped...so without doing that, it has generated password in log??

**Comment by OceanTechie** [comment]
Actually first error in log on start up is saying a relation "application" does not exist - a table?  I notice my database peertube_prod has not tables.  I don't see a step in the script it is executing a database script to create the schema and all tables used by peertube.  I've thought perhaps when detected no tables, the startup process fires off a script - but apparently no.

Is there a step which creates all the required tables in peertube_prod database?   The error later is about the permission denied to /home/peertube/.npm  - and reminder, there is no folder or contents in /home/peertube folder.  Should there be?

Mar 07 21:18:26 ip-172-31-31-175 peertube[5701]: [www.sharevrpeerdv.com:443] 2020-03-07 21:18:26.350 error: Cannot start application. {
Mar 07 21:18:26 ip-172-31-31-175 peertube[5701]:   "err": {
Mar 07 21:18:26 ip-172-31-31-175 peertube[5701]:     "stack": "SequelizeDatabaseError: relation \"application\" does not exist\n    at Query.formatError (/var/www/peertube/versions/peertube-v2.1.1/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)\n    at query.catch.err (/var/www/peertube/versions/peertube-v2.1.1/node_modules/sequelize/lib/dialects/postgres/query.js:72:18)\n    at tryCatcher (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:725:18)\n    at _drainQueueStep (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)",
Mar 07 21:18:26 ip-172-31-31-175 peertube[5701]:     "message": "relation \"application\" does not exist",
Mar 07 21:18:26 ip-172-31-31-175 peertube[5701]:     "name": "SequelizeDatabaseError",
Mar 07 21:18:26 ip-172-31-31-175 peertube[5701]:     "parent": {
Mar 07 21:18:26 ip-172-31-31-175 peertube[5701]:       "stack": "error: relation \"application\" does not exist\n    at Connection.parseE (/var/www/peertube/versions/peertube-v2.1.1/node_modules/pg/lib/connection.js:604:13)\n

**Comment by Chocobozzz** [comment]
> Does peertube require a peertube user and run install as that user??

Yes it does as stated in the documentation: https://docs.joinpeertube.org/#/install-any-os?id=peertube-user

Please reinstall peertube and follow steps of the guide.

**Comment by pscott-au** [comment]
i see the same symptoms following the guide - with the following error in the logs as the application tries to restart:

````{"err":{"stack":"SequelizeDatabaseError: relation \"application\" does not exist\n    at Query.formatError (/var/www/peertube/versions/peertube-v2.4.0/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)````

**Comment by pscott-au** [comment]
# Resolution for my instance from previous comment:
Dropped all tables in schmea
repeated unzip and yarn
modified config/production.yamp to use listening hostname of '0.0.0.0' instead of 'localhost'
