### ISSUE TITLE
Docker postfix - wrong OpenDKIM rights on keys folder - mails fail

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#2545]
**What happened?**

With the actual postfix image `wader/postfix-relay` in docker-compose, we can configure OpenDKIM keys generation and make them persistent by adding `OPENDKIM_DOMAINS` and a mounted volume on `/etc/opendkim/keys`.

Unfortunately, when mounting the volume the image does not handle strict permissions to `opendkim` user on the keys folder (https://github.com/wader/postfix-relay/pull/10).  So postfix can't get the private key and **email sending fails**.

**Steps to reproduce:**

1. Add `OPENDKIM_DOMAINS=<MY DOMAIN>=<selector>` to `.env` 

2. Add `- ./docker-volume/opendkim/keys:/etc/opendkim/keys` volume to the postfix service in `docker-compose.yml`

3. Start your containers `docker-compose up -d`

4. Add the DNS record in you domain found here `cat ./docker-volume/opendkim/keys/*/*.txt`

5. Make sure your registrar updated the DNS records `dig TXT <selector>._domainkey.<MY DOMAIN>` (without any subdomain)

6. Send an email with PeerTube (by lost password link for example)

7. Log PeerTube and Postfix containers  `docker-compose logs peertube` and `docker-compose logs postfix`, If you don't see any logs for postfix you need to connect inside and log `/var/log...` 

**Solutions**
First of all, the image `wader/postfix-relay` seems  not very maintained and is based on a debian image. I found another postfix image based on alpine linux https://github.com/bokysan/docker-postfix. Seems more complete on some features like using the port `587` and lighter than the previous one except there is also an issue about OpenDKIM rights on the keys folder : https://github.com/bokysan/docker-postfix/issues/11 and no generation keys implemented yet.

The solutions I propose are : 
- Handle DKIM signature in PeerTube with emailer / nodemailer and manual generation keys : https://github.com/Chocobozzz/PeerTube/compare/develop...kimsible:feat/dkim-emailer?expand=1
- Handle DKIM signature with the image `boky/postfix` and auto-generation keys / rights fixed in a `Dockerfile.postfix` https://github.com/Chocobozzz/PeerTube/compare/develop...kimsible:feat/dkim-custom-postfix-alpine-docker-image?expand=1

**Questions**
- Maybe, DKIM is not intended to be supported by PeerTube itself or official deployment setups ? **but this is another issue that not receiving email because of the domain verification**.
- Maybe we should propose a custom configuration of Postfix and OpenDKIM avalaible for the "baremetal" and "docker" setup (based on a simple alpine image) ?

**Comment by kimsible** [comment]
This issue (OpenDKIM rights) has been fixed in the `mwader/postfix-relay` image, but found another problem with the generation keys that does not mention the domain in the generated TXT record : https://github.com/wader/postfix-relay/pull/13

So I created another branch to implement DKIM with docker-compose : https://github.com/Chocobozzz/PeerTube/compare/develop...kimsible:feat/dkim?expand=1

Anybody would encourage to create a custom Postix image with alpine linux ? @LecygneNoir ? @Chocobozzz ?

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/2551
