### ISSUE TITLE
How to customized the player 

### ISSUE THREAD

**Issue by freddiehdxd** [Chocobozzz/PeerTube#2547]
- How can we customized the player 
- How to add custom menu
- How to add google captcha to login and register

**Comment by 3risian** [comment]
Hi! This is a bug tracker site, I would recommend posting general questions like this to the [Matrix/IRC room](https://matrix.to/#/#peertube:matrix.org), or on [the official forum](https://framacolibri.org/c/peertube).

Some customizations can be made with plugins. [See this documentation page for more infomation](https://docs.joinpeertube.org/#/admin-customize-instance).

>How to add google captcha to login and register

While this is possible, using Goggle reCAPTCHA is _*highly*_ discouraged by the PeerTube community. See this issue:  https://github.com/Chocobozzz/PeerTube/issues/1721 . Many users will avoid your instance and discourage others from using it.

I would recommend using an alternative captcha through plugins[[1]](https://www.npmjs.com/package/peertube-plugin-hcaptcha) [[2]](https://www.npmjs.com/package/peertube-plugin-mtcaptcha), or none at all.

**Comment by Chocobozzz** [comment]
> How can we customized the player

You can use 'action:video-watch.player.loaded' plugin hook. See https://docs.joinpeertube.org/#/api-plugins?id=client for more information.

> How to add custom menu

There is no easy way to do such thing yet.

> How to add google captcha to login and register

As @3risian said (thanks!)
