### ISSUE TITLE
Random downtimes with HTTP 502 error

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#2548]
**What happened?**
I decided to use a monitoring service for my peertube instance 2 days ago, and since then, it had only 2 short periods of uptime that dured approximatively between 2 and 3 hours, without me doing anything.
**What do you expect to happen instead?**
A 100% uptime.
**Steps to reproduce:**

1. I have no idea, it appeared out of the blue.

**Additional information**
* PeerTube version or URL: 2.1.1
* NodeJS version: 10.17.0
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): https://stemy.me/jirafeau/f.php?h=01BLfV1M&d=1 (warning: the file is heavy).

**Comment by Chocobozzz** [comment]
I don't see 502 errors in your logs. Check your web server logs instead

**Comment by stemy2** [comment]
https://stemy.me/zerobin/?e76c97aea5f5a879#Pde6N9ntaaXd/OowlUqMCak98XPzShcvWV5U05Q2Rqs=

Is that the right log file ?

**Comment by Chocobozzz** [comment]
Could you paste your nginx template please?

**Comment by stemy2** [comment]
> Could you paste your nginx template please?

I don't know where it is.

**Comment by Chocobozzz** [comment]
I can't help without it.

**Comment by rigelk** [comment]
It should be in your /etc/nginx/conf.d folder

**Comment by stemy2** [comment]
I have a file named "peertube.domain.tld.conf" and "domain.tld.conf". I don't know wich one is the right log so i post both of them.

https://stemy.me/zerobin/?109d441aa78d4956#dmeS3UAL59N12ZJzXS30/u/fBnHulDpJIP+3sfrL2rI=

https://stemy.me/zerobin/?7d5c553c36850e5c#FRw+jDzVydLZbpqA5MOo6SHzIzwYotx7uhr0GLGusQM=

**Comment by stemy2** [comment]
According my web monitor, it is not so random. The instance is up every day at 5:30 AM during 3-4 hours, then is down again, and the cycle go on the following days. Why does it happens so regularly ?

**Comment by stemy2** [comment]
Update: I uninstalled my mastodon instance, that was also down (but permanently), and for whatever reason i don't know, it unlocked my peertube instance.

Until now. My peertube instance is down again with a HTTP 502 error, and once again, it came out of the blue.

**Comment by Chocobozzz** [comment]
I'm sorry but I don't think it's a peertube bug. And without nginx error logs or peertube error logs I can't really do anything.
