### ISSUE TITLE
I would like to suggest keeping the web seed.

### ISSUE THREAD

**Issue by zzoozzo1122** [Chocobozzz/PeerTube#255]
Thank you for your efforts in developing a good program.
I'd like to suggest that there are some inconveniences in the use.

First, seeds must be maintained using webtorrent or vuze+webtorrent.
I know this part. However, if two programs are left to seed (200), the program will be down.
Computer performance is cpu 4c/8t , ram32gb ,HDD 4TB(7200rpm),1Gbps 
Peer, it works, it's not working and it's repeated.
So on the peertube, manager page, I want to make space to add web seed links.
If we add web seeds to one of the registered videos, it wouldn't be that inconvenient.

I uploaded the video and placed it in the generated seed file (. torrent)
I manually added the webseed path.
Does not apply.
Wetorrent's program was so unstable that I looked for this method.

If you do, you may need to use a webtorrent or vuze program to keep the seeds.
Is there another way?

**Comment by Chocobozzz** [comment]
If I understand well, you would like to manually add webseed to a specific video.

I think you just want https://github.com/Chocobozzz/PeerTube/issues/123. This issue is about adding other webseeds to specific videos.
