### ISSUE TITLE
Comments tree with deleted comments, can't add reply

### ISSUE THREAD

**Issue by ipbc-dev** [Chocobozzz/PeerTube#2552]
**What happened?**
 If there is some deleted comment in the comments tree, console is showing several errors and you're not able to add a reply to a comment (not deleted) if it have some deleted comment as a parent.
![CommentsIssue](https://user-images.githubusercontent.com/34477436/76399613-d0e23d80-6376-11ea-8028-beb0c352d8b6.png)

**What do you expect to happen instead?**
Fix console errors and be able to reply a comment, even if his parent is deleted

**Steps to reproduce:**

1. Go to a video and add some comments and replies to comments

2. Delete some comment in the middle of the tree

3. Try to add a reply to last comment in the tree

**Additional information**
* PeerTube version or URL: 2.1.1
* Browser name/version: Chrome

**Comment by Chocobozzz** [comment]
Thanks for the issue, should be fixed in https://github.com/Chocobozzz/PeerTube/commit/6cb556449064278bdcb1a54a7b980c2e7bc735f0
