### ISSUE TITLE
Peertube instance home page?

### ISSUE THREAD

**Issue by OceanTechie** [Chocobozzz/PeerTube#2553]
**What happened?**

After some retries, got a successful peertube start (sudo systemctl start peertube) - log looks "clean"
per below mapped to my domain name I set for peertube -  e.g. www.mydomainName.com.  However, loading my domain URL into chrome, I still get nginx default html page - though I commented out the listen entries in available-sites.

**What do you expect to happen instead?**

I thought there is some home page (html or js) for my instance?  something I tag onto my domainname/peerhome.html  or something like that to get all the peertube menu functions of my instance - but can't seem to find any doc showing where that is or how.  I see stuff to run .js stuff to import videos, etc. 

**Steps to reproduce:**

1. sudo systemctl start peertube
2. sudo journalctl -feu peertube

**Additional information**
* PeerTube version or URL:   v2.1.1
* Browser name/version:  chrome
* NodeJS version:  10.13

log output on startup:

Mar 11 07:55:32 ip-172-31-31-175 systemd[1]: Started PeerTube daemon.
Mar 11 07:55:33 ip-172-31-31-175 peertube[4572]: > peertube@2.1.1 start /var/www/peertube/versions/peertube-v2.1.1
Mar 11 07:55:33 ip-172-31-31-175 peertube[4572]: > node dist/server
Mar 11 07:55:38 ip-172-31-31-175 peertube[4572]: [www.sharevrpeerdv.com:443] 2020-03-11 07:55:38.091 warn: Emailer is disabled so the contact form will not work.
Mar 11 07:55:39 ip-172-31-31-175 peertube[4572]: [www.sharevrpeerdv.com:443] 2020-03-11 07:55:39.482 info: Database peertube_prod is ready.
Mar 11 07:55:41 ip-172-31-31-175 peertube[4572]: [www.sharevrpeerdv.com:443] 2020-03-11 07:55:41.701 info: Creating a default OAuth Client.
Mar 11 07:55:41 ip-172-31-31-175 peertube[4572]: [www.sharevrpeerdv.com:443] 2020-03-11 07:55:41.708 info: Creating application account.
Mar 11 07:55:41 ip-172-31-31-175 peertube[4572]: [www.sharevrpeerdv.com:443] 2020-03-11 07:55:41.723 info: Creating the administrator.
Mar 11 07:55:41 ip-172-31-31-175 peertube[4572]: [www.sharevrpeerdv.com:443] 2020-03-11 07:55:41.745 info: Client id: 04rt4ngx3998hicvphsqyukvm4hsp3yc
Mar 11 07:55:41 ip-172-31-31-175 peertube[4572]: [www.sharevrpeerdv.com:443] 2020-03-11 07:55:41.746 info: Client secret: jzHdU4uSsc3xfv3x4QNVpempAvkUmYWP
Mar 11 07:55:41 ip-172-31-31-175 peertube[4572]: [www.sharevrpeerdv.com:443] 2020-03-11 07:55:41.773 info: Generating a RSA key...
Mar 11 07:55:41 ip-172-31-31-175 peertube[4572]: [www.sharevrpeerdv.com:443] 2020-03-11 07:55:41.947 info: Generating a RSA key...
Mar 11 07:55:41 ip-172-31-31-175 peertube[4572]: [www.sharevrpeerdv.com:443] 2020-03-11 07:55:41.948 info: Generating a RSA key...
Mar 11 07:55:42 ip-172-31-31-175 peertube[4572]: [www.sharevrpeerdv.com:443] 2020-03-11 07:55:42.154 info: Username: root
Mar 11 07:55:42 ip-172-31-31-175 peertube[4572]: [www.sharevrpeerdv.com:443] 2020-03-11 07:55:42.155 info: User password: xxxxyadayada
Mar 11 07:55:42 ip-172-31-31-175 peertube[4572]: [www.sharevrpeerdv.com:443] 2020-03-11 07:55:42.159 error: Cannot use SMTP server because of lack of configuration. PeerTube will not be able to send mails!
Mar 11 07:55:42 ip-172-31-31-175 peertube[4572]: [www.sharevrpeerdv.com:443] 2020-03-11 07:55:42.183 info: Cleaning HTML cache.
Mar 11 07:55:42 ip-172-31-31-175 peertube[4572]: [www.sharevrpeerdv.com:443] 2020-03-11 07:55:42.225 info: Server listening on localhost:9000
Mar 11 07:55:42 ip-172-31-31-175 peertube[4572]: [www.sharevrpeerdv.com:443] 2020-03-11 07:55:42.226 info: Web server: https://www.sharevrpeerdv.com

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by rigelk** [comment]
Hi @OceanTechie! what installation guide did you follow and what steps did you take?

**Comment by OceanTechie** [comment]
Guide used is https://docs.joinpeertube.org/#/install-any-os

is there any other? Followed for Any OS (Ubuntu Linux).  Performed all the steps, verified unix account and postgres peer tube users.  Looks like peer_tube database got all tables created.

ran the let's encrypt step - and got problem restarting nginx - had to edit my default website [::]80 and 443 to comment those out of default as it reported another server had that.  After than restart nginx worked, proceeded with steps.

Did the systemd cp step - but in looking at the peertube.service, i left all defaults in there, as i think they will do.

in particular left this ExecStart=/usr/bin/npm start as is along with the working directory statement.
started peertube - journalctl -feu output looks correct and is included in previous post

I'm not sure if I have to configure nginx config to point to peertube home page or assure some process is launched, or go to client and server tools, but I was figuring i'd have a URL to hit on my instance to get all the standard peertube web pages/UI.

Sorry if i'm missing something obvious, but i'm not getting clarity from the docs.

**Comment by Chocobozzz** [comment]
I can't get https://www.sharevrpeerdv.com/

What is you peertube instance url?

**Comment by OceanTechie** [comment]
that is the domain i created and want to use.  I was getting the nginx default welcome page.  Now I'm getting nothing loaded.  But, I had removed HTTPS from my AWS EC2 server instance trying to resolve another problem. I added inbound rules back in, but still won't load-  maybe I need to restart my aws server to activate?

I'd appreciate pointing me to documentation and step where I am to configure nginx to point to peertube's home page

**Comment by Chocobozzz** [comment]
I can't see DNS records for you `www.sharevrpeerdv.com` so I can't get it.

Webserver config instructions are there: https://docs.joinpeertube.org/#/install-any-os?id=webserver

**Comment by OceanTechie** [comment]
Thanks I got it...i had to straighten out my hosted zone.

Question - the CLI tools say to install in a separate directory from my main peertube instance, but doing so, the alias I setup for my ubuntu user - says no permissions for some folder.  I'll create a separate issue on that.  Can you confirm folder I created and installed CLI tools in is OK to place in/var/www/peerclone?

**Comment by Chocobozzz** [comment]
> Can you confirm folder I created and installed CLI tools in is OK to place in/var/www/peerclone?

You put this folder when you cant, it shouldn't matter.

**Comment by anvaruk** [comment]
I have similar problem, followed instructions https://github.com/Chocobozzz/PeerTube/issues/2553
but at the end I see nginx default page..
probably something with nginx config, but I just followed instructions on a blank ubuntu 18,04 
no errors in nginx or peertube log files..
