### ISSUE TITLE
duplicate key value violates unique constraint "video_file_video_streaming_playlist_id_resolution_fps"

### ISSUE THREAD

**Issue by xcffl** [Chocobozzz/PeerTube#2554]
**What happened?**
I select transcoding for 1080p and meanwhile enable HLS encoding. Finally the transcoding fails.
Peertube's log:
````

 
--
{   "type": "hls",   "videoUUID": "be49444b-e474-48b5-9e6c-64e5b6141e97",   "resolution": 1080,   "isPortraitMode": false,   "copyCodecs": false }

SequelizeUniqueConstraintError: Validation error     at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:324:18)     at query.catch.err (/app/node_modules/sequelize/lib/dialects/postgres/query.js:72:18)     at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:725:18)     at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)     at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)     at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)     at runCallback (timers.js:705:18)     at tryOnImmediate (timers.js:676:5)     at processImmediate (timers.js:658:5)
````
Postgresql's log:
````
*** [4068] ERROR:  duplicate key value violates unique constraint "video_file_video_streaming_playlist_id_resolution_fps"
*** [4068] DETAIL:  Key ("videoStreamingPlaylistId", resolution, fps)=(1897, 1080, 30) already exists.
*** [4068] STATEMENT:  INSERT INTO "videoFile" ("id","resolution","size","extname","infoHash","fps","videoStreamingPlaylistId","createdAt","updatedAt") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8) RETURNING *;
````
**What do you expect to happen instead?**
The transcoding finishes, and the hls playlist is generated.

**Steps to reproduce:**

1. Enable 1080p resolution, WebTorrent support and HLS support

2. Initiate transcoding by `node ./dist/scripts/create-transcoding-job.js "--generate-hls" "-v" my-uuid`

3. Look at the log of peertube and postgresql after it finishes computation.

**Additional information**
* PeerTube version or URL: 2.1.1
* Browser name/version: Firefox 76.0a1
* NodeJS version: v10.19.0

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by xcffl** [comment]
It's simply because we set `("videoStreamingPlaylistId", resolution, fps)` as a composite key, rather than `infoHash`.
We should either use a another unique field as KEY, or gracefully update that record.

**Comment by Chocobozzz** [comment]
Thanks, fixed in https://github.com/Chocobozzz/PeerTube/commit/c547bbf96a46166c4b4548413b092c58f7b0e37a
