### ISSUE TITLE
Updating the language translation

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#2555]
I have updated many translation lines to my own language as indicated in the instructions https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/translation.md. How do I quickly update the current translation of my instance?

**Comment by rigelk** [comment]
The standard process is to wait for the next minor release, for which translations are then updated.

Otherwise, I guess you could always download the translation that interests you: `https://weblate.framasoft.org/download/peertube/angular/<lang code>/?format=xliff` and replace the content of the corresponding lang file in the PeerTube source code of your instance. Then recompile and restart.

**Comment by Alterak** [comment]
I downloaded the translation archive https://weblate.framasoft.org/download/peertube/angular/ then I replaced the angular.ru-RU.xlf file in the /var/www/peertube/versions/peertube-v2.1.1/client/dist/locale directory and restarted the peertube service, but no changes occurred. Help me fix it.

**Comment by rigelk** [comment]
You have to recompile the code from source.

**Comment by Alterak** [comment]
Why is it so difficult? Do I need to re-install peertube on my server?

**Comment by rigelk** [comment]
Maybe @Chocobozzz knows a simpler way, but as far as I know, you need to re-install it from source to be able to compile it with the newly translated file.

I know this is unpractical, but this is due to the way the internationalization is implemented in Angular.

**Comment by Alterak** [comment]
Unfortunately, it didn't work out. I completely deleted the **peertube-v2.1.1** directory, downloaded it, unzipped it, added the modified language file to the **/var/www/peertube/versions/peertube-v2.1.1/client/dist/locale** folder, and installed it. But the translation was not corrected-(

**Comment by Chocobozzz** [comment]
I'm sorry but updating translations on your instance is not supported. It's complicated because languages are injected by Angular in the built JS files. You can try to build PeerTube yourself, but I'm sorry we don't have time to support this install method.

**Comment by Alterak** [comment]
Very sorry. I would very much like to perform a full and good translation of all the peertube functionality in online testing mode, while still being able to quickly fix it.
