### ISSUE TITLE
Changed Production.yaml, restarted peertube, no changes seen

### ISSUE THREAD

**Issue by OceanTechie** [Chocobozzz/PeerTube#2556]
**What happened?**

Tried to change production yaml in order to enable login button to allow create login accounts.  Default behavior has message not accepting logins.

Simple change to production.yaml in /var/www/peertube/peertube-latest/config

signup:
    enabled: true

also changed about text for describing my instance.

Restarted peertube, via "sudo systemctl stop peertube" and "sudo systemctl start peertube"

**What do you expect to happen instead?**

Login button allows creation of users - instead, still seeing text this instance is not accepting create logins.

Expect about page changes to reflect text input into production.yaml

**Steps to reproduce:**

1. edit production.yaml

in /var/www/peertube/peertube-latest/config

2. restart peertube

How can I verify what yaml file peertube used to load/reload?

The example.yaml and production.yaml.example files are still present in the folder - do I need to remove any files?

**Additional information**
* PeerTube version or URL:
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by JohnXLivingston** [comment]
Settings that can be change be the interface are overloaded in config/local-production.json. Use the admin interface to change them. So you don't have to restart peertube. 
If you want to learn more about how configuration files works, you can read this: https://github.com/lorenwest/node-config/wiki/Configuration-Files

**Comment by OceanTechie** [comment]
Got it thanks.
