### ISSUE TITLE
Remove "Watching this video may reveal your IP address to others" from embeds if the p2p player is disabled on a certain video or server

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#2557]
This issue is similar to my previous issue https://github.com/Chocobozzz/PeerTube/issues/2370 except that this one refers to embeds.
Again, I don't know if this is an actual issue because I can't find a suitable video/instance to test this. 

I've asked https://github.com/Chocobozzz/PeerTube/issues/2370#issuecomment-570519203 Chocobozzz if the fix he's applied to the previous issue covers embeds as well, but since he hasn't answered I've decided to go ahead and create this new issue, to make sure we're not scaring people with that message when it isn't needed :smiley:  

Again, sorry if this is a non-issue.

**Comment by shawnray-cloud** [comment]
An implementation of this would really help. Thanks in advance in case you decide to implement this idea!

**Comment by Chocobozzz** [comment]
@shawnray-cloud could you explain your use case?

**Comment by shawnray-cloud** [comment]
Sure! One time, I needed to embed a video of a ceremony a couple of days ago. Neither the video nor the instance actually had P2P. The warning persisted, however, which I do imagine can really confuse and scare someone who hasn't used PeerTube before. I don't think you should make the warning configurable (to prevent fraud), but it would be nice to have the warning not show on videos where P2P won't be used.

**Comment by Chocobozzz** [comment]
Thanks. It's weird because if the tracker is disabled on the origin instance, the message should not be displayed. Could you share to me the video? (my email is in my github profile if you prefer to not share the video publicly)

**Comment by shawnray-cloud** [comment]
@Chocobozzz I just realized that there was a whole embed menu in the share button. Apparently, there are already settings for this purpose. The reason for my confusion was because I thought the only way to embed was to right-click and then click "Copy embed code". This solves the problem with my particular use case. I am fairly new to PeerTube, and that was probably why I had the confusion. Thanks though for your patience!

**Comment by shawnray-cloud** [comment]
In fact, if I'm not mistaken, I think that the embed settings in the share button actually solve this issue, and therefore,  if I'm not mistaken, it's actually safe to close this issue.

**Comment by AnonymousWebHacker** [comment]
The same happens with Mastodon, if a lik of peertube is published, the visualization shows the warning
