### ISSUE TITLE
Ability to replace a video file in order to publish new versions of a video

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#2559]
In order to publish a new version of a video (including addenda or corrections) without losing views and comments, I used to invoke the `create-import-video-file-job` command in order to replace the older version of a video. It may have been a bit hacky-ish but it used to work well.

It seems that's not feasible anymore, or at least it is buggy:
- When you view the last seconds of this video, you don't see the Skeptikon animation: https://skeptikon.fr/videos/watch/b76e3d66-737d-4052-9876-e87b20c79c56
- But you do when you download it (you can notice that the duration is 14:44 instead of 14:41): https://skeptikon.fr/download/videos/b76e3d66-737d-4052-9876-e87b20c79c56-1080.mp4

The ability to replace video files has been a killer feature compared to Youtube. Video makers as well as users really appreciate it.

It would be nice to make an official how-to in order to implement that feature again (either via an administrator action or directly offered as an option to video makers).

Thanks!

**Comment by DontUseGithub** [comment]
https://github.com/Chocobozzz/PeerTube/issues/1845

**Comment by fflorent** [comment]
@DontUseGithub Thanks!
