### ISSUE TITLE
Adv

### ISSUE THREAD

**Issue by Butonix** [Chocobozzz/PeerTube#256]
Hi
1)You have plans, add the ability to embed advertising in video, as in YouTube.
For example, you can insert into any video, but you can when the video has 1000 views, automatically include ads for this video
2) Also add the possibility of a live broadcast

**Comment by Chocobozzz** [comment]
I'm sorry but no, advertising is out of PeerTube scope.

For live streaming there is already an issue: https://github.com/Chocobozzz/PeerTube/issues/151

**Comment by kellysfu** [comment]
> I'm sorry but no, advertising is out of PeerTube scope.
> 
> For live streaming there is already an issue: #151

One thing i don't understand.  As a Streaming Site. it costs lots of money. How can you keep your website if there is no Advertisements?

Just for hobby？？？

no offense. peertube will not last long if there is no advertisements.  people will stay away peertube.

Peertube is not a new program.   There was so many similar p2p programs sinice 2007 in China. the most popular one is QvodPlayer.  The only difference is you just install the QvodPlayer on your PC if you want to watch the videos.
