### ISSUE TITLE
Weird duration display on long videos

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2560]
**What happened?**
On some videos that last more than 1 hour, the duration displayed underneath the video is wrong.
For example here: https://www.yiny.org/videos/watch/eade5066-8103-44c1-b51c-e58c14f92412
The video last 1:26:00, but the duration displayed is «1 h 25 min 3659 sec» (in french)

See this screenshot:
![image](https://user-images.githubusercontent.com/38844060/76823375-543add80-6814-11ea-9550-97829bfc1443.png)

I have other videos with the same glitch (for example «1 h 28 min 3641 sec» for 1:28:41). 

**Additional information**
* PeerTube version or URL: v2.1.1
* Browser name/version: Firefox

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/03db5c3f979928419fb3ead8c65f0bce12d07f5c
