### ISSUE TITLE
Plugin request: different plans/tiers

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2561]
This isn't something new so I don't think it needs to be much described.
This is how Vimeo did it back in the day:
![dqw](https://user-images.githubusercontent.com/57924087/76882658-a5ce8100-6883-11ea-9652-b6bc5d5d0fc4.png)

This plugin can be very simple at the beginning and only differentiate between tiers by storage.

- FREE - 1GB
- $1 - 5GB
- $3 - 6GB 

etc.. this is just an example.

**WHY?**
Because this way server admins will have a bigger motivation to better take care of their server, while their users will enjoy being part of such a nice server. I don't see any ethical issues of this monetization option, if you do, please post a comment. After all this is just an optional plugin.

**Comment by Chocobozzz** [comment]
Hi,

Please use https://framagit.org/framasoft/peertube/official-plugins/issues for plugin requests.
