### ISSUE TITLE
Avatar deleted soon after changing

### ISSUE THREAD

**Issue by stefanor** [Chocobozzz/PeerTube#2562]
**What happened?**

1. A channel (that has subscribers) has an avatar.
1. I change the avatar to a new image.
1. It visibly changes.
1. I see a row in the avatar table, with `filename=$uuid`, `fileUrl=Null`, `onDisk=True`.
1. A minute later, I see that row is gone, replaced with a new one with `filename=$uuid`, `fileUrl=$instance/lazy-static/avantars/$different-uuid`, `onDisk=False`.
1. The avatar image now 404s.

**What do you expect to happen instead?**

1. I expect my avatar to persist.

**Steps to reproduce:**

Not entirely sure, but judging from #2493, this is related to having channel subscribers.

**Workaround:**

Immediately set `fileUrl` on the new avatar, before peertube checks it.

**Additional information**
* PeerTube version or URL: https://peertube.debian.social/ (2.1.1)
* Browser name/version: Chromium 80.0.3987.132-1 (Debian)
* NodeJS version: 13.7.0

**Comment by stefanor** [comment]
> this is related to having channel subscribers.

Yep. Create a channel, set a favicon. Have someone subscribe to it. Then edits to the channel will delete the favicon.

**Comment by Chocobozzz** [comment]
Could you paste debug server logs when you reproduce this bug please?

**Comment by stefanor** [comment]
I have a log, which is annoyingly big.

https://share.riseup.net/#-bxZdwUy9bPj1X7yPMF1BQ

**Comment by Chocobozzz** [comment]
Could you paste output of `select id, url, "inboxUrl", "outboxUrl", "sharedInboxUrl" from actor where "type" = 'Application' and "serverId" is null;` please?

**Comment by Chocobozzz** [comment]
Also, could you try to find the job log of `2020-03-17 21:36:42.493`? In admin, `activitypub-http-broadcast` -> `completed`

**Comment by highvoltage** [comment]
Hi @Chocobozzz, I'm also an admin on that instance.

SQL Output:
"""
 id |                       url                        |                        inboxUrl                        |                        outboxUrl                        |            sharedInboxUrl            
----+--------------------------------------------------+--------------------------------------------------------+---------------------------------------------------------+--------------------------------------
  1 | https://peertube.debian.social/accounts/peertube | https://peertube.debian.social/accounts/peertube/inbox | https://peertube.debian.social/accounts/peertube/outbox | https://peertube.debian.social/inbox
(1 row)
"""

As for the job ID... that's difficult to find in the web UI, it seems like this job happenned 336987 times and fills 16211 pages on the web UI. Could it be that it runs excessively? We also suspected at one point that someone was attempting a DoS against us, not sure if that could be related.

**Comment by Chocobozzz** [comment]
I seems your instance tries is posting activities to yourself, but I don't really understand why since we have filters to avoid this kind of behaviour.

It's the reason why I would like to check your job logs, to see where the AP messages are being sent.

**Comment by Chocobozzz** [comment]
Do you still have the issue @stefanor?
