### ISSUE TITLE
The pod table does not exist during installation and cannot be restored after manually created

### ISSUE THREAD

**Issue by 53537** [Chocobozzz/PeerTube#2564]
**What happened?**

The installation failed, and I was told that the table did not exist, but I manually created the pods table and still could not solve the problem. I have tried to reset postgresql many times, and I have restarted peertube and turned on debug, but I still sent the solution

**What do you expect to happen instead?**
Can you help me figure out why the pods table doesn't exist and still tell me that it failed to start after manually creating it
**Steps to reproduce:**

1.
centos 7
nodejs 12.16

2.
Follow this link to install the centos dependency environment：
https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/dependencies.md#centos-7

3.
Follow this link to install：
https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#installation

4.
After starting peertube in systemctl, you see an error in the log；
I really like this project. Please help me solve this problem. Thank you

**Additional information**
* PeerTube version or URL:
* Browser name/version: chrome
* NodeJS version: 12.16

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

{"level":"debug","message":"Checking NodeJS version v12.16.1.","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:51.988Z"}
{"message":"Emailer is disabled so the contact form will not work.","level":"warn","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:55.579Z"}
{"message":"Executing (default): SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type LIKE '%TABLE' AND table_name != 'spatial_ref_sys';","level":"debug","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:57.044Z"}
{"message":"Executing (default): SELECT \"migrationVersion\" FROM \"application\"","level":"debug","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:57.125Z"}
{"message":"Executing (default): INSERT INTO \"application\" (\"migrationVersion\") VALUES (0)","level":"debug","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:57.133Z"}
{"message":"Begin migrations.","level":"info","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:57.167Z"}
{"level":"info","message":"Executing 0005-email-pod.js migration script.","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:57.187Z"}
{"message":"Executing (20bf9d8c-4abd-4f15-9417-dca5ebe26f33): START TRANSACTION;","level":"debug","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:57.201Z"}
{"message":"Executing (20bf9d8c-4abd-4f15-9417-dca5ebe26f33): SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;","level":"debug","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:57.210Z"}
{"message":"Executing (default): ALTER TABLE \"public\".\"Pods\" ADD COLUMN \"email\" VARCHAR(400) NOT NULL DEFAULT '';","level":"debug","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:57.241Z"}
{"message":"Executing (20bf9d8c-4abd-4f15-9417-dca5ebe26f33): ROLLBACK;","level":"debug","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:57.253Z"}
{"level":"error","message":"Cannot execute migration 0005.","label":"isdomain.io:443","err":{"stack":"SequelizeDatabaseError: relation \"public.Pods\" does not exist\n    at Query.formatError (/var/www/peertube/versions/peertube-v2.1.1/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)\n    at /var/www/peertube/versions/peertube-v2.1.1/node_modules/sequelize/lib/dialects/postgres/query.js:72:18\n    at tryCatcher (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:725:18)\n    at _drainQueueStep (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:15:14)\n    at processImmediate (internal/timers.js:456:21)","message":"relation \"public.Pods\" does not exist","name":"SequelizeDatabaseError","parent":{"stack":"error: relation \"public.Pods\" does not exist\n    at Connection.parseE (/var/www/peertube/versions/peertube-v2.1.1/node_modules/pg/lib/connection.js:604:13)\n    at Connection.parseMessage (/var/www/peertube/versions/peertube-v2.1.1/node_modules/pg/lib/connection.js:403:19)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v2.1.1/node_modules/pg/lib/connection.js:123:22)\n    at Socket.emit (events.js:311:20)\n    at addChunk (_stream_readable.js:294:12)\n    at readableAddChunk (_stream_readable.js:275:11)\n    at Socket.Readable.push (_stream_readable.js:209:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)","message":"relation \"public.Pods\" does not exist","name":"error","length":102,"severity":"ERROR","code":"42P01","file":"namespace.c","line":"402","routine":"RangeVarGetRelidExtended","sql":"ALTER TABLE \"public\".\"Pods\" ADD COLUMN \"email\" VARCHAR(400) NOT NULL DEFAULT '';"},"sql":"ALTER TABLE \"public\".\"Pods\" ADD COLUMN \"email\" VARCHAR(400) NOT NULL DEFAULT '';"},"timestamp":"2020-03-18T08:56:57.257Z"}

**Comment by Chocobozzz** [comment]
Drop and recreate your database, then run peertube and paste output

**Comment by 53537** [comment]
Yes, I have seen delete and rebuild in issues, and I did the same. This error log is the log I got after I deleted and rebuilt the database
--------
This is the dubug error log：
{"level":"debug","message":"Checking NodeJS version v12.16.1.","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:51.988Z"}
{"message":"Emailer is disabled so the contact form will not work.","level":"warn","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:55.579Z"}
{"message":"Executing (default): SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type LIKE '%TABLE' AND table_name != 'spatial_ref_sys';","level":"debug","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:57.044Z"}
{"message":"Executing (default): SELECT "migrationVersion" FROM "application"","level":"debug","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:57.125Z"}
{"message":"Executing (default): INSERT INTO "application" ("migrationVersion") VALUES (0)","level":"debug","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:57.133Z"}
{"message":"Begin migrations.","level":"info","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:57.167Z"}
{"level":"info","message":"Executing 0005-email-pod.js migration script.","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:57.187Z"}
{"message":"Executing (20bf9d8c-4abd-4f15-9417-dca5ebe26f33): START TRANSACTION;","level":"debug","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:57.201Z"}
{"message":"Executing (20bf9d8c-4abd-4f15-9417-dca5ebe26f33): SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;","level":"debug","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:57.210Z"}
{"message":"Executing (default): ALTER TABLE "public"."Pods" ADD COLUMN "email" VARCHAR(400) NOT NULL DEFAULT '';","level":"debug","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:57.241Z"}
{"message":"Executing (20bf9d8c-4abd-4f15-9417-dca5ebe26f33): ROLLBACK;","level":"debug","label":"isdomain.io:443","timestamp":"2020-03-18T08:56:57.253Z"}
{"level":"error","message":"Cannot execute migration 0005.","label":"isdomain.io:443","err":{"stack":"SequelizeDatabaseError: relation "public.Pods" does not exist\n at Query.formatError (/var/www/peertube/versions/peertube-v2.1.1/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)\n at /var/www/peertube/versions/peertube-v2.1.1/node_modules/sequelize/lib/dialects/postgres/query.js:72:18\n at tryCatcher (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/util.js:16:23)\n at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:547:31)\n at Promise._settlePromise (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:604:18)\n at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:649:10)\n at Promise._settlePromises (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:725:18)\n at _drainQueueStep (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:93:12)\n at _drainQueue (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:86:9)\n at Async._drainQueues (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:102:5)\n at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:15:14)\n at processImmediate (internal/timers.js:456:21)","message":"relation "public.Pods" does not exist","name":"SequelizeDatabaseError","parent":{"stack":"error: relation "public.Pods" does not exist\n at Connection.parseE (/var/www/peertube/versions/peertube-v2.1.1/node_modules/pg/lib/connection.js:604:13)\n at Connection.parseMessage (/var/www/peertube/versions/peertube-v2.1.1/node_modules/pg/lib/connection.js:403:19)\n at Socket. (/var/www/peertube/versions/peertube-v2.1.1/node_modules/pg/lib/connection.js:123:22)\n at Socket.emit (events.js:311:20)\n at addChunk (_stream_readable.js:294:12)\n at readableAddChunk (_stream_readable.js:275:11)\n at Socket.Readable.push (_stream_readable.js:209:10)\n at TCP.onStreamRead (internal/stream_base_commons.js:186:23)","message":"relation "public.Pods" does not exist","name":"error","length":102,"severity":"ERROR","code":"42P01","file":"namespace.c","line":"402","routine":"RangeVarGetRelidExtended","sql":"ALTER TABLE "public"."Pods" ADD COLUMN "email" VARCHAR(400) NOT NULL DEFAULT '';"},"sql":"ALTER TABLE "public"."Pods" ADD COLUMN "email" VARCHAR(400) NOT NULL DEFAULT '';"},"timestamp":"2020-03-18T08:56:57.257Z"}

**Comment by 53537** [comment]
This is my step to rebuild the database：
---
systemctl stop peertube
psql  -U peertube -d postgres -p 5432
DROP DATABASE peertube_prod;
sudo -u postgres createdb -O peertube -E UTF8 -T template0 peertube_prod
sudo -u postgres psql -c "CREATE EXTENSION pg_trgm;" peertube_prod
sudo -u postgres psql -c "CREATE EXTENSION unaccent;" peertube_prod
systemctl start peertube

**Comment by Chocobozzz** [comment]
What is your postgresql version?

**Comment by 53537** [comment]
psql (PostgreSQL) 9.2.24

**Comment by Chocobozzz** [comment]
You need postgresql >= 9.6

**Comment by 53537** [comment]
Oh, thank you very much. I'll try it first
