### ISSUE TITLE
Tracking user video file size uploaded

### ISSUE THREAD

**Issue by OceanTechie** [Chocobozzz/PeerTube#2565]
**What happened?**

Can I get at what files and what size are the files for each account/user?   That is track all video files and their size uploaded by each user?

In the peertube database schema, I see the videos table which shows file size, but I don't see any table which connects video file id to the user that uploaded it.

**What do you expect to happen instead?**

Documentation for database schema and all data content in peertube database - is there such documentation?

I'm seeking to extend/enhance my peer tube instance behaviors and meter the total file space uploaded by each user. 

e.g. - can I get a list of users who have uploaded more than X GB's of videos.

**Additional information**
* PeerTube version or URL:
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by rigelk** [comment]
> Documentation for database schema and all data content in peertube database - is there such documentation?

What kind of documentation do you expect? There is no standard that I know of, unlike API documentation for instance.

---

In the meantime, our column naming is pretty uniform. For instance, the files are tracked in the `videoFile` table, and there you have a `videoFile.videoId` that can be joined to a `video.videoId` in the `video` table. Each video in the `video` table has a `video.channelId`, and each channel in the `videoChannel` table has a `videoChannel.accountId`, and each account in the `account` table has a `account.userId`, which you can build your query with.

For instance, in `server/models/account/user.ts`, the quota used is queried with the following join, which retraces the above (note at least `"UserModel.id"` is replaced by sequelize, so don't go try pasting it without a specific id instead):

```sql
SELECT COALESCE(SUM("size"), 0)
FROM (
SELECT MAX("videoFile"."size") AS "size" FROM "videoFile"
INNER JOIN "video" ON "videoFile"."videoId" = "video"."id"
INNER JOIN "videoChannel" ON "videoChannel"."id" = "video"."channelId"
INNER JOIN "account" ON "videoChannel"."accountId" = "account"."id"
WHERE "account"."userId" = "UserModel"."id" GROUP BY "video"."id"'
) t
```

Personnaly, I find table descriptions (i.e. `\d "videos"`) within pg to be enough hints, at least for common joins and foreign keys. If I need something more specific, each table has an eponym model file that describes how composite attributes are queried - and they are good examples.

---

> I'm seeking to extend/enhance my peertube instance behaviors and meter the total file space uploaded by each user.

You mean the quota used, a stat that is already reported in the users list?

**Comment by OceanTechie** [comment]
thank you.  I was examining the tables to ascertain design intention myself but did not see the channel relation as yet - my bad, as i was expecting video to have account or userid directly and was seeking a published data dictionary or ER diagram to assist.   This helps a lot.
