### ISSUE TITLE
Error importing video via url and torrent

### ISSUE THREAD

**Issue by 53537** [Chocobozzz/PeerTube#2569]
**What happened?**

Error importing video via url and torrent
1、It is successful to import the short video through the url, but the long video will be disconnected after a period of time. The error message is "Command failed with exit code 1: /var/www/peertube/versions/peertube-v2.1.1/node_modules/youtube-dl/bin/youtube-dl --proxy  -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best -o /var/www/peertube/storage/tmp/d0f4e5fe72724dfexxxxxxxx43a005652637904b85057af92b12a931c63507a2-import.mp4 -- https://xxxxx.com/shipin/play-xxxx.html?road=1"

2、
Importing any torrent will be an error. Video not found

**What do you expect to happen instead?**

Hopefully both url and torrent imports will be successful

**Steps to reproduce:**

1.

2.

3.

**Additional information**
* PeerTube version or URL: 2.1.1
* Browser name/version: chrome
* NodeJS version: v12.16.1

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Try to run this command on the server to see what is the complete error message. You could also find it in PeerTube logs

**Comment by 53537** [comment]
This is an error message, but there is really only one video on this page：ERROR: fixed output name but more than one file to download

**Comment by Chocobozzz** [comment]
What is the video URL?

**Comment by McFlat** [comment]
In version 2.0.0 I was able to upload videos from the terminal with peertube upload and now in version 2.1.1 that functionality seems broken, it gets stuck and so not a single video gets imported. When I use any url to import with the other script it give me a promise rejection error.

```
import-videos 11rtyu_ https://youtu.be/PjSVApll1wA                                                                                                                                   
info: Will download and upload 1 videos.

(node:3861) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
(node:3861) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3861) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Chocobozzz** [comment]
On your server, what is the output of `/var/www/peertube/versions/peertube-v2.1.1/node_modules/youtube-dl/bin/youtube-dl https://youtu.be/PjSVApll1wA`?

**Comment by McFlat** [comment]
```
/var/www/peertube/versions/peertube-v2.1.1/node_modules/youtube-dl/bin/youtube-dl https://youtu.be/PjSVApll1wA
[youtube] PjSVApll1wA: Downloading webpage
[youtube] PjSVApll1wA: Downloading MPD manifest
[dashsegments] Total fragments: 7
[download] Destination: PlanDemic - Removing people from their homes-PjSVApll1wA.f136.mp4
[download] 100% of 6.61MiB in 00:17
[dashsegments] Total fragments: 5
[download] Destination: PlanDemic - Removing people from their homes-PjSVApll1wA.f140.m4a
[download] 100% of 477.02KiB in 00:03
[ffmpeg] Merging formats into "PlanDemic - Removing people from their homes-PjSVApll1wA.mp4"
Deleting original file PlanDemic - Removing people from their homes-PjSVApll1wA.f136.mp4 (pass -k to keep)
Deleting original file PlanDemic - Removing people from their homes-PjSVApll1wA.f140.m4a (pass -k to keep)
```

that command looks to be working fine and the video is downloaded

**Comment by Chocobozzz** [comment]
You issue is not the same than OP. You use the import CLI script instead of web interface.

Please create another issue so we can investigate.
