### ISSUE TITLE
How to add new custom module (payment system) on peertube instance?

### ISSUE THREAD

**Issue by sheshankdebugged** [Chocobozzz/PeerTube#2572]
I want to integrate stripe payments on mu peertube instance for storage to be used by user. What is the best way to start with?

**Comment by sheshankdebugged** [comment]
@Chocobozzz Please help in this

**Comment by DontUseGithub** [comment]
Currently I don't have time for this, but you could copy the text + image from here https://github.com/Chocobozzz/PeerTube/issues/2561#issue-583174263 and paste it into a new issue here https://framagit.org/framasoft/peertube/official-plugins/issues.

**Comment by Chocobozzz** [comment]
You could create users on your instance based on a payment. Since there is a [PeerTube API](https://docs.joinpeertube.org/#/api-rest-getting-started), you could automate the job. And based on the payment, you set the corresponding video quota.
