### ISSUE TITLE
Add new playbackState "Ended" to Embed-API

### ISSUE THREAD

**Issue by kantegory** [Chocobozzz/PeerTube#2574]
**What happened?**
It's just a suggestion.

We have now browser API for ended event: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/ended_event, but in PeerTube Embed-API we can handle just "playing", "paused" and "unstarted" playback states.

**What do you expect to happen instead?**
I think, it's can be useful in Embed-API, for example, for endless autoplay.

**Comment by Chocobozzz** [comment]
Added in https://github.com/Chocobozzz/PeerTube/commit/96aae68cc47b7ac9b9400d5b5cf95acdf9fe38da
