### ISSUE TITLE
Cannot switch to traditional Chinese with production build

### ISSUE THREAD

**Issue by nandiheath** [Chocobozzz/PeerTube#2575]
**What happened?**
after switching to traditional Chinese (zh-Hans-TW), it shows a blank page with js error
```
Cannot find module './angular.zh-Hant.xlf'
```

**What do you expect to happen instead?**
It should show the localized page without error

**Steps to reproduce:**

1. Build with `--light-zh-Hant`, and confirmed the `dist/zh-Hant-TW` folder exists

2. Navigate to homepage, select language, switch to Traditional Chinese

3. Blank page with errors

**Additional information**
- cookie locale: zh-Hant-TW
- on development mode + local machine it has no error, it should happen only on build
- Tried to replace all `zh-Hant-TW` within the whole project with `zh-Hant` it will work

* PeerTube version or URL: tvhk.nandiheath.com
* Browser name/version: chrome
* NodeJS version: 10-buster

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Thanks for the issue @nandiheath, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1fe654e0963da8c2801561be10de3222055a2497
