### ISSUE TITLE
Make the "can be redefined by the users" text to be a hyperlink and link to the settings option where the user can redefine that

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#2576]
Make the "can be redefined by the users" text (from the About page) to be a hyperlink and link to the settings option where the user can redefine that. We can make it just open the settings page or we can make it open the settings page and flash two times (with a somewhat bright color) the option in question. 

This issue concerns both the registered and unregistered users.

**Comment by sobhaniiest** [comment]
Hi, I would like to work on this issue. I'm new in Angular. What I've understood from the code, we need to invoke the method `openQuickSettings` of [menu.component.ts](https://github.com/Chocobozzz/PeerTube/blob/c492b05c48994828aa760d0b2b9c743e642048a6/client/src/app/menu/menu.component.ts#L179) from [shared-instance](https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/shared/shared-instance/instance-features-table.component.ts). To do this, we can use a new service. Can anyone please guide me to work on this issue? Thanks :)

**Comment by Chocobozzz** [comment]
* Create a `peertube-modal.service.ts` in `shared-main`
 * Add it to `shared-main` module (`shared-main.module.ts`)
 * In the service, create an rxjs `Subject` `openQuickSettingsSubject`
 * `menu.component.ts` subscribes to `openQuickSettingsSubject` and about page uses `.next` to send a message in this subject

**Comment by k09i71** [comment]
I think it'd be nice to first have this issue worked on https://github.com/Chocobozzz/PeerTube/issues/2930 and then this one, because it'll look weird when the 'settings page' will open but the url will stay the same - this may confuse the user, he won't be able to save the url for later use, send it to his friend, etc..
