### ISSUE TITLE
Transferring all data to another instance

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#2578]
I want to transfer all users, channels, videos, and everything else from one instance to another. Is this possible? Tell me how to do this correctly?

**Comment by rigelk** [comment]
It is not currently possible. The best you can do is to use the import feature to import videos one by one into another channel.

**Comment by Chocobozzz** [comment]
See https://github.com/Chocobozzz/PeerTube/issues/549 for an automatic migration feature
