### ISSUE TITLE
Broken video

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2579]
**What happened?**
I can't see this video: https://www.yiny.org/videos/watch/37de2f39-3fe3-472e-9cdc-837d3b6e6aa2
The quality selector is empty, and the video isn't playing. I can see any error in my browser console (I tested with firefox and chromium). I can't find any error log on the server side during the transcoding. 

Looking my storage folder, I can see videos files for resolution 0 and 208 (208??!!). Both HLS and non HLS. My server configuration is : resolutions 0, 480, 720, ....
Maybe it is because the original video resolution is underneath 480?

**Additional information**
* PeerTube version or URL: 2.1.1
* Browser name/version: Firefox and Chromium

**Comment by Chocobozzz** [comment]
Could you send me the original file please?

**Comment by JohnXLivingston** [comment]
It is not my file, so I haven't. But you can download the video and try with this one (the download button works). There is the same bug. 
I just noticed that it creates multiple transcode jobs, that finished almost instantly. Just after submitting the video, it worked. But 2 seconds later, when refreshing the page it is broken.
Here is a screenshot from the transcode jobs:
![image](https://user-images.githubusercontent.com/38844060/77823619-c953c000-70fc-11ea-90cc-fee1af4aaa0c.png)

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/a2b6ec7c3f6176ac7028b1f23899ebec3217c8cd

**Comment by JohnXLivingston** [comment]
Thanks. Once peertube is up to date, have I to launch a script to fix?

**Comment by Chocobozzz** [comment]
You'll have to reupload your video

**Comment by JohnXLivingston** [comment]
create-transcoding-job.js is not enought?

**Comment by JohnXLivingston** [comment]
Or create-import-video-file-job.js?
