### ISSUE TITLE
Text legibility using dark mode

### ISSUE THREAD

**Issue by muesli** [Chocobozzz/PeerTube#2580]
**What happened?**

I'm using the default dark theme on peertube.social and noticed that when liking/upvoting a video, the thumbs-up icon and text color changes from gray to black, making it pretty hard to read. See attached screenshot.

**What do you expect to happen instead?**

Keep the icon and text color the same as before clicking "like".

**Steps to reproduce:**

1. Use dark mode

2. Like a video

![image](https://user-images.githubusercontent.com/146378/77812738-a34e0180-70a3-11ea-836b-40d100bb6094.png)

**Comment by Booteille** [comment]
Concerning this issue. Can themes use scss variables or only pure css right now?

**Comment by Chocobozzz** [comment]
They can use whatever they want

**Comment by Booteille** [comment]
> They can use whatever they want

Okay. So how could I override the `$activated-action-button-color` variable?
It's located [in this file](https://framagit.org/framasoft/peertube/PeerTube/-/blob/develop/client/src/sass/include/_variables.scss).

Sorry if this is obvious, I didn't find the answer in docs.

**Comment by rigelk** [comment]
You cannot. SCSS is used at compile time and when the them is loaded at runtime, this variables doesn't exist anymore.

**Comment by Booteille** [comment]
> You cannot. SCSS for PeerTube core is used at compile time and when the them is loaded at runtime, this variables doesn't exist anymore.
> 
> What is meant by "you can use anything" is that you are free to choose your tools to generate your own css.

Okay, my bad then! Thank you for your answers.

So, since the issue is bound to the fact icons are SVG and the color is compiled by the server (and black by default), to solve it we would need to either implement scss in the dark theme to use the mixin or maybe to use a static white SVG?

**Comment by Chocobozzz** [comment]
I think we should only use CSS variables in PeerTube so themes can easily override default colors.

At this time, you don't need to implement scss in the dark theme. Just use a particular selector for this SVG icon and change it. But I don't think it's the right way to fix the issue.

**Comment by Booteille** [comment]
> I think we should only use CSS variables in PeerTube so themes can easily override default colors.

I think every aspect of the default theme should be easily override by themes so yup, probably you're right.

> At this time, you don't need to implement scss in the dark theme. Just use a particular selector for this SVG icon and change it. But I don't think it's the right way to fix the issue.

I don't think neither. I won't try to fix it now.

**Comment by Chocobozzz** [comment]
Has been fixed some time ago

**Comment by muesli** [comment]
Still broken for me on peertube.social. Which version was this fixed in?

**Comment by Chocobozzz** [comment]
I don't remember, but in 2.4 it seems fixed 
![screen_2020-08-29-08:22:03](https://user-images.githubusercontent.com/5180488/91630348-e4d73580-e9d0-11ea-8e7c-737920e04118.png)
