### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2582]
On the following line:
https://github.com/Chocobozzz/PeerTube/blob/76314386aeafdd6849b7b70c517779d6b2013473/server/models/account/user.ts#L236
Should it not be 'UserName' instead of 'UserPassword'?

**Comment by Chocobozzz** [comment]
Yes you're right!

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/51892fe0429e237bff956143630b295aa358f811
