### ISSUE TITLE
Updating the list of servers

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#2583]
Here is a page that has a list of servers https://joinpeertube.org/instances#instances-list
I have 2 servers that have been running for about a month, but they don't appear in the list. Why is that? How often does the list update?

https://video.ustim.ru
https://peervideo.ru

**Comment by JohnXLivingston** [comment]
You have to register your servers here: https://instances.joinpeertube.org/instances/add

**Comment by Alterak** [comment]
Thanks. I assumed that all instances are scanned and added automatically. In any case, thank you. I already added my own instance.
