### ISSUE TITLE
Federate videos of select languages for displaying content

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#2584]
If I go to the youtube site in my own country, by default I only see all the videos in my native language, probably because my IP address is like this - it's good. But if I link my instance to other instances from other countries, then my instance displays all other people's videos in other languages. I really want to associate my instance with your instances, but I want only videos in my language to be displayed. Is this possible? What would it be like on youtube.

**Comment by WonderingDane** [comment]
This would be a good default setting. Then users can choose to change the filter if they so wish.

**Comment by Chocobozzz** [comment]
Closing in favour of https://github.com/Chocobozzz/PeerTube/issues/2642
