### ISSUE TITLE
Playback duration in API embeds 

### ISSUE THREAD

**Issue by freeboub** [Chocobozzz/PeerTube#2585]
**What happened?**

I am trying to implement a peertube library for easy integration of peertube video in android apps:
I am referring to PeerTube/support/doc/api/embeds.md  Documentation
I think there are 2 missing apis to be able to full fill integration:
* Playback duration
* On PlayerEnd event (same than : #762 but it is closed :/ )

**What do you expect to happen instead?**
I am expecting : 
 - a field in playbackStatusUpdate named "duration" to be able to display video length
- an event "ended" sent by playbackStatusUpdate

**Additional information**
* PeerTube version or URL: any
* Browser name/version: any 
* NodeJS version: any

**Comment by Chocobozzz** [comment]
For `PlayerEnd` event see https://github.com/Chocobozzz/PeerTube/issues/2574

**Comment by Chocobozzz** [comment]
`duration` implemented in https://github.com/Chocobozzz/PeerTube/commit/6ccdf9d53e4d68bcdf49bb7098c382d059988c4e
