### ISSUE TITLE
Peertube vs Microsoft Edge

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2586]
**What happened?**
A user of my instance reported me that he can't watch videos. He uses Microsoft Edge (I guess so, because he told me he has windows 10). So I downloaded the Microsoft Edge VM to try myself.

On a HLS video, I have the following error:
![image](https://user-images.githubusercontent.com/38844060/77853639-55411700-71e5-11ea-84d6-00a224f612ec.png)
The video: https://www.yiny.org/videos/watch/792b944a-61bf-400a-a225-52f04ffe63ba

And on a non HLS video:
![image](https://user-images.githubusercontent.com/38844060/77853665-a18c5700-71e5-11ea-8c30-5bad3305226f.png)
The video: https://www.yiny.org/videos/watch/cad71cbc-b4cb-4e86-9ce7-6309c87bfa31

Virtual machines are available here: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
Note that the keyboard is in qwerty (for the password...).

**Additional information**
* PeerTube version or URL: 2.1.1
* Browser name/version: Edge

**Comment by Chocobozzz** [comment]
What is the Edge browser version?

**Comment by JohnXLivingston** [comment]
In my VM: 
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763
I downloaded the VM yesterday.

**Comment by Chocobozzz** [comment]
This version is outdated. Latest is 81.

**Comment by JohnXLivingston** [comment]
I just updated my VM with windows update. Same bug.
The version is now: 
Microsoft Edge 44.17763.831.0
Microsoft EdgeHTML 18.17763

If there is a more recent version, I have no idea how to update. I am not a windows user.

**Comment by JohnXLivingston** [comment]
I will try to download edge and install it manually...

**Comment by JohnXLivingston** [comment]
Hum ok. With version 80 it is ok. But I don't understand what microsoft did... Users have to manually download the new edge version? (the version based on chromium)
If so, that's meen there are still a lot of users with the old version, no?

**Comment by tcitworld** [comment]
The new Edge based on Chromium should be bundled into regular Windows updates in the following months.
