### ISSUE TITLE
peertube service not starting / stack":  \"public.Pods\" does not exist\

### ISSUE THREAD

**Issue by luc310** [Chocobozzz/PeerTube#2587]
Hello,
I've installed peertube on centos7, and got the error message when I start the service peertube : 

peertube[904]: "stack": "SequelizeDatabaseError: relation \"public.Pods\" does not exist\n    at Query.formatError (/var/www/peertube/versions/peertube-v2.1.1/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)\n    at query.catch.err (/var/www/peertube/versions/peertube-v2.1.1/node_modules/sequelize/lib/dialects/postgres/query.js:72:18)\n    at tryCatcher (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/promise.js:725:18)\n    at _drainQueueStep (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-v2.1.1/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)",

peertube-v2.1.1
nodejs-10.19.0-1
npm 6.13.4
yarn 1.22.4

Thank you for your help

**Comment by rigelk** [comment]
@luc310 what is your version of postgresql ?

**Comment by luc310** [comment]
@rigelk this is postgresql-server-9.2.24-2.

**Comment by rigelk** [comment]
@luc310 please double check the requirements. PeerTube needs version 9.6 or later of postgresql.

**Comment by febeling** [comment]
I saw this exact problem when there was a file permission error on the first startup. In that case subsequent starts would fail on the migration 0005 as well. 

```
Jan 20 13:51:14 prototube peertube[73259]: > peertube@3.0.1 start /var/www/peertube/versions/peertube-v3.0.1
Jan 20 13:51:14 prototube peertube[73259]: > node dist/server
Jan 20 13:51:25 prototube peertube[73283]: [tube.footech.io:443] 2021-01-20 13:51:25.556 info: Database peertube_prod is ready.
Jan 20 13:51:25 prototube peertube[73283]: [tube.footech.io:443] 2021-01-20 13:51:25.590 error: Cannot install application. {
Jan 20 13:51:25 prototube peertube[73283]:   "err": {
Jan 20 13:51:25 prototube peertube[73283]:     "stack": "Error: EACCES: permission denied, unlink '/rclonevol/storage/cache/previews'",
Jan 20 13:51:25 prototube peertube[73283]:     "message": "EACCES: permission denied, unlink '/rclonevol/storage/cache/previews'",
Jan 20 13:51:25 prototube peertube[73283]:     "errno": -13,
Jan 20 13:51:25 prototube peertube[73283]:     "code": "EACCES",
Jan 20 13:51:25 prototube peertube[73283]:     "syscall": "unlink",
Jan 20 13:51:25 prototube peertube[73283]:     "path": "/rclonevol/storage/cache/previews"
Jan 20 13:51:25 prototube peertube[73283]:   }
Jan 20 13:51:25 prototube peertube[73283]: }
Jan 20 13:51:25 prototube peertube[73259]: npm ERR! code ELIFECYCLE
Jan 20 13:51:25 prototube peertube[73259]: npm ERR! errno 255
Jan 20 13:51:25 prototube peertube[73259]: npm ERR! peertube@3.0.1 start: `node dist/server`
Jan 20 13:51:25 prototube peertube[73259]: npm ERR! Exit status 255
Jan 20 13:51:25 prototube peertube[73259]: npm ERR!
Jan 20 13:51:25 prototube peertube[73259]: npm ERR! Failed at the peertube@3.0.1 start script.
```
