### ISSUE TITLE
Proper hook to use videojs-vr as player for our peertube instance

### ISSUE THREAD

**Issue by OceanTechie** [Chocobozzz/PeerTube#2589]
To replace the default video player with videojs - and specfically, videojs-vr plugin for videojs - i've installed both on my ubuntu 18.4 aws ec2 instance.

To develop a plugin to do this, would the appropriate hook to use be:

action:video-watch.init

where we'd insert javascript code to invoke the videojs player - per below HTML example

I'm thinking the init event is the thing needed rather than  action:video-watch.video.loaded as the player would be loaded already when that event fires.

I want to do the equivalent of this HTML page script injection in the DIV tag for the watch page

		<script src="/home/ubuntu/node_modules/video.js/dist/video.js"></script>
		<script src="/home/ubuntu/node_modules/videojs-vr/dist/videojs-vr.js"></script>
		<script>
			(function(window, videojs) {
				window.vr_rect2 = videojs('videojs-vr-player-rect2').vr({projection: '360_TB', debug: true, forceCardboard: false});
			}(window, window.videojs));
		</script>

**Comment by OceanTechie** [comment]
BTW - is it even possible to modify peertube page UI elements - say, to add a choice for some custom category of membership we define on the account create "page"?   I'm not finding any plugin examples doing this and although I've downloaded the CLI tool client source code and see the HTML pages source code I can modify - i don't see any means to make changes be part of my peertube instance - it seems plugins are the way to go.  It would help to clarify for us on viability and any examples we can reference.

**Comment by Chocobozzz** [comment]
Hello,

You can take example on the [annotation plugin](https://framagit.org/framasoft/peertube/official-plugins/-/tree/master/peertube-plugin-video-annotation) to see how to add a videojs plugin to the player. You need to use the `action:video-watch.player.loaded` hook
