### ISSUE TITLE
When try to upload video: Unknown Error

### ISSUE THREAD

**Issue by pokapow** [Chocobozzz/PeerTube#259]
* **PeerTube version or commit:** 
peertube-v0.0.15-alpha
* **Browser name/version:**
Chrome Version 63.0.3239.84 + Firefox 57
* **NodeJS version:**
v8.9.4

* **What is the expected behaviour?**
Load a Video
* **What do you see instead?**
"Unknown Error"

* **Browser console log if useful (Gist/Pastebin...):
https://paste.ofcode.org/C8SQRHAUnWb7aqcLNB3UB4**
* **Server log if useful (Gist/Pastebin...):**
Nothing apparead in logfiles ...

In a fresh install, debian 9, I can't upload a video (tried several .mp4 of several size).
It's trying to upload, charge to 94%, sometimes 80% ... then:
I got this error:
https://ibb.co/maEYrw
https://ibb.co/ndWrdb

Nothing in log about it.

**Comment by ReK2Fernandez** [comment]
did you check on nginx config the max upload size? try to increment that,

**Comment by pokapow** [comment]
In fact that was the problem ... max upload size was ok in the nginx of the peertube VM, but not ok in the master nginx reverse proxy ... So issue is resolved.
