### ISSUE TITLE
Error importing video after disk enlargement

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#2591]
I have a disk mounted in the folder /var/www/peertube/storage/ it was Originally 100GB in size. I decided to increase the disk size to 300GB. After that, the ability to import videos from youtube disappeared and the torrent download stopped working. Errors are returned. But downloading local videos works fine. Rights to the folder /var/www/peertube/storage/ peertube:peertube 775. I showed you more details in the video. Why did this happen and how can I fix it?

https://peervideo.ru/videos/watch/4b70aeb9-1163-4dfb-b7de-9bbf6431e95c

**Here is the result of the log file at the time of import**
> {"message":"192.168.1.5 - - [01/Apr/2020:08:33:20 +0000] \"GET /tracker/socket HTTP/1.1\" 200 3624 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0\"\n","level":"info","label":"peervideo.ru:443","timestamp":"2020-04-01T08:33:20.342Z"}
> {"level":"info","message":"Cannot fetch information from import for URL https://youtu.be/zlDtPTwNm8Q.","label":"peervideo.ru:443","err":{"stack":"Error: Command failed with exit code 1: /var/www/peertube/versions/peertube-v2.1.1/node_modules/youtube-dl/bin/youtube-dl -i --dump-json -f best -j --flat-playlist https://youtu.be/zlDtPTwNm8Q\n    at makeError (/var/www/peertube/versions/peertube-v2.1.1/node_modules/youtube-dl/node_modules/execa/lib/error.js:56:11)\n    at handlePromise (/var/www/peertube/versions/peertube-v2.1.1/node_modules/youtube-dl/node_modules/execa/index.js:114:26)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","message":"Command failed with exit code 1: /var/www/peertube/versions/peertube-v2.1.1/node_modules/youtube-dl/bin/youtube-dl -i --dump-json -f best -j --flat-playlist https://youtu.be/zlDtPTwNm8Q","command":"/var/www/peertube/versions/peertube-v2.1.1/node_modules/youtube-dl/bin/youtube-dl -i --dump-json -f best -j --flat-playlist https://youtu.be/zlDtPTwNm8Q","exitCode":1,"stdout":"","stderr":"  File \"/var/www/peertube/versions/peertube-v2.1.1/node_modules/youtube-dl/bin/youtube-dl\", line 2\nSyntaxError: Non-ASCII character '\\x97' in file /var/www/peertube/versions/peertube-v2.1.1/node_modules/youtube-dl/bin/youtube-dl on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details","failed":true,"timedOut":false,"isCanceled":false,"killed":false},"timestamp":"2020-04-01T08:33:34.471Z"}

**Comment by Chocobozzz** [comment]
Please login on your server and run the youtube-dl command to see if it's a youtube-dl bug or a peertube bug

**Comment by Alterak** [comment]
> Please login on your server and run the youtube-dl command to see if it's a youtube-dl bug or a peertube bug

```
peertube@peervideo:~$ youtube-dl https://www.youtube.com/watch?v=Hhl4XP8MxIA
-bash: youtube-dl: команда не найдена
peertube@peervideo:~$ sudo youtube-dl https://www.youtube.com/watch?v=Hhl4XP8MxIA
[sudo] пароль для peertube:
sudo: youtube-dl: command not found
peertube@peervideo:~$
```

**Comment by Findus23** [comment]
@Alterak you have to use the complete path to your youtube-dl as in the error message (`/var/www/peertube/versions/peertube-v2.1.1/node_modules/youtube-dl/bin/youtube-dl`)

**Comment by Alterak** [comment]
At the moment, everything is restored. I tried to restore the backup from the 31st and from the 2nd of the day. On the 31st, the import worked fine, but on the 2nd of the 2nd, after increasing the disk, everything stopped working. I recorded the video in detail.
Earlier and now if you run youtube-dl, then an error appears
```
peertube@peervideo:~$ sudo youtube-dl https://www.youtube.com/watch?v=wcEe5P9QVoc
[sudo] пароль для peertube:
sudo: youtube-dl: command not found
```
He also recorded a video of all the details.
https://peervideo.ru/videos/watch/26764ee2-8e8f-4c8a-8ee3-a8749c922744

Later I saw your message about the full path and ran it on the current instance with an error. Result:
```
peertube@peervideo:~$ /var/www/peertube/versions/peertube-v2.1.1/node_modules/youtube-dl/bin/youtube-dl https://www.youtube.com/watch?v=wcEe5P9QVoc
  File "/var/www/peertube/versions/peertube-v2.1.1/node_modules/youtube-dl/bin/youtube-dl", line 2
SyntaxError: Non-ASCII character '\x97' in file /var/www/peertube/versions/peertube-v2.1.1/node_modules/youtube-dl/bin/youtube-dl on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
peertube@peervideo:~$
```

**Comment by Chocobozzz** [comment]
Drop and reinstall node_modules and retry the youtube-dl command please. Maybe it's a corrupted `youtube-dl` issue. If it does not fix your issue, what is the output of `sudo -u peertube /usr/bin/env python --version`?

**Comment by Alterak** [comment]
> Drop and reinstall node_modules and retry the youtube-dl command please. Maybe it's a corrupted `youtube-dl` issue. If it does not fix your issue, what is the output of `sudo -u peertube /usr/bin/env python --version`?

```
peertube@peervideo:~$ sudo -u peertube /usr/bin/env python --version
Python 2.7.16
peertube@peervideo:~$
```
The problem is resolved.
I downloaded the ** youtube-dl ** file here https://github.com/ytdl-org/youtube-dl/releases/download/2020.03.24/youtube-dl
and replaced it in the /var/www/peertube/versions/peertube-v2.1.1/node_modules/youtube-dl/bin folder
And everything began to work fine. Why the failure occurred precisely after expanding the storage disk I do not know. Many thanks to all for your advice and your help.

Now there is a problem with torrent files.

> This torrent file is not supported or too large. Please, make sure it is of the following type: .torrent

How can this problem be solved?

**Comment by Chocobozzz** [comment]
Please create another issue and fill the template with server logs, client request and torrent file.
