### ISSUE TITLE
fail to import from soundcloud

### ISSUE THREAD

**Issue by Midek** [Chocobozzz/PeerTube#2593]
**What happened?**
When trying to import (URL import) a song from soundcloud i am getting:
>Sorry, but something went wrong
>Video not found
Error.

In peertube logs i have found this:
```
Apr 02 09:06:12 peertube peertube[24785]: [tube.midov.pl:443] 2020-04-02 09:06:12.631 error: Cannot execute job 539 in queue video-import. {
Apr 02 09:06:12 peertube peertube[24785]:   "payload": {
Apr 02 09:06:12 peertube peertube[24785]:     "type": "youtube-dl",
Apr 02 09:06:12 peertube peertube[24785]:     "videoImportId": 660,
Apr 02 09:06:12 peertube peertube[24785]:     "thumbnailUrl": "https://i1.sndcdn.com/artworks-000656841949-l7hxh5-original.jpg",
Apr 02 09:06:12 peertube peertube[24785]:     "downloadThumbnail": true,
Apr 02 09:06:12 peertube peertube[24785]:     "downloadPreview": true
Apr 02 09:06:12 peertube peertube[24785]:   },
Apr 02 09:06:12 peertube peertube[24785]:   "err": {
Apr 02 09:06:12 peertube peertube[24785]:     "stack": "Error: Input buffer contains unsupported image format",
Apr 02 09:06:12 peertube peertube[24785]:     "message": "Input buffer contains unsupported image format"
Apr 02 09:06:12 peertube peertube[24785]:   }
Apr 02 09:06:12 peertube peertube[24785]: }
```
When downloading it with youtube-dl manualy, it pulls the file properly.

**What do you expect to happen instead?**
Song gets imported to peertube
or
ability to disable downloading of thumbnails/previews
**Steps to reproduce:**

1. Go to Import with URL in peertube

2. set url to https://soundcloud.com/vdj-vdj-gekko-gekko/gekko-yoswu-remix
3. press import

**Additional information**
* PeerTube version or URL: https://tube.midov.pl/about/instance version 	2.1.1
* Browser name/version: Chromium Version 80.0.3987.149 (Official Build) Arch Linux (64-bit)
* NodeJS version: node -v `v10.19.0`

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
https://cloud.midov.pl/s/gTz8rAEaktaSP6q

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/d57d1d83c6a4d98a735b21f4e8e749a5c1e1a479
