### ISSUE TITLE
Suggesting a new default behaviour

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2595]
Since the option of hiding viewcounts is already available https://github.com/Chocobozzz/PeerTube/issues/1302, I'd like to suggest it as a new default for PeerTube, at least until PeerTube gets to be more popular.
I'm suggesting that we hide the views counts from all pages except for video pages (the page where we watch the video).

**Comment by Chocobozzz** [comment]
You can easily update CSS to hide what your want on PeerTube, or make a merge request on the [ungamify plugin](https://framagit.org/rigelk/peertube-plugin-ungamify)
