### ISSUE TITLE
Add Content Warning on Mastodon (and others)

### ISSUE THREAD

**Issue by raphgilles** [Chocobozzz/PeerTube#2597]
Hello !

When the case "This video contains mature or explicit content" it's not add a CW or not mention the media as sensitive on the other tools of the Fediverse. And it should be to keep the Fediverse a safe place for everyone :)

That's all !

**Comment by Chocobozzz** [comment]
Hello,

We correctly send the `sensitive` AP attribute, and Mastodon inserts it in its database. But you can't really see it on Mastodon since AFAIK sensitive attribute acts only on medias

**Comment by raphgilles** [comment]
Ok, thank you for your answer.

So, for people who wants to follow the issue :
https://github.com/tootsuite/mastodon/issues/13435
