### ISSUE TITLE
progress control not enough visible

### ISSUE THREAD

**Issue by ClementEstievenart** [Chocobozzz/PeerTube#2598]
I find that the progress controller of the video player is not visible enough when the background of the video is white. You can't quickly see what you've watched and what remains to be seen.

Screenshot :
![Screenshot_2020-04-04 What is PeerTube ](https://user-images.githubusercontent.com/23419042/78434990-ba718e00-7665-11ea-8df2-0ca10222eb83.png)
link : [https://joinpeertube.org/#what-is-peertube](https://joinpeertube.org/#what-is-peertube)

**Comment by Chocobozzz** [comment]
I think it's fine: you can still see the progress bar and we can't really do anything here. If we choose another color, we'll have the same problem with another video. You could also change the progress bar color using the instance admin interface or a theme or a plugin.
