### ISSUE TITLE
Yunohost peertube 2.1.1 "Cannot load more videos. Try again later."

### ISSUE THREAD

**Issue by plslvval** [Chocobozzz/PeerTube#2599]
**What happened?**

I upgraded peertube 2.1.0 on yunohost working instance to 2.1.1.
Within Linux Firefox 74.0 no video can been seen, thumbnails appears only for "discover' and any other option shows red notification
'Erreur

Cannot load more videos. Try again later.'

**What do you expect to happen instead?**

This is working on chromium browser, so i expect it does the same on firefox like it was before upgrade.

**Steps to reproduce:**

Connect to https://peertube.serveur.slv-valbonne.fr/videos/local

server traces shows authentication header errors only when used with firefox :

avril 04 14:10:48 serveur.slv-valbonne.fr peertube[20404]: [peertube.serveur.slv-valbonne.fr:443] 2020-04-04 14:10:48.594 warn: Cannot authenticate. {
avril 04 14:10:48 serveur.slv-valbonne.fr peertube[20404]:   "err": {
avril 04 14:10:48 serveur.slv-valbonne.fr peertube[20404]:     "statusCode": 400,
avril 04 14:10:48 serveur.slv-valbonne.fr peertube[20404]:     "status": 400,
avril 04 14:10:48 serveur.slv-valbonne.fr peertube[20404]:     "code": 400,
avril 04 14:10:48 serveur.slv-valbonne.fr peertube[20404]:     "message": "Invalid request: malformed authorization header",
avril 04 14:10:48 serveur.slv-valbonne.fr peertube[20404]:     "name": "invalid_request",
avril 04 14:10:48 serveur.slv-valbonne.fr peertube[20404]:     "stack": "invalid_request: Invalid request: malformed authorization header\n    at new InvalidRequest (/var/www/peertube/node_modules/oauth2-server/lib/errors/invalid-request-error.js:26:14)\n    at AuthenticateHandler.getTokenFromRequestHeader (/var/www/peertube/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:146:11)\n    at AuthenticateHandler.getTokenFromRequest (/var/www/peertube/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:121:17)\n    at AuthenticateHandler.<anonymous> (/var/www/peertube/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:68:19)\n    at AuthenticateHandler.tryCatcher (/var/www/peertube/node_modules/oauth2-server/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/var/www/peertube/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromiseCtx (/var/www/peertube/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:606:10)\n    at Async._drainQueue (/var/www/peertube/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:138:12)\n    at Async._drainQueues (/var/www/peertube/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)"
avril 04 14:10:48 serveur.slv-valbonne.fr peertube[20404]:   }
avril 04 14:10:48 serveur.slv-valbonne.fr peertube[20404]: }

**Comment by plslvval** [comment]
This really seems browser version dependent, this is working under Firefox 60.5.0esr Linux version.

**Comment by plslvval** [comment]
This is a yunohost issue, i get this problem only if logged in yunohost system.

**Comment by plslvval** [comment]
filled a yunohost issue https://github.com/YunoHost-Apps/peertube_ynh/issues/161

**Comment by plslvval** [comment]
this is not browser dependent, problem occur when logged on yunohost instance only whetever the browser is.

**Comment by rigelk** [comment]
Closing since this should be debugged first within the yunohost community to better triage the problem.
