### ISSUE TITLE
Configuring the docker container with env vars

### ISSUE THREAD

**Issue by faddat** [Chocobozzz/PeerTube#26]
What's the right way to do this?  Here's the command I used:

```
docker service create --name bbvideo5 --label traefik.port=9000 -e HOST=video.beyondbitcoin.io -e PORT=80 --label traefik.frontend.rule=Host:video.beyondbitcoin.io --network traefik-net faddat/peertube
```

I know that this looks strange, I tried it with traefik.port=80 (which would set the port that my reverse proxy listens to the container on to 80, and I get nothing other than an error that it cannot reachthe backend.  Most likely, I'm doing something simple wrong.  

I'm of course getting:

![image](https://cloud.githubusercontent.com/assets/7142025/21047117/b63f1942-be3a-11e6-9689-5c924d5e50a8.png)

... image doesn't seem to work atm-- it's the "check the webserver section of the config file error.  

If I want to use env vars, do I need to take the values out of the /config folder?  It does look like it is set up to read them, but it does not seem to be reading them.  Peertube is fantastic!

**Comment by faddat** [comment]
![image](https://cloud.githubusercontent.com/assets/7142025/21047798/8cea1138-be3e-11e6-8b71-3adc68836897.png)

**Comment by faddat** [comment]
the remote address is the address of my reverse proxy.  Maybe I can find a traefik configuration setting that will modify the headers?  Is that the right thing to do?

**Comment by Chocobozzz** [comment]
I don't know traefik but if you want to configure PeerTube throught ENV variables you can set the `NODE_CONFIG` env that will override file configurations.

Example:

`$ NODE_CONFIG='{ "listen": { "port": 9001 } }' node server`

See https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_config for more informations.

**Comment by faddat** [comment]
That is just perfect man.   With my swarm setup and this information,  we
can now test hundreds of nodes.
