### ISSUE TITLE
Paging is broken in the search view

### ISSUE THREAD

**Issue by kaiyou** [Chocobozzz/PeerTube#260]
* **PeerTube version or commit:** Docker image from tedomum/peertube:stretch, based on current develop
* **Browser name/version:** Firefox 57, Chrome 63
* **NodeJS version:** 8
* **PostgreSQL version:** 10.1
* **Server:** https://video.tedomum.net

* **What is the expected behaviour?**

When scrolling from the search results page, next results should be displayed. For instance, searching for "34c3" returns enough results for paging.

* **What do you see instead?**

The page is cleared with the message "No result".

* **Server log if useful (Gist/Pastebin...):**

The browser seems to request:

```/api/v1/videos/search?start=0&count=25&sort=-createdAt&search=undefined```

Also, the fragment is changed to:

```https://video.domain.tld/videos/search;sort=-createdAt;page=1```

**Comment by Chocobozzz** [comment]
Should be fixed in the next release: https://github.com/Chocobozzz/PeerTube/commit/c88593f72f1097cc34a091b4cb4b6d6e214d1e9f
