### ISSUE TITLE
Peertube Cache in federation

### ISSUE THREAD

**Issue by Musadiqraees** [Chocobozzz/PeerTube#2600]
suppose Peertube2 follows peertube1 which have video A
How Cache will work?
For example Peertube2 will have local copy of video A or it will always get video from parent peertube1.

**Comment by rigelk** [comment]
If instance 2 enables redundancy and has a copy of that video, then visitors on either instances will be aware of the two webseeds and download from both.

**Comment by Musadiqraees** [comment]
If redundancy option is not selected then it will fetch from peertube1 everytime user watch video on peertube2 right ?

**Comment by rigelk** [comment]
@Musadiqraees or from other peers if P2P is enabled on 1 and enabled by the users.

**Comment by Musadiqraees** [comment]
I am using this docker image "chocobozzz/peertube:production-stretch". I have redundancy enabled but when peertube2 is following peertube 1 (has videos).     "https://peertube2.cit.local/api/v1/server/stats" this shows empty redundancy videos

{
"totalLocalVideos": 0,
"totalLocalVideoViews": 0,
"totalLocalVideoFilesSize": 0,
"totalLocalVideoComments": 0,
"totalVideos": 3,
"totalVideoComments": 0,
"totalUsers": 1,
"totalInstanceFollowers": 0,
"totalInstanceFollowing": 1,
"videosRedundancy": []
}

**Comment by rigelk** [comment]
@Musadiqraees what is your configuration for redundancy?

**Comment by Musadiqraees** [comment]
I am using docker, I don't know where I can specify my configuration for redundancy. can you please guide me

**Comment by Musadiqraees** [comment]
I have added it in production.yml but its have any effect

redundancy:
  videos:
    check_interval: '10 Minutes' 
    strategies:  
      -
        size: '10GB'
        min_lifetime: '48 hours'
        strategy: 'trending'

**Comment by Chocobozzz** [comment]
Did you restart the container after the `production.yaml` update?

**Comment by LecygneNoir** [comment]
Hello @Musadiqraees 

In addition to Chocobozz question, may I ask if you have enable redundancy in production.yml AND checked the option in the backend to allow Peertube2 to get video?

When connected in root in the web interface, you should see the follower, and being able to check "allow redundancy". I guess (docker or not) that if Peertube1 does not allow peertube2 to get videos, it'll not work even if configuration seems Ok.

Also, from the docker part, have you specified a directory in production.yml to store redundant videos, that is a docker volume? It's possible docker refuses to get such big file on its own docker fs depending of your docker configuration, so using an external volume may help.

Regards,

**Comment by Musadiqraees** [comment]
Dear @LecygneNoir, Can you guide me about this "checked the option in the backend to allow Peertube2 to get video " . how and where i can see this configuration kindly please explain

**Comment by rigelk** [comment]
This should be in your `admin/follows/following-list`, where you should make sure to enable redundancy for peertube1.

**Comment by Musadiqraees** [comment]
file are added locally but webseed links are not generated. I am assuming when redundancy is on both instance have seperate link for videos. so i can download same video from any of them?


ubuntu@peertube1:/peertube/docker-volume/data/videos$ ls
7b5dd07e-45cf-4c56-ba0b-1d20ccb2c37a-360.mp4  a628a0b0-4176-4803-a443-724708858833-144.mp4
7f4fb9ba-35aa-4bcb-a9cb-47e45d2760f7-288.mp4

ubuntu@peertube2:/peertube/docker-volume/data/redundancy$ ls
7b5dd07e-45cf-4c56-ba0b-1d20ccb2c37a-360.mp4  a628a0b0-4176-4803-a443-724708858833-144.mp4
7f4fb9ba-35aa-4bcb-a9cb-47e45d2760f7-288.mp4

**Comment by Musadiqraees** [comment]
I want to clear, if redundancy works then 
Supppose peertube2 follows peertube1 and if peertube1 has video "A".

Can i fetch video A with some client from peertube2 without interacting with real peertube1.
Can somebody please explain me if possible 
Bundle of thanks

**Comment by Musadiqraees** [comment]
Dear team, Videos are in redundancy folder but webseed are not generated. @rigelk @LecygneNoir. I am assuming that there will be two different webseed link for same video for respective instances.

ubuntu@peertube2:/peertube/docker-volume/data/redundancy$ ls
7f4fb9ba-35aa-4bcb-a9cb-47e45d2760f7-288.mp4  a628a0b0-4176-4803-a443-724708858833-144.mp4
a0551427-a53e-4e92-a761-e44f5fd695c5-360.mp4


ubuntu@peertube1:/peertube/docker-volume/data/videos$ ls
7f4fb9ba-35aa-4bcb-a9cb-47e45d2760f7-288.mp4  a628a0b0-4176-4803-a443-724708858833-144.mp4
a0551427-a53e-4e92-a761-e44f5fd695c5-360.mp4

**Comment by LecygneNoir** [comment]
Hello

While I guess you have found the option if the video is in your redundancy directory, here is a screenshot to find it :)

![Capture d’écran de 2020-04-06 08-30-29](https://user-images.githubusercontent.com/7755000/78529023-04cb4a00-77e1-11ea-9a0c-e4d17cac98f6.png)

Regarding the webseed problem, I am sorry I do not know how it works exactly, but I think the torrent should use Peertube1 as source and Peertube2 as a secondary source to share badnwidth, much the same than when a viewer look at a video.

In this case, I am not sure it will work without Peertube1 available, nor than a specific torrent should be generated for Peertube2 :thinking: 

@rigelk do you know more about this point?

Thanks!

**Comment by Musadiqraees** [comment]
Actually i am looking for second webseed link. Shouldn't we have two web seed static links . So  u can accesss it from peertube2 api

**Comment by Chocobozzz** [comment]
Redundancy works correctly since you have `ws=https%3A%2F%2Fpeertube2.cit.local%2Fstatic%2Fwebseed%2F7f4fb9ba-35aa-4bcb-a9cb-47e45d2760f7-288.mp4` in your magnet URI.
