### ISSUE TITLE
Playlist shows videos that are scheduled for later

### ISSUE THREAD

**Issue by Rinma** [Chocobozzz/PeerTube#2601]
**What happened?**
I created a playlist with videos from my channel. (Except for that creating a playlist and adding more than one video feels horrible, maybe an "add to playlist" option when I select multiple videos in the videos list). I added videos I scheduled to be published in a few days.

**What do you expect to happen instead?**
Scheduled videos should appear in the playlist after they are published.

**Steps to reproduce:**

1. Publish a video and scheduled it for in a day or so

2. Create a Playlist and add the video

3. Look at the playlist

**Additional information**
* PeerTube version ~or URL~: 2.1.1
* Browser name/version: Firefox 74.0.1
* NodeJS version: 10.19.0

* ~Link to browser console log if useful:~
* ~Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):~

**Comment by Rinma** [comment]
This is not a bug, more a enhancement. 
I forgot to mention that the videos are listed as "Privat" so they are not playable. 
But now I have a public playlist, to group the videos of my channel, full of privat videos which is not nice.
So it would be better if they are not listed at all for the moment or if they are listed with the time when they get published and a blurred thumbnail.

**Comment by kontrollanten** [comment]
I agree that it can be confusing. Today it looks like this:

![image](https://user-images.githubusercontent.com/6680299/101935013-ae6ba200-3bde-11eb-8168-d168d0d5b4c9.png)

Whilst under _My videos_ it's much more clear when it looks like this:

![image](https://user-images.githubusercontent.com/6680299/101934980-9dbb2c00-3bde-11eb-89a7-102dc8f3d5b1.png)

PR is welcome :)

**Comment by Chocobozzz** [comment]
We could add a special `private` badge if the video is private in the playlist :thinking:
