### ISSUE TITLE
Why did you close this problem? The problem still exists. It’s just that at that time the video was not available, I reported this.

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#2605]
Why did you close this problem? The problem still exists. It’s just that at that time the video was not available, I reported this.

_Originally posted by @Alterak in https://github.com/Chocobozzz/PeerTube/issues/2570#issuecomment-609446032_

**Comment by rigelk** [comment]
> Everything should work now.

I thought you referred to the problem mentioned in #2570, and thus that is was solved. I reopened it.
