### ISSUE TITLE
Default video privacy in video edit form

### ISSUE THREAD

**Issue by luc310** [Chocobozzz/PeerTube#2606]
Hello,
Is it possible to set all video in "only user of this instance can see this video" ?
By default it seems that they are set to "anyone can see this video" and I would like users that upload new video to have this option set to "only user of this instance can see this video" by default ?
thank you

**Comment by Chocobozzz** [comment]
Hi,

No sorry it's not possible. But I think we could add a plugin hook so admins can change default values of the video edit form :thinking:

**Comment by luc310** [comment]
Hello,

Then I’ll try to make the plugin.

Thank you



Envoyé de mon iPhone

**Comment by Yetangitu** [comment]
I'm running into the same issue, having to create a default_unlisted instance for users who can not be trusted to select that setting on upload. I've looked through the code and have not found any hook so I assume this has not been implemented yet. Could this be achieved by adding custom JS to the _Advanced Configuration_ section?

**Comment by Chocobozzz** [comment]
@Yetangitu There are helpers to delete a specific privacy: https://docs.joinpeertube.org/api-plugins?id=video-privacy-manager-api

**Comment by Chocobozzz** [comment]
I added client action hooks in https://github.com/Chocobozzz/PeerTube/commit/1599ee9b0eeba746373b330bca043518734f17bd so you can change the default privacy. For example:

```
  {
    const hooks = [
      'action:video-upload.init',
      'action:video-url-import.init',
      'action:video-torrent-import.init',
      'action:go-live.init'
    ]

    for (const h of hooks) {
      registerHook({
        target: h,
        handler: () => {
          const event = new Event('change', {
              bubbles: true,
              cancelable: true,
          });
          const selects = document.querySelectorAll('label[for=first-step-privacy] + my-select-options')

          selects.forEach(s => {
            s.value = 2 // Unlisted
            s.dispatchEvent(event)
          })
        }
      })
    }
  }
```
