### ISSUE TITLE
Unable to hide like/dislike buttons

### ISSUE THREAD

**Issue by tgurr** [Chocobozzz/PeerTube#2608]
I can hide the views count perfectly fine
`.views { display: none; }`
the comments
`.title-block { display: none; }`
the subscribe button
`.btn-group-subscribe.btn-group.subscribe-button { display: none; }`

but I'm unable to hide the like/dislike buttons as stated it's possible in: 
https://github.com/Chocobozzz/PeerTube/issues/1302#issuecomment-546274217. I tried many combinations e.g.:

```
.action-button.action-button-like { display: none; }
.action-button.action-button-dislike { display: none; }
```
but nothing worked for me.

The only way I'm able to get rid of them is via `.video-actions-rates { display: none; }` but that  hides the whole bar which carries other useful and required functionality like sharing and the context menu.

* PeerTube version or URL: 2.1.1
* Browser name/version: Chromium 80.0.3987.162
* NodeJS version: 13.12.0

**Comment by Chocobozzz** [comment]
Try `display: none !important;`

**Comment by tgurr** [comment]
@Chocobozzz awesome, thanks for the near instant help, worked just fine!
