### ISSUE TITLE
Global/Admin option to disable video comments on the whole instance

### ISSUE THREAD

**Issue by tgurr** [Chocobozzz/PeerTube#2609]
Right now it doesn't seem to be possible to disable video comments on a global basis. It would be nice to have such an option and then also hiding every evidence of such a function like displaying the sortable comments `.title-block { display: none; }` and the notice that comments are disabled on the bottom of each video.

* PeerTube version or URL: 2.1.1
* NodeJS version: 13.12.0

**Comment by Chocobozzz** [comment]
Hello,

A plugin would be appropriate.
