### ISSUE TITLE
Why the Peertube is on github and not on gitlab?

### ISSUE THREAD

**Issue by LAfricain** [Chocobozzz/PeerTube#2611]
**What happened?**
Source are on Github. I'm just surprised that Framasoft use Github, after the "degooglising internet" campaign.
**What do you expect to happen instead?**
Source should be in Gitlab. I'm sorry if I'm not in the right place but I don't know where to ask my question.

**Comment by rigelk** [comment]
The whole project is already on Gitlab. https://framagit.org/framasoft/peertube/

**Comment by DontUseGithub** [comment]
Hi @rigelk on [this](https://github.com/Chocobozzz/PeerTube/blob/develop/FAQ.md#why-host-on-github-and-framagit) page it says:

> The project has initially been hosted on GitHub by Chocobozzz. A full migration to Framagit would be ideal now that Framasoft supports PeerTube, but it would take a lot of time **and is an ongoing effort**.

Is this still true?

**Comment by rigelk** [comment]
Yes

**Comment by narcisgarcia** [comment]
First I was registering questions and issues at framacolibri.org (Discourse instance), next I'm doing this at Githib.com (proprietary tool in a proprietary service), and now I see I better go to framagit.org (Gitlab).

Could you make a clear map at joinpeertube.org and drive people from Github to the latter?
