### ISSUE TITLE
PeerTube fails to display the Occitan locale

### ISSUE THREAD

**Issue by Mejans** [Chocobozzz/PeerTube#2612]
Hello,
I experimented an issue when navigating in Occitan, and only in Occitan.
This is the console message:
**

> Cannot eval custom JavaScript. SyntaxError: "expected expression, got '<'"

**
Some miss-formed strings seem to be the root cause =/

**Comment by Chocobozzz** [comment]
We had to remove it in https://github.com/Chocobozzz/PeerTube/commit/8323c435c19ac6ed1656ee8436b175bce7bd2c82 awaiting its support in Angular

**Comment by Mejans** [comment]
Hello @Chocobozzz 
now we know why it doesn't work it's time to find a solution :)
What would it be?
I remember Mastodon being unable to display dates (day and month names) in Occitan.
They created a folder apart to put data of languages that wasn't included in a certain source.
And I think it's still the way it's handled, and it still works.

What do you say?

**Comment by Chocobozzz** [comment]
We can't. You'll have to add `oc` support directly in Angular: https://github.com/angular/angular/tree/master/packages/common/locales

**Comment by Mejans** [comment]
Hello @Chocobozzz 
well I can give it a try but I think they extract data from DLDR and Occitan is not in the main package but in the seed.
Otherwise could you switch it to the Catalan locale? To display dates there is not much changes.
But I wonder, why did it work and suddenly it stopped? What did you change?
Best regards

**Comment by Mejans** [comment]
Hello @Chocobozzz any news?

**Comment by Mejans** [comment]
I've just created what would be oc.ts:
https://github.com/angular/angular/pull/37315/files

**Comment by Chocobozzz** [comment]
Thanks @Mejans, I added the file to the bundle in https://github.com/Chocobozzz/PeerTube/commit/2a39506c7da9ef79671d4c21539313b6d49b1884

You can test oc locale tomorrow on https://peertube2.cpy.re/

**Comment by Mejans** [comment]
@Chocobozzz oups, not up to date or something is missing =/
