### ISSUE TITLE
HLS Storage Path not in Docker Volume

### ISSUE THREAD

**Issue by lost-carrier** [Chocobozzz/PeerTube#2613]
Sorry, I'm completely new to Peertube / might be a bit dump question, but...

**What happened?**
* I have a peertube installation based on that docker-compose.yml you provided.
* Changed configuration to HLS = active.
* Uploaded (kinda larger) video and after some time the playback works fine - excellent!

However: checking where all that video data went to, I find it under /app/storage/streaming-playlists/hls/.

**What do you expect to happen instead?**
From your docker-compose, i got the /data and /config mounted as volumes to that container. I see regular video data being stored under /data/videos. I would have expected to see HLS video data also somewhere under that /data mount (...since otherwise it will be lost on re-creation of that container).

To be clear: I'm happy to also mount /app/storage or something from external to solve this. It's maybe more my question what was the idea behind this or is it just a simple bug? Is this about to change in future versions. Any recommendation where to place the mount (/app/storage, /app/storage/streaming-playlists, /app/storage/streaming-playlists/hls/)?

**Additional information**
* PeerTube version or URL: production-buster / 2.1.1
* Browser name/version: -
* NodeJS version: -

* Link to browser console log if useful: -
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): -

**Comment by Chocobozzz** [comment]
Hello,

Yes it was a bug in the docker compose, fixed a few days ago in https://github.com/Chocobozzz/PeerTube/pull/2594

Just update your docker-compose with these changes :)

**Comment by lost-carrier** [comment]
Great, thanks for the link to the PR - I think I know where to fix this...

**Comment by fflorent** [comment]
Hi @Chocobozzz,

So, basically, we should apply the patch of the PR. I guess we should do `docker-compose down` and `docker-compose up`?

How may we know whether the fix is working correctly?

Thanks for your work! (and also thanks to @lost-carrier and @xcffl)

**Comment by Chocobozzz** [comment]
> So, basically, we should apply the patch of the PR. I guess we should do docker-compose down and docker-compose up?

 * Add `streaming_playlists: '../data/streaming-playlists'` below `storage:` in `config/production.yaml`
 * `docker-compose down && docker-compose up` so peertube reload the configuration
 * `docker-compose exec peertube bash` to move files from `/app/storage/streaming-playlists` to `/data/streaming-playlists`

**Comment by fflorent** [comment]
@Chocobozzz I followed your steps. However, it seems like the hls folder is empty in `/data/streaming-playlists`. There are recent folders (less than 3 days ago) that are under `/app/storage/streaming-playlists/hls`.

I checked, both `config/production.yaml` and `docker-volume/config/production.yaml` in the host have the line you mention. The docker containers were created again at `2020-04-09T12:11:14`.

Did I miss an instruction?

**Comment by Chocobozzz** [comment]
I don't understand. It's the point of this issue: move videos from `/app/storage/streaming-playlists/hls` to  `/data/streaming-playlists`.

**Comment by fflorent** [comment]
> I don't understand. It's the point of this issue: move videos from /app/storage/streaming-playlists/hls to /data/streaming-playlists/hls.

Yeah, sorry I don't understand your point either :).

What I mean is that  `/data/streaming-playlists/hls` is still empty.

Cheers,

**Comment by Chocobozzz** [comment]
You mean `/data/streaming-playlists/hls` is empty after you [updated production.yaml](https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/config/production.yaml#L48) and uploaded new videos?

**Comment by fflorent** [comment]
Yes! :)

**Comment by fflorent** [comment]
Pfff, my bad… I made a typo………… I wrote `streaming-playlists` instead of `streaming_playlists`

**Comment by Chocobozzz** [comment]
My bad too, the PR had this typo I fixed later in another commit. Happy this finally works :)

**Comment by fflorent** [comment]
> Happy this finally works :)

I'll let you know :)
