### ISSUE TITLE
Missing configuration make service run correctly but screws some page elements

### ISSUE THREAD

**Issue by immae** [Chocobozzz/PeerTube#2614]
**What happened?**

The "dots" menu doesn’t appear in the page when the configuration `transcoding.resolutions` miss entries (for instance after an upgrade). Other page elements may be missing but this is the most obvious one.

**What do you expect to happen instead?**

The node application should crash rather than run and raise silently in some pages.

**Steps to reproduce:**

1. remove some lines from transcoding.resolutions

2. restart peertube

3. go to the website and try to log out (for instance)

4. Logs in the peertube service will indicate a missing element in transcoding.resolutions but the website will look "quite right"

**Additional information**
* PeerTube version or URL: v2.1.1
* Browser name/version: Firefox
* NodeJS version: 10.X

* Link to browser console log if useful:
```
```
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
```
Apr 09 15:47:36 eldiron a1yny36isahh7j9y163wz4k5bbjpz69a-unit-script-peertube-start[13038]:   "err": "Error: Configuration property \"transcoding.resolutions.2160p\" is not defined\n    at Config.get (/nix/store/09y3xhb5r39kmyv0dqk9jcxgrpikrlm3-peertube-server-yarn-modules-v2.1.1/node_modules/config/lib/config.js:182:11)\n    at Object.get 2160p [as 2160p] (/nix/store/jjrs5v770gxp5v9waxzpnwcwaly17zmh-peertube-v2.1.1/dist/server/initializers/config.js:193:43)\n    at Object.keys.filter.key (/nix/store/jjrs5v770gxp5v9waxzpnwcwaly17zmh-peertube-v2.1.1/dist/server/controllers/api/config.js:217:102)\n    at Array.filter (<anonymous>)\n    at getEnabledResolutions (/nix/store/jjrs5v770gxp5v9waxzpnwcwaly17zmh-peertube-v2.1.1/dist/server/controllers/api/config.js:217:10)\n    at /nix/store/jjrs5v770gxp5v9waxzpnwcwaly17zmh-peertube-v2.1.1/dist/server/controllers/api/config.js:87:37\n    at Generator.next (<anonymous>)\n    at fulfilled (/nix/store/jjrs5v770gxp5v9waxzpnwcwaly17zmh-peertube-v2.1.1/dist/server/controllers/api/config.js:5:58)"
```

**Comment by Chocobozzz** [comment]
What is the content of your `config` directory? You should have `default.yaml` that contains all the configuration keys.

**Comment by Chocobozzz** [comment]
I added a check in https://github.com/Chocobozzz/PeerTube/commit/7cbbf79ff00bb0fd2103637a48848835c2368ce8

**Comment by immae** [comment]
> What is the content of your `config` directory? You should have `default.yaml` that contains all the configuration keys.

I do have it, but the configuration was older (from v1.2.*) which didn’t have the 0p and 2160p resolution. When I merged the new configuration I missed these two lines, and the result was that it ran in a degraded state.

Thanks for the fix !

**Comment by Chocobozzz** [comment]
You need to copy `default.yaml` after the upgrade. Check https://docs.joinpeertube.org/#/install-any-os?id=upgrade (`Copy new configuration defaults values and update your configuration file:`)

**Comment by immae** [comment]
Ah ok, that’s why. I only have production.yml (packaging issue, I’ll fix that), I wasn’t aware of this. Thanks for the link.
