### ISSUE TITLE
Brave look to be a unauthorized browser

### ISSUE THREAD

**Issue by Hierosme** [Chocobozzz/PeerTube#2616]
**What happened?**
I can't use Brave browser for navigate on a peertube site

**What do you expect to happen instead?**
simply use my browser

**Steps to reproduce:**

1. open brave browser

2. Allow Javascript Globally

3. connect to https://peertube.datagueule.tv/

**Additional information**
The message i have is:
```
We are sorry but it seems that PeerTube is not compatible with your web browser.
Please try with the latest version of Mozilla Firefox.
If you think this is a mistake, do not hesitate to report it.
```

* Browser name/version: Brave Version 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)

**Comment by scanlime** [comment]
Brave is broken, please don't use Brave.

**Comment by Chocobozzz** [comment]
Hello,

I can't reproduce. Could you open your web console to see what happens?

**Comment by Hierosme** [comment]
I have continue to investogate.

It look to be the cause by the Brave Global "Disable Java Script" . 

During my frist post i have insist about enable "Globally" java script. in fact i has speak about the "Orange Lion Shield on top of right" where you can disable Protection for the "entire site"

Globally i have disable Javscript and enable it WebSite by WebSite, and with Brave / PeerTube, it look impossible because Peertube don"t speack about JavaScript trouble but about my Browser Version. (That is worng diagnostique because i just have do disable protection)

As  workarround , i must disable totally protection of Brave for can look a peertube instance.

Impossible to reproduse it with a other Browser and "NoScript" plug-in

Here the web console
```
Uncaught TypeError: Cannot assign to read only property 'sessionStorage' of object '[object Window]'
    at Object.fyHm (main-es2015.ef9019f095c02bf82f77.js:1)
    at c (runtime-es2015.2e411f54962f4c630b19.js:1)
    at Object.4mtn (main-es2015.ef9019f095c02bf82f77.js:1)
    at c (runtime-es2015.2e411f54962f4c630b19.js:1)
    at Object.Rtfg (main-es2015.ef9019f095c02bf82f77.js:1)
    at c (runtime-es2015.2e411f54962f4c630b19.js:1)
    at Object.ey9i (main-es2015.ef9019f095c02bf82f77.js:1)
    at c (runtime-es2015.2e411f54962f4c630b19.js:1)
    at Module.zUnb (main-es2015.ef9019f095c02bf82f77.js:1)
    at c (runtime-es2015.2e411f54962f4c630b19.js:1)
```

About Brave usage. (scanlime)
I use **Brave** because Fondation Mozilla have cancel **Composer**, **Contact** and **Thunerbird** and now maintain a Browser it not support WebRTC well or Hangout.

I don't reconnize Fundation Mozilla anymore ... because Netscape heritage have been trash by that fundation.

Yes i'm a bit older and cross about Mozilla... but that is not the point here ... (impossible to solve here)

**Brave** will work or should work ... that is my point and that is for that i take time to repport my trouble.

I hope it help you to reproduse the trouble.

---
Heriosme

**Comment by rigelk** [comment]
Apparently SessionStorage is unavailable on your browser. Strange, I couldn't reproduce either.

**Comment by Hierosme** [comment]
Ok,

If nobody can't reproduse the trouble, that certainly because it haven't trouble.

Then I have restore "Default Parmeter" of Brave browser.

And it have work.

finally i have look to reproduce it.

If Cookie is disable + JavaScript is disable we got the warning about Firefox should be use.

**Brave** don't help in that case because , it keep a list of scripts and require explicite authorisation for each one. If scripts are black listed then it have no wait to re-enable it by just click on "enable javascript" option.

When i have post, i haven't realize that cumalative trouble, i have just read the PeerTube warning.

I sugess to update the warning message, and inform user's about need to enable JavaScript + in case of trouble **delete "Site datas"**. 

For me : **The issue can be close**

Thanks everyone.
