### ISSUE TITLE
PeerTube tries to use browser's language even when it has not been built

### ISSUE THREAD

**Issue by tuxayo** [Chocobozzz/PeerTube#2617]
Instances that build PeerTube from source may elect to not build all the languages because it considerably lengthen the build time. (should I create a ticket for that ?)

But then PeerTube still tries to use the first language of the Content-Language HTTP header. And it cause a blank screen.

**Steps to reproduce:**
Example:
- go to https://video.tedomum.net
- it should work
- in the settings of your browser, in the list of page languages, in first, add Esperanto
-  go to https://video.tedomum.net
- blank screen

**Additional information**
* PeerTube version or URL: v2.0.0 https://video.tedomum.net
* Browser name/version: Firefox

**Comment by rigelk** [comment]
We're painfully aware of the time required to build all languages. Sadly this is due to how the current internationalization module of Angular works.

**Comment by tuxayo** [comment]
> We're painfully aware of the time required to build all languages. Sadly this is due to how the current internationalization module of Angular works.

Thanks for the confirmation. Can I create an issue for that? To separate from handling non-built languages?

**Comment by DontUseGithub** [comment]
> * in the settings of your browser, in the list of page languages, in first, add Esperanto
> 
> * go to https://video.tedomum.net
> 
> * blank screen

I can confirm this bug exists when switching languages.

**Comment by Chocobozzz** [comment]
Hello,

PeerTube does not except a partial build. You can use prebuilt images. We're hoping that with Angular 10 client builds will be faster, but it's hard to be sure.
