### ISSUE TITLE
HLS Videos not accounted for Video Quota

### ISSUE THREAD

**Issue by lost-carrier** [Chocobozzz/PeerTube#2618]
It's not really important for me, but I just noticed that this Video Quota counter does not increase when adding Videos in HLS...

...maybe related to this one? https://github.com/Chocobozzz/PeerTube/issues/2613

PeerTube in Docker / production-buster / v2.1.1

**Comment by Chocobozzz** [comment]
Hello,

As described in the [configuration file](https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L215), users video quota does not take into account transcoded files, but only original files.

Check also the admin interface comment: 
![screen_2020-04-10-08:44:55](https://user-images.githubusercontent.com/5180488/78969607-9d2a3d00-7b07-11ea-94a0-33981cb5244a.png)

**Comment by lost-carrier** [comment]
OK, I see...

...I fear this renders this quota feature a bit useless, isn't it?

...anyhow: never mind! ...as said I'm not really using it and I definitely see more important stuff on your roadmap! ;-)

**Comment by rigelk** [comment]
> ...I fear this renders this quota feature a bit useless, isn't it?

@lost-carrier from the point of view of an admin with very limited storage space, this is less of an insurance, yes. But from the point of view of the user, this has a lot of advantages: the feedback on whether or not they can upload the file is instantaneous - otherwise we would have to wait for the transcoding to finish in order to tell them if they can keep their video… And estimates are impossible to make in advance.

**Comment by lost-carrier** [comment]
@rigelk Hmm... I see what you're aminig for, but...

...let's describe my "bug" like this:
- As said I have HLS enabled (...WebTorrent disabled)
- I upload a 20 GB MOV file (...only 25min of video - yes, ProRes is kind of insane)
- During transcoding I see this 20 GB of the quota used
- After transcoding I see the video stored under `streaming-playlists/hls` taking up 667 MB
- The original file file got deleted / **used quota is back to zero**...

Maybe the bug is a somewhat different one, but I don't see how this kind of quota should make sense...?

**Comment by rigelk** [comment]
Ah, Indeed this is not the same thing, and looks more like a bug!

Webtorrent or HLS, the original file gets deleted in both cases, but in both cases the original file size is the one we are supposed to take into account per the current implementation. Anyway it should not go back to 0.

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/5600def4c87d3e6b7724489c9c4415778ea014d3
