### ISSUE TITLE
ActivityPub fetcher gives up before fully synchronized

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#2619]
**What happened?**

I created a new server running PeerTube v2.1.1, and followed an existing server, also running PeerTube v2.1.1, with about 1300 videos. The new server starts crawling the activitypub outbox on the existing server, but it stops before reaching the end. The new server can see only a fraction of the existing server's videos.

It seems like the fetch stops after 100 pages or 10 minutes, whichever comes first. I was looking for a mechanism that allows it to restart where it left off, but I don't see such a thing. The outbox on the original server has a totalItems count slightly lower than the server's video count, not sure if that is correct.

**What do you expect to happen instead?**

I expected the new server to eventually pick up all of the followed server's videos, without giving up prematurely.

**Steps to reproduce:**

1. Fresh install of PeerTube v2.1.1

2. Follow https://diode.zone

3. Wait for all activitypub http fetcher jobs to finish

4. Check the site, check the logs, see that the outbox hasn't been fully scanned and many of the videos are still missing.

**Additional information**
* PeerTube version or URL:  diode.zone, dev.diode.zone
* Browser name/version: Chrome
* NodeJS version: 10.20.0

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Thanks for the issue, and the information. I increased the max page value in https://github.com/Chocobozzz/PeerTube/commit/4d9ae8f7cfce66ba0568a25c28034a2cad120444

So you'll fetch at most 20 000 videos. To rerun the outbox fetch, unfollow & refollow the remote instance.

**Comment by scanlime** [comment]
Does this fix the 10 minute limit on the fetch job as well? Often it would
only get through 30 or 40 pages.

-m
