### ISSUE TITLE
Video views stats

### ISSUE THREAD

**Issue by tcitworld** [Chocobozzz/PeerTube#262]
We currently only have the number of views for a video. Saving the date when the view occurred (for instance like we do for likes inside `accountVideoRate`) would allow : 
* the uploader to view a graph of his/her video views in function of time
* the instance to provide "real trending" videos, not just popular ones.

**Comment by Chocobozzz** [comment]
I don't think it's a good idea to directly store views in the database (size/writes).

What we could do however is:
  * Buffering views in Redis
  * Doing sums of the views and write them periodically in the database

**Comment by tcitworld** [comment]
Yeah, should have added that, sorry.

**Comment by Chocobozzz** [comment]
First step (storing views by dates) implemented: https://github.com/Chocobozzz/PeerTube/commit/9a629c6efbe39dfac290347670ca41b0d7100f41

**Comment by LoveIsGrief** [comment]
Does this mean that a plugin can now be written to implement this?

**Comment by Chocobozzz** [comment]
No not yet, the label means that we have to add features to the plugin API so we can create this kind of plugin

**Comment by rigelk** [comment]
View stats could store additional metadata, some of which we could take from https://support.google.com/youtube/answer/9314414?hl=en (YouTube support doc). For instance: view time in a video in minutes, how the user reached a video ("organic" if from within the interface, "external" if directly from a link posted outside, "embed" if from an embeded player).

Some more detailed stats could be interesting form the uploader's PoV, under "audience retention" stats. They consist in just reporting more precisely what parts of the video got watched, and not just the time watched.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/4900
