### ISSUE TITLE
Instead of displaying "22 months" - display "1 year and 10 months" or round it up and display "2 years"

### ISSUE THREAD

**Issue by DontUseGithub** [Chocobozzz/PeerTube#2622]
I've seen a video on peertube which says it was published "`22 months` ago". I don't think this is practical. 
I think we should use months only when the number of months is equal or smaller than `11 months`. 
When we reach `12 months`, we might as well write `1 year`. I think we should use years only until `9 years and 11 months`.
When we reach `9 years and 12 months` we might as well write `1 decade`. 

Month > Year > Decade ...

Now the hard decision is gonna be on how should we display 15 months for example? As 1 year and 3 months or as 2 years or as 1 year? This is the problem of rounding numbers up - they aren't accurate but their advantage is that they're short.

**Comment by rigelk** [comment]
I have used the long form in 41a94d07f, but left the grouping of years by decade for another time. The long form is okay for now, as we seem to have enough space for it. I made sure to rearrange the Private/Unlisted label in 62eacb420 to make sure that space will not vary too much.

Thanks for spotting the issue!
