### ISSUE TITLE
Validator finds errors in HLS 

### ISSUE THREAD

**Issue by n76** [Chocobozzz/PeerTube#2625]
**What happened?**
I am trying to use HLS streams from a PeerTube instance in Roku TV channel/app. When I specify a HLS stream to be played the visual is okay but there is no sound.

**What do you expect to happen instead?**
The sound should play as well as the visual.

**Steps to reproduce:**

1. In the [source code for my Roku channel/app](https://github.com/n76/PeerVue) you can delete line 64 of the [details screen](https://github.com/n76/PeerVue/blob/master/components/screens/details_screen/details_screen.brs) to enable use of HLS streams.

Before I put a bug in against Roku, I thought I'd check that the HLS stream was okay. So I installed Apple's validation tools and I found there are errors in the HLS produced by PeerTube:

    $ mediastreamvalidator https://video.fitchfamily.org/static/streaming-playlists/hls/35d8a8a8-3360-479b-ab22-d5f6f2a5e144/master.m3u8
    mediastreamvalidator: Version 1.4 (417.2-190530)
    [/static/streaming-playlists/hls/35d8a8a8-3360-479b-ab22-d5f6f2a5e144/master.m3u8] Started root playlist download
    [240.m3u8] Started media playlist download
    [360.m3u8] Started media playlist download
    [480.m3u8] Started media playlist download
    [2160.m3u8] Started media playlist download
    [720.m3u8] Started media playlist download
    [1080.m3u8] Started media playlist download
    [240.m3u8] All media files delivered and have end tag, stopping
    [360.m3u8] All media files delivered and have end tag, stopping
    [480.m3u8] All media files delivered and have end tag, stopping
    [720.m3u8] All media files delivered and have end tag, stopping
    [1080.m3u8] All media files delivered and have end tag, stopping
    [2160.m3u8] All media files delivered and have end tag, stopping

    --------------------------------------------------------------------------------
    240.m3u8
    --------------------------------------------------------------------------------
    Processed 43 out of 43 segments
    Average segment duration: 3.996124
    Total segment bitrates (all discontinuities): average: 418.08 kb/s, max: 463.09 kb/s
    Playlist max bitrate: 423.237000 kb/s
    Audio Group ID: AUDIO

    Discontinuity: sequence: 0, parsed segment count: 43 of 43, duration: 171.833 sec, average: 418.08 kb/s, max: 463.09 kb/s
    Track ID: 1
    Video Codec: avc1
    Video profile: High
    Video level: 3.1
    Video resolution: 426x240
    Video average IDR interval: 1.798246, Standard deviation: 0.473567
    Video frame rate: 30.000
    Track ID: 2
    Audio Codec: AAC-LC
    Audio sample rate: 48000 Hz
    Audio channels: 2
    Audio channel layout: Stereo (L R)

    --------------------------------------------------------------------------------
    360.m3u8
    --------------------------------------------------------------------------------
    Processed 43 out of 43 segments
    Average segment duration: 3.996124
    Total segment bitrates (all discontinuities): average: 657.21 kb/s, max: 745.47 kb/s
    Playlist max bitrate: 663.526000 kb/s
    Audio Group ID: AUDIO

    Discontinuity: sequence: 0, parsed segment count: 43 of 43, duration: 171.833 sec, average: 657.21 kb/s, max: 745.47 kb/s
    Track ID: 1
    Video Codec: avc1
    Video profile: High
    Video level: 3.1
    Video resolution: 640x360
    Video average IDR interval: 1.798246, Standard deviation: 0.471339
    Video frame rate: 30.000
    Track ID: 2
    Audio Codec: AAC-LC
    Audio sample rate: 48000 Hz
    Audio channels: 2
    Audio channel layout: Stereo (L R)

    --------------------------------------------------------------------------------
    480.m3u8
    --------------------------------------------------------------------------------
    Processed 43 out of 43 segments
    Average segment duration: 3.996124
    Total segment bitrates (all discontinuities): average: 1041.19 kb/s, max: 1259.18 kb/s
    Playlist max bitrate: 1049.430000 kb/s
    Audio Group ID: AUDIO

    Discontinuity: sequence: 0, parsed segment count: 43 of 43, duration: 171.833 sec, average: 1041.19 kb/s, max: 1259.18 kb/s
    Track ID: 1
    Video Codec: avc1
    Video profile: High
    Video level: 3.1
    Video resolution: 853x480
    Video average IDR interval: 1.779514, Standard deviation: 0.499522
    Video frame rate: 30.000
    Track ID: 2
    Audio Codec: AAC-LC
    Audio sample rate: 48000 Hz
    Audio channels: 2
    Audio channel layout: Stereo (L R)

    --------------------------------------------------------------------------------
    2160.m3u8
    --------------------------------------------------------------------------------
    Processed 43 out of 43 segments
    Average segment duration: 3.996240
    Total segment bitrates (all discontinuities): average: 28549.88 kb/s, max: 48547.62 kb/s
    Playlist max bitrate: 28692.855000 kb/s
    Audio Group ID: AUDIO

    Discontinuity: sequence: 0, parsed segment count: 43 of 43, duration: 171.838 sec, average: 28549.88 kb/s, max: 48547.62 kb/s
    Track ID: 1
    Video Codec: avc1
    Video profile: High
    Video level: 5.1
    Video resolution: 3840x2160
    Video average IDR interval: 0.933537, Standard deviation: 0.205241
    Video frame rate: 29.970
    Track ID: 2
    Audio Codec: AAC-LC
    Audio sample rate: 48000 Hz
    Audio channels: 2
    Audio channel layout: Stereo (L R)

    --------------------------------------------------------------------------------
    720.m3u8
    --------------------------------------------------------------------------------
    Processed 43 out of 43 segments
    Average segment duration: 3.996124
    Total segment bitrates (all discontinuities): average: 1856.75 kb/s, max: 2253.75 kb/s
    Playlist max bitrate: 1869.041000 kb/s
    Audio Group ID: AUDIO

    Discontinuity: sequence: 0, parsed segment count: 43 of 43, duration: 171.833 sec, average: 1856.75 kb/s, max: 2253.75 kb/s
    Track ID: 1
    Video Codec: avc1
    Video profile: High
    Video level: 3.1
    Video resolution: 1280x720
    Video average IDR interval: 1.779514, Standard deviation: 0.498153
    Video frame rate: 30.000
    Track ID: 2
    Audio Codec: AAC-LC
    Audio sample rate: 48000 Hz
    Audio channels: 2
    Audio channel layout: Stereo (L R)

    --------------------------------------------------------------------------------
    1080.m3u8
    --------------------------------------------------------------------------------
    Processed 43 out of 43 segments
    Average segment duration: 3.996124
    Total segment bitrates (all discontinuities): average: 3341.52 kb/s, max: 4050.98 kb/s
    Playlist max bitrate: 3361.022000 kb/s
    Audio Group ID: AUDIO

    Discontinuity: sequence: 0, parsed segment count: 43 of 43, duration: 171.833 sec, average: 3341.52 kb/s, max: 4050.98 kb/s
    Track ID: 1
    Video Codec: avc1
    Video profile: High
    Video level: 3.1
    Video resolution: 1920x1080
    Video average IDR interval: 1.761168, Standard deviation: 0.518405
    Video frame rate: 30.000
    Track ID: 2
    Audio Codec: AAC-LC
    Audio sample rate: 48000 Hz
    Audio channels: 2
    Audio channel layout: Stereo (L R)

    --------------------------------------------------------------------------------
    MUST fix issues
    --------------------------------------------------------------------------------

    Error: Measured peak bitrate compared to master playlist declared value exceeds error tolerance
    --> Detail:  Measured: 745.47 kb/s, Master playlist: 663.53 kb/s, Error: 12.35%
    --> Source:  https://video.fitchfamily.org/static/streaming-playlists/hls/35d8a8a8-3360-479b-ab22-d5f6f2a5e144/master.m3u8
    --> Compare: 360.m3u8

    --> Detail:  Measured: 1259.18 kb/s, Master playlist: 1049.43 kb/s, Error: 19.99%
    --> Source:  https://video.fitchfamily.org/static/streaming-playlists/hls/35d8a8a8-3360-479b-ab22-d5f6f2a5e144/master.m3u8
    --> Compare: 480.m3u8

    --> Detail:  Measured: 48547.62 kb/s, Master playlist: 28692.85 kb/s, Error: 69.20%
    --> Source:  https://video.fitchfamily.org/static/streaming-playlists/hls/35d8a8a8-3360-479b-ab22-d5f6f2a5e144/master.m3u8
    --> Compare: 2160.m3u8

    --> Detail:  Measured: 2253.75 kb/s, Master playlist: 1869.04 kb/s, Error: 20.58%
    --> Source:  https://video.fitchfamily.org/static/streaming-playlists/hls/35d8a8a8-3360-479b-ab22-d5f6f2a5e144/master.m3u8
    --> Compare: 720.m3u8

    --> Detail:  Measured: 4050.98 kb/s, Master playlist: 3361.02 kb/s, Error: 20.53%
    --> Source:  https://video.fitchfamily.org/static/streaming-playlists/hls/35d8a8a8-3360-479b-ab22-d5f6f2a5e144/master.m3u8
    --> Compare: 1080.m3u8

    Error: Playlist video resolution doesn't match parsed video resolution
    --> Detail:  Playlist: 852 x 480, Video: 853 x 480
    --> Source:  https://video.fitchfamily.org/static/streaming-playlists/hls/35d8a8a8-3360-479b-ab22-d5f6f2a5e144/master.m3u8
    --> Compare: 480.m3u8

    Error: Different target durations detected
    --> Detail:  Target duration: 5 vs Target duration: 6
    --> Source:  2160.m3u8
    --> Compare: 240.m3u8

    --> Detail:  Target duration: 5 vs Target duration: 6
    --> Source:  2160.m3u8
    --> Compare: 360.m3u8

    --> Detail:  Target duration: 5 vs Target duration: 6
    --> Source:  2160.m3u8
    --> Compare: 480.m3u8

    --> Detail:  Target duration: 6 vs Target duration: 5
    --> Source:  720.m3u8
    --> Compare: 2160.m3u8

    --> Detail:  Target duration: 6 vs Target duration: 5
    --> Source:  1080.m3u8
    --> Compare: 2160.m3u8

    $ 

**Additional information**
* PeerTube version or URL: https://video.fitchfamily.org/ (v2.1.1)

**Comment by rigelk** [comment]
hi @n76 - do you know of a tool similar to `mediastreamvalidator` that is available on Linux platforms? I don't have a macOS readily available and the aforementioned tools seem to only be made for this platform.

I came across [hls-analyzer](https://github.com/epiclabs-io/hls-analyzer) (didn't work) and [HLS Checker tool](http://www.tslemurs.com/ott/hls_checker_tool.html) (didn't work).

**Comment by n76** [comment]
@rigelk Sorry, no.

I spent several hours examining the fragmented MP4 files using tools like ffmpeg trying to figure out why I had no audio on my test streams and found nothing wrong.

I was in the midst of writing up a help/bug issue on the Roku developer's area when it dawned on me there might be a HLS validation tool set. The first my search turned up was from Apple (the originator of HLS). Since I am on a Mac I used it.

Sure would be nice if there were a web based validator like you can find for JSON, etc.

**Comment by rigelk** [comment]
@n76 I stumbled upon http://inspectstream.theoplayer.com/, which seems to yield the errors you reported.

**Comment by rigelk** [comment]
Now back to the issue, this is weird. Why would the cause for a lack of audio on Roku devices lie in misreported durations/bitrates in HLS playlists?

**Comment by n76** [comment]
> Now back to the issue, this is weird. Why would the cause for a lack of audio on Roku devices lie in misreported durations/bitrates in HLS playlists?

It probably doesn't. But I am guessing the Roku support won't help me figure out the sound issue if the stream fails validation. So I thought I'd address that first. :)

**Comment by n76** [comment]
For what it is worth, I found[ an article that goes step by step through using ffmpeg to create a HLS stream](https://www.martin-riedl.de/2020/04/17/using-ffmpeg-as-a-hls-streaming-server-overview/) that passes Apple's validator. I think it might be useful in this case.

**Comment by kontrollanten** [comment]
I'm trying to set up a load test with JMeter and Blazameter HLS Plugin. In the plugin you provide the URL to a playlist and then run. When I'm trying with https://video.fitchfamily.org/static/streaming-playlists/hls/d5cf193e-06e4-491d-812f-71feca3a0651/master.m3u8 I get the following error:

```
2020-11-02 14:47:03,666 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'bzm - Streaming Sampler'.
java.lang.NullPointerException: null
	at java.net.URI$Parser.parse(URI.java:3104) ~[?:?]
	at java.net.URI.<init>(URI.java:600) ~[?:?]
	at java.net.URI.create(URI.java:881) ~[?:?]
	at com.blazemeter.jmeter.videostreaming.hls.Playlist.buildAbsoluteUri(Playlist.java:117) ~[jmeter-bzm-hls-3.0.3.jar:?]
	at com.blazemeter.jmeter.videostreaming.hls.Playlist.lambda$getMediaSegments$1(Playlist.java:139) ~[jmeter-bzm-hls-3.0.3.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.blazemeter.jmeter.videostreaming.hls.Playlist.getMediaSegments(Playlist.java:140) ~[jmeter-bzm-hls-3.0.3.jar:?]
	at com.blazemeter.jmeter.videostreaming.hls.HlsSampler$MediaPlayback.updateMediaSegments(HlsSampler.java:116) ~[jmeter-bzm-hls-3.0.3.jar:?]
	at com.blazemeter.jmeter.videostreaming.hls.HlsSampler$MediaPlayback.<init>(HlsSampler.java:110) ~[jmeter-bzm-hls-3.0.3.jar:?]
	at com.blazemeter.jmeter.videostreaming.hls.HlsSampler$MediaPlayback.<init>(HlsSampler.java:100) ~[jmeter-bzm-hls-3.0.3.jar:?]
	at com.blazemeter.jmeter.videostreaming.hls.HlsSampler.sample(HlsSampler.java:59) ~[jmeter-bzm-hls-3.0.3.jar:?]
	at com.blazemeter.jmeter.videostreaming.core.VideoStreamingSampler.sample(VideoStreamingSampler.java:79) ~[jmeter-bzm-hls-3.0.3.jar:?]
	at com.blazemeter.jmeter.hls.logic.HlsSampler.sample(HlsSampler.java:198) ~[jmeter-bzm-hls-3.0.3.jar:?]
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1270) ~[ApacheJMeter_http.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:630) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.3]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

According to this error, it seems like there's some formatting error in the m3u8 file that makes the plugin to fail to fetch the URI. May it be some error that 99% of all clients forgives?

I've created an [issue at HLS Plugin](https://github.com/Blazemeter/HLSPlugin/issues/18), but something tells me that the error is within the format from PeerTube.

**Comment by Chocobozzz** [comment]
Closing this old issue. Please open a new one if you have other issues with peertube hls streams.

**Comment by stevespaw** [comment]
This is still an issue with ROKU - no audio on the M3U8 Streams.  Here is the Roku tester. http://devtools.web.roku.com/stream_tester/html/
It works best by installing the app locally. add the Roku test app to the Roku Stick. 
https://my.roku.com/add/ZJMQ6D5
Add the device manually by IP address (I had to do this).
Add a Peertube M3U8 - it will say no audio track. Any other M3U8's, and the samples work fine.

**Comment by stevespaw** [comment]
It seems that creating the audio as a separate stream in FFMPEG might work.
https://community.roku.com/t5/Roku-Developer-Program/HLS-fMP4-No-Audio/td-p/607399
Is it possible to enable this? This would be a huge benefit to enable Roku to play Peertube content.

**Comment by Chocobozzz** [comment]
@stevespaw See https://github.com/Chocobozzz/PeerTube/issues/939

But IMHO roku should handle fragmented mp4 containing both audio and video streams...

**Comment by stevespaw** [comment]
@Chocobozzz I totally agree ! But right now, they are they are the big Gorilla in the room. I have been trying to get them, to even recognize the issue for 6 months, but I cannot find anyone that cares there. :-(. Even the "peerVue" project by n76 above is blocked/broken, If we can get Peertube videos to play on ROKU it opens up a huge opportunity for everyone. (I am also totally in need of multiple audio track selection as in the #939  above. We are looking at a project that has 30+ languages. This would be fantastic! )  Even this cool app has no audio on Roku with Peertube videos. https://play.google.com/store/apps/details?id=com.instantbits.cast.webvideo

**Comment by stevespaw** [comment]
@Chocobozzz is there a way, with a plug-in, to make a Roku friendly HLS playlist? I am not a developer, but would be interested in supporting such a plug-in. Here is an FFMPEG string example that is supposed to work for Roku by mapping the audio streams: 
ffmpeg -i "http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_2160p_30fps_normal.mp4" -map 0:0 -map 0:1 -c:v libx265 -preset faster -c:a aac -g 48 -hls_time 4 -hls_playlist_type vod -hls_segment_type fmp4 -var_stream_map "a:0,agroup:aud,default:yes v:0,agroup:aud" -master_pl_name master.m3u8 "stream_%v.m3u8"

Could this work like the custom transcode plug-in?

This Roku incompatibility is now biting us on another project that Peertube is otherwise a perfect candidate. (Yes, I agree that Roku should fix this :-), but...... )

**Comment by stevespaw** [comment]
How hard/practical would it be to put the audio mapping options in a Radio button "Roku Compatible" here: https://framagit.org/framasoft/peertube/official-plugins/-/blob/master/peertube-plugin-transcoding-custom-quality/main.js
I am just thinking out loud.

**Comment by Chocobozzz** [comment]
Unfortunately it's not possible. Splitting audio/video streams is a big work, which we would like to implement, but probably next year.
