### ISSUE TITLE
Cli Client watch module not working

### ISSUE THREAD

**Issue by Musadiqraees** [Chocobozzz/PeerTube#2628]
**Dear team, i hope you are fine and having a good time. I am thankful for your guidance.
I am facing issue that i can able to play video from cli with this URL 
"node ./dist/server/tools/peertube-watch.js --gui vlc https://peertube.cpy.re/videos/watch/7024ae74-80a9-4e1d-8ede-cc11a470e131
"
but other than that i tried many URL but they are failing. Please guide me** 

Macbooks-MacBook-Pro-4:PeerTube macbook$ node ./dist/server/tools/peertube-watch.js --gui vlc https://alttube.fr/videos/watch/b96d04da-793d-4514-acf4-2e65771e0459
**Error: Command failed: node /Users/macbook/PeerTube/dist/server/tools/node_modules/webtorrent-hybrid/bin/cmd.js --vlc https://alttube.fr/download/torrents/b96d04da-793d-4514-acf4-2e65771e0459-480.torrent**
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at /Users/macbook/PeerTube/dist/server/tools/peertube-watch.js:59:25
    at Generator.next (<anonymous>)
    at /Users/macbook/PeerTube/dist/server/tools/peertube-watch.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/macbook/PeerTube/dist/server/tools/peertube-watch.js:4:12)
    at run (/Users/macbook/PeerTube/dist/server/tools/peertube-watch.js:50:12)
    at Command.<anonymous> (/Users/macbook/PeerTube/dist/server/tools/peertube-watch.js:42:5)
    at Command.listener (/Users/macbook/PeerTube/node_modules/commander/index.js:291:8) {
  status: 1,
  signal: null,
  output: [

Macbooks-MacBook-Pro-4:PeerTube macbook$ node ./dist/server/tools/peertube-watch.js --gui vlc https://tube.anjara.eu/videos/watch/7a93383f-1d4f-426c-9995-5d507e9e4d9c
child_process.js:669
    throw err;
    ^

Error: Command failed: node /Users/macbook/Desktop/PeerTube/dist/server/tools/node_modules/webtorrent-hybrid/bin/cmd.js --vlc https://tube.anjara.eu/download/torrents/7a93383f-1d4f-426c-9995-5d507e9e4d9c-480.torrent

**Comment by Chocobozzz** [comment]
What is the output of 

```
node /Users/macbook/PeerTube/dist/server/tools/node_modules/webtorrent-hybrid/bin/cmd.js --vlc https://alttube.fr/download/torrents/b96d04da-793d-4514-acf4-2e65771e0459-480.torrent
```

**Comment by Musadiqraees** [comment]
Macbooks-MacBook-Pro-4:PeerTube macbook$ node dist/server/tools/node_modules/webtorrent-hybrid/bin/cmd.js --vlc https://alttube.fr/videos/watch/a3aaf4a1-3352-4c91-8cbb-58dd6e6ad75c
Error: not a number: buffer[0] = 60

UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/webtorrent/webtorrent-cli/issues

**Comment by Chocobozzz** [comment]
It's not:

```
node dist/server/tools/node_modules/webtorrent-hybrid/bin/cmd.js --vlc https://alttube.fr/videos/watch/a3aaf4a1-3352-4c91-8cbb-58dd6e6ad75c
```

but 

```
node dist/server/tools/node_modules/webtorrent-hybrid/bin/cmd.js --vlc https://alttube.fr/download/torrents/b96d04da-793d-4514-acf4-2e65771e0459-480.torrent
```

**Comment by Musadiqraees** [comment]
Its not working even with this error is same

**Comment by Chocobozzz** [comment]
https://alttube.fr/download/torrents/b96d04da-793d-4514-acf4-2e65771e0459-480.torrent does not exist
