### ISSUE TITLE
Make the "updated date" column human-readable in job admin

### ISSUE THREAD

**Issue by bnjbvr** [Chocobozzz/PeerTube#263]
In the jobs tab of the administration section, the "created date" is shown in a human readable way (e.g. Jan 30, 2018 etc) while the "updated date" is just displaying what looks like a `date.toString()` (e.g.  2018-01-30T13:45:17.485Z). It would be nice if both columns displayed the same format.

**Comment by Chocobozzz** [comment]
Fixed: https://github.com/Chocobozzz/PeerTube/commit/61bbc7277501692d1520a421dff5af5d38ba6cf4
