### ISSUE TITLE
Embed API can't get duration

### ISSUE THREAD

**Issue by mjsamp** [Chocobozzz/PeerTube#2633]
Hi all,

I'm porting peertube embed to Plyr player and I succesfuly get it working but for some reason the event playbackStatusUpdate aren't returning duration value. Once the value returns as undefined I check it using JSON.stringify() and it wasn't on the object. Tried using videos from different instances. The other ones are returning as expected.

code used:
      const PeerTubePlayer = window['PeerTubePlayer'];
      player.embed = new PeerTubePlayer(iframe);

      player.embed.addEventListener('playbackStatusUpdate', function (value) {
        currentTime = value.position;
        triggerEvent.call(player, player.media, 'timeupdate');

        player.media.duration = value.duration;
        triggerEvent.call(player, player.media, 'durationchange');

        if (parseFloat(value.position) > 0) {
                var n = parseFloat(value.position / value.duration);
                console.log('position: '+value.position+' duration: '+value.duration);
		player.media.buffered = n;
		triggerEvent.call(player, player.media, 'progress');
	}

        if (value.playbackState == 'ended') {
		player.media.paused = true;
		triggerEvent.call(player, player.media, 'ended');
	}
      });

I'm using this as sdk 
https://unpkg.com/@peertube/embed-api/build/player.min.js

and following doc as reference.
https://docs.joinpeertube.org/#/api-embed-player

Plyr player
https://github.com/sampotts/plyr

Thanks in advance.

**Comment by Chocobozzz** [comment]
Hello, the `duration` field was added a few days ago and will be available in the next PeerTube release (2.2). I updated the documentation in https://github.com/Chocobozzz/PeerTube/commit/624a022157abc74e72c2cac3a80c823eb950e599

**Comment by mjsamp** [comment]
Thank you!
