### ISSUE TITLE
Add a sample of oembed code in the documentation

### ISSUE THREAD

**Issue by vincentxavier** [Chocobozzz/PeerTube#2637]
I've not seen any oembed snippet code to add, and since it would be complicated to add a it to the reference file, you could give a snippet :+1: 
```json
[
  {
    "schemes": ["https:\/\/instance.tube\/videos\/watch\/*"],
    "url":"https:\/\/instance.tube\/services\/oembed",
    "discovery":true
  }
]
```
I've tried it and it works well on a Moodle Instance, where `instance.tube` is a real PeerTube instance.

**Comment by gerhardbeck** [comment]
It would also be great to add the Oembed endpoint (e.g. for [Humhub](https://github.com/humhub/humhub/issues/2126))

**Comment by Chocobozzz** [comment]
Closed by https://framagit.org/framasoft/peertube/documentation/-/merge_requests/87
