### ISSUE TITLE
In videos screens, allow to show only instance-local videos

### ISSUE THREAD

**Issue by bnjbvr** [Chocobozzz/PeerTube#264]
When you go to any of the Videos screen (Trending or Recently Added), I think it'd be nice to have an option to display only videos that have been uploaded on this particular instance (through a checkbox / button, maybe?). It would allow discovering local and unique videos more easily. The problem is particularly strong if you federate with a lot of other instances, in which case local videos may become impossible to find.

**Comment by Chocobozzz** [comment]
I think another button below "Recently added" should be fine.

**Comment by bnjbvr** [comment]
Well, I'd be curious to see both local **and** recently added videos, as well as local **and** trending videos. More generally, I guess having ways to sort by number of views / upload date / number of comments would be nice to have in the Videos sections, what do you think?

**Comment by ReK2Fernandez** [comment]
yeah I agree, I believe I already posted a suggestion about this, not sure if it got deleted or not but if not is there any way to merge them?

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/066e94c5382a761180c7d82fa24b31b66dbeaca4
