### ISSUE TITLE
Disable thumbnail cropping

### ISSUE THREAD

**Issue by YohannLYD** [Chocobozzz/PeerTube#2640]
I am hosting a lot of video that have a 4:3 aspect ratio and would like their thumbnails to have the same AR. But when a thumbnail is uploaded, the image is cropped to match a 16:9 AR.

As thoses videos are embeded on a dedicated website with the matching aspect ratio, I wish the thumbnails would match aswell.
Would it be possible to disable the cropping of the thumnails (or add an option to disable it) to solve this?

Thanks for your help

PeerTube v2.1.1
NodeJS v10.19.0

**Comment by Chocobozzz** [comment]
Could you paste an existing cropped thumbnail, and another one with the result you would like?

**Comment by YohannLYD** [comment]
Here the original image I want to be displayed :
![4-3](https://user-images.githubusercontent.com/8319299/79353445-5ab79480-7f3b-11ea-97af-406be7db677a.jpg)

Here is how the backend crops the previous one :
![cropped](https://user-images.githubusercontent.com/8319299/79353428-55f2e080-7f3b-11ea-966f-d2d79c41f8b4.jpg)

**Comment by Chocobozzz** [comment]
Merging this discussion in https://github.com/Chocobozzz/PeerTube/issues/3027
