### ISSUE TITLE
No streamingPlaylists?

### ISSUE THREAD

**Issue by Nojus741** [Chocobozzz/PeerTube#2645]
Hello, I noticed an instance using HLS stream playlist (I think this: https://github.com/Chocobozzz/PeerTube/issues/1237) but my peertube instance does not have any streamingPlaylist url, I have enabled both webtorrent and HLS support. It still does not have any urls (see image). How can I enable HLS stream playlist?

Instance with working streamingPlaylists:
![unknown](https://user-images.githubusercontent.com/5261007/79505306-dcdbb200-803c-11ea-9d8f-4a343f1cca71.png)

My instance with no streamingPlaylists on video:
![my](https://user-images.githubusercontent.com/5261007/79505364-efee8200-803c-11ea-8ad4-b6bbdb1bfad8.png)

**Comment by Chocobozzz** [comment]
Did you enabled transcoding and HLS in `Administration` > `Configuration` > `Advanced configuration`?

**Comment by Nojus741** [comment]
Yes, I have it enabled:
![Screenshot_20200417-111055_Chrome](https://user-images.githubusercontent.com/5261007/79547190-3aebb200-809c-11ea-9a9c-82da997fe688.jpg)

**Comment by Chocobozzz** [comment]
Check your transcoding jobs in Admin -> System -> Jobs

Maybe the HLS transcoding failed

**Comment by Nojus741** [comment]
`

Job: 63211 Type: video-transcoding Processed on Apr 17, 2020, 11:39:18 AM Finished on Apr 17, 2020, 11:39:19 AM
--
{   "type": "hls",   "videoUUID": "621329bb-a513-4ef1-88b3-0a457634567f",   "resolution": 306,   "copyCodecs": true }
Error: ffmpeg exited with code 1: Unrecognized option 'hls_segment_type'. Error splitting the argument list: Option not found      at ChildProcess.<anonymous> (/var/www/peertube/node_modules/fluent-ffmpeg/lib/processor.js:182:22)     at ChildProcess.emit (events.js:198:13)     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

`

**Comment by Chocobozzz** [comment]
You need [ffmpeg >= 4.1](https://github.com/Chocobozzz/PeerTube/blob/develop/config/default.yaml#L235)

**Comment by Nojus741** [comment]
Thank you, fixed it. Also is there a way to generate hls to all existing files?

**Comment by Chocobozzz** [comment]
https://docs.joinpeertube.org/#/maintain-tools?id=create-transcoding-jobjs
