### ISSUE TITLE
Question: Two instances with same DB and storage

### ISSUE THREAD

**Issue by ipbc-dev** [Chocobozzz/PeerTube#2647]
Good morning! I have a question, I'm not sure if I should ask here or not, sorry if not, forward me to the right place please :)

Question is: Can I have two peertube instances connected to the same DataBase and Storage, or would that break the Federation or any other thing? Do I need to add some config to my slave instance in order to prevent issues??

Extra Info: I need to migrate all post from my old video platform to peertube... My live instance is not really powerfull so it's being overloaded with a huge ammount of jobs. My plan is to use my migrator server to run a peertube instance, in order to do the transcoding and even publish it and add the files to the storage from this server(storage is already remote in my live instance), leaving my live instance free of migration jobs. This would we great if it can be done! Any suggestion or comment would be appreciated. Thanks a lot!

**Comment by Chocobozzz** [comment]
No sorry, we do not support this.

**Comment by ipbc-dev** [comment]
-- Please reply above this line --


Hello!

We received your request and will get in touch with you as soon as
possible.

We usually reply WITHIN 24 HOURS BETWEEN MONDAY TO FRIDAY.

In the meantime, you can have a look at the BitTube Knowledge Base:
https://kb.bittubeapp.com [1] and reply to this email with 'SOLVED',
if you found the answer to your question.

Thanks for your understanding.

Talk to you soon,

Your BitTube Team.


Links:
------
[1] https://kb.bittubeapp.com
