### ISSUE TITLE
Caption/Subtitles supported formats?

### ISSUE THREAD

**Issue by rebelcode-xr** [Chocobozzz/PeerTube#2648]
Please explain to the user which caption formats are supported (srt?):
![image](https://user-images.githubusercontent.com/63522951/79563775-b570fd80-80ad-11ea-8d16-24debd498695.png)

I haven't found it anywhere, not even in the docs... :(

**Comment by Chocobozzz** [comment]
`.srt` and `.vtt`

**Comment by rigelk** [comment]
I added a tooltip in #2644 to inform the user of the supported formats, like we do in the upload view/profile picture upload.

**Comment by rebelcode-xr** [comment]
great! ✊
