### ISSUE TITLE
integrate native torrents into the peertube webclient

### ISSUE THREAD

**Issue by SoniEx2** [Chocobozzz/PeerTube#2651]
a bittorrent-based project that refuses to consider native bittorrent integration is not a friendly bittorrent project and should not be welcomed by users.

we don't need fragmentation.

**Comment by rigelk** [comment]
Your other issue was not a BEP, so it doesn't fall under the umbrella of BitTorrent policies we have to follow. While interesting, we don't have the resources to develop it ourselves *and* push it to BitTorrent client, a feat not even the popular WebTorrent standard achieved in a mostly ossified software ecosystem of desktop clients.
