### ISSUE TITLE
RSS feeds should be updated after transcoding job

### ISSUE THREAD

**Issue by raphgilles** [Chocobozzz/PeerTube#2652]
Hello,

Since some days I subscribed to some RSS feeds from my favorite channels, but I noticed that it's updated directly after the publication. I think it should be updated after the transcoding job, like the federation do.

It could be better for people who have a very small internet connexion. And more clean to don't enter on a page with the message "This video is not also transcoded".

Thank you !

**Comment by Chocobozzz** [comment]
Please paste an URL of one of these videos

**Comment by raphgilles** [comment]
I can paste any link of any instance. It's a general thing.

**Comment by Chocobozzz** [comment]
I can't reproduce so please paste an URL of one of these videos.
