### ISSUE TITLE
Being excluded from peertube listing

### ISSUE THREAD

**Issue by PeterAlfonsLoch** [Chocobozzz/PeerTube#2653]
We get too much malicious users, also many who do not care to read the rules (and maybe even by seeing that the language is not theirs still upload videos)

Is there a way to get isolated and not be listed or shown to other instances? Yes we understand the main reason for the project and support it's idea, but for legal reasons and our main goal it is not working in the intended way. So we do not want to be listed anymore.

**Comment by rigelk** [comment]
Please reach out to https://contact.framasoft.org/en/ with your instance domain, we'll proceed with the removal ASAP :)

**Comment by DontUseGithub** [comment]
@PeterAlfonsLoch you should enable mandatory moderation of videos before they appear public, and you'll be fine :wink:
