### ISSUE TITLE
New markdown textarea display is lots of efforts to edit

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#2656]
Since the update of PeerTube styles, the preview of markdown textareas appears down to them, 
it's really a pain to edit, especially for long text in the admin instance configuration and the video edit view.

First I thought about a plugin to replace textareas with a custom editor like code-mirror but we can't dispatch the event `change` of textareas. For the component `markdown-textarea` only Angular directives such as `(ngModel)`, `(ngModelChange)` are used:  https://github.com/Chocobozzz/PeerTube/blob/14cbb9a65a1b2853c93df429fcc3df9004a5c940/client/src/app/shared/forms/markdown-textarea.component.html#L3

For the other textareas I don't understand how it's really work.

Also for `markdown-textareas`, by clicking on "Complete Preview" should simply overclass the textarea and it's preview to see it in fullscreen mode side by side.

Something is planned to improve these textareas ?

**Comment by rigelk** [comment]
Other textareas works with Angular's reactive form's formControlName attribute.

Since we are trying to keep our bundle size in check, we try to avoid loading full editors for text edition. Maybe we could transpose their way to deal with the preview to our textareas?

**Comment by kimsible** [comment]
> Other textareas works with Angular's reactive form's formControlName attribute.

Ok, so there are no way to dispatch the value ?

> Since we are trying to keep our bundle size in check, we try to avoid loading full editors for text edition. Maybe we could transpose their way to deal with the preview to our textareas?

I understand, custom editors are usually big and full re-implementation of textarea, only the fullscreen feature (and switch `flex-direction` css directive) will be useful inside PeerTube, it needs to control parent components from markdown-textarea to override some styles.
