### ISSUE TITLE
Make twitter service an option not requiered

### ISSUE THREAD

**Issue by pprw** [Chocobozzz/PeerTube#2657]
**What happened?**

During the initial configuration (after installing peertube), Peertube asks for a twitter login (in service tab). There is already @Chocobozzz in the field if you didn't touch this part of the production.yaml

There is no option if you don't want to link your peertube instance with a twitter account.

You cannot leave this field blank. I had to write "null" as twitter login.

**What do you expect to happen instead?**
IMHO:

- there should be a more obvious way to choose to not link peertube instance to twitter account.

- it should be possible to disable Twitter stuff in the production.yaml (If I comment these lines, peertube will not restart).

**Steps to reproduce:**
visit admin/config/edit-custom after installing peertube

**Comment by pprw** [comment]
There is a [FAQ entry](https://github.com/Chocobozzz/PeerTube/blob/develop/FAQ.md#why-do-we-have-to-put-our-twitter-username-in-peertube-configuration) about this. But does peertube need a default value even if the instance does not plan to use twitter?

**Comment by Chocobozzz** [comment]
> There is no option if you don't want to link your peertube instance with a twitter account.

You don't link anything, it's just a value set in a meta element in HTML.

**Comment by meZee** [comment]
This is an issue, I spent way too much time trying to find an issue, at the very least having optional next to it is misleading. The error message saying there is an issue with the config is nondescript.

**Comment by pprw** [comment]
Agreed!

**Comment by meZee** [comment]
@Chocobozzz please consider reopening

**Comment by Chocobozzz** [comment]
There is already an issue for the error message in the config admin: https://github.com/Chocobozzz/PeerTube/issues/1795

**Comment by meZee** [comment]
Ahh thank you, I remember that issue had came up in my search now that you linked it, unfortunately it did not have any mention of this particular problem which happens after a clean install. Problem solved now by the automatic cross-referencing GitHub does!
