### ISSUE TITLE
When removing the support for a resolution, files are not deleted

### ISSUE THREAD

**Issue by pprw** [Chocobozzz/PeerTube#2658]
**What happened?**

I changed the settings of my instance to remove the generation of 240p files.

The files are not removed, so I removed them manually.

Videos continues to offer 240p versions, which now fails to launch because there are no files behind.

**What do you expect to happen instead?**

Maybe an option when removing the support of a resolution which proposes to remove related files and update database accordingly.

P-S: How can I rebuild ma database and don't anymore have the 240p choice in videos?

**Comment by Chocobozzz** [comment]
The transcoding settings take effect for future uploads. We could create a CLI to cleanup video resolutions, though

**Comment by jondavid-schober-sp** [comment]
+1 this.

I'm not sure how this happened, but I think I imported a youtube video that was at 1080p, then my peertube instance transcoded it into lower resolutions, but kept a 1080p copy. It's a rather large video, so I'd like to consider removing the 1080p copy, but it doesn't look like thats an option, unless I start mucking in the database

**Comment by prolibre** [comment]
> 
> 
> The transcoding settings take effect for future uploads. We could create a CLI to cleanup video resolutions, though
+1
I am very interested. To free up some disk space it would be nice to be able to delete a video format (with all the old transcodings).

**Comment by SimplyCorbett** [comment]
I'd also love to see the ability to restrict resolutions in general.

Example: Super popular video just came out and is hammering my instance. Dynamically let the admin set the video resolution to a max of 720p instead of 4k.

Example: Guests can only view a maximum of 720p. Members/users can view 1440p.

**Comment by Chocobozzz** [comment]
Hello,

With https://github.com/Chocobozzz/PeerTube/commit/1bb4c9ab2e8b3b3022351b33a82a5e527fa5d4d7 you can now delete manually video files in admin
