### ISSUE TITLE
Creating an account is way too complicated

### ISSUE THREAD

**Issue by rubyFeedback** [Chocobozzz/PeerTube#2659]
Guys, I just tried to create a new account but I don't UNDERSTAND the setup.

Can't you guys just at the least offer a SIMPLE way to create an account?

Right now we have to read a gazillion uninteresting stuff, click on weird things
to fine tune shit etc... and it is annoying.

What ever happened to simplicity? When was it lost?

I think a simple HTML form should be added, KEEP IT SIMPLE, anything
that I can add lateron, I could do via settings/options/preferences, but
I am just not inclined to want to go through a gazillion pages and read all
the stuff there. 

I am all in favour of finding alternatives to Google's barbaric monopoly, 
but the create-account thing is waaaaaaaaaaaaaaaaay too complicated.

Who designed this? Can we get someone who likes simplicity instead?

Please. Then I can actually create an account too.

Literally writing the above took LESS time than trying to UNDERSTAND
that create-an-account page at peertube!

**Comment by pprw** [comment]
I suppose you are talking about the root (administrator) account.

You can generate a new password with: 

`$ cd /var/www/peertube/peertube-latest && NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run reset-password -- -u root`

(as indicated in [the production guide](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md))

Then, after restarting peertube, you can connect with the password and "root" as login. This last part could be more described in the doc (I had to guess myself "root" was the login).

**Comment by rigelk** [comment]
@rubyFeedback could you describe with screenshots the parts of the interface that proved too complicated, or felt out of place ?
