### ISSUE TITLE
Add API endpoint to get instance version

### ISSUE THREAD

**Issue by tcitworld** [Chocobozzz/PeerTube#266]
`/version` ?
Or a more general `/stats` or `metadata` ?

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/915c5bbe538769b1d3430b27817d6a861c766ef3

Only fetch the version and not the git tag (would be more precise). 
See https://github.com/Chocobozzz/PeerTube/issues/202 for the exact version.
