### ISSUE TITLE
Deleted comments and unlisted videos' commets show in syndication feeds

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2663]
**What happened?**

I found 2 bugs with the video-comments feed.

The RSS comments feed (your_instance/feeds/video-comments.xml?sort=-publishedAt) show comments for unlisted videos. And so we can find them.

And when a comment is deleted, it still appears in this feed.

**What do you expect to happen instead?**

Unlisted videos' comments should not appear in RSS feeds.
Deleted comments should not appear in the feed.

**Additional information**
* PeerTube version or URL: 2.1.1

**Comment by rigelk** [comment]
Please use an issue title actually representative of the problems, not a generic one.

**Comment by Chocobozzz** [comment]
Thanks for the issue. Fixed in https://github.com/Chocobozzz/PeerTube/commit/68b6fd21b19ef17274e84dbb21ad7cfb7bc6c36a
