### ISSUE TITLE
Disable comments

### ISSUE THREAD

**Issue by pprw** [Chocobozzz/PeerTube#2664]
If it possible to disable comments for an user or an instance?

I think you can only do it per video. Am I right?

**Comment by Chocobozzz** [comment]
Yes using a peertube plugin:
 * Either by filtering the parameters (and set `commentsEnabled` to `false) when peertube creates/updates the video
 * Or by hiding the comment block section

**Comment by kosssi** [comment]
@Chocobozzz I don't understand how I can disable comments on a peertube instance, which plugin I should install?

**Comment by Chocobozzz** [comment]
Comment policy must be set per video. You can also set the default policy for new videos in the web admin configuration.
