### ISSUE TITLE
Add links to menu

### ISSUE THREAD

**Issue by pprw** [Chocobozzz/PeerTube#2665]
Sorry it is not a bug but an question and maybe a feature request. If there is a better place to put this kind of question, I can move it.

I am wondering what is the best way to insert some custom links in the left menu. By "custom links" I mean for example a link to all videos corresponding to a tag, a link to a specific channel or playlist, etc.

If you host a thematic instance, you could want this kind of "content management". And the left menu is quite empty for visitor.

To be upgrade independent, I am tempted to inject javascript using /admin/config/edit-custom. I am little bit concerned with security issues and limits of this method. 

Maybe someone tried this before? Is there some code available? What would you advice be?

**Comment by rigelk** [comment]
I've seen instances modify this, potentially via a theme/plugin though I haven't seen the code. 

Security concerns are no different from that of Angular.

**Comment by pprw** [comment]
We injected some code inside /admin/config/edit-custom.

I paste it below for the ones interested. It is not the best way to do it. The links added are not very reactive because the whole page is loaded before (test it at https://videos.ahp-numerique.fr). And if you use another theme than the default one, you will see briefly the default theme when clicking.

A plugin would be better.


Javascript field:
```
var firstLink= document.querySelectorAll("a[href='/videos/overview']");

//Parent node which contains 'Videos' title and the 3 links ('Découvrir', 'Tendances', 'Récemment ajoutées')
var parentNode = firstLink[0].parentNode;

//Adding a separator
var separator = document.createElement("hr");
separator.setAttribute('width', '80%');
separator.setAttribute('color', 'white');
separator.setAttribute('background-color', 'white');
separator.setAttribute('height', '1px');
separator.setAttribute('visible', 'true');

//Adding a new link 'Grandes conférences'
var confLink = firstLink[0].cloneNode();
confLink .setAttribute('href','video-channels/grandesconferences/videos');
confLink .setAttribute('routerlink','video-channels/grandesconferences/videos');
confLink .innerHTML = "Grandes conférences";

//Adding a new link 'Colloques et journées d'études'
var colloqueLink= firstLink[0].cloneNode();
colloqueLink.setAttribute('href','video-channels/colloques/videos-playlists');
colloqueLink.setAttribute('routerlink','video-channels/colloques/videos-playlists');
colloqueLink.innerHTML = "Colloques";

//Adding a new link 'Documentaires'
var filmLink= firstLink[0].cloneNode();
filmLink.setAttribute('href','video-channels/films/videos');
filmLink.setAttribute('routerlink','video-channels/films/videos');
filmLink.innerHTML = "Documentaires";

//Adding a new link 'La philo en petits morceaux'
var lpepmLink= firstLink[0].cloneNode();
lpepmLink.setAttribute('href','video-channels/laphiloenpetitsmorceaux/videos');
lpepmLink.setAttribute('routerlink','video-channels/laphiloenpetitsmorceaux/videos');
lpepmLink.innerHTML = "La philo en petits morceaux";

//Adding a new link 'OLKi'
var olkiLink= firstLink[0].cloneNode();
olkiLink.setAttribute('href','video-channels/projet_olki/videos');
olkiLink.setAttribute('routerlink','video-channels/projet_olki/videos');
olkiLink.innerHTML = "Projet OLKi";

//Add links to parent node
parentNode.appendChild(separator);
parentNode.appendChild(confLink);
parentNode.appendChild(colloqueLink);
parentNode.appendChild(filmLink);
parentNode.appendChild(lpepmLink);
parentNode.appendChild(olkiLink);

```
css field:

```
hr {
background-color: #ccc !important;
}
```
Result:

![image](https://user-images.githubusercontent.com/5262986/79969739-335c4c80-8492-11ea-8c95-0c2758821a7a.png)

**Comment by dhk2** [comment]
https://github.com/McFlat/peertube-plugin-custom-links seems to provide the requested functionality

**Comment by kontrollanten** [comment]
If we're looking for a long term solution for this, could it be solved by a client hook like something below? Then I can see if I've time to implement that.

```
registerHook({
  target: 'filter:top-menu',
  handler: (items) => {
    return [
      ...items.filter(item => item.key !== 'in-my-library'),  // Remove the "In my library" block
      {
        key: 'categories',
        title: 'Our categories',
        children: [
          {
            key: 'science-and-technology',
            title: 'Science and technology',
            href: 'https://science-and-tech.com',
          },
        ],
      },
    ];
  },
});
```

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/8beea2d37d90e9a12d895f4a9eebc1e532313d8c

We can extend the system for raw HTML/external links in the future.

**Comment by Nalem14** [comment]
> We injected some code inside /admin/config/edit-custom.
> 
> **EDIT: the code needs to be adapted for peertube v3.**
> 
> I paste it below for the ones interested. It is not the best way to do it. The links added are not very reactive because the whole page is loaded before (~test it at https://videos.ahp-numerique.fr~). And if you use another theme than the default one, you will see briefly the default theme when clicking.
> 
> A plugin would be better.
> 
> Javascript field:
> 
> ```
> var firstLink= document.querySelectorAll("a[href='/videos/overview']");
> 
> //Parent node which contains 'Videos' title and the 3 links ('Découvrir', 'Tendances', 'Récemment ajoutées')
> var parentNode = firstLink[0].parentNode;
> 
> //Adding a separator
> var separator = document.createElement("hr");
> separator.setAttribute('width', '80%');
> separator.setAttribute('color', 'white');
> separator.setAttribute('background-color', 'white');
> separator.setAttribute('height', '1px');
> separator.setAttribute('visible', 'true');
> 
> //Adding a new link 'Grandes conférences'
> var confLink = firstLink[0].cloneNode();
> confLink .setAttribute('href','video-channels/grandesconferences/videos');
> confLink .setAttribute('routerlink','video-channels/grandesconferences/videos');
> confLink .innerHTML = "Grandes conférences";
> 
> //Adding a new link 'Colloques et journées d'études'
> var colloqueLink= firstLink[0].cloneNode();
> colloqueLink.setAttribute('href','video-channels/colloques/videos-playlists');
> colloqueLink.setAttribute('routerlink','video-channels/colloques/videos-playlists');
> colloqueLink.innerHTML = "Colloques";
> 
> //Adding a new link 'Documentaires'
> var filmLink= firstLink[0].cloneNode();
> filmLink.setAttribute('href','video-channels/films/videos');
> filmLink.setAttribute('routerlink','video-channels/films/videos');
> filmLink.innerHTML = "Documentaires";
> 
> //Adding a new link 'La philo en petits morceaux'
> var lpepmLink= firstLink[0].cloneNode();
> lpepmLink.setAttribute('href','video-channels/laphiloenpetitsmorceaux/videos');
> lpepmLink.setAttribute('routerlink','video-channels/laphiloenpetitsmorceaux/videos');
> lpepmLink.innerHTML = "La philo en petits morceaux";
> 
> //Adding a new link 'OLKi'
> var olkiLink= firstLink[0].cloneNode();
> olkiLink.setAttribute('href','video-channels/projet_olki/videos');
> olkiLink.setAttribute('routerlink','video-channels/projet_olki/videos');
> olkiLink.innerHTML = "Projet OLKi";
> 
> //Add links to parent node
> parentNode.appendChild(separator);
> parentNode.appendChild(confLink);
> parentNode.appendChild(colloqueLink);
> parentNode.appendChild(filmLink);
> parentNode.appendChild(lpepmLink);
> parentNode.appendChild(olkiLink);
> ```
> 
> css field:
> 
> ```
> hr {
> background-color: #ccc !important;
> }
> ```
> 
> Result:
> 
> ![image](https://user-images.githubusercontent.com/5262986/79969739-335c4c80-8492-11ea-8c95-0c2758821a7a.png)

Hey, because available plugins don't fit with my need, I have searched solutions bot only found this code, simple and powerful.

I have adapted, improved and updated it to fit with v4.x. I share you it so.

Image result:
<img width="259" alt="image" src="https://user-images.githubusercontent.com/1911357/169441692-20ea0eeb-472b-4a3f-aaef-60f287519c10.png">


````

/** === LINKS ===
 * Simple add your links into the MENU_LINKS array following the example format
 * It will be added to the menu in the same order as you defined it
 */

/** === SEPARATOR ===
 * Like our example, use {name: "separator"} to add a separator to the menu
 */

/** === ICONS ===
 * You can use https://css.gg, icons are automatically imported if start with gg-*** (Ex: gg-game).
 * Else, you can use https://fontawesome.com/icons/ or any other custom icon library.
 * Just import the CSS manually.
 **/

// EDIT HERE
var MENU_LINKS = [
    {
        name: "Gaming",
        url: "/videos/recently-added?languageOneOf=fr&categoryOneOf=7&c=true&s=2",
        icon: "gg-games",
    },
    {
        name: "Kid's",
        url: "/videos/recently-added?languageOneOf=fr&categoryOneOf=17&c=true&s=2",
        icon: "gg-girl",
    },
    { name: "separator" },
    {
        name: "Pewtix - Dicutez de l\'actualité",
        url: "https://pewtix.com/",
        target: "_blank",
        icon: "gg-twitter"
    },
    {
        name: "Pixel - Partagez vos photos",
        url: "https://pixel.orion-hub.fr/",
        target: "_blank",
        icon: "gg-instagram"
    },
    { name: "separator" },
    {
        name: "Liberapay - Faire un Don",
        url: "https://liberapay.com/bthommy/",
        target: "_blank",
        icon: "gg-coffee"
    }
]

// END EDIT -- DO NOT TOUCH AFTER

/**
 * Wait for the DOM to be loaded
 * Then, init the custom menu
 */
window.addEventListener("DOMContentLoaded", (event) => {
    const wait__menuCustomInterval = setInterval(() => {
        let firstLink = document.querySelectorAll(
            '.menu-block a[href="/videos/overview"]'
        );
        if (firstLink.length > 0) {
            clearInterval(wait__menuCustomInterval);
            initCustomMenu(firstLink[0]);
        }
    }, 500);
});

/**
 * Init the custom menu
 * @param {HTMLElement} firstLink The first link of the menu
 * @returns {void}
 */
function initCustomMenu(linkTemplate) {
    //Parent node which contains 'Videos' title and the 3 links ('Découvrir', 'Tendances', 'Récemment ajoutées')
    const menuContainer = linkTemplate.parentNode;
    // Define head element
    const head = document.head;

    // Define and ADD custom CSS
    const customCSS = `
        hr {
          background-color: #ccc !important;
        }
        
        a.menu-link i {
          margin-right: 16px;
        }
    `;
    const style = document.createElement("style");
    style.type = "text/css";
    style.appendChild(document.createTextNode(customCSS));
    head.appendChild(style);

    // Define separator
    const separator = document.createElement("hr");
    separator.setAttribute("width", "80%");
    separator.setAttribute("color", "white");
    separator.setAttribute("background-color", "white");
    separator.setAttribute("height", "1px");
    separator.setAttribute("visible", "true");

    //Adding links
    MENU_LINKS.forEach((link) => {
        if (link.name === "separator") {
            // Adding separator
            menuContainer.appendChild(separator.cloneNode());
        } else {
            // Adding link

            // Manage icon (automatically import if start with gg-*** from https://css.gg)
            let icon = "";
            if (link.icon.startsWith("gg-")) {
                icon = `<i class="${link.icon}"></i>`;
                const ggName = link.icon.replace("gg-", "");

                // Inject css in the head
                const cssLink = document.createElement("link");
                cssLink.type = "text/css";
                cssLink.rel = "stylesheet";
                cssLink.href = `https://css.gg/${ggName}.css`;
                head.appendChild(cssLink);
            } else {
                icon = `<i class="${link.icon}"></i>`;
            }

            // Create link
            const linkNode = linkTemplate.cloneNode();
            linkNode.setAttribute("href", link.url);
            linkNode.setAttribute("routerLink", link.url);
            linkNode.setAttribute("target", (link.target || "_self"));
            linkNode.innerHTML = icon + " " + link.name;

            // Add link to the menu
            menuContainer.appendChild(linkNode);
        }
    });
}

````
