### ISSUE TITLE
Some videos do not start

### ISSUE THREAD

**Issue by fluxie38** [Chocobozzz/PeerTube#2667]
**What happened?**
I've recently created a Peertube instance. It worked fine until a few days ago when I uploaded a new video. When I click on this video, I get a spinning wheel which lasts forever. 
Note that it only happens with some videos.

It seems that I can get the video to start by clicking on the time curser or dragging it back. 
(Sometimes it causes the window to freeze and even the server to hang; I have to wait a while and then open a new tab. At other times I can play the other videos (except for one other maybe)).

It's infuriating. I have spent days on this. 
Your help would be much appreciated. Maybe I incorrectly set something somewhere ?

I do not believe it is related to the browser autoplay feature because the sound is on and I have played with these settings to no avail.
I have tried Firefox 60.0.1 and Chromium 65 on Ubuntu 14.04, Chrome on Windows 8.
The problem does not occur on a Samsung S6 phone with the Samsung browser !
It does **not** occur when I load the file directly in a browser (on anoter pc) from the local disk with file:///...
I don't think it is a bandwidth problem (by looking at the performance console the video seems to have loaded and it I also get the spinning wheel if I click on it again after viewing it once).
It does **not** occur when I load the same video from a photo server (Lychee).

**What do you expect to happen instead?**
The video to play like the others.

**Steps to reproduce:**

1. Go to swigif.biz.st

2. Click on the video "ski-down"

3. Enjoy (or cry)

**Additional information**
* PeerTube version or URL: swigif.biz.st
* Browser name/version: Firefox 60.0.1 and Chromium 65 on Ubuntu 14.04
* NodeJS version: v10.20.0

**Server log (journalctl):**
_Video_ _that_ _works :_
Apr 20 20:39:22 pud peertube[4293]: [swigif.biz.st:443] 2020-04-20 20:39:22.883 info: 89.3.0.0 - - [20/Apr/2020:18:39:22 +0000] "GET /api/v1/videos/d2c1912f-fb41-4537-af80-e23bc24e11bc/captions HTTP/1.0" 304 - "https://swigif.biz.st/videos/watch/d2c1912f-fb41-4537-af80-e23bc24e11bc" "Firefox"
Apr 20 20:39:22 pud peertube[4293]: [swigif.biz.st:443] 2020-04-20 20:39:22.920 info: 89.3.0.0 - - [20/Apr/2020:18:39:22 +0000] "GET /api/v1/videos/d2c1912f-fb41-4537-af80-e23bc24e11bc HTTP/1.0" 304 - "https://swigif.biz.st/videos/watch/d2c1912f-fb41-4537-af80-e23bc24e11bc" "Firefox"
Apr 20 20:39:23 pud peertube[4293]: [swigif.biz.st:443] 2020-04-20 20:39:23.029 info: 89.3.0.0 - - [20/Apr/2020:18:39:23 +0000] "GET /api/v1/videos/?start=0&count=6&sort=-createdAt HTTP/1.0" 304 - "https://swigif.biz.st/videos/watch/d2c1912f-fb41-4537-af80-e23bc24e11bc" "Firefox"
Apr 20 20:39:23 pud peertube[4293]: [swigif.biz.st:443] 2020-04-20 20:39:23.043 info: 89.3.0.0 - - [20/Apr/2020:18:39:23 +0000] "GET /api/v1/videos/7/comment-threads?start=0&count=10&sort=-createdAt HTTP/1.0" 304 - "https://swigif.biz.st/videos/watch/d2c1912f-fb41-4537-af80-e23bc24e11bc" "Firefox"
Apr 20 20:39:23 pud peertube[4293]: [swigif.biz.st:443] 2020-04-20 20:39:23.265 info: 89.3.0.0 - - [20/Apr/2020:18:39:23 +0000] "GET /static/torrents/d2c1912f-fb41-4537-af80-e23bc24e11bc-720.torrent HTTP/1.0" 304 - "https://swigif.biz.st/videos/watch/d2c1912f-fb41-4537-af80-e23bc24e11bc" "Other"
Apr 20 20:39:39 pud peertube[4293]: [swigif.biz.st:443] 2020-04-20 20:39:39.303 info: 89.3.0.0 - - [20/Apr/2020:18:39:39 +0000] "POST /api/v1/videos/d2c1912f-fb41-4537-af80-e23bc24e11bc/views HTTP/1.0" 204 - "https://swigif.biz.st/videos/watch/d2c1912f-fb41-4537-af80-e23bc24e11bc" "Firefox"

_Video_ _that_ _does_ _not_ _work :_ 
Apr 20 20:40:42 pud peertube[4293]: [swigif.biz.st:443] 2020-04-20 20:40:42.694 info: 89.3.0.0 - - [20/Apr/2020:18:40:42 +0000] "GET /api/v1/videos/f846b8f8-3fa5-46b5-b6aa-5ccec5f13cab/captions HTTP/1.0" 304 - "https://swigif.biz.st/videos/watch/f846b8f8-3fa5-46b5-b6aa-5ccec5f13cab" "Firefox"
Apr 20 20:40:42 pud peertube[4293]: [swigif.biz.st:443] 2020-04-20 20:40:42.724 info: 89.3.0.0 - - [20/Apr/2020:18:40:42 +0000] "GET /api/v1/videos/f846b8f8-3fa5-46b5-b6aa-5ccec5f13cab HTTP/1.0" 304 - "https://swigif.biz.st/videos/watch/f846b8f8-3fa5-46b5-b6aa-5ccec5f13cab" "Firefox"
Apr 20 20:40:42 pud peertube[4293]: [swigif.biz.st:443] 2020-04-20 20:40:42.814 info: 89.3.0.0 - - [20/Apr/2020:18:40:42 +0000] "GET /api/v1/videos/?start=0&count=6&sort=-createdAt HTTP/1.0" 304 - "https://swigif.biz.st/videos/watch/f846b8f8-3fa5-46b5-b6aa-5ccec5f13cab" "Firefox"
Apr 20 20:40:42 pud peertube[4293]: [swigif.biz.st:443] 2020-04-20 20:40:42.819 info: 89.3.0.0 - - [20/Apr/2020:18:40:42 +0000] "GET /api/v1/videos/10/comment-threads?start=0&count=10&sort=-createdAt HTTP/1.0" 304 - "https://swigif.biz.st/videos/watch/f846b8f8-3fa5-46b5-b6aa-5ccec5f13cab" "Firefox"
Apr 20 20:40:43 pud peertube[4293]: [swigif.biz.st:443] 2020-04-20 20:40:43.040 info: 89.3.0.0 - - [20/Apr/2020:18:40:43 +0000] "GET /static/torrents/f846b8f8-3fa5-46b5-b6aa-5ccec5f13cab-368.torrent HTTP/1.0" 304 - "https://swigif.biz.st/videos/watch/f846b8f8-3fa5-46b5-b6aa-5ccec5f13cab" "Other"

**Comment by Chocobozzz** [comment]
Our webtorrent have some bugs with small videos. 

Try to enable HLS in admin, and reupload your video.

**Comment by fluxie38** [comment]
It seems to have corrected the problem ! Thank you. 

Should I use HLS all the time then ? Or only for small videos ?
You do say that if webtorrent is enabled it doubles the disk space ?

**Comment by rigelk** [comment]
Yes, if you leave WebTorrent enabled then your store twice the file: once for WebTorrent and one for HLS.

HLS generally performs better, and from our point of view has a higher quality ecosystem than WebTorrent. It solves known issues related to seeking for long videos too, so either too small or two large are sweet spots for HLS.
