### ISSUE TITLE
Ability to show video updates from my subscription list

### ISSUE THREAD

**Issue by rosariotech** [Chocobozzz/PeerTube#2668]
I searched through the issues and didn't find this. Today Peertube instances just show what channels I'm subscribed. I didn't find a way to show video updates from my subscription list and only from that.

It believe it would be a good thing. Because there's no sense if I have an account and subscribed some channel and it gets me no priority updates nor anything.

Don't know If I did be clear, but if it is irrelevant, you can delete.

**Comment by Chocobozzz** [comment]
I'm not sure to understand. In the menu in `My library` section, `Subscriptions` entry shows videos from your subscriptions

**Comment by rosariotech** [comment]
Oh sorry. That's what I was looking for. My bad!
