### ISSUE TITLE
Mastodon likes are not forwarded 

### ISSUE THREAD

**Issue by Booteille** [Chocobozzz/PeerTube#2679]
Actually, likes/dislikes seem to be instance bound.

As an illustration, look at both screenshots:

**video.ploud.fr:**
![Ploud's instance](https://user-images.githubusercontent.com/2203721/80265234-3c6a3b00-8697-11ea-8838-3d80e5c5a9ca.png)
**peertube.datagueule.fr**
![Datagueule's instance](https://user-images.githubusercontent.com/2203721/80265254-4b50ed80-8697-11ea-9b70-38f333eb4d3b.png)

On the first screenshot, I am watching a video on the `video.ploud.fr` instance. The video has **7** likes.

On the second screenshot, I am watching the same video directly on `peertube.datagueule.fr` and the video now shows **26** likes.

I propose to have a global counter for every instance. It would help to increase the feeling to be a part of the network when watching videos from a small instance.

**Comment by Chocobozzz** [comment]
Likes/dislikes are federated. But it seems the origin instance does not correctly forward rates from mastodon instances. I'll investigate.

**Comment by Chocobozzz** [comment]
Closing since we cannot do anything here. Please subscribe to the mastodon issue instead
