### ISSUE TITLE
Videos uploaded by CLI are publicly available before transcoding

### ISSUE THREAD

**Issue by pprw** [Chocobozzz/PeerTube#2681]
Videos uploaded by CLI are publicly available before transcoding despite absence of option ` --no-wait-transcoding`.

I uploaded video using command:

    peertube up -C channel -t tag -f /home/user/../file.mp4 -n "name"

Just after uploading, I can see this video is online for visitors without being available in all resolutions I selected. It should be online only after complete transcoding.

Also, there is no the warning about video maybe not working properly I have by uploading with the web interface.

Upload script has an `-P` option `-P, --privacy <privacy_number>` but privacy_number is not documented.

**Comment by Chocobozzz** [comment]
Please paste the URL of the uploaded video

**Comment by pprw** [comment]
So, I just upload [this video](https://videos.ahp-numerique.fr/videos/watch/6e76fe5c-d654-40e1-800d-25abee70869f) using this command:

`peertube  up -f /home/user/../file.mp4 -C channel -n "title"`

If you visit the link soon enough, you will see the video is publicly available even if all resolutions (I selected all resolutions transcoding in my config) are not yet available. Currently it is only in 464p original resolution.

**Comment by pprw** [comment]
Maybe it is just me mistaking: is the video is meant to be available after "optimizing" but before transcoding in other resolution? 

If yes, there is no bug.

**Comment by Chocobozzz** [comment]
> So, I just upload this video using this command:

The `waitTranscoding` flag is correctly set: https://videos.ahp-numerique.fr/api/v1/videos/6e76fe5c-d654-40e1-800d-25abee70869f

> Maybe it is just me mistaking: is the video is meant to be available after "optimizing" but before transcoding in other resolution?

Yes, the video is published after the transcoding in another resolution (so there are already 2 resolutions for the video when it is published).
