### ISSUE TITLE
Background videojs playing on Android

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#2683]
In my experience it's a feature far more asked than a PiP support.
It seems it does not work on the actual v2.1 of PeerTube once the phone screen is sleeping.

Do you know if it's easy to implement ?

**Comment by JohnXLivingston** [comment]
Which browser do you use?

**Comment by kimsible** [comment]
> Which browser do you use?

@JohnXLivingston Firefox Beta channel, the sound actually cut after 5~10 seconds of sleeping.

**Comment by kimsible** [comment]
It's working depending of the browser by activating in the system settings app info of the browser : 

-  **Firefox** (v68) : App Info > Advanced > Modify system settings > Allow modify system settings
But for a reason I missed that option disapears on the Firefox beta channel, so it does not work anymore..., maybe a disabled feature only for the beta channel ?

<div>
<img width=49% alt=signal-attachment-2020-04-26-134050_002 src=https://user-images.githubusercontent.com/1877318/80306684-13e05f00-87c5-11ea-84a6-f6ac549b1fdd.png />
<img width=49% alt=signal-attachment-2020-04-26-134050_001 src=https://user-images.githubusercontent.com/1877318/80306683-1347c880-87c5-11ea-9ac6-5a9b53b360a4.png />
</div>

- **Chrome** :   App Info > Data Usage > Background Data (Enabled)
With chrome, there is a weird effect : we first need to minimize chrome and play again the with the player control in the chrome notification system, after that we can sleep the phone and listen.

<div>
<img width=49% alt=signal-attachment-2020-04-26-134050_003 src=https://user-images.githubusercontent.com/1877318/80306685-1478f580-87c5-11ea-9d23-9d269a0059aa.png />
<img width=49% alt=signal-attachment-2020-04-26-134050_004 src=https://user-images.githubusercontent.com/1877318/80306686-1478f580-87c5-11ea-9d11-d652e4aa75c6.png />
</div>

**Comment by Chocobozzz** [comment]
I'm not sure to know what we can do on peertube side

**Comment by Chocobozzz** [comment]
Seems to work on Firefox nightly

**Comment by kimsible** [comment]
> I'm not sure to know what we can do on peertube side

Yes, but I thought opening this issue was good to help community, maybe I should have opened it on the Framasoft forum.
