### ISSUE TITLE
understanding peertube load sharing between instances

### ISSUE THREAD

**Issue by Musadiqraees** [Chocobozzz/PeerTube#2684]
I have made two instances peetube1 and peetube2
Peertube2 follows peertube1 and with redundancy enabled .
I have uploaded video A on Peertube1. It appears in videos folder of peertube1 and redundancy folder of peertube2. **I am trying to download videoA with torrent file with cli or torrent client.**

Question : I was assuming that both instances will share network load  but i only see traffic from peertube1 (which actually host video). Peertube2 dont share network load. 
Is this normal or both should share videos.

**Comment by Chocobozzz** [comment]
Try to use the magnet link instead, that includes webseeds of instances that duplicated your videos.

**Comment by Musadiqraees** [comment]
peertube instance os : ubuntu 
tool for monitoring: vnstat -l
tool for downloading magnet link : Vuze

**Expected Outcome: peer instances should share network load  
result: traffic is only shown in Peertube3 (file hosting instance)**

**Peertube3 (file hosting instance)**
"
**ubuntu@peertube3:~$ vnstat -l**
Monitoring ens3... 
                           rx         |       tx
--------------------------------------+------------------
  bytes                    16.94 MiB  |      501.82 MiB
--------------------------------------+------------------
          max             955 kbit/s  |    27.85 Mbit/s
      average          546.66 kbit/s  |    16.19 Mbit/s
          min               0 kbit/s  |        0 kbit/s
--------------------------------------+------------------
  packets                     258414  |          125920
--------------------------------------+------------------
          max               1740 p/s  |         803 p/s
      average                993 p/s  |         484 p/s
          min                  0 p/s  |           0 p/s
--------------------------------------+------------------
"

**Peertube4 (following instance)**

**ubuntu@peertube4:/peertube$ vnstat -l**
Monitoring ens3... 
                       rx         |       tx
--------------------------------------+------------------
  bytes                       94 KiB  |          46 KiB
--------------------------------------+------------------
          max             275 kbit/s  |       13 kbit/s
      average            2.69 kbit/s  |     1.33 kbit/s
          min               0 kbit/s  |        0 kbit/s
--------------------------------------+------------------
  packets                        334  |             285
--------------------------------------+------------------
          max                 15 p/s  |          14 p/s
      average                  1 p/s  |           0 p/s
          min                  0 p/s  |           0 p/s
--------------------------------------+------------------
  time                  4.77 minutes

**Comment by Chocobozzz** [comment]
Paste the magnet link so I can check if peertube4 was correctly added.

**Comment by Musadiqraees** [comment]
Dear @Chocobozzz ,Please have a look at it and kindly guide me

"magnetUri": "magnet:?xs=https%3A%2F%2Fpeertube3.cit.local%2Fstatic%2Ftorrents%2F90128185-f07c-49c0-abd1-ed6bcf988486-720.torrent&xt=urn:btih:f5f2c553d55a4e36a69aa42c4cd0989d1e8c8076&dn=1+Hour+Burning+Logs+in+Fireplace+(in+HD)&tr=wss%3A%2F%2Fpeertube3.cit.local%3A443%2Ftracker%2Fsocket&tr=https%3A%2F%2Fpeertube3.cit.local%2Ftracker%2Fannounce&ws=https%3A%2F%2Fpeertube3.cit.local%2Fstatic%2Fwebseed%2F90128185-f07c-49c0-abd1-ed6bcf988486-720.mp4&ws=https%3A%2F%2Fpeertube4.cit.local%2Fstatic%2Fredundancy%2F90128185-f07c-49c0-abd1-ed6bcf988486-720.mp4",

**Comment by Chocobozzz** [comment]
```
{
  "xs": "https://peertube3.cit.local/static/torrents/90128185-f07c-49c0-abd1-ed6bcf988486-720.torrent",
  "xt": "urn:btih:f5f2c553d55a4e36a69aa42c4cd0989d1e8c8076",
  "dn": "1 Hour Burning Logs in Fireplace (in HD)",
  "tr": [
    "https://peertube3.cit.local/tracker/announce",
    "wss://peertube3.cit.local:443/tracker/socket"
  ],
  "ws": [
    "https://peertube3.cit.local/static/webseed/90128185-f07c-49c0-abd1-ed6bcf988486-720.mp4",
    "https://peertube4.cit.local/static/redundancy/90128185-f07c-49c0-abd1-ed6bcf988486-720.mp4"
  ],
  "infoHash": "f5f2c553d55a4e36a69aa42c4cd0989d1e8c8076",
  "name": "1 Hour Burning Logs in Fireplace (in HD)",
  "announce": [
    "https://peertube3.cit.local/tracker/announce",
    "wss://peertube3.cit.local:443/tracker/socket"
  ],
  "urlList": [
    "https://peertube3.cit.local/static/webseed/90128185-f07c-49c0-abd1-ed6bcf988486-720.mp4",
    "https://peertube4.cit.local/static/redundancy/90128185-f07c-49c0-abd1-ed6bcf988486-720.mp4"
  ]
}
```

So the magnet URI is correctly generated

**Comment by Musadiqraees** [comment]
@Chocobozzz thanks for guidance , network sharing only works only with magnet uri and if client fetch data with webtorrent . normal torrent client do no behave as expected. 
Conclusion : **Peertube instances shares data**
