### ISSUE TITLE
Player API get/set captions

### ISSUE THREAD

**Issue by YohannLYD** [Chocobozzz/PeerTube#2685]
Would it be possible to add a method like getCaptions/setCaptions for the player embed API the same way we can change the resolution or the playback rate ?

Thanks !

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/1151f5210c0e7665ec6714e73261f299e6fe757b. Will be available in PeerTube 2.2.
