### ISSUE TITLE
Playlist description does not allow more than 251 characters

### ISSUE THREAD

**Issue by pprw** [Chocobozzz/PeerTube#2687]
On  2.1.1 version, I cannot enter a playlist description if the text exceed 251 characters
If I have more characters, I have a error message `Server error. Please retry later.`

**Comment by pprw** [comment]
Were you able to reproduce or it is particular to my installation?

**Comment by rigelk** [comment]
@pprw this is always welcome :wink:

**Comment by Chocobozzz** [comment]
Thanks for the issue. Fixed in https://github.com/Chocobozzz/PeerTube/commit/4c576aca1cb8652d88f6673f1d870b53654058d5
