### ISSUE TITLE
add to home screen (A2HS) feature 

### ISSUE THREAD

**Issue by valvin1** [Chocobozzz/PeerTube#269]
This is a feature request in order to have the possibility to add to home screen a peertube website on mobile devices. 

Exact name is [A2HS](https://developer.mozilla.org/en-US/Apps/Progressive/Add_to_home_screen).

Thanks to this it launches the website almost like an app and can be available directly on the homescreen.

This feature is now implemented on Firefox although Chrome implemented for a moment. 

If I've well understood it requires to write a `manifest.webmanifest` which seems simple.

**Comment by rigelk** [comment]
If I read correctly the requirements, we need a manifest and an icon to get started with Firefox support.

Chrome is a bit trickier. They require a [service worker](https://developers.google.com/web/fundamentals/primers/service-workers/), though. They also relie on vague criteria:

> a site engagement heuristic defined by Chrome (this is regularly being changed).

> The criteria for displaying app install banners may change in the future. See [What, Exactly, Makes Something a Progressive Web App?](https://infrequently.org/2016/09/what-exactly-makes-something-a-progressive-web-app/) for a canonical reference.

As for the manifest:

```json
{
  "background_color": "gray",
  "description": "a federated decentralized video streaming platform",
  "display": "fullscreen",
  "icons": [
    {
      "src": "<path>/peertube-icon.png",
      "sizes": "192x192",
      "type": "image/png"
    }
  ],
  "name": "PeerTube",
  "short_name": "PeerTube",
  "start_url": "/videos/recently-added"
}
```

I don't know about the icon/icon path.

**Comment by lucaspontoexe** [comment]
This would only require to have some different icon sizes specified in the manifest file. Something like this:

"icons":  [

    {
      "src": "<path>/peertube-icon-192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "<path>/peertube-icon-256.png",
      "sizes": "256x256",
      "type": "image/png"
    },
    {
      "src": "<path>/peertube-icon-ETC.png",
      "sizes": "ETCxETC",
      "type": "image/png"
    }
]

Then add to the main page HTML code:
`<link rel="manifest" href="/manifest.webmanifest">`

**Comment by lucaspontoexe** [comment]
Well, I couldn't figure out the icon path, since I'm having some problems to get the dev client running.
Also, check out #273.

**Comment by MamounElAlaoui** [comment]
I use [https://realfavicongenerator.net/](this generator) to create my manifest and my icons for all the navigators and mobile plateforms.

Also, without the service workers, a PWA is just a link. We should create a service worker file (that works fine with angular) at least to allow the app to be used offline for the main pages and then see how we want to work with the backend.

**Comment by Chocobozzz** [comment]
@lucaspontoexe If you have issues with running the client, do not hesitate to report an issue so I can help.

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/9ccf111912cae2a345d8ca0cf412703e59d19cf8 https://github.com/Chocobozzz/PeerTube/commit/6583edee61b3e2726c5209b6da311d758088d619 https://github.com/Chocobozzz/PeerTube/commit/5980a252a7f71e3e79a1b7ca39a63eb4dbfca9e4 https://github.com/Chocobozzz/PeerTube/commit/151edeee3a1bff047bda4cdb60d98ad74f627488 https://github.com/Chocobozzz/PeerTube/commit/7193ad1044d2dfad8f929f0951f9a3601c056f67 

Thanks @lucaspontoexe

**Comment by valvin1** [comment]
i've justed upgraded my instance today and tested the feature and it works well :)

thank you ! :)

**Comment by Githubuxer** [comment]
Has anyone confirmed this working in Safari on iOS? It doesn’t seem to create a Peertube icon for the instance I joined. https://www.create.net/support/adding-an-ios-home-screen-icon-for-your-website![image](https://user-images.githubusercontent.com/62911518/86751034-62ec1100-c00c-11ea-98c3-5bec43e543b1.jpeg)
