### ISSUE TITLE
behind apache reverse proxy

### ISSUE THREAD

**Issue by tele81** [Chocobozzz/PeerTube#2690]
hello i run pt on a vm and use an apache reverse proxy for the distribution on the vms.

What settings do I have to make?

**Comment by Chocobozzz** [comment]
Hello,

Sorry but we don't support Apache.

**Comment by tele81** [comment]
OK

I now have nginx.

its an remote proxy for all my vms

can i disable the reverseproxy on the local?

i need instructions for the configuration of the ngnix remote proxy and the local ngnix proxy as well as the changes in the peertube yaml.

**Comment by rigelk** [comment]
@tele81 I don't know what this remote Nginx entails, I don't know how to configure every usage possible of Nginx.

Please follow the production guide and especially the configuration of Nginx via the provided template.

**Comment by tele81** [comment]
ok it works ... but i have an other problem see next question
