### ISSUE TITLE
Discover Page is Empty

### ISSUE THREAD

**Issue by fluxie38** [Chocobozzz/PeerTube#2693]
**What happened?**
Discover page on my instance is empty. Other pages (trending, etc) work fine.

**What do you expect to happen instead?**
I expect to see a list of videos by channel, tag, etc
Question : do I have to activate this page, or do I have to mark videos to get them to appear ?
Or is it automatic ?

**Steps to reproduce:**
1. Go to : https://swigif.biz.st/videos/overview
Any help would be gratefully appreciated.

**Additional information**
PeerTube version : v2.1.1
Browser name/version: Firefox Quantum 61.0.1 32 bit
NodeJS version: v10.20.0

$ sudo journalctl -feu peertube
Apr 28 14:55:23 pud peertube[1423]: [swigif.biz.st:443] 2020-04-28 14:55:23.494 info: 89.3.0.0 - - [28/Apr/2020:12:55:23 +0000] "GET /videos/overview HTTP/1.0" 200 3416 "-" "Firefox"
Apr 28 14:55:23 pud peertube[1423]: [swigif.biz.st:443] 2020-04-28 14:55:23.771 info: 89.3.0.0 - - [28/Apr/2020:12:55:23 +0000] "GET /videos/overview HTTP/1.0" 200 3416 "-" "Firefox"
Apr 28 14:55:25 pud peertube[1423]: [swigif.biz.st:443] 2020-04-28 14:55:25.080 info: 89.3.0.0 - - [28/Apr/2020:12:55:25 +0000] "GET /api/v1/oauth-clients/local HTTP/1.0" 200 99 "https://swigif.biz.st/videos/overview" "Firefox"
Apr 28 14:55:25 pud peertube[1423]: [swigif.biz.st:443] 2020-04-28 14:55:25.084 info: 89.3.0.0 - - [28/Apr/2020:12:55:25 +0000] "GET /api/v1/config/ HTTP/1.0" 200 1370 "https://swigif.biz.st/videos/overview" "Firefox"
Apr 28 14:55:25 pud peertube[1423]: [swigif.biz.st:443] 2020-04-28 14:55:25.162 info: 89.3.0.0 - - [28/Apr/2020:12:55:25 +0000] "GET /api/v1/overviews/videos HTTP/1.0" 200 41 "https://swigif.biz.st/videos/overview" "Firefox"
Apr 28 14:55:29 pud peertube[1423]: [swigif.biz.st:443] 2020-04-28 14:55:29.582 info: 89.3.0.0 - - [28/Apr/2020:12:55:29 +0000] "GET /api/v1/videos/?start=0&count=25&sort=-trending&skipCount=true HTTP/1.0" 304 - "https://swigif.biz.st/videos/trending" "Firefox"

**Comment by Chocobozzz** [comment]
Hello,

The overview page needs at least 6 videos per group (channel/category/tag) to display them: https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/constants.ts#L445
