### ISSUE TITLE
I cant not found templates

### ISSUE THREAD

**Issue by tele81** [Chocobozzz/PeerTube#2696]
i have the actualy version 

but i cant not found that

https://github.com/Chocobozzz/PeerTube/tree/develop/client/src/app/%2Bsignup/%2Bverify-account

**Comment by Chocobozzz** [comment]
I'm sorry I don't understand. If you have an issue, please fill the template.

**Comment by tele81** [comment]
I am looking for this file but it does not exist.

I want to change the email text.

**Comment by Chocobozzz** [comment]
You can't because the release contains only built files
