### ISSUE TITLE
No vertical scroll for left menu on landscape touchscreen

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#2699]
On tablet and mobile, when the orientation is landscape, the left menu is cut and can't be scrolled vertically.

![fixed-menu-portrait-mobile](https://user-images.githubusercontent.com/1877318/80546848-012d7c00-89b7-11ea-8d6e-1a73a2698e66.png)

**Comment by rigelk** [comment]
You mean on the landscape orientation, right?

**Comment by kimsible** [comment]
> You mean on the landscape orientation, right?

Sorry, it's landscape indeed !

**Comment by kimsible** [comment]
Seems the user dropdown is any case will not be fully displayed : 

![fixed-menu-landscape-dropdown-mobile](https://user-images.githubusercontent.com/1877318/80611384-d127bc80-8a3a-11ea-9537-13ad7e8885ee.png)

Maybe, we can force the screen to switch orientation when opening the left menu ?

**Comment by kimsible** [comment]
Seems touchcreens were not supported here : https://github.com/Chocobozzz/PeerTube/blob/62365adc7589a8c6b481659e77adc4bdf693e711/client/src/app/menu/menu.component.scss#L26
https://github.com/Chocobozzz/PeerTube/blob/62365adc7589a8c6b481659e77adc4bdf693e711/client/src/app/menu/menu.component.scss#L27

This could be inject after : 

```js
@media not all and (hover: hover) and (pointer: fine) {
  overflow-y: auto;
}
```
