### ISSUE TITLE
3000 chars max on video explanation

### ISSUE THREAD

**Issue by ReK2Fernandez** [Chocobozzz/PeerTube#270]
Hello I think this is a good settings but in some videos sometimes like us that we do interviews and reviews of hacker conferences and such is impossible to put all the links and such in only 3000 chars considering spaces and such are counted..(or not)  but we should have an option to expand this or reduce on each peertube node..  I got hit by this issue on a video today and was not able to put all the credits after the video links and explanation.

**Comment by Chocobozzz** [comment]
What other limit would be interesting for you?

**Comment by ReK2Fernandez** [comment]
@Chocobozzz Idk, what will be nice is for the node admin to be able to increment or decrement as he wishes, Since people put diff type of videos. Cheers

**Comment by Chocobozzz** [comment]
Fixed. We limit to 10000 characters now. I don't want to put this in the configuration file because I don't want to have too many keys.
