### ISSUE TITLE
PeerTube 2.1.1 incompatibility with Node.js >=13

### ISSUE THREAD

**Issue by tgurr** [Chocobozzz/PeerTube#2700]
**What happened?**
After upgrading Node.js from 13.x to 14.0.0 (future LTS release) PeerTube stopped working.

**What do you expect to happen instead?**
PeerTube working.

**Steps to reproduce:**

1. Upgrade to Node.js 14.x

2. Install/Reinstall PeerTube 2.1.1 (recompile node modules)

3. Restart/Start PeerTube; doesn't work.

PeerTube appeared to start without any error, but it wasn't accessible and I get "502 Bad Gateway" on nginx. Nothing is written to peertube.log or peertube-audit.log.

systemctl status peertube:
```
Apr 29 15:25:25 hostname systemd[1]: Started PeerTube daemon.
Apr 29 15:25:25 hostname peertube[111991]: > peertube@2.1.1 start /var/www/peertube/versions/peertube-v2.1.1
Apr 29 15:25:25 hostname peertube[111991]: > node dist/server
```
I've downgraded Node.js back to 13.13.0 for the time being.

**Additional information**
* PeerTube version or URL: 2.1.1
* Browser name/version: Chromium / 81.0.4044.113
* NodeJS version: 14.0.0

* Link to browser console log if useful: none
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): empty

**Comment by Your-New-SJW-Waifu** [comment]
I run Arch and the same thing happened to me. I had to downgrade node and it went back to working. Although, now I'm having to hold back icu for nodejs so it's starting to become a bit of a game of cards.

**Comment by Chocobozzz** [comment]
Blocked by https://github.com/kwhitley/apicache/issues/189

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/9162476fe9fe022ff24bd42ff828aca7c68129ef
