### ISSUE TITLE
Actor's outbox sorted incorrectly

### ISSUE THREAD

**Issue by koehn** [Chocobozzz/PeerTube#2703]
**What happened?**
Actor's `outbox` items are sorted chronologically ascending.

**What do you expect to happen instead?**
Actor's `outbox` items should be sorted chronologically descending.

**Steps to reproduce:**

1. Query an actor's outbox e.g., https://peertube.koehn.com/accounts/bkoehn/outbox

2. Look at item order

3.

**Additional information**
* PeerTube version or URL: Current (https://peertube.koehn.com uses `chocobozzz/peertube:production-buster`
* Browser name/version: n/a
* NodeJS version: `chocobozzz/peertube:production-buster`

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
> Actor's outbox items should be sorted chronologically descending.

I'm not sure if it really *should*, but that does not hurt and allows some optimizations. Changed in https://github.com/Chocobozzz/PeerTube/commit/7139845894ae24af397989f85350471cc5b91e2a

**Comment by koehn** [comment]
Thank you!
