### ISSUE TITLE
Encoding HLS: video buged

### ISSUE THREAD

**Issue by sachaz** [Chocobozzz/PeerTube#2709]
**What happened?**
I encoded a video in HLS manualy with:
sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run create-transcoding-job -- --generate-hls -v 4f4601fb-8f1a-4a6a-b02e-2b8478d1b79e

**What do you expect to happen instead?**
When I'm launching the video the default one is in very poor quality
When I'm looking at the quality I have 2 video in 1080p the bad (and the ugly), the good 
How can I clean the default bad one and it this a bug ?

https://tube.aquilenet.fr/videos/watch/4f4601fb-8f1a-4a6a-b02e-2b8478d1b79e

**Comment by Chocobozzz** [comment]
Seems related to https://github.com/Chocobozzz/PeerTube/issues/2492

Do you have audio only option enabled?

**Comment by sachaz** [comment]
yes

**Comment by sachaz** [comment]
the first step for me is to change the default one or to remove the ugly one (we gave the link on maillings lists and press)

**Comment by Your-New-SJW-Waifu** [comment]
> Seems related to #2492
> 
> Do you have audio only option enabled?

So if audio only is disabled this bug doesn't happen?

**Comment by sachaz** [comment]
I tri

> > Seems related to #2492
> > Do you have audio only option enabled?
yes
> So if audio only is disabled this bug doesn't happen?
yes

I have removed this video a uploaded a new one no problem.
The issue occurred with a reencoding of an existing one.

**Comment by Chocobozzz** [comment]
Thanks for the issue. Fixed in https://github.com/Chocobozzz/PeerTube/commit/1c3206736743646d41a667c03f3e499cc3e3373f
