### ISSUE TITLE
/usr/bin/npm: No such file or directory

### ISSUE THREAD

**Issue by rwb99** [Chocobozzz/PeerTube#2713]
**What happened?**
got this error 

![](https://i.imgur.com/EyL8g1c.png)
**What do you expect to happen instead?**
not getting any breaking errors
**Steps to reproduce:**

follow the production guide  
https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md

**Additional information**
* PeerTube version or URL: latest as of may 2nd 2020
* Browser name/version: chrome latest as of may 2nd 2020
* NodeJS version: v10.20.1

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by rwb99** [comment]
if it helps this is how i installed node https://computingforgeeks.com/installing-node-js-10-lts-on-ubuntu-18-04-16-04-debian-9/ i guess npm is supposed to come with node from the googling ive done

**Comment by Booteille** [comment]
Hi. As stated [in the readme](https://github.com/Chocobozzz/PeerTube/blob/develop/README.md#package-create-your-own-instance), you need to install Node as a dependency to install PeerTube.

Take time to read installation instructions before trying to install it. It'll help you to don't miss a step.

**Comment by rwb99** [comment]
idoing npm -v gives me v6.14.4 so its installed..

**Comment by Booteille** [comment]
What is the command you ran to get the error?

Also, check where `npm` is installed by running the command `whereis npm`.

If it's not /usr/bin/npm, maybe you should make a symlink using `ln -s /usr/bin/npm PATH_TO_NPM`.

**Comment by rwb99** [comment]
fixed it it was in issue with my peertube.service. I have another issue with my config i'll address later
