### ISSUE TITLE
Understanding peertube in depth

### ISSUE THREAD

**Issue by Musadiqraees** [Chocobozzz/PeerTube#2714]
What can be possible performance metrics for peertube service . Quality of services need to check for peertube.

**Comment by Chocobozzz** [comment]
I don't understand the question.

**Comment by Musadiqraees** [comment]
What should be qos parameters for peertube.

**Comment by rigelk** [comment]
Bandwidth and CPU are important. What metrics in that matter and how you measure them is up to you.
