### ISSUE TITLE
Search also in the description not only title

### ISSUE THREAD

**Issue by klorydryk** [Chocobozzz/PeerTube#2715]
Improvement.
Checked in v2.0.0
To improve search results by looking for keyword also in the description of the videos, not only in the titles.

**Comment by Chocobozzz** [comment]
We can't using postgresql, or it would require additional work to create a full text search table which we don't really want. Instead, we'll create an external indexer and search system based on Elastic Search that admin can install or use. See https://github.com/Chocobozzz/PeerTube/issues/824 for more information
