### ISSUE TITLE
Feature Request: Trigger HLS encoding for already uploaded Videos

### ISSUE THREAD

**Issue by tilllt** [Chocobozzz/PeerTube#2717]
It would be great if already uploaded Videos could also be HLS encoded

**Comment by Chocobozzz** [comment]
There is a script to create transcoding jobs for existing videos: https://docs.joinpeertube.org/#/maintain-tools?id=create-transcoding-jobjs

**Comment by tilllt** [comment]
Well, for somebody who is not running Peertube in  Docker, has only a couple of videos to transcode and/or is fluent in bash scripting, that is a great tool. Sure. For everybody else it's not.
