### ISSUE TITLE
Feature Request: Optionally keep original uploaded Media

### ISSUE THREAD

**Issue by tilllt** [Chocobozzz/PeerTube#2718]
It would be great to have a configurable option to keep the originally uploaded media files, unaltered. This would be good for future re-encoding to better codecs, or streaming methods (like HLS) but also to give the users the option to use the peertube instance as a backup for higher quality video files.

**Comment by DontUseGithub** [comment]
https://github.com/Chocobozzz/PeerTube/issues/733
