### ISSUE TITLE
Client-app like music.youtube.com

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#2722]
Hi,

On our instance, we have lots of audio creators who use soundcloud or bandcamp and YouTube only for visibility.

Now there is music.youtube.com.

I actually wonder how to simply build a responsive desktop app (not an heavy client like Electron.js) only to listen medias of a PeerTube instance as an audio with a player, no accounts, maybe just a local storage to store playlists and instances (something like https://github.com/TeamNewPipe/NewPipe for Android)

Do you think a Node.js relay / proxy would be required to over-pass CORS limitations ?

**Comment by JohnXLivingston** [comment]
Check Thorium: https://f-droid.org/fr/packages/net.schueller.peertube/

**Comment by tilllt** [comment]
(something like https://github.com/TeamNewPipe/NewPipe for Android)
> 

If you like newpipe, check out the audio only version of it for music https://f-droid.org/en/packages/deep.ryd.rydplayer/&ved=2ahUKEwiHlYfqrpzpAhWFfZoKHfqWCh8QFjABegQIBhAB&usg=AOvVaw2ma3cy_uNn_SO2q3isuDTd

**Comment by tilllt** [comment]
> Check Thorium: https://f-droid.org/fr/packages/net.schueller.peertube/

Last time I tried it the server was hardcoded. Did that change?

**Comment by JohnXLivingston** [comment]
> > Check Thorium: https://f-droid.org/fr/packages/net.schueller.peertube/
> 
> Last time I tried it the server was hardcoded. Did that change?

as far as I remember, the default server is hardcoded, but you can change it (as said on the f-droid page)

**Comment by Chocobozzz** [comment]
We don't have CORS limitations on our API and static files so it should not be an issue. You can use the rest api documentation (https://docs.joinpeertube.org/api-rest-reference.html) to build the desktop/mobile application you want, dedicated to audio files or not.

**Comment by kimsible** [comment]
Thanks @Chocobozzz.
