### ISSUE TITLE
About page should be a single Textarea

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#2723]
The hardcoded sections in the about page seem to be mostly made with the goal of selecting instances to display on joinpeertube.org, and they probably work fine for that. However, for instances that are not listed there (like peertube.social), it makes things unnecessarily complicated. We want to be able to reorder the sections and add new ones, which is simply not possible at the moment. 

So it would be nice if the hardcoded sections could be (optionally) replaced with a single text input, which also supports headings in markdown.

**Comment by Chocobozzz** [comment]
> The hardcoded sections in the about page seem to be mostly made with the goal of selecting instances to display on joinpeertube.org, and they probably work fine for that.

No, the main purpose is to guide admins in answering questions that are of interest to users. You already have many textareas in the configuration, just pick one.

**Comment by Nutomic** [comment]
Then how about allowing us to reorder the fields at least? For example we have very long terms of use, and I would prefer to move them to the bottom of the page.
