### ISSUE TITLE
Muted comments appears on RSS feeds

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2725]
**What happened?**
There are some users who are spamming my instance with comments. I muted them for my instance.
But their comments are still shown in RSS feeds.

It is similar to https://github.com/Chocobozzz/PeerTube/issues/2663 , but I think that your fix don't fix this one.

**What do you expect to happen instead?**
Filter muted user's and server's comments. 

**Additional information**
* PeerTube version or URL: 2.1.1

**Comment by Chocobozzz** [comment]
Thanks for the issue. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1df8a4d79a491d2ad5bdd9329f37e52cba21238c
