### ISSUE TITLE
Reset daily quota at the same time every day

### ISSUE THREAD

**Issue by TimotheeGreg** [Chocobozzz/PeerTube#2726]
**What happened?**
I need to upload many videos on my account, so every day I use all the daily quota and the quota reset 24h after my upload, therefore if some day I upload late in the day, let's say at 10pm then the following days I will have to upload later than 10pm and later every day until I wait a day without uploading.

**What do you expect to happen instead?**
My suggestion would be to reset the daily quota every day at the same time (midnight?) so that the average quota is still the same but the user can upload at any time in the day.

**Additional information**
* https://peertube.social/
* version 2.1.1

**Comment by Chocobozzz** [comment]
Hello,

We can't because it depends on the user timezone. And I don't think this is something admins except: using the daily quota allows them to limit your impact on the transcoding jobs. With your proposition, you could upload `dailyQuota` * 2 in a small amount of time (23h and on 00h).
