### ISSUE TITLE
List all comments

### ISSUE THREAD

**Issue by alejandrocobo** [Chocobozzz/PeerTube#2727]
Hi,
Recently I've installed a new Peertube instance. I have found that sometimes, users from other instances leave SPAM messages on my videos. Always I see one of them, I delete it. Is there a way to list all comments left on my instance and sort them by date in order to easy me the moderation tasks?

Thanks.

**Comment by Chocobozzz** [comment]
Hello,

https://docs.joinpeertube.org/#/admin-moderation?id=understand-what-happens-on-your-instance might help you
