### ISSUE TITLE
Video not federated between 2.2 and 2.1

### ISSUE THREAD

**Issue by dadall** [Chocobozzz/PeerTube#2728]
**Branch** : develop
**Docker** : yes

**What happened?**

Everything is federated (playlists, channels, avatars, etc) but not videos themselves.
Federation successfully tested with Peertube stable and Mastodon stable. 
It seems to be a problem between develop and stable branch only.

**What do you expect to happen instead?**

Videos to be shared properly between develop and stable versions.
 
**Steps to reproduce:**

1. Install Peertube (chocobozzz/peertube:develop-buster)

2. Upload a video

3. Check the spread 

**Example** 

-> Local : https://pt.diaspodon.fr/accounts/dada/video-channels
-> Remote : https://videos.pair2jeux.tube/accounts/dada@pt.diaspodon.fr/video-channels

**Additional information**
* PeerTube version or URL: https://pt.diaspodon.fr
* Browser name/version: Osef
* NodeJS version: Osef

* Link to browser console log if useful: Osef
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): Osef

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/7557704eec3995092136b87154a1fbe644bc0fec. I'll test the fix later

**Comment by Chocobozzz** [comment]
Latest build is now working: https://builds.joinpeertube.org/nightly/
