### ISSUE TITLE
Error: Cannot parse config file: 'production.yaml': YAMLException: can not read an implicit mapping pair; a colon is missed at line 290, column 78

### ISSUE THREAD

**Issue by rwb99** [Chocobozzz/PeerTube#2729]
**What happened?** got an error with the config

**What do you expect to happen instead?** not have an error

**Steps to reproduce:**

1.
did this https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/dependencies.md
2.
and then this  https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md
3.

**Additional information** running Ubuntu server 18.04
* PeerTube version or URL: v2.1.1
* Browser name/version: Google Chrome
* NodeJS version: v10.20.1

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

![image](https://user-images.githubusercontent.com/63825594/81064988-b0cb8800-8ea8-11ea-992e-fdb425766284.png)
But if i add a colon then it says
![image](https://user-images.githubusercontent.com/63825594/81065139-f720e700-8ea8-11ea-97c2-a9eb4473a2e1.png)
If i remove all the commented stuff i get
![image](https://user-images.githubusercontent.com/63825594/81065373-55e66080-8ea9-11ea-9ad4-cc2f9d9564ac.png)

here is my config https://pastebin.com/6z0cuvTw

**Comment by Chocobozzz** [comment]
Line 290, there is an unescaped `'` character. Prefer to update these fields using the peertube admin web interface
