### ISSUE TITLE
Error 500 when trying to add a too long description to a playlist

### ISSUE THREAD

**Issue by Booteille** [Chocobozzz/PeerTube#2730]
**What happened?**
When trying to update/create a playlist, the XHR request results in a 500 error.

**What do you expect to happen instead?**
To update properly the description or to get an explicit error saying the description is too long.

**Steps to reproduce:**

1. Go to the page to create a playlist

2. Set a description of more than 255 characters.

3. Submit the form.

**Additional information**
* PeerTube version or URL: https://video.ploud.fr/
* Browser name/version: Firefox 75.0

* Link to browser parameters: https://bin.privacytools.io/?2b83b2da7c1ddd8a#53sW0/LdvPTSeZfN+AXI8lou3LWF9rykN8hoLSufVZE=

**Comment by rigelk** [comment]
Duplicate of #2687. Please look out for similar issues before opening one.

**Comment by Booteille** [comment]
My bad, sorry.
