### ISSUE TITLE
Hide alert box if registration disabled

### ISSUE THREAD

**Issue by Natureshadow** [Chocobozzz/PeerTube#2731]
As discussed on IRC:

It would be great if the blue alert box, which directs users to other isntances if registration is disabled, could be hidden or even better replaced with a custom text. This is helpful if the instance uses another authentication provider, e.g. LDAP, which might allow registration outside of PeerTube.

**Comment by Chocobozzz** [comment]
With https://github.com/Chocobozzz/PeerTube/commit/f375bb3db401e42b4317545a7e40dcfda692604d you can now override the text:

```
  registerHook({
    target: 'action:login.init',
    handler: () => {
      console.log('Login init')
      document.querySelector('.looking-for-account > div').innerHTML = '...'
    }
  })
```
