### ISSUE TITLE
Add some digital sobriety features

### ISSUE THREAD

**Issue by Dazeilad** [Chocobozzz/PeerTube#2733]
Hi,

I would love to see new features adding more digital sobriety in PeerTube. The goal is to prevent high resolution videos to be seen if the user does not especially ask for it.

We could imagine several ways of doing this :
* Prevent - or add a warning, because we remain free - the Auto resolution setting to be higher than 720p
* Set always the Auto resolution at 360p (or less ?)
* Add a parameter for the content maker to specify if the video is supposed to be seen with a good quality (like for art, movies, or a tutorial with HD screen capture...) or not necesseraly (like for a clip music, or an interview - well, content where the audio conveys the main message and video is only there to support it). Based on that, the Auto resolution would be adjusted (HD or 360p for example)

It would be nice also to add a data meter below the video to give awareness about the size of what is downloaded (would be awesome to link it to something representative like the time of letting a lamp lit (energy) or a distance travelled by car (CO2), based on the [Carbonalyser](https://theshiftproject.org/carbonalyser-extension-navigateur/) developped by TheShiftProject ([deposit](https://github.com/carbonalyser/Carbonalyser))

What do you think ? Do you have some other ideas ?

**Comment by bristow** [comment]
That's some good ideas ! :+1:

**Comment by rigelk** [comment]
There was an issue about this already but I can't seem to find it :/

**Comment by tilllt** [comment]
Never thought about this I must admit. But it's a very valid point. Are there statistics about how much energy an average GB/MB/KB transmitted over the internet consumes?

**Comment by tilllt** [comment]
Ok reading about their "methodology" this comes across as soon doctoring and lobby work. For the right cause, I agree wholeheartedly, but I disapprove of pseudo scientific means to nudge people into better behaviour. A simple disclaimer that transferring data consumes energy is then the much more honest approach than a this "magic" formula they are using to pretend they calculate the energy consumption.

**Comment by tilllt** [comment]
Also @Dazeilad , you don't eventually work for that thinktank right?

**Comment by Dazeilad** [comment]
> There was an issue about this already but I can't find it :/
> 
> EDIT: that's #1979

Oh sorry, I did check before posting, but didn't see it... :( Whatsoever, the idea is double wanted :stuck_out_tongue_closed_eyes: 


> Also @Dazeilad , you don't eventually work for that thinktank right?

No, I don't, but I follow their works.


> Ok reading about their "methodology" this comes across as very lame spin doctoring and lobby work. For the right cause, I agree wholeheartedly, but I disapprove of pseudo scientific means to nudge people into better behaviour. A simple disclaimer that transferring data consumes energy is then the much more honest approach than a this "magic" formula they are using to pretend they calculate the energy consumption.

What does look pseudo-scientific to you ? The lack of fiability and the use of global statistics instead of measuring the actual consumption of the server ?

**Comment by Dazeilad** [comment]
@rigelk is it possible to merge this issue with #1979 ? I find the previous ideas proposed were relevant too :smiley:

**Comment by tilllt** [comment]
> What does look pseudo-scientific to you ? The lack of fiability and the use of global statistics instead of measuring the actual consumption of the server ?


What it looks like? Like this:
![221451](https://user-images.githubusercontent.com/1854364/81221965-dd37ef00-8fe3-11ea-8161-74e8f268ef72.png)

**Comment by Dazeilad** [comment]
Sorry, I don't understand, please explain.

The method used measures the quantity of data sent by the server, then multiplies by the average consumption of energy per byte (global datacenter, network and terminal statistics), then multiplies by the average CO2 emissions per kWh, based on global countries statistics. I agree this is not very specific (you might be selfhosting your instance powered on solar panels, it won't be taken into account). The issue is not the method, it is the access to the energy and CO2 data.

If the problem is the use of simple figures to explain a complex situation, well... worse has been done for a while with the "A+++ to G" energy labels for instance.

At least, I think we could agree on a "data-meter" showing the amount of data downloaded, which is the only accurate thing we can get from the software.

**Comment by tilllt** [comment]
>I agree this is not very specific (you might be selfhosting your instance powered on solar panels, it won't be taken into account). 

"Not very specific" is a big understatement. The amount of data centers running on co2 neutral energy is probably much higher than the average co2 neutral power consumption of a country, at least in Germany. 

And then there are probably hundreds of other factors which are not taken into account, which make the calculation BS at best. They DO want to come across though as "scientific" & factual. Either you got the numbers to do the stats or you don't. But don't bullshit people with a pretty random set of numbers that works fine with your confirmation bias and make it look shiny with pie charts.

**Comment by Dazeilad** [comment]
Hmm, I disagree with what you said. But this is not the place to discuss that, we might continue in private if you want.
This methodology issue would be discussed again if someone actually try to code that.

Coming back to the other ideas, do the features about "nudging" towards lower resolutions make a consensus here ? Which one do you think would be best for user experience (video maker & viewer) ?

**Comment by Chocobozzz** [comment]
Hello,

You can create a peertube plugin to implement features you talked about. If you need specific hooks, don't hesitate to create dedicated issues so we implement them.

Starting guide to develop plugins: https://docs.joinpeertube.org/#/contribute-plugins
