### ISSUE TITLE
Audio Files

### ISSUE THREAD

**Issue by trymeouteh** [Chocobozzz/PeerTube#2734]
I am not sure if Peertube can do this or not but I think it will be cool if Peertube supported audio and not just video. Allow channels to upload MP3 or FLAC files and choose a thumbnail image which can act as the album cover.

This will help save space for those who want to upload their own music or audio podcasts.

**Comment by Chocobozzz** [comment]
You can already upload audio files if the admin allows it, and admins can choose to transcode videos in audio mode only.
