### ISSUE TITLE
Admin page to list and moderate comments

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2736]
**What happened?**

Comments moderation begins to be a nightmare. Actually, I have to follow the comments RSS feed, to check new comments and moderate them.

**What do you expect to happen instead?**
It would be very usefull to have screens listings comments, with filters like:

- comments on local videos (to find user spamming my videos)
- comments emitted by local users (to find locale users spamming remote instances)

**Comment by prolibre** [comment]
At the moment I get several spam mails a day. As I'm fed up I disabled comments on all my videos with a dirty sql request "commentsEnabled=FALSE", I just hope it's not too dirty and that it will work :-)

**Comment by popindavibe** [comment]
This seems to be spreading fast, I have been looking for a way to see all comments posted lately from the administration section in the hope to be able to mute user + delete comments, but it's not a thing yet apparently.

Also, if you mute the user, comments disappears only from your instance but are visible if connecting from another one (as mentioned by @prolibre ), and you won't be able to see it from the admin interface any more.
What I ended up doing was unmute, go to the page, mute user instance-wide, and delete the comment. And if the same spammy user has commented several times, you need to delete all comments **before** you mute that user. 
This needs to be improved, as it requires far too many steps as it is to keep an instance clean.
Also, the ability to submit comments for review before validation could be an acceptable way to contain spams as well (thinking of something like WordPress _Antispam bee_ does).

**Comment by JohnXLivingston** [comment]
> This seems to be spreading fast, I have been looking for a way to see all comments posted lately from the administration section in the hope to be able to mute user + delete comments, but it's not a thing yet apparently.

FYI you can actually see all comments on your instance with this RSS feed: https://your_instance/feeds/video-comments.xml?sort=-publishedAt&filter=local
Muted comments are listed, but this is a bug that was just fixed: https://github.com/Chocobozzz/PeerTube/issues/2725

> 
> Also, if you mute the user, comments disappears only from your instance but are visible if connecting from another one (as mentioned by @prolibre ), and you won't be able to see it from the admin interface any more.

Really? I made a test from an other instance, but without being connected. If this is true, this is a bad news...

If so, it will be usefull to have a functionnality to delete all muted comments.

**Comment by popindavibe** [comment]
I've just tried the RSS feed link on my instance, however I am seeing comments posted on other instances' videos in there, confusingly enough.

**Comment by popindavibe** [comment]
Looking back at this today, I was wrong, the muted account for a local video appears to be filtered on other instances as well.
I guess the RSS feed is the only way currently to attempt to do comment moderation. I guess the moderation part of v3 roadmap will address this.

**Comment by Niquarl** [comment]
A possibility to either limit the number of comments a user can make in a given period (24 hours, a week) or just allowing in the admin panel to see users that have commented a lot could be usefull to at a glance see spam accounts too.

Also, right now, when I'm judging a user based on a reported comment to see if I need to ban that user or just remove that one reported comment I have to go into Mastodon to see all their previous comments. Adding a easy view of a users past comments for moderators would be good. I don't think a user's comments should be public though (at least by default) ie. visible to non-mods.

**Comment by Chocobozzz** [comment]
> A possibility to either limit the number of comments a user can make in a given period (24 hours, a week) or just allowing in the admin panel to see users that have commented a lot could be usefull to at a glance see spam accounts too.

This is interesting. Don't hesitate to create a dedicated issue.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/19149d45b8f68569535f7188ef25e09e3d62c8b4
