### ISSUE TITLE
Effacer Commentaire Pourriel. Nouvelle Fonctionnalité. / Delete Spam Comment. New Feature.

### ISSUE THREAD

**Issue by Francewhoa** [Chocobozzz/PeerTube#2738]
[English](#en) below

# Français

**Quel est le défis?**
Des personnes avec un comportement malfaisant utilisent des robots pour ajouter des commentaires spams sur mes vidéos téléversés

**Quel est ton besoin?**
Ci-dessous est un Scénario d’Utilisateur. Qui clarifi le besoin présent et la résolution suggèré.

## Scénario d'Utilisateur 

En tant qu’utilisateur de PeerTube, après que j’ai téléversé une vidéo, **j’ai besoin d’effacer certain commentaires spams** qui ont été ajoutés sur mes vidéos téléversés, pour que :
* Les visiteurs ont une expérience plus plaisante
* Réduire les risques d’abuses des robots. Tel que les piège à clics et ou vol d’information privé.
Par « Piège à clics » je veux dire ceci à https://fr.wikipedia.org/wiki/Pi%C3%A8ge_%C3%A0_clics
https://archive.md/wb3wX

## Suppositions

* Suppose que les numéros 1, 2, 3 dans cette mockup montrent ma suggestion pour cette nouvelle fonctionnalité 
![Mockup---Effacer---Bot---Spam_comment---PeerTube---version_1](https://user-images.githubusercontent.com/119942/81326076-1b69f880-904e-11ea-96fc-f644aa4a4802.jpg)

* Suppose que cette nouvelle fonctionnalité est disponible seulement sur les vidéos qui ont été téléversé par l’utilisateur. En d’autres mots, l’utilisateur ne devrait PAS être capable d’éffacer les commentaires sur les vidéos téléversé par d’autres utilisateurs.

* Suppose que pour de l’inspiration pour les développeurs PeerTube, voici comment un utilisateur YouTube peut éffacer un commentaire spam sur ses vidéos téléversés à https://www.wikihow.com/Delete-Comments-on-YouTube
https://archive.md/Iwktj

* Suppose que, si besoin, tout deux mois et l’équipe Ubertus serait content de contribuer des tests et documentation si besoin

**Étapes pour reproduire:**

Le numéro 1 dans cette capture d’écran montre un example d’un commentaire spam robot. Avec un piège à click:
* https://user-images.githubusercontent.com/119942/81326076-1b69f880-904e-11ea-96fc-f644aa4a4802.jpg
* Source https://open.tube/videos/watch/c472bec1-6b67-433d-a3b9-1eb10d7a51cc

**Additional information**
* PeerTube version or URL:  https://open.tube/about/instance 
* Browser name/version: Firefox 68
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

<a name="en"></a>
# English

**What happened?**
People with evil behaviors use robots to post spam comments on my uploaded videos

**What do you expect to happen instead?**

Below is a User Story to clarify the present need and the suggested resolution

## User Story

As a PeerTube user, after I uploaded a video, **I need to be able to delete some spam comments** which were added by robot accounts on my uploaded video, so that :
* Visitors have a more pleasant experience
* Reduce risks of abuse by robots. Such as clickbait or thelf of private information.
By « Clickbait » I mean this https://en.wikipedia.org/wiki/Clickbait 

## Assumptions

* Assumes that the numbers 1, 2, 3 in this mockup show this suggested new feature 
![Mockup---Effacer---Bot---Spam_comment---PeerTube---version_1](https://user-images.githubusercontent.com/119942/81326076-1b69f880-904e-11ea-96fc-f644aa4a4802.jpg)

* Assumes that this suggested new feature is available only on the videos uploaded by the user. In other words, the user should NOT be able to delete comments on videos uploaded by other users.

* Assumes that for inspiration for the PeerTube developers, here is how un utilisateur YouTube is able to delete spam comment on her/his uploaded video at https://www.wikihow.com/Delete-Comments-on-YouTube
https://archive.md/Iwktj

* Assumes for this new feature, both me and the Ubertus team would be happy to contribute testing and documentation if needed.

**Steps to reproduce:**

The number 1 in this screenshot shows an exemple of a robot spam comment with a clickbait :
* https://user-images.githubusercontent.com/119942/81326076-1b69f880-904e-11ea-96fc-f644aa4a4802.jpg
* Source https://open.tube/videos/watch/c472bec1-6b67-433d-a3b9-1eb10d7a51cc

**Additional information**
* PeerTube version or URL:  https://open.tube/about/instance 
* Browser name/version: Firefox 68
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Francewhoa** [comment]
Discussion relié à https://framacolibri.org/t/effacer-notification-abusive/7890
/
Related discussion in French at https://framacolibri.org/t/effacer-notification-abusive/7890

**Comment by Chocobozzz** [comment]
Hello,

Thanks for the issue. We implemented this in https://github.com/Chocobozzz/PeerTube/commit/fde37dc99c0ca43021ac3d1b3537f095ee6114b7 and it will be released at the end of May.
