### ISSUE TITLE
New account creation should set theme to instance default

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#2739]
**What happened?**
When creation new account from admin interface or when user registers for an account it doesn't use the theme set to the instance by default and ideally would be best to set users default theme on creation to the instance default. Otherwise users go to the site and see a dark theme then create an account and login to see a white theme and have to change it manully to have the instance default theme because right now accounts created with peertube default theme set.

<img width="288" alt="Screen Shot 2020-05-08 at 9 12 59 PM" src="https://user-images.githubusercontent.com/43896676/81461439-64ff3400-9171-11ea-8ac3-70e82280ccea.png">

**What do you expect to happen instead?**

**Steps to reproduce:**

1. visit site with dark theme

2. create account login to see peertube default light theme

3. change manually in account settings to instance default to see the dark theme 

**Additional information**
* PeerTube version or URL: https://troo.tube
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Thanks for the issue. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/3f87a46f1dd01485e4a28422f74c3a1b0f56729f
