### ISSUE TITLE
Unable to delete auto-blacklisted videos from mobile chrome

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#2740]
**What happened?**
When going to a video and trying to delete it instead of unblacklisting it, I'm unable to do it from a iPhone8 Chome browser

**What do you expect to happen instead?**

**Steps to reproduce:**

1. as admin/moderator tap auto-blacklisted video

2. try to delete/remove it

3. doesn't do anything

**Additional information**
* PeerTube version or URL: https://troo.tube
* Browser name/version: some new google chrome browser, DuckDuckGo Browser same thing 
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Closing as we rewrote the blacklist pages a few months ago. Please ask to reopen if you still have this issue.
