### ISSUE TITLE
Need instance setting set/unset wait transcoding on all uploaded videos by default

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#2742]
Need a setting in the admin to be able to set or unset wait transcoding on all uploaded videos. Would require either enabled or disabled checkbox which would either enable it by default on uploaded videos or not enable it depending on what is set in the admin, so the users dont have to uncheck "Wait transcoding before publishing the video" in order for people to see an urgent video!

**Comment by Chocobozzz** [comment]
You can create a plugin for this purpose.
