### ISSUE TITLE
Mobile users buffering issues - Can't skip ahead + fully downloads videos

### ISSUE THREAD

**Issue by HostGnome** [Chocobozzz/PeerTube#2743]
I have just installed PeerTube and noticed two issues regarding mobile users.

1) I don't seem able to skip ahead in a video unless I have it buffered already. Is this where HLS comes in?
2) Videos completely buffer which uses up a lot of data if you plan on only watching a small part of the video. How would I be able to limit how much in advance a video is downloaded?

**Comment by rigelk** [comment]
These are problems solved by our implementation of HLS. Ahead buffering is then also limited.
