### ISSUE TITLE
Video cannot be retrieved from WebTorrent

### ISSUE THREAD

**Issue by Sovxx** [Chocobozzz/PeerTube#2744]
**What happened?**
I am seeding ~20 videos (taken from various instances) with WebTorrent v0.21 on my PC1.
But I never see them beeing uploaded, even when I am watching them myself with my PC2 (different ISP) on PeerTube.

**What do you expect to happen instead?**
PC1 (WebTorrent) should show it is uploading something.
PeerTube should be able to take files shared by WebTorrent. (I guess it should, right ?)

**Steps to reproduce:**

1. Download and seed https://video.colibris-outilslibres.org/download/torrents/fe3fb11f-799b-4a0b-8b57-9472f85d8f6e-480.torrent with WebTorrent on PC1.

2. Watch https://peertube.fr/videos/watch/fe3fb11f-799b-4a0b-8b57-9472f85d8f6e on PC2 using a different (or not) ISP.

3. See that there is no upload rate showing on PC1.

**Other info**
UPnP is activated on my router (I have also tried to put my PC1 as a DMZ, but it did not change anything) for PC1.
Tested with PC1 on Ubuntu 18.04 and also Windows 10.

**Comment by rigelk** [comment]
Have you tried using the magnet link instead of the torrent file ?

**Comment by Sovxx** [comment]
Well, now it works...
with .torrent and magnet link.
I could not even tell what I did wrong :(
