### ISSUE TITLE
Adding /app/storage/streaming-playlists/hls/ as a Docker volumes

### ISSUE THREAD

**Issue by jaarandaz** [Chocobozzz/PeerTube#2745]
I got my "/var" partition full because hls encoded playlists are being created inside the app Docker image, and not using the volume "data". Can you please use a volume for this in your Docker image? Or there is another recommended way to solve this? Thanks!

**Comment by jaarandaz** [comment]
I was using an outdated production.yaml file

**Comment by dislive** [comment]
Could you tell me what exactly you changed? The fact is that in reality I have a volume of 1.9GB of video, and if I make an archive, it's 17GB. Those additional videos are stored somewhere. I understand that this is in /peertube/storage/streaming-playlists/hls
