### ISSUE TITLE
OAuth error on peertube page load

### ISSUE THREAD

**Issue by OceanTechie** [Chocobozzz/PeerTube#2746]
I have pulled full code into a separate directory structure and did a build of client and server (i made code change to use videojs-vr and then undid that and compiled again to remove my code change as possible reason for my problem).  

On load of my peertube instance, I am getting:

Cannot retrieve OAuth Client credentials: . Ensure you have correctly configured... and the root login no longer works, even with new pswd journalctl showed was generated on first start up.   old pswd no go either...throws message invalid client trying to login as root.   With my prod database, I CAN login as a user I had created before.

When I can login as a user, I upload a sample video and it won't play.  existing ones don't play either

**What do you expect to happen instead?**
no error on page load and for root login to work

**Steps to reproduce:**

1. Do a build with yarn  build:client --production --light --pure-lockfile (with or without a code change) - this step works - did build:server too
2. Stop peertube, nginx, redis, restart each
3. update my systemd service for peertube - which points to my new peertube location
4. Stop peertube, nginx, redis, restart each
5. I get my database is ready and a clean status from systemctl status and journalctl 
6. Loads my peertube page, but get OAuth error.  I can navigate to about page and see text change I had made before building client, videos don't play - black screen.

I tried creating separate database and modifying production.yaml and restarting...same deal

Do I need to re-apply or renew certbot?  I thought that is for my domain name only, which has not changed.

I found a post that said for this error, to clear all caches, stop nginx, redis and peertube, and also drop and recreate a database -  I did and I did create a new db, but not while all three were stopped (just peertube)

My webserver section of production.yaml is:

webserver:
  https: true
  hostname: 'mypeertubename.com'
  port: 443

my hostname is correct.

* PeerTube version or URL:

latest 2.2.1, on Ubuntu 18.04

* Browser name/version:
chrome

* NodeJS version:
10.13

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

journalctl is clean - says my database is ready and everything is started.

my peertube.log has several of these err messages:

{"err":{"stack":"Error: Unknown infoHash 8c6acd235f3ebf4acf36d487522137c5c49724ea\n    at Server

**Comment by Chocobozzz** [comment]
Please paste the URL of your instance
