### ISSUE TITLE
Listing non-public videos in user channels

### ISSUE THREAD

**Issue by bristow** [Chocobozzz/PeerTube#2747]
Hello everyone!

Many users don't understand why their videos are not listed in their channels when they go to the channel menu: https://instance/my-account/video-channels.

Actually, Peertube does not list unlisted videos (not public). Would it be feasible to list these videos or make them appear by checking a box, like when you are an administrator?

Thanks !

**Comment by Chocobozzz** [comment]
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1760
