### ISSUE TITLE
Context needed for translation

### ISSUE THREAD

**Issue by AutomCoding** [Chocobozzz/PeerTube#2748]
I'm finding this string difficult to translate without context:

https://github.com/Chocobozzz/PeerTube/blob/5ff523664fda3acf83e319a7c08cd14af0025e99/client/src/app/%2Badmin/users/user-list/user-list.component.html#L49

What kind of values can be expected in this column, how does it relate to the user (and plugin) and is it about authentication and/or authorization?

**Comment by Chocobozzz** [comment]
It's the name of the authentication plugin that created and authenticates the user
