### ISSUE TITLE
Disabling Resolution 1080p not working

### ISSUE THREAD

**Issue by Chardonneaur** [Chocobozzz/PeerTube#2749]
**What happened?**

Within Configuration -> Advanced Configuration -> when I unchecked Resolution 1080p and that I click on Update configuration, I am getting the following error message "Error Should have a valid theme" at the bottom right and corner of PeerTube. I tried multiple themes (official ones) and the error still appear, when I refresh the configuration page, the Resolution 1080p is still on.

**What do you expect to happen instead?**

I expect the Resolution 1080 checkbox to be unchecked.

**Steps to reproduce:**

1. Go on Configuration.

2. Advanced Configuration.

3. Uncheck 1080p and click on Update configuration.

**Additional information**
* PeerTube version or URL: https://peertube.floss-marketing-school.com/
* Browser name/version: Firefox 76.0 (64-bit)
* NodeJS version: no idea, sorry.

* Link to browser console log if useful: Backend returned code 400, errorMessage is: Should have a valid theme Choo 26
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
>  I tried multiple themes (official ones) and the error still appear, when I refresh the configuration page, the Resolution 1080p is still on.

Did you try `default` in *Basic configuration* tab?

**Comment by Chardonneaur** [comment]
Problem solved, thanks to you.
Thank you so much, my project was running out of disk space and was starting to cost a lot.
Here is how to solve it:
-> Go within Configuration.
-> Go on Basic Configuration.
-> Select the Default theme (for me it was left on blank).
-> Go on Advanced configuration.
-> Uncheck 1080p and save the configuration.
Problem solved.
