### ISSUE TITLE
videos not playing as expected

### ISSUE THREAD

**Issue by Tanami** [Chocobozzz/PeerTube#275]
* **PeerTube version or commit:**  v0.0.20-alpha
* **Browser name/version:** 65.0.3315.3 (Official Build) dev (64-bit)
* **NodeJS version:** n/a
* **PostgreSQL version:** n/a

* **What is the expected behaviour?**
When using peertube.cpy.re, a selected video will endlessly buffer. To make it play you must click pause/play twice, and the error below appears in the console. Thereafter the video will play. Thanks.

* **What do you see instead?**

* **Browser console log if useful (Gist/Pastebin...):**
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22

* **Server log if useful (Gist/Pastebin...):**

**Comment by Chocobozzz** [comment]
@Tanami Which video? :)

**Comment by Tanami** [comment]
any video. normally I would look through the source for you but I think it should be apparent what the problem is to you

**Comment by Chocobozzz** [comment]
Okay sorry, in fact it worked on Chromium but not on Google Chrome.

Should be fixed: https://github.com/Chocobozzz/PeerTube/commit/481d35966fe49e9a5d3442b658e35403e9464322

Thanks for the report @Tanami!
