### ISSUE TITLE
Links get broken in long video description

### ISSUE THREAD

**Issue by ahangarha** [Chocobozzz/PeerTube#2750]
**What happened?**
I have uploaded videos with long description in which, there are some links. Since by default, a short version of description is shown under videos, if there be a link at the point the description is getting cut, the link gets broken. See the screenshot below

![image](https://user-images.githubusercontent.com/11241315/81717925-6641a100-9490-11ea-85dc-200bef649e73.png)

**What do you expect to happen instead?**
I think before cutting the text, we should make sure cutting is happening on normal text not links.

**Steps to reproduce:**

1. Simply use a long description with links in a way the link be at the cutting point.

**Additional information**
* PeerTube version or URL: https://peertube.social/videos/watch/0bb7e5c0-ad80-4a2f-9e3c-ab7c576e22b9
* Browser name/version: Firefox 76

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/5404
