### ISSUE TITLE
Hook for filtering the suggested videos of the Discover tab

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#2751]
**What happened?**

We implemented a plugin to federate a single channel with our instance. This plugin requires to federate the instance to the channel's one, and then it ensures that the videos displayed only the one of our own instance or belongs to the federated channel.

So we made sure that:
 - the videos, the users and the channels of the search results fulfills the criteria
 - the videos of the Trending, Most Liked and Recently added tabs also fulfills this criteria

However, it seems that we cannot filter the videos displayed in the Discover tab:
https://docs.joinpeertube.org/#/api-plugins

It would be nice for us to able to do that :).

I can share the source code of our plugin upon request (we hope to free it soon once we have implemented a UI to configure it).

**Additional information**
* PeerTube version or URL: 2.1.1 (https://skeptikon.fr)

**Comment by Chocobozzz** [comment]
Hello,

I'm closing this issue now we have the homepage and dedicated hooks for overviews REST API.
