### ISSUE TITLE
autoplay the next video in playlist

### ISSUE THREAD

**Issue by bikepunk** [Chocobozzz/PeerTube#2755]
I have a playlist 
(i.e https://tube.aquilenet.fr/videos/watch/playlist/e50b9b2e-a054-4e1e-90c1-079afede9311?videoId=145c1409-0833-4c12-9360-3da6975d7299 )

If I play as stanalone, the first video of the playlist, (https://tube.aquilenet.fr/videos/watch/145c1409-0833-4c12-9360-3da6975d7299) the next video in the playlist (or the playlist itself as it appears in youtube) shall be displayed in "Other videos" column.

Idealy if the first video of the playlist is played, the autoplay shall play the next video in the playlist.

At the moment, when you open the first video of the playlist, none of the others with the same tags and similar names are in "Other videos" column ?!

**Additional information**
* PeerTube version or URL: https://tube.aquilenet.fr/ 2.1.1
* Browser name/version:  Firefox 68.8.0esr (64-bit)

**Comment by Chocobozzz** [comment]
Hello,

This should be fixed in the next release (2.2)
