### ISSUE TITLE
adding "Share" buttons in the "My playlists" page

### ISSUE THREAD

**Issue by bikepunk** [Chocobozzz/PeerTube#2756]
While logged in, the "My playlists" page (https://tube.aquilenet.fr/my-account/video-playlists)
I would expect the "Share" buttons for each playlist next to "Delete" and "Edit"

I would also add a "Share" and a "Delete" buttons on the playlist page (i.e. on the red stars in the screenshot below)
https://tube.aquilenet.fr/my-account/video-playlists/e50b9b2e-a054-4e1e-90c1-079afede9311

![peertube2-etoile](https://user-images.githubusercontent.com/14958221/82066256-71cedb00-96cf-11ea-8aef-0dc662902e79.png)

**Additional information**
* PeerTube version or URL: https://tube.aquilenet.fr/ 2.1.1
* Browser name/version: Firefox 68.8.0esr (64-bit)

**Comment by wuniversales** [comment]
And RSS button :smile:

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/82f443de1aba70ce75c72a4a7f669385600ab3c6
