### ISSUE TITLE
Cookies disabled causes message "PeerTube is not compatible with your web browser"

### ISSUE THREAD

**Issue by alphapapa** [Chocobozzz/PeerTube#2757]
Using Chrome, when accessing https://spacepub.space/, with cookies blocked, the displayed page says:

```
We are sorry but it seems that PeerTube is not compatible with your web browser.

Please try with the latest version of Mozilla Firefox.

If you think this is a mistake, do not hesitate to report it.
```

After enabling cookies and reloading the page, it works normally.

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/6189b699fbc2d428d6baf09473356ed4568ea2a6
