### ISSUE TITLE
Synchronize configuration before the example and the Docker image

### ISSUE THREAD

**Issue by kaiyou** [Chocobozzz/PeerTube#276]
Currently the Docker image uses a separate ``production.yaml`` with sane default production values.
Unfortunately, that means that any new configuration setting needs to be mirrored in that file; this causes updates on ``develop`` to break the image because configuration cannot be found when loading the file.

I suggest we use the default configuration file in the image while customizing it a bit for production during build.

**Comment by Chocobozzz** [comment]
You can copy the `default.yaml` file and keep the `production.yaml` file too. `production.yaml` will override keys defined in `default.yaml` (or not if the keys are not specified).

**Comment by kaiyou** [comment]
Sound like the perfect fix. Thanks!
