### ISSUE TITLE
Store the videos in blockstack?

### ISSUE THREAD

**Issue by wuniversales** [Chocobozzz/PeerTube#2760]
Well, I have seen that servers (Instances) have limits to save videos, at most they can store up to 50GB per account.

My subjection is that peertube allows to store the videos in blockstack.
https://blockstack.org

The storage is **unlimited** so it can be used to save all the videos, in addition to this blockstack is **decentralized.**

Currently all my websites are hosted on runkod (Blockstack based service) and I have to say that it works great, I have unlimited everything, unlimited space, unlimited bandwidth, and my websites just work 24 hours.

I think it would be nice to take a look to see if this unlimited PeerTube storage can be integrated.

On the other hand it would be to use the IPFS with unlimited storage of infura.
https://infura.io/docs/ipfs/post/add
Related to #494

But I personally don't like it very much because IPFS doesn't consider it very stable.

Cheers

**Comment by JohnXLivingston** [comment]
The limit you are talking about is a per user or per instance choice. There is no technical limit.

**Comment by tilllt** [comment]
So is blockstack just a [TAHOE-Lafs](https://tahoe-lafs.org/trac/tahoe-lafs) hosting service or how is that connected? In any case usually all these distributed files systems have a fuse driver, so depending on the real world bandwidth, you can use them alread.

Out of curiosit, what is the maximum transfer rate (up / downlink) from a "commercial" distributed file system)?

**Comment by wuniversales** [comment]
> The limit you are talking about is a per user or per instance choice. There is no technical limit.

Sure, but if I, for example, am "PeerTuber" and upload a video every day in 4K or Full HD, my 50 GB would be consumed right away (Or the GB offered by the instance), so an "infinite space" solution would be needed "

To save costs to the instance I think it would be nice to be able to store the videos in blockstack (Gaia is called the unlimited "hard drive").
https://github.com/blockstack/gaia

> So is blockstack just a TAHOE-Lafs hosting service or how is that connected? In any case usually all these distributed files systems have a fuse driver, so depending on the real world bandwidth, you can use them alread.

I can't tell you exactly how it works, take a look at the "gaia" link (It's in the comment above).

> Out of curiosit, what is the maximum transfer rate (up / downlink) from a "commercial" distributed file system)?

Unlimited I understand, but I'm not sure.

**Comment by tilllt** [comment]
I meant speed, as in maximum MB/s

**Comment by Chocobozzz** [comment]
Hello,

We don't want to store videos in a blockchain.
