### ISSUE TITLE
Disable direct download and only offer torrent option

### ISSUE THREAD

**Issue by KeithCu** [Chocobozzz/PeerTube#2763]
I like the download video feature of Peertube, but I want it to only offer the torrent option. and disable the direct download feature. Everyone using our site will likely have a torrent client on their machine, and if not free ones are easy to find. However, people are lazy and won't really bother unless they are "forced" to.

I don't see this configuration option in Peertube 2.1.1.

**Comment by JensKorte** [comment]
How about a browser based torrent downloader which reuses the code from PeerTube? Could it be possible to save the data stream to HDD/SDD which is already in browser?

**Comment by Chocobozzz** [comment]
Hello,

With https://github.com/Chocobozzz/PeerTube/commit/118e1942e6e968ffb596ded67e79eebe33eeb6e1 you can create a plugin to alter the download modal. For example to hide the direct download option:

```
  registerHook({
    target: 'action:modal.video-download.shown',
    handler: () => {
      console.log('Video download modal shown')

      document.getElementById('download-torrent').checked = true
      document.getElementById('download-direct').parentElement.style.display = 'none'
    }
  })
```
