### ISSUE TITLE
Show title of videos with a content warning.

### ISSUE THREAD

**Issue by Golutazem** [Chocobozzz/PeerTube#2765]
There is often need to for a user to understand what the subject is or why a video is given a Content Warning. The title is usually helpful with this.
This feature could be implemented one of multiple ways:

- make the title always visible
- user option about whether to display title for CW posts
- separate CW attribute for title and video thumbnail

**Comment by Chocobozzz** [comment]
Closing this issue in favour of https://github.com/Chocobozzz/PeerTube/issues/6144
