### ISSUE TITLE
Dark theme text display is broken in edit mode

### ISSUE THREAD

**Issue by FredBezies** [Chocobozzz/PeerTube#2767]
**What happened?**

My pod -  https://peertube.pcservice46.fr/ - migrated to Peertube 2.2.0-rc1. I noticed text display using dark mode is broken.

See attached screenshot. Switching back to Peertube default theme fixes the display. I can see this bug in both Mozilla Firefox nightly and Chromium 83.

![Capture du 2020-05-20 07-43-35](https://user-images.githubusercontent.com/8571419/82409515-400e9900-9a6e-11ea-9bc1-93e6e85fb611.png)

**What do you expect to happen instead?**

Text display in dark mode :)

**Steps to reproduce:**

1. Just update your version to Peertube 2.2.0-rc1.

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/3bf07dd8c27aa6ef40111c6f055e8975b3f514f4 & https://github.com/Chocobozzz/PeerTube/commit/f33dc6ab2db1c733f09dcb039b8bf46c69854753

And update of the dark theme to version 2.2.2 will also be needed.

**Comment by FredBezies** [comment]
Thanks for the fix!
