### ISSUE TITLE
Question about Registration

### ISSUE THREAD

**Issue by TsymbalArtem** [Chocobozzz/PeerTube#2768]
Hello, I have been working with Peertube instance a week. There was "Create an account" button few days ago. Now I run the project with "yarn run dev" and there is no any sign up button. I found variables this.serverConfig.signup.allowed and allowedForCurrentIP, they are false both. So, please, tell me how i used sign up earlier if this variables were false? Now I manually changed them on true, registration button appeared but when I am trying to register new user it shows me the message "User registration is not enabled or user limit is reached.", I heave 10 users already. 
1. Why sign up button was earlier? 
2. How to increase the limit of users?
3. How to delete users?
4. What should I do in order to get sign up button visible without changing that variables manually?

Thank you for your prompt reply!

**Comment by Chocobozzz** [comment]
Go in the peertube admin interface -> `Configuration` and increase the signup limit

**Comment by TsymbalArtem** [comment]
@Chocobozzz Thank you so much! Btw where I can find admin panel?

**Comment by Chocobozzz** [comment]
In the left menu, at the bottom: `Administration`. You need to log in with `root` or another admin user
