### ISSUE TITLE
video player losing keyboard focus if clicked outside the player

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#2770]
**What happened?**
keyboard focus for keys like spacebar for pause/play, "F" for fullscreen. these buttons work when the page first loads, but if i click anywhere outside the video player, that focus is lost and pressing spacebar moves the page down, "f" does nothing. then i have to click on video player body and then the focus is regained
**What do you expect to happen instead?**
like youtube, even if i click outside the video player, spacebar and "f" keys should continue focus on video player and work as expected
**Steps to reproduce:**

1. load video. test "spacebar" and "f" buttons that they work.

2.now click outside the video player, like on thumbs up button or on video title

3. now try clicking "spacebar" and "F" key

**Additional information**
* PeerTube version or URL: https://peertube2.cpy.re/
* Browser name/version: 76.0.1 (64-bit) ubuntu
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/7ede74add2d41958f3aad0053afc812698f261a0
