### ISSUE TITLE
PeerTube can be installed on an intranet without an internet connection for use on an internal network?

### ISSUE THREAD

**Issue by discapacidad5** [Chocobozzz/PeerTube#2772]
I live in a place where there is no internet, the connections are very slow But we have a very large intranet network.
  I would like to be able to install this program, to use it to watch video on the intranet and to satisfy the demand of many people simultaneously without overloading the server.
  Will it be possible to install this program and use it on a server without an internet connection only with access to the internal network?

**Comment by Chocobozzz** [comment]
Hello,

No sorry we only have a matomo plugin. You can try to develop a GA plugin for peertube like we did for matomo: https://framagit.org/framasoft/peertube/official-plugins/-/tree/master/peertube-plugin-matomo

**Comment by JojoNowack** [comment]
@dos

> I live in a place where there is no internet, the connections are very slow But we have a very large intranet network.   I would like to be able to install this program, to use it to watch video on the intranet and to satisfy the demand of many people simultaneously without overloading the server.   Will it be possible to install this program and use it on a server without an internet connection only with access to the internal network?

Did it work? could you share usefull tipps?

**Comment by discapacidad5** [comment]
> @dos
> 
> > I live in a place where there is no internet, the connections are very slow But we have a very large intranet network.   I would like to be able to install this program, to use it to watch video on the intranet and to satisfy the demand of many people simultaneously without overloading the server.   Will it be possible to install this program and use it on a server without an internet connection only with access to the internal network?
> 
> Did it work? could you share usefull tipps?

Hi JojoNowack,

I installed PeerTube on an intranet without an internet connection for a farm in Venezuela. It worked great! We were able to upload videos, movies, and other information, including videos that explain how to do different farm tasks, cartoons for kids, and movies for adults.

**Comment by samsunatakum** [comment]
> > @dos
> > > İnternetin olmadığı bir yerde yaşıyorum, bağlantılar çok yavaş. Ama çok geniş bir intranet ağımız var. Bu programı kurmak, intranette video izlemek için kullanmak ve sunucuya aşırı yüklenmeden aynı anda birçok kişinin talebini karşılayabilmek isterim. Bu programı internet bağlantısı olmayan, sadece dahili ağa erişimi olan bir sunucuya kurup kullanmak mümkün olacak mı?
> > 
> > 
> > İşe yaradı mı? faydalı ipuçlarını paylaşabilir misiniz?
> 
> Merhaba JojoNowack,
> 
> PeerTube'u Venezuela'daki bir çiftliğin internet bağlantısı olmayan bir intranetine yükledim. Harika çalıştı! Farklı çiftlik görevlerinin nasıl yapılacağını açıklayan videolar, çocuklar için çizgi filmler ve yetişkinler için filmler de dahil olmak üzere videolar, filmler ve diğer bilgileri yükleyebildik.

Hi @discapacidad5 
How did you run peertube without internet?

can you help us ?

**Comment by discapacidad5** [comment]
> > > @dos
> > > > İnternetin olmadığı bir yerde yaşıyorum, bağlantılar çok yavaş. Ama çok geniş bir intranet ağımız var. Bu programı kurmak, intranette video izlemek için kullanmak ve sunucuya aşırı yüklenmeden aynı anda birçok kişinin talebini karşılayabilmek isterim. Bu programı internet bağlantısı olmayan, sadece dahili ağa erişimi olan bir sunucuya kurup kullanmak mümkün olacak mı?
> > > 
> > > 
> > > İşe yaradı mı? faydalı ipuçlarını paylaşabilir misiniz?
> > 
> > 
> > Merhaba JojoNowack,
> > PeerTube'u Venezuela'daki bir çiftliğin internet bağlantısı olmayan bir intranetine yükledim. Harika çalıştı! Farklı çiftlik görevlerinin nasıl yapılacağını açıklayan videolar, çocuklar için çizgi filmler ve yetişkinler için filmler de dahil olmak üzere videolar, filmler ve diğer bilgileri yükleyebildik.
> 
> Hi @discapacidad5 How did you run peertube without internet?
> 
> can you help us ?


Claro que sí, aquí hay una explicación en inglés más completa sobre cómo instalar PeerTube sin internet:

There are two main ways to install PeerTube on a server without internet:

1. Set up the server where there is internet:

Install PeerTube and all its dependencies on the server.
Configure PeerTube according to your needs.
Transfer the server to the location without internet.
2. Create a virtual machine (VM):

Create a VM on a computer with internet access.
Install PeerTube and all its dependencies on the VM.
Configure PeerTube according to your needs.
Transfer the VM to the server without internet.
Once PeerTube is installed, you can access it in two ways:

1. Local IP address:

Access PeerTube through the server's local IP address on a web browser.
2. Internal DNS server:

Set up an internal DNS server on the network.
Configure the DNS server to point the domain name to the server's IP address.
Access PeerTube using the domain name on a web browser.

I hope this information is helpful. Please let me know if you have any other questions.
