### ISSUE TITLE
LDAP Invalid grant: user credentials are invalid

### ISSUE THREAD

**Issue by takking168** [Chocobozzz/PeerTube#2773]
**Error**: LDAP Invalid grant: user credentials are invalid
**Error Message**: 
warn[5/22/2020, 10:15:28 AM] Cannot login m8888@example.com in LDAP plugin.

{
  "err": "no such user: \"m8888@example.com\""
}

warn[5/22/2020, 10:15:28 AM] Login error.

{
  "err": {
    "statusCode": 400,
    "status": 400,
    "code": 400,
    "message": "Invalid grant: user credentials are invalid",
    "name": "invalid_grant",
    "stack": "invalid_grant: Invalid grant: user credentials are invalid\n    at new InvalidGrantError (/var/www/peertube/versions/peertube-v2.2.0-rc.1/node_modules/oauth2-server/lib/errors/invalid-grant-error.js:27:14)\n    at /var/www/peertube/versions/peertube-v2.2.0-rc.1/node_modules/oauth2-server/lib/grant-types/password-grant-type.js:94:15\n    at tryCatcher (/var/www/peertube/versions/peertube-v2.2.0-rc.1/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v2.2.0-rc.1/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v2.2.0-rc.1/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v2.2.0-rc.1/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v2.2.0-rc.1/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/var/www/peertube/versions/peertube-v2.2.0-rc.1/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/var/www/peertube/versions/peertube-v2.2.0-rc.1/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v2.2.0-rc.1/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-v2.2.0-rc.1/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)"
  }

Version: peertube-v2.2.0-rc.1
OS: ubuntu-18.04.4-desktop-amd64.iso	
LDAP plugin: auth-ldap 0.0.3
Search filter: (|(mail={{mail}})(uid={{sAMAccountName}}))
Mail property: mail
Username property: sAMAccountName

Hi Sir.
Could you provide the document about how to configure the ldap in Peertube? Thanks.

**Comment by Chocobozzz** [comment]
What are the `Bind DN` and `Search base` values?

**Comment by takking168** [comment]
**Bind DN**: CN=testing,CN=Users,DC=example,DC=com
**Search base**: OU=example,OU=OU,DC=example,DC=com

**Comment by takking168** [comment]
The bind account is not in the same place with user.

**Comment by takking168** [comment]
> What are the `Bind DN` and `Search base` values?

**Bind DN**: CN=testing,CN=Users,DC=example,DC=com
**Search base**: OU=example,OU=OU,DC=example,DC=com

The bind account is not in the same place with user.

**Comment by Chocobozzz** [comment]
You should not replace `{{username}}` (peertube variable). Try to update the search filter: `(|(mail={{mail}})(sAMAccountName={{username}}))` instead

**Comment by takking168** [comment]
> You should not replace `{{username}}` (peertube variable). Try to update the search filter: `(|(mail={{mail}})(sAMAccountName={{username}}))` instead
I tried the config, it can read the correct account information, but I still cannot login. Does it need to configure other setting? Thanks.

warn[5/23/2020, 11:14:41 AM] Cannot find username property in LDAP plugin.
{
  "usernameProperty": "username",
  "user": {
    "dn": "CN=Jason,OU=example,OU=OU,DC=example,DC=com",
    "controls": [],
    "objectClass": [
      "top",
      "person",
      "organizationalPerson",
      "user"
    ],
    "cn": "",
    "sn": "",
    "st": "",
    "title": "",
    "description": "",
    "physicalDeliveryOfficeName": "",
    "telephoneNumber": "",
    "telexNumber": "",
    "facsimileTelephoneNumber": "",
    "givenName": "Jason",
    "distinguishedName": "CN=Jason,OU=example,OU=OU,DC=example,DC=com",
.....ignore

**Comment by Chocobozzz** [comment]
How do you configure your LDAP on other software? For example using CLI?

**Comment by takking168** [comment]
> How do you configure your LDAP on other software? For example using CLI?

I can use the LDAP login on Teampass system, my LDAP server type is windows active directory, does it need to modify anything else on Peertube system? Thanks.

**Comment by takking168** [comment]
I didn't use the CLI to configure LDAP before, if CLI configure is work on Peertube I will try, but please let me know how to do that, Thanks.

**Comment by Chocobozzz** [comment]
Sorry for the late. I misread the error message of https://github.com/Chocobozzz/PeerTube/issues/2773#issuecomment-632977659

Just use `sAMAccountName` for the `Username property` setting and `mail` for `Mail property` setting and it should work

**Comment by takking168** [comment]
> Sorry for the late. I misread the error message of [#2773 (comment)](https://github.com/Chocobozzz/PeerTube/issues/2773#issuecomment-632977659)
> 
> Just use `sAMAccountName` for the `Username property` setting and `mail` for `Mail property` setting and it should work

Yes, I checked the log, it can read the correct account information, but I still cannot login using domain account. Thanks.

**Comment by halatik** [comment]
set search filter to (|(mail={{mail}})(sAMAccountName={{username}}))  have resolved same issue on my instance. 
thanks @Chocobozzz

**Comment by getsueineko** [comment]
Good day.
I have same trouble too! 
Please help me set up ldap-plugin. There is no documentation with examples, I couldn't find any examples online either.
I have MS AD, domain example.local 
**Question in advance - should the registration permission setting be enabled in this case?**

After looking at https://github.com/Chocobozzz/PeerTube/issues/2773 I made the following settings.
However, I noticed this error in the logs (see below).

**My settings:**
```
Auth weight
100

URL
Starting with ldap:// or ldaps://
ldap://example.local:389

Insecure TLS [Marked]

Path to LDAP Server Certificate Chain of Trust

Bind DN
CN=sv_peertube,OU=ServiceAcc,DC-example,DC=local

Bind Password
P@$$w0rd

Search base
DC=example,DC=local

Search filter
(|(mail={{mail}})(sAMAccountName={{username}}))

Mail property
mail

Mail property index
If you have many results for the email attribute, you may define the index of the result to pick:
0

Username property
sAMAccountName

Group base
Fill the following settings to map PeerTube roles to LDAP Groups. LDAP users without any valid LDAP group will be by default refused login. Leave empty to let LDAP users join with default User role.

Group filter
(member={{dn}})

Administrator group DN
CN=Peertube Administrators,OU=IT,OU=Peertube,DC=example,DC=local

Moderator group DN
CN=Peertube Moderators,OU=IT,OU=Peertube,DC=example,DC=local

User group DN
CN=Peertube Users,OU=IT,OU=Peertube,DC=example,DC=local

No group matched login [Marked]
If no LDAP Group has matched, join with default User role
```

**LOGS:**
```
peertube-1  | [peertube.example.com:443 peertube-plugin-auth-ldap] 2024-09-04 13:53:50.565 warn: Cannot login john.smith@example.local in LDAP plugin. {
peertube-1  |   "err": {
peertube-1  |     "stack": "Error: connect EHOSTUNREACH 192.168.220.51:389\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)",
peertube-1  |     "message": "connect EHOSTUNREACH 192.168.220.51:389",
peertube-1  |     "errno": -113,
peertube-1  |     "code": "EHOSTUNREACH",
peertube-1  |     "syscall": "connect",
peertube-1  |     "address": "192.168.220.51",
peertube-1  |     "port": 389
peertube-1  |   }
peertube-1  | }
peertube-1  | [peertube.example.com:443] 2024-09-04 13:53:50.571 warn: Login error {
peertube-1  |   "err": {
peertube-1  |     "stack": "invalid_grant: Invalid grant: user credentials are invalid\n    at handlePasswordGrant (file:///app/dist/core/lib/auth/oauth.js:112:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async handleToken (file:///app/dist/core/controllers/api/users/token.js:32:23)",
peertube-1  |     "message": "Invalid grant: user credentials are invalid",
peertube-1  |     "statusCode": 400,
peertube-1  |     "status": 400,
peertube-1  |     "code": 400,
peertube-1  |     "name": "invalid_grant"
peertube-1  |   }
peertube-1  | }
peertube-1  | [peertube.example.com:443] 2024-09-04 13:53:50.572 info: 10.17.82.62 - - [04/Sep/2024:13:53:50 +0000] "POST /api/v1/users/token HTTP/1.0" 400 325 "https://peertube.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
peertube-1  | [peertube.example.com:443] 2024-09-04 13:53:50.605 error: Client log: Backend returned code 400, errorMessage is: Invalid grant: user credentials are invalid {
peertube-1  |   "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
peertube-1  |   "meta": "{\"url\":\"https://peertube.example.com/api/v1/users/token\"}",
peertube-1  |   "url": "https://peertube.example.com/login"
peertube-1  | }
peertube-1  | [peertube.example.com:443] 2024-09-04 13:53:50.606 info: 10.17.82.62 - - [04/Sep/2024:13:53:50 +0000] "POST /api/v1/server/logs/client HTTP/1.0" 204 - "https://peertube.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
peertube-1  | [peertube.example.com:443 peertube-plugin-auth-ldap] 2024-09-04 13:53:54.049 warn: Cannot login john.smith@example.local in LDAP plugin. {
peertube-1  |   "err": "no such user: \"john.smith@example.local\""
peertube-1  | }
```

**Comment by getsueineko** [comment]
@takking168  @halatik  hi!
can you share your settings? I have had no success so far

**Comment by halatik** [comment]
> @takking168 @halatik hi! can you share your settings? I have had no success so far

i´m so sorry we delete the instance 4 mounts ago.  In the past i try to get the right users filter over Softerra Ldap Browser-
if you get  right response for ldap query you can use it for PeerTube.  

 Follow setup Response chatgpt: 
# LDAP authentication configuration

# https://docs.joinpeertube.org/config-ldap-auth
 auth:
  ldap:
  enabled: true
  # Active Directory or LDAP server URL
    url: 'ldap://your-ldap-server.domain.com'  # Use 'ldaps://' for secure LDAP over SSL
   # Base DN for user search
    base_dn: 'dc=example,dc=com'
   # LDAP bind DN (service account)
   bind_dn: 'CN=ldapbind,CN=Users,DC=example,DC=com'
    # LDAP bind password (service account password)
    bind_password: 'YourServiceAccountPassword'
    # LDAP search configuration for users
   search:
     filter: '(sAMAccountName={{username}})'  # AD uses sAMAccountName for login
      base_dn: 'OU=Users,DC=example,DC=com'    # Base DN where your users are stored
     scope: 'sub'                            # Search in all subdirectories
    # LDAP attributes mapping
    attributes:
     username: 'sAMAccountName'  # The AD attribute for usernames
      display_name: 'cn'          # The common name (full name) for display
      email: 'mail'               # Email attribute in AD
    # LDAP Group/Role Mapping (Optional)
    group:
      base_dn: 'OU=Groups,DC=example,DC=com'   # Base DN for groups
      filter: '(member={{dn}})'                # Group membership filter
      group_to_role:
    'CN=Admins,CN=Users,DC=example,DC=com': 'admin'  # Admin role mapping
     'CN=Editors,CN=Users,DC=example,DC=com': 'moderator'  # Moderator role mapping

    # LDAP connection settings
    connection:
    timeout: 5000                            # LDAP connection timeout in milliseconds
    max_attempts: 5                          # Max connection retry attempts
    reconnect: true                          # Reconnect if the connection fails
    tls_options:
    rejectUnauthorized: false              # Disable certificate check (use caution)
