### ISSUE TITLE
Google Analytics Support?

### ISSUE THREAD

**Issue by peetss** [Chocobozzz/PeerTube#2774]
**What happened?**
Can't find any literature on including GA with a PeerTube instance.

I've tried adding to the script to the advanced JS configuration, to no avail.

Is there any way to add GA to a PeerTube instance?

**Comment by Chocobozzz** [comment]
Hello,

No sorry we only have a matomo plugin. You can try to develop a GA plugin for peertube like we did for matomo: https://framagit.org/framasoft/peertube/official-plugins/-/tree/master/peertube-plugin-matomo

**Comment by peetss** [comment]
Will do, thanks!

**Comment by kontrollanten** [comment]
If someone else is looking for GA support there's now a plugin https://www.npmjs.com/package/peertube-plugin-google-analytics
