### ISSUE TITLE
Endless video loading

### ISSUE THREAD

**Issue by Cooliq** [Chocobozzz/PeerTube#2775]
**What happened?**
When I open page with video, I have endless loading. Video start playing only if I click pause -> play or if I click on timeline.

**What do you expect to happen instead?**
Autoplay video on page

**Steps to reproduce:**
Open page - https://aoca.ru/videos/watch/ddf205c6-a466-41cd-9047-32495cbaacb8

**Additional information**
* PeerTube version or URL: https://aoca.ru
* Browser name/version: Firefox 76.0.1
* NodeJS version: v10.18.1

* Link to browser console log if useful: 
[browser-console-log.txt](https://github.com/Chocobozzz/PeerTube/files/4667901/browser-console-log.txt)

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
[peertube.log](https://github.com/Chocobozzz/PeerTube/files/4667909/peertube.log)

**Comment by Chocobozzz** [comment]
What is the ffmpeg version?

**Comment by Cooliq** [comment]
ffmpeg version 3.4.6

**Comment by Chocobozzz** [comment]
Upgrade to ffmpeg 4.1 and reupload your video (see https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L249)

**Comment by Cooliq** [comment]
Thank you for help. It's work.
