### ISSUE TITLE
"no such file or directory, open '/package.json'" when trying to fix federation through Docker

### ISSUE THREAD

**Issue by PopeRigby** [Chocobozzz/PeerTube#2778]
I'm trying to fix federation in my Dockerized PeerTube instance by following this:
https://docs.joinpeertube.org/#/maintain-tools?id=update-hostjs

I'm running this in Docker so I `sudo docker exec -it peertube`, and then when inside the container, I do `NODE_CONFIG_DIR=/app/config NODE_ENV=production npm run reset-password -- -u target_username`. The problem is, when I do that, I get this:
```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-22T17_49_41_513Z-debug.log
```

So it can't find `package.json`, but `package.json` is in `/app`. How do I get it to see `package.json`?

**Comment by PopeRigby** [comment]
Ok I figured it out, but I'm not sure if this should be closed because it might be a good idea to add this to the docs. If I just run `npm run update-host` without the `NODE_CONFIG_DIR=/app/config NODE_ENV=production`, it runs just fine.

**Comment by Chocobozzz** [comment]
I added in the doc examples of CLI commands when using Docker.
