### ISSUE TITLE
Debian install issue

### ISSUE THREAD

**Issue by fredhampton** [Chocobozzz/PeerTube#278]
I am running Debian and root access.
Are there install instructions for Debian.

When I start the server there is an error message that says user peertube could not be authenticated .

Thanks

**Comment by tcitworld** [comment]
Follow the instructions on the wiki with a regular user account (it uses sudo).

**Comment by Chocobozzz** [comment]
@fredhampton yes there is https://github.com/Chocobozzz/PeerTube#production
