### ISSUE TITLE
Graphical bug in video import interface

### ISSUE THREAD

**Issue by pprw** [Chocobozzz/PeerTube#2781]
I notice a small graphical bug in the log of youtube imported videos. It happens only for one job for which there is a column shift 

See:

![image](https://user-images.githubusercontent.com/5262986/82751405-3c08b100-9db7-11ea-8339-f0fe35e7ca48.png)

**Comment by rigelk** [comment]
I remember fixing it in the latest version. Please ask to reopen if you ran it in your test.

**Comment by pprw** [comment]
Thanks. I am still running 2.1.1. I will reopen this if the bug is still there when upgrading to 2.2.0.
