### ISSUE TITLE
Privacy-friendly captcha

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#2782]
Hello,

I'd like to protect myself against spam bots without compromising my user's safety. There are some captchas systems among the plugins, but no one seems to be sufficiently privacy-friendly.

Some privacy-friendly captchas are listed [here](https://swiso.org/replace/google-recaptcha/), i think you should add at least one of them.

**Comment by rigelk** [comment]
I tried adding a plugin based on captcheck but couldn't make captcheck work, and other suggestions on your page are mere libraries.

**Comment by JohnXLivingston** [comment]
I have begin to work on a svg-captcha implementation (https://www.npmjs.com/package/svg-captcha). But a feature was missing on peertube plugin system (ability to add custom routes). With the new 2.2.0-RC1, the missing feature is here. I have to find some time to work on it.

**Comment by Chocobozzz** [comment]
Closing since it's a plugin feature request, and not a peertube core feature request.
