### ISSUE TITLE
Unlist all videos

### ISSUE THREAD

**Issue by Nojus741** [Chocobozzz/PeerTube#2784]
Hello,

Just wanted to ask a question I hope it's the right place. Is there a fast way to unlist all of my instance videos? I assume the fastest way is to do a database querry? But what is the table/column I need to change?

Thanks.

**Comment by Chocobozzz** [comment]
> I assume the fastest way is to do a database querry

No because peertube needs to send an `Update` activity to other instances. You could write a script using the [REST API](https://docs.joinpeertube.org/#/api-rest-getting-started) to list and update videos.
