### ISSUE TITLE
I think I'm too clumsy / I don't speak English, probably translating, I lose part of the things I have to do.

### ISSUE THREAD

**Issue by discapacidad5** [Chocobozzz/PeerTube#2785]
I think I'm too clumsy
  I spent 5 days trying to install this program that has been impossible, someone could be an installation script or create a VirtualBox image to make installation easier for clumsy people like me

I don't have a domain because I can't generate a certificate for my cravings
  I can install it without using a certificate

I don't speak English, probably translating, I lose part of the things I have to do.

So I think a virtual image script is much more effective for clumsy people like me.

**Comment by Chocobozzz** [comment]
Hello,

We already provide a docker image so you can test peertube easily. But without a domain you won't be able to use peertube on production.

**Comment by discapacidad5** [comment]
Where can I get that image? 

this page is a YouTube Clone is a node, but it does not work with p2p they use a tube to give an installation with a public address

automatically once installed there is already an address with which you can publicly access behind a firewal without needing to have a public ip

this could be a good implementation idea

There is also a fully open sorce version of ngrok clone at this link

https://github.com/antoniomika/sish

https://github.com/mayeaux/nodetube
Using ngrok
NodeTube comes with ngrok preinstalled with the setting in .env.settings to run for new instances automatically. This means that when you boot the app you will see a log come through with a link where you can access the app from the ngrok subdomain. Great you're live on the internet, that was simple!

**Comment by rigelk** [comment]
@discapacidad5 ngrok is not fit for production deployments, especially for bandwidth-heavy applications like video streaming platforms. It will also cause federation errors once you decide to migrate to your own domain.

I suggest you read https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/docker.md to deploy PeerTube using docker.

**Comment by discapacidad5** [comment]
Install
PeerTube does not support webserver host change. Keep in mind your domain name is definitive after your first PeerTube start.

PeerTube needs a PostgreSQL and a Redis instance to work correctly. If you want to quickly set up a full environment, either for trying the service or in production, you can use a docker-compose setup.

Go to your peertube workdir
cd /your/peertube/directory  (here I don't know what to do I'm supposed to be starting an installation it tells me what directory this is or how I create it)


Tweak the docker-compose.yml file there according to your needs
vim ./docker-compose.yml  (absolutely nothing applies here what I should change or modify and how)

Then tweak the .env file to change the environment variables
vim ./.env
In the downloaded example .env, you must replace:

<MY POSTGRES USERNAME>
<MY POSTGRES PASSWORD>
<MY DOMAIN> without 'https://' (what should I put here if I don't have a domain I only have a pulbica IP)
<MY EMAIL ADDRESS>

You can use the regular up command to set it up
docker-compose up (I imagine that with this last Command my node should start.)

as you can see this tutorial is not well explained and detailed for clumsy people like me
is intended for people who have much more knowledge
  the possibility that other people like me can make use of this wonder is very limited
A more detailed tutorial or an easier system would be nice.
a script where the data is simply placed and the script makes all the modifications
It would help the project grow much more than it could be implemented by many more people.
Currently Unfortunately you have to have a lot of knowledge to be able to raise a node

even though I am a computer technician and I have created a website and many things I have not been able to create a node
and installed wordpress page
and installed many pages and installed many systems And this I can't install I think it should be easier

**Comment by rigelk** [comment]
@discapacidad5 then you should try installing PeerTube via YunoHost, which provides a turnkey solution and stays production-ready.

**Comment by discapacidad5** [comment]
> YunoHost

this alternative is truly spectacular
I already installed it and installed peerturbe and I could see the page and it even generated a public address for me
  but I have a problem and I don't know what the administrator password is
according to the tutorial an email should have arrived with the administrator password
But that did not happen. How can I get the administrator password to enter the page?

**Comment by discapacidad5** [comment]
> @discapacidad5 then you should try installing PeerTube via YunoHost, which provides a turnkey solution and stays production-ready.



Thank you very much for the support
  the truth that was the best solution for me
works great for me
I was able to solve the password problem by searching the bounced emails since the problem is that the mail client does not work for me That is why the mail did not arrive but it remained inside the server as bounced mail

So I could get the key to enter without any problem very satisfied with the program

again Thank you so much for the great work
