### ISSUE TITLE
own language of languages list items is not properly indicated thru attribute lang=".."

### ISSUE THREAD

**Issue by ele-gall-ac-mineducation** [Chocobozzz/PeerTube#2786]
**What happened?**

In the list of languages (i.e. in the main menu), each language item is written in its own language (which is OK). But it is read with the main language of the page or the voice synthesis own parameter if there's no one. Except for this language, the others aren't read with their own prononciation (Português is read Portugue/Portugues/Portuguez and not Portugue**sch**).

**What do you expect to happen instead?**

An attribute « lang=".." » with the code of the language:

<a **[lang]="{{lang.id}}"** *ngFor="let lang of languages" [href]="buildLanguageLink(lang)">{{ lang.label }}</a> (or something like that as I don't know TS)

https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/menu/language-chooser.component.html#L13

**Steps to reproduce:**

1. use https://ffoodd.github.io/a11y.css/ to diagnose

2. in any page of PeerTube, open the language menu

3. use a11y.css « Afficher les langues » in French (« Show languages » in English ?)

4. no item has is language defined by lang attribute

**Additional information**

https://developer.paciellogroup.com/blog/2016/06/using-the-html-lang-attribute/

working example:

https://developer.mozilla.org/en-US/docs/Learn/Accessibility

screencaptures:
![language bug mini](https://user-images.githubusercontent.com/54439757/82793821-d4fc0280-9e71-11ea-8d77-a1ea6ee73f10.png)
![language nobug MDN](https://user-images.githubusercontent.com/54439757/82793828-d7f6f300-9e71-11ea-9e07-80b51fec520b.png)

**Comment by Chocobozzz** [comment]
Fixed by @Pandoraaa in https://github.com/Chocobozzz/PeerTube/pull/2832
