### ISSUE TITLE
Getting videos from activities at a good resolution (or canonical/source one)

### ISSUE THREAD

**Issue by lanodan** [Chocobozzz/PeerTube#2787]
Peertube activities have multiple video resolutions in the `url` field, the sorting of them changed across versions (which also broke displaying them in pleroma as we naïvely used the position without checking).

Now instead of getting an okay resolution in the first video we get the worst one, and `height` is non-standard so I'd rather avoid using it for sorting, the `application/x-mpegURL` / `master.m3u8` is interesting but it's not supported in Firefox/Chrome (should work in WebKit but actually doesn't seems to).

One way would be to have something like `rel=canonical` but on the attachments, or maybe just have a good resolution at a constant position (ie. first or last).

Related pleroma MR: https://git.pleroma.social/pleroma/pleroma/-/merge_requests/2577

**Comment by Chocobozzz** [comment]
Hello,

https://github.com/Chocobozzz/PeerTube/commit/5072b9092284e96428ed919dbeed60c46dd96ba4 should fix your issue (best resolution video file is the first `video/mp4` element of the array).

If the admin enabled HLS, HLS raw files can also be found in the `tag` array of the `mediaType: application/x-mpegURL` `Link` object. For example:

```
{
  url: [
    ...other stuff...
    {
      "type": "Link",
      "mediaType": "video/mp4",
      "href": "http://localhost:9000/static/webseed/b566069b-a47a-490c-98b4-acaf4025ac4b-480.mp4",
      "height": 480,
      "size": 4368907,
      "fps": 24
    }
    ...other stuff...
    {
      "type": "Link",
      "mediaType": "application/x-mpegURL",
      "href": "http://localhost:9000/static/streaming-playlists/hls/b566069b-a47a-490c-98b4-acaf4025ac4b/master.m3u8",
      "tag": [
        ...other stuff...
        {
          "type": "Link",
          "mediaType": "video/mp4",
          "href": "http://localhost:9000/static/streaming-playlists/hls/b566069b-a47a-490c-98b4-acaf4025ac4b/b566069b-a47a-490c-98b4-acaf4025ac4b-480-fragmented.mp4",
          "height": 480,
          "size": 4357461,
          "fps": 24
        },
        ...other stuff...
      ]
    }
  ]
}
```

The admin can also disable WebTorrent. In this case, PeerTube will only send the `"mediaType": "application/x-mpegURL"` URL object (with the fragmented files in the `tag` array).
