### ISSUE TITLE
Add Matomo (ex-piwik) integration

### ISSUE THREAD

**Issue by ldidry** [Chocobozzz/PeerTube#279]
Could you add Matomo (the new name of piwik) integration ?

It needs two fields: the URL of Matomo instance, and the ID of the site in Matomo.

Then you add this in each page:

```
<!-- Matomo -->
<script type="text/javascript">
  var _paq = _paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//URL_OF_MATOMO_WITHOUT_HTTP(S)/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 'MATOMO_ID']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->
```

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/00b5556c182fa70dfca17c517488b8afae6257c9

**Comment by c-prompt** [comment]
I've troubleshooted this for a few days now and can't figure out the problem.

As a customization, if I add:

`"javascript": "console.log('this is a test');",`

...in /public_html/config/local-production.json and `systemctl restart peertube`, as expected, it prints _this is a test_ in the console. 

However, if I add instead:

`var _paq=_paq||[];_paq.push(['setDocumentTitle',document.domain+'/'+document.title]);_paq.push(['setCookieDomain','*.mysite.com']);_paq.push(['setDomains',['*.mysite.com','*.video.mysite.com']]);_paq.push(['enableCrossDomainLinking']);_paq.push(['trackPageView']);_paq.push(['enableLinkTracking']);(function(){var u='https://mysite.com/matomo/';_paq.push(['setTrackerUrl',u+'piwik.php']);_paq.push(['setSiteId','1']);var d=document,g=d.createElement('script'),s=d.getElementsByTagName('script')[0];g.type='text/javascript';g.async=true;g.defer=true;g.src=u+'piwik.js';s.parentNode.insertBefore(g,s)})();`

...the page view is not recorded in Matomo. (As a side note, mysite.com/matomo/ is on a different server but that shouldn't matter.)

Now, if I add:

`<script type="text/javascript" src="/client/en_US/matomo.js"></script>`

...right before the `</body>` tag in /versions/peertube-v1.0.1/client/dist/en_US/index.html and include the above Javascript in the matomo.js file, the page view is recorded in Matomo correctly.

So I'm not sure this enhancement is working properly.

**Comment by Chocobozzz** [comment]
Thanks @c-prompt, it seems that we cannot use matomo with the custom js peertube field (https://github.com/Chocobozzz/PeerTube/issues/1385#issuecomment-437412908). New issue to track this: https://github.com/Chocobozzz/PeerTube/issues/1385
