### ISSUE TITLE
Feature Request: Option for instance admins to make videos from other instances redundant 

### ISSUE THREAD

**Issue by wioxjk** [Chocobozzz/PeerTube#2793]
**What happened?**
I found a video on a remote instance, that loads very slowly. So I figured that I would manually make it redundant on my instance in order to get it to load faster later that day.

**What do you expect to happen instead?**

I expected to easily find a way to make my instance start seeding that video, but I did not find it.

**Steps to reproduce:**

1.
Try to manually make a video redundant via the webUI.

**Comment by Chocobozzz** [comment]
You'll have a dedicated button in the next release :https://github.com/Chocobozzz/PeerTube/releases

**Comment by wioxjk** [comment]
> You'll have a dedicated button in the next release :https://github.com/Chocobozzz/PeerTube/releases

Wonderful! 
Somehow I missed this in the roadmap and in the notes.
Thank you for your work!
