### ISSUE TITLE
PeerTube(LIVE) - empty validation email received

### ISSUE THREAD

**Issue by OrnithOrtion** [Chocobozzz/PeerTube#2794]
**What happened?**
I attempted to create an account on peertube (live) instance. 
I received a validation email with no content from *no-reply@peertube.live* with object:

> [PeerTube] Verify your email on peertube.live

**What do you expect to happen instead?**
I think I should receive a hypertext link to confirm my email and peertube account.
**Steps to reproduce:**

1. Go to [https://peertube.live/](https://peertube.live/)

2. Click on "créer un compte / create an account"

3. Fill in the entries (name, channel, etc.)

4. Confirm account

5. Wait for the validation mail

(... Here is the trick...)

Thank you a lot for your support, 
hopefully this report can help the community.

Samuel Ortion

**Additional information**
* PeerTube version or URL: https://peertube.live/
* Browser name/version: Version 81.0.4044.138 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (32-bit)
* NodeJS version: ??
* Link to browser console log if useful:  ?? Need tip to find it if you need it to sole the issue
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): I think I can't find that, can I ?

**Comment by OrnithOrtion** [comment]
It seems to be a bug of peertube.live only, as https://peertube.servebeer.com/ sent me a good email.
Maybe somebody have a contact to say them the issue I encountered.

**Comment by Chocobozzz** [comment]
Hello,

You can contact the admin on https://peertube.live/about/instance

We also redesigned emails in 2.2 (release next week)

**Comment by JohnXLivingston** [comment]
I think there is a bug... Another related issue: https://github.com/Chocobozzz/PeerTube/issues/2812

https://peertube.servebeer.com/ is in version 2.1.1. And I think https://peertube.live/ is 2.2.0-rc1 (can't check right now, the instance is down)
