### ISSUE TITLE
Use TailwindCSS for Peertube's UI?

### ISSUE THREAD

**Issue by thomaskuntzz** [Chocobozzz/PeerTube#2795]
Hi, just making a suggestion here: have you ever heard of [Tailwind CSS](https://tailwindcss.com/)? It's a really great CSS framework that you might want to consider using instead of Bootstrap to improve the UI of PeerTube (more customizeability and freedom, better developer experience, smaller size, responsiveness, etc.). The philosophy is however different: Tailwind CSS offers "utility classes" that you add to style elements (and that you can then compose into custom components) rather than just pre-made monolithic UI components (that are hard to customize or fix or modify if they need to be to integrated with other components) like Bootstrap. There are libraries of pre-made UI components built with Tailwind CSS that you can use, but they're much easier to customize and to polish than Bootstrap. (you can find many articles explaining what is Tailwind, how it works and why you might prefer it over Bootstrap)

It might be a really good option for PeerTube just like it might not fit the project's needs, I don't know, but I definitely encourage you to check it out! :wink: (trust me)

**Comment by rigelk** [comment]
I am also using TailwindCSS on small projects, and while their philosophy is very commendable, it is not proven to improve our UI simply by switching to it - a good framework doesn't equate good UI, which is more of a process than anything. More importantly, it is simply too much work for too little gained.

Thanks for the suggestion though 🙂

**Comment by thomaskuntzz** [comment]
You're right, the simple fact of using Tailwind doesn't improve the UI by itself, but what I was trying to say as succinctly as possible was that it gives you much more flexibility to improve it if you want than Bootstrap where it's hard to customize the components.

But no problem, I totally understand that it might not fit the project's needs, I was mentioning it just in case! 😉

Maybe it could be used when you need to modify Bootstrap's base styles though, instead of writing custom CSS? 🤔
