### ISSUE TITLE
Don't hide "Auto-Blacklist" tab in Moderation when Option to moderate content is turned off

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#2797]
**What happened?**
Users uploading videos getting auto-blacklisted, want to turn off option and just let users upload without moderation, but when I dont unblacklist any videos and turn off "Blacklist New videos Automatically" it hides the "Auto-Blacklist" from the tabs in the Moderation area.
**What do you expect to happen instead?**
I expect that tab to always be there, maybe show a message instead that nothing to show because moderation is turned off.

**Steps to reproduce:**

1.

2.

3.

**Additional information**
* PeerTube version or URL:
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
We don't hide it anymore, we now use the same view for all blacklisted videos.
