### ISSUE TITLE
Question:  Why doesn't the back end use webtorrent-hybrid?

### ISSUE THREAD

**Issue by faddat** [Chocobozzz/PeerTube#28]
@feross graces us with webtorrent-hybrid.  

What is peertube doing instead of using that?  I'm looking through the code, but am not getting it.

**Comment by Chocobozzz** [comment]
The server seeds the video through Webseed. So we don't need webtorrent-hybrid.

See https://github.com/Chocobozzz/PeerTube/issues/12

**Comment by faddat** [comment]
More and more content will be seeded on both in the future.  Why not expand
the swarm's reach?

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421
