### ISSUE TITLE
Missing registration button

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#2800]
I upgraded my instance to version 2.2.0-rc.1. After the update, the ability to register users has disappeared, but this function is enabled in the settings. The registration button has completely disappeared. Browser cache cleared. Is this a developer bug?

The local-pruduction.json file shows that the registration function is enabled.

```
  "signup": {
    "enabled": true,
    "limit": 10,
    "requires_email_verification": true
  },
```

**Steps to reproduce:**

1. Peertube v. 2.2.0-rc.1. https://peervideo.ru/videos/trending

2. Browser Firefox 76.0.1 (x64).

3. NodeJS v. 12.16.3

**Comment by Chocobozzz** [comment]
Did you check signups limit in admin configuration?

**Comment by Alterak** [comment]
> Did you check signups limit in admin configuration?

You're right. I increased the number of registration attempts in the settings, after which the registration button appeared. Thank.
