### ISSUE TITLE
Private channels members added / subtracted by admin 

### ISSUE THREAD

**Issue by nachodon** [Chocobozzz/PeerTube#2803]
Imagine instructional/teaching channels where channel owners can post material for (paying or selected) members only. Channels should have the ability to be accessed by “approved” or “manually added” members only.  Or course must be have “remove” member feature  by owner / channel admin as well.

A simple feature like this can enable small specialized creators with content delivery based businesses to manage their own member lists and payments while ensuring access is only granted to approved members - All without the need of their own url, website, etc. 

BONUS if this feature can be linked in the future to payment options and grant automated access. 

BONUS  if this can include a simple splash page of sorts for the member only channel which allows a preview video and other images to be posted along with instructions of how to be admitted into the main (presumably but not necessarily; paid) channel represented in splash page.

**Comment by Chocobozzz** [comment]
Hello,

It's difficult to implement such feature due to the federation, and it's not really in the scope of the project (right now). But you could create this kind of thing using the internal privacy setting of videos. Then you'll just have to create accounts to people that pay you.

**Comment by Cam-B** [comment]
I'm also interested in this topic. As Chocobozzz suggests the internal privacy setting is a good starting point.

As it is now. the simplest way is probably to use the "only people with the private link can see this video" option and then direct paying members to follow a "members only" mastodon account. where these links are posted.

**Comment by Thann** [comment]
I think that having a "members only" channel feature would provide a really good way for instances to be monetized.
