### ISSUE TITLE
Missing licence "All rights reserved"

### ISSUE THREAD

**Issue by Manu-REMY** [Chocobozzz/PeerTube#2804]
Hi,

What happened?
Some contents I share to my students need to be available only for them and are not supposed to be shared away. As example, I've shared some films of lessons in which students are involved (with their acceptance of course) and some corrections of exercises of students works to show the right way.
The licences currently available on peerturbe don't match to requirement of this videos to stay unshared.

What do you expect to happen instead?
I need to find the licence all right reserved in the list

Steps to reproduce:

1. Add a video

2. Specify licence

3. Can't find "All right reserved"

Additional information
* PeerTube version or URL : https://tube-montpellier.beta.education.fr/

Thanks
Emmanuel

**Comment by rigelk** [comment]
"All rights reserved" is not a license. You don't need to mention it either to hold copyright (more info on that [here](https://softwareengineering.stackexchange.com/a/313979)).

**Comment by Manu-REMY** [comment]
Ok
