### ISSUE TITLE
Allow creating a user without creating a channel

### ISSUE THREAD

**Issue by MCMic** [Chocobozzz/PeerTube#2805]
**What happened?**
When creating my account on a peertube instance, I’m asked a channel name and id after having chosen my user name and user id.

**What do you expect to happen instead?**
I expected this step to be optional and to be able to create my user account without creating a channel yet.

I understand that creating a channel is proposed when creating an account, but not why it is mandatory. I expect a lot of people will create an account not to upload videos but to watch and comment.
I may upload videos someday but I do not know yet on which subject so I cannot chose a channel name now.

After user creation, it seems I can actually delete the channel I was forced to create, but it warns me that I will never be able to use the same channel name again, which is frightening.
I should have been able to create my account without creating a channel, and without reserving a name that no-one can use again.
Even for inscances and federation this situation is bad because it results in lots of empty channels everywhere that will pop-up in search results and databases for no actual use.

**Additional information**
* PeerTube version or URL:
https://video.antopie.org/signup

**Comment by MCMic** [comment]
Related to #782 but not a duplicate.

**Comment by Chocobozzz** [comment]
Hi,

The channel step is optional when you register on PeerTube so I think I can close this issue.
