### ISSUE TITLE
Linear TV Channels 24/7

### ISSUE THREAD

**Issue by discapacidad5** [Chocobozzz/PeerTube#2806]
Linear TV Channels 24/7
Create a linear channel so that all viewers watch the same content at the same time, as in the traditional television.

Scheduler
Schedule the content of your channel at a fixed time on a weekly or daily basis.

The idea is that the contents are loaded As if it were a playlist where you can see what time each content will be played
because the time of each video is added and in this way you can control what time a certain video is played
  but it is a playlist only. It should be modifiable by the owner of the Channel, people will only see the player where it will be broadcast live as the owner of the Channel configured it.
  each video at the time you configured it but the videos will be taken from the videos that you have internally loaded on channel O of some other channel

I do not know if I am understood, remember that I do not speak English and use a translator, but my idea is more or less similar to what they do on television online, like the following channels.

https://viloud.tv/
https://www.ibm.com/products/video-streaming/details

I think p2p will work much better when all the people or a big part of the person is watching the same content at the same time
this will generate more pairs and of course it will be much more effective for the p2p network generating more efficiency

Instead of watching separate videos
  group people by channel, there will always be people watching the same channel that plays the same content at the same time.

and since the channel can be configured with video from its own instance or other people's instance, you could also be serving part of the exchange of content by channels with other people from other channels forming this great television p2p network

**Comment by Chocobozzz** [comment]
What's the difference with live streaming?

**Comment by discapacidad5** [comment]
Live streaming takes data in real time
this stream takes the preloaded video data
 the live stream needs to preload at least 10 seconds of live data while this stream what it does is put videos already loaded in order to play as a playlist but simulating a live stream
 making it much easier than live streaming since the video is preloaded or can be any video that is already loaded in the system
it is similar to a playlist with the difference that the playlist can select any video and in this format everyone sees the same video simultaneously
i don't know if i can explain in a playlist anyone can be watching separately and watch the video they want from the playlist
in this method people have to watch the same video at the same time as if it were a television channel

Imagine a playlist
 But what is controlled by the owner of the Channel and that is being broadcast, that is, people cannot enter the list and select the video they want to see, but the person who enters the list will see the video that is being played at that time.
in this way all the people when entering the playlist will simultaneously watch the same video
it's like if you go to see a television channel where they see what's going on at that moment
 the playlist is controlled by the owner of the Channel who decides which videos are going to be played at what time but it is not live, they are videos that are already loaded on the channel OR that are taken from another channel

While with a live stream, the video is not preloaded, but is loaded in real time as it is recorded. And that's what makes live streaming difficult with the p2p method.

 While this way as I am proposing it, there is no such difficulty, since the video exists complete loaded in the system is not in real time, what is in real time is the simultaneous transmission that forces everyone who is in that player are watching the same video
 this of course favors the p2p network because it makes more people be simultaneously watching the same video for that reason it would work much better
 there are many people who do not know what to watch and prefer to enter a channel and watch a pre-programmed transmission sequence


Excuse me if I am redundant in what I am saying but remember that I do not speak English my language is Spanish and that I am using the Google translator and I am aware that the Google translator does not do the best translation And that is what makes it difficult for understand what i want to explain

**Comment by discapacidad5** [comment]
Let's say the closest thing is a playlist that is broadcast synchronously among all viewers - there is no live playback but synchronous streaming forcing all viewers on the playlist to play the same video at the same time.

I would like you to understand what I mean for a live broadcast, you need programs like OBS Studio

while no program is required for this type of transmission that I propose

I left some links that I would like you to come in and look at. Where explained in English How pre-programmed video streaming works

**Comment by discapacidad5** [comment]
create playlists synced with time. This functionality allows you to simulate a TV Channel behavior where the playlist starting point varies according to the time of the day; therefore the term ("fake live").

 allows you to set the current Channel Playlist based on a date or day of the week. For example, you can create a time synced playlist for each day of the week and let the Scheduler change the Channel Playlist automatically (every day), thus achieving a TV-like behavior.



Every time a person enters the Channel Link, the system verifies the time and sends it to the video in the minute corresponding to the scheduled time.
in this way, every time someone enters, they will be watching the same video at the same time as other people on the same channel
Every time someone enters or updates the browser, it will synchronize with the rest of the people or with the central video. From that point on, continuous normal playlist play would continue from that starting point.
this would generate a fake live playlist to simulate the broadcast of a television channel where everyone watches the same video at the same time but without the player buttons only volume and mute

Here is a page that takes the YouTube playlist and makes it become a simulcast is a bit like what I am proposing with the difference that what I am proposing is controlled from the server and there is no need to load any previous list by the user but the list is already preloaded by the owner of the Channel.
https://streamforever.co/

**Comment by Chocobozzz** [comment]
Hello,

It's out of the scope of PeerTube (right now) but you can create your own sync platform using embeds. 2.4.0 will have ability to embed playlists, and using the [embed API](https://docs.joinpeertube.org/#/api-embed-player) you can control the player.
