### ISSUE TITLE
ALT+Arrow keys override browser history control

### ISSUE THREAD

**Issue by B0pol** [Chocobozzz/PeerTube#2810]
**What happened?**
I tried to press ALT+back arrow key, and the video went back 10s
**What do you expect to happen instead?**
ALT+back arrow key should go back to the previous page in your browser, like any other websites (that i know). 
ALT+forward arrow key should go the next page (if you already went back in browser history)
like these buttons  ![image](https://user-images.githubusercontent.com/58657617/83335706-daf94580-a2ae-11ea-98f2-39254c2bb465.png)
back arrow key **without ALT** should move the video backward
forward arrow **without ALT** key should move the video forward

**Steps to reproduce:**
a)

1. Go to the home page of any instance.

2. Click on a video and play it.

3. Press ALT+back arrow key.

you should be back to instance home page.

b)
1. make previous steps
2. press ALT+forward arrow key

you should be back to the video

**Additional information**
* PeerTube version or URL: 2.1.1
* Browser name/version: Firefox76

**Comment by B0pol** [comment]
as a workaround on firefox, go to about:config and set permissions.default.shortcuts to 2, it will change override shortcut permission for websites from allow to block

**Comment by kontrollanten** [comment]
Can we expand this issue to cover all shortcuts? Today all the shortcuts can be combined with ctrl, alt and cmd, which makes them collide with a lot of browser native shortcuts.

**Comment by kontrollanten** [comment]
Regarding the arrow keys it seems it's intended to [mimic VLC behavior](https://github.com/Chocobozzz/PeerTube/blob/9162476fe9fe022ff24bd42ff828aca7c68129ef/client/src/assets/player/peertube-player-manager.ts#L548-L559). I think most users are not used to use those shortcuts in web applications. Neither Youtube, Vimeo or Daily Motion has this behavior. What's your take on this, @Chocobozzz ?
