### ISSUE TITLE
The release date of an uploaded video/audio file can not set properly

### ISSUE THREAD

**Issue by Vertux** [Chocobozzz/PeerTube#2811]
**Steps to reproduce:**

1. Select a video/audio file for upload
2. Click in the field for the release date to make the calendar pop up

![Bildschirmfoto 2020-05-30 um 23 45 47](https://user-images.githubusercontent.com/10457918/83339600-e14be980-a2cf-11ea-85c8-a6f3db6ab659.png)

3. Choose the correct date and close the calendar

![Bildschirmfoto 2020-05-30 um 23 17 07](https://user-images.githubusercontent.com/10457918/83339601-e7da6100-a2cf-11ea-9a0c-92ad6dc9afa1.png)

4. Now the field for the release date shows an incorrectly formatted and incomplete date/time

![Bildschirmfoto 2020-05-30 um 23 16 54](https://user-images.githubusercontent.com/10457918/83339626-1f490d80-a2d0-11ea-9303-fea4578de2e2.png)

5. If you save all data, surprisingly the release date is displayed correctly on the the publication page of the video/audio file.

![Bildschirmfoto 2020-05-30 um 23 23 22](https://user-images.githubusercontent.com/10457918/83339633-30921a00-a2d0-11ea-9499-f4df425ea8ce.png)

**Additional information**
* PeerTube version or URL: v2.1.1
* Browser name/version: Firefox v76.0.1 MacO

**Comment by Chocobozzz** [comment]
Hello,

This is a translation issue you can fix on https://weblate.framasoft.org/translate/peertube/angular/de

I put `dd-mm-yy` but feel free to update accordingly to the german language
