### ISSUE TITLE
Add kabyle language

### ISSUE THREAD

**Issue by SelyanKab** [Chocobozzz/PeerTube#2813]
See: https://weblate.framasoft.org/languages/kab/peertube/

**Comment by Chocobozzz** [comment]
Thanks for your contribution. Added in https://github.com/Chocobozzz/PeerTube/commit/0bd558a0f9c7c6f1d5460e3792eaae663bf4f5e5

Should be available on https://peertube2.cpy.re/ in less than 24 hours

**Comment by BoFFire** [comment]
Thank you @Chocobozzz @SelyanKab :)
