### ISSUE TITLE
Have feeds be compatible with podcast apps.

### ISSUE THREAD

**Issue by rkingett** [Chocobozzz/PeerTube#2814]
I tried adding the XML feed to many podcast apps, but none of the content would play in the respected podcast apps. I'd like the ability for all channel feeds to work in podcast apps, as video podcasts or audio podcasts, or a choice.

**Comment by rigelk** [comment]
@rkingett do you have links to XML standards we should follow to work as "video podcasts", and do you have a list of podcast clients that would be compatible with it? It is the first time I've heard the expression "video podcasts".

As for audio podcasts, it seems Apple Podcasts has become the norm - would that be fine? If so, then there are plenty of validators for it, i.e. [this one](https://podba.se/validate/?url=https://peertube2.cpy.re/feeds/videos.xml?sort=-trending).

**Comment by rkingett** [comment]
It seems like you will have to make the XML feeds RSS feeds. Links are below.

Looks like making your RSS feed to Apple standards will work for everybody, including video podcasts.

* [Official RSS specs.](https://www.rssboard.org/rss-specification)
* [A guide on making your own RSS feeds.](https://www.thepolyglotdeveloper.com/2016/02/create-podcast-xml-feed-publishing-itunes/)
* [Another guide.](https://itconnect.uw.edu/learn/workshops/online-tutorials/web-publishing/podcastingvodcasting-distributing-your-audio-and-video-files-via-the-web-part-i/)
* [Guide from podcast CO.](https://www.podcast.co/create/podcast-rss-feeds)
* [A final guide](https://resourcecenter.odee.osu.edu/digital-media-production/how-write-podcast-rss-xml)

**Comment by Chocobozzz** [comment]
Hello,

It seems https://peertube2.cpy.re/feeds/videos.xml is valid according to https://podba.se/validate

@rkingett Could you retry with this feed? And if it still does not work, what podcast app do you use?

**Comment by rkingett** [comment]
The above feed you gave worked! I tried it on multiple podcast apps and it worked in all apps that allow subscribing to custom RSS feeds. I tried video, and audio only. Both worked.

**Comment by Chocobozzz** [comment]
Perfect. Thanks @rkingett
