### ISSUE TITLE
IPhone, iPad + Chrome browser  Full-screen button . It is not clicked.

### ISSUE THREAD

**Issue by zzoozzo1122** [Chocobozzz/PeerTube#282]
IPhone, iPad + Chrome browser  Full-screen button .(I frame)
 It is not clicked.

**Comment by Chocobozzz** [comment]
I'm not sure to understand.

Do you mean you cannot enter in fullscreen on Chrome for iPhone/iPad?

**Comment by lucaspontoexe** [comment]
I think this has something with the `"display": "fullscreen"` property in `manifest.json`.Changing to  `"display": "standalone"` might solve the problem.

**Comment by lucaspontoexe** [comment]
I had the same issue when the page is launched from the home screen.

**Comment by Chocobozzz** [comment]
PR welcome :)
