### ISSUE TITLE
Inaccurate health indicator in the instance list

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#2820]
Hello,
My instance had a long downtime, but is up since may 29 at 6:27 AM. Despite this, health indicator is at 23% instead of -at least- 50%. I don't understand why it's so low, i does not correspond to the reality.

**Comment by Chocobozzz** [comment]
Please use the appropriate bug tracker: https://framagit.org/framasoft/peertube/instances-peertube

**Comment by stemy2** [comment]
The said bugtracker seems to be not frequently consulted by any developer. Some question have been posted 1 year ago without any answer from them.

**Comment by rigelk** [comment]
@stemy2 you posted your issue yesterday. Please have patience.

**Comment by rigelk** [comment]
@stemy2 these are feature suggestions, not questions. In that case issues are kept until implemented or in need of precisions.
