### ISSUE TITLE
Peertube stopped working after a full disk incident

### ISSUE THREAD

**Issue by FathiBenNasr** [Chocobozzz/PeerTube#2821]
Hi,
I have a peertube instance running on a debian 10 container. It worked for several weeks and I enjoyed adding content to it. I started swapping personalized drupal content type for peertube embedded videos on our intranet, till i filled up the peertube container.
So, I added some space to the container and rebooted it, and then:

peertube@veedeo:~$ cd peertube-latest
peertube@veedeo:~/peertube-latest$ npm start
npm WARN npm npm does not support Node.js v10.19.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> peertube@2.1.1 start /var/www/peertube/versions/peertube-v2.1.1
> node dist/server
Could someone help me please ?

**Comment by Chocobozzz** [comment]
Did you install nodejs using https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions?

**Comment by FathiBenNasr** [comment]
Yes, I followed the link on that url to https://github.com/nodesource/distributions/blob/master/README.md and installed accordingly.

**Comment by Chocobozzz** [comment]
What is the output of `which npm`?

**Comment by FathiBenNasr** [comment]
I removed all packages related to node and reinstalled them. Also copying content to a remote server before restoring from a container backup.
which npm returns:
/usr/bin/npm

**Comment by Chocobozzz** [comment]
Run `rm -r node_modules && yarn install -pure-lockfile` with the `peertube` user

**Comment by FathiBenNasr** [comment]
peertube@veedeo:~/peertube-latest$ rm -r node_modules && yarn install -pure-lockfile
yarn install v1.22.4
error `install` has been replaced with `add` to add new dependencies. Run "yarn add -l -o -c -k -f -i -l -e" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by Chocobozzz** [comment]
Sorry, I made a typo. It's `--pure-lockfile` instead of `-pure-lockfile`. I edited my comment
