### ISSUE TITLE
Pourquoi voit-on tout l'historique quand on affiche un channel dans mastodon ?

### ISSUE THREAD

**Issue by mathieunicolas** [Chocobozzz/PeerTube#2824]
Bonjour !

Ce n'est pas un problème, plutôt une question.
J'ai remarqué en utilisant Writefreely qu'on ne voyait pas l'historique des posts d'un compte WF quand on le cherchait depuis mastodon (sans y être abonné donc). Le dev m'a expliqué que c'était ainsi que fonctionnait ActivityPub, mais j'ai remarqué que ce comportement n'était pas toujours ainsi.
J'ai pris l'exemple de peertube, dont les channels peuvent être cherchés depuis mastodon et dont on peut voir tout l'historique dès l'affichage du "profil" du channel dans n'importe quel client mastodon, sans y avoir été abonné au préalable.

Est-ce que quelqu'un pourrait m'expliquer succinctement pourquoi/comment ceci est possible, afin que peut-être je puisse transmettre l'information ?

Est-ce simplement parce que les chaînes que j'ai eu l'occasion de tester avaient déjà des abonnés sur mon instance mastodon ?

Merci beaucoup ! Bonne journée à vous, et longue vie à peertube !

**Comment by rigelk** [comment]
@mathieunicolas bonjour, je vous invite à vous rapprocher de la communauté de développeurs Mastodon, ce comportement y étant plus lié qu'à PeerTube.

**Comment by mathieunicolas** [comment]
D'accord ! Il me semblait que ce comportement "propre à peertube" (selon mon expérience en tous cas) pouvait peut-être venir d'une façon particulière de gérer la question.
Anyway, merci quand même pour votre réponse !
