### ISSUE TITLE
Error logs «unknown infoHash»

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2826]
**What happened?**
I just updated my instance to 2.2.0, and my logs are full of these:

`Jun 04 08:24:47 yiny peertube[25184]: [www.yiny.org:443] 2020-06-04 08:24:47.180 warn: Warning in tracker. {
Jun 04 08:24:47 yiny peertube[25184]:   "err": {
Jun 04 08:24:47 yiny peertube[25184]:     "stack": "Error: Unknown infoHash de3dfb71a2f8fcdca29b9e0c9b5e1df2fc1c7dac\n    at Server.<anonymous> (/var/www/peertube/versions/peertube-v2.2.0/dist/server/controllers/tracker.js:60:27)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v2.2.0/dist/server/controllers/tracker.js:5:58)",
Jun 04 08:24:47 yiny peertube[25184]:     "message": "Unknown infoHash de3dfb71a2f8fcdca29b9e0c9b5e1df2fc1c7dac"
Jun 04 08:24:47 yiny peertube[25184]:   }
Jun 04 08:24:47 yiny peertube[25184]: }
Jun 04 08:24:47 yiny peertube[25184]: [www.yiny.org:443] 2020-06-04 08:24:47.337 warn: Warning in tracker. {
Jun 04 08:24:47 yiny peertube[25184]:   "err": {
Jun 04 08:24:47 yiny peertube[25184]:     "stack": "Error: Unknown infoHash cb6343a4e7c3c14aeea8f5b9ed9f69218e53b4ff\n    at Server.<anonymous> (/var/www/peertube/versions/peertube-v2.2.0/dist/server/controllers/tracker.js:60:27)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v2.2.0/dist/server/controllers/tracker.js:5:58)",
Jun 04 08:24:47 yiny peertube[25184]:     "message": "Unknown infoHash cb6343a4e7c3c14aeea8f5b9ed9f69218e53b4ff"
Jun 04 08:24:47 yiny peertube[25184]:   }
Jun 04 08:24:47 yiny peertube[25184]: }
Jun 04 08:24:48 yiny peertube[25184]: [www.yiny.org:443] 2020-06-04 08:24:48.164 warn: Warning in tracker. {
Jun 04 08:24:48 yiny peertube[25184]:   "err": {
Jun 04 08:24:48 yiny peertube[25184]:     "stack": "Error: Unknown infoHash 9335e32e3727fef5ed5e509974b9ab8b5eff36bf\n    at Server.<anonymous> (/var/www/peertube/versions/peertube-v2.2.0/dist/server/controllers/tracker.js:60:27)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v2.2.0/dist/server/controllers/tracker.js:5:58)",
Jun 04 08:24:48 yiny peertube[25184]:     "message": "Unknown infoHash 9335e32e3727fef5ed5e509974b9ab8b5eff36bf"
Jun 04 08:24:48 yiny peertube[25184]:   }
Jun 04 08:24:48 yiny peertube[25184]: }
Jun 04 08:24:48 yiny peertube[25184]: [www.yiny.org:443] 2020-06-04 08:24:48.372 warn: Warning in tracker. {
Jun 04 08:24:48 yiny peertube[25184]:   "err": {
Jun 04 08:24:48 yiny peertube[25184]:     "stack": "Error: Unknown infoHash 3a912db073a51cc3a4f0e6f950bf4378713712f5\n    at Server.<anonymous> (/var/www/peertube/versions/peertube-v2.2.0/dist/server/controllers/tracker.js:60:27)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v2.2.0/dist/server/controllers/tracker.js:5:58)",
Jun 04 08:24:48 yiny peertube[25184]:     "message": "Unknown infoHash 3a912db073a51cc3a4f0e6f950bf4378713712f5"
Jun 04 08:24:48 yiny peertube[25184]:   }
Jun 04 08:24:48 yiny peertube[25184]: }`

I don't know what it mean, and I don't know if it is serious.

**Additional information**
* PeerTube version or URL: 2.2.0 https://www.yiny.org

**Comment by JohnXLivingston** [comment]
It seems that I have similar logs before updating. 500Mb of logs since yesterday. More than 1 million of these lines.

**Comment by JohnXLivingston** [comment]
I have hundreds of websocket connections, that are not peertube users (their IPs only appears on /tracker/socket). Could it be related?
These connections began one week ago. I don't know why.

**Comment by Chocobozzz** [comment]
Yes it is. It's because your tracker is `private` (https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L153) and someone else uses your tracker for an invalid torrent (an old video file of your instance or another unrelated torrent file).

**Comment by JohnXLivingston** [comment]
Okay. There are thousands of different hashes. How can I stop that?
It caused a DDOS last week, because there are too many open connections. I had to raise the nginx limit. 

Can I set reject_too_many_announces to true? Will it end this?

**Comment by JohnXLivingston** [comment]
I disabled my tracker to see if it changes something. I still have hundreds of connections, but my logs aren't spammed anymore.

I just take a look to the code. I don't understand why «Unknown infoHash» messages are logged, but not «Tracker is disabled on this instance». This is heavily spamming my logs.

Is there a way to prevent connections from clients that are not coming from peertube when tracker is set to private? Perhaps by checking if the IP as accessed another entry point?
The tracker is easily overloaded, and it can lead to a DDOS.

**Comment by JohnXLivingston** [comment]
bittorrent-tracker documentation says we can set a secret key for private trackers. Could it be easily done for peertube when tracker.private is true?

**Comment by JohnXLivingston** [comment]
> I just take a look to the code. I don't understand why «Unknown infoHash» messages are logged, but not «Tracker is disabled on this instance». This is heavily spamming my logs.

Found! When tracker is disabled, trackerServer.on('error') and trackerServer.on('warning') is not called, so it is not logging.

**Comment by JohnXLivingston** [comment]
For the record, here is the graph of my server TCP connection. 
![image](https://user-images.githubusercontent.com/38844060/83887249-7889c480-a748-11ea-9b38-4ca8bd6656e6.png)

I don't know why there is such an increase.

**Comment by JohnXLivingston** [comment]
We could add the IP in the log, so we could add a fail2ban rule to detect spamming IPs, and block them.
