### ISSUE TITLE
Torrent:  path is invalid

### ISSUE THREAD

**Issue by ddeenniiss** [Chocobozzz/PeerTube#2827]
**What happened?**
torrent file does not work

**What do you expect to happen instead?**

**Steps to reproduce:**

1. Download the .torrent

2. add it in Transmission

3. Nothing happens. The log:

Thu Jun  4 10:59:57 2020	error	GOUJONS  59/63 - VOFR - 69' - 2015 720p.mp4	L'entrée de métadonnées « path » est invalide
Thu Jun  4 11:00:43 2020	error		Impossible de connecter le connecteur 31 à 2607:5300:203:3459::, port 6881 (n° d'erreur 99 - Ne peut attribuer l'adresse demandée)
Thu Jun  4 11:00:43 2020	error		Impossible de connecter le connecteur 31 à 2607:5300:203:3459::, port 6881 (n° d'erreur 99 - Ne peut attribuer l'adresse demandée)
Thu Jun  4 11:00:49 2020	error		Impossible de connecter le connecteur 31 à 2001:200:1c8:f5d:1c44:ea9e:c25a:743a, port 36860 (n° d'erreur 99 - Ne peut attribuer l'adresse demandée)
Thu Jun  4 11:00:49 2020	error		Impossible de connecter le connecteur 31 à 2001:200:1c8:f5d:1c44:ea9e:c25a:743a, port 36860 (n° d'erreur 99 - Ne peut attribuer l'adresse demandée)

**Additional information**
* PeerTube version or URL: 2.2.0
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Please, use English so other people can understand your issue.

Could you paste the link of the video?

**Comment by ddeenniiss** [comment]
https://videos.domainepublic.net/download/torrents/b93e2a30-d02b-4283-a942-1a9a2049f553-720.torrent

**Comment by ddeenniiss** [comment]
For info, the problem is only present on some videos.

**Comment by Chocobozzz** [comment]
What is your version of Transmission?
