### ISSUE TITLE
How do I install Peertube locally on my Windows. I know NodeJS a bit but these commands are confuding. Can anyone Help ?

### ISSUE THREAD

**Issue by ali5152** [Chocobozzz/PeerTube#283]
Its not a bug/error. Need Help please !!

**Comment by Chocobozzz** [comment]
Sorry but Windows is not supported.

**Comment by ali5152** [comment]
That is understandable Thank you.

**Comment by ali5152** [comment]
Can you guide me with one thing.
Which online hosting or server client i should use for Peertube and by which 3rd party client ( Like Putty ) should I use to write all these terminals commands and Install Peertube.
