### ISSUE TITLE
Stretched thumbnails with some mobile browser

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2831]
**What happened?**
On my phone (firefox mobile on galaxy s9), thumbnails are stretched horizontally.

![image](https://user-images.githubusercontent.com/38844060/83876550-5472b700-a739-11ea-8c91-5dc3d40a4a58.png)

It began with the 2.2.0 version.
I can't reproduce with firefox desktop dev tools.
It happens even in private mode, so it is not a cache problem.
I have the same problem on several peertube instances (www.yiny.org and peertube.live for example).
I don't have this issue with peertube 2.1.0.

**Additional information**
* PeerTube version or URL: 2.2.0
* Browser name/version: Firefox mobile 68.8.1
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by scanlime** [comment]
I was going to report this too. Started happening after upgrading to 2.2.0, seeing the stretched thumbnails with mobile firefox on Android.

**Comment by Chocobozzz** [comment]
Please try on https://peertube2.cpy.re/

I think I fixed this in https://github.com/Chocobozzz/PeerTube/commit/cf78883c70dca99fc519374d55620d9403d482be

**Comment by scanlime** [comment]
Looks good here! Thanks.
