### ISSUE TITLE
Question about video transcoding

### ISSUE THREAD

**Issue by vmario89** [Chocobozzz/PeerTube#2836]
Hi,
as organization we started to run an instance of peertube. After uploading a lot of videos we recognized that videos often play slowly when connection is bad. For this reason we enabled 240p resolution and HLS in settings to enable low qualy video streams. Now the problem: how do i re-transcode all the videos which were uploaded automatically? The old videos are 1080p only.

It seems to work only for newer uploads. There you can switch between 1080/240p

regards, Mario

**Comment by rigelk** [comment]
There is a script for that, which you have to run manually in the CLI.
