### ISSUE TITLE
`TextEncoder is not defined` in Edge 18

### ISSUE THREAD

**Issue by bartwr** [Chocobozzz/PeerTube#2839]
**What happened?**

In noticed that Edge 18 does not play HSL encoded videos when embedded using `@peertube/embed-api`.

- I open *Edge 18* (an old browser that doesn't auto update to newer versions yet)
- I visit a page having an embedded video transcoded for HSL
- I get the error: `TextEncoder is not defined`
- The player controls don't show up for the video

![image](https://user-images.githubusercontent.com/899234/83973184-03072b00-a8e5-11ea-81f9-757ddb2ccee3.png)

**What do you expect to happen instead?**
- The player controls appear, so I can play the video in Edge 18

**Steps to reproduce:**

1. Open *Edge 18*
2. Visit a page having a HSL transcoded video embedded using `@peertube/embed-api`
3. See the error appear

**Additional information**
* PeerTube version or URL: 2.1.1
* Browser name/version: Edge 18

## What we need

As @RaschidJFR [[1]](https://github.com/kchapelier/in-browser-download/issues/1#issuecomment-554156877) and moritzgv [[2](https://forum.genvidtech.com/t/textdecoder-is-not-defined-ie-edge-support/148/4)] mention we need a TextDecoder [polyfill](https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/pollyfils-for-stompjs-v5.html).

## What I tried

I added this JavaScript customization via the Advanced Configuration tab, at `https://YOUR_PEERTUBE_URI/admin/config/edit-custom`:

```/* TextDecoder for Edge */

var script = document.createElement("script");
script.type = "text/javascript";
script.src = "https://cdn.jsdelivr.net/npm/text-encoding@0.6.4/lib/encoding.min.js";
document.head.appendChild(script);

if (!window['TextDecoder']) {
  window['TextDecoder'] = TextDecoder;
}
```

This didn't help solving the `TextEncoder is not defined` error.

__

Summary:
- Edge 18 needs a TextEncoder polyfill to play videos transcoded for HSL.
- What's the best place to add this?

**Comment by Chocobozzz** [comment]
Hello,

This should be fixed in 2.2.
