### ISSUE TITLE
Video synchronization across peers

### ISSUE THREAD

**Issue by HugoSPT** [Chocobozzz/PeerTube#284]
Hi,

I'm trying to understand if PeerTube fits in a project I am working on.

I have a couple of videos I would like to play on a website. The only requirement is: every person visiting the website starts watching the video at the exact same point other person is watching it. So it is broadcasting.

Is this possible to achieve using PeerTube?

Thank you,
Hugo Sousa

**Comment by Chocobozzz** [comment]
Your video is just a file? Or is it a stream?

**Comment by HugoSPT** [comment]
@Chocobozzz multiple files that should play in loop (sequentially?) No streams.

**Comment by Chocobozzz** [comment]
I think peertube lacks support of timestamp (https://github.com/Chocobozzz/PeerTube/issues/271) for your use case. But I don't think it should be hard to implement.

**Comment by HugoSPT** [comment]
I think I'm going to figure out a way to do this. Already managed to start a video in a given timeframe so just need to do the logic on the server side that will send the currentTime when the video is requested.

There is any way to start playing a new video when the current one finishes?

Thank you for your promptly response, really nice support!

**Comment by Chocobozzz** [comment]
> There is any way to start playing a new video immediately after the current one finishes?

Not yet sorry. I think it will come with the playlist feature.
