### ISSUE TITLE
Backup Upload should refer to the ID of the original upload

### ISSUE THREAD

**Issue by gloschtla** [Chocobozzz/PeerTube#2846]
How to easily find disappeared YouTube videos? The answer is: Users intending to re-upload videos to any PeerTube instance, should be obliged to tag it with the original ID given by the original video platform. For example: V6HGGM4HsXw from YouTube, and x7ucw4i from DailyMotion! So, if I google-search for one of those ID codes, I expect to find the video on a meta platform comprising all PeerTube instances.

**Comment by Chocobozzz** [comment]
Hello,

You can create such thing using a plugin I guess.
