### ISSUE TITLE
PeerTube is not suitable for mobile data.

### ISSUE THREAD

**Issue by gloschtla** [Chocobozzz/PeerTube#2848]
Where are the down-scaled videos? Why are there only FullHD videos?
Where to get the stream-able audio-only track? Is there any podcast [app](https://docs.joinpeertube.org/#/use-third-party-application) based on peertube content?

I quote @rigelk: _As for your points, it depends on the instance you experience PeerTube with. Admins are free to enable/disable certain video resolutions, including mobile-friendly ones. The same goes for audio versions of the video._

**Comment by Chocobozzz** [comment]
@rigelk answered you.
