### ISSUE TITLE
Merge all video/audio frame sizes into one single webTorrent.

### ISSUE THREAD

**Issue by gloschtla** [Chocobozzz/PeerTube#2849]
I see a problem with the P2P principle: If one client watches the 1080p version of a video, he will P2P-upload only 1080p frames of it. Other clients, who are watching the 720p version of the same video, will P2P-upload only 720p frames. Is there a method to reduce the frame size on the fly? 

Example: 
Client 1 shares some 1080p frames to the P2P community (and rather has a higher upload speed than other clients).
An interface in the Torrent Network is able to convert (decentrally buffered) 1080p frames into 720p frames.
Client 2 gets 720p frames from Client 1 after they were down-scaled through the converter.
Client 3 gets audio-only frames from client 1 & 2, because he prefers the data-optimized podcast version of the original video, since he has a throttled internet download speed.

If the original file on the central server of the originating PeerTube instance goes offline (e.g. caused by server overload), the video still can be streamed in all scales through the decentral P2P network.

Otherwise there must be a way to automatically torr-mirror all versions of the original video into the federated PeerTube instances, as soon as it gets relevant to the community. This issue refers to [this one](https://github.com/Chocobozzz/PeerTube/issues/2848).

EDIT:
There might be this solution: The original video is offered as single streams of multimedia, which are all contained in one "flexible" container. The clients download the amount of streams depending on their upload speed.

The original video could contain these streams: mono-audio OPUS, stereo-audio AAC, FFmpeg (as 360p, 480p, 720p and 1080p). A P2P client with very low upload-speed would download only memory-saving streams of the video container - for example only the mono-audio stream. A P2P client with high upload-speed would download all stream sizes of the same video container, while watching only 720p or larger. And there should be one single torrent file for this flexible video container.

**Comment by rigelk** [comment]
> Otherwise there must be a way to automatically torr-mirror all versions of the original video into the federated PeerTube instances, as soon as it gets relevant to the community.

You are more or less talking about the mirroring/duplicating feature. This is already implemented and any PeerTube instance can enable mirroring of single videos or whole instances/most-viewed videos on friend instances.

> An interface in the Torrent Network is able to convert (decentrally buffered) 1080p frames into 720p frames.

It is simpler to just cache the already transcoded resolutions of a video (which is done by the above feature), since converting (transcoding) is a costly operation which would be out of scope of a cache server.

> The clients download the amount of streams depending on their upload speed.

Having one manifest containing all videos would lead to all files being downloaded, which means more data taken from your data plan, which is the real problem on mobile connections.

**Comment by gloschtla** [comment]
Thank you for giving this info! One question about:
> Having one manifest containing all videos would lead to all files being downloaded, which means more data taken from your data plan, which is the real problem on mobile connections.

Is there no way to implement this feature into the webTorrent feature of PeerTube? 
I mean: One torrent containing all sizes of streams of the same video, AND: Clients connected with mobile data are able to download only the smallest version of the streams contained in this torrent. Clients connected with LAN can download all streams contained in this torrent, if they have a good upload speed.
