### ISSUE TITLE
Unable to Edit Configuration Through Admin Interface

### ISSUE THREAD

**Issue by cclloyd** [Chocobozzz/PeerTube#2850]
**What happened?**

No matter what I change the settings to (including not changing anything at all), I get the error 

> It seems like the configuration is invalid. Please search for potential errors in the different tabs.

and the save configuration button is greyed out.

&nbsp;

**What do you expect to happen instead?**

I can edit and save configuration

**Additional information**
* PeerTube version or URL: 2.2.0
* Browser name/version: Chrome 83
* NodeJS version: 10.20.1

My full manifests for the Kubernetes deployment can be found in the following gist: 
https://gist.github.com/cclloyd/5f023168309ffa905957f3dae8c15557

**Comment by Chocobozzz** [comment]
Hello,

See https://github.com/Chocobozzz/PeerTube/issues/1795#issuecomment-637546144

I suggest you to subscribe to peertube-admin mailing list: https://framalistes.org/sympa/subscribe/peertube-admin
