### ISSUE TITLE
completeMarkdownToHTML not a function

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#2855]
I am trying to render markdown with H1, images and html tags but its not letting me.

Tried using this function:
https://github.com/Chocobozzz/PeerTube/blob/c7f36e4f485d92191b9d04c6a880724b02fa220b/client/src/app/shared/renderer/markdown.service.ts#L74

```
const html = await peertubeHelpers.markdownRenderer.completeMarkdownToHTML(c['landing-page-markdown_text'])
```

But it gives me an error:
```
Cannot run hook action:router.navigation-end of script /plugins/landing-page-markdown/0.0.1/client-scripts/client/common-client-plugin.js of plugin landing-page-markdown. TypeError: peertubeHelpers.markdownRenderer.completeMarkdownToHTML is not a function
    at handler (common-client-plugin.js:20)
```

**Comment by Chocobozzz** [comment]
Check https://docs.joinpeertube.org/#/api-plugins?id=client-register

It's `peertubeHelpers.markdownRenderer.enhancedMarkdownToHTML`
