### ISSUE TITLE
Account Settings page snaps to url handle

### ISSUE THREAD

**Issue by cclloyd** [Chocobozzz/PeerTube#2858]
**What happened?**

When viewing account settings, if there is a page handle (like `#video-settings`) in the URL, it will snap to that handle on various actions.

**What do you expect to happen instead?**

It does not scroll the page when doing actions like hitting the save button (even in other sections), or hovering over the tabs at the top of the settings page.

**Steps to reproduce:**

1.  Click the 3 dots on your profile on the left > click sensitive videos. 

2.  Click 'save' in any section, and it will snap to the header you initially loaded on.  Also hovering over the tabs at the top (such as Misc) will make it snap.

**Additional information**
* PeerTube version or URL: 2.2.0
* Browser name/version: Chrome 83

**Comment by Chocobozzz** [comment]
Thanks for the issue. Fixed in https://github.com/Chocobozzz/PeerTube/commit/64e0f8cf12c804a7a2fa582fd954f686cea9a45b
