### ISSUE TITLE
overviews page MaxPage needs to be admin config field

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#2859]
https://github.com/Chocobozzz/PeerTube/blob/111fdc267b36201cf1be1fdf91017005102b4a5e/client/src/app/videos/video-list/video-overview.component.ts#L23

needs to be configurable for the admin interface

**Comment by rigelk** [comment]
> needs to be configurable for the admin interface

I can *imagine* why, but issues are here to document *your* needs. Could you expand on why it is needed in your use case?

**Comment by McFlat** [comment]
I would love to be able to scroll forever until all the tags, and channels and whatever else runs out, not limit it at some number, my site troo.tube has more local videos than any other peertube site and so when it comes to hosting lots of videos and channels things have to be done at scale to be efficient

**Comment by Chocobozzz** [comment]
Closing in favour of https://github.com/Chocobozzz/PeerTube/issues/3582
