### ISSUE TITLE
Application Web Progressive via Android Firefox, landscape screen not working

### ISSUE THREAD

**Issue by svnet-libre** [Chocobozzz/PeerTube#286]
* **PeerTube version or commit:**
0.23
* **Browser name/version:**
Firefox 58 for Android 7.0

Hi,
Peertube in mode "Application Web Progressive" not working on my Galaxy Tab with the landscape screen
![screenshot_20180209-204606](https://user-images.githubusercontent.com/15374977/36047239-be6220e6-0ddb-11e8-9f4e-a31ba2167842.jpg)
![screenshot_20180209-205924](https://user-images.githubusercontent.com/15374977/36047379-32aec4ea-0ddc-11e8-9061-5b5663dd2bd1.png)

**Comment by Chocobozzz** [comment]
Fixed: https://github.com/Chocobozzz/PeerTube/commit/879ea0f7954d2eef9fd40464ea45fc600597ee38

Thanks @lucaspontoexe!
