### ISSUE TITLE
La fin des instances NSFW ?

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#2863]
Bonsoir,

Il existe un projet de loi en France qui forcera les sites qualifiés de pornographiques à devenir payants, officiellement pour empêcher les mineurs de les consulter. [Plus d'infos ici](https://www.madmoizelle.com/amendement-porno-mineurs-1056007)

Est-ce que ça ne signerait pas la fin des instances NSFW ? Devront-elles choisir entre mettre en place un accès payant -donc s'amputer d'une partie de son audience- ou disparaître ? Un accès payant à un instance perrtube est-il seulement possible ?

**Comment by JohnXLivingston** [comment]
Le forum francophone est ici : https://framacolibri.org/c/qualite/peertube
