### ISSUE TITLE
Video player plays automatically with sound muted

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#2865]
**What happened?**
Video player starts playing videos automatically but with sound muted on on iPhone 7 plus
**What do you expect to happen instead?**
I expect to not have to unmute the sound to listen and watch every video I want to watch

**Steps to reproduce:**

1. select any video to watch from mobile chrome or safari iOS iPhone7 plus

2. notice video starts playing with sound muted

3.

**Additional information**
* PeerTube version or URL: https://troo.tube
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Please try 2.2 version
