### ISSUE TITLE
Warn the user that they are going to delete videos when deleting a channel

### ISSUE THREAD

**Issue by bristow** [Chocobozzz/PeerTube#2876]
Today on my instance, a user accidentally deleted 54 'unlisted' videos by deleting a channel he thought was empty.
Indeed, the number of videos is not visible when deleting because they are unlisted.
This also refers to this ticket : https://github.com/Chocobozzz/PeerTube/issues/2747

Maybe we can add the number of videos contained in the channel at the time of deletion (in the modal)?

Thanks a lot !

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/1ba471c55fdbf05ef2c10152b3e4b0c5d8da3213
