### ISSUE TITLE
Option of changing 'Default policy on videos containing sensitive content' from the Settings page doesn't work

### ISSUE THREAD

**Issue by k09i71** [Chocobozzz/PeerTube#2877]
**What happened?**
Option of changing 'Default policy on videos containing sensitive content' from the Settings page doesn't work
**What do you expect to happen instead?**
Option of changing 'Default policy on videos containing sensitive content' from the Settings page should work, one should be able to change it from 'blur' to 'hidden' or 'display'.

**Steps to reproduce:**

1. https://peertube.iriseden.eu/videos/trending

2. spot a video which has a blurred thumbnail but don't click on it

3. got to settings

4. change ''Default policy on videos containing sensitive content' from 'blur' to 'hide'

5. refresh the page

6. try to spot the same video and you'll see that it's still blurred, not hidden

**Additional information**
* PeerTube version or URL: https://peertube.iriseden.eu/videos/trending
* Browser name/version: firefox 76

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Thanks, should be fixed in https://github.com/Chocobozzz/PeerTube/commit/5c20a45518c3afc40c9494cad4a78def92e5e288
