### ISSUE TITLE
Package PeerTube as a Flatpak or AppImage

### ISSUE THREAD

**Issue by k09i71** [Chocobozzz/PeerTube#2878]
**It's possible to use these two formats for web-based apps:**

_AppImage_

- https://discourse.appimage.org/t/is-appimage-spec-suitable-to-pack-and-runs-multiple-servers/1045
- https://discourse.appimage.org/t/is-appimage-suitable-for-a-multi-service-web-application-like-erpnext/1497

_Flatpak_

> Can Flatpak be used on servers too?
> 
> Flatpak is designed to run inside a desktop session and relies on certain session services, such as a D-Bus session bus and, optionally, a systemd --user instance. This makes Flatpak not a good match for a server.
> 
> However, the build features of Flatpak run fine outside a session, so you can build things on a server.

https://flatpak.org/faq/

**Why?**

Because this would simplify the process of installing PeerTube on a server.

**How?**

If you wanna package it as an _AppImage_ - https://docs.appimage.org/packaging-guide/introduction.html
If you wanna package it as a _Flatpak_ - https://docs.flatpak.org/en/latest/first-build.html

**Comment by Chocobozzz** [comment]
Hello,

We don't want to officially support another package installation. But if you want to, you can add your instructions on https://docs.joinpeertube.org/#/install-unofficial
