### ISSUE TITLE
Error: The node binary used for scripts

### ISSUE THREAD

**Issue by TsymbalArtem** [Chocobozzz/PeerTube#2880]
Hello, I do npm run build -- --light, then yarn run test and I get next errors:
> peertube-client@2.1.1 lint-scss /home/artem/peertube/versions/ting/client
> sass-lint -c .sass-lint.yml

  Test misc endpoints
    1) "before all" hook in "Test misc endpoints"
    2) "after all" hook in "Test misc endpoints"

  0 passing (367ms)
  2 failing

  1) Test misc endpoints
       "before all" hook in "Test misc endpoints":
     Error: npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1592253369578-0.46398186998067725/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

      at child_process_1.exec (shared/extra-utils/server/servers.ts:82:44)
      at ChildProcess.exithandler (child_process.js:285:7)
      at maybeClose (internal/child_process.js:982:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

  2) Test misc endpoints
       "after all" hook in "Test misc endpoints":
     TypeError: Cannot read property 'app' of undefined
      at killallServers (shared/extra-utils/server/servers.ts:264:17)
      at Object.cleanupTests (shared/extra-utils/server/servers.ts:272:3)
      at Context.<anonymous> (server/tests/misc-endpoints.ts:174:11)
      at Generator.next (<anonymous>)
      at /home/artem/peertube/versions/ting/server/tests/misc-endpoints.ts:8:71
      at new Promise (<anonymous>)
      at __awaiter (server/tests/misc-endpoints.ts:4:12)
      at Context.<anonymous> (server/tests/misc-endpoints.ts:162:16)

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Could you help me please

**Comment by rigelk** [comment]
Did you modify/add files in the config directory?

**Comment by TsymbalArtem** [comment]
modified:   client/src/app/+signup/+register/register-step-user.component.html
        modified:   client/src/app/+signup/+register/register-step-user.component.ts
        modified:   client/src/app/+signup/+register/register.component.html
        modified:   client/src/app/+signup/+register/register.component.ts
        modified:   client/src/app/core/auth/auth.service.ts
        modified:   client/src/app/login/login.component.html
        modified:   client/src/app/login/login.component.ts
        modified:   client/src/app/menu/menu.component.html
        modified:   client/src/app/menu/menu.component.ts
        modified:   client/src/app/shared/users/user.service.ts
        modified:   package.json
        modified:   server.ts
        modified:   server/controllers/api/users/index.ts
        modified:   server/middlewares/validators/users.ts
        modified:   yarn.lock


So I didn't, by the way now I Have another error:
> sass-lint -c .sass-lint.yml



  Test a client controllers
    1) "before all" hook for "Should have valid Open Graph tags on the watch page with video id"
    2) "after all" hook for "Should have valid index html updated tags (title, description...)"


  0 passing (354ms)
  2 failing

  1) Test a client controllers
       "before all" hook for "Should have valid Open Graph tags on the watch page with video id":
     Error: npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1592255206909-0.8759298727288141/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

      at child_process_1.exec (shared/extra-utils/server/servers.ts:82:44)
      at ChildProcess.exithandler (child_process.js:285:7)
      at maybeClose (internal/child_process.js:982:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

  2) Test a client controllers
       "after all" hook for "Should have valid index html updated tags (title, description...)":
     TypeError: Cannot read property 'app' of undefined
      at killallServers (shared/extra-utils/server/servers.ts:264:17)
      at Object.cleanupTests (shared/extra-utils/server/servers.ts:272:3)
      at Context.<anonymous> (server/tests/client.ts:147:11)
      at Generator.next (<anonymous>)
      at /home/artem/peertube/versions/ting/server/tests/client.ts:8:71
      at new Promise (<anonymous>)
      at __awaiter (server/tests/client.ts:4:12)
      at Context.<anonymous> (server/tests/client.ts:134:16)



error Command failed with exit code 2.

**Comment by Chocobozzz** [comment]
What do you mean by *then yarn run test*?

`npm run build -- --light` should not run tests.

**Comment by TsymbalArtem** [comment]
That was good advice, but now is the next one:

 > sass-lint -c .sass-lint.yml



  Test a client controllers
    1) "before all" hook for "Should have valid Open Graph tags on the watch page with video id"
    2) "after all" hook for "Should have valid index html updated tags (title, description...)"


  0 passing (2m)
  2 failing

  1) Test a client controllers
       "before all" hook for "Should have valid Open Graph tags on the watch page with video id":
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/artem/peertube/versions/ting/server/tests/index.ts)
  

  2) Test a client controllers
       "after all" hook for "Should have valid index html updated tags (title, description...)":
     TypeError: Cannot read property 'app' of undefined
      at killallServers (shared/extra-utils/server/servers.ts:264:17)
      at Object.cleanupTests (shared/extra-utils/server/servers.ts:272:3)
      at Context.<anonymous> (server/tests/client.ts:147:11)
      at Generator.next (<anonymous>)
      at /home/artem/peertube/versions/ting/server/tests/client.ts:8:71
      at new Promise (<anonymous>)
      at __awaiter (server/tests/client.ts:4:12)
      at Context.<anonymous> (server/tests/client.ts:134:16)



npm ERR! Test failed.  See above for more details.

**Comment by Chocobozzz** [comment]
Run `killall peertube && npm run clean:server:test && NODE_APP_INSTANCE=1 NODE_ENV=test node dist/server` to see if there are errors when you run peertube

**Comment by TsymbalArtem** [comment]
Should I use createdb -O peertube peertube_test1?


[artem@artem-pc peertube-latest]$ killall peertube
peertube: no process found
[artem@artem-pc peertube-latest]$ npm run clean:server:test

> peertube@2.1.1 clean:server:test /home/artem/peertube/versions/ting
> scripty

rm: cannot remove './test1/logs/peertube-audit.log': Permission denied
rm: cannot remove './test1/logs/peertube.log': Permission denied
NOTICE:  database "peertube_test3" does not exist, skipping
NOTICE:  database "peertube_test1" does not exist, skipping
NOTICE:  database "peertube_test4" does not exist, skipping
NOTICE:  database "peertube_test2" does not exist, skipping
NOTICE:  database "peertube_test6" does not exist, skipping
NOTICE:  database "peertube_test5" does not exist, skipping
createdb: error: database creation failed: ERROR:  must be member of role "peertube"
createdb: error: database creation failed: ERROR:  must be member of role "peertube"
createdb: error: database creation failed: ERROR:  must be member of role "peertube"
createdb: error: database creation failed: ERROR:  must be member of role "peertube"
createdb: error: database creation failed: ERROR:  must be member of role "peertube"
createdb: error: database creation failed: ERROR:  must be member of role "peertube"
[artem@artem-pc peertube-latest]$ NODE_APP_INSTANCE=1 NODE_ENV=test node dist/server
[localhost:9001] 2020-06-16 10:44:40.459 debug: Checking NodeJS version v10.20.1.
[localhost:9001] 2020-06-16 10:44:41.352 warn: Emailer is disabled so the contact form will not work.
[localhost:9001] 2020-06-16 10:44:41.573 error: Cannot start application. {
  "err": {
    "stack": "SequelizeConnectionError: database \"peertube_test1\" does not exist\n    at connection.connect.err (/home/artem/peertube/versions/ting/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:182:24)\n    at Connection.connectingErrorHandler (/home/artem/peertube/versions/ting/node_modules/pg/lib/client.js:194:14)\n    at Connection.emit (events.js:198:13)\n    at Socket.<anonymous> (/home/artem/peertube/versions/ting/node_modules/pg/lib/connection.js:134:12)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
    "message": "database \"peertube_test1\" does not exist",
    "name": "SequelizeConnectionError",
    "parent": {
      "stack": "error: database \"peertube_test1\" does not exist\n    at Connection.parseE (/home/artem/peertube/versions/ting/node_modules/pg/lib/connection.js:614:13)\n    at Connection.parseMessage (/home/artem/peertube/versions/ting/node_modules/pg/lib/connection.js:413:19)\n    at Socket.<anonymous> (/home/artem/peertube/versions/ting/node_modules/pg/lib/connection.js:129:22)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)",
      "message": "database \"peertube_test1\" does not exist",
      "name": "error",
      "length": 99,
      "severity": "FATAL",
      "code": "3D000",
      "file": "postinit.c",
      "line": "888",
      "routine": "InitPostgres"
    }
  }
}

**Comment by Chocobozzz** [comment]
> Should I use createdb -O peertube peertube_test1?

No, just follow the guide: https://docs.joinpeertube.org/#/contribute-getting-started?id=unit-tests

You have to create a postgres sql user. Also you have permissions issues in your peertube directory:

```
rm: cannot remove './test1/logs/peertube-audit.log': Permission denied
rm: cannot remove './test1/logs/peertube.log': Permission denied
```
