### ISSUE TITLE
Re-Signup of a deleted user

### ISSUE THREAD

**Issue by UnlimitedCookies** [Chocobozzz/PeerTube#2881]
Hello there,

I noticed that when you delete a user, it is not possible for that user to re-register with the same email-address.

What is stopping a potential re-signup and is this a suitable feature request?

Best regards,
Kevin

**Comment by Chocobozzz** [comment]
Hi,

> I noticed that when you delete a user, it is not possible for that user to re-register with the same email-address.

Are you sure this is the email address that prevent signup? Not the username?

**Comment by UnlimitedCookies** [comment]
I'm not all that sure what it is since when using the ldap authentication module the email address is tied to the username.
However, why are we preventing someone from signing up under the same username?

**Comment by rigelk** [comment]
This usually boils down to preventing impersonation.

**Comment by UnlimitedCookies** [comment]
Correct. But since we use ldap authentication an impersonation is almost impossible.

I don't know how to implement it, but maybe a user who changed his mind after deleting his account wants to sign-up again under the same username.

To prevent impersonation, there could be an option that an admin needs to pass the reuse of a username or something similar.

**Comment by Chocobozzz** [comment]
See https://github.com/Chocobozzz/PeerTube/issues/870#issuecomment-416250789

Just delete the row from `actor` table

**Comment by UnlimitedCookies** [comment]
Thanks for the suggestion, somehow I didn't find that issue before opening this one.

What about implementing this feature in the UI?

**Comment by ser** [comment]
It's not easy to delete such a row because of related tables.
