### ISSUE TITLE
How i can i mesaure qos

### ISSUE THREAD

**Issue by Musadiqraees** [Chocobozzz/PeerTube#2885]
How to measure below qos for peertube

Bit Rate (quality of the video that you users are experiencing)
Buffer Fill (buffer time when the video is first started)
Lag Length (waiting time when buffer is drained to start video)
Play Length (amount of data actually streamed out of your server)
Lag Ratio (total waiting time over watching time )

**Comment by rigelk** [comment]
@Musadiqraees you could write your own PeerTube plugin that sends events from videojs to your event collection server like the videojs plugin `videojs-analytics` does.

**Comment by Musadiqraees** [comment]
@rigelk I need these events at the client-side, kindly explain me in detail
