### ISSUE TITLE
Remote Subscribe with Any PeerTube Account

### ISSUE THREAD

**Issue by Malsasa** [Chocobozzz/PeerTube#2888]
I am a user and not a developer. I want an ability to subscribe to remote channel with user's PeerTube account regardless their instance instead of "an account on this instane" which leads him to making a new account instead of subscribing. If Mastodon's supported, I believe PeerTube should be supported too. 

**What happened?**
Subscribe options look like screenshot below.![1](https://user-images.githubusercontent.com/3586695/85209452-615eef80-b362-11ea-8c4b-da994cc0fd61.png)

**What do you expect to happen instead?**
It should be "Subscribe with a PeerTube account" instead of "...account on this instance" that supports any user's instance. This is my simple mockup of my feature request:
![sub](https://user-images.githubusercontent.com/3586695/85210004-b997f080-b366-11ea-865f-e8c313927e4c.png)

**Steps to reproduce:**
In my opinion, it should be:
1. User clicks Subscribe button.
2. User types his PeerTube username.
3. User sees authentication with **Remote Subscribe** button (similar to Mastodon's one).
4. User clicks Subscribe button (similar to Mastodon's one).
5. User subscribed.

Thank you very much for PeerTube and this is my first issue report.

**Comment by jeena** [comment]
This is one is also one of my biggest hurdles when it comes to recommending PeerTube to my friends. I have explained how to do that right now in https://tube.jeena.net/videos/watch/b9da3790-6710-415d-b610-45762c1a007b

**Comment by r4dh4l** [comment]
> This is one is also one of my biggest hurdles when it comes to recommending PeerTube to my friends.

I would even say it is a showstopper. I took me months to convince some minor institutions to give PeerTube a try (as alternative to YouTube). Recently they asked me: "Ok, we have a PeerTube channel now - how we can subscribe to yours?"

I'm very thankful for projects like PeerTube but sometimes I wonder if people developing these projects are too "far away" from how "average people" are used to use web services (or the other way around). I have problems to understand how something like "subscibing accounts on other servers" is an issue *in 2020* (please explain me, I would really like to understand).

However: Thanks for developing PeerTube!

**Comment by rigelk** [comment]
@r4dh4l : what are your UI suggestions?

**Comment by r4dh4l** [comment]
> what are your UI suggestions?

A subscribe button which is *not* a dropdown menu that behaves in the following way:

- if you are logged in on the same server the account/channel you want to subscribe it will be directly subscribed
- if you are not logged in on the same server the subscribe process is asking for...
    - of your profile address
    - your account name + domain of your "home server" (for people who have no idea what an ID is - and yes, these people have to be part of "our target group")
    - or an ID in the Fediverse like a Mastodon ID (for people who know what this is)
...followed by a login process.

"Subscribe via RSS" should be handled with a separate RSS icon.

The current drop down concept makes sense for people who are familiar with all the technical terms, starting with the term "ActivityPub". All others will be frustated and run away just 2s watching the menu.

**Comment by xundeenergie** [comment]
Is it possible to leave a  ookie on the computer which can be identified as peertube-specific cookie, so the dialog can serve the posibilities to subscribe for each of this instances, where i'm logged in in the moment, an serve a field like now for the mastodon-subscription, which searches also for peertube-services on the domain of the username?

And please rename the field "Subscribe with a Mastodon account" to somethin other, because the subscription will also work with pleroma-instances too! 

There is an addon for firefox called "Mastodon – Simplified Federation!", wich simplifies subscription from one mastodon-instance to another (remote) one. Maybe this Addon can be enhanced to work also for peertube...
