### ISSUE TITLE
Questions about rewrite the PeerTube frontend architecture

### ISSUE THREAD

**Issue by glauberfc** [Chocobozzz/PeerTube#2889]
Is it possible to fork the PeerTube project, rewrite the interface using other libraries like React or Vue, but continue fetching data from the current backend? What's needed to fetch data from the current backend using a new frontend architecture?

**Comment by rigelk** [comment]
hi @glauberfc,

The only thing you need is the REST API as documented on https://docs.joinpeertube.org/api-rest-reference.html. You have a full example with code that shows the oauth dance at https://docs.joinpeertube.org/api-rest-reference.html#tag/Video/paths/~1videos~1upload/post, a common use case.

**Comment by glauberfc** [comment]
@rigelk, thanks for the fast and helpful answer!
