### ISSUE TITLE
Audio is muted automaticaly in web browser

### ISSUE THREAD

**Issue by ThierryM** [Chocobozzz/PeerTube#2890]
Hi,
Thanks for your work and sharing.
When I open a link to a peertube video, the sound is automaticaly muted. So, I need to enable it all the time (and I miss often the beginning).

* PeerTube version or URL (exemple) : https://tube-montpellier.beta.education.fr/videos/watch/2f88ebc5-f61c-4880-8730-288107f1dfe5
* Browser name/version: Mozilla Firefox 77.0.1 (64 bits) sous Ubuntu

**Comment by ThierryM** [comment]
Sorry,
I didn't find the issue 2865 closed : https://github.com/Chocobozzz/PeerTube/issues/2865

**Comment by ThierryM** [comment]
Sorry,
But this issue is still present in 2.2.0 peertube version.
![Sélection_439](https://user-images.githubusercontent.com/1470067/85394284-a0ea2f00-b54e-11ea-9e0f-f5dfcac4a65b.png)

**Comment by Chocobozzz** [comment]
I'm sorry but I can't reproduce. Try manually enable sound, and refresh to see if it's still a bug in 2.2?

**Comment by ThierryM** [comment]
Hi,
You are right : I can't reproduce too.
I think I understood my error : Peertube keeps the last setting for the sound in the navigator. If the sound is muted, when you go to an other video, no sound.
Sorry for the disturbance. I close the issue.
