### ISSUE TITLE
Larger thumbnails for RSS feeds

### ISSUE THREAD

**Issue by nikoss** [Chocobozzz/PeerTube#2892]
request:
Please add (large) thumbnails of the videos in the RSS feed.
Possibly above the video player.

An icon of the channel that publishes the video would also be helpful.

**Comment by rigelk** [comment]
We don't order elements, your RSS client does.

@Chocobozzz it would be fine switching from thumbnails to previews since they are larger, right?

**Comment by nikoss** [comment]
I think there is a confusion here. I just looked at a couple raw rss feeds, and there indeed are thumbnails. But they are links...
</media:SOMETHING...
instead of...
<image>SOMETHING...
That is why they don't show up in rss clients, SeaMonkey rss preview, etc.

I am no developer, but there seems to be a mix with RSS and what I saw elsewhere being called something like Media RSS. 

These two RSSs must be different
(the one is simple and minimalistic, the other wants to add more stuff and complications).

And yes these existing thumbnails are too small. They should be at least 640x360 in size.

**Comment by rigelk** [comment]
Previews are 850x480, so that should be fine.

Yes, we only deliver Media RSS, not plain RSS.

**Comment by Chocobozzz** [comment]
> it would be fine switching from thumbnails to previews since they are larger, right?

yep

**Comment by tiotrom** [comment]
Any progress on this :) - I would love bigger thumbnails. I was about to submit a similar issue.

**Comment by Chocobozzz** [comment]
Done in https://github.com/Chocobozzz/PeerTube/commit/07319882b9d0999963a231d31a7a03ae41beea65

(will not be released in 3.1)
