### ISSUE TITLE
PeerTube theme not re-theming site for anonymous/not-signed-in users

### ISSUE THREAD

**Issue by hexydes** [Chocobozzz/PeerTube#2893]
**What happened?**
Installed PeerTube via Yunohost. Everything installed fine, changed my theme, looks great for signed-in users, but non-signed-in users still see the default theme.

**What do you expect to happen instead?**
Non-signed-in users should also see the theme that was applied to the instance.

**Steps to reproduce:**

1. Install via Yunohost to Debian 9 server.

2. Install bittube-dark-mode 2.0.0 theme

3. Go to Administration >> Configuration >> Basic Configuration >> Theme, set theme to "Bittube Dark Mode"

4. Theme changes to new theme. Log out. Refreshed page is still the default theme.

**Additional information**
* PeerTube version or URL: https://tilvids.com
* Browser name/version: Tested on Firefox on Ubuntu and Mac OS
* NodeJS version: Unknown (can find out, if necessary)

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Thanks for the issue. I fixed this some weeks ago in https://github.com/Chocobozzz/PeerTube/commit/3e95b6834304ebbff7d796a6a5e096e52813bc77

**Comment by hexydes** [comment]
Thanks for the update! Looks like 2.2.0 was released 22 days ago, and you merged the change 19 days ago, so...looking forward to seeing the new fix! :)

**Comment by DalekDave** [comment]
This issue does not seem to be cleanly resolved in v2.3.0. On my instance at https://tube.tardis.world, I have the bittube-dark theme applied as instance default.

When I visit the landing page, the proper instance-default theme displays. If I refresh the page, the peertube-default theme displays. If I refresh the page again, the instance-default theme displays.

Each time I refresh the page, there is an alternation between the instance-default theme and the peertube default theme.
