### ISSUE TITLE
featured user/video

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#2894]
This is an enhancement suggestion. 

Suppose as a site admin, i would want to support a particular person for this week because i find their work interesting and all, i would add them to featured and their profile /video would show on the homepage where more people would be able to find it.

this would help in discoverability for people who would love to have more people appreciate their work

**Comment by Chocobozzz** [comment]
Hi,

Thanks for this issue. I think we can merge it in https://github.com/Chocobozzz/PeerTube/issues/1430
