### ISSUE TITLE
"Discover" section not working properly?

### ISSUE THREAD

**Issue by hexydes** [Chocobozzz/PeerTube#2902]
**What happened?**
Clicked on the "Discover" tab on my instance. It takes me to the Discover page and shows the "Education" category, one channel, and nothing else.

**What do you expect to happen instead?**
I expected that there would be a number of categories listed on the "Discover" page with videos listed in each category.

**Steps to reproduce:**

1. Install Peertube via Yunohost.

2. Add categories to the "Main instance categories" list, save that.

3. Import videos (from YouTube link) to the instance, assigned to categories like "Entertainment", "Vehicles", etc.

4. Go to "Discover" page.

5. Only videos from "Education" category are listed.

**Additional information**
I have 14 categories selected in the "Main instance categories" list, saved the categories after adding them, and have videos on the instance in those categories. But they still don't show up on the "Discovery" tab.

* PeerTube version or URL: https://tilvids.com
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Hello,

PeerTube will display in this tab categories/channels/tags that have at least 6 videos. If you upload more videos, you'll see them.

**Comment by hexydes** [comment]
Perfect, thank you!
