### ISSUE TITLE
How to open more ports for testing the federation of PeerTube servers

### ISSUE THREAD

**Issue by zd-shenwenjie** [Chocobozzz/PeerTube#2905]
Through the instructions in the document, 
I can access on 9001, 9002, 9003, I also want to open 9004, 9005, 9006 
What should I do?

**Comment by Chocobozzz** [comment]
Just use this command: https://github.com/Chocobozzz/PeerTube/blob/develop/scripts/play.sh#L13

So for 9004: `NODE_ENV=test NODE_APP_INSTANCE=4 node dist/server.js`
