### ISSUE TITLE
 How do I rebuild and run when you develop the federation of PeerTube.

### ISSUE THREAD

**Issue by zd-shenwenjie** [Chocobozzz/PeerTube#2906]
When I want to modify the federation of PeerTube servers, How do I rebuild and run after modifying the code？

**Comment by rigelk** [comment]
The [CONTRIBUTING.md](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/CONTRIBUTING.md#server-side) document should help you on that matter: `npm run dev:server`.
