### ISSUE TITLE
Torrent download still available when tracker is disabled.

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#2907]
**What happened?**

When instance's torrent tracker is disabled, the download .torrent functionality is still there.
The download seems to succeed thanks to the webseed. 

**What do you expect to happen instead?**

I think that the option to download via bittorent should be removed. Because clients will try to connect to the tracker, even after the download is complete. 

I don't know if it is possible (if the video is not on the current instance, I don't know if we can know the tracker status via federation).

**Steps to reproduce:**

1. disable torrent tracker in the config file.

2. go to a video and download it via torrent.

**Additional information**
* PeerTube version or URL: v2.2.0

**Comment by rigelk** [comment]
> Because clients will try to connect to the tracker

Does it impact your instance in a problematic way?

**Comment by JohnXLivingston** [comment]
Webtorrents clients did, causing a denial of service: https://github.com/Chocobozzz/PeerTube/issues/2826
Real torrent clients, I don't know.
Anyway, it is always good to avoid unnecessary connections. If only for ecological reasons.

**Comment by rigelk** [comment]
@JohnXLivingston I'm confused - didn't you disable the tracker *in response* to the ddos?

**Comment by JohnXLivingston** [comment]
For webtorrents: in files server/controller/tracker.ts, even if you disable the tracker, the TrackerServer is up and accept connections. And keep them open, with a timeout of 30 minutes (see the default nginx configuration). The only difference, is that there is no log, because the on('error', ...) is not binded (line 66). So your log files wont grow up indefinitely. But it will consume connections on your nginx (and by default on debian, the limit is something like 300 workers only).

For «classic» torrents, I don't know. I never looked the code, and I don't know if it pass through nginx or not (I assume so, because on my server I only opened port 443).

**Comment by JohnXLivingston** [comment]
PS : in response to the DDOS I was facing, I disabled the tracker, and I added a «return 404» in nginx config for /tracker/socket.

**Comment by Chocobozzz** [comment]
Torrent download can still be useful because we add redundancies in the file (additional webseeds).
