### ISSUE TITLE
"Change ownership" icon uses Hillary Clinton campaign logo

### ISSUE THREAD

**Issue by 12people** [Chocobozzz/PeerTube#2909]
**What happened?**
The following icon is used for "Change ownership" on the "Videos" page in "My library":
<img width="185" alt="image" src="https://user-images.githubusercontent.com/7361228/85945372-a32cfe80-b93d-11ea-84de-686ba0583a40.png">

This is a grayscale version of the Hillary Clinton 2016 logo.

It's not only a misappropriation of a trademark, but also inappropriate for the use in general.

**What do you expect to happen instead?**
Use of a more appropriate icon. Any of these would be fine:

* ![image](https://user-images.githubusercontent.com/7361228/85945589-33b80e80-b93f-11ea-8244-7289cae7b400.png) [handshake](https://fontawesome.com/icons/handshake?style=solid)
* ![image](https://user-images.githubusercontent.com/7361228/85945613-50ecdd00-b93f-11ea-894a-278a5047bbca.png) [long arrow](https://fontawesome.com/icons/long-arrow-alt-right?style=solid)
* ![image](https://user-images.githubusercontent.com/7361228/85945628-63671680-b93f-11ea-88c3-86f073857f04.png) [arrow circle](https://fontawesome.com/icons/arrow-alt-circle-right?style=solid)
* ![image](https://user-images.githubusercontent.com/7361228/85945642-77ab1380-b93f-11ea-8a41-00a65bc5bd2c.png) [double arrow](https://fontawesome.com/icons/angle-double-right?style=solid)

**Additional information**
* PeerTube version: 2.2.0
* PeerTube instance: https://tube.4aem.com/about/instance
* Browser name/version: Firefox 77

**Comment by rigelk** [comment]
Oh wow, I didn't know. Thanks for the heads up!

**Comment by rigelk** [comment]
fixed in 035038478

**Comment by 12people** [comment]
@rigelk 
Cool, thanks!
The softies icon set itself doesn't seem to be appropriate for PeerTube — it uses a [proprietary license](https://robbiepearce.com/softies/licence) that forbids redistribution. I don't think it's compatible with PeerTube's FOSS license.

As a replacement, I'd recommend e.g. [FontAwesome](https://fontawesome.com/), which is triple-licensed under the [CC BY, SIL OFL, and MIT licenses](https://github.com/FortAwesome/Font-Awesome).

**Comment by Chocobozzz** [comment]
@12people Please create a dedicated issue so we can track this work. https://forkaweso.me/Fork-Awesome/ seems also an interesting choice.

**Comment by 12people** [comment]
@Chocobozzz Done: #2913
