### ISSUE TITLE
A possibility for creating channels that are not associated to an account?

### ISSUE THREAD

**Issue by ivnvitx** [Chocobozzz/PeerTube#2910]
Basically, in YouTube or in LBRY, you can generate many different channels with the same account... just like in PeerTube. But, with PeerTube, I believe you are forced to show the account that created the channel. Is this true or am I missing something? 

I hate this. Because if now I want to have a "peertuber" channel, and a particular, hidden account... I must log out and log in every time. 

Also, this "feature" does not add anything useful by publicly "connecting" these channels. Technically, I should be able to "connect" these channels if I want to with other means, like video descriptions or channel descriptions. 

But, okay, let's say some people find this useful for some reason... then maybe add the possibility to "privatize" the channel owner?

**Comment by test2a** [comment]
so the idea is that you want a public facing channel without any obvious public link to a peertube account? probably is a bit complicated because you are not only asking to not show the "account" with a channel but that channel should also NOT show in the channels of that particular account or are you saying show it there but only not in the channel itself?

**Comment by ivnvitx** [comment]
Yes, the idea is to have a channel that is... well, a channel. Just like in YouTube, you can have many channels under one account and they work as separate accounts, basically.

You cannot do that with PeerTube, it forces you to have all your channels connected, which is OK for some cases, but not if I want to manage different unrelated channels, such as a "PeerTuber" channel and a more personal one. So basically I would like to disconnect these, maybe by creating sub-accounts or something. Or maybe by saving multiple login accounts? So that you can just "switch accounts".

**Comment by Chocobozzz** [comment]
Hello,

I understand your use case but I think that creating multiple different PeerTube accounts is the appropriate way to address it because in peertube 2.4, default channels will be hidden and only the account will be displayed in watch page (see https://github.com/Chocobozzz/PeerTube/pull/2988)
