### ISSUE TITLE
Bodyguard app integration

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#2912]
[Bodyguard](https://www.bodyguard.ai/) is an app indended to fight cyberbullying. It proposes an [API](https://developers.bodyguard.ai/), so anyone can [use it](https://developers.bodyguard.ai/documentation/index.html) for his app. Currently, this exists only on french, but other language support are planned in the future.

It would be useful to integrate it in Peertube to fight easier cyberbully, admins could just have to introduce their bodyguard API key to use it for their instance.

**Comment by rigelk** [comment]
hi @stemy2,

Being a closed-source third-party service (and language-specific at that), it would be better as a plugin using the ['filter:api.video-thread.create.accept.result'](https://docs.joinpeertube.org/#/api-plugins?id=server-hooks-only-plugins) hook.
