### ISSUE TITLE
explainations about privacy options for uploading missing

### ISSUE THREAD

**Issue by bikepunk** [Chocobozzz/PeerTube#2916]
**What happened?**

on the upload page (https://tube.aquilenet.fr/videos/upload) some privacy options are unclear to me. 
What "internal" exactly means (I guess it's wachable only from the local instance ?).

a "get help question mark button" would be welcome to clarify

**Additional information**
* PeerTube version or URL: https://tube.aquilenet.fr/about/instance

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/pull/3035
