### ISSUE TITLE
Why hiding download button behind a "..." button ? UI

### ISSUE THREAD

**Issue by bikepunk** [Chocobozzz/PeerTube#2917]
**What happened?**

On video pages, there is this "..." button, containing a single "Download" button.
The "..." button seems useless when hiding a single button and bad for the User eXperience.

(I guess the "..." button is for the future when we'll have to many buttons to display on our tiny screens ?
=> then I realized it's actually used for more options while logged in)

**What do you expect to happen instead?**

Why not displaying directly the "download" button ?

**Additional information**
* PeerTube version or URL: https://framatube.org/about/instance

**Comment by rigelk** [comment]
The issue was already raised in #1797:

> We put it in the ... because it's an option we consider less used than Share or Save to and we miss space in this area. IMHO PeerTube is a video streaming application, not a video download application so 3 clicks to download a specific video is acceptable.

If the video download is the only option available (for instance when logged out), we could make a special case to only display the download icon.

**Comment by bikepunk** [comment]
Sorry, I didn't see #1797 

I think most of the peertube users are logged out ; then the special case actually improve the UX for most of peertube users.
The missing space reason doesn't work when ... replace a single button.

I vote for the special case you're suggesting ;-)
