### ISSUE TITLE
Edit or Update ?

### ISSUE THREAD

**Issue by bikepunk** [Chocobozzz/PeerTube#2918]
**What happened?**

On the "Videos" page (https://tube.aquilenet.fr/my-account/videos) the edit button is named "Edit".

![edit](https://user-images.githubusercontent.com/14958221/86135705-7b7b9900-baeb-11ea-9c02-586dbb4a1b5c.png)

On the video page(https://tube.aquilenet.fr/videos/watch/e66f6542-4aaa-43f7-a100-4c30b64309aa), in the "..." button the edit button is named "Update".

![update](https://user-images.githubusercontent.com/14958221/86135729-80404d00-baeb-11ea-9a5a-7b6de518c743.png)

**What do you expect to happen instead?**

IMHO, we shall decide a name for this function and stick to it everywhere.

Since on the update page (https://tube.aquilenet.fr/videos/update/e66f6542-4aaa-43f7-a100-4c30b64309aa) "updade" is used, it would make sense to stick to "update" everywhere

**Additional information**
* PeerTube version or URL: https://tube.aquilenet.fr/

**Comment by rigelk** [comment]
Thanks for spotting this inconsistency @bikepunk!
