### ISSUE TITLE
Player on Mobile impossible access to options popup

### ISSUE THREAD

**Issue by Antoine81** [Chocobozzz/PeerTube#2920]
**What happened?**
Only on mobile (iOS), I can't access to the options popup on the player, the popup disappear instantly.

![bug-peertube](https://user-images.githubusercontent.com/8601319/86243824-4af93500-bba7-11ea-94e8-82739ee0c49e.gif)

**What do you expect to happen instead?**
When I tap on the option icon, the popup appear and stay visible until I tap again on the option icon :gear:

**Steps to reproduce:**
On a mobile (iOS only ?)

1. Go to : https://peertube.cpy.re/videos/watch/d2a5ec78-5f85-4090-8ec5-dc1102e022ea

2. Try to change the resolution.

3. :cry: 

**Additional information**
* PeerTube version or URL: 2.2.0
* Browser name/version: Mozilla/5.0 (iPhone; CPU iPhone OS 13_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1
* NodeJS version: /

* Link to browser console log if useful: /
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): /

**Comment by Chocobozzz** [comment]
Thanks for the issue. Should be fixed https://github.com/Chocobozzz/PeerTube/commit/35f0a5e665a565ffc9d4b88c5a12d45c88b0a090
