### ISSUE TITLE
change "RSS 2.0" link name to "Media RSS"

### ISSUE THREAD

**Issue by nikoss** [Chocobozzz/PeerTube#2921]
**What happened?**
The link says "RSS 2.0", but if I understand correctly, the feed is "Media RSS", or "Media RSS 2.0". A different "format". That is confusing.

**What do you expect to happen instead?**

**Steps to reproduce:**

1. Go to a PeerTube instance.

2. Go to "Local" videos

3. Click on the feeds button

4. Click on the "RSS 2.0" link and check the raw output
or...
copy the "RSS 2.0" link and download the raw file

**Additional information**
* PeerTube version or URL:
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by rigelk** [comment]
corrected per 2d011d94a.
