### ISSUE TITLE
Add "RSS 2.0" feed support

### ISSUE THREAD

**Issue by nikoss** [Chocobozzz/PeerTube#2922]
**What happened?**
No RSS feeds.

**What do you expect to happen instead?**
Have an RSS feed of "Local" videos
...with a thumbnail preview per video, embedded as "image"
...with a link to the .torrent file of the initial uploaded video (at least)
... (optional) ... with links to the different resolutions/versions .torrents of the video
... with the short description of the video ( a set number of the first characters of the description of the video... equal to maybe 4 lines in a desktop computer)
... with a thumbnail of the uploader, embedded as image, because pictures are easier to remember, than names, for some of us

Produce true "RSS" feeds for local videos Search Results, listed by upload date, of course
(youtube used to have that feature, once upon a time).

** Mega Rant **
I had never heard of this "Media RSS", before I searched the issues, here, on PeerTube. And, immediately, I didn't like. It has all the marks of mediocrity. You know, how it is, when mediocrats find something "good", they instantly want to "improve" it. And you know how mediocrats "improve" stuff. They either stretch it or they cripple it. That is, they make it mediocre, they destroy it.
The RSS developers were no fools. There is a reason RSS is bare bones and minimal.
But the mediocrats don't like that. So they make their own "RSS". And they call it "RSS", too! Or "Media RSS 2.0"! Yes, it is "RSS+++++" !Because, what is more mediocre than trying to capitalise and highjack someone else's achievements?

**Steps to reproduce:**

1.

2.

3.

**Additional information**
* PeerTube version or URL:
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by rigelk** [comment]
RSS 2.0 doesn't support multiple enclosures per item. We would end up with a feed that either has a thumbnail or a file attached, and one per resolution at that.

**Comment by nikoss** [comment]
I see websites include multiple images, but that might be unconventional.
Still, you could post the links to the .torrent files, or maybe even to a video file, as simple text.

A post might look like this...

= = = = = = = = = = = = = = = = =

title-link to the video page

publisher-channel [just text]


. _________________________ .
|
|
|
| . . . . . . . . preview . . . . 
| . . . . . . . . . . . / . . . . . . . . .
| . . . . . . . thumbnail  . . . 
|
|
| 
|__________________________ .

video description,
up to about three to four
lines of text

tags [just text][good for filtering]

[just text]
https://video-torrent-file/with-resolution-initial-.torrent
https://video-torrent-file/with-resolution-360.torrent
https://video-torrent-file/with-resolution-720.torrent


= = = = = = = = = = = = = = = = =

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/3761
