### ISSUE TITLE
keep only "double" resolutions and ditch intermediates

### ISSUE THREAD

**Issue by nikoss** [Chocobozzz/PeerTube#2923]
**What happened?**
Too many video resolutions.
They take more space.
They take more bandwidth, because it becomes less likely for viewers to watch the same resolutions and share data.
Because very few people will notice the difference, let's say, between 360p and 480p, if nobody tells them.
Because there is no reason to copy anything youtube does.

**What do you expect to happen instead?**
- Define the lowest resolution.
- Make versions of "doubles" of these resolutions.
- Adapt for landscape or portrait
- But don't forget to provide the original video resolution, too

example:
Let's say that you want the lowest resolution to be 360p. Then the next resolution will be 720p. And the next 1440p. No need for 480p, 1280p and others.
If you want the lowest resolution to be 240p, then there will be no 360p version of the video. The next version will be 480p, and so on.
Of course, the initial resolution of the video must be provided, too, regardless of whether it fits the pattern or not. Because, most likely, this resolution will have the best quality.

**Steps to reproduce:**

1.

2.

3.

**Additional information**
* PeerTube version or URL:
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by nikoss** [comment]
So, lets say, you have defined (as the PeerTube software, or as a specific instance) that the lowest supported resolution is 180p.

And someone uploads a 960p video.
Then the provided resolutions will be...
180p
360p
720p
960p

If someone uploads a 544p video, then the resolutions will be...
180p
360p
544p

**Comment by rigelk** [comment]
Admins can already decide to enable/disable specific resolutions.

**Comment by rigelk** [comment]
> But don't forget to provide the original video resolution, too

This is already adressed in #733.
