### ISSUE TITLE
Embedded player: page jumps to player when autoplay is active

### ISSUE THREAD

**Issue by gerdemann** [Chocobozzz/PeerTube#2925]
**What happened?**
With an embedded player on a longer page, the browser jumps to the player on page load when the player is set to autoplay.

**What do you expect to happen instead?**
The browser stays at the top of the page when the page is loaded

**Steps to reproduce:**

1. Integrate the player on a long side below with autoplay on.

2. Reload page.

**Additional information**
* PeerTube version or URL: 2.2.0
* Browser name/version: Chrome/Safari/Firefox current version
* NodeJS version: n/a

**Comment by Chocobozzz** [comment]
Please could you try to reproduce using an embed of https://peertube2.cpy.re/videos/watch/5a6133b8-3e0c-40dc-b859-69d0540c3fe5?

**Comment by gerdemann** [comment]
That seems to work.

**Comment by Chocobozzz** [comment]
Thanks. I fixed this issue in https://github.com/Chocobozzz/PeerTube/commit/7ede74add2d41958f3aad0053afc812698f261a0

**Comment by gerdemann** [comment]
> Thanks. I fixed this issue in [7ede74a](https://github.com/Chocobozzz/PeerTube/commit/7ede74add2d41958f3aad0053afc812698f261a0)

Is there a schedule when a new version will be released?

**Comment by Chocobozzz** [comment]
2.3.0-rc.1 is planned next week, and the stable version ~ July 20-25th
