### ISSUE TITLE
Multi-owner or multi-publisher channel

### ISSUE THREAD

**Issue by 1000i100** [Chocobozzz/PeerTube#2927]
I would like to share a channel with an other user so both of us can publish and edit content in this channel.

I see nothing to do it and https://github.com/Chocobozzz/PeerTube/issues/1294#issuecomment-430922542 say it's not possible for now (2018)

The July moderation focus could be a good time to add this ?

**Additional information**
* PeerTube version or URL: 2.1.1 https://tube.aquilenet.fr/

**Comment by rigelk** [comment]
Hi @1000i100! #699 already covers this. You can then detail further your use case there, and upvote the issue to help us triage it.

I doubt it could prioritize over the existing suggested moderation improvements triaged for july ; it would probably take more than a month to implement, too.
