### ISSUE TITLE
New 'Admins & Moderators' tab in the About page

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#2929]
![admn](https://user-images.githubusercontent.com/65374098/86508300-bd585800-bde7-11ea-811e-0787701d9013.png)

When clicking this tab, there should be a list of admin accounts and moderator accounts (avatar + username + role (admin/mod)).

Server admins should have the option to hide admins/moderators if some of them don't want this info to be public.

**Comment by Poslovitch** [comment]
@andrew712-1 Feel free to take over what I've done already - I'm busy with school and other projects right now.

**Comment by Chocobozzz** [comment]
Hi,

We think we provide enough flexibility for admins to display information they want on the about page, especially with the markdown support. If they want to present the moderators teams or admins, they can easily do it using the appropriate instance info fields.
