### ISSUE TITLE
JS Error on Firefox 52 ESR

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#293]
* **PeerTube version or commit:** 0cd4344f3cf529b15308fcf3eb7d7eb07726df56
* **Browser name/version:** Firefox 52.5.0 (64 bits) Linux

* **Browser console log if useful (Gist/Pastebin...):** 
```
TypeError: _this.player.play(...) is undefined[En savoir plus]  video-watch.module.chunk.js%20line%20201%20%3E%20eval:237:21
	PeerTubePlugin.prototype.updateVideoFile/this.torrent</< webpack-internal:///../../../../../src/assets/player/peertube-videojs-plugin.ts:237:21
	onLoadStart webpack-internal:///../../../../../src/assets/player/video-renderer.ts:62:9
	ZoneDelegate.prototype.invokeTask webpack-internal:///../../../../zone.js/dist/zone.js:421:17
	Zone.prototype.runTask webpack-internal:///../../../../zone.js/dist/zone.js:188:28
	ZoneTask.invokeTask webpack-internal:///../../../../zone.js/dist/zone.js:496:24
	patchEventTarget/invokeTask webpack-internal:///../../../../zone.js/dist/zone.js:1517:9
	patchEventTarget/globalZoneAwareCallback webpack-internal:///../../../../zone.js/dist/zone.js:1554:21
```

As discussed, the issue is due to that `HTMLMediaElement.prototype.play()` in Firefox 52 does not return a promise. See [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play) :)

**Comment by Chocobozzz** [comment]
Fixed: https://github.com/Chocobozzz/PeerTube/commit/3bcfff7f446d0a1d8ef5adf340375e178259a42c

Thanks for the report @fflorent ;)
