### ISSUE TITLE
Create custom infobox in signup page

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#2931]
Add a UI option to create custom infoboxes with custom title and description which will appear on the signup page and the About page.

This is what I call an infobox
![qwdqw](https://user-images.githubusercontent.com/65374098/86509011-69e90880-bded-11ea-89a8-b4603c4d769d.png)

**Comment by Chocobozzz** [comment]
Implemented as a plugin hook in https://github.com/Chocobozzz/PeerTube/commit/071f3e519cbd3184b59ee728fe96c5c29b7792b9
