### ISSUE TITLE
Channel page appears empty 

### ISSUE THREAD

**Issue by diazepan** [Chocobozzz/PeerTube#2935]
**What happened?**

When I browse a channel page in my instance, the video tab appears empty with the message "Cannot load more videos. Try again later" popping up

**What do you expect to happen instead?**

To load the videos of the channel

**Additional information**
* PeerTube version or URL: 2.2.0
* Browser name/version: Firefox 77
* NodeJS version: 12.18

* Link to browser console log if useful:

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

10.251.98.3 - - [05/Jul/2020:15:38:21 -0300] "GET /socket.io/?accessToken=a4a17cee84226aa157cfe2819d905ed53374f239&EIO=3&transport=websocket&sid=YQ1bNo7yn2ZB0WvrAAJu HTTP/1.1" 101 36 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"

10.251.98.3 - - [05/Jul/2020:15:38:21 -0300] "GET /video-channels/leomasliah/videos HTTP/2.0" 200 1671 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"

10.251.98.3 - - [05/Jul/2020:15:38:22 -0300] "GET /client/assets/images/favicon.png HTTP/2.0" 200 746 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"

10.251.98.3 - - [05/Jul/2020:15:38:22 -0300] "GET /api/v1/config/ HTTP/2.0" 200 1403 "https://videos.pueseso.club/video-channels/leomasliah/videos" "Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"

10.251.98.3 - - [05/Jul/2020:15:38:22 -0300] "GET /api/v1/oauth-clients/local HTTP/2.0" 200 99 "https://videos.pueseso.club/video-channels/leomasliah/videos" "Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"

10.251.98.3 - - [05/Jul/2020:15:38:22 -0300] "GET /client/locales/es-ES/server.json HTTP/2.0" 304 0 "https://videos.pueseso.club/video-channels/leomasliah/videos" "Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"

10.251.98.3 - - [05/Jul/2020:15:38:22 -0300] "GET /api/v1/users/me HTTP/2.0" 200 3688 "https://videos.pueseso.club/video-channels/leomasliah/videos" "Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"

10.251.98.3 - - [05/Jul/2020:15:38:22 -0300] "GET /api/v1/users/me/notifications?start=0&count=0&unread=true HTTP/2.0" 304 0 "https://videos.pueseso.club/video-channels/leomasliah/videos" "Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"

10.251.98.3 - - [05/Jul/2020:15:38:22 -0300] "GET /client/assets/images/default-avatar.png HTTP/2.0" 200 1274 "https://videos.pueseso.club/video-channels/leomasliah/videos" "Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"

10.251.98.3 - - [05/Jul/2020:15:38:22 -0300] "GET /socket.io/?accessToken=a4a17cee84226aa157cfe2819d905ed53374f239&EIO=3&transport=polling&t=NCWHPII HTTP/2.0" 200 103 "https://videos.pueseso.club/video-channels/leomasliah/videos" "Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"

10.251.98.3 - - [05/Jul/2020:15:38:22 -0300] "GET /api/v1/videos/languages HTTP/2.0" 304 0 "https://videos.pueseso.club/video-channels/leomasliah/videos" "Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"

10.251.98.3 - - [05/Jul/2020:15:38:22 -0300] "POST /socket.io/?accessToken=a4a17cee84226aa157cfe2819d905ed53374f239&EIO=3&transport=polling&t=NCWHPJZ&sid=lhGdClW1UPJEiK6yAAJv HTTP/2.0" 200 2 "https://videos.pueseso.club/video-channels/leomasliah/videos" "Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"

10.251.98.3 - - [05/Jul/2020:15:38:23 -0300] "GET /socket.io/?accessToken=a4a17cee84226aa157cfe2819d905ed53374f239&EIO=3&transport=polling&t=NCWHPJc&sid=lhGdClW1UPJEiK6yAAJv HTTP/2.0" 200 25 "https://videos.pueseso.club/video-channels/leomasliah/videos" "Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"

10.251.98.3 - - [05/Jul/2020:15:38:23 -0300] "GET /api/v1/video-channels/leomasliah HTTP/2.0" 200 901 "https://videos.pueseso.club/video-channels/leomasliah/videos" "Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"

10.251.98.3 - - [05/Jul/2020:15:38:24 -0300] "GET /lazy-static/avatars/d63f2c93-3d58-4c40-b4f6-0bdccf21ebdb.jpg HTTP/2.0" 200 3908 "https://videos.pueseso.club/video-channels/leomasliah/videos" "Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"

10.251.98.3 - - [05/Jul/2020:15:38:24 -0300] "GET /socket.io/?accessToken=a4a17cee84226aa157cfe2819d905ed53374f239&EIO=3&transport=polling&t=NCWHPZF&sid=lhGdClW1UPJEiK6yAAJv HTTP/2.0" 200 3 "https://videos.pueseso.club/video-channels/leomasliah/videos" "Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"

10.251.98.3 - - [05/Jul/2020:15:38:24 -0300] "GET /api/v1/video-channels/leomasliah/videos?start=0&count=25&sort=-publishedAt HTTP/2.0" 200 31234 "https://videos.pueseso.club/video-channels/leomasliah/videos" "Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"

10.251.98.3 - - [05/Jul/2020:15:38:24 -0300] "GET /api/v1/users/me/subscriptions/exist?uris=leomasliah@videos.pueseso.club HTTP/2.0" 200 40 "https://videos.pueseso.club/video-channels/leomasliah/videos" "Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"

**Comment by Chocobozzz** [comment]
Hi,

I don't see errors in your logs

**Comment by diazepan** [comment]
This is the output of the browser console. I don't know if it helps.



columnNumber: 1918315
​​
fileName: "https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js"
​​
lineNumber: 3
​​
message: "No plural message found for value \"247\""
​​
stack: "dt@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:1918315\ntransform@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:1940391\nvisitExpansion@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:232016\nvisit@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:200495\nt/</</<@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:276874\nt/</<@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:276865\nt/<@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:276899\ngetVideosObservable/<@https://videos.pueseso.club/client/es-ES/30-es2015.3e7cb08c8d4a12ba3b0e.js:1:7591\n_next@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:2096987\nnext@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:284873\n_next@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:285099\nnext@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:284873\nnotifyNext@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:627900\n_next@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:183183\nnext@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:284873\n_next@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:1846867\nnext@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:284873\n_next@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:567674\nnext@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:284873\n_next@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:393942\nnext@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:284873\n_subscribe@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:1815260\n_trySubscribe@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:389839\n_trySubscribe@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:572026\nsubscribe@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:389647\nr/</</<@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:553927\nsubscribe@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:389525\ncall@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:393771\nsubscribe@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:389525\ncall@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:567509\nsubscribe@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:389525\ncall@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:1846591\nsubscribe@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:389525\nc@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:606287\n_innerSub@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:627533\n_next@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:627361\nnext@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:284873\n_next@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:1846867\nnext@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:284873\n_next@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:1946799\nnext@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:284873\nnotifyNext@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:182791\n_next@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:183183\nnext@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:284873\n_next@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:285099\nnext@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:284873\nc@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:2005462\ninvokeTask@https://videos.pueseso.club/client/es-ES/polyfills-es2015.695de6ae24a7ed10ffb0.js:1:28545\nonInvokeTask@https://videos.pueseso.club/client/es-ES/main-es2015.6c7bfa0bc292a0c84fc2.js:3:865052\ninvokeTask@https://videos.pueseso.club/client/es-ES/polyfills-es2015.695de6ae24a7ed10ffb0.js:1:28466\nrunTask@https://videos.pueseso.club/client/es-ES/polyfills-es2015.695de6ae24a7ed10ffb0.js:1:23954\ninvokeTask@https://videos.pueseso.club/client/es-ES/polyfills-es2015.695de6ae24a7ed10ffb0.js:1:29595\nh@https://videos.pueseso.club/client/es-ES/polyfills-es2015.695de6ae24a7ed10ffb0.js:1:41878\np@https://videos.pueseso.club/client/es-ES/polyfills-es2015.695de6ae24a7ed10ffb0.js:1:42203\n"
​​

**Comment by diazepan** [comment]
I found what happened.

The list of videos of a channel appear when I choose English as an interface. 

But when I choose spanish, videos don't appear. And in the browser console, the message appearing is "No plural message found for value \"679\"" or other number.

**Comment by diazepan** [comment]
I'm gonna close the issue. It was an error in the translation of the angular string (the word "other" was translated)
