### ISSUE TITLE
Adding Right-to-left css layout for proper support of RTL languages UI

### ISSUE THREAD

**Issue by Salmon-Bard** [Chocobozzz/PeerTube#2936]
As there are several RTL languages translations available for PeerTube ( Arabic,  Samaritan, Urdu for example), Sadly UI is only available in LTR which results in  degraded UX.

I did some experiments adding Webpack RTL Plugin
https://www.npmjs.com/package/webpack-rtl-plugin
to angular dev style.js config and successfully generated RTL CSS on the build 

I think this is a simple straight forward solution to RTL support to start with, more fine tuning for other models maybe required.

**Comment by Salmon-Bard** [comment]
**Additional note** 
For RTL the "<html>" tag should contain **dir="rtl"** attribute. 

Any hope of seeing this implemented in the upcoming release ?

**Comment by Chocobozzz** [comment]
the "" tag? You mean the `body` tag?

Would `dir="auto"` be enough?

**Comment by Salmon-Bard** [comment]
> he "" tag? You mean the `body` tag?
> 
> Would `dir="auto"` be enough?

From my testing in chrome it will not work if your chrome UI language is set to a LTR language. In my case I have a chrome English UI and browsing Arabic version on Peertube you get a mix  of both RTL and LTR when using generated RTL style sheet . **Here what happens:**

if you add a conversion RTL of the current webpack generated style sheet the result is that this will effect and set all elements that are included in the original sheet to RTL, while all elements not having css in the original sheet will be set by chrome to its user settings chrome UI language  layout. Even setting header direction to `"auto"` in my chrome browser does not result in chrome understanding that this is a RTL page by looking at content. Setting `"auto"` or leaving it without set will work if you already have the browsers UI language set to use RTL language.

**Comment by Chocobozzz** [comment]
We now support RTL layout.
