### ISSUE TITLE
Can't start instance after "downgrade"

### ISSUE THREAD

**Issue by diazepan** [Chocobozzz/PeerTube#2938]
**What happened?**

I updated my instance to the 2.3.0-rc1 version, and then I tried to rollback to the 2.2.0 version according to what the docs stated
https://docs.joinpeertube.org/#/install-any-os?id=things-went-wrong

Now I can't start the instance because of an error of a duplicated index, not even reverting to the rc version fixes it

This is the output when I execute NODE_ENV=production NODE_CONFIG_DIR=/var/www/peertube/config /usr/bin/npm start with the peertube user in the peertube-latest directory

2020-07-06 16:03:53.065 error: Cannot install application. {
  "err": {
    "stack": "SequelizeUniqueConstraintError: no se pudo crear el índice único «tag_name»\n    at Query.formatError (/var/www/peertube/versions/peertube-v2.3.0-rc.1/node_modules/sequelize/lib/dialects/postgres/query.js:327:16)\n    at /var/www/peertube/versions/peertube-v2.3.0-rc.1/node_modules/sequelize/lib/dialects/postgres/query.js:72:18\n    at tryCatcher (/var/www/peertube/versions/peertube-v2.3.0-rc.1/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v2.3.0-rc.1/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v2.3.0-rc.1/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v2.3.0-rc.1/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v2.3.0-rc.1/node_modules/bluebird/js/release/promise.js:725:18)\n    at _drainQueueStep (/var/www/peertube/versions/peertube-v2.3.0-rc.1/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/var/www/peertube/versions/peertube-v2.3.0-rc.1/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v2.3.0-rc.1/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-v2.3.0-rc.1/node_modules/bluebird/js/release/async.js:15:14)\n    at processImmediate (internal/timers.js:456:21)",
    "message": "no se pudo crear el índice único «tag_name»",
    "name": "SequelizeUniqueConstraintError",
    "errors": {},
    "parent": {
      "stack": "error: no se pudo crear el índice único «tag_name»\n    at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v2.3.0-rc.1/node_modules/pg-protocol/dist/parser.js:241:15)\n    at Parser.handlePacket (/var/www/peertube/versions/peertube-v2.3.0-rc.1/node_modules/pg-protocol/dist/parser.js:89:29)\n    at Parser.parse (/var/www/peertube/versions/peertube-v2.3.0-rc.1/node_modules/pg-protocol/dist/parser.js:41:38)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v2.3.0-rc.1/node_modules/pg-protocol/dist/index.js:8:42)\n    at Socket.emit (events.js:315:20)\n    at addChunk (_stream_readable.js:295:12)\n    at readableAddChunk (_stream_readable.js:271:9)\n    at Socket.Readable.push (_stream_readable.js:212:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)",
      "message": "no se pudo crear el índice único «tag_name»",
      "length": 199,
      "name": "error",
      "severity": "ERROR",
      "code": "23505",
      "detail": "La llave (name)=(effect text inkscape,) está duplicada.",
      "schema": "public",
      "table": "tag",
      "constraint": "tag_name",
      "file": "tuplesort.c",
      "line": "4056",
      "routine": "comparetup_index_btree",
      "sql": "CREATE UNIQUE INDEX \"tag_name\" ON \"tag\" (\"name\")"
    },
    "sql": "CREATE UNIQUE INDEX \"tag_name\" ON \"tag\" (\"name\")"
  }
}
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! peertube@2.3.0-rc.1 start: `node dist/server`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the peertube@2.3.0-rc.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/www/peertube/.npm/_logs/2020-07-06T19_03_53_183Z-debug.log

**Comment by Chocobozzz** [comment]
Use:
 * `select name from tag group by name having count(*) > 1;` to find duplicates
 * `select id, name from tag where name = '...';` to get duplicated entries
 * Keep only one entry for each duplicated entries `delete from tag where id = ...;`

**Comment by diazepan** [comment]
2237 entries of the first select Can I delete those tags using "delete from tag group by name having count(*) > 1;"

**Comment by diazepan** [comment]
nevermind. I did this SQL command for saving time.

delete from tag where name in (select name from tag as a group by name having count(*) > 1) and id not in (select min(id) from tag as a group by name having count(*) > 1);

AND IT WORKED. THANK YOU
