### ISSUE TITLE
Only redirected to the home after logged in

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#294]
* **PeerTube version or commit:** 0cd4344f3cf529b15308fcf3eb7d7eb07726df56
* **Browser name/version:** Firefox 52
* **What is the expected behaviour?**

Steps to reproduce:
 1. Run Peertube, unsure you're not logged in
 2. Go on some page, such as the upload one
     → You're redirected to the login page
 3. Log in
     → You should be redirected to the upload page

* **What do you see instead?**

You're redirected to the home. You have to click on "upload" again.

**Comment by Chocobozzz** [comment]
👍 

I think we could set a `redirect_url` in the local storage (not in the url to avoid security issues) and if the key exists the login component redirect to this url instead of to the home.

**Comment by fflorent** [comment]
Or the [referer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer) might be another solution? Not sure how the redirection to the login page works and if the referer would then contain the targeted page.

**Comment by Chocobozzz** [comment]
Or just use the Angular example: https://angular.io/guide/router#query-parameters-and-fragments

**Comment by BO41** [comment]
@Chocobozzz @fflorent is this issue still a thing to be solved?
https://github.com/rigelk/PeerTube/commit/42cc75bcb437e65b328c3bc38e48fb6340b027db seems to have fixed it and says: "fixes #294".

Otherwise, what is still missing?

**Comment by fflorent** [comment]
@BO41 I can still reproduce the issue :)

**Comment by rigelk** [comment]
Ah indeed, I have a few PRs left unfinished… you are free to continue it @BO41.

**Comment by BO41** [comment]
@rigelk so your mentioned PR is WIP and was never merged right?

@fflorent thanks for checking :wink:

**Comment by rigelk** [comment]
exactly.

**Comment by BO41** [comment]
@rigelk yeah sure :smiley:
