### ISSUE TITLE
Videos do not play when requesting the desktop website on iOS

### ISSUE THREAD

**Issue by Crestwave** [Chocobozzz/PeerTube#2941]
**What happened?**

It got stuck loading videos on iOS when requesting the desktop website; it downloads but never plays.

**What do you expect to happen instead?**

It should play since this is actually the default for iPadOS; I have this setting turned off myself, but my friend couldn't play a video I uploaded and I found out that it was because of this. Note that it works perfectly on the mobile website.

**Steps to reproduce:**

1. Either have Settings > Safari > Request Desktop Website > All Websites set to on (default on iPadOS) or press the aA icon on the URL bar then Request Desktop Website.

2. Try to play a video.

**Additional information**
* PeerTube version or URL: https://video.ploud.fr/
* Browser name/version: Safari on iPadOS 13.5.1
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by imc67** [comment]
Hi, is there any progress on this bug? We’ve waited for 2.3 to solve some bugs, now we can almost go live with our (1000+ own videos) PeerTube but this bug is for us a show stopper. Most of our audience is using iPad as device.

**Comment by gramakri** [comment]
@Chocobozzz Do you have a hunch what causes this problem?

**Comment by rigelk** [comment]
I tried a few local and remote videos on the instance from a 2018 iPad using Safari, iOS 12. Videos are playing fine. Do you have a more specific video I could test to replicate the problem?

**Comment by imc67** [comment]
With iPad Pro on iOS 13.6 every video on every PeerTube is not playing. The twitch is that in Safari “request desktop site” is defaulted, that is not working with PeerTube. If you manually request a “mobile site” then it does work.

**Comment by tcitworld** [comment]
On iOS 14 videos on Chrome work properly, but most of the time fail to load in Safari or Firefox Focus, and never on Firefox.

**Comment by Crestwave** [comment]
Note that unless it changed in iOS 14, all browsers on iOS use the same engine. The main issue seems to be the user agent or something; requesting a desktop site makes it use a macOS user agent, which I'm guessing causes some difference that breaks it.

Here's mine: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15`

P.S. "iPadOS" is essentially iOS 13+ on iPad, which is why you don't have this issue by default on iOS 12. You might still encounter it if you manually request it, though

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/b6a8cfc5714c93d0ecf6154e5d3a25b33b50b8cd

**Comment by tdiglx** [comment]
Some viewers using iOS and Safari reported problems viewing embedded videos. Could applying the commits diff to Peertube 2.3 fix the problem for them or would I need to add other diffs as well?

**Comment by Chocobozzz** [comment]
Replace `isIOS()` function with https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/assets/player/utils.ts#L11 should work

**Comment by tdiglx** [comment]
Thanks!
