### ISSUE TITLE
Embedding code for website is broken within url section.

### ISSUE THREAD

**Issue by FredBezies** [Chocobozzz/PeerTube#2942]
**What happened?**

After Tux'n'Tube peertube instance migrated to 2.3.0-rc1, I noticed I cannot embed videos anymore. Looking at html code, I noticed site address was missing in url part.

With this video, https://peertube.pcservice46.fr/videos/watch/fcfa5c7a-c028-4aee-818d-ebeaee548af5

With peertube 2.3.0rc1, integration code is:

`<iframe width="560" height="315" sandbox="allow-same-origin allow-scripts allow-popups" src="/videos/embed/videos/embed/fcfa5c7a-c028-4aee-818d-ebeaee548af5" frameborder="0" allowfullscreen></iframe>`

With peertube 2.x.y:

`<iframe width="560" height="315" sandbox="allow-same-origin allow-scripts allow-popups" src="https://peertube.pcservice46.fr/videos/embed/fcfa5c7a-c028-4aee-818d-ebeaee548af5" frameborder="0" allowfullscreen></iframe>`

`https://peertube.pcservice46.fr/videos/embed/` was replaced by: `/videos/embed/videos/embed/`

**What do you expect to happen instead?**

Embed code to be OK!

**Steps to reproduce:**

1. Just use a 2.3.0-rc1 instance
2. Select a video you want to embed.
3. Select integration; Grab code and look at it.

**Additional information**
* PeerTube version or URL: https://peertube.pcservice46.fr/
* Browser name/version: Mozilla Firefox 80 / Chromium 83
* NodeJS version:
* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Thanks for the issue @FredBezies. Fixed in https://github.com/Chocobozzz/PeerTube/commit/72493e44e9b455a04c4f093ed6c6ffa300b98d8b

**Comment by FredBezies** [comment]
You're welcome. It was an annoying bug I faced while testing embedding function.
