### ISSUE TITLE
Blank screen after update

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#2943]
Version 2.2.0 was installed. I decided to upgrade peertube to the latest published version 2.3.0-RC.1
After the update, there was a blank screen. I recorded the entire update process on video.
https://peervideo.ru/videos/watch/d9aee45d-affb-48b0-8ffe-1863c6ed364b

Why did such an error occur and how to fix it? I tried to update several times and each time I had to roll back the virtual machine

**Comment by rigelk** [comment]
Do you have logs?

**Comment by Alterak** [comment]
> Do you have logs?

I showed the whole process along with the magazines in the video
At the moment I can’t copy the journal. Already made a server rollback so you can see the video.

**Comment by Alterak** [comment]
Immediately after installation, the server was restarted. Here is the magazine from now on

> июл 08 22:06:24 peervideo systemd[1]: Stopping PeerTube daemon...
> июл 08 22:06:24 peervideo systemd[1]: peertube.service: Succeeded.
> июл 08 22:06:24 peervideo systemd[1]: Stopped PeerTube daemon.
> июл 08 22:06:24 peervideo systemd[1]: Started PeerTube daemon.
> июл 08 22:06:24 peervideo peertube[3989]: > peertube@2.3.0-rc.1 start /var/www/peertube/versions/peertube-v2.3.0-rc.1
> июл 08 22:06:24 peervideo peertube[3989]: > node dist/server
> июл 08 22:06:28 peervideo peertube[3989]: [peervideo.ru:443] 2020-07-08 22:06:28.578 info: Begin migrations.
> июл 08 22:06:28 peervideo peertube[3989]: [peervideo.ru:443] 2020-07-08 22:06:28.581 info: Executing 0515-video-abuse-reason-timestamps.js migration script.
> июл 08 22:06:28 peervideo peertube[3989]: [peervideo.ru:443] 2020-07-08 22:06:28.606 info: Migrations finished. New migration version schema: 515
> июл 08 22:06:28 peervideo peertube[3989]: [peervideo.ru:443] 2020-07-08 22:06:28.773 info: Database peertube_prod is ready.
> июл 08 22:06:28 peervideo peertube[3989]: [peervideo.ru:443] 2020-07-08 22:06:28.955 info: Using smtp.yandex.ru:465 as SMTP server.
> июл 08 22:06:28 peervideo peertube[3989]: [peervideo.ru:443] 2020-07-08 22:06:28.957 info: Testing SMTP server...
> июл 08 22:06:29 peervideo peertube[3989]: [peervideo.ru:443] 2020-07-08 22:06:29.124 info: Secure connection established to 77.88.21.158:465 {
> июл 08 22:06:29 peervideo peertube[3989]:   "component": "smtp-connection",
> июл 08 22:06:29 peervideo peertube[3989]:   "sid": "IfxlLBVaQsw",
> июл 08 22:06:29 peervideo peertube[3989]:   "tnx": "network",
> июл 08 22:06:29 peervideo peertube[3989]:   "localAddress": "192.168.1.10",
> июл 08 22:06:29 peervideo peertube[3989]:   "localPort": 48676,
> июл 08 22:06:29 peervideo peertube[3989]:   "remoteAddress": "77.88.21.158",
> июл 08 22:06:29 peervideo peertube[3989]:   "remotePort": 465
> июл 08 22:06:29 peervideo peertube[3989]: }
> июл 08 22:06:29 peervideo peertube[3989]: [peervideo.ru:443] 2020-07-08 22:06:29.296 info: User "admin@peervideo.ru" authenticated {
> июл 08 22:06:29 peervideo peertube[3989]:   "component": "smtp-connection",
> июл 08 22:06:29 peervideo peertube[3989]:   "sid": "IfxlLBVaQsw",
> июл 08 22:06:29 peervideo peertube[3989]:   "tnx": "smtp",
> июл 08 22:06:29 peervideo peertube[3989]:   "username": "admin@peervideo.ru",
> июл 08 22:06:29 peervideo peertube[3989]:   "action": "authenticated",
> июл 08 22:06:29 peervideo peertube[3989]:   "method": "PLAIN"
> июл 08 22:06:29 peervideo peertube[3989]: }
> июл 08 22:06:29 peervideo peertube[3989]: [peervideo.ru:443] 2020-07-08 22:06:29.297 info: Successfully connected to SMTP server.
> июл 08 22:06:29 peervideo peertube[3989]: [peervideo.ru:443] 2020-07-08 22:06:29.305 info: Cleaning HTML cache.
> июл 08 22:06:29 peervideo peertube[3989]: [peervideo.ru:443] 2020-07-08 22:06:29.315 info: Server listening on localhost:9000
> июл 08 22:06:29 peervideo peertube[3989]: [peervideo.ru:443] 2020-07-08 22:06:29.315 info: Web server: https://peervideo.ru
> июл 08 22:06:29 peervideo peertube[3989]: [peervideo.ru:443] 2020-07-08 22:06:29.327 info: Connection closed {
> июл 08 22:06:29 peervideo peertube[3989]:   "component": "smtp-connection",
> июл 08 22:06:29 peervideo peertube[3989]:   "sid": "IfxlLBVaQsw",
> июл 08 22:06:29 peervideo peertube[3989]:   "tnx": "network"
> июл 08 22:06:29 peervideo peertube[3989]: }
> июл 08 22:06:35 peervideo peertube[3989]: [peervideo.ru:443] 2020-07-08 22:06:35.780 info: 192.168.1.5 - - [08/Jul/2020:19:06:35 +0000] "GET /.well-known/nodeinfo HTTP/1.0" 200 117 "-" "Friendica 'Dalmatian Bellflower' 2019.12-1327; https://your.sensor.community"
> июл 08 22:06:36 peervideo peertube[3989]: [peervideo.ru:443] 2020-07-08 22:06:36.080 info: 192.168.1.5 - - [08/Jul/2020:19:06:36 +0000] "GET /nodeinfo/2.0.json HTTP/1.0" 200 1591 "-" "Friendica 'Dalmatian Bellflower' 2019.12-1327; https://your.sensor.community"
> июл 08 22:06:36 peervideo peertube[3989]: [peervideo.ru:443] 2020-07-08 22:06:36.396 info: 192.168.1.5 - - [08/Jul/2020:19:06:36 +0000] "GET /poco HTTP/1.0" 200 3721 "-" "Friendica 'Dalmatian Bellflower' 2019.12-1327; https://your.sensor.community"

**Comment by Chocobozzz** [comment]
We would need the web browser logs

**Comment by Alterak** [comment]
This is a browser error log

> Error: xliff parse errors:
> Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.) ("ео} =1 {1 видео} другие {<x id="INTERPOLATION" equiv-text="{{ videoChannel.videosCount }}"/> видео} }[ERROR ->]"): 0:133
> Invalid ICU message. Missing '}'. ("{VAR_PLURAL, plural, =0 {Нет видео} =1 {1 видео} [ERROR ->]другие {<x id="INTERPOLATION" equiv-text="{{ videoChannel.videosCount }}"/> видео} }"): 0:49
> Invalid ICU message. Missing '}'. ("ео} =1 {1 видео} другие {<x id="INTERPOLATION" equiv-text="{{ videoChannel.videosCount }}"/> видео} }[ERROR ->]"): 0:133
>     It https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     load https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     t https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     fac https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     hydrate https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     get https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     get https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     get https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     kn https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     ds https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     fac https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     Dn https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     i https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     x https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     create https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     bootstrap https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     _moduleDoBootstrap https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     _moduleDoBootstrap https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     bootstrapModuleFactory https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     invoke https://peervideo.ru/client/ru-RU/polyfills-es2015.88f86a15ce4c7f3ca9bb.js:1
>     onInvoke https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     invoke https://peervideo.ru/client/ru-RU/polyfills-es2015.88f86a15ce4c7f3ca9bb.js:1
>     run https://peervideo.ru/client/ru-RU/polyfills-es2015.88f86a15ce4c7f3ca9bb.js:1
>     O https://peervideo.ru/client/ru-RU/polyfills-es2015.88f86a15ce4c7f3ca9bb.js:1
>     invokeTask https://peervideo.ru/client/ru-RU/polyfills-es2015.88f86a15ce4c7f3ca9bb.js:1
>     onInvokeTask https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     invokeTask https://peervideo.ru/client/ru-RU/polyfills-es2015.88f86a15ce4c7f3ca9bb.js:1
>     runTask https://peervideo.ru/client/ru-RU/polyfills-es2015.88f86a15ce4c7f3ca9bb.js:1
>     b https://peervideo.ru/client/ru-RU/polyfills-es2015.88f86a15ce4c7f3ca9bb.js:1
> main-es2015.a84d58ace4a94c235c95.js:3:2277311
>     zUnb https://peervideo.ru/client/ru-RU/main-es2015.a84d58ace4a94c235c95.js:3
>     invoke https://peervideo.ru/client/ru-RU/polyfills-es2015.88f86a15ce4c7f3ca9bb.js:1
>     run https://peervideo.ru/client/ru-RU/polyfills-es2015.88f86a15ce4c7f3ca9bb.js:1
>     O https://peervideo.ru/client/ru-RU/polyfills-es2015.88f86a15ce4c7f3ca9bb.js:1
>     invokeTask https://peervideo.ru/client/ru-RU/polyfills-es2015.88f86a15ce4c7f3ca9bb.js:1
>     runTask https://peervideo.ru/client/ru-RU/polyfills-es2015.88f86a15ce4c7f3ca9bb.js:1
>     b https://peervideo.ru/client/ru-RU/polyfills-es2015.88f86a15ce4c7f3ca9bb.js:1

**Comment by Chocobozzz** [comment]
Thanks, I found the bug

**Comment by Alterak** [comment]
> Thanks, I found the bug

There was probably a mistake when translating into my language?

**Comment by Chocobozzz** [comment]
Yes, but it should be fixed now.
