### ISSUE TITLE
Play private video through embed

### ISSUE THREAD

**Issue by Jenner-Zhl** [Chocobozzz/PeerTube#2944]
I used the open api /users/me/videos to get all my videos， and I get embed path in the responses.
With the embedPath I can watch public videos in browser, but this doesn't work for private videos.
Can I play private video through embedPath with some parameters?

**Comment by Chocobozzz** [comment]
> Can I play private video through embedPath with some parameters?

No sorry, it's not available yet

**Comment by Jenner-Zhl** [comment]
If I want to play private video in my android/ios app client, how can I do this?

**Comment by Chocobozzz** [comment]
With https://github.com/Chocobozzz/PeerTube/pull/2926 you can now play private videos in embed. The web browser just need an `access_token`/`refresh_token` in the local storage (set by the peertube client on login)
