### ISSUE TITLE
Blockchain Like System, For Better Long-Term/Archival Protection

### ISSUE THREAD

**Issue by grravity** [Chocobozzz/PeerTube#2946]
I am suggesting somehow implementing some kind of blockchain system, [similar to how LBRY works](https://lbry.com/what), to protect user content long-term. Right now, if someone makes an instance, and it is up, but two years later that server gets taken down, all that content comes down with it. You are reliant on there being a backup somewhere, or someone duplicating it which is not always easy and may require a lot of bandwidth and storage capacity.

So, I am suggesting implementing a blockchain system, similar to how LBRY operates, alongside the PeerTube instance based system. This would make for an extremely redundant, safe, and amazing platform, that will last long term. 
I cannot speak for technicalities as to whether this is even possible to implement in PeerTube, how exactly it works or would work, as I am not extremely familiar with this from a technical stance. But I do think a system like this, would be absolutely amazing for the platform, and truly maintaining the ideals of decentralization and long-term protection. If there is any possibility of this, I hope it is considered thoroughly. I think it would be a great implementation for the platform and make it more solid, even if a lot of work is required, it'd be highly beneficial if possible.

**Comment by Alterak** [comment]
The instance has a function that allows you to save video from signed instances. It seems to me much more convenient and correct.

**Comment by grravity** [comment]
> The instance has a function that allows you to save video from signed instances. It seems to me much more convenient and correct.

When you say saved video, you mean just download them? And you are suggesting reupload them to another instance? If this is what you mean, don't get me wrong I think this is totally awesome and practical, but not for long term. As I said above:

>Right now, if someone makes an instance, and it is up, but two years later that server gets taken down, all that content comes down with it. You are reliant on there being a backup somewhere, or someone duplicating it which is not always easy and may require a lot of bandwidth and storage capacity.

So you're pretty much at the mercy of hoping that if an instance gets taken down, that someone downloaded all the videos. And even then, you're probably not gonna have all of them as it would depend on the last time someone downloaded them, unless they were doing it by a script which auto-grabbed them. You would also have to hope that those people grabbed them in original quality, otherwise they will be compressed somehow, which is also not good for long-term. Also if these people lost their downloads, the videos are essentially gone. If it was only one person who duplicated all their videos, you better hope they had a backup, and even then if something happened to those people, or both backups died for whatever reason, or they simply didn't share those backups with anyone else, that's it all that content is gone forever which is a major issue.

Download videos, and blockchain functionality similar to LBRY, are two totally different things that can be similar but one is far more reliable than the other and _ensures_ long-term. Downloading is good, but  I would in no way trust it long-term. Again I understand the blockchain like feature would be more work to implement, but I genuinely feel it would be an amazing thing both short and long term if possible.

**Comment by controlunit** [comment]
I concur. A ipfs storage solution is mandated for all instances running activityPub, and should be easily used by them through simple extensions.

It would simply store and access files from IPFS. It would be a standalone service and provide an API. It would not be limited to activityPub either it could be universally used on any Linux through extensions.

Why would anyone load up an instance with a large amount of work and content when any HostBastard could simply delete the vps?

**Comment by Chocobozzz** [comment]
Hello,

Thanks for this issue but it's out of the scope of the project.

**Comment by grravity** [comment]
Not to argue, I know I'm not the dev, but I just wanted to throw in the argument I disagree and think it is in the scope of the project. 

I just first wanted to state, that this is pretty much the only major feature Lbry has over Peertube, and I'd argue it's major enough that people may choose Lbry over Peertube because of it. 

Secondly, as seen above It's clear I'm not the only one with an interest in this. I fail to understand how a feature like this would not be beneficial to Peertube, It'd protect user content with redundancy to ensure even if an instance goes down, the content never goes away. This is critical when it comes to censorship, and could be hugely beneficial long term. 

Even if this gets put at lowest priority, to simply implement it (even as an option for instance host to enable) I fail to see any harm that won't provide a massive gain.

Again, not to argue, but I fail to see why this could not be considered implementing in the future. Peertube is definitely the "platform" of the future, and this would only ensure it.

I hope this maybe gets discussed a bit more, and reconsidered. If not, understandable, I know I'm not a dev but just wanted to fight it a little because I think long term stuff like this is important to consider.

Thanks for your time.
