### ISSUE TITLE
global search bug

### ISSUE THREAD

**Issue by k09i71** [Chocobozzz/PeerTube#2948]
**What happened?**
FF is blocking a popup and you can't _open in a new tab_ one of the global search results.
**What do you expect to happen instead?**
Be able to _right click_ and _open in a new tab_ a global search result 
**Steps to reproduce:**

1. do a global search

2. on the first result that you see, do: _right click_ and _open in a new tab_

3. you will see that in that new tab FF "has blocked" a popup and hasn't opened the video

4. if you do a simple _left click_ on that same first result then it'll work just fine

**Additional information**
* PeerTube version or URL: 2.3 rc 1
* Browser name/version: FF 76

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/0bdad52fbbad81e7654adc495088da56a00437df
