### ISSUE TITLE
login page shows links for signup/forget password buttons

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#2950]
![Screenshot_20200711_192301](https://user-images.githubusercontent.com/39449563/87225637-2faed680-c3ac-11ea-8587-99e2630bb2fe.png)

**What happened?**
check the screenshot of login page. it shows "create an account"/"i forgot my password" but they appear as links.
**What do you expect to happen instead?**
they should show up as buttons

**Comment by Chocobozzz** [comment]
*"create an account"* is actually a link

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/30961c52d2083ac249fb6274f1ded00cf1b0c69a
