### ISSUE TITLE
Does Peertube allow the user directory to be different than /var/www/peertube?

### ISSUE THREAD

**Issue by controlunit** [Chocobozzz/PeerTube#2951]
For instance the installation instructions say:

Create a peertube user with `/var/www/peertube` home:

`$ sudo useradd -m -d /var/www/peertube -s /bin/bash -p peertube peertube`

However, can a different directory such as the following be used instead?
`/home/peertube/web/peertube.somesite.com`

**Comment by JohnXLivingston** [comment]
Yes you can, as long as you change the configuration accordingly.
And for later upgrades, you can use the script this way:
`sudo -H -u peertube ./upgrade.sh /home/peertube/web/`
