### ISSUE TITLE
Default ABC  channel / Main ABC channel

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#2953]
**What happened?**
Below the videos, peertube currently shows words "main" and "default" as a prefix to the channel name. 

**What do you expect to happen instead?**
Is this necessary? Can we use the words as a suffix instead because if I say check out ABC channel or I see a video, its normal to check the icon/name and I find the prefix off.
Maybe im being unreasonable,  question, is this because the user hasnt named their channels?

https://tilvids.com/videos/watch/3b4be045-bcd0-4968-a4e7-99fbde8bd281

This link says
"Main arcaneengine channel".
Can we rewrite this as 
"Arcaneengine - Main Channel"

If we really have to differentiate between channels not based on name but also on having prefix/suffix of the word channel  ?

https://peertube.cpy.re/videos/watch/da2b08d4-a242-4170-b32a-4ec8cbdca701

Here it says
"Default Chocobozzz channel"

**Comment by k09i71** [comment]
I agree that the text doesn't look good.

But why do we even need **"Main"** ABC **"channel"**? I think the text should just say ABC and that's it. Below that it says "By ABCauthor" so it's pretty clear that the ABC channel was created "By the ABCauthor".
