### ISSUE TITLE
Playback of videos not possible on iOS with only hls enabled

### ISSUE THREAD

**Issue by tgurr** [Chocobozzz/PeerTube#2955]
**What happened?**

Playback of videos is not possible on iOS when the PeerTube instance is configured with only hls:

```
  webtorrent:
    enabled: false
  hls:
    enabled: true
```

**What do you expect to happen instead?**

Plaback working as expected.

**Steps to reproduce:**

1. set webtorrent to false, hls to true

2. restart peertube

3. upload a video

4. try to play it on an iOS device

**Additional information**
* PeerTube version or URL: 2.2.0
* Browser name/version: iOS 13.5.1 / Safari
* NodeJS version: 12.18.2

When having webtorrent enabled either solely or additionally video playback works.

**Comment by kimsible** [comment]
Hi, I have the same issue with HLS and webtorrent enabled, but only on specifics videos : ones with 1080p encoding.

**Comment by Chocobozzz** [comment]
Thanks for the issue. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/69a019968e225f1eac4a3df3041f141d0047d7f0
