### ISSUE TITLE
Next to impossible to use the video controls on iOS when webtorrent and hls are enabled

### ISSUE THREAD

**Issue by tgurr** [Chocobozzz/PeerTube#2956]
**What happened?**

* Switches to fullscreen video as soon as one hits the play button.
* Video controls are hardly usable on iOS when both webtorrent and hls are enabled in PeerTube as there's a second overlay of video controls present.

<img width="375" alt="torrent_and_hls_enabled" src="https://user-images.githubusercontent.com/414984/87309986-98699080-c51d-11ea-9c5d-7dc1e6161bb6.png">

**What do you expect to happen instead?**

Behave the same like with only webtorrent enabled where the video controls work just fine and no additonal second overlay is present.

<img width="375" alt="torrent_only" src="https://user-images.githubusercontent.com/414984/87309998-9d2e4480-c51d-11ea-8863-e66a3f382afc.png">

**Steps to reproduce:**

1. enable webtorrent and hls

2. upload a video

3. try to use the playback controls on iOS

**Additional information**
* PeerTube version or URL: 2.2.0
* Browser name/version: iOS 13.5.1 / Safari
* NodeJS version: 12.18.2

**Comment by Chocobozzz** [comment]
Could you tell me if you reproduce this issue with https://peertube2.cpy.re/videos/watch/969bf103-7818-43b5-94a0-de159e13de50 please?
