### ISSUE TITLE
Haproxy -> Nginx -> instance, web browser public IP is 127.0.0.1

### ISSUE THREAD

**Issue by BOBMASRER** [Chocobozzz/PeerTube#2957]
**What happened?**

PeerTube thinks your web browser public IP is 127.0.0.1.

**What do you expect to happen instead?**

PeerTube thinks your web browser public IP is **real ip**

Nginx as backend listen on 8080 Haproxy as the frontend listen on 443
Everything works on well except the **trust_proxy** setting, i don't know how to do to get the ideal result.
I have tried **loopback** 、**127.0.0.1**，got the same result.
Any solutions? Thanks

**Comment by rigelk** [comment]
The `trust_proxy` option forwards its configuration to Express, so you might want to refer to [its documentation](https://expressjs.com/en/guide/behind-proxies.html) for such edge-cases.

> […] [the] IP address is understood as the left-most entry in the `X-Forwarded-*` header.

Check your Haproxy configuration sets that header, [like we did in our Nginx configuration](https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube#L98).

**Comment by BOBMASRER** [comment]
Thanks for your reply.
I got this problem after setting.
`"stack": "TypeError: invalid IP address: 1oopback\n    at parseipNotation (/var/www/peertube/versions/peertube-v2.2.0/node_modules/proxy-addr/index.js:163:11)\n    at compileRangeSubnets (/var/www/peertube/versions/peertube-v2.2.0/node_modules/proxy-addr/index.js:126:23)\n    at Function.compile (/var/www/peertube/versions/peertube-v2.2.0/node_modules/proxy-addr/index.js:112:23)\n    at exports.compileTrust (/var/www/peertube/versions/peertube-v2.2.0/node_modules/express/lib/utils.js:238:20)\n    at Function.set (/var/www/peertube/versions/peertube-v2.2.0/node_modules/express/lib/application.js:372:34)\n    at Object.<anonymous> (/var/www/peertube/versions/peertube-v2.2.0/dist/server.js:49:5)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)"`

**Comment by rigelk** [comment]
You have a typo. `1oopback` is invalid.

**Comment by BOBMASRER** [comment]
I am sure i have edited the production.yaml and systemctl restart peertube but still get the same result.
