### ISSUE TITLE
Seed videos from torrent client to PeerTube instance.

### ISSUE THREAD

**Issue by doneforaiur** [Chocobozzz/PeerTube#2958]
Correct me if I'm wrong but as far as I understand users can only seed from the instance to other users as long as they're watching _the same video at the same time_. If that's the case; wouldn't it be nice to seed from torrent client to the users which are viewing the video directly?

**Comment by k09i71** [comment]
This wasn't possible, until now: https://feross.org/libtorrent-webtorrent

**Comment by doneforaiur** [comment]
@k09i71, WebTorrent doesn't show any peers so is BitTorrent. But on the video it displays 6 peers for example. I'm not completely sure to be honest. :(

**Comment by rigelk** [comment]
@doneforaiur WebSeeds are not taken into account in the count, only those connected to the tracker are.
