### ISSUE TITLE
duplicate videos from import-video.js

### ISSUE THREAD

**Issue by mclegrand** [Chocobozzz/PeerTube#2959]
Hi, (first, thanks a lot for peertube, it's an awesome project!)

**What happened?**
When importing the videos from youtube, I ran the import-video.js script several times (in a loop) because I had a several hundred videos to import, and it kept failing after a while (I suppose some token expires?).
In the end, after everything is imported, most videos were imported between 2 and 10 times into the server and I now have roughly 2000 videos instead of 400.

**What do you expect to happen instead?**
Video only imported once ? Or a way to quickly deduplicate videos in one account (they all have the same content, same description, same title...).

**Steps to reproduce:**
1. run import-video.js, restart it every time it fails

**Additional information**
* PeerTube version or URL: 2.2.0
* NodeJS version: v10.21.0

**Comment by Chocobozzz** [comment]
Hello and thank you :)

We need to implement https://github.com/Chocobozzz/PeerTube/issues/2467 to fix this issue
