### ISSUE TITLE
Service Worker isn't registered

### ISSUE THREAD

**Issue by lucaspontoexe** [Chocobozzz/PeerTube#296]
* **PeerTube version or commit:**
Peertube 0.0.24
* **Browser name/version:**
Google Chrome

* **What is the expected behaviour?**
Browsers should detect the service worker
* **What do you see instead?**
SW isn't detected. Probably it's not registered.

_Lighthouse audit:_
![](https://puu.sh/zp54o/f0c3ddca37.png)

**Comment by Chocobozzz** [comment]
Fixed: https://github.com/angular/angular-cli/issues/8779

**Comment by Chocobozzz** [comment]
I disabled it (https://github.com/Chocobozzz/PeerTube/commit/fed951557277a6f783c75909f4cbeb21c4159133) due to https://github.com/angular/angular/issues/21191

**Comment by BO41** [comment]
this issue does not seem to be blocked anymore :smiley:
