### ISSUE TITLE
Multiple issues in 2.3.0-rc.1 / OpenBSD

### ISSUE THREAD

**Issue by 22decembre** [Chocobozzz/PeerTube#2961]
Sorry for non-precision of title.

**What happened?**

I updated to 2.3.0-rc.1, hoping to provide feedback as I am on vacation. I used the upgrade script from version 2.2.0. Upgrade process was fine. Then when having a look at the logs, I get a lot of warnings and errors relating to SQL among other things.

**What do you expect to happen instead?**

That I did not have those warnings.

**Additional information**
* PeerTube version or URL:  https://github.com/Chocobozzz/PeerTube/releases/tag/v2.3.0-rc.1
* Instance : https://tube.22decembre.eu
* OS : OpenBSD 6.7
* NodeJS version:   v12.16.1

* Link to browser console log if useful:  https://pastebin.com/fq1aRrjs
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by 22decembre** [comment]
Notice that I checked well the database migration in 2.2.0 and had no issues at the time.

**Comment by Chocobozzz** [comment]
Try to fix this using https://github.com/Chocobozzz/PeerTube/issues/1531#issuecomment-454454107 on problematic tables (`videoView`, `videoCaption` ...)

I don't know why your database "loose" the `SERIAL` pseudo type

**Comment by 22decembre** [comment]
`peertube_prod2=> ALTER SEQUENCE import_id_seq OWNED BY "videoImport"."id";
ALTER SEQUENCE
peertube_prod2=> \d "videoImport"
                                     Table "public.videoImport"
   Column    |           Type           | Collation | Nullable |              Default               
-------------+--------------------------+-----------+----------+------------------------------------
 id          | integer                  |           | not null | nextval('import_id_seq'::regclass)
 targetUrl   | character varying(2000)  |           |          | NULL::character varying
 magnetUri   | character varying(2000)  |           |          | NULL::character varying
 torrentName | character varying(255)   |           |          | NULL::character varying
 state       | integer                  |           | not null | 
 error       | text                     |           |          | 
 userId      | integer                  |           | not null | 
 videoId     | integer                  |           |          | 
 createdAt   | timestamp with time zone |           | not null | 
 updatedAt   | timestamp with time zone |           | not null | 
Indexes:
    "videoImport_pkey" PRIMARY KEY, btree (id)`

or

`peertube_prod2=> ALTER TABLE ONLY "videoImport" ALTER COLUMN "id" TYPE SERIAL;
ERROR:  type "serial" does not exist`

I got that a few times. I guess it's why my DB is kind of confused.
