### ISSUE TITLE
vidiverse search bug

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#2964]
**What happened?**
https://peertube2.cpy.re/search?search=kde&searchTarget=search-index
https://peertube2.cpy.re/search?search=kde&searchTarget=local

local search works as expected.
index search results do not allow middle click, right click. it simply opens the current page in a new tab and firefox says popup blocked. it accepts simple left click which opens results in new tab
**What do you expect to happen instead?**
index results should allow right click or middle click, same as local results

**Additional information**
* PeerTube version or URL:https://peertube2.cpy.re/
* Browser name/version:firefox 78.0.1 (64-bit)
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by rigelk** [comment]
Hi @test2a! Please look out for related issues before creating one, as #2948 already covers this. You can then detail further your use case there, and upvote the issue to help us triage it.
