### ISSUE TITLE
Question: What is the difference between "local" videos and regular ones on an instance

### ISSUE THREAD

**Issue by TsymbalArtem** [Chocobozzz/PeerTube#2967]
Hello. Could you help me to understand what is the difference between "local" videos and regular ones on an instance?

**Comment by TsymbalArtem** [comment]
I tried to import videos with magnet-URI from other instances, but they also became local. So I don't understand why do we need such a filter.

**Comment by JohnXLivingston** [comment]
Local videos are videos that are hosted by your instance. In other views, you will also have video from instances you are federating with.

**Comment by TsymbalArtem** [comment]
@JohnXLivingston thanks, where can I find information on how to federate instances?

**Comment by JohnXLivingston** [comment]
https://joinpeertube.org/#what-is-peertube
https://docs.joinpeertube.org/#/admin-following-instances

**Comment by TsymbalArtem** [comment]
Thanks
