### ISSUE TITLE
Pour visiteurs anonymes, Peertube impose le theme "peertube default" au lieu de "instance default" quelques soit les reglages dans production.yml et le tableau de bord de l'administrateur

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#2968]
**What happened?**
Dans le tableau de bord de l'administrateur, j'ai installé le theme bittube-dark-mode, je l'ai choisi dans la Configuration/Basic Configuration, et dans production.yml j'ai mis le reglage :

theme:
default: ‹ bittube-dark-mode ›

Apres, bien sur, j'ai redemarre le service peertube.

Quand me me rends a la page d'acceuil de mon instance en utilisateur anonyme, le site se presente avec le theme par defaut de Peertube (blanc et orange).

Il est vrai que je peux me rendre dans le popup Settings et choisir le theme bittube-dark-mode, mais la valeur par defaut c'est "peertube default" (meme pas "instance default".

**What do you expect to happen instead?**

Ayant defini bittube-dark-mode dans le fichier production.yml et dans le tableau de bord de l'administrateur, je m'attendrai a ce que le theme par defaut montre aux visiteurs anonyme soit bittube-dark-mode (ou au moins le "instance default".

COMMENT FAIRE EN SORTE QUE LES VISITEURS ANONYMES VOIENT LE THEME PAR DEFAUT DE L'INSTANCE AU LIEU DU THEME PAR DEFAUT DE PEERTUBE ?

Une valeur dans la base de donnees ? Une valeur dans un des fichiers Js ?

**Steps to reproduce:**

J'ai explique ci-dessus donc je ne me repete pas inutilement ici...

**Additional information**
* PeerTube version or URL: 2.2
* Browser name/version: Firefox ou Chrome
* NodeJS version: celle preconisee pour Peertube 2.2

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by DalekDave** [comment]
English translation : 
In the root admin control panel, I installed the bittube-dark-mode theme, and in my instance’s production.yaml I set:

theme:
default: ‹ bittube-dark-mode ›

Obviously, I restarted the peertube service afterwards, so the change in production.yml would be implemented.

But when I visit the site as an anonymous user, the default Peertube light theme is shown. If I go to the Settings and open the Theme dropdown in the Interface settings, I can choose between ‹ instance default ›, ‹ peertube default › and ‹ bittube-dark-mode ›. But the default choice is ‹ peertube default ›.

How can I set the default setting to ‹ instance default › instead of ‹ peertube default ›, so that my site automatically loads with the dark theme when anonymous users visit?

**Comment by NoZdageek** [comment]
Hi,

I can confirm this issue, I did a fresh install yesterday and got the same behavior.

**Comment by Chocobozzz** [comment]
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/2893
