### ISSUE TITLE
sort videos in a better way (when preferring a language that's not English)

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#2969]
1. click on '_Settings'_ 

2. choose any language that's not English (like Korean) in the _'Only display videos in the following languages/subtitles'_ 

3. visit the trending page

4. observe that videos which have Korean subtitles are mixed with videos which have set _Korean_ as the language of the video. 

**What do you expect to happen instead?**

Videos which have Korean subtitles should follow after the videos which have set _Korean_ as the language of the video. This order makes more sense (at least to me).

* PeerTube version or URL: any 2.2 instance

**Comment by Chocobozzz** [comment]
Hello,

Closing this inactive discussion that does not seem to have received positive support.
