### ISSUE TITLE
Add ability to delete failed or 'failed' pending imports

### ISSUE THREAD

**Issue by Niquarl** [Chocobozzz/PeerTube#2974]
It would be great to add the possibility of wiping the 'my imports' page. Some of my imports have failled and so they have cluttered the page. Perhaps a way to do this would be to check if the same URL was importing succesfully.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/419b520ca4434d17f3505013174e195c3a316716
