### ISSUE TITLE
Installation fails at command: `cd ./peertube-latest && sudo -H -u peertube yarn install --production --pure-lockfile`

### ISSUE THREAD

**Issue by controlunit** [Chocobozzz/PeerTube#2975]
**What happened?**

Installation fails at command: `cd ./peertube-latest && sudo -H -u peertube yarn install --production --pure-lockfile`

error:
`yarn: error: no such option: --production`

**What do you expect to happen instead?**

success of the above command

**Steps to reproduce:**

Do the install steps listed here:
`https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md`

**Additional information**
* PeerTube version or URL:
* Browser name/version:
* NodeJS version:

v2.2.0

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by rigelk** [comment]
Please check your version of yarn.

**Comment by Chocobozzz** [comment]
Use the documentation to install yarn: https://docs.joinpeertube.org/#/dependencies
