### ISSUE TITLE
Re-subscription to instances

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#2978]
Due to my fault, the data storage was deleted, unfortunately it was not possible to restore all the data.
I had to manually clean up all empty videos and images, and then restore everything from the beginning. I also had to manually delete all the copies to which I was subscribed to exchange videos.

Now I started all over again, but requests to add these instances do not come to me. Probably the only option is to add everyone manually.
I think that all the data on the added instances before is stored in the database, therefore, automatic subscription is not working now. Maybe I'm wrong.

Is it possible to restore the automatic addition of instances that I manually deleted?

Peertube version - 2.2.0

**Comment by Chocobozzz** [comment]
I'm sorry but I don't understand. Could you give me what you want to do with a specific instance for example?

**Comment by Alterak** [comment]
> I'm sorry but I don't understand. Could you give me what you want to do with a specific instance for example?

I'll try to write all the steps:
If you install a new instance and enable the function to automatically subscribe to other instances, then after a while there will be many subscribers. It works right and well.
If you manually delete subscribers, then requests from them will no longer come. 
And I want to receive requests from them again.

And how can you fix empty previews in the general video list?
![1](https://user-images.githubusercontent.com/11453567/87912091-686a4200-ca75-11ea-92fd-871d0aa9ac4e.PNG)


I hope now you understand me?

**Comment by Chocobozzz** [comment]
> If you manually delete subscribers, then requests from them will no longer come.
And I want to receive requests from them again.

Refollow them using the admin interface?

> And how can you fix empty previews in the general video list?

Try to watch the video, maybe peertube will refresh the video and download the thumbnail

**Comment by Alterak** [comment]
> Try to watch the video, maybe peertube will refresh the video and download the thumbnail

It worked. Thank.


> Refollow them using the admin interface?

Do I need to add subscribers manually? I would not like to do this. I want all subscribers to be added automatically again. This function is enabled in the settings.
![2](https://user-images.githubusercontent.com/11453567/87915210-7c647280-ca7a-11ea-863d-1c2dd33b322d.PNG)

**Comment by Chocobozzz** [comment]
> Do I need to add subscribers manually?

Yes

>  This function is enabled in the settings.

You mean the `auto follow back instances`? If yes, you can't ask other instances to refollow yours. But you can copy followings from the about page and paste them in the follow tab of the admin
