### ISSUE TITLE
Improvement generic channel UI

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#2987]
When an instance has closed registration, the only way to create accounts for the moment is to use the admin / moderation feature  « Admin > users > create user ».

The form allows the user to choose its account password by sending a mail. But we miss the unique channel name. So a generic channel name is created ***username*_channel**. Display channel name is also generated **Main *username* channel**.

The user is not as well as guided than the `signup` form when registration are opened on the instance. So the user misses all the required configuration of its own channel. I may be wrong but most of PeerTube instances have closed registrations for several reasons, so the signup form is not very used, and never for most instances then.

An example of how channel description looks like under the watch view of the video : 

![image](https://user-images.githubusercontent.com/1877318/87943789-d414d500-ca9e-11ea-85aa-621ad5ef2ffe.png)

I think we need 4 levels of improvements : 
- [x] **UI - High priority - Easy** Do not display the channel display name and avatar when both are not customized ;
   Allow old channels created to benefit at least an improvement; 
- [ ] **Admin- High priority - Average** Let the admin/modo enter a channel name, it will resolve one thing (only the unwanted generic unique channel name);
- [ ] **Admin - Medium priority - Average** Let the admin/modo send an invitation link in the admin creation form with the ability to pre-define role, quotas and blacklist video option;
- [ ] **UI + federation update - Low priority - hard** Ability to rename the unique channel name with federation / followers instances update.

**Comment by kimsible** [comment]
> > Ability to rename the unique channel name with federation / followers instances update.
> 
> I don't think we'll implement this soon grin

Yes, that's why I put it as a low priority, but as I said here : https://framacolibri.org/t/edit-channel-and-account-url-name/8394/7

> Naming URLs can be an issue for creators who change their names (in case of civil state changes if they use their legal name, for example trans/non-binary people are deeply concerned).

We don't have to put them aside, and reproduce what Google/YouTube does, the right to change our name is also in the law in most of countries especially in France. Some people use a pseudonym, some people does use their legal names. It would be unfair to let this issue unchanged for a long time, when especially some of them want to go on PeerTube to avoid Google / YouTube Politic. 

The option to create a new channel and transfer all videos of the old channel to the new one puts the concerned user on an unfair choice : **Loose all your followers and channel views or be exposed with your dead-name and the fact you're transitioning**. This feature should be considered as an accessibility feature, changing name is a question of survival for some people and being forced to expose this condition is a serious social handicap.

**Comment by NathanPlus** [comment]
Yep. And outside of trans rights, being able to easily change your name seems to me to be an important right. Anonymity is something to defend, as well as identity changes

**Comment by Chocobozzz** [comment]
Channel name has also been implemented (https://github.com/Chocobozzz/PeerTube/pull/2984).

**Comment by kimsible** [comment]
> Channel name has also been implemented (#2984).
Ok @Chocobozzz, I checked it in the description.

It can be better to let this issue opened to track working of the 2 others features not yet implemented :

> Admin - Medium priority - Average Let the admin/modo send an invitation link in the admin creation form with the ability to pre-define role, quotas and blacklist video option;
> UI + federation update - Low priority - hard Ability to rename the unique channel name with federation / followers instances update.
