### ISSUE TITLE
Peertube refuses to play vidoes

### ISSUE THREAD

**Issue by aaruni96** [Chocobozzz/PeerTube#2990]
**What happened?**
When I try to open a video on peertube, all I get is a "loading" circle, and the video never really starts playing.

**What do you expect to happen instead?**
When I open a video, it should play.

**Steps to reproduce:**

1. Upload video

2. Go to video page

3. Try to play video. Video doesn't play.

**Additional information**
* PeerTube version or URL: 2.2.0
* Browser name/version: Firefox 78.0.2
* NodeJS version: 10.21.0

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
> {"err":{"stack":"Error: Unknown infoHash a0ed7879e823aedb04e504ff61712b6b2670e725\n    at Server.<anonymous> (/var/www/peertube/versions/peertube-v2.2.0/dist/server/controllers/tracker.js:60:27)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v2.2.0/dist/server/controllers/tracker.js:5:58)","message":"Unknown infoHash a0ed7879e823aedb04e504ff61712b6b2670e725"},"level":"warn","message":"Warning in tracker.","label":"peertube.local:80","timestamp":"2020-07-20T22:44:00.647Z"}

**Comment by rigelk** [comment]
What video are you trying to watch?

**Comment by aaruni96** [comment]
Doesn't matter which video. I uploaded a few to the instance, and all of them refused to play.

For now, I nuked the test VM, and I'm starting from scratch. Will report back when that's done.

**Comment by aaruni96** [comment]
On a fresh debian buster, with Peertube v 2.3.0 .

I don't have that entry in the logs anymore, but peertube still refuses to play video.

Interesting thing I have noticed is that on the "About" page, it shows "0B of hosted video"

**Comment by aaruni96** [comment]
Update : If I just leave the loading page open for long enough, eventually the video begins to play.

But waiting ~2 minutes to watch a 3mb video hosted on a VM on the same disk seems too much.

**Comment by rigelk** [comment]
What is your server URL?

**Comment by aaruni96** [comment]
Its a local site which does not face the internet. Its http://peertube.local , if that makes any difference.

**Comment by rigelk** [comment]
@aaruni96 it just means we can't see the error for ourselves - it's harder to debug.

**Comment by aaruni96** [comment]
Maybe this gist will help.

https://gist.githubusercontent.com/aaruni96/db7e74e0770b89406ae69158b5638d6a/raw/7008eeee71224bff08d6d71e24884197baafb23b/peertube.log

By what I can tell, there are no errors. Just a really long delay between clicking the play button at 00:02:56.573 , and actually starting to play at 00:04:51.318 .

More info I can think of providing is the fact that if I open up browser dev tools to find the m3u8 file and put that into VLC, it begins to play immediately.

**Comment by Chocobozzz** [comment]
Please create a production peertube instance (with a public domain name) so we can reproduce your issue
