### ISSUE TITLE
Implement Server-side rendering for SEO and descriptions in search results

### ISSUE THREAD

**Issue by peertubeserversiderendering** [Chocobozzz/PeerTube#2999]
I posted this on reddit, one of the comments was we need server-side rendering. 

I am on the latest version. This is what I get for all results when I search on google for my instance with "site:my.peertube.instance"   

"We are sorry but it seems that PeerTube is not compatible with your web browser. Please try with the latest version of Mozilla Firefox. If you think this is a mistake, ... "

I would love peertube as is if search results could actually have the description listed... and a thumbnail so it's obvious the search result leads to a video.

**Comment by Chocobozzz** [comment]
What is your instance URL?
