### ISSUE TITLE
Fail to start after upgrade

### ISSUE THREAD

**Issue by lstamellos** [Chocobozzz/PeerTube#3000]
**What happened?**

After upgrade to 2.3.0 the peertube service fails to start, with the following output:

***
Jul 24 03:47:37 systemd[1]: Started PeerTube daemon.
Jul 24 03:47:38 peertube[30341]: > peertube@2.3.0 start [peertube_dir]/versions/peertube-v2.3.0
Jul 24 03:47:38 peertube[30341]: > node dist/server
Jul 24 03:47:40 peertube[30341]: [video.omniatv.com:443] 2020-07-24 03:47:40.264 info: Begin migrations.
Jul 24 03:47:40 peertube[30341]: [video.omniatv.com:443] 2020-07-24 03:47:40.267 info: Executing 0475-redundancy-expires-on.js migration script.
Jul 24 03:47:40 peertube[30341]: [video.omniatv.com:443] 2020-07-24 03:47:40.277 error: Cannot execute migration 0475. {
Jul 24 03:47:40 peertube[30341]:   "err": {
Jul 24 03:47:40 peertube[30341]:     "stack": "SequelizeDatabaseError: must be owner of relation videoRedundancy\n    at Query.formatError ([peertube_dir]/versions/peertube-v2.3.0/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)\n    at query.catch.err ([peertube_dir]/versions/peertube-v2.3.0/node_modules/sequelize/lib/dialects/postgres/query.js:72:18)\n    at tryCatcher ([peertube_dir]/versions/peertube-v2.3.0/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler ([peertube_dir]/versions/peertube-v2.3.0/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise ([peertube_dir]/versions/peertube-v2.3.0/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 ([peertube_dir]/versions/peertube-v2.3.0/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises ([peertube_dir]/versions/peertube-v2.3.0/node_modules/bluebird/js/release/promise.js:725:18)\n    at _drainQueueStep ([peertube_dir]/versions/peertube-v2.3.0/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue ([peertube_dir]/versions/peertube-v2.3.0/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues ([peertube_dir]/versions/peertube-v2.3.0/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] ([peertube_dir]/versions/peertube-v2.3.0/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)",
Jul 24 03:47:40 peertube[30341]:     "message": "must be owner of relation videoRedundancy",
Jul 24 03:47:40 peertube[30341]:     "name": "SequelizeDatabaseError",
Jul 24 03:47:40 peertube[30341]:     "parent": {
Jul 24 03:47:40 peertube[30341]:       "stack": "error: must be owner of relation videoRedundancy\n    at Parser.parseErrorMessage ([peertube_dir]/versions/peertube-v2.3.0/node_modules/pg-protocol/dist/parser.js:241:15)\n    at Parser.handlePacket ([peertube_dir]/versions/peertube-v2.3.0/node_modules/pg-protocol/dist/parser.js:89:29)\n    at Parser.parse ([peertube_dir]/versions/peertube-v2.3.0/node_modules/pg-protocol/dist/parser.js:41:38)\n    at Socket.stream.on ([peertube_dir]/versions/peertube-v2.3.0/node_modules/pg-protocol/dist/index.js:8:42)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
Jul 24 03:47:40 peertube[30341]:       "message": "must be owner of relation videoRedundancy",
Jul 24 03:47:40 peertube[30341]:       "length": 101,
Jul 24 03:47:40 peertube[30341]:       "name": "error",
Jul 24 03:47:40 peertube[30341]:       "severity": "ERROR",
Jul 24 03:47:40 peertube[30341]:       "code": "42501",
Jul 24 03:47:40 peertube[30341]:       "file": "aclchk.c",
Jul 24 03:47:40 peertube[30341]:       "line": "3415",
Jul 24 03:47:40 peertube[30341]:       "routine": "aclcheck_error",
Jul 24 03:47:40 peertube[30341]:       "sql": "ALTER TABLE \"videoRedundancy\" ALTER COLUMN \"expiresOn\" DROP NOT NULL;ALTER TABLE \"videoRedundancy\" ALTER COLUMN \"expiresOn\" SET DEFAULT NULL;ALTER TABLE \"videoRedundancy\" ALTER COLUMN \"expiresOn\" TYPE TIMESTAMP WITH TIME ZONE;"
Jul 24 03:47:40 peertube[30341]:     },
Jul 24 03:47:40 peertube[30341]:     "sql": "ALTER TABLE \"videoRedundancy\" ALTER COLUMN \"expiresOn\" DROP NOT NULL;ALTER TABLE \"videoRedundancy\" ALTER COLUMN \"expiresOn\" SET DEFAULT NULL;ALTER TABLE \"videoRedundancy\" ALTER COLUMN \"expiresOn\" TYPE TIMESTAMP WITH TIME ZONE;"
Jul 24 03:47:40 peertube[30341]:   }
Jul 24 03:47:40 peertube[30341]: }
Jul 24 03:47:40 peertube[30341]: npm ERR! code ELIFECYCLE
Jul 24 03:47:40 peertube[30341]: npm ERR! errno 255
Jul 24 03:47:40 peertube[30341]: npm ERR! peertube@2.3.0 start: `node dist/server`
Jul 24 03:47:40 peertube[30341]: npm ERR! Exit status 255
Jul 24 03:47:40 peertube[30341]: npm ERR!
Jul 24 03:47:40 peertube[30341]: npm ERR! Failed at the peertube@2.3.0 start script.
Jul 24 03:47:40 peertube[30341]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Jul 24 03:47:40 peertube[30341]: npm ERR! A complete log of this run can be found in:
Jul 24 03:47:40 peertube[30341]: npm ERR!     /home/video/.npm/_logs/2020-07-24T00_47_40_287Z-debug.log
Jul 24 03:47:40 systemd[1]: peertube.service: Main process exited, code=exited, status=255/n/a
Jul 24 03:47:40 systemd[1]: peertube.service: Failed with result 'exit-code'.
Jul 24 03:47:40 systemd[1]: peertube.service: Service hold-off time over, scheduling restart.
Jul 24 03:47:40 systemd[1]: peertube.service: Scheduled restart job, restart counter is at 9.
Jul 24 03:47:40 systemd[1]: Stopped PeerTube daemon.
***

I tried changing owner in postgresql database, but it seems to have no effect.

**Comment by Chocobozzz** [comment]
Go inside your database using `psql` and paste the output of `\d`. Please also tell me what pg user you are using in peertube configuration

**Comment by lstamellos** [comment]
\d output:
***
                       List of relations
 Schema |              Name              |   Type   |  Owner   
--------+--------------------------------+----------+----------
 public | account                        | table    | postgres
 public | accountBlocklist               | table    | postgres
 public | accountBlocklist_id_seq        | sequence | postgres
 public | accountVideoRate               | table    | postgres
 public | accountVideoRate_id_seq        | sequence | postgres
 public | account_id_seq                 | sequence | postgres
 public | actor                          | table    | postgres
 public | actorFollow                    | table    | postgres
 public | actorFollow_id_seq             | sequence | postgres
 public | actor_id_seq                   | sequence | postgres
 public | application                    | table    | postgres
 public | application_id_seq             | sequence | postgres
 public | avatar                         | table    | postgres
 public | avatar_id_seq                  | sequence | postgres
 public | oAuthClient                    | table    | postgres
 public | oAuthClient_id_seq             | sequence | postgres
 public | oAuthToken                     | table    | postgres
 public | oAuthToken_id_seq              | sequence | postgres
 public | plugin                         | table    | postgres
 public | plugin_id_seq                  | sequence | postgres
 public | scheduleVideoUpdate            | table    | postgres
 public | scheduleVideoUpdate_id_seq     | sequence | postgres
 public | server                         | table    | postgres
 public | serverBlocklist                | table    | postgres
 public | serverBlocklist_id_seq         | sequence | postgres
 public | server_id_seq                  | sequence | postgres
 public | tag                            | table    | postgres
 public | tag_id_seq                     | sequence | postgres
 public | thumbnail                      | table    | postgres
 public | thumbnail_id_seq               | sequence | postgres
 public | user                           | table    | postgres
 public | userNotification               | table    | postgres
 public | userNotificationSetting        | table    | postgres
 public | userNotificationSetting_id_seq | sequence | postgres
 public | userNotification_id_seq        | sequence | postgres
 public | userVideoHistory               | table    | postgres
 public | userVideoHistory_id_seq        | sequence | postgres
 public | user_id_seq                    | sequence | postgres
 public | video                          | table    | postgres
 public | videoAbuse                     | table    | postgres
 public | videoAbuse_id_seq              | sequence | postgres
 public | videoBlacklist                 | table    | postgres
 public | videoBlacklist_id_seq          | sequence | postgres
 public | videoCaption                   | table    | postgres
 public | videoCaption_id_seq            | sequence | postgres
 public | videoChangeOwnership           | table    | postgres
 public | videoChangeOwnership_id_seq    | sequence | postgres
 public | videoChannel                   | table    | postgres
 public | videoChannel_id_seq            | sequence | postgres
 public | videoComment                   | table    | postgres
 public | videoComment_id_seq            | sequence | postgres
 public | videoFile                      | table    | postgres
 public | videoFile_id_seq               | sequence | postgres
 public | videoImport                    | table    | postgres
 public | videoImport_id_seq             | sequence | postgres
 public | videoPlaylist                  | table    | postgres
 public | videoPlaylistElement           | table    | postgres
 public | videoPlaylistElement_id_seq    | sequence | postgres
 public | videoPlaylist_id_seq           | sequence | postgres
 public | videoRedundancy                | table    | postgres
 public | videoRedundancy_id_seq         | sequence | postgres
 public | videoShare                     | table    | postgres
 public | videoShare_id_seq              | sequence | postgres
 public | videoStreamingPlaylist         | table    | postgres
 public | videoStreamingPlaylist_id_seq  | sequence | postgres
 public | videoTag                       | table    | postgres
 public | videoView                      | table    | postgres
 public | videoView_id_seq               | sequence | postgres
 public | video_id_seq                   | sequence | postgres
(69 rows)
***

Puzzling. I already tried changing the owner to the user "video" which was setup in the connection.

**Comment by lstamellos** [comment]
Exported the db into an sql file, edited all "owner" statements substituting user "postgres" with user "video". Seems to be fixed now. 

I'm not quite sure what changed the owner in the first place though.
