### ISSUE TITLE
Not all Videos Federating from followed instances

### ISSUE THREAD

**Issue by grondinm** [Chocobozzz/PeerTube#3002]
My instance is acting odd...Instances i've been federating with for months all of a sudden i'm not getting(All) videos from... Like just from the last 3-5 days i'm missing some videos... For examples

My instance
https://video.gcfam.net/video-channels/hexdsl@share.tube/videos

VS Original instance
https://share.tube/video-channels/hexdsl2/videos

But then this one
https://video.gcfam.net/video-channels/gamingwithwerewolves@share.tube/videos

VS
https://share.tube/video-channels/gamingwithwerewolves/videos

Everything is there...

So i'm not sure what's up. I was on 2.2.0 when it started and have since upgraded to v2.3.0

Is there anyway i can force my instance to do like a full refresh of content from another instance.

I know of at least 1 other instance that has the exact same issue with the some remote instance/channel. The admin of this second instance tried to unfollow/follow share.tube but it did not solve the issue for him.

I'm just not sure where else to go at this point in terms of where to look for the potential source of the issue.

**Comment by Chocobozzz** [comment]
Hello,

https://share.tube/video-channels/hexdsl2 seems to have had a PeerTube bug resulting in a weird federation behaviour. Try to follow **hexdsl2@share.tube** instead of **hexdsl@share.tube**

**Comment by grondinm** [comment]
So i don't have remote follow enabled for accounts. I followed the entire share.tube instance with my instance... the hexdsl2 account does not show up in my instance at all...
![image](https://user-images.githubusercontent.com/148904/89033237-bea87200-d30c-11ea-93e8-ffff9e208dbb.png)

**Comment by Chocobozzz** [comment]
Try to search `https://share.tube/video-channels/hexdsl2` instead

**Comment by grondinm** [comment]
ok that does come up but no videos...

![image](https://user-images.githubusercontent.com/148904/89033460-2eb6f800-d30d-11ea-8983-2635724ae004.png)
