### ISSUE TITLE
Follow request from mastodon marqued as pending

### ISSUE THREAD

**Issue by EBendinelli** [Chocobozzz/PeerTube#3003]
**What happened?**
Following a peertube account from a mastodon account result in the request being labeled as pending.

Follow request from @privacyint@mastodon.xyz to @privacyint@media.privacyinternational.org
![image](https://user-images.githubusercontent.com/12803082/88385609-8eaa1d80-cda6-11ea-9c97-151f873452a5.png) 

Notification from the peertube end:
![image](https://user-images.githubusercontent.com/12803082/88385711-c5803380-cda6-11ea-89c1-433abbf56c0e.png)

Other users have reported the same problem. This could very well be a configuration issue from our side but I can't find any useful log to point me in the right direction.

**What do you expect to happen instead?**
Follow request should be automatically accepted.

**Steps to reproduce:**

1. Find @privacyint@media.privacyinternational.org from your mastodon account
2. Click Follow

**Additional information**
* PeerTube version or URL:  2.3.0 - https://media.privacyinternational.org. Instance is being a reverse proxy.
* Browser name/version: Firefox
* NodeJS version: 10.20.1

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
```{"message":"192.168.0.6 - - [24/Jul/2020:11:14:47 +0000] \"POST /accounts/privacyint/inbox HTTP/1.0\" 204 - \"-\" \"http.rb/4.3.0 (Mastodon/3.1.3; +https://mastodon.xyz/)\"\n","level":"info","label":"media.privacyinternational.org:443","timestamp":"2020-07-24T11:14:47.544Z"}
{"level":"info","message":"Receiving inbox requests for 1 activities by https://mastodon.xyz/users/privacyint.","label":"media.privacyinternational.org:443","timestamp":"2020-07-24T11:14:54.136Z"}
{"message":"192.168.0.6 - - [24/Jul/2020:11:14:54 +0000] \"POST /accounts/privacyint/inbox HTTP/1.0\" 204 - \"-\" \"http.rb/4.3.0 (Mastodon/3.1.3; +https://mastodon.xyz/)\"\n","level":"info","label":"media.privacyinternational.org:443","timestamp":"2020-07-24T11:14:54.137Z"}
{"level":"info","message":"Creating job to accept follower https://mastodon.xyz/users/privacyint.","label":"media.privacyinternational.org:443","timestamp":"2020-07-24T11:14:54.176Z"}
{"level":"info","message":"Processing ActivityPub unicast in job 16.","label":"media.privacyinternational.org:443","timestamp":"2020-07-24T11:14:54.180Z"}
{"level":"info","message":"Actor https://media.privacyinternational.org/accounts/privacyint is followed by actor https://mastodon.xyz/users/privacyint.","label":"media.privacyinternational.org:443","timestamp":"2020-07-24T11:14:54.198Z"}
{"level":"info","message":"Notifying user privacyint of new follower: Privacy International.","label":"media.privacyinternational.org:443","timestamp":"2020-07-24T11:14:54.208Z"}
{"level":"info","message":"Updating 1 good actor follows and 0 bad actor follows scores in cache.","label":"media.privacyinternational.org:443","timestamp":"2020-07-24T11:14:54.280Z"}
{"message":"192.168.0.6 - - [24/Jul/2020:11:14:56 +0000] \"HEAD /videos/overview HTTP/1.0\" 200 3933 \"https://media.privacyinternational.org\" \"Mozilla/5.0+(compatible; UptimeRobot/2.0; http://www.uptimerobot.com/)\"\n","level":"info","label":"media.privacyinternational.org:443","timestamp":"2020-07-24T11:14:56.006Z"}```

**Comment by Chocobozzz** [comment]
Hello,

It seems there is an issue somewhere on `media.privacyinternational.org` because I can't ping your instance from `framapiaf.org`.

On another mastodon instance, I was able to follow `privacyint@media.privacyinternational.org`

![screen_2020-07-31-14:48:52](https://user-images.githubusercontent.com/5180488/89036448-ffb87a80-d33c-11ea-9f2c-d581eb70d5e0.png)

**Comment by EBendinelli** [comment]
Thanks for your response. Our instance was blocking ping and other ICMP by default. 

We've allowed that and it seems to have fixed the issue. 
Added: `Ping(ACCEPT) all all` to our shorewall rules if that helps anyone else.
