### ISSUE TITLE
I cannot see users Channels/Videos/About

### ISSUE THREAD

**Issue by alejandrocobo** [Chocobozzz/PeerTube#3006]
**What happened?**
I created a new instance but I am unable to check the users information.

**What do you expect to happen instead?**
When clicking on a username, I would expect to see user's activity like [this](https://video.hardlimit.com/accounts/herlock_sholmes/video-channels). Instead of that, I get [nothing](https://tubedu.org/accounts/alejandrocobo/video-channels)

**Steps to reproduce:**

1. Go to tubedu.org.

2. Click on any user like [this one](https://tubedu.org/accounts/alejandrocobo/video-channels).

3. There is no information

**Additional information**
* PeerTube version or URL: 2.3.0
* Browser name/version: Firefox 68.10 and Chromium 81
* Web server: Apache 2.4.25 using [this config file](https://gist.github.com/rigelk/07a0b8963fa4fc1ad756374c28479bc7).

Thanks.

**Comment by Chocobozzz** [comment]
Hello,

I'm not sure to understand. I can see the user on https://tubedu.org/accounts/alejandrocobo/video-channels
![screen_2020-07-27-08:35:37](https://user-images.githubusercontent.com/5180488/88510874-2d6f8d80-cfe4-11ea-8b32-373f9e4fe3f2.png)

**Comment by alejandrocobo** [comment]
That's so weird. I've change the language and it turns out that in English it works fine. I can reproduce the issue when I set the interface language to Spanish.

**Comment by Chocobozzz** [comment]
Thanks. I fixed and pulled translations. Should be fixed in develop
