### ISSUE TITLE
Repeated page refreshes alternate between the instance-default theme and the peertube-default theme 

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#3007]
**What happened?**
Issue #2893 does not seem to be properly resolved in v2.3.0. On my instance at https://tube.tardis.world, I have the bittube-dark theme applied as instance default.

When I visit the landing page, the proper instance-default theme displays. If I refresh the page, the peertube-default theme displays. If I refresh the page again, the instance-default theme displays.

Each time I refresh the page, there is an alternation between the instance-default theme and the peertube default theme.

**What do you expect to happen instead?**
The instance-default theme should always be displayed, even if I refresh the page repeatedly

**Steps to reproduce:**

1. Visit https://tube.tardis.world. On initial load, the instance-default theme displays.

2.Refresh the page with <F5> and the peertube-default theme displays.

3.Refresh the page again, and the instance-default theme displays

4. Repeated refreshes alternate between the instance-default theme and the peertube-default theme.

**Additional information**
* PeerTube version or URL:: Peertube v2.3.0 on https://tube.tardis.world
* Browser name/version: Chrome or Firefox (latest versions available on Ubuntu 20.04)
* NodeJS version: default version installed by Peertube v2.2.0 and as upgraded by Peertube v2.3.0

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by test2a** [comment]
confirmed on my side visiting the given url.

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/7c87bce4715ca291c8e449d9de3d92c69725d45c

**Comment by DalekDave** [comment]
Thank you for implementing the fix. But it won't be available to me until the next release.

To help me solve the problem now, please could you tell me how to make the edits manually in my Peertube instance, installed from source and living in /var/www/peertube ?

Or else how can I fix the problem now?

Thank you for your work on Peertube, and wishing you all the best.

**Comment by Chocobozzz** [comment]
@DalekDave Use git and cherry pick the commit: https://docs.joinpeertube.org/#/install-unofficial
