### ISSUE TITLE
Allow custom categories

### ISSUE THREAD

**Issue by ZeroAurora** [Chocobozzz/PeerTube#3009]
**What I want**
In PeerTube's instance list, the instances are grouped by some categories like music, films, gaming and so on. And in PeerTube, videos are grouped by these categories as well.
But I found in my situation, these categories are *not enough* or *too many*. For example, the "anime" category is lacked for those instances dedicated to ACG culture. And the "activism" category is not needed by some instances.
Is there any possibilities that admins choose to add or hide some categories, according to the need of their instances? If not, can this be realized by using some plugins?
Thank you!

**Additional information**
* PeerTube version or URL: develop branch at a949f67

**Comment by rigelk** [comment]
hi @ZeroAurora,

This is already possible via plugins: https://docs.joinpeertube.org/#/api-plugins?id=video-categories-manager-api

**Comment by ZeroAurora** [comment]
Hi,
As you might notice before. I created another issue to ask something about translation (now closed). I'm actually working on a plugin to modify the categories in my (future) PeerTube instance. Yes the video categories manager API works pretty well! But when I tried to translate the categories, problems appeared. I tried to use `peertubeHelpers.translate` in server's plugin file and now I realized I did a wrong thing. But I didn't find an client API to translate words in the UI, only to find a `peertubeHelpers.translate` to translate certain string and return it.
In a word, I want to add some custom categories into my instance and give them translations. What should I do to achieve this goal?
Thank you.

**Comment by rigelk** [comment]
@ZeroAurora unless I missed something, it is not possible to add categories with their translation at the same time - categories are but mere fixed values.

However, within your plugin you could always find and replace these values in the whole interface, at the cost of finding the proper selectors. It is tedious but the only way I see at the moment.

**Comment by ZeroAurora** [comment]
Thank you for replying! 😺 However, I would appreciate it if there is a more "official" way to do that. (For example, a configuration?)

**Comment by AnonymousWebHacker** [comment]
I was looking to do something like that, add custom categories. I see that this has not been worked on
