### ISSUE TITLE
command failed : cd ./peertube-latest && sudo -H -u peertube yarn install --production --pure-lockfile

### ISSUE THREAD

**Issue by Tekprog-fr** [Chocobozzz/PeerTube#301]
* **PeerTube version or commit: peertube-v0.0.24-alpha**
* **NodeJS version: node -v v8.9.4**
* **PostgreSQL version: psql (PostgreSQL) 9.4.15**
* **yarn install v1.3.2**
* **System Linux 3.16.0-5-686-pae**

* **What is the expected behaviour?**
command runs successfully  : cd ./peertube-latest && sudo -H -u peertube yarn install --production --pure-lockfile

* **What do you see instead?**
error /var/www/peertube/versions/peertube-v0.0.24-alpha/node_modules/sharp: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /var/www/peertube/versions/peertube-v0.0.24-alpha/node_modules/sharp
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | linux | ia32
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/var/www/peertube/versions/peertube-v0.0.24-alpha/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/peertube/.node-gyp/8.9.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/peertube/.node-gyp/8.9.4',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/peertube/.node-gyp/8.9.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/var/www/peertube/versions/peertube-v0.0.24-alpha/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
sharp: Intel Architecture 32-bit systems require manual installation of libvips >= 8.6.1 - please see http://sharp.pixelplumbing.com/page/install
gyp: Call to 'node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.16.0-5-686-pae
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/peertube/versions/peertube-v0.0.24-alpha/node_modules/sharp
gyp ERR! node -v v8.9.4

**Comment by Chocobozzz** [comment]
See the error message: "Intel Architecture 32-bit systems require manual installation of libvips >= 8.6.1 - please see http://sharp.pixelplumbing.com/page/install"

Did you try to install libvips >= 8.6.1?

**Comment by Tekprog-fr** [comment]
I try but doesn't work, maybe I need to take more time. Otherwise I will replace my system with debian 64-bit llke that there will be no problem I think :)

**Comment by Chocobozzz** [comment]
Anyway it seems to be related to [sharp](https://github.com/lovell/sharp) module, maybe you could ask help over there?

**Comment by omgbox** [comment]
if you see this Command: node-gyp rebuild

try this

> npm config set user 0

> npm config set unsafe-perm true

node-gyp should be avoided at all costs its extremely problematic

**Comment by Chocobozzz** [comment]
@omgbox I'm sorry but I don't think it's a good idea to set globally not safe options, more importantly without explanations. Moreover this does not seem to be a user rights issue, but a dependency issue of a native module (sharp).

I'm closing this since this is not really a PeerTube issue. Feel free to comment if you disagree.
