### ISSUE TITLE
Play/pause shortcut stop working when click is used

### ISSUE THREAD

**Issue by SansPseudoFix** [Chocobozzz/PeerTube#3013]
**What happened?**
When you click on a video to watch it and want to pause with spacebar: it doesn't work (i.e.: icon turns pause and back play and the video does not change from a state to another).
However, if you don't use click and only spacebar, it works fine.

**What do you expect to happen instead?**
Using click and spacebar to play/pause.

**Steps to reproduce:**

1. watch a video

2. click on to pause

3. use spacebar to resume (not working)

**Additional information**
* PeerTube version or URL: https://framatube.org/
* Browser name/version: Firefox 68.10.0esr , 78.0.2 and 81.0a1.

**Comment by Chocobozzz** [comment]
First part of the patch: https://github.com/Chocobozzz/PeerTube/commit/e85bfe96fd32e4f1c7ad872448e67f59ca03d020

Need the videojs-hotkeys merge now.

**Comment by Chocobozzz** [comment]
Merged and updated in https://github.com/Chocobozzz/PeerTube/commit/7a09c3007a0b0ce317ca0c76948ca9c4712933dc
