### ISSUE TITLE
video privacy text mismatch

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3015]
**What happened?**
screenshots of "upload" first page. it shows in the privacy, 
 1. public
 2. unlisted
 3. private
 4. internal
 5. scheduled

**Further, "scheduled" option is NOT available in import url or torrent import.** 

Once a video has been uploaded or imported, the "edit a video" page shows the same privacy but now the text has changed, 
it says
1. only i can see this video
2. only people with a private link can see this video
3. anyone can see this video
4. only users of this instance can see this video

![111](https://user-images.githubusercontent.com/39449563/88693711-3c0d9000-d11d-11ea-8e7c-eaac244eee66.png)
![222](https://user-images.githubusercontent.com/39449563/88693718-3dd75380-d11d-11ea-8efc-63b471716215.png)

**What do you expect to happen instead?**
make the language clear about the privacy. I have not checked the upload on any more updated instance because i havent found one which would let me upload. close the issue if its been fixed in future versions

**Additional information**
* PeerTube version or URL:https://devtube.dev-wiki.de 

PeerTube version | 2.1.1
-- | --

**Comment by Chocobozzz** [comment]
Ideally we would put the short labels in the select, with a small description below every `<option>` it but I don't know if it's feasible
