### ISSUE TITLE
Disable PeertubeLink in Embed-player

### ISSUE THREAD

**Issue by kantegory** [Chocobozzz/PeerTube#3016]
**What happened?**
I want to disable PeertubeLink in the embed player. I found information about url-param peertubeLink here:: https://github.com/Chocobozzz/PeerTube/blob/2291a412d25bd139398ca9e7a5131d0c1e4ffd7d/CHANGELOG.md#features-5. But this param doesn't work (or I didn't get how it works).

.**What do you expect to happen instead?**
I want just delete PeertubeLink. Using this code sample:

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Peertube embed API</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
</head>
<body>
	<main>
		<iframe id="embed" width="560" height="315" sandbox="allow-same-origin allow-scripts allow-popups" src="https://<videolink>?api=1&peertubeLink=0" frameborder="0" allowfullscreen></iframe>

	</main>
	<script type="text/javascript" src="dist/app.js"></script>
</body>
</html>

```
But it doesn't give me any effect.

**Additional information**
* PeerTube version or URL:
* Browser name/version:  Firefox/78.0
* NodeJS version: v10.18.0

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/08d9ba0f855bcd254151c1000a2a4008a1816ad6
