### ISSUE TITLE
Helm Chart is missing for kubernetes deployment

### ISSUE THREAD

**Issue by abdennour** [Chocobozzz/PeerTube#3017]
**What happened?**

I search on the whole repository about Kubernetes, but I found nothing.

**What do you expect to happen instead?**

I expect to find the Helm chart of this application or at least YAML files

**Steps to reproduce:**

1. Go to https://github.com/Chocobozzz/PeerTube

2. In the Search input, write "kubernetes" and search on the current repo.

3. Inspect the search results

**Additional information**
- Will send PR with the helm chart.. but what is your preference as directory hierarchy :  `charts` dir, `deploy` dir , `.devops/chart` dir ,...  ?

**Comment by rigelk** [comment]
We do not plan to maintain an helm chart. Instead, we prefer to link to third party deployment options from our documentation, where you could add a link to your repository as an additional third party option.
