### ISSUE TITLE
Adding translation of subtitles into Russian

### ISSUE THREAD

**Issue by JustErbe** [Chocobozzz/PeerTube#3018]
**What happened?**
Hello. I would like to be able to watch videos with subtitles translated into Russian. I hope this doesn't bother you too much, but many people who don't understand English well will be happy about it. My friends are a little worried about this and I decided to write to you, I am sure that you can do it. Your project is wonderful!
**What do you expect to happen instead?**
Nothing.
**Steps to reproduce:**

1. -

2. -

3. -

**Additional information**
* PeerTube version or URL:
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by rigelk** [comment]
hi @JustErbe,

Unless your request concerns videos on a server administered by the project (peertube1.cpy.re, peertube2.cpy.re, peertube3.cpy.re), I suggest you get in touch with the video author or instance admin of the videos you wish to have subtitles in russian for, as this issue tracker can only act on the software behind the instance hosting the videos, not its subtitles' content.

But maybe I misunderstood - is it related to something dependent on software improvement?

**Comment by JustErbe** [comment]
hi @rigelk and  thank you very much for your answer! 
I meant to add translation functionality, that is, for example, YouTube makes it possible, for example, by including English subtitles, to translate them into a convenient language. I meant this functionality, where I will put English subtitles and then click on the "Translate" function and I will be able to select the desired language. Maybe I'm wrong and this functionality is not up to you, but if you can help, my colleagues and my family will be very happy. I introduced all my relatives and friends to your project and we really do not have enough of this functionality.

**Comment by Chocobozzz** [comment]
Hello,

We don't have an automatic translation tool to english subtitles like youtube has. But uploaders (video owners) can upload subtitles on their videos. If you want to translate a specific video, you could try to contact the uploader using video comments for example.

There is also [this issue](https://github.com/Chocobozzz/PeerTube/issues/1481) that talks about subtitles edition on the PeerTube interface.
