### ISSUE TITLE
Different subscription icons in my-account since last changes

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#3020]
Since https://github.com/Chocobozzz/PeerTube/pull/2977/files some icons has been updated like the subscription icon to be common with the one in the left menu :

![image](https://user-images.githubusercontent.com/1877318/88801990-bd5f3400-d1aa-11ea-997c-ea17048caeb9.png)
![image](https://user-images.githubusercontent.com/1877318/88802046-d23bc780-d1aa-11ea-96aa-d7dcafec79dc.png)

And since the general user-menu effects on this PR : https://github.com/Chocobozzz/PeerTube/pull/2971, this icon has also been used on sub-titles.

![image](https://user-images.githubusercontent.com/1877318/88802265-1c24ad80-d1ab-11ea-85b6-2ebc96109260.png)

At last, since this last commit https://github.com/kimsible/PeerTube/commit/aa91835898a80e4ea142fc27b40327d8c4461686 on this PR https://github.com/Chocobozzz/PeerTube/pull/2966 about the limitation of upload form and user menus, a small refacto has been made on the user sub-menu and re-injected the old icon : 

![image](https://user-images.githubusercontent.com/1877318/88801684-52adf880-d1aa-11ea-9afe-924df5625230.png)

Anyway what icon is used, the same ones on sub-titles and sub-menu should be used.

**Comment by rigelk** [comment]
fixed by #3031.
