### ISSUE TITLE
Root user cant login if password initialized with PT_INITIAL_ROOT_PASSWORD

### ISSUE THREAD

**Issue by davidlemaitre** [Chocobozzz/PeerTube#3021]
I initialized the password for root user with PT_INITIAL_ROOT_PASSWORD environment variable in the .env file :

`PT_INITIAL_ROOT_PASSWORD=testpassword`

After starting app, I can't login with root user, this error message appears `Invalid client: client is invalid `. The app logs show PeerTube use correctly the initial password :

> info: Username: root
info: User password: testpassword

Using PeerTube 2.3.0 (v2.3.0-buster Docker image)

**Comment by Chocobozzz** [comment]
What is your instance URL?

**Comment by davidlemaitre** [comment]
The instance URL is peertube.something.localhost, mounted locally, not available online.

**Comment by Chocobozzz** [comment]
What is the values of env variables `PEERTUBE_WEBSERVER_HOSTNAME` `PEERTUBE_WEBSERVER_PORT` and `PEERTUBE_WEBSERVER_HTTPS`?

**Comment by borekon** [comment]
Same here, but no .env file (not using docker).
Changed password with 
`sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run reset-password -- -u root`

**Comment by Chocobozzz** [comment]
@borekon Please create a dedicated issue and fill the template

**Comment by borekon** [comment]
I moved to docker, then restarted and now it's working like a charm

**Comment by davidlemaitre** [comment]
@Chocobozzz I tested again and the error `Invalid client: client is invalid` has now gone and I can login with the initial password ! I didn't change the Docker configuration in the meantime. I can't reproduce the problem after changing initial root password in the .env file and recreating containers and volumes. 

The values for the webserver env variables  :
PEERTUBE_WEBSERVER_HOSTNAME=peertube.something.localhost
PEERTUBE_WEBSERVER_PORT=443
PEERTUBE_WEBSERVER_HTTPS=true
