### ISSUE TITLE
Thumbnail aspect ratio does not match video aspect

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#3027]
**What happened?**

Video thumbnails seem to all be hardcoded to 16:9, vertical videos appear stretched:

![image](https://user-images.githubusercontent.com/923812/89110361-d102d880-d3fe-11ea-8631-b67fdf1664ab.png)

**What do you expect to happen instead?**

The thumbnail should occupy the same outer container as other thumbnails but the image itself should be sized to maintain aspect ratio.

**Steps to reproduce:**

1. Currently you can see this on https://diode.zone/videos/recently-added

**Additional information**
* PeerTube version or URL: 2.2.0
* Browser name/version: Chrome 84
* NodeJS version: 10.20.1

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by JigmeDatse** [comment]
Yeah, I noticed this when I uploaded some videos which are 9:16 aspect ratio 1080 by 1920 from the iPad...

**Comment by Chocobozzz** [comment]
What's the best way to handle these videos? Should we use black columns or zoom in the image? 
![3a250ae3-068b-4680-a8e4-64a2e30de3e2](https://user-images.githubusercontent.com/5180488/89195171-a3599300-d5a8-11ea-8d0c-4a8ce09e7311.jpg)

**Comment by scanlime** [comment]
> What's the best way to handle these videos? Should we use black columns or zoom in the image?
> ![3a250ae3-068b-4680-a8e4-64a2e30de3e2](https://user-images.githubusercontent.com/5180488/89195171-a3599300-d5a8-11ea-8d0c-4a8ce09e7311.jpg)

I would think neither... could this be handled in the CSS such that the actual page background shows through and the thumbnail is smaller yet fitting in the same bounding box as the 16:9 thumbnails. Zooming would almost always make the thumbnail unreadable i would think, and black bars seem unnecessary.

**Comment by JigmeDatse** [comment]
I feel if it could be handled that the image is just displayed within the 16:9 bounding box without affecting the aspect ratio would be best.  This could result in some rather small thumbnails, but I'd rather that, and manually setting a thumbnail, than adding black bars (to the image), or cropping.

**Comment by chengjingfeng** [comment]
use black columns is acceptable

**Comment by tomtoom1978** [comment]
When upload a video with a ratio 2.39,inside the download area (torrent/direct) we can see a **real ratio**, but not friendly as
--> (rapport de forme 2,39:1 is better)
![rapportdeforme2391](https://user-images.githubusercontent.com/36678395/116375379-825c6080-a80f-11eb-964a-901db4652a64.jpg)

**Comment by ppnplus** [comment]
I think either putting black bars or including the scaled, darkened (and/or blurred) version of the thumbnail behind it (like YouTube thumbnails or what many TV stations do when airing non-16:9 footages) would be OK for me. Only scaling it could discard some important content.

**Comment by alexandre-k** [comment]
Hello,
I got the same issue discussed here after customizing a thumbnail.
In my opinion, resizing the image and keeping its aspect ratio would be better done with black bars. Eventually if this is matter of debate, keeping the aspect ratio and zoom in or out could be left to the choice of the user. Like by default resize by zooming out to fit the thumbnail size and if the user wants it, resize to cover the thumbnail. In my opinion people would be disappointed to feed an image and find it cropped with a zoom in.

**Comment by Altonss** [comment]
Same issue here: https://share.tube/videos/watch/52425747-68df-4315-95e1-f54fc839dbc9
@Chocobozzz Isn't this issue considered as a bug? The scaling is really ugly...

**Comment by Chocobozzz** [comment]
I changed the thumbnail/preview generation behaviour in https://github.com/Chocobozzz/PeerTube/commit/7196a70b28e93ede11ccbfef7f1bc919c663b964

![screen_2021-11-16-16:00:26](https://user-images.githubusercontent.com/5180488/142010375-46a163aa-6280-4c1c-b14d-24e2528768e5.png)

**Comment by Altonss** [comment]
That's great, thank you very much!

**Comment by SnejPro** [comment]
> I changed the thumbnail/preview generation behaviour in [7196a70](https://github.com/Chocobozzz/PeerTube/commit/7196a70b28e93ede11ccbfef7f1bc919c663b964)
> 
> ![screen_2021-11-16-16:00:26](https://user-images.githubusercontent.com/5180488/142010375-46a163aa-6280-4c1c-b14d-24e2528768e5.png)

Is this still working? My thumbnails are cut off. I'd like to embed 1:1 Videos with a 1:1 Thumbnail on my Website.

**Comment by Chocobozzz** [comment]
@SnejPro Can you paste the current result you have, and the result you would want?

**Comment by SnejPro** [comment]
> @SnejPro Can you paste the current result you have, and the result you would want?

This is how it could look like: https://cdn.snejp.de/example_peertube/
Everything is done using CSS. So the image has to be loaded only once from the server.

**Comment by SnejPro** [comment]
> @SnejPro Can you paste the current result you have, and the result you would want?

The current thumbnail generation behaviour does not work for me because my thumbnails are 1:1, i think.
