### ISSUE TITLE
AdNauseam blocks the Subscribe button from showing

### ISSUE THREAD

**Issue by kozross** [Chocobozzz/PeerTube#3029]
**What happened?**

When I navigated to a video page with AdNauseam enabled, I could not see the 'Subscribe' button anywhere. Disabling AdNauseam made it visible again. Even more strangely, the 'Unsubscribe' button is visible with AdNauseam enabled.

**What do you expect to happen instead?**

That the 'Subscribe' button is visible for me to click on.

**Steps to reproduce:**

1. Go to [this video](https://diode.zone/videos/watch/playlist/7049a134-c967-450e-b07c-86ab1b9a8ffb?videoId=02d8d5ad-aaad-458a-bfe6-a69ffb1b048e&resume=true) with AdNauseam enabled.

2. Look for a 'Subscribe' button.

3. Fail to find it anywhere.

4. Lament.

**Additional information**
* PeerTube version or URL: https://diode.zone
* Browser name/version: Firefox 79.0
* NodeJS version: 10.20.1

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by kozross** [comment]
Turns out this was [a problem with a filter][1] provided by AdNauseam. Closing.

[1]: https://github.com/dhowe/AdNauseam/issues/1706#issuecomment-667728640

**Comment by rigelk** [comment]
Turns out this happened with https://github.com/Chocobozzz/PeerTube/issues/1866 and https://github.com/Chocobozzz/PeerTube/issues/1866, which already identified the Fanboy's Annoyance list as the culprit.
