### ISSUE TITLE
peertube custom title size

### ISSUE THREAD

**Issue by ReK2Fernandez** [Chocobozzz/PeerTube#303]
When setting up the peertube server name - if longer than 2 words it creates new lines in the CSS(I think) so looks bad, instead it should just span to one line unless it actually classes with the right side tittles(that is actually the search box)...

**Comment by Chocobozzz** [comment]
Fixed: https://github.com/Chocobozzz/PeerTube/commit/8a44f8354e614ee24f4b749c4e1a3cf1fde2b4d4

Thanks for the report @ReK2Fernandez. If you see other CSS bugs do not hesitate.
