### ISSUE TITLE
Video stalls when redundancy peers are slow

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#3033]
**What happened?**

I'm still having trouble with videos on my instance getting *less* reliable rather than more reliable when they get popular, because of hosts offering redundancy but not fast or reliable hosting.

**What do you expect to happen instead?**

When a single host is taking excessively long to respond, I expect the client to remove that host (temporarily?) from the rotation and rely on the other hosts. I expect this to happen soon enough that the video buffer does not stall.

**Steps to reproduce:**

I don't have a sample video for this at the moment because I've been deleting the slow redundancies when I notice them.  The last video I noticed this on was hosted on diode.zone with redundancy provided by peertube.social.

1. Host a video, enable redundancy

2. Wait for some slow hosts to mirror your video

3. Notice it freezing on playback

4. Repeat under browser network inspector, notice the delays appearing on specific servers but not in general.

**Additional information**
* PeerTube version or URL:  2.2.0
* Browser name/version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/2047
