### ISSUE TITLE
Error HTTP 502

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#3042]
**What happened?**
HTTP 502 error
**What do you expect to happen instead?**
An usable app
**Steps to reproduce:**

1. Install the app

2. Try to launch it

**Additional information**
* PeerTube version or URL: 2.3
* NodeJS version: 10.21.0~dfsg-1~deb10u

* Link to browser console log if useful:
* Link to server log if useful : https://zerobin.stemy.me/?12e0461da7ca11a1#G9j1SibYZKj4Hf7uDopCo81BdcLVqHPfF8uxGrjoSWZN

**Comment by Chocobozzz** [comment]
Disable SMTP or fix it: 

```
Aug 07 09:45:29 stemy.me peertube[7079]: [peertube.stemy.me:443] 2020-08-07 09:45:29.149 error: Failed to connect to SMTP localhost:25. {
Aug 07 09:45:29 stemy.me peertube[7079]:   "err": {
Aug 07 09:45:29 stemy.me peertube[7079]:     "stack": "Error: queryA ETIMEOUT localhost\n    at QueryReqWrap.onresolve [as oncomplete] (dns.js:203:19)",
Aug 07 09:45:29 stemy.me peertube[7079]:     "message": "queryA ETIMEOUT localhost",
Aug 07 09:45:29 stemy.me peertube[7079]:     "errno": "ETIMEOUT",
Aug 07 09:45:29 stemy.me peertube[7079]:     "code": "EDNS",
Aug 07 09:45:29 stemy.me peertube[7079]:     "syscall": "queryA",
Aug 07 09:45:29 stemy.me peertube[7079]:     "hostname": "localhost",
Aug 07 09:45:29 stemy.me peertube[7079]:     "command": "CONN"
Aug 07 09:45:29 stemy.me peertube[7079]:   }
Aug 07 09:45:29 stemy.me peertube[7079]: }
```

**Comment by rigelk** [comment]
You need a reachable SMTP server in production.

**Comment by stemy2** [comment]
Do you know how to solve it (disabling is out of question for some reason) ? Because i don't.
