### ISSUE TITLE
Can't search for new plugins/themes

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#3044]
**What happened?**
I tried to install new plugins and theme, but the result is an error message saying `the plugin list doesn't exist, please try again later`. According the web console, this is a HTTP 503 error.
**What do you expect to happen instead?**
The plugins/themes list appearing.
**Steps to reproduce:**

1. Go to Administration > Plugins/themes > Search

**Additional information**
* PeerTube version or URL: 2.3.0
* Browser name/version: Firefox 68
* NodeJS version: 10.21.0~dfsg-1~deb10u1

**Comment by Chocobozzz** [comment]
Please retry, there were some bugs in the NPM registry.
