### ISSUE TITLE
Being able to add subtitles in kabyle language.

### ISSUE THREAD

**Issue by SelyanKab** [Chocobozzz/PeerTube#3045]
I would like to add subtitles kabyle languuage, iso code: kab, native name: Taqbaylit.
note: Peertube is available in Kabyle since version 2.3 and we are still working on localization.

**Comment by Chocobozzz** [comment]
Thanks for your contribution. 

Added in supported video languages in https://github.com/Chocobozzz/PeerTube/commit/07c01b3154da61b621a3308f35468a8db4a29f8e
