### ISSUE TITLE
userAuthenticated does not allow to override role

### ISSUE THREAD

**Issue by BLeQuerrec** [Chocobozzz/PeerTube#3051]
**What happened?**

I'm using the [peertube-plugin-auth-openid-connect](https://framagit.org/framasoft/peertube/official-plugins/-/tree/master/peertube-plugin-auth-openid-connect) to manage OIDC authentication with Keycloak. Plugin is configured to get role from a special token result. Role can be 0, 1 or 2.

On first login (ie. user does not exist in the Peertube's DB), the role is set from the token result. If I set a role to 0, the newly created user is an Admin on Peertube. But then, if the user logs in again (ie. the user now exists in the Peertube's DB), role is ignore: if Keycloak returns a value of 2 (User), the user is still an Admin. I can only change the role from the Peertube admin interface.

It is not a bug in the peertube-plugin-auth-openid-connect plugin: the new role is correct and passed to the [`userAuthenticated`](https://framagit.org/framasoft/peertube/official-plugins/-/blob/0cbf9a69f179dd46edfc97cd24cb875824f4d3cc/peertube-plugin-auth-openid-connect/main.js#L253-260) function. I assume the issue is in Peertube itself.

**What do you expect to happen instead?**

Role should be updated according the the value passed in `userAuthenticated` on each login.

**Steps to reproduce:**

1. Use `userAuthenticated` to log in with a new user: role is correct.
2. Use the same `userAuthenticated` to log in with the same user but with a different role: role is not updated.

**Additional information**
* PeerTube version or URL: 2.3.0 with only the peertube-plugin-auth-openid-connect plugin
* Browser name/version: not relevant (but Firefox if needed)
* NodeJS version: v12.18.3 (from nodesource)

PS: thank you for making Peertube so great! <3

**Comment by rigelk** [comment]
Please open this issue on the plugin's respective issue tracker.

**Comment by BLeQuerrec** [comment]
As I said, @rigelk, it is not an issue with the plugin but with the Peertube `userAuthenticated` API.

**Comment by Chocobozzz** [comment]
Hello,

I'm not sure we want to let admins think we can synchronize user attributes (like the role) after user creation. Because we can't: after login, the user has its access/refresh token that are internal to PeerTube, and so PeerTube won't make keycloak calls before their expiration. The consequence is that admins may think that if they remove the admin role to a particular user in keycloak, the peertube instance will instantly change the user role. But it won't, so it's kinda dangerous.

We could add a sync system with auth providers, but it would require more work.

**Comment by BLeQuerrec** [comment]
If the roles change, OpenID tokens should be revoked, so the user will have to log in again, thus syncing his/her new roles with Peertube. Peertube doesn't have to check if tokens are still valid, plugins should.

Is an option like `overrideRoles` (default to `false`) acceptable? This will not break the current API but will allow plugins to comply with expected behaviour for OpenID.

**Comment by Chocobozzz** [comment]
The `userAuthenticated` plugin API now supports the `role` attribute

https://docs.joinpeertube.org/contribute/plugins#add-external-auth-methods

Regarding my previous message, things have changed:
 * Admins can customize peertube access/refresh token lifetimes
 * You can specify a `userUpdater` function in `userAuthenticated` to update peertube user on external login
 * You also have the possibility to specify a `hookTokenValidity` to validate peertube tokens against your external auth provider
