### ISSUE TITLE
Videos won't load and Playback is slow

### ISSUE THREAD

**Issue by austin3410** [Chocobozzz/PeerTube#3053]
**What happened?**
None of my videos will play. They will just load or buffer forever. Thumbnails generate fine, I can download videos fine as well but whatever I do, I can't play the videos from the webpage.

**What do you expect to happen instead?**
I expected the video to play.

**Steps to reproduce:**

1. Doesn't matter how I try to play a video, it always buffers.

**Additional information**
* PeerTube version or URL: https://peertube.hohe.space
* Browser name/version: Google Chrome 84.0.4147.105
* NodeJS version: v12.18.3

* Server Log:
[peertube.log](https://github.com/Chocobozzz/PeerTube/files/5048209/peertube.log)
[peertube-audit.log](https://github.com/Chocobozzz/PeerTube/files/5048211/peertube-audit.log)

* Additional Notes:
My setup isn't completely default, I already had an Nginx reverse proxy on my network so the PeerTube traffic needs to flow through that. I can provide my current configs if needed but basically I'm using the default Nginx config that was provided with PeerTube on the PeerTube server just with all the SSL stuff commented out since I'm only applying SSL from my edge proxy. Then I'm using a super basic config on the edge proxy to just apply an SSL cert and then forward the traffic to PeerTubes Nginx. If this is a problem please let me know.

**Comment by rigelk** [comment]
There are errors regarding your HLS manifest not downloading properly - could you provide the relevant parts of your Nginx configuration?

**Comment by austin3410** [comment]
* Nginx config from the PeerTube Server
[peertube.txt](https://github.com/Chocobozzz/PeerTube/files/5048416/peertube.txt)

* Nginx config from my edge Nginx Server
[nginx_peertube_config.txt](https://github.com/Chocobozzz/PeerTube/files/5048417/nginx_peertube_config.txt)

**Comment by Chocobozzz** [comment]
Try to remove `location ~ ^/static/(webseed|redundancy|streaming-playlists)/ {` section

**Comment by austin3410** [comment]
After altering the config to this:
[peertube_without_location.txt](https://github.com/Chocobozzz/PeerTube/files/5051660/peertube_without_location.txt)

It didn't seem to change anything. I even tried uploading a new video but that won't play either:
https://peertube.hohe.space/videos/watch/5117743f-b88c-43cb-9aaa-bd38d5ede3bb

Thanks for the help so far.

**Comment by austin3410** [comment]
Alright so good news, I fixed my issues with video not being able to play at all! In the "production.yml" file. I had HTTPS set to false and the port set to 80 since it was going to be behind a reverse proxy anyway. I set those back to the default values (HTTPS set to true and port set to 443), I then set the hostname value under "listen" to the local IP instead of localhost and videos started to play!! I guess I overlooked that one. However now I'm running into a different problem...

My 1440p video playback performance is abysmal! What's weird is that my 1080p video get transferred at around 1MB/s. Where as my 1440p vids are usaully stuck between 200-300 kbps. Because of this you get about 1 second of video every 10 seconds or so. The rest of the time its just buffering. I upload speed is 40mbps through Charter which I would think is enough considering I stream my gameplay at full resolution to YouTube no problem. 

Another interesting thing I've found is that all of my video only have an option to play them back at native resolution. I thought, like YouTube, I would be able to select different resolutions and PeerTube would be able to downscale on the fly. Is this an incorrect assumption?

Again thanks for the help so far.

**Comment by Chocobozzz** [comment]
What is your ffmpeg version?

**Comment by austin3410** [comment]
ffmpeg version 3.4.8-0ubuntu0.2

**Comment by Chocobozzz** [comment]
You need ffmpeg >= 4.1 to enable HLS: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L250 (you'll have to reupload your videos)
