### ISSUE TITLE
Certbot and nginx issue on installation

### ISSUE THREAD

**Issue by quentinDupont** [Chocobozzz/PeerTube#3060]
**What happened?**
Following official tutorial and got stuck at generating and handling certificate with certbot

**What do you expect to happen instead?**
Restating nginx with success after certbot 

**Steps to reproduce:**

$ sudo systemctl stop nginx
$ sudo vim /etc/nginx/sites-available/peertube # Comment ssl_certificate and ssl_certificate_key lines
$ sudo certbot --authenticator standalone --installer nginx --post-hook "systemctl start nginx"

**Additional information**
* PeerTube version or URL: 2.3.0
* OS version: Ubuntu 20.04

First issue was

```
nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /etc/nginx/sites-enabled/peertube:16
nginx: configuration file /etc/nginx/nginx.conf test failed
```
I d'ont really understand because not having ssl_certificate is the goal of commenting the line :smiley: 

Then I tried to delete all `server {  listen 443 ssl http2` part in nginx conf and relaunch certbot

It seems to work, just had `Problem binding to port 80: Could not bind to IPv4 or IPv6.`
And when i restart nginx

```
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/MYDOMAIN/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/MYDOMAIN/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed
```

Indeed, I don't have live/ folder in letsencrypt

Thanks for your help :)

**Comment by Chocobozzz** [comment]
nginx was running when you ran the certbot command?

**Comment by quentinDupont** [comment]
> nginx was running when you ran the certbot command?

I've been going back through my commands logs and I seem to have forgotten to do that..

**Comment by quentinDupont** [comment]
But if i stop it and certbot again, I still have the error 

`nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /etc/nginx/sites-enabled/peertube:16
nginx: configuration file /etc/nginx/nginx.conf test failed
`

**Comment by Chocobozzz** [comment]
Try to stop nginx and uncomment `ssl_certificate` and `ssl_certificate_key` lines

**Comment by quentinDupont** [comment]
user@myserver::/etc/nginx$ sudo systemctl stop nginx
user@myserver::/etc/nginx$ sudo nano sites-enabled/peertube 
user@myserver::/etc/nginx$ sudo systemctl start nginx
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
user@myserver::/etc/nginx$ sudo systemctl status nginx
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2020-08-11 10:15:12 CEST; 2s ago
       Docs: man:nginx(8)
    Process: 21274 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)

Aug 11 10:15:12 myserver systemd[1]: Starting A high performance web server and a reverse proxy server...
Aug 11 10:15:12 myserver nginx[21274]: nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/<MYDOMAIN.TLD>/fullchain.pem": BIO_new_file() failed (SSL: erro>
Aug 11 10:15:12 myserver nginx[21274]: nginx: configuration file /etc/nginx/nginx.conf test failed
Aug 11 10:15:12 myserver systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Aug 11 10:15:12 myserver systemd[1]: nginx.service: Failed with result 'exit-code'.
Aug 11 10:15:12 myserver systemd[1]: Failed to start A high performance web server and a reverse proxy server.

**Comment by Chocobozzz** [comment]
Fixed documentation in https://github.com/Chocobozzz/PeerTube/commit/2c92b0634f780b62e26380939fcdc0508f55a1cb
