### ISSUE TITLE
password reset link usable multiple times

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3065]
**What happened?**
i reset my password on an  instance with a reset link. it worked but i tried to use the same link again and it allowed me to change password second and third time.
**What do you expect to happen instead?**
reset link should expire after using once. I don't know if this bug has been fixed in a more recent peertube update as this instance is running 2.1.1 . if this has been fixed at a later date, feel free to close this 
**Steps to reproduce:**

1. create an account at https://devtube.dev-wiki.de

2. reset password using forget password link. 

3. use the link in email to change password.

4. then use the link again. you are able to use the link for the second time.

**Additional information**
* PeerTube version or URL:https://devtube.dev-wiki.de
* PeerTube version | 2.1.1
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by test2a** [comment]
i did see https://github.com/Chocobozzz/PeerTube/pull/2305 but it talks about expiry of the reset link w.r.t time and not usage. i could be wrong though

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/e9c5f123383e461a890c95368dce6f79d3b84660
