### ISSUE TITLE
Muted player on play - iOS / Safari desktop

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#3067]
On Safari desktop or on any iOS browser (iPad for example), the player is set to muted = true when the video starts playing even if local-storage has a different muted value.

![muted-sound-safari-os](https://user-images.githubusercontent.com/1877318/89948331-2ff9f600-dc26-11ea-9281-697b283aed4d.gif)

**Comment by Chocobozzz** [comment]
Do you still have the issue referenced in https://github.com/Chocobozzz/PeerTube/pull/3068#issuecomment-682400441?

**Comment by kimsible** [comment]
@Chocobozzz thanks everything is good ! The only thing that we can see is sometimes when we touch the next button on the player, due to the proximity with the play / pause at the left, the next video may also be paused just after start. But this is another question of player UX/UI optimizations for touch devices =).
