### ISSUE TITLE
Is it possible to hide deleted comments?

### ISSUE THREAD

**Issue by sunknudsen** [Chocobozzz/PeerTube#3069]
Not a huge fan or "This comment has been deleted"... I understand why this might be useful when deleted comments have children, but when they don’t, wouldn’t it be natural to simply hide them?

![Deleted comment](https://user-images.githubusercontent.com/2117655/89955761-3f2b7480-dc23-11ea-821e-62c4c24a4f1b.png)

Btw, thanks for PeerTube! Proud to self-host a sovereign alternative to YouTube.

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/pull/3046 fixes this
