### ISSUE TITLE
Static resource Protection

### ISSUE THREAD

**Issue by icipiqkm** [Chocobozzz/PeerTube#307]
If the bad user wants to attack me, he can see my real video address like Http://www.xxx.com/video.mp4, then he can put this link address to his website, if he wants to maliciously attack you, he can maliciously consume your server's broadband traffic, So I would like to http://www.xxx.com/video.mp4 these resources are protected, only allowed through the torrent or their own website to play video, my English is not very good, do not know I express it? If you don't understand I can add that this is a long-term security issue, the purpose of Peertube is to share, and save costs, if the video resources are not protected, hackers (villains) easily attack you

**Comment by Chocobozzz** [comment]
Hi @icipiqkm,

I understand well but I don't think it would be feasible.

And I don't think it would prevent anybody to steal your bandwidth.
