### ISSUE TITLE
Brave doesn't support PeerTube's RSS

### ISSUE THREAD

**Issue by gwaHja** [Chocobozzz/PeerTube#3076]
What happened? = Rss does not work. My browser says so and I do not get updates. In my rss clint (It's not the clint)

What do you expect to happen instead? = Nothing

**Steps to reproduce:**

1..

2..

3..

**Additional information**
* PeerTube version or URL: tube.privacytools.io
* Browser name/version:Brave(Latest I think)
* NodeJS version: Idk 

* Link to browser console log if useful:NOT my browser
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):No

**Comment by rigelk** [comment]
What is your RSS client?

**Comment by gwaHja** [comment]
> What is your RSS client?
https://en.wikipedia.org/wiki/RSS

**Comment by gwaHja** [comment]
Its in my rss clint

**Comment by gwaHja** [comment]
rigelk change my title
