### ISSUE TITLE
Paywall For Exclusive Content

### ISSUE THREAD

**Issue by trymeouteh** [Chocobozzz/PeerTube#3078]
A cool feature or plugin would be to allow channels to create certain videos and to create certain channels to be behind a paywall which will require a paid subscription to watch paywall videos and to subscribe and watch videos on a paywall channel.

I think the best way to do this is with cryptocurrencies. I do not think Peertube needs to create its own cryptocurrency and should allow payments in popular cryptocurrencies such as Bitcoin, Bitcoin Cash, Dash and Monero.

**Comment by test2a** [comment]
this is not difficult even today. just set a video as unlisted and give out links to anyone who pays you say via liberapay or paypal or whatever. 
i am not sure peertube will ever implement this in the software itself, maybe you or someone else can write a plugin of sorts to do this functionality

**Comment by Chocobozzz** [comment]
Hello,

Thanks for this issue but this monetization system is out of the scope of PeerTube. But you could ask specific features/plugin hooks if you would like to create such plugin.
