### ISSUE TITLE
RSS Feed for user subscriptions

### ISSUE THREAD

**Issue by trymeouteh** [Chocobozzz/PeerTube#3079]
Please allow Peertube accounts to have a RSS feed for their own subscribe channels.

**Comment by rigelk** [comment]
Hi! Please look out for related issues before creating one, as #23 already covers RSS support and even lists various improvements made to the original implementation.

**Comment by rigelk** [comment]
@trymeouteh sorry, I misunderstood your issue at first, thinking it was only about having RSS feeds in general - which PeerTube has since may 2018.

Your issue however called for *subscription feeds*, which I incidentaly am implementing at the moment :slightly_smiling_face:

**Comment by naclander** [comment]
Not sure if this issue should go in a new issue, I see there are several RSS issues opened and I'm not sure how they're all related:

* This one
* https://github.com/Chocobozzz/PeerTube/issues/23
* https://github.com/Chocobozzz/PeerTube/issues/3079

When trying to subscribe to a channel on a peertube instance, I see the "Subscribe via RSS" option, but my RSS feel fails to update when a new video is posted. I believe this is a problem with peertube and was suggested by the peertube instance owner to file a bug upstream.

Example channel: https://spacepub.space/video-channels/sircmpwn/videos
RSS feed for channel ( broken, never updates when new videos are posted ): https://spacepub.space/feeds/videos.xml?videoChannelId=2

Is this problem already covered in a different issue? Should I file a new github  issue for this?

**Comment by rigelk** [comment]
@naclander this issue is a request for a new feed for the list of videos from a user's subscriptions, not an issue with existing feeds like you seem to have. The feed you refer to is empty, so it never updates indeed - please open a new issue.

**Comment by trymeouteh** [comment]
Has this feature been implemented into Peertube?

**Comment by rigelk** [comment]
Yes

**Comment by trymeouteh** [comment]
This is what is copied when I click on the RSS button in my subscriptions feed

/feeds/subscriptions.xml?accountId=12345&token=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

it is missing the website domain at the front and should look like this.

libre.video/feeds/subscriptions.xml?accountId=12345&token=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

**Comment by rigelk** [comment]
@trymeouteh please open an issue
