### ISSUE TITLE
[Suggestion] Video Advertisements

### ISSUE THREAD

**Issue by trymeouteh** [Chocobozzz/PeerTube#3080]
Peertube can create its own advertisement network for the entire fediverse. An instance can have its own way of users to be able to pay for their videos to be ads on other videos and this money can be used to help pay for the hosting of the instance.

- An instance admin will have the option to enable ads on their instance and weather the ads can come from other instances or only from the local instance.

- Ads are just any video, and the user who uploaded the video can pay using crypto (Bitcoin, Bitcoin Cash, Dash, Monero, etc) to have his video run as an ad for X amount of days.

- Ads must respect users privacy and the advertisers privacy. No tracking.

Video hosting costs money and this simple way could allow for huge instances to pay for lots of bandwidth and not have laggy videos on their instance.

**Comment by rigelk** [comment]
Hi! Please look out for related issues before creating one, as multiple issues cover this topic: #256, #1149, #629, #1291, etc. #1521 in particular already closes the topic:

> It is arguably out of the scope of PeerTube, which is about streaming videos, not ads. We have [a section of our FAQ](https://github.com/Chocobozzz/PeerTube/blob/develop/FAQ.md?rgh-link-date=2020-01-21T10%3A11%3A58Z#are-you-going-to-support-advertisements) dedicated to it. That is also why we labeled this issue as a problem meant to be solved with plugins: you can develop your own solution that integrates with PeerTube, but we won't develop an ads management system _in_ PeerTube.
