### ISSUE TITLE
240p auto resolution and WebTorrent over HLS

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#3081]
Since PeerTube 2.3, the auto resolution for previous encoded video encoded is 240p (though the best resolution are 720p or 1080p) and the priority is now given to WebTorrent when the video has both HLS and WebTorrent encoded files. 

**Browsers**
Seen on last Chrome and Firefox Windows and Linux

**PeerTube**
2.3 version

**Instance**
https://queermotion.org

**Comment by kimsible** [comment]
It looks like the `production.yml` in docker-volume has been back to an old version without streaming-playlists directory.

**Comment by rigelk** [comment]
@kimsible what is your main question?

**Comment by kimsible** [comment]
@rigelk 
> why HLS has no Audio-only resolution ?

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/aea53cc64919b3a3ecfdf78b6b15c6a4d6edeea1

> why HLS has no Audio-only resolution?

I couldn't get hls.js to work with them in a playlist
