### ISSUE TITLE
Automatically backup media (audio, video, etc.) to cloud storage

### ISSUE THREAD

**Issue by trymeouteh** [Chocobozzz/PeerTube#3082]
Similar to [account migration](https://github.com/Chocobozzz/PeerTube/issues/549) except every time a video is uploaded to Peertube by a user, it could be backed up to a cloud storage service such as Nextcloud or Owncloud with all of its metadata (Title, Description, etc).

This way if the instance bans the channel. Their videos and data will be easily recoverable. Here is how I can see this working...

- You can add cloud storage services in your account settings and channel settings
- To backup data to your cloud, you will always need to enter a password that Peertube will not be able to access which the cloud storage account needs to authenticate the upload. I would image this will be needed to ensure the Peertube admin cannot spam your cloud storage with data to fill up your cloud storage with nonsense.
- You can make backups of your videos when you upload a video, edit a video or delete a video

**Comment by rigelk** [comment]
Hi! Thanks for reporting the issue, but this is arguably out of scope for PeerTube, which is about streaming videos, not doing server backups. However you are welcome to ask for specific features/plugin hooks if you would like to create a plugin addressing it.
