### ISSUE TITLE
Not all Followings instances are being shown

### ISSUE THREAD

**Issue by HuGo-Y** [Chocobozzz/PeerTube#3083]
**What happened?**
Not all Followings instances are being shown.

**What do you expect to happen instead?**
For all Followings instances to be shown.

**Steps to reproduce:**

1. go here https://tube.privacytools.io/about/follows

2. observe that there is no media.privacyinternational.org yet we can watch this video https://tube.privacytools.io/videos/watch/35536358-4605-4807-a580-783be1bdf1f3

**Additional information**
* PeerTube version or URL: https://tube.privacytools.io

**Comment by rigelk** [comment]
Hi @HuGo-Y! Please look out for related issues before creating one, as #2397 already covers this, with a dangling PR: #2688. You can then detail further your use case there, and upvote the issue to help us triage it.

**Comment by Chocobozzz** [comment]
You don't see the instance in the list because the `state` of the follow is `pending`. We should not display videos in this case for consistency

**Comment by Chocobozzz** [comment]
Has already been fixed in 2.3: https://github.com/Chocobozzz/PeerTube/commit/f046e2fa5c2af98f378056206ef65347f4b29b8d
