### ISSUE TITLE
Persistent error messages log for users

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#3086]
Hello,

Sometimes, when i try to publish a video, it fails. And because the peertube page is in the background, i miss every potential error notification because they disappear after a few second. They would be more practical if they were persistent.

**Comment by rigelk** [comment]
Please don't prefix you issue titles

**Comment by Chocobozzz** [comment]
Hello,

I think we can close this issue now we display the error in the upload page.
