### ISSUE TITLE
Channel Subscription RSS feel fails to update 

### ISSUE THREAD

**Issue by naclander** [Chocobozzz/PeerTube#3089]
**What happened?**
Clicking on the "Subscribe" button and the Subscribe via RSS button produces an empty RSS feed 
**What do you expect to happen instead?**
An RSS feed that updates as new videos are posted to the peertube channel
**Steps to reproduce:**

Go to peertube instance:
https://spacepub.space/accounts/ddevault/video-channels
Click subscribe, click subscribe via RSS to get RSS feed page:
https://spacepub.space/feeds/videos.xml?videoChannelId=2
Feed is empty

**Additional information**
* PeerTube version or URL: https://spacepub.space/accounts/ddevault/video-channels
* Browser name/version: Firefox 80

**Comment by Chocobozzz** [comment]
Thanks for the issue @naclander 

Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/97816649b793bdd0f3df64631ae0ef7cf3d7461c
