### ISSUE TITLE
Peertube CLI auth got forbidden

### ISSUE THREAD

**Issue by gai00** [Chocobozzz/PeerTube#3091]
Environment: docker - chocobozzz/peertube:production-buster
Version: 2.3.0

config:
```yaml
listen:
  hostname: '0.0.0.0'
  port: 9000
webserver:
  https: true
  hostname: my.host.name
  port: 443
# ...
```

Problem:
I try to upload my video via CLI, but got forbidden.
exec command in container. 
(`docker exec -it {container_id} bash`)
```
$ peertube auth add
prompt: instance url:  http://localhost:9000
prompt: username:  root
prompt: password:  ************

expected 200 "OK", got 403 "Forbidden"

curl localhost:9000
>> peertube html content
```

I tried `https://my.host.name`, lost certs in container...
I think https is no problem. but I want to upload without ssl. (maybe faster)

**Comment by Chocobozzz** [comment]
Please fill the template. We need server logs

**Comment by hopeseekr** [comment]
It took me FOREVER to figure out:

    prompt: instance url:  https://www.example.com
    prompt: username:  hopeseekr
    prompt: password:  ************

You MUST NOT have a trailing `/` in your `instance url`, or it will always say `expected 200 "OK", got 404 "Not Found"`.

It'd be very very helpful for PeerTube to autoremove everything after and including the domain name:port.

I am going to submit a PR for this.
