### ISSUE TITLE
Why usernames cannot have channel with the same name?

### ISSUE THREAD

**Issue by trymeouteh** [Chocobozzz/PeerTube#3099]
Why cant a username have a channel with the same username?

**Comment by rigelk** [comment]
Because the account and the channel cannot have the same actor address, which is tied to the username. It would be like having two individuals with same email address..

**Comment by trymeouteh** [comment]
To my understanding though, the URL for channels are different than videos. Why are users and channel names treated the same under the hood? I can understand if channels were usernames but this is not the case.

**Comment by rigelk** [comment]
@trymeouteh to be able to interact on the fediverse, you need an actor. Both account and channels are actors, which need to be resolved in their form username@domain, hence the comparison.

Though the URL is canonical, the username it represents must be unique on a server, for every actor.

**Comment by trymeouteh** [comment]
> @trymeouteh to be able to interact on the fediverse, you need an actor. Both account and channels are actors, which need to be resolved in their form username@domain, hence the comparison.
> 
> Though the URL is canonical, the username it represents must be unique on a server, for every actor.

OK now that makes sense.
