### ISSUE TITLE
The media could not be loaded with 60 fps video

### ISSUE THREAD

**Issue by zez3** [Chocobozzz/PeerTube#310]
The orginal uploaded file is a 2GB 1080/60fps mp4 video shot with an yi 4k+ action cam 
https://peertube.video/videos/watch/3efc5a2f-54c2-455e-8778-cfea892502fc
https://video.tedomum.net/videos/watch/93b103da-5dbb-4838-a1c8-99703f4220b2

* **PeerTube version or commit:**
I have no idea what version is running on https://video.tedomum.net/ or https://peertube.video
I'll have to test on an own install later
* **Browser name/version:**
ff beta & official 58, safari, chrome(Version 63.0.3239.132 (Official Build) (64-bit), Version 64.0.3282.167 (Official Build) (64-bit)), ungoogled chromium, Opera(51.0.2830.34, 51.0.2830.40)
OS mac/win(10,7,8,old Vista)/linux(debian,ubuntu,)
* **NodeJS version:**
see PeerTube version 
* **PostgreSQL version:**
see PeerTube version 

* **What is the expected behaviour?**
flawless streaming without having to refresh and restart streaming from the beginning(I guess an buffering message would do)
* **What do you see instead?**
The media could not be loaded, either because the server or network failed or because the format is not supported.(it's more often seen on linux machines)

* **Browser console log if useful (Gist/Pastebin...):**
n.a.
* **Server log if useful (Gist/Pastebin...):**
n.a.

**Comment by Chocobozzz** [comment]
The instances are not up to date.

Try on this instance to see if you can reproduce the bug: https://peertube3.cpy.re/videos/watch/3efc5a2f-54c2-455e-8778-cfea892502fc

The PeerTube version is in the footer: https://peertube3.cpy.re/about
If there is no version in the footer, it means the PeerTube instance is very old.

**Comment by zez3** [comment]
Thanks for the quick response. Unfortunately I get the same error.
Right, but do I need to re-upload the same content on the new node ? or has/should have no influence whatsoever. Would that mean that a node friend it's like/equivalent to a torrent tracker?
I'll have to build an docker image and test it. I'll get back after.

**Comment by Chocobozzz** [comment]
Should be fixed with https://github.com/Chocobozzz/PeerTube/commit/bf5685f0b7b1f23a1a3a972fc4d66061f31f9510 and https://github.com/Chocobozzz/PeerTube/commit/73c695919c6569bfb667c36fc5a6b9b862130a0d

Thanks for the issue @zez3!
