### ISSUE TITLE
Browser not compatible is not working with IE 11

### ISSUE THREAD

**Issue by anahimself** [Chocobozzz/PeerTube#3100]
With IE8/IE9/IE10 etc, the website is indicating to the user that if must change browser to access the application, but this is not working with IE11 (it lets the user go through and the interface is broken).

Could you indicate where to patch to disallow IE11 too ? Also if possible to have the same message (some IE version are with css, and some are just raw text)

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/6c733e46174c3f5b185402f9d37c88175543cf3c

**Comment by anahimself** [comment]
Thanks I will check asap

Also I noted that safari (on mobile) was producing a blank page too

**Comment by rigelk** [comment]
@anahimself please open a separate issue for that and detail your browser version and instance version there.

**Comment by anahimself** [comment]
Doesnt work well with IE11 (fr-FR and en-US):
![image](https://user-images.githubusercontent.com/18443886/91989572-f3a34c80-ed30-11ea-8486-ffa596519fa5.png)

With IE10 no problem (fr-FR):
![image](https://user-images.githubusercontent.com/18443886/91989438-d1113380-ed30-11ea-9dc1-46537f04311c.png)

With IE9 and previous only raw text but works.. (fr-FR):
![image](https://user-images.githubusercontent.com/18443886/91989495-e1c1a980-ed30-11ea-9b4b-3c4d351afce6.png)
