### ISSUE TITLE
Rss in peertub don't worke

### ISSUE THREAD

**Issue by Hjaltiy** [Chocobozzz/PeerTube#3102]
What happened? = Rss does not work. My browser says so and I do not get updates. In my rss clint (It's not the clint)

What do you expect to happen instead? = Nothing

Steps to reproduce:

1..

2..

3..

Additional information

PeerTube version or URL: tube.privacytools.io

Browser name/version:Brave and firefox and chrome (BUT IT IS MY RSS CLINT)(Latest I think)

NodeJS version: Idk

Link to browser console log if useful:NOT my browser

Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):No

**Comment by rigelk** [comment]
Opening a second issue with the same vague information is not helping :confused:

What is the "clint" you refer to ?
Fill the steps to reproduce the issue in detail, as I fail to see what constitutes a failure or seccess in your case using the RSS feeds.
