### ISSUE TITLE
Watch/View On Instance

### ISSUE THREAD

**Issue by trymeouteh** [Chocobozzz/PeerTube#3104]
I think when your watching a video, viewing a playlist, viewing a channel and so on that is from another instance. There should be a button on the page which says "Watch On Instance" or "View On Instance" which when you click on, it will take you to the exact same page your viewing but on the instance the video/channel/playlist is on.

For example if your watching a video from instance1.com but your watching this video on instance2.com. There will be a button which when clicked on will take you to that video on instance1.com.

**Comment by Chocobozzz** [comment]
Hello,

There is already a link below the video description
![screen_2020-08-19-08:23:17](https://user-images.githubusercontent.com/5180488/90599555-5bb44780-e1f5-11ea-8faa-5416d36e0823.png)

**Comment by trymeouteh** [comment]
I have not seen any on any of the instances I been on.

Is there a link to view the channel or playlists on the original instance?

**Comment by trymeouteh** [comment]
> Hello,
> 
> There is already a link below the video description
> ![screen_2020-08-19-08:23:17](https://user-images.githubusercontent.com/5180488/90599555-5bb44780-e1f5-11ea-8faa-5416d36e0823.png)

I see that link now and that is not what this feature request is. The feature request is to have a link or button appear on a video that your watching from another instance and that button will take your to the exact same video but on the instance it is from.
