### ISSUE TITLE
502 Error

### ISSUE THREAD

**Issue by hopeholdings** [Chocobozzz/PeerTube#3107]
**What happened?**
Installed and all was running well for a couple of weeks.  Starting uploading lots of videos and now getting 502 error. We have not restarted server before getting error.

**What do you expect to happen instead?**
For application to work.

**Steps to reproduce:**

**Additional information**
* PeerTube version or URL:  2.30  gorf.tube
* Browser name/version:  all
* NodeJS version:  12.83

* Link to browser console log if useful:  
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
![image](https://user-images.githubusercontent.com/63526042/90648134-23b60000-e207-11ea-8320-eb8b851869c2.png)
![image](https://user-images.githubusercontent.com/63526042/90648198-3cbeb100-e207-11ea-8995-98d4bcd898b5.png)
[peertube.log](https://github.com/Chocobozzz/PeerTube/files/5097152/peertube.log)

**Comment by Chocobozzz** [comment]
Hello,

Your peertube instance cannot connect to your PostgreSQL database (`ECONNREFUSED 127.0.0.1:5432`)

**Comment by hopeholdings** [comment]
Hi.  thanks.  Figured it out. putting vids in wrong db and filled it up.

BTW - awesome application!
