### ISSUE TITLE
Support for SSL connections to postgresql

### ISSUE THREAD

**Issue by averymd** [Chocobozzz/PeerTube#3110]
**What happened?**

I am attempting to switch my Peertube instance to use a DigitalOcean managed postgresql database. When configuring Peertube to connect, no `sslmode` or `ssl` setting is available, which is required by DigitalOcean ([their documentation](https://www.digitalocean.com/docs/databases/postgresql/how-to/connect/) specifically calls for `sslmode = require`).

When a postgresql server requires SSL and doesn't get it, the error from journalctl looks like:

    no pg_hba.conf entry for host "x.x.x.x", user "peertube", database "peertube_prod", SSL off

I am able to manually connect to the DB from this VM, so it's not actually a matter of the IP being in the accepted list.

**What do you expect to happen instead?**

I should be able to set an option in `production.yaml` for an SSL connection to postgresql that results in the correct flag on the connection string to postgresql.

**Additional information**
* PeerTube version or URL: 2.3.0
* Browser name/version: N/A
* NodeJS version: 10.20.1

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): the error from journalctl is above, but I can provide more if it would be helpful.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/b0ce7c39dce4be8d7c2775e8205f8abfe348a0de
