### ISSUE TITLE
Streaming very high bitrate video from PeerTube?

### ISSUE THREAD

**Issue by unfa** [Chocobozzz/PeerTube#3111]
I've noticed that streaming 1080p video form some PeerTube instances switches the player to a static HTTP hosting, instead of WebTorrent P2P.

I wonder why is that - I've been searching answers but couldn't find anything. Probably I didn't figure out the right search terms...

Also watching on mobile devices does the same - I suspect that's to save mobile data, thought maybe a read-only P2P (leeching) connection could be a good idea in such cases?

Anyway - I am wondering if it's possible/feasible to serve video from PeerTube in a quality far exceeding the usual YouTube bitrate for 1080p video. It could be something unique that'd give my viewers incentive to watch on PeerTube other than the obvious reasons - they'd get much higher video quality this way.

I'm thinking about 15-20 (maybe even 30) Mb/s H.264. PeerTube's huge advantage is... well... the Peer2Peer aspect of it. If enough people watch, even a relatively puny host should be able to sustain and deliver the content.

I guess one issue is that the video is being seeded from viewers only for as long as they watch - the instant they close the tab or click to another video they are no longer seeding what they've just watched. Which is fair, as nobody would want to be seeding 30 videos that they've watched today - that'd be a total performance hog and would certainly turn users off. Thought maybe an opt-in extended seeding time could be a good option? I'd happily seed the 3-5 last videos indefinitely to help the community.

However for this reason I was thinking of using WebTorrent to seed videos. Is there a CLI-only solution that'd do it? `webtorrent-hybrid`?

**Comment by test2a** [comment]
https://peertube.co.uk/videos/watch/79973093-ab11-4608-8fb9-0a5d2bdd072d

here is a link to a 8k video. My laptop cannot even load the video but it shows on the quality selector. 

Do you have an example of the video, sign up on this public instance and lets see if we are able to run it https://devtube.dev-wiki.de/

**Comment by unfa** [comment]
Thanks! I can barely play the top quality version - the bitrate doens't seem to be that high, my laptop just struggles to decode it (I can see it's CPU bound).

**Comment by Chocobozzz** [comment]
Hello,

We have issues with the webtorrent player with high quality videos. Try to enable HLS in admin and reupload the video to see if it improves playback
