### ISSUE TITLE
REST API documentation scroll jumps

### ISSUE THREAD

**Issue by McFlat** [Chocobozzz/PeerTube#3115]
The rest api docs are nearly impossible to use with that darn scroll always jumping back to the top of the page!!!!!!!!!!Q

https://docs.joinpeertube.org/api-rest-reference.html

**Comment by Findus23** [comment]
That might be the same bug as https://github.com/Redocly/redoc/issues/816

**Comment by Chocobozzz** [comment]
Thanks @Findus23, I upgraded dependencies in https://framagit.org/framasoft/peertube/documentation/-/commit/d9222659a27a4fa2ce090f81a09f97f1016ceae2
