### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by Tachi107** [Chocobozzz/PeerTube#3118]
Supporting WebP images for video thumbnails would be nice; higher quality and lower bandwidth/storage usage, and no downsides (or am I wrong?).

**Comment by Chocobozzz** [comment]
WebP uploads is now supported in https://github.com/Chocobozzz/PeerTube/commit/e08ff02a9f1fb1cfbdfa8f0f602eda9419ba6cc3

Unfortunately webp is not supported in previous versions of Safari, so we'll have to wait before using this format by default.

**Comment by Agorise** [comment]
What about animated webp images? Creators and designers can really do some eye-catching work with webp animations.
