### ISSUE TITLE
Share link from subscription is not viewable without login

### ISSUE THREAD

**Issue by LPS-github** [Chocobozzz/PeerTube#3122]
When attempting to share a video from my subscriptions via the share button it is not viewable by anyone without a login on my server.

![image](https://user-images.githubusercontent.com/69872464/91200813-a3434380-e6cd-11ea-8b7f-b2f0bad7540a.png)

link followed without login.

![image](https://user-images.githubusercontent.com/69872464/91200843-b2c28c80-e6cd-11ea-8ef2-606a2229972a.png)

**Comment by rigelk** [comment]
Hi @LPS-github! Please look out for related issues before creating one, as #2972 already covers this. You can then detail further your use case there, and upvote the issue to help us triage it.

**Comment by Chocobozzz** [comment]
Sorry for the misunderstanding. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/e6abf95e9fc9fde52d583850cf7faafdf7d050d5
