### ISSUE TITLE
Installation instructions unclear: what needs to be modified in peertube.service?

### ISSUE THREAD

**Issue by mehronkugler** [Chocobozzz/PeerTube#3123]
Excited to get this project going. Installation has been going well. I think my instance has some configuration issues.

In the documentation, where it says

    Update the service file:
    $ sudo vim /etc/systemd/system/peertube.service

What exactly needs to be updated in `peertube.service`?

**Comment by Chocobozzz** [comment]
Hello,

If you kept the paths specified in the documentation (`/var/www/peertube`), you have nothing to do.

I updated the documentation in https://github.com/Chocobozzz/PeerTube/commit/96df6ca606ddf2b3116a788e89f70e8dafef3a44

**Comment by mehronkugler** [comment]
Thank you very much!
