### ISSUE TITLE
Change Page Title to instance name

### ISSUE THREAD

**Issue by srhughes89** [Chocobozzz/PeerTube#3124]
When I share a video url on Telegram it uses the host name and not the instance name. Is there a way to change that?

**Comment by test2a** [comment]
![Screenshot_2020-08-26-22-51-48-0693619296](https://user-images.githubusercontent.com/39449563/91336063-f9f46e80-e7ee-11ea-82de-066a54950df8.png)

https://peertube2.cpy.re/videos/watch/eec8468f-5b40-41a8-a40e-7b1e62aeb5bd

https://peertube2.cpy.re/videos/watch/9c9de5e8-0a1e-484a-b099-e80766180a6d

i shared these two links from peertube2.cpy.re. they are both federated videos but i am not seeing anything amiss. what should happen instead?

**Comment by Chocobozzz** [comment]
Thanks for the issue. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/865af3fd7b192bda44dea65c6df125f233424f3e
