### ISSUE TITLE
Content differ from original instance and same instance followed

### ISSUE THREAD

**Issue by rosbeef** [Chocobozzz/PeerTube#3126]
**What happened?**
There is a big difference between the original instance : https://video.lemediatv.fr/accounts/lemediatv/about and the instance that I follow from my instance account : https://video.3cmr.fr/accounts/lemediatv@video.lemediatv.fr/about
Many datas differ from the account creation date to the content and shared video .

**What do you expect to happen instead?**
Same datas should be returned

**Steps to reproduce:**

1.go to one instance to view the instance "https://video.lemediatv.fr/accounts/lemediatv/videos"
2.go to you instant and account and search for "lemediatv.fr "
3.click on the instance name on the video corresponding to "lemediatv@video.lemediatv.fr"
4.click on video tabs
5.compare the pages opened on step 1 and theone on step 4, you should compare de creation date in about page too.

**Additional information**
* PeerTube version or URL: 2.3.0 on both servers https://video.lemediatv.fr/about/instance | https://video.3cmr.fr/about/instance
* Browser name/version: firefox 79.0 (64-bit)
* NodeJS version: v 4.8.2 on my server https://video.3cmr.fr

* Link to browser console log if useful: [console-export-2020-8-27_11-0-27.txt](https://github.com/Chocobozzz/PeerTube/files/5137192/console-export-2020-8-27_11-0-27.txt)
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): [peertube.log](https://github.com/Chocobozzz/PeerTube/files/5137193/peertube.log)

**Comment by Chocobozzz** [comment]
Hello,

https://video.3cmr.fr/about/follows did not subscribe to https://video.lemediatv.fr/about/follows so it makes sense if video.3cmr.fr does not have all the videos of video.lemediatv.fr

**Comment by rosbeef** [comment]
i don't want to follow one external instance from my instance to not saturate my familly with "complotism" ;) in trend or discover content

I follow all of lemediatv.fr channels whith user @rosbeefandino@video.3cmr.fr and some have no videos when i access from my 3cmr account. example :
lemediatv.fr (2 videos) : https://video.lemediatv.fr/video-channels/la_main_a_la_plume/videos
![image](https://user-images.githubusercontent.com/29942937/92272194-19f2f480-eeb7-11ea-8f59-08e6319ec6cb.png)
3cmr.fr         (0 videos): https://video.3cmr.fr/video-channels/la_main_a_la_plume@video.lemediatv.fr/videos
![image](https://user-images.githubusercontent.com/29942937/92272225-25deb680-eeb7-11ea-9f01-358180642451.png)

**Comment by Chocobozzz** [comment]
Sorry for the late answer. I can't access to your peertube instance. Is it still an issue? If yes, did you try to unfollow and refollow these channels?

**Comment by rosbeef** [comment]
Non, sorry my instance fails on younohost upgrade I have to full reinstall.

Le lundi 9 novembre 2020, Chocobozzz <notifications@github.com> a écrit :
> Sorry for the late answer. I can't access to your peertube instance. Is
it still an issue? If yes, did you try to unfollow and refollow these
channels?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci4.googleusercontent.com/proxy/EBG3wVz0GAwByVcYkkHwzZZJiBe0lv3GI3TFR9g2E19Wxh_B6XYab4EBqTV6up4pSVVzMi1Fb8ZBSKFjSVI5n4dIs95iqPAuLfYUIvOYK7tmCae6eevtafM7KCAg24czekGEOTAY7H6SFOJ06ZKYkpHw6_JFrKkwdlzCgE7q1BbAbo-cd9v3QOznvz4hwDwCItAu1u07rIK_bFQ00IoFk6eGd2tpRRqGKMjjDLLVSQ=s0-d-e1-ft#https://github.com/notifications/beacon/AHEOJGKVVJ4POBMG33UWTB3SO7YGNA5CNFSM4QNDAON2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFMT4XSQ.gif
>

-- 
Envoyé depuis Gmail Mobile
