### ISSUE TITLE
Channel and Privacy select fields empty after upload on develop / v2.4.0

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#3129]
As you see on the screenshot, **Channel** and **Privacy** values pre-selected before uploading are empty in the form appearing on the next step.

Also **Category**, **License**, and **Language** looks already selected with the cross on the right but these are also empty.

With imports (URL and Torrent) it looks OK.

![image](https://user-images.githubusercontent.com/1877318/91483213-a003af80-e8a7-11ea-90d9-70623733aaca.png)

**Comment by kimsible** [comment]
@rigelk would you have an idea where this issue is from ?

**Comment by rigelk** [comment]
Channel and privacy values cannot be empty, while the other can. I'll have a look at it tomorrow

**Comment by kimsible** [comment]
Thanks.

**Comment by Chocobozzz** [comment]
Any news @rigelk?

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/30b1e1060371f5f2578910f3f4a2cdf95fe78274
