### ISSUE TITLE
Feature Request: I2P Support

### ISSUE THREAD

**Issue by gitbugged** [Chocobozzz/PeerTube#313]
Many countries and ISP block/censor torrent traffic. I would like to have an option that enforces webtorrents to run over I2P. 

https://geti2p.net/en/docs/applications/bittorrent

**Comment by tcitworld** [comment]
As far as I know WebTorrent (which uses WebRTC) can't be blocked like regular torrent traffic.

**Comment by Chocobozzz** [comment]
Thanks @gitbugged but it's a WebTorrent issue :) https://github.com/webtorrent/webtorrent/issues/465
