### ISSUE TITLE
Web Monetization Support

### ISSUE THREAD

**Issue by LuckierDodge** [Chocobozzz/PeerTube#3131]
After spending some time on PeerTube instances and other federated social media, I can't help but shake the feeling that they might benefit from [Web Monetization](https://webmonetization.org/) support. For those who don't know, Web Monetization is an open standard and JavaScript API that allows users to automatically send a small amount of money continuously to a site while the user is on a page. It's been proposed as a W3C web standard and is already used by sites like Imgur, Twitch, Hackernoon, and others. I can't help but feel PeerTube is the most natural fit for this.

I think it has a number of key benefits:
* Decentralized: anyone can create a Web Monetization provider or wallet.
* Automatic: doesn't require that users actively support each individual. Monetization is based solely on engagement from Web Monetization-enabled users.
* Easy integration: all that is needed to start monetizing is a `meta` tag on a webpage. And it has no effect on users not using the standard.
* Support for Instances and Users: payment pointers can be added for content creators on their videos and pages, and for the instance as a whole in discovery pages and unmonetized videos. Multiplexing options also exist, to support multiple payment pointers at the same time.
* Not Cryptocurrency: doesn't requires users or creators to buy into a new crypto or ecosystem. It's real money moving from users to creators, and it's not tied to any one corner of the internet.
* No Tracking, No Ads: has a similar passive support mechanism to ad-based monetization, without the icky surveillance capitalism.

If this is something people think is worthwhile, I'd love to start working on it. If they think it fits better as a plugin, I'd be happy to develop that as well once the new plugin system is unveiled.

**Comment by test2a** [comment]
instead of building this directly into the core, maybe you or someone else can build a plugin around this. peertube has that functionality now

**Comment by Chocobozzz** [comment]
Thanks for this issue @LuckierDodge. Merging it in https://github.com/Chocobozzz/PeerTube/issues/1586
