### ISSUE TITLE
Issue uploading .wav in firefox on linux

### ISSUE THREAD

**Issue by FruityWelsh** [Chocobozzz/PeerTube#3133]
**What happened?**
Tried to uploud a short .wav file, but instead of making it to naming/tag/description page instead got a failure popup saying
```
Error:
This file is not supported or too large. Please, make sure it is of the following type: .webm, .ogv, .mp4, .mov, .avi, .flv, .mkv, .m4v, null, .mp3, .ogg, .wma, .wav, .flac
```

**What do you expect to happen instead?**
it to take me to next step
**Steps to reproduce:**

1. Open firefox on linux desktop

1. Be logged into https://video.autizmo.xyz 

2. Click the ```Upload``` button in top left 

3. Click ```Select the file to upload```

4. Select a .wav file

5. optionally select ```edit``` and select another .jpg as the image (it fails either way)

6. click ```Upload {FILENAME}.wav```

**Additional information**
This file was able to be upload via chromium/84.0.4147.135 (Official Build) Arch Linux (64-bit)
* Link to uploaded .wav
https://video.autizmo.xyz/videos/watch/835e340e-be5c-46b3-8e32-3c434cba4959
* PeerTube version or URL:
https://video.autizmo.xyz
* Browser name/version:
Firefox/79.0 (64-bit) Manjaro-Linux
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by test2a** [comment]
Your instance looks to be on 2.3.0. Can you try to update to 2.4 if you are the owner ? I believe we fixed this after 2.3.0

**Comment by test2a** [comment]
https://github.com/Chocobozzz/PeerTube/pull/3097 yep. this pull request should solve your issue and i confirm it exists on 2.3.0

**Comment by FruityWelsh** [comment]
I do not run this instance, but I messaged the owner and linked to this issue.

**Comment by Chocobozzz** [comment]
Hello,

I saw your instance has been updated. Is it still an issue?
