### ISSUE TITLE
Channel Creation - Add icon

### ISSUE THREAD

**Issue by karibuTW** [Chocobozzz/PeerTube#3135]
Hello,
Will it be possible to add an icon/image right during the channel creation ("Create video channel")?
At the moment, I need to create one, then edit it, to add the icon. Will be best to be able to do it all at once.

Possible?

Thank you

**Comment by Chocobozzz** [comment]
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1506
