### ISSUE TITLE
Force langage for all user

### ISSUE THREAD

**Issue by anahimself** [Chocobozzz/PeerTube#3136]
Would it be possible to force the langage for every user to en-US for example ? If yes, can you tell me where we can override this value in the js code ?

We have indeed fr-FR + de-DE users, and the error messages are very different (some are in raw text, some are in red, ...).

We would need to have the same experience for every user

**Comment by Chocobozzz** [comment]
Hello,

You can update languages in https://github.com/Chocobozzz/PeerTube/blob/develop/shared/core-utils/i18n/i18n.ts and then rebuild PeerTube (`npm run build` after a git clone: see https://docs.joinpeertube.org/#/install-unofficial?id=git)
