### ISSUE TITLE
Hive Hosting

### ISSUE THREAD

**Issue by kayasaya** [Chocobozzz/PeerTube#3137]
How could you make an Opt-in plugin for users to "donate" HDD for the channels they follow, so the server overhead is reduced? Similar to how torrents work, and obviously they would need to download an app that automatizes the process to a few clicks and a few "i accept" buttons

**Comment by Chocobozzz** [comment]
Hello,

See https://github.com/Chocobozzz/PeerTube/issues/494 for a discussion about this.
