### ISSUE TITLE
Install using Docker on non standards ports - issues with oauth and SSL certificate

### ISSUE THREAD

**Issue by JohnLines** [Chocobozzz/PeerTube#3139]
I followed the Docker install instructions, but, as my server (Debian Buster) is already running several web sites under apache2, with certbot and an MTA, I adjusted, in docker-compose.yml) the reverse-proxy ports to be

    ports:
            #      - "80:80"     # The HTTP port
            #      - "443:443"   # The HTTPS port
                  - "1580:1580"     # The HTTP port
                  - "15443:15443"   # The HTTPS port

Otherwise following the instructions.

**What happened?**

I have a peertube site running at https://peertube.paladyn.org:15443/login  

It shows a message

_Error

Cannot retrieve OAuth Client credentials: . Ensure you have correctly configured PeerTube (config/ directory), in particular the "webserver" section._

and an error
 Invalid client: client is invalid 

for any attempt to log in.

 docker-compose logs | grep -i oauth
shows

peertube_1       | [peertube.paladyn.org:443] 2020-09-04 14:44:46.674 info: 2001:: - - [04/Sep/2020:14:44:46 +0000] "GET /api/v1/oauth-clients/local HTTP/1.1" 403 - "https://peertube.paladyn.org:15443/" "Firefox"
peertube_1       |     "stack": "invalid_client: Invalid client: client is invalid\n    at new InvalidClientError (/app/node_modules/oauth2-server/lib/errors/invalid-client-error.js:26:14)\n    at /app/node_modules/oauth2-server/lib/handlers/token-handler.js:141:15\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)"

I suspect this causes the login issue

**What do you expect to happen instead?**
Was impressed at how far it did get, but completely new to Docker and traefik. Would be good to be able to set up peertube on a server which is already running live services on the standards ports (80 and 443), particularly for people - like me - attracted to the concept, but not sure if their system will handle it.

The SSL certificate returned is a Traefix self signed one, but it is clearly intended to be set up to use a Letsencrypt one. I assume that fails due to the non standard port.
I assume the oauth issue is the the cause of the inability to log in

**Steps to reproduce:**

1.
On Debian Buster system, install docker-compose

2.
Follow instructions at https://docs.joinpeertube.org/#/install-docker
3.
Browse to https://peertube.paladyn.org:15443/login

**Additional information**
* PeerTube version or URL: chocobozzz/peertube:production-buster
* Browser name/version: Tested with Firefox and Chromium
* NodeJS version:

**Comment by rigelk** [comment]
Your issue is with traefik and port binding, not with PeerTube. Change the left part of your ports configuration only.

**Comment by JohnLines** [comment]
I did change the left parts of the ports configuration, which did not seem to make a significant difference, although the peertube_reverse_proxy container was rebuilt, so the change was picked up.

I created an apache site configuration for peertube.paladyn.org as

<VirtualHost *:80>

ServerName peertube.paladyn.org

# Prevent the proxy from being used for anything except ProxyPass (i.e. as a reverse proxy)
ProxyRequests Off

ProxyPass / http://localhost:1580/
ProxyPreserveHost On
ProxyPassReverse / http://localhost:1580/

  ErrorLog /var/log/apache2/peertube-error.log
  TransferLog /var/log/apache2/peertube-access.log



</VirtualHost>

A reload of apache and restart of the docker container and I can see that traefik has successfully obtained a Letsencrypt SSL certificate.

The oauth2 issue remains - I will investigate that next

**Comment by JohnLines** [comment]
I gave up on trying to do oauth via Docker on a non standard port. Have successfully installed peertube at https://peertube.paladyn.org/ by following the standard install instructions, apart from using a modified version of the apache configuration found at https://gist.github.com/rigelk/07a0b8963fa4fc1ad756374c28479bc7 with changes for Debian locations of log files etc.

**Comment by rigelk** [comment]
@JohnLines this config is severely broken, HLS won't work for instance

**Comment by JohnLines** [comment]
Wanted to evaluate PeerTube as an alternative to YouTube for a small organisation, currently uploading about half a dozen videos a week to Youtube, but with some people not keen on the advertising, and others on the principle.
The ability to co-host PeerTube with other Fediverse projects easily is important, as it reduces the barriers to entry, which are currently much higher than putting everything on Facebook
