### ISSUE TITLE
WebM video hangs during playing in Firefox

### ISSUE THREAD

**Issue by valvin1** [Chocobozzz/PeerTube#314]
* **PeerTube version or commit:** 0.0.28-alpha
* **Browser name/version:** : Firefox 58.0.2 - Xunbuntu 16.04
* **NodeJS version:** v8.9.4
* **PostgreSQL version:** 9.5

* **What is the expected behaviour?**
I play the video and enjoy it

* **What do you see instead?**
Video starts bug hangs after few seconds. It appears to be on WebM video only and in firefox. Same video in Chromium (64.0.3282.167) plays very well.
Other videos in different codec plays well.

I get issue on these video : 
* https://peertube.valvin.fr/videos/watch/82f21c9e-35ad-465f-b5ff-25da1399e796
* https://peertube.valvin.fr/videos/watch/54c02155-5d56-4d55-9a8d-beb447389125

It appears on different version of peertube : 0.0.20 - 0.0.23 - 0.0.28

**Comment by Chocobozzz** [comment]
I think it's a Firefox bug. I created an issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1441463

**Comment by Chocobozzz** [comment]
Closing because it's not a peertube issue, and we don't really use webm anymore.
