### ISSUE TITLE
Unblur NSFW video with one click and open it via a second click

### ISSUE THREAD

**Issue by kevATin** [Chocobozzz/PeerTube#3143]
Sometimes users might want to see the preview of a single NSFW video without disabling NSFW blur.

By clicking on the video thumbnail once it would be unblurred, and only when clicking on it a second time, in its unblurred state, it would open.

Ideally this would be a per user setting, because some might find it annoying to have to click twice.

**Comment by grravity** [comment]
I like this, it could be set by users.
Choose Blur, then a submenu appears offering reveal thumbnail on click, or open video

**Comment by Chocobozzz** [comment]
Closing this issue in favour of https://github.com/Chocobozzz/PeerTube/issues/6144
