### ISSUE TITLE
Auto-Generate Video Preview Sheets

### ISSUE THREAD

**Issue by kevATin** [Chocobozzz/PeerTube#3144]
Bandwidth was a lot more limited for me a decade ago, and for many people it still is (plus some even still have data caps). Video Preview Sheets (and the many other names they go by) have helped me greatly to efficiently decide what is worth downloading and what to skip, so I think it would make sense to have PeerTube automatically generate one for each video.
These images could then be embedded in forum posts (or anywhere else) like any other image file, next to links to the video itself and users could decide by looking at the preview images whether it's worth their bandwidth.

### Things that the Video Preview Sheet could contain:

- video name

- video length

- video uploader / author?

- available video qualities (potentially in depth information regarding resolution, frames, colors, encoding, etc)

- available audio qualities

- available subtitle languages

- available audio languages

- short video description?

- The preview images themselves. It would probably make sense to let the uploader select the frames of the video that are taken for this, but they should be evenly distributed so you get a good idea of what the whole video is about, not just a single highlighted scene. Each frame should come with a little timestamp. It might make sense for longer videos to have more preview images than short ones, but if the sheet gets too big it becomes hard to look at the frames by themselves, so maybe a limit should be enforced.
One option for handling the frame selection that I thought of could be for PeerTube to determine the amount of frames based on the video length, and then split up the video duration in N "chapters" or pieces (where N is the number of frames). Then the uploader gets to choose the individual frames however they have to pick one frame per "chapter" and no more. That way it's ensured that the previews are evenly distributed while still giving the user freedom.

Maybe instance admins could customize these fields and add their own ones or remove ones that they don't deem necessary.

**Comment by Chocobozzz** [comment]
What are *Video Preview Sheets*?

**Comment by test2a** [comment]
https://www.maketecheasier.com/create-thumbnail-sheets-for-videos-linux/

i think this is what OP is referring to. FFMPEG has this built in

**Comment by kevATin** [comment]
@Chocobozzz maybe you have heard of them as Video Contact Sheets?
Yes, like the one @test2a linked; Here are more examples:

![example1](https://camo.githubusercontent.com/43b116159e7326cad220f314debb8ef8441380aa/687474703a2f2f692e696d6775722e636f6d2f724149744f70332e706e67)

![example2](https://jasoncoleman.smugmug.com/Public-Shares/PostedOnline/i-wn72P7w/0/O/sample_contactsheet.jpg)

**Comment by sschueller** [comment]
I would like to see thumbnails autogenerated for use with the sliderbar similar to youtube.

**Comment by test2a** [comment]
We could have this in the download section specifically because that is why its usually needed.

Besides, we dont want to clutter the video player

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/537
