### ISSUE TITLE
Install with docker

### ISSUE THREAD

**Issue by TsymbalArtem** [Chocobozzz/PeerTube#3145]
Hello, I am doing the script "npm run build -- --light".  As a result, I got:

sh: 1: scripty: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! peertube@2.1.1 build: `scripty "--light"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the peertube@2.1.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by rigelk** [comment]
You need to install development dependencies before. What commands have you run to setup your environment before? How is it related to docker?

**Comment by TsymbalArtem** [comment]
@rigelk It's my Dockerfile.buster
 RUN yarn install --pure-lockfile \
  && npm run build -- --light \
  && rm -r ./node_modules ./client/node_modules \
  && yarn install --pure-lockfile --production \
  && yarn cache clean

**Comment by TsymbalArtem** [comment]
And these if logs 


root@tingtube-dev:/tmp# cat 2020-09-07T10_16_23_338Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.14.6
3 info using node@v10.22.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle peertube@2.1.1~prebuild: peertube@2.1.1
6 info lifecycle peertube@2.1.1~build: peertube@2.1.1
7 verbose lifecycle peertube@2.1.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle peertube@2.1.1~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle peertube@2.1.1~build: CWD: /app
10 silly lifecycle peertube@2.1.1~build: Args: [ '-c', 'scripty' ]
11 silly lifecycle peertube@2.1.1~build: Returned: code: 1  signal: null
12 info lifecycle peertube@2.1.1~build: Failed to exec build script
13 verbose stack Error: peertube@2.1.1 build: scripty
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid peertube@2.1.1
15 verbose cwd /app
16 verbose Linux 5.4.0-26-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v10.22.0
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error peertube@2.1.1 build: scripty
22 error Exit status 1
23 error Failed at the peertube@2.1.1 build script.
23 error This is probably not a problem with npm. There is

**Comment by toogley** [comment]
why do you rm your node_modules after building with npm?

**Comment by Chocobozzz** [comment]
Please use the official dockerfile: https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/Dockerfile.buster

You can also pull the image from docker hub (`chocobozzz/peertube:production`)
