### ISSUE TITLE
the peertube server generate to many log，and the server was lower disk due to these log

### ISSUE THREAD

**Issue by chengjingfeng** [Chocobozzz/PeerTube#3146]
reproduce at v2.1.1 and v2.3.0 did not try the other version yet

**Comment by chengjingfeng** [comment]
[syslog.txt](https://github.com/Chocobozzz/PeerTube/files/5185708/syslog.txt)
attach the log， the log size will increase to 40GB after hours

**Comment by Chocobozzz** [comment]
you logfile does not correspond to peertube server logs

**Comment by chengjingfeng** [comment]
@Chocobozzz I got a new log file from sever, i just copy piece of it here, it is a huge file, the whole log file can be download from here(https://chengjingfiles.oss-cn-beijing.aliyuncs.com/syslog.txt)


Sep  8 08:09:01 localhost peertube[27111]: > peertube@2.3.0 start /var/www/peertube/versions/peertube-v2.3.0
Sep  8 08:09:01 localhost peertube[27111]: > node dist/server
Sep  8 08:09:01 localhost CRON[27140]: (root) CMD (/usr/local/qcloud/stargate/admin/start.sh > /dev/null 2>&1 &)
Sep  8 08:09:01 localhost CRON[27148]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && /usr/lib/php/sessionclean)
Sep  8 08:09:03 localhost systemd[1]: Started Daily apt download activities.
Sep  8 08:09:05 localhost peertube[27111]: [video.gulutube.com:443] 2020-09-08 08:09:05.052 #033[33mwarn#033[39m: Emailer is disabled so the contact form will not work.
Sep  8 08:09:06 localhost peertube[27111]: [video.gulutube.com:443] 2020-09-08 08:09:06.165 #033[32minfo#033[39m: Database peertube_prod is ready.
Sep  8 08:09:06 localhost peertube[27111]: [video.gulutube.com:443] 2020-09-08 08:09:06.175 #033[31merror#033[39m: Cannot install application. {
Sep  8 08:09:06 localhost peertube[27111]:   "err": {
Sep  8 08:09:06 localhost peertube[27111]:     "stack": "Error: ENOENT: no such file or directory, mkdir",
Sep  8 08:09:06 localhost peertube[27111]:     "message": "ENOENT: no such file or directory, mkdir",
Sep  8 08:09:06 localhost peertube[27111]:     "errno": -2,
Sep  8 08:09:06 localhost peertube[27111]:     "code": "ENOENT",
Sep  8 08:09:06 localhost peertube[27111]:     "syscall": "mkdir"
Sep  8 08:09:06 localhost peertube[27111]:   }
Sep  8 08:09:06 localhost peertube[27111]: }
Sep  8 08:09:06 localhost peertube[27111]: npm ERR! code ELIFECYCLE
Sep  8 08:09:06 localhost peertube[27111]: npm ERR! errno 255
Sep  8 08:09:06 localhost peertube[27111]: npm ERR! peertube@2.3.0 start: `node dist/server`
Sep  8 08:09:06 localhost peertube[27111]: npm ERR! Exit status 255
Sep  8 08:09:06 localhost peertube[27111]: npm ERR!
Sep  8 08:09:06 localhost peertube[27111]: npm ERR! Failed at the peertube@2.3.0 start script.
Sep  8 08:09:06 localhost peertube[27111]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Sep  8 08:09:06 localhost systemd[1]: peertube.service: Main process exited, code=exited, status=255/n/a
Sep  8 08:09:06 localhost systemd[1]: peertube.service: Unit entered failed state.
Sep  8 08:09:06 localhost systemd[1]: peertube.service: Failed with result 'exit-code'.
Sep  8 08:09:06 localhost systemd[1]: peertube.service: Service hold-off time over, scheduling restart.
Sep  8 08:09:06 localhost systemd[1]: Stopped PeerTube daemon.
Sep  8 08:09:06 localhost systemd[1]: Started PeerTube daemon.
Sep  8 08:09:06 localhost peertube[27202]: > peertube@2.3.0 start /var/www/peertube/versions/peertube-v2.3.0
Sep  8 08:09:06 localhost peertube[27202]: > node dist/server
Sep  8 08:09:10 localhost peertube[27202]: [video.gulutube.com:443] 2020-09-08 08:09:09.997 #033[33mwarn#033[39m: Emailer is disabled so the contact form will not work.
Sep  8 08:09:11 localhost peertube[27202]: [video.gulutube.com:443] 2020-09-08 08:09:11.159 #033[32minfo#033[39m: Database peertube_prod is ready.
Sep  8 08:09:11 localhost peertube[27202]: [video.gulutube.com:443] 2020-09-08 08:09:11.170 #033[31merror#033[39m: Cannot install application. {
Sep  8 08:09:11 localhost peertube[27202]:   "err": {
Sep  8 08:09:11 localhost peertube[27202]:     "stack": "Error: ENOENT: no such file or directory, mkdir",
Sep  8 08:09:11 localhost peertube[27202]:     "message": "ENOENT: no such file or directory, mkdir",
Sep  8 08:09:11 localhost peertube[27202]:     "errno": -2,
Sep  8 08:09:11 localhost peertube[27202]:     "code": "ENOENT",
Sep  8 08:09:11 localhost peertube[27202]:     "syscall": "mkdir"
Sep  8 08:09:11 localhost peertube[27202]:   }
Sep  8 08:09:11 localhost peertube[27202]: }
Sep  8 08:09:11 localhost peertube[27202]: npm ERR! code ELIFECYCLE
Sep  8 08:09:11 localhost peertube[27202]: npm ERR! errno 255
Sep  8 08:09:11 localhost peertube[27202]: npm ERR! peertube@2.3.0 start: `node dist/server`
Sep  8 08:09:11 localhost peertube[27202]: npm ERR! Exit status 255
Sep  8 08:09:11 localhost peertube[27202]: npm ERR!
Sep  Sep  8 10:29:00 localhost peertube[8260]: [video.gulutube.com:443] 2020-09-08 10:29:00.159 #033[33mwarn#033[39m: Emailer is disabled so the contact form will not work.
Sep  8 10:29:01 localhost peertube[8260]: [video.gulutube.com:443] 2020-09-08 10:29:01.288 #033[32minfo#033[39m: Database peertube_prod is ready.
Sep  8 10:29:01 localhost CRON[8309]: (root) CMD (/usr/local/qcloud/stargate/admin/start.sh > /dev/null 2>&1 &)
Sep  8 10:29:04 localhost peertube[8260]: [video.gulutube.com:443] 2020-09-08 10:29:04.171 #033[31merror#033[39m: Cannot use SMTP server because of lack of configuration. PeerTube will not be able to send mails!
Sep  8 10:29:04 localhost peertube[8260]: [video.gulutube.com:443] 2020-09-08 10:29:04.194 #033[32minfo#033[39m: Cleaning HTML cache.
Sep  8 10:29:04 localhost peertube[8260]: [video.gulutube.com:443] 2020-09-08 10:29:04.243 #033[31merror#033[39m: Cannot add repeatable job. {
Sep  8 10:29:04 localhost peertube[8260]:   "err": {
Sep  8 10:29:04 localhost peertube[8260]:     "stack": "ReplyError: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.\n    at parseError (/var/www/peertube/versions/peertube-v2.3.0/node_modules/redis-parser/lib/parser.js:179:12)\n    at parseType (/var/www/peertube/versions/peertube-v2.3.0/node_modules/redis-parser/lib/parser.js:302:14)",
Sep  8 10:29:04 localhost peertube[8260]:     "message": "MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.",
Sep  8 10:29:04 localhost peertube[8260]:     "command": {
Sep  8 10:29:04 localhost peertube[8260]:       "name": "zadd",
Sep  8 10:29:04 localhost peertube[8260]:       "args": [
Sep  8 10:29:04 localhost peertube[8260]:         "bull-video.gulutube.com:videos-views:repeat",
Sep  8 10:29:04 localhost peertube[8260]:         "1599534060000",
Sep  8 10:29:04 localhost peertube[8260]:         "__default__::::1 * * * *"
Sep  8 10:29:04 localhost peertube[8260]:       ]
Sep  8 10:29:04 localhost peertube[8260]:     }
Sep  8 10:29:04 localhost peertube[8260]:   }
Sep  8 10:29:04 localhost peertube[8260]: }

**Comment by Chocobozzz** [comment]
You have an issue with your redis configuration:

```
MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
```

**Comment by chengjingfeng** [comment]
the sever log the error message again and again, finally the server is lower disk.

**Comment by chengjingfeng** [comment]
I will correct the Redis configuration. but we should not log the error message again and again it will cause the server lower disk and down

**Comment by chengjingfeng** [comment]
thanks @Chocobozzz , how can i disable the log?

**Comment by chengjingfeng** [comment]
> You have an issue with your redis configuration:
> 
> ```
> MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
> ```

this is cause by server lack of disk space.
