### ISSUE TITLE
Graceful shutdown feature

### ISSUE THREAD

**Issue by techied** [Chocobozzz/PeerTube#3147]
A option to shut down the PeerTube sever gracefully. On a larger instance, there can sometimes be a few videos in the transcoding queue, and stopping the server for an update or configuration reload can cause this queue to get lost, or for other odd quirks to surface.

So basically, the graceful shutdown would shutdown the server at a good time between jobs in the transcoding queue, and when PeerTube is started again, it will pick back up in the queue where it left off.

**Comment by Chocobozzz** [comment]
Hello,

PeerTube should restart transcoding jobs that were not finished on restart

**Comment by techied** [comment]
In that case, nevermind!
