### ISSUE TITLE
Logs leave no space on server

### ISSUE THREAD

**Issue by chengjingfeng** [Chocobozzz/PeerTube#3149]
**What happened?**
server run out of space

**What do you expect to happen instead?**
should not run out of space

**Steps to reproduce:**

1. install a new ubuntu server

2. install peertube by follow production guideline 

3. after install server run was well

4. after hours or days the server will be no space left because of full of logs

**Additional information**
* PeerTube version or URL: 2.1.1 and 2.3.0 both produce the same issue

regards
chengjing

**Comment by chengjingfeng** [comment]
I think that should be something wrong by my installation since no one else reproduce the same issue. but I did not find what is wrong. hope someone can help to figure  it out.

**Comment by chengjingfeng** [comment]
instant url https://video.haidaixia.net

**Comment by chengjingfeng** [comment]
I guess it cause by：
1. peertube server got some issue during transcode the videos and crash；
2. ubuntu system daemon service to restart the peertube server；
3. peertube server transcode the videos jod resume and fail again, and peertube server ceash again.
4. again and again the log file size increase.


l just comment the log output to check it
![Jietu20200910-145816](https://user-images.githubusercontent.com/8434766/92694258-5de36f00-f379-11ea-8f2e-2fc6cc758b3b.jpg)

**Comment by chengjingfeng** [comment]
there is a delayed job:
![Jietu20200910-154336](https://user-images.githubusercontent.com/8434766/92696469-81f47f80-f37c-11ea-8fbb-d9863b5bc5a2.jpg)

**Comment by rigelk** [comment]
Hi @chengjingfeng,

You should tweak the [`logs.rotation`](https://github.com/Chocobozzz/PeerTube/blob/7d48ea83bedc64f757510ee247270eec44067a3a/config/default.yaml#L97-L100) in your configuration so that the rotated logs fit the space available on your server.
