### ISSUE TITLE
Portrait video thumbnail and resolution

### ISSUE THREAD

**Issue by valvin1** [Chocobozzz/PeerTube#315]
* **PeerTube version or commit:** 0.0.28-alpha
* **Browser name/version:** : Firefox 58.0.2 Xubuntu 16.04
* **NodeJS version:** 8.9.4
* **PostgreSQL version:** 9.5

* **What is the expected behaviour?**
  * Thumbnail video is in portrait like the video.
  * Resolution for a 1080x1920 video is 1080p 

* **What do you see instead?**
  * Thumnail video is streched to a landscape picture
  * Resolution for a 1080x1920 video is 1920p

Example : 

![](https://framapic.org/pkBA5P3v8aVY/phcuzYmXS9A4)

![](https://framapic.org/0yTJxYxob1nO/ORXDE9chKDtP)

**Comment by Chocobozzz** [comment]
Fixed: https://github.com/Chocobozzz/PeerTube/commit/056aa7f2b4de1ef128a5fd35527de6dd7a9ebad1

The thumbnail is still in landscape mode but we keep the ratio. I don't think having a thumbnail with black borders would be a good idea but if you want to discuss about that don't hesitate to open another issue ;)

**Comment by valvin1** [comment]
I've just upgraded in the latest version. I was checking the issue but previous uploaded video are not updated. I mean thumnail are still in stretch mode. Is it the normal behaviour ?

**Comment by Chocobozzz** [comment]
We don't update old thumbnails, you need to reupload the video or update manually the thumbnail.
