### ISSUE TITLE
Missing checkbox when uploading file

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#3153]
If I load a .MP4 file, then everything is fine, the checkbox is present.

**Publish after transcoding**

![Add MP4](https://user-images.githubusercontent.com/11453567/92921175-4325fe80-f43c-11ea-80ff-2e6e1a43b0d4.JPG)
But if I upload a file in .AVI format, then this checkbox is missing.

Is this a bug in version 2.4.0 or was it done on purpose?

**Comment by JohnXLivingston** [comment]
I think that it is because mp4 can be compatible with web browsers, and AVI not. So for AVI, you have to wait for transcoding to publish (and the checkbox is no more needed because it is not optional). 
Perhaps displaying a disabled checked checkbox would be more easy to understand?

**Comment by Alterak** [comment]
> I think that it is because mp4 can be compatible with web browsers, and AVI not. So for AVI, you have to wait for transcoding to publish (and the checkbox is no more needed because it is not optional).
> Perhaps displaying a disabled checked checkbox would be more easy to understand?

It seems to me that this has nothing to do with browser compatibility. It's just that in all previous versions this function was available for any format.

**Comment by rigelk** [comment]
> It seems to me that this has nothing to do with browser compatibility

It does. Safari doesn't natively support AVI files. The option should appear greyed-out though :thinking:

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/ddb62a85c5517d3437feb7d487a8a11881b68fcb
