### ISSUE TITLE
Invalid client: client is invalid

### ISSUE THREAD

**Issue by TsymbalArtem** [Chocobozzz/PeerTube#3155]
Hello, I am running Peertube in the Docker, but when I open website, I getting this error: 
**Error Cannot retrieve OAuth Client credentials:  Ensure you have correctly configured PeerTube (config/ directory), in particular the "webserver" section.**. 
After that, when I login, I get **Invalid client: client is invalid**

**My docker-compose file:** 
version: "3.3"

services:
  peertube:
    #If you don't want to use the official image and build one from sources
    build:
      context: .
      dockerfile: ./support/docker/production/Dockerfile.buster
    #image: chocobozzz/peertube:production-buster
    env_file:
      - .env
    #Traefik labels are suggested as an example for people using Traefik,
    #remove them if you are using another reverse proxy.
 #labels:
 #traefik.enable: "true"
 #traefik.frontend.rule: "Host:${PEERTUBE_WEBSERVER_HOSTNAME}"
 #traefik.port: "9000"
    #If you don't want to use a reverse proxy (not suitable for production!)
    ports:
      - "80:9000"
    volumes:
      - ./docker-volume/data:/data
      - ./docker-volume/config:/config
    depends_on:
      - postgres
      - redis
      - postfix
    restart: "always"

  postgres:
    image: postgres:10-alpine
    env_file:
      - .env
    volumes:
      - ./docker-volume/db:/var/lib/postgresql/data
    restart: "always"
    labels:
      traefik.enable: "false"

  redis:
    image: redis:4-alpine
    volumes:
      - ./docker-volume/redis:/data
    restart: "always"
    labels:
      traefik.enable: "false"

  postfix:
    image: mwader/postfix-relay
    env_file:
      - .env
    volumes:
      - ./docker-volume/opendkim/keys:/etc/opendkim/keys
    labels:
      traefik.enable: "false"
    restart: "always"

networks:
  default:
    ipam:
      driver: default
      config:
      - subnet:  172.02.30.0/16
**My .env file:**
POSTGRES_USER=peertube
POSTGRES_PASSWORD=peertube
POSTGRES_DB=peertube
PEERTUBE_DB_USERNAME=peertube
PEERTUBE_DB_PASSWORD=peertube
#PEERTUBE_DB_HOSTNAME is the Postgres service name in docker-compose.yml
PEERTUBE_DB_HOSTNAME=postgres
PEERTUBE_WEBSERVER_HOSTNAME=127.0.0.1
PEERTUBE_WEBSERVER_PORT=443
PEERTUBE_WEBSERVER_HTTPS=true
#If you need more than one IP as trust_proxy
#pass them as a comma separated array:
PEERTUBE_TRUST_PROXY=["127.0.0.1", "loopback", "172.18.0.0/16"]
#PEERTUBE_SMTP_USERNAME=
#PEERTUBE_SMTP_PASSWORD=
#PEERTUBE_SMTP_HOSTNAME=postfix
#PEERTUBE_SMTP_PORT=25
#PEERTUBE_SMTP_FROM=noreply@<MY DOMAIN>
#PEERTUBE_SMTP_TLS=false
#PEERTUBE_SMTP_DISABLE_STARTTLS=false
PEERTUBE_ADMIN_EMAIL=admin@domain.ltd
POSTFIX_myhostname=domain.ltd
#If you need to generate a list of sub/DOMAIN keys
#pass them as a whitespace separated string <DOMAIN>=<selector>
#OPENDKIM_DOMAINS=<MY DOMAIN>=peertube
#TRAEFIK_ACME_EMAIL=<MY EMAIL ADDRESS>
#If you need to obtain ACME certificates for more than one DOMAIN
#pass them as a comma separated string
#TRAEFIK_ACME_DOMAINS=<MY DOMAIN>
#/!\ Prefer to use the PeerTube admin interface to set the following configurations /!\
PEERTUBE_SIGNUP_ENABLED=true
PEERTUBE_TRANSCODING_ENABLED=true
#PEERTUBE_CONTACT_FORM_ENABLED=true
PEERTUBE_REDIS_HOSTNAME=redis

**Comment by dev1983** [comment]
hello 
Did you find any solution for login ? and above error

**Comment by themadhacker222** [comment]
set webserver to public Ip or hostname you access the server with
