### ISSUE TITLE
Brave browser embed not working

### ISSUE THREAD

**Issue by filmaidykai** [Chocobozzz/PeerTube#3156]
Hey so after update in to 2.4.0 embed links not working anymore in my web page its showing just black screen yea if im using in to new tab brave can load a video but just in new tab and im using latest brave version so Im not sure its brave problem or iframe problem from peertube because I test it with google chrome firefox safari opera everything working perfectly just with brave come with problem

![unknown-19](https://user-images.githubusercontent.com/33236264/93225602-4ede3180-f76a-11ea-8809-47d69f4de03d.png)

**Comment by rigelk** [comment]
Are you blocking scripts somehow ?

**Comment by Nojus741** [comment]
> Are you blocking scripts from third party domains somehow ?

Fresh install of Brave browser I also have tried on multiple machines the browsers for some reasons blocks peertube embed.

**Comment by scanlime** [comment]
i am losing count of the number of ways brave has been breaking sites... is it a browser or malware

**Comment by ryanbr** [comment]
@filmaidykai @Nojus741  @scanlime 

Due to blocking 3rd-party cookies it's blocked in Brave. I've created an issue report for it. On the selected pages, allowing all cookies from shields will help here.

**Comment by antonok-edm** [comment]
@rigelk Could you shed some light on why the player requires third-party cookies to function?

**Comment by rigelk** [comment]
@antonok-edm it doesn't.

**Comment by antonok-edm** [comment]
@rigelk thanks, actually it looks like you've even created a fake proxied storage [in the case where access to `localStorage` throws an exception](https://github.com/Chocobozzz/PeerTube/blob/a4ff3100d36f2fe9a4dfc00e8487c28a94433c4f/client/src/root-helpers/peertube-web-storage.ts#L70), which is awesome.

The way 3rd-party storage is blocked in Brave is by setting `localStorage` to `null` - which actually _doesn't_ end up triggering the `catch` case. My understanding is that both the exception and `null` approach caused some webcompat issues, but `null` was selected as it broke in fewer instances.

It looks to me like the embedded players could be fixed for Brave users by also checking for `null` here. There is [ongoing work](https://github.com/brave/brave-core/pull/6560) in Brave to make a similar proxied storage implementation transparently available to all sites, but it looks like that's still as-of-yet unmerged.

**Comment by rigelk** [comment]
@antonok-edm thanks for your investigation into that problem which sounds like a quick circumvention can be done on our part. It would be nice if Brave were to behave similarly as other browsers on such common browser APIs in the future, though…

**Comment by rebelcode-xr** [comment]
@ryanbr in case the video is not loaded properly, what about showing a message instead of a black square? Something like "video cannot be loaded, might be your ad-blocker or another browser extension, try disable it". So users could investigate instead of thinking that the video is just broken.

**Comment by ryanbr** [comment]
Not really a good idea (for video, or general blocks), displaying a message everytime an item or video is block would cause display issues for some users. (and no doubt people would complain on how to turn this off, and why it should be the default etc) 

No adblocker I'm aware of will display a text message of video being blocked

**Comment by rebelcode-xr** [comment]
so the only solution is Brave fixing it? 🤔

**Comment by Chocobozzz** [comment]
Hi,

PeerTube v3 should work with brave
