### ISSUE TITLE
install peertube on centos 8 has problem,does anybody knows what's going on?

### ISSUE THREAD

**Issue by FunnyRyan** [Chocobozzz/PeerTube#3158]
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "http-signature@1.3.4" is incompatible with requested version "http-signature@~1.2.0"
warning Resolution field "oauth2-server@3.1.0-beta.1" is incompatible with requested version "oauth2-server@3.0.0"
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.                    
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @typescript-eslint/eslint-plugin@3.10.0" has unmet peer dependency "@typescript-eslint/parser@^3.0.0".
warning " > marked-man@0.7.0" has incorrect peer dependency "marked@^0.7.0".
[5/5] Building fresh packages...                                                               
$ test -n "$NOCLIENT" || (cd client && yarn install --pure-lockfile)
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.                    
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...                                                                  
warning " > file-loader@6.0.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > raw-loader@4.0.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > @ngx-i18nsupport/tooling@8.0.3" has incorrect peer dependency "@angular/common@^8.0.0".
warning " > @ngx-i18nsupport/tooling@8.0.3" has incorrect peer dependency "@angular/core@^8.0.0".
warning " > @ngx-loading-bar/http-client@5.1.0" has incorrect peer dependency "tslib@^1.10.0".
warning " > @ngx-loading-bar/router@5.1.0" has incorrect peer dependency "tslib@^1.10.0".
warning " > @ngx-meta/core@9.0.0" has incorrect peer dependency "@angular/core@>=9.0.0 <10.0.0".
warning " > @ngx-meta/core@9.0.0" has incorrect peer dependency "@angular/platform-browser@>=9.0.0 <10.0.0".
warning " > @ngx-meta/core@9.0.0" has incorrect peer dependency "@angular/platform-browser-dynamic@>=9.0.0 <10.0.0".
warning " > @ngx-meta/core@9.0.0" has incorrect peer dependency "@angular/router@>=9.0.0 <10.0.0".
warning " > @ngx-meta/core@9.0.0" has incorrect peer dependency "tslib@^1.10.0".
warning " > angular2-hotkeys@2.2.0" has incorrect peer dependency "@angular/core@^5.2.0 || ^6.0.0 || ^7.0.0 || ^8.0.0 || ^9.0.0".
warning " > angular2-hotkeys@2.2.0" has incorrect peer dependency "tslib@^1.10.0".
warning " > bootstrap@4.5.2" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.5.2" has unmet peer dependency "popper.js@^1.16.1".
warning " > css-loader@3.6.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > extract-text-webpack-plugin@4.0.0-beta.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
warning " > html-loader@1.2.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > html-webpack-plugin@4.3.0" has unmet peer dependency "webpack@>=4.0.0 < 6.0.0".
warning " > linkifyjs@2.1.9" has unmet peer dependency "jquery@>= 1.11.0".
warning " > linkifyjs@2.1.9" has unmet peer dependency "react@>= 0.14.0".
warning " > linkifyjs@2.1.9" has unmet peer dependency "react-dom@>= 0.14.0".
warning " > primeng@9.1.3" has incorrect peer dependency "@angular/core@^7.0.0 || ^8.0.0 || ^9.0.0".
warning " > primeng@9.1.3" has incorrect peer dependency "@angular/common@^7.0.0 || ^8.0.0 || ^9.0.0".
warning " > primeng@9.1.3" has incorrect peer dependency "@angular/forms@^7.0.0 || ^8.0.0 || ^9.0.0".
warning " > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
warning "sass-resources-loader > @babel/cli@7.10.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "sass-resources-loader > babel-eslint@10.1.0" has unmet peer dependency "eslint@>= 4.12.1".
warning " > terser-webpack-plugin@3.1.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "tslint-config-standard > tslint-eslint-rules@5.4.0" has incorrect peer dependency "tslint@^5.0.0".
warning " > webpack-cli@3.3.12" has unmet peer dependency "webpack@4.x.x".

**Comment by FunnyRyan** [comment]
[root@NC-PH-0978-24 peertube-latest]# sudo dnf update
Last metadata expiration check: 0:34:42 ago on Wed 16 Sep 2020 07:56:10 AM GMT.
Dependencies resolved.
Nothing to do.
Complete!
[root@NC-PH-0978-24 peertube-latest]# sudo  yum update
Last metadata expiration check: 0:34:55 ago on Wed 16 Sep 2020 07:56:10 AM GMT.
Dependencies resolved.
Nothing to do.
Complete!
[root@NC-PH-0978-24 peertube-latest]# sudo yum install epel-release
Last metadata expiration check: 0:35:10 ago on Wed 16 Sep 2020 07:56:10 AM GMT.
Package epel-release-8-8.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[root@NC-PH-0978-24 peertube-latest]# sudo yum update
Last metadata expiration check: 0:35:32 ago on Wed 16 Sep 2020 07:56:10 AM GMT.
Dependencies resolved.
Nothing to do.
Complete!

**Comment by frankstrater** [comment]
If you mean all the Yarn warnings, you can ignore those. From what I understand about it, it's a Yarn problem and it will be fixed there eventually in a next version.
