### ISSUE TITLE
Keep full screen on a playlist

### ISSUE THREAD

**Issue by MensoifG** [Chocobozzz/PeerTube#3159]
Hello,
When I play a playlist on PeerTube and want to watch it full screen the first video is full screen, but the next one resets to small screen. And I have to reset every video to full screen. I can't figure out how to make the whole playlist stay full screen.
Too bad for video clips, for example, that I cannot watch on my TV with a Chromecast without having to return to the computer to each clip to put it in full screen.
If anyone has a solution, thank you in advance.

Salut,
Quand je lit une liste de lecture sur PeerTube et que je veux la regarder en plein écran la première vidéo est en plein écran, mais la suivante se remet en petit écran. Et je suis obligé de remettre à chaque vidéo le plein écran. Je ne trouve pas comment faire pour que toute la liste de lecture reste en plein écran.
Dommage pour les clips vidéo par exemple que je ne puisse regarder sur ma télé avec une Chromecast sans devoir à chaque clip être obliger de retourner sur l’ordi pour mettre en plein écran.
Si une personne a une solution merci d’avance.

**Comment by vmario89** [comment]
would be happy to see this feature - could be useful for kiosk configured devices

**Comment by Chocobozzz** [comment]
Hi,

This should be fixed by https://github.com/Chocobozzz/PeerTube/commit/63e2f087c3410206aa294df8099b005e615592e5

**Comment by vmario89** [comment]
sadly the update to 5.2.1 did not change the behaviour. tested it in firefox and chromium. The player still stoßs fullscreen once a video played and the next is going to start

btw. for me it depends to a general feature request https://github.com/Chocobozzz/PeerTube/issues/5813: play a playlist in fullscreen (and keep it so) and run infinite loop

**Comment by Chocobozzz** [comment]
This feature will be included in v6 and was not in 5.2.1 :)
