### ISSUE TITLE
audio quality

### ISSUE THREAD

**Issue by mohibo** [Chocobozzz/PeerTube#3160]
at which audio quality are you transcoding a 320 kpbs mp3?

**Comment by rigelk** [comment]
You can find answers in [server/helpers/ffmpeg-utils.ts#L57-L73](https://github.com/Chocobozzz/PeerTube/blob/7d48ea83bedc64f757510ee247270eec44067a3a/server/helpers/ffmpeg-utils.ts#L57-L73).

**Comment by mohibo** [comment]
i couldn't understand a thing of this list

**Comment by mohibo** [comment]
i forgot to tell youthat im not using the client,but im using the website

**Comment by rigelk** [comment]
It means a 320kbit mp3 audio source will keep the same bitrate.

**Comment by mohibo** [comment]
w

> 
> 
> It means a 320kbit mp3 audio source will keep the same bitrate.

well i uploaded a 320 kbit mp3 but it transcoded at 128 aac

**Comment by rigelk** [comment]
did you upload it as audio-only or was it contained within a video container?

**Comment by mohibo** [comment]
> 
> 
> did you upload it as audio-only or was it contained within a video container?

audio only

**Comment by mohibo** [comment]
hello,anybody here?

**Comment by mohibo** [comment]
what now?what i can do?

**Comment by mohibo** [comment]
why you don't answer?

**Comment by rigelk** [comment]
Please be patient, I'll check the part of the code responsible for this soon.

Likely, we force audio-only uploads to aac 128kbit/s and that's it.
