### ISSUE TITLE
Show transcoding failures to the users (or at least uploader)

### ISSUE THREAD

**Issue by monnier** [Chocobozzz/PeerTube#3162]
I recently had problems uploading videos to our peertube instance, where the videos would stay in "Waiting transcoding" indefinitely.  After contacting my sysadmin it turned out the transcoding had failed with "Too many packets buffered for output stream".

I'd have preferred to see this error indication without having to contact my sysadmin.

I think this would fit also within #2477 (except that was closed as a duplicate of #799, which focuses on the "time to completion" which I'd also like to see, but here I'm focusing on the issue of reporting failures)

**Steps to reproduce:**

1. Download a problematic video such as the one at https://classe.iro.umontreal.ca/videos/watch/b039642b-68e5-48ef-a420-095210787db2
2. Try to upload it

3. See that transcoding seems never to finish whereas in reality it just fails

**Additional information**
* PeerTube version or URL: https://classe.iro.umontreal.ca/
* Browser name/version: Firefox from Debian testing
* NodeJS version: no idea

* Link to browser console log if useful:
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by kenshin33** [comment]
said sysadmin agrees with the above!

**Comment by Chocobozzz** [comment]
Hello,

We now display an error message on transcoding failure.

**Comment by monnier** [comment]
Chocobozzz [2022-08-04 00:54:03] wrote:
> We now display an error message on transcoding failure.

Yay!  Thanks!
