### ISSUE TITLE
Size is displayed incorrectly

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#3163]
In the Description of the instance, in the Statistics section, the total size of the loaded data is not displayed correctly
My server only shows 1GB
![gb1](https://user-images.githubusercontent.com/11453567/93591457-15e7cc00-f9b9-11ea-9bea-51281e77e621.PNG)

But the overall size is much larger. For example, only one user has more than 147 GB loaded, and the total size should be more than 200GB.
![gb2](https://user-images.githubusercontent.com/11453567/93591665-724aeb80-f9b9-11ea-9502-e32fcd675fc4.PNG)

Peertube Ver. 2.4.0.

**Comment by Alterak** [comment]
Perhaps this is due to the fact that the data disk is connected via NFS? Doesn't anyone know the solution? On other instances I've seen the same problem ... a lot of local videos, but very small size displayed.

**Comment by Chocobozzz** [comment]
Please paste the URL of your instance

**Comment by Alterak** [comment]
> Please paste the URL of your instance

https://peervideo.ru

**Comment by Chocobozzz** [comment]
Thanks, it seems we don't take into account HLS files in our SQL query.

**Comment by Alterak** [comment]
Very strange, now almost all videos are in HLS. Then it's really a bug

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/0b84383d488facc321b100f3280a872ee53e888b
