### ISSUE TITLE
Error on CLI video Import: "ENOENT: no such file or directory,"

### ISSUE THREAD

**Issue by DissidentDev** [Chocobozzz/PeerTube#3165]
_I don't post on GitHub often so forgive me._

Any help with this would be much appreciated:

I again, attempted to **import** the contents of a **YouTube channel**/individual video to my PeerTube instance. It has correctly noticed in all cases what content I had already uploaded manually and how many more total videos remaining it would add (60) and then went on to download the first missing video and this is where a problem starts. 

**Steps to reproduce:**

1. Clone Git to user home folder "PeerTube" and Install CLI as sudo user - yarn 1.22.5 and node v10.22.1

2. Add auth user to my server

3. Setup alias and run node command as sudo user: peertube import-videos --target-url "youtubeurl"

**Some other notes:**

I've tried this on multiple VPS servers and it has not worked as well as locally on the same server as the PeerTube host. Have tried installing and running as root user also
I note that in each case it downloads the files and that they are playable but the name of the video files ends  in .f136 and the other file ends in .mp4.f140 (these numbers change)

Otherwise the names are identical to the file it is searching for as far as I can tell.

**Here is a paste of the logfile:**

`Uploading on PeerTube video "Example YouTube Video".
[localhost:9000] 2020-09-18 17:02:46.866 error: uncaughtException: ENOENT: no such file or directory, open '/home/ubuntu/PeerTube/dist/server/tools/56453f73011f4b5499306f970cbba79de4bdd349cf933c42260ed87ac1d4e462.mp4'
Error: ENOENT: no such file or directory, open '/home/ubuntu/PeerTube/dist/server/tools/56453f73011f4b5499306f970cbba79de4bdd349cf933c42260ed87ac1d4e462.mp4' {
  "error": {
    "stack": "Error: ENOENT: no such file or directory, open '/home/ubuntu/PeerTube/dist/server/tools/56453f73011f4b5499306f970cbba79de4bdd349cf933c42260ed87ac1d4e462.mp4'",
    "message": "ENOENT: no such file or directory, open '/home/ubuntu/PeerTube/dist/server/tools/56453f73011f4b5499306f970cbba79de4bdd349cf933c42260ed87ac1d4e462.mp4'",
    "errno": -2,
    "code": "ENOENT",
    "syscall": "open",
    "path": "/home/ubuntu/PeerTube/dist/server/tools/56453f73011f4b5499306f970cbba79de4bdd349cf933c42260ed87ac1d4e462.mp4"
  },
  "stack": "Error: ENOENT: no such file or directory, open '/home/ubuntu/PeerTube/dist/server/tools/56453f73011f4b5499306f970cbba79de4bdd349cf933c42260ed87ac1d4e462.mp4'",
  "exception": true,
  "date": "Fri Sep 18 2020 17:02:46 GMT+0000 (Coordinated Universal Time)",
  "process": {
    "pid": 4759,
    "uid": 0,
    "gid": 0,
    "cwd": "/home/ubuntu/PeerTube",
    "execPath": "/usr/bin/node",
    "version": "v10.22.1",
    "argv": [
      "/usr/bin/node",
      "/home/ubuntu/PeerTube/dist/server/tools/peertube-import-videos.js",
      "--target-url",
      "youtubeurl"
    ],
    "memoryUsage": {
      "rss": 102899712,
      "heapTotal": 73277440,
      "heapUsed": 37730920,
      "external": 1038844
    }
  },
  "os": {
    "loadavg": [
      0.26708984375,
      0.10595703125,
      0.064453125
    ],
    "uptime": 3350
  },
  "trace": []
}
socket hang up
`

**Comment by jimgroom** [comment]
I am getting an almost identical error, have you had any luck figuring this out? I was able to confirm someone else who has the CLI tool working could upload to my account, so I am thinking it is something with the Node/Yarn setup, but would love to hear if you made any progress on this.

**Comment by jimgroom** [comment]
This was linked to no having ffmpeg installed on my local machine I am using for the CLI [face palm].

**Comment by DissidentDev** [comment]
> 
> 
> This was linked to no having ffmpeg installed on my local machine I am using for the CLI [face palm].

Excellent find, thanks for sharing the fix!

I had moved on to focus in other things after doing it in the tedious and manual way. I'm using the Docker image so I had probably incorrectly assumed that it came with everything I needed.
I shall try this fix next time I attempt an import and see if it works.

**Comment by Chocobozzz** [comment]
@DissidentDev Hi, does it work now? :)

**Comment by DissidentDev** [comment]
I haven't had the need/opportunity to test it but when I do I will make sure to let everyone here know :)
