### ISSUE TITLE
Show number of comments on a video on thumbnail

### ISSUE THREAD

**Issue by TILvids** [Chocobozzz/PeerTube#3166]
I'm trying to track comments on my instance, and it's really hard to do. One thing that might be nice is to expose the number of comments a given video has at a higher level, such as on the thumbnail for different views (Recent, Trending, etc.) I made a mockup to show what that might look like (you can see this on the "The History of Mozilla Firefox" thumbnail).

![peertube-comments-example](https://user-images.githubusercontent.com/69435791/93714197-14d8ab00-fb2f-11ea-9e6c-eb80b7af8321.png)

Thanks for considering!

**Comment by Chocobozzz** [comment]
Hello,

https://github.com/Chocobozzz/PeerTube/issues/492 and https://github.com/Chocobozzz/PeerTube/issues/2736 should address your issue.
