### ISSUE TITLE
Unclear visitor call to action when trying to like a video

### ISSUE THREAD

**Issue by Avamander** [Chocobozzz/PeerTube#3167]
**What happened?**

Bad translation in the UI that makes no sense.

![image](https://user-images.githubusercontent.com/5392141/93714499-c269af80-fb6b-11ea-9fdf-bd3fef0a366a.png)

**What do you expect to happen instead?**

It displays something useful, currently it's absolutely unclear what the user did wrong. Connected to what? Makes no sense.

**Steps to reproduce:**

1. Just try to like a video

**Additional information**
* PeerTube example video: https://video.codingfield.com/videos/watch/9bb4cd12-50fb-41a3-adb1-4f53a9a6d533
* Browser name/version: All of them

**Comment by test2a** [comment]
it should say "you should be logged in to rate this content." should i go ahead with changing it? @rigelk  what do you think?

**Comment by rigelk** [comment]
@test2a yes, and add a link for the action in the message.

Also, if you could verify if other occurrences of the problem exist in the code to correct it, that would be great!
