### ISSUE TITLE
Update a public/unlisted video to private

### ISSUE THREAD

**Issue by Bevito** [Chocobozzz/PeerTube#317]
Hi, 

I think I found a bug in video privacy selection.

* **PeerTube version or commit:**
v0.0.29-alpha
* **Browser name/version:**
Mozilla Firefox ESR 52.6.0 (64 bits) (Linux)
* **NodeJS version:**
8.9.4-1nodesource1  (Debian Stretch)
* **PostgreSQL version:**
9.6+181+deb9u1 (Debian Stretch)
* **What is the expected behaviour?**
When you update privacy option on a video, you should be able to select 'Public', 'Private', 'Unlisted'.
* **What do you see instead?**
When you want to update privacy option on a video, the 'Private' option is missing (you can only select 'Public' or 'Unlisted'.
If you update a 'Private' video to 'Public', than, you can't put it back to 'Private'.

If you need any other informations, let me know.

Thanks a lot.

**Comment by Chocobozzz** [comment]
Hi @Bevito, thanks for your report!

In fact it was an intended behaviour: when you publish your video in public/unlisted privacy it is sent to all your instance followers. In private privacy the video is kept on your instance. So for me when a video was sent out, there was nothing we could do about it.

But on second thought I think that if the user want to put its video in private privacy we could:
 * Send a remove activity to followers so they delete the video
 * Put the video in private privacy selection in our local database

**Comment by stom79** [comment]
I second that demand. I noticed that code:

https://github.com/Chocobozzz/PeerTube/blob/babecc3c09cd4ed06fe643a97fff4bcc31c5a9be/server/middlewares/validators/videos/videos.ts#L119-L123

Is it still possible to?

>- Send a remove activity to followers so they delete the video
>- Put the video in private privacy selection in our local database

Also, maybe apply something for disabling comments (for auto-removing previous public comments that were posted.)

**Comment by Chocobozzz** [comment]
@stom79 Yep, it's how I envisage to implement this

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/851f5daa1eec66e1faa3c45238ec9ab91be05b00 & https://github.com/Chocobozzz/PeerTube/commit/1b319b7aa6d2f4252615b370aaca6a800be1b1f4
