### ISSUE TITLE
telegram does not show inline videos

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3170]
**What happened?**
sharing video link on telegram shows the video link and thumbnail instead of resolving the video and playing it inline like youtube videos play. 
**What do you expect to happen instead?**
sharing youtube videos in telegram resolves the video and inline player plays it without going to the browser.

**Comment by test2a** [comment]
![Screenshot_20200921-182510_1](https://user-images.githubusercontent.com/39449563/93769181-14780700-fc38-11ea-9512-abcae8badd7c.png)

**Comment by test2a** [comment]
i dont know if the issue is on peertube side or on telegram side that they dont understand peertube website. I am posting it here and will try to post on telegram also just in case

**Comment by rigelk** [comment]
Telegram has extra code to deal with YouTube embeds. There is nothing we can do there.

**Comment by sashagra** [comment]
> Telegram has extra code to deal with YouTube embeds. There is nothing we can do there.

i think there is some API in tegram to solve this issue. Vimeo and dailymotion videos has play inline
