### ISSUE TITLE
add a "Donate to Server Admins" button in the /about/instance page, next to the "Contact Administrator" button

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#3171]
add a "Donate to Server Admins" button in the `/about/instance` page, next to the "Contact Administrator" button

**Comment by TILvids** [comment]
I'd support this. I'm sort of left to copying/pasting my Patreon link sort of wherever on the site (link on the About page, plug-in link on the left, etc).

**Comment by Chocobozzz** [comment]
With https://docs.joinpeertube.org/api-custom-client-markup, you can add a custom peertube button link in the description field of your instance.
