### ISSUE TITLE
Show the exact number of views when hovering over 20k views, 1k views etc..

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#3173]
Show the exact number of views when hovering over 20k views or 1k views etc..

**Comment by tanguybernard** [comment]
Hello, I'm new here and I would like to take this issue if it's possible ?

**Comment by tanguybernard** [comment]
> Show the exact number of views when hovering over 20k views or 1k views etc..

Hello, I'm new here and I would like to take this issue if it's possible ?

**Comment by rigelk** [comment]
@tanguybernard yes, definitely

**Comment by Poslovitch** [comment]
I'm wondering. Isn't this duplicating #2147 ?

**Comment by tanguybernard** [comment]
@Poslovitch Yes seems a duplication.

I was going to add a `title` into `video-watch.component.html` too :)

**Comment by tanguybernard** [comment]
I made a commit on the forked project, I'm not sure of the exact answer.

15K => title must be for example `15300` or `15300 views`
On the second case, Im not sure about the translation works with my code.

If you can help me :)
