### ISSUE TITLE
Option to disable WebTorrent on player embed

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#3174]
Is it possible for an anonymous user to disable WebTorrent when viewing a video [*EDIT*: through the embedded player]? (without creating an account)

If not, could it be possible to implement that feature? (although not exactly sure, but probably that GDPR would require that)

Thanks :)
PS: My message is very short, don't hesitate to ask for more details if I am not clear enough.

**Comment by rigelk** [comment]
You can do that in the settings modal, accessible from the left menu panel.

![Screenshot_2020-09-23 Trending videos - PeerTube](https://user-images.githubusercontent.com/6329880/94038476-c47b7a80-fdc6-11ea-806f-74ead40c577f.png)

**Comment by fflorent** [comment]
Thanks for your answer @rigelk ! 

I have not expressed exactly my need and I apologize for that: my need not only was about anonymous people while visiting the PeerTube instance but also for people viewing videos using an embedded player (on social media, websites, etc.).

I think that this option is not available through the video parameters (at least on version 2.3, I have not migrated to version 2.4 yet)

![image](https://user-images.githubusercontent.com/371705/94048091-440f4680-fdd3-11ea-84fd-443a3dce1977.png)

If you agree with that, may I request to reopen the issue? I may edit my first post in order to add the precision.

**Comment by Chocobozzz** [comment]
Hi,

Unfortunately we can't enable or disable P2P *on the fly*. We would need to destroy and reload the player. UX would not be very good and bug prone.

Instead, we introduced in https://github.com/Chocobozzz/PeerTube/commit/a9bfa85d2cdf13670aaced740da5b493fbeddfce the ability for admins to disable P2P in the webapp and in the embed by default. This setting can be overridden by an URL query parameter (checkbox available in the share modal).
