### ISSUE TITLE
Add option to provide responsive embed

### ISSUE THREAD

**Issue by rebelcode-xr** [Chocobozzz/PeerTube#3175]
When you embed a video the aspect ratio is not kept during window resize, creating horrible black bars on top and bottom.

**DESKTOP**
![image](https://user-images.githubusercontent.com/63522951/94010823-bae21a80-fda6-11ea-9b66-774faa06c7ed.png)

**MOBILE**
![image](https://user-images.githubusercontent.com/63522951/94010933-e2d17e00-fda6-11ea-985f-ec767d00fa3c.png)

**CODE**
`<iframe width="720" height="530" sandbox="allow-same-origin allow-scripts allow-popups" src="https://peertube.uno/videos/embed/09e77638-6538-4703-a0cc-6400c0506a70" frameborder="0" allowfullscreen></iframe>`

I expected the video to resize proportionally, like **YT** and other embedded videos.

* PeerTube URL: https://peertube.uno/
* Browser name/version: Brave 1.14.81

**Comment by rebelcode-xr** [comment]
temporary fix:

_<iframe width="720" height="530" **class="pt-resize"** sandbox="allow-same-origin allow-scripts allow-popups" src="https://peertube.uno/videos/embed/09e77638-6538-4703-a0cc-6400c0506a70" frameborder="0" allowfullscreen></iframe>_

**.pt-resize {
	width: 100%;
	height:50vw;
	max-height:520px;
}**

**Comment by Chocobozzz** [comment]
Hello,

We respect the video thumbnail ratio. Youtube seems to crop the image to fit the height space. I'm not sure this is the right solution.

**Comment by rebelcode-xr** [comment]
I don't know if it's a problem of the instance: https://peertube.uno/
The aspect ratio of the thumbnail is not kept: the height doesn't change, only the width, so black bars appear. 😞

**Comment by TROMsite** [comment]
I think it would be smart for the embed code to respect the aspect ratio of the video.  So for 16:9 this is fixed with:
```
<div>
  <div style="position:relative;padding-top:56.25%;">
      <iframe width="100%" height="100%" sandbox="allow-same-origin allow-scripts allow-popups" src="https://videos.trom.tf/videos/embed/ba8b063d-a8f3-4d33-b87b-08a57df0dcaf?title=0&warningTitle=0&peertubeLink=0" frameborder="0"  style="position:absolute;top:0;left:0;width:100%;height:100%;" allowfullscreen></iframe>
      </div>
```
Else any video you embed that has a width and height, will not look good on multiple screens. The original example is that of a small tiny mobile screen, and the fix the OP provided is for that scenario, but won't work for wide 1080p or bigger screens. My solution will work on any screen, to preserve the aspect ratio.

**Comment by Chocobozzz** [comment]
We're not responsible of embed size. Responsive embeds can be used by @tio-trom snippet.

**Comment by tio-trom** [comment]
I really hope you reconsider this. You provide an embed button already. Wouldn't it make sense to make the embed responsive?

**Comment by Chocobozzz** [comment]
> I really hope you reconsider this. You provide an embed button already. Wouldn't it make sense to make the embed responsive?

Okay then I think we can add an option disabled by default (like Vimeo for example): "Responsive embed"

**Comment by tio-trom** [comment]
That'd be fantastic! Thanks!
