### ISSUE TITLE
add ability to configure own stun servers

### ISSUE THREAD

**Issue by lub** [Chocobozzz/PeerTube#3177]
As far as I can see currently PeerTube uses hardcoded stun servers:
https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/assets/player/utils.ts#L215-L222

It would be great to have the possibility to specify your own to be more independent and prevent unnecessarily leaking user's IP addresses to 3rd party stun servers.

**Comment by gene1wood** [comment]
Here's the link to the stun servers mentioned above which has moved since this issue was opened : https://github.com/Chocobozzz/PeerTube/blob/2abaa3f27ec9870749a3a6f001922740e26c3830/client/src/assets/player/utils.ts#L205-L212

**Comment by JohnXLivingston** [comment]
Hello.
It seems this code is always here. It would be nice to add this in server configuration.

**Comment by alopatindev** [comment]
I wonder what's the purpose of `stun.stunprotocol.org` here (other than debug)?

It currently resolves to loopback IPs.

**Comment by Chocobozzz** [comment]
Thanks @alopatindev, it seems the URL has changed. Fixed & implemented in https://github.com/Chocobozzz/PeerTube/commit/70ee15d3aa22d63a00fb0fae386d31d7cf293dca
