### ISSUE TITLE
How to use a statically linked compilation of ffmpeg

### ISSUE THREAD

**Issue by alejandrocobo** [Chocobozzz/PeerTube#3178]
I'm using Debian 9 that comes with ffmpeg 3.2. I want to update my Peertube instance to version 2.4 but now it requires ffpmeg 4.1. Since I am running several services on my machine, I don't want to update to Debian 10 for now. I'm looking for a solution and it seems that the less painful way it to use [this statically linked compilation of ffmpeg 4.3](https://johnvansickle.com/ffmpeg/).

The question is, where should I unpack the executable in order to keep Debian's official version of ffmpeg and make Peertube use the newer version?

Thanks.

**Comment by Chocobozzz** [comment]
Uninstall ffmpeg and put the static compiled ffmpeg in `/usr/local/bin`

**Comment by alejandrocobo** [comment]
That worked. I just had to restart peertube's daemon after copying the executable and removing the package.

Thanks!
