### ISSUE TITLE
Video views not shown in Spanish

### ISSUE THREAD

**Issue by alejandrocobo** [Chocobozzz/PeerTube#3180]
**What happened?**
I updated my instance from 2.3 to 2.4 and now the views counter shows nothing if it is different from 1 view. If the video has 1 view, it shows "1 view" (in English). 

It happens in the all video frontpage tabs: Discover, trends, most liked, etc. If I click on any video, it show the views counter correctly with the "view" noun in Spanish.

**What do you expect to happen instead?**
It should show the number of views of each video. Furthermore, the noun "view" should appear in Spanish "visualizaciones".

**Steps to reproduce:**

1. Go to https://tubedu.org

2. Change the interface language to Spanish.

3. Go to any "Video" tabs (Discover, trends...)

**Additional information**
* PeerTube version: ver.2.4
* Browser name/version: Firefox 68.12.0 ESR and Chromium 81.0.4044.138

Thanks!

PS: Just you to know, this is the second release with Spanish translation issues. v.2.3 had a pretty annoying problem that was solved in #3006.

**Comment by criadoperez** [comment]
I can confirm this bug occurs on https://tubedu.org and also on the site https://videos.testimonia.org which is also v.2.4. Only seems to happen for the spanish language.

**Comment by Chocobozzz** [comment]
Thanks for the issue. I updated the translation on weblate and pulled the changes in PeerTube. Should now be fixed.
