### ISSUE TITLE
YouTube import fails on one specific video

### ISSUE THREAD

**Issue by TILvids** [Chocobozzz/PeerTube#3182]
I've tried to get [this specific video](https://www.youtube.com/watch?v=Rwg9a6kjrZs) multiple times now, and it has failed. I went the route of grabbing it from a downloader (all with permission from the original creator) and for some reason it only grabbed the 360p version, when that method always grabs the highest resolution option (up to 1080p). Is there something weird about that particular video that is causing it to fail? I talked to the original creator, and they assure me they haven't produced it in any different way than the dozens of other videos they've uploaded over the last few months.

YouTube change? Something else? I tried a few more imports after that of other (slightly older) videos, and they all worked fine. That video was uploaded in the last week, so I'm wondering if YouTube changed something and broke the import for new videos maybe?

**Comment by test2a** [comment]
Please use desktop youtube-DL to download this video. If it works there then maybe your instance has a bit older youtube-DL. If it doesn't work there also, then get in touch with youtube-DL team.

Wait. I will check it myself and get back to you here

**Comment by TILvids** [comment]
Ok thanks. It's not a huge deal, because like I said, it's just this one video (everything else works). I just wanted to raise it here, because it's a new video, and I don't know if it's some change on YouTube's end that might end up hitting more instances or not. If it's some anomaly then no big deal.

**Comment by test2a** [comment]
![Screenshot_20200930_081631](https://user-images.githubusercontent.com/39449563/94637542-7d751400-02f5-11eb-92d4-ccb01880f026.png)

yep. getting the latest youtube-dl worked with this video. i am not sure if peertube allows manually updating youtube-dl

**Comment by test2a** [comment]
yeah. i just imported this onto https://tube.ouahpiti.info which is on peertube 2.4.0 while your instance is still on 2.3.0.
please update your instance and try again. it should work just fine

**Comment by TILvids** [comment]
Bummer! Ok, I can't update it quite yet, but nice to know that should solve the issue. Thanks for checking it!

**Comment by AnonymousWebHacker** [comment]
@TILvids The problem occurs, because when importing the video, and it fails previously, due to network problems .etc, and you continue trying to download the same URL, youtube blocks access to that video from that ip due to many requests

**Comment by rigelk** [comment]
@test2a did you manage to update/resolve the issue? PeerTube [periodically updates (every 24h)](https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/constants.ts#L185) its version of youtube-dl, so it should work even on your instance version.

**Comment by test2a** [comment]
@rigelk oh. it wasnt me. @TILvids was having the problem importing a video

**Comment by rigelk** [comment]
Oh, sorry, I mistyped :#
Thanks for your help debugging the issue though!

**Comment by TILvids** [comment]
I did get my instance working @rigelk Was able to finally update to 2.4.0 and haven't noticed any problems since then! Thanks for the support!
