### ISSUE TITLE
False 'browser not compatable' warning with use of User-Agent swiching plugin

### ISSUE THREAD

**Issue by gppixelworks** [Chocobozzz/PeerTube#3183]
**What happened?**

False warning that browser is not supported

**What do you expect to happen instead?**

A way to acknoldge the 'warning' in order to remove the warning.

**Steps to reproduce:**

1. Use of User-agent switcher with browser (makes profiling more difficult)

2. Load any PeerTube page

3.

**Additional information**
* PeerTube version and URL:

PeerTube v2.4.0
All URL

* Browser name and version:
Firefox 78.3.0esr (64-bit, Linux) w/User-Agent switcher

* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
What is the user agent you use with this extension?

**Comment by gppixelworks** [comment]
FYI the extension is User-Agent Switcher for Firefox.  The extension's URL:  https://gitlab.com/ntninja/user-agent-switcher

    I've configured it to randomly switches between desktop user agents only:

Windows / Firefox 81 [Desktop]: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0
Linux / Firefox 81 [Desktop]: Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0
Mac OS X / Safari 12 [Desktop]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5 (Ergänzendes Update)) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15
Windows / IE 11 [Desktop]: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Windows / Edge 44 [Desktop]: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763
Windows / Chrome 86 [Desktop]: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
Windows / Firefox 60 ESR [Desktop]: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.8) Gecko/20100101 Firefox/60.8


    The plugin can also be confgured for mobile/tablet browsers and/or bots.  Here's the list of those if it's of interest:

Android Phone / Firefox 81 [Mobile]: Mozilla/5.0 (Android 10; Mobile; rv:81.0) Gecko/81.0 Firefox/81.0
Android Phone / Chrome 86 [Mobile]: Mozilla/5.0 (Linux; Android 10; Z832 Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Mobile Safari/537.36
Android Tablet / Firefox 81 [Mobile]: Mozilla/5.0 (Android 10; Tablet; rv:81.0) Gecko/81.0 Firefox/81.0
Android Tablet / Chrome 86 [Mobile]: Mozilla/5.0 (Linux; Android 10; SAMSUNG-SM-T377A Build/NMF26X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Mobile Safari/537.36
iPhone / Safari 12.1.1 [Mobile]: Mozilla/5.0 (iPhone; CPU OS 10_15_5 (Ergänzendes Update) like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Mobile/14E304 Safari/605.1.15
iPad / Safari 12.1.1 [Mobile]: Mozilla/5.0 (iPad; CPU OS 10_15_5 (Ergänzendes Update) like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Mobile/15E148 Safari/605.1.15

Google Bot [Bot]: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
PS4 [Other]: Mozilla/5.0 (PlayStation 4 4.71) AppleWebKit/601.2 (KHTML, like Gecko)
Curl [Other]: curl/7.72.0
Wget [Other]: Wget/1.20.3 (linux-gnu)

**Comment by gppixelworks** [comment]
FYI the extension is User-Agent Switcher for Firefox.  The extension's URL:  https://gitlab.com/ntninja/user-agent-switcher

I've configured it to randomly switches between desktop user agents only:

Windows / Firefox 81 [Desktop]: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0
Linux / Firefox 81 [Desktop]: Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0
Mac OS X / Safari 12 [Desktop]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5 (Ergänzendes Update)) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15
Windows / IE 11 [Desktop]: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Windows / Edge 44 [Desktop]: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763
Windows / Chrome 86 [Desktop]: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
Windows / Firefox 60 ESR [Desktop]: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.8) Gecko/20100101 Firefox/60.8


The plugin can also be confgured for mobile/tablet browsers and/or bots.  Here's the list of those if it's of interest:

Android Phone / Firefox 81 [Mobile]: Mozilla/5.0 (Android 10; Mobile; rv:81.0) Gecko/81.0 Firefox/81.0
Android Phone / Chrome 86 [Mobile]: Mozilla/5.0 (Linux; Android 10; Z832 Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Mobile Safari/537.36
Android Tablet / Firefox 81 [Mobile]: Mozilla/5.0 (Android 10; Tablet; rv:81.0) Gecko/81.0 Firefox/81.0
Android Tablet / Chrome 86 [Mobile]: Mozilla/5.0 (Linux; Android 10; SAMSUNG-SM-T377A Build/NMF26X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Mobile Safari/537.36
iPhone / Safari 12.1.1 [Mobile]: Mozilla/5.0 (iPhone; CPU OS 10_15_5 (Ergänzendes Update) like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Mobile/14E304 Safari/605.1.15
iPad / Safari 12.1.1 [Mobile]: Mozilla/5.0 (iPad; CPU OS 10_15_5 (Ergänzendes Update) like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Mobile/15E148 Safari/605.1.15

Google Bot [Bot]: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
PS4 [Other]: Mozilla/5.0 (PlayStation 4 4.71) AppleWebKit/601.2 (KHTML, like Gecko)
Curl [Other]: curl/7.72.0
Wget [Other]: Wget/1.20.3 (linux-gnu)

**Comment by Chocobozzz** [comment]
Then remove Trident from the list and it should work. We don't have time to add ability to dismiss the warning on web browser that we know they don't work. If you change your user agent using a plugin, then use at least recent ones.
