### ISSUE TITLE
"my videos" checkbox actions css issue

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3184]
![Screenshot_20201001_083335](https://user-images.githubusercontent.com/39449563/94760741-fb522180-03c0-11eb-9a96-d3e2960e1fe0.png)

**What happened?**
Clicking on the checkbox on the side of any video shows up two buttons, cancel and delete but those are showing up stuck to screen, instead of being in the row of the video selected or at the top if more than one is selected.
**What do you expect to happen instead?**

I checked this with  2.3.0 and 2.4.0 and both have this. its not a big issue, just small papercuts
**Steps to reproduce:**

1.

2.

3.

**Additional information**
* PeerTube version and URL:
* Browser name and version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

This is an intended behaviour

**Comment by test2a** [comment]
is this what you are referring to? 

![simplescreenrecorder-2020-10-23](https://user-images.githubusercontent.com/39449563/97015706-83af8680-1569-11eb-9aed-b4ad9709c53a.gif)

**Comment by Chocobozzz** [comment]
Yes, the idea is that you can easily exec actions on rows you selected + you see all available actions

**Comment by test2a** [comment]
oh. if this is intentional, then so be it. i just find this weird, instead expecting it to be at the top. anyways, i dont have anything else to say in the matter. i will close the issue
