### ISSUE TITLE
"We are sorry but it seems that PeerTube is not compatible with your web browser.", Peertube 2.3.0, Yunohost, Firefox 81.0.1

### ISSUE THREAD

**Issue by devinberg** [Chocobozzz/PeerTube#3185]
**What happened?**
I am receiving the "We are sorry but it seems that PeerTube is not compatible with your web browser." error page. Peertube 2.3.0 is installed on a Yunohost server. I am running Firefox 81.0.1 on Windows 10.

**What do you expect to happen instead?**
Load the instance.

**Steps to reproduce:**

1. Visit instance URL.

**Additional information**
* PeerTube version and URL: 2.3.0, https://video.devinberg.com
* Browser name and version: Firefox 81.0.1
* NodeJS version: 10.22.1

**Comment by devinberg** [comment]
Comment to say that it loads fine in Chrome and that I am able to load other Peertube instances in Firefox.

**Comment by JohnXLivingston** [comment]
Your instance works fine for me. Firefox 81.0 on ubuntu.

**Comment by frankstrater** [comment]
Could you post your user agent by visiting this link?

https://www.whatismybrowser.com/detect/what-is-my-user-agent

You should only get this message when your user agent contains MSIE or Trident. See:

https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/index.html

**Comment by devinberg** [comment]
"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"

Now the issue appears to have cleared itself sometime within the last few days. I am no longer receiving the error.

**Comment by raphaelbastide** [comment]
I get the same error when opening videos on this [website](https://virusland.org/) I made.

```
Uncaught (in promise) TypeError peertube-embed-api.js:1:9581
    a https://virusland.org/js/peertube-embed-api.js:1
    (Async: promise callback)
    u https://virusland.org/js/peertube-embed-api.js:1
    r https://virusland.org/js/peertube-embed-api.js:1
    r https://virusland.org/js/peertube-embed-api.js:1
    play https://virusland.org/js/peertube-embed-api.js:1
    openVideo https://virusland.org/js/main.js:66
    onclick https://virusland.org/js/main.js:15

```

**Comment by Chocobozzz** [comment]
@raphaelbastide Please create a dedicated issue and fill the template :)
