### ISSUE TITLE
A video can be added several times in a playlist

### ISSUE THREAD

**Issue by stom79** [Chocobozzz/PeerTube#3188]
I noticed while doing some tests that the post calls to add a video in a playlist add the video in the playlist each time it is executed. 
Should not it be controlled from server side to ignore a post request if the video is already in the playlist?

A simple way to reproduce that, open the elements inspector with FF. Add a video in a playlist, then resend the request from the elements inspector.

**Comment by test2a** [comment]
I think this is supposed to be a feature. From what I remember, adding multiple videos to a playlist is for having multiple start times or something. Say video a starts at 00:30 and another same at 12:12

**Comment by stom79** [comment]
OK. I understand. But maybe avoiding to add existing videos which already have null values for start and end times (or simply having the same values `videoId/startTime/endTime`)

**Comment by rigelk** [comment]
@stom79 is the possibility to add the video multiple times an impediment to your usage of the API?

**Comment by stom79** [comment]
@rigelk I noticed that when I was testing features after code refactoring. I had an issue where the video was not flagged as already in the playlist. So tapping x times the add to playlist button (toggle was broken on my app), I noticed that I added it several times.
It's of course fixed on my end, but I preferred to submit that report in the case it was not intended.

**Comment by stom79** [comment]
OK. Peertube allows in its web version to add in a same way a video with same start/end times by clicking a "+" button. So it's intended. Sorry for the noise.
