### ISSUE TITLE
Is it possible to change date of URL imported video?

### ISSUE THREAD

**Issue by sunknudsen** [Chocobozzz/PeerTube#3189]
When syndicating my YouTube channel to a self-hosted instance of PeerTube, I forgot to import a video.

Is it possible to upload that video now and change its date so it appears at the bottom of the list?

**Comment by rigelk** [comment]
You can set the "original publication date", but cannot set the "publication date" in the past.

**Comment by sunknudsen** [comment]
@rigelk Thanks for the follow up. That would not change the order right?

**Comment by rigelk** [comment]
Yes, it won't change the order, but allow sorting according to that other field.
