### ISSUE TITLE
Instance migration issues after server problem

### ISSUE THREAD

**Issue by houdini69** [Chocobozzz/PeerTube#3191]
**What happened?**
Following a big problem on my server (Odroid-HC1) I had to reinstall the system (armbian Buster) and my instance. Having backed up my instance regularly I followed the « migration » pages of the docs. 

Initially I could not see local videos but I finally solved this issue as I copied storage directory in the wrong place but view Discover, Trending… videos aren't visible since migration two days ago. Is there anything that can be done about this issue?

Looking into logs I’ve got lots of these warnings:

warn[06/10/2020 à 20:47:36] Cannot add rate https://peertube.servebeer.com/accounts/silencio/likes/267.
{
« err »: {
« stack »: « Error: Body or body actor is invalid\n at Object. (/var/www/peertube/versions/peertube-v2.4.0/dist/server/lib/activitypub/video-rates.js:26:27)\n at Generator.next ()\n at fulfilled (/var/www/peertube/versions/peertube-v2.4.0/node_modules/tslib/tslib.js:111:62) »,
« message »: « Body or body actor is invalid »
}
}

and also:

warn[06/10/2020 à 20:41:21] Cannot refresh actor https://peertube.live/accounts/peertube.

{
« err »: {
« stack »: « Error: certificate has expired\n at TLSSocket.onConnectSecure (_tls_wrap.js:1088:34)\n at TLSSocket.emit (events.js:198:13)\n at TLSSocket._finishInit (_tls_wrap.js:666:8) »,
« message »: « certificate has expired »,
« code »: « CERT_HAS_EXPIRED »
}
}
How to fix that?
**Additional information**
* PeerTube version and URL: Peertube 2.4.0 https://monplaisirtube.ddns.net

**Comment by houdini69** [comment]
So Discover, Trendings... are no more visible. I found when selecting those sections that CPU activity rises to 100% due to postgres.
![htop](https://user-images.githubusercontent.com/24533104/95785827-c99d5c80-0cd6-11eb-8be3-2909084480de.png)

**Comment by houdini69** [comment]
When querying
`SELECT pid, age(clock_timestamp(), query_start), usename, query 
FROM pg_stat_activity 
WHERE query != '<IDLE>' AND query NOT ILIKE '%pg_stat_activity%' 
ORDER BY query_start desc;`

`1289 | 00:00:07.030986 | peertube | SELECT "ActorModel"."id", "ActorModel"."type", "ActorModel"."preferredUsername", "ActorModel"."url", "ActorModel"."publicKey", "ActorModel"."privateKey", "ActorModel"."followersCount", "ActorModel"."followingCount", "ActorModel"."inboxUrl", "ActorModel"."outboxUrl", "ActorModel"."sharedInboxUrl", "ActorModel"."followersUrl", "ActorModel"."followingUrl", "ActorModel"."avatarId", "ActorModel"."serverId", "ActorModel"."createdAt", "ActorModel"."updatedAt", "Account"."id" AS "Account.id", "VideoChannel"."id" AS "VideoChannel.id" FROM "actor" AS "ActorModel" LEFT OUTER JOIN "account" AS "Account" ON "ActorModel"."id" = "Account"."actorId" LEFT OUTER JOIN "videoChannel" AS "VideoChannel" ON "ActorModel"."id" = "VideoChannel"."actorId" WHERE "ActorModel"."url" = 'https://video.qoto.org/accounts/peertube' LIMIT 1;
 1287 | 00:00:33.01711  | peertube | SELECT "video".*, "VideoChannel"."id" AS "VideoChannel.id", "VideoChannel"."name" AS "VideoChannel.name", "VideoChannel"."description" AS "VideoChannel.description", "VideoChannel"."actorId" AS "VideoChannel.actorId", "VideoChannel->Actor"."id" AS "VideoChannel.Actor.id", "VideoChannel->Actor"."preferredUsername" AS "VideoChannel.Actor.preferredUsername", "VideoChannel->Actor"."url" AS "VideoChannel.Actor.url", "VideoChannel->Actor"."serverId" AS "VideoChannel.Actor.serverId", "VideoChannel->Actor"."avatarId" AS "VideoChannel.Actor.avatarId", "VideoChannel->Account"."id" AS "VideoChannel.Account.id", "VideoChannel->Account"."name" AS "VideoChannel.Account.name", "VideoChannel->Account->Actor"."id" AS "VideoChannel.Account.Actor.id", "VideoChannel->Account->Actor"."preferredUsername" AS "VideoChannel.Account.Actor.preferredUsername", "VideoChannel->Account->Actor"."url" AS "VideoChannel.Account.Actor.url", "VideoChannel->Account->Actor"."serverId" AS "VideoChannel.Account.Actor.serverId", "VideoChannel->Accou
 1264 | 00:02:34.491568 | peertube | SELECT "video".*, "VideoChannel"."id" AS "VideoChannel.id", "VideoChannel"."name" AS "VideoChannel.name", "VideoChannel"."description" AS "VideoChannel.description", "VideoChannel"."actorId" AS "VideoChannel.actorId", "VideoChannel->Actor"."id" AS "VideoChannel.Actor.id", "VideoChannel->Actor"."preferredUsername" AS "VideoChannel.Actor.preferredUsername", "VideoChannel->Actor"."url" AS "VideoChannel.Actor.url", "VideoChannel->Actor"."serverId" AS "VideoChannel.Actor.serverId", "VideoChannel->Actor"."avatarId" AS "VideoChannel.Actor.avatarId", "VideoChannel->Account"."id" AS "VideoChannel.Account.id", "VideoChannel->Account"."name" AS "VideoChannel.Account.name", "VideoChannel->Account->Actor"."id" AS "VideoChannel.Account.Actor.id", "VideoChannel->Account->Actor"."preferredUsername" AS "VideoChannel.Account.Actor.preferredUsername", "VideoChannel->Account->Actor"."url" AS "VideoChannel.Account.Actor.url", "VideoChannel->Account->Actor"."serverId" AS "VideoChannel.Account.Actor.serverId", "VideoChannel->Accou`

**Comment by houdini69** [comment]
Here is a log file obtained with pgbadger during increase in CPU activity and rising temperature of my web server 
[2020-10-13_out.html.zip](https://github.com/Chocobozzz/PeerTube/files/5373337/2020-10-13_out.html.zip)
This problem seems related to this one 
[https://github.com/Chocobozzz/PeerTube/issues/2326](url)

**Comment by Chocobozzz** [comment]
Hello,

Your instance seems to work fine. Some SQL queries could be slow because your server is a mini computer.
