### ISSUE TITLE
Public playlist view redirects to login

### ISSUE THREAD

**Issue by jeena** [Chocobozzz/PeerTube#3193]
**What happened?**
I [posted a link to a public playlist on reddit](https://www.reddit.com/r/PeerTube/comments/j6z3ke/a_video_series_about_my_journey_of_running_a/) but the link was to some private view of that playlist so it redirected to a login page which made people upset.

**What do you expect to happen instead?**
The playlist view with the description of the public playlist should be public not private. I can't find any other view with the playlist description which would be public. Changing to view the first video in the list like https://tube.jeena.net/videos/watch/playlist/a66bbc16-ad36-4e4d-9fbe-405c92fe7184?playlistPosition=1 is not a good alternative because it doesn't show the Playlist description and thumbnail which is crucial.

**Steps to reproduce:**

1. Create a public playlist with a description and thumbnail
2. Add public videos to the playlist
3. Go in the UI to that playlist
4. Copy the URL of that playlist
5. Send it to someone without an account on your PeerTube instance
6. Watch them being sad that they can't access your public playlist with public videos

**Additional information**
* PeerTube version and URL: 2.4.0 https://tube.jeena.net
* Browser name and version: Firefox 81.0.1 on Arch Linux
* NodeJS version: v14.13.0

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/2672
