### ISSUE TITLE
Autoplay forms cycles

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#3194]
**What happened?**

The auto-play list gets into cycles, re-visiting videos that have just been played.

**What do you expect to happen instead?**

There is clearly a privacy tradeoff here, since we don't want to be tracking a user's full watch history, but I would expect that via either some short-lived cookies or via algorithmic tweaks to avoid graph cycles, that the suggestions would visit a variety of videos and avoid revisiting the same video.

**Steps to reproduce:**

1. Here's an example from diode zone: https://diode.zone/videos/watch/d2f1cfb2-4bb9-4046-8adc-812c8f44c7fe

2. Keep clicking "next" with autoplay. 

3. It will just revisit the same two videos over and over.

**Additional information**
* PeerTube version and URL: 2.4.0
* Browser name and version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/1985 since we use the recommended videos array to play the next video
