### ISSUE TITLE
Help CaptainFact to support PeerTube videos

### ISSUE THREAD

**Issue by jibe-b** [Chocobozzz/PeerTube#3197]
CaptainFacts is a community of fact-checkers. They embed videos in the website to ease fact-checking at time points and provide a webextension to go watch the current video with the checked facts.

I opened a feature request suggesting to support PeerTube videos.

They may get to do it more quickly as you definitely know the technology you used the best ;)

Here is the feature request: https://github.com/CaptainFact/captain-fact/issues/147

**Comment by Chocobozzz** [comment]
Hello,

Thanks, I subscribed to the captain-fact issue. If you have questions, we'll answer to them. You can also create dedicated issues on the PeerTube repository if you need specific API/plugin/embed API features.

**Comment by jibe-b** [comment]
Thank you @Chocobozzz!
