### ISSUE TITLE
How to clean up unused files when disabling WebTorrent or HLS?

### ISSUE THREAD

**Issue by jinnko** [Chocobozzz/PeerTube#3200]
**What happened?**

When changing transcoding config from both WebTorrent and HLS to just HLS how can one go about removing the WebTorrent versions of the files?

If there's no existing way I'd be happy to take guidance and produce a script for the task that I would raise as a PR.

**What do you expect to happen instead?**

**Steps to reproduce:**

1. Via the Config pages disable WebTorrent

2. Do something to remove the unused files.

**Additional information**
* PeerTube version and URL: 2.4.0
* Browser name and version:
* NodeJS version: (latest official docker image, not sure)

* Link to browser console log if useful:
* Link to server log if useful (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by jinnko** [comment]
It turns out videos uploaded after disabling WebTorrent were available for a short time and viewed by users, then vanished from disk.  Looking at the storage on disk the files have actually been deleted as I can see them in previous snapshots (so far only the 2160k variant, but I haven't dug deep yet).

In the browser the first error displayed is:

```
XHR  GET  https://peertube.example.com/static/streaming-playlists/hls/97303ed4-9696-47f3-bb07-3fdbcc33f2ed/segments-sha256.json
[HTTP/2 404 Not Found 23ms]
```

**Comment by Chocobozzz** [comment]
Hello,

For now removing HLS or webtorrent versions of instance videos is not supported. PR welcome if you want to create such script.

**Comment by Chocobozzz** [comment]
With https://github.com/Chocobozzz/PeerTube/commit/b46cf4b920984492df598c1b61179acfc7f6f22e you can remove HLS/WebTorrent files from the web interface

**Comment by alejandrocobo** [comment]
> With [b46cf4b](https://github.com/Chocobozzz/PeerTube/commit/b46cf4b920984492df598c1b61179acfc7f6f22e) you can remove HLS/WebTorrent files from the web interface

Great news!

Thank you very much.
