### ISSUE TITLE
Mail notification incorrect footer call to action

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#3203]
**What happened?**
When someone uses the contact form on the about page, the e-mail received ends up with «View in your notifications -- Manage your notification preferences in your profile». But this kind of notification does not exists for these emails.

**What do you expect to happen instead?**
The message should not be included in these emails.

**Additional information**
* PeerTube version and URL: 2.4.0

**Comment by rigelk** [comment]
I'll reformulate as "Open your web notifications", as there is not a 1:1 correspondence btw mail/web notifications.

**Comment by Chocobozzz** [comment]
@rigelk We could also just hide this message in contact form emails, no?

**Comment by rigelk** [comment]
@Chocobozzz makes no difference in the end I guess, do yes

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/b9cf3fb6381f71c976fbe515f728082d90a9c437
