### ISSUE TITLE
Can not subscribe accounts/channels on other PeerTube servers even with URL workaround

### ISSUE THREAD

**Issue by r4dh4l** [Chocobozzz/PeerTube#3204]
**What happened?**

With the account https://peertube.social/accounts/gnuhu/video-channels I wanted to follow https://libre.video/accounts/nachhaltigkeitsbuero_hu_berlin/video-channels.

Because of https://github.com/Chocobozzz/PeerTube/issues/2888 I tried the following workaround:

While logged in to https://peertube.social/accounts/gnuhu/video-channels I changed the URL of https://libre.video/accounts/nachhaltigkeitsbuero_hu_berlin/video-channels to https://peertube.social/accounts/nachhaltigkeitsbuero_hu_berlin@libre.video/video-channels and hit "Subscribe with your local account"...

![Screenshot_2020-10-18_14-30-56](https://user-images.githubusercontent.com/44623983/96370385-da7a2200-115d-11eb-9d5c-99507b836a7c.png)

...but nothing happens. There is no subscriber listed:

![Screenshot_2020-10-18_16-18-14](https://user-images.githubusercontent.com/44623983/96370446-2036ea80-115e-11eb-92ed-851257183f2b.png)

The same with the original URL:

![Screenshot_2020-10-18_15-27-33](https://user-images.githubusercontent.com/44623983/96370461-317ff700-115e-11eb-936e-35bac7a1282a.png)

**What do you expect to happen instead?**

I expected that I subscribe the account after hitting "Subscribe with your local account".

**Steps to reproduce:**

1. Log in to your PeerTube account.

2. Open another PeerTube account (as long as https://github.com/Chocobozzz/PeerTube/issues/2888 is not fixed) use the URL `https://YourPeertubeServer.tld/accounts/AccoutNameOfAccountOnDifferentPeertubeServer@DifferentPeertubeServer.tld`). 

3. Open the drop down menu "Unsubscribe from all channels" and use "Subscribe with your local account".

**Comment by test2a** [comment]
not possible at the moment. you can only follow channels on your instance and probably ones already federated with your server and not outside. this is a known issue

**Comment by Chocobozzz** [comment]
Hello,

If your admin allows it, you can paste the channel URL in the search bar to fetch it. Then you should be able to follow it.

**Comment by r4dh4l** [comment]
> not possible at the moment. you can only follow channels on your instance and probably ones already federated with your server and not outside. this is a known issue

@test2a Okay, so if there is an existing issue for this it is totally okay to close this one. But at least there should be link from this issue to the other one.

> If your admin allows it, you can paste the channel URL in the search bar to fetch it. Then you should be able to follow it.

@Chocobozzz Thx for your answer. Contacting the server admin and using the channel url be a workaround for technical educated people. This doesn't help people knowing just YouTube.
