### ISSUE TITLE
Add video in playlist using upload form

### ISSUE THREAD

**Issue by discapacidad5** [Chocobozzz/PeerTube#3205]
I wish there was a way to add the playlist more easily:

1. be able to add videos to the playlist directly when the video is loading
2. be able to batch add videos to a playlist when the videos are selected (in `/my-account/videos`)

**Comment by AnonymousWebHacker** [comment]
agregarle tambien esto https://github.com/Chocobozzz/PeerTube/issues/3202

**Comment by rigelk** [comment]
@discapacidad5 I reformulated your suggestions for clarity. Could you expand on your first suggestion? I'm not sure what you meant by that.

**Comment by discapacidad5** [comment]
Hello. Excuse me. If it is not very clear. My requirement is that I do not speak English. I am using the Google translator.

The problem I see is that when you have many videos and want to add all of them to a playlist there is no way to add the videos in batch Something similar to what exists when you want to Delete videos allows you to Delete videos in batch and marking one by one It would be nice if you could also add the corn to a playlist.

Also, usually when you upload a new video you already know which playlist you want to place it on, there is no option to select a playlist in the video editing directly at the time of loading it, so you have to do double work load the video then go to Play the video and being there is that you can add a playlist my requests that you can add a playlist directly in the upload dialog of the video.

In total I am asking for two functions, the first to be able to batch add videos to the playlist in the same way that you can batch delete videos and the second to be able to select the playlist to which the video belongs at the moment in that the video is loading I hope my request is clearer this time

**Comment by Chocobozzz** [comment]
For `2.`, see https://github.com/Chocobozzz/PeerTube/issues/2754

**Comment by Chocobozzz** [comment]
Hi,

Regarding 1. we don't want to add other fields to the upload form (that is already a little bit complex). A plugin could add such field though
