### ISSUE TITLE
AUTO mode remains on 240

### ISSUE THREAD

**Issue by JM-Teule** [Chocobozzz/PeerTube#3206]
**What happened?**

**What do you expect to happen instead?**

**Steps to reproduce:**

The AUTO mode in Video playback remains on the bitrate 240 whatever the quality of the connection, even on optical fiber. Forced to manually select the higher resolutions offered by the video. Is this a problem with PeerTube or with the instance hosting the videos?

**Additional information**
* PeerTube version and URL:2.3.0
* Browser name and version: Firefox 81.0.2, Safari Version 13.1.2 (15609.3.5.1.3), Opera Version :71.0.3770.271
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by JM-Teule** [comment]
The instance is https://video.tedomum.net/about/instance

**Comment by Chocobozzz** [comment]
Hello,

This bug should be fixed in 2.4
