### ISSUE TITLE
Root login not working when using http + docker

### ISSUE THREAD

**Issue by achaiah** [Chocobozzz/PeerTube#3208]
**What happened?**
I'm standing up a local docker image for peertube (chocobozzz/peertube:production-buster) with just redis and postgres containers (no reverse proxy). The following environment variables are set in my .yaml config:

```
    environment:
      - PEERTUBE_WEBSERVER_HOSTNAME=idlenas.home
      - PEERTUBE_WEBSERVER_PORT=9000
      - PEERTUBE_WEBSERVER_HTTPS=false      # since we are NOT serving with reverse proxy
      - PEERTUBE_TRUST_PROXY=["127.0.0.1", "loopback", "172.18.0.0/16"]
```

When I go to my peertube site, in the UI I get the popup:
```
Cannot retrieve OAuth Client credentials: undefined. Ensure you have correctly configured PeerTube (config/ directory), in particular the "webserver" section.
```

Then, when I proceed to login with root username and pw I see the message: `Invalid client: client is invalid `

the logs show:
```
[idlenas.home:9000] 2020-10-20 04:39:00.530 warn: Login error. {
  "err": {
    "statusCode": 400,
    "status": 400,
    "code": 400,
    "message": "Invalid client: client is invalid",
    "name": "invalid_client",
    "stack": "invalid_client: Invalid client: client is invalid\n    at new InvalidClientError (/app/node_modules/oauth2-server/lib/errors/invalid-client-error.js:26:14)\n    at /app/node_modules/oauth2-server/lib/handlers/token-handler.js:141:15\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)"
  }
}
```

**What do you expect to happen instead?**
My expectation is that I can login with root user

**Steps to reproduce:**

1. Start up a new docker compose stack with peertube configured in HTTP mode.

2. Attempt to log in with root user

3. Observe the error message: `Invalid client: client is invalid `

**Additional information**
* PeerTube version and URL: chocobozzz/peertube:production-buster   (URL is local to my network) 
* Browser name and version:  Firefox 81.0.2
* NodeJS version: 

* Link to browser console log if useful:
* Link to server log if useful (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

`PEERTUBE_WEBSERVER_PORT` and `PEERTUBE_WEBSERVER_HTTPS` are an information you give to peertube so it knows what is the URL of your public instance. So if you use a classic HTTPS instance, `PEERTUBE_WEBSERVER_HTTPS=true` and `PEERTUBE_WEBSERVER_PORT=443`

**Comment by achaiah** [comment]
I'm sorry but that doesn't seem to address the issue I'm having. I'm not trying to make the instance public but rather just have it run on my local docker swarm cluster. Hence I'm not using HTTPS. However, the local peertube instance is failing to log me in with the root user and pw provided in the log output of the docker container.

**Comment by bmiller59** [comment]
@achaiah I had the same issue and the cause was that my external nginx proxy was not configured correctly. 

I had to apply this nginx config: https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube, EXCLUDING the "could be removed" sections. This idea came thanks to https://github.com/Chocobozzz/PeerTube/issues/3151#issuecomment-706734037.

We need to exclude those because those static files are not exposed in the same way through docker. 

Now everything is working great!

**Comment by achaiah** [comment]
@bmiller59 Thanks for the tip. I saw that thread too but I don’t see how it’s related to my issue. I don’t have an external proxy or a proxy of any kind since I’m just trying to run it in a private docker swarm cluster and I’m not using https. 

I’m also not sure why this issue was closed since I think it’s a valid bug/error.

**Comment by Chocobozzz** [comment]
@achaiah what is the URL of your local PeerTube instance?

**Comment by bmiller59** [comment]
@achaiah You wrote that you are using this without the proxy provided by standard docker-compose config. I believe in that situation that some of the routes/paths will not be hitting peertube correctly, most likely the websocket. e.g.

```
location /socket.io {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;

    proxy_pass http://127.0.0.1:9000;

    # enable WebSockets
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
```

I think you will need some kind of proxy to handle that.

**Comment by achaiah** [comment]
@Chocobozzz  My local Peertube instance URL is `idlenas.home` (I set my router resolve the `.home` domain to my local network).  I also tried specifying the direct IP address instead of URL to no effect. :(

@bmiller59 Hmm that seems odd since nginx is typically just used to load-balance connections and resolve certificates for HTTPS connections.  I can certainly run it with nginx but I'd have to figure out how to disable SSL/HTTPS on the proxy since I want just a plain HTTP connection. Also, according to the standard docker-compose config [here](https://github.com/Chocobozzz/PeerTube/blob/master/support/docker/production/docker-compose.yml), peertube uses traefik and not nginx.

**Comment by rigelk** [comment]
@achaiah yes, there current docker-compose setup is far from ideal, which is why we have a PR to use Nginx there as well

**Comment by Chocobozzz** [comment]
> @Chocobozzz My local Peertube instance URL is idlenas.home (I set my router to resolve the .home domain to my local network). I also tried specifying the direct IP address instead of URL to no effect. :(

Then try
```
PEERTUBE_WEBSERVER_PORT=80
PEERTUBE_WEBSERVER_HTTPS=false
PEERTUBE_WEBSERVER_HOSTNAME=idlenas.home
```

**Comment by achaiah** [comment]
@Chocobozzz Hmm using port 80 seems to be broken. Even though I specify 80, it looks like it's still starting the server on port 9000. Here are the logs:
```
[idlenas.home:80] 2020-10-29 03:16:43.667 error: Cannot use SMTP server because of lack of configuration. PeerTube will not be able to send mails!
[idlenas.home:80] 2020-10-29 03:16:43.714 info: Cleaning HTML cache.
[idlenas.home:80] 2020-10-29 03:16:43.805 warn: It seems PeerTube was started (and created some data) with another domain name. This means you will not be able to federate! Please use NODE_CONFIG_DIR=/config NODE_ENV=production npm run update-host to fix this.
[idlenas.home:80] 2020-10-29 03:16:43.831 info: Server listening on 0.0.0.0:9000
[idlenas.home:80] 2020-10-29 03:16:43.831 info: Web server: http://idlenas.home
```

You can see that it's printing output as `idlenas.home:80` but when it finally starts it says: `Server listening on 0.0.0.0:9000`

**Comment by Chocobozzz** [comment]
As said in https://github.com/Chocobozzz/PeerTube/issues/3208#issuecomment-715335381, the `Web server:` line is just an information: PeerTube does not listen on this hostname. It just says "your reverse proxy is configured like that, so this is my public instance URL". It keeps listening on `9000` because of `listen.hostname` and `listen.port` configurations.

You have the `It seems PeerTube was started...` error because you already started peertube with another webserver URL (`idlenas.home:9000`). To fix this, delete your database and rerun peertube with the new configuration.

**Comment by achaiah** [comment]
Ok, sorry I didn't understand what you meant in your comment #3208. I typically expect a variable such as `PEERTUBE_WEBSERVER_PORT` to be specifying the internal port and something like `PEERTUBE_WEBSERVER_EXTERNAL_PORT` for the external port. Now that I've made sure to match my external port to the PEERTUBE_WEBSERVER_PORT the OAuth error has gone away and I can log in. Thanks for your help!
