### ISSUE TITLE
Add server-side privacy/data policy to the warning modal

### ISSUE THREAD

**Issue by ReK2Fernandez** [Chocobozzz/PeerTube#321]
I think is a great idea.. but in the other hand I think is limited because some people concerned with privacy and freedom like us at hispagatos, we do not keep logs we try to dissable and if we cant we will have a cron job to delete every  30m the logs... so will be nice for admins to add to that warning personal warnings about the actual system they are visiting.

**Comment by rigelk** [comment]
The warning implemented in 22b59e8 is less about the server and more about its use of WebTorrent: clients can see other clients they share content to. So no matter if you log or not, the other clients can still see each other and of course, log their IPs. Please have a thorough look at #316.

As for adding info related more to how the server handles user data itself, why not just add a link to the terms of service? That's where the info should be sitting anyway, albeit more verbose.

**Comment by ReK2Fernandez** [comment]
@rigelk ahh cool that makes sense.. sorry wrote that super late.. :) I think the terms of service is a great idea. thanks.
