### ISSUE TITLE
413 “Payload Too Large” when importing videos using CLI

### ISSUE THREAD

**Issue by jimgroom** [Chocobozzz/PeerTube#3210]
**What happened?**
Tried to import large files from video service to my Docker instance of Peertube using CLI commands but after everything was downloaded and then tried to upload to the Peertube instance I got the following error:
expected 200 “OK”, got 413 “Payload Too Large”

**What do you expect to happen instead?**
Files to successfully import
**Steps to reproduce:**

1. ran the import script to for the importing files over 90 MB

**Additional information**
* PeerTube version and URL: latest Docker image https://hub.docker.com/r/chocobozzz/peertube
* Browser name and version: Chrome Version 86.0.4240.80 
* NodeJS version: 10.22.1
* Link to browser console log if useful: N/A
* Link to server log if useful (`journalctl` or `/var/www/peertube/storage/logs/`):

My question at its simplest would be is there a way to see and update the max_body_size for the traefik reverse-proxy? I read it was set to 8GB by default, but not clear on how to find and confirm the size for my instance. If you need more information just let me know, and thanks for such awesome software.

**Comment by Chocobozzz** [comment]
Hello,

Did you try to update [these values](https://doc.traefik.io/traefik/v1.7/configuration/commons/#buffering) in your `traefik.toml`?

**Comment by jimgroom** [comment]
Thanks for the response, I just checked my ~/peertube/docker-volume/traefik/traefik.toml file and I do not see any of those value, here is what it looks liek:
# Uncomment this line in order to enable debugging through logs
debug = true
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    MinVersion = "VersionTLS12"
    CurvePreferences = [
      "CurveP521",
      "CurveP384",
      "CurveP256"
    ]
    PreferServerCipherSuites = true
    CipherSuites = [
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
      "TLS_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_RSA_WITH_AES_256_CBC_SHA"
    ]
    FrameDeny = false # here we don't want to deny frames since we have an embed
    STSIncludeSubdomains = true
    STSSeconds = 315360000
    STSPreload = true
    ContentTypeNosniff = true
    BrowserXssFilter = true

# Enable ACME (Let's Encrypt): automatic SSL.
[acme]

# File or key used for certificates storage.
#
# Required
#
storage = "/etc/acme.json"
# or `storage = "traefik/acme/account"` if using KV store.

# Entrypoint to proxy acme apply certificates to.
# WARNING, if the TLS-SNI-01 challenge is used, it must point to an entrypoint on port 443
#
# Required
#
entryPoint = "https"

# Use a HTTP-01 acme challenge rather than TLS-SNI-01 challenge
#
# Optional but recommend
#
[acme.httpChallenge]

[acme.httpChallenge]

  # EntryPoint to use for the challenges.
  #
  # Required
  #
  entryPoint = "http"

Should I add the values you suggest, and would I need a restart of the containers pick up the new values if so?  Thanks for any help, and appreciate the assist here.

**Comment by Chocobozzz** [comment]
> Should I add the values you suggest, and would I need a restart of the containers pick up the new values if so? Thanks for any help, and appreciate the assist here.

Yes I think so.
