### ISSUE TITLE
502 Bad gateway uploading videos

### ISSUE THREAD

**Issue by alejandrocobo** [Chocobozzz/PeerTube#3211]
**What happened?**
Lately has been very hard for some users to upload new videos to my instances (I have two with the same problem). When the file is bigger than 50-100Mbytes it's almost impossible. It happened overnight. Sometimes the videos uploads works fine, but lately it has become worse. The point is that the client uploads the full file but in the storage/tmp folder only are stored tens or hundreds of Mbytes from the the full file (it ends being an incomplete file). 

When the client ends the transfer, it appears this message:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
	<head>
		<title>502 Bad Gateway</title>
	</head>
	<body>
		<h1>Bad Gateway</h1>
		<p>The proxy server received an invalid response from an upstream server.<br /> </p>
		<hr>
			<address>Apache/2.4.25 (Debian) Server at video.hardlimit.com Port 443</address>
	</body>
</html>
```

I use Apache as web server. The config file is based in [this one](https://gist.github.com/rigelk/07a0b8963fa4fc1ad756374c28479bc7).

I've restarted the whole server with the same result.

I have changed nothing since the last time it worked fine.

The storage device has more than enough free space.

**Steps to reproduce:**

1. Go to https://video.hardlimit.com or https://tubedu.org.

2. Create an account.

3. Try to upload a large file (around 1GB).

**Additional information**
* PeerTube version and URL: 2.0.0 for hardlimit.com and 2.4.0 for tubedu.org
* Browser name and version: Firefox
* NodeJS version: v12.19.0

* Link to browser console log if useful: No errors appears in server's log (nor Apache, nor Peertube).

Thanks.

**Comment by rigelk** [comment]
Hi, unfortunately we don't provide support for Apache, as we don't have a reference configuration for it not have we the resources to maintain one.

You might want to check your disk size available as tmp might me constrained on your machine. You might want to check your max body size in your Apache configuration, as we do set it to a higher value than default in our nginx configuration.
