### ISSUE TITLE
Temporary 502 Bad Gateway when someone write a comment

### ISSUE THREAD

**Issue by manuelviens** [Chocobozzz/PeerTube#3212]
**What happened?**
502 Bad Gateway from nginx for about ~30 secs to 1 minute, anytime someone write a comment on one of my videos.

**What do you expect to happen instead?**
No 502.

**Steps to reproduce:**

1. Someone registered on my instance write a comment on one of my videos

2. I instantly receive a notification email from PeerTube, I click on the link.

3. nginx gives 502 on my PeerTube instance. It returns to normal after ~30 seconds to 1 minute.

P.S. Can reproduce if I reply too...

**Additional information**
* PeerTube version and URL: 2.4.0
* Browser name and version: Firefox 82.0
* NodeJS version: v12.19.0

* Link to browser console log if useful: 
* Link to server log if useful (`journalctl` or `/var/www/peertube/storage/logs/`): [peertube-audit.log and peertube.log](https://framabin.org/p/?b4f9246d379d9243#dcu5bFyAgagcsiEzDIvjAOy+VVqVp4dIpvGa2dy0gLQ=)
password : fq
[Not sure if related, errors from Journaux in Admin web UI](https://framabin.org/p/?eaad95b6924b1087#Bs419yfB6kxtystIFmpOG8tvLjIF4tNnhUwURdvI94A=)
password : fq

**Comment by Chocobozzz** [comment]
Hello,

What plugins do you use?

**Comment by manuelviens** [comment]
georegister 0.0.4
glavliiit 0.0.10
hcaptchaaa 0.0.2
player-watermark 0.0.1
social-sharing 0.2.0
upload-limits 0.3.1

**Comment by Chocobozzz** [comment]
Try to uninstall `upload-limits` and try to reproduce please

**Comment by manuelviens** [comment]
I can't reproduce without this plugin.
I hope that was the cause.
