### ISSUE TITLE
feature request: Allow support options for creators

### ISSUE THREAD

**Issue by Rik44444** [Chocobozzz/PeerTube#3214]
Hi all,
The only downside to Peertube at the moment as compared to Youtube, is that Youtube allows for creators to earn money on their  videos, through ads or through a portion of someone's subscription fee to Youtube Premium (where you pay a fixed amount per month, see no ads, and creators get a proportion of that amoun). 
This is a request to make this also possible in Peertube: a voluntary payment option for members, whereby the periodic payment gets automatically distributed to the creators of the videos that have been watched, paid out by the number of seconds that a video has been watched (as longer videos take more time and effort to create). I would advise a minimum viewing time of 10 seconds to be eligible for payment. 
I will happily pay the same as the subscription fee to Youtube Premium if this becomes possible on Peertube. (12 euro per month)

**Comment by Booteille** [comment]
Hi. There is already an issue opened about Monetization.

If you want to participate to the debate, go there: https://github.com/Chocobozzz/PeerTube/issues/1586
