### ISSUE TITLE
Wordpress Plugin to Upload and Embed Video

### ISSUE THREAD

**Issue by yfarkash** [Chocobozzz/PeerTube#3215]
Hi,

I'm new to self-hosting Wordpress and Peertube.

I think that a Wordpress plugin that alows the user to upload to Peertube a video and embed it directly in the  Wordpress post will be amazing.

The use-case is that currently using videos in Wordpress requires the writer to upload the video to another platform (Youtube, Peertube, Vimeo) and then embed the link.  There is a direct video upload to the wordpress media library, but it is limited by size.  Most Wordpress writers end up using Youtube.

It will be amazing if a plugin was developped that will allow for direct upload of a video while writing a Wordpress post, and the video will be directly uploaded and hosted at a Peertube instance and the link embeded automatically in the Wordpress post.

I think that such a plugin will 1) help writers embed videos in their blogs.  But more importantly, 2) will get Peertube to be more noticed as many writers now go through a longer process of uploading to Youtube and then getting the link to embed in Wordpress.  If they could do it withoutu leaving Wordpress they might migrate to PEertube.

Thank you for considering this.

**Comment by Chocobozzz** [comment]
Hello,

I agree it would be great to have such thing. But it is out of the scope of the peertube project, so closing this issue. Don't hesitate to discuss about this in the wordpress community instead
