### ISSUE TITLE
Mobile video player pause/play 

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3217]
**What happened?**
I am on a mobile phone and I am unable to touch the video player to pause/play the video. I am forced to cluck on the little play button for operations. 
**What do you expect to happen instead?**
Like all touch compatible video players, touching the video player usually pauses/plays the video. Interestingly, on a desktop, mouse does this exactly but touch events seem to be ignored.

I will try to investigate this with an old tablet I have. Will put it in comments later today.

**Additional information**
* PeerTube version and URL:
* Browser name and version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
I think we should display a big pause overlay on the video after a touch event, like youtube does

**Comment by Chocobozzz** [comment]
Done in https://github.com/Chocobozzz/PeerTube/commit/f1a0555a88db9ade2b073a2e4dc73c4a6176c8a0
