### ISSUE TITLE
Translation source string problems

### ISSUE THREAD

**Issue by markvdb** [Chocobozzz/PeerTube#3222]
Hello,

This is a list of language issues with the PeerTube translation sources as provided in https://weblate.framasoft.org/projects/peertube/angular/ as of today.

Could you please have a look at fixing these?

• EFRANGLAIS: "The notification points to a content now unavailable"=>"The notification points to content"
• EFRANGLAIS: "The IP address is a vague information"=> "The IP address is a vague information"
• EFRANGLAIS: "If you want to open registrations, please decide what are <x id="START_TAG_STRONG"/>your moderation rules<x id="CLOSE_TAG_STRONG"/>, fill your <x id="START_TAG_STRONG"/>instance terms<x id="CLOSE_TAG_STRONG"/> and specify the categories and languages you speak. This way, you will help users to register on <x id="START_TAG_STRONG"/>the appropriate<x id="CLOSE_TAG_STRONG"/> PeerTube instance."
• EFRANGLAIS: " It is a free and open-source software, under the <x id="START_LINK"/>AGPLv3 licence<x id="CLOSE_LINK"/>."
• EINCOMPREHENSIBLE: "Automatic video redundancy from some instances: one doesn't know if the IP downloaded the video on purpose or if it a server"
• EGRAMMAR: " This instance does not have instances followings."
• EGRAMMAR: "Allow <x id="START_TAG_STRONG"/>your users<x id="CLOSE_TAG_STRONG"/> to look up remote videos/actors by their URI, that may not be federated with your instance"
• WCLARIFYSOURCE: "Videos will be deleted, comments will be tombstoned."; See https://en.wikipedia.org/wiki/Tombstone_(data_store)
• ECLARIFYSOURCE: "Verify account ask send email"
• EPLURAL: <x id="PH"/> year ago
• WREPHRASE: "Channel name should be lowercase alphanumeric; dots and underscores are allowed."
• EGRAMMAR: "Request is too large for the server. Please contact you administrator if you want to increase the limit size." -> size limit
• EUNCLEAR: grammatica:  "Followers instances"
• EUNCLEAR: grammatica: "Followings instances"
• EUNCLEAR: "Hide any content from that user for you." unclear or wrong. Should probably be "Hide any content from that user from you.", or it means something totally different.
• EUNCLEAR: " Remove comments of this account from your videos."
• EUNCLEAR: 'Hide any content from that user for you, your instance and its users."
• EUNCLEAR: "Show back content from that user for you, your instance and its users."
• EUNCLEAR: "Hide any content from that instance for you, your instance and its users."
• EUNCLEAR: "Show back content from that instance for you, your instance and its users."
• EUNCLEAR: "Remove comments of this account from your instance."
• EUNCLEAR: "Videos that have the higher number of likes."
• EUNCLEAR: "Choosing your <x id="START_TAG_STRONG"/>instance name<x id="CLOSE_TAG_STRONG"/>, <x id="START_TAG_STRONG"/>setting up a description<x id="CLOSE_TAG_STRONG"/>, specifying <x id="START_TAG_STRONG"/>who you are<x id="CLOSE_TAG_STRONG"/>, why <x id="START_TAG_STRONG"/>you created your instance<x id="CLOSE_TAG_STRONG"/> and <x id="START_TAG_STRONG"/>how long<x id="CLOSE_TAG_STRONG"/> you plan to <x id="START_TAG_STRONG"/>maintain your it<x id="CLOSE_TAG_STRONG"/> is very important for visitors to understand on what type of instance they are. "
• ENOCONTEXT?: "About follows"

**Comment by rigelk** [comment]
Thank you for these comments. We have no dedicated channel to correct source strings, but commenting the incriminated source string within Weblate might allow us to spot the origin to correct more accurately.

**Comment by markvdb** [comment]
While translating the new strings for live streaming, I've found and tagged a few more source strings as problematic in weblate. I added a few suggestions this time how to rephrase them.
