### ISSUE TITLE
Sort channel videos

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3224]
**What happened?**
i tried to look this issue up but i could not find any duplicate, so anyways. youtube has "video sort" in channels which is very helpful if a channel has many videos. on this subject, we also dont have a channel specific search where a user can search between videos of a particular channel only. maybe that could be done but i dont  know how.

So, coming to the sort thing, consider if a channel has 100 video or say 500, scrolling is not an efficient way of looking back at content. Youtube offers sort by "most liked", "earliest" and "most recent". peertube only sorts by most recent so adding "earliest" could be interesting. We could also have most liked or most engaging but can be discussed

**Comment by test2a** [comment]
https://docs.joinpeertube.org/api-rest-reference.html#tag/Video-Channels/paths/~1video-channels~1{channelHandle}~1videos/get
this says the functionality is already existing in peertube api. interesting

**Comment by klawdhfzasjhaa** [comment]
It would also be great, if one could sort Playlist videos in chronological order (newest first). At the moment it is the other way around (oldest first). This is not good, if a playlist has many videos.

**Comment by kontrollanten** [comment]
@klawdhfzasjhaa There's a plugin that reverses the playlist order; https://www.npmjs.com/package/peertube-plugin-playlist-reverse-order

**Comment by klawdhfzasjhaa** [comment]
I think, this is a basic feature / option, which should be built in as suggested in the first place.

I tried the plugin, but it does not work. Someone already opened an issue: https://framagit.org/kontrollanten/peertube-plugin-playlist-reverse-order/-/issues/1.

**Comment by kontrollanten** [comment]
> I tried the plugin, but it does not work. Someone already opened an issue: https://framagit.org/kontrollanten/peertube-plugin-playlist-reverse-order/-/issues/1.

There's an answer in the issue which you can try to see if it helps you.

**Comment by Chocobozzz** [comment]
Closing this issue since the OP issue has been resolved: we can sort channel's and account's videos.
