### ISSUE TITLE
Feature Request - Bitchute importer

### ISSUE THREAD

**Issue by GORF-Official** [Chocobozzz/PeerTube#3225]
Many folks are unhappy with Bitchute and would like to move to a peertube instance but it is a lot of work.  If we had an importer tool like we have for youtube I think many would leave bitchute and use an actual distributed video platform, not just one that pretends to be for $$$.

**Comment by test2a** [comment]
doesn't ydl support bittube ? Oh well, let the dust settle and request there. Peertube is downstream to ydl and any improvement there flows here also.

**Comment by rigelk** [comment]
We don't plan to support BitChute.
