### ISSUE TITLE
html content in comment notification emails

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#3228]
When someone is commenting a video using a ```@xxx```, the notification email contains escaped html: 
![image](https://user-images.githubusercontent.com/38844060/97190951-a5498180-17a6-11eb-87ed-6c4a2570e71e.png)

NB: In this case, the comment came from a mastodon account. 

**What do you expect to happen instead?**

Html should be removed to have plain text. 

**Additional information**
* PeerTube version and URL: 2.4.0

**Comment by rigelk** [comment]
@kimsible could you add tests to #3255 so that we can close this issue?

**Comment by Chocobozzz** [comment]
Added in https://github.com/Chocobozzz/PeerTube/commit/45c70083ddb7f57c52e2c587d6e3ab581c657716 & https://github.com/Chocobozzz/PeerTube/commit/9afb5c10e5935e667e33219bdbd775e9ed1b4330
