### ISSUE TITLE
Can’t translate “Theater mode” and “Normal mode” strings

### ISSUE THREAD

**Issue by ariasuni** [Chocobozzz/PeerTube#3229]
**What happened?**
The tooltips “Theater Mode” to “Normal Mode” of one of the button of the player aren’t translatable. I can’t found them on the Weblate even though the strings exist in the code since more than two years.

**What do you expect to happen instead?**
I can have the tooltips of all the buttons of the player in my language of choice.

**Steps to reproduce:**

1. Open the page of a video
2. Hover the “Theater mode” button with your mouse and notice the “Theater mode” or “Normal mode” text displayed
3. Notice you can’t find these strings to translate them on the Weblate:
    - https://weblate.framasoft.org/search/peertube/player/?offset=1&q=Theater+mode&sort_by=-priority%2Cposition&checksum=
    - https://weblate.framasoft.org/search/peertube/player/?offset=1&q=Normal+mode&sort_by=-priority%2Cposition&  checksum=

**Additional information**
* PeerTube version and URL: Peertube 2.4.0, https://framatube.org
* Browser name and version: Firefox Developer Edition 83.0b4

**Comment by Findus23** [comment]
This seems to be hardcoded here:
https://github.com/Chocobozzz/PeerTube/blob/512decf37ee6d36d0f16bda0f9bec6bf37d132b3/client/src/assets/player/videojs-components/theater-button.ts#L19
https://github.com/Chocobozzz/PeerTube/blob/512decf37ee6d36d0f16bda0f9bec6bf37d132b3/client/src/assets/player/videojs-components/theater-button.ts#L31-L35

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/c1961762b31567057e32eb7432a6995a4a81075c
