### ISSUE TITLE
Error Trying to run upload.js --help

### ISSUE THREAD

**Issue by zicmama** [Chocobozzz/PeerTube#323]
* **PeerTube version or commit: peertube-v1.0.0-alpha.3**
* **Browser name/version: **
* **NodeJS version: v8.9.4**
* **PostgreSQL version: postgresql-9.5**

* **What is the expected behaviour?**
Trying to run upload.js --help
* **What do you see instead?**
node dist/server/tools/upload.js --help
module.js:540
    throw err;
    ^

Error: Cannot find module 'supertest'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/peertube/versions/peertube-v1.0.0-alpha.3/dist/server/tests/utils/server/activitypub.js:3:17)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

I followed install instructions from https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md for "peertube-v0.0.20-alpha"
Upgraded to "peertube-v1.0.0-alpha.3"

**Comment by Chocobozzz** [comment]
Hi @zicmama, thanks for the issue.

I added documentation for this script: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md

You need to run `yarn install` without the `--production` flag to run server tools scripts (see the Installation section in documentation).

**Comment by zicmama** [comment]
I followed documentation, but 

```
yarn install
yarn install v1.5.1
error An unexpected error occurred: "EISDIR: illegal operation on a directory, read".

```
gives me an errror?

**Comment by Chocobozzz** [comment]
@zicmama I guess you have user rights issues? Check the cloned directory rights/owner.

**Comment by zicmama** [comment]
This is weird, I just downloaded files through git, so all files are owned by my user.
should I run "sudo yarn install" ? Or have a more detailed log to know what directory is not readable

**Comment by Chocobozzz** [comment]
@zicmama No don't sudo, it seems there are some issues in yarn repository about this error: https://github.com/yarnpkg/yarn/search?q=yarn+EISDIR%3A+illegal+operation+on+a+directory%2C+read&type=Issues&utf8=%E2%9C%93

**Comment by zicmama** [comment]
Ouch!: I could have run yarn with sudo in the past. I don't remember, but it has great chance to be.
I will have to investigate what is yarn "root owned" files now...
