### ISSUE TITLE
Notification crash with orphan actor

### ISSUE THREAD

**Issue by peertubenotificationerror** [Chocobozzz/PeerTube#3230]
All of a sudden I am getting this error when looking at my notifications. This only occurs on my account. I have logged in as root and created a new user and notifications work fine for those users. Other users are not reporting issues.

I have made zero changes and I have only the annotations plugin enabled.

This shows up in my server log when I try to view notifications. I also cannot see previous notifications, it has become blanked out:

`error[10/26/2020, 8:50:12 PM] Error in controller.
{
  "err": "TypeError: Cannot read property 'getDisplayName' of null\n    at self.toFormattedJSON (/var/www/peertube/dist/server/models/account/user-notification.js:146:120)\n    at /var/www/peertube/dist/server/helpers/utils.js:24:49\n    at Array.map (<anonymous>)\n    at Object.getFormattedObjects (/var/www/peertube/dist/server/helpers/utils.js:24:38)\n    at /var/www/peertube/dist/server/controllers/api/users/my-notifications.js:52:33\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/node_modules/tslib/tslib.js:111:62)"
}`

**Additional information**
* PeerTube version and URL: 2.4.0
* Browser name and version: Any browser on any platform

**Comment by peertubenotificationerror** [comment]
In the network tool in Firefox, when clicking on my icon to see notifications or going to /my-account/notifications, i get a 500 error. When double clicking on it, I get the following:

JSON
error | "Token is invalid."
-- | --
code | "unauthorized_request"

Raw Data
`{"error":"Token is invalid.","code":"unauthorized_request"}`

**Comment by Chocobozzz** [comment]
Thanks for the issue. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/2af337c83905c420b2d9022ee6fd3d6ef5fd1e42
