### ISSUE TITLE
multiple smtp issues/bugs in peertube 2.4.0 

### ISSUE THREAD

**Issue by tonyppe** [Chocobozzz/PeerTube#3231]
**What happened?**

1. "contact administrator" form is not working - emails always attempt to be sent to admin@example.com
2. peertube service cannot start due to failing smtp validation. Validation fails because smtp server closes the connection. The smtp server closes the connection because peertube sends SMTP command: `EHLO [127.0.0.1]` and the "[" is causing smtp server to close the connection. However it should be sending "EHLO company.com" anyway. 

**What do you expect to happen instead?**

SMTP should be working and admin contact form should be working.

This is my yaml config relating to the smpt config (we use google g.suite and I have a working smtp relay configured) 

~~~
# SMTP server to send emails
smtp:
  # smtp or sendmail
  transport: smtp
  # Path to sendmail command. Required if you use sendmail transport
  sendmail: /sbin/sendmail
  hostname: smtp-relay.gmail.com
  port: 25 # If you use StartTLS: 587
  username: null
  password: null
  tls: false # If you use StartTLS: false
  disable_starttls: true
  ca_file: null # Used for self signed certificates
  from_address: 'no-reply@company.com'
~~~
**And then for the admin form:**
~~~
admin:
  # Used to generate the root user at first startup
  # And to receive emails from the contact form
  email: 'tony.p@company.com'

contact_form:
  enabled: true
~~~

The first issue I am not sure how it began. I did successfully start and test smtp but then someone reported that the contact form was not working. I then fixed the admin: section above and changed the email from admin@example.com to a group email. I restarted peertube and peertube failed to start. 

I took a wireshark capture and I found this happening: 
1. peertube sends `EHLO [127.0.0.1]` 
2. smtp server closes the connection with `421 4.7.0 Try again later, closing connection`

To troubleshoot the above I used telnet to send an email manually. I found that `EHLO 127.0.0.1` would have worked but `EHLO [127.0.0.1]` would always throw the error and close the connection. In any case, the peertube server does have a name so I dont know where it is getting the 127 from, especially in the square brackets. So to resolve this one I modified the code in `node_modules/nodemailer/lib/smtp-connection/index.js`

I changed line 1208: `this._sendCommand('EHLO ' + this.name);` to `this._sendCommand('EHLO company.com');`

Immediately after saving the file, peertube was no longer stuck in a restart service loop. 

The admin contact form is still broken. Checking the logs at `storage/logs/peertube1.log` I see it's still trying to send to admin@example:
~~~
{"level":"info","message":"Connection established to 74.125.200.28:25","label":"view.company.com:443","component":"smtp-connection","sid":"gjVo7FIov6M","tnx":"network","localAddress":"192.168.4.223","localPort":51662,"remoteAddress":"74.125.200.28","remotePort":25,"timestamp":"2020-10-27T07:43:59.449Z"}
{"level":"info","message":"Sending message <3293f30d-3ab9-fdf2-e1c8-e2ace98846c5@company.com> to <admin@example.com>","label":"view.company.com:443","component":"smtp-transport","tnx":"send","messageId":"<3293f30d-3ab9-fdf2-e1c8-e2ace98846c5@company.com>","timestamp":"2020-10-27T07:44:00.107Z"}
~~~

I've been unsuccessful in resolving the admin@example contact form issue. 

**Additional information**
* PeerTube version and URL:  2.4.0
* Browser name and version: any
* NodeJS version: v10.22.1

* Link to browser console log if useful:
* Link to server log if useful (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by tonyppe** [comment]
Hi guys, do you need any further info on this? I wanted to ask if I have missed anything that you require from me? As other issues have comments and looks like they have been classed as `bug` but this one not yet. 

thanks

**Comment by rigelk** [comment]
@tonyppe could it be related to https://framacolibri.org/t/admin-contact-form-error-550-mailbox-not-available-despite-other-emails-working/9436 ?

The fact that your SMTP hostname gets translated as 127.0.0.1 when sent by is troubling. Could it be a DNS problem on your machine?

**Comment by tonyppe** [comment]
Hi Rigel, not using docker here. I followed the install guide on this github site / links for CentOS 7 install. The only issues (we've noticed) are what I've explained here above. 

The IP address would be OK for the first issue. The actual issue there is the square bracket `[`. When the smtp server recieves the `[` it closes the connection with an error. So it would successfully send a mail with `EHLO 127.0.0.1` but it is failing to send when using `EHLO [127.0.0.1]`. I hope my explanation is making sense with this regard as I'm not sure how else to explain it. Please do let me know if not and I'll try my best another way. 

I checked out the link that you mentioned and it is relating to the admin contact form. The OP of the link does indeed appear to have the same issue as I have explained in part 2 above (second issue being reported). The 2nd issue seems to relate to the .yaml configuration for the admin email address. Regardless of what you have configured for the admin email in the .yaml, the default of `admin@example.com` always seems to be applied. This is causing the admin contact form to try and send the mail to `admin@example.com` and therefore it never reaches the real admin.

**Comment by Chocobozzz** [comment]
Hello,

Sorry for the late answer. For `admin@example.com` issue, check the admin email of the `root` user (on settings page).

For your `EHLO` I suggest you to create an issue on nodemailer repo: https://github.com/nodemailer/nodemailer. If this is a bug and they fix it, I'll be happy to update the dep' in PeerTube

**Comment by tonyppe** [comment]
Hi, after updating the root user email address I retried the admin contact form and unfortunately no email is ever received. Furthermore it's proving difficult to test because after sending one mail the system prevents sending a 2nd one. Do you know how to turn this off temporarily? 

I used tcpdump and the email server is never contacted. 

Looking at the storage log we now have: 
`{"level":"info","message":"Processing email in job 11.","label":"vue.company.com:443","timestamp":"2020-11-10T02:56:31.772Z"}
{"err":{"code":"PUG:INVALID_INDENTATION","msg":"Invalid indentation, you can use tabs or spaces but not both","line":80,"column":1,"filename":"/var/www/peertube/versions/peertube-v2.4.0/dist/server/lib/emails/common/base.pug"},"level":"error","message":"Error in email sender.","label":"vue.company.com:443","timestamp":"2020-11-10T02:56:31.787Z"}`

I was actually considering deleting the root user, would this further break email?

**Comment by tonyppe** [comment]
Any ideas how to reopen this issue? Or do I need to duplicate this issue to a new issue now that it's been closed?

**Comment by Chocobozzz** [comment]
> Do you know how to turn this off temporarily?

Yes, comment this line in the compiled code (`/dist/server`): https://github.com/Chocobozzz/PeerTube/blob/develop/server/middlewares/validators/server.ts#L59

Did you update `/var/www/peertube/versions/peertube-v2.4.0/dist/server/lib/emails/common/base.pug` file?

**Comment by tonyppe** [comment]
`Did you update /var/www/peertube/versions/peertube-v2.4.0/dist/server/lib/emails/common/base.pug file?`

No I didnt know that I had to 🙈 Do you have a link or anything that I could follow to understand what needs to be done?

**Comment by Chocobozzz** [comment]
Please could you pastebin its content? Also, does this error appear every time you submit the contact form?

**Comment by tonyppe** [comment]
1. pastebin link: http://paste.openstack.org/show/800079/ 
2. yes at the time i raised the issue

Could you please provide the information to me about the changes you mentioned to me in base.pug to get this working?

**Comment by Chocobozzz** [comment]
You must not update `base.pug`. But it seems you had (compare with the same file in the official release). I think it's the reason why you have the `PUG:INVALID_INDENTATION` error. Revert your change or reinstall peertube and retest the contact form to see if it works.

**Comment by tonyppe** [comment]
My apologies. The file I attached was one that we are currently using since this week but this issue began when I reported the issue a while ago now. Since it's been difficult to discuss the issue here, we went ahead with some customisations this week so that we're not held up. 

The issue remains even with the unmodified / original file. 

Any other suggestions?
