### ISSUE TITLE
Disable adaptive bitrate streaming when using HLS on short videos

### ISSUE THREAD

**Issue by Roki100** [Chocobozzz/PeerTube#3233]
Is that possible to somehow disable the adaptive bitrate streaming in HLS formats? (to reload the video like WebTorrent)
It makes HLS useless for very short videos, for example, if 9 second video is encoded to 480p, 5 seconds of it is 480p until quality change kicks in.
I have 100MB short videos (1080p60) that load so slowly with WebTorrent but i cant use HLS due to that sudden quality change.

**Comment by Roki100** [comment]
i would like to just have a simple tick in instance settings that would disable that

**Comment by Roki100** [comment]
Hello @rigelk is there any update regarding this? will this be a feature or it's not being considered?

**Comment by Chocobozzz** [comment]
Maybe the underlying issue is that the hls player does not remember your last bandwidth?

**Comment by Roki100** [comment]
> Maybe the underlying issue is that the hls player does not remember your last bandwidth average?

i am not sure but i don't think so

**Comment by Roki100** [comment]
Hello, any updates on this?
It doesnt look complex to implement and it would allow me to use my instance without issues - i (and some more people) hate the "smooth" quality changes in general - they should be instant, so having such setting in instance settings/config would be useful

**Comment by rigelk** [comment]
> Hello, any updates on this?
> It doesnt look complex to implement

The issue is labelled as ongoing discussion, so no implementation can be made yet. For it to be labelled as a confirmed enhancement target, the issue has to be understood. From @Chocobozzz's comment, there are still a few things left to understand the cause of your issue with the player's adaptative bitrate selection algorithm.

Could you fill the issue template? It has questions regarding your instance version and browser that might be useful. If your users have the same issue, better knowing their browser might help too.

**Comment by Roki100** [comment]
> > Hello, any updates on this?
> > It doesnt look complex to implement
> 
> The issue is labelled as ongoing discussion, so no implementation can be made yet ; this is not a strict rule but is usually representative of an issue's status. For it to be labelled as a confirmed enhancement target, the issue has to be understood. From my understanding of @Chocobozzz's comment, there are still a few things left to understand the cause of your issue with the player's adaptative bitrate selection algorithm.
> 
> Could you fill the issue template? It has questions regarding your instance version and browser that might be useful. If your users have the same issue, better knowing their browser might help too.

i mean that isnt really a bug/issue with peertube but a feature request/setting because of annoying behaviour where quality changes on hls take ages (i mean when you MANUALLY change from for example 720p to 1080p it takes few seconds to apply, and when you seek back, the part is still 720p, while webtorrent reloads the player to change the quality of WHOLE video INSTANTLY, and that is the behaviour i would like to see with hls, either optional in instance settings or config) 

the instance and browser version feels useless in this case but there:
Instance version: 2.4.0 (i will be updating it soon)
Browsers tested: Opera GX, Opera, Chrome, Firefox, Brave, Edge and Vivaldi
