### ISSUE TITLE
Pagination bug for /admin/system/jobs

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#3235]
**What happened?**
On page /admin/system/jobs, the pagination seems to be done without taking into account the job type filter. 
For example, if I set the filter to type=email, I have 2 jobs on first page, then many empty page.

![image](https://user-images.githubusercontent.com/38844060/97640655-887caa80-1a41-11eb-9e4f-2c73e7ff9f72.png)
![image](https://user-images.githubusercontent.com/38844060/97640685-98948a00-1a41-11eb-8db7-1f64ba033016.png)

PS: it should be nice to display all states

**Steps to reproduce:**

1. Go to /admin/system/jobs

2. Filters : type=email, status=completed

**Additional information**
* PeerTube version and URL: 2.4.0
* Browser name and version: Firefox

**Comment by Chocobozzz** [comment]
Thanks for the issue. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/439d68e53766d48e7316aab6b6f78cd555247f6e
