### ISSUE TITLE
Unable to delete channel 

### ISSUE THREAD

**Issue by raphgilles** [Chocobozzz/PeerTube#3237]
Hello,

I just noticed that it's not possible to delete a channel anymore. I tried on multiple instances based on the 2.4.0 version and the same issue appear :
I have to write the name of the channel, and the confirmation button stay grey tinted and unclickable.

Thanks !

**Comment by prolibre** [comment]
Same on my side. I deleted all the videos of the channel but when I want to delete it (after copying the name in the field), the button remains inactive. I tested under firefox and chrome.

**Comment by raphgilles** [comment]
> UPDATE : **I got around the problem by removing `disable=''` in the code (firefox console)**

Thanks for this trick !

**Comment by achaiah** [comment]
Yes I have been experiencing the same problem on PeerTube 2.4. Thanks for the trick to get around this (for now). Hope they fix it soon!

**Comment by geopayme** [comment]
What if you use brave or chrome? (I dont want to install firefox on my mac)

**Comment by achaiah** [comment]
@geopayme I tried Chrome and Safari and the same problem exists.

**Comment by Chocobozzz** [comment]
Hello,

Sorry about that. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/d88c490d38aa7c75c42aeaa15fc412f53f48811c

**Comment by mayhair** [comment]
> UPDATE : **I got around the problem by removing `disable=''` in the code (firefox console)**
How do I do that?

**Comment by achaiah** [comment]
In Firefox open Menu -> Web Developer -> Console. Find the `disable=` tag and remove it. Then the button will be enabled again.

**Comment by mayhair** [comment]
@achaiah, it turns out I had to use the Inspector and not the console. Thanks! :)
