### ISSUE TITLE
Cannot update video tag to unicode-length == 2

### ISSUE THREAD

**Issue by gai00** [Chocobozzz/PeerTube#3238]
**What happened?**
Cannot create/update video tag to unicode-length == 2

**What do you expect to happen instead?**
video tag can be saved when length == 2.

**Steps to reproduce:**

1. upload any video or update any video.

2. add one tag with length == 2.

3. submit button turn to disabled. and show me message: tag length must be greater than 2.

**Additional information**
This problem occured after version upgraded.

* PeerTube version and URL: 
2.4.0 (Docker: chocobozzz/peertube:production-buster)
* Browser name and version: 
chrome
* NodeJS version: 

* Link to browser console log if useful:
* Link to server log if useful (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Please fill the template

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/4ddcb7c3bad4e98d05d25298f7f11353a639b360
