### ISSUE TITLE
[Bug] Youtube Upload gives error Fix in desc.

### ISSUE THREAD

**Issue by anon97945** [Chocobozzz/PeerTube#3240]
**What happened?**
Youtube upload is buggy since youtube-dl is "outdated"
**What do you expect to happen instead?**
Upload youtube Video
**Steps to reproduce:**

1. Try to Upload https://www.youtube.com/watch?v=27e0A74_4Lc

2. Upload will give "error Cannot fetch remote information of this URL."
    This error is because of "ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug"

This repo of ytdl fix the problem i confirmed on local PC with both youtube-dl ... original gives error, updated is working.
Link to repo:

https://github.com/blackjack4494/yt-dlc

**Comment by Chocobozzz** [comment]
I'm sorry but I don't understand. If this is a youtube-dl bug, then this needs to be fixed upstream and not in a fork.

**Comment by anon97945** [comment]
There is no youtube-dl anymore since it got banned.

**Comment by rigelk** [comment]
@anon97945 we're aware of their dire situation, but they are the most able to fix this. Please report this issue to them once their bug tracker is back up.
