### ISSUE TITLE
Allow moderators to prevent user from deleting specific videos

### ISSUE THREAD

**Issue by markvdb** [Chocobozzz/PeerTube#3242]
I'm looking into PeerTube as a potential video platform for public performing arts academies (music, spoken word, dance).

Looking into potential workflows, I bumped into a problem. The original uploader of a video file always has the option to delete it. PeerTube currently doesn't seem to have a way to prevent this. Giving moderators the ability to prevent a video's deletion might be one potential solution to our problem.

Would this fit the PeerTube philosophy and roadmap?

The use case/workflow I'm thinking of that this would fit into:
- Student or student's parent uploads video for comments by teacher and/or students from study group.
- Teacher and students from study group are subscribed to student's channel.
- Teacher sees student video and comments.
  - If this is just a video to sollicit feedback/help by the teacher or other students, it's a somewhat ephemeral video. No need to keep it for eternity.
    Might even build an expiry mechanism for auto pruning ephemeral videos, saving precious disk space. I'll create another issue for this.
  - If this is a really good piece of work by the student, it should end up in the student's portfolio. This is something we want to keep for a student's entire career as a student at the academy, and possibly longer for archival purposes.
  - If the video is stellarly good, it might even end up becoming educational material primarily used by teachers to show other students.

**Comment by rigelk** [comment]
@markvdb please don't tag issues yourself in the title, which should only describe the requested feature or bug to solve.

**Comment by markvdb** [comment]
> @markvdb please don't tag issues yourself in the title, which should only describe the requested feature or bug to solve.
Sorry. I will keep that in mind next time.

Thank you for your incredibly quick reply.

**Comment by Chocobozzz** [comment]
Hi,

> Would this fit the PeerTube philosophy and roadmap?

No sorry. But I think a plugin could be developed to resolve your use case.
