### ISSUE TITLE
Ephemeral video

### ISSUE THREAD

**Issue by markvdb** [Chocobozzz/PeerTube#3243]
Some videos might be ephemeral. It would be great if they could expiry in some way. See also #3242 .

Maybe a minimalistic implementation could be based upon an expiry bit? If the bit is set on a video, and storage limits get reached (disk full/s3 quote/preset quota...), the oldest file with the expiry bit set gets pruned.

Would something along these lines fit the PeerTube philosophy and roadmap?

**Comment by rigelk** [comment]
Duplicate of #1289, see https://github.com/Chocobozzz/PeerTube/issues/1289#issuecomment-680021457
