### ISSUE TITLE
In the docs, why is regular installation "recommended" while docker installation isn't?

### ISSUE THREAD

**Issue by paulbernhard** [Chocobozzz/PeerTube#3244]
Hi,

thanks a lot to everybody working on this, it's such a relief to know these ways of sharing exist and people are concerned.

I installed an instance on my server and chose the installation via the [Docker installation](https://docs.joinpeertube.org/#/install-docker). First of all, the installation process was a bliss and a had a running instance up in about one hour. I chose to use Docker because i appreciate the coherence and independence of containers; also i made have to move mt PeerTube instance and thought it to be more portable running on docker.

I do not really understand why the [Install on any OS](https://docs.joinpeertube.org/#/install-any-os) is labeled as *(recommended)*, while the [Docker installation](https://docs.joinpeertube.org/#/install-docker) isn't. When using PeerTube in production, is there anything to be favoured about the "regular" installation over the Docker installation?

Thanks,
Paul

**Comment by rigelk** [comment]
hi @paulbernhard,

The docker installation is known to be inferior, notably in terms of its reverse-proxy configuration since it doesn’t use the Nginx configuration and its optimizations (see #2531). Then, it is also harder to debug for us when you have an issue with it.

**Comment by paulbernhard** [comment]
Hi @rigelk,

thanks for your response, in this case i'd prefer to use the regular installation. As you said *the docker installation is known to be inferiour*, i think it would be helpful to mention the disadvantages on the docker installation guide. 

In any case, thanks,
Paul

**Comment by magdesign** [comment]
The regular installation is quite "hard" to install (treid several hours on Ubuntu) while the docker one is installed extremely fast.
The only downside as mentioned is to get the reverse_proxy setup....which is nowhere really documented yet.
