### ISSUE TITLE
markdown emoji list- one long list

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3245]
![Screenshot_20201102_153421](https://user-images.githubusercontent.com/39449563/97855596-f7e3ea00-1d20-11eb-95bc-c52f9f6f11b7.png)
markdown emoji list button "view complete list" shows the entire emojis in one LONG list. We can easily have 2-3 columns and the vertical scroll would be greatly reduced. the current one makes going back up very difficult as there are 151 entries. 2 columns would get us 1/3 scroll

**Additional information**
* PeerTube version and URL:
* Browser name and version:
* NodeJS version:

* Link to browser console log if useful:
* Link to server log if useful (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by rigelk** [comment]
@kimsible would you be up for that?

**Comment by kimsible** [comment]
@rigelk thanks for notifying me.

@test2a thanks for your this remark ! 

Sure I'm up for that =).
