### ISSUE TITLE
Playing a video doesn't always start from the beginning of it

### ISSUE THREAD

**Issue by lamarios** [Chocobozzz/PeerTube#3248]
**What happened?**
Playing a video doesn't always start from the beginning of it
**What do you expect to happen instead?**
The video to start from the beginning
**Steps to reproduce:**

1. Load  a video page

2. press play

**Additional information**
* PeerTube version and URL:
Version 2.4.0
example video of my instance: https://tube.ftpix.com/videos/watch/16e698ae-cc53-4a06-b437-1814b6d37fad
* Browser name and version: Firefox v82 on linux, also happens on iOS v14
* NodeJS version: deployed using docker image

**Comment by Chocobozzz** [comment]
Hello,

PeerTube remembers your last view and tries to resume the video.

**Comment by lamarios** [comment]
Any way to disable that ?

**Comment by Chocobozzz** [comment]
Yes, you can disable Video history in **History** page

**Comment by lamarios** [comment]
Awesome thanks !
