### ISSUE TITLE
Display help regarding supported formats

### ISSUE THREAD

**Issue by conferences-gesticulees** [Chocobozzz/PeerTube#325]
If a user upload a video in an unsupported format, they don't get any help on which formats are actually supported.

In an ideal world, they should never wait for a video in the wrong format to be uploaded, as they won't get anything except an error message. But there's currently hardly any guidance in the upload process regarding this aspect.

**Comment by Chocobozzz** [comment]
In theory, the upload dialog should not display non supported files. With what type of file did you get an error?

**Comment by conferences-gesticulees** [comment]
This was a `.avi`, but I don't know which codecs and the likes. I can ask details if needed.

**Comment by Chocobozzz** [comment]
Codecs should not be necessary, `.avi` files are not supported, no matter what the codecs are.

Maybe you (or the person who did this upload) could retry to upload this AVI file with the latest version of PeerTube to see if the issue was fixed? In the past we did not filter the video files in the file chooser dialog.

**Comment by dedesite** [comment]
Sorry if my question has already been answered but why `.avi` containers aren't supported ? Peertube server doesn't do format transcoding via gstreamer ? So theorically, any video format should be fine, no ?

**Comment by Chocobozzz** [comment]
Yes we can accept other video formats if transcoding is enabled. Feel free to open an issue :)

FYI we transcode videos with ffmpeg ;)

**Comment by gabEDS** [comment]
Hi, I'm the user who tried to upload a ``.avi`` file mentioned by @conferences-gesticulees .
I tried and failed this morning, was PeerTube at the latest version ?

**Comment by dedesite** [comment]
Ok thanks for your reply. I didn't recall if you use ffmpeg or gstreamer :) ! Issue opened #326

**Comment by Chocobozzz** [comment]
@gabEDS Yes it was. Could you display a screenshot of the file chooser dialog in you .avi video directory? (the window when you click on the "Select the file to upload" button)

**Comment by gabEDS** [comment]
![screenshot from 2018-03-06 20-32-00](https://user-images.githubusercontent.com/37121044/37053816-7b52f680-217d-11e8-8eef-0abf705ecdb0.png)
nothing here.. I don't remember if I drag and drop the file or something else...

**Comment by Chocobozzz** [comment]
@gabEDS Maybe you change the "All supported types" value in the bottom right. But I think I'll add another check :)

**Comment by gabEDS** [comment]
> Maybe you change the "All supported types" value in the bottom right. 

typically me :-P

**Comment by isAAAc** [comment]
Same trouble with mp4 :/

**Comment by rigelk** [comment]
A hint is now displayed along the upload form.
