### ISSUE TITLE
Embed player: how to switch off the black gradient in top of the video?

### ISSUE THREAD

**Issue by ovomatik** [Chocobozzz/PeerTube#3251]
**What happened?**
When I share a video via iframe without Title or Warning Title, there is a black gradient in the top of the video:
https://tv.abzy.me/videos/embed/66819a36-6e4c-4da9-b17d-13d75c58b3aa?title=0&warningTitle=0&peertubeLink=0
**What do you expect to happen instead?**
Because there is no title and no warning title, why these gradient stay? How can I delete it?
**Steps to reproduce:**
Check on links bellow

Kind regards

**Additional information**
* PeerTube version: 2.4.0

**Comment by Chocobozzz** [comment]
Thanks for the issue. Fixed in https://github.com/Chocobozzz/PeerTube/commit/b9da21bd5a3ad00f44997930391e3316182a07db
