### ISSUE TITLE
Stale architecture docs

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3252]
[Architecture - What is an instance and how does it work](https://docs.joinpeertube.org/#/contribute-architecture?id=what-is-an-instance-and-how-does-it-work) says the following:
> * If a user wants to watch a video, they ask its instance the magnet URI and the frontend adds the torrent (with WebTorrent), creates the HTML5 video player and streams the file into it.
> * A user watching a video seeds it too (BitTorrent). Thus, another user who is watching the same video can get the data from the origin server and other users watching it.

Since HLS is now an alternative the docs should be updated accordingly. Below is my proposal:
* If a user wants to watch a video
  * If using WebTorrent: they ask its instance the magnet URI and the frontend adds the torrent (with WebTorrent), creates the HTML5 video player and streams the file into it.
  * If using HLS with P2P: they'll load the [M3U8 playlist](https://en.wikipedia.org/wiki/M3U#M3U8) from the `video` tag which will start buffering the video. The player will choose the video player depending on the network throughput, you can read more about that [at Doug Sillars blog](https://dougsillars.com/2017/10/26/how-hls-adaptive-bitrate-works/).
* A user watching a video seeds it too (BitTorrent or [WebRTC](https://github.com/novage/p2p-media-loader)). Thus, another user who is watching the same video can get the data from the origin server and other users watching it.

I'll create an issue here while I'm waiting to be approved at the Framagit GitLab.

**Comment by rigelk** [comment]
@kontrollanten you should be good to go on framagit! Please link back your MR here once you are done modifying the architectuer docs.

**Comment by kontrollanten** [comment]
@rigelk https://framagit.org/framasoft/peertube/documentation/-/merge_requests/75

Other parts that needs updates:
* https://docs.joinpeertube.org/#/contribute-architecture?id=communications-between-instances
* https://docs.joinpeertube.org/#/contribute-architecture?id=redundancy-between-instances
* https://docs.joinpeertube.org/#/contribute-architecture?id=architecture-1

**Comment by Chocobozzz** [comment]
I updated the architecture document in https://framagit.org/framasoft/peertube/documentation/-/commit/3a7c3bc7151b7679817c49f5840a6c62e9c14958
