### ISSUE TITLE
No render for comment in notification e-mail

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#3254]
Here is an example of how the html content of the comment is stringified is notification e-mails.

![Capture d’écran du 2020-11-05 22-08-26](https://user-images.githubusercontent.com/1877318/98297304-82904780-1fb4-11eb-95a0-5b79a9395f9a.png)

**Comment by rigelk** [comment]
Thanks for the PR @kimsible! (and very nice choice of music)
