### ISSUE TITLE
Torrent based download didn't use the data already in my browser

### ISSUE THREAD

**Issue by JensKorte** [Chocobozzz/PeerTube#3257]
**What happened?**
I watched a video for some minutes, even selected a fixed quality and decided to download it using torrent. I selected the same quality/resolution. The download worked w/o problems, but showed just the seeder, no peers. The browser tab was still active.

**What do you expect to happen instead?**
I expected that the torrent client (Deluge) should download from the broswer tab too, since, afaik it is a torrent client. Could the browser be added as a resource, like 127.0.0.1:12345 to the torrent file?

**Steps to reproduce:**

1. select a video, select quality, wait a minute to download some data
2. download the video as torrent with the same quality
3. have a look at your torrent file or client if the torrent is downloaded from localhost

**Comment by rigelk** [comment]
Hi @JensKorte,

Deluge doesn't support WebTorrent and thus doesn't appear as such in the counter.
