### ISSUE TITLE
Theater mode does not collapse sidebar

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3259]
**What happened?**
entering theater mode should cover the entire 100% of screen width which it does but the sidebar remains stuck onscreen. it "should" collapse the sidebar so that full width is used. check screenshots

The first screenshot below is default result on pressing theater mode button. second screenshot is after manually collapsing the sidebar.

![Screenshot_20201104_215201](https://user-images.githubusercontent.com/39449563/98137703-4becfb00-1ee8-11eb-9883-674dc2c21bbb.png)

![Screenshot_20201104_215220](https://user-images.githubusercontent.com/39449563/98137711-4e4f5500-1ee8-11eb-8dd6-6dbe9667362b.png)

_Originally posted by @test2a in https://github.com/Chocobozzz/PeerTube/issues/431#issuecomment-721834226_

**Additional information**
* PeerTube version and URL: 2.4.0 
* Browser name and version:
* NodeJS version:

**Comment by rigelk** [comment]
Whether it should collapse is debatable. We have fundamentally a different need for the sidebar than Youtube.

**Comment by Chocobozzz** [comment]
Closing this inactive discussion, as @rigelk said we don't really want to automatically close the menu depending on the player state.
