### ISSUE TITLE
Transcoding stuck on video imports

### ISSUE THREAD

**Issue by anon97945** [Chocobozzz/PeerTube#3263]
**What happened?**
This Video and multiple others are just not get Transcoded. Don't know why.

**What do you expect to happen instead?**
Transcoding of the Video. I already reuploaded. And its not only this but even this:
PeerTube Youtube Upload: https://gorf.tube/videos/watch/45de3356-9c8b-49e1-9e72-cbcb318d48b5
Yotube Original: https://www.youtube.com/watch?v=Yf1nWoxQQSY

Below is a Transcoded one so i think its has something to do with the Videos above..
Youtube Original: https://www.youtube.com/watch?v=jiwuQ6UHMQg
PeerTube Youtube Upload: https://gorf.tube/videos/watch/3f77a508-3329-459b-a2cb-61e46df7ea97

**Steps to reproduce:**

1. youtube upload: https://www.youtube.com/watch?v=ihZwWD4MFtA
(PeerTube Youtube Upload: https://gorf.tube/videos/watch/52dbe4bd-d658-4af2-98d9-5ddc680ae41e)
2. It will never Transcode.

**Additional information**
* PeerTube version and URL: https://gorf.tube Version 2.4
* Browser name and version: Brave Version 1.16.72 Chromium: 86.0.4240.183 (Offizieller Build) (64-Bit)
* NodeJS version:

* Link to browser console log if useful: Not Admin
* Link to server log if useful (`journalctl` or `/var/www/peertube/storage/logs/`): Not Admin

**Comment by rigelk** [comment]
We are going to need the failed job logs for the video transcodes

**Comment by rigelk** [comment]
Also, please don't tag your issue title yourself.
