### ISSUE TITLE
Allow custom transcode command and profiles

### ISSUE THREAD

**Issue by narcisgarcia** [Chocobozzz/PeerTube#3264]
This feature request is to allow configure Peertube instance to manage _transcode profiles_, each one with possibility to write own transcode command.

For example, I want to be able to select named profiles to encode uploaded clips:
- "Low rate" profile: 640x480px 15fps at VP9/300kbps video and Vorbis/64kbps audio
`avconv -v info -i "uploaded720x480.mp4" -bufsize 272k -b:v 300k -qmin 0 -qmax 63 -r 15 -s 640x426 -c:a libvorbis -ar 22050 -ac 1 -b:a 64k -q:a 5 -y "encoded.webm"`
- "Very low rate" profile: 640x480px 14fps at VP9/200kbps video and Vorbis/56kbps audio
`avconv -v info -i "uploaded720x480.mp4" -bufsize 272k -b:v 200k -qmin 0 -qmax 63 -r 14 -s 640x426 -c:a libvorbis -ar 22050 -ac 1 -b:a 56k -q:a 5 -y "encoded.webm"`

And also options to adopt this:
- Admin sets "A mandatory profite for all users"
- Admin sets "A default profile for all users. Users can select their own default"
- When able to do it, user sets "My default profile for all uploads"
- When able to do it, user sets "Select profile used on last upload"

**Comment by rigelk** [comment]
Please don't tag your issue title yourself.

**Comment by markvdb** [comment]
This might be one way to enable vaapi hw based encoding on bare metal intel servers too.

**Comment by SimplyCorbett** [comment]
Can we get this implemented? I'd love to see support for VP9 and hardware transcoding.

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/2442

**Comment by narcisgarcia** [comment]
I think #2442 is a reduced set of this feature request.

- What about custom ffmpeg syntax to set fps, audio compression and channels, and maybe container and codecs formats?
- And what about default and/or mandatory application policies?
