### ISSUE TITLE
Video format or resolution limitations

### ISSUE THREAD

**Issue by narcisgarcia** [Chocobozzz/PeerTube#3265]
I’m trying a Peertube 2.4.0 node, and have an issue with uploaded videos when trying to play then on Firefox
(« The media playback was aborted due to a corruption problem or because the media used features your browser did not support »)

- 320x240 MP4 25fps: fails
- 320x240 MP4 30fps: fails
- 450x360 MP4 30fps: fails
- 848x480 MP4 25fps: plays
- 1280x720 MP4 24fps: plays
- 1280x720 MP4 25fps: plays

Same behaviour with: Firefox 52, Firefox 78
BUT all videos play well with: Midori 7, Iridium 2019.04

Peertube has configured 360p and 720p as resolutions to generate (is this related to issue?).

**Comment by rigelk** [comment]
Please include reference to/in previous discussions in case someone contributes here: https://framacolibri.org/t/video-format-or-resolution-limitations/9647

**Comment by rigelk** [comment]
Could you provide the source file and transcoding job logs, as well as ffmpeg version and instance configuration related to webtorrent/hls?

**Comment by narcisgarcia** [comment]
> Could you provide the source file and transcoding job logs, as well as ffmpeg version and instance configuration related to webtorrent/hls?

I don't find job logs through web interface. What concrete file should contain them?
```
$ ffmpeg -version
ffmpeg version 4.1.6-1~deb10u1
```
I don't know where to find that webtorrent/hls configurations.

**Comment by Chocobozzz** [comment]
Hello,

What is your instance URL?

**Comment by narcisgarcia** [comment]
I'm sorry; I can't give URLs in public or outside of project's team.
