### ISSUE TITLE
White page on Firefox 48.0.2 on Mac OS X 10.6.8 (10K549)

### ISSUE THREAD

**Issue by conferences-gesticulees** [Chocobozzz/PeerTube#327]
One user reported they only see a blank page on PeerTube sites, using Firefox 48.0.2 on Mac OS X 10.6.8 (10K549). I know there's no support anymore for such an old version, but at least an error message explaining the situation would be good.

**Comment by Chocobozzz** [comment]
It's not trivial to detect non compatible web browsers but I tried something: https://github.com/Chocobozzz/PeerTube/commit/73e09f270660c78e50e86921a5ca6b356f760c7c
