### ISSUE TITLE
How to set development environment

### ISSUE THREAD

**Issue by jinbeomdev** [Chocobozzz/PeerTube#3271]
Hello. I want to study how to upload/download video in real world such as Youtube. eventually I find good open source project, PeerTube. Thank you you guys efforts.

I want to set development environment not creating Instance PeerTube. But, I'm not familiar with TypeScript, yarn....
Can you advise me?

**Comment by rigelk** [comment]
hi @jinbeomdev and thanks for your insterest in PeerTube!

Have you had a try at https://github.com/Chocobozzz/PeerTube/blob/develop/.github/CONTRIBUTING.md#develop? There are multiple options described there, including leaving the development setup to Gitpod if you really want a quick try at it.

**Comment by jinbeomdev** [comment]
I appreciate your help. I've never seen that document. So sorry. It really works well. I hope someday I could contribute PeerTube.
