### ISSUE TITLE
Discover page for channels

### ISSUE THREAD

**Issue by klorydryk** [Chocobozzz/PeerTube#3273]
When we publish videos in different channels, it is because this videos are very different in there meaning or origin.
But when a visitor show up, he only sees a list with all videos and no information about the different channels.

- I would increase the information of the visitors to display the channel name under the thumbnail (near the name of the account)
- I would add a selection feature to be able to select easily all videos of an account/channel in "local" page.

**Comment by test2a** [comment]
are you asking about a "discover" channels page instance wide or for a particular user only?

https://peertube.social/accounts/framasoft@framatube.org/video-channels

check this link. it shows for the user "framasoft" it has the following channels
* Lectures du Framablog
* Librecours Libre Culture
* MOOC-CHATONS#1 - Internet, reprendre le contrôle
* Mooc Comprendre l'Open Source
* Les vidéos de Framasoft

so if you are asking to check a users all channels, then this page shows that. in case you are asking a site wide discovery page of users and channels, then that is a feature request i guess

**Comment by klorydryk** [comment]
For my second wish, it seems ok. But the user will access to this page only by opening a video then click on the name of the user, isn't it? Too complicated.
On the [LQDN instance](https://video.lqdn.fr), we have 3 channels for the main user: "our videos", "press review" and "videos from other peoples". Visitors opening the website should understand quickly the difference between this different channels, and being able to switch between them.

**Comment by Chocobozzz** [comment]
Hello,

We now display the channel name below the video miniature. It's a link targetting the channel page, where you can see all channel's videos.

Regarding the feature to list/discover channels of the instance, subscribe to https://github.com/Chocobozzz/PeerTube/issues/1465.
