### ISSUE TITLE
Firefox's picture-in-picture feature interfers with resolution change

### ISSUE THREAD

**Issue by pprw** [Chocobozzz/PeerTube#3275]
In some situations (small screen, lots of resolutions available, windows resized, etc.) it is impossible to select a resolution because of firefox picture-in-picture (incrustration) native feature.

See:

![output](https://user-images.githubusercontent.com/5262986/98514599-03c43480-226a-11eb-9671-667fac7e2ae5.gif)

The links behind the resolution menu should be inactivated.

**Comment by rigelk** [comment]
Sounds like this could be addressed by videojs https://github.com/videojs/video.js/pull/6002#issuecomment-510620446

**Comment by highvoltage** [comment]
I fon't think it's possible for firefox to know about those extra controls over the video yet. For now if you just drag the picture-in-picture frame away then you'll be able to see the resolution button in the peertube tab and you can still change it there.

**Comment by JohnXLivingston** [comment]
I think this is a problem with firefox. I had it on peertube few days ago, but also on youtube.

**Comment by Chocobozzz** [comment]
Hello,

I also think it's a firefox bug. Not sure that we can do anything here.

**Comment by Chocobozzz** [comment]
I created a bug on firefox bug tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1742585
