### ISSUE TITLE
Separate web interface from system service and storage

### ISSUE THREAD

**Issue by narcisgarcia** [Chocobozzz/PeerTube#3276]
Feature request: Installation bundle to be split by having CMS separated, and this allows to install Peertube web interface in a shared webserver while this works with Peertube backend service from another host and data storage.
Similar to any CMS uses separated database backend.

This could be the beginning to allow multisite installations (multiple frontends for same storage and database backend).
The "channels" concept implementation can not be enough to separate contents in some social scenarios.

**Comment by Chocobozzz** [comment]
Hello,

You can already have a third party client that use another PeerTube backend.

**Comment by narcisgarcia** [comment]
Is there documentation about how to deploy a multisite installation with same Peertube backend?

**Comment by rigelk** [comment]
@narcisgarcia not that I know of
