### ISSUE TITLE
How to use system's youtube-dl or upgrade bundled youtube-dl

### ISSUE THREAD

**Issue by narcisgarcia** [Chocobozzz/PeerTube#3277]
I donwload and install Peertube. There comes /var/www/peertube/versions/peertube-v2.4.0/node_modules/youtube-dl but it's a concrete youtube-dl version.

I want to check and upgrade youtube-dl (cron.weekly) and I have 2 options:

- A) pip install --upgrade youtube_dl
- B) Peertube project's way to upgrade its bundled utilities.

The A option requires Peertube to have the ability to call system command for youtube_dl

**Comment by JohnXLivingston** [comment]
Peertube checks for youtube-dl update every 24 hours.

**Comment by rigelk** [comment]
The auto-updater within PeerTube is defined there: https://github.com/Chocobozzz/PeerTube/blob/develop/server/helpers/youtube-dl.ts#L133-L189

**Comment by narcisgarcia** [comment]
Okay, thank you.
