### ISSUE TITLE
Increase maximum video quota : 100GB and 200GB

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#3279]
The current maximum video quota is 50GB, with the new live feature, we may need to increase this maximum values for big channels :

- 100GB
- 200GB
- 500GB
- Unlimited 

![image](https://user-images.githubusercontent.com/1877318/98569916-2595d980-22b3-11eb-91af-8ad07e334c1d.png)

**Comment by Alterak** [comment]
Why are there only fixed quotas? It would be nice to add the ability for the administrator to set any quota himself.

**Comment by fmohican** [comment]
would be great feature 👍

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/21e493d4d8acb7a650eff3a30cd7e086b3cb8a28
