### ISSUE TITLE
LDAP Auth & Docker

### ISSUE THREAD

**Issue by tilllt** [Chocobozzz/PeerTube#3280]
Is it possible to install the LDAP Auth plugin for Peertube on an instance deployed via Docker, without building a custom container?

**Comment by rigelk** [comment]
Hi @tilllt,

You should be able to install the plugin [via the web interface](https://docs.joinpeertube.org/#/admin-customize-instance?id=install-a-plugin), as it is published on https://www.npmjs.com/package/peertube-plugin-auth-ldap

**Comment by tilllt** [comment]
Thanks. I was just blind. Working fine now.
