### ISSUE TITLE
Uploading a video file with a name shorten than 3 char failed at the end of the upload

### ISSUE THREAD

**Issue by DavidLibeau** [Chocobozzz/PeerTube#329]
* **PeerTube version or commit:** alpha.6
* **Browser name/version:** Firefox 58
* **NodeJS version:** 8.10.0
* **PostgreSQL version:** 9.6.7

* **What is the expected behaviour?** Upload the video or give the error at the start of the upload
* **What do you see instead?** Error "Should have a valid name", at the end of the upload

* **Browser console log :** Error "Backend returned code 400, body was: Should have a valid name"

Details : 

When you upload a file named "a.mp4", for example, it will upload it, but failed at the publish step, even if you called your video "abc", for example.

**Comment by Chocobozzz** [comment]
Fixed: https://github.com/Chocobozzz/PeerTube/commit/f2c3f7cd8a592ca1949e4f73717f17132a16c292

Nice catch @DavidLibeau thanks!
