### ISSUE TITLE
URL first access with anchors of /about/instance#my-anchor does not work.

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#3291]
Using anchors into the page /about/instance#my-anchor does not work for the first URL access : 

![Peek 11-11-2020 23-42](https://user-images.githubusercontent.com/1877318/98872883-a1408380-2477-11eb-8899-64559ec9e237.gif)

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/12c8a46362f1f92d1c1a34991a76c55f625a80c6
