### ISSUE TITLE
peertube2.cpy.re mobile video player has black bar

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3293]
**Describe the current behavior**
check the screenshot. the recently updated peertube2.cpy.re has a weird black bar below the video player. i checked the website through firefox responsive mode and the result was the same

![Screenshot_20201112-120650](https://user-images.githubusercontent.com/39449563/98905195-0086ae00-24e1-11eb-8cfc-34ae79592559.png)
and found the error 

![Screenshot_20201112_121508](https://user-images.githubusercontent.com/39449563/98905268-2449f400-24e1-11eb-876c-c53a0418462d.png)
![Screenshot_20201112_121517](https://user-images.githubusercontent.com/39449563/98905402-5f4c2780-24e1-11eb-9efe-4f684fccfdbd.png)
so somehow video-wrapper has a height of 66vh which makes it black. 

**Steps to reproduce:**

1.
2.
3.

**Describe the expected behavior**

**Additional information**

* PeerTube instance:
  * URL:https://peertube2.cpy.re/videos/watch/ec586719-a82e-4550-bb3d-cf1014986bbc
  * version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/dc13623baa244e13c33cc803de808818ef1e95a4 (peertube2 will be updated next week)
