### ISSUE TITLE
support `image/gif` for profile pictures

### ISSUE THREAD

**Issue by deffcolony** [Chocobozzz/PeerTube#3299]
**Describe the problem to be solved**

when viewing a user profile that it shows a profile banner instead of only showing a profile picture 
-->

**Describe the solution you would like:**

add a profile banner where users can import their own banner picture just like in youtube where users can customize their profile also same as on twitter and facebook just a simple profile banner. also make sure it supports .gif format so the image can be animated also please make gifs supported for the profile picture aswell

**Comment by rigelk** [comment]
hi @deffcolony,

You issue contains two feature requests in one:
- add support for `image/gif` as profile picture upload/display
- add support for banner images in profiles

The former is mostly backend work while the second requires extensive modification of the profile page layout, so please make two issues. It will help us identify and track their progress more easily.
