### ISSUE TITLE
【Updated】The whole commands to install Peertube for Production

### ISSUE THREAD

**Issue by imtube** [Chocobozzz/PeerTube#33]
I didn't know nodejs before, so I had to learn how to install it since I started to install PeerTube. Below are the all commands I had used to install PeerTube, just for some people like me.

This is my OS environment:

> Debian 8
> LNMP(You can just install nginx)
> root user

**First of all, you need a nginx**
If you don't know how to install it, you can use LNMP, it's a one key package to install nginx + mysql + php. you can install it with this command, it needs some time to complete:
`wget -c http://soft.vpser.net/lnmp/lnmp1.3-full.tar.gz && tar zxf lnmp1.3-full.tar.gz && cd lnmp1.3-full && ./install.sh lnmp`

When you need Non-Latin characters, you must set your local encoding first:
`dpkg-reconfigure locales`
Choose the option you use with suffix "UTF8", for example, en_US.UTF8, make sure that no Non-UTF8 option is chosen.

**Then you should install postgresql**
To do that, you should add a source list first:
`nano /etc/apt/sources.list`

Then you add this line into the sources.list file's end:
`deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main`

Then add key:
```
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | \
apt-key add -
```

Then install postgresql
```
apt-get update
aptitude install postgresql-9.4 postgresql-contrib-9.4 postgresql-doc-9.4
```

**Then you should install ffmpeg and openssl**
```
sh -c 'echo "deb http://www.deb-multimedia.org jessie main" >> /etc/apt/sources.list' && 
apt-get update && 
apt-get install deb-multimedia-keyring && 
apt-get install ffmpeg openssl sudo curl git build-essential
```

**Then you install nodejs 4.x and npm**
```
apt-get install python gcc make g++
curl -sL https://deb.nodesource.com/setup_4.x | bash - 
apt-get install nodejs -y
```

Then you install npm 3.x
`npm install -g npm@3`

You have to create a database, the database's name is peertube_prod or xxx_prod
```
su - postgres
psql postgres
```
Then you can input below commands:
```
CREATE USER peertube WITH PASSWORD 'peertube';
CREATE DATABASE peertube_prod OWNER peertube;
GRANT ALL PRIVILEGES ON DATABASE peertube to peertube;
\q
```

**Then create a new user for peertube:**
`useradd -m -d /home/peertube_user -s /bin/bash -p peertube_user peertube_user`

modify it's password:
`passwd peertube_user`

Then you can install PeerTube and build it
```
su - peertube_user
git clone -b master https://github.com/Chocobozzz/PeerTube
cd PeerTube
npm install
npm run build
```

Then you should setup the config file, first run below commands to generate the config file:
`cp config/production.yaml.example config/production.yaml`

Then you can modify the file production.yaml, it's location is PeerTube/config/production.yaml, you should modify the domain name and the database username and password.

Then you should add a virtual host with the domain name you want to use. If you are using LNMP, the command is:
`lnmp vhost add`

Then you should modify the virtual host conf file, insert the bellow content into the end of tag server{}.
the conf file's location is /usr/local/nginx/conf/vhost under LNMP, if you install nginx alone, it maybe is /etc/nginx/site-enabled/default.
```
  location / {
    proxy_pass http://localhost:9000;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # For the video upload
    client_max_body_size 100m;
  }

  # Bypass PeerTube webseed route for better performances
  location /static/webseed {
    if ($request_method = 'OPTIONS') {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
      add_header 'Access-Control-Max-Age' 1728000;
      add_header 'Content-Type' 'text/plain charset=UTF-8';
      add_header 'Content-Length' 0;
      return 204;
    }

    if ($request_method = 'GET') {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
    }

    alias /home/peertube_user/PeerTube/videos;
  }

  # Websocket tracker
  location /tracker/socket {
    # Peers send a message to the tracker every 15 minutes
    # Don't close the websocket before this time
    proxy_read_timeout 1200s;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_pass http://localhost:9000;
  }
```

If you want use https, you should have a look at this:
https://github.com/Chocobozzz/PeerTube/tree/master/support/nginx
(I met some error here, I can't watch video by https, somebody solved it please help me)

Then you should reload nginx:
`service nginx reload`

Then you can run PeerTube for production:
```
su - peertube_user
cd PeerTube
NODE_ENV=production npm start
```

The root user and password will be generated at first startup. You will see it in the PeerTube logs. you should remember it.

**Comment by Chocobozzz** [comment]
Thanks @myveb!

Just somes remarks:

 - PostgreSQL 9.4 is already in Debian Jessie (https://packages.debian.org/jessie/postgresql)
 - FFmpeg could be found in the official Jessie backports (https://packages.debian.org/jessie-backports/ffmpeg)
 - Do **not** run install and run PeerTube as root, please create a peertube user

We could put this guide in the wiki :)

**Comment by myveb** [comment]
@Chocobozzz 
Hello,
Thank you, I will try it on another server, it will be my pleasure to put this guide in the wiki.

**Comment by fredhampton** [comment]
Has the issue with https been solved ?

**Comment by Chocobozzz** [comment]
@fredhampton What issue? PeerTube runs well on HTTPS (and this is required to "make friends").

**Comment by fredhampton** [comment]
In the above install guide it says "I met some error here, I can't watch video by https, somebody solved it please help me"

**Comment by Chocobozzz** [comment]
I added the commands in the [wiki](https://github.com/Chocobozzz/PeerTube/wiki/Debian-Jessie-production-installation-guide). Thanks @imtube!

**Comment by ghedipunk** [comment]
Added install steps for Ubuntu 16 based on this discussion and the existing Wiki page for Debian.

https://github.com/Chocobozzz/PeerTube/wiki/Ubuntu-16-Production-Installation-Guide

Major changes are:

Uses Node 8 instead of 6:  The version of Yarn that I get from Ubuntu's repos has a minimum version requirement of 8.

Uses PostgreSQL 9.5 instead of 9.4, which is not available through Ubuntu's repos.

It also re-organizes a bit of the part where we set PeerTube's configuration, addressing an issue I'd ran into that had me blocked for a significant amount of time: When the environment variable NODE_ENV is not set, it loads the default.yaml configuration, instead of the production.yaml configuration that I expected... so when I was running `npm start` from the command line, it was loading a different config from what I expected.

At the end of the instructions, it also highlights the importance of finding the administrative credentials in the first run's output, and adds a line so that PeerTube will start up on server reboot.

**Comment by Chocobozzz** [comment]
Thanks @ghedipunk!

**Comment by borekon** [comment]
Awesome! Why it is not in the wiki section???

**Comment by Chocobozzz** [comment]
@borekon We moved the different guides in the git: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md. The idea is to have only one official tracked documentation to install PeerTube, so it can be easily maintained, reliable and up to date.

If you think it miss something in the official documentation, please open an issue :)

**Comment by wg1929** [comment]
你用中文打出来咋安装的呀，加个好友呗，英文都看不懂

**Comment by rigelk** [comment]
@wg1929 essential documentation can be translated already, but it's pointless if the interface cannot. Please see #148

**Comment by rigelk** [comment]
@xCumSlut just follow the README.
