### ISSUE TITLE
Add basic video player to <noscript> HTML

### ISSUE THREAD

**Issue by 3risian** [Chocobozzz/PeerTube#3301]
**Describe the problem to be solved**

A typical user who blocks JavaScript or runs a browser unable to properly use the current interface is unable to watch a linked PeerTube video without setting up a third-party application (which for desktop users currently requires the command line). This is an unnecessary hurdle for those who wish to watch a single video on a new instance.

**Describe the solution you would like:**

I have added a basic HTML video player to the video watch page. It shows the video title, description, thumbnail, available resolutions and a video player of the highest available resolution. https://github.com/3risian/PeerTube/

[Here is a video demonstration.](https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/JHBmEpXEtIwPrjvYSMpMySLW)

(This is a draft implementation only. If we do choose to add this feature, it shall be reviewed before merging.)

**Describe alternatives you have considered**

It had been said before that someone can develop their own client to avoid JavaScript use. However this doesn't address the common case of receiving a link to a video on a new instance and wanting to watch it in the same browser session without needing to download an app or use the command line and an external player.

**Comment by rigelk** [comment]
Please don't tag your issue title yourself.

**Comment by Chocobozzz** [comment]
Hello,

I know you won't like this answer but javascript in part of PeerTube. It's the thing that allows us to do P2P, use WebTorrent and/or HLS. We don't have time to maintain a non JS version of some pages for people that do not allow JS in their web browser. Maybe a plugin could be create to inject a player in the page, thought, but it's not something we want in core.
