### ISSUE TITLE
Admin contact form not working

### ISSUE THREAD

**Issue by tonyppe** [Chocobozzz/PeerTube#3302]
**Describe the current behavior**
Hi Guys, I raised 2 issues under here https://github.com/Chocobozzz/PeerTube/issues/3231 
but unfortunately the issue was closed and looks like the outstanding issue is not being realised :( 

When we try to contact the admin, no email is ever received. 

Someone suggested to update the ROOT user email address so that was done but unfortunately we dont receive any mail still. Actually I would like to delete the ROOT user at some point as a security step. 

There is another issue related to smtp that I raised in the link above but I was told to go away and raise it in some other place. Although I mention it here because I'm unsure if it it can be related to the contact form. 

**Steps to reproduce:**

1. try to send mail to administrator using the admin contact form
2. wait for mail

**Describe the expected behavior**

Mail should be received

**Additional information**
See: https://github.com/Chocobozzz/PeerTube/issues/3231 

Additional information

PeerTube version and URL: 2.4.0

Browser name and version: any

NodeJS version: v10.22.1

Link to browser console log if useful:

Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):

**Comment by Chocobozzz** [comment]
Please don't create duplicated issues.

**Comment by tonyppe** [comment]
Hi @Chocobozzz ! As far as I am aware, I didnt create a duplicate issue. My last issue was closed and marked as a question, so I raised a issue for the issue here. But the status on this one is now closed, too! 

Is there a better place to raise issues about peertube?
