### ISSUE TITLE
How to rename channels / users ? 

### ISSUE THREAD

**Issue by tonyppe** [Chocobozzz/PeerTube#3303]
I have installed a stand alone peertube instance. I do not wish to federate with anything. I mention this because any issues with federation from reaming channels or users is probably not a concern for me. I just want to host some videos. 

Are you able to provide me with steps to do this rename? Does this break functionality on a standalone instance? 

Thank you,

**Comment by rigelk** [comment]
hi @tonyppe,

This subject is already being discussed in #1603. Please subscribe to this issue for updates on when/if this gets implemented :slightly_smiling_face:

**Comment by tonyppe** [comment]
Thank you for the link. I did also find that link but there's not much information there to go on. So I guess that it's just not possible right now at all? Please could you confirm? 

I ask because I do not care if the federation aspect is destroyed by this operation. I never want to federate this instance. 

Thank you.

**Comment by Chocobozzz** [comment]
See https://github.com/Chocobozzz/PeerTube/issues/3269 to delete actors on your instance

**Comment by tonyppe** [comment]
Hi, 

Thank you for the link. I did go there but didnt find any content that explains how to rename a user. Did I miss something? Or maybe did you post the wrong link?

I'm somewhat confused - or are you trying to inform me that it's not possible to rename and the only option is to delete and create again? Please could you confirm?

**Comment by Chocobozzz** [comment]
> I'm somewhat confused - or are you trying to inform me that it's not possible to rename and the only option is to delete and create again?

Yes, it would be cleaner.

Go inside your database and delete the actor so you can re create an account or a channel with the same username:

```
sudo -u postgres psql
\c peertube_peertube;
DELETE FROM actor WHERE "preferredUsername"='testuser';
```

**Comment by tonyppe** [comment]
Hi @Chocobozzz - thank you for replying quickly and providing me the information there. I'm trying to avoid deleting a user because this "user" has added and shared videos. So deleting the user would invalidate the video urls and new video links would need to be shared again after re-uploading them to the new user account. So for this reason, I'm unable to delete the account.
