### ISSUE TITLE
peertube-import-videos: `youtube-dl -j` with a channel now dumps playlists and no videos anymore

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#3308]
**Describe the current behavior**

We cannot specify anymore a channel URL to peertube-import-videos to download videos. For example:
```bash
$ node dist/server/tools/peertube-import-videos.js -u https://some-peertube-instance.fr -U "some-user" --password "some-password" --target-url https://www.youtube.com/user/framasoft --last "1"
```

I investigated a bit. `peertube-import-videos` relies on youtube-dl with the following command:
```bash
$ youtube-dl -j --flat-playlist --playlist-reverse <url>
```

As far as I know, this command used to list videos. Now, when `<url>` refers to a youtube channel, it lists the playlists. Just try:

```bash
$ youtube-dl -j --flat-playlist --playlist-reverse https://www.youtube.com/user/framasoft
```

You would have this input:
```json
{"_type": "url", "url": "https://www.youtube.com/user/framasoft/videos?view=0&sort=dd&shelf_id=1", "ie_key": null, "title": "Uploads"}
```

This is due to the behavior change of youtube-dl. I don't know whether we should report the bug to the author (despite having no bug tracker anymore at this moment AFAIK), or adapt the script, or… do nothing (a simple workaround is describe below).

**Steps to reproduce:**

1. Run: `node dist/server/tools/peertube-import-videos.js -u https://some-peertube-instance.fr -U "some-user" --password "some-password" --target-url https://www.youtube.com/user/framasoft --last "1"`

**Describe the expected behavior**

It should download all the videos of the channel.

**Additional information**

**Workaround**: add `/videos` to the URL (`--target-url` option) so it can download the videos. Example: ` https://www.youtube.com/user/framasoft/videos` instead of `https://www.youtube.com/user/framasoft`

* PeerTube instance:
  * URL:
  * version: 2.4
  * NodeJS version: v12.19.0
  * Ffmpeg version: N/A

* Browser name, version and platforms on which you could reproduce the bug: N/A
* Link to browser console log if relevant: N/A
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
```
Cannot process video. {
  info: {
    url: 'https://www.youtube.com/c/<removed>/videos?view=0&sort=dd&shelf_id=4',
    _type: 'url',
    ie_key: null,
    title: 'Uploads',
    _duration_raw: undefined,
    _duration_hms: undefined,
    duration: undefined
  },
  url: 'https://<removed>'
}
```

**Comment by Chocobozzz** [comment]
Thanks for the issue. I added a workaround https://github.com/Chocobozzz/PeerTube/commit/de29e90c373c12a32bbce7b75d2017affc3ee16e
