### ISSUE TITLE
Account / Channel avatar in videos list

### ISSUE THREAD

**Issue by sschueller** [Chocobozzz/PeerTube#331]
I would like to show the Avatar of the account or channel next to the videos in the video list in the android app. To do this right now it looks like I would have to make an additional API call for each video to get this information.

Is there a way to get more data back when making an API call to the video list (`/api/v1/videos/search?start=0&count=12&sort=-createdAt`)?

**Comment by Chocobozzz** [comment]
No, but I think we'll update the Video object for lists to something like:

```
export interface Video {
  id: number
  uuid: string
  createdAt: Date | string
  updatedAt: Date | string
  categoryLabel: string
  category: number
  licenceLabel: string
  licence: number
  languageLabel: string
  language: number
  description: string
  duration: number
  isLocal: boolean
  name: string
  serverHost: string
  thumbnailPath: string
  previewPath: string
  embedPath: string
  views: number
  likes: number
  dislikes: number
  nsfw: boolean

  account: {
    name: string
    displayName: string
    url: string
    avatar: Avatar
}
```

**Comment by Chocobozzz** [comment]
Done: https://github.com/Chocobozzz/PeerTube/commit/b64c950a1cb37da880fc14e8535f438c78b5b7f7

Be careful , this is a breaking change! https://github.com/Chocobozzz/PeerTube/blob/develop/CHANGELOG.md#v100-alpha7
