### ISSUE TITLE
Clicking outside of the embedded player should close the context menu

### ISSUE THREAD

**Issue by techboyg5** [Chocobozzz/PeerTube#3312]
Inside the normal player, you can click anywhere to close the context menu (the one with four options when you right-click the video).

Inside the embedded player, you have to click inside the player area to close the context menu.

Clicking outside the player area should close the context menu on both players.

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/75d749596205511e012cecbdd39123277244f462
