### ISSUE TITLE
Allow any relative url in the landing page configuration option

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#3315]

**Comment by TROMsite** [comment]
Could this be done, for now, with nginx? 

```
Something like:
server {
# Temporary redirect to an individual page
rewrite ^/videos/local$ https://videos.trom.tf/video-channels/trom/videos redirect;
}
```
To redirect an url to another. I am desperate to fix this :D. We allow anyone to upload videos on our instance and of course that results in conspiracy videos and lots of other crap, so at least not give these people a front page would be nice. Peertube should define the "homepage" as About by default. Or let admins choose a particular channel or a page where they feature channels/videos. I feel this is such a must, else these instances will get corrupted by nonsense content that can never be properly moderated (it is too much for the admins to cope with the moderation).

**Comment by TROMsite** [comment]
A follow up. For those who want a custom landing page and are on Nginx. Go to Peertube's nginx config file. For me, using Yunohost, that's in `/etc/nginx/conf.d/videos.trom.tf/peertube.conf` and add the following line of code at the end of it all: `rewrite ^/$ /video-channels/trom redirect;` where "/video-channels/trom " can be an url or a page on your instance. For example we made the homepage our own main channel. You can make it a video if you want. Easy-peasy.

**Comment by TROMsite** [comment]
Unfortunately after users log in or log out, they can still see the whatever page is setup in admin to be the landing page, because of the way peertube loads pages. Not sure I can do anything about that...

**Comment by rigelk** [comment]
@TROMsite this is being tackled in https://github.com/Chocobozzz/PeerTube/issues/3582, not here.

**Comment by Nodja** [comment]
> For those who want to do it for their own peertube instances, it is easy. Go to your Nginx config file for Peertube. For me, using Yunohost, it is `/etc/nginx/conf.d/videos.trom.tf/peertube.conf` . On the very bottom add:
> 
> ```
> rewrite ^/$ /video-channels/trom redirect;
>   rewrite ^/videos/overview$ /video-channels/trom redirect;
> ```
> 
> And of course replace "/video-channels/trom" with a URL of your choice, and "overview" with whatever page is setup as the landing page in your admin settings.
> 
> Restart Nginx. Done.

An easier solution is to use inspect element on the configuration page.
 - Navigate to Administration -> Configure
 - Right click the dropdown below "Landing Page" and select Inspect Element
 - Change the value in one of the <option> tags, eg. I turned one of mine into`<option value="/video-channels/mychannel/videos">Discover videos</option>`, the discover videos portion doesn't matter, it's the value that actually gets saved.
 - Select Discover Videos on the dropdown.
 - Save configuration.

Now your landing page should be the channel you want, clicking on the channel leads you to the right place, etc.

**Comment by TROMsite** [comment]
I don't understand...you have to change that value in a html or php file inside the root folder or Peertube to work. Else it is not a permanent change for all users, of course...

**Comment by Nodja** [comment]
> I don't understand...you have to change that value in a html or php file inside the root folder or Peertube to work. Else it is not a permanent change for all users, of course...

The feature already exists in peertube. Changing the Landing Page on the administration configuration page will work as you want. No need to modify any files. You're just limited to a subset of urls.

The inspect element modification is just to manipulate the value sent by the POST request when you click "Update configuration" on the configuration page, thus overriding the value of the url that is saved on your peertube instance as the landing page. The change is global and affects all users.

I know this because I have a peertube instance that has only one channel (hosts twitch stream backups), and I set the landing page to be the playlist page that channel. So when people visit mypeertubinstance.com they see all existing playlists for the channel.

**Comment by TROMsite** [comment]
Oh wow it works...this is such a weird hack. haha. Thanks so much. Wow.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/4007
