### ISSUE TITLE
recently added: video from last week is shown in last month

### ISSUE THREAD

**Issue by gerhardbeck** [Chocobozzz/PeerTube#3317]
**Describe the current behavior**
Videos in "recently added videos" from last week are shown as "last month"

![Screenshot_2020-11-16_Recently_added_videos_-_PeerTube-Instanz_des_ev_-luth_Dekanat_Cham](https://user-images.githubusercontent.com/41069802/99280599-ce9f7f80-2831-11eb-81c4-354b5622c0f8.png)

**Steps to reproduce:**

1. Upload a video and select as publishing date a week ago (but not in the last month)

**Describe the expected behavior**
Showing last week instead of last month

**Additional information**

* PeerTube instance:
  * URL: https://kirche.peertube-host.de but also seen on other instances
like
![gfnjchchieaekjgl](https://user-images.githubusercontent.com/41069802/99280601-cf381600-2831-11eb-9533-a61a38759d33.png)

  * version: 2.4.0

**Comment by Chocobozzz** [comment]
Hello,

The entire sentence should be "More than 1 week ago" but to gain space, we just use *1 week ago*. Since it's between 1 and 2 weeks, it's in the *Last month* category.

**Comment by markusblogde** [comment]
Hi,

That is confusing. It should say "this month" and then "last month" when "this month" is over.

Markus

**Comment by gerhardbeck** [comment]
@Chocobozzz It is really confusing. Is it possible to change it to be more clear, e.g. as @markusblogde suggested?

**Comment by Chocobozzz** [comment]
Should be better with https://github.com/Chocobozzz/PeerTube/commit/7f88a58e3f8582431978ffff2e2beddadae6e358
