### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#3319]
**Describe the current behavior**
I had problems in the old system, I decided to install my server.
I saved the config, database and videos.
In other words, proceeding to the steps of the migration process

**Steps to reproduce:**
Backup DB 
Backup `config`
Backup `stream`

I Start the peertube installation process, import the previous database, and move the video to storage
`Nov 17 03:34:23 server multipathd[694]: sda: add missing path
Nov 17 03:34:23 server multipathd[694]: sda: failed to get udev uid: Invalid argument
Nov 17 03:34:23 server multipathd[694]: sda: failed to get sysfs uid: Invalid argument
Nov 17 03:34:23 server multipathd[694]: sda: failed to get sgio uid: No such file or directory`

**Describe the expected behavior**
The peertube today in the afternoon stopped, I had to restart the server, and I found this in the logs
**Additional information**

* PeerTube instance:
  * URL: SNET
  * version: 2.4.0
  * NodeJS version: 10.*
  * Ffmpeg version: 4.2

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
`d7e5-14bb-4d06-808c-778cd7ba785a%2Fae0ad7e5-14bb-4d06-808c-778cd7ba785a-240-fragmented.mp4",
Nov 17 03:34:14 server peertube[1519]:                 "height": 240
Nov 17 03:34:14 server peertube[1519]:               }
Nov 17 03:34:14 server peertube[1519]:             ]
Nov 17 03:34:14 server peertube[1519]:           }
Nov 17 03:34:14 server peertube[1519]:         ],
Nov 17 03:34:14 server peertube[1519]:         "likes": "https://peertube.azeroth.website/videos/watch/ae0ad7e5-14bb-4d06-808c-778cd7ba785a/likes",
Nov 17 03:34:14 server peertube[1519]:         "dislikes": "https://peertube.azeroth.website/videos/watch/ae0ad7e5-14bb-4d06-808c-778cd7ba785a/dislikes",
Nov 17 03:34:14 server peertube[1519]:         "shares": "https://peertube.azeroth.website/videos/watch/ae0ad7e5-14bb-4d06-808c-778cd7ba785a/announces",
Nov 17 03:34:14 server peertube[1519]:         "comments": "https://peertube.azeroth.website/videos/watch/ae0ad7e5-14bb-4d06-808c-778cd7ba785a/comments",
Nov 17 03:34:14 server peertube[1519]:         "attributedTo": [
Nov 17 03:34:14 server peertube[1519]:           {
Nov 17 03:34:14 server peertube[1519]:             "type": "Person",
Nov 17 03:34:14 server peertube[1519]:             "id": "https://peertube.azeroth.cu/accounts/joker"
Nov 17 03:34:14 server peertube[1519]:           },
Nov 17 03:34:14 server peertube[1519]:           {
Nov 17 03:34:14 server peertube[1519]:             "type": "Group",
Nov 17 03:34:14 server peertube[1519]:             "id": "https://peertube.azeroth.cu/video-channels/joker."
Nov 17 03:34:14 server peertube[1519]:           }
Nov 17 03:34:14 server peertube[1519]:         ],
Nov 17 03:34:14 server peertube[1519]:         "to": [
Nov 17 03:34:14 server peertube[1519]:           "https://www.w3.org/ns/activitystreams#Public"
Nov 17 03:34:14 server peertube[1519]:         ],
Nov 17 03:34:14 server peertube[1519]:         "cc": [
Nov 17 03:34:14 server peertube[1519]:           "https://peertube.azeroth.cu/accounts/joker/followers"
Nov 17 03:34:14 server peertube[1519]:         ]
Nov 17 03:34:14 server peertube[1519]:       },
Nov 17 03:34:14 server peertube[1519]:       "to": [
Nov 17 03:34:14 server peertube[1519]:         "https://www.w3.org/ns/activitystreams#Public"
Nov 17 03:34:14 server peertube[1519]:       ],
Nov 17 03:34:14 server peertube[1519]:       "cc": [
Nov 17 03:34:14 server peertube[1519]:         "https://peertube.azeroth.cu/accounts/joker/followers"
Nov 17 03:34:14 server peertube[1519]:       ]
Nov 17 03:34:14 server peertube[1519]:     }
Nov 17 03:34:14 server peertube[1519]:   },
Nov 17 03:34:14 server peertube[1519]:   "err": {
Nov 17 03:34:14 server peertube[1519]:     "stack": "jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.\n    at ContextResolver._fetchContext (/var/www/peertube/versions/peertube-v2.4.0/node_modules/jsonld/lib/ContextResolver.js:173:13)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
Nov 17 03:34:14 server peertube[1519]:     "message": "Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.",
Nov 17 03:34:14 server peertube[1519]:     "name": "jsonld.InvalidUrl",
Nov 17 03:34:14 server peertube[1519]:     "details": {
Nov 17 03:34:14 server peertube[1519]:       "code": "loading remote context failed",
Nov 17 03:34:14 server peertube[1519]:       "url": "https://www.w3.org/ns/activitystreams",
Nov 17 03:34:14 server peertube[1519]:       "cause": {
Nov 17 03:34:14 server peertube[1519]:         "stack": "jsonld.LoadDocumentError: URL could not be dereferenced, an error occurred.\n    at loadDocument (/var/www/peertube/versions/peertube-v2.4.0/node_modules/jsonld/lib/documentLoaders/node.js:74:13)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
Nov 17 03:34:14 server peertube[1519]:         "message": "URL could not be dereferenced, an error occurred.",
Nov 17 03:34:14 server peertube[1519]:         "name": "jsonld.LoadDocumentError",
Nov 17 03:34:14 server peertube[1519]:         "details": {
Nov 17 03:34:14 server peertube[1519]:           "code": "loading document failed",
Nov 17 03:34:14 server peertube[1519]:           "url": "https://www.w3.org/ns/activitystreams",
Nov 17 03:34:14 server peertube[1519]:           "cause": {
Nov 17 03:34:14 server peertube[1519]:             "stack": "Error: connect ETIMEDOUT 128.30.52.100:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)",
Nov 17 03:34:14 server peertube[1519]:             "message": "connect ETIMEDOUT 128.30.52.100:443",
Nov 17 03:34:14 server peertube[1519]:             "errno": "ETIMEDOUT",
Nov 17 03:34:14 server peertube[1519]:             "code": "ETIMEDOUT",
Nov 17 03:34:14 server peertube[1519]:             "syscall": "connect",
Nov 17 03:34:14 server peertube[1519]:             "address": "128.30.52.100",
Nov 17 03:34:14 server peertube[1519]:             "port": 443
Nov 17 03:34:14 server peertube[1519]:           }
Nov 17 03:34:14 server peertube[1519]:         }
Nov 17 03:34:14 server peertube[1519]:       }
Nov 17 03:34:14 server peertube[1519]:     }
Nov 17 03:34:14 server peertube[1519]:   }
Nov 17 03:34:14 server peertube[1519]: }
Nov 17 03:34:14 server peertube[1519]: [peertube.azeroth.website:443] 2020-11-17 03:34:13.969 #033[32minfo#033[39m: Processing ActivityPub broadcast in job 93267.
Nov 17 03:34:18 server multipathd[694]: sda: add missing path
Nov 17 03:34:18 server multipathd[694]: sda: failed to get udev uid: Invalid argument
Nov 17 03:34:18 server multipathd[694]: sda: failed to get sysfs uid: Invalid argument
Nov 17 03:34:18 server multipathd[694]: sda: failed to get sgio uid: No such file or directory
Nov 17 03:34:18 server peertube[1519]: [peertube.azeroth.website:443] 2020-11-17 03:34:18.867 #033[32minfo#033[39m: 144.100.1.198 - - [17/Nov/2020:03:34:18 +0000] "PUT /api/v1/videos/4f650573-0702-459f-aabc-3c1993dab28c/watching HTTP/1.0" 204 - "https://peertube.azeroth.website/videos/watch/4f650573-0702-459f-aabc-3c1993dab28c" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.112 Safari/537.36"
Nov 17 03:34:23 server multipathd[694]: sda: add missing path
Nov 17 03:34:23 server multipathd[694]: sda: failed to get udev uid: Invalid argument
Nov 17 03:34:23 server multipathd[694]: sda: failed to get sysfs uid: Invalid argument
Nov 17 03:34:23 server multipathd[694]: sda: failed to get sgio uid: No such file or directory
Nov 17 03:34:23 server peertube[1519]: [peertube.azeroth.website:443] 2020-11-17 03:34:23.857 #033[32minfo#033[39m: 144.100.1.198 - - [17/Nov/2020:03:34:23 +0000] "PUT /api/v1/videos/4f650573-0702-459f-aabc-3c1993dab28c/watching HTTP/1.0" 204 - "https://peertube.azeroth.website/videos/watch/4f650573-0702-459f-aabc-3c1993dab28c" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.112 Safari/537.36"
Nov 17 03:34:27 server peertube[1519]: [peertube.azeroth.website:443] 2020-11-17 03:34:27.451 #033[32minfo#033[39m: 144.100.1.198 - - [17/Nov/2020:03:34:27 +0000] "GET /api/v1/videos/?start=0&count=25&sort=-publishedAt&filter=local&skipCount=true&nsfw=both HTTP/1.0" 200 32894 "https://peertube.azeroth.website/videos/local" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.112 Safari/537.36"
Nov 17 03:34:28 server peertube[1519]: [peertube.azeroth.website:443] 2020-11-17 03:34:28.656 #033[32minfo#033[39m: 144.100.1.198 - - [17/Nov/2020:03:34:28 +0000] "GET /api/v1/users/me/video-playlists/videos-exist?videoIds=1101 HTTP/1.0" 304 - "https://peertube.azeroth.website/videos/local" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.112 Safari/537.36"
Nov 17 03:34:28 server multipathd[694]: sda: add missing path
Nov 17 03:34:28 server multipathd[694]: sda: failed to get udev uid: Invalid argument
Nov 17 03:34:28 server multipathd[694]: sda: failed to get sysfs uid: Invalid argument
Nov 17 03:34:28 server multipathd[694]: sda: failed to get sgio uid: No such file or directory
Nov 17 03:34:33 server multipathd[694]: sda: add missing path
Nov 17 03:34:33 server multipathd[694]: sda: failed to get udev uid: Invalid argument
Nov 17 03:34:33 server multipathd[694]: sda: failed to get sysfs uid: Invalid argument
Nov 17 03:34:33 server multipathd[694]: sda: failed to get sgio uid: No such file or director`

**Comment by Chocobozzz** [comment]
Hello,

Sorry but it seems to be a system bug, not a peertube bug. I can't help you.

**Comment by AnonymousWebHacker** [comment]
@Chocobozzz I already found out what the problem is.
It turns out that my peertube instance installs it with this domain peertube.azeroth.cu.

Then I made a domain change to peertube.azeroth.website.

I changed the domain in the / config / folder but it turns out that analyzing the logs, there are links that keep calling the domain peertube.azeroth.cu
Example, look at this activitypub-http-broadcast
```

Job: 1184839
Type: activitypub-http-broadcast
Processed on -
Finished on -

{
  "uris": [
    "https://peertube.azeroth.website/inbox"
  ],
  "signatureActorId": 1,
  "body": {
    "id": "https://peertube.azeroth.cu/accounts/peertube/likes/476",
    "type": "View",
    "actor": "https://peertube.azeroth.cu/accounts/peertube",
    "object": "https://peertube.azeroth.cu/videos/watch/cecc26c9-2d52-4513-9163-bac5c16d429d",
    "to": [
      "https://www.w3.org/ns/activitystreams#Public",
      "https://peertube.azeroth.cu/accounts/peertube/followers",
      "https://peertube.azeroth.website/video-channels/channelmusic/followers",
      "https://peertube.azeroth.website/accounts/music_channel/followers"
    ],
    "cc": []
  },
  "contextType": "View"
}
```
