### ISSUE TITLE
Different default avatar for channels

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#3324]
Currently, the default avatar is the same for the profile account and a channel.
It would be nice to have a different one for each other, it would be a first step to help to understand better the concept of a channel.

![image](https://user-images.githubusercontent.com/1877318/99527634-68377000-299d-11eb-8291-290229e88703.png)

**Comment by kimsible** [comment]
We could use something closer than the icons in the menu left for each default avatar : 

![image](https://user-images.githubusercontent.com/1877318/99528690-f52ef900-299e-11eb-8451-68b57b17c6dd.png)

**Comment by rigelk** [comment]
Please don't tag your issue title yourself.

**Comment by Chocobozzz** [comment]
This icon fits well for the account. Don't hesitate to make a PR with the channel icon (or another "channel" icon) in 192x192
