### ISSUE TITLE
Add speech to subtitles support

### ISSUE THREAD

**Issue by amreo** [Chocobozzz/PeerTube#3325]
**Describe the problem to be solved**
I am not good at listening spoken english but I am good at understanding written english.

**Describe the solution you would like:**
I want that peertube recognizes the speech and generate the relative subtitle.

**Comment by rigelk** [comment]
@amreo we have no good way to implement this in core PeerTube without making the installation of PeerTube much harder, for an uneven support of languages at best.

I feel like this falls more into the category of applications for which a plugin API could be developed instead, letting instance administrators free to subscribe to APIs of speech recognition providers for automatic translation upon video publishing.

**Comment by Booteille** [comment]
A mastodon user told me VOSK is having bluffing results.

Is it making PeerTube installation harder if we would add it to the peertube dependencies ?
https://alphacephei.com/vosk/

**Comment by rigelk** [comment]
> Is it making PeerTube installation harder if we would add it to the peertube dependencies ?

yes, definitely…

**Comment by Booteille** [comment]
Because of Python dependency?

I guess this feature should be considered as a good candidate for a useful plugin...

**Comment by rigelk** [comment]
Which is why it is labeled as such :wink:

**Comment by tykayn** [comment]
if anyone wants some stuff to implement a vosk transcription i made a repo with a doc to do so, but outside peertube:
https://forge.chapril.org/tykayn/transcription

i succefully extracted audio from a peertube video with ffmpeg and generated a subtitle file with a french model with the transcript from vosk and added it to a video, and it works fine.

could be used on any audio or video file.
other models of lang are also available.

**Comment by Mastercuber** [comment]
I didn't gave it a try.. But I saw a plugin named `transcription` which is generating Subtitles for videos. This plugin also uses `vosk`.
