### ISSUE TITLE
Comment Options overlapped by the lateral menu

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#3328]
**Describe the current behavior**

When viewing options on comment, the dropdown menu is overlapped by the lateral menu.

![image](https://user-images.githubusercontent.com/371705/99587595-9642a180-29e9-11eb-8469-a304bfd03775.png)

**Steps to reproduce:**

1. Connect to some PeerTube instance with a moderation account
2. View some video comments
3. Open the comment options like above
4. resize the window so the dropdown menu goes below the menu bar

**Describe the expected behavior**

The dropdown menu should be placed above the menu bar

**Ideas on the issue**

You would probably change the values here:
https://github.com/Chocobozzz/PeerTube/blob/0aa52e170727ac6bdf441bcaa2353ae0b8a354ed/client/src/sass/include/_variables.scss#L127-L142

But I wonder if there have been rationales for setting `dropdown` to a lower value than `menu` and even others.

**Additional information**

* PeerTube instance:
  * URL: https://skeptikon.fr
  * version: 2.4
  * NodeJS version: N/A
  * Ffmpeg version: N/A

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/8b57efbf1ba121cfd2e4ce326bf87ef887b2e80d

**Comment by fflorent** [comment]
Thank to **you** @Chocobozzz :)
