### ISSUE TITLE
peertube.service: Failed to determine user credentials: No such process

### ISSUE THREAD

**Issue by kayasaya** [Chocobozzz/PeerTube#3330]
Im trying to install peertube on my server and this is what i get when i come to the point of the

`$ sudo journalctl -feu peertube
`

this is my production.yaml

https://pastebin.com/M3aAuMwH

this is the error i get

https://pastebin.com/YKKqq5WZ

Any clue guys?

**Comment by rigelk** [comment]
What guide did you follow for the installation and what are your PeerTube runtime logs?

**Comment by kayasaya** [comment]
> What guide did you follow for the installation and what are your PeerTube runtime logs?

https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md

would you please instruct me how to get the peertube runtime logs?

**Comment by rigelk** [comment]
They are defined in your config storage key: '/var/www/xxxxxxx/storage/logs/'

**Comment by kayasaya** [comment]
It is not created, since its crashing in the very first sudo journalctl -feu peertube, therefor, the folder is empty

**Comment by kayasaya** [comment]
Ok, so it was a problem with Nginx, fixed it, but now, the issue i have is the Failed at step CHDIR spawning, i changed the path from /var/www/peertube/ to /var/www/xxxxxx/ ¿Any idea on which files should i touch to avoid problems here?
,

**Comment by rigelk** [comment]
> i changed the path from /var/www/peertube/ to /var/www/xxxxxx/

please note that you might need to change a few things in your configuration and in your nginx config.

> CHDIR spawning

still the same issue with "Failed at step CHDIR spawning /usr/bin/npm"? I suggest you check you npm install, and that the peertube user has access to this executable.

**Comment by kayasaya** [comment]
Yeah, the problem is i was using apache2 and nginx because im hosting 2 sites under the same ip, this generated a lot of conflict with ports, today imma try to finish the process and i post you with a workflow to fix this issues if someone else makes the same stuff

**Comment by rigelk** [comment]
@kayasaya closing since this is an unsupported scenario, but please do complete the issue with your feedback, that could certainly help others!
