### ISSUE TITLE
VideoCaptionsAPI requires OAuth but documentation omits this, so auto-generated API wrappers don't pass authorization headers 

### ISSUE THREAD

**Issue by bclarke98** [Chocobozzz/PeerTube#3332]
**Parts of the documentation concerned:**
https://docs.joinpeertube.org/api-rest-reference.html#tag/Video-Captions/paths/~1videos~1{id}~1captions~1{captionLanguage}/put

**Describe the desired information/correction**
Specify authorization is required so that the openapi-generator will actually pass auth headers with this request.

**Comment by rigelk** [comment]
fixed in 64b5c2476
