### ISSUE TITLE
Failed at step CHDIR spawning /usr/bin/npm: No such file or directory

### ISSUE THREAD

**Issue by kayasaya** [Chocobozzz/PeerTube#3333]
So before I had a problem with apache2 + nginx but that issue is solved already, this is not related at all to that problem.

Now, i changed the route for my files from var/www/peertube to var/www/xxxxxxx

I already did congfigure my production.yaml file and the /etc/nginx/sites-available/peertube & /etc/nginx/sites-enabled/peertube

Here are my files:

The error when I sudo journalctl -feu peertube
https://pastebin.com/JBBaKMum

My production.yaml
https://pastebin.com/3cK0SQji

The  /etc/nginx/sites-available/peertube & /etc/nginx/sites-enabled/peertube I don't feel are necessary for this process since it just setting the folder from var/www/peertube to the new one, which i already did.

**Comment by kayasaya** [comment]
That happened because i did use root user for all the process, instead of peertube user. Now, i get this error when i try to make the journalctl -feu peertube

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle peertube@2.4.0~prestart: peertube@2.4.0
6 info lifecycle peertube@2.4.0~start: peertube@2.4.0
7 verbose lifecycle peertube@2.4.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle peertube@2.4.0~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/peertube/versions/peertube-v2.4.0/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle peertube@2.4.0~start: CWD: /var/www/peertube/versions/peertube-v2.4.0
10 silly lifecycle peertube@2.4.0~start: Args: [ '-c', 'node dist/server' ]
11 silly lifecycle peertube@2.4.0~start: Returned: code: 1  signal: null
12 info lifecycle peertube@2.4.0~start: Failed to exec start script
13 verbose stack Error: peertube@2.4.0 start: `node dist/server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid peertube@2.4.0
15 verbose cwd /var/www/peertube/versions/peertube-v2.4.0
16 verbose Linux 5.4.0-53-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error peertube@2.4.0 start: `node dist/server`
22 error Exit status 1
23 error Failed at the peertube@2.4.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Chocobozzz** [comment]
Hello,

Please try using the `peertube` user: `cd /var/ww/peertube/peertube-latest && NODE_ENV=production NODE_CONFIG_DIR=/var/www/peertube/config node dist/server`
