### ISSUE TITLE
Video channel ownership transfer

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#3336]
Linked to this requested feature about co-authors video channels : https://github.com/Chocobozzz/PeerTube/issues/3335

Transfer the ownership of a video channel like a single video would be a great feature for collaboration.

Do you have any idea how it could be implement technically ?

**Comment by test2a** [comment]
We now edit comments by deleting them and posting afresh so that activitypub doesn't get same data twice. Can that logic be used ? I think video transfers are done the same way or are they done differently ?

**Comment by kontrollanten** [comment]
It looks like a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1417

**Comment by Chocobozzz** [comment]
Thanks @kontrollanten
