### ISSUE TITLE
accepted abuse report shows "deleted comment" 

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3338]
**Describe the current behavior**
i made a few spam reports which the instance promptly removed. the problem is now that i check the abuse report, it just says "deleted comment". it should keep the reportee comment in the abuse history for recordkeeping.

just like the first abuse report in the screenshot contains the comment in the right box, below there is a deleted comment which was accepted but no idea now what it was. the comment should be static for reporting purpose even if deleted from the instance.

![Screenshot_20201120_213129](https://user-images.githubusercontent.com/39449563/99821544-33334500-2b78-11eb-813a-a9a3bfa4f8f5.png)

**Steps to reproduce:**

1. send a abuse report on a comment
2. have the administrator accept the abuse report and delete the problem comment 
3. abuse report shows deleted comment. 

**Describe the expected behavior**
the actual abuse comment should remain in your history regardless of the action taken by administrators, local or remote
**Additional information**

* PeerTube instance: 
  * URL:
  * version: 2.4.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by test2a** [comment]
there is also redundant "message with moderators" button in overflow menu because that button is present inline

also, the *"delete report"* button does not work for me. it might be a bug but i am just writing it here.

**Comment by Chocobozzz** [comment]
Hello,

You should use the abuse note to keep a record of comments, because the software must remove user's content from the database when it's deleted (it means we can't keep data forever in the DB when it seems to be deleted on the web interface).
