### ISSUE TITLE
Uploaded video have no more sound.

### ISSUE THREAD

**Issue by GammaNu** [Chocobozzz/PeerTube#334]
* **PeerTube version or commit:** peertube-v1.0.0-alpha.6
* **Browser name/version:** Firefox/58.0
* **NodeJS version:** v8.9.4
* **PostgreSQL version:** 9.5+173ubuntu0.1

* **What is the expected behaviour?**
keep sound of the original video

* **What do you see instead?**
Silence...
and ffmpeg errors in administration jobs
```
| video-file | failed | Mar 11, 2018, 7:43:20 PM | Mar 11, 2018, 7:43:21 PM |

{   "videoUUID": "b1a38637-7623-4fc5-b5b5-6af4ca1e5e57" }
Error: ffmpeg exited with code 1:      at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v1.0.0-alpha.6/node_modules/fluent-ffmpeg/lib/processor.js:182:22)     at emitTwo (events.js:126:13)     at ChildProcess.emit (events.js:214:7)     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

I've played the video from storage/video and it still have sound.

https://video.1000i100.fr/videos/watch/7633b3fd-08eb-4fa0-a62e-9ddb4a90bf7f

**Comment by GammaNu** [comment]
Testé avec un autre navigateur (Iridium, basé sur chrome/chromium) et le son est là.
Je pense donc qu'il y a 2 problèmes : 
- firefox 58 ne gère pas le format son de cette vidéo
- ffmpeg plante au transcoding et ne permet donc pas d'avoir une version optimisé compatibilité pour le son et l'image dans PeerTube

**Comment by PhieF** [comment]
I'm also having transcoding issue, of the same kind
'''
Error: ffmpeg exited with code 1: 
    at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v1.0.0-alpha.6/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
'''

details about ffmpeg

'''
ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
libavutil      54. 31.100 / 54. 31.100
libavcodec     56. 60.100 / 56. 60.100
libavformat    56. 40.101 / 56. 40.101
libavdevice    56.  4.100 / 56.  4.100
libavfilter     5. 40.101 /  5. 40.101
libavresample   2.  1.  0 /  2.  1.  0
libswscale      3.  1.101 /  3.  1.101
libswresample   1.  2.101 /  1.  2.101
libpostproc    53.  3.100 / 53.  3.100
'''


would you need a sample file ?


thank you



would you need a sample file ?

**Comment by Chocobozzz** [comment]
@PhieF Hi, you need ffmpeg >= 3.0.

**Comment by PhieF** [comment]
Indeed, it worked, sorry for that and thank you :D
