### ISSUE TITLE
LiveStreaming doesnt work - OBS

### ISSUE THREAD

**Issue by kgnfth** [Chocobozzz/PeerTube#3341]
i run peertube-develop in docker

i select custom service and put
Server: rtmp://peertube.example.com:1935/live
Stream Key: f9fa-bc22-4f1c-a836-example

![image](https://user-images.githubusercontent.com/73314940/99878204-07f63780-2c04-11eb-92d6-2f1c787ae924.png)

pls HALP

**Comment by rigelk** [comment]
Are you exposing the port 1935 in your docker image ?

**Comment by kgnfth** [comment]
> Are you exposing port 1935 in your docker container?

That's right, its fixed now
