### ISSUE TITLE
Improved support cycle documentation

### ISSUE THREAD

**Issue by markvdb** [Chocobozzz/PeerTube#3343]
**Describe the problem to be solved**
The PeerTube support cycle is not very clear yet. What I've seen has mostly been limited to:
-  https://github.com/Chocobozzz/PeerTube/blob/develop/FAQ.md#does-peertube-ensure-federation-compatibility-with-previous-version
-  https://joinpeertube.org/roadmap .

**Describe the solution you would like:**

Sysadmins might benefit from clear answers to questions like:
- For how long will I be able to run my current version of PeerTube without having to fear unpatched security issues?
- Are specific versions of PeerTube long term supported?
- When approximately can I expect the next version of PeerTube to arrive?
- Are there any crucial dependencies with short support cycles?
- ...

The most probable and useful answer might very well be:
"We've been building on the solution. We haven't looked into this very much yet and lack the manpower to do so. We most probably won't be able to improve on that until <insert_trigger_here>."

**Comment by test2a** [comment]
I am no expert but its on a best case scenario and only most recent updates are supported because the development team is not big. They'd rather all people be on the latest release.

I could be wrong and in that case someone here would correct both of us.

**Comment by rigelk** [comment]
> For how long will I be able to run my current version of PeerTube without having to fear unpatched security issues?

We support the latest release minus 2 minor releases (ex: latest is 2.4, so 2.3 and 2.2 are supported). I am not sure we support as many versions accross major releases, though.

> Are specific versions of PeerTube long term supported?

There is no LTS release.

> When approximately can I expect the next version of PeerTube to arrive?

Anything from 2 to 6 months, with no promises. Subscribe to the sysadmin mailing list to never miss one, or subscribe to the release page RSS feed.

> Are there any crucial dependencies with short support cycles?

No. Not that sysadmins have to deal with anyway. But having recent versions of Nginx and PostgreSQL is never a bad idea :wink:

**Comment by markvdb** [comment]
Thank you!

This also seems to be relevant:
- https://nodejs.org/en/about/releases/ . The end-of-life for the version of this essential building block is 2022-04-30. That means an upgrade will be needed a year and five months from now at the very latest.

And less crucial, for those that allow imports:
- youtube-dl . This auto-upgrades as part of the PeerTube installation.

**Comment by kontrollanten** [comment]
@markvdb Thanks for raising those questions. Do you think that you can make a PR to improve the documentation where you think it's needed?

**Comment by Chocobozzz** [comment]
I added @rigelk anwsers in https://github.com/Chocobozzz/PeerTube/commit/d44cdcd766fbccbe4b96f34c11a64f0e2168c3b9
