### ISSUE TITLE
Using a zero-timestamp in description or comment does not jump to the start of the video

### ISSUE THREAD

**Issue by Roemer** [Chocobozzz/PeerTube#3354]
**Describe the current behavior**
When using `00:00:00` in the video description or comment, the generated url just omits any `start` parameter and reloads the page and continues playing where it was before and not from the beginning.

**Steps to reproduce:**

1. Upload a video
2. Create a video description or comment containing `00:00:00` and one inside the video (eg. `00:00:50`)
3. Click the timestamp in the video -> The video jumps to that location
4. Click the 0-timestamp -> The page reloads and the video keeps playing where it left before

**Describe the expected behavior**
The page should not reload (as with the other timestamps) but it should jump to the start.

* PeerTube instance:
  * URL: Private instance
  * version: 2.4.0 (official Docker Image)
  * NodeJS version: As in the Docker Image
  * Ffmpeg version: As in the Docker Image

* Browser name, version and platforms on which you could reproduce the bug: Chrome, latest, Windows 10
* Link to browser console log if relevant: -
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): -

**Comment by Chocobozzz** [comment]
Thanks for the issue, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/fc4188746340b65b7615ca0dd07f81ed7a5e53cd

**Comment by Roemer** [comment]
Awesome, thanks 👍
