### ISSUE TITLE
Cleaning up unused data

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#3356]
There is a lot of data on my copy, which is updated daily. I want to check all the data to make sure that I do not have any extra or damaged directories with files. Is there a tool for such verification? Thanks.

Peertube 2.4.0
https://peervideo.ru

**Comment by Chocobozzz** [comment]
Hello,

You can try https://docs.joinpeertube.org/#/maintain-tools?id=prune-storagejs to remove extra data. But use this carefully and make backups first.

**Comment by Alterak** [comment]
> Hello,
> 
> You can try https://docs.joinpeertube.org/#/maintain-tools?id=prune-storagejs to remove extra data. But use this carefully and make backups first.

Thanks, I will definitely try.
