### ISSUE TITLE
More detailed units of sizes and space

### ISSUE THREAD

**Issue by narcisgarcia** [Chocobozzz/PeerTube#3358]
With Peertube 2.4.0 administrators see files and/or space accounting rounded to "GB"
My feature requests about this:

- Use binary prefixes to have precise idea of space and make easier to do personal calculations (MiB, GiB, TiB)
- Scale unit as needed (few MiB, more GiB, many TiB) and use 1 decimal digit when number is below 10 (9,5 GiB 11GiB 56GiB 900GiB 1,1TiB) to fine grain.

Split from: #3294

**Comment by Chocobozzz** [comment]
Closing as I think we display detailed units in users list admin table
