### ISSUE TITLE
More sizes and space information

### ISSUE THREAD

**Issue by narcisgarcia** [Chocobozzz/PeerTube#3359]
With Peertube 2.4.0 administrators see only account used space.
My feature requests about this:

- Report total Peertube instance space (used/available) at administrator's dashboard or system information. Also total number of videos (local/cache), minutes length, stored/encoded files.
- Administrators should be able to see used space for each single video, and each one's encoded format (webm-vp9-ogg / MP4-mpeg4-aac / aac). Video owner too.
- Same summary as whole instance should be shown at user accounts list.
- A channels list should be manageable with their owner and space summary. Users should have their own channels list with same features.

Split from: #3294

**Comment by Chocobozzz** [comment]
See https://github.com/Chocobozzz/PeerTube/issues/3361#issuecomment-1143332413
