### ISSUE TITLE
Multiple concepts on videos/files information

### ISSUE THREAD

**Issue by narcisgarcia** [Chocobozzz/PeerTube#3360]
With Peertube 2.4.0 administrators see only size/space information simplified to "GB"
My feature requests about this:

- Any report or information about used space, videos or files should not only be in bytes/kib/mib/gib/tib but also in number of videos, number of files (on multiple encodings), minutes length.
- Administrators should be able to see spaces used by a single video: Whole video and per each video recodification/resolution. Calculate and show kbps of each file/recodification. Video owner to see this too.
- Administrators should be able to see what files/resolutions are stored for each single video, and each one's format (webm-vp9-ogg / MP4-mpeg4-aac / aac). Video owner too.

Split from: #3294

**Comment by Chocobozzz** [comment]
In v4 we now display these information
