### ISSUE TITLE
Plugins installed from CLI do not have settings registered

### ISSUE THREAD

**Issue by madmath03** [Chocobozzz/PeerTube#3366]
**Describe the current behavior**

When installing a plugin using the CLI, no settings are available through the admin interface.

**Steps to reproduce:**

1. Install Peertube using official docker image
```bash
$ docker images
REPOSITORY                              TAG                         IMAGE ID                 CREATED                SIZE
chocobozzz/peertube               production-buster   b5d8a8194d87        2 months ago        1.01GB
```

2. Install any plugin that have settings using the CLI
```bash
$ docker-compose exec -T --user peertube peertube npm run plugin:install -- --npm-name peertube-plugin-auth-ldap

> peertube@2.4.0 plugin:install /app
> node ./dist/scripts/plugin/install.js "--npm-name" "peertube-plugin-auth-ldap"

[peertube.example.com:443] 2020-11-26 17:42:05.209 info: Installing plugin peertube-plugin-auth-ldap.
[peertube.example.com:443] 2020-11-26 17:42:08.665 info: Successful installation of plugin peertube-plugin-auth-ldap.
[peertube.example.com:443] 2020-11-26 17:42:08.667 info: Registering plugin or theme peertube-plugin-auth-ldap.
[peertube.example.com:443] 2020-11-26 17:42:08.787 info: Add plugin peertube-plugin-auth-ldap CSS to global file.
[peertube.example.com:443] 2020-11-26 17:42:08.788 info: Cleaning HTML cache.
```

3. Login as admin and go to plugins administration then settings
![image](https://user-images.githubusercontent.com/6967675/100381604-9e1dc980-3019-11eb-8974-9273d5f4d953.png)

![image](https://user-images.githubusercontent.com/6967675/100381639-aece3f80-3019-11eb-8ade-e7be0c185296.png)

**Describe the expected behavior**

Installing a plugin from the CLI should have the same behavior as installing it from GUI.

**Additional information**

Following #3349 discussion.

This behavior happens on any plugin, not just LDAP Auth.

Also quite weird that PeerTube offers to install the plugin even though it's already installed:
![image](https://user-images.githubusercontent.com/6967675/100381732-e76e1900-3019-11eb-9beb-0f54984fc9bb.png)

Installing again from GUI displays the settings:
![image](https://user-images.githubusercontent.com/6967675/100381868-459afc00-301a-11eb-9f7f-b51cdb62d8ac.png)

* PeerTube instance: Docker image chocobozzz/peertube production-buster (b5d8a8194d87)

* Browser name, version and platforms on which you could reproduce the bug: NA

* Link to browser console log if relevant: NA

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Did you restart peertube after the install? As stated [in the doc](https://docs.joinpeertube.org/#/maintain-tools?id=plugin-installuninstall), if you want to install plugins when peertube is running without restarting it, your should use [peertube-plugins.js](https://docs.joinpeertube.org/#/maintain-tools?id=peertube-pluginsjs) script

**Comment by madmath03** [comment]
Hi @Chocobozzz 

I did restart the peertube server several times but I would still not see the settings... I'm going to try it again but just after installing the plugin.

I'm also going to try `peertube-plugins.js`, this might better suit my needs.

**Comment by madmath03** [comment]
ok, my mistake. If restart is done just after installing the plugin, the settings are available.
I will close this issue.

Thanks @Chocobozzz 

By the way, `peertube-plugins.js` is not available in the Docker container (I guess we need to build it manually using `npm run setup:cli`).
