### ISSUE TITLE
Link with invitation to register in instance

### ISSUE THREAD

**Issue by rennerocha** [Chocobozzz/PeerTube#3367]
When we open registration in an instance, we have little control over who is allowed to create a new account.

To avoid receiving spam videos from these accounts, we can set the "Video quota" to None by default, so we can manually verify who the user is before allowing them to really starts using the instance to upload videos.

However, we have other problems accepting accounts from unknown people:
- New users can comment on videos;
- It adds some burden over the instance administrator that have an extra moderation task to do;
- New users may "steal" an username for that instance, as when we delete an account, that username can not be reused. For smaller instances this may be a problem (a bit annoying), as we may want that "our" John, from our community, to be able to use @john@myinstance , but if a spammer use that name, we can't allow our community member to use that username.

One possible solution that I thought would be to allow an admin to create invite links for new users, even if public registration on the instance is closed. With that link, the person will be able to create a new account. This link may expire after some time and be used only once.

**Comment by rigelk** [comment]
Hi @rennerocha! Please look out for related issues before creating one, as #2242 already covers this. You can then detail further your use case there, and upvote the issue to help us triage it.

**Comment by rennerocha** [comment]
Hello @rigelk, don't consider that I didn't read other issues before opening it. ;-)

I read the issue you mentioned before opening this one. The problem to be solved is the same (prevent invalid registrations), but the solution proposed is not exactly equal. In that issue they are asking for a way to accept/deny subscriptions **after** the registration is done and add an extra step for instance administrators to check if the new user is really someone they want in the instance. 

The solution I proposed is a bit different (but solves the same problem anyway). It is applied **before** the registration is done, as the admin doesn't need to keep registration open for everyone and an invite link is generated and used only once. With this possibility, people will only be able to register if the admin provide a link. After that, instance administrators will not need to worry about accepting/denying the user.

Anyway, if the solution of #2242 is implemented, I will be very happy and it will make my life a bit easier. But it would be good if you could also consider other ways to solve that problem.

**Comment by Chocobozzz** [comment]
What about https://github.com/Chocobozzz/PeerTube/issues/1212?

**Comment by rennerocha** [comment]
@Chocobozzz I digged into the issues and didn't find that one. You are right, they may be considered duplicated at all!
