### ISSUE TITLE
Allow Markdown formatting in more instance information sections

### ISSUE THREAD

**Issue by rennerocha** [Chocobozzz/PeerTube#3368]
Improve how some instance information can be provided.

The following sections accept Markdown, so we add create lists and links that will make them appear nice in "About" of your instance:

- Description
- Terms
- Code of conduct
- Moderation information
- Who is behind the instance?

However, the following sections accepts only plain text:
- Why did you create this instance?
- How long do you plan to maintain this instance?
- How will you finance the PeerTube server?
- What server/hardware does the instance run on?

Specially for "How will you finance the PeerTube server?" it would be interesting to be able to add some Markdown formatting, so for example, we can create a list of links where the user can know how to donate money to the instance.

It will look much better to show this:

> Donate using:
> - [Paypal](http://example.com)
> - [Liberapay](http://example.com)

Than this:
> Donate using:
> Paypal - http://example.com?accoutn=AJHKKJFDLKJFGD
> Liberapay - http://example.com?someweirdinfo=ABCHGFDJKHLKFDSA

**Comment by Poslovitch** [comment]
Working on it.
