### ISSUE TITLE
Rebuild packege.json

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#3369]
I made a change of Host and Domain, and I lost the package.json file that is necessary to do the process of change of host

`sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run update-host`

It makes use of  `~/config /package.json`
I made a Host change and now checking, that file I lost, because does not exist.

Is there any way to rebuild it?

**Comment by Chocobozzz** [comment]
Hello,

Reinstalling peertube build should work. Or you can extract the package.json from the zip release and copy it in your `peertube-latest` directory
