### ISSUE TITLE
CLI installation issue - npm

### ISSUE THREAD

**Issue by maxabernathy** [Chocobozzz/PeerTube#3370]
Hey,
we're having issues installing the CLI scripts after a successful installation of the production environment (not via docker). Our environment is on a Ubuntu 20.04 behind a corporate proxy. We checked several possibilities with variables inside the .npmrc, global npm config as well as unsetting strict-ssl, the registry-url is accessible. The same errors persists during wrtc installation. Are the docs still up to date on this? The peertube.js wrapper seems to have evolved to typescript?

Many thanks for your help, we'd love to use peertube!

```
error /home/-----/clicli/PeerTube/server/tools/node_modules/wrtc: Command failed.
Exit code: 1
Command: node scripts/download-prebuilt.js
Arguments:
Directory: /home/-----/clicli/PeerTube/server/tools/node_modules/wrtc
Output:
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: self signed certificate in certificate chain
node-pre-gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:198:13)
node-pre-gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:636:8)
node-pre-gyp ERR! System Linux 5.4.0-53-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/-----/clicli/PeerTube/server/too                                   ls/node_modules/wrtc/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /home/-----/clicli/PeerTube/server/tools/node_modules/wrtc
node-pre-gyp ERR! node -v v10.19.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peertube@2.4.0 setup:cli: `scripty`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@2.4.0 setup:cli script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by Chocobozzz** [comment]
Hello,

I think the issue is your corporate proxy that injects its self signed cert. You should install your proxy cert on your system,
or [disable TLS check for node gyp](https://github.com/nodejs/node-gyp/issues/448), which I don't recommend.

**Comment by maxabernathy** [comment]
Dear @Chocobozzz,
thanks! Indeed it was an issue with npm, specifically with the node-webrtc package which accesses another url not yet unlocked in our proxy.
