### ISSUE TITLE
multi server support

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3372]
**Describe the problem to be solved**
#56 was closed in 2017 and i would like to request this once again
today we expect the single server to do all the jobs. be it transcoding, serving files, management and others. there is a limit, both cost wise and physically a single VM or a physical desktop/server machine can serve. What i am proposing is allowing multiple servers in the backend structure with a load balancer so that we can build better more resilient instances.
that said, i do want to request allowing GPU transcoding because apparently that is not allowed yet.
let this be a 2021 roadmap goal, but this is something peertube would need to grow horizontally instead of going vertically up with a single server.

We would want storage on multiple servers but because s3 is already available, this is solved already.

**Describe the solution you would like:**
* allow load balancing and multiple servers doing separate jobs of serving users, transcoding, storage management, users management
* GPU transcoding

**Describe alternatives you have considered**

**Comment by test2a** [comment]
now with LIVE streaming a reality, how many live streams can a single CPU handle before collapsing? if we have GPU transcoding, we could theoretically have any number of live streams because increasing live would just mean adding more GPUs

**Comment by test2a** [comment]
plex remote transcoder does this job pretty nicely. 
would it be possible to integrate this software into peertube because doing that would solve this issue almost in entirety

https://github.com/UnicornTranscoder/UnicornTranscoder
https://github.com/wnielson/Plex-Remote-Transcoder

**Comment by rigelk** [comment]
@test2a we cannot integrate it, but it's architecture is interesting.

**Comment by test2a** [comment]
@rigelk yes. if this is actively being developed and is working as expected for them, this is a feature that is essential for a project like peertube. my concern is if some instance wants to host say 50-100 live streams, would they be able to do that on a single instance setup aka single cpu?

**Comment by rigelk** [comment]
> my concern is if some instance wants to host say 50-100 live streams, would they be able to do that on a single instance setup aka single cpu?

no, most probably not at the moment.

**Comment by rigelk** [comment]
@test2a the issue you mention has been closed because supporting multiple backends is a very difficult task. Hardware transcoding is a much more reasonable goal, but don't misunderstand: GPU encoding is not easy to configure at all, as you need to choose which device will transcode, which specific codec and driver applies to this device, and which specific options apply.

Anyway, thanks for the links, they are very inspiring!
