### ISSUE TITLE
error: Your configuration files miss keys: database.suffix

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3373]
**Describe the current behavior**
When `database.suffix` isn't represented in the configuration the following error occurs:

    error: Your configuration files miss keys: database.suffix

Based on this check: https://github.com/Chocobozzz/PeerTube/blob/992f498e312efcde46f818ba719b50f1f958272f/server/initializers/checker-before-init.ts#L12

**Steps to reproduce:**

1. Remove `database.suffix` som PeerTube yaml config.
2. Restart PeerTube

**Describe the expected behavior**
[According to the example config](https://github.com/Chocobozzz/PeerTube/blob/992f498e312efcde46f818ba719b50f1f958272f/config/production.yaml.example#L35) it should be okay with only `database.name`.

**Additional information**

* PeerTube instance:
  * URL: Private
  * version: 2.4.0
  * NodeJS version: v12.20.0
  * Ffmpeg version: 4.2.4

**Comment by Chocobozzz** [comment]
Hello,

You should have the `suffix` key inherited from `default.yaml`. Then in your `production.yaml`, you can safely remove the `suffix` key and only provide the `name` key that PeerTube will use by default for the database name.
