### ISSUE TITLE
Add input-password type

### ISSUE THREAD

**Issue by madmath03** [Chocobozzz/PeerTube#3375]
**Describe the problem to be solved**

A plugin like [auth-ldap](https://framagit.org/framasoft/peertube/official-plugins/-/blob/master/peertube-plugin-auth-ldap/main.js#L46) displays the password in clear text in the settings form.

I would like plugins with sensitive information to allow edition without displaying their content.

**Describe the solution you would like:**

Add a `input-password` that plugins can use to set sensitive information.

**Describe alternatives you have considered**  

None that I can think of.

I think I can provide a PR for that with roughly this content:
*  From https://github.com/Chocobozzz/PeerTube/blob/781ba981263ee6524fea1a95836108d252a124f4/shared/models/plugins/register-client-form-field.model.ts#L1-L4 to 
```typescript
 type: 'input' | 'input-checkbox' | 'input-password' | 'input-textarea' | 'markdown-text' | 'markdown-enhanced'
```

* From https://github.com/Chocobozzz/PeerTube/blob/781ba981263ee6524fea1a95836108d252a124f4/client/src/app/shared/shared-forms/dynamic-form-field.component.html#L6-L8 to
```html
  <input *ngIf="setting.type === 'input'" type="text" [id]="setting.name" [formControlName]="setting.name" />

  <input *ngIf="setting.type === 'input-password'" type="password" [id]="setting.name" [formControlName]="setting.name" />

  <textarea *ngIf="setting.type === 'input-textarea'" type="text" [id]="setting.name" [formControlName]="setting.name"></textarea>

```

PS: I hope I'm not saying anything wrong that already exists :sweat_smile: (did not find anything in docs about it).

**Comment by rigelk** [comment]
You are welcome to submit a PR 🙂
