### ISSUE TITLE
Can't show more than 25 videos on local category with "show private video" setting on a 1440p display.

### ISSUE THREAD

**Issue by skid9000** [Chocobozzz/PeerTube#3379]
**Describe the current behavior**
I'm unable to load more than 25 local videos when i enable the "show private videos" setting on my 1440p monitor.

**Steps to reproduce:**

1. Use a 1440p monitor and be the admin of an instance.
2. Go to Local videos and enable the "show private videos" setting.
3. Not all videos will show up

**Describe the expected behavior**

I should be able to scroll through all videos.

**Additional information**

So i tried again on a 1080p monitor and it worked like a charm, so i was wondering why it's doing this.
I tried to resize the window, scroll down to load more vids and it worked, but as soon as i maximized my window again, it won't scroll down more.
I tried with and without dark theme : same result.
No plugins installed.

* PeerTube instance:
  * version: 2.4.0
  * NodeJS version: v12.20.0
  * Ffmpeg version: 4.1

* Browser name, version and platforms on which you could reproduce the bug: Firefox 83, Vivaldi 2.11.1811.47

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/617f4f5cb2ac44df481851ff4165a79820b6b146
