### ISSUE TITLE
preview image can not be deleted

### ISSUE THREAD

**Issue by gerhardbeck** [Chocobozzz/PeerTube#3380]
**Describe the current behavior**
When uploading a preview image I can't delete it. There needs to be selected another image
**Steps to reproduce:**

1.Upload a preview image
2.try to delete it

**Describe the expected behavior**
possibility to delete a preview iamge

**Additional information**

* PeerTube instance:
  * URL: kirche.peertube-host.de
  * version: 2.4.0

* Browser name, version and platforms on which you could reproduce the bug:
Firefox 83.0

**Comment by Chocobozzz** [comment]
Hello

What do you expect after the image deletion? That PeerTube automatically generates a thumbnail?

**Comment by gerhardbeck** [comment]
Hello,
my problem is: I can't delete a set image.
I would expect an automatically generated thumbnail as if I didn't use an image.
My Problem was: I chose an image, it was stretched and looked awful and just wanted to delete it

**Comment by Arvi89** [comment]
There are 2 issues here: First if an image doesn't have the right dimension it will be stretched and look bad, second we can't delete a preview.

**Comment by gerhardbeck** [comment]
True. Shall I open a secons issue?

Am 30.01.2021 02:56 schrieb Arvi Lefèvre:

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/1322
