### ISSUE TITLE
More granular moderator settings

### ISSUE THREAD

**Issue by erkinalp** [Chocobozzz/PeerTube#3381]
**Describe the problem to be solved**
Moderators can only be set per-instance currently.
**Describe the solution you would like:**
Allow per channel, per channel-group and per video moderators in addition to per instance moderators.

**Comment by rigelk** [comment]
Hi @erkinalp! Please look out for related issues before creating one, as https://github.com/Chocobozzz/PeerTube/issues/1294 already covers this. You can then detail further your use case there, and upvote the issue to help us triage it.

**Comment by Chocobozzz** [comment]
Hello,

I'm not sure it's a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1294: this issue seems to define moderators for specific videos and channels. But it's imho out of the scope of peertube. Maybe plugin hooks could help

**Comment by erkinalp** [comment]
How would a plug-in help if the underlying permission system cannot represent the permissions required for the task?
