### ISSUE TITLE
Manually trigger a failed job

### ISSUE THREAD

**Issue by 1000i100** [Chocobozzz/PeerTube#339]
I have failed transcoding jobs because of too old ffmpeg version https://github.com/Chocobozzz/PeerTube/issues/334#issuecomment-373049322

Now i have up to date ffmpeg, how can i re-run theses failed jobs to generate transcoded video ?

**Comment by Chocobozzz** [comment]
You can't for now with the interface. But you can set the job in `inactive` state directly in Redis.

**Comment by GammaNu** [comment]
I'm not familiar with redis but i've just tried to do it.

I've just set it in redis : 
```bash
$ redis-cli hmset q-video.1000i100.fr:job:2 state inactive max_attempts 10
OK
$ redis-cli hmget q-video.1000i100.fr:job:2 type state attempts max_attempts
1) "video-file"
2) "inactive"
3) "1"
4) "10"
```
now, when i list jobs in the webui https://my.instance/admin/jobs/list
i see it with sate : inactive, but in failed jobs. (if i filter by inactive state : nothing, if i filter by failed state, it show this job in inactive state and others in failed state)

Is there a cron who will change that ? did i need to restart peertube ?

**Comment by GammaNu** [comment]
Any easy way right now for me to finish these jobs ? Or do i need to wait for the feature to be implemented ?

**Comment by Chocobozzz** [comment]
Just reupload the video if you did not manage to re run the failed job with redis :)

**Comment by GammaNu** [comment]
```
$ redis
> RENAME q-video.1000i100.fr:jobs:failed q-video.1000i100.fr:jobs:inactive
OK
> RENAME q-video.1000i100.fr:jobs:video-file:failed q-video.1000i100.fr:jobs:video-file:inactive
OK
```
do the tricks

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/commit/0c948c1659c0a6010f2bf58c402b1c9af192aa5e should resolve this issue
