### ISSUE TITLE
Mastodon comments on videos visible through Mastodon but not through PeerTube

### ISSUE THREAD

**Issue by FediVideos** [Chocobozzz/PeerTube#3390]
(Hi, I have never used Github before so sorry if I have made any errors here, I have tried my best to fill in everything)

When posting comment on PeerTube video from Mastodon, comment not visible in PeerTube (though it is visible when PeerTube post is viewed through Mastodon, even from other Mastodon instances).

**Steps to reproduce:**

1. Log into Mastodon account (I used mas.to instance currently running Mastodon v3.3.0rc1)
2. Post on PeerTube post from within Mastodon interface (I posted comment on video https://tilvids.com/videos/watch/5ede6b4a-a7e2-41ee-b45f-28ce1e324c2e )
3. Compare post viewed through Mastodon and viewed directly through PeerTube, you should see my comment if you're looking through Masto but not through PT

**Describe the expected behavior**

Mastodon comments on PeerTube videos should (and have previously) appeared under the PeerTube video when viewed within PT itself

**Additional information**

I have previously commented successfully on videos on the same instance (for example here, you will need to expand the comments to see my comment, https://tilvids.com/videos/watch/21dac999-f4bc-497f-8c79-af68bfad127d )
I contacted the instance admin and they said no settings had been changed, they had no idea why this was happening now when it didn't before.

* PeerTube instance:

https://tilvids.com

  * URL:

https://tilvids.com

  * version:

2.4.0

  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:

Firefox 83.0, Ubuntu 20.04

* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

It seems there is an issue on tilvids.com instance: it does not process inbox messages. Could you contact them so they see it there are errors/warnings in their log?

**Comment by TILvids** [comment]
Hmm, I see "stuff" in the log, but not sure what I would be looking for. Are there and specific warnings that you might expect to see with this issue that I should scan for?

**Comment by Chocobozzz** [comment]
> Are there any specific warnings that you might expect to see with this issue that I should scan for?

No sorry I don't know. You can also send me your logs by email (in my github profile) if you want.

**Comment by TILvids** [comment]
> No sorry I don't know. You can also send me your logs by email (in my github profile) if you want.

Ok, I'll try emailing you. Which logs do you want ("Audit Logs" or "Standard Logs") and over what period of time, to start?

**Comment by Chocobozzz** [comment]
You can zip your log directory from the server and send it to me (it's the "Standard Logs" on the web interface). From the beginning of this day should be fine.

**Comment by TILvids** [comment]
Ok @Chocobozzz I sent it to the address you had listed, hopefully that is helpful!

**Comment by FediVideos** [comment]
I am still currently unable to follow PeerTube (for example Tilvids.com, Vidcommons.org or Diode.zone) from Mastodon (my accounts are on Mas.to, Mastodon.online and Mstdn.social), and my comments do not appear in PT.

The Mastodon instances I currently observe the problems on are all using 3.3.0rc1. For anyone trying to reproduce this, I would ask you to try this on a Masto instance running 3.3.0rc1 or newer. Also, for reproducing the follow problems, I would ask you to refresh your view of the affected PT profile within Mastodon as it seems to work initially but a refresh reveals the truth.

Note that comments and follows I made _before_ the updates to Mastodon are still working fine, it is just if I attempt to do any new follows or make new comments that they don't work. Maybe Mastodon's recent update broke something between Masto and PT?

I am wondering if these issues are caused by Mastodon rather than PeerTube, as they seemed to appear for me when instances I use upgraded their Masto version. Should I be posting on here or on Mastodon's git?



![MastoNoFollow6](https://user-images.githubusercontent.com/75383929/102018495-717de780-3d65-11eb-82fe-73fbe1d580e1.png)
![MastoNoFollow5](https://user-images.githubusercontent.com/75383929/102018496-72167e00-3d65-11eb-9131-0e2f5923b010.png)
![MastoNoFollow4](https://user-images.githubusercontent.com/75383929/102018497-72af1480-3d65-11eb-8714-465646b28db3.png)

**Comment by FediVideos** [comment]
Update: Just tried again, one hour later, and Vidcommons now works for me. It's like the bug comes and goes? Very weird.

**Comment by FediVideos** [comment]
Another Update: Tried yet again, now both Diode.zone and Vidcommons work on mastodon.online but not on mas.to or mstdn.social.

It does maybe seem like some property of the Mastodon instance is the deciding factor here on whether these bugs happen?

**Comment by FediVideos** [comment]
I have raised the follows issue (which seems to be related to this) over on the Mastodon git. Will report back if they find anything.

**Comment by rigelk** [comment]
@FediVideos could you cross-reference the issue?

**Comment by FediVideos** [comment]
> @FediVideos could you cross-reference the issue?

How do I do that? (I have never really used Github before this)

The issue is here:
https://github.com/tootsuite/mastodon/issues/15347

**Comment by rigelk** [comment]
@FediVideos that's just what you did 😉 thanks

**Comment by FediVideos** [comment]
> Another Update: Tried yet again, now both Diode.zone and Vidcommons work on mastodon.online but not on mas.to or mstdn.social.

...and now they don't work any more. Follows become follow requests again on every Masto instance I try.

It's a bit frustrating as the accounts and videos I currently most want to promote are on Tilvids.com, Vidcommons.org and Diode.zone but none of their accounts can be followed any more.

I've contacted admins of all instances, they all say nothing has changed at their end, they don't know why this is happening.

**Comment by FediVideos** [comment]
By the way, is it ok to change the title of this issue? The absolute main issue I am worried about is the broken Masto-PT follows, comments are a secondary issue.

(I did originally open the broken follows as a separate issue but it was merged into this)

**Comment by Chocobozzz** [comment]
I registered on mastodon.online that runs mastodon v3.3.0rc3. I was able to follow films@vidcommons.org and https://diode.zone/accounts/boltzbrain

tilvids.com is still broken, but I think a peertube restart should fix the issue.

**Comment by FediVideos** [comment]
That's 

> I registered on mastodon.online that runs mastodon v3.3.0rc3. I was able to follow [films@vidcommons.org](mailto:films@vidcommons.org) and https://diode.zone/accounts/boltzbrain
> 
> tilvids.com is still broken, but I think a peertube restart should fix the issue.

I just tried it from my mastodon.online account, neither of those are followable for me (see screenshots). It initially seems like the follow went through, but when I refresh it turns into a follow request.

![Screenshot_2020-12-30 Mastodon](https://user-images.githubusercontent.com/75383929/103373074-d5c1da80-4acb-11eb-9502-79ff4bc6271f.png)
![Screenshot_2020-12-30 Mastodon2](https://user-images.githubusercontent.com/75383929/103373078-d9556180-4acb-11eb-8705-3413ec57f593.png)

**Comment by FediVideos** [comment]
> I registered on mastodon.online that runs mastodon v3.3.0rc3. I was able to follow [films@vidcommons.org](mailto:films@vidcommons.org) and https://diode.zone/accounts/boltzbrain
> 
> tilvids.com is still broken, but I think a peertube restart should fix the issue.

Woohoo, confirmed! Tilvids admin informed me they restarted it today, so I just tried again. Both follows and comments now seem to be working fine!

Well done, and thanks for looking into this issue in the first place.

**Comment by ozonedGH** [comment]
Has this been resolved?

I've just hit an issue where the logs indicated that I was getting activity in, but the comments weren't reflected on the video page.  Mastodon.social could see the comments, but Peertube wasn't reflecting them.

A restart did not work, but a full stop and start did work for most of the comments.

Didn't know if I was hitting a new issue or this is still a thing?
