### ISSUE TITLE
When following from Mastodon, follows are now being reported as Follow Requests

### ISSUE THREAD

**Issue by FediVideos** [Chocobozzz/PeerTube#3391]
(Hi, I am not sure if this is a problem in PeerTube or Mastodon. If you think it is Mastodon, I will post this in their git instead.)

**Describe the current behavior**

I was previously able to follow PeerTube accounts from Mastodon successfully on instances Tilvids.com and Vidcommons.org, following from my accounts on Mastodon instances mas.to, mastodon.online and mstdn.social

Now though, if I try to follow the same accounts or new ones from any of my Mastodon accounts, it shows in Mastodon as a "follow request" rather than a follow.

**Steps to reproduce:**

1. Log into a mastodon account (for example on mas.to)
2. Open a PeerTube profile within the mastodon instance (for example a profile from tilvids.com or vidcommons.org)
3. Click follow on the profile from within Mastodon, then refresh the page. The "following" button should change to a "follow request" button. 

**Describe the expected behavior**

Should show "following", not "follow request"

**Additional information**

This bug did not happen a few months ago. I contacted Tilvids.com and Vidcommons.org admins and they said they weren't sure why this was happening now.

* PeerTube instance:
TilVids and Vidcommons

  * URL:

https://tilvids.com
https://vidcommons.org

  * version:
2.4.0 (both)

  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
Firefox 83.0, Ubuntu 20.04

* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/3390

I can reproduce the bug on tilvids.com but not on vidcommons.org

**Comment by FediVideos** [comment]
Hi,

I have again tried following various PT instances on three different Mastodon instances (mas.to, mastodon.online and mstdn.social). All of the Masto instances were running the latest version (3.3.0rc1).

At first when I try to follow PeerTube accounts from Mastodon (PT instances are tilvids.com, Vidcommons.org and diode.zone), it appears to work.

However, if I refresh the PeerTube account's page within Mastodon, the "Unfollow" button changes to a "Cancel follow request" button, and when new videos are added by the PeerTube account they do not appear in my stream on Mastodon so following seems to be broken.

Could you try reproducing this on a Masto instance running 3.3.0rc1 and refreshing the profile page within Mastodon of the PT account you tried to follow?

The weird thing is this used to work ok when the instances were running older versions of Mastodon. I am wondering if something in Mastodon itself has recently broken the ability to follow PeerTube instances.

Because of this, I am not sure whether to raise this issue here or on the Mastodon git?

**Comment by FediVideos** [comment]
> Merging this issue in #3390
> 
> I can reproduce the bug on tilvids.com but not on vidcommons.org

Did you try to reproduce this using a Mastodon instance running 3.3.0rc1 or newer?

**Comment by FediVideos** [comment]
This is happening again on Tilvids, they've tried rebooting it and it makes no difference. It started a few days ago.

It's now impossible to follow Tilvids from Mastodon, it just shows "follow request" but no actual follow happens.

**Comment by emansom** [comment]
> This is happening again on Tilvids, they've tried rebooting it and it makes no difference. It started a few days ago.
> 
> It's now impossible to follow Tilvids from Mastodon, it just shows "follow request" but no actual follow happens.

Can't subscribe from another PeerTube instance on Tilvids channels neither.

**Comment by Chocobozzz** [comment]
Thanks, that should be fixed by https://github.com/Chocobozzz/PeerTube/commit/a6b26afc561703cc343f8962906734324b8c2d0c

**Comment by FediVideos** [comment]
Oh fantastic! Thank you for your hard work, let's keep fingers crossed the bug is squashed! :clap: Wooo!
