### ISSUE TITLE
Support save replay of permanent live

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#3396]
When a live ends, create a replay by creating another video with a generic name.

**Comment by Booteille** [comment]
Yup. I think that would be nice to be notified once the replay is generated with a message like "A replay of your last live session is now available. You could edit its informations.".

For two reasons :+1: 
* So we don't forget it's only fulfilled with a generic name
* Know our live has been recorded. In case we missed this point before.

**Comment by saumyakswain** [comment]
This one would be really great. As default name, start and end time appended to the permanent live name would be fine. The admin can modify the name to a more meaningful one later.

**Comment by toon462** [comment]
ในวันที่ ศ. 7 พ.ค. 2021 21:41 น. Saumya Kanta Swain <
***@***.***> เขียนว่า:

**Comment by saumyakswain** [comment]
Hey @Chocobozzz, have we made any progress on this?

**Comment by Chocobozzz** [comment]
Yes, I implemented it in https://github.com/Chocobozzz/PeerTube/commit/4ec52d04dcc5d664612331f8e08d7d90da990415!
