### ISSUE TITLE
filter:api.videos.list.* hooks not triggered at /users/me/videos

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3398]
**Describe the current behavior**
When calling `/users/me/videos` the `filter:api.videos.list.result.list` and `filter:api.videos.list.result.params` isn't called. This can be seen here

https://github.com/Chocobozzz/PeerTube/blob/e26dc0cdbda13f8b65ab2be3a0e13e7ef5c4b98c/server/controllers/api/users/me.ts#L98-L104

According to the API for wrapPromiseFun it seems that it's not supported to pass multiple arguments since `params` argument is just a single variable. Shall we change `params` to an array instead? Then we can spread the array upon calling `fun`.

https://github.com/Chocobozzz/PeerTube/blob/2a2839860e281770d8a2f2efaacbf9553bc569fb/server/lib/plugins/hooks.ts#L15-L19

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/a4d2ca071514b4838544f2fd7229d2e8cb9da0d4
