### ISSUE TITLE
WebTorrent Size Issue

### ISSUE THREAD

**Issue by Edward-Stryfe** [Chocobozzz/PeerTube#34]
Currently there is issues with chrome for sure I'm not sure about firefox or other browsers, but uploading or downloading a file that's a lot greater than 1.8gb doesn't work, does the webseeding of the videos prevent this? If not there would have to be a way to recognize the size and opt to use the webseed directly (until the issue is resolved )

**Comment by Chocobozzz** [comment]
Hi @Edward-Stryfe,

I uploaded a video a video of 2.5GB on the demo server: https://peertube.cpy.re/videos/watch/9c57954f-8f65-4341-8109-65aa3fb39923.

I don't see any problems on Firefox or Chromium. The video is downloaded and seeded normally.

For information, all the uploaded videos are webseeded by the server whatever its size.
