### ISSUE TITLE
Highlight link

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#3402]
![2020-12-06_064042](https://user-images.githubusercontent.com/43164089/101273542-e21c7700-375b-11eb-9b5d-1c813df3080b.png)
Where can I edit to change the style?

Sometimes many users ask me, where is the button to recover account, or to register?
I want to know, how can I put it at least more highlighted, or in bold

**Comment by Poslovitch** [comment]
https://github.com/Chocobozzz/PeerTube/pull/3357 provides improvements to the login page UX/UI.

I don't know when it will be merged, but hopefully it'll be soon enough.
