### ISSUE TITLE
moderator messaging with users

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3417]
**Describe the problem to be solved**
situation: i am a moderator in a public instance. a user uploads a video but i personally find some issue with the video description for example. right now i would either comment publicly on the video or find a way to contact the user. i could report the video myself and still i don't know how to have a private conversation with that user so that the issue can be resolved

**Describe the solution you would like:**
i am suggesting that we have a feature, "message to reporter" in the the report video section. there, if a user reports a video for any reason, we can talk to that reporter and whatever. this message log can be seen by all admins.

i am suggesting adding this feature to user accounts as well. in #3416 i suggested an admin view. same thing here. this feature would be a part of the admin log. so, in the above situation, i find the issue video and i message the user as an admin and talk. the user gets a notification and they can reply to me. 

This conversation would remain in its own section in the admin log so that tomorrow another admin can just check the user account, check the log and see what i talked to that person. these two would help in moderation immensely

**Comment by Chocobozzz** [comment]
Thanks but it's a "duplicate" (more a specific use case) of https://github.com/Chocobozzz/PeerTube/issues/2513
