### ISSUE TITLE
permission for allowing unlisted/private videos

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3418]
**Describe the problem to be solved**
https://github.com/Chocobozzz/PeerTube/issues/3415#issuecomment-739885905

allow admins to give permission to users to allow or disable unlisted/private videos.
this permission can be tied together with the global upload limits, we could define by default no users can upload private videos or unlisted ones. manual approval would be needed to upload these video types and that would solve many issues including the problem of users on public instances uploading videos and setting to unlisted and playing through embed player
https://github.com/Chocobozzz/PeerTube/issues/1356
https://github.com/Chocobozzz/PeerTube/issues/3226

**Describe the solution you would like:**

**Describe alternatives you have considered**

**Comment by Chocobozzz** [comment]
Hello,

Please see https://github.com/Chocobozzz/PeerTube/issues/3226#issuecomment-716389448. We did not have many admins asking for this kind of feature, so we would rather it not be implemented in core peertube.

We added an helper so you can remove privacy from your instance using plugins: https://docs.joinpeertube.org/#/api-plugins?id=video-privacy-manager-api
