### ISSUE TITLE
Auto Detection of Web Feeds by Web Browsers

### ISSUE THREAD

**Issue by GreenLunar** [Chocobozzz/PeerTube#3422]
**Describe the problem to be solved**
There's no native way for web feeds to be indicated by web browsers nor Feed readers.

**Describe the solution you would like:**
Add tags with which web browsers and feed reader be able to auto-detect web feeds.

```
<link href="https://share.tube/feeds/videos.xml?sort=-publishedAt&filter=local" rel="alternate" title="ShareTUBE [a PeerTube Fediverse Server] (media rss 2.0)" type="application/rss+xml">

<link href="https://share.tube/feeds/videos.atom?sort=-publishedAt&filter=local" rel="alternate" title="ShareTUBE [a PeerTube Fediverse Server] (atom 1.0)" type="application/atom+xml">

<link href="https://share.tube/feeds/videos.json?sort=-publishedAt&filter=local" rel="alternate" title="ShareTUBE [a PeerTube Fediverse Server] (json 1.0)" type="application/json">
```

**Comment by rigelk** [comment]
Hi @GreenLunar! Please look out for related issues before creating one, as https://github.com/Chocobozzz/PeerTube/issues/541 already covers this. You can then detail further your use case there, and upvote the issue to help us triage it.

**Comment by GreenLunar** [comment]
Thanks
