### ISSUE TITLE
Import video direct from server file system

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3425]
### **Describe the problem to be solved**
There can be several reasons that the current video import/creation methods doesn't fit (or work at all) for single video uploads:

**Browser upload**
* There's an upload limit at a CDN that's in front of the PeerTube instance (in our case the limit is 100 mb).
* Upload fails due to unstable connection (_Allow uploads to be resumed #324_).
* There's no web browser where the file is located (e.g. at a server).

**URL import**
* Possible quality loss since not uploading the video source.
* Third part dependency that can break the functionality (e.g. IP being banned by Youtube).

**Torrent import**
* Requires knowledge about how to create and seed torrents.
* Requires public sharing the source file during import (unless using an own tracker).

For bulk video upload/import the only choice is _URL import_ (?). I guess the most common import is from Youtube, which doesn't allow downloading the video files and therefore banning IP's that doing so.

To make it easier to switch to PeerTube it would be great if there's a reliable way of bulk upload/import.

### **Describe the solution you would like:**
An easy way to manually import files for a sysadmin. Both bulk and single file imports.

### **Describe alternatives you have considered**
Extend `create-import-video-file-job` so that when not providing an uuid a new video is created in private mode. This would mean that users can mount their video library with Dropbox, rsync, fuse or whatever they like and bulk import it to PeerTube. Then a moderator can edit the video informations via the web GUI.
```
npm run create-import-video-file-job -- --help

Usage: create-import-video-file-job [options]

Use cases:
* Create a new video
* Replace an already uploaded file
* Add a new resolution

Options:
  -v, --video [videoUUID]   Video UUID. If not provided a new video will be created.
  -i, --import [videoFile]  Video file.
  -cid --channel-id          Mandatory when video UUID isn't provided.
  -sid --source-id          Optional id used by the source, to help keeping track of imports and avoid duplicates.
  -h, --help                Display help for command
```

Example usage:

```
npm run create-import-video-file-job -i "Abba - Waterloo.mpg" -cid 1 -sid "music-videos/abba-waterloo.mpg"
```

**Comment by Chocobozzz** [comment]
Hello,

You can use the upload script from your server. You just have to bypass your CDN.

**Comment by kontrollanten** [comment]
Yes, but since PeerTube doesn't support for hostname change/multiple hostnames I have to change my DNS resolver (or just edit /etc/hosts) to point to my load balancer (instead of CDN) to make this possible. I know that PT doesn't support to be ran behind a load balancer, but I think it can be good to have a way to import a file without to have to go through the internet when the file already is on the server. E.g. when handling huge files or just doesn't have fast internet connection.

With some kind of API to import a file from server file system it should be possible to create a plugin that can handle video uploads from other hostnames (to bypass the CDN).

**Comment by Chocobozzz** [comment]
Uploading to `localhost:9000` does not work?

**Comment by kontrollanten** [comment]
Since PeerTube doesn't support multiple hostnames I guess that can mess things up in the database?

**Comment by Chocobozzz** [comment]
No you just upload your file using this URL, but PeerTube will just use the host from its own config. It does not create URLs depending on the request host.

**Comment by minecraftchest1** [comment]
This is just a workaround. While it may work for the op, imports direct from the filesystem may be faster for some people and provides more flexibility.
