### ISSUE TITLE
Importing file with the CLI tool generates only one resolution HLS files

### ISSUE THREAD

**Issue by pprw** [Chocobozzz/PeerTube#3429]
On Peertube 2.4.0 with HLS activated (and webtorrent disabled).

*This is not a audio+HLS related bug*. In the example below the first (and only) resolution is the audio ("0") one but I tried with no audio transcoding and it is the same with 480p resolution.

For an existing video "13ca222d-325a-4201-b18f-25dc7d58782b" available in webtorrent only:

1. I deleted webtorrent files
`sudo -u peertube rm -v /var/www/peertube/storage/videos/13ca222d-325a-4201-b18f-25dc7d58782b*`

2. I uploaded again the original file on peertube server and import it with:
```
$ sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run create-import-video-file-job -- -v 13ca222d-325a-4201-b18f-25dc7d58782b -i original-file.mp4 

> peertube@2.4.0 create-import-video-file-job /var/www/peertube/versions/peertube-v2.4.0
> node ./dist/scripts/create-import-video-file-job.js "-v" "13ca222d-325a-4201-b18f-25dc7d58782b" "-i" "original-file.mp4"

Import job for video 13ca222d-325a-4201-b18f-25dc7d58782b created.
```
I have a new file inside /var/www/peertube/storage/videos
```
/var/www/peertube/storage/videos$ ls -hl * | grep 13ca222d-325a-4201-b18f-25dc7d58782b
-rw-r--r-- 1 peertube peertube  636M déc.   8 16:06 13ca222d-325a-4201-b18f-25dc7d58782b-900.mp4
```
3. I want to generate HLS file and launch:
```
$ sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run create-transcoding-job -- --generate-hls -v 13ca222d-325a-4201-b18f-25dc7d58782b

> peertube@2.4.0 create-transcoding-job /var/www/peertube/versions/peertube-v2.4.0
> node ./dist/scripts/create-transcoding-job.js "--generate-hls" "-v" "13ca222d-325a-4201-b18f-25dc7d58782b"

Transcoding job for video 13ca222d-325a-4201-b18f-25dc7d58782b created.
Transcoding job for video 13ca222d-325a-4201-b18f-25dc7d58782b created.
Transcoding job for video 13ca222d-325a-4201-b18f-25dc7d58782b created.
Transcoding job for video 13ca222d-325a-4201-b18f-25dc7d58782b created.
Transcoding job for video 13ca222d-325a-4201-b18f-25dc7d58782b created.
Transcoding job for video 13ca222d-325a-4201-b18f-25dc7d58782b created.
```
**Result: Peertube generates only the HLS fragmented mp4 audio file (13ca222d-325a-4201-b18f-25dc7d58782b-0-fragmented.mp4 with two m3u8 files and the json see below) and then delete the /var/www/peertube/storage/videos/13ca222d-325a-4201-b18f-25dc7d58782b-900.mp4.**

If I disable audio transcoding, it will generated 480p HLS files and stop.

```
streaming-playlists/hls/13ca222d-325a-4201-b18f-25dc7d58782b$ ls -lh
total 167M
-rw-r--r-- 1 peertube peertube 181K déc.   8 17:13 0.m3u8
-rw-r--r-- 1 peertube peertube 166M déc.   8 17:13 13ca222d-325a-4201-b18f-25dc7d58782b-0-fragmented.mp4
-rw-r--r-- 1 peertube peertube  102 déc.   8 17:13 master.m3u8
-rw-r--r-- 1 peertube peertube 152K déc.   8 17:13 segments-sha256.json
```

Log says other resolutions were not created because there is no b18f-25dc7d58782b-900-fragmented.mp4 file.

> var/www/peertube/storage/streaming-playlists/hls/13ca222d-325a-4201-b18f-25dc7d58782b/13ca222d-325a-4201-b18f-25dc7d58782b-900-fragmented.mp4: No such file or directory

**Comment by Chocobozzz** [comment]
Hello,

You must not delete files from disk because PeerTube tracks these file in the database. It may be the source of your bug
