### ISSUE TITLE
Video description Text is truncated after transcoding the Video

### ISSUE THREAD

**Issue by musinux123** [Chocobozzz/PeerTube#3433]
**Describe the current behavior**

A long Video description is truncated after transcodng the video. In the Video-Import-GUI all text can be seen. Also an Update of the truncated text with the long text version  is possible. After aprox. 1 to 5minutes after reloading the Videoplayer Page the  additional Text disappears and is truncated to the first lines again.

Please help!

(Really nice and owerful software you've created. Thats a real reolution for Video Hosting)

**Additional information**

* PeerTube instance:
  * URL: www.wiki-tube.de

Example: https://www.wiki-tube.de/videos/watch/9adc5e2b-c55b-43a8-9993-38d2465dcaba

  * version: 2.4
  * NodeJS version: 10.23.0
  * Ffmpeg version:

**Comment by kontrollanten** [comment]
Hi! That was a strange issue. We're running the same version with PeerTube but we're not facing this on our videos with long description (+3900 characters).

How does your process look like? Are you importing or uploading? Are you adding the long description in the import/upload step, or do you update the video with the description afterwards?

After the text is truncated, if you try to update the video with the whole description, will it be removed again then?

**Comment by musinux123** [comment]
Oh thanks for the immediate Response.

Am 9. Dezember 2020 06:57:52 MEZ schrieb kontrollanten <notifications@github.com>:
>Hi! That was a strange issue. We're running the same version with PeerTube but we're not facing this on our videos with long description (+3900 characters).
>
>How does your process look like? Are you importing or uploading? Are you adding the long description in the import/upload step, or do you update the video with the description afterwards?




All the Videos in the mentioned channel were imported directly from Youtube. 



>
>After the text is truncated, if you try to update the video with the whole description, will it be removed again then?
>

Yes. Correct. Spooky! Could be an issue with the database?

In addition I 've to mention, that I tried to import an icon in the channel, which was not good somehow. The icon dissappeared somehow. And now i can import a new icon, which is displayed for approx 5 minutes an dissappears afterwards...

Spooky , too.... 



Best regards,
Markus 

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Chocobozzz** [comment]
Hello,

It seems there is an issue with your instance URLs. Somehow  sending View activities to itself (reason why the views counter is that high). The thing is that you updated your hostname using `www.wiki-tube.de` whereas started the first time peertube using `wiki-tube.de`. 

To fix this, use: https://docs.joinpeertube.org/#/maintain-tools?id=update-hostjs

It should fix the Views loop, maybe the avatar and the description issues

**Comment by musinux123** [comment]
oh great. Thanks!

Am 9. Dezember 2020 10:21:14 MEZ schrieb Chocobozzz <notifications@github.com>:
>Hello,
>
>It seems there is an issue with your instance URL. Somehow sending View activities to itself (reason why the views counter is that high). The thing is that you updated your hostname using `www.wiki-tube.de` whereas started the first time peertube using `wiki-tube.de`. 
>
>To fix this, use: https://docs.joinpeertube.org/#/maintain-tools?id=update-hostjs
>
>It should fix the Views loop, maybe the avatar and the description issues
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Chocobozzz/PeerTube/issues/3433#issuecomment-741644532
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
