### ISSUE TITLE
Sizzling with Firefox, video made with powerpoint

### ISSUE THREAD

**Issue by bristow** [Chocobozzz/PeerTube#3436]
A user of our PT platform in 2.3 uses PowerPoint 2016 to generate his videos. 

The source file does not sizzle on my ubuntu 20.04 (idem on Win10) but as soon as he sends it on PT 2.3 or PT version dev (https://peertube2.cpy.re/videos/watch/dd5a1628-c9ea-491f-a872-2a742ca0d548) it sizzles strongly, but only on Firefox 83.0.
No worries on Chromium 87.0 :(

This user has found a parry which is not a solution. He sends his video on Youtube and then imports it via URL in PT, you agree with me that this is not a solution :)

Do you have an idea of the problem?

**Additional information**

* PeerTube instance 1:
  * URL: https://tube.ac-lyon.fr/
  * version: 2.3
  * NodeJS version:
  * Ffmpeg version:
* PeerTube instance 2:
  * URL: https://peertube2.cpy.re/
  * version: dev

* Browser name, version and platforms on which you could reproduce the bug:

  - Firefox 83.0 (64 bits) : KO
  - Chromium 87.0 (64 bits) : OK

**Comment by Chocobozzz** [comment]
Hello,

I think it's a firefox bug. I opened a ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1682532

**Comment by bristow** [comment]
Thanks for your investigation @Chocobozzz !

**Comment by Chocobozzz** [comment]
Closing since it's not a a peertube issue.
