### ISSUE TITLE
[thought] Peertube integration : a way for external apps to detect a peertube video from share url ?

### ISSUE THREAD

**Issue by DegrangeM** [Chocobozzz/PeerTube#3437]
**Describe the problem to be solved**
Currently, when you want to integrate a youtube video on an external platform, it's easy for the platform to detect it's a youtube video because it's in the domain name. The platform can then add the good player. However, for peertube, it's not easy because there is no fixed domain.

Moreover, the share url `https://XXX/videos/watch/YYYY` is very neutral and there is no way to know it's a peertube video. Sure, platform could detect url in this pattern as a peertube video, but I don't know if there is currently (or will one day) be an other video platform service with url in the same pattern.

**Describe the solution you would like:**

I don't know if there is a good solution. Maybe we could add the word peertube somewhere in the sharing url, but this as the disadventage of making the url uglier / longer.

Or maybe this is a non issue and the pattern is enough (moreover it seems the YYYY follow a 8-4-4-4-12 pattern) to avoid any collision with other video platform.

**Comment by kontrollanten** [comment]
How does your integration look like? If you're just using the embed iframe it may be a solution to add some property to the iframe tag? If you're parsing the watch-page you can read the `og:platform` property which says it's a PeerTube platform.

**Comment by DegrangeM** [comment]
Currently, I was thinking about the url and the the embed iframe code.

I wanted in the past to see to add the ability to use peertube video in the h5P video activity but got stuck with this issue of detecting a peertube video from the url.

Reccently, I saw that someone integrated peertube to BBB (again it's asking an url and not a iframe code)

https://github.com/bigbluebutton/bigbluebutton/pull/10918/files

The author used `RegExp("(https?)://(.*)/videos/watch/(.*)")`.

In both exemple, this check is done client side so it's not possible check the og:platform due to cross domain.

However : 

- your suggestion of an iframe tag could be usefull for other situation where the user paste the iframe code so why not add it ?

- Maybe if we don't want to add the word peertube in the share url, a solution could be to add a special url (like https://XXXX/peertube.check) with no cross domain limitation that juste return "true" and could be checked in javascript to confirm it's a peertube video when the url follow the /videos/watch/YYYY patern ?

**Comment by kontrollanten** [comment]
> * Maybe if we don't want to add the word peertube in the share url, a solution could be to add a special url (like https://XXXX/peertube.check) with no cross domain limitation that juste return "true" and could be checked in javascript to confirm it's a peertube video when the url follow the /videos/watch/YYYY patern ?

I'm not familiar with the use case so I can't really say something about that, but if there's a demand on a way to determine PeerTube instances I think your proposal sounds good.

**Comment by test2a** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/4853

Please check this issue on newpipe. I suggested the team to use the regex which has been developed by @stom79 for tubelab app which is an android peertube app on f droid and play store. Anyways, I have been using this app for months successfully and it works nicely for detecting peertube links.

You can try to adjust the regex for your usecase.

**Comment by stom79** [comment]
Yes, the regex extracts interesting parameters. Then with the domain and the video uuid extracted from the URL (and some other useful params like position), there is a call to the api of the instance. If it fails, the app delegates the intent to another app, so that's quite transparent for the end user.

**Comment by DegrangeM** [comment]
Then maybe a peertube endpoint returning true could be added to the api ?

**Comment by stom79** [comment]
I am not sure to understand. It will return true each time it's a peertube instance and a 404 otherwise. 

Regex doesn't ensure at 100% it's a peertube url. But the following call to the api ensure it. If it fails, it's not a peertube instance. Up to app dev to delegate that action.

**Comment by stom79** [comment]
Also, Peertube uses node info which allows to know the software behind the host name. Maybe this is what you're looking for?

**Comment by matheod** [comment]
@stom79 Yes this is perfect to detect confirm a peertube url after checking the regex, thanks.

I will close the issue.

**Comment by DegrangeM** [comment]
@stom79 Yes, this is perfect to confirm it's peertube after matching the regex. I will close the issue.
