### ISSUE TITLE
Disable long-press dialog to download video

### ISSUE THREAD

**Issue by alxlg** [Chocobozzz/PeerTube#3438]
**Describe the problem to be solved**

For each video you can enable or disable the Download button in the Web UI. But with some browsers (i.e. Firefox or Chrome on Android) the user can just perform a long-press on the video frame to show browser's dialog to download the video file. AFAIK this can be disabled by appending "no-download" in HTML's video tag.

**Describe the solution you would like:**

PeerTube automatically appending "no-download" tag to videos with Download button disabled.

**Describe alternatives you have considered**  

I'm trying to figure out how to do this with some JavaScript injected from Admin's panel without using JQuery. Any tips in this direction would be appreciated. It's enough to append no-download tag to all videos since videos with Download button enabled can be downloaded from there.

EDIT: it looks like the "nodownload" is just to disable the download option in Chrome's video player that PeerTube doesn't use anyway.

But on some websites I'm not able to download video by long-pressing on them so I'm trying to figure out how to do the same with PeerTube.

Because for me it doesn't make sense to disable the download button in the PeerTube UI while the video can still be downloaded by long-pressing on it :-/

**Comment by rigelk** [comment]
This property is not supported by every major browser: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/controlsList#Browser_compatibility

**Comment by alxlg** [comment]
> This property is not supported by every major browser: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/controlsList#Browser_compatibility

This means Firefox on Android will still show the dialog, am I right?

**Comment by rigelk** [comment]
Yes. Google has setup a test/sample page for the attribute: https://googlechrome.github.io/samples/media/controlslist.html
Firefox on Android definitely shows all controls.

**Comment by Chocobozzz** [comment]
Hi,

I'm closing this issue because we have our own context menu, and we prefer to not use experimental attribute not implemented in a majority of web browsers.

**Comment by alxlg** [comment]
@Chocobozzz FYI the custom menu seems to also solve this issue, since it replaces the native one that has the download button that I wanted to hide
