### ISSUE TITLE
Embeded player, sandobox, and security

### ISSUE THREAD

**Issue by bugsysop** [Chocobozzz/PeerTube#3440]
I’m working on integration of **Peertube player** with a Hugo static site, and have a security concern about the `iframe` code.

The `iframe` code generated by Peertube is something like this:

```
<iframe
    width="560" 
    height="315"
    sandbox="allow-same-origin allow-scripts allow-popups"
    src="https://indymotion.fr/videos/embed/c1cdd69f-6baa-42cd-b322-5498fead449b?title=0&warningTitle=0&controls=0&peertubeLink=0"
    frameborder="0" 
    allowfullscreen>
</iframe>
```

I read on various sources that there is a potential _security problem_ with combining `allow-same-origin` and `allow-scripts`. Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe 

**Are these variables absolutely mandatory for Peertube?**

Note: I tried to use the `iframe` without... It seems to work anyway

**Comment by Chocobozzz** [comment]
Hello,

Yes unfortunately all these attributes are required. So yes, you have to trust the PeerTube instance.
