### ISSUE TITLE
Filter for live videos in search

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3443]
**Describe the problem to be solved**
we now have live but there is no specific filter for it in the search filters.

**Describe the solution you would like:**
there are multiple search filters, sort, category, license, language, tags, duration. a live filter should be added so that one can filter only currently live videos. this filter would also be used in sepia search and you can find live videos in the vidiverse at one place.

**Comment by test2a** [comment]
searching for "live" would not work as previously live would be shown and that is not what i am aiming for. just videos that are live right now

**Comment by Booteille** [comment]
Would it make sense to have a filter for live replays too?

**Comment by test2a** [comment]
Arent live replays just regular videos? I don't know. Someone can clarify.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/7a22a0a56aa75fbb1ba986a5d2c606e1343f30c2
