### ISSUE TITLE
Error running peertube-import-videos.js

### ISSUE THREAD

**Issue by alxlg** [Chocobozzz/PeerTube#3444]
**Describe the current behavior**

Trying to import videos from a YouTube channel (with --since option) gives this error:

```
info: Will download and upload 10 videos.

(node:233035) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getTime' of null
    at /home/user/PeerTube/dist/server/tools/peertube-import-videos.js:100:67
    at Generator.next (<anonymous>)
    at fulfilled (/home/user/PeerTube/node_modules/tslib/tslib.js:111:62)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:233035) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:233035) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Steps to reproduce:**

1. Install CLI tools as described in the docs
2. Run peertube-import-videos.js

**Describe the expected behavior**
Importing the specified videos from the YouTube channel.

**Additional information**

* PeerTube instance:
  * URL: play.mepiu.it
  * version: 2.4
  * NodeJS version: 12.20.0
  * Ffmpeg version: 4.2.4

**Comment by kontrollanten** [comment]
Hi! What's the full command you're running? It looks like you're passing an invalid date as a parameter.

**Comment by alxlg** [comment]
> Hi! What's the full command you're running? It looks like you're passing an invalid date as a parameter.

Hi, I'm passing `--since $(date --date="-6 days" +%Y-%m-%d)` like the doc says: https://docs.joinpeertube.org/#/maintain-tools?id=peertube-import-videosjs

`date --date="-6 days" +%Y-%m-%d` is 2020-12-04

`--help` describes `--since` as `Publication date (inclusive) since which the videos can be imported (YYYY-MM-DD)`

**Comment by kontrollanten** [comment]
The line throwing the error is the following

```
if (youtube_dl_1.buildOriginallyPublishedAt(videoInfo).getTime() < program['since'].getTime()) {
```

According to the stack trace it's `youtube_dl_1.buildOriginallyPublishedAt(videoInfo).getTime()` that's failing, so not the you're passing as a param.

Can you open `dist/server/helpers/youtube-dl.js` and add `console.log(obj.upload_date)` at line 172 and then rerun the command? It looks like the date retrieved from youtube-dl is in an unknown format.

**Comment by alxlg** [comment]
@kontrollanten sure:
```
info: Will download and upload 10 videos.

undefined
(node:238622) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getTime' of null
    at /home/user/PeerTube/dist/server/tools/peertube-import-videos.js:100:67
    at Generator.next (<anonymous>)
    at fulfilled (/home/user/PeerTube/node_modules/tslib/tslib.js:111:62)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:238622) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:238622) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by alxlg** [comment]
youtube-dl with `--write-info-json` argument produce a JSON that contains this line: `"upload_date": "20201209"`.

Maybe the correct format is YYYYMMDD? I tried to pass it to peertube-import-videos.js but it says `Invalid date passed: 20201010. Expected format: YYYY-MM-DD. See help for usage.`

**Comment by Chocobozzz** [comment]
Try to reinstall node modules, it will update youtube-dl and maybe fix the issue.

I fixed the import script so it doesn't crash when the object doesn't have an upload date in https://github.com/Chocobozzz/PeerTube/commit/d8794cf85554a17e1f110f49a0c965be825a9b4a
