### ISSUE TITLE
DTube, IPFS & Duniter

### ISSUE THREAD

**Issue by zicmama** [Chocobozzz/PeerTube#345]
It is not really an Issue, but I wonder what the **PeerTube** community think about **DTube** ?
[edit] https://www.youtube.com/watch?v=323-v4kDdnk

I wonder how hard it will be to could use **IPFS** and **Duniter** as file storage and crypto-currency for producer payments rewards?
Ou autre...

**Comment by rigelk** [comment]
There's been a thread (in french) about DTube already: https://framacolibri.org/t/blockchain-et-peertube/2587 | there is also an interesting Hacker News thread about it: https://news.ycombinator.com/item?id=16481636.

I don't know about how Duniter works. A video producer could show a badge where their viewers could send Ğ1. But _tightly coupling_ PeerTube with a monetary reward system is something we are wary of; the gist of our opinion sits [in the dedicated FAQ section](https://github.com/Chocobozzz/PeerTube/blob/develop/FAQ.md#are-you-going-to-use-the-steem-blockchain).

As for IPFS, we simply haven't had time to look at it close enough. It sure looks interesting :) You are free to open an issue to document and discuss how we could use IPFS, though.
