### ISSUE TITLE
Free handles for deleted accounts or channels

### ISSUE THREAD

**Issue by alxlg** [Chocobozzz/PeerTube#3450]
**Describe the problem to be solved**

When I say "handle" I mean nicknames/IDs for accounts and channels. The problem here is that even after deleting an account from admin UI I can't create another account/channel with a handle previously used by the deleted account or its channels.

The UI to create a new users says: "Another actor (account/channel) with this name on this instance already exists or has already existed."

I don't see why one wouldn't be able to reuse a handle that doesn't point to anything anymore. AFAIK other social network like Twitter or Telegram let you pick previously used handles.

Also a user could register how many channel he wants and keep for him a lot of handles that have general interest, preventing others from genuinely use them.

**Describe the solution you would like:**

When an account or channel doesn't exist anymore, its handle should be available to others.

**Comment by test2a** [comment]
a question. how does youtube handle abuse that can and would probably be happening using this. i have a unique handle i want, i hack the login somehow and delete the channel/account and then re-register myself?

**Comment by alxlg** [comment]
> a question. how does youtube handle abuse that can and would probably be happening using this. i have a unique handle i want, i hack the login somehow and delete the channel/account and then re-register myself?

Who would commit cybercrime for a nickname?

However, I'm not even asking for the possibility to change your nickname as it happens on other social networks, I'm just saying to **free** it when the occupant **has deleted** their account / channel.

**Comment by alxlg** [comment]
If someone knows how to free a nickname previously used maybe by editing the database I would really appreciate it.

**Comment by rigelk** [comment]
hi @alxlg, @test2a,

The issue has already been discussed at length at https://github.com/Chocobozzz/PeerTube/issues/870, in which I invite you to contribute in order to keep discussions and participants informed.
