### ISSUE TITLE
Prefer channels as publisher instead of accounts

### ISSUE THREAD

**Issue by alxlg** [Chocobozzz/PeerTube#3451]
**Describe the problem to be solved**

The various pages listing videos like recent, popular etc display the **account** **nickname** under each video. It has been reported by many authors on the instance I manage that for them it makes more sense to display the **channel** **display name** and I think it really makes sense. YouTube shows channel display name, not user nickname.

To make clear what I'm talking about:
![immagine](https://user-images.githubusercontent.com/26327475/101904304-eb6f6e80-3bb5-11eb-87fb-d6824e6137bf.png)

**Describe the solution you would like:**

For example "Video Title by john_doe" should instead be "Video Title by Breaking News Channel" in the various pages listing videos.

**Comment by rigelk** [comment]
I agree, but we chose to display the account username to avoid impersonation: it is easy to have the same display name as anyone else. I guess we should have an infobox on display, and a user settings to revert back to the current situation.

**Comment by alxlg** [comment]
@rigelk if impersonation is the problem, why the user handle and not the channel one? AFAIK know they are all unique i.e. a channel and a username can't have the same handle.

Anyway not all instances are meant to be open to publishers, many could have closed registration and accounts are managed by root, so impersonation is not really a problem in that case and they would prefer the channel display name to channel handle.

**Comment by rigelk** [comment]
@alxlg YouTube's UX is not applicable here, mainly because a user can only have one channel. In PeerTube you can create many.

**Comment by alxlg** [comment]
@rigelk yes but on YouTube each account/user can create more channels but other users just see channels, not who created them.

Does someone know which are the files responsible for these pages so that I can try to edit them?

**Comment by rigelk** [comment]
> Does someone know which are the files responsible for these pages so that I can try to edit them

https://github.com/Chocobozzz/PeerTube//blob/5cac83a78d6ba5212755fafce2ed25f7c74b04e5/client/src/app/shared/shared-video-miniature/video-miniature.component.html#L36-L41

But please don't just replace that by your code and create a reusable component. We might use elsewhere a reusable line + card on hover too.

**Comment by WonderingDane** [comment]
I agree. The channel of which the video is from should be viewable. If people impersonate, it's a problem for the admins. It's much more important that users can see which channel a video is from.

**Comment by Chocobozzz** [comment]
In 3.2 we'll now display the channel instead of the account.

2 exceptions where we display the account username (still linking to the channel page):
 * If the channel display name is *Main/Default ${accountName} channel*
 * If the channel username is an uuid (channel created at the beginning of peertube)
