### ISSUE TITLE
Impossible de récupérer les identifiants du Client OAuth

### ISSUE THREAD

**Issue by FathiBenNasr** [Chocobozzz/PeerTube#3453]
Bonjour,

Suite à une mise-à-jour 2.20->2.4.0, j'ai des messages d'erreur lors de l'accès depuis un vnavigateur, tel que celui-ci:
Impossible de récupérer les identifiants du Client OAuth : undefined. Assurez-vous d'avoir correctement configuré PeerTube (dossier config/), en particulier la section "serveur web".
ou encore celui-ci: Cannot read property 'res' of undefined

* PeerTube instance: veedeo.sncft.com.tn
  * version: 2.4.0
  * NodeJS version: nodejs/unknown,now 12.20.0-1nodesource1 amd64
  * Ffmpeg version: ffmpeg/stable,stable,now 7:4.1.6-1~deb10u1 amd64
  * Redis version: redis-server/stable,stable,now 5:5.0.3-4+deb10u2 amd64
  * PostgreSQL version:  postgresql11-server-11.10-1PGDG.rhel7.x86_64 on a dedicated instance

[localhost:9000] 2020-12-11 13:20:02.952 warn: Login error. {
  "err": {
    "statusCode": 503,
    "status": 503,
    "code": 503,
    "message": "Cannot read property 'res' of undefined",
    "name": "server_error",
    "inner": {
      "stack": "TypeError: Cannot read property 'res' of undefined\n    at Object.<anonymous> (/var/www/peertube/versions/peertube-v2.4.0/dist/server/lib/oauth-model.js:89:34)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v2.4.0/node_modules/tslib/tslib.js:114:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/versions/peertube-v2.4.0/node_modules/tslib/tslib.js:110:16)\n    at Object.getUser (/var/www/peertube/versions/peertube-v2.4.0/dist/server/lib/oauth-model.js:88:20)\n    at Object.tryCatcher (/var/www/peertube/versions/peertube-v2.4.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/util.js:16:23)\n    at Object.<anonymous> (/var/www/peertube/versions/peertube-v2.4.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/method.js:15:34)\n    at PasswordGrantType.getUser (/var/www/peertube/versions/peertube-v2.4.0/node_modules/express-oauth-server/node_modules/oauth2-server/lib/grant-types/password-grant-type.js:91:43)\n    at PasswordGrantType.<anonymous> (/var/www/peertube/versions/peertube-v2.4.0/node_modules/express-oauth-server/node_modules/oauth2-server/lib/grant-types/password-grant-type.js:63:19)\n    at PasswordGrantType.tryCatcher (/var/www/peertube/versions/peertube-v2.4.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v2.4.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v2.4.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromiseCtx (/var/www/peertube/versions/peertube-v2.4.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:606:10)\n    at Async._drainQueue (/var/www/peertube/versions/peertube-v2.4.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:138:12)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v2.4.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/var/www/peertube/versions/peertube-v2.4.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:17:14)\n    at processImmediate (internal/timers.js:461:21)",
      "message": "Cannot read property 'res' of undefined"
    },
    "stack": "server_error: Cannot read property 'res' of undefined\n    at new ServerError (/var/www/peertube/versions/peertube-v2.4.0/node_modules/express-oauth-server/node_modules/oauth2-server/lib/errors/server-error.js:25:14)\n    at TokenHandler.<anonymous> (/var/www/peertube/versions/peertube-v2.4.0/node_modules/express-oauth-server/node_modules/oauth2-server/lib/handlers/token-handler.js:102:13)\n    at TokenHandler.tryCatcher (/var/www/peertube/versions/peertube-v2.4.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v2.4.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v2.4.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v2.4.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v2.4.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:689:18)\n    at Async._drainQueue (/var/www/peertube/versions/peertube-v2.4.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v2.4.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-v2.4.0/node_modules/express-oauth-server/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:17:14)\n    at processImmediate (internal/timers.js:461:21)"
  }
}

**Comment by rigelk** [comment]
Bonjour @FathiBenNasr,

Merci d'utiliser l'anglais sur GitHub, pour lequel nous avons choisi l'anglais comme langue commune d'échange. À défaut, vous pouvez utiliser le sous-forum francophone dédié à PeerTube sur framacolibri.org.

**Comment by Chocobozzz** [comment]
Hello,

Please reupgrade your instance: https://docs.joinpeertube.org/#/install-any-os?id=upgrade

It seems there is an issue in your instance dependency. If you use the manual upgrade, the command to install dependencies is `sudo -H -u peertube yarn install --production --pure-lockfile`

**Comment by FathiBenNasr** [comment]
> 
> 
> Bonjour @FathiBenNasr,
> 
> Merci d'utiliser l'anglais sur GitHub, pour lequel nous avons choisi l'anglais comme langue commune d'échange. À défaut, vous pouvez utiliser le sous-forum francophone dédié à PeerTube sur framacolibri.org.

Bonjour, c'est noté.
