### ISSUE TITLE
Weird behaviour with LDAP login

### ISSUE THREAD

**Issue by tilllt** [Chocobozzz/PeerTube#3454]
When trying to log-in to my second peertube instance, which has LDAP auth enabled, i get the follofing error:

Cannot create such user: an actor with that name already exists. 

What exactly does this mean and why can i not log in with the user, i dont want to "create" it, it should be there already.

**Comment by rigelk** [comment]
Hi! Thanks for reporting the issue, but you should open this kind of issue directly where the ldap plugin is developed: https://framagit.org/framasoft/peertube/official-plugins/-/tree/master/peertube-plugin-auth-ldap

**Comment by Chocobozzz** [comment]
Hello,

Did you deleted a user with the same username than your ldap account?
