### ISSUE TITLE
Fix yarn.lock with all version of dependencies

### ISSUE THREAD

**Issue by stevenroose** [Chocobozzz/PeerTube#3459]
I'm trying to package PeerTube for NixOS and it's a real problem that PeerTube's dependencies have to be pulled in over the internet on install. There is no way to do `yarn --offline` or so without having done a yarn non-offline first so that yarn fills the caches.

I tried to look for one, but it doesn't seem like yarn supports vendoring dependencies. I'm not sure if it's a common practice in the JS scene.

But it would be really nice if PeerTube would publish an all-in-one tarball that includes all its code dependencies.

That way, packagers can simply pull in that file, unpack it and they have all the needed dependencies without having to use yarn. (Not sure how to configure nodejs or so to do that. But it must be possible, right?)

**Comment by rigelk** [comment]
We didn't do this because of the resulting archive size we have to host and the marginal use case.

Maybe I'm forgetting past issues, but you're the first package maintainer to ask this! Surely other maintainers do the archive of the `node_modules` folder when they build their package. Is there something with NixOs that prevent that?

**Comment by stevenroose** [comment]
Yeah I'm still trying to dig deeper into what's preventing the regular yarn tooling in NixOS to work with PeerTube. The build environment of Nix packages is sandboxed and doesn't have internet access. So it needs to use --offline.

I think I don't really need the entire vendor, nix tooling does that already. So you can close this issue.

However, PeerTube's `yarn.lock` file is really wrong. It has these two sections:

```
http-signature@1.3.4, http-signature@~1.2.0:
  version "1.3.4"
```

Where 1.3.4 clearly does not fulfill the requirement `~1.2.0` (which means `>=1.2.0 <1.3.0`)

```
oauth2-server@3.0.0, oauth2-server@3.1.0-beta.1:
  version "3.1.0-beta.1"
```
Where `3.1.0-beta1` even more obviously does not fulfill the exact requirement `3.0.0`.

In online more, yarn will give a warning and fetch the correct packages. But in offline mode, that's not possible.

I don't know any yarn, I could patch the lock file manually for my own package (and then keep on doing that for every release until I don't have to anymore), but it would be really nice if the lockfile could be fixed in the repo :) 

Should I make a new issue about that and close this one?

**Comment by rigelk** [comment]
> However, PeerTube's `yarn.lock` file is really wrong.

I'm afraid we rely on plain ol' yarn to do generate this file. Fixing the file manually is just not possible ; either this is a bug with yarn or a missing option on our end while using it.

> Should I make a new issue about that and close this one?

No, it's okay, since the issue gives context here. Thanks for caring about that! :)

**Comment by stevenroose** [comment]
So how is the yarn.lock file generated? I keep trying to make changes to packages.json and try `yarn install` but it never updates the lockfile.

**Comment by rigelk** [comment]
@stevenroose 'yarn install' doesn't modify it, only 'yarn add' or 'yarn remove' (like all other modifying subcommands).

**Comment by Chocobozzz** [comment]
Hello,

The yarn file is not wrong: we changed dependencies resolution in https://github.com/Chocobozzz/PeerTube/blob/develop/package.json#L85. We tested these dependencies we need and they work as expected.

**Comment by stevenroose** [comment]
> Hello,
> 
> The yarn file is not wrong: we changed dependencies resolution in https://github.com/Chocobozzz/PeerTube/blob/develop/package.json#L85. We tested these dependencies we need and they work as expected.

@Chocobozzz Hmm, but a dependency that wants a package at v1.2.3 relies on that version, right? If you give it v2.0.0 instead, then PeerTube might break if that dependency updates and starts relying on behavior from the 1.2.3-branch that is changed in 2.0.0..

@Chocobozzz would you be against a PR that applies the changes that `yarn install --strict-semver` does? It seems to tidy things up.

Also, I saw the v3 release candidate. So coming weekend, I'll probably try to package that for NixOS instead of v2.4.0, let's hope it's easier. I also plan to try if using the release zip instead of "building" from sources works better.
