### ISSUE TITLE
<title/> should contain the instance name instead of PeerTube

### ISSUE THREAD

**Issue by conferences-gesticulees** [Chocobozzz/PeerTube#346]
* **PeerTube version or commit: 1.0.0-alpha.8**

* **What is the expected behaviour?**

Page title should be “*Recently added videos - Conférences gesticulées*” because instance name is set to “*Conférences gesticulées*” in “Edit custom configuration”.

* **What do you see instead?**

Page title currently is “*Recently added videos - PeerTube*”.

**Comment by DavidLibeau** [comment]
`<title>` and `<meta name="description">` are wrong.

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/63ac2857aa6550232a1727a395c40e722c32710d
