### ISSUE TITLE
Remote subcsribe direct

### ISSUE THREAD

**Issue by xundeenergie** [Chocobozzz/PeerTube#3460]
**Describe the problem to be solved**

The workflow to subscribe to a channel or a video on a remote instance is a little bit confusing for me. I can subscribe with the subscribe-button to my mastodon-account or an account on the local instance... but not from my own peertube-account. Copying the url to the search-field in my instance and subscribe from there... this is not very handy... 

**Describe the solution you would like:**

A field "Subscribe from local account"
Another field "Subscribe from remote account"
A third field "Subscribe from mastodon-account"

Or subscribe with mastodon-account works also for pleroma-accounts... so rename it to something other like "Subscribe from remote fediverse-account". And then add function to do the same on peertube as on mastodon or pleroma. 

Maybe it can be a goot idea to give a dropdown with "all" fediverse-accounts the user is acutally logged in in this browser (cookies...) and give the possibility for choosing another account like for mastodon-accounts now working.
Is peertube able to handle .well-known/foo/bar links to find the correct informations for peertube-instance itself?

**Comment by tcitworld** [comment]
Duplicate from #2888
