### ISSUE TITLE
Update group membership, roles and from ldap-users

### ISSUE THREAD

**Issue by xundeenergie** [Chocobozzz/PeerTube#3461]
**Describe the current behavior**

I have in my ldap 3 groups for my peertube: peertube_admins, peertube_moderators and peertube_users.
This 3 groups are configured in LDAP-plugin to give the ldap-user the wanted role on my ldap-instance. This works only for new users. When i move an user from "peertube_admins" to "peertube_users" (to downgrade this user), the user stays an administrator after relogin.

Also changing LDAP attribute "mail" for a user is not possible. Changing mail in ldap leads to an error in peertube on login, that a user with this name already exists (user is obviously identified by username AND email-address).

**Describe the expected behavior**
Group-membership on ldap should be updated in peertube as well on next login.
Email-Address from mail in ldap should be updated in peertube on next login.

**Comment by rigelk** [comment]
Hi! Thanks for reporting the issue, but you should open this kind of issue directly where the ldap plugin is developed: https://framagit.org/framasoft/peertube/official-plugins/-/tree/master/peertube-plugin-auth-ldap

**Comment by xundeenergie** [comment]
Ok. Thank you... didn't know that. I will open an issue there.
