### ISSUE TITLE
Please add to UnRaid community apps

### ISSUE THREAD

**Issue by jeryd** [Chocobozzz/PeerTube#3469]
**Describe the problem to be solved**

I can not figure out how to install PeerTube on UnRaid

**Describe the solution you would like:**

Please add PeerTube to the Unraid Community Apps

**Comment by rigelk** [comment]
Hi @jeryd and thanks for your interest in PeerTube,

I suggest you open this request in the UnRaid community forums to look for maintainers of a PeerTube package for UnRaid. We have limited resources and maintaining one officially is not something we can do in the foreseeable future. See https://github.com/Chocobozzz/PeerTube/issues/819#issuecomment-405559764 for a more detailed answer to a similar request for an official snap package.
