### ISSUE TITLE
Restrict domains an embed video can be played on

### ISSUE THREAD

**Issue by Agorise** [Chocobozzz/PeerTube#3470]
Q: i have a public peertube instance at xyz.com (actual url obscured for now). 
at pdq.com (or abc.net, etc) i want to embed videos from my xyz.com peertube instance, but for my "subscribers" only. the pdq.com site has a subscribers login already so that they can login and watch the videos they have paid for, but how do i lock down the url so that only people on specific sites (like pdq.com) can watch the videos streamed from my peertube instance at xyz.com? my v2.4.0 peertube instance (xyz.com) does not seem to have a way to set which "specific" sites can embed/stream specific channels or individual videos... 
. 
the "public", "unlisted", "private", "internal", etc Privacy options are not quite enough... 
![Screenshot from 2020-12-15 09-19-56](https://user-images.githubusercontent.com/31280836/102237857-b6fff900-3eba-11eb-897e-43a440c167f6.png)  
. 
btw, our xyz.com instance does not allow peertube user registration, nor do we use it. we have over 30,000 subscribers already with wordpress user accounts that we sell "subscribers only" videos to. so, securing this embed with peertube credentials is not an option for us. we use our wordpress login on the remote websites. 
. 
i'm thinking there should be a "specific" option on the video update screen as well. 
so, when that option is selected, then a few fields will dynamically appear underneath allowing me to set which sites can embed that video or channel (like website A, B, K, P, etc)...

**Comment by rigelk** [comment]
Hi @Agorise and thanks for your interest in improving PeerTube!

This issue sounds familiar: it is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/3241, which was adressed at the reverse-proxy level. It could be a solution, provided you have access to and can modify the reverse proxy behind which your PeerTube instance is.

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue but it's out of the scope of PeerTube. You can implement this using a plugin or directly in your reverse proxy.

**Comment by candidexmedia** [comment]
Restricting embeds to chosen domains is now available since [version 8.1](https://joinpeertube.org/news/release-8.1), on a per video basis. 🥳

<img width="1080" height="1358" alt="Image" src="https://github.com/user-attachments/assets/620ea5b9-08a5-45d4-b868-778f14aff6b7" />

I just wish it could be applied on a per channel and per account basis as well.
