### ISSUE TITLE
Don't warn about maximum duration of a live if it's disabled

### ISSUE THREAD

**Issue by tcitworld** [Chocobozzz/PeerTube#3472]
**Describe the current behavior**

The following banner shows up when creating a live
![image](https://user-images.githubusercontent.com/2197836/102328306-2fcc8700-3f87-11eb-8ab4-60032b49d2d7.png)

**Steps to reproduce:**

1. Have `live.max_duration: -1` into PT's configuration
2. Create a new live

**Describe the expected behavior** The banner shouldn't show up if the live has no maximum duration

* PeerTube instance:
  * version: 3.0.0-rc.1
  * NodeJS version: 12.20
  * Ffmpeg version: 4.1.6

**Comment by Chocobozzz** [comment]
Thanks, fixed by https://github.com/Chocobozzz/PeerTube/commit/ddca2576997e2769d8cc37bbfe3098591add13dd
