### ISSUE TITLE
follows page on peertube2 shows 2 errors

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3473]
**Describe the current behavior**
https://peertube2.cpy.re/about/follows
![Screenshot_20201216_175304](https://user-images.githubusercontent.com/39449563/102348337-c882f700-3fc7-11eb-860b-aac15419fbea.png)

open the url. it shows two errors, presumably for each of follows and followed. 
**Steps to reproduce:**

1.open url
2.
3.

**Describe the expected behavior**
no error should show
**Additional information**

* PeerTube instance:
  * URL:https://peertube2.cpy.re/about/follows
  * version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/c5ac9fe7c164741b2497282eac9b968f222fa151
