### ISSUE TITLE
I can't start more than one live stream on 3.0.0-rc1 in docker

### ISSUE THREAD

**Issue by piotr-sikora-v** [Chocobozzz/PeerTube#3474]
Live stream starting
I see one ffmpeg is up on 127.0.0.1:1935
but when I try to start second, no one ffmpeg starting :/

**Comment by Chocobozzz** [comment]
Hello,

Please fill the template for bug reports so we can help

**Comment by piotr-sikora-v** [comment]
I don't why... just start working :P
