### ISSUE TITLE
Stream detected, but no live shown

### ISSUE THREAD

**Issue by Desmu** [Chocobozzz/PeerTube#3475]
Hello, thanks for the livestreaming option (and the rest) ! But I've tried to test this feature on my own instance with the default settings, OBS transfers my live correctly, but the video player on PeerTube doesn't start, on Firefox and Chrome.

I've kept the video replay for one of my tests, ~~thumbnail has been generated on my server, but not the corresponding video~~. https://peertube.desmu.fr/videos/watch/68718750-ed6d-4ccb-a21d-e4d1002d02f7

* PeerTube instance:
  * URL: https://peertube.desmu.fr
  * Version: 3.0.0-rc.1
  * NodeJS version: 12.18.3
  * Ffmpeg version: 4.3-2
  * Server : Nginx 1.14.0

Update to version 3.0 has been done through the autoupdate script, PeerTube Nginx configuration is the same one that the one in this file https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube (I've just replaced `${PEERTUBE_HOST}` with `127.0.0.1:9000` and `${WEBSERVER_HOST}` with `peertube.desmu.fr`), and I've installed `libnginx-mod-rtmp`.

Audit log :
`{"level":"audit","message":"{\"user\":\"desmu\",\"domain\":\"videos\",\"action\":\"update\",\"video-tags\":[],\"video-uuid\":\"68718750-ed6d-4ccb-a21d-e4d1002d02f7\",\"video-id\":383,\"video-createdAt\":\"2020-12-16T14:05:02.179Z\",\"video-updatedAt\":\"2020-12-16T14:05:02.179Z\",\"video-publishedAt\":\"2020-12-16T14:05:00.395Z\",\"video-description\":null,\"video-duration\":0,\"video-isLocal\":true,\"video-name\":\"Live\",\"video-thumbnailPath\":\"/static/thumbnails/68718750-ed6d-4ccb-a21d-e4d1002d02f7.jpg\",\"video-previewPath\":\"/lazy-static/previews/68718750-ed6d-4ccb-a21d-e4d1002d02f7.jpg\",\"video-nsfw\":false,\"video-waitTranscoding\":true,\"video-account-id\":2,\"video-account-name\":\"desmu\",\"video-channel-id\":2,\"video-channel-name\":\"chez_desmu\",\"video-support\":null,\"video-commentsEnabled\":true,\"video-downloadEnabled\":true,\"new-video-updatedAt\":\"2020-12-16T14:05:20.636Z\",\"new-video-publishedAt\":\"2020-12-16T14:05:20.636Z\"}","timestamp":"2020-12-16T14:05:20.680Z","label":"peertube.desmu.fr:443"}`

Log (without messages from other instances) :
`{"level":"info","message":"Video live Live with uuid 68718750-ed6d-4ccb-a21d-e4d1002d02f7 created.","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:05:02.255Z"}
{"message":"92.148.0.0 - - [16/Dec/2020:14:05:02 +0000] \"POST /api/v1/videos/live/ HTTP/1.0\" 200 66 \"https://peertube.desmu.fr/\" \"Firefox\"\n","level":"info","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:05:02.268Z"}
{"message":"92.148.0.0 - - [16/Dec/2020:14:05:02 +0000] \"GET /api/v1/videos/live/383 HTTP/1.0\" 200 140 \"https://peertube.desmu.fr/\" \"Firefox\"\n","level":"info","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:05:02.491Z"}
{"message":"92.148.0.0 - - [16/Dec/2020:14:05:20 +0000] \"PUT /api/v1/videos/live/383 HTTP/1.0\" 204 - \"https://peertube.desmu.fr/\" \"Firefox\"\n","level":"info","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:05:20.635Z"}
{"level":"info","message":"Creating job to send video creation of https://peertube.desmu.fr/videos/watch/68718750-ed6d-4ccb-a21d-e4d1002d02f7.","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:05:20.647Z"}
{"level":"info","message":"Creating job to send announce https://peertube.desmu.fr/videos/watch/68718750-ed6d-4ccb-a21d-e4d1002d02f7/announces/4.","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:05:20.672Z"}
{"level":"info","message":"Creating job to send announce https://peertube.desmu.fr/videos/watch/68718750-ed6d-4ccb-a21d-e4d1002d02f7/announces/1.","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:05:20.674Z"}
{"level":"info","message":"Video with name Live and uuid 68718750-ed6d-4ccb-a21d-e4d1002d02f7 updated.","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:05:20.681Z"}
{"message":"92.148.0.0 - - [16/Dec/2020:14:05:20 +0000] \"PUT /api/v1/videos/383 HTTP/1.0\" 204 - \"https://peertube.desmu.fr/\" \"Firefox\"\n","level":"info","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:05:20.687Z"}
{"level":"info","message":"Processing ActivityPub broadcast in job 1591.","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:05:20.688Z"}
{"level":"info","message":"Updating 2 good actor follows and 0 bad actor follows scores in cache.","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:05:20.772Z"}
{"level":"info","message":"Processing ActivityPub broadcast in job 1592.","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:05:20.777Z"}
[...]
{"level":"info","message":"Updating 63 good actor follows and 6 bad actor follows scores in cache.","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:05:24.910Z"}
{"level":"info","message":"Processing ActivityPub broadcast in job 1593.","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:05:24.913Z"}
[...]
{"level":"info","message":"Will mux/transcode live video of original resolution 720.","label":"peertube.desmu.fr:443","allResolutions":[480,720],"timestamp":"2020-12-16T14:05:54.686Z"}
{"level":"info","message":"Running live muxing/transcoding for 68718750-ed6d-4ccb-a21d-e4d1002d02f7.","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:05:55.449Z"}
{"level":"info","message":"Creating job to update video https://peertube.desmu.fr/videos/watch/68718750-ed6d-4ccb-a21d-e4d1002d02f7.","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:06:14.734Z"}
{"level":"info","message":"Processing ActivityPub broadcast in job 1594.","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:06:14.754Z"}
[...]
{"sessionId":"D1KKNSQ9","level":"info","message":"Live session ended.","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:06:56.032Z"}
{"level":"info","message":"RTMP transmuxing for video rtmp://127.0.0.1:1935/live/9842b06c-d5a0-48bb-9825-4380439dbf7d ended. Scheduling cleanup","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:06:56.545Z"}
{"level":"info","message":"Creating job to update video https://peertube.desmu.fr/videos/watch/68718750-ed6d-4ccb-a21d-e4d1002d02f7.","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:06:57.661Z"}
{"level":"info","message":"Processing ActivityPub broadcast in job 1595.","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:06:57.694Z"}
{"level":"info","message":"Updating 63 good actor follows and 6 bad actor follows scores in cache.","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:07:01.133Z"}
{"message":"Updating live video views.","level":"info","label":"peertube.desmu.fr:443","timestamp":"2020-12-16T14:07:20.059Z"}`

I've also made a capture of the browser log during the live (I've disabled autoplay on Firefox, that's why I have to click on the Play button, but Chrome doesn't show the live either, the two are stuck on a black screen and the PeerTube player doesn't show up) :

![live-peertube-test](https://user-images.githubusercontent.com/70474955/102361699-cfa00a00-3fb3-11eb-8c72-b625bfee27bf.png)

(Some of the first problems also appear on normal videos, but maybe some CSP problems detected after the live launch are the cause ? I didn't find the CSP definitions in the PeerTube Nginx configuration.)

**Comment by Chocobozzz** [comment]
Hello,

You don't need `libnginx-mod-rtmp`.

Regarding your issue, did you enable live transcoding?

**Comment by Desmu** [comment]
Thanks for your answer ! I've removed `libnginx-mod-rtmp` and live transcoding was enabled through the GUI, but not through the `/var/www/peertube/config/production.yaml`. I've changed the settings and restarted Nginx but unfortunately, I've got the same problem.

![transcoding1](https://user-images.githubusercontent.com/70474955/102373714-ca958780-3fc0-11eb-966d-f2274c09fe51.png)
![transcoding2](https://user-images.githubusercontent.com/70474955/102373716-cb2e1e00-3fc0-11eb-873a-4b2196d7ec8d.png)
![transcoding3](https://user-images.githubusercontent.com/70474955/102373717-cb2e1e00-3fc0-11eb-8f10-efad3f3b42b8.png)

**Comment by test2a** [comment]
Hey. What is the latency like.

**Comment by test2a** [comment]
on firefox, there seems to be no video player and the image is all dark.
while on tubelab android app, the video at least shows if only for a minute.
![Screenshot_20201216_214058](https://user-images.githubusercontent.com/39449563/102374507-6f2ac000-3fe7-11eb-97c0-374cb274af33.png)

**Comment by test2a** [comment]
same in fullscreen. there is no video output

**Comment by test2a** [comment]
@Desmu can you check if you have contact administrator enabled? https://peertube.desmu.fr/about/instance this instance page does not show the contact administrator button like old versions. maybe this is a bug because i could not find that in gitpod also

**Comment by Desmu** [comment]
Thanks for your answers ! I've not measured latency with precision but there is less than 30 seconds between the live launch in OBS and the page reaction in PeerTube.
The video from the live lasts normally 63 seconds so it's normal.
Contact form is enabled in the `production.yaml` file and in the GUI.

And I've just made tests through Tubelab too and yes, both live streaming and replays work great ! (so I've noticed that live replays aren't in the same folder that the normal videos, forget my mention of the video not being created)

**Comment by test2a** [comment]
![Screenshot_20201216_220605](https://user-images.githubusercontent.com/39449563/102377690-f6c5fe00-3fea-11eb-872a-34727db13c7c.png)


this page near the mouse should show a big button of contact administrator. it is not on yours.

**Comment by test2a** [comment]
can you open a page https://time.is/ this one on screen and point obs. that would be easy to check on other side about latency

**Comment by test2a** [comment]
the time shown on video and in a separate browser window is just latency

**Comment by Desmu** [comment]
Best latency I can get is between 9 and 10 seconds, but it's more like 13 seconds in average.

**Comment by Desmu** [comment]
Best latency I can get is between 9 and 10 seconds, but it's more like 13 seconds in average.

Couldn't the problem come from the CSP like the error messages shown in the first post (the one with the video blob in particular) ?

**Comment by test2a** [comment]
I tried with peertube.dk but I am unable to start a live. Sigh. OBS seems to disconnect every 10 seconds.

**Comment by test2a** [comment]
@Desmu did you change something? your live has started to play on my firefox web. you should check too

**Comment by Desmu** [comment]
Okay, so it's really a CSP problem, with another set of rules, I can see my live streaming on the web client (but the latency is still around ~25s while in Tubelab it's more like ~10s).

Since there's no default CSP rules in the PeerTube Nginx configuration file, I've hardcoded this ones under the `server` block. Is it safe to keep them here or should I put them in another file ?

`add_header Content-Security-Policy "default-src 'none'; connect-src 'self'; font-src 'self' data:; img-src 'self' data:; script-src 'self' 'unsafe-inline' blob:; style-src 'self' 'unsafe-inline';";`

**Comment by test2a** [comment]
@Desmu i am not the guy to ask that. i have zero knowledge about that. @Chocobozzz should be able to help in that.

about the livestream, why does the video end after the minute mark? if you have a small video, can you just loop it on the back end because i have to click on the player to restart the video  once it is over

**Comment by test2a** [comment]
also, @Desmu how can you check the latency with this live? i just see the same video on loop and it looks like a regular video to me. am i missing something?
https://peertube.desmu.fr/videos/watch/68718750-ed6d-4ccb-a21d-e4d1002d02f7

**Comment by Desmu** [comment]
The video in the first post ? It was a replay from one of my tries. I didn't use the permanent live feature for the tests, to be able to keep replays and see if they worked. I've created a new live for each test, and stopped it when I saw that it didn't work, so the link changed every time. I've done the last tests with the time.is window opened (and thanks for the link !).

**Comment by test2a** [comment]
@Desmu hi. can you check if your live videos have a live badge? i had seen that earlier but in the rc1 it is nowhere to be found
https://peertube3.cpy.re/videos/local
this lists https://peertube3.cpy.re/videos/watch/fb1bc38d-b2d9-4a34-b639-81d644007e55
which says time 0:00 but not the live badge
@Chocobozzz is this a bug?
![Screenshot_20201217_125005](https://user-images.githubusercontent.com/39449563/102455944-76dd7980-4066-11eb-98ae-d0792f4a4759.png)

**Comment by Chocobozzz** [comment]
Then it was a custom CSP issue.

We inject latency in PeerTube for better P2P. Tubelab doesn't do p2p with live streams, so it doesn't need this latency.
