### ISSUE TITLE
Cannot remove redundancy

### ISSUE THREAD

**Issue by c0xc** [Chocobozzz/PeerTube#3476]
**Describe the current behavior**

This is about a mirror instance which is following another instance "origin" in order to mirror its videos and reduce the load on the origin instance. When unchecking "allow redundancy" for the origin instance under "instances you follow", the following error showed up in the logs in the mirror instance:

```
Cannot remove redundancy of <origin>. {
  "err": {
    "stack": "TypeError: Cannot read property 'Video' of null\n    at VideoRedundancyModel.getVideo (/var/www/peertube/versions/peertube-v2.4.0/dist/server/models/redundancy/video-redundancy.js:479:44)\n    at Object.<anonymous> (/var/www
/peertube/versions/peertube-v2.4.0/dist/server/lib/activitypub/send/send-undo.js:60:41)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v2.4.0/node_modules/tslib/tslib.js:114:75\n    at new Promise (<anony
mous>)\n    at Object.__awaiter (/var/www/peertube/versions/peertube-v2.4.0/node_modules/tslib/tslib.js:110:16)\n    at Object.sendUndoCacheFile (/var/www/peertube/versions/peertube-v2.4.0/dist/server/lib/activitypub/send/send-undo.js:58:
20)\n    at /var/www/peertube/versions/peertube-v2.4.0/dist/server/lib/redundancy.js:15:26\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v2.4.0/node_modules/tslib/tslib.js:111:62)",
    "message": "Cannot read property 'Video' of null"
  }
}

```

Is it possible to clear and recreate the redundancy cache without unfollowing and re-following the origin instance? Some mirrored videos of origin, which were listed under "video redundancies" the whole time, aren't even seeded to the browser, even after selecting "allow redundancy" again (judging by the number of peers and network traffic in the browser console).

**Steps to reproduce:**

1. Have a mirror instance which follows some "origin" instance, "redundancy allowed" checked.
2. Remove checkmark "redundancy allowed" to trigger the error.

Also, it seems like videos of a different origin2 instance (redundancy allowed already unchecked) are still being kept in the redundancy cache of this mirror instance, possibly taking up space that should be used for mirrored videos of origin. Those origin2 files are still in `redundancy/` (and `redundancy/hls/` though hls is disabled) and still listed under Federation - Video redundancies. Shouldn't these be deleted automatically after disabling "redundancy allowed"?

**Describe the expected behavior**

I would have expected all remote videos to be mirrored until the cache is full (for instances with redundancy allowed), for example all trending videos that fit in the cache (if configured). Now, the cache isn't completely full and this error seems to indicate that some videos of the origin instance that would fit in the cache are not mirrored because there are unwanted copies of that other origin2 instance. I wonder if there's a misunderstanding on my part (the idea is to follow several instances but only mirror "origin").

* PeerTube instance:
  * version: 2.4.0
  * NodeJS version: v10.21.0
  * Ffmpeg version: 4.3.1

* Browser name, version and platforms on which you could reproduce the bug: Firefox 74.0.1 on Fedora 31

**Comment by Chocobozzz** [comment]
It's weird, this video does not seem to have files associated. Anyway, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/9cfeb3cf989fffccdfe3e575903dc00baab255b2

In v3 stable you'll be able to remove these redundancies using the same action.
