### ISSUE TITLE
share window on video player pauses playback. closing window does not autostart playback

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3478]
**Describe the current behavior**
open url
https://peertube3.cpy.re/videos/watch/9c9de5e8-0a1e-484a-b099-e80766180a6d

click on share button.
share window opens.
video has paused.
close window
video stays paused.

**Steps to reproduce:**

1.
2.
3.

**Describe the expected behavior**

on closing the share window, the video should start the video playback. 

this is just like https://github.com/Chocobozzz/PeerTube/issues/2995 which was fixed. 

this can be confirmed from https://peertube.desmu.fr/videos/watch/a3ae4635-285d-4a4c-b43d-06b0a5c6936d
where the playback restarts automatically after closing support window but not after closing share window
**Additional information**

* PeerTube instance:
  * URL:
  * version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by rigelk** [comment]
The issue was reported before a recent change in the modal behaviour wrt the video player pausing, discussed in https://github.com/Chocobozzz/PeerTube/issues/3816. Since then the issue doesn't apply anymore.
