### ISSUE TITLE
Publishing permanent live when starting again

### ISSUE THREAD

**Issue by PhieF** [Chocobozzz/PeerTube#3480]
Hi !

First, thanks for the wonderful work on live

it would be great when a permanent live starts again to publish it, or republish a message to follower telling them that the live has started again, for example on mastodon we should receive a toot when the live restarts !

Permanent lives are very useful to avoid having to change streaming key each time we stream, that's why I'm using it instead of non permanent lives

thanks again !

**Comment by Chocobozzz** [comment]
>  for example on mastodon we should receive a toot when the live restarts 

We can't do that since mastodon does not handle `Update` of `Video` activities. But I think we can send a notification to peertube users.

**Comment by PhieF** [comment]
Perhaps tricking it with a boost ?

**Comment by Chocobozzz** [comment]
PeerTube instance and channel already boosted this `Video`, so we should `Undo` and resend the `Boost` which does not seem appropriate.

**Comment by PhieF** [comment]
OK it would require a reboost, then, I see

thanks

**Comment by saumyakswain** [comment]
Sending updates to peertube users would be really helpful when the permanent live is unscheduled. I'm streaming only the important parts of events and letting users know that the streaming has resumed would be really useful for my case.

**Comment by Booteille** [comment]
Would it be possible to create a new type of object would be handled by Mastodon dedicated to notifying users when a stream goes live?

The message would be something like "User went live on [URL]!".

**Comment by Chocobozzz** [comment]
Hi,

Since v4 we now send updates to peertube subscribers by automatically republishing the video.
Regarding Mastodon, it's up to them to decide to handle `Update` of live videos or not :)
