### ISSUE TITLE
Accessibility issues as reported by Axe

### ISSUE THREAD

**Issue by vijay-howlround** [Chocobozzz/PeerTube#3483]
There are several accessibility issues with the user interfaces. All of the issues seems like they would be easy to fix for the first release. It would be great to launch with a fully accessible interface (at least in the coding). 

In order to get detailed descriptions of the accessibility, I used this tool:
https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US

It describes the issues and shows you how to fix them.

**Comment by rigelk** [comment]
Hi @vijay-howlround, could you report the issues (even in broad terms) here rather than just redirect us to a tool?

**Comment by vijay-howlround** [comment]
Yes, of course. Summarizing some of the issues below: 

On the landing page: https://peertube.stream/

Here are some critical issues:
- Buttons must have discernible text
- ARIA commands must have an accessible name
- Document must have one main landmark
- id attribute value must be unique
- Elements must have sufficient color contrast

And then on an administrative page such as this one: https://peertube.stream/my-account/settings

Here are some critical issues:
- Certain ARIA roles must contain particular children
- IDs used in ARIA and labels must be unique
- Form elements must have labels
- ARIA commands must have an accessible name
- ARIA input fields must have an accessible name
- ARIA progressbar nodes must have an accessible name
- Certain ARIA roles must contain particular children
- ARIA toggle fields have an accessible name

**Comment by Chocobozzz** [comment]
Thanks, it's a very nice tool. I fixed some issues in https://github.com/Chocobozzz/PeerTube/commit/1916c9663ac632227e60ebc93cec616b2dd6800d

There additional critical issues because of some of our dependencies. I subscribed to the related issues.
