### ISSUE TITLE
HTTP 499 error during upload, and possible fix

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#3484]
**Describe the current behavior**

A user was reporting upload errors. The first problem here is that the client gives basically no useful debug information, but with the user's help I traced it to a particular server-side log on nginx, showing an HTTP 499 code for the POST to the actual upload endpoint.

**Steps to reproduce:**

I don't have specific steps yet, it seems to occur only under some network configurations. The same evening this user was reporting trouble, I had been uploading successfully from elsewhere.

**Describe the expected behavior**

The first necessary improvement would seem to be better error reporting when an upload fails. But of course uploads should also not fail without good reason.

**Additional information**

While looking for possible causes of the HTTP 499, I hit on this post with a possible solution that seemed like it might apply to this use case: https://stackoverflow.com/a/52987394

I tried setting `proxy_ignore_client_abort on` and asked the user to retry, and this time it worked. It's just one data point, not a definitive explanation, but it seemed worth reporting. I suspected timeouts as well, but my timeout and max body size limits are all quite large, as the instance is configured for large video files.

```
location / {
    proxy_pass http://127.0.0.1:9000;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # Hard limit on uploads
    client_max_body_size 200G;
    proxy_connect_timeout       100m;
    proxy_send_timeout          100m;
    proxy_read_timeout          100m;
    send_timeout                100m;
    proxy_ignore_client_abort on;
  }
```

* PeerTube instance:
  * URL: https://diode.zone
  * version: 2.4.0
  * NodeJS version: 10.23.0
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by rigelk** [comment]
@scanlime there should be better error reporting for uploads starting with the 3.0.0-rc1 release. note that we also updated the nginx template to prevent other problems, like the very large `client_max_body_size` you are setting for all routes of the API when only two need it.

**Comment by scanlime** [comment]
I noticed those updates, but I wasn't sure why it would be an improvement.
It wouldn't help prevent DoS since the upload route is still accessible at
the nginx level without a login, if I understand.

Anyway I'll try out the newer upload client too, thanks.
