### ISSUE TITLE
Previous button in playlist watch page

### ISSUE THREAD

**Issue by King-Noctis** [Chocobozzz/PeerTube#3485]
Can you add a **Previous** button when playing video in playlists?
Thanks.

![Screenshot 2020-12-18 180032](https://user-images.githubusercontent.com/76251188/102689456-43067d80-4239-11eb-900a-3696456c2e0e.jpg)

**Comment by Poslovitch** [comment]
I'm working on this.
I've got a working solution, but there's code duplication I would like to avoid.

**Comment by Chocobozzz** [comment]
@Poslovitch Our [next button](https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/assets/player/videojs-components/next-previous-video-button.ts) already supports "previous", so adding `previousVideo` below https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/%2Bvideos/%2Bvideo-watch/video-watch.component.ts#L801 should work

**Comment by Poslovitch** [comment]
Sure, that's what I figured out. 😉 

I have not found a way to get rid of code duplication yet. I'll open the PR as a draft, so that you can review it.
