### ISSUE TITLE
Make instances feel diffrent

### ISSUE THREAD

**Issue by Openmedianetwork** [Chocobozzz/PeerTube#3488]
Using simple view counts over time across an instance will bring the same content to the top on every instance - we already have a VERY bad spam problem due to the backend tools. Let's come up with creative ideas for mediating this.

Issue: currently local content loses out to popular external content in the most liked and trending.

Solution: add a UI or plugin admin tick option to give this a say 50% boost in likes/views when calculating display order so that it more easily pushes up into the federated popular content on a local instance

Outcome: this will add local "flaver" to instances they often lack, due to being swamped by generic content from across the network.

Have this as a UI option or plugin.

**Comment by test2a** [comment]
What you are describing is what Reddit mods used to do. I used to read how they could rebalance or whatever. Dunno what tangible affect will they  have because you are intentionally gaming users into interaction

**Comment by test2a** [comment]
https://www.theverge.com/2016/12/6/13862042/reddit-upvote-downvote-scoring-system-recalculation


Read up on this.

**Comment by Chocobozzz** [comment]
Hello,

> we already have a VERY bad spam problem due to the backend tools

Could you elaborate? I'm not sure to understand what it means.

**Comment by Openmedianetwork** [comment]
As lots of people talk about peertube instances have very bad spam problems in video content flows.
The implementation has suffered from the #geekproblem in that they have a #closed mod workflow rather than a #open trust based workflow. This is a normal issue and a clear #block  on the rollout of #openweb projects.

**Comment by Openmedianetwork** [comment]
> 
> 
> https://www.theverge.com/2016/12/6/13862042/reddit-upvote-downvote-scoring-system-recalculation
> 
> Read up on this.

What am suggesting is different to this, not adjusting the votes or view counts, `simply` Appling a mod option to make local content show up with popular external content to make different instances feel individual rather than them all looking the same, with the same content displayed in popular and liked views - if you are worried about the wording then change it to "on this instance" if the mod is applied. have this as a UI or a plugin option.

**Comment by test2a** [comment]
There is a tab called "local" that only shows local content. Wouldnt that solve your issue?

**Comment by Openmedianetwork** [comment]
yep... am looking at trending and liked as when I do a promo/outreach post I trend to put out trending as it give a interesting dynamic view of the instance - the problem as I outline above is that the local content is pushed off the bottom by the more "general" popular content across the networks so my instance instead of having its own personality is just like every other instance - it's a clear failing, looking for ideas to mediate this to add value to subject based instances like http://visionon.tv

More ideas?

**Comment by geopayme** [comment]
> As lots of people talk about peertube instances have very bad spam problems in video content flows.
> The implementation has suffered from the #geekproblem in that they have a #closed mod workflow rather than a #open trust based workflow. This is a normal issue and a clear #block on the rollout of #openweb projects.
> 
> http://hamishcampbell.com/index.php/2020/12/25/human-tech-omn/

the issue is that instance administrators do not take the time to manage their instances! I run 8 PeerTube instances and to this point there is 0% spam, because I clear out all the bad actors. SO rather then see someone create restrictions its better to have a better education no how to manage a peertube instance.

**Comment by Openmedianetwork** [comment]
@geopayme which ones do you run :)

These two views are not incompatible - I recently talked at two conferences, #APCONF and #RC3 and the SPAM problem was brought up at each talk/workshop as questions about #peertube

**Comment by geopayme** [comment]
This is the NonProfit Site [FightBig.Tech](https://fightbig.tech)

[The Duran](https://theduran.icu)
[Katie Hopkins](https://katiehopkinspolitical.icu)
[Censorship ICU](https://censorship.icu)
[Political ICU](https://political.icu)
[AntiVaxxer ICU](https://antivaxxer.icu)
[Voice News ICU](https://voicenews.icu)
[Our Christian Faith](https://ourchristian.faith)

**Mastodon**

[Tweety.icu](https://tweety.icu)

**Mobilizon**

[Voter Integrity](https://voterintegrity.today) - this platform had some limitation as it is still fairly new

We are on schedule for 10 more in the next  5 months... we are working to resolve some issues as it related to the federated part and the sharing on the files.. there is no actual way to track how much storage is used if media is mirrored so the storage is not accurately predicted in a nascent way to the admin

**Comment by geopayme** [comment]
> @geopayme which ones do you run :)
> 
> These two views are not incompatible - I recently talked at two conferences, #APCONF and #RC3 and the SPAM problem was brought up at each talk/workshop as questions about #peertube

Like I mentioned.. if you organize your material and federated instances (select and review what the instance promotes) then you can have information closer to your instance content and #hashtags!

**Comment by Chocobozzz** [comment]
Hello,

You can create a plugin to experiment your idea. But it's not something we would like to implement in core peertube for now.

**Comment by Openmedianetwork** [comment]
@geopayme which ones do you run :)

These two views are not incompatible - I recently talked at two conferences, #APCONF and #RC3 and the SPAM problem was brought up at each talk/workshop as questions about #peertube 

> 
> 
> Hello,
> 
> You can create a plugin to experiment your idea. But it's not something we would like to implement in core peertube for now.

will see if I can find somebody to do a plugin... at the moment any instance that covered grassroots radical media will look and feel the same with very simuler trending/liked videos - this reduces the value of the network.
