### ISSUE TITLE
Move a video to a different channel

### ISSUE THREAD

**Issue by conferences-gesticulees** [Chocobozzz/PeerTube#349]
* **PeerTube version or commit: 1.0.0-alpha.8**

* **What is the expected behaviour?**

A user might upload videos on the behalf of another user (e.g. because they have access to better bandwidth or run the YouTube import script directly on the server). Administrators or moderators should then be able to move a video to a different channel than their own.

* **What do you see instead?**

In the “*Edit a video*” screen, the *Channel* option is locked.

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/0f320037e689b2778959c12ddd4ce790f6e4ae4f
