### ISSUE TITLE
Clearer setting modal scope

### ISSUE THREAD

**Issue by sidboy55555** [Chocobozzz/PeerTube#3490]
**Describe the current behavior**
By default, sensitive content shoud be shown, but when you visit the webpage (not logged in), it doesn't, while at the settings, Sensitive content is shown. If I changed it to blurred, and back, the thumpnails and names are visible.

**Steps to reproduce:**

1.Having a video uploaded and nsfw status
2.Set default policy on videos containing sensitive content on display
3.Go to the webpage in without being signed in, or in incognito tab

**Describe the expected behavior**
See all thumpnails and video names when visiting the page

**Additional information**
![SharedScreenshot](https://user-images.githubusercontent.com/9865110/102702775-be325880-4266-11eb-9d24-e10a934aad59.jpg)

This seems also to be for the default theme

* PeerTube instance:
  * URL: 
  * version: 2.4
  * NodeJS version: v12.20
  * Ffmpeg version: 4.1.6

* Browser name, version and platforms on which you could reproduce the bug: Edge (chromiun version), 87.0.664.66, windows 10
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
*

**Comment by sidboy55555** [comment]
Issue has resolved itself strange enough...

**Comment by Chocobozzz** [comment]
Hello,

This settings modal act only for your session, not the entire instance. If you want to update the instance NSFW setting, you need to login in with an admin account and go in the administration.

I think we can be clearer in this setting modal, explaining its scope.

**Comment by sidboy55555** [comment]
Hello,

I've this settings on "display" in the administrator settings, and the settings in local settings is also on "display", but like I explained, even if everything is on "display" they are blurred out.

**Comment by Chocobozzz** [comment]
What is your instance URL?

**Comment by sidboy55555** [comment]
I've already removed the sensitive content options from all my videos so they are visible, but I'll make a second instance on another vps for testing purposes, I'll send the link when it's done

**Comment by Chocobozzz** [comment]
Up :)

**Comment by sidboy55555** [comment]
Sorry I haven't had anytime to build a instance for this topic, I'll be able to do it next month.

**Comment by own3mall** [comment]
I'm having the same problem.  I have the option set to "Display" but video thumbnails and their titles are still blurred in PeerTube 3.1.0
