### ISSUE TITLE
Make PeerTube compatible with mpv

### ISSUE THREAD

**Issue by alex-tee** [Chocobozzz/PeerTube#3491]
**Describe the problem to be solved**

`mpv https://diode.zone/videos/watch/583e7862-f2fe-4d13-9fac-40a93677202a` does not work for example. Mpv works with almost every major video site like facebook, twitter, youtube, and other video sites.

I can't watch videos because my system uses JACK exclusively and my browser does not support JACK, so my workflow is to copy the URL of a video i want to watch and watch it through mpv. i also don't like using the browser when i can use mpv.

**Describe the solution you would like:**

Make peertube compatible with mpv

**Describe alternatives you have considered**

**Comment by rigelk** [comment]
Hi @alex-tee,

What makes you think the problem stems from PeerTube and not mpv?

**Comment by alex-tee** [comment]
this is a youtube-dl issue so closing https://github.com/ytdl-org/youtube-dl/issues/26002

thanks
