### ISSUE TITLE
support modal text goes beyond the window

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3492]
**Describe the current behavior**
check the screenshot. the line of monero address should not go outside the box,
**Steps to reproduce:**

1. open url. 
2. click on support
3.
![Screenshot_20201220_152954](https://user-images.githubusercontent.com/39449563/102710541-038f6e00-42d9-11eb-9209-adc8b31e2b8e.png)

**Describe the expected behavior**
long text should wrap itself inside the box
**Additional information**
i tested this in a 3.0 rc1 instance and same thing
* PeerTube instance:
  * URL: https://videos.lukesmith.xyz/videos/watch/e0f5a4d7-070d-4a03-aca4-3d898b5c5002
  * version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by 4rtmelly** [comment]
Hi ! I'm a CS student and I think it would be interesting if I (and my mate) could work on this issue ! :)

**Comment by test2a** [comment]
@4rtmelly go for it
