### ISSUE TITLE
Reduce/Increase latency mode for live as an option to streamers/admins

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3494]
**Describe the problem to be solved**
congratulations on the livestreaming. this is probably the most requested feature and is finally upon us. 
Now, from my initial tests on the RC 1 and from reading framacolibri blog, i understand that there is a latency introduced by software to assist in p2p because how else can you send or receive data from server and peers if you watching the systemtime. 
This essentially means 30-50 seconds of latency from the streamer to the user including the p2p penalty.
What i am suggesting is, for instances which have the necessary bandwidth, allow those admins to enable a low latency mode.

what a low latency mode would do is remove the p2p penalty essentially trying to get data as fast as possible. this would harm the p2p nature but if this feature can be first enabled by the admins, then the user could decide to go for low latency mode.
the regular viewers would get to watch in normal mode as currently exists but if previously enabled, a user wanting more interaction could do this.

twitch, youtube have this. now, their low latency mode is somewhat different because it doesn't keep much buffer and the user is put nearest to systemtime but in our case it could solve issues

again, a new instance with limited resources wouldnt enable this, wanting to leverage power of p2p but for power users, this would be a good option

**Describe the solution you would like:**

**Describe alternatives you have considered**

**Comment by Chocobozzz** [comment]
Hello and thanks :)

What I would implement this:
 * Add a setting in the admin to allow uploaders to select the latency/p2p mode
 * Add this setting in the go live form. It would be a select with 3 options:
   * Low latency/low p2p (no latency introduced by our player, segments of 2 seconds)
   * Default (current setting)
   * High latency/high p2p (to be defined)

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/4846
