### ISSUE TITLE
Missing config variables should cause error on startup

### ISSUE THREAD

**Issue by stevenroose** [Chocobozzz/PeerTube#3497]
Trying to import a video logs this error:

> "Configuration property \"import.videos.http.proxy.enabled\" is not defined"

Does an operator really need to literally try out every feature before being assured that he has all the required config variables in his config file?

## Template:

**Steps to reproduce:**

1. Fill in the config file example template and remove the `import.videos.http.proxy` section
2. Run PeerTube with that config file.
3. Open the import video function.

**Describe the expected behavior**
No HTTP proxy is used for video importing.

**Describe the current behavior**
An error is produced and the video import function doesn't work.

**Additional information**

* PeerTube instance:
  * URL:
  * version: 3.0.0-rc.1
  * NodeJS version: 0.12.x (can check more specifically later if desired)
  * Ffmpeg version: n/a

* Browser name, version and platforms on which you could reproduce the bug: n/a
* Link to browser console log if relevant: n/a
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

excerpt: 
```
er/controllers/api/videos/import.js:104:48\n    at Generator.next (<anonymous>)\n    at /nix/store/r06jya5sr1qjskyxrc80i2z91brmcw3v-peertube-server-3.0.0-rc.1/node_modules/tslib/tslib.js:114:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/nix/store/r06jya5sr1qjskyxrc80i2z91brmcw3v-peertube-server-3.0.0-rc.1/node_modules/tslib/tslib.js:110:16)\n    at addYoutubeDLImport (/nix/store/drps2f2a6vmm4k1hvpvlk48pq6a9lz3r-peertube-3.0.0-rc.1/dist/server/controllers/api/videos/import.js:98:20)\n    at addVideoImport (/nix/store/drps2f2a6vmm4k1hvpvlk48pq6a9lz3r-peertube-3.0.0-rc.1/dist/server/controllers/api/videos/import.js:42:16)\n    at /nix/store/drps2f2a6vmm4k1hvpvlk48pq6a9lz3r-peertube-3.0.0-rc.1/dist/server/helpers/database-utils.js:8:25\n    at retryAttempt (/nix/store/r06jya5sr1qjskyxrc80i2z91brmcw3v-peertube-server-3.0.0-rc.1/node_modules/async/retry.js:132:9)\n    at retry (/nix/store/r06jya5sr1qjskyxrc80i2z91brmcw3v-peertube-server-3.0.0-rc.1/node_modules/async/retry.js:142:5)\n    at /nix/store/drps2f2a6vmm4k1hvpvlk48pq6a9lz3r-peertube-3.0.0-rc.1/dist/server/helpers/database-utils.js:20:9\n    at new Promise (<anonymous>)\n    at transactionRetryer (/nix/store/drps2f2a6vmm4k1hvpvlk48pq6a9lz3r-peertube-3.0.0-rc.1/dist/server/helpers/database-utils.js:19:12)\n    at Object.retryTransactionWrapper (/nix/store/drps2f2a6vmm4k1hvpvlk48pq6a9lz3r-peertube-3.0.0-rc.1/dist/server/helpers/database-utils.js:7:12)\n    at /nix/store/drps2f2a6vmm4k1hvpvlk48pq6a9lz3r-peertube-3.0.0-rc.1/dist/server/middlewares/async.js:21:49\n    at Layer.handle [as handle_request] (/nix/store/r06jya5sr1qjskyxrc80i2z91brmcw3v-peertube-server-3.0.0-rc.1/node_modules/express/lib/router/layer.js:95:5)\n    at next (/nix/store/r06jya5sr1qjskyxrc80i2z91brmcw3v-peertube-server-3.0.0-rc.1/node_modules/express/lib/router/route.js:137:13)\n    at wrapper (/nix/store/r06jya5sr1qjskyxrc80i2z91brmcw3v-peertube-server-3.0.0-rc.1/node_modules/async/dist/async.js:268:20)\n    at replenish (/nix/store/r06jya5sr1qjskyxrc80i2z91brmcw3v-peertube-server-3.0.0-rc.1/node_modules/async/dist/async.js:435:29)\n    at iterateeCallback (/nix/store/r06jya5sr1qjskyxrc80i2z91brmcw3v-peertube-server-3.0.0-rc.1/node_modules/async/dist/async.js:424:21)\n    at /nix/store/r06jya5sr1qjskyxrc80i2z91brmcw3v-peertube-server-3.0.0-rc.1/node_modules/async/dist/async.js:321:20\n    at /nix/store/drps2f2a6vmm4k1hvpvlk48pq6a9lz3r-peertube-3.0.0-rc.1/dist/server/middlewares/validators/videos/video-imports.js:65:16\n    at Generator.next (<anonymous>)\n    at fulfilled (/nix/store/r06jya5sr1qjskyxrc80i2z91brmcw3v-peertube-server-3.0.0-rc.1/node_modules/tslib/tslib.js:111:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
Dec 20 19:38:22 peertube-test peertube-start[2520]:     "message": "Configuration property \"import.videos.http.proxy.enabled\" is not defined"
```

**Comment by Chocobozzz** [comment]
Please fill the template.

**Comment by stevenroose** [comment]
I started off the template. But I dropped fields that I didn't use.. Which is usually how a template works. F.e. also when for redis I fulled the unix socket field and hence removed the TCP hostname and port fields, but it complained about these being missing.

**Comment by rigelk** [comment]
We make use of knowing your instance and redis versions, for instance. The former is asked in the template and would have been useful to know the scope of the issue.

**Comment by stevenroose** [comment]
Oh I understood "didn't fill the template" as that I didn't fill the config
file template. 😅

Will provide the issue template when I'm on the computer. I used the
v3.0.0-rc.1.

**Comment by stevenroose** [comment]
I added some more information from the template.

**Comment by Chocobozzz** [comment]
Thanks, did you install this peertube version after an upgrade or is it your first install?

You should not have to check config key because:

 * On first install, you [copy](https://docs.joinpeertube.org/install-any-os?id=peertube-configuration) the default production.yaml containing all the keys
 * On upgrade, default.yaml file is copied by the updater script (or you copy it manually if you follow the doc https://docs.joinpeertube.org/install-any-os?id=upgrade)

**Comment by stevenroose** [comment]
It was my first install. I did copy the production.yaml and removed the stuff I don't need. Where is it documented that all keys in the example file need to be present? That's quite uninuitive. I always try to keep my config files succint and remove sections I don't need or some trivial default values.

**Comment by Chocobozzz** [comment]
Okay then I updated the documentation: https://github.com/Chocobozzz/PeerTube/commit/4948dcdbeb4b097770167b50f2bddade6ae88370
