### ISSUE TITLE
Upload pre-transcoded video to instance?

### ISSUE THREAD

**Issue by averyburnettmiller** [Chocobozzz/PeerTube#3498]
Hello! I just set up my instance and I'm really liking everything so far! Thanks for the work you all have put in to make this happen!
The server I'm running on has the bare minimum specs required to function. I plan to use my instance to only upload my own videos, and I was curious if there is a way for me to transcode different versions of a video locally and upload them to my instance, in order to save on resources.

**Comment by Chocobozzz** [comment]
Hello and thanks!

You can disable transcoding on the server, upload a video and use this CLI tool: https://docs.joinpeertube.org/maintain-tools?id=create-import-video-file-jobjs
