### ISSUE TITLE
support imported HDR videos 

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#3499]
Hi there!

It would be nice if HDR support was added to peertube.

Please see the attached image of how washed out colors are (even on a display without HDR) when importing a HDR video from youtube.

![firefox_YugrianVGK](https://user-images.githubusercontent.com/7935624/102726933-55cf8f80-42d7-11eb-8b60-1b6a99e38e9e.png)

**Comment by rigelk** [comment]
Could you check if the YouTube video is a h264 one? I fear that this codec, to which we are currently limited, doesn't support HDR. It could be interesting to see if having a richer profile like High 4:4:4 could reduce the visual difference, too.

**Comment by SimplyCorbett** [comment]
youtube-dl reports VP9 and AV01 formats with AV01 not having HDR. It's possible peertube is selecting VP9 instead for some reason.

It would be nice to see VP9 encoding support in peertube at some point.

I've been testing with the latest git version of peertube and upgraded my FFMPEG to 4.3.1 and it has the same issue.

**Comment by rigelk** [comment]
Could you try transcoding manually one of the files from YouTube, using a h264 High 4.4.4 profile and see if that brings us any closer to VP9 HDR?

**Comment by SimplyCorbett** [comment]
Can you give me the command you'd like run?

Using the high encoder profile with auto on level in handbrake gives me the correct color with x264. I'm not that experienced with ffmpeg though.

**Comment by rigelk** [comment]
Ah you're right, we are using a 3.1 level cap, so there might be that too.

**Comment by rigelk** [comment]
I checked myself, no need to run the command PeerTube would run (assuming a 420p version of your video which I downloaded as `example.mp4` onwards): `ffmpeg -i example.mp4 -y -an -vcodec libx264 -filter:v scale=w=trunc(oh*a/2)*2:h=420 -f mp4 -movflags faststart -max_muxing_queue_size 1024 -map_metadata -1 -b_strategy 1 -bf 16 -pix_fmt yuv420p -r 30 -maxrate 422417 -bufsize 844834 -level:v 3.1 -g:v 60 out.mp4`.

https://user-images.githubusercontent.com/6329880/102951007-25047b80-44cc-11eb-9e73-f2b168d035d0.mp4

It turns out, adding `-x264opts colorprim=bt2020:colormatrix=bt2020nc:transfer=smpte2084:chromaloc=2` and replacing `-pix_fmt yuv420p10le` brings the h264 colorspace close enough to HDR standards:

https://user-images.githubusercontent.com/6329880/102951020-2afa5c80-44cc-11eb-8067-7edb01652836.mp4

Both videos are best played in mpv. When it comes to browser support of h264 at these bit depths, they support seems flaky at best.

**Comment by rigelk** [comment]
From my tests, both Chromium and Firefox display colors shifted in luminance compared to when the same file (downloaded from YouTube) plays originally in YouTube, so even with no transcoding on our part there is a browser problem in how colors are interpreted, that seemingly the YouTube player fixes somehow.

@SimplyCorbett could you reproduce the problem? (= play the same video in YouTube with firefox and then directly opened with firefox once downloaded from YouTube)

**Comment by SimplyCorbett** [comment]
You might be right about the youtube player fixing it. When trying to play the imported video (before it's transcoded) the colors are washed out. I wonder what they are doing to fix this on their end?

![firefox_FMWYI2zAnY](https://user-images.githubusercontent.com/7935624/103017515-935f3300-44f8-11eb-96e3-bdc49d38cf83.png)

**Comment by rigelk** [comment]
@SimplyCorbett as I mentioned in my edit, that was my conclusion before I changed source from the AV1 to VP9 one. The latter works even opened by Firefox or Chromium, while the former is washed out as above.

**Comment by rigelk** [comment]
@SimplyCorbett I couldn't find issues in the Firefox/Chromium bugtrackers that explain why AV1s are showing washed out :/

Do you have other examples of HDR videos on YouTube?

**Comment by SimplyCorbett** [comment]
Well it's funny you should mention that. I'm just casually browsing HDR videos and AV1 is only available 1080p or lower according to youtube-dl. I'm assuming peertube grabs the highest resolution option?

Haven't checked out the super-popular HDR videos which will likely have AV1 in 1440p and 4k but it's interesting how youtube is prioritizing AV1 on less popular videos.

If you need me to test this I can grab the AV1 clips manually and upload to peertube to see if the problem can be reproduced further.

**Comment by rigelk** [comment]
> I'm assuming peertube grabs the highest resolution option?

So far, yes. #3516 intends to fix that.

> it's interesting how youtube is prioritizing AV1 on less popular videos.

It seems to be where the size reductions are the most important with AV1, so it makes sense.



> If you need me to test this I can grab the AV1 clips manually and upload to peertube to see if the problem can be reproduced further.

I'm not quite sure what I could do to better understand why AV1 HDR is not displaying correctly outside of YouTube (regardless of PeerTube, just playing it straight in a new tab). I'll ask around, and maybe then create another issue tracking HDR support in PeerTube itself.

Thanks for your time and help debugging the issue!

**Comment by rigelk** [comment]
OK, found it for Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1539685 which lists issues before full HDR support. Seems like YouTube's VP9 HDR uses HLG whereas its AV1 HDR doesn't. That would explain the observed difference since HLG allows a fallback for unable decoders.

**Comment by SimplyCorbett** [comment]
@Chocobozzz has this changed with YouTube since this was originally created in 2020? Do we still need to avoid AV1?

**Comment by Chocobozzz** [comment]
> has this changed with YouTube since this was originally created in 2020? Do we still need to avoid AV1?

I have no idea! Don't hesitate to make some tests and report your feedback in a dedicated issue :)
