### ISSUE TITLE
Visitors should not see the “Upload” button when signup is disabled

### ISSUE THREAD

**Issue by conferences-gesticulees** [Chocobozzz/PeerTube#350]
* **PeerTube version or commit: 1.0.0-alpha.8**

* **What is the expected behaviour?**

When an instance only accept uploads from known users, the “*Upload*” button in the top bar is useless to anonymous visitors. Administrators should have an option to hide it. Or maybe this should just be linked to the “*Signup enabled*” setting.

* **What do you see instead?**

The “*Upload*” button in the top bar is visible to visitors.

**Comment by Chocobozzz** [comment]
I disagree. This upload button is useful even if the user is not logged in because:
 * It helps people to understand you can upload videos on this platform
 * Sometimes you forgot you're not logged in, and once https://github.com/Chocobozzz/PeerTube/issues/294 is implemented people would not loose the habits to click on the top-left button to upload a video

**Comment by conferences-gesticulees** [comment]
Our instance is a run for a closed community. We have a process for accepting new members. Random visitors will never be allowed to upload videos on our instance. The button is pure noise for them.

**Comment by mrflos** [comment]
Hello, as a cheap hack, i would propose to add a css class on the body or the app that indicates the state of login (.not-logged or .logged).  
An instance willing to hide the upload button for non logged users could add a custom css like:
`.not-logged .upload-button { display:none; }`

**Comment by Chocobozzz** [comment]
Here you go: https://github.com/Chocobozzz/PeerTube/commit/d414207f07f47307947d86d5bc5c5fc0ae73be18

Just add this as custom CSS:

```
.user-not-logged-in .upload-button {
  display: none;
}
```

**Comment by tcitworld** [comment]
I also think that the button can be misleading.
> It helps people to understand you can upload videos on this platform

Couldn't it be shown only if registration is enabled on the instance ?

**Comment by Chocobozzz** [comment]
Some administrators ask people to send them an email for registration. If this button is not there, unregistered users would not understand that they could ask for an account to upload videos.
