### ISSUE TITLE
720P25 uploaded video doesn't play HLS in Safari

### ISSUE THREAD

**Issue by imc67** [Chocobozzz/PeerTube#3502]
**Describe the current behavior**
Uploading a 720P25 video (see screenshot below for specs) to a Peertube instance (on Cloudron) with settings HLS and 2 types of transcoding (see screenshot below) results in error and not playing in all Safari browsers (MacOS, iPadOS and iOS latest versions).

Video settings (in Apple Compressor, all 1000's of our produced videos works fine on FB and YT):
<img width="197" alt="Schermafbeelding 2020-12-15 om 09 46 09" src="https://user-images.githubusercontent.com/58652432/102771284-f54b5b80-4385-11eb-9b2a-fa04cd14c852.png">
PeerTube settings:
![schermafbeelding-2020-12-02-om-22 34 27](https://user-images.githubusercontent.com/58652432/102771519-4f4c2100-4386-11eb-91e3-c70a541aff64.png)
Error and NOT playing in Safari:
![schermafbeelding-2020-12-02-om-21 44 28](https://user-images.githubusercontent.com/58652432/102771573-67bc3b80-4386-11eb-969a-45fac93a97c6.png)
Non breaking error in Firefox MacOS but playing:
![schermafbeelding-2020-12-02-om-21 47 26](https://user-images.githubusercontent.com/58652432/102771661-93d7bc80-4386-11eb-962e-08a7d8dbb441.png)

**Steps to reproduce:**

1. export your video with settings like in screenshot Apple Compressor
2. upload to PeerTube
3. play video in any Safari

**Describe the expected behavior**
Playing the video

**Additional information**

* PeerTube instance:
  * URL:
  * version: 2.4.0
  * NodeJS version: v12.16.2
  * Ffmpeg version: ffmpeg version 4.3.1-0york0~18.04

* Browser name, version and platforms on which you could reproduce the bug: all Safari browsers (MacOS, iPadOS and iOS latest versions
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Could you attach a sample file (with a duration reduced to ~10s) so I can test and debug?

**Comment by imc67** [comment]
https://user-images.githubusercontent.com/58652432/102878903-44a69000-4449-11eb-9983-f605d002a635.mov

Is this ok?

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/236841a1d73a1b67541537f0017856848ad43b79
