### ISSUE TITLE
Saved keyword filters for comments moderation

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3503]
**Describe the problem to be solved**
admin/moderation/video-comments/list

this page correctly lists all the comments and right now we can filter by local and remote comments and also search within comments but i am suggesting we add predefined keywords to this page.

mastodon has this feature called "filtering posts" https://docs.joinmastodon.org/user/moderating/#filters
where as a user can specify which keywords to automatically hide. my suggestion is to apply this reasoning for moderation.

for a public instance, i do not want to be constantly searching for each and every problematic word. if i have this filtering, just looking at this page i would see 

* keyword 1 - 3 comments
*  keyword 2- no comments
* keyword 3- 15 comments

i probably should be given option to send the admin/admins  a notification incase some serious filter was triggered.

**Describe the solution you would like:**
add option to add predefined keywords to filter comments and maybe even allow admins to set notifications on trigger. this kind of moderation tools are very useful in reddit for example where mods have to deal with a lot of spam, hate, etc
.

**Describe alternatives you have considered**

**Comment by Chocobozzz** [comment]
Hello,

As an information the plugin API can be use to implement this kind of feature: https://docs.joinpeertube.org/contribute-plugins?id=spammoderation-plugin

**Comment by Chocobozzz** [comment]
We plan to implement this feature in 2024. Read the detailed blog post on https://joinpeertube.org/news/peertube-future-2024

**Comment by Chocobozzz** [comment]
This has been implemented in 6.2: https://joinpeertube.org/news/release-6.2

Where you can create watched words lists: https://docs.joinpeertube.org/admin/moderation#instance-watched-words-lists / https://docs.joinpeertube.org/use/setup-account#comments-on-your-videos
