### ISSUE TITLE
Idea: BitTorrent Token (BTT)

### ISSUE THREAD

**Issue by trymeouteh** [Chocobozzz/PeerTube#3509]
There is a crypto called BTT which is the token for torrents. Since Peertube uses torrents for its videos, an idea will be to allow peertube instances and anyone who helps seeds a video make some BTT. Earned BTT from the instance can help with pay for the hosting and BTT can be used as payment on Peertube for exclusive paywall videos uploaded by users.

https://www.bittorrent.com/token/btt/

**Comment by rigelk** [comment]
Hi! Thanks for reporting the issue, but this is out of the scope of PeerTube, per [our FAQ](https://github.com/Chocobozzz/PeerTube/blob/develop/FAQ.md#are-you-going-to-use-the-steem-blockchain) like any monetization system. But you could ask specific features/plugin hooks if you would like to create a plugin implementing it.

**Comment by NourEddineX** [comment]
I guess it would be great, maybe at some point in the future if BTT gains significantly bigger userbase the devs gets more interest into it, or maybe someone else can make a plugin etc..
