### ISSUE TITLE
Allow to set a default language for an instance

### ISSUE THREAD

**Issue by conferences-gesticulees** [Chocobozzz/PeerTube#351]
* **PeerTube version or commit: 1.0.0-alpha.8**

* **What is the expected behaviour?**

Our instance targets French speaking users. The interface should be in French even when the visiting browser says it prefers any other language. Administrators should be able to configure a default (or main) language.

* **What do you see instead?**

Using Tor Browser, the interface is in English.

**Comment by rigelk** [comment]
I guess this can only be implemented after #148.

**Comment by captnfab** [comment]
@conferences-gesticulees : I had a similar issue. Meanwhile, I did the following:
`cd /var/www/peertube/peertube-latest/client/dist/`
`mv en_US en_US.orig`
`ln -s fr_FR en_US`

**Comment by conferences-gesticulees** [comment]
We updated our instance to beta11. It's awesome to see PeerTube finally available in French.

In the context of our instance, our audience is limited to French speakers. It would therefore be better to have the admin set a global language and the ability for user the change the language on the fly.

**Comment by Chocobozzz** [comment]
Closing this issue because we don't really want to add complexity and break the web browser preferred language.
