### ISSUE TITLE
The view count is not working (stays at 0 despite numerous views taking place)

### ISSUE THREAD

**Issue by unfa** [Chocobozzz/PeerTube#3511]
**Describe the current behavior**

Some videos I've shared on PeerTube keep displaying 0 views, even though I'm sure the video has been played multiple times in the past 12 hours.

![image](https://user-images.githubusercontent.com/491704/102993586-b9e39500-451d-11eb-80f9-2d21ff1ecb2b.png)

**Describe the expected behavior**

I'd expect the view count to go up and update at least once an hour.

**Additional information**

* PeerTube instance:
https://tube.netzspielplatz.de/videos/watch/14101b29-46d4-4ff7-b0b9-1d57831b3f98

**Comment by kontrollanten** [comment]
Are you using any external proxy (e.g. load balancer or CDN)? If you check Admin > System > Debug, do you see your own public IP address?

Also check Admin > System > Jobs and filter by "video-views" and completed/failed/waiting/delayed and report what you see.
