### ISSUE TITLE
admin-remote-storage doesnt work

### ISSUE THREAD

**Issue by kgnfth** [Chocobozzz/PeerTube#3515]
following the setup here https://docs.joinpeertube.org/admin-remote-storage

`mount --bind /media/_data/backblaze-storage/streaming-playlists /peertube-data/_data/streaming-playlists`
error `special device /media/_data/backblaze-storage/streaming-playlists does not exist.`

but if i do the following

```
$ mkdir -p /media/_data/backblaze-storage/streaming-playlists
$ mount --bind /media/_data/backblaze-storage/streaming-playlists /peertube-data/_data/streaming-playlists
$  s3fs peertubetest /media/_data/backblaze-storage -o url=https://s3.eu-central-003.backblazeb2.com -o allow_other -o use_path_request_style -o uid=1000 -o gid=1000
```
then i get this error

`s3fs: MOUNTPOINT directory /media/_data/backblaze-storage not empty. if you are sure this is safe, can use the 'nonempty' mount option.`

**Comment by kgnfth** [comment]
this is

**Comment by kontrollanten** [comment]
I don't think it's meant to mount a bucket to a folder containing files. If I don't mistake the folder in which the mount is done to will be emptied, so therefore it's a good idea that it won't be cleaned automatically.
