### ISSUE TITLE
Redirect stream function

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#3517]
Install Peertube 3.0.0 RC1

You can add the ability to restim to other services such as youtube, twitch and others. Perhaps this will help attract viewers to the peertube servers!

For implementation, when creating a live broadcast, add the "Activate Restream" section, in which you can select ready-made servers, or enter your server address to which the live broadcast will be redirected.

**Comment by rigelk** [comment]
I don't see how this will help "attract" viewers to PeerTube servers, and arguably this is a feature better handled by OBS: https://obsproject.com/forum/resources/multiple-rtmp-outputs-plugin.964/

**Comment by Alterak** [comment]
> I don't see how this will help "attract" viewers to PeerTube servers, and arguably this is a feature better handled by OBS:

In this case, the entire load will go to my Internet channel. And if the multistream goes through the instance, then the load will be on the Internet channel of the instance. Perhaps this function will be useful to someone. I would use this function and advertise my copy on the air.

**Comment by Booteille** [comment]
I don't think it's a good idea to add load on the server this way since peertube's goal is to reduce bandwidth dependency of instance owners.

It's better handled by obs like softwares IMO.

**Comment by scanlime** [comment]
fwiw i think a restream feature would be quite useful. clearly it uses more bandwidth, but some servers have plenty of bandwidth (they are more limited by disk or CPU). I run my own re-streaming system using nginx and ffmpeg, but it's more complex than many people are willing to set up. OBS does not natively stream to multiple servers, as far as I know, and many people don't have the bandwidth on their residential connection for multiple simultaneous stream uploads.

**Comment by Chocobozzz** [comment]
Hello,

I agree a restream feature could be useful, but it's out of scope of PeerTube. Maybe a plugin could handle this use case, though.
