### ISSUE TITLE
1080p60 import loss of detail - bump bitrate

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#3519]
Not sure if this can be fixed or not but I suspect increasing the bitrate would do it.

When importing youtubes 1080p60 videos there is a loss of detail. Given that we're re-encoding youtube videos I'm not sure this can be fixed though.

Import: https://www.youtube.com/watch?v=QBoeNUpr2SA

The source video is already IMO bad quality but when comparing the two platforms:

Youtube:

![youtube2](https://user-images.githubusercontent.com/7935624/103107175-a0f7e400-45f0-11eb-82a1-fb2b9bca1488.jpeg)

Peertube:

![peertube2](https://user-images.githubusercontent.com/7935624/103107182-a48b6b00-45f0-11eb-9799-4c60daa1470b.jpeg)

Very noticeable loss of quality here. This is at 17:00 on the video.

PeerTube instance:
    URL: https://vidrot.com
    version: git
    NodeJS version: 12
    Ffmpeg version: 4.3.1

Browser name, version and platforms on which you could reproduce the bug: Firefox 84

**Comment by SimplyCorbett** [comment]
Eh, maybe I'm just nitpicking. It's not -that- noticeable. Sorry for wasting your time!

**Comment by rigelk** [comment]
@SimplyCorbett FYI you can always find the bitrates at which we transcode our videos at https://github.com/Chocobozzz/PeerTube//blob/5a547f69d5dc5867e253f7721513479c754b4f15/shared/models/videos/video-resolution.enum.ts#L13-L59
