### ISSUE TITLE
Support Owncast Streams

### ISSUE THREAD

**Issue by zcdunn** [Chocobozzz/PeerTube#3522]
Allow viewing [Owncast](https://owncast.online) streams within Peertube and when the stream is complete save the video as a Peertube video. 

I imagine this would require linking a Peertube account with an Owncastaccount. Validation of this relation ship could be handled by checking for a link in each account description or other metadata with a `rel=me` attribute pointing to the other account. `Rel=me` is how related accounts are handled in the IndieWeb and in Mastodon. (EDIT: Just found an issue on Owncast repo about supporting `rel=me` links too, https://github.com/owncast/owncast/issues/511)

This would be really useful for anyone who already has an Owncast account. It would enable them to easily get a VOD of their stream into the fediverse and a way for Peertube to get new viewers.

**Comment by rigelk** [comment]
What is Overcast? You are linking to owncast, for which https://github.com/owncast/owncast/issues/458 will help both platforms display each other's live streams.

I understand you want something a bit different: when an owncast steam ends, for it to be published as a PeerTube video. I'd argue this is more fitting as an owncast feature request too, since owncast would act as a PeerTube client to upload the video when it's own steam ends.

**Comment by zcdunn** [comment]
Overcast is unrelated. Sorry for the typo.

While the main focus was Owncast, I was hoping it would lead to a more general solution allowing any livestream to be displayed and saved in Peertube, regardless of ActivityPub support. I don't know much about the way the streaming works, but my understanding is that Peertube and Owncast use RTMP streams and these can be manipulated to enable rebroadcasting and saving.  Building this on RTMP means it would support any software that also uses RTMP for streaming. Then any new services wouldn't have to explicitly build support for Peertube.

**Comment by rigelk** [comment]
In your scenario, a PeerTube instance would store Owncast streams based on a `rel=me` tag, but you don't adress how the page is discovered, nor how PeerTube accesses the RTMP stream made to the Owncast server or the Owncast-generated stream for lack of another source (but then it would be Owncast-specific and defeat the purpose). I know RTMP is like a swiss-army knife but it doesn't mean everything magically connects 🙂 

An easier scenario is having OBS stream to multiple targets (Owncast and PeerTube) at the same time, via [this plugin](https://obsproject.com/forum/resources/multiple-rtmp-outputs-plugin.964/). Likely other RTMP clients should be able to do the same with some tuning.

**Comment by Chocobozzz** [comment]
Hello,

Thanks for this issue but it's out of the scope of PeerTube to inject remote player in the interface. ActivityPub should be the way to handle this use case. See also https://github.com/Chocobozzz/PeerTube/issues/3517 for the restream feature.
