### ISSUE TITLE
Separate hls live folder from stored video hls

### ISSUE THREAD

**Issue by PhieF** [Chocobozzz/PeerTube#3523]
Hi

I'm now using a s3 type storage
it works great for ordinary videos but not at all for lives
It would be great is instead of streaming-playlists live were stored somewhere else, so as for lives I could use server storage, then they would be moved to the s3 storage at the end of the stream...

Thanks for your work, once again !

**Comment by PhieF** [comment]
By the way : it would also improve backups, as we don't need to backup ongoing streams

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/3661
