### ISSUE TITLE
Error Cannot retrieve OAuth Client 

### ISSUE THREAD

**Issue by azmiplg78** [Chocobozzz/PeerTube#3524]
Error
Cannot retrieve OAuth Client credentials: Server error: . Ensure you have correctly configured PeerTube (config/ directory), in particular the "webserver" section.

**Comment by rigelk** [comment]
Please paste the webserver section of your production.yaml (or env variables if you use docker).

**Comment by Chocobozzz** [comment]
And please fill also the bug template
