### ISSUE TITLE
report the number of active users in NodeInfo

### ISSUE THREAD

**Issue by wiki-me** [Chocobozzz/PeerTube#3525]
**Describe the problem to be solved**

The number of active users is not reported in the-federation.info peertube [page](https://the-federation.info/peertube) (or the pages of any of it's instances).

**Describe the solution you would like:**

it should show the number of active users (preferably both monthly and six month interval).

**motivation:**

it would show more of the federation active users, having a bigger count of the federation could show it’s popular and might attract more people.

You could see how many active users each instance has, so if a instance has a lot of users or it’s graph is  showing growth ( [e.g.](https://the-federation.info/node/start.hubzilla.org) ) you could assume it indicates (in a wisdom of the crowds sort of way) it is a good instance and has a smaller chance of disappearing.

**Comment by rigelk** [comment]
I suggest you open this issue on https://github.com/thefederationinfo/the-federation.info/issues/new first, so that the developers of the-federation.info explain what data is missing from our Nodeinfo endpoints.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/47d8e266f16b91fec7e4a15a8372d50c2909c042
