### ISSUE TITLE
Increase/change transcoding thread amount

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#3527]
With CPU's like the 3900x and 3950x becoming more common it would be nice to see a higher CPU thread transcoding count available.

I'd prefer to not use auto.

Peertube is limited to 8 threads but my 3900x can technically push 12. 24 if I wanted to use SMT. It would also be nice to see more thread options available - such as instead of immediately jumping from 4 to 8 there is the option for 4 to 6 to 8 and so on.

I'm not that familiar with video transcoding but I believe increments of 2 would be okay. I think 1080p has diminishing returns above 8 but 1440p and 4k video would/should benefit from a higher thread count.

**Comment by test2a** [comment]
Do you run an instance on one? I am very interested in knowing how much can these cpus work for an instance. How many simultaneous transcoding, serving files,  website and such

**Comment by SimplyCorbett** [comment]
> Do you run an instance on one? I am very interested in knowing how much can these cpus work for an instance. How many simultaneous transcoding, serving files, website and such

Yes, I run proxmox on one of them along with peertube. The 3900x will take everything you can throw at it and keep chugging right along. My next server will either be a 5900x or a 5950x.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/ead64cdf8d917fa0d6a20271e42378f38e5f2407
