### ISSUE TITLE
Links are not visible enough in the descriptions

### ISSUE THREAD

**Issue by conferences-gesticulees** [Chocobozzz/PeerTube#353]
* **PeerTube version or commit: 1.0.0-alpha.8**

* **What is the expected behaviour?**

Because descriptions are in Markdown format, they can easily contain links to other websites. However, in the current stylesheet they are hardly visible as such (at least for a colorblind person with protanopia).

* **What do you see instead?**

Links cannot be identified as such in the description unless the pointer is over them.

**Comment by Ealhad** [comment]
What would you suggest? A brighter color? Underline?

**Comment by Chocobozzz** [comment]
Closing due to no answer, don't hesitate to ask for reopening it!
