### ISSUE TITLE
Peertube won't start. Similar to issue 3426(but not the same, sadly)

### ISSUE THREAD

**Issue by Bakpfeife** [Chocobozzz/PeerTube#3531]
**Describe the problem**
peertube.service has issues starting
Error 255 in npm start
**Provide the exact sequence of commands / steps that you executed before running into the problem**
Followed the Install guide
**Additional information**
Similar issue as https://github.com/Chocobozzz/PeerTube/issues/3426
but after using the command: cd /var/www/peertube/peertube-latest && NODE_ENV=production NODE_CONFIG_DIR=/var/www/peertube/config node dist/server
my output was different

* PeerTube instance:
  * version: 2.4
  * NodeJS version: 10.x(downloaded via stream 10)
  * Ffmpeg version:
  * Redis version:
  * PostgreSQL version:

**Comment by Bakpfeife** [comment]
Command output(because it somehow doesn't display, I am pretty new to markdown):
[example.com:443] 2020-12-30 12:47:11.588 warn: Emailer is disabled so the contact form will not work.
[example.com:443] 2020-12-30 12:47:12.094 error: Unable to connect to PostgreSQL database. {
  "err": {
    "stack": "SequelizeConnectionError: Ident-Authentifizierung für Benutzer »peertube« fehlgeschlagen\n    at Client.connection.connect.err [as _connectionCallback] (/var/www/peertube/versions/peertube-v2.4.0/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:182:24)\n    at Client._handleErrorWhileConnecting (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg/lib/client.js:296:19)\n    at Client._handleErrorMessage (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg/lib/client.js:316:19)\n    at Connection.emit (events.js:198:13)\n    at parse (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg/lib/connection.js:109:12)\n    at Parser.parse (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg-protocol/dist/parser.js:40:17)\n    at Socket.stream.on (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg-protocol/dist/index.js:8:42)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
    "message": "Ident-Authentifizierung für Benutzer »peertube« fehlgeschlagen",
    "name": "SequelizeConnectionError",
    "parent": {
      "stack": "error: Ident-Authentifizierung für Benutzer »peertube« fehlgeschlagen\n    at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg-protocol/dist/parser.js:278:15)\n    at Parser.handlePacket (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.stream.on (/var/www/peertube/versions/peertube-v2.4.0/node_modules/pg-protocol/dist/index.js:8:42)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)",
      "message": "Ident-Authentifizierung für Benutzer »peertube« fehlgeschlagen",
      "length": 119,
      "name": "error",
      "severity": "FATAL",
      "code": "28000",
      "file": "auth.c",
      "line": "329",
      "routine": "auth_failed"
    }
  }
}

**Comment by Chocobozzz** [comment]
Hello,

PeerTube cannot connect to your database. Check your configuration: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L36

**Comment by Bakpfeife** [comment]
Is there some way to narrow down the issue? Because I updated the config to suit databasename, password, hostname, port and so on and its unfortunately still not working.

**Comment by Bakpfeife** [comment]
Ah. Might have narrowed it down myself. Seems like accessing the peertube user in psql is complicated atm for no apparent reason.

**Comment by Bakpfeife** [comment]
Update: PSQL has install errors. Probably part of the issue.

**Comment by Bakpfeife** [comment]
If you don't mind me asking, the production.yaml config file wants to use password instead of ident(so using a certain user) as the psql authentification method? Or does it really use ident?

**Comment by Bakpfeife** [comment]
Or does it use peer? Cause peer was used during the install, that seems weird though.

**Comment by Bakpfeife** [comment]
Fixed all errors in the database itself and looked at the config itself again. still got the database error. It seems the Ident authenticator is failing. How can I change it to a password authenticator? Because that is probably having less errors.

**Comment by Bakpfeife** [comment]
(I know how to change it in the database itself, just not in the config)

**Comment by Bakpfeife** [comment]
THIS issue is solved(new error) I was stupid and I used my hostname instead of 'localhost' in the hostname for the database.

**Comment by Bakpfeife** [comment]
Okay it seems to want to reach "peertube_dev" as defined in default.yaml instead now and there of course is no peertube_dev. Why would it use default.yaml? Isn't that not supposed to be used or edited?

**Comment by Bakpfeife** [comment]
Database works. Just gotta do some fixes of the url.

**Comment by Chocobozzz** [comment]
Please reinstall PeerTube. Your instance should use `production.yaml` file. See https://docs.joinpeertube.org/install-any-os?id=peertube-configuration

**Comment by Bakpfeife** [comment]
Would just like to add that the solution to the issue was to change the pg_hba.conf file in pgsql to accept md5 as the authorisation method and to leave the hostname as 'localhost' even if you changed your hostname. Just if someone stumbles on this thread.
