### ISSUE TITLE
No embed in WP5.6

### ISSUE THREAD

**Issue by gerhardbeck** [Chocobozzz/PeerTube#3533]
**Describe the current behavior**
hi, if I want to use the Video embed function from Wordpress 5.6 the embed link of peertube (e.g. https://evangelisch.video/videos/watch/0ea1f658-c562-430c-831d-22fb9768c608) doesn't work

The console shows the messages:
```
Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. krippenspiel-2020-geweckt-werden
Medien konnte nicht abgespielt werden. Keine Dekoder für angefragte Formate: video/mp4 krippenspiel-2020-geweckt-werden
Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. post.php
JQMIGRATE: Migrate is installed, version 3.3.2 load-scripts.php:5:709
Diese Website verwendet anscheinend einen scroll-verknüpften Positionierungseffekt. Dies könnte mit asynchronem Verschieben (Panning) schlecht zusammenspielen; siehe https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects für weitere Details und nehmen Sie an der Diskussion über damit verbundene Werkzeuge und Funktionen teil! post.php
MouseEvent.mozPressure sollte nicht mehr verwendet werden. Verwenden Sie PointerEvent.pressure stattdessen. tinymce.min.js:2:8856
HTTP-Content-Type "text/html" wird nicht unterstützt. Laden der Medienressource https://evangelisch.video/videos/watch/0ea1f658-c562-430c-831d-22fb9768c608 fehlgeschlagen. post.php
HTTP-Content-Type "text/html" wird nicht unterstützt. Laden der Medienressource https://evangelisch.video/videos/watch/0ea1f658-c562-430c-831d-22fb9768c608 fehlgeschlagen. post.php
```

**Steps to reproduce:**

1.Login into a WP 5.6 with Gutenberg Block Editor
2.Open a new blog Video => from URL 
3.Insert the embed link from peertube

**Describe the expected behavior**
I expect it to embed the video

**Additional information**
embedding works when embedding the link with .mp4 from "download"
* PeerTube instance:
  * URL: evangelisch.video

* Browser name, version and platforms on which you could reproduce the bug: Firefox 84.0 Ubuntu

**Comment by Chocobozzz** [comment]
Hello,

I think it does not work because wordpress uses an internal whitelist depending on the URL: https://wordpress.org/support/article/embeds/#oembed

You could try https://wordpress.org/support/article/embeds/#adding-support-for-an-oembed-enabled-site

**Comment by gerhardbeck** [comment]
Hi, I tested and notice:
Embedding peertube works if choosing the block "embed" or if the link is pasted directly, but not in the block "video". Very weird.
Gerhard
