### ISSUE TITLE
Process exists after trying to update youtube-dl in a read-only container

### ISSUE THREAD

**Issue by johanfleury** [Chocobozzz/PeerTube#3535]
**Describe the current behavior**

I’m running PeerTube in a read-only container (option `--read-only` for Docker or `readOnlyRootFilesystem: true` in Kubernetes) and it crashes every 24h or so while trying to update youtube-dl.

This is the stack trace when this happens:

```
[peertube.br0.fr:443] 2020-12-31 23:01:40.129 ESC[32minfoESC[39m: Updating youtubeDL binary.
[peertube.br0.fr:443] 2020-12-31 23:01:40.130 ESC[32minfoESC[39m: Checking latest plugins version.
[peertube.br0.fr:443] 2020-12-31 23:01:40.138 ESC[32minfoESC[39m: Removing old jobs in scheduler.
[peertube.br0.fr:443] 2020-12-31 23:01:40.230 ESC[32minfoESC[39m: 10.2.0.1 - - [31/Dec/2020:23:01:40 +0000] "GET / HTTP/1.1" 200 3781 "-" "kube-probe/1.20"

[peertube.br0.fr:443] 2020-12-31 23:01:40.268 ESC[32minfoESC[39m: Removing bad actor follows (scheduler).
[peertube.br0.fr:443] 2020-12-31 23:01:41.959 ESC[31merrorESC[39m: uncaughtException: EROFS: read-only file system, open '/app/node_modules/youtube-dl/bin/youtube-dl'
Error: EROFS: read-only file system, open '/app/node_modules/youtube-dl/bin/youtube-dl' {
  "error": {
    "stack": "Error: EROFS: read-only file system, open '/app/node_modules/youtube-dl/bin/youtube-dl'",
    "message": "EROFS: read-only file system, open '/app/node_modules/youtube-dl/bin/youtube-dl'",
    "errno": -30,
    "code": "EROFS",
    "syscall": "open",
    "path": "/app/node_modules/youtube-dl/bin/youtube-dl"
  },
  "stack": "Error: EROFS: read-only file system, open '/app/node_modules/youtube-dl/bin/youtube-dl'",
  "exception": true,
  "date": "Thu Dec 31 2020 23:01:41 GMT+0000 (Coordinated Universal Time)",
  "process": {
    "pid": 19,
    "uid": 65534,
    "gid": 65534,
    "cwd": "/app",
    "execPath": "/usr/local/bin/node",
    "version": "v10.22.0",
    "argv": [
      "/usr/local/bin/node",
      "/app/dist/server"
    ],
    "memoryUsage": {
      "rss": 143691776,
      "heapTotal": 96436224,
      "heapUsed": 83051088,
      "external": 506040
    }
  },
  "os": {
    "loadavg": [
      0.07421875,
      0.15673828125,
      0.1083984375
    ],
    "uptime": 1303915
  },
  "trace": []
}

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peertube@2.4.0 start: `node dist/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@2.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Steps to reproduce:**

1. Run PeerTube in a read-only container
2. Wait 24h or so
3. Notice that PeerTube crashes with a stack trace

**Describe the expected behavior**

First of all, I think PeerTube shouldn’t crash if it can’t perform a background task, but it should rather warn the administrator somehow (with a log message, an entry the job list, or even a notification).

Also, I think it should avoid changing anything in the non-persistent part of the container.

That being said, I see a couple of solutions:

* Add a flag or a configuration option to disable the `youtube-dl` upgrade feature
* Store `youtube-dl` in a place that can be mounted as a persistent volume (like for plugins)

**Additional information**

* PeerTube instance:
  * URL: https://peertube.br0.fr/
  * Version: 2.4.0, using official docker image

**Comment by Chocobozzz** [comment]
Thanks, I fixed the crash in https://github.com/Chocobozzz/PeerTube/commit/027e3080998c3e99e3a16bc336ccf47e0f1d5a8e

Unfortunately we don't support `--read-only` option for docker.

**Comment by johanfleury** [comment]
Hey @Chocobozzz, thank you very much for the fix.

> Unfortunately we don't support --read-only option for docker.

Should I open a feature request for that?

Looking at #3540, it seems that it’s not only about the container being read-only, but also having it run as a non-privileged user with uid and gid that are not the same as the `peertube` user inside the container.

@faust64 also has some very good point regarding how the download is made, should we open issues for that?
