### ISSUE TITLE
SRT or VTT upload but does not display

### ISSUE THREAD

**Issue by numeropi** [Chocobozzz/PeerTube#3536]
I realized that peertube was accepting any .srt bad-formed subtitle and therefore not displaying it afterwards during the video play (it shows javascript error on browser debug mode during play). 
![image](https://user-images.githubusercontent.com/56868560/103446012-03995180-4c7b-11eb-9ad5-99cc3acdb4a5.png)

I believe that maybe as a feature request for new versions of peertube... the .srt should be parsed and not accepted while uploading, maybe showing a "subtitle bad formatted" or similar.
And therefore will know that the problem is on their side, not in the platform.

I attach version of a .srt that was accepted but not displayed, and a .srt accepted but working(after fixing the format).

[subs.zip](https://github.com/Chocobozzz/PeerTube/files/5759338/subs.zip)

Thanks.

**Comment by Chocobozzz** [comment]
Hello,

Please fill the bug template

**Comment by numeropi** [comment]
This is the video after uploading the correct formatted .srt file:
https://video.anartist.org/videos/watch/963ad13e-00a3-4a27-8bfb-97a753d491ca

originally it was not showing the subtitles and we thought it was a peertube problem or a browser problem and then bcs of the javascript errors we realized that it was a srt error. This bug could get converted into a feature request of adding a SRT checker before the upload process  if you prefer. 

Thanks.

**Comment by WestphalDenn** [comment]
I have the same Issue after it worked till the 12 of January. The STR-Files I use are well formated. So I was shocked to find out that all of my subtitles arn't displayed anymore. 

The Errorcode suggests a simmilar issue however.

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/c9ae74d6bc2918ac38ce2dd25aa8c542132529ef
