### ISSUE TITLE
How to add additional physical storage?

### ISSUE THREAD

**Issue by JasXSL** [Chocobozzz/PeerTube#3537]
I'm currently self hosting an instance using a 2TB drive for video storage. In the future when that gets full, I'd probably like to buy a couple of 8TB drives and add to the existing 2TB drive. **Is there a recommended way of combining these?** I'm hoping to not need to use RAID. I'm estimating needing a lot more storage than read speed as I'll likely end up with a lot of videos and not so many viewers.

**Comment by rigelk** [comment]
Hi @JasXSL,

You might get more detailed answers looking for this subject independently of PeerTube. Personally I'd go for https://github.com/trapexit/mergerfs if I were you, but YMMV. You might find unionfs or aufs interesting too, albeit unmaintained they proved production-ready too.
