### ISSUE TITLE
Don't prompt for confirmation when WebRTC is disabled

### ISSUE THREAD

**Issue by conferences-gesticulees** [Chocobozzz/PeerTube#354]
* **PeerTube version or commit: 1.0.0-alpha.8**

* **What is the expected behaviour?**

When using Tor Browser, I should not be asked to confirm that I'm ok to share my IP address as we now this won't happen. Tor Browser is built without any WebRTC support, so we know this is not a problem.

* **What do you see instead?**

When using Tor Browser, I have to confirm that I will share my IP address. This might confuse Tor users.

**Comment by Chocobozzz** [comment]
Done: https://github.com/Chocobozzz/PeerTube/commit/caae7a0671df4cd513043ccf9c0b8a8d4b58845c#diff-b7342a12f863e2ea4fe04b8f4f704fbfR78
