### ISSUE TITLE
Import job cannot be cancelled

### ISSUE THREAD

**Issue by verymilan** [Chocobozzz/PeerTube#3541]
Hi there, i have not found a matching issue for this.. a user recently asked how they could cancel their import. It appears that there is no way for the user, nor through the admin interface to cancel such a job.

Could be a nice addition as a feature. :)

**Comment by zygof** [comment]
Hi, i can propose a solution on this ? :)

**Comment by rigelk** [comment]
@zygof you're free to submit a PR 🙂

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/419b520ca4434d17f3505013174e195c3a316716
