### ISSUE TITLE
Job type filter displayed twice

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#3545]
**Describe the current behavior**

On page /admin/system/jobs , in the job type select, the item «video-live-ending» appears twice. 

**Steps to reproduce:**

1.Go on /admin/system/jobs
2. Open the select to filter by job type

**Describe the expected behavior**

Should only be there once.

**Additional information**

* PeerTube instance:
  * version: 3.0.0

* Browser name, version and platforms on which you could reproduce the bug: firefox

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/a11a782f5c142f88acff8b604224cefeb8417cf1
