### ISSUE TITLE
Docker upgrade problems

### ISSUE THREAD

**Issue by tonytins** [Chocobozzz/PeerTube#3546]
**Describe the problem**

My PeerTube instance uses Docker. I upgraded from 2.4 to 3.0 but the user interface and admin options remain unchanged. It acknowledges the live feature exists when I try to update my configuration within the admin panel but I'm not presented with the any live options. 

Regardless of changing anything, I get this error:

> Should have a valid live enabled boolean. Should have a valid live allow replay boolean. Should have a valid live max duration. Should have a valid max instance lives. Should have a valid max user lives. Should have a valid live transcoding enabled boolean. Should have a valid live transcoding threads. Should have a valid transcoding 240p resolution enabled boolean.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I changed ``chocobozzz/peertube:latest`` to ``chocobozzz/peertube:v3.0.0-buster`` in the Docker Compose file.

**Additional information**

* PeerTube instance:
  * version: 3.0 from 2.4

**Comment by bikubi** [comment]
Experiencing something pretty similar:
I updated 2.1.1 → 2.4.0 via the same method, but my error message says:

> Should have a valid broadcast message enabled boolean. Should have a valid broadcast message. Should have a valid broadcast level. Should have a valid broadcast dismissable boolean. Should have a remote URI search for users boolean. Should have a valid remote URI search for anonymous boolean. Should have a valid search index enabled boolean. Should have a valid search index URL. Should have a valid search index disable local search boolean. Should have a valid search index default enabled boolean

Console says:

```
  "path": "/api/v1/config/custom",
  "err": {
    "broadcastMessage.enabled": {
      "msg": "Should have a valid broadcast message enabled boolean",
      "param": "broadcastMessage.enabled",
      "location": "body"
    },
    "broadcastMessage.message": {
      "msg": "Should have a valid broadcast message",
      "param": "broadcastMessage.message",
      "location": "body"
    },
    "broadcastMessage.level": {
      "msg": "Should have a valid broadcast level",
      "param": "broadcastMessage.level",
      "location": "body"
    },
    "broadcastMessage.dismissable": {
      "msg": "Should have a valid broadcast dismissable boolean",
      "param": "broadcastMessage.dismissable",
      "location": "body"
    },
    "search.remoteUri.users": {
      "msg": "Should have a remote URI search for users boolean",
      "param": "search.remoteUri.users",
      "location": "body"
    },
    "search.remoteUri.anonymous": {
      "msg": "Should have a valid remote URI search for anonymous boolean",
      "param": "search.remoteUri.anonymous",
      "location": "body"
    },
    "search.searchIndex.enabled": {
      "msg": "Should have a valid search index enabled boolean",
      "param": "search.searchIndex.enabled",
      "location": "body"
    },
    "search.searchIndex.url": {
      "msg": "Should have a valid search index URL",
      "param": "search.searchIndex.url",
      "location": "body"
    },
    "search.searchIndex.disableLocalSearch": {
      "msg": "Should have a valid search index disable local search boolean",
      "param": "search.searchIndex.disableLocalSearch",
      "location": "body"
    },
    "search.searchIndex.isDefaultSearch": {
      "msg": "Should have a valid search index default enabled boolean",
      "param": "search.searchIndex.isDefaultSearch",
      "location": "body"
    }
  }
```

**Comment by Chocobozzz** [comment]
Hello,

Please could you paste your docker compose file?

**Comment by tonytins** [comment]
https://gist.github.com/tonytins/24adc442bc495a9f0970f6d912df74c5

**Comment by Chocobozzz** [comment]
Thanks, I reproduced. The issue is that docker do not update our named volume `assets` (containing clients files) since it was already created by the last container (peertube 2.4).

Then I think the appropriate upgrade command should be `docker-compose pull && docker-compose down -v && docker-compose up -d`. It's longer but safer

**Comment by tonytins** [comment]
And thank you. That fixed the problem.

**Comment by bikubi** [comment]
Here, too, the `-v` in `down -v` was critical.
Thanks!

**Comment by Chocobozzz** [comment]
Thanks for the feedback. I updated the documentation: https://docs.joinpeertube.org/install-docker?id=build-your-own-docker-image

**Comment by bikubi** [comment]
@Chocobozzz -- that link says "Page not found"

**Comment by Chocobozzz** [comment]
It should also say *Please check that one of your web browser extensions (Privacy Badger, uMatrix, uBlock etc) does not block requests to GitHub.*. Did you?

**Comment by bikubi** [comment]
It does say that & I did & now I am utterly ashamed. Sorry, thanks!
