### ISSUE TITLE
Docs are not visible without MalwareScript enabled.

### ISSUE THREAD

**Issue by KOLANICH** [Chocobozzz/PeerTube#3547]
**Parts of the documentation concerned:**

All.

**Describe the desired information/correction**

The docs should be visible right after page load without any MalwareScript enabled. And MalwareScript must not be used on docs pages at all.

**Comment by rigelk** [comment]
hi @KOLANICH,

We use diverse tools to generate our documentation: Docsify and Redoc. Please open issues at their end. In the meantime, you can browse our documentation at its repository: https://framagit.org/framasoft/peertube/documentation

**Comment by KOLANICH** [comment]
>We use diverse tools to generate our documentation: Docsify and Redoc.

Who forces you into using them instead of just serving plain MarkDown/ReStructuredText files?

>https://framagit.org/framasoft/peertube/documentation

It also doesn't work without MalwareScript. Though I remember the last lime I have looked into their sources there was a pref to disable rendering of repo dir listings in JS and use server-side rendering instead. Though I suspect that they may have completely removed it since it JS their goal to push for JS (they have multiple time were caught on using JS-based malware, such as Cloudflare "under attack" mode on their login page (I won't even dig into what that code really does, for me it is enough that it is obfuscated) or browser fingerprinting in gitter that used to be owned by them).

**Comment by KOLANICH** [comment]
> > We use diverse tools to generate our documentation: Docsify and Redoc.
> 
> Who forces you into using them instead of just serving plain MarkDown/ReStructuredText files?
> 
> > https://framagit.org/framasoft/peertube/documentation
> 
> It also doesn't work without MalwareScript. Though I remember the last lime I have looked into GitLab sources there was a pref to disable rendering of repo dir listings in JS and use server-side rendering instead. Though I suspect that they may have completely removed it since it is their goal to push for JS (they have multiple time were caught on using JS-based malware, such as Cloudflare "under attack" mode on their login page (I won't even dig into what that code really does, for me it is enough that it is obfuscated) or browser fingerprinting in gitter that used to be owned by them).

**Comment by ldidry** [comment]
> It also doesn't work without MalwareScript.

But you can clone the repository and browse it locally without javascript.

**Comment by KOLANICH** [comment]
>But you can clone the repository and browse it locally without javascript.

Of course I can, as a workaround. But surely it shouldn't be done this way. The process of distribution of docs is still flawed, and should be fixed.
