### ISSUE TITLE
Display total views count

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3549]
**Describe the problem to be solved**
As soon as views count reaches 1 000 it will get shortened to 1K. The users won't see any updated view count until there's 1 000 more views. Since the view count is an important point for the users (and publishers) I think it's also important to let them see how it's changing.

**Describe the solution you would like:**
There's a lot of space after the views count, so it shouldn't be any problem to show the exact view count up to 99 999.

**Comment by Chocobozzz** [comment]
Hello,

The purpose of the short unit is to better understand the total views of a video (69K is clearer than 69 356 when you want to compare your video views). But you can also see the exact number of views on hover

**Comment by tcitworld** [comment]
Maybe add one digit after the decimal point if the views number is < 10K ?

**Comment by thekaleidoscope** [comment]
What if you show the whole count value on hover, while the shortened form can stay as is

**Comment by rigelk** [comment]
@thekaleidoscope it is already the case

**Comment by kontrollanten** [comment]
Thanks for the quick PR, @rigelk !

@Chocobozzz I understand. I'm not sure if I think the short versions is easier to compare though, and I'm thinking about that Youtube doesn't shorten their views until it reaches millions. There's a lot of money and UX research behind Youtubes decision so maybe it's not a bad idea to just follow their approach?

**Comment by rigelk** [comment]
@kontrollanten YT exposes answers without the reasoning that lead to them, so it's not like everything is transposable.
