### ISSUE TITLE
More Federated Share Options for Peertube Media

### ISSUE THREAD

**Issue by geopayme** [Chocobozzz/PeerTube#3552]
**Describe the problem to be solved**

  The Peertube instances currently only offer Twitter and Facebook Share options, I believe this to be counter intuitive to the idea and principals of decentralization and de-googlization of media.

**Describe the solution you would like:**

  We like to see more Federated SHARE options in the instance besides Facebook and Twitter, Mastodon should also be included and any other Open Source that replaces Facebook.

**Describe alternatives you have considered**

**Comment by tcitworld** [comment]
It's been a while since I linked to https://github.com/tootsuite/mastodon/issues/9373 :)

**Comment by Chocobozzz** [comment]
Hello,

I'm not sure to understand because we don't offer twitter & fb shares

**Comment by test2a** [comment]
He is talking about share plugin. How can we define a mastodon URL in the plugin when there are hundreds?

**Comment by geopayme** [comment]
**SHARE Section**

![image](https://user-images.githubusercontent.com/8299759/104018536-9b8ac400-51c2-11eb-950a-4acd9d5549bc.png)

**Administration Section**

![image](https://user-images.githubusercontent.com/8299759/104018689-e86e9a80-51c2-11eb-8754-8292074f1027.png)

I know this is a Share Plugin, can Peertube add a default SHARE for the Federated Instances - copying and pasting links make the process burdensome and less adaptable for users who are used to other social media

**Comment by geopayme** [comment]
> He is talking about share plugin. How can we define a mastodon URL in the plugin when there are hundreds?

Each Instance owner has to configure for their needs, I run 8 Peertube Instances 1 Mastodon and 1 Mobilizon Instance, We have 20 more in the pipeline for deployment and all the partners ask the same questions on SHARE so I hope this can be taken on by the Team and we can work out a future option solution.

**Comment by Chocobozzz** [comment]
Okay so it's from the sahre plugin, then you should open an issue on https://github.com/kimsible/peertube-plugin-social-sharing
