### ISSUE TITLE
Long hls conversion

### ISSUE THREAD

**Issue by Nojus789** [Chocobozzz/PeerTube#3554]
Hello, I upgraded from v3.0.0-rc.1 version to the latest v3.0.0, in the rc version hls playlist generated instantly, but in the latest version for hls to generate it takes about 30-40 minutes. Did anything change? Is it possible to generate hls instantly, without downgrading to the older version of peertube (I transcode the video to peertube specs before the upload)? Also optimization transcoding hasn't changed it is still instant.

**Comment by Chocobozzz** [comment]
Hello,

Unfortunately we had to force the first HLS encoding job because we had some playback issues on Safari: https://github.com/Chocobozzz/PeerTube/commit/236841a1d73a1b67541537f0017856848ad43b79

**Comment by Nojus789** [comment]
> Hello,
> 
> Unfortunately we had to force the first HLS encoding job because we had some playback issues on Safari: [236841a](https://github.com/Chocobozzz/PeerTube/commit/236841a1d73a1b67541537f0017856848ad43b79)
> 
> Associated bug: #3502

Is there a way to not force the hls encoding? Because the videos I encode work fine everywhere, there is no need for me to have forced hls encoding.

**Comment by Chocobozzz** [comment]
> Is there a way to not force the hls encoding?

No sorry.
