### ISSUE TITLE
Do we need port 1953/tcp open ? Also in ipv6 ?

### ISSUE THREAD

**Issue by 22decembre** [Chocobozzz/PeerTube#3556]
According to ...

https://www.reddit.com/r/PeerTube/comments/ksuli8/is_there_any_instance_that_supports_live/

You need port 1953/TCP open on firewall to make live work. It is not described in the documentation.
As looking netstat, yes something is trying to listen on it. Also, if it's needed, can it work on ipv6 ?

**Comment by rigelk** [comment]
Yes, RTMP defaults to 1953/TCP and if live is enabled in PeerTube, will be listened on. I explicited it in https://framagit.org/framasoft/peertube/documentation/-/commit/27d9f315b39e6ebcb8061b5802844d84db188c55

> Also, if it's needed, can it work on ipv6?

I don’t see any reason why it shouldn’t.
