### ISSUE TITLE
Restrict resolution under heavy load (or in general)

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#3557]
When peertube is under heavy load or the systems administrator decides that the instance has grown too popular and wants to conserve bandwidth then the option should be available to change the maximum resolution on the videos.

This option would not change the storage backend but would prevent viewers from viewing x resolution.

The resolution could be grayed out in the video or just removed altogether.

Example:

1080p,2160p disabled -> max displayable resolution 720p.

We could go a step further and have different resolution restrictions on guests and registered users.

Just a thought!

**Comment by Chocobozzz** [comment]
Hello,

Thanks for this issue but it's out of the scope of PeerTube. A plugin could be created to implement this thing.
