### ISSUE TITLE
Lack of errors when the port 1935 is already in use

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#3558]
**Describe the current behavior**

If there is already another RTMP server listening on port 1935, Peertube start without any error. The only log is «Running RTMP server on port 1935», and peertube seems happy. But in fact peertube will not receive any connection.

**Steps to reproduce:**

1. Stop peertube
2. Setup a RTMP server on port 1935 (see below for a nginx snippet to do this). 
3. Start peertube.

For setting up a RTMP server with nginx, you can add this in your /etc/nginx/nginx.conf:

```
rtmp {
  server {
        listen 1935;
        chunk_size 4096;
        
        application live {
                live on;
                interleave on;
                record all;
                record_path /a/path/where/to/record/;
                record_unique on;
        }
    }
}
```

With this config, nginx will record any RTMP stream in the chosen folder. So you can easily check if it is nginx or peertube that receive the stream (if there is something recorded, it is nginx, otherwise it is peertube).

**Describe the expected behavior**
Peertube should detect that the port is already in use, log an error, and crash.

**Additional information**

* PeerTube instance:
  * version: 3.0.0

**Comment by rigelk** [comment]
Or simply run `lsof -i:1935`.

**Comment by JohnXLivingston** [comment]
> Or simply run `lsof -i:1935`.

I think you misunderstood me. 
My case is on a service that has already a RTMP service, which has nothing to do with peertube. The nginx conf that I gave is an easy way to reproduce the bug. 
When a such service is already running, and if we don't change the peertube's RTMP port, Peertube starts without any error, but his RTMP service will not work (and I suppose that if Peertube's run before the other service, then the other service will crash). 
Peertube should detect that the port is not available, and write an error log.


PS: the install/upgrade documentation should mention that the live service will use the port 1935, and that it can be changed in the configuration file. When I upgraded to v3.0.0, I only read the CHANGELOG and the diff on production.yaml file. I did not see the RTMP port in file default.yaml. And as I had already a RTMP service running....

**Comment by rigelk** [comment]
> The nginx conf that I gave is an easy way to reproduce the bug.

I know, it’s not meant to replace all your instructions, just a simpler way to check than reading the logs produced by Nginx.

> PS: the install/upgrade documentation should mention that the live service will use the port 1935, and that it can be changed in the configuration file. When I upgraded to v3.0.0, I only read the CHANGELOG and the diff on production.yaml file. I did not see the RTMP port in file default.yaml. And as I had already a RTMP service running....

That's already been added to the documentation, but the RTMP port is not customizable in PeerTube as of now. Please open another issue for this.

**Comment by JohnXLivingston** [comment]
> I know, it’s not meant to replace all your instructions, just a simpler way to check than reading the logs produced by Nginx.
> 

Oops, sorry. 


> That's already been added to the documentation, but the RTMP port is not customizable in PeerTube as of now. Please open another issue for this.

I don't need the port to be customizable for now, I changed the port for the other service. Are you sure that it is not customizable? There is a config key live.rtmp.port that seams to be used.

**Comment by rigelk** [comment]
> > That's already been added to the documentation, but the RTMP port is not customizable in PeerTube as of now. Please open another issue for this.
> 
> I don't need the port to be customizable for now, I changed the port for the other service. Are you sure that it is not customizable? There is a config key live.rtmp.port that seams to be used.

Can be, I didn't write the code! ^^

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/c2b823826db167594f8157b0b324b6fb1559caeb
