### ISSUE TITLE
Broken npm links in list of themes

### ISSUE THREAD

**Issue by forzagreen** [Chocobozzz/PeerTube#3565]
**Current behavior**

In the list of themes, the link to npm registry points to `'https://www.npmjs.com/package/peertube-plugin-' + plugin.name` instead of `'https://www.npmjs.com/package/peertube-theme-' + plugin.name`

**Steps to reproduce:**

1. As an admin, go to Administration
2. Go to Plugins/Themes -> Search -> Themes
3. Pick any item in the list. The npm icon points to a wrong URL

**Describe the expected behavior**

The URL must point to `'https://www.npmjs.com/package/peertube-theme-' + plugin.name`

**Additional information**

* PeerTube instance version: 3.0.0
* Lines of code to be fixed: 

https://github.com/Chocobozzz/PeerTube/blob/eaf3367549f7e12d464c0fda5251640209e924cd/client/src/app/%2Badmin/plugins/plugin-search/plugin-search.component.html#L44

https://github.com/Chocobozzz/PeerTube/blob/eaf3367549f7e12d464c0fda5251640209e924cd/client/src/app/%2Badmin/plugins/plugin-list-installed/plugin-list-installed.component.html#L21

**Comment by 96RadhikaJadhav** [comment]
@forzagreen  Can I work on the issue?

**Comment by forzagreen** [comment]
@96RadhikaJadhav Yes you can. From my side, I haven't started working for it.
Thanks !

**Comment by Chocobozzz** [comment]
Thanks @96RadhikaJadhav & @forzagreen, I fixed this in https://github.com/Chocobozzz/PeerTube/commit/078b4716cdd4dbf1b15c1a864ccab999ed3d0e8e
