### ISSUE TITLE
Include key in stream URL in livestream modal

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3568]
**Describe the current behavior**
currently the live stream live information modal displays rtmp url and stream key in two separate boxes because services like OBS expect them in separate boxes.

the issue is services like jitsi meet and even android rtmp servers show a single input box where the user is expected to input rtmp url followed by "/" and then stream key.
this ui quirk is not explained by the live information modal in peertube and this leads to people only putting rtmp url in the box without the key.

**Describe the expected behavior**

my suggestion is to add the following to the live information modal,

If your live streaming software has only one input box, you must put your Live RTMP Url and Live stream key in the following manner:
Live RTMP Url/Live stream key

![Screenshot_20210109_221149](https://user-images.githubusercontent.com/39449563/104103393-e2161680-52c7-11eb-9fa0-15d6198fc0d0.png)
![Screenshot_20210109_221209](https://user-images.githubusercontent.com/39449563/104103395-e3dfda00-52c7-11eb-824b-0780b8080e4c.png)

https://github.com/jitsi/jitsi-meet/issues/8283#issuecomment-757138230
this comment is the example of this ux quirk.

**Comment by rigelk** [comment]
I don't think the UX problem stems from us here, but rather from Jitsi’s reliance on YouTube as a default and thus hiding what should be another field: the live stream URL.

Covering that special case by adding it in our documentation examples should be enough IMHO.

**Comment by test2a** [comment]
here. i took screenshots of two android RTMP stream apps. here too there is just one input box and it does only say "RTMP url"
and neither mention using stream key. 


![Screenshot_20210110-000937](https://user-images.githubusercontent.com/39449563/104106031-8bfd9f00-52d8-11eb-973e-16731f98430c.png)
![Screenshot_20210110-001051](https://user-images.githubusercontent.com/39449563/104106032-8d2ecc00-52d8-11eb-9428-cb34d75f35f4.png)

**Comment by test2a** [comment]
ok. the documentation seems to be updated to jitsi meet but we need to either tell the users to put url/key when there is just one box like in the case of android streamers or provide that ourselves in the information box.

**Comment by Chocobozzz** [comment]
I agree with @rigelk. It seems to be an UX issue from these software, because the URL is public whereas the stream key must be private. We could add another field that merges the base RTMP URL and stream key, but it would be just more confusing for users.
