### ISSUE TITLE
add comparative/relationship to similar projects

### ISSUE THREAD

**Issue by earizon** [Chocobozzz/PeerTube#3569]
**Explain whethere PeerTube has (or plans to have)some relationship  with other similar projects, an in particular https://www.thetatoken.org/ **

https://github.com/Chocobozzz/PeerTube/blob/develop/README.md

**CONTEXT:
I'm an outsider to the project but still interested in related projects. I have 1 minute to read the README.md and forget for always. Some context on how this project relates to similars ones makes easier for me to remember in a future. **

**Comment by rigelk** [comment]
Please don't tag your issue title yourself, especially when you selected a different issue template.

**Comment by rigelk** [comment]
@earizon we answer our relationship with other projects in https://github.com/Chocobozzz/PeerTube/blob/develop/FAQ.md#why-did-you-create-peertube. As for your particular question, https://github.com/Chocobozzz/PeerTube/blob/develop/FAQ.md#are-you-going-to-use-the-steem-blockchain short version applies here.
