### ISSUE TITLE
"Videos" and "Video channels" links don't return the AP object

### ISSUE THREAD

**Issue by drequivalent** [Chocobozzz/PeerTube#3573]
**Describe the current behavior**
When going to the account or channel, the user gets redirected to the pages with URIs like this:

`https://video.pony.gallery/accounts/zg/video-channels`
`https://video.pony.gallery/video-channels/zloygik/videos`

When pasted into the Mastodon's search bar, Mastodon doesn't import the account or channel they're referring to.

**Steps to reproduce:**

1. Go to channel or account
2. Copy link
3. Paste it into the search bar

When queried with curl like this:

`curl -H Accept:application/activity+json https://video.pony.gallery/accounts/zg/video-channels | jq`

they return nothing as well.

Removing the last portion helps. This returns the object:

`curl -H Accept:application/activity+json https://video.pony.gallery/accounts/zg/ | jq`

**Describe the expected behavior**

The expetation is, that the user can copy whatever link is in their address bar right now and get the AP representation of the object which they can easily import. This doesn't happen here.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/70fdff3d4e140d19587e7ea9e40c021185b06a9a
