### ISSUE TITLE
HLS Videos don't playback on Android.

### ISSUE THREAD

**Issue by akoyaxd** [Chocobozzz/PeerTube#3575]
If Videos are only available via HLS they do not playback on Android. Tested with Chrome, Firefox and NewPipe.
The Webpage does load fine but the Video doesn't play back. It only buffers without even showing the time code or in case of NewPipe I get a parsing error.

**Steps to reproduce:**

1. Install Peertube
2. Configure Peertube to only transcode to hls
3. Try to playback an uploaded Video on the Android via Browser or NewPipe.

**Describe the expected behaviour**
I can view the Video from an Browser on Android or via Newpipe.

**Additional information**
Videos uploaded after enabling Webtorrent play just fine.
Is this a regression in hls or is the some wrong configuration on my side?

I use Nginx native installed on Debian 9 from the official Debian repositories as a reverse Proxy.
Peertube is installed in a Docker Container.

Video only available with HLS:
https://tube.koyax.org/videos/watch/61873ac0-f726-46ad-a833-c341601fe01b

Video only available with Webtorrent:
https://tube.koyax.org/videos/watch/b0fd84cc-77bf-470b-bea2-f2d7159ba47c

* PeerTube instance:
  * URL: https://tube.koyax.org/
  * version: 3.0
  * NodeJS version: (Docker)
  * Ffmpeg version:  ffmpeg version 4.1.6-1~deb10u1 (from Docker Container)

* Browser name, version and platforms on which you could reproduce the bug: Firefox, Chrome, NewPipe
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by rigelk** [comment]
hi @akoyaxd, could you provide ffmpeg and browser versions?

**Comment by test2a** [comment]
The hls video works on tubelab and Firefox focus but not newpipe for me. Strange.

**Comment by SimplyCorbett** [comment]
I have no issues playing with HLS only on android on my instance.

**Comment by akoyaxd** [comment]
> hi @akoyaxd, could you provide ffmpeg and browser versions?
 ffmpeg version 4.1.6-1~deb10u1  (added to op)

The NewPipe Version is 0.20.8
Firefox (Android) Version: 84.1.2 (Fennec from F-Droid)

**Comment by SimplyCorbett** [comment]
Can you try with ffmpeg 4.3.1 (no idea if it will fix it, though).

Static builds are here - https://johnvansickle.com/ffmpeg/

**Comment by akoyaxd** [comment]
Sorry to say that: I can't reproduce the error again.
I just reuploaded the Video, that I had issues with at the beginning and it now plays in Firefox for me.
I guess something went wrong for the first upload I don't know...
Sorry for bothering you guys!

NewPipe doesn't seem to support hls at all, but that is no PeerTube issue I guess..

**Comment by rigelk** [comment]
> NewPipe doesn't seem to support hls at all, but that is no PeerTube issue I guess..

Thanks for reporting it, I wasn't aware. This is unfortunate, as they don't make any warning about it and always assume a playable video is available…
