### ISSUE TITLE
Twitter username isn't optional

### ISSUE THREAD

**Issue by prplecake** [Chocobozzz/PeerTube#3578]
**Describe the current behavior**
Twitter username isn't actually optional even though the help text says it is.

**Steps to reproduce:**

1. Edit instance configuration.
2. Remove twitter username
3. Observe configuration claims it's invalid.

<img width="666" alt="Screen Shot 2021-01-10 at 17 55 14" src="https://user-images.githubusercontent.com/1626427/104139348-789e1280-5370-11eb-9f8b-f6b2a49de59c.png">

**Describe the expected behavior**
Twitter username should be optional as the help text describes.

**Additional information**

* PeerTube instance:
  * URL:
  * version: 3.0.0
  * NodeJS version: 10.23.1
  * Ffmpeg version: 4.1.6-1~deb10u1

* Browser name, version and platforms on which you could reproduce the bug: Firefox 84.0.1, macOS Big Sur
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/f8be7bae3fa70e5402bc1b32c0c4865b8b5db97e
