### ISSUE TITLE
Peertube-cli upload magnet link support

### ISSUE THREAD

**Issue by omernaveedxyz** [Chocobozzz/PeerTube#3579]
**Describe the problem to be solved**
Maybe my use-case is a little unique, but I've actually got a list of torrent videos that I would like to upload through the cli as there are quite a few and going one-by-one through the ui will take too long.

**Describe the solution you would like:**
A way to use the peertube-cli to upload a file using a magnet link.

My current solution will be to download the torrents as videos to a directory on my server and then upload them to Peertube using the cli. This is doable, but not ideal.

**Comment by Chocobozzz** [comment]
Hello,

Please use the dedicated REST API to import magnet links because we don't plan to create a dedicated CLI tool for import: https://docs.joinpeertube.org/api-rest-reference.html#tag/Video/paths/~1videos~1imports/post
