### ISSUE TITLE
Make a video available only to following instances

### ISSUE THREAD

**Issue by lucas-dclrcq** [Chocobozzz/PeerTube#358]
* **PeerTube version or commit:** 1.0.0-alpha.8

* **What is the expected behaviour?** I think it would be great to have the possibility to make a video available only to instances that follow you (and also to have to manually accept instances that wants to follow you for that matter)
* **What do you see instead?** When I upload a video to my instance I can only make it private, unlisted or public. I can't restrict visibility only to instances that follow me.

**Comment by Chocobozzz** [comment]
I don't see an use case for such thing. And I'm afraid that would confuse regular people that don't understand completely what is a federation.

Moreover, in the future users will be able to follow instances/channels/users so what about this privacy setting? Would it restrict the video only to follower instances? Or to follower users too?

**Comment by lucas-dclrcq** [comment]
What I want to be able to do is to restrict the visibility of a video to only servers that are in my federation.
But restrict the visibility to a certain group of users would also work, is this something that you'll maybe want to implement ?

**Comment by Chocobozzz** [comment]
No, I don't want to add other privacy settings for now. We would like to keep things as simple as possible for regular users. And we don't really want to add the ability to choose what instances follow you.

**Comment by AntoineMazuyer** [comment]
Hello, I have a side questions.

Is it possible to make a video which will be visible only for the users who are logged on the instance ? (for example I would like to have an instance for my family, and I dont want other users to see the videos)

thanks !
