### ISSUE TITLE
Custom homepage for admins

### ISSUE THREAD

**Issue by LukeSmithxyz** [Chocobozzz/PeerTube#3582]
This might be a sort of niche request, but I have an instance where I store my own videos. On my main page, I would really like to be able do direct viewers to featured playlists or videos. As of now, there are categories for "Trending", "Most Liked", "Local videos", etc. but what I'd really want is to be able to showcase particular videos and playlists that might be much older, but more foundational. I.e. tutorial playlists and stuff that are linear, etc.

So really I'm asking for an alternate page that can serve as the mainpage where the instance owner has more fine-grained control over what appears. Imagine a line or so of trending videos and then a couple lines of videos below of playlists to directly pick from, all of this can be chosen by the admin.

**Comment by EricGuic** [comment]
Hi, (first steps on Github, so be kind if I don't respect the way people usually act here).
I'm a french movie director, working in the education area (and you've guest that english isn't my first skill ;-)

I will try to translate here some of the enhancement I've imagined for better organize videos on Peertube.
I think Peertube's admin lacks a way to featured chosen videos/channel/playlist to their audience.

We could have a plugin allowing us to create a "Featured page" (which could be the landing one). This page could support simple formatting functions to allow texte and image formatting, embed of video and playlist, etc. (see the visual example below).
This page could re-use the "tab" organization that already existed in the "about" section of Peertube.

The main objective is to featured a short lists of videos, with a minima contextual information through text.

One picture is worth a thousand words (specially when they came from a french speaker ;-)
![Peertube-page-éditorialisée-sommaire-à-la-une](https://user-images.githubusercontent.com/81166671/111993949-7fd36080-8b17-11eb-991c-7c962c162baf.jpg)

![Peertube-page-éditorialisée-1](https://user-images.githubusercontent.com/81166671/111993969-85c94180-8b17-11eb-8c2a-5f039cae1e1f.jpg)

**Comment by TROMsite** [comment]
In the meantime one can easily redirect the homepage and the landing page to any url as such:

Go to your Nginx config file for Peertube. For me, using Yunohost, it is `/etc/nginx/conf.d/videos.trom.tf/peertube.conf` . On the very bottom add:
```
rewrite ^/$ /video-channels/trom redirect;
  rewrite ^/videos/overview$ /video-channels/trom redirect;
```

And of course replace "/video-channels/trom" with a URL of your choice, and "overview" with whatever page is setup as the landing page in your admin settings.

Restart Nginx. Done.

Of course the best option would be what @EricGuic  have said. A simple HTML template where admins can add featured videos/playlists. I am sure this would improve the PeerTube experience hugely.

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/aea0b0e7cde7495e60fe07b4444067f53d35ce3f

**Comment by toon462** [comment]
ในวันที่ ศ. 14 พ.ค. 2021 18:38 น. Chocobozzz ***@***.***>
เขียนว่า:
