### ISSUE TITLE
Video not playing or downloadable

### ISSUE THREAD

**Issue by Sesshoumaru-sama** [Chocobozzz/PeerTube#3584]
I am hosting PeerTube (based on YunoHost / latest version) in a ProxmoxVE virtual machine to get to know the software. Its a standalone instance. I made it publically available using dynamic DNS serivice and placed it on port 40004 (beause 80 is already taken). With that said, I cannot playback any videos, neither download them.

However, I noticed that in the download link the port information is missing so its just the domain without the port. If I add the port then its downloading fine. I guess the online player has the same issue, a missing port.

Can somebody point me to a solution for this? I guess the port "just" has to be added when generating the HTML page.

**Comment by Chocobozzz** [comment]
Hello,

Please fill the template and provide your instance URL

**Comment by Sesshoumaru-sama** [comment]
**Steps to reproduce:**
1. Install PeerTube on a domain when a port is used to access it

**Describe the expected behavior**
Videos are playing

**Additional information**
Private Instance for experimentation.
Dyn-Dns domain with access over sub-domain.
Video is not playing, but the all other parts of the site seem to be fine.

* PeerTube instance:
  * URL: 		        https://pvc9rew6lfwhqhjz.myfritz.net:40004/
  * version:		2.4.0~ynh1
  * NodeJS version:	v12.20.1
  * Ffmpeg version:	4.1.6-1~deb10u1

* Browser name, version and platforms on which you could reproduce the bug:
Chrome, FireFox, IE, ...

**Comment by Sesshoumaru-sama** [comment]
I drilled it down to /server/models/video/video.ts
There is a method getBaseUrls () {...} where the baseUrlHttp propert is generated from the WEBSERVER.URL alone. If I forcefull add my port 40004 to the base-uri then the videod plays and the download links work. The WEBSERVER.PORT property points to 443 which obviously is the SSL port. So the request port of the page that created the outputted HTML page would be the correct port.

I assume I am doing something special here, but I still think it should work. So getting the actual port from the request is now the crucial part. PS: My server is not up all the time, sorry in case you cannot access the instance.

**Comment by Chocobozzz** [comment]
If your instance URL is `myinstance.com:40004` then the port value in your configuration should be `40004`: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L9

**Comment by Sesshoumaru-sama** [comment]
That seems to have done the trick, plus I had to do some creative port-forwording.
Now the videos are playing fine, but I get a message at each first page access:
"Cannot retrieve OAuth Client credentials"

Is there something I have to do to get rid of this? Thanks for you help 👍

**Comment by Chocobozzz** [comment]
I'm not sure to understand. Does nginx listen on 40004 or on 443?

**Comment by Sesshoumaru-sama** [comment]
I expose the PeerTube on my public IP on port 40004 and then its forwarded internally through two routers until it reaches the virtual machine hosting the service on port 443.

**Comment by Chocobozzz** [comment]
I'm sorry but if I cannot access to your instance it's difficult for me to understand why it fails. Please ask to reopen when you'll have a running instance behind a DNS name I can test.
