### ISSUE TITLE
IPFS & Unstoppable Domains

### ISSUE THREAD

**Issue by trymeouteh** [Chocobozzz/PeerTube#3585]
Have peertube servers be able to interact with IPFS and unstoppable domains to allow anyone on the clear web using a clear web peertube instance to watch and connect with videos from IPFS or an unstoppale domain on IPFS.

Any Peertube instance can be hosted on IPFS, Unstoppable Domains on IPFS, and allow the clear web to be able to connect to IPFS Peertube instances without needing to install any software since the Peertube server can handle the work.

Or even if Peertube can be hosted on IPFS and Unstoppable Domains on IPFS would be good if that means users will need to find a way to connect to IPFS to connect to an IPFS instance.

**Comment by rigelk** [comment]
Hi! Please look out for related issues before creating one, as #494 already covers this. You can then detail further your use case there, and upvote the issue to help us triage it.
