### ISSUE TITLE
[Docker] The data directory was initialized by PostgreSQL version 10, which is not compatible with this version 13.1

### ISSUE THREAD

**Issue by silvernode** [Chocobozzz/PeerTube#3588]
**Describe the problem**
Postgres fails to connect due to an incompatible version which was updated in the latest images.

**Additional information**
I had been running a 6 month old .env and docker-compose.yml files and only doing git pull this whole time. To get live streaming working correctly I needed to read the docker installation docs again which walked me step by step in creating the proper volume paths, entering my database connection information, etc. I followed those steps and ran a diff on the .env to make sure my database information and domain was correct. The ONLY problem I am having at this point is the incompatible postgres version with my current database. I am not sure if I am supposed to dump and migrate my database manually or if the compose file is supposed to take care of that. Nobody else has submitted an issue on this that I could find recently. Sorry if this is a trivial issue, I am still quite new to docker. Thanks for all the hard work. 

* PeerTube instance:
  * version: 3.0.1-docker

  * NodeJS version: N/A
  * Ffmpeg version: N/A
  * Redis version: N/A
  * PostgreSQL version: 13

Files: [errors.txt](https://github.com/Chocobozzz/PeerTube/files/5802462/errors.txt)

**Comment by rigelk** [comment]
Hi @silvernode,

> I am not sure if I am supposed to dump and migrate my database manually or if the compose file is supposed to take care of that.

Yes, you have to take care of that manually. I wish an automated way was included, but this is arguably a PostgreSQL issue. Surely https://github.com/Chocobozzz/PeerTube/pull/2531#discussion_r386957024 can help.

**Comment by silvernode** [comment]
> Hi @silvernode,
> 
> > I am not sure if I am supposed to dump and migrate my database manually or if the compose file is supposed to take care of that.
> 
> Yes, you have to take care of that manually. I wish an automated way was included, but this is arguably a PostgreSQL issue. Surely [#2531 (comment)](https://github.com/Chocobozzz/PeerTube/pull/2531#discussion_r386957024) can help.

Oh ok then, well thanks for the quick response and have a great day. :)
