### ISSUE TITLE
Align .videos on left ?

### ISSUE THREAD

**Issue by DavidLibeau** [Chocobozzz/PeerTube#359]
I much like to align the videos on the left (currently centered). What do you think?

![screenshot-2018-3-16 local videos - peertube](https://user-images.githubusercontent.com/11574966/37542512-55453486-2956-11e8-8be9-6f8013f755ff.png)

**Comment by Chocobozzz** [comment]
It would result in a lot of blank space on the right depending on the client resolution:

https://lutim.cpy.re/gallery#fAhgumFR.png,01yNcK45.png

**Comment by DavidLibeau** [comment]
Considering #363, do you think we might use something like CSS Flexbox or Bootstrap grid system ?

**Comment by Chocobozzz** [comment]
Closing this because I think there would be too much space on the right :)

**Comment by DavidLibeau** [comment]
Hi, I reopen this old issue because the `/videos/overview` videos are aligned on the left and the other pages are not. I think it could be cool to have the same alignement on all pages.

**Comment by rigelk** [comment]
The issue of extraneous space would be fixed by #2830, which would incidentally solves this issue.
