### ISSUE TITLE
Not logged in when opening comment in new tab

### ISSUE THREAD

**Issue by sunknudsen** [Chocobozzz/PeerTube#3591]
**Describe the current behavior**

I am a [content creator](https://peertube.sunknudsen.com/accounts/sunknudsen/video-channels).

When I open comment in new tab (using right click in bell or "see all your notifications" view), I am no longer logged in (in the context of new tab).

**Steps to reproduce:**

![preview](https://user-images.githubusercontent.com/2117655/104379198-0c164580-5521-11eb-9cf3-1551d669e553.gif)

**Describe the expected behavior**

I expected to be logged in when opening comment in new tab.

**Additional information**

* PeerTube instance:
  * URL: https://peertube.sunknudsen.com
  * Version: 3.0.1
  * NodeJS version: v12.18.2
  * ffmpeg version: 4.1.4-1~deb10u1

* Browser name, version and platforms on which you could reproduce the bug: Firefox 84.0.2 (64-bit) on macOS Catalina 10.15.7

**Comment by test2a** [comment]
Oh. This happens to me in a private window

**Comment by Chocobozzz** [comment]
Hi,

Could you try with another web browser?

**Comment by sunknudsen** [comment]
@Chocobozzz Found the culprit... it appears to be a Firefox bug.

This edge case occurs when "Delete cookies and site data when Firefox is closed" is enabled in `about:preferences#privacy`.

Allowing `https://peertube.sunknudsen.com/` in "Manage Exceptions..." "fixes" the issue (while being less private and secure).

Do you believe this is a Firefox bug or am I missing something?

**Comment by test2a** [comment]
uh.. i only use firefox and shouldnt this be until for example an entire private window is closed? does it assume in private mode at least each tab to be separate but then other apps work correctly across a private window so i dont know what i am talking about....

**Comment by sunknudsen** [comment]
@test2a See updated [comment](https://github.com/Chocobozzz/PeerTube/issues/3591#issuecomment-759389716).

My gut feeling is this issue is caused by PeerTube using local storage rather than cookies to store authentication data.

**Comment by test2a** [comment]
@sunknudsen i have had this crazy idea for so long now. you know how we cannot subscribe to remote instances right now without having to resolve to pasting the video url in search and if it plays, then subscribe trick. well i thought if we click on subscribe button, it could check local storage for a peertube identifier, if found, it would resolve that remote instance and do the above trick by itself programatically and for the user it would happen as if i can subscribe to any channel with my logged in instance.

**Comment by Chocobozzz** [comment]
> My gut feeling is this issue is caused by PeerTube using local storage rather than cookies to store authentication data.

Yes and this is the appropriate way to store user tokens. We don't want to send them using cookies.

**Comment by sunknudsen** [comment]
@Chocobozzz

> Yes and this is the appropriate way to store user tokens. We don't want to send them using cookies.

Agreed, but PeerTube could also read cookies and send authentication data using the HTTP `Authorization` header... right?

This would allow us to use PeerTube on hardened browsers or in private mode which, I believe, is aligned with the user base of PeerTube which is likely privacy-conscious.

Is there a problem with the above approach from a security perspective?

**Comment by Chocobozzz** [comment]
It's not the purpose of cookies. We don't want to send them on every requests to the server. And I don't think using cookies will resolve your issue. Maybe peertube cannot access to your local storage and just store tokens in memory.
