### ISSUE TITLE
RSS Feed for account subscription broken

### ISSUE THREAD

**Issue by trymeouteh** [Chocobozzz/PeerTube#3595]
This is what is copied when I click on the RSS button in my subscriptions feed when I am logged into my account.

/feeds/subscriptions.xml?accountId=12345&token=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

it is missing the website domain at the front and should look like this.

libre.video/feeds/subscriptions.xml?accountId=12345&token=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

Tried this on libre.video. This button should copy the fill and working RSS feed of ones Peertube account subscription feed which can allow one to get their subscription feed in an RSS format and not needing to login to Peertube.

**Comment by rigelk** [comment]
This is already fixed in 04b2996bb0d7407ff500ab39fadd8e5b596c05e2 available in 3.0.1.
