### ISSUE TITLE
Some video's problems

### ISSUE THREAD

**Issue by imtube** [Chocobozzz/PeerTube#36]
Hello,
Some videos can be watch but some can't, they are all mp4 files, why is that ?
And the limitation of video's duration is 7200s, Can I change it ?
It looks like only mp4 file can be uploaded successfully, Can I add some other file format? avi for example.

**Comment by Chocobozzz** [comment]
See https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats for the formats supported by the browsers.

AVI or MKV for example are not compatible. See http://stackoverflow.com/a/31156790.

The video limitation cannot be changed for now.
