### ISSUE TITLE
Improve modal for downloading subtitles

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#3600]
**Describe the problem to be solved**

A user came to me because he thought that the subtitles were missing on a downloaded video. 
In fact, there are 2 problems:

- it is not obvious that the subtitles are in separate files
- the button for downloading the subtitles is hard to find. We have to click on the download popup title: 
![image](https://user-images.githubusercontent.com/38844060/104639318-8ffa3a00-56a7-11eb-8877-82bab5f20929.png)

**Describe the solution you would like:**
If subtitles are present and activated, the download popup should mention that there are separate subtitles files. 
The button to switch to the subtitles download popup could be added next to this warning.

**Describe alternatives you have considered** 
Another solution would be to add a «subtitles» tab in the popup.

Or to add the content of the actual subtitles download popup directly under the video download popup.

**Comment by tdelmas** [comment]
Or, when subtitles are available, create a zip file with the video and subtitles (ideally with a name/path that makes them detectable by software such as VLC, for example in a `subtitles` folder) ? 

Or better, directly include them in the video file if/when the video format supports it.

**Comment by Chocobozzz** [comment]
Hi,

We recently changed the title to have a `<select>` than I think is more explicit than the previous dropdown. What do you think?

**Comment by JohnXLivingston** [comment]
Good enough for me. Thanks!
