### ISSUE TITLE
Unable to copy user subscription feed link

### ISSUE THREAD

**Issue by sanpii** [Chocobozzz/PeerTube#3601]
**Describe the current behavior**

I couldn’t get my subscription feed link.

**Steps to reproduce:**

1. Go to /videos/subscriptions
2. Click on the feed button

**Describe the expected behavior**

Gets the link in my clipboard.

**Additional information**

* PeerTube instance:
  * URL: https://tube.homecomputing.fr
  * version: 3.0.1
  * NodeJS version: v10.23.1
  * Ffmpeg version: 4.1.6-1~deb10u1

* Browser name, version and platforms on which you could reproduce the bug: Firefox 84.0.2 (with hardened [configuration](https://github.com/arkenfox/user.js/)) on archlinux
* Link to browser console log if relevant:
```
Réussite: Url du flux copiée
⚠️ document.execCommand(‘cut’/‘copy’) was denied because it was not called from inside a short running user-generated event handler.
```
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): N/A

This bug is probably due to my browser configuration, but is it possible to add an `href` on the link to let me gets this link?

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/7af5ded409c50f4f19a220cea36a8bbd16b0be24

**Comment by sanpii** [comment]
Thank you :smiley:
