### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#3602]
I have selected the Russian interface language, everything is fine, but I cannot translate something, because this line is missing. Interested in exactly 7 days!

Only available in the last 24 hours.

![lang1](https://user-images.githubusercontent.com/11453567/104688491-e603c780-5711-11eb-8737-e154e7992d72.png)
![lang2](https://user-images.githubusercontent.com/11453567/104688505-f025c600-5711-11eb-9613-b7de4b078efd.png)

https://weblate.framasoft.org/translate/peertube/angular/ru/?offset=1&q=Trending+videos+are+those+totalizing+the+greatest+number+of+views+during+the+last&sort_by=-priority%2Cposition&checksum=

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/f19a9e4b68f581610badcbb888727470d8c095b4
