### ISSUE TITLE
Markup problem

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#3603]
Peerube v.3.0.1

If the interface language is Russian, the titles in the "Blocked Videos" section are not displayed correctly.
But if you choose the interface language - English, then everything is displayed correctly.

![tab1](https://user-images.githubusercontent.com/11453567/104689370-77276e00-5713-11eb-9d23-9f3d35033fdd.png)
![tab2](https://user-images.githubusercontent.com/11453567/104689384-7bec2200-5713-11eb-833d-88cb8320766a.png)

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/b0a9743af0273835cdf594431a774c0f7d46b539
