### ISSUE TITLE
Transcoding old videos

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#3604]
Previously, I only had 1080p and 720p transcoding enabled. Now I have a lot of free space and I have activated the optional 480p, 360p, 240p transcoding. But Transcoding with this resolution will be available only for new videos.
Is there a way to force the processing of all videos that are on the server?

**Comment by Chocobozzz** [comment]
Hi,

There's no automatic method but you can try https://docs.joinpeertube.org/maintain-tools?id=create-transcoding-jobjs
