### ISSUE TITLE
Update nodejs to latest LTS

### ISSUE THREAD

**Issue by iamdoubz** [Chocobozzz/PeerTube#3605]
**Describe the problem to be solved**

The suggested nodejs version is 10. The EOL on this release is [this year end of April](https://nodejs.org/en/about/releases/). 

**Describe the solution you would like:**

Upgrade existing infrastructure to support the latest LTS, currently 14, which has support until [April 2023](https://nodejs.org/en/about/releases/).

**Describe alternatives you have considered**  

I currently use, even though not officially supported, nodejs version 12. I now have several other modern programs that require at minimum 14, we has forced me to learn [how to use **nvm**](https://github.com/nvm-sh/nvm) so that Peertube can still use version 12 while everything else I run uses the latest LTS.

Thank you for a wonderful product and cannot wait to see what this project comes up with next!

**Comment by rigelk** [comment]
hi @iamdoubz and thanks for your interest in PeerTube!

Unfortunately, PeerTube is capped at version 13 by one of its dependencies. You can read more in the related issue: https://github.com/Chocobozzz/PeerTube/issues/2700#issuecomment-624013824
