### ISSUE TITLE
Airplay and Chromecast support

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3606]
**Describe the problem to be solved**
We've a lot of users asking for chromecast support. I'm not familiar with that kind of devil devices but after some research I understand that there's a browser API that you can talk to to make it possible to cast a specific video stream to the chromecast.

**Describe the solution you would like:**
I found that there's a video.js plugin for [Chromecast](https://github.com/silvermine/videojs-chromecast) and [Airplay](https://github.com/silvermine/videojs-airplay).

Would it be welcome with a PR to add those plugins?

**Comment by rigelk** [comment]
Maybe add them as default plugins? Or suggested plugins at install? But I don't see them integrated in the default player code.

**Comment by rigelk** [comment]
Partial duplicate with https://github.com/Chocobozzz/PeerTube/issues/2430 (chromecast plugin request)

Please create a dedicated issue for Airplay.
