### ISSUE TITLE
Import with URL publishes the video as soon as it is imported

### ISSUE THREAD

**Issue by Sakrecoer** [Chocobozzz/PeerTube#3609]
**Describe the current behavior**
When importing videos with URL the video is published immediately after importation, meaning it's activity is pushed out to the public before any editing is saved to the video title, caption and meta-data and **most importantly without letting the user set the NSFW settings.**

**Steps to reproduce:**

1. Click publish and chose "import with URL"
2. Leave everything as is in the next step (basic info).
3. Open a new tab and navigate to your library: find you're video published.
4. If you follow your own account somewhere on fediverse, find it published there too.

**Describe the expected behavior**
Peertube should wait for me to hit "update" button before publishing the video: it might contain sensitive content and this should be taken into account before being pushed to the entire fediverse network.

**Additional information**
Work arround: Selecting "Private" on the page where you can input the URL to be imported will allow you to do changes before publishing.

* PeerTube instance:
  * URL: v.basspistol.org
  * version: 3.0.1
  * NodeJS version: v10.19.0
  * Ffmpeg version: 4.2.4-1ubuntu0.1

**Comment by Chocobozzz** [comment]
Thanks for the issue. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/d487a997c80fafe6067016c6cd8e8afd6141baa3
