### ISSUE TITLE
Request entity too large for stream thumbnail

### ISSUE THREAD

**Issue by f0x52** [Chocobozzz/PeerTube#3611]
**Describe the current behavior**
Setting a video preview under a stream's advanced settings says it allows 2MB max, but it's not special cased in the default nginx config, hence failing on `PUT /api/v1/videos/1` because that allows 1MB max

**Steps to reproduce:**

1. default nginx+peertube 3.0.1 config
2. upload stream video preview > 1MB < 2MB
3. UI allows this, clicking Update gives a 413 on bottom right popup

**Comment by Chocobozzz** [comment]
@f0x52 Could you confirm updating your nginx config like in https://github.com/Chocobozzz/PeerTube/commit/111e6c1807dac4230014bd295118c6b3a51be8f5 fixes your issue?
