### ISSUE TITLE
Advanced configuration tab is empty with german interface language.

### ISSUE THREAD

**Issue by Stormkoopa** [Chocobozzz/PeerTube#3615]
As an administrator, if I look into the advanced configuration tab of my instance with german interface language. The site, where usually the fields for custom CSS and JavaScript, aswell as cache configuration options are located, is empty with the "Update configuration" button being the only thing displayed.

Is it a known bug or an issue with the transalation, or else?

**Comment by Stormkoopa** [comment]
Note: That occured just after I updated my instance to v3.0.0. I just recently discovered that by changing the language to english it fixed this problem.

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/c59eab78052cc8bbe02cb9dd03e8fb525b61fbac
