### ISSUE TITLE
Unable to follow from mastodon "SequelizeValidationError: Validation error"

### ISSUE THREAD

**Issue by PhieF** [Chocobozzz/PeerTube#362]
* **PeerTube version or commit: ** /var/www/peertube 
* **Browser name/version:** firefox 59.0.1
* **NodeJS version:** v8.10.0
* **PostgreSQL version:**  9.5.12

* **What is the expected behaviour?** following from mastodon should work
* **What do you see instead?** it's sending an invitation, not able to accept it from peertube

* **Server log if useful (Gist/Pastebin...):** https://framabin.org/?dc53cebc93b36fa3#TsuUs4zi2RCsGmR4u+sf7Gxn/ElgJUMNix+4fiWRedU=

It could perhaps come from my shitty mastodon username : 𝓟𝓱𝓲𝓮
I know, bad.

But the log seems to be more about the description of the following account.

Any ideas ? Thanks !

**Comment by Chocobozzz** [comment]
Fixed: https://github.com/Chocobozzz/PeerTube/commit/f47776e265a45859aaf8519d7de85c6f35fdf40a
