### ISSUE TITLE
Titles do not trim leading and trailing spaces.

### ISSUE THREAD

**Issue by kyrahabattoir** [Chocobozzz/PeerTube#3623]
**Describe the current behavior**

**Steps to reproduce:**

1. Upload/Edit video properties
2. Type two characters as name (note that peertube will not allow it)
3. Add a space at the end of the title (peertube title length now satisfied)

**Describe the expected behavior**

Leading and trailing blank spaces should be removed/shouldn't count for minimum title length.

**Comment by shubham-kumar10** [comment]
@rigelk @kyrahabattoir Can I look into this issue?

**Comment by rigelk** [comment]
Yes, of course
