### ISSUE TITLE
Open videos in original instance

### ISSUE THREAD

**Issue by Niquarl** [Chocobozzz/PeerTube#3624]
When looking underneath a video you get the information for the original instance but if you click that link it just opens the homepage of the instance instead of the current video on that instance.
I would like to be able to get a direct link to the video on that instance. This could be useful when the video for whatever reason if not playing on the instance you are on but would work on the original instance.

**Comment by jeena** [comment]
As a workaround until then you can get the original video link from the "share" button. On the video press: `Share ->  More customization -> [x] Use origin instance URL -> Copy URL`

**Comment by Niquarl** [comment]
Good point. So it should be quite easy to do then. Can also do this but with a couple of cliks. Thank you for pointing this out.
