### ISSUE TITLE
Add storage

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#3626]
Is there a way to currently add more storage using mounts/bind mounts? I don't see anything about this anywhere but could just be missing something.

If not I'm assuming the only way of using more then one drive is lvm/raid/network fs.

As a feature request could you enable the admin to add more storage locations?

**Comment by rigelk** [comment]
I remember answering the question in a more detailed way in another issue ; being on mobile I can't link it here though.

What you are looking for is something like unionfs/mergerfs.

**Comment by rigelk** [comment]
Found it: https://github.com/Chocobozzz/PeerTube/issues/3537#issuecomment-753527441

> As a feature request could you enable the admin to add more storage locations?

This is very much out of scope of PeerTube, IMHO.
