### ISSUE TITLE
Lines of videos does not have equal number of videos when resizing windows

### ISSUE THREAD

**Issue by DavidLibeau** [Chocobozzz/PeerTube#363]
* **PeerTube version or commit:** alpha.8
* **Browser name/version:** Firefox 59

* **What is the expected behaviour?** The video list should have lines with equal number of videos.
* **What do you see instead?** We have lines of less videos (here a line with one video) after resizing our browser windows : 
![screenshot-2018-3-19 trending videos - peertube](https://user-images.githubusercontent.com/11574966/37596843-5bf3bfb6-2b75-11e8-9652-805eb3f96ad5.png)

**Comment by Chocobozzz** [comment]
Should be fixed https://github.com/Chocobozzz/PeerTube/commit/6194c1b41902e1d4907d192df80d454ae580884b

It's because we use a `div` to represent a page. And we calculate the number of items per page depending on the client width. Now we rebuild the pages when the client is resized.
