### ISSUE TITLE
Audio-only not produced with audio file

### ISSUE THREAD

**Issue by agates** [Chocobozzz/PeerTube#3633]
**Describe the current behavior**

Uploading an audio file while "Audio-only" is enabled in VOD Transcoding only produces a video file, not an audio only option.

**Steps to reproduce:**

1. Upload an audio file
2. Wait for transcode jobs to finish
3. Check the videos folder, only one exists for the new video (480p in my case).  No audio-only.

**Describe the expected behavior**

An audio file should be produced if "Audio-only" is enabled in Transcoding settings.

**Comment by Chocobozzz** [comment]
Please paste the URL of the video.

**Comment by agates** [comment]
One example, uploaded from a FLAC file.
https://noagendatube.com/videos/watch/4b4999f7-9c81-4428-bb52-3bf03f01f3f3

Source audio from https://archive.org/details/beethoven9/beethoven-9-01-concertgebouw-klemperer-1956-16048.wav

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/40930fda8615a9e0196e99602419cb74dda75e02

But keep in mind that "audio only resolution" is not supported by our HLS player.
