### ISSUE TITLE
add "Internal but Linkable" video privacy setting.

### ISSUE THREAD

**Issue by kyrahabattoir** [Chocobozzz/PeerTube#3634]
**Describe the problem to be solved**

Sometimes you only want instance members to be able to see new video uploads, but you also want them to be able to share a direct link to a video with non-instance members.

For example: teachers pooling learning material on a shared instance, and then sending direct links to students so they don't need to be made members.

**Describe the solution you would like:**

Add an extra privacy option where a video is only visible to instance members, but whose access by direct link is not restricted.

**Comment by jeena** [comment]
Right now this one is the feature which I really miss. What would be nice would be to be able to add additional links (hashes) for sharing which I could then later delete if needed (or they could expire). This way I could choose to share with different people for different amounts of time. But already what @kyrahabattoir describes would be a much welcome addition.

**Comment by Chocobozzz** [comment]
Hello,

Thanks for this issue but it's out of the scope of PeerTube. I think you can create a plugin to implement such thing.
