### ISSUE TITLE
Determine mirror status of remote video

### ISSUE THREAD

**Issue by c0xc** [Chocobozzz/PeerTube#3636]
**Describe the problem to be solved**

It might be useful to be able to check the mirror status of a remote video using the api. I keep noticing videos that should be mirrored but aren't and such a feature might help in determining why.

Say, our mirror instance M follows an instance A, which has thousands of videos. M has the redundancy strategy "recently-added" set to 0 min_views with the same amount of storage that A has (several TB). The disk space used by the redundancy directory is 710 GB and in the admin gui, it says that 279 GB are used for this strategy (trying to get more videos mirrored, I've enabled two other strategies which use 49 and 41 GB). On the same page, about 600 videos are listed, so not even a thousand.
I keep finding older videos on A which are not mirrored, so when such a video is opened in the browser, no downloads from M show up in the network console and a db query searching for videoFile records doesn't find anything.

Query:

    SELECT v.id, v.uuid, v.name FROM "videoFile" AS vf JOIN video AS v ON vf."videoId" = v.id LEFT JOIN "videoRedundancy" AS vr ON (vf.id = vr."videoFileId") where uuid = '<UUID>';

However, searching for such a uuid in the logs, I found lots of these:

    Remote video with uuid <UUID> updated

All I can take from those messages is that the remote video is somehow known to the mirror instance but for some unknown reason, it hasn't mirrored it.

This isn't limited to one or two videos either. I've checked a list of 50 videos to find out that 40 of them are not mirrored, which is why I stopped after those 50.

**Describe the solution you would like:**

So the feature idea is something like a cli or api call on the mirror instance M to find out why a specific video is not being mirrored or, more generic, get the mirror status of a video.

The request which is sent to the api endpoint of instance M or maybe a cli tool on M would specify the video url or video instance (A) and uuid. The response might say something like "already mirrored with file id x", "scheduled to be mirrored within y hours", "not mirrored: does not fit in dedicated redundancy space" and maybe also a timestamp when this information was generated, i.e., when the redundancy scheduler checked this video.

**Describe alternatives you have considered**  

I've enabled additional redundancy strategies but that didn't help. The documentation clearly states that the recently-added strategy can be used to mirror all videos:
_If your instance should act as a complete mirror for another instance, use the "recently-added" strategy and set the view count to 0_

**Comment by Chocobozzz** [comment]
Hi,

For your issue, what check the SQL query below `Running redundancy scheduler for strategy` log. It's the query that will check for available videos to mirror.

**Comment by c0xc** [comment]
All three redundancy scheduler jobs run hourly. I set this interval initially for testing purposes and I haven't changed it since.
```
18:24:07.116 info: Running redundancy scheduler for strategy recently-added.
18:24:07.192 info: Running redundancy scheduler for strategy most-views.
18:24:07.236 info: Running redundancy scheduler for strategy trending.
19:24:07.117 info: Running redundancy scheduler for strategy recently-added.
19:24:07.184 info: Running redundancy scheduler for strategy most-views.
19:24:07.228 info: Running redundancy scheduler for strategy trending.
```
I could reduce the interval to 24h and disable the other two because if the "recently-added" one mirrors *all* videos, as it should, the other two wouldn't be necessary anyway.

It seems like videos older than a year aren't mirrored and it's not limited to this mirror instance (i.e., many old videos show "1 peer" even though there are mirror instances with enough disk space available). That's why I think there should be tools to have more control over the mirroring process, like querying the mirror status of a video, maybe also the job queue (how many, which videos are left in the queue of the redundancy job, to be checked). For each video that's not mirrored, it should be possible to find out why it's missing.

**Comment by Chocobozzz** [comment]
Please enable debug logs to see SQL requests executed by the strategy

**Comment by c0xc** [comment]
"Removing old jobs" sounds a bit dangerous. I wouldn't cancel running jobs, right?

```
2021-01-26 21:51:03.385 ESC[34mdebugESC[39m: Checking peers.
2021-01-26 21:51:06.385 ESC[32minfoESC[39m: Removing old jobs in scheduler.
2021-01-26 21:51:06.389 ESC[32minfoESC[39m: Running redundancy scheduler for strategy recently-added.
2021-01-26 21:51:06.405 ESC[34mdebugESC[39m: Executing (default): UPDATE "actorFollow" SET "score" = LEAST("score" + 10, 10000) WHERE id IN (SELECT "actorFollow"."id" FROM "actorFollow" INNER JOIN "actor" ON "actor
"."id" = "actorFollow"."targetActorId" WHERE "actorFollow"."actorId" = 1 AND "actor"."serverId" IN ('2'))
2021-01-26 21:51:06.441 ESC[34mdebugESC[39m: Executing (default): SELECT "VideoModel".* FROM (SELECT "VideoModel"."id", "VideoModel"."publishedAt" FROM "video" AS "VideoModel" INNER JOIN "videoChannel" AS "VideoCha
nnel" ON "VideoModel"."channelId" = "VideoChannel"."id" INNER JOIN "actor" AS "VideoChannel->Actor" ON "VideoChannel"."actorId" = "VideoChannel->Actor"."id" INNER JOIN "server" AS "VideoChannel->Actor->Server" ON "VideoChannel->Actor"."se
rverId" = "VideoChannel->Actor->Server"."id" AND "VideoChannel->Actor->Server"."redundancyAllowed" = true WHERE "VideoModel"."privacy" = 1 AND "VideoModel"."views" >= 0 AND ( SELECT "videoId" FROM "videoFile" AS "VideoFiles" WHERE ("Video
Files"."id" NOT IN (SELECT "videoFileId" FROM "videoRedundancy" WHERE "actorId" = 1 AND "videoFileId" IS NOT NULL) AND "VideoFiles"."videoId" = "VideoModel"."id") LIMIT 1 ) IS NOT NULL ORDER BY "VideoModel"."publishedAt" DESC, "VideoModel
"."id" ASC LIMIT 5) AS "VideoModel" INNER JOIN "videoFile" AS "VideoFiles" ON "VideoModel"."id" = "VideoFiles"."videoId" AND "VideoFiles"."id" NOT IN (SELECT "videoFileId" FROM "videoRedundancy" WHERE "actorId" = 1 AND "videoFileId" IS NO
T NULL) ORDER BY "VideoModel"."publishedAt" DESC, "VideoModel"."id" ASC;
2021-01-26 21:51:06.482 ESC[32minfoESC[39m: Running redundancy scheduler for strategy most-views.
2021-01-26 21:51:06.501 ESC[34mdebugESC[39m: Executing (default): SELECT "VideoModel".* FROM (SELECT "VideoModel"."id", "VideoModel"."views" FROM "video" AS "VideoModel" INNER JOIN "videoChannel" AS "VideoChannel" 
ON "VideoModel"."channelId" = "VideoChannel"."id" INNER JOIN "actor" AS "VideoChannel->Actor" ON "VideoChannel"."actorId" = "VideoChannel->Actor"."id" INNER JOIN "server" AS "VideoChannel->Actor->Server" ON "VideoChannel->Actor"."serverId
" = "VideoChannel->Actor->Server"."id" AND "VideoChannel->Actor->Server"."redundancyAllowed" = true WHERE "VideoModel"."privacy" = 1 AND ( SELECT "videoId" FROM "videoFile" AS "VideoFiles" WHERE ("VideoFiles"."id" NOT IN (SELECT "videoFil
eId" FROM "videoRedundancy" WHERE "actorId" = 1 AND "videoFileId" IS NOT NULL) AND "VideoFiles"."videoId" = "VideoModel"."id") LIMIT 1 ) IS NOT NULL ORDER BY "VideoModel"."views" DESC, "VideoModel"."id" ASC LIMIT 5) AS "VideoModel" INNER 
JOIN "videoFile" AS "VideoFiles" ON "VideoModel"."id" = "VideoFiles"."videoId" AND "VideoFiles"."id" NOT IN (SELECT "videoFileId" FROM "videoRedundancy" WHERE "actorId" = 1 AND "videoFileId" IS NOT NULL) ORDER BY "VideoModel"."views" DESC
, "VideoModel"."id" ASC;
2021-01-26 21:51:06.518 ESC[32minfoESC[39m: Running redundancy scheduler for strategy trending.
```

For example, video 1107 is one that should be mirrored but isn't.
```
peertube=> SELECT "VideoModel"."id", "VideoModel"."publishedAt" FROM "video" AS "VideoModel" INNER JOIN "videoChannel" AS "VideoChannel" ON "VideoModel"."channelId" = "VideoChannel"."id" INNER JOIN "actor" AS "VideoChannel->Actor" ON "VideoChannel"."actorId" = "VideoChannel->Actor"."id" INNER JOIN "server" AS "VideoChannel->Actor->Server" ON "VideoChannel->Actor"."serverId" = "VideoChannel->Actor->Server"."id" AND "VideoChannel->Actor->Server"."redundancyAllowed" = true WHERE "VideoModel"."privacy" = 1 AND "VideoModel"."views" >= 0  and "VideoModel"."id" = 1107 ORDER BY "VideoModel"."publishedAt" DESC, "VideoModel"."id" ASC;
  id  |      publishedAt       
------+------------------------
 1107 | 2017-11-14 00:00:00+01
(1 row)

peertube=> SELECT "VideoModel"."id", "VideoModel"."publishedAt" FROM "video" AS "VideoModel" INNER JOIN "videoChannel" AS "VideoChannel" ON "VideoModel"."channelId" = "VideoChannel"."id" INNER JOIN "actor" AS "VideoChannel->Actor" ON "VideoChannel"."actorId" = "VideoChannel->Actor"."id" INNER JOIN "server" AS "VideoChannel->Actor->Server" ON "VideoChannel->Actor"."serverId" = "VideoChannel->Actor->Server"."id" AND "VideoChannel->Actor->Server"."redundancyAllowed" = true WHERE "VideoModel"."privacy" = 1 AND "VideoModel"."views" >= 0 AND ( SELECT "videoId" FROM "videoFile" AS "VideoFiles" WHERE ("VideoFiles"."videoId" = "VideoModel"."id") LIMIT 1 ) IS NOT NULL and "VideoModel"."id" = 1107;
 id | publishedAt 
----+-------------
(0 rows)

peertube=> SELECT "VideoModel"."id", "VideoModel"."publishedAt" FROM "video" AS "VideoModel" INNER JOIN "videoChannel" AS "VideoChannel" ON "VideoModel"."channelId" = "VideoChannel"."id" INNER JOIN "actor" AS "VideoChannel->Actor" ON "VideoChannel"."actorId" = "VideoChannel->Actor"."id" INNER JOIN "server" AS "VideoChannel->Actor->Server" ON "VideoChannel->Actor"."serverId" = "VideoChannel->Actor->Server"."id" AND "VideoChannel->Actor->Server"."redundancyAllowed" = true WHERE "VideoModel"."privacy" = 1 AND "VideoModel"."views" >= 0  and "VideoModel"."id" = 1107;
  id  |      publishedAt       
------+------------------------
 1107 | 2017-11-14 00:00:00+01
(1 row)

peertube=> SELECT "videoId" FROM "videoFile" AS "VideoFiles" WHERE ("VideoFiles"."videoId" = 1107);
 videoId 
---------
(0 rows)

```

**Comment by Chocobozzz** [comment]
> That query returns nothing.

What query? This one?

```
SELECT
  "VideoModel".*
FROM (
  SELECT
    "VideoModel"."id",
    "VideoModel"."publishedAt"
  FROM
    "video" AS "VideoModel"
    INNER JOIN "videoChannel" AS "VideoChannel" ON "VideoModel"."channelId" = "VideoChannel"."id"
    INNER JOIN "actor" AS "VideoChannel->Actor" ON "VideoChannel"."actorId" = "VideoChannel->Actor"."id"
    INNER JOIN "server" AS "VideoChannel->Actor->Server" ON "VideoChannel->Actor"."serverId" = "VideoChannel->Actor->Server"."id"
      AND "VideoChannel->Actor->Server"."redundancyAllowed" = TRUE
  WHERE
    "VideoModel"."privacy" = 1
    AND "VideoModel"."views" >= 0
    AND (
      SELECT
        "videoId"
      FROM
        "videoFile" AS "VideoFiles"
      WHERE ("VideoFiles"."id" NOT IN (
          SELECT
            "videoFileId"
          FROM
            "videoRedundancy"
          WHERE
            "actorId" = 1
            AND "videoFileId" IS NOT NULL)
          AND "VideoFiles"."videoId" = "VideoModel"."id")
      LIMIT 1) IS NOT NULL
  ORDER BY
    "VideoModel"."publishedAt" DESC,
    "VideoModel"."id" ASC
  LIMIT 5) AS "VideoModel"
  INNER JOIN "videoFile" AS "VideoFiles" ON "VideoModel"."id" = "VideoFiles"."videoId"
    AND "VideoFiles"."id" NOT IN (
      SELECT
        "videoFileId"
      FROM
        "videoRedundancy"
    WHERE
      "actorId" = 1
      AND "videoFileId" IS NOT NULL)
ORDER BY
  "VideoModel"."publishedAt" DESC,
  "VideoModel"."id" ASC;
```

If yes, it means that peertube does not find candidates to mirror. Then you need to check what clause in this query don't select the videos your want to mirror

**Comment by c0xc** [comment]
Yes, that one. It expects something in the videoFile table but, like I showed in my previous comment, that table has no entries for some videos.

Let's look at the subquery `#1`, without the inner join at the end (which also fails because it doesn't find matching entries in videoFile). And let's use 1107 as one of the missing videos and 4 as one that's ok. So that select from "video" will find records for both of those ids. Then, the next subquery `#2` expects a matching record in the "videoFile" table but doesn't find one for 1107. And the next subquery `#3` excludes video 4 because it's already in the "videoRedundancy" table.

```
-- SELECT
--   "VideoModel".*
-- FROM (
-- #1: this query selects the video table and it will return something for videos that aren't mirrored
  SELECT
    "VideoModel"."id",
    "VideoModel"."publishedAt"
  FROM
    "video" AS "VideoModel"
    INNER JOIN "videoChannel" AS "VideoChannel" ON "VideoModel"."channelId" = "VideoChannel"."id"
    INNER JOIN "actor" AS "VideoChannel->Actor" ON "VideoChannel"."actorId" = "VideoChannel->Actor"."id"
    INNER JOIN "server" AS "VideoChannel->Actor->Server" ON "VideoChannel->Actor"."serverId" = "VideoChannel->Actor->Server"."id"
      AND "VideoChannel->Actor->Server"."redundancyAllowed" = TRUE
  WHERE
    "VideoModel"."privacy" = 1
    AND "VideoModel"."views" >= 0
    AND
    (

-- #2: this query expects a record in the videoFile table but doesn't find one
      SELECT
        "videoId"
      FROM
        "videoFile" AS "VideoFiles"
      WHERE ("VideoFiles"."id" NOT IN
      (

-- #3: this selects video file ids from the videoRedundancy table to exclude them
          SELECT
            "videoFileId"
          FROM
            "videoRedundancy"
          WHERE
            "actorId" = 1
            AND "videoFileId" IS NOT NULL
      )
      AND "VideoFiles"."videoId" = "VideoModel"."id")
      LIMIT 1
    ) IS NOT NULL

  ORDER BY
    "VideoModel"."publishedAt" DESC,
    "VideoModel"."id" ASC
  LIMIT 5
-- ) AS "VideoModel"
-- #4: this joins the resultset with the videoFile table
-- INNER JOIN "videoFile" AS "VideoFiles" ON "VideoModel"."id" = "VideoFiles"."videoId"
-- AND "VideoFiles"."id" NOT IN (
--   SELECT
--     "videoFileId"
--   FROM
--     "videoRedundancy"
--   WHERE
--     "actorId" = 1
--     AND "videoFileId" IS NOT NULL
-- )
-- ORDER BY
--   "VideoModel"."publishedAt" DESC,
--   "VideoModel"."id" ASC
;

```

So both videos are in the "video" table but only the ok one number 4 is in the "videoFile" table, not 1107. Why (not)?

**Comment by Chocobozzz** [comment]
Thanks @c0xc, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/7448551fe5c111fcc7b7448ad864fb15a5c8d87f

**Comment by c0xc** [comment]
Thanks @Chocobozzz! I'm trying your fix now and it's already duplicating more videos. I'll see how it goes and then comment on the other issue.

By the way, I went into the redundancy settings ("Instances you follow") and after unchecking "Redundancy allowed", I got this error in the log:
```
error: Cannot remove redundancy of ... {
  "err": {
    "stack": "TypeError: Cannot read property 'Video' of null\n    at VideoRedundancyModel.getVideo (.../dist/server/models/redundancy/video-redundancy.js:524:41)\n ... (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
    "message": "Cannot read property 'Video' of null"

```

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/2e1e4af03bc9ccd2470a9f293d70dc27596aae24

**Comment by c0xc** [comment]
Thank you, I appreciate it. I'll try the new version. Can I send you a thank-you package of coffee?
