### ISSUE TITLE
Transcoding resolutions not respected during import

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3638]
**Describe the current behavior**
We've some random problems during our imports. Our PeerTube instance has VOD transcoding resolutions set to Audio only, 240p, 360p, 480p and 720p. When importing a video (from Vimeo) with a max resolution at 1080p the video will sometimes be transcoded to 1080p only (even though there's jobs for all resolutions), sometimes to some of the resolutions and sometimes to all selected resolutions (+ 1080p).

**Steps to reproduce:**

1. Set VOD transcoding resolutions to Audio only, 240p, 360p, 480p and 720p.
2. Import a 1080p video from Vimeo.
3. See that it's transcoded to 1080p.

**Describe the expected behavior**
* 1080p should never be transcoded as it's not selected in the config.
* All selected resolutions should always be available.

* PeerTube instance:
  * version: 3.0.1
  * NodeJS version: 12.20.1
  * Ffmpeg version: 4.2.4

**Comment by rigelk** [comment]
@kontrollanten I cannot reproduce, but maybe your video on Vimeo is different than mine. Could you give us the URL?

**Comment by kontrollanten** [comment]
> @kontrollanten I cannot reproduce, but maybe your video on Vimeo is different than mine. Could you give us the URL?

https://www.youtube.com/watch?v=GIhcL8K4shg

**Comment by Chocobozzz** [comment]
Hi,

I can't reproduce on peertube nightly (video is transcoded in 480p). We made some enhancements in the import and transcoding process since v3 stable so maybe it fixed this issue.

**Comment by kontrollanten** [comment]
Sorry to be unclear, the video I posted was 480 since I didn't found the 1080p video I imported yesterday. When I import 480 but set the transcode resolutions to 240 and 360 I get the video transcoded to 480 anyway.

Is there any known problems in the nightly build or do I dare to do an own release from my PT fork?

**Comment by Chocobozzz** [comment]
> Is there any known problems in the nightly build

The nightly build is not stable and should not be used in production so choose the method you want :) I just tested to import again with only 360p and 240p enabled, and it correctly imported and transcoded 360p and 240p versions.

**Comment by maxlinux2000** [comment]
Hi

same error here with this video https://www.youtube.com/watch?v=ejcbkegEZv4

![Captura de pantalla de 2021-02-08 20-26-38](https://user-images.githubusercontent.com/5683921/107271066-02163280-6a4c-11eb-8dec-814ec99ed0c5.png)


I have the PeerTube  3.0.1 version under raspberrypi4 (buster10, the default distro debian based).

**Comment by Chocobozzz** [comment]
@maxlinux2000 As I said in https://github.com/Chocobozzz/PeerTube/issues/3638#issuecomment-767404663, we made improvements **since** v3 stable. So wait for the next release or try a nightly build
