### ISSUE TITLE
screenshot/preview ffmpeg process at overly high CPU priority

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#3644]
**Describe the current behavior**

I noticed several of the ffmpeg processes used for extracting single frames, each spinning at 100% CPU, at a higher priority than background and stream transcodes.

**Steps to reproduce:**

Not sure why the ffmpeg processes were spinning, i suspect it has to do with a stream recording that includes no video frames? This is TBD. In any case though, the screenshot ffmpeg processes shouldn't be running at a higher priority than live streams.

**Describe the expected behavior**

Preview frame extraction should happen with a limited amount of concurrency, and in a bounded amount of time, at a lower CPU priority than real-time tasks like live streaming.

**Additional information**

* PeerTube instance:
  * URL: diode.zone
  * version: 3.0.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/a4a8cd39712c59119ad0be5cd584b158f06c5852

**Comment by scanlime** [comment]
Thanks. For what it's worth, the other issue that made this noticeable (ffmpeg spinning at 100% cpu) was resolved by updating ffmpeg (from an old git snapshot to a current one).
