### ISSUE TITLE
Erroneous error on Firefox for iOS

### ISSUE THREAD

**Issue by squirrellyDave** [Chocobozzz/PeerTube#3646]
When watching videos in Firefox on IOS there is a warning that can’t be dismissed that peertube is incompatible with the browser.  

I have no issues watching videos in FF mobile.

**Comment by Chocobozzz** [comment]
Please fill the template

**Comment by squirrellyDave** [comment]
I can't reproduce this.

**Comment by mmahmoudian** [comment]
@squirrellyDave I just cane here to report this. The info:
- iOS version: 15.4.1
- Firefox version: Firefox Daylight 99.0 (8654)

everythis is updated and in latest version. The following is the screenshot i just took:

![5C7A9CA9-1484-4DC8-82D4-4D24F7804C99](https://user-images.githubusercontent.com/390889/162576048-982db579-4f34-4715-bf88-8d4aae3792c0.png)

**Comment by mmahmoudian** [comment]
For what it's worth, the problem continues for the following:
- https://tube.kockatoo.org/w/q1hc3sm7nFnxGJXBXcZ5rh
- iOS version 15.4.1
- Firefox version: Firefox Daylight 99.3 (9185)
