### ISSUE TITLE
Random language translation is selected

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3647]
**Describe the current behavior**
I've selected English as default language in my browser (Brave) and Swedish as language at our PeerTube instance. Randomly when I visit our PeerTube instance I get a Finnish translation. We've also got reports from users who gets Russian translations randomly. This problem has been since version 2.4.0 and became better since 3.0.0.

**Steps to reproduce:**
Can't reproduce this since it's happening randomly.

* PeerTube instance:
  * version: 3.0.1

* Browser name, version and platforms on which you could reproduce the bug:
Brave, Linux

**Comment by Chocobozzz** [comment]
What is your instance URL?

**Comment by kontrollanten** [comment]
I emailed you the instance URL

**Comment by Chocobozzz** [comment]
Could it be a front proxy/CDN issue? Because I could not reproduce and I've never heard of such problem

**Comment by kontrollanten** [comment]
I can't really see how the CDN or proxy could cause that issue. Do you know how angular is determining the language? When the problem appears it doesn't gets solved by page reload, only by opening the site in a new tab.

**Comment by Chocobozzz** [comment]
We serve the appropriate bundle from the server: https://github.com/Chocobozzz/PeerTube/blob/develop/server/controllers/client.ts#L82 

We use the request parameter to guess the language. If it does not exist, we check the cookie. If it does not exist, we send the appropriate page according to the request accept language header: https://github.com/Chocobozzz/PeerTube/blob/9aeef9aafa009762e128046bfb2f3cec3252e181/server/lib/client-html.ts#L291

**Comment by kontrollanten** [comment]
I think I've figured out this. If the request accept language header is set to Russian our CDN will cache the Russian index.html version (with `<html lang="ru">` etc), right?

**Comment by kontrollanten** [comment]
We're still facing this issue with the latest version. I can't reproduce it and I haven't got any problems since this was closed, but we're having users reporting this issue. One user reported the following.

1) He visited the site and everything was in Swedish.
1) He downloaded a video.
1) The site was in Russian.
1) He downloaded another video.
1) The site was in English.

Can a solution be to make it possible to disable auto lang selection (and only support one selection)? I know that won't solve the root problem, but I can't find any other way in solving this.

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but we can't help. This is an issue with your current setup and not with peertube.
