### ISSUE TITLE
Restrict P2P sharing

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3648]
**Describe the problem to be solved**
Some users pay for their bandwidth and some just have slow connections, for them the only solution to save bandwidth today is to totally disable P2P.

**Describe the solution you would like:**
The `NetworkInformation.saveData` option should always be respected and it would also be great to let them choose to disable P2P when they're on slow/cellular connection.

**Describe alternatives you have considered**  
* In cases when available, [NetworkInformation.type](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/type) or [NetworkInformation.effectiveType](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/effectiveType) could be used.
* Let users set a ceiling for data share, e.g. "share at maximum 2 GB per month".

**Comment by Chocobozzz** [comment]
Hello,

We already disable seeding for HLS videos when the user is on a cellular network. Using the `saveData` API won't really help since it's too experimental, and anonymous/logged users have the ability to disable P2P in their settings.

**Comment by kontrollanten** [comment]
When I'm using 4g (NetworkInformation.effectiveType === '4g') I still share data while viewing.

**Comment by Chocobozzz** [comment]
What is the value of `navigator.connection.type`? You see that you're sending data to other peer?

**Comment by kontrollanten** [comment]
`navigator.connection.type` is `undefined` (Brave). Yes I see in the video player that I'm sending data.

**Comment by Chocobozzz** [comment]
Mobile web browser should support `navigator.connection.type`. `effectiveType` is not a property we can use to know if the user is on a cellular network.
