### ISSUE TITLE
Disable password-based login in SAML or eq. use cases

### ISSUE THREAD

**Issue by maxabernathy** [Chocobozzz/PeerTube#3649]
Hi Team,
we set up an internal peertube in our organisation and are using the SAML-plugin which has its own simple button next to the text-based login. However, we also want to disable the password-based login, so that users don't accidently type in their pw's. I have read in another response by the most venerable Chocobozzz, bozzz of the Chocolate, that admin's still need to login via pw. How should we go about it? It is a dealbreaker for our security-team and it's a pity because the SAML is working so far. So "hide" the login somewhere else for the admins - where is the login-script getting called? Thanks for any feedback!

**Comment by rigelk** [comment]
@maxabernathy you are making a feature request, so please fill [the corresponding template](https://github.com/Chocobozzz/PeerTube/issues/new?assignees=&labels=&template=30-feature-request.md).

**Comment by Chocobozzz** [comment]
Hi,

You can create a plugin or use JS/CSS customization to:
 * Hide the login form using CSS: `display: none`
 * Display it using JS if the URL contains a special query param (`?enableLoginForm=true`)

**Comment by ser** [comment]
Has anyone written such a plugin and can share please? 🥇

**Comment by artlog** [comment]
<img width="1337" height="637" alt="Image" src="https://github.com/user-attachments/assets/ce83a426-96e6-4513-9f70-d0e6769057b1" />

Adding this CSS content `#plugin-selector-login-form {display: none;}` allows to hide user/password login form.

**Comment by artlog** [comment]
This forum topic https://framacolibri.org/t/disable-password-based-login-in-oidc-or-saml-case/32620 adds even simpler solutions.
