### ISSUE TITLE
Resume upload

### ISSUE THREAD

**Issue by unfa** [Chocobozzz/PeerTube#3650]
**Describe the problem to be solved**

If uploading a video is interrupted fro whatever reason, PeerTube shows that an error occurred, and asks the user if the upload should be retried.

If allowed, it'll proceed to upload the whole file from scratch.

**Describe the solution you would like:**

It'd be great if PeerTube could keep track of the upload progress and in case of a problem could try and resume the upload instead of restarting it.

This is what YouTube does - I can put my computer to sleep while uploading to YouTube and the upload resumes after I wake my PC up. On PeerTube I've just done this by mistake and I have to upload the video from scratch.

I think this could be a nice quality of life feature, it'd also lower resource usage in case of connection problems, and could even be a life saver for people with very poor Internet access, who might not be able to upload anything otherwise.

**Comment by rigelk** [comment]
Certainly, this is a great quality of life feature! However please look out for related issues before creating one, as #324 already covers this. You can then detail further your use case there, and upvote the issue to help us triage it.
