### ISSUE TITLE
[SAML2 Plugin] Cannot migrate User to SAML Auth nor delete Actor to start over

### ISSUE THREAD

**Issue by cybershaman** [Chocobozzz/PeerTube#3652]
I recently upgraded my PeerTube instance to v3.0.1 and realised there is now a SAML2 plugin available - I'm running LemonLDAP for SSO/SAML purpose.

The instance originally had only 2 users, "root" and my personal user "pete" (both admin users).
When I successfully configured SAML2 with PeerTube all my domain's users could SSO into PeerTube and had their respective users created. My personal user "pete" wouldn't become SAML enabled (error "actor already exists" on SAML login attempt)

Things I tried:
- Postgres "user" table, change 'pluginAuth' = 'peertube-plugin-auth-saml2'   -> still cannot log in user "pete"
- delete 'preferredUsername' = 'pete' from "actor" table -> still cannot log in ("actor already exists"), after some time(?) the actor does indeed reappear in the database with the original PGP Pub/Private keys even. How is that possible?

I'd be very grateful for any pointers/help.
TIA!

**Comment by rigelk** [comment]
Hi @cybershaman,

Please open this issue directly at the SAML plugin repository: https://framagit.org/framasoft/peertube/official-plugins/-/tree/master/peertube-plugin-auth-saml2

**Comment by Chocobozzz** [comment]
Hello,

In fact this is a peertube issue since it's peertube that throws this error. We need to provide a way for admins to update the user auth field to easily change the user auth method.

**Comment by Chocobozzz** [comment]
Admins can now change the auth plugin in the user update form: https://github.com/Chocobozzz/PeerTube/commit/6d989edc66e7b541fcf97c2a4a6f91cbf960060a
