### ISSUE TITLE
Redirect instance.org/@channel links to instance.org/accounts/channel

### ISSUE THREAD

**Issue by j-james** [Chocobozzz/PeerTube#3653]
**Describe the problem to be solved**

Fediverse accounts are typically referred to with the unique syntax `@user@instance.org`, like how emails are always `user@provider.com` or URLs `website.com`. For emails and URLs, it's easy to parse with regex and convert to `mailto://` or `https://` links. 

But doing this for Fediverse accounts is a little difficult because of the leeway in how different projects can link to users - Mastodon and PixelFed use `https://instance.org/@user`, Pleroma uses `https://instance.org/user`, and PeerTube uses `https://instance.org/accounts/channel`. The best way currently is to do a WebFinger query and parse the response.

**Describe the solution you would like:**

If PeerTube redirected `https://instance.org/@channel` URLs to `https://instance.org/accounts/channel`, linkifying accounts could assume that `https://instance.org/@user` works and would remove a fair amount of excess complexity from other projects. Pleroma already redirects `https://instance.org/@user` to `https://instance.org/user`, and Mastodon's accounts are set up that way by default.

Here's an example place where this would be helpful: https://gitlab.com/tildes/tildes/-/issues/471

**Comment by Chocobozzz** [comment]
I think we could implement that, but why don't you use webfinger?

**Comment by scanlime** [comment]
+1 for URLs that are easy to type and quick to read. software should use webfinger but humans want URLs too

**Comment by j-james** [comment]
There's nothing stopping us or anyone from using WebFinger, it's just added complexity.

This would also help in places where WebFinger can't / shouldn't be used (like text editors).

**Comment by rigelk** [comment]
> This would also help in places where WebFinger can't / shouldn't be used (like text editors).

Could you elaborate?

**Comment by Chocobozzz** [comment]
Closing this issue in favor of https://github.com/Chocobozzz/PeerTube/issues/3680
