### ISSUE TITLE
Video fails to load, client issues invalid byte range requests

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#3657]
**Describe the current behavior**

The video fails to load, with the spinner running continuously. Looking at network requests, the client is making a mix of valid and invalid requests. The invalid requests have a bad byte range, like "113383-113382" here,
![image](https://user-images.githubusercontent.com/923812/106161035-56134400-613b-11eb-9040-70aceb7eb9e7.png)

**Steps to reproduce:**

1.  Not sure specifically, but I've seen this on a couple videos now. Currently seeing it here: https://diode.zone/videos/watch/35f310a7-5b33-4b15-9f3b-95e3b2d61c3d

**Describe the expected behavior**

Valid requests only, video either loads correctly or fails for a well-explained reason.

**Additional information**

* PeerTube instance:
  * URL: diode.zone
  * version: 3.0.1
  * NodeJS version: 
  * Ffmpeg version: git snapshot from yesterday

* Browser name, version and platforms on which you could reproduce the bug: Firefox 85.0, windows 10, 64-bit
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by scanlime** [comment]
The root issue seems to be something with ffmpeg that causes it to generate zero-length HLS segments. Some players will ignore them, and they aren't relevant to the fmp4 file itself, but HLS.js complains and peertube doesn't show any useful errors. Somewhere in HLS.js the zero length turns into a -1 and generates an invalid byte range.

**Comment by scanlime** [comment]
I can reproduce this still using a fresh build of ffmpeg from git. It's producing HLS playlists with a zero-length byte range (contains the string "BYTERANGE:0@"...) that leads to the malformed range request and failure in hls.js. I can sort of work around the failure by manually deleting this first hls segment, but that also loses a little bit of video.

**Comment by Chocobozzz** [comment]
I can play the video. Did you fix it? If yes, could you create another one so I reproduce?

**Comment by scanlime** [comment]
I've been trying to fix the videos by reverting to an earlier ffmpeg and re-running the transcode. That one is now partially fixed, but for me it's showing up as only 1 second long still.

Here's one that's currently entirely broken: https://diode.zone/videos/watch/e42f600d-1a22-431d-9469-4a093b49b2e1

**Comment by Chocobozzz** [comment]
> Here's one that's currently entirely broken: https://diode.zone/videos/watch/e42f600d-1a22-431d-9469-4a093b49b2e1

It doesn't seem broken and I don't see segments with size 0

**Comment by scanlime** [comment]
You're too late, i fixed that one already, I'm not trying to keep my server broken to demo a bug. You can repro it by upgrading ffmpeg.

**Comment by Chocobozzz** [comment]
We only support ffmpeg releases.

**Comment by scanlime** [comment]
I don't see any documentation on specific ffmpeg support, just "at least 4.1" from some of the release notes. The ffmpeg web site encourages folks to use git snapshots, so I expect you'll see more people hit this problem.
