### ISSUE TITLE
Answering to a video comment doesn't create a mastodon-like mention

### ISSUE THREAD

**Issue by PhieF** [Chocobozzz/PeerTube#366]
* **PeerTube version or commit:** v1.0.0-beta.1
* **Browser name/version:**  firefox 59
* **NodeJS version:** v8.10.0
* **PostgreSQL version:** 9.5.12

* **What is the expected behaviour?**
answering to a comment should (perhaps) mention with an @ at the start, like mastodon
@username@instance
* **What do you see instead?**
answering to @username@instance make the comment begin by username@instance

cf
https://framapic.org/8ehRId94o4M0/twQ7RgMTJzuB.png

**Comment by Chocobozzz** [comment]
Oup's, thanks it's fixed: https://github.com/Chocobozzz/PeerTube/commit/9add00514f89e6e3eefc8f18174338088b9ab12e
