### ISSUE TITLE
S3FS and live streaming

### ISSUE THREAD

**Issue by manuelviens** [Chocobozzz/PeerTube#3660]
**Describe the current behavior**
Lives are unreadable if S3FS is used like described at https://docs.joinpeertube.org/admin-remote-storage
Extreme lag to show any webpage for any client during a live attempt.
CPU used at ~70% (50% system + 20% user).

**Steps to reproduce:**
Start a live on an instance using S3FS as described at https://docs.joinpeertube.org/admin-remote-storage

**Describe the expected behavior**
In my nginx conf, I unquoted the line :
`client_body_temp_path /var/www/peertube/storage/nginx/;`
and expected lives would be temporary saved there (not using any S3 mouted directories).
It seems that storage/streaming-playlists (using S3FS) is used to save these files.
Even when it's a "permanent" live (not saved), it uses streaming-playlists, what I don't find intuitive.
And I noticed there still files in the directory of the video ID. I don't understand why, as it is a "permanent" live and anyway PeerTube don't show any video at it's URL (live currently offline).

**Additional information**
I just migrated from S3QL to S3FS. 
Live transcoding is deactivated.
Before this migration, lives hardly worked with S3QL, where my nginx acted as proxy to S3 bucket. But S3QL drained too much CPU.

Please note that anything else seems to work very well, better than with S3QL.

* PeerTube instance:
  * URL: https://peertube.fedi.quebec
  * version: 3.0.1
  * NodeJS version: v12.20.1
  * Ffmpeg version: 4.3.1-0york0~18.04

* Browser name, version and platforms on which you could reproduce the bug: All
* Link to browser console log if relevant: 
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks for the issue, merging in https://github.com/Chocobozzz/PeerTube/issues/3661
