### ISSUE TITLE
small UI bugs in mobile view

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3664]
**Describe the current behavior**
https://peertube2.cpy.re
i have put this url in firefox android which gives me "add to screen" as a PWA.
anyways, i see a couple of UI bugs that arent really a big deal, just pointing them out.

1.
![Screenshot-20210129-171135](https://user-images.githubusercontent.com/39449563/106305024-29b60f80-6282-11eb-847e-6ce545e08746.png)

the tooltip for "hot" gets outside the screen and because of the fixed width, i cannot zoom out to see what it says.  maybe the tooltips can be made to honor the width because that would solve these and many other tooltip bugs

2. 
![Screenshot-20210129-171304](https://user-images.githubusercontent.com/39449563/106305205-68e46080-6282-11eb-9ac8-b1560e409dd3.png)
the tooltip for "like this video" and " you need to be logged in " are overlapping. i have to click twice on the button to hide the top one so that i can read the second one. maybe we can just hide the "hover" tooltips on mobile like the above one says "like this video" because at this point, if anyone is using peertube on a mobile phone screen, they probably already understand what thumbs up means :-)

3. 
![Screenshot-20210129-171338](https://user-images.githubusercontent.com/39449563/106305516-cd072480-6282-11eb-8e12-7517f18f98d7.png)
![Screenshot-20210129-171359](https://user-images.githubusercontent.com/39449563/106305524-ced0e800-6282-11eb-8919-6811f49315a2.png)

now this one is even smaller of a nitpick but the checkboxes except the first one have their left side pressed in to the side, clipped.
the first checkbox looks fine. the others seem like one pixel is clipped. yes. i zoomed them together
![Screenshot-20210129-171338(1)](https://user-images.githubusercontent.com/39449563/106306345-efe60880-6283-11eb-9da9-7f84db6b8486.png)
![Screenshot-20210129-171359(1)](https://user-images.githubusercontent.com/39449563/106306349-f07e9f00-6283-11eb-9be0-d5f800c46f8b.png)

and this looks like it on desktop as well so yeah.

i have another screenshot of the likes "tooltip" going outside the width which makes the phone zoom out but it cant be explained easily other than is there a way to prevent the tooltips from going past the device width set on the screen?

**Describe the expected behavior**

**Additional information**

* PeerTube instance:
  * URL:
  * version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/2666fd7c753c8afdcba1907a5900ccb143df23c4
