### ISSUE TITLE
Transcode jobs do not replace output files atomically

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#3668]
**Describe the current behavior**

Trying to re-transcode existing but partially broken files using create-transcoding-job.js, and the resulting transcodes overwrite existing media files in-place, meaning that any requests during the transcode see partial results rather than a correct old or new version.

**Steps to reproduce:**

1. Use create-transcoding-job.js with --generate-hls on an existing video

**Describe the expected behavior**

Expected that transcode results always get written to a temp directory and moved in atomically after they complete successfully.

**Additional information**

* PeerTube instance:
  * URL: diode.zone
  * version: 3.0.1
  * NodeJS version:
  * Ffmpeg version: git
 
* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/aaedadd5386b580e9ebac540201399c25c7f0b0f
