### ISSUE TITLE
Don't count views as unique per IP address

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3669]
**Describe the problem to be solved**
Today the views counter limits to one view per IP address (per hour?). Since views are very important indicator for the user to see which videos are popular, I think it's also important to be too restrictive with the counting. One of hour biggest competitors is Youtube and they don't have this limit; if I look at a video five times in a row there will increment with five views. In many cases there's also multiple persons on the same network that see a video, or just that you watch a video multiple times since it's good.

**Describe the solution you would like:**
Don't restrict the views to once per IP address. Is there any particular reason that it's done that way?

**Comment by Alterak** [comment]
The documentation says that for one IP address, restrictions are only 1 time per hour
https://github.com/Chocobozzz/PeerTube/blob/develop/FAQ.md#how-are-video-views-counted

**Comment by Chocobozzz** [comment]
> per IP address (per hour?)

Yes per hour.

> biggest competitors is Youtube

Youtube is not a competitor. PeerTube is just an alternative, that is different.

> they don't have this limit;

We don't know for sure, but we're pretty sure they have such limit: http://gdac.uqam.ca/WWW2016-Proceedings/proceedings/p357.pdf

> Is there any particular reason that it's done that way?

Yes, to have an easy-to-understand metric. And it helps to limit easy views manipulation. We did not designed this counter to be as big as possible.

**Comment by kontrollanten** [comment]
> > biggest competitors is Youtube
> 
> Youtube is not a competitor. PeerTube is just an alternative, that has different goals :)

Yes, from your point of view, but from a video consumer perspective it's two video platforms that they can choose between.

> > they don't have this limit;
> 
> We don't really know, but we're pretty sure they have such limit: http://gdac.uqam.ca/WWW2016-Proceedings/proceedings/p357.pdf

I've tried uploading an unlisted video and playing in multiple times and saw that the counter increased. Probably I'm a "trusted" user by Youtube.

> > Is there any particular reason that it's done that way?
> 
> Yes, to have an easy-to-understand metric. And it helps to limit easy views manipulation. We did not designed this counter to be as big as possible.

Fair enough. It's probably not worth doing to write a super complex algorithm to catch those extra views per hour and IP address, but maybe we can change the maximum watches per hour and IP to 3 instead of 1?
