### ISSUE TITLE
create-import-video-file-job fails with SQL error

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#3670]
**Describe the current behavior**

I'm still trying to clean up the mess after an ffmpeg upgrade left me with several broken videos. After restoring an earlier (non-truncated) version of the file from a zfs snapshot, I'm trying to use create-import-video-file-job to replace the file:

```
# (with NODE_ENV and NODE_CONFIG_DIR set)
peertube@tuber:~/peertube-latest$ node dist/scripts/create-import-video-file-job.js -v 35f310a7-5b33-4b15-9f3b-95e3b2d61c3d -i /var/www/peertube/storage/tmp/saved-720.mp4 
Import job for video 35f310a7-5b33-4b15-9f3b-95e3b2d61c3d created.
```

The video file import job runs on the server briefly, then I see an error from the corresponding transcoding job which seems to have lost its UUID parameter at some point:

```
{"level":"info","message":"Processing video file in job 47422.","label":"diode.zone:443","timestamp":"2021-01-29T21:12:11.065Z"}
{"level":"error","message":"Cannot execute job 47422 in queue video-transcoding.","label":"diode.zone:443","payload":{"type":"hls","copyCodecs":true},"err":{"
stack":"Error: WHERE parameter \"uuid\" has invalid \"undefined\" value\n    at PostgresQueryGenerator.whereItemQuery (/var/www/peertube/versions/peertube-v3.
0.1/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2258:13)\n    at Utils.getComplexKeys.forEach.prop (/var/www/peertube/versions/peertube-v3
.0.1/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2247:25)\n    at Array.forEach (<anonymous>)\n    at PostgresQueryGenerator.whereItemsQue
ry (/var/www/peertube/versions/peertube-v3.0.1/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2245:35)\n    at PostgresQueryGenerator.getWher
eConditions (/var/www/peertube/versions/peertube-v3.0.1/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2663:19)\n    at PostgresQueryGenerato
r.selectQuery (/var/www/peertube/versions/peertube-v3.0.1/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1316:28)\n    at PostgresQueryInterf
ace.select (/var/www/peertube/versions/peertube-v3.0.1/node_modules/sequelize/lib/dialects/abstract/query-interface.js:939:27)\n    at Function.findAll (/var/
www/peertube/versions/peertube-v3.0.1/node_modules/sequelize/lib/model.js:1753:47)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","messag
e":"WHERE parameter \"uuid\" has invalid \"undefined\" value"},"timestamp":"2021-01-29T21:12:11.097Z"}
```

**Describe the expected behavior**

It would be great if there was a supported and non-destructive way to re-run transcodes, but at minimum it would be good for this tool to work as documented.

**Additional information**

* PeerTube instance:
  * URL: diode.zone
  * version: 3.0.1
  * NodeJS version:
  * Ffmpeg version: git

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by scanlime** [comment]
In case other admins hit this issue, one terrible but functional workaround seems to be uploading the file elsewhere (e.g. privately as admin, or even on another server) and then renaming the files to use the original uuid. For example,

```
#!/bin/bash
FROM=$1
TO=$2
set -xe
cd ~/storage/streaming-playlists/hls/$TO
mkdir -p backup
mv *.m3u8 *.mp4 *.json backup
cp ../$FROM/* ./
perl -pi -e s/$FROM/$TO/g *.json *.m3u8
rename -e s/$FROM/$TO/ *.mp4
```

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/69eddafb17c4cf8e5a6dbd19e6d216c58140d153
