### ISSUE TITLE
Custom fields via rest api

### ISSUE THREAD

**Issue by geco** [Chocobozzz/PeerTube#3674]
Probably my previous question wasn't clear enough (https://github.com/Chocobozzz/PeerTube/issues/3667)

@Chocobozzz the question is: Can i use/send pluginData (or any custom field) alongside POST /video/imports rest api call? https://docs.joinpeertube.org/api-rest-reference.html#tag/Video/paths/~1videos~1imports/post

I can't see any custom field here: https://github.com/Chocobozzz/PeerTube/blob/develop/server/controllers/api/videos/import.ts

Thanks!

**Comment by Chocobozzz** [comment]
Please don't open duplicated issue, I still can answer to your previous one :) https://github.com/Chocobozzz/PeerTube/issues/3667
