### ISSUE TITLE
Video files of imported video deleted during transcoding not deleted

### ISSUE THREAD

**Issue by stevenroose** [Chocobozzz/PeerTube#3675]
**Describe the current behavior**
When a video gets deleted during the transcoding process, it seems that some artefacts of the video stay behind.

**Steps to reproduce:**

1. Import a video from youtube.
2. Go to the published page and click the three-dot-context-menu and click "Delete".

**Describe the expected behavior**
The video gets deleted, together with all related files.

**Additional information**
There are currently 2 videos on my test instance and I see three directories in my `streaming-playlists/hls` folder. 2 of them match with the ids of the videos and they have multiple formats prepared. This one has only one format and is the ID of the video I removed during the process:
```
$ ls -ahl /data/storage/peertube/streaming-playlists/hls/0551d792-0357-47dc-9495-fcddb1de72f7/
total 292M
drwxr-xr-x 2 peertube peertube    4 Jan 31 23:09 .
drwxr-xr-x 5 peertube peertube    5 Jan 31 23:09 ..
-rw-r--r-- 1 peertube peertube 292M Jan 31 23:09 0551d792-0357-47dc-9495-fcddb1de72f7-1080-fragmented.mp4
-rw-r--r-- 1 peertube peertube  34K Jan 31 23:09 1080.m3u8
```

* PeerTube instance:
  * URL: n/a
  * version: 3.0.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/aaedadd5386b580e9ebac540201399c25c7f0b0f

Please ask for the reopening if this is not the case :)
