### ISSUE TITLE
Change thumbnail filename upon image update

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3678]
**Describe the problem to be solved**
When a video thumbnail/preview image is changed the URI doesn't change, which means that the old image is still cached in browsers and CDN.

**Describe the solution you would like:**
When a new image is uploaded, change the filename so that it's always safe to cache the pictures forever (which will lead to a better user experience).

**Describe alternatives you have considered**
Instead of updating existing row in `thumbnail` table, create a new row with a new filename.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/3740
