### ISSUE TITLE
Clicking on main logo does not redirect to Default client route

### ISSUE THREAD

**Issue by DavidLibeau** [Chocobozzz/PeerTube#368]
* **PeerTube version or commit:** beta.1

* **What is the expected behaviour?** When you click on the main logo (`#peertube-title`) you should be redirected to your `instanceDefaultClientRoute`.
* **What do you see instead?** You are redirected to `/videos/recently-added`.

**Comment by DavidLibeau** [comment]
Coded here : https://github.com/Chocobozzz/PeerTube/blob/066e94c5382a761180c7d82fa24b31b66dbeaca4/client/src/app/videos/videos-routing.module.ts#L19

**Comment by Chocobozzz** [comment]
Thanks, it's fixed: https://github.com/Chocobozzz/PeerTube/commit/29f9b56205f03c8a1da889fb451da12820d9262e
