### ISSUE TITLE
Shorter URLs for videos, accounts and channels

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#3680]
We have long URLs in PeerTube and we would like to have shorter ones (while keeping the old ones) in the client.

 * For videos: `/v/:uuid` (+ https://github.com/Chocobozzz/PeerTube/issues/534 but it requires more work)
 * For accounts: `/a/:accountName`
 * For channels: `/c/:channelName`

An additional route for actors (so accounts + channels) could also be created: `/@:actorName`

**Comment by kimsible** [comment]
Thanks for creating this issue. I had this in mind for a very long time but forgot to post the issue.

@Chocobozzz accounts and channels URLs (with @:actorName) could be done in a different PR than the vidéos URLs?

**Comment by kimsible** [comment]
@Chocobozzz the shorter URLs for videos has been implemented or do you have a current work on this ?

**Comment by rigelk** [comment]
@kimsible it has been implemented in a1eda903a497857017495f37a1fd3593ba7ab23c

**Comment by kimsible** [comment]
> @kimsible it has been implemented in [a1eda90](https://github.com/Chocobozzz/PeerTube/commit/a1eda903a497857017495f37a1fd3593ba7ab23c), and can be seen at work on peertube2.cpy.re

Thanks it's great ! 
I noticed that /@:actorName doesn't work on peertube2.cpy.ren it redirects to the home, is it freezed ?
