### ISSUE TITLE
Docker redundancy settings

### ISSUE THREAD

**Issue by Saddamus** [Chocobozzz/PeerTube#3686]
Hello, I have added redundancy settings, basing on documentation over custom-environment-variables.yaml 
![image](https://user-images.githubusercontent.com/7191172/106737438-f4f5df80-6616-11eb-9897-d642aa597b76.png)

This is screen from docker env values:
![image](https://user-images.githubusercontent.com/7191172/106737180-a8120900-6616-11eb-8739-37bd00e4c55a.png)

Instance is crashing with above settings:
![image](https://user-images.githubusercontent.com/7191172/106737252-bfe98d00-6616-11eb-8759-c50493e18491.png)

What can be wrong ?

**Comment by Chocobozzz** [comment]
Hi,

We don't have the redundancy config in [https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/config/custom-environment-variables.yaml](custom-environment-variables.yaml). Did you add them yourself?

Anyway, the `strategies` field is an array so you must have the `-`: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L124

**Comment by Saddamus** [comment]
Yes, added myself as on the screen and passed values over env.
Thanx for the reply, going to check it :)

**Comment by Saddamus** [comment]
Im sorry for disturbing, but still does not work. What did i wrong ?
![image](https://user-images.githubusercontent.com/7191172/106904680-c1d94c00-66fb-11eb-9199-8eee5d707776.png)
![image](https://user-images.githubusercontent.com/7191172/106906395-6b6d0d00-66fd-11eb-8104-e6fa7ed55110.png)

**Comment by Chocobozzz** [comment]
Unfortunately it seems array are not supported https://github.com/lorenwest/node-config/issues/472
