### ISSUE TITLE
 Instance tracking issue

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#3687]
If you manually remove instances from the list of subscribers, and then add them again, they will appear on my instance in the list, but there will be no feedback. It's hard for me to explain it ...

For example:
I have **instance1**
Another owner - **instance2**
The owner of **instance2** removed my **instance1** from the list and then added it again. Now I do not see on my copy that he is following me.

Is this a bug?

I also manually deleted all subscribers a long time ago, after that they stopped appearing in the list. I have automatic tracking and adding public instances set, the tracking address is specified https://instances.joinpeertube.org

* PeerTube instance:
  * URL: https://peervideo.ru
  * version: PeerTube v.3.0.1
  * NodeJS version: 12.20.1
  * Ffmpeg version: 4.1.6-1~deb10u1
  * Yarn version: 1.22.5
  * OS: Debian 10.5
  * G++: 8.3.0 (Debian 8.3.0-6)

Browser: Google Chrome 87.0.4280.141 (64 bit)

**Comment by rigelk** [comment]
> I also manually deleted all subscribers a long time ago, after that they stopped appearing in the list

It sounds like your manual deletion takes precedence.

**Comment by Alterak** [comment]
> It sounds like your manual deletion takes precedence.

I believe that even after manual deletion, all public instances should be found again, except those that are blacklisted. After all, I have activated the automatic search and add function.

**Comment by rigelk** [comment]
@Alterak this is not the same thing

**Comment by Chocobozzz** [comment]
Hello,

I tried to follow your instance using peertube2.cpy.re, then unfollow & follow again and I don't see any issue. Your instance correctly listed peertube2.cpy.re as a follower;

**Comment by Alterak** [comment]
> I tried to follow your instance using peertube2.cpy.re, then unfollow & follow again and I don't see any issue. Your instance correctly listed peertube2.cpy.re as a follower;

You are right, the subscription worked correctly

![Screenshot_1](https://user-images.githubusercontent.com/11453567/107676974-c927c900-6caa-11eb-8c71-81c15884c287.png)
