### ISSUE TITLE
Upload failing after configuring s3fs

### ISSUE THREAD

**Issue by mj-saunders** [Chocobozzz/PeerTube#3688]
Not sure yet if this is a bug, but I assume it's an error on my part.

Set up s3fs inside a `lxc` container. Running `arch` linux on container and host. Up to date. Also updated to `peertube v3.0.1`

The instance behaves as expected when serving content - nginx now redirects request directly to s3 server, but prior to that it also functioned (though extremely slowly) when using our server effectively as a proxy.

**We are now unable to fully upload new videos though.**
The videos upload successfully to `storage/tmp/`, but fail when attempting to rename (move) to `storage/videos/`.

It looks like a permissions issue, but all directories are owned by the `peertube` user.

These are the only related errors I can find in the logs:
```
2021-02-02 14:17:00.467 error: Cannot execute addVideo with many retries. {
  "err": {
    "stack": "Error: EACCES: permission denied, rename '/var/www/peertube/storage/tmp/9da646dbec192fd0c3b2ef98b8c2f4f7.mp4' -> '/var/www/peertube/storage/videos/9bd0cc12-750>
    "message": "EACCES: permission denied, rename '/var/www/peertube/storage/tmp/9da646dbec192fd0c3b2ef98b8c2f4f7.mp4' -> '/var/www/peertube/storage/videos/9bd0cc12-7500-469>
    "errno": -13,
    "code": "EACCES",
    "syscall": "rename",
    "path": "/var/www/peertube/storage/tmp/9da646dbec192fd0c3b2ef98b8c2f4f7.mp4",
    "dest": "/var/www/peertube/storage/videos/9bd0cc12-7500-469a-ba46-53956930e56e-1080.mp4"
  }
}
2021-02-02 14:17:00.468 error: Error in controller. {
  "err": "Error: EACCES: permission denied, rename '/var/www/peertube/storage/tmp/9da646dbec192fd0c3b2ef98b8c2f4f7.mp4' -> '/var/www/peertube/storage/videos/9bd0cc12-7500-46>
}
```

```
$ uname -a
   Linux hostname 5.9.1-arch1-1 #1 SMP PREEMPT Sat, 17 Oct 2020 13:30:37 +0000 x86_64 GNU/Linux
```

Referenced the following for set up:

- https://docs.joinpeertube.org/admin-remote-storage
- https://wasabi-support.zendesk.com/hc/en-us/articles/360015106031-What-are-the-service-URLs-for-Wasabi-s-different-regions-
- https://wasabi-support.zendesk.com/hc/en-us/articles/115001744651-How-do-I-use-S3FS-with-Wasabi-
- https://github.com/s3fs-fuse/s3fs-fuse

**Comment by rigelk** [comment]
Are PeerTube and Nginx running in the same container? If not, that might be a rights translation from an external Nginx (writing the file first) to the container's PeerTube rights that gets lost.

**Comment by mj-saunders** [comment]
@rigelk That could be the issue. nginx is running in a separate container.
But would that not have caused a problem before I switched to using s3fs?

I forgot to mention, the instance has been running fine for some months. I just switched to s3fs and moved the (originally) local files to the s3 directory.

Also, thanks for correcting the title.

**Comment by rigelk** [comment]
Maybe that s3fs doesn't have the same rights running that the PeerTube process then.

**Comment by mj-saunders** [comment]
will try and find out. Hoping it is something trivial :)

All I find odd is when using the `peertube` user directly, I can write to and modify the s3fs directory (that's how I moved the originally local videos).

**Comment by mj-saunders** [comment]
@rigelk any idea how I can dig deeper into this?
I'm not sure where to look.
All I know is peertube process is owned by peertube user, and if I use that user manually, I can work with the s3fs directory.
The files that get uploaded to `tmp` I can confirm are also owned by peertube user.
Also the s3fs directory is originally mounted by root, but is owned by peertube user.

Only thing I can think of atm is to dig through the source for where the "renaming" is happening, and see what process gets run there.

**Comment by Chocobozzz** [comment]
You could try tu use the node interactive shell, import https://github.com/jprichardson/node-fs-extra and use `move(src, dst)` to understand in what cases it fails

**Comment by mj-saunders** [comment]
thanks @Chocobozzz - will try that

**Comment by mj-saunders** [comment]
So, tested as follows.
The filepaths are exactly from the last EACCES error in journactl log.
The move succeeds.

```
# su - peertube
$ pwd
/var/www/peertube
$ cd peertube-latest
$ node
> fs = require('fs-extra')
> fs.move('/var/www/peertube/storage/tmp/c779a2f178aecd45f3055a7691d595b5.mp4', '/var/www/peertube/storage/videos/ac8bea30-c683-40c2-bf79-eb0522a8793e-720.mp4')
> Ctrl-D
$ ls /var/www/peertube/storage/videos
...
ac8bea30-c683-40c2-bf79-eb0522a8793e-720.mp4
...
```

I also tried by using `root` to `touch` an empty file into `storage/tmp` . With `peertube` user running node, it successfully moved the file and claimed ownership. This seems normal behaviour, I assume because the directory is owned by `peertube`.
Not sure how to make it fail in the same way as in the log.

The original error states that "renaming" failed, but I presume that `move()` is actually the function being called, which is what I would expect.

**Comment by Chocobozzz** [comment]
How do you run peertube?

**Comment by mj-saunders** [comment]
systemd service.

and in case it wasn't clear, things have been working fine, until I switched over to using s3 bucket (cos we rean out of local server space).

**Comment by Chocobozzz** [comment]
Try to check potential security directives in systemd service: https://github.com/Chocobozzz/PeerTube/blob/develop/support/systemd/peertube.service#L18

**Comment by normen** [comment]
How did you set your S3 ACL and CORS? These settings seem to work for me:
```
ACL:
   {
     "Version": "2012-10-17",
     "Statement": [
       {
         "Effect": "Allow",
         "Principal": "*",
         "Action": "s3:GetObject",
         "Resource": "arn:aws:s3:::peertube/*"
       }
    ]
 }
CORS:
 {
    "CORSRules": [
      {
        "AllowedOrigins": ["*"],
        "AllowedHeaders": ["*"],
        "AllowedMethods": ["GET"],
        "MaxAgeSeconds": 3000
      }
    ]
 }
```

**Comment by mj-saunders** [comment]
@normen this is the policy I set - I'll admit I had to do some research to fathom this much. It's not something I'm familiar with.
If this is the issue, I would still be left not understanding why I could manually work with the mounted disk from our server, using the `peertube` user, but `peertube` itself fails...

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AllowPublicRead",
      "Effect": "Allow",
      "Action": [
        "s3:GetObject",
        "s3:ListBucket"
      ],
      "Resource": [
        "arn:aws:s3:::omn-peertube/videos/*",
        "arn:aws:s3:::omn-peertube/redundancy/*",
        "arn:aws:s3:::omn-peertube/streaming-playlists/*"
      ]
    }
  ]
}
```

**Comment by mj-saunders** [comment]
@normen in which case, maybe this is the equivalent policy you are actually referring to:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "s3:*",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "iam:*",
        "sts:*"
      ],
      "Resource": "arn:aws:iam::${aws:accountid}:user/${aws:username}"
    }
  ]
}
```

**Comment by mj-saunders** [comment]
Currently I can only presume that whatever process that is performing the rename (and file move from `tmp/` to `videos/`) is not owned by `peertube` but that doesn't make sense to me...

**Comment by mj-saunders** [comment]
> Try to check potential security directives in systemd service: https://github.com/Chocobozzz/PeerTube/blob/develop/support/systemd/peertube.service#L18

Thank you!
It appears I set `PrivateDevices = true`.
Back to false and problem appears resolved.
