### ISSUE TITLE
Error: got torrent file with incorrect info hash from xs param...

### ISSUE THREAD

**Issue by imncls** [Chocobozzz/PeerTube#369]
* **PeerTube version or commit:**
v1.0.0-beta.1
* **Browser name/version:**
Google Chrome / 65.0.3325.181
* **NodeJS version:**
v8.10.0
* **PostgreSQL version:**
9.5.12

i get this error on web:
```
Error
got torrent file with incorrect info hash from xs param: https://{example.com}/static/torrents/{random-text}.torrent
```
im currently running 4 instances.
it can play without problems on the uploaded instance, but i get this error on other instances.
but, immediately after uploaded, other instances can play the video.
and this error will be fix if i update the video info (there is no need to change something, just push the update button.) on the uploaded instance.

**Comment by imncls** [comment]
i referenced and installed the latest production guide.

**Comment by Chocobozzz** [comment]
Can you copy paste a link so I can reproduce the issue?

**Comment by imncls** [comment]
sure.
if you meant torrent url, here is torrent url:
https://us.peertube.network/static/torrents/c000a3dd-e4c7-4ba8-b136-89e4bbb4361d-720.torrent

or you meant servers url:
- [au.peertube.network](https://au.peertube.network)
- [gb.peertube.network](https://gb.peertube.network)
- [jp.peertube.network](https://jp.peertube.network)
- [us.peertube.network](https://us.peertube.network)

uploaded on us.peertube.network.
https://us.peertube.network/videos/watch/c000a3dd-e4c7-4ba8-b136-89e4bbb4361d
i cant play on other servers.
https://au.peertube.network/videos/watch/c000a3dd-e4c7-4ba8-b136-89e4bbb4361d
https://gb.peertube.network/videos/watch/c000a3dd-e4c7-4ba8-b136-89e4bbb4361d
https://jp.peertube.network/videos/watch/c000a3dd-e4c7-4ba8-b136-89e4bbb4361d

**Comment by Chocobozzz** [comment]
On us.peertube.network, check your failed jobs. I think there is an issue with your transcoding job.

The video is uploaded and sent to the other instances: it works.
us.peertube.network then transcodes the video, so the infohash changes: it should send the update to the other instances. But I don't know why, the other instances does not receive the update activity.

**Comment by imncls** [comment]
i dont know how that is related to the this issue.
but i found this log.
<img width="1269" alt="2018-03-22 2 13 31" src="https://user-images.githubusercontent.com/28977652/37725590-a5fffc7a-2d76-11e8-83fb-a5d3b9eb2c00.png">

```json
{
  "videoUUID": "a3a99bd9-28c2-42c7-91e3-6161c9b3b7a8"
}
```
```
Error: ENOENT: no such file or directory, unlink '/var/www/peertube/storage/videos/a3a99bd9-28c2-42c7-91e3-6161c9b3b7a8-720.mp4'
```

**Comment by imncls** [comment]
hmmmmm...
this is little strange...
<img width="682" alt="2018-03-22 10 19 27" src="https://user-images.githubusercontent.com/28977652/37745885-bf407f2c-2dba-11e8-9ea9-6452b95b7042.png">

**Comment by Chocobozzz** [comment]
Send me your logfile by email please.

**Comment by imncls** [comment]
Okay.

**Comment by imncls** [comment]
hmm...
I did try to send your email.
`me@florianbigard.com `
But, I got failure notice.
What is your email address?

**Comment by Chocobozzz** [comment]
send to chocobozzz at framasoft dot org

**Comment by imncls** [comment]
Okay~

**Comment by gegeweb** [comment]
I had the same error this morning playing videos from another instance, so I wanted to post a report, so I went back tonight to read the videos to note the messages.

No reproductible tonight with the same videos from the same instance.

**Comment by Chocobozzz** [comment]
This should be fixed: https://github.com/Chocobozzz/PeerTube/commit/a216c6233d46689f73a7c542e6170555b7f287b6

**Comment by imncls** [comment]
thanks chocobozzz~ 💕

**Comment by imncls** [comment]
when will the release a new version of include this fix?

**Comment by Chocobozzz** [comment]
next week

**Comment by imncls** [comment]
okay thanks

**Comment by gegeweb** [comment]
Same error for me with : 
https://peertube.gegeweb.eu/videos/watch/fb7a1aec-1a3d-4ebd-8878-6ae51d12130a

On the original instance, no problem.

Hope this is the same fixed issue.
