### ISSUE TITLE
Adding basic cutting feature

### ISSUE THREAD

**Issue by pprw** [Chocobozzz/PeerTube#3690]
It would be very nice to be able to cut video directly after uploading to peertube.

By "cutting", I mean only to remove some part at the beginning or the end (`-ss` and `-to` options of ffmpeg). Visioconference recordings are often started a little before the actual beginning of the conference and you want sometimes to cut the questions at the end. This feature would answer to these needs and allows someone which is not comfortable to use ffmpeg or else to cut videos.

**Comment by rigelk** [comment]
applying the same tags as related: https://github.com/Chocobozzz/PeerTube/issues/1399 (another video edition feature request)

**Comment by Chocobozzz** [comment]
Closing as it's out of the scope of peertube. You can write a wrapper to download the video, cut and reimport using PeerTube CLI tools: https://docs.joinpeertube.org/maintain-tools
