### ISSUE TITLE
Remember video playback position, when not logged in or signed up

### ISSUE THREAD

**Issue by raucao** [Chocobozzz/PeerTube#3692]
**Describe the problem to be solved**

Currently, when leaving or reloading a video page during playback (or when the video is paused), the player starts the video from the very beginning when you return to the page. I'm very used to YouTube remembering the playback position, so I don't have to.

**Describe the solution you would like:**

Save current playback position in local browser storage every other second or so. Use that position when loading a video page.

**Describe alternatives you have considered**

I don't see any, off the top of my head.

**Comment by rigelk** [comment]
Note that this is already a feature for logged in users

**Comment by raucao** [comment]
Great! I have changed the title to make that clear.

**Comment by rigelk** [comment]
Currently solved as a side-effect of #3885.
