### ISSUE TITLE
End Screens (Youtube style)

### ISSUE THREAD

**Issue by skeutmeier** [Chocobozzz/PeerTube#3696]
**There is no End-Screen (as seen on youtube)**

In the last few seconds of a youtube video, it is possible for the uploader to make a so-called end-screen. This feature is limited to only the last 20 seconds and can be modified to start even later. So the uploader can modify the end-screen on a per-video basis to last only 10 secs for example.
The end screen can be put together from a few different "objects".
These "objects are":
- Link to specific video (thumbnail with title)
- Link to unspecified video (automatically choosen based on viewer preferences) (thumbnail with title)
- Link to Playlist (thumbnail with title)
- Link to channel page
- Subscribe button

There are a few Layouts you can choose from. You can then place 1 or multiple objects in the layout. A  End-screen can be saved as template to use in other video later on.

**I would like to see a similar feature in peertube**

This would help to get youtubers onboard. Endscreens are a important method to keep viewers watching videos from the same channel, and to help them to subscribe

**Alternative**  

Possible to combine with "info-card" feature. I see a few similarities. If the info-card feature is build with more features, i would be possible to create endscreen by yourself

**Comment by Chocobozzz** [comment]
See https://github.com/Chocobozzz/PeerTube/issues/3698#issuecomment-775205307
