### ISSUE TITLE
ELIFECYCLE on `npm run setup:cli`

### ISSUE THREAD

**Issue by febeling** [Chocobozzz/PeerTube#3697]
**Describe the current behavior**

When trying to build the CLI tools, the script fails with an error. See below for pastebin.

**Steps to reproduce:**

1. git clone
2. NOCLIENT=1 yarn install --pure-lockfile
3. npm run setup:cli

See full shell session for details: https://gist.github.com/febeling/266ba9fd56d681881683afad5b9fc021

**Describe the expected behavior**

Successful build.

**Additional information**

* PeerTube instance:
  * URL: n/a
  * version: master (9162476fe9fe022ff24bd42ff828aca7c68129ef)
  * NodeJS version: v10.19.0
  * Ffmpeg version: 4.2.4-1ubuntu0.1

* Browser name, version and platforms on which you could reproduce the bug: n/a
* Link to browser console log if relevant: -
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): -

**Comment by febeling** [comment]
I've just seen that nodejs 10 is deprecated. I'll report if moving to 12 changes anything.

**Comment by rigelk** [comment]
Please stay on release tags and associated dependencies

**Comment by febeling** [comment]
Okay. Conflicts with documentation though: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#installation
```
$ git clone https://github.com/Chocobozzz/PeerTube.git
$ CLONE="$(pwd)/PeerTube"
$ cd ${CLONE}
```

**Comment by rigelk** [comment]
You can, but then you should follow the dependencies guide from the associated commit.
