### ISSUE TITLE
Info-Cards (Youtube style)

### ISSUE THREAD

**Issue by skeutmeier** [Chocobozzz/PeerTube#3698]
**It is not possible to link to another video at the right moment**

Often times when making a video, I reference another video I made (deeper explanation of a situation, problem, you name it).
There is no option to "send" a viewer to a different video at the right time.

**Youtube solved this problem with Info Cards**

Youtube has a feature called "Info Cards". This allows the uploader of a video to link to another video at a specific timestamp in the video. (I will add screenshots of the backend and frontend)
That way, when I make a reference to another video, a clickable link pops up and the viewer can decide to click the link for further information.

**Alternative**  

Combine this with "End-screens" as there is a ovelrlap in features.

At the moment I referenced another video, a link pops up at the top left corner
![Screenshot from 2021-02-04 17-35-20](https://user-images.githubusercontent.com/73367887/106924539-74ff7080-670f-11eb-960d-571349c98429.png)
Clicking on the Info-Icon provides a scrollable list of all linked videos (in this case 2)
![Screenshot from 2021-02-04 17-35-31](https://user-images.githubusercontent.com/73367887/106924536-7466da00-670f-11eb-8be6-ac6ca88357bc.png)

Here I linked a video at 33 seconds.
![Screenshot from 2021-02-04 17-34-42](https://user-images.githubusercontent.com/73367887/106924544-75980700-670f-11eb-9979-d7c4143fa0f4.png)
And the second video I linked at 3 min 57 sec
![Screenshot from 2021-02-04 17-35-00](https://user-images.githubusercontent.com/73367887/106924543-75980700-670f-11eb-8581-fefac30b5cfc.png)

**Comment by Chocobozzz** [comment]
Hi and thanks for the issue. I suggest to create a plugin that uses the `action:video-watch.player.loaded` hook: https://docs.joinpeertube.org/api-plugins?id=hooks

See also the annotation plugin: https://www.npmjs.com/package/peertube-plugin-video-annotation
