### ISSUE TITLE
Ugly display of avatars

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#3699]
I want to suggest making a standard placeholder for all missing user avatars, channel images, playlists. This is necessary because it looks very ugly against the general background ... for example:

![Screenshot_1](https://user-images.githubusercontent.com/11453567/106935227-21e7e680-672c-11eb-828e-0354344a6ce5.png)
![Screenshot_2](https://user-images.githubusercontent.com/11453567/106935239-257b6d80-672c-11eb-81bd-ffde28e3031f.png)

To use a common stub, you can take your logo Peertube

**Comment by rigelk** [comment]
We already have a stub

**Comment by Alterak** [comment]
> We already have a placeholder, so something is wrong with your reverse proxy configuration

I haven't changed anything in the configuration. When installing version 3.0.1, I even installed a new NGINX and PEERTUBE config file, replaced only the server address and mail settings. Probably the problem remained in the database, which I did not touch.

**Comment by JigmeDatse** [comment]
If I remember (and things can also change) PeerTube fetches the remote avatar, and serves it locally.  And if it fails to fetch, it uses the default.  Now, I *think* that I've seen stuff like this for newly followed instances, or new users.  It can take a bit if for some reason it's having trouble with the avatar.  But then I think I've not had an instance up for about 10 months...

**Comment by Alterak** [comment]
> If I remember (and things can also change) PeerTube fetches the remote avatar, and serves it locally. And if it fails to fetch, it uses the default. Now, I _think_ that I've seen stuff like this for newly followed instances, or new users. It can take a bit if for some reason it's having trouble with the avatar. But then I think I've not had an instance up for about 10 months...

I noticed that only one server had problems with the avatar ... I stopped tracking it and now everything is normal. I don't see any more problematic avatars. Thanks.
