### ISSUE TITLE
Peertube crashed upon creating public playlist

### ISSUE THREAD

**Issue by angus6b23** [Chocobozzz/PeerTube#3701]
**Describe the current behavior**
Peertube crashed upon creating public playlist

**Steps to reproduce:**

1. Create a playlist with privacy set as "public" 
2. Peertube redirect to playlist page successfully
3. Peertube no longer responses to other pages

**Describe the expected behavior**
Peertube continue to response after creating the playlist

**Additional information**
The peertube thread pick up 100% cpu on top/htop
Browser console:
Successful: Playlist New playlist was created
Connection failed when loading page with wss://domain.name/socket.io/?accessToken=*token*&EIO=4&transport=websocket&sid=g8jA6-8E4vGjjcH_AAAI
Further requests got 504 Gateway Timeout responses

* PeerTube instance:
  * URL: --private instance--
  * version: v3.0.1
  * NodeJS version: v10.23.1
  * Ffmpeg version: v4.1.6

* Browser name, version and platforms on which you could reproduce the bug:
Firefox Developer version v86.0b5 on Debian

* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
Relevant log (debug level)
https://pastebin.com/L4TR8Ywi

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/3933a127d26f5f3e4d76f533e9bc002ae92680c4
