### ISSUE TITLE
Large video thumbnail updates still don't work

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#3705]
This regex shouldn't be anchored to the end of the string, the actual URLs for these thumbnail uploads are a PUT to .../videos/(id number).

https://github.com/Chocobozzz/PeerTube/blob/9162476fe9fe022ff24bd42ff828aca7c68129ef/support/nginx/peertube#L81

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/6c7317a0a363a609e7bffc4306aef482bda088f1
