### ISSUE TITLE
Video imports from youtube are stuck in pending state

### ISSUE THREAD

**Issue by dimitar-petrov** [Chocobozzz/PeerTube#3706]
**Describe the current behavior**
I am failing to import any video from youtube. 
It is docker deployment: peertube@3.0.1
Tried to recreate the containers with no success
Is it possible that there is a data inconsistency in the DB.

**Steps to reproduce:**

1. Add a video from youtube

**Describe the expected behavior**

**Additional information**

### Logs

This is what I see in jobs video-import:

```
Job: 12
Type: video-import
Processed on -
Finished on -
{
  "type": "youtube-dl",
  "videoImportId": 17,
  "generateThumbnail": false,
  "generatePreview": false,
  "fileExt": ".mp4"
}
```

 When I try to list transcoding jobs I get the following error
```
peertube_1  | [***.com:443] 2021-02-05 21:01:39.343 error: Error in controller. {
peertube_1  |   "err": "TypeError: Cannot read property 'timestamp' of null
at /app/dist/server/lib/job-queue/job-queue.js:124:24
at Array.sort (<anonymous>)
at JobQueue.<anonymous> (/app/dist/server/lib/job-queue/job-queue.js:123:21)
at Generator.next (<anonymous>)
at fulfilled (/app/node_modules/tslib/tslib.js:114:62)
at processTicksAndRejections (internal/process/task_queues.js:97:5)"
```

Thanks,

**Comment by Chocobozzz** [comment]
> Is it possible that there is a data inconsistency in the DB.

You mean in Redis? Then try to use `redis-cli` in the Redis container, and see job keys using `keys bull-*`. You can then try to see what is their content and/or delete them if it can help.

**Comment by dimitar-petrov** [comment]
Cleaned the redis keys and triggered another import.

This is what redis got populated with after the import:

```
/data # redis-cli --raw keys "bull-*"
bull-tube.example.com:video-import:wait
bull-tube.example.com:video-import:1
bull-tube.example.com:video-redundancy:stalled-check
bull-tube.example.com:video-import:id
bull-tube.example.com:activitypub-http-broadcast:stalled-check
```
Again the import is stuck and I see the same error when try to list transcoding jobs:

```
[tube.finxploit.com:443] 2021-02-09 06:33:34.746 error: Error in controller. {
  "err": "TypeError: Cannot read property 'timestamp' of null\n    at /app/dist/server/lib/job-queue/job-queue.js:124:24\n    at Array.sort (<anonymous>)\n    at JobQueue.<anonymous> (/app/dist/server/lib/job-queue/job-queue.js:123:21)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
 ```
Any help how to debug further is appreciated.
Thanks.

**Comment by dimitar-petrov** [comment]
Here are the values also:

```
/data # for each in $(redis-cli --raw keys "bull-*"); do echo $each $(redis-cli get $each); done
bull-tube.example.com:video-import:wait WRONGTYPE Operation against a key holding the wrong kind of value
bull-tube.example.com:video-import:1 WRONGTYPE Operation against a key holding the wrong kind of value
bull-tube.example.com:video-redundancy:stalled-check 1612852737697
bull-tube.example.com:activitypub-refresher:stalled-check 1612852737694
bull-tube.example.com:video-import:id 1
bull-tube.example.com:video-import:stalled-check 1612852737694
bull-tube.example.com:activitypub-http-broadcast:stalled-check 1612852737693
bull-tube.example.com:video-live-ending:stalled-check 1612852737698
```

**Comment by Chocobozzz** [comment]
Try to use `HGETALL` operation on import keys. Also, what is your redis version?

**Comment by dimitar-petrov** [comment]
Redis docker image: redis:4-alpine

```
/data # redis-cli --version
redis-cli 4.0.14
```

Here is a paste of the key/values of redis: http://ix.io/2OOL

**Comment by Chocobozzz** [comment]
Try to remove all these keys, or recreate the redis data file. Try also to upgrade to latest redis.

**Comment by dimitar-petrov** [comment]
OK, upgrading to redis and removing dump rdb fixed the import.

Now I see video-transcoding job in state "WAITING".
When is it supposed to start.

**Comment by Chocobozzz** [comment]
It should start as soon as there is no other transcoding job being processed.
