### ISSUE TITLE
Livepeer transcoding 

### ISSUE THREAD

**Issue by PatriotDevOps** [Chocobozzz/PeerTube#3708]
**Describe the problem to be solved**

FFMPEG transcoding doesn’t scale to high volume. Inefficient transcoding. 

**Describe the solution you would like:**

I suggest that we add integration with the livepeer decentralized video transcoding service. It recently became production ready and would provide much needed scalability for high volume transcoding. You could add options to the configuration file to choose ffmpeg or configure livepeer transcoding.

**Describe alternatives you have considered**

**Comment by Chocobozzz** [comment]
Closing in favour of https://github.com/Chocobozzz/PeerTube/issues/947
