### ISSUE TITLE
Error adding image

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#3709]
I have 2 different versions of Peertube installed:
v. 3.0.1
v. peertube-nightly-2021-02-06
***************************************
NGINX v. 1.18.0

When I create a live stream and add an image preview with a resolution of 1920x1080, 803KB and a .JPG extension, the error appears. The tooltip says only about the size no more 2MB

I apologize if this has already been reported earlier. But I didn't see.

![Screenshot_1](https://user-images.githubusercontent.com/11453567/107123999-fbec4e80-68b1-11eb-872f-9fd996f6daf0.png)

**Comment by Chocobozzz** [comment]
I think it's the same of https://github.com/Chocobozzz/PeerTube/issues/3705 so closing this one :)
