### ISSUE TITLE
Add LDAP user backend

### ISSUE THREAD

**Issue by tigre-bleu** [Chocobozzz/PeerTube#371]
Clearly not a top priority, but it would be nice to support LDAP integration as Mastodon does.

I would be happy to provide peertube service to my users when this will be implemented.

**Comment by thegcat** [comment]
Same here.

**Comment by anmol26s** [comment]
Hi
This would be priority feature for YunoHost too.

**Comment by rigelk** [comment]
Looking rapidly at what's available I found [vesse/passport-ldapauth](https://github.com/vesse/passport-ldapauth). Maybe we could use that for the implementation.

**Comment by meoso** [comment]
this is what's keeping us from implementing.  we would need to auth with Active Directory and integrate with Moodle somehow.

**Comment by rigelk** [comment]
@meoso what do you mean by "integrate with Moodle"?

**Comment by meoso** [comment]
sorry, our Moodle authenticates with Acitve Dir (LDAP), that's all.  Maybe we would just embed URL links into moodle. (not really my job function, i just know we need "something" to serv video much like a youtube clone and i really like the p2p offload of PeerTube)

**Comment by ShenZhouHong** [comment]
I think integration with LDAP or some other form of Single Sign On authentication is more important than we think. Although it's a bit of an "enterprise-y" feature, some users are hosting decentralised "cyber-collectives" where federation services like Mastodon, Nextcloud, and Matrix are all offered under one URL and umbrella. All 3 of these services support LDAP, which makes it trivial to have a central registration page, so users automatically get accounts on all 3 of the services without any hassle. If Peertube supports an SSO backend, it would make it even easier to integrate :)

**Comment by Thatoo** [comment]
I'm also waiting for LDAP support to install Peertube (and mastodon) on my familly yunohost [CHATONS](http://chatons.org/) server.

**Comment by WingsLikeEagles** [comment]
How about CAS authentication, that way people can use whatever auth they want to implement (ldap, x.509, 2 factor, etc).
https://www.apereo.org/projects/cas

**Comment by ldidry** [comment]
> How about CAS authentication, that way people can use whatever auth they want to implement (ldap, x.509, 2 factor, etc).

True, but putting up a working CAS is not so easy. Not as easy as a setting LDAP configuration in peertube conf.

I think that adding CAS authentication would be a good thing, but not for that reason.

**Comment by meoso** [comment]
I know the dev-ops team here is implementing CAS with our moodle, so here is a +1.

**Comment by immae** [comment]
Hey there,
Just so that we’re not duplicating workforce:
I started working on that feature yesterday, and I have a working change on my instance. It’s not shareable yet (hardcoded values etc.), and will probably need some adjustment for the final result, but it’s working smoothly so far.

**Comment by WingsLikeEagles** [comment]
@immae I am excited to see what you produce.  We are currently implementing YouPHPTube, but if this feature is added I will push for peertube.

**Comment by immae** [comment]
@WingsLikeEagles well I sent a PR yesterday evening: https://github.com/Chocobozzz/PeerTube/pull/1626 you can already start using it (I do :p ) :), the patch applies well on top of current released version ;)

**Comment by Thatoo** [comment]
@immae is there any news on this subject?
So far, none of the major fedivers app have a working LDAP system to work on yunohost, not mastodon, not peertube, not pixelfed... 
I hope that if one solve the issue, the other could follow.

**Comment by immae** [comment]
@Thatoo I’m sorry, I have a working PR (https://github.com/Chocobozzz/PeerTube/pull/1626), but there are too much changes required and I don’t have time at the moment. Note that mastodon has an LDAP integration, developped my myself too, and this one is merged since long :)

**Comment by Thatoo** [comment]
@immae I know mastodon has an LDAP integration but it doesn't work with Yunohost for some reason I don't understand : 
https://github.com/YunoHost-Apps/mastodon_ynh/issues/67
https://github.com/tootsuite/mastodon/issues/6991
https://discourse.joinmastodon.org/t/ldap-configuration-help-needed/1352/2

**Comment by Thatoo** [comment]
Pixelfed project even closed the LDAP issue, https://github.com/pixelfed/pixelfed/issues/388, saying that LDAP is something that can be achieved with a laravel package (https://github.com/Adldap2/Adldap2-Laravel).

I don't really understand what that means and involve but the result is that none of the major fediverse app have a working LDAP system to work on yunohost (except Osada I think).

I believe that for fediverse to express its true potential, it needs to spread as much as possible, one mastodon instance hosted by one [chatons] associations, one pixelfed instance hosted by one family and one peertube instance hosted by a media... and yunohost is the great tool to help CHATONS to spread fediverse!
Hopefully!

**Comment by Thatoo** [comment]
It seems that pleroma manage to implement LDAP, https://git.pleroma.social/pleroma/pleroma/issues/203, and yalh76, the maintainer of the yunohost pleroma package is working on it, https://github.com/YunoHost-Apps/pleroma_ynh/issues/28 .
Maybe their work could help to make LDAP coming on more fediverse package [on Yunohost].

**Comment by Chocobozzz** [comment]
Implemented in a plugin: https://framagit.org/framasoft/peertube/official-plugins/-/tree/master/peertube-plugin-auth-ldap

Only available in the next peertube release (2.2) at the end of May
