### ISSUE TITLE
Question system for live

### ISSUE THREAD

**Issue by tclavier** [Chocobozzz/PeerTube#3710]
**Describe the problem to be solved**

As a speaker during a live I want to have the list of questions from viewers ordered by popularity.

**Describe the solution you would like:**

During the live, all viewers can submit a question or vote to a submitted question. All viewers can also view all questions.

When the speaker has answer a question, he can remove the question.

**Describe alternatives you have considered**

**Comment by Chocobozzz** [comment]
Hello and thanks for the issue, but for now this feature request is out of the scope of PeerTube. We recommand you to use a dedicated platform where you can embed a PeerTube video.
