### ISSUE TITLE
Cannot replay live streamed videos

### ISSUE THREAD

**Issue by alejandrocobo** [Chocobozzz/PeerTube#3711]
I recently upgraded to Peertube 3.0.1. I'm unable to replay live stream videos that has ended. I have tried both "Automatically publish a replay when your live ends" enabled and disabled but when I go to the ended session, it shows just a black screen. There are no quota excesses.

What am I doing wrong?

Thanks.

**Comment by Chocobozzz** [comment]
Please fill the bug template so we can help you: https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/00-bug-issue.md

**Comment by alejandrocobo** [comment]
> Please fill the bug template so we can help you: https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/00-bug-issue.md

I've been testing and ends up that it works only if "Privacy" is not "Private". If this is the expected behavior, please, ignore this report. I've been trying it just with private live streams until now ("Unlisted" seems to work fine).

**Describe the current behavior**
When I end a private live transmission I cannot replay it even if I've marked "Automatically publish a replay when your live ends".

**Steps to reproduce:**

1. Go to https://video.hardlimit.com or https://tubedu.org
2. Go live with Private Privacy. 
3. Mark "Automatically publish a replay when your live ends"
4. Start a live stream
5. End it.

**Describe the expected behavior**
Once live streaming ends, I should be able to replay the video.

**Additional information**

* PeerTube instance:
  * URL: https://video.hardlimit.com and https://tubedu.org
  * version: 3.0.1
  * NodeJS version: v12.20.1
  * Ffmpeg version: 4.1.6-1~deb10u1
  * OBS version: 23.1.0
  * Admin option "Allow your users to automatically publish a replay of their live" marked
  * Admin option "Transcoding enabled for live streams" unmarked (tried with it plus 480p marked with the same result).
  * Admin option "Max live duration": 5 hours.

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by alejandrocobo** [comment]
> What do you mean by " I cannot replay"? Do you have an error or anything else?

No errors, just a black screen.

Here you have a live-streamed video that was born private and was changed to "unlisted" once it ended: 
https://video.hardlimit.com/videos/watch/f4fb423f-c323-4fd0-b6d2-5b468d7d5802

**Comment by alejandrocobo** [comment]
> What do you mean by " I cannot replay"? Do you have an error or anything else?

I am really sorry. I've been doing more tests and it seems that it takes some minutes for the video to be available.

Everything works fine. It's just that when the live-streaming ends, it appears a black screen and it is not possible to replay the video. Some minutes later, the video becomes available.
