### ISSUE TITLE
Videos not loading properly (Range not Satisfiable)

### ISSUE THREAD

**Issue by Casuallynoted** [Chocobozzz/PeerTube#3721]
**Describe the current behavior**
I'm noticing that a lot of my videos are loading very slowly, running the latest version of PeerTube. They take a long time to load and then sometimes the length of the video is inaccurate after loading.

**Steps to reproduce:**

1. Open up instance (my instance is videos.casually.cat)
2. Play video
3. Video does not load properly

**Describe the expected behavior**

Videos should play fairly quickly and the complete video should play

**Additional information**

Checking PeerTube logs, this error occurs every time I try to play a video:
error[2/9/2021, 12:38:12 AM] Error in controller.
{
  "err": "RangeNotSatisfiableError: Range Not Satisfiable\n    at SendStream.error (/Volumes/Docker/tmp/PeertubeBackups/node_modules/send/index.js:270:31)\n    at SendStream.send (/Volumes/Docker/tmp/PeertubeBackups/node_modules/send/index.js:670:19)\n    at onstat (/Volumes/Docker/tmp/PeertubeBackups/node_modules/send/index.js:729:10)\n    at FSReqCallback.oncomplete (fs.js:169:5)"
}

The Nginx logs just show: upstream prematurely closed connection while reading response header from upstream

* PeerTube instance: videos.casually.cat
  * URL: https://videos.casually.cat
  * version: 3.0.1 (Oddly enough it shows as 3.0.1...3.0.1^0)
  * NodeJS version: v12.20.1
  * Ffmpeg version: git-2020-12-13-cd821c1

* Browser name, version and platforms on which you could reproduce the bug: Safari and Firefox, latest on Mac OS (Apple Silicon)

**Comment by Chocobozzz** [comment]
Hi,

We don't support ffmpeg git version. Please use the latest stable.

**Comment by alex9099** [comment]
I'm getting the same error, when trying to load a video on firefox and chromium on android.

Basically it takes a long while to load (no resulutions are shown, but total time shows on the player), eventually it loads after some attempts

**Comment by varun-s22** [comment]
what was the resolution here? I tried showing the edited videos my browser. It gives me the following error
```
videcuttool-server       | [1] RangeNotSatisfiableError: Range Not Satisfiable
videcuttool-server       | [1]     at createHttpError (/app/server/node_modules/send/index.js:984:7)
videcuttool-server       | [1]     at SendStream.error (/app/server/node_modules/send/index.js:270:31)
videcuttool-server       | [1]     at SendStream.send (/app/server/node_modules/send/index.js:666:19)
videcuttool-server       | [1]     at onstat (/app/server/node_modules/send/index.js:725:10)
videcuttool-server       | [1]     at FSReqCallback.oncomplete (node:fs:203:5)
```

On client it gave me FFMPEG_DEMUXER error

**Comment by Chocobozzz** [comment]
@varun-s22 Please create a dedicated issue
