### ISSUE TITLE
Can't delete a user who has open reports against them

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#3722]
**Describe the current behavior**

This has been happening to me a lot while moderating my server. I will usually see a spam account and immediately try to delete the user. But if someone has already filed a report against a video, I can't delete the user itself before deleting the video or the report.

**Steps to reproduce:**

1. Report a video
2. As admin, try to delete the entire account
3. Server 500 error

**Describe the expected behavior**

I expect to be able to delete users even if there have been abuse reports against that user.

**Additional information**

* PeerTube instance:
  * URL: diode.zone
  * version: 3.0.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Please paste the 500 error log from the serveur
