### ISSUE TITLE
Transcode existing Videos from GUI

### ISSUE THREAD

**Issue by roere** [Chocobozzz/PeerTube#3723]
Existing Videos on Peertube can be transcoded now using CLI commands.

To use the CLI commands, the person must be server admin, beeing a Peertube admin is not enough. 

Starting a transcoding job should be possible from the my-library/videos section using the update dialog there.
There could be a new tab called "resolutions", showing all options configured in the config file, with those resolutions checkbox marked, that already exist. By marking or unmarking resolutions in that list, a user could manage the resolutions for the selected video.

  
Alternatively there could be an option for the peertube admin, when he updates the transcoding resolutions for the instance. Something like an "update existing videos" option.

**Comment by maxlinux2000** [comment]
+1

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/ad5db1044c8599eaaaa2a578b350777ae996b068
