### ISSUE TITLE
Custom preview image gets overwritten by import

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3727]
**Describe the current behavior**
When importing a video by URL and uploading a preview image, the preview image gets overwritten by the import job.

**Steps to reproduce:**

1. Import via a URL.
2. Change preview image.
3. Wait until first transcoding is done.

**Describe the expected behavior**
Uploaded a preview image should not be overwritten.

**Additional information**
I guess the issue is that the import job is created before it's possible to change preview image, and therefore the import job has "generateThumbnail: true".

```

Job: 48 Type: video-import Processed on Feb 10, 2021, 10:44:25 AM Finished on Feb 10, 2021, 10:45:55 AM
--
{
   "type": "youtube-dl",
   "videoImportId": 56,
   "generateThumbnail": true,
   "generatePreview": true,
   "fileExt": ".mp4"
}
```

* PeerTube instance:
  * version: 3.0.1

**Comment by Chocobozzz** [comment]
Could you paste the video URL you want to import?

**Comment by kontrollanten** [comment]
https://player.vimeo.com/external/511211688.sd.mp4?s=1892e6153254e64505584252b0a88d362ed3db56&profile_id=165

It seems that this issue only appears when using a link to a specific resolution. When using regular link (https://vimeo.com/511211688) it works fine.

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/e3b4c084cd0935dd93b1d737c4fc88c65ab5bcc1
