### ISSUE TITLE
Get video information into filter:api.video-threads.list.result hook

### ISSUE THREAD

**Issue by geco** [Chocobozzz/PeerTube#3728]
Is it possible to know video information (not only the id) into client or server hook for "filter:api.video-threads.list.result"?

I need to some operation on thread depending on some properties of video.
I can get video.id (it's the second parameter) but how i can get video information from video id?ù

Thanks in advance!

**Comment by Chocobozzz** [comment]
Hi,

I created another helper so you can fetch a video depending on its id/uuid: https://github.com/Chocobozzz/PeerTube/commit/6559da2821cfa37717fb6f607f76a505d549cc74
