### ISSUE TITLE
Comment sorting button may overlap log-in-to-comment modal window

### ISSUE THREAD

**Issue by pols12** [Chocobozzz/PeerTube#3729]
1. Go on videos/watch/id page, when you are not logged in.
2. Click on textarea to comment, a modal window opens to ask you to log in.
3. According to instances, `#dropdown-sort-comments` button (which is inside `div.dropdown`) displays over modal window.

**Expected behavior**
Modal window should ever be in foreground and hide this button.

**Additional information**
Actually, `.dropdown`’s `z-index` may be higher than `ngb-modal-window`’s `z-index`. Both use `!important`.
I’m not able to determine whether this issue comes from PeerTube or from instance config, so I have preferred to submit it to you.

* PeerTube instance:
  * URL: https://hitchtube.fr/videos/watch/82ef4b08-6f3e-4018-8734-e41e4e520221 (issuing)
  * URL: https://tube-education.beta.education.fr/videos/watch/be627894-fc3b-467c-8e1b-727c4ac7695a (well-working)

* Browser name, version and platforms on which you could reproduce the bug: Firefox 78.7 on Debian/Linux

**Comment by Chocobozzz** [comment]
Thanks for the issue @pols12, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/81f790af78cdce07f3577d1d43e0eba0626ce4b1
