### ISSUE TITLE
Hidden content is not working correctly

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#3730]
**Describe the current behavior**
In the account settings, "Show hidden content" is enabled, but in the personal section "Videos" such videos are still smeared.

**Steps to reproduce:**

1. In the account settings, in the "Default policy on videos containing sensitive content" section, select "Display"
2. Go to the "Video" section
3. Confidential content is smeared anyway.
![Screenshot_1](https://user-images.githubusercontent.com/11453567/107644074-00d14980-6c88-11eb-906d-2e643e7b10fa.png)

**Describe the expected behavior**
If the function is set to display hidden content, then such content should be in the personal section "Video".

* PeerTube instance:
  * URL: https://peervideo.ru
  * version: 3.0.1
  * NodeJS version: 12.20.1
  * Ffmpeg version: 4.1.6-1~deb10u1

* Browser name, version and platforms on which you could reproduce the bug:
Google Chrome v.88.0.4324.150 (64 bit)

**Comment by Chocobozzz** [comment]
Thanks for the issue. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/241609f1943effb731e71f11026898e63384b6e4
