### ISSUE TITLE
Fix federation auto-follow for private/custom indexes

### ISSUE THREAD

**Issue by realkinetix** [Chocobozzz/PeerTube#3731]
If one turns on federation auto-follow and runs their own instances index at, ie "pt-instances.site.com", then configuration their instance to use "https://pt-instances.site.com" should work for auto-following instances placed in that index.

This doesn't appear to be the case with 3.0.1.

When putting in the base instance index site URL, it appears that when PeerTube goes to get the list of instances, it does a "GET /?count=1000 HTTP/1.1" initially, and then the next day does something like "GET /?count=1000&since=2021-02-09T21%3A13%3A18.210Z HTTP/1.1"

The base URI it's supposed to get it's data from appears to be "/api/v1/instances/hosts", not "/".  This doesn't appear to be readily documented, it's missing in examples, etc., and, I presume, should be made simpler to work more like the search index URL, where plunking in "https://search.joinpeertube.org" just does the right thing.

* PeerTube instance: 
  * URL: https://video.mycrowd.ca
  * version: 3.0.1
  * NodeJS version: 10.23.1-1nodesource1
  * Ffmpeg version: 7:4.1.6-1~deb10u1

**Comment by Chocobozzz** [comment]
I updated the documentation to explain what URL is expected: https://docs.joinpeertube.org/admin-following-instances?id=automatically-follow-other-instances

We need the complete URL so you can easily host your auto follow index on github/gitlab/pastebin etc using a simple JSON file.

I'll also add a link in the admin config to point to this documentation.

**Comment by realkinetix** [comment]
Thanks very much for that - makes much more sense now.  Perhaps a link to that part of the documentation would also be useful in the README.md at https://framagit.org/framasoft/peertube/instances-peertube ?

Again, thank you.
