### ISSUE TITLE
federation not working with traefik

### ISSUE THREAD

**Issue by piotr-sikora-v** [Chocobozzz/PeerTube#3733]
When someone try add my instance to followers I don't see it on "Instances following you" and it dosen't matter if I have enabled "Manually approve new instance followers" or disabled
Same problem I have with when I try add some instance to followers ... is always in pending mode even if this instance accept my reqeust.

**Additional information**
Instance is running on docker-swarm with traefik reverse proxy
traefik configuration:
```
      traefik.enable: "true"
      traefik.http.routers.peertube.entrypoints: websecure
      traefik.http.routers.peertube.rule: Host(`tube.dev.lhub.pl`)
      traefik.http.routers.peertube.tls.certresolver: le
      traefik.http.services.peertube.loadbalancer.server.port: 9000
```

* PeerTube instance:
  * URL: https://tube.dev.lhub.pl/
  * version: 3.0.1 /     image: chocobozzz/peertube:production-buster

**Comment by Chocobozzz** [comment]
Hi,

Your instance was created using a `http` scheme. Your PeerTube actor URL is not valid. Try to use https://docs.joinpeertube.org/maintain-tools?id=update-hostjs to fix your database URLs.

**Comment by piotr-sikora-v** [comment]
It works!
All steps I do:
changed /config/production.yml where hostname was set to "undefined" and now is set to "tube.lhub.pl" (https to true)
run rebuild script
added to trafeik:
```
     traefik.http.routers.peertube.middlewares: tube-dev-redirect
      traefik.http.middlewares.tube-dev-redirect.redirectregex.permanent: 'true'
      traefik.http.middlewares.tube-dev-redirect.redirectregex.regex: ^https?://tube.dev.lhub.pl/(.*)
      traefik.http.middlewares.tube-dev-redirect.redirectregex.replacement: https://tuba.lhub.pl/$${1}
```
restart docker
and it works! :)
