### ISSUE TITLE
Description associated with the wrong video when inside playlist

### ISSUE THREAD

**Issue by pprw** [Chocobozzz/PeerTube#3734]
Tested on 3.0.1 and reported by several users.

Inside a playlist the wrong (entire) description is displayed when after seeing the unfold description of one.

1. Go to https://videos.ahp-numerique.fr/videos/watch/playlist/466a631b-c004-468f-aa4f-c80996c73368.
2. Click on "voir plus" to see the entire (unfold) description of the first video.
3. Go to video 3 (video 2 does not have a description long enough).
4. Click on "voir plus".
5. You see the description of video 1 instead of video 3.

It is not always the description of the first video of the playlist which is displayed but it is the first for which you click on "voir plus".

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/06bee93748db63d25b8f3b24cd0eeba97a0bbfda
