### ISSUE TITLE
S3 Storage fails when saving live video

### ISSUE THREAD

**Issue by normen** [Chocobozzz/PeerTube#3735]
**Describe the current behavior**
Currently when a S3 volume is used as per the [documentation](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md) live video can _not_ be stored. This is due to the fact that the combined video gets uploaded in full each time a part is appended.

```
[tube.bitwaves.de:443] 2021-02-09 22:45:37.762 error: Cannot copy segment /data/streaming-playlists/hls/3f5c4a3c-dad3-4eda-99cb-aab03c3a8aea/0-000029.ts to repay directory. {      "err": {                                                                                                                                                                            "stack": "Error: EIO: i/o error, close",
    "message": "EIO: i/o error, close",                                                                                                                                               "errno": -5,                                                                                                                                                                      "code": "EIO",
    "syscall": "close"                                                                                                                                                              }
}
```

When I don't save the video it works somewhat but I get errors on the client side every now and then:

```
[Error] VIDEOJS: – "ERROR:" – "(CODE:2 MEDIA_ERR_NETWORK)" – "HLS.js error: networkError - fatal: true - manifestParsingError" – ke {code: 2, message: "HLS.js error: networkError - fatal: true - manifestParsingError", status: null, …}
ke {code: 2, message: "HLS.js error: networkError - fatal: true - manifestParsingError", status: null, MEDIA_ERR_CUSTOM: 0, MEDIA_ERR_ABORTED: 1, …}kecode: 2message: "HLS.js error: networkError - fatal: true - manifestParsingError"ke Prototyp
```

**Steps to reproduce:**

1. Enable S3 storage
2. Cast a live video
3. Set the video to be stored after streaming
4. See the stream fail after a few seconds/minutes.

**Describe the expected behavior**

The temp file of the full video should be stored outside the S3 folder, then be moved in afterwards.

**Additional information**

* PeerTube instance: 
  * URL: tube.bitwaves.de
  * version: 3.0.1
  * NodeJS version: docker
  * Ffmpeg version: docker

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Closing this issue in favour of https://github.com/Chocobozzz/PeerTube/issues/3661
