### ISSUE TITLE
Display decent message to legacy browsers

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3736]
**Describe the current behavior**
Some of our users have tried to visit our instance from their LG TV and reported that it's more or less a blank page. I got some information from a user and it appeared that the TV he bought last year has Chrome 38 installed. 

**Steps to reproduce:**

1. Visit a PeerTube instance with Chrome 38 (I can recommend BrowserStack, since you're an open source project i think you can get a free account).

**Describe the expected behavior**
I know Chrome 38 isn't supported, but I think that since some users still have it should be a decent error message displayed explaining the issue.

* PeerTube instance:
  * URL: https://videos.lukesmith.xyz
  * version: 3.0.1

* Browser name, version and platforms on which you could reproduce the bug:
Chrome 40

![image](https://user-images.githubusercontent.com/6680299/107784899-3dff0f80-6d4c-11eb-80b9-f2a5d7bf078e.png)

**Comment by kontrollanten** [comment]
A solution could be to show a simple modal upon all non-catched errors, using [ErrorHandler](https://angular.io/api/core/ErrorHandler).

**Comment by Chocobozzz** [comment]
Hello,

I tested it on https://peertube2.cpy.re (nightly deploy) and it correctly displays the "incompatible browser" error message (I think due to the fact we don't provide es5 bundles anymore).
