### ISSUE TITLE
Livestreaming Using The GPU Encoder In OBS Results In An Pixelated Stream

### ISSUE THREAD

**Issue by MrTeeXD** [Chocobozzz/PeerTube#3737]
**Describe the current behavior**
I tried to Livestream using my GPU in OBS but for some reason, it resulted in a Pixelated Stream which I failed to understand why it has happened.

**Steps to reproduce:**

1. Set the Encoder in OBS to GPU (NVENC, QuickSync, AMF (AMD Encoder)
2. Click the Start Stream in OBS using the GPU encoder
3. You may notice that the stream becomes pixelated

**Describe the expected behavior**
Right now, the only way to prevent a pixelated stream from happening, is to use your CPU encoder.

**Additional information**
Here is a Stream I did using my GPU to encode the whole stream:
https://diode.zone/videos/watch/6e847263-5feb-487b-b7d9-3442d36cb537

* PeerTube instance:
  * URL: diode.zone
  * version: 3.0.1
  * NodeJS version: ???
  * Ffmpeg version: ???

* Browser name, version and platforms on which you could reproduce the bug: Brave Browser
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by MrTeeXD** [comment]
Update: Just tried it again and same result:
https://diode.zone/videos/watch/e28058e2-5f7d-44c4-8652-cc4e649a5d72

**Comment by normen** [comment]
Try disabling transcoding.

**Comment by MrTeeXD** [comment]
How do I do that?

**Comment by normen** [comment]
> How do I do that?

<img width="1110" alt="Bildschirmfoto 2021-02-13 um 17 32 27" src="https://user-images.githubusercontent.com/3270528/107855304-bb488400-6e21-11eb-9780-9e6bffebdfce.png">

**Comment by MrTeeXD** [comment]
Im afraid I am not the Admin of Diode.Zone and I dont have that option

**Comment by normen** [comment]
If you're not the admin then I suppose it doesn't make much sense posting in the issue tracker of the software that diode.zone runs on as you won't be able to supply any information to the developers to help clear up the issue. Contact the instance maintainers.

**Comment by MrTeeXD** [comment]
I have let the Maintainer know about this. Shall I close this issue?

**Comment by warnerbryce** [comment]
@MrTeeXD Would you like a test session on my instance that don't do Live-Transcoding for testing ? 
I don't have a computer that can do GPUencode for OBS.

**Comment by MrTeeXD** [comment]
I did some tests along with some of diode.zone's Techies. Tried everything but the stream is always pixelated. Some say there's something wrong with the encoder for GPU Streaming but I did explain to them that my YouTube streams comes out perfect when streaming with my GPU.

**Comment by warnerbryce** [comment]
@MrTeeXD and so you made a test without the Live-Transcode feature enabled or not ? 
if not go on my server and create an account

**Comment by MrTeeXD** [comment]
Hey @warnerbryce I just looked at your linked Instance but unfortunately, its set to "No Registrations" so I unfortunately cannot test there

**Comment by warnerbryce** [comment]
@MrTeeXD alright go onto https://peertube.we-keys.fr 
Login : fb@we-keys.fr
Password : Azerty2021 (with the A in Cap) change the password after that. 
try to upload some livestream with Nvenc or what you want

**Comment by MrTeeXD** [comment]
Trying it out now using my GPU and it looks Perfect!! This is the expected result I wanted to see. Thank you for letting me test this :D

**Comment by warnerbryce** [comment]
@Chocobozzz so the problem is the ffmpeg transcoding that : 
A- could be bad on the server of your host, so need to test this Live-Transcoding with GPU on another server and see the result
B- ffmpeg doesn’t work nice at all with GPU and that needs to be addressed to them.

**Comment by MrTeeXD** [comment]
It could be

**Comment by normen** [comment]
I also find peertubes hint about encoding in the admin section a bit misleading. For imported videos yes - they have to be transcoded to properly stream (i.e. not simply download in the background), even if they are already in a compatible codec and format. But for live streams from OBS for example - they work just fine without transcoding when they are saved so I guess its safe to turn that off if you know how you go in. Unless of course you want transcoding for different resolutions which always requires processing the files for streaming as well.

**Comment by rigelk** [comment]
Closing since the issue is inactive and unclear about its resolution status, feel free to request a reopening.
