### ISSUE TITLE
[frp] peertube http 400 error

### ISSUE THREAD

**Issue by zhengfan2014** [Chocobozzz/PeerTube#3738]
Hello, I successfully built peertube in Synology.

The port is `9000` -> `7400` , `1935` -> `1935` .
![屏幕截图(437)_LI](https://user-images.githubusercontent.com/20752478/107872909-e3e78100-6ee8-11eb-969c-7a60acf44bc2.jpg)

I can access and upload and play videos through `http://Synology ip:7400` normally.
![屏幕截图(435)](https://user-images.githubusercontent.com/20752478/107872850-5310a580-6ee8-11eb-8131-ef8b37bc1100.png)

I used the [frp](https://github.com/fatedier/frp) intranet to penetrate my peertube.

I can access the webpage of LAN port 7400 through the Internet http://v.fudaoyuan.icu

But when I use http://v.fudaoyuan.icu to access my peertube, an http 400 error appears
![屏幕截图(436)](https://user-images.githubusercontent.com/20752478/107872937-27da8600-6ee9-11eb-8653-5023606f91ba.png)

Can someone help me. Thank you

**Comment by rigelk** [comment]
Hi! I think you are the first to report installing PeerTube on Synology.

Could you details the installation steps you followed, and why you chose frp as a reverse proxy?

**Comment by zhengfan2014** [comment]
> Hi! I think you are the first to report installing PeerTube on Synology.
> 
> Could you details the installation steps you followed, and why you chose frp as a reverse proxy?

I did not use docker-compose, but used Synology's webpage to complete the peertube installation

### Synology install peertube process
1. Download PostgresSQL and Redis images from DockerHub

2. According to the [.env](https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/.env) file and [docker-compose.yml](https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/docker-compose.yml) file, configure the environment variables of the corresponding container

 - PostgresSQL requires configuration
```
env:
 - POSTGRES_USER=<MY POSTGRES USERNAME>
 - POSTGRES_PASSWORD=<MY POSTGRES PASSWORD>
 - POSTGRES_DB=peertube
volumes:
 - ./docker-volume/db:/var/lib/postgresql/data
```
![屏幕截图(438)](https://user-images.githubusercontent.com/20752478/107877611-6d5a7b80-6f08-11eb-9ba1-65471e4d764a.png)

 - Redis needs to be configured
```
volumes:
 - ./docker-volume/redis:/data
```
![屏幕截图(439)](https://user-images.githubusercontent.com/20752478/107877701-fa053980-6f08-11eb-8599-f738b223bfc0.png)

3. Download Chocobozzz/PeerTube from DockerHub

4. According to the env file, configure PeerTube

```
env:
 - PEERTUBE_DB_USERNAME=<MY POSTGRES USERNAME>
 - PEERTUBE_DB_PASSWORD=<MY POSTGRES PASSWORD>
 - PEERTUBE_DB_HOSTNAME=postgres
 - PEERTUBE_WEBSERVER_HOSTNAME=<MY DOMAIN>
 - PEERTUBE_WEBSERVER_PORT=80
 - PEERTUBE_WEBSERVER_HTTPS=false
 - PEERTUBE_ADMIN_EMAIL=<MY EMAIL ADDRESS>
ports:
 - "1935:1935"
 - "7400:9000" 
volumes:
 - ./docker-volume/data:/data
 - ./docker-volume/config:/config
```
![屏幕截图(440)](https://user-images.githubusercontent.com/20752478/107877732-1c975280-6f09-11eb-91a0-235689fdfb0c.png)

5. Link Redis container and PostgresSQL container in Synology's PeerTube container

![屏幕截图(441)](https://user-images.githubusercontent.com/20752478/107877854-ddb5cc80-6f09-11eb-914f-f2d6c7dfe7c1.png)


6. Start the PeerTube container, open Synology IP: 7400, and start enjoying

### Why i choose frp

Because according to Chinese laws and regulations, the establishment of peertube instances needs to be reviewed and approved by relevant government departments. And because peertube provides Internet video, it also needs to obtain an Internet audio-visual license issued by the relevant government department to build an instance. So I use a VPS server not in mainland China to set up Frp to reverse proxy and let me remotely access the Synology NAS

**Comment by zhengfan2014** [comment]
After several hours of waiting, `v.fudaoyuan.icu` is suddenly accessible.

After modifying the environment variables, I can access peertube on the Internet normally, but I cannot access peertube on the LAN

Also, I obviously feel that peertube webpages are slow to play videos. Under the same use of frp and cloudflare cdn, jellyfin can reach a maximum download speed of 1M per second, and webpages play 1080P videos smoothly. Peertube has a download speed of only 100kb per second, and it is very lagging when playing 1080P videos. I don't know if this is the cause of cloudflare CDN or frp.

jellyfin:
![屏幕截图(444)](https://user-images.githubusercontent.com/20752478/107897876-42f2d780-6f75-11eb-9bc2-652e7272aa9a.png)
peertube:
![屏幕截图(446)](https://user-images.githubusercontent.com/20752478/107897887-4a19e580-6f75-11eb-8463-138b4f713232.png)

**Comment by Chocobozzz** [comment]
Hello,

> Also, I obviously feel that peertube webpages are slow to play videos.

HLS should fix your issue but there is an issue with your internal URLs so the player can't use it.

Make sure your config variables are:

```
 - PEERTUBE_WEBSERVER_HOSTNAME=v.fudaoyuan.icu
 - PEERTUBE_WEBSERVER_PORT=443
 - PEERTUBE_WEBSERVER_HTTPS=true
```

Then use this script inside the peertube container to fix these URLs: https://docs.joinpeertube.org/maintain-tools?id=update-hostjs
