### ISSUE TITLE
Provide pre-built docker images

### ISSUE THREAD

**Issue by Dragnucs** [Chocobozzz/PeerTube#374]
Currently, PeerTube only makes use of prebuilt images for Postgres and Redis. It would save us time and ressources if PeerTube itself was provided as a pre-built image.

**Comment by Chocobozzz** [comment]
Done: https://hub.docker.com/r/chocobozzz/peertube/tags/

**Comment by Dragnucs** [comment]
Great thanks!

**Comment by Angristan** [comment]
From which branch are they built?

**Comment by Dragnucs** [comment]
It looks like it is from develop.
See SourceRef column: https://hub.docker.com/r/chocobozzz/peertube/builds/bws4ryttoffnvbw5jswup5u/

**Comment by Angristan** [comment]
Indeed, it would be great to have an image from master too.

**Comment by Chocobozzz** [comment]
Sure

**Comment by Chocobozzz** [comment]
Done: https://hub.docker.com/r/chocobozzz/peertube/tags/

**Comment by Angristan** [comment]
Thanks!
