### ISSUE TITLE
Wrong comments count and non-shown comments when comments has been deleted

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3741]
**Describe the current behavior**
When a lot of comments has been deleted for a certain video two issues appears:

* Wrong total comments count is shown.
* Not all comments har shown.

**Steps to reproduce:**

1. Create 30 comments on a video.
2. Delete 15  of the coments.
3. Now it'll show "30 comments" and when you scroll you probably won't be able to see all comments (depending on which of the comments you deleted).tswe

Check this video https://swebbtv.se/videos/watch/5cbd0f01-d8b9-44b0-bb05-fbe94794fe6e
1. It says 73 comments.
2. Scroll to the bottom.
3. It says 44 comments.
4. Count the comments, it's 23 comments.

**Describe the expected behavior**
It should display the total count of non-deleted comments and also display all comments.

**Additional information**
I guess this would be solved by filtering out isDeleted comments on the server side. Is there any reason to not  do so?

* PeerTube instance:
  * version: 3.2.0-c ([custom build](https://github.com/kontrollanten/PeerTube/releases/tag/v3.2.0-c))

**Comment by Chocobozzz** [comment]
Thanks for the issue. Please try https://github.com/Chocobozzz/PeerTube/commit/9d6b9d10ef8cbef39e89bc709285abffb0d8caa1

**Comment by kontrollanten** [comment]
There's still wrong total count and it seems that not all comments are shown. https://swebbtv.se/videos/watch/5cbd0f01-d8b9-44b0-bb05-fbe94794fe6e

**Comment by Chocobozzz** [comment]
It seems for me the comments are okay:
 * It loads all threads (~85) but do not display deleted threads that do not have replies
 * It displays the correct amount of non-deleted comments (~65). These counter takes into account replies now

**Comment by kontrollanten** [comment]
Oh, it must been a caching issue. Now it looks great. Thanks!
