### ISSUE TITLE
Channel RSS feed doesn't validate

### ISSUE THREAD

**Issue by yPhil-gh** [Chocobozzz/PeerTube#3743]
**Describe the current behavior**

**Steps to reproduce:**

1. Go to https://validator.w3.org/feed/
2. Enter this url: https://tube.netzspielplatz.de/feeds/videos.xml?videoChannelId=8984
3. You get [this error page](https://validator.w3.org/feed/check.cgi?url=https://tube.netzspielplatz.de/feeds/videos.xml?videoChannelId=8984).

**Describe the expected behavior**
The feed should validate, apparently custom nodes are not properly defined.

**Additional information**

* PeerTube instance:
  * URL: https://tube.netzspielplatz.de
  * version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by rigelk** [comment]
hi @yPhil-gh,

Yes, we provide MRSS feeds, not RSS 2.0 feeds, for which you can refer to https://github.com/Chocobozzz/PeerTube/issues/2922.
