### ISSUE TITLE
 Incorrect blur NSFW video

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#3744]
There was a problem that you have already completed successfully 
https://github.com/Chocobozzz/PeerTube/issues/3730#issue-806402011

![Screenshot_1](https://user-images.githubusercontent.com/11453567/108052080-b02d6800-705c-11eb-8cda-fb43bfd91f98.png)

I specifically installed Peertube version 3.0.1-nightly-2021-02-16 and found the same problem under My Library -> Channel -> Videos
![Screenshot_2](https://user-images.githubusercontent.com/11453567/108052118-bcb1c080-705c-11eb-8f82-96c9081858ec.png)

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/07f81d9deedf4921b8518c2d2b16043167b4c5d5
