### ISSUE TITLE
How to remove the "agree with terms and conditions"?

### ISSUE THREAD

**Issue by tiotrom** [Chocobozzz/PeerTube#3749]
We want to provide a trade-free instance https://www.trade-free.org/ - so we don't want for people to trade their freedom to us in order to use the instance. In other words, we don't want to force people to ONLY use our instance IF they give up this or that. So is there an easy way to remove the "agree with terms and conditions"?

**Comment by test2a** [comment]
Then write the same in terms and conditions. Not having a terms and conditions doesn't mean free for all, something like this has to be mentioned

**Comment by tiotrom** [comment]
Yes and we do write that, but we don't want to force people to agree with the terms and conditions and to be over 16. Trade-Free really means no terms and conditions. Simply let people use the instance with the rules that are in place on the instance.

 Is there a way to change the forced agreement thing in the code, and if so where? I would be very grateful if you would tell me.

**Comment by Chocobozzz** [comment]
Hello,

You can use a plugin or custom JS/CSS to automatically check and hide this checkbox.

**Comment by tiotrom** [comment]
Ok thanks. But would be nice to add this feature in the admin panel. At least one to change the text. Why should humans under 16 not be allowed generally to use a video platform? :)
