### ISSUE TITLE
ActivityPub: Activity ID is the same as the ID of the created object

### ISSUE THREAD

**Issue by lambadalambda** [Chocobozzz/PeerTube#375]
* **PeerTube version or URL:**
https://peertube.video
https://peertube.video/accounts/lain/outbox
* **Browser name/version:**
* **NodeJS version:**

* **What is the expected behaviour?**
A Create activity and the object it creates should have a different ID.
* **What do you see instead?**
They have the same ID.

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

**Comment by lambadalambda** [comment]
From the outbox:
```
 "type": "Create",
        "id": "https:\/\/peertube.video\/videos\/watch\/737b3369-9500-4678-b748-22bef7855585",
        "actor": "https:\/\/peertube.video\/accounts\/lain",
        "object": {
          "type": "Video",
          "id": "https:\/\/peertube.video\/videos\/watch\/737b3369-9500-4678-b748-22bef7855585",
[...]
```

**Comment by lambadalambda** [comment]
Mastodon just adds `/activity` to the object id to get the activity id, which should be enough.

**Comment by Chocobozzz** [comment]
Should be fixed: https://github.com/Chocobozzz/PeerTube/commit/a38b297d90a35abc8d5308f74eb2d2b64cef7c21 & https://github.com/Chocobozzz/PeerTube/commit/296c090563f9d609d3c55dec378a3a1d65c4bd78
