### ISSUE TITLE
Insert a still image in the video description

### ISSUE THREAD

**Issue by siberkolosis** [Chocobozzz/PeerTube#3750]
**Describe the problem to be solved**

Not all moments are recorded on video, maybe there are additional video descriptions that want to include still images.

**Describe the solution you would like:**

Users can add a still image to the video description. Attach images by dragging & dropping, selecting or pasting them.

**Describe alternatives you have considered**

**Comment by rigelk** [comment]
Please fill the feature request template

**Comment by siberkolosis** [comment]
> Please fill the feature request template

OK, I did.
:)

**Comment by Alterak** [comment]
It would be a good idea to have images and videos in the description and comments. When adding a video, you can even generate a preview, as is generated for example in twitter.
It would be very convenient!

**Comment by Chocobozzz** [comment]
Hello,

The image on twitter should be the preview you chose in the video create/update form. We want to keep text only in video descriptions, because they just are descriptions. But you could try to create a plugin if you want to embed images in the video watch page.
