### ISSUE TITLE
Why are only 3s on JOB_REQUEST_TIMEOUT?

### ISSUE THREAD

**Issue by manalejandro** [Chocobozzz/PeerTube#3751]
Hi, we are having problems in our instance to federate and we use docker, we have increased to 60 seconds the default value of this variable to federate correctly.

Thanks greetings

https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/constants.ts#L189

**Comment by Chocobozzz** [comment]
Hello,

We set this timeout to not slow down AP messages federation. A bad server could easily block some requests during multiple minutes. It's weird you have to increase this timeout to 60 seconds though. AP requests should not take that amount of time. What is the location of you server?

**Comment by manalejandro** [comment]
https://fediverse.tv

**Comment by Chocobozzz** [comment]
And to what server do the requests fail?

**Comment by manalejandro** [comment]
All servers, it was not federating

**Comment by Chocobozzz** [comment]
Then please fill the bug template so I can understand what is the issue: https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/00-bug-issue.md

**Comment by manalejandro** [comment]
ok :+1:
