### ISSUE TITLE
Get concurrent viewers per video

### ISSUE THREAD

**Issue by realkinetix** [Chocobozzz/PeerTube#3755]
**Describe the problem to be solved**

Presently, I believe admins are mostly in the dark about what's currently occurring on their instance.  There's no live information page for admins, nor CLI tool, to see a few items that I think would be helpful for information on how to manage the scaling of their instance, if nothing else:

- Videos being watched, sortable, with number of concurrent (as best as possible) viewers of that video

- Videos being uploaded and the transcoding queue could be helpful as well

I didn't see any plugins to assist with these, and figured it could be helpful to just have them available for admins.

**Comment by Chocobozzz** [comment]
> Videos being uploaded and the transcoding queue could be helpful as well

You already have this kind of information in the Job admin page.

**Comment by realkinetix** [comment]
> > Videos being uploaded and the transcoding queue could be helpful as well
> 
> You already have this kind of information in the Job admin page.

![Peertube-jobs](https://user-images.githubusercontent.com/13442583/108538240-7003fa80-7293-11eb-9de7-80fddaaa44c3.png)

I would posit that the information isn't presented in a human-consumable format.  Sure, we see 'things' occurring, but this is just a list of 'things' that doesn't seem to mean much - yes, it may have "detail" (I put in quotes as it's not terribly human consumable) that is useful for debugging, but it's not really an active status of what is happening *right now*, right?

**Comment by Chocobozzz** [comment]
Using the `video-transcoding` job type and `active` or `waiting` job state to list pending transcoding jobs happening on the instance.

**Comment by kontrollanten** [comment]
@realkinetix I hear you, I think it could be nice with some kind of dashboard that showing the N latest video uploads, comments, user registrations, popular videos, etc. Maybe that could be done as a plugin?

**Comment by Chocobozzz** [comment]
Closing in favour of https://github.com/Chocobozzz/PeerTube/issues/3796

**Comment by realkinetix** [comment]
I would ask you to reconsider this as a separate issue.  #3796 doesn't seem to have any mention of an administrator's view of what's presently occurring on their peertube instance, which is what this issue is relating to.
