### ISSUE TITLE
Plugin documentation: registerSettings missing attributes

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#3758]
**Parts of the documentation concerned:**

https://docs.joinpeertube.org/contribute-plugins?id=settings

**Describe the desired information/correction**

Missing «private» and «descriptionHTML» attributes for registerSettings parameter.

**Comment by Chocobozzz** [comment]
Thanks, fixed by https://github.com/Chocobozzz/PeerTube/commit/248875d243cdb868958c24a0c8031080628c57d7
