### ISSUE TITLE
Missing informations for lives in states WAITING_FOR_LIVE and LIVE_ENDED

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#3760]
**Describe the current behavior**

Video description is missing for lives in states WAITING_FOR_LIVE and LIVE_ENDED.
There must be other missing fields.
There is because of this return: https://github.com/Chocobozzz/PeerTube/blob/94d721efdc9a8c2cda612f49506a41adb6a06f1d/client/src/app/%2Bvideos/%2Bvideo-watch/video-watch.component.ts#L557
It is done too soon.

**Steps to reproduce:**

1. Create a live with a description
2. Go to the live page

**Describe the expected behavior**

The description should be displayed. It can contains important informations for the live (for example when it will start).

* PeerTube instance:
  * version: 3.0.1

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/0a6817f0ba29865576bb16e87fbf62679de885d7

The plugin hook should also be fired now

**Comment by JohnXLivingston** [comment]
Great!
Is there an expected release date for the next version?
