### ISSUE TITLE
Transcode Live into audio-only

### ISSUE THREAD

**Issue by roere** [Chocobozzz/PeerTube#3762]
Live streams can be recorded and stored on the server. This recording can be transcoded into a selection of the usual resolutions.  Problem: it cannot be transcoded into audio-only.

I would like a "0p aka audio-only" transcoding option for Live streams.

**Comment by Chocobozzz** [comment]
Blocked by https://github.com/Chocobozzz/PeerTube/issues/3281

**Comment by Chocobozzz** [comment]
We plan to implement this feature in 2024. Read the detailed blog post on https://joinpeertube.org/news/peertube-future-2024

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/6521

Live can also ingest an audio only stream
