### ISSUE TITLE
Optimice nginx

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#3767]
I've been looking at this setup. https://gist.github.com/denji/8359866

Can any of these parameters affect the operation of the nginx and peertube?

**Comment by Chocobozzz** [comment]
Hello,

I removed the link from the guide https://github.com/Chocobozzz/PeerTube/commit/8281cf00c0f31a45f6c66f6b6b31224696e130ab since we added most of these directives in our nginx template.
