### ISSUE TITLE
Vimeo imports fail after download is transcoded

### ISSUE THREAD

**Issue by kominoshja** [Chocobozzz/PeerTube#3769]
**Describe the current behavior**
When trying to import any video from a channel of Vimeo in a Peertube instance, it fails with the error `ENOENT: no such file or directory, stat '/var/www/peertube/storage/tmp/536545a6f6cce0c03a38b41e93690eec7ece476dc06fd215b0a87f4a4299d999-import.mov'`. Well.. Peertube isn't wrong, there isn't a `/var/www/peertube/storage/tmp/536545a6f6cce0c03a38b41e93690eec7ece476dc06fd215b0a87f4a4299d999-import.mov` BUT there is a `/var/www/peertube/storage/tmp/536545a6f6cce0c03a38b41e93690eec7ece476dc06fd215b0a87f4a4299d999-import.mov.mp4`. 
I tried to see if the same issue is happening with youtube, and that's not the case. It almost seems like peertube forgets that it has transcoded the file, and tries to import the original.
One thing to note is that I only tried this with one instance.

**Steps to reproduce:**
1. Try to import https://vimeo.com/469758419
2. Notice failure

**Describe the expected behavior**
Peertube imports the video without any issue

**Additional information**

* PeerTube instance:
  * URL: https://video.shuttleworthfoundation.org
  * version: v3.0.1
  * NodeJS version: 12 (originally tried on 10)
  * Ffmpeg version: 4.3.2-0york0~18.04 (originally tried the stable one of Ubuntu 18's sources)

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant: N/A
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
```json
error: Cannot execute job 19 in queue video-import. {
  "payload": {
    "type": "youtube-dl",
    "videoImportId": 19,
    "generateThumbnail": false,
    "generatePreview": false,
    "fileExt": ".mov"
  },
  "err": {
    "stack": "Error: ENOENT: no such file or directory, stat '/var/www/peertube/storage/tmp/536545a6f6cce0c03a38b41e93690eec7ece476dc06fd215b0a87f4a4299d999-import.mov'",
    "message": "ENOENT: no such file or directory, stat '/var/www/peertube/storage/tmp/536545a6f6cce0c03a38b41e93690eec7ece476dc06fd215b0a87f4a4299d999-import.mov'",
    "errno": -2,
    "code": "ENOENT",
    "syscall": "stat",
    "path": "/var/www/peertube/storage/tmp/536545a6f6cce0c03a38b41e93690eec7ece476dc06fd215b0a87f4a4299d999-import.mov"
  }
}
```

**Comment by Chocobozzz** [comment]
Thanks for the issue. It will be fixed in the next version. See https://github.com/Chocobozzz/PeerTube/pull/3516#issuecomment-762922846
