### ISSUE TITLE
Script to Export Video Titles and Unique IDs

### ISSUE THREAD

**Issue by LukeSmithxyz** [Chocobozzz/PeerTube#3772]
It'd be nice if there were a simple script included among the tools that could export all video titles and unique identifiers of the whole instance or of a specific user in simple text, perhaps one video per line with the title and IDs separated by a tab.

I've had a couple people ask me if they could have direct downloads to videos, usually torrents, on a simple HTML page and I'd like to make one on my website where people can see video titles and download links.

All I would need for this, of course, is just a such a script that exports all video names and IDs preferably in order of release date, since urls/links to torrents should be recoverable from the IDs. Obviously this would be a very extensible addition as well for others.

If there is already something that does this, sorry for overlooking it, but please make me aware of it.

**Comment by rigelk** [comment]
hi @LukeSmithxyz,

The REST API is already there for third-party applications like your HTML page listing, and provides more extensibility than writing a second API in the form of a CLI script. You can find its documentation at https://docs.joinpeertube.org/api-rest-reference.html.

**Comment by LukeSmithxyz** [comment]
Hey thanks for the info. It works, but, I'm running into another API issue.

Looks like the maximum number of videos whose data can be requested at once is 100. I have a lot more than 100 videos.

Is there a way I can override or increase the maximum in the PeerTube interface somewhere, or am I going to have to just change the API manually on the backend? (If so, telling me which file I should look to would help because I haven't ever looked at the source.)

**Comment by rigelk** [comment]
Just use paging.
