### ISSUE TITLE
 M4A files should be supported like Flac/mp3.

### ISSUE THREAD

**Issue by sierran** [Chocobozzz/PeerTube#3774]
**Describe the problem to be solved**

M4A files should be supported.

**Describe the solution you would like:**

Ability to upload M4A files like mp3/flac with video background. Videos downloaded in audio mode by youtube-dl are most often in m4a format, I would like to avoid unnecessary conversion to flac before uploading to PeerTube.

**Comment by Chocobozzz** [comment]
Thanks, should be implemented in https://github.com/Chocobozzz/PeerTube/commit/e072fb1e1633e57c986b2d19646b7a140af03bb8
