### ISSUE TITLE
Broken user settings

### ISSUE THREAD

**Issue by 1992Sofia** [Chocobozzz/PeerTube#3777]
**Describe the current behavior**
The selected theme changes to "default/null" when a setting is changed.

**Steps to reproduce:**

1. Set any custom theme as global default in the administration.
2. Logout and open the user settings.
![set](https://user-images.githubusercontent.com/79608996/109091324-d87c2d00-7714-11eb-957f-499a0a20b04e.png)
3. Change any setting.
![theme_bug](https://user-images.githubusercontent.com/79608996/109091376-f21d7480-7714-11eb-97a0-8ec52280a008.gif)
4. After a page reloaded the theme settings are empty.

**Describe the expected behavior**
The theme does not change

* PeerTube instance:
  * URL: https://devtube.dev-wiki.de/ (example)
  * version: 3.0.1 and develop branch
  * NodeJS version: any
  * Ffmpeg version: any

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/24d3352ce4b48bc9ff15e8c0af0c93df6d903e5e
