### ISSUE TITLE
Preview image file extension capitalization

### ISSUE THREAD

**Issue by frankenstein91** [Chocobozzz/PeerTube#3780]
**Describe the current behavior**
Currently you can only upload JPG files with lowercase file extensions in the video settings. The MIME type is not checked.

**Steps to reproduce:**

1. Upload Video
2. Open the Advanced Settings tab
3. Try uploading a video thumbnail with a JPG file extension in uppercase.

**Describe the expected behavior**

My expected behavior of the software would be that all JPG images are accepted. There is no difference between JPG, jpg, JPEG and jpeg in the file. It should rather check the file for a valid Jpeg content.

**Additional information**

* PeerTube instance:
  * URL: https://devtube.dev-wiki.de/video-channels/walking_the_world/
  * version: 3.0.0
  * NodeJS version: N/A
  * Ffmpeg version: N/A

* Browser name, version and platforms on which you could reproduce the bug: Firefox Linux all versions

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/88cfa3e8fa8417f14a905c089e57e1648f5a3846
