### ISSUE TITLE
Batch video uploading / cli tools should be easier / simplified

### ISSUE THREAD

**Issue by sierran** [Chocobozzz/PeerTube#3781]
**Describe the problem to be solved**
Currently, using a featured video uploader tool (CLI) is a pain. I have vacation videos and would like to upload them in one go. I approached it as recommended using "Remote Tools". Setting up simple upload tool takes around 20min using hdd, and takes 
more than 1GB of storage. Forcing it to work under windows is also not the fastest, and in the end it turned out that uploading doesn't work anyway. 

`{"path":"/api/v1/videos/upload","err":{"name":{"value":"=","msg":"Should have a valid name","param":"name","location":"body"}},"level":"warn","message":"Incorrect request parameters","label"::*****:443","timestamp":"2021-02-25T17:42:57.544Z"}
`

I got that message after trying to upload simple test.mp4 video. Peertube is already a great tool and the only thing I'm missing is the option to upload multiple videos.  I see there is a python lib so maybe I can write something in my spare time but it would still be nice to have an official tool that would be easy to use e.g. in scripts. I tried too peertube-import-videos but also without success to mirror youtube channel. 

`info: Downloading video "Wychował mnie woźny |pasta|"...
info: [youtube] Mz9SVeY3-2g: Downloading webpage
[youtube] Mz9SVeY3-2g: Downloading MPD manifest
[download] Destination: G:\sldc\peertube\cli\PeerTube\dist\server\tools\bb9a80b75c5c5350fb0f63a1ab39ede7cfa40e928efdffccfc044eab29166ad5.f136.mp4
[download] 100% of 8.22MiB in 00:00
[download] Destination: G:\sldc\peertube\cli\PeerTube\dist\server\tools\bb9a80b75c5c5350fb0f63a1ab39ede7cfa40e928efdffccfc044eab29166ad5.mp4.f140
[download] 100% of 8.25MiB in 00:0078MiB/s ETA 00:00
info:
Uploading on PeerTube video "Wychował mnie woźny |pasta|".
ENOENT: no such file or directory, open 'G:\sldc\peertube\cli\PeerTube\dist\server\tools\bb9a80b75c5c5350fb0f63a1ab39ede7cfa40e928efdffccfc044eab29166ad5.mp4'`

Btw. @Chocobozzz Great job :)

**Describe the solution you would like:**

Creating a tool that would be able to simply send several files to a given category and visibility (eg. private video).

**Comment by Chocobozzz** [comment]
Hello,

Please paste the command you try to run

**Comment by sierran** [comment]
For channel mirror:
node .\dist\server\tools\peertube-import-videos.js --target-url https://www.youtube.com/playlist?list=PL_L86XxBIFCKDUF4JeLogtYtuffSx3dxn

For one video upload:
node .\dist\server\tools\peertube.js up --file 'G:\sldc\peertube\cli\PeerTube\dist\server\tools\toup\Dziewczyna z obozu.mp4' --video-name== "Dziewczyna z obozu"

**Comment by Chocobozzz** [comment]
For video import, I think it's a youtube-dl issue that may not be able to merge files using ffmpeg. 

For single video upload, try `node .\dist\server\tools\peertube.js up --file 'G:\sldc\peertube\cli\PeerTube\dist\server\tools\toup\Dziewczyna z obozu.mp4' --video-name "Dziewczyna z obozu"` instead
