### ISSUE TITLE
Abuses list crash when video has been deleted

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3783]
**Describe the current behavior**
Upon visiting /admin/moderation/abuses/list it says "No abuses found" and then there's a notification about bad server response due to 500 response from /api/v1/abuses?start=0&count=10&sort=-createdAt. There's no errors found in any logs.

**Steps to reproduce:**

1. Write a comment.
2. Abuse report the comment.
3. Remove the video.
4. Visit abuses  list.

**Describe the expected behavior**
A) If an error occurs the UI shouldn't tell "No abuses found" but instead "Something went wrong, abuses couldn't been found."
B) The abuses list shouldn't crash when a video has been removed.

* PeerTube instance:
  * version: v3.2.2
  * NodeJS version: v12.20.2

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/494df940364b98730ae06ed08e94e5742b40a4d2
