### ISSUE TITLE
Anonymous p2p setting bug

### ISSUE THREAD

**Issue by 1992Sofia** [Chocobozzz/PeerTube#3784]
**Describe the current behavior**
I don't know if this is a bug.
The option "Help share videos" is available even if p2p is disabled.

**Steps to reproduce:**

1. Disable p2p
![p2pdis](https://user-images.githubusercontent.com/79608996/109268292-2a06e380-780b-11eb-96a2-a539f1b24d22.png)
2. Logout and open the user settings
![set](https://user-images.githubusercontent.com/79608996/109267984-b369e600-780a-11eb-8948-105d6f12133f.png)
3. "Help share videos being played" is checked. (Is this option releated to p2p?)
![befreload](https://user-images.githubusercontent.com/79608996/109268351-3c811d00-780b-11eb-9195-a61860273433.png)
4. Uncheck "share videos" and click save.
5. Reload the page and open settings again.
6. "share videos" is checked again.

Logged in users have the same (issue)
![usersahe](https://user-images.githubusercontent.com/79608996/109268750-d0eb7f80-780b-11eb-8b2b-1c29c83f9346.png)

**Describe the expected behavior**

**Additional information**

* PeerTube instance:
  * URL: local
  * version: 3.0.1
  * NodeJS version: any
  * Ffmpeg version: any

**Comment by Chocobozzz** [comment]
Hello,

The P2P instance setting is only for local videos. It's the reason why the user/anonymous setting is still needed. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/cb2e36618ca5986949d4326ea939b5b08f3a9a82
