### ISSUE TITLE
Add an option to always save replays by default

### ISSUE THREAD

**Issue by sgiraudot** [Chocobozzz/PeerTube#3785]
Currently, when creating a livestream, the option to record and save the stream as a replay afterwards is switched off by default. Users might want to always record their streams and may forget to switch on the option at some point (that just happened to me and I noticed it afterwards when the replay was not published).

A nice solution would be to add an option in the user's parameters like "When streaming, always activate replays" (switched off by default if you want to be conservative with the current behavior). Users could still select whether they want to publish the replay or not when creating a stream, but the default value would also be user-selected (instead of always off right now).

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/4024
