### ISSUE TITLE
Add donation buttons

### ISSUE THREAD

**Issue by Dev380** [Chocobozzz/PeerTube#3788]
**Describe the problem to be solved**
Most YouTube monetization comes from donations, merch, etc. PeerTube doesn't have an easy way to promote these except for video description.

**Describe the solution you would like:**
Add customizable buttons that show up when you watch a video. They could link to Bitcoin addresses or Liberapay addresses for example.

**Describe alternatives you have considered**  

Just adding links to the top of the description, however most people won't even think of using donation platforms if they aren't presented with that as a solution to monetization.

**Comment by rigelk** [comment]
This is already supported via the support filed/button.
