### ISSUE TITLE
Add IPFS support

### ISSUE THREAD

**Issue by Dev380** [Chocobozzz/PeerTube#3789]
**Describe the problem to be solved**
People cannot host videos that they would like to support. I saw someone on Reddit asking how to seed WebTorrent PeerTube videos from their device, but they couldn't find a solution.

**Describe the solution you would like:**
Add support for [IPFS](https://ipfs.io) which is a decentralized web protocol similar to Bittorent. IPFS has a larger community and developer base than WebTorrent, more tools, bigger ecosystem, and it reduces redundancy so if multiple videos use the same clip it could be stored only once, if multiple instances host a video it's accessed with the same ID, people can use already existing tools to pin (seed) videos, etc.

**Comment by rigelk** [comment]
Hi! Please look out for related issues before creating one, as #494 already covers this. You can then detail further your use case there, and upvote the issue to help us triage it.
