### ISSUE TITLE
Can't save config from the Web UI on Docker

### ISSUE THREAD

**Issue by Angristan** [Chocobozzz/PeerTube#379]
I'm using version 1.0.0 beta 1 with the repo's docker image.

I use the environment variables to configure my instance but not all of the options are available like the video quota.

However I can't modify the configuration from the web UI:
![screenshot_22-03-2018_22-05-51](https://user-images.githubusercontent.com/11699655/37798741-eac8a6e8-2e1d-11e8-9d5e-b0f7abaf4ead.png)

I suppose it makes sense since a restart of the container would erase the configuration file, does that mean we have to implement every single configuration option into a Docker environment variable?

**Comment by Chocobozzz** [comment]
I would need a screen that contains all the form inputs please :)

**Comment by Chocobozzz** [comment]
I forced the validation on form init https://github.com/Chocobozzz/PeerTube/commit/d63fd4f7b1e41ef7b05fd97abff5c4cebbea63df so you can see which field is incorrect

**Comment by Angristan** [comment]
Here you go:

![screenshot_23-03-2018_10-20-43](https://user-images.githubusercontent.com/11699655/37821456-ecec478e-2e83-11e8-9c35-2addd8f634ee.png)
![screenshot_23-03-2018_10-20-56](https://user-images.githubusercontent.com/11699655/37821460-eebf3aee-2e83-11e8-8b08-ea8cd0a6c944.png)
![screenshot_23-03-2018_10-21-05](https://user-images.githubusercontent.com/11699655/37821462-f009227a-2e83-11e8-8545-df38e491a570.png)

**Comment by Angristan** [comment]
I built an image from develop but I don't see any change on the form 🤔

**Comment by Chocobozzz** [comment]
Oup's: https://github.com/Chocobozzz/PeerTube/commit/a465bf5f472227f46af42ec26a22e381aec5d458

I think this [line](https://github.com/Chocobozzz/PeerTube/commit/95540ed23a2e6ae6d48739f211aa24df57278413#diff-1a1a8c4751f9ceb8309879af20a2fa50R18) will fix your configuration

**Comment by Angristan** [comment]
I'm getting `cp: cannot create regular file '/app/support/docker/production/config/default.yaml': Permission denied`

Fixed in https://github.com/Chocobozzz/PeerTube/pull/385

And I can modify the config file now 👍

**Comment by Angristan** [comment]
But as expected, recreating the container erases the configuration. So the solution would be to mount `production.yaml` to keep the changes.

**Comment by Chocobozzz** [comment]
Thanks for the fix @Angristan. I suggest you to mount the `config/` directory because peertube creates a local.json configuration file when you change the configuration in the admin interface.

**Comment by Angristan** [comment]
Not for me: 

```
peertube@e73fa70e232a:/app$ ls config/
default.yaml             test-1.yaml  test-3.yaml  test-5.yaml  test.yaml
production.yaml.example  test-2.yaml  test-4.yaml  test-6.yaml
```

**Comment by Chocobozzz** [comment]
It's `/app/support/docker/production/config` I think.

See https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/Dockerfile.stretch#L26

**Comment by Angristan** [comment]
Indeed it's `local-production.json` in that folder. Thanks

**Comment by noplanman** [comment]
@Angristan @Chocobozzz 
I'm faced with the same issue and was wondering about the best way to save a persistent production configuration.

What needs mounting to where?

**Comment by Angristan** [comment]
I use `./config/local-production.json:/app/support/docker/production/config/local-production.json`

**Comment by noplanman** [comment]
I'm quite new to docker, how do I set that?
I've added it to the `volumes` key, but instead of mounting just the file, it created a directory called `local-production.json`, which makes the container fail.

```yaml
...
   volumes:
      - ./data:/data
      - ./config/local-production.json:/app/support/docker/production/config/local-production.json
...
```

**Comment by noplanman** [comment]
The `config` folder already existed.

I've also tried to make a new empty folder, but still it created a folder called `local-production.json` instead of just linking the file. Weird.

**Comment by noplanman** [comment]
I'm having this exact issue:
https://stackoverflow.com/questions/42248198/how-to-mount-a-single-file-in-a-volume

@Angristan How come this isn't a problem for you? Do you have a different version of `docker-compose` that has some different behaviour?

I have: `docker-compose version 1.20.1, build 5d8c71b`

**Comment by Angristan** [comment]
Here is my setup:

```
root@hinata /s/peertube_xyz# ll
total 20K
drwxr-xr-x  2              991  991 4.0K Mar 30 00:21 config/
drwxr-xr-x 11              991  991 4.0K Mar 27 01:11 data/
-rw-r--r--  1 root             root 1.5K Mar 30 00:17 docker-compose.yml
drwx------ 19               70 root 4.0K Mar 23 19:13 postgres/
drwxr-xr-x  2 systemd-timesync root 4.0K Mar 30 15:30 redis/

root@hinata /s/peertube_xyz# ll config/
total 4.0K
-rw-r--r-- 1 991 991 802 Mar 30 00:26 local-production.json

root@hinata /s/peertube_xyz# grep config docker-compose.yml 
      - ./config/local-production.json:/app/support/docker/production/config/local-production.json

root@hinata /s/peertube_xyz# docker exec -i peertube_xyz ls /app/support/docker/production/config/
custom-environment-variables.yaml
default.yaml
local-production.json
production.yaml
```

**Comment by noplanman** [comment]
Ooook, I've managed to do it now, phew.

I first had to do `touch config/local-production.json` locally and then `chown 991:991 config/local-production.json`.

After another `docker-composer up -d` it finally managed to link the file properly!

Thanks so much @Angristan for this, brilliant!

**Comment by Angristan** [comment]
Yeah I wish it could be done simpler :(
