### ISSUE TITLE
public keys of federation partners cannot be deleted

### ISSUE THREAD

**Issue by rmalchow** [Chocobozzz/PeerTube#3790]
**Describe the current behavior**

i havent completely analyzed this - but i would appreciate some help - i think that this is what's happening:

when an existing federation partner is reset and is setup from scratch (resulting in a new keypair), federation cannot be set up again. even when adding the peers, and then removing them again, it seems the old keys are kept in the "actors", and any subsequent federation is not possible.

**Steps to reproduce:**

1. setup federation between 2 instances
2. trash one of them, set it up again
3. initiate the federation again (with the same hostnames but a new instance)

**Describe the expected behavior**

federation succeeds OR warning is received that the remote keys have changed OR a manual option is available to see actors and edit their keys.

**Additional information**

* PeerTube instance:
  * version: v.3.0.1

**Comment by rmalchow** [comment]
i removed the actors (and corresponding videos) from the database manually, then we could re-register the federation. the public keys saved alongside the "actor" entries where indeed old. so this kind of confirms this theory. how can we deal with this in a nicer way?

**Comment by Chocobozzz** [comment]
Hello,

Your issue should be fixed by https://github.com/Chocobozzz/PeerTube/commit/4cbdcf440969de2bd0c0cac3dad53d582879465e

**Comment by rmalchow** [comment]
hi,

i dont think this is fixed. in our case, both were v3 instances, and the thing that broke it was the fact that i trashed one side of the fedration, including losing the key. so:

- federation was set up
- one node got trashed
- federation could not be set up again until the actor from the "old" federation was removed.
-

**Comment by Chocobozzz** [comment]
The fix is for the next version so 3.1 :)
