### ISSUE TITLE
Plugin CSS not served

### ISSUE THREAD

**Issue by 1992Sofia** [Chocobozzz/PeerTube#3792]
**Describe the current behavior**
I wrote a Plugin with some styles but peertube is not serving them.

**Steps to reproduce:**

0. Start PeerTube localy with 'npm run dev'
1. Clone https://framagit.org/framasoft/peertube/peertube-plugin-quickstart/ and add some styles to 'assets/style.css'
```css
body#custom-css {
  display: none !important;
}
```
2. Install the plugin
3. Open 'http://localhost:3000/' and clear your cache. The 'body' is still visible.
4. Open 'http://localhost:3000/api/v1/config/' to check if the API serving your plugin styles in the json.
```json
{
    ...
    "plugin": {
        "registered": [
            {
                "clientScripts": {...}
            }
        ]
    },
    ...
}
```
**Describe the expected behavior** 
```json
{
    ...
    "plugin": {
        "registered": [
            {
                "clientScripts": {...},
                "css": {...} <--expected
            }
        ]
    },
    ...
}
```
**Additional information**
Restarting PerTube after the plugin installation did not help in my case.

* PeerTube instance:
  * URL: local dev branch
  * version: defvelop
  * NodeJS version: any
  * Ffmpeg version: any

**Comment by Chocobozzz** [comment]
Hello,

Please follow the documentation: https://docs.joinpeertube.org/contribute-plugins?id=test-your-plugintheme

Plugin CSS injection cannot work with a dev server. You need to build PeerTube (to have the compiled client files).
