### ISSUE TITLE
Using JOB_REQUEST_TIMEOUT to 3000ms is not sufficient to federate

### ISSUE THREAD

**Issue by manalejandro** [Chocobozzz/PeerTube#3794]
**Using JOB_REQUEST_TIMEOUT to 3000ms is not sufficient to federate**

https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/constants.ts#L192

**Steps to reproduce:**

1. Start Peertube
2. Add one follow instance
3. See logs and watch timeouts of the jobs

**Additional information**

* PeerTube instance:
  * URL: https://fediverse.tv
  * version: latest chocobozzz/peertube:production-buster docker image
  * NodeJS version: latest chocobozzz/peertube:production-buster docker image
  * Ffmpeg version: latest chocobozzz/peertube:production-buster docker image

* Browser name, version and platforms on which you could reproduce the bug: none
* Link to browser console log if relevant: none
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): default peertube log

**Comment by Chocobozzz** [comment]
Increased in https://github.com/Chocobozzz/PeerTube/commit/23ac334389a6b11ba0656a18ff760fb45f7bec57

But I think it won't help in your case since the cause of your issue seems to be https://github.com/Chocobozzz/PeerTube/issues/3793

**Comment by manalejandro** [comment]
Obviously it has nothing related to the ORM with the jobs so the issues are different causes.
