### ISSUE TITLE
Articafts in videos with black background (but not always)

### ISSUE THREAD

**Issue by Nartagnan** [Chocobozzz/PeerTube#3795]
**Describe the current behavior**
The window behind Firefox appear in the black background but only when :
1. in play
2. at the top (not scrolled)

In pause or if I scroll down even a pixel, the background is nice again.
(that's how I know it is not the video itself)

Nb: sometimes it is only a black rectangle and a grey-er background everywhere-else).

It is just a discrete layer, only visible because of the black background. Images of the video are still clearly visible.
I don't see it with white background but I cannot be sure.

**Steps to reproduce:**
1. Play this video
https://skeptikon.fr/videos/watch/792bbc45-7466-424e-a480-dc2a54a004f8

2. Go to a mainly-black timecode (for example 3'19")

3. see the artifact when play and scroll down a little (or pause) to see it disappear

4. change the window "behind" to see new artifacts.

5. take a screenshot, it is still here.

**Describe the expected behavior**
A nice black background

**Additional information**
Firefox 84.0.2  (official deb)
On Kubuntu 20.04

**Comment by Chocobozzz** [comment]
Hello and thanks for this issue.

I can't reproduce but it does not seem to be a peertube issue (we just use a `video` tag). It's rather a firefox on kubuntu issue. Please test using firefox nightly and report this behaviour on their bug tracker if it's still here
