### ISSUE TITLE
socket closed。upload api return no code

### ISSUE THREAD

**Issue by Jenner-Zhl** [Chocobozzz/PeerTube#3798]
**Describe the current behavior**
I use /api/v1/videos/upload api to upload a video and checked the logs. Sometimes it works fine, output the log like:
{"level":"info","message":"Creating torrent /www/wwwroot/peertube/storage/torrents/e8e4b2e3-9185-4017-8cb0-778b9be2e305-240.torrent.","label":"47.104.28.129:9000","timestamp":"2021-02-26T09:19:50.789Z"}
{"level":"info","message":"Video with name wwweds and uuid e8e4b2e3-9185-4017-8cb0-778b9be2e305 created.","label":"47.104.28.129:9000","timestamp":"2021-02-26T09:19:51.372Z"}
{"message":"218.104.155.137 - - [26/Feb/2021:09:19:51 +0000] \"POST /api/v1/videos/upload HTTP/1.1\" 200 66 \"-\" \"okhttp/4.8.1\"\n","level":"info","label":"47.104.28.129:9000","timestamp":"2021-02-26T09:19:51.434Z"}

in the log I see the POST returned code 200.

but sometimes it issued "socked closed" in my client, but the video is already uploaded though the status is transcoding, output logs like:
{"level":"info","message":"Creating torrent /www/wwwroot/peertube/storage/torrents/73123eb3-abfa-4409-984a-c9f84f449e95-240.torrent.","label":"47.104.28.129:9000","timestamp":"2021-02-26T09:20:15.647Z"}
{"message":"218.104.155.137 - - [26/Feb/2021:09:20:15 +0000] \"POST /api/v1/videos/upload HTTP/1.1\" - - \"-\" \"okhttp/4.8.1\"\n","level":"info","label":"47.104.28.129:9000","timestamp":"2021-02-26T09:20:15.908Z"}
{"level":"info","message":"Video with name wwweds and uuid 73123eb3-abfa-4409-984a-c9f84f449e95 created.","label":"47.104.28.129:9000","timestamp":"2021-02-26T09:20:16.139Z"}

There is no code returned by the POST. What does this mean? 
**Describe the expected behavior**
When the video is uploaded, response code 200.

* PeerTube instance:
  * URL:
  * version: 2.4.0
  * NodeJS version:
  * Ffmpeg version: 4.3.1-static

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

I think the request is too long to proceed by the peertube endpoint. https://github.com/Chocobozzz/PeerTube/commit/d61893f7236abbed30c25b1823e6ecad93a8e8dd should fix this issue
