### ISSUE TITLE
Error: Missing lock for job 1792 finished

### ISSUE THREAD

**Issue by alejandrocobo** [Chocobozzz/PeerTube#3799]
**Describe the current behavior**
Since yesterday, there is a job transcoding a video to 720p. When it finishes, it begins again in a infinite loop. The transcoded 720p video is available and you can watch it.

I tried by restarting the peertube instance but as soon as it is started, the transcoding job begins again.

**Steps to reproduce:**

I really don't know. It has happened just once.

**Describe the expected behavior**

Once the file has been transcoded, the job shouldn't begin again.

**Additional information**

I would like to cancel this job without deleting the video.

* PeerTube instance:
  * URL: tubedu.org
  * version: 3.0.1
  * NodeJS version: v12.20.1
  * Ffmpeg version: 4.1.6-1~deb10u1

* Link to browser console log if relevant: 

Job: 1792 Type: video-transcoding 
Processed on Mar 1, 2021, 7:38:09 AM 
Finished on -

{   
"type": "new-resolution",  
 "videoUUID": "0395ecb8-41e2-47e1-86b0-4b1c1237d8b2",   
"resolution": 720,   
"isPortraitMode": false 
}

Error: Missing lock for job 1792 finished     
at Object.finishedErrors (/home/alex/x/peertube-tubedu/versions/peertube-v3.0.1/node_modules/bull/lib/scripts.js:185:16)     at /home/alex/x/peertube-tubedu/versions/peertube-v3.0.1/node_modules/bull/lib/scripts.js:172:23     
at runMicrotasks (<anonymous>)     
at processTicksAndRejections (internal/process/task_queues.js:97:5)

Thanks.

EDIT: There are no failed job related to this video.

**Comment by alejandrocobo** [comment]
I solved it by restarting the Redis server.

**Comment by Chocobozzz** [comment]
What is your redis version?

**Comment by alejandrocobo** [comment]
Redis 3.2.6.

**Comment by Chocobozzz** [comment]
Please upgrade to redis v5 or v6.
