### ISSUE TITLE
Autoplay url parameter ignored for lives?

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#3801]
**Describe the current behavior**

If I go to a permanent live that did not start, when it starts, the video don't start playing even if there is autoplay=1 in the url. 

**Steps to reproduce:**

1. Create a permanent live
2. Open it with autoplay=1 in the uri
3. Start streaming
4. The live picture and play button are displayed, but the live did not start automatically. 

**Describe the expected behavior**

As streaming begins, live should autoplay depending on user preferences and/or autoplay parameter.

* PeerTube instance:
  * version: 3.0.1

**Comment by Chocobozzz** [comment]
Hello,

Most of the time the web browser won't allow autoplay since the user did not interact with the document since PeerTube tried to autoplay the live after a websocket message. You could check the browser console to confirm this

**Comment by JohnXLivingston** [comment]
Oh, you are right. I have this warning. I have autoplay activated for other videos, so I meant it should work. But I understand the limitation in this case. Thanks.
