### ISSUE TITLE
Custom instance theme won't save from admin panel

### ISSUE THREAD

**Issue by hopeholdings** [Chocobozzz/PeerTube#3803]
**Describe the current behavior**

Won't save custom instance theme in admin panel as default

**Steps to reproduce:**

1.  Install custom theme
2. Try to set as instance default theme

**Describe the expected behavior**
Custom theme applied as default instance theme

**Additional information**

* PeerTube instance:  gorf.tube
  * URL:  https://gorf.tube/
  * version: 3.0.1
  * NodeJS version: 12
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: chrome 81
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

What do you mean by *Try to set as instance default theme*? Where do you update the setting? What do you see?

**Comment by hopeholdings** [comment]
As Admin go under Administration > Configuration > Basic Configuration > Appearance > Theme.  When we try to select our custom theme (installed in plugin theme area) it won't save it and apply as default theme for instance.

**Comment by Chocobozzz** [comment]
It's weird because it seems you did not install any plugin on your instance (https://gorf.tube/api/v1/config/)

**Comment by hopeholdings** [comment]
We have installed and uninstalled as testing.  Also, we have testing instance.

**Comment by hopeholdings** [comment]
Are you able to select a custom theme from plugin/theme and save as the default theme for instance?  It may be something on our end...

**Comment by Chocobozzz** [comment]
> We have installed and uninstalled as testing. Also, we have testing instance.

I'm not sure to understand but if you don't provide the instance with registered themes it's difficult for me to help.


> Are you able to select a custom theme from plugin/theme and save as the default theme for instance

Yes we are: https://framatube.org/

**Comment by hopeholdings** [comment]
Okay, so this is from my dev. and was the result of us copy-pasting to the new version instead of running upgrade.
We have 2 files in config folder:
local-production.yml
local-production.json

the peertube server-side logic writes our changes from configuration into local-production.json file and after that read config data from old local-production.yml file

We fixed it by removing the local-production.yml file
