### ISSUE TITLE
Ability for admins to directly send mails/notifications to the user

### ISSUE THREAD

**Issue by ppnplus** [Chocobozzz/PeerTube#3805]
**Describe the problem to be solved**
As I've tried looking for so far, I haven't seen any way to manually send emails (like important announcements/notices) directly from the instance to the user, especially to many users (or all users) at once, just like when confirming an account or resetting password.

I also want these notifications ("admin messages") to be sent directly to logged in users in their notification panel.

**Describe the solution you would like:**
Like Mastodon's simillar feature to send warnings directly to a user, admins can use their administration page to send emails from the instance to a user, multiple users, or all users. These messages would also show up in the user's notifications when logged in.

**Comment by seniorm0ment** [comment]
This is something I really would like to see, but also in reverse. The ability for users to contact an admin directly through PeerTube over issues, without the user needing to use an email.

**Comment by Mastercuber** [comment]
Maybe an [Announcement](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-announce) could be used for sending notifications to the users of the instance.

**Comment by jayrope** [comment]
I'd like to expand this in that Peertube needs a system, that let's both sysadmins and users communicate with each other beyond moderation issues. See request at #6523

**Comment by Chocobozzz** [comment]
I'm merging this issue in https://github.com/Chocobozzz/PeerTube/issues/6523 as I think it would also resolve OP use case
