### ISSUE TITLE
"message": "Ident authentication for user» peertube «failed" 

### ISSUE THREAD

**Issue by cr0co** [Chocobozzz/PeerTube#3806]
**Describe the problem**
cant start error:
"message": "Ident authentication for user» peertube «failed" 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
sudo journalctl -feu peertube

`{"err":{"stack":"SequelizeConnectionError: Ident-Authentifizierung für Benutzer »peertube« fehlgeschlagen\n    at Client.connection.connect.err [as _connectionCallback] (/var/www/peertube/versions/peertube-v3.0.1/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:184:24)\n    at Client._handleErrorWhileConnecting (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg/lib/client.js:305:19)\n    at Client._handleErrorMessage (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg/lib/client.js:325:19)\n    at Connection.emit (events.js:198:13)\n    at parse (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg/lib/connection.js:115:12)\n    at Parser.parse (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:40:17)\n    at Socket.stream.on (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/index.js:10:42)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)","message":"Ident-Authentifizierung für Benutzer »peertube« fehlgeschlagen","name":"SequelizeConnectionError","parent":{"stack":"error: Ident-Authentifizierung für Benutzer »peertube« fehlgeschlagen\n    at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:278:15)\n    at Parser.handlePacket (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.stream.on (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/index.js:10:42)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)","message":"Ident-Authentifizierung für Benutzer »peertube« fehlgeschlagen","length":112,"name":"error","severity":"FATAL","code":"28000","file":"auth.c","line":"305","routine":"auth_failed"}},"level":"error","message":"Unable to connect to PostgreSQL database.","label":"patrioten.tube:443","timestamp":"2021-03-02T16:22:46.304Z"}`

**Comment by Chocobozzz** [comment]
Please check your postgresql credentials in peertube conf + your `pg_hba.conf` file.

See also https://serverfault.com/a/406607
