### ISSUE TITLE
Please include build-essential package in Dockerfile.buster

### ISSUE THREAD

**Issue by manalejandro** [Chocobozzz/PeerTube#3809]
**Please include `build-essential` package in [Dockerfile.buster](https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/Dockerfile.buster#L10)**
```
gyp ERR! stack Error: not found: make
```
**Steps to reproduce:**

1. clone repo && cd repo
2. docker build -t peertube -f ./support/docker/production/Dockerfile.buster .

**Should build the image**

**Additional information**

* Docker version: Docker version 20.10.4, build d3cb89e

* Browser name, version and platforms on which you could reproduce the bug: none
* Link to browser console log if relevant: none
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): none

**Comment by rigelk** [comment]
On what platform are you building the image? I can't reproduce your error.

**Comment by manalejandro** [comment]
:thinking: arm64

**Comment by Chocobozzz** [comment]
Done in https://github.com/Chocobozzz/PeerTube/commit/ada9762f81fa48d50db69a2312075e71326e71fd
