### ISSUE TITLE
PGSQL ERROR:  relation "Applications" does not exist at character 32 (at starting)

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#381]
* **PeerTube version or URL:** 1.0.0-beta.1
* **NodeJS version:** v9.8.0
* **PostgreSQL version:** 9.6.8

I had this postgresql error after each start of peertube.
Already present with the two last alpha versions.

* **Server log if useful (Gist/Pastebin...):**
```
Mar 22 23:06:38 peertube postgres[83035]: [3-1] ERROR:  relation "Applications" does not exist at character 32
Mar 22 23:06:38 peertube postgres[83035]: [3-2] STATEMENT:  SELECT "migrationVersion" FROM "Applications"
```

**Comment by Chocobozzz** [comment]
Thanks, fixed: https://github.com/Chocobozzz/PeerTube/commit/3660d6c3c7ddacfb54d4a3bb42bc93467e7a75af
