### ISSUE TITLE
Convert uploaded videos into webm formats

### ISSUE THREAD

**Issue by Huy-Ngo** [Chocobozzz/PeerTube#3811]
## Describe the problem to be solved

[MP4 is a proprietary format][mp4] whose codecs are excluded by some GNU/Linux distros, for example [openSUSE][blacklist]. This has prevented me from watching many videos because they're encoded using MP4 format, which is the most familiar with most people. Ironically, I don't experience this watching YouTube because they convert videos into WebM format.

[mp4]: https://directory.fsf.org/wiki/Collection:File_format
[blacklist]: https://en.opensuse.org/openSUSE:Build_Service_application_blacklist#Software_which_is_encumbered_by_patent_claims

## Describe the solution you would like

Due to the problem above, I believe it's crucial to add a converter that automatically convert videos into a free format like WebM.
This may cause long upload time, but if that is the issue the webm version can be added after the video is converted.

## Describe alternatives you have considered

I have tried to install the h264 codec for mp4, but since the provider server for the codec was down earlier this year, it is no longer available option for me.

**Comment by rigelk** [comment]
Hi, please see https://github.com/Chocobozzz/PeerTube/issues/481#issuecomment-769799300 and the whole thread before it before opening an issue requesting all videos to be in webm.

**Comment by rempas** [comment]
@rigelk Didn't @Chocobozzz said to open a dedicated issue in the reply you linked or is there something I don't understand?
