### ISSUE TITLE
Missing videoRedundancy table in postgres

### ISSUE THREAD

**Issue by frankstrater** [Chocobozzz/PeerTube#3812]
**Describe the problem**

When upgrading my PeerTube instance, I keep getting a migration error due to a supposedly missing videoRedundancy relation/table in postgres. I'm not sure how to fix this as I'm not that well versed with postgres.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Normal upgrade (automatic and manual) as described in the production guide. The instance will work, but I do have an issue that my instance will freeze after 12 hours (same as in https://github.com/Chocobozzz/PeerTube/issues/3793)

**Additional information**

https://peertube.linuxrocks.online

* PeerTube instance: 
  * version: 3.0.1
  * NodeJS version: 12.21.0
  * Ffmpeg version: 4.3.2
  * PostgreSQL version: 10.16
  * Redis: 4.0.9

From /var/www/peertube/storage/logs/peertube.log

{"level":"info","message":"Executing 0330-video-streaming-playlist.js migration script.","label":"localhost:9000","timestamp":"2021-03-02T09:14:06.193Z"}
{"level":"error","message":"Cannot execute migration 0330.","label":"localhost:9000","err":{"stack":"SequelizeDatabaseError: relation \"videoRedundancy\" does not exist\n    at Query.formatError (/var/www/peertube/versions/peertube-v3.0.1/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)\n    at Query.run (/var/www/peertube/versions/peertube-v3.0.1/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","message":"relation \"videoRedundancy\" does not exist","name":"SequelizeDatabaseError","parent":{"stack":"error: relation \"videoRedundancy\" does not exist\n    at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:278:15)\n    at Parser.handlePacket (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v3.0.1/node_modules/pg-protocol/dist/index.js:10:42)\n    at Socket.emit (events.js:314:20)\n    at addChunk (_stream_readable.js:297:12)\n    at readableAddChunk (_stream_readable.js:272:9)\n    at Socket.Readable.push (_stream_readable.js:213:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)","message":"relation \"videoRedundancy\" does not exist","length":113,"name":"error","severity":"ERROR","code":"42P01","file":"namespace.c","line":"407","routine":"RangeVarGetRelidExtended","sql":"ALTER TABLE \"videoRedundancy\" ALTER COLUMN \"videoFileId\" DROP NOT NULL;ALTER TABLE \"videoRedundancy\" ALTER COLUMN \"videoFileId\" SET DEFAULT NULL;ALTER TABLE \"videoRedundancy\" ALTER COLUMN \"videoFileId\" TYPE INTEGER;"},"sql":"ALTER TABLE \"videoRedundancy\" ALTER COLUMN \"videoFileId\" DROP NOT NULL;ALTER TABLE \"videoRedundancy\" ALTER COLUMN \"videoFileId\" SET DEFAULT NULL;ALTER TABLE \"videoRedundancy\" ALTER COLUMN \"videoFileId\" TYPE INTEGER;"},"timestamp":"2021-03-02T09:14:06.215Z"}

**Comment by Chocobozzz** [comment]
From which version did you upgrade?

**Comment by frankstrater** [comment]
I've been upgrading this server since v1.4 (end of 2019) with official releases (no RC). The most recent upgrade was from 3.0.0 to 3.0.1. 

I might have missed this (non-critical?) error all this time, but only noticed this now.

**Comment by Chocobozzz** [comment]
It's really weird because the `videoRedundancy` table has been introduced in v1 beta: https://github.com/Chocobozzz/PeerTube/commit/c48e82b5e0478434de30626d14594a97f2402e7c#diff-a4fcf2df14f91f5306fbe4952ee270d0f328bb29deda014aaa379b55bffef0c7

And your instance tries to run a migration that has been introduced in 1.3 (https://github.com/Chocobozzz/PeerTube/commit/092092969633bbcf6d4891a083ea497a7d5c3154#diff-cd0b0096958a5d0eac8fb6263bb3a04ccd9aa36a892d23a07b7af34db29a8343). I don't know what happened but it seems that your instance DB is broken

**Comment by frankstrater** [comment]
Ok, thanks. I'm not sure what happened before I took over the instance before 1.4, so maybe the problem was introduced there. 

Is there any way I can fix this broken instance DB? Like as in: create the table in postgres and run the migration again?

**Comment by frankstrater** [comment]
This is what I see in the tables for peertube_prod:

```
                  List of relations
 Schema |          Name           | Type  |  Owner
--------+-------------------------+-------+----------
 public | abuse                   | table | peertube
 public | abuseMessage            | table | peertube
 public | account                 | table | peertube
 public | accountBlocklist        | table | peertube
 public | accountVideoRate        | table | peertube
 public | actor                   | table | peertube
 public | actorFollow             | table | peertube
 public | application             | table | peertube
 public | avatar                  | table | peertube
 public | commentAbuse            | table | peertube
 public | oAuthClient             | table | peertube
 public | oAuthToken              | table | peertube
 public | plugin                  | table | peertube
 public | scheduleVideoUpdate     | table | peertube
 public | server                  | table | peertube
 public | serverBlocklist         | table | peertube
 public | tag                     | table | peertube
 public | thumbnail               | table | peertube
 public | user                    | table | peertube
 public | userNotification        | table | peertube
 public | userNotificationSetting | table | peertube
 public | userVideoHistory        | table | peertube
 public | video                   | table | peertube
 public | videoAbuse              | table | peertube
 public | videoBlacklist          | table | peertube
 public | videoCaption            | table | peertube
 public | videoChangeOwnership    | table | peertube
 public | videoChannel            | table | peertube
 public | videoComment            | table | peertube
 public | videoFile               | table | peertube
 public | videoImport             | table | peertube
 public | videoLive               | table | peertube
 public | videoPlaylist           | table | peertube
 public | videoPlaylistElement    | table | peertube
 public | videoRedundancy         | table | peertube
 public | videoShare              | table | peertube
 public | videoStreamingPlaylist  | table | peertube
 public | videoTag                | table | peertube
 public | videoView               | table | peertube
```

**Comment by frankstrater** [comment]
Closing the issue as this is probably related to residual effects from a non-clean production install in the past.
