### ISSUE TITLE
Discriminate RSS video/live

### ISSUE THREAD

**Issue by Zykino** [Chocobozzz/PeerTube#3813]
Is there a way (a field?) to differentiate a video item from a live item in the account RSS feed?
Starting a live I was surprise to have a notification on RSS.

Use case:
I create a notification on Discord on a specific channel when a video is published. I already am announcing lives on another channel, so I wanted a way to discriminate which content is which, either to post somewhere else or not at all when it is a live but still continue to post notification for videos.

**Comment by rigelk** [comment]
No, not yet. We're still pondering how to display lives within RSS feeds

**Comment by rigelk** [comment]
See https://github.com/Chocobozzz/PeerTube/issues/3786
