### ISSUE TITLE
Don't pause video when modal is opened

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3816]
**Describe the problem to be solved**
When opening a modal (Share, Support or Download) upon watching a video, the video gets paused. As a content creator you'd like the user  to open both Share and Support modals and act on them, I think users avoid to open the modals since it will pause their video. As a user you'd like to share and support a video while watching it.

**Describe the solution you would like:**
I'd like our users to be able to open the dialogs while watching a video (without it getting paused).

**Comment by rigelk** [comment]
Since habits might differ regarding video pause when opening a modal, we should probably put this feature behind a user preference. Until then I would rather not change the current behaviour.

**Comment by Chocobozzz** [comment]
IMHO the user preference is overkill. I mean if the user wants to pause the video to read something in a modal, it can easily do it. However, this forced video pause can not be changed by the user (it can't listen to the video while reading sharing the video for example, which can be annoying)
