### ISSUE TITLE
Allow anonymous comments during live stream

### ISSUE THREAD

**Issue by rasos** [Chocobozzz/PeerTube#3817]
Occasional users should not be required to sign up, if they just want to leave a comment during a live event, when usually a moderator is available. So I would like to discuss if PeerTube should offer an option that comments are possible during live streams without barriers, maybe just a very simple captcha.

**Comment by Chocobozzz** [comment]
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/2228 and https://github.com/Chocobozzz/PeerTube/issues/3098
