### ISSUE TITLE
We couldn't find any ressource tied to the URL

### ISSUE THREAD

**Issue by tiotrom** [Chocobozzz/PeerTube#3819]
**Describe the current behavior**
I embed a playlist as such:
`<iframe width="560" height="315" sandbox="allow-same-origin allow-scripts allow-popups" src="https://videos.trom.tf/video-playlists/embed/974c14d7-00c6-4178-9d32-84db2c640f66?playlistPosition=1" frameborder="0" allowfullscreen></iframe>`

I click the peertube logo from the playlist (any video) and normally I expect to redirect me to the peertube instance, to that particular video. But it redirects to a "404.That's an error." page.

```
 We couldn't find any ressource tied to the URL /video-playlists/watch/974c14d7-00c6-4178-9d32-84db2c640f66 you were looking for.
Possible reasons:

    The page may have been moved or deleted
    You may have used an outdated or broken link
    You may have typed the address or URL incorrectly
```

* PeerTube instance:  https://videos.trom.tf/ (but I tried on multiple instances and it is the same)
  * URL: https://videos.trom.tf/videos/watch/playlist/974c14d7-00c6-4178-9d32-84db2c640f66?playlistPosition=1
  * version: 3.0.1

* Browser name, version and platforms on which you could reproduce the bug: Firefox and Chromium

**Comment by tiotrom** [comment]
If I copy the video link (right click on the video) from a playlist that's on the instance, it looks like this and it works:
https://videos.trom.tf/videos/watch/playlist/974c14d7-00c6-4178-9d32-84db2c640f66?playlistPosition=1
But if I do the same for a video from the same playlist that's embed to a website, I get a non working url that looks like this:
https://videos.trom.tf/video-playlists/watch/974c14d7-00c6-4178-9d32-84db2c640f66

Working: https://videos.trom.tf/videos/watch/playlist/974c14d7-00c6-4178-9d32-84db2c640f66?playlistPosition=1
Not working: https://videos.trom.tf/video-playlists/watch/974c14d7-00c6-4178-9d32-84db2c640f66

So I suspect it is an error in the url structure for embed playlists.

**Comment by Chocobozzz** [comment]
Thanks for the issue, should be fixed in https://github.com/Chocobozzz/PeerTube/commit/0bd6d35f13184d8aff883121ea0e835ba6c91497
