### ISSUE TITLE
Reverse playlist order in embed playlist

### ISSUE THREAD

**Issue by tiotrom** [Chocobozzz/PeerTube#3820]
My request is quite simple: to reverse the order of playlist items. For example, I'd like for the playlist to start with the latest added video to the playlist.

**Comment by Chocobozzz** [comment]
Hi, 

Thanks for this issue but it's out of the scope of PeerTube. A plugin could be created to implement this kind of feature though.

**Comment by tiotrom** [comment]
Hi. But shouldn't this be at least considered? There are ways to embed based on a timeframe, which seems quite specific and niche. Reverting the order in a playlist serves a very practical use: you embed a playlist of your latest videos and want for users to see your latest ones. It is something quite used I'd say. Maybe you will consider this as important enough to add as a Peertube core functionality ;). Cheers!

**Comment by Chocobozzz** [comment]
It's not we don't consider this as important, but we don't have time to implement and maintain this feature that does not seem much requested. Of course we can reconsider this in the future, depending on users needs :)
