### ISSUE TITLE
Keyboard shortcut for focusing video

### ISSUE THREAD

**Issue by Oymate** [Chocobozzz/PeerTube#3821]
**Describe the problem to be solved**
Videos are not focused as soon as I click somewhere.

**Describe the solution you would like:**
Something like a keyboard shortcut may solve this.

**Describe alternatives you have considered** 
Automatically recognise if a video shortcut is used and focus and execute that action on video

**Comment by Chocobozzz** [comment]
Hi,

I'm not sure to understand: why do you want to focus the player? Is it to navigate in the control bar buttons? Because the player hotkeys can be used even if the player is not focused.

**Comment by Oymate** [comment]
Yes the player hotkeys frequently do not work if it is not focused. So, I thought maybe a focus shortcut could be used.

**Comment by Chocobozzz** [comment]
> Yes the player hotkeys frequently do not work if it is not focused.

Could you try to elaborate and provide steps to reproduce? Because if sometimes player hotkeys don't work it's a bug

**Comment by Oymate** [comment]
For example: in this video site https://tilvids.com/videos/watch/cc3014a6-6277-4f33-a763-619a67914471

If I select someplace outside the video say a LMB on a comment(not button) then the player hotkeys don't work.

**Comment by Oymate** [comment]
Seems to be fixed for now.
Closing not reproducible

**Comment by Oymate** [comment]
@Chocobozzz this seems to be seldom reproducable please reopen. To recap
> If I select someplace outside the video say a LMB on a comment text(not button) then the player hotkeys don't work.

**Comment by Chocobozzz** [comment]
Do you have error in your web browser logs?
