### ISSUE TITLE
Advanced configuration doesn't work in German

### ISSUE THREAD

**Issue by Findus23** [Chocobozzz/PeerTube#3823]
**Describe the current behavior**

When switching between tabs in the admin configuration page, once one selects "advanced configuration", the tabs stop working and nothing changes anymore when clicking on them. This only occurs when PeerTube is set to German (English works).

https://user-images.githubusercontent.com/6266037/109953218-0eef1480-7ce0-11eb-896e-8a3e2a1239ce.mp4

Also this error appears in console (including the �):
> ERROR Error: Unable to parse ICU expression in "{�0�, Plural, =1 {Bild im Cache} other {Bilder im Cache}}" message.

**Steps to reproduce:**
1. use PeerTube 3.1.0-rc.1
1. set PeerTube to German
2. go to `/admin/config/edit-custom`
3. click on the tabs until you reach the last tab

**Describe the expected behavior**

advanced configuration tab should work in German

**Additional information**

* PeerTube instance:
  * URL: https://video.lw1.at/
  * version: 3.1.0-rc.1

* Browser name, version and platforms on which you could reproduce the bug: Firefox 86 on Debian Testing

**Comment by Chocobozzz** [comment]
Thanks @Findus23, should be fixed
