### ISSUE TITLE
Videos in different languages are displayed

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#3825]
**Describe the current behavior**
The Trending (Views) page displays videos in other languages, even if my native language is Russian in my profile settings.
On the Best, Hot, Likes pages everything is displayed correctly.

**Steps to reproduce:**
In my profile, I select the language - Russian, then open the Trending (Views) page

**Describe the expected behavior**
If my language "Russian" is selected in the profile, then on all pages, as well as on the right side in the Other videos section, only those videos that have my selected language specified should be displayed.

**PeerTube instance:**
 * URL: https://peervideo.ru
 * version: 3.0.1-rc.1
 * NodeJS version: 12.20.1
 * Ffmpeg version: 4.1.6-1~deb10u1
 * Browser name, version and platforms on which you could reproduce the bug:
 * Google Chrome v.88.0.4324.150 (64 bit)

![Screenshot_1](https://user-images.githubusercontent.com/11453567/109968678-132d2900-7d04-11eb-9d0e-60f79bdd8d9a.png)

**Comment by Chocobozzz** [comment]
Hello,

I think it's because these videos have a russian caption

**Comment by Alterak** [comment]
> Hello,
> 
> I think it's because these videos have a russian caption

![Screenshot_1](https://user-images.githubusercontent.com/11453567/109996855-ad9b6580-7d20-11eb-8cd8-f7489c08b0ed.png)

These videos are listed as English, I selectively checked about 30 different videos ... and all of them are listed as English.
Or did you mean a different signature?

**Comment by Chocobozzz** [comment]
> Or did you mean a different signature?

I mean the audio is in english, but the video has also russian subtitles. It's the reason why PeerTube display them even if you selected russian in your user config.
