### ISSUE TITLE
About v3.1.0 rc.1 transcoding option for libaom-av1

### ISSUE THREAD

**Issue by meredith2u** [Chocobozzz/PeerTube#3828]
When ffmpeg using libaom-av1 for encoding, ffmpeg only using 1 thread, is my setting wrong? any other suggestions?
Also, can I change the audio encoding used in the video? such as libopus.

Here is config
**Transcoding profiles**
```
{
  "vod": [
    {
      "encoderName": "libaom-av1",
      "profileName": "av1",
      "outputOptions": ["-row-mt 1", "-tile-columns 2", "-tile-rows 2", "-cpu-used 8"]
    }
  ],

  "live": []
}
```
**Encoders priorities**
```
{
  "vod": [
   {
      "encoderName": "libaom-av1",
      "streamType": "video",
      "priority": 200
    }
  ],

  "live": []
}
```

**Comment by Chocobozzz** [comment]
>  ffmpeg only using 1 thread, is my setting wrong?

No it seems okay. Maybe you can check the threads option in admin config?

> Also, can I change the audio encoding used in the video? such as libopus.

Yes, you can use any encoders you want for audio/video. But the web browser might be not able to play the files.

**Comment by meredith2u** [comment]
> > ffmpeg only using 1 thread, is my setting wrong?
> 
> No it seems okay. Maybe you can check the threads option in admin config?
> 
> > Also, can I change the audio encoding used in the video? such as libopus.
> 
> Yes, you can use any encoders you want for audio/video. But the web browser might be not able to play the files.

On my admin config is set for 16 threads for encoding, and I can see on ffmpeg commands is correctly using 16 threads, but actually only used 1 thread.

About audio in video, I don't no how to set libaom-av1 and libopus as same time for enconding, I'm tryed Transcoding profileName using same name for libaom-av1 and libopus, but ffmpeg fail.

**Transcoding profiles**
```
{
  "vod": [
    {
      "encoderName": "libaom-av1",
      "profileName": "av1",
      "outputOptions": ["-row-mt 1", "-tile-columns 2", "-tile-rows 2", "-cpu-used 8"]
    }
    {
      "encoderName": "libopus",
      "profileName": "av1",
      "outputOptions": []
    }
  ],

  "live": []
}
```
Encoders priorities
```
{
  "vod": [
   {
      "encoderName": "libaom-av1",
      "streamType": "video",
      "priority": 200
    }
   {
      "encoderName": "libaom-av1",
      "streamType": "audio",
      "priority": 200
    }
  ],

  "live": []
}
```

**Comment by Chocobozzz** [comment]
> ffmpeg commands is correctly using 16 threads

Then it seems to be an encoder issue, maybe threading is not well supported by your encoder.

> , but ffmpeg fail.

Your config seems invalid, it should be:

```
{
  "vod": [
   {
      "encoderName": "libaom-av1",
      "streamType": "video",
      "priority": 200
    }
   {
      "encoderName": "libopus",
      "streamType": "audio",
      "priority": 200
    }
  ],

  "live": []
}
```

**Comment by meredith2u** [comment]
> > ffmpeg commands is correctly using 16 threads
> 
> Then it seems to be an encoder issue, maybe threading is not well supported by your encoder.
> 
> > , but ffmpeg fail.
> 
> Your config seems invalid, it should be:
> 
> ```
> {
>   "vod": [
>    {
>       "encoderName": "libaom-av1",
>       "streamType": "video",
>       "priority": 200
>     }
>    {
>       "encoderName": "libopus",
>       "streamType": "audio",
>       "priority": 200
>     }
>   ],
> 
>   "live": []
> }
> ```

Here is modifed config, ffmpeg still fail.
**Transcoding profiles**
```
{
  "vod": [
    {
      "encoderName": "libaom-av1",
      "profileName": "av1",
      "outputOptions": ["-row-mt 1", "-tile-columns 2", "-tile-rows 2", "-cpu-used 8"]
    }
    {
      "encoderName": "libopus",
      "profileName": "av1",
      "outputOptions": ["-b:a 128k"]
    }
  ],

  "live": []
}
```
**Encoders priorities**
```
{
  "vod": [
   {
      "encoderName": "libaom-av1",
      "streamType": "video",
      "priority": 200
    }
   {
      "encoderName": "libopus",
      "streamType": "audio",
      "priority": 200
    }
  ],

  "live": []
}
```

**Comment by meredith2u** [comment]
@Chocobozzz I found the reason why ffmpeg only uses a single thread, because ubuntu 20.04 only can install ffmpeg 4.2.x, if I want to use multi-thread for av1 enconding, I need install ffmpeg over 4.3.x
