### ISSUE TITLE
Hooks for search API

### ISSUE THREAD

**Issue by geco** [Chocobozzz/PeerTube#3831]
Hi @Chocobozzz, i'm using these plugin client hooks:
- filter:api.trending-videos.videos.list.result
- filter:api.most-liked-videos.videos.list.result
- filter:api.local-videos.videos.list.result
- filter:api.recently-added-videos.videos.list.result
- filter:api.user-subscriptions-videos.videos.list.result
to inject plugin data into video list pages.

I can't find a similar client hook to inject plugin data into Discover (/videos/overview) page.
Does it exist?

**Comment by geco** [comment]
@Chocobozzz sorry, i've similar question for search pages, but server side. If i need to inject plugin data into video search results, there is a server hook like the filter:api.videos.list.result? thanks

**Comment by Chocobozzz** [comment]
> I can't find a similar client hook to inject plugin data into Discover (/videos/overview) page.

No sorry this is not possible. We plan to remove the discover page in favour of https://github.com/Chocobozzz/PeerTube/issues/3582 in the future

> If i need to inject plugin data into video search results, there is a server hook like the filter:api.videos.list.result

No there is no hook for the search API yet

**Comment by geco** [comment]
Hi, I've solved this way:
- I've created a plugin server route that accepts "url" as query param and return plugin data
- Client side plugin invokes that route extracting url from video href and get needed own data
Does it make sense @Chocobozzz ?

Thanks

**Comment by Chocobozzz** [comment]
Hooks added in https://github.com/Chocobozzz/PeerTube/commit/aff7fdf631c3266c12b8a120674280e43736ed75
