### ISSUE TITLE
error import videos

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#3834]
![Captura de pantalla de 2021-03-06 01-18-53](https://user-images.githubusercontent.com/43164089/110197511-fa169c00-7e19-11eb-9149-3f1f8f7ca40e.png)

I imported other times videos from youtube without problems, I got an error when importing 3 videos from youtube, it turns out now that it only gives me [Error Cannot fetch remote information of this URL.] and I don't care about any more

Example a log
```
Job: 11 Type: video-import Processed on Feb 26, 2021, 5:18:22 PM Finished on Feb 26, 2021, 6:18:23 PM
--
{   "type": "youtube-dl",   "videoImportId": 11,   "generateThumbnail": false,   "generatePreview": false,   "fileExt": ".mp4" }
Error: YoutubeDL download timeout.     at Timeout._onTimeout (/var/www/peertube/versions/peertube-v3.0.1/dist/server/helpers/youtube-dl.js:96:29)     at listOnTimeout (internal/timers.js:554:17)     at processTimers (internal/timers.js:497:7)
```
Peertube: v3.0.1
nodejs 12.20.2

**Comment by AnonymousWebHacker** [comment]
I understand that the Timeout may be due to a slow connection or that it cannot be found, but the instance does have internet (it pings external sites, and the list of plugins and themes appears), but I don't want to import video from anywhere

Is there any way to see the youtube.dl logs in the console to see what another error could be?

**Comment by AnonymousWebHacker** [comment]
YouTube
  lynx https://www.youtube.com/watch?v=0ZLW7aHfp
  Alert!: HTTP/1.0 429 Too Many Requests

  ``` Sorry for the interruption. We have been receiving a large volume of requests from your network.

   To continue with your YouTube experience, please fill out the form below.
   Submit
   ____________________
   (BUTTON) Search

   [Document has only hidden links. Use the 'l'ist command.]
```

**Comment by rigelk** [comment]
> 429 Too Many Requests

It seems your IP is being rate-limited. Unfortunately there isn't much we can do about it. Please reach out to the youtubedl project for counter-measures.

**Comment by AnonymousWebHacker** [comment]
@rigelk url youtubedl repo?

**Comment by AnonymousWebHacker** [comment]
@Chocobozzz Can you give me an idea here?
The peertube instance, when trying some videos and a period of time that the internet connection was bad, due to the failed import attempts, it seems that youtube blocks the host for so many requests.

I installed google chorme to the vps, and I was able to access youtube without problems, however, from the terminal example with lynx ,, there are many requests.

Do you know any other variant?

**Comment by sunknudsen** [comment]
I just tried publishing video to a self-hosted PeerTube instance using [tube-manager](https://github.com/sunknudsen/tube-manager) and `POST https://peertube.sunknudsen.com/api/v1/videos/imports` returned the following.

```json
{
  statusCode: 400,
  body: { error: 'Cannot fetch remote information of this URL.' }
}
```

Any idea what is causing this? First time I run into this issue.

**Comment by AnonymousWebHacker** [comment]
> ```json
> Cannot fetch remote information of this URL
> ```

400 has passed me a lot.
Example, it has happened to me because I have the internet on and off and I have very good speed.
When I am importing a video from YouTube and I lose the internet or it is very slow, it gives an import error (when trying several times to download it)

As a result of this problem, it also happens that youtube detects unusual traffic from that instance to peertube (the various attempts to import) and ends up blocking that URL.

And another variant, (the common thing) why it causes this is, that the link that you are trying to import, you do not have access.
or
many unsuccessful attempts and the youtube-dl does not allow

Solution, wait approximately 3 days and try to import it again

If you want to verify that your domain is blocked, try to access that same video from lynx
lynx URL

**Comment by sunknudsen** [comment]
Thanks for helping out @AnonymousWebHacker.

My instance runs on an always-on VPS... this is the first time I can't import a video using YouTube URL.

I ran `curl "https://www.youtube.com/watch?v=1bk8YFsgVms"` on the VPS and output is identical to output on my computer at home.

@Chocobozzz, is this an issue you are aware of?

**Comment by sunknudsen** [comment]
I confirm my VPS is not blocked by YouTube.

```console
$ youtube-dl --format "bestvideo[ext=mp4][height<=1080]+bestaudio[ext=m4a]/best[ext=mp4]/best" "https://www.youtube.com/watch?v=1bk8YFsgVms"
[youtube] 1bk8YFsgVms: Downloading webpage
[download] Destination: The hustle-1bk8YFsgVms.f137.mp4
[download] 100% of 62.05MiB in 00:09
[download] Destination: The hustle-1bk8YFsgVms.f140.m4a
[download] 100% of 9.38MiB in 00:01
[ffmpeg] Merging formats into "The hustle-1bk8YFsgVms.mp4"
Deleting original file The hustle-1bk8YFsgVms.f137.mp4 (pass -k to keep)
Deleting original file The hustle-1bk8YFsgVms.f140.m4a (pass -k to keep)
```

**Comment by sunknudsen** [comment]
I ended up creating a separate [issue](https://github.com/Chocobozzz/PeerTube/issues/3882) given what I am experiencing appears to be different.

**Comment by AnonymousWebHacker** [comment]
> My instance runs on an always-on VPS... this is the first time I can't import a video using YouTube URL.

It's weird, that error has happened to me before, [Cannot fetch remote information of this URL." ]and it's because of connection problems, maybe, I see that it could be something else
