### ISSUE TITLE
Plugin settings: bug on checkbox with default=true

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#3838]
**Describe the current behavior**
In a plugin, if I have a checkbox settings with default value ``true``, it will always be checked when refreshing the settings page.

A user of my plugin https://github.com/JohnXLivingston/peertube-plugin-livechat had the following bug: https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/13

**Steps to reproduce:**

1. Install the plugin peertube-plugin-livechat
2. Go to plugin settings
3. Uncheck «Chats are only available for local videos.» or «Use builtin ConverseJS»
4. Refresh the settings page
5. The checkbox will be checked again

**Describe the expected behavior**

Checkbox should remain unchecked (default value should not override false, only undefined values)

**Additional information**

the settings declaration:
```
registerSetting({
    name: 'chat-use-builtin',
    label: 'Use builtin ConverseJS',
    type: 'input-checkbox',
    default: true,
    private: false,
    descriptionHTML: '...'
  })
```

* PeerTube instance:
  * version: 3.0.1

* Browser name, version and platforms on which you could reproduce the bug: Firefox

**Comment by Chocobozzz** [comment]
Hi and thanks for the issue. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/253d4ab621ea6b6d916e3c425a6c21643d61be43
