### ISSUE TITLE
Peertube from mastodon : following peertube@instance isn't enough to get every new videos

### ISSUE THREAD

**Issue by PhieF** [Chocobozzz/PeerTube#384]
* **PeerTube version or URL:** beta2
* **Browser name/version:** firefox 59.1
* **NodeJS version:** 

* **What is the expected behaviour?**

Following peertube@instance from mastodon should be enough to get all new videos from the peertube instance

* **What do you see instead?**

example of the issue
User A on mastodon follows both peertube@instance and B@instance

if B posts a video:
A will receive a toot from B@instance and peertube@instance (which is a "retoot")

but

if User C (not followed by A) posts a video, A won't receive any retoot from peertube@instance

Am I not understanding something ? It seems really weird, doesn't it ?

Thanks !

**Comment by Chocobozzz** [comment]
Hi, thanks for the issue @PhieF. I think it's a Mastodon issue: https://github.com/tootsuite/mastodon/issues/6878

**Comment by PhieF** [comment]
OK thanks !

**Comment by PhieF** [comment]
bad and ugly script to retoot every new videos on mastodon

https://github.com/PhieF/MiscConfig/blob/master/Peertube/peertubetomasto.py

until they fix that

**Comment by Chocobozzz** [comment]
Should be fixed: https://github.com/Chocobozzz/PeerTube/commit/fc27b17c6b4ddaef2db8e7086d3f74c081026bd9
