### ISSUE TITLE
How are the video suggestions working?

### ISSUE THREAD

**Issue by tiotrom** [Chocobozzz/PeerTube#3841]
How does peertube recommend videos on the "recommended videos" tab, bellow each video? What is the algorithm? Does it look at the title? Tags? Local videos have priority?

Would be great to be able to tweak that in the admin and user settings.

**Comment by Chocobozzz** [comment]
Hello,

We use video tags to search similar videos. We would like to develop a plugin api so admins can install the algo they want. Subscribe https://github.com/Chocobozzz/PeerTube/issues/1004 to get updates on that
