### ISSUE TITLE
Docker image multi-arch support

### ISSUE THREAD

**Issue by forzagreen** [Chocobozzz/PeerTube#3842]
The PeerTube Docker images in [Docker Hub](https://hub.docker.com/r/chocobozzz/peertube) currently support only OS/arch of type `linux/amd64` .
It would be great to support multiple architectures (= platforms), in particular `linux/arm64` , as ARM processors are widely used.

It can be done without the need of maintaining another Dockerfile.
Docker Hub supports multi-architecture images. And Docker can pull the correct image based on the machine architecture.

### Usecases

- My usecase was to deploy PeerTube on a RaspberryPi, which has an ARM processor.
- Deploying PeerTube on any ARM machine.

#### If building in GitLab (with kaniko)

Starting from version [1.5.0](https://github.com/GoogleContainerTools/kaniko/releases/tag/v1.5.0) (2021-01-25), kaniko supports multi-arch images for `linux/amd64`, `linux/arm64` and `linux/ppc64le`. 

#### If building in GitHub

You can use [buildx](https://github.com/docker/buildx). It can build and push a multi-platform image without modifying the Dockerfile.
It integrates very well with CI/CD pipelines: 
Example of GitHub Actions: https://github.com/marketplace/actions/build-and-push-docker-images#multi-platform-image

### Related issues

- https://github.com/Chocobozzz/PeerTube/pull/1907
- https://github.com/wader/postfix-relay/issues/21

**Comment by Chocobozzz** [comment]
I think we'll move docker builds on github CI https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md

**Comment by Chocobozzz** [comment]
Should be implemented by https://github.com/Chocobozzz/PeerTube/commit/f3fbbf01402fc7491e044f160edca06ef793eb50
