### ISSUE TITLE
Video shows up as empty or very short after transcode, data lost

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#3844]
**Describe the current behavior**

This is an issue I've seen twice now, once during a command line transcode, and once just now as reported by a user just after a normal file upload.

The logs don't leave great clues for what's going on here, but this is the most interesting clue so far. Listing the files for the broken video reported by a user today:

```
-rw-r--r-- 1 peertube peertube     350049 Jan 28 16:32 0.m3u8
-rw-r--r-- 1 peertube peertube     368165 Jan 29 05:47 1080.m3u8
-rw-r--r-- 1 peertube peertube        309 Jan 29 05:52 1440.m3u8
-rw-r--r-- 1 peertube peertube     360401 Jan 29 00:52 240.m3u8
-rw-r--r-- 1 peertube peertube     360757 Jan 28 20:48 360.m3u8
-rw-r--r-- 1 peertube peertube     361644 Jan 28 19:01 480.m3u8
-rw-r--r-- 1 peertube peertube     363640 Jan 28 23:30 720.m3u8
-rw-r--r-- 1 peertube peertube  287199008 Jan 28 16:32 839c146c-b286-47cb-ba5f-3fd9c6917e68-0-fragmented.mp4
-rw-r--r-- 1 peertube peertube 4723639834 Jan 29 05:47 839c146c-b286-47cb-ba5f-3fd9c6917e68-1080-fragmented.mp4
-rw-r--r-- 1 peertube peertube      97412 Jan 29 05:52 839c146c-b286-47cb-ba5f-3fd9c6917e68-1440-fragmented.mp4
-rw-r--r-- 1 peertube peertube  654131806 Jan 29 00:52 839c146c-b286-47cb-ba5f-3fd9c6917e68-240-fragmented.mp4
-rw-r--r-- 1 peertube peertube 1048432191 Jan 28 20:48 839c146c-b286-47cb-ba5f-3fd9c6917e68-360-fragmented.mp4
-rw-r--r-- 1 peertube peertube 1551995499 Jan 28 19:01 839c146c-b286-47cb-ba5f-3fd9c6917e68-480-fragmented.mp4
-rw-r--r-- 1 peertube peertube 2838851050 Jan 28 23:30 839c146c-b286-47cb-ba5f-3fd9c6917e68-720-fragmented.mp4
-rw-r--r-- 1 peertube peertube        755 Jan 29 05:53 master.m3u8
-rw-r--r-- 1 peertube peertube    1788133 Jan 29 05:55 segments-sha256.json
```

The smaller resolutions seem to be correct length, but the 1440p file is a valid file with a very short length, as if it was transcoded from a truncated original, or its transcode was stopped. I don't see anything relevant in the peertube daemon logs, and there are no recent ffmpeg errors.

**Steps to reproduce:**

1. Configure server for HLS without webtorrent
2. Upload videos, especially long and high-res videos
3. Watch it break sometimes, notice lack of recovery options or log data.

**Describe the expected behavior**

I expect there not to be race conditions that truncate video sometimes, and I'd expect there to be a way to recover the original video and re-transcode in the event of such a problem.

**Additional information**

* PeerTube instance:
  * URL: diode.zone
  * version: 3.0.1
  * NodeJS version: 10.24.0
  * Ffmpeg version: 4.3.1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Please try 3.1 that should fix some transcoding issues. If not, don't hesitate to comment this ticket to reopen the issue.
