### ISSUE TITLE
Incorrect French in private playlists page.

### ISSUE THREAD

**Issue by pprw** [Chocobozzz/PeerTube#3845]
There is a little French issue when visiting /my-library/video-playlists page.

![image](https://user-images.githubusercontent.com/5262986/110304056-6d2b3880-7ffb-11eb-95a7-7c78223eda38.png)

Should be "Mise à jour il y a ..."

**Comment by rigelk** [comment]
hi @pprw,

Unless the issue stems from how we declare the strings to be translated, please follow https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/translation.md#translation in order to correct the french translation.
