### ISSUE TITLE
Mirror instance lost in followers list

### ISSUE THREAD

**Issue by c0xc** [Chocobozzz/PeerTube#3847]
**Describe the current behavior**

A mirror instance, which was set up to duplicate all videos of the original instance, has disappeared from the "followers" list of the original instance (the list on the left). It seems like it may have happened after the mirror instance was offline due to maintenance work for a couple of hours, but that's uncertain. Is the followers list cleaned up automatically (like when some instance hasn't sent a heartbeat in a day) and why isn't the mirror instance showing errors that it's following that origin instance while that origin instance is not followed by this mirror anymore?

Also, it might be an idea to have some sort of ping tool to let upstream instances know that this instance is alive again (after maintenance work took longer than expected, for example) and maybe also the other way around, to ping downstream instances to show how long they've been unreachable and let the admin decide when to remove them (but again, only remove downstream followers in a way that they know that they aren't following anymore in case they come back to live).

**Steps to reproduce:**

I don't know.

**Describe the expected behavior**

I wouldn't expect a downstream instance to disappear from the list.

**Additional information**

It seems like this also caused it to stop mirroring newer videos which is unfortunately something that seems very difficult to debug. When I had another problem with videos not being mirrored (see [issue 3636](https://github.com/Chocobozzz/PeerTube/issues/3636)), I suggested an admin feature to show an explanation for each missing video why it isn't mirrored (each single upstream video that's not mirrored is a problem). Maybe such a feature might be helpful in this situation as well.

I tried to uncheck "Redundancy allowed" and select it again but it triggered several of these:
```
    "stack": "TypeError: Cannot read property 'Video' of null\n    at VideoRedundancyModel.getVideo (peertube-develop/dist/server/models/redundancy/video-redundancy.js:524:41)\n    at Object.<anonymous> (peertube-develop/dist/server/lib/activitypub/send/send-undo.js:59:49)\n    at Generator.next (<anonymous>)\n    at peertube-develop/node_modules/tslib/tslib.js:114:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (peertube-develop/node_modules/tslib/tslib.js:110:16)\n    at Object.sendUndoCacheFile (peertube-develop/dist/server/lib/activitypub/send/send-undo.js:57:20)\n    at peertube-develop/dist/server/lib/redundancy.js:15:26\n    at Generator.next (<anonymous>)\n    at fulfilled (peertube-develop/node_modules/tslib/tslib.js:111:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
    "message": "Cannot read property 'Video' of null"

```

* PeerTube instance:
  * version: 3.0.1 (29f148a61381727a432c22a71c7a2b7cc23d9c9e)
  * NodeJS version: v12.19.0
  * Ffmpeg version: 4.3.1

**Comment by Chocobozzz** [comment]
Hello,

Thank for this issue. It should already be fixed in 3.1 (still in RC at this moment)

**Comment by c0xc** [comment]
Thanks for your work, I understand the "null" error has been fixed. But what about the mirror instance disappearing from the followers list? Has that been fixed too or is that a feature that can be disabled?
Some users and maintainers expect every single video on the origin instance to be served from the mirror instance as well but this mechanism isn't working again, this time for new videos, and it's unclear why.

**Comment by Chocobozzz** [comment]
> It seems like it may have happened after the mirror instance was offline due to maintenance work for a couple of hours,

PeerTube should not remove followers if they are down only for a couple of hours. You could try to search for this log occurrence https://github.com/Chocobozzz/PeerTube/blob/b49f22d8f9a52ab75fd38db2d377249eb58fa678/server/models/activitypub/actor-follow.ts#L163

In 3.1-rc we also fixed some redundancy bugs

**Comment by c0xc** [comment]
Unfortuntely, I can't check the upstream instance's log on short notice. When possible, I'll look for this error and if I find it, I would take it to mean that the mirror instance was kicked out of the followers list after being offline for too long. That would make sense but I think the mirror instance should have a way to detect that it's in fact not following anymore when it comes back online. Like a daily check "hello upstream, this is mirror1, I am following you, can you confirm that you are being followed by me".

Also, since this is apparently preventing the mirror instance from duplicating new videos, I'd still say something like a redundancy overview in the mirror instances' admin view might be useful (like I've suggested in [3636](https://github.com/Chocobozzz/PeerTube/issues/3636)), or maybe a diagram that shows the number and percentage of upstream videos that are not yet mirrored.

**Comment by Chocobozzz** [comment]
> in fact not following anymore when it comes back online

It's a good idea. Please create a separate issue

**Comment by c0xc** [comment]
Should I wait a couple of days before manually removing the follow link and recreating it, maybe to test something on this instance that still thinks it's following while the upstream instance doesn't think so?
