### ISSUE TITLE
Would a second mirror instance find and recognize previously duplicated videos on shared storage?

### ISSUE THREAD

**Issue by c0xc** [Chocobozzz/PeerTube#3848]
If two or more mirror instances, each on a separate vm, share the same file based storage for the redundancy directory (for example, 20 TB in size) and the first mirror instance has already duplicated video x, will the other instance find and recognize that video x and automatically serve it (as a third peer)? Or will the other instance try to duplicate the video again and overwrite the file on the shared storage (and the other way around, will it delete the file used by the first instance if the redundancy fails or is disabled temporarily on the second instance)?

And if previously duplicated files are recognized: How about an option to make Peertube treat the redundancy directory as read-only, so that there's only one Peertube instance which updates this directory and the other instances just read from it and serve the files?

**Comment by Chocobozzz** [comment]
> If two or more mirror instances, each on a separate vm, share the same file based storage for the redundancy directory (for example, 20 TB in size) and the first mirror instance has already duplicated video x, will the other instance find and recognize that video x and automatically serve it (as a third peer)

No, sharing a directory is not supported by peertube so you must not use the same directory for 2 different instances. Sharing a directory could result in a unexpected behaviour (overwrites, deletions etc)

> And if previously duplicated files are recognized: How about an option to make Peertube treat the redundancy directory as read-only, so that there's only one Peertube instance which updates this directory and the other instances just read from it and serve the files?

It's out of the scope of PeerTube. Just use multiple proxies that serve the same directory .
