### ISSUE TITLE
It's possible to cleanup a specific resolution of published videos?

### ISSUE THREAD

**Issue by lucacalcaterra** [Chocobozzz/PeerTube#3853]
I would to remove specific resolution (1080p) od older video , mantain 720p (for save space) . There's a procedure to do this ? I suppose i must do it in manual mode, but how is the correct way ? Thanks!

**Comment by Chocobozzz** [comment]
Hello

No sorry it's not possible yet. See https://github.com/Chocobozzz/PeerTube/issues/2658
