### ISSUE TITLE
Regenerate thumbnails

### ISSUE THREAD

**Issue by TROMsite** [Chocobozzz/PeerTube#3855]
**Describe the problem to be solved**
Add the ability to auto regenerate the thumbnails. 

**Describe the solution you would like:**
Like on all major video platforms, you can either choose between multiple thumbnails, or click a button to regenerate and create new ones.

**Comment by Chocobozzz** [comment]
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1322
