### ISSUE TITLE
Limit available resolutions per user or channel

### ISSUE THREAD

**Issue by c0xc** [Chocobozzz/PeerTube#3858]
**Describe the problem to be solved**

Full HD videos require lots of bandwidth, i.e., with higher quality videos the number of concurrent viewers is much lower, so the point at which users begin to experience playback issues is reached earlier. Assuming a server could serve 30 viewers all watching a 1080p video and if there are 9 mirror instances, that would make 300 viewers. The same instance could probably serve more than 600 viewers watching 480p videos which is still sufficient for most videos, but:

Suppose a setup with moderator who upload high quality content as well as users who may upload additional content, which isn't reviewed and maybe not that important. Now, all videos that are uploaded by a moderator should be transcoded (if necessary) and stored in full hd quality. However, videos uploaded by most users should be limited to use minimal storage space, definitely not full hd.

**Describe the solution you would like:**

Maybe allow import profiles to be defined, the default profile being applied to all users unless otherwise specified and that one could be set to a maximum of 360 as required. Then some sort of full hd profile could be created which would only be applied to those users who have it configured by an instance admin.

Furthermore, it would also be useful if moderators or at least admins could re-encode existing videos to remove the highest quality, for example after reducing the maximum resolution in the default profile from 480 to 360.

**Describe alternatives you have considered**

**Comment by Alterak** [comment]
As far as I know, the possibility of different profiles is already being developed ...

**Comment by bkil** [comment]
Maybe related: #3856, #2442

**Comment by Chocobozzz** [comment]
Hello,

I added `filter:transcoding.auto.lower-resolutions-to-transcode.result` and `filter:transcoding.auto.lower-resolutions-to-transcode.result` hooks in https://github.com/Chocobozzz/PeerTube/commit/ebb9e53ada156249ed8e8cfd1de74097d3eb49d7 so you can adapt resolutions you want to build.
