### ISSUE TITLE
Consider switching to more sophisticated l10n library/framework

### ISSUE THREAD

**Issue by mikhirev** [Chocobozzz/PeerTube#3862]
**Describe the problem to be solved**

There are many languages that have several [plural forms](https://github.com/translate/l10n-guide/blob/master/docs/l10n/pluralforms.rst). Angular [does not support](https://github.com/angular/angular/issues/35912) l10n for such languages in convenient way that makes localized interface ungrammatical and hard to read.

**Describe the solution you would like:**

Please consider adoption of some translation library or framework that properly handles different plural forms.

**Comment by Chocobozzz** [comment]
I think you only refer to strings localized in components using `$localize`, that do not support plural form (whereas strings in HTML do). We could check workarounds, but switching to another l10n framework is not an option.

**Comment by mikhirev** [comment]
> I think you only refer to strings localized in components using `$localize`

Yes, particularly publication times like "* hours ago", "* days ago" etc. [here](https://github.com/Chocobozzz/PeerTube/blob/4166caabc6f439a7db7d1e15d64f74b8b694fc6b/client/src/app/shared/shared-main/angular/from-now.pipe.ts#L11-L32). I'm afraid that possible workarounds are unconvenient for translators. Something like `ngettext()` would be the best, but I'm not a web developer and can't suggest any solution.

**Comment by rigelk** [comment]
@mikhirev are publication times the only place that comes to mind? If not, could you realistically list them here, to assess the situation?

**Comment by mikhirev** [comment]
Sorry, I'm unable to list all such places, but I guess there are several of them. There is at least one even more weird place [here](https://github.com/Chocobozzz/PeerTube/blob/4e239e3554ba7162c03e939f54133933527a1b74/client/src/app/shared/shared-instance/instance-features-table.component.ts#L59-L70) — it is unlocalizeable as it is implemented now, while it would be easily handled with something similar to `ngettext`.

**Comment by mikhirev** [comment]
Some more examples:
https://github.com/Chocobozzz/PeerTube/blob/07f81d9deedf4921b8518c2d2b16043167b4c5d5/client/src/app/%2Bvideo-channels/video-channel-videos/video-channel-videos.component.ts#L88-L90
https://github.com/Chocobozzz/PeerTube/blob/07f81d9deedf4921b8518c2d2b16043167b4c5d5/client/src/app/%2Baccounts/account-search/account-search.component.ts#L88-L90
https://github.com/Chocobozzz/PeerTube/blob/e6ccdce2ea7d2a64d0bdba69f9013b6c16e5d3bf/client/src/app/shared/shared-main/video/video.model.ts#L210-L214
And [here](https://github.com/Chocobozzz/PeerTube/blob/4f926722ea6784ea389013378fd233f59077ec8a/client/src/app/%2Badmin/follows/following-list/following-list.component.ts#L47) the same string is used for single/plural, that looks unpleasant in English and also hard to translate to some languages.

**Comment by Chocobozzz** [comment]
Hi,

I added ICU support in TS components in https://github.com/Chocobozzz/PeerTube/commit/eaa529528cafcfb291009f9f99d296c81e792899 and updated weblate

The [library we use](https://formatjs.io/docs/intl-messageformat/) requires some [Intl components](https://formatjs.io/docs/intl-messageformat/#modern-intl-dependency) that old web browsers may not have (like iOS 11 and [Intl.PluralRules](https://caniuse.com/intl-pluralrules) for example). To avoid adding intl polyfills to main bundle, I decided to use fallback strings if Intl is not available. It's the reason why we still have strings like `{x} comment(s) deleted.`.
