### ISSUE TITLE
Is an overloaded mirror quickly removed from the list of peers?

### ISSUE THREAD

**Issue by c0xc** [Chocobozzz/PeerTube#3865]
Suppose there are a bunch mirror instances on slow servers with a 100 mbit/s link but just one or two mirrors with gigabit links and one of the slow mirror instances is already streaming a video to, say, 30 viewers, using up all available bandwidth. The fast gigabit mirrors still have lots of unused bandwidth though. Is there a mechanism in the player that would ensure that it removes the slow mirror from the list of peers for all new viewers, so that they can smoothly stream the video from the remaining mirrors, ideally from the fast mirrors primarily?

Reason for asking isn't just about how to scale but also a pattern I've noticed several times when at least one mirror had issues (not necessarily bandwidth related, but requests failed or timed out). Sometimes, that seemed to cause a significant delay before the video started, almost a minute, maybe more.

**Comment by Chocobozzz** [comment]
Hi,

> Is an overloaded mirror quickly removed from the list of peers?

Unfortunately no.

See https://github.com/Chocobozzz/PeerTube/issues/2047 for more information

**Comment by c0xc** [comment]
Are you saying a single follower / mirror instance that's slow could effectively prevent playback for almost all viewers? And how should a large instance be scaled up for more viewers than those few dozens that can be served by a single instance? It almost sounds like it breaks the whole concept of having multiple mirror instances.

I'm looking at that bug report but based on those comments, I'm still not sure how this is currently meant to work, all I'm reading is that some users seem to have experienced playback issues and there's been an improvement but is there any concept or explanation on how adding mirror instances should increase the number of simultaneous viewers?

**Comment by Chocobozzz** [comment]
> Are you saying a single follower / mirror instance that's slow could effectively prevent playback for almost all viewers?

Yes and no. Yes because it could slow down the video for users that download a segment from this specific instance (so `1/(n + 1)` probability, where `n` is the amount of instances that mirrored the video). It's the reason why we have this setting: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L147

See https://docs.joinpeertube.org/admin-following-instances?id=instances-redundancy for a redundancy introduction

**Comment by c0xc** [comment]
I am aware of this setting and it's already been set to "following" in some setups but even then, it doesn't matter. If 10 mirror instances are created that all follow the origin instance and all follow requests from partner instances are declined, what if there are already so many viewers that the first of those mirror instances can't handle more connections? If this mirror isn't temporarily removed, it will be used by additional clients at some point, even if the selection is random. Or what if 9 out of 10 mirrors are at their limit and there are new viewers, then there's a 90% risk that the video won't play for them? It sounds like a fundamental problem and I don't see how either that setting or the part of the documentation linked above addresses this problem.
