### ISSUE TITLE
Resume video for non-logged in users

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3866]
**Describe the problem to be solved**
As discussed in #660 it's a nice feature to be able to resume a video previously started. On mobile phones it can be especially convenient since it's more common with a bad internet connection or other disturbance. The problem is that this is only working for logged in users. I'm not sure about how the user behavior look like, but personally I'm not often logged in to sites on my mobile device.

**Describe the solution you would like:**
As non-logged in user I'd like the videos to be resumed when I revisit/reload the watch page.

**Describe alternatives you have considered**  
Store the current duration in local storage. The question is how to handle the duration when a non-logged in user logs in and there's already a duration stored at the server side? The easiest may be to just remove the duration from local storage upon login.

**Comment by AnonymousWebHacker** [comment]
I think this is something you should keep in mind.   https://github.com/Chocobozzz/PeerTube/issues/3889
