### ISSUE TITLE
Unknown error upon uploading large videos

### ISSUE THREAD

**Issue by angus6b23** [Chocobozzz/PeerTube#3868]
**Describe the current behavior**
When finishing upload of large videos, the status bar will show "unknown error" after processing for a short period of time. The video is neither listed or transcoded.
I have noticed similar issues reported, but seems there is no solution at current time. Please feel free to request logging if required.

**Steps to reproduce:**

1. Uploading Large video via web or cli (E.g. 3gb)
2. Upload finished and status bar show processing
3. Received unknown error and video is not listed 

**Describe the expected behavior**
Proper handling of large video files

**Additional information**

* PeerTube instance:
  * URL: Private instance
  * version: v3.0.1
  * NodeJS version: v10.24.0
  * Ffmpeg version: v4.1.6

* Browser name, version and platforms on which you could reproduce the bug:
Client: Firefox Developer Edition 87.0b9
Server: Debian 

* Link to browser console log if relevant:
Error log of web browser and cli tools: https://pastebin.com/nhMyVgKG

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
Nginx Access log and peertube server log: https://pastebin.com/WTXHcxwN
No logging on nginx error log 

* Link to nginx conf:
https://pastebin.com/pvPkpaYg

**Comment by Chocobozzz** [comment]
Hello,

3.1 (not released yet) should fix this issue now we generate the torrent in an async way
