### ISSUE TITLE
Public automatic new videos  on Mastodon

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#3873]
I would be interested to know if you can link the peertube with an instance of mastodon, in such a way that every time a video is published on peertube, it will automatically be published on Mastodon.

**Comment by Chocobozzz** [comment]
Hello,

Yes: if an account on the mastodon instance follows your peertube instance or a specific account/channel then peertube will send activity pub messages to your mastodon instance, that will automatically display the video in the feed.

**Comment by AnonymousWebHacker** [comment]
@Chocobozzz Hi men
Did not understand my question.
I understand that a user can subscribe to a channel or a peertube account, and this happens
I mean to subscribe, but to the total instance of peertube. Any video that gets posted, that goes straight to Mastodon

If this is not created with pleasure I can add it to the attachments

**Comment by Chocobozzz** [comment]
You can subscribe to the instance actor that `Announce` (share) videos uploaded on it: `peertube@cpy.re` for example.

**Comment by AnonymousWebHacker** [comment]
> You can subscribe to the instance actor that `Announce` (share) videos uploaded on it: `peertube@peertube.cpy.re` for example.

In that example you gave me [peertube@peertube.cpy.re], only the user's videos will be uploaded, but not all other users who upload videos

**Comment by Chocobozzz** [comment]
The `peertube` account is a special account representing the PeerTube instance.

See `curl -v -H 'Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"' 'https://peertube2.cpy.re/accounts/peertube/outbox?page=1' | jq`

**Comment by AnonymousWebHacker** [comment]
Just search the Mastodon for the default account @peertube@peertube.domain and it appears. Until now everything is perfect. Thanks a lot.
