### ISSUE TITLE
Filter search hook not always registered before search result is presented

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3876]
**Describe the current behavior**
We're using [this plugin](https://framagit.org/kontrollanten/peertube-plugin-hide-channels-in-search-result/-/blob/master/client/common-client-plugin.js) to hide channels for the search results. Around 5-10% of the page loads shows the channel results though.

**Steps to reproduce:**

1. Load https://swebbtv.se/search?search=Anita&searchTarget=local 10-20 times and you should be able to see the channel results.

**Describe the expected behavior**

* PeerTube instance:
  * version: [3.2.2-c](https://github.com/kontrollanten/PeerTube/releases/tag/v3.2.2-c)

* Browser name, version and platforms on which you could reproduce the bug: Brave 1.13.86 Chromium: 85.0.4183.102 (Official Build) (64-bit)

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I can't reproduce. Please try to add debug logs in the plugin to see what happens

**Comment by kontrollanten** [comment]
I added a breakpoint to the hook register. The register function is ran after the search results are presented.

![image](https://user-images.githubusercontent.com/6680299/111972357-ab495180-8afd-11eb-9aff-c1cab804889a.png)

**Comment by Chocobozzz** [comment]
You must set `search` in the plugin scope: https://framagit.org/kontrollanten/peertube-plugin-hide-channels-in-search-result/-/blob/master/package.json#L11
