### ISSUE TITLE
"Unknown" Licence should be "Copyright Unknown" by default

### ISSUE THREAD

**Issue by samir-s** [Chocobozzz/PeerTube#3879]
When a user does not set the licence of a video, the interface list this licence as "unknown". Such a licence does not have legal existence : most countries set by default a not specified "unknown" licenced original work as a "copyright" licence by the author, even if he or she is unknown.

Even if the video is finally found as a creative commons licence after some licence-checking, it seems wise to set it as "(c) Unknown" as first, to prevent any abuse of the author rights. Notice that even CC licence are at first copyrighted by the author, then released in CC under the rights of the author. 

And to be totally clear, the licences shouldn't by listed as "Attribution - Share Alike", etc. but "(c) Chocobuzz - Attribution - Share Alike", etc. The advantage of this new naming schema is that it allows a more clear attribution when remixing the work and we must know who has copyrighted the work in case of legal issue that might occurs with CC licences.

**Comment by rigelk** [comment]
hi @samir-s,

"Copyright Unknown" would mean that we don't know whose video this belongs to, which is nevere the case: it is always implied by reference to the account publishing the video (unless stated otherwise in the description). However, the video might not grant rights to viewers through a licence, hence the "Licence: Unknown" and not "Licence: Copyright Unknown".

**Comment by samir-s** [comment]
Assuming that the account publishing the content holds by default the copyright of the content is just an hypothesis, and seems to me insecure in a legal point of view. When a video is published in peertube, it seems to me more legally secure to clearly state who owns the copyright, instead of implying it : it's clearly easy to upload a video you don't own as a copyright holder. See for instance in wordpress, the author of an article is clearly stated. 

Creative Commons Licenses are built on copyright, it seems clearly weird to not have an author/copyright field, and to have to use the "Description" field for such critical information. You cannot use a CC BY if you don't know who owns the copyright (BY), since you're not able to attribute the work to the author: the copyright field should be mandatory when using a CC BY and variations.

**Comment by rigelk** [comment]
Then you want to open an issue regarding the addition of a copyright field, not rephrase the licence field.
