### ISSUE TITLE
Cannot fetch remote information of this URL.

### ISSUE THREAD

**Issue by sunknudsen** [Chocobozzz/PeerTube#3882]
**Describe the current behavior**

When I import video using [tube-manager](https://github.com/sunknudsen/tube-manager), the following is returned by the PeerTube API.

**POST https://peertube.sunknudsen.com/api/v1/videos/imports**

```json
{
  "statusCode": 400,
  "body": {
    "error": "Cannot fetch remote information of this URL."
  }
}
```

I also tried importing video using https://peertube.sunknudsen.com/videos/upload, same error.

I believe the following confirms YouTube is not blocking my server.

```console
$ youtube-dl --format "bestvideo[ext=mp4][height<=1080]+bestaudio[ext=m4a]/best[ext=mp4]/best" "https://www.youtube.com/watch?v=1bk8YFsgVms"
[youtube] 1bk8YFsgVms: Downloading webpage
[download] Destination: The hustle-1bk8YFsgVms.f137.mp4
[download] 100% of 62.05MiB in 00:09
[download] Destination: The hustle-1bk8YFsgVms.f140.m4a
[download] 100% of 9.38MiB in 00:01
[ffmpeg] Merging formats into "The hustle-1bk8YFsgVms.mp4"
Deleting original file The hustle-1bk8YFsgVms.f137.mp4 (pass -k to keep)
Deleting original file The hustle-1bk8YFsgVms.f140.m4a (pass -k to keep)
```

**Steps to reproduce:**

1. Import https://www.youtube.com/watch?v=1bk8YFsgVms on https://peertube.sunknudsen.com.

**Describe the expected behavior**

I never experienced this issue before and nothing has changed on the PeerTube instance (except for strange [issue](https://github.com/Chocobozzz/PeerTube/issues/3875) I reported earlier).

**Additional information**

* PeerTube instance:
  * URL: https://peertube.sunknudsen.com
  * version: 3.0.1
  * NodeJS version: v12.20.2
  * Ffmpeg version: 4.1.6-1~deb10u1

**Comment by sunknudsen** [comment]
Btw, I was able to upload videos today for no apparent reason... puzzled.

**Comment by Chocobozzz** [comment]
Hello,

Do you still have this issue? Could be a temporary bug on youtube-dl

**Comment by tio-trom** [comment]
Same here with youtube. https://videos.trom.tf is my instance. Cannot import any video. Peertube version 3.3.0 - worked with the previous version tho.
