### ISSUE TITLE
VideoChannel List is returning empty channels in API

### ISSUE THREAD

**Issue by cclloyd** [Chocobozzz/PeerTube#3884]
**Describe the current behavior**

**Steps to reproduce:**

1. Use the Python API for Peertube
2. Call [accounts_name_video_channels_get](https://framagit.org/framasoft/peertube/clients/python/-/blob/master/docs/VideoChannelsApi.md#accounts_name_video_channels_get)
3. Print output

**Describe the expected behavior**

When calling `accounts_name_video_channels_get`, it should return `list[VideoChannel]`.  It does, but the objects all have `None` as their attributes, as below

    [{'description': None,
     'display_name': None,
     'is_local': None,
     'owner_account': None},
     {'description': None,
     'display_name': None,
     'is_local': None,
     'owner_account': None}]

Yet when I just browse to the channel in Chrome, it shows the proper information https://gameclips.app/api/v1/accounts/cclloyd/video-channels

**Additional information**

* PeerTube instance:
  * URL: https://gameclips.app
  * version: 3.0.1

**Comment by rigelk** [comment]
hi @cclloyd,

The Python API library is automatically generated via the OpenAPI spec and https://openapi-generator.tech/, using their generator (org.openapitools.codegen.languages.PythonClientCodegen). There is little we can do beyond changing the OpenAPI spec ; could you spot an error in it that leads to this error?

**Comment by Chocobozzz** [comment]
Thanks, I fixed the documentation in https://github.com/Chocobozzz/PeerTube/commit/8004469c0a14f8b19f91f87a9455713422146baa
