### ISSUE TITLE
Video format .vob not allowed as additional extension

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#3887]
I don't know if it's intentional by part of the peertube team, so I didn't put it as a "Feature Request".

![Screenshot from 2021-03-25 01-29-33](https://user-images.githubusercontent.com/43164089/112425053-cee1e700-8d0b-11eb-947d-312a849c1e4d.png)

In the list of allowed videos, there is no * .vob format
So it gave a [server error] to a user of my instance when uploading it.

Solution: he had to convert the video to mp4

**Comment by rigelk** [comment]
When I added that last bach of extensions, I simply didn't have time or easy access to test it at the time ; could you provide a `.vob` here so that it can be tested against?

**Comment by AnonymousWebHacker** [comment]
@rigelk http://musicvob.net/E/elton_john/111793/

**Comment by rigelk** [comment]
@AnonymousWebHacker please, only open-licensed or royalty free content can be linked here.

**Comment by AnonymousWebHacker** [comment]
> please, only open-licensed or royalty free content can be linked here.

https://www.xnxx.com/video-3zyvc0d/vts_01_1.vob
Sorry, it's the only thing that came up googling videos filetype: vob : )
I'm sorry I can't upload one, I don't have a network speed for that

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/0c12054ae3c71b59b70cdd26fa68eea404a7daaa
