### ISSUE TITLE
Vsualization option in administration

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#3889]
I was looking at this issuse https://github.com/Chocobozzz/PeerTube/issues/3866  and in short, he asks non-logged-in users to resume playback. 

However, I agree with others that there should be a possibility to reproduce the videos only to registered users in the instance or some other instance that requests the video

* Possible solution
Add in the administration whether or not to allow the view of videos by registered users or not.

In case this is implemented, the videos would be viewed only by:
- A user registered in the instance
- B (some other instance that asks for the video)

* Reason
I do not think it is fair for content creators, who have 1k visits, and not a single like, because they can see it, without just registering, and they need to register to leave their like.

This option would only leave the admission available to allow unregistered users to view videos or not, or else, it would only leave the registered users, or some other instance of fediverso :D

**Comment by kontrollanten** [comment]
Hi @AnonymousWebHacker ! I understand your case and I think it's good to think about creating/keeping incentives for users to get registered. But it's also important to give all users (even non-logged ins) a good user experience so that they like the service. If they like the service and think it's good way watching videos I think there's a better chance that they decide to register to be able to subscribe, comment or like.

**Comment by rigelk** [comment]
>     * I do not think it is fair for content creators, who have 1k visits, and not a single like, because they can see it, without just registering, and they need to register to leave their like.

To me this sounds like gamification of our UX just for the sake of more likes ; I get the incentive but:
- not all instances allow registration
- some users have short usage timespans without accounts, but may come back on thematic instances where history keeping could prove useful
- likes are not a sound popularity metric when instances vary so much in scale and audience (neither are views!)
- likes are not important enough to justify degrading the UX (if any such thing exists in the first place) - see previous point
- views are already increased by the action of watching the video, even a second time when resuming

Incentivizing registration should be done by other means than UX degradation IMHO, but enabling/disabling features for specific user types (registered/unregistered/else) could be a feature request, provided there is a better justification.

**Comment by AnonymousWebHacker** [comment]
@rigelk 
> * not all instances allow registration

There are instances that do not allow registrations, others do; the same may be the [see without registration or not] would be something depending on the administrator of the instance


> * some users have short usage timespans without accounts, but may come back on thematic instances where history keeping could prove useful

Unfortunately, what gives life to strems like Youtube or Peertube, are the same users.
Peertube does not have any monetization system so far (I have nothing against it), but I do not agree with you, because if I were a content creditor, something that would motivate me would be followers, views and likes of my videos (although I do not charge anything for this).
How else do you stimulate your content creators?

> Incentivizing registration should be done by other means than UX degradation IMHO, but enabling/disabling features for specific user types (registered/unregistered/else) could be a feature request, provided there is a better justification.

What better justification do you want than;
- motivation of content creators
- If an instance has a speed limit (I prefer that registered users consume it, than other instances that follow me than non-registered users)
Consumption of (hardware, CPU, RAM, nginx, bandwidth ... etc)

@Chocobozzz I would like to know your personal opinion of this
