### ISSUE TITLE
Automatic bandwidth downgrade

### ISSUE THREAD

**Issue by Glandos** [Chocobozzz/PeerTube#389]
* **PeerTube version or URL:**
1.0.0-beta
* **Browser name/version:**
Firefox 59
* **NodeJS version:**
N/A

* **What is the expected behaviour?**
When playing a video (e.g. https://peertube.datagueule.tv/videos/watch/a69fc60b-248b-49f2-9e69-48561268ca68), the maximum resolution available is selected (in this case 1080p).
However, my bandwidth cannot handle it, so it should downgrade to 720p, or even a lower resolution.
* **What do you see instead?**
The player keeps 1080p resolution, and the video is buffering every 2 seconds.

I know that the origin of the lack of bandwidth is very difficult to detect, because if it comes from the servers, then new peers can improve the quality. However, I guess that if new peers come into the client list, the automatic computation can be replayed.

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/a8462c8e3a61f4f7314fe18c0c10cc2946c254d1

It's quite experimental so feedbacks welcome :)
