### ISSUE TITLE
Optimize views federation

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3892]
**Describe the problem to be solved**
Each time Video Update events to the federated instances a lot of CPU is used at the sending instances. This is blocking us from updating the video views more often (#3548).

![image](https://user-images.githubusercontent.com/6680299/112643310-85e17e00-8e44-11eb-821c-7c9d8c4909bc.png)

**Describe the solution you would like:**
Make it possible to update the views count multiple times per hour.

@Chocobozzz Please correct me if I'm wrong and provide more information if you have. I'd be really happy to solve this.

**Comment by Chocobozzz** [comment]
I think I fixed this issue in 3.2: we try to not process remote thumbnails if this is not needed (filename did not change or the thumbnail has the appropriate size).

**Comment by toon462** [comment]
ในวันที่ พ. 12 พ.ค. 2021 15:15 น. Chocobozzz ***@***.***>
เขียนว่า:
