### ISSUE TITLE
After upgrade v3.0.1 to v3.1.0 : Peertube don't start with error SequelizeUniqueConstraintError

### ISSUE THREAD

**Issue by papaeng** [Chocobozzz/PeerTube#3893]
HI,
When i start Peertube, error appear :

mars 27 01:50:31 peertube peertube[20048]: [xxx.xxx.xxx:443] 2021-03-27 01:50:31.486 info: Database xxx is ready.
mars 27 01:50:32 peertube peertube[20048]: [xxx.xxx.xxx:443] 2021-03-27 01:50:32.268 error: Cannot install application. {
mars 27 01:50:32 peertube peertube[20048]:   "err": {
mars 27 01:50:32 peertube peertube[20048]:     "stack": "SequelizeUniqueConstraintError: Validation error\n    at Query.formatError (/var/www/peertube/versions/peertube-v3.1.0/node_modules/sequelize/lib/dialects/postgres/query.js:344:18)\n    at Query.run (/var/www/peertube/versions/peertube-v3.1.0/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)\n    at processTicksAndRejections (node:internal/process/task_queues:94:5)\n    at async /var/www/peertube/versions/peertube-v3.1.0/node_modules/sequelize/lib/sequelize.js:619:16\n    at async PostgresQueryInterface.addIndex (/var/www/peertube/versions/peertube-v3.1.0/node_modules/sequelize/lib/dialects/abstract/query-interface.js:541:12)\n    at async Function.sync (/var/www/peertube/versions/peertube-v3.1.0/node_modules/sequelize/lib/model.js:1367:7)\n    at async Sequelize.sync (/var/www/peertube/versions/peertube-v3.1.0/node_modules/sequelize/lib/sequelize.js:793:35)\n    at async Promise.all (index 0)",
mars 27 01:50:32 peertube peertube[20048]:     "message": "Validation error",
mars 27 01:50:32 peertube peertube[20048]:     "name": "SequelizeUniqueConstraintError",
mars 27 01:50:32 peertube peertube[20048]:     "errors": [
mars 27 01:50:32 peertube peertube[20048]:       {
mars 27 01:50:32 peertube peertube[20048]:         "message": "filename must be unique",
mars 27 01:50:32 peertube peertube[20048]:         "type": "unique violation",
mars 27 01:50:32 peertube peertube[20048]:         "path": "filename",
mars 27 01:50:32 peertube peertube[20048]:         "value": "cebfcfec-5611-4b2b-94fd-bd2e297abab5-fr.vtt",
mars 27 01:50:32 peertube peertube[20048]:         "origin": "DB",
mars 27 01:50:32 peertube peertube[20048]:         "instance": null,
mars 27 01:50:32 peertube peertube[20048]:         "validatorKey": "not_unique",
mars 27 01:50:32 peertube peertube[20048]:         "validatorName": null,
mars 27 01:50:32 peertube peertube[20048]:         "validatorArgs": []
mars 27 01:50:32 peertube peertube[20048]:       }
mars 27 01:50:32 peertube peertube[20048]:     ],
mars 27 01:50:32 peertube peertube[20048]:     "fields": {
mars 27 01:50:32 peertube peertube[20048]:       "filename": "cebfcfec-5611-4b2b-94fd-bd2e297abab5-fr.vtt"
mars 27 01:50:32 peertube peertube[20048]:     },
mars 27 01:50:32 peertube peertube[20048]:     "parent": {
mars 27 01:50:32 peertube peertube[20048]:       "stack": "error: could not create unique index \"video_caption_filename\"\n    at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v3.1.0/node_modules/pg-protocol/dist/parser.js:278:15)\n    at Parser.handlePacket (/var/www/peertube/versions/peertube-v3.1.0/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/www/peertube/versions/peertube-v3.1.0/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v3.1.0/node_modules/pg-protocol/dist/index.js:10:42)\n    at Socket.emit (node:events:369:20)\n    at addChunk (node:internal/streams/readable:313:12)\n    at readableAddChunk (node:internal/streams/readable:288:9)\n    at Socket.Readable.push (node:internal/streams/readable:227:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
mars 27 01:50:32 peertube peertube[20048]:       "message": "could not create unique index \"video_caption_filename\"",
mars 27 01:50:32 peertube peertube[20048]:       "length": 248,
mars 27 01:50:32 peertube peertube[20048]:       "name": "error",
mars 27 01:50:32 peertube peertube[20048]:       "severity": "ERROR",
mars 27 01:50:32 peertube peertube[20048]:       "code": "23505",
mars 27 01:50:32 peertube peertube[20048]:       "detail": "Key (filename)=(cebfcfec-5611-4b2b-94fd-bd2e297abab5-fr.vtt) is duplicated.",
mars 27 01:50:32 peertube peertube[20048]:       "schema": "public",
mars 27 01:50:32 peertube peertube[20048]:       "table": "videoCaption",
mars 27 01:50:32 peertube peertube[20048]:       "constraint": "video_caption_filename",
mars 27 01:50:32 peertube peertube[20048]:       "file": "tuplesort.c",
mars 27 01:50:32 peertube peertube[20048]:       "line": "4049",
mars 27 01:50:32 peertube peertube[20048]:       "routine": "comparetup_index_btree",
mars 27 01:50:32 peertube peertube[20048]:       "sql": "CREATE UNIQUE INDEX \"video_caption_filename\" ON \"videoCaption\" (\"filename\")"
mars 27 01:50:32 peertube peertube[20048]:     },
mars 27 01:50:32 peertube peertube[20048]:     "sql": "CREATE UNIQUE INDEX \"video_caption_filename\" ON \"videoCaption\" (\"filename\")"
mars 27 01:50:32 peertube peertube[20048]:   }
mars 27 01:50:32 peertube peertube[20048]: }
mars 27 01:50:32 peertube systemd[1]: peertube.service: Main process exited, code=exited, status=255/EXCEPTION
mars 27 01:50:32 peertube systemd[1]: peertube.service: Failed with result 'exit-code'.

Thanks for reply

**Comment by papaeng** [comment]
It's ok with restore backup and delete UNIQUE KEY in tables : 

- videoCaption
- tag
- actor

**Comment by pokapow** [comment]
I have same problem, could you please help to use the good SQL request to remove the UNIQUE KEY ?

```
2021-04-07 14:15:22.786 error: Cannot install application. {
  "err": {
    "stack": "SequelizeUniqueConstraintError: Validation error\n    at Query.formatError (/var/www/peertube/versions/peertube-v3.1.0/node_modules/sequelize/lib/dialects/postgres/query.js:344:18)\n    at Query.run (/var/www/peertube/versions/peertube-v3.1.0/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)\n    at processTicksAndRejections (node:internal/process/task_queues:94:5)\n    at async /var/www/peertube/versions/peertube-v3.1.0/node_modules/sequelize/lib/sequelize.js:619:16\n    at async PostgresQueryInterface.addIndex (/var/www/peertube/versions/peertube-v3.1.0/node_modules/sequelize/lib/dialects/abstract/query-interface.js:541:12)\n    at async Function.sync (/var/www/peertube/versions/peertube-v3.1.0/node_modules/sequelize/lib/model.js:1367:7)\n    at async Sequelize.sync (/var/www/peertube/versions/peertube-v3.1.0/node_modules/sequelize/lib/sequelize.js:793:35)\n    at async Promise.all (index 0)",
    "message": "Validation error",
    "name": "SequelizeUniqueConstraintError",
    "errors": [
      {
        "message": "filename must be unique",
        "type": "unique violation",
        "path": "filename",
        "value": "cebfcfec-5611-4b2b-94fd-bd2e297abab5-fr.vtt",
        "origin": "DB",
        "instance": null,
        "validatorKey": "not_unique",
        "validatorName": null,
        "validatorArgs": []
      }
    ],
    "fields": {
      "filename": "cebfcfec-5611-4b2b-94fd-bd2e297abab5-fr.vtt"
    },
    "parent": {
      "stack": "error: could not create unique index \"video_caption_filename\"\n    at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v3.1.0/node_modules/pg-protocol/dist/parser.js:278:15)\n    at Parser.handlePacket (/var/www/peertube/versions/peertube-v3.1.0/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/www/peertube/versions/peertube-v3.1.0/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v3.1.0/node_modules/pg-protocol/dist/index.js:10:42)\n    at Socket.emit (node:events:369:20)\n    at addChunk (node:internal/streams/readable:313:12)\n    at readableAddChunk (node:internal/streams/readable:288:9)\n    at Socket.Readable.push (node:internal/streams/readable:227:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
      "message": "could not create unique index \"video_caption_filename\"",
      "length": 248,
      "name": "error",
      "severity": "ERROR",
      "code": "23505",
      "detail": "Key (filename)=(cebfcfec-5611-4b2b-94fd-bd2e297abab5-fr.vtt) is duplicated.",
      "schema": "public",
      "table": "videoCaption",
      "constraint": "video_caption_filename",
      "file": "tuplesort.c",
      "line": "4056",
      "routine": "comparetup_index_btree",
      "sql": "CREATE UNIQUE INDEX \"video_caption_filename\" ON \"videoCaption\" (\"filename\")"
    },
    "sql": "CREATE UNIQUE INDEX \"video_caption_filename\" ON \"videoCaption\" (\"filename\")"
  }
}
```

**Comment by Chocobozzz** [comment]
Go inside the DB and try:

```
DELETE FROM "videoCaption" v1 USING (SELECT MIN(id) as id, "filename" FROM "videoCaption" GROUP BY "filename" HAVING COUNT(*) > 1) v2 WHERE v1."filename" = v2."filename" AND v1.id <> v2.id
```

Then restart peertube

**Comment by pokapow** [comment]
Thx a lot @Chocobozzz It works flawlessly
