### ISSUE TITLE
Enable adaptive bitrate streaming to downgrade quality to prevent video getting stuck buffering?

### ISSUE THREAD

**Issue by c0xc** [Chocobozzz/PeerTube#3894]
When hundreds of clients are all watching a full hd video at the same time, I often experience playback issues because the server cannot handle that many clients, the video file download is slower than playback. However, manually selecting a lower quality like 720p works to get rid of the buffering (which makes a huge difference if the 1080p version requires a bitrate of 5 Mbit/s and the 720p version has 1 Mbit/s).

Would it be possible to enable adaptive bitrate streaming, to have the player automatically downgrade the playback quality to one that can be transferred without buffering?

**Comment by test2a** [comment]
How big is your server?

What is your Max concurrent users?

Do you have p2p enabled? Does that work? Or only hls?

What is your disk logs like? Is it because of your network/storage speed limitation? 

I am no expert but I suppose the web player already has this functionality, maybe there is an issue? I am not sure

**Comment by c0xc** [comment]
It's not really related to server or storage performance though if it was, the result should be similar. The bandwidth is the usual bottleneck and since this question isn't only about one server, I'm just going to say that in most cases, the server has a gigabit uplink. A general estimate for the maximum number of concurrent viewers would be 200 viewers for a full hd video with a 5 mbit/s bitrate given a 1 gbit/s uplink. But none of this is relevant in regards to the question, which is about playback issues, possibly caused by too many viewers, when the quality should be downgraded to allow playback to continue. As far as I can tell, it's always been HLS, so m3u8 playlists and "fragmented" files.

**Comment by Chocobozzz** [comment]
See https://github.com/Novage/p2p-media-loader/pull/192
