### ISSUE TITLE
Add "last video" option to playlist url

### ISSUE THREAD

**Issue by pprw** [Chocobozzz/PeerTube#3897]
A playlist url is a convenient way to share videos frequently updated.

However, it focuses the first (and older) video which induces a manual action to watch the last (newer) video uploaded.

You can point to a particular video (with `?playlistPosition=4` for example) but not to the last/newer uploaded video (afaik).

An option `?playlistPosition=last` would be nice.

**Comment by hroussel** [comment]
I think we just need to add a route param in [my-video-playlist-elements.component.ts](https://app-int.quod.ai/github/Chocobozzz/PeerTube/answers/details?open_file=client%2Fsrc%2Fapp%2F%2Bmy-library%2Fmy-video-playlists%2Fmy-video-playlist-elements.component.ts&state=%7B%22client%2Fsrc%2Fapp%2F%2Bmy-library%2Fmy-video-playlists%2Fmy-video-playlist-elements.component.ts%22%3A%7B%22range%22%3A%7B%22lineFrom%22%3A59%2C%22lineTo%22%3A64%7D%2C%22activeQuestionId%22%3A4132%7D%7D). Is that right @Chocobozzz ?

**Comment by Poslovitch** [comment]
I'm working on this.
