### ISSUE TITLE
How can I cancel or modify the Maximum number of different pods for a scheduled request ?

### ISSUE THREAD

**Issue by imtube** [Chocobozzz/PeerTube#39]
Hello,
I found that the default limitation number is a little small, how can I modify it ?

**Comment by Chocobozzz** [comment]
You can change the value in the [constants](https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/constants.js#L112) file. But please do not use PeerTube in production since there will be breaking changes in a few weeks.
