### ISSUE TITLE
Displaying strategies, is it a bug or not?

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#3902]
Peertube v.3.1.0
Site: https://peervideo.ru

In the Videos redundancies section, I have single instance sync enabled. In the config file I have all the strategies uncommented.

![Screenshot_3](https://user-images.githubusercontent.com/11453567/112962617-3c987380-914f-11eb-8333-19a7bfbb3acd.png)

If you look in the **Videos redundancies** section, you can see that for some strategies, only a directory is added, and for some, both a directory and a file are added.

![Screenshot_4](https://user-images.githubusercontent.com/11453567/112963670-45d61000-9150-11eb-9000-b9bc17552bcc.png)

![Screenshot_5](https://user-images.githubusercontent.com/11453567/112963700-4cfd1e00-9150-11eb-9e47-b829a6c37f7f.png)

![Screenshot_6](https://user-images.githubusercontent.com/11453567/112963725-525a6880-9150-11eb-9537-ab0039e15a9f.png)

For example, for the recently-added strategy, only directories are added. Is that how it should be? It's just that in previous versions, only the files with the .MP4 extension were displayed in this section

**Comment by Chocobozzz** [comment]
Hello,

Please upgrade to 3.1: we fixed some issues with redundancy and HLS videos.

**Comment by Alterak** [comment]
> Hello,
> 
> Please upgrade to 3.1: we fixed some issues with redundancy and HLS videos.

Forgive me, I indicated incorrectly in the request. I just have the latest version 3.1.0 installed.

**Comment by Chocobozzz** [comment]
Redundancy mirror HLS playlist (directories) and raw mp4 (files). It's the reason why you see directories and files in the redundancy panel.
