### ISSUE TITLE
Warn unsupported browsers

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3905]
**Describe the problem to be solved**
When visiting PeerTube with an unsupported browser (i.e. iOS 11 Safari) the player is just black without any explanation.

**Describe the solution you would like:**
In addition to the current error message due to Angular render failure I'd like a warning message at the top of the site that says that the current browser isn't supported and the page may not work as expected.

**Describe alternatives you have considered**  
I did a quick search to see if there's any small library that can do the browser check but I didn't find anything.

**Comment by Chocobozzz** [comment]
Just as an information, iOS 11.3 is supported but not iOS 11.2.

**Comment by Chocobozzz** [comment]
Embed is now compatible with iOS 11.x with https://github.com/Chocobozzz/PeerTube/commit/6527eb0ccf823b5eac547c90066d3bd693094b2c and an error message is displayed with https://github.com/Chocobozzz/PeerTube/commit/c21a0aa855f61daaca458e16b47f95278898beb4
