### ISSUE TITLE
Follow after reinstall: Signature from [...] is invalid

### ISSUE THREAD

**Issue by thorstenkirsch** [Chocobozzz/PeerTube#3911]
**Describe the current behavior**
Instance A is the main instance. Instance B is a sub instance for supporting the main one.
B followed A for video redundancy. I had to reinstall B without keeping any data. It uses the same subdomain as before.
When trying to follow A again, A does not show any notification and I can't approve it.

This is what the logs on A say:

> [abc.com:443] 2021-04-01 15:23:34.655 warn: Signature from https://subdomain.abc.com/accounts/peertube is invalid {
   "parsed": {
     "scheme": "Signature",
     "params": {
       "keyId": "https://subdomain.abc.com/accounts/peertube",
       "algorithm": "rsa-sha256",
       "headers": [
         "(request-target)",
         "host",
         "date",
         "digest"
       ],
       "signature": "(xxx/xxx/xxx/xxx/xxx/xxx/xxx/xxx/xxx=="
     },
     "signingString": "(request-target): post /accounts/peertube/inbox\nhost: abc.com\ndate: Thu, 01 Apr 2021 13:23:34 GMT\ndigest: SHA-256=xxx=",
     "algorithm": "RSA-SHA256",
     "keyId": "https://subdomain.abc.com/accounts/peertube"
   }
 }

**Steps to reproduce:**

1. Setup Instance A and Instance B
2. Follow A with B
3. Reinstall B and delete its entry at A
4. Try to follow A again

**Describe the expected behavior**
It should notify my about the follower and allow me to approve it.

* PeerTube instance:
  * version: 3.0.1

**Comment by Chocobozzz** [comment]
Hello,

After some days instance A should refresh instance B actor (and so refresh RSA keys too). Please try to refollow the instance now

**Comment by thorstenkirsch** [comment]
It works now. Thank you.

Is there a way to do this manually? By removing some entries from the DB or so?

**Comment by Chocobozzz** [comment]
Yes, deleting the `peertube` row of this instance in `account` table
