### ISSUE TITLE
Cannot change transcode profil in admin panel

### ISSUE THREAD

**Issue by TheoLeCalvar** [Chocobozzz/PeerTube#3912]
**Describe the current behavior**

Impossible to change transcode profil from admin interface.
Changing the value directly in json correctly change selected profile.

**Steps to reproduce:**

1. Create a transcode profil with a plugin (like peertube-plugin-transcoding-profile-debug)
2. Try to change transcode profil from default to the new one
3. Nothing happens

**Describe the expected behavior**

Click on a profil in the select should change the active profile.

**Additional information**

* PeerTube instance: local dev
  * version: develop
  * NodeJS version: v15.13.0

* Browser name, version and platforms on which you could reproduce the bug: firefox 87, chrome 89 on linux
* Link to browser console log if relevant: no log in console

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/b06f1ead3b599a0315053572a6cf5811e533fc49
