### ISSUE TITLE
SMTP Error on restart : code: ETIMEDOUT

### ISSUE THREAD

**Issue by compleus** [Chocobozzz/PeerTube#3913]
Hello

I've just installed a new peertube instance using docker. Thanks a lot !!!!

When I launch manually the instance using "docker-compose up -d", everything is ok.
But when I restart my virtual server (hosted by Infomaniak), I have the following error:

> peertube_1   | [zen.chat:443] 2021-04-01 22:28:09.730 info: Database peertube is ready.
> peertube_1   | [zen.chat:443] 2021-04-01 22:28:08.612 info: Using abricot.o2switch.net:465 as SMTP server.
> peertube_1   | [zen.chat:443] 2021-04-01 22:28:08.614 info: Testing SMTP server...
> peertube_1   | [zen.chat:443] 2021-04-01 22:28:08.653 info: Connection established to 109.234.161.20:465 {
> peertube_1   |   "component": "smtp-connection",
> peertube_1   |   "sid": "QPizUpGvceM",
> peertube_1   |   "tnx": "network",
> peertube_1   |   "localAddress": "172.18.0.42",
> peertube_1   |   "localPort": 48120,
> peertube_1   |   "remoteAddress": "109.234.161.20",
> peertube_1   |   "remotePort": 465
> peertube_1   | }
> **peertube_1   | [zen.chat:443] 2021-04-01 22:28:38.657 error: Greeting never received {
> peertube_1   |   "component": "smtp-connection",
> peertube_1   |   "sid": "QPizUpGvceM"
> peertube_1   | }
> peertube_1   | [zen.chat:443] 2021-04-01 22:28:38.658 error: Failed to connect to SMTP abricot.o2switch.net:465. {
> peertube_1   |   "err": {
> peertube_1   |     "stack": "Error: Greeting never received\n    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:19)\n    at SMTPConnection._onError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:760:20)\n    at Timeout.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:694:22)\n    at listOnTimeout (internal/timers.js:554:17)\n    at processTimers (internal/timers.js:497:7)",
> peertube_1   |     "message": "Greeting never received",
> peertube_1   |     "code": "ETIMEDOUT",
> peertube_1   |     "command": "CONN"
> peertube_1   |   }**
> peertube_1   | }
> peertube_1   | [zen.chat:443] 2021-04-01 22:28:38.672 info: Cleaning HTML cache.
> peertube_1   | [zen.chat:443] 2021-04-01 22:28:38.684 info: HTTP server listening on 0.0.0.0:9000
> peertube_1   | [zen.chat:443] 2021-04-01 22:28:38.685 info: Web server: https://zen.chat
> peertube_1   | [zen.chat:443] 2021-04-01 22:28:38.686 info: Connection closed {
> peertube_1   |   "component": "smtp-connection",
> peertube_1   |   "sid": "QPizUpGvceM",
> peertube_1   |   "tnx": "network"

Maybe, the network configuration is not complete (missing resolveconf, or something else ?)
--> Is there a way to put a delay to test this possibility ?

**Steps to reproduce:**

1. Install peertube docker instance on Infomanaik Cloud server
2. launch docker using  "docker-compose up -d",
3. Reboot the server and check the logs

**Describe the expected behavior**
If I do the following command "docker-compose down && docker-compose up -d", ecerything is fine :

> peertube_1   | [zen.chat:443] 2021-04-01 22:56:27.530 info: Database peertube is ready.
> peertube_1   | [zen.chat:443] 2021-04-01 22:56:27.681 info: Using abricot.o2switch.net:465 as SMTP server.
> peertube_1   | [zen.chat:443] 2021-04-01 22:56:27.683 info: Testing SMTP server...
> peertube_1   | [zen.chat:443] 2021-04-01 22:56:27.721 info: Connection established to 109.234.161.20:465 {
> peertube_1   |   "component": "smtp-connection",
> peertube_1   |   "sid": "nuKcbXzidgI",
> peertube_1   |   "tnx": "network",
> peertube_1   |   "localAddress": "172.18.0.42",
> peertube_1   |   "localPort": 48406,
> peertube_1   |   "remoteAddress": "109.234.161.20",
> peertube_1   |   "remotePort": 465
> peertube_1   | }

thanks

**Additional information**

* PeerTube instance:
  * URL: zen.chat
  * version: 3.1.0
  * NodeJS version: v12.21.0
  * Ffmpeg version: 4.1.6-1

**Comment by Chocobozzz** [comment]
Hi,

Could you paste the entire `docker-compose logs` on server restart? So we can see what happens in the postfix container

**Comment by compleus** [comment]
Hello, I have reinstalled the server and maybe I will not use peertube so I will close this thread.
Thanks
