### ISSUE TITLE
RUMBLE import fail 

### ISSUE THREAD

**Issue by kingmida** [Chocobozzz/PeerTube#3916]
hi, i can't import url from rumble.com
can be added the support of rumble import?

actually i use that site https://freedownloadvideo.net/ to download video andafter i upload to peertube
thanks !!!

**Comment by Chocobozzz** [comment]
Hello,

We use `youtube-dl` to import remote videos. Subscribe to https://github.com/ytdl-org/youtube-dl/issues/10785 instead
