### ISSUE TITLE
Job failed error when importing/reencoding videos via cli

### ISSUE THREAD

**Issue by violoncelloCH** [Chocobozzz/PeerTube#3918]
**Describe the current behavior**
As a videographer I sometimes change a already published video, so I use the manual/cli way to import a video replacing an existing one. So today I replaced some videos which i originally published in February on Peertube v3.0.0. I manually transfer the video file(s) to the server and trigger a video import and reencode via cli as follows:
```
NODE_CONFIG_DIR=/config NODE_ENV=production npm run create-import-video-file-job -- -v 79c33e8a-1a2e-4abc-ad4f-b591e06a1b9e -i /data/video.mp4
NODE_CONFIG_DIR=/config NODE_ENV=production npm run create-transcoding-job -- -v 79c33e8a-1a2e-4abc-ad4f-b591e06a1b9e
```
When checking the admin job overview/log, I see the following jobs:
1. video-file-import - COMPLETED
2. video-transcoding - FAILED (see log at the end/below)
3. further video-transcoding jobs which complete

The imported video has a resolution of 1080p. Nevertheless the failing job for hls 1080p has `isMaxQuality` set to `false`.
Interestingly, later on there is another video-transcoding job for hls 1080p with `isMaxQuality` set to `true`, which completes. So I guess the video(s) got correctly (re)encoded. It just remains that frightening error/failure in the job log.

**Steps to reproduce:**

1. manually (re)import a video
2. start (re)transcoding for it
3. see error in log

**Describe the expected behavior**
no error / failed job in job log

**Additional information**

* PeerTube instance:
  * URL: video.violoncello.ch
  * version: 3.1.0
  * NodeJS version: whatever comes with docker
  * Ffmpeg version: whatever comes with docker
  * VOD Transcoding: web-torrent and hls: 240p, 360p, 480p, 720p, 1080p, 1440p, 2160p

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):*
```
Job: 1002 Type: video-transcoding Processed on Apr 3, 2021, 11:17:53 PM Finished on Apr 3, 2021, 11:17:58 PM
--
{   
"type": "new-resolution-to-hls",   
"videoUUID": "79c33e8a-1a2e-4abc-ad4f-b591e06a1b9e",   
"resolution": 1080,   
"isPortraitMode": false,  
"copyCodecs": true,   
"isMaxQuality": false
 }
TypeError: Cannot read property 'Main' of undefined
     at Object.<anonymous> (/app/dist/server/helpers/ffprobe-utils.js:90:56)
     at Generator.next (<anonymous>)
     at fulfilled (/app/node_modules/tslib/tslib.js:114:62)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by Chocobozzz** [comment]
Hi,

Did you try to wait the `create-import-video-file-job` to succeed before running `npm run create-transcoding-job`?

Also could you send to me the video file you try to import?

**Comment by violoncelloCH** [comment]
Yes, as I imported a bunch of videos, I tried waiting for the `create-import-file-job` to succeed (what only took a few seconds) before starting the `create-transcoding-job` and the same error appeared.
Can I send you the video in private? Otherwise I'd have to create and try to reproduce with a new / arbitrary video...

I also rememberd that I've enabled transcoding for 1440p when upgrading to v3.1.0 while that transcoding resolution wasn't there when the video was originally uploaded... not sure if that could have had an impact

**Comment by Chocobozzz** [comment]
> Can I send you the video in private? Otherwise I'd have to create and try to reproduce with a new / arbitrary video...

Yes sure, you can get my email in my github profile

**Comment by violoncelloCH** [comment]
Sorry for the delay. I've now sent you an email with a link to one example video file...

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/08370f6244864df0451cb671b43b6320bf01d33f

**Comment by violoncelloCH** [comment]
whooo, nice, that was quick fix, thanks!
