### ISSUE TITLE
Importing video with a long name does not seems to work

### ISSUE THREAD

**Issue by okhin** [Chocobozzz/PeerTube#392]
* **PeerTube version or URL:**
latest
https://tbs.okhin.fr
* **Browser name/version:**
CLI
* **NodeJS version:**
v9.9.0

* **What is the expected behaviour?**
Using the import-videos.js script with an arabic name, the video should be created
* **What do you see instead?**
There's a 500 Error, saying that the name of the video is invalid

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**
https://gist.github.com/okhin/fd2de289beb61b00cd79ec7d29a92d43

**Comment by rigelk** [comment]
Ideally we should add other langages to our tests too.

**Comment by Chocobozzz** [comment]
This is not related to the language, it's just the video name is too long. We need to truncate it in the import-videos script :)
