### ISSUE TITLE
Cannot follow after reinstallation

### ISSUE THREAD

**Issue by c0xc** [Chocobozzz/PeerTube#3921]
**Describe the current behavior**

If follower F1 used to follow origin instance O and F1 is reinstalled, O won't receive new follow requests from F1. They are shown as "Pending" on F1 but they don't show up in the admin area of O.

Please note that I deliberately reinstalled F1 without restoring the automatic db backup because of another follow bug, which causes a half dead relationship, but the other way around - follower F2 still follows O but O doesn't list F2 as follower anymore, it used to be in the list of followers but got lost and isn't restored ([issue 3847](https://github.com/Chocobozzz/PeerTube/issues/3847)).

This means that F1 is effectively unusable after reinstallation.

**Steps to reproduce:**

1. As described. Reinstall F1 or maybe just restore an older db backup, losing at least 1 follow relationship.
2. Try to restore broken follow link.
3. ?

**Describe the expected behavior**

As suggested in [issue 3851](https://github.com/Chocobozzz/PeerTube/issues/3851), follow links should automatically be checked by a heartbeat, maybe every hour. If a follower is down for maintenance work and it takes more than an hour, it can be removed by O but O should automatically recognize it and restore it as a follower when F1 comes back online and starts sending heartbeats again.
(The same logic should apply for the other bug: If F2 sends heartbeats to O but O responds with "I don't know you anymore", F2 should show an admin notification and probably remove the follow link to O after >1 hour, maybe a day or two.)

**Additional information**

It keeps happening and it's a significant problem because there's no notification and no way to check if a follow link is dead or gone. It happens that partner instances are lost without anyone noticing it until someone happens to go through the full list, looking for each and every known follower.

* PeerTube instance:
  * version: 3.1.0
  * NodeJS version: 12
  * Ffmpeg version: 4.2.4

**Comment by Chocobozzz** [comment]
Instance O should refresh F1 actor after a while (~2 days). So try to re follow instance O on thuesday/wednesday

**Comment by c0xc** [comment]
Okay, thank you.

Also, could it be that O still provides clients with the address of F1 for some time? I've witnessed http requests which failed with error 404 (not only while F1 was unavailable, but the video wasn't mirrored yet in the newly installed F1).
