### ISSUE TITLE
Error 500 in generating ActivityPub outbox with video captions

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#3922]
This bug report comes via a friend who was trying to interoperate with ActivityPub, and hit this error recently when polling many of the outboxes on my server.

**Describe the current behavior**

When polling some of the ActivityPub outbox URLs, the endpoint returns HTTP 500 and an error similar to this one is logged by the peertube daemon:

```
The \"path\" argument must be of type string. Received undefined\n
    at new NodeError (node:internal/errors:329:5)\n
    at validateString (node:internal/validators:129:11)\n
    at Object.join (node:path:1081:7)\n
    at self.getCaptionStaticPath (/var/www/peertube/versions/peertube-v3.1.0/dist/server/models/video/video-caption.js:113:23)\n
    at self.getFileUrl (/var/www/peertube/versions/peertube-v3.1.0/dist/server/models/video/video-caption.js:122:53)\n
    at Object.videoModelToActivityPubObject (/var/www/peertube/versions/peertube-v3.1.0/dist/server/models/video/video-format-utils.js:270:26)\n 
    at self.toActivityPubObject (/var/www/peertube/versions/peertube-v3.1.0/dist/server/models/video/video.js:1013:37)\n
    at /var/www/peertube/versions/peertube-v3.1.0/dist/server/controllers/activitypub/outbox.js:42:43\n
    at Generator.next (<anonymous>)\n
    at fulfilled (/var/www/peertube/versions/peertube-v3.1.0/node_modules/tslib/tslib.js:114:62)
```

**Steps to reproduce:**

Several URLs reproduce this on my server currently:
1. https://diode.zone/accounts/stringlapse/outbox?page=1
2. https://diode.zone/accounts/scanlime/outbox?page=48
3. https://diode.zone/accounts/scanlime/outbox?page=49
4. https://diode.zone/accounts/rebecca/outbox?page=1

I examined the database, and didn't see any problems with the videos involved. They seem to have captions stored locally, so the "filename" is populated but the URL is set to NULL intentionally. It seems like this table is being used as intended, with the NULL signifying that captions are stored locally, and non-NULL values being used for remote captions only.

```
peertube_prod=> select * from "videoCaption" where "videoId" = 21656;
  id   | language | videoId |         createdAt          |         updatedAt          | fileUrl |                  filename                   
-------+----------+---------+----------------------------+----------------------------+---------+---------------------------------------------
 17701 | en       |   21656 | 2021-01-31 17:54:12.309-08 | 2021-01-31 17:54:12.309-08 |         | 5215f398-a7a5-44bd-ba9d-955a7075f8e1-en.vtt
```

**Describe the expected behavior**

No crash, able to fully sync with all available outbox items.

**Additional information**

* PeerTube instance:
  * URL: diode.zone
  * version: 3.1.0
  * NodeJS version: v15.12.0
  * Ffmpeg version: 4.3.1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks for the detailed issue. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1afb3c474ae1194748a6fba901058c720e01be0c
