### ISSUE TITLE
Switch to libxmljs2 for Node.js 14.x

### ISSUE THREAD

**Issue by aschaap** [Chocobozzz/PeerTube#3924]
**Describe the problem to be solved**

When setting up the dev environment with Node.js v14.16.0, `yarn install --pure-lockfile` fails on the libxmljs dependency, due to a 404 error when trying to fetch the precompiled binary (and a subsequent 404 when trying to fetch the source). Libxmljs v0.19.7 is ~2 years old, and doesn't appear to be maintained. (Additionally, Node.js v12.x is in maintenance mode.)

**Describe the solution you would like:**

Libxmljs2 is an actively maintained fork, and switching to it would have to happen at some point to move on from Node.js v12.x.

**Describe alternatives you have considered** 

I briefly looked for other forks/alternatives, but this seems to be the path of the least resistance.

**Comment by Chocobozzz** [comment]
Hi,

I think we should use another XML parser, in pure JS because we only use this module in 1 small test: https://github.com/Chocobozzz/PeerTube/blob/develop/server/tests/feeds/feeds.ts#L142

**Comment by Chocobozzz** [comment]
Done in https://github.com/Chocobozzz/PeerTube/commit/b70025bfdc5f3d7aa3e827f6cadfa1e21483a038
