### ISSUE TITLE
Transcoding: Error - Missing lock for job 

### ISSUE THREAD

**Issue by roere** [Chocobozzz/PeerTube#3926]
I get the following error in my transcoding queue:

> Job: 99 Type: video-transcoding Processed on Apr 5, 2021, 12:54:08 AM Finished on -
> --
> {   "type": "optimize-to-webtorrent",   "videoUUID": "aeb8abd0-xxxxxxxxxxxxxxxxxxxxx",   "isNewVideo": true }
> Error: Missing lock for job 99 finished     
> at Object.finishedErrors (/var/www/peertube/versions/peertube-v3.1.0/node_modules/bull/lib/scripts.js:185:16)     
> at /var/www/peertube/versions/peertube-v3.1.0/node_modules/bull/lib/scripts.js:172:23     
> at runMicrotasks (<anonymous>)     
> at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Steps to reproduce:**

1. Upload video
2. Wait for transcoding

**Additional information**

Is there a way to delete the jobs in the queue, so that I can start the transcoding again from CLI?

* PeerTube instance:
  * URL: widemus.de
  * version: 3.1.0
  * NodeJS version: 12.13.1
  * Ffmpeg version: 4.2.4

**Comment by Chocobozzz** [comment]
Hi,

What is your redis version?

> I can start the transcoding again from CLI?

Yes, see https://docs.joinpeertube.org/maintain-tools?id=create-transcoding-jobjs

**Comment by roere** [comment]
Redis Version is 5.0.7.

> >   I can start the transcoding again from CLI?
>  Yes, see https://docs.joinpeertube.org/maintain-tools?id=create-transcoding-jobjs

Yes, I know. I already started a new cli job. But it remains in status "waiting". That's why I asked if I can delete entries from the queue, in case one job is blocking the others.

**Comment by Chocobozzz** [comment]
Did you try to restart peertube?

If yes, you'll have to use `redis-cli`  (`keys bull-*` to find the broken job)

**Comment by roere** [comment]
> Did you try to restart peertube?
Yes, I tried restarting Peertube as well as the whole server. In both cases one job startet to be active for a short time and than changed again to status "waiting" with the above error.

> If yes, you'll have to use `redis-cli` (`keys bull-*` to find the broken job)
Thanks, I try that.
