### ISSUE TITLE
Provide minimum requirements for production

### ISSUE THREAD

**Issue by Rambobafet** [Chocobozzz/PeerTube#393]
Hi!
Could you provide a minimal setup for deploying Peertube on production in the documentation?

Now it's just saying `Please don't install PeerTube for production on a small device behind a low bandwidth connection (example: a Raspberry PI behind your ADSL link) because it could slow down the fediverse.` and okay I understand that a Pi is not enough, but what is enough? 
- Is an ultrabook transformed in an self hosting server enough? 
- Do I have to rent a server? With how much ram and CPU? :)

(source: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md)

**Comment by Chocobozzz** [comment]
Does it answer to your question? https://github.com/Chocobozzz/PeerTube/blob/develop/FAQ.md#should-i-have-a-big-server-to-run-peertube

**Comment by rigelk** [comment]
It would prove a bit difficult to keep in sync both, but arguably we need to tidy up references.

**Comment by Chocobozzz** [comment]
I updated the template issue: https://github.com/Chocobozzz/PeerTube/commit/ae09ed2c6a4d22262b02870905d16211994662b6

**Comment by narcisgarcia** [comment]
Additional request: Copy this HR information to first chapter in docs.joinpeertube.org
