### ISSUE TITLE
"Bad request" at plugin install

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#3930]
**Describe the current behavior**
I can't install any plugin since the last upgrade, and the message "bad request" appears.
**Steps to reproduce:**

1. Upgrade to 3.1.
2. Try to install a plugin

**Describe the expected behavior**
Plugin installation
**Additional information**

* PeerTube instance:
  * URL: peertube.stemy.me
  * version: 3.1
  * NodeJS version: 10.24.0~dfsg-1~deb10u1
  * Ffmpeg version: 7:4.1.6-1~deb10u1

* Browser name, version and platforms on which you could reproduce the bug: firefox 78.9 on debian stable
* Link to browser console log if relevant: https://zerobin.stemy.me/?131f38ce2c7c57b3#CsmfnEYmweC9VkhGJVd4uMxBaPkR8xzJByZ3efHe3yWF
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): https://zerobin.stemy.me/?45850af23604648b#44KYRiViUTfzZq7V5n1LsTuuUaWaU8PHzDA4h2JbFGGb

**Comment by Chocobozzz** [comment]
Hi,

It seems there is a permission issue in your installation: 

```
Error: Command failed: yarn add peertube-plugin-background-play\nwarning package.json: No license field\nwarning No license field\nerror An unexpected error occurred: \"EACCES: permission denied, unlink '/home/yunohost.app/peertube/storage/plugins/node_modules/@types/ldapjs/LICENSE
```

I suggest you to contact yunohost support

**Comment by kimsible** [comment]
@Chocobozzz  we have same issue on QueerMotion.org, we just noticed it because we need a plugin. What is the permission issue you found ? (what rights on what directories?)
