### ISSUE TITLE
Embeded playlists have a transparent background for the list

### ISSUE THREAD

**Issue by TROMsite** [Chocobozzz/PeerTube#3934]
**Steps to reproduce:**

1. See an embed playlist like here https://www.tromsite.com/videos/
2. Click the button to open the list of videos
3. Click the scroll bar and drag up and down. You will see that the playlist background (the semi transparent black one), is gone. It will appear again if you click somewhere else on the page. In a sense, when it is focused it loses the background color.

* PeerTube instance:
  * URL: https://videos.trom.tf
  * version: 3.1
  * 
* Browser name, version and platforms on which you could reproduce the bug: Firefox

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/b9244002fcc48dda7f3a588980d910a40429238f
