### ISSUE TITLE
User initials as default avatar

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3935]
**Describe the problem to be solved**
The majority of our users doesn't have any custom avatar. This means that there's a lot of comments with the default gray avatar, which looks a bit "boring".

**Describe the solution you would like:**
The default avatar can be a colored circle with the user initial within, instead of the grey smiley.

**Comment by rigelk** [comment]
The current solution has the advantage of simplicity: it is implemented exactly the same way as the image chosen by the user once they get to upload one.

**Comment by kontrollanten** [comment]
I think it can be possible to keep the simplicity by creating a `UserAvatar` component that takes the user object as input and then decides whether to show an avatar or initials.

**Comment by rigelk** [comment]
Initials do not apply to all channel names, nor account names for that matter. In a platform enforcing person names as display names, this would have much more sense than in PeerTube, IMHO.
