### ISSUE TITLE
Plugins modules are not correctly unloaded on uninstall (or updates)

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#3940]
**Describe the current behavior**

While working on new plugins, I have sometimes weird behaviors that requires a peertube restart.
I thinks that it is because of these lines: https://github.com/Chocobozzz/PeerTube/blob/0564fc09d3ea46d78cc4e454f52aefeca68b73e2/server/lib/plugins/plugin-manager.ts#L413-L415

Plugins are unloaded using:
```javascript
delete require.cache[modulePath]
```
But if they are requires in the module main file, it will not be unloaded.

So, when you update your module code, it will mix old and new modules.

**Describe the expected behavior**

Plugin imported files should be unloaded too.
I think this module can help: https://www.npmjs.com/package/decache

**Additional information**

* PeerTube instance:
  * version: 3.1.0
  * NodeJS version: 12

**Comment by JohnXLivingston** [comment]
I can confirm that this workaround is working with my plugin:
https://github.com/JohnXLivingston/peertube-plugin-livechat/commit/0bad31dddb413b15371b11b5cc3dccf46adddb58

Without it, changes in my settings names are not visible unless I restart the server. With the call to decache, everything works fine.

**Comment by JohnXLivingston** [comment]
@Chocobozzz , tell me if you want me to make a PR with a fix.

**Comment by Chocobozzz** [comment]
> tell me if you want me to make a PR with a fix.

Yes please :+1:

**Comment by JohnXLivingston** [comment]
For the record, I found a similar potential bug in server/initializers, function reloadConfig. 
Have you ever had a cache bug when reloading config? Maybe we should apply the same fix?

**Comment by Chocobozzz** [comment]
> Have you ever had a cache bug when reloading config?

No we did not, but it safer to use decache here too

**Comment by JohnXLivingston** [comment]
Ok, i'll do the PR.
