### ISSUE TITLE
Unable to install plugin locally

### ISSUE THREAD

**Issue by zanhesl** [Chocobozzz/PeerTube#3941]
Hello everyone, I am working on my peertube plugin, but when I am trying to install it on my local instance (run via `NODE_ENV=test npm start`) I keep getting following error:

<img width="535" alt="Снимок экрана 2021-04-08 в 16 48 59" src="https://user-images.githubusercontent.com/48605213/114038192-51c97c80-988a-11eb-8b0b-d9d88d7680e7.png">

Installation is done with `node ./dist/server/tools/peertube.js plugins install --path /your/absolute/plugin-or-theme/path`, with package path instead of test path.

I am using latest released version, and I've tried installing my own plugin and known-working plugins, but with no success.

**Comment by Chocobozzz** [comment]
Hello,

Please paste the entire log (the origin error should be above your screen)

**Comment by zanhesl** [comment]
@Chocobozzz thanks for your response. This is complete log (as far as I can tell):

<img width="525" alt="Снимок экрана 2021-04-09 в 10 31 40" src="https://user-images.githubusercontent.com/48605213/114145135-c64dfb00-991e-11eb-8b75-61ae23e09689.png">

<img width="522" alt="Снимок экрана 2021-04-09 в 10 32 48" src="https://user-images.githubusercontent.com/48605213/114145317-f09fb880-991e-11eb-8eb1-17fd2768303b.png">

**Comment by zanhesl** [comment]
Also, when I am trying to install plugin via `NODE_CONFIG_DIR=/Users/aleksandr/Downloads/PeerTube-develop/config NODE_ENV=production npm run plugin:install -- --plugin-path /Users/aleksandr/Downloads/peertube-plugin-livechat-main`

I am getting the same error:

<img width="537" alt="Снимок экрана 2021-04-09 в 10 44 05" src="https://user-images.githubusercontent.com/48605213/114146634-82f48c00-9920-11eb-99a1-9eaedda97f88.png">

<img width="542" alt="Снимок экрана 2021-04-09 в 10 44 24" src="https://user-images.githubusercontent.com/48605213/114146678-8daf2100-9920-11eb-87c4-4b0283510185.png">

**Comment by zanhesl** [comment]
I've just noticed, that `npm run build` works incorrectly, maybe that has something to do with the issue?

<img width="530" alt="Снимок экрана 2021-04-09 в 11 06 40" src="https://user-images.githubusercontent.com/48605213/114149511-aa008d00-9923-11eb-821e-f4482cb5c478.png">

**Comment by Chocobozzz** [comment]
Please follow https://docs.joinpeertube.org/dependencies?id=macos to update your bash shell.

Regarding your issue, I think there is something wrong with your plugin directory (in Downloads/) because it does not contain a `package.json`. Try `NODE_CONFIG_DIR=/Users/aleksandr/Downloads/PeerTube-develop/config NODE_ENV=production npm run plugin:install -- --npm-name peertube-plugin-livechat-main` instead

**Comment by zanhesl** [comment]
I've done all the settings for bash, of course. I am currently using  5.1.4(1)-release version. The thing is that I want to install my local plugin, that I can modify and immidiately check for the changes. How can I configure my plugin directory/peertube server directory? Should I build it before installation?

**Comment by zanhesl** [comment]
I have moved my plugin to the peertube local server directory, and the issue is still present.

<img width="1440" alt="Снимок экрана 2021-04-09 в 11 29 41" src="https://user-images.githubusercontent.com/48605213/114152366-e1bd0400-9926-11eb-850c-b981cb99f1bd.png">

**Comment by zanhesl** [comment]
<img width="1110" alt="Снимок экрана 2021-04-09 в 11 32 00" src="https://user-images.githubusercontent.com/48605213/114152660-35c7e880-9927-11eb-800d-804e62cd03ef.png">

Apparently npm-name worked, and plugin was installed correctly. So, I think the issue is solve despite being not resolved completely)
