### ISSUE TITLE
Serve javascript and CSS from S3

### ISSUE THREAD

**Issue by LasersAreGreat** [Chocobozzz/PeerTube#3943]
Being able to serve CSS and Javascript from object storage, as we we can already do easily for video and thumbnails/avatars, would be nice.  It would save nearly 900KB for each visitor which would seem to be a big deal when there is a sudden spike in visitors.

I've tried to find a way to modify the nginx config to make that happen, but I can't seem to figure it out. Even if this isn't a change that you make soon, if you can point me in the direction I am happy to try and figure it out and then post what I find here.

**Comment by rigelk** [comment]
To simplify the S3 guide, we left that aside, knowing the savings would be marginal compared to the bandwidth taken by videos. However the strategy is mostly the same as for videos: you have [a block](https://github.com/Chocobozzz/PeerTube//blob/9817060fb7b4b728eed366bd75c9cba638a4c78d/support/nginx/peertube#L176-L181) covering assets that can safely be served directly from Nginx or any CDN. You can do so by copying the content of `client/dist/` to a S3 public bucket and placing in line 179 the following:

```
set $cdn <your S3-compatiable bucket public url mounted via fuse>;
rewrite ^/client/(.*)$ $cdn/$1 redirect;
```

**Comment by LasersAreGreat** [comment]
Thank you, I got that working with everything but the javascript. It turns out that Chrome (and other browsers) don't allow the loading of javascript when it is from a redirect like that for securit reasons. This is not a CORS issue, but something that seems hardcoded in the browser for security reasons.

So, it would seem the only way to load the javascript from a CDN would be to have peertube give the CDN as the source, rather than using nginx to redirect.

Can you point me in the direction of where in the peertube source I could make such edits?

**Comment by kontrollanten** [comment]
@LasersAreGreat We've a CDN in front of our PeerTube instance, it works great and was easy to setup. Have you considered that solution?

**Comment by LasersAreGreat** [comment]
> @LasersAreGreat We've a CDN in front of our PeerTube instance, it works great and was easy to setup. Have you considered that solution?

I tried Cloudflare but the p2p feature didn't work because the Peertube server couldn't see the real IP of the client. But if you have a CDN working  I would love to hear more about how you have it setup so that I can give that a try!

**Comment by kontrollanten** [comment]
> > @LasersAreGreat We've a CDN in front of our PeerTube instance, it works great and was easy to setup. Have you considered that solution?
> 
> I tried Cloudflare but the p2p feature didn't work because the Peertube server couldn't see the real IP of the client. But if you have a CDN working I would love to hear more about how you have it setup so that I can give that a try!

We're using StackPath (they've really good and quick support). We've added all the CDN IP addresses to [trust_proxy](https://github.com/Chocobozzz/PeerTube/blob/f135bfda77d995a93d09f7cf0bf3beeb0fd1ac42/config/default.yaml#L35) and it works like a charm.

**Comment by LasersAreGreat** [comment]
> We're using StackPath (they've really good and quick support). We've added all the CDN IP addresses to [trust_proxy](https://github.com/Chocobozzz/PeerTube/blob/f135bfda77d995a93d09f7cf0bf3beeb0fd1ac42/config/default.yaml#L35) and it works like a charm.

Thank you, I've gotten a CDN working and have trust_proxy configured properly.

I would like to ask what caching you've found you can enable and still have peertube work. I don't have users account creation enabled and bypass the CDN for uploading videos, so my only concern is that people who visit the website can watch videos and have the p2p feature work.

When I enabled caching of the video URI itself ( e.g. https://peertube.newsocial.tech/videos/watch/224658e5-4e70-4fc2-b2c3-ebc7e02fc744 )  I ran into problems with pages not loading and videos not playing.  Does that mirror your experience or are you able to cache those URIs and save some load on your server?

Thanks again for all your help!

**Comment by kontrollanten** [comment]
> > We're using StackPath (they've really good and quick support). We've added all the CDN IP addresses to [trust_proxy](https://github.com/Chocobozzz/PeerTube/blob/f135bfda77d995a93d09f7cf0bf3beeb0fd1ac42/config/default.yaml#L35) and it works like a charm.
> 
> Thank you, I've gotten a CDN working and have trust_proxy configured properly.
> 
> I would like to ask what caching you've found you can enable and still have peertube work. I don't have users account creation enabled and bypass the CDN for uploading videos, so my only concern is that people who visit the website can watch videos and have the p2p feature work.
> 
> When I enabled caching of the video URI itself ( e.g. https://peertube.newsocial.tech/videos/watch/224658e5-4e70-4fc2-b2c3-ebc7e02fc744 ) I ran into problems with pages not loading and videos not playing. Does that mirror your experience or are you able to cache those URIs and save some load on your server?
> 
> Thanks again for all your help!

Great! We're caching everything except `/api/v1/*` path. And the p2p feature works great. What kind errors did you get when you cached the video URI? Do you have any output from the browser console?

**Comment by LasersAreGreat** [comment]
> Great! We're caching everything except `/api/v1/*` path. And the p2p feature works great. What kind errors did you get when you cached the video URI? Do you have any output from the browser console?
![signal-2021-04-13-213550](https://user-images.githubusercontent.com/31263132/114954662-b2bffa00-9e20-11eb-9682-b904b137b61a.jpeg)

When I enable caching of the /videos/* path, trying to open the video URI results in the browser offering to download a .bin file.  I attached a screenshot.

**Comment by kontrollanten** [comment]
Run `curl -I https://peertube.newsocial.tech/videos/watch/224658e5-4e70-4fc2-b2c3-ebc7e02fc744` with and without caching and send me the results at stambanan@pm.me. Provide me your Skype username if you've Skype.
