### ISSUE TITLE
A button like "open direct mpeg-stream" 

### ISSUE THREAD

**Issue by mfu-mcosys** [Chocobozzz/PeerTube#3944]
**Describe the problem to be solved**
With PeerTube it is at the moment not easy to stream from a smartphone to a Chromecast/TV or anything else.
At the moment you need to press "download", choose "direct download", copy the URL and paste it into VLC to get a stream to TV/Chromecast or whatever.
 

**Describe the solution you would like:**
A button like "open direct mpeg-stream" with a token (like download with intern or privat) will by a workaround for the non-existing native stream-support.

**Describe alternatives you have considered**  
support native streaming :)

**Comment by test2a** [comment]
Have you tried tubelab android? It natively supports Chromecast so it should be good for the time being the website gets it

**Comment by rigelk** [comment]
Hi @mfu-mcosys! Please look out for related issues before creating one, as https://github.com/Chocobozzz/PeerTube/issues/1797 already covers this.
