### ISSUE TITLE
Mobile interface does not honor device width

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#3948]
## Description

When the page initially loads, it loads as a 100% width page which doesn't have pinch zoom or width more than 100% that would make it move horizontally. Modals or long text should honor the width, but it breaks and you see this problem. Most of the modals go stafe left, which don't even allow moving or go 150% or 200% based on desktop width I assume is the problem.

Long text like names should wrap instead of being in a single line.

See attached screenshots: the phone interface of peertube2.cpy.re, using the forkhub android app so it doesn't show the template.

![](https://i.ibb.co/YftkvpN/Screenshot-20210411-110825.png)
![](https://i.ibb.co/ykF42My/Screenshot-20210411-110813.png)
![](https://i.ibb.co/TLbf93q/Screenshot-20210411-110749.png)
![](https://i.ibb.co/fpfhdVB/Screenshot-20210409-075244.png)
![](https://i.ibb.co/dmjzmVp/Screenshot-20210409-075254.png)

**Comment by scanlime** [comment]
fwiw if anyone wants to repro android browser bugs without an android phone, you can always download the SDK and run the device emulator; it plays video fine, assuming you're using hardware accelerated virtualization mode.

**Comment by test2a** [comment]
Here are some tests.
https://tube.ouahpiti.info/videos/watch/1081ef37-b539-407a-9006-0b6de15356c4

I uploaded this video with  long name and it wrapped correctly on mobile.

The channel name i deliberately kept really long and that didnt wrap in this view. As you can see.

But if i open channel page, https://tube.ouahpiti.info/video-channels/privatechannel/videos
The top header correctly scrolls horizontally.

Then if i open owner page, 
https://tube.ouahpiti.info/accounts/johnathan2/video-channels

It doesnt wrap again.

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/b45afe12f90c654aef8098e55bedfa81ca73b1f4
