### ISSUE TITLE
Live transcoding consumes more CPU in 3.1 than 3.01

### ISSUE THREAD

**Issue by tomtoom1978** [Chocobozzz/PeerTube#3951]
I feel the CPU usage of the last version of peertube while a live transcoding ask a lot of resource.

- Before with peertube 3.01 a live transcoding to 240/720/1080 from a 1080p50 source use **50-60%** of a Ryzen 1200
- Now with peertube 3.1 a live transcoding to 240/720/1080 from a 1080p50 source use **90-100%** of the same Ryzen 1200

I quickly fixed the problem and remove the 720p transcoding, and now the CPU usage still around 60%.
I use a Yunohost (3.1.0~ynh1) peertube version

Something changed with ffmpeg ?

**Comment by rigelk** [comment]
@tomtoom1978 did you contact the YunoHost package maintainer for potential pre-configurations made on their part? What version of ffmpeg are you running?

**Comment by tomtoom1978** [comment]
I am going to contact yunohost package maintainer.
Actualy the ffmpeg version of yunohost peertube 3.1 version is:
```
ffmpeg version 4.1.6-1~deb10u1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 8 (Debian 8.3.0-6)
```

**Comment by Chocobozzz** [comment]
Hi,

> I feel the CPU usage of the last version of peertube while a live transcoding ask a lot of resource.

You're talking about the `ffmpeg` process in your example?

What is the value of your threads *Live transcoding threads* option?

**Comment by tomtoom1978** [comment]
Yes it is ffmpeg, I leave threads to Auto
I don't change anything from 3.01 to 3.1 for this part.

**Comment by Chocobozzz** [comment]
Please try to remove `-preset veryfast` line in `dist/server/lib/video-transcoding-profiles.js` (line 27). AFAIK it's the only change we made between 3.0 and 3.1 in the ffmpeg args.

**Comment by tomtoom1978** [comment]
I spent many time I cannot really fix it. I'm not sure to really success with the profiles modification you ask me to change.
The yunohost version, is mayble the problem.
I feef not many people meet this CPU problem, maybe it's only my fault.

**Comment by Chocobozzz** [comment]
Okay then closing until someone else has the same issue
