### ISSUE TITLE
Wrong french translation on action button of muted server

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#3954]
Since PeerTube 3.1 the left action button in the muted server list has a wrong translation, in this context « Unmute » should be translated « Réactiver »

![image](https://user-images.githubusercontent.com/1877318/114324077-89edeb00-9b28-11eb-8e57-d4cbfba9c1f2.png)

**Comment by rigelk** [comment]
I had already spotted it, so it should already be corrected on weblate.

**Comment by kimsible** [comment]
Thanks !
