### ISSUE TITLE
Allows to use docker in a private network

### ISSUE THREAD

**Issue by c0llab0rat0r** [Chocobozzz/PeerTube#3957]
**Parts of the documentation concerned:**

https://docs.joinpeertube.org/install-docker

**Problems**

Following the steps to setup and start a Docker Compose based instance of PeerTube, I ran into three errors:

_Let's Encrypt_

...did not like being on a private, unreachable server on a local network. I could work around this two different ways:

* Approach 1: Access the IP address and port of the PeerTube app directly, skipping the proxy, and using http (no ssl), potentially to include setting up a DNS entry in a local DNS server or in /etc/hosts to have a domain name matching the one I chose while following the initial instructions. This approach also requires removing the port 443 server section of the Nginx config so it doesn't crash due to missing certificate files (or removing Nginx altogether from the docker-compose)
* Approach 2: Omitting Cert Bot and Lets Encrypt and configuring the Nginx proxy to use my own private key and certificate chain

I tried Approach 1 above but not Approach 2.

_Cannot retrieve OAuth Client credentials: undefined_

This is a popup on the home page that appears as soon as the home page opens.

_Invalid client: client is invalid_

If you change the `.env` file to set `PEERTUBE_SIGNUP_ENABLED=true` and go through the `Create Login` forms, and then try to login with your correct credentials, the above error appears in red at the top, and you remain not logged in.

**Describe the desired information/correction**

* Clarifications/corrections to existing instructions on how to setup a local instance without getting the OAuth and login errors
* Instructions which describe how to setup a local instance without SSL. It would be acceptable that this local instance not be able to connect to other public instances

**Are you up to submit a pull request?**

Yes. I'd be willing to do "documentation testing" and submit a PR for a documentation change, once I have a working process for a local instance, or be involved in other ways that would help advance this.

**Other**

I'd also like to upvote #3754.

**Comment by Chocobozzz** [comment]
See https://github.com/Chocobozzz/PeerTube/pull/3970#issuecomment-838037903
