### ISSUE TITLE
Retrieve authorisation token from external auth method

### ISSUE THREAD

**Issue by zanhesl** [Chocobozzz/PeerTube#3959]
Hello everyone, I’ve managed to create simple auth plugin, but I want to make it available via API. How can I retrieve authorisation token to return it as json(without instance’s code modification)?

I want to send token back to client for further API interactions (because I use an external website to upload videos to peertube etc.). But how can I get this token from peertube as a variable? I see no mentions in the documentation.

My plugin code looks like this:

![image](https://user-images.githubusercontent.com/48605213/114531079-3bd60600-9c54-11eb-9efe-2cd5b3613fd3.png)

As far as I understand, this function handles authorisation hook and redirects user's request:

![image](https://user-images.githubusercontent.com/48605213/114531225-60ca7900-9c54-11eb-84a0-a3704c509fbc.png)

Thanks for your attention.

**Comment by rigelk** [comment]
This is already being discussed in https://framacolibri.org/t/retrieve-authorization-token-from-external-auth-method/11690.
