### ISSUE TITLE
deleting a comment not deleting it on the remote instance

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#396]
* **PeerTube version or URL:**
Comment instance: https://peertube.gegeweb.eu/videos/watch/fb7a1aec-1a3d-4ebd-8878-6ae51d12130a
Followed instance: https://video.colibris-outilslibres.org/videos/watch/fb7a1aec-1a3d-4ebd-8878-6ae51d12130a

Deleting a comment on a video from a followed instance not deleting it on the source instance of the video.

**Comment by Chocobozzz** [comment]
Please try to find a failed job with the containing your deleted comment (`https://peertube.gegeweb.eu/videos/watch/fb7a1aec-1a3d-4ebd-8878-6ae51d12130a/comments/82`). Or maybe a completed job.

**Comment by gegeweb** [comment]
What type of job? activitypub-http-unicast ?

Nothing in failed.

Found this http-brodcast (660) and http-unicast (661) after for the comment : 
```
{
  "uri": "https://video.colibris-outilslibres.org/inbox",
  "signatureActorId": 54,
  "body": {
    "type": "Create",
    "id": "https://peertube.gegeweb.eu/videos/watch/fb7a1aec-1a3d-4ebd-8878-6ae51d12130a/comments/82",
    "actor": "https://peertube.gegeweb.eu/accounts/gerald",
    "object": {
      "type": "Note",
```

And this broadcast (662) (no unicast) for the delete action:
```
{
  "uris": [
    "https://linuxrocks.online/inbox",
    "https://peertube.gegeweb.eu/inbox",
    "https://stoneartprod.xyz/inbox"
  ],
  "signatureActorId": 54,
  "body": {
    "type": "Delete",
    "id": "https://peertube.gegeweb.eu/videos/watch/fb7a1aec-1a3d-4ebd-8878-6ae51d12130a/comments/82/delete",
    "actor": "https://peertube.gegeweb.eu/accounts/gerald",
    "object": "https://peertube.gegeweb.eu/videos/watch/fb7a1aec-1a3d-4ebd-8878-6ae51d12130a/comments/82"
  }
}
```
Is that enough?

**Comment by gegeweb** [comment]
As I understand here, delete action are broadcast to the followers (Mastodon users in fact) of the comment author and local instance but no to the remote instance.

**Comment by Chocobozzz** [comment]
Thanks for the issue @gegeweb, it should be fixed now: https://github.com/Chocobozzz/PeerTube/commit/73c0809326670867642f8a36f68d8564e0e406b5
