### ISSUE TITLE
Missing await for method onSettingsChanged in plugin-manager

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#3960]
**Describe the current behavior**

In the following method:

https://github.com/Chocobozzz/PeerTube/blob/1748e92aaa57623b24d71c47e18e7b7224821cd4/server/lib/plugins/plugin-manager.ts#L192-L205

There should be an await when calling `cb`.
Otherwise:

- there could be parallel calls to several callbacks, with unpredictable code execution
- errors in async callbacks will not be detected and catched

Moreover, it seems it was planned to have an async method here:
https://github.com/Chocobozzz/PeerTube/blob/1748e92aaa57623b24d71c47e18e7b7224821cd4/server/controllers/api/plugins.ts#L195

* PeerTube instance:
  * version: 3.1.0

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/24a792404cac0dffff91853af33310fbb7a30297
