### ISSUE TITLE
Picture-in-Picture support

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3961]
**Describe the problem to be solved**
Add Picture-in-Picture button to videojs player. See demo of PiP here https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API#examples

**Describe the solution you would like:**
Set [pictureInPictureToggle: true](https://docs.videojs.com/tutorial-components.html). Currently the video stops playing when leaving the page, but that may be caused by the p2p-media-loader?

**Comment by Chocobozzz** [comment]
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/1211
