### ISSUE TITLE
Update hls.js to v1.0

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3962]
We've some videos that are lagging/hacking in some specific places, when rewinding and playing the same sequence again the same lag occurs (with a console msg about stalled error). In hls.js 1.0.0 the same videos are playing smooth.

I thought this issue can just be a reminder about updating hls.js as soon as p2p-media-loader supports it. They've an open branch where it looks like there's work in progress https://github.com/Novage/p2p-media-loader/tree/feat/hlsjs1

Relates to https://github.com/Novage/p2p-media-loader/pull/178

**Comment by rigelk** [comment]
blocked by https://github.com/Novage/p2p-media-loader/pull/203
