### ISSUE TITLE
uploaded video not playing and downloading

### ISSUE THREAD

**Issue by hongyeecheah** [Chocobozzz/PeerTube#3964]
I had build an instance through synology nas using docker,
but it keep loading with no data sent from the peer tube instance 
![image](https://user-images.githubusercontent.com/44811136/114634785-4cf13800-9c91-11eb-8614-94fbdedd526f.png)
I sure the video is done transcoded as the data/videos folder are having a video with a mp4 format and the input video are in mkv format.
![image](https://user-images.githubusercontent.com/44811136/114634931-a8bbc100-9c91-11eb-8842-008367c533b3.png)
It seems to be I setting the peertube https to true which lead to this problem

**Comment by Chocobozzz** [comment]
Please fill the installation issue template

**Comment by hongyeecheah** [comment]
Steps to reproduce:
I use the same method to setup from the previous issue #3738 

 - PEERTUBE_WEBSERVER_HOSTNAME=mydomain.synology.me
 - PEERTUBE_WEBSERVER_PORT=7400
 - PEERTUBE_WEBSERVER_HTTPS=true


Additional information
Video is not playing, able to login with port 7400 but when I set
 - PEERTUBE_WEBSERVER_HTTPS=false , everything work fine with HTTP://mydomain.synology.me:7400
 -  - PEERTUBE_WEBSERVER_HTTPS=true , Video not play and website isn't at https://mydomain.synology.me:7400

**Comment by Chocobozzz** [comment]
What do you mean by `isn't at https://mydomain.synology.me:7400`? Do you have an error? Is your instance publicly available?
