### ISSUE TITLE
Failed to Transcode Video - Error: spawn ENOMEM

### ISSUE THREAD

**Issue by JacobRock** [Chocobozzz/PeerTube#3966]
Hello. I recently installed a Peertube instance on to a Vultr VPS but appear to have issues with video transcoding. I am able to successfully upload videos to the instance, but whenever I attempt to publish a video and subsequently transcode it, the transcode fails. I have attempted numerous times with multiple different videos, including a few below 100mb in size and the same result occurs. According to the Jobs log, the failed transcoding attempts display "Error: spawn ENOMEM"; I have included the full log below.

After researching the error a bit, it appears that the error frequently appears when the system is running low on memory. My Vultr VPS claims to have 512mb of RAM, which according to the Peertube FAQ should be enough for a basic instance. However, the VPS only has one vCPU, but even when I attempt to transcode a video, my VPS logs indicate a total CPU usage of only about 10-15%.

I am wondering, Is the failure to transcode a result of my VPS and its hardware? If it is, must I setup my Peertube instance on another VPS with better hardware (like 2+ vCores & 1+ gb RAM) to address the problem or is there something I can change on the existing VPS to fix this? Any help would be appreciated!

**Additional information**

My current transcoding settings are the following:
- HLS with P2P (webtorrent disabled)
- Resolutions: 480p & 720p
- Transcoding Threads: Auto (via ffmpeg)
- Transcoding Jobs Concurrency: 1
- Transcoding Profile: Default

* PeerTube instance:
  * version: 3.1.0
  * NodeJS version: 12.22.1
  * Ffmpeg version: 4.1.6-1
  * Redis version: 5.0.3-4
  * PostgreSQL version: 11.11-0
 
VPS Specifications:

- Vultr Cloud Compute
- OS: Debian 10 x64 (buster)
- CPU: 1 vCore
- RAM: 512mb
- Storage: 10gb SSD
- Bandwidth: 500gb

**Job Log:**
Job: 17 Type: video-transcoding Processed on Apr 14, 2021, 7:39:57 PM Finished on Apr 14, 2021, 7:40:00 PM
--
{   "type": "optimize-to-webtorrent",   "videoUUID": "6c6b40b5-7fb2-4ca1-a107-0c46040457e3",   "isNewVideo": true }
Error: spawn ENOMEM     at ChildProcess.spawn (internal/child_process.js:408:11)     at spawn (child_process.js:553:9)     at /var/www/peertube/versions/peertube-v3.1.0/node_modules/fluent-ffmpeg/lib/ffprobe.js:155:21     at FfmpegCommand.proto._getFfprobePath (/var/www/peertube/versions/peertube-v3.1.0/node_modules/fluent-ffmpeg/lib/capabilities.js:144:14)     at FfmpegCommand.proto.ffprobe (/var/www/peertube/versions/peertube-v3.1.0/node_modules/fluent-ffmpeg/lib/ffprobe.js:141:10)     at Function.FfmpegCommand.ffprobe (/var/www/peertube/versions/peertube-v3.1.0/node_modules/fluent-ffmpeg/lib/fluent-ffmpeg.js:221:20)     at /var/www/peertube/versions/peertube-v3.1.0/dist/server/helpers/ffprobe-utils.js:13:16     at new Promise (<anonymous>)     at ffprobePromise (/var/www/peertube/versions/peertube-v3.1.0/dist/server/helpers/ffprobe-utils.js:12:12)     at /var/www/peertube/versions/peertube-v3.1.0/dist/server/helpers/ffprobe-utils.js:155:50     at Generator.next (<anonymous>)     at /var/www/peertube/versions/peertube-v3.1.0/node_modules/tslib/tslib.js:117:75     at new Promise (<anonymous>)     at Object.__awaiter (/var/www/peertube/versions/peertube-v3.1.0/node_modules/tslib/tslib.js:113:16)     at getMetadataFromFile (/var/www/peertube/versions/peertube-v3.1.0/dist/server/helpers/ffprobe-utils.js:154:20)     at /var/www/peertube/versions/peertube-v3.1.0/dist/server/helpers/ffprobe-utils.js:176:32     at Generator.next (<anonymous>)     at /var/www/peertube/versions/peertube-v3.1.0/node_modules/tslib/tslib.js:117:75     at new Promise (<anonymous>)     at Object.__awaiter (/var/www/peertube/versions/peertube-v3.1.0/node_modules/tslib/tslib.js:113:16)     at getVideoStreamFromFile (/var/www/peertube/versions/peertube-v3.1.0/dist/server/helpers/ffprobe-utils.js:175:20)     at Object.<anonymous> (/var/www/peertube/versions/peertube-v3.1.0/dist/server/helpers/ffprobe-utils.js:135:35)     at Generator.next (<anonymous>)     at /var/www/peertube/versions/peertube-v3.1.0/node_modules/tslib/tslib.js:117:75     at new Promise (<anonymous>)     at Object.__awaiter (/var/www/peertube/versions/peertube-v3.1.0/node_modules/tslib/tslib.js:113:16)     at Object.getVideoFileFPS (/var/www/peertube/versions/peertube-v3.1.0/dist/server/helpers/ffprobe-utils.js:134:20)     at Object.<anonymous> (/var/www/peertube/versions/peertube-v3.1.0/dist/server/helpers/ffmpeg-utils.js:218:41)

**Comment by Chocobozzz** [comment]
Hi,

1GB of RAM should be enough if you don't enable transcoding. If you want transcoding, 2vCore and 2GB should fix your issue.
