### ISSUE TITLE
Repeated "Configuration Warning! You enabled user registration"

### ISSUE THREAD

**Issue by c0llab0rat0r** [Chocobozzz/PeerTube#3967]
**Describe the current behavior**

On the `Configuration Warning` dialog, when I click `Configure` button, it takes me to the `Configuration` tab on the page `http://myserver/admin/config/edit-custom#instance-information`, which appears to be the correct page to go to, except that the `Configuration Warning` pops up again.

**Steps to reproduce:**

1. Followed instructions on setting up a brand-new instance, except that in the `.env` file I un-commented the line that enables user registration.
2. Grepped for `root` login in log, then logged in as `root` succesfully
3. Received `Configuration Warning!` popup with message "You enabled user registration on your instance but did not configure the following fields: Instance name .... etc"
4. Clicked Configure to proceed
5. A new browser tab opened, with a configuration page, and the same popup appeared again
6. Clicked Configure a second time
7. A 2nd new browser tab opened (total of three tabs now) with the configuration page and the same popup

**Describe the expected behavior**

Clicking `Configure` should go to the `Configuration` tab on `http://myserver/admin/config/edit-custom#instance-information` without displaying the warning popup again. (no UI loop)

**Additional information**

n/a

* PeerTube instance:
  * URL: private
  * version: 3.1.0 from latest docker
  * NodeJS version: latest docker
  * Ffmpeg version: latest docker

* Browser name, version and platforms on which you could reproduce the bug: Firefox 87.0 on Ubuntu 20.04
* Link to browser console log if relevant: n/a
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): n/a

**Comment by Chocobozzz** [comment]
Thanks, should be fixed in https://github.com/Chocobozzz/PeerTube/commit/9929fbd6f4e209346cd31d05888417a94949da84
