### ISSUE TITLE
Continuous deployment

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3968]
I'd like to hear your thoughts regarding implementing continuous deployment for PeerTube. The last year there has been in average one release each second month. We've created a fork where we have our custom releases, which isn't optimal but works ok, except when there's merge conflicts and we've to wait until next official release. By increasing the delivery pace there'd be easier to develop new features and increase the incentive to contribute. Since the development pace probably just will increase as PeerTube grows I think the need for more frequent releases will increase as well.

Are there any obstacles to start with continuous deployment? I guess the big question is quality assurance/e2e testing. Maybe that could be solved by writing down test cases that volunteers walk through before each deployment?

https://www.atlassian.com/continuous-delivery/principles/continuous-integration-vs-delivery-vs-deployment

**Comment by rigelk** [comment]
Merge conflicts during development and release pace are unrelated, so I don't quite understand what goal you have.

Also, what do you mean by continuous deployment? It's not like we don't deploy develop automatically to peertube2.cpy.re already. Maybe you mean PR app previews?

**Comment by kontrollanten** [comment]
> Merge conflicts during development and release pace are unrelated, so I don't quite understand what goal you have.

It's not unrelated. We're cherry-picking commits that we know are production ready. Since our custom releases aren't in sync with PeerTubes `develop` branch we get a lot of conflicts during cherry-picking which makes it unmanageable without deep knowledge of the recent commits in `develop` branch.

> Also, what do you mean by continuous deployment? It's not like we don't deploy develop automatically to peertube2.cpy.re already. Maybe you mean PR app previews?

With continuous deployment I mean deploying a new version each week.

**Comment by Chocobozzz** [comment]
Hello,

A more frequent release process is asked by some admins but you need to understand that releasing a new peertube version requires a lot of my time:
 * Fix last remaining bugs and ensure we did not made a big change recently without enough testing
 * Pull and check translations
 * Check everything works in the backend and frontend (peertube is quite big now)
 * Check federation compatibility with older peertube versions and other fediverse platforms
 * Check migrations with different databases
 * Create a RC so admins can test the new version and answer to bug reports/questions about this new release
 * Create a news on joinpeertube in both english & french and sync the publication with the release
 * Communicate on social platforms
 * Maintain 2 branches to be able to quickly make a new patch release in case of security issue or big bug

Most of peertube admins don't really want to spend their time upgrading peertube every week, so we'll have a big fragmentation of peertube versions in the federation meaning additional work for me.

So I'm sorry, but I don't have time to ensure we have a production ready version/branch every week.

**Comment by kontrollanten** [comment]
Thanks for the explanation. I understood that continuous deployment is far away and that's why I created this issue to be able to start investigating what needs to be done and begin to work towards the goal, step by step. One of the main goals with continuous delivery is to lessen the burden from the team. Or as Atlassian describes it _the complexity of deploying software has been taken away. Your team doesn't have to spend days preparing for a release anymore._

> * Fix last remaining bugs and ensure we did not made a big change recently without enough testing
> * Check everything works in the backend and frontend (peertube is quite big now)
> * Create a RC so admins can test the new version and answer to bug reports/questions about this new release

A shorter release cycle should make this work a lot smaller each release. If a new version is released each week maybe the RC could be skipped since there will be so small changes each week.

> * Pull and check translations

I don't know how this is done, can it be automated?

> * Check federation compatibility with older peertube versions and other fediverse platforms

Can we make it easier for admins to upgrade PeerTube and in that way decrease the supported versions? Can we add a message to the admins in the web interface that says there's a new version available? We could add an upgrade button as well.

> * Check migrations with different databases

Can you elaborate this?

> * Create a news on joinpeertube in both english & french and sync the publication with the release
> * Communicate on social platforms

If the releases are done each week, must it be communicated at social platforms and joinpeertube? I think a summary can be published each second month instead (same pace as today).

Another option is to use conventional commits and [standard-version](https://github.com/conventional-changelog/standard-version) to get automated change log.

> * Maintain 2 branches to be able to quickly make a new patch release in case of security issue or big bug

With a faster release pace this should be easier than it its today?

**Comment by rigelk** [comment]
> > * Check federation compatibility with older peertube versions and other fediverse platforms
> 
> Can we make it easier for admins to upgrade PeerTube and in that way decrease the supported versions? Can we add a message to the admins in the web interface that says there's a new version available? We could add an upgrade button as well.

We already have an [upgrade script](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#upgrade), and I don't see a lot of ways to make it any easier than that.



> One of the main goals with continuous delivery is to lessen the burden from the team.

A lot of the release steps have already been scripted. Putting them in the CI as a manually triggered job might help a little, but some of them currently don't seem scriptable and would put an undue burden on Chocobozzz.

> > * Check migrations with different databases
> 
> Can you elaborate this?

See https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/development/release.md

**Comment by kontrollanten** [comment]
> > > * Check federation compatibility with older peertube versions and other fediverse platforms
> > 
> > 
> > Can we make it easier for admins to upgrade PeerTube and in that way decrease the supported versions? Can we add a message to the admins in the web interface that says there's a new version available? We could add an upgrade button as well.
> 
> We already have an [upgrade script](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#upgrade), and I don't see a lot of ways to make it any easier than that.

A notification to the admins and a button in the web interface should make it easier as it won't require any terminal access.

> > One of the main goals with continuous delivery is to lessen the burden from the team.
> 
> A lot of the release steps have already been scripted. Putting them in the CI as a manually triggered job might help a little, but some of them currently don't seem scriptable and would put an undue burden on Chocobozzz.

The point of this issue is to list all the tasks that seems unscriptable and see if the community can find a solution.

> > > * Check migrations with different databases
> > 
> > 
> > Can you elaborate this?
> 
> See https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/development/release.md

That looks like a task for the CI. Is the migration verified by the server starting or is there any additional manual checks?

**Comment by rigelk** [comment]
> A notification to the admins and a button in the web interface should make it easier as it won't require any terminal access.

How would you implement that upgrade button?

**Comment by kontrollanten** [comment]
> > A notification to the admins and a button in the web interface should make it easier as it won't require any terminal access.
> 
> How would you implement that upgrade button?

An API call that triggers the upgrade script to run.

**Comment by rigelk** [comment]
> An API call that triggers the upgrade script to run.

The PeerTube runtime doesn't have the rights to reload its service, nor can it integrate with community packages that encapsulate PeerTube (i.e. docker, yunohost, etc.).

**Comment by rigelk** [comment]
To clarify @kontrollanten, I don't think an upgrade button replaces sysadmin tasks. YunoHost has that kind of "upgrade with just one button" but they have to update their package too, and their package maintainer has to do it manually too.

**Comment by c0llab0rat0r** [comment]
Is pulling a newer Docker tag a supported upgrade process?

**Comment by rigelk** [comment]
@c0llab0rat0r only `production*` tags are supported, but mind you it is just an upgrade target. The process involves backing up your volumes and linked services.

**Comment by c0llab0rat0r** [comment]
If I were running a Docker-based app in production or a pre-production test environment, I would prefer to use version-numbered tags to ensure stability with the edition/version deployed to that environment. For example, I would use `chocobozzz/peertube:v3.0.0-buster` instead of `chocobozzz/peertube:production-buster` - that way I have the opportunity to test a new version after it is released to Docker Hub but before it reaches my production setup.

Assuming my `docker-compose.yml` (or Kubernetes, or whatever) references `chocobozzz/peertube:v3.0.0-buster` - is it reasonable to assume I can simply change the tag to `chocobozzz/peertube:v3.1.0-buster` and restart the app - will `v3.1.0` know how to upgrade from `v3.0.0` - assuming no Postgres or Redis upgrade is required?

**Comment by rigelk** [comment]
You also have theses, tagged from production images, hence supported.

**Comment by rigelk** [comment]
You need to read release notes in any case for eventual manual maintenance. Though unlikely, this situation can occur.

**Comment by c0llab0rat0r** [comment]
> You also have these, tagged from production images, hence supported.

That's good to know.

Using [3.1.0](https://github.com/Chocobozzz/PeerTube/releases/tag/v3.1.0) as an example, I think the constraints are reasonable. It mentions migrations taking a long time, I'd assume that I could just update the tag and let it pull and run the new image for 3.1.0

Except that it also mentions Postgres requiring an upgrade from 9.x to something newer, which is reasonable, so I would upgrade its tag first, restart the app (to let Postgres migrate itself), and once that is ok, update the Peertube tag and restart, and let Peertube migrate. But having to upgrade Postgres (or Redis for that matter) first is also reasonable.

**Comment by c0llab0rat0r** [comment]
@kontrollanten,

Referencing `Continuous Delivery` vs `Continuous Deployment` - since _deployment_ may require an upgrade to Redis, Postgres, or another micro service dependency, I don't think you can get to that with a button inside the Peertube app.

You may have to do something like include a docker-compose.yml or Kubernetes equivalent or other equivalent into a DevOps pipeline that deploys that topology somewhere and runs automated validation on it - one of the 'tests' that needs to pass or fail before the automated deploy to production happens.

That process will be dependent on your infrastructure, and is external to PeerTube itself.

**Comment by kontrollanten** [comment]
> @kontrollanten,
> 
> Referencing `Continuous Delivery` vs `Continuous Deployment` - since _deployment_ may require an upgrade to Redis, Postgres, or another micro service dependency, I don't think you can get to that with a button inside the Peertube app.

I don't think it's impossible to solve, a lot of other software have solved it. But the goal with this issue is to clarify the needs, not to solve the details.

**Comment by Chocobozzz** [comment]
Closing this issue. I agree continuous deployment would be better than a classical 2/3 months release we have now, but unfortunately we don't have enough resources to do it for now.
