### ISSUE TITLE
In video view, word-wrap and margin between the comment div and the new video div

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#397]
* **PeerTube version or URL:** v1.0.0-beta.1 
* **Browser name/version:** Firefox, Chrome and Safari (latest versions) 

There is no margin between the description and comment div and the new video div.
It's not very aesthetic. ;) Apply a margin or padding left on the right div will fix this.

In the description div, the words are cut, the wordrap does not take into account the words.
`word-wrap: normal` will be probably better than `word-wrap: break-word` and an `text-align: justify` more aesthetic.

**Question:** I can do the merge request but I haven't found where are the styles for the UI in the source code.

**Comment by gegeweb** [comment]
Found how to fix this in the CSS configuration of the instance. (Yes I know what I'm doing! ;))
But It will be better by default.

**Comment by Chocobozzz** [comment]
Hi @gegeweb see https://github.com/Chocobozzz/PeerTube/blob/develop/.github/CONTRIBUTING.md to understand how to run a dev server etc

For the description styles see this file: https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/videos/%2Bvideo-watch/video-watch.component.scss#L201

**Comment by gegeweb** [comment]
OK, thanks.
I've already read the contributing guide. ;)

**Comment by gegeweb** [comment]
Merge request submited on Framagit.

**Comment by Chocobozzz** [comment]
Fixed by @gegeweb: https://github.com/Chocobozzz/PeerTube/commit/2a97572f072233410985da938b0821e1c537ac46. Thanks!
