### ISSUE TITLE
Sending high resolution live stream can bypass configured resolutions

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#3972]
**Describe the current behavior**

On a server that as resolutions 480p and 720p enabled for live transcoding, if the source is in 1080p the server also transcode in  1080p

This can lead to over consume CPU.

**Steps to reproduce:**

1. Configure max resolution to 720p for live videos
2. Send a 1080p stream
3. Play the video: 1080 is also available

**Describe the expected behavior**

Live video should only be transcoded to resolutions that are configured.

**Additional information**

This can lead in server denial of service: even if administrators have only allowed low resolutions, because of a small CPU, a malicious person could send 4K video, so that the CPU can't follow. 

* PeerTube instance:
  * version: 3.1.0

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/1030
