### ISSUE TITLE
previewPath into plugin server side main.js

### ISSUE THREAD

**Issue by geco** [Chocobozzz/PeerTube#3975]
Hello @Chocobozzz, 
there is a way (peertubehelpers or similar) by which I can get video previewPath from a plugin hook server side (aka main.js into plugin)?
I can get video object, that have only Thumbnails.
Otherwise i can invoke rest api, but i think it's not efficient, cause the code is already running inside peertube.

Thank you very much in advance
Best

**Comment by Chocobozzz** [comment]
Hello,

Yes, using `filter:api.video.get.result` hook. If you want an helper, `loadByUrl` or `loadByIdOrUUID` should do the job because the video contains an array of `Thumbnails`. Check `Thumbnail[i].type` to know if it's a preview or a thumbnail

See https://docs.joinpeertube.org/api-plugins
