### ISSUE TITLE
Dockerize Peertube impossibe to start peertube service

### ISSUE THREAD

**Issue by arnaudbagnis** [Chocobozzz/PeerTube#3977]
hello, I followed the steps described above : 
https://normandie-libre.fr/deployer-un-serveur-peertube-grace-a-docker/

and i have a error : 

> peertube@1.3.0 start /var/www/peertube
app_1    | > node dist/server
app_1    | 
app_1    | WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
app_1    | WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
app_1    | [localhost:9000] 2021-04-17 15:12:42.404 warn: Emailer is disabled so the contact form will not work.
app_1    | [localhost:9000] 2021-04-17 15:12:42.414 warn: Directory of tmp should not be in the production directory of PeerTube. Please check your production configuration file.
app_1    | [localhost:9000] 2021-04-17 15:12:42.415 warn: Directory of avatars should not be in the production directory of PeerTube. Please check your production configuration file.
app_1    | [localhost:9000] 2021-04-17 15:12:42.415 warn: Directory of videos should not be in the production directory of PeerTube. Please check your production configuration file.
app_1    | [localhost:9000] 2021-04-17 15:12:42.416 warn: Directory of streaming_playlists should not be in the production directory of PeerTube. Please check your production configuration file.
app_1    | [localhost:9000] 2021-04-17 15:12:42.416 warn: Directory of redundancy should not be in the production directory of PeerTube. Please check your production configuration file.
app_1    | [localhost:9000] 2021-04-17 15:12:42.417 warn: Directory of logs should not be in the production directory of PeerTube. Please check your production configuration file.
app_1    | [localhost:9000] 2021-04-17 15:12:42.417 warn: Directory of previews should not be in the production directory of PeerTube. Please check your production configuration file.
app_1    | [localhost:9000] 2021-04-17 15:12:42.418 warn: Directory of thumbnails should not be in the production directory of PeerTube. Please check your production configuration file.
app_1    | [localhost:9000] 2021-04-17 15:12:42.418 warn: Directory of torrents should not be in the production directory of PeerTube. Please check your production configuration file.
app_1    | [localhost:9000] 2021-04-17 15:12:42.419 warn: Directory of captions should not be in the production directory of PeerTube. Please check your production configuration file.
app_1    | [localhost:9000] 2021-04-17 15:12:42.419 warn: Directory of cache should not be in the production directory of PeerTube. Please check your production configuration file.
app_1    | [localhost:9000] 2021-04-17 15:12:42.825 error: Error in Redis client. {
app_1    |   "err": {
app_1    |     "stack": "Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)",
app_1    |     "message": "Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379",
app_1    |     "errno": "ECONNREFUSED",
app_1    |     "code": "ECONNREFUSED",
app_1    |     "syscall": "connect",
app_1    |     "address": "127.0.0.1",
app_1    |     "port": 6379
app_1    |   }
app_1    | }
app_1    | npm ERR! code ELIFECYCLE
app_1    | npm ERR! errno 255
app_1    | npm ERR! peertube@1.3.0 start: `node dist/server`
app_1    | npm ERR! Exit status 255
app_1    | npm ERR! 
app_1    | npm ERR! Failed at the peertube@1.3.0 start script.
app_1    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
app_1    | 
app_1    | npm ERR! A complete log of this run can be found in:
app_1    | npm ERR!     /var/www/peertube/.npm/_logs/2021-04-17T15_12_42_874Z-debug.log

I tried to modify the production.yml, then to test I wanted to put the production.yml in default.yml but the error remains

**Comment by rigelk** [comment]
hi @arnaudbagnis,

Please follow https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/docker.md, or contact the tutorial author for support regarding their tutorial steps.

**Comment by GaaH** [comment]
You need to make sure redis and peertube containers are on the same network. This can be donne by adding something like the following:

```
services:
  peertube:
    networks:
      - internal
  redis:
    networks:
      - internal
networks:
  internal:
```

Of course, I omitted most of the docker-compose content.
