### ISSUE TITLE
Calculate uuid based on original video and export original file

### ISSUE THREAD

**Issue by c0xc** [Chocobozzz/PeerTube#3980]
**Describe the problem to be solved**

I've noticed that people keep uploading the same video to multiple instances and each copy gets a new uuid. Then, the link or uuid for the first one is shared and used until the first Peertube instance goes down, at which point not only the links are dead but even the uuid can't be used to find the other copies.

**Describe the solution you would like:**

 I believe it would make Peertube much more decentralized if each uploaded copy got the same uuid, so that when one instance is down, the video can easily be found and watched on other instances.

This would obviously imply that, when a video is downloaded manually, the user should get the original video file, not the compressed version.

**Describe alternatives you have considered**  

If copies of the same video file don't get identical ids, some sort of central index would be needed to link and find them. Any central index is subject to manipulation. A decentral approach as outlined above should be more reliable, it should help to keep videos up when the original instance is gone or destroyed and it should also be slightly more censorship-resistant.

**Comment by rigelk** [comment]
hi @c0xc,

I get the appeal of your solution, but it creates problems of its own: there is an asymmetry in the ease of faking data, and checking it corresponds to the original video (which means downloading it and computing its hash/fingerprint). Moderation would usually be the answer, by banning instances faking data, but here it means using one or the other to directly play content regardless of origin, and potentially preventing playback of the desired source.

> This would obviously imply that, when a video is downloaded manually, the user should get the original video file, not the compressed version.

For this you need https://github.com/Chocobozzz/PeerTube/issues/733, which is not implemented, and probably wouldn't be systematic anyway.

Also, we are not just distributing video files but metadata too. How do you resolve merge conflicts?

**Comment by c0xc** [comment]
Are you saying it might be a problem if a video is uploaded to several sites but with different titles, possibly fake titles? I don't see a problem with that (actually, this is already possible). I don't expect metadata to be synced or merged. If a user wants to upload the same video to the same site again, the upload should probably fail and point to the existing video. As far as I can tell, that would be the only option as the uuid is already used in several places to identify a video (so creating a new video record pointing to the same file uuid wouldn't be possible I guess). If there's something wrong with that idea, another approach might be to introduce a new identifier which could also be used to find a video in the search or directly in the url and then make that identifier unique, like a hash.

**Comment by rigelk** [comment]
> Are you saying it might be a problem if a video is uploaded to several sites but with different titles, possibly fake titles? I don't see a problem with that […] I don't expect metadata to be synced or merged. If a user wants to upload the same video to the same site again, the upload should probably fail and point to the existing video.

Alright, let's put aside the option people might want full control of their own version of the video, and suppose this check prevents duplicates. What happens when an instance comes to the knowledge of yours (a new federation) and this instance has a list of videos which contains a conflicting video, with a similar id to yours? That conflict will happen, and then you have to resolve it as mentioned previously.

> another approach might be to introduce a new identifier which could also be used to find a video in the search bar or directly in the url and make that identifier unique, like a hash

You mean using the hash not as a uuid anymore, but as a complementary information? That might work, but then you would want to make a specific search UX for identical videos. That's not a common use case, is it?

**Comment by Chocobozzz** [comment]
Hello,

UUID must be unique per uploaded video. 

So what you may want is to prevent video uploads of already existing videos, which can be developed in a plugin.
See also https://github.com/Chocobozzz/PeerTube/issues/214

**Comment by c0xc** [comment]
> What happens when an instance comes to the knowledge of yours (a new federation) and this instance has a list of videos which contains a conflicting video, with a similar id to yours?
Good point. That would indeed be a conflict as uuids are supposed to be unique even across instances. It seems like deterministic ids aren't possible with the way uuids are used now. But it doesn't have to be the uuid...
> You mean using the hash not as a uuid anymore, but as a complementary information?
Yes - an additional identifier for the video itself.
> That might work, but then you would want to make a specific search UX for identical videos.
Yes, probably, although I was actually thinking of some kind of api call that could be used by a separate search tool to find _one_ specific video on "any" instance. Think about the example use case described above: Some documentary or something is uploaded to several instances, then instance A goes down or its admin makes a mistake and destroys the database or whatever; the video is not lost because it exists on other instances but only such a deterministic id would make it possible for viewers to find it on other instances and play it.

> So what you may want is to prevent video uploads of already existing videos
That's not really what I'm trying to say because that wouldn't make the ids deterministic. What I'm trying to suggest is a decentralized approach that would allow videos to be played even after one copy is lost, as long as at least another copy is still on some instance.

>  See also #214
At first glance, it seems to be about videos that are "visually nearly identical" which is more complicated, but on the other hand it could later be incorporated once a reliable algorithm has been found (which shouldn't match a 5sec clip to its 2h original btw., only if it's really the same video with different resolutions or cropped borders etc.). So it's interesting that others seems to have had similar ideas.

With what I'm suggesting, only identical video copies could be found, which may be step 1, but it would work across all Peertube sites as long as the import feature is used (and not if someone downloads the 240p toaster version of a 1080p movie and then wants to reupload it but that's not something that can be fixed by software, it should be obvious that the highest quality version should be loaded and used as input). Again, video X is uploaded to instance A, then imported on instance B and C. Instance A goes down but with the deterministic identifier, the video could still be found and played.
