### ISSUE TITLE
Download information does not always show correct information

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#3981]
**Describe the current behavior**

When viewing the download information of a video and switching between resolutions it only displays the relevant information 25% of the time. The remaining 75% of the time it's stuck showing the 1080p download information.

This varies by individual video.

This has been a problem for a long time now. It is not a new issue.

I'm attaching some gif's to show the problem.

![D1K5gq1WSH](https://user-images.githubusercontent.com/7935624/115129561-e70bf580-9f9b-11eb-91da-9018464c68e5.gif)

**Steps to reproduce:**

1. View download information
2. Switch from 1080p to 720p or 480p

**Describe the expected behavior**

Information should always be updated and shown.

![htctPtrtuV](https://user-images.githubusercontent.com/7935624/115129577-1d497500-9f9c-11eb-90cd-aa26d4a980c6.gif)

**Additional information**

* PeerTube instance:
  * URL: vidrot.com
  * version: 3.1.0
  * NodeJS version: 15
  * Ffmpeg version: 4.2.2

* Browser name, version and platforms on which you could reproduce the bug: Latest firefox with ublock and bitwarden

**Comment by kontrollanten** [comment]
Thanks for reporting! This is solved in https://github.com/Chocobozzz/PeerTube/pull/3890/commits/029f322c4afdcc2aace91dc2d0d8c917927c9bb8 and will be released with the next version.
