### ISSUE TITLE
Copy video URL at the current time does not work for embedded playlists

### ISSUE THREAD

**Issue by TROMsite** [Chocobozzz/PeerTube#3983]
**Describe the current behavior**
Right click a video, then copy video at the current time. Paste it into a new tab. Does not work. This happens for embedded playlists. Here is an example https://videos.trom.tf/video-playlists/watch/9d1478a9-972f-4f4e-8376-74e3b5ec86c0?start=17m26s

**Steps to reproduce:**

1. Right click a video, then copy video at the current time.
2. Paste it into a new tab. Does not work. 

**Describe the expected behavior**
Should show the video at that current time.

**Additional information**

    PeerTube instance: https://videos.trom.tf
        URL: https://videos.trom.tf
        version: 3.1.0

    Browser name, version and platforms on which you could reproduce the bug: Firefox

**Comment by SimplyCorbett** [comment]
I can also replicate this issue.

**Comment by TROMsite** [comment]
Actually if you do the same for any embedded playlist and simply copy the url of a video from the playlist (without timeframe) it again does not work. It jumps to the first video in the playlist. For example this is the 16th video of a playlist https://videos.trom.tf/video-playlists/watch/974c14d7-00c6-4178-9d32-84db2c640f66 - I copy pasted the link from the embedded player itself. But if you click it, it goes to the first position in the playlist. 

Looking closely what it does it copies the link of the first video regardless where in the playlist you click to copy the url. This is the URL for the 15th video https://videos.trom.tf/video-playlists/watch/974c14d7-00c6-4178-9d32-84db2c640f66 as you can see it is the same...

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/e8bb5b6b3a1e4c2aeab368f01cc5092d8478b893
