### ISSUE TITLE
Combine URL and QR Code Share Tabs

### ISSUE THREAD

**Issue by techboyg5** [Chocobozzz/PeerTube#3985]
Because the URL and QR Code share tabs have the same options, I think that they can be combined into a single tag like this:

![Screenshot 2021-04-18 4 15 15 PM](https://user-images.githubusercontent.com/63317676/115161141-8cd56800-a061-11eb-879d-1011f8267d66.png)

**Comment by Chocobozzz** [comment]
Hello,

We preferred to put it in another tab because the QR code takes a lot of space even though it's not widely used (compared to the classic URL).
