### ISSUE TITLE
Import from YouTube is not using the highest quality available

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#3987]
I'm comparing two video imports from the same URL. One is downloaded through peertube, another is downloaded with youtube-dl and uploaded manually.

URL: https://www.youtube.com/watch?v=eByKuI7_F7g

Peertube URL import: https://vidrot.com/videos/watch/cd93a375-9655-45a1-a0d8-9430af53db97

youtube-dl upload (4k, please use 1080p option to compare): https://vidrot.com/videos/watch/ea61d8d8-3e9c-46d6-9dbb-2d7f0c356e80

PeerTube instance:

    URL: vidrot.com
    version: 3.1.0
    NodeJS version: 15
    Ffmpeg version: 4.2.2

VOD Setup:

480p, 1080p allowed, the rest disabled.

Steps to reproduce:

1) Import URL
2) Upload 4k version of the same clip downloaded manually with youtube-dl
3) Compare bitrate of both 1080p versions in peertube. 2) is 1Mbps higher then 1)

Expected behavior:

Bitrate should be the same on both clips.

**Comment by rigelk** [comment]
hi @SimplyCorbett,

Could you fill the issue template? I don't see any problem description in your issue.

**Comment by SimplyCorbett** [comment]
@rigelk Tried to make this more clear.

I think what's going on is if you have 1080p selected but 4k disabled peertube will grab the 1080p youtube video. The 1080p youtube video has more compression then the 4k version and so the final product on peertube is more watered down.

**Comment by rigelk** [comment]
@SimplyCorbett we changed the import selector to only import the video matching the highestd resolution selected, so this is only to be expected. It allows faster imports and transcode, especially for small instances that only selected small resolutions. As for the "watered down" effect, it is also due to YT being the source, and not the original file.

**Comment by SimplyCorbett** [comment]
@rigelk Right, I'm just pointing out the 4k file when transcoded down to 1080p is 1Mbps higher/double the bitrate.

Not sure if a faster transcode time is worth the quality loss, but that's my opinion. Any chance you could make this optional on the admin backend?

**Comment by scanlime** [comment]
transcoding from a low bit rate source should not be the default, imo. peertube is pretty hard on folks who are trying to keep their video quality high.

**Comment by rigelk** [comment]
> Not sure if a faster transcode time is worth the quality loss, but that's my opinion. Any chance you could make this optional on the admin backend?

Sure; and as @scanlime pointed most people favor quality over VPS load.

**Comment by SimplyCorbett** [comment]
Any progress on this?

**Comment by mj-saunders** [comment]
Looking at `getYoutubeDLVideoFormat` in `helpers/youtube-dl/youtube-dl-cli.js`, am I right in saying that if no resolutions are set in the `VOD Transcoding` web ui config, that the max resolution is in fact 720p, and not the maximum resolution available?

According the the `VOD` config page, `The original file resolution will be the default target if no option is selected.`

**Comment by mj-saunders** [comment]
Can confirm that changing the hardcoded `720` value in `getYoutubeDLVideoFormat` to `1080` does seem to have an effect.

Without it, `720p` was the max resolution I could get, regardless of whether `1080p` was selected in `VOD` settings, or if nothing was selected at all (and the original source was `1080p`).

I would have thought that setting in the config would have been enough, but apparently not. I don't quite understand why.

**Comment by Chocobozzz** [comment]
Hello,

If the new option [transcoding.always_transcode_original_resolution](https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L417) is set to `true`, we now import the best available resolution.

**Comment by SimplyCorbett** [comment]
@Chocobozzz testing on 4.2.2...7804e577d (fresh install) with a fresh yt-dlp, nodejs 16 and ffmpeg 5.0.1.

It does work (and keep) the original resolution. So, yay! Any chance you can add the option to remove the original resolution once transcoding has finished?

The idea was that since youtube starved bitrate on lower resolution videos that if your instance was limited to 1080p if a 1440p or 4k version was available it would transcode off the highest resolution possible, but your instance would still only have the 1080p resolution available for play.

Maybe I didn't explain that right originally. Sometimes I'm dumb like that.

**Comment by vid-bin** [comment]
As an example youtube has a 1440p version with 10.5Mbps bitrate and a 1080p with 3.5Mbps. I want peertube to grab the 1440p (higher bitrate) version and then transcode the 1080p video from that. I don't want it to waste CPU cycles transcoding the 1440p version (which with VP9 will take hours).

By using 1440p as the base resolution the bitrate is doubled on the transcoded 1080p video.

**Comment by vid-bin** [comment]
For anyone who wants higher quality 1080p transcodes (because youtube starves 1080p bitrate):

In server/helpers/youtube-dl/youtube-dl-cli.ts:

```
    if (!useBestFormat) {
      const resolution = enabledResolutions.length === 0
        ? VideoResolution.H_720P
        : Math.max(...enabledResolutions)

      result = [
        `bestvideo[vcodec^=avc1][height=${resolution}]+bestaudio[ext=m4a]`, // case #1
        `bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=${resolution}]+bestaudio`, // case #2
        `bestvideo[vcodec^=avc1][height<=${resolution}]+bestaudio[ext=m4a]` // case #
      ]
    }
```

Change this to:

```
    if (!useBestFormat) {
      const resolution = enabledResolutions.length === 0
        ? VideoResolution.H_720P
        : Math.max(...enabledResolutions)

      result = [
        `bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=1440]+bestaudio`, // prefer 1440p downloads  with high quality VP9
        `bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=${resolution}]+bestaudio`, // prefer high quality VP9 over AVC1
        `bestvideo[vcodec^=avc1][height=${resolution}]+bestaudio[ext=m4a]`, // case #1
        `bestvideo[vcodec^=avc1][height<=${resolution}]+bestaudio[ext=m4a]` // case #
      ]
    }
```
