### ISSUE TITLE
HLS not compatible with ffmpeg 4.4

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#3990]
**Describe the current behavior**

HLS videos do not play after transcoding

**Steps to reproduce:**

1. Install ffmpeg 4.4
2. Import a youtube video with HLS only. Selected resolutions of 480p and 1080p.
3. Try playing, get stuck with a loading circle

**Describe the expected behavior**

Videos transcode and play correctly

**Additional information**

* PeerTube instance:
  * URL: vidrot.com
  * version: 3.1.0
  * NodeJS version: 15
  * Ffmpeg version: 4.4

* Browser name, version and platforms on which you could reproduce the bug: firefox with ublock and bitwarden

**Comment by scanlime** [comment]
This might be #3657 coming back

**Comment by SimplyCorbett** [comment]
Will this be fixed with the upgraded hls.js v1.0 player?

**Comment by Chocobozzz** [comment]
This is a bug in ffmpeg. See https://trac.ffmpeg.org/ticket/9205 & https://trac.ffmpeg.org/ticket/9193

**Comment by SimplyCorbett** [comment]
This appears to be fixed in the git version of ffmpeg. Closing!

**Comment by Chocobozzz** [comment]
Just reopening to track a new ffmpeg stable version and notify people that subscribed to the issue :)

**Comment by Ta180m** [comment]
> Hi. I had the same issue, and fixed it by replacing ffmpeg 4.4 with ffmpeg 4.1 ( by clicking "old release" in this page for linux https://johnvansickle.com/ffmpeg/ )
> 
> Then removed all HLS playlist (you may want to remove only the broken ones) with `rm -f /var/www/peertube/storage/streaming-playlists/hls/*` (dangerous command) and asked for the reencoding of all HLS (you may want to reencode only the broken ones)
> 
> ```
> cd /var/www/peertube/peertube-latest
> for uuid in $(ls /var/www/peertube/storage/videos/|grep 240|sed -e 's/-240.mp4//') ; do echo $uuid; NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run create-transcoding-job -- --generate-hls -v  $uuid ;  done```
> ```

On Arch Linux, I compiled ffmpeg with [this patch](https://patchwork.ffmpeg.org/project/ffmpeg/patch/20210501071234.78554-1-liuqi05@kuaishou.com/). To fix the broken playlists, running this as root fixed it: 
```
rm -r /var/lib/peertube/storage/hls/*
cd /usr/share/webapps/peertube
for uuid in $(ls /var/lib/peertube/storage/videos/|grep 1080|sed -e 's/-1080.mp4//') ; do echo $uuid; NODE_CONFIG_DIR=/etc/peertube NODE_ENV=production npm run create-transcoding-job -- --generate-hls -v  $uuid ;  done
```

**Comment by KokaKiwi** [comment]
It seems the latest ffmpeg release (`4.4.1`) from 9 days ago (2021-10-23) includes the [fix](https://git.videolan.org/?p=ffmpeg.git;a=commit;h=973899054244a7239f79453e5f4bcff235b8f6e4)
Now i suppose it's a matter of it being available downstream on distros and stuff

**Comment by Chocobozzz** [comment]
Thanks @KokaKiwi I missed that release. I'll test it when it will be available on Arch.

**Comment by Ta180m** [comment]
ffmpeg 4.4.1 is now in [Arch official repos](https://archlinux.org/packages/extra/x86_64/ffmpeg/). I haven't had a chance to test it yet but I expect it'll work.

**Comment by Chocobozzz** [comment]
I can confirm 4.4.1 is correctly working. Thanks!
