### ISSUE TITLE
Instance custom picture/banner

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#3991]
Hi,

Is anything like an instance custom picture/banner planned to be implemented ?

I think something like Mastodon does on the instance home.

The picture could be used up to the _short description_ instead of the instance name on signup - login - about page ?

Plus, I may be wrong but, it seems lighter to implement than a full UI admin logo / favicon / PWA icons as requested here : https://github.com/Chocobozzz/PeerTube/issues/2752

What I mean, is the real need of the issue 2752 is to customize the instance according to the visual identity of the owner / maintainer. What's better than a picture for a visual instead of changing all the UX/UI that can be properly made with theme/plugins?

![image](https://user-images.githubusercontent.com/1877318/115275341-f462e480-a141-11eb-94cf-0c94d64e2b19.png)

**Comment by SimplyCorbett** [comment]
Are there any examples of implementing this on a live site?
