### ISSUE TITLE
Add support for more transcoding profiles based on resolution

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#3994]
I'm using the following transcoding profile:

```
"encoderName": "libvpx-vp9",
"profileName": "test",
"outputOptions": ["-crf 25", "-b:v 4500k", "-tile-columns 2", "-tile-rows 2", "-cpu-used 2", "-row-mt 1", "-g 999"]
```

This is a good profile for 1080p even up to 60fps. But when it comes to 1440p60 and above the bitrate is too low.

It would also be nice to restrict 480p bitrates further.

**Comment by emansom** [comment]
The player needs to take dropped frames into account as well for this to fully function across multiple encoding formats (VP9, AV1 vs H.264).

Most devices in use now don't ship with the required hardware and software configuration for full accelerated VP9 and AV1 video decode, leading to very high CPU usage and dropped frames.

On these devices it's better to serve them H.264 and switch formats quickly when dropped frames are detected.

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/4285
