### ISSUE TITLE
Videos are delayed in processing

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#3995]
Hi!

So this is a weird one. If I do videos individually they work, but the second I queue them up (long queue) from youtube I run into this issue with my custom video profile.

This is the only error I see:

```
info[4/20/2021, 7:44:35 PM] Creating torrent /var/www/peertube/storage/torrents/c829cfd8-d6ec-4bc5-a631-312e253c5aa6-1080.torrent.

info[4/20/2021, 7:44:35 PM] No transcoding jobs created for video c829cfd8-d6ec-4bc5-a631-312e253c5aa6 (no resolutions).

info[4/20/2021, 7:44:35 PM] Processing video file in job 1877. 
```

Basically, ffmpeg will finish but the video won't show up anywhere and says its still waiting for transcoding.

My resolutions are 480p and 1080p. **If I disable 480p and restart peertube every video that runs into this issue suddenly appears.**

In one instance I had 40+ appear all at once.

**Steps to reproduce:**

1. Install custom profile:

```
{
  "vod": [
    {
      "encoderName": "libopus",
      "profileName": "test",
      "outputOptions": ["-b:a 160k", "-strict -2"]
    },
    {
      "encoderName": "libvpx-vp9",
      "profileName": "test",
      "outputOptions": ["-crf 30", "-b:v 5000k", "-tile-columns 2", "-tile-rows 2", "-cpu-used 2", "-row-mt 1", "-g 999"]
    }
  ],

  "live": []
}

{
  "vod": [
    {
      "encoderName": "libopus",
      "streamType": "audio",
      "priority": 1000
    },
   {
      "encoderName": "libvpx-vp9",
      "streamType": "video",
      "priority": 1000
    }
  ],

  "live": [ ]
}
```

2. Select 480p and 1080p as your resolution. Have multiple transcoding jobs (I have 5 jobs at 4 threads each). Restart peertube.
3. Queue up various youtube videos ranging from 5 minutes to 40 minutes. My queue in this instance is around 40+.
4. Once it finishes transcoding some videos and the ffmpeg processes cycle, you'll see the videos don't appear as finished on peertube. If you deselect 480p in the admin menu and restart peertube all of those videos will suddenly appear as 1080p only.

**Describe the expected behavior**

Videos finish transcoding with no issue.

**Additional information**

* PeerTube instance:
  * URL: vidrot.com
  * version: 3.1.0
  * NodeJS version: 15
  * Ffmpeg version: 4.3.2

* Browser name, version and platforms on which you could reproduce the bug: Firefox with ublock and bitwarden

**Comment by SimplyCorbett** [comment]
Also just to add to this it does not happen with the regular default profile.

**Comment by rigelk** [comment]
@SimplyCorbett for the record, could you explain what lead to the resolution of your issue?

**Comment by SimplyCorbett** [comment]
> 
> 
> @SimplyCorbett for the record, could you explain what lead to the resolution of your issue?

I'm still experimenting with this. 3 transcoding jobs seem to work fine, seems to be a problem with 5.

Best guess? CPU is pegged with 5 and it can't process the videos until the youtube queue is done.

But I haven't done enough research and may have made this ticket prematurely. Don't want to clog up github with something that might end up being user error.

**Comment by SimplyCorbett** [comment]
@rigelk Just curious. When peertube finishes with a transcode does it need to make a second ffmpeg job to process and publish the video?

Not talking about 480p, just publishing the 1080p version that finishes transcoding.

If that is the case how is ffmpeg priority handled with multiple jobs going at the same time?

**Comment by rigelk** [comment]
@SimplyCorbett no, a transcode job makes the resolution associated to a video available immediately ; if you checked the "publish after it is transcoded" and it is the first resolution, it will be published in the same job.

**Comment by SimplyCorbett** [comment]
Alright so this is a bug then and I'll reopen this.

![firefox_JhwpAMZ2A0](https://user-images.githubusercontent.com/7935624/115605019-e4104e00-a296-11eb-976c-52b83b9bab5d.png)

ffmpeg video ending in 454a (solid state drives) is processing here.

![firefox_7K5rEeQbN1](https://user-images.githubusercontent.com/7935624/115605076-f4282d80-a296-11eb-8dfe-4f962628a748.png)

ffmpeg process finishes, video is still marked as being transcoded.

**Comment by SimplyCorbett** [comment]
The video is finally up. It only happened once the active transcoding jobs dropped from 5 to 3.

**Comment by SimplyCorbett** [comment]
It turns out if I refreshed a few more times there were another couple of videos loaded in (screenshot). Hopefully the below can help you guys figure out what's going on.

![cHB3AuUM9g](https://user-images.githubusercontent.com/7935624/115638815-f191fc00-a2c7-11eb-84ab-8b8475e8a6f5.gif)

![firefox_Kzmi0GT08d](https://user-images.githubusercontent.com/7935624/115638839-01a9db80-a2c8-11eb-8839-11bfc79eaaa5.png)

**Comment by SimplyCorbett** [comment]
I've experimented with this some more and even with a single transcode going the issue still happens (~1500% CPU usage, 24 cores. Plenty of spare CPU)

So this is either a bug with the custom encoder or peertube can't publish videos when the CPU is under load. I doubt it's the latter because peertube still loads pages and plays videos just fine. It also imports videos just fine.

To reiterate the problem:

While transcoding videos new videos are not published until the youtube queue finishes. This is problematic for large queues.

I'm actually not sure if this problem happens with user-uploaded videos but I'd assume it does.

**Comment by Chocobozzz** [comment]
I think the issue comes from the fair transcoding job queue introduced in 3.1. We publish a video after the optimizer job + 1 resolution. Since you have other `optimizer` jobs in your queue that have an higher priority, the first new resolution job is delayed (and so does for the publication).

With https://github.com/Chocobozzz/PeerTube/commit/a6e37eebfbef9aef91e35173ed799afb6c4a288b, optimizer and new resolutions jobs have now the same priority (should not hurt the job queue "fairness"

**Comment by SimplyCorbett** [comment]
This bug still hasn't been fixed in the latest GIT.

Which is fine really, but just letting you know.

**Comment by SimplyCorbett** [comment]
It's actually worse now. Instead of the videos showing up when I restart peertube they now only show up once the entire queue has been processed.

If there are 40 videos waiting to be processed all of them must be transcoded before a single one shows up in the menu, regardless of restarting the instance.

**Comment by SimplyCorbett** [comment]
@Chocobozzz this should probably be reopened. As an example I went to bed with ~100 videos queued for AV1 encoding.  Woke up, 40 are done but none are appearing even after restarting the instance because there are still videos in the queue waiting for transcoding.

**Comment by SimplyCorbett** [comment]
I'm having a mixed experience here.

If I import 20 videos that are 1080p, they wont show up at all until all 20 have finished transcoding @ 1080p. But once that's done the 480p/720p versions show up one at a time directly after processing.

So this bug is partly fixed. Just need to figure out why the initial encoding requires the entire queue to be finished before the videos are visible.
