### ISSUE TITLE
Transfer followers to another channel

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3999]
We'd like to transfer everything connected to account A to account B. The videos can be transferred via current functionality. But for the followers we hope we can achieve it by doing operations directly in the DB. Should it be enough to change the `targetActorId` in `actorFollow`? Can you see any obvious reasons why this wouldn't work?

**Comment by spacekookie** [comment]
This feels related to #1603 and would generally be super useful for content creators to have more control over how their video pages are layed out. I don't know what exactly is on the v4 roadmap, but maybe it's something that could be worked on?

**Comment by Chocobozzz** [comment]
> The videos can be transferred via current functionality. But for the followers we hope we can achieve it by doing operations directly in the DB.

Hello,

You can do it to change followers of local users, but it won't work for remote users.
