### ISSUE TITLE
Kodi teamwork

### ISSUE THREAD

**Issue by Matthias84** [Chocobozzz/PeerTube#4]
Hi, the www.kodi.tv center community has already some experience with torrent movie playback (popcorntime, pulsar, quasar, ...). It might  be useful to exchange the idea of decentralized videoplatform and to add features to interexchange the media?

**Comment by Chocobozzz** [comment]
Hi,

It's a very good idea. 

But I just need a little bit more time before that in order to make some "real world" tests.
