### ISSUE TITLE
Where is Template mails to help traslate on weblate

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#4001]
Hello there

In which of these options are the email templates (registration, alerts, etc.) to help the translation into Spanish
https://weblate.framasoft.org/projects/peertube/#components

**Comment by kontrollanten** [comment]
Hello. I don't think it's possible to translate them until https://github.com/Chocobozzz/PeerTube/issues/912 is solved.

**Comment by rigelk** [comment]
Closing as mentioned @kontrollanten
