### ISSUE TITLE
Dropdown menu for videos not visible on new UI profile page

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#4004]
This may be the container configuration of the video's dropdown menu on pubic profile page, we just can't access to the full options of this dropdown inside the carousel's video thumbnail container.

![image](https://user-images.githubusercontent.com/1877318/115792664-f68ba400-a3ca-11eb-98cd-b100e13522cd.png)

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/27b785dcfc4163b6ee3e1589e72e21667ef4bf70
