### ISSUE TITLE
Unable to load local videos

### ISSUE THREAD

**Issue by TROMsite** [Chocobozzz/PeerTube#4005]
**Describe the current behavior**
See this https://videos.trom.tf/video-channels/trom/videos - no videos work. I am using Yunohost and upgraded peertube from one minor version to another. Stopped working. Then fully restored peertube and I get this issue. I thought to post here in case the ynh dev may not respond and because it may be a simple fix. Other videos work, but not local ones. Works to download local ones tho.

* PeerTube instance: https://videos.trom.tf
  * URL: https://videos.trom.tf
  * version: 3.1.0

**Comment by Chocobozzz** [comment]
There is something wrong with your instance: the server returns 403 for video files. Please use yunohost support.
