### ISSUE TITLE
Comparison with distributed services

### ISSUE THREAD

**Issue by ShalokShalom** [Chocobozzz/PeerTube#401]
So what is the benefit of PeerTube compared to something fully and true distributed such as d.tube?

**Comment by rigelk** [comment]
PeerTube in no way claims to be a distributed service. Other benefits range from community-building through federation, to usage of thin standard protocols and no incentive-driven content creation, to name a few.

Then you might want to double-check which parts of Dtube are actually not distributed _at the moment_, like its development or parts of its infrastructure… Talking more broadly about blockchains, there are ongoing discussion as to allow their light integration as plugins, while still respecting [the content creation dynamic so as to not modify it](https://github.com/Chocobozzz/PeerTube/blob/develop/FAQ.md#what-is-creation-dynamic-and-why-not-modify-it).

**Comment by ShalokShalom** [comment]
Git is a distributed service: https://github.com/dtube

Thanks for your kind answer :)

**Comment by rigelk** [comment]
Git doesn't automatically make a project collaborative, and DTube still lacks proper _source_ (rather than uglified code) to make it modifiable.

**Comment by ShalokShalom** [comment]
I see
