### ISSUE TITLE
Change encoding resolution order

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#4013]
Instead of encoding highest quality first can we change this to the lowest quality first?

With VP9/AV1 encoding 240p/360p takes a very small amount of time. But higher resolutions take longer.

**Comment by Chocobozzz** [comment]
Hello,

You have the order here: https://github.com/Chocobozzz/PeerTube/blob/develop/server/helpers/ffprobe-utils.ts#L205
What job type are you talking about? (`new-resolution-to-webtorrent`, `new-resolution-to-hls` ...)?

**Comment by SimplyCorbett** [comment]
Using HLS my instance always starts transcoding the highest resolution first and the lowest resolution last. I'm proposing to reverse the order so videos are available sooner.

But if I'm reading the above right that should already be happening so maybe this is a bug.

**Comment by violoncelloCH** [comment]
I see the video's resolutions being transcoded in the following order:
480, 360, 720, 240, 1080, 1440, 2160
so it seems to work as intended in my case...

**Comment by Chocobozzz** [comment]
@SimplyCorbett Do you still have the bug?

**Comment by SimplyCorbett** [comment]
@Chocobozzz I'll get around to testing the latest git later today or tomorrow and let you know!

**Comment by SimplyCorbett** [comment]
@Chocobozzz Yes, the bug still exists. 1080p is transcoded first on the latest git of peertube.

**Comment by SimplyCorbett** [comment]
Three new videos all transcoding at 1080p first.

![1080p](https://user-images.githubusercontent.com/7935624/142728927-641495aa-f1d1-4f4b-9246-cbde80c51fd8.png)

**Comment by Chocobozzz** [comment]
What was the source resolution? 1080?

**Comment by SimplyCorbett** [comment]
Yes, 1080p youtube imports.

**Comment by Chocobozzz** [comment]
We must transcode the original resolution first because we're not sure the video can be played in the HTML video container. Then the order should be the same than in https://github.com/Chocobozzz/PeerTube/issues/4013#issuecomment-873624005

**Comment by SimplyCorbett** [comment]
Makes sense.
