### ISSUE TITLE
TLS setting not respected for Postgres connection

### ISSUE THREAD

**Issue by LasersAreGreat** [Chocobozzz/PeerTube#4014]
I'm trying to use a remote postgres database, and that database requires that TLS be used for all connections.  I edited the production.yaml file but TLS is still not being used.

The relevant portion of my production.yaml file:

database:
  hostname: 'private-db-postgresql-nyc3-48168-do-user-24554147-0.b.db.ondigitalocean.com'
  port: 25060
  ssl: required
  suffix: ''
  username: 'peertube'
  password: '123123123123'
  pool:
    max: 50

But the logs show Peertube is not attempting the connection with TLS as it says "SSL off", and so the connection fails:

Apr 24 21:54:12 peertube peertube[42728]: > peertube@3.1.0 start
Apr 24 21:54:12 peertube peertube[42728]: > node dist/server
Apr 24 21:54:15 peertube peertube[42740]: [peertube.newsocial.tech:443] 2021-04-24 21:54:15.087 error: Unable to connect to PostgreSQL database. {
Apr 24 21:54:15 peertube peertube[42740]:   "err": {
Apr 24 21:54:15 peertube peertube[42740]:     "stack": "SequelizeConnectionError: no pg_hba.conf entry for host \"10.108.0.2\", user \"peertube\", database \"peertube\", SSL off\n    at Client._connectionCallback (/var/www/peertube/versions/peertube-v3.>
Apr 24 21:54:15 peertube peertube[42740]:     "message": "no pg_hba.conf entry for host \"10.108.0.2\", user \"peertube\", database \"peertube\", SSL off",
Apr 24 21:54:15 peertube peertube[42740]:     "name": "SequelizeConnectionError",
Apr 24 21:54:15 peertube peertube[42740]:     "parent": {
Apr 24 21:54:15 peertube peertube[42740]:       "stack": "error: no pg_hba.conf entry for host \"10.108.0.2\", user \"peertube\", database \"peertube\", SSL off\n    at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v3.1.0/node_modules/pg>
Apr 24 21:54:15 peertube peertube[42740]:       "message": "no pg_hba.conf entry for host \"10.108.0.2\", user \"peertube\", database \"peertube\", SSL off",
Apr 24 21:54:15 peertube peertube[42740]:       "length": 152,
Apr 24 21:54:15 peertube peertube[42740]:       "name": "error",
Apr 24 21:54:15 peertube peertube[42740]:       "severity": "FATAL",
Apr 24 21:54:15 peertube peertube[42740]:       "code": "28000",
Apr 24 21:54:15 peertube peertube[42740]:       "file": "auth.c",
Apr 24 21:54:15 peertube peertube[42740]:       "line": "495",
Apr 24 21:54:15 peertube peertube[42740]:       "routine": "ClientAuthentication"
Apr 24 21:54:15 peertube peertube[42740]:     }
Apr 24 21:54:15 peertube peertube[42740]:   }
Apr 24 21:54:15 peertube peertube[42740]: }

I've tried values of "ssl: required" and "  ssl: on" and "  ssl: true" in the production.yaml file with no success.

**Comment by LasersAreGreat** [comment]
As a workaround, adding the line:

Environment=PGSSLMODE=require

to /etc/systemd/system/peertube.service fixed things.

**Comment by Chocobozzz** [comment]
Hello,

Thanks for the issue. We fixed it in https://github.com/Chocobozzz/PeerTube/commit/6bc672da815cf7315abd5b5a6267a07b9ad2345e. See also https://framacolibri.org/t/peertube-3-1-0-cant-connect-to-remote-ssl-postgresql-instance/11745
