### ISSUE TITLE
Embedded videos trigger 429 TOO MANY REQUESTS

### ISSUE THREAD

**Issue by fabiomaschi** [Chocobozzz/PeerTube#4016]
**Describe the current behavior**
We are embedding several (>15) videos into a single page on an external website, and peertube responds with  `HTTP 409: TOO MANY REQUESTS` for several requests.

<img width="578" alt="Screenshot 2021-04-20 at 13 42 36" src="https://user-images.githubusercontent.com/36470987/115998806-ee0cb680-a5e0-11eb-9447-3b1889d7b088.png">
<img width="697" alt="Screenshot 2021-04-20 at 13 42 08" src="https://user-images.githubusercontent.com/36470987/115998811-efd67a00-a5e0-11eb-91be-3d5d940f9953.png">

**Steps to reproduce:**

1. Create a dummy HTML page
2. Embed any 20 videos from the same instance
3. Open the page

**Describe the expected behavior**
A larger number of embedded videos (thumbnails and video player) should be properly loaded without triggering error 429. Maybe we could try to reduce the number of calls (e.g., I see captions being loaded before playing the video)?

**Additional information**
I've tried removing all `limit_rate` and similar modules from `/etc/nginx/sites-available/peertube`, but the behaviour persists. I also tried to add [ngx_http_limit_req_module](https://www.nginx.com/blog/rate-limiting-nginx/), [ngx_http_limit_conn_module](https://nginx.org/en/docs/http/ngx_http_limit_conn_module.html) and follow [this guide](https://www.nginx.com/blog/rate-limiting-nginx/), but I couldn't manage to solve the issue (either by increasing the limit, either by just removing any limit protection).

Question: is there any other component that could raise 429 error code other than NGINX?

* PeerTube instance:
  * URL: https://video.igem.org
  * version: 3.1.0
  * NodeJS version: v14.16.1

Thank you

**Comment by Chocobozzz** [comment]
Hello,

Rate limit is defined in peertube config: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L11

> (e.g., I see captions being loaded before playing the video)?

It should be fixed in the next release (we'll lazy load captions)

**Comment by rasos** [comment]
embedded videos have a post to the api endpoint, so we had to increase the value for api to 500 for a web page with many videos embedded
