### ISSUE TITLE
Problem restoring database

### ISSUE THREAD

**Issue by Elrondo46** [Chocobozzz/PeerTube#4018]
I try to restore but I have this:

pg_restore: [programme d'archivage (db)] Erreur à partir de l'entrée TOC 3192 ; 1259 17205 INDEX actor_preferred_username_server_id peertube
pg_restore: [programme d'archivage (db)] could not execute query: ERREUR:  n'a pas pu créer l'index unique « actor_preferred_username_server_id »
DÉTAIL : La clé ("preferredUsername", "serverId")=(norzfunny, 10) est dupliquée.
    La commande était : CREATE UNIQUE INDEX actor_preferred_username_server_id ON public.actor USING btree ("preferredUsername", "serverId");

pg_restore: [programme d'archivage (db)] Erreur à partir de l'entrée TOC 3195 ; 1259 17204 INDEX actor_url peertube
pg_restore: [programme d'archivage (db)] could not execute query: ERREUR:  n'a pas pu créer l'index unique « actor_url »
DÉTAIL : La clé (url)=(https://peertube.fr/video-channels/norzfunny) est dupliquée.
    La commande était : CREATE UNIQUE INDEX actor_url ON public.actor USING btree (url);

pg_restore: [programme d'archivage (db)] Erreur à partir de l'entrée TOC 3223 ; 1259 17340 INDEX tag_name peertube
pg_restore: [programme d'archivage (db)] could not execute query: ERREUR:  n'a pas pu créer l'index unique « tag_name »
DÉTAIL : La clé (name)=(9/11) est dupliquée.
    La commande était : CREATE UNIQUE INDEX tag_name ON public.tag USING btree (name);
    

How to solve this problem

**Comment by Chocobozzz** [comment]
Hello,

Try the following SQL commands to remove duplicated data:

```
DELETE FROM "actor" v1 USING (SELECT MIN(id) as id, "preferredUsername", "serverId" FROM "actor" GROUP BY "preferredUsername", "serverId" HAVING COUNT(*) > 1 AND "serverId" IS NOT NULL) v2 WHERE v1."preferredUsername" = v2."preferredUsername" AND v1."serverId" = v2."serverId" AND v1.id <> v2.id;
```

```
DELETE FROM "actor" v1 USING (SELECT MIN(id) as id, "url" FROM "actor" GROUP BY "url" HAVING COUNT(*) > 1) v2 WHERE v1."url" = v2."url" AND v1.id <> v2.id;
```

```
DELETE FROM "tag" v1 USING (SELECT MIN(id) as id, "name" FROM "tag" GROUP BY "name" HAVING COUNT(*) > 1) v2 WHERE v1."name" = v2."name" AND v1.id <> v2.id;
```

**Comment by Elrondo46** [comment]
I fixed it removing all tags manually in the sql file. 
Now instance is fully operational... I notice I have some instance have white miniatures

https://peertube.pcservice46.fr
