### ISSUE TITLE
Going back in the browser page history from a video yields undefined pagination

### ISSUE THREAD

**Issue by Phyks** [Chocobozzz/PeerTube#402]
Hi,

* **PeerTube version or URL:** http://meilleurtube.delire.party/ (EDIT by rigelk: v1.0.0-beta.1)
* **Browser name/version:** Fenned for Android 58.0.2 (https://f-droid.org/packages/org.mozilla.fennec_fdroid/) on Android 4.2.2

* **What is the expected behaviour?**

I browse the home page, then click on the first video, then goes back (previous button in the browser). I expect to come back to the home page.

* **What do you see instead?**

An error about page number not being a number. Actually, the URL is `/videos/trending;sort=-views;page=NaN`. I guess the error is coming from the `NaN` value.

* **Browser console log if useful (Gist/Pastebin...):** /
* **Server log if useful (Gist/Pastebin...):** /

Thanks!

**Comment by rigelk** [comment]
I could not reproduce the error on the same instance on Firefox for Linux 59, so I guess the issue is client-specific. What does the error console show (if anything)?

**Comment by tcitworld** [comment]
Did reproduce that once or twice, will try to reproduce it again.

**Comment by Phyks** [comment]
@rigelk Indeed, I cannot reproduce with a desktop version of Firefox. However, when going to `/videos/trending`, clicking on a video and pressing the back button, I sometimes get sent back to `/videos/trending` and sometimes get sent to `/videos/trendingsort=-views;page=1`. Not sure why.

Even on my Android device, it's not happening all the time. Not sure what the trigger is.

I'll check the console once I can hook my phone to my laptop and will tell you. Thanks,

**Comment by Phyks** [comment]
Oh actually, thinking about it after typing my last comment, it seems the redirection to `;sort=-views;page=1` is done only if the next page has started to lazy load in the homepage. So the correct STR for Android is:

* Go to `/videos/trending`.
* Scroll a bit to start loading next page.
* Click on a video.
* Go back with browser button "previous".

My wild guess so far is that there might be a race condition when computing the `page=` param in the URL if on a slow network (or slow device) and clicking on the video prior to the lazy loading of next page, or something like this.

**Comment by Phyks** [comment]
Here is what I have in the console:

```
22:14:44,523 Rebuilt pages with 5 elements per page.
main.62728c8ee74cb2633fe2.bundle.js:1:700896
22:14:45,089 Client credentials loaded.
main.62728c8ee74cb2633fe2.bundle.js:1:612758
22:14:45,583 Rebuilt pages with 5 elements per page.
main.62728c8ee74cb2633fe2.bundle.js:1:700896
22:14:47,921 TypeError: asm.js type error: Disabled by lack of compiler support
1.4528bfc1a7c92bca7509.chunk.js
22:14:50,218 Adding magnet:?xs=https%3A%2F%2Fpeertube.cpy.re%2Fstatic%2Ftorrents%2Ff78a97f8-a142-4ce1-a5bd-154bf9386504-1080.torrent&xt=urn:btih:40724354c980586f934dfc38f16f373579492177&dn=PeerTube+demonstration&tr=wss%3A%2F%2Fpeertube.cpy.re%2Ftracker%2Fsocket&tr=https%3A%2F%2Fpeertube.cpy.re%2Ftracker%2Fannounce&ws=https%3A%2F%2Fpeertube.cpy.re%2Fstatic%2Fwebseed%2Ff78a97f8-a142-4ce1-a5bd-154bf9386504-1080.mp4.
1.4528bfc1a7c92bca7509.chunk.js:1:428947
22:14:51,409 Removed magnet:?xs=https%3A%2F%2Fpeertube.cpy.re%2Fstatic%2Ftorrents%2Ff78a97f8-a142-4ce1-a5bd-154bf9386504-1080.torrent&xt=urn:btih:40724354c980586f934dfc38f16f373579492177&dn=PeerTube+demonstration&tr=wss%3A%2F%2Fpeertube.cpy.re%2Ftracker%2Fsocket&tr=https%3A%2F%2Fpeertube.cpy.re%2Ftracker%2Fannounce&ws=https%3A%2F%2Fpeertube.cpy.re%2Fstatic%2Fwebseed%2Ff78a97f8-a142-4ce1-a5bd-154bf9386504-1080.mp4
1.4528bfc1a7c92bca7509.chunk.js:1:431515
22:14:51,571 Rebuilt pages with 5 elements per page.
main.62728c8ee74cb2633fe2.bundle.js:1:700896
22:14:51,406 Firefox can't establish a connection to the server at wss://peertube.cpy.re/tracker/socket.
1.4528bfc1a7c92bca7509.chunk.js:1:343796
22:14:51,751
Backend returned code 400, body was: Should have a number start
main.62728c8ee74cb2633fe2.bundle.js:1:439917
22:14:51,697 The connection to wss://peertube.cpy.re/tracker/socket was interrupted while the page was loading.
1.4528bfc1a7c92bca7509.chunk.js:1:343796
```

Might be an `asm.js` error?

**Comment by Chocobozzz** [comment]
Hi, thanks for the issue @Phyks.

I fixed this last week: https://github.com/Chocobozzz/PeerTube/commit/1ff8d7d6314b9c6724900d1302c354d128c5d25b

**Comment by Phyks** [comment]
Oh, thanks! Sorry for the no longer applicable issue.
