### ISSUE TITLE
Send a mail to a user

### ISSUE THREAD

**Issue by tele81** [Chocobozzz/PeerTube#4021]
is it possible to send a mail to a user?

notification of updates, etc.

**Comment by ppnplus** [comment]
I also wish this to be possible too. Currently, manually sending mails to users (especially everyone on the instance at once, which can be thousands of users) can be hard and might require third-party services. I had a similar issue open at #3805.

**Comment by Chocobozzz** [comment]
> is it possible to send a mail to a user?

Yes, using an external email software
