### ISSUE TITLE
New Default Home Page Option

### ISSUE THREAD

**Issue by GORF-Official** [Chocobozzz/PeerTube#4022]
**I'd like for there to be a new option for default homepage**

It would be great if we had option to select trusted users and on homepage only show content from them - it could also apply to Trending and Popular options.

I prefer the Recently Added option for my home page but it is a bit scary because you never know who will create an account and upload some objectionable content and it would also make federating with other instances much less.  

**some option in user admin to select trusted user or verified or whatever**

  On home page only show content from trusted users

**Comment by Alterak** [comment]
> On home page only show content from trusted users

I think that you cannot do this. If you don't want to see inappropriate content? - So just hide it in the instance setup or for your account. If you do not want all the videos of this user to be displayed, then simply block him, either with your copy, or for your profile.

But adding the function of displaying live videos is a very important point!

**Comment by GORF-Official** [comment]
I am not sure you understand what I am saying.  Yes, displaying live videos is important but not as important as protecting users from harmful content.  No Peertube instance owners have the ability to moderate in real time.   My concern is a user uploads or live stream with, for example, porn.  I wake up in the morning and my home page is full of porn.  That is NOT respectful to my users.  

Blocking and hiding is a completely unscalable solution because:
1)  It is too late.  The porn is already on your homepage and forced on whoever visits.
2)  You are playing never ending game of moderation and your site will always be on defensive and look bad because it is too easy for them to win in such a contest.
3)  Dissuades instances from following other instances because it is hard enough to moderate your own users never mind the whole Fediverse.

The concern of controlling what info people have access to in a federated system is not a valid concern because users can find another instance to join or make their own.

**Comment by Alterak** [comment]
> I am not sure you understand what I am saying.

I understand everything perfectly, because I myself am the administrator of the instance ... I have the function enabled by default to hide unwanted content.

> I wake up in the morning and my home page is full of porn.

This simply cannot be. It means that "Show NSFW content" is enabled in your instance settings or in your profile settings.

> It is too late. The porn is already on your homepage and forced on whoever visits.

If the option to hide NSFW content by default is enabled on this instance, then you simply will not see such videos at all until you override this function in your profile.
Even if you enable this in your profile, you will receive a warning.


> 3. Dissuades instances from following other instances because it is hard enough to moderate your own users never mind the whole Fediverse.

Everyone chooses his own path and his own direction. There will be a viewer for any content. For example, I have a positive attitude towards porn, but at the same time I am concerned that children can see it. BUT at the same time, I understand ... Why should a child have access to these kinds of videos?
It is very difficult and every country and different people treat this differently.
That is why the developers have added the ability to hide such content by default. It was the right decision.

**Comment by GORF-Official** [comment]
Yes, I understood you had a positive attitude towards porn from the beginning.  I do not trust people, such as yourself, to understand what is and is not NSFW content and mark it as such and even if they do on my site or another site I do not want it on my site in any case.  Having it on my site until moderated is something we have to deal with, as all user generated content sites do, but having it forced on my users on the homepage is unacceptable. 

My feature request doesn't effect you or your instance or your life at all but as your type do, you seem to want to force your ideals or lack thereof, on others.   

What is URL your instance so I block it forever?

**Comment by Alterak** [comment]
> My feature request doesn't effect you or your instance or your life at all but as your type do, you seem to want to force your ideals or lack thereof, on others.

I am very sorry that you took my message so badly. I respect your views, your religion and in no way wanted to offend you.
But I want you to understand ... You are not alone on this planet and all people have different views. You can open Google and write any obscene word there ... and you will find a huge amount of content, but you are not complaining to google!


> What is URL your instance so I block it forever?

The address of my instance is https://peervideo.ru 
You can manually add only the instances you have checked, for example, I do it.

**Comment by GORF-Official** [comment]
No worries.  Yes, I understand that I am not alone on planet Earth and others have different views but again, my feature request doesn't have any effect on others, especially not in a negative way, and would actually help encourage people to federate because it poses less potential negative influence on another community.  Your tech spec does negatively effect others and their beliefs.

**Comment by Chocobozzz** [comment]
Hello,

Thanks for the issue but it's out of the scope of peertube. I think a plugin could address this use case. Don't hesitate to create another issue if you need a specific hook/helper.

**Comment by GORF-Official** [comment]
Thanks.  We will make a plugin in next few weeks and share.  I'll let you know if we have any problems.
