### ISSUE TITLE
API does not yield detailed error messages

### ISSUE THREAD

**Issue by bit** [Chocobozzz/PeerTube#4026]
posting content via API the validation rules are not document and the errors often hard to understand without any indication what the lmit is. i.e.:

- 120 character limit for name
- limit of 5 tags, limit of 30 character tag limit.

would be great if those limits would be documented in the video/put call at:
https://docs.joinpeertube.org/api-rest-reference.html#tag/Video/paths/~1videos~1{id}/put
in addition the error should indicate what the limit is, right now it just responds with:

{'errors': {'name': {'value': '...', 'msg': 'Should have a valid name', 'param': 'name', 'location': 'body'}}}

**Comment by rigelk** [comment]
@Chocobozzz how about refactoring validators called via `.custom(…)` as follows:

```diff
function isDateValid (value: string) {
-  return exists(value) && validator.isISO8601(value)
+  if (!exists(value)) throw new Error('Should have a date value')
+  if (!validator.isISO8601(value)) throw new Error('Should have a date that conforms to ISO 8601')
+  return true
 }
```

**Comment by rigelk** [comment]
@bit I amended the openapi documentation (which is used by https://docs.joinpeertube.org/api-rest-reference.html) so that characters limits for video names are properly displayed. The tag limit was already specified.
