### ISSUE TITLE
Download video info box is not updated after first view

### ISSUE THREAD

**Issue by samueltardieu** [Chocobozzz/PeerTube#4028]
**Describe the current behavior**

Go to a video page and click download. An info box opens which lets you select the resolution and gives you basic information such as the video size and bitrate. However, once you have seen the information corresponding to a given resolution, the infobox is no longer updated if you come back to this resolution later.

**Steps to reproduce:**

1. Open https://tube.rfc1149.net/videos/watch/62a97e61-9f4a-4b44-8332-38d08fe64f83
2. Click "… / Download" (or "… / Télécharger")
3. Switch several times between 1080p and 720p in the dropdown menu. Note how the size (1.19GB for 1080p and  349.37M for 720p) is not always updated. 

**Describe the expected behavior**

The info box should be updated.

**Additional information**

The bug is present using both Firefox nightly and Chromium on GNU/Linux.

* PeerTube instance:
  * URL: https://tube.rfc1149.net/
  * version: 3.1.0
  * NodeJS version: 12.21.0
  * Ffmpeg version: 4.1.6

* Browser name, version and platforms on which you could reproduce the bug:
  * Firefox nightly 90.0a1.20210420 Arch Linux
  * Chromium 90.0.4430.93 Arch Linux

**Comment by kontrollanten** [comment]
Hi! Thanks for reporting! This has been fixed in #3890 and will be included in the next release.
