### ISSUE TITLE
hardware requirements missing, opensuse repo down

### ISSUE THREAD

**Issue by zaggynl** [Chocobozzz/PeerTube#4030]
https://docs.joinpeertube.org/install-any-os
mentions a FAQ with system requirements, which links to https://github.com/Chocobozzz/PeerTube/blob/develop/FAQ.md#should-i-have-a-big-server-to-run-peertube which shows a github link to: https://joinpeertube.org/faq which doesn't contain any hardware requirements.

The openSUSE repo 'https://pkg.rigelk.eu/rpm/' mentioned in https://docs.joinpeertube.org/install-unofficial?id=opensuse no longer appears to exist.

**Comment by rigelk** [comment]
I fixed it in b5fdfcbd8

**Comment by zaggynl** [comment]
You're quick!

Er, what about the opensuse repo?
