### ISSUE TITLE
Default Video Playback Quality

### ISSUE THREAD

**Issue by GORF-Official** [Chocobozzz/PeerTube#4032]
**If a video is uploaded smaller than 240 then the default video playback Quality is, Audio**

**Steps to reproduce:**

1.  On Admin > Configuration > VOD Transcoding > Resolutions to generate per enabled format - Select Audio and 240
2.  Upload video smaller than 240
3.  View video

**I would like a way to always make the smallest video size available be the default on playback**

**Additional information**

* PeerTube instance:  Gorf Tube
  * URL:  https://gorf.tube/
  * version:  3.1.0
  * NodeJS version: ?
  * Ffmpeg version:  ?

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

Please paste the URL of the video

**Comment by GORF-Official** [comment]
Sorry for slow reply.  Just saw this.  Here are a couple examples.

https://gorf.tube/videos/watch/475c81e8-45b5-4774-888d-b84aa040ff31
https://gorf.tube/videos/watch/9f605b5f-f738-4cf4-a4dc-a317674a27e3
https://gorf.tube/videos/watch/dd70aaa1-969a-478b-8ab3-2212387a49e1

So again, any video that is uploaded less than 240 defaults to audio.  I only transcode to 240 (default) and they can change playback quality once playing to original file size but on smaller than 240 they default to audio, not the 240 (which isn't really 240 obviously).  Hope I am explaining well enough.  Please let me know if you don't get me.

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1a5b67b66d8327017d7763f4b2d54abd29c345de
