### ISSUE TITLE
Select channel when uploading from CLI

### ISSUE THREAD

**Issue by BurnyBoi** [Chocobozzz/PeerTube#4033]
When uploading a video from peertube cli, there is no way to choose what channel the video goes to when your account has more than 1 channel on it. This can cause your video to be published to the wrong channel at first, and then has to be moved to the other channel to publish it there instead.

This issue is to request an optional `--channel` flag on the upload command to also allow specifying the channel on your account to place the video.

**Comment by Chocobozzz** [comment]
Hello,

You already have this kind of flag: `--channel-name`. Use `node dist/server/tools/peertube-upload.js --help` for more information

**Comment by BurnyBoi** [comment]
```
$ peertube up
--video-name is required.
--file is required.

```

**Comment by BurnyBoi** [comment]
Show it in the output lol
