### ISSUE TITLE
Change "Code of Conduct" to "Privacy Policy" in primary core dev code. 

### ISSUE THREAD

**Issue by scramblr** [Chocobozzz/PeerTube#4034]
The "Code of Conduct" configuration setting is redundant and the Code of Conduct would generally already be stated in both the "Terms" and even "Moderation" sections. In fact, all 3 sections appear to be semi-redundant, so I am proposing we re-allocate the "CoC" section to be for individual "Privacy Policies" so that instance owners can declare their intentions more clearly upon user-signups. 

This would allow instance owners to clearly state whether they use things like 'reCaptcha', a Google product which may harvest data, or mCaptcha which is more privacy focused. It can also allow Instance Admins the ability to tell users whether the privacy IP protection is activated in the PeerTube instance. Finally, it can also allow the owners to write out how the WebTorrent protocol works, in words they think will connect better with their audience. 

I thank you for reading and considering this proposal

- The [HTP.LIVE](https://HTP.LIVE) Staff

**Comment by Chocobozzz** [comment]
Closing this inactive discussion that did not receive feedback.
