### ISSUE TITLE
Landing page sometimes redirects to trending when configured on Local videos

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#4037]
Really hard to reproduce.

When accessing the URL of the instance and with «Local videos» page configured as the landing page, we sometimes get the «Trending» page. 

Maybe it's linked to Angular Router, the navigation redirection should be hidden (no route history change).

![image](https://user-images.githubusercontent.com/1877318/116897555-acf65100-ac35-11eb-90f4-4f975be29f8c.png)

__ 

PeerTube v3.1

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/504
