### ISSUE TITLE
How to add theme repository?

### ISSUE THREAD

**Issue by roere** [Chocobozzz/PeerTube#4041]
I have created a theme for my instance and stored it on github. Also I installed it on cli level from a local copy on my server. 
Is there an easy way to add a online theme repository to my server conf, so the themes in that repository can be easily installed from the web interface?

**Comment by Chocobozzz** [comment]
Hello,

No you can't add a theme repository. You must publish your theme on NPM and install it from your instance

**Comment by roere** [comment]
Hi,
I added it on NPM two days ago (https://www.npmjs.com/package/peertube-theme-pirate-ragnar). Some Metadata, I need to add, or is it just taking more time?

**Comment by Chocobozzz** [comment]
Your package.json was invalid. I updated the plugin index to be more robust and I can now see your theme

**Comment by roere** [comment]
Thanks. Can see it now, too.
