### ISSUE TITLE
live search filter includes channel names having that search term as well

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#4043]
**Describe the current behavior**
i went to https://peertube2.cpy.re/ and searched for "live".
then i filtered out only "display only live videos".
the first results are good but below livestreams, it shows channels whose name contains that search term

**Steps to reproduce:**

1. https://peertube2.cpy.re/
2. search for "live"
3. filter to display only live videos.
4.  it shows live videos + channels whose name contains "live" for the most part

**Describe the expected behavior**
https://peertube2.cpy.re/search?isLive=true&sort=-match&searchTarget=search-index&search=live
IMO channels should not show up when the search constraint specifically asks for "only currently live videos"
**Additional information**

* PeerTube instance:
  * URL:
  * version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by test2a** [comment]
![image](https://user-images.githubusercontent.com/39449563/117262557-072e2680-ae6f-11eb-8d4b-3f76c5da6851.png)

**Comment by test2a** [comment]
checking sepia search, there the live videos filter does only show live videos and not channels so i guess there is a bug in peertube2.cpy.re

**Comment by test2a** [comment]
Would it be possible to not show "live has not started yet" about streams which are started by users but dont start them or close them?

IMO live filter should show " currently live " only.

**Comment by toon462** [comment]
แถบค้นหาไม่ขึ้นครับ

ในวันที่ พฤ. 6 พ.ค. 2021 14:58 น. test2a ***@***.***>
เขียนว่า:

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/2262

**Comment by toon462** [comment]
ในวันที่ ศ. 14 พ.ค. 2021 19:21 น. Chocobozzz ***@***.***>
เขียนว่า:
