### ISSUE TITLE
OpenGraph description show bulky markdown 

### ISSUE THREAD

**Issue by 1000i100** [Chocobozzz/PeerTube#4044]
Here is an example : 
https://forum.duniter.org/t/hackaton-axiom-1-5-g1lib-gsper-comment-ca-marche-par-millicent/8406

**Describe the current behavior**

The OpenGraph card includes raw markdown source

**Steps to reproduce:**

1. Publish a video with some link in description.
2. Share the link into social media
3. The OpenGraph card includes raw markdown source

**Describe the expected behavior**

The OpenGraph card includes parsed markdown if html is allowed or innerText of the rendered markdown for a clean text output with a good lisibility.

**Additional information**

* PeerTube instance:
  * URL: https://tube.p2p.legal/videos/watch/0808e244-e8ca-4a5c-96e7-e46754ebec62
  * version: 3.1.0
  * NodeJS version: ?
  * Ffmpeg version: ?

* Browser name, version and platforms on which you could reproduce the bug: any (but firefox in my case)

**Comment by 1000i100** [comment]
PS : if you confirm it's a good fix, i probably can send you a merge request.

**Comment by rigelk** [comment]
AFAIK this is already fixed in develop. Please request a reopening if you manage to reproduce that bug on https://peertube2.cpy.re
