### ISSUE TITLE
Display User quota on about page

### ISSUE THREAD

**Issue by Aldarone** [Chocobozzz/PeerTube#405]
* **PeerTube version or URL:** Beta1

* **What is the expected behaviour?** : Users should be able to check if an instance applies a quota before registering.
* **What do you see instead?** : The only way to discover if you will be able to upload some videos on a peertube instance is by registering on it and then go to your user settings.

**Comment by rigelk** [comment]
We could expose that in the public stats of an instance, too.

**Comment by Chocobozzz** [comment]
I think in the "create an account" would be more appropriate?

**Comment by Aldarone** [comment]
I think it's more logical in the about page. 

- User discovers a peertube instance.
- They go check the about page to see if they would fit in.
- The instance looks nice so they click on register.
- :oh_no: The quota is too low.

I think it's an important information and as such it should be visible early with other meaningful information like the instance rules.
