### ISSUE TITLE
Streaming from LiveU Solo causes poor quality

### ISSUE THREAD

**Issue by vranki** [Chocobozzz/PeerTube#4050]
**Describe the current behavior**

We are trying to live stream using a hardware streamer called LiveU Solo. The 
quality is poor - output bandwidth is 7mbps but what users receive is very low res
and glitchy video.

We tested the device can transmit high quality streams to Youtube and Twitch. Also
streaming from OBS to the same instance results in good quality.

The device in question is: https://gosolo.tv/

I understand this is difficult to debug without having access to said hardware but
maybe something can be figured out.

**Steps to reproduce:**

1. Get a LiveU solo and set it up for normal 720p broadcast
2. Start a livestream to a Peertube instance
3. Observe poor quality video

**Additional information**

* PeerTube instance:
  * URL: https://tv.pirateradio.social/
  * version: 3.1.0

* Browser name, version and platforms on which you could reproduce the bug: Several

**Comment by rigelk** [comment]
hi @vranki,

> I understand this is difficult to debug without having access to said hardware but
maybe something can be figured out.

I would suggest you open an issue on their support forums to gather information about differences between their hardware output and that of software which have been proven to work with PeerTube livestreaming (i.e. OBS). There's little we can do here otherwise.

**Comment by vranki** [comment]
Already asked their support. The issue still persists.

**Comment by rigelk** [comment]
Could you link your support request here for further details?

**Comment by vranki** [comment]
I don't think there is a publicly visible ticket anywhere. I'll let you know what they respond.
