### ISSUE TITLE
Make value of enclosure tag configureable per instance

### ISSUE THREAD

**Issue by saerdnaer** [Chocobozzz/PeerTube#4052]
Right now the enclosure tag in an Item in a RSS Feed (e.g. https://open.tube/feeds/videos.xml?videoChannelId=2291) defaults to the `.torrent` file – in this example `https://open.tube/static/torrents/260bf7e5-b5e9-432f-9307-f5e0faf780ec-360.torrent`.

In my option the default file format should be configurable per PeerTube instance or channel, e.g. one of the the MP4 files. Is there already a config option for that, or would this be a new feature?

```xml
<item>
            <title><![CDATA[My Man Godfrey (1936)- William Powell, Carole Lombard, Alice Brady, Gail Patrick]]></title>
            <link>https://open.tube/videos/watch/260bf7e5-b5e9-432f-9307-f5e0faf780ec</link>
            <guid>https://open.tube/videos/watch/260bf7e5-b5e9-432f-9307-f5e0faf780ec</guid>
            <pubDate>Sat, 15 Jun 2019 21:57:53 GMT</pubDate>
            <description><![CDATA[During the Great Depression, Godfrey "Smith" Parke (William Powell) was living alongside other men down on their luck at a New York City dump on the East River near the 59th Street Bridge. One night, spoiled socialite Cornelia Bullock (Gail Patric...]]></description>
            <content:encoded />
            <dc:creator>OpenMovies 📽</dc:creator>
            <enclosure type="application/x-bittorrent" url="https://open.tube/static/torrents/260bf7e5-b5e9-432f-9307-f5e0faf780ec-360.torrent" length="337147051">
            </enclosure>
            <media:thumbnail url="https://open.tube/static/thumbnails/260bf7e5-b5e9-432f-9307-f5e0faf780ec.jpg" height="122" width="223">
            </media:thumbnail>
</item>
```

**Comment by toon462** [comment]
ในวันที่ ศ. 7 พ.ค. 2021 19:20 น. Andreas Hubel ***@***.***>
เขียนว่า:

**Comment by saerdnaer** [comment]
For example, to be able do to subscribe to a feed via classic podcast apps.

**Comment by rigelk** [comment]
What are classic podcast apps?

**Comment by saerdnaer** [comment]
@rigelk E.g. the ones listed at https://docs.google.com/spreadsheets/d/1c2L14UVH1xtN4iDG4awheLbMgPCQgaKEamUauWs1gps/edit#gid=0

**Comment by saerdnaer** [comment]
@Chocobozzz Can you clariy the closing? Was the issue implemented?

**Comment by rigelk** [comment]
@saerdnaer thanks. The issue was closed because of your lack of response, not because it was implemented. As it stands, we need to understand what kind of enclosures are expected to take them into account in our design, and to use some of them in our test suite. Unfortunately your document lacks that kind of information, so it will take time to consolidate it.

**Comment by Chocobozzz** [comment]
Hello,

I think we can now use the mp4 file directly, adding an option for the torrent file requires additional work and I don't think it's worth it

**Comment by kontrollanten** [comment]
Do we need to update pfeed to get it working then?

https://github.com/rigelk/feed/blob/de4dcd17281f64ead97b47e6059c4d3b4a2e9da4/src/feed.js#L504-L522

**Comment by rigelk** [comment]
You just need to use the video attribute instead of the torrent one.

**Comment by Chocobozzz** [comment]
We now display the mp4 file as default enclosure.
