### ISSUE TITLE
Lack of documentation for server tool scripts

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4054]
**Parts of the documentation concerned:**
Most of `./dist/server/tools/peertube.js`  commands accept parameters as `--url`, `--username` and `--password`.
If omitted, peertube.js will fallback to the first peertube instance in the .netrc file.
But in order to be taken into account, all 3 parameters must be provided. 
If we only pass --url, there is no warning, and the script will use the first entry in .netrc. 

This is not documented in the script help content, nor in the peertube documentation.

(I told about this problem with @Chocobozzz , and he asked me to open this issue)

**Comment by Chocobozzz** [comment]
Hi and sorry for the late answer. It should be better with https://github.com/Chocobozzz/PeerTube/commit/4dfd57ae6f7dd2d014c3353111a2428a2288a588
