### ISSUE TITLE
Peertube on Microk8s - Live streaming issue

### ISSUE THREAD

**Issue by roere** [Chocobozzz/PeerTube#4057]
Hi,
I installed Peertube on Kubernetes (Microk8s), based on this repository: https://git.geekhome.org/ghp/helm-charts/src/branch/master/peertube. The installation works fine, except live streaming, as the rtmp port is not exposed.
So I added in deployment.yaml for the container port:
`      - name: live`
`         containerPort: 1935`
`         protocol: TCP`

Also I changed the service type to NodePort and added in service.yaml (under spec, ports):
`    - port: 1935`
`      targetPort: 1935`
`      protocol: TCP`
`      name: live` 

RTMP is now exposed on port 30xxx. I can start a stream (from OBS, e.g.) and the Peertube-Player starts loading after 30s, but doesn't get any data. On server level I can see a file beeing created under storage/streaming-playlists/hls, max size of that file is always around 400K.
That's it so far.

Any ideas, why the player is not getting any data?

Peertube-Version: 3.1.0

**Comment by rigelk** [comment]
Hi @roere,

You are using a community-made packaging of PeerTube. In case it doesn't work, you can always fall back to the production guide install which is the only one we can fully support here, or open an issue on https://git.geekhome.org/ghp/helm-charts/src/branch/master/peertube where you can get support closer to your deployment method.

**Comment by roere** [comment]
@rigelk Ok, I got that and I totaly understand that the peertube team cannot support that kind of issues. But as Kubernetes is part of the "unofficial" Installation methods there should be a place to discuss related issues. The repository itself is not that place, as the vast majority of the peertube admins will not find their way there.
Maybe create a label "Questions to the community" that will not be supported by the team?

**Comment by Chocobozzz** [comment]
Hello,

You can use our forum for this kind of discussion: https://framacolibri.org/c/peertube/38
