### ISSUE TITLE
Create a user API: channelName is not optional

### ISSUE THREAD

**Issue by sanpii** [Chocobozzz/PeerTube#4061]
**Parts of the documentation concerned:**

https://docs.joinpeertube.org/api-rest-reference.html#tag/Users/paths/~1users/post

**Describe the desired information/correction**

The `channelName` parameter is not optional and should match the `actorNameAlphabet` regex (spaces not allowed).

**Comment by rigelk** [comment]
hi @sanpii and thanks for reporting that documentation issue. However I can't find any reference in the code to the `channelName` not being optional, on the contrary: https://github.com/Chocobozzz/PeerTube//blob/5e8dd6e08ac1595aeb72c6b5b2c7d2c6aced8b47/server/middlewares/validators/users.ts#L60

**Comment by sanpii** [comment]
@rigelk You’re right, I sent `channelName=null` instead of nothing.
