### ISSUE TITLE
libvips as a dependency on Linux (and other systems)?

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#407]
Before amending and sending a merge request for Production.md about FreeBSD, I would like to know if vips-8 is a dependancy on Linux. It's needed to compile PeerTube on FreeBSD.

If yes, I would also update the dependencies section in the README.

**Comment by rigelk** [comment]
Doesn't seem like it's a dependency on Linux, as far as I can tell.

**Comment by Chocobozzz** [comment]
I depends: http://sharp.pixelplumbing.com/en/stable/install/#prerequisites
