### ISSUE TITLE
Mark deprecated plugins as such, and remove them from search results

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#4070]
**Describe the current behavior**

Currently the plugin index doesn't consider the deprecation status of a plugin. This is especially useful to remove plugins, as the `npm unpublish` command can only be executed at most 72h after the package publication, and the only alternative (besides contacting a human at npmjs inc.) is to deprecate the plugin, with an optional message, i.e. `npm deprecate peertube-plugin-slides@"> 0.0.0" "unfinished support for versions 3+ of PeerTube"`.

**Describe the expected behavior**

Currently installed plugins that are found to be deprecated should alert their admins, at least via a badge eventually showing the deprecation message within the plugin management interface.

The plugin management search interface should remove deprecated plugins from its list, to prevent new installations of deprecated plugins.

**Related issues**

https://github.com/Chocobozzz/PeerTube/issues/4069

**Comment by Chocobozzz** [comment]
The plugin index will automatically remove deprecated plugins. I added a doc in https://github.com/Chocobozzz/PeerTube/commit/d61515e12a8803a1662d1122a171201622a0ed77
