### ISSUE TITLE
404 for remote avatar

### ISSUE THREAD

**Issue by johanfleury** [Chocobozzz/PeerTube#4071]
I suffered a data loss recently and restored PeerTube with an empty storage. Since then, some avatars are not showing and I couldn’t find any way to make PeerTube reload them (the files are not present in the data directory).

I had a similar issue with thumbnails, but unsubscribing from a channel then subscribing again fixed that (I had no luck trying to restore avatars with this technique).

Here is a screenshot that shows the issue:

![Missing avatars on a user and their channel](https://user-images.githubusercontent.com/7230353/117690938-6189f880-b189-11eb-866c-d3fd90fde4cb.png)

The avatar URL returns a 404 status code:

```
$ curl -I -X GET https://peertube.br0.fr/lazy-static/avatars/2b8ff6f3-b4fd-45d0-9238-4dc28148c292.png
HTTP/2 404
date: Mon, 10 May 2021 16:16:27 GMT
content-length: 0
tk: N
access-control-allow-origin: *
strict-transport-security: max-age=15724800; includeSubDomains
permissions-policy: interest-cohort=()
```

And the avatar is not there:

```
$ ll avatars/2b8ff6f3-b4fd-45d0-9238-4dc28148c292.png
ls: cannot access 'avatars/2b8ff6f3-b4fd-45d0-9238-4dc28148c292.png': No such file or directory
```

The question is, is there a way to make PeerTube download a channel/user avatar when it’s not there?

If not, what would be the best solution? I’m thinking of two ways of doing this:

* Detect when a remote user/channel avatar is missing on disk and fetch it then (for instance when PeerTube returns a 404 error).
* Have a background job that checks avatars and fetch them when they are missing.

I could probably work on a PR if you want to.

**Comment by AnonymousWebHacker** [comment]
I think, you can regenerate thist avatar. See https://docs.joinpeertube.org/maintain-tools
https://docs.joinpeertube.org/maintain-tools?id=regenerate-thumbnailsjs

**Comment by johanfleury** [comment]
Thanks for the suggestion, but unfortunately this script was added in 3.2-rc1 and I’m still running version 3.1 (the latest stable release).

Also, after having a quick look at the code, it seems that it’s not doing anything related to avatars, so I don’t think it would actually solve my issue.

**Comment by AnonymousWebHacker** [comment]
That was what I was going to tell you, I confused avatar with preview of the videos [thumbnails] :)
Actually, that problem has happened to me, I do not know if it is a problem with the ffmpeg or no idea what it may be, that it is an error that the avatars fail.
However, in what they give you an answer (I hope it does not delay)
You can take the ID of the missing avatar, go to / avatars / and copy any of the ones that are there and rename it with the missing ID.

**Comment by Chocobozzz** [comment]
Hello,

Could you enable debug logs and paste SQL lines before `https://peertube.br0.fr/lazy-static/avatars/2b8ff6f3-b4fd-45d0-9238-4dc28148c292.png` request in the logs?

**Comment by johanfleury** [comment]
Here you are:
```
[peertube.br0.fr:443] 2021-06-01 23:14:37.964 debug: Executed SQL request - Executing (default): SELECT "id", "filename", "height", "width", "fileUrl", "onDisk", "type", "createdAt", "updatedAt" FROM "actorImage" AS "ActorImageModel" WHERE "ActorImageModel"."filename" = '2b8ff6f3-b4fd-45d0-9238-4dc28148c292.png' LIMIT 1;
[peertube.br0.fr:443] 2021-06-01 23:14:37.971 error: Error in controller. {
  "err": "Error: ENOENT: no such file or directory, stat '/data/avatars/2b8ff6f3-b4fd-45d0-9238-4dc28148c292.png'"
}
[peertube.br0.fr:443] 2021-06-01 23:14:37.985 info: 184.160.0.0 - - [01/Jun/2021:23:14:37 +0000] "GET /lazy-static/avatars/2b8ff6f3-b4fd-45d0-9238-4dc28148c292.png HTTP/1.1" 404 - "-" "Firefox"
```

**Comment by Chocobozzz** [comment]
Thanks, could you paste the output of the SQL query:

```
 SELECT "id", "filename", "height", "width", "fileUrl", "onDisk", "type", "createdAt", "updatedAt" FROM "actorImage" AS "ActorImageModel" WHERE "ActorImageModel"."filename" = '2b8ff6f3-b4fd-45d0-9238-4dc28148c292.png' LIMIT 1;
```

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/79db409a41bd28fd2773626c9a93b5d326a38bc0
