### ISSUE TITLE
Remember previous player resolution choice

### ISSUE THREAD

**Issue by nicolnt** [Chocobozzz/PeerTube#4073]
**Describe the problem to be solved**

Video is the main contributor to Internet data consumption (about 80% according to The Shift Project, see there report summary [here](https://theshiftproject.org/wp-content/uploads/2019/07/Excutive-Summary_EN_The-unsustainable-use-of-online-video.pdf)). The energetic impact of digital is growing at a rate of 9% per year (doubling every 8 years approximately) so it's not sustainable. I want to consume less while still enjoying video content and currently I have to manually set the quality down for every video I watch on PeerTube.

**Describe the solution you would like:**

This problem could be addressed with three changes:
* By having a [green by default](https://blr.design/blog/green-by-default/) setting, where video play in say 720p or even 360p quality if the user doesn't touch anything. It would not serve the highest possible quality that is unnecessary in most cases.
* To have a way to change the defaults in user preferences.
* To remember the last manual change on video so the next will use the same quality (like on YouTube actually). 

**Describe alternatives you have considered**

I think all the three above should go together, but any is already nice to address data consumption!

_Thanks a lot to the people working on this project and to Framasoft for providing Google free and FLOSS alternatives_ :100:

**Comment by Chocobozzz** [comment]
Closing in favour of https://github.com/Chocobozzz/PeerTube/issues/1909
