### ISSUE TITLE
NGINX error in nightly build.

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#4074]
**Describe the current behavior**
After updating the nightly build, the NGINX error appeared. 
I am using Nginx version 1.18.0

**Steps to reproduce:**

1. I have updated the instance to nightly build version 3.1.0-nightly-2021-05-11
2. I also updated the NGINX configuration file.
3. I get an error on line 83 when starting NGINX

The error is in this section of code. I had to comment out these 2 lines.

```
  location = /api/v1/videos/upload-resumable {
    if ($request_method = 'PUT') {
      #client_max_body_size    0;
      #proxy_request_buffering off;
    }

    try_files /dev/null @api;
  }
```

**Describe the expected behavior**

There should be no mistake.

* PeerTube instance:
  * URL: https://peervideo.ru
  * version: 3.1.0-nightly-2021-05-11
  * NodeJS version: 12.21.0
  * Ffmpeg version: 4.1.6-1~deb10u1
  * Nginx version: 1.18.0

**Comment by Chocobozzz** [comment]
Thanks, fixed in https://github.com/Chocobozzz/PeerTube/commit/d795b76c44fbecb1438053a7d636f6fc089c8fa9
