### ISSUE TITLE
Stats for Nerds - Only display lowerest Resolution

### ISSUE THREAD

**Issue by warnerbryce** [Chocobozzz/PeerTube#4076]
On PeerTube 3.2.0 - RC1 
When opening the Stats for Nerds info window the Resolution don't match with the actual resolution displayed. 
It displays only the lowest Resolution available on the video. 

Exemple : i have only 720/1080p videos on peertube.we-keys.fr, the Stats for Nerds display 720p30 all the time even if i watch a video in 1080p mode. I went on video who's not from my instance and it says 240p30 but i was watching it in 1080p. 

Thank you for this cool feature !

**Comment by SimplyCorbett** [comment]
This is still a problem in the 3.3.0-rc.1 beta
