### ISSUE TITLE
Album cover/thumbnail/art for video file

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4082]
**Describe the problem to be solved**
Today it's possible to enable direct download of video and audio files. It would be great to add the preview image as an album cover to the media file so that it's shown in the file explorer or when playing the file in a media player.

**Describe the solution you would like:**
When a preview image is added or changed it should be added to the files as well.

**Describe alternatives you have considered**  
```
ffmpeg -i in.mp3 -i test.png -map 0:0 -map 1:0 -c copy -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (front)" out.mp3
```
Source: https://stackoverflow.com/a/18718265/7434393

I'm not sure how this works with federation though. But since file replacements are supported I guess this works the same way.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/658241d8c6172bd1a85a77aaa5484370d2bf63db when downloading audio files using the new "generated download" endpoint
