### ISSUE TITLE
Account profile error and banner quality

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#4084]
Hey!
I have updated the instance to the latest version 3.2.0-rc.1. You did everything very well! But in the user profile, the right side is wide. Is this what you intended or is it a mistake?

![Screenshot_1](https://user-images.githubusercontent.com/11453567/118081661-7a322280-b3c4-11eb-9825-86979f2e3f03.png)
![Screenshot_2](https://user-images.githubusercontent.com/11453567/118081670-7c947c80-b3c4-11eb-824a-1018576623ed.png)

And I also want to ask ... When I load the banner image of my channel, the quality of the image changes very much, it becomes worse, although I load the recommended sizes (1600x266). How can this be fixed?

**Comment by Chocobozzz** [comment]
> But in the user profile, the right side is wide. Is this what you intended or is it a mistake?

This is intended, there is a max width to prevent too big description/videos list width.

> it becomes worse, although I load the recommended sizes (1600x266). How can this be fixed?

Please paste the two files

**Comment by Alterak** [comment]
> Please paste the two files

I posted a banner on this channel https://peervideo.ru/video-channels/progweb/videos

This is the original file

![test-banner-original](https://user-images.githubusercontent.com/11453567/118241752-2d724880-b4a5-11eb-985c-410f059de863.png)

This is the file that I saved from my channel

![test-banner-save](https://user-images.githubusercontent.com/11453567/118241836-47139000-b4a5-11eb-9b5b-aa3ca7696b1c.png)

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/bc529ef7f0e18bef4cb43c0f2345e8fd1c0075ff
