### ISSUE TITLE
Error responses as HTTP Problem details/RFC7807

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#4088]
**Describe the problem to be solved**

Currently we have 3+ ways of responding to errors within PeerTube:

Basic errors:
```http
HTTP/1.1 404 Not Found
Content-Type: application/json

{
  "error": "Account not found"
}
```

Basic errors with a code (a PeerTube-specific server error code, here corresponding to DOES_NOT_RESPECT_FOLLOW_CONSTRAINTS):
```http
HTTP/1.1 403 Forbidden
Content-Type: application/json

{
  "errorCode": 1,
  "error": "Could not follow server"
}
```

Validation errors:
```http
HTTP/1.1 400 Bad Request
Content-Type: application/json

{
  "errors": {
    "id": {
      "value": "a117eb-c6a9-4756-bb09-2a956239f",
      "msg": "Should have an valid id",
      "param": "id",
      "location": "params"
    }
  }
}
```

While _the current situation is fine_, I think at least __producing the JSON response of errors via a unique factory__ would allow mapping them/processing them as needed, and achieve a bit of yak shaving: translatable error messages, ubiquitous error codes, etc.

**Describe the solution you would like:**

I think we can take inspiration from the HTTP Problem details specification in [RFC7807](https://tools.ietf.org/html/rfc7807). It has seen a few implementations that provide examples of how it can be handled:
- https://www.npmjs.com/package/express-http-problem-details
- https://github.com/kamranahmedse/express-api-problem
- https://www.npmjs.com/package/problem-json

They generally provide different factories/handlers that produce such responses:

```http
HTTP/1.1 403 Forbidden
Content-Type: application/problem+json
Content-Language: en

{
  "title": "Could not get video",
  "detail": "Could not get the video since it originates from an actor not followed by your server, which doesn't allow fetching unrelated actors' videos",
  "instance": "/api/v1/videos/9c9de5e8-0a1e-484a-b099-e80766180a6d",
  "type": "https://docs.joinpeertube.org/errors/DOES_NOT_RESPECT_FOLLOW_CONSTRAINTS",
  "docs": "https://docs.joinpeertube.org/api-rest-reference.html#tag/Video/paths/~1videos~1{id}/get"
}
```

We could further document some errors with a `type` parameter that links to a given error code. As for validation errors, we could provide them as follows:

```http
HTTP/1.1 400 Bad Request
Content-Type: application/problem+json
Content-Language: en

{
  "title": "Invalid parameter",
  "instance": "/api/v1/videos/a117eb-c6a9-4756-bb09-2a956239f",
  "invalid-params": {
    "id": {
      "value": "a117eb-c6a9-4756-bb09-2a956239f",
      "msg": "Should have a valid id",
      "param": "id",
      "location": "params"
    }
  },
  "type": "about:blank",
  "docs": "https://docs.joinpeertube.org/api-rest-reference.html#tag/Video/paths/~1videos~1{id}/get"
}
```

Having a single factory for these errors would also allow producing an associated log entry, with an request uid that we could provide in the response for easier debugging/finding in the logs.

**Comment by toon462** [comment]
ในวันที่ พฤ. 13 พ.ค. 2021 17:26 น. Rigel Kent ***@***.***>
เขียนว่า:
