### ISSUE TITLE
Videos embed not generated when shared on Diaspora*, Facebook, (more?)

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#409]
When sharing videos on Diapora* network (or on FB) they aren't embedded in a player like on Mastodon or like video from YT.

Don't know how its works!

**Comment by rigelk** [comment]
@gegeweb PeerTube relies on websites to use oEmbeds to display the most accurate title, description, and image when sharing a video URL. It sounds like [Disapora* uses oembeds](https://wiki.diasporafoundation.org/FAQ_for_users#How_do_I_embed_a_video.2C_audio.2C_or_other_multimedia_content_into_a_post.3F). However They are the ones adding support for platform oembeds (we have our own oembed definition in `server/middlewares/validators/oembed.ts`). Maybe ours doesn't fit what they're expecting.

As for Facebook, they don't use oEmbeds but OGP. More detailed docs altogether about link previews: https://indieweb.org/link-preview#Facebook (I think we could clearly take note of some stuff from that page)

**Comment by Chocobozzz** [comment]
Most websites use whitelist for oembed...

**Comment by gegeweb** [comment]
For oembed and player integration (with or without whitelist) it is necessary to have an endpoint url that (I think) returns the player code.
Now that I have my Diaspora pod* I tried to test by listing my Peertube instance in the white list.
But I didn't find the "endpoint" url?

I open a ticket again? Did I miss something?

**Comment by Chocobozzz** [comment]
Maybe https://peertube.datagueule.tv/services/oembed?url=https://peertube.datagueule.tv/videos/watch/0b04f13d-1e18-4f1d-814e-4979aa7c9c44 ?

**Comment by gegeweb** [comment]
Yes, that's it!  Thanks.

**Comment by gegeweb** [comment]
Whitelist an instance of Peertube on Diaspora works fine with the oembed endpoint.
But… I don't know if we can do something on the Peertube side or if that's on te Diaspora side.

Before playing : 
![capture](https://user-images.githubusercontent.com/9108457/41846630-8ffb4d2a-7877-11e8-8ffa-00936891ed86.PNG)

After playing start : 
![capture2](https://user-images.githubusercontent.com/9108457/41846645-9ebc4a94-7877-11e8-95c6-c37aa6162046.PNG)

Do I open an issue here or is that an issue with Diaspora?

**Comment by Chocobozzz** [comment]
I think it's a diaspora issue. Embed works fine on other websites (mastodon, twitter, blogs etc).

**Comment by gegeweb** [comment]
I think to, that is the height of the iframe I think.
I added a comment on the diaspora* issue : https://github.com/diaspora/diaspora/issues/7792
