### ISSUE TITLE
POST /blocklist/servers returns a 204

### ISSUE THREAD

**Issue by sanpii** [Chocobozzz/PeerTube#4095]
**Parts of the documentation concerned:**

https://docs.joinpeertube.org/api-rest-reference.html#tag/Server-Blocks/paths/~1blocklist~1servers/post

**Comment by sanpii** [comment]
(this is my last issue, for now, thank you for your reactivity !)

**Comment by rigelk** [comment]
@sanpii your issues are very welcome. Keep going! 🤗
