### ISSUE TITLE
switching authentication plugin breaks local authentication 

### ISSUE THREAD

**Issue by kenshin33** [Chocobozzz/PeerTube#4096]
**Describe the current behavior**
switching authentication plugin back and forth between local and ldap  (probably others) breaks local authentication 

**Steps to reproduce:**

1. add new user 
2. set his password 
3. user can login with set password
4. switch to ldap authentication (may other plugins, I just so happen to use ldap)
5. user can login with ldap password 
6. switch back to  None (local Auth)
7. user no longer able to login (neither with step 2 password not with  ldap password) and admin no longer able to set or reset password (the whole DANGER ZONE is not shown)
8.  switch back to ldap
9.  user able to login with ldap password

**Describe the expected behavior**
admin able to set or reste the password an user can authenticate using the password in the database.
It worked very well before 3.1 (there was no ui to do it, setting authplugin  field  to the empty string did the trick then)

**Additional information**
I tracewd it back to a  null vs "null",  all the code  (auth, and what displays the UI) tests for null  -- the value --, but the ui sets authpligin field to "null" -- the string --. Modifying the code to test authplugin for   "null" (the string) works, setting the field manually in the database to null  works too  and is way way easier to do (for me anyways).

**Comment by Chocobozzz** [comment]
Thanks for the issue, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/d11eae7edc1339e8e6791d63176613c6f283f995
