### ISSUE TITLE
Turn off web seeds

### ISSUE THREAD

**Issue by SoniEx2** [Chocobozzz/PeerTube#4097]
**Describe the problem to be solved**

Peertube is supposed to be peer-to-peer but web seeds aren't.

**Describe the solution you would like:**

There should be a way to just, turn them off. Peertube has a webtorrent tracker, so it should be able to just seed over webtorrents instead...

**Comment by rigelk** [comment]
PeerTube is supposed to be a web server, and its deployment relies on efficient caching of HTTP request to improve performance. Having it seeded as regular peer wouldn't change how decentralized the solution is, and degrade performance.

**Comment by SoniEx2** [comment]
It's fine. The tracker would solve the performance issues. On the other hand it'd actually benefit the host as you wouldn't be able to watch with p2p off.
