### ISSUE TITLE
Unsubscribe button does not appear in Spanish

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#4099]
Peertube Version: 3.1.0
Browser: All Browsers no working unsubscribe button in Spanish

English
![subscription](https://user-images.githubusercontent.com/43164089/118404641-0d44b400-b674-11eb-91d3-6593d74e83b1.png)

Spanish
![spanish](https://user-images.githubusercontent.com/43164089/118404691-3bc28f00-b674-11eb-8473-274c162a430f.png)

**Comment by Can202** [comment]
ahh, it's for the spanish version, (estaba buscando una manera de desubscribirme de una cuenta, y no veía la opción, ahora se que es por mi idioma, gracias xD)

**Comment by rigelk** [comment]
Please update to the latest released version, as it was most likely fixed through a translation update.

**Comment by rigelk** [comment]
This doesn't appear on the latest version.

**Comment by AnonymousWebHacker** [comment]
@rigelk  The problem has not been fixed
Peertube V: 3.2.1
English
![Captura de pantalla de 2021-06-07 00-41-34](https://user-images.githubusercontent.com/43164089/120960142-37483e00-c729-11eb-97cf-ecc4190c1f62.png)
Spanish 
![no unsubscribe](https://user-images.githubusercontent.com/43164089/120960193-51821c00-c729-11eb-80d5-49b0dabe97e4.png)

**Comment by rigelk** [comment]
Did you check your Adblocker is disabled?

**Comment by AnonymousWebHacker** [comment]
[Adblocker] if it refers to firefox or chrome add-ons, like to block js or things like that, nop, it is without any of that
![Captura de pantalla de 2021-06-07 12-02-38](https://user-images.githubusercontent.com/43164089/121054157-1237e780-c78a-11eb-96ad-8cadb185c356.png)
If you notice, I don't have any add-ons enabled, both in firefox, like chrome, brave, gnome-browser ..etc

**Comment by Chocobozzz** [comment]
Hello,

Please fill the bug template and paste the instance URL

**Comment by AnonymousWebHacker** [comment]
> Hello,
> 
> Please fill the bug template and paste the instance URL

Instance Peertube: SNET , you cant see

**Comment by Chocobozzz** [comment]
Then can you reproduce your issue on https://peertube2.cpy.re/?

**Comment by AnonymousWebHacker** [comment]
@Chocobozzz this instance is close signup

**Comment by AnonymousWebHacker** [comment]
@Chocobozzz what you wait answer for me? 
I can signup on https://peertube2.cpy.re and, i cant see unsubscribe button in Spanish on my instance (any browser)

**Comment by Chocobozzz** [comment]
Sorry for the late answer. It should now be fixed on develop
