### ISSUE TITLE
Hide the title overlay on embedded videos quicker

### ISSUE THREAD

**Issue by Phyks** [Chocobozzz/PeerTube#410]
Hi,

* **PeerTube version or URL:** https://meilleurtube.delire.party/videos/watch/10af6bf9-eeb2-423b-a65c-88a194f79cc5
* **Browser name/version:** Firefox nightly on Linux
* **NodeJS version:** /

* **What is the expected behaviour?**

When watching an embedded version of the above video, say on https://kresus.org/blog/kresus-version-0-13-0.html, the overlay with the title takes quite a long time to disappear after the mouse is out of the video area (about 3-5 seconds). As the video is super short (10 seconds) and given the size of its embedded version, we are missing a whole part of the video, hidden by the title overlay.

Maybe it would be better to hide the overlay immediately when the mouse is over or at least with a shorter transition? Not sure what the hosted video platforms are doing for this.

Thanks for this great software!

**Comment by rigelk** [comment]
We use [videojs-dock](https://github.com/brightcove/videojs-dock) for the dock/overlay that you're seeing. It's defined in in `client/src/standalone/videos/embed.ts`, but unfortunately exposes no option to reduce that delay. I guess we'll have to hack it.

**Comment by Chocobozzz** [comment]
I'm on it

**Comment by rigelk** [comment]
@Chocobozzz the transitions are defined in https://github.com/brightcove/videojs-dock/blob/master/src/plugin.scss

**Comment by Chocobozzz** [comment]
I think it will be better now :) https://github.com/Chocobozzz/PeerTube/commit/60a26a559ca21ca02458a1311c5b464044bb8a05

**Comment by Phyks** [comment]
Awesome, thanks a lot for fixing this!
