### ISSUE TITLE
Do not stretch preview

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#4100]
**Describe the problem to be solved**

After downloading and processing the video, a preview is created, which is stretched and greatly distorted if the aspect ratio was different. I believe that the preview image should be like the original video.

**Describe the solution you would like:**

I recorded a video on my phone, I held the phone vertically in my hand. The video was recorded with the opposite aspect ratio, that is, with a resolution of 1080x1920
Here is an example of this video and you can see how the preview is stretched in width. This is very ugly.
https://peervideo.ru/videos/watch/485ff3a6-7fcf-4542-8284-a77bca9d1154

But this is the same video, but I deliberately took a screenshot of the screen and replaced the preview. It already looks nice and right.
https://peervideo.ru/videos/watch/aa913087-3ec8-4559-b6f4-ab3b65194d76

**Describe alternatives you have considered**  

I uploaded the same video to Youtube and it is displayed vertically there, as it should be.
https://youtu.be/kASJAh5WY10

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/3027
