### ISSUE TITLE
Peertube accepts users with the same email

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#4103]
If a user registers with the email example demo@domain.com and forgets their password or forgets that they have an account, they can register again in the instance with DEMO@domain.com or Demo@domain.com.

The peertube registration system should be able to detect that this email is already in use, and it should not accept it just because it is uppercase or lowercase (without noting the fact that all emails are lowercase)

**Comment by JigmeDatse** [comment]
I would say that while generally they would be the same address, technically the standard says that you can't *assume* that case doesn't matter in the user part.  That's determined on the server what to do if the case doesn't match.  

I see why that might be considered undesirable to comply with the standards, I'd argue it's preferable.  Because if it wasn't the right assumption...  It could prove an issue.

**Comment by AnonymousWebHacker** [comment]
@JigmeDatse look thath
![Captura de pantalla (376)](https://user-images.githubusercontent.com/43164089/118586889-ceaa1900-b79b-11eb-9974-7263b06d9128.png)

**Comment by JigmeDatse** [comment]
Not sure I get why that's addressed to me.  I wasn't saying "you're wrong ... that's not possible" but rather "I don't agree with your apparent belief that it should *not* be possible."  I may well have seen it myself.  And maybe...  ... I don't know.  It seems like this design is "as it should be".  Problem being, it can cause problems.  Just think those problems are easier to deal with than trying to deal with the problems which "don't allow this to happen" might cause.  

It's the "how do you verify an email address" problem.  There's a minimum regex which will pass for all valid email addresses, but the only real way is to "try sending email to it".  

Those are valid *different* email addresses.  Which *might* (probably) point to the same mailbox.

**Comment by AnonymousWebHacker** [comment]
@JigmeDatse hahaha it wasn't bad at all, sorry for mentioning you. It was just so that you could see in the photo what I meant

**Comment by Chocobozzz** [comment]
As @JigmeDatse we comply with the RFC: the local part mist be treated as case sensitive. We could however display a message in the login and signup form when the user write an uppercase in the email, to avoid confusions

**Comment by Chocobozzz** [comment]
Done in https://github.com/Chocobozzz/PeerTube/commit/7f28f2ddbaeecf451d501e99ded0408c14a33600

**Comment by AnonymousWebHacker** [comment]
tnks men

**Comment by allisonnokes** [comment]
This is a user-experience problem for the vast majority of users.  None of the major email service providers—such as Gmail, Yahoo Mail, Outlook.com, and others—treat email addresses as case-sensitive. They all normalize email addresses to lower case (or treat them in a case-insensitive manner) for the purposes of account creation, login, and sending/receiving messages. 

When logging in to PeerTube, the default behavior from a mobile device is to type a capital letter at the beginning of any string.  So notifying the user with a tool-tip or error-handling messaging makes it the user's responsibility to correct two different industry standards which cause the error (1. capitalizing the first letter of a string and 2. email addresses before the domain name are case-insensitive).  

It would be great to offer the option in the admin portal - for a choice to be made regarding the enforcement or not of user name case sensitivity.  This would allow PeerTube (in general) to continue to follow industry standards as a default, but allow individual instances to opt-out of email address case sensitivity if desired.
