### ISSUE TITLE
Plugin settings: bug on checkbox with default=true (frontend)

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4106]
**Describe the current behavior**

If a plugin has a checkbox settings with default value true, then the frontend always receive true as value.

I think that this is the line in cause: https://github.com/Chocobozzz/PeerTube/blob/3cf8874f1a0ba8a0f326b439d1155b2142b61563/server/models/server/plugin.ts#L286

It should test if the key is in `settings`, not the value. 

We had a similar bug on the backend ( https://github.com/Chocobozzz/PeerTube/issues/3838 ), here it is for the frontend.

**Steps to reproduce:**

1. Use a plugin with a checkbox settings value defaulting to true
2. Uncheck the checkbox
3. The frontend gets true as value

* PeerTube instance:
  * version: all version, including 3.2.0-rc1

**Comment by JohnXLivingston** [comment]
Just made a PR to fix this.

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/pull/4107
