### ISSUE TITLE
Live streams play back too slowly

### ISSUE THREAD

**Issue by ddevault** [Chocobozzz/PeerTube#4109]
**Describe the current behavior**

Live streams appear to playback slightly too slowly - not enough to be noticable, but enough to gradually increase the latency until the viewer falls off the back of the stream and their stream dies. Some users report it playing back too quickly as well, falling off the front of the stream and causing buffering issues.

**Additional information**

* PeerTube instance:
  * URL: https://spacepub.space
  * version: 3.1.0
  * NodeJS version: 12.18.4
  * Ffmpeg version: 4.3.1

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I would need logs or reproduce steps because it's difficult to help
