### ISSUE TITLE
Bad support for special characters passwords ?

### ISSUE THREAD

**Issue by regar42** [Chocobozzz/PeerTube#411]
* **PeerTube version or URL:** v1.0.0-beta.1
* **Browser name/version:** Firefox 59
* **NodeJS version:**

I tried to register to PeerTube using this single-use 64 characters password :
> %']mGhBp":cLUw\#H6+zp_y:Zm^&LWJWM0xuyZ_n;iGNJq?fe!,-gZz5?Pu@\3B'

* **What is the expected behaviour?**

I can login to my account, or if the password doesn't meet PeerTube's requirements, I see an error message.

* **What do you see instead?**

The register page said that the process was successful. However I couldn't authenticate, PeerTube kept saying "Authentication failed.". I contacted the instance admins, who deleted my account so I could try again. I registered one more time using the same password, but then again I couldn't authenticate. I then tried to reset my password, using the same password. The reset went without error, but I still couldn't login.

I eventually managed to login when I changed this password for some password of the same length, without special character. 

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

**Comment by Chocobozzz** [comment]
Hi, thanks for the issue! Should be fixed: https://github.com/Chocobozzz/PeerTube/commit/bf9ae5ce57c9e2117548ab5794c0c2a5096ba4ad
