### ISSUE TITLE
Live stream end: the banner don't appear

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4111]
**Describe the current behavior**

With Peertube 3.2.0-RC1, when a live stream finish, the message «This live has ended» don't appear directly. It only appears after a scroll event.

**Steps to reproduce:**

1. Start a live, and go watch it
2. Stop the stream and wait for the stream end in the browser
3. There is no «This live has ended» banner
4. Scroll down a little: the banner appears.

**Describe the expected behavior**

The banner should appear directly.

**Additional information**

I'm using a test server, on the branch origin/release/3.2.0 (commit 7e47e2aa5e13594dedde8abbb03fca914d64953d)

* PeerTube instance:
  * version: 3.2.0-rc1

* Browser name, version and platforms on which you could reproduce the bug: Firefox dev edition

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/ceb8f322118b24508abc6dd0bc6813a43610eff3
