### ISSUE TITLE
New db parameter does not sync to following instances

### ISSUE THREAD

**Issue by zanhesl** [Chocobozzz/PeerTube#4112]
**Peertube Version:** 3.1.0

**Goal:** I want to add aspect ratio of a video to api call `/api/v1/videos/video_id`

**Implementation:** 
Firstly, I created new db migration:

<img width="408" alt="Снимок экрана 2021-05-20 в 12 44 33" src="https://user-images.githubusercontent.com/48605213/118957358-2184fb80-b969-11eb-82d0-7649b366ab12.png">

Then I added new attribute to video model (path is at the top end of the screenshot):
<img width="511" alt="Снимок экрана 2021-05-20 в 12 45 54" src="https://user-images.githubusercontent.com/48605213/118957589-52653080-b969-11eb-8452-ddf679d3ad02.png">

Same goes to video-create model
<img width="600" alt="Снимок экрана 2021-05-20 в 12 50 05" src="https://user-images.githubusercontent.com/48605213/118958242-e800c000-b969-11eb-877b-6d5891668f76.png">

And then added new param to the api:
<img width="551" alt="Снимок экрана 2021-05-20 в 12 51 48" src="https://user-images.githubusercontent.com/48605213/118958488-25654d80-b96a-11eb-9c7c-2e6a46425ab2.png">
<img width="870" alt="Снимок экрана 2021-05-20 в 12 52 14" src="https://user-images.githubusercontent.com/48605213/118958549-34e49680-b96a-11eb-8fd0-a9d1079b1fb9.png">
<img width="845" alt="Снимок экрана 2021-05-20 в 12 52 49" src="https://user-images.githubusercontent.com/48605213/118958660-4af25700-b96a-11eb-870f-30220ddb61a3.png">

It works fine, however when I am trying to access video information from another following server, aspect ratio is always zero.

How can I fix this?

Thanks for your attention.

**Comment by zanhesl** [comment]
Maybe someone could tell me, which procedure initialises video copying from followed instance (I have redundancy enabled on both servers).

**Comment by zanhesl** [comment]
My fork is here: https://github.com/zanhesl/PeerTube/tree/pocketnet-updates, and the last commit somehow brakes redundancy at all

**Comment by Chocobozzz** [comment]
Hello,

You can create a plugin instead using `filter:api.video.get.result` hook: https://docs.joinpeertube.org/api-plugins
