### ISSUE TITLE
Gettting errors on creating instance on digital ocean ubuntu Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by alaksandarjesus** [Chocobozzz/PeerTube#4117]
**Describe the problem**

I am getting the below error
`could not change directory to "/root": Permission denied`

while running
`sudo -u postgres createdb -O peertube -E UTF8 -T template0 peertube_prod`

![image](https://user-images.githubusercontent.com/4712552/119213832-cb869400-badf-11eb-90de-11a397b48640.png)

Also getting ./peertube-latest not found

`cd /var/www/peertube`
`sudo -u peertube ln -s versions/peertube-${VERSION} ./peertube-latest`
`cd ./peertube-latest && sudo -H -u peertube yarn install --production --pure-lockfile`

![image](https://user-images.githubusercontent.com/4712552/119213881-215b3c00-bae0-11eb-9681-1cc44bd3306e.png)

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Additional information**

* PeerTube instance:
  * version:
  * NodeJS version: 16.1.0
  * Ffmpeg version:  4.2.4-1ubuntu0.1
  * Redis version: 5.0.7 
  * PostgreSQL version: 12.6

**Comment by Chocobozzz** [comment]
Run:

`rm /var/www/peertube/peertube-latest` and retry the command.

Also, don't run install guide in `/root` directory. `cd /var/www/peertube` first.
