### ISSUE TITLE
Add touchscreen seeking

### ISSUE THREAD

**Issue by Kohoshi12** [Chocobozzz/PeerTube#4118]
**Describe the problem to be solved**

Seeking is a common feature on video players today, it helps the user to see a specific part of the video or to skip a boring part of one. Most of the Peertube clients supports time seeking.

**Describe the solution you would like:**

Add the function of tapping twice to seek 10 or 20 seconds of a video on the Peertube video player on touchscreen devices

**Describe alternatives you have considered**

**Comment by rigelk** [comment]
hi @Kohoshi12,

The player can already seek forward or backward by 5s steps, using left or right arrows respectively, but for that you need to focus the player unlike on YouTube where the whole page has this shortcut.

**Comment by Kohoshi12** [comment]
I was referrig to touchscreen device which time seeking isn't available on the peertube player.

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/3113

**Comment by briner** [comment]
I've been wanting to move forward by touching the screen of my laptop on the right side. But there is no reaction of the player.

Somehow, I was wishing that:
- clicking on the left will move backward to 5s
- clicking on the right will move forward to 5s
- clicking on the middle will pause/start the player.
