### ISSUE TITLE
Playback issues in Android 4.2.2

### ISSUE THREAD

**Issue by Phyks** [Chocobozzz/PeerTube#412]
Hi,

* **PeerTube version or URL:** https://meilleurtube.delire.party/videos/watch/e4f5507b-ce1f-4451-bac5-b5a0f30a017e
* **Browser name/version:** Fennec for Android (latest from F-Droid) on a Fairphone 1 running Android 4.2.2.
* **NodeJS version:** /

* **What is the expected behaviour?**

I tried playing the above mentionned video on my Fairphone and got a very laggy video playing. On my laptop, I don't have any issue. It seems the video is sent as MP4 (H264?) and https://caniuse.com/mpeg4 tends to indicate that it lacks hardware acceleration support in Firefox for Android, so I guess my device is simply not powerful enough to play it.

I used WebRTC on this device in the past, using http://opentokrtc.com/, and it was working fine. As far as I understood, WebRTC is using VP8/VP9 which should have hardware acceleration.

I never encountered issues with other video streaming platforms so far, so I guess they are not streaming MP4 on my device. Not sure about what peertube could do, but a possible fix might be to reencode with FFMPEG all the videos into WebM and MP4, and serve the most appropriate version afterwards? Not sure how this could be efficiently coupled to the WebTorrent part though :/

* **Browser console log if useful (Gist/Pastebin...):** /
* **Server log if useful (Gist/Pastebin...):** /

Thanks!

**Comment by tcitworld** [comment]
Nah, Firefox on Android does support h264 decoding by handling it to the device itself.
Your device just probably doesn't handles it, sorry. https://arstechnica.com/information-technology/2012/11/mozilla-ships-firefox-with-h-264-support-on-android/

**Comment by Phyks** [comment]
I tried to google a bit for my device SoC (MediaTek MT6589 MT6589m) and GPU (PowerVR SGX544) but did not find much about hardware acceleration :/

I know that Youtube videos play nicely on my device, so I tried to check https://www.youtube.com/html5?hl=fr. Everything is green except for "MSE & WebM VP9" though.

I'll try to debug more thoroughly what PeerTube is sending vs what Youtube is sending to my device.

**Comment by Chocobozzz** [comment]
@Phyks Could you try with Chrome (just a test)?

And try with Firefox directly on the video link https://meilleurtube.delire.party/static/webseed/e4f5507b-ce1f-4451-bac5-b5a0f30a017e-576.mp4

**Comment by Phyks** [comment]
Just thinking back about it and quite related to this issue, not sure if it would be difficult/worth it to make a "diagnostics" page for a given video, giving infos about the video format, the streaming method used and other useful stuff to put in such an issue?

**Comment by Chocobozzz** [comment]
I tested the video on Android 4.3 (Galaxy Note 3) and it seems to work well so I'm closing this issue :)
