### ISSUE TITLE
Channels are invisible or confusing for viewers on Mastodon, channels should be separate accounts

### ISSUE THREAD

**Issue by FediVideos** [Chocobozzz/PeerTube#4120]
**Describe the problem to be solved**

Some PeerTube users have a single account that shares extremely different content types (for example food recipes and gaming walkthroughs), and they use channels to differentiate the content (for example a food channel and a gaming channel). The idea is that people who enjoy food follow the food channel, in this example.

However, when these videos are shared individually on Mastodon, there is no clue at all that they belong to a channel. All that people see is the video and the account (not the channel) that it came from.

If Mastodon viewers enjoy a video and want more content like it, their only option is to follow the account, not the channel. But if they do that, they get irrelevant stuff from all the other channels within that account.

(This is a problem I see a lot on my Mastodon account FediVideos, because I recommend and share individual videos from PeerTube to people on the rest of the Fediverse.)

Additionally, if people on Mastodon DO find a channel by other means, it appears to be nothing but boosts. In those circumstances, most Mastodon users follow the original posters rather than the people who boosted.

**Describe the solution you would like:**

PeerTube channels should be separate accounts, the same way YouTube channels are.

This would be much less confusing for people who come across PeerTube videos on Mastodon.

**Describe alternatives you have considered**

A workaround is if PeerTube users set up separate PT accounts for each channel, but I do not think PeerTube users are aware of this channels confusion issue. By the time they find out about the problem, it is too late to segregate their videos into separate accounts.

**Comment by rigelk** [comment]
hi @FediVideos,

Have you opened an issue on Mastodon’s repo regarding this problem?

Arguably this is a problem of Mastodon not attributing properly the created video to the channel. Mastodon parses the ActivityPub representation of a video’s `attributedTo` field, only taking into account its _account_ attribution and not its _group_ attribution (the channel actor): https://github.com/tootsuite/mastodon/blob/main/app/lib/activitypub/activity/create.rb#L126

For instance, a video’s `attributedTo` field:

```json
"attributedTo": [
    {
      "type": "Person",
      "id": "https://framatube.org/accounts/framasoft"
    },
    {
      "type": "Group",
      "id": "https://framatube.org/video-channels/bf54d359-cfad-4935-9d45-9d6be93f63e8"
    }
]
```

---

> PeerTube channels should be separate accounts, the same way YouTube channels are.
> 
> This would be much less confusing for people who come across PeerTube videos on Mastodon.

Channels are a structural feat of PeerTube, and I don’t think that downside alone balances the advantages to the point of justifying switching back to an accounts-only paradigm.
