### ISSUE TITLE
Gloabl search surfaces irrelevant results

### ISSUE THREAD

**Issue by 12people** [Chocobozzz/PeerTube#4122]
**Describe the current behavior**
Searching for a phrase using the global search can surface irrelevant results while hiding relevant ones.

**Steps to reproduce:**

1. [Search "brad sucks"](https://sepiasearch.org/search?search=brad%20sucks) (with or without quotes — it doesn't matter; it should be noted that Brad Sucks is the name of a [one-man band](https://www.bradsucks.net/), not a random insult) 
2. The videos on at least the first few pages fail to take the whole phrase into account. They tend to be relevant only to the word "sucks" or the word "brad", but not to "brad sucks" as a whole

**Describe the expected behavior**
1. Brad Sucks' songs should appear among the first few results — e.g. [this video](https://tube.4aem.com/videos/watch/29294399-0407-4c36-babf-cb60b04d080b) or [this video](https://tube.4aem.com/videos/watch/f55f2236-8719-41a7-97b8-8d48adeab09e)

**Comment by rigelk** [comment]
hi @12people,

You should open that issue at https://framagit.org/framasoft/peertube/search-index

**Comment by 12people** [comment]
Done: https://framagit.org/framasoft/peertube/search-index/-/issues/31
