### ISSUE TITLE
multiple languages

### ISSUE THREAD

**Issue by Slender1808** [Chocobozzz/PeerTube#4124]
I was analyzing here it would be very useful to have a player that loads the audio separately from the image in this way if someone is watching something in another language you don't need to create another video just to have other audio options

**Comment by rigelk** [comment]
Hi! Please look out for related issues before creating one, as https://github.com/Chocobozzz/PeerTube/issues/939 already covers this. You can then detail further your use case there, and upvote the issue to help us triage it.
