### ISSUE TITLE
chocobozzz/peertube:production-buster incompatible with postgres:10-alpine

### ISSUE THREAD

**Issue by Utopiah** [Chocobozzz/PeerTube#4125]
**Describe the problem**
chocobozzz/peertube:production-buster is incompatible with postgres:10-alpine

**Provide the exact sequence of commands / steps that you executed before running into the problem**
using the official docker-compose, migrating from 2.x to 3.0.0 worked fine. Migrating to chocobozzz/peertube:production-buster blocked due to PostgreSQL 10 to 13 incompatibility. Manual steps failed so reverted to PostgreSQL 10. The interface worked but then while clicking on a video for viewing or edition, error 500. Reverting then peertube also from production-buster to chocobozzz/peertube:v3.0.0-buster makes viewing and updating working again.

**Additional information**
I imagine this is a rare use case but could help others stuck in this situation.

* PeerTube instance:
  * version: chocobozzz/peertube:v3.0.0-buster
  * PostgreSQL version: 10

Because this is such a corner case following https://github.com/Chocobozzz/PeerTube/pull/2531#discussion_r398844344 and migrating to PostgreSQL 13 then chocobozzz/peertube:production-buster should be the default way.

**Comment by rigelk** [comment]
hi @Utopiah,

PeerTube 3.0.0 is compatible with PostgreSQL v13: https://github.com/Chocobozzz/PeerTube/blob/v3.0.0/package.json#L10

However you need to follow manual PostgreSQL-specific migration steps, as mandated between all major PostgreSQL updates by PostgreSQL. This isn't an issue with PeerTube here, and database version updates are out of the scope of PeerTube.
