### ISSUE TITLE
Accounts incorrectly stated as PeerTube  accounts

### ISSUE THREAD

**Issue by AutomCoding** [Chocobozzz/PeerTube#4128]
**Describe the current behavior**
In this latest update (3.2.0), all account pages got the title "PeerTube account", even those who are not so.

**Steps to reproduce:**
1. Go to a video with comments from a non-PeerTube account (like [What is PeerTube?](https://framatube.org/videos/watch/9c9de5e8-0a1e-484a-b099-e80766180a6d) on Framatube)
2. Click on an account name above one of the comments
3. The label in the account info box will say "PeerTube account" regardless of the account's origin

**Describe the expected behavior**
This should
* display the correct account type

or

* not be displayed if it is too difficult to determine the instance type

**Additional information**

* PeerTube instance:
  * URL: not relevant
  * version: 3.2.0
  * NodeJS version: not relevant
  * Ffmpeg version: not relevant

* Browser name, version and platforms on which you could reproduce the bug: not relevant
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks, fixed in https://github.com/Chocobozzz/PeerTube/commit/2f6a237f307e6df166def6685741126e35903a35
