### ISSUE TITLE
"This file is not supported" when I try to upload via api

### ISSUE THREAD

**Issue by diazepan** [Chocobozzz/PeerTube#4129]
I tried to upload a video using the curl script 
https://docs.joinpeertube.org/api-rest-reference.html#operation/uploadLegacy

## DEPENDENCIES: jq
USERNAME="myuser"
PASSWORD="mypassword"
FILE_PATH="Prueba.mp4"
CHANNEL_ID="4"
NAME="Prueba"
API="https://videos.pueseso.club/api/v1/"

## AUTH
client_id=$(curl -s "$API/oauth-clients/local" | jq -r ".client_id")
client_secret=$(curl -s "$API/oauth-clients/local" | jq -r ".client_secret")
token=$(curl -s "$API/users/token" \
  --data client_id="$client_id" \
  --data client_secret="$client_secret" \
  --data grant_type=password \
  --data username="$USERNAME" \
  --data password="$PASSWORD" \
  | jq -r ".access_token")

## VIDEO UPLOAD
curl -s "$API/videos/upload" \
  -H "Authorization: Bearer $token" \
  --max-time 600 \
  --form videofile=@"$FILE_PATH" \
  --form channelId=$CHANNEL_ID \
  --form name="$NAME"

and the return says "{"error":"This file is not supported. Please, make sure it is of the following type: .webm, .ogv, .mp4"}"

However my file is an .mp4 file

**Comment by Chocobozzz** [comment]
Please enable debug logs on your instance and paste lines before the HTTP request.

You could also use https://docs.joinpeertube.org/maintain-tools?id=peertube-uploadjs

**Comment by diazepan** [comment]
Here is the log

**Getting the client id and secret**
{"sql":"Executing (default): SELECT \"id\", \"clientId\", \"clientSecret\", \"grants\", \"redirectUris\", \"createdAt\", \"updatedAt\" FROM \"oAuthClient\" AS \"OAuthClientModel\" LIMIT 1;","level":"debug","message":"Executed SQL request","label":"videos.pueseso.club:443","timestamp":"2021-06-01T17:21:10.009Z"}

{"message":"10.251.98.3 - - [01/Jun/2021:17:21:10 +0000] \"GET /api/v1//oauth-clients/local HTTP/1.0\" 200 99 \"-\" \"curl/7.76.1\"\n","level":"info","label":"videos.pueseso.club:443","timestamp":"2021-06-01T17:21:10.017Z"}

{"sql":"Executing (default): SELECT \"id\", \"clientId\", \"clientSecret\", \"grants\", \"redirectUris\", \"createdAt\", \"updatedAt\" FROM \"oAuthClient\" AS \"OAuthClientModel\" LIMIT 1;","level":"debug","message":"Executed SQL request","label":"videos.pueseso.club:443","timestamp":"2021-06-01T17:21:10.103Z"}
{"message":"10.251.98.3 - - [01/Jun/2021:17:21:10 +0000] \"GET /api/v1//oauth-clients/local HTTP/1.0\" 200 99 \"-\" \"curl/7.76.1\"\n","level":"info","label":"videos.pueseso.club:443","timestamp":"2021-06-01T17:21:10.112Z"}

{"message":"Getting Client (clientId: d6dwhwcov1wlyjtms35yxq3b343h2xk9, clientSecret: nvBOhjRondfIkvQuhkquRuI4ldvXiTQg).","level":"debug","label":"videos.pueseso.club:443","timestamp":"2021-06-01T17:21:10.267Z"}

{"sql":"Executing (default): SELECT \"id\", \"clientId\", \"clientSecret\", \"grants\", \"redirectUris\", \"createdAt\", \"updatedAt\" FROM \"oAuthClient\" AS \"OAuthClientModel\" WHERE \"OAuthClientModel\".\"clientId\" = 'd6dwhwcov1wlyjtms35yxq3b343h2xk9' AND \"OAuthClientModel\".\"clientSecret\" = 'nvBOhjRondfIkvQuhkquRuI4ldvXiTQg' LIMIT 1;","level":"debug","message":"Executed SQL request","label":"videos.pueseso.club:443","timestamp":"2021-06-01T17:21:10.277Z"}

{"message":"Getting User (username/email: root, password: ******).","level":"debug","label":"videos.pueseso.club:443","timestamp":"2021-06-01T17:21:10.298Z"}

**Getting the token**
{"sql":"Executing (default): SELECT \"UserModel\".\"id\", \"UserModel\".\"password\", \"UserModel\".\"username\", \"UserModel\".\"email\", \"UserModel\".\"pendingEmail\", \"UserModel\".\"emailVerified\", \"UserModel\".\"nsfwPolicy\", \"UserModel\".\"webTorrentEnabled\", \"UserModel\".\"videosHistoryEnabled\", \"UserModel\".\"autoPlayVideo\", \"UserModel\".\"autoPlayNextVideo\", \"UserModel\".\"autoPlayNextVideoPlaylist\", \"UserModel\".\"videoLanguages\", \"UserModel\".\"adminFlags\", \"UserModel\".\"blocked\", \"UserModel\".\"blockedReason\", \"UserModel\".\"role\", \"UserModel\".\"videoQuota\", \"UserModel\".\"videoQuotaDaily\", \"UserModel\".\"theme\", \"UserModel\".\"noInstanceConfigWarningModal\", \"UserModel\".\"noWelcomeModal\", \"UserModel\".\"pluginAuth\", \"UserModel\".\"feedToken\", \"UserModel\".\"lastLoginDate\", \"UserModel\".\"createdAt\", \"UserModel\".\"updatedAt\", \"Account\".\"id\" AS \"Account.id\", \"Account\".\"name\" AS \"Account.name\", \"Account\".\"description\" AS \"Account.description\", \"Account\".\"actorId\" AS \"Account.actorId\", \"Account\".\"userId\" AS \"Account.userId\", \"Account\".\"applicationId\" AS \"Account.applicationId\", \"Account\".\"createdAt\" AS \"Account.createdAt\", \"Account\".\"updatedAt\" AS \"Account.updatedAt\", \"Account->Actor\".\"id\" AS \"Account.Actor.id\", \"Account->Actor\".\"type\" AS \"Account.Actor.type\", \"Account->Actor\".\"preferredUsername\" AS \"Account.Actor.preferredUsername\", \"Account->Actor\".\"url\" AS \"Account.Actor.url\", \"Account->Actor\".\"publicKey\" AS \"Account.Actor.publicKey\", \"Account->Actor\".\"privateKey\" AS \"Account.Actor.privateKey\", \"Account->Actor\".\"followersCount\" AS \"Account.Actor.followersCount\", \"Account->Actor\".\"followingCount\" AS \"Account.Actor.followingCount\", \"Account->Actor\".\"inboxUrl\" AS \"Account.Actor.inboxUrl\", \"Account->Actor\".\"outboxUrl\" AS \"Account.Actor.outboxUrl\", \"Account->Actor\".\"sharedInboxUrl\" AS \"Account.Actor.sharedInboxUrl\", \"Account->Actor\".\"followersUrl\" AS \"Account.Actor.followersUrl\", \"Account->Actor\".\"followingUrl\" AS \"Account.Actor.followingUrl\", \"Account->Actor\".\"avatarId\" AS \"Account.Actor.avatarId\", \"Account->Actor\".\"serverId\" AS \"Account.Actor.serverId\", \"Account->Actor\".\"createdAt\" AS \"Account.Actor.createdAt\", \"Account->Actor\".\"updatedAt\" AS \"Account.Actor.updatedAt\", \"Account->Actor->Server\".\"id\" AS \"Account.Actor.Server.id\", \"Account->Actor->Server\".\"host\" AS \"Account.Actor.Server.host\", \"Account->Actor->Server\".\"redundancyAllowed\" AS \"Account.Actor.Server.redundancyAllowed\", \"Account->Actor->Server\".\"createdAt\" AS \"Account.Actor.Server.createdAt\", \"Account->Actor->Server\".\"updatedAt\" AS \"Account.Actor.Server.updatedAt\", \"Account->Actor->Avatar\".\"id\" AS \"Account.Actor.Avatar.id\", \"Account->Actor->Avatar\".\"filename\" AS \"Account.Actor.Avatar.filename\", \"Account->Actor->Avatar\".\"fileUrl\" AS \"Account.Actor.Avatar.fileUrl\", \"Account->Actor->Avatar\".\"onDisk\" AS \"Account.Actor.Avatar.onDisk\", \"Account->Actor->Avatar\".\"createdAt\" AS \"Account.Actor.Avatar.createdAt\", \"Account->Actor->Avatar\".\"updatedAt\" AS \"Account.Actor.Avatar.updatedAt\", \"NotificationSetting\".\"id\" AS \"NotificationSetting.id\", \"NotificationSetting\".\"newVideoFromSubscription\" AS \"NotificationSetting.newVideoFromSubscription\", \"NotificationSetting\".\"newCommentOnMyVideo\" AS \"NotificationSetting.newCommentOnMyVideo\", \"NotificationSetting\".\"abuseAsModerator\" AS \"NotificationSetting.abuseAsModerator\", \"NotificationSetting\".\"videoAutoBlacklistAsModerator\" AS \"NotificationSetting.videoAutoBlacklistAsModerator\", \"NotificationSetting\".\"blacklistOnMyVideo\" AS \"NotificationSetting.blacklistOnMyVideo\", \"NotificationSetting\".\"myVideoPublished\" AS \"NotificationSetting.myVideoPublished\", \"NotificationSetting\".\"myVideoImportFinished\" AS \"NotificationSetting.myVideoImportFinished\", \"NotificationSetting\".\"newUserRegistration\" AS \"NotificationSetting.newUserRegistration\", \"NotificationSetting\".\"newInstanceFollower\" AS \"NotificationSetting.newInstanceFollower\", \"NotificationSetting\".\"autoInstanceFollowing\" AS \"NotificationSetting.autoInstanceFollowing\", \"NotificationSetting\".\"newFollow\" AS \"NotificationSetting.newFollow\", \"NotificationSetting\".\"commentMention\" AS \"NotificationSetting.commentMention\", \"NotificationSetting\".\"abuseStateChange\" AS \"NotificationSetting.abuseStateChange\", \"NotificationSetting\".\"abuseNewMessage\" AS \"NotificationSetting.abuseNewMessage\", \"NotificationSetting\".\"userId\" AS \"NotificationSetting.userId\", \"NotificationSetting\".\"createdAt\" AS \"NotificationSetting.createdAt\", \"NotificationSetting\".\"updatedAt\" AS \"NotificationSetting.updatedAt\" FROM \"user\" AS \"UserModel\" INNER JOIN \"account\" AS \"Account\" ON \"UserModel\".\"id\" = \"Account\".\"userId\" INNER JOIN \"actor\" AS \"Account->Actor\" ON \"Account\".\"actorId\" = \"Account->Actor\".\"id\" LEFT OUTER JOIN \"server\" AS \"Account->Actor->Server\" ON \"Account->Actor\".\"serverId\" = \"Account->Actor->Server\".\"id\" LEFT OUTER JOIN \"avatar\" AS \"Account->Actor->Avatar\" ON \"Account->Actor\".\"avatarId\" = \"Account->Actor->Avatar\".\"id\" INNER JOIN \"userNotificationSetting\" AS \"NotificationSetting\" ON \"UserModel\".\"id\" = \"NotificationSetting\".\"userId\" WHERE (lower(\"username\") = lower('root') OR \"UserModel\".\"email\" = 'root') LIMIT 1;","level":"debug","message":"Executed SQL request","label":"videos.pueseso.club:443","timestamp":"2021-06-01T17:21:10.336Z"}

{"message":"Saving token 1730b35a1010d395d40078f216bcb379a2059873 for client 1 and user 1.","level":"debug","label":"videos.pueseso.club:443","timestamp":"2021-06-01T17:21:10.889Z"}
{"sql":"Executing (default): INSERT INTO \"oAuthToken\" (\"id\",\"accessToken\",\"accessTokenExpiresAt\",\"refreshToken\",\"refreshTokenExpiresAt\",\"authName\",\"userId\",\"oAuthClientId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING \"id\",\"accessToken\",\"accessTokenExpiresAt\",\"refreshToken\",\"refreshTokenExpiresAt\",\"authName\",\"userId\",\"oAuthClientId\",\"createdAt\",\"updatedAt\";","level":"debug","message":"Executed SQL request","label":"videos.pueseso.club:443","timestamp":"2021-06-01T17:21:10.915Z"}

{"sql":"Executing (default): UPDATE \"user\" SET \"lastLoginDate\"=$1,\"updatedAt\"=$2 WHERE \"id\" = $3","level":"debug","message":"Executed SQL request","label":"videos.pueseso.club:443","timestamp":"2021-06-01T17:21:10.943Z"}
{"message":"10.251.98.3 - - [01/Jun/2021:17:21:10 +0000] \"POST /api/v1//users/token HTTP/1.0\" 200 194 \"-\" \"curl/7.76.1\"\n","level":"info","label":"videos.pueseso.club:443","timestamp":"2021-06-01T17:21:10.967Z"}

{"message":"Getting access token (bearerToken: 1730b35a1010d395d40078f216bcb379a2059873).","level":"debug","label":"videos.pueseso.club:443","timestamp":"2021-06-01T17:21:12.710Z"}

**Trying to upload the video**
{"sql":"Executing (default): SELECT \"OAuthTokenModel\".\"id\", \"OAuthTokenModel\".\"accessToken\", \"OAuthTokenModel\".\"accessTokenExpiresAt\", \"OAuthTokenModel\".\"refreshToken\", \"OAuthTokenModel\".\"refreshTokenExpiresAt\", \"OAuthTokenModel\".\"authName\", \"OAuthTokenModel\".\"userId\", \"OAuthTokenModel\".\"oAuthClientId\", \"OAuthTokenModel\".\"createdAt\", \"OAuthTokenModel\".\"updatedAt\", \"User\".\"id\" AS \"User.id\", \"User\".\"password\" AS \"User.password\", \"User\".\"username\" AS \"User.username\", \"User\".\"email\" AS \"User.email\", \"User\".\"pendingEmail\" AS \"User.pendingEmail\", \"User\".\"emailVerified\" AS \"User.emailVerified\", \"User\".\"nsfwPolicy\" AS \"User.nsfwPolicy\", \"User\".\"webTorrentEnabled\" AS \"User.webTorrentEnabled\", \"User\".\"videosHistoryEnabled\" AS \"User.videosHistoryEnabled\", \"User\".\"autoPlayVideo\" AS \"User.autoPlayVideo\", \"User\".\"autoPlayNextVideo\" AS \"User.autoPlayNextVideo\", \"User\".\"autoPlayNextVideoPlaylist\" AS \"User.autoPlayNextVideoPlaylist\", \"User\".\"videoLanguages\" AS \"User.videoLanguages\", \"User\".\"adminFlags\" AS \"User.adminFlags\", \"User\".\"blocked\" AS \"User.blocked\", \"User\".\"blockedReason\" AS \"User.blockedReason\", \"User\".\"role\" AS \"User.role\", \"User\".\"videoQuota\" AS \"User.videoQuota\", \"User\".\"videoQuotaDaily\" AS \"User.videoQuotaDaily\", \"User\".\"theme\" AS \"User.theme\", \"User\".\"noInstanceConfigWarningModal\" AS \"User.noInstanceConfigWarningModal\", \"User\".\"noWelcomeModal\" AS \"User.noWelcomeModal\", \"User\".\"pluginAuth\" AS \"User.pluginAuth\", \"User\".\"feedToken\" AS \"User.feedToken\", \"User\".\"lastLoginDate\" AS \"User.lastLoginDate\", \"User\".\"createdAt\" AS \"User.createdAt\", \"User\".\"updatedAt\" AS \"User.updatedAt\", \"User->Account\".\"id\" AS \"User.Account.id\", \"User->Account->Actor\".\"id\" AS \"User.Account.Actor.id\", \"User->Account->Actor\".\"url\" AS \"User.Account.Actor.url\" FROM \"oAuthToken\" AS \"OAuthTokenModel\" INNER JOIN \"user\" AS \"User\" ON \"OAuthTokenModel\".\"userId\" = \"User\".\"id\" INNER JOIN \"account\" AS \"User->Account\" ON \"User\".\"id\" = \"User->Account\".\"userId\" INNER JOIN \"actor\" AS \"User->Account->Actor\" ON \"User->Account\".\"actorId\" = \"User->Account->Actor\".\"id\" WHERE \"OAuthTokenModel\".\"accessToken\" = '1730b35a1010d395d40078f216bcb379a2059873' LIMIT 1;","level":"debug","message":"Executed SQL request","label":"videos.pueseso.club:443","timestamp":"2021-06-01T17:21:12.746Z"}

{"parameters":{"channelId":4,"name":"Prueba"},"files":{"videofile":[{"fieldname":"videofile","originalname":"Prueba.mp4","encoding":"7bit","mimetype":"application/octet-stream","destination":"/var/www/peertube/storage/tmp/","filename":"e84319309ff0b8d101a3755ff1a9a642.mp4","path":"/var/www/peertube/storage/tmp/e84319309ff0b8d101a3755ff1a9a642.mp4","size":4314852}]},"level":"debug","message":"Checking videosAdd parameters","label":"videos.pueseso.club:443","timestamp":"2021-06-01T17:21:13.446Z"}

{"sql":"Executing (default): SELECT \"VideoChannelModel\".\"id\", \"VideoChannelModel\".\"name\", \"VideoChannelModel\".\"description\", \"VideoChannelModel\".\"support\", \"VideoChannelModel\".\"actorId\", \"VideoChannelModel\".\"accountId\", \"VideoChannelModel\".\"createdAt\", \"VideoChannelModel\".\"updatedAt\", \"Actor\".\"id\" AS \"Actor.id\", \"Actor\".\"type\" AS \"Actor.type\", \"Actor\".\"preferredUsername\" AS \"Actor.preferredUsername\", \"Actor\".\"url\" AS \"Actor.url\", \"Actor\".\"publicKey\" AS \"Actor.publicKey\", \"Actor\".\"privateKey\" AS \"Actor.privateKey\", \"Actor\".\"followersCount\" AS \"Actor.followersCount\", \"Actor\".\"followingCount\" AS \"Actor.followingCount\", \"Actor\".\"inboxUrl\" AS \"Actor.inboxUrl\", \"Actor\".\"outboxUrl\" AS \"Actor.outboxUrl\", \"Actor\".\"sharedInboxUrl\" AS \"Actor.sharedInboxUrl\", \"Actor\".\"followersUrl\" AS \"Actor.followersUrl\", \"Actor\".\"followingUrl\" AS \"Actor.followingUrl\", \"Actor\".\"avatarId\" AS \"Actor.avatarId\", \"Actor\".\"serverId\" AS \"Actor.serverId\", \"Actor\".\"createdAt\" AS \"Actor.createdAt\", \"Actor\".\"updatedAt\" AS \"Actor.updatedAt\", \"Actor->Server\".\"id\" AS \"Actor.Server.id\", \"Actor->Server\".\"host\" AS \"Actor.Server.host\", \"Actor->Server\".\"redundancyAllowed\" AS \"Actor.Server.redundancyAllowed\", \"Actor->Server\".\"createdAt\" AS \"Actor.Server.createdAt\", \"Actor->Server\".\"updatedAt\" AS \"Actor.Server.updatedAt\", \"Actor->Avatar\".\"id\" AS \"Actor.Avatar.id\", \"Actor->Avatar\".\"filename\" AS \"Actor.Avatar.filename\", \"Actor->Avatar\".\"fileUrl\" AS \"Actor.Avatar.fileUrl\", \"Actor->Avatar\".\"onDisk\" AS \"Actor.Avatar.onDisk\", \"Actor->Avatar\".\"createdAt\" AS \"Actor.Avatar.createdAt\", \"Actor->Avatar\".\"updatedAt\" AS \"Actor.Avatar.updatedAt\", \"Account\".\"id\" AS \"Account.id\", \"Account\".\"name\" AS \"Account.name\", \"Account\".\"description\" AS \"Account.description\", \"Account\".\"actorId\" AS \"Account.actorId\", \"Account\".\"userId\" AS \"Account.userId\", \"Account\".\"applicationId\" AS \"Account.applicationId\", \"Account\".\"createdAt\" AS \"Account.createdAt\", \"Account\".\"updatedAt\" AS \"Account.updatedAt\", \"Account->Actor\".\"id\" AS \"Account.Actor.id\", \"Account->Actor\".\"type\" AS \"Account.Actor.type\", \"Account->Actor\".\"preferredUsername\" AS \"Account.Actor.preferredUsername\", \"Account->Actor\".\"url\" AS \"Account.Actor.url\", \"Account->Actor\".\"publicKey\" AS \"Account.Actor.publicKey\", \"Account->Actor\".\"privateKey\" AS \"Account.Actor.privateKey\", \"Account->Actor\".\"followersCount\" AS \"Account.Actor.followersCount\", \"Account->Actor\".\"followingCount\" AS \"Account.Actor.followingCount\", \"Account->Actor\".\"inboxUrl\" AS \"Account.Actor.inboxUrl\", \"Account->Actor\".\"outboxUrl\" AS \"Account.Actor.outboxUrl\", \"Account->Actor\".\"sharedInboxUrl\" AS \"Account.Actor.sharedInboxUrl\", \"Account->Actor\".\"followersUrl\" AS \"Account.Actor.followersUrl\", \"Account->Actor\".\"followingUrl\" AS \"Account.Actor.followingUrl\", \"Account->Actor\".\"avatarId\" AS \"Account.Actor.avatarId\", \"Account->Actor\".\"serverId\" AS \"Account.Actor.serverId\", \"Account->Actor\".\"createdAt\" AS \"Account.Actor.createdAt\", \"Account->Actor\".\"updatedAt\" AS \"Account.Actor.updatedAt\", \"Account->Actor->Server\".\"id\" AS \"Account.Actor.Server.id\", \"Account->Actor->Server\".\"host\" AS \"Account.Actor.Server.host\", \"Account->Actor->Server\".\"redundancyAllowed\" AS \"Account.Actor.Server.redundancyAllowed\", \"Account->Actor->Server\".\"createdAt\" AS \"Account.Actor.Server.createdAt\", \"Account->Actor->Server\".\"updatedAt\" AS \"Account.Actor.Server.updatedAt\", \"Account->Actor->Avatar\".\"id\" AS \"Account.Actor.Avatar.id\", \"Account->Actor->Avatar\".\"filename\" AS \"Account.Actor.Avatar.filename\", \"Account->Actor->Avatar\".\"fileUrl\" AS \"Account.Actor.Avatar.fileUrl\", \"Account->Actor->Avatar\".\"onDisk\" AS \"Account.Actor.Avatar.onDisk\", \"Account->Actor->Avatar\".\"createdAt\" AS \"Account.Actor.Avatar.createdAt\", \"Account->Actor->Avatar\".\"updatedAt\" AS \"Account.Actor.Avatar.updatedAt\" FROM \"videoChannel\" AS \"VideoChannelModel\" LEFT OUTER JOIN \"actor\" AS \"Actor\" ON \"VideoChannelModel\".\"actorId\" = \"Actor\".\"id\" LEFT OUTER JOIN \"server\" AS \"Actor->Server\" ON \"Actor\".\"serverId\" = \"Actor->Server\".\"id\" LEFT OUTER JOIN \"avatar\" AS \"Actor->Avatar\" ON \"Actor\".\"avatarId\" = \"Actor->Avatar\".\"id\" INNER JOIN \"account\" AS \"Account\" ON \"VideoChannelModel\".\"accountId\" = \"Account\".\"id\" INNER JOIN \"actor\" AS \"Account->Actor\" ON \"Account\".\"actorId\" = \"Account->Actor\".\"id\" LEFT OUTER JOIN \"server\" AS \"Account->Actor->Server\" ON \"Account->Actor\".\"serverId\" = \"Account->Actor->Server\".\"id\" LEFT OUTER JOIN \"avatar\" AS \"Account->Actor->Avatar\" ON \"Account->Actor\".\"avatarId\" = \"Account->Actor->Avatar\".\"id\" WHERE \"VideoChannelModel\".\"id\" = 4;","level":"debug","message":"Executed SQL request","label":"videos.pueseso.club:443","timestamp":"2021-06-01T17:21:13.500Z"}

{"message":"10.251.98.3 - - [01/Jun/2021:17:21:13 +0000] \"POST /api/v1//videos/upload HTTP/1.0\" 415 104 \"-\" \"curl/7.76.1\"\n","level":"info","label":"videos.pueseso.club:443","timestamp":"2021-06-01T17:21:13.562Z"}

**Comment by Chocobozzz** [comment]
The mime type is not set by curl. Try

```
curl -s "$API/videos/upload"
-H "Authorization: Bearer $token"
--max-time 600
--form videofile=@"$FILE_PATH;type=video/mp4"
--form channelId=$CHANNEL_ID
--form name="$NAME"
```

**Comment by diazepan** [comment]
it worked. Thank you
