### ISSUE TITLE
Banner stays white in dark mode

### ISSUE THREAD

**Issue by Elrondo46** [Chocobozzz/PeerTube#4132]
**Describe the current behavior**

Default banner is white characters are white too

**Steps to reproduce:**

Just install the last peertube version with dark mode theme

**Describe the expected behavior**

**Additional information**

* PeerTube instance:
  * URL: peertube.pcservice46.fr
  * version: 3.2.0

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://framagit.org/framasoft/peertube/official-plugins/-/commit/db12786b275d2cf08a719da9ca7c203bc6cac610
