### ISSUE TITLE
Avatar (or error message) extends beyond its allocated space.

### ISSUE THREAD

**Issue by Altonss** [Chocobozzz/PeerTube#4136]
**Describe the current behavior**
The avatar of an account is not correctly displayed:
![image](https://user-images.githubusercontent.com/66519591/120117653-853fcd80-c18e-11eb-88fe-efe553e0ec0e.png)

**Steps to reproduce:**

1. Go to https://peertube.tv/videos/watch/0c18e708-a739-4f42-954e-0b073be2f236
2. Scroll to the last comment 
3. Look at the avatar

**Describe the expected behavior**
The avatar (or the associated error message) should not extend beyond its allocated space.

* PeerTube instance: peertube.tv
  * URL: https://peertube.tv/videos/watch/0c18e708-a739-4f42-954e-0b073be2f236
  * version: 3.2.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox 88.0.1 on GNU/Linux
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Altonss** [comment]
On the original instance hosting the content (peertube 2.4.0) all seems fine: https://tube.piweb.be/videos/watch/0c18e708-a739-4f42-954e-0b073be2f236

**Comment by kontrollanten** [comment]
Hi! Did you run [regenerate-thumbnails](https://docs.joinpeertube.org/maintain-tools?id=regenerate-thumbnailsjs)?

**Comment by Chocobozzz** [comment]
Please paste server logs above the `https://peertube.tv/lazy-static/avatars/3ee2a013-101c-4cc2-9a44-2d03c507ff22.png` request

**Comment by Altonss** [comment]
> Please paste server logs above the `https://peertube.tv/lazy-static/avatars/3ee2a013-101c-4cc2-9a44-2d03c507ff22.png` request

It displays `Not Found` when I go to this url.
I must say I am just a user, not the admin of the instance :)

**Comment by Chocobozzz** [comment]
Unfortunately without server logs it's difficult to help

**Comment by Altonss** [comment]
I can ping @mstdn the admin of the instance

**Comment by mstdn** [comment]
Hi guys! I'm checking it later for you :-) Currently not with a desktop

**Comment by Altonss** [comment]
Were you able to find the logs? (I assume you just forgot to look for it, but don't worry it's really not an urgent issue :) )

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/4071
