### ISSUE TITLE
Failed plugin installation: plugin state is wrongly displayed as «installed»

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4140]
**Describe the current behavior**

When a plugin fails to start, it is displayed as «installed» in the plugin list. And when we go in the plugin settings, there is no error message, and no settings displayed.

The only ways to see that a plugin has failed are:
- a message on installation that says that the installation failed
- error logs on peertube startup or plugin installation

There is no way to see this information after startup or installation.

**Steps to reproduce:**

1. create a plugin that throw an error on register
2. install this plugin

**Describe the expected behavior**

In plugin list, there should be a state «Error». 

**Additional information**

* PeerTube instance:
  * version: 3.2.0
  * NodeJS version: 12

**Comment by Chocobozzz** [comment]
Sorry for the late. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/9c2e051c56e1ef6b9c9901f492fb506ee5d16def
