### ISSUE TITLE
Last commits of 3.2 release are not in the last docker images

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#4142]
I may be wrong, but it looks like the last official docker images (v3.2.0-buster and production-buster), don't include the fixes on May 28, 2021: https://github.com/Chocobozzz/PeerTube/commit/86dc0b9cc9374cba7548bb613ff43d92f90570a8 and this https://github.com/Chocobozzz/PeerTube/commit/1025ce5df9f5cfa7b96f9712c91d1de6bc699f71

A problem with Docker hub or just a missing merge on master ?

**Comment by rigelk** [comment]
They are only present on develop, as shown by GitHub's interface.

**Comment by kimsible** [comment]
Also on https://github.com/Chocobozzz/PeerTube/commits/release/3.2.0

**Comment by rigelk** [comment]
Ah! You're right, but the tag is fixed before they were added. Supposedly Docker Hub is only considering tags for releases.

**Comment by Chocobozzz** [comment]
The `release/3.2.0` is the WIP branch for the 3.2.x release. It doesn't mean commits pushed on this branch has been released. To know if a commit is included in a release, you can refer to the `3.2.0` tag (example: https://github.com/Chocobozzz/PeerTube/commit/b45afe12f90c654aef8098e55bedfa81ca73b1f4)

**Comment by kimsible** [comment]
Thanks for the explanation !
