### ISSUE TITLE
Error message at first screen

### ISSUE THREAD

**Issue by FathiBenNasr** [Chocobozzz/PeerTube#4145]
Hi,
PeerTube version: 3.2.0
NodeJS version: redis-server/stable,now 5:5.0.3-4+deb10u3 amd64
Ffmpeg version: ffmpeg/stable,stable,now 7:4.1.6-1~deb10u1 amd64
Redis version: redis-server/stable,stable,now 5:5.0.3-4+deb10u2 amd64
PostgreSQL version: postgresql11-server-11.10-1PGDG.rhel7.x86_64 on a dedicated instance
reverse proxy Pound:
Service "PeerTube"
    HeadRequire "Host: myF.Q.D.N"
    BackEnd
        Address internal_ip_address
        Port    80
    End
End

I am running v3.2.0, but this is an old error message i am carrying on with each upgrade since v2.x:
Impossible de récupérer les identifiants du Client OAuth : undefined. Assurez-vous d'avoir correctement configuré PeerTube (dossier config/), en particulier la section "serveur web".
This happens either i connect from a new private browser windows or if i reopen a browser window for an already authenticated user.

{"err":{"statusCode":400,"status":400,"code":400,"message":"Invalid client: client is invalid","name":"invalid_client","stack":"invalid_client: Invalid client: client is invalid\n    at new InvalidClientError (/var/www/peertube/versions/peertube-v3.2.0/node_modules/oauth2-server/lib/errors/invalid-client-error.js:26:14)\n    at Object.<anonymous> (/var/www/peertube/versions/peertube-v3.2.0/dist/server/lib/auth/oauth.js:31:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v3.2.0/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"},"level":"warn","message":"Login error","label":"localhost:9000","timestamp":"2021-06-01T12:01:50.818Z"}
{"tags":["http"],"level":"info","message":"reverse_ssl_proxy_internal_ip (listed in trust_proxy section) - - [01/Jun/2021:12:05:39 +0000] \"GET /api/v1/oauth-clients/local HTTP/1.0\" 403 - \"https://F.Q.D.N/ (hostname in webserver section)\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0\"\n","label":"localhost:9000","timestamp":"2021-06-01T12:05:39.667Z"}

**Comment by rigelk** [comment]
hi @FathiBenNasr,

Please fill the error template, with the asked logs and reverse-proxy configuration.

**Comment by FathiBenNasr** [comment]
Sorry,
PeerTube version: 3.2.0
NodeJS version: redis-server/stable,now 5:5.0.3-4+deb10u3 amd64
Ffmpeg version: ffmpeg/stable,stable,now 7:4.1.6-1~deb10u1 amd64
Redis version: redis-server/stable,stable,now 5:5.0.3-4+deb10u2 amd64
PostgreSQL version: postgresql11-server-11.10-1PGDG.rhel7.x86_64 on a dedicated instance

**Comment by rigelk** [comment]
Sorry, we only support Nginx as a reverse proxy, not Pound.
