### ISSUE TITLE
embed-api player.getResolutions() returns empty array

### ISSUE THREAD

**Issue by bnjmnjns** [Chocobozzz/PeerTube#4148]
**Describe the current behavior**
I am trying to implement a controlled player and I'm using peertube/embed-api. When I call getResolutions() I get an empty array: [].
**Steps to reproduce:**

1. embed video with '?api=1&controls=false' appended to url to hide video controls
2. set up PT video player in an async function:
```
const player = new PeerTubePlayer(videoiFrame.current)
      await player.ready

      ptVideo.current = player // setting video to a variable to accesses elsewhere
      resolutions.current = await player.getResolutions()

      console.log(resolutions.current) // logs []
      setVideoReady(true)
```

**Describe the expected behavior**
Log a list of available resolutions as described in the docs https://docs.joinpeertube.org/api-embed-player?id=getresolutions-promiseltpeertuberesolutiongt

* PeerTube instance:
  * URL: tv.undersco.re
  * version:  3.1.0
  * NodeJS version: 12.13
  * Ffmpeg version: n/a

* Browser name, version and platforms on which you could reproduce the bug: 
Brave browser 1.25.6

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/ffacd78f21d4021b3c0f654ff63ef29ca7afcde3
