### ISSUE TITLE
Upgrade from 3.0.1 Failed due to "column \"torrentFilename\" does not exist"

### ISSUE THREAD

**Issue by vyrti** [Chocobozzz/PeerTube#4154]
Hi,
Upgrade to any version from 3.0.1 is failed due to:

Jun 03 06:41:41 dehamsl3937.int.kn systemd[1]: Started PeerTube daemon.
Jun 03 06:41:41 dehamsl3937.int.kn peertube[111512]: > peertube@3.2.1 start
Jun 03 06:41:41 dehamsl3937.int.kn peertube[111512]: > node dist/server
Jun 03 06:41:45 dehamsl3937.int.kn peertube[111512]: [knmedia.int.kn:443] 2021-06-03 06:41:45.532 info: Database peertube_prod is ready.
Jun 03 06:41:45 dehamsl3937.int.kn peertube[111512]: [knmedia.int.kn:443] 2021-06-03 06:41:45.659 error: Cannot install application. {
Jun 03 06:41:45 dehamsl3937.int.kn peertube[111512]: "err": {
Jun 03 06:41:45 dehamsl3937.int.kn peertube[111512]: "stack": "SequelizeDatabaseError: column \"torrentFilename\" does not exist\n    at Query.formatError (/opt/peertube/versions/peertube-v3.2.1/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)\n    at Query.run (/opt/peertube/versions/peertube-v3.2.1/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)\n    at processTicksAndRejections (node:internal/process/task_queues:94:5)\n    at async /opt/peertube/versions/peertube-v3.2.1/node_modules/sequelize/lib/sequelize.js:619:16\n    at async PostgresQueryInterface.addIndex (/opt/peertube/versions/peertube-v3.2.1/node_modules/sequelize/lib/dialects/abstract/query-interface.js:541:12)\n    at async Function.sync (/opt/peertube/versions/peertube-v3.2.1/node_modules/sequelize/lib/model.js:1367:7)\n    at async Sequelize.sync (/opt/peertube/versions/peertube-v3.2.1/node_modules/sequelize/lib/sequelize.js:793:35)\n    at async Promise.all (index 0)",
Jun 03 06:41:45 dehamsl3937.int.kn peertube[111512]: "message": "column \"torrentFilename\" does not exist",
Jun 03 06:41:45 dehamsl3937.int.kn peertube[111512]: "name": "SequelizeDatabaseError",
Jun 03 06:41:45 dehamsl3937.int.kn peertube[111512]: "parent": {
Jun 03 06:41:45 dehamsl3937.int.kn peertube[111512]: "stack": "error: column \"torrentFilename\" does not exist\n    at Parser.parseErrorMessage (/opt/peertube/versions/peertube-v3.2.1/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/opt/peertube/versions/peertube-v3.2.1/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/opt/peertube/versions/peertube-v3.2.1/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/opt/peertube/versions/peertube-v3.2.1/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:369:20)\n    at Socket.emit (node:domain:470:12)\n    at addChunk (node:internal/streams/readable:313:12)\n    at readableAddChunk (node:internal/streams/readable:288:9)\n    at Socket.Readable.push (node:internal/streams/readable:227:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
Jun 03 06:41:45 dehamsl3937.int.kn peertube[111512]: "message": "column \"torrentFilename\" does not exist",
Jun 03 06:41:45 dehamsl3937.int.kn peertube[111512]: "length": 105,
Jun 03 06:41:45 dehamsl3937.int.kn peertube[111512]: "name": "error",
Jun 03 06:41:45 dehamsl3937.int.kn peertube[111512]: "severity": "ERROR",
Jun 03 06:41:45 dehamsl3937.int.kn peertube[111512]: "code": "42703",
Jun 03 06:41:45 dehamsl3937.int.kn peertube[111512]: "file": "indexcmds.c",
Jun 03 06:41:45 dehamsl3937.int.kn peertube[111512]: "line": "1573",
Jun 03 06:41:45 dehamsl3937.int.kn peertube[111512]: "routine": "ComputeIndexAttrs",
Jun 03 06:41:45 dehamsl3937.int.kn peertube[111512]: "sql": "CREATE UNIQUE INDEX \"video_file_torrent_filename\" ON \"videoFile\" (\"torrentFilename\")"
Jun 03 06:41:45 dehamsl3937.int.kn peertube[111512]: },
Jun 03 06:41:45 dehamsl3937.int.kn peertube[111512]: "sql": "CREATE UNIQUE INDEX \"video_file_torrent_filename\" ON \"videoFile\" (\"torrentFilename\")"
Jun 03 06:41:45 dehamsl3937.int.kn peertube[111512]: }
Jun 03 06:41:45 dehamsl3937.int.kn peertube[111512]: }
Jun 03 06:41:45 dehamsl3937.int.kn systemd[1]: peertube.service: main process exited, code=exited, status=255/n/a
Jun 03 06:41:45 dehamsl3937.int.kn systemd[1]: Unit peertube.service entered failed state.
Jun 03 06:41:45 dehamsl3937.int.kn systemd[1]: peertube.service failed.

Any ideas?

**Comment by Chocobozzz** [comment]
Migration file https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/migrations/0585-video-file-names.ts#L9 should have created this column. Maybe they fail?
