### ISSUE TITLE
Ability to select video resolution for Youtube import

### ISSUE THREAD

**Issue by vachan-maker** [Chocobozzz/PeerTube#4164]
A lot of videos on Youtube are 1080p and when importing a youtube video using the URL, there is no way to select which resolution should be imported. Sometimes, I just want to import the 480p video instead of the 1080p to save space on the server.

**Comment by Chocobozzz** [comment]
Hello,

Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/1030

**Comment by vachan-maker** [comment]
Thanks
