### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by kdmiller45** [Chocobozzz/PeerTube#4165]
I attempted to upgrade from 3.2.0 to 3.2.1 perform the manual upgrade and got the following error
![image](https://user-images.githubusercontent.com/19610991/120900126-ff85ad00-c5e7-11eb-941f-cb4f2504521f.png)

then when I restarted Peertube I got 

![image](https://user-images.githubusercontent.com/19610991/120900180-3e1b6780-c5e8-11eb-9ca6-a6d7196b3cb7.png)

I have tried this three times

Keith

**Comment by tcitworld** [comment]
[PeerTube 3.2.0 dropped NodeJS 10 support](https://github.com/Chocobozzz/PeerTube/releases/tag/v3.2.0). Install version 12 first.

**Comment by kdmiller45** [comment]
Ok up and going, might include that note in the upgrade instructions and include the command to install and location of NGINX config file also, but thanks up and going

**Comment by rigelk** [comment]
It was in the 3.1 release notes.
