### ISSUE TITLE
Videoplayer Shortcuts

### ISSUE THREAD

**Issue by basedobjectivist** [Chocobozzz/PeerTube#4166]
Most other video players like YouTube have keyboard shortcuts associated with various player functions.

Missing:
| Keyboard shortcut | Function |
| --------------- | :--------------- |
| k | Pause/Play in player. |
| m | Mute/unmute the video. |
| t | Theater/Normal mode (somehow not in [Source](https://support.google.com/youtube/answer/7631406?hl=en)) |
| Next Track Media Key on keyboards | Moves to the next track in a playlist. |
| j | Seek backward 10 seconds in player. |
| l | Seek forward 10 seconds in player. |
| , | While the video is paused, go back to the previous frame. |
| > | Speed up the video playback rate. |
| < | Slow down the video playback rate. |
| Home/End on the seek bar | Seek to the beginning/last seconds of the video. |
| / | Go to search box. |
| c | Activate closed captions and subtitles if available. To hide captions and subtitles, activate C again. |
| Shift+N | Move to the next video (If you're using a playlist, will go to the next video of the playlist. If not using a playlist, it will move to the next YouTube suggested video). |
| Shift+P | Move to the previous video. Note that this shortcut only works when you're using a playlist. |
| i | Open the Miniplayer. |

Already implemented:
| Keyboard shortcut | Function |
| --------------- | :--------------- |
| Spacebar | Play/Pause when the seek bar is selected. Activate a button if a button has focus. |
| Play/Pause Media Key on keyboards | Play / Pause. |
| Left/Right arrow on the seek bar | Seek backward/forward 5 seconds. |
| . | While the video is paused, skip to the next frame. |
| Up/Down arrow on the seek bar | Increase/Decrease volume 5%. |
| Numbers 1 to 9 on the seek bar (not on the numeric pad) | Seek to the 10% to 90% of the video. |
| Number 0 on the seek bar (not on the numeric pad) | Seek to the beginning of the video. |
| f | Activate full screen. If full screen mode is enabled, activate F again or press escape to exit full screen mode. |

[Source](https://support.google.com/youtube/answer/7631406?hl=en)

I would love to see these implemented for the PeerTube player.

**Comment by rigelk** [comment]
hi @basedobjectivist,

A lot of them are already implemented. Could you limit your list to those _not_ implemented?

**Comment by basedobjectivist** [comment]
Hello @rigelk,

Thank you for the response.
Yes of course. I have updated the original comment.

**Comment by johackim** [comment]
I agree with that.

Theses two shortcuts are very useful :

- mute (m shortcut)
- fullscreen (f shortcut)

😀

**Comment by Chocobozzz** [comment]
Hello,

These shortcuts are already enabled.

Since most of useful shortcuts are implemented, I'm closing this issue. If you need other ones, or notice bugs using keyboard shortcut please create dedicated issues.

**Comment by arcarofelipee** [comment]
There is anyway to disable the videoplayer shortcuts through Peertube Embed API?

**Comment by Chocobozzz** [comment]
> There is anyway to disable the videoplayer shortcuts through Peertube Embed API?

No, but you can create an issue for this feature request!
