### ISSUE TITLE
Video reply

### ISSUE THREAD

**Issue by hjri** [Chocobozzz/PeerTube#4167]
**Describe the problem to be solved**

Really want ability to reply to a video/post/comment with another video. YouTube used to have "video replies" long time ago (around 2007?) which had multiple different usecases - from actually replying to a video to putting your follow-up video as a reply to participating in YTP tennis.

**Describe the solution you would like:**

Being able to mark video as reply to activitypub object, i.e. peertube video, pleroma/mastodon post etc, an additional field where you can search for activity by its url. Videos with video replies would have replies show up at top of "other videos" column with header "video replies". Author should be able to hide or highlight replies. When video is a reply to something there should be an indication of what it's replying to.

For pleroma/mastodon posts it should also keep mentions of original post

**Describe alternatives you have considered**  

Just uploading videos when replying in pleroma is what I do, but it's not very manageable and doesn't have peertube's features like webtorrent, transcoding etc.

**Comment by rigelk** [comment]
Hi! Please look out for related issues before creating one, as #2212 already covers this. You can then detail further your use case there, and upvote the issue to help us triage it.

**Comment by hjri** [comment]
Hi, i looked around but couldn't find it before, must've missed it, sorry.
