### ISSUE TITLE
Unsupported codec (h265/HEVC) makes the player flickers

### ISSUE THREAD

**Issue by Glandos** [Chocobozzz/PeerTube#417]
* **PeerTube version or URL:** 1.0.0-beta
* **Browser name/version:** Firefox 59
* **NodeJS version:** unknown

* **What is the expected behaviour?**
If a codec is unsupported, like h265, it should be written once in the player.

* **What do you see instead?**
Currently, the message is displayed in the player, and disappear, and re-appear again, in a rapid pace.

Ideally, the server should have transcoded it upon submission. But, in the meantime, the error message should be clean and stable.

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

**Comment by rigelk** [comment]
Apperently there's missing support on the side of videojs (the player library we are using): https://github.com/videojs/videojs-contrib-hls/issues/1130

**Comment by Glandos** [comment]
Yes, but it does not remove the fact that the error message is flickering :)

**Comment by rigelk** [comment]
ah right :sweat_smile: 

@Chocobozzz  could it be the error disabling/enabling until the fallback to HTTP in `client/src/assets/player/peertube-videojs-plugin.ts` that triggers this flickering ?

**Comment by Chocobozzz** [comment]
@rigelk exactly! Should be fixed: https://github.com/Chocobozzz/PeerTube/commit/0dcf9a14be3f8668fe5ee65cf0365d457b4d1499

**Comment by Glandos** [comment]
Thanks for the über quick fix!
