### ISSUE TITLE
Upgrading leaves some videos as unplayable

### ISSUE THREAD

**Issue by SMJ** [Chocobozzz/PeerTube#4172]
Some older videos on a peertube instance fail to play and just display as a black screen with no other information on
their page after an upgrade.

** What did you do **
scripts/upgrade.sh
cd peertube-latest
ln -s /peertube/storage storage
mv config config-dist
ln -s peertube/config config
NODE_ENV=production npm start

**Additional information**
This is an upgrade from upgrade from 3.1.0 to 3.2.1 
example page that shows this symptom:
https://toobnix.org/videos/watch/a4663a8c-c8fe-490f-980f-b6861527310b
Error is:
[toobnix.org:443] 2021-06-07 17:23:44.591 error: Error in controller. {
  "err": "TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received type object\n    at validateString (internal/validators.js:112:11)\n    at Object.join (path.js:1040:7)\n    at VideoFileModel.getFileStaticPath (/peertube/versions/peertube-v3.2.1/dist/server/models/video/video-file.js:191:23)\n    at VideoFileModel.getFileUrl (/peertube/versions/peertube-v3.2.1/dist/server/models/video/video-file.js:185:53)\n    at /peertube/versions/peertube-v3.2.1/dist/server/models/video/video-format-utils.js:158:32\n    at Array.map (<anonymous>)\n    at videoFilesModelToFormattedJSON (/peertube/versions/peertube-v3.2.1/dist/server/models/video/video-format-utils.js:144:10)\n    at Object.videoModelToFormattedDetailsJSON (/peertube/versions/peertube-v3.2.1/dist/server/models/video/video-format-utils.js:107:25)\n    at self.toFormattedDetailsJSON (/peertube/versions/peertube-v3.2.1/dist/server/models/video/video.js:996:37)\n    at /peertube/versions/peertube-v3.2.1/dist/server/controllers/api/videos/index.js:322:31\n    at Generator.next (<anonymous>)\n    at fulfilled (/peertube/versions/peertube-v3.2.1/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:85:5)"

* PeerTube instance: toobnix.org
  * version: 3.2.1
  * NodeJS version: 12.9.1
  * Ffmpeg version: 4.1.6
  * Redis version: 5.0.3
  * PostgreSQL version:  13.3

**Comment by Chocobozzz** [comment]
Go inside your database and run:

```
UPDATE "videoFile" SET filename = t.uuid || '-' || t.resolution || '-fragmented' || t.extname, "torrentFilename" = t.uuid || '-' || t.resolution || '-hls.torrent' FROM (SELECT "videoFile".id, "video".uuid, "videoFile".resolution, "videoFile".extname FROM video INNER JOIN "videoStreamingPlaylist" ON "videoStreamingPlaylist"."videoId" = video.id INNER JOIN "videoFile" ON "videoFile"."videoStreamingPlaylistId" = "videoStreamingPlaylist".id) AS t WHERE t.id = "videoFile"."id" AND "filename" IS NULL
```

```
UPDATE "videoFile" SET filename = t.uuid || '-' || t.resolution || t.extname, "torrentFilename" = t.uuid || '-' || t.resolution || '.torrent' FROM (SELECT "videoFile".id, "video".uuid, "videoFile".resolution, "videoFile".extname FROM video INNER JOIN "videoFile" ON "videoFile"."videoId" = video.id) AS t WHERE t.id = "videoFile"."id" AND "filename" IS NULL
```

**Comment by Chocobozzz** [comment]
It's really weird. What is the output of

```
select "videoFile".* FROM "videoFile" inner join video on video.id = "videoFile"."videoId" and video.uuid = 'dd99ceba-8973-4fe5-b3b7-39d330bd665e'
```

**Comment by SMJ** [comment]
select "videoFile".* FROM "videoFile" inner join video on video.id = "videoFile"."videoId" and video.uuid = 'dd99ceba-8973-4fe5-b3b7-39d330bd665e'

Has no output.  However, I tried for another video that was in the instance prior to the upgrade:

https://toobnix.org/videos/watch/099455a1-10d5-47e6-896d-5e2f46f110c4

While the video page shows and play properly, trying to do the select statement for this UUID also returns nothing.

select "videoFile".* FROM "videoFile" inner join video on video.id = "videoFile"."videoId" and video.uuid = '099455a1-10d5-47e6-896d-5e2f46f110c4'

\d
 public | videoFile                      | table    | peertube
 public | videoFile_id_seq               | sequence | peertube

New videos can also be uploaded and play fine.

**Comment by Chocobozzz** [comment]
I edited my comment. Don't forget the `;` at the end of the query

**Comment by SMJ** [comment]
Sorry about that, followed the updates exactly how given.  Here are the results with the added semicolon:

peertube_prod=> UPDATE "videoFile" SET filename = t.uuid || '-' || t.resolution || '-fragmented' || t.extname, "torrentFilename" = t.uuid || '-' || t.resolution || '-hls.torrent' FROM (SELECT "videoFile".id, "video".uuid, "videoFile".resolution, "videoFile".extname FROM video INNER JOIN "videoStreamingPlaylist" ON "videoStreamingPlaylist"."videoId" = video.id INNER JOIN "videoFile" ON "videoFile"."videoStreamingPlaylistId" = "videoStreamingPlaylist".id) AS t WHERE t.id = "videoFile"."id" AND "filename" IS NULL;
UPDATE 51
peertube_prod=> UPDATE "videoFile" SET filename = t.uuid || '-' || t.resolution || t.extname, "torrentFilename" = t.uuid || '-' || t.resolution || '.torrent' FROM (SELECT "videoFile".id, "video".uuid, "videoFile".resolution, "videoFile".extname FROM video INNER JOIN "videoFile" ON "videoFile"."videoId" = video.id) AS t WHERE t.id = "videoFile"."id" AND "filename" IS NULL;
UPDATE 1455
peertube_prod=>

Now it looks that the older video pages are now loading and playing once again.
Thank you for the assistance with this and I hope this helps other folks in the future!

**Comment by Utopiah** [comment]
It did help, both in the future but also in the past! I was stuck in May https://framacolibri.org/t/upgrade-from-3-0-0-buster-to-production-buster-3-1-0-failed/11907 with the same problem but now thanks to these I'm on 3.4 so thank you both.
