### ISSUE TITLE
Plugin custom fields: invalid (or undocumented?) values for checkboxes

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4177]
**Describe the current behavior**

When adding a plugin custom field on a video, if the type of the settings is «input-checkbox», the values received by the backend are:

```
"pluginData": {
      "my-setting-name": "null"
}
```

or

```
"pluginData": {
      "my-setting-name": "true"
}
```

Values are strings, not booleans.

**Steps to reproduce:**

1. Create a plugin and use registerVideoField to add an input-checkbox field.
2. Update a video, and watch data received on backend (by adding a hook on action:api.video.updated and dumping the parameters, see the plugin contribution documentation).

**Describe the expected behavior**

Values should be booleans (`true` or `false` - or maybe `null`), not strings `"true"` and `"null"`.

**Additional information**

* PeerTube instance:
  * version: 3.2.1
  * NodeJS version: 12

**Comment by JohnXLivingston** [comment]
Hum... Sometimes I get `"false"` instead of `"null"`. Don't understand why.

And it seams that the form doesn't get get the right value on a later update action. (I save the value as in the documentation: https://docs.joinpeertube.org/contribute-plugins?id=add-custom-fields-to-video-form )

**Comment by JohnXLivingston** [comment]
I am a little bit confused, and I have no time to investigate further. It might be the storageManager.getData methods that always returns a string that cause the bug.

Anyway, with this code for saving the value backend it seems to be working:

```typescript
registerHook({
    target: 'action:api.video.updated',
    handler: async (params: any) => {
      logger.debug('Saving a video, checking for custom fields')

      const body: any = params.body
      const video: MVideoThumbnail | undefined = params.video
      if (!video || !video.id) {
        return
      }
      if (!body.pluginData) return
      const value = body.pluginData['livechat-active']
      if (value === true || value === 'true') {
        logger.info(`Saving livechat-active=true for video ${video.id}`)
        await storageManager.storeData(`livechat-active-${video.id}`, true)
      } else if (value === false || value === 'false' || value === 'null') {
        logger.info(`Saving livechat-active=false for video ${video.id}`)
        await storageManager.storeData(`livechat-active-${video.id}`, false)
      } else {
        logger.error('Unknown value ' + JSON.stringify(value) + ' for livechat-active field.')
      }
    }
  })

  registerHook({
    target: 'filter:api.video.get.result',
    handler: async (video: MVideoThumbnail): Promise<MVideoThumbnail> => {
      if (!video) return video
      if (!video.pluginData) video.pluginData = {}
      if (!video.id) return video

      logger.debug('Getting a video, searching for custom fields')

      const result: any = await storageManager.getData(`livechat-active-${video.id}`)
      logger.debug(`Video ${video.id} has livechat-active=` + JSON.stringify(result))
      if (result === true || result === 'true') {
        video.pluginData['livechat-active'] = true
      } else if (result === false || result === 'false' || result === 'null') {
        video.pluginData['livechat-active'] = false
      }
      return video
    }
  })
```

**Comment by JohnXLivingston** [comment]
As it seems that the front-end needs the data to be provided in video.pluginData, I think that Peertube should store and restore values itself.

**Comment by Chocobozzz** [comment]
Hello,

Unfortunately since we use multipart for video edition/upload, we can't send directly boolean values.

**Comment by JohnXLivingston** [comment]
Hum, ok, I think I understand.
What is the recommended way to have a checkbox as custom field, and store/restore it?

**Comment by Chocobozzz** [comment]
> What is the recommended way to have a checkbox as custom field, and store/restore it?

Sanitize boolean fields when you receive the data in the backend. It's what we do for core peertube routes

**Comment by Chocobozzz** [comment]
Documentation improved in https://github.com/Chocobozzz/PeerTube/commit/03a65456f44a6152bb68975e29e076c8c5754cd6
