### ISSUE TITLE
Create live with new release stable jitsi-meet work?

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#4178]
According to the doc, jitsi allows to transmit to peertube (giving a warning, that it is not a valid YouTube URL), but hey, it worked.
Now with the latest version of jitsi it doesn't allow it.

My question would be https://github.com/jitsi/jitsi-meet, I just wanted to know, if this is still working?
, https://docs.joinpeertube.org/use-create-upload-video?id=with-jitsi-meet

![Captura de pantalla de 2021-06-08 14-14-53](https://user-images.githubusercontent.com/43164089/121238655-55678880-c866-11eb-8dce-428c7019ce6c.png)
![Captura de pantalla de 2021-06-08 14-31-29](https://user-images.githubusercontent.com/43164089/121238672-5ac4d300-c866-11eb-927a-ac0b0f0e579e.png)

**Comment by damencho** [comment]
Please whenn you have questions or problems use the community forum before opening new issues, thank you.

What are the jibri logs for the errors?

**Comment by AnonymousWebHacker** [comment]
> What are the jibri logs for the errors?
 where i cant see the jibri logs?

**Comment by AnonymousWebHacker** [comment]
hoooo @damencho I can't install jibri
```
root@jitsi:/etc/jitsi/jicofo# apt search jibri
Sorting... Done
Full Text Search... Done
jibri/stable 8.0-93-g51fe7a2-1 all
  Jibri

jitsi-upload-integrations/stable 0.15.15-1 all
  jitsi-upload-integrations
```
I have only the jitsi-meet package installed, and everything is fine. What is the jibri for?

**Comment by damencho** [comment]
Jibri is the component that does recording or livestreaming. The error you see is because you dont have one. https://github.com/jitsi/jibri
Also checkout the forum there are multiple help guides there

**Comment by AnonymousWebHacker** [comment]
Hoo , @damencho   thanks. 
@Chocobozzz  I think you should specify in the documentation [https://docs.joinpeertube.org/use-create-upload-video?id=with-jitsi-meet] that you need to have jibri installed in the jitsi-meet to allow the transmission to peertube

**Comment by damencho** [comment]
Those documents are not provided from us, you can send your recommendations to those hosting the docs.
