### ISSUE TITLE
live.toobnix.org streams not viewable on VLC

### ISSUE THREAD

**Issue by Asternitix** [Chocobozzz/PeerTube#4180]
**Describe the current behavior**

**Steps to reproduce:**

1. Open VLC
2. Enter stream URL as a network stream
3. Click Play

**Describe the expected behavior**
The stream should be loaded and played.
**Additional information**

* PeerTube instance:
  * URL: live.toobnix.org
  * version: 3.1.0
  * NodeJS version: not known
  * Ffmpeg version: not known

* Browser name, version and platforms on which you could reproduce the bug: VLC version: 3.0.14 Vetinari
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by rigelk** [comment]
hi @Asternitix,

Does VLC output errors? Could you please link us to the issue created on VLC's support for reference?

**Comment by fweng322** [comment]
Same here: reference URL: https://peertube.slat.org/w/6H4WoENfKL6SXxrYLN7Ekg

No any messages output.
