### ISSUE TITLE
Plugin showModal method does not work properly.

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4182]
**Describe the current behavior**
I'm trying to use the showModal method in my plugin with a code that looks like:

```typescript
  registerHook({
    target: 'action:admin-plugin-settings.init',
    handler: ({ npmName }: ActionPluginSettingsParams) => {
      // [...]
      const listRoomsButtons: NodeListOf<HTMLAnchorElement> =
        document.querySelectorAll('.peertube-plugin-livechat-prosody-list-rooms')
      const openListRooms = (): void => {
        console.log('[peertube-plugin-livechat] Opening the room list...')
        peertubeHelpers.showModal({
          title: 'This is a test',
          content: '<p>Model content</p>',
          close: true
        })
      }
      listRoomsButtons.forEach(listRoomsButton => {
        listRoomsButton.onclick = openListRooms
      })
    }
  })
```

When I click on my button, nothing happens... Until I press a keyboard key. When I press a key, no matter which (alt, ctrl, a, b, c, ...), then the modal shows up.

Note: the log «Opening the room list» appears immediately. It is just the modal that don't appear. And if I click twice, I have the following log: «Cannot open another custom modal, one is already opened.»

**Steps to reproduce:**

1. In a plugin, add an `html` settings with this in the descriptionHTML: `<a class="peertube-plugin-livechat-prosody-list-rooms">List rooms</a>`
2. Add the code quoted above in a client script with scope 'admin-plugin'
3. Go to the plugin settings, and click on the button

**Describe the expected behavior**

Modal should open on click.

**Additional information**

* PeerTube instance:
  * version: 3.2.1 (on localhost, with NODE_ENV=test)

* Browser name, version and platforms on which you could reproduce the bug: firefox and chromium

**Comment by Chocobozzz** [comment]
Hi, 
Thanks for the issue. It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/0f6521fa6b4c2267ff4c06e2b639bb52d725e461

**Comment by JohnXLivingston** [comment]
Thanks!
I guess there is no workaround for now? I have to wait next release?

**Comment by Chocobozzz** [comment]
not that I know of, no, but you could try to fire an event somewhere so angular rerun the detector change (so sure it will work)
