### ISSUE TITLE
Error message when uploading video: "Your video file was too large (max. size: 8G)"

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#4183]
I searched but did not find any bug report like this one I'm reporting.
I can't upload video files to my instance, even though the files are smaller than the maximum size set in PHP and Nginx.

**Describe the current behavior**

When I try to upload a video to https://tube.tardis.world from my local hard drive, I get an error message : "Your video file was too large (max. size: 8G)"

**Steps to reproduce:**

1. Log into https://tube.tardis.world and try to upload a video file from local hard disk to the server
2. I get the error message "Your video file was too large (max. size: 8G)"

**Describe the expected behavior**

Since I have maximum upload size net in in the Nginx vhost as 8G, since I have set the same value in PHP 7.4 FPM to 8G as well, I would expect to be able to upload a file that is 1.2G 

**Additional information**

* PeerTube instance:
  * URL: https://tube.tardis.world
  * version: 3.2.1
  * NodeJS version: 12.22.1
  * Ffmpeg version:  4.2.4

* Browser name, version and platforms on which you could reproduce the bug:
Chrome Version 91.0.4472.101 (Official Build) (64-bit) on Ubuntu 20.04 with KDE.

Here is some output from syslog that might give you a clue. These were messages generated immediately when I tried the upload. I will put my nginx config and my php.ini in a pastebin and will post back the address:

Jun 12 05:28:17 mail peertube[81241]:   "err": {
Jun 12 05:28:17 mail peertube[81241]:     "stack": "RequestError: connect ENETUNREACH 2a01:e0a:80b:7e50:2a0:98ff:fe6f:b414:443 - Local (:::0)\n    at ClientRequest.<anonymous> (/var/www/peertube/versions/peertube-v3.2.1/node_modules/got/dist/source/core/index.js:956:111)\n    at Object.onceWrapper (events.js:421:26)\n    at ClientRequest.emit (events.js:326:22)\n    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n    at ClientRequest.origin.emit (/var/www/peertube/versions/peertube-v3.2.1/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)\n    at TLSSocket.socketErrorListener (_http_client.js:427:9)\n    at TLSSocket.emit (events.js:314:20)\n    at TLSSocket.EventEmitter.emit (domain.js:483:12)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)\n    at internalConnect (net.js:923:16)\n    at defaultTriggerAsyncIdScope (internal/async_hooks.js:364:12)\n    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1066:9)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:68:8)",
Jun 12 05:28:17 mail peertube[81241]:     "message": "connect ENETUNREACH 2a01:e0a:80b:7e50:2a0:98ff:fe6f:b414:443 - Local (:::0)",
Jun 12 05:28:17 mail peertube[81241]:     "name": "RequestError"
Jun 12 05:28:17 mail peertube[81241]:   }
Jun 12 05:28:17 mail peertube[81241]: }
Jun 12 05:28:19 mail postfix/smtpd[80708]: disconnect from unknown[87.246.7.228] ehlo=1 auth=0/1 rset=1 quit=1 commands=3/4
Jun 12 05:28:20 mail postfix/smtpd[80716]: disconnect from unknown[212.70.149.88] ehlo=1 auth=0/1 rset=1 quit=1 commands=3/4
Jun 12 05:28:21 mail peertube[81241]: [tube.tardis.world:443] 2021-06-12 05:28:21.436 #033[33mwarn#033[39m: Cannot add share https://mastodon.davidpeach.co.uk/users/david/statuses/105904112539678271/activity. {
Jun 12 05:28:21 mail peertube[81241]:   "err": {
Jun 12 05:28:21 mail peertube[81241]:     "stack": "RequestError: getaddrinfo ENOTFOUND mastodon.davidpeach.co.uk\n    at ClientRequest.<anonymous> (/var/www/peertube/versions/peertube-v3.2.1/node_modules/got/dist/source/core/index.js:956:111)\n    at Object.onceWrapper (events.js:421:26)\n    at ClientRequest.emit (events.js:326:22)\n    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n    at ClientRequest.origin.emit (/var/www/peertube/versions/peertube-v3.2.1/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)\n    at TLSSocket.socketErrorListener (_http_client.js:427:9)\n    at TLSSocket.emit (events.js:314:20)\n    at TLSSocket.EventEmitter.emit (domain.js:483:12)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)",
Jun 12 05:28:21 mail peertube[81241]:     "message": "getaddrinfo ENOTFOUND mastodon.davidpeach.co.uk",
Jun 12 05:28:21 mail peertube[81241]:     "name": "RequestError"
Jun 12 05:28:21 mail peertube[81241]:   }
Jun 12 05:28:21 mail peertube[81241]: }

**Comment by DalekDave** [comment]
My php.ini is here : 

https://t25b.xyz/60bymsr-za

**Comment by DalekDave** [comment]
My Nginx vhost config is here:

https://t25b.xyz/d5ucwzhc9j

**Comment by DalekDave** [comment]
My production.yaml is here:

https://t25b.xyz/zbboh5gh5n

**Comment by DalekDave** [comment]
Registration is open on my instance, so you could create an account on https://tube.tardis.world and try for yourself if you like.

**Comment by Chocobozzz** [comment]
Hello,

You need to add the `upload-resumable` endpoint in your nginx config: https://github.com/Chocobozzz/PeerTube/releases/tag/v3.2.0

https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube#L81
