### ISSUE TITLE
ActivityPub fetcher jobs pile up

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#4184]
**Describe the current behavior**

This isn't a new behaviour but I'm not sure if anyone else has noticed it. I keep logs of how many active and pending jobs my server has, and quite routinely the activitypub fetcher gets backed up because one particular connection is being slow.

Could we parallelize the fetcher? I don't see any reason why it's useful to do them in sequence, when this lets any other activitypub server block our entire fetch queue.

![Screen Shot 2021-06-13 at 11 36 01 AM](https://user-images.githubusercontent.com/923812/121818411-df836880-cc3b-11eb-8226-ff85c8b4048e.png)

**Comment by dhk2** [comment]
I have seen this before as well, it has gotten better with 3.2.1, but will only become more of an issue as the number of instances grow.

Perhaps a "number of activitypub threads" setting in the Basic Administration-Federation section?

**Comment by Chocobozzz** [comment]
Updated in https://github.com/Chocobozzz/PeerTube/commit/60520c7c852b7430e09cdc68ac7ccfe506cbf417
