### ISSUE TITLE
No plugin works to install anymore

### ISSUE THREAD

**Issue by TROMsite** [Chocobozzz/PeerTube#4185]
After the upgrade to 3.2.1, all of the plugins I had installed stopped working and I cannot install any new one. All give me a "Bad Request". I cannot see anything in the logs though.

**Steps to reproduce:**

1. In admin area go to the plugins
2. Try to install any
3. It will fail with an error "Bad Request"

**Additional information**

* PeerTube instance:
  * URL: https://videos.trom.tf
  * version: 3.2.1

* Browser name, version and platforms on which you could reproduce the bug: FIrefox

**Comment by Chocobozzz** [comment]
Hello,

Please paste PeerTube logs at the time your install the plugin.

**Comment by TROMsite** [comment]
That's the weird part because I cannot see any errors in the logs... Not for the past hour, not for the past day. Is this a permission issue? Maybe the server has no permission to read the logs? And also to install the plugins?

**Comment by Chocobozzz** [comment]
Yes it could be

**Comment by TROMsite** [comment]
The plugins and logs folder have 750 permission. With peertube:www-data as the owners and groups. And individual log files have 0640 permissions with the same user/groups. Is this ok?

**Comment by Tysinger** [comment]
I changed servers last night and now I can't install plugins or templates.

Here is the error log:

warn[6/17/2021, 1:13:59 AM] Cannot install plugin peertube-plugin-livechat.

{
  "err": {
    "err": {
      "stack": "Error: Command failed: yarn add peertube-plugin-livechat@2.3.1\nwarning package.json: No license field\nwarning No license field\nerror An unexpected error occurred: \"EACCES: permission denied, unlink '/home/yunohost.app/peertube/storage/plugins/node_modules/.yarn-integrity'\".\n\n    at ChildProcess.exithandler (child_process.js:319:12)\n    at ChildProcess.emit (events.js:375:28)\n    at ChildProcess.emit (domain.js:470:12)\n    at maybeClose (internal/child_process.js:1055:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)",
      "message": "Command failed: yarn add peertube-plugin-livechat@2.3.1\nwarning package.json: No license field\nwarning No license field\nerror An unexpected error occurred: \"EACCES: permission denied, unlink '/home/yunohost.app/peertube/storage/plugins/node_modules/.yarn-integrity'\".\n",
      "killed": false,
      "code": 1,
      "signal": null,
      "cmd": "yarn add peertube-plugin-livechat@2.3.1"
    },
    "stdout": "yarn add v1.22.5\n[1/4] Resolving packages...\n[2/4] Fetching packages...\ninfo If you think this is a bug, please open a bug report with the information provided in \"/home/yunohost.app/peertube/storage/plugins/yarn-error.log\".\ninfo Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.\n",
    "stderr": "warning package.json: No license field\nwarning No license field\nerror An unexpected error occurred: \"EACCES: permission denied, unlink '/home/yunohost.app/peertube/storage/plugins/node_modules/.yarn-integrity'\".\n"
  }
}

**Comment by frankstrater** [comment]
I'm experiencing similar problems with updating and deleting plugins on a RHEL server with SELinux enforced.

```json
warn[6/18/2021, 12:14:04 PM] Cannot update plugin peertube-plugin-creative-commons.
{
  "err": {
    "stack": "Error: Unknown plugin peertube-plugin-creative-commons to unregister\n    at PluginManager.<anonymous> (/var/www/peertube/versions/peertube-v3.2.1/dist/server/lib/plugins/plugin-manager.js:181:23)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v3.2.1/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/versions/peertube-v3.2.1/node_modules/tslib/tslib.js:113:16)\n    at PluginManager.unregister (/var/www/peertube/versions/peertube-v3.2.1/dist/server/lib/plugins/plugin-manager.js:177:24)\n    at PluginManager.<anonymous> (/var/www/peertube/versions/peertube-v3.2.1/dist/server/lib/plugins/plugin-manager.js:247:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v3.2.1/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "message": "Unknown plugin peertube-plugin-creative-commons to unregister"
  }
}
warn[6/18/2021, 12:18:16 PM] Cannot update plugin peertube-plugin-creative-commons.
{
  "err": {
    "stack": "Error: Unknown plugin peertube-plugin-creative-commons to unregister\n    at PluginManager.<anonymous> (/var/www/peertube/versions/peertube-v3.2.1/dist/server/lib/plugins/plugin-manager.js:181:23)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v3.2.1/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/versions/peertube-v3.2.1/node_modules/tslib/tslib.js:113:16)\n    at PluginManager.unregister (/var/www/peertube/versions/peertube-v3.2.1/dist/server/lib/plugins/plugin-manager.js:177:24)\n    at PluginManager.<anonymous> (/var/www/peertube/versions/peertube-v3.2.1/dist/server/lib/plugins/plugin-manager.js:247:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v3.2.1/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "message": "Unknown plugin peertube-plugin-creative-commons to unregister"
  }
}
warn[6/18/2021, 12:18:21 PM] Cannot unregister plugin peertube-plugin-creative-commons.
{
  "err": {
    "stack": "Error: Unknown plugin peertube-plugin-creative-commons to unregister\n    at PluginManager.<anonymous> (/var/www/peertube/versions/peertube-v3.2.1/dist/server/lib/plugins/plugin-manager.js:181:23)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v3.2.1/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/versions/peertube-v3.2.1/node_modules/tslib/tslib.js:113:16)\n    at PluginManager.unregister (/var/www/peertube/versions/peertube-v3.2.1/dist/server/lib/plugins/plugin-manager.js:177:24)\n    at PluginManager.<anonymous> (/var/www/peertube/versions/peertube-v3.2.1/dist/server/lib/plugins/plugin-manager.js:255:28)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v3.2.1/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/versions/peertube-v3.2.1/node_modules/tslib/tslib.js:113:16)\n    at PluginManager.uninstall (/var/www/peertube/versions/peertube-v3.2.1/dist/server/lib/plugins/plugin-manager.js:252:24)\n    at /var/www/peertube/versions/peertube-v3.2.1/dist/server/controllers/api/plugins.js:77:55\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v3.2.1/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/versions/peertube-v3.2.1/node_modules/tslib/tslib.js:113:16)\n    at uninstallPlugin (/var/www/peertube/versions/peertube-v3.2.1/dist/server/controllers/api/plugins.js:75:20)\n    at /var/www/peertube/versions/peertube-v3.2.1/dist/server/middlewares/async.js:14:32\n    at Layer.handle [as handle_request] (/var/www/peertube/versions/peertube-v3.2.1/node_modules/express/lib/router/layer.js:95:5)\n    at next (/var/www/peertube/versions/peertube-v3.2.1/node_modules/express/lib/router/route.js:137:13)\n    at uninstallPluginValidator (/var/www/peertube/versions/peertube-v3.2.1/dist/server/middlewares/validators/plugins.js:108:16)\n    at Layer.handle [as handle_request] (/var/www/peertube/versions/peertube-v3.2.1/node_modules/express/lib/router/layer.js:95:5)\n    at next (/var/www/peertube/versions/peertube-v3.2.1/node_modules/express/lib/router/route.js:137:13)\n    at middleware (/var/www/peertube/versions/peertube-v3.2.1/node_modules/express-validator/src/middlewares/check.js:16:13)",
    "message": "Unknown plugin peertube-plugin-creative-commons to unregister"
  }
}
error[6/18/2021, 12:18:22 PM] Error in controller.
{
  "err": {
    "err": {
      "stack": "Error: Command failed: yarn remove peertube-plugin-creative-commons\nwarning package.json: No license field\nerror No lockfile in this directory. Run `yarn install` to generate one.\n\n    at ChildProcess.exithandler (child_process.js:303:12)\n    at ChildProcess.emit (events.js:315:20)\n    at ChildProcess.EventEmitter.emit (domain.js:482:12)\n    at maybeClose (internal/child_process.js:1021:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)",
      "message": "Command failed: yarn remove peertube-plugin-creative-commons\nwarning package.json: No license field\nerror No lockfile in this directory. Run `yarn install` to generate one.\n",
      "killed": false,
      "code": 1,
      "signal": null,
      "cmd": "yarn remove peertube-plugin-creative-commons"
    },
    "stdout": "yarn remove v1.22.5\ninfo Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.\n",
    "stderr": "warning package.json: No license field\nerror No lockfile in this directory. Run `yarn install` to generate one.\n"
  }
}
```

**Comment by Roki100** [comment]
> I changed servers last night and now I can't install plugins or templates.
> 
> Here is the error log:
> 
> warn[6/17/2021, 1:13:59 AM] Cannot install plugin peertube-plugin-livechat.
> 
> {
> "err": {
> "err": {
> "stack": "Error: Command failed: yarn add peertube-plugin-livechat@2.3.1\nwarning package.json: No license field\nwarning No license field\nerror An unexpected error occurred: "EACCES: permission denied, unlink '/home/yunohost.app/peertube/storage/plugins/node_modules/.yarn-integrity'".\n\n at ChildProcess.exithandler (child_process.js:319:12)\n at ChildProcess.emit (events.js:375:28)\n at ChildProcess.emit (domain.js:470:12)\n at maybeClose (internal/child_process.js:1055:16)\n at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)",
> "message": "Command failed: yarn add peertube-plugin-livechat@2.3.1\nwarning package.json: No license field\nwarning No license field\nerror An unexpected error occurred: "EACCES: permission denied, unlink '/home/yunohost.app/peertube/storage/plugins/node_modules/.yarn-integrity'".\n",
> "killed": false,
> "code": 1,
> "signal": null,
> "cmd": "yarn add peertube-plugin-livechat@2.3.1"
> },
> "stdout": "yarn add v1.22.5\n[1/4] Resolving packages...\n[2/4] Fetching packages...\ninfo If you think this is a bug, please open a bug report with the information provided in "/home/yunohost.app/peertube/storage/plugins/yarn-error.log".\ninfo Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.\n",
> "stderr": "warning package.json: No license field\nwarning No license field\nerror An unexpected error occurred: "EACCES: permission denied, unlink '/home/yunohost.app/peertube/storage/plugins/node_modules/.yarn-integrity'".\n"
> }
> }

Hey! i have fixed this issue by doing:
`cd /var/www/peertube/storage
zip -r pls plugins/
rm -rf plugins
sudo -u peertube unzip pls`
i dont use yunohost though, but worth a try since it worked in my case

**Comment by TROMsite** [comment]
Ok so eventually it was a Yunohost issue - you can read more here https://forum.yunohost.org/t/peertube-no-plugin-theme-works-to-install-anymore/16242 - they pushed a fix. Closing this issue. Thanks all for the suggestions ;)
