### ISSUE TITLE
Migration server gives 403 forbidden message for videos

### ISSUE THREAD

**Issue by Benau** [Chocobozzz/PeerTube#4186]
Hi, I tried to migrate my peertube instance to a new server location, after following the instruction error log gives bunch of permission error (but peertube diectory is already peertube.peertube)
```
2021/06/14 08:02:40 [crit] 7268#7268: *439 stat() "/var/www/peertube/storage/dev/null" failed (13: Permission denied), client: x.x.x.x, server: x.x.x, request: "GET /lazy-static/torrents/380baa8b-a116-4a7d-a101-e8dfc3fd2db6-360.torrent HTTP/1.1", host: "x.x.x", referrer: "https://x.x.x/videos/watch/380baa8b-a116-4a7d-a101-e8dfc3fd2db6"
2021/06/14 08:02:41 [error] 7268#7268: *439 open() "/var/www/peertube/storage/videos/380baa8b-a116-4a7d-a101-e8dfc3fd2db6-360.mp4" failed (13: Permission denied), client: x.x.x.x, server: x.x.x, request: "GET /static/webseed/380baa8b-a116-4a7d-a101-e8dfc3fd2db6-360.mp4 HTTP/1.1", host: "x.x.x", referrer: "https://x.x.x/videos/watch/380baa8b-a116-4a7d-a101-e8dfc3fd2db6"
```
Similar to  issue:
https://framacolibri.org/t/update-2-1-1-and-nginx-error/7049/3

I managed to workaround as it said, but it stills fail for webseed video path, and
```
ls -l /var/www/peertube/storage/videos/380baa8b-a116-4a7d-a101-e8dfc3fd2db6-360.mp4
-rw-r--r-- 1 peertube peertube 3582751 Jun  3 20:11 /var/www/peertube/storage/videos/380baa8b-a116-4a7d-a101-e8dfc3fd2db6-360.mp4
```
so the file exists

* PeerTube instance:
  * version: 3.2.1
  * NodeJS version: 12.21.0
  * Ffmpeg version: 4.3.2
  * Redis version: 6.0.11
  * PostgreSQL version: 13.3

(and for some reason I also need to ```# rewrite ^/static/(.*)$ /$1 break;``` to make thumbnails display correctly, I guess this is not the intended behaviour, something wrong during migration? Do I need to migrate the same peertube version of original host?)

**Comment by Benau** [comment]
Ok it seems that ```sudo useradd -m -d /var/www/peertube -s /bin/bash -p peertube peertube``` from production guide
make ```/var/www/peertube``` non accesible to nginx, so:

```
root@peertube:/var/www# ls -l
total 8
drwxr-xr-x 2 www-data www-data 4096 Jun 13 18:49 html
drwxr-x--- 8 peertube peertube 4096 Jun 14 17:39 peertube
root@peertube:/var/www# chmod 755 peertube/
root@peertube:/var/www# ls -l
total 8
drwxr-xr-x 2 www-data www-data 4096 Jun 13 18:49 html
drwxr-xr-x 8 peertube peertube 4096 Jun 14 17:39 peertube
```
fixed the issue

Maybe the production guide can be updated.......

**Comment by Benau** [comment]
And by the way seems that peertube create a hls folder inside streaming-playlists with rw-rw-rw  (missing x) which will lead to permission error too

**Comment by Chocobozzz** [comment]
Hello, 

`useradd` should use `/etc/skel` which is `drwxr-xr-x` by default. If this is not the case, you need to adapt directory rights after the creation.

> seems that peertube create a hls folder inside streaming-playlists with rw-rw-rw

Or it seems that the peertube umask is not the default one (`022` or `002`)
