### ISSUE TITLE
cannot find getCurrentPosition in @peertube/embed-api

### ISSUE THREAD

**Issue by akakaze** [Chocobozzz/PeerTube#4188]
I am using @peertube/embed-api ver.0.0.4 on the front end, and I cannot find getCurrentPosition.
This is said to be added in v2.4.0.
Did I miss something?

**Comment by Chocobozzz** [comment]
HI @akakaze, sorry for the late anwser. What do you mean by "I cannot find getCurrentPosition"?

Do you have an error? Could you paste the code you're trying to use?

**Comment by Chocobozzz** [comment]
Closing, but don't hesitate to comment if you still have the issue.
