### ISSUE TITLE
Uploader failing in Safari with "block all cookies" preference

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#4189]
**Describe the current behavior**

There seems to be a compatibility problem with Safari and MobileSafari and the new uploader. After upgrading to Peertube 3.2.1, I got a user reporting failed uploads from their iOS device. I tried reproducing the problem on desktop Safari and it seems to be similar if not the same there.

**Steps to reproduce:**

1. Use Safari
2. Log in
3. Upload a video

**Describe the expected behavior**

Video starts upoading

**Additional information**

Upload stays at 0%, error in Javascript console.
I ran it again with the debugger enabled, to get a better backtrace:

![Screen Shot 2021-06-15 at 6 45 29 AM](https://user-images.githubusercontent.com/923812/122064147-c26aa900-cda5-11eb-8d71-d69974ae3493.png)

I'll look into this some more but this seemed like enough to submit a bug report in case someone else already recognizes this issue. I'm not yet sure what safari means by "insecure" in this context, as all the resources involved are https from the same domain.

* PeerTube instance:
  * URL: diode.zone
  * version: 3.2.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Safari 14.1.1
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by scanlime** [comment]
Actually the browser had a preference I'd forgotten about, it was set to "Block all cookies", which results in this unhelpful failure in the uploader code. I'm updating this bug to reflect that issue rather than the iOS problem, as I'm not sure if that's the same bug and I don't have additional information from that user.

**Comment by kukhariev** [comment]
Hi, @scanlime.
Does updating ngx-uploadx to version 4.1.2 fix this issue?

**Comment by Chocobozzz** [comment]
Thanks @kukhariev, I confirm than 4.1.2 seems to fix this issue (see https://github.com/Chocobozzz/PeerTube/commit/2b58ca796df4969622c32e4f34f4e02112e577d7)
