### ISSUE TITLE
Reduce size of docker container

### ISSUE THREAD

**Issue by MikaXII** [Chocobozzz/PeerTube#419]
Hello, 

_This is WIP don't vomit for the dockerfiles code, it need to be reworked_

I work to reduce the size of the docker images. According to me the size are too big : 
`mikaxii/peertube-old     latest              719987c594ed        50 seconds ago      2.09GB`

So I make a new way to build the project.
One container is dedicated to build the project : 
```docker
FROM node:8-alpine

# Install dependencies
RUN apk add --no-cache ffmpeg openssl bash make g++ git \
 && apk add --no-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/ vips-dev fftw-dev

RUN mkdir artifact
RUN git clone https://github.com/Chocobozzz/PeerTube /app
WORKDIR /app

VOLUME ["artifact"]

CMD  yarn install --pure-lockfile && npm run build && mv dist /artifact && mv node_modules /artifact
```

And the Dockerfile for prod : 
```docker
FROM node:8-alpine

# Install dependencies
RUN apk add --no-cache ffmpeg openssl bash \
 && apk add --no-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/ vips-dev fftw-dev

# Add peertube user
RUN addgroup -g 991 peertube \
    && adduser -D -u 991 -G peertube peertube

RUN mkdir -p /app/config /data
RUN chown peertube:peertube -R /app /data
WORKDIR /app
ADD ./artifact/dist /app/dist
ADD ./package.json .
ADD ./artifact/node_modules ./node_modules
ADD ./config/default.yaml /app/config
USER peertube
# Configure PeerTube
ADD ./config/default.yaml /app/config
ADD ./config/production.yaml /app/config
ENV NODE_ENV production
ENV NODE_CONFIG_DIR /app/config
# Run the application
CMD ["npm", "start"]
VOLUME ["/data"]
EXPOSE 9000
```
result : 
`mikaxii/peertube         test-b4             c0a5645e0846        12 minutes ago      546MB`

Of course I do that on "Quick&Dirty" mode.
And we can use that to build an official image with CI and automatic push to an official repo of peertube.

EDIT : My bad again, I didn't there are already a pipeline.

**Comment by Chocobozzz** [comment]
If you want to reduce the size again, delete `node_modules` directory and run `yarn install --pure-lockfile --production` to only download prod dependencies.

**Comment by MikaXII** [comment]
Indeed :)
Dockerhub : 

| Tag Name            | Compressed Size | Last Updated   |
|---------------------|-----------------|----------------|
| test-b4             | 166 MB          | 30 minutes ago |
| alpine-1.0.0-beta.1 | 435 MB          | 3 days ago     |

I'll work on this but I see you have already your pipeline so I'll make a PR only if you are interrested about this :) (And when the code will be more beautiful XD).

**Comment by Nautigsam** [comment]
I wanted to manage the dev of peertube with docker-compose with a minimal image so I created this [Dockerfile](https://github.com/Nautigsam/PeerTube/blob/feature/add_dev_docker-compose/Dockerfile.dev) and this [docker-compose.yml](https://github.com/Nautigsam/PeerTube/blob/feature/add_dev_docker-compose/docker-compose.yml). It makes it very easy to install and run.

@MikaXII  I needed python 2 in order to run node-gyp, I don't understand how you could not installing it?

**Comment by Chocobozzz** [comment]
Closing now we have an image ~ 474 MB on docker hub
