### ISSUE TITLE
About and Statistics pages not loading

### ISSUE THREAD

**Issue by Mastercuber** [Chocobozzz/PeerTube#4190]
**Describe the current behavior**
When I want to open the about or statistics page I get redirected to the page I selected as "Start page" in the config.

**Steps to reproduce:**

1. visit the instance
2. click on about or statistics

**Describe the expected behavior**
Both mentioned pages should be visible and no redirect to the selected home page should be triggered.

**Additional information**
I tried it with firefox and chrome. 

When I open the dev tools of a browser and take a look at the request at this time, I see, there's nothing wrong with the server side, because the request is being received with content and a 200 OK or 304 Not Modified. 

For me it seems like a problem with the translations. The main language of the instance is german and the second language english. No other languages.

Maybe a `categoryObj.?label` is enough to get an `undefined` instead of an error.. 

* PeerTube instance:
  * URL: https://tube.avensio.de/
  * version: 3.2.1
  * NodeJS version: doesn't mind (client side problem)
  * Ffmpeg version: doesn't mind (client side problem)

* Firefox 89, Ubuntu 20.04.2 LTS
![](https://www.avensio.de/img/peertube-issue-3.png)

**Comment by Chocobozzz** [comment]
Hello,

You set instance categories that do not match existing categories in your instance config

**Comment by Mastercuber** [comment]
Indeed I did.
I removed the empty and non existing categories in the config and through the admin dashboard. Now i see both pages. 
Thank you
