### ISSUE TITLE
Sort playlists by latest published

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4192]
**Describe the problem to be solved**
We're using playlist as a way to categorize content for our viewers. Currently the user has to scroll down to the bottom of the playlist to be able to see if there's any new content.

**Describe the solution you would like:**
We'd like to be able to sort our playlists by latest published videos.

**Describe alternatives you have considered**  
A) Youtube has solved this by adding a setting for each playlist that makes it possible to add new videos on top of the playlist. That's a more generic solution than sort by publish date.

B) `filter:api.video-playlist.list.result` hook to make it possible to solve this with a plugin. This will make it harder to have this setting per playlist, but it could be a good start.

**Comment by kontrollanten** [comment]
I created this hook in alternative B and realized that it may be confusing to have a `position` property that will not be respected (in case a plugin is added to change to a custom order). So therefore I'm considering a third, and probably the best, alternative

C) Add a hook upon adding a video to a playlist, to make it possible to change the position property so that it will be on top instead of bottom of the playlist.

**Comment by AnonymousWebHacker** [comment]
I think I like the **A** (something native without plugins). It would be an option on the same list for this.

**C**  Also valid too , for when you want to add a video to a list, and specify if at the beginning or end
