### ISSUE TITLE
Downloading subtitles: only one language available, and it is not the correct one

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4194]
**Describe the current behavior**

When I try to download the subtitles for a video (that has several subtitle files), there is only the link for one language.
Moreover, this is not based on the subtitle language selection for the video, but on the peertube's interface language. And it is buggy for some values.

**Steps to reproduce:**

1. go to https://videos.globenet.org/videos/watch/abbb0057-cb8a-444c-b230-3487384e2de7
2. Choose 'French' as Peertube language in the left menu, and choose «french» as subtitles for the video
3. click on «download»
4. choose «subtitles» in the modal title area
5. **bug**: the link if for deutsch subtitles (althought french is available for this video)
6. Change Peertube's language for english
7. try again to download subtitles: this time it is in english. Even if I selected «french» for the video's subtitles.

**Describe the expected behavior**

I think all files should be listed in the modal.
In any case, it should not rely on the interface's language to select which file download.

**Additional information**

* PeerTube instance:
  * URL: https://videos.globenet.org
  * version: 3.2.1
  * NodeJS version: 12

**Comment by Chocobozzz** [comment]
Hi,

Thanks. I think it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/262f8ff63109c8a95d9d149c1951cffd4c8301ef
