### ISSUE TITLE
change  order list [Checkbox]

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#4198]
I have a website where I put a video on the right hand side of peertube, a video [embed].

When I share a video playlist [Embed]
Instead of leaving the last video added to the list of first, the first video that was added to said list appears.

I think it would be ideal, that in this URL, 
https://domain.com/my-library/video-playlists/54a3c679-07f1-4023-bd8d-9eb8291e6fdb 
there was a (check box) or some other option, which allows
[change the order of the list]. I mean, last thing added to the list, come out first

**Comment by kontrollanten** [comment]
Hi! I think this relates to #4192 and will be solved by #4196

**Comment by AnonymousWebHacker** [comment]
Yeaa fixed on https://github.com/Chocobozzz/PeerTube/pull/4196 by @kontrollanten tnkss :)
