### ISSUE TITLE
Problems with dark layout

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#4199]
**Describe the current behavior**
Some zones are white text on white background.
![Screenshot_20210620_144508](https://user-images.githubusercontent.com/22192600/122675057-51712a00-d1c7-11eb-9eb7-ba803cecb913.png)

**Steps to reproduce:**

1. Activate dark layout

**Describe the expected behavior**
All zones as white text on dark background.
**Additional information**

* PeerTube instance:
  * URL: peertube.stemy.me
  * version: 3.2.1
  * NodeJS version: 10.24.0~dfsg-1~deb10u1
  * Ffmpeg version: 7:4.1.6-1~deb10u1

* Browser name, version and platforms on which you could reproduce the bug: Firefox 78.11, debian stable

**Comment by AnonymousWebHacker** [comment]
Plugins and themes, this repository is not responsible for creating them, each plugin has its own repo.

In the case of yours which I think is the dark theme, the repo is: https://framagit.org/framasoft/peertube/official-plugins/tree/master/peertube-theme-dark

**Comment by Chocobozzz** [comment]
Please upgrade your dark theme.

**Comment by stemy2** [comment]
I tried it, but i just have a "bad request" error.

**Comment by AnonymousWebHacker** [comment]
> Actualice su tema oscuro.

```
warn[25/6/2021 11:43:53 a. m.] Cannot update plugin peertube-theme-dark.

{
  "err": {
    "stack": "Error: Unknown plugin peertube-theme-dark to unregister\n    at PluginManager.<anonymous> (/var/www/peertube/versions/peertube-v3.2.1/dist/server/lib/plugins/plugin-manager.js:181:23)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v3.2.1/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/versions/peertube-v3.2.1/node_modules/tslib/tslib.js:113:16)\n    at PluginManager.unregister (/var/www/peertube/versions/peertube-v3.2.1/dist/server/lib/plugins/plugin-manager.js:177:24)\n    at PluginManager.<anonymous> (/var/www/peertube/versions/peertube-v3.2.1/dist/server/lib/plugins/plugin-manager.js:247:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v3.2.1/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "message": "Unknown plugin peertube-theme-dark to unregister"
  }
}
```
