### ISSUE TITLE
Jobs Federate Mastodon fails

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#4203]
* PeerTube instance:
  * URL: PeerTube and Mastodon are a SNET
  * version: 3.2.1
  * NodeJS version: v12.22.1

The [ activitypub-http-broadcast ] is [waiting ,delayed and failed] on Peertube ===> Mastodon

```
Job: 102616 Type: activitypub-http-broadcast Processed on Jun 23, 2021, 1:02:11 PM Finished on Jun 23, 2021, 1:02:12 PM
--
{   "uris": [     "https://mastodon.azeroth.website/inbox"   ],   "signatureActorId": 1,   "body": {     "id": "https://peertube.azeroth.website/accounts/peertube/views/videos/1275/2021-06-23T16:36:02.154Z",     "type": "View",     "actor": "https://peertube.azeroth.website/accounts/peertube",     "object": "https://peertube.azeroth.website/videos/watch/c459b69c-2571-4da2-8ce2-50e91386e875",     "to": [       "https://www.w3.org/ns/activitystreams#Public",       "https://peertube.azeroth.website/video-channels/chirimoyasauneuro/followers",       "https://peertube.azeroth.website/accounts/peertube/followers",       "https://peertube.azeroth.website/accounts/kentukyft/followers"     ],     "cc": []   },   "contextType": "View" }
jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.     at ContextResolver._fetchContext (/var/www/peertube/versions/peertube-v3.2.1/node_modules/jsonld/lib/ContextResolver.js:173:13)     at runMicrotasks (<anonymous>)     at processTicksAndRejections (internal/process/task_queues.js:97:5)


```
The videos uploaded to Peertube are not being published on Mastodon.
The weird thing is that in some of the videos uploaded to Mastodon, you make a comment, if they are published on Peertube

I'm not 100% sure, but I think this happens after having had to restart the API of the Mastodon instance, because of this problem that I had
https://github.com/tootsuite/mastodon/issues/16416#event-4920130659

**Comment by Chocobozzz** [comment]
Hello,

https://peertube.azeroth.website does not seem to work

**Comment by AnonymousWebHacker** [comment]
![Captura de pantalla de 2021-06-24 20-08-32](https://user-images.githubusercontent.com/43164089/123349947-fa9d8480-d527-11eb-99c3-96a5f0b2119e.png)
The Peertube instance is working fine. I have not made any changes to your nginx vhost or anything, for that error.

What else can it be?

PD: It is inside a SNET, you cannot access it
![Captura de pantalla de 2021-06-24 20-11-04](https://user-images.githubusercontent.com/43164089/123350144-5f58df00-d528-11eb-9193-4cb809bf6e6b.png)
![Captura de pantalla de 2021-06-24 20-11-20](https://user-images.githubusercontent.com/43164089/123350154-6384fc80-d528-11eb-83d3-ae83d155f5f5.png)

**Comment by AnonymousWebHacker** [comment]
By the way, since I reported the bug, the 3rd peertube video, if posted on Mastodon

![Captura de pantalla de 2021-06-24 20-14-15](https://user-images.githubusercontent.com/43164089/123350380-e7d77f80-d528-11eb-9bf0-63c89cc6d3aa.png)
![Captura de pantalla de 2021-06-24 20-14-10](https://user-images.githubusercontent.com/43164089/123350412-f3c34180-d528-11eb-979e-305ad664cf86.png)

**Comment by AnonymousWebHacker** [comment]
Fixed for the moment.

@Chocobozzz  I think you should look at this.
The supported nginx config was giving me that error.
[peertube.azeroth.website.github.txt](https://github.com/Chocobozzz/PeerTube/files/6712748/peertube.azeroth.website.github.txt)

Now I changed for the old one that I had as a salve and everything works perfect for me.
[peertube.azeroth.website.txt](https://github.com/Chocobozzz/PeerTube/files/6712743/peertube.azeroth.website.txt)

**Comment by AnonymousWebHacker** [comment]
@Chocobozzz I continue with the problem, I restart the nginx, and the first video that is uploaded, ok it is well federated to Mastodon, from there on out, the others, it does not happen and gives said error

**Comment by AnonymousWebHacker** [comment]
The problem was not related to the nginx Vhosts. When changing the vhost, and restarting the Vhost, the first video worked fine, from now on it gave an error, it seems that it was because it tried to index the video in the federation, requested by said 2 users

The problem is that there were two users who were following the instance completely peertube@domain.com

Solution:

One of the users stopped following the instance and the problem is fixed
Previously it was working fine like this, I don't know why that error.
