### ISSUE TITLE
Livestreams buffer infinitely, .ts requests are 404

### ISSUE THREAD

**Issue by Roki100** [Chocobozzz/PeerTube#4204]
**Describe the current behavior**
So basically when i launch livestream and then watch it, it buffers after some seconds infinitely, and all the requests get 404
![image](https://user-images.githubusercontent.com/35699619/123162241-ac797a00-d470-11eb-891b-54720e743b76.png)
![47889-opera_2021-06-23_22-20-55](https://user-images.githubusercontent.com/35699619/123162809-58bb6080-d471-11eb-90b9-1edc938e91ed.png)
![image](https://user-images.githubusercontent.com/35699619/123162936-7983b600-d471-11eb-948c-09d09f88594d.png)
It doesnt work in both: transcoding enabled & disabled
**Steps to reproduce:**

1. Launch livestream
2. Start Watching it
3. Wait 10-30 seconds to get infinity buffering

**Describe the expected behavior**
The livestream loads fine and is watchable in both: transcoding enabled & disabled without issues, such as 404 error codes

**Additional information**
I have no idea why this happens but it is kinda annoying, because it is impossible to watch the livestream

* PeerTube instance:
  * URL: https://quantube.win
  * version: 3.2.1
  * NodeJS version: 12.16.1
  * Ffmpeg version: 4.3.1

* Browser name, version and platforms on which you could reproduce the bug: Opera GX, Chrome
* Link to browser console log if relevant: 
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Could you run an endless live stream so I can try to reproduce?

**Comment by Roki100** [comment]
> Hello,
> 
> Could you run an endless live stream so I can try to reproduce?

What do you mean by "endless live stream", like permanent livestream?

**Comment by Chocobozzz** [comment]
> What do you mean by "endless live stream", like permanent livestream?

Yes, so I can try to play it

**Comment by Roki100** [comment]
> > What do you mean by "endless live stream", like permanent livestream?
> 
> Yes, so I can try to play it

as i dont know how to get ffmpeg to stream at x1 speed to rtmp (not x9/900fps) let me just give you stream data so you can try via your obs or something
https://quantube.win/videos/watch/1f0907d1-eec4-4117-a2ba-1ecb552a28fe
`rtmp://roki.ovh:1935/live`
`9b767d10-e633-4b4a-a183-6338c59b379b`
after around 40 seconds of watching it should start doing stuff such as 404 spam or random buffering with errors in console

**Comment by Chocobozzz** [comment]
Thanks, do you use a cache in front of peertube? Or a CDN? Or S3 storage?

Because at some point, the playlist file seems to be stuck and not updated.

**Comment by Roki100** [comment]
> Thanks, do you use a cache in front of peertube? Or a CDN? Or S3 storage?
> 
> Because at some point, the playlist file seems to be stuck and not updated.

yeah it is on front of cloudflare, however i have the cache mode set to bypass for the whole site so it shouldnt cache anything (and it seems it doesnt by looking at the "cached" chart)
i've also tried with development mode which 200% bypasses all the cache and got a weird behavior with the playlist file disappearing and appearing
![image](https://user-images.githubusercontent.com/35699619/126402207-b671b75a-5cef-4ae9-8b10-6cf82992395b.png)
i have no clue what could be the reason of this, generally the playlist file seems to update from my curl testing, but it seems to disappear and appear now,
![image](https://user-images.githubusercontent.com/35699619/126402318-199aaa32-fdb8-4034-baee-2a6d87137f2a.png)

from what i see the playlist file updates might be delayed, but im not sure how frequently it should update

i wouldnt blame my vps disk because the write rate seems to be at around 410 MB/s

i also wouldnt blame cloudflare at this point though

**Comment by Chocobozzz** [comment]
Please try to disable cloudflare to check if it is related to the CDN

**Comment by Roki100** [comment]
yep, i have disabled cloudflare proxy and it still happens

**Comment by Chocobozzz** [comment]
It seems you enabled it again? Could you disable it so I can check request headers/peertube behaviour?
