### ISSUE TITLE
Support unambiguous date formats

### ISSUE THREAD

**Issue by Jookia** [Chocobozzz/PeerTube#4205]
**Describe the problem to be solved**

When dealing with published dates on videos, I see something like 'Published 12/1/2020'.
I live in Australia, so that means 12th of January.
I dug through the metadata JSON in the page, and it actually meant 1st of January.

**Describe the solution you would like:**

The ability to select date formats according to my region, or just use ISO 8601 dates.

**Comment by Chocobozzz** [comment]
Hello,

Could you open your web browser console and display the result of `navigator.language`?

And also `new Date().toLocaleString()`

**Comment by Jookia** [comment]
navigator.language
"en-US"
new Date().toLocaleString()
"6/26/2021, 4:19:28 AM"

I set all my machines to en_US locales just to avoid any programs that
don't play nice with en_AU.

I don't think there's a way to get either en_US or en_AU to do ISO 8601.

**Comment by Chocobozzz** [comment]
Then I'm sorry, but if you configure your web browser so use `en-US` instead of `en-AU`, it's expected to have a wrongly formatted date. I suggest you to configure to use `en-AU` first and fallback to `en-US` in your web browser settings.

**Comment by Jookia** [comment]
Firefox doesn't have  an en_AU locale. So you're telling me to use an option that doesn't exist, and closing the issue. Thanks.

**Comment by tcitworld** [comment]
It does.
![image](https://user-images.githubusercontent.com/2197836/123594218-bc39eb00-d7ef-11eb-9033-27eb891edcfd.png)

**Comment by Jookia** [comment]
Not on my machine. How do you get that? Does it have an ISO 8601 date?

**Comment by tcitworld** [comment]
Are you by any change confusing the language in which Firefox's interface is displayed for the locale used to display pages? That's the second option on this screenshot.
![image](https://user-images.githubusercontent.com/2197836/123594593-310d2500-d7f0-11eb-915b-9efa1f5fe061.png)

**Comment by M-i-k-o-t-o** [comment]
Changing your locale has privacy implications. This is why things like the tor browser come with en-US by default.

**Comment by Jookia** [comment]
Yep, my mistake. The date still isn't ISO 8601 and there's no indication of which date format PeerTube is using, so I'm just supposed to guess which date it is still even if I use en_AU. There's no way to know it's localized.

But whatever, this issue is closed- it's clear there's no interest in making things understandable here.

**Comment by lokedhs** [comment]
Would it make sense to change the output format to use a longer form that writes the date in text form instead of using numbers? That way there would be no risk of confusion even if the locale isn't set correctly?
