### ISSUE TITLE
Accepting ownership of a livetream does not work

### ISSUE THREAD

**Issue by resoli** [Chocobozzz/PeerTube#4206]
**Describe the current behavior**

When transferring the ownership of a livestream, the target user receives an error when he tries to accept it.

**Steps to reproduce:**

1. Create a livestream; transfer ownership to another user.
2. The target user clicks on the ownership change button and on "Accept". He receives a "Server Error, try later" message.  

**Describe the expected behavior**

The target user should be able to accept the ownership, or it should be not possible to initiate the ownership transfer if this is forbidden by design.

**Additional information**

* PeerTube instance: PeerTube LinuxTrent
  * URL: https://video.linuxtrent.it
  * version: 3.1.0
  * NodeJS version: v12.21.0
  * Ffmpeg version: ffmpeg version 4.1.6-1~deb10u1

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/21b5c2982ff93bc67d5dd4c04db352a3f96608b0

(you can only change ownership of a live that is not already started)
