### ISSUE TITLE
Daily video quota progress bar - inverted used and total quota numbers

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#4209]
**Describe the current behavior**

**Steps to reproduce:**

1. Set a general or user daily quota 
2. Go to Publish a video or My Account

**Describe the expected behavior**

- Used daily quota number should be on the left of the progress bar.
- Total daily quota number should be on the right of the progress bar.

**Additional information**

* PeerTube v3.2.1

![Capture d’écran du 2021-06-28 01-21-49](https://user-images.githubusercontent.com/1877318/123562625-2af75400-d7b0-11eb-9a0a-7ce0ad3ac826.png)

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/50cb778ee6c55e318331ff80a91e891751ab5c73
