### ISSUE TITLE
Shortcut: Shift + S only unsubscribes

### ISSUE THREAD

**Issue by Oymate** [Chocobozzz/PeerTube#4213]
**Describe the current behavior**
The shortcut only unsubscribes from channel.

**Steps to reproduce:**

1.Go to this [test video](https://libre.video/videos/watch/9c9de5e8-0a1e-484a-b099-e80766180a6d), 
2.press `Shift + S` you only unsubscribe (while logged in)
3.but cannot subscribe

**Describe the expected behavior**
I should be able to do both 

**Additional information**

* PeerTube instance:
  * URL:https://libre.video/videos/watch/9c9de5e8-0a1e-484a-b099-e80766180a6d
  * version:3.0.0
  * NodeJS version:?
  * Ffmpeg version:?

* Browser name, version and platforms on which you could reproduce the bug:Firefox
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/77d873c56d112b7b1de4e703b08f7d8547dfb9fd
