### ISSUE TITLE
Share a channel between several accounts

### ISSUE THREAD

**Issue by Globulle** [Chocobozzz/PeerTube#4215]
My organisation hosts a Peertube instance. Some are personal videos made by members on their own, some others are official videos of the organisation in a dedicated channel.
In the second case we currently need to create an official account to host this official channel. Thus we share login and password among admin people, which is not satisfactory.

It would be very convenient to have instead several users able to post in the same channel. Namely, a channel owner could grant admin rights to defined users.

Thanks for the work!

**Comment by rigelk** [comment]
Hi! Please look out for related issues before creating one, as https://github.com/Chocobozzz/PeerTube/issues/699 already covers this. You can then detail further your use case there, and upvote the issue to help us triage it.

**Comment by Globulle** [comment]
Sorry, I was (surprinsigly) not able to find this topic. Thanks for the link.
