### ISSUE TITLE
Rest API not started when register is called at instance startup

### ISSUE THREAD

**Issue by lutangar** [Chocobozzz/PeerTube#4216]
**Describe the current behavior**

When the `register` function of a plugin is called at instance startup the Rest API is not yet started.
This result in all calls to the Rest API to fails in this specific scenario.

**Describe the expected behavior**

The context in which the `register` function is called should stay consistent.

**Describe the solution you would like:**

The  plugins `register` functions could only be called once the Rest API is started.

**Describe alternatives you have considered**

If the context can't be consistent depending on the scenario in which the `register` is called,
the context could then be provided the the register function.
One possible solution could be to provide a `type RegisterReason = 'start' | 'install' | 'edit'` to the `register` function.

> The inspiration comes from the browser extension API, see : 
> https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/OnInstalledReason#type

I'm describing this as an alternative but both solutions could be implemented and be seen as complementary.

**Documentation**

In any case, the different context in which the `register` and the `unregister` function are called should be described in a documentation.

**Comment by Chocobozzz** [comment]
I think we can move plugin registrations https://github.com/Chocobozzz/PeerTube/blob/develop/server.ts#L308

after the listen https://github.com/Chocobozzz/PeerTube/blob/develop/server.ts#L315

**Comment by Chocobozzz** [comment]
Done in https://github.com/Chocobozzz/PeerTube/commit/e19fdf5775aa43fcc766308cbc4dcd66a5d0776e
