### ISSUE TITLE
More peers needed: Option to federate more videos

### ISSUE THREAD

**Issue by gloschtla** [Chocobozzz/PeerTube#4222]
I found a video on an instance (bittube.video) which follows another instance (meta-tube.de). The video originates from the other instance, which now is down (Error 503). This video cannot be streamed now, because there is no alternative peer. 

So, to make federation strong, the secondary instances which follow primary instances should have the option to MIRROR ALL VIDEOS from the original instance, instead of just some most viewed videos. 

There can be freshly uploaded videos which are very requested. But these videos will never get a high view count, if the originating instance is overloaded and thus other instances get not chance to become a second peer. So in such a case, most wanted videos will never be mirrored (because users will find an alternative uploading platform for the same video). And this goes against the principle of federation.

**Comment by Chocobozzz** [comment]
Hello,

An instance can mirror all videos of another instance using the `recently-added` strategy and providing enough disk space to mirror all videos.

**Comment by SimplyCorbett** [comment]
> Hello,
> 
> An instance can mirror all videos of another instance using the `recently-added` strategy and providing enough disk space to mirror all videos.

This is no longer correct in 6.0.3. I’ve assigned 2TB of storage to a redundancy mirror and have recently-added with a 5 minimum view count and it’s only mirroring around 30GB automatically from diode.zone and the blender instance.

the remaining 100GB of usage is from manually mirrored videos.

this is with federation v2 and the crash fix you added a week ago.
