### ISSUE TITLE
Any plugin to disable views on users no registred?

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#4223]
Is there a plugin that allows me to disable viewing the videos if the user is not registered?

And at once, create rules, that if the video is requested by some instance of #Mastodon or some specific site, what if it allows to see them, without registration?

**Comment by Chocobozzz** [comment]
Hello,

No there's no such plugin AFAIK. But it can be created using `filter:html.embed.video.allowed.result`, `filter:html.embed.video-playlist.allowed.result` for example

**Comment by AnonymousWebHacker** [comment]
@Chocobozzz Please, if you know of any pugin so it is done in the PeerTube repos, mention me in this post
