### ISSUE TITLE
Cannot remote subscribe anymore, getting blank page

### ISSUE THREAD

**Issue by binarydad** [Chocobozzz/PeerTube#4224]
When attempting to remote subscribe (going onto another instance, hitting Subscribe, then Remote Subscribe, putting in MY Peertube account email), it takes me to my website, as expected, but the page is blank. I get the following error in the logs:

```
[video.binarydad.com:443] 2021-07-01 20:18:16.611 info: 192.168.1.140 - - [01/Jul/2021:20:18:16 +0000] "GET /api/v1/search/videos?search=https://video.binarydad.com/api/v1/search/videos&search=https://tube.privacytools.io/video-channels/techlore_channel HTTP/1.0" 500 - "https://video.binarydad.com/remote-interaction?uri=https:%2F%2Ftube.privacytools.io%2Fvideo-channels%2Ftechlore_channel" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0",

[video.binarydad.com:443] 2021-07-01 20:18:16.614 error: Error in controller. {,
  "err": "TypeError: search.startsWith is not a function\n    at searchVideoChannels (/app/dist/server/controllers/api/search.js:30:32)\n    at /app/dist/server/middlewares/async.js:14:32\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/app/node_modules/express/lib/router/route.js:137:13)\n    at videoChannelsListSearchValidator (/app/dist/server/middlewares/validators/search.js:33:16)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/app/node_modules/express/lib/router/route.js:137:13)\n    at middleware (/app/node_modules/express-validator/src/middlewares/check.js:16:13)"
```

This is on a docker instance running the latest image. 

Screenshot of blank page:

![image](https://user-images.githubusercontent.com/1760607/124185319-d2aea380-da88-11eb-91e0-504eca8aa7e5.png)

* PeerTube instance:
  * URL: https://video.binarydad.com
  * version: 3.2.1 (Docker)
  * NodeJS version: latest?
  * Ffmpeg version: latest?

**Comment by jswetzen** [comment]
I have the same problem, cannot remote subscribe at all. When I enter an incorrect or non existing account, it gives me an error, but with a correct account, it just silently fails.
Account instance: tube.tardis.world
Subscribing instance: peertube.tv

**Comment by binarydad** [comment]
Do you get the same JS error?

I noticed that this seems to work ONLY when I'm on my LAN (where the docker instance is also hosted). I know it does a redirect right before that page, which I have yet to diagnose. I suspect the docker instance is not getting the correct client IP, or there's something incorrect with the reverse proxy that's handling WAN traffic (where the issue is happening).

**Comment by jswetzen** [comment]
Aha, I'm actually not having the same problem! It does work for me on desktop but nothing happens when I try to subscribe on my phone. Sorry I misposted. Mobile subscribing should work though!

**Comment by Chocobozzz** [comment]
@jswetzen please create a dedicated issue

@binarydad please enable debug logs on your server and paste network request using the web browser developer tools
