### ISSUE TITLE
What is the required python version?

### ISSUE THREAD

**Issue by Stopi** [Chocobozzz/PeerTube#4225]
According to the [dependencies](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/dependencies.md) doc, python seems to be obviously required.
However, for Gentoo it is asked to get python 2.7 when this isn't the case for other distro.

My question: is this still a requirement or can we use python 3?
I couldn't find any mention in the [changelog](https://github.com/Chocobozzz/PeerTube/blob/develop/CHANGELOG.md#v230) either.

Python 2 is deprecated since 1st January 2020.
Recently Gentoo removed all dependencies to python 2 from its stable tree, the currently used version is 3.9.
Peertube 3.2.1 is my last package requiring python 2, so I'd like to know.

Hopefully this is just a matter of updating the doc...

**Comment by frankstrater** [comment]
In my experience Python3 (on Red Hat distros) works fine. I believe the Python 2.7 requirement stems from the youtube-dl binary that is included as a node module (needed for the Video Import feature of PeerTube). The latest version of youtube-dl states:

"youtube-dl is a command-line program to download videos from YouTube.com and a few more sites. It requires the Python interpreter, version 2.6, 2.7, or 3.2+, and it is not platform specific."

The npm package of youtube-dl is only slightly outdated, so I think it's fine for Python 3.2 or above

I have no experience with Gentoo, but keep in mind that youtube-dl expects /usr/bin/python to exist. So you might need to add a symlink like:

```
sudo ln -s /usr/bin/python3 /usr/bin/python
```

Certbot needs Python as well, but certbot is not part of the core of PeerTube (and probably works fine with Python 3 as well) and is out of scope.

So, not sure if I'm missing something, but also hope I don't have to maintain multiple Python versions on the server as well.

**Comment by Stopi** [comment]
Hi frankstrater, thanks for your answer.

I believe it's just a matter of changing the doc then.
requirement `dev-lang/python:2.7` for Gentoo might just be changed in `dev-lang/python` in [https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/dependencies.md](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/dependencies.md) on line 324.
Btw I see this line was written 3 years ago, so deprecation make sense.

I could do a PR if you want to but I'm hesitating to clone a full repo just for correcting a typo (aka removing 4 characters in this case). So if you can do it that would be awesome, since you already are a contributor.

For your info, Gentoo is a very python centric distribution, main distro tools are made with python including the package manager.
When I check the last Gentoo's stable tree I can tell last youtube-dl works with python 3.8, 3.9 & 3.10 and certbot works with python 3.8 & 3.9 for now.

In Gentoo `/usr/bin/python` is always pointing to the chosen python version, which is usually the last one but can manually be selected by the admin. Yes, several python version can co-exist in Gentoo.

Anyway, I'm going to remove python 2.7 from my server and if that create an issue I will then report it here.

**Comment by frankstrater** [comment]
> Anyway, I'm going to remove python 2.7 from my server and if that creates an issue I will then report it here.

If it doesn't create an issue, let me know as well. I'll prepare the PR and also report it here and then we can close this issue.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/pull/4238
