### ISSUE TITLE
Support 'authenticated fetch' for compatibility with 'limited federation' Mastodon instances. 

### ISSUE THREAD

**Issue by rscmbbng** [Chocobozzz/PeerTube#4226]
Dear devs,

**Describe the problem to be solved**

Mastodon supports a 'limited federation' mode which allows one to set up instances which federate only with those on allow lists. To enforce that model it requires federating servers to do an authenticated fetch. See [the Mastodon documentation](https://docs.joinmastodon.org/admin/config/) for more context. 

Currently it possible to add a peertube instance to the allow list of such Mastodon server running in 'secure mode'. Accounts on peertube can be followed and announcements of new videos reach the Mastodon instance. However, any comments made on those videos do not reach the Peertube instance.

While in that model it makes sense that these comments, which normally appear publicly, would not show up. They could and should show up to logged in peertube users on that instance.    

**Describe the solution you would like:**

Peertube supporting authenticated fetch to display interactions from Mastodon instances running in 'secure mode' which have allowlisted said Peertube instance. These interactions would only be visible to users on the peertube instance which are currently logged in.

**Comment by johanfleury** [comment]
I guess it’s related, logs on my instance are full of messages like this one:

```
[peertube.br0.fr:443] 2021-07-06 15:07:23.599 warn: Cannot fetch remote actor count https://[SNIPPED]/users/[SNIPPED]/followers. {
  "err": {
    "stack": "HTTPError: Response code 403 (Forbidden)\n    at Request.<anonymous> (/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejecti
ons (internal/process/task_queues.js:97:5)",
    "message": "Response code 403 (Forbidden)",
    "name": "HTTPError",
    "responseBody": {
      "error": "Forbidden"
    },
    "statusCode": 403
  }
}
```

**Comment by tribela** [comment]
Got same error. Is there any plan to support signed fetch?
