### ISSUE TITLE
Display transcoding progress to users

### ISSUE THREAD

**Issue by violoncelloCH** [Chocobozzz/PeerTube#4228]
**Describe the problem to be solved**
As an user uploading a video I always wonder when to expect the transcoding jobs of a video to finish (so it gets published completely and I then can share the link). As an admin, I can easily open the job overview of my instance and look for the transcoding jobs of a particular video.

**Describe the solution you would like:**
As an user I'd like an approximate total estimate of the transcoding progress to be shown right below the video (or maybe as an overlay on top of the video as e.g. vimeo does it?)

**Describe alternatives you have considered**  
If estimating the total progress is too complicated, the different jobs (their resolution) could be displayed with that particular progress.

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/799
