### ISSUE TITLE
Dealing with failed jobs

### ISSUE THREAD

**Issue by zanhesl** [Chocobozzz/PeerTube#4230]
Hello everyone, I've noticed that from time to time a few video transcoding jobs are failing. Is there now any automatic service that would restart these jobs? If so, how could I change time intervals for "checking for failed video transcodings"? Or videos would just be un-transcoded forever?

I've manage to partially solve this issue by manually applying transcoding commands for each individual video, but it is of course a temporary solution.

Thanks for your attention.

**Comment by Chocobozzz** [comment]
Hello,

Failed transcoding jobs should be very rare. What error do you have?
But yes, the only way to rerun failed transcoding jobs is to run the transcoding CLI script.

**Comment by drzraf** [comment]
In my case I had multiple failure (during a `native -> docker` migration):
- `No transcoding jobs created for video xxx (no resolutions)` (incorrect configuration maybe).
- `Error: getaddrinfo ENOTFOUND redis`
- `Error: Cannot guess path of /var/www/peertube/storage/tmp/0147a2d23e6a506a0f8c74733baxxx-import. Directory content....`
- `Error: connect ECONNREFUSED 127.0.0.1:637`
- ...

... and a clear need to (re)transcoding the hundreds of videos.

But the provided script takes only one videoId in argument.
Having a routine which:
1. Fetches the video in missing one or more transcoding
2. Adds the corresponding transcoding job(s)
... would be help overcoming such situation.
