### ISSUE TITLE
Move Local to S3

### ISSUE THREAD

**Issue by grubeli** [Chocobozzz/PeerTube#4234]
I have a PeerTube instance and using local storage, I just got Wasabi account and want to move usingn S3 from wasabi.
I don't mind to lost local videos.
How can I add S3 Wasabi to PeerTube?
https://docs.joinpeertube.org/admin-remote-storage is bit confusing, maybe someone can help

**Comment by Chocobozzz** [comment]
Hello,

Please try the community forum instead (https://framacolibri.org/c/peertube) and explain your trouble with the documentation.
