### ISSUE TITLE
Unable to add a tag on Android

### ISSUE THREAD

**Issue by alexandre-k** [Chocobozzz/PeerTube#4235]
**Describe the current behavior**
When pressing the Enter key on the keyboard of a smartphone while adding tags, it won't create it and skip adding tags to move to the description form.

**Steps to reproduce:**

1. Publish a new video.
2. Write a tag in the tags form.
3. Press Enter on the AOSP keyboard (I tried with other keyboards though and the result was the same), the tag won't be  added.

**Describe the expected behavior**
On a smartphone, adding a tag should be possible with the Enter key, on the bottom right side of the virtual keyboard.

* PeerTube instance:
  * URL: videorelay.co
  * version: 3.2.1
  * NodeJS version: v12.22.1
  * Ffmpeg version: 4.1.6-1~deb10u1

* Browser name, version and platforms on which you could reproduce the bug: Duckduckgo browser, v. 5.87.0, Android 11

**Comment by Chocobozzz** [comment]
Hello,

I created an issue in the appropriate repository: https://github.com/ng-select/ng-select/issues/1932

**Comment by alexandre-k** [comment]
Ok, thanks. So it’s a bug upstream.

**Comment by Chocobozzz** [comment]
This issue should be fixed by https://github.com/Chocobozzz/PeerTube/commit/5801d519a7a6fca7eb3831001e73f9825ce60a95

Android users can use `,` instead of virtual keyboard `Enter` to add a tag in the field
