### ISSUE TITLE
Support RTMPS

### ISSUE THREAD

**Issue by r6fans** [Chocobozzz/PeerTube#4236]
Describe the current behavior
I want to use the RTMPS protocol for live stream.
Will peertube support streaming with the RTMPS protocol directly  in the future like YouTube?
Or in which way RTMPS can be implemented？

Additional information

PeerTube instance:
* URL: 
* version: 3.2.1
* NodeJS version: 12.22.1
* Ffmpeg version: 4.1.6-1~deb10u1
* Postgres: 13.2

Sorry for my limited English.

**Comment by Chocobozzz** [comment]
Hello,

RTMPS is not supported yet

**Comment by r6fans** [comment]
Thanks for your comments.

Are there plans to support this in the future?

**Comment by Chocobozzz** [comment]
Yes but we don't have an ETA yet

**Comment by ROBERT-MCDOWELL** [comment]
@Chocobozzz
RTMFP would be great to as it's also peer to peer and UDP.
there is a patched version of ffmpeg with libertmfp developed by a French company here
https://github.com/MonaSolutions/librtmfp
https://github.com/thomasjammet/FFmpeg/

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/df1db951c512a58110171d046ef367789df02733
