### ISSUE TITLE
Upload video from local network 1GB/sec

### ISSUE THREAD

**Issue by kirill2400** [Chocobozzz/PeerTube#4237]
How to upload video on my server which in my local network across 1gb/sec lan, no across the internet?

**Comment by kirill2400** [comment]
I can reach it with add to hos in windowst:
serverip domain
May it work automatically?
So that I can determine that the site does not work from the Internet, and at the same time, if it is, use a gigabit channel

**Comment by kirill2400** [comment]
And I have a few question, @Chocobozzz why, when I uploaded video and delete it, transcoding still progress and as result save video in storage? And can I reboot server while transcoding process and it automatically resume after reboot?

**Comment by kirill2400** [comment]
Why uploaded video transcoding first 1080-240 instead 240-1080?

**Comment by jameskimmel** [comment]
Have you already asked in IRC/Matrix?

See rule:
Please ask first on the IRC/Matrix chat room. If nobody answers after 24h (except weekends), please fill an issue here.

**Comment by Chocobozzz** [comment]
> May it work automatically?

yes it should

> Why uploaded video transcoding first 1080-240 instead 240-1080?

See https://github.com/Chocobozzz/PeerTube/issues/4013

**Comment by kirill2400** [comment]
What about dirty file, what store on hdd and newer remove? `why, when I uploaded video and delete it, transcoding still progress and as result save video in storage? And can I reboot server while transcoding process and it automatically resume after reboot?`
