### ISSUE TITLE
Server error when loading videos

### ISSUE THREAD

**Issue by okhin** [Chocobozzz/PeerTube#424]
* **PeerTube version or URL:** peertube-latest (https://tbs.okhin.fr)
* **Browser name/version:** Firefox ESR
* **NodeJS version:** v9.9.0

* **What is the expected behaviour?**
When going on the trending page, I should see thumbnails or video
* **What do you see instead?**
An OAuth error pops, asnd no video is available (all the other page items such as the navbar are ok). It 

The text of the error message as displayed on the page is as follow:

> Error
> Cannot retrieve OAuth Client credentials: undefined. Ensure you have correctly configured PeerTube > (config/ directory), in particular the "webserver" section.

When restarting the instance (both peertube andnginx) everything works fine for a while,

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):** https://gist.github.com/okhin/25ddf92eb054e20959afb1f2c9ac1cff

**Comment by Chocobozzz** [comment]
Please send me you logs by email + what is you OS?
