### ISSUE TITLE
Add a policy where thumbnails are blurred but not titles

### ISSUE THREAD

**Issue by fenarinarsa** [Chocobozzz/PeerTube#4242]
Peertube 3.2.1

Currently there is only a few policies available for sensitive videos: display, hide and blur thumbnails.

First I must say "blur thumbnails" is incorrect. This policy also blurs the video title, making it actually useless to browse an instance when most videos are okay but some are sensitive (you just overlook them). It seems there's also currently a bug for unlogged users that show sensitive videos blurred, regardless of the policy chosen.

In my case, I have videos that are 99% okay but contains some sensitive parts. What I'd like is to mark them as sensitive, so the warning message pops up when the user tries to play them. But without actually blurring the thumbnail - which I carefully selects - nor the title.

Currently I cannot do that so the closest option is to make the videos marked sensitive to be displayed, but then there's no warning when an unlogged user tries to play it.

So what would be nice is to add more policies, like:

- Hide
- Blur thumbnails and titles
- Blur thumbnails
- Show

And a checkbox to enable the warning message when a user tries to play the video.

**Comment by Chocobozzz** [comment]
Hi, thanks for the issue.

Merging this discussion in https://github.com/Chocobozzz/PeerTube/issues/1158 and/or https://github.com/Chocobozzz/PeerTube/issues/1588
