### ISSUE TITLE
Rewinding of pages has disappeared after the update

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#4246]
**Describe the current behavior**

After updating the instance to version 3.3.0-rc.1, arrows for rewinding pages disappeared. Such a problem on the users page.
I marked these areas in the screenshot

![Screenshot_1](https://user-images.githubusercontent.com/11453567/125171824-fecfd000-e1be-11eb-8a6d-2afd94c0d56c.png)

* PeerTube instance:
  * URL: https://peervideo.ru
  * version: 3.3.0-rc.1
  * NodeJS version: v12.22.1
  * Ffmpeg version: 4.1.6-1~deb10u1

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/e89cbbdf9408fd3ea16da540c425ecf2803ac668
