### ISSUE TITLE
Unable to create a new users from web admin page

### ISSUE THREAD

**Issue by vyrti** [Chocobozzz/PeerTube#4250]
**Describe the current behavior**

**Steps to reproduce:**

1. Open up https://sitename/admin/users/create
2. Try to select role for a user
3. tada, empty list
4. <img width="480" alt="2021-07-13 11_00_37-Create a user - KNMedia" src="https://user-images.githubusercontent.com/1192062/125414695-ad6fc5b9-f5bd-4288-8caa-89aa0cc6a508.png">

**Describe the expected behavior**

Able to select role for a user

**Additional information**
Fresh clean installation on redhat7

* PeerTube instance:
  * version: 3.3rc1
  * NodeJS version: 11
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
  Chrome 91.0.4472.101

**Comment by Alterak** [comment]
I have the same problem-(

**Comment by Chocobozzz** [comment]
Thanks for the issue and the RC test. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/2d7273168b42a58f12005aad1da5a8215bc111a7
