### ISSUE TITLE
Plausible deniability in PeerTube

### ISSUE THREAD

**Issue by M-Stenzel** [Chocobozzz/PeerTube#4256]
Hi peertubers, friends, 

privacy is something to be discussed widely. I could not find any detailed information in the web/forum regarding plausible deniability. May I explain:

When an instance is deployed by some person, usually root access for server/machine is necessary. This very same person (root) has by default access even to the private videos of an instance.

If the maintainer of an instance wants to make sure that nobody except the person which uploaded  videos has access to his or her videos, then the root user must not have the rights to have read  access to the directories in the "storage:" section of the production.yaml file.

What is the view on this? Is there an easy way to make sure that the root user is banned from peeking at  the private files?

Thanks in advance, Martin.

P. S. Console access for the "peertube" user would need to be disabled, too.

**Comment by SimplyCorbett** [comment]
Youtube/gdrive also has access to your private files. You're not going to get anywhere with this - because even if you remove the ability to see them in the GUI you can still view them on the filesystem level.

**Comment by SimplyCorbett** [comment]
> then the root user must not have the rights to have read access to the directories in the "storage:" section of the production.yaml file.

Then disable the root user along with sudo.

The problem here is you can still access the video files on a recovery ISO.

**Comment by Chocobozzz** [comment]
Hello,

We can't prevent `root` (linux user and peertube user) to read user files. The instance maintainer is responsible of the content uploaded on the instance, and so it should be able to check videos files uploaded in it. Then I don't think peertube is suited for this use case.

**Comment by M-Stenzel** [comment]
Thank you for the information!

---
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBF/VIZ8BEADrUBes4ZkfCVpNpChElDxCwIorpTjiZIrzTXvXKX4zH1pQrF/c
i6XJ9R6B2y/XPm22VrdngLErqBvM60LIVwrAplPrenc+UQJ7829IpaNcb/DqnYlB
2Q418bP3J9CN36NlQFNGeycc5pEt9E01MWjxN5YHAyYNEokNj7/OclD83d4aTvLP
OyZSChH2IKvywM8E/bclNVHYeyxkJtbuwyBu+IRQojm02PzuomPUARuTCAutCF3k
N45kA6tMYXuW03Mn4yyDKp/p8NQ59KyPj1WJVlxvpIzk+hh0Wrrq0sbXbav7jg3a
oV1tjjK320NxvLzs7QZI0lcjojamMdHc9tm43/31PxL+CQQcTLlm2xeBjsYfEACE
p1d+OWiDB0jN7TX6sBoWlz9lpSUSwnldVW3n2JHhY84gSQhujF5gccCpupUet8hq
MBmFp42h+dXx8dzpeXqBoHeCn5Q6NtxGEG0mu5RYNaHvgrx00G66cutIVZUfryZm
l3oq/WKVXGc4x/Zvv8RIiPWFmY0DEczE2fN5Way0Yo1x9WT3UZMkdnZhIcEqUVKU
hIuvSkwr30/ZS7TIE1wwheWDfjpLZ7zEhjiK5PAV+AFjKl/Sjptsjc+YsHG1MDHa
JM2GLoLIxbZMuj7ENWUQBw7e2zukyQKVcH+6FXSH6BJUt7Vd7SO9tWX1MQARAQAB
tCtNYXJ0aW4gU3RlbnplbCA8bS5zdGVuemVsQG1haWwueHktc3BhY2UuZGU+iQI1
BBABCAAfBQJf1SGfBgsJBwgDAgQVCAoCAxYCAQIZAQIbAwIeAQAKCRBJ6ZRm52MB
SATxD/9AOdsZR+GecHbk9NJQz0xeW2HU4nshPqXVAHdmq3SfMLP/BhHgKNth5t1B
iX9U1l4ivGO0IZNWTlCHQj6/WnmDD+QyagyLVED4BE2aBKqKE7e+p99CzYb1yHzL
NYoMs0GupBbUr5tYAKpc5ed2TjOLTnhM9zrzT98UhUlr0kkIyOOjKFFeM+ulAgJp
C+2049qq02l1XU/RUI/ip/surJtOLO4GOLjUmmT3L/4gEPOx6BQ7Tql1/3RNGMfa
q0B1fYdA+mqCghbp9DAvQoOljUV5+nnF31ZyiXoFY1APsYyzxkwOg4SIleujM9bm
vTaQSyT8hyGVnhye1E9wOtTdeCvps3kg0iVV0SX+AJ+uuYsGs2UZsVkrFsA9qA6F
uUMT+JUWT11RqagotqH7pucUmt5F3aFTzkuEeJW6fXvuSx0eBQWG4XIIpc0J5nuZ
wbSFVGsjKWS8BV3agxiqtillJq3qbCSAIutbiRroupk6DTAV+/tfvDo6O6vmzpD/
F13xCWqx0pQO6/K9eku5lYCWwRoNAnmm92YMI50N4CISfGHw1DUNMHjxQj3axRtv
mWCwEKjrRU7OWfDNzzJQgglwhWQChli4kNHHC0aVCUCF3HWjcW0qSg0hdMBsB7Qt
zVXxEFg0k5zYl+z+L0nzx2hMreYYuX5JRqLztcpwF79rFJZgKrkCDQRf1SGfARAA
ypFKB4gczOB1nrJ/cnzkCG/bv4G8/1NCE3uxYLhxVpWwVW+mutuqGpaxIL4cJjpu
HCBrhECSWbqYDTiKAeLFpU3WAewjUnJQ1bE1TcFJXxuRXhcHY4o5ZDrJ4c3UmvEt
G3lPuVWk0L5LNhkjGuJ46TAxTntWiB+OLRuPCEeiXoAaqsi6+VC1uMc3VouparrV
o1H2fUZCJ4XcxBNZmpgs7z573r0L7HfMN62Ox5QSjVSMCv5ZNWum7hJGl+6IeFD0
KgxwbCAHiJMBsv0TMkwtj3CUk//S/mQgMwhxKrmMqyf/uC6mbbVAgr4KcA4LPkYT
B0+ZmplZjb07Raz3fheEI8GirQeyH5VQpcTuJ1PLUPxIFS71L/VrZW14ScTy/Eng
b/4fDfEpv+zly8RuVja6jbjbxTZSXGrNE7GF3cu5n0d1W2f0IZSceiQ88wglMeRh
aesY3LBWhwwLGMwhXR9avv1zw7vyRDkbGR+4LZ0e0gf3DWFCrGmMy7xk9ZR/lNKK
B6zzPPjiYbPL9ooyVrhKeGZGniS4i6v8N/Ps/E9G/cBkPBD6wA7BqgJIy6Xol4yW
xgg7LMueg2hlbKWmSIL0q9x/CU2jH5Y8h9w3T9zBAFY5q1gXiST1MKuvY21lGZuK
2GfAkp6fl46k6TboWdxvi/Sb7C+VtXBCQD0HQB5dyPkAEQEAAYkCHwQYAQgACQUC
X9UhnwIbDAAKCRBJ6ZRm52MBSKRfEACij4CVjrWhb71aZ3q/m7MQ/2q98cbLVKKD
A6wcIuW18e6S1jTewG6uAu+fpXS97OPKgZcQj+jf77qx1VL+UrhL56otOhDQBsuv
UQn9JmWtTSTqN3q1niTUJomL94QeWcvK/TS00hIAd8ibrlJHy0iVQpHiswwXjtay
f7szsWeA73sg95X8pPYsTkzImbuU2V3l+mHgD9PRj26AuTyyBpuxopjRV8Fv+T0M
yNwIdX+bxQbgAfz6DjDJuQjdCE25heLxsIsdECu4icSB+C0r64E+YposlCgojg2o
tDEPcqI5AIUmudKuLsz0aE8MGs+Ao9AwvoSZvxaRH9HRuNvjTvVh/8mvlvPGrcpP
jp2nteZGmK6K4jfWKpWzel2CrE0HgUuUuIvDnLn3KjfYbTCUePY//hoOzh8tUIpu
dsYakaHovL1JcYNQp8B6O1FdhDWPZcXIFXE0e+Ze9qaoL42b5ffJbQmCp0uxM1OP
WD+daDacEfzsp8q6BmzjLBeA80gHK3W2Zt+ZfTN8/HmAV8ukhPlSv2wAnJLt7TDP
L4/UG+QKbEpdrstJxcO+pY32Q/GoCyr///kW8koUe8ON9W0xx79AaOKv9z7f9n9V
UwdhUYhprUDCUASgDzDJO69R4TO1CQc9AK6FtgT0NE4jHU7xvEsPUpIaqGy+zQQN
2GvBVs8FBw==
=y232
-----END PGP PUBLIC KEY BLOCK-----

On 2021-07-20 09:45, Chocobozzz wrote:

> Hello,
> 
> We can't prevent root (linux user and peertube user) to read user 
> files. The instance maintainer is responsible of the content uploaded 
> on the instance, and so it should be able to check videos files 
> uploaded in it. Then I don't think peertube is suited for this use 
> case.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] 
https://github.com/Chocobozzz/PeerTube/issues/4256#issuecomment-883173752
[2]
