### ISSUE TITLE
Content filtering for self-hosted instance

### ISSUE THREAD

**Issue by sitemapxml** [Chocobozzz/PeerTube#4259]
If I want to deploy my own instance of PeerTube, I will need to have some way to automatically remove inappropriate content (adult content, violence etc...)

How this can be done?

I didn't find the answer to this question in documentation so I'm asking here.

**Comment by SimplyCorbett** [comment]
You could code a plugin that takes random images from the uploaded video and then sends them to moderatecontent.com or similar.

There isn't currently an automated way to moderate content. You would need to rely on moderators to remove inappropriate content.

**Comment by AnonymousWebHacker** [comment]
In my instance there are moderators, who watch over each submitted video.

the other variant that you can do is, enable the option of [send videos to supervision], a moderator accepts it, and then the video is published

**Comment by SimplyCorbett** [comment]
> 
> 
> In my instance there are moderators, who watch over each submitted video.
> 
> the other variant that you can do is, enable the option of [send videos to supervision], a moderator accepts it, and then the video is published

This leaves you open to liability if something you approve ends up being a problem.

Anyway, you're looking for this:

![saveme](https://user-images.githubusercontent.com/7935624/126254075-67628ee3-3167-43c4-8ecc-b4f86bd20806.jpg)

**Comment by AnonymousWebHacker** [comment]
I was referring to that option, the videos have to wait to be approved by a moderator

**Comment by SimplyCorbett** [comment]
> 
> 
> I was referring to that option, the videos have to wait to be approved by a moderator

Yeah. If you want it automated you'd need to use a solution like moderatecontent.com with a custom plugin or train your own AI model with nvidia's tensor cores or similar.

**Comment by SimplyCorbett** [comment]
You could also use amazon rekognition.

https://docs.aws.amazon.com/rekognition/latest/dg/moderation.html

**Comment by Chocobozzz** [comment]
I also suggest the [auto mute](https://framagit.org/framasoft/peertube/official-plugins/-/tree/master/peertube-plugin-auto-mute) plugin.

**Comment by sitemapxml** [comment]
Thank you @SimplyCorbett, I will definitely check this. `Amazon rekognition` seems as a good option. 
I found example very close to what you said [amazon-rekognition-video-analyzer](https://github.com/aws-samples/amazon-rekognition-video-analyzer)
I also found a Google [Cloud Vision API](https://cloud.google.com/vision), which seems as even better solution.

**Comment by sitemapxml** [comment]
Thant you @Chocobozzz, I will try `auto mute` as soon as I take some more time for this. Regards 😃
