### ISSUE TITLE
Some translations to WebLate are missing.

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#4261]
Some Russian translations are missing on WebLate.

No translation in the left menu **IN MY LIBRARY**
![Screenshot_1](https://user-images.githubusercontent.com/11453567/126307392-84ffc13c-8d14-48db-b4d9-e90bafb2fda2.png)

No translation for filter in my videos section
![Screenshot_2](https://user-images.githubusercontent.com/11453567/126307481-da598970-3be6-4775-94ff-95b3899ccb02.png)

No translation for menu on user page
![Screenshot_3](https://user-images.githubusercontent.com/11453567/126307532-3c1adb0e-5fcd-4cad-80e3-87e7a1c81d5b.png)

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed now.
