### ISSUE TITLE
Invalid z-index for notification dropdown and admin menu titles

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#4262]
![Screenshot 2021-07-20 at 14-26-09 Users list - PeerTube](https://user-images.githubusercontent.com/1877318/126367576-8fc4be9a-a67c-40c7-af7b-e58eb0313158.png)

**Comment by frankstrater** [comment]
This problem is visible when you have a 'broadcast message' activated. In the screenshot of @kimsible you can see the light blue part of the info level broadcast message which pushes the subnavbar (with 'Federation') below.

**Comment by kimsible** [comment]
> This problem is visible when you have a 'broadcast message' activated. In the screenshot of @kimsible you can see the light blue part of the info level broadcast message which pushes the subnavbar (with 'Federation') below.

@frankstrater indeed, thanks for the details

**Comment by Chocobozzz** [comment]
Closed by https://github.com/Chocobozzz/PeerTube/pull/4266
