### ISSUE TITLE
Editing homepage with peertube markup hits API rate limit quickly

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#4264]
**Describe the current behavior**

I'm trying the homepage editior, on a the 3.3.0 release. I have three peertube-channel-embed tags in the list, and I'm editing text elsewhere in the document. Every keypress causes it to update the markdown and re-issue those API requests, so within several seconds of typing I have a swarm of error popups:

![image](https://user-images.githubusercontent.com/923812/126413315-33d3889a-123d-4a5a-b680-e9c460afc88f.png)

**Steps to reproduce:**

1. Edit homepage
2. Add some channel embeds
3. Type elsewhere in the doc

**Describe the expected behavior**

I would expect the markdown refresh to be rate-limited internally so that it's not issuing API requests on each keypress. Additionally, I'd expect rate limitation to be handled more gracefully by the client. Instead of telling me about each fail, it could internally delay and then retry.

**Additional information**

* PeerTube instance:
  * URL: diode.zone
  * version: 3.3.0 release
  * NodeJS version: 
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
I think we can remove API rate limit for admins

**Comment by scanlime** [comment]
I noticed that the rate limit is also pretty easy to hit as a logged out user reloading a homepage with about a dozen channels. Just tapping reload a few times can cause the page to no longer completely load.

**Comment by Chocobozzz** [comment]
Then I think we need to fetch homepage info in bulk

**Comment by SimplyCorbett** [comment]
> 
> 
> Then I think we need to fetch homepage info in bulk

Not to hijack this issue but is there a way to disable piping API output to daemon.log? I'm just one person and it's already 3MB big from just watching a few videos.

**Comment by scanlime** [comment]
Been hitting this a lot on my instance without trying, just during normal browsing around. I've bumped the API rate limit up by 10x as a mitigation.

**Comment by tio-trom** [comment]
Same here. Logged in or not, same error. With only 1 video embed and a bunch pulled as video-miniatures https://videos.trom.tf/

**Comment by Chocobozzz** [comment]
Bulk fetch implemented in https://github.com/Chocobozzz/PeerTube/commit/3da38d6e9f8d600476be276666ac7223aa5f172c
