### ISSUE TITLE
The left side of the window is cut off on the reports page

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#4265]
**Describe the current behavior**

On the reports page, the left side of the popup is clipped. I noticed that if the window opens at the top, then the left part of the text disappears, and if it opens at the bottom, then everything is displayed correctly. I have selected the Russian interface language.

![Screenshot_1](https://user-images.githubusercontent.com/11453567/126442315-37cc4b7b-345d-43c1-b5b6-c8267547d2da.png)
![Screenshot_2](https://user-images.githubusercontent.com/11453567/126442316-037b5b7d-9a5b-4bcb-a5f1-594780f88584.png)

**Steps to reproduce:**

1. Open the reports page.
2. Open the action menu for one report.
3. If the action window opens at the top, it will be clipped.

**Describe the expected behavior**
Should display correctly. The window should not be hidden behind the left side of the menu.

* PeerTube instance:
  * URL: https://peervideo.ru
  * version: 3.3.0

**Comment by frankstrater** [comment]
Confirmed, but not a new problem. Exists as well for 3.2.1

Technical description of this CSS bug:

2 wrapper divs: 1 for dropdown and 1 for dropup

```html
<div _ngcontent-pci-c93="" style="position: absolute; z-index: 1050; top: 0px; left: 0px; will-change: transform; transform: translate(228px, 373px);" class="dropdown">
```

```html
<div _ngcontent-pci-c93="" style="position: absolute; z-index: 1050; top: 0px; left: 0px; will-change: transform; transform: translate(233px, 557px);" class="dropup">
```

CSS entry to overwrite the z-index for dropdown in bootstap.sccs:

```css
.dropdown {
    z-index: 17000!important;
}
```

@Chocobozzz just add `.dropup` to this? Like:

```css
.dropdown, .dropup {
    z-index: 17000!important;
}
```

**Comment by kimsible** [comment]
Thanks @frankstrater I added this fix to the PR https://github.com/Chocobozzz/PeerTube/pull/4266

**Comment by Chocobozzz** [comment]
Closed by https://github.com/Chocobozzz/PeerTube/pull/4266
