### ISSUE TITLE
Errors trying to delete a user who has outstanding abuse reports

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#4268]
This has been a problem for a while but I keep forgetting to file a bug.

**Describe the current behavior**

If a user has outstanding abuse reports against their videos, I can't delete the user until i find and resolve those abuse reports.  The deletion attempt gives a popup in the lower right corner of the page with a low level database error. (I didn't screenshot the exact error before it disappeared this time)

This has been kind of a bummer because it means that when a user is kind enough to file an abuse report it actually slows me down at dealing with spam more often than it helps.

**Steps to reproduce:**

1. Upload videos
2. File abuse against those videos
3. Try to delete the entire user accout as admin

**Describe the expected behavior**

I would expect the deletion to succeed, and for the abuse reports to be resolved in the same way as if I'd deleted the videos manually before deleting the account.

**Additional information**

* PeerTube instance:
  * URL: diode.zone
  * version: 3.3.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Please paste the server log about this error

**Comment by scanlime** [comment]
Ok, I couldn't find any errors from the spam I hit this with usually, but I tried making test users and filing test reports to reproduce this.

The first attempt used a report filed by root, and I then deleted the user as root. That succeeded. In the second attempt I filed the report as a different local user, and I reproduced a failure similar to what I have seen before.

On the client side, I get a popup with the text `Error: undefined is not iterable (cannot read property Symbol(Symbol.iterator))`. In the JS console:

```
Failed to load resource: the server responded with a status of 500 ()
rest-extractor.service.ts:76 Backend returned code 500, errorMessage is: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
handleError @ rest-extractor.service.ts:76
notifier.service.ts:20 Error: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
error @ notifier.service.ts:20
```

On the server:

```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at videoFilesModelToFormattedJSON (/var/www/peertube/versions/peertube-v3.3.0/dist/server/models/video/formatter/video-format-utils.js:142:5)
    at /var/www/peertube/versions/peertube-v3.3.0/dist/server/models/video/formatter/video-format-utils.js:120:23
    at Array.map (<anonymous>)
    at streamingPlaylistsModelToFormattedJSON (/var/www/peertube/versions/peertube-v3.3.0/dist/server/models/video/formatter/video-format-utils.js:116:10)
    at Object.videoModelToFormattedDetailsJSON (/var/www/peertube/versions/peertube-v3.3.0/dist/server/models/video/formatter/video-format-utils.js:90:32)
    at VideoModel.toFormattedDetailsJSON (/var/www/peertube/versions/peertube-v3.3.0/dist/server/models/video/video.js:753:37)
    at Function.<anonymous> (/var/www/peertube/versions/peertube-v3.3.0/dist/server/models/video/video.js:135:38)
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/peertube/versions/peertube-v3.3.0/node_modules/tslib/tslib.js:114:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

At first glance this appears to be an issue that might be specific to HLS rather than abuse reports, but I've only seen it when deleting users that have outstanding abuse reports against their videos. In case it matters, the user at this time has one video that's been successfully transcoded to several resolutions.

I'll leave the test video up in case that detail is useful. (It's very short and sfw if that matters. There is one open abuse report against it, which references this bug number.)

https://diode.zone/w/84a434c5-f021-4007-8bc4-5da91bfd642d

**Comment by scanlime** [comment]
Update: Just realized that the video is in a partially-deleted state. It was still working in a browser session where I had it cached. In a fresh browser it does not load, and on the server it looks like the entire video directory in storage has been removed.

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/cd162f25d2c168d29f41bef4b9c99cb6fdfbac0a
