### ISSUE TITLE
Disable allowing download video by default

### ISSUE THREAD

**Issue by kirill2400** [Chocobozzz/PeerTube#4269]
How to set "allow download video" setting when publishing to false in config by default? I did not found this setting in production.yaml. I have many video that must be undownloadable

**Comment by SimplyCorbett** [comment]
You can save videos as internal but anyone who logs in will still be able to download them.

You can't disable downloads.

**Comment by kirill2400** [comment]
Я говорю об этом переключателе
![image](https://user-images.githubusercontent.com/30482699/126596947-a5c42575-1143-43f9-ad34-d4bef9de7f36.png)

**Comment by SimplyCorbett** [comment]
Triple checked and I can't find a "allow download video" toggle on 3.3.0.

**Comment by SimplyCorbett** [comment]
Oh. It's in the advanced settings when publishing the video.

I'll shutup and let Chocobozzz answer you.

**Comment by frankstrater** [comment]
You can't configure the default for downloadEnabled (and commentsEnabled). It's hardcoded to true as default.

**Comment by Alterak** [comment]
I also really want this daw to be unchecked by default. I have asked this question for a long time. Or, for example, by default, for all videos, leave only the torrent download, but disable direct file download.

**Comment by tio-trom** [comment]
I strongly suggest to have this as default per user basis. I, as admin, would like to be able to set a global default. I think the download button is a fantastic thing and in par with what Peertube stands for: free, open. Opposite of youtube: locked.

**Comment by rscmbbng** [comment]
+1 on an admin setting to set the default value of the download button to off and the ability for users to turn it on.

**Comment by kirill2400** [comment]
@Alterak @tio-trom @rscmbbng
I tried to make my first plugin that would at least sort of solve this problem
See the link (within 24 hours it will appear in the pertube register):
https://www.npmjs.com/package/peertube-plugin-denydownload
https://github.com/kirill2400/peertube-plugin-download-video-switcher
You can help if you want

**Comment by rscmbbng** [comment]
@kirill2400 thank you for that! However, I think such a rudimentary feature should be part of the upstream project.

**Comment by kirill2400** [comment]
> @kirill2400 thank you for that! However, I think such a rudimentary feature should be part of the upstream project.

Thanks, but I remind you that what I did is blocking the download of the video in the modal window, that is, it will not be possible to download even what is allowed with a checkmark.

**Comment by Chocobozzz** [comment]
Default value of this setting can now be changed by admins: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L81

**Comment by kirill2400** [comment]
> Default value of this setting can now be changed by admins: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L81

Is it working in 4.0.0?

**Comment by Chocobozzz** [comment]
No it will be included in 4.1.0
