### ISSUE TITLE
PeerTube not compatible with Safari 9?

### ISSUE THREAD

**Issue by jayrope** [Chocobozzz/PeerTube#4272]
Accessing a PeerTube account page leads to error as displayed in attavched screenshot.
![error peertube safari](https://user-images.githubusercontent.com/18708813/126868925-b39edb66-89e5-4f9d-99f8-4b6e5d13cf06.jpg)

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but unfortunately we can't support safari 9 that is too old: it does not support many technologies we use.
