### ISSUE TITLE
Privacy bug

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#4273]
![bug1](https://user-images.githubusercontent.com/7935624/126873635-608bb977-866f-4fe1-bbed-2c827dfcf3c3.png)

"Only I can see this video"

  * version: 3.3.0
  * NodeJS version: 14 LTS
  * Ffmpeg version: git

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/d91714ca56f7baa2f0eff02f7c1ef2b891096171
