### ISSUE TITLE
production-buster image not updated to v3.3.0

### ISSUE THREAD

**Issue by michael-robbins** [Chocobozzz/PeerTube#4275]
**Describe the current behavior**

The `production-buster` image hasn't been updated to v3.3.0 yet.

**Steps to reproduce:**
N/A

**Describe the expected behavior**

The `production-buster` image is updated to v3.3.0.

**Additional information**
N/A

**Comment by normen** [comment]
+1 You can use the `v3.3.0-buster` image in the meantime..

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed now
