### ISSUE TITLE
How much (estimated) network bandwidth viewers can contribute?

### ISSUE THREAD

**Issue by xokctah** [Chocobozzz/PeerTube#4278]
Hi there. We are planning a new instance of peertube. We would like to know that how much bandwidth realistically can be contributed by the viewers in a typical configuration - or, in another way, how much network capacity of the server can be saved comparing to a centralized video streaming solution.

We saw the [FAQ](https://joinpeertube.org/faq#should-i-have-a-big-server-to-run-peertube) says:

> If other PeerTube instances following yours, chances are they have decided to mirror part of your instance! The feature is called "server redundancy" and caches your most popular videos to help serve additional viewers. While viewers themselves contribute a little additional bandwidth while watching the video in their browsers (mostly during surges), mirroring servers have a much greater uplink and will help your instance with sustained higher concurrent streaming.

it sounds like that client side browsers do not share a lot of data between each other. Is that the real case? It would be very thankful if someone can share some experience.

Thanks!

**Comment by SimplyCorbett** [comment]
Peers can take on the entire load of the video without the server uploading anything.

![firefox_L3TNaLg44r](https://user-images.githubusercontent.com/7935624/127158550-a17f5eb2-93b4-4649-8ac0-4c323e8b69fa.png)

**Comment by xokctah** [comment]
> Peers can take on the entire load of the video without the server uploading anything.
> 
> This is an example where the server did a partial upload.
> 
> ![firefox_L3TNaLg44r](https://user-images.githubusercontent.com/7935624/127158550-a17f5eb2-93b4-4649-8ac0-4c323e8b69fa.png)

Thanks for sharing this. 

We are more interested to know, statistically, in a typical running instance, what is the percentage of network traffic that we can expect PeerTube help to save, comparing a traditional centralized solution. I would expect a lower percentage (maybe less than 20%?) if there are less concurrent viewers watching longer tail videos, and higher percentage (maybe more than 90%?) if there are a lot of viewers watching a viral video at the same time. But we don't have any factual base to come up to a reasonable estimation. Is there some experiential data someone can share?

**Comment by SimplyCorbett** [comment]
Hi!

It really depends on the quality of your videos and your targeted demographic.

Less peers = less savings. Some areas of say the USA only have up to 3Mbps upload speeds.

Realistically any video that goes viral is going to be mostly or entirely p2p.

As far as knowing statistically how effective the p2p portion is that would be a question for TILVids and diode.zone which are the two largest instances I personally know of. @scanlime do you have any data you're willing to share?

**Comment by scanlime** [comment]
PeerTube does not gather any data from clients that could be used to determine the effectiveness of the hls loader or video redundancies.

In my experience with running diode.zone, performance is basically always better from the main server than the redundancies, and I've never seen p2p-hls help at all.

We have a gigabit pipe and bandwidth is not even close to the main concern. There's a steady trickle of views but nothing that would overwhelm the server.

IMO the multiple different systems in peertube (webtorrent, hls-p2p, and redundancies) are all fairly ineffective and undermeasured at this point.

**Comment by scanlime** [comment]
> Peers can take on the entire load of the video without the server uploading anything.

I also have to say this is explicitly not true. The main server has to be working and responsive for the video to load, even if there are plenty of peers that all have the entire video and infinite bandwidth.

In a real case though, you have at best some number of peers that have some subset of the content and a fairly unpredictable amount of performance. The client has a tough job to do, being asked to play smooth unbreaking video from all of those servers. We don't have the infrastructure in PeerTube necessary to ensure this happens. We'd need to, at the very very least, have testing and stats-gathering projects. We'd probably also need clients to be much smarter about downloading from multiple locations than they currently are, and we'd likely want the server to help coordinate these estimates of peer/server bandwidth and reliability.

**Comment by SimplyCorbett** [comment]
> I also have to say this is explicitly not true. The main server has to be working and responsive for the video to load, even if there are plenty of peers that all have the entire video and infinite bandwidth.

Yes but if one peer has the data the other peer can get the data from them. I've tested this on my LAN. The server does need to be responsive though as you've stated.

In a real world use case unless the video went viral you're probably going to be getting more data from the server then other peers.... I'm also not sure how peertube handles peers with poor upload. Are they dropped from the swarm? How does that work.

More stats would be nice to have.

**Comment by scanlime** [comment]
You will not get the same results from testing with peers on a LAN. There you're likely using WebRTC local broadcasts to find each other quickly. Test on a network with latency and NAT for realistic results.

As far as I'm aware there isn't a load balancing system for peers, nor would there be a way for clients to avoid requesting video from the server when it's nearing capacity. I don't think there's any kind of signaling system for expected capacity or latencies.

**Comment by wanyouzhu** [comment]
I want to know this, too. Is there any data to show the saving bandwidth from viewers? I appreciate it if anyone could provide me with any data about that.

**Comment by scanlime** [comment]
> I want to know this, too. Is there any data to show the saving bandwidth from viewers? I appreciate it if anyone could provide me with any data about that.

We would need a system to gather this data, since it's not something the server is directly involved in.

**Comment by Chocobozzz** [comment]
The question seems to have been answered, so closing.

See https://github.com/Chocobozzz/PeerTube/issues/1855 for player stats
