### ISSUE TITLE
Custom Themes for Corporate Design for Public Authorities / Municipalities

### ISSUE THREAD

**Issue by Lukas2112** [Chocobozzz/PeerTube#4284]
**Describe the problem to be solved**
Implementation of comprehensive possibilities to integrate custom themes in order to comply with corporate design. This functionality could contribute to the public broadcasters in the Federal Republic of Germany perhaps considering using PeerTube for their media libraries in the future.

**Describe the solution you would like:**
A simple and intuitive possibility to set a custom theme within PeerTube, in the best case instance-wide.

**Comment by rigelk** [comment]
hi @Lukas2112,

What is lacking in https://docs.joinpeertube.org/contribute-plugins?id=write-a-plugintheme for that use case?

**Comment by Lukas2112** [comment]
Thank you for your answer. Oh, I seem to have overlooked this page in the documentation or simply not read it thoroughly enough - I'm sorry... As far as I understand it, this would make what I had in mind implementable.

I think the issue can be closed.
