### ISSUE TITLE
Setting video playtime no longer works

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#4286]
Pressing the time in the description used to jump the video ahead to that specific time. This no longer works. The video doesn't jump ahead in version 3.3.0 / Nodejs 14 LTS / ffmpeg 4.3.2 / latest firefox on Linux.

![13](https://user-images.githubusercontent.com/7935624/127387394-bbf6dc87-bd6e-4214-8056-4622ba6bb0d0.png)

![14](https://user-images.githubusercontent.com/7935624/127387140-ab6b1ed9-4572-48f3-9d66-24d52cac0a42.png)

**Comment by SimplyCorbett** [comment]
This must be because the video is internal. If I hard refresh the page with the video playing I get a 404 not found.. even though it was playing fine before the refresh.

**Comment by Chocobozzz** [comment]
Thanks, I fixed this in https://github.com/Chocobozzz/PeerTube/commit/a00056c0c87b9a3c79a50fc98fa385218cdb3734
