### ISSUE TITLE
Torrent errors (code 500 from xs param) prevent any upload & play of new videos

### ISSUE THREAD

**Issue by yPhil-gh** [Chocobozzz/PeerTube#4287]
**Describe the current behavior**

I can't upload videos anymore, and what's even more strange, I can't even watch videos.... Upon closer inspection it seems that I can only view and play *new* videos, that I haven't already seen :(

**Steps to reproduce:**

1. Access https://exode.me/videos/watch/fed67262-6edb-4d1c-833b-daa9085c71d7 from any machine inside my local network

**Describe the expected behavior**

The video should play

**Additional information**

* PeerTube instance:
  * URL: https://exode.me/
  * version: 3.2.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox & Chrome on Linux Ubuntu, and JQuarks on Android
* Link to browser console log if relevant: Yes! A **lot** of errors in the browser console about torrent stuff, example: `Error: non-200 status code 500 from xs param: https://exode.me/lazy-static/torrents/fed67262-6edb-4d1c-833b-daa9085c71d7-240.torrent`
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Please paste logs from server logs 

> Link to server log if relevant (journalctl or /var/www/peertube/storage/logs/):

**Comment by yPhil-gh** [comment]
Hi @Chocobozzz thanks for your answer, unfortunately I don't have access to the server, I'm just a mere user :)

FYI, the problem persists here, I can't upload any video (even very small ones, and I'm way below my quota) this sets things quite a bit, I really wonder what could be going on..?

**Comment by yPhil-gh** [comment]
Update: Suspecting the annotation plugin (well, rather my heavy-handed overuse of it) I went ahead and tried to **remove all annotations**, but it turns out I can't!! And **that** is the problem, I'm pretty sure. So now I guess the instance database is somehow corrupted, kinda feel guilty about that 😧

**Comment by Chocobozzz** [comment]
It seems to be a server issue: https://exode.me/static/streaming-playlists/hls/6e3b6426-f2da-498b-afa3-47bf4e562dde/master.m3u8

Please contact your administration instead
