### ISSUE TITLE
Remove brief flash of thumbnail on peertube embeds

### ISSUE THREAD

**Issue by tilllt** [Chocobozzz/PeerTube#4288]
**Describe the current behavior**

**Steps to reproduce:**

1. [sample embed link ](https://www.pixelscope.de/videos/embed/12259e53-73a9-4a4a-b32c-a63f2c90b8d0?title=false&subtitle=false&controls=true&warningTitle=0&autoplay=true&peertubeLink=0)
2. Open in Browser
3. See Brief flash of Thumbnail

**Describe the expected behavior**
Thumbnail shouldnt show on Embeds

* PeerTube instance:
  * URL: https://www.pixelscope.de/
  * version: 3.3.0 / docker

* Shows on all browsers

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/200eaf5152ca72fe6b05a49caf819e22bd045b37
