### ISSUE TITLE
Embed video links do not work

### ISSUE THREAD

**Issue by tio-trom** [Chocobozzz/PeerTube#4289]
This was an error I reported before but maybe since you changed the url structure recently you added the bug back in :). See an embed video like here https://www.tromsite.com/videos/ - if you click the peertube logo or copy the link of the video, it does not work. Redirects to https://videos.trom.tf/video-playlists/w/9d1478a9-972f-4f4e-8376-74e3b5ec86c0 and the proper links should be https://videos.trom.tf/w/p/kp2bHhdWdXSkgirtvSAuQy

**Comment by Chocobozzz** [comment]
Thanks, it will be fixed in 3.4
