### ISSUE TITLE
Cannot create live because this instance have too many created lives

### ISSUE THREAD

**Issue by tio-trom** [Chocobozzz/PeerTube#4292]
I have checked my instance and there is no live running. I have setup 10 simultaneous lives and 2 per user. If I add unlimited simultaneous lives it works tho. So it must be a bug.

**Describe the current behavior**
 Cannot create live because this instance have too many created lives. That's the error I get while trying to create a live.

**Steps to reproduce:**

1. Setup a limited number of lives in your admin. I had 10 simultaneously and 2 per user.
2. Although no one was doing any live, I tried creating a live and I could not becasue of the above error.
3. If I increase the limit of lives to unlimited, it then works.

**Additional information**

* PeerTube instance: https://videos.trom.tf/
  * URL: https://videos.trom.tf/
  * version:  3.3.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox + Linux Arch

**Comment by rigelk** [comment]
Hi,

Please fill the issue template.

**Comment by tio-trom** [comment]
I apologize. Did it now!

**Comment by scanlime** [comment]
I'm pretty sure the limit on "number of lives" has always been total not just active streams. I've had to bump this to unlimited on my instance too, even though I'd like to be able to limit the number of running streams too so we don't exhaust the CPU and RAM.

**Comment by tio-trom** [comment]
> I'm pretty sure the limit on "number of lives" has always been total not just active streams. I've had to bump this to unlimited on my instance too, even though I'd like to be able to limit the number of running streams too so we don't exhaust the CPU and RAM.

Hm...so it means that some users have created a Live but didn't go live so now we have a bunch of "lives" that are not "lives"? This should be fixed somehow tho. To detect when a live is truly live. Else users can create lots of such "lives" and leave them there as zombie lives....

**Comment by scanlime** [comment]
Yes, there are plenty of zombie live streams :)
It doesn't harm much except it does make this setting effectively useless as it is now.

**Comment by rscmbbng** [comment]
Just want to chip in that I've also run in to the issue of the zombie live streams. It took quite a while to find out what was happening until we stumbled upon several month's old zombie live streams. Perhaps an expiry date that automatically closes a live if it has not been used in x amount of time could help in these situations.

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/3671
