### ISSUE TITLE
No transcoding after the live

### ISSUE THREAD

**Issue by tio-trom** [Chocobozzz/PeerTube#4293]
**Describe the current behavior**
I made a live like we used to, but same as in the past I did not enable "transcoding" for live streams since this never worked properly, stopping the stream after an hour or so for some reasons. But it used to be that after the live, the saved video was also transcoded just like any other uploaded video. Now it does not.

Maybe I do not understand the new setup. If I enable the transcoding for live videos does this mean that it transcodes the videos while the live is running? In parallel? Or after the live is done?
**Additional information**

* PeerTube instance:
  * URL: https://videos.trom.tf/
  * version: 3.3.0

* Browser name, version and platforms on which you could reproduce the bug: Firefox

**Comment by Chocobozzz** [comment]
> Maybe I do not understand the new setup. If I enable the transcoding for live videos does this mean that it transcodes the videos while the live is running? In parallel? Or after the live is done?

After the live is done.
