### ISSUE TITLE
Can I embed video from YouTube channels and single videos from other video repositories without uploading them to my server?

### ISSUE THREAD

**Issue by volanar** [Chocobozzz/PeerTube#4295]
Hello. Can I embed video from YouTube channels and single videos from other video repositories without uploading them to my server?

**Comment by scanlime** [comment]
no. peertube was not designed to be a youtube client, it doesn't federate links to video webpages, it federates links to the actual video data. it has its own formats the video would have to be converted to. and youtube was not designed to be a CDN with stable links, so even if this were implemented on the peertube side, youtube would still make changes that break all stored links.
