### ISSUE TITLE
P2P video problem

### ISSUE THREAD

**Issue by ne-vlezay80** [Chocobozzz/PeerTube#4299]
**Describe the current behavior**

**Steps to reproduce:**

1.Play all videos

**Describe the expected behavior**

P2P is not working from all videos.

**Additional information**

* PeerTube instance:
  * URL: http://[301:3559:2828:2843::4]
  * version: 3.3.0
  * NodeJS version: 12.22.4
  * Ffmpeg version: 4.1.6

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* https://pastebin.com/raw/ypguKdAa
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
* http://paste.debian.net/1206451/

**Comment by Chocobozzz** [comment]
What is your web browser?

**Comment by ne-vlezay80** [comment]
> What is your web browser?

Firefox 90.0.2
IceCat 78.6.1rc2
Chromium 92.0.4515.107

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/ff5f37e4f3d23ec8ade8baae5c1b73fe2ac7732c
