### ISSUE TITLE
Backend validation is too permissive for channel names

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4301]
**Describe the current behavior**

By reading the code, the only backend validation that I found for channel names is here:
https://github.com/Chocobozzz/PeerTube/blob/ff4de38385049bf8f6e1d76d8511854fcfabc71c/server/middlewares/validators/videos/video-channels.ts#L20

This function allows:
https://github.com/Chocobozzz/PeerTube/blob/ff4de38385049bf8f6e1d76d8511854fcfabc71c/server/helpers/custom-validators/activitypub/actor.ts#L35-L39

I think there are several characters that should not be allowed (backslash, hyphen, colon). The front-end form does not allow all these characters. 

**Describe the expected behavior**
Backend and Frontend validation should allow the same characters.

* PeerTube instance:
  * version: 3.3.0

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/27db78400c558e19bfac0da885fe0b7d0a3e6a0c
