### ISSUE TITLE
large Videos are not replicated: Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close

### ISSUE THREAD

**Issue by bin2brain** [Chocobozzz/PeerTube#4302]
**Describe the current behavior**
I've uploaded a huge (~30GB) Video x264 and MP4 to the first of my Instances, after transcoding i expect the Video to be replicated by the following Instances.
If i leave the Nginx Rate Limits default it simply runs into a Timeout. If i fully disable Limits for redundancy the timeout Error is gone but i get the following:
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (node:internal/errors:329:5)
    at Request.onclose (node:internal/streams/end-of-stream:138:38)
    at Request.emit (node:events:381:22)
    at Request.emit (node:domain:470:12)
    at emitCloseNT (node:internal/streams/destroy:169:10)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)

This then happens in a loop in the set interval an consumes a lot of traffic.

**Steps to reproduce:**

1. uploaded a huge (~30GB) Video x264 
2. wait for the transcoding
3. disable nginx rate limits on the first system
4. follow the first system with the secondary and enable video redundancy
5. trigger a manual mirror of the Video on the second instance or wait for a strategie to execute the replication

**Describe the expected behavior**
The Video gets successfully transferred to the follower Nodes or the replication for this Video stops after N tries.

**Additional information**
The replication of this Video worked in v3.1.0 with a increased Buffer in 
peertube-v3.1.0/dist/server/helpers/requests.js

* PeerTube instance:
  * URL:
  * version: v3.3.0
  * NodeJS version: v15.14.0
  * Ffmpeg version:  4.2.4

**Comment by Chocobozzz** [comment]
Do you try to mirror HLS videos? If yes, try to increase the limit here: https://github.com/Chocobozzz/PeerTube/blob/develop/server/lib/hls.ts#L140

**Comment by bin2brain** [comment]
@Chocobozzz thanks i simply didn't know what value to adjust :-) .
I think it would still make sense to implement a mechanism to check if the size exceeds the limit and if it does don't mirror the video at all.

Anyway i'm really thankfull for such a great piece of software and for your help, keep up the amazing work :+1:

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/18998c45c001869a883ec7a2d286d8170f768381
