### ISSUE TITLE
"Theater" mode

### ISSUE THREAD

**Issue by Phyks** [Chocobozzz/PeerTube#431]
Hi,

Some hosted platforms offer a so-called "theater" mode, which would dim down the elements on the page, except the video player. This allows the user to focus on the video (as all the other elements on the page are hidden / dimmed) and is a good alternative to fullscreen for instance when watching a video in a windows, while doing something else aside (in a split-screen setup for instance). Not sure if this is something that could fit for PeerTube as well, but I tend to think it would be a nice addition :)

As far as I know, video playback relies on videojs and there seems to be a module available [here](https://github.com/jgubman/videojs-theater-mode) to (partially) handle theater mode. 

Thanks!

**Comment by NaveenKarippai** [comment]
@Chocobozzz 

Can I pick this one please?

**Comment by Chocobozzz** [comment]
Sure

**Comment by rigelk** [comment]
@NaveenKarippai any update on this?

**Comment by NaveenKarippai** [comment]
@rigelk apologies for not giving an update! I may not be able to work on this soon.

**Comment by rigelk** [comment]
No worries @NaveenKarippai ; it's just so that we can know what is being worked on :)

**Comment by hoodiek** [comment]
something extremely relevant to theater mode is the video resizing automatically to fill the horizontal space available. (example attached)
![image](https://user-images.githubusercontent.com/23704040/41080387-3fe44936-69f4-11e8-9c90-9bf963889eb2.png)
 i would recommend this feature be somewhat seperate to the many 'theater mode dim' addons that exist for youtube, whether it be via tampermonkey / extension / etc, i personally like the horizontal size change and do not want it to dim. i would argue it might only need to be a checkbox for the dim to be 'dim when playing' or 'dim when in theater mode'

i imagine either solution could work, and i cannot decide which is preferable personally, as the dim-feature is not something i personally would use

**Comment by hoodiek** [comment]
@Phyks i neglected to @ you originally, but as you requested the dim function, which solution do you think might be better? or is neither fitting your use-case?

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/054a103b286277708a3a807a52da6cca12e1b0ce

The player takes all the entire width and height (with ~80px for the bottom margin). 

Demo: https://peertube2.cpy.re/videos/watch/217eefeb-883d-45be-b7fc-a788ad8507d3

**Comment by Phyks** [comment]
Oops, sorry I missed @hoodiek answer. That's awesome, thanks @Chocobozzz! =)

**Comment by test2a** [comment]
@Chocobozzz  hey. shouldn't the sidebar collapse itself when entering the "theater mode" because you mentioned above 
>The player takes the entire width and height 

is this by design? 
The first screenshot below is default result on pressing theater mode button. second screenshot is after manually collapsing the sidebar.

![Screenshot_20201104_215201](https://user-images.githubusercontent.com/39449563/98137703-4becfb00-1ee8-11eb-9883-674dc2c21bbb.png)

![Screenshot_20201104_215220](https://user-images.githubusercontent.com/39449563/98137711-4e4f5500-1ee8-11eb-8dd6-6dbe9667362b.png)
