### ISSUE TITLE
What about deploy an instance in China Mainland

### ISSUE THREAD

**Issue by magictomagic** [Chocobozzz/PeerTube#4316]
**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Additional information**

* PeerTube instance:
  * version:
  * NodeJS version:
  * Ffmpeg version:
  * Redis version:
  * PostgreSQL version:

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I don't understand the question.
