### ISSUE TITLE
Plugin template with webpack 5

### ISSUE THREAD

**Issue by geco** [Chocobozzz/PeerTube#4318]
Hello @Chocobozzz,
do you think it's possible to configure peertube plugins to be built using webpack 5 (or rollup)?
I have some dependencies problems with webpack old version.
Using this template https://framagit.org/framasoft/peertube/peertube-plugin-quickstart i've tried on my own to update to webpack 5, but purtuga plugin isn't supported and webpack 5 yet doesn't produce esm module.

Thank you in advance

**Comment by Chocobozzz** [comment]
Hi,

Please pull the repository I updated plugin to use webpack 5: https://framagit.org/framasoft/peertube/peertube-plugin-quickstart/-/commit/0595929613ca41b9650aa19ff01e66b4c666031a
