### ISSUE TITLE
Add hook before transcoding

### ISSUE THREAD

**Issue by albjeremias** [Chocobozzz/PeerTube#4319]
I would like to program a plugin for peertube that would blur faces automatically

Well, i'd like to known from this list of [plugins](https://framagit.org/framasoft/peertube/official-plugins) which one should I pick. I only need to run a python [script](https://github.com/JeiKeiLim/Anonymizing_video_by_DSFD) before transcoding.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/22df69fdecf299c8be6acaa25f086249ea9a0085

You can add a hook before the transcoding job is processed:

```js

  registerHook({
    target: 'filter:job-queue.process.params',
    handler: (object, context) => {
      if (context.type !== 'video-transcoding') return object

      // to what you want

      return object
    }
  })
```
