### ISSUE TITLE
error: Cannot execute migration 0005.

### ISSUE THREAD

**Issue by salvadorpla** [Chocobozzz/PeerTube#432]
Hello,

After following installation instructions when I run `NODE_ENV=production npm start` to run it for the very first time it throws following error:

```
info: Begin migrations.
info: Executing 0005-email-pod.js migration script.
error: Cannot execute migration 0005. {
  "meta": {
    "err": "SequelizeDatabaseError: relation \"public.Pods\" does not exist\n    at Query.formatError (/home/peertube/PeerTube/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)\n    at query.catch.err (/home/peertube/PeerTube/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)\n    at tryCatcher (/home/peertube/PeerTube/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/peertube/PeerTube/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/home/peertube/PeerTube/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/home/peertube/PeerTube/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/home/peertube/PeerTube/node_modules/bluebird/js/release/promise.js:689:18)\n    at Async._drainQueue (/home/peertube/PeerTube/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/home/peertube/PeerTube/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/home/peertube/PeerTube/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:794:20)\n    at tryOnImmediate (timers.js:752:5)\n    at processImmediate [as _immediateCallback] (timers.js:729:5)"
  }
}
```

Any help will be appreciated.
Thanks !

PeerTube version or URL: v1.0.0-beta.2
node -v -> v8.11.0

**Comment by Chocobozzz** [comment]
Could you connect to your database configured in your production configuration file and do `\d`?

**Comment by salvadorpla** [comment]
Yes. I'm into it right now

peertube_prod=> \d
                   List of relations
 Schema |          Name           |   Type   |  Owner   
--------+-------------------------+----------+----------
 public | account                 | table    | peertube
 public | accountVideoRate        | table    | peertube
 public | accountVideoRate_id_seq | sequence | peertube
 public | account_id_seq          | sequence | peertube
 public | actor                   | table    | peertube
 public | actorFollow             | table    | peertube
 public | actorFollow_id_seq      | sequence | peertube
 public | actor_id_seq            | sequence | peertube
 public | application             | table    | peertube
 public | application_id_seq      | sequence | peertube
 public | avatar                  | table    | peertube
 public | avatar_id_seq           | sequence | peertube
 public | oAuthClient             | table    | peertube
 public | oAuthClient_id_seq      | sequence | peertube
 public | oAuthToken              | table    | peertube
 public | oAuthToken_id_seq       | sequence | peertube
 public | server                  | table    | peertube
 public | server_id_seq           | sequence | peertube
 public | tag                     | table    | peertube
 public | tag_id_seq              | sequence | peertube
 public | user                    | table    | peertube
 public | user_id_seq             | sequence | peertube
 public | video                   | table    | peertube
 public | videoAbuse              | table    | peertube
 public | videoAbuse_id_seq       | sequence | peertube
 public | videoBlacklist          | table    | peertube
 public | videoBlacklist_id_seq   | sequence | peertube
 public | videoChannel            | table    | peertube
 public | videoChannel_id_seq     | sequence | peertube
 public | videoComment            | table    | peertube
 public | videoComment_id_seq     | sequence | peertube
 public | videoFile               | table    | peertube
 public | videoFile_id_seq        | sequence | peertube
 public | videoShare              | table    | peertube
 public | videoShare_id_seq       | sequence | peertube
 public | videoTag                | table    | peertube
 public | video_id_seq            | sequence | peertube
(37 rows)

**Comment by salvadorpla** [comment]
Ok, let me some time... will be back in a while

**Comment by salvadorpla** [comment]
Excuse me, how can I run peertube with debug logs ?

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L52

**Comment by salvadorpla** [comment]
Here it is :

 info: Begin migrations.
 info: Executing 0005-email-pod.js migration script.
debug: Executing (dc8f2d93-9b9f-4a7d-99ca-ea65a739505e): START TRANSACTION;
debug: Executing (dc8f2d93-9b9f-4a7d-99ca-ea65a739505e): SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
debug: Executing (default): ALTER TABLE "public"."Pods" ADD COLUMN "email" VARCHAR(400) NOT NULL DEFAULT '';
debug: Executing (dc8f2d93-9b9f-4a7d-99ca-ea65a739505e): ROLLBACK;
error: Cannot execute migration 0005. {
  "meta": {
    "err": "SequelizeDatabaseError: relation \"public.Pods\" does not exist\n

**Comment by salvadorpla** [comment]
If I run "AFTER TABLE ..." in psql:

peertube_prod=> ALTER TABLE "public"."Pods" ADD COLUMN "email" VARCHAR(400) NOT NULL DEFAULT '';
ERROR:  relation "public.Pods" does not exist

**Comment by salvadorpla** [comment]
Some progress!
If I create an empty table:

peertube_prod=> CREATE TABLE "public"."Pods" ();

I get no error but it stalls here: 

info: Executing 0005-email-pod.js migration script.
debug: Executing (a9243235-efc4-41ff-9464-d78247dff9c3): START TRANSACTION;
debug: Executing (a9243235-efc4-41ff-9464-d78247dff9c3): SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
debug: Executing (default): ALTER TABLE "public"."Pods" ADD COLUMN "email" VARCHAR(400) NOT NULL DEFAULT '';
debug: Executing (a9243235-efc4-41ff-9464-d78247dff9c3): UPDATE "Pods" SET "email" = 'dummy@example.com'
debug: Executing (default): ALTER TABLE "Pods" ALTER COLUMN "email" SET NOT NULL;ALTER TABLE "Pods" ALTER COLUMN "email" SET DEFAULT NULL;ALTER TABLE "Pods" ALTER COLUMN "email" TYPE VARCHAR(400);

**Comment by salvadorpla** [comment]
I've just changed storage dirs from /var/www/peertube to /home/peertube in config/production.yaml
and the migration error is gone!
My peertube instance is alive ;-)

**Comment by BigMayo** [comment]
Was there a resolution to this issue? I am running into the same issues, however the fix the OP used did not work for me.
