### ISSUE TITLE
Can I recover a live stream video?

### ISSUE THREAD

**Issue by tio-trom** [Chocobozzz/PeerTube#4322]
I forgot to enable "Automatically publish a replay" and now my 2h podcast livestream is gone. It is 100% my fault since I should have paid attention, but I also think Peertube should by default store lives and only if you select not to, to delete them.

In any case, is there any chance I can grab the video from my server? I am the owner of the server but I cannot find the video....

Any help please?

**Comment by Chocobozzz** [comment]
Hello,

No sorry you can't recover your stream because peertube has not saved the video segments. I'll see how to fix https://github.com/Chocobozzz/PeerTube/issues/4024
