### ISSUE TITLE
Incompatible with MyPal since today?!

### ISSUE THREAD

**Issue by sirrooster** [Chocobozzz/PeerTube#4326]
Hello,
sinde today I get the message, Mypal is incompatible with peertube
So it doen't show me any video.
https://vdp.veezee.tube/

My Browser is MyPal
https://github.com/Feodor2/Mypal/

Regards,
Marc

**Comment by ROBERT-MCDOWELL** [comment]
issue duplicated, palemoon
https://github.com/Chocobozzz/PeerTube/issues/4311
it seems that some javascript library changed, sadly.
