### ISSUE TITLE
API cannot add tags

### ISSUE THREAD

**Issue by lastcrash** [Chocobozzz/PeerTube#4327]
![image](https://user-images.githubusercontent.com/65862497/129471138-dffd8c81-a110-4ae2-bbdc-8f75bbf2e74e.png)

this error message on bash:
`{"errors":{"tags":{"value":"TAG1","msg":"Should have correct tags","param":"tags","location":"body"}}}`

**Comment by rigelk** [comment]
Hi, what version of PeerTube are you using?

**Comment by lastcrash** [comment]
@rigelk 
PeerTube version | 3.2.1
site:https://video.ploud.jp/

**Comment by Chocobozzz** [comment]
Please paste the command you use to upload a video

**Comment by frankstrater** [comment]
In your screenshot it should work with `--form tags[0]="TAG1"` because tags is an array/list.

**Comment by lastcrash** [comment]
> In your screenshot it should work with `--form tags[0]="TAG1"` because tags is an array/list.

works thanks
