### ISSUE TITLE
Settings Menu is too small for content

### ISSUE THREAD

**Issue by Mastercuber** [Chocobozzz/PeerTube#4330]
**Describe the current behavior**
First, this is probably only a problem with translations.

I installed an instance with German translations. When I view a video and open the settings everything shows just fine. But when I then open quality or speed, the opened menu is too small for the translated text f.e. "Geschwindigkeit" (means speed).

I think you better take a look yourself:
Settings->Speed      |  Settings->Speed (scrolled) | Settings->Quality
:-------------------------:|:-------------------------------------:|:-----------------------:

![Settings-Speed](https://user-images.githubusercontent.com/14162739/129790242-8fc471b0-d46b-42a1-abde-408ce2fc83f0.png) ![Settings-Speed-Scrolled](https://user-images.githubusercontent.com/14162739/129790241-efa7051e-1842-4da0-ae37-60b9bbf04f0d.png) ![Settings-Quality](https://user-images.githubusercontent.com/14162739/129790244-82c07afe-f426-4ddb-8b5a-35757dd0736c.png)

**Steps to reproduce:**

1. Go to a f.e. German PeerTube instance
2. View a video
3. Click on settings
4. Click on quality/speed

**Describe the expected behavior**
Expected behavior would be that the settings menu container adapts its width to the content without showing a scrollbar.

Maybe a `min-width` in combination with `width: max-content` could be enough. Or a dynamically computed width based on the width of the content..

BTW this is also true for the statistics (right click a video and click on the last element in the list)

![Statistics](https://user-images.githubusercontent.com/14162739/129792151-07050015-d4b9-4a75-96a2-84f9e59739f0.png)

**Additional information**

* PeerTube instance:
  * URL: https://tube.avensio.de/w/8yQqFN7E9KArZyp9Pt4CeP
  * version: 3.3.0
  * NodeJS version: shouldn't mind
  * Ffmpeg version: shouldn't mind

Checked  this bug in 2 Browsers: 
* First is Firefox 91.0 
* Chrome Version 86.0.4240.183
both on Ubuntu 20.04.2 LTS

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/f7891304f0c344e343df4271414c9d096ce7b4e4 and https://github.com/Chocobozzz/PeerTube/commit/5f31aaa398b83c974b8357c4e7aae66320d16271

**Comment by Mastercuber** [comment]
Glad to hear that and looking forward to upgrade to the version containing this fixes :smiley:
