### ISSUE TITLE
The number of video views can't be displayed when the language is set to Japanese

### ISSUE THREAD

**Issue by r6fans** [Chocobozzz/PeerTube#4332]
**Describe the current behavior**
When I set the language to Japanese, I can't see the the number of video views. But everything is fine in English

* English
![IMG_20210818_135436](https://user-images.githubusercontent.com/22339010/129845956-1e60c889-8a45-4b5c-9c2c-fcdd6fee06b7.jpg)

* Japanese
![IMG_20210818_135419](https://user-images.githubusercontent.com/22339010/129846033-2f119063-30f4-4838-ad09-5d443b2f3096.jpg)

**Steps to reproduce:**
1.set language to Japanese

**Describe the expected behavior**
See the number of video views when language is Japanese

**Additional information**

* PeerTube instance:
  * URL:  https://peertube.cpy.re
  * version: 3.3.0
  * NodeJS version:
  * Ffmpeg version:
  * Browser name/version: Google chrome 92

**Comment by Chocobozzz** [comment]
Thanks, I fixed the translations on weblate and pulled them.

Will be available on https://peertube2.cpy.re/ tomorrow
