### ISSUE TITLE
Design not rendered as supposed

### ISSUE THREAD

**Issue by unteem** [Chocobozzz/PeerTube#435]
I'm having some issues on how design is rendered

See: https://videos.lescommuns.org/ (https is not active yet)
I'm running it with Docker. Everything is here: https://github.com/libresh/peertube

**Comment by Chocobozzz** [comment]
The CSS file is transferred as plain-text mime-type. Try https://www.digitalocean.com/community/questions/css-files-not-interpreted-by-the-client-s-browser-i-think-my-nginx-config-is-not-good

**Comment by unteem** [comment]
indeed I missed this line `include /etc/nginx/mime.types` in my `nginx.conf`
Thanks and keep up the good work ;)
