### ISSUE TITLE
Can anyone share a working docker-compose .env file, pls? Mine always says "SequelizeConnectionError: password authentication failed for user peertube"

### ISSUE THREAD

**Issue by fishfree** [Chocobozzz/PeerTube#4355]
Run `docker-compose ps`, it shows as below:
peertube-docker_peertube_1    /usr/local/bin/entrypoint. ...   Restarting                                                
peertube-docker_postgres_1    docker-entrypoint.sh postgres    Up           5432/tcp                                     
peertube-docker_redis_1       docker-entrypoint.sh redis ...   Up           6379/tcp                                     
peertube-docker_webserver_1   /bin/sh entrypoint.nginx.sh      Up           443/tcp, 0.0.0.0:8082->80/tcp,:::8082->80/tcp

The peertube container is always restarting, run `docker-compose logs peertbue`, it shows as below:
peertube_1   | [corpus-stream.shisu.edu.cn:80] 2021-08-26 06:19:53.964 error: Unable to connect to PostgreSQL database. {
peertube_1   |   "err": {
peertube_1   |     "stack": "SequelizeConnectionError: password authentication failed for user \"peertube\"\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:184:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:305:19)\n    at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:325:19)\n    at Connection.emit (events.js:314:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /app/node_modules/pg/lib/connection.js:114:12\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:40:17)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (events.js:314:20)\n    at Socket.EventEmitter.emit (domain.js:483:12)\n    at addChunk (_stream_readable.js:297:12)\n    at readableAddChunk (_stream_readable.js:272:9)\n    at Socket.Readable.push (_stream_readable.js:213:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)",
peertube_1   |     "message": "password authentication failed for user \"peertube\"",
peertube_1   |     "name": "SequelizeConnectionError",
peertube_1   |     "parent": {
peertube_1   |       "stack": "error: password authentication failed for user \"peertube\"\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (events.js:314:20)\n    at Socket.EventEmitter.emit (domain.js:483:12)\n    at addChunk (_stream_readable.js:297:12)\n    at readableAddChunk (_stream_readable.js:272:9)\n    at Socket.Readable.push (_stream_readable.js:213:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)",
peertube_1   |       "message": "password authentication failed for user \"peertube\"",
peertube_1   |       "length": 104,
peertube_1   |       "name": "error",
peertube_1   |       "severity": "FATAL",
peertube_1   |       "code": "28P01",
peertube_1   |       "file": "auth.c",
peertube_1   |       "line": "331",
peertube_1   |       "routine": "auth_failed"
peertube_1   |     }
peertube_1   |   }
peertube_1   | }

Part of my .env file is as below:

POSTGRES_USER=postgres
POSTGRES_PASSWORD=password
POSTGRES_DB=peertube
PEERTUBE_DB_SUFFIX=_prod
PEERTUBE_DB_USERNAME=peertube
PEERTUBE_DB_PASSWORD=peertubepassword
PEERTUBE_DB_SSL=false
PEERTUBE_DB_HOSTNAME=postgres

**Comment by stoically** [comment]
Out of curiosity, if they need the same values, why are there multiple env vars required?
