### ISSUE TITLE
Notify local users on for internal privacy

### ISSUE THREAD

**Issue by vitovecc** [Chocobozzz/PeerTube#4359]
**Describe the current behavior**

When a video is [uploaded via API](https://docs.joinpeertube.org/api-rest-reference.html#operation/uploadLegacy) to a channel, users who are subscribed to the channel don't receive any kind of notification (web, email) even if they have all notifications enabled. However, if the same video is uploaded via GUI both web and email notifications arrive successfully. So there is no problem with my SMTP configuration or anything related to it. 

**Steps to reproduce:**

1. Users A and B, A has enabled all notifications (both web and email) and subscribes to B's channel. 
2. B [uploads a video via API](https://docs.joinpeertube.org/api-rest-reference.html#operation/uploadLegacy) to the channel A is subscribed to.
3. A doesn't receive any notifications.

**Describe the expected behavior**

I'd expect subscribed users to be notified even if a video is uploaded via API.

* PeerTube instance:
  * version: 3.3.0 (docker)
  
* Browser name, version, and platforms on which you could reproduce the bug: Firefox 91

**Comment by Chocobozzz** [comment]
Hello,

Please paste peertube server logs

**Comment by vitovecc** [comment]
Hey,

here it is:

```
peertube_1  | [example.com:443] 2021-08-30 09:39:58.893 info: 172.13.12.161 - - [30/Aug/2021:09:39:58 +0000] "GET /api/v1/video-channels/sd_transfers HTTP/1.1" 200 1047 "-" "python-requests/2.26.0"
peertube_1  | [example.com:443] 2021-08-30 09:39:59.291 info: 172.13.12.161 - - [30/Aug/2021:09:39:59 +0000] "POST /api/v1/users/token HTTP/1.1" 200 194 "-" "python-requests/2.26.0"
peertube_1  | [example.com:443] 2021-08-30 09:40:04.921 info: Video with name TEMPO 0063051-240p.mp4 and uuid ab553d2d-530f-4bb5-b19a-d1a37ba72fa2 created.
peertube_1  | [example.com:443] 2021-08-30 09:40:04.926 info: 172.13.12.161 - - [30/Aug/2021:09:40:04 +0000] "POST /api/v1/videos/upload HTTP/1.1" 200 104 "-" "python-requests/2.26.0"
peertube_1  | [example.com:443] 2021-08-30 09:40:05.078 info: Creating torrent /data/torrents/ab553d2d-530f-4bb5-b19a-d1a37ba72fa2-240.torrent.

```

**Comment by Chocobozzz** [comment]
Do you have an URL of this video so I can check its attributes?

And do you have other logs after `Creating torrent`? (you could also enable debug logs on peertube)

**Comment by vitovecc** [comment]
Unfortunately, our peertube instance is not public so I can't give you the URL.

I tried to upload it again with debug enabled and [here](https://pastebin.com/rDyrizqq) is the log.

**Comment by Chocobozzz** [comment]
Please tell me what are the values of video attributes: `state`, `privacy` and `blacklisted`

**Comment by vitovecc** [comment]
```
{ ...
 'blacklisted': False,
 'privacy': {'id': 4, 'label': 'Internal'},
 'state': {'id': 1, 'label': 'Published'},
... }
```

**Comment by Chocobozzz** [comment]
peertube only notify subscribers when the video is `public`

**Comment by vitovecc** [comment]
Yeah, you're right. When I upload via GUI the default privacy is `public`. That's the reason why I get notified. 

It'd help us a lot if you could change it. Thank you!

**Comment by Chocobozzz** [comment]
Notification for internal videos to local users is implemented in https://github.com/Chocobozzz/PeerTube/commit/56d48fc41b4628275a90e0df71b3ab519e21ba99 :tada:
