### ISSUE TITLE
do not show privacy warning if not using webtorrent

### ISSUE THREAD

**Issue by test2a** [Chocobozzz/PeerTube#4362]
**Describe the problem to be solved**
currently the privacy warning is showed on video load every time. this is legacy from when webtorrent was used and at that time the implication was maybe if someone can snoop on the webtorrent tracker, they can resolve users via their ip address. since we moved to hls by default, the data comes from server and not from other peers so this warning is moot

![Screenshot_20210828_111407](https://user-images.githubusercontent.com/39449563/131207726-0ea531e8-70dc-47db-a543-2b88d882d1ec.png)

check the screenshot. it does not look like getting data from webtorrent where ip address can leak so there is no point in this warning
**Describe the solution you would like:**
only show this warning if webtorrent is enabled and that too, if a particular video is using webtorrent. 

**Describe alternatives you have considered**

**Comment by Chocobozzz** [comment]
> the data comes from server and not from other peers so this warning is moot

HLS also uses P2P via the same tracker than bittorrent. Disable the tracker if you don't want to use P2P and display the message.

**Comment by andrew712-1** [comment]
> > the data comes from server and not from other peers so this warning is moot
> 
> HLS also uses P2P via the same tracker than bittorrent. Disable the tracker if you don't want to use P2P and display the message.

It'd be great to have this documented somewhere..
