### ISSUE TITLE
Admin Feature: Ability to block certain e-mail providers for registration

### ISSUE THREAD

**Issue by LoXan007** [Chocobozzz/PeerTube#4364]
Hi,

i've running my own peertube instance since a while and i notice that most of the spam registrations come from e-mail providers as gmail etc.
Currently i delete such accounts from time to time but that's not ideal. Sure i could deactivate user registration but i want to keep my instance open. 

So i wish a possibility to block e mail providers via the admin settings. For example i take "gmail" on the blacklist and users can't register with a gmail address. I know there is one plugin for that (i think it is named glaviit), but i want to make this directly in peertube itself and without a plugin. Apart from that the plugin is from a third party developer and it isn't updated for a year so i don't want to install it.

I would be happy if this feature could be integrated into Peertube.

**Comment by Chocobozzz** [comment]
Hello,

Please see this plugin: https://gitlab.com/grin/peertube-plugin-glavliiit
