### ISSUE TITLE
Upgrading to v3.4.0-rc1 on debian bullseye fails

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4366]
**Describe the current behavior**

When upgrading to v3.4.0-rc1 on debian bullseye, I got the following error during the upgrade script execution:

```
error /var/www/peertube/versions/peertube-v3.4.0-rc.1/node_modules/youtube-dl: Command failed.
Exit code: 1
Command: npm run check && npm run download
Arguments: 
Directory: /var/www/peertube/versions/peertube-v3.4.0-rc.1/node_modules/youtube-dl
Output:
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1630404090586-0.6479848526241185/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> youtube-dl@3.5.0 check /var/www/peertube/versions/peertube-v3.4.0-rc.1/node_modules/youtube-dl
> bin-version-check python '>=2'

Error: Couldn't find the `python` binary. Make sure it's installed and in your $PATH.
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-dl@3.5.0 check: `bin-version-check python '>=2'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the youtube-dl@3.5.0 check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I think this is because there is no more python2 on bullseye.

**Steps to reproduce:**

1. debian bullseye
2. cd /var/www/peertube/peertube-latest/scripts && sudo -H -u peertube ./upgrade.sh

**Comment by JohnXLivingston** [comment]
Installing the `python-is-python2` package solves the issue. But this is a temporary fix.

Here is the package description:
```
Description: symlinks /usr/bin/python to the DEPRECATED python2
 Starting with the Debian 11 (bullseye) and Ubuntu 20.04 LTS (focal)
 releases, all python packages use explicit python3 or python2
 interpreter and do not use unversioned /usr/bin/python at all. Some
 third-party code may still be python2 based, yet may use
 /usr/bin/python.
 .
 This is a convenience package which ships a symlink to point
 /usr/bin/python interpreter at the current default python2. It may
 improve compatibility with obsolete 3rd-party software, whilst
 breaking some modern software.
 .
 This package will be installed upon upgrades to Debian 11 (bullseye)
 and Ubuntu 20.04, if the DEPRECATED python2 was installed.
 .
 python2 is DEPRECATED and will not be provided in future Debian and
 Ubuntu releases. It is recommended to remove python2 and this package
 after ensuring that only python3 is in use.
 .
 No packages may declare dependencies on this package, or recommend
 that package.
```

**Comment by JohnXLivingston** [comment]
For people having the same issue, here are the steps to solve:
```
apt install python-is-python2;
cd /var/www/peertube && sudo -u peertube unlink ./peertube-latest && sudo -u peertube ln -s versions/peertube-v3.3.0/ peertube-latest;
```
Then run the upgrade script again.

**Comment by Alterak** [comment]
Strange, today I installed a [nightly build](https://builds.joinpeertube.org/nightly/) on a test server (Deb11) and everything was fine.

**Comment by JohnXLivingston** [comment]
I think that the process to install youtube-dl is not the same for an upgrade and a new installation.

**Comment by Alterak** [comment]
> For people having the same issue, here are the steps to solve:
> 
> ```
> apt install python-is-python2;
> cd /var/www/peertube && sudo -u peertube unlink ./peertube-latest && sudo -u peertube ln -s versions/peertube-v3.3.0/ peertube-latest;
> ```
> 
> Then run the upgrade script again.

This is how you link back to the old 3.3.0 version.

**Comment by JohnXLivingston** [comment]
> You have referenced again to the previous version 3.3.0.

I wrote: «then run the upgrade script again». I will edit my message to add the command to be more clear.

**Comment by Chocobozzz** [comment]
youtube-dl should support python 3, so I recommend to install https://packages.debian.org/bullseye/python-is-python3

Unfortunately since youtube-dl uses `env python`, admins must install this package.

**Comment by frankstrater** [comment]
I would recommend also adding this to the [dependencies guide](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/dependencies.md)

I prefer the more distro-agnostic solution as I've added to the RHEL family dependencies installation steps, but a package might be more 'fool-proof'.

```sh
sudo ln -s /usr/bin/python3 /usr/bin/python
```

**Comment by JohnXLivingston** [comment]
> youtube-dl should support python 3, so I recommend to install https://packages.debian.org/bullseye/python-is-python3
> 
> Unfortunately since youtube-dl uses `env python`, admins must install this package.

I must admit I just tried the first workaround I found, because I was in a hurry. Thanks.

**Comment by Chocobozzz** [comment]
I updated the changelog and the documentation in https://github.com/Chocobozzz/PeerTube/commit/4d557df51c2ad8a87b9789b3caccc95c9880a944
