### ISSUE TITLE
PeerTube main project is not visible on weblate

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#4368]
Hi,

Can we still contribute to propose any translation on weblate or do we have to propose them here ?

**Comment by rigelk** [comment]
Hey kimsible, what translation do you want to suggest? Chances are, a project for the language you seek already exists in https://weblate.framasoft.org/projects/peertube, which you can contribute to there.

**Comment by Alterak** [comment]
Perhaps the author was referring to the translation on your [main site](https://joinpeertube.org/), for example, the translation of documentation or the site itself

**Comment by frankstrater** [comment]
> Perhaps the author was referring to the translation on your [main site](https://joinpeertube.org/), for example, the translation of documentation or the site itself

That should be this one in Weblate:

https://weblate.framasoft.org/projects/joinpeertube/

**Comment by kimsible** [comment]
thanks you all, I didn't see the « angular » component before, now, I think I have the rights =)
