### ISSUE TITLE
Videos with inaccurate publication date

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#4372]
**Describe the current behavior**
I have a strange case of a video where the publication date vary depending on the page. The video is the same on both of the screenshots, but not the date.

![Screenshot_20210903_144126](https://user-images.githubusercontent.com/22192600/132007026-ce49c9fa-6264-4017-8fb7-a8642f984802.png)

![Screenshot_20210903_144029](https://user-images.githubusercontent.com/22192600/132007055-84b7f8f4-49e8-4a5b-bc92-fe5c089ece30.png)

**Steps to reproduce:**

1. Go to a video page
2. Go to the video's channel in a new tab

**Describe the expected behavior**
The date don't change.
**Additional information**

* PeerTube instance:
  * URL: peertube.stemy.me
  * version: 3.3.0
  * NodeJS version: 10.24.0~dfsg-1~deb10u1
  * Ffmpeg version: 7:4.1.6-1~deb10u1

* Browser name, version and platforms on which you could reproduce the bug: firefox 91.0.2

**Comment by Chocobozzz** [comment]
Hello,

It's related to the https://framagit.org/kontrollanten/peertube-plugin-sort-originally-published-at plugin

Please create the issue on their repository.
