### ISSUE TITLE
[docker] Jobs fail if SMTP can't connect

### ISSUE THREAD

**Issue by noplanman** [Chocobozzz/PeerTube#438]
**:exclamation: Note: I'm using production version with docker!**

- **PeerTube version or URL:** 1.0.0-beta.3
- **Browser name/version:** Waterfox 56.1.0 (64-bit)
- **NodeJS version:** v8.11.0

* **What is the expected behaviour?**
After uploading a video, transcoding should kick in and do its thing, regardless of any other (invalid) settings.

- **What do you see instead?**
An error message letting me know that the job has failed. Disabling the SMTP setting solves the problem and jobs complete successfully. Not sure how related the SMTP connection failing is, or if any system error leads to failure of creating the job.

- **Server log if useful (Gist/Pastebin...):**
```
[x.y.z:443] 2018-03-30 00:24:14.984 info: Creating torrent /data/torrents/ef9bd966-bdcc-4f80-885a-79a1dbcabcc4-480.torrent.
[x.y.z:443] 2018-03-30 00:24:15.106 error: Cannot insert the video with many retries. {
  "err": "TypeError: Cannot read property 'create' of undefined\n    at Promise (/app/dist/server/lib/job-queue/job-queue.js:69:18)\n    at new Promise (<anonymous>)\n    at JobQueue.createJob (/app/dist/server/lib/job-queue/job-queue.js:67:16)\n    at Object.<anonymous> (/app/dist/server/controllers/api/videos/index.js:174:49)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/dist/server/controllers/api/videos/index.js:4:58)\n    at <anonymous>"
}
[x.y.z:443] 2018-03-30 00:24:15.110 error: Error in controller. {
  "error": "TypeError: Cannot read property 'create' of undefined\n    at Promise (/app/dist/server/lib/job-queue/job-queue.js:69:18)\n    at new Promise (<anonymous>)\n    at JobQueue.createJob (/app/dist/server/lib/job-queue/job-queue.js:67:16)\n    at Object.<anonymous> (/app/dist/server/controllers/api/videos/index.js:174:49)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/dist/server/controllers/api/videos/index.js:4:58)\n    at <anonymous>"
}
[x.y.z:443] 2018-03-30 00:24:15.114 info: 1.2.3.4 - - [30/Mar/2018:00:24:15 +0000] "POST /api/v1/videos/upload HTTP/1.0" 500 - "https://x.y.z/videos/upload" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:50.0) Gecko/20100101 Firefox/50.0"

[x.y.z:443] 2018-03-30 00:24:39.799 error: Connection timeout {
  "component": "smtp-connection",
  "sid": "Cp4zP6cPQ4"
}
[x.y.z:443] 2018-03-30 00:24:39.803 error: Failed to connect to SMTP smtp.mail:465. {
  "meta": {
    "err": "Error: Connection timeout\n    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)\n    at SMTPConnection._onError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:579:20)\n    at Timeout._connectionTimeout.setTimeout (/app/node_modules/nodemailer/lib/smtp-connection/index.js:261:18)\n    at ontimeout (timers.js:482:11)\n    at tryOnTimeout (timers.js:317:5)\n    at Timer.listOnTimeout (timers.js:277:5)"
  }
}
```

**Comment by Chocobozzz** [comment]
At startup, if SMTP is configured PeerTube will test the connection. Since you have a connection timeout, the connection fails only after a while (and you are able to upload a video during this time).

**Comment by noplanman** [comment]
@Chocobozzz Thanks for your explanation, but that's not how I'm experiencing it :confused: 
If the SMTP connection times out (which I still don't understand why), jobs that require executing after the upload just fail with the message above.
Disabling the SMTP setting and restarting / reuploading works perfectly and the jobs all complete successfully.

How can I debug this more? Are there extra logs I can activate somewhere?

(On a side note, eager to see #339 implemented :innocent: )

**Comment by noplanman** [comment]
Hmm, I can successfully send a mail using a plain and simple `nodemailer` example, so there shouldn't be a problem connecting to my SMTP server.
Yet it still fails to connect (timeout) in PeerTube :disappointed: 

And the jobs fail when SMTP is enabled, so there is something that seems wrong there.

**Comment by Chocobozzz** [comment]
Fixed: https://github.com/Chocobozzz/PeerTube/commit/3d3441d6c7a5646388ab0a77acad57fdb63b9d32
