### ISSUE TITLE
Missing Language For Video: Latin

### ISSUE THREAD

**Issue by SentToDevNull** [Chocobozzz/PeerTube#4381]
**Describe the current behavior**

Unable to set video language to Latin.

**Steps to reproduce:**

1. Import any video. Try changing the language to Latin.

**Describe the expected behavior**

The language Latin should be in the drop-down menu, but it is not.

**Additional information**

* PeerTube instance:
  * version: latest

**Comment by Chocobozzz** [comment]
Done in https://github.com/Chocobozzz/PeerTube/commit/23fdb0ff38aef6c6ff7ab9580dc6c048fa30fdc8
