### ISSUE TITLE
What JS tool to use to manipulate DOM for easy development plugins

### ISSUE THREAD

**Issue by kimsible** [Chocobozzz/PeerTube#4383]
Hi,

I wanted to open a discussion about plugin development, especially client-side.

I maintain 2 plugins (upload-limits and social-sharing) that needs extreme manipulation of DOM asking playing constantly with `MutationObserver`, `getElement(s)*`, `querySelector` and `document.createElement`.

I know it's the fastest way to not ruin the CPU, but it needs some really good knowledge of vanilly / native JS, which not accessible for every developer.

Plus, I've realized that is a real pain to maintain even with the best architecture (creating test functions to isolate code as much as possible) :/.

**jQuery** is definitely not the tool to use, definitely NOT as plugins need to be as light as possible I think, in term of memory and CPU.

I thought about something like RE:DOM https://redom.js.org, which represents only 2ko in the bundle and the API looks really cool and light. It may be a solution for HTMLElement creation.

 Do you have any other solutions ?
 
Note: PeerTube `filter/hooks` may be not to be a real alternative to intensive `MutationObserver` or `querySelector` usage since we need to hook when components are fully rendered. @Chocobozzz ?

**Comment by kimsible** [comment]
I found that : https://gist.github.com/WebReflection/761052d6dae7c8207d2fcba7cdede295#dom-engines-features-comparison

uHTML (https://github.com/WebReflection/uhtml) looks similar to the render function of `jqlite`.
It works like `innerHTML` with ES templating.

**Comment by Chocobozzz** [comment]
Closing this inactive discussion. Don't hesitate to comment if you want to reopen it.
