### ISSUE TITLE
Banner size improvement 

### ISSUE THREAD

**Issue by tio-trom** [Chocobozzz/PeerTube#4386]
I think that converting the banner to such a specific resolution is not a good practice. It is good to recommend to people to upload such resolutions, but not convert the banner they upload. Simply use it as a background for the div where it is located and thread it as a cover and fit, with center alignment. Because if I do not upload an image that's the exact resolution you recommend, then my banner photo is going to get distorted. But with the solution I am proposing it will be made bigger to fit a fixed canvas. I think that's a much saner approach.

**Comment by Chocobozzz** [comment]
Hello,

We now use cover in https://github.com/Chocobozzz/PeerTube/commit/9c7cf0072ffbfff7e1d3276af9123d9c5a3a0aa6
