### ISSUE TITLE
Why is video.streamingPlaylists an array?

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4389]
> **streamingPlaylists** Array of objects (VideoStreamingPlaylists)HLS playlists/manifest files. If HLS is disabled on the server:field will be empty video files will be found in files field

https://docs.joinpeertube.org/api-rest-reference.html#operation/getVideo

Why is streamingPlaylists an array? In which cases is there more than one item in the array and how will they be prioritized upon playing?

**Comment by Chocobozzz** [comment]
Hello,

For the moment there is only 0 (if HLS is disabled) or 1 element in this array (if HLS is enabled). It's an array so we can support other playlist format in the future (like Dash).
