### ISSUE TITLE
Live Streaming broken since 3.4

### ISSUE THREAD

**Issue by normen** [Chocobozzz/PeerTube#4390]
**Describe the current behavior**
When trying to stream to a persistent live stream using OBS the stream never goes live on the web page. It used to work in previous versions. Now theres no `.m3u8` file created in the stream folder and theres only one `.ts` file which grows ever larger in size (hundreds of megabytes in `0-000000.ts`).

Edit: When stopping the streaming in OBS a `m3u8` file is created but by then the stream isn't available through the web page anymore either (for obvious reasons, it actually ended).

**Steps to reproduce:**

1. Create permanent live stream
2. Stream to server using e.g. OBS
3. See that the stream never starts and no playlist file is created 

**Describe the expected behavior**
The stream should be playable in the web browser.

**Additional information**

* PeerTube instance:
  * URL: https://tube.bitwaves.de
  * version: 3.4
  * NodeJS version: docker install from 3.4
  * Ffmpeg version: docker install from 3.4

* Browser name, version and platforms on which you could reproduce the bug:
Safari, Any - Server running in docker/Ubuntu
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
Log when starting the stream (seems unsuspicious?)
```
[tube.bitwaves.de:443] 2021-09-09 12:02:43.056 info: rtmp://127.0.0.1:1935/live/b50bbc7b-08e0-4eff-a935-b32d04ce0463 probing took 1639 ms (bitrate: 2560000, fps: 30, resolution: 1080)
[tube.bitwaves.de:443] 2021-09-09 12:02:43.058 info: Will mux/transcode live video of original resolution 1080. {
  "allResolutions": [
    1080
  ]
}
[tube.bitwaves.de:443] 2021-09-09 12:02:43.166 info: Running live muxing/transcoding for b7a4e544-d4f4-4879-b3bc-2a30a151e72e.
[tube.bitwaves.de:443] 2021-09-09 12:02:56.243 info: 2003:d7:173d:c900:35e4:65b6:4988:92a0 - - [09/Sep/2021:12:02:56 +0000] "GET /api/v1/videos/b7a4e544-d4f4-4879-b3bc-2a30a151e72e/captions HTTP/1.0" 304 - "https://tube.bitwaves.de/w/oFgXUaW64w36beg6ziiyXy" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15"
[tube.bitwaves.de:443] 2021-09-09 12:02:56.318 info: 2003:d7:173d:c900:35e4:65b6:4988:92a0 - - [09/Sep/2021:12:02:56 +0000] "GET /api/v1/videos/b7a4e544-d4f4-4879-b3bc-2a30a151e72e HTTP/1.0" 200 2796 "https://tube.bitwaves.de/w/oFgXUaW64w36beg6ziiyXy" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15"
[tube.bitwaves.de:443] 2021-09-09 12:02:56.418 info: 2003:d7:173d:c900:35e4:65b6:4988:92a0 - - [09/Sep/2021:12:02:56 +0000] "GET /api/v1/users/me/videos/32/rating HTTP/1.0" 304 - "https://tube.bitwaves.de/w/oFgXUaW64w36beg6ziiyXy" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15"
[tube.bitwaves.de:443] 2021-09-09 12:02:56.449 info: 2003:d7:173d:c900:35e4:65b6:4988:92a0 - - [09/Sep/2021:12:02:56 +0000] "GET /api/v1/videos/?start=0&count=6&sort=-createdAt HTTP/1.0" 304 - "https://tube.bitwaves.de/w/oFgXUaW64w36beg6ziiyXy" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15"
[tube.bitwaves.de:443] 2021-09-09 12:02:57.005 info: 2003:d7:173d:c900:35e4:65b6:4988:92a0 - - [09/Sep/2021:12:02:57 +0000] "GET /api/v1/users/me/video-playlists/videos-exist?videoIds=32 HTTP/1.0" 304 - "https://tube.bitwaves.de/w/oFgXUaW64w36beg6ziiyXy" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15"
[tube.bitwaves.de:443] 2021-09-09 12:04:13.589 info: Updating live video views.
```

**Comment by Chocobozzz** [comment]
Hello,

Please try to enable transcoding or set OBS output keyframe interval to 2s

**Comment by normen** [comment]
Hi, thanks for the quick reply!

When transcoding the video I get a working stream again but my server CPU can't handle that at all, even if I don't set any resolutions to be transcoded to (like I do in the main video settings as well - I don't want multi-resolution). Setting a keyframe interval of 2 seconds also results in a working stream but it taxes the streaming computer quite a bit more.

So first of all thanks for the quick-fix but maybe theres a chance it could be made working without a keyframe interval again?

Thanks for this project,
Normen

**Comment by Chocobozzz** [comment]
What are you streaming? A video? An audio file? Your desktop screen?

**Comment by highvoltage** [comment]
I have the same problem, it's easy to reproduce on https://peertube.debian.social (you'll just need to create an account on debian's gitlab instance in order to log on, or I could manually create a temporay user if you want).

From OBS it seems to work just fine, and in the peertube logs it appears to be remuxing and when I end the stream from OBS it seems to close with no error logged. Although on the PeerTube side it just says waiting for the stream to start. Setting the keyframe interval to 2 doesn't seem to make any difference in my case. Any pointers for me or info I can get for you?

**Comment by normen** [comment]
> What are you streaming? A video? An audio file? Your desktop screen?

Various things. Mostly video. Mainly a stage. Sometimes a "vlog face" and desktop.

**Comment by M-Stenzel** [comment]
Hi team,
today I created a live stream and fed it with OBS data.
I did not face ANY problems.

System
peertube 3.4.1
OBS 25.0.8
both running on Linux
no docker

**Comment by highvoltage** [comment]
Thanks for all the feedback, I suspect it might also be firewall related on the host. Will check again over the weekend and provide some more details. Thanks again.

**Comment by Chocobozzz** [comment]
Then I'm closing this issue for now. Don't hesitate to comment if you have new info

**Comment by rt4mn** [comment]
I suspect this issue might be affecting me as well, as the advice to enable transcending / use keyframes seems to have fixed the problem, but with a huge hit to performance (video constatly lags). I would much rather not have to transcode the video server side:

https://github.com/Chocobozzz/PeerTube/issues/4778
