### ISSUE TITLE
Improve search result UI

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#4395]
The Peertube search results, I think the aesthetics should be better.

Example
https://rumble.com/ or youube
![Captura de pantalla de 2021-09-10 19-11-02](https://user-images.githubusercontent.com/43164089/132926791-76e6ba06-c768-4fc8-92ef-62fb57688068.png)

**Comment by Chocobozzz** [comment]
Please fill the template and be more precise on what you would like to change and for what purpose

**Comment by AnonymousWebHacker** [comment]
**Describe the problem to be solved**


![search](https://user-images.githubusercontent.com/43164089/133465292-91fdf4aa-502d-43d8-a8b4-7c6f86bb76b6.png)

**Describe the solution you would like:**



![132926791-76e6ba06-c768-4fc8-92ef-62fb57688068](https://user-images.githubusercontent.com/43164089/133466349-7d94c921-d5bc-4093-9e44-d321a5c0df57.png)

**Comment by Chocobozzz** [comment]
Closing this inactive discussion that did not receive feedback. I agree the search results can be improved, but it would be better to provide a new mockup adapted to the PeerTube UI.
