### ISSUE TITLE
Peertube webpage hangs on button press

### ISSUE THREAD

**Issue by ctag** [Chocobozzz/PeerTube#4396]
**Describe the current behavior**
Hi,

On [my Peertube instance](https://video.berocs.com/), I can load the home page and play videos, but if I click on certain buttons (seems to be any button with a context menu or visible change on the page) the webpage will hang. On Firefox this will eventually crash the browser if left alone. On Chromium the tab will crash.

I first noticed this on Peertube 3.3.0 and upgraded to Peertube 3.4.0 hoping it would be resolved, but it persists.

Since using the Administration page to disable/remove themes and plugins to troubleshoot this issue also causes the freeze, I wanted to try managing the plugins from CLI, but have been unable to so far. Related github issue [here](https://github.com/Chocobozzz/PeerTube/issues/4391).

![image](https://user-images.githubusercontent.com/6200085/132939673-4e896080-b36c-4921-be50-ca529b2dc7fd.png)

![image](https://user-images.githubusercontent.com/6200085/132939694-7517a0ac-7c13-4681-a22a-7d216c404b03.png)

**Steps to reproduce:**

1. Visit the instance: https://video.berocs.com/
2. Click on a video.
3. Click on "Subscribe" (or a button with a context menu).
4. No menu appears, and the page stops responding. For me within 15 seconds the page crashes.

**Describe the expected behavior**

Previously (even on Peertube 3.3.0) the page did not crash.

**Additional information**

* PeerTube instance: 
  * URL: https://video.berocs.com/
  * version: 3.4.0
  * NodeJS version: node 16
  * Ffmpeg version: 4.4 (I'm aware of the [ffmpeg bug](https://github.com/Chocobozzz/PeerTube/issues/3990), but upgraded the system to try troubleshooting.)

* Browser name, version and platforms on which you could reproduce the bug:

Both Firefox 91.0.2 and Chromium 93.0.4577.63 on linux.

* Link to browser console log if relevant:

Output when running chromium from shell:

```
$ chromium --incognito

(chromium:208962): GLib-GIO-CRITICAL **: 02:04:30.163: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
[209000:209000:0911/020430.323537:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[209001:209017:0911/020437.217062:ERROR:socket_udp.cc(154)] bind() to :::0 failed: -109
[209001:209017:0911/020437.218259:ERROR:socket_udp.cc(154)] bind() to :::0 failed: -109
[209001:209017:0911/020437.219474:ERROR:socket_udp.cc(154)] bind() to :::0 failed: -109
[209001:209017:0911/020437.221241:ERROR:socket_udp.cc(154)] bind() to :::0 failed: -109
[209001:209017:0911/020437.222695:ERROR:socket_udp.cc(154)] bind() to :::0 failed: -109
[209001:209017:0911/020437.353118:ERROR:socket_udp.cc(154)] bind() to :::0 failed: -109
[209001:209017:0911/020437.354450:ERROR:socket_udp.cc(154)] bind() to :::0 failed: -109
[209001:209017:0911/020437.355801:ERROR:socket_udp.cc(154)] bind() to :::0 failed: -109
[209001:209017:0911/020437.357383:ERROR:socket_udp.cc(154)] bind() to :::0 failed: -109
[209001:209017:0911/020437.358810:ERROR:socket_udp.cc(154)] bind() to :::0 failed: -109
[209381:4:0911/020507.700587:ERROR:child_thread_impl.cc(339)] Crashing because hung
```

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

Log file looks OK to me. 

```
[video.berocs.com:443] 2021-09-11 01:55:02.464 info: 192.168.0.0 - - [11/Sep/2021:06:55:02 +0000] "GET /api/v1/videos/?start=0&count=6&sort=-createdAt HTTP/1.0" 200 7716 "https://video.berocs.com/w/j2HNYLm51p4raPmGNxxiaK" "Firefox"
[video.berocs.com:443] 2021-09-11 01:55:02.507 info: 192.168.0.0 - - [11/Sep/2021:06:55:02 +0000] "GET /api/v1/videos/19/comment-threads?start=0&count=10&sort=-createdAt HTTP/1.0" 200 49 "https://video.berocs.com/w/j2HNYLm51p4raPmGNxxiaK" "Firefox"
[video.berocs.com:443] 2021-09-11 01:55:02.515 info: 192.168.0.0 - - [11/Sep/2021:06:55:02 +0000] "GET /lazy-static/avatars/c7a4fb87-b701-45ff-9874-5986ab90fa71.jpg HTTP/1.0" 200 4028 "https://video.berocs.com/w/j2HNYLm51p4raPmGNxxiaK" "Firefox"
[video.berocs.com:443] 2021-09-11 01:55:02.619 info: 192.168.0.0 - - [11/Sep/2021:06:55:02 +0000] "GET /lazy-static/previews/92020186-db10-4e12-a996-c4017a4ed521.jpg HTTP/1.0" 200 41769 "https://video.berocs.com/" "Firefox"
[video.berocs.com:443] 2021-09-11 01:58:48.971 info: Updating live video views.
```

**Comment by ctag** [comment]
Was being caused by one of my themes or plugins. I tried updating them to no avail, and then deleted them. Problem resolved, though I'm not sure when plugin is at fault.

```
┌──────────────────────────────────────────────────┬──────────┬──────────────────────────────────────────────────┐
│ name                                             │ version  │ homepage                                         │
├──────────────────────────────────────────────────┼──────────┼──────────────────────────────────────────────────┤
│ peertube-theme-bittube-dark-mode                 │ 3.0.0    │ https://github.com/ipbc-dev/peertube-theme-bitt… │
├──────────────────────────────────────────────────┼──────────┼──────────────────────────────────────────────────┤
│ peertube-theme-dark                              │ 2.2.5    │ https://framagit.org/framasoft/peertube/officia… │
├──────────────────────────────────────────────────┼──────────┼──────────────────────────────────────────────────┤
│ peertube-plugin-slides                           │ 0.0.1    │ https://framagit.org/framasoft/peertube/peertub… │
├──────────────────────────────────────────────────┼──────────┼──────────────────────────────────────────────────┤
│ peertube-plugin-ungamify                         │ 0.0.1    │ https://framagit.org/rigelk/peertube-plugin-ung… │
└──────────────────────────────────────────────────┴──────────┴──────────────────────────────────────────────────┘

```

**Comment by lasat** [comment]
BTW: I had the same issue, after uninstall of peertube-plugin-ungamify (0.0.2) the problem was solved
