### ISSUE TITLE
auth ldap plugin has problems loading custom CA

### ISSUE THREAD

**Issue by zem** [Chocobozzz/PeerTube#4398]
**Describe the current behavior**

auth_ldap only works with TLS insecure option

**Steps to reproduce:**

1. get peertube docker/podman container
2. install auth_ldap
3. place custom ca.pem in config
4. configure ldap
5. find the following lines in the container logs: 

```
[stream.conesphere.cloud:443 peertube-plugin-auth-ldap] 2021-09-11 18:21:06.079 warn: Could not load custom CA in LDAP plugin {
  "err": {
    "stack": "TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined\n    at maybeCallback (fs.js:145:9)\n    at Object.readFile (fs.js:299:14)\n    at login (/data/plugins/node_modules/peertube-plugin-auth-ldap/main.js:209:48)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "message": "Callback must be a function. Received undefined",
    "code": "ERR_INVALID_CALLBACK"
  }
}
```

**Describe the expected behavior**

auth_ldap should be able to read and accept custom CA

**Additional information**

* PeerTube instance:
  * URL: https://stream.conesphere.cloud
  * version: 3.4.0

**Comment by Chocobozzz** [comment]
Hello,

Please use https://framagit.org/framasoft/peertube/official-plugins/-/issues for ldap plugin issues :)
