### ISSUE TITLE
Show allowed user quota of each instance on joinpeertube

### ISSUE THREAD

**Issue by Dostoi** [Chocobozzz/PeerTube#440]
I'm not sure if it's the right place to put it but I didn't know where else.

Right now we have to manually open each instance and go in the about section to find out what is the quota allowed for user on this instance. (and a lot of them don't say anything at all in the about section). 
It could be great if we could see in the list of open instance the quota they allow to their users.

**Comment by Chocobozzz** [comment]
Done
