### ISSUE TITLE
DB upgrade issue - failed to find conversion function from unknown to text

### ISSUE THREAD

**Issue by labiloute** [Chocobozzz/PeerTube#4402]
Hi Chocobozzz and all team :)

I encounter a problematic behavior during my peertube upgrade :

**Describe the current behavior**

Upgrading database from Peertube 3.1 on debian to Peertube 3.4.0 fails.

**Steps to reproduce:**

Classic upgrade

**Describe the expected behavior**

Database schema upgrade

**Additional information**

Logs show the following 

SequelizeDatabaseError: failed to find conversion function from unknown to text\n    at Query.formatError (/var/www/peertube/versions/peertube-v3.4.0/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)\n    at Query.run (/var/www/peertube/versions/peertube-v3.4.0/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
Sep 13 07:59:10 artitube peertube[5344]:     "message": "failed to find conversion function from unknown to text",
Sep 13 07:59:10 artitube peertube[5344]:     "name": "SequelizeDatabaseError",
Sep 13 07:59:10 artitube peertube[5344]:     "parent": {
Sep 13 07:59:10 artitube peertube[5344]:       "stack": "error: failed to find conversion function from unknown to text\n    at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v3.4.0/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/var/www/peertube/versions/peertube-v3.4.0/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/www/peertube/versions/peertube-v3.4.0/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v3.4.0/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (events.js:315:20)\n    at Socket.EventEmitter.emit (domain.js:483:12)\n    at addChunk (_stream_readable.js:295:12)\n    at readableAddChunk (_stream_readable.js:271:9)\n    at Socket.Readable.push (_stream_readable.js:212:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)",
Sep 13 07:59:10 artitube peertube[5344]:       "message": "failed to find conversion function from unknown to text",
Sep 13 07:59:10 artitube peertube[5344]:       "length": 118,
Sep 13 07:59:10 artitube peertube[5344]:       "name": "error",
Sep 13 07:59:10 artitube peertube[5344]:       "severity": "ERREUR",
Sep 13 07:59:10 artitube peertube[5344]:       "code": "XX000",
Sep 13 07:59:10 artitube peertube[5344]:       "file": "parse_coerce.c",
Sep 13 07:59:10 artitube peertube[5344]:       "line": "521",
Sep 13 07:59:10 artitube peertube[5344]:       "routine": "coerce_type",
Sep 13 07:59:10 artitube peertube[5344]:       "sql": "UPDATE \"videoFile\" SET \"torrentUrl\" = t.\"serverUrl\" || '/static/torrents/' || \"videoFile\".\"torrentFilename\", \"fileUrl\" = t.\"serverUrl\" || t.\"filePath\" || \"videoFile\".\"filename\" FROM (SELECT 'https://' || server.host AS \"serverUrl\", '/static/webseed/' AS \"filePath\", \"videoFile\".id FROM video INNER JOIN \"videoChannel\" ON \"videoChannel\".id = video.\"channelId\" INNER JOIN actor ON actor.id = \"videoChannel\".\"actorId\" INNER JOIN server ON server.id = actor.\"serverId\" INNER JOIN \"videoFile\" ON \"videoFile\".\"videoId\" = video.id WHERE video.remote IS TRUE) AS t WHERE t.id = \"videoFile\".\"id\" AND \"videoFile\".\"fileUrl\" IS NULL"
Sep 13 07:59:10 artitube peertube[5344]:     },
Sep 13 07:59:10 artitube peertube[5344]:     "sql": "UPDATE \"videoFile\" SET \"torrentUrl\" = t.\"serverUrl\" || '/static/torrents/' || \"videoFile\".\"torrentFilename\", \"fileUrl\" = t.\"serverUrl\" || t.\"filePath\" || \"videoFile\".\"filename\" FROM (SELECT 'https://' || server.host AS \"serverUrl\", '/static/webseed/' AS \"filePath\", \"videoFile\".id FROM video INNER JOIN \"videoChannel\" ON \"videoChannel\".id = video.\"channelId\" INNER JOIN actor ON actor.id = \"videoChannel\".\"actorId\" INNER JOIN server ON server.id = actor.\"serverId\" INNER JOIN \"videoFile\" ON \"videoFile\".\"videoId\" = video.id WHERE video.remote IS TRUE) AS t WHERE t.id = \"videoFile\".\"id\" AND \"videoFile\".\"fileUrl\" IS NULL"

Thanks for all great work !

**Comment by rigelk** [comment]
What debian and postgresql version are you using?

**Comment by labiloute** [comment]
Hi @rigelk 
Thanks for reply.
Debian is now Bullseye, but simiar result has been observed before upgrade (originaly was in stretch)
PG version is 13.3 but similar result observed with version embedeed in stretch and buster.

**Comment by Chocobozzz** [comment]
Hi,

Are you sure you're using pg 13.3 for the peertube database? Because it seems to be the same issue than https://framacolibri.org/t/update-to-3-1-0-failed-to-find-conversion-function-from-unknown-to-text/11481/9

Try to `psql` inside your peertube database and run `SELECT version();`

**Comment by labiloute** [comment]
Hi @Chocobozzz


My bad, I am running "PostgreSQL 9.6.23".

Is there a way to workaround this issue ?

Thanks.

**Comment by SimplyCorbett** [comment]
> 
> Hi @Chocobozzz My bad, I am running "PostgreSQL 9.6.23". Is there a way to workaround this issue ? Thanks.

I'd recommend backing up your database and upgrading to 13.3. 9.6.23 is end of life and not supported.

**Comment by labiloute** [comment]
Worked like a charm.
Thanks to all contributors :)
