### ISSUE TITLE
Player progress bar extends beyond control window on stopped livestream

### ISSUE THREAD

**Issue by UnlimitedCookies** [Chocobozzz/PeerTube#4407]
**Describe the current behavior**
![image](https://user-images.githubusercontent.com/49200216/133338575-fe9d3f4a-3cca-459f-a9be-d989c008d539.png)

**Steps to reproduce:**

Hard to reproduce. I think it was caused due to this error: `error: Too much data in client socket stream (ffmpeg is too slow to transcode the video). Stopping session of video `

Even though it's hard to reproduce, I think this might be a logical bug because why would it be able to extend further.

**Describe the expected behavior**
Player bar should not extend beyond intended window.
**Additional information**

* PeerTube instance:
  * version: latest

* Browser name, version and platforms on which you could reproduce the bug: Firefox 92.0

**Comment by Chocobozzz** [comment]
Hi,

Is it still an issue? I can't reproduce anymore
