### ISSUE TITLE
Description of privacy settings for an video always shows, that only I can see that video. 

### ISSUE THREAD

**Issue by zem** [Chocobozzz/PeerTube#4413]
When you upload a Video, you select privacy settings on the left bottom of the dialog, it shows the following options:

- Public (Only I can see this Video)
- Unlisted (Only I can see this Video)
- Private (Only I can see this Video)
- Internal (Only I can see this Video)

Displaying the right description for the Privacy settings will help users to understand what those settings are for.

**Comment by SimplyCorbett** [comment]
This is fixed in 3.4.0.
