### ISSUE TITLE
Video counts of channel is wrong

### ISSUE THREAD

**Issue by jcn50** [Chocobozzz/PeerTube#4416]
**Describe the current behavior**

The number of videos on the channel is wrong (too low) of what it is in reality.

**Steps to reproduce:**

1. upload a video without extension (remove the ".mp4")
2. upload another video
3. counter stops

**Comment by SimplyCorbett** [comment]
Why are you removing the extension from the video?

Does it start counting again when you upload another video with the proper extension?

What version of peertube is this happening on? Please fill out the bug report properly.

**Comment by jcn50** [comment]
Sorry for not filing up the template~~

> Why are you removing the extension from the video?

I am bulk uploading~ and some files did not have an extension (I didn't think it was important, but then I just saw the errors in the Journal while filing this bug report).
 
> Does it start counting again when you upload another video with the proper extension?

No 😢 

> What version of peertube is this happening on? Please fill out the bug report properly.

3.3.0

**Comment by jcn50** [comment]
Can you delete this bug report?... I have noticed another problem~~ it's coming from my side.
