### ISSUE TITLE
Prevent video visibility setting bypass by guessing the URL of a file (local or object storage)

### ISSUE THREAD

**Issue by johanfleury** [Chocobozzz/PeerTube#4417]
So, I’ve been thinking about using an S3 compatible storage to store videos on my instance, and while reading the doc I figured this part might be missing some warnings:

> #### Cache server
>
> To reduce object storage cost, we strongly recommend to setup a cache server (CDN/external proxy). Set your mirror/CDN URL in object_storage.{streaming_playlists,videos}.base_url and PeerTube will replace the object storage host by this base URL on the fly (so you can easily change the base_url configuration).

My understanding is that by setting up such a cache server, an administrators basically makes their bucket public and the only thing “protecting” the video files is not knowing their name. If one knows the name a video, one could just download it from the cache server, regardless of the “visibility” set in PeerTube.

Let’s say I’m running a PeerTube instance at `https://peertube.example/` and a cache server at `https://v.peertube.example/`. If I upload a video for which I set visibility to private, but unfortunately give the URL to someone, that person would not be able to watch the video through PeerTube, but could probably guess the name of the video file and go to `https://v.peertube.example/videos/<name>.mp4` to download the video, effectively bypassing PeerTube’s ACLs.

So the question is, how easy is it to guess a video file name from the video URL?

Regardless of how easy it is, I would recommend putting a warning in the docs to let people understand that setting up a cache proxy in front of a bucket makes the bucket public and the videos accessible for anyone who knows their file name.

---

Edit:

I figured after posting that, that I didn’t know how PeerTube works with S3: one can’t use a private bucket as PeerTube passes the bucket’s URL to the client (even without cache proxy).

The issue is more general and not only related to cache proxies. When hosting on remote storage, one just needs to guess the URL of a file in the storage bucket to bypass PeerTube visibility settings.

**Comment by SimplyCorbett** [comment]
You can already directly download videos - even internal/private videos - by knowing the URL.

Example:

https://vidrot.com/download/streaming-playlists/hls/videos/c5c64stuffhere1-853e-9701ac948218-720-fragmented.mp4?access_token=c19cstuffhere858827fa20662da89ee508213

The access token changes on login/logout but until that happens anyone could download the video if you gave out the URL.

**Comment by johanfleury** [comment]
Well, I guess that’s also an issue: why would you pass credentials as clear text GET parameters?

It’s slightly less worse with local storage tho, at least one needs to know a valid `access_token`. In the remote storage case, one just has to know the file name and can then easily guess the full URL.

But my question/remark stays: if it’s easy for one to guess the file name from a video, hosting on remote storage makes your video public by default.

**Comment by SimplyCorbett** [comment]
I haven't used S3 on peertube. However assuming the video name is the same as the one I posted above and it's not shortened it's going to take a very long time for a web scraper to guess the URL.

Ideally you would have a reverse proxy/cache server setup between the client and S3 anyway so you can rate limit requests.

Such as here:

https://github.com/Chocobozzz/PeerTube/commit/26cabf28921158a6bd26aeccafccb08e50a517fb

**Comment by johanfleury** [comment]
@Chocobozzz I’m gonna close this, I think it’s fixed by #4861.
