### ISSUE TITLE
Allow to sort instance on joinpeertube by follow/followed/quota

### ISSUE THREAD

**Issue by Dostoi** [Chocobozzz/PeerTube#442]
It could be nice to allow to sort instance on joinpeertube by their number of follower or following or quota. Right now they're not a lot of instance but it can become hard to find one if we don't allow that at some point.
Maybe putting each in a different column and allowing sorting ?

**Comment by gegeweb** [comment]
It's already possible here : https://instances.joinpeertube.org/instances

**Comment by Dostoi** [comment]
The page isn't showing the quota and it's not easily accessible for newcomers (I don't see any link to this page on the main joinpeertube.org page). A solution could be to add the quota to this page too and add a link to it on joinpeertube.org and stating that you can found a list with more data there.

**Comment by Chocobozzz** [comment]
Please report your issues of https://joinpeertube.org on https://framagit.org/framasoft/peertube/joinpeertube/issues

FYI we added a link to https://instances.joinpeertube.org in https://joinpeertube.org :)

**Comment by Dostoi** [comment]
I didn't know about this git. No problem if I have anything else to suggest :)
Thanks for everything !
