### ISSUE TITLE
Blank page on fresh install with ENOENT no index.html & nothing in /app/client/dist in docker

### ISSUE THREAD

**Issue by souldessin** [Chocobozzz/PeerTube#4427]
I’m trying to get a fresh install going with Docker Compose and I have tried the development branch as well as multiple older branches. No matter what, I keep getting the error below.

```bash
peertube_1  | [archive.newcovenantchurch.live:443] 2021-09-17 22:01:48.011 error: Cannot generate HTML page. ENOENT: no such file or directory, open '/app/client/dist/en-US/index.html' {
peertube_1  |   "errno": -2,
peertube_1  |   "code": "ENOENT",
peertube_1  |   "syscall": "open",
peertube_1  |   "path": "/app/client/dist/en-US/index.html",
peertube_1  |   "stack": "Error: ENOENT: no such file or directory, open '/app/client/dist/en-US/index.html'"
peertube_1  | }
```

Further investigation shows that /app/client/dist is completely empty.

I had a working instance on another server and I just used the same configs as that one, only changing the address to a subdomain and the port of the reverse proxy.

I’m just stumped and didn’t think that it needed to be a bug report, yet. Any help is appreciated.

I've tried recreating the containers too, but nothing changes the result.

* PeerTube instance: production-buster
  * version: 3.4

**Comment by klodner** [comment]
I have the same error after
```
git pull
yarn install --pure-lockfile
npm run build
```

NodeJS 16.11.1

**Comment by klodner** [comment]
Oh it was missing `npm install -g concurrently`

But now build throws error 

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/SSD/docker.local/peertube/PeerTube/client/node_modules/.bin/ng'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {

```
