### ISSUE TITLE
Suggestion to add encoding 144p

### ISSUE THREAD

**Issue by kirill2400** [Chocobozzz/PeerTube#4428]
YouTube has quality 144p. On the "Slow 3G" throttling profile in Web Dev Tools (Ctrl+Shift+C), the video is played without friezes. In PeerTube minimum 240p, and as in YouTube, it lags on "Slow 3G"

**Describe the problem to be solved**
PeerTube hasn't 144p quality encoding for slow 3g internet

**Describe the solution you would like:**
Add 144p quality encoding in VOD tab in admin settings, also encode old video that not have 144p quality

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/4492

**Comment by kirill2400** [comment]
@Chocobozzz
There is youtube bitrates
First test video from youtube
![image](https://user-images.githubusercontent.com/30482699/140507479-812abd0b-17fb-4c79-8464-743390faf9bc.png)
Second
![image](https://user-images.githubusercontent.com/30482699/140507567-66c2aa25-51d9-4b43-bc7f-91380a0cf955.png)
One more
![image](https://user-images.githubusercontent.com/30482699/140507641-b828e8eb-14f4-4748-9e2f-d7bf4fc6b2ea.png)

**Comment by kirill2400** [comment]
@Chocobozzz How Am I encode old uploaded videos to 144p too?

**Comment by Chocobozzz** [comment]
>  How Am I encode old uploaded videos to 144p too?

You can try https://docs.joinpeertube.org/maintain-tools?id=create-transcoding-jobjs

**Comment by kirill2400** [comment]
> > How Am I encode old uploaded videos to 144p too?
> 
> You can try https://docs.joinpeertube.org/maintain-tools?id=create-transcoding-jobjs

What if I have 500+ videos?

**Comment by kirill2400** [comment]
Okey, I am do a for loop in directory of videos in bash script. But 144p on low 3g profile work not fine, in youtube video don't freeze, but peertube freeze sometimes for loading video
