### ISSUE TITLE
auto-block message appears with globally disabled auto-block

### ISSUE THREAD

**Issue by verymilan** [Chocobozzz/PeerTube#4433]
Hi, after the recent update, users message me because they think that i review each of their videos before publishing, but this (currently) is not the case. Yet the banner pops up when they want to upload a video... .

**Comment by Alterak** [comment]
They also write to me that before publishing a video, it must be approved by the moderators-) I am sure that this is a bug in the current release 3.4.0.

**Comment by scanlime** [comment]
see bug #4418

**Comment by verymilan** [comment]
ah snap, didn't search for the correct keywords it appears, sorry
