### ISSUE TITLE
Hardware encoding (transcoding-profile-debug)

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#4435]
**Describe the current behavior**
h264_nvenc does not work with the plugin.

**Steps to reproduce:**

1. Enable plugin
2. Run the equivalent of:
ffmpeg -i test.webm -preset slow -c:v h264_nvenc -profile:v high -pixel_format nv12 -bf:v 2 -rc vbr_hq test.mp4

or

ffmpeg -i test.webm -c:v h264_nvenc test.mp4

3. Set this up in the plugin. Even with everything cleared h264_nvenc does not work.

**Describe the expected behavior**
Works as intended.

  * Ffmpeg version: 4.3.2

**Comment by Chocobozzz** [comment]
> Can you provide me with the full command peertube uses for ffmpeg when using the plugin so I can do some tests?

You can see it in debug logs.

Closing until we get the error log.

**Comment by SimplyCorbett** [comment]
For anyone else having this issue: You must specify bframes in peertube or it errors out (this is not required when running ffmpeg manually).

**Comment by snakeeater4526** [comment]
> For anyone else having this issue: You must specify bframes in peertube or it errors out (this is not required when running ffmpeg manually).

i'm trying to hardware encode with vaapi, i'm stuck with a input/output error in peertube. ( ffmpeg is working outside of that)

can you explain/show me how did you specify bframes in peertube?

**Comment by SimplyCorbett** [comment]
My issue is related to nvidia hardware encoding. I don't believe this is an issue with other encoders, but could be wrong.
