### ISSUE TITLE
Live stream is getting interrupted 

### ISSUE THREAD

**Issue by prophpgeek** [Chocobozzz/PeerTube#4438]
**Current behavior**
When we are publishing a live stream to PeerTube from restream, it (randomly) gets disconnected and there are no logs that we can see/find to troubleshoot this error. Would really appreciate any help/ideas to fix this. This is a very random behavior but we need it working flawlessly. 

Thanks,

**Comment by Alterak** [comment]
Most likely you have transcoding enabled, which is why it breaks off-). It also breaks off if I turn on transcoding, although the processor is powerful.

**Comment by Chocobozzz** [comment]
ping @prophpgeek

**Comment by prophpgeek** [comment]
We were getting this message from another service called restream.io. I
dont have any other information than this. Here are some videos/images for
your reference.
https://www.dropbox.com/sh/4dkvmbb61bgrkn6/AABbBMIUNL9PbY69Ljc9_8rka?dl=0

If you'd like some specific details, let me know I will try and fetch them.
Thanks,

**Comment by Chocobozzz** [comment]
Thanks, could you try to reproduce this connection issue and paste peertube server logs? To see why the stream is cut between peertube and restream.io

**Comment by AlthaTechnology** [comment]
@Chocobozzz Here is a log entry from today at the time of the broken stream from Peertube:

error[8/7/2024, 7:21:47 AM] Client log: HLS.js error: mediaError - fatal: true - manifestIncompatibleCodecsError
{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.182 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
  "meta": "{\"currentTime\":0,\"data\":{\"type\":\"mediaError\",\"details\":\"manifestIncompatibleCodecsError\",\"fatal\":true,\"url\":\"https://coachdavelive.tv/static/streaming-playlists/hls/01adebcf-850a-4769-b324-e9527bc6ffd0/932b54ea-375f-436c-b46e-29b3265dd4d0-master.m3u8\",\"error\":{},\"reason\":\"no level with compatible codecs found in manifest\"}}",
  "url": "https://coachdavelive.tv/w/1d2BJdX5XUgKyn2nkW4rrJ?start=0s"
}
warn[8/7/2024, 7:22:12 AM] Client log: HLS.js error: mediaError - fatal: false - bufferStalledError
{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0",
  "url": "https://coachdavelive.tv/w/3DE7AWrRreKWX27eG8AN9x"
}
error[8/7/2024, 7:22:22 AM] Client log: HLS.js error: mediaError - fatal: true - manifestIncompatibleCodecsError
{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.182 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
  "meta": "{\"currentTime\":0,\"data\":{\"type\":\"mediaError\",\"details\":\"manifestIncompatibleCodecsError\",\"fatal\":true,\"url\":\"https://coachdavelive.tv/static/streaming-playlists/hls/31f8685a-c416-4699-a38d-becf4ffa91d2/df896e9b-1c73-4d19-9347-5f2583d12eef-master.m3u8\",\"error\":{},\"reason\":\"no level with compatible codecs found in manifest\"}}",
  "url": "https://coachdavelive.tv/w/7aTJwCUJUTFX1XWPKonmYb?start=0s"
}
warn[8/7/2024, 7:22:36 AM] Client log: HLS.js error: mediaError - fatal: false - bufferStalledError
{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0",
  "url": "https://coachdavelive.tv/w/3DE7AWrRreKWX27eG8AN9x"
}
warn[8/7/2024, 7:22:39 AM] Client log: HLS.js error: mediaError - fatal: false - bufferNudgeOnStall
{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0",
  "url": "https://coachdavelive.tv/w/3DE7AWrRreKWX27eG8AN9x"
}
warn[8/7/2024, 7:23:04 AM] Client log: HLS.js error: mediaError - fatal: false - bufferStalledError
{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0",
  "url": "https://coachdavelive.tv/w/3DE7AWrRreKWX27eG8AN9x"
}
error[8/7/2024, 7:23:13 AM] uncaughtException: UNKNOWN: unknown error, watch '/data/streaming-playlists/hls/15744909-16ea-46f3-b068-7ac8977cfb67/.nfs000000000013b52d000174a4' Error: UNKNOWN: unknown error, watch '/data/streaming-playlists/hls/15744909-16ea-46f3-b068-7ac8977cfb67/.nfs000000000013b52d000174a4' at FSWatcher.<computed> (node:internal/fs/watchers:247:19) at Object.watch (node:fs:2418:34) at createFsWatchInstance (/app/node_modules/chokidar/lib/nodefs-handler.js:119:15) at setFsWatchListener (/app/node_modules/chokidar/lib/nodefs-handler.js:166:15) at NodeFsHandler._watchWithNodeFs (/app/node_modules/chokidar/lib/nodefs-handler.js:331:14) at NodeFsHandler._handleFile (/app/node_modules/chokidar/lib/nodefs-handler.js:395:23) at NodeFsHandler._addToNodeFs (/app/node_modules/chokidar/lib/nodefs-handler.js:637:21)
{
  "error": {
    "stack": "Error: UNKNOWN: unknown error, watch '/data/streaming-playlists/hls/15744909-16ea-46f3-b068-7ac8977cfb67/.nfs000000000013b52d000174a4'\n    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)\n    at Object.watch (node:fs:2418:34)\n    at createFsWatchInstance (/app/node_modules/chokidar/lib/nodefs-handler.js:119:15)\n    at setFsWatchListener (/app/node_modules/chokidar/lib/nodefs-handler.js:166:15)\n    at NodeFsHandler._watchWithNodeFs (/app/node_modules/chokidar/lib/nodefs-handler.js:331:14)\n    at NodeFsHandler._handleFile (/app/node_modules/chokidar/lib/nodefs-handler.js:395:23)\n    at NodeFsHandler._addToNodeFs (/app/node_modules/chokidar/lib/nodefs-handler.js:637:21)",
    "message": "UNKNOWN: unknown error, watch '/data/streaming-playlists/hls/15744909-16ea-46f3-b068-7ac8977cfb67/.nfs000000000013b52d000174a4'",
    "errno": -116,
    "syscall": "watch",
    "code": "UNKNOWN",
    "path": "/data/streaming-playlists/hls/15744909-16ea-46f3-b068-7ac8977cfb67/.nfs000000000013b52d000174a4",
    "filename": "/data/streaming-playlists/hls/15744909-16ea-46f3-b068-7ac8977cfb67/.nfs000000000013b52d000174a4"
  },
  "stack": "Error: UNKNOWN: unknown error, watch '/data/streaming-playlists/hls/15744909-16ea-46f3-b068-7ac8977cfb67/.nfs000000000013b52d000174a4'\n    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)\n    at Object.watch (node:fs:2418:34)\n    at createFsWatchInstance (/app/node_modules/chokidar/lib/nodefs-handler.js:119:15)\n    at setFsWatchListener (/app/node_modules/chokidar/lib/nodefs-handler.js:166:15)\n    at NodeFsHandler._watchWithNodeFs (/app/node_modules/chokidar/lib/nodefs-handler.js:331:14)\n    at NodeFsHandler._handleFile (/app/node_modules/chokidar/lib/nodefs-handler.js:395:23)\n    at NodeFsHandler._addToNodeFs (/app/node_modules/chokidar/lib/nodefs-handler.js:637:21)",
  "exception": true,
  "date": "Wed Aug 07 2024 11:23:13 GMT+0000 (Coordinated Universal Time)",
  "process": {
    "pid": 1,
    "uid": 999,
    "gid": 999,
    "cwd": "/app",
    "execPath": "/usr/local/bin/node",
    "version": "v18.20.4",
    "argv": [
      "/usr/local/bin/node",
      "/app/dist/server"
    ],
    "memoryUsage": {
      "rss": 434954240,
      "heapTotal": 180961280,
      "heapUsed": 133219392,
      "external": 135342341,
      "arrayBuffers": 123635972
    }
  },
  "os": {
    "loadavg": [
      1.51,
      3.43,
      3.4
    ],
    "uptime": 704066.32
  },
  "trace": [
    {
      "column": 19,
      "file": "node:internal/fs/watchers",
      "function": "FSWatcher.<computed>",
      "line": 247,
      "method": "<computed>",
      "native": false
    },
    {
      "column": 34,
      "file": "node:fs",
      "function": "Object.watch",
      "line": 2418,
      "method": "watch",
      "native": false
    },
    {
      "column": 15,
      "file": "/app/node_modules/chokidar/lib/nodefs-handler.js",
      "function": "createFsWatchInstance",
      "line": 119,
      "method": null,
      "native": false
    },
    {
      "column": 15,
      "file": "/app/node_modules/chokidar/lib/nodefs-handler.js",
      "function": "setFsWatchListener",
      "line": 166,
      "method": null,
      "native": false
    },
    {
      "column": 14,
      "file": "/app/node_modules/chokidar/lib/nodefs-handler.js",
      "function": "NodeFsHandler._watchWithNodeFs",
      "line": 331,
      "method": "_watchWithNodeFs",
      "native": false
    },
    {
      "column": 23,
      "file": "/app/node_modules/chokidar/lib/nodefs-handler.js",
      "function": "NodeFsHandler._handleFile",
      "line": 395,
      "method": "_handleFile",
      "native": false
    },
    {
      "column": 21,
      "file": "/app/node_modules/chokidar/lib/nodefs-handler.js",
      "function": "NodeFsHandler._addToNodeFs",
      "line": 637,
      "method": "_addToNodeFs",
      "native": false
    }
  ]
}

**Comment by Chocobozzz** [comment]
@AlthaTechnology Please don't use NFS for PeerTube storage, especially for `/data/streaming-playlists/hls` directory. You can use object storage instead: https://docs.joinpeertube.org/maintain/remote-storage

**Comment by AlthaTechnology** [comment]
Hmm, ok, will check into this. Thanks.
