### ISSUE TITLE
Torrent: set proper name in the .torrent file

### ISSUE THREAD

**Issue by baby-gnu** [Chocobozzz/PeerTube#444]
Hello.

Actually the `.torrent` attribute `name` is not the title of the video.

For example:

* open https://framatube.org/videos/watch/0900bd2e-7306-4c39-b48b-2d0cd611742e
* download the `.torrent`
* open it in a torrent client

The downloaded file is called `0900bd2e-7306-4c39-b48b-2d0cd611742e.mp4` instead of `PeerTube : préparer l'alternative à Youtube - HS - Monsieur Bidouille.mp4`.

Regards.

**Comment by Clarin98** [comment]
I think this is crucial if we want to spread the videos through search engines and dht searching... :)

**Comment by Chocobozzz** [comment]
Should be fixed for future torrents :) https://github.com/Chocobozzz/PeerTube/commit/81e504b34e71e91633442c8021e05f9cd52a49c6
