### ISSUE TITLE
Preview/thumbnail not updated in video list

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4442]
**Describe the current behavior**
We've updated a video preview/thumbnail. When visiting the single video (watch mode) the new image is shown (both preview and tn URL from the API leads to the new image). But when visiting the video list (front page) the old image is shown since the old preview/tn URL:s are returned from the API.

**Steps to reproduce:**

1. Publish HLS video.
2. Change the preview image.
3. Go to front page.

**Describe the expected behavior**
The same image URL:s should be return by all API endpoints.

* PeerTube instance:
  * version: 3.4
  * NodeJS version: 12.22.6
  * Ffmpeg version: 4.2.4-1ubuntu0.1

**Comment by Chocobozzz** [comment]
Hello,

Is the old preview/thumbnail still displayed in the front page? Could it be a cache issue with your CDN/reverse proxy?

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/a2a81f5a7fe902245d9273530bbd65f522b2edfa
