### ISSUE TITLE
instance unresponsive after upgrading to 3.4.0. MaxListenersExceededWarning

### ISSUE THREAD

**Issue by pprw** [Chocobozzz/PeerTube#4444]
I upgraded peertube from 3.2.1 to 3.4.0 using the manual method.

When restart peertube, I have this message:

`(node:26745) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 12 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit`

I can access the instance but it is now unresponsive. Both firefox and chromium warn me the page is unresponsive. 

I reproduced configuration changes for 

- nginx (no changes except increasingmax image/caption/torrent upload size to 4MB)

- systemd (removed two lines)

```
13,14d12
< StandardOutput=syslog
< StandardError=syslog

```

**Comment by pprw** [comment]
Page is unresponsive only when logged.

**Comment by AnonymousWebHacker** [comment]
> (node:26745) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 12 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit

It is possible nodejs error, what version are you using?

**Comment by pprw** [comment]
I am using:

`$ node -v
v12.22.6
`

I have another instance with run v12.22.2 and works fine.

**Comment by pprw** [comment]
I will try to upgrade to v14.

**Comment by pprw** [comment]
I am now running nodejs v14.18.0 and I launched:

`cd /var/www/peertube/versions/peertube-v3.4.0 &&     sudo -H -u peertube yarn install --production --pure-lockfile`

The problem is still there.

**Comment by pprw** [comment]
I also tried to reinstall nodejs modules with:
```sudo -H -u peertube rm -rf node_modules client/node_modules && sudo -H -u peertube yarn install --pure-lockfile```

no changes

**Comment by pprw** [comment]
I remove every plugins and themes and the bug is gone!

I had installed :

- peertube-theme-notalive-classic
- peertube-plugin-ungamify-plus
- peertube-theme-dark
- peertube-plugin-chapters
- peertube-plugin-simplelogo
- peertube-theme-bittube-dark-mode
- peertube-plugin-simplelogo
- peertube-theme-bittube-light-mode
- peertube-plugin-ungamify
- peertube-theme-notalive-classic
- notalive-classic

**Comment by AnonymousWebHacker** [comment]
@pprw 
Sure,  when you do an installation, you have to delete the modules folder
