### ISSUE TITLE
[Translations] Incorrect translation string (german)

### ISSUE THREAD

**Issue by Mastercuber** [Chocobozzz/PeerTube#4445]
**Describe the current behavior**

Under About -> about this instance (right side) -> Search (last info)
the german translation of the info is incorrect. 
english: "Users can resolve distant content" (1)
german: "Nutzer können entfernten Inhalt lösen" (2)

**Steps to reproduce:**

1. Go to any instance
2. Change the language to german
3. copy the string (2) to an translation tool and see the result -> "Users can solve removed content"

**Describe the expected behavior**
Instead of describing expected behavior, I will suggest correct translations here (german is my mother tongue). If some other germans read this, please also suggest some translations or vote for one:

(1) "Nutzer können Inhalte von anderen Instanzen suchen" "Users can search content from other instances"
(2) "Es ist möglich Inhalte von entfernten Instanzen zu suchen" "It is possible to search content from remote instances"
(3) "Inhalte von förderierten Instanzen können von dieser Instanz aus gesucht werden" "Contents of federated instances can be searched from this instance"
(4) "Inhalte von abonnierten Instanzen können gesucht werden" "Contents of subscribed instances can be searched"

**Additional information**
If (4) is correct (contents of, by the admin, SUBSCRIBED instances can be searched [not also content of channels and accounts subscribed by some user]), then I would vote for (4).
Because the "subscribed" gives a hint what content can actually be searched.

Otherwise I would vote for (1).

* PeerTube instance:
  * URL: any instance
  * version: 3.4.0

**Comment by rigelk** [comment]
hi @Mastercuber,

Issues with a translation in particular are better handled directly at https://weblate.framasoft.org/projects/peertube/, see https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/translation.md
