### ISSUE TITLE
Stream the original source in addition to the transcoded (for lives)

### ISSUE THREAD

**Issue by raphgilles** [Chocobozzz/PeerTube#4453]
Hello,

I think it would be nice to allow the user to watch the original source in lives. As we can do on Twitch.
It would allow those who have a good connection to have a better user experience.

What do you think about that ?

**Comment by Chocobozzz** [comment]
Hello,

How could we ensure the stream can be correctly muxed in the player?

**Comment by Chocobozzz** [comment]
Unfortunately I think we don't, so it's difficult to provide an unreliable source to end users.
