### ISSUE TITLE
Re-generating Video Previews

### ISSUE THREAD

**Issue by Flagelmann** [Chocobozzz/PeerTube#4457]
Hello all,

I have an "issue" (I wish it is possible to fix in a future release): I was doing some tests on a local instance of Peertube and I deleted the conten of the "previews" folder in peertube (actually after deleting the content I realized that it was not related to thumbnails....).

Now, thumbnails have been re-generated using regenerate-thumbnails.js, so no issues here.

But....is there any way to **regenerate** also **video previews** (all missing right now) for all videos already in Peertube?

I have checked the documentation and nothing there. Is it possible to add also this possibility?

Thanks a lot (and really great software)!

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/1322
