### ISSUE TITLE
Migrate videos to native object storage

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4467]
If you've previously used s3fs-fuse and are migrating to PeerTubes object storage you still need to use s3fs-fuse to be able to read the previous videos. That means that newly uploaded file will be double synced, first via s3fs-fuse and then moved by PeerTube to the object storage. I first thought that we could just change the streaming playlist path in the PeerTube config, but that will break old videos. Are there any thought out plan here?

I'd propose that files uploaded with s3fs-fuse will be uploaded to the PeerTube tmp folder instead.

PS. I've read the docs about how to migrate and couldn't find any help in this case. https://docs.joinpeertube.org/admin-remote-storage?id=object-storage-migration

**Comment by Chocobozzz** [comment]
Hello,

I think PeerTube instances should not use s3fs-fuse anymore, especially if they use built-in s3. Instead, I would like to create a script that can migrate videos from disk to s3.

**Comment by kontrollanten** [comment]
That's true, but wouldn't it be more logic to store the video files in the tmp folder when using object storage?

**Comment by Chocobozzz** [comment]
> but wouldn't it be more logic to store the video files in the tmp folder when using object storage?

Not in the current peertube architecture. We decided that s3 storage was an additional step in peertube, the first one is to store the file on disk. If the s3 step fails, the video is not deleted/lost (which could be very frustrating for the uploader). It's the reason why we decide to store the file in the classic directories first, and not in the tmp folder. This also has the advantage to test/play/manage the video before it's sent on s3.
