### ISSUE TITLE
Cannot access to remote resource

### ISSUE THREAD

**Issue by vachan-maker** [Chocobozzz/PeerTube#4473]
**Describe the current behavior**

**Steps to reproduce:**

1. Go to https://diode.zone/w/vpDJvRmRpsLnwAZuuvZVnf
2.  Remote comment on the video from an account on another instance (Eg: peertube.linuxrocks.onlin or tilvids.com)
3. Error is displayed

**Describe the expected behavior**
Allow remote comment.
**Additional information**
My main account is on peertube.linuxrocks.online but I cannot comment on the above mentioned video using this account as the error is displayed.

* PeerTube instance:
  * URL: https://diode.zone/w/vpDJvRmRpsLnwAZuuvZVnf
  * version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox 93 Desktop
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
What is the error?

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/dedcd583b2461895f816c3dd67d56f05d3274f6b
