### ISSUE TITLE
Inject video title/description in HTML

### ISSUE THREAD

**Issue by ReK2Fernandez** [Chocobozzz/PeerTube#449]
When pasting the video on most places works.. but in others it does not show(the video name).. only shows as "PeerTube"  will look when I have time why.. but just for the heads up I put it here in  case this is happening to other people and they just think is their fault or nobody has notice.

**Comment by rigelk** [comment]
@ReK2Fernandez please describe properly the issue, as right now it's too vague to figure out.

**Comment by rigelk** [comment]
Thanks @wirew0rm - that's enough to investigate indeed

**Comment by c-prompt** [comment]
Not the cleanest but if you:

- comment out lines 29 - 30 in /server/lib/client-html.ts

```
    html = ClientHtml.addTitleTag(html)
    html = ClientHtml.addDescriptionTag(html)
```

- replace line 178 in /server/lib/client-html.ts with:

```
	const titleTag = '<title>' + videoNameEscaped + '</title>';
	const descriptionTag = `<meta name="description" content="${videoDescriptionEscaped}" />`;
	return htmlStringPage.replace(CUSTOM_HTML_TAG_COMMENTS.OPENGRAPH_AND_OEMBED, tagsString).replace(CUSTOM_HTML_TAG_COMMENTS.TITLE, titleTag).replace(CUSTOM_HTML_TAG_COMMENTS.DESCRIPTION, descriptionTag);
```

...that should change the title and description to what they should be.

**Comment by Chocobozzz** [comment]
I fixed it in https://github.com/Chocobozzz/PeerTube/commit/9aac44236c84f17b14ce35e358a87389766e2743

**Comment by ReK2Fernandez** [comment]
thanks! @Chocobozzz
