### ISSUE TITLE
Possibility to pause job queue

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4499]
**Describe the problem to be solved**
We've a setup where Redis runs on a separate server, to be able to create/destroy the PeerTube server on demand. An issue we have is when jobs are running during deployment of a new server (and the server running the job goes down before finished). I know this setup isn't supported by PeerTube, but the solution may be helpful in other cases as well.

**Describe the solution you would like:**
Be able to pause the job queue by using bull's `pause`/`resume` API.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/419b520ca4434d17f3505013174e195c3a316716
