### ISSUE TITLE
Improve discoverability of followed instances

### ISSUE THREAD

**Issue by pmiossec** [Chocobozzz/PeerTube#450]
Feature request / idea of improvement:

* Being able to see somewhere the list of the instances followed by the current instance I'm on and propose links to navigate toward this instance
Example: `framatube.org` follow `peertube.datagueule.tv` but there is nowhere to see it and go to it easily

* From a video, display a link to be able to navigate toward the instance where the video has been published.

Example: if I play https://framatube.org/videos/watch/0d4a1ec1-9aa5-47e5-9e0d-3704b0ea7384 , I want to find a link to the `peertube.datagueule.tv` instance to easily be able to find all the *local* videos from this instance

Thanks a lot for what you are doing! :+1:

**Comment by strypey** [comment]
For the same reason, it would be good for users to have access to the list of instances blocked by any given instance. Mastodon provides some useful precedents for the community politics of instances. When people are choosing their instance, they're essentially choosing their "local pub", the community of "regulars" they will see and interact with a lot, and the "publican" who is in charge of moderating behaviour (and pouring the drinks). Seeing who is banned from the pub and why, is as important in making that decision as seeing who the regulars are.

**Comment by Jorropo** [comment]
Hi, as temporary solution you can use this script :)
It does this automaticaly.
https://github.com/Jorropo/PeerTube-autoDiscover

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/a6dbbf03865a955caaedc3b12f3de3e386fe850f that adds a new section in the about page to discover who the instance follows and who are its followers.
