### ISSUE TITLE
Top popular channels

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Chocobozzz/PeerTube#4502]
**Describe the problem to be solved**
I think that the option of [Top popular channels] could be added to the menu, it would consist of a list of the most popular channels, according to their views or number of subscribers.

**Describe the solution you would like:**
I attached a photo of how this option can look

![Captura de pantalla de 2021-10-27 03-00-54](https://user-images.githubusercontent.com/43164089/139016805-1fd222c3-1363-4a1c-b1a9-6ef1b430aaa5.png)

**Describe alternatives you have considered**  
A possible solution to show different popular channels can be by:
-  Number of subscribers
- Number of views
- Or by some algorithm that shows the user, possible channels that they like, according to their interests

**Comment by Chocobozzz** [comment]
Closing in favour of https://github.com/Chocobozzz/PeerTube/issues/1465
