### ISSUE TITLE
Please provide a video tutorial for remote storage

### ISSUE THREAD

**Issue by mrinalsworld** [Chocobozzz/PeerTube#4504]
Please provide a video tutorial for remote storage, for https://docs.joinpeertube.org/admin-remote-storage

Really appriciated.

**Comment by SimplyCorbett** [comment]
That's fairly straightforward. Which part are you getting stuck on?

**Comment by mrinalsworld** [comment]
I am so sorry, I just didn't get the notification. I am less experienced in Linux. Please share some steps guide or any link if available.
