### ISSUE TITLE
Provide permanent keys and templates for recorded streams [Live Shows!]

### ISSUE THREAD

**Issue by drequivalent** [Chocobozzz/PeerTube#4508]
**Describe the problem to be solved**

Every time I need to start the show, or a gaming session or anything else I want to record, I need to start a new live, fill in the description, tags, category, language, license and thumbnail, fish out the key, go to OBS or Nginx settings, and insert the key in there. This adds extra steps to a nervous as it is process of preparation, and it's error-prone, and Peertube's live stream functionality is pretty unforgiving: you screw up - go make another live stream, go get another key, go hop the same hoops all over again.

**Describe the solution you would like:**

Introduce the concept of a Live Show. Live Show is a template of a live stream that consists of:
 - Name (possibly with templates for numbers or dates, or, hell, why not just random words? It can be fun!)
 - Description (possibly with templates of the same sort also)
 - Tags
 - Category
 - Language
 - License
 - Thumbnail
 - A channel it publishes on, and, most importantly,
 - A permanent key for the OBS or other RTMP software to connect to, without changing the settings, or - changing them only when you need to do other show.

The workflow goes like this: you tap the "Create Live Show" button, fill out all the information above, get your permanent Live Show key, enter it into the OBS, and... just start streaming, and finish the stream. A day/week/two weeks/month later, when you want to make a new episode you just... start streaming again! And again! And again! And the recorded episodes just publish, with appropriate numbering.

This takes all the annoying and unnecessary busywork out of the preparation.

Additionally, make live streams more fault-tolerant. Provide a grace period to RTMP session loss. Show a user-defined "we'll be right back" picture or play a short clip while connection is lost and wait a user-defined amount of time until cutting the episode. This would be as per #3621

**Comment by Chocobozzz** [comment]
Hello,

What's the difference with a permanent live in which we can save replays? https://github.com/Chocobozzz/PeerTube/issues/3396

**Comment by scanlime** [comment]
> Hello,
> 
> What's the difference with a permanent live in which we can save replays? #3396

One difference here is that when you create a "permanent live" it shows up in everyone's feed exactly once and then it's buried. If peertube had some concept of a recurring show that could tie live and archived broadcasts together, that would begin to give it feature parity with other streaming platforms.

**Comment by scanlime** [comment]
I've been doing daily streams on PeerTube (plus twitch and youtube) and while it works the workflow is pretty awful. Here's how it usually goes:

- Decide on a new title for the stream, with the current date and topic
- Copy/paste that title into youtube and twitch where there are sensible stream dashboard UIs
- Find yesterday's "permanent" livestream on peertube, copy paste the parts I want into a new "permanent live"
- Switch computers, find the new "permanent live" again, copy paste the new stream key into OBS
- Finally do the stream
- After the stream, I'm done on youtube on twitch. For PeerTube I have more work to do:
- Start uploading a recording. I can't use PeerTube's built-in recordings or I'll have missing sections of video and I won't be able to reconnect if the connection drops, which it always does.
- Find the livestream again, copy/paste all the metadata I want as the recording is uploading
- Delete the livestream, since it's no longer useful and doesn't include saved content. Lose whatever interactions that video had.
- Wait for the actual archived recording to transcode, then it'll be automatically posted again into people's feeds.

**Comment by drequivalent** [comment]
> Hello,
> 
> What's the difference with a permanent live in which we can save replays? #3396

The difference in that it's a template with a streaming key attached to it. Which you can have multiple of!

Want to do another show - just use another key. Peertube will do the rest.

**Comment by Chocobozzz** [comment]
> One difference here is that when you create a "permanent live" it shows up in everyone's feed exactly once and then it's buried

It's something we want to fix (updating published at attribute every time someone streams into a permanent live)

> The difference in that it's a template with a streaming key attached to it. Which you can have multiple of!

But you can also have multiple permanent live, each one having its own attributes and streaming key.

**Comment by drequivalent** [comment]
Then probably we think of the same thing, and I just have a better name for it. Live show sounds better than "a permanent live with its own attributes and streaming key".
Will a permanent live automatically create a next episode complete with, for example, an episode number (or a date, or whatever user wants) and record it and save its replay though? Like, if the attribute template is, for example "Sam's Super Show episode <NUMBER(###)>", and there's already a recording named "Sam's Super Show episode 001", it will start as "Sam's Super Show episode 002", and save the recording. After this one, "Sam's Super Show episode 003" and so on. Just so that Sam doesn't manually go and rename anything.

**Comment by Chocobozzz** [comment]
Then closing in favour of https://github.com/Chocobozzz/PeerTube/issues/3396.

We'll try to improve live workflow next year. Thanks for your feedbacks!

**Comment by saumyakswain** [comment]
Any tentative timeline for this? Like first quarter, second quarter etc. 
Also a feature like breaking a permanent live into short videos (eg. 30min clips, 1hr clips etc) at predefined intervals would be useful.
