### ISSUE TITLE
FreeBSD - peertube - OPENSSL_1_1_1e required and not found

### ISSUE THREAD

**Issue by lpvm** [Chocobozzz/PeerTube#4509]
I'm trying to install a `peertube` instance in a jail of a FreeBSD 13.0-RELEASE amd64 system.

The following command
```
# yarn install --production --pure-lockfile
ld-elf.so.1: /lib/libcrypto.so.111: version OPENSSL_1_1_1e required by /usr/local
/bin/node not found
```
Package `openssl-1.1.1l,1` is accessible from the hosts' `sharedfs` and was also installed in the jail.

```
# find / -name 'libcrypto.so*'
/sharedfs/usr/lib/libcrypto.so
/sharedfs/lib/libcrypto.so.111
/usr/local/lib/libcrypto.so.11
/usr/local/lib/libcrypto.so
```

`peertube: v3.4.1`

How to proceed from here?

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I don't know free bsd. Since nobody seems to have an answer, I'm closing this issue. Maybe you will have more chance on the freebsd forum?
