### ISSUE TITLE
PeerTube not reachable after docker installation

### ISSUE THREAD

**Issue by PurgingPanda** [Chocobozzz/PeerTube#451]
peertube@1.0.0-beta.3
docker installation method

The docker-compose up seems to start successfully. With the output provided below. But I am unable to connect to the the peertube server using my browser. Is there something else that I need to do besides what is present in the docker installation guide?

```peertube_1  | [192.168.0.203:8080] 2018-03-31 17:31:55.262 info: Database peertube is ready.
peertube_1  | [192.168.0.203:8080] 2018-03-31 17:31:55.425 error: Cannot use SMTP server because of lack of configuration. PeerTube will not be able to send mails!
peertube_1  | [192.168.0.203:8080] 2018-03-31 17:31:55.431 info: Server listening on port 9000
peertube_1  | [192.168.0.203:8080] 2018-03-31 17:31:55.431 info: Web server: https://192.168.0.203:8080
```

**Comment by andzdroid** [comment]
You either need to expose the port in docker, or add a reverse proxy like traefik or nginx.

**Comment by andzdroid** [comment]
Add something like this to the docker-compose file:

```
    ports:
     - "80:9000"
```

To forward public 80 port to docker instance 9000 port. Read the docker-compose documentation for more info.

But if you do this, the site is only available through HTTP, not HTTPS, which means it can't follow other peertube instances.

**Comment by PurgingPanda** [comment]
Thank you, this solved it!

For reference for future viewers:
Add
```
ports:
 - "80:9000"```
to docker-compose.yml .

Then run "docker-compose up" and connect to it using port 80. For example "localhost:8".
