### ISSUE TITLE
"Social media" share options don't display well in dark mode

### ISSUE THREAD

**Issue by Altonss** [Chocobozzz/PeerTube#4512]
**Describe the current behavior**
"Social media" share options don't display well in dark mode. Even the icons themselves don't really fit with the dark theme.

**Steps to reproduce:**

1. Open the peertube instance in the web browser
2. Select the dark mode in peertube
3. Watch a video
4. Click on the share button under the video

**Describe the expected behavior**
The text under the "social media" icons should be lighter.

**Additional information**
![image](https://user-images.githubusercontent.com/66519591/139817932-eca04a2b-1e3b-42f9-87d3-a89ddd1eb797.png)

* PeerTube instance:
  * URL: https://peertube.tv
  * version: 3.4.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
Firefox 93.0 on Fedora 34 using Gnome desktop with Wayland

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue but you should open it on the [peertube-plugin-social-sharing](https://github.com/kimsible/peertube-plugin-social-sharing) repository which is not maintained by Framasoft :)

**Comment by Altonss** [comment]
Ah all right thank you for the information, I didn't know that this was a plugin ^
