### ISSUE TITLE
YouTube-DL Imports Failing Much of the Time

### ISSUE THREAD

**Issue by TILvids** [Chocobozzz/PeerTube#4515]
**Describe the current behavior**
YouTube imports are failing *sometimes*.

**Steps to reproduce:**

1. Import from URL.
2. Wait 20-30 minutes.
3. Video fails with "YoutubeDL download timeout."

**Describe the expected behavior**
This has been happening a lot, like on probably 70% of imports. But it doesn't happen all the time, sometimes the video goes through. It seems longer videos (20+ minutes) have a much higher chance of failing. It also seems like if two users try to import at the same time, the chance of failure it much higher. Video says it has successfully imported and you can fill out all the data for the video, but it just sits in "Pending" for 30-60 minutes. Eventually it times out and fails.

**Additional information**
I'm not sure if this is a YouTube-DL issue, or if YouTube is somehow rate-limiting the IP of the server, or something else? Whatever the culprit is, it's making it so importing from a URL is not a reliable process.

Server Error Log:
Job: 1430 Type: video-import Processed on Nov 3, 2021, 9:18:24 AM Finished on Nov 3, 2021, 10:18:24 AM

{
   "type": "youtube-dl",
   "videoImportId": 1481,
   "fileExt": ".mp4"
}

Error: YoutubeDL download timeout.
     at Timeout._onTimeout (/var/www/peertube/dist/server/helpers/youtube-dl.js:124:33)
     at listOnTimeout (internal/timers.js:557:17)
     at processTimers (internal/timers.js:500:7)'

* PeerTube instance:
  * URL: https://tilvids.com
  * version: 3.4.0
  * NodeJS version: Default
  * Ffmpeg version: Default

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by rigelk** [comment]
This will love fixed by the next release, which offers the possibility to switch to ytp. As it stands, ytp seems to offer the most up to date bypasses to the current evolution of YouTube's API rate-limiting when not using the proper URL parameters.

**Comment by TILvids** [comment]
Thanks @rigelk good to know! I'll keep an eye open for the next update, and keep my fingers crossed!

**Comment by tio-trom** [comment]
Same here. Glad to see it will be fixed soon.
```

info[12/5/2021, 12:10:35 AM] Notifying user tio its video import https://www.youtube.com/watch?v=EClSvCZkGw0 is finished.

error[12/5/2021, 12:10:35 AM] Cannot execute job 453 in queue video-import.

{
  "payload": {
    "type": "youtube-dl",
    "videoImportId": 1487,
    "fileExt": ".webm"
  },
  "err": {
    "stack": "Error: YoutubeDL download timeout.\n    at Timeout._onTimeout (/var/www/peertube/dist/server/helpers/youtube-dl.js:124:33)\n    at listOnTimeout (internal/timers.js:557:17)\n    at processTimers (internal/timers.js:500:7)",
    "message": "YoutubeDL download timeout."
  }
}
```
Which release number will have this fix? I would like to try that. I am using 	3.4.1 .

**Comment by Booteille** [comment]
The v4 (which is actually in Release Candidate) will support this.
