### ISSUE TITLE
Error uploading new content after upgrade 

### ISSUE THREAD

**Issue by dbanovski** [Chocobozzz/PeerTube#4517]
Hello,

after I have mgrated my peertube 3.0.1 to a new server and then performed an upgrade from 3.0.1 to 3.4.1 using the instructions provided on https://docs.joinpeertube.org/install-any-os?id=upgrade I have problems uploading content

Trying to upload any supported filetype results in "Your video file was too large (max. size: 8G)"

I can only upload files smaller than 2 MB
The problem is presenting itself on both the testing and producton server. All config data has been rsynced

P.S. after migration uploads were possible, they only started to fail after the upgrade has been completed

**Comment by kontrollanten** [comment]
We've also encountered a similar issue, but just with one specific file. When we tried to upload the same file from another computer and network it worked.

**Comment by Chocobozzz** [comment]
Try to check your nginx config: https://github.com/Chocobozzz/PeerTube/blob/develop/CHANGELOG.md#important-notes-3

**Comment by dbanovski** [comment]
Thank you, must have missed that. 

adding upload-resumable endpoint resolves this problem
