### ISSUE TITLE
When sharing a video and ticking the "use origin instance URL" version is not checked (thus generates invalid urls with /w/)

### ISSUE THREAD

**Issue by alex9099** [Chocobozzz/PeerTube#4518]
**Describe the current behavior**
Shared dialog produces an invalid URL when ticking the "use origin instance URL" if the origin instance uses an older version version of peertube that doesn't support the /w/ short handle

**Steps to reproduce:**

1. Open any video where the origin instance has an older PT version (this one for example https://tube.tardis.world/w/mziZQzmf95pGMSqk7BPZvi ) 
2. Click share and tick "Use origin instance URL"
3. Get an invalid URL (https://video.blender.org/w/mziZQzmf95pGMSqk7BPZvi when that version only supports  https://video.blender.org/videos/watch/a69d68a5-a0e0-4a80-9d66-49f093c97aaf )

**Describe the expected behavior**
Share dialog should generate a valid URL when ticking "use origin instance URL" regardless of what the other instance version is

**Additional information**

* PeerTube instance:
  * version: 3.4.1
  * NodeJS version: 12.22.7
  * Ffmpeg version: 4.3.2

* Browser name, version and platforms on which you could reproduce the bug: Firefox 93.0

**Comment by tcitworld** [comment]
Duplicate from https://github.com/Chocobozzz/PeerTube/issues/4479

**Comment by alex9099** [comment]
Thanks, i did search but find nothing ;)
