### ISSUE TITLE
Hide Homepage for users, that are not logged in

### ISSUE THREAD

**Issue by Stormkoopa** [Chocobozzz/PeerTube#4520]
**Hide Homepage for users, that are not logged in**

**I would like to have a checkbox or privacy setting for the homepage to be hidden for users, that are currently not logged in. If I set the video privacy settings of the videos, shown on my homepage to internal only, the captions written in my HTML code still show. If there is another way to hide them for not logged in users I would really appreciate it since I am not an expert HTML programmer.**

**Comment by Chocobozzz** [comment]
Hello,

Thanks for the issue but we prefer to not have multiple homepage depending on the user. I suggest you to create a plugin to hide the menu entry/homepage page if the user is not logged in instead.
