### ISSUE TITLE
Fediverse reject blacklist

### ISSUE THREAD

**Issue by EkkiBrue** [Chocobozzz/PeerTube#4521]
We are running an educational peertube.

We are bombarded with requests of questionable peertube instances.

Is there a chance to have a feature to run an own blacklist to block already blocked requests ?

We are aware of Plugin "auto-mute" - but we can´t edit the list on our own.

Thank you.

**Comment by Chocobozzz** [comment]
Hello,

I'm not sure to understand. If I understand well your use case, the [auto-mute](https://framagit.org/framasoft/peertube/official-plugins/-/tree/master/peertube-plugin-auto-mute) plugin should be the appropriate solution: create a custom JSON file containing muted instances and put its URL in plugin settings
