### ISSUE TITLE
More/Less Filters button should say 'Fewer'

### ISSUE THREAD

**Issue by realkinetix** [Chocobozzz/PeerTube#4526]
Peertube 3.4.0

Please fix the filter button to appropriately use Fewer, not Less.

You can count filters, therefore the usage is Fewer.

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/6fd4f8975cce2499a966975d6aa4e7929ca3d1aa

We now use "Hide filters" instead

**Comment by realkinetix** [comment]
Sounds good, thanks!
