### ISSUE TITLE
What's the proper way to migrate to HLS?

### ISSUE THREAD

**Issue by alejandrocobo** [Chocobozzz/PeerTube#4530]
Hi. I have a couple of instances that were set up to use WebTorrent from the beginning and now I'd like to use HLS. I guess if I enable HLS and disable Webtorrent, all videos in Webtorrent will remain like that and only new uploads will be served as HLS videos.

What is the better way to convert all WebTorrent videos into HLS and then keep just the HLS version of all the content?

Thanks.

**Comment by Chocobozzz** [comment]
> I guess if I enable HLS and disable Webtorrent, all videos in Webtorrent will remain like that and only new uploads will be served as HLS videos.

Yes exactly

> What is the better way to convert all WebTorrent videos into HLS and then keep just the HLS version of all the content?

You can use https://docs.joinpeertube.org/maintain-tools?id=create-transcoding-jobjs to generate HLS version, but unfortunately there is not way to delete webtorrent files for now. Please see https://github.com/Chocobozzz/PeerTube/issues/3200

**Comment by lstamellos** [comment]
Is there a way to generate HLS versions in bulk for all older videos that didn't have one?
