### ISSUE TITLE
Add opentelemetry exporter

### ISSUE THREAD

**Issue by drym3r** [Chocobozzz/PeerTube#4532]
**Describe the problem to be solved**
It's similar to this issue in here https://github.com/Chocobozzz/PeerTube/issues/3742. But I'd like to add a couple of things.

First is that the Prometheus format is not just "another" metric format, it's the standard de facto in the observability community. Also, as the title states, I talk about OpenTelemetry, which is Metrics, Logs and Traces. You may want to check it [here](https://opentelemetry.io/).

It's in early days, but this will be the standard of observability. So, adding Prometheus metrics or traces, that being done using OT or the native libraries, it's an inversion that every piece of software should do to standardize the way we look at those.

**Describe the solution you would like:**

Offer metrics and/or traces in a standard format.

**Describe alternatives you have considered**  
The workaround that's described in the related issue might work. But it requires an exporter, an external piece of software. It would be way better that the metrics would be offered directly by Peertube.

PD: Thanks for your work, Peertube is very cool!

**Comment by Chocobozzz** [comment]
Hi and thanks :)

I don't know open telemetry. Could you explain what you would expect PeerTube to do?

**Comment by drym3r** [comment]
Sure. Opentelemetry is a collection of libraries that abstract the creation of logs, metrics and traces. As I said, there's a de facto standard for traces and metrics, but not for logs.
Although, what opentelemetry libraries does is give every language a set of apis to export this data to the backend you want, being this your monitoring tool of choice.

What I'd like to see is peertube exposing the metrics in a more standard way. Also, I haven't take a look yet to what metrics does expose, but I'd like to have one for every relevant event that happens when running the program.

Does it make sense for you?

**Comment by scanlime** [comment]
fwiw i've been finding metrics really critical to keeping a peertube server running smoothly; this dashboard runs on influxdb and grafana, and data collection is a mix of standard telegraf stuff and some small custom things to get peertube-specific stats.

![image](https://user-images.githubusercontent.com/923812/141527872-e029301b-2401-48c4-96bd-6a6231a68356.png)

**Comment by drym3r** [comment]
That's awesome, it would be great to have some metrics in the format of openmetrics and also some grafana dashboards, so admins can import them easily.

**Comment by Chocobozzz** [comment]
FYI we just added a documentation for OpenTelemetry with a Grafana dashboard template on https://docs.joinpeertube.org/maintain-observability
