### ISSUE TITLE
Cannot extend or remove expiration

### ISSUE THREAD

**Issue by c0xc** [Chocobozzz/PeerTube#4534]
**Describe the current behavior**

    Cannot extend or remove expiration of https://<ORIGIN>/videos/watch/<UUID>-360 video from our redundancy system. 
    "message": "Cannot read property 'uuid' of null"

There are many of these but I picked one uuid and so far, it is still on the mirror and that mirror is still serving it to viewers.

**Steps to reproduce:**

Not sure.

**Describe the expected behavior**

Maybe this error could be caught and in case something is wrong with the origin instance (i.e., one that this mirror follows) a popup warning should indicate such a possible configuration error, like those popup messages when you have a new follower and it should warn the admin that the redundancy mechanism might currently be unable to mirror all origin videos because the origin instance is in a bad state.

**Additional information**

Some of these errors are followed by warnings like this one:

    Signature from https://<ORIGIN>/accounts/<ADMIN> is invalid
    "signingString": "(request-target): post /inbox\nhost: <MIRROR>\ndate: Thu, ...\ndigest: SHA-256=7...o=",

All of these are showing up on a mirror instance running Peertube v3.4.0, same as the origin instance.

* PeerTube instance:
  * version: v3.4.0
  * NodeJS version: v12
  * Ffmpeg version: v4.2.4

**Comment by Chocobozzz** [comment]
Thanks for the issue, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/3ef5909aecf5aa33c9f1235df81d4f8c5c8948f6
