### ISSUE TITLE
Is it possible to limit non logged in users to view any videos?

### ISSUE THREAD

**Issue by Horuyuki** [Chocobozzz/PeerTube#4535]
Is there a way to limit access for all guests? Since I cannot use the nginx basic auth which will break the log in mechanism of peertube.

What I have in mind is to limit all guests to see nothing until logged in, or is there another way?

**Comment by Chocobozzz** [comment]
Hello,

> What I have in mind is to limit all guests to see nothing until logged in, or is there another way?

No it's the way to go. You can upload videos in `internal` privacy so only logged in users can see them.
