### ISSUE TITLE
Name users explicitly in confirmation prompts

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#4536]
**Describe the problem to be solved**

I delete a lot of users when I deal with daily spammer registrations, and I always have to be very careful to double-check what i'm doing so I don't accidentally delete a legit user. It would be really useful if the confirmation dialogs explicitly named what was going to happen, like "Are you sure you want to delete user spambot99999?"

The current prompt is totally generic, only reflecting the operation being performed and not the entity it effects, so I have to look around the prompt back to what I've selected in the UI behind it, to do my double-check before clicking ok.

![image](https://user-images.githubusercontent.com/923812/141348105-c27be3ef-a4f3-4656-a62e-f77e0f5ef5aa.png)

**Describe the solution you would like:**

Please have all confirmation prompts name both the action being performed and the object it's being performed on.

**Describe alternatives you have considered**

This whole issue would be less serious if deletion wasn't such an difficult to reverse operation, any undo support would mitigate this.

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/a7dbc608714ed1981783cd98fd6909866fa78236

> This whole issue would be less serious if deletion wasn't such an difficult to reverse operation, any undo support would mitigate this.

Banning and muting are the "reverse operation"

**Comment by scanlime** [comment]
> Fixed by [a7dbc60](https://github.com/Chocobozzz/PeerTube/commit/a7dbc608714ed1981783cd98fd6909866fa78236)
> 
> > This whole issue would be less serious if deletion wasn't such an difficult to reverse operation, any undo support would mitigate this.
> 
> Banning and muting are the "reverse operation"

I haven't found banning/muting to be sufficient for dealing with automated spammers. They are registered frequently enough and commonly enough and take up enough resources that I want to minimize that as early as possible. This is especially true for spammers who immediately upload a bunch of videos. I would find it useful to have some UI support for undoing arbitrary operations- basically a snapshot backup system for database and content. I already use zfs snapshots for backing up the underlying storage, and a way for administrators to restore database or video items from backups automatically would be the kind of "undo" i had in mind.

**Comment by scanlime** [comment]
I appreciate the fix for user delete; are there other confirmation modals that could use this same treatment, like video deletions?

**Comment by scanlime** [comment]
Oh, another important distinction between ban and delete here: In many cases with spam I do actually want to delete the account profile, since that's where the spam is much of the time. (SEO spammers post links with a paragraph of automatically generated text or a prewritten advertisement)
