### ISSUE TITLE
Way to tell if video has captions

### ISSUE THREAD

**Issue by u-spec-png** [Chocobozzz/PeerTube#4537]
As of now there doesn't seem to be a way to tell if video has captions, instead I have to make a request to see if video has captions.

A `hasCaptions` boolean in Get Video method to know if it is worth making a request for captions.

**Comment by Chocobozzz** [comment]
Hello,

GET video API is already a big SQL request, and adding this boolean would require an additional join. So I'm sorry but we prefer clients to make a dedicated GET on another endpoint to know if the video has subtitles, for performance and maintenance.
