### ISSUE TITLE
"video-channels" page shows channels from multiple users when visiting a user from a notification

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#4538]
**Describe the current behavior**

It looks like this is triggered by switching from one user to another without going through another page: the list of channels isn't cleared, so the result is that channels from the last viewed user are mixed with channels from the current user. This has been around for a while but I keep forgetting to report it.

**Steps to reproduce:**

1. Open admin notifications while viewing a user's video-channels page
![image](https://user-images.githubusercontent.com/923812/141527107-2857231a-75bf-4ef0-a62e-9ef7bc61b904.png)

2. Click one of the user registration notifications
3. Resulting page still has the previous user's videos loaded

![image](https://user-images.githubusercontent.com/923812/141527209-bfc16a2a-ea1d-4445-85a6-593c511c8a0d.png)

**Describe the expected behavior**

Expect pages to render the same regardless of the previous page

**Additional information**

* PeerTube instance:
  * URL: diode.zone
  * version: 3.4.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox, Chrome
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/50fe0eac38e7a5ea6960ab4d507b5a356b5a188e
