### ISSUE TITLE
Ability to fetch past videos

### ISSUE THREAD

**Issue by ShadowJonathan** [Chocobozzz/PeerTube#4539]
#### Describe the problem to be solved

When loading remote channels on servers which have never seen these instances before, the channel loads, but without any videos.

I come to Peertube from a Youtube idea of a video-sharing site, and I (at the very least) expect to be able to list and watch past videos. I also think that this is required for a healthy buildup of the network, and to allow individual instances to be feasable (without following every major or minor instance that's out there).

#### Describe the solution you would like

I'm requesting a way to query or fetch past videos from a remote channel, and to have this show up in the list as if this information was available all along.

---

I am faintly aware that loading past content is a ActivityPub-fundamental problem, only i don't know where to voice those problems (as the w3c activitypub repo seems fairly abandoned and inactive).

If someone can point me to a place where i can voice this concern more generally, that'd be appreciated.

**Comment by Chocobozzz** [comment]
Hello,

PeerTube should already fetch previously uploaded videos. It may require some time though. See https://github.com/Chocobozzz/PeerTube/issues/3947

**Comment by Chocobozzz** [comment]
Could you check peertube logs to see if there are some errors when your instance tries to fetch this channel's videos?

**Comment by ShadowJonathan** [comment]
That's not my instance, do I can't verify that, sorry

**Comment by Chocobozzz** [comment]
I'm sorry but without log I can't help. Could you contact your administrator?
