### ISSUE TITLE
Generic CSS is overridden by angular CSS

### ISSUE THREAD

**Issue by andzdroid** [Chocobozzz/PeerTube#454]
Using any kind of generic CSS like

```
input[type=submit] { background-color: black; }
```

Is always overridden by the more specific angular css like:

```
input[type=submit][_ngcontent-c8] { background-color: #f1680d; }
```

I can't globally set the CSS for a type of element. I need to specifically override each element's properties using their _ngcontent selector. This makes custom CSS a pain to write because I need to find the specific element I want to update and copy its selector, then check to see which elements were not updated because they have a different _ngcontent ID.

**Comment by Chocobozzz** [comment]
Yes I know :/ I don't think there is a magic trick here to resolve this issue. You'll need to use `!important` for each property. Maybe we could add them automatically when you save the configuration.

**Comment by andzdroid** [comment]
Thanks, adding `!important` has helped for some elements. Unfortunately there are actually some elements that already use `!important`, so I can't override them that way.

**Comment by Chocobozzz** [comment]
I added an id to the body: https://github.com/Chocobozzz/PeerTube/commit/d49b872a7a2e0d6ecb9c23a349ba2c6e578ea3eb

Now you just have to write:

```
#custom-css .logged-in-email {
  color: red;
}
```

It will be more specific than Angular attributes (just add `!important` to override important defined properties). Hope that will help.
