### ISSUE TITLE
[Feature | Docs] Add GNU Shepherd Service

### ISSUE THREAD

**Issue by ncorder** [Chocobozzz/PeerTube#4540]
**Describe the problem to be solved**

The Documentation does not have a section for GNU Shepherd

**Describe the solution you would like:**

Add a section for GNU Shepherd, similar to OpenRC

**Describe alternatives you have considered**  

I have considered none.

**Comment by ncorder** [comment]
GNU Shepherd Manual: https://www.gnu.org/software/shepherd/manual/shepherd.html

OpenRC int.d format: https://github.com/Chocobozzz/PeerTube/blob/develop/support/init.d/peertube

GNU Shepherd Service Examples: https://www.gnu.org/software/shepherd/manual/html_node/Service-Examples.html

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I don't know GNU Shepherd, so I can't maintain a documentation nor a template for it. You can create a PR on the [documentation](https://docs.joinpeertube.org/install-unofficial) to add it if you want.

**Comment by ncorder** [comment]
> I'm sorry but I don't know GNU Shepherd

:+1: I don't have a ton of experience with services either, but I will look into crafting a PR for it

> GNU Shepherd

@Chocobozzz Is there anything users should be aware of if they wish to manually run Peertube without a service?

**Comment by Chocobozzz** [comment]
> @Chocobozzz Is there anything users should be aware of if they wish to manually run Peertube without a service?

No, you could run it in a tmux for example. The service is just here to run and track the process, but you can use whatever you want :)
