### ISSUE TITLE
More default colour schemes

### ISSUE THREAD

**Issue by KSPAtlas** [Chocobozzz/PeerTube#4541]
I personally am not a fan of the orange and black colour scheme, and other people probably also aren't fans of it. So you think you could implement multiple accent colour for default themes?

**Comment by Chocobozzz** [comment]
Hello,

We provide CSS variables so developers can easily create their own PeerTube themes. Admins can install them on their instance and users can choose the theme they want.
See for example https://framatube.org/

**Comment by KSPAtlas** [comment]
I mean user themes.

**Comment by ElonVampire** [comment]
收到！
