### ISSUE TITLE
iOS 9.x Chrome & Safari

### ISSUE THREAD

**Issue by oghh** [Chocobozzz/PeerTube#4542]
censorship makes PeerTube very important and widespread used... 
So why it fails to support older/simpler Browsers ?
Even YouTube runs remarkably good in Chrome on a 32bit iPad 2 with iOS 9.x !!!
Please try your best to be as accessible as possible 
and to lower any hurdles especially for lower incomes and older people.

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry about that and I understand your frustration. But Framasoft doesn't have time to maintain and support very old OS. I'm the only employee on peertube, so the comparison with youtube doesn't make much sense. And I don't think web developers are the people to blame if Apple lock their users with a completely outdated webkit engine, even if the hardware can run a more recent web browser.
