### ISSUE TITLE
Federation - redundancy scheduler issue

### ISSUE THREAD

**Issue by zguig52** [Chocobozzz/PeerTube#4543]
Hello,

Fist, thanks for this really good job. I am on latest peertube version from docker and didn't had this issue before one year ago. Please note that it is a fresh install.

I have two servers and configured a full replication strategy for federation (server1 / master <-- follow / is follwed --> server2 / replica):
redundancy:
  videos:
    check_interval: '1 hour' # How often you want to check new videos to cache
    strategies: # Just uncomment strategies you want
      -
        size: '250GB'
        # Minimum time the video must remain in the cache. Only accept values > 10 hours (to not overload remote instances)
        min_lifetime: '11 hours'
        strategy: 'recently-added' # Cache recently added videos
        min_views: 0 # Having at least x views

Videos are properly duplicated. But, after a while, they are no more known from the initial instance, thus the secondary peer is no more advertised to streaming peers by server1. But when I play it from the secondary, there are two peers.

When I check on the secondary server, I see this error:
info[15/11/2021, 12:46:36] Running redundancy scheduler for strategy recently-added.
{
  "tags": [
    "redundancy"
  ]
}
error[15/11/2021, 12:46:36] Cannot extend or remove expiration of https://MYSERVERNAME/static/streaming-playlists/hls/d936d307-0af7-4b75-8e40-a252d678d45d/772ecf44-45a2-455b-b074-7140eda76dcf-master.m3u8 video from our redundancy system.
{
  "err": {
    "stack": "TypeError: Cannot read property 'uuid' of null\n    at VideosRedundancyScheduler.<anonymous> (/app/dist/server/lib/schedulers/videos-redundancy-scheduler.js:253:156)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "message": "Cannot read property 'uuid' of null"
  },
  "tags": [
    "redundancy",
    "d936d307-0af7-4b75-8e40-a252d678d45d"
  ]
}

Is there something to do to fix this?

The secondary is not able to tell the first that he is having the video in his cache.

**Comment by Chocobozzz** [comment]
Hi,

It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/3ef5909aecf5aa33c9f1235df81d4f8c5c8948f6

Could you try `develop-buster`?

**Comment by zguig52** [comment]
:)

Perfect, it is fixed on this version!

Thanks a lot, I will go back to production-buster on the secondary node when this is merged on this branch!
