### ISSUE TITLE
Apache webproxy and Nginx-Peertube configuration

### ISSUE THREAD

**Issue by Yalman** [Chocobozzz/PeerTube#4546]
Hello,

i installed the Peertube instance as in the production guide described. The "/var/www/peertube/storage" dir is sym linked to a nfs share in "/mnt/nfs/peertube/storage".
I use a Apache Webproxy on a seperate VM.

If i try to play a video, but they hung and show the loading cycle. Also i cant select a resolution.
If i try to get the video and thumbnail per link i receive the following messages:

![2021-11-16_18-05](https://user-images.githubusercontent.com/6912504/142031885-7733e8ad-bce2-4277-8719-d99cf56519d2.png)

![2021-11-16_16-35](https://user-images.githubusercontent.com/6912504/142024722-f846b68d-bf30-4e14-8fef-fabbea6b5cd1.png)

![2021-11-16_16-36](https://user-images.githubusercontent.com/6912504/142024743-2e3eb3fb-84dc-4966-8dcc-6f7ff25e6421.png)

* PeerTube instance:
  * version: 3.4.1
  * NodeJS version: v14.18.1
  * Ffmpeg version: 4.3.3-0+deb11u1
  * Redis version: 6.0.16
  * PostgreSQL version: 13+225

My configs:

/etc/nginx/sites-available/peertube

`
upstream backend {
  server 127.0.0.1:9000;
}

server {
  listen 80;
  listen [::]:80;
  server_name peertube.DOMAIN.TOPLDOMAIN;

  access_log /var/log/nginx/peertube.access.log; # reduce I/0 with buffer=10m flush=5m
  error_log  /var/log/nginx/peertube.error.log;

  location @api {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host            $host;
    proxy_set_header X-Real-IP       $remote_addr;

    client_max_body_size  100k; # default is 1M

    proxy_connect_timeout 10m;
    proxy_send_timeout    10m;
    proxy_read_timeout    10m;
    send_timeout          10m;

    proxy_pass http://backend;
  }

  location / {
    try_files /dev/null @api;
  }

  location = /api/v1/videos/upload-resumable {
    client_max_body_size    0;
    proxy_request_buffering off;

    try_files /dev/null @api;
  } 

  location = /api/v1/videos/upload {
    limit_except POST HEAD { deny all; }

    client_max_body_size                      12G; # default is 1M
    add_header            X-File-Maximum-Size 8G always; # inform backend of the set value in bytes before mime-encoding (x * 1.4 >= client_max_body_size)

    try_files /dev/null @api;
  } 

  location ~ ^/api/v1/(videos|video-playlists|video-channels|users/me) {
    client_max_body_size                      6M; # default is 1M
    add_header            X-File-Maximum-Size 4M always; # inform backend of the set value in bytes before mime-encoding (x * 1.4 >= client_max_body_size)

    try_files /dev/null @api;
  }

  location @api_websocket {
    proxy_http_version 1.1;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   Host            $host;
    proxy_set_header   X-Real-IP       $remote_addr;
    proxy_set_header   Upgrade         $http_upgrade;
    proxy_set_header   Connection      "upgrade";

    proxy_pass http://backend;
  }

  location /socket.io {
    try_files /dev/null @api_websocket;
  } 

  location /tracker/socket {
    proxy_read_timeout 15m; # default is 60s

    try_files /dev/null @api_websocket;
  }

  root /var/www/peertube/storage;

  gzip              on;
  gzip_vary         on;
  gzip_types        # text/html is always compressed by HttpGzipModule
                    text/css
                    application/javascript
                    font/truetype
                    font/opentype
                    application/vnd.ms-fontobject
                    image/svg+xml;
  gzip_min_length   1000; # default is 20 bytes
  gzip_buffers      16 8k;
  gzip_comp_level   2; # default is 1

  client_body_timeout       30s; # default is 60
  client_header_timeout     10s; # default is 60
  send_timeout              10s; # default is 60
  keepalive_timeout         10s; # default is 75
  resolver_timeout          10s; # default is 30
  reset_timedout_connection on;
  proxy_ignore_client_abort on;

  tcp_nopush                on; # send headers in one piece
  tcp_nodelay               on; # don't buffer data sent, good for small data bursts in real time

  location ~ ^/client/(assets/images/(icons/icon-36x36\.png|icons/icon-48x48\.png|icons/icon-72x72\.png|icons/icon-96x96\.png|icons/icon-144x144\.png|icons/icon-192x192\.png|icons/icon-512x512\.png|logo\.svg|favicon\.png))$ {
    add_header Cache-Control "public, max-age=31536000, immutable"; # Cache 1 year

    root /var/www/peertube;

    try_files /storage/client-overrides/$1 /peertube-latest/client/dist/$1 @api;
  } 

  location ~ ^/client/(.*\.(js|css|png|svg|woff2|otf|ttf|woff|eot))$ {
    add_header Cache-Control "public, max-age=31536000, immutable"; # Cache 1 year

    alias /var/www/peertube/peertube-latest/client/dist/$1;
  }

  location ~ ^/static/(thumbnails|avatars)/ {
    if ($request_method = 'OPTIONS') {
      add_header Access-Control-Allow-Origin  '*';
      add_header Access-Control-Allow-Methods 'GET, OPTIONS';
      add_header Access-Control-Allow-Headers 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
      add_header Access-Control-Max-Age       1728000; # Preflight request can be cached 20 days
      add_header Content-Type                 'text/plain charset=UTF-8';
      add_header Content-Length               0;
      return 204;
    }

    add_header Access-Control-Allow-Origin    '*';
    add_header Access-Control-Allow-Methods   'GET, OPTIONS';
    add_header Access-Control-Allow-Headers   'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
    add_header Cache-Control                  "public, max-age=7200"; # Cache response 2 hours

    rewrite ^/static/(.*)$ /$1 break;

    try_files $uri @api;
  }

  location ~ ^/static/(webseed|redundancy|streaming-playlists)/ {
    limit_rate_after            5M;

    set $peertube_limit_rate    800k;

    if ($request_uri ~ -fragmented.mp4$) {
      set $peertube_limit_rate  5M;
    }

    set $limit_rate $peertube_limit_rate;

    if ($request_method = 'OPTIONS') {
      add_header Access-Control-Allow-Origin  '*';
      add_header Access-Control-Allow-Methods 'GET, OPTIONS';
      add_header Access-Control-Allow-Headers 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
      add_header Access-Control-Max-Age       1728000; # Preflight request can be cached 20 days
      add_header Content-Type                 'text/plain charset=UTF-8';
      add_header Content-Length               0;
      return 204;
    }

    if ($request_method = 'GET') {
      add_header Access-Control-Allow-Origin  '*';
      add_header Access-Control-Allow-Methods 'GET, OPTIONS';
      add_header Access-Control-Allow-Headers 'Range,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

      access_log off;
    }

    sendfile on;
    sendfile_max_chunk 1M; # prevent one fast connection from entirely occupying the worker process. should be > 800k.
    aio threads;

    rewrite ^/static/webseed/(.*)$ /videos/$1 break;
    rewrite ^/static/(.*)$         /$1        break;

    try_files $uri @api;
  }
}
`

/var/www/peertube/config/production.yaml

`
listen:
  hostname: 'localhost'
  port: 9000

webserver:
  https: true
  hostname: 'peertube.DOMAIN.TOPLDOMAIN'
  port: 443

rates_limit:
  api:
    window: 10 seconds
    max: 50
  login:
    window: 5 minutes
    max: 15
  signup:
    window: 5 minutes
    max: 2
  ask_send_email:
    window: 5 minutes
    max: 3

trust_proxy:
  - 'loopback'
  - '10.0.X.XX'    <- this is the IP address of my Apache-Letsencrypt Proxy
  
database:
  hostname: 'localhost'
  port: 5432
  ssl: false
  suffix: '_prod'
  username: 'peertube'
  password: 'XXXXXXXXXX'
  pool:
    max: 5

redis:
  hostname: 'localhost'
  port: 6379
  auth: null
  db: 0

smtp:
  transport: smtp
  sendmail: null
  hostname: null
  port: 465 # If you use StartTLS: 587
  username: null
  password: null
  tls: true # If you use StartTLS: false
  disable_starttls: false
  ca_file: null # Used for self signed certificates
  from_address: 'admin@example.com'

email:
  body:
    signature: "PeerTube"
  subject:
    prefix: "[PeerTube]"

storage:
  tmp: '/var/www/peertube/storage/tmp/' # Use to download data (imports etc), store uploaded files before and during processing...
  avatars: '/var/www/peertube/storage/avatars/'
  videos: '/var/www/peertube/storage/videos/'
  streaming_playlists: '/var/www/peertube/storage/streaming-playlists/'
  redundancy: '/var/www/peertube/storage/redundancy/'
  logs: '/var/www/peertube/storage/logs/'
  previews: '/var/www/peertube/storage/previews/'
  thumbnails: '/var/www/peertube/storage/thumbnails/'
  torrents: '/var/www/peertube/storage/torrents/'
  captions: '/var/www/peertube/storage/captions/'
  cache: '/var/www/peertube/storage/cache/'
  plugins: '/var/www/peertube/storage/plugins/'
  client_overrides: '/var/www/peertube/storage/client-overrides/'

object_storage:
  enabled: false

  endpoint: '' # 's3.amazonaws.com' or 's3.fr-par.scw.cloud' for example

  region: 'eu-central-1'

  credentials:
    access_key_id: ''
    secret_access_key: ''

  max_upload_part: 2GB

  streaming_playlists:
    bucket_name: 'streaming-playlists'

    prefix: '' # Example: 'streaming-playlists:'

  base_url: '' # Example: 'https://mirror.example.com'

  videos:
    bucket_name: 'videos'
    prefix: ''
    base_url: ''

log:
  level: 'debug' #'info' # 'debug' | 'info' | 'warn' | 'error'
  rotation:
    enabled : true # Enabled by default, if disabled make sure that 'storage.logs' is pointing to a folder handled by logrotate
    maxFileSize: 12MB
    maxFiles: 20
  anonymizeIP: false
  log_ping_requests: true
  prettify_sql: false

trending:
  videos:
    interval_days: 7 # Compute trending videos for the last x days
    algorithms:
      enabled:
        - 'best' # adaptation of Reddit's 'Best' algorithm (Hot minus History)
        - 'hot' # adaptation of Reddit's 'Hot' algorithm
        - 'most-viewed' # default, used initially by PeerTube as the trending page
        - 'most-liked'
      default: 'most-viewed'

redundancy:
  videos:
    check_interval: '1 hour' # How often you want to check new videos to cache
    strategies: # Just uncomment strategies you want

remote_redundancy:
  videos:
    accept_from: 'anybody'

csp:
  enabled: false
  report_only: true # CSP directives are still being tested, so disable the report only mode at your own risk!
  report_uri:

security:
  frameguard:
    enabled: true

tracker:
  enabled: true
  private: true
  reject_too_many_announces: false

history:
  videos:
    max_age: -1

views:
  videos:
    remote:
      max_age: '30 days'

plugins:
  index:
    enabled: true
    check_latest_versions_interval: '12 hours' # How often you want to check new plugins/themes versions
    url: 'https://packages.joinpeertube.org'

federation:
  videos:
    federate_unlisted: false

   cleanup_remote_interactions: false

peertube:
  check_latest_version:
    enabled: true
    url: 'https://joinpeertube.org/api/v1/versions.json'

cache:
  previews:
    size: 500 # Max number of previews you want to cache
  captions:
    size: 500 # Max number of video captions/subtitles you want to cache
  torrents:
    size: 500 # Max number of video torrents you want to cache

admin:
  email: 'admin@example.com'

contact_form:
  enabled: true

signup:
  enabled: false
 limit: 10 # When the limit is reached, registrations are disabled. -1 == unlimited
  minimum_age: 16
  requires_email_verification: false
  filters:
    cidr: # You can specify CIDR ranges to whitelist (empty = no filtering) or blacklist
      whitelist: []
      blacklist: []

user:
  video_quota: -1
  video_quota_daily: -1

transcoding:
  enabled: true

  allow_additional_extensions: true

  allow_audio_files: true

  threads: 2
  concurrency: 2

  profile: 'default'

  resolutions: # Only created if the original video has a higher resolution, uses more storage!
    0p: true # audio-only (creates mp4 without video stream, always created when enabled)
    240p: true
    360p: false
   480p: true
    720p: false
    1080p: true
    1440p: false
    2160p: false

  webtorrent:
    enabled: false

  hls:
    enabled: true

live:
  enabled: false

  max_duration: -1 # For example: '5 hours'

  max_instance_lives: 20

  max_user_lives: 3

  allow_replay: true

  rtmp:
    port: 1935

  transcoding:
    enabled: true
    threads: 2

    profile: 'default'

    resolutions:
      240p: false
      360p: false
      480p: false
      720p: false
      1080p: false
      1440p: false
      2160p: false

import:
  videos:
    concurrency: 1

    http: # Classic HTTP or all sites supported by youtube-dl https://rg3.github.io/youtube-dl/supportedsites.html
      enabled: false

     force_ipv4: false

      proxy:
        enabled: false
        url: ""
    torrent: # Magnet URI or torrent file (use classic TCP/UDP/WebSeed to download the file)
      enabled: false

auto_blacklist:
  videos:
    of_users:
      enabled: false

instance:
  name: 'PeerTube'
  short_description: 'PeerTube, an ActivityPub-federated video streaming platform using P2P directly in your web browser.'
  description: 'Welcome to this PeerTube instance!' # Support markdown
  terms: 'No terms for now.' # Support markdown
  code_of_conduct: '' # Supports markdown

  moderation_information: '' # Supports markdown

  creation_reason: '' # Supports Markdown

  administrator: '' # Supports Markdown

  maintenance_lifetime: '' # Supports Markdown

  business_model: '' # Supports Markdown

  hardware_information: '' # Supports Markdown

  languages:
     - de

  categories:

  default_client_route: '/videos/trending'

  is_nsfw: false
  default_nsfw_policy: 'do_not_list'

  customizations:
    javascript: '' # Directly your JavaScript code (without <script> tags). Will be eval at runtime
    css: '' # Directly your CSS code (without <style> tags). Will be injected at runtime
  robots: |
    User-agent: *
    Disallow:
  securitytxt:
    "# If you would like to report a security issue\n# you may report it to:\nContact: https://github.com/Chocobozzz/PeerTube/blob/develop/SECURITY.md\nContact: mailto:"

services:
  twitter:
    username: '@Chocobozzz' # Indicates the Twitter account for the website or platform on which the content was published
    whitelisted: false

followers:
  instance:
    enabled: true
    manual_approval: false

followings:
  instance:
    auto_follow_back:
      enabled: false

    auto_follow_back:
      enabled: false

    auto_follow_index:
      enabled: false
      index_url: ''

theme:
  default: 'default'

broadcast_message:
  enabled: false
  message: '' # Support markdown
  level: 'info' # 'info' | 'warning' | 'error'
  dismissable: false

search:
  remote_uri:
    users: true
    anonymous: false

  search_index:
    enabled: false
    url: ''
    disable_local_search: false
    is_default_search: false
`

/etc/apache2/sites-available/peertube-le-ssl.conf on my Apache WebProxy
`
<IfModule mod_ssl.c>
<VirtualHost *:443>
 ServerName peertube.DOMAIN.TOPLDOMAIN
 ProxyPreserveHost On
 DocumentRoot /var/www/html
 ProxyPass /.well-known !
 ProxyPass / http://peertube.LOCALDOMAIN:80/
 ProxyPassReverse / http://peertube.LOCALDOMAIN:80/

 RewriteEngine on
 RewriteCond %{HTTP:Upgrade} websocket [NC]
 RewriteCond %{HTTP:Connection} upgrade [NC]
 RewriteRule ^/?(.*) "ws://peertube.LOCALDOMAIN:80/$1" [P,L]

Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile /etc/letsencrypt/live/peertube.DOMAIN.TOPLDOMAIN/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/peertube.DOMAIN.TOPLDOMAIN/privkey.pem
</VirtualHost>
</IfModule>
`

Error Messages:

/var/log/nginx/peertube.error.log

`
...
2021/11/16 16:36:31 [crit] 18817#18817: *468 stat() "/var/www/peertube/storage/dev/null" failed (13: Permission denied), client: 10.0.1.30, server: peertube.DOMAIN.TOPLDOMAIN, request: "POST /socket.io/?accessToken=798469d9271fb9f486e098d7095342d8e9431fb0&EIO=4&transport=polling&t=NqfP7tM&sid=ijUhBLi8K2rlryHHAACs HTTP/1.1", host: "peertube.DOMAIN.TOPLDOMAIN", referrer: "https://peertube.DOMAIN.TOPLDOMAIN/86f5e3cc-7e86-4b86-ac38-10368a7407a6"
...
`

Thanks for helping. Peertube rules!

**Comment by Yalman** [comment]
new information:
if i change the storage path in the config from /var/www/peertube/storage/* to /mnt/nfs/peertube/storage the failure persist.
if i remove the symlink and copy the storage folder from nfs mount to the /var/www/peertube/ folder the above described failure is solved.
Maybe this is not a symlink failure, just a nfs problem?

**Comment by Yalman** [comment]
i m glad to find the problem.
chmod o+rx /mnt/nfs/peertube
solved

**Comment by Yalman** [comment]
what are the correct permission and owners for this folder? What is with nginx and his group www-data? Do they need access to the files?

**Comment by SimplyCorbett** [comment]
> what are the correct permission and owners for this folder? What is with nginx and his group www-data? Do they need access to the files?

User/group needs to be peertube in the storage folder. You need to find your peertube user GID/UID and then apply ownership over the NFS share.

Otherwise your issue is either the symlink or a NFS specific issue. You could try bind mounting the directory instead of symlinking.

**Comment by ROBERT-MCDOWELL** [comment]
Bind the directory permently in /etc/fstab and it works. symlink seems the problem
