### ISSUE TITLE
User themes

### ISSUE THREAD

**Issue by KSPAtlas** [Chocobozzz/PeerTube#4547]
**Describe the problem to be solved**
User themes allow users to have custom CSS, allowing users to personalise any instance.

**Describe the solution you would like:**
A text box allowing CSS to be added that overrides the normal CSS.

**Comment by Chocobozzz** [comment]
Hello,

As I said in https://github.com/Chocobozzz/PeerTube/issues/4541, users can already choose themes provided by their administrator. We don't plan to add more customization for users. If you want to update your instance CSS, you can use web browser extensions like [stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/) for example
