### ISSUE TITLE
Possible installation with mysql ?

### ISSUE THREAD

**Issue by Le-Max-De-Culture** [Chocobozzz/PeerTube#4549]
Hello!
I hope taht you are doing well.
Is it possible to install peertube with mysql instead of PostgreSQL ?
Thanks in advance
Cheers
Maxime

**Comment by SimplyCorbett** [comment]
No, it's not possible.

**Comment by Le-Max-De-Culture** [comment]
Thanks you for your answer!

**Comment by AnonymousWebHacker** [comment]
wtf? @Le-Max-De-Culture do you know that postgres is better than myslqp?
