### ISSUE TITLE
Current state & plans for 10k or 100k simulteanous users on live-stream

### ISSUE THREAD

**Issue by lschaupp** [Chocobozzz/PeerTube#4554]
Hey there,

First, peertube looks really awesome. However I have seen in the v3 news that
there is a current limit of simulteanous users for live streams.
Therefore I wanted to ask about the current plans (roadmap) to get into the 10k or even 100k
user range.

Thank you very much

**Comment by Chocobozzz** [comment]
Hello,

> Therefore I wanted to ask about the current plans (roadmap) to get into the 10k or even 100k
user range.

This is not planned and we still miss information about live limitations in peertube. If you have such data, please report it so we can discuss about that.
