### ISSUE TITLE
create-import-video-file-job not working with remote storage

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4555]
**Describe the current behavior**
When using [create-import-video-file-job](https://docs.joinpeertube.org/maintain-tools?id=create-import-video-file-jobjs) while object storage is enabled the video-transcoding job fails due to no such file or directory when the video file has been moved to object storage.

**Steps to reproduce:**

1. Enabled remote storage.
2. Run `npm run create-import-video-file-job ...`
3. Wait until `move-to-object-storage` job has finished.
4. See that the following `video-transcoding` job fails.

**Describe the expected behavior**
`move-to-object-storage` should wait until the transcoding is done.

* PeerTube instance:
  * version: 3.4.1

**Comment by Chocobozzz** [comment]
Hello,

Are you sure `video-transcoding` has been created by your `create-import-video-file-job` command (or by the `move-to-object-storage` job created by it)?

**Comment by kontrollanten** [comment]
Yes. I retried now and now there was only one `video-transcoding` job created, which succeeded. But the `move-to-object-storage` job (which I didn't create manually) failed due to no such file or directory when looking for the 720p m3u8 file.

**Comment by Chocobozzz** [comment]
I'm sorry but I don't see in the code where we run a `video-transcoding` job after a `import-video-file` job

**Comment by kontrollanten** [comment]
Yes, see below. But I just saw that this has been removed since 3.4.1 so I'm closing this issue.

https://github.com/Chocobozzz/PeerTube/blob/3edbafb6377cfb65bca3964d46fa27bc9f813300/server/lib/job-queue/handlers/video-file-import.ts#L19-L42
