### ISSUE TITLE
Youtube heavily throttling peertube

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#4556]
Youtube appears to be heavily throttling peertube.

My current assumption is peertube is using an older yt-dlp binary. The yt-dlp binary released on 11.10 fixes youtube throttling.

If that's not the case then something peertube is doing is causing youtube to throttle it..

Because it's not throttled from the node when I manually use yt-dlp, so they aren't rate limiting my IP.

* PeerTube instance:
  * URL: private
  * version: GIT
  * NodeJS version: 16.10
  * Ffmpeg version: 4.4.1

**Comment by Chocobozzz** [comment]
PeerTube just run a `youtube-dl`/`yt-dlp` shell command, so I don't think youtube can throttle peertube.

Try to run the complete command from your shell (written by peertube in debug logs) because we select a specific format

**Comment by SimplyCorbett** [comment]
Using a random video it appears to max my 1Gbps connection when run from the yt-dlp binary on github releases.

But when downloading with peertube it's stuck at 0.50Mbps.

```
./yt-dlp --force-ipv4 -f "bestvideo[vcodec^=avc1][height=1080]+bestaudio[ext=m4a]/bestvideo[vcodec=av01][vcodec=vp9.2][height=1080]+bestaudio/bestvideo[vcodec^=avc1][height<=1080]+bestaudio[ext=m4a]/bestvideo[vcodec=av01][vcodec=vp9.2]+bestaudio/best[vcodec=av01][vcodec=vp9.2]/best" -o temp.mp4 https://www.youtube.com/watch?v=mLt7JRCS1po
[youtube] mLt7JRCS1po: Downloading webpage
[youtube] mLt7JRCS1po: Downloading android player API JSON
[youtube] mLt7JRCS1po: Downloading player 4c89207b
[info] mLt7JRCS1po: Downloading 1 format(s): 299+140
[download] Destination: temp.f299.mp4
[download] 100% of 235.45MiB in 00:03
[download] Destination: temp.f140.m4a
[download] 100% of 7.77MiB in 00:00
```

**Comment by SimplyCorbett** [comment]
I have seven imports going at the same time and I'm only hitting 3.50Mbps download.

![yt-dl](https://user-images.githubusercontent.com/7935624/142895290-2310063f-0c19-4aaa-951e-b383bffd6ed1.png)
