### ISSUE TITLE
Create Your Own Instance page has script which results in infinite loop, consuming all resources

### ISSUE THREAD

**Issue by trinitroglycerin** [Chocobozzz/PeerTube#4557]
**Parts of the documentation concerned:**

The Create Your Own Instance page: https://docs.joinpeertube.org/#package-create-your-own-instance

Not necessarily an issue with the veracity of the documentation. Visiting this page on Firefox 94.0 (64-bit) on Ubuntu 20.04 causes a script on the page to consume all available resources of Firefox, requiring me to shut down Firefox entirely (not just the tab) to restore functionality. My best guess is that there's an issue with whatever script is rendering the content that is causing an infinite loop. The documentation does not load at all, so this issue also prevents access to that particular page.

This occurs even in private browsing mode with no extensions enabled.

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed

**Comment by trinitroglycerin** [comment]
Unfortunately, it is not. :(

**Comment by Chocobozzz** [comment]
Oup's sorry, it should be correctly fixed by https://framagit.org/framasoft/peertube/documentation/-/commit/9373c2e230ff151cbb3436cf63351d332b2add72 (you may have to clean your cache)

**Comment by trinitroglycerin** [comment]
Yep, can confirm it's sorted after clearing my cache. It's always caching :( Except when it's DNS
