### ISSUE TITLE
Bandwidth spike at end of stream due to rapid retries from all clients

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#4558]
**Describe the current behavior**

I was just tracking down why a full gigabit of traffic showed up on my server suddenly... it looked like a DoS attack. Actually someone was running an unauthorized football stream from my server. But that wasn't even the worst part- the logs show that traffic steadily ramped up as the stream ended, and the pcap was full of clients just checking the m3u8 file fruitlessly.

**Steps to reproduce:**

1. Run a live stream with many viewers, end the broadcast.
2. Capture traffic

**Describe the expected behavior**

Clients should at the very least poll much less frequently once the broadcast has been interrupted; and preferably we would have a better way for live streams to begin and end in a more definite way, for the benefit of both clients and the saved video archives. (See how youtube does it for example, with a timeout so that the broadcast officially ends if the video stream has stopped for more than a couple minutes)

**Additional information**

![image](https://user-images.githubusercontent.com/923812/142920022-c693da66-c107-4f72-8e9f-05847e631108.png)

* PeerTube instance:
  * URL:
  * version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by scanlime** [comment]
As an update: I wasn't sure whether these clients were even using the peertube embed or using the hls stream directly, and I saw no evidence that these clients ever interacted with peertube's UI- they were just loading the stream m3u8 in some other player.

If the server ends the stream by removing the m3u8 file, that would presumably help both our client and arbitrary other HLS players notice that the stream is in fact gone.

**Comment by Chocobozzz** [comment]
I'm sorry but I can't reproduce: ffmpeg correctly ends the playlists using `#EXT-X-ENDLIST` at the end of the file and the peertube client does not check m3u8 file endlessly when it saws it

**Comment by scanlime** [comment]
Thanks for taking a look. Would it not make sense to remove the m3u8 entirely, a few minutes after the stream stops?

**Comment by Chocobozzz** [comment]
> Thanks for taking a look. Would it not make sense to remove the m3u8 entirely, a few minutes after the stream stops?

Yes, we remove live files [5 minutes](https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/constants.ts#L671) after the live ends (https://github.com/Chocobozzz/PeerTube/blob/98846837ebb6bfbed3866eee5258946b35769651/server/lib/live/live-manager.ts#L378)
