### ISSUE TITLE
Remove stale transcode jobs - how to?

### ISSUE THREAD

**Issue by M-Stenzel** [Chocobozzz/PeerTube#4559]
Hi team, 

this is **not a bug report**, but a documentation request/question:

Following scenario:

After a physical server reboot the "storage" directory was not mounted properly at startup and because of that there seem to be some data inconsistencies which I face now.

Peertube server (latest version) runs smoothly, however, transcoding new video imports stopped.
I tried to investigate and found this error log (every other minute).

{"err":"Error: ENOENT: no such file or directory, stat '/mnt/volume-hel1-3/peertube/storage/streaming-playlists/hls/a94e5fd5-021d-4ba4-ae86-6e73e47a747b/0.m3u8'","level":"error","message":"Error in controller.","label":"tube.xy-space.de:443","timestamp":"2021-11-23T18:25:57.494Z"}

**This file indeed does not exist** (any longer), most probably because I removed it by mounting the correct "storage" directory AFTER peertube server started. I for sure cannot restore this file.

**Easiest solution to the problem would be to delete these stale transcode jobs but I do not know how.**

It seems that as long the oldest transcode job in the queue is not finished yet successfully, all the new jobs will be put on hold.

Thanks for your help, time, dedication, and ... clarification,

Martin.

P. S. Running "prune-storage.js" and deleting all the suggested files did not help in my case.

**Comment by SimplyCorbett** [comment]
On the GIT version you can manually delete videos from the admins end. Find which video a94e5fd5-021d-4ba4-ae86-6e73e47a747b belongs to and remove it, then restart peertube.

On the stable release you have to go into in my library - videos on the user in question and then find the correct video, remove and restart peertube. If you can't login as the user you can't remove the video from the GUI at least.

As a last ditch resort you could create the missing file by hand and hope for the best.

**Comment by SimplyCorbett** [comment]
Side note, you can just unmount storage/peertube, grab the file, remount storage/peertube and move it to the correct directory.

**Comment by Chocobozzz** [comment]
Hello,

If I understand well, you could like to run again the failed transcoded jobs. This is not possible, but you can re create these transcoding jobs using https://docs.joinpeertube.org/maintain-tools?id=create-transcoding-jobjs

As @SimplyCorbett said, in the next version you'll be able to run transcoding jobs from the web interface.
