### ISSUE TITLE
if download failed, it will block here

### ISSUE THREAD

**Issue by memoryboxes** [Chocobozzz/PeerTube#456]
https://github.com/Chocobozzz/PeerTube/blob/f209b32afaffbb8b93c265525ebde182ab66c37a/server/tools/import-videos.ts#L107

**fix:**

```
if (err) {
    console.error(err)
    return res()
}
```

**Comment by Chocobozzz** [comment]
Nice catch @memoryboxes! Maybe you would make a PR?

**Comment by memoryboxes** [comment]
OK, I'll PR later.
