### ISSUE TITLE
manifest for chocobozzz/peertube:production-bullseye not found

### ISSUE THREAD

**Issue by mohseninew24** [Chocobozzz/PeerTube#4561]
Hi,

I want to deploy PeerTube on ubuntu 18.0.4 . I have done the following steps:
1- git clone https://github.com/Chocobozzz/PeerTube.git
2- curl  docker-compose.yml , then ipv4_address and subnet were changed based on server static IP
3- curl  .env and some parameters were changed
4- after enter the "  docker-compose up " , the following error was shown:

ERROR: manifest for chocobozzz/peertube:production-bullseye not found: manifest unknown: manifest unknown

**Comment by Chocobozzz** [comment]
Hi,

Please try `curl https://raw.githubusercontent.com/chocobozzz/PeerTube/master/support/docker/production/docker-compose.yml > docker-compose.yml` instead

**Comment by mohseninew24** [comment]
Hi,

Thanks for your help. 

I have tried the "docker-compose.yml" file you mentioned in your last reply but the following error was shown: 

ERROR: for peertube_webserver_1  Cannot create container for service webserver: invalid mount config for type "bind": bind source path does not exist: /root/peertube/PeerTube/docker-volume/nginx/peertube

ERROR: for webserver  Cannot create container for service webserver: invalid mount config for type "bind": bind source path does not exist: /root/peertube/PeerTube/docker-volume/nginx/peertube

**Comment by Chocobozzz** [comment]
Please follow the guide, it seems you missed that step: https://docs.joinpeertube.org/install-docker?id=webserver
