### ISSUE TITLE
Video uploads broken after upgrade

### ISSUE THREAD

**Issue by LasersAreGreat** [Chocobozzz/PeerTube#4564]
After an automatic upgrade from  v3.3.0 to v3.4.1, video playback works fine but clicking on "upload" results in the page never loading and the browser window freezing.  I've tried this in Chrome and Firefox on two different computers with the same result. I'm not seeing anything in the error log.  I tried manually running the upgrade again to make sure the dependencies were all met and they seem to have been met.

I love peertube and use my instance rather heavily, so I'm rather concerned. Any help would be appreciated. I don't see anything in the error logs that point me towards a solution, but I am happy to run any commands or check any files you can suggest. Thank you.

**Comment by SimplyCorbett** [comment]
Have you cleared/flushed your redis cache? How about nginx cache if enabled?

**Comment by LasersAreGreat** [comment]
> Have you cleared/flushed your redis cache? How about nginx cache if enabled?

Yes, I did. I even tried a few reboots too.

**Comment by LasersAreGreat** [comment]
Not sure why, but disabling the two plugins I had (ungamify and menu bar links) fixed the issue.
