### ISSUE TITLE
Translation problem of secondary development based on PeerTube

### ISSUE THREAD

**Issue by VWWL** [Chocobozzz/PeerTube#4569]
Dear,
I have read your official documents and found that you use Weblate to do translation integration. I hope to develop secondary from PeerTube, so there will be a lot of fields defined by us. I want these fields have i18N multi-language support. Obviously, it is not practical for our own custom fields to be transferred to your Weblate platform through PR. Is there any good solution?
Best, VWWL

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I don't understand.

**Comment by VWWL** [comment]
I used the PeerTube framework for secondary development. I added a string and appended i18n to its HTML tag. But when I run npm i18n:update, it won't be automatically translated.

**Comment by VWWL** [comment]
I want it to be translated automatically. Or manually add the translation result and let PeerTube translate according to the translation result.

**Comment by VWWL** [comment]
@Chocobozzz
