### ISSUE TITLE
Transcoding "Error: Video not found" but does exist

### ISSUE THREAD

**Issue by mj-saunders** [Chocobozzz/PeerTube#4571]
## The problem
When running `create-transcoding-job`, many `uuid`'s returned `"Error: Video not found"`. Upon checking though, these videos are in fact present in our s3 bucket `videos/` directory.  
From a brief dig into `dist/scripts/create-transcoding-job.js` and `dist/server/models/video/video.js`, I have a small suspicion that the `postgres` database may not know about the files, but I've no idea why, _if_ that is the case.

The videos that were not transcoded, while they exist in the s3 buckets `videos/`, and can be found on the front end, they no longer play back at all. 

After reading what follows, if any further detail is needed, please ask.

## Background
There are perhaps other issues at play, so I'll try to give a brief background.

- Have been migrating videos from youtube, using `peertube-import-videos`; seemingly successfully
- Noticed problems with playback. Massive lag to start, then choppy playback
- Determined this may be due to the [ffmpeg hls bug](https://github.com/Chocobozzz/PeerTube/issues/3990)
  - Turns out I had neglected the `CHANGELOG` from previous update and have thus been transcoding 10's of videos with buggy hls
- Decided to re-do all hls as I have no way of knowing which videos were affected
- Removed all sub-directories from `streaming-playback/hls/` in the s3 bucket
  - Note: we use s3 storage from wasabi, with public read access to directly serve from there
- Temporarily fuse-mounted the s3 bucket, so I could then run the `bash` command the shortly follows
  - Note: soft-linked (`ln -s`) the mounted s3 `videos/` to the local `storage/videos/` so that the transcoder could find things
- Ran this to rebuild the hls files:
  - `for uuid in $(ls ~/s3-storage/videos/ | cut -c -36 | sort -d | uniq) ; do echo $uuid ; NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run create-transcoding-job -- --generate-hls -v $uuid ; done`
- The transcoding _partly_ worked
  - Some hls directories were created, and mostly moved over automatically to the s3 bucket
  - **Many videos were not found and not processed - this is the issue being raised herein**
  - 21 directories remain in local `/storage/streaming-playlists/hls` and were not moved over to the s3 bucket
    - **This is a separate issue I do not understand**

## Our setup
During the above process, I updated `peertube` and `ffmpeg` so that the current setup should no longer produce buggy video going forward (assuming the problem was what I think)
```
peertube 3.4.1
Arch Linux
Basic installation (non-docker)
wasabi s3 for storage (now using native object storage)

$> ffmpeg -version | head -n1
ffmpeg version n4.4.1 Copyright (c) 2000-2021 the FFmpeg developers

$> uname -srmo
Linux 5.15.4-arch1-1 x86_64 GNU/Linux
```

I updated the `nginx` config as per [here](https://github.com/Chocobozzz/PeerTube/blob/5f59cf077fd9f9c0c91c7bb56efbfd5db103bff2/support/nginx/peertube#L235-L242).  
Our current config can be seen [here](https://termbin.com/i1dm). A couple of sections are commented out as they cause breakage, but they are not the priority at the moment.

I am also wondering if the `nginx` config could be affecting download rates - playback directly from the wasabi url (taken from browser inspector while playing from peertube) is smooth as expected, but between 15 and 50KBps on rough average from the peertube player.  
However, this is a separate issue I guess.

**Comment by SimplyCorbett** [comment]
```

Noticed problems with playback. Massive lag to start, then choppy playback
Determined this may be due to the ffmpeg hls bug

    Turns out I had neglected the CHANGELOG from previous update and have thus been transcoding 10's of videos with buggy hls
```

The bug I reported made videos unplayable. Choppy playback is not part of the bug.

My guess is you're seeing issues with wasabi.

**Comment by mj-saunders** [comment]
@SimplyCorbett Thanks for the clarification.
Any idea how I might go about determining that the issue is with wasabi, or at least with how peertube is communicating with wasabi?

I originally used the "old method", while now it's using "native object storage".
I guess I'll start with reverting and see if it makes a difference.

**Comment by SimplyCorbett** [comment]
> @SimplyCorbett Thanks for the clarification. Any idea how I might go about determining that the issue is with wasabi, or at least with how peertube is communicating with wasabi?
> 
> I originally used the "old method", while now it's using "native object storage". I guess I'll start with reverting and see if it makes a difference.

I haven't personally used S3 with peertube so I don't know if the video is going through the server to the end user or if the video is going directly to the end user.

If it's going through the server first you need to make sure the sysctl settings were configured correctly.

But I have experience with wasabi s3 on nextcloud and let me tell you wasabi is bottom of the barrel in my experience. They're great and cheap but unreliable. Not something I'd be streaming video with in any case.

When I say unplayable I mean unplayable. Loading circle that never went away.

**Comment by mj-saunders** [comment]
@SimplyCorbett The video should be streaming directly from wasabi, not via the peertube server.
According to my browser inspector, it appears to agree; packets stream directly from the wasabi url.
If the packets were passing through the server, would the wasabi url be preserved?

When I copy one of the fragment links that the browser network stats show, and paste directly in a browser, it streams perfectly fine; so though wasabi may be unreliable, it's not the source of this particular problem - not directly at least.

> When I say unplayable I mean unplayable. Loading circle that never went away.
Ok cool, thanks.

**Comment by SimplyCorbett** [comment]
I'm not going to be much help here but since peertube is P2P and acts as the tracker I'd assume the video is streaming through the peertube server.

I could be wrong. When you are streaming the video through peertube does the server have upload/download that would be consistent with streaming video?

If the video is streaming through your server:

1) Make sure your server is downloading the video smoothly through wasabi and that there isn't a routing issue.

2) Make sure the sysctl settings were applied correctly.

3) Check to see if there is a routing issue between your server and the end user. Any packet loss??

**Comment by SimplyCorbett** [comment]
Actually if you could include the URL of the peertube instance so I can see the issue firsthand that would be nice. I know that's not always possible for privacy reasons though.

**Comment by mj-saunders** [comment]
Should be fine. https://visionon.tv/
You'll need to set a custom cookie at the moment though. key: 'dev', value: 'maintainer'

**Comment by SimplyCorbett** [comment]
I'm able to stream https://visionon.tv/w/ppsx3FMVyYyDtjxa6f4WX4 @ 1060p60 with no issue and am hitting 50Mbps download.

This doesn't fix your missing videos, but as far as streaming goes it seems to work fine.

**Comment by mj-saunders** [comment]
That's a non-local video.
Try this one: https://visionon.tv/w/6gt4W1e6BwNRmEPUj4M1nM

Note, this is one of the re-transcoded videos and they are running a little better than before...in that they don't take a couple of mintues to start playing. I still experience choppy playback though via our instance.
This is the direct bucket link, copied from the browser inspector, which streams fine for me: https://omn-peertube.s3.eu-central-1.wasabisys.com/videos/2aa687ed-087c-41ad-a57c-20e99bc65ee7-720.mp4

As for the missing files, I'm still stumped.

**Comment by mj-saunders** [comment]
> I'm not going to be much help here but since peertube is P2P and acts as the tracker I'd assume the video is streaming through the peertube server.
> 
> I could be wrong. When you are streaming the video through peertube does the server have upload/download that would be consistent with streaming video?
> 
> If the video is streaming through your server:
> 
> 1. Make sure your server is downloading the video smoothly through wasabi and that there isn't a routing issue.
> 2. Make sure the sysctl settings were applied correctly.
> 3. Check to see if there is a routing issue between your server and the end user. Any packet loss??

Just saw this, sorry. Thank you.
I will have to do some digging. I'm still learning and not sure of the best ways to do as you suggest, but I have a couple ideas, and will have a read around to see what I can determine. (hopefully `nethogs` will suffice in part)

- Not sure how best to check if there might be a routing issue
- I'll read up on `sysctl`
- How to check for packet loss? From client or server side? Using something like wireshark, or simpler?

Even if you can just suggest a handful of tools, I'm happy to go do the research on usage.
Thanks again for helping out.

**Comment by SimplyCorbett** [comment]
Yeah, the problem is wasabi.

For example you can download this file just fine - https://omn-peertube.s3.eu-central-1.wasabisys.com/videos/5a51d7d3-c3b1-4726-bb60-d4368f24651e-720.mp4

But when you stream it through peertube it opens a bunch of seek/connections that refresh every .5 seconds or so and wasabi just doesn't seem to care about that. Straight http downloads are fine, but the constant connections/parts are causing wasabi to barf all over itself.

Unfortunately the multiple connections/parts downloaded are what makes peertube peertube. It's the P2P aspect. You are likely going to need to change your S3 provider to fix this.

**Comment by SimplyCorbett** [comment]
![S3](https://user-images.githubusercontent.com/7935624/143626391-25251396-61e6-411b-ab77-2af16938251f.png)

**Comment by mj-saunders** [comment]
Well that sucks if it's the case.
Any idea why it worked fine before?
No worries if not. I'll test a little more, and resign myself to change if I must.


> ![S3](https://user-images.githubusercontent.com/7935624/143626391-25251396-61e6-411b-ab77-2af16938251f.png)

What's unusual about this image? Maybe I'm missing something, but it appears to be doing what I would expect.
Well, other than the time between requests is long.
But isn't that a server issue rather than a wasabi one?

**Comment by SimplyCorbett** [comment]
> What's unusual about this image? Maybe I'm missing something, but it appears to be doing what I would expect.

Nothing, that's how peertube is supposed to work. The problem is wasabi either can't respond to the requests in time or are rate limiting the connection. I've seen upwards of 2000ms between requests which is why your video stops playing at times.

**Comment by mj-saunders** [comment]
Thanks again; will look at what other options I have.

Now, just for solving the issue at hand. The missing videos that aren't missing.

**Comment by SimplyCorbett** [comment]
As an example this is what I see on my LAN instance.

The response time is just too long. Compare the two pictures on the right side.

![S32](https://user-images.githubusercontent.com/7935624/143627098-afab9c1c-35c5-4283-b5fa-ae359ad6e6b8.png)

**Comment by mj-saunders** [comment]
Noted. I just don't understand what's changed. Will reach out to wasabi for confirmation.
Adn will test the "old method" tomorrow on the off-chance.

**Comment by SimplyCorbett** [comment]
@pingiun Any ideas? My assumption is the amount of requests made by peertube is causing wasabi to rate limit the connection. Perhaps increasing the chunk size would fix this?

Could be way off base though, I'm not that familiar with S3 on peertube.

**Comment by pingiun** [comment]
> @pingiun Any ideas? My assumption is the amount of requests made by peertube is causing wasabi to rate limit the connection. Perhaps increasing the chunk size would fix this?
> 
> Could be way off base though, I'm not that familiar with S3 on peertube.

When I tested the linked video by mj-saunders just now it worked fine. Even when skipping around everything loaded very quickly. Might it be the case that wasabi was having temporary issues?

Increasing the chunk size could help if the problem is rate limiting. However I'm not familiar with this, it's probably an option somewhere in the player we use.

**Comment by mj-saunders** [comment]
Thanks @pinguin.
I'm still experiencing the lag from where I am.

Tested the stream here: https://hls-js.netlify.app/demo/
With this URI: https://s3.eu-central-1.wasabisys.com/omn-peertube/streaming-playlists/hls/2aa687ed-087c-41ad-a57c-20e99bc65ee7/b2944642-811e-4557-aeae-2592a16e500f-720.m3u8

Rather than constant `16K` chunks (which I see when using our peertube instance), it was fetching roughly 600K to 1.2M chunks on average, and playback was smooth until the last few seconds where it had 3 `buffer stall error`s.

So maybe it is rate limiting.

What is determining this size?
I'm trying to find out myself at the same time.

**Comment by mj-saunders** [comment]
To come back to the original posted issue (though I still need to figure out what's been discussed above).

I just manually queried the postgres database, and can confirm that the videos being rejected by `create-transcoding-job` with `Error: Video not found` are in fact in the database. And the files exist in `storage`.

Looks like I'll need to dig into what the transcoding script is actually doing.

**Comment by SimplyCorbett** [comment]
I would just try this with another S3 provider and see if you can replicate the issue. If you can it's a bug that needs looking into but if you can't its a wasabi issue.

**Comment by mj-saunders** [comment]
Regarding the lag issue, that's definitely a fair suggestion. Thanks

**Comment by mj-saunders** [comment]
I wrote I small script to take all the hashes (uuid's) that failed `create-transcoding-job`, and extract some useful info from the `postgres` db - video id, name, creation time.

So I can at least confirm that all the videos that failed are at least present in `storage` and the database is aware of them.

I'm not much closer, but maybe getting somewhere with figuring out why `create-transcoding-job` believes the files don't exist.

**Comment by mj-saunders** [comment]
For now I chose to delete all the offending files that failed to be found for transcode.

It turns out that all of the offenders were files that had just been imported into our instance from youtube, via `peertube-import-videos`.

Is there perhaps something lacking in the database when files are imported like this instead of directly uploaded as normal, that would cause these videos to not be found by `create-transcoding-job`?

**Comment by mj-saunders** [comment]
Can also confirm wasabi is not rate limiting. More digging to be done

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but you made too much manual tasks on your filesystem/s3 to understand if there is a peertube bug or not. I suggest to continue the discussion on https://framacolibri.org/c/peertube/38

If you find a peertube bug, please create a dedicated issue with the steps to reproduce.

**Comment by mj-saunders** [comment]
@Chocobozzz Unfortunately the discussion on this issue also got sidetracked into a separate issue mentioned in the original post, but that was not the intended focus.

I'll look at opening a topic at `framacolibri` as suggested, thanks.

Regarding the original issue - the transcoding error bash loop - is that what you're referring to by making "too much manual tasks"?
I would have thought the little `bash for` loop was only running the script one `uuid` at a time.
As such, I don't understand the problem.

Or do you mean because I manually ran `peertube-import-videos`, then removed (seemingly) bad `hls` files, and then ran `create-transcoding-job`?

If I can figure out how to make this reproducable, I will file a more specific bug report.

Until then, is there really no one who can suggest perhaps why `"Error: Video not found"` would be raised, when as far as I can determine, the files clearly exist?

I don't mind digging myself, as I imagine should be clear, but I'm new to the codebase.
