### ISSUE TITLE
CSS problem on the live waiting screen, affecting some plugins

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4572]
**Describe the current behavior**

I'm currently working on the chating plugin https://github.com/JohnXLivingston/peertube-plugin-livechat , and I noticed a visual glitch with some window sizes. 
It happens only on the screen before of after lives, when the chat is open. See this screenshot:
![image](https://user-images.githubusercontent.com/38844060/143597731-3550dd7b-b12d-448b-ab36-376316581ce3.png)

The chat is truncated, and a horizontal scrollbar appears.
When scrolling:
![image](https://user-images.githubusercontent.com/38844060/143597848-76f6a1ee-082d-40b9-86df-dfeafbce0bac.png)

When not using the chat plugin, there is also a bug, but it is more difficult to notice:
![image](https://user-images.githubusercontent.com/38844060/143598015-60987f0e-3ce2-4290-8c0d-36485fab8581.png)
![image](https://user-images.githubusercontent.com/38844060/143598044-dbe8d48c-414b-4e54-a636-56533061bc58.png)

I think this is because of the placeholder image CSS:
![image](https://user-images.githubusercontent.com/38844060/143598211-75269c90-2c78-4808-bf63-a9afa88274a7.png)
There is no width. And no flex-shrink.

**Steps to reproduce:**

1. Create a new live, but don't start it
2. Go on the page
3. Shrink the browser horizontal until the horizontal scrollbar appears

**Describe the expected behavior**

The place holder image should shrink as the video does when the live is started.

**Additional information**

* PeerTube instance:
  * URL: -
  * version: 3.4.1
  * NodeJS version: -
  * Ffmpeg version: -

* Browser name, version and platforms on which you could reproduce the bug: Firefox dev edition, Firefox stable version

**Comment by Chocobozzz** [comment]
Can you tell me if `max-width: 100%` on `.placeholder-image` fixes your issue?

**Comment by JohnXLivingston** [comment]
The scrollbar disapears, but the image is squashed:
![image](https://user-images.githubusercontent.com/38844060/143611326-286e2651-3e21-49da-aafb-714477e5b866.png)

**Comment by Chocobozzz** [comment]
Okay thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/71ab0c07ccfe6a2b2ef5899bab53b4e983265fed

**Comment by JohnXLivingston** [comment]
Yes it works! Thanks.
