### ISSUE TITLE
How to deploy peerbube in the docker of synology? How to configure related parameters?

### ISSUE THREAD

**Issue by tiggerik** [Chocobozzz/PeerTube#4574]
**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Additional information**

* PeerTube instance:
  * version:
  * NodeJS version:
  * Ffmpeg version:
  * Redis version:
  * PostgreSQL version:

**Comment by SimplyCorbett** [comment]
Hi,

Please read the docker tutorial here - https://docs.joinpeertube.org/install-docker

If synology doesn't allow you to do any of that you have to contact their support team.
