### ISSUE TITLE
The playlist thumbnail is cropped

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#4577]
**Describe the current behavior**
If the playlist description is very long, then the playlist thumbnail is cropped and narrowed. It looks really bad.
This can be seen in the screenshot.

![pl](https://user-images.githubusercontent.com/11453567/143814630-56b04368-4d65-46b9-b73d-71053a7b5895.png)

![pl2](https://user-images.githubusercontent.com/11453567/143814733-594eca52-68a7-4c4c-98ff-d9d443742ea4.png)

**Steps to reproduce:**

1. Edit playlist, write long description text
2. The playlist image is cropped.

**Describe the expected behavior**
Playlist image must be standard

**Additional information**
I want to propose to limit the number of characters to display in the playlist description. If the description text is very long, then display a short description, but hide the rest of the text and add the ability to expand the full description, but in this case, the previous playlist should go lower in the general list.

* PeerTube instance:
  * URL: https://video.ustim.ru
  * version: 3.4.1-nightly-2021-11-27

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/247bbe29145c66a1c4ff61ce5dab70fec51a29aa
