### ISSUE TITLE
Encode quotes in  <meta name="description" content="" />

### ISSUE THREAD

**Issue by Findus23** [Chocobozzz/PeerTube#4579]
**Describe the current behavior**

When the description of a video contains quotes (`"`), the HTML of the video page is invalid as it prints the quotes verbatim.

**Steps to reproduce:**

1. create video with quotes in description (e.g. https://video.matomocamp.org/w/10ad981e-b0a5-43bd-98f9-e6bfa235c204)
2. check HTML of video page
3. notice invalid HTML (see syntax highlighting)
```html
    <meta name="description" content="UserFeedback is our form builder plugin for Matomo and in this session I will demo its functionality., With UserFeedback you can:
Build forms with the included form builder and customize fields and values.
After creating a form, you can display this form anywhere on your website (as long as you use Matomos Tag Manager).
You can also customize how to display the forms.
We have built in support for:

Overlay display
Feedback button
Raw (inline)

It is also easy to add your custom styling to the forms
After publishing a form to your site, feedback data will be collected in Matomo and you can also use Matomos "Segments" to filter down your results.
by Tomas Persson
View in Schedule: https://schedule.matomocamp.org/matomocamp-2021/talk/G98E3P/
Slides: https://schedule.matomocamp.org/media/matomocamp-2021/submissions/G98E3P/resources/Introduction_to_the__Matomo_User_Feedback___7mwlMHg.pdf
Audio-only: https://video.matomocamp.org/raw/User Feedback/output.opus
High-Quality Video: https://video.matomocamp.org/raw/User Feedback/output.mp4
Help improve the subtitles: https://github.com/MatomoCamp/recording-subtitles/blob/main/User Feedback/Project.kdenlive.srt" />
```

**Describe the expected behavior**

**Additional information**

* PeerTube instance:
  * URL: https://video.matomocamp.org/
  * version: 3.4.1
  * NodeJS version: -
  * Ffmpeg version: -

**Comment by SimplyCorbett** [comment]
I don't see that on the example video you provided. Seems okay to me! Using firefox on windows.

**Comment by Findus23** [comment]
Just to make this easier reproducible:
```bash
curl https://video.matomocamp.org/w/10ad981e-b0a5-43bd-98f9-e6bfa235c204 -s | sed -n '27,44p'
```
prints out the same lines as the code block above for me.

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/55cb8bc73c259cb8e41c913aacdc3087c7421049
