### ISSUE TITLE
Treat “unlisted” Mastodon replies as valid comments

### ISSUE THREAD

**Issue by ThibG** [Chocobozzz/PeerTube#458]
* **What is the expected behaviour?**

“Unlisted” (=public but does not appear in public timelines) replies from Mastodon are ignored by PeerTube.

* **What do you see instead?**

“Unlisted” replies should appear as comments.

The check is performed here:
https://github.com/Chocobozzz/PeerTube/blob/develop/server/helpers/custom-validators/activitypub/video-comments.ts#L19

It should also check for “cc” field of the activity.

**Comment by Chocobozzz** [comment]
Thanks @ThibG! https://github.com/Chocobozzz/PeerTube/commit/20760d9160e09bb4efaddffb331395f8d6c3c59d
