### ISSUE TITLE
create sitemap.xml

### ISSUE THREAD

**Issue by Findus23** [Chocobozzz/PeerTube#4580]
**Describe the problem to be solved**

It would make it a bit easier for search engines to crawl instances (especially if they have only public videos about one topic) if peertube could create a sitemap.xml.
Of course using the `/api/v1/accounts/user/videos` endpoint makes it not that hard to create the sitemap oneself (e.g. attached python script), but it would simplify things if Peertube could do this.

**Describe the solution you would like:**

Peertube would create a sitemap at the `https://peertube.example/sitemap.xml` endpoint.

**Describe alternatives you have considered**  

<details>
<summary>peertube-sitemap.py</summary>

```python
from dataclasses import dataclass

import requests
from jinja2 import Template


@dataclass
class Page:
    url: str
    last_modified: str


baseurl = "https://video.matomocamp.org"

r = requests.get(baseurl + "/api/v1/videos?count=100")
r.raise_for_status()

pages = []
for page in r.json()["data"]:
    pages.append(Page(
        url=baseurl + "/w/" + page["uuid"],
        last_modified=page["updatedAt"]
    ))

sitemap_template = '''<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    {% for page in pages %}
    <url>
        <loc>{{page.url}}</loc>
        <lastmod>{{page.last_modified}}</lastmod>
    </url>
    {% endfor %}
</urlset>'''

template = Template(sitemap_template)
sitemap_output = template.render(pages=pages)
with open("peertube-sitemap.xml", "w") as f:
    f.write(sitemap_output)
```
</details>

**Comment by Alterak** [comment]
> **Describe the problem to be solved**
> 
> It would make it a bit easier for search engines to crawl instances (especially if they have only public videos about one topic) if peertube could create a sitemap.xml. Of course using the `/api/v1/accounts/user/videos` endpoint makes it not that hard to create the sitemap oneself (e.g. attached python script), but it would simplify things if Peertube could do this.
> 
> **Describe the solution you would like:**
> 
> Peertube would create a sitemap at the `https://peertube.example/sitemap.xml` endpoint.
> 
> **Describe alternatives you have considered**
> 
> peertube-sitemap.py

I completely agree with you. I also wanted to ask the developers to add such functionality.

**Comment by Chocobozzz** [comment]
PeerTube already has a sitemap: https://peertube2.cpy.re/sitemap.xml

**Comment by Findus23** [comment]
Okay, I'm really confused as to what went wrong here. I guess I tested multiple software at the same time, misremembered the results, didn't find any GitHub issue for it and assumed it was missing.

Sorry for the interruption.
