### ISSUE TITLE
Dislike counter feature that was removed from YouTube

### ISSUE THREAD

**Issue by natewrench** [Chocobozzz/PeerTube#4582]
**Describe the problem to be solved**
Implement public dislikes counter

I have an issue when a video is so bad that I can't tell if the community finds it useful or not of the bat looking at the hearts or like reading the comments
**Describe the solution you would like:**
I would like an anti heart logo for dislike and a number counter

I want peertube to become what old YouTube use to be a 5 star rating system and like dislike counters again
**Describe alternatives you have considered**  
Dissenter like plugin

**Comment by Chocobozzz** [comment]
We already have a dislike counter, that admins can disable using plugins.
