### ISSUE TITLE
Running HLS transcoding for old videos generates a publishing notification

### ISSUE THREAD

**Issue by tcitworld** [Chocobozzz/PeerTube#4583]
**Steps to reproduce:**

1. Run HLS transcoding from admin panel for a video that only had webtorrent files
2. Wait for the transcoding to finish
3. The user (which is the administrator) gets a notification that the video was published, but it already was

**Describe the expected behavior**
No need for notifications. Regular users should definitely not get these notifications in this case.

* PeerTube instance:
  * version: 4.0.0-rc.1

EDIT: It seems not all jobs generate a notification ?

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1da843eeac58ccad4fd5bc68606551004d7dbb7a
