### ISSUE TITLE
Customize About page

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4586]
**Describe the problem to be solved**
Currently the about page has a lot of information, which in some cases isn't relevant and may confuse some users.

**Describe the solution you would like:**
Customize the information shown at the about page. Possibility to hide:
* _Statistics_ section
* _Features_ section
* _Terms_ section
* _Who we are_ section
* Group headers (Administrators and sustainability, etc)
* _About PeerTube_ page 
* _Network_ page

**Describe alternatives you have considered**  
Hiding with CSS is possible, but may break with upgrades, and also won't totally hide the About PT and Network pages.

Another alternative is to add a _About page_ section in the admin interface. There it could be possible to enable/disable these elements with checkboxes. It would also make it possible to customize the about page with markdown. 

Related to #3560

**Comment by Chocobozzz** [comment]
Hello,

We can add plugin selector (introduce in v4: https://docs.joinpeertube.org/contribute-plugins?id=plugin-selector-on-html-elements) so you can easily hide sections you want.
