### ISSUE TITLE
Allow multiple users to manage a channel

### ISSUE THREAD

**Issue by ranjithrajv** [Chocobozzz/PeerTube#4590]
**Describe the problem to be solved**
We have opened our orgnaisation account in a peertube instance. This channel needs to be managed by multiple users in the organisation.

**Describe the solution you would like:**
Add a feature to allow multiple users to manage a channel. 

**Describe alternatives you have considered**

**Comment by kontrollanten** [comment]
Hi! This is a duplicate of #699
