### ISSUE TITLE
Peertube with Minio S3

### ISSUE THREAD

**Issue by bbm3h14aku** [Chocobozzz/PeerTube#4596]
Upload Content should move into Minio S3 Buckets, but nothing happend. Under the Video, in Peertube Interface, there's still the Infomration that the Video is moving on external Storage.  

S3 works, i've tested it via the Minio CLI, its possible to copy files, create buckets etc. 

**Additional information**

* PeerTube instance:
  * version: 3.4.1

**Comment by kontrollanten** [comment]
Do you get any message when you expand the job in the web interface (Admin > System > Job)? You can also change to verbose logging and check the logs to see if you can find any message.

**Comment by bbm3h14aku** [comment]
Last entry in the Logs was created at 11/30. 

Log Message: 
Job: 5 Type: move-to-object-storage Processed on Nov 30, 2021, 10:41:00 PM Finished on Nov 30, 2021, 10:41:00 PM
--
{   "videoUUID": "xxxxxxx-xxx-xxx-xxx-xxxxxxx",   "isNewVideo": true }
CredentialsProviderError: Could not load credentials from any providers     at providers (/app/node_modules/@aws-sdk/credential-provider-node/dist/cjs/index.js:59:19)     at /app/node_modules/@aws-sdk/property-provider/dist/cjs/chain.js:20:28     at runMicrotasks (<anonymous>)     at processTicksAndRejections (internal/process/task_queues.js:97:5)     at async SignatureV4.credentialProvider (/app/node_modules/@aws-sdk/property-provider/dist/cjs/memoize.js:20:24)     at async SignatureV4.signRequest (/app/node_modules/@aws-sdk/signature-v4/dist/cjs/SignatureV4.js:84:29)     at async /app/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:13:18     at async StandardRetryStrategy.retry (/app/node_modules/@aws-sdk/middleware-retry/dist/cjs/StandardRetryStrategy.js:51:46)     at async /app/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
 
I‘ve published the credentials via .env to the docker container

**Comment by Chocobozzz** [comment]
> I‘ve published the credentials via .env to the docker container

What env did you use?

**Comment by bbm3h14aku** [comment]
We are working in a docker environment.

**Comment by Chocobozzz** [comment]
I mean what `.env` keys  :)

**Comment by bbm3h14aku** [comment]
Yeah, that make more sense ^^`

We pass AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY or did you need a full dump of our env?

**Comment by Chocobozzz** [comment]
No I think it's fine. Do you also have an `AWS_PROFILE` env?

If no, try to add debug logs in `/app/node_modules/@aws-sdk/credential-provider-node/dist/cjs/index.js`

**Comment by bbm3h14aku** [comment]
no i didn't have this one set.

Okay, i will give them a try

**Comment by bbm3h14aku** [comment]
Sorry for my late answer, i've tried it out. We haven't an AWS_PROFILE env. 

I've enabled an loggigng option for our parsed options. But since 11/30 there wasn't a new try to push the data into bucket... 

S3 is still active and it's possible to push/pull data using the cli

**Comment by Chocobozzz** [comment]
>  But since 11/30 there wasn't a new try to push the data into bucket...

Can you try to upload a private video to test the log you added?
