### ISSUE TITLE
Give admins access to edit channels

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4598]
**Describe the problem to be solved**
We've some users that needs help with customizing their video channels. Currently there's not possible for an admin to edit someone else's video channel.

**Describe the solution you would like:**
Give the administrator access to edit all video channels.

**Describe alternatives you have considered**  
Same solution as for user accounts; add a dropdown menu to the right of the video channel name.

**Comment by Alterak** [comment]
I believe that administrators should have access not only to all channels, but also to edit account descriptions. A lot of bots are registered (perhaps they are not bots), which have only one link in the description of the account or channel. As an administrator, I want to be able to edit this description and just delete the link.

**Comment by andrew712-1** [comment]
The owner though should receive a notification if/when such an action occurs.
