### ISSUE TITLE
Ability to install a plugin alpha/beta version from npm with the CLI

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4600]
**Describe the problem to be solved**

It would be nice to be able to install plugins alpha or beta versions from NPM.

It is possible to manually install them with the CLI (command `plugins install --path ...`), but the process is not consistent with a NPM installation. Yarn is not handling installation consistently between the 2 methods, and I had multiple bugs when releasing my plugins (see for example bug https://github.com/Chocobozzz/PeerTube/issues/4593 that seems related). I'd like to be able to test NPM installation before releasing.

Moreover, if a plugin developers wants to test with several other instance's admin, it is more difficult to coordinate tests with them if them have to manually download and install the plugin.

In this PR https://github.com/Chocobozzz/PeerTube/pull/4599 , I added an option to install a plugin specific version. 
But for now, Peertube only accept version numbers that are like /\d+\.\d+\.\d+/ (see function isPluginVersionValid).

**Describe the solution you would like:**

`isPluginVersionValid` should accept versions likes «1.0.0-beta.0» or «1.0.0-alpha.0».

Alpha and Beta versions should not be listed by the plugin indexer.

Alpha and Beta versions should not be proposed by the «upgrade» button.

Alpha and Beta versions should be installable by using the CLI with --plugin-version parameter (see PR https://github.com/Chocobozzz/PeerTube/pull/4599)

**Comment by JohnXLivingston** [comment]
Hi,

I'm still very interested in such feature. Any chance it could be implemented in Peertuve v5?
I'm going to soon release a major version of the livechat plugin, and I'd like to be able to do beta testing with other Peertube admins (as there will be breaking changes).

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/ff91b644fb1b063d0a8eff7492beb1a9bf7e4ce1

**Comment by JohnXLivingston** [comment]
Thanks a lot!
