### ISSUE TITLE
Transcoding failed with multiple restarts

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#4602]
**Describe the current behavior**

Restart peertube multiple times. Watch every video in the queue go to "failed to transcode". Videos will not try to transcode again. Manually running the transcode option results in "this video is already being transcoded".

There should be a way to manually restart the transcode in this instance.

**Additional information**

* PeerTube instance:
  * URL: vidbin.org
  * version: 4.0.0 rc1
  * NodeJS version: 16
  * Ffmpeg version: git
  * 
![transcoding](https://user-images.githubusercontent.com/7935624/144536973-d76a3232-45f4-4822-8839-28a93c5825ba.png)

**Comment by Chocobozzz** [comment]
The bug should be fixed by https://github.com/Chocobozzz/PeerTube/commit/025d858e7997d6b9895fa6b7beaf23bf5ff814af

You can fix your broken video in the database using:

```
update "videoJobInfo" set "pendingTranscode" = 0 where "videoId" = ...
```

**Comment by SimplyCorbett** [comment]
Thanks!
