### ISSUE TITLE
Decrease interval of scheduled resumable uploads cleanup

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4603]
**Describe the problem to be solved**

**Describe the solution you would like:**
We've had some users that had problems with their uploads, which lead to that they retried the upload many times. Our hard drive became full and then it stoped work completely.

**Describe alternatives you have considered**  
* Decrease the interval to 2 hours instead of 16 hours. Or is there any reason that the interval is so huge?
* Run the cleanup if the disk space is more or less full. In first case it can delete all files older than 1 hour, and if it's still close to full it can do a total cleanup. I assume this can lead to that currently uploads gets broken, but maybe that's better than the alternative that it's not possible to upload at all.
* Display a warning for the admin if the disk is close to full.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/6d472b4046084e5f477124b11ac62dca9f6a1a63: we now cleanup the directory every hour using the `.purge` uploadx function (thanks @kukhariev)
