### ISSUE TITLE
Can't run unit tests locally

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4609]
Steps to reproduce:
1. sudo -u postgres createuser you_username --createdb
2. createdb -O peertube peertube_test{1,2,3}
3. npm run build
4. npm run clean:server:test
5. sudo docker run -p 9444:9000 chocobozzz/s3-ninja
6. sudo docker run -p 10389:10389 chocobozzz/docker-test-openldap
7. TS_NODE_TRANSPILE_ONLY=true npm run mocha -- --timeout 30000 --exit -r ts-node/register -r tsconfig-paths/register --bail server/tests/api/videos/video-transcoder.ts

```

> peertube@4.0.0-rc.1 mocha /var/code/PeerTube
> mocha "--timeout" "30000" "--exit" "-r" "ts-node/register" "-r" "tsconfig-paths/register" "--bail" "server/tests/api/videos/video-transcoder.ts"



  Test video transcoding
    1) "before all" hook in "Test video transcoding"


  0 passing (7s)
  1 failing

  1) Test video transcoding
       "before all" hook in "Test video transcoding":
     Error: Process exited
      at ChildProcess.onPeerTubeExit (shared/extra-utils/server/server.ts:226:40)
      at ChildProcess.EventEmitter.emit (domain.js:486:12)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peertube@4.0.0-rc.1 mocha: `mocha "--timeout" "30000" "--exit" "-r" "ts-node/register" "-r" "tsconfig-paths/register" "--bail" "server/tests/api/videos/video-transcoder.ts"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@4.0.0-rc.1 mocha script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

System:
Node version: v14.15.1
OS: Ubuntu 20.04.3 LTS

**Comment by Chocobozzz** [comment]
Try to run `NODE_APP_INSTANCE NODE_ENV node dist/server` to see if it succeed to run a test server

**Comment by kontrollanten** [comment]
Thanks, the issue was that my `local.json` config was overriding the test configs (so they tried to run on the same port). Can we make those errors be printed by `shared/extra-utils/server/server.ts`?

**Comment by Chocobozzz** [comment]
Yes! Should be better with https://github.com/Chocobozzz/PeerTube/commit/f307255e694d290c346749bff68545d5dfc581cf
