### ISSUE TITLE
Please, allow audio formats

### ISSUE THREAD

**Issue by pedro-nonfree** [Chocobozzz/PeerTube#461]
We want to setup a podcasts repository (archive) for different radio organizations in a "youtube style" and decentralized manner.

I thought of a solution based on webtorrent or IPFS and here it is! Very happy to have found you guys

[The problem is that audios are not accepted](https://github.com/Chocobozzz/PeerTube/blob/develop/FAQ.md#what-codecs-can-i-use-for-the-videos-i-want-to-upload). Web radios are using mp3 a lot, and [it is patent-free since 16 April 2017](https://en.wikipedia.org/wiki/MP3#Licensing,_ownership_and_legislation)

interesting audio formats: mp3 (very important), optional (in that order): ogg, .opus

**Comment by rigelk** [comment]
Hi @pedro-nonfree, please look out for related issues before creating one, as #170 already covers this. You can then detail further your use case there.

**Comment by pedro-nonfree** [comment]
@rigelk thank you for your indication
