### ISSUE TITLE
Can't share custom filtered video lists URL's without login being presented. 

### ISSUE THREAD

**Issue by Openmedianetwork** [Chocobozzz/PeerTube#4611]
I often find that the coders working on projects we use have different agender to us producers and users. An example of this, is looking like the new filtering tools for videos in #peertube i share the links but find you need to be logged in to actually access them as URL's  likely the is a resion for this?

**Comment by Chocobozzz** [comment]
Hello,

I think you're sharing a link that contains an "all local videos" filter enabled. You need to be admin to see all videos. It's the reason why you see an error when you share the URL with another person.
