### ISSUE TITLE
Disable Main root channel

### ISSUE THREAD

**Issue by clement850** [Chocobozzz/PeerTube#4612]
Hello, I would like my users not to be able to see the user "root" and its associated channel ("Main root channel"). 

From another administrator account, I have the possibility to mute the account (root) for my instance, but it doesn't seem to work...

Thanks in advance

**Comment by Chocobozzz** [comment]
Hello,

Could you explain the use case? Why do you need to hide the `root` accounts and its channels?

**Comment by clement850** [comment]
Hello, 

Thanks for the answer. When I click on a tag on a video, the search result shows the root account and the main root channel... but also all the channels of the instance, in addition to videos matched with the tag

**Comment by Chocobozzz** [comment]
Okay then I think your use case should be fixed by https://github.com/Chocobozzz/PeerTube/commit/8cf43a6524d354fbfa0f0eaf789e8d4756bd25d6

Now when you click on a tag peertube will automatically display videos, and not channels/playlists so you won't see root channel anymore :)
