### ISSUE TITLE
Live stream recordings are not reliable

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#4613]
**Describe the current behavior**

This has come up tangentially in a few other issues (see https://github.com/Chocobozzz/PeerTube/issues/4508#issuecomment-959909884) but I didn't see an issue for it specifically.

When I've attempted to use peertube's live streaming, the resulting recordings are often incomplete or unplayable. I've seen this happen both with and without transcoding enabled, and server load does not appear to be a factor.

**Steps to reproduce:**

1. Live stream every day, actually check the recordings.

**Describe the expected behavior**

Expect recordings to always be playable and not to have any gaps. Length of the recording should match actual length of the broadcast.

**Additional information**

Live streaming in general has not been very reliable, and it would be useful to have some more specific attention toward this by the PeerTube developers, rather than just having an issue closed when there isn't an obvious single root cause already.

* PeerTube instance:
  * URL: diode.zone
  * version: 3.4.1
  * NodeJS version: v12.22.7
  * Ffmpeg version: 4.2.4-1ubuntu0.1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by andybalaam** [comment]
This has caused problems for my live streams and I would be happy to try and help diagnose.

**Comment by normen** [comment]
I am basically using PeerTube exclusively for streaming (mainly without live transcoding) and it works a charm, both with recordings and without (permanent stream). Of course connection issues on the sender side can cause issues, e.g. slow WiFi or a WiFi with a lot of interference. Can you stream elsewhere (e.g. youtube) with your setup?

**Comment by andybalaam** [comment]
Yes, I was simultaneously streaming to Twitch without problems.  I was using an nginx in a cloud data centre to stream to both simultaneously.

**Comment by Chocobozzz** [comment]
Hello,

Do you still have issues with live stream replays?

**Comment by Chocobozzz** [comment]
Closing as we made some improvements in replay saving.

Don't hesitate to add comments in this issue if you still notice the bug.
