### ISSUE TITLE
Inconsistency in theme change between logged in and logged out users

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4618]
**Describe the current behavior**

The process to change theme is very different between logged in and logged out users. And it is much easier when the user is logged out.

When logged out:

- just click on «my settings» in the left menu, then you can change the theme without leaving the current page/video
- the theme change instantly

When logged in:

- you have to go to «my account / settings» (and leave the current page/video)
- the theme field is at the end of the form, hard to find
- when changing the theme in the form, it does not apply instantly
- even when saving the form, the theme don't apply. We have to refresh the page. (this seems to be a bug)

**Describe the expected behavior**

When logged in, changing the theme should apply without refreshing the page.

Moreover, it would be really nice to have a button that open a popup, in the top left dropdown (just after the «change language» button)

* PeerTube instance:
  * version: 3.4.1, 4.0.0-RC1

**Comment by Chocobozzz** [comment]
Thanks, I've put the theme select just below the profile settings and fixed the theme change bug in https://github.com/Chocobozzz/PeerTube/commit/4b57ebdfe69e862373908590b0cf781ab0d71a02

**Comment by JohnXLivingston** [comment]
Thanks! :D
