### ISSUE TITLE
Home page title do not refresh

### ISSUE THREAD

**Issue by manuelviens** [Chocobozzz/PeerTube#4619]
**Home page title do not refresh**

**Steps to reproduce:**

1. Go to any page on an instance (or log in)
2. Click on Home and see the title has not change

**Title refreshed**

* PeerTube instance:
  * URL: Seems to be any up to date instances
  * version: 3.4.1

* Firefox 95 on Linux

**Comment by scanlime** [comment]
Confirmed on ChromeOS also

**Comment by buoyantair** [comment]
Seems to be working fine on https://peertube.social/ 
I am using macos / firefox

**Comment by buoyantair** [comment]
Seems to be working fine on https://peertube.social/ 
I am using macos / firefox

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/2e694a3b9850fa8f426aa4bf31fc8a596ae2d310
