### ISSUE TITLE
VAAPI hardware transcoding 

### ISSUE THREAD

**Issue by snakeeater4526** [Chocobozzz/PeerTube#4622]
hi,

i try to make work VAAPI in peertube for transcoding.

the vaapi plugin give me input/output error.

and the transcoding-profile-debug plugin, i tried that:

{
"vod": [
{
"encoderName": "aac",
"profileName": "test",
"outputOptions": []
},
{
"encoderName": "h264_vaapi",
"profileName": "test",
"outputOptions": []
}
],

"live": []
}

and it give me error 1 : conversion failed....

If anyone have an idea.... i would be really happy to hear it.... i'm not someone that like asking help but here i searched everywhere on google and i'm working on that particular project since non stop 48h

THANK YOU

**Comment by SimplyCorbett** [comment]
...Are you sure this is a peertube issue and not a user configuration issue? For example, is the driver loaded? Does your ffmpeg support hardware transcoding?

**Comment by snakeeater4526** [comment]
> 

ffmpeg support vaapi, i have the drivers, and i tried to manually ffmpeg a file with vaapi accel and it was working.

the problem is that i don't manage to make it work in peertube.

FFMPEG now support natively hardware accel ^^ at least with vaapi.

so yes it's a peertube issue

**Comment by snakeeater4526** [comment]
> 

how did you configured peertube to make it work with nvenc?

**Comment by SimplyCorbett** [comment]
That doesn't mean its a peertube issue. It's more then likely your configuration is wrong. NVENC is not vaapi so my stuff wont be of any help here.

Check the error logs and see if you can spot anything conclusive.

**Comment by SimplyCorbett** [comment]
I don't mind helping out though. This is what your debug plugin config should look like.

https://pastebin.com/TdVBPUfd

**Comment by snakeeater4526** [comment]
i tried your config and it worked, but it's software vp9 encoding so not really what i wanted.

i tried that :
{
  "vod": [
    {
      "encoderName": "aac",
      "profileName": "test",
      "outputOptions": ["-b:a 128k"]
    },
    {
      "encoderName": "h264_vaapi ",
      "profileName": "test",
      "outputOptions": ["-b:v 5M"]
    }
  ],
 
  "live": []
}

it does launch the encoding, but i think it's not using the conf at all ( it's slow and in htop it show that it's using libx264 and default settings of peertube....

how did you passed your settings for nvenc encoding ?

**Comment by snakeeater4526** [comment]
https://trac.ffmpeg.org/wiki/Hardware/VAAPI
for info

**Comment by Chocobozzz** [comment]
Hello,

Have you selected the `test` profile in admin config?

**Comment by snakeeater4526** [comment]
> Hello,
> 
> Have you selected the `test` profile in admin config?

hi, ofc i did ^^

like i said... was working with the vp9 config, and with the vaapi config, it fallback to default settings

**Comment by SimplyCorbett** [comment]
Then you need to find the error and figure out what's wrong. When I had a problem with bframes being required it specifically spit out that error in the log.

**Comment by snakeeater4526** [comment]
i have no idea i can fin any explanation... the logs don't help me at all... neither google...

@SimplyCorbett what was your nvenc config? maybe i can figure it out with your config

**Comment by SimplyCorbett** [comment]
The only thing different about my nvenc config is the bframes. I don't even know if intels iGPU supports bframes.

**Comment by Chocobozzz** [comment]
@snakeeater4526 vaapi is a little bit difficult to configure.
First ensure you installed `peertube-plugin-transcoding-profile-debug` **v0.0.3**

Then you can try:

```
{
  "vod": [
  {
    "encoderName": "aac",
    "profileName": "test",
    "outputOptions": []
  },
  {
    "encoderName": "h264_vaapi",
    "profileName": "test",
    "outputOptions": [],
    "inputOptions": [ "-hwaccel", "vaapi", "-hwaccel_output_format", "vaapi", "-vaapi_device", "/dev/dri/renderD128" ],
    "scaleFilter": { "name": "scale_vaapi" }
  }
  ],

  "live": []
}
```

You may also need [this commit](https://github.com/Chocobozzz/PeerTube/commit/14857212f15256ff4dd0d36ff5158005f1d7caae), on my side the default b frame value was too high and ffmpeg failed.

**Comment by snakeeater4526** [comment]
> @snakeeater4526 vaapi is a little bit difficult to configure. First ensure you installed `peertube-plugin-transcoding-profile-debug` >= **v0.0.3**
> 
> Then you can try:
> 
> ```
> {
>   "vod": [
>   {
>     "encoderName": "aac",
>     "profileName": "test",
>     "outputOptions": []
>   },
>   {
>     "encoderName": "h264_vaapi",
>     "profileName": "test",
>     "outputOptions": [],
>     "inputOptions": [ "-hwaccel", "vaapi", "-hwaccel_output_format", "vaapi", "-vaapi_device", "/dev/dri/renderD128" ],
>     "scaleFilter": { "name": "scale_vaapi" }
>   }
>   ],
> 
>   "live": []
> }
> ```
> 
> You may also need [this commit](https://github.com/Chocobozzz/PeerTube/commit/14857212f15256ff4dd0d36ff5158005f1d7caae), on my side the default b frame value was too high and ffmpeg failed.

Thanks for the help, seems like right, however i still have the default settings used when i want to transcode and i don't know why... Yes i use the test profile, and here are my settings in this profile:
```{
  "vod": [
  {
    "encoderName": "aac",
    "profileName": "test",
    "outputOptions": ["-b:a 128k"]
  },
  {
    "encoderName": "h264_vaapi",
    "profileName": "test",
    "outputOptions": ["-c:v h264_vaapi", "-b:v 5M"],
    "inputOptions": [ "-hwaccel", "vaapi", "-hwaccel_device /dev/dri/renderD128", "-hwaccel_output_format", "vaapi", "-vaapi_device"],
    "scaleFilter": { "name": "scale_vaapi" }
  }
  ],

  "live": []
} 
```

i however didn't used the commit you said , don't know if it's the problem, maybe will try later.

PS: yes i used peertube-plugin-transcoding-profile-debug >= v0.0.3

**Comment by Chocobozzz** [comment]
> Thanks for the help, seems like right, however i still have the default settings used when i want to transcode and i don't know why

Enable peertube debug logs, it prints why and what encoders it will use

**Comment by snakeeater4526** [comment]
Thank you i understand the problem now and will work on it

**Comment by snakeeater4526** [comment]
ok so
now it's working but i get an ffmpeg input/output error
![image](https://user-images.githubusercontent.com/41698614/146034519-12549148-d4b8-4221-b08c-0ac83b086e84.png)

i tried everything to fix it , it won't ... that really make no sense

if someone have an idea, i'm open .

**Comment by snakeeater4526** [comment]
found the problem, there is a problem with the introducing of input/output option in ffmpeg via the plugin

**Comment by snakeeater4526** [comment]
@Chocobozzz can you tell me how to input something into inputOptions or outputOptions? cause i think the way you described is wrong and cause the input/output error i have.

for exemple do i need to have 

``
 "inputOptions": [  "-hwaccel", "vaapi", "-hwaccel_device", "/dev/dri/renderD128", "-hwaccel_output_format", "vaapi" ],
``
or more like? :
``
 "inputOptions": [-hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi],
 ``
 i'm pretty sure it's the input/output error that i have 
 
 thank you

**Comment by snakeeater4526** [comment]
seems like there is access problem, ffmpeg launched via peertube doesn't have access to /dev/dri/renderD128,
i don't know why since everyone have the right, and i even made peertube user ROOT.

I wonder if they use or not a sub user for that....

**Comment by snakeeater4526** [comment]
@TheoLeCalvar you have an idea?

**Comment by TheoLeCalvar** [comment]
I checked the [profile I use](https://git.kher.nl/tlc/peertube-plugin-hardware-transcode-vaapi/-/blob/main/main.js) and noticed I use a slightly different set of input parameters.
You have `-hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -vaapi_device`  where I have `-hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device /dev/dri/renderD128`.
It could be the issue.

Also, how are you running peertube ? Inside a docker container or directly ?

If you are running directly then the user running peertube should be in the `render` group.

If you are inside a container you have configuration to do.
I had to add these to the peertube section of the `docker-compose.yml`:
```
    group_add:
      - 107
    devices:
      # VAAPI Devices
      - /dev/dri:/dev/dri
```

Group 107 is the render group on my debian host.
