### ISSUE TITLE
Add new Angular page using plugin

### ISSUE THREAD

**Issue by raazkarkee405** [Chocobozzz/PeerTube#4623]
I want to develop a plugin that adds new page in my peertube. For that page I will be displaying some information through API. And, according to the peertube documentation I have to work through it by using the available hooks.
Creating a page means creating a new route. So, going through the documentation I found a custom routes section for plugin which provides route for the endpoints create with plugin.
But these routes are I guess API routes that serves data. I want a custom frontend route that will be able to display the data in a better UI.
In the [Plugins & Themes API](https://docs.joinpeertube.org/api-plugins) page there is a hook that adds item to the left menu `'filter:left-menu.links.create.result': true`.
For now I added an item through that hook and provided a path example: `/my-information`. On clicking it I am directed to that path and 404 error message is displayed and that is obvious. 
So, to render the data I have removed the tag and injected some html and I know this is not the best solution. 
My question is that is there any possible way to do so or it is not possible?

The plugin I am working on: [peertube-plugin](https://github.com/raazkarkee405/peertube-plugin-angular-route)
![image](https://user-images.githubusercontent.com/26194365/145533108-f51f1e1c-aaf8-473e-b969-8c27988c9cad.png)

**Comment by Chocobozzz** [comment]
Hello,

I implemented custom client route in https://github.com/Chocobozzz/PeerTube/commit/d63e6d4604dfbe4938c7d66832c9202364c5bb64

Please test it and don't hesitate to tell me if you need other parameters/helpers.

**Comment by raazkarkee405** [comment]
@Chocobozzz I have tested the custom client route and it is working fine. 
Please have a look if this the way you meant for this to work.
[peertube-plugin-angular-route](https://github.com/raazkarkee405/peertube-plugin-angular-route/blob/main/client/common-client-plugin.js)

**Comment by raazkarkee405** [comment]
Hello, @Chocobozzz  
I was able to create the new angular page using plugin with `registerClientRoute` and able to add route to that page using the hook `'filter:left-menu.links.create.result'`. What if we have the ability to add the page both for general users and only for authorized users using plugin. It would be also better if we are able to add new items to the left menu based on authorization similar to `my account`, `my library`.
`
> Hello,
> 
> I implemented custom client route in [d63e6d4](https://github.com/Chocobozzz/PeerTube/commit/d63e6d4604dfbe4938c7d66832c9202364c5bb64)
> 
> Please test it and don't hesitate to tell me if you need other parameters/helpers.
