### ISSUE TITLE
Need Tutorials  about Firewall configuration

### ISSUE THREAD

**Issue by memoryboxes** [Chocobozzz/PeerTube#463]
I don't know what port ranges  peertube allow Other Connections, maybe:

* 80 http
* 443 https
* 9000 local service

webtorrent server ports?

We need a tutorials about how to set up a firewall for peertube instance server.

**Comment by Chocobozzz** [comment]
PeerTube only needs web ports (80/443). 9000 should not be opened to the world if your reverse proxy is on the same server. There are many tutorials on the web to do such things :)
