### ISSUE TITLE
Consider adding Norwegian Nynorsk locale

### ISSUE THREAD

**Issue by aujawindar** [Chocobozzz/PeerTube#4630]
Greetings,

The strings for player, server and Peertube are translated 100% to Norwegian Nynorsk in Weblate. There is still a lot to do on angular, but I see this applies to many other languages too. Considering the level of translated strings, I kindly ask you to consider adding Norwegian Nynorsk to the Peertube localisations.
The name of the locale in its own language is nynorsk. Should Norwegian Bokmål reach a suitable translation level, its name in its own language is bokmål. An alternative is to use norsk nynorsk and norsk bokmål, respectively.

**Comment by Chocobozzz** [comment]
Thanks for your contribution! Both *norsk* locales should be available tomorrow on https://peertube2.cpy.re/
