### ISSUE TITLE
Unable to start Peertube 4.0.0 instance

### ISSUE THREAD

**Issue by whyronimus** [Chocobozzz/PeerTube#4632]
Dear Peertubers,

I have problems getting Peertube 4.0.0 to start. I installed the release candidate by downloading it from github, otherwise following the manual as described. 

**Commands executed:**

`sudo service peertube start`

Also tried, with user peertube:

`cd /var/www/peertube/peertube-latest && NODE_ENV=production NODE_CONFIG_DIR=/var/www/peertube/config node dist/server`

I got the following errors:

```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/var/www/peertube/versions/PeerTube-release-4.0.0/dist/server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

(Likewise for `sudo journalctl -feu peertube`, just multiple times)

Other commands don't work either, error is always the same: `MODULE_NOT_FOUND`. 

**Additional information**

OS is ubuntu 20.04 in a VM.

Installation worked well with no errors.

I also noticed that there are no folders created in /var/www/peertube/storage. Usually, the subdirectories would be there.

**PeerTube instance:**
  * version: 4.0.0
  * NodeJS version: 14.18.2
  * Ffmpeg version: 4.2.4-1ubuntu0.1
  * Redis version: 5.0.7
  * PostgreSQL version: 12.9

Where is my mistake? Any setting I missed, or anything changed for version 4.0.0?

If I can provide any addition info such as config, please let me know.

**Comment by Chocobozzz** [comment]
Hello,

Did you follow https://docs.joinpeertube.org/install-any-os?id=installation?

If yes, what is the output of `ls /var/www/peertube/peertube-latest`?

**Comment by whyronimus** [comment]
Hello,

yes, of course I did follow your (very well written) install guide.

from `/var/www/peertube` the output of `ls -l /var/www/peertube/peertube-latest` is:

`lrwxrwxrwx 1 peertube peertube 32 Dec 12 02:02 /var/www/peertube/peertube-latest -> versions/PeerTube-release-4.0.0/`

If I `cd` to `peertube-latest`, the output of `ls` is:

```
-rw-rw-r--   1 peertube peertube 137167 Dec  9 04:54 CHANGELOG.md
drwxrwxr-x   6 peertube peertube   4096 Dec 12 06:27 client
-rw-rw-r--   1 peertube peertube   3831 Dec  9 04:54 CODE_OF_CONDUCT.md
drwxrwxr-x   2 peertube peertube   4096 Dec  9 04:54 config
-rw-rw-r--   1 peertube peertube   9465 Dec  9 04:54 CREDITS.md
-rw-rw-r--   1 peertube peertube     89 Dec  9 04:54 engines.yaml
-rw-rw-r--   1 peertube peertube     38 Dec  9 04:54 FAQ.md
-rw-rw-r--   1 peertube peertube  34520 Dec  9 04:54 LICENSE
drwxrwxr-x 643 peertube peertube  20480 Dec 12 06:27 node_modules
-rw-rw-r--   1 peertube peertube   7532 Dec  9 04:54 package.json
lrwxrwxrwx   1 peertube peertube     31 Dec 12 06:26 PeerTube-release-4.0.0 -> versions/PeerTube-release-4.0.0
-rw-rw-r--   1 peertube peertube  10003 Dec  9 04:54 README.md
drwxrwxr-x  10 peertube peertube   4096 Dec  9 04:54 scripts
-rw-rw-r--   1 peertube peertube   4624 Dec  9 04:54 SECURITY.md
drwxrwxr-x  14 peertube peertube   4096 Dec  9 04:54 server
-rw-rw-r--   1 peertube peertube  10540 Dec  9 04:54 server.ts
drwxrwxr-x   5 peertube peertube   4096 Dec  9 04:54 shared
drwxrwxr-x  10 peertube peertube   4096 Dec  9 04:54 support
-rw-rw-r--   1 peertube peertube    871 Dec  9 04:54 tsconfig.json
-rw-rw-r--   1 peertube peertube 386717 Dec  9 04:54 yarn.lock
```

What irritates me is the `ln` to `versions/Peertube-release-4.0.0` which practically redirects to its own directory.

Is everything as it should be?

**Comment by Chocobozzz** [comment]
> Is everything as it should be?

No, you don't have downloaded the release zip. It seems you downloaded the source code of PeerTube instead. The `PeerTube-release-4.0.0` link in `peertube-latest` should not exist.

I suggest you to retry the installation

**Comment by whyronimus** [comment]
That sounds like it's the problem. Thanks! 
Since the release is available, I will try this one.

**Comment by whyronimus** [comment]
With the proper release, it worked. Thank you again!
