### ISSUE TITLE
Peertube v4.0.0: video that are only available as webtorrents don't play

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4634]
**Describe the current behavior**

After migrating to v4.0.0, I search for videos that are only available in webtorrent on my instance, using the new tools:

![image](https://user-images.githubusercontent.com/38844060/145806723-b846fc7e-2b1d-4488-98b7-e66cb4d95b09.png)

I tried to open it. The player don't show. There is no play button, no video.
![image](https://user-images.githubusercontent.com/38844060/145806819-442f168b-0441-42e2-beea-aee7d5346a3a.png)

In the browser logs:
```
Uncaught Error: Can't update video file since videoFile is undefined.
    updateVideoFile webtorrent-plugin.ts:144
    initializePlayer webtorrent-plugin.ts:441
    Hi webtorrent-plugin.ts:98
    triggerReady core.js:4480
    triggerReady core.js:4479
    l core.js:5146
    0 zone.js:2561
    invokeTask zone.js:406
    runTask zone.js:178
    invokeTask zone.js:487
    invoke zone.js:476
    0 zone.js:2541
webtorrent-plugin.ts:144:12
```

Here is the video: https://videos.globenet.org/w/cRRrntFdmL5NVuWAU3Yojd

Note: the download button is working. The file exists.

**Steps to reproduce:**

1. find a video that is only available in webtorrent format
2. try to read the video

**Describe the expected behavior**

Video should play

**Additional information**

* PeerTube instance:
  * URL: https://videos.globenet.org
  * version: 4.0.0

* Browser name, version and platforms on which you could reproduce the bug: Firefox stable

**Comment by JohnXLivingston** [comment]
Additional note: it is working with chromium. Seems related to firefox.

**Comment by JohnXLivingston** [comment]
That's weird. It is working with firefox and private browsing. Maybe one of my extension. I'll try to disable them.

**Comment by JohnXLivingston** [comment]
It seems to happen when I'm logged in. Not related to the browser as I thought.

**Comment by JohnXLivingston** [comment]
Summary of what is happening:
- works on chromium
- works on chromium + private browsing
- works on firefox + private browsing
- don't work on firefox. Logged in or not. Even when disabling all my firefox plugins

I have another user who as the same bug on this video.

I tried also to disable peertube's plugins. Same bug.

**Comment by JohnXLivingston** [comment]
I had to delete all data and cookies for videos.globenet.org to make it work.

**Comment by JohnXLivingston** [comment]
Could it be related to this change: «Removed deprecated /static/torrents route»?
Maybe there was a deprecated route saved in the browser localStorage? Or indexDB? Or cookie?

**Comment by Chocobozzz** [comment]
Hi,

It was a bug that should be fixed by https://github.com/Chocobozzz/PeerTube/commit/2b6af10e9f37ccd104a9cc179e32c530a6655964

**Comment by JohnXLivingston** [comment]
Great! Can I transcode the video to HLS? Or do you want me to keep it as so until next release?

**Comment by Chocobozzz** [comment]
> Great! Can I transcode the video to HLS? Or do you want me to keep it as so until next release?

In fact I don't know how you managed to have only an audio version of this video ^^ So I don't know how you could fix it: transcoding to HLS will not work since the player is not compatible with audio-only resolution...

**Comment by JohnXLivingston** [comment]
Oh, I didn't realize that! (that the video is audio only).

**Comment by JohnXLivingston** [comment]
For you information, i ran «transcode to HLS» on this file (audio only, see your last comment @Chocobozzz ). 
It generates video in multiple resolutions.
Should I open an issue for that?
