### ISSUE TITLE
peertube-plugin-transcoding-profile-debug doesn't seem to have any effect

### ISSUE THREAD

**Issue by whyronimus** [Chocobozzz/PeerTube#4635]
I installed the plugins "transcoding-custom-quality" and "transcoding-profile-debug", especially the last one seemed very promising to me since it allows (almost) full control over transcoding. I created the following profile:

```
{
  "vod": [
    {
      "encoderName": "copy",
      "profileName": "keep-original-audio",
      "outputOptions": []
    },
    {
      "encoderName": "libx264",
      "profileName": "keep-original-audio",
      "outputOptions": []
    }
  ],

  "live": []
}
```

The new profile shows up in the VOD transcoding options, but practically, no matter what setting is entered, ffmpeg transcodes with settings `-acodec aac` and `-vcodec libx264`. Also, when I set the second encoder to `libvpx-vp9`, nothing different happens. I tried to set the parameter `outputOptions`, but with no luck (a syntax example in the help file would be good), it gave the error "transcoding failed", when I tried `-c:a copy`.

**Questions:**

- how should a transcoding profile look like? 
- can it be entered somewhere else than this plugin?
- can standard ffmpeg settings be overriden if they are given via profile/plugin?
- does peertube need a restart or any other confirmation before a profile is applied to VOD transcoding?

**Additional information**

The input Video is H264 and FLAC audio, intention is to let ffmpeg work with parameter` -c:a copy` so the output should be FLAC in playback. (If this is intentionally not possible, please let me know!). 

Another issue: If a video is deleted before it's finished transcoding, the transcoding job is not stopped. This is not a problem if the video is 2 minutes long, but for a 2 hour concert video this could ve very annoying.

**PeerTube instance:**

  * version: 4.0.0
  * NodeJS version: 14.18.2
  * Ffmpeg version: 4.2.4-1ubuntu0.1

**Comment by Chocobozzz** [comment]
Hello,

Upgrade `peertube-plugin-transcoding-profile-debug` to **v0.0.4** and try:

Transcoding profiles:
```
{
  "vod": [
    {
      "encoderName": "aac",
      "profileName": "keep-original-audio",
      "outputOptions": [],
      "copy": true
    }
  ],

  "live": []
}
```

Encoders priorities:
```
{
  "vod": [
    {
      "encoderName": "aac",
      "streamType": "audio",
      "priority": 1005
    }
  ],

  "live": [ ]
}
```

**Comment by whyronimus** [comment]
Thanks a lot, will try.
Could you explain or add documentation what exactly the profile is doing? Is the parameter `encoderName` intendet to set a reaction if this codec is identified in the input file, or that the encoder is to be used with this profile?

**Comment by whyronimus** [comment]
Unfortunately, it did not work - I get message "Transcoding failed".

In peertube log, ffmpeg reports:

`Error: ffmpeg exited with code 1: Could not write header for output file #0 (incorrect codec parameters ?)`

The same occurs when I change `aac` to `flac` in the profile.

**Comment by Chocobozzz** [comment]
What input file are you trying to transcode?

**Comment by whyronimus** [comment]
It's a H264 encoded video with flac audio stream, in MP4 container. It works well if standard encoding profile is set, he then transcodes to H264 and aac.

**Comment by whyronimus** [comment]
Hello, just a quick update:

I had to add `-strict -2` to the `outputOptions`. (MP4 supports flac, but ffmpeg wants "experimental features" activated).

It then transcoded with `-acodec copy` as desired. Unfortunately, the HLS conversion did not work. My assumption is that it is done via another ffmpeg call, so maybe it's necessary to have the outputOptions applied to this one too. I didn't find any good info whether HLS actually supports flac, but neither that it doesn't. Could you give it another glance? Many thanks in advance!

**Comment by Chocobozzz** [comment]
I don't think copying codecs can work for HLS. You may try to reencode audio using `flac` encoder

**Comment by whyronimus** [comment]
I got it working! With ffmpeg, `-c:a copy` did return HLS with flac audio using the following commands:

`ffmpeg -i inputfile.mp4 -c:v copy -c:a copy -strict -2 -start_number 0 -hls_time 10 -hls_list_size 0 -hls_playlist_type vod -hls_segment_type fmp4 -f hls playlist.m3u8`

So the trick is to use `fmp4`, .ts does not support flac audio as far as I understand. `-strict -2` is also needed.
It did not work with ffmpeg 4.2.4 but with 4.3.2 (comes with ubuntu 21.04)

I'd absolutely love to see this implemented. It would be awesome to have the possibility of lossless audio in HLS streams. This issue has been around recently (https://github.com/video-dev/hls.js/issues/4387) but is now actually - technically - possible. As far as I can see, FLAC support for HLS has been merged into a IETF standardization draft https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis) so there could be real chance of it becoming a new standard - which is overdue. Peertube could provide a genuine technical advantage by this feature. 

Sorry for me being too excited about it, I was just very happy that FLAC now is going to be a real option, which could lead it out of the niche it's currently in. If there is any additional info I can provide, I'm glad to help.

**Comment by whyronimus** [comment]
Just a short update:

I got it to work also in my peertube instance by editing `ffmpeg-utils.ts`, adding `.outputOption('-strict -2')` to `function addCommonHLSVODCommandOptions`. The Video transcodes now with FLAC audio and is played with such. However, this is only a workaround. Unfortunately, I wasn't able to find out how the `outputOptions` set in profile are returned, if anyone can help here, I will try to edit the code and commit. 

IMHO a parameter like `hlsoutputoptions` in the profile would be ideal, to make both processing steps customizable independent from each other.
