### ISSUE TITLE
Global Search index is unavailable - System Error 97

### ISSUE THREAD

**Issue by LPS-github** [Chocobozzz/PeerTube#4637]
I updated my instance approximately 5 days ago and since then my Subscriptions are no longer updating with new videos and also the Global Search index is unavailable ... It returns an error when searching for anything at all.  "Unknown system error 97"

![image](https://user-images.githubusercontent.com/69872464/145919461-fccf232e-28b5-49a7-aaa3-112e7ffb0f0e.png)

I've checked the admin panel to verify the address being used for Global Search (search.joinpeertube.org) works.  It doesn't return results from within my instance, but works just fine the URL in a browser directly.

Hopefully this error gives a clue to what's going on:

![image](https://user-images.githubusercontent.com/69872464/145919875-e7416588-36d4-41a9-a687-6cf3ed8b2090.png)

and the instance version 
![image](https://user-images.githubusercontent.com/69872464/145919922-aa218d71-cab3-4a9f-a7b9-f4cbd2fe58f6.png)

**Comment by Chocobozzz** [comment]
Hello,

It seems there is an issue on your system. I never seen this `Unknown system error 97 ` error, and google does not seem either.
You can try to reboot your server? What is your OS and nodejs version?

**Comment by LPS-github** [comment]
Hi, thanks for the response.  Unfortunately, a reboot didn't resolve the issue:(

My OS is Debian Buster (10) and my node.js version is v12.22.1

**Comment by rosbeef** [comment]
Hello i'm in the same trouble 
I'm running peertube installed with yunohost
Here what's you asked for
require('os').networkInterfaces()
{
  lo: [
    {
      address: '127.0.0.1',
      netmask: '255.0.0.0',
      family: 'IPv4',
      mac: '00:00:00:00:00:00',
      internal: true,
      cidr: '127.0.0.1/8'
    },
    {
      address: '::1',
      netmask: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
      family: 'IPv6',
      mac: '00:00:00:00:00:00',
      internal: true,
      cidr: '::1/128',
      scopeid: 0
    }
  ],
  eth0: [
    {
      address: '192.168.0.221',
      netmask: '255.255.255.0',
      family: 'IPv4',
      mac: '00:16:3e:49:93:54',
      internal: false,
      cidr: '192.168.0.221/24'
    },
    {
      address: '2a01:e0a:XXX"',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: 'xxxxx',
      internal: false,
      cidr: '2a01:e0a:xxxx/64',
      scopeid: 0
    },
    {
      address: 'fe80::2xxxxxx',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: 'xxxxxx',
      internal: false,
      cidr: 'fe80::2xxxxxx/64',
      scopeid: 6
    }
  ]
}

**Comment by Chocobozzz** [comment]
Seems a yunohost issue: https://github.com/YunoHost-Apps/peertube_ynh/issues/283
