### ISSUE TITLE
Can't login after Peertube 4 upgrade

### ISSUE THREAD

**Issue by fenarinarsa** [Chocobozzz/PeerTube#4638]
Can't login after Peertube 4 upgrade

Upgraded from one of the latest Peertube 3 to Peertube 4.0 and modified/added required keys in production.yaml.
I also added storage.bin as requested but I didn't have a storage/bin folder so I created it?

Logs when I try to login doesn't show much (set to 'debug'). I don't have any error message in the UI. It just doesn't log in anymore (for any user):
{"tags":["http"],"level":"info","message":"[***IP masked***] - - [14/Dec/2021:23:32:44 +0000] \"GET /api/v1/users/me HTTP/1.0\" 200 3161 \"https://peertube.fenarinarsa.com/login\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0\"","label":"peertube.fenarinarsa.com:443","timestamp":"2021-12-14T23:32:44.443Z"}

* PeerTube instance: peertube.fenarinarsa.com
  * version:  4.0.0
  * NodeJS version: v12.22.2
  * Ffmpeg version: 4.1.6-1~deb10u1
  * Redis version: 5.0.3-4+deb10u3 
  * PostgreSQL version: 11+200+deb10u4

**Comment by Chocobozzz** [comment]
Please paste web browser logs

**Comment by fenarinarsa** [comment]
Very strange, this morning I can login again. I don't understand at all what happened. Maybe something like anti-hammering?

**Comment by Chocobozzz** [comment]
I'm sorry but I don't know. Don't hesitate to comment if you still have the issue.
