### ISSUE TITLE
Can't add mp3 when cover image is too big

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4641]
**Describe the current behavior**

When I try to add a mp3 file, with a PNG cover bigger than 2Mo, it does not work, and there is no correct error message.

![image](https://user-images.githubusercontent.com/38844060/146227830-097e0cf2-1a5c-4b0e-99ca-a4665051d3ba.png)

(notice the [object object] message)

Logs in my browser:

```
The upload failed: [object Object] notifier.service.ts:20:12
    error notifier.service.ts:20
    q upload.ts:29
    handleUploadError video-upload.component.ts:303
    onUploadVideoOngoing video-upload.component.ts:144
    ngOnInit video-upload.component.ts:109
    RxJS 6
    stateChange ngx-uploadx.js:675
    Angular 5
    stateChange ngx-uploadx.js:675
    set status ngx-uploadx.js:349
    upload ngx-uploadx.js:398
    _ tslib:72
    Angular 9

```

**Steps to reproduce:**

1. click «public»
2. add a mp3 file
3. add a cover. In my case, it was a 2Mo png file
4. click the upload button

**Describe the expected behavior**

Should fail with an error message, and we should be able to resume with another cover.

**Additional information**

* PeerTube instance:
  * URL:
  * version: 4.0.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox

**Comment by Chocobozzz** [comment]
Hi,

Could you send me the cover you try to upload? And what is the server response?

**Comment by JohnXLivingston** [comment]
Just send you by e-mail

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/293074ae7920040ede7e01d0aec4dabbeeb864ff

**Comment by JohnXLivingston** [comment]
Thanks!
Thank you so much for your work on Peertube! <3

**Comment by JohnXLivingston** [comment]
Hum, I just saw the comment on this line:
https://github.com/Chocobozzz/PeerTube/blob/293074ae7920040ede7e01d0aec4dabbeeb864ff/support/nginx/peertube#L95

Maybe there is also a fix to do on the nginx config?

**Comment by Chocobozzz** [comment]
> Maybe there is also a fix to do on the nginx config?

I'm sorry but I don't understand?

**Comment by JohnXLivingston** [comment]
> > Maybe there is also a fix to do on the nginx config?
> 
> I'm sorry but I don't understand?

no need to increase client_max_body_size on the nginx entrypoint where the images are send? (currently, client_max_body_size is only set for /api/v1/videos/upload )

**Comment by Chocobozzz** [comment]
The image is sent in the same endpoints where the client_max_body_size should already be correctly set (resumable upload endpoint + classic upload endpoint)

**Comment by JohnXLivingston** [comment]
Ok!
