### ISSUE TITLE
SQL error in videos-id-list-query-builder.ts 

### ISSUE THREAD

**Issue by lamposu** [Chocobozzz/PeerTube#4642]
**Describe the current behavior**
Subscriptions videos not show correctly, video with "internal" privacy not show on Subscriptions page.

**Steps to reproduce:**
1.User A and B in the same instance.
2. User A subscribes to "channel_b" of user B.
3. User B upload and publish a new video "video_b" in "channel_b" with "internal" privacy.
4. User A can not see the "video_b" video  in **Subscriptions** page.

**Describe the expected behavior**
1.User A should be able to see the "video_b" on the subscriptions page.

Additional information

PeerTube instance:

URL:
version: 4.0.0
NodeJS version: v12.22.7
Ffmpeg version: 4.2.4
Browser name, version and platforms on which you could reproduce the bug:
Browser: Chrome Version 96.0.4664.110 (Official Build) (64-bit), Win10

Link to browser console log if relevant:

Link to server log if relevant (journalctl or /var/www/peertube/storage/logs/):

![927cc1c73e0b4c7595d2e73062c8af55](https://user-images.githubusercontent.com/34417123/146300630-0e03b230-f138-4ae4-bb4a-0bda78ed0f1d.jpg)

**Comment by Chocobozzz** [comment]
Hello,

Could you explain why and what is the error?

**Comment by lamposu** [comment]
The subscriptions videos not show correctly, you can test the video with privacy "internal".

**Comment by lamposu** [comment]
and the column  "targetActorId" in table "actorfollow"  means the channel actorId and not the account actorId, right?

**Comment by lamposu** [comment]
When change the video privacy from "public"(published with public) to unpublic("internal" or "private"), but the data still in the table "videoShare", i think this also not right. 
I didn't do much test from UI and only check the database data, maybe i am wrong, But I think you should check it.. Thanks

**Comment by Chocobozzz** [comment]
Please fill the [bug template](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/00-bug-issue.md) because I don't understand

> and the column "targetActorId" in table "actorfollow" means the channel actorId and not the account actorId, right?

It means any actor (channel or account)

**Comment by lamposu** [comment]
OK, I have fill the bug template. 
Maybe you're not a developer, never mind.  Thank you very much.

**Comment by Chocobozzz** [comment]
Okay thanks with the template I understood the bug! :) Should be fixed by your solution: https://github.com/Chocobozzz/PeerTube/commit/9e2789aa4bcd582d6e7746e2f6ece0fd25a3240a
