### ISSUE TITLE
Incorrect public IP address 

### ISSUE THREAD

**Issue by jpatje** [Chocobozzz/PeerTube#4643]
I am using a DNS proxy via Cloudfare, to not show my home IP address to the world. Now the debug says 'PeerTube thinks your web browser public IP is [cloudfare IP]'.
So that's not my true IP address where Peertube is hosted from.
Do I need to set the trust_proxy for this? Apparantly, there are 3 options.

It's not clear to me which I should choose:

  - 'loopback'
  - 'linklocal'
  - 'uniquelocal'
  
  Or not set it at all?
  Btw, just updated to version 4 without any problem :)

**Comment by Chocobozzz** [comment]
Hello,

Try to add all cloudflare IPs (https://www.cloudflare.com/fr-fr/ips/)

**Comment by jpatje** [comment]
Thanks, but where do I add it? Not behind the 'trust_proxy' setting? Or do I?

**Comment by Chocobozzz** [comment]
Yes you do!

Something like:

```
trust_proxy:
  - 'loopback'
  - '103.21.244.0/22'
  - ...
```

**Comment by jpatje** [comment]
Thanks for the great help, it worked!
