### ISSUE TITLE
404 Page error on reload (Using registerClientRoute()).

### ISSUE THREAD

**Issue by smilekison** [Chocobozzz/PeerTube#4646]
I have created a new page and integrated a Graph with chart.js library with route using `registerClientRoute()`  https://github.com/Chocobozzz/PeerTube/commit/d63e6d4604dfbe4938c7d66832c9202364c5bb64 . I added the route to the left navigation bar. At first, the route is working properly but when the page is refreshed, the page shows 404 page not found error. Upon logging the error, I got the following error `"Could not find registered route /graph"`. 

The problem occurs only when external libraries are imported through plugin so I tried configuring the webpack to support external module import. Also, I downloaded chartbundle.js file and kept it on folder. There is no error while compiling the plugin and at first the chart is also displayed but after refreshing the 404 page is displayed. Can you help me on how can i import external libraries in registerClientRoute()?

Inside common client, i have imported chartbundle like this
`import ChartBundleMin from "./Chart.bundle.min.js";`

The following are the logs:
1) The webpack configuration:
![peeerweb](https://user-images.githubusercontent.com/24309222/146498293-16864101-0574-4944-a3cc-52552b518074.png)

2) On first load (From navigation)
![peertu](https://user-images.githubusercontent.com/24309222/146498298-64fc8567-9549-4d6e-a9a9-f723b6d2c784.png)

3) On page reload (Refresh)
![peertutu](https://user-images.githubusercontent.com/24309222/146498306-264be0e8-0004-4c31-a08b-01e19b8af23d.png)

**Comment by Chocobozzz** [comment]
Hi,

Could you try with https://github.com/Chocobozzz/PeerTube/commit/9d9a37330ce23642460d911f2932b8b70c80d6a0?

**Comment by smilekison** [comment]
@Chocobozzz , 
It is working properly. 
Thank you :)
