### ISSUE TITLE
Hide publish button until user is logged in

### ISSUE THREAD

**Issue by whyronimus** [Chocobozzz/PeerTube#4647]
Hello,

would it be possible to hide the "publish" button, until a user has logged in?
In my use cases, registration is deactivated and only authorized personnel will have access to the instance.
It's possible to hide it with `display:none` in custom CSS of course, but this is login-agnostic.

Many thanks in advance :-)

**Comment by kontrollanten** [comment]
Hi! This is solved by the plugin [hide-publish-button](https://www.npmjs.com/package/peertube-plugin-hide-publish-button), which will hide the publish button until a user is logged in has a video quota that's greater than 0.

**Comment by whyronimus** [comment]
My apologies - I should have mentioned that, of course, I tried the plugin, but with no effect.
I installed it, but the button still is there. (When logged out). Is there any other setting I have missed?

**Comment by kontrollanten** [comment]
No, it shouldn't be. Can you create an issue at https://framagit.org/kontrollanten/peertube-plugin-hide-publish-button with a link to the instance?

**Comment by whyronimus** [comment]
Instance 1 is in a VM (Peertube 4.0.0), the other one is also not publicly available yet (Peertube 3.4.2), it should be noted that on both instances the plugin does not seem to have the desired effect. Could it be an ad-blocker or such in browser, which is preventing it from doing what it's supposed to do? When the page is loaded, the button at very first split-second is not there, but then appears.

**Comment by kontrollanten** [comment]
I actually haven't tried it with 4.0, but 3.4 should work. It may be an ad blocker. What if you try with a different browser or in incognito mode (no extensions)?

**Comment by whyronimus** [comment]
I tried Vivaldi and Edge, unfortunately with no change - Firefox in incognito mode also still displays the button. All extensions are deactivated. Can you reproduce the issue?

**Comment by whyronimus** [comment]
**Solution:** Set standard video quota and quota per day to 0.
