### ISSUE TITLE
Update a video over API

### ISSUE THREAD

**Issue by jb-alvarado** [Chocobozzz/PeerTube#4648]
**Parts of the documentation concerned:**

API Doc -> [Update a video](https://docs.joinpeertube.org/api-rest-reference.html#operation/putVideo)

**Describe the desired information/correction:**

The documentation say that the request body part should be: `multipart/form-data`. But that's not working, instead it needs to be: `application/json`. At least in version 4.0 from PeerTube.

**Comment by Chocobozzz** [comment]
Hello,

What do you mean by "not working"? Both are supported (you need multipart if you upload a video thumbnail/preview)

**Comment by jb-alvarado** [comment]
Hello @Chocobozzz, sorry that I was not specific enough. First I had problems with updating the tags from videos in python. To test it in a more simple environment I change to Insomnia and tried there my requests. With `multipart/form-data` I was not able at all to make a put request. Only with `application/json` I was able to make changes. That is why I come to the conclusion that something is happen with`multipart/form-data`.

**Comment by jb-alvarado** [comment]
> Both are supported (you need multipart if you upload a video thumbnail/preview)

Then I was to fast with my issue, sorry!
