### ISSUE TITLE
Add Malayalam as a supported language for video content

### ISSUE THREAD

**Issue by pravi** [Chocobozzz/PeerTube#465]
* **PeerTube version or URL:**
https://firedragonvideos.com 1.0.0 beta 1

* **Browser name/version:**
* **NodeJS version:**

* **What is the expected behaviour?**

User should be able to select Malayalam.

* **What do you see instead?**

Malayalam is missing from the language list.

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

**Comment by Chocobozzz** [comment]
Closing in favor of https://github.com/Chocobozzz/PeerTube/issues/466
