### ISSUE TITLE
Packages for Debian and Ubuntu LTS

### ISSUE THREAD

**Issue by supersexy** [Chocobozzz/PeerTube#4651]
I am totally hot for installing and maintaining several PeerTube instances for some local community projects - but I am stopped right now because no Debian or Ubuntu LTS packages exist. 

I guess it could be an enormous push for the popularity / usability of PeerTube if you would like to provide a repository for Debian and Ubuntu LTS distros, that is still the most easy way to get software and packages installed with sane default configuration. 

No, docker is not "simpler" - it hides complexity inside containers and layers of image files, but instance admins will have to peel the docker layers away in case they need to debug / fine tune etc, what makes things actually much more complicated than software installed by packages in standard places with everything important in /etc. 

Debian packages are still the best way to distribute software in a transparent and efficient way. Also unattended updates for security fixes can be delivered in a very quick and efficient way by the unattended-upgrades package, what will be a huge plus for fleets of PeerTube instances hosted by weekend-admins!

Yes, for developers docker is still useful, but as a distribution mechanism for end users it makes things much more complicated than they need to be. Please keep it simple and transparent with plain old packages.

Thanks!

**Comment by Chocobozzz** [comment]
Hi,

I'm sorry but unfortunately we don't have time and sufficient knowledge to create debian/ubuntu packages.

If you want you can create them and update https://docs.joinpeertube.org/install-unofficial
