### ISSUE TITLE
Mastodon interaction/federation issues, followers disappearing and comments not appearing

### ISSUE THREAD

**Issue by FediVideos** [Chocobozzz/PeerTube#4652]
**Describe the current behavior**

On instance tilvids.com followers from Mastodon have recently started to vanish, for example user account thelinuxexperiment@tilvids used to have about 800 followers and steadily growing, but started quickly going down to about 400 around the time this issue appeared. I've observed this on all the Tilvids accounts that I have promoted through FediVideos, followers used to creep up slowly after I posted about them, but have suddenly started ticking down rapidly.

When I try to follow a new Tilvids account from Mastodon, the follow doesn't happen, it gets stuck as a follow request.

Simultaneously, comments posted from Mastodon no longer appear on PeerTube (see attached screenshots).

I've been in touch with the instance admin, they tried restarting the server as this resolved all past federation issues, but this time it didn't seem to make any difference.

**Steps to reproduce:**

1. From Mastodon, attempt to reply to a Tilvids.com video and subscribe to a Tilvids.com account
2. Check the same video on Tilvids.com to see if the comment has appeared, this issue means it won't
3. Refresh the Tilvids account within Mastodon to see if you are following, this issue means it will just be a request rather than a follow

**Describe the expected behavior**

Replies in Mastodon should appear as comments on Tilvids

Follows from Mastodon should work on Tilvids, there should not be any follow request status returned

**Additional information**

* PeerTube instance:
  * URL: https://tilvids.com
  * version: 3.4.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox 95, Ubuntu
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

![HolidayDrink2](https://user-images.githubusercontent.com/75383929/146647192-0795ea62-4fa7-479a-a864-a9ff1c2e5056.png)
![HolidayDrink1](https://user-images.githubusercontent.com/75383929/146647193-65b1834b-8689-45b2-8586-3da5ad5a9875.png)

**Comment by AnonymousWebHacker** [comment]
That has happened to me before, but something different.
It happened to me that not all comments appear in Mastodon, or if I commented from mastodon, they were not shown in peertube.

Verify that both servers can find your dns name
And check on both servers, if they have the tracking for said instances activated, blocked ..etc

**Comment by Chocobozzz** [comment]
Hello,

Could you try peertube v4? We made some improvements in the federation process

**Comment by Chocobozzz** [comment]
Closing until v4 is tested, don't hesitate to comment if you still notice the bug after upgarde.

**Comment by FediVideos** [comment]
I'm still waiting on Tilvids to upgrade, so cannot give an update on that.

HOWEVER... there is a somewhat similar (but not as bad) federation issue on the v4 instance vidcommons.org (which also had issue when on older versions). I did some investigations by asking for people to test it out on Mastodon: some instances were able to follow while others just got a follow request.

In amongst the replies, someone said there had been similar issues on other Fediverse platforms interacting with Mastodon. I will quote their reply in full as it may be useful for resolving the PT-Masto issue:

> 
> (Trying to follow a vidcommons account) shows just a follow request.
> 
> I encountered with this problem several times, and it happens only to those non-mastodon accounts. I guess it might be related to mastodon secure mode.
> 
> Last time this issue occured to one group server, and its maintainer fixed it by: https://github.com/wxwmoe/wxwClub/commit/e2d21783a41c054174e0efacb8b43dc87df50832

Is it possible that this could fix the issue that has caused problems for people following certain PeerTube instances from certain Masto instances?

**Comment by FediVideos** [comment]
Right, Tilvids.com has now updated to 4.1 and this seems to have fixed things! :partying_face: 

Thank you to the developers for fixing federation :pray: 

I'll post in this thread if the problems come back.
