### ISSUE TITLE
Audio only files generated as webtorrent instead of HLS, with a «transcoding failed» status

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4657]
**Describe the current behavior**

My instance is configured to only generate HLS format.
![image](https://user-images.githubusercontent.com/38844060/146752718-026beba0-9fcd-454b-8995-331cb90a6d19.png)

But 5 days ago, a video appeared in webtorrent, without HLS, and with a «transcoding failed» status (the first one on the screenshot):
![image](https://user-images.githubusercontent.com/38844060/146752949-f78b7f18-2fb6-4e8a-84b8-5924893da95d.png)

Note: the second video in the screenshot is the one mentionned here: https://github.com/Chocobozzz/PeerTube/issues/4634 (see the comment https://github.com/Chocobozzz/PeerTube/issues/4634#issuecomment-995868417 , it could be related in some ways).

The link to the new video: https://videos.globenet.org/w/s1r2hd5boa8H9JgHJiAkwY

I found this log:

```log
error[15/12/2021, 18:31:03] Cannot execute job 2336 in queue video-transcoding.

{
  "payload": {
    "type": "optimize-to-webtorrent",
    "videoUUID": "d29d068a-8fba-4f3a-aded-5a33b5940810",
    "isNewVideo": true
  },
  "err": {
    "stack": "Error: Cannot compute FPS because 0 is lower than our minimum value 1\n    at computeFPS (/srv/peertube/versions/peertube-v4.0.0/dist/server/helpers/ffprobe-utils.js:286:15)\n    at Object.<anonymous> (/srv/peertube/versions/peertube-v4.0.0/dist/server/helpers/ffmpeg-utils.js:222:46)\n    at Generator.next (<anonymous>)\n    at fulfilled (/srv/peertube/versions/peertube-v4.0.0/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "message": "Cannot compute FPS because 0 is lower than our minimum value 1"
  }
}
```

**Steps to reproduce:**

Here is what I found in the audit log:

```log
audit[15/12/2021, 18:30:54]Par cnt_fte ->video-imports -> create

{
  "user": "cnt_fte",
  "domain": "video-imports",
  "action": "create",
  "video-import-id": 249,
  "video-import-targetUrl": "https://www.mixcloud.com/CNTEducation93/14-d%C3%A9cembre-2021-el%C3%A8ves-sans-papiers-et-mineures-isol%C3%A9es/?utm_source=notification&utm_medium=email&utm_campaign=notification_new_upload&utm_content=html",
  "video-import-video-name": "14 décembre 2021 - Élèves sans papiers et mineur.e.s isolé.e.s"
}
```

**Describe the expected behavior**

File should be encoded in HLS, there should not be any «transcoding failed» status.

**Additional information**

* PeerTube instance:
  * URL: https://videos.globenet.org
  * version: 4.0.0
  * NodeJS version: v12.22.7
  * Ffmpeg version: 4.1.8-0+deb10u1

**Comment by Chocobozzz** [comment]
Hello and thanks for the detailed issue.

It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/482b26231b4e39234f107b8400ef606c5f003c55
