### ISSUE TITLE
Send and receive private messages (compatible with Mastodon/Fediverse)

### ISSUE THREAD

**Issue by rebelcode-xr** [Chocobozzz/PeerTube#4658]
**Ability to send private messages between PT users**
This is something I would expected as "basic feature": the ability to write a message to another PT user in private. A sort of email/chat, like the one Mastodon has.

![image](https://user-images.githubusercontent.com/63522951/146763293-4d561c31-378d-4264-acb4-621a6389ee39.png)

**Ability to send private messages between federated users**
Since messages would be sent over AP protocol, this would add the ability to send private message between different PT instances and also between different platforms (PT<->Mastodon).

**A federated chat/IM system instead of emails**
Isn't this part of the vision behind the Fediverse? A way to keep your connections, avoiding the lock-in in a single instance or even in a certain kind of platform.
If every federated platform would have private messages, we could have a federated IM/chat system.

**Also on Mobilizon**
A similar request has been open for Mobilizon: https://framagit.org/framasoft/mobilizon/-/issues/898

**Comment by Poslovitch** [comment]
(sort of) duplicates #2513
