### ISSUE TITLE
Videos stuck in limbo after failed move to object storage

### ISSUE THREAD

**Issue by mariOwO** [Chocobozzz/PeerTube#4659]
I'm having a little problem after a failed create-move-video-storage-job for all my videos.
Due to me not having the upgrade to 4.0.0 script run before i started the jobs, all of them failed due to the HLS files not being found.
Here is one error for example:
```
error[12/20/2021, 10:06:09 AM] Cannot execute job 106 in queue move-to-object-storage.

{
  "payload": {
    "videoUUID": "82ce0d92-a599-4556-a85b-79b58246122e",
    "isNewVideo": false
  },
  "err": {
    "stack": "Error: ENOENT: no such file or directory, stat '/var/lib/peertube/storage/streaming-playlists/hls/82ce0d92-a599-4556-a85b-79b58246122e/82ce0d92-a599-4556-a85b-79b58246122e-1080.m3u8'",
    "message": "ENOENT: no such file or directory, stat '/var/lib/peertube/storage/streaming-playlists/hls/82ce0d92-a599-4556-a85b-79b58246122e/82ce0d92-a599-4556-a85b-79b58246122e-1080.m3u8'",
    "errno": -2,
    "code": "ENOENT",
    "syscall": "stat",
    "path": "/var/lib/peertube/storage/streaming-playlists/hls/82ce0d92-a599-4556-a85b-79b58246122e/82ce0d92-a599-4556-a85b-79b58246122e-1080.m3u8"
  }
}
```
The video is still available on local storage but unlisted on the PeerTube Page, going to the video directly yields the `The video is being moved to an external server, it may not work properly.` notice.
When I try to run the create-move-video-storage-job job again on the failed videos I get the following error and the script gets stuck:
```
> peertube@4.0.0 create-move-video-storage-job
> node ./dist/scripts/create-move-video-storage-job.js "--to-object-storage" "-v" "82ce0d92-a599-4556-a85b-79b58246122e"

Processing video DARK SOULS - The Movie - The Last of the Ancient Dragons.
Error: Cannot use same state 6
    at VideoModel.<anonymous> (/usr/share/webapps/peertube/dist/server/models/video/video.js:902:23)
    at Generator.next (<anonymous>)
    at /usr/share/webapps/peertube/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/share/webapps/peertube/node_modules/tslib/tslib.js:113:16)
    at VideoModel.setNewState (/usr/share/webapps/peertube/dist/server/models/video/video.js:900:38)
    at /usr/share/webapps/peertube/dist/server/lib/video-state.js:53:21
    at Generator.next (<anonymous>)
    at fulfilled (/usr/share/webapps/peertube/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Is it possible to reset the state of all the failed videos to retry the move script?
Thank you very much.

**Comment by Chocobozzz** [comment]
Hello,

Stuck videos should not happen anymore with https://github.com/Chocobozzz/PeerTube/commit/dbd9fb44ddd880622265097bd7baf4dd71ea0861

To fix your current videos, go inside your database and run:

```
UPDATE video SET state = 1 WHERE uuid = '...';
```

It will set their state to "published"

**Comment by mariOwO** [comment]
Thank you very much!
Sadly that didn't fix the problem completely. While i can re-create the job, it causes other issues:

1. The videos stay unlisted since the `The video is being moved to an external server, it may not work properly.` notice still won't disappear with the new jobs.
2. The P2P Player uses the local playlist and tries to play the now-moved local videos instead from off the remote storage. The videos and playlist have been moved to the remote bucket and be viewed though. Also the HTTP Player uses the remote playlist and uses the video from the remote storage perfectly.

**Comment by Chocobozzz** [comment]
Then try to download from object storage missing playlist files on disk so the job does not fail

**Comment by jdaviescoates** [comment]
I've just hit this issue too, not sure exactly what to do now how?

This video failed https://bridport.tv/w/jcW35StYWcuNczxVWt2PNP it plays as it's obviously stored locally, but is unlisted because it failed. 

So what are the steps to fix this? And how to investigate why it happened in the first place?

**Comment by Chocobozzz** [comment]
Check in your logs why the video failed to be moved in external storage. Then use https://docs.joinpeertube.org/maintain-tools?id=create-move-video-storage-jobjs to move it again

**Comment by polykit** [comment]
I have a problem related to this issue. For some videos on my instance upload to object storage fails with:

```
Job: 254 Type: move-to-object-storage Processed on 7/20/23, 5:54:56.155 AM Finished on 7/20/23, 5:55:19.994 AM
--
{   "videoUUID": "3773fafa-6c3b-4791-aea8-57f96660dd53",   "isNewVideo": true,   "previousVideoState": 2 }
Error [ERR_STREAM_WRITE_AFTER_END]: write after end     at new NodeError (node:internal/errors:387:5)     at ClientRequest.end (node:_http_outgoing:968:15)     at writeBody (/app/node_modules/@aws-sdk/node-http-handler/dist-cjs/write-request-body.js:22:21)     at ClientRequest.<anonymous> (/app/node_modules/@aws-sdk/node-http-handler/dist-cjs/write-request-body.js:9:13)     at ClientRequest.emit (node:events:513:28)     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:635:11)     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)     at TLSSocket.socketOnData (node:_http_client:534:22)     at TLSSocket.emit (node:events:513:28)     at addChunk (node:internal/streams/readable:315:12)     at readableAddChunk (node:internal/streams/readable:289:9)     at TLSSocket.Readable.push (node:internal/streams/readable:228:10)     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
```

After running `create-move-video-storage-job` the video got uploaded successfully to object store but master playlist is still on local storage. The video is now stuck in `TO MOVE TO AN EXTERNAL STORAGE` state and can't be played.

The error might be related to my setup with MinIO object storage and Traefik ingress in front.

Do you have any advice on how to fix the videos to make them playable again? Thanks!
