### ISSUE TITLE
Allow to increase description limit characters > 1000

### ISSUE THREAD

**Issue by isAAAc** [Chocobozzz/PeerTube#4662]
Hello, 
as asked in https://masto.krashboyz.org/@isaaac/107428820914587534 to @Chocobozzz , 
i would have to set a chan description with more than 1000 characters

`Description cannot be more than 1000 characters long.`
thx a lot for all your work <3

isAAAc

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/5841
