### ISSUE TITLE
Unable to add authorization to the angular route and page created using plugin?

### ISSUE THREAD

**Issue by raazkarkee405** [Chocobozzz/PeerTube#4663]
I was able to create the new angular page using plugin with `registerClientRoute` and able to add route to that page using the hook `filter:left-menu.links.create.result`. With this I was only able to add page to the general user but not for the authorized user.  It would be better if we are able to add new items to the left menu based on authorization similar to my account, my library and add authorization to the added page using the plugin.

I would be better if I was able to add angular pages and routes for both general user and authorized user.

**Comment by Chocobozzz** [comment]
Hello,

You have the `isLoggedIn()` helper so you can add the entry depending on the logged in status: https://docs.joinpeertube.org/api-plugins?id=client-register

**Comment by raazkarkee405** [comment]
Hello @Chocobozzz, 

I tried using isLoggedIn() helper to check the entry depending on the logged in status. I did was if isLoggedIn() is true then the registerClientRoute and filter:left-menu.links.create.result is triggered similar to:

```
 // to display content in the route /p/my-information
  if (peertubeHelpers.isLoggedIn()) {
    const options = {
      route: "my-information",
      onMount: async (options) => {
        const { rootEl } = options;
        await fetch(peertubeHelpers.getBaseRouterRoute() + "/mydata", {
          method: "GET",
          headers: peertubeHelpers.getAuthHeader(),
        })
          .then((res) => res.json())
          .then((data) => {
            const z = document.createElement("h3");
            z.innerHTML = data.email;
            // rootEl.setAttribute("id", "root");
            rootEl.appendChild(z);
          });
      },
    };
    registerClientRoute(options);

    console.log("plugin route", peertubeHelpers.getBasePluginClientPath());

    // to add item in left menu
    registerHook({
      target: "filter:left-menu.links.create.result",
      handler: (items) => {
        return [
          ...items,
          {
            key: "features",
            title: "Additional Features",
            links: [
              {
                label: "My Information",
                icon: "trending",
                shortLabel: "My Information",
                path: "/p/my-information",
              },
            ],
          },
        ];
      },
    });
  }
```
At first when the peertube was initialized I was not able to see the left-menu item My Information that was added with plugin and also /p/my-information page was not accessible. (without login). But On login also I was not able to see the left-menu item My Information and the /p/my-information page was redirected to /404 page. In order to see the left-menu item I have to reload it.

And on logout also My Information item was still there and to feel the change I have to reload it.

![image](https://user-images.githubusercontent.com/26194365/147323250-22c50012-f252-4489-9e2a-f52bc046cf18.png)
![image](https://user-images.githubusercontent.com/26194365/147323287-7f9a5354-69cb-4a4b-a7fb-248f20560b86.png)
![image](https://user-images.githubusercontent.com/26194365/147323360-2379a5bc-4a4b-4b0a-aa77-84f37253d9e5.png)
![image](https://user-images.githubusercontent.com/26194365/147323397-a01a692e-9ad8-480d-bffe-34f7f9622fa7.png)

**Comment by Chocobozzz** [comment]
Always register your route, but display an error message or redirect to `/404` if the user is not logged in.

It's the same for `filter:left-menu.links.create.result`, that will be called if the login status change. So you need to check the login status in the `handler`

**Comment by raazkarkee405** [comment]
Hello,

So, in `filter:left-menu.links.create.result` I checked the login status in the `handler` as suggested and is working fine.
And for the angular route I did the following: 

```
registerHook({
    target: "action:router.navigation-end",
    handler: (value) => {
      const { path } = value;
      console.log("route::", path);
      if (
        !peertubeHelpers.isLoggedIn() &&
        path == peertubeHelpers.getBasePluginClientPath() + "/my-information"
      ) {
        location.assign(
          window.location.protocol + "//" + window.location.host + "/login"
        );
      }
    },
  });
```
With this it solves the problem but I am not sure if it is the right way. Is it?

**Comment by Chocobozzz** [comment]
You can put this code in `onMount` function of your route
