### ISSUE TITLE
Certbot Errors with every installation option. An unexpected error occured: Requesting acme-v02.api.letsencrypt.org/directory:Permission denied

### ISSUE THREAD

**Issue by Fin55** [Chocobozzz/PeerTube#4668]
I had used the normal any OS installation with Debian 10 and have gotten certbot errors after:
$ sudo certbot --authenticator standalone --installer nginx --post-hook "systemctl start nginx"

with:
nginx: configuration file /etc/nginx/nginx.conf test failed

Where all my other certificates no longer working, nginx becomes buggy and doesnt work, and I have to rebuild my entire vps to re add them.

I have not seen any answers at all to get this resolved.

So now im using the doc method and after this step:

docker run -it --rm --name certbot -p 80:80 -v "$(pwd)/docker-volume/certbot/conf:/etc/letsencrypt" certbot/certbot certonly --standalone

And getting:

An unexpected error occured: Requesting acme-v02.api.letsencrypt.org/directory:Permission denied
![image](https://user-images.githubusercontent.com/96567726/147207824-c6b21fce-d002-41f9-8a4b-f496cf8fa3e1.png)

All NodeJS version, Ffmpeg version:, Redis version, PostgreSQL version are up to date.

I want to be able to use peertube but the steps with certbot always lead to errors and I don't know how to fix it. I have spent two days trying to figure this out.

**Comment by Chocobozzz** [comment]
Hello,

From your error `nginx: configuration file /etc/nginx/nginx.conf test failed` is seems your nginx configuration is broken. Try `nginx -t` to check the failure.
