### ISSUE TITLE
Ability for a user to mute an instance/channel/account

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#467]
* **PeerTube version or URL:** peertube.mastodon.host
* **Browser name/version:** Firefox 61.0
* **NodeJS version:** N/A

* **What is the expected behaviour?**
Within the account parameter screen, one is able to hide instances based on a simple list of hosts.
* **What do you see instead?**
Right now, depending on what the instances the admin of the current instance chose to display one will see everything (but explicit content which is filtered by default), turning more an more the homepage into a spam-wall with content that should end in the "explicit" area.

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

**Comment by Chocobozzz** [comment]
I think a personal page for users that only display videos from instances/accounts/channels they subscribed would be better.

**Comment by zikzakfr** [comment]
Hello Chocobozzz,
Isn't that already the case with the "local" option? It show only the video from the instance I registered to.

Though, a page with user's subscriptions only would help a lot, for sure. Both would be great, like on Mastodon, to follow an account and to mute/block another.

**Comment by Chocobozzz** [comment]
Okay so I renamed the issue. See https://github.com/Chocobozzz/PeerTube/issues/470 for user subscriptions.

**Comment by Chocobozzz** [comment]
Implemented :+1:
