### ISSUE TITLE
PeerTube stuck while loading videos

### ISSUE THREAD

**Issue by avdb13** [Chocobozzz/PeerTube#4671]
Peertube seems to be working flawlessly for the biggest part but whenever I play a video it takes forever to load. At first you can see it downloading the video but after that it just stops and the video player keeps hanging. Eventually after a long time it will finally start playing after throwing some errors in the browser console. I can still download the videos though.

**Steps to reproduce:**

1. Install Peertube on Gentoo GNU/Linux with kernel `5.10.76-gentoo-r1` (here is my `/proc/config.gz`: http://dpaste.com/GWAZ43NP4).
2. Experience the problem and have a terrible day.

**Describe the expected behavior**
It should preferably play the video as soon as possible.

**Additional information**

* PeerTube instance:
  * URL: https://tube.gravitation.me
  * version: 4.0.0
  * NodeJS version: nodejs-14.17.6
  * Ffmpeg version: 4.4.1-r1

* Browser name, version and platforms on which you could reproduce the bug:
Gentoo GNU/Linux with Mozilla Firefox 95.0.1 and Chromium 95.0.4638.54.
* Link to browser console log if relevant:
http://dpaste.com/EW6KPQSYA
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
Nothing interesting here.

**Comment by Chocobozzz** [comment]
Hello,

The instance is not responding and dpaste is not found

**Comment by avdb13** [comment]
Hi @Chocobozzz 

Every so often I experience a mysterious crash with PeerTube, I also noticed that the PID file doesn't remove itself which is very frustrating. This time it seems like I can't restart PeerTube at all. This is what I found in `/var/log/peertube/peertube.log`:
```
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '/var/www/peertube/peertube-latest/dist/server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Browser log:
```

```

And the kernel configuration, this one should last a little longer before it gets deleted: https://dpaste.com/5CBUVJV55

**Comment by Chocobozzz** [comment]
Thanks, 

It seems to be a ffmpeg issue. Are you sure you use ffmpeg 4.4.1 and not 4.4.0? If yes, try to install 4.3.x and reupload the videos

**Comment by avdb13** [comment]
It's working now, thank you.
