### ISSUE TITLE
Unable to use develop-bullseye docker image

### ISSUE THREAD

**Issue by raazkarkee405** [Chocobozzz/PeerTube#4675]
Hello,

I have a running peertube with the latest docker image tag `peertube:v4.0.0-bullseye`. The peertube server is running as expected but I wanted to use the `develop-bullseye` image tag for peertube.

For that I just changed the image in my `docker-compose.yml` file with `develop-bullseye` and when I ran the containers with `docker-compose up -d` all the containers ran including peertube but I ran into the following problem which shows error in redis client.
![image (2)](https://user-images.githubusercontent.com/26194365/147721343-c6b22049-99be-45bb-84a5-3c320dbdfe49.png)

**Comment by Chocobozzz** [comment]
What is the status of redis container?

**Comment by raazkarkee405** [comment]
The logs from my redis container looks like this:
![image](https://user-images.githubusercontent.com/26194365/147912052-d3c7dff3-2601-4c57-88fa-ad9e54ab1e41.png)

**Comment by Chocobozzz** [comment]
PeerTube container [should retry](https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/docker-compose.yml#L68) to start until redis is ready, this is not the case?

**Comment by raazkarkee405** [comment]
The PeerTube container is trying to restart but it is not able to connect with Redis Client.
![image](https://user-images.githubusercontent.com/26194365/147921300-1a48079f-58ae-4cde-88ee-3832daa7c411.png)

I also tried fresh setup with `develop:bullseye` tag but same error occured.

**Comment by Chocobozzz** [comment]
Please paste your docker compose content

**Comment by raazkarkee405** [comment]
```
version: "3.3"

services:

  # You can comment this webserver section if you want to use another webserver/proxy
  webserver:
    image: chocobozzz/peertube-webserver:latest
    # If you don't want to use the official image and build one from sources:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.nginx
    env_file:
      - .env
    ports:
     - "80:80"
     - "443:443"
    volumes:
      - type: bind
        # Switch sources if you downloaded the whole repository
        #source: ../../nginx/peertube
        source: ./docker-volume/nginx/peertube
        target: /etc/nginx/conf.d/peertube.template
      - assets:/var/www/peertube/peertube-latest/client/dist:ro
      - ./docker-volume/data:/var/www/peertube/storage
      - certbot-www:/var/www/certbot
      - ./docker-volume/certbot/conf:/etc/letsencrypt
    depends_on:
      - peertube
    restart: "always"

  # You can comment this certbot section if you want to use another webserver/proxy
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./docker-volume/certbot/conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    restart: unless-stopped
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;"
    depends_on:
      - webserver

  peertube:
    # If you don't want to use the official image and build one from sources:
    # build:
    #   context: .
    #   dockerfile: ./support/docker/production/Dockerfile.bullseye
    image: chocobozzz/peertube:develop-bullseye
    # Use a static IP for this container because nginx does not handle proxy host change without reload
    # This container could be restarted on crash or until the postgresql database is ready for connection
    networks:
      default:
        ipv4_address: 172.18.0.42
    env_file:
      - .env

    ports:
     - "1935:1935" # If you don't want to use the live feature, you can comment this line
    #  - "9000:9000" # If you provide your own webserver and reverse-proxy, otherwise not suitable for production
    volumes:
      - assets:/app/client/dist
      - ./docker-volume/data:/data
      - ./docker-volume/config:/config
    depends_on:
      - postgres
      - redis
      - postfix
    restart: "always"

  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - ./docker-volume/db:/var/lib/postgresql/data
    restart: "always"

  redis:
    image: redis:6-alpine
    volumes:
      - ./docker-volume/redis:/data
    restart: "always"

  postfix:
    image: mwader/postfix-relay
    env_file:
      - .env
    volumes:
      - ./docker-volume/opendkim/keys:/etc/opendkim/keys
    restart: "always"

networks:
  default:
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/16

volumes:
  assets:
  certbot-www:
```

**Comment by Chocobozzz** [comment]
Thanks,

And what is the content of `./docker-volume/config` in host and `/config` in peertube container?
In these directories, you should have [production.yaml](https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/config/production.yaml) (in particular https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/config/production.yaml#L40)

**Comment by raazkarkee405** [comment]
Hello, 

Since the PeerTube server was setup fresh and the PeerTube is not running so, there isn't any contents in the `./docker-volume/config`.  Also, checking the `/config` in peertube container, `production.yaml` file was not available.
![image](https://user-images.githubusercontent.com/26194365/148369847-34c8d717-4638-4c24-8b73-59271f5fe92d.png)

**Comment by Chocobozzz** [comment]
I think it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/ff4d2c73fd5a8ab08a5a5c2655eb91c96d39687e

Please retry the develop container next week (or build it yourself)
