### ISSUE TITLE
Improve OpenRC script using start-stop-daemon

### ISSUE THREAD

**Issue by avdb13** [Chocobozzz/PeerTube#4678]
**Describe the current behavior**
I don't know whose idea it was to create an init script that doesn't just use `start-stop-daemon` since that would have made things a million times easier instead of reinventing the wheel.
Currently peertube just silently crashes on startup after starting it automatically on boot with `rc-update` and the biggest problem is that it doesn't report a crash so OpenRC can do something about it (which is the purpose of an init system after all).
I tried editing the existing script but it's hopeless.

**Steps to reproduce:**

1. Install Peertube on an operating system with OpenRC
2. Add it to the default runlevel
3. Find out it's actually not running on startup

**Describe the expected behavior**
`/etc/init.d/peertube` should use `start-stop-daemon` or just make sure it works on startup with the current init script.

**Additional information**
Nothing.

* PeerTube instance:
All not relevant.

* Browser name, version and platforms on which you could reproduce the bug: No.
* Link to browser console log if relevant: No.
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
Nothing gets logged on startup.

**Comment by Chocobozzz** [comment]
You can rewrite the script. Unfortunately I don't use/know openrc.

**Comment by avdb13** [comment]
Good to hear. I will open a pull request once I did.
