### ISSUE TITLE
preview are not shown

### ISSUE THREAD

**Issue by 01123581321345589144233** [Chocobozzz/PeerTube#4680]
**Describe the expected behavior**
i have installed a new server with v4 and try to upload a video, the video is not playing and the prwviews are not shown

and i have a error:

warn[31.12.2021, 22:27:42] Cannot generate thumbnail of https://tv2.gomntu.space/videos/watch/e5bd9d49-0986-4c4f-a5c9-363b89facfd2.

{
  "err": {
    "stack": "Error: ffmpeg exited with code 1: Error while decoding stream #0:0: Invalid data found when processing input\nCannot determine format of input stream 0:0 after EOF\nError marking filters as finished\nConversion failed!\n\n    at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v4.0.0/node_modules/fluent-ffmpeg/lib/processor.js:182:22)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:475:12)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)",
    "message": "ffmpeg exited with code 1: Error while decoding stream #0:0: Invalid data found when processing input\nCannot determine format of input stream 0:0 after EOF\nError marking filters as finished\nConversion failed!\n"
  },
  "tags": [
    "ap",
    "video",
    "update",
    "e5bd9d49-0986-4c4f-a5c9-363b89facfd2",
    "https://tv2.gomntu.space/videos/watch/e5bd9d49-0986-4c4f-a5c9-363b89facfd2"
  ]
}

**Additional information**

* PeerTube instance:
  * URL:https://tv2.gomntu.space
  * version:4
  * NodeJS version:v12.22.8
  * Ffmpeg version:ffmpeg version 4.4.1

* Browser name, version and platforms on which you could reproduce the bug:Firefox
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by kontrollanten** [comment]
Hi! Can you provide the video file you are trying to upload?
