### ISSUE TITLE
Lates videos from another instance not being shown

### ISSUE THREAD

**Issue by vachan-maker** [Chocobozzz/PeerTube#4681]
**Describe the current behavior**
I am subscribe to the channel/account niccolo_ve@tube.kockatoo.org from the server https://tilvids.com
Usually, all his latest videos are shown on my subscriptions page on TILvids. I also received notifications as well.

But a month later, his new videos don't appear on my subscriptions page. He uploaded a video a two days ago but that video does not appear on my tilvids subscriptions page 
**Steps to reproduce:**

1. Remote subscribe to the channel/account niccolo_ve@tube.kockatoo.org from TILvids instance
2. Wait for a few weeks
3. New videos don't appear/synchronise between instances.

**Describe the expected behavior**
All videos are shown on the subscriptions page including the new ones.

**Additional information**
TILvids server: 3.4.1
https://tube.kockatoo.org server version: 3.4.0
* PeerTube instance:
  * URL: https://tilvids.com
  * version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
### TILvids page 
![image](https://user-images.githubusercontent.com/65799568/147877551-cafd8fc3-df06-4df9-9109-889d3abb9f17.png)
###  Main Server of creator
![image](https://user-images.githubusercontent.com/65799568/147877572-fa3569f5-b817-4265-b04b-e6eafa3f73e2.png)
**You can see that new videos uploaded by the creator don't appear on the tilvids instance subscription page for me **

**Comment by Chocobozzz** [comment]
Hello,

Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/4652

**Comment by jeena** [comment]
This one really reminds me of https://github.com/Chocobozzz/PeerTube/issues/3947 it seems the same problem, and it got worse after upgrading to v4, now only local things appear on the subscription tab.

**Comment by vachan-maker** [comment]
@jeena Yeah, it seems to be the same problem. 
I can also only see the local videos on my subscription page as well even though I have remotely subscribed to many channels.
