### ISSUE TITLE
Seekbar's time tooltip and slider are not available on mobile

### ISSUE THREAD

**Issue by christophehenry** [Chocobozzz/PeerTube#4688]
I'm talking about the `.vjs-time-tooltip` and `.vjs-play-progress.vjs-slider-bar::before` elements:

![](https://user-images.githubusercontent.com/22097904/147936944-6a3dbc06-9fa2-4a48-8c1f-4570724d1678.png)

Those appear only on hover, which is not avaible on most mobiles. Thus, it's almost impossible to navigate in a video — inparticular, a long one — on mobile.

**Comment by Chocobozzz** [comment]
Hello,

I created a PR on videojs repository: https://github.com/videojs/video.js/pull/7598

**Comment by Chocobozzz** [comment]
Implemented directly in PeerTube in https://github.com/Chocobozzz/PeerTube/commit/fb84fad50c4798a4add5a8cf93ed43f8a43c2243

![screen_2023-06-19-08:56:01](https://github.com/Chocobozzz/PeerTube/assets/5180488/734c9e8c-b5e1-4dd4-9037-36a0b18e361b)
