### ISSUE TITLE
Double tap on the video's sides to rewind or fast forward 10s on mobile

### ISSUE THREAD

**Issue by christophehenry** [Chocobozzz/PeerTube#4689]
Very useful feature on mobile present on Youtube. Double-tap on the right side to fast-forward 10 seconds and double-tap en the left side to rewind 10 seconds. I'm really missing this on Peertube.

**Comment by Chocobozzz** [comment]
Should be implemented in https://github.com/Chocobozzz/PeerTube/commit/2dd0a8a8fd2fc85180fa3b45c5a6a56d07320ed3
