### ISSUE TITLE
UI: show less / show more action not reseting when playing a new video

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#469]
* **PeerTube version or URL:** 1.0.0-beta.3 (same with previous beta)
* **Browser name/version:** Firefox, Chrome, Safari (latest versions)

* **What is the expected behaviour?**
When opening a new video in the playing view, full description should be displayed if the full description was displayed for the previous video. Or the 'show more'/'show less' action should be reseted.

* **What do you see instead?**
  * Open a video with a long description
  * display full description with 'show more' action
  * Open a new video from the others video on the right side : 
     truncated description is displayed but 'show less' action is always here.
     You need to : clic on 'show less' to display 'show more' action and clic to 'show more' to display the full description.

    ![](https://framapic.org/7Un93DyMvj1i/WkX8adJundL2)

(hope my english is good!)

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed: https://github.com/Chocobozzz/PeerTube/commit/c448d41242c5ae3b78830da4fdf37aa21b55a65f

> (hope my english is good!)
Don't worry, what matters is that we can understand the issue :)
