### ISSUE TITLE
Transcoding fails for videos with no audio track

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#4691]
**Describe the current behavior**

Users see an opaque transcoding failure with no explanation, and have to guess at why videos fail to trascode. Server logs have some ffmpeg output that points at the problem.

**Steps to reproduce:**

1. Find a video without any audio track. Verified that this works with a simple ffmpeg test video:

```
ffmpeg -f lavfi -i testsrc=duration=10:size=1280x720:rate=30 -pix_fmt yuv420p -t 1 blah.mp4
```
2. Upload the video. In the case of the 1 second test above the transcode should complete quickly if the queue is empty.
3. "Transcoding failed, this video may not work properly."
4. Server logs show a failure while the audio-only video (resolution 0) transcodes, as the resulting file is empty and ffmpeg protests this:

```
{"level":"error","message":"Cannot execute job 65030 in queue video-transcoding.","label":"diode.zone:443","payload":{"type":"new-resolution-to-hls","videoUUID":"c952789a-abc
0-4559-bfe0-e6d92e3be23a","resolution":0,"isPortraitMode":false,"copyCodecs":false,"isMaxQuality":false,"autoDeleteWebTorrentIfNeeded":true,"isNewVideo":true},"err":{"stack":
"Error: ffmpeg exited with code 1: Output #0, hls, to '/var/www/peertube/storage/tmp/hls/05abcaf1-de50-4502-88db-afb7b5edf31a-0.m3u8':\nOutput file #0 does not contain any st
ream\n\n    at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v4.0.0/node_modules/fluent-ffmpeg/lib/processor.js:182:22)\n    at ChildProcess.emit (events.js:3
14:20)\n    at ChildProcess.EventEmitter.emit (domain.js:483:12)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)","message":"ffmpeg exited with
 code 1: Output #0, hls, to '/var/www/peertube/storage/tmp/hls/05abcaf1-de50-4502-88db-afb7b5edf31a-0.m3u8':\nOutput file #0 does not contain any stream\n"},"timestamp":"2022
-01-05T18:49:06.391Z"}
```

**Describe the expected behavior**

Expected videos without audio tracks to skip the audio-only transcode.

**Additional information**

* PeerTube instance:
  * URL: diode.zone
  * version: 4.0.0
  * NodeJS version:
  * Ffmpeg version: 4.2.4-1ubuntu0.1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by tio-trom** [comment]
Same here. It rarely worked some year ago, but since then it never worked. In my case it doesnt work to transcode the video in any format https://github.com/Chocobozzz/PeerTube/issues/4695

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/cbe2f36d93c779ca08424336be7e3988e57be01d
