### ISSUE TITLE
For how long can a permanent live store the content?

### ISSUE THREAD

**Issue by tio-trom** [Chocobozzz/PeerTube#4692]
Say a permanent live is started and I pause it after a while. Can I, for example, click play and the stream will be resumed, even if it takes me one hour to resume it? Is this gonna work even if the stream ended? I am curious how the permanent live stores the chunks and for how long.

**Comment by Chocobozzz** [comment]
Hi,

You can find values used by peertube for ffmpeg in https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/constants.ts#L684

So ~1 minute is kept by peertube.

**Comment by tio-trom** [comment]
Thanks!
