### ISSUE TITLE
"Private" player embed

### ISSUE THREAD

**Issue by tio-trom** [Chocobozzz/PeerTube#4693]
I would like to embed some lives on my website but not have them link to the original URL. Is that possible? Even if I choose no player controls one can right click the player and get the URL. For example in Vimeo I could create a video and choose to only embed on a particular website, and if you were to see the embed player on that website you would not be able to access that URL on Vimeo. Is this possible with Peertube or something you could add?

Cheers!

**Comment by Chocobozzz** [comment]
Hi,

It's not built in peertube but you can create a plugin to forbid embeds depending on request headers. See https://github.com/Chocobozzz/PeerTube/issues/3773
