### ISSUE TITLE
HLS/ffmpeg/nginx/mp4 Question

### ISSUE THREAD

**Issue by Roki100** [Chocobozzz/PeerTube#4698]
Hello! I have a question about HLS, is there any possibility to make "direct mp4" playing possible of the fragmented mp4 files?
entering `instance.xxx/static/streaming-playlists/hls/videoid/videoid-1080-fragmented.mp4` in browser makes it load for ages before playing
however the webtorrent webseed plays instantly
yes, i know its a fragmented mp4 and stuff but i also tried enabling mp4 addon in nginx to allow `?start= &end=`'ing videos and it errors with `no mp4 trak atoms were found in...` do those atoms exist in fragmented files?, using ffmpeg on fragmented videos makes them playable (`ffmpeg -i fragmentedvideo.mp4 -c copy video.mp4`), does it revert fragmenting it or something?
and my question there is if its by any chance possible to get fragmented videos to start playing instantly or atleast prtty fast while doing direct access of the mp4 (anything can work, plugin, code mod, nginx config mod)?
im on peertube 3.2.1 but i doubt anything has changed in this since 3.2.1
seeking such videos after download is also not possible in windows 10's default video player and this sounds like metadata issue but i dont really know whats normal in fragmented mp4s

**Comment by Chocobozzz** [comment]
Hi,

See https://github.com/Chocobozzz/PeerTube/issues/4130 :)
