### ISSUE TITLE
iPhone as peer

### ISSUE THREAD

**Issue by Vladislavik** [Chocobozzz/PeerTube#4700]
Hi, do you plan to add ios support, like it have [cdnbye](https://demo.cdnbye.com/?ios=true) they use ServiceWorker to intecept requests from ios player and load chunks via p2p even on iPhones [info](https://www.cdnbye.com/en/views/hls-sw/introduction.html)

**Comment by Chocobozzz** [comment]
Hi,

Unfortunately we prefer to not add this complexity to the player. We'll wait mediasource support on ios.

**Comment by snowinszu** [comment]
I think we can integrate cdnbye into PeerTube if possibile :)

**Comment by Vladislavik** [comment]
Cdnbye is shit with big cost, i have already implemented ios p2p support
via js service worker

Ср, 8 февр. 2023 г. в 19:25, snowinszu ***@***.***>:
