### ISSUE TITLE
History does not keep track of video I watched from other instances

### ISSUE THREAD

**Issue by Axeltherabbit** [Chocobozzz/PeerTube#4701]
**Describe the current behavior**
The history does not keep track of video I watched from other instances

**Steps to reproduce**
create and login with an account, search for a video in the fediverse (not local), watch it, the video is not in the history

**Describe the expected behavior**
I would like to have the full history of what I watched and not just the local videos

**Additional information**
PeerTube instance: peertube.wiredentrypoint.xyz
version: 4.0
NodeJS version: v17.3.0
Ffmpeg version: 4.2.4-1ubuntu0.1
Browser name, version and platforms on which you could reproduce the bug:
Chromium 95.0.4638.54 Arch Linux

**Comment by Chocobozzz** [comment]
Please fill the [bug template](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/00-bug-issue.md), in particular the **Steps to reproduce:** part.

**Comment by Axeltherabbit** [comment]
ok, I edited it

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/ac75f640fefb4412a9982b904c043e93fd606966

**Comment by Axeltherabbit** [comment]
thank you :)
