### ISSUE TITLE
Video redundancies are done at all resolutions

### ISSUE THREAD

**Issue by Axeltherabbit** [Chocobozzz/PeerTube#4703]
**Describe the problem to be solved**

When I mirror a video it's mirrored for all resolution, I'd like to be able to mirror just one or more resolution

**Describe the solution you would like:**
I'd like to be able to choose what I mirror, and on the video quality the number of peers should be shown for each available resolution

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but we prefer to keep things simple and not provide the ability to select specific resolutions when mirroring a video.
