### ISSUE TITLE
Create and modify user from other software

### ISSUE THREAD

**Issue by Tuxicoman2** [Chocobozzz/PeerTube#4704]
Hi,

Is it possible to create a user on the local instance using a bash command? Without any email verification.
Is it possible to provide a new password to a user on the local instance using a bash command?

I've looked into server/tools source code but I don't find that.

Thanks,

**Comment by Chocobozzz** [comment]
Hello,

Yes using peertube rest api (https://docs.joinpeertube.org/api-rest-reference.html#operation/addUser and https://docs.joinpeertube.org/api-rest-reference.html#operation/putUser)
