### ISSUE TITLE
Peertube isn't limiting the number of users even though limit is set

### ISSUE THREAD

**Issue by realkinetix** [Chocobozzz/PeerTube#4707]
**Describe the current behavior**

My instance, video.mycrowd.ca has the configuration setting of Signup limit 100 users.
The system currently has 109 users and it's still allowing signups.

**Steps to reproduce:**

1. Enable signups
2. Set user limit to X
3. Signups continue without limit

**Describe the expected behavior**

When the user limit is hit, new users shouldn't be able to be created.

**Additional information**

* PeerTube instance:
  * URL: https://video.mycrowd.ca
  * version: 4.0.0 (issue was present in previous version as well)
  * NodeJS version: 12.22.6-deb-1nodesource1
  * Ffmpeg version: 4.1.6-1~deb10u1

* Browser name, version and platforms on which you could reproduce the bug: Firefox Linux

**Comment by Chocobozzz** [comment]
Hello,

What limit did you set?

**Comment by realkinetix** [comment]
![peertube-limit-signups](https://user-images.githubusercontent.com/13442583/148798769-2d5d417b-9a48-40d9-9859-37c93aeea8ed.png)

Configuration -> New Users -> Enable Signup, Signup Limit = 100

**Comment by Chocobozzz** [comment]
Seems to be a bug in mtcaptcha2 plugin. Try to uninstall it

**Comment by realkinetix** [comment]
Huh, thanks for pointing that out - it did indeed shut down registrations as soon as I removed the plugin.

(I haven't searched yet, but is there a feature request/enhancement for enabling/disabling plugins? I have had to make side notes for the settings relating to mtcaptcha2 for when I re-enable it)

I have filed https://framagit.org/kimsible/peertube-plugin-mtcaptcha2/-/issues/1

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/issues/2856 :)
