### ISSUE TITLE
Question about one API route

### ISSUE THREAD

**Issue by Roki100** [Chocobozzz/PeerTube#4708]
Hello, im running my instance under double-cache due to DDoS activity and i have a question on what `/api/v1/oauth-clients/local` route is for and if it is safe to cache it? It seems to output same tokens for few users so i assume yes but its better to ask

**Comment by Chocobozzz** [comment]
Hello,

This endpoint is used by peertube clients to get oauth client tokens. This API is public but the server checks the `Host` req header to ensure it's called by a client saying it's on your peertube server.
