### ISSUE TITLE
Improve Support for High-Bitrate Content

### ISSUE THREAD

**Issue by Jafner** [Chocobozzz/PeerTube#4710]
**Describe the problem to be solved**

PeerTube's presumed use-case focuses significantly on providing resiliency for video media and making that content accessible practically everywhere. As described in [this comment](https://github.com/Chocobozzz/PeerTube/issues/849#issuecomment-407846433), server-side transcoding is recommended for every production instance. But I believe this ignores a significant use-case for the PeerTube server: video quality samples and extremely high-fidelity content.

**Describe the solution you would like:**

For me, this could be enabled with two features:

* Provide a remux-only transcode option. This would allow me to upload my 1440p165fps content and compare different encoding options. For now, I need to do this locally, but I cannot share this publicly.
* Allow administrators to configure the server with per-upload transcoding options. With the current system, I need to enable or disable transcoding for the entire server. Sometimes I upload a 2-hour video that I *want* transcoded to a smaller, more usable format. And sometimes I upload a 15-second clip that I don't want to suffer any quality reduction.

As an alternative to the above, add a button to download the original file from the video's page. This would require a couple other components as well: permissions for who is allowed to download files, and a per-video configuration setting for preserving the original video.

**Comment by whyronimus** [comment]
It's possible to set the "copy" option for transcoding profiles via the plugin transcoding-profile-debug. But copy doesn't work for video transcoding, since the `-vf` option in ffmpeg is activated. It would very good to have the copy option at least for the original resolution.

Question: Is the original video stored, after transcoding is done? When another transcoding job on the same video is started, is it done from original video or from the transcoded one?

**Comment by Chocobozzz** [comment]
Hello,

Thanks for this issue. Unfortunately the workflow described is too complex to include it in PeerTube core. However we provide a plugin API so you can choose transcoding option (including `copy` encoders) depending on the criteria you want. See https://docs.joinpeertube.org/contribute-plugins?id=add-new-transcoding-profiles

**Comment by Chocobozzz** [comment]
> Is the original video stored, after transcoding is done? When another transcoding job on the same video is started, is it done from original video or from the transcoded one?

Transcoded videos replace original one. See https://github.com/Chocobozzz/PeerTube/issues/733
