### ISSUE TITLE
Feature Request: Automatic Twitch Integration

### ISSUE THREAD

**Issue by 0lhi** [Chocobozzz/PeerTube#4713]
**Describe the problem to be solved**

One of the biggest strength's of PeerTube is the convenience it provides compared to it's competitors when it comes to importing stuff from other platforms. However, a lot of stuff still has to be done manually when importing VODs, Clips and Highlights from Twitch, which does take Energy that not everyone has or is up to provide.

**Describe the solution you would like:**

An ability to connect PeerTube with a Twitch Account, and to enable automatic imports of VODs, Clips and/or Highlights.

The user should be able to decide which kind of video should be uploaded to which Channel. There should be a default set of tags which can be changed later if need be. One Tag should be the Twitch Category, another could be the Streamer Name, and "Twitch" itself would seem appropriate, too.

Description can be something basic like:

"*Source: https;//twitch,tv/videoID*"

For Clips:

"*\[Clipped by TwitchUser12](https;//clips,twitch,tv/ClipID)*"

There should be a setting to decide from what date onward videos should be imported, to avoid duplicate uploads.

There should also be an option to have a delay between making the VOD/Highlight, and the automated Import, to give the Streamer some time to make a proper description/thumbnail.

**Describe alternatives you have considered**  

Doing it manually. For Highlights it's no problem, but more than that is too much.

**Comment by Booteille** [comment]
Hi!

There is actually a subject discussing about automatic integration from other platforms: https://github.com/Chocobozzz/PeerTube/issues/754
