### ISSUE TITLE
Cannot link to other video on same peertube instance in description

### ISSUE THREAD

**Issue by despens** [Chocobozzz/PeerTube#4714]
**Describe the current behavior**
When putting a full HTTP URL into a description that points to another video including a time stamp parameter, the link leads to the current video at that time when activated. When the link is opened in a new tab or new window, the behavior works as expected.

**Steps to reproduce:**

1. Go to some video on a peertube instance. Share a link including "Start at" time from this video.
2. Paste this link into the description of another video on that same instance.
3. Click on the link.

**Describe the expected behavior**
The browser should load the linked video and start at the time contained in the `start` URL parameter.

**Additional information**

* PeerTube instance:
  * URL: https://video.rhizome.org/
  * version: 3.0.1
  * [use-case with link at bottom of description](https://video.rhizome.org/videos/watch/fb2f21aa-a847-43b3-b22b-d9c88821080b)

* Browser name, version and platforms on which you could reproduce the bug: Firefox, Chrome, Epiphany on Linux

**Comment by Booteille** [comment]
I can confirm the bug on 4.0.0

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/696b45deb63bc9f36da9c9ee55c5d4a3a883b87e
