### ISSUE TITLE
[ActivityPub] Comments seem to be in markdown but are missing "mediaType"

### ISSUE THREAD

**Issue by lanodan** [Chocobozzz/PeerTube#4716]
Peertube version: 4.0.0

Example comment: https://video.latavernedejohnjohn.fr/videos/watch/5f701308-5ea1-4714-b00c-feb2c2bcb563/comments/27932

Got: Comment (`as:Note`) with markdown content; no `mediaType`
Expected: Comment with either HTML content (ActivityPub default) or markdown content with `"mediaType": "text/markdown"`, similarly to videos.

**Comment by Chocobozzz** [comment]
Thanks! AP `mediaType` federation should be fixed by https://github.com/Chocobozzz/PeerTube/commit/3726c3725506d0f8a26ded34f42d7bcfb5d0e639
