### ISSUE TITLE
Auto detect subtitles and upload bigger files

### ISSUE THREAD

**Issue by Androz2091** [Chocobozzz/PeerTube#4719]
**Describe the problem to be solved**

I am uploading movies to PeerTube and need to export the subtitles from my MKV files **for each** file, then upload them with the video file. Some files are also very large (+14mo for a .srt file) and can even not be uploaded!

**Describe the solution you would like:**

It would be nice to:
- detect subtitles automatically from the video file
- allow larger subtitles upload. how can I modify the max file size value manually?

**Describe alternatives you have considered**  

Trying to understand my movies without the subtitles 🥲

**Comment by Chocobozzz** [comment]
Hello,

> detect subtitles automatically from the video file

See this existing issue: https://github.com/Chocobozzz/PeerTube/issues/1226

> allow larger subtitles upload. how can I modify the max file size value manually?

I increase captions max size in https://github.com/Chocobozzz/PeerTube/commit/ce7c099f0e36f00d88f7082dd7e158197d3146dd
