### ISSUE TITLE
"Help share videos being played" doesn't work in 4.0

### ISSUE THREAD

**Issue by andrew712-1** [Chocobozzz/PeerTube#4725]
**Describe the current behavior**
When I **uncheck** the "Help share videos being played" box, it doesn't automatically switch to HTTPS, but instead it continues connecting to other peers.

**Steps to reproduce:**

1. watch a video which has a few peers
2. uncheck the "Help share videos being played" box
3. nothing happens, peers are still present
4. reload page
5. the same thing happens

**Additional information**

* PeerTube instance: https://hitchtube.fr

* Browser name, version and platforms on which you could reproduce the bug: Firefox 96.0

**Comment by Chocobozzz** [comment]
Hi,

Should already be fixed on develop in https://github.com/Chocobozzz/PeerTube/commit/bf1c3c78b0e2b70bb46168a9dec0d3fa0997ab14
