### ISSUE TITLE
@peertube/peertube-types package has unwanted dependencies

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4726]
**Describe the current behavior**

When using the type definition package @peertube/peertube-types (see https://github.com/Chocobozzz/PeerTube/pull/4531), there are a lot of unwanted dependencies.
Just by adding this package to the devDependencies of my plugin, there are many additional packages that are installed. See the diff for the `package-lock.json` file of this commit: https://github.com/JohnXLivingston/peertube-plugin-livechat/commit/7db856ce0f523075a74a606eaff60cab354ba516
For example, socket.io is added.

Is this really necessary?
@lutangar , any idea?

* PeerTube instance:
  * version: @peertube/peertube-types 4.0.0-beta3

**Comment by Chocobozzz** [comment]
Hello,

PeerTube types need socket.io types (return type of a middleware function in this particular case)

**Comment by JohnXLivingston** [comment]
Ok, so this was expected and not a side effect. I'm closing the issue.
