### ISSUE TITLE
how can i tjek livestreams ?

### ISSUE THREAD

**Issue by 01123581321345589144233** [Chocobozzz/PeerTube#4727]
Hi i have a smal issue i have enabled live streaming to max 2 users. after i have enabled this i try to stream live.
but it says there are alredy 2 livestreming sesions. how can i tjek the stremingsessions ?
when i go up to 3 it works, but not with 2. i can see in the firewall there is no trafik on the livestream port.

**Comment by Booteille** [comment]
Hi. Users probably configured already two live streams on peertube. Even if those streams are not live, peertube will reserve the place for them.

Either tell your users to don't configure streams they don't use or increase the limit.

**Comment by Chocobozzz** [comment]
See also https://github.com/Chocobozzz/PeerTube/issues/4292
