### ISSUE TITLE
The page isn't redirecting properly.

### ISSUE THREAD

**Issue by Gxnfvhg** [Chocobozzz/PeerTube#4728]
**Describe the current behavior**
When i try to connect to peertube.urgelle.fr, it says that the page isn't redirecting properly, to be clear, it might be because i had to remove `upstream backend {
  server ${PEERTUBE_HOST};
}` because otherwise Nginx just wouldn't restart (I run a mastodon instance on the same server)
**Steps to reproduce:**

1. Install Mastodon
2. Install Peertube
3. Remove upstream_backend
4. Add `config.hosts << peertube.urgelle.fr` to production.rb

**Describe the expected behavior**
I can access my Peertube instance.
**Additional information**
 It also threw a 502 error one time but i don't really know how to reproduce it...
* PeerTube instance: peertube.urgelle.fr
  * URL:
  * version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox, latest, Manjaro
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Gxnfvhg** [comment]
Yes but if i leave in the upstream_backend 9000 that the sed command modifies, i can't restart nginx.

**Comment by Chocobozzz** [comment]
Then paste nginx logs to understand what happens.

**Comment by Gxnfvhg** [comment]
Sorry should have posted them earlier, here : `2022/01/20 00:32:46 [crit] 209874#209874: *2312 SSL_do_handshake() failed (SSL: error:141CF06C:SSL routines:tls_parse_ctos_key_share:bad key share) while SSL handshaking, client: , server: 0.0.0.0:443
2022/01/20 05:02:26 [crit] 209874#209874: *2886 SSL_do_handshake() failed (SSL: error:141CF06C:SSL routines:tls_parse_ctos_key_share:bad key share) while SSL handshaking, client:  server: 0.0.0.0:443
2022/01/20 06:47:27 [crit] 209874#209874: *3039 SSL_do_handshake() failed (SSL: error:141CF06C:SSL routines:tls_parse_ctos_key_share:bad key share) while SSL handshaking, client: , server: 0.0.0.0:443
2022/01/20 12:26:52 [alert] 209874#209874: *3288 open socket #13 left in connection 9
2022/01/20 12:26:52 [alert] 209874#209874: *3295 open socket #25 left in connection 22
2022/01/20 12:26:52 [alert] 209874#209874: aborting
2022/01/20 12:26:52 [emerg] 226391#226391: duplicate upstream "backend" in /etc/nginx/sites-enabled/peertube:18
`

**Comment by Chocobozzz** [comment]
> [emerg] 226391#226391: duplicate upstream "backend" in /etc/nginx/sites-enabled/peertube:18

There is no duplicate upstream "backend" directive in the official nginx template: https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube#L18

Do again steps of https://docs.joinpeertube.org/install-any-os?id=truck-webserver should fix your issue

**Comment by Gxnfvhg** [comment]
I did these steps again but it didn't fix anything, i think it's because the mastodon nginx file also uses upstream "backend". When i change it to backend2, i can launch nginx again.

**Comment by joenepraat** [comment]
Thank you @Gxnfvhg. This worked for me too, because I also have a Mastodon server running on the same VPS.

**Comment by gabrix73** [comment]
Hi,
i have encountered the same issue and i have together with peertube, mastodon up and running.
Thank you @Gxnfvhg. This worked for me too.
