### ISSUE TITLE
Display video file name for video owner

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4731]
**Describe the problem to be solved**
When a user creates different versions of a video it good to know which of the file that's published on the PeerTube instance.

**Describe the solution you would like:**
Video/channel owners can see the filename of the uploaded video file.

**Describe alternatives you have considered**  
Either the filename is shown in the watch view or in the update view. I think YouTube has this functionality, but I don't know how they're showing it.

**Comment by kontrollanten** [comment]
I've started looking at this. Even though it's just a simple field, it was pretty hard to figure out a good place to put the data. In one way it's logical to put in the `video` table, but if we're going to support multiple versions of a video (i.e. updating video files with rollback support), that will break. And by putting it in the `videoFile` table means that the data will be duplicated in multiple rows.

@Chocobozzz What do you think about creating a `videoSource` table which will describe the video file used as source? Today we can put duration and originalFilename in there. If we want to add support for multiple video versions we could move the relationships from `videoCaption`, `videoFile` and `videoStreamingPlaylist` to `videoSource` instead of `video`

**Comment by Chocobozzz** [comment]
This table is a good idea, but I would keep `duration` in `video` table. `videoSource` could also be used to implement https://github.com/Chocobozzz/PeerTube/issues/733

**Comment by kontrollanten** [comment]
> but I would keep `duration` in `video` table

Isn't it better to move all data related to the actual video file to the `videoSource` table? Then we can separate so the data in `videoSource` is only related to the uploaded file (and will never change), whilst all other information, such as title, desc, etc, is in the `video` table?

**Comment by Chocobozzz** [comment]
It's just the duration can be a little bit different before/after transcoding (after merging an audio file and an image for example)

**Comment by kontrollanten** [comment]
Okay. But shouldn't the duration be in the videoFile table then?
