### ISSUE TITLE
To add embed url in the "sharing" -> URL modal.

### ISSUE THREAD

**Issue by klorydryk** [Chocobozzz/PeerTube#4737]
In order to share a video by email or in a chat, the video url is nice to have in the "sharing" window. But in some tools, like CodiMD for example, in doesn't work because this url target the complet page, with all the html environment.

The only way to get the right url is to open "Integration" tab, and extract it from the iframe string.

I would like to have both URL in the first tab: video page and video embed.

Thanks !

**Comment by Chocobozzz** [comment]
Hello,

I'm not sure to understand: you want to paste a peertube URL in CodiMD, and expect the video to be injected in the preview?

**Comment by Xaekai** [comment]
At first I was pondering if OP was inquiring about something like https://oembed.com/ or https://ogp.me/, open source protocols for facilitating embed cards, but looking at [CodiMD](https://codimd.web.cern.ch/features#Externals) it seems to be a riced-out markdown editor that, for a number of video sites, displays an embedded thumbnail with an event listener that [spawns an iframe](https://github.com/hackmdio/codimd/blob/e7a5ea813ab684f5c9569dcee3423dd9c442b9bd/public/js/extra.js#L318) when you click it. It would seem that functionally needs to be tooled at their end.

**Comment by Chocobozzz** [comment]
Thanks for your comment @Xaekai  

PeerTube supports oembed, it's the reason why peertube player can be displayed on mastodon or twitter for example. From your findings, it seems to be an issue that should be created on codimd repository.
