### ISSUE TITLE
Import some videos from 3.2.1 or 2.4.0 to 4.0.0 peertube instance failed

### ISSUE THREAD

**Issue by klorydryk** [Chocobozzz/PeerTube#4738]
Hi,

I have a lot of users who needs to move videos from some old instances (v2 or v3) to new one (v4). They are doing it using url of the videos. But for some of them, it doesn't work.

For example :
- 3.2.1 https://tube-education.beta.education.fr/videos/watch/7d2bdeed-7628-4ff0-9e49-db39c0b181f5
- 2.4.0 : https://tube-versailles.beta.education.fr/videos/watch/6c02ac06-0610-45ec-a7c6-69f8f13266c7

In the same 2.4.0 server, some other videos are correctly imported to a 4.0.0 instance.

It ends with "Cannot fetch remote information of this URL."

It seems it is a youtube-dl error, because when I try to download it manually, I get this error :

> youtube-dl https://tube-versailles.beta.education.fr/videos/watch/6c02ac06-0610-45ec-a7c6-69f8f13266c7
> [generic] 6c02ac06-0610-45ec-a7c6-69f8f13266c7: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] 6c02ac06-0610-45ec-a7c6-69f8f13266c7: Downloading webpage
> [generic] 6c02ac06-0610-45ec-a7c6-69f8f13266c7: Extracting information
> [download] Downloading playlist: Structuration - Les Formes
> [generic] playlist Structuration - Les Formes: Collected 1 video ids (downloading 1 of them)
> [download] Downloading video 1 of 1
> [PeerTube] 6c02ac06-0610-45ec-a7c6-69f8f13266c7: Downloading video JSON
> Traceback (most recent call last):
>   File "/usr/bin/youtube-dl", line 33, in <module>
>     sys.exit(load_entry_point('youtube-dl==2021.12.17', 'console_scripts', 'youtube-dl')())
>   File "/usr/lib/python3.10/site-packages/youtube_dl/__init__.py", line 475, in main
>     _real_main(argv)
>   File "/usr/lib/python3.10/site-packages/youtube_dl/__init__.py", line 465, in _real_main
>     retcode = ydl.download(all_urls)
>   File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2068, in download
>     res = self.extract_info(
>   File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
>     return self.__extract_info(url, ie, download, extra_info, process)
>   File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
>     return func(self, *args, **kwargs)
>   File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 847, in __extract_info
>     return self.process_ie_result(ie_result, download, extra_info)
>   File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 933, in process_ie_result
>     return self.__process_playlist(ie_result, download)
>   File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 1067, in __process_playlist
>     entry_result = self.__process_iterable_entry(entry, download, extra)
>   File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
>     return func(self, *args, **kwargs)
>   File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 1076, in __process_iterable_entry
>     return self.process_ie_result(
>   File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 885, in process_ie_result
>     return self.extract_info(ie_result['url'],
>   File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
>     return self.__extract_info(url, ie, download, extra_info, process)
>   File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
>     return func(self, *args, **kwargs)
>   File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
>     ie_result = ie.extract(url)
>   File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
>     ie_result = self._real_extract(url)
>   File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/peertube.py", line 573, in _real_extract
>     if len(description) >= 250:
> TypeError: object of type 'NoneType' has no len()

Thank you !

**Comment by Chocobozzz** [comment]
Hello,

It's a bug in youtube-dl when importing a video that does not have description. Using [yt-dlp](https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L445) should fix this issue

**Comment by klorydryk** [comment]
It works since the version 2022.12.27. Thanks !
The direct download link can be filled in the file production.yaml with this address: https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
