### ISSUE TITLE
Sharing videos on Jitsi or Presto

### ISSUE THREAD

**Issue by mmmccain** [Chocobozzz/PeerTube#4739]
**Describe the current behavior**
Sharing a link to a peertube video fails with Jitsi or with other applications like Presto Video that claims to work with "any video URL." This was an issue with 3.4 also, but I was hoping it would be resolved in the "cleanup."

* PeerTube instance:
  * URL: ap.okyrios.org
  * version: 4.0
  * NodeJS version: 14.x (as in dependencies)
![image](https://user-images.githubusercontent.com/97072059/150389819-cd4b586b-1c1d-468f-9288-d99eed973ee5.png)

**Comment by Chocobozzz** [comment]
Hello,

I would need Presto Video or Jitsi log explaining why it fails. This issue may also be opened on their bug repository

**Comment by mmmccain** [comment]
I looked through the jitsi logs and even let them run (tail -f) to see what they would drop. Nothing. Just the error above from jitsi meet at the browser. For Presto, nothing in the logs and it does not throw an error. In fact, it acts like it works, but simply fails. I tried with direct links and emded. I also have iframe on their as an example. 

https://lavra.okyrios.org/the-architect/

**Comment by mmmccain** [comment]
I filed a ticket with Presto, they simple said they do not support peertube. They do however support HLS, so this is the approach I am taking with them. There are a couple of items out there on sharing peertube on jitsi, but none where the issue is resolved.

**Comment by mmmccain** [comment]
Here is the answer I received back from the jitsi community. 

"Oh, you mean sharing a video hosted on peertube in a Jitsi meeting. Well, peertube doesn’t give you a direct video link, it gives you a link to a webpage with the video embedded. The ‘Share video’ feature in Jitsi expects a direct video link. And you don’t need to run your own jibri server to use/test the feature - it’s available at meet.jit.si."

Does his answer make sense? Would turning Webtorrent on assist in some way?

**Comment by mmmccain** [comment]
I continue to work this with Presto Made. Here is there latest reply, "At present, we do not have any direct integration with PeerTube. Suman has already shared with the engineering team to check for the feasibility of such an integration. However, if your video hosting service provides you with public link (concluding with .mp4 format - Presto player might be able to play the video)"

This appears to be the common theme between jitsi and presto. They are looking for direct access to the video file. Is this possible with peertube?

**Comment by Chocobozzz** [comment]
Hello,

It seems these services need a specific support of peertube. We provide everything they would need in [the API](https://docs.joinpeertube.org/api-rest-reference.html#operation/getVideo)

Until it is implemented, as a user you can share the video file URL displayed in the "Download" modal

**Comment by rasos** [comment]
If you share a video in Jitsi with a Peertube download link, then all clients are first downloading the full video, before they can watch it together. This may work if the video has a length of only a few minutes, but not for a one hour documentary. 

A workaround is to share in Jitsi the Chrome/Chromium tab where a user plays the video https://github.com/jitsi/jitsi-meet/issues/7601#issuecomment-989012630

Ideally Peertube would provide the same link as it does with Youtube, which is embedded in Jitsi using the format https://www.youtube.com/embed/mHK9YdHydu4?origin=https%3A%2F%2Fmyjitsiserver.net&fs=0&autoplay=0&controls=1&rel=0&enablejsapi=1&widgetid=2
