### ISSUE TITLE
Internal Moderation Notes / Issues

### ISSUE THREAD

**Issue by siberkolosis** [Chocobozzz/PeerTube#4740]
**Describe the problem to be solved**
i have largest and most active of all peertube instances, the problem is hard to communicate or notice between admin and moderator if we have an issue.

**Describe the solution you would like:**

In the moderation menu, add a Staff notes page for internal admin staff and moderators to make notes, and listing notes like the reports page. just like issues pages on github. 

**Describe alternatives you have considered**

**Comment by Chocobozzz** [comment]
Hello,

Thanks for the issue but unfortunately we don't have enough resources to implement this tool, that would be less useful than a dedicated one like a mailing list, internal chat, loomio, discourse etc.

**Comment by Booteille** [comment]
I guess it could also be a good candidate for a plugin.
