### ISSUE TITLE
Please someone create a "Home page" layout similar to the one of Rumble

### ISSUE THREAD

**Issue by andrew712-1** [Chocobozzz/PeerTube#4741]
It could be official or just a plugin, but I think their homepage layout looks cool!
https://rumble.com/

**Comment by vachan-maker** [comment]
there is this new home layout https://diode.zone/

**Comment by andrew712-1** [comment]
nah, doesn't look nearly as good as the one of Rumble, also, can Admins hide the left sidebar by default?
