### ISSUE TITLE
PeerTube Transcription Plugin

### ISSUE THREAD

**Issue by mmmccain** [Chocobozzz/PeerTube#4742]
I would like to be able to use the Transcription Plugin, but it fails to install with the following error looking for node.js 15.0.0. They are not on githug or I would reach out to them directly. Can we update to 15.x? Should we?

warn[1/21/2022, 11:21:41 PM] Cannot install plugin peertube-plugin-transcription.
{
  "err": {
    "err": {
      "stack": "Error: Command failed: yarn add peertube-plugin-transcription@1.6.0\nwarning package.json: No license field\nwarning No license field\nerror peertube-plugin-transcription@1.6.0: The engine \"node\" is incompatible with this module. Expected version \">=15.0.0\". Got \"14.18.2\"\nerror Found incompatible module.\n\n    at ChildProcess.exithandler (child_process.js:383:12)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:475:12)\n    at maybeClose (internal/child_process.js:1058:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)",
      "message": "Command failed: yarn add peertube-plugin-transcription@1.6.0\nwarning package.json: No license field\nwarning No license field\nerror peertube-plugin-transcription@1.6.0: The engine \"node\" is incompatible with this module. Expected version \">=15.0.0\". Got \"14.18.2\"\nerror Found incompatible module.\n",
      "killed": false,
      "code": 1,
      "signal": null,
      "cmd": "yarn add peertube-plugin-transcription@1.6.0"
    },
    "stdout": "yarn add v1.22.17\n[1/4] Resolving packages...\n[2/4] Fetching packages...\ninfo Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.\n",
    "stderr": "warning package.json: No license field\nwarning No license field\nerror peertube-plugin-transcription@1.6.0: The engine \"node\" is incompatible with this module. Expected version \">=15.0.0\". Got \"14.18.2\"\nerror Found incompatible module.\n"
  }
}

* PeerTube instance:
  * 4.0
  * NodeJS version: 14.18.2
  * Ffmpeg version:
  * Redis version:
  * PostgreSQL version:

**Comment by Booteille** [comment]
Hi.

I think you should post your issue on the plugin repository instead: https://gitlab.mim-libre.fr/extensions-peertube/plugin-transcription

Next time you need to reach a plugin repository, check for its name on [npm](https://www.npmjs.com/). e.g: `peertube-plugin-transcription` for this one.

**Comment by mmmccain** [comment]
I am aware of their private gitlab instance, but I am not a member there, nor do they offer registration. I am a member on NPM, but they do not offer the ability to present issues. Neither their private git instance nor npm can provide an answer, which is why I posted here. 

If I missing something, please do advise, but this appears to be the only place to ask the question at this time.

**Comment by Booteille** [comment]
The thing is that this PeerTube repository is dedicated to issues about core PeerTube, not plugins. Plugins are handled independently, especially when they are not "officials" (made by Framasoft).
Either find a way to contact the plugin author or create an account on their forge.

ping @lutangar

**Comment by mmmccain** [comment]
@Booteille I understand and thank you. Hopefully he will reply here. 

@lutangar I would be thank for your assistance.

**Comment by lutangar** [comment]
Sorry for the inconvenience!

Transcription plugin issues aren't "publicly writable" yet (see [issue #37](https://gitlab.mim-libre.fr/extensions-peertube/plugin-transcription/-/issues/37)) but this definitely somewhere on our todo list.

As for the issue itself, the error message is self explanatory, here is the relevant part :
```
The engine "node" is incompatible with this module. Expected version ">=15.0.0". Got "14.18.2"
```

You'll need to install nodejs 15 or higher in order for the plugin to work.
I'd recommend to use the LTS, which is version 16.13.2 at the time of writing.

**Comment by mmmccain** [comment]
@lutangar If I get it working I am going to give it a work out. We have 1000s of videos across 3 languages. Thank you for your work. 

Yes, the exception was very clear. 

As peertube requires Node.js 14.x, how can I safely install 16.13.2 without breaking peertube?

**Comment by Booteille** [comment]
You can safely use nodejs v16 since PeerTube 3.4.0: https://github.com/Chocobozzz/PeerTube/blob/develop/CHANGELOG.md

**Comment by mmmccain** [comment]
I did, it worked and thank you. @lutangar as soon as we can profile public feedback, we will. Thank you for bending the rules and helping us out here.

**Comment by Booteille** [comment]
Happy it worked! You can close the issue if you need no more help.

**Comment by toby3d** [comment]
> You'll need to install nodejs 15 or higher in order for the plugin to work. I'd recommend to use the LTS, which is version 16.13.2 at the time of writing.

I used the latest version of Node (v17.4.0) to install the plugin (v1.6.0) via the following command:
```bash
# cd /var/www/peertube/peertube-latest/ NODE_ENV=production NODE_CONFIG_DIR=/var/www/peertube/config yarn plugin:install -n peertube-plugin-transcription
yarn run v1.22.10
$ node ./dist/scripts/plugin/install.js -n peertube-plugin-transcription
[video.toby3d.me:443] 2022-01-26 12:08:38.287 info: Installing plugin peertube-plugin-transcription.
[video.toby3d.me:443] 2022-01-26 12:08:52.050 info: Successful installation of plugin peertube-plugin-transcription.
[video.toby3d.me:443] 2022-01-26 12:08:52.051 info: Registering plugin or theme peertube-plugin-transcription.
[video.toby3d.me:443 peertube-plugin-transcription] 2022-01-26 12:08:52.460 info: Fetching Vosk models from https://alphacephei.com/vosk/models/model-list.json...
[video.toby3d.me:443 peertube-plugin-transcription] 2022-01-26 12:08:52.500 info: Found 0 valid models for languages: .
[video.toby3d.me:443] 2022-01-26 12:08:52.547 info: Add plugin peertube-plugin-transcription CSS to global file.
[video.toby3d.me:443] 2022-01-26 12:08:52.553 info: Cleaning HTML cache.
[video.toby3d.me:443] 2022-01-26 12:08:52.555 info: Added locale fr-FR of plugin peertube-plugin-transcription.
[video.toby3d.me:443] 2022-01-26 12:08:52.558 info: Added locale en-US of plugin peertube-plugin-transcription.
Done in 19.73s.
```

As you can see from the logs, the plugin was successfully installed. After restarting PeerTube service (just in case), the plugin can be seen in the list of installed, but it has no settings page.

![изображение](https://user-images.githubusercontent.com/5412322/151161685-f2184797-9a54-4a23-92b4-b5959b3c64e6.png)

Attempts to update existing videos with speech up to 30 seconds have no effect on the plugin and no subtitles are generated.

**Comment by Chocobozzz** [comment]
Hello,

Please prefer [the PeerTube forum](https://framacolibri.org/c/peertube/38) to discuss about external plugins so watchers of this repository do not receive discussions of external projects :)

**Comment by UnlimitedCookies** [comment]
For anyone having a similar issue: you need to have the following requisites:
1. Have Gnu Make installed
2. Have GCC installed
3. Have a modern version of NodeJS (the ancient one that is recommended by peertube is not sufficient)

**Comment by bgman111111** [comment]
> I did, it worked and thank you. @lutangar as soon as we can profile public feedback, we will. Thank you for bending the rules and helping us out here.

Can you help me.https://github.com/Chocobozzz/PeerTube/issues/5106
