### ISSUE TITLE
Support internal channel privacy setting

### ISSUE THREAD

**Issue by smilekison** [Chocobozzz/PeerTube#4744]
This feature is in request to feature request https://github.com/Chocobozzz/PeerTube/issues/4733. This feature is in request to provide the channel privacy (Internal) for federated servers.

**Comment by Chocobozzz** [comment]
Hello,

As said in https://github.com/Chocobozzz/PeerTube/issues/4733#issuecomment-1017462147, the channel is not federated if it contains only internal videos.

Unfortunately we don't want to add privacy settings for channels in PeerTube for now.

**Comment by candidexmedia** [comment]
I hope this Issue gets revisited. I hate having empty channels listed on my page because I'm just using it to store private / unlisted videos.

**Comment by Chocobozzz** [comment]
> listed on my page

What page? :)

**Comment by candidexmedia** [comment]
> What page? :)

The public-facing account page that lists all the channels.

**Comment by Chocobozzz** [comment]
Can you create an issue to ignore empty channels on this page?
