### ISSUE TITLE
Retranscoding doesn't work properly with object storage

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4746]
**Describe the current behavior**
When object storage is used and create-transcoding-job is ran, the master playlist and segments file won't be moved to object storage nor updated in the database. The transcoded files will be some kind of orphans that's not connected to any video in the database.

**Steps to reproduce:**

1. Turn on object storage
2. Upload a video
3. Run npm run create-import-video-file-job
4. Run npm run create-transcoding-job

**Describe the expected behavior**
master playlist and segments file should be updated so that the transcoding job will have effect.

**Additional information**
I think it's this `continue` statement that breaks it; https://github.com/Chocobozzz/PeerTube/blob/ebe4b3df5c4e595f3fcf92b8ecf6c5174b13b3b0/server/lib/job-queue/handlers/move-to-object-storage.ts#L85-L87

What's the point with doing this check?

To reduce the complexity it may be easier to create new entries of videoFile and videoStreamingPlaylists in the database upon video-file-import. That would need to have some kind of `active` column in the database to know which videoFile/videoStreamingPlaylist is the accurate. That would also make it possible to rollback a file import, and will probably also help to create a video journal as proposed in https://github.com/Chocobozzz/PeerTube/issues/4320

* PeerTube instance:
  * version: 4.0

**Comment by kontrollanten** [comment]
I tried to just delete the `continue` statement, but it failed (surprise). The move-to-object-storage job succeeded though, even though it shows an error;

```
Error: ENOENT: no such file or directory, stat '/var/www/peertube/storage/streaming-playlists-local/hls/14dd3db0-ef1e-4456-94e6-1fda266f25b3/4835c2cf-575d-4546-98be-38dfa3359fc4-master.m3u8'
```

When I check in the object storage the file stated above is there, so it seems to be ran multiple times.

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/a2caee9f5162232234de2e8aae6957cc7f38c853
