### ISSUE TITLE
HLS: Video player tries to fallback non-existent webtorrent

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4748]
**Describe the current behavior**
When a HLS file for some reasons is corrupt and the media player can't proceed to play it, it will just stop and display a black screen in the media player with a loading spinner that continues for some minutes. After some minutes an error message is displayed for the user; "The media playback was aborted due to a corruption problem or because the media used features your browser did not support.".

**Steps to reproduce:**

1. Make a HLS video corrupt (I don't know exactly how to do that manually though)
2. Play it

**Describe the expected behavior**
At least the error message should be displayed earlier, few users will wait for many minutes. It would be even better if the player tries to go some seconds forward in the video, to skip the corrupted part.

**Additional information**
* Web Torrent disabled.
* HLS enabled, with 240, 360, 480 and 720 resolutions.

Even though web torrent is disabled, it will try to fallback to web torrent and it seems to succeed in fetching the web torrent for resolution 360, and then it will fetch the fragmented mp4 for some seconds.

* PeerTube instance:
  * version: 4.0

* Browser name, version and platforms on which you could reproduce the bug:
Latest Chrome, MacOS
* Link to browser console log if relevant:
Immediately upon crash the following is printed to the web console:
```
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. 
Fallback to webtorrent.
Adding magnet:?xs=...
Adding magnet:?xs=...
ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.
Destroying IndexDB database webtorrent-chunks-3f42c441b9b9e547e3a0c7912be07127589aa3b2.
Removed magnet:?xs=...
webtorrent-plugin.ts:355 DOMException: Failed to load because no supported source was found.
Dexie.delete('webtorrent-chunks-3f42c441b9b9e547e3a0c7912be07127589aa3b2') was blocked
```

**Comment by kontrollanten** [comment]
> it will just stop and display a black screen in the media player with a loading spinner that continues for some minutes

It seems that this is happening because the player is trying to fallback to webtorrent even though there's no webtorrent version of the video.

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/c4207f978e23c77f09c4646b940dfd532281300f
