### ISSUE TITLE
WebTorrent transcoding also transcodes to HLS

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4749]
**Describe the current behavior**
When running a manual WebTorrent transcoding on an existing video, the web torrent will also create jobs for HLS transcoding.

**Steps to reproduce:**

1. Disable transcoding.
2. Upload a video.
3. Enable HLS and WebTorrent transcoding.
4. Run WebTorrent transcoding on the video.
5. See that HLS playlist is created.

**Describe the expected behavior**
It should only run WebTorrent transcoding.

* PeerTube instance:
  * version: 4.0

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/0f11ec8dd32b50897c18588db948e96cf0fc2c70
