### ISSUE TITLE
Move test related configs to test folder

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4751]
**Describe the problem to be solved**
When running tests locally there's a bit unclear whether configs used for development (`yarn dev`) will affect the test configs. As I understand the local.json config file will also affect the tests.

**Describe the solution you would like:**
Move all test configs to `server/tests/config` to distinct them from the ones used for running the platform.

I tried to do this, but the tests failed silently and I didn't mange to figure out how to solve it.

**Comment by Chocobozzz** [comment]
Hello,

Thanks, I should have done this since the beginning of PeerTube ^^ I created a dev environment in https://github.com/Chocobozzz/PeerTube/commit/9452d4fd3321148fb80b64a67bd9983fee6c208e so now you should use `NODE_ENV=dev`. It should not conflict with tests anymore.
