### ISSUE TITLE
Channel-miniature element: Channel not found error

### ISSUE THREAD

**Issue by bmactruth** [Chocobozzz/PeerTube#4752]
**Describe the current behavior**
<peertube-channel-miniature> tag does not display channels properly. This is a brand new instance of Peertube 4.0 and it's not clear what is going on. 

**Steps to reproduce:**
1. Go to https://bitcast.online homepage
2. See screenshot of missing elements.

**Describe the expected behavior**

**Additional information**
I installed 3 plugins:  auto-import-ytb, web-monetization and matomo-analytics.   

I have uninstalled these plugins and still have same result.

* PeerTube instance:
  * URL: https://bitcast.online
  * version: 4.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:  All browsers were tested.
* Link to browser console log if relevant: 
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

<img width="1879" alt="Screen Shot 2022-01-29 at 8 40 41 AM" src="https://user-images.githubusercontent.com/83043401/151673016-21f3fbbb-6847-49c9-8dd8-78fb640f78ff.png">

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/8d9c10bc51d5200175811408578b826fd2cb00bf
