### ISSUE TITLE
instance startup error

### ISSUE THREAD

**Issue by MOHAMADRV2007** [Chocobozzz/PeerTube#4755]
hi 
i did anything in production quide. but wen i want to access the web site this error appeare .
dial tcp: lookup fiscalhub.ir on 127.0.0.11:53: server misbehaving
can anyone help on this error . tnx

**Comment by Chocobozzz** [comment]
Hello,

Please fill the [installation issue template](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/10-installation-issue.md)

**Comment by MOHAMADRV2007** [comment]
hi my server is runig in a test mode with this user and pass . i did anything in installation quide but its didnt work . can please sign in and see why its not runing? tnx a lot for your time and attention .
pass : qRQi31MapA8y44Ww1N
username : root
vnc url : https://hub.iranserver.com/modules/servers/solusvmpro/vnc.php?id=162763
email : mohamadrv2007@gmail.com
anyhelp appreciatable.

**Comment by Booteille** [comment]
@MOHAMADRV2007 Hi! You should really don't paste any login information on this public thread.

Additionally, I don't think Framasoft (sponsoring the project) has resources to allocate to doing this kind of support.

Please, refer to the first comment from @Chocobozzz and fill the template issue and join logs accordingly to your situation.

**Comment by MOHAMADRV2007** [comment]
i installed peertube on ubuntu 20.04 with instruction for dependencies in https://docs.joinpeertube.org/dependencies and installation quide in https://docs.joinpeertube.org/install-any-os
nodejs -v 14.18.3
ffmpeg 4.2.4-1
redis-server 5.0.7
psql : 12.9 
when i using vpn in browser this error is appeare dial tcp: lookup fiscalhub.ir on 127.0.0.11:53: server misbehaving
and when im not using it this error is appeare This site can’t be reachedCheck if there is a typo in fiscalhub.ir.
If spelling is correct, [try running Windows Network Diagnostics](javascript:diagnoseErrors()).
DNS_PROBE_FINISHED_NXDOMAIN
ping messege for server ip (135.181.124.44) dosent have any error 
any help is appercated
