### ISSUE TITLE
Explain how to do unit tests for PeerTube plugins

### ISSUE THREAD

**Issue by smilekison** [Chocobozzz/PeerTube#4757]
Hello everyone, 

Currently, I am working on a plugin that fetches data from the database and visualizes it in the UI (custom dashboard). 

For the development of the plugin, I am using server hook and client hooks as defined by the PeerTube.
 
For server hook, I am using `peertubeHelpers.database.query()` to perform queries on the database. Then fetched data is served to create the API route using `getRouter()`.

Using client hook `registerClientRoute` I have created a client route that retrieves data from the above API. And within the hook `registerClientRoute` I have created some functions that use the data from the API and inject it into DOM elements. 

Now, I am trying to perform unit testing (and some others) on this plugin but I couldn't find many references regarding the Unit Testing on the plugins. So, I would like to ask if there is a format to perform Unit testing on PeerTube Plugins or if anyone has done unit testing on their plugin for references.

**Comment by kontrollanten** [comment]
Hello! Since the help functions are passed as arguments, I think you should be able to create mock functions with sinon. Something like

```
const mockPeertubeHelpers = {
  database: {
    query: sinon.stub()
  }
};

register({ peertubeHelpers: mockPeertubeHelpers });

expect(mockPeertubeHelpers.database.query.calledOnce).to.have.equal(true);
```

**Comment by kontrollanten** [comment]
I'm sorry but I haven't done any unit tests on the plugins I've written. Maybe it can be worth to create a npm package containing the mock functions?

**Comment by smilekison** [comment]
@kontrollanten, right now, I have no idea where, to begin with for unit testing. If you could help me with this one I would be thankful as you have experience writing plugins for PeerTube or we can collaborate together!

**Comment by kontrollanten** [comment]
I'm sorry but I don't have time for that right now.

**Comment by smilekison** [comment]
Hello,

@kontrollanten @Chocobozzz 

I tried to perform Unit Testing. For this, I used JEST tool for creating mockup. ` I have done a sample which passed the unit test. ` Here is the function: 
```
function getUserId(user, peertubeHelpers, logger) {
  const results = peertubeHelpers.database.query(
    'SELECT "id" from "user" WHERE "username" = $username',
    {
      type: "SELECT",
      bind: { username: user.username },
    }
  );
  logger.info("results", results);

  return results;
}
```

The unit test of the above function: 

 ```
 test('testing calledWithExactly', () => {
    const user = {
      username: 'root'
    }
    const mockPeertubeHelpers = {
      database: {
        query: sinon.stub()
      }
    }
    const logger = {
      info: sinon.stub()
    }
    getUserId(user, mockPeertubeHelpers, logger)
    expect(mockPeertubeHelpers.database.query.calledWithExactly('SELECT "id" from "user" WHERE "username" = $username', {
      type: "SELECT",
      bind: {
        username: user.username
      },
    })).toBe(true);
  })
```

I have done the same thing for another function which didn't pass the unit testing. Here is the function and test code: 
```
function getTotalSubscriber(results, peertubeHelpers, logger) {
  const totalSubscribers = peertubeHelpers.database.query(
    `SELECT sum(a."followersCount") as "followersCount"
    FROM "actor" a
    JOIN "videoChannel" vc on vc."actorId"=a."id"
    JOIN "account" ac on ac."id"=vc."accountId"
    JOIN "user" u on u."id" = ac."userId"
    WHERE u."id"=$userId`,
    {
      type: "SELECT",
      bind: { userId: results[0].id },
    }
  );
  logger.info("This is totalSubscribers: ", totalSubscribers);
  return totalSubscribers;
}
```

Unit Test Code: 
```
test('testing calledwithexactly', () => {

        const results = [{
            id: 1
        }]

        const mockPeertubeHelpers = {
            database: {
                query: sinon.stub()
            }
        }
        const logger = {
            info: sinon.stub()
        }

        getTotalSubscriber(results, mockPeertubeHelpers, logger)

        expect(mockPeertubeHelpers.database.query.calledWithExactly(`SELECT sum(a."followersCount") as "followersCount"
            FROM "actor" a
            JOIN "videoChannel" vc on vc."actorId"=a."id"
            JOIN "account" ac on ac."id"=vc."accountId"
            JOIN "user" u on u."id" = ac."userId"
            WHERE u."id"=$userId`, {
            type: "SELECT",
            bind: {
                userId: results[0].id
            },
        })).toBe(true);
    })
```

Here I am doing same for both test cases calling "CalledWithExactly" I assumed that both should return true value. However, the first test case is returning true and the second case is returning false. 

![Screenshot from 2022-02-25 10-06-11](https://user-images.githubusercontent.com/24309222/155653834-d11ea058-5c90-4033-a8d2-f2c4b8c68936.png)

**Comment by kontrollanten** [comment]
Hello. I don't think this is issue is related to PeerTube. I think you can debug further by comparing the arguments with something like `expect(mockPeertubeHelpers.database.query.getCalls(0).args[0].to.equal(...)`
