### ISSUE TITLE
GDPR compliance: Option to disable p2p functions in an embed

### ISSUE THREAD

**Issue by kuba-orlik** [Chocobozzz/PeerTube#4759]
**Describe the problem to be solved**

In order to achieve full GDPR compliance, the website administrator has to have control over which server is the website sending requests to. This also applies to iframes embedded on the given website.

Due to p2p functionalities, embedding an iframe with a Peertube video can lead to requests that for example lead outside of EU jurisdiction. This is a potential issue from GDPR standpoint. 

Recently even embedding Google Fonts is frowned upon (and fined!), so an additional layer of control is necessary.

**Describe the solution you would like:**

An optional parameter to an embed link, say `disablep2p=true`, that if set - makes the embedded player use only the source server for downloading video.

**Describe alternatives you have considered**

1. Disable the tracker and remote redundancies (with obvious performance penalty for users visiting the instance directly, not through the embed)
2. Using a `<video>` tag with a static mp4 link. This is bad because it doesn't affect the view count and doesn't let easily pick custom resolutions etc.

I have currently settled on choosing 1.

**Comment by b90g** [comment]
+1 

- would love to see it on the instance itself as well, right now we completely disabled the p2p for that reason.
- a consent dialog/window would be great so the user/viewer can make a decision 
- especially live streaming is of interest. (since jitsi supports it)
 
Wasnt able to find a bounty program, let me know if there is any so i can bring it back to an organisation which sends me here :)

**Comment by Chocobozzz** [comment]
Hello,

In the next version administrators will have the choice to enable/disable p2p: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L93

You'll also be able to disable P2P when you share an embed using query param in URL (a checkbox will be available in the share modal).
