### ISSUE TITLE
Error during publication

### ISSUE THREAD

**Issue by DerLothringer** [Chocobozzz/PeerTube#476]
* PeerTube version or URL: 1.0.0-beta3
* Browser name/version: Firefox 56 (Linux)
* NodeJS version:v9.11.1
* PostgreSQL: v9.6.7
* OS : Debian Stretch

* What is the expected behaviour?
Publication ok after clicking Publish button
* What do you see instead?
**Error message : "Error Server error. Please retry later."**

After a successful upload, the publication fails...
It seems a PostgreSQL error, so I dropped the database, then I recreated it, but the error is always here. It was my first video.
[peertube_git.txt](https://github.com/Chocobozzz/PeerTube/files/1884151/peertube_git.txt)

**Comment by Chocobozzz** [comment]
Can you go inside psql and run `SHOW SERVER_VERSION` please?

And can you run the server with debug logger (see the config file) and retry to reproduce the bug?

**Comment by DerLothringer** [comment]
Hello Chocobozzz,

Here is the result of the query command :  9.1.24lts2

I tried to reproduce the bug, and the debug file is attached.

[peertube_debug.txt](https://github.com/Chocobozzz/PeerTube/files/1886239/peertube_debug.txt)

**Comment by DerLothringer** [comment]
The problem is solved. I've upgraded my PostgreSQL version to 9.6 and it works fine, now.
