### ISSUE TITLE
Tag Index contains a lot of unrelated items

### ISSUE THREAD

**Issue by DeadSuperHero** [Chocobozzz/PeerTube#4762]
I've noticed this on older instances as well as newer ones: If I click on a tag index, even if no content actually has a matching tag, there ends up being a lot of unrelated stuff.

Check it out:

* [Tag term "Aliens"](https://vidcommons.org/search?tagsOneOf=Aliens)
* [Tag term "France"](https://vidcommons.org/search?tagsOneOf=France)
* [Tag Term "Sandwich"](https://vidcommons.org/search?tagsOneOf=Sandwich)
* [Tag Term "Teleport"](https://vidcommons.org/search?tagsOneOf=Teleport)

This is actually bad for local or in-network discovery of videos - it makes the process for finding videos less obvious for users because there's a bunch of unrelated results in each index. 

Here's the kind of behavior I expect: if there aren't any matching results, don't show anything. If there are results, they should only match the query - there shouldn't be unrelated results in them.

**Comment by Chocobozzz** [comment]
Hello,

This will be fixed by https://github.com/Chocobozzz/PeerTube/commit/8cf43a6524d354fbfa0f0eaf789e8d4756bd25d6: if you filter on tags, peertube will only display videos. Then, you should not have these unrelated channel/playlist results anymore
