### ISSUE TITLE
Sort by name

### ISSUE THREAD

**Issue by oricou** [Chocobozzz/PeerTube#4763]
Hi,

Could you add a "Sort by name" in a video channel (where the default value is "Sort by Recently Added")? I want to order my video and the easiest way for me is to give them numbers: "01 Introduction" "02 What is a language?" etc
I know that there is the Playlist to do that, but adding videos in a playlist is a real pain, you have to start each video to add them!

Thanks for all,

Olivier.

**Comment by kontrollanten** [comment]
Hi! You can add them to a playlist from the list page by clicking on the dots in the right corner, and then choose "Add to playlist".

**Comment by oricou** [comment]
No, I didn't and thank because it is faster, however if you have 50 videos, it is still 200 clicks!

**Comment by Chocobozzz** [comment]
Hi,

If I understand well the use case, I'm closing this issue in favour of https://github.com/Chocobozzz/PeerTube/issues/2754 where we could ease videos bulk addition.
Sorting by name from the interface would require an additional index in the database leading to performance and storage overhead

**Comment by oricou** [comment]
Sure bulk addition is fine for my case however there is another case which is "Looking for the vidéo named Charlot" when you have 50 vidéos. If sorted by name, it helps.
I am confused to see a "hot" index or a "likes"index which I couldn't care less, but no name index which seems basic. I would be very confused if my ls command lists file in a hot order!
Names do have a meaning.

**Comment by Chocobozzz** [comment]
> Sure bulk addition is fine for my case however there is another case which is "Looking for the vidéo named Charlot" when you have 50 vidéos. If sorted by name, it helps.

Then please create an issue so we add a search field in channel's page

> In Microsoft there is a sort by name and we use it

You want to sort videos of another channel by name or your own videos?

**Comment by oricou** [comment]
It is not only search. You have a list of videos and you want a global view to see if everything is fine (name are consistant, no video is missing...). In that case you need to see all videos in name order.

I would like a 'Sort by "Name"' as a choice everywhere you have a menu with default value 'Sort by "Recently Added"' i.e. in channels but also in Trending and Local videos.
