### ISSUE TITLE
Show "access denied" when visiting a private/internal video

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4768]
**Describe the problem to be solved**
When a user is visiting a watch page of a video that's private/internal, the user will be redirected to login form if it's not logged in. This may be confusing for the user since it's not clear why they're going to the login page.

**Describe the solution you would like:**
It would be better if an access denied message would be shown, with a link to the login page.

**Comment by Chocobozzz** [comment]
What about  a message above the login form? ("You need to be connected to access this resource")

**Comment by kontrollanten** [comment]
That would work. But I'd prefer something more user friendly; "You need to be logged in to see this video".
