### ISSUE TITLE
Blocking subscriptions before the end of subscription

### ISSUE THREAD

**Issue by Epy** [Chocobozzz/PeerTube#4770]
Hello everyone
On joinpeertube.org we can find instances to create a account which in fact doesn't accepts accounts BUT that not what I came to tell:
[It seems incorrectly reported by the instance as stated here: https://www.orion-hub.fr/about/instance]

The behaviour is strange: The peertube instance allowed me to type all my info to create an account and then told me it doesn't accept new accounts anymore

**Steps to reproduce:**

1. Go to joinpeertube.org/instances select your criteria, in my case: "content creator" "create an account" "live yes" "gaming"
2. Select an instance, in my case: https://www.orion-hub.fr/
3. Follow steps to create an account
4. Get the message "We don't accept new accounts"

(Messages translated from french and from memory for the last one, so not exactly accurate sorry)

It would be better to show the error message right at the click on "create an account" button of the instance. Or even better: disable the button and display the message with an infotip or anything that suits accessibility the best

**Additional information**

* PeerTube instance:
  * URL: https://www.orion-hub.fr/
  * version: 4.0.0
  * NodeJS version: Unknown (user)
  * Ffmpeg version: Unknown (user)

* Browser name, version and platforms on which you could reproduce the bug: Firefox ESR on Debian 10, but probably not relevant ;)

I didn't find any issue about this, I hope I did not made a duplicate or a report on a old version.

Thanks

**Comment by Chocobozzz** [comment]
Hello,

I think it's an issue on this specific instance, coming from a plugin. This registering issue should not happen with other instances. I used their contact form to notify them about that.

**Comment by Epy** [comment]
Oh ok, sorry. I could have contact them but I thought it was a vanilla software problem.
Thank you

**Comment by Nalem14** [comment]
Hi,

I'm the owner of this instance and I have found this issue on google when searching for "Orion-hub" by accident.
For some (unknown) reason I'm don't have received the email that you have send Choco...

Thanks for reporting this, I have tested but I can make an account without problem and some others users is registering every days without issues.

Can you confirm that is resolved on your side ?
Thanks a lot for your report, have a good day !

(Sorry for reopening this issue,  I just want to be sure that all users can register without error)

**Comment by Epy** [comment]
Hi
Happy little mistake ^_^
I'm sorry I didn't try registering again, I found another instance to try streaming.
If you have others registering without any problem it probably was a temporary problem, or you fixed it while maintaining your instance.
Thanks for asking
