### ISSUE TITLE
Cannot Forward live broadcast service via nginx-rtmp to any peertube instence

### ISSUE THREAD

**Issue by rt4mn** [Chocobozzz/PeerTube#4778]
I followed a mix of [this guide](https://www.artificialworlds.net/blog/2021/11/22/streaming-to-twitch-and-peertube-simultaneously-using-nginx-on-oracle-cloud/
) and [this page](https://github.com/arut/nginx-rtmp-module/wiki/Installing-via-Build) to setup a dedicated debian 11 nginx VPS to multi-stream to peertube and twitch (and youtube and owncast). Peertube is currently the only streaming service that will not work, nginx-rtmp re-broadcasts to all of the others listed there just fine. 

On peertube the stream indicates as "started", and I can hit the play button and the loading circle will start, but the video never actually starts playing. Will just load forever. 

I have tried our own self hosted instance at https://watch.rt4mn.org and also https://diode.zone and also https://peertube.su so it does not seem to be an issue with just our peertube instance (all three servers are running peertube V 4.0.0)

I have tested playback with updated versions of firefox and chrome. 

If I stream directly to the peertube instance with obs, the stream will play live just fine. 

If I stream directly from the vps with ffmpeg, the stream will play live just fine. command I use for that is `ffmpeg -re -i streamtest.mp4 -vcodec libx264 -vprofile baseline -g 30 -acodec aac -strict -2 -f flv rtmp://watch.rt4mn.org:1935/live/streamkey`. It is only when I try to use the nginx-rtmp module that it does not work. 

Normally I use a "permanent live", but iIf when setting up the live stream in peertube I set the settings to "Stream only once and save a replay of your live", the stream will still not work, but once I finish streaming it does manage to save recording of the stream, and it does replay the video just fine. 

I have tested several different versions of the nginx-rtmp-module, but none have worked. although the only two I can say for sure do not work are v 1.21.4 and the most recent version.

Current nginx config on the vps is:

```

rtmp {
    server {
        listen 1935;
        chunk_size 4096;
        application live {
            live on;
            record off;
            push rtmp://stream.cyberia.club/live/streamkey
            push rtmp://live.twitch.tv/app/live_streamkey;
            push rtmp://a.rtmp.youtube.com/live2/streamkey;
            push rtmp://watch.rt4mn.org:1935/live/streamkey;
        }
    }
}
```

I've tinkered with a bunch of different chunk sizes / configs here but none seem to work. Even just having peertube all by itself without the other streaming services does not seem to work. 

I am still not sure if the issue is something with peertube or something with nginx-rtmp, so I am opening the issue on both repos. 

https://github.com/arut/nginx-rtmp-module/issues/1661

**Comment by Chocobozzz** [comment]
Hello,

It seems nginx-rtmp does not correctly send the RTMP metadata command. See for example several issues on their repository: https://github.com/arut/nginx-rtmp-module/issues/578, https://github.com/arut/nginx-rtmp-module/pull/509 or https://github.com/arut/nginx-rtmp-module/issues/1292

As mentioned in https://github.com/arut/nginx-rtmp-module/issues/1292#issuecomment-490323251, peertube expects `|@setDataFrame|onMetaData|Object|`, but nginx-rtmp sends `|onMetaData|Object|` which means we can't handle the metadata object.
Since PeerTube did not store metadata, it won't be able to forward it. Without metadata, ffprobe cannot guess stream bitrate. In muxing mode, ffmpeg needs to guess the bitrate to correctly fill `master.m3u8`. Since it has not, `master.m3u8` is not filled and peertube player cannot play the video.

**Comment by rt4mn** [comment]
I don't have "meta copy;" anywhere in my nginx-rtmp configs, so there is nothing to remove to fix the issue.

**Comment by Chocobozzz** [comment]
I'm sorry but we can't fix this in PeerTube. Ideally, it should be fixed on nginx-rtmp-module side. You could also propose to handle handle this bug in https://github.com/illuspas/Node-Media-Server (dependency we use to manage RTMP streams).

**Comment by rt4mn** [comment]
> I'm sorry but we can't fix this in PeerTube. Ideally, it should be fixed on nginx-rtmp-module side. You could also propose to handle handle this bug in https://github.com/illuspas/Node-Media-Server (dependency we use to manage RTMP streams).

Good to know. I might look into a fork of that module, since it looks like that version is pretty stale. 

Thanks so much for all the work you do, and for the insight regarding the nature of the issue!
