### ISSUE TITLE
Display a message if the user connection doesn't support the peer to peer

### ISSUE THREAD

**Issue by JamesDAdams** [Chocobozzz/PeerTube#4779]
**Describe the problem to be solved**
I have a user who have a internet connection who does not support the peer to peer

**Describe the solution you would like:**
Display a message for the user who have a internet connection who does not support the peer to peer

**Comment by Chocobozzz** [comment]
Hello,

We prefer to not confuse users with this kind of message by default, because most of them don't understand what is P2P. But you can try to create a plugin if you still want to display it on your instance: https://docs.joinpeertube.org/contribute-plugins
