### ISSUE TITLE
demo site trends not populating on browsers in iOS

### ISSUE THREAD

**Issue by scottrlarson** [Chocobozzz/PeerTube#478]
https://peertube.cpy.re/videos/trending
Safari/Firefox iOS

Expected Behavior: The trends section to populate videos
Actual Behavior: The trends section is blank

I was just testing the demo links for watching a video from mobile browsers on the iOS platform.  I didn't see any issues reported regarding this and just wanted to make sure that this issue is happening.

**Comment by Chocobozzz** [comment]
I'm sorry but I cannot reproduce. What is your iOS, firefox and safari versions?

**Comment by Chocobozzz** [comment]
The Firefox and iOS versions are outdated. We cannot support too old web browser :/

**Comment by Serkan-devel** [comment]
@scottrlarson Firefox or Chrome on iOS is just simply Safari with a different UI ontop. Can you go to https://httpbin.org/user-agent and paste the result here? Maybe the Safari version has partial support
