### ISSUE TITLE
Problem with yt-dlp and timeout in peertube

### ISSUE THREAD

**Issue by Sir-Grizzly** [Chocobozzz/PeerTube#4780]
**Describe the current behavior**

I have a problem with Direct download URL , I use yt-dlp plugin and after 1 hour system/job peertube show me FAILED

Job: 39 
Type: video-import 
Processed on Feb 8, 2022, 6:08:13 AM 
Finished on Feb 8, 2022, 7:08:13 AM
--
{
   "type": "youtube-dl",   
   "videoImportId": 39,   
   "fileExt": ".mp4"
}

Error: YoutubeDL download timeout.     
       at Timeout._onTimeout (/var/www/peertube/versions/peertube-v4.0.0/dist/server/helpers/youtube-dl/youtube-dl-wrapper.js:68:46)     
       at listOnTimeout (internal/timers.js:557:17)     
       at processTimers (internal/timers.js:500:7)
 
-- but yt-dlp continues to download the video in the background and saves the complete movie file in storage/tmp and I can't publish that movie.

* PeerTube instance:

  * version: 4.0.0
  * NodeJS version: 14
  * Ffmpeg version: 4.3.3

**Comment by Chocobozzz** [comment]
Hello,

It's weird the import takes so much time. Could you paste the URL you try to import?

Anyway, I increased timeout in https://github.com/Chocobozzz/PeerTube/commit/7630e1c893f9848dce9d94135ce9b9a21ab80788

**Comment by Sir-Grizzly** [comment]
Thanks. I need sometimes import video 1080p 2-3GB from youtube and the problem is only with youtube :( they try to hinder the download by cutting the transfer, that why I need more time to import video.

Thanks again !
