### ISSUE TITLE
Please implement minimal installation via bash script

### ISSUE THREAD

**Issue by zackees** [Chocobozzz/PeerTube#4781]
**Describe the problem**

I just want to evaluate peertube and I attempted to spin up an instance. I was unsuccessful in my two hour time frame. I realized that I have to make a whole bunch of decisions and learn about those tools to make the right decisions.

Looking at the build script it became very apparent that what could solve this problem is two things:

  * 1) All build steps are combined into a shell script which can be executed like so:
`curl https://peertube.url/file/install_demo_ubuntu_20_lts.sh | bash`
  * 2) Proper modifications are made so that the `install_demo_ubuntu_20_lts.sh` can run in one script. I know there are certain blockers today such as the webhost being locked to a certain name that can't be changed. What is blocking this from changing?
  
  
  Then match this installation script with a specific Ubuntu VMware player image so that executing this one line above will install the entire thing.

Being able to see all the features and iterate on the demo would REALLY lower the barrier of entry for people spinning up their own instances without having to surmount the barrier, which requires the developer/user to being a web systems expert in order to run it.

**Comment by kontrollanten** [comment]
Hi! I remember it was tricky for me as well to get it up and running the first time, even though it was some years ago now. I agree that it would be really great to just get an instance up and running with as less config as possible. Maybe the install script can read properties from env variables, and if they're not set there's defaults (such as peertube.local as host)?

Was there any specific step you got stuck on?

**Comment by Chocobozzz** [comment]
Hi,

It would be great to know what are the frictions in the install guide so we can improve it.

Regarding this install bash script, it's already available on https://github.com/YunoHost-Apps/peertube_ynh/

**Comment by zackees** [comment]
Okay, I created one that works pretty well for the first few steps.

https://github.com/zackees/peertube_ezinstall_ubuntu20LTS.

If anyone runs into the same desire to have a single one line install, please contribute to this repo

https://github.com/zackees/peertube_ezinstall_ubuntu20LTS
