### ISSUE TITLE
Handle network issues appropriate in media player

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#4782]
**Describe the current behavior**
When watching a HLS video and the internet connection goes offline the player just becomes black with a spinner.

**Steps to reproduce:**

1. Visit https://peertube.cpy.re/w/rjy7vLphL2DL4gFA73twWN
2. Set the network connection to offline
3. Start the video

**Describe the expected behavior**
A user friendly message should be shown describing the issue and let them restart the video. Maybe the message should just be shown and then we're waiting for the network issue to be solved, and then automatically continue the video.

* PeerTube instance:
  * URL: https://peertube.cpy.re/w/rjy7vLphL2DL4gFA73twWN

* Browser name, version and platforms on which you could reproduce the bug: Latest Brave
* Link to browser console log if relevant:

```
hls-plugin.ts:255 HLS.js error: networkError - fatal: false - levelLoadError {type: 'networkError', details: 'levelLoadError', fatal: false, url: 'https://peertube2.cpy.re/static/streaming-playlist…7ba/cd0ba4ee-9763-44b4-a66f-3550eaf987ba-480.m3u8', loader: T, …}
hls-plugin.ts:226 trying to recover network error
VM205:1 GET https://peertube2.cpy.re/static/streaming-playlists/hls/cd0ba4ee-9763-44b4-a66f-3550eaf987ba/cd0ba4ee-9763-44b4-a66f-3550eaf987ba-480.m3u8 net::ERR_INTERNET_DISCONNECTED
...
peertube-player-manager.ts:212 Fallback to webtorrent.
VM205:1 GET https://peertube2.cpy.re/static/streaming-playlists/hls/cd0ba4ee-9763-44b4-a66f-3550eaf987ba/cd0ba4ee-9763-44b4-a66f-3550eaf987ba-480.m3u8 net::ERR_INTERNET_DISCONNECTED
...
webtorrent-plugin.ts:340 Error: http error from xs param: https://peertube.cpy.re/lazy-static/torrents/0ac21bb2-2479-4ef7-b549-b15cee21b745-480-hls.torrent
index.js:64 WebSocket connection to 'wss://peertube2.cpy.re/tracker/socket' failed: 
webtorrent-plugin.ts:340 Error: Error connecting to wss://peertube2.cpy.re/tracker/socket
```

**Comment by emansom** [comment]
I configured NGINX to only allow a certain amount of HLS requests per second in order to share bandwidth more evenly across users.

Sometimes eager people overload this limit by skipping too fast, crashing the video player.

I very much welcome this functionality 👍🏻
