### ISSUE TITLE
defaults: privacy: 4 is not reflected on /about/instance under "Video uploads"

### ISSUE THREAD

**Issue by decentral1se** [Chocobozzz/PeerTube#4783]
**Describe the current behavior**

When I set the following in my `production.yaml`:

```yaml
defaults:
  publish:
    privacy: 4
```

Then I restart and look under `/about/instance`, I see:

![image](https://user-images.githubusercontent.com/1991377/153172934-d10eb27d-daf1-4484-bb10-7ca35f355909.png)

**Steps to reproduce:**

1. Change default privacy settings to 4
2. Restart app
3. Look at about page

**Describe the expected behavior**

I should see "internal", like indicated on https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L86.

**Additional information**

* PeerTube instance:
  * URL: n/a
  * version: v4.0.0 (docker)
  * NodeJS version: v4.0.0 (docker)
  * Ffmpeg version: v4.0.0 (docker)

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello :)

See https://github.com/Chocobozzz/PeerTube/issues/4784#issuecomment-1033616706
