### ISSUE TITLE
defaults: download_enabled: false is not reflected on /about/instance under "Video uploads"

### ISSUE THREAD

**Issue by decentral1se** [Chocobozzz/PeerTube#4784]
**Describe the current behavior**

When I set the following in my `production.yaml`:

```yaml
defaults:
  download_enabled: false
```

Then I restart and look under `/about/instance`, I see:

![image](https://user-images.githubusercontent.com/1991377/153176116-cb8328b4-d1b6-4915-bb93-8e3b7810242e.png)

**Steps to reproduce:**

1. Change default download settings to false
2. Restart app
3. Look at about page

**Describe the expected behavior**

I expect to see "downloads disabled by default", like indicated on https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L81. Like the NSFW policy info.

**Additional information**

* PeerTube instance:
  * URL: n/a
  * version: v4.0.0 (docker)
  * NodeJS version: v4.0.0 (docker)
  * Ffmpeg version: v4.0.0 (docker)

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

This table is not intended to display all instance configuration, but only ones we think are important enough (to keep it simple). Default download policy, that can easily be changed by uploaders is not a very important information.
