### ISSUE TITLE
Show best-practise video format properties for upload

### ISSUE THREAD

**Issue by Matthias84** [Chocobozzz/PeerTube#4788]
**Parts of the documentation concerned:**

At webfrontend a hint should appear

**Describe the desired information/correction**

There should be a hint, which video formats are known to work well. Similar to [this listing](https://gist.github.com/mikoim/27e4e0dc64e384adbcb91ff10a2d3678) that documents compatibility for youtube...

_(I had problems to upload FFMPEG generated / converted struggle on the transcode step and as user Iam unable to fix it and to get it listed on my channels)_

**Comment by Chocobozzz** [comment]
Hello,

What were your ffmpeg errors? Input file should not break transcoding (and so specifying input format should affect transcoding process)

**Comment by Chocobozzz** [comment]
> So are there any limitations or recommend video profiles you can use enable / avoid unnecessary (re/trans)coding of your uploaded videofiles?

No, there should not be any limitation and if transcoding fails with a specific format, your admin can fill an issue so we fix it.
Unfortunately, with HLS we can't avoid transcoding.
