### ISSUE TITLE
Ability to register custom api calls

### ISSUE THREAD

**Issue by Master-Minder** [Chocobozzz/PeerTube#4789]
In order to customize server side functionality, it would be great to have the option to register custom api calls, maybe in a similar way the the registerClientRoute works. Obviously this would also requiere the possibility to inject a custom server side handler for the api calls including the ability to access the db.

**Comment by Chocobozzz** [comment]
Hello,

You can already register custom server routes using https://docs.joinpeertube.org/contribute-plugins?id=add-custom-routes :)
