### ISSUE TITLE
Channel presentation video

### ISSUE THREAD

**Issue by HarleyQuinn-Z6** [Chocobozzz/PeerTube#4791]

**Comment by Booteille** [comment]
Hi.

Could you please fill the [template for features](https://raw.githubusercontent.com/Chocobozzz/PeerTube/develop/.github/ISSUE_TEMPLATE/30-feature-request.md) (I guess you ask for a feature) requests, please?

**Comment by Chocobozzz** [comment]
Hello,

I think I understood the use case so I'm closing this issue in favour of https://github.com/Chocobozzz/PeerTube/issues/3997
