### ISSUE TITLE
Installation on Android

### ISSUE THREAD

**Issue by master255** [Chocobozzz/PeerTube#4802]
@Chocobozzz How about installing on Android devices?
It would be very cool to download the server app on Android TV (which runs 24\7 even if you turn it off with the remote control) from Play Market. Override the port on the router, buy a domain and make your PeerTube instance without knowledge of computers.

Why haven't you done this yet?

**Comment by Chocobozzz** [comment]
Hello,

Thanks for this issue but for now it's out of the scope of PeerTube. Of course anyone can try to bundle PeerTube in an Android app', and explain the process on our forum :)
