### ISSUE TITLE
Add RSS feed number of items configuration

### ISSUE THREAD

**Issue by master255** [Chocobozzz/PeerTube#4803]
@Chocobozzz I watch Peertube channels through the RSS feed. No matter what format it displays a very small number of recent videos.
If you increase the number of items, it will not create a load on the server, but will allow to watch more videos.
You need to change the default setting to 200 videos.

Better yet, add a tag to the url for viewing a certain number of videos.

**Comment by master255** [comment]
@Chocobozzz And add the parameter in the url: &maxitems=200

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/db9d882c2567fba197754a1f6fd1d75114d33560

**Comment by sbinet** [comment]
apologies for the drive-by comment, but I am wondering if the `&maxitems=200` feature had been implemented ?
(looking at the commit, I'd say "no", but my Typescript is rubbish.)

**Comment by Chocobozzz** [comment]
> apologies for the drive-by comment, but I am wondering whether the &maxitems=200 feature had been implemented ?

It has not :)

**Comment by master255** [comment]
It's a freak development

**Comment by sbinet** [comment]
I am not sure I get what you meant by that, but it would be very useful to have that extra query argument.
IIUC, only the admin of the peertube instance can change the default number of items in a feed.
being able to modify this from the user/client side would be great (and IIUC, wouldn't incur too big of a resources hit).
