### ISSUE TITLE
PeerTube 5.0

### ISSUE THREAD

**Issue by master255** [Chocobozzz/PeerTube#4804]
@Chocobozzz For over a year now, my Media Library player has had torrents that can be edited.
The idea is that the person distributing these torrents can change them while they are being distributed. 
I recently added RSS feed compatibility to the player. And the PeerTube RSS feed is supported.
Yesterday I added saving/reading url-list in info section when creating/editing torrents. This allowed me to convert any https link (link directory or link site) to an internet file into a torrent link or magnet link (editable torrents). Basically, if I add links to pictures and file descriptions in the torrent ( maybe a sub torrent) to the info section, it will be a mobile PeerTube, without the need to create a website and knowledge of computers. But I won't do that as there are no users and no one needs it in my player. And I won't use it myself.

Without moving url-list to info section it is impossible to download torrent file from DHT with url-list. It will be deleted. This is the functionality request. You need to move the url-list to the info section and then the distribution effect will be much greater.

**Comment by Chocobozzz** [comment]
Hello,

Thanks for the issue but it's out of the scope of peertube
