### ISSUE TITLE
Disable P2P Serverside?

### ISSUE THREAD

**Issue by anon97945** [Chocobozzz/PeerTube#4806]
Hello, how do i deactivate p2p serverside? Would like to have it turned off by default.

**Comment by Booteille** [comment]
Hi. 

It's under admin settings.

In transcoding options, there is the ability to disable HLS/Webtorrent.

**Comment by anon97945** [comment]
i did, i need to have atleast 1 activated. i tried disable HLS with P2P and also webtorrent... :-( cant disable both. and its still p2p whatever i do.

**Comment by Chocobozzz** [comment]
Hi,

> In transcoding options, there is the ability to disable HLS/Webtorrent.

HLS also uses P2P :)

To disable P2P on your instance, you can disable the tracker: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L227

In 4.1, you can also set the default p2p policy for anonymous users and new users: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L93

**Comment by Booteille** [comment]
> HLS also uses P2P :)

Ha yeah, I knew it but I didn't thought you had either the option to use Webtorrent or HLS but none to disable both (which makes sense because without one of them there is no video) and so the option to totally remove p2p would not be one of them.
Sorry!
