### ISSUE TITLE
When commenting with remote account, it's not shown on peertube

### ISSUE THREAD

**Issue by librewarrior** [Chocobozzz/PeerTube#4808]
**Describe the current behavior**
I posted a comment on a peertube video with my mastodon account. The comment was readable by the creator. I know because I got a reply. But it wasn't publicly visible on the peertube site itself. However it was publicly visible from the mastodon account. 

**Steps to reproduce:**
Used [my home instance](https://snabelen.no) to comment on a [video](https://tilvids.com/w/7SogZFoiS8BbL3Ukfieq7N). Which resulted in this [comment](https://snabelen.no/@vega/107837861526803608).

**Comment by AnonymousWebHacker** [comment]
Same !
PeerTube Version: 4.1.0-rc.1
I try to make a comment from an instance of mastodon and the comments are not published on peertube.

I'll try peertube-v4.1.0. when i update in a few minutes

**Comment by drym3r** [comment]
Related to the issue I opened, when it works I do see the comment on the peertube page, FYI.

**Comment by Chocobozzz** [comment]
Hello,

tilvids instance is outdated. Could you try to comment a video of another instance?

**Comment by FediVideos** [comment]
Tilvids just upgraded to 4.1, might be worth trying again?

**Comment by FediVideos** [comment]
This may be a related issue:

When posting a comment on Tilvids, it only appears if I am following the Tilvids account that posted the video.

For example, try posting on the video https://tilvids.com/w/qwSoseemEse2coifHgBYiL without following its creator, then try posting another comment after following the creator. Only the second comment will appear.

**Comment by Chocobozzz** [comment]
What was the first account to comment?

**Comment by FediVideos** [comment]
Just tried this several times again, it seems to be working fine now. Posting a comment appears (after a short delay) whether you're following the PeerTube account or not.

**Comment by Chocobozzz** [comment]
Thanks @FediVideos!
