### ISSUE TITLE
All videos not playing after version up to 4.1

### ISSUE THREAD

**Issue by TechnicalSuwako** [Chocobozzz/PeerTube#4809]
**Describe the current behavior**
「Refused to load media from '〇〇' because it violates the following Content Security Policy directive: "default-src https: data: 'unsafe-inline' 'unsafe-eval'". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback.」and「VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.」on all videos.

**Steps to reproduce:**

1. watch a video
2. error will come

**Describe the expected behavior**
Can play video.

**Additional information**
Can be played by LightPeer (PeerTube without JS).
Example:
https://video.076.ne.jp/w/wNuVKa7EvTu9WArTdkBRLB ← not playing
https://lightpeer.076.ne.jp/w/wNuVKa7EvTu9WArTdkBRLB ← playing

* PeerTube instance:
  * URL: https://video.076.ne.jp/
  * version: 4.1
  * NodeJS version: v17.5.0
  * Ffmpeg version: 4.3.3-0+deb11u1

* Browser name, version and platforms on which you could reproduce the bug: all
* Link to browser console log if relevant: please see above
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): no error

**Comment by binarydad** [comment]
Is this a docker or native install? I was about to update my docker instance when I saw this.

**Comment by Chocobozzz** [comment]
Hello,

Try to disable CSP

**Comment by TechnicalSuwako** [comment]
> Is this a docker or native install? I was about to update my docker instance when I saw this.

native



> Hello,
> 
> Try to disable CSP

where?
nginx? html? peertube configure?

**Comment by Chocobozzz** [comment]
In peertube: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L216

**Comment by TechnicalSuwako** [comment]
It seems that csp → enabled is already set to false

**Comment by Chocobozzz** [comment]
Then maybe it's added by nginx? Or another software in front of your peertube instance

**Comment by TechnicalSuwako** [comment]
⚡ root@mail  /etc/nginx  grep -Rr "Content-Security-Policy"
conf-available/headers.conf:add_header Content-Security-Policy "default-src https: data: 'unsafe-inline' 'unsafe-eval'";
conf-enabled/headers.conf:add_header Content-Security-Policy "default-src https: data: 'unsafe-inline' 'unsafe-eval'";
grep: sites-enabled.bak/default: そのようなファイルやディレクトリはありません

 ✘ ⚡ root@mail  /etc/nginx  cat conf-enabled/headers.conf
add_header X-Frame-Options sameorigin;
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection '1; mode=block';
add_header X-Download-Options noopen;
add_header X-Permitted-Cross-Domain-Policies none;
add_header Content-Security-Policy "default-src https: data: 'unsafe-inline' 'unsafe-eval'";
add_header Referrer-Policy strict-origin;

 ⚡ root@mail  /etc/nginx 

**Comment by TechnicalSuwako** [comment]
PeerTube and LightPeer is same sarver.

**Comment by AnonymousWebHacker** [comment]
@TechnicalSuwako I did a video search on your instance, and it sent me a 500

![Captura de pantalla de 2022-02-23 14-01-49](https://user-images.githubusercontent.com/43164089/155389138-5b57c43e-9b22-47e8-89a2-ba922d9a8559.png)

**Comment by AnonymousWebHacker** [comment]
@TechnicalSuwako I did a video search on your instance, and it sent me a 500

![Captura de pantalla de 2022-02-23 14-01-49](https://user-images.githubusercontent.com/43164089/155389138-5b57c43e-9b22-47e8-89a2-ba922d9a8559.png)

**Comment by TechnicalSuwako** [comment]
> @TechnicalSuwako I did a video search on your instance, and it sent me a 500
> 
> ![Captura de pantalla de 2022-02-23 14-01-49](https://user-images.githubusercontent.com/43164089/155389138-5b57c43e-9b22-47e8-89a2-ba922d9a8559.png)

It's still under development, so I understand.

**Comment by TechnicalSuwako** [comment]
```
Refused to connect to 'wss://video.076.ne.jp/socket.io/?accessToken=〇〇&EIO=4&transport=websocket&sid=imctDCyHF1QQ5jlIAAAp' because it violates the following Content Security Policy directive: "default-src https: data: 'unsafe-inline' 'unsafe-eval'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

doOpen @ websocket.js:54
```

```
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.
ze
  code: 4
  message: "The media could not be loaded, either because the server or network failed or because the format is not supported." 
 [[Prototype]]: Object
    MEDIA_ERR_ABORTED: 1
    MEDIA_ERR_CUSTOM: 0
    MEDIA_ERR_DECODE: 3
    MEDIA_ERR_ENCRYPTED: 5
    MEDIA_ERR_NETWORK: 2
    MEDIA_ERR_SRC_NOT_SUPPORTED: 4
    code: 0
    message: ""
    status: null
(anonymous) @ core.js:234
```

```
MEDIA_ERROR:  The video could not be loaded, either because the server or network failed or because the format is not supported
(anonymous) @ hls-plugin.ts:144
```

when will you fix?

**Comment by Chocobozzz** [comment]
I'm sorry @TechnicalSuwako but I don't understand what you want me to fix. From https://github.com/Chocobozzz/PeerTube/issues/4809#issuecomment-1048869573 we can see you're adding `CSP` in your nginx config: `add_header Content-Security-Policy "default-src https: data: 'unsafe-inline' 'unsafe-eval'";`. Just try to remove it.

Closing as this is not a peertube issue, but a sysadmin one.

**Comment by TechnicalSuwako** [comment]
> I'm sorry @TechnicalSuwako but I don't understand what you want me to fix. From [#4809 (comment)](https://github.com/Chocobozzz/PeerTube/issues/4809#issuecomment-1048869573) we can see you're adding `CSP` in your nginx config: `add_header Content-Security-Policy "default-src https: data: 'unsafe-inline' 'unsafe-eval'";`. Just try to remove it.
> 
> Closing as this is not a peertube issue, but a sysadmin one.

Thank you!
It's work!
