### ISSUE TITLE
Wrong docker tag for v4.1.0?

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4810]
I think that there was an error in the docker image tag name.
https://hub.docker.com/r/chocobozzz/peertube/tags

![image](https://user-images.githubusercontent.com/38844060/155343442-e22f0cde-70ab-4dea-be99-5788cfb8a17f.png)

The tag peertube:v4.0.0-bullseye should be peertube:v4.1.0-bullseye , no?

**Comment by Chocobozzz** [comment]
`peertube:v4.1.0-bullseye` is not ready yet. We have some issues with our CI

**Comment by oe1rfc** [comment]
It seems that the [v4.1.0-bullseye](https://hub.docker.com/layers/chocobozzz/peertube/v4.1.0-bullseye/images/sha256-90c26a5a27a48fc90852a9e72fcd742086dbba8560bced4fc6ec7d1d6e7722a5?context=explore) tag with node updated to 14.19.0 has been pushed, and `production-bullseye` now points to the same image hash.

**Comment by JohnXLivingston** [comment]
Thanks @Chocobozzz and @oe1rfc  :)
