### ISSUE TITLE
python3 is missing in docker image for 4.1.0

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#4812]
Hello !

It seems that for the recent 4.1.0 release, python3 was forgotten inside the docker image.
Thus it causes impossibility to use ytp-dl to fetch video :
```
 2022-02-24 12:55:26.786 Cannot fetch information from import for URL https://www.youtube.com/watch?v=6n-Ic9CMaL4.
 "shortMessage": "Command failed with ENOENT: /usr/bin/python3 /data/bin/youtube-dl --dump-json -f [...]
```

Indeed when looking inside the image, python is correctly installed (as in https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/Dockerfile.bullseye#L5) BUT it's python 2
```
# /usr/bin/python --version
Python 2.7.18
```

The binary directly called by peertube is not present:
```
# ls /usr/bin/python3
/usr/bin/python3: File not Found
```

When installing python3 directly inside the image, the import feature works:
```
apt update
apt install python3
=> import from peertube working
```

I have no idea why debian bullseyes still point to python2 when installing python, but I guess we need to specify python3 in the dockerfile :-/

Thanks!

**Comment by LecygneNoir** [comment]
Okay, when trying to install the python virtual package inside the docker image, it auto-select `python-is-python2` instead of python-is-python3 😭 

```
# apt install python
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'python-is-python2' instead of 'python'
python-is-python2 is already the newest version (2.7.18-9).
```

This is the explanation why we have python2 instead of 3 in the docker image. However, I found anything from debian that explain this, and why it could be different in prior versions

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/pull/4813
