### ISSUE TITLE
Upgrade from 4.0.0 to 4.1.0 fails in a weird way

### ISSUE THREAD

**Issue by jpatje** [Chocobozzz/PeerTube#4814]
Tried several times to upgrade but the output gets really weird and it ends with no clear clues. Here is a partial log (first part and the last part all the way at end end of this post), I pasted a few lines where it inflates packages and all seems to go well. After that it shows 'differences in configuration files' and outputs a lot of data from my setup, don't know which files it comes from. If needed, i will post the full log.
I did the 'any OS' upgrade line from the official documentation (cd /var/www/peertube/peertube-latest/scripts && sudo -H -u peertube ./upgrade.sh)

--------------------------------------------------------------------------------------------------------------------------------

  __inflating: peertube-v4.1.0/support/systemd/peertube.service
  inflating: peertube-v4.1.0/yarn.lock
yarn install v1.22.11
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ test -n "$NOCLIENT" || (cd client && yarn install --pure-lockfile)
Done in 0.51s.
Differences in configuration files...
--- /var/www/peertube/config/production.yaml    2021-12-16 15:53:46.801606399 +0100
+++ /var/www/peertube/versions/peertube-v4.1.0/config/production.yaml.example   2022-02-22 08:47:34.000000000 +0100
@@ -5,7 +5,7 @@
  Correspond to your reverse proxy server_name/listen configuration (i.e., your public PeerTube instance URL)
 webserver:
   https: true
-  hostname: 'I.removed.my.hostname.for.privacy.com'
+  hostname: 'example.com'
   port: 443

 rates_limit:
@@ -31,31 +31,15 @@
 If you run PeerTube behind a remote proxy, add the proxy IP address (or subnet)
 trust_proxy:
   - 'loopback'__
   
  **_[There is a lot more to come after this, I will also post the last few lines under here, after it returns to the CLI. So here are the last lines:]_**

 followers:
@@ -528,3 +619,16 @@
     disable_local_search: false
     # If you did not disable local search, you can decide to use the search index by default
     is_default_search: false
+
+# PeerTube client/interface configuration
+client:
+  videos:
+    miniature:
+      # By default PeerTube client displays author username
+      prefer_author_display_name: false
+
+  menu:
+    login:
+      # If you enable only one external auth plugin
+      # You can automatically redirect your users on this external platform when they click on the login button
+      redirect_on_single_external_auth: false

**Comment by Chocobozzz** [comment]
Hello,

It seems the update succeeded. At the end of the script, we display a diff of your current configuration file and the official template so you can update your configuration.
It's written in the output:
```
Differences in configuration files...
--- /var/www/peertube/config/production.yaml 2021-12-16 15:53:46.801606399 +0100
+++ /var/www/peertube/versions/peertube-v4.1.0/config/production.yaml.example 2022-02-22 08:47:34.000000000 +0100
```

Once you've updated your config, don't forget to restart PeerTube (https://docs.joinpeertube.org/install-any-os?id=auto):

```
sudo systemctl restart peertube
```

**Comment by Chocobozzz** [comment]
What is the output of `sudo journalctl -eu peertube`?

**Comment by jpatje** [comment]
Feb 26 15:14:39 zeus peertube[720979]:       "native": false
Feb 26 15:14:39 zeus peertube[720979]:     },
Feb 26 15:14:39 zeus peertube[720979]:     {
Feb 26 15:14:39 zeus peertube[720979]:       "column": 18,
Feb 26 15:14:39 zeus peertube[720979]:       "file": "internal/modules/cjs/helpers.js",
Feb 26 15:14:39 zeus peertube[720979]:       "function": "require",
Feb 26 15:14:39 zeus peertube[720979]:       "line": 74,
Feb 26 15:14:39 zeus peertube[720979]:       "method": null,
Feb 26 15:14:39 zeus peertube[720979]:       "native": false
Feb 26 15:14:39 zeus peertube[720979]:     },
Feb 26 15:14:39 zeus peertube[720979]:     {
Feb 26 15:14:39 zeus peertube[720979]:       "column": 23,
Feb 26 15:14:39 zeus peertube[720979]:       "file": "/var/www/peertube/versions/peertube-v4.1.0/dist/server.js",
Feb 26 15:14:39 zeus peertube[720979]:       "function": null,
Feb 26 15:14:39 zeus peertube[720979]:       "line": 65,
Feb 26 15:14:39 zeus peertube[720979]:       "method": null,
Feb 26 15:14:39 zeus peertube[720979]:       "native": false
Feb 26 15:14:39 zeus peertube[720979]:     },
Feb 26 15:14:39 zeus peertube[720979]:     {
Feb 26 15:14:39 zeus peertube[720979]:       "column": 30,
Feb 26 15:14:39 zeus peertube[720979]:       "file": "internal/modules/cjs/loader.js",
Feb 26 15:14:39 zeus peertube[720979]:       "function": "Module._compile",
Feb 26 15:14:39 zeus peertube[720979]:       "line": 999,
Feb 26 15:14:39 zeus peertube[720979]:       "method": "_compile",
Feb 26 15:14:39 zeus peertube[720979]:       "native": false
Feb 26 15:14:39 zeus peertube[720979]:     },
Feb 26 15:14:39 zeus peertube[720979]:     {
Feb 26 15:14:39 zeus peertube[720979]:       "column": 10,
Feb 26 15:14:39 zeus peertube[720979]:       "file": "internal/modules/cjs/loader.js",
Feb 26 15:14:39 zeus peertube[720979]:       "function": "Module._extensions..js",
Feb 26 15:14:39 zeus peertube[720979]:       "line": 1027,
Feb 26 15:14:39 zeus peertube[720979]:       "method": ".js",
Feb 26 15:14:39 zeus peertube[720979]:       "native": false
Feb 26 15:14:39 zeus peertube[720979]:     },
Feb 26 15:14:39 zeus peertube[720979]:     {
Feb 26 15:14:39 zeus peertube[720979]:       "column": 32,
Feb 26 15:14:39 zeus peertube[720979]:       "file": "internal/modules/cjs/loader.js",
Feb 26 15:14:39 zeus peertube[720979]:       "function": "Module.load",
Feb 26 15:14:39 zeus peertube[720979]:       "line": 863,
Feb 26 15:14:39 zeus peertube[720979]:       "method": "load",
Feb 26 15:14:39 zeus peertube[720979]:       "native": false
Feb 26 15:14:39 zeus peertube[720979]:     }
Feb 26 15:14:39 zeus peertube[720979]:   ]
Feb 26 15:14:39 zeus peertube[720979]: }
Feb 26 15:14:39 zeus peertube[720979]: [my.peertubesite.com:443] 2022-02-26 15:14:39.448 info: Database peertube_prod is ready.
Feb 26 15:14:39 zeus peertube[720979]: [my.peertubesite.com:443] 2022-02-26 15:14:39.567 info: Using smtp-mail.outlook.com:587 as SMTP server.
Feb 26 15:14:39 zeus peertube[720979]: [my.peertubesite.com:443] 2022-02-26 15:14:39.569 info: Testing SMTP server...
Feb 26 15:14:39 zeus peertube[720979]: [my.peertubesite.com:443] 2022-02-26 15:14:39.583 error: Cannot start application. {
Feb 26 15:14:39 zeus peertube[720979]:   "err": {
Feb 26 15:14:39 zeus peertube[720979]:     "stack": "ReferenceError: Cannot access 'server_config_manager_1' before initialization\n    at /var/www/peertube/versions/peertube-v4.1.0/dist/server.js:1>
Feb 26 15:14:39 zeus peertube[720979]:     "message": "Cannot access 'server_config_manager_1' before initialization"
Feb 26 15:14:39 zeus peertube[720979]:   }
Feb 26 15:14:39 zeus peertube[720979]: }
Feb 26 15:14:39 zeus systemd[1]: peertube.service: Main process exited, code=exited, status=255/EXCEPTION
Feb 26 15:14:39 zeus systemd[1]: peertube.service: Failed with result 'exit-code'.
Feb 26 15:14:39 zeus systemd[1]: peertube.service: Scheduled restart job, restart counter is at 25589.
Feb 26 15:14:39 zeus systemd[1]: Stopped PeerTube daemon.
Feb 26 15:14:39 zeus systemd[1]: Started PeerTube daemon.
Feb 26 15:14:40 zeus peertube[721015]: [my.peertubesite.com:443] 2022-02-26 15:14:40.124 warn: Your NodeJS version v12.22.10 is deprecated. Please upgrade.

**Comment by chatainsim** [comment]
Same issue for me, seems to have update nodejs for the system not peertube.
How can we update nodejs for peertube ? Thanks

**Comment by chatainsim** [comment]
Find a way.
When node upgrade, he change is location:
```
# whereis node
node: /usr/bin/node /usr/local/bin/node /usr/include/node /usr/share/man/man1/node.1.gz
```
/usr/bin/node -v gave me v12 and /usr/local/bin/node -v gave me v16, so removed /usr/bin/node and made a symbolic link.
```
rm /usr/bin/node
ln -s /usr/local/bin/node /usr/bin/node
```

**Comment by jpatje** [comment]
> sudo journalctl -eu peertube

Simon, you're the man! Thanks a lot! Got my instance working again and finally updates to version 4.1.0 :)
