### ISSUE TITLE
Upgrading from 4.0 to 4.1

### ISSUE THREAD

**Issue by marcopavanello** [Chocobozzz/PeerTube#4815]
**Describe the current behavior**
Hi, I'm getting this error during the upgrading process from version 4.0 to 4.1 when executing the automatic upgrade command `cd /var/www/peertube/peertube-latest/scripts && sudo -H -u peertube ./upgrade.sh` from https://docs.joinpeertube.org/install-any-os and don't know how to fix it.
![Screenshot from 2022-02-24 23-39-37](https://user-images.githubusercontent.com/8861988/155620291-5c04168e-0c9e-475f-b985-dae1958171f0.png)

**Comment by tcitworld** [comment]
Install Nodejs 14, NodeJS 12 was depreciated in 4.1 but is actually incompatible.

**Comment by marcopavanello** [comment]
The latest version of NodeJS in Ubuntu 20.04 is 12.22, how can I update it?

**Comment by kontrollanten** [comment]
https://github.com/nodesource/distributions/blob/master/README.md#debinstall
