### ISSUE TITLE
Some video imported from dailymotion have a duration bug

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4817]
**Describe the current behavior**

Hello,
I'm currently importing videos from dailymotion to archive some content. And for some videos, I have a weird bug. Not all videos are concerned, but a lot of them.

Here is one of the original videos: https://www.dailymotion.com/video/xanghr
Its duration is 3:39.

I'm importing it with the CLI (v4.0.0), but I have the exact same bug when importing from the Peertube web interface (v4.0.0 and v4.1.0). 
Once the video is imported, the duration shown in lists is the correct one (3:39): https://www.yiny.org/search?search=pogomarto%20-%20j%27ai%20peur&searchTarget=local
![image](https://user-images.githubusercontent.com/38844060/155684836-086539d7-b504-4926-8817-90dd693e6c97.png)

But when I open the video, the player thinks its double time (7:18): https://www.yiny.org/w/j19UCTjhsFitoWSqPAZXMQ
![image](https://user-images.githubusercontent.com/38844060/155684945-7269db0f-2e70-4af3-a618-e26e9fb1d631.png)

And the playback stops at 3:39.
If I go forward, I can see some requests in my browser's console that actually return content (http status 206, videos are in HLS format). There is no error log on the frontend.

I tried on 2 Peertube instances, with CLI or with web interface, v4.0.0 and v4.1.0. Same bug every time.

I'm using yt-dlp on the server. When using the cli, i'm using youtube-dl I think (I did not configure anything, i'm using a git clone of the Peertube repo)

**Steps to reproduce:**

1. Import https://www.dailymotion.com/video/xanghr
2. Try to view the video

**Describe the expected behavior**

**Additional information**

* PeerTube instance:
  * URL: https://www.yiny.org
  * version: v4.1.0
  * NodeJS version: 14.19.0
  * Ffmpeg version: ffmpeg version 4.3.3-0+deb11u1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by JohnXLivingston** [comment]
I forgot: if you find and fix the bug, I am also interested in a way to correct the existing data.

**Comment by Chocobozzz** [comment]
Hello,

It seems to be a ffmpeg bug. If I download manually the video, and just run `ffmpeg -i input.mp4 outpout.mp4` we can see `output.mp4` video stream duration doubled.

**Comment by JohnXLivingston** [comment]
Ok, make sense.
Any idea why there are 2 different duration displayed in Peertube? (one in lists, one when playing). I assume the second one is displayed by the player, once the video begins to load? If so, it means we only need to wait a fix in ffmeg, then run transcoding again. I'm I right?

**Comment by JohnXLivingston** [comment]
I can see a bug reports for ffmpeg that's maybe related: https://trac.ffmpeg.org/ticket/6832 (old but reopened).
I'll open a new one, just in case it is not the same bug.

**Comment by Chocobozzz** [comment]
> If so, it means we only need to wait a fix in ffmeg, then run transcoding again. I'm I right?

Right!

Then closing this issue since it's not a peertube bug.

**Comment by JohnXLivingston** [comment]
Seems that this is not considered as a bug: https://trac.ffmpeg.org/ticket/6832#comment:14
I don't know what «editlist» is, and don't know what to think of this response.

I'll assume that this bug is due to some old videos from dailymotion, and that it will not appear again. 
But I don't know how to fix my videos... I assume that transcoded HLS videos don't have the «editlist» anymore...

**Comment by Chocobozzz** [comment]
You can try to fix the videos manually and then "reupload" them using https://docs.joinpeertube.org/maintain-tools?id=create-import-video-file-jobjs

**Comment by JohnXLivingston** [comment]
Ok, thanks.
