### ISSUE TITLE
User and last connection date

### ISSUE THREAD

**Issue by binerf** [Chocobozzz/PeerTube#4818]
**Describe the problem to be solved**
Getting information related to user connections (time and date) to purge and clean-up database from inactive users.

**Describe the solution you would like:**
In the user information page, display last connection (or full list of user's connections) date/time.

Thank you !

**Comment by Chocobozzz** [comment]
Hi,

I was going to implement this issue but in fact it's already done ^^ You can display more columns using the dropdown on the left of the *username* column

![screen_2022-05-24-15:17:19](https://user-images.githubusercontent.com/5180488/170044318-b91faca2-9969-4f0c-a378-125a75bb93ae.png)

I made some changes in https://github.com/Chocobozzz/PeerTube/commit/87a0cac618c8ed4a09408273d0f5a468530e8062:
 * I fixed the sort (so NULL values come first on last login ASC sort)
 * We now display automatically the last login date (I think it's an important information)
 * We restore previously selected columns from local storage

**Comment by binerf** [comment]
Oh yes !!

Sorry, didn't know this option to add more columns.

Many thanks !
