### ISSUE TITLE
Upload causes "Unknown error", possible misparsed URL behind HAProxy

### ISSUE THREAD

**Issue by kenneaal** [Chocobozzz/PeerTube#4819]
**Describe the current behavior**
Attempting to upload a video to a Peertube instance behind a HAproxy instance fails, due to a badly formated URL returned as redirect from POST.

**Steps to reproduce:**

1. Install and configure Peertube with remote proxying, running Peertube in HTML mode.
2. Set up HAProxy for SSL offloading and backending directly to Peertube
3. Create an account and attempt to upload a video.
4. The upload fails, with Peertube log showing the URL being malformed: https://peertube.mydomain/api/v1/videos/https,%20 https://peertube.mydomain/api/v1/videos/upload-resumable?upload_id=2-83885f505e8e67399e7d9a151ac71778

**Describe the expected behavior**
Being able to upload videos.

**Additional information**

* PeerTube instance:
  * URL: https://contactbymessage.ifneeded/
  * version: 4.0.0
  * NodeJS version: 17.5.0
  * Ffmpeg version: 4.4-6

* Browser name, version and platforms on which you could reproduce the bug: Any platform and browser, 
* Link to browser console log if relevant: https://paste.fuelrats.com/puzajojoha.log
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): https://paste.fuelrats.com/uvibalisap.json

**Comment by Chocobozzz** [comment]
Hi,

Issue seems to come from `x-forwarded-proto` header that contains an array (`http, https`) where our library expect a single value. So is it a valid value?

**Comment by kenneaal** [comment]
Hm. That is very curious. HAProxy is set up to set X-Forwarded-Proto to https in the frontend, so I'm not sure how it gets turned into an array. HAProxy points directly to Peertube, so I have no other way to inspect the headers being sent to the app.

**Comment by Chocobozzz** [comment]
It seems there is something in your system setup that inject this incorrect header. Finding and fixing this should also fix the issue on peertube

**Comment by kenneaal** [comment]
Greetings.

It doesn't seem like that's the heart of the problem. By setting up HaProxy to temporarily forward to Nginx (running the Peertube provided config), the requests are parsed correctly, but hangs before completion:
`{"message":"Getting access token (bearerToken: f8xxxx).","level":"debug","label":"peertube.localecho.net:443","timestamp":"2022-03-03T12:49:29.399Z"}
{"parameters":{"name":"274521043_689358832068932_5529350405890275689_n","mimeType":"video/mp4","size":"24860739","lastModified":"1645575800000","waitTranscoding":true,"commentsEnabled":true,"downloadEnabled":true,"channelId":2,"nsfw":false,"privacy":"3","filename":"274521043_689358832068932_5529350405890275689_n.mp4"},"headers":{"x-forwarded-for":"192.168.1.85, 192.168.1.85, 192.168.1.1","host":"peertube.localecho.net","x-real-ip":"192.168.1.1","connection":"close","content-length":"1249","sec-ch-ua":"\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"98\", \"Microsoft Edge\";v=\"98\"","sec-ch-ua-mobile":"?0","authorization":"Bearer f8f1cxxx","content-type":"multipart/form-data; boundary=----WebKitFormBoundaryARtDu857mjpOA925","accept":"application/json","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.62","x-upload-content-length":"24860739","x-upload-content-type":"video/mp4","sec-ch-ua-platform":"\"Windows\"","origin":"https://peertube.localecho.net","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://peertube.localecho.net/videos/upload","accept-encoding":"gzip, deflate, br","accept-language":"en-GB,en;q=0.9,en-US;q=0.8,no;q=0.7","x-forwarded-proto":"https, https","x-scheme":"https"},"files":{},"level":"debug","message":"Checking videosAddResumableInitValidator parameters and headers","label":"peertube.localecho.net:443","timestamp":"2022-03-03T12:49:29.423Z"}
{"sql":"Executing (default): SELECT \"VideoChannelModel\".\"id\", \"VideoChannelModel\".\"name\", \"VideoChannelModel\".\"description\", \"VideoChannelModel\".\"support\", \"VideoChannelModel\".\"actorId\", \"VideoChannelModel\".\"accountId\", \"VideoChannelModel\".\"createdAt\", \"VideoChannelModel\".\"updatedAt\", \"Actor\".\"id\" AS \"Actor.id\", \"Actor\".\"type\" AS \"Actor.type\", \"Actor\".\"preferredUsername\" AS \"Actor.preferredUsername\", \"Actor\".\"url\" AS \"Actor.url\", \"Actor\".\"publicKey\" AS \"Actor.publicKey\", \"Actor\".\"privateKey\" AS \"Actor.privateKey\", \"Actor\".\"followersCount\" AS \"Actor.followersCount\", \"Actor\".\"followingCount\" AS \"Actor.followingCount\", \"Actor\".\"inboxUrl\" AS \"Actor.inboxUrl\", \"Actor\".\"outboxUrl\" AS \"Actor.outboxUrl\", \"Actor\".\"sharedInboxUrl\" AS \"Actor.sharedInboxUrl\", \"Actor\".\"followersUrl\" AS \"Actor.followersUrl\", \"Actor\".\"followingUrl\" AS \"Actor.followingUrl\", \"Actor\".\"remoteCreatedAt\" AS \"Actor.remoteCreatedAt\", \"Actor\".\"avatarId\" AS \"Actor.avatarId\", \"Actor\".\"bannerId\" AS \"Actor.bannerId\", \"Actor\".\"serverId\" AS \"Actor.serverId\", \"Actor\".\"createdAt\" AS \"Actor.createdAt\", \"Actor\".\"updatedAt\" AS \"Actor.updatedAt\", \"Actor->Server\".\"id\" AS \"Actor.Server.id\", \"Actor->Server\".\"host\" AS \"Actor.Server.host\", \"Actor->Server\".\"redundancyAllowed\" AS \"Actor.Server.redundancyAllowed\", \"Actor->Server\".\"createdAt\" AS \"Actor.Server.createdAt\", \"Actor->Server\".\"updatedAt\" AS \"Actor.Server.updatedAt\", \"Actor->Avatar\".\"id\" AS \"Actor.Avatar.id\", \"Actor->Avatar\".\"filename\" AS \"Actor.Avatar.filename\", \"Actor->Avatar\".\"height\" AS \"Actor.Avatar.height\", \"Actor->Avatar\".\"width\" AS \"Actor.Avatar.width\", \"Actor->Avatar\".\"fileUrl\" AS \"Actor.Avatar.fileUrl\", \"Actor->Avatar\".\"onDisk\" AS \"Actor.Avatar.onDisk\", \"Actor->Avatar\".\"type\" AS \"Actor.Avatar.type\", \"Actor->Avatar\".\"createdAt\" AS \"Actor.Avatar.createdAt\", \"Actor->Avatar\".\"updatedAt\" AS \"Actor.Avatar.updatedAt\", \"Actor->Banner\".\"id\" AS \"Actor.Banner.id\", \"Actor->Banner\".\"filename\" AS \"Actor.Banner.filename\", \"Actor->Banner\".\"height\" AS \"Actor.Banner.height\", \"Actor->Banner\".\"width\" AS \"Actor.Banner.width\", \"Actor->Banner\".\"fileUrl\" AS \"Actor.Banner.fileUrl\", \"Actor->Banner\".\"onDisk\" AS \"Actor.Banner.onDisk\", \"Actor->Banner\".\"type\" AS \"Actor.Banner.type\", \"Actor->Banner\".\"createdAt\" AS \"Actor.Banner.createdAt\", \"Actor->Banner\".\"updatedAt\" AS \"Actor.Banner.updatedAt\", \"Account\".\"id\" AS \"Account.id\", \"Account\".\"name\" AS \"Account.name\", \"Account\".\"description\" AS \"Account.description\", \"Account\".\"actorId\" AS \"Account.actorId\", \"Account\".\"userId\" AS \"Account.userId\", \"Account\".\"applicationId\" AS \"Account.applicationId\", \"Account\".\"createdAt\" AS \"Account.createdAt\", \"Account\".\"updatedAt\" AS \"Account.updatedAt\", \"Account->Actor\".\"id\" AS \"Account.Actor.id\", \"Account->Actor\".\"type\" AS \"Account.Actor.type\", \"Account->Actor\".\"preferredUsername\" AS \"Account.Actor.preferredUsername\", \"Account->Actor\".\"url\" AS \"Account.Actor.url\", \"Account->Actor\".\"publicKey\" AS \"Account.Actor.publicKey\", \"Account->Actor\".\"privateKey\" AS \"Account.Actor.privateKey\", \"Account->Actor\".\"followersCount\" AS \"Account.Actor.followersCount\", \"Account->Actor\".\"followingCount\" AS \"Account.Actor.followingCount\", \"Account->Actor\".\"inboxUrl\" AS \"Account.Actor.inboxUrl\", \"Account->Actor\".\"outboxUrl\" AS \"Account.Actor.outboxUrl\", \"Account->Actor\".\"sharedInboxUrl\" AS \"Account.Actor.sharedInboxUrl\", \"Account->Actor\".\"followersUrl\" AS \"Account.Actor.followersUrl\", \"Account->Actor\".\"followingUrl\" AS \"Account.Actor.followingUrl\", \"Account->Actor\".\"remoteCreatedAt\" AS \"Account.Actor.remoteCreatedAt\", \"Account->Actor\".\"avatarId\" AS \"Account.Actor.avatarId\", \"Account->Actor\".\"bannerId\" AS \"Account.Actor.bannerId\", \"Account->Actor\".\"serverId\" AS \"Account.Actor.serverId\", \"Account->Actor\".\"createdAt\" AS \"Account.Actor.createdAt\", \"Account->Actor\".\"updatedAt\" AS \"Account.Actor.updatedAt\", \"Account->Actor->Server\".\"id\" AS \"Account.Actor.Server.id\", \"Account->Actor->Server\".\"host\" AS \"Account.Actor.Server.host\", \"Account->Actor->Server\".\"redundancyAllowed\" AS \"Account.Actor.Server.redundancyAllowed\", \"Account->Actor->Server\".\"createdAt\" AS \"Account.Actor.Server.createdAt\", \"Account->Actor->Server\".\"updatedAt\" AS \"Account.Actor.Server.updatedAt\", \"Account->Actor->Avatar\".\"id\" AS \"Account.Actor.Avatar.id\", \"Account->Actor->Avatar\".\"filename\" AS \"Account.Actor.Avatar.filename\", \"Account->Actor->Avatar\".\"height\" AS \"Account.Actor.Avatar.height\", \"Account->Actor->Avatar\".\"width\" AS \"Account.Actor.Avatar.width\", \"Account->Actor->Avatar\".\"fileUrl\" AS \"Account.Actor.Avatar.fileUrl\", \"Account->Actor->Avatar\".\"onDisk\" AS \"Account.Actor.Avatar.onDisk\", \"Account->Actor->Avatar\".\"type\" AS \"Account.Actor.Avatar.type\", \"Account->Actor->Avatar\".\"createdAt\" AS \"Account.Actor.Avatar.createdAt\", \"Account->Actor->Avatar\".\"updatedAt\" AS \"Account.Actor.Avatar.updatedAt\" FROM \"videoChannel\" AS \"VideoChannelModel\" LEFT OUTER JOIN \"actor\" AS \"Actor\" ON \"VideoChannelModel\".\"actorId\" = \"Actor\".\"id\" LEFT OUTER JOIN \"server\" AS \"Actor->Server\" ON \"Actor\".\"serverId\" = \"Actor->Server\".\"id\" LEFT OUTER JOIN \"actorImage\" AS \"Actor->Avatar\" ON \"Actor\".\"avatarId\" = \"Actor->Avatar\".\"id\" LEFT OUTER JOIN \"actorImage\" AS \"Actor->Banner\" ON \"Actor\".\"bannerId\" = \"Actor->Banner\".\"id\" INNER JOIN \"account\" AS \"Account\" ON \"VideoChannelModel\".\"accountId\" = \"Account\".\"id\" INNER JOIN \"actor\" AS \"Account->Actor\" ON \"Account\".\"actorId\" = \"Account->Actor\".\"id\" LEFT OUTER JOIN \"server\" AS \"Account->Actor->Server\" ON \"Account->Actor\".\"serverId\" = \"Account->Actor->Server\".\"id\" LEFT OUTER JOIN \"actorImage\" AS \"Account->Actor->Avatar\" ON \"Account->Actor\".\"avatarId\" = \"Account->Actor->Avatar\".\"id\" WHERE \"VideoChannelModel\".\"id\" = 2;","tags":["sql"],"level":"debug","message":"Executed SQL request","label":"peertube.localecho.net:443","timestamp":"2022-03-03T12:49:29.435Z"}
{"sql":"Executing (default): SELECT \"id\", \"password\", \"username\", \"email\", \"pendingEmail\", \"emailVerified\", \"nsfwPolicy\", \"webTorrentEnabled\", \"videosHistoryEnabled\", \"autoPlayVideo\", \"autoPlayNextVideo\", \"autoPlayNextVideoPlaylist\", \"videoLanguages\", \"adminFlags\", \"blocked\", \"blockedReason\", \"role\", \"videoQuota\", \"videoQuotaDaily\", \"theme\", \"noInstanceConfigWarningModal\", \"noWelcomeModal\", \"noAccountSetupWarningModal\", \"pluginAuth\", \"feedToken\", \"lastLoginDate\", \"createdAt\", \"updatedAt\" FROM \"user\" AS \"UserModel\" WHERE \"UserModel\".\"id\" = 2;","tags":["sql"],"level":"debug","message":"Executed SQL request","label":"peertube.localecho.net:443","timestamp":"2022-03-03T12:49:29.451Z"}
{"tags":["http"],"level":"info","message":"192.168.1.111 - - [03/Mar/2022:12:49:29 +0000] \"POST /api/v1/videos/upload-resumable HTTP/1.0\" 201 - \"https://peertube.localecho.net/videos/upload\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.62\"","label":"peertube.localecho.net:443","timestamp":"2022-03-03T12:49:29.459Z"}
`

I still think this is a bug somewhere in the URL handling.

**Comment by Chocobozzz** [comment]
If PeerTube still receives `"x-forwarded-proto":"https, https"` header, it won't work

**Comment by kenneaal** [comment]
But in this case, it's still receiving the https, https header, but the original problem of the URL being misencoded does not persist:
`{"parameters":{"name":"Cyberpunk_2077_2020.12.13_-_00.13.55.02",[...] "headers":{"x-forwarded-for":"192.168.1.85, 192.168.1.85, 192.168.1.1","host":"peertube.localecho.net","x-real-ip":"192.168.1.1"[...]

"x-forwarded-proto":"https, https","x-scheme":"https"},

"files":{},"level":"debug","message":"Checking videosAddResumableInitValidator parameters and headers","label":"peertube.localecho.net:443","timestamp":"2022-03-03T13:06:10.644Z"}

{"tags":["http"],"level":"info","message":"192.168.1.111 - - [03/Mar/2022:13:06:10 +0000] \"POST /api/v1/videos/upload-resumable HTTP/1.0\" 201 - \"https://peertube.localecho.net/videos/upload\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.62\"","label":"peertube.localecho.net:443","timestamp":"2022-03-03T13:06:10.656Z"}

`
