### ISSUE TITLE
How to use specific fonts and images to modify the template?

### ISSUE THREAD

**Issue by VV666** [Chocobozzz/PeerTube#482]
I would like to use a specific font with the @font-face CSS property. Where do I store this font on the server?
Where should I store svg images to modify the theme?

I tried to create a "style" folder in /storage, but I can't reach it with the css?
Do I have to declare it in the production.yaml file?

New feature proposal: in the administration, add an upload field for additional files like fonts and svg images.

Thank you

**Comment by VV666** [comment]
And a little tinkering?
By manually creating the style file, etc?

**Comment by Chocobozzz** [comment]
Closing in favor of https://github.com/Chocobozzz/PeerTube/issues/484
