### ISSUE TITLE
Vimeo import fails

### ISSUE THREAD

**Issue by tio-trom** [Chocobozzz/PeerTube#4820]
A user tries to import her videos to our instance but she cannot. I tried it too and looked at the logs. It does fail indeed.

This is the error log https://paste.trom.tf/uzutepiden.sql - too big to paste it here

* PeerTube instance:
  * URL: https://videos.trom.tf
  * version:  4.1.0

**Comment by Chocobozzz** [comment]
Hi,

Could you check your `ffmpeg` and `/home/yunohost.app/peertube/storage/bin/yt-dlp` versions?

**Comment by tio-trom** [comment]
`ffmpeg version 4.1.8-0+deb10u1`

But how do I check the `/home/yunohost.app/peertube/storage/bin/yt-dlp` version?

**Comment by Chocobozzz** [comment]
`/home/yunohost.app/peertube/storage/bin/yt-dlp --version`

**Comment by tio-trom** [comment]
That's what I tried and does not work.

```
/home/yunohost.app/peertube/storage/bin/yt-dlp --version
sudo: /home/yunohost.app/peertube/storage/bin/yt-dlp: command not found
```
Works for ffmpeg.

**Comment by Chocobozzz** [comment]
`python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --version`

**Comment by tio-trom** [comment]
```
version
2022.02.04
```

**Comment by Chocobozzz** [comment]
Then I'm sorry but I can't help you. From your error log `ERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)` it seems to be a `yt-dlp` issue. You can try to run this command manually on your server to reproduce the error.

**Comment by tio-trom** [comment]
Ok so this is an error with yt-dlp itself you are saying, not peertube related. I can report it to them then.
