### ISSUE TITLE
Can't add an instance to my subscriptions

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#4821]
**Describe the current behavior**
I'd like to add an instance to my subscriptions list, but the button "add instance" has disappeard, so i can't.
**Steps to reproduce:**

1.Go to instance subscriptions panel.

**Describe the expected behavior**
There's no button "add instance" anymore.
**Additional information**

* PeerTube instance:
  * URL: peertube.stemy.me
  * version: 4.1.0
  * NodeJS version: 10.24.0~dfsg-1~deb10u1
  * Ffmpeg version: 7:4.1.8-0+deb10u1

* Browser name, version and platforms on which you could reproduce the bug: Ubuntu 21.10, Firefox 97

![Screenshot_20220226_172616](https://user-images.githubusercontent.com/22192600/155850895-7f284629-95a6-4fd2-a61c-36b65c3c2163.png)

**Comment by Chocobozzz** [comment]
Hi,

We already had this kind of issue reporter. The cause was a special list hidding this button in a web browser plugin (ublock origin I think).

**Comment by stemy2** [comment]
I disabled all my blockers and extensions, but the button is still missing.

**Comment by Chocobozzz** [comment]
Could you try to open the web browser inspector to find `.follow-button` `a` element? In `.p-datatable-header` element, just above the table

**Comment by stemy2** [comment]
I can find `.follow-button` but there's no `.follow-button a`.

**Comment by Chocobozzz** [comment]
Yes, it's `a.follow-button`. Then if it exists in the DOM, can you check why it's not displayed?

**Comment by stemy2** [comment]
I can see the button now. I don't get why i didn't saw it earlier, but at least, it's solved.

**Comment by marius851000** [comment]
I had this issue too. I seems to be related to either the "Fanboy’s Annoyance" or the "Fanboy’s Social" (or maybe both) blocklist in ublock.
