### ISSUE TITLE
After upgrading to 4.1.0, Peertube keeps complaining my nodejs v12.22.8 is deprecated but I've upgraded it to v17.3.0

### ISSUE THREAD

**Issue by fweng322** [Chocobozzz/PeerTube#4822]
**Describe the current behavior**
Couldn't start peertube service after upgrading to v4.1.0.
It keeps complaining my node.js version as v12.22.8.
I noticed that this version was installed at my /var/www/peertube/node_modules, but my global node (`which node` shows v17.3.0) has been upgraded.  I have no idea how to go on to solve this.

**Steps to reproduce:**

1. Upgrade from v4.0.0 to v4.1.0 using scripts_upgrade.sh
2.
3.

**Describe the expected behavior**
It should start the service.

**Additional information**

* PeerTube instance:
  * URL:
  * version:
  * NodeJS version: v17.3.0 (?)
  * Ffmpeg version:

**Comment by fweng322** [comment]
I tried to manually edit the package.json and re-run npm install.  It upgraded my /var/www/peertube/node_modules/node and now my service can be started.  Closing this, but I still wonder why or how it can be automated upgraded...

**Comment by Chocobozzz** [comment]
As a side note, I think it's the same issue than https://github.com/Chocobozzz/PeerTube/issues/4814#issuecomment-1055159270
