### ISSUE TITLE
z-index for modal not applied

### ISSUE THREAD

**Issue by rriemann** [Chocobozzz/PeerTube#4825]
**Describe the current behavior**

![Screenshot_20220302_004153](https://user-images.githubusercontent.com/111932/156267556-61805e8f-5fc1-4931-929c-7200798770b7.png)

The modal z-index value of 16000 is not applied.

**Steps to reproduce:**

1.  logout
2. access the settings menu
3. find out that the x of the modal is a bit cut of (with modified header height even entirely covered by header)

**Describe the expected behavior**

1. the modal is not covered by the header

**Additional information**

* PeerTube instance:
  * URL: https://media.privacyinternational.org/w/ejSWkoZpjwofKwA82nB7GP?start=0s
  * version: 4.0.0 and 4.1.0

* Browser name, version and platforms on which you could reproduce the bug: Mozilla Firefox 96.0.2 on Linux x86_64

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/42d73f1c57f131e33d632de55d2b231f3fafd70c
