### ISSUE TITLE
TV UI

### ISSUE THREAD

**Issue by PhieF** [Chocobozzz/PeerTube#483]
Hi

With very very low priority (even no priority at all), just to know what you would think about this

A complete TV UI like https://youtube.com/TV would require a lot of work so I was thinking about a more simple thing, just casting

Let's say I have a computer/smartphone with a web browser and also a TV with a simple web browser (or for android TV we could create a simple cast receiver which would be nothing else than a webview)

I want to watch a video on my TV using my smartphone as a remote

to do so we could connect the TV with login/password to the instance and register the device as a cast receiver
so for example 
https://instance.bla/cast
would only be a html form with login / password that can be used with arrows of the remote

on the smartphone when watching a video while logged in the same instance the we could just send a message to the tv's browser containing the URL of the video, automatically in full screen (tv browser are in fullscreen so just a video filling the whole page)

**Comment by Chocobozzz** [comment]
Maybe related to https://github.com/Chocobozzz/PeerTube/issues/93?

**Comment by PhieF** [comment]
Indeed, I didn't see this (thanks) both can be interesting but I guess using a webview seems to be easier, especially for webtorrent, am I mistaking ?

**Comment by PhieF** [comment]
Simple TV UI

It should be possible to have a simpler UI for TV

for example

for "Overview"

vertical and horizontal scrolling, horizontal for each category, vertical to go through category.
![](http://pix.toile-libre.org/upload/original/1536844073.png)
Then, going to the far left will make left menu appear with a selector for each part, and a search button at the top
![](http://pix.toile-libre.org/upload/original/1536844202.png)

Clicking on the video could make a fullscreen player appear without comment feature, perhaps only like/ dislike button at the bottom

it's not perfect but seems easy to adapt 

first : removing upload button, moving search button to the left menu for it to be easily accessible with a remote, having focus background (I guess there is no background for now ?) and the fullscreen player

I will try to do it with javascript

**Comment by rigelk** [comment]
@PhieF please refer to #921 where I implemented the keyboard focus part.

**Comment by Chocobozzz** [comment]
Closing this inactive discussion. Don't hesitate to comment if you want to reopen it.
