### ISSUE TITLE
Docker setup: serving assets from nginx – path missmatch?

### ISSUE THREAD

**Issue by rriemann** [Chocobozzz/PeerTube#4830]
Hi all!

**Describe the current behavior**

I have the impression that an optimisation in the nginx file for Docker does not work:

https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube#L187

~~~nginx
  # Bypass PeerTube for performance reasons. Optional.
  location ~ ^/client/(.*\.(js|css|png|svg|woff2|otf|ttf|woff|eot))$ {
    add_header Cache-Control "public, max-age=31536000, immutable"; # Cache 1 year

    alias /var/www/peertube/peertube-latest/client/dist/$1;
  }
~~~

The alias leads to an asset path like `/var/www/peertube/peertube-latest/client/dist/client/en-US/runtime.ad1633532e253953.js`.

However, the actual file is in the nginx container under `/var/www/peertube/peertube-latest/client/dist/en-US/runtime.ad1633532e253953.js`

I suggest that the Docker compose mount is changed accordingly.

https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/docker-compose.yml#L23

~~~yaml
services:

  # You can comment this webserver section if you want to use another webserver/proxy
  webserver:
    image: chocobozzz/peertube-webserver:latest
    # If you don't want to use the official image and build one from sources:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.nginx
    env_file:
      - .env
    ports:
     - "80:80"
     - "443:443"
    volumes:
      - type: bind
        # Switch sources if you downloaded the whole repository
        #source: ../../nginx/peertube
        source: ./docker-volume/nginx/peertube
        target: /etc/nginx/conf.d/peertube.template
      - assets:/var/www/peertube/peertube-latest/client/dist:ro
      - ./docker-volume/data:/var/www/peertube/storage
      - certbot-www:/var/www/certbot
      - ./docker-volume/certbot/conf:/etc/letsencrypt
    depends_on:
      - peertube
    restart: "always"
~~~

The line `      - assets:/var/www/peertube/peertube-latest/client/dist:ro` should be modified to `
      - assets:/var/www/peertube/peertube-latest/client:ro` without the `dist`.

I have not tested this. I am working currently on a replacement of nginx by caddy. There, I ran into this issue.

**Comment by Chocobozzz** [comment]
Hi,

> The alias leads to an asset path like /var/www/peertube/peertube-latest/client/dist/client/en-US/runtime.ad1633532e253953.js.

I'm not sure this is true. From my tests, JS files are correctly sent by nginx. Alias `alias /var/www/peertube/peertube-latest/client/dist/$1;` uses `$1` that takes everything after `client/` so it should not append this path segment to the `alias` :thinking:

**Comment by rriemann** [comment]
Oups, indeed the regexp matches only a part of the path.
