### ISSUE TITLE
documentation is not clear what is administrator's username after installation

### ISSUE THREAD

**Issue by lukaprincic** [Chocobozzz/PeerTube#4833]
In Production guide - installation - [production.md](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md)

Documentation is not clear that administrator's username is "root". Or at least after using the recommended commandline for a password reset administrator's username is root.

I can sumbit a PR.

**Comment by Chocobozzz** [comment]
Thanks! I improved documentation in https://github.com/Chocobozzz/PeerTube/commit/fc10ecf167bd07f32426441e74b49370d5ff919b
