### ISSUE TITLE
Is there an way to clean up non existent video files / transcodings ?

### ISSUE THREAD

**Issue by cutec-chris** [Chocobozzz/PeerTube#4834]
An 3.x version wasnt able to transcode my webtorrent files to hls, so i played around a bit with transcoding jobs.
Now i have a bit of a mess i have deleted the hls files and wanted to start over.

4.1 can now nicely create transcodings from web interface but it "thinks" i have already hls files but they dont exists anymore.
Is there an way to clean up this ?

**Comment by cutec-chris** [comment]
when i "delete" the hls files from webinteface it dont shows the hls tag but says when i make an transcoding job "thee are already hls files"

**Comment by Chocobozzz** [comment]
> when i "delete" the hls files from webinteface it dont shows the hls tag but says when i make an transcoding job "thee are already hls files"

Could you detail where this message is displayed?

**Comment by cutec-chris** [comment]
Ive made now an python script that deletes the non existing Entrys from videoFiles table. 
So the base problem is gone.

But i have videos that shows this message and i have no clue whats different to other videos. 
When is peertube showing those Message ?
I have a lot of videos where i can start transcoding to hls even when there already hls files.

**Comment by Chocobozzz** [comment]
I'm sorry but I don't understand. I suggest to create another issue, filling the bug template if you encounter another problem in peertube
