### ISSUE TITLE
When any change is made via UI, all the configuration is saved in the json

### ISSUE THREAD

**Issue by drym3r** [Chocobozzz/PeerTube#4835]
Not sure if it's a bug or a "feature".

**Describe the current behavior**
When you do a change on the configuration via UI, for example custom css, all your configuration is saved in the `local-production.json` file. This makes that any change that you do in the `production.yaml` file is ignored, since the json file takes precedence.

**Steps to reproduce:**

1. Do a change via UI
2. Save it

**Describe the expected behavior**
I'd expect that when doing a change in the UI, only the change done is saved in the json file. If you allow admins to make changes via UI, then you can't do changes via the yaml file. 

With the proposed change, both ways could coexist. 

PD: Forgot to say it on the last issue I opened, thanks for all your work! Peertube is awesome.

**Comment by Chocobozzz** [comment]
Hi,

This is a feature explained in `production.yaml` file :) https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L286

**Comment by alexppg** [comment]
Thanks for the quick answer!
