### ISSUE TITLE
Sorting by "Best" unavailable to unauthenticated users

### ISSUE THREAD

**Issue by Sakrecoer** [Chocobozzz/PeerTube#4838]
**Describe the current behavior**
"Sort by best" not available to unauthenticated users
**Steps to reproduce:**

1. Got to "administartion > Configuration > Basic"
2. Set the default trending page to "Best Videos"
3. From the same session go to the "trending" tab and find videos sorted by best
![image](https://user-images.githubusercontent.com/3484593/156926310-ae53e0c0-7b13-4bb0-8bfc-6dca970926a3.png)

5. Open an unauthenticated session
6. Go to "trending" tab.
7. Sorting menu looks odd:
![image](https://user-images.githubusercontent.com/3484593/156926344-be17cad1-9e03-4640-896b-fbf260e29492.png)
8. unfold menu to see "Sorted by Best" unavailable
![image](https://user-images.githubusercontent.com/3484593/156926365-60ae64c7-7d3c-4c8f-8691-19c1bb17f809.png)

**Describe the expected behavior**
Sort By best should be available for unauthenticated users too
**Additional information**

* PeerTube instance:
  * URL: https://v.basspistol.org
  * version: 4.0.1
  * NodeJS version: v14.19.0
  * Ffmpeg version: 4.2.4-1ubuntu0.1

* Browser name, version and platforms on which you could reproduce the bug: Firefox Linux

**Comment by Chocobozzz** [comment]
Hello,

Best algorithm uses user's history to improve Hot algorithm. So it's an expected behaviour this sort is not available for unauthenticated users that don't have an history.

**Comment by Sakrecoer** [comment]
Thanks for clarifying and sorry for wasting your time. I tried to find documentation about the differences between the algorithms but couldn't. I will try submit a PR for the documentation about this as soon as i have a moment.
