### ISSUE TITLE
Multi users administration of a channel, possible ?

### ISSUE THREAD

**Issue by tutle** [Chocobozzz/PeerTube#4839]
Hello,
I like a lot Peertube but I'm very disappointed after discovering it seems not possible to share administration of a channel between users.
Am I wrong ? Any plugin or modification possible ?
It's an essential basic function for any collaborative work, I'm ready for financial contribution for development.
Any help or suggestion is welcome.
Sincerely.
Yvan

**Comment by kontrollanten** [comment]
Hi! Unfortunately it's currently not possible to share channel administration between users. There's an issue for that already; https://github.com/Chocobozzz/PeerTube/issues/699

**Comment by tutle** [comment]
Bad news...
