### ISSUE TITLE
Embed with preview image in portrait format

### ISSUE THREAD

**Issue by stoically** [Chocobozzz/PeerTube#4843]
**Describe the problem to be solved**

Currently when uploading a video in portrait mode it will always generate a preview image in landscape format. Now, when embedding the portrait video to be used with mobile devices in portrait mode, it'll show a landscape preview image. There is also no way to upload an alternative preview image in portrait mode.

**Describe the solution you would like:**

Some way of specifying portrait preview images for videos.

**Describe alternatives you have considered**  

Putting a video fully in "portrait mode", which would always show the player and preview images in portrait mode, not in landscape mode.

**Comment by Chocobozzz** [comment]
Hi,

> Now, when embedding the portrait video to be used with mobile devices in portrait mode,

You mean you're using the `iframe` code with portrait size? (`width` `iframe` attribute < `height` `iframe` attribute)

**Comment by stoically** [comment]
Yep. Basically the `iframe` inside a `<div style="aspect-ratio: 9 / 16;">`.

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/bb21e0b3c8a81206db064d68b68ce96e971aeb73 :)
