### ISSUE TITLE
Explain how to do performance tests for PeerTube plugins

### ISSUE THREAD

**Issue by smilekison** [Chocobozzz/PeerTube#4845]
Hello everyone,
I am developing a plugin for PeerTube. I have done the unit testing and integration testing. If there is any way to do a performance testing, Can anyone recommend me a tool or a link where you have implemented performance testing?

**Comment by Chocobozzz** [comment]
Hello,

You can try [autocannon](https://github.com/mcollina/autocannon). It's what we use to benchmark peertube REST API: https://github.com/Chocobozzz/PeerTube/blob/develop/scripts/benchmark.ts
