### ISSUE TITLE
The "path" argument must be of type string. Received null

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#4847]
**Describe the current behavior**
When I upload a video, there is an underscore "_" in the title, then an error appears after clicking the Publish button.
The "path" argument must be of type string. Received null
The button becomes inactive.

If you remove this character, or put a comma instead, then there will be no error.
This bug appeared in the previous version 4.1.0

![Скриншот 09 03 22_16 18 14](https://user-images.githubusercontent.com/11453567/157452929-c6589ad2-ba82-462f-85bf-18af2bc40cd7.png)

**Steps to reproduce:**

1. Upload a video file, the name must contain the symbol "_"
2. Error message "The "path" argument must be of type string. Received null"
3. The publish button becomes inactive.

**Describe the expected behavior**
There shouldn't be any mistakes.

* PeerTube instance:
  * URL: https://peervideo.ru
  * version: 4.1.1
  * NodeJS: 14.19.0

**Comment by Alterak** [comment]
Now I noticed that such an error appears without an underscore ... for example, if you write the title "Test. Test 2"

**Comment by Alterak** [comment]
> Please paste server error logs

{"level":"info","message":"Video with name Боец. Серия 3 тест and uuid 246c1e80-e380-4d24-8ea8-d8bd1e34cf7c updated.","label":"peervideo.ru:443","tags":["api","video","246c1e80-e380-4d24-8ea8-d8bd1e34cf7c"],"timestamp":"2022-03-11T11:06:57.718Z"}
{"err":{"stack":"TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received null\n    at new NodeError (internal/errors.js:322:7)\n    at validateString (internal/validators.js:124:11)\n    at join (path.js:1148:7)\n    at /var/www/peertube/versions/peertube-v4.1.1/dist/server/helpers/webtorrent.js:103:48\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v4.1.1/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at __awaiter (/var/www/peertube/versions/peertube-v4.1.1/node_modules/tslib/tslib.js:113:16)\n    at updateTorrentMetadata (/var/www/peertube/versions/peertube-v4.1.1/dist/server/helpers/webtorrent.js:101:34)\n    at /var/www/peertube/versions/peertube-v4.1.1/dist/server/controllers/api/videos/update.js:148:58\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v4.1.1/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at __awaiter (/var/www/peertube/versions/peertube-v4.1.1/node_modules/tslib/tslib.js:113:16)\n    at updateTorrentsMetadata (/var/www/peertube/versions/peertube-v4.1.1/dist/server/controllers/api/videos/update.js:146:34)\n    at /var/www/peertube/versions/peertube-v4.1.1/dist/server/controllers/api/videos/update.js:105:23\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v4.1.1/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","message":"The \"path\" argument must be of type string. Received null","code":"ERR_INVALID_ARG_TYPE"},"level":"error","message":"Cannot execute updateVideo with many retries.","label":"peervideo.ru:443","timestamp":"2022-03-11T11:06:57.725Z"}
{"err":"TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received null\n    at new NodeError (internal/errors.js:322:7)\n    at validateString (internal/validators.js:124:11)\n    at join (path.js:1148:7)\n    at /var/www/peertube/versions/peertube-v4.1.1/dist/server/helpers/webtorrent.js:103:48\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v4.1.1/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at __awaiter (/var/www/peertube/versions/peertube-v4.1.1/node_modules/tslib/tslib.js:113:16)\n    at updateTorrentMetadata (/var/www/peertube/versions/peertube-v4.1.1/dist/server/helpers/webtorrent.js:101:34)\n    at /var/www/peertube/versions/peertube-v4.1.1/dist/server/controllers/api/videos/update.js:148:58\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v4.1.1/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at __awaiter (/var/www/peertube/versions/peertube-v4.1.1/node_modules/tslib/tslib.js:113:16)\n    at updateTorrentsMetadata (/var/www/peertube/versions/peertube-v4.1.1/dist/server/controllers/api/videos/update.js:146:34)\n    at /var/www/peertube/versions/peertube-v4.1.1/dist/server/controllers/api/videos/update.js:105:23\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v4.1.1/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","level":"error","message":"Error in controller.","label":"peervideo.ru:443","timestamp":"2022-03-11T11:06:57.726Z"}

**Comment by Chocobozzz** [comment]
Hello,

What if you wait a little bit before clicking on the "Publish" button at the bottom right?

**Comment by Alterak** [comment]
> What if you wait a little bit before clicking on the "Publish" button at bottom right?

You are right... if you wait another 10 seconds after uploading the file and click the "Publish" button, then the error does not appear.
Can you fix this bug?

**Comment by gsugambit** [comment]
i just ran into this issue. Thanks for the work around!
