### ISSUE TITLE
Missing elements in the main page

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#4852]
**Describe the current behavior**
Some elements of the main page are missing. Strangely, they reappears briefly when reloading the page, and loading another instance's page can fix it.
**Steps to reproduce:**

1. Go to the website.

**Describe the expected behavior**
Page loading correctly.
**Additional information**
![Screenshot_20220313_084749](https://user-images.githubusercontent.com/22192600/158050540-3f522752-1ee9-4644-9c25-92e5cb35e8ae.png)

* PeerTube instance:
  * URL: peertube.stemy.me
  * version: 4.1.1
  * NodeJS version: 10.24.0~dfsg-1~deb10u1
  * Ffmpeg version: 7:4.1.8-0+deb10u1

* Browser name, version and platforms on which you could reproduce the bug: ubuntu firefox 98
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
A plugin is breaking your instance (`nanotubes`)
