### ISSUE TITLE
envsubst: error while reading "standard input": Is a directory issue

### ISSUE THREAD

**Issue by gsugambit** [Chocobozzz/PeerTube#4853]
**Describe the problem**
Running the application in docker and the follow error is occuring in the docker logs for the web server. All other components seem to be working

**Provide the exact sequence of commands / steps that you executed before running into the problem**
docker-compose up -d

**Additional information**
I see the following logs then the nginx server crashes.
> webserver_1  | envsubst: error while reading "standard input": Is a directory
webserver_1  | envsubst: error while reading "standard input": Is a directory
webserver_1  | envsubst: error while reading "standard input": Is a directory
webserver_1  | envsubst: error while reading "standard input": Is a directory

This line of code references this command in nginx config: https://github.com/Chocobozzz/PeerTube/blob/0a25749f14a083d2c388b6229cbdbba695d0387e/support/docker/production/entrypoint.nginx.sh

**Docker Compose Configuration**

> webserver:
    image: chocobozzz/peertube-webserver:latest
    env_file:
      - .env
    ports:
     - "20001:80"
    volumes:
      - type: bind
        source: ../docker-volume/nginx/peertube
        target: /etc/nginx/conf.d/peertube.template
      - assets:/var/www/peertube/peertube-latest/client/dist:ro
    depends_on:
      - peertube
    restart: "always"
    networks:
      peertube-network:
        aliases:
          - peertube-nginx
      external_network:
        aliases:
          - peertube-nginx

* PeerTube instance: peertube.gsugambit.com
  * version: latest docker image as of this post
  * Redis version: 6-alpine
  * PostgreSQL version: 13-alpine

**Comment by gsugambit** [comment]
I do have the flag `PEERTUBE_WEBSERVER_HOSTNAME=peertube.gsugambit.com` configured in my .env file that this is using.

The reason i'm using non standard HTTP port is because I already have `haproxy` with all my certs etc inside this server. So the requests come to haproxy and then get routed to this nginx.

**Comment by gsugambit** [comment]
Actually I thought haproxy should be able to route directly to port 9000. For some reason it was not working earlier but it is now, maybe i had forgot to restart my proxy. So above is an issue but im no longer using the webserver so it's not affecting me.

**Comment by kavemang** [comment]
im having this issue now after some update and the page wont load any longer
