### ISSUE TITLE
Google Cloud Storage - Watch Not Working But Download Is

### ISSUE THREAD

**Issue by gsugambit** [Chocobozzz/PeerTube#4855]
**Describe the current behavior**
I have tried to get peertube to publish to a google GCP bucket. What i found was that the issue is that the source code automatically puts "public-read" as the ACL. Can this be made configurable based off a parameter? Something like PEERTUBE_OBJECT_STORAGE_APPLY_ACL ? Maybe it could default to `true` to maintain functionality for today. With GCS, because they use uniform bucket-level access by default, it throws this error:

> Details": "Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access"

If I was certain on how to build the entire system locally i would test deploying a docker container with that 1 line of code removed and see if it works.

**Steps to reproduce:**

1. Use current docker containers
2. Configure .env to communicate with GCS bucket
3. Attempt to upload a video and see error

**Describe the expected behavior**
Video should be uploaded to bucket

**Additional information**

* PeerTube instance: 
  * URL: peertube.gsugambit.com
  * version: latest version
  * NodeJS version: using docker container to deploy, latest image
  * Ffmpeg version: using docker container to deploy, latest image

* Browser name, version and platforms on which you could reproduce the bug:
Latest version of chrome and firefox

This seems like the same issue that was run into [here](https://github.com/Chocobozzz/PeerTube/issues/4850) but it looks like he changed the code to make it work. If this could be configurable it would help others use the GA docker containers

**Comment by gsugambit** [comment]
Actually, upon further investigation into logging, even if i change the ACL to public for all items in the bucket, I can see that Peertube is adding the `bucketName` to the `host` property. This is causing an issue because now the host is incorrect. When i changed the bucket name property to other things this was also happening. Is this a configuration problem. Here is my config prop

> PEERTUBE_OBJECT_STORAGE_ENDPOINT=https://storage.googleapis.com



![image](https://user-images.githubusercontent.com/13861767/158099048-64d173e6-2eb8-46e9-98d4-ae5da5bce658.png)

**Comment by gsugambit** [comment]
More information, I have found out there is a `BASE_URL` property. If this is not set in the source code, it will attempt to put the bucket name in front of url [here](https://github.com/Chocobozzz/PeerTube/blob/0305db28c98fd6cf43a3c50ba92c76215e99d512/server/lib/object-storage/urls.ts). So I have updated the configuration to have base url. This has fixed my upload problem (after also making the bucket public).

I can see that each time when I upload a the UUID from Peertube logs is the name of the folder in the bucket 
![image](https://user-images.githubusercontent.com/13861767/158102785-e418e636-aba0-4f14-9910-252b10fc02fc.png)

However, the videos now cannot play. It just loops like it's waiting. I went to the Network tab and I can see that it seemingly should be hitting the right address
![image](https://user-images.githubusercontent.com/13861767/158102878-ba71feb5-f444-497d-98e9-30031835fefd.png)
![image](https://user-images.githubusercontent.com/13861767/158102918-aaaf8ec7-6c9c-4519-b7a5-05dd12c41684.png)

I compared the URLs character by character in NotePad++ and each character is the exact same. (I had to put the bucketname at the end of the base url for this to happen. So I see the files being uploaded into `streaming-playlists` however nothing is being uploaded to `videos` folder but maybe that's by design?

Any thoughts on how this can be solved. Here is screenshot of the bucket configuration parameters (except password. Anything else that could help please let me know.
![image](https://user-images.githubusercontent.com/13861767/158103265-4e4f9ef7-0c31-4c47-b508-d4d91b3910c9.png)

**Comment by Chocobozzz** [comment]
Hello,

You should not set a `BASE_URL` configuration. It should be used if you want to serve files from another endpoint (a cache server for example to reduce costs). And I don't know how this setting could have fixed your upload issue since peertube only uses `BASE_URL` when displaying video JSON information in REST API.

**Comment by gsugambit** [comment]
@Chocobozzz https://peertube.gsugambit.com/w/71tCgPvLbFRRhXhtYf64Wp
I don't know if you can see this video but it is saving inside GCS now however it won't play. When I didn't change the base URL the code would try to go to https://peeertube.storage.googleapis.com. I can send you logs but I can see in the code i linked above [here](https://github.com/Chocobozzz/PeerTube/blob/0305db28c98fd6cf43a3c50ba92c76215e99d512/server/lib/object-storage/urls.ts) that if base URL is not set, it will use the bucket name before the host which is why nothing works until i set base url

` return `${getEndpointParsed().protocol}//${bucketInfo.BUCKET_NAME}.${getEndpointParsed().host}/``

**Comment by gsugambit** [comment]
@Chocobozzz 'Also any hopes of getting a config flag to disable `ACL` public-read? Having to set our AWS or GCS to public access to people not even authenticated is a really big vulnerability

**Comment by Chocobozzz** [comment]
Have you enabled CORS on your bucket? https://docs.joinpeertube.org/admin-remote-storage?id=cors-settings

I see a CORS error when I try to load your video.

**Comment by gsugambit** [comment]
@Chocobozzz That fixed it. The videos now play instantly. Here is the configuration I used for GCS in case you want to put it in the documents

> [
    {
      "origin": ["*", "https://mydomainhere.com"],
      "method": ["GET", "PUT", "DELETE", "OPTIONS", "HEAD", "PATCH", "POST"],
      "responseHeader": ["*"],
      "maxAgeSeconds": 3600
    }
]


If you would like I can try removing the base URL parameter and see if videos still upload/play/download without issue.

Any thoughts on the ACL being a configurable parameter? If i can get a dev environment set up for this, i'd love to contribute

**Comment by gsugambit** [comment]
@Chocobozzz So I have confirmed that removing base url still allows it to work which is puzzling because it was the only change I made at that point in debugging. I did notice one issue though.

When you first upload a video it begin's transcoding but you can watch it before hand. Once the video finishes transcoding and is available in the cloud, the logs start to error and write every few milliseconds that the video is no longer available locally in peertube (since it's not in cloud storage). The video then stops playing and user has to refresh though they won't know what is happening.
This is basically written to the log every few milliseconds 
![image](https://user-images.githubusercontent.com/13861767/158298397-0783541a-0e6e-4be1-b5c3-ac2c66421000.png)

It wrote 3 log files in a very small amount of time. I had just cleaned all logs before doing the base URL check.
![image](https://user-images.githubusercontent.com/13861767/158298542-72c3dd8a-7d40-413b-9620-5b6c5dee0ed3.png)

**Comment by gsugambit** [comment]
@Chocobozzz Actually in the HTTP request, I can see the URL is indeed incorrect, it's adding in the bucket name in the URL but somehow google is handling it and it is working now but this definitely isn't how it should be. The bucket name should not be in the function i highlighted from the source code above. Is that required for AWS or some other object storage potentially?
![image](https://user-images.githubusercontent.com/13861767/158299274-3285d10b-8825-4ce7-8ec7-ab949ac74d2a.png)

**Comment by Chocobozzz** [comment]
> The video then stops playing and user has to refresh though they won't know what is happening.

It's an expected behaviour, it's the reason why we display a message below the player: `The video is being moved to an external server, it may not work properly.` or `The video is being transcoded, it may not work properly.`

> The bucket name should not be in the function i highlighted from the source code above. Is that required for AWS or some other object storage potentially?

I don't understand. If you disabled `BASE_URL` then the URL in your screen is correct

**Comment by Chocobozzz** [comment]
We're just using the virtual host path for buckets: https://cloud.google.com/storage/docs/request-endpoints#xml-api

**Comment by gsugambit** [comment]
this is solved in https://github.com/Chocobozzz/PeerTube/issues/4850

**Comment by kpideas** [comment]
@Chocobozzz @gsugambit I was trying the steps listed above with configs directly in production.yaml and GCS bucket does have the CORS. But I keep getting the Access Denied error.

I'm able to use gsutil to upload a file from GCP VM to the GCS bucket after using the Service Account.

Am I missing any other configs? And the object storage lib seems to be AWE specific? @gsugambit were you using the inbuilt one or something else for GCS bucket?
