### ISSUE TITLE
Segment error on HLS.js

### ISSUE THREAD

**Issue by luxtiasco** [Chocobozzz/PeerTube#4856]
Using docker and external nginx. Cannot play after transcoded.
Object Error: Hashes does not correspond for segment

It seems that there is a wrong hash or something.

```
 Segment error. {id: 'https://domain/static/streaming-playlists/hls/e5…c459-33b2-479b-99f5-92fd812a0d52-master.m3u8+V0+0', url: 'https://domain/static/streaming-playlists/hls/e5…8-5d12-4793-bd63-871a06447e42-1080-fragmented.mp4', masterSwarmId: 'https://domain/static/streaming-playlists/hls/e5…/d0f2c459-33b2-479b-99f5-92fd812a0d52-master.m3u8', masterManifestUri: 'https://domain/static/streaming-playlists/hls/e5…/d0f2c459-33b2-479b-99f5-92fd812a0d52-master.m3u8', streamId: 'V0', …}id: "https://domain/static/streaming-playlists/hls/e57558d6-e905-4b7f-8886-ae06c7da0119/d0f2c459-33b2-479b-99f5-92fd812a0d52-master.m3u8+V0+0"masterManifestUri: "https://domain/static/streaming-playlists/hls/e57558d6-e905-4b7f-8886-ae06c7da0119/d0f2c459-33b2-479b-99f5-92fd812a0d52-master.m3u8"masterSwarmId: "https://domain/static/streaming-playlists/hls/e57558d6-e905-4b7f-8886-ae06c7da0119/d0f2c459-33b2-479b-99f5-92fd812a0d52-master.m3u8"priority: 0range: "bytes=1345-1701237"requestUrl: "https://domain/static/streaming-playlists/hls/e57558d6-e905-4b7f-8886-ae06c7da0119/f8b66798-5d12-4793-bd63-871a06447e42-1080-fragmented.mp4"responseUrl: "https://domain/static/streaming-playlists/hls/e57558d6-e905-4b7f-8886-ae06c7da0119/f8b66798-5d12-4793-bd63-871a06447e42-1080-fragmented.mp4"sequence: "0"streamId: "V0"url: "https://domain/static/streaming-playlists/hls/e57558d6-e905-4b7f-8886-ae06c7da0119/f8b66798-5d12-4793-bd63-871a06447e42-1080-fragmented.mp4"[[Prototype]]: Object Error: Hashes does not correspond for segment f8b66798-5d12-4793-bd63-871a06447e42-1080-fragmented.mp4/1345-1701237(expected: a2d3300c6799ff1d5fba5bc7df1072bc192a7b40d8d4e46bace88c907f28b6be instead of 8c92cc02677250e095a13ef6ec7f5f4b21ce9c0c2e353cc2b84fc72ab280aaf5)
```

**Comment by Chocobozzz** [comment]
Hello,

Please fill the [bug template](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/00-bug-issue.md)

**Comment by luxtiasco** [comment]
> Hello,
> 
> Please fill the [bug template](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/00-bug-issue.md)

Sorry but it is not that capable. I am running the official Docker Image, nothing wrong on backend but have errors on web frontend console as I have pasted above.

**Comment by luxtiasco** [comment]
Using [production-bullseye](https://hub.docker.com/layers/chocobozzz/peertube/production-bullseye/images/sha256-8b26d3c49aa21aed0c72207535dc76ea7994a60f824a2dadcefebf050fa12c59?context=explore) and an non-docker Nginx.

**Comment by Chocobozzz** [comment]
Please paste the URL of a broken video

**Comment by Chocobozzz** [comment]
Do you have error in peertube logs? (`Admininistration` -> `System` -> `Logs`)

What are your ffmpeg and nodejs versions?

**Comment by luxtiasco** [comment]
Official latest docker image and native nginx reverse proxy with wss on, tried rebuild docker-compose for more than 5 times.
No error in log and nothing special in the info.

**Comment by Chocobozzz** [comment]
Do you have a another reverse proxy in front of your docker-compose setup?

Because it seems your webserver does not support byte range requests:

```
curl -v 'https://t.pub.pm/static/streaming-playlists/hls/60079313-0abf-4ac5-8086-8d9a2c01c93f/6e00187f-ddeb-4f9e-ae35-$ c7d3500986ea-1080-fragmented.mp4' -H 'Range: bytes=1000-10000'
...
content-length: 1720699
...
```
