### ISSUE TITLE
Peertube cli upload claims arguments are not present when they obviously are

### ISSUE THREAD

**Issue by jfoucher** [Chocobozzz/PeerTube#4858]
**Describe the current behavior**
The cli tools installed on Ubuntu server 20.04 as described here https://docs.joinpeertube.org/maintain-tools?id=cli-tools-guide have strange behaviour. I am trying to upload a video with the following command line : 

`peertube up -f /some/directory/file.mp4 -u https://videos.6px.eu -U "username" --password "mypassword"`

This is the only thing it does : 
```
--username field is required
--password field is required
```
The problem is the same whether I use the short or long version of the options.

**Steps to reproduce:**

1. Install peertube with docker as described here https://docs.joinpeertube.org/install-docker
2. Install the cli tools as described here https://docs.joinpeertube.org/maintain-tools?id=cli-tools-guide
3. Setup peertube with the web interface, create a new user to upload videos with
4. Try to upload a video with the cli tools

**Describe the expected behavior**
It should upload the video

**Additional information**

* PeerTube instance:
  * URL: videos.6px.eu
  * version:4.1.1
  * NodeJS version: v16.14.0
  * Ffmpeg version: irrelevant

* Browser name, version and platforms on which you could reproduce the bug: irrelevant
* Link to browser console log if relevant: irrelevant
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): irrelevant

**Comment by Chocobozzz** [comment]
Oup's, please try https://github.com/Chocobozzz/PeerTube/commit/74220dba9db6a1dc5c0b504b0230de26ef9c9dd5 that should fix your issue

**Comment by DoumeDuSud** [comment]
I try it, but I still have the same error

**Comment by Chocobozzz** [comment]
Did you run `npm run setup:cli` after your `git pull`?

**Comment by DoumeDuSud** [comment]
Thanks for the tips, it's working
