### ISSUE TITLE
Advances Federation filters 

### ISSUE THREAD

**Issue by HumanG33k** [Chocobozzz/PeerTube#4859]
---
name: ✨ Federation content filter 💡
---

**Describe the problem to be solved**

In order to promote the free(dom) content on a Chaton instance we think it can be great the default view (as anonymous or as user) show only free(dom) content. Also a way to only accept content following free(dom) licences can be great.
 
**Describe the solution you would like:**

A default filter on the federation and local content. 
A way to restrict licences can be used on the local instance.

**Comment by Chocobozzz** [comment]
Hello,

Please fill the [feature template](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/30-feature-request.md)

**Comment by Chocobozzz** [comment]
Thanks, using `filter:api.videos.list.params` hook in a plugin should implement your feature request.

For example:

```js
  registerHook({
    target: 'filter:api.videos.list.params',
    handler: obj => ({ ...obj, licenceOneOf: [ ] })
  })
```

See the [licence](https://docs.joinpeertube.org/api-rest-reference.html#operation/getLicences) endpoint to find available licence ids

**Comment by HumanG33k** [comment]
Ok thx for feedback
