### ISSUE TITLE
Add an option to delete instance follows in bulk 

### ISSUE THREAD

**Issue by Booteille** [Chocobozzz/PeerTube#4863]
**Describe the problem to be solved**
Actually, you can't unfollow a lot of instances at the same time from the web interface, you've to do it one by one.

**Describe the solution you would like:**
That would be awesome to be able to select a lot of instances at the same time and to unfollow them with one click.

So there could be checkboxes on the left, permitting us to select each instance individually.
Also, a checkbox, located in the header of the table, would allow us to select all instances in the shown list.
Finally, a button « Select all » should allow us to select absolutely all instances.

Then, maybe there could be a general « delete » button (and why not a « redundancy » one too) which would act on selected instances.

**Comment by gsugambit** [comment]
Thank you!

**Comment by gsugambit** [comment]
a CLI tool for "unfollow all" would be really nice.

**Comment by Tr4sK** [comment]
@gsugambit maybe you can use that little tool I used to unfolllow/follow en masse

https://framagit.org/Tr4sK/peertools

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/e3d6c6434f570f77c0532f86c82f78bcafb399ec
