### ISSUE TITLE
How to remove left menu options (Trending,subscriptions, ect) With new latest Peertube version

### ISSUE THREAD

**Issue by losless50** [Chocobozzz/PeerTube#4864]
I'm a noob at all this, I've been running a peertube instance for a while now and I love it and completely appreciate you all for doing it! I was wondering how I can remove the Left menu options? I'm using my instance for just me so It's not necessary to have them there. I've looked at the documentation here: [https://docs.joinpeertube.org/contribute-plugins?id=hooks] and I saw that there is a way to do it I just don't understand where to put the code or how to edit the code to my needs. Thank you so much!

**Comment by kontrollanten** [comment]
Hi! You have to create a plugin which filters the menu items. You can have a look at this plugin to get started https://framagit.org/kontrollanten/peertube-plugin-menu-items/-/blob/master/client/common-client-plugin.js

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/4787
