### ISSUE TITLE
Add the possibility to import a liste of video with CLI peertube-import-videos

### ISSUE THREAD

**Issue by DoumeDuSud** [Chocobozzz/PeerTube#4866]
Thanks for your great tools.

Could you had the possibility to import a list of video (write in a file).

In youtube-dl it's the `-a` args. 

Actualy if I put it inside the command with 

```
node dist/server/tools/peertube-import-videos.js \
    -u 'PEERTUBE_URL' \
    -U 'PEERTUBE_USER' \
    --password 'PEERTUBE_PASSWORD' \
    -- -a liste.txt
```
it's complain about the lack of `--target-url` args and if I give also a target-url, it's make an error.

It's will be a great help at the start of a peertube instance to bulks import video.

**Comment by Chocobozzz** [comment]
Hello,

What is the content of `liste.txt`?

**Comment by DoumeDuSud** [comment]
a liste of url, like discribe in [youtube-dl doc](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#filesystem-options)

**Comment by Chocobozzz** [comment]
If there is one URL per line, you can use xargs: `cat list.txt | xargs -L 1 node dist/server/tools/peertube-import-videos.js ...`

**Comment by DoumeDuSud** [comment]
ok, thanks for the tips
