### ISSUE TITLE
Unclear how to proceed with Resumable Video Uploads in API documentation

### ISSUE THREAD

**Issue by ekianjo** [Chocobozzz/PeerTube#4868]
**Parts of the documentation concerned:**

https://docs.joinpeertube.org/api-rest-reference.html#operation/uploadResumable

> upload_id
> required
> string

> Created session id to proceed with. If you didn't send chunks in the last 12 hours, it is not valid anymore and you need to initialize a new upload.
> header Parameters
> Content-Length
> required
> number, Example: 262144
> Size of the chunk that the request is sending.
> The chunk size must be a multiple of 256 KB, and unlike [Google Resumable](https://developers.google.com/youtube/v3/guides/using_resumable_upload_protocol) doesn't mandate for chunks to have the same size throughout the upload sequence.
> Remember that larger chunks are more efficient. PeerTube's web client uses chunks varying from 1048576 bytes (~1MB) and increases or reduces size depending on connection health.

>Content-Range
> required
> string
> Example: bytes 0-262143/2469036
> Specifies the bytes in the file that the request is uploading.
> For example, a value of bytes 0-262143/1000000 shows that the request is sending the first 262144 bytes (256 x 1024) in a 2,469,036 byte file.

**Describe the desired information/correction**

Something is not clear for me regarding the content-length. You mention it should be a multiple of 256KB, but what about the last chunk you transmit in a file, if that file does not end up perfectly with a 256kb chunk anyway? How are you supposed to handle such chunks?

One more thing, in the last example with the "bytes 0-262143/2469036" I am not sure about the following: Is 2469036 the actual file size or should it represent the position of the last chunk (which should be 2469035 since we start from 0?) Or does that mean that the last chunk will look like: "bytes <value>-2469035/2469036" ?

The documentation is lacking in details and the examples only take in account the first chunk, while the last chunk is really the one that is irregular both in size and position parameter. Appreciate if you could clarify.

**Comment by ekianjo** [comment]
@rigelk - additional comment - while I reported this as documentation improvement I am currently unable to make my script work - the first chunks proceed file with a 308 response but I fail to get a 200 response from the last chunk.

**Comment by kukhariev** [comment]
ngx-uploadx set 256KB dynamic chunk limit only for [Google storages ](https://cloud.google.com/storage/docs/performing-resumable-uploads)compatibility. This should probably be removed from api docs.

@ekianjo,
> One more thing, in the last example with the "bytes 0-262143/2469036" I am not sure about the following: Is 2469036 the actual file size or should it represent the position of the last chunk (which should be 2469035 since we start from 0?) Or does that mean that the last chunk will look like: "bytes -2469035/2469036" ?

 [Here ](https://github.com/kukhariev/node-uploadx/blob/master/proto.md)is a few details.

**Comment by Chocobozzz** [comment]
Thanks, I removed the bad information from https://github.com/Chocobozzz/PeerTube/commit/b4a4bcd20e401a6e7db4345a0a5cc238c6b99200

> The documentation is lacking in details and the examples only take in account the first chunk, while the last chunk is really the one that is irregular both in size and position parameter. Appreciate if you could clarify.

We did not explain the protocol in the REST API since we've put a link in the description to https://github.com/kukhariev/node-uploadx/blob/master/proto.md. Don't hesitate to comment this issue if you still need help

**Comment by ekianjo** [comment]
@Chocobozzz thanks a lot for the explanations and the link - I have now solved my issue! 
I see you proposed some slight changes in https://github.com/Chocobozzz/PeerTube/commit/b4a4bcd20e401a6e7db4345a0a5cc238c6b99200, it may be a good idea to also add a link to the proto.md link somewhere inside there, because I am not sure where it was supposed to be in the docs.

**Comment by Chocobozzz** [comment]
@ekianjo There is a link to proto.md in the description https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/api/openapi.yaml#L2069 :)
