### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by MOHAMADRV2007** [Chocobozzz/PeerTube#4870]
hi 1-how we can create translation files from weblet to use in our project in gitpot?2-how we can create our nighty wersion from gitpod to use in server . tnx a lot

**Comment by Chocobozzz** [comment]
Hello,

I don't think it's possible. But you can try to build peertube locally using https://docs.joinpeertube.org/install-unofficial?id=git

**Comment by MOHAMADRV2007** [comment]
ok its means that we cant reproduce translation files ? some of translations are not correct and after correction ???
