### ISSUE TITLE
Blank page on Create Channel

### ISSUE THREAD

**Issue by smilekison** [Chocobozzz/PeerTube#4871]
I think this is a critical bug, so sorry to mention @Chocobozzz & @JohnXLivingston , I pulled the latest develop branch and built it. I see that the you have removed the avatar column from Actor Table. So, I am unable to create a new channel in my account. I have tried it. Can you check it out on this one?

**Comment by kontrollanten** [comment]
Hi! Have you ran the migration script? https://github.com/Chocobozzz/PeerTube/issues/4865#issuecomment-1070827112 Please paste both browser and server logs.

**Comment by smilekison** [comment]
I am running PeerTube on my local server.

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/9ca5728be138fad03a63b6701cd4164a9433509d
