### ISSUE TITLE
Make Latin translation file available

### ISSUE THREAD

**Issue by JimKillock** [Chocobozzz/PeerTube#4873]
Hi there,

On Weblate, I would like to add some Latin translations for a Peertube project I am working on. However, Latin is not available as a option. Could you add it for me?

Thank you!

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I don't understand.

> On Weblate, I would like to add some Latin translations for a Peertube project I am working on

What is your project? An external one? If yes, why do you want to use PeerTube weblate?

**Comment by JimKillock** [comment]
Hi there, my project is a PeerTube instance, in Latin featuring Latin language videos. So I would like to start a PeerTube Latin interface translation, but Latin is not available as a translateable option within PeerTube's Weblate interface. So I would like someone to allow for Latin to be translated at Weblate.

**Comment by Chocobozzz** [comment]
Okay thanks, I added it on https://weblate.framasoft.org/languages/la/peertube/
