### ISSUE TITLE
using calendar 

### ISSUE THREAD

**Issue by MOHAMADRV2007** [Chocobozzz/PeerTube#4874]
hi . is it possible to use another calendar like Hijri or other calendars . or if we can select among calendars in root account for all instance . tanx a lot

**Comment by Chocobozzz** [comment]
HI,

No unfortunately it's not possible because the library we use does not support it. Please subscribe to https://github.com/primefaces/primeng/issues/8706

**Comment by MOHAMADRV2007** [comment]
Tanks a lot for your moment
