### ISSUE TITLE
Changes in Database?

### ISSUE THREAD

**Issue by smilekison** [Chocobozzz/PeerTube#4875]
Hi developers,
After the release of 4.1.1, I see that there were some changes made on the database. Is it possible to release the database schema with after releasing or changing the database like in changes.md file or somewhere just to be clear about the changes made. So,  can you please provide us with the database schema so that it will be easier for us to create Plugins ?

**Comment by Chocobozzz** [comment]
Hi,

You can see all database changes reading migration files in https://github.com/Chocobozzz/PeerTube/tree/develop/server/initializers/migrations
