### ISSUE TITLE
Faulty ffmpeg command paralyses system

### ISSUE THREAD

**Issue by M-Stenzel** [Chocobozzz/PeerTube#4876]
**Describe the current behavior**

Transcoding stalls with incorrect ffmpeg command

This is an example of an incorrect ffmpeg command, generated by peertube

sudo -u peertube /usr/bin/ffmpeg -loop 1 -i /mnt/volume-hel1-3/peertube/storage/tmp/3f0e3771-c499-4a9c-a6f1-073186f5774d.jpg -i /mnt/volume-hel1-3/peertube/storage/videos/f6df6746-bb52-44ae-9ed9-e3e67a384962-0.mp4 -y -an -vcodec libx264 -threads 4 -f mp4 -movflags faststart -max_muxing_queue_size 1024 -map_metadata -1 -pix_fmt yuv420p -vf scale=trunc(iw/2)*2:trunc(ih/2)*2 -level:v 3.1 -preset:v veryfast -tune stillimage -shortest /mnt/volume-hel1-3/peertube/storage/tmp/56573-transcoded.mp4

Running this manually results in 

-bash: syntax error near unexpected token `('

When killing the job manually transcoding the subsequent jobs runs fine.

Maybe this is related to a newer peertube version (4.1.1)? I am not aware of this when running version 4.0 (if this is correct).

**Steps to reproduce:**

1. Upload mp4 or mp3
2. Wait for transcoding
3. Transcoding never finishes
4. All subsequent transcoding jobs will not get started, the transcoding system gets "paralysed"

**Describe the expected behavior**

Transcoding videos runs without any errors.

**Additional information**

* PeerTube instance:
  * URL: https://tube.xy-space.de
  * version: 4.1.1
  * NodeJS version: v12.22.5
  * Ffmpeg version: ffmpeg version 4.2.5

* Browser name, version and platforms on which you could reproduce the bug: any browser
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

The server logs are not available since the log file limit was reached, so the last logs are the ones from version 4.0.0. Right now there are no warnings/errors in the log, with ffmpeg command being logged. 

{"supportedEncoders":[["libfdk_aac",true],["aac",true],["libx264",true]],"searchEncoders":["libfdk_aac","aac","libx264"],"tags":["ffmpeg"],"level":"info","message":"Built supported ffmpeg encoders.","label":"tube.xy-space.de:443","timestamp":"2022-03-24T09:43:47.973Z"}

**Comment by Chocobozzz** [comment]
Hello,

Please paste server logs regarding the ffmpeg error
