### ISSUE TITLE
What is the license for the PeerTube logo?

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#4878]
I could not find the license through the issues or through this page:
https://github.com/Chocobozzz/PeerTube/blob/develop/CREDITS.md#icons

Wikipedia says the logo along with the text is in CC BY-SA:
https://commons.wikimedia.org/wiki/File:Logo_PeerTube_long_accented.svg

Also who should I credit for it?

Thanks in advance :pray:

**Comment by Chocobozzz** [comment]
Hi,

CC BY-SA :)
