### ISSUE TITLE
Clickable watermark logo on the corner of the player

### ISSUE THREAD

**Issue by fredsif** [Chocobozzz/PeerTube#488]
As Peertube is a FOSS replacement of Youtube, a lot of potential Youtubers creators could be interested into creating their own instance exclusively with their original content so they don't have to rely anymore on Google & get their own revenue via crowdsourced funding _(patreon, etc.)_

A nice way for gaining referral traffic, and share bandwidth, would be creating a section on the site as "_Recommended_", where you can add other _peertube_ instances videos from creators that you like with a backlink to their site/instance. It could be the most popular videos of others creators, or popular videos within the instances network. 
Each referral videos on the "_recommended_" section could have their own watermark that is clickable in the corner (_ie. a logo_), so they can promote their site.

That way, each instances can increase their video delivery capacity by sharing it via their own p2p/webseed traffic with the side effect of gaining referral traffic.

This could be a nice way to increase adoption of the software.

**Comment by rigelk** [comment]
@fredsif if I get your proposal right, _referred_ videos are actually a hosted clone that helps seed the video.

How is it different from #123 ? (apart from the fact you then give existence to a logo in the corner, and a seperate video object on the referring instance). I'd rather have suggestions added to that canonical issue directly.

**Comment by fredsif** [comment]
@rigelk Oh, I didn't saw that issue with server redundancy. 
Yes, I'm saying pretty much the same examples on that thread, manually set by the administrator.

But my suggestion for a personalized watermark on the player with a link to the site is a great idea to gain referral traffic and push the adoption of the software.
Others can use the embed video to post it on blogs, etc. and the watermark will show up.

**Comment by rigelk** [comment]
I guess we can just bring the idea on issue #123 then.
