### ISSUE TITLE
Error upgrading 4.1.0 to 4.1.1

### ISSUE THREAD

**Issue by TILvids** [Chocobozzz/PeerTube#4882]
**Describe the current behavior**
Using a yunohost administered installation, attempted to upgrade from 4.1.0 to 4.1.1. Upgrade fails, results in 502 Bad Gateway.

**Steps to reproduce:**

1. Have a 4.1.0 instance managed by yunohost
2. Upgrade to 4.1.1.
3. Instance no longer accessible.

**Describe the expected behavior**
Expect upgrade to go through successfully.

**Additional information**
Not sure if this is a yunohost-specific issue, or something with 4.1.1. Haven't had any upgrade problems in the past, this one just totally bailed. I tried getting some logs to see what might be going on. In 'peertube.log' I have a bunch of:

> {"level":"info","message":"Database peertube_peertube is ready.","label":"tilvids.com:443","timestamp":"2022-03-27T03:02:25.592Z"}
{"err":{"stack":"Error\n    at Query.run (/var/www/peertube/node_modules/sequelize/dist/lib/dialects/postgres/query.js:50:25)\n    at /var/www/peertube/node_modules/sequelize/dist/lib/sequelize.js:313:28\n    at processTicks$

(hundreds of them in the log)

I grabbed the yunopaste of the error logs as well. I'm not an expert, but it seems like there was an issue while trying to re-initialize the postgres database during the upgrade (maybe a duplicate entry?) and it caused the upgrade to hang, eventually give up, and get into a bad state. Here's the log for that: https://paste.yunohost.org/raw/lecorivudu

I've been working on it for about a day, but can't get to the bottom of what's happening, so I'm tapping out and asking the community! Thanks in advance!

* PeerTube instance:
  * URL: tilvids.com
  * version: 4.1.0 >> 4.1.1
  * NodeJS version: 16.14.2
  * Ffmpeg version: 4.1.8

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

>Mar 27 03:08:16 tilvids.com systemd[1]: Started PeerTube daemon.
Mar 27 03:08:22 tilvids.com peertube[1374]: [tilvids.com:443] 2022-03-27 03:08:22.491 info: Database peertube_peertube is ready.
Mar 27 03:08:22 tilvids.com peertube[1374]: [tilvids.com:443] 2022-03-27 03:08:22.739 error: Cannot install application. {
Mar 27 03:08:22 tilvids.com peertube[1374]:   "err": {
Mar 27 03:08:22 tilvids.com peertube[1374]:     "stack": "Error\n    at Query.run (/var/www/peertube/node_modules/sequelize/dist/lib/dialects/postgres/query.js:50:25)\n    at /var/www/peertube/node_modules/sequelize/dist/lib/
Mar 27 03:08:22 tilvids.com peertube[1374]:     "message": "Validation error",
Mar 27 03:08:22 tilvids.com peertube[1374]:     "name": "SequelizeUniqueConstraintError",
Mar 27 03:08:22 tilvids.com peertube[1374]:     "errors": [
Mar 27 03:08:22 tilvids.com peertube[1374]:       {
Mar 27 03:08:22 tilvids.com peertube[1374]:         "message": "url must be unique",
Mar 27 03:08:22 tilvids.com peertube[1374]:         "type": "unique violation",
Mar 27 03:08:22 tilvids.com peertube[1374]:         "path": "url",
Mar 27 03:08:22 tilvids.com peertube[1374]:         "value": "https://tilvids.com/accounts/john_doe",
Mar 27 03:08:22 tilvids.com peertube[1374]:         "origin": "DB",
Mar 27 03:08:22 tilvids.com peertube[1374]:         "instance": null,
Mar 27 03:08:22 tilvids.com peertube[1374]:         "validatorKey": "not_unique",
Mar 27 03:08:22 tilvids.com peertube[1374]:         "validatorName": null,
Mar 27 03:08:22 tilvids.com peertube[1374]:         "validatorArgs": []
Mar 27 03:08:22 tilvids.com peertube[1374]:       }
Mar 27 03:08:22 tilvids.com peertube[1374]:     ],
Mar 27 03:08:22 tilvids.com peertube[1374]:     "parent": {
Mar 27 03:08:22 tilvids.com peertube[1374]:       "stack": "error: could not create unique index \"actor_url\"\n    at Parser.parseErrorMessage (/var/www/peertube/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser
Mar 27 03:08:22 tilvids.com peertube[1374]:       "message": "could not create unique index \"actor_url\"",
Mar 27 03:08:22 tilvids.com peertube[1374]:       "length": 204,
Mar 27 03:08:22 tilvids.com peertube[1374]:       "name": "error",
Mar 27 03:08:22 tilvids.com peertube[1374]:       "severity": "ERROR",
Mar 27 03:08:22 tilvids.com peertube[1374]:       "code": "23505",
Mar 27 03:08:22 tilvids.com peertube[1374]:       "detail": "Key (url)=(https://tilvids.com/accounts/john_doe) is duplicated.",
Mar 27 03:08:22 tilvids.com peertube[1374]:       "schema": "public",
Mar 27 03:08:22 tilvids.com peertube[1374]:       "table": "actor",
Mar 27 03:08:22 tilvids.com peertube[1374]:       "constraint": "actor_url",
Mar 27 03:08:22 tilvids.com peertube[1374]:       "file": "tuplesort.c",
Mar 27 03:08:22 tilvids.com peertube[1374]:       "line": "4056",
Mar 27 03:08:22 tilvids.com peertube[1374]:       "routine": "comparetup_index_btree",
Mar 27 03:08:22 tilvids.com peertube[1374]:       "sql": "CREATE UNIQUE INDEX \"actor_url\" ON \"actor\" (\"url\")"
Mar 27 03:08:22 tilvids.com peertube[1374]:     },
Mar 27 03:08:22 tilvids.com peertube[1374]:     "fields": {
Mar 27 03:08:22 tilvids.com peertube[1374]:       "url": "https://tilvids.com/accounts/john_doe"
Mar 27 03:08:22 tilvids.com peertube[1374]:     },
Mar 27 03:08:22 tilvids.com peertube[1374]:     "sql": "CREATE UNIQUE INDEX \"actor_url\" ON \"actor\" (\"url\")"
Mar 27 03:08:22 tilvids.com peertube[1374]:   }
Mar 27 03:08:22 tilvids.com peertube[1374]: }
Mar 27 03:08:22 tilvids.com systemd[1]: peertube.service: Main process exited, code=exited, status=255/EXCEPTION

**Comment by Chocobozzz** [comment]
Hello,

I don't understand what could happened, since the actor url unique index is there since a long time. The database may be broken.

Anyway, you can try to fix your database using `psql peertub_prod` and running `SELECT url FROM actor GROUP BY "url" HAVING COUNT(*) > 1`

Then, delete duplicated rows

**Comment by TILvids** [comment]
Ugh, I tried messing with psql, it wants the password for the peertube user, and I'm not sure if I have it, because I let yunohost do the install. Can I change the peertube user password to get in to do that, or will that mess up a bunch of permissions?

Thanks!

Kelly

-------- Original Message --------

**Comment by TILvids** [comment]
Ok, I deleted the offending "duplicate" row, and re-ran the update, but it still failed. Lots of errors again, but this one seems relevant:

> 58850 writing new private key to 'example.com.key'
58850 -----
107508 (this may take some time)
379435 The service peertube didn't fully executed the action start before the timeout.
379445 Please find here an extract of the end of the log of the service peertube:
379493 Mar 27 13:57:22 peertube[23024]: "schema": "public",
379494 Mar 27 13:57:22 peertube[23024]: "table": "actor",
379494 Mar 27 13:57:22 peertube[23024]: "constraint": "actor_preferred_username",
379495 Mar 27 13:57:22 peertube[23024]: "file": "tuplesort.c",
379496 Mar 27 13:57:22 peertube[23024]: "line": "4056",
379497 Mar 27 13:57:22 peertube[23024]: "routine": "comparetup_index_btree",
379498 Mar 27 13:57:22 peertube[23024]: "sql": "CREATE UNIQUE INDEX \"actor_preferred_username\" ON \"actor\" (\"preferredUsername\") WHERE \"serverId\" IS NULL"
379499 Mar 27 13:57:22 peertube[23024]: },
379499 Mar 27 13:57:22 peertube[23024]: "fields": {
379500 Mar 27 13:57:22 peertube[23024]: "preferredUsername": "james_h_jackson_jr"
379501 Mar 27 13:57:22 peertube[23024]: },
379501 Mar 27 13:57:22 peertube[23024]: "sql": "CREATE UNIQUE INDEX \"actor_preferred_username\" ON \"actor\" (\"preferredUsername\") WHERE \"serverId\" IS NULL"
379502 Mar 27 13:57:22 peertube[23024]: }
379502 Mar 27 13:57:22 peertube[23024]: }
379503 Mar 27 13:57:22 systemd[1]: peertube.service: Main process exited, code=exited, status=255/EXCEPTION
379503 Mar 27 13:57:22 systemd[1]: peertube.service: Failed with result 'exit-code'.
379504 Mar 27 13:57:23 systemd[1]: peertube.service: Service RestartSec=100ms expired, scheduling restart.
379504 Mar 27 13:57:23 systemd[1]: peertube.service: Scheduled restart job, restart counter is at 70.
379505 Mar 27 13:57:23 systemd[1]: Stopped PeerTube daemon.
379505 Mar 27 13:57:23 systemd[1]: Started PeerTube daemon.

Seems questionable that there would just be another "duplicate" in there. I'm going to try deleting that row as well, but if (assuming) that doesn't work, it's making me wonder if the database became corrupted somehow?

**Comment by TILvids** [comment]
Re-read what was going on in the error above, and didn't delete that row because it doesn't actually say it's a duplicate. In looking at the new error logs, it really looks like the upgrade is falling down while at some step in processing the database, and that's just where it starts throwing errors. Here's the new log - https://paste.yunohost.org/raw/fokenatome

This is where it looks like things start falling apart...

> 2022-03-27 13:45:16,457: DEBUG - + systemctl enable peertube --quiet
2022-03-27 13:45:16,649: DEBUG - + systemctl daemon-reload
2022-03-27 13:45:16,842: INFO - [##########+.........] > Starting a systemd service...
2022-03-27 13:45:16,843: DEBUG - + ynh_systemd_action --service_name=peertube --action=start --log_path=systemd '--line_match=HTTP server listening on localhost'
2022-03-27 13:45:17,005: DEBUG - + service_name=peertube
2022-03-27 13:45:17,006: DEBUG - + action=start
2022-03-27 13:45:17,006: DEBUG - + line_match='HTTP server listening on localhost'
2022-03-27 13:45:17,006: DEBUG - + length=20
2022-03-27 13:45:17,006: DEBUG - + log_path=systemd
2022-03-27 13:45:17,006: DEBUG - + timeout=300
2022-03-27 13:45:17,006: DEBUG - + '[' start == stop ']'
2022-03-27 13:45:17,006: DEBUG - + [[ -n HTTP server listening on localhost ]]
2022-03-27 13:45:17,006: DEBUG - ++ mktemp
2022-03-27 13:45:17,007: DEBUG - + local templog=/tmp/tmp.8kDs4z2Emc
2022-03-27 13:45:17,007: DEBUG - + '[' systemd == systemd ']'
2022-03-27 13:45:17,007: DEBUG - + local pid_tail=1569
2022-03-27 13:45:17,007: DEBUG - + journalctl --unit=peertube --follow --since=-0 --quiet
2022-03-27 13:45:17,007: DEBUG - + '[' start == reload ']'
2022-03-27 13:45:17,007: DEBUG - + systemctl start peertube
2022-03-27 13:45:17,014: DEBUG - + [[ -n HTTP server listening on localhost ]]
2022-03-27 13:45:46,110: WARNING - (this may take some time)
2022-03-27 13:50:18,041: DEBUG - + '[' 300 -ge 3 ']'
2022-03-27 13:50:18,042: DEBUG - + '[' 300 -eq 300 ']'
2022-03-27 13:50:18,042: DEBUG - + ynh_print_warn '--message=The service peertube didn'\''t fully executed the action start before the timeout.'
2022-03-27 13:50:18,042: DEBUG - 
2022-03-27 13:50:18,054: DEBUG - + ynh_print_log 'The service peertube didn'\''t fully executed the action start before the timeout.'
2022-03-27 13:50:18,054: DEBUG - + echo -e 'The service peertube didn'\''t fully executed the action start before the timeout.'
2022-03-27 13:50:18,054: DEBUG - + ynh_print_warn '--message=Please find here an extract of the end of the log of the service peertube:'
2022-03-27 13:50:18,055: WARNING - The service peertube didn't fully executed the action start before the timeout.
2022-03-27 13:50:18,068: DEBUG - + ynh_print_log 'Please find here an extract of the end of the log of the service peertube:'
2022-03-27 13:50:18,068: WARNING - Please find here an extract of the end of the log of the service peertube:
2022-03-27 13:50:18,070: DEBUG - + echo -e 'Please find here an extract of the end of the log of the service peertube:'
2022-03-27 13:50:18,070: DEBUG - + ynh_exec_warn journalctl --quiet --no-hostname --no-pager --lines=20 --unit=peertube

I'll post this over on the yunohost github as well, since I'm not sure if the root-cause of the problem lies with PeerTube, yunohost, or somewhere in-between.

**Comment by Chocobozzz** [comment]
Delete duplicated `james_h_jackson_jr` actor from your `actor` table and I think you'll also have to delete `comedy` tag from `tag` table

**Comment by TILvids** [comment]
Ok, will try that today.

**Comment by TILvids** [comment]
Comment over at yunohost GH thinks it might be related to a plugin that's installed. I tried removing it from CLI but get the following error @Chocobozzz (looks like it can't find the plugin, despite it showing up in the list). Any idea?

> peertube@4.1.0 plugin:uninstall
> node ./dist/scripts/plugin/uninstall.js "--npm-name" "peertube-plugin-tv-streaming"

[tilvids.com:443] 2022-03-28 18:03:24.045 info: Uninstalling plugin peertube-plugin-tv-streaming.
[tilvids.com:443] 2022-03-28 18:03:24.048 info: Unregister plugin peertube-plugin-tv-streaming.
[tilvids.com:443] 2022-03-28 18:03:24.049 warn: Cannot unregister plugin peertube-plugin-tv-streaming. {
  "err": {
    "stack": "Error: Unknown plugin peertube-plugin-tv-streaming to unregister\n    at PluginManager.<anonymous> (/var/www/peertube/dist/server/lib/plugins/plugin-manager.js:180:23)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at __awaiter (/var/www/peertube/node_modules/tslib/tslib.js:113:16)\n    at PluginManager.unregister (/var/www/peertube/dist/server/lib/plugins/plugin-manager.js:176:38)\n    at PluginManager.<anonymous> (/var/www/peertube/dist/server/lib/plugins/plugin-manager.js:260:28)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at __awaiter (/var/www/peertube/node_modules/tslib/tslib.js:113:16)\n    at PluginManager.uninstall (/var/www/peertube/dist/server/lib/plugins/plugin-manager.js:257:38)\n    at /var/www/peertube/dist/scripts/plugin/uninstall.js:25:55\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/node_modules/tslib/tslib.js:114:62)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Unknown plugin peertube-plugin-tv-streaming to unregister"
  }
}
[tilvids.com:443] 2022-03-28 18:03:24.063 error: Cannot uninstall plugin peertube-plugin-tv-streaming: it does not exist or is already uninstalled.

**Comment by TILvids** [comment]
Anyone running into this, resolved over here. TL;DR something happened with either a plugin or duplicate entries in the database.
