### ISSUE TITLE
Support .srt subtitle imports

### ISSUE THREAD

**Issue by JimKillock** [Chocobozzz/PeerTube#4883]
Subtitle files in .srt format are not currently supported; this would be very helpful if importing from Wikimedia for instance.

Be able to import .srt files through direct upload or through URL import of videos

**Describe alternatives you have considered**

**Comment by JimKillock** [comment]
A couple of further remarks:

* yt-download options claim to include subtitle conversion
* In Wikimedia's case, the API outputs srt and vrt formats

**Comment by JimKillock** [comment]
This can now be moved along @Chocobozzz … YT-DLP has aded Wikimedia video support at https://github.com/yt-dlp/yt-dlp/pull/4314

**Comment by Chocobozzz** [comment]
Thanks @JimKillock 
It's working with the latest yt-dlp release.
