### ISSUE TITLE
Rtl layout not working properly in phone

### ISSUE THREAD

**Issue by MOHAMADRV2007** [Chocobozzz/PeerTube#4884]
hi
at first tanks for [Chocobozzz] for reply to all topics in git and here . with his recommends the translation to persian is commplated .
secound , the translated instance with rtl layout is not working properly . a long scroler appears and only several circle like radio buttuns are apeares in left side . why this is happening . please visit the site : fiscalhub.ir
another thanks for your priceless moments .

**Comment by Chocobozzz** [comment]
The issue seems to be fixed with the latest translations pulled and merged into peertube.
