### ISSUE TITLE
private server for registered user only

### ISSUE THREAD

**Issue by discapacidad5** [Chocobozzz/PeerTube#4888]
I would like the server to be configured so that only the videos of registered people are seen. that it is mandatory to log in to be able to see the videos hosted on the server

**Comment by Chocobozzz** [comment]
Hello,

You can upload all videos in `Internal` privacy so only logged in users can see them

**Comment by discapacidad5** [comment]
When a person wants to upload a video to the server they have to register if they don't register they can't upload video I would like the same thing to happen but to play the video to watch it

The intention of this function is to force the user to register on the server to enjoy the service to watch the videos
