### ISSUE TITLE
Account creation crash existing channel account

### ISSUE THREAD

**Issue by klorydryk** [Chocobozzz/PeerTube#4889]
Peertube 4.1.1

If an existing user A create a channel with a specific name B, then a user create a new account with a name B, the creation of this new user will fail with this error "_Another actor (account/channel) with this name on this instance already exists or has already existed._"
Because, I assume, the fediverse names "user@server" and "channel@server" will crash.

it should work, as the users are not able to know that the account is already used as channel... specifically when it comes from OIDC.

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but it can't work. We can't remove an existing channel is favour of a new user created by an external authentication.

**Comment by klorydryk** [comment]
I understand we can't *remove* an existing channel, but for now, a new user cannot connect to this instance, so we need to find a solution to allow a new user to be created, as we can't forbid him when he create the account on the authentication server.
-> How to prevent a crash between "user@server" and "channel@server"? For example prefix the channel names?

**Comment by Chocobozzz** [comment]
> How to prevent a crash between "user@server" and "channel@server"? For example prefix the channel names?

Unfortunately I don't think we can. We did have a suffix in the past for channels, but since it's the main identity displayed on the web interface it was not ideal (you don't want to always have a `username_channel` author name below video miniatures for example). Moreover users wanted to create the identity/brand they wanted without being forced to have a suffix to their channel.

**Comment by klorydryk** [comment]
So how could we do?
We had this problem 1 time with 80 accounts, and have been able to rename the channel, but when we'll have 80.000 accounts, it could be more complicated...

**Comment by klorydryk** [comment]
I think that adding a setting to force a prefix, and, in case of conflict, auto-suffixing the name, could resolve all the possible problems.

**Comment by Chocobozzz** [comment]
Hello,

With now add a suffix to user and channel usernames in case of conflict: https://github.com/Chocobozzz/PeerTube/commit/0b6f531653a7a24f82ad65564479a70a9326301a
