### ISSUE TITLE
PeerTube can't find assets, 500 errors

### ISSUE THREAD

**Issue by vitobotta** [Chocobozzz/PeerTube#4891]
**Describe the problem**

Hi! Just installed PeerTube with Docker Compose (https://bin.botta.me/h4eF) and I get 500 errors when I visit the site. In the logs I see this:

```
[video.domain.com:443] 2022-03-30 16:34:57.274 error: Cannot generate HTML page. ENOENT: no such file or directory, open '/app/client/dist/en-US/index.html' {
  "errno": -2,
  "code": "ENOENT",
  "syscall": "open",
  "path": "/app/client/dist/en-US/index.html",
  "stack": "Error: ENOENT: no such file or directory, open '/app/client/dist/en-US/index.html'"
}
```

What am I missing? Thanks!

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Just using Docker Compose, see pastebin above.

**Additional information**

* PeerTube instance:
  * version: latest image tag as of today
  * NodeJS version:
  * Ffmpeg version:
  * Redis version:
  * PostgreSQL version: 14

**Comment by vitobotta** [comment]
NVM, It works if I don't mount the assets directory to a dir.

**Comment by worldofgeese** [comment]
This also bit me. The assets directory should probably be removed from the docker-compose example.

**Comment by Chocobozzz** [comment]
It's weird, we declare the volume for the [webserver](https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/docker-compose.yml#L23) and [peertube](https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/docker-compose.yml#L61). Since the webserver [depends on peertube](https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/docker-compose.yml#L28), the volume should be populated by peertube container files. It seems in you cases that it's the opposite, and so the directory is empty since the webserver does not have such directory. :thinking:

**Comment by fuomag9** [comment]
> It's weird, we declare the volume for the [webserver](https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/docker-compose.yml#L23) and [peertube](https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/docker-compose.yml#L61). Since the webserver [depends on peertube](https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/docker-compose.yml#L28), the volume should be populated by peertube container files. It seems that in you case, it's the opposite, and so the directory is empty since the webserver does not have such directory. 🤔

In my case I was using a local folder

```
volumes:
      - ./assets:/app/client/dist
```
instead of:
```
volumes:
      - assets:/app/client/dist
```

Removing it solved my issue. Why a volume for that folder is it even needed if the files are already present in the container? @Chocobozzz

**Comment by Chocobozzz** [comment]
So the nginx container can serve them

**Comment by fuomag9** [comment]
> So the nginx container can serve them

Ah, makes sense.

Maybe I missed it, but it'd probably be a good idea to document this (I can make a PR if you want) if someone doesn't use the nginx container (as I already have a reverse proxy)

**Comment by Chocobozzz** [comment]
Sure, I think we can add a comment in the docker compose file :) Don't hesitate to create a PR
