### ISSUE TITLE
Original resolution and default resolution description needs editing

### ISSUE THREAD

**Issue by JimKillock** [Chocobozzz/PeerTube#4892]
**Describe the current behavior**

At admin/config/edit-custom#transcoding it states

"The original file resolution will be the default target if no option is selected."

AIUI according to #4241 this is not quite true; on import from yt-downloader the target file resolution is 720px. This should be explained here, and id this setting overrides the the 720px default resolution, this should be explained also.

**Comment by Chocobozzz** [comment]
Hello,

The sentence is correct: we import the 720p version and send the file to the transcoding process that will transcode using the input file resolution (720p). See https://github.com/Chocobozzz/PeerTube/issues/3987 for a configurable import behaviour.
