### ISSUE TITLE
"If you are looking for an account… Currently this instance doesn't allow for user registration"

### ISSUE THREAD

**Issue by TrevorMellon** [Chocobozzz/PeerTube#4893]
docker image latest
same issue as reported [here](https://github.com/Chocobozzz/PeerTube/issues/2441)

User signup disabled even though it's enabled in both the .env and through the web interface, this has been an issue since the last couple of pulls.

Reading above link, the solution was a cache issue but the "assets" volume has been purged, not sure what to try next.

**Comment by Chocobozzz** [comment]
Hello,

Please fill the [bug template](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/00-bug-issue.md)
