### ISSUE TITLE
Feature request: Webtorrent HLS

### ISSUE THREAD

**Issue by LoveIsGrief** [Chocobozzz/PeerTube#4895]
**Describe the problem to be solved**

CLI seeds for HLS streams. I wrote a [reseeder for peertube](https://gitlab.com/NamingThingsIsHard/media_tools/peertube-reseed) that uses webtorrent. However, I found out that it doesn't work with HLS streams because [p2p-media-loader](https://github.com/Novage/p2p-media-loader) is being used that only uses the webtorrent trackers, but doesn't actually use webtorrents (I might be wrong though).

**Describe the solution you would like:**

A single torrent for the chunks. It should then be possible to instruct webtorrent to download sequentially or a certain file in the torrent.

**Describe alternatives you have considered**  

 - An option for viewers to fallback to using webtorrent files (`.files[]` in the result from `/videos/{id}` endpoint)
 - A torrent per chunk

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but it's out of the scope of PeerTube. If you want to create a CLI script to seed HLS streams, you can try to use [p2p-media-loader](https://github.com/Novage/p2p-media-loader) directly in your library.

**Comment by LoveIsGrief** [comment]
The script already exists, but had to be written in Python because webtorrent didn't work. It seeds the torrents just find, but the HLS videos just don't work. Webtorrent uses WebRTC and the npm package uses a headless chromium instance which fails (https://github.com/feross/simple-peer/issues/866).

I'd like to contribute bandwidth to peertube without running a full instance of peertube. Is there a way to do that?

**Comment by Chocobozzz** [comment]
> I'd like to contribute bandwidth to peertube without running a full instance of peertube. Is there a way to do that?

Unfortunately no
