### ISSUE TITLE
Video transcoded fail: already transcoded but actually not

### ISSUE THREAD

**Issue by fweng322** [Chocobozzz/PeerTube#4896]
**Describe the current behavior**
I'm re-creating transcoding job from stale ones.  The following two videos could not be transcoded to HLS because an error message "This video is already being transcoded" was shown.  

https://peertube.slat.org/w/4KxWoUTonpiQMEQiaUej94
https://peertube.slat.org/w/q3gsTxPwkJTby3NkibiisJ

However in the list these two videos only show Webtorrent ones as shown in the [screenshot](https://nextcloud.slat.org/index.php/s/dmHLe5KxePHACkF)

**Describe the expected behavior**
It should transcode to HLS.

**Additional information**
I used to run transcoding jobs a few weeks ago but the hard drive was full so many jobs were stale there.  I'm now re-creating transcoding jobs following the way described [here](https://docs.joinpeertube.org/maintain-tools?id=create-transcoding-jobjs).

* PeerTube instance:
  * URL: https://peertube.slat.org/
  * version: 4.1.0
  * NodeJS version: 16.14.2
  * Ffmpeg version: 4.3.3

**Comment by Chocobozzz** [comment]
Hi,

Please update peertube to 4.1.1. I think https://github.com/Chocobozzz/PeerTube/commit/f6f48301a9ad392759d714d2cff13f1564942a50 should fix your issue.

**Comment by cutec-chris** [comment]
for me this dont works also with 5.2.1

**Comment by Chocobozzz** [comment]
@cutec-chris Please create a dedicated issue and fill the bug template :)
