### ISSUE TITLE
is it possible to add a custom banner or for example custom slideshow to landingpage?

### ISSUE THREAD

**Issue by MOHAMADRV2007** [Chocobozzz/PeerTube#4898]
is it possible to add a custom banner or for example custom slideshow  or image to landingpage?

**Comment by Chocobozzz** [comment]
Hi,

Yes your can. Since the homepage accepts markdown, you can inject an image: `![img](https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg)`

See the guide for more information https://docs.joinpeertube.org/api-custom-client-markup)

**Comment by MOHAMADRV2007** [comment]
tanks a lot .
