### ISSUE TITLE
Unable to upload video files in .mts / .m2ts / .aac / .ac3 / .vob format

### ISSUE THREAD

**Issue by raazkarkee405** [Chocobozzz/PeerTube#4899]
I tried uploading **.mts** / **.m2ts** / **.aac** / **.ac3** / **.vob** format video files in my PeerTube but none were uploaded instead I got an error message mentioning the video format was not supported.
![Screenshot from 2022-04-05 11-22-54](https://user-images.githubusercontent.com/26194365/161731299-15f2c3d5-0c6a-446c-b312-d3d2cb6a50a3.png)

PeerTube Version: 4.1.1
I had installed two plugins **transcoding-custom-quality** & **transcoding-profile-debug** with some settings but uninstalling both the plugins still showed the same result.

I have following setting for VOD transcoding.
<img src="https://user-images.githubusercontent.com/26194365/161733067-61ffd1e2-024f-4dbd-9444-8923b6625a19.png" width="450" height="450">

<img src="https://user-images.githubusercontent.com/26194365/161733836-01ef14bf-8ced-40a0-8f4c-dc73f5cdf63a.png" width="450" height="450">

Also, there is no system log related to this.

**Comment by Chocobozzz** [comment]
Hi,

What web browser and OS do you use?

**Comment by raazkarkee405** [comment]
Hello,

I tried uploading those file format videos from windows using firefox.

At first, I tried uploading those file format using GUI but, i got the error mentioned above.
After that, I tried uploading the same file with same formats using API provided by PeerTube, in this approch the file were successfully uploaded.

The script file I ran to upload the files as provided in the documentation:

```
## DEPENDENCIES: jq
USERNAME="root"
PASSWORD="peertube"
FILE_PATH="/home/xxx/Downloads/Music/ac3/sample1.ac3"
CHANNEL_ID="24"
NAME="ac3"
CATEGORY_ID="1"
DESCRIPTION="This is the sample video for testing ac3 format uploaded using API"
PRIVACY_ID="1"
API="https://example.com/api/v1"

## AUTH
client_id=$(curl -s "$API/oauth-clients/local" | jq -r ".client_id")
client_secret=$(curl -s "$API/oauth-clients/local" | jq -r ".client_secret")
token=$(curl -s "$API/users/token" \
  --data client_id="$client_id" \
  --data client_secret="$client_secret" \
  --data grant_type=password \
  --data username="root" \
  --data password="peertube" \
  | jq -r ".access_token")

## VIDEO UPLOAD
curl -s "$API/videos/upload" \
  -H "Authorization: Bearer $token" \
  --max-time 600 \
  --form videofile=@"$FILE_PATH" \
  --form channelId=$CHANNEL_ID \
  --form name="$NAME" \
  --form category=$CATEGORY_ID \
  --form description="$DESCRIPTION" \
  --form privacy=$PRIVACY_ID \
```
Result:
![image](https://user-images.githubusercontent.com/26194365/162455093-e36c63f3-2b9b-4ea6-89eb-95cfe5e06139.png)

The video gets uploaded from API but the other issue I have faced here is the **transcoding** of the uploaded audio files are failed even if the **audio-only** options is enabled in **VOD transcoding**.

**Comment by Chocobozzz** [comment]
Hi,

Original issue should be fixed by https://github.com/Chocobozzz/PeerTube/commit/4b7a20d88b11b2935aca0605c43b34bba745b40c

> The video gets uploaded from API but the other issue I have faced here is the transcoding of the uploaded audio files are failed even if the audio-only options is enabled in VOD transcoding.

Please create a dedicated issue with using the bug report template :)
