### ISSUE TITLE
Compilation errors in client

### ISSUE THREAD

**Issue by tcitworld** [Chocobozzz/PeerTube#49]
Running `npm run build` on latest sources gives me something that look like an angular issue.

<details>
<pre>
 ~/dev/PeerTube   develop  npm run build           

> peertube@0.0.1 build /home/tcit/dev/PeerTube
> npm run build:client:prod

> peertube@0.0.1 build:client:prod /home/tcit/dev/PeerTube
> scripty

> peertube-client@0.0.1 webpack /home/tcit/dev/PeerTube/client
> webpack "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"

Starting compilation using the angular compiler.
Angular compilation done, starting webpack bundling.
Error: Error at /home/tcit/dev/PeerTube/client/compiled/node_modules/ng2-completer/components/completer-cmp.ngfactory.ts:846:18: Property 'ctrInput' is private and only accessible within class 'CompleterCmp'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/admin.component.ngfactory.ts:23:19: Namespace ''*'' has no exported member 'AdminComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/admin.component.ngfactory.ts:51:38: Namespace ''*'' has no exported member 'AdminComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/admin.component.ngfactory.ts:79:71: Namespace ''*'' has no exported member 'AdminComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/admin.component.ngfactory.ts:79:126: Namespace ''*'' has no exported member 'AdminComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/admin.component.ngfactory.ts:82:67: Namespace ''*'' has no exported member 'AdminComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/friends/friends.component.ngfactory.ts:23:19: Namespace ''*'' has no exported member 'FriendsComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/friends/friends.component.ngfactory.ts:51:38: Namespace ''*'' has no exported member 'FriendsComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/friends/friends.component.ngfactory.ts:79:73: Namespace ''*'' has no exported member 'FriendsComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/friends/friends.component.ngfactory.ts:79:130: Namespace ''*'' has no exported member 'FriendsComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/friends/friends.component.ngfactory.ts:82:69: Namespace ''*'' has no exported member 'FriendsComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/friends/friend-list/friend-list.component.ngfactory.ts:35:19: Namespace ''*'' has no exported member 'FriendListComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/friends/friend-list/friend-list.component.ngfactory.ts:64:38: Namespace ''*'' has no exported member 'FriendListComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/friends/friend-list/friend-list.component.ngfactory.ts:92:76: Namespace ''*'' has no exported member 'FriendListComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/friends/friend-list/friend-list.component.ngfactory.ts:92:136: Namespace ''*'' has no exported member 'FriendListComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/friends/friend-list/friend-list.component.ngfactory.ts:261:72: Namespace ''*'' has no exported member 'FriendListComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/friends/friend-add/friend-add.component.ngfactory.ts:41:19: Namespace ''*'' has no exported member 'FriendAddComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/friends/friend-add/friend-add.component.ngfactory.ts:70:38: Namespace ''*'' has no exported member 'FriendAddComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/friends/friend-add/friend-add.component.ngfactory.ts:98:75: Namespace ''*'' has no exported member 'FriendAddComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/friends/friend-add/friend-add.component.ngfactory.ts:98:134: Namespace ''*'' has no exported member 'FriendAddComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/friends/friend-add/friend-add.component.ngfactory.ts:365:71: Namespace ''*'' has no exported member 'FriendAddComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/requests/requests.component.ngfactory.ts:23:19: Namespace ''*'' has no exported member 'RequestsComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/requests/requests.component.ngfactory.ts:51:38: Namespace ''*'' has no exported member 'RequestsComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/requests/requests.component.ngfactory.ts:79:74: Namespace ''*'' has no exported member 'RequestsComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/requests/requests.component.ngfactory.ts:79:132: Namespace ''*'' has no exported member 'RequestsComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/requests/requests.component.ngfactory.ts:82:70: Namespace ''*'' has no exported member 'RequestsComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/requests/request-stats/request-stats.component.ngfactory.ts:25:19: Namespace ''*'' has no exported member 'RequestStatsComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/requests/request-stats/request-stats.component.ngfactory.ts:55:38: Namespace ''*'' has no exported member 'RequestStatsComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/requests/request-stats/request-stats.component.ngfactory.ts:84:78: Namespace ''*'' has no exported member 'RequestStatsComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/requests/request-stats/request-stats.component.ngfactory.ts:84:140: Namespace ''*'' has no exported member 'RequestStatsComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/requests/request-stats/request-stats.component.ngfactory.ts:209:74: Namespace ''*'' has no exported member 'RequestStatsComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/users/users.component.ngfactory.ts:23:19: Namespace ''*'' has no exported member 'UsersComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/users/users.component.ngfactory.ts:51:38: Namespace ''*'' has no exported member 'UsersComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/users/users.component.ngfactory.ts:79:71: Namespace ''*'' has no exported member 'UsersComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/users/users.component.ngfactory.ts:79:126: Namespace ''*'' has no exported member 'UsersComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/users/users.component.ngfactory.ts:82:67: Namespace ''*'' has no exported member 'UsersComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/users/user-list/user-list.component.ngfactory.ts:35:19: Namespace ''*'' has no exported member 'UserListComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/users/user-list/user-list.component.ngfactory.ts:64:38: Namespace ''*'' has no exported member 'UserListComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/users/user-list/user-list.component.ngfactory.ts:92:74: Namespace ''*'' has no exported member 'UserListComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/users/user-list/user-list.component.ngfactory.ts:92:132: Namespace ''*'' has no exported member 'UserListComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/users/user-list/user-list.component.ngfactory.ts:230:70: Namespace ''*'' has no exported member 'UserListComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/users/user-add/user-add.component.ngfactory.ts:38:19: Namespace ''*'' has no exported member 'UserAddComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/users/user-add/user-add.component.ngfactory.ts:67:38: Namespace ''*'' has no exported member 'UserAddComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/users/user-add/user-add.component.ngfactory.ts:95:73: Namespace ''*'' has no exported member 'UserAddComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/users/user-add/user-add.component.ngfactory.ts:95:130: Namespace ''*'' has no exported member 'UserAddComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/users/user-add/user-add.component.ngfactory.ts:185:69: Namespace ''*'' has no exported member 'UserAddComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/admin-routing.module.ngfactory.ts:31:75: Namespace ''*'' has no exported member 'AdminRoutingModule'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/admin-routing.module.ngfactory.ts:33:33: Namespace ''*'' has no exported member 'AdminRoutingModule'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/admin-routing.module.ngfactory.ts:138:28: Namespace ''*'' has no exported member 'AdminRoutingModule'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/admin-routing.module.ngfactory.ts:152:74: Namespace ''*'' has no exported member 'AdminRoutingModule'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/admin.module.ngfactory.ts:67:68: Namespace ''*'' has no exported member 'AdminModule'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/admin.module.ngfactory.ts:69:33: Namespace ''*'' has no exported member 'AdminRoutingModule'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/admin.module.ngfactory.ts:81:27: Namespace ''*'' has no exported member 'AdminModule'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/admin.module.ngfactory.ts:101:31: Namespace ''*'' has no exported member 'FriendService'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/admin.module.ngfactory.ts:102:32: Namespace ''*'' has no exported member 'RequestService'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/admin.module.ngfactory.ts:103:29: Namespace ''*'' has no exported member 'UserService'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/admin.module.ngfactory.ts:280:36: Namespace ''*'' has no exported member 'FriendService'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/admin.module.ngfactory.ts:284:37: Namespace ''*'' has no exported member 'RequestService'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/admin.module.ngfactory.ts:288:34: Namespace ''*'' has no exported member 'UserService'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/admin.module.ngfactory.ts:292:28: Namespace ''*'' has no exported member 'AdminModule'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/admin.module.ngfactory.ts:351:67: Namespace ''*'' has no exported member 'AdminModule'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/menu-admin.component.ngfactory.ts:23:19: Namespace ''*'' has no exported member 'MenuAdminComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/menu-admin.component.ngfactory.ts:51:38: Namespace ''*'' has no exported member 'MenuAdminComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/menu-admin.component.ngfactory.ts:79:75: Namespace ''*'' has no exported member 'MenuAdminComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/menu-admin.component.ngfactory.ts:79:134: Namespace ''*'' has no exported member 'MenuAdminComponent'.
Error at /home/tcit/dev/PeerTube/client/compiled/src/app/admin/menu-admin.component.ngfactory.ts:82:71: Namespace ''*'' has no exported member 'MenuAdminComponent'.
    at UserError.Error (native)
    at new UserError (/home/tcit/dev/PeerTube/client/node_modules/tools/@angular/tsc-wrapped/src/tsc.ts:33:25)
    at check (/home/tcit/dev/PeerTube/client/node_modules/tools/@angular/tsc-wrapped/src/tsc.ts:69:11)
    at Tsc.typeCheck (/home/tcit/dev/PeerTube/client/node_modules/tools/@angular/tsc-wrapped/src/tsc.ts:152:5)
    at /home/tcit/dev/PeerTube/client/node_modules/tools/@angular/tsc-wrapped/src/main.ts:68:11
    at process._tickCallback (internal/process/next_tick.js:103:7)

npm ERR! Linux 4.9.0-2-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "webpack" "--" "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! peertube-client@0.0.1 webpack: `webpack "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the peertube-client@0.0.1 webpack script 'webpack "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertube-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertube-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tcit/dev/PeerTube/client/npm-debug.log
/home/tcit/dev/PeerTube/node_modules/scripty/cli.js:38
    if (er) { throw er }
              ^

Error: Error: scripty - script "fail" failed by exiting with a non-zero code (1).
    at ChildProcess.<anonymous> (/home/tcit/dev/PeerTube/node_modules/scripty/lib/run/spawn-script.js:11:10)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

npm ERR! Linux 4.9.0-2-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:client:prod"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! peertube@0.0.1 build:client:prod: `scripty`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the peertube@0.0.1 build:client:prod script 'scripty'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertube package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripty
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertube
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tcit/dev/PeerTube/npm-debug.log

npm ERR! Linux 4.9.0-2-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! peertube@0.0.1 build: `npm run build:client:prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the peertube@0.0.1 build script 'npm run build:client:prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertube package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:client:prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertube
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tcit/dev/PeerTube/npm-debug.log
</pre>
</details>

**Comment by Chocobozzz** [comment]
Try `rm -r /home/tcit/dev/PeerTube/client/compiled/` and re run `npm run build`.

**Comment by tcitworld** [comment]
Works indeed. You can rename the issue.

**Comment by Chocobozzz** [comment]
See https://github.com/oferh/ng2-completer/pull/172

**Comment by Chocobozzz** [comment]
Should be fixed now.
