### ISSUE TITLE
File unreadable error while uploading M2v Video.

### ISSUE THREAD

**Issue by smilekison** [Chocobozzz/PeerTube#4905]
I am getting this error while uploading m2v file in the PeerTube using UI and REST API. I have attached the screenshot of the file and the file.

The file that i am trying to upload: 
https://filesamples.com/samples/video/m2v/sample_960x400_ocean_with_audio.m2v

I am getting this error on UI: 
![Screenshot from 2022-04-07 16-38-08](https://user-images.githubusercontent.com/24309222/162361326-d87aec5e-9764-48eb-9c22-022df6dc2439.png)

I am getting this error while uploading using REST API.
`{"type":"about:blank","title":"Unprocessable Entity","detail":"Video file unreadable.","status":422,"docs":"https://docs.joinpeertube.org/api-rest-reference.html#operation/uploadLegacy","error":"Video file unnce.html#operation/uploadLegacy","error":"Video file unreadable."}`

Additional information
    PeerTube instance:
     Version: 4.1.1
      NodeJS version: v14.19.1
      ffmpeg version 4.2.4-1ubuntu0.1

**Comment by Chocobozzz** [comment]
Closing as the post has already been created on https://framacolibri.org/t/m2v-video-file-unreadable-error/14582
