### ISSUE TITLE
about updated translation files 

### ISSUE THREAD

**Issue by MOHAMADRV2007** [Chocobozzz/PeerTube#4906]
hi i updated some translations in weblet but in recently nightly versions of peertube they are not used . how can i modify the translation files in peertube . some translations have big mistakes. you can see the persian translation logs .tanks a lot

**Comment by Chocobozzz** [comment]
Hi,

Translations has been updated in https://github.com/Chocobozzz/PeerTube/commit/2e25a6dad3308a01dc8fb13a24777eb58a6e5758

As a side note, please stop creating the same post in multiple places (github, personal message, forum, irc etc) at the same time.

**Comment by MOHAMADRV2007** [comment]
thats my mistake . im apologizing . tanks a lot
