### ISSUE TITLE
How to make unsupported browsers for MAC OS X 10.6.8 work? YouTube opens everywhere.

### ISSUE THREAD

**Issue by 600900** [Chocobozzz/PeerTube#4908]
Hello! Tell me how to independently support different Internet browsers, for example in Firefox Nightly 52.9.1 (32-bit version), Chromium 50, Firefox starting from version 43, SeaMonkey (2.40), Pale Moon 29.7.4, then Arctic Fox Web Browser (based on Pale Moon). That is, my question is, is it possible to make a notification about the old browser, with the possibility of closing it and watching video programs on the site. Source: 3.600900.su . Thanks for the answers and support.

**Comment by 600900** [comment]
Unfortunately, I can't attach screenshots, but in all cases it writes the following:

PeerTube
Incompatible browser

We are sorry but it seems that PeerTube is not compatible with your web browser.

Please try with the latest version of Mozilla Firefox.

If you think this is a mistake, please report it.

**Comment by Chocobozzz** [comment]
Hello,

Unfortunately we don't have enough resources to support this outdated web browser versions.
