### ISSUE TITLE
Email messages: the number of links in html and plain text does not match

### ISSUE THREAD

**Issue by quicktrick** [Chocobozzz/PeerTube#4909]
Here is what [Rspamd](https://rspamd.com/) reports (note the first symbol URI_COUNT_ODD):

![image](https://user-images.githubusercontent.com/18548503/162688728-2f8b8b4d-abdd-4bf9-bea3-5ca6e0a589f8.png)

The problem is with the sender's email address in the body of the email. The HTML part has one link and the plain text has two links.

HTML:

```
<p style=3D"-ms-text-size-adjust: =
100%; -webkit-text-size-adjust: 100%;">You can contact them at <a =
href=3D"mailto:myuser@mydomain.tld" style=3D"-ms-text-size-adjust: 100%; =
-webkit-text-size-adjust: 100%; text-decoration: none; color: =
#f2690d;">myuser@mydomain.tld</a>, or simply reply to this email to get in =
touch.</p>
```

Plain text:

```
You can contact them at =
myuser@mydomain.tld [myuser@mydomain.tld], or simply reply
to this email to get in touch.
```

In plain text, the two email addresses are treated as separate links.  Only one email address `myuser@mydomain.tld` would be enough.

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/3c7ddd7daa61d35c6fd0a992389a92599a246779
