### ISSUE TITLE
User notification when a video is commented

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#491]
* **PeerTube version or URL:** 1.0.0.beta-3
* **NodeJS version:** 9.8.0

* **What is the expected behaviour?**
The author who published the video should receive a notification when one of his videos is commented. By mail or on the web UI when connected.

* **What do you see instead?**
I don't receive email when on of my video is commented.
I don't know if it's not implemented yet or if it's a bad instance configuration (MTA/SMTP).

**Comment by gegeweb** [comment]
OK, thanks.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/1513
