### ISSUE TITLE
RSS stopped working kinda randomly

### ISSUE THREAD

**Issue by Zykino** [Chocobozzz/PeerTube#4912]
**Describe the current behavior**
My channel’s (and account’s)  RSS feed are broken. 
https://videos.pair2jeux.tube/feeds/videos.xml?accountId=1913
https://videos.pair2jeux.tube/feeds/videos.xml?videoChannelId=4783

I have an error 500 : Internal Server Error.
![image](https://user-images.githubusercontent.com/3809938/162843010-e33ba2cb-440d-45c1-b4ab-e46d20d7e73f.png)

Sometimes we get this error instead of a yellow screen:
```json
{
  "type": "https://docs.joinpeertube.org/api-rest-reference.html#section/Errors/TypeError",
  "detail": "Cannot read property 'replace' of null",
  "status": 500,
  "code": "TypeError",
  "error": "Cannot read property 'replace' of null"
}
```

**Steps to reproduce:**
Not sure, see additionnal infos.

**Describe the expected behavior**
Give me a RSS.

**Additional information**
I uploaded videos with Prismedia, a new serie on a new playlist but existing channel. I recently added `{<game name> by Zykino}` so maybe the `{}` are breaking the RSS renderer?
I also found out that federation still works see this screenshot from my mastodon account can still see the new video.
![image](https://user-images.githubusercontent.com/3809938/162846127-a97ead10-6a4d-42b6-adcc-4e5c09171081.png)

**EDIT:** Almost forgot to mention: all the instance’s RSS is not broken, we can see another account’s RSS just fine: https://videos.pair2jeux.tube/feeds/videos.xml?accountId=3
Or even another channel for my account: https://videos.pair2jeux.tube/feeds/videos.xml?videoChannelId=832

The first video that did break my bot watching RSS was this one: https://videos.pair2jeux.tube/w/eYVFCnv82c6ok6cFjMisw5

* PeerTube instance:
  * URL: https://videos.pair2jeux.tube
  * version: 4.1.1
  * NodeJS version: ?
  * Ffmpeg version: ?

* Browser name, version and platforms on which you could reproduce the bug: Firefox 99.0
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): Lot

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/feed/commit/9f97d3095e6a527c840a3f504b315393aa2ff945 and https://github.com/Chocobozzz/PeerTube/commit/322ef8bb9c5c31aea77f23baded9b7518e1c3ddb
