### ISSUE TITLE
Search improvement

### ISSUE THREAD

**Issue by Mastercuber** [Chocobozzz/PeerTube#4913]
**Describe the problem to be solved**
When I want to search something I need to click in the search field and can then start typing.

**Describe the solution you would like:**
It would be convenient to have the [`autofocus`](https://www.w3schools.com/TAGS/att_input_autofocus.asp) attribute on the search field to start typing when the page is loaded.

**Comment by Booteille** [comment]
Hi.

Aren't keyboard shortcuts enough?
By typing `/` or `s` you can go directly to the search input.

**Comment by Mastercuber** [comment]
It's perfectly fine like it is. 
Honestly, I wasn't really aware, that it's possible to use `s` to focus the search bar, though I'm sure I clicked on the shortcuts link at least once.
