### ISSUE TITLE
fail to import from peertube

### ISSUE THREAD

**Issue by bikepunk** [Chocobozzz/PeerTube#4914]
**Describe the current behavior**

Tried to import https://tube.fdn.fr/w/eQSYgM9gEWETcJEEhLuZhb on https://tube.aquilenet.fr

**Steps to reproduce:**

1. Click publish > import with URL
2. Paste URL from a peertube video
3. Says : "Congratulations, the video behind https://tube.fdn.fr/w/eQSYgM9gEWETcJEEhLuZhb will be imported! You can already add information about this video."
4. most of the fields are filled :-)
5. When you click "upate" button at the end of the page, it says "Sorry, but something went wrong
Video not found "

In https://tube.aquilenet.fr/my-library/video-imports I have some interesting stuff: 

ffprobe exited with code 1
ffprobe version 4.3.3-0+deb11u1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55f4adbbda00] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55f4adbbda00] moov atom not found
/var/www/peertube/storage/tmp/41f6798f52ec52b09afca1126c02f2282ad9fdf5a4014cde520ae6bdf8f9f162-import.mp4: Invalid data found when processing input

**Describe the expected behavior**

import from another instance would be sweet

**Additional information**

worked with torrent import as a workaround

* PeerTube instance:
  * URL: https://tube.aquilenet.fr/
  * version: 4.1.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox 91.8.0esr (64-bit)
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

Could you ask more server logs from your instance administrator please?
