### ISSUE TITLE
Add a subhead/subtitle to videos

### ISSUE THREAD

**Issue by maksutheam** [Chocobozzz/PeerTube#4915]
**Describe the problem to be solved:**
For years, people who upload videos to Peer- and YouTube have had two tools to tell a viewer what a video is about without them having to view it; the title and the thumbnail. But sometimes these tools are not enough. 

I will be using YouTube in my examples, but they should apply to current Peertube as well.
Now, look at these video-suggestions:

![kuva](https://user-images.githubusercontent.com/60304828/163037060-d958d5ec-cf8f-4040-a820-70f5f12bb6d4.png)

(I don't have the source for this at hand, it was in a tweet or something, but I will try to find it soon!) Originally, the text you see in the thumbnails were the titles of the videos. While they are nice titles for videos, the author, [Dan Olson](https://twitter.com/FoldableHuman), felt that they didn't describe the content of the videos enough, thus potential viewers didn't know what the videos were about withot clicking them. They couldn't add more text to the title, as it made it too long to be contained in a suggestion, so they moved the original titles to the thumbnail and made new, more descriptive titles. While this _kinda_ helps, I think there should be a better solution for this than putting text into the thumbnail.

**Describe the solution you would like:**
I propose we add something that journalists have had for years; subheads AKA subtitles. A smaller text field below the video title that is not the first thing the viewer sees, but can fit more text in it compared to the title.
Here's a rough mockup of what it could look like;

![coolidea](https://user-images.githubusercontent.com/60304828/163063109-46b0101d-6ff6-421c-aced-e96aa39ae96a.png)
([Link to the video](https://video.mycrowd.ca/w/krhYojqJe9gDzwXqeDwrZB), I made the subtitle from text found on the description of the video)

This would make the video suggestion a bit taller, since it has more text in it, but it could help tell a potential viewer what a video is about in more detail, thus help them decide if a video is worth watching faster.

**Describe alternatives you have considered:**  
I searched the issues and found #3321, that suggest increasing the length limit of the title or adding a subtitle. I don't think increasing the length of the title will help, however. The title is supposed to be short and sweet, so a viewer can identify if a video interests them at all at a glance.

**Comment by Chocobozzz** [comment]
Hi @maksutheam 

Thanks for the issue, but we prefer to keep page listing videos simple for the moment. However I agree it seems an interesting solution, and so you could try to develop a plugin that inject data using `filter:api.videos.list.result` server hook. This data could be filled by users by registering a video field: https://docs.joinpeertube.org/contribute-plugins?id=add-custom-fields-to-video-form

If you need more hooks, or specific placeholder don't hesitate to create issues :)
