### ISSUE TITLE
Error on feature/video-stats branch

### ISSUE THREAD

**Issue by smilekison** [Chocobozzz/PeerTube#4917]
I pulled the branch and installed in my local environment, I can see the analytics for video.
Use case scenario: 
When i upload 15sec video, after i finished watching it just 1 time. The video view is count it as 3 views. And when i watch video in that respective stat page, It is counting 2 or more views at a time. Sometimes, it is showing the views as 1 and the graph is showing 5 viewers:

![Screenshot from 2022-04-13 12-28-05](https://user-images.githubusercontent.com/24309222/163116066-0b711471-c51f-4891-9e2d-c9940b61a232.png)

**Comment by Chocobozzz** [comment]
Hello,

Don't hesitate to comment the PR instead of creating an issue :)

When using the dev mode, views expire very quickly (5 seconds) so the views counter may be incremented many times. Can be the same behaviour for the viewers counter. Please try to reproduce in production mode.

**Comment by smilekison** [comment]
Hi, 
Thank you for your reply. 
Actually we are going working on PeerTube Analytics plugin. Soon, we will be releasing our analytics plugin soon for PeerTube. So, it was a good reference for us to optimize.
