### ISSUE TITLE
Capability for fully public upload without pushing video to federation.

### ISSUE THREAD

**Issue by BrotherIAmPinnedHere** [Chocobozzz/PeerTube#4918]
**Describe the problem to be solved**
I have recently come into the problem of some content, while not being NSFW, pushing the boundaries of some of my followers. I've had the uploaders put the videos to 'internal', but it comes with the issue that only people with accounts on my instance can view them, not casual viewers of the site. This pretty much means they'll be left unviewed.

**Describe the solution you would like:**
If it is possible to implement, I would like to suggest a new upload category, somewhere inbetween the function of internal and public, where it can be watched by guests directly on your instance, but is not seen on the instances of your followers.

**Comment by Chocobozzz** [comment]
Hi,

If [federate_unlisted](https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L277) is set to `false` then you can use the `Unlisted` privacy setting.
