### ISSUE TITLE
Likes given from Mastodon to PeerTube are gradually disappearing

### ISSUE THREAD

**Issue by FediVideos** [Chocobozzz/PeerTube#4919]
**Describe the current behavior**

Likes given to videos from some Mastodon instances are disappearing after a short while

**Steps to reproduce:**

1. Log into a Mastodon account
2. Go to the video https://diode.zone/w/5c0c7585-88e5-4291-8d7b-b87ad9e3c293
3. Like it from Mastodon, and make a note of the number of likes within PeerTube
4. Check back a few days later, look at the number again

**Describe the expected behavior**

The number of likes shown on PeerTube should reflect the number of likes given in Mastodon

**Additional information**

I've been noticing this behaviour over the last few weeks, and thought I was imagining it. So I picked a particular video and kept an eye on it.

I have liked https://diode.zone/w/5c0c7585-88e5-4291-8d7b-b87ad9e3c293 from accounts on mastodon.online, mstdn.social and mas.to. At the time I made the likes, the number on the video said 3.

Now, a few days later, when looking at the video itself in PeerTube the likes have gone down to 1.

When I search for the video within Mastodon, all the likes are still visible, but they don't seem to be counted by PeerTube any more?

I can make the likes go back up to three by unliking the video within Mastodon, then liking it again, but give it a few days and the number goes back to 1 again. It's like something within PeerTube keeps resetting the federated likes?

* PeerTube instance:
  * URL: https://diode.zone/w/5c0c7585-88e5-4291-8d7b-b87ad9e3c293
  * version: 4.1.1
  * NodeJS version: ?
  * Ffmpeg version: ?

The Mastodon instances are running 3.5.1

**Comment by Chocobozzz** [comment]
Hi,

This is due to https://github.com/mastodon/mastodon/issues/13571

I added a workaround in PeerTube https://github.com/Chocobozzz/PeerTube/commit/69d48ee30c9d47cddf0c3c047dc99a99dcb6e894

**Comment by FediVideos** [comment]
The likes still seem to be disappearing, will the workaround take effect when PT instances update to a new version?

**Comment by FediVideos** [comment]
Sorry to ask again, but likes still seem to be disappearing? Is this bug still present?
