### ISSUE TITLE
Incompatible browser

### ISSUE THREAD

**Issue by raymonddurk** [Chocobozzz/PeerTube#4920]
I received this notification on standard Google Chrome for desktop. I played a few videos and the audio and video both come in perfectly fine without delays or quality issues so this may be a false positive.

**Comment by Chocobozzz** [comment]
Hello,

Please fill the [bug template](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/00-bug-issue.md) so we can understand what happened
