### ISSUE TITLE
Unexpected } during playlist delete.

### ISSUE THREAD

**Issue by smilekison** [Chocobozzz/PeerTube#4921]
Hi there, 
When i delete a playlist, I am getting this extra } in the success message.
![Screenshot from 2022-04-15 15-53-02](https://user-images.githubusercontent.com/24309222/163558625-83727e76-e6d6-4b6b-b101-3dc838846f1f.png)

**Comment by smilekison** [comment]
I found that there is an extra } in the my-video-playlists.component.ts file. @Chocobozzz, Can you help on this.

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/ef3de8de216d63f3ac8166c5699be9a9c37f152b
