### ISSUE TITLE
FreeBSD: how to rotate `/var/log/peertube/peertube.log`?

### ISSUE THREAD

**Issue by quicktrick** [Chocobozzz/PeerTube#4922]
Is it possible to rotate the log `/var/log/peertube/peertube.log` with `newsyslog`?  Or should I install `logrotate` and use the `copytruncate` option?

**Comment by freelancePerfexCrmDeveloper** [comment]
Contact Me for installation or setup on vps
https://wa.me/+919782533298
skype : ersonusaini

**Comment by Chocobozzz** [comment]
Hello,

PeerTube logs should be automatically rotated: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L167

I don't know `newsyslog` or `copytruncate` so I can't help on these subjects.

**Comment by quicktrick** [comment]
> PeerTube logs should be automatically rotated

@Chocobozzz, you mean the logs in `/var/www/peertube/storage/logs`. But in FreeBSD there is one more log: `/var/log/peertube/peertube.log`, which is not rotated.

I installed `logrotate` and used its `copytruncate` option. The log is rotated properly now.
