### ISSUE TITLE
The button for sending a message to administrators has disappeared

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#4923]
In the nightly build 4.1.1-nightly-2022-04-16 the button for Contacting administrators has disappeared
Link to the test server https://video.ustim.ru/about/instance

![Скриншот 16 04 22_08 32 40](https://user-images.githubusercontent.com/11453567/163663035-cadcbbee-badc-42fb-82c7-05127f364154.png)

**Comment by freelancePerfexCrmDeveloper** [comment]
Contact Me for installation or setup on vps 
https://wa.me/+919782533298
skype : ersonusaini

**Comment by Alterak** [comment]
I made a mistake. The test server simply does not have this option enabled.
