### ISSUE TITLE
peertube.service: Failed with result 'exit-code'.

### ISSUE THREAD

**Issue by piiskop** [Chocobozzz/PeerTube#4925]
**Describe the problem**
I followed the [installation instructions](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md). _nginx_ tells me that the gateway is bad. Nothing's running at the port _9000_.
**Provide the exact sequence of commands / steps that you executed before running into the problem**
`$ sudo journalctl -feu peertube`

That shows a lot of data like this:

> apr   16 13:28:07 test.tennis24.ee peertube[2654429]: [peertube.tennis24.ee:443] 2022-04-16 13:28:07.088 info: Begin migrations.
apr   16 13:28:07 test.tennis24.ee peertube[2654429]: [peertube.tennis24.ee:443] 2022-04-16 13:28:07.093 info: Executing 0005-email-pod.js migration script.
apr   16 13:28:07 test.tennis24.ee peertube[2654429]: [peertube.tennis24.ee:443] 2022-04-16 13:28:07.105 error: Cannot execute migration 0005. {
apr   16 13:28:07 test.tennis24.ee peertube[2654429]:   "err": {
apr   16 13:28:07 test.tennis24.ee peertube[2654429]:     "stack": "Error\n    at Query.run (/projektid/peertube/versions/peertube-v4.1.1/node_modules/sequelize/dist/lib/dialects/postgres/query.js:50:25)\n    at /projektid/peertube/versions/peertube-v4.1.1/node_modules/sequelize/dist/lib/sequelize.js:313:28\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async PostgresQueryInterface.addColumn (/projektid/peertube/versions/peertube-v4.1.1/node_modules/sequelize/dist/lib/dialects/abstract/query-interface.js:173:12)",
apr   16 13:28:07 test.tennis24.ee peertube[2654429]:     "message": "relation \"public.Pods\" does not exist",
apr   16 13:28:07 test.tennis24.ee peertube[2654429]:     "name": "SequelizeDatabaseError",
apr   16 13:28:07 test.tennis24.ee peertube[2654429]:     "parent": {
apr   16 13:28:07 test.tennis24.ee peertube[2654429]:       "stack": "error: relation \"public.Pods\" does not exist\n    at Parser.parseErrorMessage (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:526:28)\n    at Socket.emit (node:domain:475:12)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
apr   16 13:28:07 test.tennis24.ee peertube[2654429]:       "message": "relation \"public.Pods\" does not exist",
apr   16 13:28:07 test.tennis24.ee peertube[2654429]:       "length": 102,
apr   16 13:28:07 test.tennis24.ee peertube[2654429]:       "name": "error",
apr   16 13:28:07 test.tennis24.ee peertube[2654429]:       "severity": "ERROR",
apr   16 13:28:07 test.tennis24.ee peertube[2654429]:       "code": "42P01",
apr   16 13:28:07 test.tennis24.ee peertube[2654429]:       "file": "namespace.c",
apr   16 13:28:07 test.tennis24.ee peertube[2654429]:       "line": "415",
apr   16 13:28:07 test.tennis24.ee peertube[2654429]:       "routine": "RangeVarGetRelidExtended",
apr   16 13:28:07 test.tennis24.ee peertube[2654429]:       "sql": "ALTER TABLE \"public\".\"Pods\" ADD COLUMN \"email\" VARCHAR(400) NOT NULL DEFAULT '';"
apr   16 13:28:07 test.tennis24.ee peertube[2654429]:     },
apr   16 13:28:07 test.tennis24.ee peertube[2654429]:     "sql": "ALTER TABLE \"public\".\"Pods\" ADD COLUMN \"email\" VARCHAR(400) NOT NULL DEFAULT '';",
apr   16 13:28:07 test.tennis24.ee peertube[2654429]:     "parameters": {}
apr   16 13:28:07 test.tennis24.ee peertube[2654429]:   }
apr   16 13:28:07 test.tennis24.ee peertube[2654429]: }
apr   16 13:28:07 test.tennis24.ee systemd[1]: peertube.service: Main process exited, code=exited, status=255/EXCEPTION
apr   16 13:28:07 test.tennis24.ee systemd[1]: peertube.service: Failed with result 'exit-code'.
apr   16 13:28:07 test.tennis24.ee systemd[1]: peertube.service: Scheduled restart job, restart counter is at 218.
apr   16 13:28:07 test.tennis24.ee systemd[1]: Stopped PeerTube daemon.
apr   16 13:28:07 test.tennis24.ee systemd[1]: Started PeerTube daemon.

**Additional information**

* PeerTube instance:
  * version: i don't know how to find it, i used the latest one
  * NodeJS version:v16.14.2
  * Ffmpeg version:4.2.4-1ubuntu0.1
  * Redis version:i don't know how to find it
  * PostgreSQL version:12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)

**Comment by Chocobozzz** [comment]
Hello,

There might be an initialization issue. Remove your `peertube_prod` database using `dropdb` command, and recreate it (https://docs.joinpeertube.org/install-any-os?id=card_file_box-database).

Then run peertube and paste the log output

**Comment by piiskop** [comment]
`$ tail -f peertube.log `

> {"level":"error","message":"Cannot execute migration 0005.","label":"peertube.tennis24.ee:443","err":{"stack":"Error\n    at Query.run (/projektid/peertube/versions/peertube-v4.1.1/node_modules/sequelize/dist/lib/dialects/postgres/query.js:50:25)\n    at /projektid/peertube/versions/peertube-v4.1.1/node_modules/sequelize/dist/lib/sequelize.js:313:28\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async PostgresQueryInterface.addColumn (/projektid/peertube/versions/peertube-v4.1.1/node_modules/sequelize/dist/lib/dialects/abstract/query-interface.js:173:12)","message":"relation \"public.Pods\" does not exist","name":"SequelizeDatabaseError","parent":{"stack":"error: relation \"public.Pods\" does not exist\n    at Parser.parseErrorMessage (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:526:28)\n    at Socket.emit (node:domain:475:12)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","message":"relation \"public.Pods\" does not exist","length":102,"name":"error","severity":"ERROR","code":"42P01","file":"namespace.c","line":"415","routine":"RangeVarGetRelidExtended","sql":"ALTER TABLE \"public\".\"Pods\" ADD COLUMN \"email\" VARCHAR(400) NOT NULL DEFAULT '';"},"sql":"ALTER TABLE \"public\".\"Pods\" ADD COLUMN \"email\" VARCHAR(400) NOT NULL DEFAULT '';","parameters":{}},"timestamp":"2022-04-16T16:24:21.411Z"}
> {"message":"Begin migrations.","level":"info","label":"peertube.tennis24.ee:443","timestamp":"2022-04-16T16:24:25.453Z"}
> {"level":"info","message":"Executing 0005-email-pod.js migration script.","label":"peertube.tennis24.ee:443","timestamp":"2022-04-16T16:24:25.459Z"}
> {"level":"error","message":"Cannot execute migration 0005.","label":"peertube.tennis24.ee:443","err":{"stack":"Error\n    at Query.run (/projektid/peertube/versions/peertube-v4.1.1/node_modules/sequelize/dist/lib/dialects/postgres/query.js:50:25)\n    at /projektid/peertube/versions/peertube-v4.1.1/node_modules/sequelize/dist/lib/sequelize.js:313:28\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async PostgresQueryInterface.addColumn (/projektid/peertube/versions/peertube-v4.1.1/node_modules/sequelize/dist/lib/dialects/abstract/query-interface.js:173:12)","message":"relation \"public.Pods\" does not exist","name":"SequelizeDatabaseError","parent":{"stack":"error: relation \"public.Pods\" does not exist\n    at Parser.parseErrorMessage (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:526:28)\n    at Socket.emit (node:domain:475:12)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","message":"relation \"public.Pods\" does not exist","length":102,"name":"error","severity":"ERROR","code":"42P01","file":"namespace.c","line":"415","routine":"RangeVarGetRelidExtended","sql":"ALTER TABLE \"public\".\"Pods\" ADD COLUMN \"email\" VARCHAR(400) NOT NULL DEFAULT '';"},"sql":"ALTER TABLE \"public\".\"Pods\" ADD COLUMN \"email\" VARCHAR(400) NOT NULL DEFAULT '';","parameters":{}},"timestamp":"2022-04-16T16:24:25.476Z"}
> {"message":"Begin migrations.","level":"info","label":"peertube.tennis24.ee:443","timestamp":"2022-04-16T16:24:29.656Z"}
> {"level":"info","message":"Executing 0005-email-pod.js migration script.","label":"peertube.tennis24.ee:443","timestamp":"2022-04-16T16:24:29.662Z"}
> {"level":"error","message":"Cannot execute migration 0005.","label":"peertube.tennis24.ee:443","err":{"stack":"Error\n    at Query.run (/projektid/peertube/versions/peertube-v4.1.1/node_modules/sequelize/dist/lib/dialects/postgres/query.js:50:25)\n    at /projektid/peertube/versions/peertube-v4.1.1/node_modules/sequelize/dist/lib/sequelize.js:313:28\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async PostgresQueryInterface.addColumn (/projektid/peertube/versions/peertube-v4.1.1/node_modules/sequelize/dist/lib/dialects/abstract/query-interface.js:173:12)","message":"relation \"public.Pods\" does not exist","name":"SequelizeDatabaseError","parent":{"stack":"error: relation \"public.Pods\" does not exist\n    at Parser.parseErrorMessage (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:526:28)\n    at Socket.emit (node:domain:475:12)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","message":"relation \"public.Pods\" does not exist","length":102,"name":"error","severity":"ERROR","code":"42P01","file":"namespace.c","line":"415","routine":"RangeVarGetRelidExtended","sql":"ALTER TABLE \"public\".\"Pods\" ADD COLUMN \"email\" VARCHAR(400) NOT NULL DEFAULT '';"},"sql":"ALTER TABLE \"public\".\"Pods\" ADD COLUMN \"email\" VARCHAR(400) NOT NULL DEFAULT '';","parameters":{}},"timestamp":"2022-04-16T16:24:29.674Z"}
> {"message":"Begin migrations.","level":"info","label":"peertube.tennis24.ee:443","timestamp":"2022-04-16T16:24:33.635Z"}
> {"level":"info","message":"Executing 0005-email-pod.js migration script.","label":"peertube.tennis24.ee:443","timestamp":"2022-04-16T16:24:33.641Z"}
> {"level":"error","message":"Cannot execute migration 0005.","label":"peertube.tennis24.ee:443","err":{"stack":"Error\n    at Query.run (/projektid/peertube/versions/peertube-v4.1.1/node_modules/sequelize/dist/lib/dialects/postgres/query.js:50:25)\n    at /projektid/peertube/versions/peertube-v4.1.1/node_modules/sequelize/dist/lib/sequelize.js:313:28\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async PostgresQueryInterface.addColumn (/projektid/peertube/versions/peertube-v4.1.1/node_modules/sequelize/dist/lib/dialects/abstract/query-interface.js:173:12)","message":"relation \"public.Pods\" does not exist","name":"SequelizeDatabaseError","parent":{"stack":"error: relation \"public.Pods\" does not exist\n    at Parser.parseErrorMessage (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:526:28)\n    at Socket.emit (node:domain:475:12)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","message":"relation \"public.Pods\" does not exist","length":102,"name":"error","severity":"ERROR","code":"42P01","file":"namespace.c","line":"415","routine":"RangeVarGetRelidExtended","sql":"ALTER TABLE \"public\".\"Pods\" ADD COLUMN \"email\" VARCHAR(400) NOT NULL DEFAULT '';"},"sql":"ALTER TABLE \"public\".\"Pods\" ADD COLUMN \"email\" VARCHAR(400) NOT NULL DEFAULT '';","parameters":{}},"timestamp":"2022-04-16T16:24:33.652Z"}
> 
>

**Comment by Chocobozzz** [comment]
Please send entire `peertube.log` (my email is in my github profile)

**Comment by piiskop** [comment]
[peertube14.log](https://github.com/Chocobozzz/PeerTube/files/8519214/peertube14.log)

**Comment by Chocobozzz** [comment]
I'm sorry but this log does not correspond to a peertube startup on a fresh database. Have you correctly dropped & recreated the database? You may want to remove `Restart=always` from systemd to only keep first startup logs

**Comment by Chocobozzz** [comment]
Can you display your `production.yaml` (`database` section only) and your systemd service content?

**Comment by piiskop** [comment]
> database:
  hostname: 'localhost'
  port: 5432
  ssl: false
  suffix: '_prod'
  username: 'peertube'
  password: 'peertube 2022'
  pool:
    max: 5

> [Unit]
Description=PeerTube daemon
After=network.target postgresql.service redis-server.service

[Service]
Type=simple
Environment=NODE_ENV=production
Environment=NODE_CONFIG_DIR=/projektid/peertube/config
User=peertube
Group=peertube
ExecStart=/usr/bin/node dist/server
WorkingDirectory=/projektid/peertube/peertube-latest
SyslogIdentifier=peertube
;Restart=always

; Some security directives.
; Mount /usr, /boot, and /etc as read-only for processes invoked by this service.
ProtectSystem=full
; Sets up a new /dev mount for the process and only adds API pseudo devices
; like /dev/null, /dev/zero or /dev/random but not physical devices. Disabled
; by default because it may not work on devices like the Raspberry Pi.
PrivateDevices=false
; Ensures that the service process and all its children can never gain new
; privileges through execve().
NoNewPrivileges=true
; This makes /home, /root, and /run/user inaccessible and empty for processes invoked
; by this unit. Make sure that you do not depend on data inside these folders.
ProtectHome=true
; Drops the sys admin capability from the daemon.
CapabilityBoundingSet=~CAP_SYS_ADMIN

[Install]
WantedBy=multi-user.target

**Comment by Chocobozzz** [comment]
Then please run

```
sudo systemctl stop peertube
sudo -u postgres dropdb peertube_prod
sudo -u postgres createdb -O peertube -E UTF8 -T template0 peertube_prod
sudo -u postgres psql -c "CREATE EXTENSION pg_trgm;" peertube_prod
sudo -u postgres psql -c "CREATE EXTENSION unaccent;" peertube_prod
cd /projektid/peertube/peertube-latest
NODE_ENV=production NODE_CONFIG_DIR=/projektid/peertube/config /usr/bin/node dist/server 
```

And paste the output

**Comment by piiskop** [comment]
```
kalmer@test:~$ sudo systemctl stop peertube
kalmer@test:~$ sudo -u postgres dropdb peertube_prod
kalmer@test:~$ sudo -u postgres createdb -O peertube -E UTF8 -T template0 peertube_prod
kalmer@test:~$ sudo -u postgres psql -c "CREATE EXTENSION pg_trgm;" peertube_prod

```

> CREATE EXTENSION


kalmer@test:~$ sudo -u postgres psql -c "CREATE EXTENSION unaccent;# peertube_prod
> ^C
`kalmer@test:~$ sudo -u postgres psql -c "CREATE EXTENSION unaccent;" peertube_prod
`

> CREATE EXTENSION


```
kalmer@test:~$ cd /projektid/peertube/peertube-latest
kalmer@test:/projektid/peertube/peertube-latest$ NODE_ENV=production NODE_CONFIG_DIR=/projektid/peertube/config /usr/bin/node dist/server

```

> /projektid/peertube/versions/peertube-v4.1.1/node_modules/config/lib/config.js:821
>       throw new Error('Config file ' + fullFilename + ' cannot be read. Error code is: '+e2.code
>       ^
> 
> Error: Config file /projektid/peertube/config/runtime.json cannot be read. Error code is: EACCES. Error message is: EACCES: permission denied, open '/projektid/peertube/config/runtime.json'
>     at Config.util.parseFile (/projektid/peertube/versions/peertube-v4.1.1/node_modules/config/lib/config.js:821:13)
>     at Config.util.loadFileConfigs (/projektid/peertube/versions/peertube-v4.1.1/node_modules/config/lib/config.js:697:26)
>     at new Config (/projektid/peertube/versions/peertube-v4.1.1/node_modules/config/lib/config.js:116:27)
>     at Object.<anonymous> (/projektid/peertube/versions/peertube-v4.1.1/node_modules/config/lib/config.js:1492:31)
>     at Module._compile (node:internal/modules/cjs/loader:1105:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
> k

**Comment by Chocobozzz** [comment]
Sorry, it should be `sudo -u peertube NODE_ENV=production NODE_CONFIG_DIR=/projektid/peertube/config /usr/bin/node dist/server `

But what is `/projektid/peertube/config/runtime.json ` file?

**Comment by piiskop** [comment]
sudo -u peertube `NODE_ENV=production` NODE_CONFIG_DIR=/projektid/peertube/config /usr/bin/node dist/server

> [sudo] password for kalmer: 
> [peertube.tennis24.ee:443] 2022-05-04 12:12:54.602 info: Database peertube_prod is ready.
> [peertube.tennis24.ee:443] 2022-05-04 12:12:54.727 error: Cannot install application. {
>   "err": {
>     "stack": "Error: EACCES: permission denied, mkdir '/var/www/peertube'",
>     "message": "EACCES: permission denied, mkdir '/var/www/peertube'",
>     "errno": -13,
>     "code": "EACCES",
>     "syscall": "mkdir",
>     "path": "/var/www/peertube"
>   }
> }
> 

The mentioned _runtime.json_ doesn't exist.

**Comment by Chocobozzz** [comment]
It seems you have permission issues. Ensure `/var/www/peertube` is correctly owned by `peertube` user. See https://docs.joinpeertube.org/install-any-os?id=construction_worker-peertube-user for more information.

**Comment by piiskop** [comment]
i had set _/projektid/peertube_ as the home folder for the user _peertube_ and made that change into _production.yaml_ as well. i had forgotten a row to change where still _/var/www/peertube_ existed. Now, after changing that row as well:

sudo -u peertube `NODE_ENV=production` NODE_CONFIG_DIR=/projektid/peertube/config /usr/bin/node dist/server

> [sudo] password for kalmer: 
> node:internal/modules/cjs/loader:936
>   throw err;
>   ^
> 
> Error: Cannot find module '/projektid/peertube/dist/server'
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
>     at node:internal/main/run_main_module:17:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
>

**Comment by Chocobozzz** [comment]
Run the command in `/projektid/peertube/peertube-latest`

**Comment by piiskop** [comment]
kalmer@test:/projektid/peertube/peertube-latest$ sudo `-u` peertube NODE_ENV=production 

> NODE_CONFIG_DIR=/projektid/peertube/config /usr/bin/node dist/server
> [peertube.tennis24.ee:443] 2022-05-04 17:26:13.957 info: Begin migrations.
> [peertube.tennis24.ee:443] 2022-05-04 17:26:13.961 info: Executing 0005-email-pod.js migration script.
> [peertube.tennis24.ee:443] 2022-05-04 17:26:14.008 error: Cannot execute migration 0005. {
>   "err": {
>     "stack": "Error\n    at Query.run (/projektid/peertube/versions/peertube-v4.1.1/node_modules/sequelize/dist/lib/dialects/postgres/query.js:50:25)\n    at /projektid/peertube/versions/peertube-v4.1.1/node_modules/sequelize/dist/lib/sequelize.js:313:28\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async PostgresQueryInterface.addColumn (/projektid/peertube/versions/peertube-v4.1.1/node_modules/sequelize/dist/lib/dialects/abstract/query-interface.js:173:12)",
>     "message": "relation \"public.Pods\" does not exist",
>     "name": "SequelizeDatabaseError",
>     "parent": {
>       "stack": "error: relation \"public.Pods\" does not exist\n    at Parser.parseErrorMessage (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/projektid/peertube/versions/peertube-v4.1.1/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:527:28)\n    at Socket.emit (node:domain:475:12)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
>       "message": "relation \"public.Pods\" does not exist",
>       "length": 102,
>       "name": "error",
>       "severity": "ERROR",
>       "code": "42P01",
>       "file": "namespace.c",
>       "line": "415",
>       "routine": "RangeVarGetRelidExtended",
>       "sql": "ALTER TABLE \"public\".\"Pods\" ADD COLUMN \"email\" VARCHAR(400) NOT NULL DEFAULT '';"
>     },
>     "sql": "ALTER TABLE \"public\".\"Pods\" ADD COLUMN \"email\" VARCHAR(400) NOT NULL DEFAULT '';",
>     "parameters": {}
>   }
> }
>

**Comment by Chocobozzz** [comment]
:thinking: :thinking: 

Could you try https://github.com/Chocobozzz/PeerTube/issues/1736#issuecomment-477531955?

**Comment by piiskop** [comment]
What exactly should i try? They say that changing postresql connection to _md5_ could fix something however no instructions what and where to change.

**Comment by nebocamin** [comment]
hi, i have that too. 
`"sql": "ALTER TABLE \"public\".\"Pods\" ADD COLUMN \"email\" VARCHAR(400) NOT NULL DEFAULT '\'''\'';"`
and i am experiencing that using the current stable yunohost on debian buster.

**Comment by Chocobozzz** [comment]
I'm sorry but it seems to be a connection issue with PostgreSQL, and not a PeerTube issue by itself.
