### ISSUE TITLE
Remove .m2v extension from targets

### ISSUE THREAD

**Issue by raazkarkee405** [Chocobozzz/PeerTube#4927]
**PeerTube version:** v4.1.1
**Node version:** v14.19.1
**FFmpeg version:** 4.2.4

**Problem:** Unable to upload .m2v file on PeerTube
**Replicate:** Upload any file with extension .m2v file
**Error message:** Upload file unreadable

![image](https://user-images.githubusercontent.com/26194365/163926834-fe302259-4d9d-4f53-8d7f-3f2f554dd966.png)
![image](https://user-images.githubusercontent.com/26194365/163927213-8fcfa4a6-c90e-48ac-a7f8-b169030994db.png)

**Reason:** As seen on the issue: [#4905](https://github.com/Chocobozzz/PeerTube/issues/4905), It is clear that currently PeerTube is not supporting the .m2v file for upload. Further discussion of this with the FFmpeg community on [link](https://trac.ffmpeg.org/ticket/9726#comment:2
) it seems that the FFmpeg package is unable to guess the file duration of the .m2v file format. Due to this issue, PeerTube is facing problems during file upload. Also, it looks like the FFmpeg community is not inclined to solve this issue in the near future and marked the issue as closed with won't fix status.

**Solution:** In conclusion, I would like the PeerTube community to remove the .m2v extension from PeerTube for now. 
![2022-04-18_14-19](https://user-images.githubusercontent.com/26194365/163781426-1ffaee20-c20d-47d8-acb1-b8f9058c78b2.png)
The further discussion can be seen on the following links:
 https://framacolibri.org/t/m2v-video-file-unreadable-error/14582
 https://trac.ffmpeg.org/ticket/9726#comment:2

**Comment by Chocobozzz** [comment]
Hi,

You should be able to upload m2v files with https://github.com/Chocobozzz/PeerTube/commit/f692fc8d6f186c0535599c5c2321d896e41bdb98
