### ISSUE TITLE
Transcoding failed of the video files .aac / .ac3 uploaded from API  and UI

### ISSUE THREAD

**Issue by raazkarkee405** [Chocobozzz/PeerTube#4928]
**Current behavior**

The files with extension .aac / .ac3 were uploaded from the API and UI successfully but the transcoding of the uploaded files failed even if the audio-only option is enabled in VOD transcoding.

![image](https://user-images.githubusercontent.com/26194365/164373072-a81a2e01-5c43-4519-82e2-3d50b9a2bc25.png)

**Steps to reproduce:**
For API upload 
1. Run the following script to upload the files as provided in the documentation:
```
## DEPENDENCIES: jq
USERNAME="root"
PASSWORD="peertube"
FILE_PATH="/home/xxx/Downloads/Music/ac3/sample1.ac3"
CHANNEL_ID="24"
NAME="ac3"
CATEGORY_ID="1"
DESCRIPTION="This is the sample video for testing ac3 format uploaded using API"
PRIVACY_ID="1"
API="https://example.com/api/v1"

## AUTH
client_id=$(curl -s "$API/oauth-clients/local" | jq -r ".client_id")
client_secret=$(curl -s "$API/oauth-clients/local" | jq -r ".client_secret")
token=$(curl -s "$API/users/token" \
  --data client_id="$client_id" \
  --data client_secret="$client_secret" \
  --data grant_type=password \
  --data username="root" \
  --data password="peertube" \
  | jq -r ".access_token")

## VIDEO UPLOAD
curl -s "$API/videos/upload" \
  -H "Authorization: Bearer $token" \
  --max-time 600 \
  --form videofile=@"$FILE_PATH" \
  --form channelId=$CHANNEL_ID \
  --form name="$NAME" \
  --form category=$CATEGORY_ID \
  --form description="$DESCRIPTION" \
  --form privacy=$PRIVACY_ID \
```
2. Check the uploaded video and job status on your PeerTube.

For UI upload 
1. Upload any aac / ac3 file enabling transcoding
2. check the uploaded file and job status on your PeerTube.

**Expected behavior**

The files should be transcoded and able to play.

**Additional information**
Result of the file uploaded from API:
![image](https://user-images.githubusercontent.com/26194365/164226758-913a107b-68f7-4cb0-be70-c3fa23d8349a.png)
Sample file:
https://filesamples.com/samples/audio/aac/sample3.aac
https://filesamples.com/samples/audio/ac3/sample2.ac3

* PeerTube instance:
  * URL: Private
  * version: 4.1.1
 * NodeJs version: 14.19.1
 * Ffmpeg version: 4.2.4

**Comment by Chocobozzz** [comment]
Please fill the [bug template](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/00-bug-issue.md)

**Comment by raazkarkee405** [comment]
> Please fill the [bug template](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/00-bug-issue.md)
hello @Chocobozzz,
I have update issue with bug template.

**Comment by Chocobozzz** [comment]
Please paste server logs after transcoding failed
You may also find the error log in `Administration -> System -> Jobs` to find what happened
