### ISSUE TITLE
Websocket communication is failing

### ISSUE THREAD

**Issue by raazkarkee405** [Chocobozzz/PeerTube#4929]
**Current behavior**
Approach 1: At first I played some videos on my PeerTube, Most of the videos were playing normally without any issues with WebSocket.
Approach 2: After that, I played the other two videos from my PeerTube, the video loaded slowly and started to show the WebSocket error in the console. (* However, the video played successfully)

Problem: After approach 2, the videos that were played during approach 1 started to show the WebSocket errors.

Approach 3: The other thing is that when I disable the `Help share videos` option none of the above mention issues occurs.

![image](https://user-images.githubusercontent.com/26194365/164229353-f6086b2d-6aff-4ef2-9080-ec8ddc555279.png)

**Steps to reproduce:**

I don't know how to reproduce this issue.

**Expected behavior**

The socket connection should respond with a `101` status code.
![image](https://user-images.githubusercontent.com/26194365/164230390-1679fee9-9938-4c80-a8cf-40fe374262da.png)

**Additional information**
`WebSocket connection to 'wss://example.com/tracker/socket' failed:`

* PeerTube instance:
  * URL: Private
  * version: 4.1.1
  * NodeJS version: 14.19.1
  * Ffmpeg version: 4.2.2

* Browser name: Chrome
* Version: 100.0.4896.127
* Platform: Linux
*  browser console log 
![image](https://user-images.githubusercontent.com/26194365/164229739-4292ad5c-4be2-41b3-ba63-9bc0ddb29ea3.png)
![image](https://user-images.githubusercontent.com/26194365/164229752-3575740d-2209-4c17-a88b-3e251f39e4a5.png)

**Comment by Chocobozzz** [comment]
Hello,

Please fill the [bug template](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/00-bug-issue.md)

**Comment by raazkarkee405** [comment]
> Hello,
> 
> Please fill the [bug template](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/00-bug-issue.md)

hello @Chocobozzz,
I have update issue with bug template.

**Comment by Chocobozzz** [comment]
I would need your instance URL to debug this issue. You can send it to me by email (in my github profile)

**Comment by jahanson** [comment]
I'm having this same issue, what was the resolution you guys came to?

**Comment by ROBERT-MCDOWELL** [comment]
same here, I get time to time tracker/socket failed and couldn't fix it until now.

**Comment by Kinuseka** [comment]
The issue isnt resolved. What was the conclusion?

**Comment by Chocobozzz** [comment]
@Kinuseka Create a specific issue for your problem it will be easier to debug

**Comment by ROBERT-MCDOWELL** [comment]
@Chocobozzz 
a web console debug here
which file does it need for a server debug about this issue?
[server.log](https://github.com/Chocobozzz/PeerTube/files/11245051/server.log)

**Comment by ROBERT-MCDOWELL** [comment]
any news about this issue?
with peertube 5.2.0 I still see on the debug console
WebSocket connection to 'wss://secure.icn.press/tracker/socket' failed: 

what this tracker is done for? where to set it and how?

**Comment by PYU224** [comment]
I am also facing that problem now.
Connection with WebSocket fails.
