### ISSUE TITLE
Non-owner users cannot watch Live

### ISSUE THREAD

**Issue by noellabo** [Chocobozzz/PeerTube#4931]
**Describe the current behavior**

Live is no longer visible to anyone other than the account that posted the Live. 

**Steps to reproduce:**

1. Click Live or type in the URL to open it
2. I get a 403 error in my browser

**Describe the expected behavior**

Anyone can view the public Live. 

**Additional information**

* PeerTube instance:
  * URL: https://fedimovie.com
  * version: develop / https://github.com/Chocobozzz/PeerTube/commit/4b7a20d88b11b2935aca0605c43b34bba745b40c
  * NodeJS version: 14.19.1
  * Ffmpeg version: n4.4.1

Verify since https://github.com/Chocobozzz/PeerTube/commit/f443a74649174b2f9347c158e30f8ac7aa3e958a.

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue @noellabo 
It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/961cbe4269e5f34639e29310fb3d90a6cb1bd6bc
