### ISSUE TITLE
New config file variables cause breakage

### ISSUE THREAD

**Issue by stevenroose** [Chocobozzz/PeerTube#4937]
This is really unacceptable in principle. It's my third time updating my PeerTube instance and every time, I have to re-deploy a dozen times because of new config variables that are added. Last time I complained about the config file system, I got "fill in the template file" as a response, but is it really a requirement for using PeerTube to re-fill the template file on every update? Just to make sure there is nothing missing?

Regardless of opinion of implementation, if a missing config value breaks the software, they should be considered breaking semver changes and they should be listed under the important notices of the changelog. That should probably be the first thing to improve.

**Comment by Chocobozzz** [comment]
Hello,

How do you upgarde peertube? Do you use https://docs.joinpeertube.org/install-any-os?id=auto?
