### ISSUE TITLE
Position of "Join remote"-Box in mobile device is bad

### ISSUE THREAD

**Issue by xundeenergie** [Chocobozzz/PeerTube#4938]
When i want to join a video in mobile-device browser i get this

![grafik](https://user-images.githubusercontent.com/5894829/165260560-318f2e12-f36e-4a20-9af5-604b6aa02f92.png)

Can not scroll to left, so the box is not fully visible.

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/dd29842306142a11a5f551a17b9a856d76e467e4
