### ISSUE TITLE
Anyway to allow longer cache when watching a video?

### ISSUE THREAD

**Issue by pullopen** [Chocobozzz/PeerTube#4940]
My internet goes very slow these days, so when I watch a video, normally I will wait a moment until it's cached in my browser. But with Peertube I found that it stops downloading after a few seconds, and when I play on, it will soon reach the furthest point and then I'll have to pause again and wait until it downloads again. 

Is there a way for me to configure my site and allow it to cache longer when pausing or watching?

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but unfortunately it's not possible to control buffer size of official PeerTube player.

**Comment by pullopen** [comment]
> Hello,
> 
> I'm sorry_ but _unfortunately it's not possible to control buffer size of official PeerTube player.

Is there any way to configure it as a site-administator?

**Comment by Chocobozzz** [comment]
> Is there any way to configure it as a site-administator?

Maybe using a plugin but I'm not 100% sure
