### ISSUE TITLE
Click on 'About' page link in left-hand sidebar does not display the 'About' page... instead, nothing happens

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#4942]
**Describe the current behavior**

Clicking on the About link on https://dalek.zone does not display the Peertube About page. Instead, the current page remains on display.

**Steps to reproduce:**

1. Visit https://dalek.zone
2. Click on the About link in the left-hand column.
3. Wait for the About page to display. Nothing happens. The result is the same from any page displayed.

**Describe the expected behavior**

When you click on the About link in the left-hand column, the About page should display with information about the instance.

**Additional information**
When I first encountered this problem during a re-installation on a 'fresh' distribution of Ubuntu 20.04, I tried removing the entire /var/www/peertube directory, deleting the Linux user peertube, deleting the Postresql database and database user, and completely reinstalling Peertube as per the official documentation instructions (no apparent errors during installation). The problem remained the same.

Plugins installed:
 - simplelogo
 - social-sharing
 - background-play

* PeerTube instance:
  * URL: https://dalek.zone
  * Peertube version: 4.1.1
  * NodeJS version: v14.19.1
  * Ffmpeg version: 4.2.4-1ubuntu0.1

* Browser name, version and platforms on which you could reproduce the bug:
  * On Kubuntu 21.10:
  * Firefox  99.0 (64-bit)
  * Chrome 100.0.4896.127 (Official Build) (64-bit)

* Link to browser console log if relevant: N/A?

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): N/A?

**Comment by Chocobozzz** [comment]
Hi,

Categories defined in your configuration are invalid: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L538

They must be a number, so you must not remove the `#` character

**Comment by DalekDave** [comment]
Thank you for your reply. I have restored the categories to the default collection.

But this has not fixed the unavailability of the About page.

Also, a) Could you tell me why the 'categories' settings would affect that? and b) I've not yet managed to successfully define any additional categories, and have been wondering how to do that... That's probably a subject for a separate ticket, anyway.

In any case, for the moment, the problem remains the same, even with just the default catogories...
