### ISSUE TITLE
Port 1935 for live streaming only activates on IPv6 interface (':::1935') not any IPv4 interface

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#4943]
Describe the current behavior

Editing /var/www/peertube/config/production.yaml and setting the host for RTMP to 'localhost' or '127.0.0.1' should cause Peertube to listen on http://localhost:1935 or http://127.0.0.1:1935. But, no matter what setting I use, it only listens on '::::1935'.

Settings in my production.yaml:

....
live:
  enabled: true
....
  rtmp:
    enabled: true
    hostname: 'localhost'
    port: 1935
.....

Steps to reproduce:

Edit /var/www/peertube/config/production.yaml and set the configuration as above. Execute 'sudo netstat -lnpt' and see result:

me@myserver /var/www/peertube # sudo netstat -lnpt | grep 'peertube'
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN      5318/peertube       
tcp6       0      0 :::1935                 :::*                    LISTEN      5318/peertube       

Describe the expected behavior

When you set 'live' to 'enabled: true' and the RMTP hostname to 'localhost', Peertube should listen on 1935 for RMTP traffic.

Additional information

I have IPv6 disabled on the server via the following settings in /etc/sysctl.conf and the exclusion of any IPv6 configuration in /etc/network/interfaces:

net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1

So I'm not sure how port 1935 is even managing to be opened on ':::' ....

Plugins installed:

    simplelogo
    social-sharing
    background-play

    PeerTube instance:
        URL: https://dalek.zone/
        Peertube version: 4.1.1
        NodeJS version: v14.19.1
        Ffmpeg version: 4.2.4-1ubuntu0.1

    Browser name, version and platforms on which you could reproduce the bug:
        On Kubuntu 21.10:
        Firefox 99.0 (64-bit)
        Chrome 100.0.4896.127 (Official Build) (64-bit)

    Link to browser console log if relevant: N/A?

    Link to server log if relevant (journalctl or /var/www/peertube/storage/logs/): N/A?

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/cfbe6be516808de4b45ca9d98f912999ef8daaab

@kontrollanten I renamed your `hostname` config value to `public_hostname`

**Comment by DalekDave** [comment]
> Thanks, should be fixed by [cfbe6be](https://github.com/Chocobozzz/PeerTube/commit/cfbe6be516808de4b45ca9d98f912999ef8daaab)
> 
> @kontrollanten I renamed your `hostname` config value to `public_hostname`

Until the next version becomes available, where could I hack and resolve the problem on my instance, please?
