### ISSUE TITLE
How do you define new categories?

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#4945]
How do you define new categories? 

I have the following in my instance's production.yaml:

  categories:
#    - 1  # Music
#    - 2  # Films
#    - 3  # Vehicles
#    - 4  # Art
#    - 5  # Sports
#    - 6  # Travels
#    - 7  # Gaming
#    - 8  # People
#    - 9  # Comedy
#    - 10 # Entertainment
#    - 11 # News & Politics
#    - 12 # How To
#    - 13 # Education
#    - 14 # Activism
#    - 15 # Science & Technology
#    - 16 # Animals
#    - 17 # Kids
#    - 18 # Food

I have read the documentation, but do not understand whether we are supposed to leave both hash signs on each line,  or whether we are supposed to leave just the second one...

Is a correct additional entry supposed to be like this below?

   - 19 # Linux

Also, can I modify the existing categories, or would this have some unintended side effect?

**Comment by Chocobozzz** [comment]
Hello,

In the [configuration](https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L538) you **enable** (and not define) main categories of your peertube instance. These categories are defined by a number, and we added as a comment (everything after the `#`) the meaning of the number. For example, category `14` corresponds to `Activism`.

You can't add custom categories using PeerTube configuration. You need to create a peertube plugin instead: https://docs.joinpeertube.org/contribute-plugins?id=update-video-constants
