### ISSUE TITLE
With dark theme, font color of 'Tags' field in Publish/Update page is black 

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#4946]
**Describe the current behavior**

When you publish a new content item or update an existing content item, the font color in the 'Tags' field is black and, therefore, difficult to read.

**Steps to reproduce:**

1. Visit https://dalek.zone
2. Publish or update a content item.
3. Start typing a tag in the 'Tags' field 

**Describe the expected behavior**

When you type in the 'Tags' field, the font color should be white (or some other light color), so that it is readable.

**Additional information**
N/A.

Plugins installed:
 - simplelogo
 - social-sharing
 - background-play

* PeerTube instance:
  * URL: https://dalek.zone
  * Peertube version: 4.1.1
  * NodeJS version: v14.19.1
  * Ffmpeg version: 4.2.4-1ubuntu0.1

* Browser name, version and platforms on which you could reproduce the bug:
  * On Kubuntu 21.10:
  * Firefox  99.0 (64-bit)
  * Chrome 100.0.4896.127 (Official Build) (64-bit)

* Link to browser console log if relevant: N/A?

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): N/A?

**Comment by Chocobozzz** [comment]
Thanks, that should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1160fd709f3a20120f135f6fcd85eb0892145b6b
