### ISSUE TITLE
Unable to embed Unlisted videos

### ISSUE THREAD

**Issue by smilekison** [Chocobozzz/PeerTube#4947]
**Describe the current behavior**

While sharing the video with setting `unlisted`. I am getting the 403 error. 
![not-public](https://user-images.githubusercontent.com/24309222/165885267-f986ef75-1a60-4d98-be5c-61aa6cbf7aef.png)

**Steps to reproduce:**
1. Upload any video with privacy setting `unlisted`.
2. Open embed service with url: https://example.com/services/oembed?url=https://example.com/w/8WsRJsTtgAAJ2B7fSH2QTA

**Describe the expected behavior**
While sharing the link directly, I am able to play the video on the browser. So, I think i should be able to embed the video and get preview.
![public-setting](https://user-images.githubusercontent.com/24309222/165885250-5b2b1916-a4a6-49f3-8f01-5e42e787b8a4.png)

I found this code on PeerTube. According to this, I think i should be able to get the video preview of the unlisted video file as long as the video UUID is valid.
![Screenshot from 2022-04-28 11-24-52](https://user-images.githubusercontent.com/24309222/165885737-6534f4a3-edfa-4235-adb4-61f4f6a42323.png)

```
* PeerTube instance:
  * version: 4.1.1
  * NodeJS version: v14.19.1
  * Ffmpeg version: 4.2.4-1ubuntu0.1
```

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/b3d9dedcc36a333bae0bafe92eeede1a11796ce7
