### ISSUE TITLE
Upgrade Docker image to node16

### ISSUE THREAD

**Issue by Thulium-Drake** [Chocobozzz/PeerTube#4948]
**Describe the problem to be solved**
Some plugins for Peertube require Node 16+ and python3, such as https://www.npmjs.com/package/peertube-plugin-transcription

**Describe the solution you would like:**
Upgrade the Docker image to use node16 as a base and also add python3 to the image.

The diff I currently have on my checkout which I use to build my own docker image is:

```
diff --git a/support/docker/production/Dockerfile.bullseye b/support/docker/production/Dockerfile.bullseye
index ac97ddc..ce20665 100644
--- a/support/docker/production/Dockerfile.bullseye
+++ b/support/docker/production/Dockerfile.bullseye
@@ -1,8 +1,8 @@
-FROM node:14-bullseye-slim
+FROM node:16-bullseye-slim
 
 # Install dependencies
 RUN apt update \
- && apt install -y --no-install-recommends openssl ffmpeg python ca-certificates gnupg gosu build-essential curl \
+ && apt install -y --no-install-recommends openssl ffmpeg python3 python ca-certificates gnupg gosu build-essential c
  && gosu nobody true \
  && rm /var/lib/apt/lists/* -fR
```
This produces images that work fine with the plugin

**Describe alternatives you have considered**

**Comment by Chocobozzz** [comment]
Hi,

python3 is already used in 4.1.1

I updated the docker image in https://github.com/Chocobozzz/PeerTube/commit/b0f3c7df138cb1a5547be9104e06abda5d3ff7fe to use node 16

**Comment by Thulium-Drake** [comment]
@Chocobozzz Thanks for picking it up so quickly!

Does this change already reflect in future builds that end up on Dockerhub? Or do we need to wait for 4.1.2?

**Comment by Chocobozzz** [comment]
> Or do we need to wait for 4.1.2?

You'll have to wait 4.2 :)
