### ISSUE TITLE
The Error messages for uploading files are not descriptive enough.

### ISSUE THREAD

**Issue by Ambraven** [Chocobozzz/PeerTube#495]
* **PeerTube version or URL:** v1.0.0-beta1 https://tube.darfweb.eu
* **Browser name/version:** Firefox 

Error messages when a video refuse to upload are not enough descriptive. "Error unknown" does not tell the user if the video was too big, not of the right format, or any other problem that could happen.

Being told what the maximum size and what format are supported on the upload page would also help.

**Comment by Chocobozzz** [comment]
There is an error message if the user tries to upload a file in a wrong format. What is the size of your video you try to upload?

**Comment by Chocobozzz** [comment]
Closing this old issue (we improved the error messages since). Feel free to ask for reopening it.

**Comment by scottrlarson** [comment]
Just a fyi Im having massive problems uploading videos from firefox using various file sizes and encodings. Is there some problem with the video upload tool? Also Im not sure if the error message description changed but I see: error: unknown error about 20% of the time. 
Most of the time I dont get an error at all but get dumped back to the upload screen after 8%. Encoding with mp4(AVC), (XVID).

**Comment by rezonant** [comment]
That's no good. Could you file a new issue for it?

**Comment by Chocobozzz** [comment]
Yes please @scottrlarson fill another issue (with server version etc) so we can investigate :)
