### ISSUE TITLE
Note for debian support

### ISSUE THREAD

**Issue by HumanG33k** [Chocobozzz/PeerTube#4952]
Support debian Todo list for records : 
- support the current inside debian npm/node package
- detect debian and replace yarn by yarnpkg 

 (I know drop v12 and not so much time)

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I don't understand. Please fill the feature request template: https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/30-feature-request.md
