### ISSUE TITLE
[Weblate] Missing a string "Play in loop"

### ISSUE THREAD

**Issue by mastoduy** [Chocobozzz/PeerTube#4955]
In newest release 4.1.1-nightly-2022-05-03, still missing a string "Play in loop" when I right-click to the player.
I searched on Weblate but not found this string.
Hope PeerTube will add soon!

![Missing](https://user-images.githubusercontent.com/104808921/166614216-735f091e-5d8c-4cbf-9e37-0fd37d301584.jpg)

**Comment by Chocobozzz** [comment]
Thanks, it should be available now
