### ISSUE TITLE
"Get help" tooltip be hidden

### ISSUE THREAD

**Issue by mastoduy** [Chocobozzz/PeerTube#4956]
When I clicked on any "Get help" tooltip icon

![1](https://user-images.githubusercontent.com/104808921/166614900-243d7681-470d-4f2f-9405-af466bfcd7b5.png)

_**The popup will be hidden because it is under the dialog.**_ They should be always on top of screen.

![2](https://user-images.githubusercontent.com/104808921/166615045-7367ba2e-4d42-4fd7-b699-96ffe2257713.png)

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/26da644eab9ef62a3e559ac5626bb65a0b13a14d
