### ISSUE TITLE
Ошибка the table "Actor Following->Server" is missing in the FROM clause

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#4958]
**Describe the current behavior**
В разделе Federation->Following если я нажму изменить список, то появляется ошибка the table "Actor Following->Server" is missing in the FROM clause

![Скриншот 04 05 22_10 11 47](https://user-images.githubusercontent.com/11453567/166637256-721818d1-51b3-4b7e-8605-0bc6da7f34eb.png)

**Steps to reproduce:**

1. Go to the **Federation->Following page**
2. Click on Redundancy Allowed

This error is in the release and in the nightly builds.

**Comment by Chocobozzz** [comment]
Thanks, that should be fixed by https://github.com/Chocobozzz/PeerTube/commit/bae616273d455d225d131eb17c56db6c20a0b6b3
