### ISSUE TITLE
Peertube doesnt work on brave/ webtorrent doesnt work

### ISSUE THREAD

**Issue by avenirperma** [Chocobozzz/PeerTube#496]
* **PeerTube version or URL:**peertube mastodon.host
* **Browser name/version:**brave 0.22.13
* **NodeJS version:**

* **What is the expected behaviour?**videos should open
* **What do you see instead?**it starts downloading using brave interface

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

**Comment by Chocobozzz** [comment]
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/218
