### ISSUE TITLE
YAMLException: expected a single document in the stream, but found more

### ISSUE THREAD

**Issue by Lofaq** [Chocobozzz/PeerTube#4962]
Hello, 

I can't run the service peertube in my syslog i have this errors  : 

May  5 16:10:56 HQ-IT-Template-Debian-20210719 peertube[7763]: Error: Cannot parse config file: '/var/www/peertube/config/production.yaml': YAMLException: expected a single document in the stream, but found more
May  5 16:10:56 HQ-IT-Template-Debian-20210719 peertube[7763]:     at Config.util.parseFile (/var/www/peertube/node_modules/config/lib/config.js:844:11)
May  5 16:10:56 HQ-IT-Template-Debian-20210719 peertube[7763]:     at /var/www/peertube/node_modules/config/lib/config.js:644:26
May  5 16:10:56 HQ-IT-Template-Debian-20210719 peertube[7763]:     at Array.forEach (<anonymous>)
May  5 16:10:56 HQ-IT-Template-Debian-20210719 peertube[7763]:     at Config.util.loadFileConfigs (/var/www/peertube/node_modules/config/lib/config.js:643:16)
May  5 16:10:56 HQ-IT-Template-Debian-20210719 peertube[7763]:     at new Config (/var/www/peertube/node_modules/config/lib/config.js:116:27)
May  5 16:10:56 HQ-IT-Template-Debian-20210719 peertube[7763]:     at Object.<anonymous> (/var/www/peertube/node_modules/config/lib/config.js:1492:31)
May  5 16:10:56 HQ-IT-Template-Debian-20210719 peertube[7763]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
May  5 16:10:56 HQ-IT-Template-Debian-20210719 peertube[7763]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
May  5 16:10:56 HQ-IT-Template-Debian-20210719 peertube[7763]:     at Module.load (internal/modules/cjs/loader.js:653:32)
May  5 16:10:56 HQ-IT-Template-Debian-20210719 peertube[7763]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
May  5 16:10:56 HQ-IT-Template-Debian-20210719 systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
May  5 16:10:56 HQ-IT-Template-Debian-20210719 systemd[1]: peertube.service: Failed with result 'exit-code'.
May  5 16:10:56 HQ-IT-Template-Debian-20210719 systemd[1]: peertube.service: Service RestartSec=100ms expired, scheduling restart.
May  5 16:10:56 HQ-IT-Template-Debian-20210719 systemd[1]: peertube.service: Scheduled restart job, restart counter is at 5.
May  5 16:10:56 HQ-IT-Template-Debian-20210719 systemd[1]: peertube.service: Start request repeated too quickly.
May  5 16:10:56 HQ-IT-Template-Debian-20210719 systemd[1]: peertube.service: Failed with result 'exit-code'.
May  5 16:10:56 HQ-IT-Template-Debian-20210719 systemd[1]: peertube.service: Start request repeated too quickly.
May  5 16:10:56 HQ-IT-Template-Debian-20210719 systemd[1]: peertube.service: Failed with result 'exit-code'.

Could-you help me plz ? 
Thx :)

**Comment by Chocobozzz** [comment]
Hi,

Please paste systemd service content
