### ISSUE TITLE
Redirect to previousUrl after login with External Auth

### ISSUE THREAD

**Issue by mspasiano** [Chocobozzz/PeerTube#4964]
I changed the official plugin for OIDC authentication, 
the problem is that if I request a private video after login the redirection is not done, I found a solution but `document.referrer` is everything blank, as you can see here:

https://github.com/mspasiano/peertube-plugin-oidc-cnr/blob/8954d26a0c0a479a289487f4cbd57693155b671c/client/login-client-plugin.js#L11

Or what do you think about this: https://github.com/mspasiano/PeerTube/commit/208a51b9877d0d6b7776610120180602b29b0702

Also I try to register Action `action:router.navigation-end` but it does not work

**Comment by Chocobozzz** [comment]
Hi,

https://github.com/Chocobozzz/PeerTube/commit/cb28bb92daf1a0e123bc0144030c2bc65b865f4a should resolve your use case :)
