### ISSUE TITLE
Some tool tips transformed strangely and hard to read

### ISSUE THREAD

**Issue by mastoduy** [Chocobozzz/PeerTube#4966]
In newest release 4.1.1-nightly-2022-05-06, not all but some tool tips transformed strangely and hard to read. Before realease, those tool tips were normal in rectangle form.

List of those tool tips be affected

- Markdown
- Video desciption
- Contains sensitive content
- Publish after transcoding
- Support's short text

![Untitled1](https://user-images.githubusercontent.com/104808921/167156755-5c7b3668-f075-40bc-b530-ca23311062ce.png)
![2](https://user-images.githubusercontent.com/104808921/167156774-d8ceeac8-172c-4632-ac92-9f553368f5f2.png)
![3](https://user-images.githubusercontent.com/104808921/167156811-031effbd-6bab-4d8d-8c58-8f6952db1bb3.png)

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/644014cc55fcf61e611f2031b125304da086c039
