### ISSUE TITLE
Some new translations updated for mobile version, but not updated on desktop version

### ISSUE THREAD

**Issue by mastoduy** [Chocobozzz/PeerTube#4967]
In newest release 4.1.1-nightly-2022-05-06, some strings were updated right on mobile version (**updated**), but on desktop version-they still keep the old translation (**not-updated**).

![Untitled1](https://user-images.githubusercontent.com/104808921/167165684-39b0bef6-8eea-4c8a-ab6d-b2db82f6759b.png)
![2](https://user-images.githubusercontent.com/104808921/167165707-7cc9cab5-c663-4df8-917b-143a3e306e0e.png)
![4](https://user-images.githubusercontent.com/104808921/167165720-3b379ee6-4d5c-4c78-9f71-92ee34be61f8.png)

**Comment by Chocobozzz** [comment]
Hello,

Could you retry? I don't have such problem.

**Comment by mastoduy** [comment]
Hello. After clear browser cache and retry, the problem is fixed now.
Thank you!
