### ISSUE TITLE
Extra dot on the email reset password URL

### ISSUE THREAD

**Issue by BoFFire** [Chocobozzz/PeerTube#497]
Hi,
When a user asks for password reset, the URI in the email contains an extra dot at the end.
I deleted the dot and password reset was ok.

Link to the screenshot : https://mstdn.fr/@BoF/99845840384391666
Regards,

**Comment by Chocobozzz** [comment]
Fixed: https://github.com/Chocobozzz/PeerTube/commit/37ddeba57f4c2aa85475fd3ef4498bb2802e1c7c

Thanks for the issue @BoFFire!

**Comment by BoFFire** [comment]
Thank you :)
