### ISSUE TITLE
default-avatar.png is missing in latest (and version 3) release

### ISSUE THREAD

**Issue by M-Stenzel** [Chocobozzz/PeerTube#4970]
My nginx throws this error message

2022/05/07 05:29:33 [error] 15880#15880: *331328 open() "/var/www/peertube/peertube-latest/client/dist/assets/images/default-avatar.png" failed (2: No such file or directory), client: 127.0.0.1, server: tube.xy-space.de, request: "GET /client/assets/images/default-avatar.png HTTP/2.0", host: "tube.xy-space.de"

And indeed this file is missing from version 4.1.1 and older versions.

I found it in version 2.3.0 and put it in the proper place, now the error message went away,

Martin.

**Comment by Chocobozzz** [comment]
Hello,

We don't use `default-avatar.png` anymore in PeerTube. May be a third party client, a plugin a an outdated cached version of PeerTube that does such request.
