### ISSUE TITLE
Incorrect ActivityPub Follower/Following collection type

### ISSUE THREAD

**Issue by gediminasel** [Chocobozzz/PeerTube#4972]
**Describe the current behavior**

The type of Followers collection is `OrderedCollectionPage`:

```
{
 "first": "https://peertube.tv/video-channels/maras_world/followers?page=1",
 "id": "https://peertube.tv/video-channels/maras_world/followers",
 "totalItems": 4,
 "type": "OrderedCollectionPage", // this
 ...
}
```

**Steps to reproduce:**

1. Request followers collection of a user
2. Check the `Type` field of the returned object

**Describe the expected behavior**

The type should be `OrderedCollection` [OrderedCollection in ActivityStreams](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-orderedcollection) (example 19 from [here](https://www.w3.org/TR/activitystreams-core/#collection))

```
{
 "first": "https://peertube.tv/video-channels/maras_world/followers?page=1",
 "id": "https://peertube.tv/video-channels/maras_world/followers",
 "totalItems": 4,
 "type": "OrderedCollection", // this
 ...
}
```

**Additional information**

Probably this line should be changed accordingly:

https://github.com/Chocobozzz/PeerTube/blob/a219c9100b3ce8774d454497d46be87465bf664e/server/lib/activitypub/collection.ts#L21

* PeerTube instance:
  * URL: https://peertube.tv/
  * version: 4.0.0

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/f82ea670d83dd7a02843b5ccc36ab1ce180a8d44
