### ISSUE TITLE
Video not played from defined parameters in embed service

### ISSUE THREAD

**Issue by raazkarkee405** [Chocobozzz/PeerTube#4974]
**Describe the current behavior**
When setting different parameters in the video URL, the video is played without considering the parameter setting in the embed service.
**Steps to reproduce:**

1. Click on the Share button of any public video 
2. Customize the URL adding different parameters. Example: https://example.com/w/o7fL1ZRMqQw5Z5cSxtxXbc?start=1m39s&muted=1
3. Open embed service with URL: https://example.com/services/oembed?url=https://example.com/w/o7fL1ZRMqQw5Z5cSxtxXbc?start=1m39s&muted=1

**Describe the expected behavior**
When opening the link on the browser I am able to play the video as per the parameter but with the embed service, I am not able to play the video as per the parameter.
For example: If the video URL has a parameter set to start=1m39s, the video is played from the same time on the browser but not with the embed service.

**Additional information**
![image](https://user-images.githubusercontent.com/26194365/167384067-4a8a1686-b27c-4f56-8f81-105abae07691.png)

![image](https://user-images.githubusercontent.com/26194365/167385635-1ab8997c-fde6-4635-8c99-58f85527aae2.png)
So, If we see the youtube embed URL it is clearly mentioned the start duration of the video in the HTML section which plays the video from the defined start time.

But if we see the PeerTube embed URL defining the start time and other customization parameters do not get included in the HTML section which is restricting the video to be played from the defined start time and with custom parameters.
![image](https://user-images.githubusercontent.com/26194365/167382965-ee9020f3-a1e5-4bf7-8e16-16bf457b5408.png)

* PeerTube instance:
  * version: 4.1.1
  * NodeJS version: v14.19.1
  * Ffmpeg version: 4.2.4-1ubuntu0.1

**Comment by smilekison** [comment]
@Chocobozzz, Are you trying to resolve this issue?

**Comment by Chocobozzz** [comment]
Hi,

I'm not sure the OEmbed service should mimic the current URL query params. Youtube, for example, doesn't add the timecode query param to oembed.

Can you detail your use case?

**Comment by raazkarkee405** [comment]
Hello, 

Our organization is currently using Mattermost as a messaging channel and PeerTube as solution provider. And the members in organization share videos with specific start times to directly provide solutions which points to that specific time, making it easier and faster for other members to access relevant information.

Isn't this already working?

**Comment by Chocobozzz** [comment]
Thanks!

It should be implemented with https://github.com/Chocobozzz/PeerTube/commit/546265e9aec514d50d083a4847c82e11a387ff5d

For now we only support forwarding `start` and  `playlistPosition` (if playlist) query params.
