### ISSUE TITLE
peertube-import-videos.js not found on docker image

### ISSUE THREAD

**Issue by Lapinator** [Chocobozzz/PeerTube#4975]
image: chocobozzz/peertube:production-bullseye

#node dist/server/tools/peertube-import-videos.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/app/dist/server/tools/peertube-import-videos.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

I failed to install peertube-import-videos.js on the docker
Question: how to install peertube-import-videos.js?

**Comment by Lapinator** [comment]
I failed to install peertube-import-videos.js on the docker. 
Question: how to install peertube-import-videos.js?

**Comment by Chocobozzz** [comment]
Hello,

These tools are not available in Docker. See the installation section in the documentation: https://docs.joinpeertube.org/maintain-tools?id=remote-tools
