### ISSUE TITLE
Rss of rss?

### ISSUE THREAD

**Issue by master255** [Chocobozzz/PeerTube#4978]
@Chocobozzz Perhaps if we have rss of each server, we need to make rss of the servers?
And if possible, then in each rss (rss item) server link to its rss feed. That it would be possible to go immediately and see the content.

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I don't understand. Please fill the [feature request template](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/30-feature-request.md)
