### ISSUE TITLE
Impossible to upload video file containing two points

### ISSUE THREAD

**Issue by Kaor** [Chocobozzz/PeerTube#4979]
I try to upload : "Screencast_11-05-2022_13:01:39.webm" but i have an error
```
Le téléversement a échoué
[object Object]
```
if i rename the file to test.webm, no problem

* PeerTube instance:
  * version: 4.1.1

* Browser name, version and platforms on which you could reproduce the bug: Firefox

**Comment by kukhariev** [comment]
This symbol is [blacklisted by node-uploadx](https://github.com/kukhariev/node-uploadx/blob/eeb9cd025aa8e4f76feb9fc506b25b2927f3a86c/packages/core/src/storages/file.ts#L115).

**Comment by Chocobozzz** [comment]
Thanks @kukhariev 

Fixed in peertube in https://github.com/Chocobozzz/PeerTube/commit/f4120aea7a4b4785cc59b690b9187621c84126af
