### ISSUE TITLE
Basic markdown formatting in comments

### ISSUE THREAD

**Issue by ChameleonScales** [Chocobozzz/PeerTube#498]
Would it be possible to allow some basic text formatting in comments (bold, italic, underlined) ?
I think bold would be especially useful. I don't like writing some words in capitals, making the readers think I'm screaming at them. As you know, Youtube comments are full of capital letters because it doesn't have text formatting. This could be another way to make Peertube more interesting.

**Comment by 1000i100** [comment]
If it's not done before 2019, ping me, i will try to find some time to do it.

**Comment by Chocobozzz** [comment]
Some students are working on this issue. :)

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/1aa7543403f278ad88d64e368e77bcb3efa58dd7
