### ISSUE TITLE
minio object storage video delete problem

### ISSUE THREAD

**Issue by dreami2023** [Chocobozzz/PeerTube#4980]
I am using minio object storage. I am doing the video uploading process without any problems. But I am having a problem when I want to delete an uploaded video. The video is not deleted from the minio. The following error has been recorded in the Peertube log.
Cannot remove hls/65f0bfbe-1749-475f-a7d0-152243df4bb9 prefix in bucket hls: no files >
  "response": {
    "$metadata": {
      "httpStatusCode": 200,
      "attempts": 1,
      "totalRetryDelay": 0
    }
  }
}
 2022-05-11 15:41:02.108 error: Some errors when removing files of video 65f0bfbe-1749-475f-a7d0-152243df4bb9 in befor>
  "err": {
    "stack": "Error: Cannot remove hls/65f0bfbe-1749-475f-a7d0-152243df4bb9 prefix in bucket hls: no files listed.\n    at /var/www/peertube/vers>
    "message": "Cannot remove hls/65f0bfbe-1749-475f-a7d0-152243df4bb9 prefix in bucket hls: no files listed."
  }
}

peertube config
[
object_storage:
  enabled: true

  # Without protocol, will default to HTTPS
  endpoint: 'minio.xxxxx.com'

  region: 'hbxxx'

  credentials:
    # You can also use AWS_ACCESS_KEY_ID env variable
    access_key_id: '                   '
    # You can also use AWS_SECRET_ACCESS_KEY env variable
    secret_access_key: '                     '

  # Maximum amount to upload in one request to object storage
  max_upload_part: 3GB

  streaming_playlists:
    bucket_name: 'hls'

    # Allows setting all buckets to the same value but with a different prefix
    prefix: ''
                # Example: 'streaming-playlists:'

    # Base url for object URL generation, scheme and host will be replaced by this URL
    # Useful when you want to use a CDN/external proxy
    base_url: ''
                # Example: 'https://mirror.example.com'

  # Same settings but for webtorrent videos
  # videos:
  #    bucket_name: 'videos'
  #    prefix: 'videos/'
  #    base_url: ''
]

  * version: 4.1.1
  * NodeJS version: 14.9.2
  * Ffmpeg version: 4.4.1
  * minio version 2022-05-08

**Comment by Chocobozzz** [comment]
Hello,

Could you list files in your bucket?
