### ISSUE TITLE
Better support for vertical format videos on peertube site and embeds

### ISSUE THREAD

**Issue by despens** [Chocobozzz/PeerTube#4981]
**Describe the problem to be solved**

Vertical videos are handled and played fine on a peertube site and when embedded. However, the poster image (the setting displayed before users start the video manually) always assumes a horizontal, landscape format video:

![image](https://user-images.githubusercontent.com/571494/168269607-298917b9-9bce-4d18-8917-73c1085fb6f6.png)
This example from a peertube site shows big letterboxes, but in fact should show pillarboxes.

![Screenshot-20220513130226-830x450](https://user-images.githubusercontent.com/571494/168270345-6baf74fc-dffe-4a93-9940-9e5f67df79ff.png)
The embed code produced by peertube is also not respecting the video format and produces a 16:9 embed <iframe>.

![Screenshot-20220513130729-683x985](https://user-images.githubusercontent.com/571494/168271055-311eae3e-07c9-4e03-abfa-85bdc46ef020.png)
When manually changing the embed code to the right proportions, the letterboxes appear.

In any case, once hitting play the video takes up the available height and plays perfectly.

**Describe the solution you would like:**

* It would be great if the poster image before a video plays would use the available surface respecting the videos format. Especially when vertical format videos are embedded, it looks like the video would be very small with lots of space wasted on letterboxes.
* Ideally, the embed code produced by peertube would respect the video's aspect ratio. Users will have a difficult time fixing this.

---
PS: I sincerely want to apologize for the video I used to illustrate my proposal.

**Comment by candideu** [comment]
I agree! I also have this issue with any non-standard aspect ratio. I just want to get rid of the letterboxes.

**Comment by SnejPro** [comment]
I have a similar issue/idea and posted it here: https://ideas.joinpeertube.org/posts/159/thumbnail-aspect-ratio

**Comment by tigexplorer** [comment]
Fitting the poster image orientation and the embed code to the aspect ratio of vertical videos would be very very nice!
For mobile use, it would be a better user experience.
I hope, someone can help.

**Comment by Chocobozzz** [comment]
Responsive embeds now adapt their size depending on the video aspect ratio: https://github.com/Chocobozzz/PeerTube/commit/91d7a3928f8c023dfb4dd2cc1ae442a8de7320f1

**Comment by tigexplorer** [comment]
Maybe I don't understand this right, but it seems for me, it isn't working with 6.1.

I've uploaded a Video after updating the instance to 6.1 with:

`h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 720x1280 [SAR 1:1 DAR 9:16], 2839 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc`


But the embed code is 16:9 (width="560" height="315") instead of 9:16

**Comment by Chocobozzz** [comment]
In the share modal, have you checked "Responsive embed" in "More customization"?

**Comment by tigexplorer** [comment]
> In the share modal, have you checked "Responsive embed" in "More customization"?

Yea, that's perfect!

But how can I get rid of the horizontal preview image of a vertical video on the PeerTube instance view?
Even if I upload a vertical image manually, it's resized to horizontal.

**Comment by Chocobozzz** [comment]
You can't, PeerTube needs an horizontal thumbnail/preview. But the player should crop the thumbnail in portrait mode so the background of the preview is not displayed
