### ISSUE TITLE
Manually delete some video files

### ISSUE THREAD

**Issue by alejandrocobo** [Chocobozzz/PeerTube#4982]
### Describe the problem to be solved
Hi,

Sometimes, users upload 4k long videos that have 0 views for months and have little to none interest. So in order to save some disk space in this specific case, it would be nice to be able to keep just 1080p and below resolutions.

### Describe the solution you would like
Adding a 'delete' button to each resolutions available into 'Administration' > 'Overview' > 'Videos' would be pretty convenient.

Thanks.

**Comment by SimplyCorbett** [comment]
Might as well not allow 4k then.

You can already do this, no need for a feature request on github. If you're using HLS only you can go into /var/www/peertube/storage/streaming-playlists/hls and manually remove the 4k video.

Find the video ID by opening the "download" button and selecting the resolution you want to delete. Copy (etc 4257174e-e62c-43f8-872e-d20a924ed299-1080-fragmented.mp4)

replace 1080 with the resolution you want to remove.

cd /var/www/peertube/storage/streraming-playlists/4257174e-e62c-43f8-872e-d20a924ed299

rm *1080*

The video player will now automatically play the lower resolution.

If you want to remove 4k from the video player entirely edit *master* and remove the resolution from it.

This does not modify the database. The resolution will not disappear from the download list (it will error out).

**Comment by alejandrocobo** [comment]
_The resolution will not disappear from the download list (it will error out)._

That's the point of the feature request. I want to allow any video resolution and be able to delete the higher resolutions of irrelevant videos that nobody watch in a clean way.

I guess that deleting the HLS files is fine for now, but some kind of option that updates the database would be great.

Thanks.

**Comment by SimplyCorbett** [comment]
> I guess that deleting the HLS files is fine for now, but some kind of option that updates the database would be great.

The error is client-only and doesn't cause any problems on the server end. Remove the download button and the user isn't going to ever know there was a higher resolution.

**Comment by alejandrocobo** [comment]
That is fine as a temporary workaround but "**the error is client-only and doesn't cause any problems on the server end**" is no acceptable as a final solution. If the users of my instance have problems, I have problems. Not to mention the idea of disabling features like videos downloads.

If you guys are overwhelmed with higher priority changes, this change is too hard to apply or you find this proposal useless for the most users, I understand you don't want to invest resources on this specific feature request.

**Comment by alejandrocobo** [comment]
> I'm curious on why that isn't an acceptable solution. Which part of the process are you getting stuck on?

Because your proposal involves changing the user experience either by giving an error in case somebody want to download a non-existent file or by removing a feature (disable file downloads).

For me is important that the user experience is flawless and your solutions doesn't meet that requirement. Nevertheless I take that in case I need it while the proper workaround is applied, so thank you for the suggestion.

**Comment by alejandrocobo** [comment]
I appreciate your effort in giving me a solution, but I don't think is wise to advise random people to manipulate the database that way.  

> I think the problem is you're looking for a quick solution through the GUI.

Maybe I'm wrong but asking for new features is precisely for that: to have new features. If I want a convenient and safe way to delete files, why do you think it's a problem to ask for it?

**Comment by SimplyCorbett** [comment]
I can see we are going in circles. Modifying the database isn't hard or special. Most users won't be trying to selectively remove resolutions from individual videos like you're trying to do which means it requires manual intervention.

I've given you a solution to this.. so what you're really requesting is a GUI addition to peertube. Your OP should be modified to reflect this,

**Comment by tio-trom** [comment]
I suggest an option in the admin backend to only allow certain resolutions. I also want to stop people from uploading 4k videos that in my view make no sense at all. Huge diskspace and no visible quality improvement for most screens out there anyway.

**Comment by alejandrocobo** [comment]
> I suggest an option in the admin backend to only allow certain resolutions. I also want to stop people from uploading 4k videos that in my view make no sense at all. Huge diskspace and no visible quality improvement for most screens out there anyway.

I'd say that's a different feature. What I propose is to allow any resolution and at the same time, being able to delete higher resolutions in videos with no relevance or where (as you said), a 4k resolution is pointless.

**Comment by JohnXLivingston** [comment]
> I suggest an option in the admin backend to only allow certain resolutions. I also want to stop people from uploading 4k videos that in my view make no sense at all. Huge diskspace and no visible quality improvement for most screens out there anyway.

This already exists (when transcoding is enabled).



> I'd say that's a different feature. What I propose is to allow any resolution and at the same time, being able to delete higher resolutions in videos with no relevance or where (as you said), a 4k resolution is pointless.

I agree. In my case, having documentaries or movies in 4K make sense, but when I accidentally captured a concert with my smartphone in 4K... Well...

**Comment by tio-trom** [comment]
Yes I was afraid that this was the case....thanks for the link to the issue.

**Comment by alejandrocobo** [comment]
Meanwhile this feature is implemented, I've thought on a workaround that doesn't need to manipulate the database and I think is safe. Is this one:
1) Delete the undesired higher resolution files (ex. ??-2160.m3u8 and ??-2160-fragmented.mp4).
2) Go to Administration > Overview > Videos.
3) Click on the three dots button of the video we just deleted the undesired resolutions.
4) Click on 'Run HLS/WebTorrent transcoding'.

This should reenconde the entire video taking as the "native resolution" the highest resolution we left in the folder, no?

I know this implies to rerun the transcoding which means a high usage of server's resources and maybe a little loss of video quality. But as a temporary workaround, do you see any problem regarding federation issues, missing files or whatever problem as a result of this operation?

Thanks.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/1bb4c9ab2e8b3b3022351b33a82a5e527fa5d4d7

**Comment by alejandrocobo** [comment]
Thank you very much, @Chocobozzz

**Comment by manicmarvin** [comment]
@SimplyCorbett you are an obnoxious troll.
