### ISSUE TITLE
Addition of a control to turn the video stream ON/OFF

### ISSUE THREAD

**Issue by m3uusi** [Chocobozzz/PeerTube#4986]
Hi,

**Describe the problem to be solved**

I am spending a lot of time watching videos only for the audio (Conferences/Interviews where video does not offer much). Most of the time, they are opened in a tab somewhere in the lowest quality available but still receiving a video stream.
I'd like to reduce the data consumption of this kind of usage but most of the time, those videos are only available in video (no podcast)
And in some conferences, there is a few moment where video is interesting (When graphs or maps are shown) so having only the audio stream would not fit.  

**Describe the solution you would like:**

I was wondering if it would be possible to have an option in the player to shut the video stream to avoid consuming data for something I'm not watching (I don't know if it technically possible to send only the audio stream of a video without having to convert it to an audio file)

The solution I thought about would be to have a control to turn the video stream ON/OFF. I've never seen this type of thing before. I don't know if you want Peertube to offer this kind of service (As it's a video platform and not an audio one)

The presence of such a control should be configured for each instance/maybe for each video.

What do you think ? Am I the only one having this kind on usage of videos ?
Regards,

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue but we can't send video stream only for now. See https://github.com/Chocobozzz/PeerTube/issues/3281 for more information
