### ISSUE TITLE
Allow translation to Toki Pona

### ISSUE THREAD

**Issue by Sobsz** [Chocobozzz/PeerTube#4987]
I'm planning to launch a PeerTube instance dedicated to content in [Toki Pona](https://en.wikipedia.org/wiki/Toki_Pona) (ISO code: `tok`) and would like the ability to translate the interface with a few people from the community.

---

According to the readme:
> If you don't see your locale in the platform you can add it directly in the Weblate interface.

However, I couldn't find an option to do so. Even if I did find it, Weblate doesn't seem to have Toki Pona in its list of languages, which means it might need to be added manually (in which case it should be set to have no plural forms, as in Mandarin Chinese). As such, I'm following the precedent of #4873 and posting it as a GitHub issue.

**Comment by Chocobozzz** [comment]
Hi,

We've added it on weblate :)

**Comment by Chocobozzz** [comment]
@Sobsz Added in https://github.com/Chocobozzz/PeerTube/commit/4c1ce3d44ca6608c58082a14cb3e18d56a4acbfb and https://github.com/Chocobozzz/PeerTube/commit/978489b64c7b329cbfde5ffd7fe806702a3490c7

Will be available on https://peertube2.cpy.re next week

Thanks for your contribution!
