### ISSUE TITLE
Issues with BigBlueButton «Share External Video» feature

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#4988]
**Describe the current behavior**

BigBlueButton (called BBB later on) is a virtual classroom software. 
There is a builtin function: «share an external video».
Using this feature, you just have to paste a link to a video (youtube, web, or even peertube), and you can then play the video synchronously between participants. The video starts at the same time for every viewers, and when the presenter start/stops or move anywhere in the video, everybody sees the same part of the video.

This works perfectly fine with peertube links... but only for participants that were there when the video was shared.
If a participants join the room after, the video will be stuck, with a curious message: «Lire la vidéo pour permettre la synchronisation des médias» (sorry for the french, that's my BBB language).

See this screenshot:
![image](https://user-images.githubusercontent.com/38844060/169244607-1c628bd7-7a33-4a90-97fd-fe6d0cf0fd64.png)

**Steps to reproduce:**

1. Start a BBB conference
2. Share a peertube video
3. Start the video
4. Join the room with another user

**Describe the expected behavior**

Video should start.

**Additional information**

I think this is related to the way browsers deals with autoplay.
When I share a youtube video, the newcomers have to click on a play button to start the video. I think this button is just missing with Peertube (and clicking on the video does not work).

@Chocobozzz , if you need a BBB instance to test, I have one. Please contact me by mail.

* PeerTube instance:
  * URL: tries with several
  * version: 4.1.1

* Browser name, version and platforms on which you could reproduce the bug: Firefox
* Link to browser console log if relevant: no relevant log found

**Comment by Chocobozzz** [comment]
Hello,

`controls` player parameter in PeerTube mimics `controls` attribute of a `video` HTML tag. It means it disables all controls, including the big play button. To reproduce Youtube `controls` behaviour, I added a `controlBar` boolean option in https://github.com/Chocobozzz/PeerTube/commit/60f013e1031871b7e0913c724f0bd2e569721c8e.

I suggest to open an issue on their side to notify about this new option that will be available in PeerTube 4.2 (RC should be released soon).

**Comment by JohnXLivingston** [comment]
Just made it: https://github.com/bigbluebutton/greenlight/issues/3466
I open this issue on the greenlight repo (greenlight is the BBB frontend). I hope this is the good repo for this bug.

Thanks!
