### ISSUE TITLE
CSS duplication with del tag

### ISSUE THREAD

**Issue by raazkarkee405** [Chocobozzz/PeerTube#4989]
**Describe the current behavior**
When we inspect elements the CSS is duplicating with the `del` tag.

**Steps to reproduce:**

1. Open any page of the instance 
2. Right-click and click on inspect
3. Check the styles section

**Describe the expected behavior**
The Styles should not duplicate with the `del` tag.

**Additional information**
![image](https://user-images.githubusercontent.com/26194365/169453251-ba852244-2962-4146-8e89-84370f7204a3.png)

* PeerTube instance:
  * URL: https://peertube2.cpy.re/
  * version: 4.1.1

* Browser name, version and platforms on which you could reproduce the bug: Version 101.0.4951.64 

The bug is seen in other browsers as well.

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I don't understand: what is the `del` tag?

**Comment by raazkarkee405** [comment]
Hello,
Let's just forget about the del tag the styles are duplicating in the following way.
For example: 
The class body is duplicated with multiple same classes including the same properties.
1. ![image](https://user-images.githubusercontent.com/26194365/169477440-8430abd8-5696-4041-9f12-268c748a5205.png)
2. ![image](https://user-images.githubusercontent.com/26194365/169477506-d40ec2ac-c411-49df-9236-10142da2e02b.png)

The images one shows the used CSS and  the image two show the unused CSS but same.
