### ISSUE TITLE
Ability to edit comments

### ISSUE THREAD

**Issue by ChameleonScales** [Chocobozzz/PeerTube#499]
Would it be possible to give users the ability to edit their comments after posting them ?

**Comment by Ealhad** [comment]
I guess we should be able to delete them as well.

And when the comment is part of a thread, it's probably better to just mark it as deleted without completely removing it.

**Comment by ChameleonScales** [comment]
Comment deletion is already available, although they always completely disappear, unlike what you suggest.
Side note : deleting a comment that has replies also deletes the replies. Maybe that's not ideal.

**Comment by Ealhad** [comment]
Oh, right, sorry, I didn't check while logged to an account 😅

[According to the API](https://htmlpreview.github.io/?https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/api/html/index.html#operation--videos--videoId--comments--commentId--post), the route for editing a comment already exists. Is it just not used yet, or not implemented at all?

And while I think about it, an edited comment should have some kind of glyph or text to indicate it has changed (also maybe when it has, if we store/decide to store this information).

**Comment by Chocobozzz** [comment]
The route you linked is to **create** a comment :)

**Comment by Ealhad** [comment]
Oh, my bad, it’s to answer to a given comment — I thought maybe it was to edit a comment, because of the `{comment-id}` thingy.

I guess a new route should use the `PUT` verb?

**Comment by Chocobozzz** [comment]
yep

**Comment by Chocobozzz** [comment]
Closing, because we don't want that users edit what they said. They should delete and recreate the comment instead (like on Mastodon).

See https://github.com/Chocobozzz/PeerTube/issues/507 regarding comment deletion

**Comment by ChameleonScales** [comment]
Ok, then how about a "Delete and redraft", just like on Mastodon?
