### ISSUE TITLE
Uploading a video fails because it tries to use http instead of https.

### ISSUE THREAD

**Issue by lamarios** [Chocobozzz/PeerTube#4990]
**Describe the current behavior**

My setup:

HAProxy (https) -> Traefik (http) -> peertube (http)

When  uploading a video, it tries to upload using http instead of https and then fail because my domain is https:

![Firefox issue](https://cloud.ftpix.com/s/AwAMbj8bRx3N7es/download/Screenshot%20from%202022-05-20%2014-22-47.png)

The rest works without problem, if I import a video using it's url it works fine too.

**Steps to reproduce:**

1. upload a video
2. fail
3.

**Describe the expected behavior**

**Additional information**

* PeerTube instance:
  * URL: https://tube.ftpix.com
  * version: 4.1.1
  * NodeJS version: ? (docker install)
  * Ffmpeg version: ? (docker install)

* Browser name, version and platforms on which you could reproduce the bug: firefox 100.0.1
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): it doesn't reach the server

**Comment by Chocobozzz** [comment]
Hi,

Could you display the request/response headers of `POST /api/v1/videos/upload-resumable`?

**Comment by kukhariev** [comment]
The response contains an incorrect `location` header.
The haproxy config contains  `http-request set-header X-Forwarded-Proto "https"` line?

**Comment by lamarios** [comment]
No, should it ?

**Comment by kukhariev** [comment]
Definitely because `x-forwarded-proto` header is set somewhere to `http`.
Try  add http-request set-header X-Forwarded-Proto "https".

**Comment by lamarios** [comment]
Ok i found the culprit it was traefik. After I added the line to my HAProxy it still didn't work so after a bit of digging, I figured out that it might be my traefik that doesn't forward the header properly because apparently, traefik needs to trust the source of the request to forward the X-Forwarded-for so I had to add the following to my traefik config:

```
--entrypoints.web.forwardedHeaders.trustedIPs=192.168.7.0/16
```

Thank you for leading me in the right direction !
