### ISSUE TITLE
Plugin CSS style Invalid

### ISSUE THREAD

**Issue by MaKunyu** [Chocobozzz/PeerTube#4992]
**Describe the current behavior**
I wrote a Plugin with some styles but peertube is not serving them
**Steps to reproduce:**

1.I follow the documentation: https://docs.joinpeertube.org/contribute-plugins write a plugin and add some styles to 'assets/style.css'
2. Install the plugin and build PeerTube (to have the compiled client files)
3.Start PeerTube localy with 'npm run dev', but the CSS style I added is not displayed on the page
4.I have the same problem as this link : https://github.com/Chocobozzz/PeerTube/issues/3792#issue-818010214，I also tried the method proposed by the author（https://github.com/Chocobozzz/PeerTube/issues/3792#issuecomment-788770072）, but CSS style is still invalid

**Describe the expected behavior**
I want plugin CSS style to be effective, but I don't know how to solve it. Can you answer it for me？Thanks,sorry to trouble you.

**Additional information**

* PeerTube instance:
  * URL:  local dev branch
  * version: 4.1.1
  * NodeJS version: v14.17.0
  * Ffmpeg version:4.2.4

This is not a bug. This is a problem I encountered when writing a plug-in. I need help.

**Comment by Chocobozzz** [comment]
Hi,

Plugins can't inject style in dev server (`localhost:3000`). Try `localhost:9000` instead to test your plugin. I also suggest to follow the guide to test your plugin: https://docs.joinpeertube.org/contribute-plugins?id=test-your-plugintheme

**Comment by MaKunyu** [comment]
收到，谢谢您！

**Comment by MaKunyu** [comment]
I see. Thank you very much
