### ISSUE TITLE
PeerTube v4.2.0-rc.1: wrong number of my videos

### ISSUE THREAD

**Issue by quicktrick** [Chocobozzz/PeerTube#4993]
**Describe the current behavior**

The number of `My videos` on the `/my-library/videos` page is several times the actual number of videos:

![image](https://user-images.githubusercontent.com/18548503/169829146-0cbe86b0-fe93-47c9-b980-88ba6d02d79a.png)

The actual number of videos:

![image](https://user-images.githubusercontent.com/18548503/169829346-c60790b3-4643-4661-8ef8-c3afedba823a.png)

**Steps to reproduce:**

1. After upgrading PeerTube from `v4.1.1` to `v4.2.0-rc.1`, the number of `My videos` became incorrect.

**Additional information**
There are no errors in the log. The upgrade migration script was executed as specified in the [release notes](https://github.com/Chocobozzz/PeerTube/releases/tag/v4.2.0-rc.1)

* PeerTube instance:
  * URL: https://tube.artsale.info/
  * version: v4.2.0-rc.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: 
Chrome Version 101.0.4951.67 (Official Build) (64-bit)

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/a65858746c1d2904bf117e8d91816e752d4b94c4
