### ISSUE TITLE
 Peertube 4.2.0-RC1: upgrade script fails when run on server with 4.1.1 instance

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#4995]
**Describe the current behavior**

**Steps to reproduce:**

1. As root, execute upgrade script: cd /var/www/peertube/peertube-latest && sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production node dist/scripts/migrations/peertube-4.2.js
node:internal/modules/cjs/loader:936

**Describe the expected behavior**
Script should install Peertube 4.2.0 PC1

* PeerTube instance:
  * URL: https://dalek.zone
  * version: Peertube 4.1.1
  * NodeJS version: v16.15.0
  * Ffmpeg version: 4.2.4-1ubuntu0.1

* Browser name, version and platforms on which you could reproduce the bug: N/A, script executed from command line via SSH
* Link to browser console log if relevant: N/A
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

On executing the ugrade installation script, I get the following output on the command line:

root@mail /var/www/peertube/peertube-latest # cd /var/www/peertube/peertube-latest && sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production node dist/scripts/migrations/peertube-4.2.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/var/www/peertube/versions/peertube-v4.1.1/dist/scripts/migrations/peertube-4.2.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by Chocobozzz** [comment]
Hello,

From ` Cannot find module '/var/www/peertube/versions/peertube-v4.1.1/dist/scripts/migrations/peertube-4.2.js'` I can see you did not upgrade peertube to 4.2.0-rc.1

**Comment by DalekDave** [comment]
Hello :) 

In the release notes, it says, "You need to execute manually a migration script (can be executed after your upgrade, while your PeerTube instance is running) to generate smaller avatar miniatures"

So it seems the migration script can be run after the upgrade....?

Also, the release notes don't currently contain a link to where to find that script (I was going to look through the README.md of the new codebase afterwards, but an explicit link to it would be really cool... :)

Once again, thank you for your work on the project! :)

**Comment by DalekDave** [comment]
"From Cannot find module '/var/www/peertube/versions/peertube-v4.1.1/dist/scripts/migrations/peertube-4.2.js' I can see you did not upgrade peertube to 4.2.0-rc.1"

Erm... no.... because I got the error message when attempting to upgrade.... :)

**Comment by DalekDave** [comment]
Hello, sorry, I misread the changelog notes.... I followed the upgrade procedure in the Peertube documentation, and the upgrade did work (sorry for the brain fart).

All good now, thank you! :)
