### ISSUE TITLE
[Peertube 4.2.0-rc1] Account and channel avator disply in list is broken

### ISSUE THREAD

**Issue by FredBezies** [Chocobozzz/PeerTube#4996]
**Describe the current behavior**

When I'm connected, I noticed all avatars are using the default one instead of showing the one I used before.

But they are displayed when I click to get my profile / any channel by itself.

See attached screenshots.

Screenshots:
 
![01 - account avatar](https://user-images.githubusercontent.com/8571419/169987473-e9f18d5b-64f0-4278-9e21-aedc680cb7f7.png)
![02 - missing avatars in list view](https://user-images.githubusercontent.com/8571419/169987483-d0e26ca2-dce2-40d8-9b1a-62b0b9f51402.png)
![03 - a channel with the defined avatar used ](https://user-images.githubusercontent.com/8571419/169987487-b41a1357-9919-48b7-8e73-6f088d9a372d.png)

**Steps to reproduce:**

1. Upgrade to 4.2.0-rc1
2. Look at displayed avatars for both your account and your channels in when all is displayed as a list

**Describe the expected behavior**

Using the avatar previously defined.

**Additional information**

* PeerTube instance:
  * URL: https://peertube.pcservice46.fr/
  * version: 4.2.0-rc1
  * NodeJS version: 14.19.2
  * Ffmpeg version: 4.3.4-0+deb11u1

* Browser name, version and platforms on which you could reproduce the bug: Firefox, 102a1 and Chromium 100, Archlinux
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

I think your instance admins have not run the upgrade script: https://github.com/Chocobozzz/PeerTube/blob/develop/CHANGELOG.md#v420-rc1

**Comment by FredBezies** [comment]
> Hello,
> 
> I think your instance admins have not run the upgrade script: https://github.com/Chocobozzz/PeerTube/blob/develop/CHANGELOG.md#v420-rc1

As far as I know - and I asked the admin - this script was run.

**Comment by Elrondo46** [comment]
After rerun the migration script AFTER restart of service, all is good

**Comment by FredBezies** [comment]
So let's close this bug...
