### ISSUE TITLE
Mobile devices

### ISSUE THREAD

**Issue by Matthias84** [Chocobozzz/PeerTube#5]
A lot of people use current videoplattforms also from mobile devices. I guess PT would need an fallback to become compatible with the low performance of this embedded platforms?

**Comment by Chocobozzz** [comment]
I completely agree. But I can't take position for now because I never tested WebTorrent on Android so I have no visibilty about the compatibily or the performances.

If the prototype is a success, I would love to see a "native" application (with NativeScript or Cordova?) for mobile phones.

**Comment by ldidry** [comment]
Works as a charm on my Nexus 6P (yes, I know, it's not a low performance device).

Only bad thing: while you can browse PeerTube easyly on a mobile device, it's not the best view you can have (videos too small, navbar on the left taking too much place, etc).
