### ISSUE TITLE
The display of avatars in the account notification area is missing

### ISSUE THREAD

**Issue by rnek0** [Chocobozzz/PeerTube#5001]
**Current behavior**  
The display of avatars in the account notification area is missing when clicking on the bell, after update from version 4.1.1

**Steps to reproduce:**  
1. I ran the update script,
2. updated yarn to last version
3. ran the script for the thumbnail migration.

**Expected behavior**  
Icons should be displayed.

*PeerTube instance:
  * URL: http://ptb.lunarviews.net
  * version: v4.2.0-rc.1 (pre-release)  
  * NodeJS version: v14.19.3
  * Ffmpeg version: 4.3.4-0+deb11u1

* Browser name, version and platforms on which you could reproduce the bug:
 1. Firefox 100.0.2 (64 bits)
 2. Chromium Version 101.0.4951.64 (Build officiel) Arch Linux (64 bits)

![2022-05-24_17:16:04](https://user-images.githubusercontent.com/52655832/170073673-5e11f2b0-f2f2-4a53-91eb-464df54dce49.png)

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/a220b84b0e29c7ce1b32166aec07870696a28ef9
