### ISSUE TITLE
Make peertube work with sqlite

### ISSUE THREAD

**Issue by bil-ash** [Chocobozzz/PeerTube#5005]
**Describe the problem to be solved**
Backing up a postgresql database is quite difficult task. In comparison, backing up a sqlite database is quite easy. We can periodically backup the dbname.db file or use https://litestream.io/

**Describe the solution you would like:**
I would like peertube to be able to run using a sqlite database also. Since peertube uses an ORM(sequelize), will changing the db connection string from the pg sql one to that of sqlite be sufficient? Or do we have to make some other changes also?

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but supporting another DBMS is not an option because we're very happy with PostgreSQL, and use some of its specific tools.
