### ISSUE TITLE
Access to XMLHttpRequest Peertube do not allow port change

### ISSUE THREAD

**Issue by vontani** [Chocobozzz/PeerTube#5006]
**Describe the current behavior**
i just cant upload an file to my working instance since i did change ports from 80/443 to something elses ..
its an fresh ubuntu 20.04 instance latest tube installed.
it looks like there is an config some where that do not follow given port 4443, i would like to know if i can coment this hardening function out ?

///##########################################
Access to XMLHttpRequest at 'https://my.domain.com/api/v1/videos/upload-resumable?upload_id=370cabd5-26ccb939-fed014a9-47cbcc17' from origin 'https://my.domain.com:4443' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
///##########################################

**Steps to reproduce:**
change http and https ports and try to upload file

1.
2.
3.

**Describe the expected behavior**

**Additional information**

* PeerTube instance: 
  * URL:
  * version: latest 411
  * NodeJS version: latest 
  * Ffmpeg version: latest

* Browser name, version and platforms on which you could reproduce the bug: chrome (F12)
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by kukhariev** [comment]
@vontani 
https://github.com/Chocobozzz/PeerTube/issues/4951

Can also work:
`proxy_set_header Host $http_host;`  or `proxy_set_header Host $host:$server_port;`

**Comment by vontani** [comment]
dear, (Thank you for ur fast response)
adding server port variable ($server_port; )or http_host indeed works but only for uploading, that make oauth causing an error:

///
Error: Cannot retrieve OAuth Client credentials: undefined.
Ensure you have correctly configured PeerTube (config/ directory), in particular the "webserver" section.
///

**Comment by vontani** [comment]
did edit nginx confing, peertube config, oauth-clients.js ... added in multiple ways proxy headers and no luck here.. if upload works, login dos not, if login works, upload dos not ... somewhere in oauth or on the way to oauth must be an seperate config file, see ?

**Comment by kukhariev** [comment]
Are you sure you set the config.webserver.port to 4443?

**Comment by vontani** [comment]
yes sir ! 

Let me show it as detailed as possible so anyone can follow up destinations, here u go:

**/var/www/peertube/config/production.yaml**

`webserver:
  https: true
  hostname: 'my.domain.com'
  port: 4443`

**/etc/nginx/sites-available/my.domain.com**

`server {
  listen 8080;
  listen [::]:8080;
  server_name [my.domain.com];


  location /.well-known/acme-challenge/ {
    default_type "text/plain";
    root /var/www/certbot;
  }
  location / { return 301 https://$host$request_uri; }
}

upstream backend {
  server 127.0.0.1:9000;
}

server {
  listen 4443 ssl http2;
  listen [::]:4443 ssl http2;
  server_name [my.domain.com];`

**/var/www/peertube/versions/peertube-v4.1.1/dist/server/controllers/api/oauth-clients.js**

`         if (serverPort !== 8080 && serverPort !== 4443) {
            headerHostShouldBe += ':' + serverPort;
        }`

**Comment by kukhariev** [comment]
```if (serverPort !== 8080 && serverPort !== 4443) { headerHostShouldBe += ':' + serverPort; }```    Why? It's wrong.

**Comment by vontani** [comment]
thats the code my dear, i just editet ports, not the code, how ever, i did comment this part totaly out, but this gives no change here to.. ( command line to my right site to reload nginx) ..

**Comment by kukhariev** [comment]
https://github.com/Chocobozzz/PeerTube/blob/9c931cf0bb162aa4733584be96107cdcd922d308/server/lib/uploadx.ts#L5-L8

you can add  ```useRelativeLocation: true,``` to ignore host:port

**Comment by vontani** [comment]
dear,
 i dont have any uploadx.ts file to edit at my instance :/  uploadx.ts

only files i have are   uploadx.js   and   uploadx.d.ts   and they differ

**Comment by kukhariev** [comment]
dist/server/lib/uploadx.js

```js
const uploadx = new core_1.Uploadx({
    directory: (0, upload_1.getResumableUploadPath)(),
    useRelativeLocation: true,
    maxMetadataSize: '10MB',
    userIdentifier: (_, res) => {
        if (!res.locals.oauth)
            return undefined;
        return res.locals.oauth.token.user.id + '';
    }
});
```

**Comment by vontani** [comment]
@kukhariev u did the golden edit dear ! this works with no errors  :)  login and uploads go truth like a charm ! good job! 

For other Peertube users try to figure out what to do after changing ports on Peertube instances, try to:

Add: 
`useRelativeLocation: true` inside uploadx.js betw. line 7 - 8
**Destination**
/var/www/peertube/versions/peertube-v4.1.1/dist/server/lib/uploadx.js


**comment out:**  or copy - past @ Line 18 - 20 
#####################################
         /*if (serverPort !== 8080 && serverPort !== 4443) {
            headerHostShouldBe += ':' + serverPort;
        }*/
#####################################
**Destination**
/var/www/peertube/versions/peertube-v4.1.1/dist/server/controllers/api/oauth-clients.js

**Edit Ports:**
Nginx: 
`/etc/nginx/sites-available/your.domain.com`
or `/etc/nginx/sites-available/peertube`

**PeerTube**
/var/www/peertube/config/production.yaml

Hope that helps any no coders at some way 

Thanks For helping me and other peertube users!

**Comment by Chocobozzz** [comment]
Hello,

We prefer to not use `useRelativeLocation: true` because our dev client uses `:3000` and the dev server uses `:9000` and we prefer to keep the same config between the dev mode and the prod mode. 

@kukhariev I saw you added a workaround regarding the malformed forwarding header. So I think it will be enough to fix these kind of problems :)

**Comment by vontani** [comment]
@Chocobozzz , im for now experimenting with peertube to get an better understanding for the app so i will let this varible on place until an fix will come over and update my posts as soon some news arrives .
thank you guys-n-girls for a top notch app and your time working on it.
