### ISSUE TITLE
REST api limits comments deletion

### ISSUE THREAD

**Issue by nderambure** [Chocobozzz/PeerTube#5009]
Hello.

Was making some cleanup after some federated instances put hundreds of comments in our database, and when trying to delete 50 or more comments (filters by local:false), I get a message saying too many requests.
And indeed, in doc, limit is at 50 requests for 10s :
https://docs.joinpeertube.org/api-rest-reference.html#section/Rate-limits

So trying 50 or 100 deletion is impossible by default.
Maybe this task may ask the deletion in 1 unique request instead of as many requests than comments to delete ?

Anyway, keep the good work ;)

**Comment by smilekison** [comment]
@nderambure, You can make the API request unlimited by setting the values to 0

**Comment by Chocobozzz** [comment]
Hi,

With https://github.com/Chocobozzz/PeerTube/commit/e5a781ec25191c0dbb4a991f25307732d798619d, we now bypass rate limiter for administrators and moderators

**Comment by nderambure** [comment]
Wow, thx @Chocobozzz !
