### ISSUE TITLE
What is a good way to add UMami tracking code to peertube?

### ISSUE THREAD

**Issue by mmance** [Chocobozzz/PeerTube#5010]
I see that Matomo is the analytics of choice for peertube, but I don't have the budget for that.  I have recently stood up a UMami instance and I need to add the <script> to the header.  Instead of pretending I know best where to put it, I thought I should ask here.

**Comment by Chocobozzz** [comment]
Hello,

Unfortunately someone will have to develop a plugin to support UMami, like we did for Matomo

**Comment by LukasSchulz** [comment]
If you are using nginx, you could do a kind of hacky version by using the `ngx_http_sub_module` http://nginx.org/en/docs/http/ngx_http_sub_module.html (Is automatically installed on debian, but maybe has to be enabled on compilatio if you are using another distribution)

You could just add `sub_filter '</head>' '<script>...</script></head>'` to your configuration just under the server_name or where you want tracking enabled. 
Not the most beautiful and maybe also not the most performant option, but it works fine for me.

**Comment by alexandregv** [comment]
Someone now wrote a plugin:
* https://git.inpt.fr/inp-net/peertube-plugin-umami
* https://github.com/inp-net/peertube-plugin-umami

Doesn't support customizing the script name, it uses `/script.js` only.

It currently contains a JS typo, see https://github.com/inp-net/peertube-plugin-umami/issues/1
