### ISSUE TITLE
Videos uploaded to object storage do not load/play, browser console errors

### ISSUE THREAD

**Issue by ChanoSan** [Chocobozzz/PeerTube#5011]
**Describe the current behavior**
Videos uploaded to object storage (self-hosted SeaweedFS using an S3 Gateway) are stored successfully, but will not play in browser. Webtorrent videos result in a 403 error when attempting to play, HLS Streaming videos end in a network/syntax JS error.

**Steps to reproduce:**

1. Have a functioning PeerTube instance
2. Configure it to use remote object storage
3. Upload a video from file
4. Data appears in S3 bucket and appears as normal in PeerTube's interface
5. Atttempt to play the video. Video loads infinitely but never plays. Using "Inspect" in the browser reveals errors when attempting to fetch remote content

**Describe the expected behavior**
PeerTube should be able to fetch and play video content normally.

**Additional information**
The PeerTube instance has functioned normally for some time now. Object storage (as mentioned above) is SeaweedFS configured with an S3 gateway. The gateway itself is behind an nginx reverse proxy which is configured to enable CORS.

The S3 configuration obviously works, because the upload and move-to-object-storage both succeed, and the files are visible in the bucket as well as Local Videos. PeerTube's credentials give it full access (Read,Write,List,Tagging,Admin), so if uploads succeed then it follows that Read access should also be possible.

This has been tested on multiple devices and browsers, including Firefox, Brave and IceCat (in Android). An example object storage uploaded video is provided to illustrate:
https://peertube.anon-kenkai.com/w/7P4h72WgguiLCpWD7CkKYV

* PeerTube instance:
  * URL: https://peertube.anon-kenkai.com
  * version: 4.1.1
  * NodeJS version: v16.13.1
  * Ffmpeg version: 4.2.4-1ubuntu0.1

* Browser name, version and platforms on which you could reproduce the bug: Firefox 100.0.2, Brave 1.38.119
* Link to browser console log if relevant: 
Copy/Pasted from Firefox console, for HLS video. Logs for Webtorrent 403 error can be reproduced on request.
`HLS.js error: networkError - fatal: true - manifestLoadError 855.8071fe71c8c195a9.js:1:3266`

`Cannot get sha256 segments SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data 611.646de916cc923ae4.js:1:144763`
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
No errors appear in PeerTube logs

**Comment by Chocobozzz** [comment]
Hello,

Web browsers fetch directly your S3 bucket, so it needs to be publicly available (which is not since we have a 403).
