### ISSUE TITLE
Peertube 4.2.0-RC1: Trending view, invalid value in the «sort select»

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5012]
**Describe the current behavior**

When opening the page https://videos.john-livingston.fr/videos/trending , the select on the top right shows an invalid value («-best»):
![image](https://user-images.githubusercontent.com/38844060/171233454-9d1a46c7-715a-421a-847a-9ecad66854be.png)

**Steps to reproduce:**

1. Open the trending page

**Describe the expected behavior**

The label should be one of the select option label.

**Additional information**

* PeerTube instance:
  * URL: https://videos.john-livingston.fr/videos/trending 
  * version: 4.2-RC1

* Browser name, version and platforms on which you could reproduce the bug: Firefox

**Comment by Chocobozzz** [comment]
Hi,

We removed `best` sort algorithm in 4.2: we use it automatically if the user is logged in when using `hot` algorithm. I removed config inconsistencies and added a message in changelog in https://github.com/Chocobozzz/PeerTube/commit/010382b6037cff5d0ed16fa8b158691439fac9b7
