### ISSUE TITLE
Displaying a playlist for instance guests

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5013]
**Describe the current behavior**

**Describe the current behavior**
If you create a public playlist and then add an internal video to it, then a black screen will be displayed for guests of this instance, without messages and warnings.

The test server already has such a playlist. Here is the link
https://video.ustim.ru/w/p/9XWDbpVegnSWTAp8tWLvmD

**Steps to reproduce:**

1. Create a public playlist
2. Add a video to this playlist. This video should only be available to internal users of this instance.
3. Copy the link of this playlist
4. Log in to the instance as a guest and open this playlist.

**Describe the expected behavior**
I assume that a warning should be displayed that all videos in this playlist are only available to internal users. You need to register or log in.

![1](https://user-images.githubusercontent.com/11453567/171356540-e4511e40-f98c-404b-b06b-0d3bc7c383bd.png)
![2](https://user-images.githubusercontent.com/11453567/171356564-0d7adb86-7cb3-4375-bd02-70a0114ffbb2.png)
![3](https://user-images.githubusercontent.com/11453567/171356592-8f4e1237-ead4-499a-9630-a0561baad4b4.png)

**Comment by Chocobozzz** [comment]
Thanks, an error message is now displayed with https://github.com/Chocobozzz/PeerTube/commit/5a2f775a212bcb708f1756e3780c764cc232a910
