### ISSUE TITLE
Blank screen at first start

### ISSUE THREAD

**Issue by ALeXTRiXSMSB** [Chocobozzz/PeerTube#5014]
**I have installed peertube according to the installation instructions. Now at the first start i get several 403 error messages in the network analysis and blocked MIME types ("text/html").**

**Installation Instructions**

**peertube logs**

* PeerTube instance:
  * version: v4.1.1
  * NodeJS version: v14.19.3
  * Ffmpeg version: 4.3.4-0+deb11u1
  * Redis version: 6.0.16
  * PostgreSQL version: 13.7
![403error](https://user-images.githubusercontent.com/23039845/171437965-8c12b3b6-5d7a-4ec2-bafa-c6a43e25ab4f.png)
![mimeerror](https://user-images.githubusercontent.com/23039845/171437976-9bba5012-0f80-45d9-b941-b824055ef568.png)

**Comment by Chocobozzz** [comment]
Hello,

It seems to be a webserver (nginx) configuration/right issue and not a peertube bug. Please prefer to use [the forum](https://framacolibri.org/c/peertube) to get help from the community

**Comment by ALeXTRiXSMSB** [comment]
> Thank you very much for the quick reply. 
I looked in the forum and this post helped me.
https://framacolibri.org/t/solved-need-help-with-nginx-conf-for-remote-reverse-proxy/13868/7
