### ISSUE TITLE
File name truncated when downloading video with forward slash

### ISSUE THREAD

**Issue by Mike35538** [Chocobozzz/PeerTube#5015]
**Describe the current behavior**

If you have a video and there is a forward slash in the title then the file name is truncated when you do a direct download.

**Steps to reproduce:**

1. Upload a new video, or rename an existing video and make the title: My Family Vacation on 3/8/22 in Honolulu, Hawaii
2. Click on Download (Direct download)
3. The file name becomes: 22 in Honolulu, Hawaii-720p.mp4

**Describe the expected behavior**

File name should not be truncated and slash characters should be replaced with an underscore (or dash).
For example: My Family Vacation on 3_8_22 in Honolulu, Hawaii-720p.mp4

**Additional information**

* PeerTube instance:
  I've seen this behavior in v4.1.1 and v4.2.0-rc.1

Thanks!

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/62f53731cf807562ba885b180e71bb75b3902443
