### ISSUE TITLE
Contabo Object Storage problem.

### ISSUE THREAD

**Issue by siberkolosis** [Chocobozzz/PeerTube#5018]
**Describe the current behavior**
object storage does not work with contabo,

error[6/5/2022, 3:43:57 PM] Cannot move video https://fgage.com/videos/watch/f13c032d-bdc9-4b06-8bdc-65efdd715cd1 to object storage.

{
  "err": {
    "stack": "Error: getaddrinfo ENOTFOUND fgage.sin1.contabostorage.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)",
    "message": "getaddrinfo ENOTFOUND fgage.sin1.contabostorage.com",
    "errno": -3008,
    "code": "ENOTFOUND",
    "syscall": "getaddrinfo",
    "hostname": "fgage.sin1.contabostorage.com",
    "$metadata": {
      "attempts": 1,
      "totalRetryDelay": 0
    }
  },
  "tags": [
    "move-object-storage",
    "f13c032d-bdc9-4b06-8bdc-65efdd715cd1",
    "https://fgage.com/videos/watch/f13c032d-bdc9-4b06-8bdc-65efdd715cd1"
  ]
}

**Steps to reproduce:**

1.
2.
3.

**Describe the expected behavior**

**Additional information**
contabo doesn't support virtual-hosted-style URLs,
base url should like this https://sin1.contabostorage.com/a808f6dce2514fba8eeb68596724ddd1:fgage
not fgage.sin1.contabostorage.com

below is my config on owncast instance apps and it runs fine.
![image](https://user-images.githubusercontent.com/72482678/172043129-54dad885-9c80-4300-af31-59a6731c2432.png)

owncast config docs https://owncast.online/docs/storage/contabo/
[Contabo Object Storage](https://contabo.com/en/object-storage/) is S3 compatible and a good choice if you have a lot of viewers and a small budget, because there are no data transfer fees. You only have to pay for the storage capacity, starting at $2.49/month for 250 GB. Outbound traffic is routed through Cloudflare CDN.

* PeerTube instance:
  * URL:
  * version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

Contabo seems to require path style requests. Closing in favour of https://github.com/Chocobozzz/PeerTube/issues/4455

**Comment by fenarinarsa** [comment]
> Contabo seems to require path style requests. Closing in favour of #4455


I did succeed to make it work without "force path style" option, but the public Serving endpoint is different from the default endpoint as shown above (owncast allows to have a different endpoint & serving endpoint).

So it may actually be a different issue?

**Comment by Chocobozzz** [comment]
You can serve files from another endpoint using `base_url`: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L191

**Comment by yunkuangao** [comment]
@fenarinarsa Can you tell me how your object storage is configured? I also use contabo object storage, but my data cannot be uploaded.

**Comment by fenarinarsa** [comment]
> You can serve files from another endpoint using `base_url`: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L191

So it means you can actually change the S3 storage for all the already imported videos if you transfer the files yourselves and force the base URL to the new storage?

Because so far I only read that migration of S3 storage wasn't supported.

**Comment by fenarinarsa** [comment]
> 



> @fenarinarsa Can you tell me how your object storage is configured? I also use contabo object storage, but my data cannot be uploaded.

I did this test with Owncast, not Peertube. I didn't migrate to S3 storage on peertube since the documentation states that migration between S3 storages is not supported.

**Comment by Chocobozzz** [comment]
>I did this test with Owncast, not Peertube. I didn't migrate to S3 storage on peertube since the documentation states that migration between S3 storages is not supported.

I'm not sure to understand: can you describe the feature you miss to move to s3 on peertube?

**Comment by fenarinarsa** [comment]
> > I did this test with Owncast, not Peertube. I didn't migrate to S3 storage on peertube since the documentation states that migration between S3 storages is not supported.
> 
> I'm not sure to understand: can you describe the feature you're missing to move to s3 on peertube?

To be able to move all the already imported videos from one S3 storage to another. The documentation says that only the future videos will be imported on the new S3 storage but all the oldest will still be served from the old S3 storage.

Basically it says that if you want to change the S3 service provider and stop paying the former one, you lose all the previously imported videos, if I understand well.

From https://docs.joinpeertube.org/maintain/remote-storage

"PeerTube stores object URLs in the database, so even if you change the object storage configuration it will serve previously uploaded videos using the old object storage endpoint while serving new uploads using the new object storage endpoint.

File URLs migration in PeerTube is not provided yet."

**Comment by Chocobozzz** [comment]
Thanks! I created an issue: https://github.com/Chocobozzz/PeerTube/issues/5654
