### ISSUE TITLE
schema.org URI in `@context` is not correct

### ISSUE THREAD

**Issue by trwnh** [Chocobozzz/PeerTube#5019]
**Steps to reproduce:**

1. Expand or compact a JSON-LD document from Peertube

**Describe the current behavior**

`@context` uses `http://schema.org#` which leads to incorrect namespacing, for example `https://schema.org#Boolean`

**Describe the expected behavior**

`@context` uses `http://schema.org/` which leads to correct namespacing, for example `https://schema.org/Boolean`

**Additional information**

https://github.com/mastodon/mastodon/issues/18361

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/4d526901349b35bfac9811acc45854c65639cee3
