### ISSUE TITLE
copyright year displayed on ui says 2021, instead of 2022. 

### ISSUE THREAD

**Issue by Agorise** [Chocobozzz/PeerTube#5022]
**Describe the current behavior** 
fyi, in the bottom left corner of most peertube instance ui's, the copyright still says 2021. 
can someone please notify the peertube devs about that?

**Steps to reproduce:**

1. load any instance default page 
2. look in bottom left corner 
3. see the copyright year should say 2022, not 2021 

**Describe the expected behavior** 
change the 2021 to 2022 (or automate the year change via code) 

**Additional information**

* PeerTube instance:
  * URL: https://dollarvigilante.tv 
  * version: 4.1.1 
  * NodeJS version: ? 
  * Ffmpeg version: ? 

* Browser name, version and platforms on which you could reproduce the bug: mint, brave browser, latest. 
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue. It will be fixed in 4.2
