### ISSUE TITLE
Default Theme error

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5025]
**Describe the current behavior**
If I install any additional theme, the new theme becomes active by default, even if "Default" is set in the settings.
I tried to install this dark theme and my instance immediately started using this dark theme.
https://framagit.org/framasoft/peertube/official-plugins/tree/master/peertube-theme-dark
This problem was also present in previous versions.

**Steps to reproduce:**

1. Install any instance theme
2. The theme immediately becomes active and there is no way to change to a standard light theme.

**Describe the expected behavior**
If "Default" is set in the settings of the Basic->Theme instance, then the instance should use the standard Peertube theme. But each user must be able to select a different theme in their settings, which are installed on this instance.

* PeerTube instance:
  * URL: https://peervideo.ru
  * version: 4.2.0

**Comment by Chocobozzz** [comment]
Hello,

Dark theme is automatically chosen if your web browser prefers dark themes. However we should improve the label to specify this behaviour

**Comment by Alterak** [comment]
> Hello,
> 
> Dark theme is automatically chosen if your web browser prefers dark themes. However we should improve the label to specify this behaviour

I believe that if a new user visits my instance, then he should have the theme that the server administrator has installed by default. In my case, the default is the standard Peertube theme. But at the same time, any user should be able to redefine the theme and select any available one from the list. The instance administrator should simply download and install the available themes on his instance.
This is how it is used in any CMS... I think it's right.

**Comment by Chocobozzz** [comment]
> But at the same time, any user should be able to redefine the theme and select any available one from the list

This is the point of this feature. Users specify through their web browser their preferred theme (dark/light). So PeerTube automatically applies this choice if dark theme is installed, so the user doesn't have to manually select the dark theme. See the original issue: https://github.com/Chocobozzz/PeerTube/issues/2753

**Comment by Alterak** [comment]
> > But at the same time, any user should be able to redefine the theme and select any available one from the list
> 
> This is the point of this feature. Users specify through their web browser their preferred theme (dark/light). So PeerTube automatically applies this choice if dark theme is installed, so the user doesn't have to manually select the dark theme. See the original issue: #2753

I have a different opinion on this. I hope this feature is only for the official dark theme? Other dark themes won't be selected automatically?

**Comment by Chocobozzz** [comment]
> I hope this feature is only for the official dark theme?

Yes, it's only for the official dark theme
