### ISSUE TITLE
4.2.0 - Docker migration command is wrong

### ISSUE THREAD

**Issue by TheFrenchGhosty** [Chocobozzz/PeerTube#5027]
**Parts of the documentation concerned:**

https://github.com/Chocobozzz/PeerTube/releases/tag/v4.2.0

**Describe the desired information/correction**

```
cd /var/www/peertube-docker && docker-compose exec -u peertube peertube node dist/scripts/migrations/peertube-4.2.js
```

Is wrong.

The correct way to do it is:

```
docker exec -u peertube peertube node dist/scripts/migrations/peertube-4.2.js
```

**Comment by Chocobozzz** [comment]
Hi,

You could at least explain why the documentation command is wrong :)

**Comment by TheFrenchGhosty** [comment]
@Chocobozzz 

`docker-compose exec` doesn't exist

Changing directory before executing a docker command is useless

**Comment by Chocobozzz** [comment]
`docker-compose exec` does exist: https://docs.docker.com/compose/reference/exec/

This command requires `docker-compose.yml` file. `peertube` args is the service name, not the container name.
