### ISSUE TITLE
Documentation: Endpoint for Getting an OAuth Token Is Not Documented

### ISSUE THREAD

**Issue by BrainBlasted** [Chocobozzz/PeerTube#503]
I was testing the API documentation when this came to my attention. After successfully registering an account on peertube.video through the API,  interactions with the account require a token. I am not sure if this bit is implemented yet.

**Comment by Chocobozzz** [comment]
Hi, sorry I forgot to add that part in the documentation :)

Should be fixed: https://github.com/Chocobozzz/PeerTube/commit/94ff4c2335ace54b36b2bca96f63226ee8f575b1
