### ISSUE TITLE
More Admin Tools for Local/Trending Curation

### ISSUE THREAD

**Issue by TomatDividedBy0** [Chocobozzz/PeerTube#5031]
**Describe the problem to be solved**
Presently, PeerTube's sorting treats videos neutrally. This has its benefits but it can also mean that higher-effort content can go overlooked. I administrate an instance (https://watch.breadtube.tv) and often times you'll have Podcast Episode #999 crowd out other forms of content. Someone can make a video essay and put a lot of effort into it, but it will get little engagement because other uploads overshadow it. This in turn, is discouraging for new creators since they like to see engagement when they post. It also means that those visiting the instance aren't necessarily seeing the best content on the front page. On others' instances, sometimes remote content will overshadow local content. 

Ensuring good content gets to the right users is crucial in order to promote engagement and incentivize creators/audiences to keep coming back to an instance. 

**Describe the solution you would like:**
YouTube often makes use of a complex algorithm to promote videos to people. There's a myriad of issues with this as we're all aware, but it has the benefit of connected creators and audiences effectively. I think a good alternative to this is to allow for certain videos/channels to be manually "hoisted" by admins for a specified period of time, where there will be more weight to said video being pushed to the top of the Local/Trending tabs. Maybe even have a "hoist factor" of sorts, which would be a number from 1 to 100 which you could specify in settings to have more fine-grained control in how strongly each video/channel gets promoted/demoted. 

There's a lot of trust already put into instance admins, and the model of the Fediverse is to find a new instance if you're dissatisfied with the current owner, so I don't think giving this control is an issue.

**Comment by Chocobozzz** [comment]
Hello,

I think this use case can be implemented by the admin homepage no?
