### ISSUE TITLE
Docker upgrade Postgres backup/restore

### ISSUE THREAD

**Issue by Cyrille37** [Chocobozzz/PeerTube#5033]
In the Docker guide (/support/doc/docker.md) the "Upgrade" section is missing  about Postgres backup and restore.

I cannot upgrade docker peertube from 3.4.1 `chocobozzz/peertube:production-buster` to 4 `chocobozzz/peertube:production-bullseye` because of Postgres incompatible data files version.

Thanks & cheers :-)

**Comment by Chocobozzz** [comment]
Hi,

It's weird because we have not upgrade postgresql service version in our [docker-compose](https://github.com/Chocobozzz/PeerTube/blame/develop/support/docker/production/docker-compose.yml#L71) between these two versions :thinking:

**Comment by Chocobozzz** [comment]
@Cyrille37 Try to follow https://betterprogramming.pub/how-to-upgrade-your-postgresql-version-using-docker-d1e81dbbbdf9
