### ISSUE TITLE
Constant problem with live videos

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5035]
**Describe the current behavior**

If I turn off transcoding for live videos, then there are no errors.
If I enable transcoding without additional permissions, then an error appears. If I activate at least one permission, the error appears very often. It is not possible to use the broadcast.

At the time of the error, I took a screenshot and a log

![4](https://user-images.githubusercontent.com/11453567/172854188-b29be84b-b29b-4e59-8b80-60352038bd25.png)
![2](https://user-images.githubusercontent.com/11453567/172849942-b8126fab-166b-4c3a-9726-60a302b4af7a.png)

```
error[09.06.2022, 15:31:24] Cannot process segments
{
  "err": {
    "stack": "Error: ENOENT: no such file or directory, open '/data/peervideo/storage/streaming-playlists/hls/a1ea93fc-570a-4bfb-8cd8-adb2ce7fa40b/2-000014.ts'",
    "message": "ENOENT: no such file or directory, open '/data/peervideo/storage/streaming-playlists/hls/a1ea93fc-570a-4bfb-8cd8-adb2ce7fa40b/2-000014.ts'",
    "errno": -2,
    "code": "ENOENT",
    "syscall": "open",
    "path": "/data/peervideo/storage/streaming-playlists/hls/a1ea93fc-570a-4bfb-8cd8-adb2ce7fa40b/2-000014.ts"
  },
  "tags": [
    "live",
    "NI49S4PA",
    "a1ea93fc-570a-4bfb-8cd8-adb2ce7fa40b"
  ]
}
```

Also at this moment you can see the CPU load and the load on the hard disk. There is no heavy load. My local storage is displayed as "sdb"

![3](https://user-images.githubusercontent.com/11453567/172850184-02ed0d02-f778-44ea-956f-e7dab0803a90.png)

I do not know why this happens, but errors began to appear in versions 3+. There were never any errors on older versions of 2.x.x.

I did an experiment. In the first minutes of the live video, everything was fine... at that moment, I uploaded a regular video to my channel and started transcoding in several resolutions (1080, 720 480p). The live video was working well at this point.
I also tried to eliminate the HDD problem. On the test server, I used an SSD (M.2). There is definitely a high bandwidth. But the error also appeared.

**Describe the expected behavior**
Live video should work stably.

* PeerTube instance:
  * URL: https://peervideo.ru
  * version: 4.2.0
  * NodeJS version: v14.19.3
  * Ffmpeg version: 4.3.4-0+deb11u1

My hardware is on the server
AMD Ryzen7 2700 (8/16)
DDR4 12GB
HDD 2 - 6TB (ZFS Mirror)

**Comment by Alterak** [comment]
I'm running tests on another server again. Transcoding of live videos is completely disabled.

![Скриншот 11 06 22_13 04 17](https://user-images.githubusercontent.com/11453567/173183330-70ebfc16-61e7-45de-b6b3-a37bfe1023b3.png)


As a result, I get errors again.

```
warn[11.06.2022, 12:53:35] Unknown files map to remove sha for c7d4f4d1-3bb3-4597-bad6-4f8484764761.
{
  "tags": [
    "live",
    "c7d4f4d1-3bb3-4597-bad6-4f8484764761"
  ]
}
warn[11.06.2022, 12:53:35] Unknown files map to remove sha for c7d4f4d1-3bb3-4597-bad6-4f8484764761.
{
  "tags": [
    "live",
    "c7d4f4d1-3bb3-4597-bad6-4f8484764761"
  ]
}
error[11.06.2022, 12:53:36] Cannot process segments
{
  "err": {
    "stack": "Error: ENOENT: no such file or directory, open '/var/www/peertube/storage-disk/streaming-playlists/hls/c7d4f4d1-3bb3-4597-bad6-4f8484764761/0-000044.ts'",
    "message": "ENOENT: no such file or directory, open '/var/www/peertube/storage-disk/streaming-playlists/hls/c7d4f4d1-3bb3-4597-bad6-4f8484764761/0-000044.ts'",
    "errno": -2,
    "code": "ENOENT",
    "syscall": "open",
    "path": "/var/www/peertube/storage-disk/streaming-playlists/hls/c7d4f4d1-3bb3-4597-bad6-4f8484764761/0-000044.ts"
  },
  "tags": [
    "live",
    "KN1TKM9G",
    "c7d4f4d1-3bb3-4597-bad6-4f8484764761"
  ]
}
```

I can't believe my CPU can't process live video, even with transcoding turned off.
The processor processes ordinary video without problems, even 3 simultaneous tasks.

**Comment by Chocobozzz** [comment]
I'm sorry, it's actually a peertube bug. See https://github.com/Chocobozzz/PeerTube/issues/5051
