### ISSUE TITLE
Changes in production.yaml file on Peertube upgrade

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5036]
**Parts of the documentation concerned:**

https://docs.joinpeertube.org/install-any-os?id=upgrade

**Describe the desired information/correction**

When we use the upgrade.sh script https://docs.joinpeertube.org/install-any-os?id=auto , the script does a diff between the current production.yaml file and the production.yaml.example file: https://github.com/Chocobozzz/PeerTube/blob/1a99dc647fd407f443238d10f9a721c8d887074f/scripts/upgrade.sh#L81

This diff is difficult to read, because there are many customizations in the production.yaml file.

I suggest to remove the diff in the script, and instead add a chapter in the documentation, with the same kind of diff than for the nginx or systemd configuration (https://docs.joinpeertube.org/install-any-os?id=nginx and https://docs.joinpeertube.org/install-any-os?id=systemd)

I'll make a PR with a proposal.

NB: instead of removing the diff, we could also change it to be the same kind of diff that is in documentation for nginx and systemd (between the last installed versions).

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/5037
