### ISSUE TITLE
Channel filter in «my library»: use channel name instead of channel display name

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5038]
**Describe the current behavior**

When I open the filters on the page https://www.yiny.org/my-library/videos , channels are listed by they names, and not display names.
For old channels, the name was a UUID. So it is impossible to use the filter.

See for example the first 3 in this screenshot:

![image](https://user-images.githubusercontent.com/38844060/172861461-2fda52a4-4cee-4655-add8-cb22b7bb17f2.png)

Here is the public links to one these 3 channels, so you can see what I mean: https://www.yiny.org/c/18791fc5-cc9f-4937-96df-82ef2fe3d72e/videos
Here is one of the channel that works: https://www.yiny.org/c/punk/videos (here the name is not a uuid, it was chosen by the user).

**Steps to reproduce:**

1. Open «my library => videos»
2. Open the menu on the left of the «filter» field

**Describe the expected behavior**

This dropdown should use `display name` instead of `name`

**Additional information**

* PeerTube instance:
  * URL: https://www.yiny.org
  * version: 4.2.0

* Browser name, version and platforms on which you could reproduce the bug: Firefox

**Comment by AnvarKhatik** [comment]
Can I Resolve This Issue & You Can Guide Me To Fixed This Issue?
