### ISSUE TITLE
Homepage local config 

### ISSUE THREAD

**Issue by webafrancois** [Chocobozzz/PeerTube#504]
* **PeerTube version or URL:** https://videos.cemea.org/
* **Browser name/version:** Firefox 59.0.2
* **NodeJS version:** 8.10.0-1nodesource1

* **What is the expected behaviour?** 
I configure the "Default client route" as local videos. When I click on the logo "Peertube" on the top, I arrive to my homepage with only the local videos. I thought that the default homepage is local videos. But it's not.
* **What do you see instead?**
When I open a new private window of my browser ant point to my peertube website, the default homepage is https://videos.cemea.org/videos/trending
"Default client route" is not the same as default homepage when you're not login ? 

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

**Comment by Chocobozzz** [comment]
The configuration will only take to effect on the second user visit (optimization). But I agree we should find a solution for the configuration to be taken into account on the first visit.

**Comment by Chocobozzz** [comment]
Closing this issue, we accept the bad config on first visit for better performance (ie not waiting the config before loading the page).

**Comment by tiotrom** [comment]
Since the homepage is what users see first, I'd argue it is important enough to make it work properly :). Else it kinda defeats a bit the purpose of choosing a default landing page. Cheers!

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/aea0b0e7cde7495e60fe07b4444067f53d35ce3f
