### ISSUE TITLE
Video embeds in Discord

### ISSUE THREAD

**Issue by Sobsz** [Chocobozzz/PeerTube#5040]
**Describe the problem to be solved**

[Discord](https://discord.com) is mostly compatible with the Twitter embed format, but one area it differs in is ~~video~~ HTML embeds. Enabling video embeds for Twitter not only doesn't work for Discord, but it causes the embeds to go from a full-size static image:

![full-size thumbnail](https://user-images.githubusercontent.com/18291848/172944845-84d91620-aa9f-4a02-a753-f4c70a059308.png)

to this subjectively uglier-looking format:

![tiny thumbnail to the right](https://user-images.githubusercontent.com/18291848/172944912-75adbf09-d181-47dc-ba10-03b650bb909f.png)

**Describe the solution you would like:**

According to [this comment](https://github.com/discord/discord-api-docs/issues/734#issuecomment-434856405) from a Discord developer, arbitrary iframes cannot be embedded and the only way to embed a video is by providing a direct URL to the video file itself in the `og:video:url` meta tag.

I've confirmed that copying the HLS URL from the `Download` section into `og:video` and related meta tags makes the video embed work in Discord, while still delivering the custom iframe (defined in `twitter:player`) to Twitter users. However, there might be concern about the added "leech" factor due to viewers no longer being incentivized to view the video in the browser and thus participate in the P2P network.

**Comment by Sobsz** [comment]
Another issue I just realized: while Twitter would be unaffected, other services with iframe support (such as Mastodon) would. I've only just heard of OpenGraph, so I don't know if it's possible to provide both an iframe URL and a fallback MP4 one, but if not, the proposed feature should probably be toggleable.

**Comment by Chocobozzz** [comment]
Hi,

I'm not sure to understand: you say that updating twitter setting changes discord behaviour so I presume they use the `twitter:card` tags no? Why would they also use opengraph tags?

**Comment by Sobsz** [comment]
Oh, I thought it changed the Open Graph tags too, but the diff doesn't lie... I guess it tries to embed with the Twitter tags first, then falls back to Open Graph once it notices it's an embed.

Some new notes:
- I just checked and Mastodon uses the Twitter tags too, so its embeds are unaffected.
- The Open Graph standard (at least, [the little I could find of it](https://ogp.me/)) has a direct video URL as the sole example of the `og:video` tag and doesn't mention anything about iframes, so I'd be surprised if any platform accepts embed links there.

**Comment by Chocobozzz** [comment]
Hello,

It's sad but we can't do anything here. Discord needs to adapt their whitelist or do not use a whitelist like Twitter that correctly embed PeerTube player. We prefer to not change our OpenGraph/Twitter card metadata to just work with Discord.

**Comment by Aeris1One** [comment]
Based on what I understood :
- PeerTube exposes the correct Twitter tags with an iframe for the video, it also exposes OpenGraph tags but no tag that allow to play the video in an embed.
- Discord have a whitelist over which websites can use an iframe, there's most likely zero PeerTube instance that are on that whitelist.
- Discord falls back to OpenGraph when Twitter tags are incorrect or if the iframe is not in the whitelist.
- OpenGraph have a `og:video` tag that takes a direct link.
- Discord embed works well when `og:video` is set to the direct link that's shown in the "Download" button of PeerTube.
- Setting the OpenGraph `og:video` doesn't change how the embed is rendered in, at least, Twitter and Mastodon, as they primarly use Twitter tags. 

Would setting the `og:video` tag to a direct link to the video be possible? 
It would make PeerTube "more compliant" with OpenGraph specs and would allow softs that doesn't support Twitter tags to play the video in an embed.

As a side note, if you prefer to set this tag only for Discord requests, Discord uses the UserAgent `Mozilla/5.0 (compatible; Discordbot/2.0; +https://discordapp.com)` when parsing pages for embed.

**Comment by ben221199** [comment]
As far as I know the iframe-embeds are done by the `html` attribute in the OEmbed response.

**Comment by sallyFoster** [comment]
This was never fixed. It is not working
