### ISSUE TITLE
yt upload plugin

### ISSUE THREAD

**Issue by ncamacho97** [Chocobozzz/PeerTube#5044]
hello when trying to install auto-import-ytb i fail to install 

anyone have this issue ?

**Comment by Tr4sK** [comment]
I have the same on my raspberry/Docker. I think it was because of some wrong path between /usr/python and /usr/python3 or sqlite.

I don't think it's the right place those issue. Try to contact the plugin dev

**Comment by ncamacho97** [comment]
@Chocobozzz any reason or what I can do resolve this issue please and thank you

**Comment by Chocobozzz** [comment]
Hello,

We don't develop this plugin. You should ask the maintainer instead: https://www.npmjs.com/package/peertube-plugin-auto-import-ytb
