### ISSUE TITLE
use yt-dlp as download option for Youtube

### ISSUE THREAD

**Issue by 01123581321345589144233** [Chocobozzz/PeerTube#5047]
Hi, when i import a video from yt the download is very slow. it is possible to include the fork yt-dlp  ?
Or as extra option under in the upload page.

**Comment by Chocobozzz** [comment]
Hello,

You can already set `yt-dlp` in the config: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L499

**Comment by 01123581321345589144233** [comment]
thanks :-)
