### ISSUE TITLE
Add ability to tag NSFW remote videos

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#505]
See #501 

It would be fine to add an option in the admin section to hide NSFW content comming from federation and not tagget yet.

**Comment by Chocobozzz** [comment]
I think it's the same issue than https://github.com/Chocobozzz/PeerTube/issues/506

**Comment by gegeweb** [comment]
No really, that's why I've open two issue. But perhaps it could be implemented at the same time (if implemented).

This, is for tagged with NSFW untagged content comming from federation (see #501 if it's a bug, that's because I've received NSFW - porn - untagged on mine). We keep the content available on the instance, but tagged with NSFW. Tagged the content could send a notification (signalement) to the admin of the original instance. It is then up to him to make the decision on his own.

#506 is to refuse or automatically blacklist on the instance NSFW content. So, your question is right: uploaded and comming from federation. That is the ability to refuse NSFW. Of course we have to trust the users for the uploaded videos. However we can moderate in hindsight with the blacklist option.

Another related ehancement might be to be able to configure the instance for no federate NSFW content uploaded on it.

**Comment by Chocobozzz** [comment]
In fact, it's not a good idea to update a remote video. That could break the AP specs concerning the update (update the whole object), or add complexity inside the PeerTube codebase.

If you think a video should be NSFW whereas it is no, just blacklist it.
