### ISSUE TITLE
After replay video job completes it disables the original recurring live video

### ISSUE THREAD

**Issue by Mike35538** [Chocobozzz/PeerTube#5051]
### Is there an existing issue for this?

- [X] I have searched existing issues

### Describe the current behavior

After a reply video job completed the original permanent/recurring live video is un-viewable when the stream starts again.

### Steps to reproduce

1. Create a Live video that is a permanent/recurring live and enable Automatically publish a replay when your live ends.
2. Stream to the Live video using streaming software, eg. OBS
3. Stop streaming in OBS for 10 seconds so that a reply is automatically generated
4. Now start OBS stream again.
5. Wait for the reply video-live-ending job to complete.
6. Now go to the original live stream video page in PeerTube and refresh the page, hit the play button, the video won't start and is unreachable.

### Describe the expected behavior

Replay video job should not affect the original live video.

### Additional information

* PeerTube instance:
  * Version: 4.2.0

**Comment by Chocobozzz** [comment]
Hello,

Please paste web browser and server logs when you restream the video

**Comment by Mike35538** [comment]
I've checked it in Firefox 100.0.2 and Edge 102.0.1245.39. In Firefox I can't push the play button, in Edge the video area is all black.

Here's the PeerTube Logs, is this what you're looking for?

warn[6/14/2022, 8:13:55 AM] Cannot authenticate.

{
  "err": {
    "statusCode": 401,
    "status": 401,
    "code": 401,
    "message": "Invalid token: access token has expired",
    "name": "invalid_token",
    "stack": "invalid_token: Invalid token: access token has expired\n    at new InvalidTokenError (/var/www/peertube/versions/peertube-v4.2.0/node_modules/oauth2-server/lib/errors/invalid-token-error.js:25:14)\n    at AuthenticateHandler.validateAccessToken (/var/www/peertube/versions/peertube-v4.2.0/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:224:11)\n    at AuthenticateHandler.<anonymous> (/var/www/peertube/versions/peertube-v4.2.0/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:74:19)\n    at PassThroughHandlerContext.finallyHandler (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/finally.js:57:23)\n    at PassThroughHandlerContext.tryCatcher (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/async.js:15:14)\n    at processImmediate (internal/timers.js:464:21)"
  }
}

warn[6/14/2022, 8:13:55 AM] Cannot authenticate.

{
  "err": {
    "statusCode": 401,
    "status": 401,
    "code": 401,
    "message": "Invalid token: access token has expired",
    "name": "invalid_token",
    "stack": "invalid_token: Invalid token: access token has expired\n    at new InvalidTokenError (/var/www/peertube/versions/peertube-v4.2.0/node_modules/oauth2-server/lib/errors/invalid-token-error.js:25:14)\n    at AuthenticateHandler.validateAccessToken (/var/www/peertube/versions/peertube-v4.2.0/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:224:11)\n    at AuthenticateHandler.<anonymous> (/var/www/peertube/versions/peertube-v4.2.0/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:74:19)\n    at PassThroughHandlerContext.finallyHandler (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/finally.js:57:23)\n    at PassThroughHandlerContext.tryCatcher (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/async.js:15:14)\n    at processImmediate (internal/timers.js:464:21)"
  }
}

warn[6/14/2022, 8:13:55 AM] Cannot authenticate.

{
  "err": {
    "statusCode": 401,
    "status": 401,
    "code": 401,
    "message": "Invalid token: access token is invalid",
    "name": "invalid_token",
    "stack": "invalid_token: Invalid token: access token is invalid\n    at new InvalidTokenError (/var/www/peertube/versions/peertube-v4.2.0/node_modules/oauth2-server/lib/errors/invalid-token-error.js:25:14)\n    at /var/www/peertube/versions/peertube-v4.2.0/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:203:15\n    at tryCatcher (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/versions/peertube-v4.2.0/node_modules/bluebird/js/release/async.js:15:14)\n    at processImmediate (internal/timers.js:464:21)"
  }
}

warn[6/14/2022, 8:19:23 AM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/14/2022, 8:19:23 AM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/14/2022, 8:19:23 AM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/14/2022, 8:19:23 AM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/14/2022, 8:19:23 AM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/14/2022, 8:19:23 AM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/14/2022, 8:19:23 AM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/14/2022, 8:19:23 AM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/14/2022, 8:19:23 AM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/14/2022, 8:19:23 AM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/14/2022, 8:19:23 AM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/14/2022, 8:19:23 AM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/14/2022, 8:19:23 AM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/14/2022, 8:19:23 AM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/14/2022, 8:19:23 AM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/14/2022, 8:19:23 AM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/14/2022, 8:19:23 AM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

error[6/14/2022, 8:19:24 AM] Cannot process segments

{
  "err": {
    "stack": "Error: ENOENT: no such file or directory, open '/var/www/peertube/storage/streaming-playlists/hls/1cd5e8df-cd34-40d5-8848-a75abf3e1f3f/0-000031.ts'",
    "message": "ENOENT: no such file or directory, open '/var/www/peertube/storage/streaming-playlists/hls/1cd5e8df-cd34-40d5-8848-a75abf3e1f3f/0-000031.ts'",
    "errno": -2,
    "code": "ENOENT",
    "syscall": "open",
    "path": "/var/www/peertube/storage/streaming-playlists/hls/1cd5e8df-cd34-40d5-8848-a75abf3e1f3f/0-000031.ts"
  },
  "tags": [
    "live",
    "TZTDCT6H",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/14/2022, 8:19:28 AM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

error[6/14/2022, 8:19:32 AM] Cannot process segments

{
  "err": {
    "stack": "Error: ENOENT: no such file or directory, open '/var/www/peertube/storage/streaming-playlists/hls/1cd5e8df-cd34-40d5-8848-a75abf3e1f3f/0-000032.ts'",
    "message": "ENOENT: no such file or directory, open '/var/www/peertube/storage/streaming-playlists/hls/1cd5e8df-cd34-40d5-8848-a75abf3e1f3f/0-000032.ts'",
    "errno": -2,
    "code": "ENOENT",
    "syscall": "open",
    "path": "/var/www/peertube/storage/streaming-playlists/hls/1cd5e8df-cd34-40d5-8848-a75abf3e1f3f/0-000032.ts"
  },
  "tags": [
    "live",
    "TZTDCT6H",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/cdd838168d617f70fc04fe7f23846810e7e07082

**Comment by asterismo** [comment]
I'm beeing affected by this, is this fixed in 4.2.0? or is fixed in the next release?

**Comment by Chocobozzz** [comment]
Yes, it is fixed in 4.2.2
