### ISSUE TITLE
Change the PeerTube button text in embed

### ISSUE THREAD

**Issue by quicktrick** [Chocobozzz/PeerTube#5055]
### Describe the problem to be solved

In the embedded videos I have only one text option for the PeerTube button:

![image](https://user-images.githubusercontent.com/18548503/173854353-cd22ff2a-730b-45a7-9079-6c25590364d8.png)

### Describe the solution you would like

I'd like to put my own text in there. If I inspect the element in the browser, I can find the code with this text and I can change it:

```
<button class="vjs-icon-settings vjs-control vjs-button vjs-settings" type="button" aria-disabled="false" title="Settings" aria-label="Settings Button" aria-expanded="false"><span class="vjs-icon-placeholder" aria-hidden="true"></span><span class="vjs-control-text" aria-live="polite">Settings</span></button>
<a href="https://tube.artsale.info/w/gSMACZ8YGX784LyLXkizms?start=10m42s" title="Video page (new window)" class="vjs-peertube-link" target="_blank" aria-disabled="false">PeerTube</a>
```

![image](https://user-images.githubusercontent.com/18548503/173855805-25603afc-6ec2-4b2c-831a-4f0c9c6ca5d1.png)

But I can't find where to change it in the PeerTube source code. Is there any way to change this text or can you add an option to change this text in `production.yaml`?

**Comment by Mike35538** [comment]
I just wanted to echo that being able to change the instance name in the embed player is important, specifically in terms of consistent branding and name recognition for the instance.

If the video embed is on another website, users click the PeerTube link thinking they are being redirected to a site called PeerTube but instead are redirected to the instance URL.

The embed link could automatically just use the instance name as set in: configuration > information
Or you could allow the instance admin the ability to manually set it, possible using a shortly name, or a name without spaces.

If this feature does get added, consider also automatically updating the name in the share modal.
By default it says: Display PeerTube button link
If the name is updated in the production.yaml or settings for example it would show: Display ArtSaleTube button link

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/bd2b51be4b29e6c3c72d8715164cde672bd41186
