### ISSUE TITLE
Failure to move to object storage doesn't put video in failure state

### ISSUE THREAD

**Issue by averymd** [Chocobozzz/PeerTube#5056]
### Describe the current behavior

In v4.2.0, when a `move-to-object-storage` job fails with the error "job stalled more than allowable limit", the video is left in the `TO_MOVE_TO_EXTERNAL_STORAGE` state instead of being moved to the `TO_MOVE_TO_EXTERNAL_STORAGE_FAILED` state. The result is that the `move-to-object-storage` job cannot be retried until the DB is modified to set the state of the video to something else.

The full error log of the job failure:

```
error[6/15/2022, 2:26:02 PM] Cannot execute job 43 in queue move-to-object-storage.
{
  "payload": {
    "videoUUID": "0ee615fa-81be-4dbb-ab71-18559bb68183",
    "isNewVideo": false,
    "previousVideoState": 8
  },
  "err": {
    "stack": "Error: job stalled more than allowable limit\n    at /var/www/peertube/versions/peertube-v4.2.0/node_modules/bull/lib/queue.js:1009:13\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Promise.all (index 0)",
    "message": "job stalled more than allowable limit"
  }
}
```

If helpful, additional context for the situation around this can be found on [the forums](https://framacolibri.org/t/transcoding-error-on-undesired-resolution/15046/7?u=maw).

### Steps to reproduce

1. Have a `move-to-object-storage` job fail with "job stalled more than allowable limit". (I'm not sure how to make this happen.)
2. Attempt to use [create-move-video-storage-job.js](https://docs.joinpeertube.org/maintain-tools?id=create-move-video-storage-jobjs) on the video.
3. Creating the job will fail with the message, "This video is already being moved to external storage"
4. Update the video in the database to a failure state: `UPDATE PUBLIC.video SET "state" = 8 WHERE uuid = '<uuid>';`
5. Attempt to create the job again. This time the job will queue.

### Describe the expected behavior

I would expect either:

1. To be able to immediately start another `move` job once one fails, or
2. To get a clearer error message if I should not be able to do so.

### Additional information

* PeerTube instance:
  * URL: https://irrsinn.video
  * Version: 4.2.0
  * NodeJS version: 14.19.0
  * Ffmpeg version: 4.2.2-1ubuntu1~16.04.york0

* Browser name, version and platforms on which you could reproduce the bug: n/a
* Link to browser console log if relevant: n/a
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): n/a

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/3256771725430ab6fc716e937b88ca2b2b85263b
