### ISSUE TITLE
Docker Compose Doesn't work

### ISSUE THREAD

**Issue by tripleo1** [Chocobozzz/PeerTube#5057]
### Describe the current behavior

Error 

```
...
production_webserver_1 exited with code 1
...
```

### Steps to reproduce

1. `docker-compose up`

### Describe the expected behavior

...

### Additional information

* PeerTube instance:
  * URL:  intended for local network only
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I can't help if you don't correctly fill the template, in particular sever logs

**Comment by tripleo1** [comment]
```
[peertube.local:443] 2022-06-17 05:20:17.787 [32minfo[39m: Cleaning video viewers.

... repeats about 50 times

[peertube.local:443] 2022-06-17 06:07:17.775 [32minfo[39m: Removing bad actor follows (scheduler).
[peertube.local:443] 2022-06-17 06:07:17.778 [32minfo[39m: Removing old jobs in scheduler.
[peertube.local:443] 2022-06-17 06:07:17.788 [32minfo[39m: Processing viewer statistics.
[peertube.local:443] 2022-06-17 06:07:17.796 [32minfo[39m: Cleaning video viewers.

... repeats...
```
It's been restarting over and over I guess.

`peertube.local` is mapped to 127.0.0.1 in `/etc/hosts`.

**Comment by tripleo1** [comment]
My use case is to run peertube as a local service: first, for me on my personal workstation, then maybe move it to a NAS or something.  At this point, I am not interested in the P2P aspect...

If that helps.

**Comment by Tr4sK** [comment]
I think that you're missing something here.
It seems on the last log that the peertube app is running fine.
The issue you describe in the first post, is about peertube webserver, in our case nginx crashing. Can you check that the nginx configuration file is correct and does not contain error ?
Are you missing some ssl certificates ?

**Comment by tripleo1** [comment]
> Are you missing some ssl certificates ?

Very likely. I think I skipped that...
