### ISSUE TITLE
Different total users on /about/instance and /admin/users/list

### ISSUE THREAD

**Issue by drym3r** [Chocobozzz/PeerTube#5058]
### Describe the current behavior

When showing the user's statistics on `/about/instance` it shows an incorrect amount of users, if the total on `/admin/users/list` can be the source of true.

### Steps to reproduce

Visit both endpoints and compare.

### Describe the expected behavior

It should show the same number.

### Additional information

* PeerTube instance:
  * URL: https://fediverse.tv
  * Version: 4.2.0
  * NodeJS version: The one on the docker image.
  * Ffmpeg version: The one on the docker image.

* Browser name, version and platforms on which you could reproduce the bug: any

A couple of captures:
- The [about](https://fediverse.tv/about/instance#statistics) from the instance:
![2022-06-17-185635_1607x304_scrot](https://user-images.githubusercontent.com/7255473/174343634-60825e18-e919-4748-bfb2-c10bd4368e61.png)

- The number of users shown on the admin interface:
![2022-06-17-185733_178x26_scrot](https://user-images.githubusercontent.com/7255473/174343736-1b1714c1-0e29-4d53-b495-4448dd4da535.png)

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/5e0dbb3e52797cdea7a9069a9dd605c8f84034dd

**Comment by drym3r** [comment]
@Chocobozzz Will this affect the metrics exposed at `/api/v1/server/stats`? It also shows the incorrect number of users.
We will update the next week, so I'll be able to test it.

**Comment by Chocobozzz** [comment]
@drym3r yes, the commit fixes this specific endpoint
