### ISSUE TITLE
Font in night builds

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5059]
### Describe the current behavior

In nightly builds, starting with the **peertube-nightly version-2022-06-17** the font has been enlarged.

![fonts](https://user-images.githubusercontent.com/11453567/174428909-67b2a79b-04d1-4623-85a3-659d0ed4379b.png)

Or was this font size set on purpose?

**Comment by Chocobozzz** [comment]
Hello,

Yes, the font-size has been increased in https://github.com/Chocobozzz/PeerTube/commit/5b0ec7cddb1ae6dbd2057f067382866f846b882c
