### ISSUE TITLE
Add admin option to hide NSFW videos

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#506]
it would be fine to have an admin option for refuse (or automaticaly blacklist) NSFW tagged content comming from federation.

**Comment by Chocobozzz** [comment]
What about NSFW content uploaded on your instance?

**Comment by gegeweb** [comment]
Good question! I don't really know… but I think if we refuse NSFW content from federation we probably refuse NFSW uploaded on our instance.

**Comment by gegeweb** [comment]
As I've commented on the #505, this is a little bit different. But perhaps this and the #505 could be merged on the same ehancement for the moderation about NSFW contents.

**Comment by benrob0329** [comment]
IMHO simply getting it off the front page would be a great first step, as not all NSFW content is necessarily say, porn. But people should still be able to follow whoever they want, even if the server doesn't help in the streaming.

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/0883b3245bf0deb9106c4041e9afbd3521b79280
