### ISSUE TITLE
Cannot get channel list while uploading hence cannot upload any video after upgrading to 4.2.0

### ISSUE THREAD

**Issue by fweng322** [Chocobozzz/PeerTube#5061]
### Describe the current behavior

After upgrading to v4.2.0, when trying to uploading a video, in the channel selection widget I got only "No items found" (but actually I have several channels in my account) and hence when trying to upload it showed an error message "Incorrect request parameters: channelId".

### Steps to reproduce

1. Hit the button to publish a video
2. Got "No items found" in the channel list
3. Got "Incorrect request parameters: channelId" when trying to publish anyway

### Describe the expected behavior

It should be able to get my channels and be able to upload

### Additional information

* PeerTube instance:
  * URL: https://peertube.slat.org
  * Version: v4.2.0
  * NodeJS version: 16.15.1-deb-1nodesource1
  * Ffmpeg version: 4.3.4-0+deb11u1

* Browser name, version and platforms on which you could reproduce the bug: Firefox 91.10.0esr
* Link to browser console log if relevant: https://pastebin.com/RcjQw1Gu
  **a TypeError  e.Z(...) is undefined in Line 10**

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by fweng322** [comment]
After upgrading to v4.2.0 my avatar couldn't be shown in the left sidebar but could be shown in my profile.

https://nextcloud.slat.org/index.php/s/rQmbjDaz68qzPZf

Not sure if they are the same issues.  For avatar issue I didn't get any error messages in console log.

**Comment by fweng322** [comment]
I could get the list in channel list page ( https://peertube.slat.org/my-library/video-channels ) without errors in console log

**Comment by Chocobozzz** [comment]
Hello,

Have you followed https://github.com/Chocobozzz/PeerTube/blob/develop/CHANGELOG.md#important-notes?
