### ISSUE TITLE
Autoplay loops between two most recent videos

### ISSUE THREAD

**Issue by cloo** [Chocobozzz/PeerTube#5062]
### Describe the current behavior

When playing video with autoplay switched on, two most recent videos are looped interchangeably, and no other videos are shown.

### Steps to reproduce

1. Play the most recent uploaded video
2. Switch on "autoplay" switch during playback
3. Wait for next video to start
4. Observe that the most recent video is first in playlist again
5. Observe that the video you played before, is first in playlist again

### Describe the expected behavior

The videos in autoplay should never be repeated.

### Additional information

* PeerTube instance: private
  * Version: 4.1.1

**Comment by Chocobozzz** [comment]
Hi,

Thanks for this issue. Merging it into https://github.com/Chocobozzz/PeerTube/issues/1985 since we use the "Other videos" to play next video
