### ISSUE TITLE
Confusing Centos8 dependency (ffmpeg + unzip + yarn)

### ISSUE THREAD

**Issue by slendermon** [Chocobozzz/PeerTube#5063]
### Describe the desired information/correction

This is a slightly confusing one, but on the depencies for ffmpeg, (step 3), then step 1 on the link, this is the command: 
`sudo yum-config-manager --set-enabled PowerTools  `

That doesn't work. But in the comments section, bottom website, this works: 
`sudo yum-config-manager --set-enabled powertools`

Maybe make a note to make it lowercased? Or just take the whole lines of commands and embed them in the dependency section? 

Also add dependency `unzip`

When getting to install peertube part, yarn didn't work,
`sudo: yarn: command not found`

So I used this website: 
https://linuxize.com/post/how-to-install-yarn-on-centos-8/

**Comment by Chocobozzz** [comment]
Hi,

Since I'm not a centos user, could you update the documentation with the commands that worked for you?

**Comment by slendermon** [comment]
Sorry that I took a while, I couldn't access my computer, so I made a pull request with my phone.

**Comment by Chocobozzz** [comment]
@slendermon Where did you make a pull request? I don't see it
