### ISSUE TITLE
Pro people s 

### ISSUE THREAD

**Issue by bgman111111** [Chocobozzz/PeerTube#5064]
### Describe the desired information/correction

Hi please this hackers who are expert in linux. help newbies like me how to make it like you. How to have latest thing on linux, so peertube can be latest working.

I try install peertube telegram and it comment missing  --module_path=/var/www/peertube/storage/plugins/node_modules/sqlite3/lib/binding/node-v93-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)\n"
Jun 20 00:22:05 a peertube[102886]:   }
Jun 20 00:22:05 a peertube[102886]: }
Jun 20 00:22:05 a peertube[102886]: [peertube.bgzashtita.es:443] 2022-06-20 00:22:05.569 #033[32minfo#033[39m: 192.168.0.0 - - [20/Jun/2022:00:22:05 +0000] "POST /api/v1/plugins/install HTTP/1.0" 400 255 "https://peertube.bgzashtita.es/admin/plugins/search?pluginType=1" "Firefox"
Jun 20 00:22:19 a peertube[102886]: [peertube.bgzashtita.es:443] 2022-06-20 00:22:19.795 #033[32minfo#033[39m: Cleaning video viewers.
root@a:/home/a# tail -f /var/log/peertube.log.1
Jun 20 00:22:05 a peertube[102886]:       "killed": false,
Jun 20 00:22:05 a peertube[102886]:       "signal": null,
Jun 20 00:22:05 a peertube[102886]:       "cmd": "yarn add peertube-plugin-telegram@0.1.6"
Jun 20 00:22:05 a peertube[102886]:     },
Jun 20 00:22:05 a peertube[102886]:     "stdout": "yarn add v1.22.18\n[1/4] Resolving packages...\n[2/4] Fetching packages...\n[3/4] Linking dependencies...\n[4/4] Building fresh packages...\ninfo Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.\n",
Jun 20 00:22:05 a peertube[102886]:     "stderr": "warning package.json: No license field\nwarning ../../package.json: No

license found.

i try web-monetization and it dont work. what is happeing. why this two plugins dont work.
If expert in linux make manuals for newbies teaching them how to fix things errors wont be. And this newbies can teach other newbies. I see in other peertube there is donation button and someo  i can't activate it neither acivate it for paypal.  It comment missing license. I try conetact some peertube developer and he has gitlab and no register web page. so can't write with him. Please hepl newbie understand how to be pro.

**Comment by Chocobozzz** [comment]
Hello,

Please open an issue on web-monetization repository instead
