### ISSUE TITLE
how to activate support plugin peertube

### ISSUE THREAD

**Issue by bgman111111** [Chocobozzz/PeerTube#5065]
### Describe the desired information/correction

Eeeeeee i try find support plugin for peertube and can;t find it:

Like here https://www.yiny.org/w/399a8d13-d4cf-4ef2-b843-98530a8ccbae this is demonstration web page and had hand with hearth. How i can put the same plugin on my peertube.

**Comment by Chocobozzz** [comment]
Hello,

Please use the forum to ask questions: https://framacolibri.org/c/peertube/
