### ISSUE TITLE
Upgrade to 4.2.1 re-installs 4.2.0.

### ISSUE THREAD

**Issue by jpatje** [Chocobozzz/PeerTube#5068]
### Describe the problem

When I do the upgrade as per the documentation, it installs version 4.2.0 again instead of 4.2.1.

Using the command:

cd /var/www/peertube/peertube-latest/scripts && sudo -H -u peertube ./upgrade.sh

### Additional information

* PeerTube instance URL: secret
* PeerTube version: 4.2.0.
* NodeJS version: 16.14.0
* Ffmpeg version: 4.2.7-0ubuntu0.1
* Redis version: 5.0.7
* PostgreSQL version: unable to find

**Comment by Booteille** [comment]
Hi.

PeerTube 4.2.1 is not a thing yet. The last released version is 4.2.0 as you can see on this page: https://github.com/Chocobozzz/PeerTube/releases

**Comment by Booteille** [comment]
No problem. Since my answer, v4.2.1 became a thing. Don't forget to check release notes before upgrading and to follow upgrade steps!
