### ISSUE TITLE
Live ending job that breaks new live session still happening

### ISSUE THREAD

**Issue by Mike35538** [Chocobozzz/PeerTube#5070]
### Describe the current behavior

I updated to 4.2.1 and tested live streaming as show in steps 1-6 on #5051.

As soon as the replay video-live-ending job completes, the live stream on the PeerTube page stops, goes to a black screen with the spinning loading circle graphic. Logs below:

warn[6/21/2022, 3:21:46 PM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/21/2022, 3:21:46 PM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/21/2022, 3:21:46 PM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/21/2022, 3:21:46 PM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/21/2022, 3:21:46 PM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/21/2022, 3:21:46 PM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/21/2022, 3:21:46 PM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/21/2022, 3:21:46 PM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/21/2022, 3:21:46 PM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/21/2022, 3:21:46 PM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/21/2022, 3:21:46 PM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/21/2022, 3:21:46 PM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/21/2022, 3:21:46 PM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/21/2022, 3:21:46 PM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/21/2022, 3:21:46 PM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/21/2022, 3:21:46 PM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

warn[6/21/2022, 3:21:46 PM] Unknown files map to remove sha for 1cd5e8df-cd34-40d5-8848-a75abf3e1f3f.

{
  "tags": [
    "live",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

error[6/21/2022, 3:21:52 PM] Cannot process segments

{
  "err": {
    "stack": "Error: ENOENT: no such file or directory, open '/var/www/peertube/storage/streaming-playlists/hls/1cd5e8df-cd34-40d5-8848-a75abf3e1f3f/0-000035.ts'",
    "message": "ENOENT: no such file or directory, open '/var/www/peertube/storage/streaming-playlists/hls/1cd5e8df-cd34-40d5-8848-a75abf3e1f3f/0-000035.ts'",
    "errno": -2,
    "code": "ENOENT",
    "syscall": "open",
    "path": "/var/www/peertube/storage/streaming-playlists/hls/1cd5e8df-cd34-40d5-8848-a75abf3e1f3f/0-000035.ts"
  },
  "tags": [
    "live",
    "2IHBCL0Y",
    "1cd5e8df-cd34-40d5-8848-a75abf3e1f3f"
  ]
}

**Comment by Chocobozzz** [comment]
Arf sorry. It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/53023be33af420675d0060eb95c99a8038457564

Could you confirm that fast restream in a permanent live **without** save replay enabled correctly works with 4.2.1?

**Comment by Mike35538** [comment]
After testing the fast restream without saving replay I noticed:
If I stream for about 15 seconds in OBS, then stop the stream for about 15 seconds, then re-start the stream, it interrupts the live view on the PeerTube page.
The interruption happens when I'm watching the video stream on the PeerTube page and when video-live-ending is completed it stops the video and the loading circle spinning graphic appears and the video doesn't play anymore. But then if I refresh the page and hit the play button then the video starts playing as normal again.

Thanks!

**Comment by Chocobozzz** [comment]
Thanks! I fixed another bug in https://github.com/Chocobozzz/PeerTube/commit/92083e42289e19033425672dfbe2234aef03c6df
