### ISSUE TITLE
No more channel to upload

### ISSUE THREAD

**Issue by ddeenniiss** [Chocobozzz/PeerTube#5073]
### Describe the current behavior

Since the upgrade to 4.2.0, some users no longer have access to channels in the upload form ("no item")

So they can't upload anything anymore

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL: https://videos.domainepublic.net
  * Version: 4.20
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by ddeenniiss** [comment]
![Capture d’écran du 2022-06-22 11-44-58](https://user-images.githubusercontent.com/17127091/174998799-1a9b0410-5a89-4c8b-a76c-8a43af31247a.png)
![Capture d’écran du 2022-06-22 11-44-34](https://user-images.githubusercontent.com/17127091/174998803-6093f828-5ea0-4dd8-8c2b-27b1047adebc.png)

**Comment by kontrollanten** [comment]
Hello,

Have you followed https://github.com/Chocobozzz/PeerTube/blob/develop/CHANGELOG.md#important-notes?

**Comment by Tr4sK** [comment]
I don't have that issue.
If you use docker, have you properly restarted the service after the upgrade ?

```
docker-compose down -v
docker-compose up -d
```

**Comment by ddeenniiss** [comment]
yes, I did update and adapt the nginx configuration.

For now, the problem is only with this account. For two others that I tested everything works fine

**Comment by Chocobozzz** [comment]
Hello,

Please paste `browser console log` when you try to upload a video

**Comment by GORF-Official** [comment]
We are having the same issue but only one account we have found so far.  Can't determine how this account is different than any others but the same problem as this user explained.

**Comment by quentinDupont** [comment]
I had the same issue but it was resolved by launching script from important notes of v4.2.0 https://github.com/Chocobozzz/PeerTube/blob/develop/CHANGELOG.md#important-notes-2= : `cd /var/www/peertube/peertube-latest && sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production node dist/scripts/migrations/peertube-4.2.js` :tada:

**Comment by dadall** [comment]
@quentinDupont Merci ! <3
