### ISSUE TITLE
Allow bigger avatar images for better og:image meta compatibility

### ISSUE THREAD

**Issue by Mike35538** [Chocobozzz/PeerTube#5077]
### Describe the problem to be solved

The channel & account avatars are 120x120 pixels. When you post the channel or account URL in Facebook for example the og:image tag is unusable because the avatar image is too small. So the image can't be retrieved and used by Facebook.

If you scrape the channel or account URL in Facebook Dev: https://developers.facebook.com/tools/debug/

You get an error like:
Provided og:image URL, https://pt-instance-site.com/lazy-static/avatars/5b28bf2b-a1ed-6229-9036-96ffd17b72w.jpg was not valid because it did not meet the minimum size constraint of 200px by 200px.

### Describe the solution you would like

Allow higher resolution avatar images to be uploaded and saved, for example 600x600. 
Maybe save a couple different sizes:
5b28bf2b-a1ed-6229-9036-96ffd17b72w-120x120.jpg
5b28bf2b-a1ed-6229-9036-96ffd17b72w-600x600.jpg

On the channel & account pages display the 120x120.jpg size but in the og:image tag use the 600x600.jpg version.

Thanks!

**Comment by Chocobozzz** [comment]
Hi,

We now provide the max avatar resolution in opengraph tags (currently 1500x1500).
