### ISSUE TITLE
Cache chunks to upload in server to resume upload later

### ISSUE THREAD

**Issue by BlitDev** [Chocobozzz/PeerTube#5078]
### Describe the problem to be solved

If you start downloading a video and the internet connection is interrupted, the video download will continue as if nothing had happened (#3933)
However, if you close the PeerTube site, the download will be **permanently interrupted**.

### Describe the solution you would like

There must be a **cache** of Peertube **uploads**, while uploading videos, chunks **should be cached**, and if the upload is interrupted and **the user starts uploading a file with the same name again**, take the already uploaded chunks from the cache.
If the user does **not want to upload this file again**, the cache will be cleared within 7 days, or it can be done manually by the user through the settings.

**Comment by Chocobozzz** [comment]
Hello,

I'm not sure users would be happy to store a cache that can be multiple GB of size in their web browser during 7 days. And AFAIK there is no cache mechanism in web browsers that allow us to automatically purge the storage after a period if the user doesn't come back on the peertube instance.

**Comment by BlitDev** [comment]
> Hello,
> 
> I'm not sure users would be happy to store a cache that can be multiple GB of size in their web browser during 7 days. And AFAIK there is no cache mechanism in web browsers that allow us to automatically purge the storage after a period if the user doesn't come back on the peertube instance.

I meant that the cache of chunks should be stored on the PeerTube instance itself.

**Comment by BlitDev** [comment]
I have another suggestion. Give instance administrators the ability to change the cache limit for each user. I think 2-3 gigabytes will be enough for everyone by default, I was uploading a movie, there the series weighed 1.5-2.0 gigabytes.

**Comment by BlitDev** [comment]
Update:
![image](https://user-images.githubusercontent.com/79034202/178300153-7498b1d3-cb6b-4951-b488-5661cf153108.png)

Despite the fact that in issue #3933 resumable downloads were added, with a long network outage, the download still does not continue.

**Comment by Chocobozzz** [comment]
Implemented by https://github.com/Chocobozzz/PeerTube/pull/5224
