### ISSUE TITLE
Invalid signature problem in Docker installation

### ISSUE THREAD

**Issue by agbossi** [Chocobozzz/PeerTube#5079]
### Describe the current behavior

I have 2 instances, each one in its own domain. Domains are
https://abossi.tpredespeertube.com.ar
https://mine.gbarbieripederiva.com.ar/

I followed the Docker guide on https://docs.joinpeertube.org/install-docker. Both instances are running but when either of them tries to follow the other, the following error appears

I searched on similar posts but couldn't solve it. I don't know what to do
---
warn[6/25/2022, 10:13:46 PM] Signature from https://abossi.tpredespeertube.com.ar/accounts/peertube is invalid

{
  "parsed": {
    "scheme": "Signature",
    "params": {
      "keyId": "https://abossi.tpredespeertube.com.ar/accounts/peertube",
      "algorithm": "rsa-sha256",
      "headers": [
        "(request-target)",
        "host",
        "date",
        "digest"
      ],
      "signature": "YzjjDzv01fhOFqcTaU9SCEGcNeycx+tA6NSkfmoHCuKMVoghEOuc3JizUuhBYc8+Y9NFsbGpriAychRTr/IQFMiV/reyqaN0yoUgeGrGDPCs+WiaFYdlMlZ4OUTB1V6yzA4JPpbhZ8txfeEhwHhuxIl3SubSj2TW2OrbE464K4/kI9ngtdQpYmilji2Frd19tKiNUKD66lwwdpdnbt3YMzlA6VXhIna4bIvY+GQj5b7N8MXzxtiJ3D6M34rITOODaFZQgLZ2MISjYGQwUeQSh4US8vd386u+v9RDrXec/Y8WV3ND/zSmp+dLee7vxlSDBvHyURZTyDfiyly1OrgPSQ=="
    },
    "signingString": "(request-target): post /accounts/peertube/inbox\nhost: mine.gbarbieripederiva.com.ar\ndate: Sun, 26 Jun 2022 01:13:32 GMT\ndigest: SHA-256=cEGXJvbjLxWZ3yWL6wvGLy9KJBFh/EKq7QnuCbOOziM=",
    "algorithm": "RSA-SHA256",
    "keyId": "https://abossi.tpredespeertube.com.ar/accounts/peertube"
  }
}
---
The docker-compose.yml file is exactly as downloaded from the guide and .env has domain and db tweaked.

date command right before submitting shows:  sáb jun 25 23:00:07 -03 2022

### Steps to reproduce

1. From https://mine.gbarbieripederiva.com.ar/ admin page 
2. Federation -> following -> follow. 
3. Paste abossi.tpredespeertube.com.ar and press follow
4. Go to logs in abossi.tpredespeertube.com.ar and the error will be there

### Describe the expected behavior

id expect to be able to have instances follow each other

### Additional information

* PeerTube instance:
  * URL: https://abossi.tpredespeertube.com.ar
  * Version: 
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by agbossi** [comment]
Sorry, what I posted was what can be found on https://mine.gbarbieripederiva.com.ar jobs. 
This is in https://abossi.tpredespeertube.com.ar logs
`
{   "uri": "https://mine.gbarbieripederiva.com.ar/accounts/peertube/inbox",   "signatureActorId": 1,   "body": {     "type": "Accept",     "id": "https://abossi.tpredespeertube.com.ar/accepts/follows/4/1",     "actor": "https://abossi.tpredespeertube.com.ar/accounts/peertube",     "object": {       "type": "Follow",       "id": "https://mine.gbarbieripederiva.com.ar/accounts/peertube/follows/4",       "actor": "https://mine.gbarbieripederiva.com.ar/accounts/peertube",       "object": "https://abossi.tpredespeertube.com.ar/accounts/peertube"     }   },   "contextType": "Accept" }
--
HTTPError: Response code 403 (Forbidden)     at Request.<anonymous> (/app/node_modules/got/dist/source/as-promise/index.js:117:42)     at runMicrotasks (<anonymous>)     at processTicksAndRejections (node:internal/process/task_queues:96:5)
`

**Comment by Chocobozzz** [comment]
Hello,

Your instances are not responding so I cannot test federation

**Comment by agbossi** [comment]
Sorry, had a network issue. Should be accessible now

**Comment by Chocobozzz** [comment]
From what I can see there is no error on your instances. I can follow them, and they can follow me. I suggest to retry the follows, actors keys should have been refreshed.

**Comment by JohnXLivingston** [comment]
I have similar warnings on (at least) one of my instance. It is not a docker installation, its a manual installation on a Debian.

I just updated from 4.2.2 to 4.3.0-RC1. I then go to see if there was some error logs, and I discovers such warnings. Some prior to the upgrade, some after.

Before:

```log
warn[18/09/2022 18:06:28] Signature from https://video.blast-info.fr/accounts/peertube is invalid

{
  "parsed": {
    "scheme": "Signature",
    "params": {
      "keyId": "https://video.blast-info.fr/accounts/peertube",
      "algorithm": "rsa-sha256",
      "headers": [
        "(request-target)",
        "host",
        "date",
        "digest"
      ],
      "signature": "G/6btL7yykiQsILF/FhDuxqcdRNxbAm61rzwTPubnC0/WMLX96X97AjeEni/qAK7JkqeR10stNtRiScc0c5uc4+MfolPX5zcA/wRJHdFZA2Zplu3fuoyNaOHE2UJBMDXfyoznye1ldA22e19sZyQMn1xLU53xatiyOlpliU0z1ZGv/fkqENoG4Hnq+geN8N+OBZkhIAr8CVwVQcBgpTn2RzsMz45R9Kq2S+4XC4H6YPbvyXmhwyjsTh4X0GRoayMUItklLyRQJ0fAg+8QvvkpcuHB8redextMe5+mEDUXbQ62HEMQqFnWQ0I+df8dtaeim84jnChgRdikx380gyyZw=="
    },
    "signingString": "(request-target): post /inbox\nhost: videos.john-livingston.fr\ndate: Sun, 18 Sep 2022 16:06:28 GMT\ndigest: SHA-256=zL4oRCx8CM4etW382yFRQhVEMwTpEEPHtM9YsJnRhPQ=",
    "algorithm": "RSA-SHA256",
    "keyId": "https://video.blast-info.fr/accounts/peertube"
  }
}

warn[18/09/2022 18:07:46] Signature from https://www.videos-libr.es/accounts/peertube is invalid

{
  "parsed": {
    "scheme": "Signature",
    "params": {
      "keyId": "https://www.videos-libr.es/accounts/peertube",
      "algorithm": "rsa-sha256",
      "headers": [
        "(request-target)",
        "host",
        "date",
        "digest"
      ],
      "signature": "eCrd0lupJxbCMQKRzu6tNrEOm4GBYHkpITZdeG1sq8o+CMbZtDyyMBQIyENcZy/LYvKkmWpRjx7JkSydu5XYKgyKDevQEjzIq/gwGaIDC4eELzLDloaKCaBhwyqdBRMhLCFoU1lHBmR82Wu6IhNCCpCIPORnNm6MQqGpSIV3Ghk2jGS4Tlxzi1yUJK54xlXd+3+7sNU4ABtFGH0ddR1rQiJJEqvDplkSDWSnhTIuNvo91jV2YpQAyrNkI1HO/XzF2yvuLFXKpYxdBhWCcm+JSaqQS1a77Lq6F+nYed2PBa2WKS/LN4dLfmSjpdOQg7kKVMiht6H/3jhshOGqnpjAUQ=="
    },
    "signingString": "(request-target): post /inbox\nhost: videos.john-livingston.fr\ndate: Sun, 18 Sep 2022 16:07:46 GMT\ndigest: SHA-256=5QXnTJIptTG3aMmnBGmSYZn7yi8PID6GeXJ8OD+/h6o=",
    "algorithm": "RSA-SHA256",
    "keyId": "https://www.videos-libr.es/accounts/peertube"
  }
}
```

After:

```log
warn[18/09/2022 18:28:11] Signature from https://video.blast-info.fr/accounts/peertube is invalid

{
  "parsed": {
    "scheme": "Signature",
    "params": {
      "keyId": "https://video.blast-info.fr/accounts/peertube",
      "algorithm": "rsa-sha256",
      "headers": [
        "(request-target)",
        "host",
        "date",
        "digest"
      ],
      "signature": "BEc2RdwKDaZdb0vw/tr0MzXQGIO2TJZaBj2TEmQLtYRE7tr33s3ye2C0gnqLwa2orqcMCHccXf200ZH4KuSXO/NvI/ldmn9GE0p/fNpqhhF9ac+rIOFYWQRletVh1IOvJLW96xQpIsETD2+sAw4ItW0/HT/ZWdRVKU7pILL3hDwsp74WeygPkWM/DZhQXxauaS1X2nP3sX9Co27S3OFg0R0M4PM5tgOF7uAP/uiyv9xqbqevOVbC9SGVKzPhp1kgjYYDpeH+oyykCHUHent7Pvc1D4jA0/i6XN08yTRis3lAodlOA3mhMePjyA2M0Vjg8Xs/l89MPmUhZeCgSpcLqw=="
    },
    "signingString": "(request-target): post /inbox\nhost: videos.john-livingston.fr\ndate: Sun, 18 Sep 2022 16:28:11 GMT\ndigest: SHA-256=m7RxdSI3PQtZnVfRG/DoryWEQ1v3sL36s+5qjLS9qAk=",
    "algorithm": "RSA-SHA256",
    "keyId": "https://video.blast-info.fr/accounts/peertube"
  }
}

warn[18/09/2022 18:28:43] Signature from https://video.blast-info.fr/accounts/peertube is invalid

{
  "parsed": {
    "scheme": "Signature",
    "params": {
      "keyId": "https://video.blast-info.fr/accounts/peertube",
      "algorithm": "rsa-sha256",
      "headers": [
        "(request-target)",
        "host",
        "date",
        "digest"
      ],
      "signature": "i9itELmKZVJTSOns+USRwsnyidtHb4J2UgqhS8i/N8gHX8tESxYEZdP8hHxu2dKpIFYB0Y6NqCLZT83hx+iO2SZInCKG8KBmsTqZFfMCuciYhUjN40isCg8JPlpOhuSywSLhONdZYueVq8cnx4DnxlgXEt2vUpMT0NxUCUeaf1pwvCdIQzMHT32F2AsMhHyF3wXoe0bCliSJIAYChDg9VSIArj7GKoFQZSFh30rHZUvLqf8DXb9YM5H7e5gm65dQJgI2wbVUUsMYrd3A5EsnOdjMQfA5BnZFAT0IqkNG5PY5p7MjfqZtrBlB39OJgfVV9xEuIoq65Xpaj5QGk+o9vw=="
    },
    "signingString": "(request-target): post /inbox\nhost: videos.john-livingston.fr\ndate: Sun, 18 Sep 2022 16:28:43 GMT\ndigest: SHA-256=puaz5H8Ikn9aispX85R8s4SizcDMc52Dr+9Nk95GDyw=",
    "algorithm": "RSA-SHA256",
    "keyId": "https://video.blast-info.fr/accounts/peertube"
  }
}
```


I have such logs for differents remote instances. I can't tell when it started, it seems it started a long time ago.

I did not notice any federation issue. I can see remote videos, and I even received notification for new videos on one of them this morning.

Maybe these warnings are false warnings?

**Comment by Chocobozzz** [comment]
Prior 4.3, PeerTube may **send** incorrect HTTP signature. It should be progressively fixed in the future when admin will upgrade their instance.
