### ISSUE TITLE
Theme error in nightly builds

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5080]
### Describe the current behavior

A nightly build of version 4.2.1 is installed on the test server-nightly-2022-06-26 .
If you activate themes
Borked
Dark - Official theme

An error appears

> warn[26.06.2022, 10:23:04] Incorrect request parameters
> {
>   "path": "/api/v1/users/me",
>   "err": {
>     "theme": {
>       "value": "Borked",
>       "msg": "Should have a valid theme",
>       "param": "theme",
>       "location": "body"
>     }
>   }
> }
> warn[26.06.2022, 10:35:47] Incorrect request parameters
> {
>   "path": "/api/v1/users/me",
>   "err": {
>     "theme": {
>       "value": "Dark",
>       "msg": "Should have a valid theme",
>       "param": "theme",
>       "location": "body"
>     }
>   }
> }

### Steps to reproduce

1. Install the theme
2. Activate
3. Get an error

### Additional information

* PeerTube instance:
  * URL: https://video.ustim.ru
  * Version: 4.2.1-nightly-2022-06-26
  * NodeJS version: v16.15.1

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/00fe5d61369b1769c62686e5bd8e6e666f867598
