### ISSUE TITLE
Document how to use metrics

### ISSUE THREAD

**Issue by drym3r** [Chocobozzz/PeerTube#5081]
### Describe the desired information/correction

There's the `/api/v1/server/stats` endpoint which returns a lot of useful metrics about how is Peertube running, but there's no information on how to use it. 
Would you like to add a page under `Peertube logs` called `Peertube metrics`, and there how to use them with the different possible solutions? 
If so, I could add the section of how to use them with Prometheus, the json-exporter and a Grafana dashboard, which is the stack I use. But it would be done in a way that could be expanded to add other solutions.

**Comment by drym3r** [comment]
Related to this, there's this issues:
- https://github.com/Chocobozzz/PeerTube/issues/3742
- https://github.com/Chocobozzz/PeerTube/issues/4532

**Comment by Chocobozzz** [comment]
Hi,

Yes it's a good idea.

**Comment by Chocobozzz** [comment]
Hello,

We added a documentation for OpenTelemetry with a Grafana dashboard template on https://docs.joinpeertube.org/maintain-observability
