### ISSUE TITLE
Feeds fail to build when a livestream is active

### ISSUE THREAD

**Issue by Sakrecoer** [Chocobozzz/PeerTube#5082]
### Describe the current behavior

When a live stream is active, the feeds fail to build and return a 500

### Steps to reproduce

1. Start a live stream
2. Wait until the feeds rebuild (media RSS2.0, JSON and atom)
3. Open a feed
4. Error 500 displayed:

```
{"type":"https://docs.joinpeertube.org/api-rest-reference.html#section/Errors/TypeError","detail":"Cannot read property 'url' of undefined","status":500,"code":"TypeError","error":"Cannot read property 'url' of undefined"}
```

### Describe the expected behavior

1. Start a live stream
2. Wait until the feeds rebuild (media RSS2.0, JSON and atom)
3. Open a feed
4. Feed is available
```

### Additional information

* PeerTube instance:
  * URL: v.basspistol.org
  * Version: 4.2.1
  * NodeJS version: v14.19.3
  * Ffmpeg version: 4.2.7-0ubuntu0.1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

```
{"err":"TypeError: Cannot read property 'url' of undefined\n    at addVideosToFeed (/var/www/peertube/versions/peertu
be-v4.2.1/dist/server/controllers/feeds.js:224:36)\n    at /var/www/peertube/versions/peertube-v4.2.1/dist/server/con
trollers/feeds.js:117:9\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v
4.2.1/node_modules/tslib/tslib.js:114:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (inte
rnal/process/task_queues.js:95:5)","level":"error","message":"Error in controller.","label":"v.basspistol.org:443","t
imestamp":"2022-06-27T07:56:21.223Z"}
```

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/41e74ec9cd6076109c91128047d8b866c36a3005

**Comment by Sakrecoer** [comment]
:tada: You rock!!!
