### ISSUE TITLE
Incorrect command in Production.md Directions

### ISSUE THREAD

**Issue by davkastheranger19** [Chocobozzz/PeerTube#5085]
### Describe the desired information/correction

In the following section:
To generate the certificate for your domain as required to make https work you can use [Let's Encrypt](https://letsencrypt.org/):

$ sudo systemctl stop nginx
$ sudo certbot certonly --standalone --post-hook "systemctl restart nginx"
$ sudo systemctl reload nginx

Now you have the certificates you can reload nginx:

$ sudo systemctl reload nginx

The line $ sudo certbot certonly --standalone --post-hook "systemctl restart nginx"
$ sudo systemctl reload nginx

Should be $ sudo systemctl start nginx

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I don't understand: what specific command should be replaced by ``sudo systemctl start nginxN
