### ISSUE TITLE
Save filter conditions in Recently Added and Hot Videos

### ISSUE THREAD

**Issue by fweng322** [Chocobozzz/PeerTube#5087]
### Describe the problem to be solved

There are a lot videos in the Recently Added and Hot Videos so I would like to add some filter conditions (like languages) to find out related videos.  However every time I need to repeatedly set the same condition.  I'd like to add a feature to save the condition and give it a name (and one account can have certain number tags for saved conditions) so that I can easily find videos with the same conditions.  (Something similar to bugzilla search)

### Describe the solution you would like

When specifying filter conditions users can save these conditions and give it a name, which will be shown in the filter row.

**Comment by Chocobozzz** [comment]
Hello,

Thanks for this issue but it would complexify peertube ui. Instead, I suggest to create web browser bookmarks since we inject filters in URL.
