### ISSUE TITLE
User interface update LDAP

### ISSUE THREAD

**Issue by hellosct1** [Chocobozzz/PeerTube#5088]
### Describe the problem

Hi, 

I followed the following [link](https://github.com/Chocobozzz/PeerTube/issues/2857) and the update of the account is done manually with the command

`update "user" set "pluginAuth" = 'peertube-plugin-auth-ldap' where username = $username;`

is there a way to update the account from the interface or through the user profile

Thanks

**Comment by Chocobozzz** [comment]
Hi,

Yes, you should be able to change the auth method for a user in `Administration -> Overview -> Users -> Update`

![screen_2022-06-28-11:59:25](https://user-images.githubusercontent.com/5180488/176151862-0ba521ad-319e-4b89-88cc-87502d2f1bce.png)
