### ISSUE TITLE
Inject HTML elements in channel related pages (create/update/detail)

### ISSUE THREAD

**Issue by raazkarkee405** [Chocobozzz/PeerTube#5089]
### Describe the problem to be solved

Currently, I am trying to inject some HTML into create/update channel & channel detail page. I was able to inject the HTML using the plugin.

To inject the HTML elements I have used document.onreadystatechange event (Fires when the state of the object has changed) event of DOM in create channel page. I am using this event because I cannot append elements before the DOM loads and this event is fired when DOM has completed loading.
The drawback of using this event is the injected elements load only once. If we came to that path from other paths the elements do not get injected and in order to inject them, we have to refresh the page.

Is there a way to inject HTML in desired pages or do I need to use any hooks to inject HTML?

### Describe the solution you would like

Since I want to inject HTML in channel-related pages using the plugin, a client-side hook if available would solve my issue.

**Comment by Chocobozzz** [comment]
Hi,

I added channel hook in https://github.com/Chocobozzz/PeerTube/commit/9ca0f688e9e8558233f1a538b96a43da44e35353

```
  // Fired when the video channel creation page is being initialized
  'action:video-channel-create.init': true,

  // Fired when the video channel update page is being initialized
  'action:video-channel-update.init': true,
  'action:video-channel-update.video-channel.loaded': true,

  // Fired when the page that list video channel videos is being initialized
  'action:video-channel-videos.init': true,
  'action:video-channel-videos.video-channel.loaded': true,
  'action:video-channel-videos.videos.loaded': true,

  // Fired when the page that list video channel playlists is being initialized
  'action:video-channel-playlists.init': true,
  'action:video-channel-playlists.video-channel.loaded': true,
  'action:video-channel-playlists.playlists.loaded': true,
```
