### ISSUE TITLE
More interesting homepage

### ISSUE THREAD

**Issue by andzdroid** [Chocobozzz/PeerTube#509]
I'd like the homepage to be a distinct page from the Trending/Recent/Local pages, which are just a plain grid of videos.

Using youtube as an example, they show a small selection of trending videos, a small selection of recent videos, videos from your subscriptions, recommended videos based on your view history, etc.

This makes the homepage unique for logged-in users, and gives a better idea of what's on this site for new users.

**Comment by rigelk** [comment]
Related to #757 - just to keep track of things :)

**Comment by Chocobozzz** [comment]
I would like to create an interesting homepage, in which we would list latest videos, some interesting categories or tag etc. But I would need some help on the design:
 * Do we do something like youtube with different sections: https://www.youtube.com/
 * Or like d.tube/dailymotion with lines we can browse: https://d.tube/ https://www.dailymotion.com
 * ...?

**Comment by andzdroid** [comment]
We don't use arrows for scrolling anywhere else in peertube, so I prefer the youtube grid look because it's more consistent with the existing design.

**Comment by bradsk88** [comment]
I did some thinking about recommendations last night.  I'm new to the PeerTube system and it's just a first draft, want to throw it out there just in case someone else is also actively investigating this concept:

https://github.com/bradsk88/peertube-recommendations/wiki

**Comment by mattcoxonline** [comment]
![image](https://user-images.githubusercontent.com/673542/44795449-fe0f3680-abaa-11e8-9d8b-0871f52e6dd4.png)

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/2d3741d6d92e9bd1f41694c7442a6d1da434e1f2 (PR: https://github.com/Chocobozzz/PeerTube/pull/986)

It's just a first version, so don't hesitate to create other issues if you have interested ideas :)

(Just for information, I linked the @bradsk88 and @mattcoxonline comments in their appropriate issues)
