### ISSUE TITLE
Error during Torrent file import

### ISSUE THREAD

**Issue by BlitDev** [Chocobozzz/PeerTube#5093]
### Describe the current behavior

Error:
```
Incorrect request parameters: torrentfile
```
I think it's because of the torrent file name (it's too complicated), but any torrent clients like Deluge-Gtk or qBittorrent download it without problems.

### Steps to reproduce

1. Click **Publish**
2. Try importing a .torrent file
3. See the error

### Describe the expected behavior

Normal file import

### Additional information

* PeerTube instance: Peerlook
  * URL: https://peerlook.ru/
  * Version: 4.2.2
  * NodeJS version: ?
  * ffmpeg version: ?

* Browser name, version and platforms on which you could reproduce the bug: Chromium, Firefox
* Link to browser console log if relevant: ?
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): ?

**Comment by BlitDev** [comment]
> Hi.
> 
> Why are you thinking it's bound to your torrent name? What's your torrent name?

Sorry, I forgot to add a name.
Name: 歷 Mr. Robot Mr. Robot Season 1-4 Episodes 1-45 (Sam Esmail, Jim McKay, Tricia Brock) [2015-2019, USA, drama, crime, WEB-DL [rutracker-5744512].torrent
However, even if you change the file name, nothing changes (it seems like there is the name of the torrent itself, not the file)

**Comment by Booteille** [comment]
What are files inside the torrent? Are there some non-video files?

**Comment by BlitDev** [comment]
> What are files inside the torrent? Are there some non-video files?

![image](https://user-images.githubusercontent.com/79034202/177138623-7d6ce6ea-2511-49f8-8218-10f80807bc90.png)
4 folders, each with 10 episodes in .mkv format

**Comment by BlitDev** [comment]
> I don't think PeerTube is able to handle many videos in one torrent files.
> 
> Try with a torrent having only one movie file, it should work I think.

Most of the series are distributed in the form of several episodes, you need to think of something about it. So that a menu appears with the selection of the desired video file.

**Comment by Booteille** [comment]
> > I don't think PeerTube is able to handle many videos in one torrent files.
> > Try with a torrent having only one movie file, it should work I think.
> 
> Most of the series are distributed in the form of several episodes, you need to think of something about it. So that a menu appears with the selection of the desired video file.

Well. That's just to answer to your issue. (If you think I did it properly, please, think about closing this issue)

If you think a feature is missing in PeerTube, you can propose it in another ticket, though I don't think importing a whole serie is in the scope of PeerTube.
Instead, you could develop a plugin allowing you to do whatever you need.
