### ISSUE TITLE
Handle redis connection failure gently

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5095]
### Describe the problem to be solved

We had an issue with our redis server (ReplyError: LOADING Redis is loading the dataset in memory) that made it impossible to connect with it. Because of that PeerTube crashed and restarted, time after time.

### Describe the solution you would like

PeerTube should be able to continue to run with degraded capabilities when redis connection fails.

One solution could be:
* A flash message is shown on all the pages; "This instance is running with degraded capabilities, it may not work as expected."
* An email is sent to the site administrators telling the status.

A more advanced solution, which may be too complex:
* All user interaction (login, comment, video upload, etc) is disabled to ensure no data is lost (emails, transcoding jobs, etc).

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but it would be too complicated. PeerTube requires redis to run, like it requires postgresql. If one of these components doesn't work, peertube can't work.

**Comment by kontrollanten** [comment]
Would it be an option to support Redis to load the dataset in memory during start? By setting [enableReadyCheck](https://github.com/luin/ioredis#connection-events) to true and listen for the `ready` event that should be possible.

**Comment by kontrollanten** [comment]
In our case restarts (during 12 hours) didn't help. But now when I think further the enableReadyCheck probably wouldn't have changed that since Redis was probably stuck for some reason.

**Comment by Chocobozzz** [comment]
I'll test it when I'll time and will update this thread :)

**Comment by Chocobozzz** [comment]
Should not crash anymore with https://github.com/Chocobozzz/PeerTube/commit/ab08ab4e284ad145de64ff9e1c9cf8149f701e29
