### ISSUE TITLE
[4.2.2] not working when  privacy set to 2  ( unlisted ) in files config/default.yaml

### ISSUE THREAD

**Issue by WilliamFromTW** [Chocobozzz/PeerTube#5096]
### Describe the current behavior

defaults:
  publish:
...
    # public = 1, unlisted = 2, private = 3, internal = 4
    **privacy: 2**

### Steps to reproduce

1. docker exec -it peertube bash
2. apt install vim
3. vi config/default.yaml
4. exit && docker restart peertube
5. http://peertube , login , upload video , but alway public by default

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Booteille** [comment]
Hi.

Could you please fill other parts of the template?
Having more informations about your setup could help us understand what's going on.

Also, I didn't understand what you you mean by "not working". What is not working? Have you errors? Can you join us your logs?

Thanks.

**Comment by WilliamFromTW** [comment]
Hi sir , 
i install peertube for private use , all settings is default value, 
but i need upload video by default "unlisted" , not "public"  , 
finally i found a parameter "privacy" 
in config/default.yaml  should work ,  but not , maybe this my fault  to modify wrong paramter.

![image](https://user-images.githubusercontent.com/5213198/177226081-5542c1ef-0416-4d4e-9078-a56b71f6854b.png)
 

![image](https://user-images.githubusercontent.com/5213198/177225568-23d7f884-33a2-46b9-b4b7-0dccf49fa871.png)

**Comment by WilliamFromTW** [comment]
Hi sir,
my config/  have product.yml.example only , it still the same , when i copy default.yaml to production.yml.

![image](https://user-images.githubusercontent.com/5213198/177438172-c0e9767b-2f0b-438c-aa90-a9c6cdcd1cde.png)

**Comment by Chocobozzz** [comment]
Hello,

You need to apply your configuration on the host in `docker-colume/config/production.yml`. I
