### ISSUE TITLE
Add ability to change ownership of a video

### ISSUE THREAD

**Issue by 22decembre** [Chocobozzz/PeerTube#510]
It would be cool if the admin of the instance and/or the owner of a video can «give it» to another user.

**Comment by gegeweb** [comment]
Hi,

Before this feature is implemented, there is a way to modify the video owner?
I would like to change the owner for the first videos uploaded on my instance.
I'm now on 1.0.0-beta.10.pre.2.

**Comment by grizio** [comment]
I tried to implement the feature. I stopped because there is lot of things to handle and some architectural decisions to be made.

Here a simple design of the feature:

![diagram of the process](https://user-images.githubusercontent.com/11132978/43358229-8836e01e-928e-11e8-9aed-ec2faaedac3d.png)

For each lane, it could have ActivityPub in the middle. So some questions arise:

* Should we accept to give the ownership through multiple instances?
* How to chose the user to give the video?
* How to handle cases when the video is removed from first server and some users watch it?

<details>
  <summary>PlantUML code of diagram</summary>

```puml
@startuml
|Current owner|
start
:Send invitation;

|Next owner|
if (accepts) then (no)
  |Next owner|
  :Send refusal;
  |Current owner|
  :Save refusal;

  stop

else (yes)
  |Next owner|
  :Choose channel;
  :Send acceptation;

  |Current owner|
  :Send video file;

  |Next owner|
  :Save video file;
  :Publish (or not?);

  |Current owner|
  :Remove video file locally;

  stop

endif
@enduml
```
</details>

**Comment by rigelk** [comment]
@grizio ah indeed, I didn't notice you had already begun working on the issue. I'm marking it as already in progress then.

To answer your questions, I think - but @Chocobozzz might want to interject - that we should clearly define the scope:

- for now the model imposes a unique owner (for now). so giving the ownership effectively means transferring data and rights. as to wether this should only be local, I don't see why, but it sure would be simpler…
- giving the handle of that user should be enough.
- when the video is removed from the first server, doing a redirection (302) to the new server.

**Comment by grizio** [comment]
Yes, this could be split in two different features. I will simply start at local instance level.

However, about the change of ownership, it is not trivial, even it is pretty simple. The above schema is still valid minus the sending of the video.

The acceptance by the target user has several reasons:

* Avoid a user sending video to anyone and give all responsibilities (quota, respect of terms…) to them
* Let the user chose the channel to put the video in (and maybe create a new one beforehand)

But if the admin should have all rights, another feature could be created so he can send directly to the user channel.

I continue with this scenario. If you do not agree, do not hesitate to answer.

**Comment by Chocobozzz** [comment]
Implemented by @grizio in https://github.com/Chocobozzz/PeerTube/commit/74d63469355bad731cdd32defdc85913df3cbd5c

**Comment by MathiasRenner** [comment]
Thank for this nice feature! Will the view count stay the same after you changed the ownership of a video?

**Comment by rigelk** [comment]
@MathiasRenner yes.

**Comment by MathiasRenner** [comment]
@rigelk Super nice, thanks! And will the link/URL to the video stay the same after having changed ownership?

**Comment by JohnXLivingston** [comment]
> @rigelk Super nice, thanks! And will the link/URL to the video stay the same after having changed ownership?

Yes.
