### ISSUE TITLE
Allow admin to remove user's profile picture

### ISSUE THREAD

**Issue by dausruddin** [Chocobozzz/PeerTube#5100]
### Describe the problem to be solved

Sometimes user are using profile picture that is against the rules.
Unfortunately we admin cannot remove them.

### Describe the solution you would like

Admin should be able to remove their profile picture.

Would be great if we can include a reason too, so user will get a notification on why their profile picture is being removed.
Since we can't PM a user (https://github.com/Chocobozzz/PeerTube/issues/2513), a reasoning system is a good way to moderate better.

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/6618
