### ISSUE TITLE
Temporary banning

### ISSUE THREAD

**Issue by dausruddin** [Chocobozzz/PeerTube#5101]
### Describe the problem to be solved

Not all situations are suitable for permanent ban.
Having an option for temporary banning a user would be really great.

### Describe the solution you would like

Ability to ban a user temporarily.
A tracker would be great too, so we can keep track of their ban history.

**Comment by dausruddin** [comment]
Let say someone posting an offensive comment, which is againt the rules. I want to temporary banning them let say for 5 hours.

Or when someone upload video that outside of scope of my instance allowing. I want to remind him to follow the rules, by giving a few hours ban.

Different case would be different duration.

**Comment by Nalem14** [comment]
If you need, I have made a plugin "orion-moderation-tools" that permit to make temp. ban per channel. (deny access to the channel and auto blacklist all of theses videos during the ban)

I have plan to also make temp. ban of the account. (and also do the same thing with all theses channels/videos)

**Comment by dausruddin** [comment]
Sorry for the delay. That is a quite nice plugin. I'm happy to hear about your future plan for this plugin. I'll be waiting for that.

**Comment by Nalem14** [comment]
> Sorry for the delay. That is a quite nice plugin. I'm happy to hear about your future plan for this plugin. I'll be waiting for that.

Hi, I just released the v1.1.0 on NPM who add Temp. account ban :)
Let me know if your have any issue.

https://www.npmjs.com/package/peertube-plugin-orion-moderation-tools

**Comment by dausruddin** [comment]
@Nalem14 your plugin is working fine as far as I tested.

I'm going to close this as my request is fulfilled. Looking forward for any additional feature that will be implemented in the future, probably reason field for why they got banned :)

Thanks a lot!

**Comment by Nalem14** [comment]
> @Nalem14 your plugin is working fine as far as I tested.
> 
> 
> 
> I'm going to close this as my request is fulfilled. Looking forward for any additional feature that will be implemented in the future, probably reason field for why they got banned :)
> 
> 
> 
> Thanks a lot!

Yes I will add reason field later :)
