### ISSUE TITLE
Paid subscribers

### ISSUE THREAD

**Issue by ncamacho97** [Chocobozzz/PeerTube#5104]
### Describe the problem to be solved

so basically having a feature or plugin that allows a content creator the ability to have paid videos  

### Describe the solution you would like

users that pay can user the videos

**Comment by Booteille** [comment]
Hi.

This is a duplicate of #1586.

You can discuss there about monetization options.
For now, monetization is out of scope of PeerTube but any plugin addressing this problem is welcomed.
