### ISSUE TITLE
new video slow to start + cuts

### ISSUE THREAD

**Issue by ddeenniiss** [Chocobozzz/PeerTube#5105]
### Describe the current behavior

Since the update to version 4.2, the new videos uploaded are sometimes slow to start or with micro-cuts

### Steps to reproduce

1. Test here for a new video https://videos.domainepublic.net/w/qPC8veH3uqbfwFf8f3f2Q2
2. Compare to an old video https://videos.domainepublic.net/w/2Xgr5czopMUx9TZvooUvRv

### Additional information

* PeerTube instance:
  * URL: https://videos.domainepublic.net
  * Version: peertube-v4.2.0
  * NodeJS version:14.19.3-deb-1nodesource1
  * Ffmpeg version: 10:4.4-dmo4+deb11u3

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

There is a bug in ffmpeg 4.4.0. Please upgrade to 4.4.1 or downgrade to 4.3.x and rerun transcoding on broken videos.
