### ISSUE TITLE
Groups do not work in the official auth-ldap plugin

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5112]
### Describe the current behavior

I created a topic on the [forum](https://framacolibri.org/t/error-or-incorrect-configuration-of-the-auth-ldap-plugin/15206), it's a pity that there is a very long time to wait for an answer.

I have installed the official auth-ldap plugin for authorization from Active Directory.
Users who are in the domain can log in to the Pertube instance without problems, while they become default Users.

Then I created 3 groups in Active Directory and changed the plugin settings

Group base
`OU=PeerTube,OU=Groups,OU=Service Accounts,DC=domain,DC=local`

Group filter
`(objectCategory=Group)`

Administrator group DN
`CN=domain-sg-videoadmins,OU=PeerTube,OU=Groups,OU=Service Accounts,DC=domain,DC=local`

Moderator group DN
`CN=domain-sg-videomoderators,OU=PeerTube,OU=Groups,OU=Service Accounts,DC=domain,DC=local`

User group DN
`CN=domain-sg-videousers,OU=PeerTube,OU=Groups,OU=Service Accounts,DC=domain,DC=local`

But any changes in user groups do not affect Peertube users in any way. I want to understand, is this a plugin error or is it my mistake?

I noticed one feature… If the user is a domain administrator, then when logging in to Peertube, he also becomes an instance administrator. At the same time, the user does not belong to AD groups at all:
domain-sg-videoadmins
domain-sg-videomoderators
domain-sg-videousers

### Steps to reproduce

1. Install the plugin
2. Configure the plugin, as well as configure the group fields
3. Groups do not apply

### Describe the expected behavior

Groups should work correctly

### Additional information

* PeerTube instance:
  * URL: Corporate
  * Version: 4.2.2

**Comment by Chocobozzz** [comment]
Hello,

Please don't create duplicate posts since you already created a post on the forum. Moreover you may want to create an issue on [the LDAP plugin repository](https://framagit.org/framasoft/peertube/official-plugins/-/issues)
