### ISSUE TITLE
Option to set initial privacy of a new live replay

### ISSUE THREAD

**Issue by Mike35538** [Chocobozzz/PeerTube#5113]
### Describe the problem to be solved

Some live streaming users like to save a replay and publish it later. Currently the live replay takes the privacy status of the original live video. So if the live video is public, the replay will also default to public. However users don't always want the live video replays to immediately become public after they are processed by the instance. Sometimes they will trim it in Studio first and then make it public. Currently users live stream and then wait for the replay to become available in their library then they can change the privacy to private. But if they leave for awhile because the instance is still processing the replay then when the processing is done the replay is automatically public for everyone until the user gets back later and makes it private.

### Describe the solution you would like

Add an option to set the initial privacy of the replay. You could add the option under the replay settings under live settings like in the mock up below.

![replay-privacy](https://user-images.githubusercontent.com/104943871/178069290-deaa1985-97e2-47c5-b900-c50876840823.jpg)

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/5692 by @wickloww :sparkles:
