### ISSUE TITLE
Rendering issues on mobile device

### ISSUE THREAD

**Issue by xundeenergie** [Chocobozzz/PeerTube#5116]
### Describe the current behavior

There are some dropdowns in Admin-section, which are unusable on mobile devices.

![Screenshot_20220709_165837](https://user-images.githubusercontent.com/5894829/178111381-607212fe-92e9-4c57-91e0-d77e44d7d38a.jpg)

See the marked one for example on "basic settings"

All of them are broken like this in the basic-settings page

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL: kino.schuerz.at
  * Version: 4.2.2
  * NodeJS version: ?
  * Ffmpeg version: ?

* Browser name, version and platforms on which you could reproduce the bug: firefox android
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/21d8979fbdbc26067f2ed19efa30060c44b3b102
