### ISSUE TITLE
Broken settings page

### ISSUE THREAD

**Issue by xundeenergie** [Chocobozzz/PeerTube#5117]
### Describe the current behavior

When i klick to "Administration" i'm led to the Users overview.
When i try to change to "federation" or "moderation, i get this
![Screenshot_20220709_165927](https://user-images.githubusercontent.com/5894829/178111513-81827a87-33e4-4279-9551-88d3e3576227.jpg)

When i change to "Settings" and then back to Federation, i get this (how it should!)
![Screenshot_20220709_170040_org mozilla firefox](https://user-images.githubusercontent.com/5894829/178111559-b590a1bf-56d5-4473-8196-f5a22a7202b9.jpg)

So i found out, the changing of tab in administration ist only broken from users overview. 

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL: kino.schuerz.at
  * Version: 4.2.2
  * NodeJS version: ?
  * Ffmpeg version: ?

* Browser name, version and platforms on which you could reproduce the bug: all plattforms
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

What is your phone OS? And web browser?

**Comment by Chocobozzz** [comment]
Please paste web browser console log on desktop

**Comment by xundeenergie** [comment]
> Please paste web browser console log on desktop

I'm on holydays... will paste it, when i'm home.

**Comment by xundeenergie** [comment]
In Firefox Developer-Console i get permanently this error:
```
ERROR TypeError: K is undefined
    Angular 7
    C actor-avatar.component.html:4
    Angular 54
    RxJS 6
    Angular 18
    RxJS 12
    Angular 17
    RxJS 11
    
```

almost every second. Even if i click nothing, when I'm on "Overview -> Users".
Changing to "Configuration" the errors are stopping and the output is once:
```
Running hook action:router.navigation-end of plugin custom-links. [plugins-manager.ts:111:14](webpack:///src/root-helpers/plugins-manager.ts)
Running hook action:router.navigation-end of plugin livechat. [plugins-manager.ts:111:14](webpack:///src/root-helpers/plugins-manager.ts)
Running hook action:router.navigation-end of plugin social-sharing. [plugins-manager.ts:111:14](webpack:///src/root-helpers/plugins-manager.ts)
Running hook action:router.navigation-end of plugin custom-links. [plugins-manager.ts:111:14](webpack:///src/root-helpers/plugins-manager.ts)
Running hook action:router.navigation-end of plugin bittube-light-mode. [plugins-manager.ts:111:14](webpack:///src/root-helpers/plugins-manager.ts)
Running hook action:router.navigation-end of plugin livechat. [plugins-manager.ts:111:14](webpack:///src/root-helpers/plugins-manager.ts)
Running hook action:router.navigation-end of plugin social-sharing. [plugins-manager.ts:111:14](webpack:///src/root-helpers/plugins-manager.ts)
Running hook action:router.navigation-end of plugin bittube-light-mode. [plugins-manager.ts:111:14](webpack:///src/root-helpers/plugins-manager.ts)
```

**Comment by xundeenergie** [comment]
In Chrome the error exists too.
I get this in dev-tools console, when i'm on "overview -> users"

```
DevTools failed to load source map: Could not load content for https://kino.schuerz.at/plugins/tv-streaming/1.1.4/client-scripts/dist/common-client-plugin.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not parse content for https://kino.schuerz.at/plugins/main.css.map: Unexpected token < in JSON at position 0
core.mjs:6485 ERROR TypeError: Cannot read properties of undefined (reading 'trim')
    at z._toggleClass (common.mjs:2831:23)
    at common.mjs:2823:53
    at Array.forEach (<anonymous>)
    at z._removeClasses (common.mjs:2823:29)
    at set ngClass [as ngClass] (common.mjs:2750:14)
    at a_ (core.mjs:10979:22)
    at Lo (core.mjs:10023:9)
    at Object.Mu (core.mjs:14446:9)
    at C (actor-avatar.component.html:4:38)
    at Gh (core.mjs:9618:9)
mm	@	core.mjs:6485
handleError	@	core.mjs:6532
(anonymous)	@	core.mjs:26500
invoke	@	zone.js:372
run	@	zone.js:134
runOutsideAngular	@	core.mjs:25447
tick	@	core.mjs:26500
(anonymous)	@	core.mjs:26345
invoke	@	zone.js:372
onInvoke	@	core.mjs:25548
invoke	@	zone.js:371
run	@	zone.js:134
run	@	core.mjs:25402
next	@	core.mjs:26344
next	@	Subscriber.js:91
_next	@	Subscriber.js:60
next	@	Subscriber.js:31
(anonymous)	@	Subject.js:34
M	@	errorContext.js:19
next	@	Subject.js:27
emit	@	core.mjs:22427
dd	@	core.mjs:25470
onHasTask	@	core.mjs:25565
hasTask	@	zone.js:426
_updateTaskCount	@	zone.js:447
_updateTaskCount	@	zone.js:274
runTask	@	zone.js:195
W	@	zone.js:585
invokeTask	@	zone.js:491
x	@	zone.js:1648
Show 2 more frames
```

**Comment by Chocobozzz** [comment]
Can you list your instance users username?

**Comment by xundeenergie** [comment]
Sorry, i don't understand, what you mean.
The instance-user is peertube@kino.schuerz.at

What should i list?

**Comment by Chocobozzz** [comment]
> What should i list?

All your users usernames registered on your instance

**Comment by xundeenergie** [comment]
this are only 6 users. i have ldap and keycloak and closed registration.
but only one user @jakob@kino.schuerz.at is using this instance and has administration rights.

**Comment by xundeenergie** [comment]
I logged in as another administration-user... and the problem is the same as described above.

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/dbf49527172c6b97385481610786688effbe5c13
