### ISSUE TITLE
Better grouping of search results

### ISSUE THREAD

**Issue by xundeenergie** [Chocobozzz/PeerTube#5119]
### Describe the problem to be solved

I had a big issue with searching on my peertube-instance. 
I searched for channels. With url and handle... and got no result. I choose searching in vidiverse with configures sepiasearch-backend (search.joinpeertube.org). 

I have to open the "filter" and choose extra "channels"
![grafik](https://user-images.githubusercontent.com/5894829/178128226-80fae08d-bf81-412a-a13b-e7d5888d0df3.png)
to get a result for channel-search.

When i remove "&resultType=videos" from the search-url, no type is selected, and i get always the channel in result too.

### Describe the solution you would like

I think, it would be a very good idea to have a "All" radio-button for "result types" in the filter, which removes the "&resultType=" completely from the query-url. 

And a much better idea would be to have 3 tabs on search-results:
- videos
- channels
- playlists

and maybe users too... 
The headline of the tab should show the count of found results

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/e45dd87b93c621c606415f9e8d0d381de6d7a2d7
