### ISSUE TITLE
Scaling Peertube

### ISSUE THREAD

**Issue by ssadok** [Chocobozzz/PeerTube#5120]
### Describe the problem to be solved

It will be nice to scaling peertube, and especially now there is kubernetes and microservices.

### Describe the solution you would like

I found in internet an interesting architecture suggestion :
https://framacolibri.org/t/scaling-peertube/8317

![a666678f648000d96de10fc74c6e602fed5a19d0](https://user-images.githubusercontent.com/1891667/178160680-10f80acd-6e6b-44ca-aa20-8be0981b4905.jpeg)

It can be a way to begin.

Thanks.

**Comment by Chocobozzz** [comment]
Hello,

Can you explain the use case you want to solve?

**Comment by AlthaTechnology** [comment]
I think part of what they are talking about is architecting peertube to operate with each function able to be separated onto different hardware that can be purpose built for each activity. Then it can scale up better, in theory.

On this, I have been using an application called AVideo. The encoder can run on a separate server, then multiple AVideo instances can communicate with the same encoder. 

In my experience with AVideo, this broken apart architecture can end up cause some issue in having a reliable application overall. Sometimes the encoder breaks, sometimes the frontend, sometimes the livestreamer. You never know which is the problem, or it's difficult to troubleshoot.

The reason I am looking at peertube for my video hosting options is that it seems to be more simple and reliable. So I would think to scale up hardware to handle more load by increasing the power of my server, and then also federating with my own distributed peertube's.

For example, I would have an instance at: althapeertube.com which has 1000 videos. Then I would have a separate cloud instance that is: cdn1.althapeertube.com, that federates and shares using the built in replication strategy. Then if I need more bandwidth, and/or scale, I do that again with cdn2.althapeertube.com.

Does this work as a strategy in practice? I think one bottleneck is the encoder. The videos need to be encoded at the main server always. Maybe being able to allow for other instances to encode videos for other instances then transfer the files on off-hours or something would be cool. Sharing the compute in that way, as well as video delivery.

**Comment by Chocobozzz** [comment]
Hello,

With S3 support you can scale PeerTube storage. You'll also be able to scale encoder capacity with https://github.com/Chocobozzz/PeerTube/issues/947

**Comment by AlthaTechnology** [comment]
@Chocobozzz Ok, will look at that. Will also follow that issue. Thanks much!
