### ISSUE TITLE
A simple way to broadcasting of created playlists (P2P TV) ?

### ISSUE THREAD

**Issue by fwn0** [Chocobozzz/PeerTube#5121]
### Describe the problem to be solved

I did try some experiments with ffplayout, owncast and restreamer for broadcast live-stream of playlists with peer2be; it works technically, but streams are laggy, disconnected or broken. Is there some simple and intelligent way for broadcasting of playlists ?

**Comment by Chocobozzz** [comment]
Hello,

Please use [the forum](https://framacolibri.org/c/peertube/38) for peertube related questions
