### ISSUE TITLE
"loaded" in hooks doesn't mean it is completely loaded?

### ISSUE THREAD

**Issue by dausruddin** [Chocobozzz/PeerTube#5126]
### Describe the current behavior

I am writing a plugin to modify certain elements when the comments loaded.
Unfortunately my code cannot find element that I specified.

```
registerHook({
    target: 'action:video-watch.video-threads.loaded',
    handler: () => {


                var xp_admin_nm = "//span[contains(concat(' ', normalize-space(@class), ' '), ' comment-account-fid ')"
                var rs_admin_nm = document.evaluate(xp_admin_nm, document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);

                console.log(rs_admin_nm.snapshotLength);


    }
})
```

I found out that adding a delay work.

So, this is my test code that is working, with 1 second of delay.

```
registerHook({
    target: 'action:video-watch.video-threads.loaded',
    handler: () => {
        setTimeout(
            function () {
                var xp_admin_nm = "//span[contains(concat(' ', normalize-space(@class), ' '), ' comment-account-fid ')"
                var rs_admin_nm = document.evaluate(xp_admin_nm, document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);

                console.log(rs_admin_nm.snapshotLength);
            }
        , 1000);
    }
})
```

From what I understand, my code is executed before comments are loaded, which doesn't accurately follows its hook name 'action:video-watch.video-threads.**loaded**'

Adding a delay would fix it, but it will be ugly to users.
So is there any other way I could achieve what I want?

### Steps to reproduce

1. Make a plugin using the hook I wrote
2. Check console log to see how many elements it found.

### Describe the expected behavior

Hook triggered after comments are fully loaded.

### Additional information

* PeerTube instance:
  * URL: localhost
  * Version: 4.2.2
  * NodeJS version: docker
  * Ffmpeg version: docker

* Browser name, version and platforms on which you could reproduce the bug: Firefox, 102.0.1 (64-bit), Arch Linux
* Link to browser console log if relevant: N/A
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): N/A

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/d65cd16551449216f23d68a6238f7739bab34644
