### ISSUE TITLE
Stream Key change 

### ISSUE THREAD

**Issue by Lofaq** [Chocobozzz/PeerTube#5128]
### Describe the current behavior

Hello, 

Several times during Live tests, 
My stream key changed, which cut the live. 

Am I the only one ? 

thanks 

### Steps to reproduce

1.Start a live
2.
3.

### Describe the expected behavior

That the key does not change? 

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Booteille** [comment]
Hi. Depending on the kind of live you're doing you'll generate a new key at each live or not.
Permanent lives (which since 4.2 supports saving replays too) are the kind of live which use the same key for each live.

**Comment by Lofaq** [comment]
Hello, 
My problem is that the key changes during the live, which stops it :(
