### ISSUE TITLE
HLS.js error: networkError - fatal: false - fragLoadError with Backblaze B2

### ISSUE THREAD

**Issue by OrvilleQ** [Chocobozzz/PeerTube#5131]
### Describe the current behavior

If I press the Play button, the website will download almost tenfold the size of the video should be from the server. Then failed with `HLS.js error: networkError - fatal: false - fragLoadError`.

### Steps to reproduce

1. Setup a fresh new site with Backblaze B2 storage enabled.
2. Upload a video.
3. Wait for the transcode and upload finished.
4. try to play the video.
5. fail.

### Describe the expected behavior

The video should just play.

### Additional information

* PeerTube instance:
  * URL: https://nekofans.tv
  * Version: 4.2.2
  * NodeJS version: v16.14.1
  * Ffmpeg version: 4.4

* Browser name, version and platforms on which you could reproduce the bug: MacOS(Safari), Android(Firefox, Edge)
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

----

At the first place, I thought this is because B2's S3 API does not support `Range` header, so I switch to b2 native API use `base_url` but things still not working.

Then I look deep into the console and Network things, I do found something strange.

1. After I press the play button, console shows a `Segment error` from `p2p-media-loader-plugin.ts:117` said `Error: Hashes does not correspond for segment XXX-XXX-XXX-720-fragmented.mp4/208425-208424` which is really strange. and the `HLS.js error: networkError - fatal: false - fragLoadError` from `hls-plugin.ts:266` said the same-thing too. But man, I don't think any server could accept Range like `208425-208424`.

2. Then I check into the Network tab: 
```
GET /file/tv-nekofans-peertube/streaming-playlists/hls/c0c3e433-766a-4790-a9d9-73aeeabd727b/7681333b-de36-499d-bcd8-00c8400ce3bb-720-fragmented.mp4 HTTP/1.1
Accept: */*
Origin: https://nekofans.tv
Accept-Language: zh-CN,zh-Hans;q=0.9
Range: bytes=208425-208424
Host: f002.backblazeb2.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15
Referer: https://nekofans.tv/
Accept-Encoding: identity
Connection: keep-alive
```
And it do ask a `Range: bytes=208425-208424` which blow my mind. The browser download the hole video file with this header for about 7 to 8 times before failed.

3. Then I check into the B2 storage itself. The m3u8 file seems normal (See the attach files), but the `segments-sha256.json` file have this section:
```
"208425-208424":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
```
The file is attached below too.

----

This is how far I can go now. The demo video link is [here](https://nekofans.tv/w/pNASpstUziL1RXpkH4FRSt), Please help me with this if you'd like to. Thank you.

----

Attachments:

1. [streaming-playlists_hls_c0c3e433-766a-4790-a9d9-73aeeabd727b_7681333b-de36-499d-bcd8-00c8400ce3bb-720.m3u8.zip](https://github.com/Chocobozzz/PeerTube/files/9127472/streaming-playlists_hls_c0c3e433-766a-4790-a9d9-73aeeabd727b_7681333b-de36-499d-bcd8-00c8400ce3bb-720.m3u8.zip)

2.  [streaming-playlists_hls_c0c3e433-766a-4790-a9d9-73aeeabd727b_cef878f6-bdae-4855-8079-31ceadc5c94b-segments-sha256.json.zip](https://github.com/Chocobozzz/PeerTube/files/9127473/streaming-playlists_hls_c0c3e433-766a-4790-a9d9-73aeeabd727b_cef878f6-bdae-4855-8079-31ceadc5c94b-segments-sha256.json.zip)

**Comment by OrvilleQ** [comment]
All above are based on 720P. 1080P have the same issue too, asking for `Range: bytes=296724-296723`.

Demo video [here](https://nekofans.tv/w/fo3duwasp6HfTZoQSaNSjr0

**Comment by krautzone** [comment]
PeerTube has a bug with ffmpeg version 4.4, see #3990.
Your options: Downgrade or upgrade ffmpeg, f.e. to version 4.3.4 or 4.4.1

To fix the broken videos you can re-code them to WebTorrent (if WebTorrent is disabled by default), delete the broken HLS files, and re-code the WebTorrent to HLS again the changed ffmpeg version.

**Comment by OrvilleQ** [comment]
> PeerTube has a bug with ffmpeg version 4.4, see #3990. Your options: Downgrade or upgrade ffmpeg, f.e. to version 4.3.4 or 4.4.1
> 
> To fix the broken videos you can re-code them to WebTorrent (if WebTorrent is disabled by default), delete the broken HLS files, and re-code the WebTorrent to HLS again with the changed ffmpeg version.

I read those issues and yes, you are right.

But OpenSUSE Leap is still using ffmpeg version 4.4 by default. Maybe we should document this as a warning in the document?

**Comment by Chocobozzz** [comment]
I added a message in https://github.com/Chocobozzz/PeerTube/commit/1efad362ef0b65118d1d79d802ffc928994c0ef6
