### ISSUE TITLE
The number of videos is displayed incorrectly

### ISSUE THREAD

**Issue by BlitDev** [Chocobozzz/PeerTube#5132]
### Describe the current behavior

The number of my videos is about twice as large as the actual number of videos.
![image](https://user-images.githubusercontent.com/79034202/179476862-1f2df44e-1ada-4bce-9690-a0b0cde29a87.png)
I counted the number of videos manually, via the console. Here is the result:
![bug_peertube](https://user-images.githubusercontent.com/79034202/179477602-f5d203e7-73e6-42ed-a8cf-bd1a15f679b4.png)

### Steps to reproduce

1. Just open section "My videos"

### Additional information

* PeerTube instance:
  * URL: https://peertube.su/
  * Version: 4.2.2
  * NodeJS version: idk, I don't own this instance.
  * Ffmpeg version: idk, I don't own this instance.

* Browser name, version and platforms on which you could reproduce the bug: Latest Librewolf (Firefox fork)
* Link to browser console log if relevant: ?
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): I don't own this instance.

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/58c44687f748a3ea5feafe6335fe962aea8186bd
