### ISSUE TITLE
Sort videos by size

### ISSUE THREAD

**Issue by alejandrocobo** [Chocobozzz/PeerTube#5136]
### Describe the problem to be solved

When you go to Administration > Overview > Videos, you only can sort the videos by date.

### Describe the solution you would like

It would be nice to be able to sort the video list by file size.

Thanks.

**Comment by velw** [comment]
Would love to see this too. I've just been trying to figure out what size of video I uploaded to a PeerTube instance and which videos are using how much of my quota, and there seems to be no way to tell. Showing the size of uploaded videos and/or allowing to sort by that size would be very useful.

**Comment by vid-bin** [comment]
You can see how much quota users are using in the user tab and sort by usage amount.

**Comment by luzpaz** [comment]
Any code proposal for how to implement this ?

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/0648d578705c795db22b7e614eed43ccb0e03e69
