### ISSUE TITLE
master playlist and segment file should be named by content hash

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5137]
### Describe the problem to be solved

When doing a manual transcoding of a video, the master playlist and segments file will keep their filenames. This will break the video if the files are cached in a CDN or browser.

I assume this also may cause partial finished (i.e. not contained all resolutions due to transcoding in progress) files can be cached and not refreshed.

### Describe the solution you would like

Each time a new resolution has been transcoded the master playlist and segments file should have new filenames based on the content hash.

Relates to #4210

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/7b6b445d91d3f0bcbb526cb1e8c1f26b96f0a971
