### ISSUE TITLE
Add captions creation and/or update date

### ISSUE THREAD

**Issue by SansPseudoFix** [Chocobozzz/PeerTube#5139]
### Describe the problem to be solved

When you have a video with many languages maintained by many users, it's sometimes uneasy to know which captions is up to date or not.

### Describe the solution you would like

Adding **Last update: n months ago** should be useful:

![ksnip_20220721-133838](https://user-images.githubusercontent.com/6507951/180205064-cc1b27bb-285b-452e-b67c-107705db3538.png)

**Comment by Chocobozzz** [comment]
Added in https://github.com/Chocobozzz/PeerTube/commit/4f50475c67356fb1fecd1de6d2551fdc5ad9a739
