### ISSUE TITLE
Add Notification hook

### ISSUE THREAD

**Issue by dhk2** [Chocobozzz/PeerTube#5140]
### Describe the problem to be solved

Creating a bot for Telegraph integration. Part of the integration is a chat channel open between the bot and authenticated users that can send notifications of new videos, new lives, etc. Getting new videos from subscribed channels isn't as easily implemented without some kludgy work arounds so far. Adding a hook fired for a new notification would make it easier and add more flexibility in passing other types of notifications to the user via plugin instead of email.

### Describe the solution you would like

A hook created after a new notification is created. Something like
```
  registerHook({
    target: 'action:api.notification.created',
    handler: ({ user, notificationElement }) => {} )
  })
```

**Comment by Chocobozzz** [comment]
Hi,

You now have a notification hook with https://github.com/Chocobozzz/PeerTube/commit/785f1897a42984ece9c6f65829d195d67e331d95

```
  // Fired when a new notification is created
  'action:notifier.notification.created': true,
```

It comes with `{ webNotificationEnabled, emailNotificationEnabled, user, notification }` object
