### ISSUE TITLE
Redis Sentinel support

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5141]
### Describe the problem to be solved

Currently the only way to ensure high availability for the redis server is to use master/slave setup with manual handling when making system upgrades.

### Describe the solution you would like

> Redis Sentinel provides high availability for Redis when not using [Redis Cluster](https://redis.io/docs/manual/scaling).
> 
> * Monitoring. Sentinel constantly checks if your master and replica instances are working as expected.
> * Notification. Sentinel can notify the system administrator, or other computer programs, via an API, that something is wrong with one of the monitored Redis instances.
> * Automatic failover. If a master is not working as expected, Sentinel can start a failover process where a replica is promoted to master, the other additional replicas are reconfigured to use the new master, and the applications using the Redis server are informed about the new address to use when connecting.
> * Configuration provider. Sentinel acts as a source of authority for clients service discovery: clients connect to Sentinels in order to ask for the address of the current Redis master responsible for a given service. If a failover occurs, Sentinels will report the new address.

Read more at https://redis.io/docs/manual/sentinel/

The currently used redis client doesn't [support sentinels](https://github.com/redis/node-redis/issues/302) though, so a switch to ioredis would be needed. https://github.com/luin/ioredis#sentinel

**Comment by ROBERT-MCDOWELL** [comment]
is anyone know this very popular fork? https://github.com/Snapchat/KeyDB
looks much better than redis since it allows multimaster!
