### ISSUE TITLE
Refused and muted instances can still create follow requests (repeatedly)

### ISSUE THREAD

**Issue by pietsch** [Chocobozzz/PeerTube#5143]
### Describe the current behavior

The instance I run as a volunteer for an NGO has _Manually approve new instance followers_ enabled because we do not want our content to appear on illegal or disgusting instances.

The problem is that after I refuse a follow application, most instances re-apply sooner or later. This makes instance follow moderation very tedious.

I assumed that adding those annoying instances to the list of muted instances would prevent them from re-applying, but this is not the case – see the dalek and chalec domains in both screenshots.

This problem has existed for a long time – it was mentioned in comments to the possibly related issue #2143 but never addressed.

![Screenshot 2022-07-24 at 14-09-18 Muted instances - Digitalcourage](https://user-images.githubusercontent.com/1190858/180647021-ce6d658a-94fd-4485-9b81-f75d1fbce00a.png)
![Screenshot 2022-07-24 at 12-59-16 Followers - Digitalcourage](https://user-images.githubusercontent.com/1190858/180647034-24bb7a45-3ca9-4808-8ce6-127879bacc55.png)

### Steps to reproduce

1. Enable _Manually approve new instance followers_ in Administration → Configuration → Basic (`/admin/config/edit-custom#basic-configuration`).
2. In Administration → Federation → Followers (`/admin/follows/followers-list`), refuse a follow application.
3. Wait for it to re-apply. It might take days.

### Describe the expected behavior

Refused instances should not be allowed to re-apply.

Alternatively, there should be an option to refuse instances permanently.

In any case, muted instances should not be allowed to create follow requests.

### Additional information

* PeerTube instance: digitalcourage.video
  * URL: https://digitacourage.video/
  * Version: 4.2.2
  * NodeJS version: v14.20.0
  * Ffmpeg version: 4.1.9-0+deb10u1

* Browser name, version and platforms on which you could reproduce the bug: Firefox 102.0.1 on Debian GNU/Linux 11

**Comment by Chocobozzz** [comment]
Hello,

We now remember rejected follow requests and display them in the admin. Followers can not resend follow request if they were already rejected. This way you won't have follow notifications anymore.

We also automatically reject remote follows of muted accounts/servers.

This has been implemented in https://github.com/Chocobozzz/PeerTube/commit/927fa4b11f692174d6296aa096d7a74bacdeea8b and https://github.com/Chocobozzz/PeerTube/commit/073deef8862f462de5f159a57877ef415ebe4c69

**Comment by FediVideos** [comment]
My instance at https://fedi.video is still seeing requests from previously rejected servers.

I have tried muting the servers, but this does not stop them sending requests.

Is there specific info I can give to help solve this problem?

**Comment by Chocobozzz** [comment]
@FediVideos Seems to be a bug :thinking:  Can you open a dedicated issue and fill the bug template with some screens so I can understand what happens?
