### ISSUE TITLE
502 bad gateway 

### ISSUE THREAD

**Issue by germanfung** [Chocobozzz/PeerTube#5146]
### Describe the current behavior

Hi,

I have experienced 502 bad gateway on my instance running on freebsd. There was no issue when it still run v3.4.
It happened almost weekly in v4.0 during weekend and user report on Monday morning and resolved by a reboot. It then happened again a month after it was upgraded to v4.2.1… (less often, but problem still there). Originally I thought it was due to the missing configuration update in production.yaml during the upgrade from v3.x to v4.0, I have fixed them in v4.2.1 upgrade. See the error below and please give me some hints. Thanks

### Steps to reproduce

1. On every Sat morning 8am, we have our internal Tenable Nessus scanner for web security vulnerability scanning
2. Peertube returns 502 bad gateways

### Additional information

* PeerTube instance:
  * URL:  video.lchs.com.au  (internal hosting)
  * Version: 4.2.1
  * NodeJS version:  
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
[standard logs - error.txt](https://github.com/Chocobozzz/PeerTube/files/9230151/standard.logs.-.error.txt)
[debug.txt](https://github.com/Chocobozzz/PeerTube/files/9230156/debug.txt)

**Comment by Chocobozzz** [comment]
Hello,

Please fill correctly the template, in particular the URL and logs section. I would need debug logs (or at least info logs) just before the crash.

**Comment by germanfung** [comment]
> Hello,
> 
> Please fill correctly the template, in particular the URL and logs section. I would need debug logs (or at least info logs) just before the crash.

Sorry I have collected the required info incorp to the template

**Comment by Chocobozzz** [comment]
Can you try `--abort-on-uncaught-exception` node option? https://nodejs.org/api/cli.html#cli_abort_on_uncaught_exception

**Comment by germanfung** [comment]
Hi, see the response

Welcome to Node.js v17.0.1.
Type ".help" for more information.
> --abort-on-uncaught-exception
Uncaught ReferenceError: abort is not defined

Regards,
German
