### ISSUE TITLE
Peertube static packet request in case of big internet failure

### ISSUE THREAD

**Issue by maxlinux2000** [Chocobozzz/PeerTube#5147]
### Describe the problem to be solved

Imagine that the internet as we know it now, starts to crash and it becomes impossible to download the hundreds and hundreds of dependencies of yarn, nodejs, etc.
Ideally, there should be an installation package such as .deb or tar or .snap, or whatever is more convenient, where there is everything necessary to make Peertube work.
The motivation for this request is that we can mirror the Debian repositories and their sources, but personally it would be impossible for me to add the nodejs, python, npn, yarn, etc. repositories as well.
...and with the times we are going through, where interest, wars and politics are colliding, it is not unreasonable to imagine a world with many small internets that cannot communicate with each other, instead of the big internet we have now.

### Describe the solution you would like

So I recommend you create a package that can run on any debian10 with no external dependencies apart from the debian repositories themselves.

Cheers

**Comment by maxlinux2000** [comment]
In case someone reminds me that there are telecommunications satellites in orbit, I just want to comment that:

A) the satellites are private but obey military and political interests

B) there is a strong possibility of a Kessler syndrome that would leave us without satellites and especially without space programs for centuries
https://en.wikipedia.org/wiki/Kessler_syndrome

**Comment by ROBERT-MCDOWELL** [comment]
why not to do it yourself?

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but we don't have time to maintain such package.
