### ISSUE TITLE
Peertube does not recognize ffmpeg git version

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5148]
### Describe the current behavior

I actually use my own compiled ffmpeg from the last git, however peertube does not recognize it as a git version

Error: Could not find ffmpeg version in ffmpeg version N-107416-ga26a2f38e1

### Steps to reproduce

1. install ffmpeg from git
2. upload a video to transcode
3. read the peertube.log

### Describe the expected behavior

Peertube must distinct release version from git version like N-107416-ga26a2f38e1

### Additional information

* PeerTube instance:
  * Version: 4.2.2
  * Ffmpeg version: GIT

* Browser name, version and platforms on which you could reproduce the bug:
All

**Comment by Chocobozzz** [comment]
Hello,

Unfortunately this git version doesn't contain underlying ffmpeg version. PeerTube cannot parse it so I think it's expected to display an error message.

**Comment by ROBERT-MCDOWELL** [comment]
Git version always start with N-. anyhow nevermind I will use another ffmpeg installation so...
