### ISSUE TITLE
Confusion about VOD transcoding configuration choice

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5149]
### Describe the current behavior

When I click to Allow VOD transcoding and select HLS only
in torrents folder I can still see torrents created and the player insist to try to watch with torrent files

is it normal?

also there is checkbox disabled issue when I unselect both torrent and HLS both checkbox are disabled so I have to refresh the page to have a chance to select one or both checkbox again

### Steps to reproduce

1. select VOD transcoding
2. choose HLS only
3. check torrents folder

### Describe the expected behavior

when torrents unchecked no torrent must be created

### Additional information

* PeerTube instance:

  * Version: 4.2.2

* Browser name, version and platforms on which you could reproduce the bug:
ALL

**Comment by Chocobozzz** [comment]
Hello,

Yes this is normal. We also generate a torrent file for HLS videos.

> also there is checkbox disabled issue when I unselect both torrent and HLS both checkbox are disabled 

It's weird that you can disable both options. How do you do?

**Comment by ROBERT-MCDOWELL** [comment]
@Chocobozzz 
> Yes this is normal. We also generate a torrent file for HLS videos.
gotcha.

> It's weird that you can disable both options. How do you do?
attached saved settings and when I uncheck HLS
![Untitled-1](https://user-images.githubusercontent.com/2649072/181001155-20ab0dca-5362-406c-ab8f-f3040fd44835.jpg)
![Untitled-2](https://user-images.githubusercontent.com/2649072/181001163-c1c675d3-e693-43d9-b06a-70cbc63d6917.jpg)

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/8224e13d3b59ff4420d6c323c95d829ca014a442
