### ISSUE TITLE
Invalid client: client is invalid

### ISSUE THREAD

**Issue by arnaudbagnis** [Chocobozzz/PeerTube#5150]
### Describe the current behavior

I am following a ticket which for me was the same #4901

After installation, I tried to log in with the root account. and I got an error:
client is invalid

In the server logs I have: 
```
Jul 25 21:27:56 server13 peertube[40310]: [server13.tk:9000] 2022-07-20 21:27:56.557 #033[33mwarn#033[39m: Login error {
Jul 25 21:27:56 server13 peertube[40310]:   "err": {
Jul 25 21:27:56 server13 peertube[40310]:     "statusCode": 400,
Jul 25 21:27:56 server13 peertube[40310]:     "status": 400,
Jul 25 21:27:56 server13 peertube[40310]:     "code": 400,
Jul 25 21:27:56 server13 peertube[40310]:     "message": "Invalid client: client is invalid",
Jul 25 21:27:56 server13 peertube[40310]:     "name": "invalid_client",
Jul 25 21:27:56 server13 peertube[40310]:     "stack": "invalid_client: Invalid client: client is invalid\n    at new InvalidClientError (/var/www/peertube/versions/peertube-nightly-2022-07-25/nod>
Jul 25 21:27:56 server13 peertube[40310]:   }
Jul 25 21:27:56 server13 peertube[40310]: }
```

### Steps to reproduce

1. Install Peertube 4.2.2 on Ubuntu 22.04
2. `tail -f /var/log/syslog`
3. `sudo service peertube start `

### Describe the expected behavior

Login to peertube admin with root

### Additional information

* PeerTube instance:
  * URL: [meding.tk](url)
  * Version: peertube-nightly-2022-07-25
  * NodeJS version: v18.6.0
  * Ffmpeg version: ffmpeg version 4.4.2-0ubuntu0.22.04.1

* Browser name, version and platforms on which you could reproduce the bug: Chrome
* Link to browser console log if relevant: 
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

It seems your server is configured with port `9000` in https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L9. However it should be `443`.
Then run https://docs.joinpeertube.org/maintain-tools?id=update-hostjs

**Comment by arnaudbagnis** [comment]
thank you very much it works!
