### ISSUE TITLE
Option to only transcode lower resolutions and keep source file for default resolution.

### ISSUE THREAD

**Issue by manicphase** [Chocobozzz/PeerTube#5153]
### Describe the problem to be solved

Low end hardware struggles to transcode multiple outputs. Currently if transcoding is enabled for livestreams, peertube will transcode all for resolutions including the source one. 

For example, if live stream transcoding is enabled and set to only 480p, and the source is 1080p, a transcoding job will start for both 480p and 1080p.

Transcoding for the source resolution is not always necessary, as the original stream will suffice.

### Describe the solution you would like

Add an option in Configuration > Live streaming > Transcoding to use the source stream for the highest resolution

**Comment by Chocobozzz** [comment]
Hello,

Unfortunately the original file needs to be transcoded to be correctly played in the web browser. If you still want to just "copy" streams of the original file, you can create a plugin by adding custom transcoding profile: https://docs.joinpeertube.org/contribute-plugins?id=add-new-transcoding-profiles

**Comment by manicphase** [comment]
As far as I'm aware, transcoding plugins can't use different encoders for different resolutions. And from what I can tell, peertube uses the an ffmpeg command containing `-c:v copy -c:a copy` if transcoding is disabled anyway. I'm asking if it's possible to use different profiles for different resolutions. I don't mind attempting to write it myself if you can point me to the right place to make changes. I see it could probably be done in `server/lib/live/shared/muxing-session.ts` or `server/helpers/ffmpeg/ffmpeg-live.ts` if there's a chance to get the changes pulled.
