### ISSUE TITLE
Incorrect type syntax in muxing-session.ts

### ISSUE THREAD

**Issue by RyanCavanaugh** [Chocobozzz/PeerTube#5154]
### Describe the current behavior

In https://github.com/Chocobozzz/PeerTube/blob/3efa4da1fef44400931c3db47dc27a92da77062e/server/lib/live/shared/muxing-session.ts#L24

This line of code doesn't do what it looks like it's doing (the "number" annotation doesn't make this a number at all) - it either should be
```ts
  'master-playlist-created': (x: { videoId: number }) => void
```
if the function takes an object with a `videoId` property, or
```ts
  'master-playlist-created': (videoId: number) => void
```
if it takes a single numeric argument.

As-is, this function accepts an object with a `videoId` of *any* type.

See also https://github.com/microsoft/TypeScript/issues/50060 for a full list. This will be an error in TypeScript 4.8

### Steps to reproduce

1. See code
2. It's not right

### Describe the expected behavior

Should be right

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

Thanks I didn't know. Nice to see it will be an error in next TS version.
Should be fixed in PeerTube by https://github.com/Chocobozzz/PeerTube/commit/15eb9e5b8fe9a29201567ab41f730fd39c1a14b8
