### ISSUE TITLE
Follow Request Doesn't Appear

### ISSUE THREAD

**Issue by TILvids** [Chocobozzz/PeerTube#5155]
### Describe the current behavior

I have two PeerTube instances, we'll call them "main" and "redundancy". I told "redundancy" to follow and become redundant of "main". The follow request appeared on "main", I accepted it, and they were federated. Unfortunately, I had to re-initialize "redundancy". I deleted the follow from "main" and told "redundancy" to follow "main" again, but now the follow request never comes through. Other follow requests from other servers appear, but "redundancy" never does. Is there anything I can do to troubleshoot why the request isn't showing up on "main" anymore?

### Steps to reproduce

1. Follow one PeerTube instance from another.
2. Delete the follow.
3. Send another follow request.

### Describe the expected behavior

Expected: Another follow request appears.

Actual: Follow request doesn't appear.

### Additional information

* PeerTube instance: 4.2.2
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Please enable debug logs on your peertube instances, send a follow request and paste the logs of "main" and "redundancy"

**Comment by TILvids** [comment]
@Chocobozzz Thank you for the response. Is there anything special I need to do to enable debug logs, or are these just the regular logs found in the web admin?

**Comment by TILvids** [comment]
@Chocobozzz Hmm, looks like the request showed up after I tried again now. I hadn't tried it for a few days, so...not sure what the cause would be there.
