### ISSUE TITLE
About LIVE streaming and MPEG .TS files

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5156]
### Describe the problem to be solved

Sorry if my question lacks of technical skills but something about the live system makes me wonder why since RTMP(S) streaming which is in H264/AAC is converted in MPEG2 .TS, then again in HLS mp4 segments for replay?

why not to convert the RTMP live stream in WebRTC/RTSP or WSS and connect from the client directly with this transports?
this project can be an example of how they convert RTMP to webrtc/websocket
https://github.com/illuspas/Node-Media-Server
or
https://pkg.go.dev/github.com/pion/example-webrtc-applications/v3/rtmp-to-webrtc#section-readme
I recently installed peertube on my server and the client cannot follow the .TS livestream even on a 100Mb internet line I really don't know why... it can come from my server which has HD and not SSD or else.

Also why not to convert directly the RTMP stream direclty in HLS for the replay with a script like this one https://github.com/Hemisphere-Project/HLS-segmenter
or maybe it's already done with ffmpeg isn't it?

thanks for your answer

**Comment by Chocobozzz** [comment]
Hello,

Please use the forum for PeerTube releated questions: https://framacolibri.org/c/peertube
