### ISSUE TITLE
Cannot play some videos on Chrome/Chromium

### ISSUE THREAD

**Issue by alejandrocobo** [Chocobozzz/PeerTube#5158]
### Describe the current behavior

Hi,

A user of my instance has complained about a couple of its videos won't play giving this message:

`The media could not be loaded, either because the server or network failed or because the format is not supported.`

I was able to reproduce the issue on Chrome 103.0.5060.134 but the videos work fine on Firefox (Windows and Linux). At the moment I just was able to reproduce the issue with those two videos (the rest work fine). I don't find a pattern of size/length/resolution since there are several videos similar to those that work as expected on Chromium.

While checking the console, I found the errors shown in the image:
![image](https://user-images.githubusercontent.com/1640709/182038789-1a9a7de8-1fc0-44d0-b8cb-9df47191f079.png)

### Steps to reproduce

Try to play one of these videos on Chrome/Chromium:
· https://video.hardlimit.com/w/dydYeSFyEDAUsSmLu9avjy
· https://video.hardlimit.com/w/9g2GRyLaV9rFgdJ3pjNgz4

### Describe the expected behavior

The videos should work since these particular clips work fine on Firefox and I tried a bunch of other videos on Chrome and Chromium that work as expected.

### Additional information

* PeerTube instance:
  * Version: 4.2.2
* Browsers
  * Chromium 103.0.5060.134 on Linux normal and incognito mode (restored to default settings, cookies and cache cleaned).
  * Chrome 103.0.5060.134 on Windows (fresh installation).

Thanks.

**Comment by ROBERT-MCDOWELL** [comment]
did you try to read your HLS video with a player like VLC?

**Comment by alejandrocobo** [comment]
> did you try to read your HLS video with a player like VLC?

Thanks to the quick reply. I don't have to since both videos work fine on Firefox (Linux and Windows).

**Comment by ROBERT-MCDOWELL** [comment]
compare this video to other working and you will see where is the problem

**Comment by alejandrocobo** [comment]
> compare this video to other working and you will see where is the problem

Compare in what regard? Those videos are in HLS like other videos that work fine and have a length similar to others and a standard resolution.

**Comment by ROBERT-MCDOWELL** [comment]
to know why chrome is less permissive about corrupted HLS segment than others...  anyhow there is a good reason why chrome does not accept the chunks.

**Comment by alejandrocobo** [comment]
> to know why chrome is less permissive about corrupted HLS segment than others... anyhow there is a good reason why chrome does not accept the chunks. it's surely not a peertube problem...

Out of curiosity, how do you know is a corruption issue? I played all the files of one of the videos with VLC and I didn't see any corrupted data in the statistics.

**Comment by ROBERT-MCDOWELL** [comment]
you said it works on firefox so it's easy to guess there is a encoding issue that Chrome does not accept....

**Comment by Chocobozzz** [comment]
Hello,

Can you run again HLS transcoding on these videos?

**Comment by alejandrocobo** [comment]
Maybe this is a different issue, but I leave the details here in case it helps:
Another user uploaded a video for which Peertube is unable to show the video length nor a thumbnail (it shows a lenth of 0:00 and shows a blank thumbnail). Apparently it was transcoded correctly (I have multiple resolutions) and I can play it but at certain point, the player crashes showing this error:

`HLS.js error: otherError - fatal: true - levelSwitchError`

This error appears randomly and it is reproducible in both, Firefox and Chrome. The problematic video is this one: https://video.hardlimit.com/w/mv197YSgFrrBGC3aNVSnYs

I rerun the HLS transcoding but the error is still there.

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/4fd6dcfb4432b71549fb2d4c3cc3b92f34c29665

You'll have to run again transcoding
