### ISSUE TITLE
V 4.2.2 - Muted Domains page hides domain names?

### ISSUE THREAD

**Issue by jwildeboer** [Chocobozzz/PeerTube#5159]
### Describe the current behavior

The "Muted Domains" page on my instance running 4.2.2 only shows an unmute button but no domain names.

### Steps to reproduce

1. Mute domains
2. Go to Muted Domains Page
3. No domains visible, only unmute buttons.

### Describe the expected behavior

Should show domain names

### Additional information

* PeerTube instance: vid.wildeboer.net
  * URL: https://vid.wildeboer.net
  * Version: 4.4.2
  * NodeJS version: unknown
  * Ffmpeg version: unknown

My instance is installed and maintained by spacebar.ee

* Browser name, version and platforms on which you could reproduce the bug: Safari, MacOS
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Can you take a screen of the page?

**Comment by jwildeboer** [comment]
Sure. I forgot to attach it, Apologies

<img width="1113" alt="Screenshot 2022-07-31 at 20 52 39" src="https://user-images.githubusercontent.com/873028/182112595-ce28a9ff-851d-49d3-97f0-7111d6dd2f8c.png">
!

**Comment by Chocobozzz** [comment]
Is it the admin view or your account view?
Can you reproduce with another web browser?

**Comment by jwildeboer** [comment]
Here's a screenshot of the HTML source. Looks OK to me. I am using stock peer tube, no changes to JS or CSS.

<img width="495" alt="Screenshot 2022-08-01 at 11 08 59" src="https://user-images.githubusercontent.com/873028/182114765-139b680d-10dc-4944-8b2b-6940849b2c46.png">

And the HTML itself for one row:

```
<tr _ngcontent-rtk-c237="" class="ng-star-inserted">
  <td _ngcontent-rtk-c237="" class="action-cell">
    <button _ngcontent-rtk-c237="" class="unblock-button">Unmute</button>
  </td>
  <td _ngcontent-rtk-c237="">
    <a _ngcontent-rtk-c237="" title="Open instance in a new tab" target="_blank" rel="noopener noreferrer" href="https://gorf.tube"> gorf.tube <span _ngcontent-rtk-c237="" class="glyphicon glyphicon-new-window"></span></a>
  </td>
  <td _ngcontent-rtk-c237="">7/31/22, 8:30 PM</td>
</tr>
<td _ngcontent-rtk-c237="" class="action-cell"><button _ngcontent-rtk-c237="" class="unblock-button">Unmute</button></td>
<td _ngcontent-rtk-c237=""><a _ngcontent-rtk-c237="" title="Open instance in a new tab" target="_blank" rel="noopener noreferrer" href="https://gorf.tube"> gorf.tube <span _ngcontent-rtk-c237="" class="glyphicon glyphicon-new-window"></span></a></td>
<td _ngcontent-rtk-c237="">7/31/22, 8:30 PM</td>
<tr _ngcontent-rtk-c237="" class="ng-star-inserted"><td _ngcontent-rtk-c237="" class="action-cell"><button _ngcontent-rtk-c237="" class="unblock-button">Unmute</button></td><td _ngcontent-rtk-c237=""><a _ngcontent-rtk-c237="" title="Open instance in a new tab" target="_blank" rel="noopener noreferrer" href="https://gorf.tube"> gorf.tube <span _ngcontent-rtk-c237="" class="glyphicon glyphicon-new-window"></span></a></td><td _ngcontent-rtk-c237="">7/31/22, 8:30 PM</td></tr>
```

**Comment by jwildeboer** [comment]
It's the admin view. I think it is a safaris specific quirk, let me check with Chrome. Yep. Safari-only :(

<img width="1163" alt="Screenshot 2022-08-01 at 11 27 04" src="https://user-images.githubusercontent.com/873028/182118240-aa8d827f-8add-4cd4-8933-d0435174a15e.png">

**Comment by jwildeboer** [comment]
For whatever reason, the first td with the unmute button becomes too big, shoving the second td under the 3rd td and that's why the text disappears.
<img width="471" alt="Screenshot 2022-08-01 at 11 47 12" src="https://user-images.githubusercontent.com/873028/182121995-6a2e353e-89a4-4fc0-b83f-6512f427c7cd.png">

**Comment by Chocobozzz** [comment]
Thanks for the details! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/e07c55167eedc17bb4f4c5f1fe4294b6bde9aabe
