### ISSUE TITLE
Unable to import video from other PeerTube server.

### ISSUE THREAD

**Issue by smilekison** [Chocobozzz/PeerTube#5161]
### Describe the current behavior

I was trying to upload video from other PeerTube server (Eg: https://peertube2.cpy.re/w/9ugKvpyv8qXGNCkAwwojLW) to my PeerTube server. But I am getting the following error displayed: 
![6](https://user-images.githubusercontent.com/24309222/182071053-131bada7-8590-4531-8647-638c3f556c8d.png)

Some videos are successfully published but shows error on job task during importing.
![image](https://user-images.githubusercontent.com/24309222/182073141-83cdff25-b10d-46a4-8f6f-fcfb3247c8a8.png)

### Steps to reproduce
1. Login to you account
2. Click on Publish
3. Click on Import with URL.
4. Paste the video URL from other peertube server.
5. Click on Import
6. On video information screen, Click on Update/Publish.
7. Error message pops up, as shown in the image.

### Describe the expected behavior

After click on update, the video should import from PeerTube server same as it imports from other video platform.

### Additional information

* PeerTube instance:
  * Version: 4.2.2
 
* Browser name: Chrome/Mozilla

**Comment by smilekison** [comment]
I am not sure.. I have deployed using the default settings used on PeerTube.

**Comment by Chocobozzz** [comment]
Moving to `yt-dlp` should fix your issue: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L539
