### ISSUE TITLE
About streaming-playlists/hls folder

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5164]
### Describe the problem to be solved

Is there a way to separate the live xxx.ts files from hls as I would like to make the .TS chunks available on a zram folder to speed up the write/read? I think it's a good idea to get the .ts chunks out from hls folder since it's confusing to have mpeg2 ts files into hls folder where it is supposed to be only fragmented mp4 files....

### Describe the solution you would like

have a dedicated folder for live mpeg2 TS files to allow the administrator to optimize it with various ways.

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but we don't plan to move out ts files from HLS directory. HLS directory is for HLS playlists, than can use fragmented or segmented files.

**Comment by ROBERT-MCDOWELL** [comment]
do you think I can hack the code for it or does it involve to many changes?
