### ISSUE TITLE
Bandwidth between HLS and webtorrent

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5165]
### Describe the current behavior

I noticed after an experiment with the same server and line conditions a big bandwidth rate difference between a pure webtorrent full mp4 and an HLS video.
the webtorrent full mp4 file never pass more than 50KB for a 720p resulting lags and stop. Rather, with HLS it plays flawlessly with around 800KB to 1MB / sec rate.
What cause  this difference? is webtorrent file can be streamed with the same rate than HLS?

### Describe the expected behavior

have the same rate than HLS to be able to play webtorrent file in high resolution.

**Comment by Chocobozzz** [comment]
Hello,

See https://docs.joinpeertube.org/admin-configuration?id=webtorrent-transcoding-or-hls-transcoding

Webtorrent is considered as a legacy player in peertube, so we don't plan to improve it.

**Comment by ROBERT-MCDOWELL** [comment]
ok understood, maybe  beside the "webtorrent" checkbox a line lke "Legacy webtorrent" with an info anchor saying that it's a non recommended option present for backward compatibility" ?
