### ISSUE TITLE
About Live streaming transcoding with replay

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5166]
### Describe the problem to be solved

It seems that after the live the replay is transcoding to only the resolution of the original live streaming.
Why not to respect the VOD configuration as Live transcoding configuration concerns the realtime transcoding?

### Describe the solution you would like

Respect the VOD transcoding configuration for REPLAY live stream as REPLAY is considered as a VOD.

**Comment by Alterak** [comment]
I also asked for this feature to be added a long time ago.
https://github.com/Chocobozzz/PeerTube/issues/3914

**Comment by ROBERT-MCDOWELL** [comment]
well, it's never too late ;)

**Comment by Chocobozzz** [comment]
Then merging this issue in https://github.com/Chocobozzz/PeerTube/issues/3914 :)
