### ISSUE TITLE
Switch video format to H.264 when dropped frames are detected in VP9/AV1 streams

### ISSUE THREAD

**Issue by emansom** [Chocobozzz/PeerTube#5167]
### Describe the problem to be solved

Most devices in use now don't ship with the required hardware and software configuration for full accelerated VP9 and AV1 video decode, leading to very high CPU usage and dropped frames when other formats than H.264 are served.

### Describe the solution you would like

On these devices it's better to switch format quickly to H.264 when dropped frames are detected.

In the future when PeerTube lands functionality to serve multiple codecs per video, this will need to be addressed to ensure a good user experience on multiple platforms and devices.

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I don't understand: we don't officially support VP9 or AV1 videos in PeerTube so what is the problem you want to solve with this issue?

**Comment by emansom** [comment]
As noted above, future reference to point to.

**Comment by Chocobozzz** [comment]
Then we'll reopen this issue when it will be the case

**Comment by vid-bin** [comment]
@Chocobozzz @emansom I've been experimenting with converting VP9 to AV1 using the "Run hls transcoding" option which works. Pain to do manually though.

https://vidbin.org/w/swWHwLFjbp16osktD4NaPG

HLS is able to successfully play the 480p VP9 format on the iphone and AV1 on PC.

I know this isn't supported in peertube but it does work. Is there a way to create more then one profile with the transcoding-profile-debug plugin and then specify that profile in the source code for 480p and 1080p? I do not mind getting my hands a little dirty but am completely unfamiliar with peertubes code.

**Comment by vid-bin** [comment]
Ah, misread the issue. I think this is a good compromise though since it would allow more users to view the videos. AV1 isn't exactly widely supported at the moment.
