### ISSUE TITLE
Add ability for plugins to handle federation

### ISSUE THREAD

**Issue by based-a-tron** [Chocobozzz/PeerTube#5169]
### Describe the problem to be solved

For reference, I have read the livechat blogpost, and the closed issue that discussed adding a live chat feature.

Currently there are several plugins available to embed frontends for various federated chat services like XMPP and Matrix into the peertube interface. I do not think these plugins need be abandoned; their interfaces work quite well.
However, an issue arises when we take into account federation. We do not know what chat service another server is running, if they are running one at all. Consequently, there is no standard way (at least not that I know of; if it exists then consider this a documentation issue) to affiliate chatrooms to a video and/or playlist, even if the two servers are running compatible chat software.
It would be nice to load or mirror a video from another service and still be able to access the chatroom that was affiliated with that video. This would pair extremely nicely with, for instance, a plugin which allows users to sync videos and watch them together over xmpp or matrix, even on remote servers.

### Describe the solution you would like
Perhaps adding an `affiliatedChatrooms` list to the `Video` activitypub object would be a good idea. Something that has maybe chatroom URN's in a list. Let me know what you think, please.

**Comment by based-a-tron** [comment]
Thanks for taking an interest in this. I think this is something that could really make peertube a lot more desirable for a ton of use cases.

**Comment by based-a-tron** [comment]
Hi, has there been any discussion on this? I feel like I can't be the only person that desires such a feature.

**Comment by Chocobozzz** [comment]
Hi,

Plugins can now support federation in PeerTube 5.1: https://docs.joinpeertube.org/contribute/plugins#federation
