### ISSUE TITLE
Theme | Default theme is overwritten by system preferences

### ISSUE THREAD

**Issue by Aioph** [Chocobozzz/PeerTube#5172]
### Describe the current behavior

Hi,

when adding a new theme and setting it as default theme, I expect it to be set as a default theme.
As written in https://github.com/Chocobozzz/PeerTube/issues/5025 this setting is overwritten by system preferences - which leads to confusion because in the user settings, the theme can be set to instance default and yet is overwritten by system preferences

### Steps to reproduce

1. Set browser default theme to dark
2. Import some light theme
3. Set light theme as default for the instance

### Describe the expected behavior

I would expect that the instance default is actually overwritting the system preferences, not the other way around.

### Additional information

* PeerTube instance:
  * URL: n.A.
  * Version: 4.2.2
  * NodeJS version: 14.x
  * Ffmpeg version: -

* Browser name, version and platforms on which you could reproduce the bug: Edge 103.0.1264.49 on Windows 10
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

I'm not sure to understand: do you want to force the default peertube light theme? Or do you see a bug where peertube uses the dark theme with web browsers that prefer dark colors while you set a custom installed theme in admin config?

**Comment by Aioph** [comment]
Hi 👋
I'm actually myself quite unsure.
I think it's not good that the system preferences overwrite the

**Comment by ROBERT-MCDOWELL** [comment]
@Chocobozzz  it seems that sometimes the word "default" on select box disappear when a theme is installed and does not show also the new theme after refresh.
