### ISSUE TITLE
Cleaning HLS folder?

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5174]
### Describe the problem to be solved

Is there any cron task or else that clean the HLS folder from orphan segment folders/files?
I noticed that apparently some segment folders stay in HLS after various unfinished task like reboot, crash or else

### Describe the solution you would like

Create a cron like task that compare active online videos and orphans segment folders

**Comment by Chocobozzz** [comment]
Hello,

You can use the prune storage script: https://docs.joinpeertube.org/maintain-tools?id=prune-storagejs

**Comment by ROBERT-MCDOWELL** [comment]
I added in the systemd unit to automate the task:
ExecStartPre=-"NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run prune-storage 2>&1>/dev/null"
