### ISSUE TITLE
HLS.js error: other error: fatal: true - levelSwtich error on IOS and Android from recorded live stream

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5176]
### Describe the current behavior

HLS.js error: other error: fatal: true - levelSwtich error on IOS and Android from a freshly recorded live stream.
on windows it seems to work but with many bufferStalledError.

### Steps to reproduce

1. replay live stream sent from OBS

### Describe the expected behavior

must not have any error to play the stream and a no bufferStalledError on a high bandwidth internet line

**Comment by Chocobozzz** [comment]
Hello,

Please paste the URL of the replay

**Comment by ROBERT-MCDOWELL** [comment]
mmhmm, sorry I deleted the replay and now I cannot reproduce it with the new lives :-\
