### ISSUE TITLE
Little glitches in statnerds

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5178]
### Describe the current behavior

when seeking throught the video and no buffer yet on the part of the seeked video "resolution" becomes "undefinedp"
and codec line disappear.

### Steps to reproduce

1. open statnerds
Player modep2p-media-loader
P2P enabled
Video UUID3f24c747-4658-4de9-ae78-588fc5bd6bd0
Viewport / Frames1920x1127*1.00 / 3 dropped of 5439
Resolution 480p29
Volume 38
Codec savc1.64001f / mp4a.40.2
Connection Speed936 KB/s
Network Activity0 B ⇓ / 0 B ⇑
.....

2. seek a part of the video where buffer does not still exist
Player modep2p-media-loader
P2P enabled
Video UUID3f24c747-4658-4de9-ae78-588fc5bd6bd0
Viewport / Frames1920x1127*1.00 / 56 dropped of 8396
Resolution undefinedp
Volume38
???
Connection Speed1008 KB/s
Network Activity0 B ⇓ / 0 B ⇑
Total Transfered

### Describe the expected behavior

keep the resolution consistent and keep the codec line shown with the last result at least...

**Comment by Chocobozzz** [comment]
Hello,

Please paste the URL of the video

**Comment by ROBERT-MCDOWELL** [comment]
https://secure.scanovid.com/w/sqPUT4DvfYGYmUjJejsQgH

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/37229de26e0979733d197b10811db17fab31abcc
