### ISSUE TITLE
Wrong error message on embeded player when clicking play on non started live

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5180]
### Describe the current behavior

I shared a link to a live on Mastodon. The live is not started yet.
If I click on «play» on mastodon, I got an error message «sorry, the player is not compatible»:
![image](https://user-images.githubusercontent.com/38844060/183379551-8d520446-9eb5-418f-879e-2b48867ee2d9.png)

You can see the post here:
https://mamot.fr/@John_Livingston/108782080579347690

### Steps to reproduce

1. Share a link to a live on Mastodon (for example). I think it should be the same if you embed the live in a web page.
2. Try to play the live

### Describe the expected behavior

The message should be something like «the live has not started yet».

### Additional information

* PeerTube instance:
  * URL:
  * Version: 4.2.2
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/aeb112edbe8524fdd25fcaa339e8cfab63bc16db
