### ISSUE TITLE
Views count after upgrade

### ISSUE THREAD

**Issue by geco** [Chocobozzz/PeerTube#5182]
### Describe the problem

Hello,
we upgraded from version 4.0.0. to 4.2.2.
We applied migration procedure.

Before upgrade, we had thousands of views, now we have 0-1 views per video.
We are investigating what's different into the stack, perhaps can you suggest some idea?
What's changed relevant between versions?
Watch time is counted same way?
Nginx stack can impact views count?

Thank you in advance

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by Chocobozzz** [comment]
Hello,

Please paste your instance URL

**Comment by Chocobozzz** [comment]
I'm not sure to understand: old videos have now their views counter equal to 0 after the upgrade?
I suggest you try to disable your plugins to see if they are responsible of your issue

**Comment by geco** [comment]
Old videos have thousands of views, new videos 0 or 1 views.
I've already tried uninstalling all plugins.

**Comment by geco** [comment]
Perhaps some Nginx config can block video view watchTime saving?

**Comment by Chocobozzz** [comment]
It seems you upgraded your instance but the client (JS/CSS files) are still in the old version. How did you install peertube?

**Comment by geco** [comment]
Thanks for the suggestion, it's odd, i'll take a look

**Comment by geco** [comment]
thank you so much @Chocobozzz you are right, that was the issue
