### ISSUE TITLE
New docker base install: Cannot register new user, cannot login as root

### ISSUE THREAD

**Issue by jeffrson** [Chocobozzz/PeerTube#5183]
### Describe the problem

I've gone through docker install instructions: https://docs.joinpeertube.org/install-docker

My installation is a bit different since I'm using an exisiting reverse proxy. But this shouldn't be the problem.

I can access the standard page. If I try to login as root, the page says "Invalid client: client is invalid". Furthermore it says that registration is not allowed for this instance.

My docker-compose.yml contains
```
volumes:
      - ./docker-volume/data:/data
      - ./docker-volume/config:/config
```
as does the file downloaded via `curl https://raw.githubusercontent.com/chocobozzz/PeerTube/master/support/docker/production/docker-compose.yml > docker-compose.yml` as written in the instructions. Now ./docker-volume/config stays empty. Is this correct?

### Additional information

* PeerTube instance URL: private so far
* PeerTube version: production-bullseye
* NodeJS version: ?
* Ffmpeg version: ?
* Redis version: 6-alpine
* PostgreSQL version: 13-alpine

**Comment by jeffrson** [comment]
Well - that's strange. Now I can login. Honestly I don't know what changed :-(

Anyway, where should production.yaml go for docker based installations? Really /config? I wonder because there's /app/config inside the container.

**Comment by Chocobozzz** [comment]
Put your `production.yaml` in `docker-volume/config/` directory on host
