### ISSUE TITLE
Missing information for enabling Typescript in plugins.

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5187]
### Describe the desired information/correction

In this documentation:
https://github.com/Chocobozzz/PeerTube/blob/2a491182e483b97afb1b65c908b23cb48d591807/support/doc/plugins/guide.md?plain=1#L915-L922

There are missing information to make it work.
You must also add this in your **front-end** tsconfig.json file:
```json
{
  "compilerOptions": {
    [...]
    "allowSyntheticDefaultImports": true,
    [...]
}
```

Otherwise you will get a compilation error.

Moreover, the v0.0.4 of the quickstart plugin uses Esbuild to compile the front-end code.
If you want Esbuild to work, so also have to add these two options: `"isolatedModules": true` and `"esModuleInterop": true`.

And, as said in the documentation, [Esbuild does not really compile typescript](https://esbuild.github.io/content-types/#typescript), it only ignores typing syntax. So you have to use `tsc -noEmit` to check your Typescript code.
Here is what I suggest to do: in your package.json file, before calling the `build.js` script, do `npx tsc --p client/tsconfig.json --noEmit && node ./scripts/build.js`.
You will also have to do this in the build.js script:
https://github.com/JohnXLivingston/peertube-plugin-open-on-my-instance/commit/1a52ac5944f6df880f5baabff2a475187135c4f7#diff-a992dd64a8c626fedc95d613f43602b91f6dc6339893afaf405dc05fa13c9cea

Maybe it would be simplier to provide a typescript-quickstart plugin? With both front-end and back-end code in Typescript?
I can help with that if you want. Basically, it would be like [this](https://github.com/JohnXLivingston/peertube-plugin-open-on-my-instance/tree/better_typescript_wip), the only customization there are for now is that I added Eslint, and I added two registerHook calls.

**Comment by Chocobozzz** [comment]
Hi,

Yes I think a dedicated quickstart for typescript plugins could be interesting!

**Comment by JohnXLivingston** [comment]
> Yes I think a dedicated quickstart for typescript plugins could be interesting!

Do you want me to initialize it?
On framagit or github?
Do you want to be the owner of the repository?

**Comment by Chocobozzz** [comment]
> Do you want me to initialize it?

Yes please, I won't have time to maintain it

> On framagit or github?

Where you want, we'll put the link in the documentation

> Do you want to be the owner of the repository?

I don't think I need to :)

**Comment by JohnXLivingston** [comment]
Ok. I'll do that next week!

**Comment by JohnXLivingston** [comment]
I am a little bit late, but here it is!
https://github.com/JohnXLivingston/peertube-plugin-quickstart-typescript
https://framagit.org/Livingston/peertube-plugin-quickstart-typescript

I let you choose which one you want to add in the documentation.

It comes with Typescript and linting. And I'm going to add SCSS support as well.

**Comment by Chocobozzz** [comment]
Hi,

Thanks!
You can add the link you want in the documentation. I'll let you make the PR :)

**Comment by JohnXLivingston** [comment]
> I'll let you make the PR :)

Done :)
