### ISSUE TITLE
Peertube instance detection in http response headers

### ISSUE THREAD

**Issue by sspi** [Chocobozzz/PeerTube#5188]
### Describe the problem to be solved

When an author paste an URL in a rich content editor, we need to detect that it is a Peertube video in order to properly transform the URL for different uses: full site url, emebedded view url, etc.

To know the nature of the content of an URL:
- With YouTube for example, it's simple: we know the domain.
- With a federated approach like Peertube, we must request the url with the http HEAD method in order to sniff the nature of the content.

But I don't see any HTTP response headers that could help sniff that a url is a Peertube instance (in https://tube.picasoft.net/).

### Describe the solution you would like

Add a custom HTTP response header in the html front pages `X-Peertube: 1.2.3` where `1.2.3` is the current version of the core Peertube.

**Comment by based-a-tron** [comment]
Would it not be better to check the `og:platform` meta property, if you're going to be fetching the front page anyway?
Maybe that should have a version attached to it, if necesary.

**Comment by sspi** [comment]
Thanks for your reply.

This would require for each URL analysis, a request in GET method and not HEAD and the parsing of the content, which is much more expensive. When a document contains hundreds of links it becomes problematic. 

At edition step we don't necessarily fetch front pages, but we adjust the user interface (buttons) in order to preview or open the remote content for example.
At building step (we transform the logical xml content in web site, pdf, etc) we rarely fetch the content (except when building an offline web content), but we construct the "good" url depending on the publishing context.

For the version, it will become useful when Peertube will change url syntax or add rendition parameters in a newer versions.

**Comment by Chocobozzz** [comment]
Hello,

You can use the NodeInfo endpoint that has been developed for that purpose:
 * well known endpoint: https://peertube2.cpy.re/.well-known/nodeinfo
 * nodeinfo endpoint: https://peertube2.cpy.re/nodeinfo/2.0.json

**Comment by sspi** [comment]
Unfortunately, that does not match my needs, 2 GET requests and 2 parsing per link are not sober enough. Never mind, I cannot generally integrate Peertube in my software.

Thanks for your quick reply.

**Comment by Chocobozzz** [comment]
Hi @sspi 

I added a `x-powered-by` header in https://github.com/Chocobozzz/PeerTube/commit/4765348107ddd21cd2a0b86093859aa2e23ac0f1

**Comment by sspi** [comment]
Good news, thank you! I will integrate Peertube.

**Comment by sspi** [comment]
PeerTube is now well integrated in the next Scenari 6.2, thanks again !
