### ISSUE TITLE
Disable update button in some cases

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5189]
### Describe the current behavior

click several time on update button while creating live stream will create many live stream as clicks.
this behavior should be also a problem for other cases

### Steps to reproduce

1. publish, click update many times

### Describe the expected behavior

update button must be disabled as long as no answer from the server

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/2f6e1730026b089cb18842a6996d50b928de440c
