### ISSUE TITLE
support ostatus for video preview in e.g. diaspora

### ISSUE THREAD

**Issue by paskalito** [Chocobozzz/PeerTube#519]
im really sorry if this is terribly uninformed, but i think it would make a big change in acceptance if the links to peertube would create little previews within a diaspora stream like youtube,vimeo,or media.ccc.de

unlike
https://nerdpol.ch/posts/4721060
but like
https://nerdpol.ch/posts/4654274

i think this can be done by supporting ostatus. but i actually dont know.

**Comment by rigelk** [comment]
Hi @paskalito ! Please look out for related issues before creating one, as #409  already covers this. Please document your issue there, or further document your difference in the current issue.
