### ISSUE TITLE
activitypub-http-* jobs raise "Error [ERR_CRYPTO_SIGN_KEY_REQUIRED]: No key provided to sign" on Ubuntu 22.04LTS

### ISSUE THREAD

**Issue by FiskFan1999** [Chocobozzz/PeerTube#5193]
### Describe the problem

Hey everyone,

I have recieved reports from other instance webmasters that my Peertube instance is not federating properly. I noticed that all jobs of type activitypub-http-broadcast-parallel, -broadcast, and -unicast (but not -fetcher, -follow, or -cleaner, those jobs succeed) fail with the following error. I feel like I messed up something with the installation, maybe installed a dependency that was too recent and had breaking changes. Everything else on the instance is working correctly, as far as I can tell. This is on ubuntu 22.04LTS.

```
Error [ERR_CRYPTO_SIGN_KEY_REQUIRED]: No key provided to sign
    at new NodeError (internal/errors.js:322:7)
    at Sign.sign (internal/crypto/sig.js:99:11)
    at /var/www/peertube/versions/peertube-nightly-2022-08-12/dist/server/helpers/peertube-crypto.js:90:37
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/peertube/versions/peertube-nightly-2022-08-12/node_modules/tslib/tslib.js:115:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Thank you in advance,

### Additional information

* PeerTube instance URL: `https://rankett.net`
* PeerTube version: `4.2.2-nightly-2022-08-12`
* NodeJS version: `v14.20.0`
* Ffmpeg version: `ffmpeg version 4.4.2-0ubuntu0.22.04.1`
* Redis version: `Redis server v=6.0.16 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=a3fdef44459b3ad6`
* PostgreSQL version: `psql (PostgreSQL) 14.4 (Ubuntu 14.4-0ubuntu0.22.04.1)`

**Comment by FiskFan1999** [comment]
From reading online, ERR_CRYPTO_SIGN_KEY_REQUIRED has to do with a key not being supplied to crypto.sign.sign(). I am using openssl v3.0.2 do you think this could be due to a parsing error similar to #4901 ?

**Comment by Chocobozzz** [comment]
Hello,

It seems there was an issue on peertube first startup to generate private/public keys for you instance actor. Please try to delete/recreate your database et rereun peertube. It will re create your instance actor. Check the logs if there is an issue at this step

**Comment by FiskFan1999** [comment]
@Chocobozzz thank you for the tip. I actually reinstalled peertube (from the latest nightly this time instead of latest release) and federation appears to be working now.

**Comment by ctsrc** [comment]
Hi, I have this same issue.

> Please try to delete/recreate your database et rereun peertube. It will re create your instance actor

Could you describe how to do this? For the benefit of myself and anyone else arriving here via Google searches

**Comment by Chocobozzz** [comment]
```
sudo -u postgres dropdb database_name
```

Then using the same command described in https://docs.joinpeertube.org/install/any-os#database

**Comment by ctsrc** [comment]
@Chocobozzz but that would delete all of my users and videos and everything

**Comment by ctsrc** [comment]
How can I achieve the same while still keeping all of my users and videos etc?

**Comment by Chocobozzz** [comment]
First, find which users are broken:

```
select * from actor where "privateKey" is null and "serverId" is null;
```
