### ISSUE TITLE
API to find a YouTube/Alternative Platform content on Peertube

### ISSUE THREAD

**Issue by FireMasterK** [Chocobozzz/PeerTube#5198]
### Describe the problem to be solved

I would like to find a video on Peertube from a given YouTube videoId/URL. This could potentially be extended to channels too.
LBRY/Odysee has an API for this: https://api.lbry.com/yt/resolve?video_ids=djeL6qUTDTo

I find that extensions like Peertubify, which use the search API have no guarantees that the video is in fact the same as on YouTube/Other Platforms, which is my main concern.

Related issue: https://github.com/Chocobozzz/PeerTube/issues/754

### Describe the solution you would like

An API that could be called to find videos/channels. Potentially like how LBRY/Odysee does it currently.

**Comment by Chocobozzz** [comment]
Hello,

I'm not sure to understand: you mean that finding on PeerTube videos that were imported from other platform through their original URL?

**Comment by FireMasterK** [comment]
Yes, that's what I want.

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/2467
