### ISSUE TITLE
Private instance (family, restricted community...)

### ISSUE THREAD

**Issue by AntoineMazuyer** [Chocobozzz/PeerTube#520]
Hello,

My question can be weird, but it is possible to made video accessible only for logged user on my instance ? I would like to make a platform to share videos ONLY with my family and I don't know if peertube could be suitable for this use.

Thanks in advance !

**Comment by mokas01** [comment]
Would be awesome, and complementary to https://github.com/Chocobozzz/PeerTube/issues/371

**Comment by Chocobozzz** [comment]
For now you have 2 solutions:
 * Create 1 account that you'll share with your family and upload the videos in `private` privacy
 * Upload your videos in `unlisted` (they will be federated but people will need to find the correct URL to watch it) and share the URL with your family

To have a real restricted instance, we would need:
 * An admin option to forbid followers
 * An admin option to allow only logged users to list/watch videos

**Comment by benrob0329** [comment]
Wouldn't this be equivalent to Mastodon's followers only privacy setting? With the account set up for non-automatic follow approval.

**Comment by anmol26s** [comment]
On YunoHost you can keep the web interface behind the SSO. So only the users who are logged in on YunoHost will be able to access the web interface. Further only group of users on YunoHost can be given access to the web interface,all other users will be treated same as pubic users and will not have access to the web interface of PeerTube.

**Comment by vincib** [comment]
I tried to use HTTP AUTH in the Nginx in front of the peertube, but any call by the js client to /api/ would not use the HTTP auth :/ 
no luck then. If anyone has a better idea :) 
(or I will end up with a port knocker on location / through a crude php script...)

**Comment by hauspie** [comment]
> For now you have 2 solutions:
> 
>     * Create 1 account that you'll share with your family and upload the videos in `private` privacy
> 
>     * Upload your videos in `unlisted` (they will be federated but people will need to find the correct URL to watch it) and share the URL with your family
> 
> 
> To have a real restricted instance, we would need:
> 
>     * An admin option to forbid followers
> 
>     * An admin option to allow only logged users to list/watch videos

I do not think that a full private instance was what the OP has in mind. 

Actually what I would really like in an instance is the possibility to set a video as only viewable by the users of my instance, on a per video basis. This would allow a semi-public instance that can be federated with others but with some videos (or channels maybe) that are only listed if you are connected on the local instance (and of course not federated).

Private video are not exactly what I want because they are not listed for connected users. I do not want to have to share a link for each video. Also, I specifically want that the video can only be viewed if the user is logged in MY instance. With private videos, if the private link is leaked, your only option is to remove the video. Of course that does not solve the problem of a malicious user of the instance downloading the video and leaking the video file itself, but if I want to set an instance for family usage, I can probably trust them not to.

**Comment by realityfabric** [comment]
How does WebTorrent work with this kind of privacy? Is it possible to restrict who is able to torrent the video files? If someone downloads a video, but is then restricted from viewing it, can they still seed the video?

And if your audience is intentionally small and isolated from the rest of the vidiverse (or even the fediverse) do you really need to be using WebTorrent? I do understand the desire for a personal social network for sharing videos, but this seems like the wrong technology for it.

I wouldn't be against this feature being implemented, I just would want to know what the security of it would look like before I relied on it.

**Comment by GauthierPLM** [comment]
I am also interested by having a private instance. I am adopting PeerTube for a small education institution and we would like to restrict access to our videos so only connected users can watch them.

Coupled with #2242 it would allow our instance to be fully controlled by our team and ensure that our content is only watched by our students.

Of course, it turns PeerTube into a full-private instance but I think it's a use case that companies or institutions might be interested in: it would let them rely on PeerTube to host their video content while ensuring that it remains private and intern to the company/institution.

**Comment by Chocobozzz** [comment]
I added an **Internal** privacy mode that you can set per video. In this setting, only logged in users of your instance will be able to list and watch it. The video is not federated.

If you would like to allow your users to only upload "Internal" videos, you can subscribe to https://github.com/Chocobozzz/PeerTube/issues/1969

**Comment by hauspie** [comment]
Awesome! many thanks!

**Comment by AntoineMazuyer** [comment]
Thanks a lot :)

**Comment by Bricklou** [comment]
I am trying to set up this private access functionnality on peertube and I think I have found some solutions to close totaly an instance on server and client side. I think that with a little more time and more work I would be able to make a Pull Request to add this feature even if won't be perfect.

**Comment by Bricklou** [comment]
I have somethink that is worker but I would like to know if it is usefull to restrict assets and statics file access when instance is configured as private ? By example, block videos and preview when user is not logged in.

(PS, my repo is there: [https://github.com/Bricklou/PeerTube/tree/private_mode](https://github.com/Bricklou/PeerTube/tree/private_mode))

**Comment by Agorise** [comment]
I hope my commit was not redundant, but I have a similar request here: 
https://github.com/Chocobozzz/PeerTube/issues/3470

**Comment by CodingAlbert** [comment]
> I am also interested by having a private instance. I am adopting PeerTube for a small education institution and we would like to restrict access to our videos so only connected users can watch them.
> 
> Coupled with #2242 it would allow our instance to be fully controlled by our team and ensure that our content is only watched by our students.
> 
> Of course, it turns PeerTube into a full-private instance but I think it's a use case that companies or institutions might be interested in: it would let them rely on PeerTube to host their video content while ensuring that it remains private and intern to the company/institution.

Hello GauthierPLM, did you succeed in setting the private Peertube? I am currently thinking of doing exactly the same, and would really appreciate any help or feedback.

**Comment by tomaytotomato** [comment]
I think in this case https://mediagoblin.org/pages/tour.html

Is a much more appropriate solution

**Comment by CodingAlbert** [comment]
> I think in this case https://mediagoblin.org/pages/tour.html
> 
> Is a much more appropriate solution

Yes, it looks like it! Especially because it allows sharing so many different media types. I am looking into it atm and getting in touch with project's main contributors. I will keep this thread posted.
