### ISSUE TITLE
Cannot save settings in admin panel

### ISSUE THREAD

**Issue by vladh** [Chocobozzz/PeerTube#5201]
### Describe the current behavior

When trying to save settings in the admin panel, the “Update configuration” button is grayed out (`disabled=""`). The following error message shows: “There are errors in the form:”, followed by nothing.

Complete HTML for that section:

```
<div _ngcontent-jmy-c209="" class="col-md-5 col-xl-5"><div _ngcontent-jmy-c209="" class="form-error submit-error ng-star-inserted"> There are errors in the form: <ul _ngcontent-jmy-c209=""><!----></ul></div><!----><!----><!----><input _ngcontent-jmy-c209="" type="submit" value="Update configuration" disabled=""></div>
```

I see no errors in any of my logs. There are no errors in the JS console, and there are no requests that return a non-200 response.

If I manually remove the "disabled" attribute from the button, I can then click the button and successfully save configuration changes.

Could you please let me know which steps I should follow to debug this?

This issue seems to be a duplicate of this one: https://framacolibri.org/t/there-are-errors-in-the-form-when-trying-to-use-administration-panel/14804

### Steps to reproduce

1. Visit admin panel

(I assume this has to do with some specific configuration on my part.)

### Describe the expected behavior

When visiting the admin panel and making a change, I expected to be able to press the “Update configuration” button.

### Additional information

I do not use Docker.

* PeerTube instance:
  * URL: https://video.clumsy.computer
  * Version: 4.2.2
  * NodeJS version: 14.20.0
  * Ffmpeg version: 4.2.7

* Browser name, version and platforms on which you could reproduce the bug: Firefox on Arch Linux
* Link to browser console log if relevant: (No errors)
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): (No errors)

**Comment by Chocobozzz** [comment]
I don't understand why the form is not `.valid` if there a no errors (that should be injected in ` <ul _ngcontent-jmy-c209=""><!----></ul>`).

Does this element populated if you fill change the form validity? (removing the instance name to create an error for example).

**Comment by vladh** [comment]
> IS this element populated if you fill change the form validity? (removing the instance name to create an error for example).

Yes!

```
 There are errors in the form:
    Instance name is required. 
```

**Comment by Chocobozzz** [comment]
Can you use the firefox debugger, open `webpack:///src/app/+admin/config/edit-custom-config/edit-custom-config.component.ts` and add a breakpoint in the `isUpdateAllowed()` function? You'll be able to access `this` in this function, that contains the `formErrors` and `form` attributes. `form` should contain the invalid state, and `form.controls` should indicate for every control which one is invalid.

**Comment by vladh** [comment]
Thank you for the detailed debugging instructions! It turns out the Twitter handle was the problem. When I installed PeerTube, I saw this in the config:

```
services:
    twitter:
      username: '@Chocobozzz'
```

I set this to an empty string, but reading the admin panel, it says “If you don't have a Twitter account, just leave the default value”. I've set it to `@Chocobozzz`, and this fixed the problem, thank you very much!

However, as a user, I'm now not certain whether your Twitter handle will show up somewhere on my instance. I think it would be best to allow an empty string here — I don't want any Twitter links at all on my instance.

**Comment by Chocobozzz** [comment]
Okay thanks, I'll fix this behaviour.

> I don't want any Twitter links at all on my instance.

You don't have any twitter link on your instance. It's just used to inject `<meta property="twitter:site" content="@Chocobozzz" />` in the HTML page to make Twitter happy when someone paste a PeerTube link on Twitter.

**Comment by vladh** [comment]
Got it, thank you very much! :)

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/8b69f9f02879ee3cf72bc9d4aa96cc71f18e6eea
