### ISSUE TITLE
4.2.2 HLS.JS regression/bug

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#5202]
### Describe the current behavior

Web player outputs HLS.js error: mediaError - fatal: true - manifestIncompatibleCodecsError when trying to play AV1 videos.

AV1 worked under 4.2.0 and I believe 4.2.1.

Can confirm it works under the "default" transcoding profile but not the custom AV1.

### Steps to reproduce

1. https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/master/Docs/Build-Guide.md in the section "SVT-AV1 ffmpeg plugin installation"

2. ffmpeg compile command 
`
./configure --enable-gpl --enable-version3 --enable-gnutls --enable-static --disable-debug --disable-ffplay --cc=gcc --enable-fontconfig --enable-gray --enable-libaom --enable-libopus --enable-libvpx --enable-libsvtav1 --enable-libx264`

3. transcoding profile debug plugin:

```
{
  "vod": [
    {
      "encoderName": "libopus",
      "profileName": "test",
      "outputOptions": ["-b:a 128k", "-strict -2"]
    },
    {
      "encoderName": "libsvtav1",
      "profileName": "test",
      "outputOptions": ["-crf 35", "-b:v 5000k"]
    }
  ],

  "live": []
}

{
  "vod": [
    {
      "encoderName": "libopus",
      "streamType": "audio",
      "priority": 1000
    },
   {
      "encoderName": "libsvtav1",
      "streamType": "video",
      "priority": 1000
    }
  ],

  "live": [ ]
}

```

### Describe the expected behavior

Video plays without issue.

### Additional information

* PeerTube instance:
  * URL: private
  * Version: 4.2.2
  * NodeJS version: 16
  * Ffmpeg version: git-2022-08-17-1eaa575

* Browser name, version and platforms on which you could reproduce the bug: Firefox

**Comment by Chocobozzz** [comment]
Hello,

Can you link a video transcoded in this format that doesn't work?

**Comment by SimplyCorbett** [comment]
https://user-images.githubusercontent.com/7935624/186281965-bbdd1cdb-2b71-4cd8-87c0-4d2a45fe2031.mp4

**Comment by SimplyCorbett** [comment]
https://drive.google.com/file/d/1fUGV0qvuDY1QRQ6c4xOfBkBQV-gzf6m3/view?usp=sharing

**Comment by SimplyCorbett** [comment]
Can also confirm VP9/Opus work, so it's specifically a AV1 bug.

**Comment by SimplyCorbett** [comment]
Well I recompiled ffmpeg & svtav1 with todays version and the problem is gone. I'll go ahead and just close this..
