### ISSUE TITLE
Can't find documentation on how logging in with mastodon or remote instances to comment works.

### ISSUE THREAD

**Issue by eyoxin** [Chocobozzz/PeerTube#5204]
I know there is interest from other federated projects on allowing the option for users from remote instances to be able to login to any instance like how peertube allows you to login using a mastodon account or a remote instance to comment but there is seemingly no documentation on how peertube allows this for them to learn how to implement it on their fediverse projects

**Comment by Booteille** [comment]
Hi!

I think everything you need is in the API documentation: https://docs.joinpeertube.org/api-rest-reference#tag/Video-Comments/paths/~1videos~1%7Bid%7D~1comment-threads/post

You can click on `authorizations` from this section to have informations about how to handle authentication. (You can also check out the "login" endpoint).

IMO, you've everything you need to succeed in what you need.

**Comment by eyoxin** [comment]
@Booteille that doesn't seem to be it

**Comment by Booteille** [comment]
> @Booteille that doesn't seem to be it

Could you be more specific about what is lacking, please?

**Comment by eyoxin** [comment]
> > @Booteille that doesn't seem to be it
> 
> Could you be more specific about what is lacking, please?

honestly im not sure i just saw someone link it on lemmy and the dev said it wasn't what they needed https://lemmy.ml/post/424308/comment/261196

**Comment by Chocobozzz** [comment]
Hello,

We're using `http://ostatus.org/schema/1.0/subscribe` `rel` in webfinger well known endpoint. I added an issue in our documentation repository: https://framagit.org/framasoft/peertube/documentation/-/issues/19

**Comment by eyoxin** [comment]
The first link you provided loads a page filled with ads
