### ISSUE TITLE
OpenidConnect and PeerTube

### ISSUE THREAD

**Issue by a772832** [Chocobozzz/PeerTube#5205]
### Describe the current behavior

Hi,

I have a problem updating the identifiers between the openId plugin [1] and Peertube [2].

If a user changes his email address but not his login the plugin does not update the user record
We get the following message: 

Cannot create such user: an actor with that name already exists.

in the SSO the user has updated his profile **demoexample@domain.fr** with the login **demo.example**

and the peertube keeps the old address **demo.example@domain.fr** and therefore signals that the username already exists 

[1] https://framagit.org/framasoft/peertube/official-plugins/-/tree/master/peertube-plugin-auth-openid-connect
 [2] https://github.com/Chocobozzz/PeerTube

### Steps to reproduce

1.
2.
3.

### Describe the expected behavior

If a user changes his email address but not his login the plugin does not update the user record
We get the following message: 

Cannot create such user: an actor with that name already exists.

in the SSO the user has updated his profile **demoexample@domain.fr** with the login **demo.example**

and the peertube keeps the old address **demo.example@domain.fr** and therefore signals that the username already exists 

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

Tracking this issue in the the official plugins repository: https://framagit.org/framasoft/peertube/official-plugins/-/issues/39
