### ISSUE TITLE
Unable to play videos in Iphone

### ISSUE THREAD

**Issue by upcastvideo** [Chocobozzz/PeerTube#5207]
### Describe the current behavior

The copy of the live streaming videos published after the live event has finished is unable to be played in mobile devices. The error is the following "The media could not be loaded, either because the server or network failed or because the format is not supported".

However uploaded videos are being played correctly. The problem is only on mobile Iphone, desktop works just fine for any OS.

I installed the instance in a docker droplet a couple of days ago.

### Steps to reproduce

1. Live streaming starts.
2. Live streaming ends.
3. Published video can´t be played mobile.

### Describe the expected behavior

I expect the published video after live event to be playable in Iphone.

### Additional information

* PeerTube instance:
  * URL: 
  * Version: Latest
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: IOS with firefox, safari and brave
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Booteille** [comment]
Hi!

Could you fill informations asked by the bug report template? Your instance URL, PeerTube, NodeJS & FFmpeg versions, etc.

Thanks.

**Comment by emansom** [comment]
Which browser? Which iPhone? Which iOS version?

**Comment by upcastvideo** [comment]
> Which browser? Which iPhone? Which iOS version?

I´m testing with iPhone 12 pro max with several browsers like safari, firefox and brave. iOS version is the last 15.6.1 since I upgraded it a couple of days ago.

**Comment by SimplyCorbett** [comment]
Can you link to the video?

**Comment by emansom** [comment]
PeerTube version? WebTorrent disabled? Default transcode settings or modified through plugin?

**Comment by SimplyCorbett** [comment]
This is not limited to transcoded live streams.

My iphone will not play any videos on my instance (VP9/Opus). Under experimental features in safari VP9 decoding is enabled. It also doesn't work in firefox.

This is on 4.2.2, nodejs 16 with git ffmpeg. Webtorrent is disabled and I am using HLS.

**Comment by SimplyCorbett** [comment]
Nevermind, my issue turned out to be opus. Apparently iphones hate it so I've moved back to AAC.

**Comment by vid-bin** [comment]
Well I’m confirming this issue as I experience it on my iPhone from diode.zone on the following video:

https://diode.zone/w/nAYj3r74uvH3yzoh91Y4DF

**Comment by Chocobozzz** [comment]
Thanks for the video URL. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/e4fc3697acb27c4192cbbb63eb94272a6cf7ce32
