### ISSUE TITLE
Unable to follow other instances

### ISSUE THREAD

**Issue by sebu77** [Chocobozzz/PeerTube#521]
If I try this curl command:
`curl -X POST "Content-Type:application/json" -H "Authorization: Bearer xxx" https://peertube.xxx.com/api/v1/server/following -d '{"hosts": ["peertube.cpy.re"]}'`

it returns me:
`{"error":"Cannot follow non HTTPS web server."}`

I received the same message when I tried in the web client.

**Comment by Chocobozzz** [comment]
It seems `webserver.https` is `false` in your configuration.

**Comment by Chocobozzz** [comment]
Use the [docker-compose](https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/docker-compose.yml) template, the HTTPS variable is already set.
