### ISSUE TITLE
Dots in usernames break Fediverse compatibility

### ISSUE THREAD

**Issue by FediVideos** [Chocobozzz/PeerTube#5210]
### Describe the current behavior

If a PeerTube username has dots (. aka full stops aka periods) in it, it will be impossible to follow it from Mastodon etc.

### Steps to reproduce

1. Create a username in PeerTube with . in it
2. Attempt to follow that user's address from Mastodon

### Describe the expected behavior

EIther dots should be forbidden in PeerTube usernames, or there should be a warning that the user will break compatibility with other Fediverse platforms if they use dots in their username.

### Additional information

* PeerTube instance:  videos.pair2jeux.tube
  * URL:
  * Version: 4.1.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by FiskFan1999** [comment]
what account name did you test this with? Can you try this on the latest release and/or nightly?

**Comment by Chocobozzz** [comment]
ping @FediVideos
