### ISSUE TITLE
Update Installation Instructions from NodeJS14 to NodeJS16

### ISSUE THREAD

**Issue by grower-rhyme** [Chocobozzz/PeerTube#5212]
### Describe the desired information/correction

Currently, when installing PeerTube, if you select "Any OS (recommended)," under the "dpendencies" section at the beginning, the documentation explicitly says to install NodeJS 14.x (See here: https://docs.joinpeertube.org/dependencies?id=debian-ubuntu-and-derivatives). Personally this caused me nearly two months of headache as my instance refused to send emails due to some sort of LetsEncrypt conflict with nodemailer. TL;DR: once I updated to NodeJS 16, it just suddenly worked. Therefore, I propose updating the documentation to suggest installing NodeJS 16 LTS to avoid this confusion and headache for future hosters (admins? whatever they're called).

**Comment by SimplyCorbett** [comment]
The next peertube release supports NodeJS 18 so that should be added as well.

**Comment by Chocobozzz** [comment]
Thanks, documentation changed in https://github.com/Chocobozzz/PeerTube/commit/a3de59ab728dc5c712a2985b8149d9d21116ca78
