### ISSUE TITLE
Channel Syncronization not accessible by end user

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#5216]
### Describe the current behavior

Under https://domain.tld/my-library/video-channel-syncs does not let the end user browse their synchronized channels saying "a moderator can only manage users".

The channel does sync though, it's just that the end user can't manage their channels.

I also can't figure out how to manage the users channel synchronization as the admin.

![cftYLIecJYJ9WgWFOXJh](https://user-images.githubusercontent.com/7935624/186538258-97de1f55-abb3-4366-b248-515d5e83b4c7.png)

Probably still a WIP but figured I'd report it anyway.

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL: private
  * Version: 4.2.2...5f016383a
  * NodeJS version: 18
  * Ffmpeg version: N-62475-g130d19bf20-static

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/d4d9bbc6f24522f5d63b0ab105a02f80ca98d702
