### ISSUE TITLE
NodeJS? Oh come on...

### ISSUE THREAD

**Issue by zilti** [Chocobozzz/PeerTube#522]
I thought this is FOSS. Not script kiddie realm.

**Comment by voronoipotato** [comment]
FOSS means free open source software, you can read the code so I really don't understand what isn't FOSS about this.  Feel free to do a total rewrite in whatever language you feel more comfortable in, just make sure it federates with PeerTube.

**Comment by voronoipotato** [comment]
This issue was a pretty rude thing to do. I don't really understand what provoked you to act out like this, but if you're old enough to contribute to FOSS you should be old enough to know better.

**Comment by Chocobozzz** [comment]
Well, it's TypeScript so... :grin:
