### ISSUE TITLE
When `action:api.video.updated` is triggered, `videoFiles` might be empty.

### ISSUE THREAD

**Issue by lutangar** [Chocobozzz/PeerTube#5221]
### Describe the current behavior

When `action:api.video.updated` is triggered at __video creation__, `videoFiles` might be empty.

It does work as expected when you actually __edit__ the video.

### Steps to reproduce

When `action:api.video.updated` hook is triggered,
then I attempt to find a video file *via* `peerTubeVideosHelpers.getFiles` method, 
and `hls.videoFiles` is __sometimes__ empty.
```typescript
const videoFiles = await peerTubeVideosHelpers
  .getFiles(id)
  .then(({ hls: { videoFiles } }) => videoFiles.sort(({ size: sizeA }, { size: sizeB }) => sizeA - sizeB));

if (videoFiles.length === 0) {
  this.logger.info(`No valid video file found for video "${id}", skipping.`);
  return;
}
```

From what I understand the `action:api.video.updated` event is also triggered video creation and this seems to happen when the __PeerTube__ transcoding is still ongoing.

On video edition, there's no such issue, the video file is always found.

### Describe the expected behavior

When `action:api.video.updated` hook is triggered, `hls.videoFiles` should always be populated.

### Additional information

Maybe `action:api.video.updated` should simply not be triggered at video creation time, but if it's the case, another reliable event should exists to get the video file reliabily.

**Comment by emansom** [comment]
Possibly related to lower-level task queue bug #5213

**Comment by Chocobozzz** [comment]
Hello,

`action:api.video.updated` is not triggered when you upload the file. But the web interface starts to upload the file in private, and then update the video when the user submits the second form.

If `hls.videoFiles` is empty it means HLS transcoded has not finished or is disabled. Then you should find files in `webtorrent.videoFiles`

**Comment by lutangar** [comment]
Sorry for the late reply and thanks for your feedback.

If it's the expected behaviour, from my point of view the following issue still stands :

> another reliable event should exists to get the video file reliabily.

Then would it makes sense to add another hook when the HLS transcoding is completed ?
Maybe something like `action:api.video.transcoding_completed` ? *Meaning when this event occurs `hls.videoFiles` is completed.*

I can create another issue as a feature request if needed.

**Comment by Chocobozzz** [comment]
> I can create another issue as a feature request if needed.

This hook is a good idea. Yes, please create a dedicated issue I would still have questions like if you need a hook when every transcoding job completes or if you need a "final" hook when all transcoding jobs finished.

**Comment by Chocobozzz** [comment]
> Lately, it happens when uploading a video from a URL (ex: from youtube).

I'm not sure we have an action hook to be notified of an imported video :thinking:

**Comment by lutangar** [comment]
Well a video file is available half the time after the same hook is triggered `action:api.video.updated` even for imported video.

**Comment by Chocobozzz** [comment]
> I can confirm that when uploading a video from a Youtube link, if the processing of the video isn't finished there are no videoFiles available. Is that expected ?

If you talk about `action:api.video.updated` yes it is, the video metadata can be updated even if the video is not yet imported by peertube. If the video is not imported there is no `webtorrent.videoFiles`.

We need to add an `action` hook so you can add an handler when an import finished. With this hook + `action:api.video.uploaded` it should correctly fit your use case

**Comment by lutangar** [comment]
> Superceded by #5343
