### ISSUE TITLE
Allow multiple storage locations

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#5225]
### Describe the problem to be solved

Peertube currently uses one central location to store videos in the streaming-playlists folder.

### Describe the solution you would like

Allow multiple storage locations so users who may run out of space can add another NAS or RAID array into the mix.

It would also be nice if S3 could be added into the mix with an existing installation (not sure if that's possible or not currently).

There are many solutions to this problem (CephFS/GlusterFS/MergerFS/etc) but peertube should have the functionality in place to use multiple storage locations for videos.

**Comment by Chocobozzz** [comment]
Hello,

Thanks for the issue but it's out of the scope of PeerTube. Prefer to use object storage instead.
