### ISSUE TITLE
Failing to move to object storage upon import-video-file

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5227]
### Describe the current behavior

When running import-video-file only 408,9 mb of the file (total is 2,4 gb) is moved to object storage. The same is happening every time I'm trying (I've just tried with one file), the file size is always 408,9 mb. When I run ffprobe on the original file there's no error shown.

### Steps to reproduce

object_storage.max_upload_part: 2GB
webtorrent.enabled: false
hls.enabled: true

1. `sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run create-transcoding-job -- -v [videoUUID]`
2. Wait for move-to-object-storage job is done. 
3. Check the size of the file.

### Describe the expected behavior

The whole file should have been moved.

### Additional information

* PeerTube instance:
  * Version: 4.2.2
  * NodeJS version: v16.17.0
  * Ffmpeg version: 5.1

**Comment by kukhariev** [comment]
Approximately how long does it take to upload 2 gigabytes on the s3?

**Comment by kukhariev** [comment]
with max_upload_part  set too 500mb?

**Comment by kukhariev** [comment]
Looks like the same [bug with 5mb part size](https://github.com/aws/aws-sdk-js-v3/issues/3816).

Anyway, maybe 2 gigabytes is not safe in terms of timeouts.

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/pull/5231
