### ISSUE TITLE
Resolutions set by account (override defaults)

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#5229]
### Describe the problem to be solved

Currently resolutions are set globally per instance

### Describe the solution you would like

Allow specific accounts access to different resolutions and bypass the instance defaults.

### Use case

I want to allow specifically vetted accounts access to 1440p-4k resolutions. Currently any user can use 1440p@60 which has a very long encoding time when using VP9.

**Comment by Chocobozzz** [comment]
Hello,

You'll be able to create a plugin that can alter resolutions to trancode in the next version: https://github.com/Chocobozzz/PeerTube/blob/develop/CHANGELOG.md#pluginsthemesembed-api using `filter:transcoding.manual.resolutions-to-transcode.result` hook
