### ISSUE TITLE
Add profile link to user drop down

### ISSUE THREAD

**Issue by rhaamo** [Chocobozzz/PeerTube#523]
It would be great to have a link to "My Profile" (```/accounts/X```) in the "dropdown" here:
![image](https://user-images.githubusercontent.com/8625/39257733-859be9b0-48b2-11e8-8ad4-6bb47bba69de.png)

~~Also the picture (on the left) does have a link to ```/account/settings``` which doesn't works, perhaps fix it by using ```/my-account/settings``` which is the one of the username right to it ?~~

**Comment by Chocobozzz** [comment]
Nice catch! The bug is fixed: https://github.com/Chocobozzz/PeerTube/commit/d62cf3234ccfca0223a9639782635f0fb6594f8c
