### ISSUE TITLE
On update Peertube does not change version

### ISSUE THREAD

**Issue by Graciasseo** [Chocobozzz/PeerTube#5230]
### Describe the problem

There is no way that I can update to version 4.2.2, I have tried the automatic way and the manual way, but the version of Peertube on the web does not change, it is still at 4.1.1.
I have followed all the documentation to update to the end.

I have followed the steps and searched for information and I can't find a solution.

Can you help me?

Thank you

### Additional information

* PeerTube instance URL: tv.reml.live
* PeerTube version: 4.1.1
* NodeJS version: v16.17.0
* Ffmpeg version: ffmpeg version 4.3.4-0+deb11u1
* Redis version: Redis server v=6.0.16
* PostgreSQL version: (PostgreSQL) 13.7 (Debian 13.7-0+deb11u1)
* Operating System: Debian GNU/Linux 11 (bullseye)
* Kernel: Linux 5.10.0-17-cloud-amd64

**Comment by vid-bin** [comment]
Are you sure the symlink peertube-latest is pointing at the new version? Have you tried shutting down the peertube service and moving the old peertube folder out of the versions folder then starting it again? Have you run flushdb/flushall on redis to see if its a cache issue? Have you cleared the cache of cloudflare, nginx, etc?

**Comment by Chocobozzz** [comment]
Hello,

Please use the forum for PeerTube install/upgrade related questions: https://framacolibri.org/c/peertube

**Comment by Graciasseo** [comment]
> Are you sure the symlink peertube-latest is pointing at the new version? Have you tried shutting down the peertube service and moving the old peertube folder out of the versions folder then starting it again? Have you run flushdb/flushall on redis to see if its a cache issue? Have you cleared the cache of cloudflare, nginx, etc?

Thanks for the suggestion and your answer.
I've tried all of this and it still doesn't work...
I will continue testing and post in the forum as Chocobozzz comments
