### ISSUE TITLE
AV1 1080p does play or show up in player

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#5234]
### Describe the current behavior

1440p works. But 1080p on the web player does not show up on a 1440p+1080p video. It does however show up under downloads.

https://vidbin.org/w/7xVt22f7x8LPn897rE9FQN

https://i.imgur.com/nbLSo20.png

https://i.imgur.com/1x2Tlcn.png

On a 1080p only video it will not play (exactly like in #5202.)

https://vidbin.org/w/aQnoVPiekMPEEmK1pMdDbR

### Steps to reproduce

Follow steps in #5202 

### Describe the expected behavior

Works as intended

### Additional information

* PeerTube instance:
  * URL: vidbin.org
  * Version: 4.2.2
  * NodeJS version: 16
  * Ffmpeg version: git

**Comment by vid-bin** [comment]
This issue is fixed on 4.2.2...5f016383a.

But only for newly transcoded videos. Old 1080p AV1 videos from 4.2.2 still have the same error.

**Comment by vid-bin** [comment]
Right so after testing this further 480p also doesn't work. I don't know why 1440p works.

**Comment by vid-bin** [comment]
The 1440p that works in firefox 104.0.1 doesn't play at all in either chrome or edge.

Is this a hls.js bug or a peertube bug?

**Comment by vid-bin** [comment]
Changing the following in the master.m3u8 allows 1080p to play:

From:

```
#EXT-X-STREAM-INF:BANDWIDTH=4733552,RESOLUTION=1920x1080,FRAME-RATE=60,CODECS="av01.0.9M.08,mp4a.40.2"
12884bb3-b43e-483a-837c-4e818c2fbf50-1080.m3u8
```

To:

```
#EXT-X-STREAM-INF:BANDWIDTH=4733552,RESOLUTION=1920x1080,FRAME-RATE=60,CODECS="av01.0.12M.08,mp4a.40.2"
12884bb3-b43e-483a-837c-4e818c2fbf50-1080.m3u8
```

**Comment by vid-bin** [comment]
As an example, here is an unmodified m3u8 which allows 1440p but not 1080p playback which can be set under quality-levels.

https://hls-js.netlify.app/demo/?src=https%3A%2F%2Fvidbin.org%2Fstatic%2Fstreaming-playlists%2Fhls%2F350bd69b-aa4d-4f77-acce-871ff2cbb84a%2F6bed4067-56d9-4e3f-ac76-ff6cb1cc17ef-master.m3u8&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOnRydWUsInN0b3BPblN0YWxsIjpmYWxzZSwiZHVtcGZNUDQiOmZhbHNlLCJsZXZlbENhcHBpbmciOi0xLCJsaW1pdE1ldHJpY3MiOi0xfQ==

Here is a modified m3u8 which allows both 1080p and 1440p playback.

https://hls-js.netlify.app/demo/?src=https%3A%2F%2Fvidbin.org%2Fstatic%2Fstreaming-playlists%2Fhls%2F350bd69b-aa4d-4f77-acce-871ff2cbb84a%2F6bed4067-56d9-4e3f-ac76-ff6cb1cc17ef-master2.m3u8&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOnRydWUsInN0b3BPblN0YWxsIjpmYWxzZSwiZHVtcGZNUDQiOmZhbHNlLCJsZXZlbENhcHBpbmciOi0xLCJsaW1pdE1ldHJpY3MiOi0xfQ==

**Comment by Chocobozzz** [comment]
Missed the `0` before `9M`. Should  be fixed by https://github.com/Chocobozzz/PeerTube/commit/01ec3975e0775163740607b45e5a35ffc25b55ed

**Comment by vid-bin** [comment]
@Chocobozzz Well I have good news and bad news. 4.2.2...01ec3975e fixes 480p and 1080p... but now 1440p doesn't work or show up in the resolution selection.

I'm assuming 4k has the same problem.

Test video: https://vidbin.org/w/wMrTcG2yprLJ8fV8o2vgqF

**Comment by Chocobozzz** [comment]
Can you provide a link of such video?

**Comment by vid-bin** [comment]
@Chocobozzz https://vidbin.org/w/mPTJwYTk4WX3neFUFag579

**Comment by vid-bin** [comment]
```#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=3367428,RESOLUTION=1920x1080,FRAME-RATE=60,CODECS="av01.0.09M.08,mp4a.40.2"
0540d8de-29b2-460e-9e58-109a865d2679-1080.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=4862483,RESOLUTION=2560x1440,FRAME-RATE=60,CODECS="av01.0.0cM.08,mp4a.40.2"
f51490ff-bccc-429e-ae64-5c3d705a9700-1440.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=9646024,RESOLUTION=3840x2160,FRAME-RATE=60,CODECS="av01.0.0dM.08,mp4a.40.2"
b8861d4d-741e-4d74-bd54-16934f36b03c-2160.m3u8
```

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/31951badb3f0582bb0c8b7cfc81ade438af824b7

**Comment by vid-bin** [comment]
Thanks! Appreciate how fast you work.
