### ISSUE TITLE
Looking for DB setup script.

### ISSUE THREAD

**Issue by a-kenji** [Chocobozzz/PeerTube#5237]
### Describe the desired information/correction

I am looking for a script allowing for initialization and/or migration of the database, without starting peertube itself. Is that already provided?

I am looking to install the plugins through a configuration file, rather than an interface and for that I am looking at the following steps:
- initialize peertube
- install plugins
- restart peertube

With a script/command that can set the database itself up, the restart of the peertube instance would not be needed.

**Comment by Chocobozzz** [comment]
Hello,

Can you describe your use case?

**Comment by Chocobozzz** [comment]
Is starting and automatically stopping PeerTube after DB creation a solution for you?

**Comment by Chocobozzz** [comment]
Ping @a-kenji

**Comment by a-kenji** [comment]
Ah, thank you for the ping!

> Is starting and automatically stopping PeerTube after DB creation a solution for you?

This is indeed our current solution and it works.
We thought since other functionality is exposed as a script, it could be sensible that the DB creation would be as well, which would make the initial setup a little bit smoother.

If you think this is out of scope, we of course understand.

**Comment by Chocobozzz** [comment]
It's an interesting use case, but unfortunately we won't have time to maintain such script. If the start & stop peertube doesn't work don't hesitate to comment this issue so we can find another solution :)
