### ISSUE TITLE
Opus does not play in chrome

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#5238]
### Describe the current behavior

Works on firefox but doesn't work in chrome. Changing libopus to aac fixes it.

https://vidbin.org/w/npw8nJGNiX1KWBDC8CWBDC

### Steps to reproduce

1. Encode VP9 and opus
2. Try playing on chrome

### Describe the expected behavior

works as expected

### Additional information

* PeerTube instance:
  * URL: vidbin.org
  * Version: 4.2.2
  * NodeJS version: 16
  * Ffmpeg version: Latest master. Tested on other versions as well.

**Comment by emansom** [comment]
Direct mp4 plays fine on Chromium, seems like a HLS.js issue.

![Schermafdruk van 2022-09-05 18-50-03](https://user-images.githubusercontent.com/981494/188491765-bf7f0037-3c8f-4cd2-97b6-980228ef2cd2.png)

Console logs the following:

![Schermafdruk van 2022-09-05 18-53-45](https://user-images.githubusercontent.com/981494/188491978-c0a92287-32e0-4f55-8e2e-28d7476c93f5.png)

**Comment by emansom** [comment]
> Direct mp4 plays fine on Chromium, seems like a HLS.js issue.

Or a mismatch in codec info in the `.m3u8` as mentioned in #5234.

**Comment by Chocobozzz** [comment]
Hello,

I think hls.js doesn't initialize correctly the audio source buffer because we specify `opus` instead of `Opus`. See the original issue on their repository: https://github.com/video-dev/hls.js/issues/4527

**Comment by vid-bin** [comment]
Changing it to Opus prevents playback on firefox and chrome.

**Comment by vid-bin** [comment]
Doesn't look like there is an easy solution to this problem though.. may have to stick with AAC.

**Comment by emansom** [comment]
Serving other `.m3u8` selectively based on the [User-Agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) string maybe.
