### ISSUE TITLE
Show video count and channel count in the user profile

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#524]
Right now a user's profile only shows their number of subscribers. Additional (more?) relevant info typically includes the viewcount, the number of videos and here, the nubmer of channels. I suggest we add the latter two to the profile view added in 0626e7a.

For instance, from the current line berow the user name on the side of the user picture that says:

> 102 subscribers

to

> 102 subscribers, 40 videos

and if the user uses multiple channels (something we plan to add)

> 102 subscribers, 40 videos accross 3 channels

---

Implementing it requires to cover the following tasks: 

- add the information display to the view (ui)
- make the request to the database, since we have no dedicated function to retrive such user stats *yet*
  - add a migration to the database, adding a column listing these user stats (perf)
  - request info from this column in the controller
- add related tests

**Comment by Chocobozzz** [comment]
Now we have the account/video channel pages, I added the number of published videos: https://github.com/Chocobozzz/PeerTube/commit/0bf1f2652382089c06434a7d297b638aad778b52
