### ISSUE TITLE
Transcoding queue statistics

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#5242]
### Describe the problem to be solved

User has no idea what position their video is in on the transcoding queue.

### Describe the solution you would like

Under https://url.tld/my-library/videos display position in the transcoding queue after "Waiting transcoding" so it says "Waiting transcoding position 6 of 20" as an example.

And perhaps under the instance statistics on about/instance#statistics display how many videos are currently transcoding on the peertube instance.

**Comment by Chocobozzz** [comment]
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/799
