### ISSUE TITLE
import from other peertube instance does not work

### ISSUE THREAD

**Issue by rocky-III** [Chocobozzz/PeerTube#5244]
### Describe the current behavior

import fom YT does work but 
import from other peertube instance does NOT work

### Steps to reproduce

. Click publish > import with URL
    Paste URL from a peertube video
    Says : "Congratulations, the video behind https://xxx.xx.xx/w/eQSYgM9gEWETcJEEhLuZhb will be imported! You can already add information about this video."
    most of the fields are filled :-)
    When you click "upate" button at the end of the page, it says "Sorry, but something went wrong
    Video not found

### Additional information

VPS   
PeerTube Version | 4.2.2
Yunohost 11.0.9.14 

under /my-library/video-imports

 I see this error:

```
ffprobe exited with code 1
ffprobe version 4.3.4-0+deb11u1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55e3e2bdea00] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55e3e2bdea00] moov atom not found
/home/yunohost.app/peertube/storage/tmp/d47afe5d772c6402d69e01d24af8ddba6b73c788c326f2b6479283b1f4626782-import.mp4: Invalid data found when processing input
```

Waht could I try - Thanks for help

**Comment by vid-bin** [comment]
Assuming you're using yt-dlp since youtube-dl is horribly outdated what version is your yt-dlp?

Run the following command to find out:

`/var/www/peertube/storage/bin/./yt-dlp -v`

**Comment by rocky-III** [comment]
some logs: https://paste.yunohost.org/raw/efamimosup

**Comment by vid-bin** [comment]
Can you answer the question? Thx

**Comment by rocky-III** [comment]
can you help me - how to do this ?

**Comment by vid-bin** [comment]
> can you help me - how to do this ?

```
systemctl stop peertube

nano /var/www/peertube/config/production.yaml

change name: 'youtube-dl' under import to 'yt-dlp'. You may wnt to enable force_ipv4 to true as well.

-> Save file

systemctl start peertube
```

**Comment by rocky-III** [comment]
THANKS but that did not help - same error

**Comment by vid-bin** [comment]
Please provide the ouput of /var/www/peertube/storage/bin/./yt-dlp -v

**Comment by vid-bin** [comment]
I'm able to successfully import https://diode.zone/w/f8ifBFc3PdJ3HqVsdh1gNf with ffmpeg master (git-2022-09-07-ff6f2c5) and the latest yt-dlp.

**Comment by rocky-III** [comment]
```
admin@admin:~$ sudo /var/www/peertube/storage/bin/./yt-dlp -v                                                                   
sudo: /var/www/peertube/storage/bin/./yt-dlp: command not found      
```

**Comment by vid-bin** [comment]
> ```
> admin@admin:~$ sudo /var/www/peertube/storage/bin/./yt-dlp -v                                                                   
> sudo: /var/www/peertube/storage/bin/./yt-dlp: command not found      
> ```

You are not using yt-dlp then. **I also have no idea how this is managed on yunohost and you may need to open a support ticket with that platform**.

Make sure the production.yaml file shows yt-dlp then run the following to manually download it:

```
systemctl stop

cd /var/www/peertube/storage/bin && wget https://github.com/yt-dlp/yt-dlp/releases/download/2022.09.01/yt-dlp && chown peertube:peertube /var/www/peertube/storage/bin/yt-dlp && chmod +x /var/www/peertube/storage/bin/yt-dlp

systemctl start
```

**Comment by rocky-III** [comment]
What I´m doing wrong ?
`admin@admin:~$ sudo cd /var/www/peertube/storage/bin && wget https://github.com/yt-dlp/yt-dlp/releases/download/2022.09.01/yt-dl
p && chown peertube:peertube /var/www/peertube/storage/bin/yt-dlp && chmod +x /var/www/peertube/storage/bin/yt-dlp              
sudo: cd: command not found                                                                                                     `

**Comment by vid-bin** [comment]
Well what you're doing wrong is using sudo on a cd command.

**Comment by rocky-III** [comment]
`admin@admin:~$ cd /var/www/peertube/storage/bin && wget https://github.com/yt-dlp/yt-dlp/releases/download/2022.09.01/yt-dlp && 
chown peertube:peertube /var/www/peertube/storage/bin/yt-dlp && chmod +x /var/www/peertube/storage/bin/yt-dlp                   
-bash: cd: /var/www/peertube/storage/bin: Permission denied                                                                     `

**Comment by vid-bin** [comment]
run `su -` to become root if the admin user on yunohost doesnt have sudo privileges.

I have no idea how yunohost works, sorry.

**Comment by vid-bin** [comment]
And thats assuming you were even able to save the modified production.yaml...

**Comment by rocky-III** [comment]
`root@admin:/home/admin# cd /var/www/peertube/storage/bin && wget https://github.com/yt-dlp/yt-dlp/releases/download/2022.09.01/y
t-dlp && chown peertube:peertube /var/www/peertube/storage/bin/yt-dlp && chmod +x /var/www/peertube/storage/bin/yt-dlp          
bash: cd: /var/www/peertube/storage/bin: No such file or directory                                                              `

**Comment by vid-bin** [comment]
Open a support ticket with yunohost as they aren't following the standard installation of peertube.

Also if that folder doesnt exist why does /var/www/peertube/config/production.yaml??

**Comment by rocky-III** [comment]
Ok Thanks anyway

**Comment by vid-bin** [comment]
I want to emphasize that I am using the latest yet-flip, ffmpeg master and the video I linked above.

It’s possible the video format you’re trying to import has issues but you haven’t given us a url to test.

**Comment by rocky-III** [comment]
i tested the upload with several videos form several different PT servers -same result

**Comment by Chocobozzz** [comment]
Hello,

Try to mimic the default `production.yaml` configuration to use `yt-dlp`: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L535

**Comment by rocky-III** [comment]
@Chocobozzz    just to be clear - this does NOT work with PeerTube Yunohost installation - maybe because yt-dlp is not installed

**Comment by Chocobozzz** [comment]
PeerTube installs and manage youtube-dl/yt-dlp binaries by itself

**Comment by rocky-III** [comment]
@Chocobozzz THANKS - good to know... than the described problem must have a different cause.

**Comment by rocky-III** [comment]
@Chocobozzz  so what does this mean: 

```
admin@admin:~$ sudo /var/www/peertube/storage/bin/./yt-dlp -v                                                                   
sudo: /var/www/peertube/storage/bin/./yt-dlp: command not found    
```

**Comment by emansom** [comment]
> @Chocobozzz so what does this mean:
> 
> ```
> admin@admin:~$ sudo /var/www/peertube/storage/bin/./yt-dlp -v                                                                   
> sudo: /var/www/peertube/storage/bin/./yt-dlp: command not found    
> ```

That `/./` inside `/var/www/peertube/storage/bin/` is evidently not a directory.
