### ISSUE TITLE
User video quota does not match instance usage

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#5247]
### Describe the current behavior

One user has uploaded 39GB of video according to /admin/users/list. However the instance quota shows 78GB uploaded.  du -h under streaming-playlists shows 80GB.

This is the only active user on my instance currently. The rest are negligible in terms of upload.

![example1](https://user-images.githubusercontent.com/112714131/189228937-9467514d-3907-4dc8-a374-ee369b9fe8b0.png)

![example2](https://user-images.githubusercontent.com/112714131/189228964-9c409c72-cd19-4eef-afbf-af67377db319.png)

### Additional information

* PeerTube instance:
  * URL: https://vidbin.org
  * Version: 4.2.2
  * NodeJS version: 16
  * Ffmpeg version: master

**Comment by Chocobozzz** [comment]
Hello,

As stated in the configuration the quota only takes into account the uploaded file: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L374

I think we should add this explanation in the web interface too (user edit form and admin config form)

**Comment by Mike35538** [comment]
Maybe showing both totals would be helpful for admins. Show the amount the user has uploaded (combined space of his original video file uploads), then also show the total space used including all of the transcoded versions for that user.

For example, Used 25GB of 200GB Quota (Total storage used w/transcoding: 55GB)

**Comment by vid-bin** [comment]
Well that makes sense.

**Comment by Chocobozzz** [comment]
@thecashewtrader At the bottom of https://peertube2.cpy.re/about/instance

**Comment by thecashewtrader** [comment]
I see, I don't think per user storage is stored though.
Should I implement your original suggestion?
> I think we should add this explanation in the web interface too (user edit form and admin config form)

**Comment by Chocobozzz** [comment]
Sure!
