### ISSUE TITLE
Private or unlisted channels/lists which applies to all including videos

### ISSUE THREAD

**Issue by mokazemi** [Chocobozzz/PeerTube#5248]
### Describe the problem to be solved

We're planning to use PeerTube as our video hosting platform. We have video courses which their videos should only be shown to those who enrolled the course, not publicly. So we should make the videos unlisted and then put the direct link for students, or embed the videos. Right now the only option I found was to make all the videos individually unlisted, which is hard to to and may be forgotten. 

### Describe the solution you would like

There should be an option to make the whole channel/list private or unlisted, including all of its videos. (Probably overrides video privacy settings)

**Comment by vid-bin** [comment]
Change the privacy setting to unlisted in the production.yaml and restart your peertube instance.

The only issue is all videos will be unlisted by default as its not per channel.
