### ISSUE TITLE
Watch Time and Average Watch Time of stats is in negative

### ISSUE THREAD

**Issue by raazkarkee405** [Chocobozzz/PeerTube#5251]
### Describe the current behavior

The average watch time and total watch time of a video are not visible on the stats page due to the negative values returned from the database table.  Also, the watch time graph is downward due to negative values.

I don't know whether the watch time data can be negative or not, but I believe it should be always positive. And also, I don't know how negative data got inserted into the column `watchTime` of the table `localVideoViewer`.

### Steps to reproduce

1. Can be on any video.
2. Open video stats and view the average watch time, total watch time, and watch time graph.
(Note: This might or might not be reproduced in your instance)

![image](https://user-images.githubusercontent.com/26194365/189611699-25229398-6837-4711-9f0a-080e4bed66a1.png)
![image](https://user-images.githubusercontent.com/26194365/189611976-aae78b42-c5e5-41b4-9dbd-baa92cabe360.png)
![image](https://user-images.githubusercontent.com/26194365/189612767-bf543c53-f2c0-4ad4-8894-7b04ab2addd6.png)

### Describe the expected behavior

The `localVideoViewer` table should not contain negative data.

### Additional information

* PeerTube instance:
  * URL: Private
  * Version: 4.2.2
  * NodeJS version: 16+
 
* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

It should be fixed in 4.3 by https://github.com/Chocobozzz/PeerTube/commit/a49407524fc1212299a41d7c5330f27b36112167
