### ISSUE TITLE
About plugins and themes on the search list

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5252]
### Describe the problem

It would be great to make a big cleanup of all plugins and themes since some are broken, website or git repo not existing anymore nor updated or abandoned.
thanks!

**Comment by Chocobozzz** [comment]
Hello,

Can you make a list of such broken plugins?

**Comment by ROBERT-MCDOWELL** [comment]
I cannot check all plugins obviously but some like:
hive-tube
videojs-vr
ungamify-plus
custome-page
background-play
auto-set-lang
beetoons-tv
hide-channels-in-search-result
telegram
player-api
vigilante-tv
...

**Comment by Booteille** [comment]
Is there a kind of API saying compatible PeerTube versions for a plugin?

That would maybe help to give a warning to admins (saying something like "This plugin has been made for an older version of PeerTube and would maybe not work with your version." or "This plugin has been made for a newer version of PeerTube and is not compatible with yours.")

**Comment by Chocobozzz** [comment]
Yes there is. Plugin versions that require a newer version of PeerTube are filtered out so your PeerTube instance don't install them. But I'm not sure the minimum compatibility version would be appropriate to decide if a plugin is broken or not.

**Comment by Nalem14** [comment]
> auto-set-lang

I have made this plugin a month ago and it is fully functional hihi ^^
It permit to auto-complete the language field by browser lang when you upload new video
Also auto define video list lang filter to the browser language where visiting website as guest

**Comment by ROBERT-MCDOWELL** [comment]
@Chocobozzz 
all the plugins I listed above are more than not updated, they don't exist anymore (404 or website does not exist anymore)

**Comment by Nalem14** [comment]
> @Chocobozzz all the plugins I listed above are more than not updated, they don't exist anymore (404 or website does not exist anymore) @Nalem14 yes it would be worth but more interesting a code checking or something like GIT approving that the code does not destroy the peertube code... A plugin can be outdated and work very well so it's not a good stat.

I know yes, but auto-set-lang is not dead ^^
https://git.orion-serv.fr/Orion/Peertube-plugins

So, else why not add a button "report as outdated" to downvote a plugin and if a certain amount of vote are made during a window time it is hidden from the list ?

Also we can make a "community moderators" that have permission to blacklist a plugin. So we can report outdated / destructive plugin and it will be blacklisted.

If Chocobozz don't wan't to manage this, why not add a hook filter "plugin-list", and permit us to make a plugins that doing that. We can share a list between instances, like auto-mute or auto-blacklist plugin.

**Comment by ROBERT-MCDOWELL** [comment]
@Nalem14
never been a fan of upvote nor downvote as all can be spoiled for X reasons.

**Comment by Chocobozzz** [comment]
Please open the issue on https://framagit.org/framasoft/peertube/plugin-index and only list plugin that are really broken.
