### ISSUE TITLE
Possibility for exact search on sepiasearch.org

### ISSUE THREAD

**Issue by maninthemiddle01** [Chocobozzz/PeerTube#5254]
### Describe the problem to be solved

If I search I'll be shown results for similar words, even if I put the word/phrase in quotation marks. It would be nice, if there is a possibility to have exact results without being confused if somewhere in the results is a video for the exact term.

### Describe the solution you would like

Make an option for exact search or just the possibility for it if search term is in quotation marks.

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue. It's already tracked by https://framagit.org/framasoft/peertube/search-index/-/issues/17
