### ISSUE TITLE
[4.3.0-rc.1] When updating video metadata, "TypeError: Cannot read properties of undefined"

### ISSUE THREAD

**Issue by DeadSuperHero** [Chocobozzz/PeerTube#5255]
### Describe the current behavior

Whenever I try to update content on a video, the update page ends up not loading. Upon closer inspection, the console in my browser produces a TypeError:

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'path')
TypeError: Cannot read properties of undefined (reading 'path')
    at _ (channel.ts:43:27)
    at channel.ts:28:25
    at Array.map (<anonymous>)
    at channel.ts:24:12
    at map.js:7:37
    at h._next (OperatorSubscriber.js:13:21)
    at h.next (Subscriber.js:31:18)
    at throwIfEmpty.js:9:24
    at h._next (OperatorSubscriber.js:13:21)
    at h.next (Subscriber.js:31:18)
    at At (zone.js:1211:31)
    at At (zone.js:1165:17)
    at zone.js:1278:17
    at o.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26254:33)
    at o.invokeTask (zone.js:405:60)
    at pt.runTask (zone.js:178:47)
    at k (zone.js:585:35)
    at c.invokeTask [as invoke] (zone.js:491:21)
    at T (zone.js:1661:18)
```

At first, I thought that maybe this was caused by a broken plugin (PeerTube Chapter Plugin), but it seems to happen on all of my videos now. This happens both from an individual video page, as well as the My Videos library page.

### Steps to reproduce

1. Upgrade Peertube to 4.3.0-RC1
2. Go to a video you've already uploaded
3. Click "..." then "Update"

### Describe the expected behavior

PeerTube should successfully redirect to the Update function to adjust video metadata.

### Additional information

* PeerTube instance:
  * URL: https://spectra.video
  * Browser name, version and platforms on which you could reproduce the bug: Firefox, and Chrome-based browser
  * Version: 4.3.0-RC1
  * NodeJS version:  18.9.0
  * Ffmpeg version: 4.3.1-4ubuntu1:

**Comment by Chocobozzz** [comment]
Hi,

Did you follow https://github.com/Chocobozzz/PeerTube/releases/tag/v4.2.0 important notes? In particular running the migration script

**Comment by DeadSuperHero** [comment]
Oh, that totally fixed it! Thank you.
