### ISSUE TITLE
View video in original resolution

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#5258]
### Describe the problem to be solved

Currently the only options in the player are normal mode & theater mode

### Describe the solution you would like

Add an original resolution mode to the player

**Comment by Chocobozzz** [comment]
We already provide original resolution. So I'm not sure to understand the feature request.

**Comment by vid-bin** [comment]
The player has theater mode and normal mode.

But if you're playing say a 480p video in the player it stretches the video in both theater mode and normal mode.

Instead of doing this have the video displayed in original resolution (scaled) so it's not stretched.

**Comment by Chocobozzz** [comment]
But transcoding should keep video ratio and the player adds black borders to not stretch the video :thinking:
