### ISSUE TITLE
Channel Synchronisation list limited to 10 results (no pagination)

### ISSUE THREAD

**Issue by Nalem14** [Chocobozzz/PeerTube#5259]
### Describe the current behavior

I have set max channel to sync per user to 25, but when viewing my list I can't see more than 10 results. (can see first results by ordering date asc/desc)

### Steps to reproduce

1. Go to video channel synchronisations
2. See that there is no pagination

### Describe the expected behavior

I like to have a pagination to see all results

### Additional information

* PeerTube instance:
  * URL: https://www.orion-hub.fr
  * Version: 4.3.0-rc.1
  * NodeJS version: 
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: 
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/c95fbe65530191d7be22341815ecb743c139396f
