### ISSUE TITLE
Restarting peertube forces x264 transcodes on video queue

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#5260]
### Describe the current behavior

Use transcoding-profile-debug with a custom video codec. Have videos queued for transcoding. Restart peertube - all videos in queue are now using the default transcoding profile (x264).

NEW videos added to the queue will use the custom profile. If they finish - great. Another restart will force x264 on the existing queue.

### Steps to reproduce

Described above

### Describe the expected behavior

Custom profile is kept through restart.

### Additional information

* PeerTube instance:
  * URL: vidbin.org
  * Version: 4.3.0-rc.1
  * NodeJS version: 18
  * Ffmpeg version: git

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/4404a7c467a2c6863728127eeff5ca4b59619940
