### ISSUE TITLE
The user creation date is not displayed

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5261]
### Describe the current behavior

If you select the Russian language of the interface, the Administration->Overview->Users section does not display the date of account creation

![2](https://user-images.githubusercontent.com/11453567/190066966-6906fb67-db52-4aaf-94a9-549370bdb135.png)

If you select the English language of the interface, then all dates are displayed correctly

![1](https://user-images.githubusercontent.com/11453567/190067033-4954b74b-2684-4978-9f80-6318eb83789b.png)

### Additional information

* PeerTube instance:
  * URL: https://peervideo.ru
  * Version: 4.3.0-rc.1

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/fc3784583ce383cec8619be5b1d311b340b645f9
