### ISSUE TITLE
Error build client: mv: cannot stat 'dist/build/vi': No such file or directory

### ISSUE THREAD

**Issue by Izorkin** [Chocobozzz/PeerTube#5263]
### Describe the problem

Error build client in Peertube version 4.3.0-rc.1:
```
peertube> > peertube@4.3.0-rc.1 build:client
peertube> > bash ./scripts/build/client.sh
peertube> mv: cannot stat 'dist/build/vi': No such file or directory
```
I was unable to track down commit after which the build error started to occur

### Additional information

* PeerTube version: v4.3.0-rc.1
* NodeJS version: v16.17.0

**Comment by Chocobozzz** [comment]
Can you try to run manually `./scripts/build/client.sh`?

**Comment by Izorkin** [comment]
Error:
```
peertube> Error during step 'resolvePaths'
peertube> compilerOptions.baseUrl is not set in tsconfig
peertube> mv: cannot stat 'dist/build/vi': No such file or directory
error: builder for '/nix/store/cfqflbqmfyprca1x2qkxknmblwhn5dlb-peertube-4.3.0-rc.1.drv' failed with exit code 1;
```

**Comment by Izorkin** [comment]
It is likely that this condition has now started working and throwing an error:
```
if [ -z ${1+x} ] || ([ "$1" != "--light" ] && [ "$1" != "--analyze-bundle" ]); then
```

**Comment by Izorkin** [comment]
Found out that this command does not work for me:
```
node --max_old_space_size=8192 node_modules/.bin/ng build --configuration production --output-path "dist/build" $additionalParams
```

**Comment by Izorkin** [comment]
@Chocobozzz found commit - https://github.com/Chocobozzz/PeerTube/commit/f552ca84a568b77062d3e4fc06fb9e3096529b1b

**Comment by emansom** [comment]
Have you installed all dependencies?

Execute `yarn install` inside the `client` directory and then once again in the root of the project.

**Comment by Izorkin** [comment]
Yes, all dependencies are installed correctly.
During build process on NixOS, the following commands are executed - https://github.com/NixOS/nixpkgs/blob/ae6664f06c4cfbf510f29efda84754436a9aafca/pkgs/servers/peertube/default.nix#L46-L90

I guess the error happened after updating angular/cli.

**Comment by Izorkin** [comment]
Yes, the problem is with angular/cli.
```diff
diff --git a/client/package.json b/client/package.json
index 1c9c04c27..db514744c 100644
--- a/client/package.json
+++ b/client/package.json
@@ -34,7 +34,7 @@
     "@angular-eslint/template-parser": "13.5.0",
     "@angular/animations": "^14.0.1",
     "@angular/cdk": "^14.0.1",
-    "@angular/cli": "^14.0.1",
+    "@angular/cli": "^13.0.1",
     "@angular/common": "^14.0.1",
     "@angular/compiler": "^14.0.1",
     "@angular/compiler-cli": "^14.0.1",
diff --git a/client/yarn.lock b/client/yarn.lock
index 590c3128a..ef41ff7b5 100644
--- a/client/yarn.lock
+++ b/client/yarn.lock
@@ -191,10 +191,10 @@
   optionalDependencies:
     parse5 "^5.0.0"

-"@angular/cli@^14.0.1":
-  version "14.0.1"
-  resolved "https://registry.yarnpkg.com/@angular/cli/-/cli-14.0.1.tgz#3cfefc32155140812ce6145e3d1021026d971aed"
-  integrity sha512-5NUfpHlIQ+BipsHIMHImP2bXu5nJcyr4sbs8Otf5ReCcqculJGfKwX0gYYgLfExbw1r4JtCTDggYanUcVgqkdw==
+"@angular/cli@^13.0.1":
+  version "13.3.0"
+  resolved "https://registry.yarnpkg.com/@angular/cli/-/cli-13.3.0.tgz#77ec936392766462e6a0a3334f2cd33efacfaefc"
+  integrity sha512-2qCKP/QsyxrJnpd3g4P/iTQ4TjI04N8r+bG5YLLfudoMDsQ/Ti4ogdI7PBeG2IMbRylZW9XLjHraWG42+Y9tWw==
   dependencies:
     "@angular-devkit/architect" "0.1400.1"
     "@angular-devkit/core" "14.0.1"

```

**Comment by Chocobozzz** [comment]
> Found out that this command does not work for me:

What is the error?

**Comment by Izorkin** [comment]
@Chocobozzz `node_modules/.bin/ng` command not executing when running script `./scripts/build/client.sh`. Rolling back `angular/cli` to version 13.3.0 helped solve problem.
Perhaps this bug has been fixed in the new version of `angular/cli`.

**Comment by tjni** [comment]
The reason for this is that `which` is not on the PATH and `ng` exits prematurely. I filed https://github.com/angular/angular-cli/issues/23997 about this. This can be worked around in nixpkgs by adding `which` for the time being.

**Comment by Chocobozzz** [comment]
Thanks, then I'm closing this issue as it's not a PeerTube one!
