### ISSUE TITLE
Admin users list : Some created_at is missing

### ISSUE THREAD

**Issue by Nalem14** [Chocobozzz/PeerTube#5264]
### Describe the current behavior

When listing users in the admin area, some created_at field are simply empty

### Steps to reproduce

1. Go to admin area
2. See the user list (not all results are empty)
3.

### Describe the expected behavior

Can see all created_at fields in admin users list

### Additional information

* PeerTube instance:
  * URL: https://www.orion-hub.fr
  * Version: 4.3.0-rc.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant: 
`ERROR Error: NG02100
    at Ki (common.mjs:4134)
    at K.transform (common.mjs:4568)
    at vm (core.mjs:22510)
    at Object.Mm (core.mjs:22705)
    at Ka (user-list.component.html:154)
    at z_ (core.mjs:12101)
    at vc (core.mjs:11964)
    at r1 (core.mjs:13014)
    at vc (core.mjs:11988)
    at r1 (core.mjs:13014)`
![image](https://user-images.githubusercontent.com/1911357/190206787-8526f022-6787-4fd6-a67f-31b6913d1e89.png)

(user-list.component.html:154)
![image](https://user-images.githubusercontent.com/1911357/190207038-ee890092-0cb0-45dc-8ffd-e93a6f5f5d4e.png)

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Nalem14** [comment]
It is related to https://github.com/Chocobozzz/PeerTube/commit/fc3784583ce383cec8619be5b1d311b340b645f9 ?

**Comment by Chocobozzz** [comment]
Yes it is! So should be already fixed
