### ISSUE TITLE
Uninstall plugin/theme improvement suggestion

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5266]
### Describe the current behavior

1st issue: 
When click on UNINSTALL the SETTINGS AND UNINSTALL buttons are still active so clicking several times on them cause chaos on socket requests.

2nd issue:
when click INSTALL plugin/theme and an ERROR is occuring the INSTALL button continues to be disabled with "progress" state.

### Describe the expected behavior

1st issue solution: 
once clicked on UNINSTALL, disable UNINSTALL button with a progress icon and disable SETTINGS button
until the socket request is answered.

2n issue solution:
reinitialize the INSTALL button in ready state.

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/81ed2de85c4d1cedcb5b4d58f3bfa39c3601ed2a  and https://github.com/Chocobozzz/PeerTube/commit/e1eada8bae03d06dcd9549c06c67392a55a0fc96
