### ISSUE TITLE
Synchronized videos are published before transcode finishes

### ISSUE THREAD

**Issue by emansom** [Chocobozzz/PeerTube#5268]
### Describe the current behavior

When new synchronized videos are imported, they are directly published before the transcode finishes, resulting in a broken video on some user agents.

### Steps to reproduce

1. Setup PeerTube using latest develop branch (2022-09-16)
2. Synchronize a YouTube channel
3. Observe new imported videos being published before transcode finishes

### Describe the expected behavior

New synchronized videos that have been imported to only be published **_after_** transcoding finishes.

and/or to have a configurable setting similar to what's requested in #5265.

### Additional information

* PeerTube instance:
  * URL: https://pcbu.nl
  * Version: latest code in develop branch (2022-09-16)
  * NodeJS version: v16.17.0
  * Ffmpeg version: 4.3.4-0+deb11u1

**Comment by Chocobozzz** [comment]
Thanks for your tests on the auto sync feature :) Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/3c4754a3a16939337bfeb90c375fbb9e0f7d91fb
