### ISSUE TITLE
Live streams cut off halfway through

### ISSUE THREAD

**Issue by SimplyCorbett** [Chocobozzz/PeerTube#5269]
### Describe the current behavior

Hi there.

I've been watching some livestreams on diode.zone which runs 4.2.2. In most of these live streams it stops loading halfway through with 0MB from server. Refreshing the page doesn't fix it.

As an example here is one that doesn't load at all really (fast forward 5-10 minutes).

https://diode.zone/w/iWyzBDURetnM5is6DcV8vG

hls.js will error out:

![lol5](https://user-images.githubusercontent.com/7935624/190648791-fd014d69-d80d-48f0-84a9-6a49b31114a2.png)

Is this fixed in v4.3.0-rc.1?

**Comment by Chocobozzz** [comment]
May be fixed by https://github.com/Chocobozzz/PeerTube/issues/5207
Let's see with 4.3

**Comment by TaylorJadin** [comment]
I had a similar error message on the last two live streams I did. I'm running 5.0 in Docker. Things were working great for me, but then I set up Backblaze B2 as external storage, and then had the issues with my next two streams, so I think that might be related. Going to try and reproduce and find something in the logs to post here.

**Comment by TaylorJadin** [comment]
Did some more testing and had a livestream cut off after about 20 minutes. I disabled object storage (I'm using Backblaze B2) and haven't had any issues so far. Is it possible to disable object storage for just live streams?

**Comment by Chocobozzz** [comment]
@TaylorJadin Please create a dedicated issue and provider server logs (you may have an error). It's not possible to disable object storage for lives
