### ISSUE TITLE
Improve display of comments

### ISSUE THREAD

**Issue by roukydesbois** [Chocobozzz/PeerTube#527]
* **PeerTube version or URL:** 
https://video.passageenseine.fr/videos/watch/2a4f2626-0651-4e51-bee9-500e6ab3ea63
* **Browser name/version:** 
Firefox 59

* **What is the expected behaviour?**
I'm not sure about that: at least, the "stairs-like" display of replies of replies should be capped at some point to avoid having very narrow comments.
* **What do you see instead?**
A "stairs-like" display of comments that are replies to each other. At the end it becomes narrow, and the word are not properly chunked between two lines.

**Comment by buoyantair** [comment]
@roukydesbois Can you give an example of the end result? Do you mean the behavior that reddit does for example when there is an overflow of replies? aka making it possible to _fold_ the replies?

**Comment by roukydesbois** [comment]
@buoyantair this is a start, but you'll still have the issue of narrowing the width of the comment as long as you go through the conversation. I was more thinking of grouping conversations:
Initial toot/peertube video
--First answer to initial toot (#1)
--Answer to #1 (#2)
--Answer to #2 (#3)
----------(some kind of separator)
--Second answer to initial toot (#4)
----Answer to #4 (#5)
----Answer to #5 (#6)
  ---------- (other separator, but between answers to #4)
----Answer to #4 (#7)
----Answer to #7 (#8)

The logic would be:
I have the toot I want to display. Is it an answer to a previous toot?
. No -> Initial toot, no indentation
. Yes. Are there more direct answers to the previous toot?
  . No -> Keep indentation of previous toot
  . Yes -> Take indentation of previous toot and add one indentation

Does it make sense?

**Comment by Chocobozzz** [comment]
I tried to improve it in https://github.com/Chocobozzz/PeerTube/commit/fc641dedd6d984bf49d6b2c20ace4d5ecf25e06f

![screen_2019-12-10-11:04:15](https://user-images.githubusercontent.com/5180488/70519804-d6907300-1b3c-11ea-8f45-13e7893dafd5.png)
