### ISSUE TITLE
Add ability to import all playlists of a remote channel

### ISSUE THREAD

**Issue by emansom** [Chocobozzz/PeerTube#5272]
### Describe the problem to be solved

PeerTube currently does not synchronize playlists from YouTube. This data is exposed via `yt-dlp` and could be utilized to synchronize to local PeerTube channel playlists.

### Describe the solution you would like

Support synchronizing playlists from YouTube.

Maybe behind a setting in a options page, similar to described in #5265

**Comment by Chocobozzz** [comment]
Hi,

> PeerTube currently does not synchronize playlists from YouTube

It should work :thinking: Do you have an error?

**Comment by emansom** [comment]
> It should work thinking Do you have an error?

The actual playlists itself, not the contents of them.

**Comment by Chocobozzz** [comment]
So just the title and the description of the playlist?

**Comment by emansom** [comment]
> So just the title and the description of the playlist?

For the YouTube playlists of a channel

![Schermafdruk van 2022-09-20 11-10-52](https://user-images.githubusercontent.com/981494/191218189-1aa409c1-379d-4ba8-b8ff-99e49df85b20.png)

to be synchronized to PeerTube here

![Schermafdruk van 2022-09-20 11-11-41](https://user-images.githubusercontent.com/981494/191218266-e7d2ce53-8033-46c3-b55a-bf9f7d1dbdf8.png)

**Comment by emansom** [comment]
Closing as duplicate of #5186
