### ISSUE TITLE
Periodically check if thumbnail on YouTube changed

### ISSUE THREAD

**Issue by emansom** [Chocobozzz/PeerTube#5273]
### Describe the problem to be solved

When video thumbnails on YouTube are changed, those changes are not reflected in PeerTube.

### Describe the solution you would like

Check (e.g. via hash functions) for every video during the synchronization process if the thumbnail returned by `yt-dlp` has changed, and reflect that within PeerTube.

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/5186
