### ISSUE TITLE
Live streaming real IP?

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#5276]
### Describe the current behavior

I have my peertube in front of wireguard with a nginx reverse proxy which has the real ip working. In order to get live stream working I have to forward the internal IP over iptables/nat. This means anyone using livestream is going to show up as 10.0.0.1.

Will this cause any problems?

If it does cause problems, would using something like haproxy with flags to forward the real IP work or does peertube not respect that for streaming?

### Steps to reproduce

```
iptables -A FORWARD -i eth0:1 -o wg0 -p tcp --syn --dport 1935 -m conntrack --ctstate NEW -j ACCEPT
iptables -t nat -A PREROUTING -i eth0:1 -p tcp --dport 1935 -j DNAT --to-destination 10.0.0.2
iptables -t nat -A POSTROUTING -o wg0 -p tcp --dport 1935 -d 10.0.0.2 -j SNAT --to-source 10.0.0.1
```

**Comment by Chocobozzz** [comment]
If nginx has the real ip working, PeerTube should get it if you correctly set the `trust_proxy` configuration: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L37

PeerTube needs to know real user IPs for different purposes (cache system, view counters etc)

**Comment by vid-bin** [comment]
So nginx does have the real ip which works, but any traffic coming over the 1935 port is not on a real ip. That shouldn't cause issues, correct?

**Comment by Chocobozzz** [comment]
> That shouldn't cause issues, correct?

I don't think it will but since we use a library to handle RTMP session I cannot guarantee it.
