### ISSUE TITLE
Wrong langage for a modal title

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5278]
### Describe the current behavior

I updated my instance to v4.3.0-RC1.
The Peertube interface is in french.
I clicked on «delete and rewrite» under a comment. The modal title is in arabic:

![image](https://user-images.githubusercontent.com/38844060/190981816-8034aba8-e656-4ea1-bd73-7bdd7495bd13.png)

### Steps to reproduce

1. set interface in french
2. write a comment
3. click on «supprimer et réécrire»

### Describe the expected behavior

title should be in french

### Additional information

* PeerTube instance:
  * URL: https://videos.john-livingston.fr/w/qqNQwFDerUB1KnFA6N6Jbi
  * Version: 4.3.0-RC1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
This was a mistake on weblate. I fixed the string and we'll update the translations later
