### ISSUE TITLE
Expose node information following the nodeinfo convention

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#528]
Following some discussion in Pleroma about reporting basic info about a server, there has been some interest for the [nodeinfo](https://github.com/jhass/nodeinfo/blob/master/schemas/2.0/example.json) standard. They seem to be already used by diaspora*, Friendica and Hubzilla, to name a few. 

While I know we already have reporting of such info, maybe it could help play nice with other server implementations at some point?

**Comment by Chocobozzz** [comment]
NodeInfo is a nice thing, but IMHO it's too restricted to social software. Yes we could use `localPosts` as *totalVideos*, but it's confusing.

**Comment by hrefhref** [comment]
I don't really see how it's confusing-- for the wider fediverse, videos are _mostly_ like any kinds of posts.

NodeInfo is generalistic but I think it's a good thing overall; if someone wants to do something _specific_ to PeerTube, he can use the server stats endpoint and it's called videos there. If someone wants to do something _common_ to the fediverse, he can use the nodeinfo endpoint and it will (mostly) work on all servers (Pleroma, Friendica and Hubzilla integrates it) out of the box, including PeerTube.

You could also put in the free-form "metadatas" object something like "postsName" if you'd like, or even go propose something at NodeInfo repository to allow adding a specialized name to "posts" ?
