### ISSUE TITLE
Performance bottlenecks during many concurrent viewers

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5280]
### Describe the desired information/correction

During a live session PeerTube crashed. We used a third part service to stream our live, so that part shouldn't affected our servers at all. I guess it was the traffic to the view endpoint that made PeerTube to crash, it wasn't more than 40 comments so that shouldn't have been an issue. It may of course be other endpoints that affected the issues, since there was a lot of users visiting the site at the same time.

I saw that in the next version there's a commit that will optimize the performance for that https://github.com/Chocobozzz/PeerTube/commit/aa2ce188d102ab38452df316d06286040b5d9075 But it looks like this will fix performance for non-lives, right?
Have you seen any other obvious bottlenecks that can bring PeerTube down during high traffic? When looking into our performance logs I can't see any obvious issues; CPU and memory usage looks okay. May it be the websocket connections that hit some kind of roof in the OS config? As I understand each websocket connection required one Linux file handle, and the default limit is 1024. On top we saw around ~700-800 concurrent viewers, so it may be that each time it reached ~1 000 PeerTube crashed. It would be good to add some notes about this in the documentation.

**Comment by Chocobozzz** [comment]
How PeerTube crashed? What was the error (502 I guess?)?
We've made some optimizations in 4.3 that can resolve this issue. But I can't guarantee it will. We also added some Opentelemetry metrics that should help to understand what happened on your peertube instance.

**Comment by Chocobozzz** [comment]
PeerTube crashed and automatically restarted? Or was it still running when your users had this 502 error?

**Comment by Chocobozzz** [comment]
Did you have errors in nginx logs?

**Comment by vid-bin** [comment]
> As I understand each websocket connection required one Linux file handle, and the default limit is 1024

The default limit on debian 11 with nginx mainline is 1024. Otherwise the default on nginx stable is iirc 512.

Check your nginx logs and see what they say.

Did you have to restart peertube or nginx to fix the problem?

**Comment by Chocobozzz** [comment]
> Btw the peertube.log in storage/logs is empty, even though journalctl -feu peertube gives a lot of log messages, where are those log files placed?

Where you decided: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L116

**Comment by Chocobozzz** [comment]
Closing as it seems to be a nginx issue. I added a note in the documentation about the `worker_connections` directive: https://github.com/Chocobozzz/PeerTube/commit/6689214920897e9b555a5acaf4a3c2db527be32e

**Comment by emansom** [comment]
`worker_connections` above the CPU thread count doesn't make sense. 10K is ridiculous and will only introduce further latency.

Utilize NGINX's connection [keepalive](https://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive) functionality to not run out of socket file descriptors.

Requires the following headers to be proxied as well:

```
proxy_http_version 1.1;
proxy_set_header Connection "";
```

**Comment by Chocobozzz** [comment]
I don't see how it helps for this particular issue, where we run out of worker connections because of websocket connections from the client.

**Comment by emansom** [comment]
> I don't see how it helps for this particular issue, where we run out of worker connections because of websocket connections from the client.

There'd be view count and API traffic as well, which would allocate a socket file descriptor for each request.

Having NGINX reuse TCP connections towards PeerTube instead, significantly lowers and limits that.

**Comment by Chocobozzz** [comment]
Hello,

Can you share your OpenTelemetry Grafana dashboard? If not, can you share screens of *Active handles*, *Libuv active requests* and *Waiting Job Queue*? (starting just before the stream starts)

**Comment by Chocobozzz** [comment]
> Since no users are downloading videos directly from our servers I assume this graph shows all network traffic from the server?

This graph is built from metrics sent by the player. So how much the player downloaded segments from HTTP/P2P. HTTP segments can come from another server than peertube

Can you paste a screen of the entire grafana page so I can see all graphs (please open all panels)
