### ISSUE TITLE
Imports not working with YT-DLP in 4.3 release candidate

### ISSUE THREAD

**Issue by dhk2** [Chocobozzz/PeerTube#5281]
### Describe the current behavior

Importing from URL fails when yt-dlp is enabled or youtube_dl_release: is missing from production.yaml

Affecting multiple instances after upgrading to release candidate. Noticed one instance was still working. Determined that one was explicitly configured for youtube-dl. Changed one failing instance to youtube-dl and it started successfully importing after restarting peertube. Added the youtube_dl_release: section to an older instance that did not have that in production.yaml and it started working again as well. 

Happening on imports started through the GUI or through the API

**working config**:
      youtube_dl_release:
        url: 'https://yt-dl.org/downloads/latest/youtube-dl'
        name: 'youtube-dl'

**failing config**
      youtube_dl_release:
        url: 'https://api.github.com/repos/yt-dlp/yt-dlp/releases'
        name: 'yt-dlp'

**example error:**

error[9/20/2022, 12:59:47 PM] Cannot execute job 1872 in queue video-import.

{
  "payload": {
    "type": "youtube-dl",
    "videoImportId": 2260,
    "fileExt": ".webm",
    "preventException": false
  },
  "err": {
    "stack": "Error: Command failed with exit code 1: /usr/bin/python3.8 /var/www/peertube/storage/bin/yt-dlp --merge-output-format mp4 -f bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best -o /var/www/peertube/storage/tmp/1a51a9d637b2e115098de432c9aa0b5c9b1a541ce0495d6bccad8c4c12002fc8-import https://www.youtube.com/watch?v=v4yLeNt-kCU\nERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)\n[youtube] v4yLeNt-kCU: Downloading webpage\n[youtube] v4yLeNt-kCU: Downloading android player API JSON\n[info] v4yLeNt-kCU: Downloading 1 format(s): 248+251\n[download] Destination: /var/www/peertube/storage/tmp/1a51a9d637b2e115098de432c9aa0b5c9b1a541ce0495d6bccad8c4c12002fc8-import.f248.webm\n\r[download]   0.0% of 15.93MiB at  990.62KiB/s ETA 00:16\r[download]   0.0% of 15.93MiB at    1.55MiB/s ETA 00:10\r[download]   0.0% of 15.93MiB at    2.68MiB/s ETA 00:05\r[download]   0.1% of 15.93MiB at    4.63MiB/s ETA 00:03\r[download]   0.2% of 15.93MiB at    7.79MiB/s ETA 00:02\r[download]   0.4% of 15.93MiB at   13.19MiB/s ETA 00:01\r[download]   0.8% of 15.93MiB at   11.78MiB/s ETA 00:01\r[download]   1.6% of 15.93MiB at   11.42MiB/s ETA 00:01\r[download]   3.1% of 15.93MiB at   11.17MiB/s ETA 00:01\r[download]   6.3% of 15.93MiB at   10.30MiB/s ETA 00:01\r[download]  12.5% of 15.93MiB at   11.00MiB/s ETA 00:01\r[download]  25.1% of 15.93MiB at   10.98MiB/s ETA 00:01\r[download]  50.2% of 15.93MiB at   10.94MiB/s ETA 00:00\r[download]  60.9% of 15.93MiB at   10.72MiB/s ETA 00:00\r[download]  60.9% of 15.93MiB at  Unknown B/s ETA  Unknown\r[download]  60.9% of 15.93MiB at    2.12MiB/s ETA 00:02   \r[download]  60.9% of 15.93MiB at    3.55MiB/s ETA 00:01\r[download]  61.0% of 15.93MiB at    5.86MiB/s ETA 00:01\r[download]  61.1% of 15.93MiB at    9.67MiB/s ETA 00:00\r[download]  61.3% of 15.93MiB at   11.72MiB/s ETA 00:00\r[download]  61.6% of 15.93MiB at   11.50MiB/s ETA 00:00\r[download]  62.4% of 15.93MiB at   10.97MiB/s ETA 00:00\r[download]  64.0% of 15.93MiB at    8.69MiB/s ETA 00:00\r[download]  67.1% of 15.93MiB at   10.82MiB/s ETA 00:00\r[download]  73.4% of 15.93MiB at   10.90MiB/s ETA 00:00\r[download]  86.0% of 15.93MiB at   10.82MiB/s ETA 00:00\r[download] 100.0% of 15.93MiB at   11.03MiB/s ETA 00:00\r[download] 100% of 15.93MiB in 00:01 at 10.34MiB/s     \n[download] Destination: /var/www/peertube/storage/tmp/1a51a9d637b2e115098de432c9aa0b5c9b1a541ce0495d6bccad8c4c12002fc8-import.f251.webm\n\r[download]   0.1% of 1.38MiB at  717.71KiB/s ETA 00:02\r[download]   0.2% of 1.38MiB at    1.52MiB/s ETA 00:00\r[download]   0.5% of 1.38MiB at    2.55MiB/s ETA 00:00\r[download]   1.1% of 1.38MiB at    4.40MiB/s ETA 00:00\r[download]   2.2% of 1.38MiB at    7.48MiB/s ETA 00:00\r[download]   4.5% of 1.38MiB at   10.27MiB/s ETA 00:00\r[download]   9.0% of 1.38MiB at   10.77MiB/s ETA 00:00\r[download]  18.0% of 1.38MiB at   10.63MiB/s ETA 00:00\r[download]  36.1% of 1.38MiB at   10.92MiB/s ETA 00:00\r[download]  72.3% of 1.38MiB at    9.99MiB/s ETA 00:00\r[download] 100.0% of 1.38MiB at   11.05MiB/s ETA 00:00\r[download] 100% of 1.38MiB in 00:00 at 10.09MiB/s     \n[Merger] Merging formats into \"/var/www/peertube/storage/tmp/1a51a9d637b2e115098de432c9aa0b5c9b1a541ce0495d6bccad8c4c12002fc8-import.mp4\"\n    at makeError (/var/www/peertube/versions/peertube-v4.3.0-rc.1/node_modules/execa/lib/error.js:60:11)\n    at handlePromise (/var/www/peertube/versions/peertube-v4.3.0-rc.1/node_modules/execa/index.js:118:26)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "message": "Command failed with exit code 1: /usr/bin/python3.8 /var/www/peertube/storage/bin/yt-dlp --merge-output-format mp4 -f bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best -o /var/www/peertube/storage/tmp/1a51a9d637b2e115098de432c9aa0b5c9b1a541ce0495d6bccad8c4c12002fc8-import https://www.youtube.com/watch?v=v4yLeNt-kCU\nERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)\n[youtube] v4yLeNt-kCU: Downloading webpage\n[youtube] v4yLeNt-kCU: Downloading android player API JSON\n[info] v4yLeNt-kCU: Downloading 1 format(s): 248+251\n[download] Destination: /var/www/peertube/storage/tmp/1a51a9d637b2e115098de432c9aa0b5c9b1a541ce0495d6bccad8c4c12002fc8-import.f248.webm\n\r[download]   0.0% of 15.93MiB at  990.62KiB/s ETA 00:16\r[download]   0.0% of 15.93MiB at    1.55MiB/s ETA 00:10\r[download]   0.0% of 15.93MiB at    2.68MiB/s ETA 00:05\r[download]   0.1% of 15.93MiB at    4.63MiB/s ETA 00:03\r[download]   0.2% of 15.93MiB at    7.79MiB/s ETA 00:02\r[download]   0.4% of 15.93MiB at   13.19MiB/s ETA 00:01\r[download]   0.8% of 15.93MiB at   11.78MiB/s ETA 00:01\r[download]   1.6% of 15.93MiB at   11.42MiB/s ETA 00:01\r[download]   3.1% of 15.93MiB at   11.17MiB/s ETA 00:01\r[download]   6.3% of 15.93MiB at   10.30MiB/s ETA 00:01\r[download]  12.5% of 15.93MiB at   11.00MiB/s ETA 00:01\r[download]  25.1% of 15.93MiB at   10.98MiB/s ETA 00:01\r[download]  50.2% of 15.93MiB at   10.94MiB/s ETA 00:00\r[download]  60.9% of 15.93MiB at   10.72MiB/s ETA 00:00\r[download]  60.9% of 15.93MiB at  Unknown B/s ETA  Unknown\r[download]  60.9% of 15.93MiB at    2.12MiB/s ETA 00:02   \r[download]  60.9% of 15.93MiB at    3.55MiB/s ETA 00:01\r[download]  61.0% of 15.93MiB at    5.86MiB/s ETA 00:01\r[download]  61.1% of 15.93MiB at    9.67MiB/s ETA 00:00\r[download]  61.3% of 15.93MiB at   11.72MiB/s ETA 00:00\r[download]  61.6% of 15.93MiB at   11.50MiB/s ETA 00:00\r[download]  62.4% of 15.93MiB at   10.97MiB/s ETA 00:00\r[download]  64.0% of 15.93MiB at    8.69MiB/s ETA 00:00\r[download]  67.1% of 15.93MiB at   10.82MiB/s ETA 00:00\r[download]  73.4% of 15.93MiB at   10.90MiB/s ETA 00:00\r[download]  86.0% of 15.93MiB at   10.82MiB/s ETA 00:00\r[download] 100.0% of 15.93MiB at   11.03MiB/s ETA 00:00\r[download] 100% of 15.93MiB in 00:01 at 10.34MiB/s     \n[download] Destination: /var/www/peertube/storage/tmp/1a51a9d637b2e115098de432c9aa0b5c9b1a541ce0495d6bccad8c4c12002fc8-import.f251.webm\n\r[download]   0.1% of 1.38MiB at  717.71KiB/s ETA 00:02\r[download]   0.2% of 1.38MiB at    1.52MiB/s ETA 00:00\r[download]   0.5% of 1.38MiB at    2.55MiB/s ETA 00:00\r[download]   1.1% of 1.38MiB at    4.40MiB/s ETA 00:00\r[download]   2.2% of 1.38MiB at    7.48MiB/s ETA 00:00\r[download]   4.5% of 1.38MiB at   10.27MiB/s ETA 00:00\r[download]   9.0% of 1.38MiB at   10.77MiB/s ETA 00:00\r[download]  18.0% of 1.38MiB at   10.63MiB/s ETA 00:00\r[download]  36.1% of 1.38MiB at   10.92MiB/s ETA 00:00\r[download]  72.3% of 1.38MiB at    9.99MiB/s ETA 00:00\r[download] 100.0% of 1.38MiB at   11.05MiB/s ETA 00:00\r[download] 100% of 1.38MiB in 00:00 at 10.09MiB/s     \n[Merger] Merging formats into \"/var/www/peertube/storage/tmp/1a51a9d637b2e115098de432c9aa0b5c9b1a541ce0495d6bccad8c4c12002fc8-import.mp4\"",
    "shortMessage": "Command failed with exit code 1: /usr/bin/python3.8 /var/www/peertube/storage/bin/yt-dlp --merge-output-format mp4 -f bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best -o /var/www/peertube/storage/tmp/1a51a9d637b2e115098de432c9aa0b5c9b1a541ce0495d6bccad8c4c12002fc8-import https://www.youtube.com/watch?v=v4yLeNt-kCU",
    "command": "/usr/bin/python3.8 /var/www/peertube/storage/bin/yt-dlp --merge-output-format mp4 -f bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best -o /var/www/peertube/storage/tmp/1a51a9d637b2e115098de432c9aa0b5c9b1a541ce0495d6bccad8c4c12002fc8-import https://www.youtube.com/watch?v=v4yLeNt-kCU",
    "escapedCommand": "\"/usr/bin/python3.8\" \"/var/www/peertube/storage/bin/yt-dlp\" --merge-output-format mp4 -f \"bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best\" -o \"/var/www/peertube/storage/tmp/1a51a9d637b2e115098de432c9aa0b5c9b1a541ce0495d6bccad8c4c12002fc8-import\" \"https://www.youtube.com/watch?v=v4yLeNt-kCU\"",
    "exitCode": 1,
    "stdout": "[youtube] v4yLeNt-kCU: Downloading webpage\n[youtube] v4yLeNt-kCU: Downloading android player API JSON\n[info] v4yLeNt-kCU: Downloading 1 format(s): 248+251\n[download] Destination: /var/www/peertube/storage/tmp/1a51a9d637b2e115098de432c9aa0b5c9b1a541ce0495d6bccad8c4c12002fc8-import.f248.webm\n\r[download]   0.0% of 15.93MiB at  990.62KiB/s ETA 00:16\r[download]   0.0% of 15.93MiB at    1.55MiB/s ETA 00:10\r[download]   0.0% of 15.93MiB at    2.68MiB/s ETA 00:05\r[download]   0.1% of 15.93MiB at    4.63MiB/s ETA 00:03\r[download]   0.2% of 15.93MiB at    7.79MiB/s ETA 00:02\r[download]   0.4% of 15.93MiB at   13.19MiB/s ETA 00:01\r[download]   0.8% of 15.93MiB at   11.78MiB/s ETA 00:01\r[download]   1.6% of 15.93MiB at   11.42MiB/s ETA 00:01\r[download]   3.1% of 15.93MiB at   11.17MiB/s ETA 00:01\r[download]   6.3% of 15.93MiB at   10.30MiB/s ETA 00:01\r[download]  12.5% of 15.93MiB at   11.00MiB/s ETA 00:01\r[download]  25.1% of 15.93MiB at   10.98MiB/s ETA 00:01\r[download]  50.2% of 15.93MiB at   10.94MiB/s ETA 00:00\r[download]  60.9% of 15.93MiB at   10.72MiB/s ETA 00:00\r[download]  60.9% of 15.93MiB at  Unknown B/s ETA  Unknown\r[download]  60.9% of 15.93MiB at    2.12MiB/s ETA 00:02   \r[download]  60.9% of 15.93MiB at    3.55MiB/s ETA 00:01\r[download]  61.0% of 15.93MiB at    5.86MiB/s ETA 00:01\r[download]  61.1% of 15.93MiB at    9.67MiB/s ETA 00:00\r[download]  61.3% of 15.93MiB at   11.72MiB/s ETA 00:00\r[download]  61.6% of 15.93MiB at   11.50MiB/s ETA 00:00\r[download]  62.4% of 15.93MiB at   10.97MiB/s ETA 00:00\r[download]  64.0% of 15.93MiB at    8.69MiB/s ETA 00:00\r[download]  67.1% of 15.93MiB at   10.82MiB/s ETA 00:00\r[download]  73.4% of 15.93MiB at   10.90MiB/s ETA 00:00\r[download]  86.0% of 15.93MiB at   10.82MiB/s ETA 00:00\r[download] 100.0% of 15.93MiB at   11.03MiB/s ETA 00:00\r[download] 100% of 15.93MiB in 00:01 at 10.34MiB/s     \n[download] Destination: /var/www/peertube/storage/tmp/1a51a9d637b2e115098de432c9aa0b5c9b1a541ce0495d6bccad8c4c12002fc8-import.f251.webm\n\r[download]   0.1% of 1.38MiB at  717.71KiB/s ETA 00:02\r[download]   0.2% of 1.38MiB at    1.52MiB/s ETA 00:00\r[download]   0.5% of 1.38MiB at    2.55MiB/s ETA 00:00\r[download]   1.1% of 1.38MiB at    4.40MiB/s ETA 00:00\r[download]   2.2% of 1.38MiB at    7.48MiB/s ETA 00:00\r[download]   4.5% of 1.38MiB at   10.27MiB/s ETA 00:00\r[download]   9.0% of 1.38MiB at   10.77MiB/s ETA 00:00\r[download]  18.0% of 1.38MiB at   10.63MiB/s ETA 00:00\r[download]  36.1% of 1.38MiB at   10.92MiB/s ETA 00:00\r[download]  72.3% of 1.38MiB at    9.99MiB/s ETA 00:00\r[download] 100.0% of 1.38MiB at   11.05MiB/s ETA 00:00\r[download] 100% of 1.38MiB in 00:00 at 10.09MiB/s     \n[Merger] Merging formats into \"/var/www/peertube/storage/tmp/1a51a9d637b2e115098de432c9aa0b5c9b1a541ce0495d6bccad8c4c12002fc8-import.mp4\"",
    "stderr": "ERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)",
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "killed": false
  }
}

### Steps to reproduce

1. Publish->import from url
2. import youtube video

### Describe the expected behavior

Videos to import successfully.

### Additional information

* PeerTube instance:
  * URL:multiple
  * Version:4.3 rc1
  * NodeJS version:v16.17.0 and v14.20.0
  * Ffmpeg version:4.2.7 and 4.3.2
  * yt-dlp version: 2022.04.08 and 2022.06.29

**Comment by Nalem14** [comment]
I have solved that issue on my side by downloading an updated version of FFpmeg here : https://github.com/yt-dlp/FFmpeg-Builds

Simply download the binary in the Release page and replace your binary.

**Comment by Chocobozzz** [comment]
Thanks for the issue but it seems to be a yt-dlp bug/incompatibility with your ffmpeg version.

**Comment by lutangar** [comment]
We had the same issue on several 4.3 instances with either `ffmpeg` version 4.1.9 and 4.2.7.

The issue happens when using `yt-dlp` `--merge-output-format mp4` option. 

A minimum reproductible test case was :
```
./yt-dlp --merge-output-format mp4 https://www.youtube.com/watch\?v\=HC-mdMWpjc4

[youtube] HC-mdMWpjc4: Downloading webpage
[youtube] HC-mdMWpjc4: Downloading android player API JSON
[info] HC-mdMWpjc4: Downloading 1 format(s): 247+251
[download] Destination: Le remerciement de François Sureau lors de sa réception à l'Académie française [HC-mdMWpjc4].f247.webm
[download] 100% of  284.54MiB in 00:00:17 at 16.12MiB/s
[download] Destination: Le remerciement de François Sureau lors de sa réception à l'Académie française [HC-mdMWpjc4].f251.webm
[download] 100% of   60.22MiB in 00:00:03 at 15.38MiB/s
[Merger] Merging formats into "Le remerciement de François Sureau lors de sa réception à l'Académie française [HC-mdMWpjc4].mp4"
ERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)
```

Using one of `yt-dlp` custom `ffmpeg` build solved the issue, see the following note for reference :
https://github.com/yt-dlp/yt-dlp#strongly-recommended

To use a custom `ffmpeg` build with __PeerTube__ you mays use the `FFMPEG_PATH` env variable :
```
FFMPEG_PATH=/path/to/custom/build/ffmpeg npm start
```

**Comment by Chocobozzz** [comment]
@mjohanning99 You need to keep the same environment variables that your systemdl service (`NODE_CONFIG_DIR` and `NODE_ENV`)
