### ISSUE TITLE
Allow customizing security.txt

### ISSUE THREAD

**Issue by JacksonChen666** [Chocobozzz/PeerTube#5282]
### Describe the problem to be solved

I want to change the contents in the security.txt file. However, configuration of the contents does not appear to possible with the yaml or local json file, or in the peertube interface.

### Describe the solution you would like

Add a way to customize the contents of `security.txt` in the peertube instance configuration interface (or document it (or make it obvious) if it already exists).

**Comment by JacksonChen666** [comment]
@kontrollanten changing the option in `local-production.json` seems to work (doing it in `production.yaml` results in `\n` literally, somehow), only after changing that option and waiting more than a day for the change to actually apply (i restarted peertube. a lot).

so maybe the problem i'm facing is that the file does not update immediately after a restart of peertube (which also takes too long which makes systemd kill the process forcefully).

**Comment by Chocobozzz** [comment]
Hi,

There is a cache behind well known endpoints, so you just have to wait a little bit to view your changes. I'll add a message in the configuration file.
