### ISSUE TITLE
Rendering in settings on 4.3.0 in smartphone-browser

### ISSUE THREAD

**Issue by xundeenergie** [Chocobozzz/PeerTube#5284]
### Describe the current behavior

I did the upgrade to 4.3.0 this morning and found a rendering problem in settings -> extended -> cache on my smartphone android firefox

![Screenshot_20220922_094711](https://user-images.githubusercontent.com/5894829/191688724-e9c8b15d-8872-4352-ae42-f0a6d682f52e.jpg)

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance: 4.3.0
  * URL: https://kino.schuerz.at
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox Android 104.2.0
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by xundeenergie** [comment]
Another Rendering-Issue also.

This is in comments-section on the smartphone, when i open the moderation dialog.

![Screenshot_20220926_205206_org mozilla fennec_fdroid](https://user-images.githubusercontent.com/5894829/192357420-c42156ed-d1e6-41d0-856f-8bb5ce1b3418.jpg)

**Comment by Chocobozzz** [comment]
Hi,

Thank you! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/85edcb5626d6843fbe4aa6f4d002e7ccbb5e7b58 & https://github.com/Chocobozzz/PeerTube/commit/52444ea13c72ccf6ff09c629710a545b7e8283df
