### ISSUE TITLE
Black screen on live stream (AV1)

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#5285]
### Describe the current behavior

When using live stream the video is black. Audio works. No client side errors shown in the browser. Using AV1 with 10bit (yuv420p10le).

```
{
  "vod": [
    {
      "encoderName": "aac",
      "profileName": "test",
      "outputOptions": ["-b:a 192k", "-ac 2"]
    },
    {
      "encoderName": "libsvtav1",
      "profileName": "test",
      "outputOptions": ["-crf 33", "-preset 8", "-g 300"]
    }
  ],

  "live": [    {
      "encoderName": "aac",
      "profileName": "livetest",
      "outputOptions": ["-b:a 192k", "-ac 2"]
    },
    {
      "encoderName": "libsvtav1",
      "profileName": "livetest",
      "outputOptions": ["-preset 9", "-g 300", "-b:v 4000k", "-svtav1-params lp=8:pin=1"]
    }
]
}
```

```
{
  "vod": [
    {
      "encoderName": "aac",
      "streamType": "audio",
      "priority": 1000
    },
   {
      "encoderName": "libsvtav1",
      "streamType": "video",
      "priority": 1000
    }
  ],

  "live": [    {
      "encoderName": "aac",
      "streamType": "audio",
      "priority": 1001
    },
   {
      "encoderName": "libsvtav1",
      "streamType": "video",
      "priority": 1001
    }
]
}
```

Here are some errors logged in peertube:

```
error[9/22/2022, 5:10:29 AM] Client log: HLS.js error: networkError - fatal: false - fragLoadError

{
  "tags": [
    "client"
  ],
  "username": "the_zombie_hunter",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0",
  "meta": "{\"data\":{\"type\":\"networkError\",\"details\":\"fragLoadError\",\"fatal\":false,\"frag\":{\"_byteRange\":null,\"_url\":\"https://vidbin.org/static/streaming-playlists/hls/6ddc368c-1513-4a51-a4be-8083f875c78d/0-000012.ts\",\"baseurl\":\"https://vidbin.org/static/streaming-playlists/hls/6ddc368c-1513-4a51-a4be-8083f875c78d/0.m3u8\",\"relurl\":\"0-000012.ts\",\"elementaryStreams\":{\"audio\":null,\"video\":null,\"audiovideo\":null},\"_decryptdata\":null,\"rawProgramDateTime\":\"2022-09-22T05:09:49.850-0700\",\"programDateTime\":1663848589850,\"tagList\":[[\"INF\",\"5.000000\"],[\"PROGRAM-DATE-TIME\",\"2022-09-22T05:09:49.850-0700\"]],\"duration\":5,\"sn\":12,\"type\":\"main\",\"loader\":null,\"level\":0,\"cc\":0,\"start\":60.032,\"stats\":{\"loaded\":0,\"total\":1138716,\"aborted\":true,\"retry\":0,\"chunkCount\":0,\"bwEstimate\":0,\"loading\":{\"start\":86117,\"end\":0,\"first\":86117},\"parsing\":{\"start\":0,\"end\":0},\"buffering\":{\"start\":0,\"end\":0,\"first\":0}},\"urlId\":0,\"bitrateTest\":false,\"title\":null,\"initSegment\":null},\"response\":{}}}",
  "url": "https://vidbin.org/w/eyQ3HeoL5X4rD3hh125hgX"
}

error[9/22/2022, 5:10:33 AM] Client log: HLS.js error: mediaError - fatal: false - bufferNudgeOnStall

{
  "tags": [
    "client"
  ],
  "username": "the_zombie_hunter",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0",
  "meta": "{\"data\":{\"type\":\"mediaError\",\"details\":\"bufferNudgeOnStall\",\"fatal\":false}}",
  "url": "https://vidbin.org/w/eyQ3HeoL5X4rD3hh125hgX"
}

error[9/22/2022, 5:10:39 AM] Client log: Segment https://vidbin.org/static/streaming-playlists/hls/6ddc368c-1513-4a51-a4be-8083f875c78d/master.m3u8+V0+14 error.

{
  "tags": [
    "client"
  ],
  "username": "the_zombie_hunter",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0",
  "meta": "{\"isTrusted\":true}",
  "url": "https://vidbin.org/w/eyQ3HeoL5X4rD3hh125hgX"
}
```

### Additional information

* PeerTube instance:
  * URL: vidbin.org
  * Version: 4.3.0...4.3.0^0 
  * NodeJS version: 18
  * Ffmpeg version: git

**Comment by vid-bin** [comment]
I know this is outside the norm. I’ll have to give it a shot with regular yuv420p. My end goal is to use a hardware av1 encoder on my Peertube instance for live streams.

**Comment by vid-bin** [comment]
yuv420p does not change this bug.

**Comment by vid-bin** [comment]
Also live streaming works with the default profile, so not a problem with my setup.

**Comment by vid-bin** [comment]
So both the master.m3u8 and 0.m3u8 have no codec information.. probably the issue.

**Comment by ROBERT-MCDOWELL** [comment]
have the same problem from remote video of following instance. quality selection disappeared

**Comment by Chocobozzz** [comment]
Hi,

For live stream we rely exclusively on ffmpeg to generate the appropriate HLS playlists (master included). From what I see, it doesn't seem to be a hls.js or peertube bug. Please try to run the ffmpeg command created by peertube (displayed in debug mode) manually first to ensure the bug is not on their side

**Comment by vid-bin** [comment]
@Chocobozzz I'm looking at the cmdline and see the following: -c:v:0 libsvtav1

I believe 0 means it cant transcode video correct? Not an expert at ffmpeg though.

**Comment by vid-bin** [comment]
`-map a:0 -c:a:0 aac ` is also a thing.

**Comment by vid-bin** [comment]
[output.txt](https://github.com/Chocobozzz/PeerTube/files/9654831/output.txt)

**Comment by vid-bin** [comment]
Alright, I have two different outputs here.

This is the command from peertube debug with quotes added around filter_complex to avoid bash errors (same error either way, though):

https://pastebin.com/raw/pbDjjATu

Here is the command from ps args with ffmpeg debug enabled:

https://pastebin.com/raw/Zk6FGFt1

The last one runs, but still gives me a black screen.

**Comment by vid-bin** [comment]
I also wanted to say that there does appear to be video in the .ts files based on the file sizes. But the web player and vlc can't see the video streams.

On https://www.reddit.com/r/AV1/comments/stbk3r/av1_in_hls_manifests_works_for_browsers_that/ the m3u8's have the proper CODECS="av01.0.31M.08" and stuff listed.

In the master.m3u8 and 0.m3u8 that CODECS= part is missing.
