### ISSUE TITLE
Importing playlist URLs should work in sync.

### ISSUE THREAD

**Issue by anilgulecha** [Chocobozzz/PeerTube#5286]
### Describe the problem to be solved

Thank you for the recent 4.3 release which supports syncing channels. I immediately tried it out, and naively assumed playlists would work - turns out they don't.

I think this ability would be more fine-grained, and allow specific content to be synced to the peertube instance.

### Describe the solution you would like

Importing playlist URLs should work in sync.

**Comment by Chocobozzz** [comment]
It should import playlists too. What was the playlist URL?

**Comment by anilgulecha** [comment]
It actually worked now. I think something to do with a fresh playlist? I'd created a fresh playlist yesterday, and that did not take. The same did take just now.

Will close the issue - I'm set!
