### ISSUE TITLE
Version 4.3.0 depends on redis server >= 5.0 (any OS)

### ISSUE THREAD

**Issue by M-Stenzel** [Chocobozzz/PeerTube#5287]
### Describe the problem

Version 4.3.0 of peertube depends on redis version not less than 5.0.
Older versions are not supported any longer.
It would be nice to have this information in the CHANGELOG.md file.

Martin.

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by decentral1se** [comment]
Was bitten by this and had to run a Redis upgrade. Unfortunately, I ran into https://github.com/Chocobozzz/PeerTube/issues/5303 and https://github.com/Chocobozzz/PeerTube/issues/5302 so then had to run a downgrade but my Redis then complained about invalid version so I had to partially downgrade. Was a bit of a suprise given the minor version marker.

**Comment by Chocobozzz** [comment]
Hello,

Minor PeerTube versions can break dependencies and/or require manual sysadmin intervention. They are specified in the **Important Notes** in the changelog. However I completely missed the new Redis support version, sorry about that. I added a note in the release: https://github.com/Chocobozzz/PeerTube/releases/tag/v4.3.0

**Comment by decentral1se** [comment]
No worries and thank you @Chocobozzz!

I feel like other admins who see a "semver" like format might make the same assumption I made. "Important notes" is not always a convention on every project that uses a "semver" like format but using minor -> major to signal breakage typically is.

What I mean to say is, is it written somewhere that "Important notes" is the potential breakage signal?

I feel like a quoted warning on the top of https://github.com/Chocobozzz/PeerTube/blob/develop/CHANGELOG.md might be useful here to help admins not make the same mistake. I could submit a PR if you liike. Or link to already existing documentation about this versioning scheme.

**Comment by Chocobozzz** [comment]
> What I mean to say is, is it written somewhere that "Important notes" is the potential breakage signal?

Yes, it's written in the documentation as the first step before upgrading: https://docs.joinpeertube.org/install-any-os?id=upgrade

> I feel like other admins who see a "semver" like format might make the same assumption I made

I understand but we never said we use semver with PeerTube. While I agree it would be better, Framasoft doesn't have enough resource to ensure compatibility between minor versions.
