### ISSUE TITLE
yt-dlp no longer works with ffmpeg 4.1

### ISSUE THREAD

**Issue by pietsch** [Chocobozzz/PeerTube#5288]
### Describe the current behavior

After I upgraded from version 4.2.2 to 4.3.0 (and updating yt-dlp at the same time), importing videos from YouTube no longer worked. Metadata was retrieved, but then the error "video file could not be found" was shown to the user.

Logs show that `ffmpeg` failed with the error message `ERROR: Stream #1:0 -> #0:1 (copy)` when `yt-dlp` tried to merge the two files (audio and video?) it downloaded from YouTube.

### Additional information

This seems to be another dependency that needs updating in the documentation. My analysis so far:

PeerTube instances that still run ffmpeg 4.1 can no longer import videos from YouTube (and perhaps other sites) because the current `yt-dlp` needs a more recent `ffmpeg` than the PeerTube documentation states (it currently states `ffmpeg` >= 4.1).

My workaround was to install the huge, statically linked [ffmpeg binaries](https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz) that were patched and built by the yt-dlp project [especially for this purpose](https://github.com/yt-dlp/FFmpeg-Builds/). I can share a cron job that updates them daily.

* PeerTube instance:
  * Version: 4.3.0
  * ffmpeg version: 4.1.9
  * yt-dlp version: 2022.09.01

**Comment by vid-bin** [comment]
You’re not the first person to use those 80MB ffmpeg binaries.

question: why? The ffmpeg.org site offers pre compiled static binaries with the following link -  https://johnvansickle.com/ffmpeg/ which are half the size and work with yt-dlp.

**Comment by Chocobozzz** [comment]
Hello,

Thank you for the issue. I added a note in the changelog about the new ffmpeg version support: https://github.com/Chocobozzz/PeerTube/releases/tag/v4.3.0
