### ISSUE TITLE
warning Resolution field "jpeg-js@0.4.4" is incompatible with requested version "jpeg-js@0.4.2"

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5289]
### Describe the problem

how to make peertube 4.3.0 upgrade accepting jpeg-js@4.4 ?
thanks

after upgrade I get warning Resolution field "jpeg-js@0.4.4" is incompatible with requested version "jpeg-js@0.4.2"

**Comment by Chocobozzz** [comment]
Hello,

This is just a warning from yarn that is not important. We forced a patch version upgrade of a dependency to fix a CVE.
