### ISSUE TITLE
Ffmpeg uses all threads regardless of how many have been assigned in `/admin/config/edit-custom#transcoding`

### ISSUE THREAD

**Issue by Sakrecoer** [Chocobozzz/PeerTube#5292]
### Describe the current behavior

As the title suggests

### Steps to reproduce

1. Upload a video
2. Start `top` on the host
3. Watch the CPU work like zealot at gunpoint

### Describe the expected behavior

Use the amount of threads allocated

### Additional information

* PeerTube instance:
  * URL:
  * Version: 4.3.0
  * NodeJS version: v16.17.0
  * Ffmpeg version: 4.4.2-0ubuntu0.22.04.1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by vid-bin** [comment]
I don't see a problem with the default profile.

Are you using a custom profile?

**Comment by Sakrecoer** [comment]
Thanks for looking into it. No i use the default profile shipped peertube

**Comment by vid-bin** [comment]
And you've restarted peertube since changing the thread count and core count?

I'd chalk this up to a problem with ffmpeg 4.4.2. Try updating to 5.1.1 or git.

**Comment by vid-bin** [comment]
What is the thread count set to anyway?

**Comment by Sakrecoer** [comment]
it set to 2. i haven't changed it since first install. i'll try see what happens if i upgrade ffmpeg and report back. Thank you!

**Comment by Sakrecoer** [comment]
wait... thread count ANd core count? where can i set the core count?

**Comment by Chocobozzz** [comment]
Hello,

> looking at the configuration, it seems like they are reversed: VOD settings contains live transcoding thread count, and Live settings contain VOD transcoding thread count.

Can you explain how you arrived to this conclusion?

**Comment by Sakrecoer** [comment]
@Chocobozzz I don't know if it is swapped in the backend, but in the frontend it is. See attached screenshots:

![image](https://user-images.githubusercontent.com/3484593/192547466-3c144cad-c47c-460c-8838-06024422a535.png)

![image](https://user-images.githubusercontent.com/3484593/192547653-c53191c3-03fe-4dc0-b9e3-dc7758d75e62.png)

**Comment by Nalem14** [comment]
Its just a Total used threads with the other transcoding method. Used to know your total used threads with all transcoding jobs.

**Comment by Sakrecoer** [comment]
@Nalem14 sure, still the thread-count for live is displayed on VOD-setting page and vice versa. This is also where i used to be able to set how many threads that were to be used during transcoding. Since upgrade from 4.2.2 > 4.3.0  it uses all of them regardless of the values i put i there.

**Comment by Nalem14** [comment]
In frontend its grabbed from config.transcoding.threads for vod and config.live.transcoding.threads for live

And I think the backend take the good option to use
![image](https://user-images.githubusercontent.com/1911357/192566135-d64c8d16-6410-4838-bd0b-1b7562b9634f.png)
![image](https://user-images.githubusercontent.com/1911357/192566210-153ecb96-4ca9-4387-aeb8-4534a5aa2fd3.png)
![image](https://user-images.githubusercontent.com/1911357/192566269-c3744dc8-2919-4a7a-b024-374ecd577285.png)

**Comment by Sakrecoer** [comment]
Thanks for verifying @Chocobozzz ! Would you like me to file a separate issue for the swapped text describing the function (légende) in the front end display? 

I will continue investigating for this one, begining by trying a newer version fo ffmpeg and report any findings back.

Many thanks for taking the time to look into this! :)

**Comment by Sakrecoer** [comment]
> The legend is here to remember the number of threads you set to the other transcoding option.

Oh, but the legend number changes as i change the value in the selector. So it looks like it shows how many threads in the current slector while talking about the other selector...I'm quite confused tbh..

**Comment by Nalem14** [comment]
Yes, the legend show your total used threads with all transcoding jobs.

**Comment by Sakrecoer** [comment]
oh, i see now... i have never enabled live-transcoding before... But now that i did just to see, it makes sense! Thanks for baring with me! :sweat_smile:

**Comment by Sakrecoer** [comment]
I am no longer able to reproduce this issue, mesning everything is working fine now. I have to conclude there was another process spooking around on my machine at the same time during my initial testing. I apologize for the noise and thank you for your kind assistance. Closing this issue.
