### ISSUE TITLE
Enable automatic subtitles using OpenAI's Whisper neurel network

### ISSUE THREAD

**Issue by NIXOYE** [Chocobozzz/PeerTube#5293]
### Describe the problem to be solved

Open AI recently open sourced a neural network that is incredibly good at making transcriptions and translations in english including english spoken in a variety of accents. It would be great for peertube to make it easy for hard of hearing folk and non english speakers to enable subtitles on any video uploaded to peertube.

### Describe the solution you would like

Here is a link to Open AI's blog post on Whisper https://openai.com/blog/whisper/

There is already a script to auto translate YouTube videos and any videos that work with youtube-dl https://github.com/m1guelpf/yt-whisper

**Comment by vid-bin** [comment]
It would be nice to see a plugin for this. The requirements put this project out of reach for the majority of peertube instances though (specifically mentions vram so it requires a gpu. VPS and most dedicated servers at datacenters don't have a gpu).

**Comment by Chocobozzz** [comment]
Hello,

A transcription plugin already exists: https://gitlab.com/apps_education/peertube/plugin-transcription
You may open an issue on their repository to use this specific tool :)

**Comment by NIXOYE** [comment]
@Chocobozzz ah, thanks for the link. I opened an issue there :)
