### ISSUE TITLE
Can´t reach peertube after upgrade to v4.3.0

### ISSUE THREAD

**Issue by Stormkoopa** [Chocobozzz/PeerTube#5297]
### Describe the problem

After upgrading my peertube instance from v4.2.2 to v4.3.0 I get a HTTP 500 Error whenever I try to reach my instance. When I run journalctl -feu peertube I see the following error:
 "err": {
Sep 26 09:50:06 gerlnxptube peertube[990]:     "stack": "Error: ENOENT: no such file or directory, open '/var/www/peertube/storage/tmp/plugins-global.css'",
Sep 26 09:50:06 gerlnxptube peertube[990]:     "message": "ENOENT: no such file or directory, open '/var/www/peertube/storage/tmp/plugins-global.css'",
Sep 26 09:50:06 gerlnxptube peertube[990]:     "errno": -2,
Sep 26 09:50:06 gerlnxptube peertube[990]:     "code": "ENOENT",
Sep 26 09:50:06 gerlnxptube peertube[990]:     "syscall": "open",
Sep 26 09:50:06 gerlnxptube peertube[990]:     "path": "/var/www/peertube/storage/tmp/plugins-global.css"
Sep 26 09:50:06 gerlnxptube peertube[990]:   }

I haven´t found a similar issue so I am opening this one. Please suggest a duplicate if there is one.

### Additional information

* PeerTube instance URL: not public
* PeerTube version: 4.3.0
* NodeJS version: 18.9.1
* Ffmpeg version: 4.2.7
* Redis version: 5.0.7
* PostgreSQL version: 12.12

**Comment by Nalem14** [comment]
I think the problem is your have installed plugin locally, and the local source is not foundable.
Check that the plugin(s) source folder is not in the old /versions/4.x folder

**Comment by Stormkoopa** [comment]
I haven´t installed any plugin locally.

**Comment by Nalem14** [comment]
Can you provide the full start logs ?

**Comment by Stormkoopa** [comment]
[se-motion.se-commerce.com:443] 2022-09-26 14:54:22.870 error: Cannot register plugins and themes. {
Sep 26 14:54:22 gerlnxptube peertube[1030]:   "err": {
Sep 26 14:54:22 gerlnxptube peertube[1030]:     "err": {
Sep 26 14:54:22 gerlnxptube peertube[1030]:       "stack": "Error: Command failed: yarn install --pure-lockfile\nError: EACCES: permission denied, open '/home/peertube/.config/yarn'\n    at Object.openSync (node:fs:599:3)\n    at readFileSync (node:fs:467:35)\n    at /usr/local/lib/node_modules/yarn/lib/cli.js:97395:58\n    at Array.map (<anonymous>)\n    at parseRcPaths (/usr/local/lib/node_modules/yarn/lib/cli.js:97393:78)\n    at Object.findRc (/usr/local/lib/node_modules/yarn/lib/cli.js:97407:10)\n    at getRcConfigForCwd (/usr/local/lib/node_modules/yarn/lib/cli.js:56965:74)\n    at /usr/local/lib/node_modules/yarn/lib/cli.js:88756:56\n    at Generator.next (<anonymous>)\n    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)\n\n    at ChildProcess.exithandler (node:child_process:412:12)\n    at ChildProcess.emit (node:events:513:28)\n    at maybeClose (node:internal/child_process:1091:16)\n    at Socket.<anonymous> (node:internal/child_process:449:11)\n    at Socket.emit (node:events:513:28)\n    at Pipe.<anonymous> (node:net:313:12)",
Sep 26 14:54:22 gerlnxptube peertube[1030]:       "message": "Command failed: yarn install --pure-lockfile\nError: EACCES: permission denied, open '/home/peertube/.config/yarn'\n    at Object.openSync (node:fs:599:3)\n    at readFileSync (node:fs:467:35)\n    at /usr/local/lib/node_modules/yarn/lib/cli.js:97395:58\n    at Array.map (<anonymous>)\n    at parseRcPaths (/usr/local/lib/node_modules/yarn/lib/cli.js:97393:78)\n    at Object.findRc (/usr/local/lib/node_modules/yarn/lib/cli.js:97407:10)\n    at getRcConfigForCwd (/usr/local/lib/node_modules/yarn/lib/cli.js:56965:74)\n    at /usr/local/lib/node_modules/yarn/lib/cli.js:88756:56\n    at Generator.next (<anonymous>)\n    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)\n",
Sep 26 14:54:22 gerlnxptube peertube[1030]:       "code": 1,
Sep 26 14:54:22 gerlnxptube peertube[1030]:       "killed": false,
Sep 26 14:54:22 gerlnxptube peertube[1030]:       "signal": null,
Sep 26 14:54:22 gerlnxptube peertube[1030]:       "cmd": "yarn install --pure-lockfile"
Sep 26 14:54:22 gerlnxptube peertube[1030]:     },
Sep 26 14:54:22 gerlnxptube peertube[1030]:     "stdout": "",
Sep 26 14:54:22 gerlnxptube peertube[1030]:     "stderr": "Error: EACCES: permission denied, open '/home/peertube/.config/yarn'\n    at Object.openSync (node:fs:599:3)\n    at readFileSync (node:fs:467:35)\n    at /usr/local/lib/node_modules/yarn/lib/cli.js:97395:58\n    at Array.map (<anonymous>)\n    at parseRcPaths (/usr/local/lib/node_modules/yarn/lib/cli.js:97393:78)\n    at Object.findRc (/usr/local/lib/node_modules/yarn/lib/cli.js:97407:10)\n    at getRcConfigForCwd (/usr/local/lib/node_modules/yarn/lib/cli.js:56965:74)\n    at /usr/local/lib/node_modules/yarn/lib/cli.js:88756:56\n    at Generator.next (<anonymous>)\n    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)\n"
Sep 26 14:54:22 gerlnxptube peertube[1030]:   }
Sep 26 14:54:22 gerlnxptube peertube[1030]: }


That´s what I´ve found while starting up

**Comment by Chocobozzz** [comment]
Hello,

Like written in the log you have a permission issue on your server.
Ensure `'/home/peertube/.config/yarn` is owned by `peertube`, the user that is running your peertube process

**Comment by Stormkoopa** [comment]
Yea I have tried that but there is no such directory.

**Comment by Chocobozzz** [comment]
What is the output of `ls -l /home/peertube/.config`?

**Comment by Stormkoopa** [comment]
![Peertube](https://user-images.githubusercontent.com/43676722/192706296-ee33004c-0db9-436f-9133-a06be4d03053.png)

**Comment by Chocobozzz** [comment]
Ensure `/home/peertube/.config` is traversable by `peertube` user (`sudo -u peertube mkdir /home/peertube/.config/yarn` for example).

**Comment by Stormkoopa** [comment]
I have created the directory.
Then I changed the permissions to 777 for testing purposes, it´s still throwing the same error.
The peertube user is the owner of the folder.

**Comment by Chocobozzz** [comment]
What is the output of `ls -l / | grep home` ?

**Comment by Stormkoopa** [comment]
![image](https://user-images.githubusercontent.com/43676722/192771477-3df328bd-c679-4f78-bb17-4919c881443b.png)

**Comment by Chocobozzz** [comment]
Let's use the [forum](https://framacolibri.org/c/peertube/38) instead since it appears to be a sysadmin issue

**Comment by Stormkoopa** [comment]
https://framacolibri.org/t/issue-after-upgrading-from-v4-2-2-to-4-3-0/15723/2
