### ISSUE TITLE
New layout issue on most pages

### ISSUE THREAD

**Issue by AresUII** [Chocobozzz/PeerTube#5298]
### Describe the current behavior

Leftmost portion of main content area is cut off by left sidebar and cannot be seen. Proof:
![image](https://user-images.githubusercontent.com/42591316/192305560-796e2471-ca62-43c4-b984-26d947fa936f.png)
Instance about pages are also affected.
Bug does not occur with Chromium.

### Steps to reproduce

1. Visit a video page on the affected PeerTube version with the safe browser.
2. Observe.
3. Zoom out and observe how this does not fix the issue.

### Describe the expected behavior

Content area does not overlap anything. Examples [top: unaffected browser; bottom: unaffected instance on older version]:
![image](https://user-images.githubusercontent.com/42591316/192309448-bc8da5b3-42f6-496a-bff5-dd55e5b8ee6e.png)
![image](https://user-images.githubusercontent.com/42591316/192314567-88b59274-0a64-416d-80e5-502911acf185.png)

### Additional information

* PeerTube instance: Tube.Shanti.Cafe
  * URL: https://tube.shanti.cafe/w/7G3Z6NyMUA34h1zg1Z1kR1
  * Version: 4.3.0

* Browser name, version and platforms on which you could reproduce the bug: FF 102.3esr, Windows 10 64-bit

**Comment by Chocobozzz** [comment]
I'm sorry but I can't reproduce. Can you try to disable all your firefox plugins?

**Comment by emansom** [comment]
Also experiencing this from time to time when docking a tab to one part of the screen and then to full window again (changing the viewport of the document).

Browser being Firefox on a 1440p screen with 1.25x scaling.

**Comment by Chocobozzz** [comment]
@emansom I think it's a different issue. Can you open a dedicated one with the detailed steps to reproduce please?

**Comment by emansom** [comment]
@Chocobozzz Done!

**Comment by Chocobozzz** [comment]
Ping @AresUII

**Comment by AresUII** [comment]
This issue now appears to be fixed on some instances as discussed in #5326.
