### ISSUE TITLE
After installation 4.3.0 the index page is not shown.

### ISSUE THREAD

**Issue by tocan** [Chocobozzz/PeerTube#5299]
### Describe the problem

After new installation 4.30 Debian 11 I have this issue. In the menue left side the section
Miss the options like “recently”, “most viewed”… and in the middle nothing happens.

Someone knows how to fix this? At least there are just for one sound libary I do 1500 videos to upload that demonstrate sounds and combinations with instructions how to produce specific sounds. But this is just one libary.

Screenshot:
URL https://notobono.de

### Additional information

* PeerTube instance URL: https://notobono.de
* PeerTube version: 4.3.0
![FCBA9E26-B12D-4429-A00A-2A6508FB9848](https://user-images.githubusercontent.com/30770487/192335897-2e74c50e-7761-47c4-b0d0-b5c3b55646f3.png)

* NodeJS version: v18.9.0
* Ffmpeg version: 4.3.4-0+deb11u1
* Redis version: 5.2.1
* PostgreSQL version: Debian 13.8-0+deb11u1

**Comment by Chocobozzz** [comment]
Hello,

This is a bug of the social-sharing plugin that wait forever when registering the plugin because of invalid asset. Try to disable `mewe` and/or `gab` sharing to fix this while keeping the plugin installed.
