### ISSUE TITLE
Yunohost

### ISSUE THREAD

**Issue by Thatoo** [Chocobozzz/PeerTube#53]
It would be nice, because easy, to be able to install PeerTube on Yunohost.

**Comment by rigelk** [comment]
Apparently Yunohost is tracking the issue: https://dev.yunohost.org/issues/728

The currently developped package is lacking upgrade, update and backup scripts. It also dates from december and was written to fetch the HEAD from that time and not a release.

**Comment by Chocobozzz** [comment]
If it's tracked on the yunohost bug tracker I think we can close this issue :)
