### ISSUE TITLE
Do you know Ferment project ?

### ISSUE THREAD

**Issue by zicmama** [Chocobozzz/PeerTube#530]
# No issue !

## Ferment 
A peer-to-peer audio publishing and streaming application. Think SoundCloud or Spotify, but entirely decentralized and free. https://lolashare.com

## Code
https://github.com/fermentation/ferment

**Comment by rigelk** [comment]
I've already seen this project. To me the most interesting part is its UI. Apart from that:

- the bummer: unmaintained
- it uses ssb for discovery and webtorrent for up/dl (so nothing new there)
- it cannot guarantee long term seeding
- it very much depends on the client app
- they do not clear up how discovery made accessible to λ users

I fail to see how we could use any the ideas put in their project to improve PT.

**Comment by tcitworld** [comment]
> the bummer: unmaintained

I guess you could say Ferment has ... :smiley: :sunglasses: rotten.
