### ISSUE TITLE
InvalidVideoTitle: video title is too long 110 vs 100 character limit

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5300]
### Describe the current behavior

When having videos with titles with a length greater than 100 PeerTube will log `InvalidVideoTitle [videoURL] video title is too long 110 vs 100 character limit` for each video.

### Steps to reproduce

1. Create a video with a title with 110 characters.
2. Eventually you have to restart PeerTube.
3. Wait for a while (last time it took 6 hours after start)
4. Run `journactl -u peertube`

### Describe the expected behavior

Since the limit seems to be set to 120 character there shouldn't be any logging about this.

### Additional information

* PeerTube instance:
  * Version: 4.3.0

**Comment by Chocobozzz** [comment]
Hello,

I don't know where comes from this message. Moreover we have a limit of 120 characters for video names. Filling

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/2b32c5b37e0b10261a108cc7c23b72d64f806576
