### ISSUE TITLE
v4.3.0: Cannot generate HTML page

### ISSUE THREAD

**Issue by decentral1se** [Chocobozzz/PeerTube#5303]
### Describe the current behavior

On a `chocobozzz/peertube:v4.3.0-bullseye` docker deployment, the `/data/tmp/...` folder suddenly isn't a place that can be written to apparently but `peertube` does have permissions on those folders... before `v4.3.0` things could be written to that directory because there are files ther already with the correct permissions...

Config is here: https://git.coopcloud.tech/coop-cloud/peertube/src/branch/main/compose.yml

Is this related to changes around having a readonly `/tmp` folder in the docker deploy? I don't mount `/tmp` as a volume, but do mount `/data`... if I `touch plugins-global.css; chown peertube plugins-global.css` then I can start the app but then on restart, it is again coming with this error:

```
error[27/09/2022, 11:15:41] Cannot generate HTML page.

{
  "err": {
    "stack": "Error: ENOENT: no such file or directory, open '/data/tmp/plugins-global.css'",
    "message": "ENOENT: no such file or directory, open '/data/tmp/plugins-global.css'",
    "errno": -2,
    "code": "ENOENT",
    "syscall": "open",
    "path": "/data/tmp/plugins-global.css"
  }
}
```

### Steps to reproduce

1. Upgrade to chocobozzz/peertube:v4.3.0-bullseye

### Describe the expected behavior

Peertube can start up.

### Additional information

* PeerTube instance:
  * URL: https://tv.lumbung.space
  * Version: `chocobozzz/peertube:v4.3.0-bullseye` 
  * NodeJS version: `v16.17.1`
  * Ffmpeg version: `4.3.4-0+deb11u1`

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/5302
