### ISSUE TITLE
Livestream not playing if no audio channel exists

### ISSUE THREAD

**Issue by thomasgraf** [Chocobozzz/PeerTube#5306]
### Describe the current behavior

Sending streams via rtmp without sound channel cannot be watched as livestream. Sending an stream via obs e.g. which has a soundchannel works flawlessly. 

These videos where correctly transcoded to an mp4 which then can be watched in the peertube instance. Setting up transcoding for these livestreams ends up that no hls files are written. 
Without transcoding activated hls files are written. They have been copied for further analysis. (vlc screenshot attached)

 

### Steps to reproduce

1. setup peertube with a permanent livestream (no transcoding)
2. setup streamingurl and streaming key in sender
3. start livestream
4. open livestream in browser

### Describe the expected behavior

If only a video channel is send either mux a silent chanel to the video for displaying it correctly in a browser or the parsing of the m3u8 should be aware that no sound channel is present.

### Additional information

* PeerTube instance:
  * URL: static.83.88.47.78.clients.your-server.de
  * Version: 4.3.0
  * NodeJS version: 18.9.1
  * Ffmpeg version: ffmpeg version 4.3.4-0+deb11u1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)

* Browser name, version and platforms on which you could reproduce the bug: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 (same on Firefox)
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
* VLC show only Stream 0 in not transcoded hls output

<img width="509" alt="hls-not-transcoded" src="https://user-images.githubusercontent.com/1936946/192716228-403e3789-6769-4821-bcb1-aea177dd27ee.png">

* VLC media information on transcoded mp4 output

<img width="509" alt="mp4-transcoded" src="https://user-images.githubusercontent.com/1936946/192716874-3a6ceba1-c369-493f-b02e-8aa2f004ccf9.png">

**Comment by Chocobozzz** [comment]
Thanks for the issue. It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1ce4256a6577d0607320a320d9c5d328bdd162f7
