### ISSUE TITLE
Add suspension points after the truncated name of the video to notify that it's not the end of the sentence

### ISSUE THREAD

**Issue by antistress** [Chocobozzz/PeerTube#5307]
### Describe the current behavior

In user/video-channels the lack of suspension points after the truncated name of the video let the user think that it's the end of the sentence

### Describe the expected behavior

Suspension points after the truncated name of the video should be there to notify that it's not the end of the sentence

### Additional information

* PeerTube instance: apps.education.fr

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/9fb75b169d8255bc3a8bbd8b872f476dc79e3fec
