### ISSUE TITLE
Add External Storage information

### ISSUE THREAD

**Issue by Sir-Grizzly** [Chocobozzz/PeerTube#5308]
### Describe the problem to be solved

I want to move some my oldest movies to external storage (backblaze) 

after copying, I have no information which movies are on the local disk and which are in external storage.
<img width="536" alt="Screen Shot 2022-09-28 at 9 54 12 PM" src="https://user-images.githubusercontent.com/99275875/192921325-8c6dbd48-45c1-49fb-b2fd-3f99f6a4f197.png">

Is it possible to add the "external storage" status
This would be helpful for video management if I wanted to keep some files locally

Thx

**Comment by Nalem14** [comment]
Also a button like the "Run HLS transcoding" for "Move to object storage" (if enabled) could be a good solution when some video failed to move.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/1a3b53de6f39d0301c48d47d53cca3eb7cd60197
