### ISSUE TITLE
High virt memory usage

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#5309]
### Describe the current behavior

Yes it's virt memory but I don't recall this on the previous version with nodejs 16. This is with a fresh restart. I'm not sure if this is because I'm using the github 4.3.0...4.3.0^0 instead of the standard 4.3.0 release though.

![peertube1](https://user-images.githubusercontent.com/112714131/193153924-434b5d10-03aa-4ce9-92ef-db5c32651eca.png)

### Steps to reproduce

??

### Additional information

* PeerTube instance:
  * URL: vidbin.org
  * Version: 4.3.0...4.3.0^0
  * NodeJS version: 18
  * Ffmpeg version: git

**Comment by Chocobozzz** [comment]
Seems to be related to NodeJS, and not very important.

**Comment by emansom** [comment]
@vid-bin You could try running Node.js with the [`--lite-mode`](https://github.com/v8/v8/blob/d757cd5c63f38f096130d8ba747573c30c672269/src/flags/flag-definitions.h#L423) and [`--optimize-for-size`](https://github.com/v8/v8/blob/d757cd5c63f38f096130d8ba747573c30c672269/src/flags/flag-definitions.h#L945) command line option (check output of `node --v8-options` to see a full list) to lower memory usage.
