### ISSUE TITLE
Support for channel sync from odysee.com/lbry network

### ISSUE THREAD

**Issue by FillingTheVoidOnYT** [Chocobozzz/PeerTube#5313]
### Describe the problem to be solved

would be great to sync channels from the lbry network or even the odysee frontend

### Describe the solution you would like

being able to sync channels on another platform

**Comment by Chocobozzz** [comment]
Hello,

We rely on youtube-dl and/or yt-dlp to download remote videos/channels/playlists. To support more websites, you need to create an issue on their repository.
