### ISSUE TITLE
Ability to view local comments missing

### ISSUE THREAD

**Issue by grower-rhyme** [Chocobozzz/PeerTube#5315]
### Describe the problem to be solved

I'm pretty sure this used to be a thing. I'm unable to view comments made by users who are registered on my instance. Not comments on my instance, but if a user registers on my instance and comments somewhere else, I can't tell.

### Describe the solution you would like

I want a way to view comments made by my users, even if the comments made are on other instances. My goal here is to ensure that the users on my instance are not spamming other instances and videos.

**Comment by Chocobozzz** [comment]
Hello,

The admin overview of comments should show comments made by your users, even on remote instances. Can you explain why you think it's not the case?

**Comment by grower-rhyme** [comment]
Oh. Woops. It appears that you are correct. I guess my instance was just so new and small that there no such comments before, so I assumed I simply couldn't see them, but I do now. Thank you.
