### ISSUE TITLE
Possibility for plugins to disable validation of segments

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5317]
### Describe the problem to be solved

I'm integrating a third part live stream solution to a PeerTube instance and therefore would need to disable segment validation. Currently that's not possible with the `filter:internal.player.videojs.options.result` or any other filter.

### Describe the solution you would like

* `filter:internal.player.p2PMediaLoaderOptions.options.result`
* Rewrite implementation of `filter:internal.player.videojs.options.result` to be able to manipulate the p2pMediaLoaderOptions.

**Comment by Chocobozzz** [comment]
> Currently that's not possible with the filter:internal.player.videojs.options.result or any other filter.

Can you explain why?
