### ISSUE TITLE
Ability to enable and disable privacy publishing options for server.

### ISSUE THREAD

**Issue by scoute** [Chocobozzz/PeerTube#5321]
### Describe the solution you would like

First of all great thanks for the app!

I need the ability to customize publishing options:
[ ] - public
[ ] - unlisted
[x] - private
[x] - internal
to make my server completely private without the risk of making it publicly available.

Is it possible now?

**Comment by Chocobozzz** [comment]
Hello,

Yes you can using a plugin: https://docs.joinpeertube.org/contribute-plugins?id=update-video-constants (`videoPrivacyManager.deleteConstant(...)`)

**Comment by kaamui** [comment]
Hi,

I would like to achieve that but at the user-level (some users can upload public videos, some just internal, etc). What would be the best way to do so ? Is there a hook/filter I can user to test some conditions ?

I looked at the code a bit, but not being familiar with angular, nodejs and typescript makes it hard for me to know what and where I should look at. I think the simpler way to do it is to modify the options according to some random conditions, but I would like to do it the good way so I can provide a PR (if you are interested). From what I've seen so far, the enum is used as-is to fill the select, so it would imply some internal changes. I don't know if I can make a plugin that overrides this part.

The context is that we would like to have teachers able to publish public videos, students able to publish internal videos only, etc

Btw, https://docs.joinpeertube.org/contribute-plugins?id=update-video-constants <= `videoLanguageManager.addConstant('al_bhed', 'Al Bhed')` :smile: Oui syta so tyo :smile:
