### ISSUE TITLE
Cannot build Docker image:  /app/tsconfig.json missing

### ISSUE THREAD

**Issue by klodner** [Chocobozzz/PeerTube#5322]
### Describe the problem

Cannot build Docker image using /support/docker/production/Dockerfile.bullseye:

> 
> > peertube@4.2.2 build:client
> > bash ./scripts/build/client.sh
> 
> 
> > peertube@4.2.2 build:server
> > bash ./scripts/build/server.sh
> 
> 
> > peertube@4.2.2 tsc
> > tsc
> 
> 7:27:12 PM - Projects in this build:
>     * tsconfig.json
> 
> error TS5083: Cannot read file '/app/tsconfig.json'.

Expected: image builds

### Additional information

* PeerTube version: 4.2.2, 4.3

**Comment by klodner** [comment]
Used release asset /peertube-v4.3.0.zip

source code release works, so above release is stripped somehow, perhaps Dockerfile should also be stripped, when it i not working with that release.

**Comment by Chocobozzz** [comment]
Done in https://github.com/Chocobozzz/PeerTube/commit/4373b2d56658391d5a45754c464be2ad37bffc37
