### ISSUE TITLE
Non finished jobs show wrong finished date

### ISSUE THREAD

**Issue by alejandrocobo** [Chocobozzz/PeerTube#5323]
### Describe the current behavior

When there is an active transcoding job running, the Finished date shows
`Finished on 1/1/70, 1:00:00.000 AM`

When the transcoding job is waiting, it shows both, the 'Processed on' and 'Finished on' dates:
```
Processed on 1/1/70, 1:00:00.000 AM
Finished on 1/1/70, 1:00:00.000 AM
```

### Steps to reproduce

1. Upload a video or wait somebody uploads one.
2. Go to 'Administration' > 'System' > 'Jobs'
3. Filter by 'Job State Active' or 'Waiting'.
4. Expand the information.
5. Check the dates.

### Describe the expected behavior

If it is an active job, it shound't show the 'Finished on' date.
If it is a waiting job, it shoudn't show any date.

### Additional information

* PeerTube instance:
  * Version: 4.3.0

Thanks.

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1c048f04a5a37fcf870804157216a271ac709e9d
