### ISSUE TITLE
Mistake in "week" Spanish translation

### ISSUE THREAD

**Issue by alejandrocobo** [Chocobozzz/PeerTube#5328]
### Describe the current behavior

When the number of weeks shown below the title is an integer, there is no space between the number and the string 'semana' (week in Spanish).

AFAIK it only happens when the interface is in Spanish.

![imagen](https://user-images.githubusercontent.com/1640709/194152541-e3f1d40d-fff9-4227-ab9e-7e99ac3cab04.png)

### Steps to reproduce

1. Set the interface into Spanish.
2. Look for a video that is older than one week and more recent than a month.

### Describe the expected behavior

There should be a space between the integer and the string.

### Additional information

* PeerTube instance:
  * Version: 4.3.0

**Comment by Chocobozzz** [comment]
Hi,

You can fix the string directly in weblate: https://weblate.framasoft.org/translate/peertube/angular/es/?offset=1&q=semanas&sort_by=-priority%2Cposition&checksum=#history

(I fixed it)
