### ISSUE TITLE
Virtualmin install script

### ISSUE THREAD

**Issue by kdmiller45** [Chocobozzz/PeerTube#5330]
### Describe the problem
I submitted Peertube to have a install script written for Virtualmin and this was there reply

Dependencies on this one are really rough.
[docs.joinpeertube.org](https://docs.joinpeertube.org/dependencies)
[PeerTube documentation](https://docs.joinpeertube.org/dependencies)

PeerTube documentation

Node 14 is not available in any of our supported distros, AFAIK. Maybe Ubuntu 22.04 has one that new. But, given they’re going to probably stay on the bleeding edge forever, it will be impossible to update old installs to new ones in the future.

Also, PostgreSQL, while a fine database and one we support and like, is very rarely the database our users choose (so much so that we default to MariaDB, and never install PostgreSQL, by default…we’ll support it if you choose to install it, and there is a command to configure it for use with Virtualmin, but it’s not there for like 99% of Virtualmin users).

I think this one is a non-starter for an install script. I won’t rule it out in the future, when Docker is an option for installable apps. But, for now, this is just too much work for something that literally only a handful of users would even be able to use.

### Additional information

* PeerTube instance URL: https://worldofvids.com
* PeerTube version: 4.2.2  ( i have a working instance up but when I try to upgrade to current version it bombs the site)
* NodeJS version: 14.20.1
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by emansom** [comment]
Migrate to Cloudmin and deploy the PeerTube container.

One could also choose a more freedom respecting, and less reliant on a single entity [Rocky](https://rockylinux.org/) server and [deploy Cockpit](https://www.tutorialworks.com/podman-monitoring-cockpit-fedora/) for a fancy web UI.

_(tutorial references Fedora, instructions apply to any RHEL derivative)_
