### ISSUE TITLE
move-to-object-storage COMPLETED, but actually FAILED? Also, please add Cloudflare R2 compatibility.

### ISSUE THREAD

**Issue by dausruddin** [Chocobozzz/PeerTube#5333]
### Describe the current behavior

I am trying to use Cloudflare R2 S3 compatible) with my Peertube instance.

Although the job is completed,
![image](https://user-images.githubusercontent.com/5763466/194686115-2af0d085-d2ab-44dc-9abd-ccf4cbdc1a7a.png)

it actually failed
![image](https://user-images.githubusercontent.com/5763466/194686149-1b4d2ae1-ff19-4752-a452-07bbb1bdc02d.png)

In `peertube.log`, I saw this error
```
NotImplemented: Header 'x-amz-acl' with value 'public-read' not implemented
```

You can read more info regarding this in rclone forum
https://forum.rclone.org/t/not-implemented-headers/30744/

Simply put, R2 buckets are always private. Public files will be accessible from public URL, or custom domain.
Adding R2 support will be greatly appreciated.

### Steps to reproduce

1. Use R2 as your object storage
2. Your video now will served from local instead

### Describe the expected behavior

Video uploaded to Cloudflare R2 and served from there.

### Additional information

* PeerTube instance:
  * URL: N/A
  * Version: v4.3.0
  * NodeJS version: v14.19.0
  * Ffmpeg version: 4.1.8-0+deb10u1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

I'm not sure to understand: if R2 doesn't support public buckets, how do you access the files with a public URL?

**Comment by dausruddin** [comment]
I'll give an example.

- S3 endpoint: `https://eb0bfc815409a215ddcd86114bcf4adb.r2.cloudflarestorage.com/bucket`

It will stay private. If you want to access publicly, use

- Public Access: `https://pub-1a81697cb2654d6f8df6c11aee4153d3.r2.dev`

So, for a private file,

```
https://bucket.eb0bfc815409a215ddcd86114bcf4adb.r2.cloudflarestorage.com/test-file.txt
```

You can access them publicly at

```
https://pub-1a81697cb2654d6f8df6c11aee4153d3.r2.dev/test-file.txt`
```

From what I understand, we can use public URL as cdn in settings.
So the issue now is, peertube should upload a file as private for R2.
I'm not used to S3, or R2, but I explained a s the best as I can

**Comment by Chocobozzz** [comment]
Thanks for the explanation. Then the `upload_acl` setting should do the trick: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L145

**Comment by dausruddin** [comment]
Oh I see. Thanks a lot!
