### ISSUE TITLE
One channel has no publicKeyPem

### ISSUE THREAD

**Issue by xundeenergie** [Chocobozzz/PeerTube#5335]
### Describe the current behavior

Only one channel on my peertube-instance is not able to federate with lemmy.

It can not be found from lemmy. ALL other channels are found. 
Videos from this channel are also not found by lemmy, but from other services (friendica, pleroma...)
When i move a video from this channel to another channel, it is found by lemmy.
Moving the video back, it is not found again.

### Steps to reproduce

1. Go to a lemmy-instance and try to find !eisenbahn@kino.schuerz.at
2. Go to a lemmy-instance and try to find !h0e@kino.schuerz.at
3. eisenbahn is not found, h0e is found

### Describe the expected behavior

The Channel and it's videos should be found from lemmy too, as the other ones.

### Additional information

* PeerTube instance: 
  * URL: https://kino.schuerz.at
  * Version: 4.3.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

I opened an Issue in Lemmy https://github.com/LemmyNet/lemmy/issues/2402 and the devs there said, that my peertube does not deliver "publicKeyPem"

```
"publicKey": {
    "id": "https://kino.schuerz.at/video-channels/eisenbahn#main-key",
    "owner": "https://kino.schuerz.at/video-channels/eisenbahn",
    "publicKeyPem": null
},
```
on this channel. Therefore it is not found by lemmy.

**Comment by xundeenergie** [comment]
So i found in my database, that there is a channel with the name "eisenbahn" AND a user with the name "eisenbahn"

The user is from a non any more existing friendica instance, and the group is from my peertube, account.
The Group has really no private or public-key in the table "actor".
The other groups from my peertube-account have such a pubkey and a private-key.

How can it happen, that a channel has no pub- and private-key?

And can i recreate this?

**Comment by Chocobozzz** [comment]
> How can it happen, that a channel has no pub- and private-key?

In previous peertube version, private/public key generation could fail without notice/retries. It should be fixed now.
To fix this specific bug, you can generate the public/private keys of this channel and update the row manually in the database.

To generate the same keys as peertube, use `node` and execute this script:
```js
const options = {
  modulusLength: 2048,
  publicKeyEncoding: {
    type: 'spki',
    format: 'pem'
  },
  privateKeyEncoding: {
    type: 'pkcs1',
    format: 'pem'
  }
}

require('crypto').generateKeyPair('rsa', options, (err, publicKey, privateKey) => {
  if (err) return console.error(err)

  console.log('Public key')
  console.log(publicKey)
  console.log('Private key')
  console.log(privateKey)
})
```

**Comment by xundeenergie** [comment]
Ok... Thank your.

Can you, please give me a hint, how i get the pub/privkey into the database? (Postgresql). 
I have only basic knowledge about such steps...

**Comment by xundeenergie** [comment]
Oh, i got it!

thank you. Now the channel is working correctly.

This would be a great improvement for older instances, to fix the missing keys with a button in channel-settings (only if the keys are missing!)
