### ISSUE TITLE
Websocket routes for plugins

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5339]
### Describe the problem to be solved

Actually, plugins can't create backend routes that use the websocket protocol, because the nginx configuration doesn't allow it.

Moreover, the `server` object is not easily available, so that plugins can do:
```javascript
server.on('upgrade', (req, res) => {
  if (req.url === 'my_plugin_ws_route') {
    // my code
  }
})
```
Or:
```javascript
server.off('upgrade', my_callback)
```

I'm looking a way to do this for the livechat plugin.

### Describe the solution you would like

There should be a nginx location using the rule `@api_websocket` available for the plugins.

Plugins should also have a way to listen (and stop listening) the `upgrade` event on the `server` object.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/9d4c60dccc8e7e777ad139a82e9f61feda9d21fc
