### ISSUE TITLE
Using docker for development on localhost

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5342]
### Describe the desired information/correction

In the v4.3.0 Changelog, there is this line: «Add ability to easily use the docker compose stack on localhost».

I don't really know how this is supposed to be used.

Before v4.3.0 I was already using docker for dev environnement (to work on plugins). But in my case, I used 127.0.0.1, instead of `localhost` for the webserver hostname.

So I decided to give a try to this new features. I changed the configuration of my development Peertube from 127.0.0.1 to localhost.
I ran the `update-host` script.

And now, I have the following error: «Incorrect request parameters: uris»

![image](https://user-images.githubusercontent.com/38844060/194896662-f1a786b5-f559-4c8d-9d7c-47e8a50d3f7c.png)

It seems these errors are because my root channel has `root_channel@localhost:9000` as ActivityPub handle.

Reading the code lead to this line:

https://github.com/Chocobozzz/PeerTube/blob/dce2aba1e2c39535ed6af43f6aaf792ead8b0a6e/server/middlewares/validators/user-subscriptions.ts#L24

Then, at the end:

https://github.com/Chocobozzz/PeerTube/blob/dce2aba1e2c39535ed6af43f6aaf792ead8b0a6e/server/helpers/custom-validators/servers.ts#L6-L18

My conclusion is: I get this error because my NODE_ENV is not `dev`.

I can't find any documentation to use docker with localhost. I neither can't find any NODE_ENV set in the docker example files.

How I'm I supposed to use the docker setup for dev purpose on localhost?

Must I add `NODE_ENV=dev` in the `.env` file in my docker dir?
Then rename the database from `peertube_production` to `peertube_dev`?

Maybe NODE_ENV is missing in https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/.env ?

**Comment by Chocobozzz** [comment]
Yes, please give it a try with `NODE_ENV=dev` to see if the instance is working correctly. Then I'll create a section in the contributing guide

**Comment by JohnXLivingston** [comment]
I made following changes in `.env` file:
- add `NODE_ENV=dev`
- replace `POSTGRES_DB=peertube` with `POSTGRES_DB=peertube_dev`
- add `PEERTUBE_DB_SUFFIX=_dev`

But I still got the error. I don't understand why.

**Comment by JohnXLivingston** [comment]
Looking at this line:

https://github.com/Chocobozzz/PeerTube/blob/dce2aba1e2c39535ed6af43f6aaf792ead8b0a6e/server/helpers/custom-validators/servers.ts#L17

I assume that the `host.split('://').length === 1` if for testing that there is no «http://» in the value?
If so, isn't this equivalent to add the option `isURLOptions.protocole = false`?

**Comment by JohnXLivingston** [comment]
```bash
docker-compose exec -u peertube peertube bash
peertube@a8102ff8f19e:/app$ echo $NODE_ENV
production
```

Ok, it seems that my understanding of docker .env file is wrong. The container still thinks it is in production mode.

**Comment by JohnXLivingston** [comment]
I don't understand why, but I had to add this in the `.env` file:

```bash
PEERTUBE_REDIS_HOSTNAME=redis
```

Now I have an unexpected result... Peertube is looking data into `/app/storage/` instead of `/data`.

I think something is broken in my Docker environnement, and configuration files are not read in the correct order.

**Comment by JohnXLivingston** [comment]
Ok, got it!

```
 Using following configuration file hierarchy: /app/config/default.yaml -> /app/config/dev.yaml -> /app/support/docker/production/config/custom-environment-variables.yaml.
```

Changing the NODE_ENV changes the configuration files that are read.

**Comment by Chocobozzz** [comment]
Hi,

In fact you don't need to use a custom `dev` environment. We don't have time to support a dev docker stack. However there was a bug in PeerTube regarding this URL validation that should be fixed by https://github.com/Chocobozzz/PeerTube/commit/e5fc6b598325c861a7696e320b8de0eecb856cc7

**Comment by emansom** [comment]
Wasn't the gitpod stuff meant for "dev" environments?
