### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by zikzakfr** [Chocobozzz/PeerTube#535]
* **PeerTube version or URL:**
https://peertube.datagueule.tv/videos/watch/0b04f13d-1e18-4f1d-814e-4979aa7c9c44
* **Browser name/version:**
Firefox Nightly 61.0a1
* **NodeJS version:**
N/A

* **What is the expected behaviour?**
Reduced usage of RAM
* **What do you see instead?**
Watchijng the URL provided and seeding it to other peers I noticed at some point that the computer was not responsive any longer as I kept seeding.
The browser was using 100% of the available memory.
At first I thought it was related to the number of peers, but even alone (on a resolution not seeded much) the memory usage continued to grow as the video advanced.

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

**Comment by Chocobozzz** [comment]
How many memory Firefox consumes when you watch the video?

**Comment by zikzakfr** [comment]
Everything. It topped at more than 3GB. The videofile is 2GB.
I'm now trying the 480p version and I'm already above 600MB (and counting).

**Comment by rigelk** [comment]
Canonical issue could very well be https://github.com/webtorrent/webtorrent/issues/248. We should check if we use a version of webtorrent that leverages the then-fix https://github.com/webtorrent/webtorrent/commit/c85dd3b83bdbd7fcbbb32c65a080b7011e4daede

**Comment by anayrat** [comment]
Hi, I have the same issue with Opera and Chrome.

**Comment by Chocobozzz** [comment]
It's because WebTorrent stores video chunks in memory. I'm testing storing them in [IndexDB](https://developer.mozilla.org/fr/docs/Web/API/API_IndexedDB) but we would need to delete data after the watch (we are not interested in storing them indefinitely for now) and add some optimizations (bulk insert chunks etc). 

I'm currently creating a custom [abstract chunk store](https://github.com/mafintosh/abstract-chunk-store) for this purpose.

**Comment by rigelk** [comment]
@zikzakfr with the upcoming solution @Chocobozzz is developing, that wouldn't be a concern anymore as the video would not be stored in RAM anymore. But in the meantime, that is indeed a concern.

**Comment by zikzakfr** [comment]
I'm really confident (and everyone else) that he will make us forget about any other solution to share videos efficiently ;-)

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/efda99c30f2c04702bf57cc150cdfdd0acccc178

@zikzakfr @anayrat @rigelk Could you test on https://peertube2.cpy.re/videos/watch/0b04f13d-1e18-4f1d-814e-4979aa7c9c44 since it's quite experimental

**Comment by zikzakfr** [comment]
Memory usage is now around a gigabyte and stay around it.
Was the change an expected tradeoff with CPU usage? All cores are at 100% when playing the video and above 50% when paused.
Firefox 62.0a1 64bits.

**Comment by zikzakfr** [comment]
After the five minute mark I'm between 50% and 100% CPU usage and 1GB of RAM used.
Based on this link:
https://peertube2.cpy.re/videos/watch/0b04f13d-1e18-4f1d-814e-4979aa7c9c44

**Comment by Chocobozzz** [comment]
It's a webtorrent issue: https://github.com/webtorrent/webtorrent/issues/903 and https://github.com/webtorrent/webtorrent/search?q=cpu&type=Issues

**Comment by zikzakfr** [comment]
Oh sh... So either huge ram usage on long content or high CPU usage after 5 minutes.
I wonder why I was the only one to face the latter, is it also related to the browser (if other testers used something else than Firefox Nightly)?
