### ISSUE TITLE
Trending, Recently added, and Local videos screens are blank after running regenerate-thumbnails

### ISSUE THREAD

**Issue by CorpulentBrony** [Chocobozzz/PeerTube#5350]
### Describe the current behavior

I recently upgraded from PeerTube 3.1.0 to 3.2.1.  I then ran the regenerate-thumbnails script.  After running it, the Trending, Recently added, and Local videos screens are now blank.  I do see videos under Discover and from individual user's pages.

### Steps to reproduce

1. Have an existing PeerTube 3.1.0 instance
2. Manually upgrade to 3.2.1
3. Run regenerate-thumbnails

### Describe the expected behavior

Thumbnails are regenerated and the Trending, Recently added, and Local videos screens remain as they were before the thumbnail regeneration but with the newly generated thumbnails.

### Additional information

* PeerTube instance:
  * URL: https://pony.tube/
  * Version: 3.2.1
  * NodeJS version: 14.18.3
  * Ffmpeg version: N-63101-gc92edd969a-static (from master on 2022-09-10)

* Browser name, version and platforms on which you could reproduce the bug: Any
* Link to browser console log if relevant: Nothing shows as 404 or errors, it just doesn't load any videos on the page
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Uninstalling social sharing plugin should fix your issue

**Comment by CorpulentBrony** [comment]
> Uninstalling social sharing plugin should fix your issue

Yes, this worked!  Thank you so much for your help, keep up the great work!
