### ISSUE TITLE
Unable to encode video after Peertube crash

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#5355]
### Describe the current behavior

Hello!

## Context

My instance is pretty old (from the first beta) and I used to have a defective hdd that provoked Peertube crash when too much video are uploaded and encoded without pause.

When this crash occurs, Peertube is restarted, but some videos stay in "to transcode" status.

Usually when I detect such video, I use the [create-transcoding-job](https://docs.joinpeertube.org/maintain-tools?id=create-transcoding-jobjs) cli to patch video manually and relaunch the HLS encoding.

## Bug

With the new Peertube v4.3.0 and the adding of the new admin view to see all video, I am able to get directly all video "local:true and hsl:false" to get all this defective videos, that's pretty good!

Here is an example of such a video: 
![Capture d’écran de 2022-10-14 14-51-10](https://user-images.githubusercontent.com/7755000/195852521-4c3b9e87-49a1-4f90-aa1d-2e08ea9aee8b.png)

But, for a unknown reason, the transcode-job does not work anymore.

Usually,when I run the cli, there is an answer "transcode jobs XXX created". Now, it says nothing:
```
# sudo -E -u peertube NODE_CONFIG_DIR=/config NODE_ENV=production npm run create-transcoding-job -- --generate-hls -v fQu8LuS2w6LeWwmHMJLdfz

# 
```
There is no logs visible in peertube logs when this command is launched.

The new admin view allow to launch encoding job for "webtorrent only" video, but the choice is absent for these video.

## Try to fix

I have played around the database to change the video.state=2 to videos.state=1 to remove the "To transcode" tag.
```
update video set "state"='1' where "id"='230049';
```

With this manipulation, the "Run HLS transcoding" appears in the admin view. But when I click, I got another error: 

![Capture d’écran de 2022-10-14 14-51-31](https://user-images.githubusercontent.com/7755000/195853662-153a165e-81e2-4795-aff6-c18f4d25df7e.png)

So I am unable to patch these videos.

It seems an old transcoding jobs exists in the videojobinfo table, that needs to be removed manually.

### Steps to reproduce

Unfortunately as it was because of defective hdd, not sure how to reproduce exaclty but I think :

1. Uplaod a video and wait for the ffmpeg process
2. kill -9 the ffmpeg process, and perhaps the full Peertube process
3. Relaunch peertube and check the video status

### Describe the expected behavior

A way to workaround such crash could be useful.

Some ideas could be to allow the possibility to re-encode video if the tags "to transcode" is here since a long time.

Detecting the ffmpeg process or the existence of waiting/active jobs regarding of entries in videojobinfo table may help to reconcile the BDD status and the real status.

This is not a classic administrative task, perhaps a cli to launch such a check BDD status agains real status for all videos?

Thank you!

### Additional information

* PeerTube instance:
  * URL: https://videos.pair2jeux.tube
  * Version: v4.3.0
  * NodeJS version: v16.17.1
  * Ffmpeg version: 4.3.4-0+deb11u1

**Comment by Chocobozzz** [comment]
Hi,

I think we can create another REST endpoint to cancel all transcoding tasks of a specific video. With a robust endpoint (not failing if the video is in inconsistent state) it should fix this kind of issue.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/89aa3331106874266f6feeee7bff852da2c1727e

You can now force transcoding if you consider the video is in a broken state
