### ISSUE TITLE
Let admin re create import job

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5358]
### Describe the problem to be solved

Our redis server went down for several hours. During this period some users created imports, which now are stuck in a `TO_IMPORT` state with no jobs that will run the import.

### Describe the solution you would like

In /admin/videos/list, add an option to create an import job (below "Start HLS transcode"). This would delete any existing waiting/running jobs and create a new job.

**Comment by emansom** [comment]
IMHO this is a job queue persistence problem, not a import process problem.

PeerTube needs some way to persist the job queue locally to a local event store (e.g. SQLite) in case of network failure, without running the jobs.

Then once BullMQ/Redis kicks back in, it'll read that local event store, create and run jobs.

**Comment by emansom** [comment]
> The kind of solution you're proposing sounds good. But even if we'd have that architecture there may be conditions that makes the video stuck in `TO_IMPORT` state, so wouldn't it good for an admin to make it rerun?

When storage runs out it'd fail too, yeah. _Not much to fix that scenario, unless there'd be some systemd/filesystem API to reserve a certain amount of disk space always; but there isn't (yet)._

The more PeerTube eases recovery scenarios for users, the better. PeerTube shouldn't require sysadmin skills to administer. Yes, a button to restart stuck imports would aid in that.

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/4939
