### ISSUE TITLE
Add ability to hide "Download" for a video

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#536]
Some uploaders don't want people to be able to easily download their video. It's their choice, so let's add an opt-out checkbox in the upload form.

Of course, this is just "cosmetic". If someone really wants to download the video, he will be able to do it (like we can on other video platforms with youtube-dl for example).

**Comment by leethax666** [comment]
Seems like a false sense of privacy

**Comment by rigelk** [comment]
It has nothing to do with privacy though.
