### ISSUE TITLE
Error: "Cannot access to remote resource"

### ISSUE THREAD

**Issue by Tulux** [Chocobozzz/PeerTube#5360]
### Describe the current behavior

Similar to #4473

### Steps to reproduce

1. Go to any video of any instance
2. Remote comment referring to my own instance (florent@myinstance.tld)
3. Error: "Impossible d'accéder à la ressource à distance"

### Describe the expected behavior

A remote comment should be added

### Additional information

* PeerTube instance: 
  * URL: May be provided in private message
  * Version: 4.3.0
  * NodeJS version: 18.10.0
  * Ffmpeg version: 5.1.2

* Browser name, version and platforms on which you could reproduce the bug: Firefox 102.3.0, Debian 12
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
[logs.txt](https://github.com/Chocobozzz/PeerTube/files/9795526/logs.txt)

**Comment by Chocobozzz** [comment]
Please end me your instance URL and also paste logs (browser logs, network logs and server logs)

**Comment by Tulux** [comment]
Hi @Chocobozzz, I just sent you an email.
Florent

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the email. The server error is 

```
Cannot search remote video channel https://video.latavernedejohnjohn.fr/w/kK5mhY9kiSCyedgAXSRFAU.","err":{"stack":"RequestError: queryA EDESTRUCTION video.latavernedejohnjohn.fr\n
```

I never saw this error, and google doesn't seem to have a lot of answer about it. But it seems to be related to a DNS problem between nodejs and your DNS server

**Comment by Tulux** [comment]
You were right, my resolv.conf was providing ipv6 adresses only.
Solved !
