### ISSUE TITLE
Add missing videos sort options in admin

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5363]
### Describe the current behavior

When you are on the main Trends page, there is a drop-down sorting filter on the right.
For example, there is an item: Sort by Original Publication Date

![1](https://user-images.githubusercontent.com/11453567/196344696-0a94dae0-0e74-4b5d-995b-3780c1190f5f.png)

but if you go to the administrator settings, then there is no such item there, as well as many other options.

![2](https://user-images.githubusercontent.com/11453567/196344727-6b9e26d1-193b-46a4-88d7-b67c7b747cd1.png)

### Describe the expected behavior

In the Trends section in the admin settings, all available options for the trends page should be displayed.

### Additional information

* PeerTube instance:
  * URL: https://peervideo.ru
  * Version: 4.3.0-nightly-2022-10-13

**Comment by jee1mr** [comment]
Hi @Chocobozzz Shall I pick this up?

**Comment by Chocobozzz** [comment]
Sure you can

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/5471
