### ISSUE TITLE
External storage: Video not available until all transcoding jobs are done

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5366]
### Describe the current behavior

The output from transcoding doesn't get uploaded to external storage until the last transcoding job has finished. This means that during the transcoding process is not available.

### Steps to reproduce

1. Config external storage
2. Upload video
3. Visit video

### Describe the expected behavior

After each transcoding job all files should be moved to external storage so that they're playable.

### Additional information

* PeerTube instance:
  * Version: 4.3.0

**Comment by Chocobozzz** [comment]
> The output from transcoding doesn't get uploaded to external storage until the last transcoding job has finished. This means that during the transcoding process is not available.

The video is not served by peertube before the move job?

**Comment by Chocobozzz** [comment]
Are you talking about a re-transcoding process?

Because during the first transcoding, the streaming playlist is still on filesystem and so PeerTube should serve the master playlist and fragmented mp4 from disk.

**Comment by Chocobozzz** [comment]
Okay so if it's a feature request to allow the admin to choose when the video is available (after how many resolutions for example) please create another request detailing what you would want as an admin (config option, use case etc)
