### ISSUE TITLE
Add preview thumbnail in video progress bar

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#537]
Youtube offers a way to preview the frames when hovering the progress bar. This is very convenient when you want to go directly to a certain moment of a video or to watch it again.

![image](https://user-images.githubusercontent.com/371705/39661822-d5203a06-5058-11e8-9ac3-7e5940d914cd.png)

Unfortunately there doesn't seem to be maintained and convenient plugins for videojs (I saw [this one](https://github.com/TwigWorld/videojs-thumbnails) or [this another one](https://github.com/brightcove/videojs-thumbnails)).

It seems that it is not that difficult. We could use canvas for that: https://jsfiddle.net/epistemex/gdp00x2s/

Also definetely worth to implement it as a plugin.

What do you think?
Florent

**Comment by Chocobozzz** [comment]
I think it could be suitable in the core PeerTube. I don't think we should use federation for these "progress thumbnails", but a cache as we do with previews.

**Comment by BO41** [comment]
I found one which is only
- a month old https://www.npmjs.com/package/videojs-sprite-thumbnails-for-videojs6
- 5 months https://www.npmjs.com/package/videojs-vtt-thumbnails
- and 6 months https://www.npmjs.com/package/videojs-sprite-thumbnails

would this count, as being maintained?

**Comment by tilllt** [comment]
I would really like this feature to be added. There would be non js-alternatives to this, like ffmpeg sampling the video at different times on initial thumbnail selection. The problem with how it is in the stable version right now is that the random thumbnail selection often chooses an image which does not represent the video at all.

**Comment by Chocobozzz** [comment]
@tilllt See https://github.com/Chocobozzz/PeerTube/issues/1322

**Comment by davidak** [comment]
[Timelens](https://timelens.io/) is a tool for creating visual timelines. It is used on https://media.ccc.de/.

There are also plugins for JavaScript players: https://timelens.io/plugins/

![Screenshot from 2020-08-04 08-52-16](https://user-images.githubusercontent.com/91113/89262411-d72bcb80-d62f-11ea-9645-42bc2a71efba.png)

**Comment by SimplyCorbett** [comment]
It would be nice to have this implemented.

**Comment by Chocobozzz** [comment]
This feature has been implemented in https://github.com/Chocobozzz/PeerTube/commit/d8f39b126d9fe4bec1c12fb213548cc6edc87867 and https://github.com/Chocobozzz/PeerTube/commit/638a2950215af1f11be8e8bdd136ca12e5176c32. It will be available in PeerTube 6 planned at the end of the year 🎉

PeerTube will automatically generate the storyboard of uploaded/imported videos and display them in the player progress bar

![screen_2023-10-12-16_27_08](https://github.com/Chocobozzz/PeerTube/assets/5180488/fffa8766-e4c7-4b3c-b4a0-81ec629245b4)

A script (`npm run create-generate-storyboard-job`) will be available to generate storyboard of local videos uploaded before PeerTube v6.

**Comment by jimaek** [comment]
I wonder, could storyboards be adopted for nice fluid previews of videos when hovering over their thumbnails? Similar to youtube. Cause I think static thumbnails are a huge hit to good user experience. Is something like this planned or possible?

**Comment by Chocobozzz** [comment]
@jimaek Yes I think you're talking about https://github.com/Chocobozzz/PeerTube/issues/3142
