### ISSUE TITLE
Uploads not working when using nginx proxy manager configured using the nginx config file

### ISSUE THREAD

**Issue by Neshura87** [Chocobozzz/PeerTube#5373]
### Describe the problem

Hope this is the correct issue type as I'm not sure whether it qualifies as documentation or installation.

When using nginx proxy manager instead of nginx video uploads get stuck after the first upload package.
Through playing around with the config I have discovered that using
`location ~ /api/v1/videos/upload-resumable` instead of `location = /api/v1/videos/upload-resumable` allows for uploads to work again.
Since I'm using nginx proxy manager I am not sure whether nginx would work with my method or not. If it does I would propose changing the template file so other nginx proxy manager users don't stumble over the same problem.

Edit and Note: I'm using the docker-compose install should that somehow be relevant

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I don't know nginx proxy manager. PeerTube provides a nginx template for a "classic" nginx and we unfortunately don't have time to maintain this config for other nginx related programs.
