### ISSUE TITLE
Signup Process Changes Break Existing Plugins

### ISSUE THREAD

**Issue by own3mall** [Chocobozzz/PeerTube#5375]
### Describe the current behavior

I'm not sure when this changed, but since user signup registration process has changed, existing plugins such as Recaptcha V2 no longer work due to DOM changes.

https://github.com/Chocobozzz/PeerTube/issues/1721

### Steps to reproduce

1.  Install Recaptcha V2 plugin.  (https://framagit.org/rigelk/peertube-plugin-recaptcha)
2.  Go through new user signup / registration process on updated PeerTube instance with recaptcha plugin enabled.  No recaptcha is shown during the signup process due to a console error which states that the plugin script is unable to find a form element which no longer exists when scope of signup is first loaded.

### Describe the expected behavior

Old plugins continue to work.

**Comment by Chocobozzz** [comment]
Hello,

We don't provide DOM compatibility for plugins. It's the reason why we added the concept of HTML placeholders: https://docs.joinpeertube.org/contribute-plugins?id=html-placeholder-elements

Please create the issue on the plugin owner repository

**Comment by own3mall** [comment]
@Chocobozzz Going through the documentation, it doesn't seem there's any infrastructure there anymore for a plugin like this (add recaptcha to sign up form) to hook into?
