### ISSUE TITLE
cloudflare block domain stream .mp4

### ISSUE THREAD

**Issue by dungrew1** [Chocobozzz/PeerTube#5376]
### Describe the current behavior

i have use hls convert but the .m3u8 file has only fragmented files "fragmented.mp4"
why not .ts ? this violates cloudflare's policy, they don't let mp4 files stream, my domain got locked after that

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

I don't know Cloudflare policy and I'm not really sure to understand why they prefer ts files instead of fragmented mp4. We prefer to use fragmented mp4 files because it's easier to maintain (just 1 file) and they can be downloaded by users/directly played in they web browser/video player.

**Comment by emansom** [comment]
Don't use Cloudflare.

![cfmalware_x4](https://user-images.githubusercontent.com/981494/198678458-7b8cb2c1-c982-47a8-9f01-5e300bf65ead.jpg)
