### ISSUE TITLE
Unable to list channels at upload time

### ISSUE THREAD

**Issue by alejandrocobo** [Chocobozzz/PeerTube#5377]
### Describe the current behavior

Hi,

A user of my instances is having problems uploading videos into its account. He gave me a couple of image but I don't know how to reproduce it:

![imagen](https://user-images.githubusercontent.com/1640709/198006418-846d82d5-130b-421d-8493-f058530177a6.png)

If he selects no options, this is the result:
![imagen](https://user-images.githubusercontent.com/1640709/198006478-6884d594-2a81-4dce-bfd1-76b0fe5c42ae.png)

### Steps to reproduce

Explained above.

This is the problematic account: https://tubedu.org/a/andrefuarte/video-channels

### Describe the expected behavior

A list of channels should appear at upload time.

### Additional information

* PeerTube instance:
  * Version: 4.3.0

Thanks.

**Comment by Chocobozzz** [comment]
Hello,

Did you follow the important notes when you upgraded to 4.2? https://github.com/Chocobozzz/PeerTube/blob/develop/CHANGELOG.md#v420 (in particular running `dist/scripts/migrations/peertube-4.2.js` script)

**Comment by alejandrocobo** [comment]
As far as I remember I did but that was long time ago and I am not 100% sure. Is it possible to run it now from 4.3 to be sure?

**Comment by Chocobozzz** [comment]
> Is it possible to run it now from 4.3 to be sure?

Yep!
