### ISSUE TITLE
content go behind of sidebar in RTL

### ISSUE THREAD

**Issue by mskf1383** [Chocobozzz/PeerTube#5385]
### Describe the current behavior

The sidebar cover the content:

![نماگرفت_۲۰۲۲۱۰۳۱_۱۶۳۰۰۲](https://user-images.githubusercontent.com/50908329/199013849-331883c7-054e-4f51-bfbf-801382b10112.png)

### Steps to reproduce

1. Set a RTL language like Persian or Arabic
2. See

### Describe the expected behavior

The sidebar does not cover the content. Like in LTR:
![نماگرفت_۲۰۲۲۱۰۳۱_۱۶۳۴۴۵](https://user-images.githubusercontent.com/50908329/199014504-292768fb-565a-4910-8f9b-8d92c3e3409d.png)

### Additional information

* PeerTube instance:
  * URL: https://tube.tchncs.de
  * Version: 4.3.0

* Browser name, version and platforms on which you could reproduce the bug: Firefox 106.0 on Debian unstable

**Comment by Chocobozzz** [comment]
Hi,

It should already be fixed on develop. You can test on https://peertube2.cpy.re/
I just fixed a screen overflow in https://github.com/Chocobozzz/PeerTube/commit/e4d9696af5927af86943e551d6d88346494ae9bd
