### ISSUE TITLE
Error playing restricted videos in nightly builds

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5390]
### Describe the current behavior

In recent nightly builds, there have been changes with modern video.
I have build 4.3.0-nightly-01-11-2022 installed and all videos that are "Internal" or "Restricted" stopped working.

If I add a new restricted video then it works well. But the old videos don't work-(

### Additional information

* PeerTube instance:
  * URL: https://peervideo.ru
  * Version: 4.3.0-nightly-2022-11-01
  * NodeJS version: v16.18.0
  * Ffmpeg version: 4.3.4-0+deb11u1

* Browser name, version and platforms on which you could reproduce the bug: Firefox, Chrome
* Link to browser console log if relevant: 

![1](https://user-images.githubusercontent.com/11453567/199655231-a200303e-e2ce-46d7-8f7a-a742ee69ea1f.png)

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
```
error[03.11.2022, 08:42:51] Client log: Cannot get sha256 segments

{
  "tags": [
    "client"
  ],
  "username": "onix",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0",
  "stackTrace": "JSON.parse: unexpected character at line 1 column 1 of the JSON data\n",
  "url": "https://peervideo.ru/w/p/ifvikPGPB5ZtWGFYyRCxf7?playlistPosition=17&resume=true"
}
```

**Comment by Chocobozzz** [comment]
Hello,

Ensure you're up to date with the official nginx template

**Comment by Alterak** [comment]
> Ensure you're up to date with the official nginx template

Of course! If I see changes in the nginx or peertube build, then I always change the configuration file.

I have made [these changes](https://github.com/Chocobozzz/PeerTube/commit/216fa9d5793469f2ad958363fb270990fbce3787)

**Comment by Chocobozzz** [comment]
And did you run https://github.com/Chocobozzz/PeerTube/blob/develop/scripts/migrations/peertube-5.0.ts?

**Comment by Alterak** [comment]
> And did you run https://github.com/Chocobozzz/PeerTube/blob/develop/scripts/migrations/peertube-5.0.ts?

I didn't do the migration. I have not seen this information anywhere. Now I'll try to do it.

Can I run the script like this?
`sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production node dist/scripts/migrations/peertube-5.0.js`
