### ISSUE TITLE
Switching off "Allow users to do remote URI/handle search" breaks federation

### ISSUE THREAD

**Issue by FediVideos** [Chocobozzz/PeerTube#5394]
### Describe the current behavior

On my own instance, if I switch OFF the option "Allow users to do remote URI/handle search", it causes almost all federated videos to no longer play properly on my instance. The federated videos are visible, but if I click play they (almost all) refuse to play and show the message "This video is not available on this instance. Do you want to be redirected on the origin instance:"

A few still play, but almost all do not.

Exactly same thing happens if I switch OFF the "Allow anonymous to do remote URI/handle search", it stops federated videos playing on my instance when I'm not logged in.

There's a thread about this issue on the PeerTube support board at https://framacolibri.org/t/video-is-not-available-on-this-instance-message/16040 and I am reporting this bug as suggested by reponse there.

### Steps to reproduce

1. Federate with (for example) chriswere@share.tube, and in Administration > Configuration switch off "Allow users to do remote URI/handle search" and "Allow anonymous to do remote URI/handle search" 
2. Attempt to play the Federated version of (https://share.tube/w/64849036-8d62-41d5-8d9e-cb46a82eb20c) within your own instance 
3. It will not play, but produces the error message "This video is not available on this instance. Do you want to be redirected on the origin instance:"

### Describe the expected behavior

The federated version of the video should play regardless of whether I have switched or or off the option "Allow users/anonymous to do remote URI/handle search".

### Additional information

* PeerTube instance: fedi.video
  * URL: https://fedi.video
  * Version: 4.2.2
  * NodeJS version: unknown (managed hosting instance)
  * Ffmpeg version: unknown (managed hosting instance)

* Browser name, version and platforms on which you could reproduce the bug: Firefox 106.0.1 Ubuntu LInux
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/11ae7e2917ddf6e3c8e53d0855fd786163112d59

As a workaround, following account's channels instead of directly the channel should work :)

**Comment by FediVideos** [comment]
Thank you! :pray:
