### ISSUE TITLE
Error: ffmpeg exited with code 1: Error initializing output stream 0:0

### ISSUE THREAD

**Issue by alejandrocobo** [Chocobozzz/PeerTube#5395]
### Describe the current behavior

When I try to convert a specific video from Webtorrent to HLS, I get this message:

```
Job: e1142e62-3418-48bd-b07b-e38e8b975cae Type: video-transcoding Processed on 5/11/22, 13:32:24,308 Finished on 5/11/22, 13:32:24,699
--
{   "type": "new-resolution-to-hls",   "videoUUID": "4394411b-2097-4868-a87b-ea89004d5bef",   "resolution": 241,   "hasAudio": false,   "copyCodecs": false,   "isNewVideo": false,   "autoDeleteWebTorrentIfNeeded": false,   "isMaxQuality": false }
Error: ffmpeg exited with code 1: Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height Conversion failed!      at ChildProcess.<anonymous> (.../versions/peertube-v4.3.0/node_modules/fluent-ffmpeg/lib/processor.js:182:22)     at ChildProcess.emit (node:events:527:28)     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)


```

There is only one video file with a resolution of 241p@60fps

I get the same error if I try to re-transcode the video to Webtorrent. Maybe it never was property transcoded because of this issue.

### Steps to reproduce

The faulty video is this one: https://video.hardlimit.com/w/9m1rnSfpxEiVfwyGj2V4AX

### Describe the expected behavior

It should be able to transcode the video.

### Additional information

* PeerTube instance:
  * Version: 4.3
  * NodeJS version: v16.15.1
  * Ffmpeg version: 4.3.4-0+deb11u1

Thanks.

**Comment by Chocobozzz** [comment]
Hello,

Can you enable debug logs in peertube and provide more ffmpeg logs? (in particular the payload of `Will run transcode` log)
