### ISSUE TITLE
community fair use button to fight dmca takedowns

### ISSUE THREAD

**Issue by freesoftwarerocks** [Chocobozzz/PeerTube#5396]
### Describe the problem to be solved

False DMCAs plague places like youtube

### Describe the solution you would like

The community decides if content or work is fair use or licensed or not to alleviate mass flagging, so content can be put back up in a few minutes rather than hours or weeks, if the majority or elected few decide that the content is fair use then it goes back up, if not then the process continues.

**Comment by Chocobozzz** [comment]
Hello,

Thanks for the issue but a in its current form the PeerTube instance in managed by its admins, not by the community. Then, it's the administrators that decide if they accept or not a DMCA by removing the content.
