### ISSUE TITLE
Inconsistent contraints for the support field in video channels

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#540]
Steps to reproduce : 
 - edit some video channel
 - enter more than 300 chars in the field and submit the changes
   - → a message appears asking to enter a text with a maximum length of 300 chars
 - enter between 255 and 300 chars in the same field and submit
  - → Error 500 coming from the server. In the logs, you see this : 
```
[skeptikon.fr:443] 2018-05-07 08:47:45.635 error: Error in controller. {
peertube_1       |   "error": "SequelizeDatabaseError: value too long for type character varying(255)\n    at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)\n    at query.catch.err (/app/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:689:18)\n    at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:794:20)\n    at tryOnImmediate (timers.js:752:5)\n    at processImmediate [as _immediateCallback] (timers.js:729:5)"
```

When you reduce your text to a length below 255 chars, the submission succeeds.

Sounds like the constraints between the database and the frontend is inconsistent. The frontend should rather show the warning when the length is above 255.

* **PeerTube version or URL:** 1.0 b3 (6a478b11651a5e764337b3e4c02dba83c919a50a)
* **Browser name/version:** Firefox nightly (61a1)
* **NodeJS version:** v8.11.1

**Comment by Chocobozzz** [comment]
Thanks, should be fixed: https://github.com/Chocobozzz/PeerTube/commit/a10fc78bb0e00e98c8f59edc16cd323b9c8b0615
