### ISSUE TITLE
Display the thumbnail of audio-only recordings rather than a black screen.

### ISSUE THREAD

**Issue by kyrahabattoir** [Chocobozzz/PeerTube#5400]
### Describe the problem to be solved

Currently, audio-only recordings display a black viewport when played.

### Describe the solution you would like

It would be nice if you could display the thumbnail there instead.

**Comment by Chocobozzz** [comment]
Hi,

It should now be the case with https://github.com/Chocobozzz/PeerTube/commit/63e2f087c3410206aa294df8099b005e615592e5
