### ISSUE TITLE
Unable to use Peertube on Firefox developper Edition ﻿﻿﻿﻿﻿Version 107.0b9 (64-bit) on Macos

### ISSUE THREAD

**Issue by LukasSchulz** [Chocobozzz/PeerTube#5401]
### Describe the current behavior

When I try to use peertube, I get the error-message `PeerTube Incompatible browser`

### Steps to reproduce

1. Install latest Firefox developper edition
2. try to use latest peertube

### Describe the expected behavior

Peertube works as in all other current browsers.

### Additional information

* PeerTube instance: 
  * URL: climatejustice.video, but others too
  * Version: 4.3.0 
  * NodeJS version: 
  * Ffmpeg version: 

* Browser name, version and platforms on which you could reproduce the bug: Firefox developper Edition ﻿﻿﻿﻿﻿Version 107.0b9 (64-bit) on Macos
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Can you display web browser console logs? (F12 key)

**Comment by Chocobozzz** [comment]
ping @LukasSchulz

**Comment by LukasSchulz** [comment]
Sorry for my silence, I was very busy.
I just disabled some addons to ensure that it is a browser-specific error, now the problem seems to be gone. Sorry for the inconvenience. I will close this Issue as I think it's an addon problem, not a thing that should be resolved on the peertube-site.
