### ISSUE TITLE
Account description of Mastodon users shows raw HTML

### ISSUE THREAD

**Issue by jeena** [Chocobozzz/PeerTube#5402]
### Describe the current behavior

If a Mastodon account subscribes to you and you click on the notification it brings you to their account page on your server. There the account description is shown as raw HTML instead of being interpreted by the browser. Example: https://tube.jeena.net/a/magicborderguy@mas.to/video-channels

![Screenshot from 2022-11-11 08-04-22](https://user-images.githubusercontent.com/151764/201224558-117cac28-6192-430c-8b79-5d5cf1c6cfb1.png)

### Steps to reproduce

1. Go to the account page of a mastodon user on your PeerTube instance
2. Look at the account description

### Describe the expected behavior

The browser should interpret the HTML so links are clickable.

### Additional information

* PeerTube instance:
  * URL: https://tube.jeena.net
  * Version: 4.3.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: All
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/0e45e336f62a411b3c423be46d16252355c754d7
