### ISSUE TITLE
When video description is truncated and that cut happens on an hyperlink, its url is unveiled

### ISSUE THREAD

**Issue by antistress** [Chocobozzz/PeerTube#5404]
### Describe the current behavior

With apps.education.fr, shortened description unveils the url of the hyperlink when cut happens at the corresponding part

### Steps to reproduce

Go to https://tube-action-educative.apps.education.fr/w/j7Kcu5SgWKAykMzKuCArAM

See that shortened description shows "Encourager une adolescente ou un adolescent qui se confie, cela implique de lui montrer qu'on est prêt·e à recevoir ce qu'elle ou il a à dire, quoi que ce puisse être, à l'image de cet extrait du film `https://fr.wikip`..."

Whereas full description shows "Encourager une adolescente ou un adolescent qui se confie, cela implique de lui montrer qu'on est prêt·e à recevoir ce qu'elle ou il a à dire, quoi que ce puisse être, à l'image de cet extrait du film [Itinéraire d'un enfant gâté](https://fr.wikipedia.org/wiki/Itin%C3%A9raire_d%27un_enfant_g%C3%A2t%C3%A9)…"

### Describe the expected behavior

Shortened description should not unveiled the url of the hyperlink when cut happens at the corresponding part

### Additional information

* PeerTube instance: apps.education.fr

**Comment by Chocobozzz** [comment]
We need to change how we handle video description and stop truncate them directly from the API when we GET a video. This way the front-end will be able to correctly truncate the description to display without breaking tags.

**Comment by Chocobozzz** [comment]
WIP with https://github.com/Chocobozzz/PeerTube/commit/f713f36bdf6f696ab0fe8a309035a09e864a48ca

We need to wait a few versions before migrating completely to the new API.

**Comment by Chocobozzz** [comment]
We migrated to the new API since V6 :) https://github.com/Chocobozzz/PeerTube/commit/c5f8dc0533153658f46b68a9e214646b41abebfc

**Comment by antistress** [comment]
👍
