### ISSUE TITLE
Embedded live player does not indicate ¨This live has ended", does not autoplay after initial live, and displays confusing replay video

### ISSUE THREAD

**Issue by vijay-howlround** [Chocobozzz/PeerTube#5406]
### Describe the current behavior

When viewing an embedded PeerTube live video player on an external webpage (with autoplay selected when copying/pasting the iframe code), we do not see the helpful message that ¨This live has ended" when the encoder/broadcaster stops sending the RTMP stream to the PeerTube live. (The PeerTube page for the live has this helpful message). 

When the live stream ends, we immediately see a replay icon/button on the PeerTube live embed that does not provide any content when pressed except for a perpetual loading icon, and thus could be confusing or frustrating to users. (If you refresh your browser, you can play something, but it's only the last 57 seconds or so.)

Additionally, if the encoder starts live streaming again, soon after stopping, the embedded live video player does not autoplay this new live stream. The only way for a user to see the new live stream is to manually refresh the webpage where the PeerTube live player is embedded. 

### Steps to reproduce

1. Click "Publish" > Go Live > select Unlisted > select Permanent/recurring live

2. On the live page, click "Share" > Embed > check Autoplay. There is a message overlayed on the video saying: "This live has not started yet." Embed your iframe on an external webpage, or look at the preview provided in the Share pop-up window.

3. Start Stream from OBS Studio.

4. After 20-30 seconds, the live stream begins automatically in embedded live video player iframe.

5. Stop the Stream from OBS Studio, and wait 20-30 seconds to see the embedded live video player iframe provide a replay/icon button in the place of the play/pause button. The "This live has ended" message does not appear. 

6. Re-start Stream from OBS Studio

7. Result: nothing has changed in the embedded live video player iframe even after waiting 20-30 seconds. 

### Describe the expected behavior

- The embedded live video player should indicate: "This live has ended" when the live stream has ended.  After a short moment (perhaps two minutes), the message should revert to: "This live has not started yet." (Or, perhaps, there could be just one message for both pre- and post-event states: "Off-air", for simplicity.)

- The embedded live video player should immediately show its video thumbnail image in order to additionally help viewers understand that there is no live event programming at the moment. That we are "off-air".

- There should not be any replay video present in the embedded live video player when there is no active live stream as this is confusing experience for the viewer. (This could be somewhat related to issue #5113. Though we want recordings, we do want, nor need an immediate public VOD to be available and published.)

- When a live stream re-starts, the embedded live video player should autoplay again. (This is important for the case when a broadcaster's/encoder's local internet stops for a moment in the middle of a live event, and the broadcaster needs to re-start the live stream. If there is no replay video during this interruption, and if autoplay works , then this experience will be much less confusing for viewers.)

### Additional information

* PeerTube instance:
  * URL: https://peertube-us.howlround.com/
  * Version: 4.3.0

* Browser name, version and platforms on which you could reproduce the bug: Firefox for Fedora 106.0.4 (64-bit)

**Comment by Chocobozzz** [comment]
Hi Vijay,

I think I fixed this bug in develop. Can you confirm by creating a live on peertube2.cpy.re?

**Comment by vijay-howlround** [comment]
Hi @Chocobozzz,

**Result:
- Autoplay works on Firefox/Fedora, and the autoplay works again when there is a stop and re-start of the live stream. 
- Autoplay does not work on Chrome/Windows, nor on Firefox/Windows.**

I created a new live on peertube2.cpy.re with the following settings: 

- Unlisted
- This is a permanent/recurring live
- Automatically publish a replay when your live ends

I copied the iframe embed code with "autoplay" selected, and pasted it into a howlround webpage. 

I viewed the live stream simultaneously from:

- Firefox (106.0.4) on Fedora 36 Workstation
- Firefox (106.0.5) on Windows 10 Enterprise
- Chrome (107.0.5304.107) on Windows 10 Enterprise

The other aspects of this issue #5406 are all still present:

- the lack of a message in the iframe embed that says: "This live has ended" (or "off-air")
- the appearance of a replay button and a subsequent perpetual loading animation if you press the replay button
- the confusing replay video of 57-59 seconds

**Comment by ElonVampire** [comment]
收到！

**Comment by vijay-howlround** [comment]
@Chocobozzz: I tried another test: this time with "Autoplay" and "Muted" selected and copied from the Share > Embed > Customization pop-up.

**Result**
- Autoplay with Muted works on Firefox/Windows, Chrome/Windows, Firefox/Fedora, Chrome/Fedora, and the Autoplay (plus Muted) works again when there is a stop and then a re-start of the live stream.

**Comment by Chocobozzz** [comment]
Hi,

Autoplay is restricted on web browsers. Muted videos can be autoplayed, but if there is some sound it will depends on the web browser settings/profile.

**Comment by Chocobozzz** [comment]
Hi,

 * With https://github.com/Chocobozzz/PeerTube/commit/c2419476302b20e9fe3708d7a0a889ae18c95c1b we now correctly "terminate" a live that has ended in embed by hiding the control bar, disabling the player and displaying the live preview
 * With https://github.com/Chocobozzz/PeerTube/commit/59a643aa5cf6775d27dfcc147b19c4537292d53c we "force" autoplay (if enabled in user/instance settings) of the live the user was waiting for. "Force" means the player will try to autoplay the live with sound, and if it doesn't work it will mute the live and retry the process
