### ISSUE TITLE
Redis memory gets full

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5409]
### Describe the current behavior

Since v4.3.0 we've had some issues with redis server going down due to memory outage. It may be related to that the jobs created in bullmq doesn't have any expiry date by default (I'm not sure how node-redis works).

<img width="651" alt="image" src="https://user-images.githubusercontent.com/6680299/201762369-e0c3b6c7-ea26-4b6e-8fb2-ef70d068ee9c.png">

### Steps to reproduce

1. Monitor redis memory over several weeks

### Describe the expected behavior

Either:

* Documentation telling that this should be handled by some custom config/script, which also tells for how long PT needs to keep the jobs to function correctly.

Or:

* Adding expiry key to each job. May be different expiration time based on job type and status.

### Additional information

* PeerTube instance:
  * Version: v4.3.0

**Comment by Chocobozzz** [comment]
> Since v4.3.0 we've had some issues with redis server going down due to memory outage

They have (completed jobs are removed after 2 days).

Can you check in redis what kind of key is taking all this space?

**Comment by Chocobozzz** [comment]
Maybe related and fixed by https://github.com/Chocobozzz/PeerTube/commit/f240fb4bea61484854cecbe711ac20d77c31915d?

**Comment by emansom** [comment]
> But I think I can move to https://docs.bullmq.io/guide/queues/auto-removal-of-jobs And have a small expiration time for parallel broadcast jobs.

Please implement an indefinite retry (with a hold off that increases to a maximum value of e.g. a week on incremental tries as to not cause a DDoS) mechanism as well, otherwise it'd break ActivityPub cross-talk if either host goes down for a while (e.g. long maintenance or hardware failure).

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/c3b21b68b55fa5cb0ee7a23e4316b5466a0448f0

**Comment by Chocobozzz** [comment]
What do you mean by "existing jobs"? Active ones? Completed ones? Waiting?

**Comment by Chocobozzz** [comment]
It's weird https://github.com/Chocobozzz/PeerTube/blob/develop/server/lib/schedulers/remove-old-jobs-scheduler.ts doesn't cleanup your olds jobs :thinking: 

As a side note, https://github.com/Chocobozzz/PeerTube/commit/c3b21b68b55fa5cb0ee7a23e4316b5466a0448f0 will be included in v5, not 4.3.1

**Comment by Chocobozzz** [comment]
Nice catch! I'll update the code to handle more jobs to delete in v5.

**Comment by Chocobozzz** [comment]
This part is only for old jobs (created before v5) because I wasn't sure the new expiration system set using directly bullmq would delete them.
So now we use auto removal via bullmq: https://github.com/Chocobozzz/PeerTube/blob/develop/server/lib/job-queue/job-queue.ts#L523
