### ISSUE TITLE
Undocumented dependency on GNU coreutils

### ISSUE THREAD

**Issue by ddevault** [Chocobozzz/PeerTube#5414]
### Describe the problem

The upgrade scripts depend on GNU coreutils-specific features, rather than relying on the portable subset of features defined by POSIX. This dependency should be documented, or, ideally, the tool usage rewritten to be portable.

**Comment by Chocobozzz** [comment]
Hi,

Dependencies guide is maintained by the community. Don't hesitate to update the document to add core utils dep': https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/dependencies.md
