### ISSUE TITLE
Possibility for plugins to get the listening host and port

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5416]
### Describe the problem to be solved

For the livechat plugin, I need to make API Calls from a XMPP server running on the Peertube server, to the Peertube instance.

For now, I use the public Peertube url to make these requests.

But this has 2 drawbacks:
- requests go through nginx, but they could bypass nginx to directly hit Peertube, as it is on the same server (and use http instead of https for better perf)
- in Docker installations, this can be a problem (the public url is not correctly resolved)

To fix the second point, I added a settings to change the API endpoint url, and you can for example set `http://127.0.0.1:9000`

I want to make this simpler, and I'd like to automatically compute this endpoint.

But for now, plugin manager provide no way to get the local host and port (the values `listen.hostname` and `listen.port` in the config file).

### Describe the solution you would like

I'd like to have listen.host and listen.port somewhere in the helpers provided by Peertube.

For example, by adding it in the result of the backend getServerConfig helper.

Or by adding a new helper here: https://github.com/Chocobozzz/PeerTube/blob/77239b425a8e00822a53c9907415832a473c3eb6/server/lib/plugins/plugin-helpers-builder.ts#L206-L216 . Could be something like that:
```typescript
function buildConfigHelpers () {
  return {
    getWebserverUrl () {
      return WEBSERVER.URL
    },
    getServerListeningOptions {
        return { hostname: WEBSERVER.HOSTNAME, port: WEBSERVER.PORT }
    },
    getServerConfig () {
      return ServerConfigManager.Instance.getServerConfig()
    }
  }
}
```

**Comment by JohnXLivingston** [comment]
Hi @Chocobozzz 
As you already know, there was a stress test last week.
I think this Feature Request will help me to optimize the livechat plugin.
See here (in french, english translation coming soon): https://www.john-livingston.fr/foss/article/plugin-de-tchat-peertube-retour-rapide-sur-un-test-de-montee-en-charge#3_modules_prosody_specifiques

Is it possible to include this in the next release?

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/60bab7b540de3709f3392a0ea964524c13c7e404

**Comment by JohnXLivingston** [comment]
Thanks!
