### ISSUE TITLE
Question: Is there a way to update the channel for a video?

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#542]
* **PeerTube version or URL:** 1.0.0.beta.4
* **Browser name/version:** Firefox Quantum 59.0.2

After creating a new channel, is there a way to update the channel of a video already uploaded?
In the update form, the listbox channel is disabled.

**Comment by Chocobozzz** [comment]
No sorry. See https://github.com/Chocobozzz/PeerTube/issues/349

**Comment by gegeweb** [comment]
OK, I'd looked, but I didn't see the #349.
