### ISSUE TITLE
Unable to generate classic hls

### ISSUE THREAD

**Issue by bil-ash** [Chocobozzz/PeerTube#5421]
### Describe the current behavior

I have webtorrent disabled and the peertube plugin transcoding-profile-debug installed. I want to generate mpeg1 video and mp2 audio(classic hls) in mpegts container (which hls.js can play,so shouldn't be a problem for the player) instead of h.264 and aac(fmp4) in mp4 container-because I want to avoid any future licensing issues and also because I have a use case where the videos will be downloaded and played in low-end hardware(non-browser). So I  use the following config in **transcoding profiles** section 
`{
  "vod": [
    {
      "encoderName": "libavcodec",
      "profileName": "test",
      "outputOptions": ["-c:a","mp2","-b:a", "32k"]
    },
    {
      "encoderName": "libavcodec",
      "profileName": "test",
      "outputOptions": ["-c:v","mpeg1video","-q", "25"]
    }
  ],
  "live": []
}`
and the following in **Encoders priorities** section
`{
  "vod": [
    {
      "encoderName": "libavcodec",
      "streamType": "audio",
      "priority": 1000
    },
   {
      "encoderName": "libavcodec",
      "streamType": "video",
      "priority": 1000
    }
  ],
  "live": [ ]
}`

After updating the plugin settings and running **systemctl restart peertube** on  my vps, peertube still generates mp4 container with h.264 video and aac audio on transcoding.  I believe there is some problem with my configuration for transcoding-profile-debug but in that case peertube should give an error and/or not do the transcoding at all. But in my case the transcoding happens and h.264 video and aac audio get generated. Someone please provide me the appropriate config to generate mpegts file(classic hls) with mpeg1 video and mp2 audio.

### Steps to reproduce

1.Mentioned above
2.
3.

### Describe the expected behavior

Mentioned above

### Additional information

* PeerTube instance:
  * URL:
  * Version:4.3.0
  * NodeJS version:18.x
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Please use [the forum](https://framacolibri.org/c/peertube/38) for questions/help on peertube plugins. We'll also need peertube debug logs to see what happens in transcoding job.

**Comment by mfu-mcosys** [comment]
Got the same problem, if i change the related hls flags in the ffmpeg-vod.js, there are errors from ffprobe-utils.js/tslib.js.

Is there there is a "simple" way to use mpegts? At the end, i just want to use the peertube-files in kodi with inputstream.adaptive. :)
