### ISSUE TITLE
 Add the video license information on PeerTube

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#5424]
### Describe the problem to be solved

One of the problems with video is knowing whether certain content can be used or not. What I add here is a license link that says if the video is copyrighted or not.

#### concept
![image](https://user-images.githubusercontent.com/111701513/203382504-d23627e9-4993-4a99-84fc-db814e1b2072.png)

**image-description:** As we can see in the image there is an area where I can choose the license of my video like [CC-BY-SA-4.0](https://creativecommons.org/licenses/)

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I don't understand because the licence can already be filled in video edition form and displayed below the video

![screen_2022-11-23-08:32:02](https://user-images.githubusercontent.com/5180488/203492651-8d2f9c82-ce05-415d-ba5c-e15f7a87dde2.png)
