### ISSUE TITLE
improving the ui/ux  on PeerTube

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#5427]
### Describe the problem to be solved
I would like to contribute to this project. Initially, I thought of improving the ui/ux part. I initially thought about a position for the icons. The position of the icons improves the usability of a certain software or web product/service. I find it a problem not to have icons in easily accessible places. For this reason, I requested here for resolution or discussion whether the icons are in an easily accessible position.

### Describe the solution you would like
The solution to solve the above problem is to add icons in more accessible places like the menu below the video, as we can see in these images.

#### 1. concept(ui/ux): "button to report"
<img src="https://user-images.githubusercontent.com/111701513/203642283-53ecdf77-01b6-4694-bbd1-cb3ee96eaf12.png" width="700px"/>

**image-description:** As we can see in the image, there is a button where the user can report the content of the video or video. Any reported video must be analyzed or reported by all the people who watched the video - or even, it must notify who is responsible for having made, developed or created it. Either you must notify future users or the responsible company or organization, in this case who hosts PeerTube. If the video is reported, it will not be accessible to other users. This can be done with the consent of one or more users on PeerTube. 

#### 2. concept(ui/ux): "indicative classification" or "age rating" or "target audience" 
<img src="https://user-images.githubusercontent.com/111701513/203640588-2dc32e82-1619-43a6-ba35-d1f64c915108.png" width="700px"/>

**image-description:** As we can see in the image, we have the indicative classification of the video as ``L``, which means libre in spanish or "free" in english, that is, it is an accessible content for anyone. Depending on the indicative classification of the video, certain contents cannot be viewed by other people. Even if a video contains material that is "L" for "libre" or "free" in English and does not have that type of content because it has been manipulated in some way. User interaction or peer review can report the video even without a report button being called. *That is, people may no longer want to see the video, or they may not be interested in posting, sharing, or storing the video. That's because the video doesn't have the target audience button or indicative classification button or age rating button too*

**Comment by Chocobozzz** [comment]
Closing this inactive discussion. Don't hesitate to comment if you want to reopen it.
