### ISSUE TITLE
Show average moderation-time statistics in “Find instance” tools 

### ISSUE THREAD

**Issue by 1br0wn** [Chocobozzz/PeerTube#5433]
### Describe the problem to be solved

I signed up to my first PeerTube instance on Friday morning and uploaded a video (an academic seminar I gave on Thursday). The instance (quite understandably) has publication-after-moderation, but several days later this still hasn’t happened, despite a follow-up e-mail to the instance admins yesterday. (No other feedback either). If I had seen on the “find instance” JoinPeerTube site I might have to wait days (or weeks) for moderation, I would have chosen a different instance. Thanks! (I read through the 17 pages of current requests and couldn’t see anything related.)

### Describe the solution you would like

Content creators should be able to choose an instance to sign up to with information on how long moderation of a new video is likely to take.

**Comment by Chocobozzz** [comment]
This has been implemented on JPT for instances > v6.0 for account approval, which should be enough too find an instance with reactive moderators/admins :)

![screen_2024-08-02-15_01_55](https://github.com/user-attachments/assets/905dec0b-7ccc-4d9e-abc4-0b9b964f339e)

**Comment by 1br0wn** [comment]
Thanks!
