### ISSUE TITLE
Stats: Can't see the names of the countries that viewed the live if more than 10 countries viewed the live.

### ISSUE THREAD

**Issue by vijay-howlround** [Chocobozzz/PeerTube#5435]
### Describe the current behavior

For a live that had viewers from 22 countries, we can only see 10 of those countries listed in the "Stats" analytics page for that live event. 

### Steps to reproduce

1. Produce a live that has viewers from more than 10 countries. 
2. Visit the "Stats" page for that live. 
3. Compare the number of countries listed in the dashboard box versus in the names of the countries listed in the bar graph. 

### Describe the expected behavior

See all the names of the countries that viewed the live. 

### Additional information

* PeerTube instance:
  * URL: https://peertube-eu.howlround.com/stats/videos/5110e2c7-a174-44bd-adec-ac580bdc9a31
  * Version: 4.3.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox/Windows
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks, I removed the limit in https://github.com/Chocobozzz/PeerTube/commit/04509c43254dc232c61681ac4bb98e09fd126115
