### ISSUE TITLE
Rebroadcast livestream from YouTube if a channel is streaming

### ISSUE THREAD

**Issue by emansom** [Chocobozzz/PeerTube#5437]
### Describe the problem to be solved

[`yt-dlp`](https://github.com/yt-dlp/yt-dlp) has gained support to download livestreams from their start in https://github.com/yt-dlp/yt-dlp/commit/4d37720a0c5f1c9c4768ea20b0f943277f55bc12 and https://github.com/yt-dlp/yt-dlp/commit/adbc4ec4bbfbe57842049cf9194384480f534859 plus a bunch of other commits that refine the feature.

It has become a possibility to download the livestream that's broadcasting on a channel from the start and rebroadcast it.

### Describe the solution you would like

I would like PeerTube to support this rebroadcasting feature.

When paired with #5436 it could drastically reduce the total time to publication, for livestreams from other platforms.

**Comment by pukkandan** [comment]
> [`yt-dlp`](https://github.com/yt-dlp/yt-dlp) has gained support to download livestreams from their start

The feature is still buggy under certain circumstances. You may want to look into using https://github.com/Kethsar/ytarchive instead while we refine the feature

**Comment by Chocobozzz** [comment]
Hello,

Thanks for the issue but re-broadcasting videos/lives of external platforms is out of the scope of PeerTube for now.
