### ISSUE TITLE
Remote Tools on ubuntu 22

### ISSUE THREAD

**Issue by ncamacho97** [Chocobozzz/PeerTube#5438]
### Describe the problem

NOCLIENT=1 yarn install --pure-lockfile
Usage: yarn [options]

yarn: error: no such option: --pure-lockfile

**Comment by Chocobozzz** [comment]
Follow the guide: https://docs.joinpeertube.org/dependencies?id=debian-ubuntu-and-derivatives

**Comment by ncamacho97** [comment]
i did and i dont work
