### ISSUE TITLE
Private videos are no longer accessible on iOS with v5.0.0-rc.1

### ISSUE THREAD

**Issue by raphgilles** [Chocobozzz/PeerTube#5439]
### Describe the current behavior

ENGLISH :
With v5.0.0-rc1 we generate a key to secure private videos. This is a great step forward for security!

However, they are no longer playable on iOS (Firefox & Safari). Everything works perfectly fine with unlisted and public videos. It works also on computer (macOS, Windows & Linux) and Android.
I tried on another instance than mine in v5.0.0-rc1 (https://peervideo.ru/) and got the same result.
There is no error in Nginx.

Here are two captures. The first on iOS the other on Android.

FRENCH :
Avec la v5.0.0-rc1 nous générons une clé pour sécuriser les vidéos privées. C'est une superbe avancée pour la sécurisation !

Cependant, elles ne sont plus lisibles sur iOS (Firefox & Safari). Tout fonctionne parfaitement bien avec les vidéos non-repertoriées et publiques. Ça fonctionne aussi sur ordinateur (macOS, Windows & Linux) et Android.
J'ai essayé sur une autre instance que la mienne en v5.0.0-rc1 (https://peervideo.ru/) et j'ai obtenu le même résultat.
Il n'y a pas d'erreur dans Nginx.

Voici deux captures. La première sur iOS l'autre sur Android.

![2022-12-01 23 03 30](https://user-images.githubusercontent.com/49836486/205168659-513442ed-c1b3-41e1-9936-3575393856f6.jpg) ![2022-12-01 23 03 39](https://user-images.githubusercontent.com/49836486/205168687-3194b74c-65ee-4c0c-8a1f-4357eb9d0db3.jpg)

### Steps to reproduce

1. Uploader une vidéo en privée
2. Essayer de la lire sur iOS

### Additional information

* PeerTube instance: 
  * URL: https://peertube.stream 
  * Version: 5.0.0-rc.1
  * NodeJS version: v16.8.0
  * Ffmpeg version: 4.4.3

* Browser name, version and platforms on which you could reproduce the bug: Firefox iOS, Safari iOS
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by kaamui** [comment]
Ta gueule version métal :smile: 

ENGLISH : Could it be related to #5434 (e.g the issue is more related to encoding differences than visibility differences ?

FRENCH : c'est peut-être plus lié à l'encodage de la vidéo qu'à sa visibilité ? cf. #5434

**Comment by raphgilles** [comment]
FR : Dès qu’on passe la vidéo en non-listée ou publique ça ne pose plus aucun problème. Sachant qu’elles sont toutes retranscodées/standardisées par PeerTube via FFmpeg.

EN : When we switch the video to unlisted or public, it is no longer a problem. Knowing that they are all retranscoded/standardized by PeerTube via FFmpeg.

**Comment by Chocobozzz** [comment]
Thanks for the issue, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/71e3e879c0616882ee82a0e44f8c2e5ee9698a3e
