### ISSUE TITLE
Comments and videos from other instances appearing locally without follow

### ISSUE THREAD

**Issue by EBendinelli** [Chocobozzz/PeerTube#5440]
### Describe the current behavior

Hi there, I might be missing something obvious but right now I can't see it! [Privacy International's instance](https://media.privacyinternational.org) is currently not following any other instances or followed by anyone (data protection measure for now).

![image](https://user-images.githubusercontent.com/12803082/205321877-e88611af-6fd3-444c-9345-dfd71fcf6692.png)

We don't allow registrations and only have approved local users. 

However we just noticed after migration to a new server that we had thousands of comments from users from other instances on videos from other instances. See screenshot:

![image](https://user-images.githubusercontent.com/12803082/205321361-1be0ea52-7c6a-44e0-9b53-285e405a095d.png)

The videos in question can be accessed if you are logged in on our instance but will give an error and offer to redirect if you try to access them as a guest (e.g.: https://media.privacyinternational.org/w/35082d3d-d52c-43b4-bff4-b907c09be639;threadId=5315). Videos are coming from multiple instances.

![image](https://user-images.githubusercontent.com/12803082/205323064-be0a9145-24db-4baa-999d-dba4d40d7930.png)
_Video viewed from a logged account on media.privacyinternational.org_

Deleting a comment will make it disappear locally (i.e. when looking at the video from our instance) but not on the origin instance (expected). We are not being notified of new comments.

While this is not a major issue at the moment for us as none of this can be accessed publicly it does pose a problem as it means we are unwillingly collecting personal data in the form of comments on our instance, something we are actively trying to avoid at this stage.

Any advice appreciated!

### Steps to reproduce

1. Have an instance with no follower and following nobody + closed registration
2. Run said instance for a some time
3. Look a the comments

### Describe the expected behavior

Only videos from our instance (and instance we follow which is currently zero) should be accessible from our instance. Same with comments.

### Additional information

* PeerTube instance:
  * URL: https://media.privacyinternational.org/
  * Version: 4.3.1
  * NodeJS version: v16.17.1
  * Ffmpeg version: 5.0.1

**Comment by EBendinelli** [comment]
Thanks a lot for this response, this sort of makes sense but I'm still confused as to why these comments would show up in the first place. 

I understand users on our instance can access videos and comments outside the federation and I will disable this option but I don't get why those videos would appear in the first place given that we haven't actively fetched them? 

We only have 3 users (and only actively use one), all admins and owned by us and as far as I'm aware nobody has actively searched for these videos to watch them from our instance. So why would the comments appear and the videos be accessible? I've done some testing and indeed, if I search for a video from another instance while being logged in then the comments posted under that video will show up in the comment moderation page. But I'm fairly certain nobody had ever done that on our instance before (for one thing most of the videos fetched are in french and I'm the only french speaking person with access). 

Any suggestion as to how this could have happened? Some of the videos are fairly recent and we haven't changed ```search.remote_uri.anonymous``` recently (otherwise it would have been a good explanation).

I'm also confused as to why the search says "in this instance's network" since I understand this as "instances followed by this instance" but it seems that it means more than that.

![image](https://user-images.githubusercontent.com/12803082/205602752-7656e83d-2a60-41bb-8290-bb004be6ea63.png)

Thanks

**Comment by Chocobozzz** [comment]
PeerTube can fetch videos of remote actors that commented one of your videos for example.

> I'm also confused as to why the search says "in this instance's network" since I understand this as "instances followed by this instance" but it seems that it means more than that.

It means instances your instance follows.

**Comment by EBendinelli** [comment]
> PeerTube can fetch videos of remote actors that commented one of your videos for example.

Sorry to keep asking questions, but something still doesn't sound quite right, cCould you explain how that works? We only have 4 comments (!) coming from 3 different instances and most of the videos fetched don't come from any of these 3:

![image](https://user-images.githubusercontent.com/12803082/205624451-89f7b6b0-f97c-49fd-ba22-fa73535e27d9.png)

> It means instances your instance follows.

But we don't follow any instance as stated in the first post. And yet I can fetch a video from another instance as illustrated in my previous reply. So something's off right?

**Comment by Chocobozzz** [comment]
ActivityPub uses the "follow your nose" approach. When PeerTube resolves a remote actor, it may add in the DB its videos, comments, likes etc.
PeerTube does this kind of thing when you resolve a remote content using its URL in the search bar.

We may have reduced the amount of content fetched in recent releases.

> But we don't follow any instance as stated in the first post

You're logged in so you're able to search remote content using the URL directly: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L728

**Comment by EBendinelli** [comment]
I've disabled this option and it seems I can still fetch remote content in the search bar:

```
search:
  # Add ability to fetch remote videos/actors by their URI, that may not be federated with your instance
  # If enabled, the associated group will be able to "escape" from the instance follows
  # That means they will be able to follow channels, watch videos, list videos of non followed instances
  remote_uri:
    users: false
    anonymous: false
```

![image](https://user-images.githubusercontent.com/12803082/207088593-6bc6eb54-97e5-4938-a23a-bb0066203eb0.png)

This videos hadn't not been fetched previously.

**Comment by Chocobozzz** [comment]
You need to disable it from the web interface: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L358
