### ISSUE TITLE
SELinux support, assigning the appropriate file labels

### ISSUE THREAD

**Issue by emansom** [Chocobozzz/PeerTube#5442]
### Describe the problem to be solved

On a securely configured RHEL derivative (_like [Rocky](https://rockylinux.org/)_), PeerTube currently does not play nice with SELinux.

One needs to set up some custom rules on the system to let it punch a hole through SELinux access control.

### Describe the solution you would like

PeerTube detecting if it's being run (_or explicitly configured for, in case detection isn't possible, e.g. for container environments_) in a SELinux enabled environment, and assigning the appropriate `httpd_sys_content_t` file label on all files shared with the web server created in the storage directory.

**Comment by Chocobozzz** [comment]
Hello,

Unfortunately we don't have enough resources and knowledge to support SELinux for PeerTube at the time of writing.

**Comment by emansom** [comment]
@Chocobozzz Would you accept a PR that implements this behind a flag?

SELinux is kind of a prerequisite in any government and/or ISO 27002 certified business entity.

**Comment by Chocobozzz** [comment]
Yes I think so if it doesn't add too much complexity!
