### ISSUE TITLE
Wrong TS type for loadByIdOrUUID and loadByUrl?

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5446]
### Describe the current behavior

I'm not sure, but I think there are errors in these TS types:

https://github.com/Chocobozzz/PeerTube/blob/d3340f242cb8b9b399123665a56736449686276b/server/types/plugins/register-server-option.model.ts#L36-L37

```typescript
    loadByUrl: (url: string) => Promise<MVideoThumbnail>
    loadByIdOrUUID: (id: number | string) => Promise<MVideoThumbnail>
```

I think that the correct return type should be `VideoModel`:

https://github.com/Chocobozzz/PeerTube/blob/d3340f242cb8b9b399123665a56736449686276b/server/lib/plugins/plugin-helpers-builder.ts#L82-L97

```typescript
    loadByUrl: (url: string) => {
      return VideoModel.loadByUrl(url)
    },

    loadByIdOrUUID: (id: number | string) => {
      return VideoModel.load(id)
    },

    removeVideo: (id: number) => {
      return sequelizeTypescript.transaction(async t => {
        const video = await VideoModel.loadFull(id, t)

        await video.destroy({ transaction: t })
      })
    },

```

Because of this, I have problems using @peertubes/peertube-types.

Note: there might be other methods with wrong types, I did not check everything.

### Additional information

* PeerTube instance:
  * Version: 4.2.2, 4.3.0

**Comment by Chocobozzz** [comment]
Can you describe why you consider this as an error?

**Comment by JohnXLivingston** [comment]
Hum, I think I messed up, i was probably too tired. Closing the issue. Sorry for the noise.
