### ISSUE TITLE
Automatically transcribe videos

### ISSUE THREAD

**Issue by JediMaster25** [Chocobozzz/PeerTube#5449]
### Describe the problem to be solved

I can't search for videos using a quote I remember.

### Describe the solution you would like

Using Whisper AI all videos could be transcribed automatically, and the transcription made crawlable.

**Comment by Chocobozzz** [comment]
Thanks for reporting this issue, but this is a duplicate of https://github.com/Chocobozzz/PeerTube/issues/4849

There is also a plugin to automatically translate videos https://gitlab.com/apps_education/peertube/plugin-transcription
