### ISSUE TITLE
Add multiple LDAP sources for peertube-plugin-auth-ldap

### ISSUE THREAD

**Issue by Stormkoopa** [Chocobozzz/PeerTube#5451]
### Describe the problem to be solved

I would like to provide multiple sources for LDAP authentification since in our structure there is more than one domain where users want to enter our peertube instance from. Right now only users from one single domain can authenticate.

### Describe the solution you would like

Add functionality to specify multiple LDAP sources to authenticate against.

**Comment by Chocobozzz** [comment]
Hello,

Please open the issue on the ldap plugin repository: https://framagit.org/framasoft/peertube/official-plugins
