### ISSUE TITLE
Upgrade failure

### ISSUE THREAD

**Issue by kdmiller45** [Chocobozzz/PeerTube#5454]
### Describe the problem

upgraded from 4.3.1 to 5.1.1 rc1 and got a 502 bad gateway

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

keith

### Additional information

* PeerTube instance URL: worldofvids.com
* PeerTube version: 4.3.1
* NodeJS version: 14.21.1
* Ffmpeg version: 4.3.2
* Redis version: 4.0.9
* PostgreSQL version:

I perform these commands

$ cd /var/www/peertube/peertube-latest/scripts && sudo -H -u peertube ./upgrade.sh
$ sudo systemctl restart peertube # Or use your OS command to restart PeerTube if you don't use systemd

**Comment by Chocobozzz** [comment]
Hello,

You need to follow the important notes: https://github.com/Chocobozzz/PeerTube/blob/develop/CHANGELOG.md#v500-rc1

PeerTube logs can also be useful

**Comment by revpriest** [comment]
~/config/production.yaml seems to have a
secrets:
  peertube: ''
  
 option. Could be something to do with that I guess? That already has a value in it though, presumably created with openssl during install to judge by the comment.
 
 Is it saying I have to create a new one? Just a new random number from openssl?
 
 Doesn't seem likely that would fix a "property not defined" type error though.

**Comment by revpriest** [comment]
Ah, here we go.

Apparently the file /var/www/peertube/config/production.yaml needs to be changed.

There used to be:
`
upload_acl: 'public-read'
`
But now we have to separate ones, for private and public videos, so we need to remove that and define:

```
upload_acl:
  public: 'public-read'
  private: 'private'
```
  
  The migration then worked, which means the restart worked.
  
  The documentation really needs improving in that area. 
  
  Thanks.

**Comment by Chocobozzz** [comment]
I improved the changelog!

**Comment by mro** [comment]
after config change, reboot or rerun upgrade.sh?
