### ISSUE TITLE
Unable to update a plugin in beta version to its stable release

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5456]
### Describe the current behavior

Since Peertube v5.0.0, it is possible to install plugin beta version (see https://github.com/Chocobozzz/PeerTube/issues/4600 ).

But when the stable release is here, Peertube won't propose to update. See this screenshot:
![image](https://user-images.githubusercontent.com/38844060/207272206-b4a0e180-9b4f-4173-a7a5-eddd2538e8af.png)

The v6.0.0 of the plugin is know by this Peertube instance:
```
peertube_prod=> select "latestVersion" from "plugin" where "name" = 'livechat';
 latestVersion 
---------------
 6.0.0
(1 ligne)
```

The bug comes from the `compareSemVer` function:
https://github.com/Chocobozzz/PeerTube/blob/develop/shared/core-utils/common/version.ts

### Steps to reproduce

1. Install a plugin beta version (for example livechat v6.0.0-beta.2)
2. Set the latestVersion for the plugin to its stable release (6.0.0)
3. Go to the plugin list: there is no update button

### Additional information

* PeerTube instance:
  * Version: 5.0.0

**Comment by Chocobozzz** [comment]
Thanks for the issue! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/6e06694fd6acab185432bccf57bd5c9c3b68f218
