### ISSUE TITLE
Notes on upgrade documentation

### ISSUE THREAD

**Issue by kdmiller45** [Chocobozzz/PeerTube#5457]
### Describe the problem
after attempted upgrade to 5.0.0 get 502 Bad Gateway

I performed this command
Important You need to manually execute a migration script after your upgrade to migrate private/internal video files:

    Classic installation: cd /var/www/peertube/peertube-latest && sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production node dist/scripts/migrations/peertube-5.0.js

I generated the secret using 
openssl rand -hex 32

NOTE: this config file Production.yaml is located in /var/www/peertube/peertube-latest/config should this actually be in /var/www/peertube/config

You must update your nginx configuration 
Location: /etc/nginx/
   Which file

We introduced a new location for plugin websocket routes
We introduced a new location for private videos files

Where is the new location for websocket
Where is the new location for private videos files

object_storage.upload_acl is now a parent key that you must update:  where is object_storage.upload_acl located and how is the parent key generated 

### Additional information

* PeerTube instance URL: worldofvids.comn
* PeerTube version: tryijng to upgrade to 5.0.0
* NodeJS version: 14.21.1
* Ffmpeg version: 4.3.2
* Redis version: 4.0.9
* PostgreSQL version: 10.22

**Comment by Utopiah** [comment]
IMHO https://github.com/Chocobozzz/PeerTube/releases/tag/v5.0.0 at least should be mentioned in https://docs.joinpeertube.org/install-docker?id=upgrade and wherever else needed. I assume most Docker users will "just" do as is written which unfortunately, at least from 4.x to 5.x I believe will fail due to the new secret field.

**Comment by Chocobozzz** [comment]
I added a note in docker upgrade section in https://github.com/Chocobozzz/PeerTube/commit/6905da7ae98d9e7867d1b1b2186f2a339e5fd84b
