### ISSUE TITLE
Support assets, video CDN

### ISSUE THREAD

**Issue by RinCat** [Chocobozzz/PeerTube#5460]
### Describe the problem to be solved

Most common servers/VPS have only 1Gb network port, which usually only support up to 100-200 users watching 1080p at the same time. Higher resolutions and multiple simultaneous users live significantly reduce the number of simultaneous plays available further. Assuming they can use the full 1Gb port, most VPS are shared. The newly supported object storage alleviates this problem in some ways, but not for users who do not use object storage.

### Describe the solution you would like

Support something like 
`assets_base_url` that replace `https://example.com/client/assets` to `https://assets.example.com/client/assets`
`video_base_url` that replace `https://example.com/static/streaming-playlists/` to `https://cdn.example.com/static/streaming-playlists/`

Just like how the `base_url` works in the `object_storage`. The users could use round-robin DNS and/or GeoDNS to do load balancing on multiple servers and reduce the load on the main server.
Unlike the object storage, the files should accessible use current `https://example.com/client/assets` and `https://example.com/static/streaming-playlists/`, so the other CDN/cache servers can get data from the main server to distribute.

Further, some resources (like `/client/en-US/runtime.c6a074343c198fd0.js`) are not under assets, maybe move them to assets or put the whole `/clients` under `assets_base_url`.

This should also works for the live streaming. The CDN / cache server should only cache the `.m3u8` for 1s.

**Comment by emansom** [comment]
Great feature request!

It should also allow multiple CDNs to be defined and PeerTube handing one to each viewer based on occupancy buckets with max slots per CDN configurable.

The viewer internally then sends more details during it's viewer ping on which CDN is accessed, and the occupancy bucket data is updated based on it.

**Comment by RinCat** [comment]
> It should also allow multiple CDNs to be defined and PeerTube handing one to each viewer based on occupancy buckets with max slots per CDN configurable.

If multiple CDNs exists, the client could try to pull data from the top 3 fastest instead of being bound to one.

**Comment by Chocobozzz** [comment]
Hello,

PeerTube already supports CDN where your domain name points to the CDN and the CDN serves PeerTube files from your server :)

**Comment by RinCat** [comment]
Hi @Chocobozzz , that's not the case. Route all traffic thought CDN / edge server is different than route only static video files. The latter can be deployed on servers that are not highly trusted, not even under the same domain name. These servers are also invulnerable to attack because they do not participate in any logical processing and only cache and forward static files.
