### ISSUE TITLE
Support minimized redundancy server

### ISSUE THREAD

**Issue by RinCat** [Chocobozzz/PeerTube#5462]
### Describe the problem to be solved

The current instance of redundancy is essentially the same as a full instance. In my opinion this is completely unnecessary and adds more maintenance costs.

### Describe the solution you would like

As a supplement of https://github.com/Chocobozzz/PeerTube/issues/5460 

A minimized redundancy server should:

1. Statically configured in `production.yaml`.
2. No UI and login, only the root user and a very long random password to reduce attack surface. Trying to access the UI or login should return 404 and 403.
3. Does not use a persistent database, but can use redis. All data should be pullable from the main server, and unknown data (perhaps deleted from the main server) can be cleaned up without relying on database tracking.

This makes all components static, except for reading and writing to `/storage`. Users do not need to worry about the maintenance and updating of this barely used database. Especially major version updates require manual operations.

**Comment by emansom** [comment]
This would be amazing to spread bandwidth. 👍🏻

**Comment by Chocobozzz** [comment]
Hello,

Thanks for the issue but unfortunately Framasoft doesn't have enough resources to develop this "light" tool.

**Comment by RinCat** [comment]
I don't think it needs to be a separate tool, it could be based entirely on the current code but with some components turned off depending on the startup configuration. If you're interested I could probably spend some time looking into it, but I don't write much nodejs.
