### ISSUE TITLE
Import videos and audio from LBRY

### ISSUE THREAD

**Issue by trymeouteh** [Chocobozzz/PeerTube#5463]
### Describe the problem to be solved

The ability to import your videos and audios from your LBRY channel.

### Describe the solution you would like

A setting to allow users to import videos from your LBRY channel in a decentralised way (Not using odysee or any librarian instance, directly from the LBRY network)

**Comment by Chocobozzz** [comment]
Hi,

Thanks for this issue but we don't plan to support other import method than using yt-dlp/youtube-dl. So you may open an issue on these tools instead.
