### ISSUE TITLE
Suggestion for upgrade/Install instructions

### ISSUE THREAD

**Issue by kdmiller45** [Chocobozzz/PeerTube#5467]
### Describe the problem

Suggest you rewrite your upgrade/Install instructions so that you don't send people to other instructions with links and then they  have to go back to the original setup, I am at 4.2.2 and have tried multiple times to upgrade to 5.0.0 but have not been successful
I will probably just stay where I'm at until the documentation is more of a step by step instead of jumping around. 

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by Chocobozzz** [comment]
Hello,

You can find detailed upgrade steps on https://docs.joinpeertube.org/install-any-os?id=upgrade

If you have difficulties with a particular step or an error after the upgrade please explain/paste it.
