### ISSUE TITLE
Issue with trying to access private/internal video from an authorized user

### ISSUE THREAD

**Issue by Kinuseka** [Chocobozzz/PeerTube#5468]
### Describe the current behavior

Playing the video from CDN proxy works fine when the video becomes privated/internalized the cdn link no longer works (As expected)

When the video is privated, the main server now becomes a proxy for the video so that only AUTHORIZED users can access it.
The issue now comes from here, it seems to load the `.json` metadata and `.m3u8` pretty fine however the video FAILS to load.

Upon checking the logs from the server we can see a 
```log
Dec 17 05:21:53 ip-x peertube[51078]: [tube.kinu.ml:443] 2022-12-17 05:21:53.875 error: Client log: Segment https://tube.kinu.ml/object-storage-proxy/streaming-playlists/hls/private/416c7067-1182-4f7f-9083-cd18c2dcbccb/445d813e-d4e3-4f0c-8722-1756249c14d8-master.m3u8+V0+0 error. {
Dec 17 05:21:53 ip-x peertube[51078]:   "username": "user",
Dec 17 05:21:53 ip-x peertube[51078]:   "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
Dec 17 05:21:53 ip-x peertube[51078]:   "stackTrace": "Hashes does not correspond for segment 4ab785a9-70e8-4dde-b512-d19896d3baa2-360-fragmented.mp4/1387-111721(expected: a629d0843e3495d7200c37a5f2371168829ae9af88d331effad2eb917386673f instead of 76cdec31e124134e5b971b6da17fb5f0a5fab7f4c949dbab0f8f5b71e76308c1)\nError: Hashes does not correspond for segment 4ab785a9-70e8-4dde-b512-d19896d3baa2-360-fragmented.mp4/1387-111721(expected: a629d0843e3495d7200c37a5f2371168829ae9af88d331effad2eb917386673f instead of 76cdec31e124134e5b971b6da17fb5f0a5fab7f4c949dbab0f8f5b71e76308c1)\n    at Object.<anonymous> (https://tube.kinu.ml/client/en-US/5474.a421789c05c17b8f.js:1:151865)\n    at Generator.next (<anonymous>)\n    at e (https://tube.kinu.ml/client/en-US/main.3f1de96c17edc7ce.js:1:679789)\n    at m (https://tube.kinu.ml/client/en-US/main.3f1de96c17edc7ce.js:1:679991)\n    at i.invoke (https://tube.kinu.ml/client/en-US/polyfills.49fdee6c496b7b63.js:1:68456)\n    at ft.run (https://tube.kinu.ml/client/en-US/polyfills.49fdee6c496b7b63.js:1:63744)\n    at https://tube.kinu.ml/client/en-US/polyfills.49fdee6c496b7b63.js:1:78751\n    at i.invokeTask (https://tube.kinu.ml/client/en-US/polyfills.49fdee6c496b7b63.js:1:69076)\n    at ft.runTask (https://tube.kinu.ml/client/en-US/polyfills.49fdee6c496b7b63.js:1:64384)\n    at V (https://tube.kinu.ml/client/en-US/polyfills.49fdee6c496b7b63.js:1:71119)",
Dec 17 05:21:53 ip-x peertube[51078]:   "url": "https://tube.kinu.ml/w/95z2EQygJ3P9rLjv54FL3x"
Dec 17 05:21:53 ip-x peertube[51078]: }
```
Seems like that above is the main cause of the error. 

If you open DevTools while viewing the video you can see the video being downloaded millions of times and wrecks havoc in my bandwidth (It seems to be recursively downloading). Not sure what causes this, feel free to check.

What I have tried
✔ Removed old pre 5.0.0 nginx config, replaced with the new 5.0.0 nginx config
✔ Updated my peertube `production.yaml` in accordance to the **Important Notes** on releases page.
✔ Video does indeed work, when set to public (via the CDN network)

### Steps to reproduce

**Specific reproduction**

1. Install a 4.3.0 instance
2. Enable Object storage
3. Update to 5.0.0 
4. Follow Important notes (From releases) and Upgrade guide (on peertube documentation)
5. upload a video
6. set it to private/internal
7. play.

**Test my issue**
1.  go to https://tube.kinu.ml/w/95z2EQygJ3P9rLjv54FL3x (requires an account first)
2.  play the video (You can also open devTools and monitor networking tab)
--

### Describe the expected behavior

Should play the video as normal

### Additional information

* PeerTube instance:
  * URL: https://tube.kinu.m;
  * Version: 5.0.0 (recent release)
  * NodeJS version: 14.21.1
  * Ffmpeg version: 4.4.2-0ubuntu0.22.04.1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Kinuseka** [comment]
New information discovered. It seems like the `/object-storage-proxy/ ` is only returning http code `200` and not `206` even though `bytes` header was present. This now explains the recursive downloading.

**Comment by Chocobozzz** [comment]
Hello,

Ensure services in front of your peertube server correctly forward the `range` header.

**Comment by Kinuseka** [comment]
# 
Hi, thanks for the response. I was really sure it was a misconfiguration somewhere in nginx or peertube, I looked everywhere including the source code. Hit a roadblock. When you mentioned `forward range header` I had a sudden realization that *Cloudflare* might not actually be forwarding these headers correctly, since they are a reverse proxy after all. I did my research and indeed that cloudflare has issues with forwarding `bytes range headers` (related forums: [here](https://community.cloudflare.com/t/accept-ranges-and-content-length-headers-not-forwarded-by-cloudflare/41445) and [here](https://community.cloudflare.com/t/mp4-wont-load-in-safari-using-cloudflare/10587/16)). 

## Problem
But the issue is not because cloudflare does not support `range headers` but rather because peertube does not correctly return the correct http code. For a partial content Cf (short for cloudflare) must expect http code 206 (partial content) from the webserver other wise the internal cache from cloudflare causes overlapping. ["For a legit "Range" request response, your webserver need to return status code '206'."
](https://stackoverflow.com/questions/27712778/video-plays-in-other-browsers-but-not-safari#:~:text=For%20a%20legit%20%22Range%22%20request%20response%2C%20your%20webserve%20need%20to%20return%20status%20code%20%22206%22.)
![Untitled](https://user-images.githubusercontent.com/66762783/208389681-e8f3ffbb-d1bb-454b-9c2a-0abea82227cb.png)


# Solution
To mitigate this issue, we simply have to bypass cloudflare completely by using page rules as shown here:
![image](https://user-images.githubusercontent.com/66762783/208398046-62b7f0c6-3a52-4889-8ed1-e419a81975d1.png)

This makes it so that the Client communicates to the server directly.


### 1.) How come the CDN does not request to the origin for a new content if it detects the range file value has changed per request. 
**My Assumption:** It may be because cloudflare is trying to mitigate origin load by mitigating invalid requests, for example if a client sends `range` headers, then the server should return 206. However when the server returns 200, the cloudflare cache thinks the origin server has no `Partial Content` support so it tries to send the same data over and over again from the same request it did first.

**Comment by Chocobozzz** [comment]
Thanks for the details! I fixed this issue in https://github.com/Chocobozzz/PeerTube/commit/57e11a20f12c69927e5739ecf541ed340934ff90
