### ISSUE TITLE
Dumping and loading Postgresql without old server

### ISSUE THREAD

**Issue by sortedcord** [Chocobozzz/PeerTube#5469]
### Describe the problem

Hi, this is a follow-up to #5455 . I believe my OS installation was somehow broken which is why I having issues with ffmpeg, etc. So I decided to reinstall Ubuntu Server and looked up the instance migration guide. I was able to transfer all the files in the storage folder, however I cannot load the database dump since I did not dump it before I replaced my installation. I do have all the files though...

Is it possible to load the previous database If I no longer have the previous installation active?

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by Kinuseka** [comment]
Normally peertube does its own routine database backups found on `/var/www/peertube/backup`

If you did not manage to dump the database before reinstallation then it might be lost forever.

**Comment by sortedcord** [comment]
Well, I suppose routine database backups weren't configured properly on my instance. Is there any way I can import the videos present in `streaming-playlists/` ? It's fine if they don't have their metadata..

**Comment by Chocobozzz** [comment]
Hello,

Please use [the forum](https://framacolibri.org/c/peertube/) for PeerTube support. But you may be able to create a script to upload your backed up videos using https://docs.joinpeertube.org/maintain-tools?id=peertube-uploadjs
