### ISSUE TITLE
Browser extension to seed videos

### ISSUE THREAD

**Issue by leethax666** [Chocobozzz/PeerTube#547]
I would love to seed videos I watch after I close the PeerTube page. A browser extension could do this, and have a few controls/stats.

**Comment by Chocobozzz** [comment]
Hi,

If you want to keep seeding a video, just use [WebTorrent Desktop](https://github.com/webtorrent/webtorrent-desktop/). It's better than an extension because files are stored on disk (not on RAM), and when you restart your computer it can continue to seed the files.
