### ISSUE TITLE
Highlights channels over accounts in global RSS feeds

### ISSUE THREAD

**Issue by raphgilles** [Chocobozzz/PeerTube#5470]
### Describe the problem to be solved

Currently the RSS feeds of the main tabs highlights accounts rather than channels. It does not follow the logic which highlights channels in these tabs since some versions.

It seems obvious to me to follow this logic for RSS feeds as well.

### Describe the solution you would like

Change : 
`<dc:creator>The account</dc:creator>`

By : 
`<dc:creator>The channel</dc:creator>`

**Comment by Chocobozzz** [comment]
Yes you're right! Implemented in https://github.com/Chocobozzz/PeerTube/commit/ec3ce76f195467bcc4f30b0844b63f5495162f8f
