### ISSUE TITLE
Prometheus exporter: wrong channel number

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5472]
### Describe the current behavior

We just setup Prometheus/Grafana for one of our instance (and that's really great!).

We notice an inconsistency in data: 20 users, but 970 channels!

I think that the user count is for the local users (and that's good), but the channel count includes all remote channels know by the server.

### Steps to reproduce

1. Configure Prometheus/Grafana
2. Check the channel count

### Describe the expected behavior

The channel count should only count local channels.

### Additional information

* PeerTube instance:
  * Version: 5.0.0

**Comment by Chocobozzz** [comment]
Thanks! That should be fixed by https://github.com/Chocobozzz/PeerTube/commit/dfa4944f3401b5c1225e3235a016510c9f5a7c8a
