### ISSUE TITLE
Videos are uploaded & transcoded but none will play

### ISSUE THREAD

**Issue by joekarns** [Chocobozzz/PeerTube#5473]
### Describe the current behavior

I created a new instance of Peertube via Cloudron (running on Vultr server) and everything seems to be working fine except one (big) issue:

None of the videos will play after being uploaded (and transcoded).

Examples:  
https://tube.viraladdiction.com/w/dmiX1UXsnDegjpuokEEG4W
https://tube.viraladdiction.com/w/wBfTh9fjeYTE9gWBkVAcht
https://tube.viraladdiction.com/w/xjqPtuWyeVzsM7fzjUTdNM
https://tube.viraladdiction.com/w/p1ssnh44Co3Q9fMWufoH9B

I checked the "jobs" (tasks) log and see that these videos have been transcoded.  Also strange:  When I post one of my Peertube video links on Twitter, the preview video shows and will play, so this issue seems to be isolated to watching the videos on my instance of Peertube directly.

Any idea how I can get the videos to play?

![Transcoding Completed Screen Shot Example](https://user-images.githubusercontent.com/8163562/208502320-14224529-16ab-4b2a-a8a6-8c0eaab54cf6.jpg)

![image](https://user-images.githubusercontent.com/8163562/208502424-d8a86eed-eeb8-4ce7-81c1-a1940b842ed9.png)

Thanks!

### Steps to reproduce

1. Try playing/watching any of the videos on this instance (black screen)

### Describe the expected behavior

Videos should play once they are uploaded and transcoded.

### Additional information

* PeerTube instance:
  * URL:  https://tube.viraladdiction.com

* Browser name, version and platforms on which you could reproduce the bug:  Tested in Chrome, Brave, Edge, and Firefox

**Comment by SimplyCorbett** [comment]
Disable the tv-streaming plugin and try again.

**Comment by joekarns** [comment]
That seems to have solved it.  

Thanks!
