### ISSUE TITLE
Post deletions not federating to Mastodon

### ISSUE THREAD

**Issue by FediVideos** [Chocobozzz/PeerTube#5474]
### Describe the current behavior

(I wasn't sure whether to report this in PeerTube or Mastodon github. I tried Mastodon first but didn't get much interest.)

Posts deleted from PeerTube are persisting on Mastodon servers.

A large PeerTube instance was blocked by a large Mastodon instance due to spam, despite the spam already being deleted at the PeerTube end. Because the spam persisted on Mastodon, the Mastodon instance decided to block the PeerTube instance.

### Steps to reproduce

1. Go to https://tilvids.com/w/wm3Y7ztbnjJS8XKAdpBiw3 and observe no spam
2. Try opening same URL on Mastodon and you may see lots of spam, especially if it is a larger instance (I tested this on mstdn.social)
3. Try opening a spammer's account on the original page, you will see they have all been deleted on PeerTube

### Describe the expected behavior

Posts deleted on PeerTube should also be deleted on Mastodon.

### Additional information

* PeerTube instance: tilvids.com
  * URL: https://tilvids.com/w/wm3Y7ztbnjJS8XKAdpBiw3
  * Version: 4.3.1
  * NodeJS version: 
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

> Try opening same URL on Mastodon and you may see lots of spam, especially if it is a larger instance (I tested this on mstdn.social)

Can you give the direct link?

**Comment by alejandrocobo** [comment]
I have the same issue. Here you have a toot with an answer from an account that doesn't exist anymore: https://social.hardlimit.com/web/@pos_yo@video.hardlimit.com/109546572343971755

**Comment by Chocobozzz** [comment]
@alejandrocobo your url is redirecting to the peertube instance

**Comment by alejandrocobo** [comment]
Apparently you must be logged in to see that toot. Here I post a screenshot:

![imagen](https://user-images.githubusercontent.com/1640709/210108322-edfdfeee-840a-4c93-8a66-ff631655657a.png)

**Comment by FediVideos** [comment]
> Hello,
> 
> > Try opening same URL on Mastodon and you may see lots of spam, especially if it is a larger instance (I tested this on mstdn.social)
> 
> Can you give the direct link?

The direct link can be got by pasting the same URL into your Mastodon instance's search box.

I did this on mstdn.social but am guessing you will see the same results on any instance where at least one person was already following this PeerTube account (so that would be any very large instance like mastodon.social etc).

As @alejandrocobo says, you have to be logged in to see this so I cannot give a direct link on Mastodon. But the result is similar to what they posted a screenshot of.


(My apologies for taking time to get back to this!)

**Comment by Chocobozzz** [comment]
The delete message may have been lost or wrongly delivered. Are you aware of other videos that have this issue with PeerTube instances >= v5? We fixed some Activity Pub delivery problems in 5.0

**Comment by FediVideos** [comment]
This seems to happen particularly on Tilvids, but that's possibly because it's a relatively high profile server that is being targetted by a lot of spammers.

They are still on 4.3.1 though so perhaps this has already been fixed by 5.0?

I'll ask them to update, see how that goes and will report back in this thread if the problems persist.

**Comment by Chocobozzz** [comment]
I'm closing this issue, please comment it if you still have your bug with peertube v5 :)
