### ISSUE TITLE
Visibility status not constant

### ISSUE THREAD

**Issue by EricGuic** [Chocobozzz/PeerTube#5475]
### Describe the current behavior

Hi, maybe this is more a translation error than a code one, but I prefer to report it here.
The visibility status of a video isn't constant in the different pages of Peertube.

For the **same video**, it shows "_Non listée_" here in the "Update" page : 
![image](https://user-images.githubusercontent.com/81166671/208612560-a0c5efaa-abff-4f39-8f8a-3789db8b35ed.png)

and here in the playlist view on the channel page, it shows "_Non répertoriée_" : 
![image](https://user-images.githubusercontent.com/81166671/208613049-49c39123-7482-4bab-a7d4-85073a98a1e6.png)

Same occurs for **the playlist visibility**. There is also a possible confusion in the playlist view with "_Non répertoriée_" : 
![image](https://user-images.githubusercontent.com/81166671/208613291-a82af3a1-981c-4767-8355-7437a27d8bc2.png)

where the edit page of the playlist shows "_Non listée_" : 
![image](https://user-images.githubusercontent.com/81166671/208613584-0549cceb-fc35-4c1c-af1a-ab06cf82d6ad.png)

### Steps to reproduce

1.Create a video or a playlist
2. Set his visibility to "Unlisted" (maybe true for other value, I didn't test it)
3. See the different page where this status is visible

### Describe the expected behavior

Have the same term used in this different pages, to avoid confusion

### Additional information

* PeerTube instance:
  * URL:
  * Version: 4.3.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

I think it's an inconsistency in the French translations. You can use the search function in weblate to find and fix translations: https://weblate.framasoft.org/translate/peertube/angular/fr_FR

**Comment by EricGuic** [comment]
Hi, I've made the changes in weblate (I've only found to occurences).
