### ISSUE TITLE
Missing ellipsis on peertube-videos-list markdown

### ISSUE THREAD

**Issue by Kinuseka** [Chocobozzz/PeerTube#5477]
### Describe the problem to be solved

Custom homepage is certainly one of the best ways to show, decorate, and to impress visitors to your instance.
The only thing is that this needs a consistency to the UI. 
for example on `/home`
![image](https://user-images.githubusercontent.com/66762783/208836621-1f8248a6-9d4a-464b-b84e-19963c87b55f.png)
Shows no vertical ellipsis on the video. 

but on `Discover`, `Local videos`, `recently added`, and `trending`
shows a vertical ellipses
![image](https://user-images.githubusercontent.com/66762783/208836943-e272d36e-f358-463d-9603-3f878fabed6c.png)

### Describe the solution you would like

What we want is a consistency on the UI to make sure that all the tool of features are provided and remains streamline.

For example the user finds something they like on the homepage, they want to add it to their playlist, but the homepage  does not contain the vertical ellipsis that they want to quickly add it to their playlist so they have to click the video first to add it. Pretty inconvenient.

**Comment by Chocobozzz** [comment]
Nice catch! I enabled the dropdown in https://github.com/Chocobozzz/PeerTube/commit/77f0c0e5dc197729a9255188c210e363b7d90be1
