### ISSUE TITLE
Peertube showing 1 column of videos instead of 2 on mobile browser

### ISSUE THREAD

**Issue by dausruddin** [Chocobozzz/PeerTube#5478]
### Describe the current behavior

In 5.0.0, video list are being shown in 1 column, instead of 2.

How it looks like in **4.3.1**:
![Screenshot_20221222-205832_Edge](https://user-images.githubusercontent.com/5763466/209140721-2e6c6417-c346-47e4-b256-b87bf02cdd4a.png)

How it looks like in **5.0.0**:
![Screenshot_20221222-205843_Edge](https://user-images.githubusercontent.com/5763466/209140760-c8bbd3f6-781e-46b1-b87f-7ff74814f526.png)

### Steps to reproduce

1. Upgrade to 5.0.0
2. Go to homepage

### Describe the expected behavior

2 columns are shown instead

### Additional information

* PeerTube instance:
  * URL: https://peertube.sqweeb.net/ (not mine, but any 5.0.0 will have same issue)
  * Version: 5.0.0
  * NodeJS version: N/A
  * Ffmpeg version: N/A

* Browser name, version and platforms on which you could reproduce the bug: Edge, Android, version 108.0.1462.48
* Link to browser console log if relevant: 
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Margins may have changed so with your specific width you have now only 1 column. However it's weird that your mobile phone has so big width. Did you change DPI setting? If no can you test with another web browser?
