### ISSUE TITLE
4k Video will not move to external storage

### ISSUE THREAD

**Issue by stevespaw** [Chocobozzz/PeerTube#5483]
### Describe the current behavior

error[12/27/2022, 9:01:51 AM] Cannot execute job 6 in queue move-to-object-storage.
{
  "payload": {
    "videoUUID": "17b45991-63ca-4cfd-8147-556e063d8907",
    "isNewVideo": false,
    "previousVideoState": 8
  },
  "err": {
    "stack": "RangeError [ERR_INVALID_ARG_VALUE]: The argument 'size' is invalid. Received 5182274049\n    at Function.allocUnsafe (node:buffer:373:3)\n    at Function.concat (node:buffer:552:25)\n    at getChunkStream (/app/code/server/node_modules/@aws-sdk/lib-storage/dist-cjs/chunks/getChunkStream.js:24:31)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Upload.__doConcurrentUpload (/app/code/server/node_modules/@aws-sdk/lib-storage/dist-cjs/Upload.js:120:26)\n    at async Promise.all (index 0)\n    at async Upload.__doMultipartUpload (/app/code/server/node_modules/@aws-sdk/lib-storage/dist-cjs/Upload.js:211:9)\n    at async Upload.done (/app/code/server/node_modules/@aws-sdk/lib-storage/dist-cjs/Upload.js:39:16)",
    "message": "The argument 'size' is invalid. Received 5182274049",
    "code": "ERR_INVALID_ARG_VALUE"
  }
}

### Steps to reproduce

upload a 1.5 hour 4K movie. with transcodes to 2160,1080,720,480
All works fine - (slow, but works)
All of the files move fine into the bucket except the 2160 (5.1 GB)- it seems to have a "size" error
Peertube 5

### Additional information

* PeerTube instance:
  * URL:
  * Version: 5
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Kinuseka** [comment]
Diagnostics:
Check your object storage provider their maximum file size per upload.
Next is check your File system type, 
then check if ur running this on a low ram environment 

Possible causes:
- nodejs ran out of Heap memory 

Possible solutions:
on `production.yaml` check your `object_storage.max_upload_part`

If its >5gb set it to `100MB` or `10MB`

**Comment by stevespaw** [comment]
I had it set to 100MB. but even changed it to 1000MB. Still the same issue.

It is s3 storage with no issue on files larger that this in regular use.

**Comment by Chocobozzz** [comment]
Can you display https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L145 section? (hiding `object_storage.credentials`)

**Comment by stevespaw** [comment]
listen:
  hostname: 0.0.0.0
  port: 9000
# Correspond to your reverse proxy server_name/listen configuration
webserver:
  https: true
  hostname: 'video3.c.co'
  port: 443
rates_limit:
  api:
    # 50 attempts in 10 seconds
    window: 10 seconds
    max: 50
  login:
    # 15 attempts in 5 min
    window: 5 minutes
    max: 15
  signup:
    # 2 attempts in 5 min (only succeeded attempts are taken into account)
    window: 5 minutes
    max: 2
  ask_send_email:
    # 3 attempts in 5 min
    window: 5 minutes
    max: 3
# Proxies to trust to get real client IP
# If you run PeerTube just behind a local proxy (nginx), keep 'loopback'
# If you run PeerTube behind a remote proxy, add the proxy IP address (or subnet)
trust_proxy:
  - 172.18.0.0/16
  - 'loopback'
database:
  hostname: 'postgresql'
  name: 'dbc46dab9aad894823973b94e3c7042c38'
  port: 5432
  username: 'userc46dab9aad894823973b94e3c7042c38'
  password: 'xxxxxxx9d5f3923dbb22ae2341036cd0851a824dd2707090a0aca18fdb5ae7aa86c9638c4a40c0e927bcc43c381bd5d1a0d19fec3b150f09cf4ee02c6065d1'
  pool:
    max: 5
# Redis server for short time storage
# You can also specify a 'socket' path to a unix socket but first need to
# comment out hostname and port
redis:
  hostname: 'redis-c46dab9a-ad89-4823-973b-94e3c7042c38'
  port: 6379
  auth: 1c0958ea32a24cb2d27ecdae2bec8843c478a9c55b9ae3ef
  db: 0
# SMTP server to send emails
smtp:
  # smtp or sendmail
  transport: smtp
  # Path to sendmail command. Required if you use sendmail transport
  sendmail: null
  hostname: mail
  port: 2525 # If you use StartTLS: 587
  username: video3.app@c.co
  password: xxxxxx4ed777aecdc1d097c22aa5274f12dbab5aad4aba5
  tls: false # If you use StartTLS: false
  disable_starttls: true
  ca_file: null # Used for self signed certificates
  from_address: 'video3.app@c.co'
email:
  body:
    signature: "PeerTube"
  subject:
    prefix: "[PeerTube]"
# From the project root directory
storage:
  tmp: '/app/data/storage/tmp/' # Use to download data (imports etc), store uploaded files before processing...
  avatars: '/app/data/storage/avatars/'
  videos: '/app/data/storage/videos/'
  streaming_playlists: '/app/data/storage/streaming-playlists/'
  redundancy: '/app/data/storage/redundancy/'
  logs: '/app/data/storage/logs/'
  previews: '/app/data/storage/previews/'
  thumbnails: '/app/data/storage/thumbnails/'
  torrents: '/app/data/storage/torrents/'
  captions: '/app/data/storage/captions/'
  cache: '/app/data/storage/cache/'
  plugins: '/app/data/storage/plugins/'
  client_overrides: '/app/data/storage/client-overrides/'
  bin: /app/data/storage/bin/
  well_known: /app/data/storage/well_known/
# insert after storage
object_storage:
  enabled: true
  # Without protocol, will default to HTTPS
  endpoint: 'xxxxxxxxdrivexx-14.com' # 's3.amazonaws.com' or 's3.fr-par.scw.cloud' for example
  region: 'us-da'
  upload_acl:
    # Set this ACL on each uploaded object of public/unlisted videos
    public: 'public-read'
    # Set this ACL on each uploaded object of private/internal videos
    # PeerTube can proxify requests to private objects so your users can access them
    private: 'private'
  proxy:
    # If private files (private/internal video files) have a private ACL, users can't access directly the ressource
    # PeerTube can proxify requests between your object storage service and your users
    # If you disable PeerTube proxy, ensure you use your own proxy that is able to access the private files
    # Or you can also set a public ACL for private files in object storage if you don't want to use a proxy
    proxify_private_files: true
  credentials:
    # You can also use AWS_ACCESS_KEY_ID env variable
    access_key_id: 'xxxxxxxxxxxxxxxxxx'
    # You can also use AWS_SECRET_ACCESS_KEY env variable
    secret_access_key: 'xxxxxxxxxxxxxxxxxxxxxxxxxx'
  # Maximum amount to upload in one request to object storage
  max_upload_part: 1000GB
  streaming_playlists:
    bucket_name: 'video3'
    # Allows setting all buckets to the same value but with a different prefix
    # Example: 'streaming-playlists/'
    prefix: 'streaming-playlists/'
    # Base url for object URL generation, scheme and host will be replaced by this URL
    # Useful when you want to use a CDN/external proxy
    # Example: 'https://mirror.example.com'
    base_url: 'https://video3cdn.cappital.co'
  # Same settings but for webtorrent videos
  videos:
    bucket_name: 'video3'
    prefix: 'videos/'
    # Base url for object URL generation, scheme and host will be replaced by this URL
    # Useful when you want to use a CDN/external proxy
    base_url: 'https://video3cdn.cappital.co'
# Next - log
log:
  level: 'info' # debug/info/warning/error
  rotation:
    enabled: true # Enabled by default, if disabled make sure that 'storage.logs' is pointing to a folder handled by logrotate
    maxFileSize: 12MB
    maxFiles: 20
  anonymizeIP: false
trending:
  videos:
    interval_days: 7 # Compute trending videos for the last x days
# Cache remote videos on your server, to help other instances to broadcast the video
# You can define multiple caches using different sizes/strategies
# Once you have defined your strategies, choose which instances you want to cache in admin -> manage follows -> following
redundancy:
  videos:
    check_interval: '1 hour' # How often you want to check new videos to cache
    strategies: # Just uncomment strategies you want
#      -
#        size: '10GB'
#        # Minimum time the video must remain in the cache. Only accept values > 10 hours (to not overload remote instances)
#        min_lifetime: '48 hours'
#        strategy: 'most-views' # Cache videos that have the most views
#      -
#        size: '10GB'
#        # Minimum time the video must remain in the cache. Only accept values > 10 hours (to not overload remote instances)
#        min_lifetime: '48 hours'
#        strategy: 'trending' # Cache trending videos
#      -
#        size: '10GB'
#        # Minimum time the video must remain in the cache. Only accept values > 10 hours (to not overload remote instances)
#        min_lifetime: '48 hours'
#        strategy: 'recently-added' # Cache recently added videos
#        min_views: 10 # Having at least x views

# Other instances that duplicate your content
remote_redundancy:
  videos:
    # 'nobody': Do not accept remote redundancies
    # 'anybody': Accept remote redundancies from anybody
    # 'followings': Accept redundancies from instance followings
    accept_from: 'anybody'
csp:
  enabled: false
  report_only: true # CSP directives are still being tested, so disable the report only mode at your own risk!
  report_uri:
tracker:
  # If you disable the tracker, you disable the P2P aspect of PeerTube
  enabled: true
  # Only handle requests on your videos.
  # If you set this to false it means you have a public tracker.
  # Then, it is possible that clients overload your instance with external torrents
  private: true
  # Reject peers that do a lot of announces (could improve privacy of TCP/UDP peers)
  reject_too_many_announces: false
history:
  videos:
    # If you want to limit users videos history
    # -1 means there is no limitations
    # Other values could be '6 months' or '30 days' etc (PeerTube will periodically delete old entries from database)
    max_age: -1
views:
  videos:
    # PeerTube creates a database entry every hour for each video to track views over a period of time
    # This is used in particular by the Trending page
    # PeerTube could remove old remote video views if you want to reduce your database size (video view counter will not be altered)
    # -1 means no cleanup
    # Other values could be '6 months' or '30 days' etc (PeerTube will periodically delete old entries from database)
    remote:
      max_age: -1
plugins:
  # The website PeerTube will ask for available PeerTube plugins and themes
  # This is an unmoderated plugin index, so only install plugins/themes you trust
  index:
    enabled: true
    check_latest_versions_interval: '12 hours' # How often you want to check new plugins/themes versions
    url: 'https://packages.joinpeertube.org'
federation:
  videos:
    federate_unlisted: true
###############################################################################
#
# From this point, all the following keys can be overridden by the web interface
# (local-production.json file). If you need to change some values, prefer to
# use the web interface because the configuration will be automatically
# reloaded without any need to restart PeerTube.
#
# /!\ If you already have a local-production.json file, the modification of the
# following keys will have no effect /!\.
#
###############################################################################
cache:
  previews:
    size: 500 # Max number of previews you want to cache
  captions:
    size: 500 # Max number of video captions/subtitles you want to cache
admin:
  # Used to generate the root user at first startup
  # And to receive emails from the contact form
  email: 'admin@server.local'
contact_form:
  enabled: true
signup:
  enabled: false
  limit: 10 # When the limit is reached, registrations are disabled. -1 == unlimited
  requires_email_verification: false
  filters:
    cidr: # You can specify CIDR ranges to whitelist (empty = no filtering) or blacklist
      whitelist: []
      blacklist: []
user:
  # Default value of maximum video BYTES the user can upload (does not take into account transcoded files).
  # -1 == unlimited
  video_quota: -1
  video_quota_daily: -1
# If enabled, the video will be transcoded to mp4 (x264) with "faststart" flag
# In addition, if some resolutions are enabled the mp4 video file will be transcoded to these new resolutions.
# Please, do not disable transcoding since many uploaded videos will not work
transcoding:
  enabled: true
  # Allow your users to upload .mkv, .mov, .avi, .flv videos
  allow_additional_extensions: true
  # If a user uploads an audio file, PeerTube will create a video by merging the preview file and the audio file
  allow_audio_files: true
  threads: 1
  resolutions: # Only created if the original video has a higher resolution, uses more storage!
    0p: false # audio-only (creates mp4 without video stream, always created when enabled)
    240p: false
    360p: false
    480p: false
    720p: false
    1080p: false
    2160p: false
  # Generate videos in a WebTorrent format (what we do since the first PeerTube release)
  # If you also enabled the hls format, it will multiply videos storage by 2
  # If disabled, breaks federation with PeerTube instances < 2.1
  webtorrent:
    enabled: true
  # /!\ Requires ffmpeg >= 4.1
  # Generate HLS playlists and fragmented MP4 files. Better playback than with WebTorrent:
  #     * Resolution change is smoother
  #     * Faster playback in particular with long videos
  #     * More stable playback (less bugs/infinite loading)
  # If you also enabled the webtorrent format, it will multiply videos storage by 2
  hls:
    enabled: false
import:
  # Add ability for your users to import remote videos (from YouTube, torrent...)
  videos:
    http: # Classic HTTP or all sites supported by youtube-dl https://rg3.github.io/youtube-dl/supportedsites.html
      enabled: false
      # You can use an HTTP/HTTPS/SOCKS proxy with youtube-dl
      proxy:
        enabled: false
        url: ""
    torrent: # Magnet URI or torrent file (use classic TCP/UDP/WebSeed to download the file)
      enabled: false
auto_blacklist:
  # New videos automatically blacklisted so moderators can review before publishing
  videos:
    of_users:
      enabled: false
# Instance settings
instance:
  name: 'PeerTube'
  short_description: 'PeerTube, a federated (ActivityPub) video streaming platform using P2P (BitTorrent) directly in the web browser with WebTorrent and Angular.'
  description: 'Welcome to this PeerTube instance!' # Support markdown
  terms: 'No terms for now.' # Support markdown
  code_of_conduct: '' # Supports markdown
  # Who moderates the instance? What is the policy regarding NSFW videos? Political videos? etc
  moderation_information: '' # Supports markdown
  # Why did you create this instance?
  creation_reason: ''
  # Who is behind the instance? A single person? A non profit?
  administrator: ''
  # How long do you plan to maintain this instance?
  maintenance_lifetime: ''
  # How will you pay the PeerTube instance server? With your own funds? With users donations? Advertising?
  business_model: ''
  # If you want to explain on what type of hardware your PeerTube instance runs
  # Example: "2 vCore, 2GB RAM..."
  hardware_information: '' # Supports Markdown
  # What are the main languages of your instance? To interact with your users for example
  # Uncomment or add the languages you want
  # List of supported languages: https://peertube.cpy.re/api/v1/videos/languages
  languages:
  #    - en
  #    - es
  #    - fr

  # You can specify the main categories of your instance (dedicated to music, gaming or politics etc)
  # Uncomment or add the category ids you want
  # List of supported categories: https://peertube.cpy.re/api/v1/videos/categories
  categories:
  #    - 1  # Music
  #    - 2  # Films
  #    - 3  # Vehicles
  #    - 4  # Art
  #    - 5  # Sports
  #    - 6  # Travels
  #    - 7  # Gaming
  #    - 8  # People
  #    - 9  # Comedy
  #    - 10 # Entertainment
  #    - 11 # News & Politics
  #    - 12 # How To
  #    - 13 # Education
  #    - 14 # Activism
  #    - 15 # Science & Technology
  #    - 16 # Animals
  #    - 17 # Kids
  #    - 18 # Food
  default_client_route: '/videos/trending'
  # Whether or not the instance is dedicated to NSFW content
  # Enabling it will allow other administrators to know that you are mainly federating sensitive content
  # Moreover, the NSFW checkbox on video upload will be automatically checked by default
  is_nsfw: false
  # By default, "do_not_list" or "blur" or "display" NSFW videos
  # Could be overridden per user with a setting
  default_nsfw_policy: 'do_not_list'
  customizations:
    javascript: '' # Directly your JavaScript code (without <script> tags). Will be eval at runtime
    css: '' # Directly your CSS code (without <style> tags). Will be injected at runtime
  # Robot.txt rules. To disallow robots to crawl your instance and disallow indexation of your site, add '/' to "Disallow:'
  robots: |
    User-agent: *
    Disallow:
  # Security.txt rules. To discourage researchers from testing your instance and disable security.txt integration, set this to an empty string.
  securitytxt: "# If you would like to report a security issue\n# you may report it to:\nContact: https://github.com/Chocobozzz/PeerTube/blob/develop/SECURITY.md\nContact: mailto:"
services:
  # Cards configuration to format video in Twitter
  twitter:
    username: '@cloudron_io' # Indicates the Twitter account for the website or platform on which the content was published
    # If true, a video player will be embedded in the Twitter feed on PeerTube video share
    # If false, we use an image link card that will redirect on your PeerTube instance
    # Change it to "true", and then test on https://cards-dev.twitter.com/validator to see if you are whitelisted
    whitelisted: false
followers:
  instance:
    # Allow or not other instances to follow yours
    enabled: true
    # Whether or not an administrator must manually validate a new follower
    manual_approval: false
followings:
  instance:
    # If you want to automatically follow back new instance followers
    # If this option is enabled, use the mute feature instead of deleting followings
    # /!\ Don't enable this if you don't have a reactive moderation team /!\
    auto_follow_back:
      enabled: false
    # If you want to automatically follow instances of the public index
    # If this option is enabled, use the mute feature instead of deleting followings
    # /!\ Don't enable this if you don't have a reactive moderation team /!\
    auto_follow_index:
      enabled: false
      # Host your own using https://framagit.org/framasoft/peertube/instances-peertube#peertube-auto-follow
      index_url: ''
theme:
  default: 'default'
broadcast_message:
  enabled: false
  message: '' # Support markdown
  level: 'info' # 'info' | 'warning' | 'error'
  dismissable: false
search:
  # Add ability to fetch remote videos/actors by their URI, that may not be federated with your instance
  # If enabled, the associated group will be able to "escape" from the instance follows
  # That means they will be able to follow channels, watch videos, list videos of non followed instances
  remote_uri:
    users: true
    anonymous: false
  # Use a third party index instead of your local index, only for search results
  # Useful to discover content outside of your instance
  # If you enable search_index, you must enable remote_uri search for users
  # If you do not enable remote_uri search for anonymous user, your instance will redirect the user on the origin instance
  # instead of loading the video locally
  search_index:
    enabled: false
    # URL of the search index, that should use the same search API and routes
    # than PeerTube: https://docs.joinpeertube.org/api-rest-reference.html
    # You should deploy your own with https://framagit.org/framasoft/peertube/search-index,
    # and can use https://search.joinpeertube.org/ for tests, but keep in mind the latter is an unmoderated search index
    url: ''
    # You can disable local search, so users only use the search index
    disable_local_search: false
    # If you did not disable local search, you can decide to use the search index by default
    is_default_search: false
secrets:
  peertube: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by Kinuseka** [comment]
I recommend setting `max_upload_part` should be <1GB 
or
 `max_upload_part: 100MB`  

It seems the error is that nodeJS cannot allocate more than 4gb of memory (strict standard based on documentation)

**Comment by stevespaw** [comment]
I had tried setting to 100MB (when it first occurred - that is the default) and 10MB. Both had the same result. Why is the issue closed?

**Comment by Chocobozzz** [comment]
Issue has been closed because @Kinuseka answered to your question. We said to set `object_storage.max_upload_part: 100MB` but you paste your configuration where `object_storage.max_upload_part` is `1000GB`. It's clearly the cause of your issue.

**Comment by stevespaw** [comment]
I said in my first post that 100 MB is where I started, the default. I changed it to 1000 just to test.
The error ""stack": "RangeError [ERR_INVALID_ARG_VALUE]: The argument 'size' is invalid. Received 5182274049\n at Function.allocUnsafe"
Seems to be the issue, but I don't know.

**Comment by stevespaw** [comment]
Here is the Job error if that helps - I have changed the upload_part back to 100 MB

--
RangeError [ERR_INVALID_ARG_VALUE]: The argument 'size' is invalid. Received 5182274049     at Function.allocUnsafe (node:buffer:373:3)     at Function.concat (node:buffer:552:25)     at getChunkStream (/app/code/server/node_modules/@aws-sdk/lib-storage/dist-cjs/chunks/getChunkStream.js:24:31)     at runMicrotasks (<anonymous>)     at processTicksAndRejections (node:internal/process/task_queues:96:5)     at async Upload.__doConcurrentUpload (/app/code/server/node_modules/@aws-sdk/lib-storage/dist-cjs/Upload.js:120:26)     at async Promise.all (index 0)     at async Upload.__doMultipartUpload (/app/code/server/node_modules/@aws-sdk/lib-storage/dist-cjs/Upload.js:211:9)     at async Upload.done (/app/code/server/node_modules/@aws-sdk/lib-storage/dist-cjs/Upload.js:39:16)


</body>
</html>

**Comment by Chocobozzz** [comment]
Can you add a `console.log(CONFIG)` in `dist/server/initializers/config.js` (~ line 500) to check the value loaded by PeerTube? (only paste `OBJECT_STORAGE` sub object please)

**Comment by stevespaw** [comment]
I am not sure what you need here, Here is that section of config.js

    },
    OBJECT_STORAGE: {
        ENABLED: config.get('object_storage.enabled'),
        MAX_UPLOAD_PART: bytes_1.default.parse(config.get('object_storage.max_upload_part')),
        ENDPOINT: config.get('object_storage.endpoint'),
        REGION: config.get('object_storage.region'),
        UPLOAD_ACL: {
            PUBLIC: config.get('object_storage.upload_acl.public'),
            PRIVATE: config.get('object_storage.upload_acl.private')
        },
        CREDENTIALS: {
            ACCESS_KEY_ID: config.get('object_storage.credentials.access_key_id'),
            SECRET_ACCESS_KEY: config.get('object_storage.credentials.secret_access_key')
        },
        PROXY: {
            PROXIFY_PRIVATE_FILES: config.get('object_storage.proxy.proxify_private_files')
        },
        VIDEOS: {
            BUCKET_NAME: config.get('object_storage.videos.bucket_name'),
            PREFIX: config.get('object_storage.videos.prefix'),
            BASE_URL: config.get('object_storage.videos.base_url')
        },
        STREAMING_PLAYLISTS: {
            BUCKET_NAME: config.get('object_storage.streaming_playlists.bucket_name'),
            PREFIX: config.get('object_storage.streaming_playlists.prefix'),
            BASE_URL: config.get('object_storage.streaming_playlists.base_url')
        }
    },

**Comment by Chocobozzz** [comment]
Insert `console.log(CONFIG.OBJECT_STORAGE)` in `peertube-latest/dist/server/initializers/config.js` line `500`, and restart PeerTube. It should output in stdout (that you can see using `journalctl -eu peertube`) the config loaded by peertube

**Comment by stevespaw** [comment]
Sorry, I am not a linux/docker expert. I am running this with a docker image, and get this with nano: 
![image](https://user-images.githubusercontent.com/11045430/210430742-f00acf80-99ee-4cf8-9730-e1eac1cf8058.png)
How do I do this?

**Comment by stevespaw** [comment]
tried with and without sudo, same thing - I think this is a docker thing.

**Comment by Chocobozzz** [comment]
Oh you use Docker?

Then try to add `PEERTUBE_OBJECT_STORAGE_MAX_UPLOAD_PART=100MB` in your `.env` and restart your containers.

**Comment by stevespaw** [comment]
OK I will try that Thanks. I am back from vacation.
This can be replicated on an object storage system with a YouTube download:
https://www.youtube.com/watch?v=bUCfv8D_hoQ

**Comment by stevespaw** [comment]
same error... after I found an .env file and added the line and restarted.

**Comment by kukhariev** [comment]
Currently with `lib-storage`, even if we set `PEERTUBE_OBJECT_STORAGE_MAX_UPLOAD_PART=100MB`, 3*100MB of memory will be used for each file.

@kontrollanten 
What do you think about undoing the use of lib-storage(#4903)?

**Comment by kukhariev** [comment]
`lib-storage` always buffers file streams (`queueSize` * `partSize`) аnd there is no way to change this.
