### ISSUE TITLE
Invalid link for "required external dependencies versions"

### ISSUE THREAD

**Issue by joho1968** [Chocobozzz/PeerTube#5489]
### Describe the desired information/correction

The link "[required external dependencies versions](https://github.com/Chocobozzz/PeerTube/blob/master/engines.yaml)." on this page: https://docs.joinpeertube.org/dependencies is pointing to a 404 (https://github.com/Chocobozzz/PeerTube/blob/master/engines.yaml)

**Comment by Chocobozzz** [comment]
Thanks! I removed the dead link in https://github.com/Chocobozzz/PeerTube/commit/cf7045bfd7866447a3f18e1395c7978a4296c7ec
