### ISSUE TITLE
Navigation in imports are broken in smartphone view

### ISSUE THREAD

**Issue by xundeenergie** [Chocobozzz/PeerTube#5491]
### Describe the current behavior

The bottom of the Imports-page show arrows and site-numbers to navigate through my imports.
In smartphoneview this is broken.
See the screenshot

![Screenshot_20221230_041734](https://user-images.githubusercontent.com/5894829/210031273-0b3bfc01-a606-4853-861c-d34953a0900a.jpg)

Pagenumbers and arrows and description-text is mixed up together.

### Steps to reproduce

1.
2.
3.

### Describe the expected behavior

Show clear view of arrows side by side with pagenumbers on the bottom in smartphone-view.

### Additional information

* PeerTube instance: 
  * URL: https://kino.schuerz.at/my-library/video-imports
  * Version: 5.0.0
  * NodeJS version: ?
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox Android
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks for the issue!

It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/fbe088b816c6e33e013006285e18bc2938173507
