### ISSUE TITLE
You can still go back in the timeline of a livestream with arrow keys

### ISSUE THREAD

**Issue by DavidLibeau** [Chocobozzz/PeerTube#5494]
### Describe the current behavior

On a livestream, if you press left arrow key you can go back in the timeline.

### Steps to reproduce

1. Open a livestream
2. Press left arrow key

### Describe the expected behavior

I think this is not intended and it cause issues. If you press left arrow key several times you come back to the livestream without notice. The player could also crash if you press these keys too fast.

### Additional information

* PeerTube instance:
  * URL:
  * Version: 5.0.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/66b73484c719659d213cab225ae3b63a3aae5228
