### ISSUE TITLE
Leave socket.io for performance reasons?

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5495]
### Describe the desired information/correction

[ws](https://www.npmjs.com/package/ws) seems to has a lot of better performance than socket.io. [uWebSocket.js claims to be even faster](https://github.com/uNetworking/uWebSockets.js/blob/00c9f4e47873b7395054b2f93332f27cf47f62e6/README.md#muscle-unfair-advantage). The latter is built in C++ and [is used by bun](https://github.com/oven-sh/bun/blob/fc6c4bbefbbd59063aae9127f267247f587163bf/README.md). Before doing any benchmarks and putting work into this, is there any particular reason that socket.io is used today?

Note to self: benchmark can be done with artillery.

**Comment by Chocobozzz** [comment]
>  is there any particular reason that socket.io is used today

The API of socket.io has nothing in common with ws, or am I missing something? socket.io is used to manage events between server and client using an easy API. It doesn't necessarily use a websocket under the hood.

**Comment by Chocobozzz** [comment]
socket.io is much more powerful than classic websocket library: you can create rooms, it has HTTP fallback, auto reconnection, broadcasting, multiplexing etc.
Do you have performance issues with socket.io?

**Comment by ROBERT-MCDOWELL** [comment]
socket.io has been developed to have a maximum compatibility between browsers, OS and versions, not for performance.
As long as you start to add layer of frameworks it will be obviously slower than pure javascript.

**Comment by ROBERT-MCDOWELL** [comment]
@kontrollanten 
don't forget that there are many countries where old computers with old OS are still running and not all people have money to have a device with the last version of everything...

**Comment by ROBERT-MCDOWELL** [comment]
@kontrollanten 
trust statistics today is like trust illusions....
