### ISSUE TITLE
Settings Link Missing after 5.0 Upgrade

### ISSUE THREAD

**Issue by nishantsworld** [Chocobozzz/PeerTube#5496]
### Describe the current behavior

I was able to see the Administration link while installing v4.3, however unable to see it in v5.

Just fyi...

- It was missing even in v5 RC1, however i thought it might be a miss and will get fixed in the stable build
- I have not installed any custom plugins, but using the official production-bullseye image
- Even if i try to manually visit /admin/users/list in the URL (like for v4.3), it simply redirects me to "My Account"

### Steps to reproduce

1. Login with root creds
2. Check the main navigation menu
3. Settings link is missing

### Describe the expected behavior

Settings link should be visible when logged in as root

### Additional information

* PeerTube instance:
  * URL: https://wakenext.com/
  * Version: 5.0.0
  * NodeJS version: Using official Docker Image
  * Ffmpeg version: Using official Docker Image

* Browser name, version and platforms on which you could reproduce the bug: Chrome Version 108.0.5359.125 (Official Build) (64-bit) on Windows 10 22H2
* Link to browser console log if relevant: N/A
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): N/A

**Comment by Chocobozzz** [comment]
> It was missing even in v5 RC1, however i thought it might be a miss and will get fixed in the stable build

Please report this kind of issue when you use release candidates. It's the purpose of such release :)

Have you correctly followed docker upgrade guide? https://docs.joinpeertube.org/install-docker?id=upgrade

In particular the `sudo docker-compose down -v` step (`-v` is important)

**Comment by Chocobozzz** [comment]
I think your web browser is blocking the request to github to fetch the markdown file. Disable your privacy plugins for this domain or use another web browser :)

**Comment by nishantsworld** [comment]
Finally able to view the https://docs.joinpeertube.org/install-docker?id=upgrade .

However, I have done a fresh install (not an upgrade) without any plugins, following the instructions in https://docs.joinpeertube.org/install-docker?id=install and still no luck. I still don't see the settings menu on logging in as root.

**Comment by Chocobozzz** [comment]
Please run `docker-compose down -v && docker-compose up -d`

**Comment by nishantsworld** [comment]
Excellent! That has brought back the Administration menu!

Worth adding that line of command to https://docs.joinpeertube.org/install-docker?id=install

Thank you :)
