### ISSUE TITLE
Seems doesn't support Chinese character

### ISSUE THREAD

**Issue by imtube** [Chocobozzz/PeerTube#55]
Hello,
I see that you have add Chinese character support for tag and title and description, and I had a look at the demo, 

I have reinstalled my server's OS and peertube, but when I input Chinese character, the system says:

> A tag should be between 2 and 10 alphanumeric characters long.

so I can't add any tag successfully.

Then I changed the tag to English, and uploaded a video whose file name is Chinese, then I met some error and can't complete the uploading.

This is the log file, in case you need it:
[log.txt](https://github.com/Chocobozzz/PeerTube/files/878874/log.txt)

**Comment by imtube** [comment]
The web browser console error is 
`Failed to load resource: the server responded with a status of 504 (Gateway Time-out)`

**Comment by imtube** [comment]
Sorry, I have just tested it again, even the title and tag and description are all English character, the system shows the same error: Unknown error,and the web browser console error is
Failed to load resource: the server responded with a status of 504 (Gateway Time-out)

**Comment by Chocobozzz** [comment]
Might be a PostgreSQL setup issue.

Can you try http://stackoverflow.com/a/14525508?

**Comment by imtube** [comment]
@Chocobozzz I have tried it, and there's some strange error.
I followed the guide, first, it was all right:
```
postgres=# show client_encoding;
 client_encoding
-----------------
 LATIN1
(1 row)

postgres=# SET client_encoding = 'UTF8';
SET

postgres=# show client_encoding;
 client_encoding
-----------------
 UTF8
(1 row)
```
Then I rebooted the server, and run command:
`show client_encoding;`
It shows:
```
 client_encoding
-----------------
 LATIN1
(1 row)
```

**Comment by imtube** [comment]
I tested again, there's no need reboot the server after I set UTF8, just run command
`\q`
to quit PostgreSQL, then login it again, run command
`show client_encoding;`
It will shows
```
client_encoding
-----------------
 LATIN1
(1 row)
```

**Comment by Chocobozzz** [comment]
What is the output of `\l` in psql?

https://www.postgresql.org/docs/9.3/static/multibyte.html could be relevant

**Comment by imtube** [comment]
@Chocobozzz The output result is follow:
```
postgres=# \l
                               List of databases
     Name      |  Owner   | Encoding | Collate | Ctype |   Access privileges
---------------+----------+----------+---------+-------+-----------------------
 peertube_prod | kankan   | LATIN1   | en_US   | en_US | =Tc/kankan           +
               |          |          |         |       | kankan=CTc/kankan
 postgres      | postgres | LATIN1   | en_US   | en_US |
 template0     | postgres | LATIN1   | en_US   | en_US | =c/postgres          +
               |          |          |         |       | postgres=CTc/postgres
 template1     | postgres | LATIN1   | en_US   | en_US | =c/postgres          +
               |          |          |         |       | postgres=CTc/postgres
(4 rows)
```

**Comment by Chocobozzz** [comment]
`peertube_prod` should be in UTF8

**Comment by imtube** [comment]
@Chocobozzz How can I fix it ?

**Comment by imtube** [comment]
@Chocobozzz I have changed peertube_prod to UTF8, the result is:
```
postgres=# \l
                               List of databases
     Name      |  Owner   | Encoding | Collate | Ctype |   Access privileges
---------------+----------+----------+---------+-------+-----------------------
 peertube_prod | kankan   | UTF8     | en_US   | en_US | =Tc/kankan           +
               |          |          |         |       | kankan=CTc/kankan
 postgres      | postgres | LATIN1   | en_US   | en_US |
 template0     | postgres | LATIN1   | en_US   | en_US | =c/postgres          +
               |          |          |         |       | postgres=CTc/postgres
 template1     | postgres | LATIN1   | en_US   | en_US | =c/postgres          +
               |          |          |         |       | postgres=CTc/postgres
(4 rows)

```
But I still get 401 error now when I update video:
`Failed to load resource: the server responded with a status of 401 (Unauthorized)`

**Comment by imtube** [comment]
@Chocobozzz I reset my server's local encoding and reinstall psql, then I can upload Chinese title video and set it's title and description to Chinese now, but I still can't set Chinese tag, it always says `A tag should be between 2 and 10 alphanumeric characters long.` when I input Chinese tag and I can't press enter to add it.

**Comment by Green-Star** [comment]
I tried to upload a video on my peertube, setting a `測試` tag (which seems to mean test according to Google Translate (don't judge me :pensive:)) and everything went fine.

From your error message, I would say your issue is related to the tag length (which seems to be too short or too long) rather than the Chinese character support.

**Comment by Chocobozzz** [comment]
@imtube Check you are up to date with the `develop` branch.

**Comment by imtube** [comment]
@Green-Star  @Chocobozzz  Thank you for your help. I had input 1-5 Chinese characters, and it showed the same error. I will check it.

**Comment by imtube** [comment]
@Chocobozzz Can you please tell me how can I check my develop branch ? I'm using the latest peertube version.

**Comment by Green-Star** [comment]
You can run a `git fetch; git status` on your `develop` branch to see if you're up-to-date.

Also, `git rev-parse HEAD` should display the last commit of your repo. Be sure, it is the same id as the last commit id in `Chocobozzz/PeerTube`

**Comment by imtube** [comment]
@Green-Star Thank you! your guide is very detailed, but I still can't understand for now, let me research it.
