### ISSUE TITLE
Playlists not shown in Channel

### ISSUE THREAD

**Issue by xundeenergie** [Chocobozzz/PeerTube#5501]
### Describe the current behavior

I created a few playlists, made the "private" and gave them into a channel.
![Screenshot_20230101_173630](https://user-images.githubusercontent.com/5894829/210178156-81019180-390e-44b3-8ef7-c71c77967621.jpg)
when i go to the Channel and want to show the playlists in this channel, the overview is empty

![Screenshot_20230101_173654](https://user-images.githubusercontent.com/5894829/210178181-b7f9e2bf-883d-4f91-8edc-4beb227d0e8f.jpg)

### Steps to reproduce

1. Create Playlist
2. Add some Videos
3. Save playlist with permission "private" in channel
4. Go to Channel
5. Go to "Playlistsx instead of "Videos"
6. Playlistindex is empty

### Describe the expected behavior

Want to see my playlists in the Channel, also my private, when i'm logged in. 

When i'm not logged in, the private playlists should be invisible.

### Additional information

* PeerTube instance:
  * URL: https://kino.schuerz.at
  * Version: 5.0.0
  * NodeJS version: ?
  * Ffmpeg version: ?

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

These public channel pages only list public videos videos and playlists. So what you see is what people see. You can see all your playlists (including private ones) in `My library` -> `Playlists` in left menu.
