### ISSUE TITLE
Run spawned processes with lower I/O and CPU priority

### ISSUE THREAD

**Issue by emansom** [Chocobozzz/PeerTube#5503]
### Describe the problem to be solved

Currently, the  `ffmpeg`, `ffprobe`, `yt-dlp` long-running processes run with standard I/O and CPU priority. This may lead to higher latencies in other processes like the web interface and API, as well as the database if they are running on the same box.

### Describe the solution you would like

Running the `ffmpeg`, `ffprobe`, `yt-dlp` long-running processes with lower I/O and CPU priority. Some I/O and CPU schedulers on Linux can then use this information to ensure those processes won't disrupt the interactivity of other processes.

**Comment by Chocobozzz** [comment]
Hello,

We already use `nice` for ffmpeg commands: https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/constants.ts#L441
Do you have something else in your mind?

**Comment by emansom** [comment]
> Hello,
> 
> We already use `nice` for ffmpeg commands: https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/constants.ts#L441 Do you have something else in your mind?

Must've read over that code. That tackles the CPU part. 👍🏻 

For the I/O scheduling part, `ffmpeg` needs to be executed from [`ionice`](https://man.archlinux.org/man/ionice.1.en) with `-c 3` as argument passed to it.

It's probably better if this is abstracted away behind a `iopriority` option passed to `fluent-ffmpeg`.

I'll create a bug report and send a PR there.
