### ISSUE TITLE
Streams are not extracted correctly by yt-dlp

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#5504]
### Describe the current behavior

I'm watching some peertube videos with an utilitary that uses yt-dlp to extract the video. But very often, it extracts only a part of the video, making it stop too early. It may be because the manifest file doesn't fit.

### Steps to reproduce

1. Open kodi media center
2. Open the peertube link with sendtokodi

### Describe the expected behavior

Ability to watch the full video

### Additional information

* PeerTube instance:
  * URL: skeptikon.fr
  * Version: unknown
  * NodeJS version: unknown
  * Ffmpeg version: unknown

* Browser name, version and platforms on which you could reproduce the bug: not relevant

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I don't see how it's related to peertube? Please open the issue on yt-dlp or kodi.
