### ISSUE TITLE
In upgrade.sh, add a warning saying specific migration instructions can be found on changelog

### ISSUE THREAD

**Issue by Booteille** [Chocobozzz/PeerTube#5506]
### Describe the problem to be solved

I often see people forgetting to run migration scripts indicated in the changelog when upgrading their server.

### Describe the solution you would like

In the upgrade script, always show an indication saying they should check if migration instructions exist with a link to the releases page in big and yellow.

**Comment by Utopiah** [comment]
Indeed but IMHO it's more general than that, it also applies to Docker, cf https://github.com/Chocobozzz/PeerTube/issues/5457#issuecomment-1373909157

**Comment by Chocobozzz** [comment]
I added a message in the upgrade script in https://github.com/Chocobozzz/PeerTube/commit/b30ad9888f54e6b55f3b6ca6e73534227d4d401e
