### ISSUE TITLE
Add Icelandic to translatable languages in Weblate

### ISSUE THREAD

**Issue by sveinki** [Chocobozzz/PeerTube#5509]
### Describe the current behavior

Could you please Icelandic (is) to translatable languages in Weblate, the instance doesn't seem to have a complete list of locales.
Looks like you have been able to add new languages (such as Toki Pona #4987), would be grateful.

**Comment by Chocobozzz** [comment]
Hi,

I added it in https://weblate.framasoft.org/projects/peertube/angular/is/

Don't hesitate to comment this issue when translated strings will be ready! :)

**Comment by sveinki** [comment]
Hi,
Already translated 77% of the strings, emphasizing on strings facing a "normal user". Still some more to hunt down, but I think the interface would be more than usable at this stage.
Of course some modifications will be necessary once the translations come live.

**Comment by Chocobozzz** [comment]
Thanks for your contribution! I added Icelandic locale support in https://github.com/Chocobozzz/PeerTube/commit/166311358d82657a15520ef35cd99e4fb82ed56f

You'll be able to see it on https://peertube2.cpy.re/ in 24 hours

**Comment by sveinki** [comment]
Now up to 88% of strings, which I guess are nearly all visible strings for casual users. Did also some modifications on the strings present in the nightly. Would be nice to see an update live.

**Comment by sveinki** [comment]
OK, up to 95% of strings, just ~90 strings left, mostly corner cases during upload and admin stuff.
I think the Icelandic translations can go to production.

**Comment by Chocobozzz** [comment]
Hello,

Icelandic is already on production: https://peertube2.cpy.re/is

**Comment by sveinki** [comment]
Thanks, yes I saw it in Nightly, but I meant for distribution in next upgrade.
BTW: Saw one change in nightly; when in [About](https://peertube2.cpy.re/about/instance), the three headings "Instance - PeerTube - Network" are now glued together - they used to be separated as a sort of tab-headings.
![PeerTube-Nightly 2023-02-21 07-49-47](https://user-images.githubusercontent.com/14218967/220284321-405d80f3-139b-4f5b-8bf5-56073bd14646.png)
Should I repart it as a bug or is this just a temporary hitch?

**Comment by Chocobozzz** [comment]
> Thanks, yes I saw it in Nightly, but I meant for distribution in next upgrade

Everything in the nightly will be included in the next release

> Should I repart it as a bug or is this just a temporary hitch?

Temporary hitch :)
