### ISSUE TITLE
Add annotation support

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#551]
Hi there,
AFAIK, annotations on videos (like on Youtube, which are clickable areas on videos displayed on a certain time range, or just texts displayed also on a certain time range).

Possibly there are videojs plugins to answer to that need. I found this one, but it looks like it is not working currently and I am afraid it is not maintained anymore:
https://github.com/spchuang/videojs-markers

Florent

**Comment by benrob0329** [comment]
It is worth noting that end-cards and "i bubbles" are what people use nowadays, which seem to be abused a lot less than YouTube's old annotations.

**Comment by bachrc** [comment]
It is not because a minority seem to abuse this functionality on their videos that everyone should be penalized. I think that this is a great functionality in order to make the video more interactive.

**Comment by BO41** [comment]
>  I am afraid it is not maintained anymore:
> https://github.com/spchuang/videojs-markers

seems more or less maintained.

https://github.com/contently/videojs-annotation-comments was updated more recently and seems to have more features

**Comment by Chocobozzz** [comment]
Implemented in https://framagit.org/framasoft/peertube/official-plugins/-/tree/master/peertube-plugin-video-annotation (will be available in peertube 2.4)
