### ISSUE TITLE
After upgrade to 5.0.1, videos not loading in PeerTube page, but playing normally through embeds

### ISSUE THREAD

**Issue by lstamellos** [Chocobozzz/PeerTube#5512]
### Describe the current behavior

After doing an upgrade from v. 4.3.1 to 5.0.1 (carefully following the Important Notes from v. 5.0.0), videos do not play on PeerTube pages, but they do play in website pages where they are embedded.

It seeems that the player itself is being loaded in the PeerTube video page, but it does not play the video.

### Describe the expected behavior

Videos should be playing on PeerTube

### Additional information

* PeerTube instance:
  * URL: https://video.omniatv.com
  * Version: 5.0.1
  * NodeJS version: 18.12.1
  * Ffmpeg version: 4.4.2

* Browser name, version and platforms on which you could reproduce the bug: Same in all main browsers and recent versions of them.
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): https://omniatv.com/wp-content/uploads/var/peertube-log.tar.gz (storage/logs/peertube.log)

**Comment by Chocobozzz** [comment]
Hello,

Please test by disabling peertube plugins (`--no-plugins` option when running peertube)

**Comment by lstamellos** [comment]
Unbelievable that I missed that step in trying to debug. It works. Pfff! Sorry for wasting your time.

The culprit is the "tv-streaming" plugin (v. 1.1.4 - Chromecast and AirPlay support for PeerTube)

Thank you.

**Comment by DalekDave** [comment]
I encountered this issue as well, but it was indeed solved by uninstalling the "tv-streaming" plugin.
