### ISSUE TITLE
Encourage IPv6 hosting for PeerTube platforms and adjust FAQ

### ISSUE THREAD

**Issue by ffrediani** [Chocobozzz/PeerTube#5513]
### Describe the problem to be solved

On the PeerTube´s FAQ  there is a question about views (https://joinpeertube.org/faq#how-does-peertube-count-views).
it says that that "After giving a view, that IP address cannot add another view in the next hour.". However it is very common these days that many users are connected to the Internet behind a Broadband connection using a CGNAT IP Address, so the public IPv4 that reaches the hosted PeerTube server only sees a single IP address for multiple users which can be dozen of residential and/or commercial connections behind a single IPv4 address. Therefore it is necessary to get some extra data from that connection to consider it a single user. Something like the source port or something related to the fingerprint of user´s browser, otherwise the number of views to a view depending from where they are being accessed may be compromised and reduced to what it really is.

Despite that one things that can help people willing to host a PeerTube platform is to amend the FAQ encouraging them to enable IPv6 on their servers. Many hosting platforms that offer dedicated server or VPS deliver them with IPv6 enable so it is just a question of adding a AAAA record in the DNS along with the A record in order for the videos to be delivered via IPv6.
Furthermore the data delivery over IPv6 tends to be more efficient than IPv4 due to different reasons like the traffic not having to pass through a sometimes bottlenecked CGNAT equipment which translates into a much better end-user experience.

Finally another part of the website you can add a detail that can encourage people to adopt IPv6 on their hosted PeerTube is on the index of instances (https://instances.joinpeertube.org/instances). Just add a column with a green check or a X for IPv6 support or not.

Thanks

### Describe the solution you would like

For the FAQ text a suggestion would be: "Your web browser sends a view to the server after 30 seconds of playback. If a video is less than 30 seconds in length, a view is sent after 75% of the video duration. After giving a view, that IP address cannot add another view in the next hour. Views are buffered, so don't panic if the view counter stays the same after you watched a video. **We encourage those hosting their PeerTube to remember to enable IPv6 on their servers and add the necessary AAAA DNS record along with the A record in order to have a more accurate view count. Many hosting companies deploy their servers and VPS with IPv4 and IPv6 support which makes it easier to have it enabled on your PeerTube.**"

**Comment by Chocobozzz** [comment]
Hello,

Thanks for the explanations and the issue but we unfortunately don't have time/resources to also promote IPV6...

**Comment by ffrediani** [comment]
Hello
What kind of answer is this ? This clearly shows you haven't understood about what IPv6 is and how fundamental it is for the continuous and healthy growth of Internet. You, as a developer, may be thinking that IPv6 is just something cosmetic or 'nice to have' thing to be promoted and not something that changes in a positive way not only the way streaming flows better over IPv6 but the whole of Internet. Perhaps you ignore that over 40% of the whole of Internet traffic is already IPv6 and major companies as Google Facebook, Netflix, Akamai, Cloudflare, etc have already 100% IPv6 support and are treating it seriously.

I have explained an error you have on your understanding of counting a view for one single IP address. This may lead to an fatal undercounting specially in times where many big Broadband Service Providers are massively using CGNAT techniques. It is not just a question of a 'way to see' the issue, but that Peertube is counting views wrongly that way and that must be fixed, even for IPv4. Having IPv6 is just a way to improve this, but even not having any IPv6 this still has to be fixed because it is wrong the way it is counting views.

How can you say that adding an extra text to a FAQ spend time and resources to promote IPv6. It seems more an answer from someone that either didn't understand or doesn't want to do anything about because consider IPv6 unimportant or just something minor in this context. 

You may not wish to amend the text but you may not ignore how IPv6 works in this context and mainly that even considering IPv4 alone the view count based only on the source IPv4 is wrong and has to have some fix applied. Please try to seek better understanding and technical information before closing it so quickly.

**Comment by Chocobozzz** [comment]
> You, as a developer, may be thinking that IPv6 is just something cosmetic or 'nice to have' thing to be promoted

I don't. Me and by extension Framasoft are completely aware of IPv6 implications.

> I have explained an error you have on your understanding of counting a view for one single IP address

We already know that. Views in PeerTube had never been an accurate metric because of the trade off we chose between measurement accuracy and falsification.

> How can you say that adding an extra text to a FAQ spend time and resources to promote IPv6.

We never considered IPv6 usage as "minor". But you want to promote IPv6 talking about DNS in a section that explain how PeerTube counts views to **viewers**. We want the FAQ to use simple terms to not scare people without technical knowledge that discover PeerTube. Finding the appropriate place to put this kind of text, maintaining it, maybe translating it while keeping guides/explanations concise requires time we don't have. For example I would see instead a section in the FAQ explaining the good practices when creating the PeerTube, that would include IPv6 explanations among other things.

As a side note, PeerTube is compatible out of the box with IPv6 and we already provide in our template the configuration to easily configure PeerTube to use IPv6: https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube#L24

**Comment by ffrediani** [comment]
The suggestion I have to add that to the FAQ text was one of the ways to also improve this metric for measurement accuracy and falsification given that dozen of thousand of users worldwide would be genuinely identified as a single user, but of course that is not the only measures to be taken in that way like fingerprint and it has to be considered further, but why not starting from one that is unequivocal ? The text was just a suggestion and could be shorter as well, the idea was just to mention to people have it enabled give it improves a Peertube feature in that sense. Just that. Perhaps it can go anywhere else still, agree.

Having a column showing IPv6 support on https://instances.joinpeertube.org/instances seemed a tiny and very discrete but interesting way to have those willing to have their instances there to have it enabled beforehand brining a better experience to users.

The idea to have it on configuration template is good either.
Thanks for answering with more details and interest.

**Comment by RJGhugo** [comment]
After moving from **IPv4/IPv6 Dual Stack** to **IPv6 only**, I am not able to run my Peertube Instance anymore.

Any help here?

**Comment by ffrediani** [comment]
It may be the case that some components of Peertube check content on IPv4-only destinations and is unable to do on Peertube IPv6-only hosts. It would be worth to check what are these destinations FQDNs and find out of why any of them don't have IPv6 enable, if it is possible to enable or even move it to another hosting that can support or have IPv6 enabled.
This may be more likely on some CDNs that host .js objects and similar stuff.

You can also have a NAT64 connection to your IPv6-only Peertube which will be able to reach IPv4-only destinations but that will not be the best solution which is always adding IPv6 support where it doesn't exist.
