### ISSUE TITLE
In release 5.0.1, the extended list of trend pages disappeared

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5514]
### Describe the current behavior

In release 5.0.1, the extended list of trend pages that you added recently in nightly builds stopped working

![1](https://user-images.githubusercontent.com/11453567/211135373-b2304c76-1324-4dfa-b453-f623e46803db.jpg)

For example, in the nightly build 5.0.0-nightly-2022-12-20 this feature has already been added and worked

![2](https://user-images.githubusercontent.com/11453567/211135396-1e43293d-97a8-48af-826c-49604ccae92f.jpg)

### Additional information

* PeerTube instance:
  * URL: https://peervideo.ru
  * Version: 5.0.1

**Comment by Chocobozzz** [comment]
Hello,

5.0.1 only include hotfixes where nightly build can contain new developments.
