### ISSUE TITLE
Comment option for synchronization

### ISSUE THREAD

**Issue by Vertux** [Chocobozzz/PeerTube#5515]
### Describe the problem to be solved

In addition to #5461 it would be nice to have a checkbox to disable comments for channel synchronization - like that:

<img width="866" alt="Bildschirm­foto 2023-01-07 um 19 56 47" src="https://user-images.githubusercontent.com/10457918/211166554-ec90389c-726f-4657-9986-a6ccba7d5911.png">

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/5265
