### ISSUE TITLE
Support live streaming from third part

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5517]
### Describe the problem to be solved

We use a CDN for caching our regular video streams. Since live streams are harder to cache we want to use a third part streaming software to keep it scalable without putting all the burden on our servers. 

### Describe the solution you would like

We'd like to give plugins the ability to play HLS streams in PeerTubes video player. From a user perspective it shouldn't be any difference, the only twist is that the files are hosted on a different server.

We've been able to do this by doing the following changes in PeerTube in a fork:
* StreamingPlaylist models functions getMasterPlaylistUrl doesn't replace the URL for lives.
* Disabling segmentValidator (#5240)

Since those solutions are specific for our narrow use case I'm wondering if we can find a more general solution.

Disabling segmentValidator should be possible to solve by just be able to disable p2p with a plugin filter. The URL for master playlist is a bit more tricky to get a good solution for. @Chocobozzz can't we just rely on the playlist URL in the database?

**Comment by Chocobozzz** [comment]
Hello,

You cannot use a plugin filter to replace the master playlist URL from the server? Or I think you can also replace this from client hooks that alter player options

**Comment by Chocobozzz** [comment]
Ping @kontrollanten
