### ISSUE TITLE
Programmatically import video from url into a plugin

### ISSUE THREAD

**Issue by geco** [Chocobozzz/PeerTube#5521]
### Describe the problem to be solved

Hi @Chocobozzz, i'm trying to import a video file from an url inside a plugin using the 'api/v1/videos/upload' rest api.
Can you please help me with a simple example on how to do it?
I've tried different methods (axios, superagent, plain https, streams) but all are failing.

Thank you in advance
Best regards

**Example that was working on peertube v4 (inside main.js server side plugin):**
(stream is a stream retrieved from an url "streamingUrl" that point to a mp4 file with axios get responseType stream)

const res = await axios.get(encodeURI(streamingUrl), {
  responseType: 'stream'
});
const stream = res.data;
const size = parseInt(res.headers['content-length'], 10);

  const formData = new FormData();
  formData.append('waitTranscoding', 'true');
  formData.append('channelId', channelId);
  formData.append('name', name);
  formData.append('videofile', stream, {
    knownLength: size,
    filename: 'video.mp4',
    contentType: 'video/mp4',
  });
  const headers = {
    Authorization: 'Bearer ' + access_token,
    ...formData.getHeaders(),
    'Content-Type': "multipart/form-data"
  };

await axios.post(
    `${serverUrl}/api/v1/videos/upload`, 
    formData,
    {
      headers,
      maxBodyLength: 10 * 1024 * 1024 * 1024, // 10 GB
      maxContentLength: 10 * 1024 * 1024 * 1024, // 10 GB

    }
  ); 

The code hangs up and finally nodejs crashes with out of memory (peertube v5, this wasn't happening on peertube v4)

### Describe the solution you would like

An example code snippet, thank you so much in advance

**Comment by Agorise** [comment]
yeah imports worked great in peertube v4.2.2 but with peertube v5 all imports have totally died. what changed? maybe @Chocobozzz or one of the core guys can shed some light on this.
