### ISSUE TITLE
text very thin on epiphany

### ISSUE THREAD

**Issue by www-cat** [Chocobozzz/PeerTube#5522]
### Describe the current behavior

![tilvids homepage with text appearing very light](https://user-images.githubusercontent.com/112013524/211672186-5e9fe018-8aa3-4a2c-ab1d-e3434da6fd06.png)

### Steps to reproduce

1. open website

### Describe the expected behavior

Text is regular, as in Firefox

### Additional information

* PeerTube instance:
  * URL: tilvids.com

* Browser name, version and platforms on which you could reproduce the bug:
* Epiphany 43.0

**Comment by Chocobozzz** [comment]
Hi,

I think it's an epiphany issue with woff2 variable fonts (which is supposed to support) :thinking:

**Comment by Chocobozzz** [comment]
Closing as this doesn't seem to be a peertube bug
