### ISSUE TITLE
Nginx config for setup with remote reverse proxy

### ISSUE THREAD

**Issue by dausruddin** [Chocobozzz/PeerTube#5524]
### Describe the problem

Hi.

When looking at the Peertube [configuration file](https://github.com/Chocobozzz/PeerTube/blob/cdd3cef91152c72eb14427427c54be1cb63744f7/config/production.yaml.example#L46), it seems that Peertube support remote reverse proxy natively.
But when I try to set it up, I find that it is quite hard to make it work, and there is no documentation for it.

Currently I lose optimization rules such as https://github.com/Chocobozzz/PeerTube/blob/cdd3cef91152c72eb14427427c54be1cb63744f7/support/nginx/peertube#L178 and https://github.com/Chocobozzz/PeerTube/blob/cdd3cef91152c72eb14427427c54be1cb63744f7/support/nginx/peertube#L188 since I connect to port 9000 directly on remote proxy server. Since those optimization rules are for local files, I had to disable them on remote reverse proxy server.

I had an idea where I run Nginx on both server, but something always broken since it is much complicated.

My request is, it would be nice if we have official recommended Nginx config for remote proxy setup with best optimization implemented to help people like me.

Thank you!

### Additional information

* PeerTube instance URL:
* PeerTube version: v5.0.1
* NodeJS version: v16.19.0

**Comment by Chocobozzz** [comment]
Hello,

Thanks for the issue but unfortunately we don't have time to maintain an additional nginx template for remote configurations. Removing these blocks and having peertube on another server should work. These optimizations are interesting, but not mandatory as PeerTube can serve static files without too much overhead.
