### ISSUE TITLE
Error "RangeError: data is too long" while uploading a multipart video transcode to Object Storage

### ISSUE THREAD

**Issue by vincib** [Chocobozzz/PeerTube#5525]
### Describe the current behavior

We tried to upload a video on a peertube 5.0.1 using object storage on a minio s3 server

the upload failed with the following error in the peertube log : 

```
Job: 9 Type: move-to-object-storage Processed on 12/01/23 15:27:26,179 Finished on -
--
{   "videoUUID": "6551ddbc-4d17-4599-8e78-f74b929eab06",   "isNewVideo": false,   "previousVideoState": 8 }

RangeError: data is too long
     at Hash.update (node:internal/crypto/hash:109:22)
     at Hash.update (/var/www/davduf/versions/peertube-v5.0.1/node_modules/@aws-sdk/hash-node/dist-cjs/index.js:12:19)
     at getPayloadHash (/var/www/davduf/versions/peertube-v5.0.1/node_modules/@aws-sdk/signature-v4/dist-cjs/getPayloadHash.js:18:18)
     at SignatureV4.signRequest (/var/www/davduf/versions/peertube-v5.0.1/node_modules/@aws-sdk/signature-v4/dist-cjs/SignatureV4.js:96:71)
     at processTicksAndRejections (node:internal/process/task_queues:96:5) 
```

On the s3 server side, we have : 

```
91.194.60.186 - - [12/Jan/2023:15:27:34 +0100] "POST /streaming-playlists/hls/6551ddbc-4d17-4599-8e78-f74b929eab06/0bafeefd-f2d8-4a4e-a141-8654ed84c9c4-1080-fragmented.mp4?uploads=&x-id=CreateMultipartUpload HTTP/1.1" 200 420 "-" "aws-sdk-js/3.210.0 os/linux/5.10.0-0.bpo.12-amd64 lang/js md/nodejs/16.15.1 api/s3/3.210.0" davduf.s3-1.octopuce.fr 912
91.194.60.186 - - [12/Jan/2023:15:27:42 +0100] "PUT /streaming-playlists/hls/6551ddbc-4d17-4599-8e78-f74b929eab06/0bafeefd-f2d8-4a4e-a141-8654ed84c9c4-1080-fragmented.mp4?partNumber=2&uploadId=NjBlYTY4OWItNDRiMC00OWEwLTkwZWEtYTNlODRlZGYxMGEyLjhkMDcxM2Q2LTlhOWQtNDQ1My05ZDE1LTBiNzlmZGE0MjdiZg&x-id=UploadPart HTTP/1.1" 200 25 "-" "aws-sdk-js/3.210.0 os/linux/5.10.0-0.bpo.12-amd64 lang/js md/nodejs/16.15.1 api/s3/3.210.0" davduf.s3-1.octopuce.fr 230408225
```

(the last field is the number of uploaded bytes to the s3 server from the peertube) 200 is the returned code, so it look fine on the s3 side

### Steps to reproduce

1. configure a peertube 5.0.1 with a remote minio s3 server 
2. upload a big video
3. it doesn't work, the message appears in the peertube error log.

### Describe the expected behavior

the video should be uploaded to s3 using multipart upload 

### Additional information

* PeerTube instance:
  * URL: https://video.davduf.net
  * Version: 5.0.1
  * NodeJS version: 16.15.1
  * Ffmpeg version: 5.1.1-static

**Comment by vincib** [comment]
okay, we found a way to make it work : 

we had 2GB on this configuration key, we put it down to 100MB and it's working : 

```
  # Maximum amount to upload in one request to object storage
  max_upload_part: 100MB

```

**Comment by Chocobozzz** [comment]
I added a warning in case of too big value in https://github.com/Chocobozzz/PeerTube/commit/1f6dd0084485e10623aeb222f1429edf30e5f823
