### ISSUE TITLE
Visibility issues with dark theme on various pages

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#5526]
### Describe the current behavior

There are a number of issues with the Peertube's dark theme. Here are some screenshots showing the problems, with a text description to accompany each one:

Login and Account Creation pages:

The 4 screenshots below show some visibility / legibility issues when using the Peertube dark theme in the login page and the account creation pages:

![Display problems with dark theme on login page](https://user-images.githubusercontent.com/64964084/212164725-97dfce11-dbeb-47fd-99ab-79ff1274daa5.png)

![Display problems with dark theme on account creation pages #1](https://user-images.githubusercontent.com/64964084/212164509-e4b6a88a-2359-4087-a213-e587512f6f23.png)

![Display problems with dark theme on account creation pages #2](https://user-images.githubusercontent.com/64964084/212164589-04bb5254-567d-4c71-948e-0c6ec6c7e3bb.png)

![Display problems with dark theme on account creation pages #3](https://user-images.githubusercontent.com/64964084/212164653-ce8a984c-db03-4ec2-9b7b-f4773611d7c1.png)

Styling inconsistency on keyboard shortcuts page when dark theme is in use:

When the dark theme is used, it would be nice if the Keyboard shortcuts page  did not have a solid white background. IMHO, it would be better if it had a darkish background with partial opacity, and white lettering / buttons.

![Keyboard shortcuts overlay in dark theme has white background (better inverted and partial opacity)](https://user-images.githubusercontent.com/64964084/212165079-048c6b16-9f88-4d75-84de-db9f67fd435d.png)

Dropdown menus have black dropdown arrow on dark grey:

When the dark theme is used, all dropdown menus have a black down arrow on a dark gray background. The arrow should be the same color as the text (white or light gray), You can see this in the screenshot below:

![Black dropdown buttons on dark gray with all dropdown menus](https://user-images.githubusercontent.com/64964084/212168470-fb705182-dedd-4388-9e43-5d532473472d.png)

When the dark theme is used, all secondary buttons have white text on a light gray background, and are difficult to read. IMHO, it would be better if the text was black: 

![Secondary buttons have white text on light gray background - poor visibility](https://user-images.githubusercontent.com/64964084/212168274-aede875e-c4fd-4600-b6de-5bafed3b2f94.png)

Thank you for all your work on Peertube! :) Hope this helps! :)

### Steps to reproduce

1. Visit the mentioned pages with the dark theme selected (dark theme is the default on Dalek Zone)

### Describe the expected behavior

See above.

### Additional information

* PeerTube instance: Dalek Zone
  * URL: https://dalek.zone
  * Version: 5.0.1
  * NodeJS version:  v16.19.0
  * Ffmpeg version:  4.2.7

* Browser name, version and platforms on which you could reproduce the bug: Firefox and Chrome on Ubuntu Linux and Microsoft Windows

**Comment by Kinuseka** [comment]
Hi also include this issue 
Unliked:
![image](https://user-images.githubusercontent.com/66762783/212280908-0478f67d-0c89-4645-80aa-b1b5cde9d90c.png)

Liked:
![image](https://user-images.githubusercontent.com/66762783/212280944-c22dfd4d-33b1-49bc-86af-6d8b4295db8d.png)

Have a very hard visibility differentiating between the two. A better solution is to shade the Liked button based on the color theme of the instance ` --mainColor`

**Comment by Chocobozzz** [comment]
@Booteille has made some improvements on the dark theme (I'll release a new version in a few hours): https://framagit.org/framasoft/peertube/official-plugins/-/merge_requests/20

Please open official theme/plugin issues on https://framagit.org/framasoft/peertube/official-plugins/-/issues
