### ISSUE TITLE
Adding a robots.txt file

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#553]
It would be nice to include a robots.txt file in peertube. And offer to configure if the instance is allowed or not (to differenciate tests and productions servers

Best regards,
J.

**Comment by sinemageorgia** [comment]
I have already uploaded 1300 movies to my instance. 2 terabytes. I have had it on for 4 months and it is not indexing the site. I want to change the robot. How can I fix it?

**Comment by Chocobozzz** [comment]
> I have already uploaded 1300 movies to my instance. 2 terabytes. I have had it on for 4 months and it is not indexing the site. I want to change the robot. How can I fix it?

Did you use Google search console to upload the peertube sitemap? (https://peertube.example.com/sitemap.xml)
