### ISSUE TITLE
YouTube Synchronisation Not Working with Postgres Error

### ISSUE THREAD

**Issue by MrSpuddy** [Chocobozzz/PeerTube#5533]
### Describe the current behavior

When attempting to import all videos of a YouTube channel (or when a new one is uploaded), the synchronisation quickly fails with an error code identical to the below one.

{
  "err": {
    "stack": "Error: WHERE parameter \"targetUrl\" has invalid \"undefined\" value\n    at PostgresQueryGenerator.whereItemQuery (/var/www/peertube/versions/peertube-v5.0.1/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1693:13)\n    at /var/www/peertube/versions/peertube-v5.0.1/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1684:25\n    at Array.forEach (<anonymous>)\n    at PostgresQueryGenerator.whereItemsQuery (/var/www/peertube/versions/peertube-v5.0.1/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1682:35)\n    at PostgresQueryGenerator.getWhereConditions (/var/www/peertube/versions/peertube-v5.0.1/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2025:19)\n    at PostgresQueryGenerator.selectQuery (/var/www/peertube/versions/peertube-v5.0.1/node_modules/sequelize/lib/dialects/abstract/query-generator.js:954:28)\n    at PostgresQueryInterface.select (/var/www/peertube/versions/peertube-v5.0.1/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:59)\n    at Function.findAll (/var/www/peertube/versions/peertube-v5.0.1/node_modules/sequelize/lib/model.js:1134:47)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Function.findOne (/var/www/peertube/versions/peertube-v5.0.1/node_modules/sequelize/lib/model.js:1228:12)",
    "message": "WHERE parameter \"targetUrl\" has invalid \"undefined\" value"
  }
}

### Steps to reproduce

1. Attempt to synchronise YouTube channel, for example “https://www.youtube.com/@macaddress” (without quotations).
2. Refresh page to see synchronisation has failed.

### Describe the expected behavior

The videos begin to be imported successfully.

### Additional information

* PeerTube instance:
  * URL: https://peer.lukeog.com
  * Version: v5.0.1 (error also occurred on v5.0.0)
  * NodeJS version: 8.19.3
  * Ffmpeg version: v4.2.7

* Browser name, version and platforms on which you could reproduce the bug: Occurs regardless of browser, so any will do.
* Link to browser console log if relevant: N/A
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): Above

**Comment by Chocobozzz** [comment]
Hello,

Do you use `yt-dlp` or `youtube-dl`? Can you provide more log in particular debug logs when the import starts?

**Comment by MrSpuddy** [comment]
I'm using yt-dlp, appropriate section in the config:
# Classic HTTP or all sites supported by youtube-dl https://rg3.github.io/youtube-dl/supportedsites.html
    http:
      # We recommend to use a HTTP proxy if you enable HTTP import to prevent private URL access from this server
      # See https://docs.joinpeertube.org/maintain-configuration?id=security for more information
      enabled: false

      youtube_dl_release:
        # Direct download URL to youtube-dl binary
        # Github releases API is also supported
        # Examples:
        #   * https://api.github.com/repos/ytdl-org/youtube-dl/releases
        #   * https://api.github.com/repos/yt-dlp/yt-dlp/releases
        #   * https://yt-dl.org/downloads/latest/youtube-dl
        url: 'https://yt-dl.org/downloads/latest/youtube-dl'

        # Release binary name: 'yt-dlp' or 'youtube-dl'
        name: 'yt-dlp'

        # Path to the python binary to execute for youtube-dl or yt-dlp
        python_path: '/usr/bin/python3'

      # IPv6 is very strongly rate-limited on most sites supported by youtube-dl
      force_ipv4: false



Import Debug Logs:
{"level":"info","message":"Video import job for channel \"Main root channel\" with url \"https://www.youtube.com/channel/UCfOfMrhJXwexPSxWalQV6Vg\" created.","label":"peer.lukeog.com:443","timestamp":"2023-01-13T08:46:52.545Z"}
{"tags":["http"],"level":"info","message":"51.19.93.222 - - [13/Jan/2023:08:46:52 +0000] \"POST /api/v1/video-channels/root_channel/import-videos HTTP/1.0\" 204 - \"https://peer.lukeog.com/my-library/video-channel-syncs\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15\"","label":"peer.lukeog.com:443","timestamp":"2023-01-13T08:46:52.547Z"}
{"level":"info","message":"Processing video channel import in job 13.","label":"peer.lukeog.com:443","timestamp":"2023-01-13T08:46:52.550Z"}
{"message":"Starting importing videos from external channel \"https://www.youtube.com/channel/UCfOfMrhJXwexPSxWalQV6Vg\" to \"Main root channel\" ","level":"info","label":"peer.lukeog.com:443","timestamp":"2023-01-13T08:46:52.587Z"}
{"tags":["http"],"level":"info","message":"51.19.93.222 - - [13/Jan/2023:08:46:55 +0000] \"GET /my-library/video-channel-syncs HTTP/1.0\" 200 12853 \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15\"","label":"peer.lukeog.com:443","timestamp":"2023-01-13T08:46:55.852Z"}
{"tags":["http"],"level":"info","message":"51.19.93.222 - - [13/Jan/2023:08:46:55 +0000] \"GET /manifest.webmanifest?7dcb0cf4c6330ac74e84ca05eb230991f88d68f8 HTTP/1.0\" 200 906 \"https://peer.lukeog.com/my-library/video-channel-syncs\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15\"","label":"peer.lukeog.com:443","timestamp":"2023-01-13T08:46:55.990Z"}
{"tags":["http"],"level":"info","message":"51.19.93.222 - - [13/Jan/2023:08:46:56 +0000] \"GET /api/v1/oauth-clients/local HTTP/1.0\" 304 - \"https://peer.lukeog.com/my-library/video-channel-syncs\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15\"","label":"peer.lukeog.com:443","timestamp":"2023-01-13T08:46:56.028Z"}
{"tags":["http"],"level":"info","message":"51.19.93.222 - - [13/Jan/2023:08:46:56 +0000] \"GET /api/v1/users/me HTTP/1.0\" 304 - \"https://peer.lukeog.com/my-library/video-channel-syncs\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15\"","label":"peer.lukeog.com:443","timestamp":"2023-01-13T08:46:56.139Z"}
{"tags":["http"],"level":"info","message":"51.19.93.222 - - [13/Jan/2023:08:46:56 +0000] \"GET /api/v1/config/about HTTP/1.0\" 304 - \"https://peer.lukeog.com/my-library/video-channel-syncs\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15\"","label":"peer.lukeog.com:443","timestamp":"2023-01-13T08:46:56.236Z"}
{"tags":["http"],"level":"info","message":"51.19.93.222 - - [13/Jan/2023:08:46:56 +0000] \"GET /api/v1/config/ HTTP/1.0\" 304 - \"https://peer.lukeog.com/my-library/video-channel-syncs\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15\"","label":"peer.lukeog.com:443","timestamp":"2023-01-13T08:46:56.251Z"}
{"tags":["http"],"level":"info","message":"51.19.93.222 - - [13/Jan/2023:08:46:56 +0000] \"GET /api/v1/accounts/root/video-channel-syncs?start=0&count=10&sort=createdAt HTTP/1.0\" 200 400 \"https://peer.lukeog.com/my-library/video-channel-syncs\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15\"","label":"peer.lukeog.com:443","timestamp":"2023-01-13T08:46:56.299Z"}
{"level":"info","message":"Fetched 1 candidate URLs for sync channel root_channel.","label":"peer.lukeog.com:443","targetUrls":[null],"timestamp":"2023-01-13T08:46:58.380Z"}
{"err":{"stack":"Error: WHERE parameter \"targetUrl\" has invalid \"undefined\" value\n    at PostgresQueryGenerator.whereItemQuery (/var/www/peertube/versions/peertube-v5.0.1/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1693:13)\n    at /var/www/peertube/versions/peertube-v5.0.1/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1684:25\n    at Array.forEach (<anonymous>)\n    at PostgresQueryGenerator.whereItemsQuery (/var/www/peertube/versions/peertube-v5.0.1/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1682:35)\n    at PostgresQueryGenerator.getWhereConditions (/var/www/peertube/versions/peertube-v5.0.1/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2025:19)\n    at PostgresQueryGenerator.selectQuery (/var/www/peertube/versions/peertube-v5.0.1/node_modules/sequelize/lib/dialects/abstract/query-generator.js:954:28)\n    at PostgresQueryInterface.select (/var/www/peertube/versions/peertube-v5.0.1/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:59)\n    at Function.findAll (/var/www/peertube/versions/peertube-v5.0.1/node_modules/sequelize/lib/model.js:1134:47)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Function.findOne (/var/www/peertube/versions/peertube-v5.0.1/node_modules/sequelize/lib/model.js:1228:12)","message":"WHERE parameter \"targetUrl\" has invalid \"undefined\" value"},"level":"error","message":"Failed to import channel Main root channel","label":"peer.lukeog.com:443","timestamp":"2023-01-13T08:46:58.385Z"}

**Comment by Chocobozzz** [comment]
Can you run on your server using `yt-dlp` binary (in `/var/www/peertube/storage/bin`):

```
./yt-dlp --dump-json --flat-playlist --skip-download --playlist-reverse 'https://www.youtube.com/channel/UCfOfMrhJXwexPSxWalQV6Vg'
```

**Comment by MrSpuddy** [comment]
I had to grant execution permissions to the yt-dlp file (only rw for owner initally), but afterwards, it output:
{"_type": "url", "url": "https://www.youtube.com/@lukeogregory/videos?view=0&sort=dd&shelf_id=0", "ie_key": null, "title": "Uploads"}

Attempting to synchronise with the file executable returns the same postgresql error as before.

**Comment by Chocobozzz** [comment]
> I'm using yt-dlp, appropriate section in the config:

Where did you find this config? In `/var/www/peertube/config/production.yaml`? If no, please paste the same section from `production.yaml`

**Comment by MrSpuddy** [comment]
That is the section from production.yaml. Full section from /var/www/peertube/config/production.yaml:

import:
  # Add ability for your users to import remote videos (from YouTube, torrent...)
  videos:
    # Amount of import jobs to execute in parallel
    concurrency: 1

    # Set a custom video import timeout to not block import queue
    timeout: '2 hours'

    # Classic HTTP or all sites supported by youtube-dl https://rg3.github.io/youtube-dl/supportedsites.html
    http:
      # We recommend to use a HTTP proxy if you enable HTTP import to prevent private URL access from this server
      # See https://docs.joinpeertube.org/maintain-configuration?id=security for more information
      enabled: false

      youtube_dl_release:
        # Direct download URL to youtube-dl binary
        # Github releases API is also supported
        # Examples:
        #   * https://api.github.com/repos/ytdl-org/youtube-dl/releases
        #   * https://api.github.com/repos/yt-dlp/yt-dlp/releases
        #   * https://yt-dl.org/downloads/latest/youtube-dl
        url: 'https://yt-dl.org/downloads/latest/youtube-dl'

        # Release binary name: 'yt-dlp' or 'youtube-dl'
        name: 'yt-dlp'

        # Path to the python binary to execute for youtube-dl or yt-dlp
        python_path: '/usr/bin/python3'

      # IPv6 is very strongly rate-limited on most sites supported by youtube-dl
      force_ipv4: false

    # Magnet URI or torrent file (use classic TCP/UDP/WebSeed to download the file)
    torrent:
      # We recommend to only enable magnet URI/torrent import if you trust your users
      # See https://docs.joinpeertube.org/maintain-configuration?id=security for more information
      enabled: false

  # Add ability for your users to synchronize their channels with external channels, playlists, etc.
  video_channel_synchronization:
    enabled: true

    max_per_user: 5

    check_interval: 1 hour

    # Number of latest published videos to check and to potentially import when syncing a channel
    videos_limit_per_synchronization: 10

    # Max number of videos to import when the user asks for full sync
    full_sync_videos_limit: 1000

**Comment by Chocobozzz** [comment]
Hum I think I understood the issue.

You use `name: 'yt-dlp'` with `https://yt-dl.org/downloads/latest/youtube-dl` (`youtube-dl`). 
Use the default setting instead: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L572

It will download the latest `yt-dlp` which fixes some issues when downloading youtube videos. You can delete `yt-dlp` from `bin` directory to force a refresh and not wait the auto upgrade.

**Comment by MrSpuddy** [comment]
Yep, that fixed it, synchronisations appear to be working. I've annoyed I missed something that obvious. Thanks for your help!
