### ISSUE TITLE
Faulty button layout in video list

### ISSUE THREAD

**Issue by Vertux** [Chocobozzz/PeerTube#5536]
### Describe the current behavior

In the video list some update buttons look different (s. screenshot)

<img width="207" alt="Bildschirm­foto 2023-01-14 um 18 35 02" src="https://user-images.githubusercontent.com/10457918/212487932-e18881b8-27a2-41b0-b7a4-f9e8184c0824.png">

Same issue if I switch to german interface language:

<img width="241" alt="Bildschirm­foto 2023-01-14 um 19 06 02" src="https://user-images.githubusercontent.com/10457918/212488525-3e1143f8-007f-4c68-9d60-2cb48106495a.png">

As you can see, some buttons got no "Update" text on the button but beneath it.

### Steps to reproduce

1. Login Peertube
2. Choose "My library" --> "Videos"
<img width="258" alt="Bildschirm­foto 2023-01-14 um 18 38 07" src="https://user-images.githubusercontent.com/10457918/212487993-3d854cff-6dff-4d1a-8935-313fc229127d.png">
<img width="561" alt="Bildschirm­foto 2023-01-14 um 18 38 13" src="https://user-images.githubusercontent.com/10457918/212488001-75626dec-dcee-489e-b434-20402e2d2e54.png">

### Describe the expected behavior

All buttons in the video list should look the same.

### Additional information

* Firefox v108.0.2 (MacOS) and Safari Version 16.2 (18614.3.7.1.5)
* PeerTube instance:
  * Version: 5.0.1
  * NodeJS version: v16.19.0

  * Ffmpeg version: 5.1.1

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/55bd2e579385c302461be9d6169de3598512196c
