### ISSUE TITLE
Slow query: SELECT LocalVideoViewerModel

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5537]
### Describe the current behavior

A lot of these in the slow log (around 400-600 ms):

```
SELECT "id", "startDate", "endDate", "watchTime", "country", "uuid", "url", "videoId", "createdAt" 
FROM "localVideoViewer" AS "LocalVideoViewerModel" 
WHERE "LocalVideoViewerModel"."url" = '...' 
LIMIT 1;
```

### Additional information

* PeerTube instance:
  * Version: 4.3.1

**Comment by Chocobozzz** [comment]
Thanks, I forgot the index for this column. Fixed in https://github.com/Chocobozzz/PeerTube/commit/f008e9f3f34ed1724afd5e071c39ed931741acbc
