### ISSUE TITLE
User registration gets disabled before reaching 'Signup limit'

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#5538]
### Describe the current behavior

If I set the 'Signup limit' to 250 in Configuration / Basic in the admin interface, user signup actually gets disabled long before (at 172 registered users, in the attached screenshots.

Screenshot 1 shows how user registration is displayed as disabled in the About page:
 
![registration-bug-screenshot-1](https://user-images.githubusercontent.com/64964084/212539930-dc0235e8-5819-48ea-94fb-d81c953e1f1b.png)

Screenshot 2 shows that the 'Signup limit' is actually set to 250 in Configuration / Basic in the admin interface:

![registration-bug-screenshot-2](https://user-images.githubusercontent.com/64964084/212539973-92f5a556-b8a4-492b-abcb-c190f0439897.png)

Screenshot 3 shows that the current number of registered users is 172:

![registration-bug-screenshot-3](https://user-images.githubusercontent.com/64964084/212540061-b64c6078-2670-4025-8199-1e72180e976f.png)

### Steps to reproduce

1. See above explanation and screenshots
2. Set the 'Signup limit' to your desired number X
3. Wait and watch, until registration gets disabled long before reaching that number
4. Increase the 'Signup limit' by even 1 again enables registration, but not until reaching X

### Describe the expected behavior

When you set the 'Signup limit' to 250 (or whatever value), registration should not get disabled until the registered user base has reached exactly 250.

### Additional information

* PeerTube instance: Dalek Zone
  * URL: https://dalek.zone
  * Version: 5.0.1
  * NodeJS version: v16.19.0
  * Ffmpeg version: 4.2.7-0ubuntu0.1

* Browser name, version and platforms on which you could reproduce the bug: Firefox and Chrome on Ubuntu Linux 22.04 and Microsoft Windows 10

**Comment by Kinuseka** [comment]
this is also an observed behavior on my instance. 
18 users I set limit is 23 would disable it, I set it to 24 then I only have room for 1 user.

There is a discrepancy of -5 user on the setting to the actual count. It seems like on his case is a bigger discrepancy. But the noticeable common factor is that the it always stops at the 70% of the user_registered/user_limit

**Comment by Chocobozzz** [comment]
Thanks for the issue, fixed by https://github.com/Chocobozzz/PeerTube/commit/823e411fa6e2d66258fb7bc9e617a0822190273f
