### ISSUE TITLE
Syndicate the tags

### ISSUE THREAD

**Issue by yassinphilip** [Chocobozzz/PeerTube#554]
I had to move instances for performance issues, so now I have [a bunch of my videos on Exode](https://exode.me/accounts/808/videos), my previous instance, and [the new ones are on NSA](https://peertube.nsa.ovh/accounts/1379/videos), my new one ; that's a (very real) problem, that could be elegantly worked around with _tags_, either by using [a per-tag feed](https://github.com/Chocobozzz/PeerTube/issues/23#issuecomment-384333689) (bit overkill / heavy maybe) or by (KISSier) making the tags [searchable](https://github.com/Chocobozzz/PeerTube/issues/60), and eventually clickable.

That way all the videos could be listed / linked to on a single page, even though they are hosted on different instances.

**Comment by rigelk** [comment]
While the tag issue has already been identified, I don't understand how it's linked to your migration.

**Comment by yassinphilip** [comment]
It's not, at all, I was just providing context / use case ; You are right, it's a duplicate, closing.
