### ISSUE TITLE
Cannot update user description with CanvasBlocker extension

### ISSUE THREAD

**Issue by JacksonChen666** [Chocobozzz/PeerTube#5540]
### Describe the current behavior

If you click the "save" button for the user description, nothing happens.

This happens if you have the [CanvasBlocker extension](https://addons.mozilla.org/en-US/firefox/addon/canvasblocker/) enabled

### Steps to reproduce

1. Install [CanvasBlocker](https://addons.mozilla.org/en-US/firefox/addon/canvasblocker/)
2. Try to update user description
3. Click the "save" button
4. (nothing happens)

### Describe the expected behavior

Ideal should be able to click the "save" button and something should happen, like saving the user description, even with CanvasBlocker enabled.

### Additional information

* PeerTube instance: videos.jacksonchen666.com
  * URL: https://videos.jacksonchen666.com
  * Version: 5.0.1
  * NodeJS version: v16.18.1
  * Ffmpeg version: 5.1.2

* Browser name, version and platforms on which you could reproduce the bug: LibreWolf 108.0.1-1, macOS 13.1
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Do you have errors in you web browser logs?

**Comment by JacksonChen666** [comment]
Sorry, forgot about this. Version is still 5.0.1, but I can't reproduce this issue anymore.
