### ISSUE TITLE
If no category is assigned the video details show "Misc" as category

### ISSUE THREAD

**Issue by Vertux** [Chocobozzz/PeerTube#5541]
### Describe the current behavior

If you import a video with no category assigned, the video info shows "Misc" as a kind of "fake" category, but if click update to edit the video details, the category field is empty. That's very confusing and misleading.

### **Video details:**
<img width="461" alt="Bildschirm­foto 2023-01-16 um 21 44 57" src="https://user-images.githubusercontent.com/10457918/212764799-ea682508-a20f-4500-8f83-308c74fe1330.png">

### **When you click update it looks like that:**

<img width="370" alt="Bildschirm­foto 2023-01-16 um 21 33 49" src="https://user-images.githubusercontent.com/10457918/212765031-77cf64d0-4e27-4b64-9599-5102b78a7195.png">

### Steps to reproduce

see description above

### Describe the expected behavior

If no category is assigned the filed behind category should be blank or should show "None", but not "Misc", because it makes everyone think, that "Misc" is a real category, which is not.

### Additional information

* PeerTube instance:
  * Version: **5.0.1**

* Browser name, version and platforms on which you could reproduce the bug: **Firefox 108.0.2 macOS**

**Comment by DalekDave** [comment]
I noticed this, too.

What category number is 'Misc" ? It's not documented in the documentation...

**Comment by Chocobozzz** [comment]
Behaviour changed in https://github.com/Chocobozzz/PeerTube/commit/32fde390f465b9ceef9e49c4037acdacbe176d65

We now display "Unknown"
