### ISSUE TITLE
Recording of live cast truncated

### ISSUE THREAD

**Issue by retog** [Chocobozzz/PeerTube#5542]
### Describe the current behavior

When I stream into a normal or a regular recurring live, the recording is truncated. I don't know if the live view aborts as well.

### Steps to reproduce

1. choose "upload a video"/"go live"
2. enter the key in OBS
3. Stream
4. Wait for video to be available
5. notice that the video is truncated

### Describe the expected behavior

I expect everything to be in the video till I stop the streaming

### Additional information

* PeerTube instance: tv.farewellutopia.com
  * URL: https://tv.farewellutopia.com/w/nE68PgLBdSRLpeMBEa7vnb
  * Version: 5.0.1
  * NodeJS version: Included in docker image chocobozzz/peertube:production-bullseye
  * Ffmpeg version:Included in docker image chocobozzz/peertube:production-bullseye

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

The live is truncated or the video saved from the live is truncated?

**Comment by retog** [comment]
For the live viewer, the image freezes with a rotating wheel in the center. And while OBS seems to still be streaming, the truncated recording is published.

**Comment by Chocobozzz** [comment]
Please enable PeerTube debug logs (in config), retry the live and paste server logs

**Comment by retog** [comment]
I'm feeling stupid, when through the webinterface, the `.env`-file, but I don't see in what config I can set the log-level.

**Comment by Chocobozzz** [comment]
You can try `PEERTUBE_LOG_LEVEL=debug` in your `.env`

**Comment by retog** [comment]
No log entry relates to the recording. All log entries look similar to the following:

```
debug[2/11/2023, 5:33:37 PM] HTTP broadcast to https://[host]/inbox failed.

{
  "err": {
    "stack": "RequestError: connect EHOSTUNREACH 82.65.193.44:443\n    at ClientRequest.<anonymous> (/app/node_modules/got/dist/source/core/index.js:970:111)\n    at Object.onceWrapper (node:events:628:26)\n    at ClientRequest.emit (node:events:525:35)\n    at ClientRequest.origin.emit (/app/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n    at TLSSocket.socketErrorListener (node:_http_client:494:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)",
    "message": "connect EHOSTUNREACH [ip]:443",
    "name": "RequestError"
  }
}
``

**Comment by Chocobozzz** [comment]
Sorry for the late answer. It seems you enabled debug logs from the line your pasted. So you should also have info and debug logs coming from the live manager.

Can you stream a live to peertube, copy all log lines until the live is truncated and send them to me (by email for example, in my github profile)?

**Comment by retog** [comment]
Thanks, @Chocobozzz, for following up on this.

I've recorded several streams while collecting the logs, but unexpectedly the problem didn't occur again. Not sure what might have changed. Maybe the OBS Version.
