### ISSUE TITLE
"Publish" a Pre-encoded HLS package that is already on Object Storage

### ISSUE THREAD

**Issue by stevespaw** [Chocobozzz/PeerTube#5545]
### Describe the problem to be solved

Our Clients have plenty of local CPU/GPU to pre-encode the HLS. We could create a Standard "peertube" HandBrake or ffmpeg workflow to pre encode and upload these to S3. We would then "publish" in Peertube, to add meta data etc.

This would really allow scaling of transcoding options.
It would also be handy if we could have caption files in the same folder.

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/947
