### ISSUE TITLE
Videos in encoding queue not deleted when sync channe importl is deleted

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5547]
### Describe the current behavior

if I add a channel import with a lot of videos in queue to encode and after a little while I decide to delete the channel import from the list I can still see all queued videos from this channel still waiting to be encoded

### Steps to reproduce

1. Import a channel with a lot of videos to create an encoding queue
2. wait a little and then delete the channel import
3. list your videos section dans still see videos from the deleted channel

### Describe the expected behavior

when a channel is deleted so cleanup all videos waiting to be encoded and all other related stuff from the channel.

**Comment by Chocobozzz** [comment]
Hello,

Deleting a sync doesn't mean that you'll deleted videos previously synced. You need to manually delete them.

**Comment by ROBERT-MCDOWELL** [comment]
Hi @Chocobozzz , the main issue is when there are hundreds of videos synced I have to check the box of each, it took me 2 hours to delete them :(. if the user makes a channel mistake on a channel containing thousands of videos logically PeerTube should stop all processes and delete them which is more logical isn't it?

**Comment by Chocobozzz** [comment]
>  if the user makes a channel mistake on a channel containing thousands of videos logically PeerTube should stop all processes and delete them which is more logical isn't it?

It's difficult to know when the sync seems "too big". But you can adjust the `import.video_channel_synchronization.full_sync_videos_limit` setting.

>  I have to check the box of each

You couldn't use the admin -> overview -> videos table to check all videos at once?
