### ISSUE TITLE
bufferStalledError log Error

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5550]
### Describe the current behavior

I installed PeerTube 5.0.1, and uploaded several videos. My users see the videos mostly by their mobile phones. In the standard logs on the root administration page, I see a lot of below errors:

error[1/23/2023, 3:56:38 PM] Client log: HLS.js error: mediaError - fatal: false - bufferStalledError

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-A510F) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/19.0 Chrome/102.0.5005.125 Mobile Safari/537.36",
  "meta": "{\"data\":{\"type\":\"mediaError\",\"details\":\"bufferStalledError\",\"fatal\":false,\"buffer\":3.946666}}",
  "url": ****************
}

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

This error should just be a warning (network issue etc). This will be fixed in the next version by https://github.com/Chocobozzz/PeerTube/pull/5484

**Comment by paymanzafar1** [comment]
Thank you very much.
