### ISSUE TITLE
peertube-video-miniature should also accept shortUUID

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5552]
### Describe the problem to be solved

When writing the home page, we can use the `peertube-video-miniature` tag.
It accept an `uuid` attribute to specify which video to display.

But since there are shortUUID, the full UUID is hard to find. Before, we could copy it from the video url... But in recent Peertube version the url uses the shortUUID.
There is no more an easy way to get the full UUID of a video.

### Describe the solution you would like

So, it would be helpfull if `peertube-video-miniature` could also accept an `short-uuid` attribute.

Same for playlists and other special tags.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/647c2b7d0448e68d8c8ade52d9568e9b33f8638d
