### ISSUE TITLE
Change the default minimum play time (30 Secs)

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5554]
### Describe the problem to be solved

It is a good feature if the administrator will be able to change the default minimum playing time (30 Secs) for a video to increase its views count. 

### Describe the solution you would like

Define a new setting in the production.yaml file to set the default minimum play time for a video to increase its views count.

**Comment by Chocobozzz** [comment]
I'm not in favour of this idea because it would create inconsistencies between the view counter of a local video compared to a remote one.

**Comment by paymanzafar1** [comment]
Yes it is correct. But I need this feature for a standalone instance without any follower. 
If I know where can I change it is the source code, I will change and compile the code for my own usage.

**Comment by Chocobozzz** [comment]
Hi,

Sorry for the late answer. You can change this behaviour in https://github.com/Chocobozzz/PeerTube/blob/develop/server/lib/views/shared/video-views.ts#L62
