### ISSUE TITLE
Mention a user is broken

### ISSUE THREAD

**Issue by xundeenergie** [Chocobozzz/PeerTube#5557]
### Describe the current behavior

When i write a comment on a video and mention a user from somewhere else, the mentioning is broken.

When i mention the user @jakob@soc.schuerz.at it will create this comment

![Bildschirmfoto von 2023-01-25 17-36-15](https://user-images.githubusercontent.com/5894829/214622129-4ba08cef-9071-443f-9594-64a2ba4c148e.png)

The first part "@jakob@soc" is linked to https://kino.schuerz.at/services/redirect/accounts/soc
the second part "schuerz.at" is linked to http://schuerz.at/

So this ist really broken into to parts, which are both wrong.
And the mentioned user gets no notification.

### Steps to reproduce

1. create a comment on a video

### Describe the expected behavior

I expect that i get a mention for an activitypub-user from a remote instance and this user gets notificated about this mention.

### Additional information

* PeerTube instance:
  * URL: https://kino.schuerz.at 
  * Version: 5.0.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox Desktop and Android
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by xundeenergie** [comment]
When i make a mention in a video from friendica, the mention is ok then shown on peertube!

**Comment by DalekDave** [comment]
I confirm this on Dalek Zone. Please see the screenshot below. I mentioned someone, and you can see the mention is incorrectly displayed and linked:


![2023-01-25 23_02_35-Window](https://user-images.githubusercontent.com/64964084/214690333-29652376-f07b-4a36-922b-3b97291d8466.png)

**Comment by xundeenergie** [comment]
`Thanks for this amazing software! :)`

Oh yes!

For me, Peertube is the most mature Software in the whole Fediverse.

It's great. I love my Instance with your Peertube 😊

**Comment by Chocobozzz** [comment]
Thanks :)

This issue should be fixed by https://github.com/Chocobozzz/PeerTube/commit/e81d45b4cb6462029661a525315529b02261722d
