### ISSUE TITLE
Incorrect number of unique views & views

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5562]
### Describe the current behavior

We have a mobile application, and we publish a video every week for our users. Previously we used a public video sharing site to publish our video. Last week, I installed PeerTube, and used this software to publish our video. But we saw a considerable reduction in the number of views. Here is the stats for this video: 

![full1](https://user-images.githubusercontent.com/91053236/215256511-ca0a8cde-df1a-462b-8eb3-59cac0193169.jpg)

I installed the GoAccess software to read the Nginx access logs, and the result is as below:

![full](https://user-images.githubusercontent.com/91053236/215256351-55ceed0f-b27a-4ce0-8d5d-58817ad90a4d.jpg)

You see the huge difference between the video stats with the GoAccess report.

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by DalekDave** [comment]
I confirm this issue on https://dalek.zone.

**Comment by paymanzafar1** [comment]
We uploaded a new video, and used autoplay=1 & muted=1 in its URL to autoplay the video even in Chrome. Here are the new status after 2 hours:

![goaccess-31-Jan](https://user-images.githubusercontent.com/91053236/215711751-794989b0-9095-4c5f-b405-cb16d0631318.jpg)

The video URL was called 3608 times, and the notifyUserIsWatching is called 2670 times. But this video views count is as below:

![peertube-1](https://user-images.githubusercontent.com/91053236/215712297-66f8f79f-ae16-477a-8fd9-ab2feb8c425e.jpg)

It is a very big issue. Please help.

**Comment by paymanzafar1** [comment]
> 

Yes peertube increment the views after 30 seconds, but the unique viewer counter must match the Nginx stats.

**Comment by paymanzafar1** [comment]
We have a lot of following error, not yours:

error[2/7/2023, 2:40:31 PM] Client log: HLS.js error: mediaError - fatal: false - bufferStalledError

{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Linux; Android 12; SAMSUNG SM-A125F) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/19.0 Chrome/102.0.5005.125 Mobile Safari/537.36",
  "meta": "{\"data\":{\"type\":\"mediaError\",\"details\":\"bufferStalledError\",\"fatal\":false,\"buffer\":17.002666}}",
  "url": "***********"
}

**Comment by Chocobozzz** [comment]
Hello,

 * I confirm the `bufferStalledError` error is a badly logged error (should not sent to the server)
 * A view is only taken into account after 30 seconds
 * A viewer don't have this limit, viewing the video during 5 seconds will be enough to increment this counter

**Comment by paymanzafar1** [comment]
Hello,
Thank you very much for your explanation. I am aware of the minimum play time (30 Sec) to increase the view count.
My problem is regarding the number of unique viewers which is very lower than the number of unique viewers logged by Nginx. As you see in the GoAccess reports.

**Comment by Chocobozzz** [comment]
Some web browser will still deny autoplay even if the video is muted. If you can't find errors related to views coming from the client unfortunately it's difficult to find the root cause of this "inconsistency".
What you can try is finding if the inconsistency increases a lot in goaccess between the `/embed` path and the `/views` endpoint on a particular device (maybe a specific ios version doesn't send views or something like that?)

**Comment by Chocobozzz** [comment]
It seems autoplaying muted videos is not supported on IOS. I created an issue: https://github.com/Chocobozzz/PeerTube/issues/5604

**Comment by paymanzafar1** [comment]
> Some web browser will still deny autoplay even if the video is muted. If you can't find errors related to views coming from the client unfortunately it's difficult to find the root cause of this "inconsistency". What you can try is finding if the inconsistency increases a lot in goaccess between the `/embed` path and the `/views` endpoint on a particular device (maybe a specific ios version doesn't send views or something like that?)

According to GoAccess reports, most of my users are using Android, and Chrome. So I do not think this is the source of my problem.

You mentioned that playing about 5 seconds will increment the unique viewer counter. Would you please let me know in which function you check this 5 Secs. playback?

**Comment by Chocobozzz** [comment]
> You mentioned that playing about 5 seconds will increment the unique viewer counter. Would you please let me know in which function you check this 5 Secs. playback?

 * https://github.com/Chocobozzz/PeerTube/blob/59a643aa5cf6775d27dfcc147b19c4537292d53c/client/src/assets/player/shared/peertube/peertube-plugin.ts#L180
 * https://github.com/Chocobozzz/PeerTube/blob/59a643aa5cf6775d27dfcc147b19c4537292d53c/client/src/assets/player/shared/peertube/peertube-plugin.ts#L194
 * https://github.com/Chocobozzz/PeerTube/blob/59a643aa5cf6775d27dfcc147b19c4537292d53c/client/src/assets/player/shared/peertube/peertube-plugin.ts#L207

**Comment by paymanzafar1** [comment]
> > You mentioned that playing about 5 seconds will increment the unique viewer counter. Would you please let me know in which function you check this 5 Secs. playback?
> 
>     * https://github.com/Chocobozzz/PeerTube/blob/59a643aa5cf6775d27dfcc147b19c4537292d53c/client/src/assets/player/shared/peertube/peertube-plugin.ts#L180
> 
>     * https://github.com/Chocobozzz/PeerTube/blob/59a643aa5cf6775d27dfcc147b19c4537292d53c/client/src/assets/player/shared/peertube/peertube-plugin.ts#L194
> 
>     * https://github.com/Chocobozzz/PeerTube/blob/59a643aa5cf6775d27dfcc147b19c4537292d53c/client/src/assets/player/shared/peertube/peertube-plugin.ts#L207

@Chocobozzz Thank you very much.

It arises another question. If every viewer has at-least 5 Seconds watching time, in the retention window, how is it possible to show the number of users with 1 to 5 Secs. watching time?
