### ISSUE TITLE
In a Channel page, channel description is cut off uncleanly, not either in full or cleanly abbreviated

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#5563]
### Describe the current behavior

In a user channel page, the description of the channel is not shown in full, and is limited uncleanly rather than either expanding the box and showing it in full or else abbreviating the description in a clean, attractive manner. Please see the screenshot below, which illustrates the issue:

![2023-01-28 12_44_43-Window](https://user-images.githubusercontent.com/64964084/215273607-b8b3c182-764f-42b7-9f89-047e9e655efe.png)

### Steps to reproduce

1. Create a channel and enter a channel Description that exceeds PeerTube's recommended length.
2. View the channel page.
3. The Description is not shown in full in the channel page; the "overflow" is uncleanly cut off.

### Describe the expected behavior

1. Display a recommended max length in the channel management page.
2. Cleanly display any description up to the recommended length.
3. Prevent the entry of a description longer than the max characters.

### Additional information

* PeerTube instance: Dalek Zone
  * URL: https://dalek.zone
  * Version: 5.0.1
  * NodeJS version: v16.19.0
  * Ffmpeg version: 4.2.7-0ubuntu0.1

* Browser name, version and platforms on which you could reproduce the bug: Firefox, Chrome and Edge on Windows 10, Firefox and Chrome on Ubuntu Linux 22.04

**Comment by Chocobozzz** [comment]
Hello,

It's related to your theme where `--channelBackgroundColor` is `transparent`. Set a real color instead
