### ISSUE TITLE
Broadcast message preview in admin interface Configuration / Basic page does not show preview of line breaks correctly

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#5564]
### Describe the current behavior

When you write a broadcast message in the admin interface Configuration page, any line breaks you insert in the text are not displayed properly in the preview box underneath. (Line breaks do display correctly in the final message published on the site.)
Please see the screenshot below: 

![2023-01-28 16_48_34-Window](https://user-images.githubusercontent.com/64964084/215274711-6805cb8b-8c7e-47a0-9909-c492ea02f010.png)

### Steps to reproduce

1. Go to the site admin interface, and go to the Configuration / Basic page
2. Enter a broadcast message (of "Info" type, for example).
3. Insert line breaks in the message, such as below:

`<br> <br/>`

4. Look at the preview box underneath, where you expect to see a proper preview of your message. The line break tags are shown as inline text, not replaced by line breaks in the preview.

### Describe the expected behavior

Permitted markdown tags inserted in the Message box should be appropriately displayed in the Preview box. 

### Additional information

* PeerTube instance: Dalek Zone
  * URL: https://dalek.zone
  * Version: 5.0.1
  * NodeJS version: v16.19.0
  * Ffmpeg version: 4.2.7-0ubuntu0.1

* Browser name, version and platforms on which you could reproduce the bug: Firefox, Chrome and Edge on Windows 10, and Firefox and Chrome on Ubuntu Linux 22.04.

**Comment by Chocobozzz** [comment]
Thanks, fixed by https://github.com/Chocobozzz/PeerTube/commit/cb38c9b9eaaf20abdb739553d7a3f1e1add8c604
