### ISSUE TITLE
99 notifications but not more?

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5566]
### Describe the current behavior

If there are more than 99 notifications maybe it should be 99+ to tell the user there are more than 99 notifications.

**Comment by Chocobozzz** [comment]
Thanks! Implemented in https://github.com/Chocobozzz/PeerTube/commit/587aa74ac3d8f2e1fdd8754d60c7a8c38ce30b88
