### ISSUE TITLE
OpenTelemetry metrics is disabled, but playback POSTs are being sent

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5567]
### Describe the current behavior

OpenTelemetry metrics is disabled by default as in the below image:

![opentelemetry](https://user-images.githubusercontent.com/91053236/215309986-9fccf54c-6456-450b-a375-d38700e6a18e.jpg)

But the browser is sending playback POSTs to server. Even when the video is stopped.

![playback](https://user-images.githubusercontent.com/91053236/215310080-69ebc93d-761f-4485-8058-dcc328cb313e.jpg)

These POSTs are also indicated in the Nginx access logs as below:
 
![playback2](https://user-images.githubusercontent.com/91053236/215310321-447774bd-5ab2-4ca4-bbf7-ecc3ff3f461c.jpg)

### Steps to reproduce

1.
2.
3.

### Describe the expected behavior

When the OpenTelemerty metrics is disabled, browser does not send playback POSTs to server. 

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/aaab74f4627673e099758676762ccb290ca72b1e
