### ISSUE TITLE
Server Hooks for Subscription

### ISSUE THREAD

**Issue by raazkarkee405** [Chocobozzz/PeerTube#5574]
### Describe the problem to be solved

Hello @Chocobozzz, 

Currently, I could not find any server side hook for Subscription to filter params/result used to list subscription videos for the REST API.

### Describe the solution you would like

adding the hooks similar to the following for the REST API would solve my issue.
  `filter:api.video-subscription.videos.list.params`: `true`,
  `filter:api.video-subscription.videos.list.result`: `true`

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/5648 :)
