### ISSUE TITLE
Peertube-upload.js does not handle connections with self-signed certificates on closed intranets

### ISSUE THREAD

**Issue by maxlinux2000** [Chocobozzz/PeerTube#5577]
### Describe the current behavior

peertube-upload.js does not handle connections with self-signed certificates on closed intranets

Hello
I have tons of videos on my local network that I want to organize using peertube in a local intranet environment, not accessible from outside.
I have created with yunohost a mini-server with peertube in a local domain: https://videos.my.local.
I have exported the certificate /etc/yunohost/certs/yunohost.org/ca.pem as a C.A certificate. (and in firefox it works perfectly)

Then to automate the process I'm trying to use peertube-upload.js with a simple script to upload the videos to peertube, after having installed peertube-cli as well, in /usr/local/bin.

there is no way it works, i think the problem is that peertube forcefully requires an ssl certificate from a recognized and trusted authority.
It's great on the internet... but locally? I have tried to pass to peertube-upload.js first the certificate and then telling it to ignore the self-signed certificates... but nothing.
I think the problem is how videos-command.js handles ssl connections.

`

        export  NODE_EXTRA_CA_CERTS="/root/ca.pem"
        node /root/PeerTube/dist/server/tools/peertube-upload.js -n "hacha Tomahwawk(casera)" -C "julian545" -b /root/PeerTube/julian545/WLkRbAxLZMU.jpg -d "2015-09-16 - WLkRbAxLZMU - Herramienta de Supervivencia.A veces tenemos cosas que no usamos en el fondo de la casa,nada se pierde,todo se trasforma (Con Brian) .Esta arma blanca ya tuvo una primera resurrección a mediados de los años 60 del siglo pasado, al comienzo de la Guerra de Vietnam, destinándose a equipar a las unidades de Operaciones Especiales (Boinas Verdes) y a los Marines. Luego, pasados muchos años, volvió a emplearse en la Segunda Guerra del Golfo. El U.S Army ha incorporado el hacha de guerra (Tomahawk) al armamento de las Fuerzas Especiales, y debido al buen recibimiento de esta se esta estudiando ampliarla a otras unidades." -L "null" -U "yo" -p "preparandonos" -f "/root/PeerTube/julian545/WLkRbAxLZMU.mp4"  -u https://videos.mi.local/
#############################

Uploading hacha Tomahwawk(casera) video...
TypeError: Cannot read properties of undefined (reading '0')
    at VideosCommand.<anonymous> (/root/PeerTube/dist/shared/server-commands/videos/videos-command.js:154:38)
    at Generator.next (<anonymous>)
    at fulfilled (/root/PeerTube/node_modules/tslib/tslib.js:115:62)

-------------------------------------------------------

        export NODE_TLS_REJECT_UNAUTHORIZED="0"
        node /root/PeerTube/dist/server/tools/peertube-upload.js -n "hacha Tomahwawk(casera)" -C "julian545" -b /root/PeerTube/julian545/WLkRbAxLZMU.jpg -d "2015-09-16 - WLkRbAxLZMU - Herramienta de Supervivencia.A veces tenemos cosas que no usamos en el fondo de la casa,nada se pierde,todo se trasforma (Con Brian) .Esta arma blanca ya tuvo una primera resurrección a mediados de los años 60 del siglo pasado, al comienzo de la Guerra de Vietnam, destinándose a equipar a las unidades de Operaciones Especiales (Boinas Verdes) y a los Marines. Luego, pasados muchos años, volvió a emplearse en la Segunda Guerra del Golfo. El U.S Army ha incorporado el hacha de guerra (Tomahawk) al armamento de las Fuerzas Especiales, y debido al buen recibimiento de esta se esta estudiando ampliarla a otras unidades." -L "null" -U "yo" -p "preparandonos" -f "/root/PeerTube/julian545/WLkRbAxLZMU.mp4"  -u https://videos.mi.local/
#############################

(node:14171) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
Uploading hacha Tomahwawk(casera) video...
TypeError: Cannot read properties of undefined (reading '0')
    at VideosCommand.<anonymous> (/root/PeerTube/dist/shared/server-commands/videos/videos-command.js:154:38)
    at Generator.next (<anonymous>)
    at fulfilled (/root/PeerTube/node_modules/tslib/tslib.js:115:62)

`

Can you please take a look at it? Even a simple tip to get out of trouble would be worth it, although I think that peertube is gaining ground to be an optimal video manager in an intranet environment, and therefore without recognized ssl certificates.

greetings
Max

### Steps to reproduce

1. create a peertube instance in yunohost (the stable version) in a local enviroment
2. crate a channel in peertube
3. install peertube-cli
4. use peertube-upload.js in order to upload a video

optional to reproduce:
use the /etc/yunohost/certs/yunohost.org/ca.pem as variable, like  export  NODE_EXTRA_CA_CERTS="/root/ca.pem"
and export NODE_TLS_REJECT_UNAUTHORIZED="0"

### Additional information

* PeerTube instance: INTRANET (videos.mi.local)
  * URL:
  * Version: 5.0.1 
  * NodeJS version: v14.21.2
  * Ffmpeg version: ffmpeg version 4.3.5-0+deb11u1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Thanks for the issue but unfortunately we don't have time to add self signed certificate support in PeerTube scripts.
