### ISSUE TITLE
Monetize videos on Peertube

### ISSUE THREAD

**Issue by collector-ynh** [Chocobozzz/PeerTube#5578]
### Describe the problem to be solved

Currently impossible to monetize videos on Peertube!

### Describe the solution you would like

Hello, I'm a long time Peertube user and I'm very happy with it, but I think that this tool is missing a necessary feature! Peertube doesn't allow to monetize videos, it would be really good to integrate a feature that would allow to make some videos paying, like on Youtube, Vimeo, Patreon...

There are several tools that can be used by Peertube for payments, there are even cryptocurrency oriented tools like BTCPay that can be used in a totally open-source way!

Do you have any idea when this feature will be released?

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/1586
