### ISSUE TITLE
Some youtube channels cannot be imported.

### ISSUE THREAD

**Issue by maxlinux2000** [Chocobozzz/PeerTube#5581]
### Describe the current behavior

Please try importing this (entire) channel on a test computer:
https://www.youtube.com/@Julian545

There is something in this channel that prevents its full import.
I have tried several times and it always stops after about 4-5 videos.
I suspect it is a problem with the cookies or with the youtube login.

On the other hand, with my script that you can see here (in bash) I can import it without problems, passing it the cookies.txt from firefox
I'll put the link here if you want to take a look.
https://www.preparandonos.es/2022/12/30/downloader20-sh/

I know that if I have a video importer that works, why do you want another one?
The answer is simple: I am creating a Live+persistence with debian+yunohost+peertube to distribute to people who want to have many offline youtube channels in case the internet is cut off or if the line cannot be paid for in the future.
And my working script lacks a graphical interface, as well as not being able to work with self-signed domains.

Today I tried using upload.js on http://localhost:9000 and I broke the test installation :-)

So please try to download this channel from julian545. If it manages to download the entire 464 videos, your importer will work perfectly with all the others.

https://www.youtube.com/@Julian545

greetings

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL: private network
  * Version: 5.0.1
  * NodeJS version: v14.21.2
  * Ffmpeg version: 4.3.5-0+deb11u1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

What do you mean by "cannot be imported"? Does the imports? Do you see less import job created compared to the amount of total videos?

**Comment by maxlinux2000** [comment]
Hi! The problem comes if the video has restrictions that, for example,
require you to log in to YouTube.
And I'm not talking about porn videos, I'm talking about, for example,
wanting to download chemistry videos where they explain how to make
nitric acid for use in agriculture or similar things.

I have solved using the cookies.txt exported with firefox in my script

By the way... I recommend you stop using youtube-dl to use ytlp (pip3
install yt-dlp)
The download speed increases by 2000% and it's not that bad.

yt-dlp is a very updated fork of youtube-dl and is fully compatible
with its parent

greetings
Max

**Comment by Chocobozzz** [comment]
Hello,

Unfortunately we don't support importing restricted videos. And we already use yt-dlp by default :)
