### ISSUE TITLE
Webtorrent is disabled, but torrent videos are built

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5583]
### Describe the current behavior

Webtorrent is disabled in production.yaml file, but all of the uploaded videos are converted to torrent file, and stored in "storage/torrents" folder on the server.

### Steps to reproduce

1.
2.
3.

### Describe the expected behavior

If the Webtorrent is disabled, no torrent file will be created.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

We still generate torrent files for all videos uploaded on peertube, even for HLS videos.
