### ISSUE TITLE
Previous video, and Next video buttons are not translatable

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5584]
### Describe the current behavior

On the video player, the previous video, and next video buttons are **not** translatable.
Play & Pause buttons are translatable.

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! The strings are now available on weblate
