### ISSUE TITLE
Live stream regularly drops connection when streaming from Blackmagic ATEM Mini Pro

### ISSUE THREAD

**Issue by TheAssassin** [Chocobozzz/PeerTube#5586]
### Describe the current behavior

I recently tried to stream directly from a Blackmagic ATEM Mini Pro ISO (most likely, the regular Pro version is affected, too, though). Its built-in encoder uses a variable video bitrate that can range from 0.1 MBit/s to a maximum value. The built-in profiles range from 3 to 70 MBit/s as a maximum bitrate, depending on the chosen profile and framerate.

Below a certain threshold (around 4 MBit/s according to hours of experiments), the stream becomes unstable: every 40-50 seconds, the mixer loses the connection to the server (the "On Air" button begins to flash, the PeerTube log just reports that the stream ended and (depending on the configuration) that the stream dumps will be made available. After a few seconds, the connection is working again. Obviously, this provides a horrible experience for the audience, since this causes them to drop out of the live stream for at least 15 seconds. As long as the stream is configured to be permanent, they will join the "new" stream automatically. Also, the server will generate tons of short stream dump clips which are not helpful to anyone. 

What's interesting is that if I generate higher bitrates by, e.g., feeding a stream from a camera or some test footage via HDMI, the stream is relatively stable (I noticed one a dropout in a 30 minute session, this may not have been PeerTube's fault, the sample size is insufficient).

These low bitrates can be seen when using static images (like, e.g., recording a computer's desktop background, bitrate is around 1 MBit/s then) or using the built-in vertical bars test feed (bitrate drops to 0.1 MBit/s) even when choosing the highest quality profile (which can use up to 70 MBit/s). I could reproduce the issue with slightly higher bitrates, too (e.g., when using the PiP keyer, ranging between 2 and 3 MBit/s). Given the fact that I'll mostly be streaming livecasts of software tutorials, Peertube has become completely unusable for me for this purpose.

I was unable to reproduce the issue so far with OBS and ffmpeg as stream sources. I'll keep experimenting, though. I'd strongly prefer to use PeerTube, but will have to resort to some other software for now.

Please note that I live transcode to four different resolutions (360p, 480p, 720p, 1080p) on the server. I don't see how that could be related, though.

### Steps to reproduce

You need the hardware to reproduce the problem. I have just one brand new, up to date ATEM Mini Pro ISO at hand (these devices are quite costly, after all).

I can assist testing the problem, of course.

### Describe the expected behavior

PeerTube should handle the livestream correctly, that is, avoid losing the connection with these low bitrates.

### Additional information

My guess is that this is related to server-side buffering. On Blackmagic's forums, some users of ATEM Mini Pro (ISO) devices have reported similar problems. Please note that in my case, the device's buffer remains at 0 ("OK"). The device works with other software such as [OwnCast](https://owncast.online/), I also tested against a few well-known services for at least half an hour, but did not see any dropouts.

PeerTube 5.0.1, using Docker tag `v5.0.1-bullseye`, hash `fda28bd5344c`.

Server log excerpt: https://bin.snopyta.org/?2de62d3b43d37c43#3ZmKZ8QeGM4BTkudkRdb25GAoHjnqTtb4c3B1qFpuezT (these `fragLoadError`s are weird, too, but that might be caused my reverse proxy setup...)

**Comment by Chocobozzz** [comment]
Hi,

We just use `ffmpeg` on the server to receive the RTMP stream and convert it to HLS. We consider the stream ended when the ffmpeg command also ended, so in theory the issue comes from ffmpeg. Can you try to stream to a ffmpeg you run from the CLI to see if you also have this bug?

However it's weird owncast works, as I think they also use ffmpeg to receive the RTMP stream and convert it to HLS :thinking: 

(client errors are not important for this issue)

**Comment by TheAssassin** [comment]
> However it's weird owncast works, as I think they also use ffmpeg to receive the RTMP stream and convert it to HLS thinking

That's what I was stunned by, too. I haven't got around to compare the CLI parameters passed to ffmpeg by both PeerTube and owncast.

I plan to test this in a LAN setup with some OPNsense between a powerful PeerTube server and the switcher so I can also configure some network parameters (e.g., MTU, maybe simulate packet loss.

**Comment by Chocobozzz** [comment]
Any news @TheAssassin?

**Comment by Chocobozzz** [comment]
I'm closing this issue, don't hesitate to comment if you have some news!

**Comment by TheAssassin** [comment]
Unfortunately, I have to report that the issue persists with the latest Peertube 5.2.1. The stream keeps dropping out. The log does not provide any useful information. Here is a redacted excerpt:

```
[peertube.example.org:443] 2023-10-31 00:21:17.300 info: rtmp://127.0.0.1:1935/live/xxx probing took 1442 ms (bitrate: 6144000, fps: 30, resolution: 1080)
[peertube.example.org:443] 2023-10-31 00:21:17.301 info: Handling live video of original resolution 1080. {
  "allResolutions": [
    360,
    720,
    1080
  ]
}
[peertube.example.org:443] 2023-10-31 00:21:17.440 info: Built supported ffmpeg encoders. {
  "supportedEncoders": [
    [
      "libfdk_aac",
      false
    ],
    [
      "aac",
      true
    ],
    [
      "libx264",
      true
    ]
  ],
  "searchEncoders": [
    "libfdk_aac",
    "aac",
    "libx264"
  ]
}
[peertube.example.org:443] 2023-10-31 00:21:19.590 info: Running local live muxing/transcoding for yyy.
[peertube.example.org:443] 2023-10-31 00:21:25.808 info: Master playlist file for yyy has been created
[peertube.example.org:443] 2023-10-31 00:21:29.761 info: Will publish and federate live https://peertube.example.org/videos/watch/yyy.
[peertube.example.org:443] 2023-10-31 00:21:45.923 info: 172.20.0.0 - - [31/Oct/2023:00:21:45 +0000] "GET /api/v1/videos/yyy/captions HTTP/1.1" 200 21 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:45.934 info: 172.20.0.0 - - [31/Oct/2023:00:21:45 +0000] "GET /api/v1/videos/yyy HTTP/1.1" 200 3778 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:45.959 info: 172.20.0.0 - - [31/Oct/2023:00:21:45 +0000] "GET /api/v1/videos/yyy/captions HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:45.983 info: 172.20.0.0 - - [31/Oct/2023:00:21:45 +0000] "GET /api/v1/videos/yyy HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:45.997 info: 172.20.0.0 - - [31/Oct/2023:00:21:45 +0000] "GET /api/v1/videos/live/yyy HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.072 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /api/v1/users/me/videos/yyy/rating HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.096 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /api/v1/videos?start=0&count=6&sort=-createdAt HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.100 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /api/v1/videos/live/yyy HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.100 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /client/de-DE/9383.95d7f2585e10c899.js HTTP/1.1" 200 28372 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.103 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /client/de-DE/1436.35bd5ffd73f70f06.js HTTP/1.1" 200 83641 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.104 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /client/de-DE/110.afb1f892936f6181.js HTTP/1.1" 200 72374 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.105 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /client/de-DE/9512.493e5e50780cd626.js HTTP/1.1" 200 322741 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.117 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /api/v1/videos/yyy/comment-threads?start=0&count=10&sort=-createdAt HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.150 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /api/v1/users/me/videos/yyy/rating HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.157 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /api/v1/videos?start=0&count=6&sort=-createdAt HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.178 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /api/v1/videos/yyy/comment-threads?start=10&count=10&sort=-createdAt HTTP/1.1" 200 49 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.255 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /api/v1/videos/yyy/comment-threads?start=10&count=10&sort=-createdAt HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.266 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /client/locales/de-DE/player.json HTTP/1.1" 200 6879 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.303 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /static/streaming-playlists/hls/yyy/segments-sha256.json HTTP/1.1" 200 1217 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.331 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /static/streaming-playlists/hls/yyy/segments-sha256.json HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.332 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /static/streaming-playlists/hls/yyy/master.m3u8 HTTP/1.1" 200 310 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.347 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /client/de-DE/next.7bb9b7a43970af24.svg HTTP/1.1" 200 1675 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.384 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /static/streaming-playlists/hls/yyy/2.m3u8 HTTP/1.1" 200 605 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.396 info: Creating job to send viewer of https://peertube.example.org/videos/watch/yyy.
[peertube.example.org:443] 2023-10-31 00:21:46.423 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "POST /api/v1/videos/yyy/views HTTP/1.1" 204 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.426 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /static/streaming-playlists/hls/yyy/2-000001.ts HTTP/1.1" 200 94940 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.455 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /static/streaming-playlists/hls/yyy/2-000002.ts HTTP/1.1" 200 94564 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.491 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /static/streaming-playlists/hls/yyy/2-000003.ts HTTP/1.1" 200 94940 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.510 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /client/assets/images/icons/icon-192x192.png HTTP/1.1" 200 8197 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:46.561 info: 172.20.0.0 - - [31/Oct/2023:00:21:46 +0000] "GET /api/v1/users/me/video-playlists/videos-exist?videoIds=37 HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:47.158 info: 172.20.0.0 - - [31/Oct/2023:00:21:47 +0000] "GET /static/streaming-playlists/hls/yyy/master.m3u8 HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:47.161 info: 172.20.0.0 - - [31/Oct/2023:00:21:47 +0000] "GET /api/v1/users/me/video-playlists/videos-exist?videoIds=37 HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:47.181 info: 172.20.0.0 - - [31/Oct/2023:00:21:47 +0000] "POST /api/v1/videos/yyy/views HTTP/1.1" 204 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:47.198 info: 172.20.0.0 - - [31/Oct/2023:00:21:47 +0000] "GET /static/streaming-playlists/hls/yyy/2.m3u8 HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:49.419 info: 172.20.0.0 - - [31/Oct/2023:00:21:49 +0000] "GET /static/streaming-playlists/hls/yyy/2-000005.ts HTTP/1.1" 200 94940 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:50.033 info: 172.20.0.0 - - [31/Oct/2023:00:21:50 +0000] "GET /static/streaming-playlists/hls/yyy/segments-sha256.json HTTP/1.1" 200 1460 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:50.383 info: 172.20.0.0 - - [31/Oct/2023:00:21:50 +0000] "GET /static/streaming-playlists/hls/yyy/2.m3u8 HTTP/1.1" 200 689 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:50.421 info: 172.20.0.0 - - [31/Oct/2023:00:21:50 +0000] "GET /static/streaming-playlists/hls/yyy/2-000006.ts HTTP/1.1" 200 94564 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:51.001 info: 172.20.0.0 - - [31/Oct/2023:00:21:51 +0000] "GET /static/streaming-playlists/hls/yyy/segments-sha256.json HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:51.341 info: 172.20.0.0 - - [31/Oct/2023:00:21:51 +0000] "POST /api/v1/videos/yyy/views HTTP/1.1" 204 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:51.536 info: 172.20.0.0 - - [31/Oct/2023:00:21:51 +0000] "GET /static/streaming-playlists/hls/yyy/segments-sha256.json HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:52.065 info: 172.20.0.0 - - [31/Oct/2023:00:21:52 +0000] "GET /static/streaming-playlists/hls/yyy/segments-sha256.json HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:52.152 info: 172.20.0.0 - - [31/Oct/2023:00:21:52 +0000] "GET /static/streaming-playlists/hls/yyy/2.m3u8 HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:52.597 info: 172.20.0.0 - - [31/Oct/2023:00:21:52 +0000] "GET /static/streaming-playlists/hls/yyy/segments-sha256.json HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:53.129 info: 172.20.0.0 - - [31/Oct/2023:00:21:53 +0000] "GET /static/streaming-playlists/hls/yyy/segments-sha256.json HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:53.664 info: 172.20.0.0 - - [31/Oct/2023:00:21:53 +0000] "GET /static/streaming-playlists/hls/yyy/segments-sha256.json HTTP/1.1" 304 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:54.198 info: 172.20.0.0 - - [31/Oct/2023:00:21:54 +0000] "GET /static/streaming-playlists/hls/yyy/segments-sha256.json HTTP/1.1" 200 1703 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:54.379 info: 172.20.0.0 - - [31/Oct/2023:00:21:54 +0000] "GET /static/streaming-playlists/hls/yyy/2.m3u8 HTTP/1.1" 200 773 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:54.420 info: 172.20.0.0 - - [31/Oct/2023:00:21:54 +0000] "GET /static/streaming-playlists/hls/yyy/2-000004.ts HTTP/1.1" 200 94564 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:55.862 info: Live session ended. {
  "sessionId": "PQR3LAUG"
}
[peertube.example.org:443] 2023-10-31 00:21:56.123 info: RTMP transmuxing for video rtmp://127.0.0.1:1935/live/xxx ended. Scheduling cleanup
[peertube.example.org:443] 2023-10-31 00:21:56.156 info: 172.20.0.0 - - [31/Oct/2023:00:21:56 +0000] "GET /static/streaming-playlists/hls/yyy/2.m3u8 HTTP/1.1" 200 872 "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:56.340 info: 172.20.0.0 - - [31/Oct/2023:00:21:56 +0000] "POST /api/v1/videos/yyy/views HTTP/1.1" 204 - "https://peertube.example.org/w/zzz" "Chrome"
[peertube.example.org:443] 2023-10-31 00:21:57.030 warn: Unknown live video with stream key xxx.
[peertube.example.org:443] 2023-10-31 00:21:57.031 info: Live session ended. {
  "sessionId": "3FR32SO2"
}

```

The parameters in the log look correct, the switcher uses H.264 with AAC. I ingest a 1080p stream. The switcher is configured to use an audio bitrate of 128 kbit/s and a video bitrate of 9 MBit/s at 1080p/60 and 9 MBit/s at 1080p/30. Lowering the (video) bitrate to half does not do anything. Also, it still works fine with alternative streaming solutions like Owncast. It must be Peertube's configuration.

I configured Peertube to broadcast the resolutions in the list but not transcode the original stream. I flipped the setting, but it doesn't seem to have any effect.

**Comment by TheAssassin** [comment]
I have an event at the weekend for which I want to use Peertube as a streaming server with the mixer. I'll continue to test until the middle of the week (I need to announce the streaming URL a couple of days before the event). If no solution is found, I'll keep digging afterwards.

Please reopen the issue, as it clearly has not been solved.

**Comment by Chocobozzz** [comment]
Hi,

Can you reproduce using debug logs in PeerTube configuration?

**Comment by TheAssassin** [comment]
Thanks. I even set it to `debug`, which generated a lot of logging. I stripped the SQL queries and identifying data. This includes the first stream right after the startup and a few reconnects (permanent live cast this time).

https://privatebin.net/?907ec2c858af6e68#FmPnxTg4tHNQvELigV3p5mwDafPNVYooctSi6vNHYc14

This is from a beta-grade system, if you need more, let me know and I'll set up a separate test instance.

**Comment by TheAssassin** [comment]
I hacked a bit on the ffmpeg command in the logs and got this to work fine with my ATEM Mini:

```sh
/usr/bin/ffmpeg -listen 1 -i rtmp://0.0.0.0:1935/live -y -filter_complex "[v:0]split=3[vtemp360][vtemp720][vtemp1080];[vtemp360]scale=w=-2:h=360[vout360];[vtemp720]scale=w=-2:h=720[vout720];[vtemp1080]scale=w=-2:h=1080[vout1080]" -threads 4 -sc_threshold 0 -max_muxing_queue_size 1024 -map_metadata -1 -pix_fmt yuv420p -map [vout360] -level:v:0 3.1 -g:v:0 60 -c:v:0 libx264 -preset veryfast -maxrate:v:0 1036800 -bufsize:v:0 2073600 -b_strategy 1 -bf 16 -r:v:0 30 -b:v:0 1036800 -map a:0 -c:a:0 copy -map [vout720] -level:v:1 3.1 -g:v:1 60 -c:v:1 libx264 -preset veryfast -maxrate:v:1 3041280 -bufsize:v:1 6082560 -b_strategy 1 -bf 16 -r:v:1 30 -b:v:1 3041280 -map a:0 -c:a:1 copy -map [vout1080] -level:v:2 3.1 -g:v:2 60 -c:v:2 libx264 -preset veryfast -maxrate:v:2 6220800 -bufsize:v:2 12441600 -b_strategy 1 -bf 16 -r:v:2 30 -b:v:2 6220800 -map a:0 -c:a:2 copy -hls_time 4 -hls_list_size 15 -hls_flags delete_segments+independent_segments+program_date_time -hls_segment_filename /tmp/ffmpeg-out/%v-%06d.ts -master_pl_name master.m3u8 -f hls -var_stream_map "v:0,a:0 v:1,a:1 v:2,a:2" /tmp/ffmpeg-out/%v.m3u8
```

This uses Ubuntu 22.04's ffmpeg build. Note that it has ffmpeg listen.. It's worked fine on my local machine for around half an hour now. I'm just feeding black just like I do with Peertube. The recorded `.ts` playlist plays back fine with `ffplay`. I also ran the command on the host in question in a simple Ubuntu 22.04 Docker container. It worked as expected.

I'm starting to feel this is not necessarily an issue with ffmpeg but with its deployment and operation inside of the Peertube container. It looks like the ingest part is not done with ffmpeg directly (which probably makes sense, I don't know for sure). When having ffmpeg listen directly, it has worked flawlessly in the last 45 minutes without any interruptions.

Is there a way to capture ffmpeg's output directly? Or is everything it ever logs contained in the logs above already?

I'll try using ffmpeg or gstreamer as a proxy in front of Peertube next. This could serve as a viable workaround for #5587, too.

**Comment by TheAssassin** [comment]
I invested quite a bit more time into testing with the proxy I suggested. This command is working just fine (not sure if any container other than `flv` would be better):

```sh
ffmpeg -listen 1 -i rtmp://0.0.0.0:1935/"$stream_key" -c:a copy -c:v copy -f flv rtmp://peertube.domain/live/...
```

It's worked fine for over an hour now with the ATEM Mini Pro I have on hand. I'm still wondering what the problem could be. Some element in the chain doesn't like the stream that comes in. This little conversion to another container appears to do the trick. I consider this a workaround, as this introduces yet another element in the chain that induces delay and could cause issues.

I'm up for more testing, so please let me know what I can try. I'm also willing to send streams to some instance of yours so you can have a look directly.

**Comment by Chocobozzz** [comment]
We use https://github.com/illuspas/Node-Media-Server to handle RTMP stream. Maybe it doesn't like something if the root stream? Can you try to use this library to confirm it's the source of your bug?

**Comment by TheAssassin** [comment]
I will.

**Comment by TheAssassin** [comment]
Looks like the mixer cannot connect at all (might be a configuration problem, though). I can connect using the ffmpeg command they provide, which also uses the `flv` container. I need to check which container the mixer uses internally, but I'm relatively sure it's not `flv`. I think the container format could be the problem.

**Comment by Chocobozzz** [comment]
Did you manage to debug this issue @TheAssassin?

**Comment by TheAssassin** [comment]
The issue persists. It's some codec thing with the streaming server. I cannot work around it and can't spend more time on this. Maybe you want to close this as wontfix rather than completed.

**Comment by vincib** [comment]
Hi everyone. I'm having something similar : I have an ATEM Mini Pro ISO deck, that allows to stream to a RTMP server, and it never worked properly with Peertube.

- What I see : the ATEM is streaming : "on air" icon blinks then stay red for about a minute
- then the ATEM "on air" is blinking, and peertube logs ```[indymotion.fr:443] 2025-05-14 14:29:38.483 info: Live session ended.{  "sessionId": "QQLVVW7V"}```
- the ATEM retry and restart the live

so basically the live "blinks" ...

I just tried to make it work by passing the RTMP stream via a nginx with nginx-rtmp module. 

The configuration I used was : 

```
rtmp {
        server {
                listen 1995;
                chunk_size 4096;
                allow publish 127.0.0.1;
                deny publish all;
                application livetest123 {
		       allow publish all;
  	   	        push rtmp://indymotion.fr:1935/live/1234567890-1234-1234-1234-1234567890;
                        live on;
			access_log /var/log/nginx/rtmp_access.log;
                }
        }
```

and now I'm publishing in the ATEM to my Nginx, which "forwards" the stream to peertube ... and it worked ...

**Comment by vincib** [comment]
I can try to launch my peertube dev instance in debug mode and try to see what Node-rtmp is logging ... will keep you informed

**Comment by Chocobozzz** [comment]
FYI PeerTube still uses node-media-server v2

**Comment by TheAssassin** [comment]
Sounds very similar to my workaround. By using a different streaming client as a proxy, PeerTube accepts the stream and it's just as reliable as you would expect.
