### ISSUE TITLE
Accurate error messages in the client

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5591]
### Describe the current behavior

When the web server is unavailable our CDN returns a HTML page, which results in the following errors dialogs:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/6680299/217857421-8b72d230-b9ef-453e-b64d-349db9b2992b.png">

### Describe the expected behavior

If the server response isn't in an accurate JSON format, can we display a default message ("Server is unavailable")?

### Additional information

* PeerTube instance:
  * Version: 4.3.1

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/03902b00994a03e333acd7662d26782e3dc52e07
