### ISSUE TITLE
Please support multi-server

### ISSUE THREAD

**Issue by imtube** [Chocobozzz/PeerTube#56]
Please think about it, if peertube will be used for business, it must be support multi-server to save videos.

**Comment by Chocobozzz** [comment]
Can you clarify? I don't understand.

**Comment by imtube** [comment]
@Chocobozzz Hello, I mean, one single server maybe don't have enough space and other resource to run a website when the number of videos is very big.

**Comment by Chocobozzz** [comment]
Yes I know, PeerTube is designed to be decentralized. It works with multiple servers right now.
