### ISSUE TITLE
Transcoding elsewhere and submit to Peertube

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#560]
I would like to know if there are some ways to:
 - transcode videos on another computer (using ffmpeg);
 - upload the result of the transcoding to the Peertube server?

This way, as I have a much more efficient CPU, I could submit the different resolutions of a video more rapidly.

Does it sound to you like a reasonnable use case? Do you know if that's feasible with the current tools? Or should this lead to some dirty tricks in the database (I saw there is the "videoFile" table for that).

Cheers!
Florent

**Comment by Chocobozzz** [comment]
We use the `ffmpeg` command, so you can create a script that accepts the same options than `ffmpeg` but sends the file on another server, transcode it, and fetch the result on the PeerTube server (just an example). There are some tools on the web that try to distribute `ffmpeg` transcoding

You should be able to change `ffmpeg` path with `FFMPEG_PATH` env.

**Comment by fflorent** [comment]
Well, I meant on my local personal computer (which is time to time off).
