### ISSUE TITLE
Autoplay Next video returns to the main video

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5602]
### Describe the current behavior

I enabled the autoplay next video setting. When the main video is played, the top video from "Next video to be played" will be played, and the main video will be put on the top of the list. So, these two videos will be played one after another. 

### Steps to reproduce

1.
2.
3.

### Describe the expected behavior

After playing the video, the next video from the top of the list will be played. Then the second, 3rd, ... video from the recommended videos list should be played.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue. Merging it with https://github.com/Chocobozzz/PeerTube/issues/1985, since resolving this other issue will also solve this one.
