### ISSUE TITLE
A PeerTube instance is accessible by IP, not just by domain name

### ISSUE THREAD

**Issue by quicktrick** [Chocobozzz/PeerTube#5603]
### Describe the current behavior

My PeerTube instance is accessible not only by domain name, but also by IP. I found this out by accident from the log entries.

### Steps to reproduce

1. https://tube.artsale.info/
2. https://46.138.246.97/

### Describe the expected behavior

A PeerTube instance should be accessible only by domain name.

### Additional information

* PeerTube instance:
  * URL: https://tube.artsale.info/
  * Version: 5.0.1
  * NodeJS version: 18.12.1
  * Ffmpeg version: 4.4.3_4
  * OS: FreeBSD 13.1

* Browser name, version and platforms on which you could reproduce the bug: Any

**Comment by Chocobozzz** [comment]
Hello,

It's the responsibility of your front proxy (nginx for example) to deny HTTP(S) access to your server when using your server IP as host in URL.

**Comment by quicktrick** [comment]
I thought it made sense to build the solution into the default PeerTube Nginx configuration. Okay, then. I added the following default server block to my configuration:

```
    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        listen 443 default_server;
        listen [::]:443 default_server;
        ssl_reject_handshake on;

        server_name _;
        return 444;
    }
```
