### ISSUE TITLE
No autoplay on ios

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#5604]
### Describe the current behavior

Autoplay a muted video doesn't autoplay the video on ios

### Steps to reproduce

1. Go on https://peertube2.cpy.re/videos/embed/nYijJfhF2aPmN3XXmf39ob?autoplay=1&muted=1 with IOS device

### Describe the expected behavior

I think we can autoplay the video on IOS. We need to investigate if the bug comes from the HLS fallback where we don't inject the appropriate tags to the `video` element.

### Additional information

* PeerTube instance:
  * Version: 5.1

**Comment by Chocobozzz** [comment]
Blocked by https://github.com/Chocobozzz/PeerTube/issues/5465

**Comment by SnejPro** [comment]
I have the same issue with p2p completly disabled.
But I can use the Embed API to start the video automatically.
YouTube works.

**Comment by Chocobozzz** [comment]
Muted autoplay should work with https://github.com/Chocobozzz/PeerTube/commit/63e2f087c3410206aa294df8099b005e615592e5

I still had some autoplay failures with an iOS device though, but I don't think it's a peertube issue.
