### ISSUE TITLE
PeerTubeLinkButton under the video player does not work correctly 

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5605]
### Describe the current behavior

When you play a video via embed link, you see the instance name as a button below the player which directs you to the video page. I checked it on several Android phones. This button works in FireFox, but in Chrome, it does not work at all, or it works randomly after several clicks.

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/c9c21fafdb481a4bbb661229f6dc3e2b673ab3c6

**Comment by paymanzafar1** [comment]
@Chocobozzz Thank you very much
