### ISSUE TITLE
Autoplay next video does not set correctly

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5606]
### Describe the current behavior

Setting/Clearing the "Automatically start playing the next video" check box in my settings, does not update the autoplay button under the video player. But the reverse is OK.

### Steps to reproduce

1.	Open a video page
2.	Disable the autoplay button under the video player
3.	Open My settings & set the "Automatically start playing the next video" check box
4.	Close My settings
5.	You see the autoplay button under the video player is still disabled
6.	But if you disable/enable the autoplay button under the player, it will update "My settings"

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/6a7cea15271cf30c4b06c7981bff5201978337e8

**Comment by paymanzafar1** [comment]
@Chocobozzz Thank you very much
