### ISSUE TITLE
Notification error in the nightly build 5.0.1-nightly-2023-02-14

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5607]
### Describe the current behavior

I have updated my test instance of the nightly build to the 5.0.1-nightly-2023-02-14 and I noticed that unread notifications are constantly displayed in large numbers.
Even if you mark all notifications as read, they reappear after the page is refreshed.

![Скриншот 14 02 23_12 07 14](https://user-images.githubusercontent.com/11453567/218689644-da60625e-7978-40ca-8936-eb9140452355.png)

### Additional information

* PeerTube instance:
  * URL: https://video.ustim.ru
  * Version: 5.0.1-nightly-2023-02-14

**Comment by Chocobozzz** [comment]
Thanks, fixed by https://github.com/Chocobozzz/PeerTube/commit/4de99f22dfc4f00587eeac5bc929f462437315e4
