### ISSUE TITLE
Quick feature for updating Peertube translations

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5608]
### Describe the problem to be solved

A huge request to add a function so that new translations from Weblate can be uploaded to the instance.
Why is this necessary:
I constantly monitor and perform translations into my own language, I recently noticed that a "bad" person appeared and began to translate incorrectly, as well as some words are simply terrible and even funny. I do not know how to deal with it!

If the perverted words get into the release, it will be very terrible.

### Describe the solution you would like

I would like to use a command that will request the updated translation files from Weblate and replace them on the server.
This is necessary to get an instant translation of the text.

**Comment by Chocobozzz** [comment]
Hello,

To report abuse on weblate you can use the contact form: https://weblate.framasoft.org/contact/
Then we'll be able to review the situation, block an account and revert its modifications.

You can also mention me on weblate in the translation comments.

**Comment by Alterak** [comment]
> 

Thank you, if I understand you correctly, then it is impossible to do the function of fast loading of text translation in Peertube?

**Comment by Chocobozzz** [comment]
I think it's possible to upload a translation file directly on weblate, but I'm not sure it's allowed for "classic" users. If there are many strings to replace I can try to do it for you if you want. But it's better to communicate by email.
