### ISSUE TITLE
Multiple access-control-allow-origin headers

### ISSUE THREAD

**Issue by joho1968** [Chocobozzz/PeerTube#5609]
### Describe the current behavior

Using PT on video.domain1.com, I'm running into issues with oembedding content in a WordPress page hosted on web.domain2.com. Both Chromium and Firefox complain, and I cannot for the life of me find any place in the configuration where I emit multiple access-control-allow-origin headers, but they are there.

### Steps to reproduce

Simply creating a WordPress page on web.domain2.com that oembeds a video from video.domain1.com generates this result.

Using the WP iframe method to embed the video, everything works. Viewing the video directly on video.domain1.com works.

### Describe the expected behavior

I would expect only one access-control-allow-origin header to be generated.

![image](https://user-images.githubusercontent.com/3135227/218693147-70dba641-314e-4f75-a1dd-6dad0c65446e.png)

### Additional information

* PeerTube instance:
  * URL: Behind auth
  * Version: 5.0.1
  * NodeJS version: 16.19.0
  * Ffmpeg version: 4.2.7-0ubuntu0.1

* Browser name, version and platforms on which you could reproduce the bug: Chrome, Firefox, Chrome, Linux, Windows

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://video.domain1.com/api/v1/videos/27be4172-3982-472a-807c-626dabc152c9. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘*, *’)

**Comment by Chocobozzz** [comment]
Hello,

Can you provide the HTML generated by Wordpress when using OEmbed? We would also need the request headers and request path to understand which request fails.

**Comment by joho1968** [comment]
This looks like it's the one (it's a bit messy, to put it mildly):

```
<figure class="wp-block-embed is-type-wp-embed is-provider-peertube wp-block-embed-peertube">
  <div class="wp-block-embed__wrapper">
    <iframe class="wp-embedded-content" sandbox="allow-scripts" security="restricted" title="Some title" width="560" height="315" src="[https://video.domain1.com/videos/embed/27be4172-3982-472a-807c-626dabc152c9#?secret=rHD5UnVSib](view-source:https://video.domain1.com/videos/embed/27be4172-3982-472a-807c-626dabc152c9#?secret=rHD5UnVSib)" data-secret="rHD5UnVSib" frameborder="0"></iframe>
  </div>
</figure>
```

I know Apache isn't formally/officially supported, but Nginx is, unfortunately not an option in this case.

What I did find to help was to clear the Access-Control-Allow-Origin on web.domain2.com like this:

```
Header always unset Access-Control-Allow-Origin                                                                                   
Header always unset access-control-allow-origin
```

And then setting it to whatever I wanted. I have no idea if it's Firefox, Chromium, Chrome, or Apache that is interpreting headers in a case sensitive manner, but that's the only reason I can think of why there'd be two "identical" headers with "*".

**Comment by Chocobozzz** [comment]
I suggest to continue this discussion on the forum (https://framacolibri.org/c/peertube) as it doesn't seem to be a problem with PeerTube itself
