### ISSUE TITLE
Distribute tips among authors that showcase support information

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#561]
This issue is a writeup following [a thread on the fediverse](https://mastodon.eliotberriot.com/@eliotberriot/100011906327720733), now published as a [blog post](https://eliotberriot.com/blog/2018/05/11/funkwhale-content-monetization-trust/). I will paraphrase some text from it, and strongly recommend you to read it before what follows.

The rough idea is:

1. We have a network of content servers (Peertube, Funkwhale, MediaGoblin instances...). Those servers are hosting and replicating the content (music, videos, whatever), making it available on the internet, *for free* (this is important and incidentally what we are already doing)
2. Creators publish their content on those servers
3. Creators define needs/goals in a standardized way. Those are also made available publicly.

Now, that is where this issue finds its purpose: find a way to interact with an upcoming standard (3. Could be based on ActivityPub, but let’s focus on the bigger picture here). We already have a support button/info zone that can hold more than just links. It's far from ideal, as the info should be updated by the author from their main account and broadcast to update the info on all videos and tipping accounts, but that's another story that will need integration in ActivityPub.

We could use the support button info to identify Liberapay accounts for instance, and automatically trigger a mail at the end of the month, giving hints as how to balance the tips depending on how much the user has viewed each video featuring support info. Beyond that we could also trigger the tip on Liberapay, but that would need some integration. An example of such an integration:

> Typically, your Funkwhale instance could use your listening history to suggest you a few creators you like that also happen to need help.
> Hell, you could even define a monthly budget on Liberapay, connect it to your PeerTube instance, and let PeerTube dispatch your donations based on your views to creators that need it the most!
> This is not a new idea: Flattr does that. But it’s centralized.
> As a creator, you could share various channels to get your financial contributions: a Liberapay account, a Ğ1 or Bitcoin address, an IBAN, a PayPal account, a Patreon or Tipeee page, a Flattr address…
> No need to force your audience to use a specific channel.
> Most of this could be semi or fully automatized.

Clearly we miss the monthly/whatever budget broadcasting, but we can already make a simple suggestion based on history. Now, I know we don't store history and don't want to track users, but that would be opt-in anyway and there's no need to track all videos. There's only an interest to store counters for videos we actually can link to an account. And then we can also make the support button active, and only take into account videos whose support button was clicked.

What do you think?

**Comment by Bugsbane** [comment]
Yeah, I'm not sure how this would work with text/image based content, but for time based media (audio, video etc), it makes sense to split the monthly tip budget up based on minutes of viewing / listening time.

The beauty of this is that a user can set it up once to begin with, and then have all of their donations work automatically after that. No need to be reminded each month to tip anyone manually. Users just set a budget, enter payment details and then watch / listen to media after that. After payments are made (monthly? weekly?) any viewing records could be automatically deleted by the instance, without ever sharing them off the instance.

**Comment by obaviet** [comment]
Why dont we use a crypto? Ex: steem

**Comment by Chocobozzz** [comment]
Closing this inactive discussion. Don't hesitate to comment if you want to reopen it.

**Comment by LoveIsGrief** [comment]
Glad to see I'm not the only one who had this idea. IMO, this could be the way to get more content creators to join peertube.

From reading the [plugin API](https://docs.joinpeertube.org/api-plugins), I don't think this will be possible with a fine granularity: it won't be possible to track how long a user watched a video down to seconds or even minutes. All one would have access to is `action:api.video.viewed` on the server. Am I mistaken? Is it possible to create a plugin that hooks into the player and tracks viewing time?

However, before work starts on a plugin, the questions is: would this feature even be wanted in the base-code of peertube?

**Comment by Bugsbane** [comment]
Whether it's wanted in the base code of Peertube or in a plugin, it sounds like the first step would be adding an api call to return how much time a given user has watched a channel/video. Obviously that requires the server to remember this, however it could only be for users with this feature enabled and it would only need to be a cumulative total, not a record of each and every view, eg api.user.viewtime.channelx=211 (seconds). Apps using this could just mark the date and time they last called and figure out the difference to calculate viewtime for payment.
