### ISSUE TITLE
Stats for Live: the number of "viewers" when hovering over a country does not match the "unique viewers" number

### ISSUE THREAD

**Issue by vijay-howlround** [Chocobozzz/PeerTube#5611]
### Describe the current behavior

The issue is that when I total the viewer numbers for each country, they do not add up to the "unique viewers" number that is displayed in a block above the graph. This discrepancy is the issue/bug. 

![viewers in the country graph versus the unique viewers display](https://user-images.githubusercontent.com/3924097/218810699-17902e09-7c0a-40e1-bfeb-0b7bee40ba3f.png)

### Steps to reproduce

1. Open the Stats page for a Live 
2. Select a time range from the drop down
3. Click on the Countries tab and then compare the total viewers from various countries with the "unique viewers" number displayed above the graph. 

### Describe the expected behavior

The graph of countries/viewers should match the "unique viewers" number that is displayed in the block above the graph.

### Additional information

* PeerTube instance:
  * URL: https://peertube-us.howlround.com/stats/videos/d83733c6-2b7a-42c3-aff1-793cd144aaff?startDate=2023-02-06T22:00:28.770Z&endDate=2023-02-06T22:57:17.946Z&s=2

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue. It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/fd7581b036d9e3580e2e0b1e20d7e4c771d8ff83
