### ISSUE TITLE
Regression: Sidebar on larger (e.g. iPad-like) touch capable devices

### ISSUE THREAD

**Issue by aeharding** [Chocobozzz/PeerTube#5612]
### Describe the current behavior

At some point, the functionality depicted in the video from the following PR stopped working:

https://github.com/Chocobozzz/PeerTube/pull/3088

Now, when the sidebar is open, the content dissappears and scrolling is broken/weird (see video):

https://user-images.githubusercontent.com/2166114/219129953-d5ba20d5-24c1-4ce2-bfc1-8a7a5ef6745e.mp4

### Steps to reproduce

1. Use an iPad or a browser inspector with touch enabled (e.g. iPad in Firefox Inspector)
2. Go to PeerTube (nightly and/or stable), open sidebar
3. Observe content disappears and scrolling is weird

### Describe the expected behavior

* Content should have a black transparent overlay
* Only scrolling sidebar should work.

### Additional information

* PeerTube instance: https://peertube2.cpy.re/
* Browser: iOS iPad or iOS iPad simulator in FireFox (e.g., touch-enabled large screen device)

**Comment by Chocobozzz** [comment]
Thanks, I don't know why I removed this lines. Reverted in https://github.com/Chocobozzz/PeerTube/commit/4835b374d04705408e6c458f7ce100d929b2edc1
