### ISSUE TITLE
Still receiving notification after unsubscribing to a channel

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5613]
### Describe the current behavior

I unsubscribed to a channel, but I'm still receiving notifications (e-mail and in-app).

Note: my server is also following the origin instance. I did not check the code, but maybe the bug is here: my server still receive updates as I follow the whole instance

### Steps to reproduce

1. Follow a whole server
2. Subscribe to a distant channel (from the server followed at step 1)
3. Unsubscribe to the channel
4. Wait for a notification

### Describe the expected behavior

Should not receive notifications

### Additional information

* PeerTube instance:
  * URL: https://videos.john-livingston.fr
  * Version: 5.0.1
  * NodeJS version:
  * Ffmpeg version:

**Comment by Chocobozzz** [comment]
Hello,

I can't reproduce: can you include some logs in your bug report?

**Comment by JohnXLivingston** [comment]
I can't re-subscribe to the channel:
- if I click on subscribe, it seems ok. But when refreshing the page, I'm not following anymore
- if I re-subscribe and immediatly unsubscribe, the API request returns a 404 «Client log: Backend returned code 404, errorMessage is: Subscription xxxxxxxx not found.»

It reminds me a bug that was discuted on framacolibri some month ago.

I don't know where to look. If you want, we can go on a BigBlueButton room, so I can show you. Highlight me on the matrix room if it is ok for you.

**Comment by Chocobozzz** [comment]
Can you paste server logs when you try to subscribe?

**Comment by JohnXLivingston** [comment]
Here you go: https://cloud.john-livingston.fr/s/3qqLekmwd5gEJFq

**Comment by Chocobozzz** [comment]
Hi, and sorry for the late answer.

Can you try to reproduce and give me your debug server logs?

**Comment by JohnXLivingston** [comment]
Sorry, i set a expiration date on the file share. Here is an updated link, valid for 2 months:
https://cloud.john-livingston.fr/s/JiScpxdR9izjtF8

**Comment by Chocobozzz** [comment]
From your logs it seems you subscribed to a channel on `video.davduf.net` but it doesn't answer to your request. 

I also don't see unsubscription.

**Comment by JohnXLivingston** [comment]
Does it mean that a malicious remote instance can ignore unfollow requests, so that users can't unfollow?

What can I do to debug `video.davduf.net` ? (this is not my instance, but i think you already knew ;) )

I you want to debug the process with me, we can do it by visio.

**Comment by Chocobozzz** [comment]
> Does it mean that a malicious remote instance can ignore unfollow requests, so that users can't unfollow?

No, the follow request is removed from the database. But in your logs I don't even see the HTTP request used by your PeerTube client to unsubscribe. Please can you reproduce by removing a channel from your subscriptions and confirming that you still receive notifications?

**Comment by Chocobozzz** [comment]
Thanks a lot!

The cause of the issue is the remote instance does not send back an `Accept` or `Reject` activity. Then your follow entry is still in `pending` state.

https://github.com/Chocobozzz/PeerTube/commit/d3fcf1c57ab898e18654910e880875a911fbd128 allows to delete `pending` follows so you don't have an error anymore

https://github.com/Chocobozzz/PeerTube/commit/f530dde2443f23dbb7b90dd82e84c0701e877a93 prevents the video notification when the subscription is not in `accepted` state

Regarding the follow request that is not accepted by the remote instance, I suggest to contact the remote administrator (@vincib) to do some tests and check the PeerTube logs. Don't hesitate to email them to me.

**Comment by JohnXLivingston** [comment]
> Regarding the follow request that is not accepted by the remote instance, I suggest to contact the remote administrator (@vincib) to do some tests and check the PeerTube logs. Don't hesitate to email them to me.

Could it be the same type of bug? Remote server inconsistency, and rejecting the request because it thinks that i'm in a `pending` state?

**Comment by vincib** [comment]
need help? @JohnXLivingston we could test it some day if needed :)

**Comment by JohnXLivingston** [comment]
> need help? @JohnXLivingston we could test it some day if needed :)

Yes, but i'm not really available this week.
You can check peertube logs just before I posted this comment: https://github.com/Chocobozzz/PeerTube/issues/5613#issuecomment-1547944536 (may 15, 16:12 GMT+2). The request came from `https://videos.john-livingston.fr`. There were also requests from `mamot.fr` (i think these one were ok).
