### ISSUE TITLE
Increase thumbnail resolution (or make configurable)

### ISSUE THREAD

**Issue by aeharding** [Chocobozzz/PeerTube#5618]
### Describe the problem to be solved

A large and growing segment of computer displays are running at 2x and larger pixel densities.

Currently, PeerTube thumbnail images are the same size as the actual container (1x):

<img width="595" alt="Screenshot 2023-02-17 at 9 50 50 PM" src="https://user-images.githubusercontent.com/2166114/219829988-a594229e-fa34-4638-a8d3-186b23a0cedb.png">

However, this leads to thumbnails that look noticeably blurry/low quality.

### Describe the solution you would like

Double the size of thumbnails, or greater (to allow for more flexibility in customizing the UI, for example zoom animations).

This would also align with what other video streaming platforms are doing, such as YouTube:

<img width="950" alt="Screenshot 2023-02-17 at 9 54 53 PM" src="https://user-images.githubusercontent.com/2166114/219830157-888d19c1-dde1-4cca-8f2e-15090cc64c62.png">

Lastly, mobile devices already use the larger `PREVIEWS_SIZE` as thumbnails, so increasing `THUMBNAILS_SIZE` would have no impact on mobile devices.

Similar issue, but for `PREVIEWS_SIZE`: #5464

**Comment by eddyacthergal** [comment]
Hello,
We suffer from the same prob, and we would love to have better quality resolution for thumbnail.
Maybe a way to configure it on server side (if not already available ?)

If already exists, I would be interesting to know how to do it .

Thx in advance

**Comment by gergob** [comment]
I am planning to do a PR for making the `PREVIEWS_SIZE` and `THUMBNAILS_SIZE` configurable from some of the configs. The default values would stay the same, so we maintain backwards compatibility:

```js
// Videos thumbnail size
const THUMBNAILS_SIZE = {
  width: 280,
  height: 157,
  minWidth: 150
}
const PREVIEWS_SIZE = {
  width: 850,
  height: 480,
  minWidth: 400
}
```

What do you think ?

**Comment by Chocobozzz** [comment]
Please do :)

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/3fbe84918392141e16976b952932e7eac10e99be & https://github.com/Chocobozzz/PeerTube/commit/1e3a5b25c367b47e49808b443c504769db21ebe6
