### ISSUE TITLE
The display of trends does not correspond to the settings.

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5619]
### Describe the current behavior

I have updated the server to the nightly build version **5.0.1-nightly-2023-02-18**

In the settings I have set the display of the Trends page - "Original publication date"
![1](https://user-images.githubusercontent.com/11453567/219853837-de83b609-7b50-4ee7-ad12-94733c31c0ca.jpg)

Trends are displayed on the main page "Recent Views"
![2](https://user-images.githubusercontent.com/11453567/219853952-35c28800-ff50-4244-a616-bc2e2ca47fe2.jpg)

In previous versions of nightly builds, this problem did not exist.

### Additional information

* PeerTube instance:
  * URL: https://video.ustim.ru
  * Version: 5.0.1-nightly-2023-02-18

**Comment by Chocobozzz** [comment]
Hello,

This is a mistake: we don't support "Original publication date" trending algorithm. I fixed this behaviour in https://github.com/Chocobozzz/PeerTube/commit/15825ef18d3b2bb74f4e613496cf3e2921a87389

**Comment by Alterak** [comment]
> Hello,
> 
> This is a mistake: we don't support "Original publication date" trending algorithm. I fixed this behaviour in [15825ef](https://github.com/Chocobozzz/PeerTube/commit/15825ef18d3b2bb74f4e613496cf3e2921a87389)


Hi! I installed the nightly build 5.0.1-nightly-2023-02-21 and now all the additional menu items have disappeared in the settings altogether, for example, "Original publication date"

![1](https://user-images.githubusercontent.com/11453567/220255598-ccd4cc2b-7912-4cb2-8396-648db1a41cd6.png)
![2](https://user-images.githubusercontent.com/11453567/220255614-6c5d8912-1818-473f-a1c6-3e3b6415aea5.png)

**Comment by Chocobozzz** [comment]
Yes, because original publication date is not a trending algorithm.

**Comment by Alterak** [comment]
> Yes, because original publication date is not a trending algorithm.

You added this function earlier and it worked fine... here is the request
https://github.com/Chocobozzz/PeerTube/issues/5363

**Comment by Chocobozzz** [comment]
It was a mistake. This setting only concerns the "Trending" page. It's not designed to choose the default sort.
You need to configure the setting above "Landing page" to set a custom homepage with the sort you want.

**Comment by Alterak** [comment]
> It was a mistake. This setting only concerns the "Trending" page. It's not designed to choose the default sort.
> You need to configure the setting above "Landing page" to set a custom homepage with the sort you want.

Ok. I'll try to explain ...
there are 2 ways of sorting, they are the same, only the appearance of the page changes.

Method 1 - Recently Added. This method displays videos that are separated by the time they were added. This method of the main page is very inconvenient for me, but this method is also useful and necessary in some cases.
Also, this type of sorting leads to a separate category on the left side of the menu - Recently Added
![1](https://user-images.githubusercontent.com/11453567/220300598-6cc2221b-101e-4388-a5ea-cc838049e8be.png)

Method 2 - Original Publication Date. This type of sorting also displays the most recent videos, but there is no breakdown by time of addition on the main page. I like it better and it looks beautiful!
![2](https://user-images.githubusercontent.com/11453567/220304014-4cd63e1c-acf7-4bd8-ac78-ed7a55853bb3.png)


Maybe try adding an additional drop-down list in the configuration settings panel?
For example...
If Landing page = Trending Videos, then show an additional drop-down list in which you can select any default sorting type. This function will allow you to do the desired type of sorting for the default page.
