### ISSUE TITLE
Peertube should use publishAt date for sorting video instead of createdAt by default

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#562]
Hello !

* **PeerTube version or URL:** https://videos.lecygnenoir.info
* **NodeJS version:** v8.11.1

With the new peertube version (beta4) was introduced the publishAt field that display the date of publication instead of uploaded date when you publish your video, and this is a great addition!

However I have noticed that the sort field still use createdAt when you display video, which leads to strange displaying (see attaching screenshot), where a video uploaded and published 21h ago is displayed before a video published 56min ago (and uploaded 2 days ago)
![capture d ecran de 2018-05-12 17-53-45](https://user-images.githubusercontent.com/7755000/39959272-94c47762-560f-11e8-82fc-6cd59629e124.png)

I think that using the publishAt field for sorting videos, or adding an option to sort with this field could be less disturbing for viewers.

Anyway thanks you for this job on Peertube!

**Comment by Chocobozzz** [comment]
Thanks for the issue, it should be fixed: https://github.com/Chocobozzz/PeerTube/commit/136cce4d6744bef7fd316b929157c1e4e3984fe3
