### ISSUE TITLE
I noticed a few markup issues in the nightly build 5.0.1-nightly-2023-02-18

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5620]
### Describe the current behavior

After updating the nightly build to version 5.0.1-nightly-2023-02-18 on the channels page, the buttons have become large.

![3](https://user-images.githubusercontent.com/11453567/219856543-9ce349c1-bf6f-46fe-975a-9afdf92cbbe2.jpg)

### Additional information

* PeerTube instance:
  * URL: https://video.ustim.ru
  * Version: 5.0.1-nightly-2023-02-18

**Comment by Alterak** [comment]
Also on the About page in the Statistics section, the upper part of the icons began to be cut off

![4](https://user-images.githubusercontent.com/11453567/219856625-92db709f-7a18-4e7c-9e13-2129fdf36455.jpg)

**Comment by Alterak** [comment]
I also found a problem with the markup.
I have Russian installed. The text on the registration button goes beyond this button.

![5](https://user-images.githubusercontent.com/11453567/219880545-9e6cf050-77be-4e47-a77e-13c1facaee0b.jpg)

**Comment by Alterak** [comment]
Also, the text is not displayed exactly in the comments.

![7](https://user-images.githubusercontent.com/11453567/219884491-233f412b-d289-40b4-aa46-cd86acdeb279.jpg)

**Comment by Chocobozzz** [comment]
Hello,

Please create 1 issue per problem :)
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/420a6043cc579d6fc342adcfe8107daf51664761

> Also on the About page in the Statistics section, the upper part of the icons began to be cut off

It's on purpose, it's the style of the blocks
