### ISSUE TITLE
Theme [dark 2.5.0] Keyboard shortcuts overlay not dark-themed

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#5622]
### Describe the current behavior

The 'Keyboard shortcuts' overlay is not dark themed. Please see the screenshot below:

![2023-02-18 12_07_09-About this instance - Dalek Zone — Mozilla Firefox](https://user-images.githubusercontent.com/64964084/219869846-e19c5b7b-9f9e-4bcd-b398-08ce2634d04c.png)

### Steps to reproduce

1. Go to https://dalek.zone.
2. Click on the 'Keyboard shortcuts' link in the left-hand menu.
3. The keyboard shortcuts overlay displays themed like the default light theme.

### Describe the expected behavior

When the PeerTube 'dark' theme is applied, the keyboard shortcuts overlay should be themed like, for instance, the contact form popup and overlay in the About page (see screenshot below):

![2023-02-18 16_03_12-Window](https://user-images.githubusercontent.com/64964084/219870061-fcdba3e9-f2d6-4fb3-b9d5-7240e9ebd8d9.png)

### Additional information

* PeerTube instance: Dalek Zone
  * URL: https://dalek.zone
  * Version:  Peertube version 5.0.1 and 'dark' theme version 2.5.0
  * NodeJS version: 16.19.1
  * Ffmpeg version: 4.2.7

* Browser name, version and platforms on which you could reproduce the bug: Firefox on Kubuntu 22.04 and Windows 10

**Comment by DalekDave** [comment]
A second example of what the keyboard shortcuts overlay should be styled like is the Settings pane overlay. Please see the screenshot below:


![2023-02-18 12_06_35-About this instance - Dalek Zone — Mozilla Firefox](https://user-images.githubusercontent.com/64964084/219872614-1e23238d-786d-4acf-94ed-fb0216b82798.png)

**Comment by Chocobozzz** [comment]
Hi @DalekDave 

Thanks a lot for all your issues regarding the dark theme but you need to open them on the [official plugins repository](https://framagit.org/framasoft/peertube/official-plugins/-/issues)

**Comment by Booteille** [comment]
I think this one should be fixed in core.

In [hotkeys.component.scss](https://github.com/Chocobozzz/PeerTube/blob/8cbc40b2fe9d36ef0505b9441276ca561342e9e9/client/src/app/core/hotkeys/hotkeys.component.scss) we can see we're setting colors without using available CSS variables.

We should, IMHO, use available CSS variables so any theme would have correct colors easily.

**Comment by Chocobozzz** [comment]
Fixed in core by https://github.com/Chocobozzz/PeerTube/commit/20c21606aca70717d0b6dc0060be398b06d993e7
