### ISSUE TITLE
Theme [dark 2.5.0] Terms and Code of conduct links not visible when minimized

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#5623]
### Describe the current behavior

When you start the registration flow and are presented with the Terms and Code of conduct links (in minimized state), the content that should be in the 2 boxes is invisible / not present. Please see the screenshot below:

![2023-02-18 11_52_37-Register - Dalek Zone — Mozilla Firefox](https://user-images.githubusercontent.com/64964084/219870797-576a101d-6a72-4b28-9eb6-514089512deb.png)

### Steps to reproduce

1. Go to https://dalek.zone
2. Start the registration process
3. In the page presenting the Terms and Code of conduct, you don't see any content in the 2 boxes.

### Describe the expected behavior

You should see content in the boxes like the screenshots below:

![2023-02-18 16_22_03-Window](https://user-images.githubusercontent.com/64964084/219870959-ef342c3a-f242-4c79-929f-eee518ff867b.png)

![2023-02-18 16_21_41-Window](https://user-images.githubusercontent.com/64964084/219870946-bdd2402b-7a16-4253-849e-9015339e505f.png)

### Additional information

* PeerTube instance: Dalek Zone
  * URL: https://dalek.zone
  * Version:  Peertube version 5.0.1 and 'dark' theme version 2.5.0
  * NodeJS version: 16.19.1
  * Ffmpeg version: 4.2.7

* Browser name, version and platforms on which you could reproduce the bug: Firefox on Kubuntu 22.04 and Windows 10

**Comment by DalekDave** [comment]
You can also see the same issue when logging in. Please see the screenshot below:



![2023-02-18 12_15_30-Login - Dalek Zone — Mozilla Firefox Private Browsing](https://user-images.githubusercontent.com/64964084/219871133-ed8c3386-f6b1-44da-ac36-65d73d3048f3.png)

**Comment by Booteille** [comment]
Hi!

Can you please report your issue on the [Dark theme repository](https://framagit.org/framasoft/peertube/official-plugins/-/issues)?

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/issues/5622#issuecomment-1436685622
