### ISSUE TITLE
Theme [dark 2.5.0] Login / Registration pages - site description paragraph line spacing should be 1.5

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#5624]
### Describe the current behavior

The spacing of lines in the site description paragraph (and other similarly-styled paragraphs) in the Login and Registration pages should be 1.5, not single-line spacing. Please see the screenshot below from the Login page (but the issue also exists on the Registration pages). The paragraph I mean is the one starting with "Dalek Zone hosts....":

![2023-02-18 12_15_30-Login - Dalek Zone — Mozilla Firefox Private Browsing](https://user-images.githubusercontent.com/64964084/219871615-bf432dbe-32da-44fb-bfd3-1903a5b16dd2.png)

### Steps to reproduce

1. Go to https://dalek.zone
2. Go to the Login page or Registration pages.
3. You will see the site description paragraph has styling mentioned above.

### Describe the expected behavior

The site description paragraph in the Login and Registration pages should be in 1.5 line spacing, to be more easily legible and to be consistent with other text paragraph styles.

### Additional information

* PeerTube instance: Dalek Zone
  * URL: https://dalek.zone
  * Version:  Peertube version 5.0.1 and 'dark' theme version 2.5.0
  * NodeJS version: 16.19.1
  * Ffmpeg version: 4.2.7

* Browser name, version and platforms on which you could reproduce the bug: Firefox on Kubuntu 22.04 and Windows 10

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/issues/5622#issuecomment-1436685622

**Comment by Booteille** [comment]
Hi.

This issue is not dark-theme specific and should, IMHO, be fixed in core.

In [instance-about-accordion.component.scss](https://github.com/Chocobozzz/PeerTube/blob/9f4109e263be961ab0b210fcbc003a8c78f5b9fe/client/src/app/shared/shared-instance/instance-about-accordion.component.scss) we can see we're calling `ellipsis-multiline(1rem, 3)`. I guess we should maybe use there 1.5rem.

**Comment by Chocobozzz** [comment]
Sorry, I didn't read carefully the issue. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/2987c34e454aa4d1539e638a2f913097e0fd1edc
