### ISSUE TITLE
Theme [dark 2.5.0] progress icons in the Registration flow header are insufficiently contrasting with page background

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#5625]
### Describe the current behavior

The progress icons in the Registration flow header are insufficiently contrasting with the page background. You can see this in the screenshot below:

![2023-02-18 12_14_39-Register - Dalek Zone — Mozilla Firefox Private Browsing](https://user-images.githubusercontent.com/64964084/219872234-2c040547-e103-45eb-9267-df09b6a1359f.png)

### Steps to reproduce

1. Go to https://dalek.zone.
2. Start the Registration process.
3. The progress icons in the process flow header are low contrast and not very visible.

### Describe the expected behavior

The inactive progress icons (and the active progress icon) and the joining lines between them should be more visible.

The currently-active icon could have a glow halo around it to make it stand out better.

### Additional information

* PeerTube instance: Dalek Zone
  * URL: https://dalek.zone
  * Version:  Peertube version 5.0.1 and 'dark' theme version 2.5.0
  * NodeJS version: 16.19.1
  * Ffmpeg version: 4.2.7

* Browser name, version and platforms on which you could reproduce the bug: Firefox on Kubuntu 22.04 and Windows 10

**Comment by DalekDave** [comment]
To be absolutely clear, here is a page snip of the icons I mean:


![2023-02-18 11_50_08-Register - Dalek Zone — Mozilla Firefox](https://user-images.githubusercontent.com/64964084/219872753-5968cf55-efa4-456c-a3c5-68ed9fb3b8e0.png)

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/issues/5622#issuecomment-1436685622
