### ISSUE TITLE
Theme [dark 2.5.0] instance name in instance name box in various pages - not visible because of non-contrasting font color

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#5626]
### Describe the current behavior

The instance name in the instance name box in various pages (registration and channel creation pages) is illegible / invisible because of the font color. Please see the screenshots below:

![2023-02-18 11_33_28-](https://user-images.githubusercontent.com/64964084/219874787-ea4755ed-ac3d-4c93-8de0-4a5280e2f82f.png)

![2023-02-18 11_49_38-Register - Dalek Zone — Mozilla Firefox](https://user-images.githubusercontent.com/64964084/219874842-e014a9fb-a45c-45a3-87bd-62d86260efd1.png)

### Steps to reproduce

1. Go to https://dalek.zone
2. Go through the registration process.
3. You will see that the instance name shown when you create your username is not visible because of the font color.

### Describe the expected behavior

The instance name should be clearly visible and readable.

### Additional information

* PeerTube instance: Dalek Zone
  * URL: https://dalek.zone
  * Version:  Peertube version 5.0.1 and 'dark' theme version 2.5.0
  * NodeJS version: 16.19.1
  * Ffmpeg version: 4.2.7

* Browser name, version and platforms on which you could reproduce the bug: Firefox on Kubuntu 22.04 and Windows 10

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/issues/5622#issuecomment-1436685622

**Comment by Booteille** [comment]
Hi!

IMHO this should be fixed in core by adding a background-color based on a variable for .input-group-text in bootstrap.scss:
https://github.com/Chocobozzz/PeerTube/blob/393f9d396cdbe39e50856859a44f3996a2bc76f9/client/src/sass/bootstrap.scss#L349

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/0b38e69dc1f196785545b20bc57a5d1b678aa5a1
