### ISSUE TITLE
Theme [dark 2.5.0] non-contrasting spinner up/down arrows in various controls of options in admin interface

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#5627]
### Describe the current behavior

The spinners of various controls for options in the admin interface are not clearly visible because of insufficiently-contrasting foreground / font color. Please see the screenshots below:

![2023-02-18 17_33_14-Window](https://user-images.githubusercontent.com/64964084/219875452-8e5c0bcc-c210-4c0f-842c-8caf25d1d8d6.png)

![2023-02-18 17_33_37-Window](https://user-images.githubusercontent.com/64964084/219875460-561ebcb0-6d46-4d1e-a5ca-2495a5048026.png)

![2023-02-18 17_34_03-Window](https://user-images.githubusercontent.com/64964084/219875465-d2a61d9f-ab53-4e81-a47f-b86f14724bb7.png)

![2023-02-18 17_34_35-Window](https://user-images.githubusercontent.com/64964084/219875474-1d4cea47-d788-46a4-95c9-b0b521501bf7.png)

![2023-02-18 17_34_58-Window](https://user-images.githubusercontent.com/64964084/219875482-c43eb3fe-d5be-4475-b2a8-096ba18a58f2.png)

![2023-02-18 17_35_14-Window](https://user-images.githubusercontent.com/64964084/219875490-3870945e-e636-4acb-8ccd-9f95ce37d148.png)

### Steps to reproduce

1. Go to the admin interface of a site themed with the PeerTube 'dark' theme version 2.5.0
2. You will see that the up and down arrows of the spinners of various controls are not clearly visible

### Describe the expected behavior

The up and down arrows of spinner controls should be clearly legible.

### Additional information

* PeerTube instance: Dalek Zone
  * URL: https://dalek.zone
  * Version:  Peertube version 5.0.1 and 'dark' theme version 2.5.0
  * NodeJS version: 16.19.1
  * Ffmpeg version: 4.2.7

* Browser name, version and platforms on which you could reproduce the bug: Firefox on Kubuntu 22.04 and Windows 10

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/issues/5622#issuecomment-1436685622

**Comment by Booteille** [comment]
Hi.

I think this issue could be probably fixed in core by managing the way spinners are displayed for `input[type="number"]`.
Their `color` and `background-color` should be bound to a variable so any theme would have their spinners following their colors set.

**Comment by Chocobozzz** [comment]
Unfortunately it doesn't seem easy to style the number input: https://stackoverflow.com/questions/26024771/styling-an-input-type-number
