### ISSUE TITLE
Theme [dark 2.5.0] scroll bars in various controls for options in the admin interface are insufficiently contrasted

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#5628]
### Describe the current behavior

The scroll bars in various controls for options in the admin interface are insufficiently contrasted. The background color of the scroll bar does not stand out sufficiently against the page background. Please see the screenshot below for one example (all other scroll bars currently look similar):

![2023-02-18 17_37_33-Window](https://user-images.githubusercontent.com/64964084/219875795-c64b8cf0-91d3-48de-b73a-02353aea4aa2.png)

### Steps to reproduce

1. Go to the admin interface of a PeerTube site themed with the PeerTube 'dark' theme version 2.5.0.
2. You will see that scroll bars of smaller controls (especially) are not user-friendly to use because of the low-contrast background of the scroll bar and the small size of the draggable scroll button.

### Describe the expected behavior

The background of scroll bars should stand out better, so that the scroll bar control can be clearly recognized and easily used.

### Additional information

* PeerTube instance: Dalek Zone
  * URL: https://dalek.zone
  * Version:  Peertube version 5.0.1 and 'dark' theme version 2.5.0
  * NodeJS version: 16.19.1
  * Ffmpeg version: 4.2.7

* Browser name, version and platforms on which you could reproduce the bug: Firefox on Kubuntu 22.04 and Windows 10

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/issues/5622#issuecomment-1436685622
