### ISSUE TITLE
Theme [dark 2.5.0] Text boxes need a differently colored background to stand out properly in the page

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#5629]
### Describe the current behavior

Text boxes (and editing boxes plus other similar controls) need a differently colored background so that they stand out against the page background. At the moment, only the frame color distinguishes them from the page background.
Please see screenshot 1 below for the current styling, and screenshot 2 for another control with a background color that could possibly be used for the solution (it might need to be adjusted so that the frame / border color is still well-contrasted):

Screenshot 1:

![2023-02-18 11_44_58-Register - Dalek Zone — Mozilla Firefox](https://user-images.githubusercontent.com/64964084/219876317-66e52653-a26a-4eed-8767-4837b47b57df.png)

Screenshot 2:
The background color of the 'Video quota' control could be chosen for the solution to this issue:

![2023-02-18 12_29_18-Users list - Dalek Zone — Mozilla Firefox Private Browsing](https://user-images.githubusercontent.com/64964084/219876371-45c93bc0-0284-4df2-b074-e37c94a0f0cd.png)

### Steps to reproduce

1. Go to many pages of a PeerTube site themed with the PeerTube 'dark' theme version 2.5.0
2. The text boxes and editing boxes can only be identified because of their frame / border color.

### Describe the expected behavior

Text boxes (and editing boxes plus other similar controls) need a differently colored background in relation to the page background, as well as a contrasting frame / border color, for better legibility / styling.

### Additional information

* PeerTube instance: Dalek Zone
  * URL: https://dalek.zone
  * Version:  Peertube version 5.0.1 and 'dark' theme version 2.5.0
  * NodeJS version: 16.19.1
  * Ffmpeg version: 4.2.7

* Browser name, version and platforms on which you could reproduce the bug: Firefox on Kubuntu 22.04 and Windows 10

**Comment by Booteille** [comment]
Hi.

I think this one is bound to https://github.com/Chocobozzz/PeerTube/issues/5626 and could be fixed in core.
