### ISSUE TITLE
Please correct the headlines of various countries

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5631]
### Describe the problem to be solved

If the user wants to change the interface language, then he sees a list of different countries. At the same time, some countries start with a capital letter, and some with a small letter.
I highlighted some of them in the screenshot. Unfortunately, Asian countries are displayed in hieroglyphs, so I can't identify the first character. Perhaps it may offend some if his country is written starting with a small letter.
![6](https://user-images.githubusercontent.com/11453567/219881953-b92ab8c1-7cf7-4b98-8d6a-b4ea1b7385ac.jpg)

If you go to WebLate, then all countries start with a capital letter.

### Describe the solution you would like

Please make all countries with a capital letter.

**Comment by paymanzafar1** [comment]
Hello,
I think it is a good feature for administrator to be able to define the required languages.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/f069b90114070735f16d21f3bdfa1117fe3bacc2
