### ISSUE TITLE
Change mouse pointer to hand pointer

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5634]
### Describe the current behavior

In the video stats window, in the Viewers tab, after you select a part of the graph, the "Reset zoom" link below the expanded graph should have a hand pointer.

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks, fixed in https://github.com/Chocobozzz/PeerTube/commit/a6f214d462c19b061bbbbb08acc1411bf3bf2445
