### ISSUE TITLE
The problem with styles in 5.0.1-nightly-2023-02-21

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5637]
### Describe the current behavior

In the nightly build version 5.0.1-nightly-2023-02-21 there was a problem with styles.

Most of the items were displayed incorrectly.
This is a problem in all sections of Pertube.

For example
![1](https://user-images.githubusercontent.com/11453567/220254138-f992fc97-e7f3-4635-b6cc-6aea875da900.png)

### Additional information

* PeerTube instance:
  * URL: https://video.ustim.ru
  * Version: 5.0.1-nightly-2023-02-21

**Comment by Chocobozzz** [comment]
Oup's, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/667d909b665f59f8ec3c08724e118d311e38b332
