### ISSUE TITLE
Error when try prune-storage.js

### ISSUE THREAD

**Issue by kirill2400** [Chocobozzz/PeerTube#5638]
### Describe the current behavior

Error when try [prune-storage.js](https://docs.joinpeertube.org/maintain-tools?id=prune-storagejs)
[Error: Unknown system error -117: Unknown system error -117, scandir '/hdd/storage/torrents/'] {
  errno: -117,
  code: 'Unknown system error -117',
  syscall: 'scandir',
  path: '/hdd/storage/torrents/'
}

### Steps to reproduce

1. Idk

### Describe the expected behavior

Cleaning Up Unused Files

### Additional information

* PeerTube instance:
  * URL: https://spacecomfort.miracleinsense.ru
  * Version: 5.0.1
  * NodeJS version: v16.19.0
  * Ffmpeg version: 4.4.3-0ubuntu1~20.04.sav2

* Browser name, version and platforms on which you could reproduce the bug: Opera GX Latest (LVL 4 (core: 94.0.4606.107))
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by kirill2400** [comment]
Just discovered a bug in processing one of the new videos
![image](https://user-images.githubusercontent.com/30482699/220292362-87bbe211-b2fa-47bf-b119-240e4c5d77aa.png)

**Comment by kirill2400** [comment]
The other day I was updating Peertube from a version below 5.0.0, because periodically the server completely hung for a while while processing some videos. During the migration I was getting multiple missing files errors (three videos that were shared internally)

**Comment by kirill2400** [comment]
Another question, is there a way to increase the storage? I have a hard drive of 1 terabyte will soon run out, how can I expand the disk without resorting to, for example, a raid 0 array

**Comment by Alterak** [comment]
> Another question, is there a way to increase the storage? I have a hard drive of 1 terabyte will soon run out, how can I expand the disk without resorting to, for example, a raid 0 array

You can make RAID5, but you will need at least 3 disks. You can use ZFS, or you can use S3.
There are many options and it's up to you to decide-)

**Comment by Chocobozzz** [comment]
Hello,

It seems there is an issue with your disk or your filesystem (maybe corrupted) that is not related to PeerTube.

**Comment by kirill2400** [comment]
> Hello,
> 
> It seems there is an issue with your disk or your filesystem (maybe corrupted) that is not related to PeerTube.

Is there a script in peertube to migrate storage to another location?

**Comment by Alterak** [comment]
> Is there a script in peertube to migrate storage to another location? With saving all videos?

If from one disk to another, then simply transfer (or copy) the /var/www/pertube/storage directory to another disk.
If you will transfer to S3 storage, then there is a script https://docs.joinpeertube.org/maintain-tools?id=create-move-video-storage-jobjs

**Comment by kirill2400** [comment]
> > Is there a script in peertube to migrate storage to another location? With saving all videos?
> 
> If from one disk to another, then simply transfer (or copy) the /var/www/pertube/storage directory to another disk. If you will transfer to S3 storage, then there is a script https://docs.joinpeertube.org/maintain-tools?id=create-move-video-storage-jobjs

So can I use one more pc as s3 server?
