### ISSUE TITLE
Playback error via iframe. 5.0.1-nightly-2023-02-19

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5639]
### Describe the current behavior

After installing the nightly build version 5.0.1-nightly-2023-02-19 many users began to complain about the video playback.

![image](https://user-images.githubusercontent.com/11453567/220329119-89ec0b9f-9eb2-4871-81bc-1b372d214aed.png)

The problem is only on the Iphone
iPhone OS 12_5
iPhone OS 15_7
iPhone OS 16_1_1
iPhone OS 16_2

All the videos were embedded on various sites via the Iframe code
For example, like this:

`<iframe title="Большой брат (2018)" width="560" height="315" src="https://peervideo.ru/videos/embed/ce72e560-341e-4d82-a765-cff095e15a12" frameborder="0" allowfullscreen="" sandbox="allow-same-origin allow-scripts allow-popups"></iframe>`

Not everyone has a problem... I couldn't reproduce it, but several users are complaining right now... it doesn't work for them-(

### Additional information

* PeerTube instance:
  * URL: https://peervideo.ru
  * Version: 5.0.1-nightly-2023-02-19
  * NodeJS version: v16.19.0
  * Ffmpeg version: 4.3.5-0+deb11u1

**Comment by Alterak** [comment]
Forced to roll back to version 5.0.1-nightly-2023-02-15 . Users said that everything works.

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/39a88d24c7d32e5e17f3741266226525fe6363d8
