### ISSUE TITLE
The buttons have become large. The problem has not been fixed. 5.0.1-nightly-2023-02-22

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5640]
### Describe the current behavior

I have already made a request about the big buttons. The problem has not been fixed.
https://github.com/Chocobozzz/PeerTube/issues/5620

In the nightly build version 5.0.1-nightly-2023-02-22 if you go to the user's channel, the buttons are displayed in different sizes.
Also, the "Subscriptions" button has uneven curves
For example this channel https://peervideo.ru/c/alterak_channel/videos

![1](https://user-images.githubusercontent.com/11453567/220537910-965080c4-e045-4014-95f6-7e47010a4407.png)

### Steps to reproduce

1. Open the user channel
2. Large buttons. It looks ugly.

### Describe the expected behavior

All buttons should be small, the same size as it was before.

### Additional information

* PeerTube instance:
  * URL: https://peervideo.ru
  * Version: 5.0.1-nightly-2023-02-22

**Comment by Chocobozzz** [comment]
Hi,

Thanks again. It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/b849adf9d807a59de23a0e4983417e213fee2beb

If you notice other button UI bug, you can comment this issue!
