### ISSUE TITLE
Select desired languages in "change the language" window

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5641]
### Describe the problem to be solved

It is a good feature for admin to be able to select the desired languages in "change the language" window.

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I don't understand. Please correctly fill the feature request template

**Comment by InformaticaJBM** [comment]
Hi, I think topic starter mean, have possibility to choose languages that shows in change user language option. Now there are all known languages. Its can be done on a server side, but not from admin panel.
