### ISSUE TITLE
Missing grafana's dashboard for Peertube

### ISSUE THREAD

**Issue by drym3r** [Chocobozzz/PeerTube#5643]
### Describe the desired information/correction

Hello there.

I saw that the offered grafana dashboard can't be found in the [documentation page](https://docs.joinpeertube.org/maintain-observability?id=visualize-data-in-grafana). It points to a non existing file, `monitoring.json`.

![image](https://user-images.githubusercontent.com/7255473/220911129-076224e7-56a2-4310-a8c4-f0442a1be58f.png)

Also, if possible it would be really cool to add the dashboard to grafana.com, since there's plugin to automatically download dashboards from their ID. But the main thing would be restore the dashboard anywhere.

Thanks for your work!

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://framagit.org/framasoft/peertube/documentation/-/commit/cb4e8181b6238ebed1309201c3ca5cc83a8f7cdf.  Please open the issue on https://framagit.org/framasoft/peertube/documentation/-/issues for documentation issues!

**Comment by drym3r** [comment]
Thanks for being so quick, and sorry for open it here!
