### ISSUE TITLE
Problem While Importing Videos Using the API: The thumbnails aren't being imported

### ISSUE THREAD

**Issue by syhammer** [Chocobozzz/PeerTube#5645]
### Describe the desired information/correction

Hello everyone!

I have a project (the programming language is Python) where I'm uploading videos from one application and migrating them to PeerTube. I'm using the "Import Video" API call and this is the data being passed to the API:

```python
data = {
            'channelId': channel_id,
            'name': video['title'][:max_title_length]+'...' if len(video['title']) > max_title_length else video['title'],
            'targetUrl': videoUrl,
            'commentsEnabled': True,
            'downloadEnabled': video['can_download'],
            'language': 'en',
            'nsfw': False,
            'originallyPublishedAt': video['videoCreation'],
            'privacy': 4,
            'thumbnailfile': getImageBinary(video['images']['posterLandscapeThumbs']),
            'waitTranscoding': False,
        }
```

Here is the "getImageBinary" function:

```python
def getImageBinary(url):
    response = requests.get(url,stream=True)
    response.raw.decode_content = True
    with open(test_file,'wb') as out:
        shutil.copyfileobj(response.raw,out)
    with open(test_file,'rb') as file:
        png_encoded = base64.b64encode(file.read())
        encoded_b2 = "".join([format(n, '08b') for n in png_encoded])
        return encoded_b2
```

The "url" argument is the URL to the image that I want as the thumbnail. But to sum up what this function does:

* It saves the image to a test file
* Opens the file
* And then returns the image as a binary string (as required in the API reference)

But the API doesn't recognize it and auto-generates a thumbnail. I've tried passing in a byte string, binary string (above), and the URL but none of those formats were valid to the API.

Thank you all for your time. If you have any solutions or suggestions, please let me know.

**Comment by Chocobozzz** [comment]
Hello,

Please use the forum for PeerTube REST API support https://framacolibri.org/c/peertube :)

**Comment by syhammer** [comment]
For anyone with this same problem, this issue is being continued [here](https://framacolibri.org/t/problem-while-importing-videos-using-the-api-the-thumbnails-arent-being-imported/17071).
