### ISSUE TITLE
PeerTube no longer supports older browsers

### ISSUE THREAD

**Issue by artenax** [Chocobozzz/PeerTube#5647]
### Describe the current behavior

I go to https://peervideo.ru/ and see an error: "PeerTube Incompatible browser. We are sorry but it seems that PeerTube is not compatible with your web browser."

### Steps to reproduce

1. Go to https://peervideo.ru/

### Describe the expected behavior

I want to be able to watch the video. Or better still uploading.

I noticed that in Firefox 60 I can't even go to the site and watch videos now. This is a shame, because YouTube supports older browsers.

I think it has to do with the polyfills that are popular now. You rely on their implementation in the browser, but you could have loaded them with js, like DeepL does, for example.

### Additional information

* PeerTube instance:
  * Version: 5.0.1-nightly-2023-02-24

Firefox 60, Ubuntu 16.04 i386.

**Comment by Chocobozzz** [comment]
Hello,

PeerTube supports Firefox >= 68. Unfortunately we don't have enough resources to support older web browsers.
