### ISSUE TITLE
Some videos are not displayed in the admin section. 5.0.1-nightly-2023-02-24

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5650]
### Describe the current behavior

The **Administrations->Overview->Videos** section now does not display videos for which the NSFW function is installed.
Although ALL videos should be displayed in this section.

### Describe the expected behavior

All videos should be displayed as it was before.

### Additional information

* PeerTube instance:
  * Version: 5.0.1-nightly-2023-02-24

**Comment by Chocobozzz** [comment]
Thanks! Fixed by https://github.com/Chocobozzz/PeerTube/commit/357308ce22e235428ee5c48aaca9308ed194c01a
