### ISSUE TITLE
Options: API search for all Instances videos

### ISSUE THREAD

**Issue by Pantyhose-X** [Chocobozzz/PeerTube#5655]
### Describe the problem to be solved

Most instances have no users at all using and watching the video, What is the point of such instances ! |

Allow instance administrators, to enable or disable the instance search API

### Describe the solution you would like

Demonstrationv
`api.peertube.cpy.re/search?search=`  -- administrators to enable instance search API, Search scope ( title, tags )

### APPS
The software only needs to import .json to search and watch videos, and it works with all PeerTube instances

### Example
.json 
```
api.peertube.cpy.re/search?search=
api.peertube2.cpy.re/search?search=
api.peertube3.cpy.re/search?search=
```

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I don't understand. Can you give more details about the use case this issue is supposed to resolve?

**Comment by Pantyhose-X** [comment]
> Hello,
> 
> I'm sorry but I don't understand. Can you give more details about the use case this issue is supposed to resolve?

Just like https://joinpeertube.org/browse-content
 can search any public instance.
But I think instance administrators can forbid, searching for their own private instances,
Instances should be divided into public instances and private instances.


I've used [Thorium](https://f-droid.org/en/packages/net.schueller.peertube/) and [TubeLab](https://f-droid.org/en/packages/app.fedilab.tubelab/), and they only have a few examples built in, not what I'm looking for, 
There is no single APPS that searches all public instances of PeerTube, which I think is the reason why people don't use PeerTube much

**Comment by Chocobozzz** [comment]
You can find instances on https://joinpeertube.org/instances
Videos on public instances can be found on https://sepiasearch.org/
