### ISSUE TITLE
[Theming] Close button always white on hover in Hotkey component

### ISSUE THREAD

**Issue by Booteille** [Chocobozzz/PeerTube#5656]
### Describe the current behavior

On the keyboard shortcuts page, when hovering the close button, its background will be white, even if you're using a dark theme.

Check this line : https://github.com/Chocobozzz/PeerTube/blob/393f9d396cdbe39e50856859a44f3996a2bc76f9/client/src/app/core/hotkeys/hotkeys.component.scss#L91

### Steps to reproduce

1. Click on Keyboard shortcuts
2. Hover the close button, on the top right

### Describe the expected behavior

We should use a variable, instead of fixed background color, so the button would follow the theme colors set.

### Additional information

* PeerTube instance:
  * URL: localhost
  * Version: Develop
  * NodeJS version: 19.7.0
  * Ffmpeg version: 4.4.2

* Browser name, version and platforms on which you could reproduce the bug: Firefox V110.0
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/a9816e189ac8f2a078e480b9db9e3e0e9e9b2b53
