### ISSUE TITLE
v5.1.0-rc.1: minimal recommanded redis version

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5659]
### Describe the problem

According to v5.1.0-rc.1 release notes, «Minimum recommended Redis version is 6.2».

But for Debian Stable, the Redis server version is 6.0:
https://packages.debian.org/bullseye/redis-server

Note: v7.0 is available in bullseye-backport: https://packages.debian.org/bullseye-backports/redis-server

Will Redis 6.0 work? Or will it be broken?

I think Peertube should be able to use Debian stable repository for databases servers (postgresql and redis), because of well-known Debian stability. And it will be more complicated to install for people who are not very familiar with system administration.

### Additional information

* PeerTube version: v5.1.0-rc.1
* Redis version: 6.0

**Comment by vid-bin** [comment]
> I think Peertube should be able to use Debian stable repository for databases servers (postgresql and redis), because of well-known Debian stability.

I disagree. Debian stable is outdated. I think the current postgresql version is 13 on their repository (haven't checked) and the latest version is 15.2. So it's already two versions out of date.

I use debian stable as a base because I'm familiar with it but I've had to replace a lot of software with third party mirrors or manually compiled them because the versions are so outdated.

**Comment by aeharding** [comment]
I'm also using redis v6.0.

I can understand both viewpoints. My only input is if redis v6.2 is required but debian stable installs 6.0 by default, I think [the installation/dependency guide](https://docs.joinpeertube.org/support/doc/dependencies#debian-ubuntu-and-derivatives) should be updated with guidance to install the proper version.

**Comment by JohnXLivingston** [comment]
> I disagree. Debian stable is outdated. I think the current postgresql version is 13 on their repository (haven't checked) and the latest version is 15.2. So it's already two major versions/releases out of date.

Administrating production servers is not a race to the last features. Database systems (as postgresql or redis) have LTS policies. For example, Postgresql 13 will have active support until 2025: https://www.postgresql.org/support/versioning/
Redis is maintained for the current major version and the previous one: https://redis.io/docs/about/releases/#support

In production, it is always best to have highly-tested version for database softwares. And that is not always the last major version. Many administrators appreciate Debian for its lifecycle: long term version, stable for years.

**Comment by Chocobozzz** [comment]
Hello,

The recommended version is coming from a PeerTube dependency: https://github.com/taskforcesh/bullmq/issues/1594#issuecomment-1358928178

6.0 should still work, it's the reason why I did not update the dependency guide knowing that the default Debian version is still 6.0.
I'll add a note in the changelog

**Comment by Sakrecoer** [comment]
@JohnXLivingston is it safe to assume that you had no issues while remaining on redis 6.0 ? :)

**Comment by JohnXLivingston** [comment]
> @JohnXLivingston is it safe to assume that you had no issues while remaining on redis 6.0 ? :)

I did not see any issue. Transcoding works fine, mails jobs too, .... (I now have 4 instances using v5.1.0)

**Comment by Sakrecoer** [comment]
Many thanks @JohnXLivingston ! Worked fine for me too! \o/
