### ISSUE TITLE
v5.1.0-RC1: new parameter requires_approval default value

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5660]
### Describe the problem

In the newly published v5.1.0-RC1 version, the new parameter requires_approval is set to true by default (in the default.yml file).

This means that admins who update without checking new parameters will change their instance behaviour without knowing.

We know that for some instances, admins don't respond to notifications. So, it could be possible that new users got stuck forever with such a feature.

I have mixed feelings about it. I don't know if this is a good or bad thing. (if it could prevent spam account creation on instances that are well-know for not moderating comments, why not :wink: )

Have you thought about it? Have you listed pros and cons?

**Comment by Booteille** [comment]
I guess we could at least add this information in `IMPORTANT NOTES` section of the release?

**Comment by JohnXLivingston** [comment]
> I guess we could at least add this information in `IMPORTANT NOTES` section of the release?

I agree.

**Comment by Chocobozzz** [comment]
Added in https://github.com/Chocobozzz/PeerTube/commit/aa8478f374b375167f048bbf6703a02b0b5a89df
