### ISSUE TITLE
[Theming] Channels avatar automatically generated (with a letter) are improperly aligned on home page

### ISSUE THREAD

**Issue by Booteille** [Chocobozzz/PeerTube#5662]
### Describe the current behavior

Consider following screenshots:

User uploaded avatar, inserted with a `<img>` element:
![Capture d’écran du 2023-03-01 19-11-11](https://user-images.githubusercontent.com/2203721/222226548-14985b63-4220-4630-9ba5-dbd5fa14a3d0.png)

Automatically generated avatar, inserted with a `<div>` element:
![Capture d’écran du 2023-03-01 19-11-00](https://user-images.githubusercontent.com/2203721/222226551-39820c9a-61c3-4cb5-9862-8aec3fe625a1.png)

### Steps to reproduce

1. Visit https://aperi.tube/videos/overview

### Describe the expected behavior

Automatically generated avatars should be aligned in the same way as uploaded avatars.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/pull/5667
