### ISSUE TITLE
Comments from Mastodon users don't have avatars

### ISSUE THREAD

**Issue by aeharding** [Chocobozzz/PeerTube#5663]
### Describe the current behavior

Avatars from non-peertube users aren't showing up in comments.

### Steps to reproduce

View comment from fedi.video on this video:

https://urbanists.video/w/8LXF512yXZokjipuahB6Lx;threadId=3405

Notice avatar doesn't appear.

Visit their profile (via PeerTube), notice there is an avatar:

https://urbanists.video/a/FediVideo@social.growyourown.services/video-channels

### Describe the expected behavior

Avatars should be properly displayed for mastodon users on peertube video comments.

### Additional information

* PeerTube instance:
  * URL: https://urbanists.video
  * Version: v5.0.1

* Browser name, version and platforms on which you could reproduce the bug: Firefox

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/e2d8587bd36239f0ba0be59a9185682072a392fc
