### ISSUE TITLE
S3 Storage not used for every videos (?)

### ISSUE THREAD

**Issue by Nalem14** [Chocobozzz/PeerTube#5670]
### Describe the current behavior

I can see that my Storage folder is heavy, but I use an S3 storage to store videos
I have tried some time to launch job to move all video to s3 storage, but I continue having a big storage folder

### Steps to reproduce

(unknown)

### Describe the expected behavior

When I use the S3 storage I don't want that videos are stored localy. Do you have any idea of what are the problem ? It is a bug ?

### Additional information

* PeerTube instance:
  * URL: https://orion-hub.fr
  * Version: 5.x
  * NodeJS version: 16.x
  * Ffmpeg version:

Storage used (see /videos and /streaming-playlists):
```
root@mckay:/var/www/peertube/storage# du -hs ./*
114M	./avatars
11M	./bin
16K	./cache
11M	./captions
372K	./client-overrides
926M	./logs
1.3G	./plugins
409M	./previews
28G	./redundancy
470G	./streaming-playlists
1.4G	./thumbnails
20K	./tmp
208M	./torrents
145G	./videos
4.0K	./well-known
```

**Comment by Chocobozzz** [comment]
Can you run https://docs.joinpeertube.org/maintain/tools#create-move-video-storage-job-js and display the output?

**Comment by Nalem14** [comment]
> Can you run https://docs.joinpeertube.org/maintain/tools#create-move-video-storage-job-js and display the output?

Hello and thank your for your answer :)
I run this every day since 3 days, I have started it and send it to you when it is finished.

Also here is my current bucket used space:
![image](https://user-images.githubusercontent.com/1911357/223223370-71373fbb-cb0a-4c43-a1df-a9ea50947c7c.png)


So it is working, but some videos are not uploaded for unknown reason.

**Comment by Nalem14** [comment]
[test.txt](https://github.com/Chocobozzz/PeerTube/files/10902601/test.txt)
@Chocobozzz Here is the full output

**Comment by Nalem14** [comment]
I just seen that I have failed jobs with that errors
![image](https://user-images.githubusercontent.com/1911357/223234627-1aa661fe-38f0-42f7-a049-f6bbd9bb7d9d.png)
![image](https://user-images.githubusercontent.com/1911357/223234865-26507189-753b-4ade-a6d6-87dd49853cde.png)

(The 'RangeError: data is too long' is the more common error I see)

**Comment by Chocobozzz** [comment]
Thanks, 

For the first screen, can you paste the output of the following sql command (replace *'video of job 10617*)?

```sql
select "videoFile".* from video 
inner join "videoStreamingPlaylist" ON "videoStreamingPlaylist"."videoId" = video.id 
inner join "videoFile" ON "videoFile"."videoStreamingPlaylistId" = "videoStreamingPlaylist".id 
where video.uuid = 'video of job 10617';
```

For the second screen see https://github.com/Chocobozzz/PeerTube/issues/5525

**Comment by Nalem14** [comment]
Thanks four your help I have applied the change for max upload part and run the move to object storage again.

Here is the result of the SQL command
![image](https://user-images.githubusercontent.com/1911357/223384812-92b875fa-bb0b-463b-abbd-7d650db4cad0.png)

**Comment by Chocobozzz** [comment]
Thanks, the second error should be fixed by https://github.com/Chocobozzz/PeerTube/commit/9c84bf515691bad77ea4befbaf1f866c11c5dadd
