### ISSUE TITLE
Live Streaming not working when domain proxy to Cloudflare

### ISSUE THREAD

**Issue by upcastvideo** [Chocobozzz/PeerTube#5671]
### Describe the current behavior

Hi,

I created an instance through docker installation. My domain was first mapped from my domain registar straight to my cloud service dns manager without Cloudflare, live streaming was working well at that time, I test it several times. After that I mapped the domain from my domain registar straight to Cloudflare, and now live streaming doesn´t work. When using any client, it always get a connection rejected message.

### Steps to reproduce

1. Create instance with docker installation
2. Connect domain to server without Cloudflare
3. Live streaming working
4. Connect domain to Cloudflare
5. Live streaming not working (connection rejected)
6. Opened port 1935/tcp and reboot server
7. Live streaming not working (connection rejected)

### Describe the expected behavior

I expect the live streaming to be working as it was before I connected the domain to Cloudflare

### Additional information

* PeerTube instance:
  * URL: https://upcast.work
  * Version: 5.0.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: safari, brave, firefox
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by vid-bin** [comment]
I haven't tried this but what happens if you create a subdomain that points to your server IP (not cloudflare) and you use the port with it? Or how about the server ip+port instead of a domain name?

Unfortunately with the domain pointed at cloudflare you can't direct the port to the servers real ip address unless there is an option I missed.

**Comment by upcastvideo** [comment]
Well if you use Peertube instance with subdomain while your domain is not mapped to Cloudflare, then it will be the same as if you use the domain name, it will work. When using Peertube with a domain without Cloudflare, live streaming works smoothly, the problem is when you proxy the domain.  

So far as per my research, port 1935 is not part of the allowed default ports in Cloudflare, so will need to buy an enterprise plan in order to able to open custom ports

**Comment by Chocobozzz** [comment]
Hello,

Thanks for your issue but it seems to not be related to PeerTube. Please use [the forum](https://framacolibri.org/c/peertube) for PeerTube related support/questions.
