### ISSUE TITLE
Different encoding profiles for resolutions / FPS

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#5672]
### Describe the problem to be solved

This has been brought up in the past but I did a quick search and didn't see any open issue.

It would be nice if we could have different encoding profiles for resolution and FPS.

Example:

I am testing av1_qsv (intel arc gpus) and the setup appears to lack crf/qp which means I am limited to one set b:v for all resolutions and FPS.

Problem:

Instance is set to 480p/1080p/1440p transcodes using a custom profile from transcoding-profile-debug.

At 60FPS, from one 1440p source file:

1440p is encoded at 5.3Mbps - great, that's within the 6Mbps limit I specified.
1080p is encoded at 5.2Mbps.. not so great.
480p is encoded at 4.3Mbps..

With the bitrate being so similar on different resolutions I might as well just limit my entire peertube instance to one resolution.

### Describe the solution you would like

Add different encoding profiles for resolutions and FPS.

**Comment by vid-bin** [comment]
Yeah after looking around it is a driver bug - https://github.com/intel/media-driver/issues/1597

Would still like to see the ability to use different profiles for both resolutions and fps. It would allow instance owners to fine tune their encoding settings. Would donating any money help towards this?

**Comment by Chocobozzz** [comment]
Hello,

Can https://github.com/Chocobozzz/PeerTube/issues/4285 solve your issue?

**Comment by vid-bin** [comment]
Ah yeah, it's been a while. Issue #4285 doesn't really address the problem though.

After thinking it through the attached image would be one way of doing this.

It would be even better if we could have different transcoding profiles for 30-60 fps content as well.

Would donating money help this become a reality? It's been a feature I've been looking forward to / wanting for a while now.

![transcoding-profile](https://user-images.githubusercontent.com/112714131/223248222-334b19f0-2455-4656-8914-cea52344041f.jpg)

**Comment by Chocobozzz** [comment]
> After thinking it through the attached image would be one way of doing this.

The configuration and the UI would be too complex for this specific use case. And your mockup doesn't take into account FPS. It's the reason why I think the plugin should be in charge to specify if the transcoding profile should be used for the specific input file.

**Comment by Chocobozzz** [comment]
> Isn't there a blanket statement for the transcoding profile like pix_fmt in the code?

Yes there is: https://github.com/Chocobozzz/PeerTube/issues/5270

Closing this issue in favour of https://github.com/Chocobozzz/PeerTube/issues/4285 where you would be able to specify a profile depending on video resolution/height. For now there is no easy way to achieve such result.

**Comment by vid-bin** [comment]
Right, but is there a area in the code where I could just specify resolution and fps (or just resolution) and call on a custom profile?

Could you at least point me in the right direction? I'm thinking helpers/ffmpeg/ffmpeg-vod.ts is the right file but not sure.

**Comment by vid-bin** [comment]
Okay, will do. I've been farting around on ffmpeg-vod.ts but pretty sure its wrong and return is the wrong command to use. Maybe I should learn coding.

```
interface BaseTranscodeVODOptions {
  type: TranscodeVODOptionsType

  inputPath: string
  outputPath: string

  // Will be released after the ffmpeg started
  // To prevent a bug where the input file does not exist anymore when running ffmpeg
  inputFileMutexReleaser: MutexInterface.Releaser

  availableEncoders: AvailableEncoders
  if VideoResolution == 1080 then
	profile: changeme1
  else if VideoResolution == 720 then
    profile: changeme2
  else
    profile: string
  return

  resolution: number

  job?: Job
}
```

**Comment by vid-bin** [comment]
Hi!

For anyone wondering about how to do this if you open server/lib/transcoding/transcoding.ts you can replace all of the instances of:

CONFIG.TRANSCODING.PROFILE

with something like:

profile: '720p30',

With your custom profile made by transcoding-profile-debug. I'm still working on how to make if and else if statements since I haven't coded in years but that method works for me.

**Comment by vid-bin** [comment]
> See
> 
> https://github.com/Chocobozzz/PeerTube/blob/0e3026f3159f2b766a73393219b10cbe49111141/server/helpers/ffmpeg/ffmpeg-encoders.ts#L46

Hmm. Well, peertube doesn't like my if else if else statements. I don't know typescript but I've tried copying other instances in the peertube code and it still errors out on build.

But manually replacing profile: string, with something like profile: '720p', works so an if/elseif statement based on the video resolution should as well.

If you (or someone else) could show me the code needed on ffmpeg-encoders.ts to call a different profile for each resolution I'd be happy to chip in $50 to anyones paypal account linked with the code. If it includes resolution and 30fps/60fps profiles as well I'd up that to $75.

I certainly don't mind manually adding the code and building peertube from source.

**Comment by SimplyCorbett** [comment]
@Chocobozzz

Is this a bug with transcoding-profile-debug? I had someone else code the attached ffmpeg-encoders.ts. When I remove the 480p30/60 profiles from the transcoding profiles in the plugin it will encode at the specified bitrate in forced h264. But when I have the 480p30/60 profile it will encode in the specified encoder but the bitrate will stay the same between video resolutions.

Would you mind helping a poor soul out? There are no errors.

`{
  "vod": [
    {
      "encoderName": "libopus",
      "profileName": "1440p60",
      "outputOptions": ["-b:a 128k", "-strict -2", "-vbr on"]
    },
    {
      "encoderName": "av1_qsv",
      "profileName": "1440p60",
      "outputOptions": ["-b:v 10000k", "-minrate 10k", "-maxrate 12000k", "-g 300", "-preset 1", "-profile 1"]
    },
	    {
      "encoderName": "libopus",
      "profileName": "1440p30",
      "outputOptions": ["-b:a 128k", "-strict -2", "-vbr on"]
    },
    {
      "encoderName": "av1_qsv",
      "profileName": "1440p30",
      "outputOptions": ["-b:v 4000k", "-minrate 10k", "-maxrate 5000k", "-g 300", "-preset 1", "-profile 1"]
    },
	    {
      "encoderName": "libopus",
      "profileName": "1080p60",
      "outputOptions": ["-b:a 128k", "-strict -2", "-vbr on"]
    },
    {
      "encoderName": "av1_qsv",
      "profileName": "1080p60",
      "outputOptions": ["-b:v 5000k", "-minrate 10k", "-maxrate 7000k", "-g 300", "-preset 1", "-profile 1"]
    },
	    {
      "encoderName": "libopus",
      "profileName": "1080p30",
      "outputOptions": ["-b:a 128k", "-strict -2", "-vbr on"]
    },
    {
      "encoderName": "av1_qsv",
      "profileName": "1080p30",
      "outputOptions": ["-b:v 2500k", "-minrate 10k", "-maxrate 3500k", "-g 300", "-preset 1", "-profile 1"]
    },
	    {
      "encoderName": "libopus",
      "profileName": "720p60",
      "outputOptions": ["-b:a 128k", "-strict -2", "-vbr on"]
    },
    {
      "encoderName": "av1_qsv",
      "profileName": "720p60",
      "outputOptions": ["-b:v 3000k", "-minrate 10k", "-maxrate 4000k", "-g 300", "-preset 1", "-profile 1"]
    },
	    {
      "encoderName": "libopus",
      "profileName": "720p30",
      "outputOptions": ["-b:a 128k", "-strict -2", "-vbr on"]
    },
    {
      "encoderName": "av1_qsv",
      "profileName": "720p30",
      "outputOptions": ["-b:v 1500k", "-minrate 10k", "-maxrate 2500k", "-g 300", "-preset 1", "-profile 1"]
    },
		    {
      "encoderName": "libopus",
      "profileName": "480p30",
      "outputOptions": ["-b:a 128k", "-strict -2", "-vbr on"]
    },
    {
      "encoderName": "av1_qsv",
      "profileName": "480p30",
      "outputOptions": ["-b:v 1000k", "-minrate 10k", "-maxrate 1500k", "-g 300", "-preset 1", "-profile 1"]
    },
		    {
      "encoderName": "libopus",
      "profileName": "480p60",
      "outputOptions": ["-b:a 128k", "-strict -2", "-vbr on"]
    },
    {
      "encoderName": "av1_qsv",
      "profileName": "480p60",
      "outputOptions": ["-b:v 2000k", "-minrate 10k", "-maxrate 3000k", "-g 300", "-preset 1", "-profile 1"]
    }
  ],

  "live": []
}`

[ffmpeg-encoders.zip](https://github.com/Chocobozzz/PeerTube/files/11044882/ffmpeg-encoders.zip)

**Comment by SimplyCorbett** [comment]
Whoops line 57 and 59 needed quotes. So it does work but it's defaulting to the 480p30 profile. Is the way it's getting the video resolution or FPS wrong?

**Comment by SimplyCorbett** [comment]
I was able to get this to work. :)

**Comment by rriemann** [comment]
Hey @SimplyCorbett !

How did you get it work? Maybe you can report also on the overall status at https://framacolibri.org/t/hardware-transcoding-in-peertube-docker/17680 ? /cc @vid-bin

**Comment by vid-bin** [comment]
@rriemann the issue you linked to is about hardware transcoding, but the issue in this topic is about using different profiles per resolution/fps, which issue do you need help with?

**Comment by vid-bin** [comment]
@rriemann you can see how this issue was solved here - https://github.com/Chocobozzz/PeerTube/issues/4285#issuecomment-1481940220
