### ISSUE TITLE
Missing docker environment variables for object storage ACLs

### ISSUE THREAD

**Issue by rknightion** [Chocobozzz/PeerTube#5674]
### Describe the current behavior

On 5.0.1 (but also I believe 5.1-RC1) I'm running peertube in Docker and trying to set the public & private ACLs.
The environment variable at https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/config/custom-environment-variables.yaml has the variable from when https://github.com/Chocobozzz/PeerTube/pull/4861 was introduced (to set a global ACL). But when improvements were made to split out public/private in https://github.com/Chocobozzz/PeerTube/pull/5370 I don't think the custom environment variables were updated. 
This effectively makes the PEERTUBE_OBJECT_STORAGE_UPLOAD_ACL variable no longer function.
I did try setting PEERTUBE_OBJECT_STORAGE_UPLOAD_ACL_PUBLIC & PEERTUBE_OBJECT_STORAGE_UPLOAD_ACL_PRIVATE but I suspect as they're not defined in the custom environment variables map they have no effect. 

Note: I am also happy to configure using the production yaml file but inside my data/config directory there's an existing yaml file containing json that I assume is generated by the environment variables. If there's a way to use the settings yaml instead of env vars to work around this that would be a suitable alternative.

### Steps to reproduce

1. Deploy with Docker
2. Update PEERTUBE_OBJECT_STORAGE_UPLOAD_ACL
3. Try to configure public/private ACL names via the .env file
4. Note peertube doesn't try to use those

### Describe the expected behavior

Setting PEERTUBE_OBJECT_STORAGE_UPLOAD_ACL_PUBLIC & PEERTUBE_OBJECT_STORAGE_UPLOAD_ACL_PRIVATE should work

**Comment by Chocobozzz** [comment]
Added in https://github.com/Chocobozzz/PeerTube/commit/a3e5f7e732cca41267314d64307bdcfebd12e7de :+1:
