### ISSUE TITLE
+property+ is not defined

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#5676]
-snip-

There is an undocumented change in the production.yaml file in the latest git and 5.1.0 that causes peertube to error out. Copying the production.yaml file from the new version fixes it.

**Comment by vid-bin** [comment]
Closing.

**Comment by Chocobozzz** [comment]
Hello,

Can you describe what was the cause of this issue?

**Comment by vid-bin** [comment]
I’m not sure? I deleted the config folder and replaced the production.yaml with the one in the new release.On Mar 6, 2023, at 6:41 AM, Chocobozzz ***@***.***> wrote:﻿
Hello,
Can you describe what was the cause of this issue?
