### ISSUE TITLE
Peertube transcoding stuck at 100%

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#5683]
### Describe the current behavior

The transcoding job is stuck at 100%. There are no errors. In order to restart peertube the ffmpeg job has to be manually killed in ssh. This seems to be a problem with this specific video but I'm not sure how to figure out what the error is.

It would be nice if peertube could give more information on why ffmpeg jobs get stuck and what the problem is.

![transcoding-stuck](https://user-images.githubusercontent.com/112714131/223526025-cdc50770-e70a-4313-9e53-92ce344aabf6.png)

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL: vidbin.org
  * Version: 5.1.0-rc.1...0e3026f31
  * NodeJS version: 18
  * Ffmpeg version: git

**Comment by vid-bin** [comment]
Yeah so this is an issue with a specific youtube video at a specific resolution. I dont think its a peertube specific issue. It would still be nice if there was more information on the error and if peertube stopped trying to transcode the file if ffmpeg freezes.

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue. We can't know if ffmpeg is stuck but after some time the job will automatically fail because of time limit exceeded

**Comment by vid-bin** [comment]
That's why I made this ticket! It doesn't automatically fail. Unless it requires 3+ hours?
