### ISSUE TITLE
Contributing : Helm chart for Peertube 5.0.1

### ISSUE THREAD

**Issue by Elam-Monnot** [Chocobozzz/PeerTube#5685]
### Describe the problem

I have created an helm chart to deploy Peertube in version 5.0.1 .
I am currently doing an internship at "Rectorat de Dijon" in the EOLE office.
During this internship I have been asked to create an helm chart to deploy Peertube in an educational environment. Right now I have a working helm chart that deploys Peertube and offers configuration and an install guide in a README file.
I would be very interested in contributing to the Peertube project.
https://github.com/Elam-Monnot/Peertube-helm
Have a good day.

**Comment by Chocobozzz** [comment]
Hi and thanks! You can add your contribution on https://docs.joinpeertube.org/install/unofficial#kubernetes
