### ISSUE TITLE
Import script does not import captions

### ISSUE THREAD

**Issue by dullbananas** [Chocobozzz/PeerTube#5686]
### Describe the current behavior

When importing a YouTube video with captions, the resulting PeerTube video has no captions. The captions list in the video editor says "No captions for now."

### Steps to reproduce

1. Run dist/server/tools/peertube-import-videos.js with the URL of a YouTube channel with a video that has manually added captions
2. On PeerTube, go to "my library", then "videos"
3. Click "update" under a video that should have captions
4. Go to the "captions" tab

### Describe the expected behavior

Captions list should not be empty

### Additional information

* PeerTube instance:
  * URL: https://www.orion-hub.fr/
  * Version: 5.0.1

* Import script
  * NodeJS version: 19.6.0
  * Ffmpeg version: 4.2.7
  * Peertube repository commit: 692ae8c31caa5a404142c9f46e03fdc8dc5b233f

* Browser name, version and platforms on which you could reproduce the bug: Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Mobile/15E148 Safari/604.1
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
I'm sorry but we had to remove this unmaintained script, so I'm closing this issue. Please use the built-in [channel sync](https://docs.joinpeertube.org/use/channel-sync] instead! (has to be enabled by your admin)
