### ISSUE TITLE
videos are not transferring to remote storage

### ISSUE THREAD

**Issue by you2314** [Chocobozzz/PeerTube#5687]
### Describe the current behavior

videos are not transferring to minio s3 storage

here is my config:

`object_storage:
  enabled: true
  endpoint: 'http://s3.xxxx' 
  region: 'xxxx'
  upload_acl:  
    public: 'null'
    private: 'null'
  proxy:
    proxify_private_files: true

  credentials:
    access_key_id: 'xxxx'
    secret_access_key: 'xxxx'
  max_upload_part: 100MB
  streaming_playlists:
    bucket_name: 'hls-videos'
    prefix: ''
    base_url: '' 
`

### Steps to reproduce

1.Add above configuration
2.Run create-move-video-storage-job

### Describe the expected behavior

The video should transfer to s3 storage

### Additional information

* PeerTube instance:
  * URL:
  * Version:5.0.1
  * NodeJS version:19.7.0
  * Ffmpeg version:4.3.5

* Browser name, version and platforms on which you could reproduce the bug: Firefox

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

`info[2023-03-09, 9:15:44 p.m.] Initialized S3 client http://s3.xxxx with region xxx.

{
  "tags": [
    "object-storage"
  ]
}
error[2023-03-09, 10:03:34 p.m.] Cannot execute job 95 in queue move-to-object-storage.

{
  "payload": {
    "videoUUID": "72a28683-ca66-4e5a-bbdc-86963cf6edbe",
    "isNewVideo": false,
    "previousVideoState": 8
  },
  "err": {
    "stack": "Error: read ETIMEDOUT\n    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)",
    "message": "read ETIMEDOUT",
    "errno": -110,
    "code": "ETIMEDOUT",
    "syscall": "read",
    "name": "TimeoutError",
    "$metadata": {
      "attempts": 3,
      "totalRetryDelay": 202
    }
  }
}`

**Comment by Chocobozzz** [comment]
Hello,

I don't think it's peertube related: the s3 endpoint doesn't seem accessible from the peertube server
