### ISSUE TITLE
Live streaming connected to R2 issues

### ISSUE THREAD

**Issue by upcastvideo** [Chocobozzz/PeerTube#5689]
### Describe the current behavior

I have a test instance connected to R2. Live streaming is only working when I set video privacy to "private" but the video can be only played in desktop browser. If you login to the instance using your phone, the player has an issue and doesn´t reproduce the video.

If you set video privacy to "public" the live streaming from your client is not going to be sent to peertube instance.

My instance is built on Digital Ocean under Ubuntu 22.10 X64.

This is my cors policy in R2:

`[
  {
    "AllowedOrigins": [
      "*"
    ],
    "AllowedMethods": [
      "GET",
      "HEAD"
    ],
    "AllowedHeaders": [
      "*"
    ],
    "ExposeHeaders": [],
    "MaxAgeSeconds": 3600
  }
]`

And this is my production.yaml settings:

`object_storage:
  enabled: true

  # Without protocol, will default to HTTPS
  endpoint: 'https://XXX.r2.cloudflarestorage.com' # 's3.amazonaws.com' or 's3.fr-par.scw.cloud' fo>

  region: 'auto'

  upload_acl:
    # Set this ACL on each uploaded object of public/unlisted videos
    public: 'public-read'
    # Set this ACL on each uploaded object of private/internal videos
    # PeerTube can proxify requests to private objects so your users can access them
    private: 'private'

  proxy:
    # If private files (private/internal video files) have a private ACL, users can't access directly the ressource
    # PeerTube can proxify requests between your object storage service and your users
    # If you disable PeerTube proxy, ensure you use your own proxy that is able to access the private files
    # Or you can also set a public ACL for private files in object storage if you don't want to use a proxy
    proxify_private_files: true

  credentials:
    # You can also use AWS_ACCESS_KEY_ID env variable
    access_key_id: 'XXX'
    # You can also use AWS_SECRET_ACCESS_KEY env variable
    secret_access_key: 'XXX'

  # Maximum amount to upload in one request to object storage
  max_upload_part: 90MB

  streaming_playlists:
    bucket_name: 'live'

    # Allows setting all buckets to the same value but with a different prefix
    prefix: 'streaming-playlists/' # Example: 'streaming-playlists:'

    # Base url for object URL generation, scheme and host will be replaced by this URL
    # Useful when you want to use a CDN/external proxy
    base_url: 'https://live-cdn.upcast.work' # Example: 'https://mirror.example.com'

  # Same settings but for webtorrent videos
  videos:
    bucket_name: 'live'
    prefix: 'videos/'
    base_url: 'https://live-cdn.upcast.work'`

### Steps to reproduce

1. Publish live streaming with "private" mode.
2. Start live streaming through stream yard.
3. Live streaming is only playable in desktop browsers. In phones the player has a problem and it doesnt start the live.
4. -------------------------
5. Publish live streaming with "public" mode.
6. Start live streaming through stream yard.
7. Live streaming is not being sent to Peertube

### Describe the expected behavior

Be able to live stream with both "private" and "public" options and to reproduce the live streaming in mobile phones.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Please paste server logs when you try to live stream

**Comment by upcastvideo** [comment]
Mar 12 20:47:16 live peertube[1329]: [live.upcast.work:443] 2023-03-12 20:47:16.458 info: Cleaning video viewers.
Mar 12 20:47:49 live peertube[1329]: [live.upcast.work:443] 2023-03-12 20:47:49.536 warn: Warning in tracker. {
Mar 12 20:47:49 live peertube[1329]:   "err": {
Mar 12 20:47:49 live peertube[1329]:     "stack": "Error: Unknown infoHash 8dcc751898e2355d52a57f3f340368872d30e1e7 requested by ip 84.125.210.67\n    at Server.<anonymous> (/var/www/peertube/versions/peertube-v5.0.1/dist/server/controllers/tracker.js:52:20)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v5.0.1/node_modules/tslib/tslib.js:115:62)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
Mar 12 20:47:49 live peertube[1329]:     "message": "Unknown infoHash 8dcc751898e2355d52a57f3f340368872d30e1e7 requested by ip 84.125.210.67"
Mar 12 20:47:49 live peertube[1329]:   }
Mar 12 20:47:49 live peertube[1329]: }

**Comment by upcastvideo** [comment]
> Hello,
> 
> Please paste server logs when you try to live stream

Mar 12 20:47:16 live peertube[1329]: [live.upcast.work:443] 2023-03-12 20:47:16.458 info: Cleaning video viewers.
Mar 12 20:47:49 live peertube[1329]: [live.upcast.work:443] 2023-03-12 20:47:49.536 warn: Warning in tracker. {
Mar 12 20:47:49 live peertube[1329]: "err": {
Mar 12 20:47:49 live peertube[1329]: "stack": "Error: Unknown infoHash 8dcc751898e2355d52a57f3f340368872d30e1e7 requested by ip 84.125.210.67\n at Server. (/var/www/peertube/versions/peertube-v5.0.1/dist/server/controllers/tracker.js:52:20)\n at Generator.next ()\n at fulfilled (/var/www/peertube/versions/peertube-v5.0.1/node_modules/tslib/tslib.js:115:62)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
Mar 12 20:47:49 live peertube[1329]: "message": "Unknown infoHash 8dcc751898e2355d52a57f3f340368872d30e1e7 requested by ip 84.125.210.67"
Mar 12 20:47:49 live peertube[1329]: }
Mar 12 20:47:49 live peertube[1329]: }

**Comment by Chocobozzz** [comment]
I don't see live stream logs in these logs.

**Comment by upcastvideo** [comment]
This is the logs when trying a private video streaming.

  "username": "root",
  "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Mobile/15E148 Safari/604.1",
  "stackTrace": "The intl string context variable \"visitas\" was not provided to the string \"{visitas, plural, =0 {Sin visualizaciones} =1 {1 visualización} other {{views} visualizaciones}}\"\nF@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:208876\nF@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:209486\nEr@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:210137\n@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:212317\n@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:215607\ntemplate@https://live.upcast.work/client/es-ES/8337.c6ce2a778782cb91.js:1:59316\nK_@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:795425\nTu@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:794199\nn1@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:801077\nkv@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:795071\nTu@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:795080\ne1@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:794630\nTu@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:794653\ne1@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:794630\nTu@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:794653\nn1@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:801077\nkv@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:795071\nTu@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:795080\ne1@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:794630\nTu@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:794653\nn1@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:801077\nkv@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:795071\nTu@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:795080\ne1@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:794630\nTu@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:794653\nn1@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:801077\nkv@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:795071\nTu@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:795080\nMu@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:801739\ndetectChanges@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:804064\ntick@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:864340\n@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:862895\nonInvoke@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:854930\nrun@https://live.upcast.work/client/es-ES/polyfills.49fdee6c496b7b63.js:1:63750\nnext@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:862880\nnext@[native code]\nnext@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:615077\n_next@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:614761\nnext@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:614455\n@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:612415\np@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:640981\nnext@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:612250\nemit@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:841064\nrp@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:855929\nc0@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:856347\nonInvokeTask@https://live.upcast.work/client/es-ES/main.fca463a4dd8db6d1.js:3:854872\nrunTask@https://live.upcast.work/client/es-ES/polyfills.49fdee6c496b7b63.js:1:64394\ninvokeTask@https://live.upcast.work/client/es-ES/polyfills.49fdee6c496b7b63.js:1:70142\nT@https://live.upcast.work/client/es-ES/polyfills.49fdee6c496b7b63.js:1:82897\nN@https://live.upcast.work/client/es-ES/polyfills.49fdee6c496b7b63.js:1:83316",
  "url": "https://live.upcast.work/w/n2ggaKKRrs4H8E3F7Z5Ezs"
}
error[18/3/2023, 1:20:40] Client log: Error: No se pudo reproducir el video, se intentará avanzar rápidamente.
{
  "tags": [
    "client"
  ],
  "username": "root",
  "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Mobile/15E148 Safari/604.1",
  "url": "https://live.upcast.work/w/n2ggaKKRrs4H8E3F7Z5Ezs"
}

**Comment by Chocobozzz** [comment]
You don't have `Running live muxing/transcoding` or `probing took` strings in your server logs?
