### ISSUE TITLE
Problem running isolated peertube server (Cannot retrieve OAuth Client credentials)

### ISSUE THREAD

**Issue by amnona** [Chocobozzz/PeerTube#5694]
### Describe the problem

Thanks for this amazing server!
I am trying to install peertube locally (on windows subsystem linux with ubuntu).
I followed the installation instructions on https://docs.joinpeertube.org/install/any-os (thanks - very comprehensive and easy to follow instructions)

However, when I connect to the server locally (127.0.0.1:9000), I get the following error message in the browser (a pop up warning in the main page):
"Cannot retrieve OAuth Client credentials: Getting client tokens for host 127.0.0.1:9000 is forbidden. Ensure you have correctly configured PeerTube (config/ directory), in particular the "webserver" section."
And additionally, I cannot log in/create an account (I get an "Invalid client: client is invalid" message when I provide a user/password in the login or register pages)

I ran the server with debug messages, and this is what I get when loading the main page:
"Mar 15 12:40:58 DemiGod peertube[7338]: [conglomerate.com:443] 2023-03-15 12:40:58.773 info: 127.0.0.1 - - [15/Mar/2023:10:40:58 +0000] "GET / HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
Mar 15 12:40:58 DemiGod peertube[7338]: [conglomerate.com:443] 2023-03-15 12:40:58.847 info: Getting client tokens for host 127.0.0.1:9000 is forbidden (expected conglomerate.com).
Mar 15 12:40:58 DemiGod peertube[7338]: [conglomerate.com:443] 2023-03-15 12:40:58.847 info: 127.0.0.1 - - [15/Mar/2023:10:40:58 +0000] "GET /api/v1/oauth-clients/local HTTP/1.1" 403 282 "http://127.0.0.1:9000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
Mar 15 12:40:58 DemiGod peertube[7338]: [conglomerate.com:443] 2023-03-15 12:40:58.852 info: 127.0.0.1 - - [15/Mar/2023:10:40:58 +0000] "GET /api/v1/videos/languages HTTP/1.1" 304 - "http://127.0.0.1:9000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
Mar 15 12:40:58 DemiGod peertube[7338]: [conglomerate.com:443] 2023-03-15 12:40:58.854 info: 127.0.0.1 - - [15/Mar/2023:10:40:58 +0000] "GET /api/v1/config/ HTTP/1.1" 304 - "http://127.0.0.1:9000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
Mar 15 12:40:58 DemiGod peertube[7338]: [conglomerate.com:443] 2023-03-15 12:40:58.897 error: Client log: Backend returned code 403, errorMessage is: Getting client tokens for host 127.0.0.1:9000 is forbidden {
Mar 15 12:40:58 DemiGod peertube[7338]:   "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
Mar 15 12:40:58 DemiGod peertube[7338]:   "url": "http://127.0.0.1:9000/"
Mar 15 12:40:58 DemiGod peertube[7338]: }
Mar 15 12:40:58 DemiGod peertube[7338]: [conglomerate.com:443] 2023-03-15 12:40:58.898 info: 127.0.0.1 - - [15/Mar/2023:10:40:58 +0000] "POST /api/v1/server/logs/client HTTP/1.1" 204 - "http://127.0.0.1:9000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
Mar 15 12:40:58 DemiGod peertube[7338]: [conglomerate.com:443] 2023-03-15 12:40:58.900 info: 127.0.0.1 - - [15/Mar/2023:10:40:58 +0000] "POST /api/v1/server/logs/client HTTP/1.1" 429 42 "http://127.0.0.1:9000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
Mar 15 12:40:58 DemiGod peertube[7338]: [conglomerate.com:443] 2023-03-15 12:40:58.951 info: 127.0.0.1 - - [15/Mar/2023:10:40:58 +0000] "GET /api/v1/videos/categories HTTP/1.1" 304 - "http://127.0.0.1:9000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
Mar 15 12:40:58 DemiGod peertube[7338]: [conglomerate.com:443] 2023-03-15 12:40:58.976 info: 127.0.0.1 - - [15/Mar/2023:10:40:58 +0000] "GET /api/v1/videos?start=0&count=25&sort=-trending&skipCount=true&nsfw=false HTTP/1.1" 304 - "http://127.0.0.1:9000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
Mar 15 12:40:58 DemiGod peertube[7338]: [conglomerate.com:443] 2023-03-15 12:40:58.992 info: 127.0.0.1 - - [15/Mar/2023:10:40:58 +0000] "GET /manifest.webmanifest?c46bd6c1636c564079b43c56324606ac410d6e72 HTTP/1.1" 304 - "http://127.0.0.1:9000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
"

This is without running an nginx server. However, I got the same problem also when running the nginx server (following the instructions at https://docs.joinpeertube.org/install/any-os)
I made sure the peertube.service config file WorkingDirectory=/var/www/peertube/peertube-latest

Any suggestions?

### Additional information

* PeerTube instance URL: local (but also conglomerate.com and I have my LAN DNS pointing conglomerate.com to the server computer)
* PeerTube version:5.0.1
* NodeJS version:16.19.1
* Ffmpeg version:4.4.2
* Redis version:
* PostgreSQL version:14.7

**Comment by Chocobozzz** [comment]
Hello,

Please paste the `webserver` section from your `production.yaml`

**Comment by Chocobozzz** [comment]
I think you should set `port: 80` and access your peertube instance from `http://conglomerate.com`

**Comment by amnona** [comment]
Thanks!

I tried changing the port to 80 and accessing from http://conglomerate.com . However, this does not work (i get ERR_CONNECTION_REFUSED).
I am able to reach a simple flask webserver running on the same wsl machine (port 5000) by accessing http://conglomerate.com:5000 .
I also changed the "listen" part in the config file from 127.0.0.1 to 0.0.0.0, so now I am also able to reach http://conglomerate.com:9000 (but still get the "Cannot retrieve OAuth Client credentials: Getting client tokens for host conglomerate.com:9000 is forbidden. Ensure you have correctly configured PeerTube (config/ directory), in particular the "webserver" section." error).

My /var/www/peertube/config/production.yaml file contains now:

```
listen:
  hostname: '0.0.0.0'
  port: 9000

webserver:
  https: false
  hostname: 'conglomerate.com'
  port: 80
```

Any suggestions?

**Comment by Chocobozzz** [comment]
So use `port: 9000` if you want to use http://conglomerate.com:9000/ url

**Comment by amnona** [comment]
I tried, however I still get the same popup error message when loading the page (from http://conglomerate.com:9000):
`Cannot retrieve OAuth Client credentials: Getting client tokens for host conglomerate.com:9000 is forbidden. Ensure you have correctly configured PeerTube (config/ directory), in particular the "webserver" section."`
And when I try to log in / register, I get the error message:
`Invalid client: client is invalid`

What am I doing wrong?

**Comment by amnona** [comment]
Update: I also tried running peertube using the docker installation.
I installed without nginx, for local testing, and still get the same error (popup on the main local peertube page) when accessing either 127.0.0.1:9000 or conglomerate.com:9000 :
"Cannot retrieve OAuth Client credentials: Getting client tokens for host conglomerate.com:9000 is forbidden. Ensure you have correctly configured PeerTube (config/ directory), in particular the "webserver" section."
And additionally I can't sign in as root or register a new user ("Invalid client: client is invalid").

NOTE: I do not own conglomerate.com. Instead I am using a local DNS that translates it to the LAN address of the server.

Here is the docker-compose.yaml file I used for the docker:
```
version: "3.3"

services:

  # You can comment this webserver section if you want to use another webserver/proxy or test PeerTube in local
#  webserver:
#    image: chocobozzz/peertube-webserver:latest
#    # If you don't want to use the official image and build one from sources:
#    # build:
#    #   context: .
#    #   dockerfile: Dockerfile.nginx
#    env_file:
#      - .env
#    ports:
#     - "80:80"
#     - "443:443"
#    volumes:
#      - type: bind
#        # Switch sources if you downloaded the whole repository
#        #source: ../../nginx/peertube
#        source: ./docker-volume/nginx/peertube
#        target: /etc/nginx/conf.d/peertube.template
#      - assets:/var/www/peertube/peertube-latest/client/dist:ro
#      - ./docker-volume/data:/var/www/peertube/storage
#      - certbot-www:/var/www/certbot
#      - ./docker-volume/certbot/conf:/etc/letsencrypt
#    depends_on:
#      - peertube
#    restart: "always"

  # You can comment this certbot section if you want to use another webserver/proxy or test PeerTube in local
#  certbot:
#    container_name: certbot
#    image: certbot/certbot
#    volumes:
#      - ./docker-volume/certbot/conf:/etc/letsencrypt
#      - certbot-www:/var/www/certbot
#    restart: unless-stopped
#    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;"
#    depends_on:
#      - webserver

  peertube:
    # If you don't want to use the official image and build one from sources:
    # build:
    #   context: .
    #   dockerfile: ./support/docker/production/Dockerfile.bullseye
    image: chocobozzz/peertube:production-bullseye
    # Use a static IP for this container because nginx does not handle proxy host change without reload
    # This container could be restarted on crash or until the postgresql database is ready for connection
    networks:
      default:
        ipv4_address: 172.18.0.42
    env_file:
      - .env

    ports:
#     - "1935:1935" # Comment if you don't want to use the live feature
      - "9000:9000" # Uncomment if you use another webserver/proxy or test PeerTube in local, otherwise not suitable for production
    volumes:
      - assets:/app/client/dist
      - ./docker-volume/data:/data
      - ./docker-volume/config:/config
    depends_on:
      - postgres
      - redis
      # - postfix
    restart: "always"

  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    # by amnon
    ports:
      - "5432:5432" # by amnon
    volumes:
      - ./docker-volume/db:/var/lib/postgresql/data
    restart: "always"

  redis:
    image: redis:6-alpine
    volumes:
      - ./docker-volume/redis:/data
    restart: "always"

  postfix:
    image: mwader/postfix-relay
    env_file:
      - .env
    volumes:
      - ./docker-volume/opendkim/keys:/etc/opendkim/keys
    restart: "always"

networks:
  default:
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/16

volumes:
  assets:
  # certbot-www:

```

And the .env file:
```
# Database / Postgres service configuration
POSTGRES_USER="postgres"
POSTGRES_PASSWORD="XXXX"

# # Postgres database name "peertube"
POSTGRES_DB="peertube"
# # Editable only with a suffix :
# #POSTGRES_DB=peertube_prod
# #PEERTUBE_DB_SUFFIX=_prod
PEERTUBE_DB_USERNAME="peertube"
PEERTUBE_DB_PASSWORD="XXXXX"
PEERTUBE_DB_SSL=false
# # Default to Postgres service name "postgres" in docker-compose.yml
PEERTUBE_DB_HOSTNAME="postgres"

# PeerTube server configuration
# If you test PeerTube in local: use "peertube.localhost" and add this domain to your host file resolving on 127.0.0.1
PEERTUBE_WEBSERVER_HOSTNAME="peertube.localhost"
# If you just want to test PeerTube on local
PEERTUBE_WEBSERVER_PORT=9000
PEERTUBE_WEBSERVER_HTTPS=false
# If you need more than one IP as trust_proxy
# pass them as a comma separated array:
PEERTUBE_TRUST_PROXY=["127.0.0.1", "loopback", "172.18.0.0/16"]

# Generate one using `openssl rand -hex 32`
PEERTUBE_SECRET="XXXXX"

# E-mail configuration
# If you use a Custom SMTP server
#PEERTUBE_SMTP_USERNAME=
#PEERTUBE_SMTP_PASSWORD=
# Default to Postfix service name "postfix" in docker-compose.yml
# May be the hostname of your Custom SMTP server
PEERTUBE_SMTP_HOSTNAME="postfix"
PEERTUBE_SMTP_PORT=25
PEERTUBE_SMTP_FROM="noreply@conglomerate.com"
PEERTUBE_SMTP_TLS=false
PEERTUBE_SMTP_DISABLE_STARTTLS=false
PEERTUBE_ADMIN_EMAIL="admin@conglomerate.com"

# Postfix service configuration
POSTFIX_myhostname="postfixer.com"
# If you need to generate a list of sub/DOMAIN keys
# pass them as a whitespace separated string <DOMAIN>=<selector>
OPENDKIM_DOMAINS=conglomerate.com="peertube"
# see https://github.com/wader/postfix-relay/pull/18
OPENDKIM_RequireSafeKeys=no

# /!\ Prefer to use the PeerTube admin interface to set the following configurations /!\
PEERTUBE_SIGNUP_ENABLED=true
#PEERTUBE_TRANSCODING_ENABLED=true
#PEERTUBE_CONTACT_FORM_ENABLED=true

```

Any suggestions? I'd really like to be able to test the peertube server locally before registering a domain etc.

**Comment by amnona** [comment]
ok, managed to make it work locally using the docker.
The problem was in the .env config file. It was:
PEERTUBE_WEBSERVER_HOSTNAME="peertube.localhost"
changed it to:
PEERTUBE_WEBSERVER_HOSTNAME="conglomerate.com"

and now it works on conglomerate.com:9000

Thanks!
