### ISSUE TITLE
Change the source video for transcoding lower resolution videos

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#5695]
### Describe the problem to be solved

Current issue:

4k video import @ 25Mbps -> 1440p 8Mbps

That 1440p fragmented 8Mbps video is then used as the source for 1080p which reduces quality. Sometimes the 720p import also uses the 1440p. It depends on which resolution goes first in the queue.

### Describe the solution you would like

4k video import @ 25Mbps -> 1440p
4k video import @ 25Mbps -> 1080p
4k video import @ 25Mbps -> 720p

And so on. This would prevent quality loss from re-transcoding a second (or third time depending on video source).

Is there a technical limitation on why the source video can't be used for lower resolution transcodes?

Edit: This is with the 1440p, 1080p and 720p transcoding options selected.

**Comment by Chocobozzz** [comment]
Hello,

See the source discussion on https://github.com/Chocobozzz/PeerTube/issues/656

Can you provide examples of videos transcoded using 4k source vs lower one?

**Comment by vid-bin** [comment]
> Can you provide examples of videos transcoded using 4k source vs lower one?

Sure. 4k @ 27Mbps source on both transcodes with a 2Mbps VBR (not CRF) using transcoding-profile-debug.

This is the 4k -> 1080p transcode:

![1080p (1080)](https://user-images.githubusercontent.com/112714131/226378936-3c48b4d2-e74d-4601-8732-e4ed41a13b9b.png)

This is the 4k -> 1440p -> 1080p transcode:

![1080p (1440p+1080)](https://user-images.githubusercontent.com/112714131/226379072-57327555-1bbf-427a-a3cb-23b7067a28a0.png)

**Comment by vid-bin** [comment]
I see that @rigelk also acknowledged there would be quality loss in that discussion. The problem is the quality loss is substantial when comparing low bitrate videos as you can see from the above screenshots when viewing fullscreen.

**Comment by vid-bin** [comment]
Figured I'd give a quick update. As of version 5.2.1, the current occurs:

With one transcoding job it will go in the following video order in terms of quality (worse quality loss): 

4k -> 1440p -> 1080p -> 720p

With 5+ transcoding jobs it will do the following (good):

4k -> 1440p
4k -> 1080p
4k -> 720p

So this issue is "solved" when the server is powerful enough to A) launch 3+ transcoding jobs and B) launches them immediately. If they get delayed in queue it will default to the prior behavior.

Example:

4k -> 1440p and 1080p delayed because another job has priority. When the job resumes 1440p -> 1080p so 4k is not the source.

**Comment by Chocobozzz** [comment]
Have you enabled `Always transcode original resolution` config in peertube web config?

**Comment by Chocobozzz** [comment]
Ping @vid-bin regarding https://github.com/Chocobozzz/PeerTube/issues/5695#issuecomment-1744389943
