### ISSUE TITLE
Bug with italian translation on 5.1.0-rc.1

### ISSUE THREAD

**Issue by Sampozzo** [Chocobozzz/PeerTube#5696]
### Describe the current behavior

On 5.1.0-rc.1 there is a bug in the italian translation: you can't open the configuration -> basic tab (error in console as the screenshot).
Switching to english language it works.

<img width="288" alt="image" src="https://user-images.githubusercontent.com/81194017/225761648-8cfa6637-f31a-4058-ba96-c158e9578516.png">

### Steps to reproduce

1.
2.
3.

**Comment by Chocobozzz** [comment]
Thanks, I fixed the strings on weblate. `plural` and `other` must not be translated (they are keywords)
