### ISSUE TITLE
Various features: Select all video button -> actions like channel transfer, delete etc...., table legends clickable or filters to change my library videos and imports list order

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5697]
### Describe the problem to be solved

1) For now to delete thousands videos are very painful as it can be done one by one!
2) No filter in my library->videos and imports to see only one status like pending videos
3) No way for Bulk transfer of synchronization channel list from one to other local channel

### Describe the solution you would like

group all the missing feature in a kind of "select all" (on screen and/or on DB) checkbox allowing a selectbox actions
like "delete, transfer to other channel, cancel etc...)

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/1980
