### ISSUE TITLE
Extremely buffering with long length videos using Cloudflare R2

### ISSUE THREAD

**Issue by upcastvideo** [Chocobozzz/PeerTube#5698]
### Describe the current behavior

My instance is connected to R2. Playing short videos like 1 hour works well, however when I upload a video usually larger than 2 hours, once you move the video forward and backward in the player there is a big buffering that makes the playback impossible.

FYI the domain is not proxied to Cloudflare since with the free plan you can´t upload videos larger than 100MB, I´m using only R2 object storage from Cloudflare.

I copied 2 urls, the first one is a video uploaded without R2, you can see that is loading fast, the second one is uploaded to R2, at the beginning of the video starts fast, but once you move the timeline there is long buffering.

https://live.upcast.work/w/m4KARWkQLsAsbqea3d9Vwr

https://live.upcast.work/w/cTk6oZQQQTkiR9fYNLXgVA

**This is my S3 config in production.yaml**
object_storage:
  enabled: true

  # Without protocol, will default to HTTPS
  endpoint: 'https://XXX.r2.cloudflarestorage.com' # 's3.amazonaws.com' or 's3.fr-par.scw.cloud' for >

  region: 'us-east-1'

  upload_acl:
    # Set this ACL on each uploaded object of public/unlisted videos
    public: 'public-read'
    # Set this ACL on each uploaded object of private/internal videos
    # PeerTube can proxify requests to private objects so your users can access them
    private: 'private'

  proxy:
    # If private files (private/internal video files) have a private ACL, users can't access directly the ressource
    # PeerTube can proxify requests between your object storage service and your users
    # If you disable PeerTube proxy, ensure you use your own proxy that is able to access the private files
    # Or you can also set a public ACL for private files in object storage if you don't want to use a proxy
    proxify_private_files: true

  credentials:
    # You can also use AWS_ACCESS_KEY_ID env variable
    access_key_id: 'XXX'
    # You can also use AWS_SECRET_ACCESS_KEY env variable
    secret_access_key: 'XXX'

  # Maximum amount to upload in one request to object storage
  max_upload_part: 90MB

  streaming_playlists:
    bucket_name: 'upcast-live'

    # Allows setting all buckets to the same value but with a different prefix
    prefix: 'streaming-playlists/' # Example: 'streaming-playlists:'

    # Base url for object URL generation, scheme and host will be replaced by this URL
    # Useful when you want to use a CDN/external proxy
    base_url:  'https://upcast-live-cdn.upcast.work' # Example: 'https://mirror.example.com'

  # Same settings but for webtorrent videos
  videos:
    bucket_name: 'upcast-live'
    prefix: 'videos/'
    base_url: 'https://upcast-live-cdn.upcast.work'

### Steps to reproduce

1. Connect production.yaml to R2
2. Upload video
3. Video buffering when moving the time line

### Describe the expected behavior

To play the video without buffering when moving the timeline.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by upcastvideo** [comment]
```c++
streaming_playlists:
bucket_name: 'upcast-live'
```

**Comment by upcastvideo** [comment]
/object_storage:
  enabled: true

  # Without protocol, will default to HTTPS
  endpoint: 'https://XXX.r2.cloudflarestorage.com' # 's3.amazonaws.com' or 's3.fr-par.scw.cloud' for >

  region: 'us-east-1'

  upload_acl:
    # Set this ACL on each uploaded object of public/unlisted videos
    public: 'public-read'
    # Set this ACL on each uploaded object of private/internal videos
    # PeerTube can proxify requests to private objects so your users can access them
    private: 'private'

  proxy:
    # If private files (private/internal video files) have a private ACL, users can't access directly the ressource
    # PeerTube can proxify requests between your object storage service and your users
    # If you disable PeerTube proxy, ensure you use your own proxy that is able to access the private files
    # Or you can also set a public ACL for private files in object storage if you don't want to use a proxy
    proxify_private_files: true

  credentials:
    # You can also use AWS_ACCESS_KEY_ID env variable
    access_key_id: 'XXX'
    # You can also use AWS_SECRET_ACCESS_KEY env variable
    secret_access_key: 'XXX'

  # Maximum amount to upload in one request to object storage
  max_upload_part: 90MB

  streaming_playlists:
    bucket_name: 'upcast-live'

    # Allows setting all buckets to the same value but with a different prefix
    prefix: 'streaming-playlists/' # Example: 'streaming-playlists:'

    # Base url for object URL generation, scheme and host will be replaced by this URL
    # Useful when you want to use a CDN/external proxy
    base_url:  'https://upcast-live-cdn.upcast.work' # Example: 'https://mirror.example.com'

  # Same settings but for webtorrent videos
  videos:
    bucket_name: 'upcast-live'
    prefix: 'videos/'
    base_url: 'https://upcast-live-cdn.upcast.work'

**Comment by vid-bin** [comment]
> https://live.upcast.work/w/cTk6oZQQQTkiR9fYNLXgVA

This doesn't play for me but my internet usage is at 60Mbps in the background which is my home internets max speed. If I had to guess your S3 provider doesn't support seeking which causes the entire file to have to be downloaded first before playing.

**Comment by upcastvideo** [comment]
Well that one of 3 hours duration doesn´t work, but this one of 1 hour and 40 minutes does work perfectly connected to R2 https://live.upcast.work/w/9oABFycZ66zFK7Czc2hVFA.
I tried with a lot of videos and different lengths. It happens only with videos longer than around 2 hours.

**Comment by Chocobozzz** [comment]
Hello,

Please contact cloudflare support as it seems they don't respect the `Range` header for this particular video:


```
curl 'https://upcast-live-cdn.upcast.work/streaming-playlists/hls/603f395a-6920-439e-920d-418502411058/05838ed3-838f-4624-bd45-1da7e99f2ca8-720-fragmented.mp4' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0' -H 'Accept: */*' -H 'Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.5,en;q=0.3' -H 'Accept-Encoding: gzip, deflate, br, identity' -H 'Range: bytes=1372-208351' -H 'Origin: https://live.upcast.work' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: https://live.upcast.work/' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-site' -H 'Sec-GPC: 1' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'TE: trailers' --output - > /dev/null
```

**Comment by upcastvideo** [comment]
Is not for that particular video. Any video larger than 2 hours will have the issue if you have peertube connected to R2

**Comment by aeharding** [comment]
This is for any video file that's larger than 512MB. Workaround: https://community.cloudflare.com/t/public-r2-bucket-doesnt-handle-range-requests-well/434221
