### ISSUE TITLE
Add the ability to select a channel for uploading videos by default

### ISSUE THREAD

**Issue by kirill2400** [Chocobozzz/PeerTube#5701]
### Describe the problem to be solved

When adding a new channel, it is automatically selected first in the video upload window
![image](https://user-images.githubusercontent.com/30482699/226273150-d2e38b96-a0ea-48a7-9d18-efd8201fe9c4.png)

### Describe the solution you would like

I suggest on this page to set the order, or at least tick the "default"
![image](https://user-images.githubusercontent.com/30482699/226273207-f9efa810-0597-45a2-a201-8677ddbed4da.png)

**Comment by Chocobozzz** [comment]
Hi,

Channels a sorted by `updatedAt` in descending order. It means that if you upload a video in `SpaceComfort`, it will be the first choice for the next upload

**Comment by kirill2400** [comment]
> Hi,
> 
> Channels a sorted by `updatedAt` in descending order. It means that if you upload a video in `SpaceComfort`, it will be the first choice for the next upload. Does this behaviour suit you?

Yes. thanks. But I was need Press Ctrl+F5 for this
