### ISSUE TITLE
Upgraded to 5.1

### ISSUE THREAD

**Issue by Ofloo** [Chocobozzz/PeerTube#5705]
### Describe the problem

Ever since I've upgraded to 5.1 I keep getting this error in the settings page when trying to save the changes.

![afbeelding](https://user-images.githubusercontent.com/2203497/227382195-077a29da-9341-4016-994f-ed5c66ecf9b1.png)

### Additional information

* PeerTube instance URL: https://tube.ofloo.io
* PeerTube version: 5.1

docker running on debian https://pastebin.com/sSZwEKVt

**Comment by Chocobozzz** [comment]
Hello,

https://github.com/Chocobozzz/PeerTube/issues/5666#issuecomment-1456189205 should fix your issue

**Comment by Ofloo** [comment]
I'm sorry but what in particular should fix my issue? I've removed all volumes except those with data, and the issue is still there.

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/docker-compose.yml#L61 is not correctly cleaned on your instance, it seems you still have client files from a previous version

**Comment by Ofloo** [comment]
I guess but if I need to remove all data then I will remove the video's as well. So which volumes are ok to clear as you can see from my  docker compose file some of it is persistent storage.

So what do you mean by client data.

**Comment by Ofloo** [comment]
Not sure how you answered my question. Am I supposed to clear all persistent data !? If so then what am I upgrading !?

Because "docker-compose down -v" is doing just that. And if that's the case why do you keep saying upgrade then just say remove everything. And install new.

Maybe I'm misunderstanding but as you can see docker-compose down -v will delete all volumes !?

**Comment by Ofloo** [comment]
I finally was able to decipher your answer 

Maybe next time just say remove assets volume.

Thanks for your support.
