### ISSUE TITLE
Log warnings about "Invalid end watch section ..."

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5706]
### Describe the current behavior

We're seeing a lot of "Invalid end watch section" warning messages in the logs. 

```
Invalid end watch section 942. Last start record was at 5089.
```

This has been going since at least PeerTube 4.3.1.

### Additional information

* PeerTube instance:
  * Version: 5.1.0
  * NodeJS version: v16.19.1
  * Ffmpeg version: 5.1.2-0ubuntu1~22.04.sav2

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/7815dc450ea9f8fd63e2234b6215013a132e6229
