### ISSUE TITLE
Database Name Environment

### ISSUE THREAD

**Issue by berksmbl** [Chocobozzz/PeerTube#5708]
### Describe the problem

By default the database name is "peertube" and it is not possible to change it with env variables, I can use the docker image only if I create a database as "peertube". However, I host my database as a service elsewhere, and the service provider does not give complete freedom to specify the database name.

### Additional information

* PeerTube version: production-bullseye (Docker)
* Redis version: 7
* PostgreSQL version: 14

**Comment by Jolg42** [comment]
It looks to me that you could set the database name with `POSTGRES_DB=mydbname` from:
https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/.env#L5

If this is confirmed to work we could mention it in:
- https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/docker.md
- https://github.com/Chocobozzz/PeerTube/blob/master/support/docker/production/config/custom-environment-variables.yaml

**Comment by berksmbl** [comment]
> It looks to me that you could set the database name with `POSTGRES_DB=mydbname` from: https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/.env#L5

Hello, This variable only interacts with PostgreSQL. It has no interaction with PeerTube and continues to use its default value.

**Comment by Jolg42** [comment]
@berksmbl Indeed!
I opened a PR to make the appropriate change here: https://github.com/Chocobozzz/PeerTube/pull/5734

**Comment by berksmbl** [comment]
@Chocobozzz The update still hasn't been released on Docker for production.

**Comment by Chocobozzz** [comment]
It's released on docker in `develop-bullseye` image

**Comment by berksmbl** [comment]
> It's released on docker in `develop-bullseye` image

Hello, I am preparing an installation scheme through the one-click install logic on EasyPanel for people to use. We only create templates for production and stable versions. Unfortunately, I cannot use latest or develop versions here. Can you give me an estimated time of completion?

**Comment by berksmbl** [comment]
> It's released on docker in `develop-bullseye` image

Hello @Chocobozzz, I am preparing an installation scheme through the one-click install logic on EasyPanel for people to use. We only create templates for production and stable versions. Unfortunately, I cannot use latest or develop versions here. Can you give me an estimated time of completion?

**Comment by Chocobozzz** [comment]
It will be in docker production image for the next release, ~2 months I think.

**Comment by berksmbl** [comment]
> It will be in docker production image for the next release, ~2 months I think.

Hello @Chocobozzz,
It's longer than I expected. What is the chance of releasing an interim update that only includes this small correction :(
