### ISSUE TITLE
Images in Markdown or in HTML

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5710]
### Describe the problem to be solved

In the Support section (for a channel or for a video) it is possible to add an image, for example like this:
`![альт](https://peervideo.ru/static/st-files/donate.png "Donate")`
Also in the NGINX configuration file I added a directory of static files "st-files"
```
  # Bypass PeerTube for performance reasons. Optional.
  location ~ ^/static/(thumbnails|avatars|st-files)/ {
```
This works fine, but only for the "Support" section

Now I want in the description of my server, in the Financing section of Pertube I want to also add an image (barcode). I may want to add an image in other sections of my server description, but I can't do that because there is no such image support there.

### Describe the solution you would like

A big request is to add support for images in all sections of the server where Markdown or HTML support is used. If this violates security, then you can add this item to the Peertube configuration so that the administrator decides what to choose (either Yes or No).

**Comment by Jolg42** [comment]
I created my first PR on PeerTube for this here https://github.com/Chocobozzz/PeerTube/pull/5732

**Comment by Alterak** [comment]
> I created my first PR on PeerTube for this here #5732

Thank you for this functionality!
Can you tell me how to control the image size?

**Comment by Chocobozzz** [comment]
You can't, please create another issue. https://github.com/markdown-it/markdown-it/issues/80#issuecomment-1146587035 might be the way to handle this case
