### ISSUE TITLE
Require explicit consent

### ISSUE THREAD

**Issue by SoniEx2** [Chocobozzz/PeerTube#5711]
### Describe the problem to be solved

Revenge porn is a big problem, but porn is not the only place where consent is regularly violated. Consent is a big deal and it should be possible to deal with consent violations in a far more straightforward way than they're currently dealt with.

### Describe the solution you would like

Simply remove ppl from the video who didn't explicitly consent to being in the video. This can be done with AI. The only extra step would be requiring the uploader to scan the ppl who consent at the time of upload.

For privacy reasons, none of the scan data nor the original video should be stored or federated anywhere, only the scrubbed video should be stored and federated.

This should be an admin setting, ofc.

**Comment by vid-bin** [comment]
When you've finished the code changes submit a PR and it should be merged.

**Comment by vid-bin** [comment]
Remember that your implementation has to take into account that the majority of peertube instances are hosted on VPS with no access to a GPU. Your implementation would need to be CPU based. Most VPS instances have 1-4 cores/threads.

**Comment by SoniEx2** [comment]
Since it's opt-in it should only be available when a GPU or AI accelerator, plus a video transcode accelerator, is available.

**Comment by vid-bin** [comment]
> Since it's opt-in it should only be available when a GPU or AI accelerator, plus a video transcode accelerator, is available.

Well what you're asking for would be a lot of work. And if only one or two peertube instances will be using it then it doesn't make a lot of sense to dedicate resources towards it.

Peertube only has one full time developer working on it.

**Comment by Chocobozzz** [comment]
Hello,

Thanks for this issue but it's out of the scope of the project. You may want to develop a plugin to resolve this use case :)
