### ISSUE TITLE
The web player get stuck in an infinite retry loop on 404 error on the video file

### ISSUE THREAD

**Issue by ar9708** [Chocobozzz/PeerTube#5712]
### Describe the current behavior

When opening a video where the backend cannot find the source file and returns a 404, the web client reacts by immediately retrying. This leads to our users DDoS'ing our server infrastructure when there's some glitch. Example from this video, https://test.swebbtv.se/w/cobqXhyjzPuDyqVahDVSmK:

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/123388211/227716156-415db81e-4edc-4e9c-b71d-5344330a047b.png">

### Steps to reproduce

1. Open browser logs
2. Open video linked above
3. Notice endless stream of 404 retries

### Describe the expected behavior

If the video file cannot be found, I would expect a dialog/banner to be shown in the UI stating something along the lines of...

> Error: File Not Found, https://test.swebbtv.se/static/webseed/00e11138-ef4b-4a2f-9423-66fb6233f23f-1080.mp4, would you want to retry? &lt;Click button to retry&gt;

As it is now, it's just a spinner shown to the user, so he or she might not realize they're contributing to spamming our servers with a thousand requests per minute in the background.

Alternatively, if retrying in the background for say 1 minute, the player should apply an exponential backoff e.g. 1 sec, 4 sec, 8 sec, 16 sec, 32 sec... 

### Additional information

* PeerTube instance:
  * URL: https://test.swebbtv.se (just ask if you want an admin account, @Chocobozzz!)
  * Version: 5.1
  * NodeJS version: 16
  * Ffmpeg version: ?

* Browser name, version and platforms on which you could reproduce the bug: Chrome 110/latest, arm64 MacOS

**Comment by Chocobozzz** [comment]
Hello,

We'll remove webtorrent support in v6: https://github.com/Chocobozzz/PeerTube/issues/5465

Do you notice this bug with HLS videos?

**Comment by Chocobozzz** [comment]
Ping @ar9708

**Comment by ar9708** [comment]
Thank you @Chocobozzz for looking at this, I did not realise it was a WebTorrent video. I have this disabled on all current server configs:
<img width="543" alt="image" src="https://user-images.githubusercontent.com/123388211/231131118-f65684b4-edfe-4ff6-8a22-5ebe9695e18b.png">

Trying to reproduce the error with a (made broken) HLS video here, https://test.swebbtv.se/w/byVQhnrA36xWagUSSf5njv, I find that the error handling seem legit:
<img width="934" alt="image" src="https://user-images.githubusercontent.com/123388211/231131556-2b6706c7-1ebe-4a5c-aa74-bc12759883d3.png">

I.e. it tries the available resolutions one by one and starts playing the first one that does not yield a 403, or display the _"Failed to play video"_ error and stop retry activity if no resolution could be loaded.
