### ISSUE TITLE
Gracefully handle metrics POST errors

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#5713]
### Describe the problem to be solved

Probably this isn't an issue for users but our sentry is spammed with a lot of `Failed to fetch` due to error during posting metrics.

### Describe the solution you would like

It would be great if these can be logged as warnings instead.

**Comment by Chocobozzz** [comment]
Hello,

What is the root cause of the HTTP errors?

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/89fc0142625126b0a2923c9d625be5d201354bb7
