### ISSUE TITLE
Error "Cannot retrieve OAuth Client credentials" on Webservice with other port than 443

### ISSUE THREAD

**Issue by devnull-hub-lab** [Chocobozzz/PeerTube#5715]
### Describe the current behavior

Hi folks,

I'm having a problem with Peertube when webserver is running on other port than 443.
I'm not using docker, and the ports are open on UFW Firewall.

When I try to enter on login page, I receive the error: Cannot retrieve OAuth Client credentials: Getting client tokens for host [videos.slackjeff.com.br](http://videos.slackjeff.com.br/) is forbidden.

I'm listening nginx webserver on port 9443 (not 443).
And peertube node service on port 9000 (default)

When I set peertube log to 'debug' level, I got the message log:
"message":"Getting client tokens for host [videos.slackjeff.com.br](http://videos.slackjeff.com.br/) is forbidden (expected [videos.slackjeff.com.br:9443](http://videos.slackjeff.com.br:9443/)).","label":"videos.slackjeff.com.br:9443"

I dont know why, but service [videos.slackjeff.com.br](http://videos.slackjeff.com.br/) is trying to communicate on port 443, not 9443

So, only for testing purposes, I configured nginx webserver on port 443 and changed the production.yaml to port 443 as well; and everything runs fine!
The problem is specifically using another port other than 443. I tried 3 times a fresh installations, but same problem occurs.

### Steps to reproduce

1. Fresh Install Peertube (following GIT tutorial)
2. Nginx Webserver running on port 9443 (TLS)
3. Peertube node service running on port 9000

Partial nginx.conf:
...
upstream backend {
  server 127.0.0.1:9000;
}
server {
  listen 9443 ssl http2;
 .....

production.yaml:
listen:
  hostname: '127.0.0.1'
  port: 9000
webserver:
  https: true
  hostname: 'videos.slackjeff.com.br'
  port: 9443

### Additional information

*Debian Buster

* PeerTube instance: v5.1.0
  * URL: https://videos.slackjeff.com.br:9443
  * NodeJS version: v18.15.0.
  * Ffmpeg version: 4.3.5

* Tested on Firefox 111.0.1 and Safari 16.3
*

**Comment by Chocobozzz** [comment]
Hello,

Please use the forum for PeerTube sysadmin support to keep the github issue tracker reserved for bugs/feature requests: https://framacolibri.org/c/peertube
