### ISSUE TITLE
Modify, Hide, Add buttons under the video (like,save etc...)

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5718]
### Describe the problem to be solved

I would like to hid thumb down and replace the thumb up by a gift when clicked open a frame for a donation.
Further maybe some other buttons will be added.
is it possible to do it or should it need to develop a full plugin for that?
thanks

### Describe the solution you would like

Easy access to the list of buttons under the video to add/hide/modify them.

**Comment by Chocobozzz** [comment]
Hello,

You need to develop a plugin :)
