### ISSUE TITLE
Followers list links aren't always formatted properly with Mastodon instance-level followers

### ISSUE THREAD

**Issue by aeharding** [Chocobozzz/PeerTube#5721]
### Describe the current behavior

Some followers of my instance, like aquaticpotato@better.boston, have weird links.

https://urbanists.video/about/follows

<img width="375" alt="image" src="https://user-images.githubusercontent.com/2166114/229231710-7dfdfa36-8dfa-4af2-971a-1fdb6d3a33b8.png">

If you click the link, you get this error:

<img width="402" alt="image" src="https://user-images.githubusercontent.com/2166114/229231020-d1786282-2c14-4068-8f95-457bdfb9ac89.png">

Because the href is https://aquaticpotato@better.boston

### Steps to reproduce

1. Follow `peertube@mypeertubeinstance.com` via Mastodon account
2. Go to PeerTube followers
3. See link doesn't work

### Describe the expected behavior

Should probably link to https://better.boston/@aquaticpotato.

### Additional information

* PeerTube instance: 
  * URL: https://urbanists.video
  * Version: 5.1.0

**Comment by aeharding** [comment]
FWIW, the follower list from the admin panel has the correct link:

<img width="481" alt="image" src="https://user-images.githubusercontent.com/2166114/229295469-88671030-876c-4534-93e9-79b164eb6f39.png">

linking to https://better.boston/users/aquaticpotato

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/d15531fb3567f2f27229d3086ffd48069ca73315
