### ISSUE TITLE
Video player tries to download the entire video when trying to play a livestream replay

### ISSUE THREAD

**Issue by Kinuseka** [Chocobozzz/PeerTube#5724]
### Describe the current behavior

Current example for this is: https://vid.kinuseka.us/w/wwwomUNhoayeViNaWBR15C

The player seems to download the entire video 

on developer tab we see that the player is returning http code 200 which means that the player is not returning the appropriate parameters for a partial content viewing

### Steps to reproduce

1. Create a livestream
2. Do not transcode livestream
3. Start live
4. Stop the live
5. Open developer tab
6. Click networks
8. View the replay of the livestream
9. Observe.

### Describe the expected behavior

It should view the video as normal

### Additional information

* PeerTube instance:
  * URL:
  * Version: 5.1.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by aeharding** [comment]
1. Looks like a CORS misconfiguration.
 2. It looks like you're using r2. it's a cloudflare bug: https://github.com/Chocobozzz/PeerTube/issues/5698#issuecomment-1477205525

This is not a PeerTube issue.

**Comment by Kinuseka** [comment]
Confirmed to be an R2 issue, thanks 
closing this issue now.
