### ISSUE TITLE
Live playback hanging on iOS web views from Slack/Gmail

### ISSUE THREAD

**Issue by ar9708** [Chocobozzz/PeerTube#5725]
### Describe the current behavior

I have 2 videos up for evaluating the live streaming feature for production.

Here is one at 720p: https://test.swebbtv.se/w/8fWHRgp4kkri4emY5hx6ej

Here is another at 240p: https://test.swebbtv.se/w/a4K6kviwb8Pi7iSPN12J8U

When opening these links in Safari on latest iOS 16.4, everything works smoothly and playback starts within seconds. And opening these links on Android 13 with Samsung Internet 20.0.3.x, Chrome 111.x, or Brave 1.49.x on my Samsung Galaxy S21 works equally great. What more works great is desktop Safari 16.4 and desktop Chrome 111.x on my Apple Silicon MacBook. (It has been playing for hours straight in parallel windows, very stable across reloads.)

What does not work is opening these 2 links from Gmail or Slack, which opens up the link in a Safari-like web view, after hitting the "play" button all you get is a spinner that spins for 2+ minutes (maybe forever).

Phase 1 after clicking link within Slack/Gmail apps (still looking normal):
[
![IMG_4719](https://user-images.githubusercontent.com/123388211/229370157-34596ddd-b6b0-4af3-8485-324513f01dd5.PNG)
](url)

Phase 2 after clicking the "play" button, spinner starts and spins indefinitely (notice clock time in the top left corner):
![IMG_4720](https://user-images.githubusercontent.com/123388211/229370241-a76800ee-b5a0-48db-af3f-3240e0ba36be.PNG)

This seem like a blocker for putting this to production, I think we're looking to broadcast the information about a planned live stream via email a couple of hours before the start time, so if everyone who is on iPhone and click our "start watching live" link from the app gets stuck in loading screen, it won't look good. 

@Chocobozzz Do you have any input on how to address and identify the root cause of these mysterious hanging? (And thanks for all your heroic work! 🥇)

### Steps to reproduce

1. Start a permanent/recurring live stream (with "small latency" to avoid P2P)
2. Go to the PeerTube site with a normal desktop/mobile browser, open the video post and press "play" (expect things to work)
3. Copy the live stream URL and send it to yourself in Slack or Gmail
4. Open the message/email in your Slack/Gmail app on iPhone, and find it's opened inside some kind of web view
5. Press "play" on the video and see the spinner spin and spin and spin

### Describe the expected behavior

I would expect live streaming playback to work equally well in any modern web browser context, unless the user involved some odd browser add-on or had networking security in place for blocking the video.

### Additional information

* PeerTube instance:
  * URL: https://test.swebbtv.se
  * Version: 5.1.x
  * NodeJS version: 16.19.1
  * Ffmpeg version: 5.1.2

* Browser name, version and platforms on which you could reproduce the bug: "The iOS 16.4 web view you end up in when clicking in-app URLs", I don't know what it is (but I think it's same as default Mobile Safari?)
* Link to browser console log if relevant: I don't have any access to logs on my iPhone (don't know how)
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): Please let me get back on this, I can try to get them if it might have something to do with the server side of things! 🙂 
*

**Comment by vid-bin** [comment]
The live stream works for me on iOS 16.4 when opened from apples mail app.

This sounds like a bug with those specific apps you mentioned. It's not a peertube issue.

![Church of the Living God - Swebbtv](https://user-images.githubusercontent.com/112714131/229375103-d690eb5a-f9bd-40cf-b247-20da797743fd.png)

**Comment by ar9708** [comment]
> The live stream works for me on iOS 16.4 when opened from apples mail app.
> 
> This sounds like a bug with those specific apps you mentioned. It's not a peertube issue.
> 
> /.../

Hello @vid-bin! Thank you for having a look at this. I re-ran the scenario you point to and I noticed an interesting thing, iOS built-in Mail app does not use the in-app web view at all but opens links in the standard Safari app (and you have this "app switcher" animation as soon as you click a link in the Mail app).

Here is how it looks like when Mail app have opened Safari:
![IMG_4722](https://user-images.githubusercontent.com/123388211/229375612-b6a9d98c-b0e7-494d-b730-2de33d57f683.jpg)

But when opening the "Safari web view" by clicking URLs in apps like Gmail or Slack, the web view animates in from the right side of the screen and you don't end up in the mobile Safari app (you're still in e.g. Slack app if you look at the app switcher):
![IMG_4721](https://user-images.githubusercontent.com/123388211/229375561-f0463097-48fe-453c-a12d-02cc1a7baad4.jpg)

I don't know anything about app development or iOS. Do you happen to know the correct term for the sandboxed "web thing" links are opened in, inside various native apps?

**Comment by vid-bin** [comment]
If it's opening a hardened version of safari I'm not sure there is anything we can do to fix this. It's likely not working because of the P2P aspect of peertube or some other technical limitation.

You may want to consider filing a bug with apple.

**Comment by ar9708** [comment]
> If it's opening a hardened version of safari I'm not sure there is anything we can do to fix this. It's likely not working because of the P2P aspect of peertube or some other technical limitation.
> 
> You may want to consider filing a bug with apple.

Valid point! It could be an Apple thing. A "funny" detail I noticed, is if you let the screen black out and sleep while in this never-ending "spinner screen", immediately after you unlock the phone again and see the spinner, then it stops spinning and starts playing in a second or two.

**Comment by vid-bin** [comment]
Yeah so sounds like an apple issue.

**Comment by Chocobozzz** [comment]
Hello,

Can someone try to paste the webview console logs?

**Comment by Chocobozzz** [comment]
Closing as I don't think we can do anything here on PeerTube side.
