### ISSUE TITLE
oEmbed options not working

### ISSUE THREAD

**Issue by EricGuic** [Chocobozzz/PeerTube#5726]
### Describe the current behavior

When I want to share a video with the oEmbed url, I get this : 
https://tube.reseau-canope.fr/videos/embed/5b3d8a54-2d18-41a2-a7b6-488954cec611
By default, some options are pre-selected : 
![image](https://user-images.githubusercontent.com/81166671/229466679-04d624f9-3afb-49df-949b-f3ed4802180f.png)

If I want to hide some infos (like the title, the warning message...), I can unselect the corresponding options and get an url like : 
https://tube.reseau-canope.fr/videos/embed/5b3d8a54-2d18-41a2-a7b6-488954cec611?title=0&warningTitle=0&peertubeLink=0&p2p=0

But all of the options dosen't work.

### Steps to reproduce

1. Open this url in the web browser : https://tube.reseau-canope.fr/videos/embed/5b3d8a54-2d18-41a2-a7b6-488954cec611?title=0&warningTitle=0&peertubeLink=0&p2p=0
2. Notice the Title, the Warning, and the Réseau Canopé button in the player bar.
3. Change the "0" by "1" in the options : you will notice that the change is made **only for the title**, but nothing happen for the Warning or the Peertube button.

Even weird for a playlist : 
1. Here is the oEmbed url of a playlist : https://tube.reseau-canope.fr/video-playlists/embed/79216e9d-95bc-4e58-bacd-d10ff430f173
2. by default, Title and Warning and Button are displayed (and the "Share" popup window doesn't allow the user to unselect those options like he can do for a single video)
3. add "?title=0&warningTitle=0&peertubeLink=0&p2p=0" at the end and it works exactly as expected ! Each options can be set as wished with "0" or "1"

### Describe the expected behavior

The expected behavior is to see all the options really affected by the change of the value "0" / "1".
And to see the same options in the webUI share section of the playlist.

Idea for improvments :
Having the option (in the webadmin or in the configuration file on server) to specify the default settings for oEmbed (for example in my case _title=0 ; warningTitle=0 ; peertubeLink=0_), so when I click on the "Share" button under a video, the custom options preselected matches this default settings (for iframe and for oEmbed).

### Additional information

* PeerTube instance:
  * URL: tube.reseau-canope.fr
  * Version: 5.0.1 (and the 5/04/2023 we update to 5.1)
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Chrome
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I can't reproduce: title and warning titles are not displayed when I click on your link. Can you take a screenshot? And do you have some messages in web browser console logs?

**Comment by EricGuic** [comment]
Hi Chocobozzz, very sorry to disturb you, because the problem have vanished here too. I don't understand because I've seen it for a couple of weeks (and this morning again), and I don't see what has changed during lunch.
I will check again and see if I can reproduced it...

**Comment by Chocobozzz** [comment]
Then please create a dedicated issue by filling the feature request template.
