### ISSUE TITLE
Transcode Live replay 

### ISSUE THREAD

**Issue by Kinuseka** [Chocobozzz/PeerTube#5729]
### Describe the problem to be solved

Currently by default we only have 2 options, Remuxing during live or Transcode during live. 

When the live ends and Live transcoding option is turned off, the video replay would not be transcoded by default. 

for instances that does not have alot of resources, then disabling Transcoding for only during live would be viable choice to ensure that the stream would play smoothly.

### Describe the solution you would like

But after the stream ends, I believe it would make sense after a certain period of time to transcode the live replay based on the specification of the VOD Transcoding setting.  

This feature should be also a toggable setting, to ensure all are satisfied.

For example:
- [ ] Transcode Live replay 
`After:  1600 seconds/hours/days`

**Comment by Alterak** [comment]
I have already created such a function request, but my request has been open for a very long time. It is a pity that this issue is not being resolved-(
https://github.com/Chocobozzz/PeerTube/issues/3914
