### ISSUE TITLE
CloudStorage B2 [no automatic deletion file]

### ISSUE THREAD

**Issue by morpheustao** [Chocobozzz/PeerTube#5735]
### Describe the current behavior

When someone deletes a video, it is correctly removed from the portal and is no longer visible. But I realized that the files remain on the cloud.

Over time I think I have accumulated an inordinate amount of garbage on the cloud. 

What could be the problem and how can I fix it?

### Steps to reproduce

1. Deleting a video
2. I check that it is deleted on the site
3. In the job queue, I can't find anything about a possible deletion process from the cloudstorage
4. I realize that it is not cancelled by B2

### Describe the expected behavior

I expect that when a video is deleted, it will also be deleted on the external storage

### Additional information

* PeerTube instance:
  * Version: 5.1.0

**Comment by Chocobozzz** [comment]
Hello,

Please enable debug logs in peertube configuration, delete a video file and paste the logs

**Comment by kukhariev** [comment]
For B2 it is necessary to set bucket lifecycle settings -> "Keep only the last version of the file".
The file will be "hidden" for one day and then actually deleted.
