### ISSUE TITLE
Account link width on video page is too much

### ISSUE THREAD

**Issue by tcitworld** [Chocobozzz/PeerTube#574]
* **PeerTube version or URL:** Peertube Beta 4
* **Browser name/version:** Firefox 61

The account link on the video page takes the full width of the container, which can cause misclicks:

![](https://framapic.org/WSbfD7Ntrwa7/UsaZtLaVsI99)

A quick and dirty fix I've found is to change `display: flex` on the link to `display: inline`.

**Comment by rigelk** [comment]
Thanks @tcitworld for spotting the bug!
