### ISSUE TITLE
Choose the default quality

### ISSUE THREAD

**Issue by aflamrip** [Chocobozzz/PeerTube#5743]
### Describe the problem to be solved

When watching the video on the instance, it works well, and the lowest quality is chosen at the start of playback for the speed of downloading the file, and then the quality is improved
But when using the embed link at startup, the highest quality is chosen, and the video may take some time to work

### Describe the solution you would like

If possible, update the embed so that it starts running at a lower quality as the default driver on the instance
Or an option can be added in the Share settings to specify the default quality, such as the default subtitle option

**Comment by Chocobozzz** [comment]
Hello,

Can you share the video where your reproduced this behaviour?

**Comment by aflamrip** [comment]
This example
https://peertube.cpy.re/w/s1FsHY6YQ1x8o18yC6QbPd
You can watch the default quality of the video upon playback starting with 480p quality
As for this example
https://peertube.cpy.re/videos/embed/d2a5ec78-5f85-4090-8ec5-dc1102e022ea
You can watch the default quality of the video when you play it, starting with 720p quality
It's the same video, but I don't know why it doesn't start at 480p on the embed link

**Comment by Chocobozzz** [comment]
This video uses webtorrent technology, that will be removed in v6: https://github.com/Chocobozzz/PeerTube/issues/5465
Do you reproduce the issue with a HLS video, like this one https://framatube.org/w/58UdeJ7NayzNSScpTE3YRa?

**Comment by aflamrip** [comment]
Same problem when starting the video on this link
https://framatube.org/w/58UdeJ7NayzNSScpTE3YRa
Look quickly at the video quality and you will find that the quality starts at 480p and then starts to improve
But if you open the video from the embed link
https://framatube.org/videos/embed/217eefeb-883d-45be-b7fc-a788ad8507d3
When you start playing the video, look at the quality of the video quickly, you will find that it starts playing at 720p quality or higher, and this may be the cause of the slow startup problem for some users

Also, I noticed something when playing videos through embed links
https://framatube.org/videos/embed/217eefeb-883d-45be-b7fc-a788ad8507d3
After watching a few minutes, presenting the video, exiting and returning again, or reloading the browser, it is not possible to complete the viewing. The video is downloaded from the beginning every time, unlike watching from the main video link.
https://framatube.org/w/58UdeJ7NayzNSScpTE3YRa
The viewing is completed from any point it stopped at

**Comment by Chocobozzz** [comment]
PeerTube stores your average bandwidth in web browser local storage so I think it's expected that you starts at 480p with your first video, and then at 720p because it remembered your previous bandwidth.

Embeds don't support videos resuming by design.
