### ISSUE TITLE
Missing plugins-global.css file during Peertube startup

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5744]
### Describe the current behavior

When Peertube starts, some requests are failing because of a missing plugins-global.css file.
Depending on the number of plugins, and the time they take to start, Peertube can be unavailable during several seconds/minutes.

Here is the error when trying to display Peertube home page:

```
peertube_1  | [localhost:9000] 2023-04-10 12:24:42.566 error: Cannot generate HTML page. {
peertube_1  |   "err": {
peertube_1  |     "stack": "Error: ENOENT: no such file or directory, open '/data/tmp/plugins-global.css'",
peertube_1  |     "message": "ENOENT: no such file or directory, open '/data/tmp/plugins-global.css'",
peertube_1  |     "errno": -2,
peertube_1  |     "code": "ENOENT",
peertube_1  |     "syscall": "open",
peertube_1  |     "path": "/data/tmp/plugins-global.css"
peertube_1  |   }
peertube_1  | }

```

I found the code that is responsible of this, and I will make a PR in a minute.

### Steps to reproduce

1. Install some plugins
2. Restart Peertube
3. Try to open peertube in a browser

### Additional information

* PeerTube instance:
  * URL:
  * Version: 5.1.0
  * NodeJS version:
  * Ffmpeg version:

**Comment by JohnXLivingston** [comment]
> Is this fix included in latest version v5.2.0? I am still getting it.
> 
> ```
> [domain.tld:443] 2023-08-03 14:19:58.527 error: Error retrieving the Plugin Global CSS file, ignoring it. {
>   "err": {
>      "stack": "Error: ENOENT: no such file or directory, open '/var/www/peertube/storage/tmp/plugins-global.css'",
>      "message": "ENOENT: no such file or directory, open '/var/www/peertube/storage/tmp/plugins-global.css'",
>     "errno": -2,
>     "code": "ENOENT",
>     "syscall": "open",
>     "path": "/var/www/peertube/storage/tmp/plugins-global.css"
>   }
> }
> ```

Yes, it is included. In your case, you have the error log, but the server is no more crashing.

This error log should only happen under very rare conditions. You should only see it once after a restart. If you see it multiple time, it can be another issue.

**Comment by Chocobozzz** [comment]
There is a bug, I'll fix it ;)

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/3ff44b67eaf8e2cae2cee1880dab3217e339a8e1
