### ISSUE TITLE
Live Playback Broken on iOS Safari and Chrome

### ISSUE THREAD

**Issue by ar9708** [Chocobozzz/PeerTube#5745]
### Describe the current behavior

When opening (any) PeerTube live stream in Safari or Chrome on latest iOS, the playback breaks down within a minute or two.

I have been watching these 2 live streams non-stop on latest macOS in Safari and Chrome, on Ubuntu 22 in Firefox, and on Android in Samsung Internet and Chrome, and it works really great:
* https://swebbtube.se/w/aS2nB4FQqZGkCE92iGWth2
* https://swebbtube.se/w/4sAQGBsdkEC257RBi3zLQ2

It goes on and on, as long as playback is not interrupted for too long (see #5733). However, on latest iPhone iOS, the same live video playback consistently breaks down in a minute or two. This happens on Mobile Safari, Chrome, and Edge (WebKit browsers?). Video always start up normally, but comes to a halt after 10-15 seconds or longer, sometimes it can play even up to a few minutes.

Illustration:
<img width="1691" alt="Screenshot 2023-04-10 at 14 07 41" src="https://user-images.githubusercontent.com/123388211/230902439-7a0e58dd-fba0-41ba-8e64-c9c3441a2496.png">

### Steps to reproduce

1. Start a live video stream backed by S3/object storage (permanent/recurring live stream, no replay, no transcoding, and small latency mode)
2. View live video in any browser on Mac or Android (things look fine, can play 30 minutes and more without interruption)
3. Open same live video in Safari or Chrome on latest iPhone/iOS and watch until it breaks down within minutes

### Describe the expected behavior

I would expect live video playback to work the same on the major browsers and device types. 🙃 

**Update at 2023-04-10T22 CET with respect to [findings mentioned in comment 1502250885 below](https://github.com/Chocobozzz/PeerTube/issues/5745#issuecomment-1502250885):** I would want Mobile Safari/Chrome to apply the moderate retry logic suggested in #5733, i.e. some exponential back-off between retries, a reasonable ceiling on 403/404 retries, and a fallback strategy that checks the `m3u8` metadata so we're not grabbing for long gone video segments.

### Additional information

* PeerTube instance:
  * URL: https://swebbtube.se
  * Version: 5.1.x
  * NodeJS version: 16
  * Ffmpeg version: 4.2.x

* Browser name, version and platforms on which you could reproduce the bug: Mobile Safari and Google Chrome 112.x on iOS 16.4.1 (iPhone 14)
* Link to browser console log if relevant: I don't know how to get them...
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): Let me look!

**Comment by Chocobozzz** [comment]
Hi,

Our HLS player that uses mediasource can handle 404 segment responses and correctly retry them.
iOS on iphone doesn't support mediasource (:angry:) so we need to use their HLS player, and it seems it doesn't retry on requests on 404.

We need to update PeerTube backend so we wait the segment to be uploaded on S3 before uploading the playlist variant file (m3u8) (for now they are uploaded in parallel).

**Comment by ar9708** [comment]
> /.../
> I have been watching these 2 live streams non-stop on latest macOS in Safari and Chrome, on Ubuntu 22 in Firefox, and on Android in Samsung Internet and Chrome, and it works really great:
> 
> * https://swebbtube.se/w/aS2nB4FQqZGkCE92iGWth2
> * https://swebbtube.se/w/4sAQGBsdkEC257RBi3zLQ2

Sorry, these 2 streams were down for a moment in the morning, but now they should be up (for a week on stretch at least).

> Hi,
> 
> Our HLS player that uses mediasource can handle 404 segment responses and correctly retry them. iOS on iphone doesn't support mediasource (😠) so we need to use their HLS player, and it seems it doesn't retry requests on 404.
> 
> We need to update PeerTube backend so we wait the segment to be uploaded on S3 before uploading the playlist variant file (m3u8) (for now they are uploaded in parallel).

@Chocobozzz Thank you for explanation! I've noticed some subtle differences in the iOS player (like the "Quality" drop-down often being broken, unlike Android/desktop) but I never had any clue as to why, but your remark sheds some light on this! 🌟 Is it a big/difficult change to wait with publishing the `m3u8` metadata until the video segments are pushed to object storage?

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/34023e12534f22f28d0b5afc1db3fdf2fd1e7e60

See https://github.com/Chocobozzz/PeerTube/pull/5765#issuecomment-1541749210
