### ISSUE TITLE
More filters / hide filters text color bug on Dark mode

### ISSUE THREAD

**Issue by Showfom** [Chocobozzz/PeerTube#5749]
### Describe the current behavior

https://peertube3.cpy.re/videos/trending

<img width="407" alt="image" src="https://user-images.githubusercontent.com/6773591/231831595-6ca8acb4-2be1-4924-b8ce-32908b7072ff.png">

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! Fixed by https://github.com/Chocobozzz/PeerTube/commit/8b95440c8ac050594955926f18dab9f6d4a86e19
