### ISSUE TITLE
Changing video channels

### ISSUE THREAD

**Issue by leethax666** [Chocobozzz/PeerTube#575]
I created a couple channels and I can't move any of my existing uploads into them

**Comment by fflorent** [comment]
If you need a workaround, and now a little bit of SQL, you may change the `"channelId"` field (quotes required in your SQL commands) of the `video` entry you'd like. `"channelId"` is a foreign key pointing to the `"videoChannel"` table.

If you need to take a look at the description of any table using the `\d "<tablename>"` command.

Hope this can help!
Florent

**Comment by Chocobozzz** [comment]
@leethax666 Hi, it's a duplicate of https://github.com/Chocobozzz/PeerTube/issues/349. That will be available in the next release

@fflorent Thanks for the tip but please don't do that since it would create inconsistency in the federation
