### ISSUE TITLE
Support for non standard SSL Configurations (8443)

### ISSUE THREAD

**Issue by BataBoom** [Chocobozzz/PeerTube#5750]
### Describe the problem to be solved

I've read over the threads discussing 'Invalid client: client is invalid'. Most people misconfigured their boxes and just had to set port to standard 443.  Though I've got multiple HTTP/S services on this box (that don't use nginx) unfortunately.  It would require too much work to change those services to something non standard, and then using standard ports in this scenario. 

Anyhow its up and it looks pretty, but I can't login 

```
peertube[1777512]: [cdn-07.private.com:8443] 2023-04-14 07:52:41.066 error: Client log: Backend returned code 400, errorMessage is: Invalid client: client is invalid {
Apr 14 07:52:41 peertube[1777512]:   "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:111.0) Gecko/20100101 Firefox/111.0",
Apr 14 07:52:41 peertube[1777512]:   "url": "https://cdn-07.private.com:8443/login"
Apr 14 07:52:41 peertube[1777512]: }
```

### Describe the solution you would like

Hopefully one day this may be supported, I look forward to using it.

**Comment by Chocobozzz** [comment]
Hello,

We should support non standard SSL configuration. You may have an issue in a previous HTTP request where PeerTube tries to fetch the oauth client token

**Comment by BataBoom** [comment]
Apologies on the delay, I wasn't expecting a reply so quickly 😳 👏! That does appear to be the issue. Wish I hadn't posted in features now, cause I'd like to continue this thread on a 'bug'. Through the CLI I updated the host post-install. When I query the log I find that it generated oauth 'tokens' for example.com 😳

{"message":"Client id: qdl9usowtpa7f65xrszyejdi6lz3f1b5","level":"info","label":"example.com:9443","timestamp":"2023-04-14T05:54:54.506Z"}
{"message":"Client secret: plfFCHO5qtgRHESLrSkxXkU1xHisiYDG","level":"info","label":"example.com:9443","timestamp":"2023-04-14T05:54:54.506Z"}
{"message":"Generating a RSA key...","level":"info","label":"example.com:9443","timestamp":"2023-04-14T05:54:54.527Z"}
{"message":"Generating a RSA key...","level":"info","label":"example.com:9443","timestamp":"2023-04-14T05:54:54.637Z"}
{"message":"Generating a RSA key...","level":"info","label":"example.com:9443","timestamp":"2023-04-14T05:54:54.637Z"}
{"message":"Username: root","level":"info","label":"example.com:9443","timestamp":"2023-04-14T05:54:54.731Z"}

How should I go about re-generating these, if possible without full reinstall?

Many thanks!

**Comment by Chocobozzz** [comment]
You can use https://docs.joinpeertube.org/maintain/tools#update-host-js
