### ISSUE TITLE
Plugin Websocket routes can make crash Peertube server

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5752]
### Describe the current behavior

If a plugin uses `registerWebSocketRoute` to declare websockets endpoints, and if the plugin's handler throw an exception, Peertube crashes.

### Steps to reproduce

1. install a plugin that declares a websocket route, and that throw an error in the handler
2. try to connect to the websocket route

### Describe the expected behavior

I think we should add a try/catch around `wss.handler(request, socket, head)` in the following function:

https://github.com/Chocobozzz/PeerTube/blob/e7c89cc3f3e69776c6ad62e62a52f8d2f12a81c1/server/lib/plugins/plugin-manager.ts#L80-L100

Moreover, I wonder if the multiple `return` statements are valid. Shouldn't we close the socket if there is no plugin or route?
I'm perhaps wrong, but I think that the sockets are not closed, and the connection will hang for a while. So it could be used to DDOS the server by open multiple random websocket connections, on random routes.

### Additional information

* PeerTube instance:
  * Version: 5.1.0

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/82d1653d799ccc0bcc228bb5e5aafef7a071c2db

No need to destroy the socket, there are other ws handlers in peertube executed after this one

**Comment by JohnXLivingston** [comment]
> No need to destroy the socket, there are other ws handlers in peertube executed after this one

Ok thanks!
