### ISSUE TITLE
User roles are not translatable

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5754]
### Describe the current behavior

In the create user windows, and in the Role drop down menu, user roles (user, moderator, administrator) are not translatable.

### Steps to reproduce

1.
2.
3.

### Describe the expected behavior

Be able to translate user roles in Weblate.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/208c97e111f2610880a588964bb61a03503cfcf6
