### ISSUE TITLE
Plugins and Themes buttons are not translatable

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5755]
### Describe the current behavior

In the Administration->plugins/themes window, there are 4 buttons. The texts on the "Plugins" button and "Themes" button are not translatable. The other two buttons are correct.

### Steps to reproduce

1.
2.
3.

### Describe the expected behavior

To be able to translate the texts on these two buttons on Weblate.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks, they should now be translatable: https://github.com/Chocobozzz/PeerTube/commit/df0bd13210d8d6fa1431df2449afc0d49188a2ca
