### ISSUE TITLE
current time is not saved when page is reloaded or left and further back to the video

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5756]
### Describe the current behavior

Before update to 5.1.0 PT was saving ok the current video time but now, it's just restart the video from the zero everytime the page is loaded or left and back.

### Steps to reproduce

watch a movie several sec/min then leave and go back.

### Describe the expected behavior

should save the current time of the player (and if possible quality and speed)

**Comment by vid-bin** [comment]
Works fine for me. Standard peertube install, no S3 and using iOS safari.

**Comment by ROBERT-MCDOWELL** [comment]
any cookie to set nor else behind a reverse proxy?

**Comment by vid-bin** [comment]
Are you sure this is due to your content-security-policy cookie? Easy way to check would be to revert it back to default.

**Comment by ROBERT-MCDOWELL** [comment]
mmhmmm, seems that PT cookies contain non alpha letters and my policy restrict cookie to alphanumerical chars.
I'm going to disable the policy and see what's happening.

**Comment by Chocobozzz** [comment]
Hello,

Do you use a logged in user or an anonymous one?

**Comment by Chocobozzz** [comment]
Do you have videos history enabled?

**Comment by ROBERT-MCDOWELL** [comment]
@Chocobozzz 
no history enabled. I logged out and watched a video as anonymous and indeed the current time after reload works.
are you using special chars (non alpha) as cookie name or data?

**Comment by Chocobozzz** [comment]
Videos history has to be enabled in your account so the server saves your last "current time".
