### ISSUE TITLE
Noscript wording issue...

### ISSUE THREAD

**Issue by JigmeDatse** [Chocobozzz/PeerTube#5757]
### Describe the current behavior

When using no script you get "options" with the third one listed as:

* Review the source code on GitHub or Framasoft's GitLab, and ask for eventual modifications to the instance owner.

### Steps to reproduce

1. connect to site with JavaScript turned off...
2.
3.

### Describe the expected behavior

The wording is awkward (not sure if there's different translations getting fed, but this is English).  I would consider something like:

* Review the source code on GitHub or Framasoft's GitLab, and ask for modifications from the instance owner.

Though...  Issues for the project would be preferable to modifications for the specific instance.  Ie. have it suggest the requests go *first* to one of the GitHub or GitLab repositories.  Then specifically to the instance owner.

**Comment by Chocobozzz** [comment]
Done in https://github.com/Chocobozzz/PeerTube/commit/3ba6af5265abac83da88fa353c0d54ef1cb779d6
