### ISSUE TITLE
Live streaming benchmark

### ISSUE THREAD

**Issue by emiliana32** [Chocobozzz/PeerTube#5759]
Hello,
I looked in the peertube [documentation](https://docs.joinpeertube.org/admin/configuration#live-streaming), but I couldn't find any limit on the maximum number of simultaneous users in a live stream given a certain hardware configuration. I only found old [test-benchmarks](https://framacolibri.org/t/fonctionnalite-live-retour-dutilisation/10070/54) that were run when the live stream functionality of peertube 3.0 was launched.
Is there a more up-to-date benchmark that allows users to compare with other streaming services/systems?
Thank you

**Comment by Chocobozzz** [comment]
Hello,

Unfortunately no. We want to create a real setup to automatically spawn a Selenium grid so we can benchmark PeerTube with real web browsers and find bottlenecks and P2P ratio. We'll try to do this work this year :)

**Comment by Chocobozzz** [comment]
We conducted a real world test with 1,000 viewers that watch the same livestream. See the report on the following blog post: https://joinpeertube.org/news/stress-test-2023
