### ISSUE TITLE
'Other Videos' is hidden on small screens

### ISSUE THREAD

**Issue by andzdroid** [Chocobozzz/PeerTube#576]
Sometimes when I was on a peertube video, I would see the 'other videos' column, but sometimes I didn't see it. This behaviour is confusing, and I thought maybe my peertube version was wrong or incorrectly configured.

After investigating, it seems that it's simply hidden on small screens.

It could be shown as a row in between the description and comments maybe, or simply after the comments. Or make the comments column smaller (it really doesn't need to stretch across the screen), and have the 'other videos' section always appear in the same place no matter the screen size.

**Comment by rigelk** [comment]
I think adding a row between the description and comments is the most appropriate. Stretching the comments to fit the videos only displaces the problem.

**Comment by Chocobozzz** [comment]
Agreed with @rigelk.
