### ISSUE TITLE
Live `replaySettings` are sent, even though `saveReplay` is disabled

### ISSUE THREAD

**Issue by mblomdahl** [Chocobozzz/PeerTube#5761]
### Describe the current behavior

I tried to start a live video stream using latest develop, but saving the live stream event fails with a "Bad Request" error:
![image](https://user-images.githubusercontent.com/786326/233060263-3c24388a-2f13-4175-93d8-23c6113865f6.png)

It seems that the client sends a `body.replaySettings` response back to the server, even though live replay is disabled, which yields the following error:
![image](https://user-images.githubusercontent.com/786326/233059221-f336ed94-3a15-415a-888a-0b3660e6ab8d.png)

### Steps to reproduce

1. Have live streaming enabled in settings, but disable "live replay"
2. Create a new permanent live stream video
3. Try to save the live video settings and get an error

### Describe the expected behavior

The client should not send `replaySettings` object if replay is disabled

### Additional information

* PeerTube instance:
  * URL: http://localhost:9000/
  * Version: origin/develop
  * NodeJS version: 14.21.x
  * Ffmpeg version: 4.2.x

* Browser name, version and platforms on which you could reproduce the bug: Chrome (latest) on Windows 10
* Link to browser console log if relevant: No
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): See screenshot above!

**Comment by wickloww** [comment]
Thanks :slightly_smiling_face: it should be fixed in https://github.com/Chocobozzz/PeerTube/pull/5762
