### ISSUE TITLE
Account redirect should be case insensitive

### ISSUE THREAD

**Issue by aeharding** [Chocobozzz/PeerTube#5763]
### Describe the current behavior

Currently, if you mention a user with all lowercase but their actual username is camelcased, it will fail to redirect.

### Steps to reproduce

1. Observe this fails: https://urbanists.video/services/redirect/accounts/drtcombs@transportation.social
2. Observe this succeeds: https://urbanists.video/services/redirect/accounts/DrTCombs@transportation.social

### Describe the expected behavior

Should be case insensitive

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/85c20aaeb90ef0e0f44c377e62c323fde275cdde
