### ISSUE TITLE
Audio clicking artifacts upon transcoding certain file when viewed with Firefox

### ISSUE THREAD

**Issue by aeharding** [Chocobozzz/PeerTube#5764]
### Describe the current behavior

One of our users is experiencing an issue where they try to upload a file with good sounding audio, and the audio gets annoying clipping artifacts (Firefox-only) that make it hard to watch.

We are using default settings for transcoding.

Here's the video once transcoded: https://urbanists.video/w/5FgLJv6aRz3YHSkgv6WJa3

### Steps to reproduce

1. Upload the following file and let PeerTube transcode: https://drive.google.com/file/d/1PDqM827_YfFjVGJOHxfCAia4gCP-fEZK/view?usp=share_link
2. Observe audio clipping issues as seen in the following video when viewed in Firefox: https://urbanists.video/w/5FgLJv6aRz3YHSkgv6WJa3

### Describe the expected behavior

Audio should sound like the original file without clipping artifacts.

### Additional information

* PeerTube instance:
  * URL: https://urbanists.video
  * Version: 4.1.0
  * NodeJS version:
  * Ffmpeg version: 4.3.5

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

```
ffmpeg version 4.3.5-0+deb11u1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
```

Firefox version 112.0.1
on Macos 13.3.1

**Comment by aeharding** [comment]
Follow up, this appears as if it's a Firefox bug. I created this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1828967

It would still be nice to transcode audio so we are guaranteed it will playback nicely, so the original file audio stream doesn't need to be trusted 🙂 For example YouTube does this, notice the audio is just fine: https://www.youtube.com/watch?v=2f9fUnPlitU

**Comment by Chocobozzz** [comment]
Hi,

Closing as it doesn't seem to be a peertube bug. We can add a workaround on peertube side, but we would need to know how to detect this kind of bad audio input first.
