### ISSUE TITLE
RDF link https://joinpeertube.org/ns# broken

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5767]
### Describe the desired information/correction

Since the recent documentation changes, the link `https://joinpeertube.org/ns#` (which is given in JSON-LD context) does not redirect to the correct page.
If i open it in a browser, it redirects to `https://docs.joinpeertube.org/#/api-activitypub`, which only displays the doc home page.
I think the correct link should be `https://docs.joinpeertube.org/api/activitypub`.

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed
