### ISSUE TITLE
Hook filter:html.client.json-ld.result appears in the documentation, but is not yet released

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5768]
### Describe the desired information/correction

On page https://docs.joinpeertube.org/api/plugins, there is a `filter:html.client.json-ld.result` hook that is not released yet, and there is no comment to say it will come with Peertube >= 5.2.

Moreover, it seems that the online documentation is updated on each commit on the `dev` branch. Wouldn't it be better to only update from the `master` branch?

**Comment by Chocobozzz** [comment]
Version added in https://github.com/Chocobozzz/PeerTube/commit/257fa0d1a06b0110335ca53fb6cd341b6759fa5a
