### ISSUE TITLE
Find a way to have more language set in video metadata

### ISSUE THREAD

**Issue by anubis2814** [Chocobozzz/PeerTube#5772]
### Describe the problem to be solved

So many videos don't have a language and therefore show up in feeds when filtering for a language.  

### Describe the solution you would like

Require either a language or no dialogue to be selected before they can publish a video.   Better yet if you could put reminders or notifications on videos reminding people to set languages that don't have them.

**Comment by Chocobozzz** [comment]
Maybe having a tool that guesses the language from the audio could also be interesting

**Comment by zordsdavini** [comment]
I can't select right language (Samogitian, sgs) as video language because it is not in the list

**Comment by Chocobozzz** [comment]
Hi,

The transcription feature automatically set the language of the video if enabled, so I think we can close this issue
