### ISSUE TITLE
FFMPEG path

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5775]
### Describe the problem to be solved

Is there any way to change the ffmpeg path? I have 2 ffmpeg installed and would like to use the special compiled one

thanks

### Describe the solution you would like

have a variable in production config where we can change the ffmpeg path.

**Comment by ROBERT-MCDOWELL** [comment]
I set FFMPEG_PATH to a ffmpeg last git but peertube complains:
Could not find ffmpeg version in ffmpeg version N-110402-ge3143703e9 Copyright (c) 2000-2023 the FFmpeg developers\nbuilt with gcc 12 (GCC)\nconfiguration:

does it imean I cannot use any FFMPEG from  git?

**Comment by Chocobozzz** [comment]
PeerTube cannot guess the ffmpeg "classic" version because the git version doesn't provide it. But you still can use ffmpeg from git anyway :)

**Comment by ROBERT-MCDOWELL** [comment]
you mean "can guess the classic version"... yes, there is an error in the log telling that it does not recognize the git version, but I noticed that all transcoding were in standby.... so for now I'm using a special ffmpeg 6.0 compiled in a special folder with special FFMPEG_PATH env.
