### ISSUE TITLE
Moving private videos: Migration script trouble for >=v5.0

### ISSUE THREAD

**Issue by bolt-blue** [Chocobozzz/PeerTube#5776]
### Describe the problem

Following the instructions in the [CHANGELOG][changelog], while upgrading from `v4.3.0`.
All seems to have gone smoothly, except for running the migration script.

> Classic installation: `cd /var/www/peertube/peertube-latest && sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production node dist/scripts/migrations/peertube-5.0.js`

If you need further info let me know.

I get the following error and am not sure how to proceed:

```
Moving private video files in dedicated folders.
Moving files of video b2293aaf-9b4d-4286-911b-0435253e6b72.
Cannot move files of video b2293aaf-9b4d-4286-911b-0435253e6b72. NoSuchKey: The specified key does not exist.
    at deserializeAws_restXmlNoSuchKeyResponse (/var/www/peertube/versions/peertube-v5.1.0/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:6155:23)
    at deserializeAws_restXmlPutObjectAclCommandError (/var/www/peertube/versions/peertube-v5.1.0/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5810:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/www/peertube/versions/peertube-v5.1.0/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /var/www/peertube/versions/peertube-v5.1.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async /var/www/peertube/versions/peertube-v5.1.0/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /var/www/peertube/versions/peertube-v5.1.0/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:58:20
    at async /var/www/peertube/versions/peertube-v5.1.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 404,
    requestId: '97F52D6CF77781F2',
    extendedRequestId: 'XsNNE5pM5Ke3KS37DVxgWWGs5/lVIu216twcEPBiDLISIY4z2K2NW7G3T6J+ZEs3QYObQFe/ugiH',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Code: 'NoSuchKey',
  Key: 'videos/1dc2995f-8d02-46fa-acba-437adc737e36-480.mp4',
  RequestId: '97F52D6CF77781F2',
  HostId: 'XsNNE5pM5Ke3KS37DVxgWWGs5/lVIu216twcEPBiDLISIY4z2K2NW7G3T6J+ZEs3QYObQFe/ugiH'
}
```

[changelog]: https://github.com/Chocobozzz/PeerTube/blob/develop/CHANGELOG.md#important-notes-2

### Additional information

* PeerTube instance URL:
* PeerTube version: 5.1.0
* NodeJS version: 19.0.0
* Ffmpeg version: 5.1.2
* Redis version: 7.0.5
* PostgreSQL version: 14.5

We use s3 storage from wasabi

**Comment by Chocobozzz** [comment]
Hello,

Do this video file exists in your S3 bucket?

**Comment by bolt-blue** [comment]
No, apparently not. Searched for the filename based on `key` from the error message.

**Comment by Chocobozzz** [comment]
> Is there a neat way to get the database back to a happy place? Assuming that's the issue.

Yes it is: you can remove videos that have this error. Since the files are gone, they should not work anyway.
