### ISSUE TITLE
Postgres issues

### ISSUE THREAD

**Issue by ncamacho97** [Chocobozzz/PeerTube#5777]
### Describe the problem

https://imgur.com/a/KO0BOZR

### Additional informatio

version: "3.3"
services:

  peertube:
    # If you don't want to use the official image and build one from sources:
    # build:
    #   context: .
    #   dockerfile: ./support/docker/production/Dockerfile.bullseye
    image: chocobozzz/peertube:production-bullseye
    # Use a static IP for this container because nginx does not handle proxy host change without reload
    # This container could be restarted on crash or until the postgresql database is ready for connection
    env_file:
      - .env

    ports:
     - "1935:1935" # Comment if you don't want to use the live feature
     - "9000:9000" # Uncomment if you use another webserver/proxy or test PeerTube in local, otherwise not suitable for production
    volumes:
      - assets:/app/client/dist
      - ./docker-volume/data:/data
      - ./docker-volume/config:/config
    depends_on:
      - postgres
      - redis
      - postfix
    restart: "always"

  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - ./docker-volume/db:/var/lib/postgresql/data
    restart: "always"

  redis:
    image: redis:6-alpine
    volumes:
      - ./docker-volume/redis:/data
    restart: "always"

  postfix:
    image: mwader/postfix-relay
    env_file:
      - .env
    volumes:
      - ./docker-volume/opendkim/keys:/etc/opendkim/keys
    restart: "always"

networks:
  default:
    ipam:
      driver: default
      config:
      - subnet: 172.30.0.0/16
volumes:
  assets:
  certbot-www:

**Comment by ncamacho97** [comment]
seems like postgres won't create the user for some reason @JohnXLivingston  @Chocobozzz

**Comment by ncamacho97** [comment]
I Don't understand why there's lots of tickets not solved @Chocobozzz

**Comment by JohnXLivingston** [comment]
Did you read the error message?
It says it can't authenticate to the database. 

Please, don't @ me here, I'm not an official Peertube maintainer. And please be a bit more patient, we all have personal lives, and can't be available all days, including holidays and week-ends.

**Comment by ncamacho97** [comment]
my apologies
