### ISSUE TITLE
Video cannot play after upgrading PeerTube from 4.3.1 to 5.0.1

### ISSUE THREAD

**Issue by vendornet** [Chocobozzz/PeerTube#5778]
### Describe the current behavior

Hi,

I had a PeerTube instance running on a docker with a standard YML file. PeerTube 4.3.1 was running fine. I’ve updated it to 5.0.1 and the main functionality seems to work, however I noticed that videos that I’ve imported from Youtube no longer play. I got an error message “The media could not be loaded, either because the server or network failed or because the format is not supported.”.

I’ve updated PeerTube to version 5.1.0 and the issue still persists.

It is strange because the videos which I’ve uploaded are working without any issues. Only the Youtube videos which I’ve uploaded only with a link from PeerTube do not play (Import with URL).

If I import the Youtube video again with (Import with URL) it starts playing without issues.

### Steps to reproduce

1. Install PeerTube 4.3.1
2. Import Youtube video via Import with URL
3. Update to PeerTube 5.0.1
4. Open the Youtube video 

### Describe the expected behavior

The video should play.

### Additional information

* PeerTube instance:
  * URL:
  * Version: 5.1.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Safari on iPad OS 16.4.1
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by vid-bin** [comment]
Were you using webtorrent instead of HLS? The webtorrent format is being deprecated so it wouldn't surprise me if this was the issue.

**Comment by vendornet** [comment]
> Were you using webtorrent instead of HLS? The webtorrent format is being deprecated so it wouldn't surprise me if this was the issue.

How can I tell which format am I using?

**Comment by vid-bin** [comment]
Can you link to the videos that work and dont work?

**Comment by StraightDroid** [comment]
Might  be the same problem like here behind ingress-nginx on kubernetes:

In 4.3.1 works and >=5 not

 error: Client log: HLS.js error: networkError - fatal: true - manifestLoadError

**Comment by StraightDroid** [comment]
.... OK. I Rewrote the attributes from the not loaded videos and now it works (private and back to public for example). There might some twikes to the the nginx, but this was not the fault.

**Comment by StraightDroid** [comment]
@vendornet please import a new file and you will see they are work.
