### ISSUE TITLE
Allow to wait for the background jobs to finish before publishing the video

### ISSUE THREAD

**Issue by gordonzola** [Chocobozzz/PeerTube#578]
* **PeerTube version or URL:** v1.0.0-beta.4
* **Browser name/version:** Firefox 60, Chromium 66
* **NodeJS version:** Any

* **What is the expected behaviour?** When I upload a video, the Peertube server runs a background transcript job. Meanwhile, the video cannot be played at all. The people that subscribed to this user won’t be able to play the video either, and will probably forget to play it later (especially when there’s no indication of a running job that prevents the play)
* **What do you see instead?** When posting a video, I would like to choose if I want to publish it right now, or if I want the background jobs to finish. That way, when the post reaches the Fediverse, the video is already playable by anybody.

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/2186386cca113506791583cb07d6ccacba7af4e0

Now there is a small alert below the video if it is being (or will be) transcoded. In addition, there is a new opt out checkbox in the upload/update video form with the label "wait transcoding" that allows to publish the video (ie is publicly available and federated) only when the video has been transcoded to at least 1 lower quality (or 0 if no resolutions are enabled).

**Comment by Chocobozzz** [comment]
No, we tried to define an "efficient" order: https://github.com/Chocobozzz/PeerTube/blob/develop/server/helpers/utils.ts#L89

Thinking about that, maybe we should proceed 360p first before 4080p :thinking:
