### ISSUE TITLE
Cannot start docker missing Secrets error

### ISSUE THREAD

**Issue by bananacy** [Chocobozzz/PeerTube#5780]
### Describe the problem

Excuse my ignorance! i am testing peertube on Docker windows. It won't start with this error. I am unable to access its shell so cannot run the openssl to update the config file. From v5 changelog: "There is a new secrets.peertube configuration. You must fill it before running PeerTube v5:"

`"stack": "Error: secrets.peertube is missing in config. Generate one using `openssl rand -hex 32`\n    at checkSecretsConfig (/app/dist/server/initializers/checker-after-init.js:88:15)\n    at checkConfig (/app/dist/server/initializers/checker-after-init.js:37:5)\n    at Object.<anonymous> (/app/dist/server.js:39:42)\n    at Module._compile (node:internal/modules/cjs/loader:1196:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)\n    at Module.load (node:internal/modules/cjs/loader:1074:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:909:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:22:47",`

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by JohnXLivingston** [comment]
You can just set a random 64 char string, using numbers and letters `a` to `f`.
Something like: `3afe10c18af4e228f1b42a9512697c60206b2a3828fa77287c8ddca35df1e541` (of course, don't use this one)

**Comment by Chocobozzz** [comment]
Hello,

For docker you must fill `PEERTUBE_SECRET` env variable. I updated the changelog for the sake of clarity.
