### ISSUE TITLE
Translations - ICU MessageFormat warnings

### ISSUE THREAD

**Issue by milotype** [Chocobozzz/PeerTube#5781]
### Describe the current behavior

There are many warnings/Failing checks about "ICU MessageFormat" in the translations on Weblate for many languages.

### Steps to reproduce

1. Go to https://weblate.framasoft.org/translate/peertube/angular/hr/?q=check:icu_message_format
2. There are 122 issues about "ICU MessageFormat"
3. Go to https://weblate.framasoft.org/translate/peertube/angular/de/?q=check:icu_message_format
4. There are 73 issues about "ICU MessageFormat"
5. Go to https://weblate.framasoft.org/translate/peertube/angular/cs/?q=check:icu_message_format
6. There are 7 issues about "ICU MessageFormat"

### Describe the expected behavior

The issue with "ICU MessageFormat" warnings should be resolved.
If that is not possible, should translators simply "Dismiss" these checks?

### Additional information

I'm not a programmer, so I don't have a solution for the issue :-(
I entered some strings at https://devpal.co/icu-message-editor/, but even there the strings don't work. Even the english strings have problems.

E.g.: `{<x id="PH" equiv-text="this.views"/> view(s)}`
- Weblate returns a warning **Syntax error: Expected , or } at position 4 but found "i"**
- ICU message editor returns a warning **Expected argNameOrNumber but "<" found.**

**Comment by Chocobozzz** [comment]
Thanks, I created an issue on weblate repository: https://github.com/WeblateOrg/weblate/issues/9206

**Comment by Chocobozzz** [comment]
I removed the checks on weblate until the issue is fixed.
