### ISSUE TITLE
"Move to external storage failed." even though the videos migrated fine and no failed jobs

### ISSUE THREAD

**Issue by bmanturner** [Chocobozzz/PeerTube#5787]
### Describe the problem

Using classic installation (v4.3.1) I recently moved all videos to minio. They moved over fine, and each video plays without issues, but each video says "Move to external storage failed, this video may not work properly." and therefore they aren't listed.

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by Chocobozzz** [comment]
Please fill the additional information, in particular a video URL and server error logs.

**Comment by bmanturner** [comment]
It was related to not being able to use "path-style" S3.
