### ISSUE TITLE
 Video embedding error in the night build

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5790]
### Describe the current behavior

Updated my server to the nightly build version 5.1.0-nightly-2023-05-11

After the update, an error appeared when embedding the video on the site. Users began to complain. This error occurs in all browsers.
There was no error in the previous version 2023-05-10. I have to downgrade the version of my server.

Here is a screenshot of the error
![1](https://github.com/Chocobozzz/PeerTube/assets/11453567/46820ede-842e-49da-ac1b-76616d0128d9)

* PeerTube instance:
  * Version:  5.1.0-nightly-2023-05-11
  * NodeJS version:  v16.20.0
  * Ffmpeg version: 4.3.6-0+deb11u1

* Link to browser console log if relevant:

> HLS.js error: otherError - fatal: false - internalException

**Comment by robwalch** [comment]
> Until there is a new release, I reverted to hls.js 1.3

Hi @Chocobozzz,

Does using the hls.light.mjs build in v1.4.4 resolve this issue for you?

**Comment by kontrollanten** [comment]
https://github.com/video-dev/hls.js/issues/5484 is released in [hls.js@1.4.4](https://github.com/video-dev/hls.js/releases/tag/v1.4.4) so it should be safe to upgrade hls.js now.

**Comment by Chocobozzz** [comment]
We now use the latest version of hls.js (1.5.x).
