### ISSUE TITLE
Home page for local videos

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5791]
### Describe the problem to be solved

I have already asked many times to add this function, I don't remember exactly, but in some version of Peertube it worked, then you removed this function. Very sorry.
[Request 1](https://github.com/Chocobozzz/PeerTube/issues/5619)
[Request 2](https://github.com/Chocobozzz/PeerTube/issues/5363)

In these queries, I wanted to get exactly this result from the main page (pages with local videos)... I have to stop subscribing to other instances that specifically increase the number of video views... In this case, other people's videos are displayed on my home page by default, this does not suit me.

I'll try to explain... I want users and guests to go to the main page of my instance and by default only local videos are displayed, but they should be displayed in the usual order, WITHOUT being divided into groups by time.
Now, in the administrator settings, I can make "Local videos" the start page, but in this case all videos are displayed broken down by time (day, week, month and old videos), I am not satisfied with this.

### Describe the solution you would like

There is a filter that sorts videos by different display options... I suggest adding an additional field in the admin settings, like this:
If the administrator has selected Start page is - "Local videos", then make an additional (new) field active, in which all the available sorting menu items will be available and the administrator can choose any option for sorting his local videos.

**Comment by Chocobozzz** [comment]
The *Custom value" with the appropriate page URL doesn't work?

**Comment by Alterak** [comment]
> The _Custom value_ with the appropriate page URL doesn't work?

I couldn't do it... I tried different options.

**Comment by Chocobozzz** [comment]
> I couldn't do it... I tried different options.

I'm sorry but I don't understand: it didn't work? What value have you put? What was the result?

**Comment by Alterak** [comment]
> I'm sorry but I don't understand: it didn't work? What value have you put? What was the result?

It's a pity that there were no fixes in the link in the pre-release
