### ISSUE TITLE
In RTL languages, the menu items are not adjusted to the right side.

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5792]
### Describe the current behavior

I am using Persian language which is an RTL language. But the following menus' items are not adjusted to the right side:

My account-> Moderation
My library-> Follows
Administration-> Overview
Administration-> Federation
Administration-> Moderation
Administration-> System
Channels-> Follows
Videos-> Follows
Playlists-> Follows
History-> Follows

### Steps to reproduce

1.
2.
3.

### Describe the expected behavior

For RTL languages, the menu items must be adjusted to the right side, not to the left side.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by paymanzafar1** [comment]
The current menu adjustment for Administration->Moderation menu is as below.
The menu items must be shifted to the right according to the red arrows.

![image](https://github.com/Chocobozzz/PeerTube/assets/91053236/810fa40c-e9bc-4654-992b-4c95c871f75a)

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1a5b7dff7fa1fc8b55ed12008f7720b46671e3d3
