### ISSUE TITLE
Converted Output changed: m3u8

### ISSUE THREAD

**Issue by aflamrip** [Chocobozzz/PeerTube#5793]
### Describe the problem to be solved

Is it possible to change the file format Converted Output: from m3u8 and mp4 to any other format because cloudflare imposes restrictions on video streaming

### Describe the solution you would like

It is possible to convert the files normally by transcoding to mp4 and m3u8 and after completion the file is renamed with the change of the file format

**Comment by Chocobozzz** [comment]
Hello,

No it's not possible. If Cloudflare prohibits video streaming you can exclude the video endpoints to be served from Cloudflare.
