### ISSUE TITLE
In RTL languages, table header items are not adjusted to the right side

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5795]
### Describe the current behavior

I am using Persian language which is a RTL language. In all tables, the header items are still adjusted to the left side.
Here are some examples:

Overview-> Users
Overview-> Videos
Overview-> Comments
Federation-> Followings
Federation-> Followers
Federation-> Video Redundancies
Moderation-> Registrations
Moderation-> Reports
Moderation-> Video Blocks
.
.
.
Here is the header items adjustments in Moderation-> Registrations table for Persian site:

![image](https://github.com/Chocobozzz/PeerTube/assets/91053236/443df8a7-59b9-425e-8258-c29085326ab7)

### Steps to reproduce

1.
2.
3.

### Describe the expected behavior

In RTL languages, all the table header items must be adjusted to the right side.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! Fixed by https://github.com/Chocobozzz/PeerTube/commit/42379e4eef2987472790656d6b8ab6c3a57825fa
