### ISSUE TITLE
Separate audio stream/video stream in HLS

### ISSUE THREAD

**Issue by stevespaw** [Chocobozzz/PeerTube#5797]
### Describe the problem to be solved

Issue: to enable Peertube to connect to OTT platforms with a common M3U8 Playlist
Peertube provides muxed Audio in the video container (eg. mp4)
Roku cannot detect the audio in these files.
(Roku CAN play MUXED audio in TS bucket containers)
Testing / confirmation:
This is an issue with ROKU - no audio on the M3U8 Streams with Muxed audio. Here is the Roku tester. [http://devtools.web.roku.com/stream_tester/html/](http://devtools.web.roku.com/stream_tester/html/)
It works best by installing the app locally.
Add the Roku test app to the Roku Stick.
[https://my.roku.com/add/ZJMQ6D5](https://my.roku.com/add/ZJMQ6D5)
Add the device manually by IP address (I had to do this).
Add a Peertube M3U8 - it will say no audio track. Video playback is fine. 
https://cdn3.shadow-technologies.com/streaming-playlists/hls/845abbce-415e-4d45-996a-abc74c84e79b/3c138194-3f93-4600-94ab-8b85ff1b8aa9-master.m3u8

Any other M3U8's, and the samples work fine. 
Such as https://r0n5.c13.e2-3.dev/demo-video/hls-3/master.m3u8
This is a Fragmented MP4 HLS with SEPARATE Audio.

### Describe the solution you would like

Fragmented Mp4 Container bucket/single file playlist **_Separate Audio Track_**
Roku DOES recognize the Audio, and all players play this perfectly.
`ffmpeg -i test4k.mkv\
-filter_complex \
"[0:v]split=4[v1][v2][v3][v4]; \
[v1]copy[v1out]; [v2]scale=w=1920:h=1080[v2out]; [v3]scale=w=1280:h=720[v3out]; [v4]scale=w=720:h=480[v4out]" \
-map [v1out] -c:v:0 libx264 -x264-params "nal-hrd=cbr:force-cfr=1" -b:v:0 9M -maxrate:v:0 9M -minrate:v:0 9M -bufsize:v:0 18M -preset slow -g 48 -sc_threshold 0 -keyint_min 48 \
-map [v2out] -c:v:1 libx264 -x264-params "nal-hrd=cbr:force-cfr=1" -b:v:1 5M -maxrate:v:1 5M -minrate:v:1 5M -bufsize:v:1 10M -preset slow -g 48 -sc_threshold 0 -keyint_min 48 \
-map [v2out] -c:v:2 libx264 -x264-params "nal-hrd=cbr:force-cfr=1" -b:v:2 3M -maxrate:v:2 3M -minrate:v:2 3M -bufsize:v:2 3M -preset slow -g 48 -sc_threshold 0 -keyint_min 48 \
-map [v3out] -c:v:3 libx264 -x264-params "nal-hrd=cbr:force-cfr=1" -b:v:3 1M -maxrate:v:3 1M -minrate:v:3 1M -bufsize:v:3 1M -preset slow -g 48 -sc_threshold 0 -keyint_min 48 \
-map a:0 -c:a:0 aac -b:a:0 96k -ac 2 \
-map a:0 -c:a:1 aac -b:a:1 96k -ac 2 \
-map a:0 -c:a:2 aac -b:a:2 48k -ac 2 \
-map a:0 -c:a:3 aac -b:a:3 48k -ac 2 \
-f fmp4 \
-hls_time 6 \
-hls_playlist_type vod \
-hls_flags single_file \
-hls_segment_type fmp4 \
-hls_segment_filename stream_%v/single.m4s \
-master_pl_name master.m3u8 \
-var_stream_map "a:0,agroup:aud,default:yes v:0,agroup:aud a:1,agroup:aud,default:yes v:1,agroup:aud a:2,agroup:aud,default:yes v:2,agroup:aud a:3,agroup:aud,default:yes v:3,agroup:aud" stream_%v/stream.m3u8`

Windows command line:

Working ROKU 4K fMp4-SINGLE FILE 4K - Separate audio -
Single file 4K ready fMp4 Separate Audio 264

Sample result:   https://r0n5.c13.e2-3.dev/demo-video/hls-3/master.m3u8
`ffmpeg -i test4k.mkv -filter_complex "[0:v]split=4[v1][v2][v3][v4]; [v1]copy[v1out]; [v2]scale=w=1920:h=1080[v2out]; [v3]scale=w=1280:h=720[v3out]; [v4]scale=w=720:h=480[v4out]" -map [v1out] -c:v:0 libx264 -x264-params "nal-hrd=cbr:force-cfr=1" -b:v:0 9M -maxrate:v:0 9M -minrate:v:0 9M -bufsize:v:0 18M -preset slow -g 48 -sc_threshold 0 -keyint_min 48 -map [v2out] -c:v:1 libx264 -x264-params "nal-hrd=cbr:force-cfr=1" -b:v:1 5M -maxrate:v:1 5M -minrate:v:1 5M -bufsize:v:1 10M -preset slow -g 48 -sc_threshold 0 -keyint_min 48 -map [v3out] -c:v:2 libx264 -x264-params "nal-hrd=cbr:force-cfr=1" -b:v:2 3M -maxrate:v:2 3M -minrate:v:2 3M -bufsize:v:2 3M -preset slow -g 48 -sc_threshold 0 -keyint_min 48 -map [v4out] -c:v:3 libx264 -x264-params "nal-hrd=cbr:force-cfr=1" -b:v:3 1M -maxrate:v:3 1M -minrate:v:3 1M -bufsize:v:3 1M -preset slow -g 48 -sc_threshold 0 -keyint_min 48 -map a:0 -c:a:0 aac -b:a:0 96k -ac 2 -map a:0 -c:a:1 aac -b:a:1 96k -ac 2 -map a:0 -c:a:2 aac -b:a:2 48k -ac 2 -map a:0 -c:a:3 aac -b:a:3 48k -ac 2 -f hls -hls_time 6 -hls_playlist_type vod -hls_flags single_file -hls_segment_type fmp4 -hls_segment_filename "stream_%v/single.m4s" -master_pl_name master.m3u8 -var_stream_map "a:0,agroup:aud,default:yes v:0,agroup:aud a:1,agroup:aud,default:yes v:1,agroup:aud a:2,agroup:aud,default:yes v:2,agroup:aud a:3,agroup:aud,default:yes v:3,agroup:aud" stream_%v/stream.m3u8
`

<img width="357" alt="Screenshot 2023-05-18 132909" src="https://github.com/Chocobozzz/PeerTube/assets/11045430/8fa0b5c6-97d1-4738-b183-86c93d448abd">

**Comment by stevespaw** [comment]
`ffmpeg -i test4k.mkv\
-filter_complex \
"[0:v]split=4[v1][v2][v3][v4]; \
[v1]copy[v1out]; [v2]scale=w=1920:h=1080[v2out]; [v3]scale=w=1280:h=720[v3out]; [v4]scale=w=720:h=480[v4out]" \
-map [v1out] -c:v:0 libx264 -x264-params "nal-hrd=cbr:force-cfr=1" -b:v:0 9M -maxrate:v:0 9M -minrate:v:0 9M -bufsize:v:0 18M -preset slow -g 48 -sc_threshold 0 -keyint_min 48 \
-map [v2out] -c:v:1 libx264 -x264-params "nal-hrd=cbr:force-cfr=1" -b:v:1 5M -maxrate:v:1 5M -minrate:v:1 5M -bufsize:v:1 10M -preset slow -g 48 -sc_threshold 0 -keyint_min 48 \
-map [v2out] -c:v:2 libx264 -x264-params "nal-hrd=cbr:force-cfr=1" -b:v:2 3M -maxrate:v:2 3M -minrate:v:2 3M -bufsize:v:2 3M -preset slow -g 48 -sc_threshold 0 -keyint_min 48 \
-map [v3out] -c:v:3 libx264 -x264-params "nal-hrd=cbr:force-cfr=1" -b:v:3 1M -maxrate:v:3 1M -minrate:v:3 1M -bufsize:v:3 1M -preset slow -g 48 -sc_threshold 0 -keyint_min 48 \
-map a:0 -c:a:0 aac -b:a:0 96k -ac 2 \
-map a:0 -c:a:1 aac -b:a:1 96k -ac 2 \
-map a:0 -c:a:2 aac -b:a:2 48k -ac 2 \
-map a:0 -c:a:3 aac -b:a:3 48k -ac 2 \
-f fmp4 \
-hls_time 6 \
-hls_playlist_type vod \

-hls_flags independent_segments \
	#Swap to this for Single file
#-hls_flags single_file \

-hls_segment_type fmp4 \

-hls_segment_filename stream_%v/bucket%02d.m4s \
	#Swap to this for Single file
#-hls_segment_filename stream_%v/single.m4s \

-master_pl_name master.m3u8 \
-var_stream_map "v:0,a:0 v:1,a:1 v:2,a:2 v:3,a:3" stream_%v/stream.m3u8

	#Swap to this for separate audio
#-var_stream_map "a:0,agroup:aud,default:yes v:0,agroup:aud a:1,agroup:aud,default:yes v:1,agroup:aud a:2,agroup:aud,default:yes v:2,agroup:aud a:3,agroup:aud,default:yes v:3,agroup:aud" stream_%v/stream.m3u8`

**Comment by stevespaw** [comment]
`ffmpeg -i test4k.mkv\
-filter_complex \
"[0:v]split=4[v1][v2][v3][v4]; \
[v1]copy[v1out]; [v2]scale=w=1920:h=1080[v2out]; [v3]scale=w=1280:h=720[v3out]; [v4]scale=w=720:h=480[v4out]" \
-map [v1out] -c:v:0 libx264 -x264-params "nal-hrd=cbr:force-cfr=1" -b:v:0 9M -maxrate:v:0 9M -minrate:v:0 9M -bufsize:v:0 18M -preset slow -g 48 -sc_threshold 0 -keyint_min 48 \
-map [v2out] -c:v:1 libx264 -x264-params "nal-hrd=cbr:force-cfr=1" -b:v:1 5M -maxrate:v:1 5M -minrate:v:1 5M -bufsize:v:1 10M -preset slow -g 48 -sc_threshold 0 -keyint_min 48 \
-map [v2out] -c:v:2 libx264 -x264-params "nal-hrd=cbr:force-cfr=1" -b:v:2 3M -maxrate:v:2 3M -minrate:v:2 3M -bufsize:v:2 3M -preset slow -g 48 -sc_threshold 0 -keyint_min 48 \
-map [v3out] -c:v:3 libx264 -x264-params "nal-hrd=cbr:force-cfr=1" -b:v:3 1M -maxrate:v:3 1M -minrate:v:3 1M -bufsize:v:3 1M -preset slow -g 48 -sc_threshold 0 -keyint_min 48 \
-map a:0 -c:a:0 aac -b:a:0 96k -ac 2 \
-map a:0 -c:a:1 aac -b:a:1 96k -ac 2 \
-map a:0 -c:a:2 aac -b:a:2 48k -ac 2 \
-map a:0 -c:a:3 aac -b:a:3 48k -ac 2 \
-f fmp4 \
-hls_time 6 \
-hls_playlist_type vod \

-hls_flags independent_segments \
	#Swap to this for Single file
#-hls_flags single_file \

-hls_segment_type fmp4 \

-hls_segment_filename stream_%v/bucket%02d.m4s \
	#Swap to this for Single file
#-hls_segment_filename stream_%v/single.m4s \

-master_pl_name master.m3u8 \
-var_stream_map "v:0,a:0 v:1,a:1 v:2,a:2 v:3,a:3" stream_%v/stream.m3u8

	#Swap to this for separate audio
#-var_stream_map "a:0,agroup:aud,default:yes v:0,agroup:aud a:1,agroup:aud,default:yes v:1,agroup:aud a:2,agroup:aud,default:yes v:2,agroup:aud a:3,agroup:aud,default:yes v:3,agroup:aud" stream_%v/stream.m3u8`

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/6521
