### ISSUE TITLE
Allow user to change live audio/video background

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5798]
### Describe the problem to be solved

for now it's impossible for the user to have its own live background (audio and video)

### Describe the solution you would like

add an option that allow the user to upload it's own live background, but not only jpeg but animated gif or even an mp4.

**Comment by Chocobozzz** [comment]
Hello,

Unfortunately it's out of the scope of the project: you can inject the background/stream you want using OBS in your live stream.
