### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5799]
### Steps to reproduce

1. Go to Administration-> Overview ->Users
2. Click Create user button
3. Click on ? mark (Get help) for password
4. Along with the help, you see an error message 

### Describe the expected behavior

In this scenario, you must see the help message, not any error message.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/f3bc1b541619673f14db7de220b9c520a4f35ca8
