### ISSUE TITLE
The modification of constants.js not work

### ISSUE THREAD

**Issue by imtube** [Chocobozzz/PeerTube#58]
Hello,
It seems doesn't work when I modify the file constants.js, for example:
I have change tag's length to:
`TAG: { min: 0, max: 20 }`
but when I input tag, it still tell me:
`A tag should be between 2 and 10 alphanumeric characters long.`

**Comment by Chocobozzz** [comment]
`constants.js` file should not be modified. Moreover there is another verification on client side.

Tags length are limited because they are sent to other pods.
