### ISSUE TITLE
Add a like/dislike system

### ISSUE THREAD

**Issue by jfoucry** [Chocobozzz/PeerTube#580]
It would be great if viewer could like or dislike videos. Yes i know, like YouTube does.

**Comment by tcitworld** [comment]
There's one if you login on the instance.
![screenshot_20180521-131605__01](https://user-images.githubusercontent.com/2197836/40305096-5d073db4-5cf9-11e8-9917-11dfe99776da.jpg)

**Comment by Chocobozzz** [comment]
Like @tcitworld (:kissing_heart:) said :)
