### ISSUE TITLE
Federate/integrate with Owncast?

### ISSUE THREAD

**Issue by WGandy** [Chocobozzz/PeerTube#5800]
### Describe the desired information/correction

The author of Owncast has suggested that if some one could publish the Peertube fediverse particulars at their fediverse documentation system, there might be room to allow the two apps to connect.  

https://github.com/gabek/fedidocs

I would like to see some more live stream options (metrics for the stream and the ability to record live streams at a persistent link) and it seems to me that if Owncast could work in kahoots with Peertube, there might be some magic that could happen. 

For instance, what if Owncast was used to stream a live video and Peertube could "capture" the live streams (all the transcodes perhaps) and immediately make them available for replay?

**Comment by Chocobozzz** [comment]
Hi,

PeerTube already has this kind of documentation: https://docs.joinpeertube.org/api/activitypub
