### ISSUE TITLE
Video not launch

### ISSUE THREAD

**Issue by Iwios** [Chocobozzz/PeerTube#5801]
### Describe the current behavior

After uploading video and transcoding OK, video not launched. I've a black screen with a loading picto.

I have a first server for reverse proxy and second with peertube instance

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance: 
  * URL: https://videos.asso-manager.fr
  * Version: 5.1.0
  * NodeJS version: v16.20.0
  * Ffmpeg version: 4.3.6-0

* Browser name, version and platforms on which you could reproduce the bug: Firefox 
* Link to browser console log if relevant: 113.0.1
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Please paste [this section](https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L6) of your `production.yaml` configuration file

**Comment by Iwios** [comment]
listen:
  hostname: '127.0.0.1'
  port: 9000

# Correspond to your reverse proxy server_name/listen configuration (i.e., your public PeerTube instance URL)
webserver:
  https: http
  hostname: 'videos.asso-manager.fr'
  port: 80

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L7 should be `false`, not `http`

Then you'll have to run https://docs.joinpeertube.org/maintain/tools#update-host-js

**Comment by Iwios** [comment]
After change in production.yaml, video playing doesn't work
