### ISSUE TITLE
Cannot change nickname without popping the live chat window out

### ISSUE THREAD

**Issue by Justinzobel** [Chocobozzz/PeerTube#5802]
### Describe the current behavior

You need to pop the live chat window into it's own window in order to change nickname

### Steps to reproduce

1. Try to change nickname without popping chat out
2.
3.

### Describe the expected behavior

An option to change the user nickname without popping out the chat into it's own tab/window.

### Additional information

* PeerTube instance:
  * URL: https://tube.kockatoo.org/
  * Version: 5.1.0

**Comment by Chocobozzz** [comment]
Hi,

Please open the issue on the livechat repository instead: https://github.com/JohnXLivingston/peertube-plugin-livechat
