### ISSUE TITLE
"Request an account" page doesn't work in Italian

### ISSUE THREAD

**Issue by alejandrocobo** [Chocobozzz/PeerTube#5803]
### Describe the current behavior

Clicking on the "Request an account" button shows a blank page when the interface is in Italian.

### Steps to reproduce

1. Log out your current session.
2. Switch the interface language to Italian
3. Click on "Richiedi un account" ("Request an account" in Italian).

### Additional information

* PeerTube instance:
  * URL: https://tubedu.org and https://video.hardlimit.com
  * Version: 5.1.0

* Browser name, version and platforms on which you could reproduce the bug: Firefox 102.11.0esr and Chromium 111.0.5563.64

Thanks.

**Comment by Chocobozzz** [comment]
Thanks, I fixed the strings on weblate: https://github.com/Chocobozzz/PeerTube/commit/ce722c0f0fe081ce3308b857158810def93f161e
