### ISSUE TITLE
Text is not translatable

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5805]
### Describe the current behavior

In Administration-> Configuration -> VOD Transcoding and in the "transcoding profile" dropdown, the "default" word is not translatable.

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/b99ee1b150257e0d54bde4b928dd9dc76b97ef7b
