### ISSUE TITLE
Dropdown menu items are not translatable

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5806]
### Describe the current behavior

In Administration-> Configuration -> Basic menu, and in the "Broadcast message level" dropdown, the 3 items are not translatable.

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/f9fc41cb881ef7049c8f6ae55d89400abcb13f63
