### ISSUE TITLE
Subtitle uploaded but not shown when playing

### ISSUE THREAD

**Issue by fweng322** [Chocobozzz/PeerTube#5810]
### Describe the current behavior

https://peertube.slat.org/w/6sFgc75F6wPSA2CTAgYuo3

The user upload the video and two subtitles: English and Traditional Chinese.  However when playing this video, we can select CC language but no any subtitle shown.

### Steps to reproduce

1.
2.
3.

### Describe the expected behavior

It should show the subtitle when we select the CC language from the settings

### Additional information

* PeerTube instance:
  * URL: https://peertube.slat.org/
  * Version: 5.0.1
  * NodeJS version: 16.20
  * Ffmpeg version: 4.3.6

**Comment by Chocobozzz** [comment]
Hello,

You subtitle file is invalid: https://peertube.slat.org/lazy-static/video-captions/094ccf98-fd6f-4892-b581-9e7b3b2a0880-en.vtt

It should start with `WEBVTT`

See https://w3c.github.io/webvtt.js/parser.html

**Comment by fweng322** [comment]
> Hello,
> 
> You subtitle file is invalid: https://peertube.slat.org/lazy-static/video-captions/094ccf98-fd6f-4892-b581-9e7b3b2a0880-en.vtt
> 
> It should start with `WEBVTT`
> 
> See https://w3c.github.io/webvtt.js/parser.html

@Chocobozzz 

Oh, thanks.  The subtitle file is in srt format, which is commonly used.  Sorry I didn't check about the subtitle format in peertube.

Do you think it's reasonable to have srt format supported as well?  If so I can start an enhancement issue.

**Comment by Chocobozzz** [comment]
Can you paste the subtitle you uploaded? Peertube supports srt, and should have converted it to a valid WEBVTT subtitle
