### ISSUE TITLE
Your video file was too large (max. size: 8G)

### ISSUE THREAD

**Issue by megabitsenmzq** [Chocobozzz/PeerTube#5814]
### Describe the current behavior

Upload video results in an error "Your video file was too large."
I'm using Cloudflare. And I have the workaround set in my settings.
I'm using Caddy2 instead of Nginx.

```
client:
  videos:
    upload:
      maxChunkSize: '90MB'
```

### Steps to reproduce

1. upload an 800MB video file.

### Describe the expected behavior

It should be uploaded.

### Additional information

* PeerTube instance:
  * Version: 5.1.0
  * NodeJS version: 16.20.0

* Browser name, version and platforms on which you could reproduce the bug:

Both Safari and Firefox.

* Link to browser console log if relevant:

Firefox Says:
Your video file was too large (max. size: 8G)

Safari says:
Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)

**Comment by Chocobozzz** [comment]
Hello,

Please use the forum for PeerTube related questions or sysadmin support: https://framacolibri.org/c/peertube
