### ISSUE TITLE
Non-scrollable long list of channels

### ISSUE THREAD

**Issue by EricGuic** [Chocobozzz/PeerTube#5815]
### Describe the current behavior

In the my-library/videos page, I can sort the videos displayed by channel.
But I have a long list of channels and I can't scroll inside it (capture below).
![Probleme ascenceur chaines nombreuses](https://github.com/Chocobozzz/PeerTube/assets/81166671/35a5e3d2-85d0-443c-b1b7-df8d2f9c83cd)

### Steps to reproduce

1.Create a large number of channels
2.Go to my-library/videos page
3.Click on the little triangle of the channel filter to open the channels list
4.Try to scroll to the last entries down below : the list doesn't react as expected.

### Describe the expected behavior

A scrolling list as everywhere else ;-)

### Additional information

* PeerTube instance: Réseau Canopé
  * URL: tube.reseau-canope.fr
  * Version: 5.1
  * NodeJS version: ?
  * Ffmpeg version: ?

* Browser name, version and platforms on which you could reproduce the bug: Chrome version 113.0.5672.127 (Build officiel) (64 bits)
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/ae51278920aab47f1a04d66cb6fc06293fbb03c6

**Comment by Chocobozzz** [comment]
Sure: https://github.com/Chocobozzz/PeerTube/commit/7d758898dc907b8643bab6ae2e70c3ca2a021fac
