### ISSUE TITLE
Not always the same info on the Edit video tabs

### ISSUE THREAD

**Issue by EricGuic** [Chocobozzz/PeerTube#5816]
### Describe the current behavior

I've noticed differences between the infos and fields displayed in the Edit video page.
For example, for 2 videos uploaded the same way (local upload from my computer), I have sometimes a "Publish after transcoding" check box, and sometimes not : 
![no publish after transcoding](https://github.com/Chocobozzz/PeerTube/assets/81166671/c65592a5-2fa2-48ac-b7a2-6f26b1ca10df)

![publish after transcoding](https://github.com/Chocobozzz/PeerTube/assets/81166671/0563b8f0-b944-4695-9aba-98608d56e5da)

In the same order, I have sometimes the name of the originally uploaded files, and sometimes nothing : 
![name of the file uploaded](https://github.com/Chocobozzz/PeerTube/assets/81166671/a6574772-4675-461c-a6ba-b53a4396d64d)

![no name of the file uploaded](https://github.com/Chocobozzz/PeerTube/assets/81166671/ee4aaf41-bcea-49db-9bbd-04f59d4f53b6)

Between this 2 videos, I can see only two differences in the process :
one have been uploaded before the v5.1 upgrade, and the other after.
And maybe (I can't be 100% sure) one have been migrated to S3 storage, when the other have been directly uploaded after the object storage migration.

### Steps to reproduce

Sorry, no idea on how reproduce it.

### Describe the expected behavior

Having consistent infos for every video (and by the way, when I replace a video through CLI, the "File name uploaded" still display the name of the originally uploaded one, not the name of the last version.)

### Additional information

* PeerTube instance: Réseau Canopé
  * URL: tube.reseau-canope.fr
  * Version: 5.1
  * NodeJS version: ?
  * Ffmpeg version: ?

* Browser name, version and platforms on which you could reproduce the bug: Chrome Version 113.0.5672.127 (Build officiel) (64 bits)
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
The `Publish after transcoding` is hidden if the video has already been transcoded.
The video source field is displayed when you update a video that was uploaded (not imported etc)

**Comment by EricGuic** [comment]
Hi Chocobozzz,
For the `video source` field, the info could be usefull for any uploaded video, even without any replacement after the first uplaod.

For the `Publish after transcoding` field, maybe it's a clue for another issue :
i've noticed today that those videos replaced by CLI can't be played inside Peertube. I'm quite sure that juste after the replacement, I've tested the video and it was playing well. But a few days/weeks later, I can't play it on Peertube.

Also, those  videos replaced by CLI have a different set of transcoded files, with 1 webtorrent in addition to the HLS files (see capture below) : 

![image](https://github.com/Chocobozzz/PeerTube/assets/81166671/137b8a5a-cbc8-4235-8938-e0b01adf4878)

**The first video (top) was replaced by CLI.**
You can reach it here : https://tube.reseau-canope.fr/w/4pKry4xa2D9PCycJhdSxWE
The `Publish after transcoding` field is visible for it. (does it mean that something goes wrong with transcoding process ?).
As said earlier, I can't play it on Peertube.
But the direct link plays as expected :

- the 1080 webtorrent : https://s3.reseau-canope.fr/peertube/webtorrent/c44303e5-cb84-4873-8531-55c536b0cdab-1080.mp4

- the 1080 HLS : https://s3.reseau-canope.fr/peertube/streaming-playlistshls/1b9c4b3c-55fd-4f87-979b-ccf30c5ce44e/b9c74885-d333-4f45-9692-acadd0a46a58-1080-fragmented.mp4


The second video was uploaded (and no replacement after).
Only HLS files are listed (as my configuration is set), and the video plays as expected.
Here the `Publish after transcoding` field is hidden.
You can reach it here : https://tube.reseau-canope.fr/w/fw8TQvdRW7i8tSY2cMpHpW
And the direct link : 

- 1080 HLS : https://s3.reseau-canope.fr/peertube/streaming-playlistshls/75951e78-4c0c-47dc-9d69-f837d9ca99b8/f7ce827f-a91c-41bf-bb3c-246c514e4c02-1080-fragmented.mp4


If you need, I can copy/paste the command I send through CLI to check ?

Thanks, Eric.

**Comment by EricGuic** [comment]
If it can help to investigate the issue, here is another video, uploaded from local computer, never replaced, and for which I've manually execute webtorrent transcoding trhough the web UI of Peertube : 
![image](https://github.com/Chocobozzz/PeerTube/assets/81166671/3caf31d7-0998-463e-b387-e192a1b319e0)

Everything works as expected here.

You can reach it here : https://tube.reseau-canope.fr/w/2FbgVYaPFfrnfXFTezj4Jj

**Comment by Chocobozzz** [comment]
> For the video source field, the info could be usefull for any uploaded video, even without any replacement after the first upload. A feature request ? smiley

Yes please create a dedicated issue

The wait transcoding checkbox display bug should be fixed by https://github.com/Chocobozzz/PeerTube/commit/a2406b86a7597948a45f639392d0d52d3be047c7
