### ISSUE TITLE
ApiCache groups are lost after restart

### ISSUE THREAD

**Issue by agates** [Chocobozzz/PeerTube#5818]
### Describe the current behavior

ApiCache groups, added in 5.2 as part of PR https://github.com/Chocobozzz/PeerTube/pull/5487, are lost during server restarts.  This prevents cache groups from being cleared within the relevant cache TTL after the server is restarted.

It's not a huge issue, but I thought it was worth documenting regardless.  Once the cached entry expires, the issue is resolved.

### Steps to reproduce

1. Load a channel's Podcast RSS feed over http (curl, command line, etc) to get it loaded into cache
2. Restart the PeerTube server
3. Make an update to the given channel or a video included in the given feed, to trigger the internal event emitter and `podcastApiCache.clearGroupSafe`
4. Check the Podcast RSS feed again, seeing the previously cached response from step 1

### Describe the expected behavior

The cache should be cleared after channel/video updates.

### Additional information

* PeerTube instance:
  * URL: local dev environment
  * Version: v5.2.0-rc.1
  * NodeJS version: v18.16.0

**Comment by Chocobozzz** [comment]
Thanks, I don't think we need to save cached routes between server restarts. Keys are now unique per restart with https://github.com/Chocobozzz/PeerTube/commit/ed14d1ebd7c8d9428ac58b3a6280e3df6686aec1

**Comment by agates** [comment]
> Thanks, I don't think we need to save cached routes between server restarts. Keys are now unique per restart with [ed14d1e](https://github.com/Chocobozzz/PeerTube/commit/ed14d1ebd7c8d9428ac58b3a6280e3df6686aec1)

I like this solution, should help with any cache issues in the future.
