### ISSUE TITLE
LDAP Plugin not working as expected for Peertube

### ISSUE THREAD

**Issue by ravikumarsinga** [Chocobozzz/PeerTube#5819]
### Describe the problem

Hi,

I am facing an issue with Peertube to integrate with Microsoft Active Directory for authentication, below are the details.
 
I have Installed 5.1.0 on private network and installed ldap authentication plugin "auth-ldap version 0.0.12" from web interface "Plugins/Themes" option and using Nginx as proxy for Peertube.

There are total of 15 options available to configure ldap authentication to the peertube and i have configured them as below

**Auth weight** - 100
**URL** - ldap://my.company.local:389 (with 389 and without 389 also tested)
**Insecure TLS** - Check box selected
**Path to LDAP Server Certificate Chain of Trust** - left blank (not sure if this is mandatory)
**Bind DN** - cn=rwaccess-peertube, ou=peertube, dc=my, dc=company, dc=local
**Bind password** - xxxxxxxx (service account password mentioned in above step)
**Search base** - ou=peertube, dc=my, dc=company, dc=local (this is where all users accounts residing)
**Search filter** - (|(mail={{mail}})(sAMAccountName={{username}}))
**Mail property** - mail (its a default value)
**Mail property index** - 0 (its a default value )
**Username property** - sAMAccountName (default is uid)
**Group base** - ou=peertube, dc=my, dc=company, dc=local
**Group filter** - (member={{dn}}) (default value)
**Administrator group DN** - cn=#Admin, ou=peertube, dc=my, dc=company, dc=local (Universal Security Group)
**Moderator group DN** - cn=#Moderator, ou=peertube, dc=my, dc=company, dc=local (Universal Security Group)
**User group DN** - left blank as i wanted everyone else to be logged in as user axcept above 2 group users.

When a user login from the Peertube login page(note - user has hyphen in the user name and i believe this is resolved in 5.1.0 version) the error is` incorrect user or password` and log show below.

```
Error Logs

Jun  4 23:51:35 peertube-site peertube[5778]: [peertube-site-local:80] 2023-06-04 23:51:35.778 #033[32minfo#033[39m: 10.99.104.126 - - [04/Jun/2023:18:21:35 +0000] "GET /client/en-US/common.74416e55e7d6c2da.js HTTP/1.1" 200 16981 "http://peertube-site-local/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
Jun  4 23:51:35 peertube-site peertube[5778]: [peertube-site-local:80] 2023-06-04 23:51:35.782 #033[32minfo#033[39m: 10.99.104.126 - - [04/Jun/2023:18:21:35 +0000] "GET /client/en-US/9325.582c013f69d4b2c5.js HTTP/1.1" 200 536154 "http://peertube-site-local/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
Jun  4 23:51:41 peertube-site peertube[5778]: [peertube-site-local:80 peertube-plugin-auth-ldap] 2023-06-04 23:51:41.825 #033[33mwarn#033[39m: Cannot login username-id in LDAP plugin. {
Jun  4 23:51:41 peertube-site peertube[5778]:  "err": {
Jun  4 23:51:41 peertube-site peertube[5778]:    "stack": "InvalidCredentialsError: 80090308: LdapErr: DSID-0C090436, comment: AcceptSecurityContext error, data 52e, v23f0\u0000\n    at messageCallback (/var/www/peertube/storage/plugins/node_modules/ldapjs/lib/client/client.js:1220:45)\n    at Parser.onMessage (/var/www/peertube/storage/plugins/node_modules/ldapjs/lib/client/client.js:888:14)\n    at Parser.emit (node:events:513:28)\n    at Parser.write (/var/www/peertube/storage/plugins/node_modules/ldapjs/lib/messages/parser.js:107:8)\n    at Socket.onData (/var/www/peertube/storage/plugins/node_modules/ldapjs/lib/client/client.js:875:22)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
Jun  4 23:51:41 peertube-site peertube[5778]:    "lde_message": "80090308: LdapErr: DSID-0C090436, comment: AcceptSecurityContext error, data 52e, v23f0\u0000",
Jun  4 23:51:41 peertube-site peertube[5778]:    "lde_dn": null
Jun  4 23:51:41 peertube-site peertube[5778]:  }
Jun  4 23:51:41 peertube-site peertube[5778]: }
Jun  4 23:51:41 peertube-site peertube[5778]: [peertube-site-local:80] 2023-06-04 23:51:41.856 #033[33mwarn#033[39m: Login error {
Jun  4 23:51:41 peertube-site peertube[5778]:  "err": {
Jun  4 23:51:41 peertube-site peertube[5778]:    "statusCode": 400,
Jun  4 23:51:41 peertube-site peertube[5778]:    "status": 400,
Jun  4 23:51:41 peertube-site peertube[5778]:    "code": 400,
Jun  4 23:51:41 peertube-site peertube[5778]:    "message": "Invalid grant: user credentials are invalid",
Jun  4 23:51:41 peertube-site peertube[5778]:    "name": "invalid_grant",
Jun  4 23:51:41 peertube-site peertube[5778]:    "stack": "invalid_grant: Invalid grant: user credentials are invalid\n    at new InvalidGrantError (/var/www/peertube/versions/peertube-v5.1.0/node_modules/@node-oauth/oauth2-server/lib/errors/invalid-grant-error.js:26:14)\n    at /var/www/peertube/versions/peertube-v5.1.0/dist/server/lib/auth/oauth.js:114:19\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v5.1.0/node_modules/tslib/tslib.js:164:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
Jun  4 23:51:41 peertube-site peertube[5778]:  }
Jun  4 23:51:41 peertube-site peertube[5778]: }
Jun  4 23:51:41 peertube-site peertube[5778]: [peertube-site-local:80] 2023-06-04 23:51:41.857 #033[32minfo#033[39m: 10.99.104.126 - - [04/Jun/2023:18:21:41 +0000] "POST /api/v1/users/token HTTP/1.1" 400 325 "http://peertube-site-local/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
Jun  4 23:51:41 peertube-site peertube[5778]: [peertube-site-local:80] 2023-06-04 23:51:41.867 #033[31merror#033[39m: Client log: Backend returned code 400, errorMessage is: Invalid grant: user credentials are invalid {
Jun  4 23:51:41 peertube-site peertube[5778]:  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
Jun  4 23:51:41 peertube-site peertube[5778]:  "url": "http://peertube-site-local/login"
Jun  4 23:51:41 peertube-site peertube[5778]: }
Jun  4 23:51:41 peertube-site peertube[5778]: [peertube-site-local:80] 2023-06-04 23:51:41.868 #033[32minfo#033[39m: 10.99.104.126 - - [04/Jun/2023:18:21:41 +0000] "POST /api/v1/server/logs/client HTTP/1.1" 204 - "http://peertube-site-local/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
```

Please let me know what is missing in this over all and why the LDAP authentication is not working and throwing above error.

### Additional information

* PeerTube instance URL: http://peertube-site-local/
* PeerTube version: 5.1.0 
* NodeJS version:  16.19.1
* Ffmpeg version:  4.2.9
* Redis version: 5.0.3
* PostgreSQL version: 10.23
* auth-ldap plugin - 0.0.12 (https://framagit.org/framasoft/peertube/official-plugins/-/tree/master/peertube-plugin-auth-ldap)
OS - Rocky Linux 8.4 (Domain Joined? - No)

**Comment by Chocobozzz** [comment]
From https://community.arubanetworks.com/discussion/ldap-for-operators-login it seems the error is that your credentials are invalid

But please use https://framagit.org/framasoft/peertube/official-plugins for ldap plugin issues

**Comment by ravikumarsinga** [comment]
The page  https://framagit.org/framasoft/peertube/official-plugins doesn't open up!

![image](https://github.com/Chocobozzz/PeerTube/assets/135543766/25444785-6782-4319-9af5-18fabce97b13)

**Comment by ravikumarsinga** [comment]
> From https://community.arubanetworks.com/discussion/ldap-for-operators-login it seems the error is that your credentials are invalid

This is not the case at all at least with my credentials but i have some special characters in my password as it was a standard password policy.
