### ISSUE TITLE
Cannot regenerate new Token while both access_token and refresh_token are expired (-1)

### ISSUE THREAD

**Issue by Chomroeun** [Chocobozzz/PeerTube#5821]
### Describe the current behavior

I don't know how to regenerate while refresh_token is also expired and when I use api for login user with user and password it always return message with expired_token_in = -1

`Login error {
"err": {
"statusCode": 400,
"status": 400,
"code": 400,
"message": "Missing parameter: `refresh_token`",
"name": "invalid_request",
"stack": "invalid_request: Missing parameter: `refresh_token` `

**Comment by Chomroeun** [comment]
Yeah I already use this rest api but the result with expires_in = -1. it does not reset expire_in value.

**Comment by Chocobozzz** [comment]
Maybe a configuration issue? https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L40
I don't think we support `-1` value here
