### ISSUE TITLE
On 5.2.0-rc.1 api  broken link, menu bottom left.

### ISSUE THREAD

**Issue by rnek0** [Chocobozzz/PeerTube#5825]
### Describe the current behavior

Click on api link sends to a 404  : <https://docs.joinpeertube.org/api/rest-reference.html>

### Steps to reproduce

1. Click bottom left on api link
2. Send to : https://docs.joinpeertube.org/api/rest-reference.html (404)

See here : <https://github.com/Chocobozzz/PeerTube/blob/07880c3642ca9fd9363850cf1a8e3cd2c6d9cd59/client/src/app/menu/menu.component.html#L145>  or or check the api doc homepage.

### Describe the expected behavior

Have the api doc pages.

### Additional information

* PeerTube instance: 
  * URL: https://ptb.lunarviews.net/
  * Version: 5.2.0-rc.1
  * NodeJS version: v18.16.0
  * Ffmpeg version: ffmpeg version 4.3.6-0+deb11u1

**Comment by Chocobozzz** [comment]
Thanks, I added a redirection on the server documentation to avoid 404
