### ISSUE TITLE
Plugin/theme static endpoints optimization

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5826]
### Describe the problem to be solved

Plugins and Themes can declare folders that will be served as static files (using `staticDirs` in `package.json`).

Serving these static files is not well optimized. It requires to pass throught Peertube controllers, like these ones:

```typescript
pluginsRouter.get('/plugins/:pluginName/:pluginVersion/static/:staticEndpoint(*)',
  getPluginValidator(PluginType.PLUGIN),
  pluginStaticDirectoryValidator,
  servePluginStaticDirectory
)
```

These functions have to check each time that the plugin is installed, check its version, and so on.
And nginx has no way to shortcut this, to directly serve the files.

As Peertube is single threaded, this can add a huge load of work. See for example what happened when we made a stress test in december 2022: https://www.octopuce.fr/test-de-charge-dun-peertube-en-live-avec-auposte/ 

### Describe the solution you would like

Create a dedicated folder for plugins/themes static files (somewhere in `/var/www/peertube/storage/plugins` for example).

On plugin/theme installation:

* Create a subfolder with the plugin name
* Create symbolic links (or copy files?) pointing to the plugins/themes static directories.

So we can configure nginx to serve these files staticly, and shortcut Peertube.

On plugin uninstallation, these links would be deleted.

This would result in a structure like:

```
/var/www/peertube/storage/plugins/statics
/var/www/peertube/storage/plugins/statics/peertube-plugin-livechat
/var/www/peertube/storage/plugins/statics/peertube-plugin-livechat/7.0.0
/var/www/peertube/storage/plugins/statics/peertube-plugin-livechat/7.0.0/directory_1 -> /var/www/peertube/storage/plugins/nodes_modules/peertube-plugin-livechat/directory_1
```

And nginx would `try_files` in these directories. Nginx could also add some headers to tell browser to make aggressive file caching (as file should be immutable in these directories).

**Comment by Chocobozzz** [comment]
Hi,

Do you have a flamegraph or a profile file to confirm these middleware are responsible for this high peertube load?

**Comment by JohnXLivingston** [comment]
> Hi,
> 
> Do you have a flamegraph or a profile file to confirm these middleware are responsible for this high peertube load?

No. But I think that all kind of optimization are welcome. And this one seems relatively easy to add.

**Comment by Chocobozzz** [comment]
Hi,

I made a benchmark test on my dev instance on my local computer with 100 concurrent users and 10000 requests.

```
Document Path:          /plugins/livechat/7.1.0/static/conversejs/locales/dayjs/fr-js.js
Document Length:        1241 bytes

Concurrency Level:      100
Time taken for tests:   32.739 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      16960000 bytes
HTML transferred:       12410000 bytes
Requests per second:    305.45 [#/sec] (mean)
Time per request:       327.390 [ms] (mean)
Time per request:       3.274 [ms] (mean, across all concurrent requests)
Transfer rate:          505.89 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.2      0       2
Processing:    10  326 142.0    341    1122
Waiting:        7  323 141.0    338    1118
Total:         12  326 142.0    342    1122

Percentage of the requests served within a certain time (ms)
  50%    342
  66%    359
  75%    382
  80%    402
  90%    464
  95%    597
  98%    672
  99%    692
 100%   1122 (longest request)
```

> As Peertube is single threaded, this can add a huge load of work. See for example what happened when we made a stress test in december 2022: https://www.octopuce.fr/test-de-charge-dun-peertube-en-live-avec-auposte/

As you can see I don't think this endpoint is responsible for the performance issues you had, especially with a SPA application that loads static files only once when we arrive on the page. I prefer to not spend more optimizing this endpoint that doesn't seem to be a bottleneck. Of course we can reopen the issue if you still think it's the case, but then please provide some metrics.

> And this one seems relatively easy to add.

Nothing is easy to add, as it requires code, tests and maintenance during several years :)

**Comment by JohnXLivingston** [comment]
Thanks for your tests @Chocobozzz. 
I plan to make some performance tests soon (backend and frontend). Should help to find the bottleneck(s).
