### ISSUE TITLE
Log error - Cannot get latest plugins version

### ISSUE THREAD

**Issue by EricGuic** [Chocobozzz/PeerTube#5827]
### Describe the current behavior

Error in the log : 

error[05/06/2023 05:31:52] Cannot get latest plugins version.
{
  "npmNames": [
    "peertube-plugin-upload-instructions",
    "peertube-theme-dark",
    "peertube-plugin-originally-published-at",
    "peertube-plugin-transcoding-custom-quality",
    "peertube-plugin-simplelogo",
    "peertube-plugin-auth-saml2",
    "peertube-plugin-bittube-livestream-instructions",
    "peertube-plugin-matomo",
    "peertube-plugin-custom-links",
    "peertube-plugin-categories"
  ],
  "err": {
    "stack": "RequestError: Timeout awaiting 'request' for 7000ms\n    at ClientRequest.<anonymous> (/var/www/peertube/versions/peertube-v5.1.0/node_modules/got/dist/source/core/index.js:970:65)\n    at Object.onceWrapper (node:events:628:26)\n    at ClientRequest.emit (node:events:525:35)\n    at ClientRequest.origin.emit (/var/www/peertube/versions/peertube-v5.1.0/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n    at TLSSocket.socketErrorListener (node:_http_client:494:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n    at runNextTicks (node:internal/process/task_queues:65:3)\n    at processTimers (node:internal/timers:499:9)\n    at Timeout.timeoutHandler [as _onTimeout] (/var/www/peertube/versions/peertube-v5.1.0/node_modules/got/dist/source/core/utils/timed-out.js:36:25)\n    at listOnTimeout (node:internal/timers:561:11)\n    at processTimers (node:internal/timers:502:7)",
    "message": "Timeout awaiting 'request' for 7000ms",
    "name": "TimeoutError"
  }
}

### Steps to reproduce

Automatic check.

### Additional information

* PeerTube instance: Réseau Canopé
  * URL: tube.reseau-canope.fr
  * Version: 5.1.0
  * NodeJS version: ?
  * Ffmpeg version: ?

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Do you still have the issue?

**Comment by EricGuic** [comment]
Hi, I don't see any new error since last week. We will assume you're right kontrollanten, Thanks.
