### ISSUE TITLE
Changing video resolution options gives theme.default error

### ISSUE THREAD

**Issue by jpatje** [Chocobozzz/PeerTube#5828]
### Describe the current behavior

Under Configuration -> Video Transcoding, when removing the checkmark for 'Always transcode original resolution', and then clicking the Save button, a popup appears in the lower right corner 'Incorrect request parameters: theme.default'.

I did make sure to select at least 1 other resolution (1440p). When, for example I only select 1080p and hit save, the same error message appears and the change is not saved. (The 'Always transcode original resolution' checkmark is still active).

### Steps to reproduce

1. Go to Configuration - Video Transcoding and remove the checkmark for 'Always transcode original resolution', making sure there is at least a checkmark for any resolution.
2. Hit the Save button and the error will appear.

### Describe the expected behavior

The 'Always transcode original resolution' checkmark removed and only the chosen resolution has a checkmark (in my case 1440p).

### Additional information

* PeerTube instance:
  * URL: video.yerunski.nl
  * Version: 5.1.0.
  * NodeJS version: v16.14.0
  * Ffmpeg version: 4.4.2-0ubuntu0.22.04.1

* Browser name, version and platforms on which you could reproduce the bug: Chrome version 114.0.5735.110, Windows 10 22H2.
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

Can you check the `Theme` select value in admin -> configuration -> basic? Maybe set to a theme that do not exist anymore?

**Comment by jpatje** [comment]
Hi @Chocobozzz, it was blank. I chose 1 of the 2 themes and the issue is solved. Thanks so much!
