### ISSUE TITLE
In notifications page, lots of "ERROR TypeError: Ge.registration is undefined"

### ISSUE THREAD

**Issue by nderambure** [Chocobozzz/PeerTube#5833]
### Describe the current behavior

Just going to notifcation page https://..../my-account/notifications and console shows a lot of this error.
There is also lots of empty lines in notifcations list.
I think it happened just after the 5.1.0 update but not sure, I just saw this recently.

Any idea ?
Thx !

### Additional information

* PeerTube instance:
  * URL: https://tube.futuretic.fr
  * Version: 5.1.0
  * NodeJS version: 16.20 (Debian 11)
  * Ffmpeg version: 4.3.6-0+deb11u1

* Browser name, version and platforms on which you could reproduce the bug: all
* Link to browser console log if relevant: https://pastebin.com/83GzUatt

**Comment by Chocobozzz** [comment]
Thanks! It was a migration issue. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/7aacaa76ec990f6b06f3f15a5666d103f68594f1

**Comment by nderambure** [comment]
Thx @Chocobozzz !
