### ISSUE TITLE
S3 storage proxy doesn't work with Strato S3

### ISSUE THREAD

**Issue by normen** [Chocobozzz/PeerTube#5835]
### Describe the current behavior

When enabling S3 storage with Strato HiDrive S3 and proxying for private videos the private videos never play. Public and unlisted videos play fine directly from S3.

This error appears in the server log when trying to play a private video:
```
23:34:20 peertube_peertube_1[526936]: [tube.bitwaves.de:443] 2023-06-14 21:34:20.568 error: Client log: HLS.js error: networkError - fatal: true - manifestParsingError {
23:34:20 peertube_peertube_1[526936]:   "username": "normen",
23:34:20 peertube_peertube_1[526936]:   "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15",
23:34:20 peertube_peertube_1[526936]:   "url": "https://tube.bitwaves.de/w/ksdjalksjdkajsdkljsalkdjl"
23:34:20 peertube_peertube_1[526936]: }
23:34:20 peertube_peertube_1[526936]: [tube.bitwaves.de:443] 2023-06-14 21:34:20.572 error: Client log: Cannot get sha256 segments {
23:34:20 peertube_peertube_1[526936]:   "username": "normen",
23:34:20 peertube_peertube_1[526936]:   "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15",
23:34:20 peertube_peertube_1[526936]:   "stackTrace": "The string did not match the expected pattern.\njson@[native code]\nrun@https://tube.bitwaves.de/client/de-DE/polyfills.053
2020c31aa9a62.js:1:31062\n@https://tube.bitwaves.de/client/de-DE/polyfills.0532020c31aa9a62.js:1:46025\nrunTask@https://tube.bitwaves.de/client/de-DE/polyfills.0532020c31aa9a62.j
s:1:31706\nH@https://tube.bitwaves.de/client/de-DE/polyfills.0532020c31aa9a62.js:1:38440",
23:34:20 peertube_peertube_1[526936]:   "url": "https://tube.bitwaves.de/w/ksdjalksjdkajsdkljsalkdjl"
23:34:20 peertube_peertube_1[526936]: }
```

Same for the browser:
```
[Error] Cannot get sha256 segments – SyntaxError: The string did not match the expected pattern.
SyntaxError: The string did not match the expected pattern.jsonrun — zone.js:134(anonyme Funktion) — zone.js:1278runTask — zone.js:178H — zone.js:588
	clientError (main.6feb00aeda3fe6ea.js:3:582376)
	error (main.6feb00aeda3fe6ea.js:3:582338)
	(anonyme Funktion) (9325.582c013f69d4b2c5.js:1:160335)
	run (polyfills.0532020c31aa9a62.js:1:31063)
	(anonyme Funktion) (polyfills.0532020c31aa9a62.js:1:46026)
	runTask (polyfills.0532020c31aa9a62.js:1:31707)
	H (polyfills.0532020c31aa9a62.js:1:38441)
[Error] Cannot stringify meta. – TypeError: JSON.stringify cannot serialize cyclic structures.
TypeError: JSON.stringify cannot serialize cyclic structures.
	buildMetaServerLogPayload (main.6feb00aeda3fe6ea.js:3:583772)
	buildServerLogPayload (main.6feb00aeda3fe6ea.js:3:583327)
	(anonyme Funktion) (main.6feb00aeda3fe6ea.js:3:582635)
	runHooks (main.6feb00aeda3fe6ea.js:3:583871)
	error (main.6feb00aeda3fe6ea.js:3:582308)
	_onError (7195.5dd12268a8f147b2.js:1:3434)
	(anonyme Funktion) (7195.5dd12268a8f147b2.js:698:1865)
	(anonyme Funktion) (7195.5dd12268a8f147b2.js:449:2976)
	(anonyme Funktion) (7195.5dd12268a8f147b2.js:545:6143)
	(anonyme Funktion) (7195.5dd12268a8f147b2.js:545:3877)
	(anonyme Funktion)
	successPlaylist (1513.90baa2f04abc84c6.js:1:38099)
	(anonyme Funktion) (1513.90baa2f04abc84c6.js:1:36686)
	M (2857.2b0edcf615bcebb5.js:1:82427)
	v (2857.2b0edcf615bcebb5.js:1:82640)
	run (polyfills.0532020c31aa9a62.js:1:31063)
	(anonyme Funktion) (polyfills.0532020c31aa9a62.js:1:46026)
	runTask (polyfills.0532020c31aa9a62.js:1:31707)
	H (polyfills.0532020c31aa9a62.js:1:38441)
	invokeTask (polyfills.0532020c31aa9a62.js:1:37479)
	T (polyfills.0532020c31aa9a62.js:1:50202)
	F (polyfills.0532020c31aa9a62.js:1:50512)
[Error] HLS.js error: networkError - fatal: true - manifestParsingError – Object
ObjectcurrentTime: 0data: {type: "networkError", details: "manifestParsingError", fatal: true, url: "https://tube.bitwaves.de/object-storage-proxy/stre…/ahskdjhajksdhjksahdjkhsdkjhksdj-master.m3u8", reason: "no EXTM3U delimiter", …}ObjectObject Prototyp
	clientError (main.6feb00aeda3fe6ea.js:3:582376)
	error (main.6feb00aeda3fe6ea.js:3:582338)
	_onError (7195.5dd12268a8f147b2.js:1:3434)
	(anonyme Funktion) (7195.5dd12268a8f147b2.js:698:1865)
	(anonyme Funktion) (7195.5dd12268a8f147b2.js:449:2976)
	(anonyme Funktion) (7195.5dd12268a8f147b2.js:545:6143)
	(anonyme Funktion) (7195.5dd12268a8f147b2.js:545:3877)
	(anonyme Funktion)
	successPlaylist (1513.90baa2f04abc84c6.js:1:38099)
	(anonyme Funktion) (1513.90baa2f04abc84c6.js:1:36686)
	M (2857.2b0edcf615bcebb5.js:1:82427)
	v (2857.2b0edcf615bcebb5.js:1:82640)
	run (polyfills.0532020c31aa9a62.js:1:31063)
	(anonyme Funktion) (polyfills.0532020c31aa9a62.js:1:46026)
	runTask (polyfills.0532020c31aa9a62.js:1:31707)
	H (polyfills.0532020c31aa9a62.js:1:38441)
	invokeTask (polyfills.0532020c31aa9a62.js:1:37479)
	T (polyfills.0532020c31aa9a62.js:1:50202)
	F (polyfills.0532020c31aa9a62.js:1:50512)
```

### Steps to reproduce

1. Enable S3 with Strato HiDrive S3
2. Enable proxying
3. Try playing a private video

### Describe the expected behavior

The video should play via the peertube proxy. Maybe the S3 storage is incompatible in some way?

### Additional information

* PeerTube instance:
  * URL: https://tube.bitwaves.de
  * Version: 5.1.0 (docker)
  * NodeJS version: (docker)
  * Ffmpeg version: (docker)

* Browser name, version and platforms on which you could reproduce the bug: Safari 16.5, MacOS
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by stevespaw** [comment]
Same thing happens will the several s3 providers we are using. It seems that "private" does not move them properly. We have to use "unlisted" for now.

**Comment by normen** [comment]
> Same thing happens will the several s3 providers we are using. It seems that "private" does not move them properly. We have to use "unlisted" for now.

Indeed, when I look at the S3 storage directly there is all folders and files but the files all have 0kB size... This means you effectively delete your videos when you make them private... :/

**Comment by Chocobozzz** [comment]
Hi,

I think ACL is not supported by this S3 provider. You can disable it in https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L173

See also https://github.com/Chocobozzz/PeerTube/issues/5497

**Comment by normen** [comment]
> Hi,
> 
> I think ACL is not supported by this S3 provider. You can disable it in https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L173
> 
> See also #5497

Thanks for the hints, I did disable private ACLs it for now in peertube but for my server backup I am using that same S3 provider and I can set a private ACL in that case. The funny thing is that the files are created in the container, they're just empty.

**Comment by Chocobozzz** [comment]
Do you still have the bug with ACL disabled? If yes, can you run peertube with debug logs and paste them after a video upload?

**Comment by normen** [comment]
> Do you still have the bug with ACL disabled? If yes, can you run peertube with debug logs and paste them after a video upload?

When I set a public-read ACL for private videos in peertubes settings it works, just like public/unlisted S3 videos work fine. I was just mentioning that for other things I am using a private ACL with that same cloud.

**Comment by Chocobozzz** [comment]
Maybe they support ACL when we create the object, but updating ACL is not implemented? I don't know. You may contact them to figure it out :)

**Comment by normen** [comment]
> Maybe they support ACL when we create the object, but updating ACL is not implemented? I don't know. You may contact them to figure it out :)

From what I found out with the `aws s3api` tools it seems that `get-object-acl` is the one thats acting a bit funny. It doesn't report the state XML, instead it returns the file content. Could that be the issue?
