### ISSUE TITLE
Add a subtitle entry to the list : "Français pour sourds et malentendants" (or "Français SME")

### ISSUE THREAD

**Issue by EricGuic** [Chocobozzz/PeerTube#5837]
### Describe the problem to be solved

Help deaf and hard of hearing people (sorry if the translation is wrong) to play and understand peertube videos.

### Describe the solution you would like

Support of SME subtitle (in french "sous-titres pour sourds et malentendants") in Peertube player.
In short, allow rich text support with colour in subtitle.

See the website of the french authority for all details : https://www.csa.fr/Reguler/Espace-juridique/Les-relations-de-l-Arcom-avec-les-editeurs/Chartes-et-autres-guides/Charte-relative-a-la-qualite-du-sous-titrage-a-destination-des-personnes-sourdes-ou-malentendantes-Decembre-2011

**Comment by Chocobozzz** [comment]
I think we need a more global setting for all available languages no?

**Comment by EricGuic** [comment]
Yes, you're right.
I see two differents actions to be made : 

- (I guess) every langage would need an alternative version (so "French" seconded by a "French SME" entry ; "SME" is the term in France, but it would be different in every country).
- Then a support of rich text in subtitle (colorized letters, italic, bold, etc.).

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/2649
