### ISSUE TITLE
Wrong alphabetical order in subtitle langage list

### ISSUE THREAD

**Issue by EricGuic** [Chocobozzz/PeerTube#5838]
### Describe the current behavior

In the subtitle langage list, entry starting with an accentueted letter is forwarded to the end of the list (for example "éwé" in the capture below).

![image](https://github.com/Chocobozzz/PeerTube/assets/81166671/8194bfa8-292d-47dc-ae76-de2aeb3c38c5)

### Steps to reproduce

1. Edit a video
2. Try to add a caption
3. Scroll the langage list to the bottom

### Describe the expected behavior

See "éwé" in the right order (at the end of the langage starting with the letter "e").

### Additional information

* PeerTube instance:
  * URL:
  * Version: 5.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/7c77ace9a7678e2e0e15644b0080f2dd31d2f7ec
