### ISSUE TITLE
HTML and AP formats use different account ids, leading to incompatible URLs

### ISSUE THREAD

**Issue by nightpool** [Chocobozzz/PeerTube#584]
When viewing a video, the account it links to looks something like https://peertube.mastodon.host/accounts/1328

going to that page shows the right videos and data:

![image](https://user-images.githubusercontent.com/233815/40438103-2ec85fae-5e85-11e8-8bfd-3815dde35491.png)

but when plugging that URL into another AP system, like mastodon, it suddenly fails to work:

![image](https://user-images.githubusercontent.com/233815/40438087-2393a1de-5e85-11e8-8c5e-c6a552f87851.png)

```bash
nightpool@neo:~$ curl -H "Accept: application/ld+json" https://peertube.mastodon.host/accounts/1328
{"error":"Account not found"}
```

It turns out that when you webfinger the account, it actually returns a completely different URL: https://peertube.mastodon.host/accounts/sandhawke

However, when you look at it in a browser, this just renders a blank page:

![image](https://user-images.githubusercontent.com/233815/40438197-718fac7a-5e85-11e8-8313-480556f200d1.png)

this URL incompatibility makes it really hard for users to find accounts that they may be interested in following, especially since as far as I can tell, peertube doesn't have any sort of remote follow button yet. Many mastodon users are used to using the search bar to resolve URL content when they want to interact with it from their local instance.

* **PeerTube version or URL:** https://peertube.mastodon.host/videos/watch/969ea381-4800-4718-b085-8c6ab1c518bb

**Comment by Chocobozzz** [comment]
Thanks for the issue @nightpool 

Just have a question: if you curl an account id (for example 1328) that is on another server, should we return a 301 to the origin URL of this actor or a 404?

**Comment by tcitworld** [comment]
Edit : said crap, sorry.

**Comment by Chocobozzz** [comment]
Okay so with this commit https://github.com/Chocobozzz/PeerTube/commit/ad9e39fb815d85e5e718c40540fa75471474fa17, now we only use account names (and host for remote actors) in client routes (like the AP routes) : `/accounts/chocobozzz` or `/accounts/chocobozzz@example.com`. It fixes the consistency issue with AP routes and the issue when the actor has only numbers in his username (because `/accounts/:idNumber` is not a valid route anymore).

**Comment by tcitworld** [comment]
That's good, but it doesn't solve the part where the user wants to do an ActivityPub query on `/accounts/chocobozzz@example.com`.

**Comment by Chocobozzz** [comment]
@cwebber Do you have any thoughts on https://github.com/Chocobozzz/PeerTube/issues/584#issuecomment-391701147?

**Comment by cwebber** [comment]
Strictly speaking, there is no requirement that viewing the actor URI ever render HTML.  But I agree this is probably what users expect.  Redirects, depending upon content negotiation, to the "equivalent" page for that content-type seem reasonable.

**Comment by nightpool** [comment]
@cwebber as i understand it, the question is about remote user accounts. i.e. should https://peertube.mastodon.host/accounts/chocobozzz@example.com 301 to https://example.com/accounts/chocobozzz

**Comment by nightpool** [comment]
Anyway, uniting the client and AP routes was the main thing I was worried about here, so i think the main concern is resolved.
