### ISSUE TITLE
Text is not translated

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5844]
### Describe the current behavior

Although the "I forgot my password" sentence is translated on Weblate, but it is not translated on the login page.
I am using Persian language.

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

In which version of peertube?

**Comment by Chocobozzz** [comment]
Translations are not integrated in older releases. For example I merged translations yesterday in 5.2.0 (that you can see on https://peertube3.cpy.re for example). The forgot password string is translated here in Persian language. But if you continue to translate other strings on weblate from now on, you'll only be able to see them on https://peertube2.cpy.re/ (test instance updated nightly) or in the next peertube major version (v6)

**Comment by paymanzafar1** [comment]
This is not a new translation. It was translated long time ago. There is a bug in the source code. Please check.

**Comment by paymanzafar1** [comment]
I built my instant with the latest translation file.

**Comment by Chocobozzz** [comment]
It was translated 3 weeks ago: https://weblate.framasoft.org/translate/peertube/angular/fa/?checksum=d0d93a801810e9b8&q=I+forgot+my+password&sort_by=-priority%2Cposition

So it's expected to not have the translation in 5.1 but you can see it in 5.2

**Comment by paymanzafar1** [comment]
Please note that I have built my own instance with the latest translation files. So, I am have this translation in my code, but it is not shown on the login page.

**Comment by Chocobozzz** [comment]
I don't know how you built peertube, but with 5.2 built a few hours ago and on my computer we can see the translation

![screen_2023-06-21-11:55:38](https://github.com/Chocobozzz/PeerTube/assets/5180488/340fdf43-6e54-46cc-b815-aafd231185f7)

**Comment by paymanzafar1** [comment]
OK. Thank you. I will check.
