### ISSUE TITLE
Error in parsing config file

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5846]
### Describe the problem

Hi,
I built the new 5.2.0 version. I have already built the previous version several times without any problem.

After starting the peertube service, it stops. I found the following error in journalctl:

 Error: Cannot parse config file: '/var/www/peertube/config/production.yaml': YAMLException: bad indent>
Jun 24 10:44:35 paymanzafar peertube[345640]:  439 |   # Default value of maximum vide ...
Jun 24 10:44:35 paymanzafar peertube[345640]:  440 |   # Byte format is supported ("1G ...
Jun 24 10:44:35 paymanzafar peertube[345640]:  441 |   # -1 == unlimited
Jun 24 10:44:35 paymanzafar peertube[345640]:  442 |   video_quota: -1
Jun 24 10:44:35 paymanzafar peertube[345640]: ---------^
Jun 24 10:44:35 paymanzafar peertube[345640]:  443 |   video_quota_daily: -1
Jun 24 10:44:35 paymanzafar peertube[345640]:  444 |
Jun 24 10:44:35 paymanzafar peertube[345640]:     at util.parseFile (/var/www/peertube/versions/peertube-v5.2.0/node_modules/config/lib/config.js:85>

It seems that it has problem with the new parameters: video_quota & video_quota_daily

I commented these two lines in production.yaml file, and the service started, and it is OK.

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by Chocobozzz** [comment]
Hello,

There is something wrong indentation in your configuration file. Please paste the section around `video_quota`

**Comment by paymanzafar1** [comment]
signup:
  enabled: false

  limit: 10 # When the limit is reached, registrations are disabled. -1 == unlimited

  minimum_age: 16 # Used to configure the signup form

  # Users fill a form to register so moderators can accept/reject the registration
  requires_approval: true
  requires_email_verification: false

  filters:
    cidr: # You can specify CIDR ranges to whitelist (empty = no filtering) or blacklist
      whitelist: []
      blacklist: []

user:
  history:
    videos:
      # Enable or disable video history by default for new users.
      enabled: true
  # Default value of maximum video bytes the user can upload (does not take into account transcoded files)
  # Byte format is supported ("1GB" etc)
  # -1 == unlimited
  video_quota: -1
  video_quota_daily: -1

video_channels:
  max_per_user: 20 # Allows each user to create up to 20 video channels.

# If enabled, the video will be transcoded to mp4 (x264) with `faststart` flag
# In addition, if some resolutions are enabled the mp4 video file will be transcoded to these new resolutions
# Please, do not disable transcoding since many uploaded videos will not work
transcoding:
  enabled: true

**Comment by Chocobozzz** [comment]
Is it your `/var/www/peertube/config/production.yaml` file?

**Comment by paymanzafar1** [comment]
Hi,
I found the problem. Thank you very much.
