### ISSUE TITLE
PeerTube crashes every day when it's trying to do some updates and checks

### ISSUE THREAD

**Issue by ctsrc** [Chocobozzz/PeerTube#5850]
### Describe the current behavior

I am running PeerTube v5.1.0 on FreeBSD

Every day it crashes. These are the last lines of output that appear in the log when it crashes

```text
[video.nstr.no:443] 2023-06-23 23:00:10.778 info: Updating youtubeDL binary from https://api.github.com/repos/yt-dlp/yt-dlp/releases.
[video.nstr.no:443] 2023-06-23 23:00:10.788 info: Removing old videos views.
[video.nstr.no:443] 2023-06-23 23:00:10.790 info: Checking latest PeerTube version.
[video.nstr.no:443] 2023-06-23 23:00:10.792 info: Updating GeoIP database from https://dbip.mirror.framasoft.org/files/dbip-country-lite-latest.mmdb.
[video.nstr.no:443] 2023-06-23 23:00:10.793 info: Checking latest plugins version.
Assertion failed: (!"unknown EAI_* error code"), function uv__getaddrinfo_translate_error, file src/unix/getaddrinfo.c, line 90.
```

### Steps to reproduce

1. Have PeerTube v5.1.0 running on FreeBSD
2. When it attempts to do some updates and checks, it crashes
3. That's it

### Describe the expected behavior

It should not crash like this

### Additional information

* PeerTube instance:
  * URL: https://video.nstr.no
  * Version: PeerTube v5.1.0
  * NodeJS version: Node v19.6.0 
  * Ffmpeg version: ffmpeg version 4.4.4

* Browser name, version and platforms on which you could reproduce the bug: N/A
* Link to browser console log if relevant: N/A
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): Relevant parts of log included above

**Comment by ctsrc** [comment]
Also worth to point out that this server is intentionally IPv6 only. The jail (FreeBSD container) that I run PeerTube inside of has intentionally been given only IPv6 connectivity and is not able to reach IPv4 internet.

**Comment by Chocobozzz** [comment]
Hi,

I think the peertube instance needs a way to reach out to IPv4 internet because github doesn't have an IPV6 (line `Updating youtubeDL binary from https://api.github.com/repos/yt-dlp/yt-dlp/releases.`)

**Comment by ctsrc** [comment]
I understand. But instead of requiring IPv4 internet, could there not be a way to disable the checks for yt-dlp updates @Chocobozzz
