### ISSUE TITLE
Cannot register runners

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5854]
### Describe the current behavior

I can start the runner server but not register to the peertube instance.

### Steps to reproduce

/usr/bin/peertube-runner server --id DIRECT-LIVE-node138

/usr/bin/peertube-runner register --url https://xxx.example.ltd --registration-token ptrrt-xxxxx --runner-name DIRECT-LIVE-node138

### Describe the expected behavior

must be able to register

### Additional information

log:
Jun 27 01:16:14 node138 peertube-runner[52243]: [01:16:14.475] INFO (52243): Running PeerTube runner in server mode
Jun 27 01:16:14 node138 peertube-runner[52243]: [01:16:14.483] INFO (52243): Using /home/PEERTUBE/.config/peertube-runner-nodejs/DIRECT-LIVE-node138/config.toml as configuration file
Jun 27 01:16:14 node138 peertube-runner[52243]: [01:16:14.499] INFO (52243): IPC socket created on /home/PEERTUBE/.local/share/peertube-runner-nodejs/DIRECT-LIVE-node138/peertube-runner.sock
Jun 27 01:16:14 node138 peertube-runner[52243]: [01:16:14.501] INFO (52243): Using /home/PEERTUBE/.cache/peertube-runner-nodejs/DIRECT-LIVE-node138/transcoding for transcoding directory
Jun 27 01:16:19 node138 peertube-runner[52244]: Cannot register this PeerTube runner.
Jun 27 01:16:19 node138 peertube-runner[52244]: Error: connect ENOENT /home/PEERTUBE/.local/share/peertube-runner-nodejs/default/peertube-runner.sock
Jun 27 01:16:19 node138 peertube-runner[52244]:     at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
Jun 27 01:16:19 node138 peertube-runner[52244]:   errno: -2,
Jun 27 01:16:19 node138 peertube-runner[52244]:   code: 'ENOENT',
Jun 27 01:16:19 node138 peertube-runner[52244]:   syscall: 'connect',
Jun 27 01:16:19 node138 peertube-runner[52244]:   address: '/home/PEERTUBE/.local/share/peertube-runner-nodejs/default/peertube-runner.sock'
Jun 27 01:16:19 node138 peertube-runner[52244]: }
Jun 27 01:16:19 node138 systemd[1]: peertube-runner@DIRECT-LIVE.service: Control process exited, code=exited, status=255/EXCEPTIO

**Comment by Chocobozzz** [comment]
Hello,

The `register` command needs to specify the same `--id` option as the server so just add `--id DIRECT-LIVE-node138` to `/usr/bin/peertube-runner register`

**Comment by ROBERT-MCDOWELL** [comment]
ok thx!
