### ISSUE TITLE
Remote Runners - Live Original Resolution get Transcoded

### ISSUE THREAD

**Issue by warnerbryce** [Chocobozzz/PeerTube#5855]
### Describe the problem to be solved

i have an Intel 11thGen core i5 as a dedicated runner for my live. 
I use to stream in 1080p60.
My PeerTube Instance runs on a NAS. 
If i tell my PeerTube Instance to transcode my live into 480p for viewers with weak bandwidth, my NAS give up and the stream is laggy. 

So when Remote Runners get released, i had to test this but.... 
Now my runner have to transcode 480p and 1080p60 and with this behavior my Intel 11thGen is too weak for long stream. 
About after 30 Minutes of livestream, i get a disconnect/reconnect on OBS, meaning that the Remote Runner do several jobs at once, Transcode the first part of the live and Transcode the live that is still running. 
Again after some more minutes it enters in a deadly loop where the stream stopped every 30 seconds.

### Describe the solution you would like
What are my options ? 
Do i need to a second remote worker for one live stream ? one for 1080p60 and one for 480p ?
Do i miss a conf where i can say transcode 480p only and let 1080p60 untouched ?

thank you

Edit : i’ve made a second attempt with two remote runners. I started a live and 35 minutes later i get a disconnect, i have this message on the runner job logs :
Job has been aborted but it is not supported by this job type 
Then the stream get disconnected every minutes until i stop the stream

**Comment by Chocobozzz** [comment]
Hi,

You can find runner config in `~/.config/peertube-runner-nodejs`
You can change the `concurrency` to `1` to avoid multiple transcoding in parallel. Did you also change the `threads` `[ffmpeg]` configuration to an higher value?

**Comment by warnerbryce** [comment]
I have : 
[jobs]
concurrency = 2

[ffmpeg]
threads = 2
nice = 20

I will set to concurrency to 1, enhance threads for ffmpeg and see how it works.

Thank you

**Comment by warnerbryce** [comment]
@Chocobozzz Alright with this settings i get a constant stream during 1h45 minutes then cut disconnect with a 502 Error from my NGINX PROXY, so i will have to see what setting needs to be modded. 
But great news because the stream restart automatically (with a F5 on the client though) and being handled correctly by the remote runner. Then it runs again for 1h45 and dies again with the Nginx Proyx. 

Thank you again @Chocobozzz
