### ISSUE TITLE
Error on log when register runner

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5857]
### Describe the current behavior

when I register a runner I can see the runner in the list but at the start the log shows

Jun 28 01:10:59 node230 peertube-runner[9946]:           Error: websocket error
Jun 28 01:10:59 node230 peertube-runner[9946]:               at WS.onError (/usr/lib/node_modules/@peertube/peertube-runner/dist/peertube-runner.js:82028:33)
Jun 28 01:10:59 node230 peertube-runner[9946]:               at ws.onerror (/usr/lib/node_modules/@peertube/peertube-runner/dist/peertube-runner.js:82594:35)
Jun 28 01:10:59 node230 peertube-runner[9946]:               at callListener (/usr/lib/node_modules/@peertube/peertube-runner/dist/peertube-runner.js:34127:18)
Jun 28 01:10:59 node230 peertube-runner[9946]:               at WebSocket3.onError (/usr/lib/node_modules/@peertube/peertube-runner/dist/peertube-runner.js:34081:13)
Jun 28 01:10:59 node230 peertube-runner[9946]:               at WebSocket3.emit (node:events:513:28)
Jun 28 01:10:59 node230 peertube-runner[9946]:               at emitErrorAndClose (/usr/lib/node_modules/@peertube/peertube-runner/dist/peertube-runner.js:35035:17)
Jun 28 01:10:59 node230 peertube-runner[9946]:               at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Jun 28 01:10:59 node230 peertube-runner[9946]:       "type": "TransportError"
Jun 28 01:10:59 node230 peertube-runner[9946]:     }

is it safe to ignore it?

**Comment by Chocobozzz** [comment]
It's safe but runners won't be able to process lives as soon as they start. I think you have an issue in your reverse proxy configuration that prevents correct socket.io websocket connection.

**Comment by ROBERT-MCDOWELL** [comment]
ok I see. is this websocket created with http headers I can check on my proxy or should I create a condition to treat this request adequately?

**Comment by Chocobozzz** [comment]
You can see how we handle it in the official nginx configuration: https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube#L119

**Comment by ROBERT-MCDOWELL** [comment]
Thanks!

**Comment by ROBERT-MCDOWELL** [comment]
ok fixed, as you (maybe) know I'm using apache (I maintain the apache configuration here
https://gist.github.com/rigelk/07a0b8963fa4fc1ad756374c28479bc7?permalink_comment_id=4242655#gistcomment-4242655
https://gist.github.com/ROBERT-MCDOWELL/0ed82ec304fa76de9ff52cc4a5a49e4c
)
and the issue were coming from the rewritecond chain  where [NC] flag created the trouble. I removed it and everything is ok now.
