### ISSUE TITLE
Runners rows dups in the DB

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5862]
### Describe the current behavior

When multiple runner registrations (by accident) are done with the same url and same runner name so there are multipled duplicates on the DB

### Steps to reproduce

1. register multiple times without to unregister witth the same URL, ID and RUNNER NAME

### Describe the expected behavior
- Avoid duplicates in DB by maybe some unique constraints with URL and RUNNER NAME combinations.
- Add an option to specify the config path of the runner ID when register

**Comment by ROBERT-MCDOWELL** [comment]
BTW is it possible to specify the config path of the runner for registration?

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/d959b763f089ed4c1087aa4aeb824a8ef6743111
