### ISSUE TITLE
Cannot execute migration 0770

### ISSUE THREAD

**Issue by TrevorMellon** [Chocobozzz/PeerTube#5866]
### Describe the problem

Migrating from v5.1.0 to v5.2.0

Long running instance.

Error:

peertube-peertube-1  | [peertube.ignifi.me:443] 2023-07-02 12:56:40.742 info: Executing 0770-actor-preferred-username.js migration script.
peertube-peertube-1  | [peertube.ignifi.me:443] 2023-07-02 12:56:40.962 error: Cannot execute migration 0770. {
peertube-peertube-1  |   "err": {
peertube-peertube-1  |     "stack": "Error\n    at Query.run (/app/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n    at /app/node_modules/sequelize/lib/sequelize.js:315:28\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
peertube-peertube-1  |     "message": "update or delete on table \"videoChannel\" violates foreign key constraint \"video_channelId_fkey\" on table \"video\"",
peertube-peertube-1  |     "name": "SequelizeForeignKeyConstraintError",
peertube-peertube-1  |     "parent": {
peertube-peertube-1  |       "stack": "error: update or delete on table \"videoChannel\" violates foreign key constraint \"video_channelId_fkey\" on table \"video\"\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
peertube-peertube-1  |       "message": "update or delete on table \"videoChannel\" violates foreign key constraint \"video_channelId_fkey\" on table \"video\"",
peertube-peertube-1  |       "length": 275,
peertube-peertube-1  |       "name": "error",
peertube-peertube-1  |       "severity": "ERROR",
peertube-peertube-1  |       "code": "23503",
peertube-peertube-1  |       "detail": "Key (id)=(1339) is still referenced from table \"video\".",
peertube-peertube-1  |       "schema": "public",
peertube-peertube-1  |       "table": "video",
peertube-peertube-1  |       "constraint": "video_channelId_fkey",
peertube-peertube-1  |       "file": "ri_triggers.c",
peertube-peertube-1  |       "line": "2478",
peertube-peertube-1  |       "routine": "ri_ReportViolation",
peertube-peertube-1  |       "sql": "DELETE FROM \"actor\" v1 USING (SELECT MIN(id) as id, lower(\"preferredUsername\") AS \"lowerPreferredUsername\", \"serverId\" FROM \"actor\" GROUP BY \"lowerPreferredUsername\", \"serverId\" HAVING COUNT(*) > 1 AND \"serverId\" IS NOT NULL) v2 WHERE lower(v1.\"preferredUsername\") = v2.\"lowerPreferredUsername\" AND v1.\"serverId\" = v2.\"serverId\" AND v1.id <> v2.id"
peertube-peertube-1  |     },
peertube-peertube-1  |     "sql": "DELETE FROM \"actor\" v1 USING (SELECT MIN(id) as id, lower(\"preferredUsername\") AS \"lowerPreferredUsername\", \"serverId\" FROM \"actor\" GROUP BY \"lowerPreferredUsername\", \"serverId\" HAVING COUNT(*) > 1 AND \"serverId\" IS NOT NULL) v2 WHERE lower(v1.\"preferredUsername\") = v2.\"lowerPreferredUsername\" AND v1.\"serverId\" = v2.\"serverId\" AND v1.id <> v2.id",
peertube-peertube-1  |     "parameters": {},
peertube-peertube-1  |     "table": "videoChannel",
peertube-peertube-1  |     "fields": null,
peertube-peertube-1  |     "index": "video_channelId_fkey"
peertube-peertube-1  |   }
peertube-peertube-1  | }

### Additional information

* PeerTube instance URL: peertube.ignifi.me
* PeerTube version: v5.1.0 -> v5.2.0

* PostgreSQL version: 13

**Comment by Chocobozzz** [comment]
Hi,

Sorry about that. 


Can you display `videoChannel` table information? 

```
sudo -u postgres psql peertube_prod
\d "videoChannel"
```

**Comment by TrevorMellon** [comment]
There seemed to be a lot of problems with the database and the new migrations. Specifically making some table properties unique (and rightly so), I went through the database myself and fixed all the duplicated fields so the migration could continue.

All working now, touch wood.

**Comment by Chocobozzz** [comment]
I think there is an issue in your database, where a foreign key doesn't have the appropriate cascade values

**Comment by poka-IT** [comment]
You can see the database upgrading in process names, `ps -aux | grep peertube`:

`postgres: peertube peertubeprod 172.18.0.42(58038) UPDATE`
