### ISSUE TITLE
Limit the number of characters in the `og:description` meta to a sane count.

### ISSUE THREAD

**Issue by christophehenry** [Chocobozzz/PeerTube#5871]
### Describe the current behavior

Current behavior is to put the whole vide descrption in `og:description` which is useles because most social networks will trim this text to a reasonnable amount of character. 

However when sharing a Peertube in a social network Android app which with char count limits for posts (e.g. Twitter or Mastodon), this forces the user to delete a text that can be very long, which is tedious.

### Describe the expected behavior

The `og:description` meta content should be limited to a sane char count. E.g 20.

**Comment by christophehenry** [comment]
200 seems already too long for Twitter, for instance.

**Comment by hollownights** [comment]
Just use what has been the default in search engines for years and years, 150 characters.
