### ISSUE TITLE
Fressh Install Blank Pages

### ISSUE THREAD

**Issue by 2TonWaffle** [Chocobozzz/PeerTube#5875]
### Describe the problem

Experiencing this is after a fresh install of Peertube in which the page loads but it does not display anything. Further looking there are a few 403 errors but I'm not sure where or what file might be the cause.

![scrnli_7_5_2023_12-03-31 PM](https://github.com/Chocobozzz/PeerTube/assets/128096662/2baa533a-1431-4b5c-9473-b8c332b4a221)

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue but please use the forum for sysadmin support: https://framacolibri.org/c/peertube
