### ISSUE TITLE
Terms link is not expanding text field

### ISSUE THREAD

**Issue by polykit** [Chocobozzz/PeerTube#5876]
### Describe the current behavior

Terms/CoC etc. links on login and registration page are not expanding the related text field. It seems this is a problem in Peertube version 5.2.0. I've seen this working on prior versions.

### Steps to reproduce

Click on Terms link on the following pages:
https://makertube.net/login
https://makertube.net/signup

I've also seen this problem on other Peertube sites running on version 5.2.0.

### Describe the expected behavior

The text field should expand and show the text.

### Additional information

* PeerTube instance:
  * URL: https://makertube.net
  * Version: 5.2.0
  * NodeJS version: Official docker image
  * Ffmpeg version: Official docker image

* Browser name, version and platforms on which you could reproduce the bug: Chrome on Linux Version 114.0.5735.133 (Official Build) (64-bit)
* Link to browser console log if relevant: no relevant errors
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): no relevant logs

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/ed22eaabfac0d53550cd838c12b7d80e01bcc7b5
