### ISSUE TITLE
Automatic upgrade doesn't account for specified DB port

### ISSUE THREAD

**Issue by averymd** [Chocobozzz/PeerTube#5878]
### Describe the problem

The automated upgrade script (https://github.com/Chocobozzz/PeerTube/blob/develop/scripts/upgrade.sh) doesn't leverage the `['database']['port']` setting from the `production.yaml` file. This breaks the ability to use the script for servers that use non-standard ports (e.g., DigitalOcean's managed postgresql).

### Additional information

* PeerTube instance URL: https://irrsinn.video
* PeerTube version: 5.2.0 (and previous)
* NodeJS version: 16.20.1
* PostgreSQL version: 12

**Comment by Chocobozzz** [comment]
Hi,

I added support of the db port in https://github.com/Chocobozzz/PeerTube/commit/97f57e928fafb715d0763e97c7a3e6fd454a0bfc

Can you test this patch?
