### ISSUE TITLE
Re-transcoding videos somehow makes 480p show up twice

### ISSUE THREAD

**Issue by JacksonChen666** [Chocobozzz/PeerTube#5879]
### Describe the current behavior

Upon HLS re-transcoding, there will be video qualities that show up twice in the settings and video admin panel.

480p seems to show up multiple times, at least on my side. (I just had a case of 360p showing up twice now)

### Steps to reproduce

1. Have only a couple of transcoded resolutions (only like 1080p and 480p and original)
2. Upload video
3. Turn on most transcoded resolutions
4. Re-transcode video (in admin panel for videos)
5. See 480p shows up twice, sometimes (and maybe others too)

### Describe the expected behavior

The video is re-transcoded without leaving behind duplicate qualities.

### Additional information

* PeerTube instance: videos.jacksonchen666.com
  * URL: https://videos.jacksonchen666.com
  * Version: 5.2.0
  * NodeJS version: v16.18.1
  * Ffmpeg version: 6.0 (for all remote runners and only remote runners)

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

Other info:
- Multiple remote runners were used
- The other video file is older, meaning the old video resolutions probably wasn't deleted

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/d98909f69070c81e87da723e414d91c6a2a6f343

**Comment by Chocobozzz** [comment]
May be a bug in a previous release of PeerTube, you can delete resolution you want
