### ISSUE TITLE
Re issue 1079

### ISSUE THREAD

**Issue by Downes** [Chocobozzz/PeerTube#5880]
### Describe the problem

Solution for issue 1079 located here https://github.com/Chocobozzz/PeerTube/issues/1079#issuecomment-872256813 (now closed) should be updated to reference version 20 instead of version 12. Tested and changing the 12 to 20 does succeed.

This is the relevant line: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by Chocobozzz** [comment]
Hi,

The [dependencies guide](https://docs.joinpeertube.org/support/doc/dependencies) already give the link to install correct versions of yarn and nodejs
