### ISSUE TITLE
Publish a video from another site as embedded

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5881]
### Describe the problem to be solved

Hi all,

During the publish process, if you input a video URL from another site, the video will be downloaded to your instance.

I think it is a very good feature to be able to published a video from another site (not a PeerTube instance) and put it inside an iframe html tag. Both on the home page, and also as a published video. 

### Describe the solution you would like

Add the ability to publish a video from another site as an embedded video.

**Comment by Chocobozzz** [comment]
Hi,

I'm sorry but this feature is out of the scope of PeerTube that needs to manage and transcode video files into appropriate format/codecs.
