### ISSUE TITLE
Executing a migration script in a nightly build

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#5885]
### Describe the problem

In the nightly build 5.2.0-nightly-2023-07-12 there was a change [Rename "videos" config to "web-videos"](https://github.com/Chocobozzz/PeerTube/commit/d732ec7b46caa2a0972f132894023fec6bc5dd6a)

I assume that you need to run the script execution. If so, which script should I use?

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by Chocobozzz** [comment]
Hi,

 * Rename `transcoding.webtorrent` to `transcoding.web_videos`
 * Rename `storage.videos` to `storage.web_videos`
 * Rename `object_storage.videos` to `object_storage.web_videos`

**Comment by Alterak** [comment]
> Hi,
> 
> * Rename `transcoding.webtorrent` to `transcoding.web_videos`
> * Rename `storage.videos` to `storage.web_videos`
> * Rename `object_storage.videos` to `object_storage.web_videos`

I am using a new configuration. There are no problems with this.
I'm more interested in the storage itself (moving or renaming). Don't need to make any changes manually?

**Comment by Chocobozzz** [comment]
> Don't need to make any changes manually?

No, it's just "cosmetic" changes where we updated key names in the configuration so it's more consistent and easier to understand for administrators. You can still use the previous configuration values.
