### ISSUE TITLE
Clear the cache when a runner starts

### ISSUE THREAD

**Issue by tio-trom** [Chocobozzz/PeerTube#5887]
### Describe the problem to be solved

If a runner shuts down while in the process of transcoding, then the files in .cache folder will remain there forever because the runner was unable to do the cleaning.

### Describe the solution you would like

When a runner first starts it should check the .cache folder and remove the leftovers from there.

**Comment by Chocobozzz** [comment]
Hello,

We should already cleanup the cache directory at startup and on exit. Can you display the command you use to run peertube-runner server? And display the content of the cache directory?

**Comment by tio-trom** [comment]
I use this command `peertube-runner server ` and at times this to start in the background 

`[ "$(pgrep -fx 'node /usr/bin/peertube-runner server' | wc -l)" -lt 1 ] && setsid -f peertube-runner server >/dev/null 2>&1`

> And display the content of the cache directory?

I have since removed them but they are the videos themselves as .mp4 files. Partially converted.

**Comment by tio-trom** [comment]
But I will test it today one more time. Maybe because I was testing many other things I didn't properly test this. I will update.

**Comment by Chocobozzz** [comment]
Any update on this @tio-trom?

**Comment by tio-trom** [comment]
Unfortunately no. I am sorry. It is on my test list but I did not have any time to properly test. If you can please leave this open so I can get back to it. I cannot properly test for the next 3 weeks tho. I did not forget but I was very busy.

**Comment by tio-trom** [comment]
Tested these past 2 days and seems to be all fine. Closing.
