### ISSUE TITLE
Youtube videos import on Peertube don't have subtitles

### ISSUE THREAD

**Issue by SventuraOscura** [Chocobozzz/PeerTube#5889]
### Describe the problem to be solved

I backup many youtube channels that have risk of removal, and what i noticed is that when i import the videos, subtitles aren't added at all.

### Describe the solution you would like

Peertube should import also the subtitles in the videos, and if possible, it should "check" every now and then, if subtitles got updated/removed from a particular video.  checking dimension, or name of file.

examples of filenames from Downsub.com

[English] The Halo Effect_ The Superpower of Beautiful People [DownSub.com]
[English (auto-generated)] The Halo Effect_ The Superpower of Beautiful People [DownSub.com]

Let me know, thanks!.

**Comment by Chocobozzz** [comment]
Hello,

It should import youtube subtitles already. Can you provide a youtube URL so we can reproduce?

**Comment by SventuraOscura** [comment]
Sure, i synched two channels 👍 

https://www.youtube.com/@jaketran
https://www.youtube.com/@FarFromWeakFFW

No subtitles are added.

**Comment by Chocobozzz** [comment]
@SventuraOscura I received an email with your answer but it disappeared from github. Anyway, can you give me a youtube video URL that contains subtitles that are not automatically generated *on the fly* by youtube?

**Comment by SventuraOscura** [comment]
Hi, sorry my bad.

I noticed only now that i imported channels on youtube that don't have subtitles, i am importing others that have subtitles and will let you know. 

Also, i noticed that when you synchronize a channel, you can't pass the ownership to another user, why?, if i want to do that, i need to delete and re-import everything. And, if you need to add the subtitles, why is not possible to use an expression function to separate them by language, instead of selecting each one of them each time?, for people that have many videos is kinda hard to do.

**Comment by Chocobozzz** [comment]
> Also, i noticed that when you synchronize a channel, you can't pass the ownership to another user, why

You can give ownership of specific videos in "My videos" page.
