### ISSUE TITLE
I can't access any peertube from phone.

### ISSUE THREAD

**Issue by frederiiiic** [Chocobozzz/PeerTube#589]
I can't access any peertube websites from my phone, i'm actually with a fairephone 2, OpenOs 18.03.1, android 6.0.1.

* **PeerTube version or URL: https://thinkerview.video/ and all the other url i've try**
* **Browser name/version: mozilla 50.1**
* **NodeJS version: ?**

* **What is the expected behaviour? List of vidéos**
* **What do you see instead? White page with this error ritten in red : "We are sorry but it seems that PeerTube is not compatible with your web browser.

Please try with the latest version of Mozilla Firefox.

If you think this is a mistake, do not hesitate to report it."**

* **Browser console log if useful (Gist/Pastebin...):?**
* **Server log if useful (Gist/Pastebin...):?**

**Comment by Chocobozzz** [comment]
You Firefox version is outdated. Please upgrade to the latest version (60) and retest.

**Comment by Chocobozzz** [comment]
Closing this old issue. Feel free to ask for reopening it.

**Comment by Zig-03** [comment]
@Chocobozzz what about LTS versions of Firefox, do you aim to support them as well? https://www.mozilla.org/en-US/firefox/organizations/

**Comment by Chocobozzz** [comment]
@Zig-03 Yes, we support (if all goes well) Firefox 52 (old LTS)

**Comment by frederiiiic** [comment]
@Chocobozzz My bad, with the last version it's working well!

Thanks for help.
