### ISSUE TITLE
Some input text boxes must be LTR even in RTL languages

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#5890]
### Describe the current behavior

I am using PeerTube v5.2.0 in Persian language which is RTL language.

Some input text boxes which contains codes & scripts, must be LTR, even in RTL languages. Here are some examples:

Administration -> Configuration -> Homepage -> Homepage
Administration -> Configuration -> Advanced -> JavaScript
Administration -> Configuration -> Advanced -> CSS

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
> Administration -> Configuration -> Homepage -> Homepage

Are you sure about this one? It's a more a classic "markdown" text area where you can optionally insert HTML tags, not a plain script/code text area like the "Custom CSS"/"Custom JS"

**Comment by paymanzafar1** [comment]
Hi,
Yes. Please refer to the attached screen capture.
Because the HTML tags are written LTR, it is somewhat confusing when show RTL. Also when you are going to edit them, sometimes it is difficult.

![image](https://github.com/Chocobozzz/PeerTube/assets/91053236/38e4ac49-c082-42c1-8a9e-445408c3b841)

**Comment by Chocobozzz** [comment]
Okay then! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/d430862f00f04e0831bcb4b3e188aad0fd8c45d1
