### ISSUE TITLE
No any new videos in "Recently-added" section for a few days

### ISSUE THREAD

**Issue by fweng322** [Chocobozzz/PeerTube#5891]
### Describe the current behavior

Instance: [https://peertube.slat.org](https://peertube.slat.org/)

I recently upgraded to 5.2.0 and migrated to a new server. But then I noticed that there are no any new videos in the Recently-added section for about 4 days, only local videos I added.

I’m not sure if it is caused by upgrading to 5.2.0, or by migrating to a new server.

I posted a discussion on forum [here](https://framacolibri.org/t/solved-nothing-in-the-recently-added-for-several-days/18356) and someone reminded me of the network configuration, which I fixed soon.  After that, three or four videos were added, but then it stopped again.  Until now more than 48 hours no any new videos from other instances were added here, only videos I post in local were shown there.

I disabled my ufw firewall but it didn't make any differences.

The peertube log from last 10 hours is [here](https://nextcloud.slat.org/index.php/s/7YCy9YaJHsSsJZq). 8MB size. 24234 Lines, only 538 lines with "level ":"warn" and 20 lines with "level":"error" in them. I still don’t know where to find the problem is.

### Steps to reproduce

1.
2.
3.

### Describe the expected behavior

New videos from other instances should be in Recently-added section.

### Additional information

* PeerTube instance: 
  * URL: https://peertube.slat.org/
  * Version: 5.2.0
  * NodeJS version: 16.20.1
  * Ffmpeg version: 4.3.6

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

https://nextcloud.slat.org/index.php/s/7YCy9YaJHsSsJZq

The logs from last 10 hours.

**Comment by Chocobozzz** [comment]
Hi,

I can see new videos https://peertube.slat.org/w/hPND2N7Qyw7Ng7y47ya7cQ

**Comment by Chocobozzz** [comment]
I think you should try to remove all your following, and restart to follow them again. Might be an issue during the migration process.

**Comment by fweng322** [comment]
> I think you should try to remove all your following, and restart to follow them again. Might be an issue during the migration process.

I tried to remove all my following and re-follow them.  However I got all the following requests pending.

Here is the peertube log after sending out the following requests:

https://nextcloud.slat.org/index.php/s/c9zx2p9fp4deer5

I noticed that many account signatures are invalid.  Not sure if that's the reason I didn't get responses.  I remembered that many of the sites I asked to follow before almost immediately accepted my requests.  Still no idea what's wrong.

**Comment by fweng322** [comment]
Is there any way I can help debug this?

**Comment by fweng322** [comment]
@Chocobozzz  Is there any way I can help debug this?  I noticed that several Peertube instances also got zero following.  I wonder if they met the same problem.

**Comment by fweng322** [comment]
Tried to regenerate SSL certificates from Let's Encrypt following this post:
https://framacolibri.org/t/cant-follow-other-instances/13915

Still no luck.

**Comment by Chocobozzz** [comment]
Try to follow framatube.org and peertube2.cpy.re so I can check the logs

**Comment by fweng322** [comment]
> Try to follow framatube.org and peertube2.cpy.re so I can check the logs

I just followed both.

I found this in my logs, not sure if it is where the problem is:

```
{"level":"warn","message":"Signature from https://framatube.org/accounts/peertube is invalid","label":"peertube.slat.org:443","parsed":{"scheme":"Signature","params":{"keyId":"https://framatube.org/accounts/peertube","algorithm":"rsa-sha256","headers":["(request-target)","host","date","digest"],"signature":"H8A3CL88fTdl0SNpKjOnoFQ5giyj/0WpEaYaZ7rqmr+dErNQweVXn9g4aHUz4RBTCeypB5kPLOu075HEDIuJvkdHDDz5IBFUqwAhRQx6mh0kKF6ZW7wmwxXB3VKyd5iu0Pl6bZMcw7QCqLVLDOxa/loea0zsh9onNA+IGcIGE3nEnaSY5n2uRTb2kIMmUqTJJKAOqdkr5hx2jYeLJBH+ekOG7z+Yq1dmLWbDyLYxHXvR5RCB24bOD8Fjv2bM7b42oUdvA65zRqbtofvXfmYXGicNhUzXSKgZly8GzA/1gKs8Wz3UpPpdfwqzMpm8kITH/rBoSuQrLbwqPlbrW+LJ1Q=="},"signingString":"(request-target): post /accounts/peertube/inbox\nhost: peertube.slat.org:443\ndate: Mon, 24 Jul 2023 13:46:07 GMT\ndigest: SHA-256=DJw3ONnzVBNAVJ2rxib6Xprw5TNWn7jwfoZL7W58i9A=","algorithm":"RSA-SHA256","keyId":"https://framatube.org/accounts/peertube"},"timestamp":"2023-07-24T13:46:07.844Z"}
{"tags":["http"],"level":"info","message":"178.63.240.146 - - [24/Jul/2023:13:46:07 +0000] \"POST /accounts/peertube/inbox HTTP/1.0\" 403 168 \"-\" \"PeerTube/5.2.0-nightly-2023-07-24 (+https://peertube2.cpy.re)\"","label":"peertube.slat.org:443","timestamp":"2023-07-24T13:46:07.837Z"}
{"level":"warn","message":"Signature from https://framatube.org/accounts/peertube is invalid","label":"peertube.slat.org:443","parsed":{"scheme":"Signature","params":{"keyId":"https://framatube.org/accounts/peertube","algorithm":"rsa-sha256","headers":["(request-target)","host","date","digest"],"signature":"HWV+P97fhPoXpbGqNGxAvHP+txYfi8++cZMrkfNuqaSPXT2fKGos1Z6pXpgX6cQG71qf8nJC4UjlWsRHHsBW8aGbIpPcUnb0prrKFHzOT5yQOury8h9UvSDpHeG5L0gcwhAdBNYR+ANlPE9wRX/c50UGYaylL0JKg+IAYiy1viMVRppFHun26ChgVKTPpoMK9J60c/lzxcOaR/JgIUWgAC92Zal2aWRRVfmA32Ks+YH/BKtb/xYNG6zvZmkO7Jzwex3bONsnCu5PhTqYlVOYIixgU5JDKmfAfVk4q2zDjGbAeX13lMk/R1i3QEhHet8nxTuZVrNpgLc+1Urrh1TPSg=="},"signingString":"(request-target): post /inbox\nhost: peertube.slat.org:443\ndate: Mon, 24 Jul 2023 13:46:13 GMT\ndigest: SHA-256=CKh7wKYfUMm85CLNrN7MedZ4enjrUgxmvpL94IDYXL8=","algorithm":"RSA-SHA256","keyId":"https://framatube.org/accounts/peertube"},"timestamp":"2023-07-24T13:46:14.221Z"}
{"tags":["http"],"level":"info","message":"178.63.240.148 - - [24/Jul/2023:13:46:14 +0000] \"POST /inbox HTTP/1.0\" 403 165 \"-\" \"PeerTube/5.2.0 (+https://framatube.org)\"","label":"peertube.slat.org:443","timestamp":"2023-07-24T13:46:14.223Z"}
```

**Comment by fweng322** [comment]
For all the instances I sent following requests, this 403 error exists

{"tags":["http"],"level":"info","message":"116.202.171.185 - - [24/Jul/2023:13:46:54 +0000] \"POST /inbox HTTP/1.0\" 403 174 \"-\" \"PeerTube/4.3.0 (+https://peertube.debian.social)\"","label":"peertube.slat.org:443","timestamp":"2023-07-24T13:46:54.152Z"}

**Comment by Chocobozzz** [comment]
Can you go inside your database and display:

```
 select * from actor inner join server ON server.id = actor."serverId" where server.host = 'framatube.org' and actor."preferredUsername" = 'peertube';
```

**Comment by fweng322** [comment]
> Can you go inside your database and display:
> 
> ```
>  select * from actor inner join server ON server.id = actor."serverId" where server.host = 'framatube.org' and actor."preferredUsername" = 'peertube';
> ```

https://pastebin.com/YnwepCa5

The output is a bit mess, hope it works

**Comment by fweng322** [comment]
Perhaps this screenshot is more clear.
https://nextcloud.slat.org/index.php/s/2wGnWwKPNdR4egY

**Comment by dhk2** [comment]
When you migrated to a new server, did you change the URL?

**Comment by fweng322** [comment]
> When you migrated to a new server, did you change the URL?

No.  IP changed, but hostname / URL didn't change.

**Comment by Chocobozzz** [comment]
Do you have a proxy or something like that in front of peertube that may update the `host` header of the HTTP request made by other peertube instances? I'm not sure to understand why the http signature parser says `host` is `peertube.slat.org:443` in https://github.com/Chocobozzz/PeerTube/issues/5891#issuecomment-1647957816

It may be the root cause of the issue

**Comment by fweng322** [comment]
> Do you have a proxy or something like that in front of peertube that may update the `host` header of the HTTP request made by other peertube instances? I'm not sure to understand why the http signature parser says `host` is `peertube.slat.org:443` in [#5891 (comment)](https://github.com/Chocobozzz/PeerTube/issues/5891#issuecomment-1647957816)
> 
> It may be the root cause of the issue

Do you mean this in nginx site configuration?

```
  ##
  # Application
  ##

  location @api {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host            $host:443;     # if not add :443 it will have "Cannot retrieve OAuth Client credentials" error
    proxy_set_header X-Real-IP       $remote_addr;

    client_max_body_size  100k; # default is 1M

    proxy_connect_timeout 10m;
    proxy_send_timeout    10m;
    proxy_read_timeout    10m;
    send_timeout          10m;

    proxy_pass http://backend;
  }
```

At first when migrating the instance to the new server, I tried to put it behind a reverse proxy, but I couldn't get it right, so I gave up and used the old way.  So now there is no proxy in front of the peertube instance.

And I added :443 after $host because if I didn't add it, everytime I open the page or refresh it would give me an error: `cannot retrieve oauth client credentials getting client tokens for host peertube.slat.org is forbidden`

https://nextcloud.slat.org/index.php/s/j2jTLcDLs3n4tFC

I searched and read a page saying that to add :443 after the $host to solve this error.  But I couldn't find it now.

Now I removed it (and now the nginx site setting is exactly the same as in the support/).  I'll see if it solves this issue.  But if yes, how can I solve the "cannot retrieve oauth client credentials" error?

**Comment by fweng322** [comment]
The webserver: section in my production.yaml is
```
# Correspond to your reverse proxy server_name/listen configuration (i.e., your public PeerTube instance URL)
webserver:
  https: true
  hostname: 'peertube.slat.org'
  port: 443
```

**Comment by fweng322** [comment]
> > I searched and read a page saying that to add :443 after the $host to solve this error. But I couldn't find it now.
> 
> It would have been relevant to specify you updated the default nginx configuration, because I spent a lot of time digging into the peertube code to understand why the signature was broken...
> 
> Please stick to the official nginx template and open a topic on https://framacolibri.org/c/peertube for your "cannot retrieve oauth client credentials" problem.

Thank you very much for your efforts.  I [opened a topic](https://framacolibri.org/t/cannot-retrieve-oauth-client-credentials-getting-client-tokens-for-host-peertube-slat-org-is-forbidden/18467) for the client credentials problem.
