### ISSUE TITLE
Move to external storage failed, this video may not work properly

### ISSUE THREAD

**Issue by nicfab** [Chocobozzz/PeerTube#5893]
### Describe the current behavior

After publishing a video (public), I saw a banner with "**Move to external storage failed, this video may not work properly**".
That video is not in my instance's list of published videos.
Is there anything I can do to solve it?

### Additional information

* PeerTube instance:
  * URL: https://tube.nicfab.eu/
  * Version: 5.2.0
  * NodeJS version: v16.20.1
  * Ffmpeg version: ffmpeg version 4.2.7-0ubuntu0.1

* Browser name, version and platforms on which you could reproduce the bug: Firefox, Brave, Safari, LibreoWolf
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Please correctly fill the bug template, in particular the `Link to server log` entry. Without logs we can't help.

**Comment by nicfab** [comment]
> Hello,
> 
> Please correctly fill the bug template, in particular the `Link to server log` entry. Without logs we can't help.

Thank you.
Unfortunately, I cannot retrieve the correct file with the error mentioned above.

**Comment by Chocobozzz** [comment]
Logs are also available in `Administration` -> `System` -> `Logs`. But let's use the forum instead to continue the discussion as it seems to be a sysadmin config issue: https://framacolibri.org/c/peertube
