### ISSUE TITLE
S3 Backend - Videos get deleted when switching private->public

### ISSUE THREAD

**Issue by normen** [Chocobozzz/PeerTube#5894]
### Describe the current behavior

Currently I am using Peertube with a Strato S3 backend and due to some incompatibility I am using `public-read` acls for private and public videos. When trying to use private acls I am running into an issue as described here: https://github.com/Chocobozzz/PeerTube/issues/5835#issuecomment-1597907245

While using public acls allows me to upload and view private videos in my library the same issue happens when I switch from private to public (or unlisted) - all files related to that video are deleted (exist but with 0 file size) on the S3 server.

### Steps to reproduce

1. Set S3 backend with `public-read` for both private and public videos
2. Upload a private video
3. View video - it is working and streaming from S3
4. Set the video to public or unlisted
5. Try to view video - it fails, the files stored on S3 are all 0 bytes in size

### Describe the expected behavior

The file on the S3 server shouldn't really be messed with when switching the accessibility and no acl changes occur.

### Additional information

* PeerTube instance:
  * URL: https://tube.bitwaves.de
  * Version: 5.2
  * NodeJS version: docker
  * Ffmpeg version: docker

* Browser name, version and platforms on which you could reproduce the bug: Safari 16
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

can you try to set `null` instead?: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L174 & https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L170

**Comment by normen** [comment]
Duh, he who can read has a clear advantage in life.. Thank you, that did the trick!
