### ISSUE TITLE
Remote avatars not loading

### ISSUE THREAD

**Issue by gianmarcogg03** [Chocobozzz/PeerTube#5895]
### Describe the current behavior

When I go to my subscriptions channel list, all the avatars are empty frames. The frames look similar to the ones in [issue 5001](https://github.com/Chocobozzz/PeerTube/issues/5001).

![immagine](https://github.com/Chocobozzz/PeerTube/assets/28053717/51322218-2605-4c3e-bd26-3fb46308f785)

### Steps to reproduce

1. Go to My library > Follows > Subscriptions

### Describe the expected behavior

The avatars should load.

### Additional information

* PeerTube instance:
  * URL: videos.gianmarco.gg
  * Version: 5.1.0
  * NodeJS version: 18.16.1
  * Ffmpeg version: 5.1.3

* Browser name, version and platforms on which you could reproduce the bug: Librewolf 115.0.1-1 (AUR)
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): [pt.log](https://github.com/Chocobozzz/PeerTube/files/12094424/pt.log)
* Extra note: this is running on a NixOS server

**Comment by Chocobozzz** [comment]
Hi,

Can you go inside your database and run

```
SELECT * FROM "actor" WHERE "url" = 'https://peertube.libresolutions.network/video-channels/lsn'
```

**Comment by gianmarcogg03** [comment]
The nginx configuration for the Peertube server is automated by the NixOS Peertube service, however I was able to extract the configuration with `cat /nix/store/3g8171ay4ylc2rhvdz6hr1rjr4w304pn-nginx.conf.drv | awk  '{gsub("\\\\n","\n")};1'`.

[ng.txt](https://github.com/Chocobozzz/PeerTube/files/12162439/ng.txt)

**Comment by Chocobozzz** [comment]
Hi,

The nginx configuration must not serve `lazy-static` paths. Please stick to the official nginx configuration: https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube
