### ISSUE TITLE
Following a closed issue but not resolved yet....

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5896]
### Describe the current behavior

from the issue https://github.com/Chocobozzz/PeerTube/issues/4929

@Chocobozzz 
how to set this tracker url on nginx/apache? what this tracker is done for?

thanks

**Comment by Chocobozzz** [comment]
Hello,

Please use the forum for PeerTube related questions: https://framacolibri.org/c/peertube

Unfortunately we don't have enough resources to also support apache.

**Comment by ROBERT-MCDOWELL** [comment]
@Chocobozzz 
I know that apache is not officially supported, no worries, but it's also doing it on nginx.
I just need to know what's this "tracker/socket" is done for thanks

**Comment by Chocobozzz** [comment]
It's for P2P

**Comment by ROBERT-MCDOWELL** [comment]
ok, I thought it was for torrent.. thanks!

**Comment by ROBERT-MCDOWELL** [comment]
btw @Chocobozzz I can say I support apache for Peertube since 1 years now.
You can add or not the config file in your github if you wish (once I'll resolve these last gliltches)
here is my repo https://gist.github.com/ROBERT-MCDOWELL/0ed82ec304fa76de9ff52cc4a5a49e4c

**Comment by ROBERT-MCDOWELL** [comment]
@Chocobozzz 
I cannot find a way to debug this connection issue (wss://xxx/track/socket) 
I try to directly test online a connection to the nodejs port 9000 (firewall open of course)
with https://www.piesocket.com/websocket-tester but no success. I have other project with nodejs, same apache configuration and I can connect. Any clue where I can find logs for this connection error?

**Comment by ROBERT-MCDOWELL** [comment]
@Chocobozzz 
ok everything has been fixed.
the apache configuration is tip top now...
https://gist.github.com/ROBERT-MCDOWELL/0ed82ec304fa76de9ff52cc4a5a49e4c
