### ISSUE TITLE
There is a suddenly error when uploading

### ISSUE THREAD

**Issue by imtube** [Chocobozzz/PeerTube#59]
Hello,
I met a error when I was uploading my 16th video, the before 15 videos are all right.
the error is :
`POST https://xxx.com/api/v1/videos net::ERR_CONTENT_LENGTH_MISMATCH`

I'm using Chinese title and description as same as the other 15 videos. then I tried two more videos, and met the same error. Then I rebooted the server and restarted peertube, still got the same error.
Please help me, I'm using it for production, This is the log file in case you need it
[log.txt](https://github.com/Chocobozzz/PeerTube/files/899696/log.txt)

**Comment by imtube** [comment]
@Chocobozzz Is there any possible that there will be some error when upload many videos ?

**Comment by Chocobozzz** [comment]
I don't see errors in the log, only 401 HTTP status (bad token) when you upload a video. I don't know why you have this `net::ERR_CONTENT_LENGTH_MISMATCH` error.

**Comment by imtube** [comment]
@Chocobozzz thank you!, I don't know why, but it's normal again after I relogin.
