### ISSUE TITLE
QoL features (Ongoing)

### ISSUE THREAD

**Issue by SventuraOscura** [Chocobozzz/PeerTube#5901]
### Describe the problem to be solved

1° Problem)
For users that have a huge amount of videos, you need to manually click each one in the section "my videos" if you want to delete them, it takes a huge amount of time, and there is a simpler approach (with a little modification)

2° Problem)
There is no web-access to the database that manages the videos , want to copy paste all the links of a conference/anime/video collection? good luck copy-pasting each one of them it takes forever!, want to delete them, or apply a query to apply massive modifications? you can't do that, if you are not good using CLI commands (and the average user will cause more trouble than anything, like me!). Also, when you upload video files, the orginal filename isn't preserved, so, you don't actually know how the filename is called, if you don't access ftp, and check manually each one of them (they are random numbers/letters).
![random gibberish](https://github.com/Chocobozzz/PeerTube/assets/124525552/abff62d4-f5bd-467c-833b-5efc907b1033)

Ongoing...

### Describe the solution you would like

Solution to problem 1)
Add a "select all" option, in the "my videos" page, similar to the media library of wordpress, with a max amount of selectable files (to avoid server overload, the amount should be changeable if possible)
![Qol 1 original](https://github.com/Chocobozzz/PeerTube/assets/124525552/6b88590c-7e7d-4465-b507-7b0e29d64822)
![Qol 1 epic modification](https://github.com/Chocobozzz/PeerTube/assets/124525552/a7784adb-f1eb-4381-82c7-ab25b1ff6e3d)

Solution to problem 2)
Simply a grid-like access dashboard to the database, you would see "video titles","video filename name" "video link" "video description" "video captions" and so on. kinda like to Mysql, easier, and, in this interface you should be also able to "clean" or "delete" informations about a video, so no more "error 500 unknown file" or similar things. For example, if my video fails to load due to internet connection, i need to manually access FTP to delete cache files, or, if i don't do that, the failed upload still takes up space...
![Qol 2](https://github.com/Chocobozzz/PeerTube/assets/124525552/3aaeba59-7c21-4240-a6a5-7ca82c85dcaa)

**Comment by vid-bin** [comment]
Why are you comparing this to phpmyadmin when you should be using pgadmin for postgresql?

**Comment by vid-bin** [comment]
Infact I just went through the trouble of setting this up on my end and the data you're asking for is already in the video table.

**Comment by Chocobozzz** [comment]
Thanks for this issue. Merging it into https://github.com/Chocobozzz/PeerTube/issues/5505

**Comment by SventuraOscura** [comment]
@vid-bin is just for visuals, so is more clear as example, i think you noticed i am a newbie. Also, what do you mean postgresql?, does peertube uses that?, i know for sure that uses redis, but not postgresql...

**Comment by vid-bin** [comment]
> @vid-bin is just for visuals, so is more clear as example, i think you noticed i am a newbie. Also, what do you mean postgresql?, does peertube uses that?, i know for sure that uses redis, but not postgresql...

You can download pgadmin for windows which will run like an application, setup the postgresql database on the peertube server to accept remote connections and connect that way. Easy to do and not complicated.

Most of what you're asking for in #2 is already in the video table on the database.

Yes peertube uses postgresql.
