### ISSUE TITLE
Settings translations breaks links

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#5905]
### Describe the current behavior

In the livechat plugin settings, I have a link to the documentation:

![image](https://github.com/Chocobozzz/PeerTube/assets/38844060/b2b4f68a-c679-4dc6-929a-07f8dae9ebd9)

This works perfectly fine in english.

But if i'm in french (for example), the link in marked "unsafe" and won't work:

![image](https://github.com/Chocobozzz/PeerTube/assets/38844060/10c4f1ae-753c-41eb-9741-5c39a4adce82)

This paragraph is generated using:

```
registerSetting({
    type: 'html',
    private: true,
    descriptionHTML: `You can find the plugin documentation here: <a href="https://livingston.frama.io/peertube-plugin-livechat/" target="_blank"> Peertube Plugin Livechat documentation </a>.`
  })
```

### Steps to reproduce

1. install livechat plugin
2. set interface language to french
3. go to the settings page
4. try to click on the link to the documentation

### Describe the expected behavior

The link should not be modified when translated.

### Additional information

* PeerTube instance:
  * Version: 5.2.0

**Comment by Chocobozzz** [comment]
Hi,

There is an extra (invalid) space in the french translation after `https`

**Comment by JohnXLivingston** [comment]
Oops!
Sorry, don't know how i missed it. Thanks :)
