### ISSUE TITLE
Split video between peertube runners

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#5906]
### Describe the problem to be solved

Videos are currently sent to peertube runners whole.

### Describe the solution you would like

Allow video frames to be split up between runners  (runner 1 handles frames 1-50, runner 2 handles frames 50-100 and so on) to achieve faster transcoding. Then have the main peertube server put the video back together and publish it.

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue but it's out of the scope of the PeerTube project. You can however create your own runner that would have such strategy with sub-runners.
