### ISSUE TITLE
Player does not automatically adjust video playback quality

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#5907]
### Describe the current behavior

With my current setup video quality remains at 480p and does not automatically adjust quality.

This happens regardless on if AV1 is the only format or if it's mixed in with h264.

The only error I see is the below one, which occurred when manually changing quality (which worked):

`Client log: HLS.js error: mediaError - fatal: false - bufferStalledError `

Master.m3u8:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=1376372,RESOLUTION=854x480,FRAME-RATE=60,CODECS="avc1.64001f,mp4a.40.2"
3c693d2b-89ce-462e-bc64-bb54eaa1d555-480.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3068680,RESOLUTION=1280x720,FRAME-RATE=60,CODECS="av01.0.08M.08,opus"
c1b402b2-98d0-412d-8670-88165cff5036-720.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=6067167,RESOLUTION=1920x1080,FRAME-RATE=60,CODECS="av01.0.09M.08,opus"
567ee5ec-799e-40ee-a563-654dd0240a12-1080.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=10122746,RESOLUTION=2560x1440,FRAME-RATE=60,CODECS="av01.0.12M.08,opus"
77f943fa-c156-4761-a9d6-c05e79d1576b-1440.m3u8
```

### Additional information

* PeerTube instance:
  * Version: 5.2.0
  * NodeJS version: 20.3.1
  * Ffmpeg version: git

* Browser name, version and platforms on which you could reproduce the bug: Firefox, no errors in console.

**Comment by vid-bin** [comment]
The only odd thing is bitdepth in the master.m3u8 is saying 8bit when the AV1 videos are 10bit (yuv420p10le) perhaps thats the issue.

**Comment by vid-bin** [comment]
You can see this here: https://vidbin.org/w/3gnRtTn7qnrUG4pz4XmeHr

**Comment by Chocobozzz** [comment]
Thanks for the video link. I think it's a hls.js issue as you can see the same behaviour on their official demo: https://hlsjs.video-dev.org/demo/?src=https%3A%2F%2Fvidbin.org%2Fstatic%2Fstreaming-playlists%2Fhls%2F1257e6bd-aedf-4c05-bf31-c2582792c967%2F5988e183-0de3-4ca9-8600-19d6da808c65-master.m3u8&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOnRydWUsInN0b3BPblN0YWxsIjpmYWxzZSwiZHVtcGZNUDQiOmZhbHNlLCJsZXZlbENhcHBpbmciOi0xLCJsaW1pdE1ldHJpY3MiOi0xfQ==

Please open the issue on their side (the root cause of the issue is probably the mixed codecs in the master playlist)

**Comment by vid-bin** [comment]
I opened up a report over on their github.

I have replicated this in the past with just AV1. I know in the past hls.js has had issues with opus audio, so maybe thats the source of the problem.

**Comment by vid-bin** [comment]
@Chocobozzz Can you point out where these options are in peertubes source code so I can modify and try them out?

Thanks!

https://github.com/video-dev/hls.js/issues/5708#issuecomment-1656757907

https://github.com/video-dev/hls.js/pull/5704

**Comment by Chocobozzz** [comment]
You can find hls.js options here: https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/assets/player/shared/player-options-builder/hls-options-builder.ts
