### ISSUE TITLE
Generate bigger actor avatars

### ISSUE THREAD

**Issue by Agorise** [Chocobozzz/PeerTube#5908]
### Describe the problem to be solved

Podcast RSS 2.0 feeds have been added to Peertube v5.2. That's great, but Apple will never feature your podcast on their iTunes homepage unless you have cover art that is 1400x1400 px in size (they recommend 3000x3000 for retina displays). 
https://help.apple.com/itc/podcasts_connect/#/itcb54353390 
![itunes:image_requirement](https://github.com/Chocobozzz/PeerTube/assets/31280836/2001aee9-b52e-4a9c-80bc-ab521d4bf518) 
 
Example Podcast RSS 2.0 audio-only podcast feed: 
https://validator.w3.org/feed/check.cgi?url=https://cast.garden/feeds/podcast/videos.xml?videoChannelId=37
https://podba.se/?url=https://cast.garden/feeds/podcast/videos.xml?videoChannelId=37
https://www.castfeedvalidator.com/validate.php?url=https://cast.garden/feeds/podcast/videos.xml?videoChannelId=37 
As you can see, the RSS Validators do not like the tiny cover art. 
 
Right now, we always upload a 192x192 channel avatar image, but that needs to allow for jpg/png images up to 3000x3000.

**Comment by Mike35538** [comment]
I agree the avatar images are too small, hopeful this can eventually be fixed. In addition to the issue with Podcast RSS 2.0, the tiny channel avatars and account avatars make it very difficult to share those pages on social media. #5077

**Comment by Agorise** [comment]
More bad news: Apple Podcasts are now BLOCKING all podcasts/videos unless you use a channel avatar that is at least 1400x1400, but they really push the 3000x3000 size since that is what their new retina displays promote. (no agenda there lol) 
 
Please allow us to upload channel avatar images as large as 3000x3000 png/jpg

**Comment by Agorise** [comment]
I made a nice colorful 3000x3000 image and it was a ridiculous 2.8MB. I used tinypng.com on that image though and reduced its filesize to 944K. Tinify offers that compression as a free add-on so if @Chocobozzz and Team can add the ability to upload channel avatars as large as 3000x3000 it would be reeeeeally nice if you could also add tinify compression at the same time: 
https://github.com/tinify/tinify-nodejs 
 
I've been using tinypng.com and tinyjpg.com for years and their compression is outstanding and I see no difference in image quality.

**Comment by dhk2** [comment]
One of the design goals of the podcast2 plugin is to resolve this registration issue. currently passes the validator.

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fmusic.freediverse.com%2Fplugins%2Fpodcast2%2Frouter%2Fpodcast2%3Fchannel%3Dtomlehrer

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/109e93c139d87fb73d7bd9597852ac5f856b8018 where we now generate `600x600` and `1500x1500` avatars.
