### ISSUE TITLE
Mistranslation of description about CC BY-ND in Japanese

### ISSUE THREAD

**Issue by sorairolake** [Chocobozzz/PeerTube#5909]
### Describe the current behavior

The current current Japanese translation is correct as the description of CC BY-NC-ND, but incorrect as the description of CC BY-ND. Because "非営利" means "NonCommercial" in English, but this is not included in the terms of CC BY-ND.

<https://github.com/Chocobozzz/PeerTube/blob/89aa3331106874266f6feeee7bff852da2c1727e/client/src/locale/server.ja-JP.json#L22>

### Steps to reproduce

1.
2.
3.

### Describe the expected behavior

"CC BY-ND (作品を複製、頒布、展示、実演を行うにあたり、著作権者の表示を要求し、いかなる改変も禁止する)"

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

Thanks! Translations are made by the community, so you can change it directly on https://weblate.framasoft.org/translate/peertube/server/ja/?q=Attribution+-+No+Derivatives&sort_by=-priority%2Cposition&checksum= :)

**Comment by sorairolake** [comment]
@Chocobozzz Thanks! I translated this.
