### ISSUE TITLE
Wide screen content (21:9) has black bars on both horizontal and vertical axis

### ISSUE THREAD

**Issue by SethFalco** [Chocobozzz/PeerTube#5915]
### Describe the current behavior

PeerTube supports content as a variety of aspect ratios, and works flawlessly for aspect ratios of 1.78 (16:9) or below. However, content that has a higher aspect such as 2.33 (21:9) gets black bars on both axis.

Note that the issue is with the player styles, and not the video itself.

![](https://github.com/Chocobozzz/PeerTube/assets/22801583/af0d976b-8810-4923-a5af-7e84df6cb2b9)
> A 21:9 video uploaded on a local PeerTube instance, and being viewed on a 21:9 display. Observe that there are both horizontal and veritcal black bars.

### Steps to reproduce

1. Publish a video at an aspect ratio higher than 1.78, for example, a 21:9 video. (Sample file provided.)
2. View the published video on PeerTube.

https://github.com/Chocobozzz/PeerTube/assets/22801583/b1870340-5d61-4aa4-87e1-1d1b75558bac

### Describe the expected behavior

There should always only be one set of black bars, either horizontal or vertical, to best make use of the space available.

### Additional information

* PeerTube instance:
  * URL: N/A
  * Version: `04d1da5` (`develop` at time of posting this issue)
  * NodeJS version: v18.16.0
  * Ffmpeg version: 5.1.3-1

* Browser name, version and platforms on which you could reproduce the bug: Firefox 115, Debian 12
* Link to browser console log if relevant: N/A
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): N/A

**Comment by vid-bin** [comment]
Can we also have a third option for a 1:1 of the video being played?

It's size dependent but when on a 4k monitor I'd like to watch 1080p without stretching the video. This is especially true for 480p/720p.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/8e4fba97b26090e0c77ee9591058cd34ef9d2f55

Feedback are welcomed :)

**Comment by SethFalco** [comment]
LGTM! Thanks for resolving this. :+1:

**Comment by SethFalco** [comment]
@Chocobozzz 

Hmm… actually something is wrong here.
I tested this earlier and I thought it was fine, but it could be I wasn't running the right commit. :thinking: 

I've tested this again with cb909ab38a6a176edce53043bcfcec8ca2f156fb and this is _not_ resolved. 

![image](https://github.com/Chocobozzz/PeerTube/assets/22801583/bbe2e107-d07e-44bd-acca-11a851544613)
> Normal video player (should only have single black bars)

![image](https://github.com/Chocobozzz/PeerTube/assets/22801583/4dbc82c1-6e6c-4e3e-a539-5b6375af6364)
> Theatre video player (should only have single black bars)

![image](https://github.com/Chocobozzz/PeerTube/assets/22801583/a99ad90e-62fb-4f31-9e0a-5454738338ec)
> Fullscreen video player :heavy_check_mark:

**Comment by Chocobozzz** [comment]
I'm surprised about this behaviour on your local computer, can you confirm on https://peertube2.cpy.re/w/wf1UJjft81nWG2fWSFfcKS?

**Comment by SethFalco** [comment]
Hmm, it runs perfectly there on the instance you've provided.

I've attempted to reproduce the issue again with my local machine using 69601b66feaeb6e508fffe5f7b4c31ccb8a79bb9 (`develop` at the time of this comment).

While the video is still transcoding, it runs exactly as expected.  
Once the video has finished transcoding, the issue with two black bars returns.

![image](https://github.com/Chocobozzz/PeerTube/assets/22801583/d2e4bb96-1841-42ae-83dc-d548e94eaf9a)
> Video while it is still being transcoded.

![image](https://github.com/Chocobozzz/PeerTube/assets/22801583/6a85f21b-cd56-4fa5-8b05-864576b91ed4)
> I spammed refresh until the transcoding warning disappeared, which the issue then immediately occurs.

**Comment by Chocobozzz** [comment]
The transcoded version still has the correct ratio? Can you share it?

**Comment by Chocobozzz** [comment]
I'm sorry but I don't know what happens. It's difficult to debug your issue since it's on your local computer. I suggest to wait the next pre-release so you can test on a production server. Then I would be able to reproduce using your public video URL.
