### ISSUE TITLE
Peertube reports incorrect FPS @ 480p

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#5919]
### Describe the current behavior

When encoding a 1080p @ 60 FPS video peertube reports the 480p version @ 30 FPS during encode.

![firefox_2VF4XBMPPI](https://github.com/Chocobozzz/PeerTube/assets/112714131/edab13be-912a-464c-b8b6-dfa38d135de1)

However, the final 480p video is correctly encoded at 60 FPS.

Because of this bug the 480p version of this video will go through my custom coded profiles @ 30FPS instead of 60, resulting in lower bitrate.

### Describe the expected behavior

Peertube properly reports 480p output at 60 FPS during encode so it goes to the correct profile.

### Additional information

* PeerTube instance:
  * Version: 5.2.0
  * NodeJS version: 20.5.0
  * Ffmpeg version: git

**Comment by vid-bin** [comment]
The only thing my custom code does is choose which transcoding profile to use. So if the 480p video is supposed to only be encoded in 30 FPS and this is intended behavior it does not work with the transcoding-profile-debug plugin as the video is @ 60 FPS.

**Comment by Chocobozzz** [comment]
Hi,

PeerTube chooses and specifies the fps value to the transcoding profile. See https://github.com/Chocobozzz/PeerTube/issues/3036 to adapt fps depending on the resolution.

**Comment by vid-bin** [comment]
Right I don’t care that it’s supposed to be 30fps. The problem is that with transcoding-profile-debug it’s transcoded at 60fps instead of 30.

It’s a bug with transcoding profile debug.

**Comment by vid-bin** [comment]
Basically peertube calls for 30fps and transcoding profile debug laughs and does 60 anyway.

**Comment by vid-bin** [comment]
I'll try testing this on a vanilla install at some point over the weekend but all my custom code should do is select what profile to transcode in. And the profile doesn't determine what FPS the video is transcoded at.
