### ISSUE TITLE
Clarify public admin E-Mail address

### ISSUE THREAD

**Issue by Findus23** [Chocobozzz/PeerTube#5920]
### Describe the problem to be solved

I recieved a SPAM mail to my personal E-Mail address which mentioned that they found it at https://mypeertube.example/.well-known/security.txt .

And indeed the security.txt mentions `Contact: mailto:theaddress@example.com`. Which makes sense, so that there is a way to contact the instance admin in case of an security issue. But I didn't consider this when I created the instance and used my personal E-Mail address instead of a public one for the admin account.
So it would be great if this fact could be documented more clearly.

Also the account page mentions `It is never shown to the public.` even when the user is the admin account.

![grafik](https://github.com/Chocobozzz/PeerTube/assets/6266037/044ba408-6563-44ad-8aea-5c859dbdfe5d)

I just realized that this is caused by the admin setting, so maybe that's the best place to document this fact:

https://github.com/Chocobozzz/PeerTube/blob/b4516abc392ed2b38cb7b587929a9249ddeb2b30/config/production.yaml.example#L410-L413

### Describe the solution you would like

Give peertube admins a heads-up that logged out users can see their admin E-Mail address.

**Comment by Chocobozzz** [comment]
Hi,

Sorry about that. We also received this email :/ I'll add an option in the next version below the `email` configuration to enable/disable email injection in security.txt. FYI the admin email is also publicly available in the config API endpoint. I'll also add a configuration to disable this behaviour too.

**Comment by JohnXLivingston** [comment]
Hello,

Instead of the email, you could also use the contact form url if enabled.

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/822872aacdd763988cb9e81cdcc3576178993b74
