### ISSUE TITLE
Schedule when a video or stream goes live

### ISSUE THREAD

**Issue by Rylan-Meilutis** [Chocobozzz/PeerTube#5921]
### Describe the problem to be solved

When publishing a video. It publishes the moment it finishes transcoding. It would be nice to be able to pick a time and have the video go live at or after that time

### Describe the solution you would like

When publishing a video, there could be an option to pick a time to schedule when it goes live. After uploading the video would transcode and then go into the users private videos. When the selected time arrives, the video would get switched to either public or unlisted.

**Comment by Chocobozzz** [comment]
Hello,

You have a `Scheduled` video privacy when you upload the video: https://docs.joinpeertube.org/use/create-upload-video#video-confidentiality-options-what-do-they-mean

**Comment by Rylan-Meilutis** [comment]
I missed that option. Thanks.

**Comment by fabiopicchi** [comment]
Sorry for maybe reopening this issue, but another use case would be to show in the main UI, to the viewers, that a certain video will be published at a certain time. For now, the video remains private/hidden until the scheduled time.

It would be nice to have this scheduling feature for live streams as well.
