### ISSUE TITLE
some GUI elements are unreadable using the "Dark" theme

### ISSUE THREAD

**Issue by YourAutisticLife** [Chocobozzz/PeerTube#5922]
### Describe the current behavior

When I want to upload a new video or edit an old one:

1. The list of tags is unreadable. The text looks like it is white on a very pale salmon. No contrast at all.

2. The dropdown menus like the "Language" menu suffer from the same problem. No contrast.

(I tried to upload screenshots, but github made it difficult, so I gave up.)

### Steps to reproduce

1. Set the theme to "Dark."
2. Upload a new video or edit a new one. 
3. Insert some tags: unreadable.
4. Look at the drop down menus: unreadable.

### Describe the expected behavior

A readable UI.

### Additional information

* PeerTube instance:
  * URL: https://spectra.video/
  * Version: 5.2.0
  * NodeJS version: No clue where to find this.
  * Ffmpeg version: No clue where to find this.

* Browser name, version and platforms on which you could reproduce the bug: Chrome 115.0.5790.170 (Official Build) (64-bit) on Debian 12
* Link to browser console log if relevant: not relevant.
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): not relevant.

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue but the bug has been fixed in the dark theme (v2.5). Please ask your admin to update the theme :)

**Comment by YourAutisticLife** [comment]
Will do. Thanks!
