### ISSUE TITLE
Live is not working, missing EXT-X-STREAM-INF

### ISSUE THREAD

**Issue by normen** [Chocobozzz/PeerTube#5923]
### Describe the current behavior

Sometimes live streams won't play on the client side, I see a spinning wait symbol while the .ts segments still seem to be loaded in the background, I see them in the browser debug tool and in the bandwidth use of my server.

On my instance transcoding is disabled for live streams. When this problem occurs the `master.m3u8` is missing the `#EXT-X-STREAM-INF` entry, it seems that the ffprobe task fails. In the log I see that when the playlist is created it says the bandwidth being set to `NaN` so I suppose the `ffprobe` command went wrong somehow?

This happens with streams from OBS and from other apps, seemingly randomly.

### Steps to reproduce

1. Create a live without transcoding
2. Stream from any source (OBS etc.)
3. See the `master.m3u8` is missing the `EXT-X-STREAM-INF` entry
4. See that the replay is saved and plays fine.

### Describe the expected behavior

The playlist should contain the `EXT-X-STREAM-INF` entry.

### Additional information

* PeerTube instance:
  * URL: https://tube.bitwaves.de
  * Version: 5.2
  * NodeJS version: docker
  * Ffmpeg version: docker
  * S3 Backend Enabled

* Browser name, version and platforms on which you could reproduce the bug: MacOS
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Ping @normen :)
