### ISSUE TITLE
Video Import - Support Comments

### ISSUE THREAD

**Issue by upintheairsheep** [Chocobozzz/PeerTube#5925]
### Describe the problem to be solved

Importing videos from external platforms via YT-DLP supports extracting comments for YouTube and a few other sites. Comments (as well as replies) should be imported optionally as comments to the video, with “ghost accounts” which correspond to a YouTube or any other service account like @youtube@youtube.com creating the comment for example.

### Describe the solution you would like

See above

**Comment by dhk2** [comment]
Due to the lack of a way to get consent from commenters to have their words duplicated on a different platform, I'd have to advise against this feature.

**Comment by rasos** [comment]
We are in the situation to migrate our own channel where mostly users from our own community have commented. The risk is low to get an objection and if somebody claims not having given consent there is an abuse button and the comment could be deleted by an admin. Especially if the video has been published on YT under a CC license, one could even say that the video plus the comments is a derivative under the same license.

**Comment by vid-bin** [comment]
> the comments is a derivative under the same license.

explain your logic

**Comment by Chocobozzz** [comment]
Hello,

Thanks for the issue but importing comments from an external platform is out of the scope of PeerTube.
