### ISSUE TITLE
Chunked uploads

### ISSUE THREAD

**Issue by Rylan-Meilutis** [Chocobozzz/PeerTube#5926]
### Describe the problem to be solved

I would like to have my instance behind cloudflare for many reasons, however this limits upload file sizes to 100mb at max.

### Describe the solution you would like

Sites like nextcloud use chunked uploads, which get around this limitation by uploading the source video in multiple smaller parts. If this is possible with PeerTube it would be very helpful.

**Comment by Chocobozzz** [comment]
Hello,

PeerTube already uses chunked uploads: PeerTube/blob/develop/config/production.yaml.example#L848
