### ISSUE TITLE
Buffer animation circle in video player never disappears on Chrome

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5927]
### Describe the current behavior

this new issue is on chrome 115.0.5790.171 only, does not appear on firefox nor edge.

whatever I play, scrub, forward or rewind, the wait cicle never disappear. no javascript errors.
on the stats nerd, the buffer progress reaches a max of 1.6%, maybe is it the issue?

**Comment by Chocobozzz** [comment]
Can you try with chrome 116?

**Comment by ROBERT-MCDOWELL** [comment]
@Chocobozzz 
with v116 sometimes it disappears, sometimes not.... :-\

**Comment by Chocobozzz** [comment]
Please provide web browser logs

**Comment by ROBERT-MCDOWELL** [comment]
nothing special in logs...
[txt.log](https://github.com/Chocobozzz/PeerTube/files/12379867/txt.log)

**Comment by wiwikuan** [comment]
I can confirm this issue with the buffer spinner when using Brave browser version 1.57.53 (Chromium: 116.0.5845.114). While the video plays correctly, the buffer spinner remains on screen and doesn't disappear. I noticed this problem today, likely after an automatic update from Brave. Notably, this issue does not occur when I use Firefox.

As a temporary solution, I've implemented the following workaround in my custom CSS settings:

```
.vjs-loading-spinner {
    display: none !important;
}
```

**Comment by ROBERT-MCDOWELL** [comment]
@wiwikuan thanks to share your CSS

**Comment by kontrollanten** [comment]
We've the same issue in 5.1.0.

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue.

Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/e23b95a901819fecc69b47ac83b3b3ce1b0037e3

**Comment by Chocobozzz** [comment]
Released in 5.2.1: https://github.com/Chocobozzz/PeerTube/releases/tag/v5.2.1
