### ISSUE TITLE
Cannot load heavy videos

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#593]
* **PeerTube version or URL:** 1.0.0b6 / https://skeptikon.fr/
* **Browser name/version:** Firefox Nightly 62.0a1 (2018-05-26) (64-bit)
* **NodeJS version:** v8.11.2

When I open an heavy video (I don't have a precise criterion of what is "heavy", sorry), the video doesn't start.
Some videos on which I encounter the issue:
 - https://skeptikon.fr/videos/watch/90f05567-647a-4dae-bbc8-851b516fd702
 - https://skeptikon.fr/videos/watch/5a997d02-8b84-4667-8e4f-e649cb1a6999
 - and lots more (often videos > 30 min and in 1080p)

I note that I am not the only one. More interestingly, I notice that on peertube.mastodon.host (v1.0.0b6), one of the heavy video cannot be loaded:
 - https://peertube.mastodon.host/videos/watch/5bf53f72-b32f-4052-8585-ba2b28b38d08

Whereas on the original server (1.0.0b4) the same video can be played:
 - http://videos.lecygnenoir.info/videos/watch/5bf53f72-b32f-4052-8585-ba2b28b38d08

However, I don't know what is the precise criterion that causes the issue.

Note that I encountered the issue since I upgraded the server from 1.0.0b4 to 1.0.0b6 (and pulled the latest traefik, redis, and postgres docker images). Also I have made some hacks on the server, but I am not convinced that's the reason of the issue. I can explain what I did if you request it.

But my question is rather the following: do you have any idea on how to diagnose the issue?

* **What is the expected behaviour?** The videos can be played
* **What do you see instead?** The videos are not played immediately

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

**Comment by Chocobozzz** [comment]
I think it is a transcoding issue. Try to reupload the videos with transcoding enabled to see if it fails or not.

**Comment by fflorent** [comment]
I have rather pushed a new job using the API of the [kue dashboard](https://github.com/Automattic/kue#post-job), with this script : 
```bash
$ node node_modules/kue/bin/kue-dashboard -p 3050 -q q-skeptikon.fr -r redis://redis:6379
$ curl -H "Content-Type: application/json" -X POST -d     "{ \
		\"type\": \"video-file\", \
		\"data\": { "videoUUID": "d037b940-7456-4441-b982-1d63f206f9df" }, \
		\"options\" : { \
			\"attempts\": 5, \
			\"priority\": \"high\" \
		}}" http://localhost:3050/job
```

If I am good, this should transcode as if I reuploaded the video. What do you think?

**Comment by fflorent** [comment]
This worked pretty well for this video: https://skeptikon.fr/videos/watch/d037b940-7456-4441-b982-1d63f206f9df

Let's see with others. Thanks @Chocobozzz! I close the issue.
