### ISSUE TITLE
x264 switch x265 or AV1

### ISSUE THREAD

**Issue by filmaidykai** [Chocobozzz/PeerTube#5932]
### Describe the problem to be solved

I tried to find something, but no one seems to have talked about it so why no one is talking about at least x265 possibility yet?

### Describe the solution you would like

I think x265 requires less storage space, required less traffic and the video quality would be better

**Comment by ROBERT-MCDOWELL** [comment]
x265 is still not became web browser standard

**Comment by filmaidykai** [comment]
> x265 is still not became web browser standard

don't say drastically, there are browsers that support it
Chrome (version 107 and higher)
Microsoft Edge
Internet Explorer – Ideal for those who still prefer this browser
[Safari desktop]– Apple’s Safari browser
[Safari on iOS]

**Comment by ROBERT-MCDOWELL** [comment]
mozilla browsers still not.

**Comment by ROBERT-MCDOWELL** [comment]
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs

**Comment by vid-bin** [comment]
> ###
> 
> I tried to find something, but no one seems to have talked about it so why no one is talking about at least x265 possibility yet?

x265 does work when using a custom transcoding profile. I tested this back on version 4. It will direct play.

**Comment by vid-bin** [comment]
And AV1 is fully supported when using a custom transcoding profile. Everything works.

If you want x265 to do more then direct play you will need to open an issue on the hls.js github.

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue but we prefer to stick with x264 for now as it's the most supported codec.

**Comment by vid-bin** [comment]
Wanted to quickly add after experimenting with HEVC it appears to be fully supported now and working with hls.
