### ISSUE TITLE
Peertube failing to start after Debian dist-upgrade

### ISSUE THREAD

**Issue by asterismo** [Chocobozzz/PeerTube#5934]
### Describe the problem

Peertube won't start, this is the log, web gives error 502

ago 12 15:58:19 debian12 systemd[1]: Started peertube.service - PeerTube daemon.                                                              
ago 12 15:58:20 debian12 peertube[210703]: > peertube@5.0.0 start                                                                             ago 12 15:58:20 debian12 peertube[210703]: > node dist/server                                                                                 
ago 12 15:58:24 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:24.226 info: Using following configuration file hierarchy: /media/peertube/config/default.yaml -> /media/peertube/config/local-production.json.                                                            ago 12 15:58:24 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:24.880 info: Database peertube_prod is ready.              
ago 12 15:58:25 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:25.218 info: Connecting to redis...                        
ago 12 15:58:25 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:25.226 info: Using mail.mail.com:587 as SMTP server.    
ago 12 15:58:25 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:25.230 info: Testing SMTP server...                        ago 12 15:58:25 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:25.359 info: Connected to redis.
ago 12 15:58:25 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:25.833 info: Connection established to 185.101.93.79:587 { ago 12 15:58:25 debian12 peertube[210737]:   "component": "smtp-connection",                                                                  
ago 12 15:58:25 debian12 peertube[210737]:   "sid": "mbsQk4KBRlc",                                                                            ago 12 15:58:25 debian12 peertube[210737]:   "tnx": "network",                                                                                
ago 12 15:58:25 debian12 peertube[210737]:   "localAddress": "192.168.1.166",                                                                 ago 12 15:58:25 debian12 peertube[210737]:   "localPort": 50080,                                                                              
ago 12 15:58:25 debian12 peertube[210737]:   "remoteAddress": "185.101.93.79",                                                                ago 12 15:58:25 debian12 peertube[210737]:   "remotePort": 587                                                                                
ago 12 15:58:25 debian12 peertube[210737]: }                                                                                                  ago 12 15:58:27 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:27.556 info: Connection upgraded with STARTTLS {
ago 12 15:58:27 debian12 peertube[210737]:   "component": "smtp-connection",                                                                  ago 12 15:58:27 debian12 peertube[210737]:   "sid": "mbsQk4KBRlc",
ago 12 15:58:27 debian12 peertube[210737]:   "tnx": "smtp"                                                                                    ago 12 15:58:27 debian12 peertube[210737]: }                                                                                                  
ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.295 info: User "peertube@mail.com" authenticated {      ago 12 15:58:28 debian12 peertube[210737]:   "component": "smtp-connection",                                        
ago 12 15:58:28 debian12 peertube[210737]:   "sid": "mntrogedr4Rou",                                                                            ago 12 15:58:28 debian12 peertube[210737]:   "tnx": "smtp",
ago 12 15:58:28 debian12 peertube[210737]:   "username": "peertube@mail.com",                                       
ago 12 15:58:28 debian12 peertube[210737]:   "action": "authenticated",                                                                       ago 12 15:58:28 debian12 peertube[210737]:   "method": "PLAIN"
ago 12 15:58:28 debian12 peertube[210737]: }                                                                                                  ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.297 info: Successfully connected to SMTP server.
ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.307 info: Running RTMP server on port 1935              ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.522 info: Connection closed {
ago 12 15:58:28 debian12 peertube[210737]:   "component": "smtp-connection",                                                                  
ago 12 15:58:28 debian12 peertube[210737]:   "sid": "mbsQk4KBRlc",                                                                            ago 12 15:58:28 debian12 peertube[210737]:   "tnx": "network"                                                                                 
ago 12 15:58:28 debian12 peertube[210737]: }                                                                                                  ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.861 info: Registering plugin or theme peertube-theme-bit
tube-dark-mode.                                                                                                                                 
ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.873 info: Cleaning HTML cache.                          ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.873 info: Registering plugin or theme peertube-theme-dar
k.                                                                                                                                              ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.874 info: Cleaning HTML cache.
ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.874 info: Registering plugin or theme peertube-plugin-au
to-mute.                                                                                                                                        
ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443 peertube-plugin-auto-mute] 2023-08-12 15:58:28.890 info: Do not load auto mut
e plugin because of empty blocklist URLs.                   
ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.891 info: Add plugin peertube-plugin-auto-mute CSS to global file.                                                                                                                                      
ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.891 info: Cleaning HTML cache.       
ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.892 info: Registering plugin or theme peertube-plugin-social-sharing.                                                                                                                                   ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.898 info: Add plugin peertube-plugin-social-sharing CSS to global file.                                                         
ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.902 info: Added locale fr-FR of plugin peertube-plugin-s
ocial-sharing.                                                          
ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.902 info: Added locale gd of plugin peertube-plugin-soci
al-sharing.                                                                                                                                     
ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.902 info: Added locale sv-SE of plugin peertube-plugin-s
ocial-sharing.

ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.902 info: Added locale sv-SE of plugin peertube[65/1232]ocial-sharing.
ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.903 info: Cleaning HTML cache.                          ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.903 info: Registering plugin or theme peertube-plugin-hi
de-channels-in-search-result.                                                                                                                   ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.909 info: Add plugin peertube-plugin-hide-channels-in-se
arch-result CSS to global file.                                                                                                                 ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.909 info: Cleaning HTML cache.
ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.909 info: Registering plugin or theme peertube-plugin-background-play.                                                                                                                                  ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.915 info: Add plugin peertube-plugin-background-play CSS
 to global file.                                                                                                                                
ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.916 info: Cleaning HTML cache.                       
ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.916 info: Registering plugin or theme peertube-plugin-categories.
ago 12 15:58:28 debian12 peertube[210737]: Response ended:                                                                                    ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.956 info: Add plugin peertube-plugin-categories CSS to g
lobal file.                                                                                                                                     ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.958 info: Added locale fr-FR of plugin peertube-plugin-c
ategories.                                                                                                                                      ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.959 info: Added locale en-US of plugin peertube-plugin-c
ategories.                                                                                                                                      ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.959 info: Cleaning HTML cache.
ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.959 info: Registering plugin or theme peertube-plugin-creative-commons.
ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.968 info: Add plugin peertube-plugin-creative-commons CSS to global file.
ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.968 info: Cleaning HTML cache.                          ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.968 info: Registering plugin or theme peertube-theme-rea
litytube-dark.                                                                                                                                  ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.969 info: Cleaning HTML cache.
ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.970 info: Registering plugin or theme peertube-theme-kamerton-dark.
ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.970 info: Cleaning HTML cache.
ago 12 15:58:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:28.970 info: Registering plugin or theme peertube-plugin-livechat.        
ago 12 15:58:29 debian12 peertube[210737]: [peertube.mydomain.com:443 peertube-plugin-livechat] 2023-08-12 15:58:29.044 info: Checking if there is a migration script to launch...
ago 12 15:58:29 debian12 peertube[210737]: [peertube.mydomain.com:443 peertube-plugin-livechat] 2023-08-12 15:58:29.045 info: Checking if we need to migrate chat-type
ago 12 15:58:29 debian12 peertube[210737]: [peertube.mydomain.com:443 peertube-plugin-livechat] 2023-08-12 15:58:29.047 info: The setting chat-type
 is already here, no need to migrate.                                                                                                           ago 12 15:58:29 debian12 peertube[210737]: [peertube.mydomain.com:443 peertube-plugin-livechat] 2023-08-12 15:58:29.049 info: Changing http-bind po
rt for null                                                                                                                                     ago 12 15:58:29 debian12 peertube[210737]: [peertube.mydomain.com:443 peertube-plugin-livechat] 2023-08-12 15:58:29.062 info: Checking if Prosody i
s correctly running                                                                                                                             
ago 12 15:58:29 debian12 peertube[210737]: [peertube.mydomain.com:443 peertube-plugin-livechat] 2023-08-12 15:58:29.062 info: Checking if Prosody is running
ago 12 15:58:29 debian12 peertube[210737]: [peertube.mydomain.com:443 peertube-plugin-livechat] 2023-08-12 15:58:29.063 info: Prosody is not running correctly:
ago 12 15:58:29 debian12 peertube[210737]: [peertube.mydomain.com:443 peertube-plugin-livechat] 2023-08-12 15:58:29.063 info: Pid file /media/peert
ube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.pid not found                                                          
ago 12 15:58:29 debian12 peertube[210737]: [peertube.mydomain.com:443 peertube-plugin-livechat] 2023-08-12 15:58:29.064 info: Checking if Prosody i
s running, and shutting it down if so                       
ago 12 15:58:29 debian12 peertube[210737]: [peertube.mydomain.com:443 peertube-plugin-livechat] 2023-08-12 15:58:29.403 info: ProsodyCtl command returned: certmanager         error        Error indexing certificate directory /media/peertube/storage/plugins/data/peertube-plugin-livechat/pros
ody/certs: cannot open /media/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/certs: No such file or directory
ago 12 15:58:29 debian12 peertube[210737]: WARNING: Use of prosodyctl start/stop/restart/reload is not recommended                            ago 12 15:58:29 debian12 peertube[210737]:          if Prosody is managed by an init system - use that directly instead.                      ago 12 15:58:29 debian12 peertube[210737]:          e.g. systemctl stop prosody                                                               ago 12 15:58:29 debian12 peertube[210737]: Prosody is not running
ago 12 15:58:29 debian12 peertube[210737]: [peertube.mydomain.com:443 peertube-plugin-livechat] 2023-08-12 15:58:29.403 info: Changing http-bind po
rt for null                                                             
ago 12 15:58:29 debian12 peertube[210737]: [peertube.mydomain.com:443 peertube-plugin-livechat] 2023-08-12 15:58:29.416 info: Writing prosody confi
guration file to /media/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.cfg.lua
ago 12 15:58:29 debian12 peertube[210737]: [peertube.mydomain.com:443 peertube-plugin-livechat] 2023-08-12 15:58:29.418 info: Going to launch prosody
ago 12 15:58:29 debian12 peertube[210737]: [peertube.mydomain.com:443 peertube-plugin-livechat] 2023-08-12 15:58:29.445 info: Changing http-bind port for 52800, on host peertube.mydomain.com
ago 12 15:58:29 debian12 peertube[210737]: [peertube.mydomain.com:443 peertube-plugin-livechat] 2023-08-12 15:58:29.446 info: Waiting for the prosody process to launch
ago 12 15:58:29 debian12 peertube[210737]: [peertube.mydomain.com:443 peertube-plugin-livechat] 2023-08-12 15:58:29.948 info: Verifying prosody is launched
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443 peertube-plugin-livechat] 2023-08-12 15:58:30.055 info: Prosody status: certmanager         error        Error indexing certificate directory /media/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/certs: cannot open /media/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/certs: No such file or directory
ago 12 15:58:30 debian12 peertube[210737]: Prosody is running with PID 210847
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443 peertube-plugin-livechat] 2023-08-12 15:58:30.055 info: Prosody is running
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443 peertube-plugin-livechat] 2023-08-12 15:58:30.055 info: Starting Prosody log rotation
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:30.056 info: Add plugin peertube-plugin-livechat CSS to global file.
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:30.057 info: Added locale ca-ES of plugin peertube-plugin-livechat.
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:30.058 info: Added locale fr-FR of plugin peertube-plugin-livechat.
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:30.058 info: Added locale eo of plugin peertube-plugin-livechat.
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:30.059 info: Added locale eu-ES of plugin peertube-plugin-livechat.
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:30.059 info: Added locale oc of plugin peertube-plugin-livechat.
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:30.060 info: Added locale pl-PL of plugin peertube-plugin-livechat.
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:30.060 info: Added locale de-DE of plugin peertube-plugin-livechat.
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:30.061 info: Added locale it-IT of plugin peertube-plugin-livechat.
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:30.061 info: Cleaning HTML cache.
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:30.061 info: Registering plugin or theme peertube-plugin-video-annotation.
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:30.069 info: Add plugin peertube-plugin-video-annotation CSS to global file.
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:30.070 info: Added locale fr-FR of plugin peertube-plugin-video-annotation.
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:30.071 info: Cleaning HTML cache.
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:30.071 info: Registering plugin or theme peertube-plugin-chapters.
ago 12 15:58:30 debian12 peertube[210737]: (node:210737) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
ago 12 15:58:30 debian12 peertube[210737]: (Use `node --trace-warnings ...` to show where the warning was created)
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:30.095 info: Add plugin peertube-plugin-chapters CSS to global file.
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:30.096 info: Added locale de-DE of plugin peertube-plugin-chapters.
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:30.096 info: Cleaning HTML cache.
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:30.098 info: HTTP server listening on localhost:9000
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:30.098 info: Web server: https://peertube.mydomain.com/
ago 12 15:58:30 debian12 peertube[210737]: Response ended:
ago 12 15:58:30 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 15:58:30.165 error: Cannot run hook action:application.listening of plugin categories. {
ago 12 15:58:30 debian12 peertube[210737]:   "err": {
ago 12 15:58:30 debian12 peertube[210737]:     "stack": "SyntaxError: Unexpected token < in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at IncomingMessage.<anonymous> (/media/peertube/storage/plugins/node_modules/peertube-plugin-categories/src/server/api.js:27:31)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
ago 12 15:58:30 debian12 peertube[210737]:     "message": "Unexpected token < in JSON at position 0"
ago 12 15:58:30 debian12 peertube[210737]:   }
ago 12 15:58:30 debian12 peertube[210737]: }
ago 12 16:00:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 16:00:28.312 info: Cleaning video viewers.
ago 12 16:02:28 debian12 peertube[210737]: [peertube.mydomain.com:443] 2023-08-12 16:02:28.313 info: Cleaning video viewers.

### Additional information

* PeerTube instance URL:
* PeerTube version: 5.0.0
* NodeJS version: 18.13.0
* Ffmpeg version: 4.4.3
* Redis version: 7.0.11
* PostgreSQL version: 10

**Comment by SventuraOscura** [comment]
Disable all the plugins, seems a problem related to that.

**Comment by asterismo** [comment]
Thanks, i have disabled two plugins and i was able to start the instance. The errors on the plugins vanished. There was a problem with my nginx. It appears that previous versions i had proxy pass to http://127.0.0.1:9000 and it was giving error 502, after changing it to http://localhost:9000 it worked. 

I'm closing this issue. 

Best regards.

**Comment by SventuraOscura** [comment]
Have a good day.

**Comment by JohnXLivingston** [comment]
> It appears that previous versions i had proxy pass to http://127.0.0.1:9000 and it was giving error 502, after changing it to http://localhost:9000 it worked.

Thanks for the tip!

It was not a plugin issue, but a change in NodeJS `localhost` handling. I explain it here:
https://framacolibri.org/t/tips-how-to-fix-peertube-no-more-working-when-updating-to-nodejs/18688
