### ISSUE TITLE
Private live replays won't play after made public

### ISSUE THREAD

**Issue by ashpool37** [Chocobozzz/PeerTube#5936]
### Describe the current behavior

Live replays that used to be private won't play after they are made public

### Steps to reproduce

1. Go live with the setting "Automatically publish a replay when your live ends" on. Set the "Privacy of the new replay" to "Private".
2. End the live and wait for the replay to publish.
3. Update the replay settings, changing the visibility to "Public"
4. Try to play or download the replay.

### Describe the expected behavior

The replay plays normally after made public

### Additional information

* PeerTube instance:
  * URL: https://nethack.tv
  * Version: v5.2.0-bullseye (docker)
  * Docker image digest: sha256:e76d4d4c0bce967b6b79ad1f48c040c7919c7063858c716fcb130637200b4cfa

Trying to download the video reveals the following error:
```
type | "https://docs.joinpeertube.org/api-rest-reference.html#section/Errors/Error"
-- | --
detail | "ENOENT: no such file or directory, stat '/data/streaming-playlists/hls/f630e857-4c1d-4315-bbfc-d8c56ee9c16d/3272e149-246e-4fce-9370-e80e780d0f4d-1080-fragmented.mp4'"
status | 404
code | "Error"
error | "ENOENT: no such file or directory, stat '/data/streaming-playlists/hls/f630e857-4c1d-4315-bbfc-d8c56ee9c16d/3272e149-246e-4fce-9370-e80e780d0f4d-1080-fragmented.mp4'"
```
When I logged in over SSH and inspected the filesystem, I found that the video was still in the "private" folder. Apparently, the backend simply failed to move the video.
Notably, moving or copying the video manually solves the issues, as does changing the video visibility back to private.
The issue is not present with normal videos that are not automatically created live replays.

**Comment by Chocobozzz** [comment]
Hi,

Did you have an error in peertube logs when you updated the replay privacy?

**Comment by ashpool37** [comment]
Hi @Chocobozzz,
Yes, I just reproduced it again, and the error goes like this:
```
peertube-peertube-1  | [nethack.tv:443] 2023-08-17 08:02:37.931 error: Cannot move HLS file /data/streaming-playlists/hls/private/a7f6652a-a2e9-402a-97e3-e3092df7fe9b to /data/streaming-playlists/hls/a7f6652a-a2e9-402a-97e3-e3092df7fe9b after privacy change {
peertube-peertube-1  |   "err": {
peertube-peertube-1  |     "stack": "Error: dest already exists.\n    at /app/node_modules/fs-extra/lib/move/move.js:51:31\n    at /app/node_modules/universalify/index.js:22:54",
peertube-peertube-1  |     "message": "dest already exists."
peertube-peertube-1  |   }
peertube-peertube-1  | }
```

**Comment by ashpool37** [comment]
Here are the contents of `/data/streaming-playlists/hls/a7f6652a-a2e9-402a-97e3-e3092df7fe9b`
```
nethack-tv:/mnt/files/peertube/peertube-data/streaming-playlists/hls$ tree a7f6652a-a2e9-402a-97e3-e3092df7fe9b/
a7f6652a-a2e9-402a-97e3-e3092df7fe9b/
└── replay
    └── 2023-08-17T07:53:33.213Z
        ├── concat-0.ts
        ├── concat-1.ts
        └── concat-2.ts

2 directories, 3 files
```

**Comment by Chocobozzz** [comment]
Is it a permanent live?

**Comment by ashpool37** [comment]
No, a regular one

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1022e273092f539c0b77a5cf6411b06c74fd15e5
