### ISSUE TITLE
Breaking Change in API: CreateLive new replaySettings

### ISSUE THREAD

**Issue by Schoumi** [Chocobozzz/PeerTube#5937]
### Describe the desired information/correction

Hi,

API Change has made replaySettings a requirement when saveReplay settings is enabled. I think the documentation should reflect that change since it's mandatory.

This comment seems says that: https://github.com/Chocobozzz/PeerTube/blob/develop/server/middlewares/validators/videos/video-live.ts#L310

No fallback are in place to avoid that (like make the same privacy as the live video or something else), and since it's a breaking change a bump in the version of the API should be made. v1 API is deprecated since version XX (with fallback in place to not break clients application if new things are mandatory) and v2 API is now live with this settings. According to the Blame the change was made in 5.2.0 version https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/api/openapi.yaml#L3079
The API doc has not been bump to 5.2.0 too. https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/api/openapi.yaml#L4

I've tried to add it in Peertube Live but seems not working, I keep getting "Live replay is enabled but privacy replay setting is missing". So i'm not sure it's the only breaking change made to that part. https://docs.joinpeertube.org/api-rest-reference.html#tag/Live-Videos/operation/addLive and https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/api/openapi.yaml#L3070 says the format to createLive in the API is multi-part: form-data but it's not working as it should or i'm missing something in there. I send the following (with the other data in order to create the live video)
```
Content-Disposition: form-data; name="replaySettings"
Content-Type: application/json

{"privacy":2}
```

I've looked on what the web client send when I create a live and it's not a multi-part:form-data but a json object. So is the doc still accurate on the content-type? If yes, i'd like to know what i'm doing wrong with the replaySettings.
Is json format is good for older peertube version too or is it another breaking change?

Thanks

**Comment by Chocobozzz** [comment]
Oup's sorry about that. I fixed the breaking change in https://github.com/Chocobozzz/PeerTube/commit/90b84bd4bbba27944ad78765965ceae5a8f0e133
