### ISSUE TITLE
Apache configuration

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5938]
### Describe the problem to be solved

@Chocobozzz 

I finalized the Apache config and works very well without any error for now (last version tested one week without interruption)
should I make a pull request? if yes which branch?

thanks

### Describe the solution you would like

Add the new apache configuration into the next update version of PT

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but we don't have enough resources to maintain this an apache configuration. We prefer to only support nginx. I suggest you paste the configuration in this issue so people can find it when they search "apache peertube" terms.
