### ISSUE TITLE
Cannot remove date in Original publication date

### ISSUE THREAD

**Issue by Mike35538** [Chocobozzz/PeerTube#5939]
### Describe the current behavior

In video settings (Advanced settings), once you add a date in Original publication date and save it, you cannot go back and remove it. You can only change it to a different date but cannot delete the date.

### Steps to reproduce

1. Import a video so that an Original publication date gets added automatically, or go to a video that has a blank Original publication date and add a date and then click Update to save it.
2. Now go back an edit the video settings to Original publication date and select the date and hit delete or blank out the date. Then click Update to save it
3. Go view the video Original publication date and the date is still there.

### Describe the expected behavior

When removing the date from Original publication date, that field should now be NULL or empty.
Original publication date is optional and should remain optional even if it was previously filled in.

### Additional information

* PeerTube instance:
  * Version: 5.2.0

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/7ace48819edc63f19f28ba3eedbbfbaa7c6504bd
