### ISSUE TITLE
Missing ActivityPub replies to comments

### ISSUE THREAD

**Issue by monnier** [Chocobozzz/PeerTube#5942]
### Describe the current behavior

When someone comments on a video of mine and I reply to that comment from my Mastodon account, my reply does not appear in the video's comments.

### Steps to reproduce

1. From Mastodon account A, boost one of your own videos
2. From Mastodon account B, reply to the boost to add a comment to the video.
3. From Mastodon account A, reply to that reply.

### Describe the expected behavior

I expect both replies to appear as comments (ideally, properly threaded) in the PeerTube webpage for that video, but instead only the first reply shows up.

Compare for example the PeerTube page:

    https://classe.iro.umontreal.ca/w/o3cPGBufJsNMYxTj5QoGb5

with the corresponding page on Mastodon:

    https://oldbytes.space/@monnier@classe.iro.umontreal.ca/106330900966678514

### Additional information

* PeerTube instance:
  * URL: https://classe.iro.umontreal.ca
  * Version: 5.2.0
  * NodeJS version: no idea (sorry, I don't administer it)
  * Ffmpeg version: no idea either

* Browser name, version and platforms on which you could reproduce the bug: Firefox 102.13.0esr on Debian stable amd64
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue. It's related to https://github.com/Chocobozzz/PeerTube/issues/4226 and so should be fixed in next peertube release
