### ISSUE TITLE
Channel synchronization redundancy check

### ISSUE THREAD

**Issue by tobozo** [Chocobozzz/PeerTube#5948]
### Use case:

1) An account was just created with "skip channel creation" option used during registration.
2) A synchronization profile is then added to a youtube channel. **Since no default channel exists, this also forces the creation of a default channel.**
3) Synchronization succeeds and all videos are processed.

### Problem 1: The default video channel name created during the process cannot be changed.

Although the default channel and its synchronization profile can be deleted and re-created, **doing so will have the peertube instance to download and convert the remote channel twice and also create 404 errors for all the deleted items from the default channel**.

### Problem 2: Creating of a redundant synchronization profile (same `Remote channel URL` but different `Video Channel`) is allowed by the webapp, but eventually fails and the other Video Channel remains empty:

<img width="1165" alt="image" src="https://github.com/Chocobozzz/PeerTube/assets/1893754/1f86dbfa-2fb8-4715-86c8-9bda92a3a937">

A few ideas come out from this situation:

- Show a prompt or confirm dialog before assigning default values that cannot be changed later.
- Either block or honor the creation of a synchronization profile when `Remote channel URL` is duplicate.
- Add the ability to modify and existing `Video Channel` slug
- Add the ability to create a `Video Channel` alias

**Comment by Chocobozzz** [comment]
Hello,

In fact the "Skip channel creation" just creates a default channel with the default name. Then you chose to sync the remote channel with this default channel. We may add a button near the channel choice to go to the channel management page.

Problem 2 is another story, can you share errors from peertube server?

**Comment by tobozo** [comment]
thanks for your feedback 👍 

> the "Skip channel creation" just creates a default channel with the default name

I'd be tempted to suggest this change in [the register view](https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/%2Bsignup/%2Bregister/register.component.html#L95): 

- `I don't want to create a channel` => `Create a default channel`
- `You will be able to create a channel later` => `A channel with default name will be automatically created`

... however this wouldn't fix the `skip` oxymoron in `skipChannelCreation()` function name.

> Problem 2 is another story, can you share errors from peertube server?

There's no visible error in the browser console, and I don't have access to the server logs as I'm a simple user.

The peertube instance is [makertube](https://makertube.net), and it's managed by [@MakerTube@mastodon.social](https://mastodon.social/@MakerTube) account, I'm not sure how to bring them in the loop though.

**Comment by Chocobozzz** [comment]
You can contact your admin on https://makertube.net/about/instance
