### ISSUE TITLE
Display name being shown instead of actual username@address

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#595]
* **PeerTube version or URL:**
beta.6
* **What is the expected behaviour?**
The actual username@address should display in the applicable "Get Help" menus instead of using the display name.
* **What do you see instead?**
![image](https://user-images.githubusercontent.com/28912578/40597223-ba5c383c-6205-11e8-92a3-de677b9e9043.png)

**Comment by gegeweb** [comment]
Same bug on the helper about the owner of a vidéo.
![](https://framapic.org/FH3CL1NHHm7Z/DTaaTYD9IKGs)

**Comment by rigelk** [comment]
Sorry about that, I'm the one at fault for not double-checking it (and indeed in the two helpers, as it's basically the same implementation).
