### ISSUE TITLE
"search" unlisted videos

### ISSUE THREAD

**Issue by stevespaw** [Chocobozzz/PeerTube#5950]
### Describe the current behavior

Doing a search does not find video that are "unlisted". I am logging in as the user that published the video.

### Steps to reproduce

1. Publish a video - make it "public"
2. do search for the title
3. update the video and change it to "unlisted".
4. search for it again

### Describe the expected behavior

I would expect that, if I am logged in, that when I do search, Peertube would look at all videos even "unlisted" ones.

### Additional information

* PeerTube instance:
  * URL:
  * Version: 5.2
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Kinuseka** [comment]
That is the intended behaviour. You need to use "Internal" to be only searchable while logged in

**Comment by stevespaw** [comment]
We need the videos to be Unlisted, they are used in external applications. The SHOULD be searchable by the logged in user. There are 1,000's of unlisted videos that we need to be able to search in the Peertube GUI as the logged in publisher.  Also, if you have a large library and "accidently" published a video as unlisted - you can never find it later?????

**Comment by Kinuseka** [comment]
It is searchable on here though `domain.com/my-library/videos`

**Comment by Kinuseka** [comment]
I was also able to search my own unlisted videos using this API:
`https://domain.com/api/v1/users/me/videos?search=Video%20Title`

This api requires a bearer token on the header to authenticate: 
Format: `Authorization: Bearer [User Token here]`


If you want to learn more about peertube's rest API. I highly recommend to read their docs:
https://docs.joinpeertube.org/api-rest-reference.html

More information about the API I used: https://docs.joinpeertube.org/api-rest-reference.html#tag/My-User/paths/~1api~1v1~1users~1me~1videos/get

**Comment by stevespaw** [comment]
@Kinuseka Thank You very much! This is what I was looking for - but this is not an obvious method (when there is a "search" box at the top of the frame :-). I appreciate your help!

**Comment by stevespaw** [comment]
Thanks for the solution, I hope this helps others that need this...
