### ISSUE TITLE
Process cannot be sent with Misskey, etc.

### ISSUE THREAD

**Issue by PYU224** [Chocobozzz/PeerTube#5952]
### Describe the current behavior

When I follow Peertube with Misskey, the following Warn appears.

```
warn[2023/8/27 14:32:24] Cannot execute processLikeVideo with many retries.
{
  "err": {
    "stack": "Error: Cannot fetch remote video with url: https://misskey.kindworld.one/notes/9iwkvjccj7\n    at /var/www/peertube/versions/peertube-v5.2.0/dist/server/lib/activitypub/videos/get.js:27:19\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v5.2.0/node_modules/tslib/tslib.js:164:62)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "message": "Cannot fetch remote video with url: https://misskey.kindworld.one/notes/9iwkvjccj7"
  }
}
warn[2023/8/27 14:32:24] Cannot process activity Like.
{
  "err": {
    "stack": "Error: Cannot fetch remote video with url: https://misskey.kindworld.one/notes/9iwkvjccj7\n    at /var/www/peertube/versions/peertube-v5.2.0/dist/server/lib/activitypub/videos/get.js:27:19\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v5.2.0/node_modules/tslib/tslib.js:164:62)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "message": "Cannot fetch remote video with url: https://misskey.kindworld.one/notes/9iwkvjccj7"
  }
}
```

### Steps to reproduce

1. Follow PeerTube instances on Misskey

### Additional information

* PeerTube instance: Maha Mukta
  * URL: https://arcadia.video
PeerTube version: 5.2.0
NodeJS version: 20.5
Ffmpeg version: 7:4.4.2-0ubuntu0.22.04.1
Redis version: 6.0.16 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=a3fdef44459b3ad6
PostgreSQL version: Ubuntu 14.8-0ubuntu0.22.04.1)

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! Fixed in https://github.com/Chocobozzz/PeerTube/commit/0cc1a698813e50d86b5a2a8400e1e8a9b82461da
