### ISSUE TITLE
Cannot upload a large video (the upload progress bar resets from 100% to 0%)

### ISSUE THREAD

**Issue by vendornet** [Chocobozzz/PeerTube#5953]
### Describe the current behavior

When I try to upload a large 10.5 Gb video to my instance, the upload reaches 100% and then starts from the beginning from 0% and can go again to 100% and then restarts to 0%. The page stays the same and there are no visible errors on the site just the upload bar resets to 0% and starts again.

I am using the default docker configuration and the provided web server (chocobozzz/peertube-webserver:latest).

The error I got from /data/logs/peertube.log is
```
{"level":"error","message":"[error]: {
  name: 'UploadxError',
  message: 'FileNotFound',
  uploadxErrorCode: 'FileNotFound',
  detail: '',
  request: {
    headers: {
      'x-forwarded-for': '192.168.18.70',
      host: 'mypeertube.com',
      'x-real-ip': '192.168.18.70',
      connection: 'close',
      'content-length': '10407372523',
      'content-type': 'application/octet-stream',
      accept: '*/*',
      authorization: 'Bearer 2d39d1effbe0fdd059e64c537af4ce8c607ba1b2',
      'sec-fetch-site': 'same-origin',
      'accept-language': 'en-US,en;q=0.9',
      'accept-encoding': 'gzip, deflate, br',
      'sec-fetch-mode': 'cors',
      origin: 'https://mypeertube.com',
      'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15',
      referer: 'https://mypeertube.com/videos/upload',
      'content-range': 'bytes 0-10407372522/10407372523',
      'sec-fetch-dest': 'empty'
    },
    method: 'PUT',
    url: '/upload-resumable?upload_id=af63af4c8601a015-2d0b5ceb674a9880-65396afcc5f2605d-5cd0e9a29e7a8aac'
  }
}","label":"mypeertube.com:443 uploadx","timestamp":"2023-08-27T17:55:27.900Z"} 
```

Please find attached the web server configuration. It is from the Peertube template.

The only thing I have changed is in 2 places:
```

location ~ ^/api/v1/videos/(upload|([^/]+/studio/edit))$ {
    limit_except POST HEAD { deny all; }

    # This is the maximum upload size, which roughly matches the maximum size of a video file.
    # Note that temporary space is needed equal to the total size of all concurrent uploads.
    # This data gets stored in /var/lib/nginx by default, so you may want to put this directory
    # on a dedicated filesystem.
    client_max_body_size                      50G; # default is 1M <——- I have changed this to 50G
    add_header            X-File-Maximum-Size 50G always; # 8G inform backend of the set value in bytes before  mime-encoding (x * 1.4 >= client_max_body_size) <——- I have changed this to 50G

    try_files /dev/null @api;
  }

location ~ ^/api/v1/runners/jobs/[^/]+/(update|success)$ {
    client_max_body_size                      50G; # default is 1M <——- I have changed this to 50G
    add_header            X-File-Maximum-Size 50G always; # 8G inform backend of the set value in bytes before mime-encoding (x * 1.4 >= client_max_body_size) <——- I have changed this to 50G

    try_files /dev/null @api;
  }

```

Please find attached the full web server conf file.
[peertube.txt](https://github.com/Chocobozzz/PeerTube/files/12458228/peertube.txt)

### Steps to reproduce

1. Use Safari on iPad Pro M1 11” with iPadOS 16.6 (20G75)
2. Login to Peertube
3. Upload a 10.5 Gb file mp4 file
4. When the upload reaches 100% it restarts from the beginning on the same page

### Describe the expected behavior

The video should be uploaded and being processed.

### Additional information

* PeerTube instance:
  * URL:
  * Version: 5.2.0 (Docker - chocobozzz/peertube:v5.2.0-bullseye)
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Safari on iPad Pro M1 11” with iPadOS 16.6 (20G75)
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by kukhariev** [comment]
Hi @vendornet,
Large files upload from iOS 15.3+ should be fixed by f9ac050a354ee91356aa342d10b49033d8b79fe0
