### ISSUE TITLE
Application crashes with error ERR_HTTP_HEADERS_SENT

### ISSUE THREAD

**Issue by jknipper** [Chocobozzz/PeerTube#5954]
### Describe the current behavior

When I scroll back and forth in time in a video the application crashes and restarts with the following error:

```
  "error": {
    "stack": "Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:387:5)\n    at ServerResponse.setHeader (node:_http_outgoing:644:11)\n    at ServerResponse.header (/app/node_modules/express/lib/response.js:794:10)\n    at ServerResponse.json (/app/node_modules/express/lib/response.js:275:10)\n    at ServerResponse.res.fail (/app/dist/server/middlewares/error.js:24:13)\n    at handleObjectStorageFailure (/app/dist/server/lib/object-storage/proxy.js:60:16)\n    at /app/dist/server/lib/object-storage/proxy.js:46:17\n    at node:internal/util:453:5\n    at finishImpl (node:internal/streams/pipeline:223:7)\n    at finish (node:internal/streams/pipeline:203:5)\n    at node:internal/streams/pipeline:242:13\n    at node:internal/util:453:5\n    at node:internal/streams/pipeline:81:5\n    at finishImpl (node:internal/streams/pipeline:216:23)\n    at finish (node:internal/streams/pipeline:203:5)\n    at node:internal/streams/pipeline:242:13\n    at node:internal/util:453:5\n    at node:internal/streams/pipeline:81:5\n    at finishImpl (node:internal/streams/pipeline:216:23)\n    at finish (node:internal/streams/pipeline:203:5)\n    at node:internal/streams/pipeline:242:13\n    at node:internal/util:453:5\n    at ServerResponse.<anonymous> (node:internal/streams/pipeline:73:7)\n    at ServerResponse.<anonymous> (node:internal/util:453:5)\n    at ServerResponse.onclose (node:internal/streams/end-of-stream:144:25)\n    at ServerResponse.emit (node:events:525:35)\n    at Socket.onServerResponseClose (node:_http_server:275:23)\n    at Socket.emit (node:events:525:35)",
    "message": "Cannot set headers after they are sent to the client",
    "code": "ERR_HTTP_HEADERS_SENT"
  },
```

I'm using MinIO as S3 object storage. This post in the forum seems related: https://framacolibri.org/t/cannot-set-headers-after-they-are-sent-to-the-client/17485/9

### Steps to reproduce

1. play a video
2. scroll time bar back and forth
3. application crashes (not every time)

### Describe the expected behavior

Video should play as expected and application shouldn't crash.

### Additional information

* PeerTube instance:
  * URL: https://makertube.net
  * Version: v5.2.0
  * NodeJS version: official container image
  * Ffmpeg version: official containet image
  * S3 object storage: Minio

* Browser name, version and platforms on which you could reproduce the bug: Chrome/Linux
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/ca8a00d0e7cb71b77f8abc3a830810be9d50c9ad

Unfortunately it hides to root error. I suggest you to apply the patch on your instance, restart peertube and check why minio proxying has an error.
