### ISSUE TITLE
Atom feed files contain invalid XML when a cateogery contains an & sign

### ISSUE THREAD

**Issue by alexlehm** [Chocobozzz/PeerTube#5955]
### Describe the current behavior

I have a video in the category Science & Technolgoy, which when exporting the atom xml for my video list gives an invalid xml since the & sign is used without quoting

### Steps to reproduce

1. open the atom xml for the account https://cliptube.org/feeds/videos.atom?accountName=alexlehm
2. xml should fail validation
3. otherwise check for the string Science & Technology

### Describe the expected behavior

The XML file should be well-formed which means that the string should be Science &amp; Technology

### Additional information

* PeerTube instance:
  * URL: https://cliptube.org/
  * Version: 5.2.0
  * NodeJS version: 
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox 116.0.3. Windows 10
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! Fixed by https://github.com/Chocobozzz/PeerTube/commit/d2640682f6a1c8e355bd7525c1b61b5ee2b128df
