### ISSUE TITLE
Torrent file contains target filename with "invalid" characters like : or /

### ISSUE THREAD

**Issue by alexlehm** [Chocobozzz/PeerTube#5956]
### Describe the current behavior

When Downloading a video file with bittorrent the target filename contains the unchanged video title including "invalid" characters like : or / (at least in Windows that is illegal).
I would usually expect the torrent client to replace the characters but at least when I tried with Transmission it didn't do that and failed to save the file

### Steps to reproduce

1. Download a video file with / in the description as torrent file
2. e.g. https://cliptube.org/download/torrents/f36bf19a-04e6-494c-b72e-04bb894f969e-1080.torrent
3. the target filename is "The Sweet Encore: Blockbuster / Ballroom Blitz 1080p.mp4"

### Describe the expected behavior

The target filename should not contain characters that are invalid filesystem chars like : / or " and replace them with _ or -

Linux allows : and ", but that is still quite odd to have a filename like that

On a sidenote, the https download filename is replacing / with _ but not : 

### Additional information

* PeerTube instance:
  * URL: https://cliptube.org/
  * Version: 5.2.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Transmission 404 on Windows 10
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/c4799cd1b919a0e7081872b995fe1637c174cab8
