### ISSUE TITLE
iOS safari constant loading loop

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#5957]
### Describe the current behavior

Using hevc codec with AAC audio on iOS safari when attempting to play the video it gets caught in a loading loop with "video failed to play".

It works flawlessly on safari with macOS.

I don't know if this is a hevc codec issue or a player issue on iOS.

### Additional information

* PeerTube instance:
  * Version: 5.2.1
  * Ffmpeg version: git

**Comment by vid-bin** [comment]
Well, as it turns out this bug is specific to 4k videos. And I believe it's specific to 60 fps. 1080p60 doesn't have this problem.

Unfortunately even when there are two resolutions (1080p and 4k) it looks like it defaults to the 4k and it just gets caught in an endless loop.

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue but unfortunately we don't have enough resource to support non official video codecs. We are of course opened to make changes in peertube code to add compatibility with other codecs if you manage to understand what happens.

**Comment by vid-bin** [comment]
@Chocobozzz understood but this issue also occurs on the default transcoding profile (h264) that comes with the software.

Set 2160p as the resolution and disable all others then upload a 4k60 video and try playing on an iPhone.

**Comment by vid-bin** [comment]
Also note that even with 1080p selected as well it will try playing the 4k video instead and get stuck in a endless loop.

**Comment by Chocobozzz** [comment]
Can you share a video link?

**Comment by vid-bin** [comment]
Well, I actually can't replicate this on iPhone 4k videos. Seems to be a YouTube specific issue.

You can search for Ink Art 4K on YouTube and the 46 second clip that shows up has this problem.
