### ISSUE TITLE
5.2.1 iPhone cannot play videos with resolution above 1080p

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#5958]
### Describe the current behavior

When using a DEFAULT installation with 5.2.1 and the default h264 encoder any video with a resolution above 1080p results in a constant loading loop on the iPhone.

This includes if there is a low resolution (1080p) and high resolution (1440p/2160p).

If the resolution is max 1080p without a high resolution video plays fine.

Attached is the developer console from the iPhone.

<img width="990" alt="Screenshot 2023-08-30 at 11 21 41 PM" src="https://github.com/Chocobozzz/PeerTube/assets/112714131/dd233fe3-c5fa-45ff-9aa0-64e4c4a14d2a">

### Additional information

* PeerTube instance:
  * Version: 5.2.1
  * Ffmpeg version: git

**Comment by vid-bin** [comment]
Anyway I'm not that surprised because the iPhone/safari has historically had crappy support for high resolution videos.

However the video player included in peertube should default to the low resolution video (1080p) that can be played successfully. Instead it's defaulting to the 1440p/2160p video and gets stuck in a constant loop.

**Comment by Chocobozzz** [comment]
Hello,

Please provide a public URL link so we can reproduce

**Comment by vid-bin** [comment]
I've tried to upload Creative Commons videos but finding a 4k60 creative common video that triggers this is hard.

You can use this clip on your test instance and with 1080p and 2160p selected as transcoding options the issue should show up. This video triggers it for me every time without fail.

https://www.youtube.com/watch?v=WO2b03Zdu4Q

**Comment by Chocobozzz** [comment]
Ping @vid-bin
