### ISSUE TITLE
upgrade probleme 5.2.0 > 5.2.1 ("cd /var/www/peertube")

### ISSUE THREAD

**Issue by prolibre** [Chocobozzz/PeerTube#5959]
### Describe the problem

Attempt to upgrade from version 5.2.0 to 5.2.1
In the /upgrade.sh script, the link to /var/www/peertube is hard-coded. As my installation is in another folder it crashes :-)
_./upgrade.sh: ligne 93 : cd: /var/www/peertube: Aucun fichier ou dossier de ce type_
You need to modify the script on line 93.
I should point out that the update is still being installed despite the error.

Tentative de mise à jour de la version 5.2.0 vers la 5.2.1
Dans le script /upgrade.sh le lien vers /var/www/peertube est en dur dans le script. Comme mon installation est dans un autre dossier ça plante :-)
_./upgrade.sh: ligne 93 : cd: /var/www/peertube: Aucun fichier ou dossier de ce type_
Il faut modifier le script ligne 93.
Je précise que l'installation de la mise à jour à quand même lieu malgré l'erreur.

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/pull/5960
