### ISSUE TITLE
Multiple hostnames for the same instance

### ISSUE THREAD

**Issue by poka-IT** [Chocobozzz/PeerTube#596]
As I ask on [framacolibris forum](https://framacolibri.org/t/several-hostname-for-same-instance/3008), 
It would be a nice feature to be able to associate the same peertube instance with several hostnames.

For the moment, when we try to join an instance with a hostname different from the one given in config, we get this error:

> Cannot retrieve OAuth Client credentials: undefined. Ensure you have correctly configured PeerTube (config/ directory), in particular the “webserver” section.Cannot retrieve OAuth Client credentials: undefined. Ensure you have correctly configured PeerTube (config/ directory), in particular the “webserver” section.Cannot retrieve OAuth Client credentials: undefined. Ensure you have correctly configured PeerTube (config/ directory), in particular the “webserver” section.Cannot retrieve OAuth Client credentials: undefined. Ensure you have correctly configured PeerTube (config/ directory), in particular the “webserver” section.

**Comment by Chocobozzz** [comment]
I don't think we can do such thing with ActivityPub. Maybe you could do a redirection from domain 1 to domain 2?

**Comment by Chocobozzz** [comment]
Closing, it's not really possible with ActivityPub.

**Comment by entomologe** [comment]
Hello; what a great project! When testing on some arbitrary port, I get the same warning. I configured everything else like in the documentation (except the standard ports), so my configuration differs as follows:

/var/www/peertube/config/production.yaml:
listen:
  hostname: 'localhost'
  port: 9000
webserver:
  https: true
  port: 4443
...

/etc/nginx/sites-enabled/peertube:
server {
  listen 8000;
  listen [::]:8000;  
  location / { return 301 "https://$host:4443$request_uri"; }
...
server {
  listen 4443 ssl http2;
  listen [::]:4443 ssl http2;
...

My syslog prints the following meaningful regarding the problem:

Oct 28 14:07:11 localhost peertube[18140]: [peertube.$INSTANCE:4443] 2020-10-28 14:07:11.694 #033[33mwarn#033[39m: It seems PeerTube was started (and created some data) with another domain name. This means you 
will not be able to federate! Please use NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run update-host to fix this.

When I do this I get:
...
npm ERR! path /var/www/peertube/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/var/www/peertube/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

---

Just a quick sidenote: when changing the 2 configs above to standard ports, everything works fine. Meanwhile I used this aproach as I have already apache listening on 80 and 443 and did not felt to migrate the nginx vhost config to apache or migrate my other vhosts to nginx. ; )

**Comment by rigelk** [comment]
@entomologe please open a new issue and refer to the issue instead

**Comment by entomologe** [comment]
> @entomologe please open a new issue and refer to the issue instead

Okay, I opened a new issue: https://github.com/Chocobozzz/PeerTube/issues/3234

**Comment by Agorise** [comment]
We run 1 instance on 3 domains actually, including a darkweb .onion url: 
https://dollarvigilante.tv 
https://vigilante.tv 
http://dollarvifyat7aehsklwzl2vf4rpkn5t4bftecepzfmv4q4fq53rxwyd.onion 
The pages load and videos seem to stream ok. 
Any questions just ping kencode on agorise.chat
