### ISSUE TITLE
arm64 docker images missing in 5.2.1

### ISSUE THREAD

**Issue by EvilOlaf** [Chocobozzz/PeerTube#5961]
### Describe the problem

https://hub.docker.com/r/chocobozzz/peertube/tags

Hey,
is arm64 no longer supported or is this a bug?

Cheers

### Additional information

* PeerTube instance URL: N/A
* PeerTube version: N/A
* NodeJS version: N/A
* Ffmpeg version: N/A
* Redis version: N/A
* PostgreSQL version: N/A

**Comment by mossroy** [comment]
Same issue here.
It looks like the "develop-bookworm" tag deployed on docker hub has images for both amd64 and arm64.
Only version 5.2.1-bullseye is missing the arm64 image.
So I suppose it has been a temporary issue?

**Comment by Chocobozzz** [comment]
Hi,

Sorry about the late answer. We have some issues with the docker build on ARM64 that timeouts in our CI. So I manually rebuilt the docker image and pushed it on docker hub. ARM64 version of 5.2.1-bullseye should now be available :)
