### ISSUE TITLE
Error when I try to upload a files already upload but interupted

### ISSUE THREAD

**Issue by Iwios** [Chocobozzz/PeerTube#5965]
### Describe the current behavior

Hello,

During an upload I have had a problem with my computer.
When I try to reupload the same video, I have an error 

**Server Log:**

{"tags":["http"],"level":"info","message":"10.12.0.20 - - [08/Sep/2023:11:05:15 +0000] \"POST /api/v1/videos/upload-resumable HTTP/1.0\" 400 - \"https://peertube.fqdn.fr/videos/upload\" \"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0\"","label":"peertube.fqdn.fr:443","timestamp":"2023-09-08T11:05:15.323Z"}
{"tags":["client"],"username":"manage","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0","url":"https://peertube.fqdn.fr/videos/upload#upload","level":"error","message":"Client log: Le téléversement a échoué: Unknown error","label":"peertube.fqdn.fr:443","timestamp":"2023-09-08T11:05:15.407Z"}
{"tags":["http"],"level":"info","message":"10.12.0.20 - - [08/Sep/2023:11:05:15 +0000] \"POST /api/v1/server/logs/client HTTP/1.0\" 204 - \"https://peertube.fqdn.fr/videos/upload\" \"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0\"","label":"peertube.fqdn.fr:443","timestamp":"2023-09-08T11:05:15.407Z"}

**Client error:**

![2023-09-08_13-08](https://github.com/Chocobozzz/PeerTube/assets/94412636/96db2638-e479-467e-b978-71e0b51cb897)

### Additional information

* PeerTube instance:
 
  * Version: 5.2.1
  * NodeJS version: 18.13.0
  * Ffmpeg version: 5.1.3-1

**Comment by wickloww** [comment]
Hello, 
The exact cause of the error is not specified in the logs provided. It is coming from the resumable upload, but I need more information. Can you give me the steps to reproduce this error?

**Comment by kukhariev** [comment]
@wickloww,
error can occur if we try to upload the same file several times.
Should be fixed by 6bd160a68dac55f61b28c7631f9985320daf7755

**Comment by Iwios** [comment]
several timles ? Why not in memory, I remeber after 2 try I have this error.

For reproduce: Upload files and during the upload time close the navigator
Re open peertube and try to upload video

I don't remeber if the error occured when I close during upload time or encode time

**Comment by Chocobozzz** [comment]
Hi,

As @kukhariev said I think it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/6bd160a68dac55f61b28c7631f9985320daf7755 that will be included in next peertube version (v6). Once this version is released, if you still have the bug don't hesitate to comment this issue.
