### ISSUE TITLE
Video not found while attempting to upload after connecting Object Storage

### ISSUE THREAD

**Issue by russjr08** [Chocobozzz/PeerTube#5967]
### Describe the current behavior

I am attempting to connect PeerTube to object storage powered by DigitalOcean Spaces, after setting up my config and restarting PeerTube I am met with a "Video not found" error while attempting to upload a video (specifically, after clicking the publish option after the upload completes).

The biggest issue that I'm having with this process is that there are no further errors or details about what is causing this failure. Even after changing my log level to debug, I cannot find any trace of what is occurring. 

### Steps to reproduce

1. Update PeerTube's configuration to enable Object Storage, and restart PeerTube
2. Attempt to upload a video
3. After the upload completes, click the "Publish" option

### Describe the expected behavior

The video should upload, start transcoding, and then move to object storage. Upon encountering an error during these steps, details about what caused the error should be provided. 

### Additional information

* PeerTube instance:
  * URL: N/A
  * Version: 5.2.1
  * NodeJS version: v16.19.1
  * Ffmpeg version: 4.2.8

* Browser name, version and platforms on which you could reproduce the bug: Firefox 117, Linux
* Link to browser console log if relevant: N/A
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): https://pastebin.com/CGNKPHeJ

**Comment by Chocobozzz** [comment]
Hello,

Can you enable debug logs in peertube configuration and paste again server logs?

**Comment by russjr08** [comment]
Since the debug logs are quite large (and hits limits when trying to upload anywhere), I've tried to capture just the logs between actually triggering the upload, and when the browser client gets the error https://pastebin.com/1vgCgtL1 - but if more logging is needed I can try to grab more. 

For further context, I'm trying to use Cloudflare's R2 as the S3 storage provider. Based off the research I saw, since R2 doesn't support ACLs I've changed `object_storage.upload_acl.{public,private}` in my PeerTube config to just an empty string (''), though I did try `null` as well. The `proxify_private_files` option is also set to `false`. 

After receiving this error, attempting to reupload the video seems to just immediately fail as well with:

```
Upload failed

Unknown error
```

The error continues to happen until restarting PeerTube it seems, then I run back into the original issue.

**Comment by Chocobozzz** [comment]
Do you have the exact same issue if you upload another video file?

**Comment by russjr08** [comment]
It was, yep. I believe I've narrowed down the issue a bit more. During some more troubleshooting I changed from Cloudflare's R2 service to Amazon's S3 service, was still running into the issue. I've now found that by waiting a bit of time (around two minutes in my case, for shorter videos) after getting the "Upload complete" notice, the issue doesn't seem to occur. 

I noticed when looking into the jobs area of the admin panel, there were two video transcode jobs - the "longer" one (as in, takes longer to run) was waiting on the first ("shorter") one to complete and I believe that attempting to publish before the shorter one completes is what triggers the issue. 

Not sure if that makes any sense or helps track down the problem a bit more. If there's any more information I can provide I'm happy to do so.

**Comment by Chocobozzz** [comment]
I think it might help if you could create an account for me. You can email me the details (available on my github profile).

**Comment by russjr08** [comment]
Interestingly enough, after attempting to reproduce the issue again after waking up today, I can't seem to do so. Same PC/browser, same settings, same server version, same sample videos including a couple of extra ones just to be sure (from the ["Sample Videos" site](https://sample-videos.com/)).

I'm not exactly sure what has changed here. I suppose it could be a case of the remote storage settings needing time to "settle", which is my only theory. I can still create an account for you if you'd like, but as far as I can tell the issue seems to have resolved on its own.

**Comment by Chocobozzz** [comment]
Okay thanks, then we can close this issue. Don't hesitate to comment if still get this problem.

I think it can also be related to https://github.com/Chocobozzz/PeerTube/issues/5965, so maybe v6 would fix it.
