### ISSUE TITLE
Display video tags as hashtags on other platforms

### ISSUE THREAD

**Issue by xplosionmind** [Chocobozzz/PeerTube#5969]
### Describe the problem to be solved

On Mastodon, the way PeerTube videos are displayed is:

```
video title

video link
```

### Describe the solution you would like

In order to enact tags interoperability, it would be great if video tags could be printed as hashtags on other platforms:

```
video title

hashtags

video link
```

**Comment by asifurrahaman754** [comment]
I would like work on this, can anyone assign me?

**Comment by Chocobozzz** [comment]
Hi,

Mastodon decides how it formats objects coming from PeerTube. You should create an issue on mastodon repository instead :)
