### ISSUE TITLE
Channel synchronizations are flagged as all failed after PT 5.2.1 update

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5973]
### Describe the current behavior

since I updated in 5.2.1 I see all sync channels in failed status. I tried to force the sync but nothing changed, failed is constant.
nothing in the logs related to this issue. I'm stuck.

**Comment by ROBERT-MCDOWELL** [comment]
more info on logs now:

/home/PEERTUBE/ICN/storage/logs/peertube.log:{"err":{"stack":"Error: Command failed with exit code 1: /usr/bin/python3 /NFS_PEERTUBE/ICN/storage/bin/yt-dlp --ffmpeg-location /usr/local/ffmpeg-git/bin/ffmpeg --skip-download --playlist-reverse --flat-playlist --playlist-end 1024 --dump-json -f bestvideo[vcodec^=avc1][height=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=720]+bestaudio/bestvideo[vcodec^=avc1][height<=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://odysee.com/@LugNassad:8?view=content\nTraceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/NFS_PEERTUBE/ICN/storage/bin/yt-dlp/__main__.py\", line 14, in <module>\n  File \"<frozen zipimport>\", line 195, in get_code\n  File \"<frozen zipimport>\", line 758, in _get_module_code\n  File \"<frozen zipimport>\", line 604, in _get_data\nzipimport.ZipImportError: bad local file header: '/NFS_PEERTUBE/ICN/storage/bin/yt-dlp'\n    at makeError (/home/PEERTUBE/ICN/versions/peertube-v5.2.1/node_modules/execa/lib/error.js:60:11)\n    at handlePromise (/home/PEERTUBE/ICN/versions/peertube-v5.2.1/node_modules/execa/index.js:118:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","message":"Command failed with exit code 1: /usr/bin/python3 /NFS_PEERTUBE/ICN/storage/bin/yt-dlp --ffmpeg-location /usr/local/ffmpeg-git/bin/ffmpeg --skip-download --playlist-reverse --flat-playlist --playlist-end 1024 --dump-json -f bestvideo[vcodec^=avc1][height=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=720]+bestaudio/bestvideo[vcodec^=avc1][height<=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://odysee.com/@LugNassad:8?view=content\nTraceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/NFS_PEERTUBE/ICN/storage/bin/yt-dlp/__main__.py\", line 14, in <module>\n  File \"<frozen zipimport>\", line 195, in get_code\n  File \"<frozen zipimport>\", line 758, in _get_module_code\n  File \"<frozen zipimport>\", line 604, in _get_data\nzipimport.ZipImportError: bad local file header: '/NFS_PEERTUBE/ICN/storage/bin/yt-dlp'","shortMessage":"Command failed with exit code 1: /usr/bin/python3 /NFS_PEERTUBE/ICN/storage/bin/yt-dlp --ffmpeg-location /usr/local/ffmpeg-git/bin/ffmpeg --skip-download --playlist-reverse --flat-playlist --playlist-end 1024 --dump-json -f bestvideo[vcodec^=avc1][height=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=720]+bestaudio/bestvideo[vcodec^=avc1][height<=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://odysee.com/@LugNassad:8?view=content","command":"/usr/bin/python3 /NFS_PEERTUBE/ICN/storage/bin/yt-dlp --ffmpeg-location /usr/local/ffmpeg-git/bin/ffmpeg --skip-download --playlist-reverse --flat-playlist --playlist-end 1024 --dump-json -f bestvideo[vcodec^=avc1][height=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=720]+bestaudio/bestvideo[vcodec^=avc1][height<=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://odysee.com/@LugNassad:8?view=content","escapedCommand":"\"/usr/bin/python3\" \"/NFS_PEERTUBE/ICN/storage/bin/yt-dlp\" --ffmpeg-location \"/usr/local/ffmpeg-git/bin/ffmpeg\" --skip-download --playlist-reverse --flat-playlist --playlist-end 1024 --dump-json -f \"bestvideo[vcodec^=avc1][height=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=720]+bestaudio/bestvideo[vcodec^=avc1][height<=720]+bestaudio[ext=m4a]/bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best\" \"https://odysee.com/@LugNassad:8?view=content\"","exitCode":1,"stdout":"","stderr":"Traceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/NFS_PEERTUBE/ICN/storage/bin/yt-dlp/__main__.py\", line 14, in <module>\n  File \"<frozen zipimport>\", line 195, in get_code\n  File \"<frozen zipimport>\", line 758, in _get_module_code\n  File \"<frozen zipimport>\", line 604, in _get_data\nzipimport.ZipImportError: bad local file header: '/NFS_PEERTUBE/ICN/storage/bin/yt-dlp'","failed":true,"timedOut":false,"isCanceled":false,"killed":false},"level":"error","message":"Failed to import https://odysee.com/@LugNassad:8?view=content in channel ICN Watch","label":"secure.icn.press:443","timestamp":"2023-09-16T12:40:59.716Z"}

the guilty is apparently "bad local header" ?!?! any clue?

**Comment by ROBERT-MCDOWELL** [comment]
is PT puts its own yt-dlp in storage/bin/ or should yt-dlp installed at the OS level?
I have installed yt-dlp from source but apparently PT has its own, I even cannot delete it as it reappear again but with read pemissions, not exec. So I modified in exec permissions and it should be better  I think

**Comment by Chocobozzz** [comment]
> is PT puts its own yt-dlp in storage/bin/ or should yt-dlp installed at the OS level?

It puts its own version of yt-dlp in `storage/bin` and doesn't use `yt-dlp` from the OS. From what I see it seems there is something wrong with your installation as `storage/bin/yt-dlp` should be a binary file, whereas on your disk there is `storage/bin/yt-dlp/main.py`. Delete ``storage/bin/yt-dlp` and let PeerTube automatically download the `yt-dlp`
