### ISSUE TITLE
Player issues with high bitrate videos

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#5974]
### Describe the current behavior

When using high bitrate ~60Mbps videos with increased rate limits in the nginx.conf the initial load time is incredibly fast but after the buffer runs out has 0 network activity and does not play.

Sometimes it struggles if you fast forward, sometimes it doesn't.

I am unsure if this is a peertube issue, a hls.js issue or an issue with the software AV1 decoder in firefox.

I am seeing a lot of "mediaError - fatal: false - bufferfullerror" along with bufferstallederror.

### Additional information

* PeerTube instance:
  * Version: 5.2.1
  * Ffmpeg version: git

**Comment by Chocobozzz** [comment]
Hi,

Please provide an example video URL

**Comment by vid-bin** [comment]
@Chocobozzz 

I emailed you a link. On this particular video the buffer appears to be able to keep up but it only holds around 5-7 seconds worth of clip at a time.

**Comment by Chocobozzz** [comment]
Thanks!

Unfortunately I think you hit a hls.js limit or a web browser limit where it is not fast enough to decode the video.

Closing as I don't think we can do anything on PeerTube side.
