### ISSUE TITLE
Reduce delay time to the lowest possible level

### ISSUE THREAD

**Issue by hoang2807** [Chocobozzz/PeerTube#5978]
### Describe the problem to be solved

I'm using peertube for a company project about livestreaming, the delay compared to real time is 11s, can it be reduced further? I have a question: Did you set the ~15s setting because you tested it or set it hard?

**Comment by Chocobozzz** [comment]
Hi,

>  Did you set the ~15s setting because you tested it or set it hard?

It's just an information, the settings are in fact defined in https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/assets/player/shared/player-options-builder/hls-options-builder.ts#L141 and https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/assets/player/shared/player-options-builder/hls-options-builder.ts#L208 (we disable P2P and [have a delay of 2 segments](https://github.com/video-dev/hls.js/blob/master/docs/API.md#livesyncdurationcount) of 2 seconds each.

I think it may be possible to reduce latency by a few seconds, but it's not something we worked on. HLS and RTMP introduce incompressible delays, even if there [is some work done on HLS side](https://developer.apple.com/documentation/http-live-streaming/enabling-low-latency-http-live-streaming-hls)
