### ISSUE TITLE
Rss feed include audio media as video (wrong type video/mp4 and medium)

### ISSUE THREAD

**Issue by ztec** [Chocobozzz/PeerTube#5979]
### Describe the current behavior

When subscribing to the RSS feed of a channel, you get all video with Media including all resolutions available.
One of those resolution is `0` and is audio only in reality. The type is set as `type="video/mp4"` 

Here an example from a random peertube instance

```
<item>
[...]
            <dc:creator>Creator</dc:creator>
            <category>News &amp; Politics</category>
            <enclosure length="613861895" type="video/mp4" url="https://BASEURL+ID-1080-fragmented.mp4"/>
            <media:community>
                <media:statistics views="39"/>
            </media:community>
            <media:embed url="https://BASEURL+ID"/>
            <media:player url="https://BASEURL+IDj"/>
            <media:group>
                <media:peerLink type="application/x-bittorrent" href="[BASEURL+ID-1080-hls.torrent](view-source:BASEURL+ID-1080-hls.torrent)" isDefault="false"/>
                <media:peerLink type="application/x-bittorrent" href="[BASEURL+ID-480-hls.torrent](view-source:https://BASEURL+ID-480-hls.torrent)" isDefault="false"/>
                <media:peerLink type="application/x-bittorrent" href="[https://BASEURL+ID-0-hls.torrent](view-source:https://BASEURL+ID-0-hls.torrent)" isDefault="false"/>
                <media:content type="video/mp4" medium="video" height="1080" fileSize="613861895" url="https://BASEURL+ID-1080-fragmented.mp4" framerate="24" duration="3252" isDefault="true"/>
                <media:content type="video/mp4" medium="video" height="480" fileSize="289323299" url="https://BASEURL+ID-480-fragmented.mp4" framerate="24" duration="3252" isDefault="false"/>
                <media:content type="video/mp4" medium="video" height="0" fileSize="52958339" url="https://BASEURL+ID-0-fragmented.mp4" framerate="0" duration="3252" isDefault="false"/>
            </media:group>
[...]
        </item>
        <item>
```

the important line is this one

```
<media:content type="video/mp4" medium="video" height="0" fileSize="52958339" url="https://BASEURL+ID-0-fragmented.mp4" framerate="0" duration="3252" isDefault="false"/>
```

### Steps to reproduce

1. open rss feed of any channel

### Describe the expected behavior

we should have the type set to `audio/mp4` or equivalent instead of `video/mp4` so the reader can properly display and play the media (with an audio player instead of a video player) without having to open the file and parse it.

 

### Additional information

Got my example from this instance https://canard.tube. I do not know if this issue is specific or has been fixed in newer version (if any). But I dig a little in the code and found the following point of interest in the code

Where the feed is built: https://github.com/Chocobozzz/PeerTube/blob/develop/server/server/controllers/feeds/video-feeds.ts#L125-L189

I think the type (video/mp4) comes from this line https://github.com/Chocobozzz/PeerTube/blob/develop/server/server/controllers/feeds/video-feeds.ts#L141

After digging, I found out that the `videoFile` object contains data that actually tells if the video is a video or audio only. it's here: https://github.com/Chocobozzz/PeerTube/blob/develop/server/server/models/video/formatter/video-api-format.ts#L213

I think the fix would be to change this line https://github.com/Chocobozzz/PeerTube/blob/develop/server/server/controllers/feeds/video-feeds.ts#L141 with `videoFile.resolution.label === 'Audio' ? 'audio' : 'video'`  in order to properly set the media type. 

I have no idea how to test this fix to ensure it actually fix it. So if anyone have the knowledge, here are the required data on a plate.

**Comment by Chocobozzz** [comment]
Thanks @ztec! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1611721c9b9bb00015730259fd91dfd6c5aed824
