### ISSUE TITLE
Error When Attempting to Use Upload.js

### ISSUE THREAD

**Issue by bootlicker** [Chocobozzz/PeerTube#598]
* **PeerTube version or URL:** Peertube beta 6 git cloned repo server tools, uploading to beta 3 instance
* **Browser name/version:** Firefox, but not a browser related issue
* **NodeJS version:** 8.11.1

* **What is the expected behaviour?** 
A successful upload of a locally stored video file to the Peertube instance.

* **What do you see instead?**
I get this error output when using the Upload.js tool:

`node dist/server/tools/upload.js -u "https://tube.boolicker.party" -U XXX -p XXXX -f "/var/www/html/vlog/Still_Slightly_Anxious_Day_360_-_Thursday_10_December_2015-BL1Uej9KC1s.f134.mp4" --video-name "Still Slightly Anxious (Day 360 - Thursday, 10 December 2015)"
`

`TypeError: Cannot read property 'status' of undefined
    at Test._assertStatus (/root/PeerTube/node_modules/supertest/lib/test.js:263:11)
    at Test._assertFunction (/root/PeerTube/node_modules/supertest/lib/test.js:281:11)
    at Test.assert (/root/PeerTube/node_modules/supertest/lib/test.js:171:18)
    at assert (/root/PeerTube/node_modules/supertest/lib/test.js:131:12)
    at /root/PeerTube/node_modules/supertest/lib/test.js:128:5
    at Test.Request.callback (/root/PeerTube/node_modules/superagent/lib/node/index.js:728:3)
    at ClientRequest.req.once.err (/root/PeerTube/node_modules/superagent/lib/node/index.js:647:10)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

* **Browser console log if useful (Gist/Pastebin...):** Not a browser related issue.

* **Server log if useful (Gist/Pastebin...):**

**Comment by bootlicker** [comment]
I got this error back in beta 3 as well.

**Comment by Chocobozzz** [comment]
It's tube.bootlicker.party no?

**Comment by bootlicker** [comment]
ah yes, but i still get the error when i correct the URL.

i also get the same error when i use https://localhost:9000

**Comment by bootlicker** [comment]
here is the peertube log file, as you requested!

https://bootlicker.party/peertube.log

**Comment by bootlicker** [comment]
i used
`tail -f peertube.log`
and ran the upload.js script, but the log did not change.

**Comment by Chocobozzz** [comment]
If you don't see the request on peertube side, check the nginx (error) logs. Maybe your video is too big for your reverse proxy.

**Comment by bootlicker** [comment]
hmm it's only about 50megs

**Comment by bootlicker** [comment]
i have checked the nginx logs, and access.log and error.log do not change after running upload.js, and getting the same error message

is there a problem with the typing inside the code?

**Comment by Chocobozzz** [comment]
Nope, the file was compiled into JS.

What is your node version? Do you run is from your computer or on the same server than your PeerTube instance?

I created an account on your instance, and uploaded your file with the same name but I can't reproduce.

**Comment by bootlicker** [comment]
My node version is 8.11.1

This article seems to suggest that a variable has not been initialised with a value somewhere in the code: https://medium.com/@sarahelson81/uncaught-typeerror-cannot-read-property-of-undefined-in-javascript-c81e00f4a5e3

Oh, so you're able to use the CLI script? Maybe it's an issue with my Node version

**Comment by bootlicker** [comment]
I am running this on the same server as my peertube instance

**Comment by bootlicker** [comment]
i am gonna try and update to Node 10 and see what happens

**Comment by tcitworld** [comment]
@bootlicker You'll probably run into other issues https://github.com/Chocobozzz/PeerTube/issues/599

**Comment by bootlicker** [comment]
well i had difficulty installing, but now i get this error, with Node 10 and Yarn 1.7:

Connection refused...

And nothing shows up on the Nginx logs, or the peertube logs...

![screenshot_20180530_001646](https://user-images.githubusercontent.com/29275023/40664552-866aaadc-639e-11e8-814a-0575e5715a1f.png)

**Comment by bootlicker** [comment]
And when I use https://tube.bootlicker.party instead of localhost:9000, i get this:

![screenshot_20180530_002017](https://user-images.githubusercontent.com/29275023/40664761-01028562-639f-11e8-92a6-3efc4ee0076d.png)

**Comment by bootlicker** [comment]
Using tube.bootlicker.party:9000 produces the exact same error as localhost:9000

**Comment by bootlicker** [comment]
okay I updated to beta 7, and went back to Node 8, and now i am getting the same connection refused messages.

i think this is an improvement

**Comment by bootlicker** [comment]
could it be my npm version?

**Comment by bootlicker** [comment]
i don't see why nginx would refuse the connection when i am issuing the command on the same server as it is running, seeing as that would not mean that port 9000 is blocked. port 9000 is blocked to the internet though, through my firewall. perhaps i need to open it, or create some rules around it.

**Comment by bootlicker** [comment]
sorry to spam, but nginx logs respond to a connection when i use http://127.0.0.1 as the URL, but issues a Moved Permanently response as i outlined in the config when a non-SSL connection is made.

i am getting error messages related to my SSL certificate when i use https://localhost and https://tube.bootlicker.party

**Comment by bootlicker** [comment]
the peertube daemon/service on my VPS has stopped, so i restarted it, NOW i am getting this message

![screenshot_20180530_010130](https://user-images.githubusercontent.com/29275023/40667135-bc21d474-63a4-11e8-9672-ca0ee9820816.png)
