### ISSUE TITLE
Embed playlist - same features as for embeding a video

### ISSUE THREAD

**Issue by tio-trom** [Chocobozzz/PeerTube#5980]
### Describe the problem to be solved

When we try to embed a video we have a lot of options like hiding the peertube link, the title, make it responsive, etc..
![2023-09-20_14-23](https://github.com/Chocobozzz/PeerTube/assets/38043315/b20176b6-0d04-4899-a694-fd4c8b6c1ffa)
But we do not have that for playlists:
![2023-09-20_14-23_1](https://github.com/Chocobozzz/PeerTube/assets/38043315/1087ebeb-40a8-4d02-932c-0cbc5ac92966)

### Describe the solution you would like

We should have the same options. It works with the same code:

```
<div>
  <div style="position:relative;padding-top:56.25%;">
      <iframe width="100%" height="100%" sandbox="allow-same-origin allow-scripts allow-popups" src="https://videos.trom.tf/video-playlists/embed/9d1478a9-972f-4f4e-8376-74e3b5ec86c0?title=1&warningTitle=0&peertubeLink=0" frameborder="0"  style="position:absolute;top:0;left:0;width:100%;height:100%;" allowfullscreen></iframe>
      </div>
```

**Comment by EricGuic** [comment]
Hi @tio-trom, an open issue already exist for this : https://github.com/Chocobozzz/PeerTube/issues/5369

(by the way, where do this "Responsive embed comes from ?)

**Comment by tio-trom** [comment]
Ah ok I missed that. I will close this then.
