### ISSUE TITLE
Constant quality drops on a 4k video

### ISSUE THREAD

**Issue by JacksonChen666** [Chocobozzz/PeerTube#5982]
### Describe the current behavior

I have a [4k video](https://videos.jacksonchen666.com/w/22x8rqrkhqLULFPH9D6Wnp) which seems to quality drop about every 2 seconds (including at the start, where very little is happening).

The quality drop is very annoying and very noticeable, because it affects the whole video.

(I suggest watching the video at 4k and on a 4k screen, if possible)

### Steps to reproduce

1. Upload some 4k video (static but complicated visuals e.g. Minecraft)
2. Let it be transcoded
3. Watch it
4. Hopefully notice the constant quality drops

### Describe the expected behavior

The video shouldn't constantly drop in quality noticeably.

### Additional information

* PeerTube instance: videos.jacksonchen666.com
  * URL: https://videos.jacksonchen666.com
  * Version: 5.2.1
  * NodeJS version: v16.18.1
  * Ffmpeg version: 6.0 (same as remote runner)

* ~~Browser name, version and platforms on which you could reproduce the bug:~~
* ~~Link to browser console log if relevant:~~
* ~~Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):~~

The video quality drops are reproduce on a video file level (tested with VLC and mpv), so the browser isn't relevant here.

A remote runner setup is used.

The source video (the file I uploaded to my PeerTube instance) is encoded by ffmpeg on my local machine, combined from 2 separate videos. I have tried the `medium` and `ultrafast` presets (affects size because of amount of compression effort put into it), which did not change anything about the final versions on PeerTube (they have a very similar bitrate with only a 0.1 Mbps difference, and the quality still drops).

[source video](https://files.jacksonchen666.com/debugging/peertube-bitrate/) (encoded with a `slower` preset, [corresponding PeerTube video](https://videos.jacksonchen666.com/w/22x8rqrkhqLULFPH9D6Wnp))

**Comment by vid-bin** [comment]
Can you provide the source video (not the transcoded one)?

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/fbc7f1a00d5dac605e7991fd2352493083110cd3

We now use the default ffmpeg level (that adjusts its value depending on resolution/fps).

**Comment by Chocobozzz** [comment]
Please upgrade remote runners to `0.0.7` and retry to replace the file :)
