### ISSUE TITLE
Do  not Release RC

### ISSUE THREAD

**Issue by HumanG33k** [Chocobozzz/PeerTube#5983]
### Describe the problem to be solved

In order to make update more automatic for production server can RC not be publish on Release section but only on tag ? 

Thx

**Comment by Booteille** [comment]
Hi!

I don't get it. Why would having RC releases forbid automatic updates?

**Comment by HumanG33k** [comment]
it not forbid but RC are not "real" release and should not be in a release workflow.
Each person who want to follow updates through release in github have to filtered stuff …

**Comment by tcitworld** [comment]
Github Releases which are RCs are marked as pre-release. Depending on your workflow, you might be able to filter them out one way or another.

**Comment by Chocobozzz** [comment]
I think https://github.com/Chocobozzz/PeerTube/releases/latest redirects on the latest non-RC release.
