### ISSUE TITLE
mod_av: compilation failed with ffmpeg 6.x lib as some ffmpeg functions are deprecated

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#5984]
### Describe the current behavior

compilation failed if ffmpeg version 6.x installed

### Steps to reproduce

./comfigure
make
make install

### Describe the expected behavior

must compile with ffmpeg 6.x libs

### Additional information

here is the log:
avcodec.c: In function 'switch_h264_encode':
avcodec.c:1560:18: error: 'key_frame' is deprecated [-Werror=deprecated-declarations]
1560 | avframe->key_frame = 1;
| ^~~~~~~
In file included from /usr/local/include/libavcodec/avcodec.h:35,
from avcodec.c:37:
/usr/local/include/libavutil/frame.h:436:9: note: declared here
436 | int key_frame;
| ^~~~~~~~~
avcodec.c:1604:9: error: 'key_frame' is deprecated [-Werror=deprecated-declarations]
1604 | if (context->need_key_frame && avframe->key_frame == 1) {
| ^~
/usr/local/include/libavutil/frame.h:436:9: note: declared here
436 | int key_frame;
| ^~~~~~~~~
avcodec.c:1606:17: error: 'key_frame' is deprecated [-Werror=deprecated-declarations]
1606 | avframe->key_frame = 0;
| ^~~~~~~
/usr/local/include/libavutil/frame.h:436:9: note: declared here
436 | int key_frame;
| ^~~~~~~~~
cc1: all warnings being treated as errors

a little patch will solve it.

**Comment by Chocobozzz** [comment]
Hi,

Thanks but I don't think it's a PeerTube related error as you try to compile ffmpeg. Please open a ticket on their bug tracker instead.
