### ISSUE TITLE
Structured data VideoObject not accessible when you use an iframe

### ISSUE THREAD

**Issue by frerej** [Chocobozzz/PeerTube#5985]
### Describe the current behavior

Testing tool : https://search.google.com/test/rich-results?hl=en

If you test the URL https://peertube.cpy.re/w/rjy7vLphL2DL4gFA73twWN then structured data is detected and the rich results are validated.

If you test the code <iframe title="Nextcloud 21 collaboration features screencast" width="560" height="315" src="https://peertube.cpy.re/videos/embed/cd0ba4ee-9763-44b4-a66f-3550eaf987ba" frameborder="0" allowfullscreen="" sandbox="allow-same-origin allow-scripts allow-popups"></iframe> then there's no structured data detected and the rich results test fails.

### Steps to reproduce

1.Go to https://search.google.com/test/rich-results?hl=en
2. Insert any PeerTube URL generated by the share button, launch the test, rich results are detected.
3. Insert any iframe code generated by the share button, launch the test, no rich results are detected.
4.

### Describe the expected behavior

VideoObject type structured data should be accessible either with link or iframe share button.

### Additional information

* PeerTube instance:
  * URL: https://peertube.cpy.re
  * Version: latest stable
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
I'm sorry but I don't understand: if you use the code tab, it's to test a HTML page that contains json ld tags (`<script type="application/ld+json">{"@context":"http://schema.org","@type":"VideoObject","name...` code).

Can you explain what is your use case?

**Comment by frerej** [comment]
You can either use the /embed URL provided in the iframe : https://peertube.cpy.re/videos/embed/cd0ba4ee-9763-44b4-a66f-3550eaf987ba

So my point is the /embed URL should include structured data, as the /w URL.

**Comment by Chocobozzz** [comment]
Thanks! Can you explain your use case to know what type of information you would need?

**Comment by Chocobozzz** [comment]
Hi,

With https://github.com/Chocobozzz/PeerTube/commit/f90db24233eb4ee0a9fa2a8e6672c3b14449725f peertube will generate jsonld tags inside the embed html. The embed also allow robot indexation for public objects. See also https://github.com/Chocobozzz/PeerTube/issues/5995 for more information

**Comment by frerej** [comment]
Thank you!
