### ISSUE TITLE
Support  null/undefined value returned by 'filter:api.video.get.result' hook

### ISSUE THREAD

**Issue by prateekasap** [Chocobozzz/PeerTube#5988]
### Describe the problem to be solved

Currently, the 'filter:api.video.get.result' hook does not support null/undefined values. 

This topic is discussed here. 

https://framacolibri.org/t/video-isoutdated-is-not-a-function/19037

### Describe the solution you would like

 the 'filter:api.video.get.result' hook should support values other than only the current implementation.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/3601872153ee06a2b58b7fb45898e2b7acbb62ea
