### ISSUE TITLE
Upgrade libxmljs for Node 10 compatibility

### ISSUE THREAD

**Issue by tcitworld** [Chocobozzz/PeerTube#599]
Node 10 breaks `nan` <~ 2.10.0 or so https://github.com/nodejs/nan/issues/504

Fixed by upgrading `libxmljs` to `0.18.8`.

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/8c2c915e0ffce745cda5746ecc0e7f7040b3f893

Thanks @tcitworld
