### ISSUE TITLE
Embed.ly Support for Embedding on Patreon and other platforms

### ISSUE THREAD

**Issue by SteveCaruso** [Chocobozzz/PeerTube#5993]
### Describe the problem to be solved

[Embed.ly](https://embed.ly/) is a service that is used by a large number of providers for embedding content -- specifically in my case being Patreon. 

When Embed.ly scrapes its embedding data from a PeetTube video, important fields for a successful embed are left blank.

For example: If I give them the following PeerTube URL: https://video.arghacademy.org/w/9ZsK6NT3fCxccojyzDfUry

They return the following: [https://embed.ly/docs/explore/oembed?url=https%3A%2F%2Fvideo.arghacademy.org%2Fw%2F9ZsK6NT3fCxccojyzDfUry](https://embed.ly/docs/explore/oembed?url=https%3A%2F%2Fvideo.arghacademy.org%2Fw%2F9ZsK6NT3fCxccojyzDfUry)

Compared to an embed request from Vimeo, which returns the following: [https://embed.ly/docs/explore/oembed?url=http%3A%2F%2Fvimeo.com%2F18150336](https://embed.ly/docs/explore/oembed?url=http%3A%2F%2Fvimeo.com%2F18150336)

If you look at the bottom of both, the PeerTube link is missing the "html" field, which has the actual iframe in it.

### Describe the solution you would like

Is there any way to get Embed.ly the appropriate metadata so that it works?

They have an integration guide here: https://embed.ly/providers/new

I do not have the necessary familiarity with the PeerTube codebase to undertake an attempt at implementation at this time.

**Comment by Chocobozzz** [comment]
Hello,

Unfortunately it seems embed.ly is based on URLs when you add a provider. So it's a blocker for PeerTube as every instance has its own URL. Maybe you can contact them to know if there would be a workaround/alternative approach? For example PeerTube instances responds to HTTP requests with a `x-powered-by: PeerTube` header so external tool can easily know the website uses the PeerTube software under the hood.

**Comment by Chocobozzz** [comment]
Closing as we can't do anything on PeerTube side
