### ISSUE TITLE
Conflicting SEO makes instances be removed from indexing

### ISSUE THREAD

**Issue by Sakrecoer** [Chocobozzz/PeerTube#5995]
### Describe the current behavior

The `sitemap.xml` lists the old format of accounts/channels URLs (`https://peertube.tld/accounts/username` and `https://peertube.tld/channels/channelname`) These URLs being redirections to the new format (`https://peertube.tld/a/username` and `https://peertube.tld/c/channelname`), they are then disregarded for indexing.

Indexers are also unhappy about the data in `<video:player_loc>` of the `sitemap.xml` These links lead to pages that are marked as `NOINDEX` in meta properties inside `<head>`.

This also applies for the canonical URLs listed in the `<head>` of accounts, channels and individual video pages. Here and example of an account page: 
`<link rel="canonical" href="https://peertube.tld/accounts/username">` 
These URLs conflict with that of `og:url` meta property which are following the current schema for URLs, i.e. `<meta property="og:url" content="https://peertube.tld/a/username">`

Canonical URLs should never be redirects. 

![Screenshot of error message on Google's search console](https://github.com/Chocobozzz/PeerTube/assets/3484593/c7ee611b-98fa-464a-accd-b2fc79f0d042)

To address this issue and make sure no further instances disappear from indexes, it is important to consolidate the generation of URLs printed in the leveraged SEO to follow the new standards of peertube. Redirected URLs should stay redirected of course, but never be printed in the SEO tools.

### Additional information

* PeerTube instance: 
  * URL: v.basspistol.org
  * Version: 5.2.1
  * NodeJS version: v16.20.2
  * Ffmpeg version: 4.4.2-0ubuntu0.22.04.1

* Browser name, version and platforms on which you could reproduce the bug: any

**Comment by Chocobozzz** [comment]
Hi,

Thank you very much for these detailed information.
https://github.com/Chocobozzz/PeerTube/commit/f90db24233eb4ee0a9fa2a8e6672c3b14449725f should fix all these issues:
 * sitemap.xml uses new, short, URLs
 * embeds that contain public objects can now be indexed (we use a canonical tag inside that targets the watch page, as youtube embeds do)
 * canonical tags also target new, short, URLs
 * we forbid indexation of remote videos and playlists (and do not use the canonical tag anymore as we can't guess the remote non-redirected URL)

Don't hesitate to create other issues if you still notice SEO bugs or improvements we can do! :)

**Comment by Sakrecoer** [comment]
Beautiful!! many thanks @Chocobozzz!
