### ISSUE TITLE
Link to HLS playlist seems to disappear after some times

### ISSUE THREAD

**Issue by EricGuic** [Chocobozzz/PeerTube#5997]
### Describe the current behavior

I've uploaded some videos, with HLS transcoding set in the configuration.
For those videos, I then allow download, and manually trigger the transcoding of the webtorrent files (the HLS download url isn't enough for my specific need : embeding in H5P.org interactive objects).
(we use S3 object storage).
**Those video were working as expected, but after some time (a few months ?), the first one stops to play.**

![image](https://github.com/Chocobozzz/PeerTube/assets/81166671/ca39de13-1c1a-4180-9e9e-72a748d93b6d)

In the screen capture, you can see those two videos, the first problematic and the second working well.
**Today, I notice that I can't play [the first one ](https://tube.reseau-canope.fr/w/gUVJ2E1p1jiREdBmEHDyXK)(the buffering ring keep spinning) while I can play the [second one](https://tube.reseau-canope.fr/w/1vfwVeP7BdPvrDk3Tkq35V) as expected.**

When I test the various links on this admin page, the webtorrent are ok, but the HLS of the first video ends to the "never starting" player.
**Here are some urls if it can help :** 
First problematic video : 
- webtorrent 480p : https://s3.reseau-canope.fr/peertube/webtorrent/321fa19f-f311-49b6-b39a-0eb955e7b8e8-480.mp4
- hls 480p : https://s3.reseau-canope.fr/peertube/streaming-playlistshls/80dcdd6b-5c58-4846-9943-1c0d8f6866b9/0fbce09e-fe5a-49a4-b882-5931e1cbc3bf-480-fragmented.mp4 

Second working video : 
- webtorrent 480p : https://s3.reseau-canope.fr/peertube/webtorrent/4c4adf35-de9f-4896-8ea2-81adc69c14cc-480.mp4
- hls 360p : https://s3.reseau-canope.fr/peertube/streaming-playlistshls/04158691-0e9e-40cd-b777-925e2f83c535/e6d4ffe1-9fb2-4a0f-8c3f-7fb62c2cf219-360-fragmented.mp4

**Two strange things I've noticed :**
First clue : on my screecapture, you can see that Webtorrent and HLS files of the problematic video have exactly the same size.
Whereas the files of the working video have different sizes.

Second clue : the two videos where uploaded (published ?) at the same date (21/07/2022) if I trust the webadmin UI, but I think the first problematic one where replaced (through CLI) at some point (around june 2023 if I remember). I can guess that from the original HLS resolutions listed : a year ago, my instance was set up to transcode to 1080+720+**480**+0 resolution, and before that to 1080+720+**360**+0).
So maybe is the replacement process the cause ? It's strange because I **always** test the video after the replacement process. (if it helps, I could provide the commands I pass during the replacement process).

Thanks for your help.

### Steps to reproduce

I can't identify what is triggerring this "bug"

### Describe the expected behavior

To keep all links to HLS and other dependencies during time, even after a replacement.

### Additional information

* PeerTube instance: https://tube.reseau-canope.fr
  * URL: https://tube.reseau-canope.fr
  * Version: 5.2.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Chrome
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by EricGuic** [comment]
Looking at some other clue, my colleague has noticed that the m3u8 file is missing : 
https://s3.reseau-canope.fr/peertube/streaming-playlistshls/80dcdd6b-5c58-4846-9943-1c0d8f6866b9/97bb31e5-2e80-49f7-8469-dba94b9f78ad-master.m3u8

**Comment by Chocobozzz** [comment]
Hello,

Can you provide the public URL of a video that doesn't work?

**Comment by EricGuic** [comment]
Hello, here : https://tube.reseau-canope.fr/w/gUVJ2E1p1jiREdBmEHDyXK

**Comment by Chocobozzz** [comment]
Can you check in your bucket if you have this missing m3u8 file? (`https://s3.reseau-canope.fr/peertube/streaming-playlistshls/80dcdd6b-5c58-4846-9943-1c0d8f6866b9/97bb31e5-2e80-49f7-8469-dba94b9f78ad-master.m3u8`)

And other m3u8 files with the following prefix `https://s3.reseau-canope.fr/peertube/streaming-playlistshls/80dcdd6b-5c58-4846-9943-1c0d8f6866b9`?

**Comment by Chocobozzz** [comment]
Could it be removed by some S3 provider rules? Do you have S3 logs to check who deleted these files?

**Comment by EricGuic** [comment]
Hi, I've just asked my colleagues, waiting for their answer. I will update as soon as I get something.

**Comment by EricGuic** [comment]
Hi, after a deeper investigation, here are our results : 
For the problematic video, only the **master.m3u8** file is missing. 
All other files are here : 

1. In the HLS folder : 
- 1080.m3u8 + 1080-fragmented.mp4
- 720.m3u8 + 720-fragmented.mp4
- 480.m3u8 + 480-fragmented.mp4
- 0.m3u8 + 0-fragmented.mp4
- segments-sha256.json

2. In the Webtorrent folder : 
- the 4 mp4 files corresponding to the 4 resolutions

Inspecting another working video, we look at the info inside the **master.m3u8** files : it seems to "only" list the m3u8 files of each resolution.
So we "build" a **new master.m3u8** file for the problematic video, and after pushing it on the S3 (with the right ACL) in the right subfolder, our problematic video plays as it should.

 We are waiting for some answer from OVH on the date (and maybe reason) of the deletion of this file...

---
So with this manual trick, the video plays again. But we don't have any idea on what triggered this deletion.
We tried to reproduce every step on another new video (upload, then CLI replacment), and we will monitor it to see if the same issue appears.

If you have any idea, or want some other test, tell me.

Thanks.

_(By the way, I notice that the HLS files are stored in a subfolder named with the UUID. But the Webtorrent files are stored at the root of the Webtorrent : why this difference ? It would shortly became a real mess with a lot of files from different vidéos...)._

**Comment by Chocobozzz** [comment]
> If you have any idea, or want some other test, tell me.

An audit log of your S3 storage should help us to understand what happened :)

> why this difference ?

"historical reason" :o)

**Comment by Chocobozzz** [comment]
Any news @EricGuic?

**Comment by EricGuic** [comment]
Hi Chocobozzz, sorry but no fresh news about this issue.
It seems we cannot get any usefull log on the S3 side, and I didn't noticed another similar problem since this one. (there is maybe, but I didn't spent all my day looking at all the videos on our instance :-)
Sorry to not be able to provide more clues to think about.

**Comment by Chocobozzz** [comment]
Then I'm closing this issue. Don't hesitate to comment in the future if you have more clues.
