### ISSUE TITLE
Live Streaming not working in instance installed by docker

### ISSUE THREAD

**Issue by upcastvideo** [Chocobozzz/PeerTube#5999]
### Describe the current behavior

I can´t connect live streaming from OBS/Streamyard to RMTP server.

### Steps to reproduce

1. Create live streaming event in instance
2. Connect studio software to RMTP
3. Studio software can´t connect.

### Describe the expected behavior

To connect live straming studio software to custom RMTP

### Additional information

* PeerTube instance:
  * URL: https://upott.upcast.work/
  * Version: 
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by RisedSky** [comment]
In my side it does work.
Check the compose.yml file and the firewall

**Comment by upcastvideo** [comment]
> Hello,
> 
> Please fill the bug template, in particular the `Link to server log` section. Without logs or error message we can't help

Could you point me please on how to get a public log url from server? thanks.

**Comment by Booteille** [comment]
Hi.

I think you must just paste your logs on a service like https://sebsauvage.net/paste/
