### ISSUE TITLE
Split the client and server in different repositories

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#6]
For now the client part (in Angular 2) and the server part (Express) are in the same repository.

But they have many differencies (the client is in TypeScript, the server in JavaScript...) and it does not make sense to keep them the same repo.

The idea is to move the client part in another repository when PeerTube will be ready to be released. For now it's simplier for everyone to have the complete project inside the same repository/server.

**Comment by faddat** [comment]
I could do this, but do you consider it ready now?

**Comment by Chocobozzz** [comment]
Awesome! 

But it is not ready yet. There are some work to do before that (change DBMS, add some features to the inter-pod protocol...).

**Comment by faddat** [comment]
It just dawned on me that the front end serves perfectly from github pages.  

:D.

**Comment by Chocobozzz** [comment]
Now the server is in TypeScipt, it shares its models with the client so we don't need to split the them anymore.
