### ISSUE TITLE
Advanced search

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#60]
For now, we search on the video name, account username and account host fields (substring search).

It could be interesting to search on:
 * Tags (exact search with disambiguation)
 * Category
 * Licence
 * Language

**Comment by imtube** [comment]
Perfect !

**Comment by nvivant** [comment]
Accent insensitive search would be interesting as well, so that videos with "février" are displayed when you request "fevrier" (and the other way around).

**Comment by rigelk** [comment]
@Serkan-devel yacy and elasticsearch are two different search mechanisms with overlapping functionalities. I'm not sure what you suggest we do with them. Especially since they're added external dependencies.

**Comment by Serkan-devel** [comment]
yacy is a decentralized search engine and elastic can scope the search results better

**Comment by lanodan** [comment]
I think you can avoid requiring such heavy dependencies by using the already included fuzzy match of PostgreSQL. (It’s used by pleroma btw and it’s more than enough for a local search)
Related documentation: https://www.postgresql.org/docs/9.2/static/pgtrgm.html

**Comment by Chocobozzz** [comment]
Thanks @lanodan, I think we will use this :)

**Comment by Zig-03** [comment]
`concept from the issue nr.784` 

After deciding on how the advanced search should work, I'd like to suggest **to duplicate it's functionality and have it usable as a "filter"**. 

The filter will serve as layer between the user and all the content the user sees which will be active all the time, unlike the advanced search which you have to configure every time you wanna use it.
Unlike the advanced search, the filter settings will be kept into the account settings or in the cookies (for unregistered users).

To me, the implementation of such a feature will mean power/control to the user. Use cases:
- you always wanna watch videos in English
- you never wanna watch videos tagged with the "car" tag, for example.
- etc..

I can see this function later transforming into a "feed filter" where you'll also be able to select which channel's videos you wanna see first or which channel's videos you wanna see only on Sunday and so on. This again, would mean you giving us the control over what we wanna see, unlike other centralized and proprietary platforms which decide these things for you and default you to them.

**Comment by Zig-03** [comment]
How I see the Advanced search work:
- declare all variables such as tags, video title, video description, comments, license, language, time published, keywords (everything that's on a page)
- group them into defined and undefined. Defined are those with limits, like for example we have exactly 4 types of licenses or exactly 45 languages and undefined are all the others.
- declare rules, such as:
    --should include
    --should exclude
    --should range in between
- declare rule types, such as:
    --exact match
    --not exact match
    --begins with
    --ends with

Some example of how it'll work in a text-based format, by typing these commands directly into the search bar:
`1..4 cats "green" -"yellow" -dog daterange:2455332-2455334 language:fr license:cc tag:cat tag:paw -tag:dog -intitle:*bad indescription:good` 

**explanaition:**
- 1..4 cats - number range
- "green" - keyword in quotes means it's an exact keyword that has to be present somewhere on that page
- -"yellow" - keyword in quotes and with a - sign meaning that this exact keyword should not be present on the page
- -dog - means this broad keyword should not be present
- daterange:2455332-2455334 - means we are looking for a page created in between these dates, in Julian format.
- language:fr - language 
- license:cc - I'm not sure if a search operator like this exists, and so I came up with it, if there is a standard one, we better use that. so here it means it should be licenced cc
- tag:cat tag:paw - it must have these tags
- -tag:dog - it must not have this tag
- -intitle:*bad in the page/video title should not be any words that end with these letters "bad"
- indescription:good - again, I'm not sure if a search operator like this exists, and so I came up with it, if there is a standard one, we better use that. In this example it means that the page/video description should have the broad keyword "good".

As a reference we can see how [Search Engine Optimization (SEO) is doing it](https://moz.com/learn/seo/search-operators), we don't necessarily have to re-coin the wheel :) Another good resource [here](https://bynd.com/news-ideas/google-advanced-search-comprehensive-list-google-search-operators/).
Here's how [google is doing it](https://www.google.com/advanced_search), but other Search Engines do it too, for example in duckduckgo you can refine search results with the same commands, like:
cat -dogs insite:ututu.com "go" 
so it looks like a "standard" and I believe we should not deviate from it.

**Comment by Chocobozzz** [comment]
@Zig-03 Thanks, but a search string is a little bit too complicated for now. I tried to make something we can extend easily based on query parameters:  https://github.com/Chocobozzz/PeerTube/pull/829. And nothing prevents in the future to create your search parser, as I agree this is a very powerful and flexible way to query data.

**Comment by Serkan-devel** [comment]
Will advanced search also fetch data from other peertube instances?

**Comment by Chocobozzz** [comment]
@Serkan-devel No, only local videos and videos from instances followed by your admin (for now). See https://github.com/Chocobozzz/PeerTube/issues/824 for search on the entire fediverse

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/57c36b277e68b764dd34cb2e449f6e2ca3d1e9b6 & https://github.com/Chocobozzz/PeerTube/commit/0b18f4aa80df8868bf34605423c7a298dffbb2aa & https://github.com/Chocobozzz/PeerTube/commit/d525fc399a14a8b16eaad6d4c0bc0a9c4093c3c9

**Comment by lanodan** [comment]
Is there a reason why there is no global search? I mean at least with peered videos.

**Comment by Serkan-devel** [comment]
@lanodan maybe the instances need to be updated for that. This has been freshly commited

**Comment by lanodan** [comment]
That would be weird, I mean the local instance already got the metadata of the video that is given with ActivityPub, right?

**Comment by Serkan-devel** [comment]
@lanodan I don't have an instance, so I'm not shure

**Comment by Chocobozzz** [comment]
> Is there a reason why there is no global search? I mean at least with peered videos.

I don't understand, the search occurs on all videos of instances followed by your admin (so peered videos too).
