### ISSUE TITLE
The registration request button is displayed crookedly

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#6001]
### Describe the current behavior

The button for requesting registration is displayed poorly. It's short, it doesn't look very nice.
Please correct the markup for this button

![Снимок экрана 2023-10-11 164924](https://github.com/Chocobozzz/PeerTube/assets/11453567/1a1bb340-e198-4b75-8305-478ed99fc82e)

### Additional information

* PeerTube instance:
  * URL: https://video.ustim.ru
  * Version: 5.2.1-nightly-2023-10-10

**Comment by Chocobozzz** [comment]
Hello,

This has been fixed in https://github.com/Chocobozzz/PeerTube/commit/57abac459ba6817ee92145256d52435051f08a1d
