### ISSUE TITLE
No way to requeue a transcoding job that failed to be built

### ISSUE THREAD

**Issue by sturmen** [Chocobozzz/PeerTube#6006]
### Describe the current behavior

This has happened a couple of times: I set a video to publish once transcoding is finished, but the transcode job never gets created properly. Then the video is stuck in a "TO TRANSCODE" state forever, with no way to recover.

![image](https://github.com/Chocobozzz/PeerTube/assets/169858/60e6a423-d4c1-41cf-bd15-44e23579a0b3)

### Steps to reproduce

1. Upload video
2. Job fails to be created
4. No way to re-queue a transcoding job

### Describe the expected behavior

There exist some button somewhere to re-trigger the transcoding job.

### Additional information

* PeerTube instance: TinsleyTube
  * URL:  https://tinsley.video
  * Version: 5.2.0 (recently upgraded to 5.2.1)
  * NodeJS version: 16.20.1
  * Ffmpeg version: 4.2.7

I think the original failure was due to ffprobe.js: 
```
}
error[10/10/2023, 10:43:28 PM] Cannot execute job 41b44396-131d-44e3-8376-206dbc422da2 in queue transcoding-job-builder.
{
  "payload": {
    "videoUUID": "38d41bb3-00fc-4874-989f-2ad6aa68b3f1",
    "optimizeJob": {
      "isNewVideo": true
    }
  },
  "err": {
    "stack": "Error: ffprobe exited with code 1\nffprobe version 4.2.7-0ubuntu0.1 Copyright (c) 2007-2022 the FFmpeg developers\n  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)\n  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  libavutil      56. 31.100 / 56. 31.100\n  libavcodec     58. 54.100 / 58. 54.100\n  libavformat    58. 29.100 / 58. 29.100\n  libavdevice    58.  8.100 / 58.  8.100\n  libavfilter     7. 57.100 /  7. 57.100\n  libavresample   4.  0.  0 /  4.  0.  0\n  libswscale      5.  5.100 /  5.  5.100\n  libswresample   3.  5.100 /  3.  5.100\n  libpostproc    55.  5.100 / 55.  5.100\n/var/www/peertube/storage/videos/private/3b366d85-20f8-4f88-92a4-85a322fe06da-2160.mov: No such file or directory\n\n    at ChildProcess.<anonymous> (/var/www/peertube/versions/peertube-v5.2.0/node_modules/fluent-ffmpeg/lib/ffprobe.js:233:22)\n    at ChildProcess.emit (node:events:513:28)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)",
    "message": "ffprobe exited with code 1\nffprobe version 4.2.7-0ubuntu0.1 Copyright (c) 2007-2022 the FFmpeg developers\n  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)\n  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  libavutil      56. 31.100 / 56. 31.100\n  libavcodec     58. 54.100 / 58. 54.100\n  libavformat    58. 29.100 / 58. 29.100\n  libavdevice    58.  8.100 / 58.  8.100\n  libavfilter     7. 57.100 /  7. 57.100\n  libavresample   4.  0.  0 /  4.  0.  0\n  libswscale      5.  5.100 /  5.  5.100\n  libswresample   3.  5.100 /  3.  5.100\n  libpostproc    55.  5.100 / 55.  5.100\n/var/www/peertube/storage/videos/private/3b366d85-20f8-4f88-92a4-85a322fe06da-2160.mov: No such file or directory\n"
  }
}
```

**Comment by sturmen** [comment]
> See [#5691 (comment)](https://github.com/Chocobozzz/PeerTube/issues/5691#issuecomment-1655344640) for a way to force transcoding of a broken video in the future.

I did find that commit, but I don't see it appearing in the menu:
<img width="615" alt="Screenshot 2023-10-18 at 11 03 22 AM" src="https://github.com/Chocobozzz/PeerTube/assets/169858/8712e804-ac5d-4c26-9112-bb6a9cbe0d4b">

> But I would like to fix the root cause of this error: I'm really surprised with `/var/www/peertube/storage/videos/private/3b366d85-20f8-4f88-92a4-85a322fe06da-2160.mov: No such file or directory`. Does the file exists on your disk?

It does not. I can't recall but I may have force-published it early; I assume that would move the file out of where the PeerTube transcoder was expecting it to be?

**Comment by Chocobozzz** [comment]
> I did find that commit, but I don't see it appearing in the menu:

It's not released yet, and it will be available in the admin videos overview page

> It does not. I can't recall but I may have force-published it early; I assume that would move the file out of where the PeerTube transcoder was expecting it to be?

Do you reproduce this issue every time you upload this video?

**Comment by Chocobozzz** [comment]
Ping @sturmen

**Comment by sturmen** [comment]
For posterity: no, I was not able to reproduce this after deleting and reuploading.

**Comment by mikoducky** [comment]
I just got this issue last night. I uploaded a large file and I edited information while uploading. Once it was done, I hit publish, but got an error that I should have taken a picture of. I checked on it in the morning, but it still said waiting to transcode. No jobs were waiting. I tired clicking the HLS and Web Video Transcoding from the admin videos screen, but both gave me a file does not exist error.
I have my stuff going to object storage. Maybe that's what is causing this error?

**Comment by matthijskooijman** [comment]
I also ran into something like this, with 8.0.2. Initial transcoding worked ok (I think), but then making some changes in the studio (I think only changing start time) seems to have started a transcoding job,  which failed.

<img width="1837" height="570" alt="Image" src="https://github.com/user-attachments/assets/b72d0e7f-cdda-4520-8cb9-355d4424db44" />

*Edit: this used to show an error about a "numerical result out of range" error from ffmpeg, but that turned out to be another video. That error was caused by a 3Gbyte bufsize argument to ffmpeg, due to a massive bitrate, due to a 90k fps value in my actual uploaded file (no clue how that happened, but ffprobe shows `r_frame_rate  = 90000 and avg_frame_rate = 0`). Maybe that could be handled more gracefully and provide more info about the error, but this did not lock up the video, I could still retry transcoding for that video, or replace it with a fixed version.*

*Edit: The video that was stuck in TO_EDIT state, had a different error. See https://github.com/Chocobozzz/PeerTube/issues/7426 for a full report about the cause of that error.*

Now, the video is stuck in "TO EDIT" state, and I cannot seem to get it out anymore. I thought to use the studio to make another change, which should force another transcode, but the studio cannot be opened for this video, because the video is already being edited.

> See https://github.com/Chocobozzz/PeerTube/issues/5691#issuecomment-1655344640 for a way to force transcoding of a broken video in the future.

This does not work for me, since commit https://github.com/Chocobozzz/PeerTube/commit/f5104fb234badc16a0d659724337da3dcfbc0441 changed this to not allow transcoding in TO_EDIT state (https://github.com/Chocobozzz/PeerTube/blob/4d2b0c442077a48086656fe72cf215e90fdbaa8b/client/src/app/shared/shared-main/video/video.model.ts#L320-L328)

**Comment by Chocobozzz** [comment]
Forcing transcoding even with a "TO EDIT" state should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1d95916a9982a140a703a4fd71a295a12afaff58
