### ISSUE TITLE
Support go back from S3 to local storage

### ISSUE THREAD

**Issue by PhieF** [Chocobozzz/PeerTube#6009]
### Describe the problem to be solved

In my case I'm not moving completely to S3 (instead, I'm using S3QL to mount it as a file system) because I'm not sure it will work as I want for my backup system, I would have tried it if there was a way to reverse back to local storage

### Describe the solution you would like

some kind of script like the one peertube has to move videos to s3 storages, but to do it the other way: grab them back to local storage. Can also be useful if our s3 storage is buggy or something else

**Comment by Lewiscowles1986** [comment]
What about using AWS s3 command line tooling and changing the `endpoint` (if you are not using AWS provided S3) to `sync` to a local folder, presuming you have enough space...

https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html

**Comment by PhieF** [comment]
@Lewiscowles1986  that helps getting video back to local storage, but doesn't change urls on peertube database, it will continue using s3 storage

**Comment by Lewiscowles1986** [comment]
Looks like peertube has a highly academic design and some weird choices.

I was able to setup an S3 (via minio) locally, and then disconnect it and upload a file

you just need to set `fileUrl` to be `NULL` and `storage = 0`

```
UPDATE videoFile SET fileUrl = NULL, storage = 0 WHERE storage = 1 AND fileUrl IS NOT NULL AND videoId IS NULL
```

That should work. I'd advise taking a sql backup first as it's a destructive operation.

**Comment by Chocobozzz** [comment]
Hello,

`create-move-video-storage-job` script will support `to-file-system` option with https://github.com/Chocobozzz/PeerTube/commit/d3c9a2e5b9ea0b6d8eeb5603444528fce93f7370
