### ISSUE TITLE
Ability to import any kind of article (text and photos)

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#6011]
### Describe the problem to be solved

sometimes some channels YT, odysee, rumble etc... post an article (text only, photo sometimes)
but cannot be imported.

### Describe the solution you would like

It would be fantastic to add to PT the ability to import an article (text + photos) as sometimes there are very interesting articles that don't contain any video related too. So it will extend PT to be also an articles platform

**Comment by Chocobozzz** [comment]
Hello,

Thanks for this issue but for now it's out of the scope of PeerTube
