### ISSUE TITLE
Comments from Mastodon servers with authorized fetch (secure mode) are not visible on PeerTube

### ISSUE THREAD

**Issue by FediVideos** [Chocobozzz/PeerTube#6016]
### Describe the current behavior

If you reply to a PeerTube video post from a Mastodon server with authorized fetch (secure mode) activated, the comment does not appear under the PeerTube video.

If you do the same reply on the same video from a Mastodon server without authorized fetch active, the comment does appear.

(Also, the comments are visible as replies if the thread is observed from any Mastodon server, whether it has auth fetch or not.)

### Steps to reproduce

1. I've posted a comments on PeerTubes video from an authorized fetch Masto server at https://social.growyourown.services/@FediVideo/111297463675521397 and https://social.growyourown.services/@FediVideo/111297502704611609
2. The videos they are supposed to appear under are at https://fedi.video/w/momEri96GRdktTCWaznjMh and https://makertube.net/w/8VA2PFGue6vaRngfdQVniE
3. The comment does not appear. This has happened consistently with other PeerTube servers too, it won't show replies from authorized fetch Masto servers.

### Describe the expected behavior

Public replies should always appear as comments below the video post they are replying to, including from servers with authorized fetch active.

### Additional information

* PeerTube instance: https://fedi.video and others
  * URL: See URLs in report above
  * Version: 5.2.1 and 5.0.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox, Ubuntu Linux

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue. It will be fixed in next peertube version: https://github.com/Chocobozzz/PeerTube/issues/4226

**Comment by FediVideos** [comment]
Fantastic news! And thank you for the fast response to this issue!
