### ISSUE TITLE
The chapter is displayed incorrectly

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#6017]
### Describe the current behavior

This is a test server. Version 5.2.1-nightly-2023-10-29

I added 5 chapters and saved the changes

![image](https://github.com/Chocobozzz/PeerTube/assets/11453567/432053f9-24e1-44b2-b914-ddbd1dc56c6a)

All chapters are displayed incorrectly.

![image](https://github.com/Chocobozzz/PeerTube/assets/11453567/4e12d91a-d0ae-43d9-a2b3-97cce6ff84bc)
![image](https://github.com/Chocobozzz/PeerTube/assets/11453567/c4c9df92-64a3-4460-8b42-75e08c08cd6f)

### Additional information

* PeerTube instance:
  * URL: https://video.ustim.ru/w/uYRW1e2haeGe2mfV7U8ud8
  * Version: 5.2.1-nightly-2023-10-29
  * NodeJS version: v18.17.1
  * Ffmpeg version: 5.1.3-1

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/4fa78cda9299e3f3c669158836ff0aa64a90da2f
