### ISSUE TITLE
Video transcoding won't run after power failure

### ISSUE THREAD

**Issue by alejandrocobo** [Chocobozzz/PeerTube#6018]
### Describe the current behavior

I had a power failure and the UPS failed to provide due to expired batteries. There were several videos in the task list waiting to be transcoded. After power recovered, the list was there and the jobs resumed. But there are a couple of videos that are not in the waiting list and weren't transcoded. 

I cannot launch a transcoding job from the three dots menu of each video while they have the tag "To transcode".

Do I have to wait the current waiting list gets empty? I remember there were a script to push a trancoding jobs but I don't find it in the documentation.

Thanks.

### Steps to reproduce

I don't know the exact steps to reproduce this.

### Additional information

* PeerTube instance:
  * Version: 5.2.1

**Comment by Chocobozzz** [comment]
Hi,

I think https://github.com/Chocobozzz/PeerTube/issues/5691#issuecomment-1655344640 should answer to your question. The feature will be available in next peertube version :)
