### ISSUE TITLE
Jump to the highlighted thread

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#602]
Selecting a comment/comment thread shouldn't need a page reload as is the case right now.

Likewise, accessing a URL with a `;threadId=` parameter should jump directly to the comment/comment thread, with the video paused as it's likely the video will then be of second interest.

**Comment by Chocobozzz** [comment]
Thanks @rigelk 

https://github.com/Chocobozzz/PeerTube/commit/bf079b7bfd7f0fb75ceb28e333bb4b74d8840dd4
