### ISSUE TITLE
Error message for video not loading needs slight tweak so people know how to fix it

### ISSUE THREAD

**Issue by FediVideos** [Chocobozzz/PeerTube#6020]
### Describe the current behavior

At the moment, if a video fails to load, the English-language error message is this:

> Sorry, but this video is not available because the remote instance is not responding.
> Please try again later. 

This implies that the remote instance is broken and the user has no way of fixing this immediately.

However, this is incorrect, as the video does often load fine if the user just refreshes the page. In those cases, the user doesn't have to try later.

### Steps to reproduce

1. Check English language pack and you'll see this is the error message

### Describe the expected behavior

The message ought to say something like this:

Sorry, but this video did not load because the remote instance did not respond.
Please try refreshing the page, or try again later.

### Additional information

* PeerTube instance: fedi.video
  * URL: https://fedi.video
  * Version: 5.0.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Would you like to create a PR by editing this file directly? https://github.com/Chocobozzz/PeerTube/blob/15f2ac71522122b4056f5d5142f2b65de2c5bae4/client/src/app/%2Bvideos/%2Bvideo-watch/video-watch.component.html#L5

**Comment by FediVideos** [comment]
Goodness, sorry, I must have missed your reply. I'm not a developer so I am a bit nervous about editing it directly. I've normally left actual PRs to developers?

I'd love to help if I can, I am just nervous of messing something up!

**Comment by Chocobozzz** [comment]
No worries you can't break anything I'll be there to review and manually merge your changes :)

Just use the edit feature of github on this file: https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/%2Bvideos/%2Bvideo-watch/video-watch.component.html#L5

Then github will automatically create a PR for you (you don't need to fill the PR template for this change)

**Comment by FediVideos** [comment]
Okay... I just get "You need to fork this repository to propose changes." if I try to switch to the editor?

**Comment by Chocobozzz** [comment]
> Okay... I just get "You need to fork this repository to propose changes." if I try to switch to the editor?

Yes you can accept and fork the repository :)

**Comment by FediVideos** [comment]
Okay, I did the fork and clicked for a PR. Hopefully I did it correctly!

**Comment by FediVideos** [comment]
Thanks to Chocobozzz for merging it! Closing issue as fixed :+1:
