### ISSUE TITLE
HLS.js error when replaying a live stream

### ISSUE THREAD

**Issue by alejandrocobo** [Chocobozzz/PeerTube#6021]
### Describe the current behavior

Me and other users are having issues playing videos that were stored after a live streaming. The player works fine when it begins but after a few seconds, the player shows this error:

`HLS.js error: networkError - fatal: false - fragLoadError`

It happens with videos from different live streamers. The uploaded videos (not coming from a live stream) seem to work fine.

Thanks.

### Steps to reproduce

1. Play this video: https://video.hardlimit.com/w/iJXLpz7sTAnKinb9X2Ln8Y
2. Wait a few seconds
3. The error message will show up

### Additional information

* PeerTube instance:
  * URL: https://video.hardlimit.com/w/iJXLpz7sTAnKinb9X2Ln8Y
  * Version: 5.2.1
  * Ffmpeg version:  5.1.3-1

**Comment by Chocobozzz** [comment]
Hello,

Does it work if you manually run transcoding on the replay?  Do the server uses a classic disk to store videos? It seems there was an issue calculating specific segment hashes :thinking:

**Comment by alejandrocobo** [comment]
All replays I've transcoded manually work fine. I can transcode this one but it will last a while since I have a long waiting list from other live streams I manually transcode from time to time. I will reply as soon as it is done.

Regarding the storage, I use a local NAS thru SMB. Sometimes, the NAS is pretty busy and I think during this particular live-streaming, it was busy.

**Comment by Chocobozzz** [comment]
I think SMB is the root cause of the issue, but I don't understand why the FS does not return an error when we read the chunks. I have to admin we had many weird issues in PeerTube repository with instances using SMB or remote network drive. So I'm sorry but we can't support this use case. I suggest to move to object storage instead.

**Comment by alejandrocobo** [comment]
I there a way to transcode livestreams automatically after they have finished? 

That would solve the issue in the short term.

**Comment by Chocobozzz** [comment]
> Is there a way to transcode livestreams automatically after they have finished?

No sorry. You can subscribe to https://github.com/Chocobozzz/PeerTube/issues/3914

**Comment by alejandrocobo** [comment]
Thanks @Chocobozzz. The last question: where are livestreams stored while they are being streamed? Is in .../storage/tmp/?

If that's the case, by moving .../storage/tmp/ to a local storage device, this issue would be mitigated, no?

**Comment by MattyBoombalatty** [comment]
I keep getting the same fragment loading error when using Wasabisys S3. I'm not sure what I'm doing wrong here, but it seems to primarily effect higher resolutions (like 1080p). When watching the network tab, it seems the video is downloaded/requested several times in the browser (for example if it's a 2 GB video, the total download could reach up to several hundred gigabytes).
