### ISSUE TITLE
Not all views are counted

### ISSUE THREAD

**Issue by alejandrocobo** [Chocobozzz/PeerTube#6025]
### Describe the current behavior

There are a couple of video in my instance that have received more than 1000 unique visits (excluding bots) for a fact coming from a news aggregator.

This video has more than 2000 visits and 250 views: https://video.hardlimit.com/w/uZGK12oU5FeSsy8CDLP4hD
This one has more than 1500 visits and 65 views: https://video.hardlimit.com/w/uyN8tZJfdwzU7pTpDtoyKz

I am not sure how many people has clicked on the play button and who clicked,  how long they watched each video. But for me is pretty weird to have such amount of visits and then, so little counted views.

In the past I have had a similar activity from the same aggregator and the views were counted properly. 
This is an example with 1900 visits from the same aggregator and it has 1900 views: https://video.hardlimit.com/w/p2SPvdyzzQxwhXkRePMB5E

That's why it makes no sense to me having so little views in more recent videos.

Maybe it's a misconfiguration or just the people didn't click play o watched the videos long enough as they did before. I didn't notice this behavior until now.

### Steps to reproduce

I really don't know when and why some views are counted and others are not.

### Describe the expected behavior

The number of views should be, at least, in the same order of magnitude than the number of visits a video have from certain sites.

### Additional information

* PeerTube instance:
  * Version: 5.2.1
  * NodeJS version: 18.18.0
  * Redis version: 7.0.11

Thanks.

**Comment by Chocobozzz** [comment]
Hello,

You can check PeerTube correctly sees your IP adress on `/admin/system/debug`. Then you can check if viewers stayed long enough on the video in the `Statistics` page (you can check the `Retention` for example). Can you screen these graphs?

**Comment by alejandrocobo** [comment]
The public IP showed is 127.0.0.1 so that might be the problem?

The retention of the 1500 visits videos is this:
![imagen](https://github.com/Chocobozzz/PeerTube/assets/1640709/0a204fe2-fac5-4e0e-8bf6-25e424074863)

**Comment by Chocobozzz** [comment]
>  The public IP showed is 127.0.0.1 so that might be the problem?

Yes it is. Ensure your reverse proxy correctly forwards the web browser IP address (https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube#L63) and peertube trusts your remote proxy (https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L66)
