### ISSUE TITLE
Unable to Install Plugins

### ISSUE THREAD

**Issue by MattyBoombalatty** [Chocobozzz/PeerTube#6027]
### Describe the current behavior

I am unable to install plugins/themes with the web interface. Error log below:

```
"stack": "Error: Command failed: yarn add peertube-plugin-hive-tube@8.4.9\n/bin/sh: 1: yarn: not found\n\n    at ChildProcess.exithandler (node:child_process:422:12)\n    at ChildProcess.emit (node:events:514:28)\n    at maybeClose (node:internal/child_process:1105:16)\n    at Socket.<anonymous> (node:internal/child_process:457:11)\n    at Socket.emit (node:events:514:28)\n    at Pipe.<anonymous> (node:net:337:12)",
Nov 13 01:26:35 ncd-peertube peertube[44344]:       "message": "Command failed: yarn add peertube-plugin-hive-tube@8.4.9\n/bin/sh: 1: yarn: not found\n",
```

Yarn is indeed installed on the `peertube` user.

### Steps to reproduce

1. Log in to web interface
2. Navigate to Administration > Plugins/Themes
3. Attempt to install a plugin/theme

### Describe the expected behavior

I should be able to install a plugin/theme from the administration interface.

### Additional information

* PeerTube instance:
  * URL: [redacted]
  * Version:  6.0.0-rc1 (also happened on [v5.2.1](https://github.com/Chocobozzz/PeerTube/releases/tag/v5.2.1))
  * NodeJS version: 18.18.2
  * Ffmpeg version: 4.4.2

* Browser name, version and platforms on which you could reproduce the bug: All platforms
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by MattyBoombalatty** [comment]
Note that when I utilize the CLI tools, I'm able to install plugins just fine. Not sure what the hang up is here.

**Comment by Chocobozzz** [comment]
What is the output of `which yarn`?

**Comment by MattyBoombalatty** [comment]
`/var/www/peertube/.nvm/versions/node/v18.18.2/bin/yarn`

**Comment by Chocobozzz** [comment]
`yarn` must be in `peertube` user path, which I think is not the case. 

We don't recommend to install node using `nvm`, prefer using the nodesource distribution: https://docs.joinpeertube.org/support/doc/dependencies#debian-ubuntu-and-derivatives
