### ISSUE TITLE
New Transcoding Jobs Don't Start

### ISSUE THREAD

**Issue by MattyBoombalatty** [Chocobozzz/PeerTube#6029]
### Describe the current behavior

New transcoding jobs on 6.0.0-rc1 do not begin. 

### Steps to reproduce

1. Upload video
2. Expect remote runners to transcode
3. Job isn't created 

### Describe the expected behavior

Remote runners should transcode videos. 

### Additional information

* PeerTube instance:
  * URL:
  * Version: 6.0.0-rc1
  * NodeJS version: 18.18.2
  * Ffmpeg version: 4.4.2

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by MattyBoombalatty** [comment]
Testing to see if increasing the time limit of `remote_runners.stalled_jobs.vod` to 2 hours gives the endpoint more time to update, which might stop it from failing altogether.

**Comment by MattyBoombalatty** [comment]
It seems that large files fall back to the server to transcode, rather than remote runners? I've got an FFMPEG job running on the PeerTube server, despite having runners set up. The video is approximately 1.3 GB in size. In v5.2.1, the videos would be sent to the remote runners, then transcoded, re-uploaded to the server and from there they were moved to storage. Is there a configuration option to resolve this? @Chocobozzz

**Comment by Chocobozzz** [comment]
Hello,

Please provide your server logs

**Comment by MattyBoombalatty** [comment]
Is there something in particular you're looking for?

**Comment by MattyBoombalatty** [comment]
Debug log can be found [here](https://files.catbox.moe/mx7d1g.log)

**Comment by MattyBoombalatty** [comment]
After testing a small (64 MB) video that is one hour in length, I noticed that the PeerTube server does the initial transcoding, and then sends the media to the runners and creates jobs for them. However, for large files, they are never sent to the remote runners and transcoding jobs are not created for them, which leaves the "this video is being transcoded, it may not work properly" notice on the video.

**Comment by MattyBoombalatty** [comment]
Upon further investigation, it seems that the length, rather than the size of the video, is what's causing the issue. I uploaded a 23 second, 230 MB video and it was transcoded by the remote runners, then uploaded and transferred to object storage. I will try to see if I can make a very short video as large as possible (ideally under 30 minutes long and over 1 GB in size) to see if it's truly the length rather than the size that's causing the issue.

**Comment by MattyBoombalatty** [comment]
Alright, it does seem to be the *size* of the video rather than the length that leading to the issue. I doubt this has to do with NGINX as that's simply a reverse proxy, but I'm willing to consider anything to resolve this problem. I don't want videos hanging around in local storage indefinitely because it will inevitably use a ton of it and I'm quite limited.

**Comment by MattyBoombalatty** [comment]
Just got this from the remote runner after uploading a video.

```
    err: {
      "type": "Error",
      "message": "Expected status 200, got 400. \nThe server responded: \"This runner job is not in pending state\".\nYou may take a closer look at the logs. To see how to do so, check out this page: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/development/tests.md#debug-server-logs",
      "stack":
          Error: Expected status 200, got 400.
          The server responded: "This runner job is not in pending state".
          You may take a closer look at the logs. To see how to do so, check out this page: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/development/tests.md#debug-server-logs
              at buildRequest (file:///home/peertube/peertube/apps/peertube-runner/dist/peertube-runner.js:77866:14)
              at makePostBodyRequest (file:///home/peertube/peertube/apps/peertube-runner/dist/peertube-runner.js:77808:10)
              at RunnerJobsCommand.postBodyRequest (file:///home/peertube/peertube/apps/peertube-runner/dist/peertube-runner.js:77937:12)
              at RunnerJobsCommand.accept (file:///home/peertube/peertube/apps/peertube-runner/dist/peertube-runner.js:78323:28)
              at RunnerServer.tryToExecuteJobAsync (file:///home/peertube/peertube/apps/peertube-runner/dist/peertube-runner.js:88716:45)
              at RunnerServer.checkAvailableJobs (file:///home/peertube/peertube/apps/peertube-runner/dist/peertube-runner.js:88682:20)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
          ----
              at file:///home/peertube/peertube/apps/peertube-runner/dist/peertube-runner.js:77869:19
              at file:///home/peertube/peertube/apps/peertube-runner/dist/peertube-runner.js:48866:17
              at Test._assertFunction (file:///home/peertube/peertube/apps/peertube-runner/dist/peertube-runner.js:48852:17)
              at Test.assert (file:///home/peertube/peertube/apps/peertube-runner/dist/peertube-runner.js:48742:27)
              at localAssert (file:///home/peertube/peertube/apps/peertube-runner/dist/peertube-runner.js:48710:18)
              at file:///home/peertube/peertube/apps/peertube-runner/dist/peertube-runner.js:48714:11
              at Request3.callback (file:///home/peertube/peertube/apps/peertube-runner/dist/peertube-runner.js:48283:7)
              at file:///home/peertube/peertube/apps/peertube-runner/dist/peertube-runner.js:48435:22
              at IncomingMessage.<anonymous> (file:///home/peertube/peertube/apps/peertube-runner/dist/peertube-runner.js:47686:11)
              at IncomingMessage.emit (node:events:529:35)
      "res": {
        "req": {
          "method": "POST",
          "url": "https://nicecrew.tv/api/v1/runners/jobs/4ab4724d-271d-47eb-950e-dadb19a7a417/accept",
          "data": {
            "runnerToken": "[redacted]"
          },
          "headers": {
            "content-type": "application/json"
          }
        },
        "header": {
          "server": "nginx/1.18.0 (Ubuntu)",
          "date": "Fri, 17 Nov 2023 00:16:36 GMT",
          "content-type": "application/problem+json; charset=utf-8",
          "content-length": "158",
          "connection": "close",
          "x-powered-by": "PeerTube",
          "x-frame-options": "DENY",
          "tk": "N",
          "access-control-allow-origin": "*",
          "access-control-allow-credentials": "true",
          "access-control-expose-headers": "Retry-After",
          "x-ratelimit-limit": "50",
          "x-ratelimit-remaining": "48",
          "x-ratelimit-reset": "1700180207",
          "etag": "W/\"9e-pQ72Id20rqUqUkbACcA8Oqhg9p0\""
        },
        "status": 400,
        "text": "{\"type\":\"about:blank\",\"title\":\"Bad Request\",\"detail\":\"This runner job is not in pending state\",\"status\":400,\"error\":\"This runner job is not in pending state\"}"
      }
    }
```

**Comment by Chocobozzz** [comment]
Hi,

What is your server hardware? Seems the storyboard generation is failing because it timeouts. You can try to increase the TTL in `peertube-latest/dist/core/initializers/constants.js` (set `JOB_TTL.generate-video-storyboard` to `1000 * 60 * 30` for example)

**Comment by MattyBoombalatty** [comment]
2 cores, 4 GB of RAM. It is definitely underpowered haha. Do I need to rebuild PeerTube after changing it?

**Comment by MattyBoombalatty** [comment]
Got it. It seems jobs are being sent to the remote runners now. So, better hardware or longer timeouts. Thank you for your help. What do the storyboards do anyway?

**Comment by Booteille** [comment]
Hi!

Storyboards allow user to preview a frame from the video by hovering the timebar.

**Comment by MattyBoombalatty** [comment]
Thanks! Sorry to be a pain in the ass. I'll close this issue now.

**Comment by Chocobozzz** [comment]
I increased the default job TTL in https://github.com/Chocobozzz/PeerTube/commit/1682b0bab031d25dde58378565caf70a58f3907c :)

**Comment by normen** [comment]
> I increased the default job TTL in [1682b0b](https://github.com/Chocobozzz/PeerTube/commit/1682b0bab031d25dde58378565caf70a58f3907c) :)

Still not enough for my slow server with S3 storage and long archived streams :( Would be nice to have this configurable.

**Comment by Chocobozzz** [comment]
I prefer to not manage another config key. Please try with this new TTL: https://github.com/Chocobozzz/PeerTube/commit/a5bdce80f6caac7be3d4a357444655bfc26ea6b7

**Comment by normen** [comment]
> I prefer to not manage another config key. Please try with this new TTL: [a5bdce8](https://github.com/Chocobozzz/PeerTube/commit/a5bdce80f6caac7be3d4a357444655bfc26ea6b7)

I already increased the timeout in my docker container to 260 minutes, seems to work. If this makes transcodes fail (I was just running the `create-generate-storyboard-job` script) then this should definitely be at least the 3 hours you set.

For long streams the s3 download and ffmpeg process can take a long time given that ffmpeg is (sensibly) capped in terms of cpu power.
