### ISSUE TITLE
Peertube v6.0.0-RC1: plugins/themes list broken in dark mode

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#6033]
### Describe the current behavior

I just upgraded my dev environnement to test the v6.0.0-RC1.

I'm using the [develop-bookworm](https://hub.docker.com/layers/chocobozzz/peertube/develop-bookworm/images/sha256-349adef0ade2059d63a53728dee4adea307dcf24ada75ee512ced179d9d49da5?context=explore) docker image (as there is no tag for the 6.0.0-RC1).

I use the official `dark` theme.

The plugin list is broken:

![image](https://github.com/Chocobozzz/PeerTube/assets/38844060/7ebf78ac-a94c-4618-9c83-69b82d7e5c59)

Same for theme list:

![image](https://github.com/Chocobozzz/PeerTube/assets/38844060/ea443a7f-a4ca-4765-9020-171d073e5788)

### Steps to reproduce

1. Upgrade to v6.0.0-RC1
2. Install `dark` theme
3. Go the the plugin list page, using the browser dark mode (or select the dark theme)

### Additional information

* PeerTube instance:
  * URL: localhost
  * Version: chocobozzz/peertube:develop-bookworm , as of November the 16th
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/5b436024573f964a5d406a18fd9e8ae12c09d4f6
