### ISSUE TITLE
S3 Storage Does Not Load Large Videos

### ISSUE THREAD

**Issue by MattyBoombalatty** [Chocobozzz/PeerTube#6037]
### Describe the current behavior

When using S3 Storage to hold videos, videos large in size do not display. In the console, the video is downloaded several times over, a notice that a network failure occurred, and this loops indefinitely. Loading lower resolutions (144p) works okay for the most part. 

### Steps to reproduce

1. Upload large video (over 1 GB) 
2. Wait for it to publish and move to object storage 
3. Play it

### Describe the expected behavior

Videos should load in chunks rather than download all at once from S3

### Additional information

* PeerTube instance:
  * URL:
  * Version: 6.0.0-rc1 
  * NodeJS version: 18.18.2 
  * Ffmpeg version: 4.4.2 

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by MattyBoombalatty** [comment]
It looks like for the original resolution of the video, whatever it is, the hashes seem not to line up which causes the video to keep downloading in the browser. Lower resolutions work. I noticed that the PeerTube host still converts the video to a `web-video` and then sends it to the remote runners to do the HLS transcoding. I'm going to test turning off remote runners for the next upload and see if there's something going on there. Note this only seems to happen on larger videos. Videos under about 100 MB in size do not have this problem, and load correctly from object storage.

```
Segment https://streaming-playlists.benis.zone/hls/16a61d30-3ea3-4d43-b5ff-ac5ca3cdcce9/2e772116-215a-4077-accb-50c9b6174e4b-master.m3u8+V0+0 error. Error: Hashes does not correspond for segment 1757bea8-32c1-445c-8e65-9fe3791d493e-1080-fragmented.mp4/1351-2538122(expected: 6367d333ad4383de47c1b056d128edd2303ac7c0152b0304ca04ee42b61d0fc0 instead of e6474afc5bfbe280460c97b6728ea22fb8ddfc8303836a3ea2987b76a30bf6b7)
```

**Comment by MattyBoombalatty** [comment]
Looks like this happens even without S3. I believe this has to do with the original transcoding task.

**Comment by Chocobozzz** [comment]
Hello,

Please ensure your S3 provider and S3 cache server supports and correctly forward the `Range` HTTP Header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests
