### ISSUE TITLE
move-to-object-storage failing on video uploaded long ago

### ISSUE THREAD

**Issue by vincib** [Chocobozzz/PeerTube#6038]
### Describe the current behavior

- on indymotion.fr, which was installed at peertube 1.0, long ago
- we used local storage for a long time and we just migrated to our own minio S3 system.
- we used the Peertube CLI and the command move-to-object-storage to move all videos to S3.

- this video (amongst a lot of others...) failed https://indymotion.fr/w/iYpRrvat16oimpUU7UbGmz

with the following error:

```
Job: 2905
Type: move-to-object-storage
Processed on 18/11/23 08:13:20,952
Finished on 18/11/23 08:13:20,963
{
  "videoUUID": "918bb539-8540-42fe-afcd-1d0e1a5b8ad9",
  "isNewVideo": false,
  "previousVideoState": 1
}
Error: ENOENT: no such file or directory, open '/var/www/peertube/storage/streaming-playlists/hls/918bb539-8540-42fe-afcd-1d0e1a5b8ad9/918bb539-8540-42fe-afcd-1d0e1a5b8ad9-720.m3u8'
```

This folder contains the following : 

```
indymotion:/var/www/peertube/storage/streaming-playlists/hls/918bb539-8540-42fe-afcd-1d0e1a5b8ad9 ll
total 874823
-rwxr-xr-x 1 peertube peertube     84299  5 mai    2021 0.m3u8
-rwxr-xr-x 1 peertube peertube     87016  5 mai    2021 240.m3u8
-rwxr-xr-x 1 peertube peertube     87343  5 mai    2021 480.m3u8
-rwxr-xr-x 1 peertube peertube     87435  5 mai    2021 720.m3u8
-rwxr-xr-x 1 peertube peertube  64658157  5 mai    2021 918bb539-8540-42fe-afcd-1d0e1a5b8ad9-0-fragmented.mp4
-rwxr-xr-x 1 peertube peertube 140444813  5 mai    2021 918bb539-8540-42fe-afcd-1d0e1a5b8ad9-240-fragmented.mp4
-rwxr-xr-x 1 peertube peertube 282649799  5 mai    2021 918bb539-8540-42fe-afcd-1d0e1a5b8ad9-480-fragmented.mp4
-rwxr-xr-x 1 peertube peertube 409191224  5 mai    2021 918bb539-8540-42fe-afcd-1d0e1a5b8ad9-720-fragmented.mp4
-rwxr-xr-x 1 peertube peertube       428  5 mai    2021 master.m3u8
-rwxr-xr-x 1 peertube peertube    284288  5 mai    2021 segments-sha256.json
```

It seems that this is because this video was uploaded long ago :) 

could you please either 

- change this command so that it finds the video in the former file name scheme 
- or create another command to migrate thos "old format" folder to the new format?

thanks <3

### Steps to reproduce

1. have a very old peertube with local storage
2. try to migrate a video to S3
3. fail

### Additional information

* PeerTube instance:
  * URL: https://indymotion.fr/w/iYpRrvat16oimpUU7UbGmz
  * Version: 6.0.0~rc1
  * NodeJS version: 18.17.1
  * Ffmpeg version: 5.1.1-static

**Comment by vincib** [comment]
idea: if you just have a 3-lines shell script to rename files to the proper new format, that could help a lot <3

**Comment by vincib** [comment]
sooo... I tried to find a way to fix it...  :feet: 

- renaming the {0,240,480,720,1080,...}.m3u8 to {uuid}-{0,240,480,720,1080,...}.m3u8 
- renaming segments-sha256.json to {uuid}-segments-sha256.json
- renaming master.m3u8 to  {uuid}-master.m3u8  and changing its content to rename the m3u8 above to their new name

and relaunching move-to-object-storage worked

it says "it worked" but the video is now failing :sob: 

had to restore, and I confirm this is a bug harder to fix than I can easily :)

**Comment by Chocobozzz** [comment]
Hi,

Did you run https://github.com/Chocobozzz/PeerTube/blob/develop/server/scripts/migrations/peertube-4.0.ts when you upgraded to PeerTube v4?

**Comment by vincib** [comment]
Hello Chocobozzz. I didn't launch it manually (I'm pretty sure), maybe I missed it...

I launched it and it failed for some with "Error: ENOENT: no such file or directory," but  that's ok the files seems to already have the right name. (But that's weird because this video has been published before Peertube 4...  but I changed the date of some older videos from a previous mediacenter...) 

I relaunched move-to-object-storage --all-videos and it seems to work (at least for the 2 first that failed :) ) 

That's okay, thanks ! 

(sorry if we didn't read the upgrade path informations properly at that time :( )
