### ISSUE TITLE
CSS issue in videos list on small screens 

### ISSUE THREAD

**Issue by Booteille** [Chocobozzz/PeerTube#6043]
### Describe the current behavior

Hi!

On /my-library/videos webpage, there is a CSS issue when the screen is not wide enough.

Look at there screenshot.

The first one is the behavior (which is the one intended) on a 1920p screen:
![Capture d’écran du 2023-11-21 09-22-05](https://github.com/Chocobozzz/PeerTube/assets/2203721/003813e9-f532-48ac-9df6-861a509e27aa)

The second one on a screen with half the width, after I resized the window:
![Capture d’écran du 2023-11-21 09-22-37](https://github.com/Chocobozzz/PeerTube/assets/2203721/5f7e813e-f79a-414c-807c-2bf3acb1e293) 

It's probably bound to the fact the video has a long name. It does not happen with short names videos.

### Describe the expected behavior

I expect the css to be coherent between views.

### Additional information

* PeerTube instance:
  * URL: localhost
  * Version: latest dev (6.0.0-rc.2...76fc448ab)
  * NodeJS version: 20.8.1
  * Ffmpeg version: 6.1-1build2~22.04

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/4c07200d64386d72248da16e34005618abb16e78
