### ISSUE TITLE
Add a custom video format that opens an external URI instead of video playback

### ISSUE THREAD

**Issue by 3unjee** [Chocobozzz/PeerTube#6044]
### Describe the problem to be solved

Greetings and congrats for PeerTube, a neat project.

I have a question / feature request:  I would like to support an ascii based video format (https://omega.gg/VBML) that's supposed to be parsed and opened via a standalone video player (based on libVLC).

### Describe the solution you would like

1. Is it possible to configure PeerTube to accept these lightweights video text files ?
2. When "playing" said format, is it possible to tell to the embedded player to open an external URI instead of running the video file.

**Comment by Chocobozzz** [comment]
Hi and thanks!

We may add additional format if ffmpeg can transcode them. But unfortunately it's out of the scope of PeerTube to support playing other format than mp4/h264 (i.e. supported in all web browsers).
