### ISSUE TITLE
How to retrigger transcoding for "Transcoding failed" videos?

### ISSUE THREAD

**Issue by arladmin** [Chocobozzz/PeerTube#6045]
### Describe the current behavior

I have uploaded a bunch of videos. Most of them got transcoded successfully into all the defined formats, but a bunch of them did not.

They just show "Transcoding Failed".

When i try to retrigger transcoding, by clicking on "Run Webtorrent/HLS transcoding" for each of the files, i get the error, Transcoding job already in progress. But there are currently no transcoding jobs in progress!

How to resolve this issue?

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version: 5.2.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

In V6 you'll be able to force transcoding of particular videos, in v6. See https://github.com/Chocobozzz/PeerTube/issues/5691#issuecomment-1655344640

**Comment by arladmin** [comment]
> Hello,
> 
> In V6 you'll be able to force transcoding of particular videos, in v6. See https://github.com/Chocobozzz/PeerTube/issues/5691#issuecomment-1655344640

@Chocobozzz That's great.

Also, i need to force transcoding now, of the failed entries. 

How do i do that? 

There are several, large video files that i spent a lot of time uploading. Surely deleting and reuploading them shouldn't be the only option.

**Comment by CorpulentBrony** [comment]
> Hello,
> 
> In V6 you'll be able to force transcoding of particular videos, in v6. See [#5691 (comment)](https://github.com/Chocobozzz/PeerTube/issues/5691#issuecomment-1655344640)

Since we're on V6, how do you force these transcoding jobs to re-run?  I'm not seeing anything in the interface nor do I see a new script.

**Comment by CorpulentBrony** [comment]
> Hello,
> 
> In V6 you'll be able to force transcoding of particular videos, in v6. See [#5691 (comment)](https://github.com/Chocobozzz/PeerTube/issues/5691#issuecomment-1655344640)

@Chocobozzz Since we're on V6, how do you force these transcoding jobs to re-run? I'm not seeing anything in the interface nor do I see a new script.  Am I missing something?

**Comment by Chocobozzz** [comment]
In `Administration` > `Overview` -> `Videos` you should now be able to `Run xxx transcoding` using the `...` button.
