### ISSUE TITLE
Multiple storage locations

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#605]
It'd be useful to have to option to designate multiple locations for storage (with priority for use).

**Comment by Chocobozzz** [comment]
I don't really understand. What would be the use case?

**Comment by rigelk** [comment]
@Chocobozzz I guess that would be to extend storage, possibly with mount points to remote storage locations.

**Comment by fflorent** [comment]
In such a case, I wonder if aufs / unionfs / overlayfs … wouldn't address the use case in a more simple way.

**Comment by rigelk** [comment]
That's probably a simpler way, and should probably be the default recommendation. It doesn't deal with usage priority though, does it?

**Comment by Chocobozzz** [comment]
I completely agree with @fflorent, for me it should be a FS configuration. Closing this issue, but we could continue to discuss about this! I think it's a very interesting way to extend PeerTube storage.
