### ISSUE TITLE
Bug: Markdown button in comments section publish comment instead of displaying markdown syntax

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#6051]
### Describe the current behavior

Hello ! 

When you want to publish a comment, either new or answer to existing one, there is a "Markdown" button at the top right, useful to display a reminder of Markdown syntax

But currently, when clicking on the button, the popup is showing for only one second, and the comment is immediately published, as if the "publish" button is clicked.

### Steps to reproduce

1. Open a video to publish a comment (eg: https://videos.pair2jeux.tube/w/fiqfg39Cw4V2PuVxc7R4b4;threadId=95647)
2. tape some text
3. Click the Markdown button to see the Markdown syntax
4. Comment is published

### Describe the expected behavior

The button should only show the Markdown syntax popup, not publish the comment

Thanks!

### Additional information

* PeerTube instance: https://videos.pair2jeux.tube
  * URL: https://videos.pair2jeux.tube/
  * Version: 5.1
  * NodeJS version: v16.20.0
  * Ffmpeg version: 4.3.6-0+deb11u1

**Comment by Chocobozzz** [comment]
Hi,

Thanks but I can't reproduce on 5.2 so it should already been fixed :)
