### ISSUE TITLE
Typo in v6.0.0 changelog

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#6054]
### Describe the desired information/correction

There are some typos in the v6.0.0 tag notes : https://github.com/Chocobozzz/PeerTube/releases/tag/v6.0.0

* [ ] `There is not "Auto"` => `There is no "Auto"`
* [ ] `Support moving video files from object storage to filesystem: https://docs.joinpeertube.org/maintain/tools#generate-storyboard` => seems you have mixed up 2 lines (generating storyboard, and moving video to object storage)
* [ ] Nginx: missing `rewrite ^/static/webseed/(.*)$ /videos/$1 break;` must be changed to `rewrite ^/static/webseed/(.*)$ /web-videos/$1 break;`
* [ ] Nginx: the content of `location ~ ^/static/(webseed|web-videos|redundancy|streaming-playlists)/ {` must also be changed, not only the location line

**Comment by Chocobozzz** [comment]
Thanks a lot!

> Nginx: missing rewrite ^/static/webseed/(.*)$ /videos/$1 break; must be changed to rewrite ^/static/webseed/(.*)$ /web-videos/$1 break;

This line must not be updated if you don't update the directory name on your filesystem. Since we don't advise that in the changelog, we have not asked for this line to be changed.

> Nginx: the content of location ~ ^/static/(webseed|web-videos|redundancy|streaming-playlists)/ { must also be changed, not only the location line

We just highlight important things in the nginx configuration, but yes some other things can also be changed (that are just "cosmetic" or a little bit better). The update guide gives a command to see all changes: https://docs.joinpeertube.org/install/any-os#update-nginx-configuration

**Comment by JohnXLivingston** [comment]
> Thanks a lot!

You are welcome :)

> > Nginx: missing rewrite ^/static/webseed/(._)$ /videos/$1 break; must be changed to rewrite ^/static/webseed/(._)$ /web-videos/$1 break;
> 
> This line must not be updated if you don't update the directory name on your filesystem. Since we don't advise that in the changelog, we have not asked for this line to be changed.

Oups, you are right!
My bad!

> 
> > Nginx: the content of location ~ ^/static/(webseed|web-videos|redundancy|streaming-playlists)/ { must also be changed, not only the location line
> 
> We just highlight important things in the nginx configuration, but yes some other things can also be changed (that are just "cosmetic" or a little bit better). The update guide gives a command to see all changes: https://docs.joinpeertube.org/install/any-os#update-nginx-configuration

That's how i found the diff :)

What a great release! Congrat for all the work!

**Comment by JohnXLivingston** [comment]
@Chocobozzz , i think there is still an issue.

On this video: https://www.yiny.org/w/ccydLqr1T2fum3925wGT8C

![image](https://github.com/Chocobozzz/PeerTube/assets/38844060/9d800131-0398-4229-bcc7-e04eae9b98cc)

I think we must move the folder 'videos' to 'web-videos', or add the following rewrite in the nginx conf: `rewrite ^/static/web-videos/(.*)$ /videos/$1 break;`

Note: i have fixed the issue on yiny.org, by adding the rewrite rule.

**Comment by Chocobozzz** [comment]
Thanks! I think it's better if everybody move the directory name from the filesystem, for consistency and maintenance ease.

I updated the important notes in https://github.com/Chocobozzz/PeerTube/commit/ee6844d718e97c64af637c57438840b713dca5d3

I'll add a note in 6.0.1 changelog so admins that already upgraded to V6 before this change can see it in the next version.

**Comment by JohnXLivingston** [comment]
Perfect!
