### ISSUE TITLE
Missing job type filter: generate-video-storyboard

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#6055]
### Describe the current behavior

Hello,

In the local job list, there is a missing entry for the "job type" filter: the new `generate-video-storyboard`.
See screenshots:

### Steps to reproduce

![image](https://github.com/Chocobozzz/PeerTube/assets/38844060/7fd9ec79-adcb-43da-aef3-81fc4b947cd3)

![image](https://github.com/Chocobozzz/PeerTube/assets/38844060/53c11d32-6b2e-4b2e-8375-7822540be5c3)

### Additional information

* PeerTube instance:
  * URL: https://videos.john-livingston.fr
  * Version: 6.0.0

**Comment by Chocobozzz** [comment]
Thanks! Fixed by https://github.com/Chocobozzz/PeerTube/commit/4826cb2c698a2bc532c870ee056ebf299ffae4ae
