### ISSUE TITLE
Small X-File-Maximum-Size header for replacing video with another

### ISSUE THREAD

**Issue by kirill2400** [Chocobozzz/PeerTube#6056]
### Describe the current behavior

Sorry for bad bug report
Small X-File-Maximum-Size header for replacing video with another
![image](https://github.com/Chocobozzz/PeerTube/assets/30482699/3cf99a8c-1c66-4816-9e26-232106858ee6)
![image](https://github.com/Chocobozzz/PeerTube/assets/30482699/2c99a758-2d4c-4b0c-932a-6d7bd1c1cb9b)

### Steps to reproduce

1. Try to replace video with another

### Additional information

* PeerTube instance:
  * URL: https://spacecomfort.miracleinsense.ru
  * Version: 6.0.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/db61334cc3ec5091c2635d6e4860853f090d6c31
