### ISSUE TITLE
Video is not transferred to object storage

### ISSUE THREAD

**Issue by kirill2400** [Chocobozzz/PeerTube#6057]
### Describe the current behavior

Sorry again for bad bug report
Old Video stucks on stage six (TO_MOVE_TO_EXTERNAL_STORAGE) (info from postgress db)
But task complete successfully
![image](https://github.com/Chocobozzz/PeerTube/assets/30482699/deab2736-b36a-42ca-ad4e-39f5b8065b95)
Also I have empty segmentsSha256Url in videoStreamingPlaylist table after every try to reencode HLS
![image](https://github.com/Chocobozzz/PeerTube/assets/30482699/de769090-c16b-4599-881b-2c80ded01a93)
Screen from Admin Video Panel (What's odd is that the correct links are listed here)
![image](https://github.com/Chocobozzz/PeerTube/assets/30482699/44f3980e-f726-4864-953f-d963de87d120)
But in reality, it uses paths not with Object Storage when playing video. And since it successfully moved them there (it really did) it removed those files from the path in the screenshot and as a result the video doesn't play.
![image](https://github.com/Chocobozzz/PeerTube/assets/30482699/7354244c-a11e-4800-b85b-ad8393229f7f)
P.S.
This video was broken a long time ago when I was doing a migration from file system to object storage. At that time I didn't realize that s3 should have a public address and in the config I specified the path to s3 as localhost at that time. Most of the videos were successfully migrated again after fixing the address to s3. A small part and this video among others I fixed directly through the database. I replaced manually the file system paths to s3 and set stage = 1. However, after upgrading to version 6.0.0 I found the video control panel and found that I have 3 videos with webvideo files. This is one of them. By deleting the webvideo file I was causing hls transcoding, because on these videos I had some items in the "video quality" section duplicated. Hope this helps you find some flaw in the code or hopefully there will be some for me besides manually replacing links. I will try to provide all the information you need for you

### Additional information

* PeerTube instance: 
  * URL: https://spacecomfort.miracleinsense.ru
  * Version: 6.0.0
  * NodeJS version: v21.2.0
  * Ffmpeg version: 4.4.4-0ubuntu1~20.04.sav1.1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by kirill2400** [comment]
I'm currently studying the peertube source code to get a rough idea of what the problem might be, but so far I can't catch the floo from the stage you need to transcode to published

**Comment by kirill2400** [comment]
Approximate debug log from the moment of transcoding 
[peertube8.log](https://github.com/Chocobozzz/PeerTube/files/13489445/peertube8.log)

**Comment by normen** [comment]
Maybe it's due to the new storyboard generation? It fails when it takes longer than 30min and all following actions fail as well then.

**Comment by kirill2400** [comment]
> Maybe it's due to the new storyboard generation? It fails when it takes longer than 30min and all following actions fail as well then.

It's probably unrelated, as this problem I'm having is pretty old, dating back to version 5. The behavior when trying to recode has not changed at all

**Comment by kirill2400** [comment]
> Maybe it's due to the new storyboard generation? It fails when it takes longer than 30min and all following actions fail as well then.

And storyboard generation still procced normally
![image](https://github.com/Chocobozzz/PeerTube/assets/30482699/a572160f-fed7-4494-9f32-3b6957c9ca98)

**Comment by kirill2400** [comment]
I did move it to webvideo and looks like its work from s3, but state not set to 1 automatically
![image](https://github.com/Chocobozzz/PeerTube/assets/30482699/0cbeec21-71aa-4efa-9ec5-96288cd204b9)
![image](https://github.com/Chocobozzz/PeerTube/assets/30482699/97cd6fab-a65d-4d93-bdd2-588ec4427926)

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I'm not sure to understand the issue. 

Can you paste the video URL?

**Comment by kirill2400** [comment]
> Hello,
> 
> I'm sorry but I'm not sure to understand the issue.
> 
> Can you paste the video URL?

https://spacecomfort.miracleinsense.ru/w/oA5TMg4PtxoYuCXzihavyJ
I will remove all webvideo files and reencode to hls for u

**Comment by kirill2400** [comment]
Interesting fact that because the links are not changed to the necessary links to the server object storage, as a result, when recoding files are not deleted and copied to the object storage
![image](https://github.com/Chocobozzz/PeerTube/assets/30482699/ee4f2e51-0eb2-4889-909d-e4605d16e5ad)

**Comment by kirill2400** [comment]
My guess is that the video record in the database has been corrupted, and the recode can't recover the right information and something breaks. I think I need to run some big query on the database to get all the necessary information about the video from the database tables, but unfortunately I'm bad at database queries and can't make such a complex query

**Comment by Chocobozzz** [comment]
If the files are in S3 you can set the `fileUrl` in` videoFile` table directly in the database using files ids returned by the server: https://spacecomfort.miracleinsense.ru/api/v1/videos/oA5TMg4PtxoYuCXzihavyJ

**Comment by kirill2400** [comment]
> If the files are in S3 you can set the `fileUrl` in` videoFile` table directly in the database using files ids returned by the server: https://spacecomfort.miracleinsense.ru/api/v1/videos/oA5TMg4PtxoYuCXzihavyJ

I agree, I did that once a long time ago to make it work, however if you request hls recode, it will recode, delete the old files from s3 and load the new ones and it will break again. The other videos don't break if you call recode, but only this one, and I think this video has something misassigned in the database somewhere else. Ideally would find that place and it might be possible to find some flaws in the code to improve it

**Comment by kirill2400** [comment]
Now we know that in terms of files it does everything correctly and loads everything where it should, but valid fileUrl are not written to the database correctly and state hangs on 6. So we narrow down the area of code where something may be wrong and which will help us to find out what the problem really is

**Comment by Chocobozzz** [comment]
> I agree, I did that once a long time ago to make it work, however if you request hls recode, it will recode, delete the old files from s3 and load the new ones and it will break again.

Can you do the process and paste all peertube logs from the point where you run again transcoding?

**Comment by kirill2400** [comment]
> > I agree, I did that once a long time ago to make it work, however if you request hls recode, it will recode, delete the old files from s3 and load the new ones and it will break again.
> 
> Can you do the process and paste all peertube logs from the point where you run again transcoding?

[peertube10.log](https://github.com/Chocobozzz/PeerTube/files/13502269/peertube10.log)
There is. But I accidentally ran systemctl restart peertube while encoding, but I don't think it affects anything, but it's visible in the logs so don't be surprised.

**Comment by Chocobozzz** [comment]
Thanks, can you go inside your database and paste the output of

```sql
select * from "videoJobInfo" inner join video ON video.id = "videoJobInfo"."videoId" where video.uuid = 'b6eb5a9d-f9a6-4c06-986c-76a432df9c46'
```

**Comment by Chocobozzz** [comment]
Try to run 

```sql
delete from "videoJobInfo" where "videoId" = 297
```

and retry the process

**Comment by kirill2400** [comment]
> Try to run
> 
> ```sql
> delete from "videoJobInfo" where "videoId" = 297
> ```
> 
> and retry the process

Awesome! It works. Can I consider this as a universal solution in case of similar problems? In other words if I delete an entry from videoJobInfo I can't permanently lose the video?
Can I consider this as a universal solution in case of similar problems? In other words if I delete an entry from videoJobInfo I can't permanently lose the video?

PS. What is also strange is that all the transcoding and moving to object storage tasks were completed, but the video still hung in state 6, but after waiting 2-3 minutes it was fixed. It's strange that there is some time when there is something unclear going on and it is not displayed for example on the "tasks" page, like the transcoding process.

![image](https://github.com/Chocobozzz/PeerTube/assets/30482699/029d9973-dca3-4d44-9b09-36e2795cfd37)

**Comment by kirill2400** [comment]
The segment file is finally available in S3 too, used to have to load it manually I guess
![image](https://github.com/Chocobozzz/PeerTube/assets/30482699/f30fef6d-e68f-4aa1-a87f-d163ab83d6f7)

**Comment by kirill2400** [comment]
Recoding again works properly, Thank You!
