### ISSUE TITLE
Cannot run service after upgrade to v6.0.0

### ISSUE THREAD

**Issue by toby3d** [Chocobozzz/PeerTube#6058]
### Describe the current behavior

After upgrading the working instance from v5.1.0 to v6.0.0 and updating the configuration following the information in CHANGELOG.md, the instance stopped starting at all, citing a missing module.

### Additional information

* PeerTube instance:
  * URL: https://video.toby3d.me/
  * Version: v6.0.0
  * NodeJS version: v18.17.1
  * Ffmpeg version: 4.1.11-0+deb10u1
* Server log(`journalctl`):
```log
Nov 28 21:32:03 vm155804.local systemd[1]: Started PeerTube daemon.
Nov 28 21:32:06 vm155804.local peertube[9651]: internal/process/esm_loader.js:74
Nov 28 21:32:06 vm155804.local peertube[9651]:     internalBinding('errors').triggerUncaughtException(
Nov 28 21:32:06 vm155804.local peertube[9651]:                               ^
Nov 28 21:32:06 vm155804.local peertube[9651]: Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:timers/promises
Nov 28 21:32:06 vm155804.local peertube[9651]:     at new NodeError (internal/errors.js:322:7)
Nov 28 21:32:06 vm155804.local peertube[9651]:     at Loader.builtinStrategy (internal/modules/esm/translators.js:289:11)
Nov 28 21:32:06 vm155804.local peertube[9651]:     at new ModuleJob (internal/modules/esm/module_job.js:63:26)
Nov 28 21:32:06 vm155804.local peertube[9651]:     at Loader.getModuleJob (internal/modules/esm/loader.js:258:11)
Nov 28 21:32:06 vm155804.local peertube[9651]:     at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:78:21)
Nov 28 21:32:06 vm155804.local peertube[9651]:     at async Promise.all (index 1)
Nov 28 21:32:06 vm155804.local peertube[9651]:     at async link (internal/modules/esm/module_job.js:83:9) {
Nov 28 21:32:06 vm155804.local peertube[9651]:   code: 'ERR_UNKNOWN_BUILTIN_MODULE'
Nov 28 21:32:06 vm155804.local peertube[9651]: }
Nov 28 21:32:07 vm155804.local systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
Nov 28 21:32:07 vm155804.local systemd[1]: peertube.service: Failed with result 'exit-code'.
Nov 28 21:32:07 vm155804.local systemd[1]: peertube.service: Service RestartSec=100ms expired, scheduling restart.
Nov 28 21:32:07 vm155804.local systemd[1]: peertube.service: Scheduled restart job, restart counter is at 3.
Nov 28 21:32:07 vm155804.local systemd[1]: Stopped PeerTube daemon.
```

**Comment by MattyBoombalatty** [comment]
Did you upgrade via the script?

**Comment by toby3d** [comment]
> Did you upgrade via the script?

Yes, as always. Nothing bad happened on this step.

I update instance via script, update my configuration and nginx files as described and only then run service by systemctl.

**Comment by Chocobozzz** [comment]
Hello,

How did you installed and upgrade nodejs to v18?

**Comment by toby3d** [comment]
> How did you installed and upgrade nodejs to v18?

This question made me once again double-check any points of nodejs existence on my server.

I've been using `n` for version control of `node` and `npm`, but even that doesn't work with PeerTube the way it should. The nodejs repository on the debian system didn't see fit to update the installed version, as the repository pointed to version 14. After forcing the nodejs repository to version 18 and updating it via `apt update && apt install nodejs` the startup went fine.
