### ISSUE TITLE
Manual upgrade to 6.0 failing due to incorrect check for webtorrent attribute

### ISSUE THREAD

**Issue by MrRoyce** [Chocobozzz/PeerTube#6066]
### Describe the problem

Manual upgrade to 6.0 is failing with the following error:
```
Please rename transcoding.webtorrent.enabled key to transcoding.web_videos.enabled in your configuration file
```

The code at `dist/core/initializers/checker-after-init.js` seems like its checking if the config does NOT have `webtorrent` then rename it to `web_videos`.  Should the "!" be removed from this check so the check works as expected?

```
    if (!content.includes('"webtorrent"')) {
      throw new Error('Please rename transcoding.webtorrent.enabled key to transcoding.web_videos.enabled in your configuration file')
    }
```

I do NOT have `webtorrent` anywhere in my config file.  The upgrade was successful when I removed the "!" from the check in that file.

### Additional information

* PeerTube instance URL: flashist.health
* PeerTube version: 6.0.1
* NodeJS version: 20.10
* Ffmpeg version: 4.4.2
* Redis version: 6.0.16
* PostgreSQL version: 14.9

**Comment by Chocobozzz** [comment]
Hello,

Do you use Docker ou a classic installation?

**Comment by MrRoyce** [comment]
Classic - Not Docker.

I went through the manual upgrade steps.

**Comment by MrRoyce** [comment]
➜ ls /var/www/peertube/config                                                                                                                                                         
default.yaml  local-production.json  production.yaml  production.yaml.bkup

sudo grep -r webtorrent /var/www/peertube/config                                                                                                                                    
/var/www/peertube/config/default.yaml:  # Same settings but for webtorrent videos
/var/www/peertube/config/default.yaml:  webtorrent:
/var/www/peertube/config/default.yaml:  # If you also enabled the webtorrent format, it will multiply videos storage by 2

**Comment by Chocobozzz** [comment]
How do you upgrade PeerTube? The [upgrade script](https://docs.joinpeertube.org/install/any-os#upgrade) should automatically copy the new `default.yaml` configuration: https://github.com/Chocobozzz/PeerTube/blob/develop/server/scripts/upgrade.sh#L89

**Comment by MrRoyce** [comment]
As usual, you found the issue.  

I didn't use the script, I was using the manual process and missed the step to copy the default.yaml. I'll close this issue.  Thanks for your help.

**Comment by binerf** [comment]
Hi,

I don't know if have to open a new issue or not as mine is the same error when I start Peertube but with Docker install:
```
# ls config/
custom-environment-variables.yaml  default.yaml  local-production.json  production.yaml
# sudo grep -r webtorrent config
config/custom-environment-variables.yaml:  webtorrent:
config/default.yaml:  # Same settings but for webtorrent videos
config/default.yaml:  webtorrent:
config/default.yaml:  # If you also enabled the webtorrent format, it will multiply videos storage by 2

```
I've updated manually "production.yaml" file as described in page https://github.com/Chocobozzz/PeerTube/releases/tag/v6.0.0

**Comment by Chocobozzz** [comment]
Make a copy first, but you can delete `docker-volume/config/default.yaml`,  `docker-volume/config/custom-environment-variables.yaml`

**Comment by binerf** [comment]
And it works !!! Many thanks !!!
