### ISSUE TITLE
Upgrade to version 6 failed

### ISSUE THREAD

**Issue by jpatje** [Chocobozzz/PeerTube#6067]
### Describe the problem

After following the guidelines to upgrade to version 6.0.0 and doing the upgrade, the peertube service fails to start.
Nginx and Production.yaml are updated according to the guidelines provided in the release notes.

systemctl status peertube:

× peertube.service - PeerTube daemon
     Loaded: loaded (/etc/systemd/system/peertube.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2023-11-29 22:03:59 CET; 39s ago
    Process: 22847 ExecStart=/usr/bin/node dist/server (code=exited, status=1/FAILURE)
   Main PID: 22847 (code=exited, status=1/FAILURE)
        CPU: 1.743s

Nov 29 22:03:59 zeus systemd[1]: peertube.service: Failed with result 'exit-code'.
Nov 29 22:03:59 zeus systemd[1]: peertube.service: Consumed 1.743s CPU time.
Nov 29 22:03:59 zeus systemd[1]: peertube.service: Scheduled restart job, restart counter is at 5.
Nov 29 22:03:59 zeus systemd[1]: Stopped PeerTube daemon.
Nov 29 22:03:59 zeus systemd[1]: peertube.service: Consumed 1.743s CPU time.
Nov 29 22:03:59 zeus systemd[1]: peertube.service: Start request repeated too quickly.
Nov 29 22:03:59 zeus systemd[1]: peertube.service: Failed with result 'exit-code'.
Nov 29 22:03:59 zeus systemd[1]: Failed to start PeerTube daemon.

Looking up Peertube's PID details with the command 'journalctl _PID=<PID> reveals the following:

Nov 29 22:03:59 zeus peertube[22847]: internal/process/esm_loader.js:74
Nov 29 22:03:59 zeus peertube[22847]:     internalBinding('errors').triggerUncaughtException(
Nov 29 22:03:59 zeus peertube[22847]:                               ^
Nov 29 22:03:59 zeus peertube[22847]: Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:timers/promises
Nov 29 22:03:59 zeus peertube[22847]:     at new NodeError (internal/errors.js:322:7)
Nov 29 22:03:59 zeus peertube[22847]:     at Loader.builtinStrategy (internal/modules/esm/translators.js:289:11)
Nov 29 22:03:59 zeus peertube[22847]:     at new ModuleJob (internal/modules/esm/module_job.js:63:26)
Nov 29 22:03:59 zeus peertube[22847]:     at Loader.getModuleJob (internal/modules/esm/loader.js:258:11)
Nov 29 22:03:59 zeus peertube[22847]:     at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:78:21)
Nov 29 22:03:59 zeus peertube[22847]:     at async Promise.all (index 1)
Nov 29 22:03:59 zeus peertube[22847]:     at async link (internal/modules/esm/module_job.js:83:9) {
Nov 29 22:03:59 zeus peertube[22847]:   code: 'ERR_UNKNOWN_BUILTIN_MODULE'
Nov 29 22:03:59 zeus peertube[22847]: }

After running the upgrade script, it said the upgrade was successful. But the service refused to start.
I also checked /var/log/nginx/peertube.error.log but there seem to be only connection related errors, probably unrelated to the issue I'm having.
How can I find out what's wrong?

Additional information: I set up redis hardening by adding a password in the requirepass section of /etc/redis/redis.conf.
Changing it back to default and restarting the server didn't help so I don't think this is the issue.

(For anyone interested in Redis hardening, [here](https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-redis-on-ubuntu-22-04) is the guide I followed. Although I'm not sure if all is compatible with how Peertube works.)

### Additional information

* PeerTube instance URL: video.yerunski.nl
* PeerTube version: 6.0.1
* NodeJS version: V20.10.0
* Ffmpeg version: 4.4.2
* Redis version: 7.2.2
* PostgreSQL version: 14.9

**Comment by Chocobozzz** [comment]
Hi,

This seems like the same issue as https://github.com/Chocobozzz/PeerTube/issues/6058

Can you check the version of nodejs by running `/usr/bin/node --version`?

**Comment by jpatje** [comment]
Hi and thanks!

The version is v14.21.3.

**Comment by Chocobozzz** [comment]
Then please upgrade to node 18 (see v6 important notes: https://github.com/Chocobozzz/PeerTube/releases/tag/v6.0.0)

You can get help from the dependencies documentation: https://docs.joinpeertube.org/support/doc/dependencies

**Comment by dhk2** [comment]
I had issues with multiple versions as well. The depency guide links weren't particularly helpful for me.

Method 2 from this article has worked with several systems so far.
https://www.hostingadvice.com/how-to/update-node-js-latest-version/
