### ISSUE TITLE
options.key must be a sshpk.PrivateKey

### ISSUE THREAD

**Issue by kodxana** [Chocobozzz/PeerTube#6068]
### Describe the current behavior

After upgrading my docker setup to version 6.0+ aparently I cant pull content from remote instances.

```
RequestError: options.key must be a sshpk.PrivateKey
    at Request._beforeError (file:///app/node_modules/got/dist/source/core/index.js:310:21)
    at Request.flush (file:///app/node_modules/got/dist/source/core/index.js:299:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.signRequest (/app/node_modules/@peertube/http-signature/lib/signer.js:362:14)
    at got.extend.Object.assign.hooks.beforeRequest (file:///app/dist/core/helpers/requests.js:49:35)
    at Request._makeRequest (file:///app/node_modules/got/dist/source/core/index.js:942:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Request.flush (file:///app/node_modules/got/dist/source/core/index.js:285:13)
```

### Steps to reproduce

Update docker to 6.0+ and try load subscribed instances.

### Describe the expected behavior

I should get response from remote instances

### Additional information

* PeerTube instance:
  * URL: peer.madiator.cloud
  * Version: 6.0.1
  * NodeJS version: Latest from chocobozzz/peertube:production-bookworm
  * Ffmpeg version: Latest from chocobozzz/peertube:production-bookworm

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Can you go inside your database and check your `peertube` local actor has a `privateKey`?

(don't paste the output in this issue to not leak your private key)

```sql
select * from actor where "preferredUsername" = 'peertube' and "serverId" is null;
```

**Comment by kodxana** [comment]
> Hello,
> 
> Can you go inside your database and check your `peertube` local actor has a `privateKey`?
> 
> (don't paste the output in this issue to not leak your private key)
> 
> ```sql
> select * from actor where "preferredUsername" = 'peertube' and "serverId" is null;
> ```

Looks like this values are null:
privateKey
publicKey
remoteCreatedAt and serverId

**Comment by Chocobozzz** [comment]
When did you install your instance? Can you reinstall it from scratch? On first run PeerTube should have created a private/public key for your account but it doesn't seem to have worked. You notice the bug in V6 now we also signs HTTP request to fetch content (whereas before we only signed requests to post content on remote instances).

**Comment by kodxana** [comment]
I think I installed my instance on version v5 though I would like avoid wiping whole instance as I have lot of videos uploaded and other users. How about manually regenerating priv/pub key pair?

**Comment by Chocobozzz** [comment]
You can try https://github.com/Chocobozzz/PeerTube/issues/5335#issuecomment-1272894875

Then go inside your database update the row with these values

**Comment by kodxana** [comment]
So looks like it worked:
```
const options = {
  modulusLength: 2048,
  publicKeyEncoding: {
    type: 'spki',
    format: 'pem'
  },
  privateKeyEncoding: {
    type: 'pkcs1',
    format: 'pem'
  }
}

require('crypto').generateKeyPair('rsa', options, (err, publicKey, privateKey) => {
  if (err) return console.error(err)

  console.log('Public key')
  console.log(publicKey)
  console.log('Private key')
  console.log(privateKey)
})
```
Generated keys here and then updated database

```
UPDATE actor
SET "publicKey" = 'your_public_key_string', "privateKey" = 'your_private_key_string'
WHERE id = 1;
```

Question is if it also could be the issue I wasn't able to federate with other instances :/

**Comment by Chocobozzz** [comment]
Yes couldn't federate without a private/public key for your `peertube` instance actor
