### ISSUE TITLE
Firefox：「We are sorry but it seems that PeerTube is not compatible with your web browser.」

### ISSUE THREAD

**Issue by TechnicalSuwako** [Chocobozzz/PeerTube#6070]
### Describe the current behavior

The message "We are sorry but it seems that PeerTube is not compatible with your web browser." appears on all Firefox browsers.
It seems that it can be used only with ungoogled-chromium.

![Screenshot_20231130_141719](https://github.com/Chocobozzz/PeerTube/assets/15627184/d0f5131c-4d00-40a7-9403-f2f51bfa9380)
![Screenshot_20231130_141907](https://github.com/Chocobozzz/PeerTube/assets/15627184/af434528-ebcd-40b5-8830-db11d6e2e0f3)
![Screenshot_20231130_141957](https://github.com/Chocobozzz/PeerTube/assets/15627184/525badec-a14a-47af-a328-0a2da5afebb0)

### Steps to reproduce

If you open PeerTube in Firefox, you'll understand.

### Describe the expected behavior

Visible condition

### Additional information

* PeerTube instance:
  * URL: https://video.076.moe/
  * Version: 6.0.1
  * NodeJS version: v18.18.2
  * Ffmpeg version: 6.0.1

* Browser name, version and platforms on which you could reproduce the bug: Firefox、Iceweasel、Icecat、Librewolf、FireDragon等
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

It seems CSP causes some issues loading the website: `img-src 'self' http://mitra.076.moe *.technicalsuwako.moe *.dangerous.software *.076.moe *.hozon.site; script-src 'self' *.hozon.site; style-src 'self' *.hozon.site;`

Please disable them and retry to load PeerTube

**Comment by TechnicalSuwako** [comment]
fixed! !
thank you.
