### ISSUE TITLE
Update button disabled when importing videos

### ISSUE THREAD

**Issue by diazepan** [Chocobozzz/PeerTube#6075]
### Describe the current behavior

Sometimes when I import a video, Peertube doesn't let me update the settings of the video. For example with this video
https://www.youtube.com/watch?v=jEluDr_SIXM

![imagen](https://github.com/Chocobozzz/PeerTube/assets/49599198/783a8713-a698-42e0-bcdf-903b5761e00a)

However, if I upload the video normally, the button is enabled and I can update the settings

![imagen](https://github.com/Chocobozzz/PeerTube/assets/49599198/4cddec4b-5a2a-491a-9467-fff287890503)

### Additional information

* PeerTube instance: 
  * URL:
  * Version: 6.0.0
  * NodeJS version: 18
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

Thanks, it's the same bug as https://github.com/Chocobozzz/PeerTube/issues/6062 that is already fixed and will be available in next peertube release
