### ISSUE TITLE
Increase the FPS limit

### ISSUE THREAD

**Issue by YaLTeR** [Chocobozzz/PeerTube#608]
Hello!

I love the idea of PeerTube, but the 30 FPS limit (set in place in https://github.com/Chocobozzz/PeerTube/commit/73c695919c6569bfb667c36fc5a6b9b862130a0d to fix https://github.com/Chocobozzz/PeerTube/issues/310) is, unfortunately, unacceptable for me and for a large part of the gaming-related content since it makes the videos look considerably worse than at, say, 60 FPS.

Many people nowadays have monitors with refresh rates at 144 Hz and even higher, and 60 Hz refresh rate is pretty much a guarantee. So it'd be great for the FPS limit to be bumped to _at the very least_ 60 FPS, and really amazing if the increment would be to 120 or 144 FPS.

AFAIK the main issue with high FPS videos is that browsers can struggle to play them, especially on lower end PCs. However, considering major streaming services such as YouTube and Twitch, 60 FPS isn't really an issue any more. As for higher refresh rates, I think having lower resolution transcodes (480p and below) have lower FPS (for instance, 60 or even 30 FPS for the lowest resolutions) could solve that issue. Another option is to have lower FPS transcodes for each resolution, however that would significantly increase the storage costs.

**Comment by Chocobozzz** [comment]
Implemented (as a test): https://github.com/Chocobozzz/PeerTube/commit/3a6f351b255d21ec42578632600ba699885f350e

We keep original FPS (hard limit of 60FPS) for resolution higher or equal to 720p. We limit to 30FPS for 480p/360p/240p.
