### ISSUE TITLE
Thumbnail Isn't Used on Mobile Browsers

### ISSUE THREAD

**Issue by cahlenlee** [Chocobozzz/PeerTube#6081]
### Describe the current behavior

When using a mobile device the thumbnails of a feed load, and then they quickly change to some random (and usually horrible) frame from the video. 

### Steps to reproduce

1. Go to https://moderndaywizards.org on a Android device
2. View thumbnails

### Describe the expected behavior

Author's selected thumbnail is displayed.

### Additional information

* PeerTube instance:
  * URL: https://moderndaywizards.org
  * Version: 5.2.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

How do you upload videos? If you use directly the REST API, you need to manually set the `previewfile` field (in addition to `thumbnailfile`:  https://docs.joinpeertube.org/api-rest-reference.html#tag/Video/operation/putVideo

**Comment by cahlenlee** [comment]
Here's the command I use in the script:

peertube-cli upload --channel-name cahlen --language en --category 13 --tags "$TAG1" --file "$VIDEOPATH" --thumbnail "$IMAGEPATH" --video-name "$TITLE" --video-description "$DESC"

So just adding this is all I need?

--previewfile "$IMAGEPATH"

**Comment by Chocobozzz** [comment]
> So just adding this is all I need?

Yes! I the future we'll merge `thumbnailfile` and `previewfile` I think
