### ISSUE TITLE
Embeded live video players claim browser is not the latest version

### ISSUE THREAD

**Issue by Sakrecoer** [Chocobozzz/PeerTube#6083]
### Describe the current behavior

When trying to embed a live, the player asks the user to install a newer version of Firefox. Even if the user is on the latest version.
![image](https://github.com/Chocobozzz/PeerTube/assets/3484593/805275a3-d585-4dc3-a670-c28740e21944)

Same happens in chromium (although the fact that it asks them to install Firefox might be a feature :sweat_smile: )

![image](https://github.com/Chocobozzz/PeerTube/assets/3484593/ecaacb6e-e31c-4813-834b-c167d22bd9fa)

**⚠️ Embedding VOD videos is fine.**

### Steps to reproduce

1. Create a live video
2. Click share button
3. Go to embed tab

### Describe the expected behavior

The embed link should display the player.

### Additional information

* PeerTube instance:
  * URL: v.basspistol.org
  * Version: 6.0.1
  * NodeJS version: v18.19.0
  * Ffmpeg version: 4.4.2-0ubuntu0.22.04.1

* Browser name, version and platforms on which you could reproduce the bug: Chromium 119.0.6045.199 snap, Mozilla Firefox 120.0.1
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Sakrecoer** [comment]
Sure, i noted it on 2 different instances with 6.0.1:

https://v.basspistol.org/w/1gSVye63Fa6DxkQTJrDVna
https://diode.zone/w/kBas5YH2cVHQ6mJukGGFEW

**Comment by Chocobozzz** [comment]
Thanks! Can you confirm the embed correctly works when the live is running?

**Comment by Sakrecoer** [comment]
Good idea, turns out embed displays fine if the live is running.

**Comment by Sakrecoer** [comment]
In fact, it seems to continue to display fine after the live has been stopped. As if it needs some sort of cache...

**Comment by Sakrecoer** [comment]
yes, new and old recurrent-live need a little splash of stream to become visible.

**Comment by Sakrecoer** [comment]
A couple of hours later, the videos that started showing the embedded player after some streaming are now showing the error message again.

**Comment by keesnobel** [comment]
I have exactly the same problem.
