### ISSUE TITLE
SEO needs more fixing: wrong canonical and missing `mainEntity` in JSON+LD of profile page

### ISSUE THREAD

**Issue by Sakrecoer** [Chocobozzz/PeerTube#6090]
### Describe the current behavior

The JSON+LD of user and channel pages (profile pages) are missing a `mainEntity` field, which renders it invalid on many of the main search engines.

examples from two different servers running 6.0.1: 
- https://search.google.com/test/rich-results/result/r%2Fprofile-page?id=41UKdaXetFBkkKfv_XcVEg
- https://search.google.com/test/rich-results/result?id=uUoeS-n-t-skiYDNu7YZjQ
- https://search.google.com/test/rich-results/result?id=SICJQV0YzcV8Ify7cazK7Q
- https://search.google.com/test/rich-results/result?id=LkItC1KKiQb0ykZSrRz-KQ

Here's a guide on how it should be formatted:
https://developers.google.com/search/docs/appearance/structured-data/profile-page

Another thing is that profiles have canonical URL listed as: `https://domain.tld/a/user` But these pages redirect to: `https://domain.tld/a/user/video-channels`. Same goes for channel pages which are listed in the sitemap as `https://domain.tld/c/channelname` but redirect to `https://domain.tld/c/channelname/videos`

### Additional information

* PeerTube instance:
  * URL: v.basspistol.org
  * Version: 6.0.1
  * NodeJS version: v18.19.0

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/2fde12d7e1843260c66773ca89a6ac889791b6d3
