### ISSUE TITLE
I can't found the file ,  peertube.template

### ISSUE THREAD

**Issue by weiyi88** [Chocobozzz/PeerTube#6091]
### Describe the problem

I encountered problems when using docker-compoe. When "docker-compoe up" was displayed,
 "peertube-webserver-1 exited with code 1" was displayed.
Then, I docker logs peertube-webserver-1 find the output situation is

```
[root@iZ7xva1a80i0lm5ry6lmc4Z ~]# docker logs peertube-webserver-1 | tail
envsubst: error while reading "standard input": Is a directory
envsubst: error while reading "standard input": Is a directory
envsubst: error while reading "standard input": Is a directory
envsubst: error while reading "standard input": Is a directory
```
and i realized 
```
webserver:
...
        source: ./docker-volume/nginx/peertube
        target: /etc/nginx/conf.d/peertube.template
...
```
I don't have peertube.template

 

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by Chocobozzz** [comment]
Hello,

Please use the forum for sysadmin related questions: https://framacolibri.org/c/peertube

You need to follow docker documentation, in particular https://docs.joinpeertube.org/install/docker#webserver
