### ISSUE TITLE
Incorrect process of replacing any video

### ISSUE THREAD

**Issue by kirill2400** [Chocobozzz/PeerTube#6095]
### Describe the current behavior

Incorrect process of replacing any video with any video (and web-torren turned off).

### Steps to reproduce

Watch video
https://spacecomfort.miracleinsense.ru/w/dfZ92j2gKez6F9GC863BgS

### Describe the expected behavior

The video should seamlessly replace and load on the S3 and work without additional steps

### Additional information

* PeerTube instance:
  * URL: https://spacecomfort.miracleinsense.ru
  * Version: 6.0.1
  * NodeJS version: v21.2.0
  * Ffmpeg version: 4.4.4-0ubuntu1~20.04.sav1.1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/6096 as I think that fixing it should also fix this one
