### ISSUE TITLE
When deleting videos, files are not deleted from the object-storage server

### ISSUE THREAD

**Issue by kirill2400** [Chocobozzz/PeerTube#6096]
### Describe the current behavior

Deleting a video does not delete files from the s3 server. I haven't checked deletion during encoding, but maybe the "prune storage" tool helps here. But how do I clean s3 now?

### Steps to reproduce

1. Upload video
2. Wait for end transcoding
3. Remove video
4. Check s3 server

Watch video
https://spacecomfort.miracleinsense.ru/w/hEVy7ekSsAyP6Hg2Jc7k71

### Describe the expected behavior

When deleting videos, the files should be deleted from the object-storage server

### Additional information

* PeerTube instance:
  * URL: https://spacecomfort.miracleinsense.ru
  * Version: 6.0.1
  * NodeJS version: v21.2.0
  * Ffmpeg version: 4.4.4-0ubuntu1~20.04.sav1.1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Please paste server logs around the time when you delete the video. May be related to https://framacolibri.org/t/peertube-setup-with-minio-s3-object-storage-system-cannot-delete-content-from-bucket/19722

**Comment by Chocobozzz** [comment]
Then I think it's the same issue as described in https://framacolibri.org/t/peertube-setup-with-minio-s3-object-storage-system-cannot-delete-content-from-bucket/19722

**Comment by kirill2400** [comment]
> Then I think it's the same issue as described in https://framacolibri.org/t/peertube-setup-with-minio-s3-object-storage-system-cannot-delete-content-from-bucket/19722

Yeah, that seems to be the problem. Can you make a prune-storage script for object-server?

**Comment by Chocobozzz** [comment]
> Yeah, that seems to be the problem. Can you make a prune-storage script for object-server?

Please create a dedicated issue.
