### ISSUE TITLE
Add Highlight Reel/Clips Feature

### ISSUE THREAD

**Issue by MattyBoombalatty** [Chocobozzz/PeerTube#6098]
### Describe the problem to be solved

People are unable to create clips, or extract segments and highlights of a livestream/upload. 

### Describe the solution you would like

I think it would be pretty cool to grant this feature to locally authenticated users, so that they could create clips or highlights from livestreams and uploads to post as shortened segments on platforms. Some of the components of this would be:

1. Ability to create up to X second/minute highlights of an upload or live stream.
2. Automatically expire the clips after a period of time (to save space). The hard limit could be set by the administrator.
3. Remote runners could be used to take the clip, process it, and send it to either object storage or local storage, however it is configured.
4. The user who created the clip would be notified, and a page on their profile would display all the clips they've captured.

**Comment by Chocobozzz** [comment]
Hi,

Thanks for this interesting idea. Can you propose it on https://ideas.joinpeertube.org/ so other users can upvote/discuss on it?
