### ISSUE TITLE
Does not load meta information when sharing a link

### ISSUE THREAD

**Issue by Barkoczy** [Chocobozzz/PeerTube#6099]
Since version 6 it doesn't load meta information when sharing a link for example to telegram facebook and others.

**Comment by Barkoczy** [comment]
I don't understand it, but everything is working at the moment. None of the shared links to any of the videos worked at all.

For example share same links:

https://video.barkoczy.social/w/nF4jkVT8xSrmBNAHXDN9i9

https://video.barkoczy.social/w/jexqXMgofFdswFAkCJFNCw

**Comment by Chocobozzz** [comment]
Hello,

If it's working now maybe the instance had network/load issues at the time you shared the links initially? Anyway I'm closing the issue but don't hesitate to comment if you still notice the bug in the future.
