### ISSUE TITLE
Add chapters with textarea

### ISSUE THREAD

**Issue by Atn-D** [Chocobozzz/PeerTube#6100]
### Describe the problem to be solved

Since PeerTube 6, chapters are automatically imported when you import a YouTube video, and it's great!

On the other hand, it's a lot of work to set them up on videos imported on my instance before this feature.

---

:fr: 
Depuis PeerTube 6 les chapitres s’importe automatiquement quand on importe une vidéo YouTube et c’est génial !

Par contre, le travail est énorme pour les mettre en place sur les vidéos importés sur mon instance avant cette fonctionnalité.

---

### Describe the solution you would like

Many of the channels I host have chapters in the form of :
00:00 chapter 1
00:42 chapter 2
03:14 chapter 3

It would be nice to be able to simply copy and paste this already formatted information into a textarea, rather than having to enter it one by one in the form currently in place.

(I'm talking about an additional input option, because the current form is actually much easier to use for non-technical people).

---

:fr: 
Beaucoup des chaines que j’héberge ont dans leur description le chapitrage sous forme de :
00:00 chapitre 1
00:42 chapitre 2
03:14 chapitre 3

Il serait agréable de pouvoir simplement copier puis coller ces informations déjà formatées dans un textarea, plutôt que de devoir les saisir un a un dans le formulaire actuellement en place.

(je parle bien d’une option de saisie en plus, car le formulaire actuel est effectivement bien plus simple à utiliser pour des personnes non techniques)

**Comment by Chocobozzz** [comment]
Hi,

You can set chapters directly from the description, like on youtube if you prefer :)

**Comment by Atn-D** [comment]
Hello,
If there was a way to do it automatically from the video description, it would require even less work! :star_struck: 

Is this already possible and I haven't seen the option, or is this a proposal?

**Comment by Chocobozzz** [comment]
It's already possible. I updated [the documentation](https://docs.joinpeertube.org/use/create-upload-video#chapters) to inform users of such method to create chapters.

**Comment by Atn-D** [comment]
Thank you, after various tests, for the already existing videos which already have this information in description, I must :
edit, cut description, save, edit, paste, save
so that it's finally taken into account
