### ISSUE TITLE
Meta description does not escape quotes

### ISSUE THREAD

**Issue by Sakrecoer** [Chocobozzz/PeerTube#6101]
### Describe the current behavior

The `og:description` property in the `<meta>` tags in the `<head>` does not escape quotes... 

Example:
https://v.basspistol.org/w/f3aDVhguVrVV15LmGJV4cc

Since there are quotes (`"`) in the description, the meta tag becomes very funky

```
<meta property="og:description" content="Extrait du EP " rox="" -="" la="" route="" du="" soi="" 2="" :="" correspondance="" "="" https:="" roxafrowest.bandcamp.com="" album="" rox-la-route-du-soi-2-correspondance="" textes="" &amp;="" rap="" prod:="" dj="" dan="" vidéo="" chispa="" pour="" geneva..."="">
```

### Additional information

* PeerTube instance:
  * URL: v.basspistol.org
  * Version: 6.0.2
  * NodeJS version: v18.19.0
  * Ffmpeg version: ffmpeg version 4.4.2-0ubuntu0.22.04.1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/edc695263f5a33ee012d50fa914ee10a385c9433

**Comment by Sakrecoer** [comment]
You are the best! Thank you! <3
