### ISSUE TITLE
Cannot install or remove plugins

### ISSUE THREAD

**Issue by TheCableGuy99** [Chocobozzz/PeerTube#6104]
### Describe the current behavior

I'm trying to install or remove plugins and I'm getting an error during the install or removal.

`  [www.mydomain.com:443] 12/12/2023, 11:05:17 PM.892 error: Cannot install plugin peertube-plugin-hardware-transcode-vaapi, removing it... {
  "err": {
    "err": {
      "stack": "Error: Command failed: yarn add peertube-plugin-hardware-transcode-vaapi@0.2.9\nwarning package.json: No license field\nwarning No license field\n(node:22637) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.\n(Use `node --trace-deprecation ...` to show where the warning was created)\nerror Error: ENOTSUP: operation not supported on socket, symlink '../../../mediainfo.js/dist/cli.js' -> '/var/www/peertube/storage/plugins/node_modules/peertube-plugin-upload-limits/node_modules/.bin/mediainfo.js'\n\n    at genericNodeError (node:internal/errors:956:15)\n    at wrappedFn (node:internal/errors:510:14)\n    at ChildProcess.exithandler (node:child_process:422:12)\n    at ChildProcess.emit (node:events:519:28)\n    at maybeClose (node:internal/child_process:1105:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:305:5)",
      "code": 1,
      "killed": false,
      "signal": null,
      "cmd": "yarn add peertube-plugin-hardware-transcode-vaapi@0.2.9"`

### Steps to reproduce

1. Try and install or uninstall a plugin

### Describe the expected behavior

The plugin installs or uninstalls

### Additional information

* PeerTube instance:
  * URL: Private 
  * Version: 6.0.2
  * NodeJS version: 21.4.0
  * Ffmpeg version: 4.4.2-0ubuntu0.22.04.1

* Browser name, version and platforms on which you could reproduce the bug: Edge, 120.0.2210.61 (Official build) (64-bit), Windows 11 Pro
* Link to browser console log if relevant: N/A 
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): Logs as above from "sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run parse-log -- --level info" 

Thanks.

**Comment by Chocobozzz** [comment]
Hello,

What is your OS? Is it a classic Ubuntu?

**Comment by TheCableGuy99** [comment]
Hey,

Firstly this was working so I don't know whats gone on.  But it's an Orange Pi 5 and their download of Ubuntu. 

I'm currently in the middle of re-installing over the top of itself to see if it resolves it but any ideas would be great?

Thanks.

**Comment by Chocobozzz** [comment]
I'm sorry but I don't know. But it's more a system issue as PeerTube requires that your filesystem supports symlinks.

**Comment by TheCableGuy99** [comment]
Gotta love how you just presume the system doesn't support symlinks and close the case.... of course it supports symlinks! It's still a fully functional O/S, just made to run on the Orange Pi's architecture.

**Comment by Chocobozzz** [comment]
Unfortunately, I don't have any more ideas than that based on the error message `Error: ENOTSUP: operation not supported on socket, symlink '../../../mediainfo.js/dist/cli.js'`

As a workaround you can also remove the `peertube-plugin-upload-limits` plugin

**Comment by TheCableGuy99** [comment]
that;s fine, can you just tell me how I can manually install and remove plugins (and download them) without the GUI or peertube-cli and I should be able to get it working again please? i.e. How to do it completely manually if possible?

Thanks.

**Comment by dhk2** [comment]
First thing I'd try is deleting /var/www/peertube/storage/plugins, it's fixed a variety of screwed up plugin situations i've found myself in.

A more prudent man might back it up first.

**Comment by JohnXLivingston** [comment]
> First thing I'd try is deleting /var/www/peertube/storage/plugins, it's fixed a variety of screwed up plugin situations i've found myself in.
> 
> A more prudent man might back it up first.

For the livechat, this will lose almost all your configuration. You should keep `/var/www/peertube/storage/plugins/data`.
