### ISSUE TITLE
Video speed and quality still not memorized in 6.0.2

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#6105]
### Describe the current behavior

despite of in the CHANGELOG it was specified that now video player save the settings of volume, speed and quality for now I just can see the volume keeping the same value for all video playing on all pages.
but speed and quality still go back to a generic settings. Am I missing something?

**Comment by Chocobozzz** [comment]
Hello,

quality is not memorized but video speed should keep the same value when the player loads another video (so for example when auto playing the next video in a playlist or in "other videos"). 

The setting is not kept when you refresh your web browser.

**Comment by ROBERT-MCDOWELL** [comment]
sad because the volume keeps the setting whatever you change pages, refresh it or autoplay. why not speed and quality too? is it managed by client cookie?

**Comment by Chocobozzz** [comment]
You can create dedicated feature request for each parameter you want to save with the use case so we can discuss about this :)

The thing is that I think people may set a custom playback rate for a particular watch session (podcast for example) but not keep it the day after when they'll listen to music. But we can of course discuss it in an issue.

Regarding the quality, the HLS player automatically choose the appropriate one depending on your web browser bandwidth in "Auto" mode. But I agree we should remember the quality selection (480p, 240p, "Auto" etc) in web browser local storage like we do for the volume/mute.

**Comment by ROBERT-MCDOWELL** [comment]
ok I'm going to open a Feature request so.. thanks!
