### ISSUE TITLE
Discover page isn't refreshing on Logout 

### ISSUE THREAD

**Issue by raazkarkee405** [Chocobozzz/PeerTube#6106]
### Describe the current behavior

Currently I have a plugin that filters videos from the list of videos in the discover, trending, etc. pages. To filter the videos I have used the `filter:api.overviews.videos.list.result` server hook for discover page and `filter:api.videos.list.result` server hook for other pages. 
The current behavior which is creating problem for my plugin is that if the landing page of the instance is Discover videos(/videos/overview), and on logging out from the discover page i'm able to view the videos which should not be visible on logout. 
I have tested on all the other pages by changing the landing page and following the above process. I haven't found any issues but what I noticed is that on logout discover page is keeping cache but on refresh I get what I wanted. 

**Discover Page**
<img src="https://github.com/Chocobozzz/PeerTube/assets/26194365/19894341-55ab-4cbe-beec-c5087ffcb736" width="400">
<img src="https://github.com/Chocobozzz/PeerTube/assets/26194365/469c41ed-d2be-415c-a94d-7809e7e5246e" width="400">

**On Logout**
<img src="https://github.com/Chocobozzz/PeerTube/assets/26194365/d3afae52-3ce9-4f0d-a514-e9cc0b482419" width="400">

**Trending Page**
<img src="https://github.com/Chocobozzz/PeerTube/assets/26194365/e62b5d56-b8a3-4327-8b03-c3931dd8be73" width="400">
<img src="https://github.com/Chocobozzz/PeerTube/assets/26194365/075a33b5-bc8b-4802-9ded-25259abfea06" width="400">

**On Logout**
<img src="https://github.com/Chocobozzz/PeerTube/assets/26194365/fd3ee5c6-7b3f-4f15-bcf7-5a3f09892c68" width="400">

### Steps to reproduce

1. Go to /admin/config/edit-custom#basic-configuration and set the Landing page to Discover videos (/videos/overview).
2. Go to discover page and logout. (On logout the discover page won't refreshing)
3. Follow the similar process on 1 and 2 with Trending videos (/videos/trending). (On logout the trending page will refresh)

### Describe the expected behavior

As similar to other pages (trending, recently-added, local videos, etc) the discover page should also refresh on log out.

### Additional information

* PeerTube instance:
  * URL:  Private
  * Version: 5.2.0 and above
  * NodeJS version: 18.16.0

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/bd1dd8fd95c345b37e1fcc0051f1f818fe113422
