### ISSUE TITLE
Non-federated remote live does not start

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#6111]
### Describe the current behavior

If i open a remote live on my instance, by copy-pasting the url: the video won't start when the live begins.

### Steps to reproduce

1. Copy paste the url of a non-started live in the searchbox (we must not follow the remote instance)
2. open the video
3. wait for the live to start
4. it won't play. Even if i reload the page, or search again the url

The video stay marked as "non started", event if the live started.
I manage to fix this by adding a like to the video, then refreshing the page.

### Describe the expected behavior

Live should start at some point.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

When you fetch a remote video, you don't subscribe to the account/channel/instance and so the origin instance doesn't send related video events like `Update` activities. I'm not sure how we can improve this behaviour

**Comment by JohnXLivingston** [comment]
> When you fetch a remote video, you don't subscribe to the account/channel/instance and so the origin instance doesn't send related video events like `Update` activities. I'm not sure how we can improve this behaviour

That's what i thought...

Maybe just fetch again the remote data on window reload? So that if the user just make f5, the live will start.

Or maybe is it possible to just subscribe to a single video throught AP?

**Comment by Chocobozzz** [comment]
> Or maybe is it possible to just subscribe to a single video throught AP?

No it's not possible as you can only subscribe to actors in AP

**Comment by JohnXLivingston** [comment]
@Chocobozzz , Is think i have a related bug with Peertube v6.2.0-RC1.

On my freshly updated instance, on the "recent video" page, i have a live started 2 month ago:

https://videos.john-livingston.fr/videos/recently-added

![image](https://github.com/Chocobozzz/PeerTube/assets/38844060/71bf63f5-bed2-4962-9b68-627e3924f1dc)

If i remember well, I opened this live by seaching its url in the search bar. My instance was not federating with the original instance when the live occured.

Here is the link to the live on my instance:
https://videos.john-livingston.fr/w/6ZnQrdr4jwT6RT9E8nCofZ
And the original:
https://video.passageenseine.fr/w/30808b66-c7cd-4dc3-af0e-8c1324e4f64d


For the record, i followed the instance starting at june the 9th (but the live was before, in april):
![image](https://github.com/Chocobozzz/PeerTube/assets/38844060/2027cb6d-02fd-42e7-8bb4-579fd0b46f3f)

**Comment by Chocobozzz** [comment]
I'm not sure it's related, the live is also broken on the origin instance: https://videos.john-livingston.fr/w/6ZnQrdr4jwT6RT9E8nCofZ

**Comment by JohnXLivingston** [comment]
> I'm not sure it's related, the live is also broken on the origin instance: https://videos.john-livingston.fr/w/6ZnQrdr4jwT6RT9E8nCofZ

Oh yes, you are right. I did not notice the other day.
Removing the instance from my followings removes the live from my front page. Adding it again make it come back. So yes, this is not the bug i thought, and the issue is on `[video.passageenseine.fr]`.

I'm closing this issue.
