### ISSUE TITLE
Remote ActivityPub subscribers no longer getting updates since v6.0.1

### ISSUE THREAD

**Issue by CorpulentBrony** [Chocobozzz/PeerTube#6113]
### Describe the current behavior

I upgraded to v6.0.1 on 11/30.

Something occurred on 12/1 that stopped all ActivityPub subscriptions from being broadcast from my instance.  There are currently around 74,070 activitypub-http-broadcast jobs in a waiting state.

There are about 10 jobs with dates from 12/3 (processed on today) with the following error message:

```
Error: Timeout
    at Timeout.<anonymous> (file:///var/www/peertube/versions/peertube-v6.0.1/packages/core-utils/dist/common/promises.js:12:42)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

The way I discovered this issue was the @peertube@pony.tube account followed from my Mastodon instance had stopped displaying newly posted videos, with the most recent being from 12/1.

### Steps to reproduce

1. Install PeerTube v6.0.1
2. Follow @peertube@instance.name from an external ActivityPub subscriber (i.e., Mastodon)
3. Upload video to instance

### Describe the expected behavior

Newly uploaded public videos should be visible and posted not only to the @peertube@instance.name account but also the individual user accounts.

### Additional information

* PeerTube instance: 
  * URL: https://pony.tube
  * Version: v6.0.1
  * NodeJS version: v18.18.2
  * Ffmpeg version: N-67885-gcc86343b96-static

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

Were you using node 16 with your previous PeerTube version?

If yes, it may be related to IP DNS/IPV6. Can you try to run PeerTube using `--dns-result-order=ipv4first` node option?
