### ISSUE TITLE
start url parameter doesn't always work

### ISSUE THREAD

**Issue by Nodja** [Chocobozzz/PeerTube#6114]
### Describe the current behavior

When using urls with the start parameter (the ones you get when you right click -> copy the video url at the current time), the video player jumps to the wrong position if the seconds are not in the url. 

Examples:
`start=5h10m` jumps to 5s instead
`start=5h10m0s` works properly and jumps to 5h10m

5h0s also works properly (omitting the minutes).

BTW: If the player is at 5:00:00 it'll generate `start=5h` when you right click -> copy the video url at the current time and I think this was always the case since we have a bunch of links in our wiki pointing to positions that don't work anymore. I believe this started happening when we updated to 6.x

### Steps to reproduce

1. Go to https://peertube.nodja.com/w/ge4Vk8A4yCT8cbNQCz5LAs?start=5h10m

### Describe the expected behavior

The video should jump to 5h10m instead of 5s.

### Additional information

* PeerTube instance:
  * URL: https://peertube.nodja.com
  * Version: 6.0.2
  * NodeJS version: I'm using the official docker image
  * Ffmpeg version: I'm using the official docker image

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/ea685879bb19ea2ee787f52e7118b8641809c70e
