### ISSUE TITLE
S3 download fails when the filename contains an emoticon

### ISSUE THREAD

**Issue by 3unjee** [Chocobozzz/PeerTube#6117]
### Describe the current behavior

When downloading a video resource with a title containing an emoticon from an S3 bucket the request fails with the following:

![chrome_DAYnkAbm8B](https://github.com/Chocobozzz/PeerTube/assets/17432415/38924ecc-7455-43a4-9f0a-96ca2a027372)

### Steps to reproduce

1. Use Peertube 6.0.1 + transcoding OFF
2. Upload a video and set a title with an emoticon like "Hello 🙊"
3. Click on "..." and Download
4. Clilck the Download button

### Describe the expected behavior

The video resource should be retrieved properly from S3

### Additional information

* PeerTube instance: 6.0.1

**Comment by Chocobozzz** [comment]
Can you try to replace in `dist/core/lib/object-storage/pre-signed-urls.js` `ResponseContentDisposition: `attachment; filename=${downloadFilename}`` by `ResponseContentDisposition: `attachment; filename=${encodeURI(downloadFilename)}``? (line `13` and line `26`)

**Comment by 3unjee** [comment]
Yes, both changes seem to solve it on my side. Tested in production

**Comment by Chocobozzz** [comment]
Thanks! Then it's fixed by https://github.com/Chocobozzz/PeerTube/commit/c93b7088c2a6bffd0cec24909797bde4cb6095b8
