### ISSUE TITLE
"You don't have any external auth plugin enabled" but It's not

### ISSUE THREAD

**Issue by Lastorder-DC** [Chocobozzz/PeerTube#6119]
### Describe the current behavior

I installed and configured `auth-oauth2-mastodon` but page still says "You don't have any external auth plugin enabled" and `auth-oauth2-mastodon` still not works

I have searched for how to "enable" plugin and searched for issue but there are no such thing as "enable plugin" at [docs](https://docs.joinpeertube.org/)

### Steps to reproduce

1. Install `auth-oauth2-mastodon` plugin
2. Go to basic config page
3. "Redirect users on single external auth when users click on the login button in menu" setting still says "You don't have any external auth plugin enabled" and mastodon login also not works

### Describe the expected behavior

`auth-oauth2-mastodon` works and "You don't have any external auth plugin enabled" message disappear

### Additional information

* PeerTube instance:
  * URL: -
  * Version: 6.0.2
  * NodeJS version: v18.17.1
  * Ffmpeg version: 6.0-6ubuntu1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

I think you need to configure `auth-oauth2-mastodon` plugin on `peertube.example.com/admin/plugins/show/peertube-plugin-auth-oauth2-mastodon`

**Comment by Lastorder-DC** [comment]
@Chocobozzz I already configured `auth-oauth2-mastodon` plugin.

**Comment by Chocobozzz** [comment]
Do you see the external login box in the login page when `Redirect users on single external auth when users click on the login button in menu` is not checked?

If no, can you update plugin settings and paste peertube logs?

**Comment by Lastorder-DC** [comment]
https://github.com/agates/peertube-plugin-auth-oauth2-mastodon

Found reason. Plugin README says `Identity access token URL parameter name` is `Required if the access token is sent via the URL` but It is actually just `required`(According to code)

I think appending like `Check log for details` might helpful for beginners, as `not enabled` is bit confusing.
