### ISSUE TITLE
Why do you need P2P stream?

### ISSUE THREAD

**Issue by AsilbekKeldiyarov** [Chocobozzz/PeerTube#6120]
### Describe the current behavior

Good afternoon! I have a movies website. The number of daily visitors to my site is around 100,000. But I am suffering with bandwidth on my servers with my site.

I have 8 web servers. Each has 1Gbps and unlimited traffic. Every evening, all my servers are running at full 1 Gbps and each server has 900-1200 online users. And they write in the discussion that they are having trouble watching and downloading movies from the site. Because the number of users is high in the evening and the network speed is not enough 1gb/s.

I have a few questions about your P2P stream:

Will I solve this network speed problem if I install PeerTube on all my servers? Actually my servers are running at full 1gbps in the evening, can I increase this via P2P? Because I liken your P2P servers to a torrent system, user-to-user data is transmitted. Therefore, the speed will not be a problem at all.

Thank you in advance!

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Closing as the question has already been answered on https://framacolibri.org/t/why-do-you-need-p2p-stream/19945/2
