### ISSUE TITLE
Daemon fails to start with "Error: Configuration property 'rates_limit.plugins.window' is not defined" after upgrade from 5.2.1 to 6.0.2 

### ISSUE THREAD

**Issue by TankieTanuki** [Chocobozzz/PeerTube#6124]
### Describe the problem

The `peertube.service` daemon fails to start after a system upgrade which included PeerTube.

I am using the package in the [Arch user repository](https://aur.archlinux.org/packages/peertube). It installs to `/usr/share/webapps/peertube` and uses `/var/lib/peertube/storage` as the storage directory.

I made changes specified in the important notes sections of the [release notes](https://github.com/Chocobozzz/PeerTube/releases) for v6.0.0-rc.1, v6.0.0, v6.0.1, and v6.0.2.

Here's the systemd log:

```
Dec 19 02:53:42 <hostname> systemd[1]: Started PeerTube daemon.
Dec 19 02:53:43 <hostname> peertube[2440]: /usr/share/webapps/peertube/node_modules/config/lib/config.js:179
Dec 19 02:53:43 <hostname> peertube[2440]:     throw new Error('Configuration property "' + property + '" is not defined');
Dec 19 02:53:43 <hostname> peertube[2440]:           ^
Dec 19 02:53:43 <hostname> peertube[2440]: Error: Configuration property "rates_limit.plugins.window" is not defined
Dec 19 02:53:43 <hostname> peertube[2440]:     at Config.get (/usr/share/webapps/peertube/node_modules/config/lib/config.js:179:11)
Dec 19 02:53:43 <hostname> peertube[2440]:     at file:///usr/share/webapps/peertube/dist/core/initializers/config.js:178:49
Dec 19 02:53:43 <hostname> peertube[2440]:     at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
Dec 19 02:53:43 <hostname> peertube[2440]:     at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
Dec 19 02:53:43 <hostname> peertube[2440]:     at async loadESM (node:internal/process/esm_loader:28:7)
Dec 19 02:53:43 <hostname> peertube[2440]:     at async handleMainPromise (node:internal/modules/run_main:113:12)
Dec 19 02:53:43 <hostname> peertube[2440]: Node.js v21.4.0
Dec 19 02:53:43 <hostname> systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
Dec 19 02:53:43 <hostname> systemd[1]: peertube.service: Failed with result 'exit-code'.
Dec 19 02:53:43 <hostname> systemd[1]: peertube.service: Consumed 2.483s CPU time.
Dec 19 02:53:43 <hostname> systemd[1]: peertube.service: Scheduled restart job, restart counter is at 1.
```

Apologies in advance in case it's a problem with the AUR package (or me) and not PeerTube.

### Additional information

* PeerTube version: 6.0.2
* NodeJS version: 21.4.0
* Ffmpeg version: 6.1
* Redis version: 7.2.3
* PostgreSQL version: 16.1

**Comment by Chocobozzz** [comment]
Hi,

Where is your `production.yaml`?

In the [installation guide](https://docs.joinpeertube.org/install/any-os#peertube-configuration) or [upgrade guide](https://docs.joinpeertube.org/install/any-os#peertube-instance) we advise to copy `default.yaml ` that contains new configuration keys to their default values. If you don't, them you need to ensure your `production.yaml` contains all keys defined in `production.yaml.example`

**Comment by TankieTanuki** [comment]
You're exactly right. I was missing new configuration keys from `/etc/peertube/poduction.yaml.pacnew`. When I added them to `/etc/peertube/production.yaml` the problem was fixed. Silly me.

Thank you very much! I love your software. 🙂
