### ISSUE TITLE
Follow redirects when downloading input file from remote runner

### ISSUE THREAD

**Issue by polyhb** [Chocobozzz/PeerTube#6125]
### Describe the problem to be solved

We are currently using remote runner independently from the Peertube application and we struggle with a traffic problem. The runner is using a download URL in the payload and is making a `POST` request with the `runnerToken`  and `jobToken` in the body for security verification. If we try to set, for example, a s3 URL in the payload, then the download won't work because it is a POST request.
Thus,  we are forced to make an endpoint that will stream the video file through our application causing resources problems like memory or traffic issue.

### Describe the solution you would like

Making the download a `GET` request and set the `runnerToken` and `jobToken` as the query parameter or in a header, should be enough to make it work with a s3 URL. While this solution could be enough, it is still not optimal:
- We are no more checking the  `runnerToken` or `jobToken`
- video download URL is set in the payload at the job creation. If it is signed and have an expiration date, we could be in case where the runner took too much time to take this job and the URL is no more valid.

A more optimal solution would be to make the request follows redirect. Doing this, we keep our endpoint unchanged, can generate an S3 URL and then return an HTTP redirect to this URL.

A quick win could be using a library like [follow-redirects](https://www.npmjs.com/package/follow-redirects)

```JSON
{
  "name": "@peertube/peertube-runner",
  "version": "0.0.7",
  "type": "module",
  "main": "dist/peertube-runner.js",
  "bin": "dist/peertube-runner.js",
  "engines": {
    "node": ">=16.x"
  },
  "license": "AGPL-3.0",
  "dependencies": {
    "follow-redirects": "1.15.3"
  },
  "devDependencies": {
    "@types/follow-redirects": "1.14.4",
    "@commander-js/extra-typings": "^10.0.3",
    "@iarna/toml": "^2.2.5",
    "env-paths": "^3.0.0",
    "net-ipc": "^2.0.1",
    "pino": "^8.11.0",
    "pino-pretty": "^10.0.0"
  }
}
```
And changing the file:  [https.js](https://github.com/Chocobozzz/PeerTube/blob/develop/apps/peertube-runner/src/shared/http.ts)
like this

```JS
import { createWriteStream } from 'fs'
import { remove } from 'fs-extra/esm'
// Change import accordingly
import { RequestOptions } from 'https'
import { http, https } from 'follow-redirects'
import { logger } from './logger.js'

// File code

// This function should now return request object from follow-redirect library
function getRequest (url: string) {
  if (url.startsWith('https://')) return https.request

  return http.request
}
```

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/6126
