### ISSUE TITLE
Resume of playing issues

### ISSUE THREAD

**Issue by DavidLibeau** [Chocobozzz/PeerTube#613]
* **PeerTube version or URL:** Beta.7
* **Browser name/version:** Firefox 60

* **What is the expected behaviour?**

Do not play the video when the player is paused.

* **What do you see instead?**

When the video is paused, the player plays the video by itself in some situations, as : when the video is 100% downloaded by the player.

**Comment by Chocobozzz** [comment]
Could you detail the steps to reproduce?

**Comment by DavidLibeau** [comment]
Yep,
- Go to a video page (I am in autoplaying config).
- Pause the video quickly.
- Wait until the video in fully loaded (need to be a small video).
The video should play by itself.

**Comment by Chocobozzz** [comment]
Reproduced, thanks @DavidLibeau 

On my side this bugs appears when the video resolution changes.

**Comment by Chocobozzz** [comment]
Should be fixed: https://github.com/Chocobozzz/PeerTube/commit/3baf9be283d75cddc8aab918e6d6557371fbd9e9
