### ISSUE TITLE
Allow file format modification after encoding

### ISSUE THREAD

**Issue by aflamrip** [Chocobozzz/PeerTube#6132]
### Describe the problem to be solved

The Peertube instance encodes files in m3u8 and mp4 format, but the Internet Download Manger (idm) program pulls the file links, and anyone can pull the links and add them to other sites, which causes excessive bandwidth consumption.

### Describe the solution you would like

This may be a suitable solution in my opinion
An option has been added to the instance control panel in the VOD Transcoding section that allows changing the default format for files. The instance administrator writes the appropriate format for it. After the instance encodes the files, the file format is changed. It is possible to specify the file type as application/octet-stream or video/ webm or image/webp. Video files are supposed to work normally. This method will also contribute to protecting the content. The instance administrator may need to prevent the download feature, but IDM will withdraw the links. This method will prevent IDM from withdrawing the file links.

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but we can't protect public content. If you want to prevent external programs to download your videos, you must use the `private`, `internal`, or `password protected` video privacies.
