### ISSUE TITLE
Stats page - Dark Theme errors

### ISSUE THREAD

**Issue by kodxana** [Chocobozzz/PeerTube#6133]
### Describe the current behavior

When browsing any video stats page on any dark mode theme numbers are hardly readable as they also being dark where most of UI have white font.
![image](https://github.com/Chocobozzz/PeerTube/assets/16674412/85c535f6-3b89-46c5-8bc4-48ebddd9d652)

Issue happens on all dark themes.

### Steps to reproduce

1. Switch theme to any of dark mode.
2. Got to any /stats/videos/ page
3. Try read numbers

### Describe the expected behavior

The stats numbers should change based on dark/light mode

### Additional information

* PeerTube instance:
  * URL: peer.madiator.cloud
  * Version: 5.02
  * NodeJS version: Latest docker
  * Ffmpeg version: Latest docker

* Browser name, version and platforms on which you could reproduce the bug: Firefox Windows 11
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/b25a6d05604e7ca3db986701874d57d0897960db
