### ISSUE TITLE
Copy paste shared link to twitter shows the post nicely but....

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#6138]
### Describe the current behavior

Since a month now (maybe since the 6.0.2 update) Copy paste shared link to twitter shows embedded video nicely but when I click to the twitter post rather than the video is playing embedded (like before) it open a new browser window to go directly to my PT platform. Why?

### Steps to reproduce

1. post a link to twitter
2. click on the post

### Describe the expected behavior

should show the embedded video player playing through twitter.
BTW is it possible to automatically the embedded video with muted sound if the previous issue is solved?

**Comment by Chocobozzz** [comment]
Can you paste an example of such twitter post?

**Comment by ROBERT-MCDOWELL** [comment]
sure here is one example
https://twitter.com/ICN_PRESS/status/1739436691776032966?s=20

**Comment by Chocobozzz** [comment]
I think it's another change or a bug on twitter side as the doc example doesn't work either: https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards

**Comment by ROBERT-MCDOWELL** [comment]
thanks for the link! it seems they changed their metatags condition to play the video/audio directly. put a simple link
is like a static summary card. I'm looking into it to see their new policy and metatags

**Comment by ROBERT-MCDOWELL** [comment]
@Chocobozzz 
I don't really now what changes have been made on X twitter side, but we lost the ability to play the video in an embedded way :-\

**Comment by Chocobozzz** [comment]
I'm sorry but we can't do anything here :/ (as a side note mastodon still support peertube embeds when sharing a peertube link :) )
