### ISSUE TITLE
LDAP plugin install fails

### ISSUE THREAD

**Issue by lapineige** [Chocobozzz/PeerTube#6139]
### Describe the current behavior

During normal installation in Yunohost, the LDAP plugin fails to install: https://github.com/YunoHost-Apps/peertube_ynh/pull/397#issuecomment-1869497725

### Steps to reproduce

1. Install Yunohost package

### Describe the expected behavior

Plugin install normally

### Additional information

* PeerTube instance:
  * URL:
  * Version: 5.x and 6.x
  * NodeJS version: 16, 18 and 20 (tried all of them)
  * Ffmpeg version:

* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): https://github.com/YunoHost-Apps/peertube_ynh/pull/397#issuecomment-1869497725

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but I don't think it's a PeerTube bug. Maybe the db is not initialized yet when the plugin is installed, or the installation command is missing the appropriate env variables (`NODE_CONFIG_DIR`/`NODE_ENV`)

**Comment by lapineige** [comment]
Ok, we had a few reason to believe it was the case (seems to had happened in the past), but nothing very sure.
Thanks for the hint, we will investigate this :slightly_smiling_face:

**Comment by lapineige** [comment]
After some discussion with people more savy than me on that topic, it seems that indeed we are not launching it in a correct way here https://github.com/Yunohost-Apps/peertube_ynh/blob/master/scripts/install#L201, it might be still initializing it… In my case it was on slow hardware (HDD + Raspberry Pi 3), so might be it !

Thanks a lot for you help :)

**Comment by lapineige** [comment]
It was indeed a database initialization issue !
Solved here : https://github.com/YunoHost-Apps/peertube_ynh/pull/400
