### ISSUE TITLE
UI hangs when editing a video being published

### ISSUE THREAD

**Issue by fenarinarsa** [Chocobozzz/PeerTube#6143]
### Describe the current behavior

Since I upgraded to 6.0.x, editing details of a video when publishing it, especially when uploading a thumbnail, makes the UI hangs for a very long time or even forever. If I force exit the publish page the video can even ends up in an error status, without being able to reupload a new video version.

Note that my server has very few transcoding capabilities (I don't need an expensive server since I don't upload new videos often).

### Steps to reproduce

1. Upload a first video and publish it so a transcoding job is running while you publish another video
2. Upload a second video, wait for the upload to finish in the publish page
3. Upload a new thumbnail, or even just modify the video's title. (note: changing the visibility works)
4. Click on the Publish button
5. The uploading bar goes all the way to the right then stalls for a very long time or even forever

### Describe the expected behavior

The metadata modifications to a video should be almost immediate, whatever the status of upload/transcoding jobs are.

### Additional information

* PeerTube instance: 
  * URL: https://peertube.fenarinarsa.com
  * Version: 6.0.2
  * NodeJS version: 18.19.0
  * Ffmpeg version: 4.3.6-0+deb11u1

* Browser name, version and platforms on which you could reproduce the bug: Firefox 121.0 Windows
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Please enable debug server logs and paste them.

Can you also paste a screen of `top` command when the upload edit hangs?

**Comment by Chocobozzz** [comment]
Ping @fenarinarsa
