### ISSUE TITLE
Chapters Tab Doesn't Work Correctly for Videos 10+ Hours in Length

### ISSUE THREAD

**Issue by kuoushi** [Chocobozzz/PeerTube#6146]
### Describe the current behavior

The Chapters tab when uploading or updating a video does not work as expected when the chapters go over the 10 hour mark. This can be mitigated by adding the chapters into the video's description through the "HH:MM:SS Chapter Title" format, and they will work as expected in the player, however the timestamps displayed in the Chapters tab will not look correct after doing this.

### Steps to reproduce

1. Upload video over 10 hours in length.
2. Go to the Chapters tab and try to set a chapter at the 10+ hour point. <-- Not currently possible
3. Go back to the Basic Info tab and set chapters for the 10+ hour point with the "HH:MM:SS Chapter Title" format in the description.
4. Save the uploaded video.
5. Confirm chapters are correct in the player.
6. Go back to the Update video screen, confirm that chapters beyond the 10 hour point display incorrectly in the Chapters tab.

### Describe the expected behavior

Allow for chapters above 10+ hours in the Chapters tab using the HH:MM:SS format rather than forcing only the H:MM:SS format.

### Additional information

* PeerTube instance:
  * URL: https://videos.kuoushi.com
  * Version: 6.0.2
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox 120.0.1
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/3608eb4f1ec34de223843a9c3c463d4ab095dece
