### ISSUE TITLE
Local videos not loading/constantly falling back to HTTP

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#615]
* **PeerTube version or URL:**
https://dialup.express (beta.7) (running on DigitalOcean droplet, 1 vCPU w/ transcoding off, 1GB RAM, 40GbE)
* **Browser name/version:**
Firefox 60.0.1 (x64)
Chrome 66.0.3359.181 (x64)
* **NodeJS version:**
v8.11.2

* **What is the expected behaviour?**
Videos load and play and don't constantly fall back to HTTP when they do.

* **What do you see instead?**
- https://dialup.express/videos/watch/080c3d13-8cd5-4626-8035-033009ea1259 
Hasn't loaded since upload.

- https://dialup.express/videos/watch/f120a009-f782-4b60-932c-4d79f7ee2d0a
Used to load and play, now no longer loads.

- https://dialup.express/videos/watch/b4b0ceb2-842e-45cb-be42-63d63fec73ab
Loads and plays, but falls back to HTTP after a minute or two.

It might also be relevant that when playing remote videos, a connection error will usually pop up despite the videos always loading completely fine.

* **Browser console log if useful (Gist/Pastebin...):**
https://pastebin.com/DhCgcLha
https://pastebin.com/E235Vrh8

* **Server log if useful (Gist/Pastebin...):**
Nothing recent, only old and resolved error messages.

**Comment by Chocobozzz** [comment]
You need to enable transcoding so it converts your uploaded videos with the appropriate codecs/options.

**Comment by XenonFiber** [comment]
@Chocobozzz Alright, thanks! I'm guessing it doesn't work retroactively, so I'll try reuploading the videos later tonight to test.

Also, I've only got a single core right now; is needing two for transcoding (without resolution conversion) still the case?

**Comment by Chocobozzz** [comment]
ffmpeg will use 100% of you CPU, but it's running in nice priority so I think it should work even if you have only 1 CPU. But I suggest you to test :)
