### ISSUE TITLE
Weird video player in some case, with "audio-only" HLS files

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#6151]
### Describe the current behavior

Hi,

When opening [this video](https://www.yiny.org/w/pgKpvvmo9fDxYBEftibJXf) in a mobile browser (firefox mobile), the player is not visible.
Here is the result when simulating a mobile firefox:

![image](https://github.com/Chocobozzz/PeerTube/assets/38844060/0f6dea5a-308d-4f29-966d-7841f124e6af)

When opening on a desktop firefox, the player has a weird size:

![image](https://github.com/Chocobozzz/PeerTube/assets/38844060/762ca56c-6404-4828-9ae7-4edec53cb642)

The files seems to be "audio-only" (which it should not, as it is HLS...):

![image](https://github.com/Chocobozzz/PeerTube/assets/38844060/5a96f068-a4b6-4edc-869b-1beaf77b0e49)

![image](https://github.com/Chocobozzz/PeerTube/assets/38844060/84b464d8-87dd-4992-982f-c86912afb021)

I don't know how the user came up with this. I only know that, some times ago, he made some tests to send an optimized file, without video (as it is a radio show).

### Steps to reproduce

1. open https://www.yiny.org/w/pgKpvvmo9fDxYBEftibJXf on a firefox mobile

### Describe the expected behavior

Player should be visible.

### Additional information

* PeerTube instance:
  * URL: https://www.yiny.org/
  * Version: 6.0.2
  * NodeJS version: 18 LTS
  * Ffmpeg version: 4.3.6-0+deb11u1 (but can have been processed by another ffmpeg on a remote runner, version 5.1.4-0+deb12u1)

* Browser name, version and platforms on which you could reproduce the bug: firefox mobile, up to date

**Comment by gilou** [comment]
So to add a few precisions:
- this was from a live, that was streamed using a still image and a MP3 source using ffmpeg, using those relevant parameters:`  -vf "scale='min(240,iw)':min'(180,ih)':force_original_aspect_ratio=decrease,pad=240:180:-1:-1:color=black" -s 240:180 -f flv`
- there was a specific thumbnail added to it (isn't that guy lovely? ;))
- I edited in the studio to trim the beginning (and maybe the end)

**Comment by Chocobozzz** [comment]
@gilou can you provide the full ffmpeg command you run?

**Comment by JohnXLivingston** [comment]
> @gilou can you provide the full ffmpeg command you run?

He was using this for the live stream:

```bash
ffmpeg -loop 1 -i ~/HKLogo.png -i https://diffusion.lafrap.fr/jetfm.mp3 -vf "scale='min(240,iw)':min'(180,ih)':force_original_aspect_ratio=decrease,pad=240:180:-1:-1:color=black" -s 240:180 -f flv rtmp://www.yiny.org:1935/live/xxx
```

**Comment by Chocobozzz** [comment]
@JohnXLivingston Can you display your live transcoding settings?

**Comment by JohnXLivingston** [comment]
Here we go:

![image](https://github.com/Chocobozzz/PeerTube/assets/38844060/4a48cd5d-884a-41de-84bf-370b73c6e72c)

**Comment by Chocobozzz** [comment]
Thanks! Player size should be fixed by https://github.com/Chocobozzz/PeerTube/commit/5cf5465d20f21ed76c0ea027b9de07e8db9878eb

HLS audio only is supported if there is only this resolution available (hls.js doesn't support mixing video + audio streams and audio only streams).

**Comment by gilou** [comment]
Thanks, I really could have used a proper ratio hehe… but yeah, that paves the way for actual audio only streams (technically, it had video, even if it's a still image…), that is not too bad…

**Comment by JohnXLivingston** [comment]
Thanks @Chocobozzz :)
