### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by M-Stenzel** [Chocobozzz/PeerTube#6155]
### Describe the current behavior

Peertube installation works, but throws an error in nginx error log

### Steps to reproduce

1. Start peertube
2. Have no entries in the nginx error log
3. Error log shows from time to time (every other day)

`2024/01/04 06:34:43 [error] 2346237#2346237: *398800 open() "/var/www/peertube/peertube-latest/client/dist/assets/images/icons/icon-144x144.png/client/assets/images/icons/icon-144x144.png" failed (20: Not a directory), client: 127.0.0.1, server: tube.xy-space.de, request: "GET /client/assets/images/icons/icon-144x144.png/client/assets/images/icons/icon-144x144.png HTTP/2.0", host: "tube.xy-space.de", referrer: "https://web.flow.opera.com/"`

Please note that this - https://web.flow.opera.com/ - is not the server peertube runs on but the referring server.
This happens with other referring servers, too.

I do understand the error message, this does not seem to be a valid path:

/var/www/peertube/peertube-latest/client/dist/assets/images/icons/icon-144x144.png/client/assets/images/icons/icon-144x144.png

### Describe the expected behavior

Have no entries in the nginx error log

### Additional information

* PeerTube instance: tube.xy-space.de
  * URL: https://tube.xy-space.de
  * Version: 6.0.1
  * NodeJS version: 18.13.0
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Can you check your nginx config has the same line as https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube#L187?

**Comment by M-Stenzel** [comment]
Ui, that was quick, and ideed the line is exactly the same as in the github nginx.conf file
And, there is no second (defective) line in my nginx.conf file.

The error line appears about every 14 days with about 800 users of the instance. So is this plausible?

Martin.

**Comment by Chocobozzz** [comment]
Since the request is invalid (`GET /client/assets/images/icons/icon-144x144.png/client/assets/images/icons/icon-144x144.png`) I guess an external crawler is doing an invalid request on your instance. Or maybe we have an invalid manifest file? https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/manifest.webmanifest

**Comment by M-Stenzel** [comment]
Well, I checked both the source manifest.webmanifest as well as the file for all the different languages, they are all o. k.
Webcrawler -- this could explain that the error is reported only once in a while.
Maybe something not really troublesome!?

Matin.

**Comment by Chocobozzz** [comment]
> Maybe something not really troublesome!?

:+1: 

If you notice a wrong URL in peertube code that leads to such request, don't hesitate to comment. But I think we can close this issue :)
