### ISSUE TITLE
No longer getting feeds from other instances

### ISSUE THREAD

**Issue by Axeltherabbit** [Chocobozzz/PeerTube#6156]
### Describe the current behavior

I'm on version 6.0.2, I'm not receiving videos feeds from other instances

### Steps to reproduce

go to subscriptions or recently added videos and you don't have new videos

### Describe the expected behavior

get updates

### Additional information

* PeerTube instance:
  * URL: https://peertube.wiredentrypoint.xyz/videos/recently-added
  * Version: 6.0.2
  * NodeJS version: v18.17.1.
  * Ffmpeg version: 4.4.2-0ubuntu0.22.04.1

i can't see anything relevant in the logs

**Comment by Axeltherabbit** [comment]
I suspect is something similar to: https://github.com/Chocobozzz/PeerTube/issues/6113, but I don't have failed jobs recently.

I added `--dns-result-order=ipv4first ` to the systemd service

**Comment by Chocobozzz** [comment]
You can also try to enable debug logs in peertube to see if your instance manages to process inbox messages

**Comment by Axeltherabbit** [comment]
https://sprunge.us/dIW3DP full logs are here, not sure if I need to do something to enable debug logs

**Comment by Chocobozzz** [comment]
Do you still have the error after the dns change? If yes, please enable peertube debug logs: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L229

**Comment by Axeltherabbit** [comment]
yes, this is my systemd service file:

```
ExecStart=/usr/bin/node --dns-result-order=ipv4first dist/server
```

**Comment by Axeltherabbit** [comment]
debug logs: https://sprunge.us/qEjza1

**Comment by Chocobozzz** [comment]
From what I see you did not receive messages from another peertube instance. Try to refollow your subscriptions

**Comment by Axeltherabbit** [comment]
Yep, seems to work, I guess it was caused by the instance being offline for a while, does peertube softban followers instances if they fail to receive feeds?
