### ISSUE TITLE
M3u of channel, user, etc

### ISSUE THREAD

**Issue by b4zz4** [Chocobozzz/PeerTube#6160]
### Describe the problem to be solved

List of m3u ready to include in a player or smarttv

### Describe the solution you would like

This makes it possible to add PeerTube channels as IPTV

https://github.com/iptv-org/iptv

**Comment by Chocobozzz** [comment]
Hello,

Can you be more specific of what we would have to do on PeerTube side?

**Comment by Chocobozzz** [comment]
Hi,

And thanks for the explanation. Unfortunately we don't have enough resources to add this feature to PeerTube, as we consider media RSS should already be the default choice for such use case
