### ISSUE TITLE
Improve chapters visibility in player

### ISSUE THREAD

**Issue by EricGuic** [Chocobozzz/PeerTube#6163]
### Describe the problem to be solved

With Peertube 6, chapters can be added to a video.
But  there is no button to display all the available chapters, and each chapter is really difficult to see on the timeline of the player : 
![image](https://github.com/Chocobozzz/PeerTube/assets/81166671/febf7e47-e044-415f-a37a-b19563f24ba3)

### Describe the solution you would like

- Add a button to the player, listing all the available chapters.

- Add some "dot" on the timeline to better display the chapter's position.

For example the vimeo player : 
![image](https://github.com/Chocobozzz/PeerTube/assets/81166671/e0c2ad91-c968-46e7-a4dd-6c57771f3db5)

Other example : 
![image](https://github.com/Chocobozzz/PeerTube/assets/81166671/eef3400b-b36c-4e1a-8cf0-438cedc27ba4)
See it in actions : https://help.sundaysky.com/hc/en-us/articles/4408600968465-Segmenting-Your-Video-into-Chapters

**Comment by Alterak** [comment]
Indeed! Now the chapters are very hard to see-(I fully support [EricGuic](https://github.com/EricGuic)

**Comment by Chocobozzz** [comment]
> Add some "dot" on the timeline to better display the chapter's position.

Implemented in https://github.com/Chocobozzz/PeerTube/commit/226f712d93b1bbcb53dac29698354634c8b62c18

If you still need a chapter widget please create a dedicated issue :)
