### ISSUE TITLE
Thumbnail heavily cropped (v6 regression)

### ISSUE THREAD

**Issue by Sabilon2** [Chocobozzz/PeerTube#6164]
### Describe the current behavior

The observed behavior affects 1:1 videos. Though not tested, it probably affects portrait videos as well.

On a square video, with a square preview image (default or uploaded, see attached image), it first gets cropped to fit the 16:9 aspect radio of video lists (screenshot 1). This seems to be an old regression (before v6) from https://github.com/Chocobozzz/PeerTube/commit/7196a70b28e93ede11ccbfef7f1bc919c663b964.

When displayed in the player it gets cropped again to fit the square aspect ratio of the preview. As a result, only the center part of the original image is displayed (screenshot 2). This seems to be a side-effect of the v6 feature which adjusts the player aspect ratio to the video.

When the play button is pressed, the 16:9 version of the thumbnail is briefly shown before the video starts (screenshot 3).

Uploaded thumbnail
![2023-10 FargeBois - Les uns regretteront les forêts, les autres les scieries 1x1](https://github.com/Chocobozzz/PeerTube/assets/76934049/2ddc8e75-5b97-459b-a6c4-f1d383413af1)

Screenshot 1
![Capture d’écran du 2024-01-10 00-19-29](https://github.com/Chocobozzz/PeerTube/assets/76934049/5cbb273a-4ec1-47be-8700-65171b60c159)

Screenshot 2
![Capture d’écran du 2024-01-10 00-19-02](https://github.com/Chocobozzz/PeerTube/assets/76934049/59fdc04c-46f2-4b48-964d-9a96a849a199)

Screenshot 3
![Capture d’écran du 2024-01-10 00-19-57](https://github.com/Chocobozzz/PeerTube/assets/76934049/c6e288b9-a1c5-4558-9c48-e7b825f43d6d)

### Steps to reproduce

1. Upload a 1:1 video

### Describe the expected behavior

The 16:9 preview should be generated from the 1:1 image adding background stripes, like this 2021 commit would do : https://github.com/Chocobozzz/PeerTube/commit/7196a70b28e93ede11ccbfef7f1bc919c663b964. But it does not seem to work anymore.

If it did, the 16:9 preview would have these stripes, the 1:1 one would be the original image. Not sure if the image that is briefly shown before the video starts would be ok (should be the 1:1 original image).

### Additional information

* PeerTube instance:
  * URL: https://video.telemillevaches.net
  * Version: 6.0.2
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:Firefox 121 Linux
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

I'm surprised it worked before because we always used a `<` comparison: https://github.com/Chocobozzz/PeerTube/commit/7196a70b28e93ede11ccbfef7f1bc919c663b964#diff-8d7c09b8653229ccb2995fc12858e7a94dee5597976edf52a6a0620004ae3e49R80

Anyway I think it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/0cbe9a471fd144c4a41281ae9ad1ea013b390981

Can you try the patch? :)

**Comment by Sabilon2** [comment]
Alright, I must have seen it work on a near square video.

I can't try the patch, I'll wait for the 6.0.3 update. Meanwhile, I've just uploaded a 1078x1080 image and Peertube behaves as expected at generating the 16:9 thumbnail. Thanks !

**Still, the preview image that is briefly displayed before the video starts is still the generated 16:9 image, within the square framed player. Here lies the regression of v6. Not a big issue, but it would definitely look better if the original image were displayed instead.**
