### ISSUE TITLE
Problem transitionning from Webtorrent (5.2.1) to Web-Videos (6.0.2)

### ISSUE THREAD

**Issue by EricGuic** [Chocobozzz/PeerTube#6165]
### Describe the current behavior

We had a Peertube test instance (tubetest) under 5.2.1, with Object Storage.
We had videos on it, transcoded only to HLS by default in configuration. 
For some of them, we need the webtorrent version to embed the stream inside H5P.org interactive module. So we manually run webtorrent transcoding and get the specific url from the download button (so we used the url with "_tubetest..._" and not the url with "_s3..._").
H5P resulting modules were working as expected.
**After the update to 6.0.2, H5P module doesn't access the webtorrent stream anymore**.

If I try to access the url used directly in the browser, this url is "converted" from
**https://tubetest.reseau-canope.fr/download/videos/3ad05af3-1ed3-4db7-8944-ff1286ed0d68-1080.mp4**
to
**https://s3.reseau-canope.fr/peertubetest/webtorrent/a6026171-ef85-4d54-a6ca-86f06a1aed94-1080.mp4**
and I get this error : 
`
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<RequestId>tx90bef7f3efe9440c9eb91-0065a8d8cd</RequestId>
<Key>webtorrent/a6026171-ef85-4d54-a6ca-86f06a1aed94-1080.mp4</Key>
</Error>
`

**Example of a problematic video :** 
- video uploaded under 5.2.1 :
https://tubetest.reseau-canope.fr/w/8gemoaqR6oqGZ8Jy3WZEDE

- url of the Webtorrent created under 5.2.1 (I get it from the download button, and it isn't working anymore) :
https://tubetest.reseau-canope.fr/download/videos/3ad05af3-1ed3-4db7-8944-ff1286ed0d68-1080.mp4

- url of the same Webtorrent but on S3 (I get it from the webUI admin) :
https://s3.reseau-canope.fr/peertubetest/a6026171-ef85-4d54-a6ca-86f06a1aed94-1080.mp4

**Comparison with a working video (uploaded AFTER the update to 6.0.2) :**

- https://tubetest.reseau-canope.fr/w/sgJjNX5XrVgmKg3HVxo5bx
- https://tubetest.reseau-canope.fr/download/videos/d4bfd851-1475-4364-9be3-1ab2a395ffb3-1080.mp4
- https://s3.reseau-canope.fr/peertubetest/webtorrent/1211c42f-6fe1-4358-a618-50fdbac46c92-1080.mp4

We can see that the only difference is the "webtorrent" addition in the S3 url after the update.

### Steps to reproduce

1.
2.
3.

### Describe the expected behavior

Maintain the access to old webtorrent version of a video even after the upgrade to Peertube 6.0.2

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

The root cause of the issue is described in https://framacolibri.org/t/command-to-generate-storyboard-thumbnail-for-all-older-videos/20170: the object storage configuration has changed but the old files were not moved to the new object storage key. So PeerTube is not able to retrieve these old files.

Moving old files to the new prefix and updating object storage URLs in database should fix the issue.

**Comment by EricGuic** [comment]
Thank you Chocobozzz, I was (slowly) getting to the same feeling, but your confirmation helps me.
