### ISSUE TITLE
Viewing private video in hls format occurs directly through nginx

### ISSUE THREAD

**Issue by Izorkin** [Chocobozzz/PeerTube#6170]
### Describe the current behavior

Viewing private video in hls format occurs directly through nginx.

### Steps to reproduce

1. Upload video.
2. Convert video to HLS format.
3. Move video to a private section.
4. Video viewing occurs directly through nginx.

### Describe the expected behavior

The request to watch the video is sent to peertube.

### Additional information

The private video is moved to folder '/var/lib/peertube/storage/streaming-playlist/hls/private' and nginx used this block `location ~ ^/static/(webseed|web-videos|redundancy|streaming-playlists)/`.
Need to move video to folder `/var/lib/peertube/storage/streaming-playlist/private` or change nginx configuration.

**Comment by Chocobozzz** [comment]
Hello,

Thanks! Can you try to replace [this line](https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube#L202) with `  location ~ ^(/static/(webseed|web-videos|streaming-playlists/hls)/private/)|^/download {`?

**Comment by Izorkin** [comment]
Yes, I already did this at my place:
```
    location ^~ /static/streaming-playlists/hls/private/ {
      proxy_pass http://127.0.0.1:9000;
      proxy_set_header X-Forwarded-For            $proxy_add_x_forwarded_for;
...
```

**Comment by Chocobozzz** [comment]
Thanks! Fixed by https://github.com/Chocobozzz/PeerTube/commit/12ea8f0dd11e3fb5fbb8955f5b7d52f27332d619
