### ISSUE TITLE
Video upload fails if video has multiple chapters on the same timecode.

### ISSUE THREAD

**Issue by S0yKaf** [Chocobozzz/PeerTube#6175]
### Describe the current behavior

When uploading a video with baked in chapters. if 2 chapters are on the same timecode, the upload will fail at 100%. throwing the following errors.

Peertube logs:
```
error[1/16/2024, 11:47:24 AM] Error in controller.

{
  "err": "Error\n    at Query.run (/app/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n    at /app/node_modules/sequelize/lib/sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PostgresQueryInterface.insert (/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:308:21)\n    at async VideoChapterModel.save (/app/node_modules/sequelize/lib/model.js:2490:35)\n    at async VideoChapterModel.create (/app/node_modules/sequelize/lib/model.js:1362:12)\n    at async createChapters (file:///app/dist/core/lib/video-chapters.js:38:9)\n    at async replaceChapters (file:///app/dist/core/lib/video-chapters.js:10:5)\n    at async file:///app/dist/core/controllers/api/videos/upload.js:111:13\n    at async /app/node_modules/sequelize/lib/sequelize.js:507:18\n    at async addVideo (file:///app/dist/core/controllers/api/videos/upload.js:88:30)\n    at async addVideoResumable (file:///app/dist/core/controllers/api/videos/upload.js:59:22)",
  "sql": "INSERT INTO \"videoChapter\" (\"id\",\"timecode\",\"title\",\"videoId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4,$5) RETURNING \"id\",\"timecode\",\"title\",\"videoId\",\"createdAt\",\"updatedAt\";"
}
```

postgres logs:
```
peertube-postgres-1  | 2024-01-16 14:42:42.212 UTC [3001] ERROR:  duplicate key value violates unique constraint "video_chapter_video_id_timecode"
peertube-postgres-1  | 2024-01-16 14:42:42.212 UTC [3001] DETAIL:  Key ("videoId", timecode)=(40655, 0) already exists.
peertube-postgres-1  | 2024-01-16 14:42:42.212 UTC [3001] STATEMENT:  INSERT INTO "videoChapter" ("id","timecode","title","videoId","createdAt","updatedAt") VALUES (DEFAULT,$1,$2,$3,$4,$5) RETURNING "id","timecode","title","videoId","createdAt","updatedAt";
```

culprit in videoChapter table:
```
    "video_chapter_video_id_timecode" UNIQUE, btree ("videoId", timecode)

```

Responsible code:
https://github.com/Chocobozzz/PeerTube/blob/4d8018de68a977c75591abd60c55d80b29da15f4/server/core/models/video/video-chapter.ts#L9-L17

I believe this issue is happening because indexes are created based on the videoId+timecode column. 

Steps should be taken to remove or skip one of the duplicate index before upload, or the database model needs to be changed. I think a simple auto-increment id field is more than sufficient.

I leave someone more familiar with peertube to decide which fix is more appropriate.

### Steps to reproduce

1. Upload a video with 2 chapters on the same timecode
2. wait for the video to upload
3. witness the error

### Describe the expected behavior

upload should not fail.

**Comment by psaunders** [comment]
Confirmed, removing markers in DaVinci allowed the upload of a video. It was giving me a 500 response error about uniqueness that made me think a duplicate copy of the file was already processing or something.

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/eb02a5dd5dfd130c123747875fa9363a51eb0ef1
