### ISSUE TITLE
Add clear Yarn cache after upgrading several versions in documentation

### ISSUE THREAD

**Issue by frankstrater** [Chocobozzz/PeerTube#6176]
### Describe the problem

I noticed quite a buildup of Yarn cache files after a couple of years of upgrading in the peertube home directory. Not sure if it should be mentioned somewhere in maintenance documentation, but this might save you some gigs in the /var/www/peertube directory.

`sudo -u peertube yarn cache clean`

I did see this is done after yarn install in the docker version of PeerTube, which makes sense.

**Comment by Chocobozzz** [comment]
Thanks, I added a note in https://github.com/Chocobozzz/PeerTube/commit/64128512b2fda952b890e5d83fc0a0a828d8d39c :)
