### ISSUE TITLE
Firefox error message: PeerTube Incompatible browser

### ISSUE THREAD

**Issue by walterebert** [Chocobozzz/PeerTube#6177]
### Describe the current behavior

When using Firefox web pages show:

```
PeerTube
Incompatible browser

We are sorry but it seems that PeerTube is not compatible with your web browser.

Please try with the latest version of Mozilla Firefox.

If you think this is a mistake, please report it.
```

In the browser console I get the following JS error

```
Uncaught TypeError: Ht.kg.registerServerSending is not a function
    63266 https://tube.network.europa.eu/client/en-US/main.76aafe20d1879349.js:3
    a https://tube.network.europa.eu/client/en-US/runtime.f7d2903e0553cdfc.js:1
    <anonymous> https://tube.network.europa.eu/client/en-US/main.76aafe20d1879349.js:3
    f https://tube.network.europa.eu/client/en-US/runtime.f7d2903e0553cdfc.js:1
    <anonymous> https://tube.network.europa.eu/client/en-US/main.76aafe20d1879349.js:3
main.76aafe20d1879349.js:3:578229
```

### Steps to reproduce

1. Open any Peertube page with Firefox 121.0.1
2. View the page

### Describe the expected behavior

Peertube pages load normally.

### Additional information

PeerTube instances:
* https://tilvids.com/
* https://video.blender.org/
* https://tube.network.europa.eu/

Happens in Firefox 121.0.1 on Linux and MacOS

Firefox Developer Edition 122.0b6 works as expected.

**Comment by KanenasPL** [comment]
Same here.
https://kinowolnosc.pl, Peertube 5.2.1 (Yunohost).

Mullvad browser 13.0.7 (based on Mozilla Firefox 115.6.0esr) works fine.

**Comment by Chocobozzz** [comment]
Can you test on https://framatube.org/?

**Comment by walterebert** [comment]
After some more testing, I could determine that it is caused by an add-on. In my case GNU Taler Wallet: https://addons.mozilla.org/en-GB/firefox/addon/taler-wallet/

So it is not an issue with Firefox itself.

**Comment by walterebert** [comment]
The bug has been resolved https://bugs.gnunet.org/view.php?id=8136
