### ISSUE TITLE
Peertube support of Postlight / Mercury for archiving

### ISSUE THREAD

**Issue by OrcVole** [Chocobozzz/PeerTube#6178]
### Describe the problem to be solved

Mercury

Project site: https://mercury.postlight.com/
Goal: Mercury is an API and web scraper that extracts structured data from web pages. It parses the content of a web page to identify key elements like titles, authors, published dates, content bodies, and more.
Use cases: Mercury is useful for extracting clean, structured data from websites. This allows developers to easily parse web page content and store or display it in a systematic way, such as creating RSS feeds, building databases, or redisplaying content.

### Describe the solution you would like

If Peertube could be aware of this Free Software project and try and ensure that it was compatible to support archiving, that would be good.

**Comment by Chocobozzz** [comment]
Hello,

Can you describe what PeerTube must do in concrete terms? I mean we already support JSONLD in HTML pages, RSS feeds, ActivityPub endpoints, REST API so I'm not sure what have to implement/fix :)
