### ISSUE TITLE
Peertube support of readability

### ISSUE THREAD

**Issue by OrcVole** [Chocobozzz/PeerTube#6179]
### Describe the problem to be solved

https://github.com/mozilla/readability

Readability helps archiving, especially longer form content. People might start using Peertube to publish their texts in addition to the already popular video publishing.

**Comment by Chocobozzz** [comment]
Hello,

Thanks for the issue but I'm not sure of what we should do on PeerTube ends. If you notice features we can add to PeerTube to improve compatibility, don't hesitate to comment with tasks we have to implement.
