### ISSUE TITLE
Support for readability archiving on Peertube

### ISSUE THREAD

**Issue by OrcVole** [Chocobozzz/PeerTube#6180]
### Describe the problem to be solved

https://github.com/mozilla/readability

Readability helps archiving, especially longer form content. People might start using Peertube to publish their texts in addition to the already popular video publishing. 

It is useful for saving just the main article content from a web page. This can be used for purposes like creating simplified/cleaner views of articles, archiving just the relevant content, or reformatting content for different displays. It's especially useful for reading longform content.

### Describe the solution you would like

If the Peertube project is aware of readability and can try and keep compatible with it, that can help archiving.

**Comment by bnjbvr** [comment]
Peertube describes itself as an *ActivityPub-federated video streaming platform using P2P directly in your web browser*. I'm not sure how it relates to archiving text-based content, and if/why federation would make it better. Moreover, I do strongly think, with my software engineering background hat on, that having a platform that specializes on one kind of content will result in a much better platform than one that tries to address All The Things™, but then would have to scatter its contributors' time and energy doing so.

It sounds to me that you're looking for a read-me-later / reading-list software, have you considered trying out the excellent [Wallabag](https://www.wallabag.it), for instance? There are many other free and open-source alternatives too. If you feel that adding federation support to such a piece of software would make sense, I would encourage you doing so on their repositories. In the meanwhile, closing this issue.
