### ISSUE TITLE
Password reset form is case-sensitive

### ISSUE THREAD

**Issue by florianwgnr** [Chocobozzz/PeerTube#6181]
### Describe the current behavior

The password reset form is currently case-sensitive which confuses users

### Steps to reproduce

1. Register an account with e.g. Abc@test.de
2. Click on reset password and enter abc@test.de => no mail is sent
3. Click on reset password and enter Abc@test.de => mail is sent

### Describe the expected behavior

1. Register an account with e.g. Abc@test.de
2. Click on reset password and enter abc@test.de => mail is sent
3. Click on reset password and enter Abc@test.de => mail is sent

### Additional information

* PeerTube instance:
  * Version: 6.0.3

* Firefox (latest)

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed with https://github.com/Chocobozzz/PeerTube/commit/c2c2cd4121fb80b6c54e8cf0e90b9c0b3e06b016 where we introduced a warning message if the email contains uppercases.
