### ISSUE TITLE
Wrong message Incompatible browser for Chromium based Yandex Browser

### ISSUE THREAD

**Issue by svetlyak40wt** [Chocobozzz/PeerTube#6184]
### Describe the current behavior

I'm using latest version of the Chromium based Yandex Browser: 23.11.2.821 (64-bit)

But from some moment PeerTube started to show this warning:

```
Incompatible browser
We are sorry but it seems that PeerTube is not compatible with your web browser.
```

### Steps to reproduce

For example, on this page I see this message: https://diode.zone/w/kxaAqysHScSWco266ymgUF

### Describe the expected behavior

I think the browser is modern enough to work with peertube.

### Additional information

* PeerTube instance:
  * URL: https://diode.zone
  * Version: ???
  * NodeJS version: ???
  * Ffmpeg version: ???

* Browser name, version and platforms on which you could reproduce the bug: Yandex Browser 23.11.2.821 (64-bit), OSX

**Comment by Chocobozzz** [comment]
Hi,

I can't reproduce with yandex browser 23.11.1.714

Can you try this version? Can you also paste web browser logs?

**Comment by svetlyak40wt** [comment]
This is strange. Today I can't reproduce it either.
