### ISSUE TITLE
Option to set default seek position for thumbnail generation

### ISSUE THREAD

**Issue by kntndrsn** [Chocobozzz/PeerTube#6185]
### Describe the problem to be solved

The as-is thumbnail generation code seeks to the center of the video to generate the thumbnail. In my case, the videos we publish contain overlays at the start with useful information. This means we need to go and change our thumbnail for each video if we want the preview information visible. If we had an option to override the default seek position, that would save this manual step.

### Describe the solution you would like

* Add a setting to the configuration allowing the default seek position to be set.
For example: `thumbnails -> generation_from_video -> seek_position: 5 seconds`
* Pass this value into `generateThumbnailFromVideo` from `generateImageFromVideoFile` so this would take affect for any new videos added.

* Add the thumbnail generation config settings to the admin page.

**Comment by kntndrsn** [comment]
@Chocobozzz If it's alright with you I'll work on this one.

**Comment by Chocobozzz** [comment]
Hi @kntndrsn and thanks for the issue.

Is the issue not too specific for your use case? I mean I doubt most admins have the same type of videos uploaded on their instance like you have.

I know it requires more work, but I think we should instead implement https://github.com/Chocobozzz/PeerTube/issues/1322 and give the ability to admins to:
 * Customize the number of thumbnails to choose from
 * Customize the timecode of these thumbnails
 * Customize the default thumbnail

**Comment by kntndrsn** [comment]
@Chocobozzz Thanks for the response. I see your point. Even for us, #1322 features would get us to a better place. I'll jump over there and see what I can contribute.

**Comment by kntndrsn** [comment]
Duplicate of #1322
