### ISSUE TITLE
Download a video using a Magnet

### ISSUE THREAD

**Issue by geco** [Chocobozzz/PeerTube#6186]
### Describe the problem to be solved

Downloading a video using a Magnet (magnetUri) doesn't work

### Describe the solution you would like

Into the video rest api, a magnetUri field is present: https://github.com/Chocobozzz/PeerTube/blob/88006beeb379d55b4448da73b4063863295b36dc/server/core/models/video/formatter/video-api-format.ts#L217

If I try to download the video using the magnet, it doesn't start, I suppose cause it cannot download the torrent file from a peer.
Instead if I download using torrent file, peertube let the file download.

Is it possibile to make the magnetUri work?

**Comment by Chocobozzz** [comment]
Hi,

What torrent client do you use? It must support the `xs` parameter inside the magnet URI (https://wiki.theory.org/BitTorrent_Magnet-URI_Webseeding)

**Comment by geco** [comment]
Hi, i'm using transmission 3.00 in Debian 11.1

**Comment by Chocobozzz** [comment]
Hi,

Then please see https://github.com/transmission/transmission/issues/317
