### ISSUE TITLE
Black video screen when Internal/Private video is played without login

### ISSUE THREAD

**Issue by durgaraj-Tai** [Chocobozzz/PeerTube#6191]
### Describe the current behavior

Whenever I tried to access videos with private or internal through link a black screen appears before showing 401 error message page. 

https://github.com/Chocobozzz/PeerTube/assets/117817896/59abdcdf-9c44-4acb-aedd-9624c6279e2f

### Steps to reproduce

1. Copy link of any private/internal video. 
2. Log out if you are logged in.
3. Try to access the video.

### Additional information

* PeerTube instance:
  * URL: Private
  * Version: 6.0.0

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/5f3009d8e980ae25ca7dc9be01487d1d473e43d7
