### ISSUE TITLE
[UI] No pagination for "Waiting" jobs

### ISSUE THREAD

**Issue by Tangeek42** [Chocobozzz/PeerTube#6196]
### Describe the current behavior

The "Waiting" jobs list doesn't show any page further than 1, even though I have way more than 10 jobs pending in that list.
The other jobs (Completed, Active, Failed, and so on) do show correctly pages as needed. Only Waiting are stuck.
I can confirm there are more jobs by changing the max items per page.

Not a really problematic issue, but it did throw me for a loop when I was searching for jobs I didn't know were there. xD 

Peertube version 6.0.2. I don't see anything regarding this in the recent changelog, sorry if I've missed it. I can't upgrade right now since it's running. :D 

![Screenshot 2024-01-27 at 19-57-12 Travaux - {-V6 $3  l%8qyE ^0% @2f2M32rk](https://github.com/Chocobozzz/PeerTube/assets/11335279/67236d8a-9fe9-47b1-acec-13d967702c29)
![Screenshot 2024-01-27 at 19-57-40 Travaux - {-V6 $3  l%8qyE ^0% @2f2M32rk](https://github.com/Chocobozzz/PeerTube/assets/11335279/9705ca06-c01c-4d54-a648-fc63852ac6bc)

### Steps to reproduce

1. Generate a lot of jobs that won't be processed quickly enough (uploading seven videos at once seemed to do the trick ^^ )
2. Go to the Waiting jobs page

### Additional information

* PeerTube instance:
  * Version: 6.0.3
  * NodeJS version: v18.19.0
  * Ffmpeg version: 5.1.4-0+deb12u1

* Browser name, version and platforms on which you could reproduce the bug: Firefox 122.0, Windows 11

**Comment by Chocobozzz** [comment]
Thanks for the issue! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/4300cc1ee107fa5be1c69b9a4743fbdcc777de78
