### ISSUE TITLE
Cannot remote follow specific remote peertube channel

### ISSUE THREAD

**Issue by aeharding** [Chocobozzz/PeerTube#6197]
### Describe the current behavior

When I try to remote follow [paige@video.canadiancivil.com](https://video.canadiancivil.com/c/main_channel/videos) from https://urbanists.video, I get the following issue:

<img width="707" alt="image" src="https://github.com/Chocobozzz/PeerTube/assets/2166114/6a320206-c1c5-4a67-8ad4-a685a1a14180">

Looking at my logs on urbanists.video, I see the following:

`Actor from DB with URL https://video.canadiancivil.com/video-channels/paige does not correspond to actor https://video.canadiancivil.com/accounts/paige`

### Steps to reproduce

1. Log in to urbanists.video
2. Click the following link and see error: https://urbanists.video/remote-interaction?uri=https:%2F%2Fvideo.canadiancivil.com%2Fvideo-channels%2Fmain_channel

### Describe the expected behavior

Should show remote channel

### Additional information

* PeerTube instance: https://urbanists.video
  * URL: https://urbanists.video
  * Version: v6.0.1
  * NodeJS version: v20.10.0
  * Ffmpeg version: v4.3.6

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

```
Jan 27 22:37:12 urbanists peertube[2511601]: [urbanists.video:443] 2024-01-27 22:37:12.622 info: 24.183.0.0 - - [27/Jan/2024:22:37:12 +0000] "GET /api/v1/users/me/notifications?start=0&count=0&unread=true HTTP/1.0" 304 - "https://urbanists.video/remote-interaction?uri=https:%2F%2Fvideo.canadiancivil.com%2Fvideo-channels%2Fmain_channel" "Firefox"
Jan 27 22:37:12 urbanists peertube[2511601]: [urbanists.video:443] 2024-01-27 22:37:12.709 info: Fetching remote video https://video.canadiancivil.com/video-channels/main_channel.
Jan 27 22:37:12 urbanists peertube[2511601]: [urbanists.video:443] 2024-01-27 22:37:12.733 info: Fetching remote actor https://video.canadiancivil.com/video-channels/main_channel.
Jan 27 22:37:12 urbanists peertube[2511601]: [urbanists.video:443] 2024-01-27 22:37:12.754 info: Cannot search remote video https://video.canadiancivil.com/video-channels/main_channel. {
Jan 27 22:37:12 urbanists peertube[2511601]:   "err": {
Jan 27 22:37:12 urbanists peertube[2511601]:     "stack": "Error: Cannot fetch remote video with url: https://video.canadiancivil.com/video-channels/main_channel\n    at getOrCreateAPVideo (file:///var/www/peertube/versions/peertube-v6.0.1/dist/core/lib/activitypub/videos/get.js:22:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async searchVideoURI (file:///var/www/peertube/versions/peertube-v6.0.1/dist/core/controllers/api/search/search-videos.js:82:28)",
Jan 27 22:37:12 urbanists peertube[2511601]:     "message": "Cannot fetch remote video with url: https://video.canadiancivil.com/video-channels/main_channel"
Jan 27 22:37:12 urbanists peertube[2511601]:   }
Jan 27 22:37:12 urbanists peertube[2511601]: }
Jan 27 22:37:12 urbanists peertube[2511601]: [urbanists.video:443] 2024-01-27 22:37:12.755 info: 24.183.0.0 - - [27/Jan/2024:22:37:12 +0000] "GET /api/v1/search/videos?search=https://video.canadiancivil.com/video-channels/main_channel HTTP/1.0" 304 - "https://urbanists.video/remote-interaction?uri=https:%2F%2Fvideo.canadiancivil.com%2Fvideo-channels%2Fmain_channel" "Firefox"
Jan 27 22:37:12 urbanists peertube[2511601]: [urbanists.video:443] 2024-01-27 22:37:12.790 info: Fetching remote actor https://video.canadiancivil.com/accounts/paige.
Jan 27 22:37:12 urbanists peertube[2511601]: [urbanists.video:443] 2024-01-27 22:37:12.856 info: Removing actor image file 4606ab63-9c54-49cd-8de9-f0801638de8c.png.
Jan 27 22:37:12 urbanists peertube[2511601]: [urbanists.video:443] 2024-01-27 22:37:12.864 info: Removing actor image file ceffe906-9129-4896-97a2-d2ebbbed174b.png.
Jan 27 22:37:12 urbanists peertube[2511601]: [urbanists.video:443] 2024-01-27 22:37:12.871 warn: Cannot execute bound create with many retries. {
Jan 27 22:37:12 urbanists peertube[2511601]:   "err": {
Jan 27 22:37:12 urbanists peertube[2511601]:     "stack": "Error: Actor from DB with URL https://video.canadiancivil.com/video-channels/paige does not correspond to actor https://video.canadiancivil.com/accounts/paige\n    at APActorCreator.tryToFixActorUrlIfNeeded (file:///var/www/peertube/versions/peertube-v6.0.1/dist/core/lib/activitypub/actors/shared/creator.js:79:23)\n    at file:///var/www/peertube/versions/peertube-v6.0.1/dist/core/lib/activitypub/actors/shared/creator.js:24:24\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /var/www/peertube/versions/peertube-v6.0.1/node_modules/sequelize/lib/sequelize.js:507:18",
Jan 27 22:37:12 urbanists peertube[2511601]:     "message": "Actor from DB with URL https://video.canadiancivil.com/video-channels/paige does not correspond to actor https://video.canadiancivil.com/accounts/paige"
Jan 27 22:37:12 urbanists peertube[2511601]:   }
Jan 27 22:37:12 urbanists peertube[2511601]: }
Jan 27 22:37:12 urbanists peertube[2511601]: [urbanists.video:443] 2024-01-27 22:37:12.872 info: Cannot search remote video channel https://video.canadiancivil.com/video-channels/main_channel. {
Jan 27 22:37:12 urbanists peertube[2511601]:   "err": {
Jan 27 22:37:12 urbanists peertube[2511601]:     "stack": "Error: Actor from DB with URL https://video.canadiancivil.com/video-channels/paige does not correspond to actor https://video.canadiancivil.com/accounts/paige\n    at APActorCreator.tryToFixActorUrlIfNeeded (file:///var/www/peertube/versions/peertube-v6.0.1/dist/core/lib/activitypub/actors/shared/creator.js:79:23)\n    at file:///var/www/peertube/versions/peertube-v6.0.1/dist/core/lib/activitypub/actors/shared/creator.js:24:24\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /var/www/peertube/versions/peertube-v6.0.1/node_modules/sequelize/lib/sequelize.js:507:18",
Jan 27 22:37:12 urbanists peertube[2511601]:     "message": "Actor from DB with URL https://video.canadiancivil.com/video-channels/paige does not correspond to actor https://video.canadiancivil.com/accounts/paige"
Jan 27 22:37:12 urbanists peertube[2511601]:   }
Jan 27 22:37:12 urbanists peertube[2511601]: }
Jan 27 22:37:12 urbanists peertube[2511601]: [urbanists.video:443] 2024-01-27 22:37:12.875 info: 24.183.0.0 - - [27/Jan/2024:22:37:12 +0000] "GET /api/v1/search/video-channels?search=https://video.canadiancivil.com/video-channels/main_channel HTTP/1.0" 304 - "https://urbanists.video/remote-interaction?uri=https:%2F%2Fvideo.canadiancivil.com%2Fvideo-channels%2Fmain_channel" "Firefox"
```

**Comment by aeharding** [comment]
I have a hunch: Paige (Canadian Civil) has an account at urbanists.video but recently set up his own PeerTube instance.

I think what may have happened, is he set up @paige as a *channel* handle, tried to access it through urbanists.video to see how things worked, then decided he wanted @paige as an *account* handle so deleted the user/channel and started over.

However I think that confused urbanists.video and thats why @paige cannot be accessed from urbanists.video.

Anyways, just my hunch. Any help would be appreciated.

**Comment by kaleb-haugen** [comment]
> I have a hunch: Paige (Canadian Civil) has an account at urbanists.video but recently set up his own PeerTube instance.
> 
> 
> 
> I think what may have happened, is he set up @paige as a *channel* handle, tried to access it through urbanists.video to see how things worked, then decided he wanted @paige as an *account* handle so deleted the user/channel and started over.
> 
> 
> 
> However I think that confused urbanists.video and thats why @paige cannot be accessed from urbanists.video.
> 
> 
> 
> Anyways, just my hunch. Any help would be appreciated.

I believe you are correct. This post from him today confirms that:

paige@canadiancivil.com (who had a PeerTube presence as paige@urbanists.video) created his own PeerTube instance with the user admin@video.canadiancivil.com and later changed his user to be paige@video.canadiancivil.com

![image](https://github.com/Chocobozzz/PeerTube/assets/73085536/eea48749-7d4f-488d-aa27-279f809bb724)

**Comment by Chocobozzz** [comment]
Hello,

Updating actors in PeerTube is not supported because of federation issues like this. You can try to fix the problem by deleting your actor with `https://video.canadiancivil.com/video-channels/paige` URL inside your database (`actor` table). You might also need to delete the association video channel (`videoChannel` table)

**Comment by aeharding** [comment]
Hmm - I am not really comfortable editing the database. I can investigate, though. Any pointers or documentation on editing Peertube's DBs?

Is it possible there could be a CLI helper to purge problematic actors from the database in the future?

Otherwise their channel will be broken in urbanists.video forever :(

**Comment by aeharding** [comment]
Update: Well, I tried manually following from the instance follows page (https://urbanists.video/admin/follows/following-list), and I think that fixed things! 🎉  I can now visit https://urbanists.video/a/paige@video.canadiancivil.com/video-channels. Yay!

**Comment by kaleb-haugen** [comment]
This is good, I can now access https://urbanists.video/a/paige@video.canadiancivil.com/video-channels both directly and via the remote subscribe feature. 

Unfortunately searching still yields no results. I guess this is a small price to pay.
