### ISSUE TITLE
Add GIF type to allow peertube to also act as a GIF aggregator

### ISSUE THREAD

**Issue by panosda** [Chocobozzz/PeerTube#6198]
### Describe the problem to be solved

Hi all, I'm Panos from Catodon, formerly in the core team of Firefish. So, let me explain where I'm coming from - we'd love to have GIFs in the fediverse. We had discussed this last year in Firefish but didn't want to add support for Giphy or Tenor because we didn't want to link and depend on Google or Meta services. But there also doesn't seem to be any serious open source alternative. There was an attempt with https://gifbox.me/ but it seems to be offline or have technical issues most of the time. But I never abandoned the idea as I love using GIFs in other platforms. Then someone suggested this again for Catodon: https://codeberg.org/catodon/catodon/issues/147

So, seeing the wonderful job you are doing with peertube, I thought - hey, we already have a decentralized, activitypub video hosting solution - and that's what GIFs basically are. And in general I think we should not reinvent the wheel wherever possible, if there is already a fedi project that can do something, others should support their implementations for better interoperability. So let me explain how Peertube could help, if you'd be interested in covering this need too! I think it would take not too much effort, but could become something really useful for a lot of people.

### Describe the solution you would like

Basically, what I was thinking, was that GIF could be a Type that is hidden from Peertube browsing pages by default - as I'm sure you don't want your servers to be full of GIFs instead of actual original videos. I saw that you've already got Type and by searching in your repo I see that GIF type has actually been suggested in #2464, but not implemented afaik. So my suggestion would be to add it, and have it disabled in searches/Discover/Trending by default. Then if someone wanted to post a gif somewhere, they could search for the specific type and embed it in their post. Furthermore, perhaps other fedi platforms like us could add a gif search box, which would search in federated peertube servers for GIF type files only, and embed them. This way Peertube would also extend to be a decentralized Tenor/Giphy alternative! GIFs don't take much space anyway so it shouldn't be a huge load on existing servers, and maybe admins can choose to not host GIF types if they don't want to.

Thank you for your time and keep up the great work!

**Comment by DeadSuperHero** [comment]
I don't think this is a bad idea, but maybe it makes more sense to fork PeerTube or create an entirely new project specifically for serving GIFs?

I don't think most video hosts want to mix and match GIFs in their catalogues, but I agree that such a thing could be a positive resource for Fediverse apps and platforms that don't want to use Giphy or Tenor.

**Comment by Chocobozzz** [comment]
Hi,

This is a good idea but unfortunately Framasoft doesn't have enough resource to include this use case inside PeerTube :/
