### ISSUE TITLE
Encode video automatically on upload

### ISSUE THREAD

**Issue by imtube** [Chocobozzz/PeerTube#62]
Hello,
When I upload videos, I hope that the system can convert it to mp4 file format  automatically so peertube can play it. And in the control panel, I can choose some parameters, for example, encoder, resolution, etc.
Is it possible？

**Comment by Chocobozzz** [comment]
Not yet. I think we should begin to just reencode the video automatically.

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/227d02feadbc9b1fc916a12528ccc0623fb3069e

I you enable transcoding in your configuration file, PeerTube will automatically transcode videos (a few minutes after the upload) in .mp4 (h264 with faststart).
