### ISSUE TITLE
Signup Page Blank When Language is Set to Traditional Chinese

### ISSUE THREAD

**Issue by wiwikuan** [Chocobozzz/PeerTube#6200]
### Describe the current behavior

Hello,

I am encountering an issue with my PeerTube instance (version 6.0.3) where the login page at [https://wiwi.video/signup](https://wiwi.video/signup) appears completely blank under certain conditions. On my macOS 13 system, the page fails to display anything in Firefox, while it works fine in Chromium. Interestingly, Firefox on a different Linux machine does not exhibit this issue.

Several users have reported similar problems, although the affected browser and operating system combinations vary among them. On the other hand, some users are able to register without any issues, which suggests that the problem might not be browser-specific.

I have spent a considerable amount of time trying to identify the root cause but to no avail. I have also checked existing GitHub Issues for similar reports and found none.

Could anyone help me understand what might be causing this inconsistent behavior? Any insights or suggestions would be greatly appreciated.

Thank you!

System Information:
- PeerTube Version: 6.0.3
- Affected Systems: macOS 13 with Firefox, various others
- Working Systems: macOS 13 with Chromium, Linux with Firefox (and others)

Screenshot, Chromium on left, Firefox on right:
![2024-01-31_12-42](https://github.com/Chocobozzz/PeerTube/assets/4676714/da66f685-862c-4f53-a415-93f8975dcc72)

### Steps to reproduce

1. Go to https://wiwi.video/signup
2. Sometimes the page appears completely blank. (on various combinations of browsers and operating systems)

### Additional information

* PeerTube instance:
  * URL: https://wiwi.video
  * Version: 6.0.3
  * NodeJS version: 18.19.0
  * Ffmpeg version: 4.4.3

* Browser name, version and platforms on which you could reproduce the bug:
  * Uncertain.

**Comment by wiwikuan** [comment]
I think I've found the answer just after I posted this issue. When I switch the language back to Traditional Chinese, the registration page turns blank. But how can I solve this?

**Comment by wickloww** [comment]
I was able to reproduce this issue on Chrome and Firefox on https://tilvids.com/signup by selecting traditional Chinese, 繁體中文（台灣）, as the language.

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the bug report

I removed [the broken translation](https://weblate.framasoft.org/translate/peertube/angular/zh_Hant/?checksum=a0a54aa9e5a3fe72) on weblate and updated peertube files in https://github.com/Chocobozzz/PeerTube/commit/0eff76f80069b63f41342b8e64aaa89d2aaf1c99 to fix the issue
