### ISSUE TITLE
Podcast RSS Feed does not include email address

### ISSUE THREAD

**Issue by DeadSuperHero** [Chocobozzz/PeerTube#6201]
### Describe the current behavior

We're using PeerTube to host the video content for our podcast. We want to use the resulting RSS feed to syndicate to a YouTube Podcast channel.

However, when we try to provide the feed URL to YouTube, we get an error message: `This RSS Feed is Invalid: Missing Owner Email`

The thing is, we have checked an option in the associated user account that says `Allow email to be publicly displayed (Necessary to claim podcast RSS feeds.)`

The email field never shows up in any of the feeds.

See our feed here: https://spectra.video/feeds/podcast/videos.xml?videoChannelId=4683

### Steps to reproduce

1. Create a PeerTube Channel
2. Upload some videos to it
3. In user account options, check `Allow Email to be publicly displayed`
4. Save
5. Look at the RSS feeds for that channel

### Describe the expected behavior

The RSS feeds should include the email field.

### Additional information

* PeerTube instance:
  * URL: https://spectra.video
  * Version: 6.0.3
  * NodeJS version: 18.9.0
  * Ffmpeg version: 4.3.1-4ubuntu1

**Comment by Chocobozzz** [comment]
Hi,

Is the email of the channel's owner verified?

**Comment by Chocobozzz** [comment]
Ping @DeadSuperHero

**Comment by Chocobozzz** [comment]
> Is the email of the channel's owner verified? (You can see it in the users list in the admin, just before the email cell)

Clearer message added in https://github.com/Chocobozzz/PeerTube/commit/7e573616d95d863ff706983d0c2766b340ff8054

**Comment by DeadSuperHero** [comment]
Hey @Chocobozzz, apologies for the lack of response on my part.

Looking at the admin interface for this user, I cannot see any indication of whether the user is verified or not.

![image](https://github.com/Chocobozzz/PeerTube/assets/401560/70ec892a-a7b7-4fef-b887-5f037dd619f5)
![image](https://github.com/Chocobozzz/PeerTube/assets/401560/ec175edb-508d-48f1-bf8e-8c46f3e96617)

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/b080ccc3ee8f7e9d0a609c649b9b9ac478de17f0 (will be available in `...` button in the next release)

In the meantime you can access the option by enabling `Signup requires email verification` option in admin configuration (your instance must have `smtp` configured).

**Comment by DeadSuperHero** [comment]
Hey, just checking in on this. I managed to update my user to be verified, and a value now gets added to the RSS Podcast feed: https://spectra.video/feeds/podcast/videos.xml?videoChannelId=4683

New problem: even though the value is in there, YouTube fails to see it. I think that maybe it's looking for the wrong value?

The value as my feed represents it: `<podcast:locked owner="hello@wedistribute.org">yes</podcast:locked>`

I think YouTube is expecting a more traditional value, like this: 

`<itunes:email>hello@wedistribute.org</itunes:email>`

**Comment by Chocobozzz** [comment]
Thanks for the feedback! `itunes:email` tag will be included in 6.1 with https://github.com/Chocobozzz/PeerTube/commit/c67dfb979be044edd0ef9d82e8bd1c04e0cb0910
