### ISSUE TITLE
If username ends with space is should be truncated

### ISSUE THREAD

**Issue by alexlehm** [Chocobozzz/PeerTube#6204]
### Describe the current behavior

The login page accepts a space at the end of the username which is added by paste in some cases

### Steps to reproduce

1.kogin with your name[space]
2. Login gails
3.

### Describe the expected behavior

The trailing space should be truncated

### Additional information

* PeerTube instance:
  * URL:pt.vern.cc
  * Version:5.2.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:brave, android
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks for the tip, it is implemented in https://github.com/Chocobozzz/PeerTube/commit/331e7cb3c5089567a16539d0fb990205388be72e
