### ISSUE TITLE
Quotations in HTML Attributes are not properly escaped, resulting in broken embeds

### ISSUE THREAD

**Issue by letydoesstuff** [Chocobozzz/PeerTube#6205]
### Describe the current behavior

HTML attributes used for rendering embeds break if they contain double quote characters. The commit edc6952 attempts to address this issue using backslash escapes. However, this does not work because inserting backslash characters does not actually escape the problematic double quote character from the HTML value.

The current, resultant behavior is that the truncated description gets cut short early after the first backslash character, terminating where the double quote character would be.

![improperescape](https://github.com/Chocobozzz/PeerTube/assets/48048071/a5502398-0a07-43fe-96f2-a294c12af8f4)

### Steps to reproduce

1. Publish a PeerTube video that contains quotations in the first 250 characters of the description. 250 characters is the length of the truncated description passed on to HTML attributes.
2. Post the video somewhere that generates an embed which includes the truncated description. As an example, I posted such a link on Discord.

### Describe the expected behavior

The expected behavior is for the truncated description to render with the embed in its entirety. This would require for double quote characters to be replaced with the  `&quot;` HTML entity instead of being backslash-escaped.

![properescape](https://github.com/Chocobozzz/PeerTube/assets/48048071/3066d9b5-d80f-41fe-a05e-5ac3c873755b).

### Additional information

* PeerTube instance: [Does Stuff Social's Peertube](https://peertube.doesstuff.social), although I've since patched this issue with a linked PR forthcoming
  * URL: https://peertube.doesstuff.social
  * Version: 6.0.3
  * NodeJS version: Not relevant
  * Ffmpeg version: Not relevant

* Browser name, version and platforms on which you could reproduce the bug: All Chromium and Gecko-based browsers
* Link to browser console log if relevant: Not relevant
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): Not relevant

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/pull/6206, thanks again @letydoesstuff
