### ISSUE TITLE
Public Profile Error

### ISSUE THREAD

**Issue by alacava** [Chocobozzz/PeerTube#6207]
### Describe the current behavior

When I attempt to go to my public profile, I get:
`400.That's an error.
We couldn't find any resource tied to the URL /a/(username)/video-channels you were looking for.
Possible reasons:
You may have used an outdated or broken link
The resource may have been moved or deleted
You may have typed the address or URL incorrectly`

Based on what I'm seeing in the logs, it looks like the query parameter is trying to count=200 but it's getting an error that the max is 100. 

Log output (username and URL removed)
`warn[2/5/2024, 9:46:18 AM] Incorrect request parameters
{
  "path": "/api/v1/accounts/(username)/video-channels?start=0&count=200&withStats=false",
  "err": {
    "count": {
      "type": "field",
      "value": "200",
      "msg": "Should have a number count (max: 100)",
      "path": "count",
      "location": "query"
    }
  }
}
error[2/5/2024, 9:46:18 AM] Client log: Backend returned code 400, errorMessage is: Incorrect request parameters: count
{
  "tags": [
    "client"
  ],
  "username": "(username)",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
  "url": "https://(URL)/a/(username)/video-channels"
}
error[2/5/2024, 9:46:18 AM] Client log: Error: Incorrect request parameters: count
{
  "tags": [
    "client"
  ],
  "username": "(username)",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
  "url": "https://(URL)/a/(username)/video-channels"
}`

I have tried to logging out and logging back in, clearing cookies, and a different browser. Same error. 

### Steps to reproduce

1. Go to my username in the upper left hand corner
2. Click "Public Profile"
3. Get the error message

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/26fb3ee660a86d10ba01e4473796d4ac3a5a3d18
