### ISSUE TITLE
BBB mp4 importation

### ISSUE THREAD

**Issue by klorydryk** [Chocobozzz/PeerTube#6211]
### Describe the problem to be solved

BigBlueButton recordings are available on the scalelite server through an html page, or (with right click -> copy video link) as m4v format.
For the moment, none of them can be imported in Peertube as url. Only downloading the file then uploading it onto peertube.

### Describe the solution you would like

Allow Peertube to download BBB recording via BBB scalelite url.

**Comment by Chocobozzz** [comment]
Hi,

Can you provide the URL of such page so I can test?

**Comment by klorydryk** [comment]
Hi,
You can use this  video link is : https://bbb-adm-scalelite.visio.education.fr/playback/video/7e0afc57fcc68495f786437bf56113eb6b401229-1699019115578/video-0.m4v
Thanks.

**Comment by Chocobozzz** [comment]
I can't reproduce locally: the video is correctly imported using your URL.

Can you paste the error you get from peertube server?

**Comment by klorydryk** [comment]
Hi Chocobozzz,
My PT (v5.2.1) answer:
`Cannot fetch information from import for URL https://bbb-adm-scalelite.visio.education.fr/playback/video/7e0afc57fcc68495f786437bf56113eb6b401229-1699019115578/video-0.m4v`

**Comment by Chocobozzz** [comment]
Do you use `yt-dlp`? https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L689

If yes, please try with latest peertube version

**Comment by Chocobozzz** [comment]
Ping @klorydryk

**Comment by klorydryk** [comment]
Yes, sorry, it was the yt-dlp version XD
I close it, thanks.
