### ISSUE TITLE
downloading videos: replace slashes with sensible substitute

### ISSUE THREAD

**Issue by lukaprincic** [Chocobozzz/PeerTube#6213]
### Describe the current behavior

If the title of the video contains a slash character (/) peertube will offer only the part of the title after the last slash as filename for download.

for example: a title: "**Podcast 6 (2/FEB/2024)**" will offer "**2024)-1080p-hls.mp4**" as filename to be downloaded.

### Steps to reproduce

1. choose any video already uploaded, click Update
2. change the title of the video into anything that contains slash character (/)
3. click update/save
4. click download and choose any options
5. the download dialogue will show "You have chosen to open:" with only part of the title after the last slash as filename

### Describe the expected behavior

Since slash is not a allowed character to be used in filenames such (and any other illegal charcters) should be replaced with something like space, underscore or a dash.

### Additional information

* PeerTube instance:
  * URL: vid.pretok.tv
  * Version: 6.0.2
  
* Browser name, version and platforms on which you could reproduce the bug: Firefox 122 on Linux

![image](https://github.com/Chocobozzz/PeerTube/assets/79146090/c1cdcf60-7bb7-4b45-9ac5-f9af76df2be3)
![image](https://github.com/Chocobozzz/PeerTube/assets/79146090/01fc0dd3-597e-482b-970c-c5a0750e2331)

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/a40981fc307a1e0163afad8f701a27ed22343588
