### ISSUE TITLE
Flutter mobile app

### ISSUE THREAD

**Issue by trymeouteh** [Chocobozzz/PeerTube#6214]
### Describe the problem to be solved

Found out that peertube plans on making a mobile app. Woukd like to suggest making the app using one codebase for allowing less code to be managed over time

https://joinpeertube.org/news/peertube-future-2024

### Describe the solution you would like

Would highly suggest using flutter/dart which allows creating apps for Android, iOS and even desktop.

**Comment by ElonVampire** [comment]
收到！

**Comment by Chocobozzz** [comment]
Hi,

We are indeed planning to use Flutter for the mobile application.

**Comment by wickloww** [comment]
Hi, 

Here is the repository of the flutter application : https://framagit.org/framasoft/peertube/mobile-application
