### ISSUE TITLE
Failed at the peertube@1.0.0-beta.7 start script 'node dist/server'

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#622]
I just set up a new Peertube instance according to the [production guide](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md). A few hours ago, I noticed that it suddenly shows an error 502 for all requests. I haven't changed any configuration since it last worked.

[Output of journalctl](https://gist.github.com/Nutomic/cc3fd33c86362d545640d96dac46811e)

The log mentions a file `urdna2015.node`, but everything looks normal, and I certainly didn't change anything there.
```
$ ls -la urdna2015.node
-rwxr-xr-x 1 peertube peertube 300584 May 30 15:42 urdna2015.node
```
PeerTube version or URL: https://peertube.social
NodeJS version: v8.10.0
OS: Ubuntu 18.04

**Comment by Nutomic** [comment]
Okay it looks like I just fixed the problem with the following commands:
```
cd /var/www/peertube/peertube-latest/node_modules/rdf-canonize
mv build build_backup
cd /var/www/peertube/peertube-latest
npm install rdf-canonize
```
I still don't know what caused this problem, if it is a bug in Peertube or somewhere else.

**Comment by Chocobozzz** [comment]
How did you install NodeJS from official Ubuntu repository? If yes, uninstall it and try https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

PeerTube does not support NodeJS compiled against OpenSSL 1.1 yet.

**Comment by Nutomic** [comment]
Ah that was it. I thought Nodejs from the Ubuntu repo would be fine, because it is also version 8.x (like it says in the dependencies guide). But apparently there's a difference between the Ubuntu version and the official version.

Thanks for your help, and sorry for the noise!
