### ISSUE TITLE
Peertube cannot be started after upgrading to v6.0.0

### ISSUE THREAD

**Issue by Zagur** [Chocobozzz/PeerTube#6220]
### Describe the problem

During the upgrade to version v6.0.0.0 we tried to lift our Docker container from Peertube and we got the following error:

```
Feb 11 16:28:48 [fediverse.tv](https://fediverse.tv/) peertube[30389]: [[fediverse.tv:443](https://fediverse.tv/)] 2024-02-11 15:28:48.525 error: Config error. {
Feb 11 16:28:48 [fediverse.tv](https://fediverse.tv/) peertube[30389]:   "err": {
Feb 11 16:28:48 [fediverse.tv](https://fediverse.tv/) peertube[30389]:     "stack": "Error: ENOENT: no such file or directory, open '/config/local-production.json'\n    at Object.openSync (node:fs:603:3)\n    at readFileSync (node:fs
Feb 11 16:28:48 [fediverse.tv](https://fediverse.tv/) peertube[30389]:     "message": "ENOENT: no such file or directory, open '/config/local-production.json'",
Feb 11 16:28:48 [fediverse.tv](https://fediverse.tv/) peertube[30389]:     "errno": -2,
Feb 11 16:28:48 [fediverse.tv](https://fediverse.tv/) peertube[30389]:     "syscall": "open",
Feb 11 16:28:48 [fediverse.tv](https://fediverse.tv/) peertube[30389]:     "code": "ENOENT",
Feb 11 16:28:48 [fediverse.tv](https://fediverse.tv/) peertube[30389]:     "path": "/config/local-production.json"
Feb 11 16:28:48 [fediverse.tv](https://fediverse.tv/) peertube[30389]:   }
Feb 11 16:28:48 [fediverse.tv](https://fediverse.tv/) peertube[30389]: }
```

This is very strange, because the file exists on the file system and has not been modified. What exactly is the local-production.json file for?

If I try to delete the file, it doesn't start either. I left production.yml and nginx as I had it before and it worked fine in version v5.2.1.

### Additional information

* PeerTube instance URL: https://fediverse.tv
* PeerTube version: 5.2.1
* NodeJS version: 18.x
* Ffmpeg version: 
* Redis version:
* PostgreSQL version:

**Comment by Chocobozzz** [comment]
Hi,

Can you go inside the container and display the output of `ls -l /config`?

**Comment by Zagur** [comment]
> Can you go inside the container and display the output of `ls -l /config`?

It is not possible to access the container. Once the container is up, it shows this error and restarts in a loop. So I cannot access the container.

Anyway, the container is being raised with the option:

`-v /var/www/vhosts/fediverse.tv/www/:/www --entrypoint "" -e NODE_CONFIG_DIR=/www/config/`

**Comment by Chocobozzz** [comment]
The official peertube container must be used with the official compose file: https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/docker-compose.yml

Please try to use it, or at least try to mount `/config`: https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/docker-compose.yml#L64C32-L64C39
