### ISSUE TITLE
Firefox Android password manager can't fill login/password

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#6226]
### Describe the current behavior

On Firefox Android, using the firefox password manager does not work.
Firefox shows the login, but when we click on it, login and password won't fill.

### Steps to reproduce

1. have your credentials saved on Firefox Android
2. open your Peertube instance on Firefox Android
3. go on the login form
4. click in the login field (or the password field, same issue)
5. registered logins shows up
6. click on the correct one
7. nothing happen

I have this bug for several months (with different Firefox and Peertube versions).

### Additional information

* PeerTube instance:
  * URL: tried on all my instances
  * Version: 6.0.3

* Browser name, version and platforms on which you could reproduce the bug: Firefox Android, 122.1.0
* Link to browser console log if relevant: sorry, i have no ADB to get browser logs

**Comment by Chocobozzz** [comment]
Hello,

Several persons in Framasoft tried to reproduce your bug without success.

But anyway I don't think it's a PeerTube bug as we use classic HTML elements to represent the login form.

**Comment by JohnXLivingston** [comment]
> Thanks, but I still think it's a firefox issue as we use a classic HTML element to represent the login form.
> 
> Don't hesitate to comment if you find there's something we can do on peertube side to fix this behaviour.

Ok.
Little update: it seems related to the fact i have other passwords for other subdomains.
