### ISSUE TITLE
generate-video-storyboard fails on upload while job is marked as completed

### ISSUE THREAD

**Issue by EricGuic** [Chocobozzz/PeerTube#6227]
### Describe the current behavior

Hi,
On upload through the webUI of a mp4 video (with thumbnail) from my computer, the generation of storyboard jpg fails.
Uploading a large number of videos, I can't say if this occurs for all upload with my user account (admin) or only a feww times (and even more after trying different workaround like the command to regenarate the storyboard for all videos).

At least I can say that an upload from another simple user account works as expected. I d'ont know if this user also uploaded a thumbnail or not.

In the webUI, jobs are marked as completed. See the capture below : the first job is the problematic video 1 I've uploaded. The second job is the working video 2 uploaded by the other user.
![image](https://github.com/Chocobozzz/PeerTube/assets/81166671/506e6224-68fc-46f0-a804-5d36c3fa2ba0)

For a problematic video, if I manually trigger the job through the command, Peertube successfully generates a new working storyboard.

Here is the url to the problematic video 1 uploaded under 6.0.3 :
https://tube.reseau-canope.fr/w/ghcnHLG1LTxqQDTuz58LEH
But the same problematic behavior happens with others videos uploaded before 5.0.2 to 6.0.3 update :
https://tube.reseau-canope.fr/w/ajtND3NYDGHeZgS2zNxXu6

Here is an example of the storyboard generated for the first video. There is only a few images, corresponding to the end of the video, but placed at the beginning of the timeline.
![14f227dc-cfb0-406f-af48-0d8cc1bb16e7](https://github.com/Chocobozzz/PeerTube/assets/81166671/cc673d31-80b0-4800-a1ae-85a2c829b9c6)
Same thing for the second one : 
![3caa7f88-3c7d-4be7-9f2c-c5f1ca08c039](https://github.com/Chocobozzz/PeerTube/assets/81166671/cdb3161f-4951-43f0-87b6-4b24affb4eb0)

### Steps to reproduce

No clear steps identified

### Describe the expected behavior

Have generate-video-storyboard jobs working everytime :-)

### Additional information

* PeerTube instance: tube.reseau-canope.fr
  * URL:
  * Version: 6.0.3
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

What is your ffmpeg version?
If it happens randomly with the same input file it may be a ffmpeg bug. You can try to enable debug logs on your instance to have ffmpeg output when it generates storyboards (near `Generating storyboard from video of` log)

**Comment by EricGuic** [comment]
Hello, ffmpeg version 5.1.2-3
But when we execute manually the command, it works, so we guess it's not related to ffmpeg
`cd /var/www/peertube/peertube-latest ; sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run create-generate-storyboard-job -- -v 4d53532f-d036-4a4e-bb66-bed3a8b77e9c`

**Comment by Chocobozzz** [comment]
Please enable debug logs on the server. Then when you see a video has this bug paste your debug logs around the generate storyboard task (PeerTube may give wrong args to ffmpeg, and debug logs provide the ffmpeg command run by peertube)

**Comment by EricGuic** [comment]
Hi, here is a link to download both log and mp4 files. One is creating this issue, and the other one gets his storyboard as expected. If it helps you.
https://reseau-canope.fromsmash.com/peertube-problem-storyboard

**Comment by Chocobozzz** [comment]
Thanks @EricGuic it helped me to debug the issue.

Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/888b142e2ef9a5e200e520bf14b63e8c97f39082
