### ISSUE TITLE
Add fediverse section on the configuration panel for instance representation

### ISSUE THREAD

**Issue by gutocarvalho** [Chocobozzz/PeerTube#6229]
### Describe the problem to be solved

I don't have a twitter account, but I have a Mastodon account.

Since Peertube is also a Fediverse/ActivityPub enabled service, it seems reasonable to offer a fediverse field to fill with the representing account.

### Describe the solution you would like

It's the same pattern and behavior of twitter section.

Fediverse Username

Nothing more.

Our instance is https://bolha.tube.

**Comment by gutocarvalho** [comment]
![image](https://github.com/Chocobozzz/PeerTube/assets/663841/6bc70a84-c741-43f6-bb7e-3d4223d9790f)

**Comment by vid-bin** [comment]
Yeah the twitter only thing always confused me. Mastodon support would be nice.
