### ISSUE TITLE
href link in the short video description also shortened

### ISSUE THREAD

**Issue by alarictabaries** [Chocobozzz/PeerTube#623]
Hi,

The href link in the short video description is also shortened.

#### Short description : 

![Short description](https://altab.fr/snaps/chrome_2018-06-05_09-25-29.png)
#### Long description :

![Long description](https://altab.fr/snaps/chrome_2018-06-05_09-25-58.png)

Screenshots taken from https://video.lqdn.fr/videos/watch/d375bac6-984a-4392-b030-adc230275f2e

**Comment by Chocobozzz** [comment]
Thanks, it's fixed: https://github.com/Chocobozzz/PeerTube/commit/cc69c8db39f48b1053c246458541ccc406228711
