### ISSUE TITLE
Redundancy not using correct URL

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#6230]
### Describe the current behavior

When using redundancy if I click on a URL in the redundancy tab it tries to open https://myurl.com:401/etc which is not accessible.

In this case 401 is the internal web server port. My nginx cache mirror is at https://myurl.com/etc which then directs to the internal web server over a network tunnel.

I am unsure if this actually blocks redundancy functions or if it's just a bug when clicking on the URL.

### Additional information

* PeerTube instance:
  * URL:
  * Version: 6.0.3
  * NodeJS version: 20.11.0
  * Ffmpeg version: GitHub

* Browser name, version and platforms on which you could reproduce the bug: Firefox MacOS

**Comment by vid-bin** [comment]
Well, I tried to use a wireguard instance. Let peertube listen on the wireguard IP, then tried to use the standard nginx config on the remote server. This worked, but videos didn't play.

What's the best config currently for a nginx proxy mirror -> nginx main (local) -> peertube (local) ?

**Comment by Chocobozzz** [comment]
Hello,

PeerTube generates URLs using your `webserver` config: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L6

So the `webserver` section in your config should represent the public URL of your nginx proxy mirror

**Comment by vid-bin** [comment]
> Hello,
> 
> PeerTube generates URLs using your `webserver` config: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L6
> 
> So the `webserver` section in your config should represent the public URL of your nginx proxy mirror

Right so that's what I'm saying. When clicking on a URL in the redundancy page it redirects to url:port when it should just be url.

The printed URL is correct but the hyperlink goes to url:port.

**Comment by Chocobozzz** [comment]
> The printed URL is correct but the hyperlink goes to url:port

Can you create manually a redundancy on a new video to check if it's not an issue only with old redundancies?

**Comment by vid-bin** [comment]
I just followed diode.zone and manually created a mirror of a video. The URL is correct (including hyperlink) but when opening the URL it redirects to vidbin.org:301, the internal nginx server port.

Try going to https://vidbin.org/static/redundancy/hls/45f9cf25-f3a1-4b35-be76-1b1662225bb6

![Screenshot 2024-02-19 at 8 27 26 AM](https://github.com/Chocobozzz/PeerTube/assets/112714131/0fab51ba-5252-4508-8bf7-165122d01a36)

**Comment by vid-bin** [comment]
Also the videos my instance hosts play fine, so I'm not sure if this is a bug in peertube or something to do with my nginx configuration.

**Comment by Chocobozzz** [comment]
> Try going to https://vidbin.org/static/redundancy/hls/45f9cf25-f3a1-4b35-be76-1b1662225bb6

PeerTube doesn't have redirects on this route, so I think it's a nginx issue?

**Comment by vid-bin** [comment]
I'm using the standard nginx config that comes with peertube on the main server. This is the current cache mirror configuration:

https://gist.github.com/vid-bin/c7b860e67b56cc6c8b40a46a51f66ebe#file-gistfile1-txt

I don't see anything that would specifically make redundancy videos redirect to port 301. All other pages on peertube appear to work fine.

**Comment by vid-bin** [comment]
I changed the config to not use the port and just use standard 443 which did solve that issue, but now I'm getting 404 not found errors when trying to browse the redundancy video directly. Unsure if that's normal behavior for redundancy videos or if it's a bug, because I've never used redundancy with peertube before.

https://vidbin.org/redundancy/hls/6a88a567-f3d2-4dfa-962b-7983fd1f1446
