### ISSUE TITLE
Add redundancy info on video player

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#6237]
### Describe the problem to be solved

The video player doesn't show how many redundancy instances the client connects to.

### Describe the solution you would like

Redundancy instances should be listed for debugging purposes.

**Comment by SimplyCorbett** [comment]
For anyone curious I had to delete all of the manually added redundancy videos on the remote instances. Then go into the host instance and wipe every entry in the videoRedundancy table on postgresql. Then I had to manually re-add the mirror videos on the redundancy instances. Then the redundancy instances were able to connect to the user and show up as peers on the player.

@Chocobozzz This seems like a blocker to me. I don't know what caused it but peertube should be able to gracefully recover from this without a database entry causing the entire federation to collapse. Well, the P2P portion anyway.
