### ISSUE TITLE
Video stuck in transcoding failed state

### ISSUE THREAD

**Issue by fenarinarsa** [Chocobozzz/PeerTube#6241]
### Describe the current behavior

When a resolution fails to trancode:
- The video is stuck in "transcode failed state" even if the failed resolution is not needed in the end
- There's no way to remove the transcode fail state
- Deleting the webvideo source don't fix the transcode fail state
- User can't reupload a new version of the video

### Steps to reproduce

1. Upload a 1440p video witch transcode activated in 480p, 1080p + source 1440p
2. somehow make ffmpeg fail for 1440p
3. HLS is available for 480/1080. Remove the 1440p webvideo because 1080p is enough (why not)
4. There's no way to remove the transcode fail label. Also no way to reupload the video.

### Describe the expected behavior

- Either allow to remove the transcode fail state, to start transcoding only the missing resolution
- Allow user to reupload a new video in the transcode failed state
- 

### Additional information

* PeerTube instance:
  * URL: peertube.fenarinarsa.com
  * Version: 6.0.2
  * NodeJS version: 18.19.1
  * Ffmpeg version: 4.3.6-0+deb11u1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by fenarinarsa** [comment]
The transcoding failed because of a segfault in ffmpeg but this issue is about the transcode failed state, not the transcode process itself.

**Comment by SimplyCorbett** [comment]
The job has to complete for it to go from pending to completed. If the job fails due to a segfault error it will be in a failed state.

You can force transcoding to run again by clicking "Run HLS transcoding" on the video in the admin panel. Once the job has finished it will no longer be in the failed state.
