### ISSUE TITLE
Redundancy does not list all videos and some aren't listed at all

### ISSUE THREAD

**Issue by vid-bin** [Chocobozzz/PeerTube#6248]
### Describe the current behavior

I am using federation v2 so this could be a federation v2 bug.

Currently peertube doesn't list all federated videos on the primary instance, meaning those videos don't get added to the P2P network. The videos are however hosted on the redundancy hosts.

Peertube also doesn't list some videos at all despite being on the redundancy hosts.

### Steps to reproduce

1. enable federation v2 (have not tested v1)
2. use a series of redundancy mirrors

### Describe the expected behavior

works as intended.

### Additional information

Master instance:

![Screenshot 2024-02-24 at 6 05 28 PM](https://github.com/Chocobozzz/PeerTube/assets/112714131/62bbf9e0-6d7a-4de7-a419-34bcacdc6e37)

Not shown: The missing videos.

* PeerTube instance:
  * URL: vidbin.org
  * Version: 6.0.3
  * NodeJS version: 20.11.1
  * Ffmpeg version: 6.1.1

**Comment by Chocobozzz** [comment]
I'm sorry but I don't understand the issue.

`mirror-01.vidbin.org` does list all videos from `vidbin.org`?

> enable federation v2 (have not tested v1)

`USE_VIEWERS_FEDERATION_V2` is just a new way of federating viewers, but it's a small part of the PeerTube federation that should not interfere with redundancy.

**Comment by vid-bin** [comment]
I've removed the redundancy mirrors for the time being, but yes, mirror-01 had all videos listed, as did mirror-02 and mirror-03.

The master peertube server did not show the redundancy mirrors as having all of them listed. In fact, it didn't show some videos at all as being on any of the redundancy mirrors.

I think out of the 24 videos only a handful had all 3 mirrors listed.

**Comment by Chocobozzz** [comment]
Can you enable debug logs and provide them so we can see messages sent by mirrors to the main instance? With the videos URL/UUID that are not considered as mirrored by the main instance?
