### ISSUE TITLE
Video Import: Set default privacy for video import 

### ISSUE THREAD

**Issue by spirillen** [Chocobozzz/PeerTube#6250]
### Describe the problem to be solved

When you IE import a Music Video from disgusting youtube, the description field are more spam than actual comments, and I don't want this published in any of my domains.

Default `privacy` is public on video upload/import/synchronized

### Describe the solution you would like

This request should help setting some defaults, like the default privacy on import but also to `My synchronizations`

It's fine you already can set the "privacy" state on the `Import with URL`, but you can't set the default from public.

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue but admins already have such settings: https://github.com/Chocobozzz/PeerTube/blob/develop/config/default.yaml#L129

**Comment by spirillen** [comment]
> Thanks for the issue but admins already have such settings

This was not for admins... but for the individual users to choose...

Please consider reopening in the light of the additional info

**Comment by spirillen** [comment]
> Hi,
> 
> Thanks for the issue but admins already have such settings: https://github.com/Chocobozzz/PeerTube/blob/develop/config/default.yaml#L129

Hey @Chocobozzz 

Today I've learned this do not applies to videos imported via `My Imports`, any change this could be fixed?
