### ISSUE TITLE
Video views not matching the real number of views

### ISSUE THREAD

**Issue by spirillen** [Chocobozzz/PeerTube#6251]
### Describe the current behavior

I have for a long time been wondering why the video "views" counter isn't reflecting the actual number of views, but seems more like only showing the number of IP addresses visited divided by 10 is used as the number of views (I can see this as for sure have been seeing the same videos over 100 times, but the view counts are below one + from my weblog.

### Steps to reproduce

1. publish a video
2. view it more than once
3. Number of views are (if you are lucky) `previous views ++1`

### Describe the expected behavior

I would expects the view counter grow by one for each views, this includes replays as the video obviously are views one more time.

### Additional information

Any version I've had since 5.4

**Comment by Chocobozzz** [comment]
Hi,

Can you go on yourinstance.com/admin/system/debug and check if your IP is correctly detected by PeerTube?

**Comment by spirillen** [comment]
The real IP is detected as I did put up the realip in the nginx + I'm bypassing crimeflare

Sp for the test, I've tested over tor as well and here I get a different results... which is unexpected as this have work before...

I'm getting back on this issue when the IP issue is solved.

**Comment by spirillen** [comment]
Hmm when using a VPN, the IP is the exit IP, only over tor this is different... So assuming the (proxy) setup is working

**Comment by Chocobozzz** [comment]
Can you try to reproduce with PeerTube debug logs enabled and paste them with:
 * The number of views you made (considering 1 address IP -> 1 view)
 * The number of views PeerTube displays (after a while since viewers are buffered)

You can also check interesting debug logs like `Processing local view for` to see what kind of IP PeerTube detects

**Comment by spirillen** [comment]
Just to let you know I haven't forgotten this issue, just awaiting I get time to a minor disturbance in my force to pick it up

**Comment by spirillen** [comment]
@Chocobozzz After the update to version `6.0.3` it seems the counter have start working, but that is leaving my other question or should we say request

> The number of views you made (considering 1 address IP -> 1 view)

To make one view = one view... like if I have a stable IP, then none of my view would count as a view.

**Comment by Chocobozzz** [comment]
> To make one view = one view... like if I have a stable IP, then none of my view would count as a view.

I'm sorry but I don't understand

**Comment by spirillen** [comment]
The counter per video seems to be limited to only count one view per IP address that visit a video.

`IF == TRUE; then`...

My question is to make each Play count as a view, disregard IP address.

IE:

I've uploaded a Music Video, that I mysteriously happens to like and hit either <kbd>F5</kbd> (+ <kbd>ctrl</kbd>)? or press the reply button, then I would expect the view counter to grow with one `i++`

**Comment by Chocobozzz** [comment]
Thanks for the explanations.

> The counter per video seems to be limited to only count one view per IP address that visit a video

To be more specific, it's "The counter per video seems to be limited to only count one view per IP address that visit a video **per hour**"

You can reduce the **per hour** interval by updating the `views.videos.ip_view_expiration` setting: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L382

**Comment by spirillen** [comment]
Thanks, I most admit I never looked that deep into the config file :)
