### ISSUE TITLE
Include option for "Sort By Size"

### ISSUE THREAD

**Issue by OrcVole** [Chocobozzz/PeerTube#6253]
### Describe the problem to be solved

Sometimes the admin needs to find which are the very large local videos which are consuming a disproportionate amount of space.
We should be able to sort files by filesize.

### Describe the solution you would like

Include a sorting option
<img width="1051" alt="brave_l43RgOf7AE" src="https://github.com/Chocobozzz/PeerTube/assets/68787520/df85c782-7912-4f1a-8987-5730aafef8cf">

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/4596ec2a9f1cd9fd9403cd4d9908449fa4bf1959

(but in the admin videos list page)
