### ISSUE TITLE
Validation error: "http://peertube_nginx.com/accounts/user" 

### ISSUE THREAD

**Issue by notaLonelyDay** [Chocobozzz/PeerTube#6255]
### Describe the current behavior

Trying to add user.

Error: 

```
Validation error: "http://peertube_nginx.com/accounts/user" is not a valid url., 
Validation error: "http://peertube_nginx.com/accounts/user/inbox" is not a valid inbox url., 
Validation error: "http://peertube_nginx.com/accounts/user/outbox" is not a valid outbox url., 
Validation error: "http://peertube_nginx.com/inbox" is not a valid shared inbox url., 
Validation error: "http://peertube_nginx.com/accounts/user/followers" is not a valid followers url., V
alidation error: "http://peertube_nginx.com/accounts/user/following" is not a valid following url.
```

Peertube in docker-compose, every service in own container, access using hostnames.
There is reverse proxy from main nginx instance to peertube_nginx

`PEERTUBE_WEBSERVER_HOSTNAME=peertube_nginx.com`

Problem is here:
https://github.com/Chocobozzz/PeerTube/blob/bfdf82c4903a7637b4da23f8f1b698d83f082fad/server/core/helpers/custom-validators/servers.ts#L13
it has require_tld: true

Why do you think, that valid url can't be without tld?
It also can be just ip

```
  peertube:
    # If you don't want to use the official image and build one from sources:
    # build:
    #   context: .
    #   dockerfile: ./support/docker/production/Dockerfile.bookworm
    container_name: peertube
    build: services/peertube/docker
#      # Use a static IP for this container because nginx does not handle proxy host change without reload
#      # This container could be restarted on crash or until the postgresql database is ready for connection
#      networks:
#        default:
#          ipv4_address: 172.18.0.42
    env_file:
      - ./services/peertube/.env

#    ports:
#        - "1935:1935" # Comment if you don't want to use the live feature
    #  - "9000:9000" # Uncomment if you use another webserver/proxy or test PeerTube in local, otherwise not suitable for production
    volumes:
      # Remove the following line if you want to use another webserver/proxy or test PeerTube in local
      - assets:/app/client/dist
      - ./data/peertube/storage:/data
      - ./data/peertube/config:/config
    depends_on:
      - peertube_postgres
      - peertube_redis
    networks:
      - peertube
    restart: "always"

  peertube_postgres:
    container_name: peertube_postgres
    image: postgres:13-alpine
    env_file:
      - ./services/peertube/.env
    volumes:
      - ./data/peertube/db:/var/lib/postgresql/data
    restart: "always"
    networks:
      - peertube

  # peertube
  peertube_redis:
    container_name: redis
    image: redis:6-alpine
    volumes:
      - ./data/peertube/redis:/data
    restart: "always"
    networks:
      - peertube
```

**Comment by SimplyCorbett** [comment]
I'm confused. Did you actually buy the domain peertube_nginx.com or is that a placeholder?

Follow-up, do you have your IP pointed at the DNS records? Because if you cant browse the domain on a web browser it won't work.

**Comment by notaLonelyDay** [comment]
@SimplyCorbett 

![image](https://github.com/Chocobozzz/PeerTube/assets/33029221/a2a9431f-2555-4d2f-9ad1-e3066e4abeba)


I have this container topology

Is it possible to not letting know peertube and peertube_nginx  their real global hostname (example.com), i don't care about features like federation

**Comment by SimplyCorbett** [comment]
its outside of the setup documentation. The domain has to be real or you have to fake it through your hosts file.

**Comment by Chocobozzz** [comment]
Hello,

Like @SimplyCorbett said you just need to have a classic domain name to use PeerTube in production. You can easily add it using your host file.

[PeerTube/server/core/helpers/custom-validators/servers.ts](https://github.com/Chocobozzz/PeerTube/blob/bfdf82c4903a7637b4da23f8f1b698d83f082fad/server/core/helpers/custom-validators/servers.ts#L13) purpose is for tests
