### ISSUE TITLE
Peertube runner stuck forever if server deletes job

### ISSUE THREAD

**Issue by notaLonelyDay** [Chocobozzz/PeerTube#6257]
### Describe the current behavior

I have runners, and if it comes to state "ERROR (7): Cannot send job progress" it never continue doing other jobs.
Looks like this update runs forever and never exits

https://github.com/Chocobozzz/PeerTube/blob/0fe016f0ea21c52318102f44104f18f0100c2e97/apps/peertube-runner/src/server/process/shared/common.ts#L50

Shouldn't job be cancelled after k retries? Or by timeout

peertube-runner --version
0.0.11

**Comment by notaLonelyDay** [comment]
related: https://framacolibri.org/t/unknown-runner-job-on-remote-runner/18013

**Comment by notaLonelyDay** [comment]
Looks like if runner is running and peertube server is restarted, server never updates Runner "Last Contact"

**Comment by notaLonelyDay** [comment]
I think I understood

When runner socket reconnects, it does not check available jobs

https://github.com/Chocobozzz/PeerTube/blob/0fe016f0ea21c52318102f44104f18f0100c2e97/apps/peertube-runner/src/server/server.ts#L117

**Comment by Chocobozzz** [comment]
> Looks like this update runs forever and never exits

The process should end when transcoding is finished :thinking: 

> When runner socket reconnects, it does not check available jobs

Thanks, fixed by https://github.com/Chocobozzz/PeerTube/commit/54a7183b119e6c4b4ad717835d199a558d0beab2
