### ISSUE TITLE
Terrible audio quality when transcoding 

### ISSUE THREAD

**Issue by PhieF** [Chocobozzz/PeerTube#626]
* **PeerTube version or URL:** beta 7

* **What is the expected behaviour?**
Audio shouldn't be that bad after transcoding

have a "look" here :p 
https://exode.me/videos/watch/9c884dde-808b-4ea1-b8cd-cb8ccdceb931

It looks like a very bad encoding, any ideas why ? The original video was mp4 with h264 + mp3 256 kb/sec

**Comment by rigelk** [comment]
It doesn't sound so bad on my side (Firefox 60.0.1). What browser are you using?

You could download the video and try to play it using a desktop player to see if there is a difference induced by your browser.

**Comment by PhieF** [comment]
firefox also, I've downloaded the file and the issue is still there, the audio is aac 128k which is low
you can compare to the original one which is far better : 

https://cloud.exode.me/index.php/s/owo5MscjYLezL4B

I've reuploaded directly using aac, I will see if it's better

**Comment by Chocobozzz** [comment]
The sound is good on my side too

**Comment by rigelk** [comment]
By default we don't specify the audio bitrate, so it should be using the default setting of your ffmpeg install.

We could do as YT does, with `-b:a 384k`.

**Comment by PhieF** [comment]
would be very nice, indeed !

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/4176e227cb18c40e13f30f4634d128cc3169e9d4, thanks @rigelk!
