### ISSUE TITLE
hls.js assertion errors

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#6263]
### Describe the current behavior

In sentry we see thousands of assertions errors:

* `true level.details must be defined` https://github.com/video-dev/hls.js/blob/848c5cb0e1d6d55147f9531ad9f8070216a339f2/src/controller/base-stream-controller.ts#L1444
* `true audiovideo sourceBuffer must not be updating` https://github.com/video-dev/hls.js/blob/848c5cb0e1d6d55147f9531ad9f8070216a339f2/src/controller/buffer-controller.ts#L879

### Steps to reproduce

We haven't been able to reproduce these errors.

### Describe the expected behavior

No assertion errors at all.

### Additional information

* PeerTube instance:
  * Version: 5.2.1

* Browser name, version and platforms on which you could reproduce the bug: Chrome, Edge, Safari, Firefox, etc.

**Comment by Chocobozzz** [comment]
Hi,

Do you still see these errors in latest PeerTube version?

**Comment by Chocobozzz** [comment]
Closing, but don't hesitate to comment if you still have errors with PeerTube 6.3 (that includes a major hls.js upgrade)
