### ISSUE TITLE
Add Option to Select Different Resolutions to Generate for Web Videos and HLS

### ISSUE THREAD

**Issue by Mike35538** [Chocobozzz/PeerTube#6267]
### Describe the problem to be solved

With Web Videos enabled along with HLS, PeerTube always transcodes a video into all the Web Video resolutions automatically. So if the selected resolutions are 1080p, 720p, 480p, 240p, you automatically have a Web Video version and HLS version of each of those resolutions. It seems like users always download the highest resolution file via the Direct Download link. I feel like it is such a rare instance that a user will actually direct download the lower resolution files like 480p or 240p, but these lower resolutions are important for the HLS user experience. I know the instance admin can manually delete off lower resolutions in the video list, but it would be nice to be able to set Web Video output resolutions separate from HLS Output resolutions. Furthermore, keeping the original video file is being implemented in #6157, maybe allow for an option to keep Web Videos of Original file and/or other resolutions. If a user truly wants a lower resolution Web Video copy, then they can download the high resolution video and manually encode it down. Or the instance admin could choose to keep only 1080p and 240p Web Videos, but not all the other HLS resolutions that are enabled.

### Describe the solution you would like

If Web Videos and HLS are enabled, have the option to enable different resolutions for each.
For example, you could choose to have:
Web Video output resolutions: Original File, 1080p, 240p
HLS output resolutions: 1080p, 720p, 480p, 240p

This would reduce the file storage load for unnecessary Web Video resolutions, as well as reduce unnecessary transcoding of these resolutions.
Thanks!

**Comment by Chocobozzz** [comment]
Hi,

Are your enabling web videos only for users who want to download the video? If so, I think fixing https://github.com/Chocobozzz/PeerTube/issues/4130 would also fix your issue since you wouldn't need to enable web videos anymore

**Comment by Mike35538** [comment]
Hi Chocobozzz,

Yes, I enable Web Videos so that my users can download a non-fragmented video file. So, if priority remuxing occurred when users click the download link, then that would accomplish my requirements. Maybe a limit on how many download remuxings a user could initiate at once would be good, or a global limit for the instance, depending on how much processing the remuxing consumes.

But specifically for my use, I'd prefer an option to only store the highest resolution non-fragmented video file for instant download, or choose which web video resolutions to store for the downloadable links instead of utilizing the processor for a remuxing job.
