### ISSUE TITLE
Vertical/Short/TikTok Format Video Support

### ISSUE THREAD

**Issue by joewood9364** [Chocobozzz/PeerTube#6268]
### Describe the problem to be solved

TikTok is likely to be banned/neutered in the USA and alternative is needed. TikTok is not just dancing/music, important activism and educational content is easily accessed by millions through vertical/short form video. As with the migration away from Reddit to the Fediverse-based Lemmy, TikTok users will likely need to migrate to another platform.
Ideally a FOSS, decentralised platform like PeerTube can become the new home for these users.

### Describe the solution you would like

Dedicated support for vertical video and its curation in PeerTube would allow for organisations to setup instances with a focus on vertical content, eventually allowing for alternatives to TikTok to take-off.

**Comment by Chocobozzz** [comment]
Hello,

We made big improvements to the peertube player lately, in particular to change its size depending on the video ratio. This means that when the video is in portrait mode, the player takes up almost all of the available device height on mobile.

Unfortunately we don't have enough resources right now to create a tiktok alternative (where the central part of the system is the recommendation engine).

But anyone can build it using PeerTube as video platform, just by creating a custom front-end (for example: https://codeberg.org/SVWareHouse/PeerTok) that communicates with [PeerTube REST API](https://docs.joinpeertube.org/api/rest-getting-started) and use the [PeerTube player API](https://docs.joinpeertube.org/api/embed-player).

We're also opened to requests to improve the API to support such use case :)
