### ISSUE TITLE
upload.js  Error

### ISSUE THREAD

**Issue by zzoozzo1122** [Chocobozzz/PeerTube#627]
* **PeerTube version or URL:**  PeerTube v1.0.0-beta.7 
* **Browser name/version:**   Chrome browser latest version
* **NodeJS version:**  ver8

* **What is the expected behaviour?**
* **What do you see instead?**

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

Question 1
upload.js

Upload the " upload.js"and you'll get it right.

However, if you give them the option " VideoPrivacy, " they will not be registered.

In addition, if you register an option in Public " 1 ", it will be registered. If you register a private, private, you will say, " You are registered, " but you are not registered.

--privacy <privacy number> 
--privacy 1 (success)
--privacy 2(failure )
--privacy 3(failure)
Please check.
-----------------------------------------------------------------------
Question 2
And let me ask you one last question.
If the version is updated
Have programs previously Clone the PeerTube to version
Do I need to reinstall to a different version?

[PeerTube v1.0.0-beta.7  >>PeerTube v1.0.0-beta.8]
Clone to reinstall?

**Comment by Chocobozzz** [comment]
For you privacy issue I can't reproduce, did you check your videos were uploaded on `/my-account/videos` page?

If you cloned the repository, just follow the production guide and move your `storage` directory, update your nginx reverse proxy, copy your old config directory and I think it should be fine.
