### ISSUE TITLE
Create Prune script for Object storage

### ISSUE THREAD

**Issue by lantrix** [Chocobozzz/PeerTube#6273]
### Describe the problem to be solved

Created after #6096 discussion as dedicated issue.

Like the [prune filesystem](https://docs.joinpeertube.org/maintain/tools#prune-filesystem-storage) storage script, it would be useful to have a similar one for Object Storage.

Currently videos moved to object storage (in my case B2) when deleted on the peertube instance remain on object storage.

### Describe the solution you would like

A script that can be run ad-hoc to allow clearing of left over objects in the Object Store.

**Comment by mikoducky** [comment]
i also seem to have this issue. No error in the log on Peertube, so not sure what the deal is. I'm using Backblaze B2 storage. It took a very long time to set up and while moving a video to it did not work, it worked to upload a new video and have it go straight there. Just not come back off...

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/54c140c8004fad5df136fca73268c35f07249e79
