### ISSUE TITLE
Add Finnish Sign Language to the video language menu

### ISSUE THREAD

**Issue by Stoori** [Chocobozzz/PeerTube#6275]
### Describe the problem to be solved

There is no option to select Finnish Sign Language as the video language.

### Describe the solution you would like

Finnish Sign Language (suomalainen viittomakieli, ISO 639-3: fse) should be added to the video language selector menu.

**Comment by Chocobozzz** [comment]
Added in https://github.com/Chocobozzz/PeerTube/commit/c10c3c5e796cc177624172637ccb59cd6e13541c :)
