### ISSUE TITLE
language issue

### ISSUE THREAD

**Issue by yildirimyaprak** [Chocobozzz/PeerTube#6277]
### Describe the problem to be solved

Dear chocobozzz,
First of all, we would like to state that we are pleased with your work and sharing. We use peertube in Turkey. However, we see that the application does not have Turkish language support. Our request is that Turkish be added as a new language to the language selection interface, and if available, you provide methods on how to do it. 
Regards,

**Comment by Chocobozzz** [comment]
Hi & thank you :)

We're not far to be able to enable Turkish language support in PeerTube, but there's still a bit of translation work to be done, as many string are not yet translated: https://weblate.framasoft.org/projects/peertube/-/tr/

We have a documentation dedicated to contributors that want to help to translate PeerTube: https://docs.joinpeertube.org/support/doc/translation

When you think enough strings are translated please ping me in this issue and so I can add Turkish language support.
