### ISSUE TITLE
First video in playlist not starting at "starts at" defined value when URL has no parameters

### ISSUE THREAD

**Issue by SteelAlloy** [Chocobozzz/PeerTube#6278]
### Describe the current behavior

When clicking on a playlist on a channel page, if the first element has start/stop times then they are not applied.

This is because the URLs given on the channel page are just the playlist URLs without any parameters, and that's fine when you navigate in the playlist since there the generated links contains the correct parameters.

```md
# Generated link
https://itvplus.iiens.net/w/p/q72rfyKzpqbUFLPBcTauA4
# Missing parameters
https://itvplus.iiens.net/w/p/q72rfyKzpqbUFLPBcTauA4?playlistPosition=1&start=49&resume=true
```

### Steps to reproduce

1. Add videos to a playlist
2. Change the starting time of the first video
3. Enter the playlist URL directly in the browser without query parameters OR click on it via channel page
4. Video starts/ends normally, without the defined "start/stop at"

### Describe the expected behavior

I think the expected behaviour should be that if the server receives a playlist URL without params **and** the first element has start/stop times, it should redirect to the same URL but with added parameters.

### Additional information

* PeerTube instance:
  * URL: https://itvplus.iiens.net
  * Version: 6.0.3

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/167d36df631fd0fb1ab013eaacb8bcfcdfbfa910
