### ISSUE TITLE
Copied iframe code of a password-protected video misses a "allow-forms" option (preventing password submit)

### ISSUE THREAD

**Issue by kaamui** [Chocobozzz/PeerTube#6279]
### Describe the current behavior

A copied iframe code of a password-protected video cannot be used as-is, missing a "allow-forms" option in the sandbox parameter of the iframe (submit the form won't work). Adding the option resolves the issue : 

```html
<iframe title="Earth" src="<url>" allowfullscreen="" sandbox="allow-same-origin allow-scripts allow-popups" width="560" height="315" frameborder="0"></iframe>
```

works when adding **allow-forms** to the sandbox parameter
```html
sandbox="allow-same-origin allow-scripts allow-popups allow-forms"
```

### Steps to reproduce

1. copy the iframe code (right-click on the video -> copy embed code)
2. add it to a web page
3. open the page and try to enter the password

### Describe the expected behavior

When clicking on submit or pressing enter, password should be submitted and video played if password is correct

### Additional information

* PeerTube instance: local
  * URL: localhost
  * Version: 6.0.3
  * NodeJS version: 18.19.1
  * Ffmpeg version: 5.1.4

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/78e4cc30c535c2acf0bb7b001882179500c1c589 & https://github.com/Chocobozzz/PeerTube/commit/da63a030f3230dfcce6c8ad328c74984eb2812c8
