### ISSUE TITLE
Chunked resumable processing for PeerTube remote runners

### ISSUE THREAD

**Issue by emansom** [Chocobozzz/PeerTube#6280]
### Describe the problem to be solved

When a PeerTube remote runner is operating in a spotty network (e.g. 4G cellular at a festival) the video transfer from and to PeerTube may be interrupted due to network disruptions.

### Describe the solution you would like

In these scenarios it'd help a lot of PeerTube were able to recover and deal with these unoptimal conditions by sending chunked fragments (e.g. 15s of frames+audio) instead of whole files always, and to be able to resume previous send chunks.

This'd likely require some revamping of the way ffmpeg is interacted with as well, to get it to spit out chunks instead of full processed files.

Having such functionality would greatly aid in scenarios where PeerTube is used for live event broadcasts.

### Linked/related issues

#5888

**Comment by emansom** [comment]
Similar/related to #5888

**Comment by Chocobozzz** [comment]
> Similar/related to https://github.com/Chocobozzz/PeerTube/issues/5888

Thanks! Merging this issue in #5888
