### ISSUE TITLE
Create clip from another video

### ISSUE THREAD

**Issue by kntndrsn** [Chocobozzz/PeerTube#6281]
### Describe the problem to be solved

We would like the option to create a clip from another video on the platform. For example, from a livestream recording, we would like the option to select a start and end time from an existing video, then save as a new video.

### Describe the solution you would like

Add a Save as Copy option to the Studio

**Comment by kntndrsn** [comment]
If this make sense to add as a feature to the platform, you can assign to me and I'll work on it.

**Comment by Chocobozzz** [comment]
I would think to extend the [studio feature](https://docs.joinpeertube.org/use/studio) where the user would be able to create another video instead of editing the current one

**Comment by kntndrsn** [comment]
Something like this for the action buttons?
![image](https://github.com/Chocobozzz/PeerTube/assets/6994260/0335191a-0b41-473a-9187-cccfc932ef65)

**Comment by stevespaw** [comment]
#5107 Related !

**Comment by stevespaw** [comment]
Studio Set new start and stop from the player current time #5352 Also would be handy :-) .

**Comment by kntndrsn** [comment]
@stevespaw Thanks for sharing. Looks like this is a duplicate of #5107. I didn't see that one in my search.

**Comment by kntndrsn** [comment]
Thanks for the sharing. I've created a demo and would appreciate your feedback.

There is a new button "Save as new video" and I renamed the existing in an attempt to make there function clearer.

![image](https://github.com/Chocobozzz/PeerTube/assets/6994260/a1487dd4-fb63-4330-b783-671a87008699)

If you select Save as new video, it creates a new video based on the edit. For now I've added the text " - Studio Edit" to the end. However, I'm not seeing a way to localize that so open to ideas.

![image](https://github.com/Chocobozzz/PeerTube/assets/6994260/52ac5d10-ac1b-4be1-95ef-bcb67c02b372)

**Comment by stevespaw** [comment]
The "Studio Edit" looks fine. Easy to rename after. Could you put a field in the Studio Edit to create the new name before the save, if not entered it gets this default name. I can see creating highlight videos and wanting to name it "Mike's Trumpet Solo" when you create this sub clip.

**Comment by Chocobozzz** [comment]
> https://github.com/Chocobozzz/PeerTube/issues/5107 Related !

Thanks! Merging this issue in #5107 then.

**Comment by stevespaw** [comment]
Is this feature going to make it to 6.1?  We can really use it.
