### ISSUE TITLE
Using Turkish Language in Peertube 

### ISSUE THREAD

**Issue by yildirimyaprak** [Chocobozzz/PeerTube#6289]
### Describe the problem to be solved

Dear choco,

In response to the email I sent you recently, you said, "We are not far away from enabling Turkish language support on PeerTube, but there is still some translation work to be done as many strings have not yet been translated." Ultimately, we have increased the percentage of Turkish from 36% to close to 100%. ;-) 
In conclusion;
1) When you create a language pack for Turkish, should we re-do the entire installation or install it as an add-on to the system?
2) How can we install some features as plugins? Is there a video or document about this? (We did not come across the Plugin module in peertube, which we work offline)
3) What features can't Peertube display when it works offline?

Note: **Our system works offline**

**Comment by Chocobozzz** [comment]
Hi and thank you very much for your contribution!

I added Turkish language support in https://github.com/Chocobozzz/PeerTube/commit/a246c4450402768b9dada5dab0b0189d772cfa25

It will be included in next PeerTube release (6.1), but you can already see it in action on https://peertube2.cpy.re/

> When you create a language pack for Turkish, should we re-do the entire installation or install it as an add-on to the system?

You'll just have to upgrade your peertube instance to 6.1

> How can we install some features as plugins? 

See https://docs.joinpeertube.org/admin/customize-instance & https://docs.joinpeertube.org/maintain/tools#install-or-uninstall-plugins 

> What features can't Peertube display when it works offline?

Sorry I don't really know, but I think everything will work correctly except features that fetch content from the internet (federation, plugins/themes, global search etc).
