### ISSUE TITLE
'sponsor' payment model, donations and the like

### ISSUE THREAD

**Issue by hoodiek** [Chocobozzz/PeerTube#629]
while https://github.com/Chocobozzz/PeerTube/blob/develop/FAQ.md explains peertube's stance on ads (which i personally agree with, to put it out there first), it does not mention any stance on solutions to content creation funding such as patreon, paypal.me, ko-fi, or liberapay, all of which function much, much differently.

while i do not believe paypal/patreon integration is all that plausible (patreon at least features the ability to release 'videos' in some form, as i have not experienced the feature myself, i can not speak much on it, but it's closed box factor means its unlikely we can automate much or any of the process of hosting such things.

that all said: patreon for instance has become a huge portion of how content on youtube thrives. this is not to say this is inherently a flawless methodology of financing or otherwise encouraging content, but it is definitely worth addressing in some form.

i personally do not know of any reason this method of encouraging/supporting/funding content to be of any problem. as such, i would recommend, at the very least, allowing for some buttons reminiscent of what youtube for instance (a major competitor) has recently added 
![image](https://user-images.githubusercontent.com/23704040/41081144-afcd7288-69f7-11e8-9853-dd5fe014243c.png)

this does not need to be a built-in patreon-esque subscribe model like youtube has, but it could very easily be a patreon button, paypal.me, ko-fi and the like, simply a link with a fancy visual that looks professional.

if this is not to be implemented, it should be addressed in the FAQ related to the ads question, probably directly after it.

note: this is not a video i follow, the sponsor feature is just very new to youtube and thus not broadly used / broadly rolled out, i'm not sure which is bottlenecking

**Comment by Chocobozzz** [comment]
Hi @hoodiek, 

We already have a "Sponsor" button (called "Support"): ![https://lutim.cpy.re/1zAv5N8s.png](https://lutim.cpy.re/1zAv5N8s.png)

Users can write Markdown in it so they can display a Patreon or Tipeee (or anything else) badge that points to their personal Patreon/Tipeee webpage for example.

**Comment by hoodiek** [comment]
that probably solves the issue entirely! i must have missed it entirely when looking through things due to the different name, i apologize for the unnecessary issue.

**Comment by Chocobozzz** [comment]
No worries, thanks anyway :)

**Comment by alexgleason** [comment]
Nice! I just came to open this issue and discovered this feature.

Since there are now two people who missed this feature, I think maybe there could be increased discoverability for it. :slightly_smiling_face: 

In particular, "Support" with a heart icon is not clear enough to me. "Heart" is usually a synonym for "Like" and I assumed it was a button that lets you favorite a video or give it a thumbs up. Maybe it should be a dollar sign instead?

I also think making it more prominent (using a green button, for example) could help this feature catch on. YouTube has already screwed creators over and I think this could be an incentive for people to use PeerTube instead.

**Comment by McFlat** [comment]
I like the idea of the green button with a dollar sign, +1 on that one

**Comment by Chocobozzz** [comment]
@alexgleason Could you open another issue to discuss the enhancement of this button? :)
