### ISSUE TITLE
Instance player development

### ISSUE THREAD

**Issue by aflamrip** [Chocobozzz/PeerTube#6290]
### Describe the problem to be solved

There is no problem, but I would like to take a look at this player. It may be useful to integrate it with the instance. Everything develops over time, so if it is possible to develop the player on the instance or add an additional player.

### Describe the solution you would like

A new player, I think it has most of the features that will contribute to the integration and development of the PeerTube instance
Links
https://github.com/vidstack/player
https://www.vidstack.io/

**Comment by Chocobozzz** [comment]
Hi,

What feature would we gain by changing the video player framework from video.js to vidstack?

**Comment by aflamrip** [comment]
Compatible with modern programming languages
Next.js
React

Features
[Section titled Features](https://www.vidstack.io/docs/player?styling=default-theme#features)
The following is a comprehensive list of all features you will have access to when using Vidstack Player:

First-class TypeScript support for all frameworks.
Multiple framework support via our [Web Component](https://www.vidstack.io/docs/player/getting-started/installation/web-components) and [React](https://www.vidstack.io/docs/player/getting-started/installation/react) libraries. JSX types included out of the box for [Vue](https://www.vidstack.io/docs/player/getting-started/installation/vue), [Svelte](https://www.vidstack.io/docs/player/getting-started/installation/svelte), and [Solid](https://www.vidstack.io/docs/player/getting-started/installation/solid).
Multiple styling options: CSS, [Tailwind CSS](https://www.vidstack.io/docs/player/styling/tailwind?styling=default-theme), and extending our Default Theme.
Multiple media provider support: Audio, Video, HLS, YouTube, Vimeo, and Remotion.
Single standard API across all providers.
Mature and battle-tested architecture which we integrated into Reddit at scale and used for analytics.
Production-ready layouts for when you don’t have time to build your own UI.
Streaming support via HLS and DASH (soon).
Live streaming support.
Keyboard shortcuts.
Next.js 13 and RSC ready.
SSR-friendly for all frameworks.
Completely customizable headless components.
[30+ components](https://www.vidstack.io/docs/player/components/core/player?styling=default-theme) for you to build with and configure.
[18+ React hooks](https://www.vidstack.io/docs/player/api/hooks/use-media-state?styling=default-theme) for managing state and building UI.
Simple automatic setup via our bundler plugins.
State management solutions for reading and updating media state.
Rich event system.
Comprehensive player API: autoplay, audio tracks, fullscreen, picture-in-picture, live, keyboard, text tracks, and video quality.
Resolve cross-browser differences for native APIs such as fullscreen, picture-in-picture, tracks, streaming, and rendering/styling captions.
AirPlay and Google Cast support.
Screen orientation support.
Clipping media start and end times.
Easily add async local or database storage.
Tons of styling hooks for components via data attributes.
Accessible. Following the WCAG 2.1 specification and adhering to FCC and CVAA guidelines.
Custom [media captions library](https://github.com/vidstack/media-captions) with support for VTT, SRT, and SSA. We also include a plugin to support libass via [jassub](https://github.com/ThaUnknown/jassub).
Tooltips and menus with animation support.
Support for media chapters inside sliders and menus.
Thumbnails/previews when user is interacting with time slider.
JSON suppot for text tracks and thumbnails.
Gesture-support for handling direct user interaction with media such as tapping to seek and more.
Load strategies for determining when to load media and posters (lazy by default).
Lightweight at 54kB gzip for all core features and components. The library is also treeshakeable to bring that down further.
Internationalization (i18n) support on all components and our production-ready layouts.

Compare
[Section titled Compare](https://www.vidstack.io/docs/player?styling=default-theme#compare)
You might be curious about how this library stacks up against other well-known players like JW Player or Video.js. Here’s how we’re different:

TypeScript: Enjoy robust first-class TypeScript support for type-safe development. Everything is typed including the player itself, core features, component props, state, events, and hooks. All exported from our NPM package.
Reactivity: Our library is built with Signals which enable tracking and subscribing to individual media state internally and externally. We take advantage of this to expose a variety of props to configure components, manage tricky internal state, design a complex production-ready default layout, and hooks such as useMediaState and useMediaStore in React.
Components: Our library offers a wide range of declarative components to enhance your media player’s functionality and appearance.
Custom UI: The other players are not built well for building a custom player UI. The lack of any hooks and components makes it hard to do so.
Production-ready UI: The other players offer a limited player experience out of the box that’s not easy to customize. We provide a much higher-quality UI experience that supports a variety features and stream types out of the box with props and over 150+ CSS variables to easily customize it all.
Framework Support: We support many JS frameworks, environments (Browser/SSR), and styling options, making it easier to integrate and build with our player.
Rich Events: We include more events out of the box and include triggers to track where and how they originated.
Modernized: We provide up-to-date APIs for the library, player, and all of our components. Some examples include not supporting old and outdated browsers, providing ESM bundles and TS types, and using ReadableStream to handle processing large captions.
Features: In general, you’ll find we support many more features out of the box such as: frameworks, hooks, providers, styling options, state management solutions, UI components, chapters, thumbnails, tooltips, menus, animations, caption file types, customization options, and much more.
Bundle Size: We’ve optimized our library to keep the bundle size minimal, ensuring faster loading times. To compare, Video.js base size is 656kB (195kB gzipped), whilst Vidstack Player is 173kB (53.4kB gzipped). In addition, our library can treeshake unused code to further reduce the size, and most heavier parts are lazy loaded such as providers and captions.
Licensing: JW Player requires purchasing licenses for each individual player based on the number of content plays. It’s paid for above 100K plays. Vidstack Player is MIT licensed and free to use without any limits.

You can check the website https://www.vidstack.io/
It is planned to work on the UI component library for building
This will contribute very significantly to improving the user experience and developing the Peertube instance
To see an example of a player on the site, search for Built for React.

**Comment by Chocobozzz** [comment]
Thanks, but the work to move away from video.js doesn't seem worth it
