### ISSUE TITLE
How do I disable the "req.setTimeout(1000 * 60 * 10)" in upload.ts?

### ISSUE THREAD

**Issue by adamflorizone** [Chocobozzz/PeerTube#6297]
### Describe the problem to be solved

Using:
```
peertube-cli upload
```

I get error:
```
Uploading big_buck_bunny.mp4 video...
Error: Expected status 200, got 408.
```

Hard coded value:
https://github.com/Chocobozzz/PeerTube/blob/v6.0.3/server/core/controllers/api/videos/upload.ts#L97

Version: 6.0.3

### Describe the solution you would like

Stop hard coding values. :( Also "Video upload has timed out" is not even being put into the logs. I need a config var to make large size uploads work. Also the default "1000 * 60 * 10" is kind of low. The docs are needs a "compile and run for your self". I would make a PR but I cant seem to recompile in docker.

**Comment by Chocobozzz** [comment]
> Stop hard coding values. :( Also "Video upload has timed out" is not even being put into the logs.

If it's not in your log, are you sure 408 error comes from peertube? You can enable debug logs on peertube side to also see the `res.fail` log: https://github.com/Chocobozzz/PeerTube/blob/v6.0.3/server/core/controllers/api/videos/upload.ts#L99

**Comment by adamflorizone** [comment]
No proxy it's a direct connection to peertube.localhost

**Comment by Chocobozzz** [comment]
Can you paste your peertube logs?

**Comment by adamflorizone** [comment]
```grep -r "Video upload has timed out." /data/logs/``` returns nothing

I don't understand why the client would return 408 to localhost. I can unplug eth and it still works with smaller videos. I did this all via "docker exec". It might be a CLI issue.

Logs
I said something that is not in the logs, I can't paste.

I resolved this:
By changing to a faster docker computer and the error is no longer an issue,
You can close this issue.
