### ISSUE TITLE
Peertube plugin installation in intranet network

### ISSUE THREAD

**Issue by yildirimyaprak** [Chocobozzz/PeerTube#6301]
### Describe the problem

Hi Chocobozzz,

        It's really great that you respond to our posts so quickly...
        We've come a long way in the process of building Peertube and sharing it with users. However, We're currently at the "Houston, we have a problem" point :/

        We try to run the necessary plug-in packages for Peertube by downloading them from the internet and then moving them to the Peertube local directory (var/www/peertube/storage/plugin) on the intranet network. At this stage we encountered an error. This error is caused by the license area not existing. However, when we check the package.json file, we see that the license area is available.

        We examined some websites on the subject (https://framacolibri.org/c/peertube/38 ........https://framacolibri.org/t/how-can-i-install-the-ldap- plugin -on-my-peertube-instance-running-offline/20978....https://docs.joinpeertube.org/api/plugins). We have not received any results yet, I am sharing the error image and package.json file with you.
![3_ldap eklenti hatası (gönderilecek olan)](https://github.com/Chocobozzz/PeerTube/assets/28116543/9e9f6964-7d64-45fc-a51d-2f7daa17df7e)
![4_package json dosyası](https://github.com/Chocobozzz/PeerTube/assets/28116543/9923d040-aa7b-458f-8717-cb06434556b3)

As a result;
1) Do I need internet to copy the plugin files to the local directory and run them?
2) We see that there is a License field in the package.json file. Is there a problem here? How should it be?

We are waiting for your suggestions,

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by Chocobozzz** [comment]
Already existing topic on https://framacolibri.org/t/how-can-i-install-the-ldap-plugin-on-my-peertube-instance-running-offline/20978/4
