### ISSUE TITLE
Live Stream Without Saving Video and Replays (Disposable LiveStream)

### ISSUE THREAD

**Issue by Mike35538** [Chocobozzz/PeerTube#6306]
### Describe the problem to be solved

I don't see a way to give an option to live streamers to not save a video replay. Whether you do a normal live or a permanent live, the video is always stored since a replay is always created.

Can there be an option to not store the live video and automatic replay? I see this case happening when someone wants to live stream something like an eagle's nest for 24 hours or more, or live stream a playlist of videos from OBS for 24 hours, or live streaming their video game. In these cases there is no need to store the video that has passed already and there is no need to save a replay. However, when streaming for 24 hours, a large amount of files are stored in anticipation of making a replay. Often up to 40 GB for a 24-hour stream. 

### Describe the solution you would like

I'm not sure if this is possible but maybe create something like a "Disposable" live stream, where you'd only need to save 2-3 minutes of video for the live latency, while older video can be purged.

Add a third option (disposable)
Normal liveStream only once, replay will replace your live
Permanent/recurring liveStream multiple times, replays will be separate videos
Disposable LiveStream (LiveStream only, video is not saved, and a replay is not created)

**Comment by MattyBoombalatty** [comment]
You can do this by turning off "automatically publish a replay" in the settings of the Live.

Update video > Live settings 

![image](https://github.com/Chocobozzz/PeerTube/assets/95333219/bfa5becf-63f1-4de9-be40-97476b0da556)
![image](https://github.com/Chocobozzz/PeerTube/assets/95333219/973719e3-2051-4e7f-b7a0-3605d4c20f92)

**Comment by Mike35538** [comment]
Ok, so the full video length isn't stored on the server during the live stream if that 'publish a reply' is not enabled.

**Comment by MattyBoombalatty** [comment]
Correct.

**Comment by Mike35538** [comment]
Ok, thanks for the clarification!
