### ISSUE TITLE
ffmpeg SIGSEGV on remote and local runner when using ffmpeg static build !

### ISSUE THREAD

**Issue by vincib** [Chocobozzz/PeerTube#6308]
### Describe the current behavior

I get a SIGSEGV on ffmpeg 5.1.1 or 6.1 downloaded from https://johnvansickle.com/ffmpeg/ 

only when using those ffmpeg releases, (on an updated debian 12). I tested it on multiple machine, it's clearly not the hardware ;) 

The same video and live with the stock debian release of ffmpeg works fine.

### Describe the expected behavior

This static version of ffmpeg is working great for other usages of ffmpeg (in my case, for a professionnal video streaming service for Focusgroups that I maintain, not peertube-related.) so I guess it's a compatibility issue between  Peertube and those ffmpeg static builds (local or remote runner, both are crashing) 

so ... basically peertube seems fine as long as people don't use that ffmpeg release. **Maybe you could tell people NOT to use those static builds...**

**Comment by vincib** [comment]
so ... basically peertube seems fine as long as people don't use that ffmpeg release. Maybe you could tell people NOT to use those static builds...

**Comment by Chocobozzz** [comment]
> it's a compatibility issue between Peertube and those ffmpeg static builds 

We just run a classic ffmpeg command it's weird :thinking: 

> Maybe you could tell people NOT to use those static builds...

The official guide installs ffmpeg from official repository: https://docs.joinpeertube.org/support/doc/dependencies#debian-ubuntu-and-derivatives

But I still added a note in https://github.com/Chocobozzz/PeerTube/commit/1d52f1f138d734b7319f98ec5946665b32daf37f

**Comment by jb-alvarado** [comment]
Hello, just a note: I use for years my own ffmpeg static builds in all situations, also with peertube and I had never problems. I think this issue should be more observed for a general recommendation.
