### ISSUE TITLE
Where does the storageManager read and write from?

### ISSUE THREAD

**Issue by MattyBoombalatty** [Chocobozzz/PeerTube#6309]
### Describe the desired information/correction

I'm trying to fix an issue with a PeerTube plugin, and one of the features it uses is storing data in the database via the `storageManager` helper. I've looked everywhere for the keys but I can't find them - including in `plugins` as well as `user`.

**Comment by kontrollanten** [comment]
Hi! I’m not sure I understand your question, but storageManager is storing its data in Postgres. All storage is stored as JSONB in the storage column in the plugins table.

**Comment by MattyBoombalatty** [comment]
Perhaps this plugin wasn't coded correctly or I'm missing something then. Thanks for the heads up - I'll continue investigating. I just wanted to confirm where the JSONB data was supposed to be stored.
