### ISSUE TITLE
onboarding improvements

### ISSUE THREAD

**Issue by hoodieak** [Chocobozzz/PeerTube#631]
as someone who was a user and at least slightly active github-side since before and during the rapid growth and rapid interest in mastodon, something that was a _huge issue_ was the onboarding process and  the beginning/exploring-not-yet-user experience.

as such, i think it's rather fair to point out how (as a not-yet-user / explorer of peertube) i can find many flaws with peertube's current attempts at solving this problem in federated tech such as both of these projects.

http://joinmastodon.org/ is a plenty fine way to get a basic understanding of the bare minimum you will need to onboard new users

it fits all the most required things (i think peertube's differences inherent to the medium mean it can do better, but i'll get to that)
-basic definition of federation so it can be understood easily accessible
-list of instances / basic instance-finding-tool
-quick blurb to 'sell'/inform users (could easily be made less intrusive, but i do not claim to know too much about the web-design aspect of selling a user like this. i personally (at least as a returning user of mastodon) find a slight negative response to the 'selling user on software' bit being above the instance-finder bit, but that might be due to my long-standing usage of the medium)

the above list also gives a pretty decent comparison to peertube's current implementation of things, but that can honestly be solved pretty quickly, considering just how close knit existing tools that solve half of the problems already are:
-basic definition is already handled
-https://instances.joinpeertube.org/instances is already hosted by the same person as peertube, and thus is probably not all that hard to modify/combine with the main website, while already meeting one of the 3 necessary goals https://framagit.org/chocobozzz/instances-peertube/tree/develop < seems to be the source / github equivalent. the main issue here is a lack of searchability and no language filter.
-also seems to be met decently by the main website

there is however one final issue here, before i get to how we might surpass mastodon's work on the front, in a way specific to this project: the instances and project website page is very easy to miss in the README.md file 
![image](https://user-images.githubusercontent.com/23704040/41082708-32b95c34-69fd-11e8-8065-7f6ac506fb97.png)

it is there, do not misunderstand, but the orientation and position makes it very missable. i myself missed it until i was in the middle of drafting this very post, after having viewed the readme.md 3 to 5 times, i lost count since i wasnt paying attention, and entirely didnt know the main website page existed, i only happened to find the instances list via an issue i viewed when browsing the issue list before posting.

the main issue is the horizontal alignment, which can easily be fixed. it being seperate from all other center-aligned text means it can blend into the picture at a glance very easily. secondly, it doesnt have any header, and the text is very small. i would suggest at least making the text bigger, but would also recommend aligning it to the left.

so now the juicy bit: unlike most social media, the primary interface for a video service is not necessarily the subscriptions/followed users page

it is often something else, like the home page of an instance, or 'trending' as it is most often the intended content of the home page of said instance.

since peertube (and this is not a tech side evaluation, this is from the user perspective) seemingly does not require much overhead to actually display a video from a different service/instance, due to the torrenting based nature of videos, this means that the primary onboarding / user experience can be extrapolated/experienced by a non-user of the service: the act of browsing trending and watching videos does not need an account.

this means, should a 'no-user' or 'view-only' sort of option exist for instances of the service, the instance list could become integrated into the tech itself pretty easily, and the onboarding site could simply link to a 'official' instance that is relatively cheap to upkeep, as it would not have any users, and would only store instances-it-federates-with-data. making such an official portal, but disallowing users to login/create accounts and such, allows for the onboarding process to be GREATLY improved at (again, from a non-programmer or hoster view) seemingly little cost.

this also allows for another feature to be implemented, which is 'closed instances' in which a user cannot make an account, which is a highly utilized mastodon feature that is probably even more useful/likely to be wanted in peertube.

thanks for listening! sorry it ended up being so long, but onboarding is a tricky business and i believe it was necessary. i wasnt sure where to logically split it up into different issues, so i kept it all in one.

**Comment by hoodiek** [comment]
i will be attempting a PR for the README.md changes that i would suggest very shortly, if PRs are allowed to be made by me. i think such things can be closed from strangers? but i don't honestly remember. i have done a similar PR once before, im not super good at code so its rare i can contribute much via PR

**Comment by hoodiek** [comment]
the PR looks like it shall be merged soon, and i realized that the title of the thread is a bit misleading for when it is merged, and beforehand, since there is a second section note related to what the title originally was. as such, the new title is a bit more vague? but also more accurate.

should the PR be / when the PR is merged, the main thing that remains is a much larger project than the PR in question. a searching function for the instances list also doesn't quite belong here, i presume it belongs on the other codebase for said instances list

**Comment by rigelk** [comment]
@hoodiek indeed the instances list codebase is not on github, but issues concerning it are accepted here too for convenience. I like a lot your idea of an instance setup like a looking glass to PeerTube's network.

Of course PRs are welcome :)

**Comment by rigelk** [comment]
Closing this in favor of #824 since it will more properly answer the onboarding issue of video discovery than just a looking glass.
