### ISSUE TITLE
Allow both Spanish (Latin America) and Spanish (Spain) for captions

### ISSUE THREAD

**Issue by notpointify** [Chocobozzz/PeerTube#6310]
### Describe the problem to be solved

Similar to #5962, both can be very different, but currently PeerTube only allows a single "Spanish" caption track.

### Describe the solution you would like

The option for both "Spanish (Latin America)" and "Spanish (Spain)" caption tracks.

**Comment by Chocobozzz** [comment]
Thanks! Added in https://github.com/Chocobozzz/PeerTube/commit/e43326ed5b156826d4e0ea70190f95e17338baf0
