### ISSUE TITLE
Atom Subscriptions Feed Self Link double XML encoded.

### ISSUE THREAD

**Issue by kevincox** [Chocobozzz/PeerTube#6312]
### Describe the current behavior

When accessing a subscription feed such as `https://peertube.example/feeds/subscriptions.atom?accountId=123&token=efd5ffc4-4dfb-4c19-9b1c-696db563c964` the self link is incorrect as it is double-XML encoded such as `<link rel="self" href="https://peertube.example/feeds/videos.atom?accountId=123&amp;amp;token=efd5ffc4-4dfb-4c19-9b1c-696db563c964"/>`.

### Steps to reproduce

```
% curl -i 'https://peertube.example/feeds/subscriptions.atom?accountId=123&token=efd5ffc4-4dfb-4c19-9b1c-696db563c964' | grep '<link rel="self"'
    <link rel="self" href="https://peertube.example/feeds/videos.atom?accountId=123&amp;amp;token=efd5ffc4-4dfb-4c19-9b1c-696db563c964"/>
```

### Describe the expected behavior

The value of the `href` attribute should be the feed link. (Possibly normalized). For this example it should look like:

```xml
    <link rel="self" href="https://peertube.example/feeds/videos.atom?accountId=123&amp;token=efd5ffc4-4dfb-4c19-9b1c-696db563c964"/>
```

Note that the `&` is encoded once making the value of the attribute the original URL.

### Additional information

* PeerTube instance:
  * URL: https://diode.zone/
  * Version: 6.0.4
  * NodeJS version: Unknown
  * Ffmpeg version: Unknown

* Browser name, version and platforms on which you could reproduce the bug: Various clients.
* Link to browser console log if relevant: N/A
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): Unknown

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/7163a1a0448d33e9276843ba797142bba846ec40
