### ISSUE TITLE
Some videos not playing properly in some geographical regions

### ISSUE THREAD

**Issue by FediVideos** [Chocobozzz/PeerTube#6313]
### Describe the current behavior

Some videos on some instances seem to have problems playing for some videos on some instances. For example this video https://video.canadiancivil.com/w/icJhCfvv6iGuE7kFVS18cJ stops after 10 or 20 seconds if you're watching from Europe.

(I asked others about this and similar pattern for them, see Fediverse thread at https://social.chinwag.org/@FediThing/112218319947974047)

Have also seen similar problems on other instances, for example videos older than 3 years on https://tilvids.com don't seem to play at all in Europe, but the maintainer (in North America) can play them fine. For example https://tilvids.com/w/skdJs94R8Noe1CATFhTjgY doesn't play in Europe.

I'm wondering if this is due to geographically-based cacheing services? It's kind of random though, other videos on same instance may work fine everywhere.

### Steps to reproduce

1. Try watching https://video.canadiancivil.com/w/icJhCfvv6iGuE7kFVS18cJ from within Europe
2. See if it plays properly beyond 10 or 20 seconds on all resolutions
3. Try watching same video outside Europe (either by asking another person to do it or using a VPN)

### Describe the expected behavior

Video should play for people around the world.

### Additional information

* PeerTube instance: video.canadiancivil.com
  * URL: https://video.canadiancivil.com
  * Version: 6.0.3
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox 123.0.1, Ubuntu Linux
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

> For example this video https://video.canadiancivil.com/w/icJhCfvv6iGuE7kFVS18cJ stops after 10 or 20 seconds if you're watching from Europe.

I think this is a cloudflare issue, probably the same as https://github.com/Chocobozzz/PeerTube/issues/5046

>  For example https://tilvids.com/w/skdJs94R8Noe1CATFhTjgY doesn't play in Europe.

Seems to be another problem, maybe a sysadmin one. You can tell to the maintainer of tilvids to contact me by email if they need help

**Comment by FediVideos** [comment]
Okay, thanks, I guess this isn't a PeerTube issue then! :/ Hopefully it gets fixed at cloudflare end.

**Comment by FediVideos** [comment]
Just a follow-up, someone has pointed out these play okay in Europe on Safari-based browsers in iOS (which is all of them until Apple opens up browsing). Kind of struggling to see a pattern here, this is so intermittent. It's only a few videos this happens to as well.

**Comment by S0yKaf** [comment]
Hello, I'm the video.canadiancivil sysadmin. The issue was in fact caused by our Cloudflare config (same as #5046). problem should start becoming resolved as Cloudflare propagates the config change. New uploads should work as intended. 

@FediVideos  if you run into anymore issues don't hesitate to shoot me an email at victor@fedihost.co

Cheers!
