### ISSUE TITLE
Searchresult "All languages" should cover also "No linguistic content"

### ISSUE THREAD

**Issue by xundeenergie** [Chocobozzz/PeerTube#6314]
### Describe the problem to be solved

I have many videos without spoken or written text. So i declared them as "No linguistic content".

When i search (standard-search) for some keywords or tags, peertube does not find them. 
Search-language is "All languages"
When i change the search lang to "no language", i can find my videos.

This is not very intuitive.

### Describe the solution you would like

Search-Option "All languages" should also find videos declared as "no linguistic content"

**Comment by Chocobozzz** [comment]
Hi,

I'm sorry but I can't reproduce. Do you have a public instance so I can test a real world example?

**Comment by xundeenergie** [comment]
For sure
https://kino.schuerz.at

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/965c592e890dba0d1cd86fc128a2b538f6b3cd76

**Comment by xundeenergie** [comment]
Thank you!
