### ISSUE TITLE
Notification number of new published videos is wrong

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#6315]
### Describe the current behavior

Apparently the notification number of new published videos counts also all different encoding types which is not really what the publisher wants here. for i.e. if 10 videos are published, the notification number will show 50 if there is 5 different encodings,

### Steps to reproduce

1. publish 10 videos
2. wait until all transcoded
3. check the notification bell number

### Describe the expected behavior

should be 1 for 1 video published, not 1 x X encoded videos.

**Comment by Chocobozzz** [comment]
Hello,

How do you publish your videos? Using the regular upload form? If the notification number accurate when you reload the page?

If no, can you paste the `/api/v1/users/me/notifications?start=0&count=10&sort=-createdAt` request output from web browser network request?

**Comment by ROBERT-MCDOWELL** [comment]
from upload publish import it's ok, it seems to come from channel syncrhonization. for example, notifications bell say 18 new videos and in fact there are only 3 videos visible in local section, As there are 6 transcodings (included the original) so I guess it counts the whole transcoded video rather than one.
how do you want I use /api/v1/users/me/notifications?start=0&count=10&sort=-createdAt ? sory I don't understand you request

**Comment by Chocobozzz** [comment]
> from upload publish import it's ok, it seems to come from channel syncrhonization. for example, notifications bell say 18 new videos and in fact there are only 3 videos visible in local section, As there are 6 transcodings (included the original) so I guess it counts the whole transcoded video rather than one.

Can you take a screen of your notifications? FYI there is 1 notification when the video is imported and another one when it is published.
