### ISSUE TITLE
Muted users videos still online

### ISSUE THREAD

**Issue by M-Stenzel** [Chocobozzz/PeerTube#6316]
### Describe the current behavior

The videos of newly muted users are still visible after muting

### Steps to reproduce

1. Mute user
2. Restart peertube
3. Watching the videos still possible

### Describe the expected behavior

1. Mute user
2. Restart peertube
3. Watching the videos IS NOT possible

### Additional information

* PeerTube instance: tube.xy-space.de
  * URL: https://tube.xy-space.de
  * Version: 6.0.4
  * NodeJS version: 18.13.0
  * Ffmpeg version: 5.1.3

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/2067
