### ISSUE TITLE
local-production.json not valid anymore after update to 6.x

### ISSUE THREAD

**Issue by lonesomewalker** [Chocobozzz/PeerTube#6322]
### Describe the problem

After upgrading from 5.x to 6.x i was still missing the "studio" functionality, also the possibility to replace videos.
So i added these values to the local-production.json from another default installation.
Same intendation, all exact fine.

Now, studio is available, but the setting to replace videos is missing (not able to enable it in admin backend), also when i try to save the new values, i get a:

```
Incorrect request parameters: cache.storyboards.size, transcoding.webVideos.enabled, videoFile.update.enabled
```

Did i miss something?
The values are exact copied from a working instance, also i am wondering why the option to upload videos/overwrite them is not shown...

Thank you

### Additional information

* PeerTube version: 6.0.3
* NodeJS version: docker latest
* Ffmpeg version: docker latest
* Redis version: docker latest
* PostgreSQL version: docker latest

**Comment by Chocobozzz** [comment]
Hi,

` local-production.json` must not be updated manually.

When [you upgrade](https://docs.joinpeertube.org/install/docker#upgrade), do you use `docker compose down -v`? (`-v` option is important)

**Comment by lonesomewalker** [comment]
Hi :-)

``` local-production.json must not be updated manually.```

Yeah, i thought so, but this was the only file which contained these values.

I could SWEAR i did it with -v, but obviously... after doing it again, works like a charm.

Closed.

THANK YOU FOR YOUR SWIFT RESPONSE!
