### ISSUE TITLE
Enhancement for users (streamers): follower counter for obs

### ISSUE THREAD

**Issue by franzcor** [Chocobozzz/PeerTube#6328]
### Describe the desired information/correction

Hi! I am writing this issue because I want to contribute and do my part to make Peertube better.
I am recently streaming again on Peertube and I found out a follower counter is missing (something that displays follower number on the screen when streaming with OBS for example, similarly to what Twitch does).
So I created this little utility that can work both for Youtube and Peertube:

https://codeberg.org/franzbonanza/obsFollowerCounter/

I think it would be a nice addition to suggest users to use this script if they want to have a simple widget that displays info fetched from the API on OBS. It's very easy: you just git clone it, add the info in the js file and import the html page in the OBS scene using obs browser.
Styling can be edited using .css.
This script can be added in the user guide, streamer section.

Let me know what you think!

**Comment by Chocobozzz** [comment]
Hi,

Please use https://framagit.org/framasoft/peertube/documentation for user documentation enhancements! :)
