### ISSUE TITLE
odd positioning for like/dislike/etc buttons

### ISSUE THREAD

**Issue by hoodieak** [Chocobozzz/PeerTube#633]
the first picture is half my (notably quite large) screen, and the other is fullscreened. strangely, there is enough room for it to remain aligned like the second image when half-screened, and it does not move to the position of the second image, which i believe to be preferable in all cases when there is the room for it.

![image](https://user-images.githubusercontent.com/23704040/41084304-c69a9cc0-6a01-11e8-922c-b244f6587b91.png)
![image](https://user-images.githubusercontent.com/23704040/41084310-caf0346a-6a01-11e8-850f-9fce101d695f.png)

as such, i would recommend the code be tuned to properly check for room to shift the buttons, or the algorithm being used to determine it be changed to function in such a way that moves the buttons whenever that room is not being otherwise utilized: this empty space is just ineffficient, and adds to wasting rather-crucial vertical space by putting it on a newline in the very space that users are least likely to scroll too far down past.  comments at least in youtube are not often worth looking at, and as such, you want the comments, should they ever be used, be as close as you can get to the bottom of the video player itself without compromising other features, to encourage usage when appropriate

**Comment by rigelk** [comment]
I think I fixed it in develop last week :relaxed:
