### ISSUE TITLE
SequelizeInstanceError on video import

### ISSUE THREAD

**Issue by skynet2982** [Chocobozzz/PeerTube#6331]
### Describe the current behavior

When I try to import video (manually, by sync or API) most of the times I have the following error.

```
error[4/15/2024, 9:10:18 AM] Cannot execute job 2072 in queue video-import.

{
  "payload": {
    "type": "youtube-dl",
    "videoImportId": 2376,
    "fileExt": ".webm",
    "preventException": false
  },
  "err": {
    "stack": "SequelizeInstanceError: Instance could not be reloaded because it does not exist anymore (find call returned null)\n    at self.reload (/var/www/peertube/versions/peertube-v6.0.4/node_modules/sequelize/lib/model.js:2564:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async refreshVideoImportFromDB (file:///var/www/peertube/versions/peertube-v6.0.4/dist/core/lib/job-queue/handlers/video-import.js:166:19)\n    at async processFile (file:///var/www/peertube/versions/peertube-v6.0.4/dist/core/lib/job-queue/handlers/video-import.js:127:42)\n    at async Object.processVideoImport [as video-import] (file:///var/www/peertube/versions/peertube-v6.0.4/dist/core/lib/job-queue/handlers/video-import.js:42:13)\n    at async Object.wrapPromiseFun (file:///var/www/peertube/versions/peertube-v6.0.4/dist/core/lib/plugins/hooks.js:8:24)\n    at async Worker.processJob (/var/www/peertube/versions/peertube-v6.0.4/node_modules/bullmq/dist/cjs/classes/worker.js:350:28)\n    at async Worker.retryIfFailed (/var/www/peertube/versions/peertube-v6.0.4/node_modules/bullmq/dist/cjs/classes/worker.js:535:24)",
    "message": "Instance could not be reloaded because it does not exist anymore (find call returned null)",
    "name": "SequelizeInstanceError"
  }
}
```

### Steps to reproduce

1. Click on import
2. Select https://www.youtube.com/watch?v=O0xlH2HF5Jc
3. Error on import

### Describe the expected behavior

Video is imported and transcoded.

### Additional information

* PeerTube instance:
  * URL: https://peertube.nogafam.fr/
  * Version: 6.0.4
  * NodeJS version: v20.8.1
  * Ffmpeg version: 4.4.2-0ubuntu0.22.04.1

* Browser name, version and platforms on which you could reproduce the bug: Firefox 124.0.2 on macOS 14.4.1
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): https://cryptpad.fr/pad/#/2/pad/view/YtwIgqDe+RoSF5pYwE0A0GJxmfcF8iY2XLjbEVmTueE/

**Comment by Chocobozzz** [comment]
Hi,

From what I see from the logs the video is deleted immediately after the import. Can you confirm?

**Comment by skynet2982** [comment]
Ok your right, it's seems to be on my side. I have a script that removes video under 60s (to avoid youtube shorts). But for some reason the script is applying on longer videos.
Thanks for your help @Chocobozzz  :)
