### ISSUE TITLE
Smaller bundle size: implement split chunks + tree shake + minification

### ISSUE THREAD

**Issue by emansom** [Chocobozzz/PeerTube#6333]
### Describe the problem to be solved

Currently there are bundles in the frontend that've grown to ridiculous sizes of 1MB+.

This leads to considerable slow down in page loading speed if the bandwidth of the client is limited for bandwidth saving, or if the client is on slow cellular data.

On my instance I'd like to limit the bandwidth per connection to 1Mbit/s (or even lower if applicable) to ensure there's max capacity for the live video being broadcasted @ 10Mbps bitrate with ~150ish viewers on a gigabit link.

The WebRTC sharing should mitigate that risk, however I'd like to cover all potential SPOFs: Murphy had a point you know.

Please note that the NGINX config PeerTube provides denotes units in bytes, not bits: currently it allows for 800KB * 8 = 6.4Mbit/s on the pages by default.

### Describe the solution you would like

The build process for the frontend to split chunks, tree shake and minimize to ensure faster page loading on slower connections.

Or an even better way if there's one. Haven't kept up with the latest in minification.

**Comment by Chocobozzz** [comment]
Hello,

We already do all this stuff, and continuously improve chunks splitting/tree shacking (for example by moving to standalone components: https://github.com/Chocobozzz/PeerTube/commit/5e041ff7c2a72f1fdff75d0bc11dd6248108266f)

Please create dedicated issues if you notice a specific work we can do to decrease front-end initial size.

**Comment by emansom** [comment]
> We already do all this stuff, and continuously improve chunks splitting/tree shacking (for example by moving to standalone components: [5e041ff](https://github.com/Chocobozzz/PeerTube/commit/5e041ff7c2a72f1fdff75d0bc11dd6248108266f))

Wasn't aware this was already implemented in the latest release candidate. Will test!
