### ISSUE TITLE
Peertube 6.1.0 version

### ISSUE THREAD

**Issue by yildirimyaprak** [Chocobozzz/PeerTube#6334]
### Describe the problem

Hi chocobozz,
When will the stable version of Peertube 6.1.0 be available to users? Currently version 6.0.4 seems to be active.

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by Booteille** [comment]
Hi! The latest release candidate just got released.

Usually, version are released once a quarter (there are sometimes exceptions of this rhythm) when they are ready.
