### ISSUE TITLE
Blocking account via REST API mutes the account, rather than blocking the account

### ISSUE THREAD

**Issue by agrathwohl** [Chocobozzz/PeerTube#6335]
### Describe the current behavior

Sending a `POST` request to the REST API on my peertube 6.0.3 instance [as documented here](https://docs.joinpeertube.org/api-rest-reference.html#tag/Account-Blocks/paths/~1api~1v1~1server~1blocklist~1accounts/post) does not perform the correct action. Instead of blocking the account, it *mutes* the account instead. I cannot find another REST API endpoint in the documentation that blocks an account.

### Steps to reproduce

1. Acquire admin credentials to get an admin-level `access_token`.
2. Send bearer-authenticated `POST` to `/api/v1/server/blocklist/accounts` with a JSON body such as: `{ "accountName": "testaccount@domain" }`.
3. On the Peertube admin GUI, the user is now listed as *muted*, not *blocked*.

### Describe the expected behavior

Expected behavior is the user gets blocked, not muted.

### Additional information

* PeerTube instance:
  * Version: 6.0.3

**Comment by Chocobozzz** [comment]
Hi,

PeerTube supports a mute++ feature, between mute and a block: https://docs.joinpeertube.org/use/mute#what-does-mute-do
As described in the documentation, it mutes the user but also block some interactions on your videos.

See the following issue for a complete blocking feature: https://github.com/Chocobozzz/PeerTube/issues/1087
