### ISSUE TITLE
Video embedding error in pre-release 6.1.0-rc.1

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#6336]
### Describe the current behavior

After updating the server to version 6.1.0-rc.1, users began to complain that the videos that were embedded on their sites stopped working.
The following error appears

![image](https://github.com/Chocobozzz/PeerTube/assets/11453567/f0b9cc4c-26e0-4423-95ae-6b50cba2afb0)

It also doesn’t work directly on the instance.
![image](https://github.com/Chocobozzz/PeerTube/assets/11453567/146d7182-28c1-4739-b6e7-965917860a52)

Forced to rollback all changes.

### Additional information

* PeerTube instance:
  * Version: 6.1.0-rc.1
  * NodeJS version: v18.19.0
  * Ffmpeg version: 5.1.4-0+deb12u1

**Comment by MattyBoombalatty** [comment]
Re-run the update script, per [this issue](https://github.com/Chocobozzz/PeerTube/issues/6337)

**Comment by Alterak** [comment]
> Re-run the update script, per [this issue](https://github.com/Chocobozzz/PeerTube/issues/6337)

I have updated PeerTube again. Everything is working now, thank you.
