### ISSUE TITLE
Weird "lock" icon and "..." in /admin/videos/list url

### ISSUE THREAD

**Issue by vincib** [Chocobozzz/PeerTube#6337]
### Describe the current behavior

at the following URL : 

https://dev.indymotion.fr/admin/videos/list

I see: 

- a weird "lock", a  "-" button and a text field with no legend
- the "..." at the right of the info column labels should show "can't upload to object storage" or something similar (because I was testing a broken S3 server on purpose ;)) but the ... is hidding something, right? 

![Screenshot_20240417_180147](https://github.com/Chocobozzz/PeerTube/assets/358692/3d42e930-69a6-4825-a550-33770c281a66)

### Steps to reproduce

1. install 6.1.0~rc1
2. upload a video
3. go to /admin/videos/list url
4. click on the > at the left of one video

### Describe the expected behavior

- I expect to see all flags of the videos in the "info" column
- I expect that the lock + field + button would "do" something or "have a legend" ? 

### Additional information

* PeerTube instance: 
  * URL:https://dev.indymotion.fr/ 
  * Version: 6.1.0~rc1
  * NodeJS version:  v18.19.0

* Browser name, version and platforms on which you could reproduce the bug: chromium 123

**Comment by MattyBoombalatty** [comment]
I also noticed that. Also, the total size is determined based on the input size of the original file, AND the transcoded version. As far as I know, the original input file is not actually saved (unless chosen in the configuration)

**Comment by Chocobozzz** [comment]
Hi,

Can you reuse the upgrade script? I updated the broken archive files from the github release

**Comment by MattyBoombalatty** [comment]
That worked - thank you.

**Comment by vincib** [comment]
same here, fixed, thanks !
