### ISSUE TITLE
Incorrect Video Size Reported by Admin Page

### ISSUE THREAD

**Issue by MattyBoombalatty** [Chocobozzz/PeerTube#6341]
### Describe the current behavior

In 6.1.0-rc1, the Administration -> Videos page shows each newly transcoded video as what it would be after transcoding (size on system), *plus* the original video size. Please note that "keep a copy of the original video" is disabled.

### Steps to reproduce

1. Upload a video (let's say 10 MB pre-transcoded)
2. After video processes, the video is 15 MB on the file system
3. Total video size is reported as 25 MB, rather than 15 MB.

### Describe the expected behavior

The total video size should be post-transcoded video size, rather than the original size plus the transcoded size. I do not know if this is negatively impacting user storage capacity but will test it shortly.

### Additional information

* PeerTube instance:
  * URL: https://nicecrew.tv
  * Version: 6.1.0-rc1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by MattyBoombalatty** [comment]
It appears that only the HLS / web video size counts towards the user's storage quota, not the size reflected in "total". In this case the user would only have 455.5 MB added to their quota, rather than 632.3 MB (original file size + HLS transcoded file size).

![image](https://github.com/Chocobozzz/PeerTube/assets/95333219/6a984290-1007-4572-af13-2fea8bce6a00)
![image](https://github.com/Chocobozzz/PeerTube/assets/95333219/9fec7b80-be22-4b31-8b93-9fa23ef25689)

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/bce0f2f11b2eb22af97430cb91ec0f6bf049c128
