### ISSUE TITLE
add privacy settings to synchronization

### ISSUE THREAD

**Issue by erinarbleizez** [Chocobozzz/PeerTube#6343]
### Describe the problem to be solved

right now when we create a synchronization, video uploaded that way are public by default. But we don't always want to give access to the whole world to those videos without prior moderation. With how the world is turning (yes I'm pointing to the 2 wars that are also information war), a good channel may sometime fail to meet what we, as admin, may accept but not with a blind faith.

### Describe the solution you would like

on the form to create a synchronization and on the form to edit them, we should be able to choose the default privacy for new videos. That way we would be able to review video, remove them, keep them private or internal access, or we may decide to give internet access to it.

**Comment by Alterak** [comment]
> ### Describe the problem to be solved
> right now when we create a synchronization, video uploaded that way are public by default. But we don't always want to give access to the whole world to those videos without prior moderation. With how the world is turning (yes I'm pointing to the 2 wars that are also information war), a good channel may sometime fail to meet what we, as admin, may accept but not with a blind faith.
> 
> ### Describe the solution you would like
> on the form to create a synchronization and on the form to edit them, we should be able to choose the default privacy for new videos. That way we would be able to review video, remove them, keep them private or internal access, or we may decide to give internet access to it.

You can set the default value in the configuration file

![image](https://github.com/Chocobozzz/PeerTube/assets/11453567/ad33caed-f7c3-43aa-9c78-4c7834da5856)

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/5265

See also: https://github.com/Chocobozzz/PeerTube/issues/5217
