### ISSUE TITLE
Allow users to upload a new version of their video: limit to 4MB

### ISSUE THREAD

**Issue by spirillen** [Chocobozzz/PeerTube#6349]
### Describe the current behavior

I was trying to replace a damaged Video but got limited to 4MB, while I can upload unlimited (by config) and tested as usual upload, and working.

### Steps to reproduce

1. Go to the advance tab under video
2. Try uploading a video of ~35MB
3. You get a failure, that says the file is bigger than 4MB

### Describe the expected behavior

I would expect the file limit would be following the default file size limitation set system wise config.

### Additional information

* PeerTube instance:
  * URL: redacted for privacy
  * Version: 6.0.3
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: FF-esr + tor
* Link to browser console log if relevant: N/A
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): N/A

**Comment by Chocobozzz** [comment]
Hello,

Ensure your nginx configuration is up to date to [the template](https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube#L81) (See the important notes of v6: https://github.com/Chocobozzz/PeerTube/releases/tag/v6.0.0)
