### ISSUE TITLE
Caption Option and quality option is not visible and not selectable.

### ISSUE THREAD

**Issue by biowilli** [Chocobozzz/PeerTube#6351]
### Describe the current behavior

The caption option is not selectable and remains invisible. This issue was observed across multiple versions of PeerTube, specifically versions 5.0.1 and 6.0.3. 

Testing was conducted on the following platforms:

iOS App:
- Chrome version 124.0.6367.71
- Firefox version 125.1

peertube.fr
![here](https://github.com/Chocobozzz/PeerTube/assets/47250005/f024a15e-b92f-4e00-a20a-b18457f131aa)

fair.tube:
![IMG_4817](https://github.com/Chocobozzz/PeerTube/assets/47250005/69689afd-79fc-4321-b66c-3b117ef6a357)

### Steps to reproduce

1. Access PeerTube platform.
2. Attempt to select the caption option or click on the quality option on ios:

iOS App:
- Chrome version 124.0.6367.71
- Firefox version 125.1

3. Observe that the option is not selectable and remains invisible, only a box is visible 

### Describe the expected behavior

The caption option should be selectable and visible for users to enable or disable captions as needed, also quality is should also be selectable :)

### Additional information

* PeerTube instance:
  * URL: [peertube.fr](peertube.fr)and [fair.tube](fair.tube)
  * Version: 5.0.1 and 6.0.3. 
  * NodeJS version: -
  * Ffmpeg version: -

* Browser name, version and platforms on which you could reproduce the bug:

iOS App:
- Chrome version 124.0.6367.71
- Firefox version 125.1

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue. It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/4e09837aa0e9ba46b2fd3b44443ce02aa4b61e4d
