### ISSUE TITLE
Subscriber count varies depending on the instance

### ISSUE THREAD

**Issue by TobiGr** [Chocobozzz/PeerTube#6352]
### Describe the current behavior

The subscriber count of some channels is different when viewing them on their home instance of via a different one. Bug mught eb related to version difference between instances (6.1.0-rc.1 vs 6.0.4)

![grafik](https://github.com/Chocobozzz/PeerTube/assets/17365767/135e43cf-4d75-44e9-91f5-526ec676dec3)
![grafik](https://github.com/Chocobozzz/PeerTube/assets/17365767/ba6aab43-7a78-4301-9e3c-e409dbacef35)

### Steps to reproduce

1. Open https://video.lqdn.fr/c/lqdn_channel/videos -> subscriber count > 900
2. Open https://framatube.org/c/lqdn_channel@video.lqdn.fr/videos -> no subscribers

### Describe the expected behavior

Subscriber count is the same on both instances, i.e. the same as on the home instance.

### Additional information

* PeerTube instance: 
  * URL: https://video.lqdn.fr
  * Version: 6.1.0-rc.1
  * NodeJS version: ?
  * Ffmpeg version: ?

and 

* PeerTube instance: 
  * URL: https://framatube.org
  * Version: 6.0.4

* Browser name, version and platforms on which you could reproduce the bug: -
* Link to browser console log if relevant: -
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): -

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/47ae6e880d3228f40cc10f71a4656031e829f221
