### ISSUE TITLE
Comments to autoblocked videos listed publicly are being published on the fediverse, revealing a playable URL

### ISSUE THREAD

**Issue by Sakrecoer** [Chocobozzz/PeerTube#6354]
### Describe the current behavior

When a new user that has auto-moderation enabled published a public video, it is being autoblocked. However, if this video is set to "public", any comments made by the moderation is published on the fediverse as a public post. Many fediverse system fetches the toot being answered to, meaning that the URL of the video is revealed. It is also playable by unauthenticated users, effectively acting like an unlisted public video, before moderation can take place.

### Steps to reproduce

1. publish a public video from an account that is automoderated
2. create a comment on this video from a moderator account
3. check the account profile on a misskey account to find the moderator comment being public, including the post being answered to. The post being answered to contains a link to the video. This link is playable by unauthenticated users.

### Describe the expected behavior

Set autoblocked videos to "private" and send comments to autoblocked videos as private messages. (DMs?)

### Additional information

* PeerTube instance:
  * URL: v.basspistol.org
  * Version: 6.0.4
  * NodeJS version: v18.20.2
  * Ffmpeg version: 4.4.2-0ubuntu0.22.04.1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Auto blocked and blocked videos are not publicly available. Please try with another web browser to ensure the video is not displayed to anonymous users.

I'll fix AP federation of comments on private/blocked/internal videos.

**Comment by Sakrecoer** [comment]
Thank you for your quick response @Chocobozzz 
They are indeed not visible when accesed by `w/shortlinkHASH` like this: https://v.basspistol.org/w/kWrqgSH63tFH57Ng9SmxZ2 But in the fediverse post, the link displayed is the long version of the above link (https://v.basspistol.org/w/a177767c-5026-46a3-a877-f4b19b314447) At some point it was accessible to anons (i tried in a "private" browsing tab)... 

But I can't reproduce it anymore... so... i might have just _imagined_ i was in a private browsing tab... :shrug: 

Will keep an eye out for it. Many thanks for looking into the AP federation of comments :purple_heart: 

Mad love,
Setto

**Comment by Chocobozzz** [comment]
> I'll fix AP federation of comments on private/blocked/internal videos.

Fixed in https://github.com/Chocobozzz/PeerTube/commit/afb28272f53d7b3a547bb7b06eff09cf482d3a11
