### ISSUE TITLE
So many updates?

### ISSUE THREAD

**Issue by TheCableGuy99** [Chocobozzz/PeerTube#6360]
### Describe the problem

Hi, I'm new to Peertube and running it in a Docker container on my Synology NAS. 

I've had it running just a couple of months now and using the tag: "production-bookworm". 

What I don't understand is why there are so many updates to the docker container (practically every day) when the github says there's been no new releases for weeks. 

Am I using the wrong tag?

Thanks.

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by Chocobozzz** [comment]
Hello,

The image is updated regularly to get the latest base image updates (debian bookworm with nodejs).

See https://docs.docker.com/develop/security-best-practices/#rebuild-images for more information
