### ISSUE TITLE
Transcode Batch Action on failed transcoded videos does not work

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#6361]
### Describe the current behavior

if I check more than one video with status "transcoded failed" and batch the action "hls transcode"
an error message occurs saying "This video is already transcoded"
Rather, if I do one by one the transcoding state is converted to "To transcode" to start a new transcoding.

### Describe the expected behavior

must have the same confirm message to transcode the batch than the one video hls (or webvideo) transcode

### Additional information

PeerTube 6.0.4

**Comment by ROBERT-MCDOWELL** [comment]
Also I noticed that if for example some videos from a sync channel has "to import" status and if for any reason the targeted video source is not accessible or could not be found I get this alert:

Error
Cannot read properties of undefined (reading 'getVideoOrStreamingPlaylist')

Would it be better to have a less coding alert and more user alert to let the user decide if it needs to cancel/delete the video or else? thanks

**Comment by Chocobozzz** [comment]
Bulk force transcoding implemented in https://github.com/Chocobozzz/PeerTube/commit/57c94fb51cee630fed5a0e83d18b56b2027a8794

> Cannot read properties of undefined (reading 'getVideoOrStreamingPlaylist')

Please create a dedicated issue with the complete stacktrace :)
