### ISSUE TITLE
RTL UI inconsistency

### ISSUE THREAD

**Issue by jermanuts** [Chocobozzz/PeerTube#6363]
### Describe the current behavior

Search icon overlapping with text
![image](https://github.com/Chocobozzz/PeerTube/assets/109705802/2102d8be-edf5-4598-90a5-ba7bc6a8d317)

Settings: 
![image](https://github.com/Chocobozzz/PeerTube/assets/109705802/e5e46c58-f7ce-418a-a2b7-9c0b4d9518a0)

Lastly, shouldn't input fields like email and password set to LTR instead of RTL?

### Steps to reproduce

1.
2.
3.

### Describe the expected behavior

As shown above. Also, shouldn't email and password be LTR? https://rtlstyling.com/posts/rtl-styling#rtl-design-considerations

### Additional information

* PeerTube instance:
  * URL:
  * Version: 6.10
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! Fixed by https://github.com/Chocobozzz/PeerTube/commit/810519b1d41bd938a0e13588d2ef77ea83411e98

> As shown above. Also, shouldn't email and password be LTR?

Yes you're right, but unfortunately placeholders using RTR with a value using LTR using `dir` attribute is not supported by web browsers yet: https://github.com/whatwg/html/issues/4903
