### ISSUE TITLE
Deleted comments are counted in the "In this instance federation" total

### ISSUE THREAD

**Issue by dexgs** [Chocobozzz/PeerTube#6365]
### Describe the current behavior

When a comment is deleted, the total under "By users on this instance" on the about page updates correctly, but the total under "In this instance federation" still counts the deleted comment.

### Steps to reproduce

1. Create a comment
2. Check total comments reported under "In this instance federation"
3. Delete the comment
4. Check total comments reported under "In this instance federation"

### Describe the expected behavior

Deleted comments should not be counted in the total under "In this instance federation"

**Comment by ElonVampire** [comment]
收到！

**Comment by Chocobozzz** [comment]
Thanks for the issue, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/cb88f25ffa333a9dd931dde359882c85c264b42b
