### ISSUE TITLE
Import failed, text value too long for chapters

### ISSUE THREAD

**Issue by Mike35538** [Chocobozzz/PeerTube#6366]
### Describe the current behavior

A YouTube video with long chapter text/key moments can cause an error and fail to import due to what seems to be a character limit and the import text not being truncated.

Error message:
    "message": "value too long for type character varying(255)",
    "name": "SequelizeDatabaseError",
    "parent": {
      "stack": "error: value too long for type character varying(255)\n    at Parser.parseErrorMessage (/var/www/peertube/versions/peertube-v6.1.0/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/var/www/peertube/versions/peertube-v6.1.0/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/var/www/peertube/versions/peertube-v6.1.0/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/var/www/peertube/versions/peertube-v6.1.0/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
      "message": "value too long for type character varying(255)",
      "length": 99,
      "name": "error",
      "severity": "ERROR",
      "code": "22001",
      "file": "varchar.c",
      "line": "632",
      "routine": "varchar",
      "sql": "INSERT INTO \"videoChapter\" (\"id\",\"timecode\",\"title\",\"videoId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4,$5) RETURNING \"id\",\"timecode\",\"title\",\"videoId\",\"createdAt\",\"updatedAt\";",

For example, this YT video will cause the import error to occur.
https://www.youtube.com/watch?v=rkbI651WHl8

### Steps to reproduce

1. Import the YT URL listed to see the error occur.

**Comment by Chocobozzz** [comment]
Hello,

Please fill the bug template, in particular the **Additional information** (with your instance version/URL)
