### ISSUE TITLE
Object Storage: Google Cloud Storage Config issues 

### ISSUE THREAD

**Issue by kpideas** [Chocobozzz/PeerTube#6367]
### Describe the problem

I was trying the steps listed in #4855 with configs directly in production.yaml and GCS bucket does have the CORS. But I keep getting the Access Denied error.

I'm able to use gsutil to upload a file from GCP VM to the GCS bucket after using the Service Account.

Am I missing any other configs? And the object storage lib seems to be AWS specific? 

Please suggest 

_Originally posted by @kpideas in https://github.com/Chocobozzz/PeerTube/issues/4855#issuecomment-2089603139_
            

### Additional information

* PeerTube version: 6.0.4

**Comment by Chocobozzz** [comment]
Hello,

Please use the forum for PeerTube sysadmin related questions: https://framacolibri.org/c/peertube

**Comment by kpideas** [comment]
Sure, I just posted it there
https://framacolibri.org/t/object-storage-google-cloud-storage-config-issues/21307

Thank you!
