### ISSUE TITLE
Error in installation documentation

### ISSUE THREAD

**Issue by jpatje** [Chocobozzz/PeerTube#6368]
### Describe the problem

After installing all the dependencies outlined in the [dependencies](https://docs.joinpeertube.org/support/doc/dependencies) document.
I want to create the database following the guide of the [official installation](https://docs.joinpeertube.org/install/any-os), Database section. It says to:

_cd /var/www/peertube_ and after that:
_sudo -u postgres createuser -P peertube_

But it is not possible to cd into the var/www/peertube directory. The error is 'permission denied'.
Of course I can sudo su and enter the directory in this way, but then the next command won't work (sudo -u postgres createuser -P peertube).
Doing a clean install on Ubuntu 24.04 LTS.
 

### Additional information

* PeerTube instance URL: not yet installed
* PeerTube version:  not yet installed
* NodeJS version: 18.19.1
* Ffmpeg version: 6.1.1
* Redis version: 7.0.15
* PostgreSQL version: 16.2

**Comment by jpatje** [comment]
Found the solution, it is not in the manual. sudo chmod 755 peertube sets the correct permissions (under /var/www).

**Comment by Chocobozzz** [comment]
Hi,

The documentation state:

> Ensure the peertube root directory is traversable by nginx:
```
ls -ld /var/www/peertube # Should be drwxr-xr-x
```

In https://docs.joinpeertube.org/install/any-os#peertube-user section :)
