### ISSUE TITLE
downloading old videos don't work (error 404) json

### ISSUE THREAD

**Issue by ArnOCP** [Chocobozzz/PeerTube#6369]
### Describe the current behavior

Goodmorning,
After the 6.1.0 upgrade (?), all old videos cannot been downloading, they can been watch in my instance, but not downloading?
I had to switch with this two line in my nginx conf to download either new videos either old videos:
![image](https://github.com/Chocobozzz/PeerTube/assets/97297565/5fc566e0-9c8f-4210-a63d-6f6dd18807f2)
the comment line allow old videos to be downloading
the actual config allowing the new videos?
Would you mind to helping me?
Regards

### Steps to reproduce

1.click on the link "télécharger"
2.its genrate a link: https://videos.mydomain.tld/download/videos/f80a3f19-87b4-4bec-9f6d-fda6bbaf5b26-1080.mp4
3. depanding of my nginx conf i can or not downloading the video

### Additional information

* PeerTube instance:
  * URL: https://videos.mydoamin.tld
  * Version: 6.1.0
  * NodeJS version: 18.20.2
  * Ffmpeg version: 5.1.4-0+deb12u1

* Browser name, version and platforms on which you could reproduce the bug: Firefox 115 ESR, Windows 10 22H2
* Link to browser console log if relevant: 
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

Have you followed the [IMPORTANT NOTES](https://github.com/Chocobozzz/PeerTube/blob/develop/CHANGELOG.md#important-notes-5) on V6 upgrade?

In particular:

>  `storage.videos` must be **renamed** to `storage.web_videos`
> Configuration value of `storage.web_videos` must have the directory name to be **changed** from `videos/` to `web-videos/`
> Directory on filesystem must be **renamed** from `videos/` to `web-videos/` to represent the value of `storage.web_videos`

You must also update your nginx configuration
