### ISSUE TITLE
Tags on docker images

### ISSUE THREAD

**Issue by MikaXII** [Chocobozzz/PeerTube#637]
Hi, 

Possible to add tags on your docker image pushed into your registry ?
Something like : 
- v1.0.3-beta2
- v1.0.0 <- assuming stable image

etc etc... And your images are build throught a pipeline or you push them manually ?

**Comment by Chocobozzz** [comment]
We use docker cloud that builds automatically the images. I'll try to configure it to build tags too.

**Comment by MikaXII** [comment]
Thank you, I work on a k8s helm chart and I can use a custom image built by my self but I'll prefer use your official image (ethically its better ^^)

**Comment by Chocobozzz** [comment]
Done https://hub.docker.com/r/chocobozzz/peertube/tags/
