### ISSUE TITLE
Batch delete failed runners job shows "unknown runner jobs" systematically

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#6370]
### Describe the current behavior

Deleting with status "errored/parent job failed" multiple jobs with the batch action button result always with an alert "unknown runner jobs" despite of it indeed deletes some jobs but not all

### Steps to reproduce

1. filter runner jobs with "failed"
2. select all and batch delete

### Describe the expected behavior

must force delete and show "success" even if some runner jobs don't exist anymore.

### Additional information

* PeerTube instance:
  * Version: 6.1.0

**Comment by Chocobozzz** [comment]
Hi,

To better understand: when you batch delete and the data is refreshed you no longer see the jobs you selected?
