### ISSUE TITLE
Video imported from channel sync accept description length beyond the max authorized

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#6371]
### Describe the current behavior

when a video with a long description is automatically imported from channel sync PT allows it without problem.
but if we update this video to make some changes, it says "description too long".

### Steps to reproduce

1. import a channel from synchronization
2. in this channel must have a video with a very long description
3. select this video once imported and transcoded and click on update to make some changes

### Describe the expected behavior

it must make a choice here. Truncate the description automatically when description length is more than the max, or increase the max length, or pause the import before the admin fixes which description to be truncated

### Additional information

* PeerTube instance:
  * Version: 6.1.0

**Comment by Chocobozzz** [comment]
Hi,

Can you provide the URL of the problematic video?
