### ISSUE TITLE
6.1.0 docker account exports fail with bucket not found

### ISSUE THREAD

**Issue by JerryLerman** [Chocobozzz/PeerTube#6372]
### Describe the current behavior

6.1.0 - Using the docker version, and using Wasabi S3 buckets, when using the new export feature, I get a "bucket not found" error because it's trying to access, by default, "user-exports.s3.wasabisys.com", which can't exist. I believe the .ENV file ought to define 3 new bucket configuration items for defining the bucket to access. For example:
PEERTUBE_OBJECT_STORAGE_USER_EXPORTS_BUCKET_NAME
PEERTUBE_OBJECT_STORAGE_USER_EXPORTS_PREFIX
PEERTUBE_OBJECT_STORAGE_USER_EXPORTS_BASE_UR

### Steps to reproduce

1. On a 6.1.0 docker instance that uses Wasabi S3, request account export. The bucket not found error will be in the logs, showing it can't find user-exports.s3.wasabisys.com and the account holder will get an email that this was the error for a failed export.
2.
3.

### Describe the expected behavior

Export works

### Additional information

* PeerTube instance:
  * URL: https://my-sunshine.video
  * Version: Docker. May still be on 6.0.4
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/21f4ed5c33638156b8ab047da2ac2fd7ce34f228

As a side note your can also add a `production.yaml` in `docker-volume/config` that would contain configuration you could not set using env variables.
