### ISSUE TITLE
Error log when a plugin retrieves settings

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#6374]
### Describe the current behavior

There are some errors logs when a plugin retrieves its settings:

```json
error[05/05/2024 00:32:27] internal

{
  "result": {
    "chat-per-live-video": true,
    "chat-all-lives": false,
    "chat-all-non-lives": false,
    "disable-websocket": false,
    "prosody-room-type": "video",
    "federation-dont-publish-remotely": false,
    "chat-no-anonymous": false,
    "prosody-room-allow-s2s": true,
    "prosody-s2s-port": "5269"
  }
}
```

This seems to come from here:

https://github.com/Chocobozzz/PeerTube/blob/46b45dc51dad7173d94667733f52aea8e484ea0c/server/core/models/server/plugin.ts#L177

I guess it was a debug log that you forgot to remove.

### Steps to reproduce

1. install a plugin using settings (livechat for example)
2. check error logs
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Oup's and thanks! Removed in https://github.com/Chocobozzz/PeerTube/commit/81d4d557f754681de035778cef7a82e0f0c0f93b
