### ISSUE TITLE
cannot make a documentation fix

### ISSUE THREAD

**Issue by cyberb** [Chocobozzz/PeerTube#6378]
### Describe the desired information/correction

Each documentation page has a link to edit.
1. Click on it and it asks for a login to framagit.org.
2. It asks for a login/password or login using third party apps like gitlab.
3. Click on login with gitlab (I have an account) and authorize framagit.
4. Get a wired error message saying:
`Signing in using your GitLab.com account without a pre-existing GitLab account is not allowed. Create a GitLab account first, and then connect it to your GitLab.com account.`
![Screenshot_2024-05-06-13-33-27-351_org mozilla firefox](https://github.com/Chocobozzz/PeerTube/assets/885528/50dfb800-f57b-49ac-98b6-28dac6932930)

**Comment by cyberb** [comment]
Unless this login is intended for admin users only because I thought of it as offer a fix/PR for you to pull.

**Comment by cyberb** [comment]
The actual typo is here:
https://docs.joinpeertube.org/contribute/plugins

```
an helper
```
Should be
```
a helper
```
![IMG_20240506_134420](https://github.com/Chocobozzz/PeerTube/assets/885528/c5b59ec0-8177-4195-81f2-b9ea64f7386c)

**Comment by Chocobozzz** [comment]
This error is weird :thinking: Not sure if it's a gitlab bug, but anyway I fixed the typo directly in https://github.com/Chocobozzz/PeerTube/commit/32b0206cd320194108bb035e72519ab43ec46e06

Thanks!
