### ISSUE TITLE
Cannot update GeoIP database for cities

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#6380]
### Describe the current behavior

Upon updating to 6.1.0 our instance cannot download db for cities, but for countries work well. I've tried to curl the URL from our server and it returns 200.

```
Cannot update GeoIP database from https://dbip.mirror.framasoft.org/files/dbip-city-lite-latest.mmdb.","err":{"stack":"HTTPError: Response code 500 (Internal Server Error) ... }
```

### Steps to reproduce

1. Update to 6.1.0
2. Watch logs.

### Describe the expected behavior

It should be downloaded.

### Additional information

* PeerTube instance:
  * Version: 6.1.0
  * NodeJS version: v18.20.2

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue. It should be fixed :)
