### ISSUE TITLE
number of views

### ISSUE THREAD

**Issue by yildirimyaprak** [Chocobozzz/PeerTube#6390]
### Describe the current behavior

Hi!
The peertube 6.0.3 version we use works on the **intranet network**. Although the videos uploaded by the admin are watched by everyone, the number of views remains 0.
How we can solve this problem.

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Try 6.1 where we made some changes in the way we count views: https://joinpeertube.org/news/release-6.1

We also fixed [this bug](https://github.com/Chocobozzz/PeerTube/issues/6307)
