### ISSUE TITLE
Lightweight PeerTube icon, for blogs/sites to place in footers, etc.

### ISSUE THREAD

**Issue by Jieiku** [Chocobozzz/PeerTube#6396]
### Describe the problem to be solved

Lightweight PeerTube icon, for blogs/sites to place in footers, etc.

### Describe the solution you would like

This one I made comes out at only 176 bytes.

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M3 12V0l9 6-9 6Z"/><path fill="#777" d="M3 24V12l9 6-9 6Z"/><path fill="#f60" d="M12 18V6l9 6-9 6Z"/></svg>`

![peertube](https://github.com/Chocobozzz/PeerTube/assets/106644/103a9d3d-651f-4fb8-b2a0-b0b4765cbe35)

**Comment by Chocobozzz** [comment]
Hi,

Thank you, but it's not exactly the same as https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/assets/images/logo.svg

(your icon has a left padding in the svg box)
