### ISSUE TITLE
Generate multiple video resolutions

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#64]
Now we have a job scheduler that can run ffmpeg commands we can generate multiple resolutions of the same video for low bandwidth users.

This should be opt-in because it will require more disk space.

TODO:
 * Generate multiple video resolutions (360p, 720, 1080...) through job scheduler
 * Add a new field in video model (`resolutions`?) and send it to remote pods
 * Suffix video torrents and files by the resolution (blablabla-360.mp4, blablabla-360.torrent)
 * Generate multiple video magnets (one per resolution) when getting video attributes

Then the client will be able to choose the right resolution according to its bandwith. But it will be another task.

**Comment by ldidry** [comment]
Todo: ask a ffmpeg guru what are the best options to encode for every resolution?

**Comment by Chocobozzz** [comment]
Implemented:  https://github.com/Chocobozzz/PeerTube/commit/40298b02546e8225dd21bf6048fe7f224aefc32a and https://github.com/Chocobozzz/PeerTube/commit/aa8b6df4a51c82eb91e6fd71a090b2128098af6b
