### ISSUE TITLE
Allow setting a profile ID for channels

### ISSUE THREAD

**Issue by espectalll** [Chocobozzz/PeerTube#640]
Just like user profiles are asked to have an username, video channels could be configured with a specific ID. This could be done when creating the channel and, if feasible and properly convenient, after doing so. The main purpose of this is to get easily human-readable channel URLs in order to make sharing and following a specific channel easier.

**Comment by Chocobozzz** [comment]
Yes, but how to differentiate an account than a video channel?

If my account is `chocobozzz@peertube.cpy.re`, and I create a channel `squall@peertube.cpy.re` it's confusing. Moreover nobody will be able to register on `peertube.cpy.re` with the username `squall`.

**Comment by espectalll** [comment]
is easy, you just don't need to. Block usernames which are already registered for both. Allow all of them. Or rather, if there is any need to differentiate, append a prefix/suffix for channels and/or accounts.

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/8a19bee1a1ee39f973bb37429e4f73c3f2873cdb
