### ISSUE TITLE
Cannot compute FPS because 0 is lower than our minimum value 1

### ISSUE THREAD

**Issue by Casuallynoted** [Chocobozzz/PeerTube#6403]
### Describe the current behavior

When uploading some videos that are primarily audio, I've noticed I get this error and the video doesn't get transcoded to HLS. Seems to maybe be related to previous issues that were marked as fixed.

### Steps to reproduce

1. Upload a video with a still image and audio
2. Roughly 70% chance it won't transcode
3. Will provide this error

### Describe the expected behavior

Should convert to HLS

### Additional information

* PeerTube instance: 
  * URL: https://peertube.casually.cat
  * Version: 6.1.0
  * NodeJS version: v18.20.2
  * Ffmpeg version: 5.1.4-0+deb12u1

* Browser name, version and platforms on which you could reproduce the bug: Firefox, Chrome
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Casuallynoted** [comment]
Oh! Actually, as an addition to this, it seems to be happening specifically with videos that have black bars on the left and right side. Videos that feature audio only but have a full screen image do not trigger this error. For example:

![image](https://github.com/Chocobozzz/PeerTube/assets/6272557/0e3c8832-d1a6-4a9d-8e54-f20d40747be0)
The video on the top vs the one on the bottom

**Comment by Chocobozzz** [comment]
Hi,

Can you share a link of the video so I can debug it?

**Comment by Casuallynoted** [comment]
> Hi,
> 
> 
> 
> Can you share a link of the video so I can debug it?

Here's one:

https://peertube.casually.cat/w/qZcCorVZRWNYpzVBTw28fM

**Comment by Chocobozzz** [comment]
Can you also paste peertube error logs? Seems related to storyboard generation bug on my side

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/4ea659d569d596791bc6bf3f15d8ee9eea20b672

(the main reason of your bug is because your video has 0.2 FPS)
