### ISSUE TITLE
Playback issue with range (position) with unusual video framerate

### ISSUE THREAD

**Issue by gilou** [Chocobozzz/PeerTube#6404]
### Describe the current behavior

If I try to seek in a video, that runs at 1 FPS (240p1), Firefox issues a byte range request but loads indefinitely, and does not manage to play the video at all.

### Steps to reproduce

1. Using Firefox, go to https://www.yiny.org/w/51UnWF8X1BBQBGhhPbseGU?start=5m34s&autoplay=1
2. Hit play if autoplay is not engaged
3. it seems to load forever, but won't play

### Describe the expected behavior

It should play!

### Additional information

* PeerTube instance:
  * URL: https://www.yiny.org/
  * Version: 6.1.0
  * NodeJS version: N/A (@JohnXLivingston ? ;))
  * Ffmpeg version: N/A

* Browser name, version and platforms on which you could reproduce the bug: Firefox 126/Ubuntu 22.04
Note : on Chrome, it tries to play, so we have blank for x seconds, but seems to realize it's not correct, and it issues another request for somehow the appropriate range.
* Link to browser console log if relevant: 
Video format "nerd stats" info:
Player mode
p2p-media-loader
P2P
activé
UUID de la vidéo
2084d57c-4966-4ede-8a29-154861234128
Fenêtre d’affichage / Cadres
1850x941*1.00 / 0 supprimées sur 0
Résolution
240p1
Volume
100
Codecs
avc1.640015 / mp4a.40.2

My guess is that it expects a different framerate when translating from timestamp to bytes, and doesn't get what it wants… But I didn't analyze the issue further. Of course, I could stream in 30 FPS, or maybe stream using pure audio, but those "videos" are now out in 240p/1 FPS… And seek / timestamped playback is broken.

**Comment by Chocobozzz** [comment]
Hi,

I think it's a firefox bug as it correctly works on chrome and I don't see issues in the m3u8 file PeerTube creates.

You can also test using directly hls.js on https://hlsjs.video-dev.org/demo/ with `https://www.yiny.org/static/streaming-playlists/hls/2084d57c-4966-4ede-8a29-154861234128/79859328-8cd1-4326-8185-b3365a7c8b1b-240.m3u8`

**Comment by gilou** [comment]
Yeah, same symptoms, works on Chrome (though it seems to hesitate at first), not on Firefox on hls.js demo. I have an "easy" workaround: not doing 1 FPS video (or doing audio only :wink: :wink:). I probably won't be able to chase the bug on Firefox :cry: anyway..

**Comment by gilou** [comment]
Ah, funny thing. It seems that before going to the studio (which I use to cut the beginning and end of the video), seeking works just fine... See https://www.yiny.org/w/isPXmWExKZFLieTdtGVwiM (I won't edit that one, in the name of science!)

**Comment by gilou** [comment]
Ah, funny thing. It seems that before going to the studio (which I use to cut the beginning and end of the video), seeking works just fine... See https://www.yiny.org/w/isPXmWExKZFLieTdtGVwiM (I won't edit that one, in the name of science!) that is the direct product of the live, and seeking works in Firefox there).

But if I simply re-upload the exact downloaded .mp4 file back (from Peertube), it has the seeking issue, see https://www.yiny.org/w/5N8QCNMyAsJUMr9GnN2iuP, the same happens if I use the studio to cut it through.

Well, I think there's a bug, but I think it's not worth investigating further… I'll just encode @ 24 FPS or something that makes players happy...

**Comment by gilou** [comment]
Ah, and to add to this, though again, I think it's over… If I re-encode the image/video part at 24 FPS, such as here: https://www.yiny.org/w/3eJ3QMVFrrKDiHAoZLK73w seeking works fine. And it doesn't use more disk in the end, so, whatever, let's not have weird framerates ;)
