### ISSUE TITLE
Turkish translation

### ISSUE THREAD

**Issue by KerimDemirkaynak** [Chocobozzz/PeerTube#6405]
### Describe the problem to be solved

Even though the Turkish translation is 100% available, why isn't it added?

**Comment by Chocobozzz** [comment]
Hello,

6.1 PeerTube version includes Turkish translation as stated in our blog post: https://joinpeertube.org/news/release-6.1

![Capture d’écran 2024-05-28 à 08 43 19](https://github.com/Chocobozzz/PeerTube/assets/5180488/c4d8434c-79f9-447c-bd1a-716cbfd14dda)
