### ISSUE TITLE
trying to restore sql db is failining

### ISSUE THREAD

**Issue by Medienzentrum-Landkreis-Harburg** [Chocobozzz/PeerTube#6406]
### Describe the problem

got a problem after upgrading from 6.0.4 to 6.1.0 and want to downgrade but the call is failing on:
OLD_VERSION="v6.0.4" && SQL_BACKUP_PATH="backup/sql-peertube_prod-20240517-1400.bak" && cd /var/www/peertube && sudo -u peertube unlink ./peertube-latest && sudo -u peertube ln -s "versions/peertube-$OLD_VERSION" peertube-latest && sudo -u postgres pg_restore -c -C -d postgres "$SQL_BACKUP_PATH" && sudo systemctl restart peertube
pg_restore: [archiver] unsupported version (1.14) in file header

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by Medienzentrum-Landkreis-Harburg** [comment]
Peertube version 6.0.4
NodeJs: v18.19.0
FFMPEG: ffmpeg version 5.1.4-0+deb12u1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
Redis : redis-server --version
Redis server v=7.0.15 
Postgresql: psql -V
psql (PostgreSQL) 15.6 (Debian 15.6-0+deb12u1)



ffmpeg version 5.1.4-0+deb12u1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)

**Comment by Chocobozzz** [comment]
Hello,

Please use the forum for sysadmin related questions: https://framacolibri.org/c/peertube

(https://stackoverflow.com/questions/59455783/pg-restore-archiver-unsupported-version-1-14-in-file-header may also help)
