### ISSUE TITLE
Error log on server: "Cannot read properties of undefined (reading 'isBlacklisted')"

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#6407]
### Describe the current behavior

Hello,

I got these errors on one of my server:

```
error[20/05/2024 10:57:54] Error in controller.

{
  "err": "TypeError: Cannot read properties of undefined (reading 'isBlacklisted')\n    at canVideoBeFederated (file:///var/www/peertube/versions/peertube-v6.1.0/dist/core/lib/activitypub/videos/federate.js:22:15)\n    at videoPlaylistRedundancyGetValidator (file:///var/www/peertube/versions/peertube-v6.1.0/dist/core/middlewares/validators/redundancy.js:61:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
}
```

Don't know exactly what it means.

### Steps to reproduce

1. Check error log on a production server

### Additional information

* PeerTube instance:
  * URL: https://www.yiny.org
  * Version: 6.1.0
  * NodeJS version: 18
  * Ffmpeg version:

**Comment by Chocobozzz** [comment]
Thanks! Fixed in https://github.com/Chocobozzz/PeerTube/commit/e2c354878fdef4f00a51f4ff3f4721aec6f7244e
