### ISSUE TITLE
Settings of type "password" triggers the browser password store

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#6408]
### Describe the current behavior

When a plugin has settings of type "password", and you save the plugin settings, the browser password store is triggered:

![image](https://github.com/Chocobozzz/PeerTube/assets/38844060/6614ea9b-9528-47e0-979e-206be9bd45ce)

### Steps to reproduce

1. Install a plugin with such settings (livechat for example)
2. Enter a password
3. Save the form

### Describe the expected behavior

The `<input type="password">` should have `autocomplete="off"` to prevent this behaviour.

### Additional information

* PeerTube instance:
  * Version:  6.1.0 (and previous)

**Comment by Chocobozzz** [comment]
Hi,

We should already use `autocomplete="off"`. Can you confirm?

**Comment by JohnXLivingston** [comment]
> Hi,
> 
> We should already use `autocomplete="off"`. Can you confirm?

Oh, right. The attribute is set.
So, why does Firefox want to save the password? Any idea?

Can you reproduce?
You can try with the livechat plugin, by enabling «open id connect», and using following testing options:

* url: `https://oidctest.wsweet.org/.well-known/openid-configuration`
* client id: `public`
* client secret: `tardis`

**Comment by Chocobozzz** [comment]
> So, why does Firefox want to save the password? Any idea?

See https://www.stefanjudis.com/snippets/turn-off-password-managers/

I think we should not try to find a workaround to prevent this behaviour web browser explicitly want

**Comment by JohnXLivingston** [comment]
> See https://www.stefanjudis.com/snippets/turn-off-password-managers/

Oh...

> I think we should not try to find a workaround to prevent this behaviour web browser explicitly want

I found this behaviour really annoying, as it keeps asking everytime i want to save settings.
But ok, i understand that this is a browser issue.
Thanks.
