### ISSUE TITLE
"Stats" button appears for remote video

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#6409]
### Describe the current behavior

As an admin, i have a "Stats" button under videos. But this button also appears for remote video:

![image](https://github.com/Chocobozzz/PeerTube/assets/38844060/80117a59-cd79-4a37-838c-75ab7792005f)

Of course, when clicking on it, i got some errors:

![image](https://github.com/Chocobozzz/PeerTube/assets/38844060/0364b8b9-6214-4b4b-b3bc-3fda077e18ba)

### Steps to reproduce

1. Connect as admin
2. Open a remote video
3. Open the action menu under the video.

### Describe the expected behavior

"Stats" action should not be available for remote videos.

### Additional information

* PeerTube instance:
  * Version: 6.1.0

**Comment by Chocobozzz** [comment]
Thanks! Fixed in https://github.com/Chocobozzz/PeerTube/commit/605f5328c1c3c4626ad6b17e2d5533103965cd19
