### ISSUE TITLE
Index plugins/themes on first startup, for better user experience for new admins.

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#6411]
### Describe the problem to be solved

It seems that when an instance is started for the first time, plugins and themes are not indexed before a few hours.
See for example here: https://framacolibri.org/t/theme-search-causes-message-plugin-index-is-not-available/16041

This could be difficult to understand for admins discovering Peertube for the first time.

### Describe the solution you would like

Peertube could index plugins and themes just after the first startup.

**Comment by Chocobozzz** [comment]
Hello,

PeerTube just proxy the request to the plugin index when you search themes/plugins. I think the plugin index was down at the moment or the instance is unable to contact it. Let's continue the discussion on the forum.
