### ISSUE TITLE
Error when updating version

### ISSUE THREAD

**Issue by zzoozzo1122** [Chocobozzz/PeerTube#642]
* **PeerTube version or URL:**PeerTube v1.0.0-beta.7
* **Browser name/version:** Chrome 66.0.3359.139
* **NodeJS version:** ver8 

* **What is the expected behaviour?**
* **What do you see instead?**

When I updated the program to the best version in the old version, there was one problem.

peertube-v1.0.0-beta.1 >>> PeerTube v1.0.0-beta.7

1st server (admin / config / edit-custom) Transcoding enabled
2nd Server Transcoding Disabled

If you update to the best version on the first server, the existing image will be visible.
When you update from the second server to the latest version,
Existing images are not output due to infinite loading.

How do I edit an existing video on server 2?
Do I need to upload a video again?

The video on server 2 had no problem with the previous version.
The video is also H264, mp4 file.

If you are sure of the problem, please fix it in the update.

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

**Comment by rigelk** [comment]
hello @zzoozzo1122 - early betas might have slight inconpatibility issues with later ones. wdyt @Chocobozzz ?

Overall the setting in which your problem occurs is not quite clear. Are you just uploading a new video? What do you mean by "best version"? Are you talking about thumbnails or video streaming when you talk about "Existing images are not output due to infinite loading" ?

Thanks for clearing that up, so that we can help :)

**Comment by Chocobozzz** [comment]
@zzoozzo1122 In addition, could you provide us the URL of your instance where the images are not loaded please? It would be easier to investigate

**Comment by zzoozzo1122** [comment]
test1
https://ts.oio.bz/videos/watch/b5b9e4a6-e77e-4d08-8845-32d1ff507274

test2
https://ts.oio.bz/videos/watch/b7efe55c-49c8-47ce-93c8-68dca610f358

The same image and test1 failed. test2 succeeded.

But it's the same image.
test1 - H264, mp4 image

test2 - H264, mp4 video, admin page - Enable transcoding options.

Update to PeerTube v1.0.0-beta.8 from PeerTube v1.0.0-beta.4

Other servers also have the same problem.

**Comment by Chocobozzz** [comment]
With beta 8, for different reasons, uploaded videos that are not encoded with the `faststart` flag won't work. We add this flag on transcoding, it's the reason why your first video do not work whereas the second does.

Use [create-transcoding-job](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#create-transcoding-jobjs) to create transcoding jobs for already uploaded videos.

Example with your video test1 with `peertube-latest` **beta 8**: 

```
$ cd /var/www/peertube/peertube-latest
$ sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run create-transcoding-job -- -v b7efe55c-49c8-47ce-93c8-68dca610f358
```

**Comment by zzoozzo1122** [comment]
I will ask you one more question.
When transcoding, if the file name contains special characters, is it not encoded?
For example , [  ] ( ) _ -  spacing

**Comment by Chocobozzz** [comment]
@zzoozzo1122 No, the video filename should not have impact on transcoding.
