### ISSUE TITLE
OAuth 2FA in Documentation

### ISSUE THREAD

**Issue by Schoumi** [Chocobozzz/PeerTube#6420]
### Describe the desired information/correction

Hi,

When user enable 2FA on his account and we try to connect to we get a 401 error code with body bellow. We get two links to the Documentation (see bellow). 

```json
{
"type":"https://docs.joinpeertube.org/api-rest-reference.html#section/Errors/missing_two_factor",
"detail":"Missing two factor header",
"status":401,
"docs":"https://docs.joinpeertube.org/api-rest-reference.html#operation/getOAuthToken",
"code":"missing_two_factor",
"error":"Missing two factor header"
}
```

The first link doesn't lead to an existing section. Errors missing_two_factor is not documented.
The second link leads to the oauth documentation but error 401 could be token expired or could be missing two factor header.

**Comment by Chocobozzz** [comment]
> The first link doesn't lead to an existing section. Errors missing_two_factor is not documented.

Discussed in https://github.com/Chocobozzz/PeerTube/issues/6421

> The second link leads to the oauth documentation but error 401 could be token expired or could be missing two factor header.

Thanks, fixed in https://github.com/Chocobozzz/PeerTube/commit/b3e39df59e113eb6636fc15d9b7531d794800bbb
