### ISSUE TITLE
The configuration file issue after upgraded to v6.0.4

### ISSUE THREAD

**Issue by r6fans** [Chocobozzz/PeerTube#6429]
### Describe the problem
I followed the release note and modify the `/config/production` file when upgrading from v5.0 to v6.0.4.
After that Peertube run normally.

The maintenance of AWS ECS on May 30th caused Peertube to restart, and Peertube reported errors after the restart.

* Peertube Error log
![image](https://github.com/Chocobozzz/PeerTube/assets/22339010/37adecce-378a-498a-9379-7a744cc85ebf)

From the error message , it can be seen that it was caused by the configuration file be overwritten by the default configuration. 

My question is, why didn't I get that error when I upgraded the image but only after restart?
According to the configuration file hierarchy, Peertube config change need to modify both `/config/default` and `/config/production` file, right?

### Additional information

* PeerTube instance URL:
* PeerTube version:  v6.0.4
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by Chocobozzz** [comment]
Hi,

I think you can remove `/app/default.yaml` and ensure you don't have a `webtorrent` string in `/app/production.yaml`
