### ISSUE TITLE
Static video link with proper extension in iframe

### ISSUE THREAD

**Issue by anmol26s** [Chocobozzz/PeerTube#643]
Hi
For proper embed of the video some network may require static link with video extension. ActivityStreams provide it currently but normal link don't. See here as the HubZilla developer points it out.
https://macgirvin.com/display/f0c095b75575ca33ba198110b947550a1c2dd3eb285968133140a905ba5769d1

**Comment by Chocobozzz** [comment]
We only want to provide an embed to the player, that uses P2P. Playing directly a video file would "break" one of the core concept of PeerTube...

**Comment by anmol26s** [comment]
But there is no restriction on direct playing of the videos.If someone plays video directly you can't stop him . I even  watch video directly sometimes, I don't know why but sometimes long videos works better on direct play.
Do you have plan to restrict direct video in future? 
Moreover as Mike mentioned in the comment the : 

> The peertube ActivityStreams feeds provide an mp4 alternative; but they don't seem to provide this link on the page and sort of force you to handcraft it unless you actually connect to peertube over ActivityPub; in which case we'll pick the correct link and embed it for you. 

This was discussed here too: 
https://hub.reticu.li/display/4ac1fdcb8db8bf15d9562b879c3deea7124c261ec4de49decbc553ea8404b336@hub.somaton.com
When direct video is provided in ActivityStreams, then why not for normal links too?
Mike has security concerns over iframe accessing the local cookies.

**Comment by Chocobozzz** [comment]
> Do you have plan to restrict direct video in future?

No, but we just don't want to "facilitate" direct playing. We provide a mp4 link in AP for different reasons, but again, we hope other platforms will use P2P instead of the direct link.

> Mike has security concerns over iframe accessing the local cookies.

I don't think an iframe of a different domain could access to local cookies. Twitter and Mastodon both use PeerTube player inside an iframe so I think it's fine. Of course if Mike or anyone else have some concerns, they are free to open an issue so we can discuss about them :)

**Comment by anmol26s** [comment]
Most of the people on HubZilla have migrated from Github to Framagit. I don't think it will be possible for them to reply here. 
But you can follow this thread : 
https://pod.datamol.org/display/36f05ab5c11ca598f306d4286f40eb1fd3a86659ac92174c72ebbf03b33fa30f
Or 
Create an discussion  issue there repo
https://framagit.org/hubzilla/core

**Comment by rigelk** [comment]
@anmol26s I opened https://framagit.org/hubzilla/core/issues/1224 to discuss the matter.

_note_: trusting remote code has always been difficult, and most existing mechanisms only deal with traditional client-server models where the server is trusted, not client-server where only parts of the code served by the server is trusted. Overall it's an interesting issue, but I don't know how realistic it is to want a perfect solution :thinking:

**Comment by Francewhoa** [comment]
Related ticket at https://framagit.org/hubzilla/core/issues/1224
