### ISSUE TITLE
Error while exporting user account(s).

### ISSUE THREAD

**Issue by mygitcrazy** [Chocobozzz/PeerTube#6431]
#### Description
We recently ran the export feature that is available in Peertube. We tried starting the export job a couple of times, but it keeps failing with the following error code in the Peertube instance itself:

#### Error in Peertube Instance:
Job: 7
Type: create-user-export
Processed on 25-5-24 21:16:25,192
Finished on 25-5-24 21:46:03,979

{
"userExportId": 7
}

Error: ENOENT: no such file or directory, stat '/app/data/storage/tmp_persistent/user-export-2-2024-05-25T19:16:25.187Z.zip'

#### Error in PostgreSQL Logs:
ERROR: value "18519529041" is out of range for type integer
<27>1 2024-06-01T13:41:40+02:00 cloudronserver postgresql 920 postgresql - 2024-06-01 11:41:40.171 UTC [2226] userdxxxxxxx4b34b2e2b12ab16a57eb@xxxxxxdbd6d0b666 CONTEXT: unnamed portal parameter $1 = '...'
<27>1 2024-06-01T13:41:40+02:00 cloudronserver postgresql 920 postgresql - 2024-06-01 11:41:40.171 UTC [2226] userdxxxxxxx4b34b2e2b12ab16a57eb@xxxxxxdbd6d0b666 STATEMENT: UPDATE "userExport" SET "size"=$1,"state"=$2,"error"=$3,"updatedAt"=$4 WHERE "id" = $5

### Steps to reproduce

1. Go to the export feature in Peertube.
2. Start an export job.
3. Observe the error after the job fails.

### Describe the expected behavior

The export job fails with the above error messages.

### Additional information

* PeerTube instance: 6.1.0
* Running on a Cloudron instance.

#### Possible Solution
I'm no database expert, but is this something that has to be done on the database that holds Peertube on Cloudron, Postgresql?
For example, to adjust the integer to the appropriate values of the database of Peertube?

Any thoughts or suggestions on how to resolve the issue would be highly appreciated.

Please let us know if you need any further information or logs.

Thank you!

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue. It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/e7ebcb16acbd43043fd7f95e8918b8ab50595796 :)

**Comment by mygitcrazy** [comment]
Thanks for the quick response and update 👌
