### ISSUE TITLE
Can't follow channels on multiple servers from Mastodon.

### ISSUE THREAD

**Issue by ozonedGH** [Chocobozzz/PeerTube#6435]
### Describe the current behavior

Right now I'm on Mastodon.social.  When I attempt to follow channels on numerous Peertubes I just get a follow request.  I don't run a Peertube myself, but I have a friend that does and I get the same thing.  Tilvids, maker space, share.tube, peertube.tv.  All of them just show follow request.  I can however follow framasoft@framatube.org.  

While this might be a config issue on the Peertube itself it seems like everyone with Peertube is experiencing this issue and this either isn't apparent to them or something else is going on.  I've spoken to Tilvids admin a year+ ago and they thought it was a bug in peertube.

I honestly don't know where to go with this, but I can probably get logs from my friend's server if it's needed.

Any suggestions are appreciated that I can give my friend in order to get the word out.  I really feel like this could be a blocker for the Fediverse to gain even more traction, including peertube as a viable alternative.

### Steps to reproduce

1. Be on a Mastodon instance, I've also tried my GoToSocial, and follow someone on Peertube (example here's my channel: @ozoned@video.thepolarbear.co.uk )
2. Follow goes to a follow request on the Mastodon end.  So it looks like I have to wait for the person whose channel it to approve the follow, but Peertube doesn't have a way to approve follows.

### Additional information

* PeerTube instance: Tilvids.com, share.tube, makertube.net, peertube.tv, video.thepolarbear.co.uk

* Browser name, version and platforms on which you could reproduce the bug: Firefox
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):  Gonna try to get this from friend.

**Comment by Chocobozzz** [comment]
Hi,

Thanks for your logs but unfortunately I would need the latest ones. These logs date back to May.

From what I see I can correctly follow `@ozoned@video.thepolarbear.co.uk` from `framapiaf.org` so I don't know what happens :thinking:

**Comment by ozonedGH** [comment]
Yeah, I'm wondering if there's somethign going on with older accounts that attempted to follow before that cancel and attempt to refollow.  I got the latest 2 logs from my friend. 

THank you so much for all of your help btw.  And thank you for all of the amazing work with peertube.  It's absolutely incredible and you're all helping build a more free internet.  

[peertube91.log](https://github.com/user-attachments/files/15805067/peertube91.log)
[peertube90.log](https://github.com/user-attachments/files/15805073/peertube90.log)

**Comment by ozonedGH** [comment]
I tried following my @ozoned@video.thepolarbear.co.uk from both my GTS, @ozoned@social.ozoned.net, as well as my older Mastodon account, @ozoned@mastodon.social, and still both go directly to a follow request instead of following.  Looking at the logs I don't see any errors with the Mastodon.Social, but I don't really know what I'm looking for there.  With GTS it's very Alpha so I honestly don't have much expectation that it works, but I know that others on mastodon.social can follow, so not sure why my old account can't.

Again, thank you so much for all of your time.

**Comment by Chocobozzz** [comment]
Can you go inside your peertube database and display the output of:

```sql
SELECT * FROM "actor" LEFT JOIN "account" ON "account"."actorId" = "actor"."id" LEFT join "videoChannel" ON "videoChannel"."actorId" = "actor".id  WHERE "url" = 'https://mastodon.social/users/ozoned'
```

**Comment by ozonedGH** [comment]
That posts the following:

id | type | preferredUsername | url | publicKey  
| privateKey | followersCount | followingCount | inboxUrl | outboxUrl  
| sharedInboxUrl | followersUrl | followingUrl | rem  
oteCreatedAt | serverId | createdAt | updatedAt | id | name | description | actorId | userId | applicatio  
nId | createdAt | updatedAt | id | name | description | support | actorId | accountId | createdAt | updatedAt  
--------+---------+-------------------+--------------------------------------+-------------------------------------------------------------  
-----+------------+----------------+----------------+--------------------------------------------+-----------------------------------------  
----+-------------------------------+------------------------------------------------+------------------------------------------------+----  
-------------+----------+----------------------------+----------------------------+----+------+-------------+---------+--------+-----------  
----+-----------+-----------+----+------+-------------+---------+---------+-----------+-----------+-----------  
342746 | Service | ozoned | https://mastodon.social/users/ozoned | -----BEGIN PUBLIC KEY----- +| | 188 | 413 | https://mastodon.social/users/ozoned/inbox | https://mastodon.social/users/ozoned/outbox | https://mastodon.social/inbox | https://mastodon.social/users/ozoned/followers | https://mastodon.social/users/ozoned/following | | 21 | 2024-06-12 12:32:45.809+00 | 2024-06-12 12:32:45.809+00 | | | | | | | | | | | | | | | |  
| | | | MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzDzGjp0K8nfD6iAUz5I0+| | | | | | | | | | | | | | | | | | | | | | | | | | | |  
| | | | yFDXoa0WBA3T8lrK9pk8UVnp+ge7kQtSnciTcspvjcgglYvAWm9akhBZBmbWn4b2+| | | | | | | | | | | | | | | | | | | | | | | | | | | |  
| | | | nimQTIeoDC2vBKcEARKOAO3fL08jnf/ikLLUg1EHFOtDkSpk+dm1okRgHpKVpYUY+| | | | | | | | | | | | | | | | | | | | | | | | | | | |  
| | | | ugkfITu/MnVEsQSXR6AKL9YMjoECJKJ4zCJ56kJ8v+6Rb7Pujh99yDhe3uPZQGaL+| | | | | | | | | | | | | | | | | | | | | | | | | | | |  
| | | | LA+mM0NqgP/nTOnPpnfXFt0TNqVRsPwI9DIEbBCmejcChpr0W5mriXVZlxN3fcF5+| | | | | | | | | | | | | | | | | | | | | | | | | | | |  
| | | | rHehYQWg1t4D+2+gjtr0psbIBlKB3XQaJcfildLdcdgiMuq7Px3zQV9rziLjz1BH+| | | | | | | | | | | | | | | | | | | | | | | | | | | |  
| | | | nQIDAQAB +| | | | | | | | | | | | | | | | | | | | | | | | | | | |  
| | | | -----END PUBLIC KEY----- +| | | | | | |

**Comment by Chocobozzz** [comment]
Thanks, I think I understand now. Your account on Mastodon is `Automated` and so using the `Service` type which is not supported by PeerTube. I'll see how PeerTube can handle this actor type but I'm surprised an `Automated` account manually follow other accounts :)

**Comment by ozonedGH** [comment]
I had no clue I had the "Automated" type set.  I'm asking my friends to check my GTS (GoToSocial) to see if it's sending the same thing and then I can talk to GTS how to change that.  Thank you very much for all of your help.  Very sorry for the confusion.

**Comment by Chocobozzz** [comment]
Supported in https://github.com/Chocobozzz/PeerTube/commit/346be1d4781d0a3cd3f25e166511af8dee3a03aa

Please test in 24 hours to follow an account/channel on https://peertube2.cpy.re/ to see it it's correctly fixed
