### ISSUE TITLE
Quality and speed menus are not shown in Persian language

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#6439]
### Describe the current behavior

Hi.
I am using PeerTube v6.1.0 with Persian (fa) language.
When I play a video, and click on the settings menu below the playback window, I am unable to change the speed and quality. Nothing is shown as in the below images:

![1](https://github.com/Chocobozzz/PeerTube/assets/91053236/862c393e-79f3-43f3-acb9-23bd0ada9ab6)

after clicking on quality menu:

![2](https://github.com/Chocobozzz/PeerTube/assets/91053236/569a7650-b47c-4406-af0c-197c221b7921)

after clicking on speed menu:

![3](https://github.com/Chocobozzz/PeerTube/assets/91053236/def3706a-e666-4960-8a5b-07b139279e75)

### Steps to reproduce

1. Set the language to Persian (Or maybe any other RTL language)
2. Play a video
3. Try to change quality or speed

### Additional information

* PeerTube instance:
  * URL:
  * Version: 6.1.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/c1fe77b99376ff3661fe3a2cf8d299f6cd9a1b85

**Comment by paymanzafar1** [comment]
Hi,
I changed the files accordingly, but there are errors during "yarn build" as below on @include lines:

Undefined mixin.
    ╷
58 │               @include right(0);
    │               ^^^^^^^^^^^^^^^^^^^
    ╵

Undefined mixin.
    ╷
148 │               @include left(15px);
    │               ^^^^^^^^^^^^^^^^^^^
    ╵

**Comment by Chocobozzz** [comment]
> I changed the files accordingly, but there are errors during "yarn build" as below on @include lines:

Please use the develop branch or nightly builds: https://builds.joinpeertube.org/nightly/

**Comment by paymanzafar1** [comment]
I have customized other parts of this software, so I must build my own code as before.

Is there any other changes to resolve these bug other than below files?

client/src/sass/custom-markup.scss
client/src/sass/player/settings-menu.scss

**Comment by paymanzafar1** [comment]
I found the related changes in \client\src\sass\include\_mixins.scss file.
Thank you.
