### ISSUE TITLE
Custom Plugin Field not transmit with hook 

### ISSUE THREAD

**Issue by Schoumi** [Chocobozzz/PeerTube#6441]
### Describe the current behavior

When the plugin register hook with `action:api.live-video.created` it seems that the live video parameters used during creation are not transmit to the plugin unlike `action:api.video.updated`. So create a live video with some plugin specific settings require multiple API call.

### Describe the expected behavior

Custom plugin fields should be transmited to the callback for each API Call who authorize them or should authorize them. API Documentation doesn't mention them for API Calls where they are allowed. Specify the field pluginData in them and explains format expected would be helpful.

### Additional information

You can see the issue here and the PR associated in the comment: https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/400#issuecomment-2160153744

Thank you

**Comment by Chocobozzz** [comment]
Hi,

`req` is sent to the hook so you can access body using `req.body` :)

**Comment by JohnXLivingston** [comment]
> Hi,
> 
> `req` is sent to the hook so you can access body using `req.body` :)

I need more cofee. Sorry 😂
