### ISSUE TITLE
UUID no longer visible for playlists

### ISSUE THREAD

**Issue by FediVideos** [Chocobozzz/PeerTube#6442]
### Describe the current behavior

The latest version of PeerTube (6.1.0) hides the long UUID for playlists, which causes problems when trying to create custom home pages. Without the long UUID, it is impossible to add playlists to the custom home page.

### Steps to reproduce

1. Create a playlist in 6.1.0
2. Observe that the UUID is no longer used or displayed in the URL or anywhere else when editing the playlist

### Describe the expected behavior

The UUID should be visible somewhere when editing your own playlist, either in the URL or as information on the editing page. This would allow adding playlists to the custom home page.

### Additional information

* PeerTube instance: fedi.video
  * URL: https://fedi.video
  * Version: 6.1.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Short UUID supported by playlist miniatures in https://github.com/Chocobozzz/PeerTube/commit/42c78c7fcc2ddebbeec42a09c95a3f72c4809721

**Comment by FediVideos** [comment]
Thanks for fixing so quickly! 🙏
