### ISSUE TITLE
Keyboard Shortcuts when enabled is ruining my custom input field

### ISSUE THREAD

**Issue by raazkarkee405** [Chocobozzz/PeerTube#6444]
### Describe the current behavior

I have a custom input field in a custom page. The input field is from the library [tagify](https://github.com/yairEO/tagify) and is handling the channel search in my custom page. 
The problem that arise is that when ever I enter `s` in the field my cursor moves to the global search page and `s` is not entered in the input field and same is the case when entering other shortcut keys like `g o`, `g t` , `m c`, etc. This is only happening in the custom input field that is added from the plugin. 

![image](https://github.com/Chocobozzz/PeerTube/assets/26194365/6082cde0-a5d5-469e-ba49-e165a292aea7)
![image](https://github.com/Chocobozzz/PeerTube/assets/26194365/a042c908-f63c-4850-95df-8d7cd00b337f)

### Steps to reproduce

1. Add any custom input field using plugin
2. Enable hotkeys for the Keyboard Shortcuts 
3. Click on the custom input field and make sure the cursor is in custom input field and click on the key defined on the keyboard shortcuts like `s`

### Describe the expected behavior

When the cursor is in any input field add previously by PeerTube, enabling hotkeys and pressing it adds the letter to the field and same should be the case for custom input fields.

**Comment by raazkarkee405** [comment]
hello @Chocobozzz, 
My PeerTube is inside a private network so you won't be able to access it.  I will try to provide you a sample plugin with custom input field so that you can reproduce in your environment.

**Comment by raazkarkee405** [comment]
Here is the link for the repo with custom input field.
https://github.com/raazkarkee405/peertube-plugin-custom-input

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/4aadf69a8b5fdc3147ef330c36dccf3406ca0085 (and https://github.com/Chocobozzz/PeerTube/commit/419da534af0d9411143d3d51645ff04af7fe6f5b)
