### ISSUE TITLE
Private videos and S3

### ISSUE THREAD

**Issue by Kitanit** [Chocobozzz/PeerTube#6448]
### Describe the current behavior

If the video is not public, it is not uploaded to S3 (or the UI does not display it "object storage") and also you can not download a transcoded video from the admin panel(screen).
![image](https://github.com/Chocobozzz/PeerTube/assets/65107731/4e333ef3-1e2a-4df8-8535-5be72dd7c5b4)

### Steps to reproduce

1) upload a video
2) set access restricted

### Additional information

docker PeerTube 6.1.0

**Comment by Chocobozzz** [comment]
Hello,

Please provide your instance URL so I can reproduce and also paste your server logs

**Comment by Kitanit** [comment]
> Hello,
> 
> Please provide your instance URL so I can reproduce and also paste your server logs

https://peertube.in.ua/

**Comment by Kitanit** [comment]
https://pastebin.com/MRN48urs

**Comment by Chocobozzz** [comment]
>  log 1 hour https://pastebin.com/MRN48urs

Thanks, can you upload a private video to see if there is an error in the logs? Admin "Local jobs" page may also help to see the error of `move-to-object-storage` job.

Can you also provide the value of `upload_acl`->`private` config? https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L193 (or if you use an env variable it's `PEERTUBE_OBJECT_STORAGE_UPLOAD_ACL_PRIVATE`

**Comment by Chocobozzz** [comment]
Fixed downloading private/protected videos from the admin by https://github.com/Chocobozzz/PeerTube/commit/79d6e93b03e23cac9760b71c1904a1f77a69e941
