### ISSUE TITLE
Plugin video field doesn't remember selected value

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#6453]
### Describe the current behavior

When using `registerVideoField` to create a video field, the form won't select the current value.

### Steps to reproduce

1. Install `peertube-plugin-premium-users`
2. Choose a video to edit and mark it as "Premium content"
3. Go back to the Update page, and then "Non-premium content" is selected.

### Additional information

* PeerTube instance:
  * URL:
  * Version: 6.1.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

Do you store and restore the value of the field in the storage manager? (see https://docs.joinpeertube.org/contribute/plugins#add-custom-fields-to-video-form)

**Comment by kontrollanten** [comment]
Ah, sorry. I didn't see that info.
