### ISSUE TITLE
Horizontal Scaling to distribute videos

### ISSUE THREAD

**Issue by MattyBoombalatty** [Chocobozzz/PeerTube#6456]
### Describe the problem to be solved

Is it possible to set up PeerTube to accept horizontal scaling/elasticity by using Digital Ocean or another API compatible provider to serve the data? We have a 10 GbE connection but at some point this will likely be exhausted. We could always ask users to set a higher P2P ratio in their live settings but that requires intervention from them unless we can make that the default.

I was thinking that PeerTube could support it since IP geolocation is already enabled for stats. This is something that I would contribute financially to the project for. 

### Describe the solution you would like

Discuss, research and develop solutions for scaling PeerTube instances in/out.

**Comment by Chocobozzz** [comment]
Hi,

Please see https://joinpeertube.org/faq#does-peertube-support-horizontal-scaling

So you can use:
 * S3 to distribute your videos (using a provider or building your own horizontally scaled architecture): https://docs.joinpeertube.org/maintain/remote-storage
 * PeerTube redundancy, where another PeerTube instance also serves your videos: https://docs.joinpeertube.org/admin/following-instances#instances-redundancy
