### ISSUE TITLE
Error loading video ()

### ISSUE THREAD

**Issue by raphaelbastide** [Chocobozzz/PeerTube#6457]
### Describe the current behavior

On a website I created, using Peertube embed API, the video that should autoplay on click *sometimes* does not play and the message `Sorry, the player is not compatible with your web browser. Please try latest Firefox versions.`.

### Steps to reproduce

1. Go to https://virusland.org/
2. Click on thumbnails, at least 10 times to open various videos, until you find the error. I feel it is kind of random, but I may be wrong.

### Describe the expected behavior

The videos should play all the time.

### Additional information

* PeerTube instance:
  * URL: https://peertube.swrs.net/
  * Version: 6.1.0
  * NodeJS version: I don’t know
  * Ffmpeg version: I don’t know

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Please try to lazy load the embeds (on click/mouseover for example) or increase rate limits: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L16

**Comment by raphaelbastide** [comment]
I increased the rate limit from 50 to 100, and made lazy load on mouseover, but I still have the following error on 1/10 `videos.play()` calls. 
    
    Uncaught (in promise) TypeError peertube-embed-api.js:1:9575

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/539dd6888dba9b95142ef4d5d4f129a5c5d27353

(as a side note you can also use https://docs.joinpeertube.org/api/embed-player#autoplay to autoplay the embed using the URL)
