### ISSUE TITLE
Large Videos Fail to Upload to Object Storage

### ISSUE THREAD

**Issue by MattyBoombalatty** [Chocobozzz/PeerTube#6458]
### Describe the current behavior

Large videos (>1 GB) fail to move to object storage. Error below. S3 provider is not behind CloudFlare or anything like that.

```
  "err": {
    "stack": "RangeError: data is too long\n    at Hash.update (node:internal/crypto/hash:119:22)\n    at _Hash.update (/var/www/peertube/versions/peertube-v6.1.0/node_modules/@smithy/hash-node/dist-cjs/index.js:37:15)\n    at getPayloadHash (/var/www/peertube/versions/peertube-v6.1.0/node_modules/@smithy/signature-v4/dist-cjs/index.js:171:14)\n    at _SignatureV4S3Express.signRequest (/var/www/peertube/versions/peertube-v6.1.0/node_modules/@smithy/signature-v4/dist-cjs/index.js:374:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "message": "data is too long",
    "code": "ERR_OUT_OF_RANGE",
    "$metadata": {
      "attempts": 1,
      "totalRetryDelay": 0
    }
```

### Describe the expected behavior

Videos should move to object storage.

### Additional information

* PeerTube instance:
  * URL:
  * Version: 6.1.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Have you checked this similar issue? https://github.com/Chocobozzz/PeerTube/issues/5525

**Comment by MattyBoombalatty** [comment]
Yes, decreasing the value seems to work. Thanks!
