### ISSUE TITLE
Error when deploying from docker (admin email is required)

### ISSUE THREAD

**Issue by MikaXII** [Chocobozzz/PeerTube#646]
Sorry I don't keep the error log but something like : `sequelize error : user.model cannot be null`.
I've get this error when I following your docker-compose.yaml : 
```
# /!\ Prefer to use the PeerTube admin interface to set the following configurations /!\
#PEERTUBE_ADMIN_EMAIL=admin@domain.tld
[...]
```
If the admin email is not set the container cannot be start. I add user email and that work again :)

**Comment by Chocobozzz** [comment]
Thanks!

Should be fixed: https://github.com/Chocobozzz/PeerTube/commit/e8d639b1d75b82f432713436c8168a9d8e107cb5
