### ISSUE TITLE
Upgrading from Peertube v1.2.1 possible?

### ISSUE THREAD

**Issue by codibby** [Chocobozzz/PeerTube#6460]
### Describe the problem

I am running Peertube v1.2.1 and I am trying to upgrade it to the latest version (following https://docs.joinpeertube.org/maintain/migration), but I failed multiple times. The instance has about 120 videos. Unfortunately I have no experience with PostgreSQL.

I wonder:
* Is it technically possible to upgrade from such an old version?
* Is it simpler to start from scratch and manually upload again each video? If so, is there a way to update the number of visualisations of each?
* Is there anyone who would be willing to do the upgrade for money (I can pay in Eur)?

Many thanks in advance for any help!

### Additional information

Versions on the **old** server:
* PeerTube version: 1.2.1
* NodeJS version: 8.15.1
* Ffmpeg version: 3.2.14-1
* Redis version: 3.2.6
* PostgreSQL version: 9.6.13

**Comment by Chocobozzz** [comment]
Hi,

Please use the forum for PeerTube sysadmin related questions: https://framacolibri.org/c/peertube (you can also ask there if someone can help you to upgrade your instance, ping @JohnXLivingston)

You should try to upgrade first to v2, then v3, v4, v5 and v6.1/v6.2. And apply "IMPORTANT NOTES" of each release.
It's possible to update video views by using a SQL query directly in the database.
