### ISSUE TITLE
After Studio Edit, a re-transcription of video does not occur

### ISSUE THREAD

**Issue by Mike35538** [Chocobozzz/PeerTube#6464]
### Describe the current behavior

I'm enjoying the new automatic transcription of videos feature in v6.2.0-rc.1, great work!

I noticed that uploading a new video causes it to generate a transcription but if you preform a Studio Edit of the video and trim off the beginning and end, it does not initiate a re-transcription of the video. So the old transcription is still there, which does not line up with the new video edition.

You can manually delete the transcription under Chapters and then in the Admin Videos list choose Generate caption, but shouldn't a re-transcription occur automatically when the video is changed in the Studio Edit?

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! Implemented in https://github.com/Chocobozzz/PeerTube/commit/e99e4aa93cd16b78e86b0f09886ed094c7d850fb
