### ISSUE TITLE
Plugin settings regression with 6.2.0-RC1: only one settings without name is possible

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#6466]
### Describe the current behavior

v6.2.0-RC1 comes with: "Add ability to register the same setting multiple times to replace the old one https://github.com/Chocobozzz/PeerTube/pull/6357 & [1bfb791e0](https://github.com/Chocobozzz/PeerTube/commit/1bfb791e0539df54d1d007683719dcb883870e1d)"

This feature introduce a regression with settings that have no name.

For example, in the livechat plugin, i have multiple "settings" without name. There are in fact placeholders for some html markup. Here is an example:

```javascript
 registerSetting({
    type: 'html',
    private: true,
    descriptionHTML: loc('important_note_title')
  })
  registerSetting({
    type: 'html',
    private: true,
    descriptionHTML: loc('important_note_text')
  })
  registerSetting({
    type: 'html',
    private: true,
    descriptionHTML: loc('diagnostic')
  })
```

With v6.2.0-RC1, these settings cancel each others, and only the last one remains.

### Steps to reproduce

1. use the livechat plugin
2. go the the plugin settings page
3. see that there are many missing labels. For example the "diagnostic" button is missing (check screenshots)

With v6.1.0:

![image](https://github.com/Chocobozzz/PeerTube/assets/38844060/f5cf1d96-3c4d-47c0-8f31-956a44a9b869)

With 6.2.0-RC1:

![image](https://github.com/Chocobozzz/PeerTube/assets/38844060/4b841a50-e286-4657-bc42-ef2527f7d5c8)

### Describe the expected behavior

Settings with no name should not cancel each others.

### Additional information

* PeerTube instance:
  * Version: v6.2.0-RC1

**Comment by Chocobozzz** [comment]
Thanks, fixed by https://github.com/Chocobozzz/PeerTube/commit/c5de5ef1d0d6e9fd8c8399ecc39bebd2ff244d48

**Comment by JohnXLivingston** [comment]
Do you plan another RC before the stable 6.2.0?

**Comment by Chocobozzz** [comment]
No it's not planned but I think you can try the nightly build as the develop branch is the same as release/6.2.0

**Comment by JohnXLivingston** [comment]
The question was not just about this issues. It was just to know. Thanks :)
