### ISSUE TITLE
Videos do not work on Opera (Linux)

### ISSUE THREAD

**Issue by catwell** [Chocobozzz/PeerTube#647]
* **PeerTube version or URL:**

https://peertube.cpy.re/videos/watch/f78a97f8-a142-4ce1-a5bd-154bf9386504

* **Browser name/version:**

Opera 53.0 on Arch Linux

* **What is the expected behaviour?**
* **What do you see instead?**

I get the error message:

> The media could not be loaded, either because the server or network failed or because the format is not supported.

* **Browser console log if useful (Gist/Pastebin...):**

> DOMException: play() failed because the user didn't interact with the document first.

> VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 

![screenshot from 2018-06-11 11-01-33](https://user-images.githubusercontent.com/221332/41222322-d9d2566c-6d66-11e8-9c47-d9aa4fbc32e7.png)

**Comment by Chocobozzz** [comment]
You need to install `opera-ffmpeg-codecs`  package

**Comment by catwell** [comment]
It works, thanks!

It's not obvious for the user though, maybe you can improve the error message or link to a page where it explains what to do?

**Comment by Chocobozzz** [comment]
This error can occur for different reasons, so it's difficult to be more explicit than "The media could not be loaded... **because the format is not supported**.
