### ISSUE TITLE
Automatic subtitles: mark them as automatically generated

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#6470]
### Describe the problem to be solved

When subtitles are generated with the new feature coming with v6.2.0-RC1, they should be marked as "automatically generated".

### Describe the solution you would like

For example, Youtube differentiates automatic subtitles and user added subtitles by adding the information in the subtitle name (see screenshot, in french):

![image](https://github.com/Chocobozzz/PeerTube/assets/38844060/c837eef6-8c08-47e0-9e00-a4e3a42f79bb)

For the record, there is also this suggestion that could be implemented:
https://ideas.joinpeertube.org/posts/230/allow-multiple-subtitles-for-the-same-language

**Comment by Chocobozzz** [comment]
Thanks for the suggestion! Implemented in https://github.com/Chocobozzz/PeerTube/commit/5d62c3c1cbec67fb7aab4365fa869339b811d16d
