### ISSUE TITLE
Offloading bandwidth from ISP

### ISSUE THREAD

**Issue by Twiub** [Chocobozzz/PeerTube#6473]
### Describe the problem to be solved

After testing peertube i realised it help offload bandwidth load from server through p2p. I believe we can as well offload bandwidth to isp as well. 

### Describe the solution you would like

How can we do that, by grouping users from same network and same isp together. Assuming in my house i have a router and we are watching same live stream only one user should get data outside the network and the rest we peer.
Going with the current setting yes user do share but randomly selected therefore advantaging server alone

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue but unfortunately it's out of the scope of PeerTube. We're currently happy with the P2P ratio (see [our blog post](https://joinpeertube.org/news/stress-test-2023)) and I think the feature should be implemented in the bittorrent tracker instead (https://github.com/webtorrent/bittorrent-tracker/issues/279)
