### ISSUE TITLE
Middle-click on «terms» opens an invalid page.

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#6474]
### Describe the current behavior

On the login page: https://www.yiny.org/login
If you middle-click on «terms», it goes on `https://www.yiny.org/client/en-US` which does not exist.

![image](https://github.com/Chocobozzz/PeerTube/assets/38844060/be56eba4-0bec-4f17-b96a-4ba9256d709c)

### Steps to reproduce

1. open  https://www.yiny.org/login
2. middle click on «terms»

### Describe the expected behavior

Should scroll down to the instance's terms, as the left click does.

### Additional information

* PeerTube instance:
  * Version: 6.1.0

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/60a424059d35e9f9d008a84b06b39d86161f3b6f
