### ISSUE TITLE
Configuration for max FPS

### ISSUE THREAD

**Issue by darkralts** [Chocobozzz/PeerTube#6475]
### Describe the problem to be solved

i want to upload 144fps videos, it seems to cap at 60fps.

i set up my own instance now, can i set in the config for 144fps? thank you :)

**Comment by MadMan247** [comment]
I agree with frame rate control; I want to control the frame rate on top of the resolution. This should be for all resolutions too. For example, I want 60fps on a 480p video. sometimes resolutions as low as 240p, for old T.V. broadcasts, need 60fps. Neither of these are currently doable. What about a Go-pro's 120fps video stream? Very desirable.

**Comment by darkralts** [comment]
i think 120fps is important too

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/bbaf96d60d4bc1a40bbc88584524c94c1c2b0b9f
