### ISSUE TITLE
"Error: Output format mp4 is not available"  causing transcoding failures

### ISSUE THREAD

**Issue by neunenak** [Chocobozzz/PeerTube#6476]
### Describe the current behavior

When I upload a video, the video always displays the "Transcoding failed" yellow warning text below the uploaded video. The peertube systemd service log has:

```
"stack": "Error: Output format mp4 is not available\n    at /usr/share/webapps/peertube/node_modules/fluent-ffmpeg/lib/capabilities.js:589:21\n    at nextTask
(/usr/share/webapps/peertube/node_modules/async/dist/async.js:5791:13)\n    at next (/usr/share/webapps/peertube/node_modules/async/dist/async.js:5799:13)\n    at /usr/share/webapps/peertube/node_modules/
async/dist/async.js:329:20\n    at proto.availableFormats.proto.getAvailableFormats (/usr/share/webapps/peertube/node_modules/fluent-ffmpeg/lib/capabilities.js:513:14)\n    at /usr/share/webapps/peertube/
node_modules/fluent-ffmpeg/lib/capabilities.js:568:14\n    at nextTask (/usr/share/webapps/peertube/node_modules/async/dist/async.js:5791:13)\n    at Object.waterfall (/usr/share/webapps/peertube/node_mod
ules/async/dist/async.js:5802:9)\n    at Object.awaitable [as waterfall] (/usr/share/webapps/peertube/node_modules/async/dist/async.js:212:32)\n    at proto._checkCapabilities (/usr/share/webapps/peertube
/node_modules/fluent-ffmpeg/lib/capabilities.js:565:11)\n    at /usr/share/webapps/peertube/node_modules/fluent-ffmpeg/lib/processor.js:298:14\n    at nextTask (/usr/share/webapps/peertube/node_modules/as
ync/dist/async.js:5791:13)\n    at Object.waterfall (/usr/share/webapps/peertube/node_modules/async/dist/async.js:5802:9)\n    at Object.awaitable [as waterfall] (/usr/share/webapps/peertube/node_modules/
async/dist/async.js:212:32)\n    at proto._prepare (/usr/share/webapps/peertube/node_modules/fluent-ffmpeg/lib/processor.js:295:11)\n    at proto.exec.proto.execute.proto.run (/usr/share/webapps/peertube/
```

I believe this is the same issue as described in https://github.com/Chocobozzz/PeerTube/issues/6426 . I'm on arch linux and can't easily downgrade the system ffmpeg package, which is version n7.0.1.

The fluent-ffmpeg project has an issue about this (https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/1262), and seems to have released a patch (https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/1266) as of their version 2.13. This is newer than the one peertube is using, so perhaps just bumping the fluent-ffmpeg version would be enough to fix this.

### Steps to reproduce

1. Attempt to upload a video
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version: 6.1.0
  * NodeJS version:
  * Ffmpeg version: n7.0.1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

Please try PeerTube 6.2 (currently in RC) that should fix your issue

**Comment by neunenak** [comment]
Looks like bumping to 6.2 fixed the issue!
