### ISSUE TITLE
Issue with dislikes

### ISSUE THREAD

**Issue by PhieF** [Chocobozzz/PeerTube#648]
* **PeerTube version or URL:** beta 8 (https://exode.me)
* **Browser name/version:** firefox 60
* **NodeJS version:**

* **What is the expected behaviour?**
should display number of dislikes when mouse hover

the pic talks better than I do 

https://framapic.org/gQSvhMezCx2s/dE6fasVrpLlW.png

**Comment by Chocobozzz** [comment]
:man_facepalming: 

Thanks, fixed: https://github.com/Chocobozzz/PeerTube/commit/86bed4a6aaf9819822b6d9f23397d37c580dff51
