### ISSUE TITLE
Time-stamped comments and annotations

### ISSUE THREAD

**Issue by Roboin161** [Chocobozzz/PeerTube#6483]
### Describe the problem to be solved

It would be nice for people to make time-stamped comments and annotations while watching a video.

### Describe the solution you would like

Add time-stamped comments and annotations that can then be exportsd as a text file later.
Maybe by letting a user log in to add these, or just by simply leaving their name.

This is a feature request, I accidentlaly filed it under issues and can't seem to change it.

**Comment by Roboin161** [comment]
Thanks! I think this is for when the uploader wants to make this. I was looking for watchers of the video to be able to do something similar.

**Comment by Chocobozzz** [comment]
Do you have an example of another platform that handle such use case?

**Comment by Roboin161** [comment]
Something similar to what Frame.io does:
https://www.youtube.com/watch?v=Z3yG2WADp0A

**Comment by Chocobozzz** [comment]
Nice, I didn't know this service/features.

Unfortunately it's currently out of the scope of PeerTube. But we can still implement a third party service similar to frame.io using the [PeerTube embed API](https://docs.joinpeertube.org/api/embed-player), where you can use PeerTube as a video backend and inject the player into this third party service.

As a side note, PeerTube supports timecodes in comments (but not interval or annotations).
