### ISSUE TITLE
Optimize the performance of /api/v1/videos/<videoid>/transcoding

### ISSUE THREAD

**Issue by fabiopicchi** [Chocobozzz/PeerTube#6484]
### Describe the problem to be solved

Currently, requests to transcode videos take a very long time because Peertube has to ffprobe the video in question to figure out what operations it has to do. This can increase significantly the response time if the web video is already in object storage.

### Describe the solution you would like

Figure out a way of reducing the processing time maybe by storing ffprobe metadata in the database when first interacting with the video or by streaming from object storage only the bytes ffprobe needs to read the metadata.

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/pull/6521

(we store file metadata in database now so we don't have to run ffprobe anymore)
