### ISSUE TITLE
Remote runner stuck after socket disconnect

### ISSUE THREAD

**Issue by fabiopicchi** [Chocobozzz/PeerTube#6485]
### Describe the current behavior

Under certain circumstances (possibly internet instability), the remote runner can lose connection to the server. After that, it never recovers. I am using version 0.0.18 of peertube-runner.

### Steps to reproduce

1. Start a remote runner
2. Leave it running for a while (maybe try to emulate it by disabling and enabling the internet connection)
3. Observe the failures

### Describe the expected behavior

The remote runner should simply reconnect and resume the work.

### Additional information

* PeerTube instance:
  * URL: https://play.cotv.org.br
  * Version: 6.1.0
  * NodeJS version: 22.3
  * Ffmpeg version: 6.1.1

Link to the runner logs:
https://pastebin.com/Z7RTFyJn

They are not complete and unfortunately I lost the original file :/

**Comment by fabiopicchi** [comment]
The issue seems to affect only macos

**Comment by Chocobozzz** [comment]
Hi,

Are you sure you're using peertube-runner 0.0.18? I don't see some logs that should be included in this version

**Comment by Chocobozzz** [comment]
Thanks, I can see the appropriate logs now. From what I read it seems the socket reconnected (line 4763) and a job is currently processed (even if the server may have sent it to another worker after the network failure)

**Comment by fabiopicchi** [comment]
I wonder if the problem is: if a runner has his queue full, loses connection and then reconnects, it can't report completion for any of its tasks anymore as they were assigned to other runners.

I think the problem only happens in the mac because it sleeps even if connected to power.

**Comment by fabiopicchi** [comment]
In this case it didn't even disconnect, but it got stuck in an error loop trying to send progress updates to the server.
https://drive.google.com/file/d/1BvbK-aJPoTXDP8zZtKYovo6PVeN1pVP0/view?usp=sharing

**Comment by Chocobozzz** [comment]
The runner should finish the task even if it cannot report progress. We can make the runner more robust (like failing the task more quickly when the progress update fails) but I have to admit that we don't except so many network request failures on runner side.

**Comment by Chocobozzz** [comment]
Hi @fabiopicchi 

Thanks I think I fixed the bug where the job is stuck in "Completing" state: https://github.com/Chocobozzz/PeerTube/commit/89e3951587595ccdde8f7e9e36506be0cae4cae7

**Comment by fabiopicchi** [comment]
Ahhh, that makes a lot of sense. Is it part of a hotfix that was already released?

Thanks a lot @Chocobozzz

**Comment by Chocobozzz** [comment]
(Fix of the fix: https://github.com/Chocobozzz/PeerTube/commit/18f13f43ec6f17df457d6cf61e5030179670949c)

> Ahhh, that makes a lot of sense. Is it part of a hotfix that was already released?

Not yet :)

**Comment by ROBERT-MCDOWELL** [comment]
btw where can we see in runners job if the tranSCRIPTING job?
