### ISSUE TITLE
Peertube 6.2.0 is speaking half french and half english

### ISSUE THREAD

**Issue by FredBezies** [Chocobozzz/PeerTube#6489]
### Describe the current behavior

Hello.

Since the upgrade to version 6.2.0 from 6.1.1, I noticed the UI is speaking half french and half english. This is weird. See attached screenshot.
![Capture d’écran du 2024-07-18 08-11-20](https://github.com/user-attachments/assets/bf059c06-1945-4bca-8be2-ce53138e3ca8)

### Steps to reproduce

1. Upgrade to version 6.2.0 from a previous one
2. Restart Peertube
3. Look at homepage

### Describe the expected behavior

Only one language used :)

### Additional information

* PeerTube instance: Ourtube
  * URL: https://peertube.pcservice46.fr/
  * Version: 6.2.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Any browser
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

You can translate remaining strings on weblate: https://weblate.framasoft.org/projects/peertube/angular/fr_FR/

See the documentation: https://docs.joinpeertube.org/support/doc/translation
