### ISSUE TITLE
Provide proxy config for youtube-dl

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#6494]
### Describe the current behavior

YT decided to block directly IP range of any crawlers like yt-dlp and apparently it can take days to months before the IP will be unblocked! this happening since june 10. Searching for a solution now the best is to have a random ipv6 range. VPN or Oauth may or may not work. I just hope we can find a way to avoid this stupid restriction. is anyone have a good solution please share it here thanks

### Steps to reproduce

just try manually yt-dlp from your server and will see if your IP is blocked or not

**Comment by Chocobozzz** [comment]
Hi,

I'm sorry but we can't do anything on PeerTube side. However I think we can provide at least a `proxy` option so it's easier for admins to use another IP with youtube-dl

**Comment by TaylorJadin** [comment]
Another workaround here may be to implement some way to use the [yt-dlp-youtube-oauth2 plugin](https://github.com/coletdjnz/yt-dlp-youtube-oauth2). I had success with this when using the `yt-dlp` cli directly, but I haven't come up with a good way to get peertube to tell yt-dlp to use those credentials when I start Imports from the web interface.

**Comment by TaylorJadin** [comment]
Or maybe some other way to pass API credentials to yt-dlp, I'm just less familiar with most of the alternatives.

**Comment by ParleurA** [comment]
> Hi,
> 
> I'm sorry but we can't do anything on PeerTube side. However I think we can provide at least a `proxy` option so it's easier for admins to use another IP with youtube-dl

I guess it can be doable to send cookies to yt-dlp to use credentials ?

**Comment by Chocobozzz** [comment]
Proxy support has been implemented in PeerTube 6.3: https://joinpeertube.org/news/release-6.3

**Comment by ashley-graves** [comment]
> Proxy support has been implemented in PeerTube 6.3: https://joinpeertube.org/news/release-6.3

Does this make it possible to use [yt-dlp-youtube-oauth2](https://github.com/coletdjnz/yt-dlp-youtube-oauth2)?
