### ISSUE TITLE
Import fails due to chapters being too long

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#6495]
### Describe the current behavior

When importing a video where the chapters are above 255 characters, it fails.

This is because the database restricts the title to a length of 255, and there is no cropping in the code.

### Steps to reproduce

I need to find minimal steps to reproduce. With this video, it appears that the issue happens:
https://youtu.be/M6ZU272Q0Vs?list=PLnaYq3EY7RdgujfJnrTkHOt50oJmiEnqJ

At least, it happens with video channel synchronization.

Here are the relevant logs: https://paste.yunohost.org/raw/tawilizaji

### Describe the expected behavior

The channel should be imported with the chapters (entirely or truncated to 255 characters)

### Additional information

* PeerTube instance:
  * URL: https://skeptikon.fr
  * Version: 6.2.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): https://paste.yunohost.org/raw/tawilizaji

**Comment by fflorent** [comment]
I can work on a fix, but I am asked a password when running `./scripts/clean/server/test.sh` (due to databases commands like `createdb` or `dropdb`), despite having set my user as superuser in postgresql.

I don't mind if anyone else take the issue otherwise. The most important is that we get a fix :)

**Comment by Chocobozzz** [comment]
> I can work on a fix, but I am asked a password when running ./scripts/clean/server/test.sh (due to databases commands like createdb or dropdb), despite having set my user as superuser in postgresql.

Can you try to `sudo -u postgres dropuser your_username && sudo -u postgres createuser you_username --createdb --superuser`?

**Comment by fflorent** [comment]
Already done. (`you_username` or `your_username` being my user in bash, right?)

I also inspected the result of the `\du` command, which shows me with Superuser role

**Comment by Chocobozzz** [comment]
Can you paste the `pg_hba.conf` configuration? (https://serverfault.com/a/406607 may help)

**Comment by Chocobozzz** [comment]
I fixed the chapter issue in https://github.com/Chocobozzz/PeerTube/commit/bba6538435a06b744b03233f138a06978cb9e45f

But don't hesitate to comment this issue so we can fix the dev problem :)

**Comment by Chocobozzz** [comment]
> Do you know when there will be a new release?

Hopefully this week
