### ISSUE TITLE
nodeinfo does not follow the standard, makes it seem like peertube is dying on fediverse observer and possibly other sites

### ISSUE THREAD

**Issue by wiki-me** [Chocobozzz/PeerTube#6496]
### Describe the current behavior

See the [issue](https://gitlab.com/diasporg/poduptime/-/issues/75) originally reported on fediverse observer.

It makes it seem like the project is dying (see [page](https://peertube.fediverse.observer/stats)) , i thought maybe there was some problem with the project and people are migrating to pixelfed or something like that. (there is something like a 80 percent drop in active users)

### Steps to reproduce

1. go to the nodeinfo of a peertube instance that has the latest version (e.g. [this](https://tube.kher.nl/.well-known/nodeinfo))
2. see that it does not follow [this](http://nodeinfo.diaspora.software/) spec

### Describe the expected behavior

follow the spec.

**Comment by Chocobozzz** [comment]
Hello,

Can you explain what's wrong with our nodeinfo implementation?

**Comment by DismalShadowX** [comment]
I'm also getting this. [Fediverse Observer](https://peertube.fediverse.observer/video.everythingbagel.me) reported my [server dead](https://video.everythingbagel.me/.well-known/nodeinfo), however [FediDB](https://fedidb.org/network/instance/video.everythingbagel.me) reported differently.

**Comment by Chocobozzz** [comment]
As explained in [my comment](https://gitlab.com/diasporg/poduptime/-/issues/75#note_2015417673) on fediverse observer repo, we just implemented [FEP-2677](https://codeberg.org/fediverse/fep/src/branch/main/fep/2677/fep-2677.md) that added a link to the nodeinfo endpoint. Fediverse observer should rely on the `rel` parameter to find the appropriate nodeinfo link. It seems a fix is has been pushed on their side: https://gitlab.com/diasporg/poduptime/-/commit/9d8165547181223b6571aa74fc9e0f7680631ada
