### ISSUE TITLE
Cannot start 6.2.0 service after upgrade: dependency error

### ISSUE THREAD

**Issue by toby3d** [Chocobozzz/PeerTube#6497]
### Describe the problem

Attempting to start the service after successful execution of the upgrade script results in the following dependency error:
```bash
Jul 22 15:34:11 vm155804.local systemd[1]: Started PeerTube daemon.
Jul 22 15:34:13 vm155804.local peertube[18952]: file:///var/www/peertube/versions/peertube-v6.2.0/node_modules/execa/lib/utils/max-listeners.js:1
Jul 22 15:34:13 vm155804.local peertube[18952]: import {addAbortListener} from 'node:events';
Jul 22 15:34:13 vm155804.local peertube[18952]:         ^^^^^^^^^^^^^^^^
Jul 22 15:34:13 vm155804.local peertube[18952]: SyntaxError: The requested module 'node:events' does not provide an export named 'addAbortListener'
Jul 22 15:34:13 vm155804.local peertube[18952]:     at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
Jul 22 15:34:13 vm155804.local peertube[18952]:     at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
Jul 22 15:34:13 vm155804.local peertube[18952]: Node.js v18.17.1
Jul 22 15:34:13 vm155804.local systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
Jul 22 15:34:13 vm155804.local systemd[1]: peertube.service: Failed with result 'exit-code'.
Jul 22 15:34:14 vm155804.local systemd[1]: peertube.service: Service RestartSec=100ms expired, scheduling restart.
Jul 22 15:34:14 vm155804.local systemd[1]: peertube.service: Scheduled restart job, restart counter is at 9.
Jul 22 15:34:14 vm155804.local systemd[1]: Stopped PeerTube daemon.
```

### Additional information

* PeerTube instance URL: https://video.toby3d.me/
* PeerTube version: 6.1.0 => 6.2.0
* NodeJS version: v18.17.1
* Ffmpeg version: 4.1.11-0+deb10u1
* Redis version: 5.0.14
* PostgreSQL version: 16.3

**Comment by Chocobozzz** [comment]
Hi,

Please try to upgrade to Node v18.18 (at least).

**Comment by own3mall** [comment]
Same issue!  Running node v20.10.0

**Comment by own3mall** [comment]
I upgrade node to v20.15.1, and then I had to create a symlink:

ln -s /usr/local/bin/node /usr/bin/node

So that the peertube service would use it.  Seems to have worked...

**Comment by toby3d** [comment]
> I upgrade node to v20.15.1, and then I had to create a symlink:
> ```bash
> ln -s /usr/local/bin/node /usr/bin/node
> ```
>
> Then re-run `yarn install`
> 
> So that the peertube service would use it. Seems to have worked...

I updated nodejs, recreated the link (for some reason the new version wasn't being used on it), executed `yarn install` and restarted the service. Everything seems to be working now.

**Comment by Chocobozzz** [comment]
As a side note, I suggest if you're on Debian to use our dependencies guide: https://docs.joinpeertube.org/support/doc/dependencies#debian-ubuntu-and-derivatives

In particular to use https://github.com/nodesource/distributions to install Node on your system
