### ISSUE TITLE
Remote runners and remote jobs view not shown when using runners only for transcription

### ISSUE THREAD

**Issue by lyn1337** [Chocobozzz/PeerTube#6499]
### Describe the current behavior

When use of remote runners is disabled, except for automatic transcriptions, the Administration/System/Remote Runner  and Remote Jobs view isn't shown and has to be accessed via the link in the configuration tab.

### Steps to reproduce

1.Disable remote runners for VODs and Lives, enable for for transcriptions
2.Check Administration/System tab
3.nuffin :(

### Describe the expected behavior

…

### Additional information

* PeerTube instance: rather not say
  * URL: —
  * Version: 6.2.0 release
  * NodeJS version: v18.19.0
  * Ffmpeg version: 4.4.4

* Browser name, version and platforms on which you could reproduce the bug: —
* Link to browser console log if relevant: —
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): —

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/44919a8d57697abc0cac97ee648503cd27656614

**Comment by lyn1337** [comment]
kweh!
