### ISSUE TITLE
RSS bad description for videos with account filter

### ISSUE THREAD

**Issue by PhieF** [Chocobozzz/PeerTube#650]
Hi

on peertube beta 8, when I display the atom xml of a specific user, I get the description of the whole instance instead of just the user : so my rss/atom client handle that badly when I add the subscription

for example here

https://exode.me/feeds/videos.atom?accountId=7

instead of 

```
<id>https://exode.me</id>
<title>Exode... a music instance</title>
<subtitle>This PeerTube instance focuses on music even though we won&apos;t refuse other kind of videos, but try not to abuse
</subtitle>
```

we should have

```
<id>https://exode.me</id>
<title>Username / channel name</title>
<subtitle>Description
</subtitle>

```

Am I making a mistake ?

Thanks ! :)

**Comment by Chocobozzz** [comment]
Should be better now: https://github.com/Chocobozzz/PeerTube/commit/749c7247ae9042a74d132afda0c7eefab66a0428

Since I'm not a RSS/Atom expert, don't hesitate to tell me if you notice other inconsistencies.
