### ISSUE TITLE
Video Playback not working after migrating to an new Server

### ISSUE THREAD

**Issue by Happyfeet01** [Chocobozzz/PeerTube#6503]
### Describe the problem

Hello,

I used the classic installation method. I installed all depends and sync the files from server A to B. 
I made an update to version 6.2.0. also updated the production.yml. 

It seems to work, but the local Video are not playable. I have only an circle at the black screen. 

Can anyone help? 

### Additional information

* PeerTube instance URL: https://tube.fulda.social
* PeerTube version: 6.2.0
* NodeJS version: v20.15.1
* Ffmpeg version: 4.4.2
* Redis version: Redis server v=6.0.16
* PostgreSQL version: 14.12

**Comment by Chocobozzz** [comment]
Hello,

You can try to check if the files are on your disk + if they have the appropriate linux owner/rights.

But please use the forum for PeerTube sysadmin related questions: https://framacolibri.org/c/peertube
