### ISSUE TITLE
Officially support the Category Management plugin

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#6505]
### Describe the problem to be solved

There is a Categories Management plugin for PeerTube at https://www.npmjs.com/package/peertube-plugin-categories
However, that plugin stopped working when PeerTube 6.0 was published, and the original author has not worked on it for a long time.

If you don't want to provide category management in the PeerTube core, could you make the above-mentioned category management plugin an officially-supported plugin?

Additionally, category support in the API is lacking. I opened a GitHub feature request a long time ago, but it was ignored. The comment about a supposed workaround does not take account of what was requested.

https://github.com/Chocobozzz/PeerTube/issues/6071

### Describe the solution you would like

Please could you officially support the Category Management plugin at https://www.npmjs.com/package/peertube-plugin-categories

**Comment by DalekDave** [comment]
You can see the broken state of this plugin at https://dalek.zone in the About page. I added new categories in addition to the standard PeerTube ones, but the plugin stopped working after PeerTube v6.0.

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/6504
