### ISSUE TITLE
PeerTube homepage markup / API has no peertube-category-list or peertube-category-embed or peertube-category-miniature functions

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#6506]
### Describe the problem to be solved

In PeerTube's page markup tags/API function calls, you can insert a playlist and channel embed and miniature into home page markup, but there is no equivalent functionality for categories.

See the PeerTube documentation at https://docs.joinpeertube.org/api/custom-client-markup#peertube-playlist-embed

The result is that although you can pull content from one user's playlists and channels into your instance's home page, you cannot pull content from a category into your home page and display content from all your instance's community posted in a specific category or a specific list of categories.

So that makes it difficult to make my PeerTube instance at https://dalek.zone really community-oriented.

I already posted a feature request about this at https://github.com/Chocobozzz/PeerTube/issues/6071 but it got closed.

### Describe the solution you would like

The PeerTube home page markup tags / API needs peertube-category-list and peertube-category-embed and peertube-category-miniature functions, so that new content from the instance's community can be automatically shown on the instance's home page.

You previously commented in XXXXX that: "You can use peertube-videos-list  with data-category-one-of attribute no? https://docs.joinpeertube.org/api/custom-client-markup#peertube-videos-list"

The answer is no, using peertube-videos-list with data-category-one-of attribute does not fulfill the need I described originally in https://github.com/Chocobozzz/PeerTube/issues/6071

**Comment by Chocobozzz** [comment]
Please don't open duplicate issues, I'll reopen the other one.
