### ISSUE TITLE
PeerTube project can acquire domain name peertube.zone

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#6507]
### Describe the problem to be solved

This is not actually a feature request but at least you'll see the offer.

I currently have registered the domain name 'peertube.zone'.

I am willing to transfer it to the PeerTube project at no cost. Interested?

**Comment by Chocobozzz** [comment]
Hi & thanks for the proposal. Unfortunately we can't pay "exotic" TLD like `.zone` for PeerTube. We would be more interested in classic TLDs like `.fr`, `.com` etc. :)
