### ISSUE TITLE
Add a page for video category, similar to a user's channel page 

### ISSUE THREAD

**Issue by DalekDave** [Chocobozzz/PeerTube#6508]
### Describe the problem to be solved

PeerTube is able to display a user's channel (listing videos and playlists of the user's videos).

But there is not a dedicated page that contains all videos in a known category on the instance.  

### Describe the solution you would like

PeerTube should be able to display a page listing all videos in a known category on the instance.
Optionally, PeerTube could allow you to display all federated videos in a known category.

If this feature were implemented, it would also be very useful to be able to link to that page in the home page markup.

**Comment by DalekDave** [comment]
In the home page markup on https://dalek.zone, I can use the API function peertube-videos-list to show a selection of videos from a category. But I can't link to any page showing all the videos in that category known about by the instance. So, if I list 50 videos of a category, the ones beyond 50  "fall off the end" and can only be seen in the owning user's channel page.

I want to list 50 videos (for example), but I also want to be able to link to a page that shows all the videos in that category known about by the instance.

**Comment by Chocobozzz** [comment]
Hi,

There is the "Search page" that can filter on categories: https://peertube2.cpy.re/search?categoryOneOf=7

It's also possible to filter videos by categories: https://peertube2.cpy.re/videos/recently-added?categoryOneOf=14&categoryOneOf=16

**Comment by DalekDave** [comment]
Hmmmmm... I will play with that in the home page markup on [Dalek Zone](https://dalek.zone) and write back in this issue over the weekend.

Thanks for the idea.

But links in PeerTube's home page markup behave rother wierdly (that's another subject, for a different issue report).

**Comment by Chocobozzz** [comment]
> But links in PeerTube's home page markup behave rother wierdly (that's another subject, for a different issue report).

Yes please create a dedicated issue.

I'm closing this one then!

**Comment by DalekDave** [comment]
Please can you leave it open a few days longer? I have not had time to test yet!
