### ISSUE TITLE
Add compatibility with the piped and invidious API so that we can use existing apps

### ISSUE THREAD

**Issue by Darin755** [Chocobozzz/PeerTube#6509]
### Describe the problem to be solved

Currently Peertube is lacking in terms of apps. There are mobile applications but they tend to be less maintained and are lacking the features of bigger projects. Right now Peertube works best in the browser.

### Describe the solution you would like

If possible it might make sense to implement the piped or invidious api on the server. This would allow clients such as Libretube and Freetube to be able to coonnect to a peertube server just like it was a Youtube frontend. This would mean that people could simply use existing applications to access peertube instances instead of trying to use either a web page or a less maintained Peertube client. I realize this would take some development effort but I think it would better than trying to create dedicated Peertube apps.

**Comment by Booteille** [comment]
Hi!

I don't get it.
What is actually missing in PT API forbidding people to create web apps?

What Invidious or Piped API brings that PT should add to their API?

**Comment by Darin755** [comment]
> Hi!
> 
> I don't get it. What is actually missing in PT API forbidding people to create web apps?
> 
> What Invidious or Piped API brings that PT should add to their API?

So my idea is that Peertube could implement the exact same APU as either Piped or Invidious. This would allow existing clients to work with Peertube.

**Comment by Chocobozzz** [comment]
Hi & thanks for the issue.

Unfortunately we don't have enough resources to create another API that would be compatible with these clients.

As a side note we're developing a mobile application that should be released at the end of the year. More info on our blog post: https://joinpeertube.org/news/peertube-future-2024 ;)
