### ISSUE TITLE
Auto-rotate not respecting PWA

### ISSUE THREAD

**Issue by DismalShadowX** [Chocobozzz/PeerTube#6510]
### Describe the current behavior

Auto-rotate not respecting PWA install.

Does not rotate if using web browsers on mobiles

Affects especially Android. iOS does not support PWA as it uses different mechanism (Add to Home Screen) in Safari which is not native PWA.

### Steps to reproduce

1. Auto-rotate toggle disabled on mobile
2. Install Peertube install as PWA
3. Put mobile in landscape position
4. Peertube instances would auto-rotate regardless disabled

### Describe the expected behavior

Respect the auto-rotate specifically PWA.

### Additional information

* PeerTube instance:
  * URL: https://video.everythingbagel.me
  * Version: 6.2.0
  * NodeJS version: 20.15.1
  * Ffmpeg version:  6.1.1-3ubuntu5 Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 13 (Ubuntu 13.2.0-23ubuntu3)

* Browser name, version and platforms on which you could reproduce the bug:
  * Android 14
  * Chrome 126.0.6478.186
  * Pixel 7 Pro

**Comment by Chocobozzz** [comment]
Thanks for the issue! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/65aa1c257134769163e5e5a2e3eea554bcff8541 & https://github.com/Chocobozzz/PeerTube/commit/06fbcde34ee68d1a116a355039b9b7033704e2a1 (`default` seems to respect OS settings)
