### ISSUE TITLE
Node version requirement unsatisfiable on FreeBSD aarch64

### ISSUE THREAD

**Issue by src386** [Chocobozzz/PeerTube#6513]
### Describe the problem

The following command:
```
yarn install --production --pure-lockfile
```
Eventually results in:
```
error @angular-devkit/build-angular@18.0.6: The engine "node" is incompatible with this module. Expected version "^18.19.1 || ^20.11.1 || >=22.0.0". Got "21.7.3"
error Found incompatible module.
```

Right now (Jul 2024) FreeBSD aarch64 provides:
```
node-20.12.2_1                 V8 JavaScript for client and server (meta port)
node18-18.20.2                 V8 JavaScript for client and server
node20-20.12.2                 V8 JavaScript for client and server
node21-21.7.3                  V8 JavaScript for client and server
```

node22 may be available in a few weeks/month, but right now it is impossible to install peertube.
Is it possible somehow to "loosen" the node version requirement?

### Additional information

* PeerTube version: 6.2
* NodeJS version: 21.7.3
* Ffmpeg version: 6.1
* Redis version: 7.2.4
* PostgreSQL version: 16.2
* Operating system: FreeBSD 14.1-RELEASE

**Comment by Chocobozzz** [comment]
I sugges to use node 18 or node 20 (LTS versions). I'll update the documentation

`NOCLIENT=1 yarn install --production --pure-lockfile` may also fix your issue.

**Comment by Chocobozzz** [comment]
`node18-18.20.2` satisfies `^18.19.1`

> What is the purpose of NOCLIENT=1?

Skip checking client dependencies, which are not installed anyway because of `--production` option

**Comment by Chocobozzz** [comment]
Doc fixed by https://github.com/Chocobozzz/PeerTube/commit/5084a8fe71d532e4daa4038e7fa49fc24402bf91
