### ISSUE TITLE
Automatic emoji replacement in video description not shown in preview

### ISSUE THREAD

**Issue by JacksonChen666** [Chocobozzz/PeerTube#6517]
### Describe the current behavior

The video at https://videos.jacksonchen666.com/w/22x8rqrkhqLULFPH9D6Wnp has the description which looks like this:

> (there's a tiny cut at 1:47 but who cares (i accidentally quit minecraft 😛))

![The description of the video, showing an emoji in the sentence "(there's a tiny cut at 1:47 but who cares (i accidentally quit minecraft 😛))"](https://github.com/user-attachments/assets/ba659952-e993-4615-bff1-e365fc478508)

---

While the source markdown looks like this:
```
(there's a tiny cut at 1:47 but who cares (i accidentally quit minecraft :P))
```

And the preview looks like this:
> (there's a tiny cut at [1:47](https://videos.jacksonchen666.com/w/22x8rqrkhqLULFPH9D6Wnp?start=1m47s) but who cares (i accidentally quit minecraft :P))

![Video update page, description section. The raw text form has ":P" while the preview also has ":P" instead of an emoji.](https://github.com/user-attachments/assets/0d514b7e-a1f1-4f15-b8cf-c8c7b21003c3)

### Steps to reproduce

1. Type `:P` in video description
2. See ":P" in truncated/complete preview of the video description
3. Save the video
4. See that the ":P" has been replaced with "😛", which isn't shown in the preview of the video description

### Describe the expected behavior

If the source markdown looks like this:
```
(there's a tiny cut at 1:47 but who cares (i accidentally quit minecraft :P))
```

Then preview should look like this because of the automatic emoji replacement:
> (there's a tiny cut at [1:47](https://videos.jacksonchen666.com/w/22x8rqrkhqLULFPH9D6Wnp?start=1m47s) but who cares (i accidentally quit minecraft 😛))

![Video update page, description section. The page has been edited](https://github.com/user-attachments/assets/4f5a5ea9-c1e6-4117-a889-6440cfd5eb3c)

(The screenshot above was made after messing around with devtools to put the emojis there. So I don't actually have the code to fix this issue)

(Also, I personally would rather not have PeerTube automatically replace my ASCII emoticons with emojis, and making PeerTube not do that doesn't seem possible from an attempt at using backslashes)

### Additional information

* PeerTube instance:
  * URL: https://videos.jacksonchen666.com/w/22x8rqrkhqLULFPH9D6Wnp
  * Version: 6.2.0
  * NodeJS version: v20.12.2
  * Ffmpeg version: 6.1.1

* Browser name, version and platforms on which you could reproduce the bug: LibreWolf 128.0.3-1 (Firefox fork), macOS 14.5
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/40a498790ed5d66be665fa755f289e626bcac388
