### ISSUE TITLE
PeerTube version 6.2.0 does not run on Linux glibc < 2.25 version OS - solved!

### ISSUE THREAD

**Issue by M-Stenzel** [Chocobozzz/PeerTube#6518]
### Describe the current behavior

Upgrading to version 6.2.0 of the software makes peertube fail.

### Steps to reproduce

1. Run Linux OS with glibc < 2.25
2. Upgrade to version 6.2.0 of the software
3. Peertube startup fails.

### Describe the expected behavior

Peertube depends on the node-datachannel binary ([https://github.com/murat-dogan/node-datachannel](https://github.com/murat-dogan/node-datachannel)). Latest version of peertube (6.2.0) ships with a binary that depends on glibc >= 2.25. 
To solve the problem you have to compile the binary  yourself!

Find additional information in your installation in here:

/var/www/peertube/versions/peertube-v6.2.0/node_modules/node-datachannel/BULDING.md

But you have to run

"npm i --build-from-source"

otherwise a non-functioning binary will be downloaded, this will not help.

Hope this helps persons which distro ships with older versions of glibc.

Martin.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/6486
