### ISSUE TITLE
Add file size / video length / bitrate limits

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#652]
At the moment, Peertube does not seem to implement any limits on uploaded videos. That means it would be possible to upload any of the following:

- a video with a bitrate 100 Mbps from [here](http://www.jell.yfish.us/)
- a video with a duration of 5 hours or more
- a video with more than 5 GB in size

Unfortunately I don't have a good internet connection right now, so I can't check this myself. 

I suggest that you add some configuration options for admins. Personally, I would prefer to host many small videos, than filling up the server with a few large movies that no one watches.

Edit: other than storage, such large videos also take forever to transcode.

Edit2: Someone just uploaded like 10 GB of videos to my server in one day, and the server was busy with transcoding for the past 4 days (which means other people's videos couldn't be transcoded). For such cases, it would be nice to have a limit like "upload at most 1 GB per day".

**Comment by Nutomic** [comment]
Just saw this comment in the nginx config: "PeerTube does not support videos > 4GB". So this is not as bad as I thought. Still, the size is higher than I would like. I've set `client_max_body_size` to 1G for now as a workaround, but I don't know if that gives a nice error message to the user.

**Comment by Chocobozzz** [comment]
Hello!

> a video with a bitrate 100 Mbps from here
Covered by https://github.com/Chocobozzz/PeerTube/issues/638

> a video with a duration of 5 hours or more
I don't think you really care about the duration of the video

> a video with more than 5 GB in size
:+1: 

> . I've set client_max_body_size to 1G for now as a workaround, but I don't know if that gives a nice error message to the user.

Unfortunately no, because the 4GB limit is hardcoded in the client. We need to improve it!

**Comment by usbsnowcrash** [comment]
I would love to see max video length / size etc specified with a .env variable

**Comment by Nutomic** [comment]
Somewhat relevant, this video manages to be 1.3 GB in size, even though uploads are limited to 750 MB in nginx. So either the video grew during encoding, or they went around the upload limit.

https://peertube.social/videos/watch/d5da8051-af89-4653-9c68-0f43179e069b

**Comment by scanlime** [comment]
Not sure if this should be a new issue, a comment here, or a message to some forum, apologies if I guessed wrong:

Related to the video limit, what's the reason behind the 8GB upload limit? Is it a memory/storage cap, or is there a reason related to future federation or backup mechanisms?

(I've already been transcoding a few videos before upload to squeeze them into 8GB, and I have a bunch more I'd like to avoid :)

**Comment by Chocobozzz** [comment]
We need an hard limit when uploading files, and I decided it was 8GB with no particular reason :)

This issue is about adding a configuration key so this limit could be changed by the admin.

**Comment by Chocobozzz** [comment]
Go for it! :+1:

**Comment by Nutomic** [comment]
Not my issue really, ping @usbsnowcrash @scanlime.
