### ISSUE TITLE
Random videos imported by URL can't have metadata updated

### ISSUE THREAD

**Issue by TangentFoxy** [Chocobozzz/PeerTube#6520]
### Describe the current behavior

Some videos, when imported by URL, cannot be updated, with no indication of what's wrong. These videos otherwise load and play fine.

![image](https://github.com/user-attachments/assets/f2ada368-78e4-41df-9a14-46a5ec94b0cd)

### Steps to reproduce

1. Import a video via URL (an example affected video is https://www.youtube.com/watch?v=sSoNk89MzvU )
2. Change any details about the video.
3. Update button is greyed out and can't be clicked. Exiting and coming back never changes this.

### Describe the expected behavior

Updating metadata should work for all videos.

### Additional information

* PeerTube instance:
  * URL: https://peertube.tangentfox.com/
  * Version: 6.2.0
  * NodeJS version: ? (whatever is included in Docker image chocobozzz/peertube:production-bookworm)
  * Ffmpeg version: ? (whatever is included in Docker image chocobozzz/peertube:production-bookworm)

* Browser name, version and platforms on which you could reproduce the bug: Firefox 127.0.2 64-bit on Windows 10 22H2
* Link to browser console log if relevant: N/A
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): N/A

**Comment by Chocobozzz** [comment]
Hi & thanks for the issue. It's the same issue as https://github.com/Chocobozzz/PeerTube/issues/6495

Try to truncate chapter 19 to fix your issue with this particular video
