### ISSUE TITLE
Synchronization from YouTube fails

### ISSUE THREAD

**Issue by cedric-famibelle-pronzola** [Chocobozzz/PeerTube#6522]
### Describe the current behavior

I have channels synchronized to YouTube channels.
I noticed that the synchronizations were not done.
So I deleted and added the synchronization again by monitoring with the command `sudo journalctl -fu peertube`.
Here's the error: 
- `“stderr”: “ERROR: [youtube] PCJqXuxb6EU: Sign in to confirm you're not a bot. This helps protect our community. Learn more"` 
(`PCJqXuxb6EU` is a video that's not synchronized.)

The task is not in error in the webadmin but there is no import.

### Steps to reproduce

1. In PeerTube instance server : `sudo journalctl -fu peertube`
2. In the PeerTube instance webpage : synchronize a YouTube channel

### Additional information

* PeerTube instance: GADE
  * URL: https://gade.o-k-i.net
  * Version: 6.2.0
  * NodeJS version: v18.19.0
  * Ffmpeg version: 5.1.5-0+deb12u1

* Browser name, version and platforms on which you could reproduce the bug: Mozilla Firefox 128.0.2

**Comment by ROBERT-MCDOWELL** [comment]
the issue comes from YT, blocking IP range using download crawlers... the problem is after this block even when you import from one YT link in publish section it will fail too.

**Comment by Mike35538** [comment]
I've been getting the same YT import error since upgrading to 6.2.0. Not sure if PT 6.2.0 upgraded yt-dlp or not but seems that yt-dlp has a bug related to this issue https://github.com/yt-dlp/yt-dlp/issues/10128

**Comment by Chocobozzz** [comment]
Hi,

PeerTube can't do anything here, it's a yt-dlp issue. PeerTube upgrades yt-dlp regularly to get the latest version (provided [in the config](https://github.com/Chocobozzz/PeerTube/blob/develop/config/default.yaml#L774))

**Comment by ROBERT-MCDOWELL** [comment]
@Mike35538 
it's even not yt-dlp, it's YT itself who changed their surveillance system since June 7th, you should go to yt-dlp a bunch of issues are opened because of that. Many platform are suffering from this new stupid rule, like discord and all apps of music grabbing music channel on YT.

**Comment by cedric-famibelle-pronzola** [comment]
> the issue comes from YT, blocking IP range using download crawlers... the problem is after this block even when you import from one YT link in publish section it will fail too.

Yes, it seems to come directly from YouTube 😬
Is there a way around it?

**Comment by ROBERT-MCDOWELL** [comment]
@cedric-famibelle-pronzola 
well, if there is a way today YT will realize quickly that it needs to fix it. Their firewal network A.I. is aware of that.

**Comment by cedric-famibelle-pronzola** [comment]
@ROBERT-MCDOWELL 
OK, well, the only solution I can think of at the moment is to download locally via yt-dlp and then upload the file 😅

**Comment by ROBERT-MCDOWELL** [comment]
@cedric-famibelle-pronzola 
even not, as long as you start to download more than one video (I guess because I tested already) they block your IP, local or not, Worse, they can even block your IP and its range! so imagine at the airport someon is using a YT download crawler, then the whole airport will be blocked.

**Comment by ParleurA** [comment]
It's possible to use yt-dlp with your browser cookies if you have a Youtube account connected.

One way to solve the problem would be to be able to import those cookies into Peertube ?

**Comment by MarkWieczorek** [comment]
How to you configure Peertube to use an HTTP proxy? I couldn't find any documentation about this.

**Comment by ROBERT-MCDOWELL** [comment]
you mean reverse proxy? use proxy-balancer.conf from apache and use https://gist.github.com/ROBERT-MCDOWELL/a12abc31b9e188f48ffbda31f457c0ba

**Comment by MarkWieczorek** [comment]
> you mean reverse proxy?

No. I have a working instance of Peertube using a reverse Proxy. If I understand @Chocobozzz point, I think that they were referring to this in the documentation: 

> With ActivityPub federation and import features, PeerTube does many HTTP requests to the external world. To prevent private network/URL access, we encourage to use a HTTP proxy using HTTP_PROXY and HTTPS_PROXY environment variables.

By using something like a SOCKS proxy, you could get around any IP bans that Youtube might have.

**Comment by Barikad** [comment]
# Complete Guide: YouTube Anti-Bot Bypass on PeerTube

This procedure resolves the `Sign in to confirm you're not a bot` error by forcing the use of session cookies via a Python wrapper.

## 1. Diagnosis: Identify the Block

Before starting, confirm that YouTube is indeed blocking your server:

```
journalctl -u peertube -f | grep -i "Sign in to confirm you're not a bot"
```

*If lines appear, your IP address is marked as a "bot" by Google.*

## 2. Installation / Update of `yt-dlp`

It is crucial to have a very recent version of the download engine.

```
# Navigate to the PeerTube binaries folder
cd /var/www/peertube/storage/bin/

# Download the latest official version
wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O yt-dlp.real

# Apply permissions
chmod +x yt-dlp.real
chown peertube:peertube yt-dlp.real
```

## 3. Preparation of YouTube Cookies

Cookies allow the server to simulate a human connection.

1. On your browser (Chrome/Firefox), install the extension **"Get cookies.txt LOCALLY"**.
2. Log in to YouTube.
3. Use the extension to export the cookies from `youtube.com` in **Netscape** format.
4. On the server, create the file:

```
nano /var/www/peertube/storage/youtube-cookies.txt
# [Paste the cookie content here]
# Save: Ctrl+O, Enter, then Ctrl+X

# Secure the file
chown peertube:peertube /var/www/peertube/storage/youtube-cookies.txt
chmod 600 /var/www/peertube/storage/youtube-cookies.txt
```

## 4. Setting Up the Python Wrapper

This script will intercept PeerTube requests to silently add the `--cookies` option.

```
cd /var/www/peertube/storage/bin/
nano yt-dlp
```

**Copy-paste this exact code:**

```
#!/usr/bin/env python3
import sys
import os

# Paths to the real binary and cookies
real_binary = "/var/www/peertube/storage/bin/yt-dlp.real"
cookie_file = "/var/www/peertube/storage/youtube-cookies.txt"

# Inject the cookies argument at the beginning of the list
args = [real_binary, "--cookies", cookie_file] + sys.argv[1:]

# Replace the process with the real yt-dlp
os.execv(real_binary, args)
```

**Finalize permissions:**

```
chmod +x yt-dlp
chown peertube:peertube yt-dlp
```

## 5. Maintenance and Monitoring

### Technical Verification

```
# Check that the wrapper works (should display the version)
sudo -u peertube /var/www/peertube/storage/bin/yt-dlp --version

# Test access to a video (should display JSON without error)
sudo -u peertube /var/www/peertube/storage/bin/yt-dlp --dump-json "https://www.youtube.com/watch?v=vfmJpfjsp8w" | head -n 5
```

### Monitor Video Imports

Once the configuration is complete, monitor if the videos are being imported correctly:

1. **In the database:**

   ```
   sudo -u postgres psql -d peertube_prod -c "SELECT name, state, \"createdAt\" FROM video ORDER BY \"createdAt\" DESC LIMIT 10;"
   ```

2. **In the logs (ongoing downloads):**

   ```
   journalctl -u peertube -f | grep -iE "importing|successfully|created"
   ```

3. **Active processes:**

   ```
   ps aux | grep yt-dlp.real
   ```

### Summary of Future Interventions

- **PeerTube Update:** Check if the `yt-dlp` file has been overwritten. If so, rename the new one to `.real` and replace the wrapper.
- **Cookie Expiration:** If the "Anti-bot" error returns, generate a new `youtube-cookies.txt` file.
- **Quotas:** If nothing appears, check in **Administration > Users** that the user does not have a disk quota that is too low (set to `-1` for unlimited).

**Comment by cedric-famibelle-pronzola** [comment]
@Barikad 

It works. Thank you so much for the tip 🙏🏾

**Comment by afilina** [comment]
To add to the answer from @Barikad, if you still get the following error message:

> n challenge solving failed: Some formats may be missing. Ensure you have a supported JavaScript runtime and challenge solver script distribution installed. Review any warnings presented before this message. For more details, refer to  https://github.com/yt-dlp/yt-dlp/wiki/EJS

Then just edit `yt-dlp` from above to change this line:

```diff
- args = [real_binary, "--cookies", cookie_file] + sys.argv[1:]
+ args = [real_binary, "--cookies", cookie_file, "--js-runtimes", "node"] + sys.argv[1:]
```

I didn't even need to install a challenge solver at this time.

**Comment by mikegleasonjr** [comment]
@Barikad what about the docker image?
