### ISSUE TITLE
Include parameter in List Videos

### ISSUE THREAD

**Issue by DimitarSlezenkovski** [Chocobozzz/PeerTube#6524]
### Describe the desired information/correction

Do you need to have Administrator role in order to use the include=8 parameter in list videos request?

https://domain.com/api/v1/videos?start=0&count=10&sort=-best&skipCount=true&nsfw=false&tagsOneOf=bursts&include=8

{
    "type": "about:blank",
    "title": "Unauthorized",
    "detail": "You are not allowed to see all videos.",
    "status": 401,
    "docs": "https://docs.joinpeertube.org/api-rest-reference.html#operation/getVideos",
    "error": "You are not allowed to see all videos."
}

**Comment by Chocobozzz** [comment]
Hi,

The `include` parameter can only be used by admins and moderators. I added a note in the openapi documentation in https://github.com/Chocobozzz/PeerTube/commit/7c83510b831b8f29425947977a2c33f4f937d0fe

I also suggest to upgrade your peertube instance, current server error message is clearer :) https://github.com/Chocobozzz/PeerTube/blob/bba6538435a06b744b03233f138a06978cb9e45f/server/core/middlewares/validators/videos/videos.ts#L485

**Comment by DimitarSlezenkovski** [comment]
Thanks
