### ISSUE TITLE
IPv6 only

### ISSUE THREAD

**Issue by RJGhugo** [Chocobozzz/PeerTube#6526]
### Describe the current behavior

With **IPv6 only** it seems not possible to run a Peertube Instance.

### Steps to reproduce

Mastodon has a similar problem: https://github.com/mastodon/mastodon/issues/27043

**Comment by Chocobozzz** [comment]
Hello,

Please correctly fill the [bug template](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/00-bug-issue.md)

**Comment by RJGhugo** [comment]
Hello,

I think it is a general problem.

There are a lot of components that has to be checked...

https://github.com/Chocobozzz/PeerTube/issues/5513#issuecomment-2263464719

**Comment by Chocobozzz** [comment]
I'm sorry but I don't understand your issue: what is not working? do you have errors? warnings? what are you trying to do?

Please fill the bug template so we can help: https://github.com/Chocobozzz/PeerTube/blob/develop/.github/ISSUE_TEMPLATE/00-bug-issue.yml

**Comment by RJGhugo** [comment]
I got this error since I am on **IPv6** only...

It seems, that several components are not resolving IPv6 the right way...

[peertube.XXXX.XXX:443] 2024-08-05 15:39:53.553 info: Using following configuration file hierarchy: /config/production.yaml.
[peertube.XXXX.XXX:443] 2024-08-05 15:39:53.554 warn: SMTP is not configured so the contact form will not work.
[peertube.XXXX.XXX:443] 2024-08-05 15:39:53.768 info: Database peertube is ready.
[peertube.XXXX.XXX:443] 2024-08-05 15:39:53.929 info: Connecting to redis standalone...
[peertube.XXXX.XXX:443] 2024-08-05 15:39:53.930 error: Cannot use SMTP server because of lack of configuration. PeerTube will not be able to send mails!
[peertube.XXXX.XXX:443] 2024-08-05 15:39:53.941 error: Redis failed to connect {
  "err": {
    "stack": "Error: getaddrinfo ENOTFOUND peertube-redis\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)",
    "message": "getaddrinfo ENOTFOUND peertube-redis",
    "errno": -3007,
    "code": "ENOTFOUND",
    "syscall": "getaddrinfo",
    "hostname": "peertube-redis"
  }

**Comment by Chocobozzz** [comment]
Closing this issue as it seems a Docker issue not related to PeerTube. Please use the forum instead: https://framacolibri.org/c/peertube
