### ISSUE TITLE
Mark the caption file as auto-transcribed

### ISSUE THREAD

**Issue by chagai95** [Chocobozzz/PeerTube#6528]
### Describe the problem to be solved

The user doesn't know if they can trust the quality of the captions 

### Describe the solution you would like

Perhaps by adding something to the file itself or to the file name?
This could then be useful to also show in the UI of PeerTube so people see they are using auto-transcribed captions.

The original issue: 
https://gitlab.com/apps_education/peertube/plugin-transcription/-/issues/52

**Comment by Chocobozzz** [comment]
We already specify the caption has been automatically generated so I'm not sure to understand?

**Comment by Chocobozzz** [comment]
The auto generated label has been added for transcription generated in 6.2.x. It is missing in captions generated in the RC version

**Comment by chagai95** [comment]
Ah sorry, my bad, thx!
