### ISSUE TITLE
Support Captions on Live Streams

### ISSUE THREAD

**Issue by stevespaw** [Chocobozzz/PeerTube#6538]
### Describe the problem to be solved

As we may possibly get Captions in the HLS playlist, it would be fantastic to support eia-708 captions in a live stream. OBS has a plugin to create these, as do broadcast professional products.

### Describe the solution you would like

Support 708  embedded captions like those that can be generated with OBS. The "saved" live stream could have the tag - "Live Captioned" and could be appended with 2nd caption file of "auto generated" on final transcode. 
OBS plugin here: [https://github.com/ratwithacompiler/OBS-captions-plugin?tab=readme-ov-file](url)
Twitch tech info for reference: [https://help.twitch.tv/s/article/guide-to-closed-captions?language=en_US#HowtoUseLiveClosedCaptionsforBroadcasters](url)

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/4505
