### ISSUE TITLE
Deleting failed/error runner jobs result most of the time by "error, runner not found"

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#6542]
### Describe the current behavior

if I delete a failed/error runner job batch (more than 10) it result an error.
I have to refresh it and apparently there are some deleted but no more than 10 on 100 showed.

### Steps to reproduce

1. select 100 failed/errored jobs
2. delete it from batch

### Describe the expected behavior

it should delete all selected jobs!

Also, what's the process of PT whe jobs failed? does it try to restart or not?

### Additional information

peertube v6.2.1

**Comment by Chocobozzz** [comment]
Hi,

Can you paste web browser and server logs when you delete your runner jobs?

**Comment by ROBERT-MCDOWELL** [comment]
ok, for now no failed runner jobs ;-\

**Comment by Chocobozzz** [comment]
I'm closing this issue but feel free to comment if you have any news to share

**Comment by ROBERT-MCDOWELL** [comment]
since I updated to 6.2.1 there are much less runner jobs error so for now I cannot reproduce the issue since it needs more than 20 errors
