### ISSUE TITLE
Option to restart runner job or transcode particular resolution

### ISSUE THREAD

**Issue by ilfarpro** [Chocobozzz/PeerTube#6546]
### Describe the problem to be solved

Sometimes runner jobs stuck and get unresponsive. It would be great if there is an option to restart that job or create another job to transcode missing resolution only.

**Comment by Chocobozzz** [comment]
I think we should fix the job issue instead. Can you provide peertube instance  + runner versions and logs from the time the job is created until it's stuck?

**Comment by ilfarpro** [comment]
Peertube instance is 6.2.1
Runner – 0.0.20

Job
```
Parent job: 50054508-fe8e-4661-8906-574e9efb03ff
Processed on 8/12/24, 1:26:56.939 PM
Finished on 8/12/24, 9:39:53.411 PM
Payload:
{
  "input": {
    "videoFileUrl": "https://k-pop.22x22.ru/api/v1/runners/jobs/ce745b82-9ac5-4fae-8793-1aca66be58f5/files/videos/04304237-df79-4f75-9a76-dbfdb5eed266/max-quality"
  },
  "output": {
    "fps": 60,
    "resolution": 720
  }
}
Private payload:
{
  "videoUUID": "04304237-df79-4f75-9a76-dbfdb5eed266",
  "isNewVideo": false,
  "deleteWebVideoFiles": false
}
```

Don't have any logs on Peertube instance side, since I explicitly set them to be warning level and above (for performance reasons).

Peertube runner was started with debug level, however at 1:26 PM or 9:39:53 PM there are no logs only pings from Peertube instance. Runner was transcoding videos a day before runner job was marked as finished in Peertube I guess. 

Since I don't have any usefull logs to provide I will close this issue and reopen if this problem happens again. This time I'm going to log everything properly.
