### ISSUE TITLE
Can't create database in firts intall (node v20.16.0)

### ISSUE THREAD

**Issue by lifespirit** [Chocobozzz/PeerTube#6547]
### Describe the problem

Hello.
When I first run instance I have error:

> null value in column \"nodeVersion\" of relation \"application\" violates not-null constraint

Full log: https://pastebin.com/Uj9SAr0P

### Additional information

* PeerTube instance URL: libertube.ru
* PeerTube version: 6.2.1
* NodeJS version: v20.16.0
* Ffmpeg version: n7.0.1
* Redis version: 7.2.5
* PostgreSQL version: 16.3

**Comment by Chocobozzz** [comment]
Hi,

Please drop and re-create your database. Then run PeerTube and paste the logs

**Comment by lifespirit** [comment]
I fixed it. Thanks for help.

Solution for history:

1. You don't need add 
sudo -u postgres psql -c "CREATE EXTENSION pg_trgm;" peertube_prod
sudo -u postgres psql -c "CREATE EXTENSION unaccent;" peertube_prod
in database. All work without it.

2. You can see real problem only in first launch on clean installation. I have permissions problem with storage/tmp folder in my case, but I can see that error only when I drop database.

Thanks for help again.
