### ISSUE TITLE
Defederation system

### ISSUE THREAD

**Issue by FediVideos** [Chocobozzz/PeerTube#6551]
### Describe the problem to be solved

My instance's channels have a few followers from a very dubious non-PeerTube instance which I would like to defederate. There doesn't seem to be any way to do this?

### Describe the solution you would like

An optional defederation system where instance admins can block specific instances so that they will not be communicated with or follows acknowledged. (I realise they could still follow by RSS, but RSS doesn't allow them to interact with me.)

**Comment by Chocobozzz** [comment]
Muted account or server cannot follow your instance or your channels. But if the remote actor already follows one of your channel, we need a page where you can remove them. I'm merging this issue in https://github.com/Chocobozzz/PeerTube/issues/1764 (a management page to approve/refuse/remove channel followers)

**Comment by FediVideos** [comment]
Ah, apologies, I did not realise this, thank you for the reply. The "mute" term on some platforms implies it just hides stuff, didn't realise it's actually blocking.
