### ISSUE TITLE
6.03 - 6.21 Upgade wont start

### ISSUE THREAD

**Issue by tyler-hh** [Chocobozzz/PeerTube#6552]
### Describe the problem

I used the /update.sh script to try and upgrade my instance.
At first it failed due to being unable to backup the Postgres Database.  I had to give the peertube user higher rights for the backup to take place.

I did complete this task:
You must update nginx configuration: https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube
Add location ~ ^/api/v1/users/[^/]+/imports/import-resumable$ { block

But I did not complete this task:
Breaking changes:
Rename views.videos.ip_view_expiration to views.videos.view_expiration

As I could not find that text in any files.  So I assume not doing that step is what broke my instance.

Nginx error log says it cant connect to the web socket.  

This is the systemcontrol log.

 peertube.service: Consumed 3.610s CPU time.
Aug 20 19:59:51 mainserver systemd[1]: Started PeerTube daemon.
Aug 20 19:59:54 mainserver peertube[72620]: file:///mnt/2/var/www/videos.website.com/peertube/versions/peertube-v6.2.1/node_modules/execa/lib/utils/max-listeners.js:1
Aug 20 19:59:54 mainserver peertube[72620]: import {addAbortListener} from 'node:events';
Aug 20 19:59:54 mainserver peertube[72620]:         ^^^^^^^^^^^^^^^^
Aug 20 19:59:54 mainserver peertube[72620]: SyntaxError: The requested module 'node:events' does not provide an export named 'addAbortListener'
Aug 20 19:59:54 mainserver peertube[72620]:     at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
Aug 20 19:59:54 mainserver peertube[72620]:     at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
Aug 20 19:59:54 mainserver peertube[72620]:     at async Promise.all (index 0)
Aug 20 19:59:54 mainserver peertube[72620]:     at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
Aug 20 19:59:54 mainserver peertube[72620]:     at async loadESM (node:internal/process/esm_loader:91:5)
Aug 20 19:59:54 mainserver peertube[72620]:     at async handleMainPromise (node:internal/modules/run_main:65:12)
Aug 20 19:59:54 mainserver systemd[1]: peertube.service: Main process exited, code=exited, status=1/FAILURE
Aug 20 19:59:54 mainserver systemd[1]: peertube.service: Failed with result 'exit-code'.
Aug 20 19:59:54 mainserver systemd[1]: peertube.service: Consumed 3.867s CPU time.
Aug 20 19:59:54 mainserver systemd[1]: peertube.service: Scheduled restart job, restart counter is at 2.
Aug 20 19:59:54 mainserver systemd[1]: Stopped PeerTube daemon.

Any advice on how I can correct my errors?

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by tyler-hh** [comment]
I have since tried the manual route and was made aware my node.js was out of date.  I have since updated to a later version.  Peertube now fails to start with:

 Started PeerTube daemon.
Aug 20 20:47:26 mainserver systemd[89713]: peertube.service: Changing to the requested working directory failed: No such file or directory
Aug 20 20:47:26 mainserver systemd[89713]: peertube.service: Failed at step CHDIR spawning /usr/bin/node: No such file or directory
Aug 20 20:47:26 mainserver systemd[1]: peertube.service: Main process exited, code=exited, status=200/CHDIR
Aug 20 20:47:26 mainserver systemd[1]: peertube.service: Failed with result 'exit-code'.
Aug 20 20:47:27 mainserver systemd[1]: peertube.service: Scheduled restart job, restart counter is at 3.
Aug 20 20:47:27 mainserver systemd[1]: Stopped PeerTube daemon.

I was unable to complete the steps:
diff -u "$(ls -t | head -2 | tail -1)/support/nginx/peertube" "$(ls -t | head -1)/support/nginx/peertube"
diff: peertube-latestcd/support/nginx/peertube: Too many levels of symbolic links

diff -u "$(ls -t | head -2 | tail -1)/support/systemd/peertube.service" "$(ls -t | head -1)/support/systemd/peertube.service"
diff: peertube-latestcd/support/systemd/peertube.service: Too many levels of symbolic links

**Comment by Chocobozzz** [comment]
Hello,

Please use the forum for PeerTube sysadmin related questions: https://framacolibri.org/c/peertube

See for example: https://framacolibri.org/t/start-after-upgrade-to-6-2-1-fails-with-error-syntaxerror-the-requested-module-node-events-does-not-provide-an-export-named-addabortlistener/22284?u=chocobozzz
