### ISSUE TITLE
Peertube website as Major search engine result with subtitle shows a browser error string!

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#6554]
### Describe the current behavior

subtitle result of search engines results show this:

[MyPT- MyPT](https://www.mypt.com/c/news)
We are sorry but it seems that PeerTube is not compatible with your web browser · Please try with the latest version of Mozilla Firefox

??!!!???

### Steps to reproduce

1. Search on major search engines your peertube website (if referenced of course)
2. read the subtitle of the result

### Describe the expected behavior

should be the description of the description in the config in administration section no?

### Version
v6.2.1

**Comment by Chocobozzz** [comment]
Hi,

Can you share your search so we can check?
