### ISSUE TITLE
Character encoding broken after migration

### ISSUE THREAD

**Issue by fabiopicchi** [Chocobozzz/PeerTube#6563]
### Describe the current behavior

After instance migration my video titles and descriptions are not being displayed correctly, and they have these dreaded � characters where we would have accented characters. I have checked the locales and the database and everything seems to be correct.

Funnily enough, if I restart Peertube with `systemctl restart peertube`, the strings are rendered correctly for about a minute and then stop working again. Titles are also rendered correctly in the home page, where videos are displayed in a grid.

Example:
https://play.cotv.org.br/w/4CjPtWh4w6PKQBJbKHDS66

Same video in the _Trending_ page:
https://play.cotv.org.br/videos/trending

On a last note, the same behavior affects the logs. I noticed when inspecting my debug logs that the � characters appear in logged SQL queries (because some of our hashtags contain accented characters) and that starts to happen once peertube is running.

### Steps to reproduce

1. Open a video page
2. Verify that the accented characters are not displayed correctly

### Describe the expected behavior

Accented characters are displayed correctly

### Additional information

* PeerTube instance:
  * URL: https://play.cotv.org.br/
  * Version: 6.1.0
  * NodeJS version: 22.7.0
  * Ffmpeg version: 6.1.0

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by fabiopicchi** [comment]
It worked! Sorry for not paying close attention to the installation guide (it specifies 20.x).

Before I close this one, would you know what happened in newer versions of node to produce this weird behavior?

**Comment by Chocobozzz** [comment]
No, I think it's just a nodejs bug :)
