### ISSUE TITLE
Make viewer aware of started live stream

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#6565]
### Describe the problem to be solved

When a user opens up a live stream that hasn't started yet he'll probably switch to another browser tab to continue with something else while waiting. When the web client receives stream started event the page will just reload, without making the user aware of that the stream has started.

### Describe the solution you would like

If possible, autoplay the video and maybe switch to another favicon and/or page title to make the user aware of a started live stream.

**Comment by Chocobozzz** [comment]
In the next version (6.3) the page will not be completely rebuilt: the player will just autoplay the video. But web browsers may block the autoplay request. Please try this new version (when it will be released) and tell me if it fixes the autoplay issue.

If not, we'll reopen this issue and try to implement the favicon/page title idea :)
