### ISSUE TITLE
Metadata Import Bug from Instagram

### ISSUE THREAD

**Issue by tilllt** [Chocobozzz/PeerTube#6568]
### Describe the current behavior

When importing a video from Instagram, the Title of the Video is "Video by Username". The actual Title of the Video is imported as the first line of the description.

### Steps to reproduce

1. Import video from insta
2. Review imported Metadata
3.

### Describe the expected behavior

The Title of the videoon Instagram should be the imported  title on Peertube, optionally the "video by username" could be added to the Title.

What would be great is admin configurable metadata mapping, so the admin could decide which data to map and where to map it. Personally I would like to maintain a link to the imported media (i.e. on tiktok or Instagram) in the description 

### Additional information

* PeerTube instance: 6.2 docker
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

Can you share an instagram URL?

**Comment by tilllt** [comment]
Sure, 

https://www.instagram.com/p/C6GRCrTs0Cz/

In fact I just realized there is no "title" in Instagram videos, but usually the first line contains either the hashtags (which are not mapped to tags, neither used as a title) or a description of the video which might serve as a title.

**Comment by Chocobozzz** [comment]
Indeed, there's not title for instagram videos. Then I suggest to request an improvement on the [yt-dlp repository](https://github.com/yt-dlp/yt-dlp/) so they improve the `title` attribute (that PeerTube uses).

**Comment by tilllt** [comment]
So who maps the username to the title field yt-dlp or Peertube?
