### ISSUE TITLE
Writing unit tests

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#657]
Currently there are API and CLI tests which run the entire application and test the result of the full stack.

We could have also unit tests with mocking utilities to only test specific modules, isolating from their dependencies. The idea behind is to cover lots of cases, even (and particularly) the edge ones.

I am personally used to Mocha + Sinon (for spies and stubs) + Chai + [proxyquire](https://www.npmjs.com/package/proxyquire) (mock injectors). The advantage of proxyquire is that it is unobtrusive (no need to change anything in the application code), but it seems like it does not run well with Typescript.

Some mocking libraries that fit well with Typescript:
 - [ts-mockito](https://github.com/NagRock/ts-mockito)
 - [typemoq](https://github.com/florinn/typemoq)

I can pave the way with a PR to show a concrete use case (in the next weeks).

Florent

**Comment by Chocobozzz** [comment]
No sorry, I don't think unit tests would be worth because we are not a team of 10 persons, and with the current integration tests I never felt the need to have unit tests.
