### ISSUE TITLE
Video Studio Missing Video Embed in Mobile

### ISSUE THREAD

**Issue by Mike35538** [Chocobozzz/PeerTube#6572]
### Describe the current behavior

If you are in a mobile device and go to the Video Studio editor for any video, then the embedded video does not display when using a phone in vertical mode. If you rotate your phone to horizontal, then the embed video is so tiny it is unusable. Also, in most tablets, the embedded video is very tiny so you cannot play the video for timestamp references.

![tablet](https://github.com/user-attachments/assets/f32bd9dc-169f-4c8d-ba99-bb2291463661)

### Steps to reproduce

1. Use a phone and go to Video Studio and view in vertical and horizontal.
2. On a computer with a large display, in Firefox browser, go to Menu > More Tools > Responsive Design Mode, and test different devices and display sizes.

### Describe the expected behavior

The Video would be visible and large enough to view accurate timestamps for typing into the New Start and New End fields.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! Fixed by https://github.com/Chocobozzz/PeerTube/commit/82c15dd48efed01b0fb3702fa612fa27d61005a4
