### ISSUE TITLE
Dark Theme: Input for "original publication date" almost not readable

### ISSUE THREAD

**Issue by bjoernmartin** [Chocobozzz/PeerTube#6576]
### Describe the current behavior

The input field for the **Original Publication Date** on the **Advanced settings** tab of the video publish / edit page is shown in black on a dark background when using dark mode:

![image](https://github.com/user-attachments/assets/b8269fd5-c307-462a-bd51-2a5078fdd6b7)

### Steps to reproduce

1. Edit an uploaded video **or** start publishing a new one (opens almost the same mask)
2. Navigate to **Advanced settings**
3. Click on the input field of **Original Publication Date** and enter any value, closing the selector popup

### Describe the expected behavior

The input field should show its content in the same color as the **Comments policy** input field below it. Mockup:

![image](https://github.com/user-attachments/assets/fdead9c9-bcdc-4e00-9da9-ac8990afbd16)

### Additional information

* PeerTube instance:
  * URL: _intranet installation_
  * Version: 6.2.1
  * NodeJS version: unknown (can find out next week if relevant)
  * Ffmpeg version: unknown (can find out next week if relevant)
  * Dark Theme version: 2.5 + later 2.6

* Browser name, version and platforms on which you could reproduce the bug: Firefox 130.0 (64-bit) on Windows 11
* Link to browser console log if relevant: -
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): -

**Comment by bjoernmartin** [comment]
The location within the code that renders this seems to be [./client/src/app/+videos/+video-edit/shared/video-edit.component.html](https://github.com/Chocobozzz/PeerTube/blob/d12e0746219f77f78c78d546e82675c49a532831/client/src/app/%2Bvideos/%2Bvideo-edit/shared/video-edit.component.html#L436C16-L436C26). But I have no clue about how styling is applied to this `p-calendar` component, especially since theming seems to be a thing (at least for dark mode).

**Comment by Chocobozzz** [comment]
Hi,

What is your dark theme versionN

**Comment by bjoernmartin** [comment]
We had version 2.5 but just updated to 2.6. Same issue.

**Comment by bjoernmartin** [comment]
It got fixed. 

Our Peertube instance got an update for **DarkTheme to 2.6.1 two days ago**, but a test by me didn't fix it. Yesterday the colleagues updated **Peertube to 6.3.0**, and now it's fixed.

![image](https://github.com/user-attachments/assets/8defa3ff-8990-4d69-9f4b-474bf5525ecb)

I cannot see (as a user) whether that did also update DarkTheme again. Or maybe it was my browser (cache) and I didn't try hard enough? Not sure. 

Anyway, thanks for the fix!
