### ISSUE TITLE
Federated profile photos from external, non-PeerTube platforms have giant file sizes

### ISSUE THREAD

**Issue by letydoesstuff** [Chocobozzz/PeerTube#6579]
### Describe the current behavior

Federated profile photos from external, non-PeerTube platforms are resized to 1500x1500px upon import. This results in external profiles taking up giant amounts of storage, especially if such profile photos are complex, animated gifs.

My PeerTube channel, [@letydoesshitposting_channel@peertube.doesstuff.social](https://peertube.doesstuff.social/c/letydoesshitposting_channel/videos), is currently set to have the same profile photo as my primary Mastodon account, [@lety@doesstuff.social](https://peertube.doesstuff.social/a/lety@doesstuff.social/video-channels). These look the same to the end user, but the [local PeerTube profile photo](https://peertube.doesstuff.social/lazy-static/avatars/885ebd16-1ffc-415a-9c95-4b370970fe1c.gif) is under 700KB at 120x120px, while the [external Mastodon profile photo](https://peertube.doesstuff.social/lazy-static/avatars/d26f9989-c20b-4368-9185-a76f02aaba07.gif) is just about 70MB at 1500x1500px.

Profiles federated from external PeerTube instances will also import their local 120x120px profile photo ([example](https://peertube.doesstuff.social/a/bazza@fediverse.tv/video-channels)). The giant 1500x1500px profile photos only seem to be generated for accounts from external, non-PeerTube platforms ([example](https://peertube.doesstuff.social/a/omggstuff@mastodon.social/video-channels)).

[Videos with comments from external, non-PeerTube platforms](https://peertube.doesstuff.social/w/dRzZSwBDSiuYhpQfin3wnJ;threadId=22325) consume a lot of data loading up these giant profile photo. On some videos, it is possible for the data required to load external profile photos to exceed the data needed to load the video itself. 

### Steps to reproduce

Explained above.

### Describe the expected behavior

Federated profile photos from external, non-PeerTube platforms should also import and render at the same 120x120px as local PeerTube profile photos.

### Additional information

* PeerTube instance: Does Stuff Social (but affects all instances)
  * URL: https://peertube.doesstuff.social
  * Version: v6.3.0-rc.1
  * NodeJS version: 18.20.4
  * Ffmpeg version: v4.4.2-0ubuntu0.22.04.1

* Browser name, version and platforms on which you could reproduce the bug: Irrelevant
* Link to browser console log if relevant: Irrelevant
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): Irrelevant

**Comment by Chocobozzz** [comment]
Thank you very much for the issue! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/565a11d8d37f16ab0965015f136986f4368668c6 where we don't resize remote images anymore.

You can run https://docs.joinpeertube.org/maintain/tools#cleanup-remote-files to cleanup your local disk
