### ISSUE TITLE
Replays No Longer Counting Views Correctly 

### ISSUE THREAD

**Issue by MattyBoombalatty** [Chocobozzz/PeerTube#6580]
### Describe the current behavior

Before 6.2.1, live video view count aggregates would translate over to the replay/VOD publishing of the video but that doesn't seem to be the case anymore. For example, last night we had a livestream with ~15 concurrent viewers with others coming and going for about 2.5 hours. However, the replay shows there are only 5 views. Is there a setting I missed? Thanks! 

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL: https://nicecrew.tv
  * Version: 6.2.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by kontrollanten** [comment]
Hi, sounds related to https://github.com/Chocobozzz/PeerTube/issues/6571
