### ISSUE TITLE
Transcription highlight color has light text in 6.3.0-rc.1

### ISSUE THREAD

**Issue by Mike35538** [Chocobozzz/PeerTube#6585]
### Describe the current behavior

Using the dark theme, Show transcription and let the video play. The highlight color is white on gray text and unreadable.

![transcript-highlight](https://github.com/user-attachments/assets/cb11fe1d-e6c7-487a-8fba-10d05aee7210)

### Additional information

* PeerTube instance:
  * Version: 6.3.0-rc.1

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by dark plugin 2.6.0 (available soon on the index).

**Comment by Mike35538** [comment]
It looks great, thanks so much!
