### ISSUE TITLE
Videos on a 6.3.0-rc1 server break federation on earlier instances.

### ISSUE THREAD

**Issue by MadMan247** [Chocobozzz/PeerTube#6586]
### Describe the current behavior

Currently, videos from 6.3.0-rc1 instances break when federated with past Peertube versions. Videos contain no audio when played back through 6.2.1. Even older versions (5.2.0) simply don't seem to want to play anything at all.

### Steps to reproduce

1. locate a video from an instance that is running peertube 6.3.0-rc1
2. locate an instance that is running 6.2.1
3. play 6.3.0-rc1 video through 6.2.1 instance
4. video plays, audio does not.

### Describe the expected behavior

Playing the video still results in a video stream that contains audio.

### Additional information

* PeerTube instance:
  * URL: peer.acidfog.com [example 1](https://peer.acidfog.com/w/b6UwctmBAhxCMkpKrtMXyG), [example 2](https://peer.acidfog.com/w/kRq4UWxLgdSmb2tHeh4XU8), [example 3](https://video-cave-v2.de/w/kRq4UWxLgdSmb2tHeh4XU8), [example 4 (5.2.0)](https://peertube.otakufarms.com/w/kRq4UWxLgdSmb2tHeh4XU8)
  * Version: 6.2.1
  * NodeJS version: 20.17.0 (probably. Just because I have this one installed doesn't mean Peertube uses it.)
  * Ffmpeg version:  4.3.7-0+deb11u1+rpt2

* Browser name, version and platforms on which you could reproduce the bug: Firefox 130.0 (64-bit), Windows 10.
* Link to browser console log if relevant: https://pastebin.com/m0JAYbcG (probably not relevant)
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): (not relevant. I checked)

**Comment by MadMan247** [comment]
I think the title is bad/misleading. Apologies. Please correct at your convenience. I am not sure what a proper title would be.

**Comment by Chocobozzz** [comment]
Hi & thank you for the issue

These remote instances decided to enable a configuration in transcoding that prevent instances < 6.3.0 to correctly play these videos. I added a warning in https://github.com/Chocobozzz/PeerTube/commit/7fa9004f4ca653ab7ce00bdb388fc0c0c5720b8d so admins know they break federation with this option with instances < 6.3.0.

**Comment by MadMan247** [comment]
Hello.
Thank you for the prompt response and solution. I wonder if this change will cause many peertube instances that have remained on past versions to upgrade. Over half [of all instances](https://instances.joinpeertube.org/instances?sort=version&page=1) are 6.1.0 or lower.
Just as a heads up, you should change that operator to either < 6.3.0 or <= 6.2.1. currently <=6.3.0.
`If enabled, remote PeerTube instances <= 6.3.0 won't be able to play these video`
since 6.3.0 instances will support this feature.
