### ISSUE TITLE
Firefox version 130.0 : annoncé incompatible peertube

### ISSUE THREAD

**Issue by picreach** [Chocobozzz/PeerTube#6590]
### Describe the current behavior

PeerTube
Incompatible browser

We are sorry but it seems that PeerTube is not compatible with your web browser.

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance: Toutes instances sur picasoft
  * URL: https://tube.picasoft.net/login
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Please provide your web browser console log
