### ISSUE TITLE
Version 6.3.0 Mobile Video Controls Issue

### ISSUE THREAD

**Issue by MattyBoombalatty** [Chocobozzz/PeerTube#6593]
### Describe the current behavior

On mobile (Firefox/Brave and PWA tested on Android), when tapping on the gear icon in the video player, the video player settings modal will flicker and then close itself, making it impossible to change the quality or select audio-only.

This also happens when just resizing the browser to mobile size on desktop, so it's easily repeatable.

### Steps to reproduce

1.
2.
3.

### Describe the expected behavior

This should not happen.

### Additional information

* PeerTube instance:
  * URL: https://nicecrew.tv
  * Version: 6.3.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by MattyBoombalatty** [comment]
It looks like the `vjs-hidden` class is added to the `div` as soon as you click on it, which opens and then closes it. At the same time the `vjs-settings-dialogue-opened` class name is added and then immediately removed from the parent element, which leads me to believe the problem is there. Maybe an issue with `preventDefault`?

**Comment by Chocobozzz** [comment]
Thanks for the issue! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/7d3a9cabdca75d906b170f509b75edc665c200d5
