### ISSUE TITLE
Automatically resume videos

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#660]
On a long video, we may watch it in several times. It might be worth to resume it automatically, and display a small loading bar below the video miniature (to see when we previously stopped the video).

The only thing I'm unsure: do we store this information on the server (for logged users) or in the local storage?

**Server**
Cons: privacy -> admin instances could know what videos their user have watched
Pro: We can resume a video we watched on our mobile device or on another computer

**Local storage**
Cons: We can't resume a video we watched on another device/web browser
Pro: Would be available for all users, not only logged in

Maybe we could add a checkbox in user preferences, but I would like to keep it as simple as possible.

**Comment by DavidLibeau** [comment]
Local will be difficult to do because we can watch a video on several instances.

**Comment by bennukem** [comment]
Server side can be useful for later, to make stats about what a viewer watched or not.
Theses data can be erased after few days.

**Comment by nightpool** [comment]
> Cons: privacy

wouldn't it be trivial to figure out what videos users have watched anyway, by looking at the webtorrent connections?

**Comment by Chocobozzz** [comment]
> wouldn't it be trivial to figure out what videos users have watched anyway, by looking at the webtorrent connections?

If you're the admin, in theory you can hack peertube to see what IPs has announced which video file, and save this data somewhere, but you won't really be able to know how long and if the user watched the video.

> Or like.... the list of pages requested in your web server logs

Yes, if you enable nginx byte range requests logging, you might be able to know what IPs has consumed which video file, but it would be more difficult than just executing a SELECT in a SQL table. Moreover, it's not because the IP downloaded the data that they watched it while with this feature the admin would know at what timestamp the user stopped the video.

But these are interesting arguments, thank you!

**Comment by Chocobozzz** [comment]
Let's implement this on server side, with a button to clear the history.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/6e46de095d7169355dd83030f6ce4a582304153a

**Comment by BO41** [comment]
@Chocobozzz is this just a notification about the time point I last stopped watching the video, or is it automatically resuming?
Both solutions are good, but for music for example, it would be better to not resume the video but just name the time point of the last time I was on this video

**Comment by Chocobozzz** [comment]
> is this just a notification about the time point I last stopped watching the video, or is it automatically resuming?

It is automatically resuming

**Comment by jean-emmanuel** [comment]
I think the resume information should expire at some point, after a day or so, don't you ?

**Comment by bennukem** [comment]
> I think the resume information should expire at some point, after a day or so, don't you ?

no, I hate when it isn't remember I saw a video event if one year old.
and you can do it on the database with a sexy cron
