### ISSUE TITLE
Provide more video tags in sitemap.xml

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#6606]
### Describe the problem to be solved

In order to make Peertube sites to be easier indexed by search engines we should provide more information about the videos in the sitemap.xml.

### Describe the solution you would like

Add:

* <video:content_loc>	
* <video:duration>	
* <video:view_count>	
* <video:publication_date>	
* <video:uploader>	
* <video:live>	
* <video:tag>	

And maybe:
* <video:family_friendly> - Should be possible to use "sensitive content" value to set this.
* <video:rating> - Calculate based on likes/dislikes ratio.

https://developers.google.com/search/docs/crawling-indexing/sitemaps/video-sitemaps

**Comment by Chocobozzz** [comment]
Do you have SEO/indexation issues with PeerTube?

**Comment by kontrollanten** [comment]
Yes, Google doesn't treat videos on watch pages as the main content, and pretty low rank overall. I assume that if we provide as much information as possible it's a better chance that Google treats the sites as serious.
