### ISSUE TITLE
Peertube webserver asnwers with any hostname which pertains to your root domain (*.domain.com)

### ISSUE THREAD

**Issue by jmsimonet** [Chocobozzz/PeerTube#6608]
I'm pretty sure that isn't a peertube bug, but I can't found how to avoid in project documentation, maybe a documentation fault, I don't know.
I've succesfully configured a peertube instance, with all dockers running, including it own webserver.
The instance works perfectly and is listening on normal ports 80 and 443, the only "strange thing" it's that I 've replaced certbots certificates with my own digicert certificates,(respecting the volume paths declared on nginx template) but I think it isn't the problem.
The peertube instance answers under any hostname that differs of the hostname declared on .env file.
If my peertube instance is xxx.peertube.com, if I create an A record on my dns server that appoints to same IP, the peertube instance responses with tokens client error, but responses, althought differs on .env declared hostname.
For example:
Declared hostname : peertube.media.com
Invented hostname : peertube1.media.com
Is there a way to restrict the hostname to avoid this?.
The peertube web shows a token error if you enter by other hostname, bu you can watch public videos.
I 've other projects with nginx and this doesn't happen.
Thank you,

### Steps to reproduce

1.Declare peertube hostname on .env file
2.Run the dockers
3.The access to peertube instance can be carried out with any hostname that differs on .env file

### Describe the expected behavior

Peertube instance must answer with hostname declared on .env file, showing a domain error instead

### Additional information

* PeerTube instance:
  * URL:
  * Version:<=6.3.0
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:all browsers
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

Can you try to add a nginx configuration to catch all requests to other domains than `peertube.media.com` so they are not forwarded to PeerTube?

**Comment by jmsimonet** [comment]
Hi,
Thank you so much for your help.
As you can say, I have succesfully block non-site domains with 

https://stackoverflow.com/questions/16672562/nginx-reverse-proxy-non-listening-domain-catch-all

Putting a new directive for 80 and 443 and returning a 404 http error.
In my opinion, the nginx template should specify something like this, is pretty strange want to answer under any domain.

Thanks,
