### ISSUE TITLE
Quality Gear

### ISSUE THREAD

**Issue by msdeek** [Chocobozzz/PeerTube#6609]
### Describe the current behavior

i Embed Video 
Unable to preventDefault inside passive event listener invocation.
Kt.s.preventDefault @ embed-CJwT91rw.js:20
n.handleMouseDown @ embed-CJwT91rw.js:20
n.handleMouseDown @ embed-CJwT91rw.js:20
t.handleMouseDown_ @ embed-CJwT91rw.js:20
G.r.dispatcher.r.dispatcher @ embed-CJwT91rw.js:20

<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto; color: rgb(227, 227, 227); font-family: &quot;Noto Sans Mono&quot;, &quot;DejaVu Sans Mono&quot;, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(78, 53, 52); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Unable to preventDefault inside passive event listener invocation.</span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(227, 227, 227); font-family: &quot;Noto Sans Mono&quot;, &quot;DejaVu Sans Mono&quot;, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(78, 53, 52); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace stack-preview-container width-constrained" style="display: inline-block; --monospace-font-size: 11px; --monospace-font-family: &quot;Noto Sans Mono&quot;,&quot;DejaVu Sans Mono&quot;,monospace; --source-code-font-size: 11px; --source-code-font-family: &quot;Noto Sans Mono&quot;,&quot;DejaVu Sans Mono&quot;,monospace; width: 922px; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | Kt.s.preventDefault | @ | embed-CJwT91rw.js:20
-- | -- | -- | --
  | n.handleMouseDown | @ | embed-CJwT91rw.js:20
  | n.handleMouseDown | @ | embed-CJwT91rw.js:20
  | t.handleMouseDown_ | @ | embed-CJwT91rw.js:20
  | G.r.dispatcher.r.dispatcher | @ | embed-CJwT91rw.js:20

</span></div>

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Please provide the URL of your website
