### ISSUE TITLE
Transcoding jobs seems to stay in inactive state, for some reason

### ISSUE THREAD

**Issue by DavidLibeau** [Chocobozzz/PeerTube#661]
* **PeerTube version or URL:** Beta.8
* **NodeJS version:** v8.11.2

* **What is the expected behaviour?**
Do all the video-file transcoding jobs.
* **What do you see instead?**
When I manually add several video transcoding jobs with `npm run create-transcoding-job`, it seems that the last one is proceeded and the other stay in inactive state forever.

**Comment by DavidLibeau** [comment]
I add 3 videos with `npm run create-transcoding-job` : the **last** one added is proceeded and the others are in inactive state.
Newly uploaded videos are well transcoded.

**Comment by Chocobozzz** [comment]
If you restart the server, are these jobs being run?

**Comment by DavidLibeau** [comment]
Doing `sudo systemctl restart peertube` seems to do nothing with these inactive jobs.

**Comment by fflorent** [comment]
I had the same issue with `create-import-video-file-job`. The only way to fix this was to run the [kue dashboard](https://github.com/Automattic/kue#user-interface) and run each job manually. 

Do you use Docker?

Florent

**Comment by DavidLibeau** [comment]
Ok,
I am not using Docker.

**Comment by fflorent** [comment]
I think @rigelk tried to reproduce, but without success. Also it seems that it's a bug of kue.

> We should not have to run kue dashboard to run these jobs

Sure, that's only a workaround.

**Comment by gled-rs** [comment]
we may be impacted by that also on peertube.mastodon.host ( baremetal deployment, 1 transcode thread with only 720p and 480p enabled ).

A lot of videos in the queue are shown as inactive.

It may have been triggered by a crash we had 10 days ago ( node segfault ). Upon restarting the service after the crash, if refused to start, mentioning a missing -1080p video file ( there was a file at the location mentionned, so I just erased it and it allowed to restart ). Maybe it is what triggered the bug ?

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/2cdf27bae6acfaa0b99bb07555edc57f48b8bc43 & https://github.com/Chocobozzz/PeerTube/commit/94831479f5facff9469540a3d49dd347b88bdf5a
