### ISSUE TITLE
Access to the Peertube plugin site is not possible under certain conditions.

### ISSUE THREAD

**Issue by wjdans0172** [Chocobozzz/PeerTube#6611]
### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL: 
  * Version: v6.3.0
  * NodeJS version: v20.15.0
  * Ffmpeg version: v6.1.1

Hello Peertube Foundation!

I am a Peertube user from Korea (not North Korea). I’ve been using Peertube without issues, but at some point, I started seeing the error: "Plugin index is not available" and I couldn’t access the plugin. (I’m not exactly sure when this issue began.)

So I investigated and found that the connection to the site below timed out:

https://packages.joinpeertube.org/api/v1/plugins

There was nothing blocked by the firewall or similar measures. The strange thing is, the connection works fine on KT's network (a Korean telecommunications company), but it times out on other networks.

1. Before I contact the telecommunications companies, I’d like to ask first: Is there any logic that blocks access based on IP or other metadata? Based on the A record IP (178.63.240.150) of the site above, it doesn’t seem like services like Cloudflare are being used, so I’m asking for clarification.

2. Is there an alternative URL, or is there a way to download the files locally? In production.yaml, there is a section for plugins. I would like to know if there is another method for obtaining the plugins.

![fail1](https://github.com/user-attachments/assets/adb142b1-d6bc-4592-84dd-2a5a5553d9db)
![fail2](https://github.com/user-attachments/assets/7da5222b-087f-4a5a-84ca-a4b89550b466)

**Comment by Chocobozzz** [comment]
Hi,

FAIK we don't block IPs on our PeerTube services. Please contact me by email (in my github profile) and provide your IP address so we can debug this issue!
