### ISSUE TITLE
No Audio on 6.3 upgrade to clips that are re-transcoded.

### ISSUE THREAD

**Issue by stevespaw** [Chocobozzz/PeerTube#6612]
### Describe the current behavior

Looking forward to new separate audio feature in 6.3. Works great on new published clips, but existing clips when running "Run HLS transcoding" the audio disappears and no "-0-fragmented.mp4" is created. 

### Steps to reproduce

1. publish any video - Video transcodes - moves to object storage and Audio plays fine - "*-0-fragmented.mp4" is created.
2. download an existing video just to test. And republish works fine.
3.  "Run HLS transcode" on the same video. No audio plays and "*-0-fragmented.mp4" does not exist.
4.

### Describe the expected behavior

 "Run HLS transcode" on existing videos to create new m3u8 and "*-0-fragmented.mp4" is created properly.
Is there a different way to do this?

### Additional information

Upgrade from 6.21
  * Version: 6.3

**Comment by Chocobozzz** [comment]
Thanks for the issue! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/093a9bf74982dbe09ddeebe83392c93df345fd91

**Comment by stevespaw** [comment]
@Chocobozzz Wow thanks for the quick fix. 6.3.1 so far all good!
