### ISSUE TITLE
Issue with POSTGRES_USER. Variable not being passed? 

### ISSUE THREAD

**Issue by tokenwizard** [Chocobozzz/PeerTube#6619]
### Describe the problem

In the .env file, the first few lines allow you to specify the POSTGRES_USER and POSTGRES_PASSWORD variables. 

A few lines down, it uses the values of those variable to set the PEERTUBE_DB_USERNAME and the PEERTUBE_DB_PASSWORD, meaning this should make both sets of credential variables match, right? 

![image](https://github.com/user-attachments/assets/ca12555b-5465-42ee-a30f-42cf50b17238)

When running ofr the first time on a fresh Ubuntu install (via Docker), I am geting errors that seem to indicate it isn't recognizing those variables being set:
![image](https://github.com/user-attachments/assets/aa4e5d53-1f51-4cd7-80e5-5c95dc0514e3)

If I docker inspect the postgres container, it looks like it recognizes the env variables picked up from the .env file, so I'm not sure why $PEERTUBE_DB_USERNAME =/= $POSTGRES_USER and PEERTUBE_POSTGRES_PASSWORD =/= POSTGRES_PASSWORD:

![image](https://github.com/user-attachments/assets/1d5c84d7-879e-4291-ac25-6cb8c52ee223)

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by tokenwizard** [comment]
FYI, adding the same values for each set of credential variables fixes the issue, but the way the default .env file is presented, it seems like it would be unnecessary to do this.

**Comment by tokenwizard** [comment]
Closing due to update above. I have Peertube running successfully. Just leaving this for anyone else who may have my same confusion.

**Comment by Chocobozzz** [comment]
What is your docker compose version?

**Comment by tokenwizard** [comment]
`docker-compose version 1.29.2, build unknown`
Running Ubuntu 22.04 on the server.

**Comment by Chocobozzz** [comment]
docker compose version is the main cause of your problems

As stated in the documentation (https://docs.joinpeertube.org/install/docker), peertube requires docker compose > v2
