### ISSUE TITLE
Video upload fails on v 6.3.1

### ISSUE THREAD

**Issue by gunchleoc** [Chocobozzz/PeerTube#6625]
### Describe the current behavior

When uploading a video, the upload fails immediately and I get a generic error message.

After changing `peertube-latest` back to v6.3.0, the uploads started working again

### Steps to reproduce

1. Publish
2. Choose a file to upload
3. The upload fails immediately

### Describe the expected behavior

Video file upload starts

### Additional information

* PeerTube instance:
  * URL: https://tbh.co-shaoghal.net
  * Version: 6.3.1
  * NodeJS version: v20.17.0
  * Ffmpeg version:  5.1.6-0+deb12u1  built with gcc 12 (Debian 12.2.0-14)

* Browser name, version and platforms on which you could reproduce the bug: Firefox 130.0.1 (64-bit) on Linux Mint
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): Nothing was written to either log

**Comment by Chocobozzz** [comment]
> Nothing was written to either log

Please see https://docs.joinpeertube.org/admin/logs to access logs from the admin and paste them so we can see what is the upload error on the server

**Comment by gunchleoc** [comment]
Looks like my HD temporarily ran full, and was just barely available again when I downgraded & tested again. I have now created some space & upgraded again and it's working now.

This also explains why the logs were empty.
