### ISSUE TITLE
administration->overview->videos->filter issue

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [Chocobozzz/PeerTube#6627]
### Describe the current behavior

duplicates states in the filter field if same states are selected several times

### Steps to reproduce

1. click on filter selectbox
2. select "local videos" state
3. select "without HLS" multiple times

### Describe the expected behavior

should not duplicate the state list in filter field

### Additional information

* PeerTube instance:
  * Version: 6.3.1

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/5f886402f5d17850d118d88b18624dd9cde83469
