### ISSUE TITLE
Download issue on new installs

### ISSUE THREAD

**Issue by stevespaw** [Chocobozzz/PeerTube#6629]
### Describe the current behavior

Older instances that have been upgraded - downloads work fine but the last 2 setups, I get this when trying to download from the administration. I have s3 storage but nothing is different and everything else seems to work fine.

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
<Key>streaming-playlists/hls/34cb8c52-126f-4be5-b002-95cff379331b/a458c24d-ece7-4f42-b15a-bd665ffdbd1a-1080-fragmented.mp4</Key>
<BucketName>bb1-video</BucketName>
<Resource>/bb1-video/streaming-playlists/hls/34cb8c52-126f-4be5-b002-95cff379331b/a458c24d-ece7-4f42-b15a-bd665ffdbd1a-1080-fragmented.mp4</Resource>
<RequestId>17F8D23A3169A2D9</RequestId>
<HostId>cbd6dd2b-9818-4914-9563-a238e79685ef</HostId>
</Error>

I just get "forbidden" when trying to download from the main player.

### Steps to reproduce

1. download from Admininstration
2. download from the page that contains a video.
3.

### Describe the expected behavior

Download properly

### Additional information

* PeerTube instance: 6.x
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by stevespaw** [comment]
OK Sorry, I have fixed most of them - Incorrect CDN settings....  One site is still having errors - I will keep looking. Sorry for the noise.

**Comment by ROBERT-MCDOWELL** [comment]
you should close the issue then...
