### ISSUE TITLE
Video channel owner image and markdown missing

### ISSUE THREAD

**Issue by DavidLibeau** [Chocobozzz/PeerTube#663]
* **PeerTube version or URL:** Beta.8

* **What is the expected behaviour?**
The owner image (`.actor-owner>img`) should appear and the Markdown of the description and "Support this channel" should be generated to HTML.
* **What do you see instead?**
![sans-titre](https://user-images.githubusercontent.com/11574966/41424915-d7c7b81e-6fee-11e8-9930-c7e54e8f9818.png)

**Comment by Chocobozzz** [comment]
Thanks:

Fixed in https://github.com/Chocobozzz/PeerTube/commit/53055a1124cbc2eaeeeeef21b19b0b46e96f23c5 and https://github.com/Chocobozzz/PeerTube/commit/c305467cd784345b87703a98c2cc7f0f7d8ba196
