### ISSUE TITLE
Error running on Docker for Windows install

### ISSUE THREAD

**Issue by Code-Quake** [Chocobozzz/PeerTube#6630]
### Describe the current behavior

I'm trying to install this using Docker Desktop for Windows following the instructions. After I run docker compose up I get this error in the web server container

nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/peertube.localhost/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/letsencrypt/live/peertube.localhost/fullchain.pem, r) error:10000080:BIO routines::no such file)

### Steps to reproduce

1. Run docker compose up
2.
3.

### Describe the expected behavior

A working peertube

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Please use the forum for PeerTube sysadmin/install related questions: https://framacolibri.org/c/peertube
