### ISSUE TITLE
Unable to Publish Videos – Account Requires Moderator Approval

### ISSUE THREAD

**Issue by broken-bucket** [Chocobozzz/PeerTube#6632]
### Describe the problem

I am running PeerTube on Gitpod, and I’m trying to publish videos. However, I am unable to do so because the platform requires me to sign in first. After creating an account and providing all the necessary details, I am informed that a moderator needs to approve the account before I can proceed.

Since I am running this instance locally and there are no external moderators, how can I bypass or manually approve the account so I can publish videos? Is there a configuration that allows auto-approval of accounts or any other workaround?

![image](https://github.com/user-attachments/assets/f634ed79-d619-43aa-bfb3-a95e84d45794)

**Comment by Chocobozzz** [comment]
Hi,

You already have an account: `root` / `test`: https://docs.joinpeertube.org/contribute/getting-started#prerequisites

After `root` login, you will be able to change the settings in `Administration` -> `Configuration`. I'm closing this issue but don't hesitate if you have more questions.
