### ISSUE TITLE
peertube viewer can't copy the URL with timing when video is in fullscreen

### ISSUE THREAD

**Issue by lm2lm2** [Chocobozzz/PeerTube#6637]
### Describe the current behavior

copy the URL without timing works well
copy the URL with timing works well when video is not in fullscreen
copy the URL with timing doesnt works when video is in fullscreen

### Steps to reproduce

1. launch a video
2. put it in fullscreen
3. try to copy/get the URL/link of the video, with the timing data at the end of the link

good luck!

### Describe the expected behavior

get the timing at the end of the URL even when video is in fullscreen

### Additional information

* PeerTube instance:
  * URL: https://video.ploud.jp/w/4TDTCgb8VGjkhbeUdsnuWy
  * Version:?
  * NodeJS version:?
  * Ffmpeg version:?

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
firefox 117.0.1 x64 in linux mint debian 5
i dont own a peertube server

**Comment by Chocobozzz** [comment]
Thanks for the issue! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/d96bc497427fdf2f18166bfcebadea751bed2936
