### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by RJGhugo** [Chocobozzz/PeerTube#6639]
> The address 2001:db8:: in this example is [reserved for use in documentation](https://en.wikipedia.org/wiki/Reserved_IP_addresses#IPv6). Replace it with a valid IPv6 network.
> 
> 
> 
> https://docs.docker.com/engine/daemon/ipv6/ 

 _Originally posted by @RJGhugo in [ccfd57e](https://github.com/Chocobozzz/PeerTube/commit/ccfd57e349c8bed557d6a60007f92f45d40879e3#commitcomment-147258187)_

Replace it with a valid IPv6 network.

https://docs.docker.com/engine/daemon/ipv6/

**Comment by Chocobozzz** [comment]
Hi,

Can you create a pull request to update the network?

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/f4339cfb72ac80c1c68059496da99797c4a0484b
