### ISSUE TITLE
6.3.0: New download modal gives forbidden error

### ISSUE THREAD

**Issue by SteelAlloy** [Chocobozzz/PeerTube#6643]
### Describe the current behavior

Since the 6.3.0 upgrade, users get to enjoy the new download modal, but they face `403 Forbidden` on my instance.

![image](https://github.com/user-attachments/assets/418d930e-24ae-497c-b3c6-c175ca301824)

The old panel still works though.
![image](https://github.com/user-attachments/assets/2235ca50-7a3b-40c2-9d13-403110764145)

The `dist/scripts/migrations/peertube-6.3.js` script has been executed with success, I don't know if it's related.

### Steps to reproduce

1. Upgrade to 6.3.0
2. Try to download a video from the new download modal

### Describe the expected behavior

Download videos

### Additional information

* PeerTube instance:
  * URL: https://itvplus.iiens.net
  * Version: 6.3.1

This Peertube instance is hosted on docker, with slight modifications from the Docker guide to run on Dokku.

I'd be happy to give additional information if needed

EDIT : The `403 Forbidden` error happens when clicking on `Download` 
![image](https://github.com/user-attachments/assets/a029a24b-3829-408e-a02b-d5706f63bd33)

**Comment by SteelAlloy** [comment]
Note : new videos are also affected

**Comment by EricGuic** [comment]
@SteelAlloy : I just tried to download this video without being logged in, and it works as expected, no error.
https://itvplus.iiens.net/w/a8Sw2aoHZEvbeFsbKDUiXw

**Comment by SteelAlloy** [comment]
@EricGuic thanks for pointing that out.
Public and unlisted videos can be downloaded, but unlisted and private videos are affected.

**Comment by Chocobozzz** [comment]
Thanks for the issue, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/0484b82fe3f6eab4cdbf21390b15ff8529ea3acc

**Comment by SteelAlloy** [comment]
> Hi, as there is a UI tag for this issue, I could suggest a simplification for this new download panel, which adds some confusions IMO. Why not have only 1 screen, with the expandable avanced infos ? See the pictures below. That way, there is no need to have the 2 options "Videos" and "Video files" in the dropdown menu on the top, which confuse me.
> 
> ![new download menu - simple view](https://private-user-images.githubusercontent.com/81166671/372828418-98b9c49e-db7b-474a-b87a-f45d3cef27a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDU0NTUsIm5iZiI6MTcyODMwNTE1NSwicGF0aCI6Ii84MTE2NjY3MS8zNzI4Mjg0MTgtOThiOWM0OWUtZGI3Yi00NzRhLWI4N2EtZjQ1ZDNjZWYyN2EzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDEyNDU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZWVhMjdlZmJjNjc1NTgzM2QwZmQ3MDQxM2ZkOTQwOTdmYjI3MDc0OWNlNmI5ODQ0Y2ZhNDIyZmU5MjdhNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MNr33aPz77y40bAtgqP3RsdMzzKQAQOOx28twy-CGp8)
> 
> ![new download menu - view with advanced options](https://private-user-images.githubusercontent.com/81166671/372828443-404115e4-b6bf-4826-b325-d5f069821fdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDU0NTUsIm5iZiI6MTcyODMwNTE1NSwicGF0aCI6Ii84MTE2NjY3MS8zNzI4Mjg0NDMtNDA0MTE1ZTQtYjZiZi00ODI2LWIzMjUtZDVmMDY5ODIxZmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDEyNDU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMjNhNThmMzkwMWZjNzM1YzBiNDBkYjlhNDg5ZWNmODc2NTY3MzdmYTVmZjBjZWYzMzYzMjlkOTEzYjU2ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LEnZ5cv7Zcwe7MnCT7NK-SY8AMrfTB7ZN0xLb-DXRUE)

@EricGuic I really like this idea, you should open a separate issue for it I think
