### ISSUE TITLE
Custom plugin install error

### ISSUE THREAD

**Issue by stevespaw** [Chocobozzz/PeerTube#6646]
### Describe the current behavior

This has worked perfectly until trying on a new clean 6.3.1 install, but now our plug-in will not install..
This is a big deal for us.

### Steps to reproduce

1. Install via CLI
peertube-cli plugins install --path /app/data/storage/plugins/company/myplug --url https://video.xxx.com --username root --password XXXXX

3.This error in the log:
error[10/1/2024, 11:00:03 AM] Cannot install plugin /app/data/storage/plugins/company/myplug, removing it...
{
  "err": {
    "stack": "Error: ENOENT: no such file or directory, open '/app/data/storage/plugins/node_modules/peertube-theme-myplug/package.json'",
    "message": "ENOENT: no such file or directory, open '/app/data/storage/plugins/node_modules/peertube-theme-myplug/package.json'",
    "errno": -2,
    "code": "ENOENT",
    "syscall": "open",
    "path": "/app/data/storage/plugins/node_modules/peertube-theme-myplug/package.json"
  }
}
4.  This seems to be added erroneously "/node_modules/peertube-theme-"

### Describe the expected behavior

The plug-in should install.
It might be connected to the path string that is added somewhere.

### Additional information

* PeerTube instance: New Install - docker based
  * URL:
  * Version: 6.3.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Can you paste the output of `ls  /app/data/storage/plugins/company/myplug`?

**Comment by stevespaw** [comment]
assets  client  main.js  package-lock.json  package.json  public

![image](https://github.com/user-attachments/assets/df210e3e-55bf-41ab-9df0-8f64b0545523)

**Comment by stevespaw** [comment]
![image](https://github.com/user-attachments/assets/5013ee77-6034-4b78-bac7-d30d9bfa5a23)

**Comment by stevespaw** [comment]
![image](https://github.com/user-attachments/assets/fc0d9392-ca7e-49e4-a199-dd3b0e92b66e)

**Comment by Chocobozzz** [comment]
Can you enable debug logs and paste more logs? I don't know what happens :thinking:
