### ISSUE TITLE
No HLS Transcode of "post live" videos

### ISSUE THREAD

**Issue by stevespaw** [Chocobozzz/PeerTube#6647]
### Describe the current behavior

We are doing "no transcode" lives right now. But we expect that these recurring/saved lives will be transcoded when the live is over, but now in version 6.3.1 that are not. Cations are created, but we have to manually trigger the "re-transcode HLS" . 
 We are doing the new split audio as default.
This is a blocker for us currently

### Steps to reproduce

1. Set Audio split in config.
2. Set no transcode live in config
3. Go Live 
4. Stop live
5.wait - see one HLS resolution (no Audio only)
6. Captions appear
7. No transcodes to VOD preset resolutions that are in the config.

### Additional information

* PeerTube instance: New and upgraded instances
  * URL:
  * Version: 6.3.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

> but now in version 6.3.1 that are not.

I'm surprised because PeerTube never re-transcoded lives

**Comment by stevespaw** [comment]
Ahh after discussion with one of our users. They usually did a "Studio" trim of the post live. Now they want to use it without trimming - so I guess this is now a feature request. 😄
