### ISSUE TITLE
Disable comment containing link

### ISSUE THREAD

**Issue by dausruddin** [Chocobozzz/PeerTube#6649]
### Describe the problem to be solved

Spammers registered and commenting links to scam and spam websites.
I kept deleting those comments and banning their accounts but they just keep registering a new account.
I keep banning their temporary email domains, then they started using gmail.
For some reasons, they can do tons of gmail accounts.

I also tried approving registration one-by-one, but there is no way to know a particular account is for spamming or legit usage.

### Describe the solution you would like

Disable URL in comment. At least no users will accidentally clicked on their spam links.

**Comment by Chocobozzz** [comment]
> Hiding comments from that specific user with the setting enabled?

No, the comments will be in the "Review queue". See https://docs.joinpeertube.org/use/setup-account#comments-on-your-videos

> As an administrator, is there a way to do this to all users?

No you can't, it's an uploader feature. I'm closing this issue in favour of https://github.com/Chocobozzz/PeerTube/issues/6658
