### ISSUE TITLE
Max FPS configuration can't be adjusted after running PeerTube 6.3.0

### ISSUE THREAD

**Issue by JacksonChen666** [Chocobozzz/PeerTube#6655]
### Describe the current behavior

`local-production.json` overrides the max FPS in `production.yaml`, which would be fine, if the value was exposed in the user interface. It's not. You must adjust `local-production.json` as well.

### Steps to reproduce

1. Run a PeerTube instance with >6.3.0 and max FPS configured to something like 60
2. Change it to 120 or 144 or whatever else
3. It's not affected (Transcoding the video or replacing it)

### Describe the expected behavior

Max FPS value should be adjustable via web interface or `production.yaml`, and should not require adjusting `local-production.json` as well.

### Additional information

* PeerTube instance:
  * URL: https://videos.jacksonchen666.com (I do not have a public video that's 144 fps though)
  * Version: 6.3.0
  * NodeJS version: 20.17.0
  * Ffmpeg version: 6.1.2 on server, 6.1.1 on 1 remote runner

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! I added the setting in the admin in https://github.com/Chocobozzz/PeerTube/commit/7c3eaf868c7707e9f38e0718195bcfd4f94eaa16
