### ISSUE TITLE
Cannot retroactively re-transcode higher FPS videos with original files

### ISSUE THREAD

**Issue by JacksonChen666** [Chocobozzz/PeerTube#6656]
### Describe the current behavior

With PeerTube's new "Store original files" option enabled, then adjusted max FPS, you can click the "Run HLS transcoding" button and it will not increase the FPS of any existing videos. You must replace the video for it to work.

### Steps to reproduce

0. Some instance config: Original files stored, uploaded high FPS video, instance configured with low FPS limit (e.g. 60), HLS only, no separate audio, remote runners
1. Instance adjusts FPS to be higher (accounting for #6655)
2. Try to transcode a video that has the original file ("Run HLS transcoding")
3. Nope, still low FPS

### Describe the expected behavior

I expected the video to increase FPS after adjusting the instance FPS (#6655 accounted for) by clicking on the "Run HLS transcoding" button.

### Additional information

* PeerTube instance:
  * URL: https://videos.jacksonchen666.com
  * Version: 6.3.0
  * NodeJS version: 20.17.0
  * Ffmpeg version: 6.1.2 on server, 6.1.1 on runner

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Closing in favour of https://github.com/Chocobozzz/PeerTube/issues/6657
