### ISSUE TITLE
Mismatched time on live replays

### ISSUE THREAD

**Issue by stevespaw** [Chocobozzz/PeerTube#6659]
### Describe the current behavior

The "published" time is the correct time based on the instance settings it does not match the time generated on the replay clip.

### Steps to reproduce

![image](https://github.com/user-attachments/assets/7cedd07d-cbf6-46a6-a51c-0ced5df7c1ed)

### Describe the expected behavior

Where is the time for the replay name generated?

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

The date in the live name is when the live started, using the server timezone. Is your web browser in a different time zone to your server?

**Comment by Chocobozzz** [comment]
The date in the name is the time the live was started, the published at is the time the replay was published. Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/6162
