### ISSUE TITLE
Custom user quotas

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#666]
Unless I'm missing something, there's no way to enter a custom universal quota after first run/at all for individual accounts. There's only the preset options in the admin panel.

**Comment by lil5** [comment]
**1.**
You could try digging in `server/controllers/api/users/index.ts`
This includes:
- `updateUser` with req including a videoQuota
- `listUsers` to loop threw

**2.**
You could cycle threw all accounts with `listVideoAccountChannels` in `server/controllers/api/accounts.ts`,
then change the `videoQuota` in `server/controllers/api/config.ts`

*First* you will need to find the connections from `server/tools/cli.ts` to the server.

**Comment by McFlat** [comment]
@lil5 I don't mean to be a grammar nazi, just trying to help you out bro. I think you mean the word through or thru

**Comment by lil5** [comment]
@McFlat changed, still a grammar nazi but thats cool xD

**Comment by zacharystenger** [comment]
I'm planning to work on this issue. I was picturing the dropdowns would have a 'custom' option which, when selected, would make two items appear to the right of the dropdown: a number input field and a dropdown for selecting MB or GB. Open to suggestions as this could definitely be handled differently

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/21e493d4d8acb7a650eff3a30cd7e086b3cb8a28
