### ISSUE TITLE
Can we remove the yarn depedency?

### ISSUE THREAD

**Issue by Jibec** [Chocobozzz/PeerTube#667]
Hi,

we are packaging PeerTube for YunoHost and it works fine, thanks for your great work :)
https://github.com/YunoHost-Apps/peertube_ynh/

Your application requires Yarn, which is not available in default Debian packages and makes a longer/bigger installation.

I understand the project Funkwhale is using the same dependency, but release compiled files, making yarn mandatory only for contributors.
See: https://docs.funkwhale.audio/installation/debian.html#download-latest-funkwhale-release and https://code.eliotberriot.com/funkwhale/funkwhale

Do you think it would be possible to do the same for PeerTube?

**Comment by Chocobozzz** [comment]
We already provide compiled client files.

yarn is required to download server dependencies, so I'm sorry but we cannot remove it.

**Comment by Nautigsam** [comment]
Hey, actually maybe the question of moving away from yarn can be asked. NPM team did a great job implementing `package-lock.json` and speeding up install step which is, if I'm right, the main reasons why people use yarn. Plus, it seems that yarn [comes with its own problems](https://mixmax.com/blog/to-yarn-and-back-again-npm).

**Comment by Chocobozzz** [comment]
Maybe they did a great job, but some time ago I lost a lot of time because of npm bugs/no cache/no lockfile. I switched to yarn, and I (and sysadmins) never had a problem with it. yarn works well, we are happy with it, and we don't have time to change tools we are satisfied with.

**Comment by rezonant** [comment]
For what it's worth, it's still possible to use npm to install peertube's dependencies with one or two tweaks to the package.json deps, and this is what I do when working on PeerTube because I don't use yarn, but I agree with Chocolate here that PeerTube has too much going on to switch officially right now
