### ISSUE TITLE
Upgrade to a specific version instead of "big jump"

### ISSUE THREAD

**Issue by Flagelmann** [Chocobozzz/PeerTube#6676]
### Describe the problem

Hello,

I was wondering if it would be possible to upgrade from version 6.1.0 to version 6.2.0 before doing the "big jump" to the latest.

It would be helpful to not introduce issues to the instance due to the latest changes.

Many thanks and kind regards.

**Comment by Chocobozzz** [comment]
Hi,

If you follow important notes of each major release you can upgrade from 6.1.x to 6.3.2

**Comment by Flagelmann** [comment]
Hello,

ok, I know and I usually checked those notes before upgrading, but my question is different.

If I want first to upgrade to version 6.1.0 to 6.2.0, for example, the only thing I can do right now is the following:

cd /var/www/peertube/peertube-latest/scripts && sudo -H -u peertube ./upgrade.sh

My question is: how do I force the upgrade.sh to be limited to upgrade up to 6.2.0 and not just getting the latest available?

Is it possible to modify the upgrade.sh to specify a param to define which is the target version instead of being force to upgrade by default to latest version?

Many thanks

**Comment by Chocobozzz** [comment]
> My question is: how do I force the upgrade.sh to be limited to upgrade up to 6.2.0 and not just getting the latest available?

Unfortunately it's not possible, but yes you can try to manually edit `upgrade.sh` to specify the URL of 6.2.0 release

**Comment by Flagelmann** [comment]
Hello,

just to inform that I have upgrade successfully from 6.1.0 to 6.2.1 just by assigning to the VERSION variable in upgrade.sh the version that I wanted to force.

All good.

Thanks
