### ISSUE TITLE
Quota preset imprecision

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#668]
Version: beta.8
NodeJS: v8.11.2

This is taken from the user list.

![image](https://user-images.githubusercontent.com/28912578/41504537-e584af0a-71b7-11e8-9c32-0505aa66b02a.png)

**Comment by Chocobozzz** [comment]
Thanks @XenonFiber, fixed in https://github.com/Chocobozzz/PeerTube/commit/a2788c698eae1d2bfeedb06a1c4c3fb82b5e30a8
