### ISSUE TITLE
Homepage OG image tag missing

### ISSUE THREAD

**Issue by Mike35538** [Chocobozzz/PeerTube#6680]
### Describe the current behavior

Currently, the home page does not have a meta tag for og:image, even if the instance has a Banner image.

### Steps to reproduce

1. Past the URL https://peertube2.cpy.re/about/instance into the FB OG debugger at https://developers.facebook.com/tools/debug
2. Even though the instance has a banner set, the OG image is missing.

### Describe the expected behavior

When an instance has a banner set, use the banner for the og image tag on the home page, about, and custom homepage.
<meta property="og:image" content="https://peertube2.cpy.re/lazy-static/banners/772ff0ae-6cb5-4d1c-b89b-ace85eece196.jpg">

**Comment by Chocobozzz** [comment]
Thanks, implemented in https://github.com/Chocobozzz/PeerTube/commit/54adc6f038758e3b7a759f9a5c2a71d0a6b9959b
