### ISSUE TITLE
can't download plugins

### ISSUE THREAD

**Issue by DbIsDb** [Chocobozzz/PeerTube#6682]
### Describe the current behavior

Hello,

I started to use peertube a few days ago.

i wanted to get live chating to start but when i try to download a plugin i get an error.

hope step to reproduce and additional information is helpful

nginx(swag) config in the first pastbin.

### Steps to reproduce

1.create a stack on portainer, replace all .env with stack.env (to make env variable work)
2. comment all things that need to be commented to use cutom proxy or local test (webserver, assets, etc..)
3. use swag proxy with default nginx conf or a default swag template
4, try to istall a plugin 

### Additional information

* PeerTube instance:
  * URL:https://it.redcorp.me
  * Version: latest

* Browser name, version and platforms on which you could reproduce the bug: Firefox
* nginx : https://pastebin.com/PpJnznsH
* logs ; https://pastebin.com/HjUwp3Wz

**Comment by Chocobozzz** [comment]
Hi,

I think there is a network issue in your container: `An unexpected error occurred: \"https://registry.yarnpkg.com/peertube-plugin-transcoding-custom-quality: connect ENETUNREACH 2606:4700::6810:1e22:443` 

Disabling IPv6 should fix your issue.
