### ISSUE TITLE
GUI issue - change ownership field

### ISSUE THREAD

**Issue by stevespaw** [Chocobozzz/PeerTube#6685]
### Describe the current behavior

Ownership Text color is the same as text box. Both say "Hello World"
![image](https://github.com/user-attachments/assets/d720513b-35e7-4479-a898-11998cd372e2)
![image](https://github.com/user-attachments/assets/9a7045c8-8d21-4c6a-b041-0d8456dbd142)

### Steps to reproduce

1. Videos - Change ownership
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version: 6.3.2
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by JelenaDinic** [comment]
I would like to fix this issue. Can you assign it to me?

**Comment by stevespaw** [comment]
this also happens here: on embed start and stop
![image](https://github.com/user-attachments/assets/3ba6c6bb-a818-45b1-8644-310b8630358e)

**Comment by Chocobozzz** [comment]
Hi & thanks,

This is already fixed in develop and will be released in PeerTube v7 (you can test public pages on https://peertube2.cpy.re/)
