### ISSUE TITLE
move-object-to-storage jobs stuck until Peertube restarted

### ISSUE THREAD

**Issue by dausruddin** [Chocobozzz/PeerTube#6686]
### Describe the current behavior

Sometimes, unpredictable, `move-to-object-storage` job got stuck, then new jobs after that will just queuing indefinitely until I restarted Peertube.

![image](https://github.com/user-attachments/assets/196a25f6-7eee-48e2-84c7-620a094c7791)

This is the log for job 8514:
```
Job: 8514
Type: move-to-object-storage
Processed on 10/22/24, 5:57:36.476 AM
Finished on -

{
  "videoUUID": "f0a01bf5-f9da-4ad3-9362-01c90232e83e",
  "isNewVideo": true,
  "previousVideoState": 2
}

Error: Timeout
    at Timeout.<anonymous> (file:///var/www/peertube/versions/peertube-v6.3.2/packages/core-utils/dist/common/promises.js:12:42)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7)
```

### Steps to reproduce

1. Keep uploading once every few hours until the issue happen
2. Restart Peertube to fix the issue temporarily, until it happens again

### Describe the expected behavior

`move-to-object-storage` successfully executed, and video published.

### Additional information

* PeerTube instance:
  * URL: private
  * Version: 6.3.2
  * NodeJS version: v20.18.0
  * Ffmpeg version: 5.1.6-0+deb12u1

* Browser name, version and platforms on which you could reproduce the bug: Firefox 131.0.2 (64-bit), ArchLinux
* Link to browser console log if relevant: N/A
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): N/A

**Comment by Chocobozzz** [comment]
Please enable debug logs and paste peertube logs around the time the job timeout. You can also run [parse-log](https://docs.joinpeertube.org/maintain/tools#parse-logs) command using object storage tags:

```
cd /var/www/peertube/peertube-latest
sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run parse-log -- --tags object-storage --tags move-object-storage
```

**Comment by Chocobozzz** [comment]
> I am already running my instance with debug logs enabled. parse-log command returns no log, perhaps because it is no longer in the log file.

You can also use the admin log web interface that can search in multiple log files

**Comment by Chocobozzz** [comment]
Thanks to multiple gigabytes of logs sent by @TankieTanuki, I think I was able to find the bug.

It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/10c5f44e1a915e60d1d55cb5898efd807008a477

See https://github.com/aws/aws-sdk-js-v3/issues/6691 for more information
