### ISSUE TITLE
Waiting for parrent job while there free runners to process transcoding jobs

### ISSUE THREAD

**Issue by ilfarpro** [Chocobozzz/PeerTube#6688]
### Describe the problem to be solved

For some reason, when I upload video and use runner to transcode it, I have to wait while highest resolution version is transcoded. Only then other free runners can process video. This limitation seems artificial, because every time it downloads highest resolution from API to transcode, so there is no relation to highest resolution and no need to wait while it finishs processing.

![image](https://github.com/user-attachments/assets/5ffc5a53-c74a-498f-99ab-e4afcd8330ee)

![image](https://github.com/user-attachments/assets/1699f35b-94c7-4f04-b7c6-cedab2d7ebca)

In previous versions of Peertube when transcoding of highest resolution is done it would populate all runners with other resolution jobs, but now for some reason is not happening and runner is just waiting. Please, fix this

![image](https://github.com/user-attachments/assets/07479113-b587-495c-bae7-06eda15cb5c9)

### Describe the solution you would like

Don't block other transcoding jobs unless it's absolutely necessary.

I tested this on my testing instance which runs Peertube 6.3.2 and latest version of peertube-runner package.

**Comment by Chocobozzz** [comment]
Hello,

PeerTube (in runners and local transcoding jobs) first optimize the video and then run the lower resolution jobs. We have to do that because we can have playback issues on some devices if we don't do the optimize step first.

**Comment by ilfarpro** [comment]
> Hello,
> 
> PeerTube (in runners and local transcoding jobs) first optimize the video and then run the lower resolution jobs. We have to do that because we can have playback issues on some devices if we don't do the optimize step first.

After optimization of video in previous versions of Peertube it would assign other resolutions jobs to all available runners, but now it transcodes only one resolution at a time even if other resolutions shouldn't be blocked by "waiting parrent job" message. Could you please recall if any recent commits might change behaviour of job queue?

It wasn't like that before.

**Comment by ilfarpro** [comment]
Sorry I wasn't able to reopen issue, so I created another one with additional info https://github.com/Chocobozzz/PeerTube/issues/6689

**Comment by Chocobozzz** [comment]
Please try to upgrade to peertube 6.3.2

**Comment by ilfarpro** [comment]
> Please try to upgrade to peertube 6.3.2

I was testing this on 2 different instances of Peertube running version 6.3.2, can confirm this behavior is consistent

**Comment by Chocobozzz** [comment]
Are you sure? Because https://vanilla.22x22.ru/about/instance is 6.3.0. If you reproduce the bug with another instance, please paste the screens of the jobs of that instance so I can understand what happens.

**Comment by ilfarpro** [comment]
> Are you sure? Because https://vanilla.22x22.ru/about/instance is 6.3.0. If you reproduce the bug with another instance, please paste the screens of the jobs of that instance so I can understand what happens.

I originally tested in 6.3.2 and then downgraded to 6.0.0 to see if it helps, but it didn't.

I think this issue can be reproduced if optimize-web-video job fails and then I manually start HLS transcoding. No hard evidence yet
