### ISSUE TITLE
"Waiting for parrent job to finish" even when optimization is done

### ISSUE THREAD

**Issue by ilfarpro** [Chocobozzz/PeerTube#6689]
### Describe the current behavior

When web-video-optimization job is done it transcodes only one resolution at a time and my available runners just stay idle.
In previous versions of Peertube it would assign jobs to all free runners once web-optimization is done.
I tried to downgrade to Peertube 6.0.0 from 6.3.2 but it didn't helped.
This issue was reproduced on my production and testing instance.

### Steps to reproduce

1. Install Peertube 6.3.2
2. Add 2 runners
3. Upload video
4. Watch how jobs are processed. You will see after web-video optimization that job is assigned only to 1 runner and other one will stay idle. Same happens for other resolution. For some reason only one runner does jobs. 

When I was testing, I checked that both runners are healthy and can process jobs by temporarily disabling them to see that they will get jobs to transcode.

### Describe the expected behavior

Once web-video-transcoding is done, all free runners should get jobs to transcode different resolution in parallel, not one by one. 

### Additional information

* PeerTube instance:
  * Version: 6.3.2
  * NodeJS version: v20
  * Ffmpeg version: 7.0.1

**Comment by ilfarpro** [comment]
Sorry I wasn't able to reopen previous issue, so I created another one with additional info https://github.com/Chocobozzz/PeerTube/issues/6688

**Comment by Chocobozzz** [comment]
We can still continue the discussion even if the issue is closed :)
