### ISSUE TITLE
documentation errors; devtoolset-6

### ISSUE THREAD

**Issue by EndeavourAccuracy** [Chocobozzz/PeerTube#669]
These are inconsistent:

https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/dependencies.md#centos-7
$ **sudo** scl devtool**set**-6 bash

https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#prepare-peertube-directory
$ scl **enable** devtool-6 bash

_Both_ are currently incorrect.

**Comment by daftaupe** [comment]
Hello @EndeavourAccuracy,

from https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/, the correct command to run is : scl enable devtoolset-7 bash

I will fix the documentation accordingly.

**Comment by Chocobozzz** [comment]
Thanks @daftaupe
