### ISSUE TITLE
PeerTube Incompatible browser

### ISSUE THREAD

**Issue by PinSeppe69** [Chocobozzz/PeerTube#6693]
### Describe the current behavior

I get this message when I open PeerTube with google chrome:
"Sorry, but it looks like PeerTube is not compatible with your web browser.
Try the latest version of [Mozilla Firefox]... ".

However, this does not seem to be true, because chrome also works fine on the PeerTube site.

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

What is your web browser and version? What is the PeerTube website URL?

**Comment by PinSeppe69** [comment]
Browser: Chrome, Versione 130.0.6723.70 (Build ufficiale) (a 64 bit);
O.S.: Windows 11 Pro, Versione 23H2 (a 64 bit).

Il problema si verificava su tutto il sito.
Oggi non si verifica più questo problema e non sono stato io a risolverlo.

Grazie comunque per l'interessamento.

**Comment by Chocobozzz** [comment]
Please provide the website URL so I can try to reproduce

**Comment by PinSeppe69** [comment]
https://peertube.it/
![Immagine 2024-10-28 140720](https://github.com/user-attachments/assets/e8e321a5-9421-4def-859e-676aec7ec6f7)

**Comment by Chocobozzz** [comment]
Thanks! Can you paste messages in your web browser console? https://balsamiq.com/support/faqs/browserconsole/#google-chrome
