### ISSUE TITLE
Preview and thumbnail sizes are not limited

### ISSUE THREAD

**Issue by fflorent** [Chocobozzz/PeerTube#670]
* **PeerTube version or URL:** 1.0.0b8 → https://skeptikon.fr
* **Browser name/version:** Firefox v60
* **NodeJS version:** v8.11.2

### Steps to reproduce
1. Upload some video
2. Upload this image as a thumbnail (>7Mb weighed): https://upload.wikimedia.org/wikipedia/commons/3/3b/L%27Ile_d%27Ouessant_face_au_vent_d%27Automne.jpg
3. Same for the preview
4. Publish

* **What is the expected behaviour?** The description of the thumbnail and preview fields states that the image cannot be over 2Mb. Or the statement be removed and it should work.
* **What do you see instead?** 
   * On my workstation: The image is normally uploaded
   * On [Skeptikon](https://skeptikon.fr) (reported by a user): The upload fails with "Bad Gateway" (NB: skeptikon is behind a Traefik reverse proxy).

* **Browser console log if useful (Gist/Pastebin...):** none
* **Server log if useful (Gist/Pastebin...):** none (yup, sorry, I don't see anything…)

Cheers,
Florent

**Comment by Chocobozzz** [comment]
Thanks! I think it should be fixed: https://github.com/Chocobozzz/PeerTube/commit/0c237b19fdf9c614293c1442f0ab95a81ce05735
