### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by RJGhugo** [Chocobozzz/PeerTube#6704]
### Describe the current behavior

Wrong IPv6: **2001:db8:2::42**

`    networks:`
`      default:`
`        ipv4_address: 172.18.0.42`
`        ipv6_address: 2001:db8:2::42`

`networks:`
`  default:`
`    enable_ipv6: true`
`    ipam:`
`      driver: default`
`      config:`
`      - subnet: 172.18.0.0/16`
`      - subnet: fdab:e4b3:21a2:ef1b::/64`

### Additional information

support/docker/production/docker-compose.yml

**Comment by Chocobozzz** [comment]
Oup's, thank you! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/e0f39d7995b07c4a2757716a684fcd6458750056

Please test!
