### ISSUE TITLE
Questions - after sync delete original files

### ISSUE THREAD

**Issue by chefblogger** [Chocobozzz/PeerTube#6706]
### Describe the current behavior

i have synchronised my peertube with my youtube - it worked great.

on peertube i reduce the videos to 720p - can i delete the original files somewhere to free up space - if so how?

Unfortunately I can't find any instructions or path to the folder with the original videos

thank you for your answers :)

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

Please use the [forum](https://framacolibri.org/c/peertube) for PeerTube related questions.

You can delete specific video files in `Administration` -> `Overview` -> `Videos`
