### ISSUE TITLE
Not able to install from user with sudo rights

### ISSUE THREAD

**Issue by SouceCalve** [Chocobozzz/PeerTube#6708]
### Describe the problem

I can't deploy my instance because I don't have access to peertube-latest: the link is created correctly, but the user doesn't see it as a directory, only as a file/broken link. I've already prepared a solution in the pull request, although it requires a root user to work.

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by SouceCalve** [comment]
Found a solution with help of bash autocorrection.
Its not working under normal user with sudo rights, only root.
This command is wrong:
sudo -u peertube ln -s versions/peertube-${VERSION} ./peertube-latest
corrected command:
sudo -u peertube ln -s versions/peertube-${VERSION}/ peertube-latest
НОВОЕ
[18:04]
I've already forked the repo and modified the docs, I'll be sending out a pull request soon.

**Comment by SouceCalve** [comment]
Mentioned on forum and discord already.

**Comment by Chocobozzz** [comment]
Moving this discussion on https://framacolibri.org/t/install-stuck/23167
