### ISSUE TITLE
Different video codecs with the new download interface

### ISSUE THREAD

**Issue by SteelAlloy** [Chocobozzz/PeerTube#6709]
### Describe the desired information/correction

Hi ! 

Since the introduction of the new interface, I've noticed noticeable differences between downloaded files.

<details>
  <summary>Interfaces</summary>
  <img src="https://github.com/user-attachments/assets/4510c31f-30bb-40ab-a78f-bf2350781685">
  <img src="https://github.com/user-attachments/assets/64c07803-2159-4cc4-ac16-a5f395344a42">
</details>

The files generated by the "Video" panel contains more codecs (and that's a good thing)

```diff
# Analysis with MP4Box
< Major Brand isom - version 512 - compatible brands: isom iso6 iso2 avc1 mp41
---
> Major Brand iso5 - version 512 - compatible brands: iso5 iso6 mp41
```

To my knowledge, this information is not documented. Perhaps you could include it in the panel?

Or fuse the two panels (#6663) but if that's the case please keep the new codecs.

## Note

How did I discover these differences? It turns out that videos downloaded with the old panel (video files) are not readable with Premiere Pro. And that annoyed a lot of the members of my instance.

But with the introduction of the new panel, the videos are now readable because the codecs are not the same !

**Comment by SteelAlloy** [comment]
Hello and thank you
It was rather a request for documentation, all this information is not in the panel.

**Comment by Chocobozzz** [comment]
> It was rather a request for documentation, all this information is not in the panel.

Okay thanks I get it! Unfortunately since we mux the file on the fly we don't know in advance what the codec will be, it may depend on the ffmpeg version
