### ISSUE TITLE
Unlisted videos bypass user account setting "validation by moderators"

### ISSUE THREAD

**Issue by agru** [Chocobozzz/PeerTube#6712]
### Describe the current behavior

If a user has not set the option "User bypasses video validation by moderators" in her/his account the videos can anyway be shared by the user when setting the option "Unlisted" at the video. This can lead to data protection and copyright problems with an unmoderated video.

### Steps to reproduce

1. Create user account and do not check the box beneath "User bypasses video validation by moderators"
2. As this user upload a video and set the video privacy to "Unlisted"
3. Create a share link / embed code and test that now this video can be used without authentication or password although the user is moderated.

### Describe the expected behavior

A user that is moderated should not have the possibility to publish videos this way.

### Additional information

* PeerTube instance:
  * Version: 6.3.2

**Comment by agru** [comment]
Instance-URL is [pt01.lehrerfortbildung-bw.de](https://pt01.lehrerfortbildung-bw.de/) and there is no plugin installed

**Comment by Chocobozzz** [comment]
Thank you very much :pray: 

It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/af7ffcf813a043c2953608ad43aaa9f3e9214afa

**Comment by agru** [comment]
Great! Thank you very much for your work! Then I'm going to wait for the next release to have this live on my server.
