### ISSUE TITLE
Publication date format improvements

### ISSUE THREAD

**Issue by FediVideos** [Chocobozzz/PeerTube#6713]
### Describe the problem to be solved

At the moment dates (at least on English language version) are shown as MM/DD/YY

This has a couple of drawbacks:
-Most countries (including many English-speaking ones like UK, Ireland, Australia etc) use DD/MM instead of MM/DD
-The two-digit year causes e.g. videos originally published in 1924 to look like they were published in 2024

(If anyone is wondering why people would upload stuff published in the 1920s, lots of films and animations are from that period and many are now entering the public domain due to the 95 year limit on US films.)

### Describe the solution you would like

Changing format to DD/MM/YYYY would be easiest, but this might still leave problems in MM/DD countries. At least showing YYYY in either format would be very helpful :)

Alternatively, could there be options for instance admins on how they display publication dates?

**Comment by Chocobozzz** [comment]
Hi,

We display dates based on the web browser locale. But I understand it can be confusing. 

> At the moment dates (at least on English language version) are shown as MM/DD/YY

Can you list where are displayed such dates?

**Comment by FediVideos** [comment]
I have Firefox set to en-gb, is that where it is deriving date format from? en-gb should be dd/mm though? It's only en-us that uses mm/dd.

If this is a browser issue should I close issue here and open issue on Firefox?

![PeerTubeDates](https://github.com/user-attachments/assets/bc38590b-9ee5-40f2-a17f-e7245bdadb2d)

**Comment by Chocobozzz** [comment]
Thanks! I think it's a PeerTube bug. Will investigate

**Comment by FediVideos** [comment]
Obviously this is very low priority, no worries if you don't have time, maybe I shouldn't have opened this issue. Apologies! I didn't realise it was in the browser, it thought this was something small and simple to do with PeerTube directly.

By the way, it does seem to definitely be the browser:

On Firefox on Linux, when setting browser to a non-English language PeerTube displays the date correctly as DD/MM/YYYY

On Safari on iOS, when setting browser to a non-English language PeerTube  displays the date correctly as DD/MM/YYYY

**Comment by Chocobozzz** [comment]
> maybe I shouldn't have opened this issue

You always should when you have a problem with peertube :) We should rely on the web browser local (en-UK, en-US etc.) to fix the bug. We currently use the web client page locale for now but we only have one locale for english (en-US), and so English people have this bug

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/57d9e96d63a43889e058edf6b502a3d86285eb4b

**Comment by FediVideos** [comment]
Confirmed as fixed! Sorry I didn't post earlier about this, thank you so much!
