### ISSUE TITLE
Repository bind-mounted inside docker container

### ISSUE THREAD

**Issue by PisoniLuca** [Chocobozzz/PeerTube#6714]
### Describe the problem

Hi, i'm getting some troubles with a fresh installation inside a custom docker container. So, i ' m  trying to mount in **bind mode** the repository directly inside the container, and then execute in dev mode via **npm run dev**.

First, i've got the missing concurrency module, already solved, but now i' m getting:

```
2024-11-08 17:13:31 [0] Error: Cannot find module '/app/client/node_modules/.bin/ng'
2024-11-08 17:13:31 [0]     at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
2024-11-08 17:13:31 [0]     at Module._load (node:internal/modules/cjs/loader:981:27)
2024-11-08 17:13:31 [0]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
2024-11-08 17:13:31 [0]     at node:internal/main/run_main_module:28:49 {
2024-11-08 17:13:31 [0]   code: 'MODULE_NOT_FOUND',
```
Yes, i know that development containers are not provided from this project, but i want to install and edit in live mode without install bullshit on my computer, and, in the meantime, move my installation between various machines. 

There is a way to do it?
 

### Additional information

* PeerTube instance URL:
* PeerTube version:
* NodeJS version:
* Ffmpeg version:
* Redis version:
* PostgreSQL version:

**Comment by ilfarpro** [comment]
Hello! Can you please provide your docker-compose.yml or docker run command and structure of folders

**Comment by PisoniLuca** [comment]
Thanks for your answers, @ilfarpro .

This is my docker compose file:

`version: '3.8'
services:

  # You can comment this webserver section if you want to use another webserver/proxy or test PeerTube in local
  webserver:
    image: chocobozzz/peertube-webserver:latest
    # If you don't want to use the official image and build one from sources:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.nginx
    env_file:
      - .env
    ports:
     - "80:80"
     - "443:443"
    volumes:
      - type: bind
        # Switch sources if you downloaded the whole repository
        source: ./PeerTube/support/nginx/peertube
        #source: ./docker-volume/nginx/peertube
        target: /etc/nginx/conf.d/peertube.template
      - assets:/var/www/peertube/peertube-latest/client/dist:ro
      - ./docker-volume/data:/var/www/peertube/storage
      - certbot-www:/var/www/certbot
      - ./docker-volume/certbot/conf:/etc/letsencrypt
      - ./certs:/etc/letsencrypt/live/localhost
    depends_on:
      - peertube
    restart: "always"

  # You can comment this certbot section if you want to use another webserver/proxy or test PeerTube in local
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./docker-volume/certbot/conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    restart: unless-stopped
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;"
    depends_on:
      - webserver

  peertube:
    # If you don't want to use the official image and build one from sources:
    build:
      dockerfile: ./Dockerfile
    #image: chocobozzz/peertube:production-bookworm
    # Use a static IP for this container because nginx does not handle proxy host change without reload
    # This container could be restarted on crash or until the postgresql database is ready for connection
    networks:
      default:
        ipv4_address: 172.18.0.42

    env_file:
      - .env

    ports:
      - "1935:1935" # Comment if you don't want to use the live feature
      - "3000:3000" # Client dev port
      #- "9000:9000" # Uncomment if you use another webserver/proxy or test PeerTube in local, otherwise not suitable for production
    volumes:
      - ./PeerTube:/app
      - ./entrypoint.sh:/app/entrypoint.sh
    depends_on:
      - postgres
      - redis
      - postfix
    #restart: "always"
    working_dir: /app
    entrypoint: ./entrypoint.sh


  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - ./docker-volume/db:/var/lib/postgresql/data
    restart: "always"

  redis:
    image: redis:6-alpine
    volumes:
      - ./docker-volume/redis:/data
    restart: "always"

  postfix:
    image: mwader/postfix-relay
    env_file:
      - .env
    volumes:
      - ./docker-volume/opendkim/keys:/etc/opendkim/keys
    restart: "always"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
volumes:
  assets:
  certbot-www:
`

And this is my entrypoint.sh

`#!/bin/bash


chown -R peertube:peertube .
yarn install --pure-lockfile
npm run dev

exit`

**Comment by Chocobozzz** [comment]
Hello,

Please use the forum for PeerTube related questions: https://framacolibri.org/c/peertube

You can also use [Gitpod](https://docs.joinpeertube.org/contribute/getting-started#online-development) to contribute to PeerTube without having to install it
