### ISSUE TITLE
Doc does not explain where remote runner registration token comes from

### ISSUE THREAD

**Issue by rptb1** [Chocobozzz/PeerTube#6715]
### Describe the desired information/correction

https://docs.joinpeertube.org/maintain/tools#register says:
```
peertube-runner register --url http://peertube.example.com --registration-token ptrrt-... --runner-name my-runner-name
```
but there is no documentation on the page about where the registration token comes from.  Using the command as-is (with a valid URL) gets:
```
The server responded: "Registration token is invalid".
```
so it must come from somewhere, but where?

The documentation should say (or refer to) where to get the token.

If someone explains the answer I could make an edit.  Thanks!

**Comment by ilfarpro** [comment]
Hello! In order to get registration token, navigate to Administration - System, choose Remote Runners in dropdown menu, then click Runner Registration Tokens button in the right side of page.

![image](https://github.com/user-attachments/assets/1ef168c6-4014-469b-8fbd-6a6706eb64ad)

**Comment by rptb1** [comment]
Thank you!

And before that drop-down menu will appear, you must [enable Remote Runners](https://docs.joinpeertube.org/admin/remote-runners#enable-remote-runners) in Administration -> Configuration -> VOD Transcoding, ticking this box:
![Screenshot from 2024-11-10 11-14-03](https://github.com/user-attachments/assets/35cc7a32-02e8-4d71-b4bc-3455fecaa565)

I will see about updating the document with a reference.

**Comment by Chocobozzz** [comment]
Hi and thanks for the issue.

You can find the doc on how to use peertube runners on https://docs.joinpeertube.org/admin/remote-runners

I added the link in the tools documentation in https://github.com/Chocobozzz/PeerTube/commit/81f19ef47c12e132fba92afcef53f02871b3f554
