### ISSUE TITLE
"Edit this page" link does not allow edit

### ISSUE THREAD

**Issue by rptb1** [Chocobozzz/PeerTube#6716]
### Describe the desired information/correction

If you click on the "Edit this page" link at e.g. https://docs.joinpeertube.org/maintain/tools#register then it goes to https://framagit.org/framasoft/peertube/documentation/-/blob/master/docs/maintain/tools.md which does not allow you to edit the page.  The last commit message there says "moved to vitepress".

So the "edit this page" links need to be updated, or removed.

Thanks!

**Comment by rptb1** [comment]
Background: I'm trying to provide an edit to resolve https://github.com/Chocobozzz/PeerTube/issues/6715

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://framagit.org/framasoft/peertube/documentation/-/commit/49000d935edbe03f29a1f021596abf1a30df52f8
