### ISSUE TITLE
Edit captions in the web interface and add translated subtitles

### ISSUE THREAD

**Issue by M-Stenzel** [Chocobozzz/PeerTube#6717]
### Describe the problem to be solved

1. Captions can be edited as owner of the instance (vtt file). USERS should be able to edit subtitles since AI fails sometimes with bad audio quality and, e. g. with strong dialects.

2. By means of deepl.com for example, vtt files can be translated into a different language. It would be great to add translated subtitles to the original video. Quality of deepl.com translations is VERY high, and by the way, it is NOT Google :)

### Describe the solution you would like

1. Have some way to edit subtitles as video owner.

2. Integrate deepl.com API to translate subtitles and add them as subtitle option.

**Comment by Chocobozzz** [comment]
Hi,

Please create 1 issue per feature request.
