### ISSUE TITLE
Rate-limit the login/register routes

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#672]
Without rate limiting, an adversary can perform online dictionary attacks in which a off-the-shelf tools are run in hopes of gaining access to an account with a weak password. Account lockout also helps with this problem by requiring extended login information from a user the next time they log in, but that's beyond the scope of this issue.

Multiple requests for user registration or login password checking are an easy way to turn a lightweight HTTP request into costly time for the server.

While I found ways to rate-limit specific routes (those dedicated to registration and login) [with Nginx](https://www.nginx.com/blog/rate-limiting-nginx/), I cannot seem to find anything less than a [global rate-limit for Traefik](https://docs.traefik.io/configuration/commons/#rate-limiting). That means we have to have a backup plan within PeerTube. Hopefully there are tons of rate limiting middlewares for Express, such as [express-rate-limit](https://github.com/nfriedly/express-rate-limit), [express-limiter](https://www.npmjs.com/package/express-limiter), and [express-brute](https://github.com/AdamPflug/express-brute).

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/blob/develop/server/controllers/api/users.ts#L51 :)

**Comment by rigelk** [comment]
My bad, I didn't see it :x
