### ISSUE TITLE
Separated audio streams not respected with remote runner.

### ISSUE THREAD

**Issue by MadMan247** [Chocobozzz/PeerTube#6721]
### Describe the current behavior

Hello! I have a remote runner for my instance, version 0.0.20. 

My peertube server seems to not be respecting the separation of audio and video. The audio only track that my server produces is of an audibly much higher quality than the audio that plays during video playback. A LOT of artifacting is audible when there is a constant high-end noise, resulting in a hiss and a warlbling noise. I could only explain this as the audio-only stream is supposed to be rather high quality because it is meant for audio only content, but then why not just increase it? Why kick the video's audio quality down? The other explanation is that the videos are being encoded with audio (which they aren't supposed to), and the encoded audio stream is superseding the intended separate audio stream. The latter is what I believe to be the case.

If the former is true, I do not understand why the audio bitrate attached to videos seemingly dropped from previous versions of peertube.

https://github.com/user-attachments/assets/33051bb5-487e-4c6e-9495-7eba582065d9

(^yoinked from [here](https://www.youtube.com/watch?v=icDwkh0kF0k). Simulated compression artifacts.)

![image](https://github.com/user-attachments/assets/ca87e438-f438-4b59-a712-646e573e7de1)
![image](https://github.com/user-attachments/assets/e77f21d4-b976-49e2-864a-f659b33d4fe2)
^Compare the reported audio stream from the audio only, and the 1080P version.

![image](https://github.com/user-attachments/assets/499c21c2-a96f-4ad4-b93f-47ae42b20720)
^Why is there no audio only version available?

![image](https://github.com/user-attachments/assets/f1246e4d-98dd-43d4-918c-b19a72380953)
^I believe that I have my instance configured correctly.

![image](https://github.com/user-attachments/assets/84f32cc0-9b31-447e-b765-5bb1ebc802ac)
^This is from a previously uploaded video, from a previous verison of peertube, and it does have a much higher audio file tied to the video files.

Since we're all about customizability here, any chance the audio stream bitrate could be configurable in a future update? I wouldn't be against serving a 320Kbps stream with my videos. I'd also be for a configurable video stream bitrate for the remote runners (I know that there is a video bitrate adjustment for videos transcoded on the main server without remote runners).

Please let me know if you need any further information, examples, etc.

### Steps to reproduce

0. Set up a remote runner
1. Enable Transcoding as pictured above
2. Upload a video file
3. Observe the audio stream bitrates

### Describe the expected behavior

I would expect all downloads to have the same reported bitrate, since if I recall, the audio and video streams are supposed to be encoded together on the fly, as well as the audible audio should share the same quality as the audio only stream at the bare minimum.

### Additional information

* PeerTube instance: 
  * URL: peer.acidfog.com
  * Version: 6.3.0
  * NodeJS version Remote Runner: 12.22.12?
  * Ffmpeg version Remote Runner: 4.3.8-0+deb11u1
  * NodeJS version main server: 20.18.0
  * Ffmpeg version main server: 4.3.8-0+deb11u1

* Browser name, version and platforms on which you could reproduce the bug: Firefox 132.0.2, Windows 10 x64.
* Link to browser console log if relevant: likely not relevant.
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): I do not see anything relevant, but let me know if you want me to send anyways.

**Comment by Chocobozzz** [comment]
Hi,

What is your peertube-runner version? Can you also upgrade your instance to 6.3.3?

**Comment by MadMan247** [comment]
Hello! I have a remote runner for my instance, version 0.0.20. (Newest version is 0.0.22? The changes I saw didn't seem significant enough to affect this. https://github.com/Chocobozzz/PeerTube/commits/develop/apps/peertube-runner)

I have now upgraded to 6.3.3. The previously uploaded videos remain with the same issues: obviously low audio quality, the download modal shows a different audio quality from the audio-only file, and there is no audio-only option from the player quality selection menu. I will upload a new video for transcoding and update you.

**Comment by MadMan247** [comment]
New Video on 6.3.3, same issue. I'll look into updating my runner. Maybe just maybe that's the problem. I'm gonna do that after I sleep on it.

![image](https://github.com/user-attachments/assets/7f4afa01-b802-4bf5-8c8f-f61c354168d2)
![image](https://github.com/user-attachments/assets/efbb7184-1f17-4731-9d4f-dd50b2841782)
![image](https://github.com/user-attachments/assets/e8e8bfc7-830f-4939-a0c9-29921791d8ab)

**Transcoding on the host server (without remote runner):**
Works as intended. The video files have no audio stream. 
![image](https://github.com/user-attachments/assets/6542fbb9-7a70-45e6-9376-29d8a5048884)
![image](https://github.com/user-attachments/assets/7fff3b3c-325c-4a83-b9db-d9699dafbc86)


Let me know if there are other steps I should take. I appreciate your attention to this matter, since my main server is, well, raspberry pi's aren't great at transcoding at a reasonable pace. They serve fine, just no transcode.

**Comment by Chocobozzz** [comment]
Please use the latest runner version

**Comment by MadMan247** [comment]
I am sorry for wasting your time. Updating the runner sure did fix this.

Thank you again for your time and attention.
