### ISSUE TITLE
Can't Sync More Than 100 Channels

### ISSUE THREAD

**Issue by alacava** [Chocobozzz/PeerTube#6722]
### Describe the current behavior

I'm unable to Sync more than 100 channels on my account even though I have my production.yaml set to a higher number. 
`import:
  video_channel_synchronization:
    enabled: true
    check_interval: '6 hour'
    max_per_user: 150`

### Steps to reproduce

1. Updated production.yaml to reflect 150
2. When I go to add channel 101, I get "You cannot create more than 100 channel synchronization"
3. Unable to add

### Describe the expected behavior

Add more than 100. 

### Additional information

* PeerTube instance:
  * Version: 6.3.3

Logs:
error[11/13/2024, 4:08:04 PM] Client log: Backend returned code 400, errorMessage is: You cannot create more than 100 channel synchronizations
{
  "tags": [
    "client"
  ],
  "username": "(username)",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
  "meta": "{\"url\":\"https://(servername)/api/v1/video-channel-syncs\"}",
  "url": "https://(servername)/my-library/video-channel-syncs/create"
}

**Comment by Chocobozzz** [comment]
As a workaround you can update the value in your `local-production.json` file (in config foler)

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/a253a8088ac47517159c50b5eeeffd3681118e97
