### ISSUE TITLE
Partage de chaine entre deux propriétaires

### ISSUE THREAD

**Issue by MNAG974** [Chocobozzz/PeerTube#6727]
### Describe the problem to be solved

Bonjour Nous avons créé une chaine pour communiquer en sciences et technologie dans l'académie de la Réunion (cast_run). Je suis propriétaire de la chaine, mais je souhaiterais savoir si il est possible de partager les droits de propriétaire avec une autre personne ? Nous serions ainsi deux à animer cette chaine ? Je vous remercie Bien cordialement

### Describe the solution you would like

dans les paramètres de la chaine je souhaite donner les mêmes droits d'éditeur à un autre utilisateur

**Comment by Chocobozzz** [comment]
Hello,

Merci d'utiliser le forum pour des questions relatives à PeerTube: https://framacolibri.org/c/peertube

Pour répondre il n'est pas encore possible de partager les droits d'une chaine. Une issue suit déjà ce projet: https://github.com/Chocobozzz/PeerTube/issues/699
