### ISSUE TITLE
Peertube Log Rotation

### ISSUE THREAD

**Issue by Wxx-time** [Chocobozzz/PeerTube#6728]
### Describe the problem to be solved

What is the specific effect of log rotation configured in the configuration file?
When the peertube.log file size reaches the value I set, will a peertube1.log be created and the new log written?
The size limit for viewing Log on the peertube page is 2GiB. If I set max_file_size of log rotation to 1.5G and max_files to 10, when there are 10 log files, can I still view the log on the page?

**Comment by Chocobozzz** [comment]
Hello,

Please use the forum for PeerTube related questions: https://framacolibri.org/c/peertube

> When the peertube.log file size reaches the value I set, will a peertube1.log be created and the new log written?

Yes, you can find the documentation of our logger on https://github.com/winstonjs/winston/blob/master/docs/transports.md#file-transport

> If I set max_file_size of log rotation to 1.5G and max_files to 10, when there are 10 log files, can I still view the log on the page?

Yes, PeerTube uses your filter and open log files to display them on the interface.
