### ISSUE TITLE
PeerTube api functions isPlaying() and getCurrentTime() are not working for some reason

### ISSUE THREAD

**Issue by chagai95** [Chocobozzz/PeerTube#6732]
### Describe the current behavior

I'm on peertube version 6.3.3
The other functions are working.

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hello,

Please correctly fill the template because I'm unable to reproduce. Do you have a page example so I can test?

**Comment by chagai95** [comment]
Hi, sorry I do not have a page example, just some code which is part of Jitsi - I'm trying to use the peertube api in jitsi just like it's being used for [YouTube](https://github.com/jitsi/jitsi-meet/blob/master/react/features/shared-video/components/web/YoutubeVideoManager.tsx), so here is the code:

```
/* eslint-disable */

import { PeerTubePlayer } from '@peertube/embed-api';
import React from 'react';
import { connect } from 'react-redux';

import { PLAYBACK_STATUSES } from '../../constants';
import logger from '../../logger';

import AbstractVideoManager, {
    IProps,
    _mapDispatchToProps,
    _mapStateToProps
} from './AbstractVideoManager';

class PeerTubeVideoManager extends AbstractVideoManager {
    isPlayerAPILoaded: boolean;
    player?: any;
    currentPlaybackState?: string;

    constructor(props: IProps) {
        super(props);
        this.isPlayerAPILoaded = false;
        this.currentPlaybackState = PLAYBACK_STATUSES.PAUSED;
    }

    getPlaybackStatus() {
        let status;

        if (!this.player) {
            return;
        }

        status = this.currentPlaybackState;
        return status;
    }

    isMuted() {
        return this._isMuted;
    }

    getVolume() {
        return this._volume * 100;
    }

    getTime() {
        return this._currentTime;
    }

    seek(time: number) {
        this.player?.seek(time);
    }

    play() {
        logger.info("Play called");
        this.player?.play();
    }

    pause() {
        logger.info("Pause called");
        this.player?.pause();
    }

    mute() {
        this.player?.setVolume(0);
        this._isMuted = true;
    }

    unMute() {
        this.player?.setVolume(1);
        this._isMuted = false;
    }

    dispose() {
        if (this.player) {
            this.player = null;
        }
    }

    _isMuted = false;
    _volume = 1;
    _currentTime = 0;

    _updateState = async () => {
        if (this.player) {
            const volume = await this.player.getVolume();
            this._volume = volume;
            this._isMuted = volume === 0;
        }
    };

    setupEventListeners() {
        const { _isOwner } = this.props;

        // Common events for all users
        this.player.addEventListener('play', () => {
            this.currentPlaybackState = PLAYBACK_STATUSES.PLAYING;
            this.onPlay();
        });

        this.player.addEventListener('volumeChange', () => {
            this._updateState().then(() => this.onVolumeChange());
        });

        // Owner-only events
        if (_isOwner) {
            this.player.addEventListener('pause', () => {
                this.currentPlaybackState = PLAYBACK_STATUSES.PAUSED;
                this.onPause();
            });

            this.player.addEventListener('playbackStatusUpdate', this.throttledFireUpdateSharedVideoEvent);
        }
    }

    onPlayerReady = async () => {
        await this.player.ready;
        this.setupEventListeners();

        setTimeout(() => {
            this.play();
            if (this.isMuted()) {
                this.unMute();
            }
        }, 1000);
    };

    render() {
        const { videoId, _isOwner } = this.props;
        const showControls = _isOwner ? 1 : 0;

        return (
            <iframe
                ref={iframe => {
                    if (iframe) {
                        this.player = new PeerTubePlayer(iframe);
                        this.onPlayerReady();
                    }
                }}
                id="sharedVideoPlayer"
                src={`${videoId}?api=1&autoplay=1&controls=${showControls}`}
                width="100%"
                height="100%"
                allowFullScreen
            />
        );
    }
}

export default connect(_mapStateToProps, _mapDispatchToProps)(PeerTubeVideoManager);
```

I'm not sure what else is relevant in the template because this is the api which is not working and I tried on multiple different instances.

I'll try build a version of jitsi web with this inside so you have an example page, thx so much!

The node version I'm using (not for peertube) is v20.16.0

**Comment by Chocobozzz** [comment]
Just in case, the PeerTube version should be >= 6.3

**Comment by chagai95** [comment]
yes, thx, I noticed that - I tried with instance with peertube version 6.3.3

**Comment by Chocobozzz** [comment]
Do you have an error in the JS console?

**Comment by chagai95** [comment]
Yep

**Comment by chagai95** [comment]
```
ERROR
this.player.isPlaying is not a function
TypeError: this.player.isPlaying is not a function
```

**Comment by chagai95** [comment]
I see the npm package was only pushed on the 18th of September but the code for these functions was added only on the 25th, maybe the package just needs to be updated?

https://github.com/Chocobozzz/PeerTube/blame/3172bd1de7e2b6a55f46ba502455c35114c5d900/client/src/standalone/embed-player-api/player.ts#L81

**Comment by chagai95** [comment]
I just got around to checking this again and I think it's still not working, even in the newest version...
this is what happens when I don't catch the error:
![image](https://github.com/user-attachments/assets/16a6e015-dc3a-4d8a-ba5f-2b018b2de985)
and when I catch it;
<PeerTubeVideoManager.getTime>:  Error getting current time: method_not_found

this is the code I'm running:
            this._currentTime = await this.player.getCurrentTime();

**Comment by Chocobozzz** [comment]
Sorry again, the documentation is wrong and the methods only work with PeerTube v7

(you can test with an embed of https://peertube2.cpy.re/ if you want)

I fixed the doc in https://github.com/Chocobozzz/PeerTube/commit/15ce40778d6e065d0f62b2ad2cc84c1b36911ceb
