### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by JiananZhang01** [Chocobozzz/PeerTube#6733]
### Describe the current behavior

![捕获](https://github.com/user-attachments/assets/4a6cdb13-d0f2-4e25-ac8d-744d48773778)
dropdownList sort by field function, field not transfered all correct

### Steps to reproduce

1.
2.
3.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
I think it will be fixed in the next version: https://peertube2.cpy.re/videos/browse

You can also help to translate the software :) https://weblate.framasoft.org/projects/peertube/angular/

**Comment by JiananZhang01** [comment]
Yes, this project is exciting, I love to make a contribution to this project ,but I can't access this link .

[cid:cbaef83e-2000-476b-9c48-a7a03adea15c]
You can also help to translate the software :) https://weblate.framasoft.org/projects/peertube/angular/



With Best Regards,
JianAn Zhang
________________________________

**Comment by Chocobozzz** [comment]
>,but I can't access this link

Do you have an HTTP error?

**Comment by JiananZhang01** [comment]
It's working now!


With Best Regards,
JianAn Zhang
________________________________
