### ISSUE TITLE
ed2k to store videos

### ISSUE THREAD

**Issue by sjehuda** [Chocobozzz/PeerTube#6734]
### Describe the problem to be solved

Making sure that videos are shared forever.

### Describe the solution you would like

Similarly to [IPFS](https://github.com/Chocobozzz/PeerTube/issues/494), ed2k, which is more prevalent and more simple for single files, can also be utilized with PeerTube instances.

**Comment by Chocobozzz** [comment]
Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/494

**Comment by sjehuda** [comment]
Thank you.

May you please change the title of issue #494 to:

IPFS (and DC, ed2k, RetroShare) to store videos
