### ISSUE TITLE
Object storage - CDN - HLS  of sidecar data

### ISSUE THREAD

**Issue by stevespaw** [Chocobozzz/PeerTube#6736]
### Describe the problem to be solved

I am not sure of the best way to ask about these connected issues.
We many times use Peertube content with external players and are looking for potential solutions.
1. The connected data files eg.  - Captions, Storyboard images, thumbnails, etc are not moved to object storage with the media content.
2. Also these are not included in the HLS manifest, so these have to be reference externally with the player. (Not even possible in some cases)

1. Since the files are not moved to object storage they are not currently served by a CDN for us.
   This costs much more bandwidth of the Peertube instance to serve these files. We could maybe setup a CDN path for these, but that could get complicated in the future with this approach, as this is not managed in Peertube YAML. Moving these to object storage with the media would seems to be the best approach.
   Referencing these external files in the HLS manifest would be the BEST solution. Now that we have external audio, and are managing these, is this a big lift? (embedded captions are mandatory in Roku and iOS BTW)
  Can we have an option to move this to object storage in a file structure in the YAML? 

I think that this may also be part of adding Multiple audio tracks in the future.

This is a messy post with several concepts - maybe some of these are already in the works, I doubt I am the first to discuss this.

I am happy to break this up into chunks that may work better.
Thanks for this great project!

### Describe the solution you would like

1. Move connected data files to object storage next to the media. Manage this in YAML setup like everything else.
2. Include all of the connected data in the HLS manifest - Any external player will see all of the connected content in the M3U8. 
    This would all show properly when a Peertube M3U8 is loaded here. [https://hlsjs.video-dev.org/demo/](https://hlsjs.video-dev.org/demo/)

Audio Streams now show accurately here as of Peertube 6.2+ :-)

**Comment by Chocobozzz** [comment]
Hi,

We already have issues to upload thumbnails/captions in object storage: https://github.com/Chocobozzz/PeerTube/issues/5788 & https://github.com/Chocobozzz/PeerTube/issues/5699

And https://github.com/Chocobozzz/PeerTube/issues/6530 to inject VTT in HLS playlist :)

**Comment by stevespaw** [comment]
@Chocobozzz Thanks, glad to know this might be somewhere on a list! I think I know what you will say, but do you have any idea when these may be implemented? 😉

**Comment by Chocobozzz** [comment]
Unfortunately we don't have an ETA for these features, but you can contact Framasoft (https://contact.framasoft.org/ or my email on my github profile) if you want to fund these features.

**Comment by stevespaw** [comment]
@Chocobozzz  I have sent you an email, Let me know if you do not see it. Thanks!
