### ISSUE TITLE
Request for Modifications to Peertube Search in the video description or comments and Tag Limitations

### ISSUE THREAD

**Issue by al3m0odi** [Chocobozzz/PeerTube#6739]
### Describe the problem to be solved

I installed Peertube, but I found that the search feature cannot search in the video description or comments.
Additionally, when publishing a video, I can't add more than 5 tags in the tags field. 
How can I modify it to allow searching in the description and comments? 
Also, how can I change it to accept more than 5 tags?

**Comment by Chocobozzz** [comment]
Please don't create 2 different issues/topics: https://framacolibri.org/t/request-for-modifications-to-peertube-search-in-the-video-description-or-comments-and-tag-limitations/23669/1

(continuing the discussion on the forum)
