### ISSUE TITLE
Run on AWS

### ISSUE THREAD

**Issue by kabo** [Chocobozzz/PeerTube#674]
Couldn't find anything about this in the FAQ...

This is a really cool project. But my home internet connection sucks. And if I'd like to use this to host videos for a business I wouldn't want to run it on site anyways.

Any idea how hard it would be to get this running on AWS?

- Redis: elasticache
- PGSql: AWS Aurora PGSql
- Server: Elastic Beanstalk or perhaps just Fargate

It could be really cool with autoscaling, perhaps be able to choose database (Aurora Serverless is around the corner, DynamoDB, etc), perhaps be able to choose SNS/SQS instead of Redis, do video encoding on lambdas / step functions. Lots of opportunities.

It would also be nice to be have a "Launch in AWS" button which deploys a cloudformation stack with everything set up, ready to use, production grade.

Does this sound interesting to anyone?

**Comment by rigelk** [comment]
It sure sounds interesting for businesses familiar with the Amazon tech stack. The thing is, most of us here are not so familiar with it (mostly because we don't use AWS, I guess). 

I've heard of [Kubernetes PeerTube setups](https://github.com/MikaXII/helm-charts/), and Salt setups (can't find the source - just bear in mind both are community and experimental setups), but an AWS one is yet to be done.

**Comment by kabo** [comment]
I'm interested in helping with this. I won't be able to pour in tons of time, but I know a bit about AWS. I can try to fiddle around with PeerTube in the weekend, just get it running normally to get acquainted with how it all fits together to begin with.

**Comment by kabo** [comment]
Status update:
I've forked the PeerTube repo, and started with some basic plumbing. It seems to me that PeerTube is currently designed to be run on a single node, storage being local paths and such. So for now I'll focus on getting the docker image to run on ECS with RDS (postgre) and Elasticache (redis).
When PeerTube in the future supports multiple webseed hosts, a worker pool, etc. we could start to leverage autoscaling and such things.

https://github.com/kabo/PeerTube/tree/develop/aws
