### ISSUE TITLE
0.25 playback speed

### ISSUE THREAD

**Issue by JacksonChen666** [Chocobozzz/PeerTube#6743]
### Describe the problem to be solved

There's no 0.25x playback speed in PeerTube to look at something slower

### Describe the solution you would like

Add 0.25x playback speed

**Comment by ShreeHarsha-22** [comment]
Hey @Chocobozzz @JacksonChen666 ! I’d like to work on this issue. Could you please assign it to me?

**Comment by Chocobozzz** [comment]
@ShreeHarsha-22 done!

**Comment by algobuddha** [comment]
Hi @Chocobozzz  I created a pull request regarding this issue #6743. Please kindly look into it this is my first attempt on contributing, any feedback will be really helpful. Regards.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/issues/6743 

Thanks @algobuddha
