### ISSUE TITLE
Video embed of federated video connects to original instance

### ISSUE THREAD

**Issue by Natureshadow** [Chocobozzz/PeerTube#6744]
### Describe the current behavior

When embedding a video from instance A that was federated from instance B, the browser loading the embed connects to instance B to load the playlist.

### Steps to reproduce

1. Add a federated instance to your PeerTube
2. Open a federated video
3. Use the embed tool to generate an `iframe` code snippet
4. Embed the iframe into a webpage
5. Use uBlock Origin or the network console to check what domains the browser connects to

### Describe the expected behavior

All meta data, playlist and video streams should be loaded through the instance the video was embedded through.

### Additional information

* PeerTube instance:
  * URL: https://tube.teckids.org
  * Version: 6.3.3
  * NodeJS version: 18.19.0
  * Ffmpeg version: 5.1.6

* Browser name, version and platforms on which you could reproduce the bug: Firefox 132.0 on openSUSE Tumbleweed

**Comment by Chocobozzz** [comment]
Hello,

Playlists/video files are not federated. Merging this issue in https://github.com/Chocobozzz/PeerTube/issues/3431

**Comment by Natureshadow** [comment]
Please be aware that this is a very basic privacy issue (both in practice and in GDPR compliance terms).
