### ISSUE TITLE
Can't download subtitles in my language

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#6746]
### Describe the current behavior

I'm forced to download subtitles from the preselected language. For a real example, i wanted to download french subtitles of a video, but the preselected language was "albanian", and still selected even when i clicked on "french", so the only subtitle i was able to download was the albanian subtitles, despite the fact that french subtitles were -theorically- available.

### Steps to reproduce

1. Open a video
2. Go to download
3. Select "subtitles".

### Describe the expected behavior

French subtitles download.

### Additional information

* PeerTube instance:
  * URL: framatube.org
  * Version: 6.3.3
  * NodeJS version: don't know
  * Ffmpeg version: don't know

* Browser name, version and platforms on which you could reproduce the bug: the bug appears with all web browsers i tested.

**Comment by Chocobozzz** [comment]
Thanks for the issue! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/348161da6e4da95b9dae10e12900ebea10eb3637
