### ISSUE TITLE
@peertube/embed-api doesn't export types

### ISSUE THREAD

**Issue by mrkvon** [Chocobozzz/PeerTube#6747]
### Describe the current behavior

In https://www.npmjs.com/package/@peertube/embed-api, `player.d.ts` is not included in dist, although it's announced in `package.json`. NPM itself also says that the package contains type definitions, although this is false.

### Steps to reproduce

1. Install https://www.npmjs.com/package/@peertube/embed-api in a TypeScript project `npm i @peertube/embed-api --save`
2. See that the project complains about missing declaration files

### Describe the expected behavior

Types for the package are exported.

### Additional information

n/a

**Comment by Chocobozzz** [comment]
Thanks, it should be fixed by https://github.com/Chocobozzz/PeerTube/commit/32303b40e36534468cbadb5a4f5c809d96d4035c (v0.2.0)

**Comment by mrkvon** [comment]
Amazing, thank you! 🤩
