### ISSUE TITLE
Not work in Pale Moon

### ISSUE THREAD

**Issue by Symbian9** [Chocobozzz/PeerTube#675]
- **PeerTube version or URL:** https://video.blender.org/
- **Browser name/version:** Pale Moon / v27.9.2 (64-bit)
- **NodeJS version:**

- **What is the expected behaviour?** 

Open web-page.

- **What do you see instead?**

Here is screenshot:

![PeerTube in Pale Moon](http://i.imgur.com/EPupxpj.png)

- **Browser console log if useful (Gist/Pastebin...):**
- **Server log if useful (Gist/Pastebin...):**

### REFERENCE

- https://www.blender.org/media-exposure/youtube-blocks-blender-videos-worldwide/
- https://twitter.com/blender_org/status/1009077941676986368

**Comment by rigelk** [comment]
Hi @Symbian9 ! Please look out for related issues before creating one, as #257  already covers this. Notably [this](https://github.com/Chocobozzz/PeerTube/issues/257#issuecomment-384407877).

Apart from that, I've heard [Basilisk](https://www.basilisk-browser.org/) was an alternative to PaleMoon that worked well with PeerTube, at least.

**Comment by Symbian9** [comment]
It's look like next development branch of Pale Moon (Pale Moon 28.x) would be migrated to same codebase as Basilisk:

- https://github.com/MoonchildProductions/UXP/releases/tag/PM28.0.0a4_Unstable

Be waiting for first Pale Moon 28.x release then.
