### ISSUE TITLE
Can't use livestream

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#6750]
### Describe the current behavior

OBS is configured accordingly, but the live page says there's no live stream.

### Steps to reproduce

1. Create the live on the instance.
2. Configure OBS according the live parameters.
3.Start the stream.

### Additional information

* PeerTube instance:
  * URL: https://video.stemy.xyz
  * Version: 6.3.3
  * NodeJS version: 18.19.0+dfsg-6~deb12u2
  * Ffmpeg version: 8:5.1.6-0+deb12u1+rpt1

**Comment by Chocobozzz** [comment]
Please paste server logs

**Comment by stemy2** [comment]
It's working now, even if i didn't do any change.
