### ISSUE TITLE
Webpage freezed by malfunctioning scripts

### ISSUE THREAD

**Issue by stemy2** [Chocobozzz/PeerTube#6751]
### Describe the current behavior

I tried to load the main page, but it stops suddenly and nothing in the page responds.

### Steps to reproduce

1.Load a page.

### Describe the expected behavior

Many elements on the page aren't even loaded, and the page is not responding anymore.

### Additional information

URL: https://video.stemy.xyz/
   * Version: 6.3.3
   * NodeJS version: 18.19.0+dfsg-6~deb12u2
   * Ffmpeg version: 8:5.1.6-0+deb12u1+rpt1

Javascipt console

I could not copypaste the console content because it was scrolling very fast. I was only able to make some screenshots:

![Copie d'écran_20241203_001409](https://github.com/user-attachments/assets/0628af3e-c7dc-4985-b3f7-b201081a9520)

![Copie d'écran_20241203_001711](https://github.com/user-attachments/assets/59859cf3-36c5-446c-81aa-bc17ef58db47)

**Comment by Chocobozzz** [comment]
Hi,

The error is coming from a plugin. Try to disable them

**Comment by stemy2** [comment]
I deleted the plugins i installed just before the problem appeared, but it didn't fixed anything.

**Comment by Chocobozzz** [comment]
You can use https://docs.joinpeertube.org/maintain/tools#peertube-cli-plugins to list and delete them

**Comment by stemy2** [comment]
I have some problems with peertube-cli, it keeps repeating the same error message as if it was in bad faith.

```
stem@stem-kubuntu:~$ peertube-cli plugins uninstall peertube-plugin-ungamify
Cannot uninstall plugin: You need to specify the npm name of the plugin/theme you want to uninstall.
stem@stem-kubuntu:~$ peertube-cli plugins uninstall plugin-ungamify
Cannot uninstall plugin: You need to specify the npm name of the plugin/theme you want to uninstall.
stem@stem-kubuntu:~$ peertube-cli plugins uninstall ungamify
Cannot uninstall plugin: You need to specify the npm name of the plugin/theme you want to uninstall.
stem@stem-kubuntu:~$
```

**Comment by stemy2** [comment]
Plugin uninstalled, now my instance is working fine again.

Thanks a lot.
