### ISSUE TITLE
Unable to upload videos.

### ISSUE THREAD

**Issue by TremerePuck** [Chocobozzz/PeerTube#6754]
### Describe the problem

I'm running peertube via docker on unraid. I'm not using nginx but rather a Cloudflare Argo tunnel. 

I get an "unknown error" whenever trying to upload a video of any length and file type.
Under debug it's showing that it thinks my IP address is the internal address of the host.

### Additional information

* PeerTube version: 6.3.3
* PostgreSQL version: 17

**Comment by Chocobozzz** [comment]
Hello,

Please use the forum for PeerTube sysadmin related questions: https://framacolibri.org/c/peertube
