### ISSUE TITLE
Concern about "About" page telling people to use Tor.

### ISSUE THREAD

**Issue by milleniumbug** [Chocobozzz/PeerTube#676]
The "About" page contains this blurb:

> If you want to keep your public IP address private, please use a VPN or Tor.

However, Tor project [explicitly tells people to not use BitTorrent over it](https://www.torproject.org/docs/faq.html.en#FileSharing):

> File sharing (peer-to-peer/P2P) is widely unwanted in the Tor network, and exit nodes are configured to block file sharing traffic by default. Tor is not really designed for it, and file sharing through Tor slows down everyone's browsing. Also, Bittorrent over Tor is not anonymous! 

Should the "or Tor" part be removed?

**Comment by rigelk** [comment]
> Also, Bittorrent over Tor is not anonymous!

I don't think the vulnerability concern as depicted in the 2010 paper is valid anymore, as it was mainly an implementation problem, on a whole different protocol stack (UDP). Please correct me if I'm wrong.

But as for the concern of slowing down the Tor network, it can be said of any connection meant to share voluminous data like videos.

**Comment by Chocobozzz** [comment]
In fact Tor browser disables WebRTC so you don't use P2P with it, just WebSeed.

**Comment by rigelk** [comment]
@Chocobozzz then we should be more specific and say "Tor Browser" instead of just Tor

**Comment by sandov** [comment]
But it doesn't matter what protocol you're using, it still sucks a lot of bandwidth from the tor network, which is the principle of their plea

Isn't it bad manners to hog Tor when they are  are explicitly asking people not to do so?
