### ISSUE TITLE
plugin system: validation of REST API parameters conflicts with custom parameters

### ISSUE THREAD

**Issue by ppom0** [Chocobozzz/PeerTube#6760]
### Describe the problem to be solved

Context: I just wrote a plugin permitting to add a random listing of videos.

More context on this sibling issue: https://github.com/Chocobozzz/PeerTube/issues/6759

#### sort=random

I first started to change the `sort` parameter of the `GET /video` call.

This works client-side:
```js
	registerHook({
		target: 'filter:api.local-videos.videos.list.params',
		handler: params => Object.assign({}, params, { sort: "random" }),
	});
```

But the server returns a 400 before the server-side plugin can do something like this:
```js
	registerHook({
		target: 'filter:api.videos.list.params',
		handler: params => {
			if (params.sort === "random") {
				// Dummy value
				params.sort = "views";
				// Used by the filter:api.videos.list.result hook
				params.random = true;
			}
			return params;
		},
	});
```

#### random=true

I then tried to add a new parameter `random=true`, hoping it would not cause a server-side validation error:
```js
	registerHook({
		target: 'filter:api.local-videos.videos.list.params',
		handler: params => Object.assign({}, params, { random: true }),
	});
```

But it's filtered client-side: the API request doesn't contain the new parameter.

#### hack

So I did change sort to `publishedAt`, which is never really used client-side.

And when I detect this on server-side, I do my random thing.

Of course this is hacky, because it prevents potential scripts to use this ordering.

### Describe the solution you would like

I don't know what's best.

If custom parameters indeed are exempt from server validation, the easiest move would be to allow custom parameters client-side.

What do you think?

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/d8b3436f687034948964627cce88148daf7fb4eb

You can now add custom params in the client hook

Note: In v7, use `filter:api.browse-videos.videos.list.params` instead of `filter:api.local-videos.videos.list.params`: https://github.com/Chocobozzz/PeerTube/releases/tag/v7.0.0-rc.1
