### ISSUE TITLE
Security Improvements

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#6761]
### Describe the problem to be solved

Hi,
We had a security audit on PeerTube, and find the below problems:

1) Session Timeout: Session termination is an important part of the session lifecycle. Reducing to a minimum the lifetime of the session tokens decreases the likelihood of a successful session hijacking attack. This can be seen as a control against preventing other attacks like Cross Site Scripting and Cross Site Request Forgery

2) Session management policy: We were able to login to one account in two browsers simultaneously.Also logging out from the account from one browser,didn't logout the account from the other browser

3) Cookie attributes: In addition to a name and value, cookies can also have one or more attributes. Browsers do not include cookie attributes in requests to the server—they only send the cookie's name and value. Cookie attributes are used by browsers to determine when to delete a cookie, block a cookie or whether to send a cookie to the server. Set the HttpOnly,Secure and SameSite attributes, Also set __Secure- or __Host- prefix for every coockie name (__Host- is prefred. For more information: WSTG v4.2 § Testing for Cookies Attributes).

4) Strong password policy: A key concern when using passwords for authentication is password strength. A "strong" password policy makes it difficult or even improbable for one to guess the password through either manual or automated means

**Comment by Chocobozzz** [comment]
Hi,

And thanks for the report.

> Session Timeout: Session

Can be changed in the configuration: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L64
I think that 1 day is an appropriate default for the access token, so I'm not sure to understand the guideline here :thinking: 

> Session management policy

We need a proper page to see active sessions and remove all of them. I think that logging out and only remove the current session is an appropriate behaviour, as some users share the same account on multiple web browsers.

> Cookie attribute

The only cookie we use is to remember the web browser language so I don't think we need more attributes to secure it

> Strong password policy

Setting minimum password length would be a nice addition (opt-out by the admin?)

**Comment by paymanzafar1** [comment]
Hi,
Thank you very much for your reply.

**Session Timeout**: The session is not closed after one day due to the following configuration. My session is open until I logout.

oauth2:
  token_lifetime:
    access_token: '1 day'
    refresh_token: '2 weeks'

**Cookie attribute**: Set the HttpOnly,Secure and SameSite attributes, Also set __Secure- or __Host- prefix for every coockie name (__Host- is prefred. For more information: WSTG v4.2 § Testing for Cookies Attributes)

![image](https://github.com/user-attachments/assets/5e2720bf-5052-45d7-9786-5dccb25d064a)

**Strong password policy**: In addition to minimum password length, it is better to add upper case characters & special characters to assign a strong password.

**Comment by paymanzafar1** [comment]
Hi,
I set the access_token & refresh_token to 15 minutes, and it works. After 15 minutes, my session was ended.

**Comment by paymanzafar1** [comment]
According to our security negation company recommendations, we also added the following lines to the Nginx configurations file:

more_clear_headers Server;
more_clear_headers x-powered-by;

add_header X-XSS-Protection "1; mode=block";
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
add_header X-Content-Type-Options "nosniff";
add_header Referrer-Policy "no-referrer";
add_header Permissions-Policy "accelerometer=(), autoplay=(), camera=(), cross-origin-isolated=(), display-capture=(), encrypted-media=(), fullscreen=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(self), usb=(), web-share=(), xr-spatial-tracking=(), clipboard-read=(), clipboard-write=(), gamepad=(), hid=(), idle-detection=(), interest-cohort=(), serial=(), unload=()"; 

The first 2 lines removes the server & x-powered-by headers which provide unnecessary information to attackers as in the below images:

![image](https://github.com/user-attachments/assets/600774d5-2edc-44b2-a540-643b5acf5451)

![image](https://github.com/user-attachments/assets/140d34d2-ef75-41e4-89d8-01dc9ba735df)
  
To use the more_clear_headers to remove these headers, the user must install nginx-extras.

**Comment by Chocobozzz** [comment]
> We need a proper page to see active sessions and remove all of them. I think that logging out and only remove the current session is an appropriate behaviour, as some users share the same account on multiple web browsers.

https://github.com/Chocobozzz/PeerTube/issues/3340

> Setting minimum password length would be a nice addition (opt-out by the admin?)

https://github.com/Chocobozzz/PeerTube/issues/6777
