### ISSUE TITLE
v7.0.0-RC1: missing release note related to a configuration change

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#6762]
### Describe the desired information/correction

In the [v7.0.0-RC1 changelog](https://github.com/Chocobozzz/PeerTube/blob/develop/CHANGELOG.md#v700-rc1), there is a missing configuration change:

```
-  default_client_route: '/videos/trending'
+  default_client_route: '/videos/browse'
```

As the route name changed, admins should check that their default route still exists. And change accordingly.
This should be mentioned in the release notes.

**Comment by Chocobozzz** [comment]
Thanks! Added a note in https://github.com/Chocobozzz/PeerTube/commit/b2aac08921a3cb05452d3b39c00014b588a684ce
