### ISSUE TITLE
v7.0.0-RC1: CSS issues with plugins

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#6763]
### Describe the current behavior

**edit**: after some thinking, not 100% sure that this is an issue. Let me know what you think.

In v7.0.0-RC1, Peertube defines some CSS for `label` tag, increasing the font-size (to 18px instead of 14px).

As there is no additionnal class or context given to this CSS rule, it can break the display of some plugins, by having labels way bigger than text around them.

For example, in the livechat plugin, i have labels that are wait too big now (this is especially true in the "Task" app, where task labels are bigger than task list titles).

See screenshot:

![image](https://github.com/user-attachments/assets/a267bda4-5762-452a-ab03-ac316ed534f3)

### Describe the expected behavior

Not sure that all labels should have this new font-size.

I'll propose a fix for the livechat plugin, but maybe there are some other side effects on other plugins?

### Additional information

* PeerTube instance:
  * Version: 7.0.0-RC1

**Comment by JohnXLivingston** [comment]
Here is a screenshot with v6:

![image](https://github.com/user-attachments/assets/07a54423-cb1f-4ee1-bee2-5d3d784485a5)

**Comment by Chocobozzz** [comment]
I'm not sure it's a bug either, because if you want to use the same "UX" as PeerTube then labels should be 18px. And I think most plugin, in most cases would want to not bother to add a custom PeerTube class to their labels so they look like those in the main app

**Comment by JohnXLivingston** [comment]
You are right. I'm closing.

The issue was on the livechat side i think. v7 made it just more visible. I changed task list labels to also use a `label` tag.
