### ISSUE TITLE
v7.0.0-RC1: bad url in "new theme version" email

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#6764]
### Describe the current behavior

The mail received when a new theme is available contains the following url:
`https://videos.john-livingston.fr/admin/plugins/list-installed?pluginType=2`
But the correct one is:
`https://videos.john-livingston.fr/admin/settings/plugins/list-installed?pluginType=2`

So when we click on the link in the email, we are forwarded to the plugin list, not the theme list.

### Steps to reproduce

1. wait for a new theme version
2. click on the link

### Additional information

* PeerTube instance:
  * Version: 7.0.0-RC1

**Comment by Chocobozzz** [comment]
Thanks John! Fixed by https://github.com/Chocobozzz/PeerTube/commit/6b60a1d85237151ce21829e812bef631fed493b9
