### ISSUE TITLE
Can't run on docker: error: Unable to connect to PostgreSQL database

### ISSUE THREAD

**Issue by Magikh42** [Chocobozzz/PeerTube#6765]
### Describe the problem

Hello, I tried to install PeerTube using Docker
I used the offcial `docker-compose.yml`

I keep getting this error message: "`error: Unable to connect to PostgreSQL database`"
If I use `peertube:latest` instead of `peertube:production-bookworm` it works
[Logs](https://sebsauvage.net/paste/?a47580a164f27cf6#Lf95Qgmo9JMcQDmV51UraEdfVsJFyp5pfzIk2nh1aHY=)

**Comment by Chocobozzz** [comment]
Hello,

Please use the forum for PeerTube sysadmin related questions: https://framacolibri.org/c/peertube
