### ISSUE TITLE
Please try latest Firefox version.

### ISSUE THREAD

**Issue by AsilMediaUzbek** [Chocobozzz/PeerTube#6766]
### Describe the current behavior

![Screenshot_20241213_044913_Plus](https://github.com/user-attachments/assets/0c6c6e6e-a654-4800-ac23-d92c1baf2518)

I installed the latest version of Peertube today. But I see this problem.

### Steps to reproduce

1. I created an embed link.
2. I saved the link to the Telegram messenger cloud.
3. I tried to open the link by phone and entered Telegram from the phone.  Then I entered the embed link.  Telegram now has its own web browser.  Was using Chrome earlier.  Now they have created their own browser.

### Describe the expected behavior

There is a problem with the Telegram browser.

### Additional information

* PeerTube instance:
  * URL: https://peertube.yangi.tv/videos/embed/b542c7cb-acf3-42cb-954b-cc96d6331a57?loop=1&warningTitle=0&peertubeLink=0
  * Version: 6 3
  * NodeJS version: latest
  * Ffmpeg version: latest

* Browser name, version and platforms on which you could reproduce the bug: Telegram browser
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Telegram web browser throws an uncaught exception... We now "handle" it in https://github.com/Chocobozzz/PeerTube/commit/f80157eff8524948d4ef9655314600091ff7acc1
