### ISSUE TITLE
Menu overlapping problem

### ISSUE THREAD

**Issue by papiche** [Chocobozzz/PeerTube#6768]
### Describe the current behavior

Menu is overlapping main area...  css problem ?
![err](https://github.com/user-attachments/assets/f34ab721-b37e-4561-85f8-0ebce6679bff)

### Steps to reproduce

1. Close/Open Menu on Firefox
![Br](https://github.com/user-attachments/assets/0c481b47-7d7f-4475-a728-dc3ab74d4dc0)

Menu is overlapping main area... 

### Describe the expected behavior

main area and menu keeps aligned and separated

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Hi,

It should be fixed in v7: the menu does not overlap on big screen, overlaps on small screens and takes all the width on mobile screens :)
