### ISSUE TITLE
PeerTube Desktop Application

### ISSUE THREAD

**Issue by Wajinn** [Chocobozzz/PeerTube#6769]
### Describe the problem to be solved

Have a desktop application of PeerTube. Somewhat like FreeTube, but for finding channels and videos on PeerTube without using the browser. Maybe have it also able to work with other external players.

### Describe the solution you would like

PeerTube desktop app, that doesn't need browser.

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the issue! Unfortunately Framasoft doesn't have enough resource to also develop a desktop application. You can find unofficial desktop application developed by the community on https://docs.joinpeertube.org/use/third-party-application#desktop-clients
