### ISSUE TITLE
Remove webseeds

### ISSUE THREAD

**Issue by SoniEx2** [Chocobozzz/PeerTube#677]
Webseeds and HTTP downloads should be disabled on peertube. Or at least, they should be an option, disabled by default.

Basically, if you can require clients to follow p2p, you should do so. Don't let youtube-dl ruin peertube by providing a half-assed extractor that can't even extract magnet links, and just hammering the instance until it goes down, either because the admins have to pay extra for bandwidth or because their instance can't handle the complete lack of peering.

**Comment by rigelk** [comment]
The thing is, PeerTube acts as a superpeer: without WebSeed, there is no guarantee of service anymore. But more than a superpeer, it is also the initial seeder, as the upload mechanism creates the torrent on PeerTube's side. So if we deactivate WebSeed, there is no sharing chain anymore.

Plus, so far as I understand, youtube-dl users are a minority. And why bother? We also provide direct download of the video in our interface. Do you want us to stop doing that too?

The idea is more to make p2p the default behaviour, but not close doors to marginal uses so long as it a choice of the user.

**Comment by SoniEx2** [comment]
You can replace webseed with a (fixed) peer, I think by using `x.pe` in magnet links (e.g. `x.pe=hostname-of-peertube:port_of_peertube_torrent_client`).

And you'd still have the tracker.

**Comment by Chocobozzz** [comment]
There is already an issue to disable Download in peertube: https://github.com/Chocobozzz/PeerTube/issues/536

And the HTTP enpoint is rate limited in nginx: https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube#L82 

Actually, we encourage people/platforms to use P2P, but we want to keep compatibility with other video platforms that just don't use WebTorrent
