### ISSUE TITLE
Unable to edit start/end in studio for audio only tracks

### ISSUE THREAD

**Issue by gilou** [Chocobozzz/PeerTube#6770]
### Describe the current behavior

Trying to edit the beginning/end of a video that was streamed live as audio only, once published, using the Studio doesn't work, we get an error:
`Backend returned code 500, errorMessage is: Cannot read properties of undefined (reading 'size')`

Or more in details:
```
00:11:36,610 Backend returned code 500, errorMessage is: Cannot read properties of undefined (reading 'size') 
Object { type: undefined, url: "https://www.yiny.org/api/v1/videos/9f1bc133-f591-4491-b4ca-bf6ef7ed332a/studio/edit" }
logger.ts:45:22
    clientError logger.ts:45
    error logger.ts:41
    buildErrorMessage rest-extractor.service.ts:99
    handleError rest-extractor.service.ts:62
    f video-studio.service.ts:26
    RxJS 22
    Angular 9
00:11:36,612 Erreur: Cannot read properties of undefined (reading 'size') logger.ts:46:17
00:11:36,613
Object { message: "Cannot read properties of undefined (reading 'size')", status: 500, body: {…}, headers: {…} }
logger.ts:46:17
```

### Steps to reproduce

1. Stream a live video set to audio only
2. Go to Studio to edit once uploaded
3. Get the error when trying to start the video editing process

### Describe the expected behavior

It should start editing the beginning / ending of the video

### Additional information

* PeerTube instance:
  * URL: https://www.yiny.org/ (let's mention friend @JohnXLivingston)
  * Version: 6.3.3
  * NodeJS version: v18.20.5
  * Ffmpeg version: 4.3.8-0+deb11u1

* Browser name, version and platforms on which you could reproduce the bug: Firefox 133, Ubuntu 24.04
* Link to browser console log if relevant: included
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): server side logs basically tells the same

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/a1dd455634cc1adf9f59fbf1eb4c2f4301f6eca0
