### ISSUE TITLE
User exports are deleted too quickly

### ISSUE THREAD

**Issue by prolibre** [Chocobozzz/PeerTube#6771]
### Describe the current behavior

I've noticed that exports are deleted very quickly (a few tens of minutes maximum).

In the configuration, the parameter is set to 7 days (in the file but also in the administration page).

### Steps to reproduce

I've launched an export that works very well and is stored in the “tmp_persistent” directory.

But the problem is that a few minutes later this file is deleted.

the risk, of course, is that the user won't have time to download the archive :-( 

Merci pour tout ! / have a nice day !

* PeerTube instance:
  * URL: https://peertube.heraut.eu
  * Version:6.3.3

**Comment by prolibre** [comment]
I'll be back with more details.

I've reset the deadline to its original value: 2 days in the conf and in administration.

Archive created at 2024-12-16 05:49:23

Here's what's in the “userExport” table :
 	
id _6_
filename _user-export-2-2024-12-16T05:49:23.790Z.zip_
withVideoFiles _FALSE_
state _3_
error _NULL_
size _9698361_
storage _0_
userId _2_
createdAt _2024-12-16 05:49:23_
updatedAt _2024-12-16 05:49:30_
fileUrl _NULL_

and less than an hour later in the logs (the export has already been deleted) :-(

`{"message":"Removing expired user exports user-export-2-2024-12-16T05:49:23.790Z.zip","level":"info","label":"peertube.heraut.eu:443","timestamp":"2024-12-16T06:47:16.631Z"}
{"level":"info","message":"Removing user export file user-export-2-2024-12-16T05:49:23.790Z.zip.","label":"peertube.heraut.eu:443","timestamp":"2024-12-16T06:47:16.632Z"}`

Thank you and good luck.

**Comment by Chocobozzz** [comment]
Thanks! If fixed this bug in https://github.com/Chocobozzz/PeerTube/commit/ae3b487c4299d32624b4f52a5ef55227b5644b50
