### ISSUE TITLE
Full screen button does not work in Chrome browser

### ISSUE THREAD

**Issue by paymanzafar1** [Chocobozzz/PeerTube#6773]
### Describe the current behavior

Hi,
In the 6.3.3 version, the full screen button in the video control panel does not work, but in FireFox it works.

### Steps to reproduce

1. Use Google Chrome to open a video to play
2. On the video control menu, press full screen button
3.

### Additional information

* PeerTube instance: 
  * URL:
  * Version: 6.3.3
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Chrome
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Please paste web browse console logs

**Comment by paymanzafar1** [comment]
![image](https://github.com/user-attachments/assets/3d852f2a-b858-4e12-a6de-6c7100d0367e)

**Comment by Chocobozzz** [comment]
Can you record a screencast? :think

**Comment by paymanzafar1** [comment]
https://github.com/user-attachments/assets/978c52a0-6a52-4f9d-a579-d1ad240ecc17

**Comment by paymanzafar1** [comment]
https://clipet.tv/w/41S8tJ6qCHgEfHtqCJGNc2

**Comment by Chocobozzz** [comment]
HTTP permission policy forbids fullscreen on this PeerTube instance

**Comment by paymanzafar1** [comment]
I removed the permission policy & all the other added headers, but the problem is still exists. Please check again.
