### ISSUE TITLE
Creating an account with username peertube causes unexpected behavior

### ISSUE THREAD

**Issue by dumptyd** [Chocobozzz/PeerTube#678]
* **PeerTube version or URL:** https://peertube.social

* **What is the expected behaviour?**
1. https://peertube.social/my-account/video-channels should show me a list of all my video channels.
2. Video update page should show me the channel list as options in the dropdown.
3. Clicking on `My public profile` should take me to my own profile.

* **What do you see instead?**
1. No channels are listed.
2. Dropdown is not populated as the API returns an empty array.
3. https://peertube.social/accounts/peertube/ opens a different page with many subscribers.

**Comment by Chocobozzz** [comment]
Thanks for the issue @dumptyd!

Should be fixed: https://github.com/Chocobozzz/PeerTube/commit/2ef6a0635cb6be32ef6028fb76d1c8ba4a6f7109
