### ISSUE TITLE
Hide channel setup promotion for consume only users

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#6781]
### Describe the problem to be solved

A user without upload permissions may be a bit confused upon visiting `/my-library/video-playlists` and reads the text below. When a user creates an account just to consume video and write comments it'll be confusing with the "channel" term, since they're not even aware of having a channel (it seems hidden in all menus as well).

> Some of your channels are not fully set up. Make them welcoming and explicit about what you publish by adding a <strong>banner</strong>, an <strong>avatar</strong> and a <strong>description

### Describe the solution you would like

Hide this text for users without any upload quota.

**Comment by Chocobozzz** [comment]
Thanks! I removed the message in https://github.com/Chocobozzz/PeerTube/commit/bf37b94af7d8ddc7c8e2b78686cb541f3512d44d
