### ISSUE TITLE
Empty discover page

### ISSUE THREAD

**Issue by SteelAlloy** [Chocobozzz/PeerTube#6782]
### Describe the current behavior

Hi,
Great work on the v7, it's wonderful !

*I might have missed something in the changelog*, but the `Discover` page is empty in every instance I own.

![image](https://github.com/user-attachments/assets/c057a68d-ae54-430b-af78-3be365920e75)

### Steps to reproduce

Maybe useless but :

1. Have thousand of videos with tags
2. Have hundred of videos with assigned categories
3. Except a few (less than 10), every video is internal
4. No videos in discover page

### Describe the expected behavior

Looking at the v7 blog post announcement, it should be filled with videos from tags and categories

![light_beige_interface](https://github.com/user-attachments/assets/7a11a4f1-ceef-4dc2-aac7-87b7807679b0)

### Additional information

* PeerTube instance:
  * URL: https://itvplus.iiens.net
  * Version: 7.0.0

**Comment by Chocobozzz** [comment]
Hi,

Discover page doesn't take into account internal videos. See https://github.com/Chocobozzz/PeerTube/issues/4406 for this feature request :)
