### ISSUE TITLE
Clicking chapter markers doesn't work properly on very long files

### ISSUE THREAD

**Issue by FediVideos** [Chocobozzz/PeerTube#6789]
### Describe the current behavior

If you are viewing a very long file, clicking on the chapter marker becomes very inexact and does not take you to the marker's timestamp.

The chapter markers activate an animation to highlight themselves, but they do not actually snap the pointer to their timestamp, so when the click happens it may actually be some distance from the marker's timestamp.

This isn't an issue on short videos, but it becomes significant on very long files such as audiobooks, as the cramped timeline makes it very difficult to choose specific times.

### Steps to reproduce

1. View a very long file such as https://fedi.video/w/8aVXe5QNUy6zEPzLPoNxTB
2. Click on some chapter markers
3. Observe that they do not line up with their timestamps (the audio should be announcing the beginning of a chapter marker at the marker's exact timestamp)

### Describe the expected behavior

If a chapter marker is clicked on, it should start playing from its exact timestamp.

### Additional information

* PeerTube instance: fedi.video
  * URL: https://fedi.video
  * Version: 6.3.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Firefox 133.0.3 Linux Mint
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1310cb1adc2c4b4d4e8328d20c4be012368efc91 (will be included in 7.1, not 7.0.x)

**Comment by FediVideos** [comment]
Thank you so much for fixing this, apologies that I didn't thank you earlier! Audiobooks work perfectly now!
