### ISSUE TITLE
Oauth error after installing.

### ISSUE THREAD

**Issue by Mecallie** [Chocobozzz/PeerTube#6791]
### Describe the problem

I have just installed PeerTube via docker on Unraid. After installing I get the following error:
```
```Error

Cannot retrieve OAuth Client credentials: Getting client tokens for host 192.168.1.92:9001 is forbidden. Ensure you have correctly configured PeerTube (config/ directory), in particular the "webserver" section.
```

I have read the previous posts about this, but cannot fix it.

What I have tried:
re-install from scratch (including new DB), be sure to use the same domain name (peertube.mydomain.org) and use the same port number for the web interface and the web server (although that one still confuses me).

I have tried to use http instead of https.

I have tried using just a hostname (peertube) instead of an fqdn.

I have tried a different port number (9001).

I have tried redirecting my nginx proxy manager to it (502, bad gateway).

Can someone point me in the right direction for this? I am totally stuck.

### Additional information

* PeerTube instance URL: peertube.mecallie.com
* PeerTube version: latest
* NodeJS version: n/a
* Ffmpeg version: n/a
* Redis version: latest
* PostgreSQL version: 17

**Comment by Chocobozzz** [comment]
Hello,

Please use the forum for PeerTube related questions: https://framacolibri.org/c/peertube

(if you want to access `https://peertube.mcallie.com` use `443` for `webserver.port`: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L9. You'll also have to run https://docs.joinpeertube.org/maintain/tools#update-peertube-instance-domain-name)
