### ISSUE TITLE
Can't watch a specific video

### ISSUE THREAD

**Issue by Zig-03** [Chocobozzz/PeerTube#682]
this is the specific video I'm trying to watch and I can't
https://video.blender.org/videos/watch/c27df7df-7474-457a-8e93-da4ebf6af352
Is the issue on my side, or the instance was wrongly set up?

* **Browser name/version:**
Firefox ESR 52

* **What is the expected behaviour?**
be able to watch the video
* **What do you see instead?**
it's just loading infinitely. I can see it downloading but the video won't play.

**Comment by Chocobozzz** [comment]
No it's peertube that cannot (weirdly) stream the video. It should fallback to HTTP but we had another issue on firefox (chrome should work) I fixed this morning https://github.com/Chocobozzz/PeerTube/commit/575712a5c970ea1edeb6b44a35a095fc08193a3d

**Comment by Chocobozzz** [comment]
I tried to debug it from the videostream package, but i could not :/ It's the first time I see this with a transcoded video. Since we have HTTP fallback, I won't spend more time on this issue and will close it. Feel free to comment if you notice other transcoded videos that do not work.
