### ISSUE TITLE
Add qr-code for video url

### ISSUE THREAD

**Issue by bristow** [Chocobozzz/PeerTube#683]
It would be great if we could have a qrcode displayed after to click on share button.
We could have : 
- url of video
- embed code
- qrcode

This  code could be easily downloaded in order to place it on documents for education (there is a lot of tablets on french schools).
qrcode is also a good solution because videos url are very long...

**Comment by DeeJayBro** [comment]
Can i take this issue?

**Comment by Chocobozzz** [comment]
@DeeJayBro Sure!
