### ISSUE TITLE
Installation Problem: "v1.0.0~beta8-0": version does not begin with a number

### ISSUE THREAD

**Issue by gege2b** [Chocobozzz/PeerTube#687]
Hi there

I was trying to install Peertube on a test server using [the tool on this page](https://purr.rigelk.eu/lang/en/docs/install/#debian-beta)

**Which operating system are you using:**
Debian 9.4 stretch

**Which version of the package are you using:**
v1.0.0 beta8

**Please describe the steps you took when trying to install PeerTube and what went wrong:**

I just followed the instruction on [https://purr.rigelk.eu/lang/en/docs/install/#debian-beta](https://purr.rigelk.eu/lang/en/docs/install/#debian-beta)
Packages installation was running fine until the peertube package, the "v" in "v1.0.0" makes APT angry

```
(... blabla all OK ...)
dpkg: erreur de traitement de l'archive /tmp/apt-dpkg-install-k5qIDk/179-peertube_v1.0.0~beta8-0_amd64.deb (--unpack) :
 analyse du fichier '/var/lib/dpkg/tmp.ci/control' vers la ligne 2 paquet 'peertube' :
 erreur dans la chaîne du champ « Version » : « v1.0.0~beta8-0 »: le numéro de version ne commence pas par un chiffre 
Des erreurs ont été rencontrées pendant l'exécution :
 /tmp/apt-dpkg-install-k5qIDk/179-peertube_v1.0.0~beta8-0_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by rigelk** [comment]
It's an error of my package - I didn't spot it sorry! Correcting that ASAP.

**Comment by gege2b** [comment]
no problem thank you for your reactivity!
BTW, I think that peertube beta 7 package is also concerned (but it's less important)

```
httpdeb:~$# apt-cache show peertube
Package: peertube
Version: v1.0.0~beta8-0                                                                                                                                                                                        
(...)
Package: peertube                                                                                                                                                                                              
Version: v1.0.0~beta7-0

(other packages are correctly versioned)

```

**Comment by rigelk** [comment]
Yes - actually I've spotted the error and next releases won't be affected. I'm fixing the existing releases just once I've finished my PR :)

**Comment by rigelk** [comment]
Package updated with the fix, and the faulty packages have been purged :wink:
