### ISSUE TITLE
import-videos.js root access to import video on behalf of another user

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#689]
Hello,

It would be nice that we can use import-videos.js, with root login and password, but to import video in an other user's account.
Example: `import-videos.js -u mypeertube.com -U root --password *** -t youtube/xxx --for newbie_login`

So we can launch import process for our instance's users, who have bad internet connection, or begginners who are not able to use a CLI tools

Best regards,
John

**Comment by Chocobozzz** [comment]
I'm sorry but we had to remove this unmaintained script, so I'm closing this issue.
