### ISSUE TITLE
Is there an example config for running peertube behind nginx reverse proxy?

### ISSUE THREAD

**Issue by jkirkcaldy** [Chocobozzz/PeerTube#692]
I have the server up and running on my LAN. but I am stuggling to get it to work through my Nginx reverse proxy. Is there any examples or has anyone got it working behind a reverse proxy?

**Comment by jkirkcaldy** [comment]
So that's where I have started. But maybe I should have been more specific. 

I am running peertube on a separate machine to my proxy. So all of the alias links don't work.

**Comment by Chocobozzz** [comment]
Okay so the alias are just here for the sake of efficiency (nginx is better to server static files than a node application) . But you can remove them safely since the node application will serve them too.

Just don't forget to edit the `trust_proxy` key in [the configuration file](https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L15)

**Comment by jkirkcaldy** [comment]
So I figured it out.

I needed to replace the alias entries with the proxy_pass info also some of the ssl options were giving me trouble. But that's just as likely an issue on my end.

[Here's my working config](https://pb.themainframe.co.uk/ulizonexik.nginx)

**Comment by tele81** [comment]
> So I figured it out.
> 
> I needed to replace the alias entries with the proxy_pass info also some of the ssl options were giving me trouble. But that's just as likely an issue on my end.
> 
> [Here's my working config](https://pb.themainframe.co.uk/ulizonexik.nginx)

can u post your config?

**Comment by WonderingDane** [comment]
> So I figured it out.
> 
> I needed to replace the alias entries with the proxy_pass info also some of the ssl options were giving me trouble. But that's just as likely an issue on my end.
> 
> [Here's my working config](https://pb.themainframe.co.uk/ulizonexik.nginx)

Do you still have the working config??

**Comment by gabeyww** [comment]
Just since I found this in my journeys to fix this problem, here is my working config:

[peertube-nginx-config-file.txt](https://github.com/Chocobozzz/PeerTube/files/11669540/peertube-nginx-config-file.txt)

Note, I had to comment out this section as well to make it work:

```
  # Bypass PeerTube for performance reasons. Optional.
  #location ~ ^/client/(.*\.(js|css|png|svg|woff2|otf|ttf|woff|eot))$ {
  #  add_header Cache-Control "public, max-age=31536000, immutable"; # Cache 1 year

  #  alias /var/www/peertube/peertube-latest/client/dist/$1;
  #}
```
