### ISSUE TITLE
Problematic strings

### ISSUE THREAD

**Issue by M1dgard** [Chocobozzz/PeerTube#693]
Not all languages have sentence structures that work in the same way as English does. In the `player` resource, I identified some problematic strings, that I believe are naively concatenated. The comma was a dead giveaway here, but there may be more places where this is done.

* `, opens captions settings dialog`
* `, opens subtitles settings dialog`
* `, opens descriptions settings dialog`
* `, opens descriptions settings dialog`

On IRC @Chocobozzz said this was a technical limitation with Angular that should be lifted in a few weeks. They said I could open this issue to track strings like these.

**Comment by Chocobozzz** [comment]
These are videojs strings, so we cannot do anything. Keep this issue opened to track other problematic strings because I'm pretty sure we have some in the Angular application

**Comment by Chocobozzz** [comment]
Closing in favor of https://github.com/Chocobozzz/PeerTube/issues/711
