### ISSUE TITLE
Constructed languages, like Lojban

### ISSUE THREAD

**Issue by M1dgard** [Chocobozzz/PeerTube#694]
While translating the iso639 resource, I noticed that there are quite a lot of local languages, great. How would you feel about adding constructed languages like Esperanto and Lojban? I know there are a lot of instructional videos in Lojban on other sites.

**Comment by F3nd0** [comment]
I think that “constructed” shouldn't be a distinguishing trait for languages. If they're well-established languages with many users and international recognition, I see that as a good reason to include them, whether they're natural or not.

For example, [Esperanto](https://en.wikipedia.org/wiki/Esperanto) is *by far* the most popular [international auxiliary language](https://en.wikipedia.org/wiki/International_auxiliary_language), which has been used every day by many people, for many years. A serious list of global languages could not be considered complete without it. On the other hand, an artistic language like [Klingonese](https://en.wikipedia.org/wiki/Klingon_language) probably holds much less significance in real-world usage, but if many people do use it and create content in it, then it should be included as well.

The real issue should be a technical one; PeerTube (according to [this issue](https://github.com/Chocobozzz/PeerTube/issues/466)) uses [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) codes to identify languages. Apparently, the standard provides codes for only a few prominent constructed languages, which include Esperanto, but not [Lojban](https://en.wikipedia.org/wiki/Lojban) or Klingonese. PeerTube should definitely include all the languages from the list (and ideally have a work-around for other ones).

**Comment by Chocobozzz** [comment]
We already add some specific ISO369-3 languages so it should not be an issue. You just have to tell me what languages to add and I'll add them :)

So for now:
 * Esperanto
 * Lobjan
 * Klingon

That's all?

**Comment by M1dgard** [comment]
There's [Kotava](https://en.wikipedia.org/wiki/Kotava) (639-3 avk).

I also thought about Ido, but according to [Wikipedia](https://en.wikipedia.org/wiki/Ido_language) it has less than 200 users, not really notable.

**Comment by Chocobozzz** [comment]
Done: https://github.com/Chocobozzz/PeerTube/commit/1d94c154689b89b2c5e55f6e12ec25f49b369d52
