### ISSUE TITLE
PeerTube Rooms (livestreamed playlists)

### ISSUE THREAD

**Issue by faissaloo** [Chocobozzz/PeerTube#695]
This is a feature that will allow users to click on a button under a video or playlist to take them to a dedicated livestream of that video or playlist with a chatroom, users can then send a link to the 'room' to their friends or coworkers. This link should be copyable or sharable via other social media sites particularly Twitter, Facebook and Mastodon (when they get a share button).  
This feature would provide a critical advantage for PeerTube over its competitors (especially YouTube) and would facilitate natural growth for the platform among the non-technical (who decentralised projects often have trouble engaging).

**Comment by rigelk** [comment]
I think this is a bit early to think about this, as we don't support livestreaming right now. In the meantime, you can contribute to #151 (issue tracking livestream possibilities), #14 (playlists) and create an issue documenting and preparing the chat feature.

**Comment by faissaloo** [comment]
Yes it's early but I still think it's worth noting down on a wishlist.
