### ISSUE TITLE
Encoding or re-encoding a video generate activitypub notification

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#698]
Hello !

I am currently working to encode my old videos to be able to upgrade to beta8 quietly.

However, I have noticed something that seems strange. Once a video is encoded, it generate a new notification, that appear in Mastodon timeline even if the video was already public (see attachment)

![timelinebug](https://user-images.githubusercontent.com/7755000/41760588-80dd661e-75f4-11e8-95c9-aceae6c4861c.png)

As you can see, the notification is from February, 16, but it's between today's notifications :thinking: 

I am using the script create-transcoding-job through the line:  
`sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run create-transcoding-job -- -v video_id`

I am unsure if this is a bug or normal as the video is in some way added again in the server, so feel free to close if the issue is not relevant ^^

Thanks again for Peertube, cheers for the work ! :hugs: 

Regards

**Comment by Chocobozzz** [comment]
Hello, and thanks for the issue I was not aware of this Mastodon behaviour!

When we transcode a video, the infohash might change. So we send an Update through ActivityPub. I think Mastodon creates a notification when it receives an Update. Not sure if it is a bug or an intended behaviour, but it's not a peertube bug :)
