### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#7]
For now there is no available documentation (except for the [Architecture](https://github.com/Chocobozzz/PeerTube/blob/master/ARCHITECTURE.md)). The idea is to make beautiful documents that would explain the API, code architecture, how to develop...
- [x] Server Rest API documentation
- [x] [Server code documentation (architecture...)](https://github.com/Chocobozzz/PeerTube/blob/master/support/doc/server/code.md)
- [x] [Server CONTRIBUTING.md (tools...)](https://github.com/Chocobozzz/PeerTube/blob/master/.github/CONTRIBUTING.md)
- [x] Client code documentation (architecture...)
- [x] Client CONTRIBUTING.md (tools...)

**Comment by teusday** [comment]
I would be interested in helping, and documentation feels like my speed. Would there be a good place for a newbie to start?

**Comment by Chocobozzz** [comment]
Hi @teusday, glad to hear that.

The goal of these documentations is to help newcommers so IMHO it would be difficult for you to begin with this part.

But I think that documenting the REST API would be feasible. The REST API routes are defined in the [controllers/routes directory](https://github.com/Chocobozzz/PeerTube/tree/master/server/controllers). The [validators middlewares](https://github.com/Chocobozzz/PeerTube/tree/master/server/middlewares/validators) are used to check the user parameters validity of these routes. 

I suggest to use http://apidocjs.com because I like the idea that the documentation is in the same place than the code (to don't forget to update it).

**Comment by Chocobozzz** [comment]
API REST documentation is done, see https://github.com/Chocobozzz/PeerTube#api-rest-documentation

It is not perfect but it's a good place to start thanks to the work of @DimitriGilbert. If you interesting in helping to improve the api documentation, I created a special section in the [CONTRIBUTING guide](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/CONTRIBUTING.md#write-documentation).
