### ISSUE TITLE
Can speed up for video ?

### ISSUE THREAD

**Issue by imtube** [Chocobozzz/PeerTube#70]
The videos which I uploaded to peertube, can I speed up them by webtorrent client on another torrent server ?

I have tested it, it looks like doesn't work, there is no upload speed. Is there any way to make it works ?

**Comment by Chocobozzz** [comment]
You can speed up the video with another torrent client that is compatible with WebRTC (for example WebTorrent in a web browser).

See https://github.com/webtorrent/webtorrent/issues/369
