### ISSUE TITLE
Various pointer related errors after uploading File

### ISSUE THREAD

**Issue by kl4rk** [Chocobozzz/PeerTube#702]
* **PeerTube version or URL:**
v1.0.0-beta.8
* **Browser name/version:**
Chromium 67.0.3396.87
* **NodeJS version:**
v10.5.0

* **What is the expected behaviour?**
1. Avatar: New image is uploaded an user avatar is changed
2. Video: New Video is uploaded and its properties can be changed
* **What do you see instead?**
1. Avatar: Image doesn't change and popup error message Error: Unknown error
2. Video: Video uploads to 100% but while processing the browser is redirected to the */videos/upload page 

* **Browser console log if useful (Gist/Pastebin...):**
Not sure if usefull
1. Avatar: [pastebin](https://pastebin.com/2M7SjBY9)
2. Video: [pastebin](https://pastebin.com/fwSBgLrE)
  
* **Server log if useful (Gist/Pastebin...):**
Both times the error can be 
a) [pastebin munmap_chunk()](https://pastebin.com/QNQv3rKi)
b) [pastebin free()](https://pastebin.com/591QFEwW)
c) [pastebin corrupted size](https://pastebin.com/Mm8tKd7C)
Nginx logs are empty
redis log is empty
postgres log is empty

* **Description:**
After uploading a file various pointer related Errors e.g. "free(): invalid next size (fast)" appear in the peertube log and the Unknown Error PopUp apperars.

The files are stored in their respective path under storage/ but not in the postgres tables.
The postgres connection should be stable, because users can be added and are listed in the tables.

After a reboot avatar images can be changed for a short period but after a few tries the same error appears, videos still can't be added.

* **System:**
I should note that the instance runs on a Raspberry Pi 3 for testing purposes and is therefore not connected with the other instances.
So maybe the error is caused by the 32-Bit OS.

**Comment by Chocobozzz** [comment]
Could you please remove node modules, downgrade to node 8 (we don't test against node 10), `yarn install --pure-lockfile` and try again please?

**Comment by kl4rk** [comment]
That solved the issue, thank you very much!
