### ISSUE TITLE
Increase tags limit per video

### ISSUE THREAD

**Issue by Booteille** [Chocobozzz/PeerTube#704]
I find the tags limit of 5 a bit inconveniant, would it be possible to increase this limit to 10 (or more)?

I don't know if I am the only one, though. What do you think?

**Comment by rigelk** [comment]
We base our limit on [that kind of reason](https://meta.stackexchange.com/a/34743). But admittedly we could go to 10, since our ontology is broader than SO's.

**Comment by Booteille** [comment]
Yeah, I thought about that before posting but I think 10 should be fine, and better for the case of PeerTube, yup.

Especially for news video, containing many differents informations in one video.

**Comment by Zig-03** [comment]
@Booteille 

> Especially for news video, containing many differents informations in one video.... 

which is not advised by professional content creators. Short videos which discuss one topic are the greatest, in terms of SEO, attention retention etc... Long videos have their place too, but in very very rare cases.

5 tags is good enough to me.

**Comment by Booteille** [comment]
Well. Since there are not only short videos discussing one topic and I don't think this should be the only option to make news videos (even if SEO is better on them), I think we should think about others content creators too.

**Comment by Chocobozzz** [comment]
IMHO 5 tags maximum is fine, because it forces uploaders to choose the right tags (not funny I know), so it's more relevant to viewers. More than 5 tags would be difficult for users to picture them mentally, and if all uploaders add 10 tags to every video they upload it would make this field useless.

**Comment by rigelk** [comment]
I guess 5 tags will be plenty enough, especially once we use [Wikidata tags](https://github.com/Chocobozzz/PeerTube/issues/352#issuecomment-377204232). Closing for now until we have more practical clues :)

**Comment by Yetangitu** [comment]
Here's one more piece of input to this discussion. I'm using Peertube to host a few thousand videos from all sorts of sources, this as a companion to an image archive containing photos from the same devices. The photos are tagged with the names of individuals portrayed in them as well as with location tags ('school', 'train', 'plane', etc), activity tags, event tags ('birthday', 'christmas', etc), source tags (camera_type-owner_name) and object category tags ('tools', 'vehicles', 'meteorological phenomena', etc). These are hierarchical tags which makes it possible to find e.g. photos containing 'people' (which is the parent category for names) observing 'meteorological phenomena', e.g. _children looking at a rainbow_ or 'all photos containing person_X at event_Y in year_Z' or 'photos containing person_X but not person_Y'.

While the use of tags to categorise items in this way has been discussed (and denounced by some, defended by others) in practice this is one of the more practical ways to open up a largish archive (50.000 photos, 2500 videos) for exploration. It might not be a canonical, theoretically sound way to use tags but... it works, even for people who are not all that computer-savvy. 

It is also clear that 5 tags are not sufficient to implement this scheme. I increased the number of allowed tags in the instance I use for this purpose. This means that videos shared from that instance potentially fail the tags validator on the importing instance and either loose tags or fail to be imported (I have not followed the code path to find out how it would behave).

One of the ways in which this dilemma could be solved is by having a generic metadata section containing key:value pairs which can be searched in the same way tags can be. This metadata section can be shared in federation, allowing the same search capacity on remote systems. While it is not as 'pure' as the Wikidata-sourced tags it is far more usable for detailed exploration.

**Comment by george110765** [comment]
Whether or not 5 tags is good practice, shouldnt it be up to the user to use the peer tube as they see fit. Or shoudl the length of video also be limited as ppl see that short videos are more effective than long videos etc etc... I can see the above usage case and maybe others would just force ppl to not use peer tube at all.

**Comment by Yetangitu** [comment]
Too many tags without a plan to use them makes for a useless system, just look at the keywords in the header for many web pages or eBay product descriptions where the main purpose seems to be for the page or product to show up in *every* query.

**Comment by Yetangitu** [comment]
A good middle way between overly restrictive tags and tag soup would be for the first `X` tags to be shared with other PT instances. It would still be possible to have more than `X` of them (as I do) but those extra tags do not get shared.

**Comment by tilllt** [comment]
I agree that 5 tags are not enough. The way people organize their information is an individual decision and I find 5 tags very limiting. Especially if you need to put a tag and an alternative (abbreviation, alternative spelling etc)

**Comment by 3risian** [comment]
My main issue with the limited number of tags is that there is (as far as I know) no recommended convention for tagging. Maybe this is a cultural issue, maybe there are ways PeerTube front-end and official sites can help mitigate this.

Motivating case:
Consider a video which is a 'YouTube Poop' (a genre of video remix) using clips from the cartoon _'The Grim Adventures of Billy & Mandy'_ as a source.

(not rhetorical:) How would you tag this video?

First, the genre. 'youtube poop' seems appropriate to me, as does 'ytp' (common abbreviation). Quick searching reveals users simultaneously tagging: (case ignored, many are videos imported from YouTube so IDK if tags were preserved)
* 'youtube poop', 'ytp'
* 'ytp', 'poop'
* 'poop'
* 'ytp', 'parody'
* 'ytp', 'détournement'
* 'youtube poop' [on a video discussing the genre]
* 'peertube poop', 'youtube poop'
* none, lol
I personally thought 'edit' was reasonable

So, just the genre itself has taken up a couple of tags ('ytp', 'youtube poop') to make sure you get most people looking for the genre. However, putting '[YTP]' in the title could reduce this to one tag?

Then comes the source material. How would you type it?

* 'the grim adventures of billy & mandy'
* 'the grim adventures of billy & mandy (TV series)' [I've seen this format on PeerTube]
* 'billy and mandy'
* 'billy & mandy'
I don't think tags match loosely, so even that last tag won't match the first or third. Again, unless it's in the title (unlikely in this genre), you will probably miss other PeerTube videos related to the show.

After this, do we need other tags? 'edit', 'cartoon', 

Unless communities settle on basic tagging conventions (which can be a challenge even in centralized communities unless established early), I think this will end up separating similar content for no good reason.

Possible mitigation techniques I can think of:
1) have a tooltip [that (?) icon] linking to tagging suggestions
2) have an alert show if no-one has used a tag so far, suggesting they search for similar tags 
3) when editing, show in parentheses the number of existing videos with that tag
4) community-driven moderation (comment to authors/moderators asking them to use the most popular version of tags)

**Comment by mpfaff** [comment]
5 tags is absolutely not enough for a hard maximum. I'd be fine with that as a default, but it should absolutely within the administrator's control.

**Comment by quicktrick** [comment]
> I increased the number of allowed tags in the instance I use for this purpose.

Hi @Yetangitu!  How did you do that?  I need it very much, too.

**Comment by stevespaw** [comment]
We also have requests for more tags.... News organizations with stories on various topics

**Comment by Chocobozzz** [comment]
Related feature request: https://github.com/Chocobozzz/PeerTube/issues/1815
