### ISSUE TITLE
Guide on setting up more servers?

### ISSUE THREAD

**Issue by hellomotow** [Chocobozzz/PeerTube#709]
I would like to setup two more nodes each of which contain all the videos for speed purposes. I notice P2P torrent seeds take a bit too long to get started. Is there any guides on this?

**Comment by rigelk** [comment]
Hi @hellomotow! Setting up instances as mirrors of an instance is not yet implemented, but something we plan to do as of #123 (which is btw one of the goals of our crowdfunding). Once it's done we'll make sure to add instructions.

In the meantime you can always script a mirror to seed automatically based on a server's RSS feeds, but that's not ideal.
