### ISSUE TITLE
Video playback goes into HTTP fallback mode when it should not

### ISSUE THREAD

**Issue by mmozeiko** [Chocobozzz/PeerTube#710]
* PeerTube version: v1.0.0-beta.8 
* Browser name/version: Chrome 67.0.3396.87 (Linux & Windows), Edge/Win10
* NodeJS version: v8.9.3 

For some videos I get "HTTP" fallback mode when playing. I assume this does not use P2P streaming, and just downloads mp4 file directly from server.

Strangely enough, if I cut same file a bit shorter, video plays fine and shows "peers" not "HTTP" in player bottom. **Note**: I have disabled transcoding, and I am making PeerTube to play file I've uploaded.

I debugged a bit, and I can see that there is an exception happening in videostream library here: https://github.com/Chocobozzz/videostream/blob/master/mp4-remuxer.js#L311
fragment.ranges array is empty, so this throws `Cannot read property 'start' of undefined` error.

This exception eventually make following error to appear on console log: `VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. `

But I don't think there is anything wrong with file, server or network. Because same file plays just fine if it is just one second shorter!

Here is an example of video where this does happen. This is fragment of Elephants Dream and it is 430 seconds long: [first.mp4](https://drive.google.com/uc?export=download&id=1TxqfGY9V0ClKOUSibipS8LxgBFi9L7RV) (52MB)

If I cut this video just 1 second shorter (429 seconds long) then this error does not happen anymore and file is played back in P2P mode: [second.mp4](https://drive.google.com/uc?export=download&id=1XtlYHd5PhKrhhf-LoI8mRbIeswGenLPV) (52MB)

Second file was obtained from first file with following command:
`ffmpeg -i first.mp4 -c:v copy -c:a copy -t 429 -movflags +faststart second.mp4`

Any suggestions what is wrong with file? Or something else? I assume this is not expected behavior.

Let me know if you need more information.

**Comment by Chocobozzz** [comment]
Thanks @mmozeiko, it was really helpfull. I made a PR in the appropriate repository: https://github.com/jhiesey/mp4-box-encoding/pull/5

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/8ea021ef48fdaf3f2892f08be1aafa84c94b9d81
