### ISSUE TITLE
i18n workflow improvements

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#711]
Some annoyances while translating:
* some strings have leading and trailing whitespace due to indentation in the sources,
* a little description about each string, especially for short strings, would make translating easier. Some strings are ambiguous if you can't see them in context (this is always so in software translation projects). If you could provide a way to do this, I would take it upon myself to describe the strings,
* the "filename" and "line number" context that I see in the XML is not recognized in Zanata.

![screenshot_2018-06-24_13-54-37](https://user-images.githubusercontent.com/4283376/41818812-6e5300aa-77a5-11e8-8895-71a9ed22f621.png)

**Comment by Chocobozzz** [comment]
Please could you tell me if these issues are fixed now we use weblate? https://weblate.framasoft.org/projects/peertube/
