### ISSUE TITLE
Add Brazilian Portuguese translation

### ISSUE THREAD

**Issue by RockyTV** [Chocobozzz/PeerTube#716]
Is it possible to add Brazilian Portuguese (pt_BR) on the translation platform? Most software nowadays have different translations for Portuguese and Brazilian Portuguese.

**Comment by Chocobozzz** [comment]
Are there a lot of differences between them? Since it's just the beginning of PeerTube localization, I would prefer to keep things as simple as possible first :)

**Comment by RockyTV** [comment]
Sorry for the late reply but yes. There are a bunch of different words and they borrow much stuff from English, while the `pt_BR` actually has words for these terms. It's a mess, but unfortunately they have big differences.

**Comment by Chocobozzz** [comment]
Added https://trad.framasoft.org/zanata/iteration/view/peertube/develop/languages
