### ISSUE TITLE
Add Catalan translation

### ISSUE THREAD

**Issue by salvadorpla** [Chocobozzz/PeerTube#717]
Please add Catalan translation. I will start translation as soon as possible.
I’m running peertube.cat for catalan people so having our native language available of course will be really nice.
Thank you for the great job! Peertube is so cool!

* **PeerTube version or URL:**
* **Browser name/version:**
* **NodeJS version:**

* **What is the expected behaviour?**
* **What do you see instead?**

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

**Comment by Chocobozzz** [comment]
Added https://trad.framasoft.org/zanata/iteration/view/peertube/develop/languages :+1:
