### ISSUE TITLE
Correct me if I'm wrong. Sounds bad for the average viewer

### ISSUE THREAD

**Issue by lcompote** [Chocobozzz/PeerTube#719]
So there will be no single domain where people can browse and watch vids from all the instances since every instance decides which ones to follow and which not. People don't wanna move between sites (domains) to watch videos. That's clear as day. Let's just say if people aren't lazy enough, which they are, I can't be bothered with this instance mess to be honest, most of them will flood the most popular instances with free speech and fewer limits and the high follow count which populate instances' catalogs with the highest number of vids which will lead to certain instances (a couple maybe) getting to the top and controlling everything and dictating its policies, the rest of the instances will die out or will be zombie towns. If the most popular instances got the best freedom of speech rules that's good if so. We've got youtube situation here already. Then what? Somebody gets a ban over something or conflict with the instance owner or whatever. How is he supposed to move his content since instances don't even communicate on such a level. He will have to register on another less popular instance and upload its content basically losing everything. 

This idea seems too decentralised. Correct me if I'm wrong but I don't see how this will take off. 
There should be one domain with the highest freedom rules possible and everyone who wants to set up server and offer space or whatver has to connect to the main domain so it actually feels like youtube experience for the average user. There has to be one single video catalog and one domain and one set of rules other wise this whole thing won't get anywhere.

**Comment by rigelk** [comment]
I wouldn't be so sure about what users want. Single rulesets are exactly why people are leaving YouTube.

What you want is a looking glass to all PeerTube instances. This has been suggested by @hoodiek in #631.

> since peertube (and this is not a tech side evaluation, this is from the user perspective) seemingly does not require much overhead to actually display a video from a different service/instance, due to the torrenting based nature of videos, this means that the primary onboarding / user experience can be extrapolated/experienced by a non-user of the service: the act of browsing trending and watching videos does not need an account.
> this means, should a 'no-user' or 'view-only' sort of option exist for instances of the service, the instance list could become integrated into the tech itself pretty easily, and the onboarding site could simply link to a 'official' instance that is relatively cheap to upkeep, as it would not have any users, and would only store instances-it-federates-with-data. making such an official portal, but disallowing users to login/create accounts and such, allows for the onboarding process to be GREATLY improved at (again, from a non-programmer or hoster view) seemingly little cost.

For now you can setup an instance to follow as many instances as you like, and have you own looking glass. It's not perfect, but it works. And YouTube is far from perfect: their search works, but that's basically it. And their home page is not as helpful as the video suggestions. I'm not sure we want to make the same mistakes… As for our search, it will soon be rewritten, so hopefully discovery will be easier.

Account migration is issue #549. It's not an easy one, so it might take some time. But I get your point. Ideally one would have a replication of their account as Hubzilla does. It's neat and it's what I would like to see long term too.

**Comment by lcompote** [comment]
What he says doesn't actually seem like even any kind of improvement. So my criticism still stands.
Don't kid yourself. The average viewer doesn't want jump from one site to another to watch vids. That's ridiculous to claim otherwise. 

I think it should be clear I wouldn't be here if I liked youtube or something something.
Unless you pack this whole thing to meet the 3 criteria I mentioned you guys are wasting your time. 
It beats me how you don't see that.

**Comment by lcompote** [comment]
Oh look at that I got 2 laughing reacts. That's LOL for me! Prove me wrong dummies.

**Comment by benrob0329** [comment]
You don't jump to a different site to watch the video, have you even used PeerTube?

**Comment by lcompote** [comment]
Oh yes I did. You's the one who doesn't seem to get it
Helloooooo who said a particular instance will follow every other out there to create a comprehensive vid catalogue

**Comment by EliotBerriot** [comment]
Peertube is absolutely useless as a project. it does not serve any purpose. I completely agree with you.

That's probably why hundreds of people gave thousand of euros over the past weeks to support it's developpment. That's also why instances are popping every days and the global library growing as well, why we are starting to see some interest about the projcect in mainstream medias, why bigger players like the Blender Foundation are trying it as well.

Peertube does not have to be centralized to work because centralized solutions already exist. It does not even have to be a concurrent to centralized software: it just have to be different and address user cases that are not properly fullfilled by centralized solutions (like having control on your content, or being more resilient to censorship).

The point of building an alternative is exactly that: build something different, that will attract different people, for different reasons.

I'd like to thank everyone involved in Peertube's development (including documentation effort, support, translators, etc.) for working on this project. Despite what is being said in this really aggressive issue, you are doing something that matters, and it does not have to be a billion-users network to be successful.

I wish you the best.

**Comment by benrob0329** [comment]
>Helloooooo who said a particular instance will follow every other out there to create a comprehensive vid catalogue.

I'm alright with every instance not following every other instance, I'd rather keep a porno instance out of my feed thank you very much. However having following be based on who the user follows (like mastodon) is probably a good default (with instance blocking as well).

**Comment by lcompote** [comment]
Aggressive issue? hahaha Omg western cucks! Everything is aggressive. My bad I have forgotten I deal with positive retarded robots hahaha


Hundrends of euros? hahah Cos they're as naive as you.  You know this thing called kickstarter? Do you know the percent of projects coming to fruition?  
Interest in mainstream media? hahahah Minds gab and others are stagnating.... so again it means shit.

Attract different people?! hahahah like old farts who don't use tech? There's one certain group of people who are interested in the online vids. There's no other group

Why don't you go and shill somewhere else and let smart people talk. BYE!

Who's next?!

**Comment by lcompote** [comment]
benrob0329 

hahahaha Porn is already a separate thing you fool. Porntube and stuff. Again you don't have an argument

NEXT!
