### ISSUE TITLE
Looping support

### ISSUE THREAD

**Issue by algotruneman** [Chocobozzz/PeerTube#721]
* **PeerTube version or URL:**
* **Browser name/version:**
* **NodeJS version:**

Feature suggestion.
To better support GIF conversions, offer a user-selectable option to loop the "video".

![rotate10](https://user-images.githubusercontent.com/1197187/41858967-1433ee1c-7869-11e8-83fb-252a1df73c12.gif)

Conversions to either ogv or webm do not stream, although they do work once downloaded back to my computer.

* **What is the expected behaviour?**
* **What do you see instead?**

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

**Comment by bodqhrohro** [comment]
Not only GIFs, but looping any video would be great. Especially if video and audio could be looped separately: that way, PeerTube will become an alternative not only to traditional video hostings, but also to things like Coub.

**Comment by Chocobozzz** [comment]
Hi, this is already implemented in 1.4

**Comment by Booteille** [comment]
Can the option to auto-loop be added to the native player, not only on embed videos?

**Comment by rigelk** [comment]
@Booteille please open an issue instead of replying to an old closed issue.

**Comment by Booteille** [comment]
Yes, my bad. Since it's the same subject I thought you would maybe re-open this issue.

I opened #2662.

Thank you.

**Comment by rigelk** [comment]
@Booteille it's not easy to track issues that way, so we generally don't reopen for variations of a subject.
