### ISSUE TITLE
Add Esperanto locale to Zanata

### ISSUE THREAD

**Issue by F3nd0** [Chocobozzz/PeerTube#722]
I have registered at Framasoft's Zanata instance following [these instructions](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/translation.md), linked to from [this issue](https://github.com/Chocobozzz/PeerTube/issues/148). As I'd like to translate PeerTube into Esperanto, I have joined the Esperanto team. However, after visiting PeerTube's project page, I was only presented with 13 languages, which did not include Esperanto, and no option to add a new one.

Therefore, would you please add Esperanto to the list, or provide clarified instructions on how to do so? (Because if it's possible for me to do it myself, then I did not figure out how.) Thanks!

**Comment by Chocobozzz** [comment]
Added :) https://trad.framasoft.org/zanata/iteration/view/peertube/develop/languages
