### ISSUE TITLE
Language preferences/filters

### ISSUE THREAD

**Issue by dixonge** [Chocobozzz/PeerTube#723]
Need to be able to filter videos out by language - foreign-language audio without closed captioning would be rather pointless, so would prefer to not have to scroll through dozens of them. Probably some sort of preference for language (preferred language) as well as filtering option.

**Comment by rigelk** [comment]
For reference it should be related to #60. Outside of searches, it also has to do with a user's own preferences to filter videos from the instance views (and thus with QoE as well as anti-harassment filtering). Maybe we should make the scope more global than just language filters.

**Comment by Chocobozzz** [comment]
I would prefer to keep issues as simple as possible containing 1 specific task. So for the anti-harassment filtering please create a dedicated issue.

**Comment by Strit** [comment]
I would also echo the need for this.
Most of the instances that's connected to mine are french (it seems), and I can't speak, read or understand french, so it's all just clutter for me. :slightly_smiling_face:

**Comment by Chocobozzz** [comment]
@Strit Add a :+1: to the issue :)

**Comment by MayeulC** [comment]
Also, this should probably default to what's reported by the user's browser, for users that are not logged-in, and for their defaults upon registration. (While providing obvious feedback that the video list was restricted to these criterion).

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/3caf77d3b11f2dbc12e52d665183d36604c1dab9 & https://github.com/Chocobozzz/PeerTube/commit/a5f8b0b49f09e4399a8176d5cd06cc80c61b07d8
