### ISSUE TITLE
issue npm run release 

### ISSUE THREAD

**Issue by PhieF** [Chocobozzz/PeerTube#724]
Hi !
on current dev
running
npm run release version-number

crashes at 

npm version --no-git-tag-version --no-commit-hooks "$1"

of the client (same issue for server, I guess)

my npm version is 6.1.0

Is there something to do before creating a release ? I've got to do that because I've modified a bit peertube source code to have new links on left menu for my instance (cf my repo exode)

Thanks !

**Comment by rigelk** [comment]
The release script is meant to be run by @Chocobozzz as it involves `scripts/release.sh` and publishing signed archives (among others).

What do you want to achieve?

**Comment by PhieF** [comment]
just building a clean zip and sending it to my git repo, to make an easy upgrade of my instance, I've modified it accordingly
