### ISSUE TITLE
Improve licence selection and presentation

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#726]
At the moment, when uploading a video, the user is presented with an option to choose a licence, but the actual options don't look like licences; they're only combinations of various licence traits taken from the Creative Commons licences (“Attribution”, “Share alike”, etc.), but it's not at all clear what those mean by themselves.

According to what @rigelk wrote on IRC, the option is supposed to present exact licences to choose from. If that's the case, the licences should be explicitly marked as such. Each licence name should therefore start with “Creative Commons”, or possibly take the abbreviated form of “CC”. The user should be provided with a link to the given licence, and not only at the selection, but also in the information box that's below each video being watched.

In addition, I would like to ask for [Free Art License](http://artlibre.org/licence/lal/en/) to be added to the list, which is another libre licence – but maybe I should open another issue for that?

**Comment by Chocobozzz** [comment]
@F3nd0 Thanks for the issue, you're totally right. There is no need to open another issue for Free Art Licence, since it covers the same component.

**Comment by emorrp1** [comment]
For reference if someone wants to work on an extended license selection, I really recommend [SPDX identifiers](https://spdx.org/licenses/) for computer-readable forms (available in e.g. XML). It is obviously biased towards code relevant licenses, so some search ability might be desired and others added.

Specifically regarding the Free Art License, there are [discussions](https://lists.debian.org/debian-legal/2011/01/msg00042.html) around whether it succeeds in its goal at being libre, but I don't think that should affect its inclusion for PeerTube purposes.

**Comment by frankstrater** [comment]
After a lot of preparation we have funded a small project team ([extending-peertube](https://github.com/beeldengeluid/extending-peertube/projects/1)) who are working on this specific issue of license selection and presentation. 

We will make a strong case (in a future blog post) for properly using and presenting CC licenses, but will try not to overhaul the existing licensing system, which in it's flexibility allows for extending/replacing the licenses (for example with a PeerTube [plugin](https://docs.joinpeertube.org/#/contribute-plugins?id=update-video-constants)).

[This pull request](https://github.com/Chocobozzz/PeerTube/pull/3306) is a small start, which we consider an improvement for inclusion upstream as it mainly helps choosing one of the existing default licenses, although it's true they need "CC" or "Creative Commons" to be considered real.

**Comment by frankstrater** [comment]
The link to the licenses on selection (during manual upload/import) was already added in this pull request https://github.com/Chocobozzz/PeerTube/pull/3306 By adding the link to the CC licenses chooser this addressed one part already.

We have just released a PeerTube plugin (version 1.0) named 'creative-commons' that addresses the other points. See:

https://www.npmjs.com/package/peertube-plugin-creative-commons

We also wrote some posts on creating this plugin, which might also help if you want to write your own plugin for adding other licenses like 'Free Art License'

https://beeldengeluid.github.io/extending-peertube/
