### ISSUE TITLE
Wishes.

### ISSUE THREAD

**Issue by zzoozzo1122** [Chocobozzz/PeerTube#727]
Wishes.
Using two servers,
The first server is a high performance server

The second server is a server with a lot of hard disk capacity

After transcoding from server # 1, it automatically goes to # 2

I wish.

I would like to have a way to connect server # 1 and server # 2.

If you have a lot of videos because you are transcoding with one server
It works too slowly.

Or is there a similar method already included in the program?

**Comment by Chocobozzz** [comment]
Hi,

I think you could do that with union mount filesytems. See https://github.com/Chocobozzz/PeerTube/issues/605#issuecomment-393133930
