### ISSUE TITLE
oEmbed discovery and author_url missing

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#728]
I don't know if it would help for integration in Diaspora* (https://github.com/diaspora/diaspora/issues/7792) or others, but it might be nice to add oEmbed discovery in the video/watch view headers, see : https://oembed.com/#section4.

And about oEmbed, author_url is missing on the json returned by the endpoint.

**Comment by gegeweb** [comment]
I've look at the code (and the html source), the link tag for oEmbed is already present (beta.9).
It is added by the function `addOpenGraphAndOEmbedTags` in `server/controllers/client.ts`.
Perhaps just missing `&format=json` in `oembedLinkTags.href` string.

So, just the author_url property is missing on the json. ;)
But i diden't find where fix it.

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/49799b165e3cd547f1dbb23bd31369baca0b39da

Thanks for the issue @gegeweb
