### ISSUE TITLE
Chocobozzz. Locked my thread cos not you nor anybody else on the forum has any kind of counter argument hahaha

### ISSUE THREAD

**Issue by lcompote** [Chocobozzz/PeerTube#730]
You just proved that I'm right by locking the thread
You got nothing. You're doomed to fail! If you had a case you would easily counter my argument.  
You're probably a leftist french frog that blocks people whose opinion he doesn't like hahahaha That's what leftists do - they censor people and try to shut them up when they don't have an argument LOOOOOOOL
And you're trying to build a decentralised censorship resilient alternative ? HAHAHAHHAA Look at you.

**Comment by Chocobozzz** [comment]
:'(

**Comment by rezonant** [comment]
This is not a forum, this is not Twitter or Reddit. This is a bug tracker for the Peertube project. If you aren't going to be productive and professional, please leave. If you don't like the direction of Peertube and are unable to articulate it in a respectful and professional manner, go build your own alternative. Starting a project on Github is free. Please see The Code of Conduct on how to conduct yourself while interacting with this project.
