### ISSUE TITLE
Access-Control on the PeerTube REST API

### ISSUE THREAD

**Issue by rezonant** [Chocobozzz/PeerTube#731]
Right now PeerTube doesn't explicitly set any CORS/Access Control headers. These headers are important to allow Javascript applications running in the browser to interact with the REST APIs provided by PeerTube instances.

Different media providers (ie YouTube, Vimeo etc) handle this differently - some just leave it open (`Access-Control-Allow-Origin: *` et al), some allow only a registered origin (though this is rare), and still others require that you pass `origin=mydomain.com` as a query parameter.

Without any Access Control headers (which is how PeerTube ships now afaik), an application must stand up a server to handle talking to PeerTube's REST API (unless the JS is hosted on the same domain as the instance itself), and have their Javascript application use the relay. Every 'Tube API I've worked with until now has allowed for in-browser JS apps to access their APIs, PeerTube should too!

Has there been any discussion on this topic yet? If there's general agreement on the behavior, I'd loveto work on this as my first contribution to the project!

PS: PeerTube is definitely one of the most exciting projects I've seen in the media-space for quite some time. The potential is really here to disrupt video distribution, and video distribution desperately needs to be disrupted. Much :heart: to @Chocobozzz and everyone else in this community for making something so innovative :-D

**Comment by Chocobozzz** [comment]
Sure, go for it! You can take example from https://github.com/Chocobozzz/PeerTube/blob/develop/server/controllers/static.ts#L17

**Comment by rezonant** [comment]
This is all set with #741
