### ISSUE TITLE
Before implementing subscription...

### ISSUE THREAD

**Issue by PhieF** [Chocobozzz/PeerTube#732]
Hi !
It would be nice to display a subscribe button in channel / accounts which will redirect to a web page explaining that the function hasn't yet been implemented, and a short explanation on how to subscribe to channels with rss feed reader for example or with mastodon, etc

**Comment by rigelk** [comment]
There is already an helper popover explaining how to subscribe with Mastodon.

**Comment by rigelk** [comment]
@PhieF why would you need SQL to display help messages? :sweat_smile: 

It's probably a better idea to put fake buttons than just these helpers:

![2018-06-27-145349_102x92_scrot](https://user-images.githubusercontent.com/6329880/41975057-f56bdf28-7a19-11e8-9911-e9d617232537.png)
![2018-06-27-145359_314x224_scrot](https://user-images.githubusercontent.com/6329880/41975062-f6dd8f28-7a19-11e8-8ac0-82ae98bc26a7.png)

**Comment by PhieF** [comment]
Well I was trying to implement the real subscribe feature haha, so I was just, you know, looking at how DB are managed in peertube, node JS stuffs are pretty new for me. I know it's already in progress but it is a way to better understand peertube in case I want to help for other things

**Comment by rigelk** [comment]
Ah I see. Well that isn't the easy way to begin with, but anyway it's never easy to begin with a new codebase, honestly. At any rate, please ask for help on IRC to help with it.

**Comment by Chocobozzz** [comment]
Closing since there is this help button. Feel free to make a PR to improve it though
