### ISSUE TITLE
Provide option to store the source video file

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#733]
Be it for archival, or just to provide a way to transcode again without a potentially degraded source (the highest transcoded resolution is still a lossy version of the source video file), we might want to store the source video file along, and allow to download it (but not stream it).

Not everyone might be interested by this, of course, but it could certainly interest data preservation projects in general.

**Comment by rzr** [comment]
Yes this is helpful, specially when original format is free (ogv, webm).

**Comment by rigelk** [comment]
Should we allow users to save the source video file by default? I can see admins wishing to prevent users from keeping the source video file since it's additional storage, but that will unevitably restrict its usage a lot. Another option is to allow it by default so long as the bitrate stays under a known limit: it prevents users just pushing rushes from their camera with no regards to the file size, and allows unoptimized albeit better quality/other format videos to stay.

**Comment by Chocobozzz** [comment]
I think we should disable it by default, and not use the bitrate trick: it will be confusing for users and potentially admins to understand why original files of some videos are stored, and other are not.

**Comment by flaki** [comment]
Is this issue open for contributions? I'm using a self-hosted PeerTube instance both for archival of my own content and for integrating with the rest of the fediverse, but PeerTube not keeping around the originals both defeats the first purpose (causing inconvenience, having to keep the original files around) and also often making high-bandwidth videos unusable on default transcode levels (data loss, where PeerTube was the original source and the file is no longer available in its source form).

I am currently looking into patching my own instance to keep the old files around and would be happy to contribute a patch, but it's unclear to me from the current conversation what's the stance around this issue.

**Comment by chagai95** [comment]
> I am currently looking into patching my own instance to keep the old files around and would be happy to contribute a patch, but it's unclear to me from the current conversation what's the stance around this issue.

We started working on a patch, would you be interested in helping us? I think the stance is pretty clear now.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/6157

The option has to be enabled by the admin. Owners/moderators/admins can download the original file and we include it in the user export archive.
