### ISSUE TITLE
Option for videos to not go live until Transcoding finished

### ISSUE THREAD

**Issue by hellomotow** [Chocobozzz/PeerTube#737]
I think there should be an option to make videos not appear until transcoding has finished. Most new videos don't need it but it's a nice feature if like me you know you're uploading old videos.

**Comment by gegeweb** [comment]
This feature is implemented in the 1.0.0-beta.9, no ?
This option is checked by default after uploading and before to publish.

One of the side effects is that if you modify the video to publish it without waiting after first publishing with the option, it will only be federated at the end of transcoding.
At least that's what I saw yesterday.

**Comment by hellomotow** [comment]
Yes this is already added, did not upgrade
