### ISSUE TITLE
Bug in dns.js or misconfiguration on remote instance ?

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#743]
* **PeerTube version or URL:** 1.0.0-beta.9

* **What is the expected behaviour?**
Trying to ad a follow request to videos.iut-orsay.fr 
 
* **What do you see instead?**
Don't know when and where videos.iut-orsay.fr become videos.iut.orsay.fr (a dot isntead of a dash beetween iut and orsay).

I've checked the post request params, it's good.

<img width="1106" alt="capture d ecran 2018-06-28 a 07 56 28" src="https://user-images.githubusercontent.com/9108457/42016040-33830b02-7aaa-11e8-89d7-c73952a237e4.png">

* **Server log if useful (Gist/Pastebin...):**

```
[peertube.gegeweb.eu:443] 2018-06-28 07:59:14.452 info: 146.185.159.169 - - [28/Jun/2018:05:59:14 +0000] "POST /inbox HTTP/1.1" 204 - "-" "-"
[peertube.gegeweb.eu:443] 2018-06-28 07:59:21.061 info: Processing ActivityPub follow in job 7047.
[peertube.gegeweb.eu:443] 2018-06-28 07:59:21.164 info: Fetching remote actor https://videos.iut.orsay.fr/accounts/peertube.
[peertube.gegeweb.eu:443] 2018-06-28 07:59:21.171 error: Cannot execute job 7047. {
  "meta": {
    "err": "Error: getaddrinfo ENOTFOUND videos.iut.orsay.fr videos.iut.orsay.fr:443\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)"
  }
}
```

```
# host videos.iut-orsay.fr
videos.iut-orsay.fr is an alias for solo.iut-orsay.fr.
solo.iut-orsay.fr has address 192.70.36.21
```

Similar error with tube.ac-lyon.fr wich reply with a bad hostname : 

```
[peertube.gegeweb.eu:443] 2018-06-28 08:16:30.234 error: Cannot execute job 7056. {
  "meta": {
    "err": "Error: getaddrinfo ENOTFOUND peertube-dane.in.ac-lyon.fr peertube-dane.in.ac-lyon.fr:443\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)"
  }
}
```

**Comment by bristow** [comment]
If there is something to do, i can do some tests on tube.ac-lyon.fr.
Thanks

**Comment by gegeweb** [comment]
You can check config/production.yaml and look if the hostname in the server section is tube.ac-lyon.fr : 

```
webserver:
  https: true
  hostname: 'example.com'
```

If yes, it is possible (I don't relly know how its works) the first time you launch Peertube peertube-dane.in.ac-lyon.fr was the hostname.
And probably that hostname is now stored somewhere in the database. 

We send a post request to tube.ac-lyon.fr and the response is with peertube-dane.in.ac-lyon.fr.
try to set a CNAME for peertube-dane.in.ac-lyon.fr to tube.ac-lyon.fr and on the http server side redirect request send to peertube-dane.in.ac-lyon.fr to tube.ac-lyon.fr.
Not sur it will works!

I think same "bug" with videos.iut-orsay.fr, probably a typo in production.yaml.
But my apprentices who are from the Orsay IUT don't know who administers the case and besides didn't know Peertube! ;)

**Comment by gegeweb** [comment]
I had the same kind of problem with Status.net. You shouldn't change your hostname after the fact.
Mastodon has an alias mechanism in its configuration to handle this.
This must be linked to the functioning of the protocols used for the federation.

**Comment by Chocobozzz** [comment]
With beta 9 you are now warned at peertube startup if there are inconsistencies with the current domain name and AP urls. You'll need to run `update-host` script that will update the database and torrent URLs
