### ISSUE TITLE
cloudflare+ peertube  

### ISSUE THREAD

**Issue by zzoozzo1122** [Chocobozzz/PeerTube#744]
cloudflare upload limit 512MB

Is there any way to use it?

I want to upload up to 4GB,

There seems to be no way.

"import-videos.js" Will it work when I upload it using this?

**Comment by rigelk** [comment]
Cloudflare actually limits uploads to less than that, but it’s "per request", a single HTTP transaction.

**Comment by Chocobozzz** [comment]
I'm sorry but I don't use cloudflare so I cannot help you.

Maybe you could  try to bypass cloudflare dns, or run import-videos directly on your server.
