### ISSUE TITLE
Add a way to contact instance admin

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#745]
If not specified in the about, terms or description, there is no way to contact the administrator of an instance.

Why not a contact form to not expose the email address?

**Comment by kyrahabattoir** [comment]
Shouldn't it be up to the instance admin if they wish to be contacted?

**Comment by ChameleonScales** [comment]
Being an admin is a responsibility. There should be some form of contact in order to address issues like bugs, abuse and software upgrades.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/a4101923e699e49ceb9ff36e971c75417fafc9f0 & https://github.com/Chocobozzz/PeerTube/commit/3866f1a02f73665541468fbadcc3cd2cc459aef2 & https://github.com/Chocobozzz/PeerTube/commit/d3e56c0c4b307c99e83fbafb7f2c5884cbc20055

(opt-out)
