### ISSUE TITLE
Cap the maximum resolution to the screen resolution

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#746]
*note*: adapted from https://framacolibri.org/t/choix-automatique-de-la-resolution-video/3204

Right now the resolution is selected automatically in order to fit the maximum bandwidth the connection allows. However it doesn't make sense to watch a 1080p video on a 720p screen, for instance.

Adding a check detecting the current window size and adapting the resolution if necessary would fit the use and allow to avoid consuming more bandwidth than necessary.

**Comment by Chocobozzz** [comment]
Do we check the window size of the video element size?

**Comment by rezonant** [comment]
As a side note, does PeerTube use adaptive bitrate streaming or is it a one time bandwidth check before playback begins?

**Comment by rigelk** [comment]
@rezonant it is adaptative.

**Comment by rigelk** [comment]
@Chocobozzz we should check for the video element size.

**Comment by ns23** [comment]
Can I take this issue ?

**Comment by rezonant** [comment]
Implementation should continually affect the adaptive bitrate selection as well, to handle upgrading resolution when going full screen, resizes etc

**Comment by Chocobozzz** [comment]
@ns23 sure!

**Comment by ns23** [comment]
Can you suggest me any start point, from where I start working on this issue.

**Comment by Chocobozzz** [comment]
In this function: https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/assets/player/peertube-videojs-plugin.ts#L361

We choose the appropriate resolution. You could just reject resolution (in fact this is the video width) that are > to the width of the video element.

**Comment by ns23** [comment]
Okay, I will go through the code, and start working on the issue

**Comment by Chocobozzz** [comment]
Yep, but put it before the current filter function:

```
const filteredFiles = this.videoFiles
  .filter(... your filter)
  .filter(... current filter)
```

**Comment by ns23** [comment]
Okay, I will make the changes and create a PR
