### ISSUE TITLE
Incorrect REST API documentation

### ISSUE THREAD

**Issue by tomdug** [Chocobozzz/PeerTube#752]
The documentation for the REST API provided [here](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/api/openapi.yaml) has some inconsistencies.

E.g. for `/videos`, the doc indicates that it requires `start` & `stop` (first and last page). Although, it actually requires `start` & `count` (offset + number of items). This applies for other requests as well.

**Comment by Chocobozzz** [comment]
Thanks @tomdug, it should be fixed: https://github.com/Chocobozzz/PeerTube/commit/330eaf12969ed0f15f93d5dd50599885f62ffbed
