### ISSUE TITLE
Display extra information about a video when focusing it on a listing

### ISSUE THREAD

**Issue by 945fc41467** [Chocobozzz/PeerTube#759]
Hello,
One thing is missing when we are navigating on peertube : a resume of the video to know if I should click it or not. Maybe in a tooltip or in a specific frame when the cursor or the selection is on a video. Or something like simple click to select the video and show the resume, double click to play (or enter if the video is already selected). I prefer the idea of the tooltip to be honest. But whatever is the solution chosen, I think the possibility to see the synopsy before choosing the video is important.

**Comment by rezonant** [comment]
So to restate the request: A user should be able to view additional information about the video without having to play it (or without having to set Autoplay to false if they are signed in). This could take the form of a hover-over on desktop, for instance.

Hover-overs can often be obtrusive, so it's difficult to accomplish without irritating other users. But given that PeerTube default to autoplay and playing a video is a somewhat public affair (at least for your IP address) it may be worth some discussion.

**Comment by 945fc41467** [comment]
> A user should be able to view additional information about the video without having to play it
To be sure we understand each other: a user should be able to view additional information about a video without to open it. Directly from the local/trending/recently added view of the instance, where there is the list of all the videos.
If I take the demo instance as example, I should be able to access information on the video Björg - Ma télévision directly from [this view](https://peertube2.cpy.re/videos/trending?sort=-views&page=2), without having to click on the video to access [the video](https://peertube2.cpy.re/videos/watch/626da0a4-5d86-4f2c-a7e8-39ece9214d18) (playing or not, that’s another question).

After, the way it is implement is an open discussion. I agree it should not be to much obtrusive. Presently, when the mouse is over a video, a tooltip with the full name of the video appear. The same thing with the name in bold and additional information in regular font is a possibility. Another is a dedicated frame somewhere on the interface, for exemple, under the "about" link in the left panel, or in an additional panel at the right or the bottom. There is lots of possibility. This is also possible to offer to the user to disable this functionality (for example to close the dedicated panel to gain space on little screen) if you judge the solution is still obtrusive.

I don’t really care to the retained solution, but I really would like to be able to have information on video without opening a new tab, and reclosing it or changing page and undo it. This is also important to help to recognise clickbait, ambiguous or second degree titles, all this kind of things.

I hope my English is clear enough.

**Comment by Chocobozzz** [comment]
Closing this inactive discussion. Don't hesitate to comment if you want to reopen it.
