### ISSUE TITLE
Filter video list

### ISSUE THREAD

**Issue by sschueller** [Chocobozzz/PeerTube#760]
Hi,

I can't find an example of how I can filter the list provided by the API. I see in the code there is `req.query.filter` but setting `filter` in the GET query doesn't appear to have an affect. I also don't see `filter` in the API docs so I am not even sure that would work.

I am trying to filter NSFW which I see also has an option but that appears to apply only to logged in users.

How do I need to structure the call if filter is available?

I tried but it didn't work: 
```
https://troll.tv/api/v1/videos/?start=0&count=100&sort=-publishedAt&filter=nsfw%3Afalse
```

Thanks in advance.

**Comment by rezonant** [comment]
Looks like you cannot filter out NSFW with an API parameter with the code as written. You can only set the hide NSFW option as a user. I think this would be a good enhancement, pehraps modifying `isNSFWHidden` in `server\controllers\api\videos` to take `req` and check for a query parameter there (perhaps `nsfw=0`)

**Comment by Chocobozzz** [comment]
Hi @sschueller,

As @rezonant said, currently the backend automatically filter NSFW videos according to the user preferences. I agree adding a req filter would be nice, for unlogged users or convenience.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/d525fc399a14a8b16eaad6d4c0bc0a9c4093c3c9

You can add `nsfw=true|false|both` in videos endpoints that will override user and instance preferences.
