### ISSUE TITLE
Playback API for Embed

### ISSUE THREAD

**Issue by rezonant** [Chocobozzz/PeerTube#762]
It should be possible to programmatically control a PeerTube video embed iframe as well as to pass more of the standard HTML media options such as muted, loop, controls etc to the embed. I've been investigating this and I think the JSChannel library from Mozilla would be a great way to manage the complexity of cross-frame messaging between the embed and it's host.

**Comment by rigelk** [comment]
Thanks for the pointer to JSChannel @rezonant ! But #468 already covers this. Why not detail further your proposition there?

**Comment by rezonant** [comment]
Closing, continuing discussion on other issue
