### ISSUE TITLE
Playback error: No compatible source was found for this media.

### ISSUE THREAD

**Issue by F3nd0** [Chocobozzz/PeerTube#767]
* **PeerTube version or URL:** https://peertube.video/videos/watch/a8ea95b8-0396-49a6-8f30-e25e25fb2828
* **Browser name/version:** [Iceweasel 59.0.2 (64-bit)](https://www.parabola.nu/packages/libre/x86_64/iceweasel/)
* **Operating system:** [Parabola GNU+Linux-libre](https://www.parabola.nu/)

I expect the video to be played normally in my browser, but instead I am shown a black screen in place of the video, with the text: No compatible source was found for this media. This happens on Iceweasel 59 (Firefox modified for [Parabola](https://www.parabola.nu/)) and Abrowser 60 (Firefox modified for [Trisquel](https://trisquel.info/)) on my system.

WebRTC should be enabled; it may not have been by default, but I have changed the approriate settings in about:config, and Jitsi Meet, for example, seems to work. In fact, I have reverted all of the settings in about:config to their default values in Iceweasel, but that fixed nothing.

In the normal Firefox 61, the video plays without any issues. It worked even after I disabled the OpenH264 plugin (to see if that might be required). Maybe the derivative browsers make some deep changes that break PeerTube? Is there a way I could collect more useful informations about this issue?

**Comment by rezonant** [comment]
I believe the transcoding outputs mp4/h.264, perhaps Rigel can correct me if I'm wrong on that. If so, I suspect iceweasel doesn't support the codec (probably intentionally). There is an enhancement issue open for transcoding with FLOSS formats which for HTML5 video would mean WebM.

**Comment by rezonant** [comment]
Oh I see you disabled Open264 on FF so maybe that's not the reason?

**Comment by Zig-03** [comment]
https://github.com/Chocobozzz/PeerTube/issues/481

**Comment by F3nd0** [comment]
> If so, I suspect iceweasel doesn't support the codec (probably intentionally).

It appears that you were right, although it seems to be a bug, rather than intention. [Here](https://labs.parabola.nu/issues/1837) is the relevant bug report for Iceweasel. It should get resolved once they release a new major version, so I'll be reporting back once that happens. (I suppose decoding proprietary formats with libre software is alright with them?)

> #481

It would seem that the specification for AV1 has been finalised, so hopefully we'll get some practical coding tools in the coming years!

**Comment by Chocobozzz** [comment]
Okay so I think we can close since it's not a peertube issue :)

**Comment by VitaliyAT** [comment]
You close it but no any recommendations. I meet this problem but not clear what I should do.
