### ISSUE TITLE
Integrating external platform in PeerTube federation

### ISSUE THREAD

**Issue by dfeyer** [Chocobozzz/PeerTube#769]
We work on a video platform. We focus on "premium" content, with a feature set to create transcript, captioning, distribution of protected and public content. Peertube is a really nice intiative, and we want to support it. We are in the planning phase, did you have any documentation on how we can provide/consume content from/to PeerTube instance ?

**Comment by rigelk** [comment]
Hi @dfeyer and thanks for the interest. Curious of what you are planning here, but I guess that it's a bit early to ask.

We have an [API documentation](https://github.com/Chocobozzz/PeerTube#api-rest-documentation) visible [here](https://htmlpreview.github.io/?https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/api/html/index.html).

**Comment by dfeyer** [comment]
It's early on my side too ;) I have different ideas, but basically we want to be able to federate public channel from our platform to Peertube, and subscribe to some peer tube instances. Need to build a prototype to see how this can works. Our platform will be opensource too, so sounds like a good move to collaborate on this. I can not promise anything during summer time, but for sure I ping you as soon as I have more question or a prototype.

**Comment by rigelk** [comment]
Summer is busy for us too, but feel free to ask, here or on IRC. Anyway glad to hear you're planning to go open source :)

**Comment by Chocobozzz** [comment]
And if you want to federate with peertube, you'll have to use [ActivityPub](https://www.w3.org/TR/activitypub/).

Good luck! :)
