### ISSUE TITLE
Ctrl-number overrides Firefox's default behaviour

### ISSUE THREAD

**Issue by thibaultamartin** [Chocobozzz/PeerTube#771]
* **PeerTube version or URL:** https://peertube.touhoppai.moe/videos/watch/2f24f9e0-e91e-40dc-9554-7864d8b9bc0f or any PeerTube video
* **Browser name/version:** Firefox 61.0
* **NodeJS version:** N/A

* **What is the expected behaviour?** When pressing Ctrl and a number n, the default behaviour in Firefox is to switch to tab number n (*e.g.* if I have three tabs, Ctrl-2 will lead me to the second tab)
* **What do you see instead?** When watching a video on PeerTube, Ctrl-<number> will jump to the n/10 part of the video (*e.g.* Ctrl-5 will jump to the middle of the video).

* **Browser console log if useful (Gist/Pastebin...):** N/A
* **Server log if useful (Gist/Pastebin...):** N/A

**Comment by rigelk** [comment]
Maybe we could use letters-only modifiers to like `g+1` to go to the beginning of a video. That way we would avoid clashing with browser modifiers.

**Comment by rezonant** [comment]
Actually, why not just use the number keys without modifiers. This is what YouTube does, although they limit it to the full screen view.

**Comment by thibaultamartin** [comment]
I just figured yesterday night that YouTube did what @rezonant describes. This seems good in terms of UX

**Comment by rigelk** [comment]
Related option in the videojs plugin we use for hotkeys is `enableModifiersForNumbers` as shown in https://github.com/ctd1500/videojs-hotkeys/pull/35.

That's a quick fix then :)

**Comment by ZettaScript** [comment]
The problem happens again, `CTRL+digit` seeks an instant in the video instead of switching tabs.
(PeerTube 4.1.1, Firefox 99.0.1, Linux)

**Comment by Chocobozzz** [comment]
@ZettaScript Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1c8a9a1d2288247abc3ea7199954db9421bdb7b4
