### ISSUE TITLE
Can I use the lastest Rapsberry PI ?

### ISSUE THREAD

**Issue by freeroot** [Chocobozzz/PeerTube#772]
In support/doc/production.md :

    Please don't install PeerTube for production on a small device behind a low bandwidth connection 
    (example: a Raspberry PI behind your ADSL link) because it could slow down the fediverse."

In FAQ.md : 

    So you would need:
    CPU 1 core if you don't enable transcoding, 2 at least if you enable it
    RAM 1GB
    Storage Completely depends on how many videos your users will upload

But https://www.raspberrypi.org/products/raspberry-pi-3-model-b-plus/ => specifications : 

    The Raspberry Pi 3 Model B+ is the latest product in the Raspberry Pi 3 range.
    Broadcom BCM2837B0, Cortex-A53 (ARMv8) 64-bit SoC @ 1.4GHz
    1GB LPDDR2 SDRAM"

Recent Rapsberry PI can be enough for PeerTube server, no ?

**Comment by tcitworld** [comment]
Well, it definitely won't be enough to transcode videos (RPi is good at decoding, not encoding), but maybe you don't need this part.
However the issue will probably be with your network speed if you're at home, which will be to slow for external viewers.

**Comment by Chocobozzz** [comment]
As @tcitworld said + feedbacks are welcome :)

**Comment by freeroot** [comment]
Ok so I can thx :) Maybe support/doc/production.md should be modified.

**Comment by orbiter28** [comment]
There is more and more fiber optics at home.
With 300 Mb/s, and a 24/24 uptime, peertube can be improved if we can use it on a rpi.

**Comment by rigelk** [comment]
@orbiter28 nothing prevents you from installing it on a rpi.
