### ISSUE TITLE
Anti-abuse tools are urgently needed

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#773]
There's no real way to deal with abuse from remote users and instances. If my instance or its users are targeted, how am I supposed to stop the attackers besides by constantly removing individual things? I can't.

Right now, we can only delete local users, remove individual comments and videos, and /only/ unfollow instances. No way to block, no way to ban. This is an extremely dangerous setup that I'm surprised hasn't been a bigger problem yet.

**Comment by barzamin** [comment]
A good start would be:
* a tool to suspend a problematic remote user instance-wide (for instance, someone commenting spam or harassing comments on local videos)

and, potentially
* the ability to suspend an entire remote instance.

These two relatively easy-to-implement things would go a _long_ way to solving some of the future moderation challenges as the PeerTube federation grows.

**Comment by rigelk** [comment]
Related #718.

**Comment by Chocobozzz** [comment]
> This is an extremely dangerous setup that I'm surprised hasn't been a bigger problem yet.

An admin can unfollow remote servers, and close video comments. This is clearly not ideal but with the current tools you can protect your users. PeerTube clearly needs comments improvements (moderation, abuse etc) but for now you could:
 * Automatically close video comments
 * Embed the videos on a social platform (for example a forum) that implements the anti abuse tools that you feel confident with

I'll try to work on some points of https://github.com/Chocobozzz/PeerTube/issues/718 ASAP, so closing this discussion :)
