### ISSUE TITLE
Thumbnail/preview image “unsupported”

### ISSUE THREAD

**Issue by lanodan** [Chocobozzz/PeerTube#778]
* **PeerTube version or URL:** 1.0.0-beta.9
* **Browser name/version:** chromium 66.0.3359.170
* **NodeJS version:** v8.11.3

* **What is the expected behaviour?** custom thumbnails / previews should be working, at upload or edit time. (logs are at edit time)
* **What do you see instead?**
  * Server-side: ``Error: Input file is missing or of an unsupported image format`` ( Complete log: https://cloudsdale.hacktivis.me/pastes/2018-07-06T20:18:59-peertube_server.log )
  * Client-side: ``this.i18n is not a function`` (Complete log: https://cloudsdale.hacktivis.me/pastes/2018-07-06T20:20:05-o.urtu.be-1530908357165.log)

Also the server is running on gentoo and so might lack configuration flags on few dependencies (I failed to identify what is responsible for this).

**Comment by Chocobozzz** [comment]
I fixed the client logging issue: https://github.com/Chocobozzz/PeerTube/commit/e4f0e92e755be1332dea7cb161e70a53af5c42ef

It's an error in [sharp](https://github.com/lovell/sharp), the module we use to resize the thumbnail/preview, but I don't understand why.

Could you send me the image you want to upload? And please enable debug logs on your peertube instance (see the config file), retry to change the thumbnail/preview and pastebin the server logs like you did :)

**Comment by lanodan** [comment]
It was a system misconfiguration on my side, vips didn’t have jpeg support, maybe it could be added to the README and/or have a better error (like relate it to vips/sharp) ?

**Comment by Chocobozzz** [comment]
Thanks @lanodan. Maybe you could update the [dependencies guide](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/dependencies.md)? (i'm not familiar at all with gentoo).
