### ISSUE TITLE
Reach out to Angela Fisher of Jupiter Broadcasting to held an interview

### ISSUE THREAD

**Issue by Anton-Latukha** [Chocobozzz/PeerTube#779]
* **PeerTube version or URL:**

  Jupiter Broadcasting PeerTube: https://getjupiter.com/
  Jupiter Broadcasting Community PeerTube: https://peertube.linuxrocks.online/

* **What do you see?**

  On Jupiter Broadcasting PeerTube was talked about in last three weeks. Especially in Linux Unplugged # 255 and 256. Ha-ha, just understood, max number of the byte (2^8 -1 = 0xFF) and number of the byte positions (2^8 = 0x0100), that is not intentionally 8).

  Programs have metadata timestamps (#271). 

  Links:

  * LUP # 255 (on 00:05:00):
    * PeerTube: https://getjupiter.com/videos/watch/cb162032-2b4e-4911-b617-12d1de854b66
    * Official site: http://linuxunplugged.com/255
    * Timestamp on the one that should not be named here: https://youtu.be/BkmSD3Z0kUk?t=5m1s

  * LUP # 256 (on 1:22:26):
    * PeerTube: https://getjupiter.com/videos/watch/5eabeaad-9163-41c4-bd13-f9b89cac5b76
    * Official site: http://linuxunplugged.com/256
    * Timestamp on the one that should not be named here: https://www.youtube.com/watch?v=ZUDSdeBretw&t=4946s

  Due to breakthrough of crowdsourced Jupiter Broadcasting PeerTube infrastructure, Chris thinks to switch main links of all his shows (http://www.jupiterbroadcasting.com) to PeerTube in the nearest future. So you would have biggest OpenSource IT media network switched to PeerTube, and its main audience.

* **What is the expected behavior?**

It is probably great to give interview and get to know Chris Fisher and his shows.

But know - he is really busy in the most current days. He in recent days switched Linux Academy to Linux 8], and also switched their broadcasting equipment to OBS/Linux. And he travels from state of Washington to Texas to curate their huge live broadcast marathon celebration of their release of [huge bunch of courses (150 new ones)](https://linuxacademy.com/blog/linuxacademy-com/christmas-in-july-over-150-new-ways-to-train/?utm_source=website&utm_medium=livepage&utm_campaign=July2018CourseLaunch) in these days. They would live broadcast, teach the main parts of main courses. 

So he under heavy-heavy load of production and partying for a couple of days.

They would be glad to organize interview at nearest shows. Basing on the topic and content they would pick the best spot in one of his shows.

A lot of their production/messaging flows happens over Telegram.

Due to current load of Chris - directly ping Angela Fisher Telegram: `@angerz`. She handles business and operations administration in Jupiter Broadcasting. She is a hub and arranger, and would communicate and arrange everything at a good time.

**Comment by Anton-Latukha** [comment]
I heavily edited main post. Now everything is right there.

**Comment by Chocobozzz** [comment]
Thanks @Anton-Latukha, I will try to find a way to contact them.

**Comment by Anton-Latukha** [comment]
AFAIK there is was no interview.

Today I've read in the chatroom that Chris now thinks maybe to make a good cover of the topic of today's multimedia platforms in nearest future, as this topic still raised to him by listeners every other day, you would be good guests to share experience in any part of this, to share your perspective and thoughts.

**Comment by DontUseGithub** [comment]
>     * Jupiter Broadcasting PeerTube: https://getjupiter.com/

They seem to have deleted this instances? Do you know why?

**Comment by Anton-Latukha** [comment]
@DontUseGithub 

Good name =)

There was a really complex situation when I created this issue.

To put shortly: 
Official PeerTube was deployed on some pretty powerful cluster granted by a good samaritan from a private server room.

At the time of me publishing this issue - Chris got into a severe health problem. He survived through it. Then he and the whole Jupiter Broadcasting podcasting network merged with the Linux Academy company as they found big mutual symbiosis in that.

I know other sings, but I would not elaborate on them. But we see that the instance is no more online.

You can see the situation changed drastically. Chris held a lot of JB-like domains, vacant ones, he probably got rid of most of them, that is why `getjupiter.com` is some other site.

Linux Academy/JB now have a resources to keep a Official PeerTube instance online, probably just no-one got to ask and do a job on this at the time.

As I said, Chris is still very motivated and interested in the topic of media platforms, and wants to cover it deeply.
