### ISSUE TITLE
Add to README the paragraph of channels to reach-out into

### ISSUE THREAD

**Issue by Anton-Latukha** [Chocobozzz/PeerTube#780]
In https://github.com/Chocobozzz/PeerTube/pull/774 I had a problem finding communication channels.

When someone faces Terra Incognita, and searches - he knows in Terra Incognita the possibilities where it can be is infinite, and chances to find approach zero.

====

<sub>

My experience example.

I read through the readme.

I searched for paragraph something: "Support", "Contact",  or at least text, at the bottom or anywhere on page.

I Ctrl+F search for IRC, Matrix, Gitter on the page.

I searched on Riot Matrix, but there is confusing interface, so I searched not there where it searches for global channels.

So I asked in a pull request, that person that invited me to IRC.

Received answer and got in.

Then I searched for the IRC keyword inside the whole repo.

And found-out that the last badge of many badges refers in address to IRC, and that is marked "#peertube/on freenode".

I could not found that information. Besides Freenode there are IRCnet and GeekShed IRC networks.

Also as a person that looks for particular things in documentation, I do not care about badges,

does CI build works, what dependencies it has, what version of whatever used in the project.

I know it is fancy and marketing move and can be useful, but people who search serious information tend to not look on badges.

</sub>

====

### To the point.

Please, think about channels you want to share, and do them in the paragraph in readme. If you add IRC, probably Matrix is also suitable.

Imagine otherwise case, if person wants to get the contact, and _not_ looked for "Contacts", "Support" or links in readme - that person even _did not_ glanced over readme and not deserve to bother you, and that person moreover probably not read through all the badges.

Or if person looked though badges, but not through the readme... <sub>that person probably does not want to read basic documentation, so...</sub>

**Comment by rigelk** [comment]
Thanks for pointing that out! I have fixed that in 106e68cfff2573af5262e282101358d7fb926184.
