### ISSUE TITLE
Allow users to filter/control what content they see

### ISSUE THREAD

**Issue by Zig-03** [Chocobozzz/PeerTube#784]
After deciding on how the [advanced search](https://github.com/Chocobozzz/PeerTube/issues/60) should work, I'd like to suggest to duplicate it's functionality and have it usable as a "filter" as well.

The filter will serve as a layer between the user and all the content the user sees which will be active all the time (if the user turns it on | by default it will be turned off), unlike the advanced search which you have to configure every time you wanna search for something.
Also unlike the advanced search, the filter configurations will be saved inside the account settings or in the cookies (for unregistered users).

To me, the implementation of such a feature will mean power/control to the user. Use cases:

- you might wanna watch only videos that are in English, _for example;_
- you might wanna block all videos which have the "car" tag, _for example;_
- you might wanna block all videos which have the keyword "car" in their title, _for example;_
- etc..

I can see this function later evolve into a "feed filter" where you'll also be able to select which channel's videos you wanna see first or which channel's videos you wanna see only on Sunday and so on. This again, would mean peertube giving us the control over what we wanna see, unlike other centralized and proprietary platforms which decide these things for you and default you to them.

**How I see it working**
The user lands on an instance **>** somewhere on the interface they see the button "Filter content" **>** once clicked, they'll have a handful number of tools (the tools available for advanced search & maybe some more specific to filtering) allowing them to configure stuff they see.

**Comment by rigelk** [comment]
Hi @Zig-03 ! Please look out for related issues before creating one, as #319 and #60 (meta-issue) already cover this. You can then detail further your use case there.

**Comment by Zig-03** [comment]
Hi @rigelk,
I decided to create a new issue to avoid having two kinds of discussions inside a single issue, since what I explain here is more of a feature that can be implemented after the **issue nr.60** is solved. In any case, I made sure it's well explained in the `**issue nr.60**`.

**Comment by rigelk** [comment]
Ah, I see. Thanks for the clarification :)

**Comment by Chocobozzz** [comment]
Closing for more specialized issues (for example: https://github.com/Chocobozzz/PeerTube/issues/723).
