### ISSUE TITLE
Refresh or go back doesn't works after paginate on user account or channel view

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#787]
* **PeerTube version or URL:** 1.0.0-beta9
* **Browser name/version:** Firefox and Chrome

* **What is the expected behaviour?**

After watching a video from an account page or navigate on the account video views, go back to the previous page or refresh the page should works.

* **What do you see instead?**

Go to an account page on an instance or a channel page, for example https://peertube.gegeweb.eu/accounts/gerald/videos (but same bug on other instances).
Navigate inside the video list to activate pagination, you will see a URL like this with the params : 
https://peertube.gegeweb.eu/account/gerald/videos?sort=-publishedAt&page=2

Try to refresh the page, look at a video and try to go back and try to remove params and refresh the page you wille see « Sorry, but we couldn't find the page you were looking for. »

Because there is no way to go back to the previous view after watching a video, you need to use the browser feature to go back on the view you come from.

I don't see nothing (no error) in the console.

**Comment by Chocobozzz** [comment]
Thanks @gegeweb, should be fixed in https://github.com/Chocobozzz/PeerTube/commit/c7b514157b9027ade3ad6e202effda72ac937d1b
