### ISSUE TITLE
issues logging in and enabling signup

### ISSUE THREAD

**Issue by fredhampton** [Chocobozzz/PeerTube#79]
I have PeerTube installed on Debian 8.9
When I go to the site in latest release of chrome I receive an error message 

"Error Cannot retrieve OAuth client credentials:Server error. Ensure you have correctly configured PeerTube (config/directory) in particular the "Webserver" section."

When I attempt to log in I receive the following error 
"invalid_client: Invalid client: cannot retrieve client credentials"

I have enabled signup but the signup section is not showing up in the app.

Thanks for the Art that is PeerTube !

**Comment by Chocobozzz** [comment]
Is your issue resolved?

**Comment by fredhampton** [comment]
Yes !!!
