### ISSUE TITLE
Inject custom CSS into the client dynamically to eliminate FOUC

### ISSUE THREAD

**Issue by rezonant** [Chocobozzz/PeerTube#791]
There's a gap between the page loading and application of custom CSS. This gap could be eliminated if the custom stylesheet were to be injected onto the client index.html at the moment it is served. If implemented correctly, it should not meaningfully affect performance versus the regular static handler.
Server-side rendering can also solve the issue, but I don't think this issue alone warrants it.

Since the PeerTube server handles serving up the client files, this could be done somewhere in the client router
https://github.com/Chocobozzz/PeerTube/blob/602a81a2137afcb5ca12341329199fbea2f08bd8/server/controllers/client.ts#L72

Such a change would let us modify the custom CSS loading done here to load only if injection weren't possible:
https://github.com/Chocobozzz/PeerTube/blob/602a81a2137afcb5ca12341329199fbea2f08bd8/client/src/app/app.component.ts#L97

EDIT: The existing implementation shouldn't be removed, it should be able to detect if the custom styles were injected, and if not, apply it when the server configuration arrives.

**Comment by Chocobozzz** [comment]
> If implemented correctly, it should not meaningfully affect performance versus the regular static handler.

How would you do it effectively? We already inject some tags (opengraph etc) in the watch page with the `replace` function: https://github.com/Chocobozzz/PeerTube/blob/develop/server/controllers/client.ts#L191, but maybe there is a more efficient way to do that.

**Comment by rezonant** [comment]
In this case, doing the injection can be done once as long as the custom CSS doesn't change, and the result could be cached in memory. Honestly this isn't going to matter that much, but it is a simple enough caching problem that it might as well be tackled in the first implementation. However in order for the /watch page to benefit from the CSS, we'll need to put together a service that manages fetching and processing the 'index.html' for other areas of the service where the `index.html` must be fetched.

In the case of the opengraph tags, the injection is different per video, so it's a more complex cache scenario. The performance impact of doing that .replace is going to be negligible under low traffic. Under high traffic scenarios (*if* it were to be identified as a real perf issue) I would probably look at using Redis to cache the watch pages, especially since Redis is already a dependency for the queue. Alternatively, a caching reverse proxy like Cloudflare could handle caching such pages for non-logged in users.

I think the easier "get" on the Opengraph side of things is to cache the file read. One might imagine using the file's mtime and/or a cache invalidation timeout to limit the hits to the filesystem. That would get you a bigger bang for your buck coming from an incremental improvement angle.

**Comment by Chocobozzz** [comment]
I like this idea. So:

 * At startup, load index.html in nodejs memory
 * Inject CSS in the variable
 * Serve this string each time someone requests index.html
 * Use this string to add opengraph tags (I don't think that it's worth using redis for now) and serve watch pages

We just have to remember to execute again the first two steps if the admin configuration changed.

Don't need to watch the index.html file, we expect admins to not update the index.html file at runtime.

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/e032aec9b92be25a996923361f83a96a89505254
