### ISSUE TITLE
Not published videos stay in storage/videos as xxxx-transcoded.mp4

### ISSUE THREAD

**Issue by FirePowi** [Chocobozzz/PeerTube#792]
* **PeerTube version or URL:**
1.0.0-bêta.9
* **Browser name/version:**
Firefox Quantum 61
* **NodeJS version:**
v8.11.3

* **What is the expected behaviour?**
Unpublished videos should be deleted (I guess)

* **What do you see instead?**
9147-transcoded.mp4 and 9895-transcoded.mp4

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**
Will upload if asked, but really think it's useless.

**Comment by Chocobozzz** [comment]
Hi,

See https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#prune-storagejs to delete them :)

**Comment by FirePowi** [comment]
I had to install `prompt` `bcrypt` `create-torrent` `mkdirp` `pem` `rimraf` `lodash` `config` with npm install.

Well for now I have an issue with config.js. Look like it doesn't read NODE_CONFIG_DIR at all
https://pastebin.com/pcTvKshC
Look like it's config v1.30.0 → https://registry.npmjs.org/config/-/config-1.30.0.tgz

Hope I do it well (I'm really not used to Git issues).
