### ISSUE TITLE
Make the User Interface More Accessible to screen reader Users

### ISSUE THREAD

**Issue by mcb2003** [Chocobozzz/PeerTube#797]
## Background
  I'm almost completely blind and am very enthusiastic about the PeerTube project.
## My Issue
  I use a screen reader to navigate my way around a computer, including on PeerTube. And while 90% of the PeerTube site is fully accessible, there are a few areas in which it isn't. these are:
* The *like* and *dislike* buttons are not reported as buttons. This means I Don't know if they're selected or not. Toggle buttons or even checkboxes would let me read the state of the buttons, although I don't know how you could make them fit into the UI's appearance.
* The *share* button is not reported as a button either, only as "clickable". However, some screen readers do not inform the user of this, so it appears as just a piece of text. Again, a button would be better, or even a link.
* The same goes for the *"get help" buttons* around the UI: they are not reported as buttons.
* *checkboxes* such as the *"enable comments"* checkbox are reported only as text, meaning I don't know if it is ticked or not. Again, this can be solved by using a standard HTML checkbox or toggle button, but how you would make this fit with the rest of the code and/or appearance I don't know.

I've made [a video that demonstrates these issues](https://peertube.linuxrocks.online/videos/watch/fe5ef4eb-0cb0-4a79-8ec9-e5192f54dde4), so that may be helpful as well.

Thanks
Mikey

**Comment by Chocobozzz** [comment]
Hi @mcb2003, thanks for the explanations and the video, they are very useful. I'll try to fix that.

**Comment by rezonant** [comment]
I am also willing to help on accessibility :-D

**Comment by Chocobozzz** [comment]
@rezonant you can take this issue if you want :)

**Comment by mcb2003** [comment]
Something else I thought about: it would be nice if you could add alt text to the video thumbnails, possibly the title of the video, as right now they are a string of garbled letters and numbers when you read them with a screen reader.

**Comment by Chocobozzz** [comment]
@mcb2003 Could we use `aria-labelledb` attribute instead of `alt`? Because the `alt` attribute is displayed when loading the thumbnails, which it is quite embarrassing for non blind users.

**Comment by Chocobozzz** [comment]
I tried to improve the accessibility in https://github.com/Chocobozzz/PeerTube/commit/0f7fedc39857ebc0eb29182c1588a92b9adfb75a

@mcb2003 Could you check if it solves your issues on https://peertube2.cpy.re? Thanks.

**Comment by mcb2003** [comment]
Also, @Chocobozzz, *aria-labelledby* would be perfectly fine. I've just looked it up (I'm not that familiar with aria in general) and it seems like a perfectly good solution that is specifically designed for this purpose.

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/c487d3033cad9c5e0f85ae49ed3d2a7b6c2711d8
