### ISSUE TITLE
Some scaling experiment?

### ISSUE THREAD

**Issue by Lapin0t** [Chocobozzz/PeerTube#8]
Hi, this is an awesome project! I am part of the Nuit Debout developer team and we are developing a [periscope.tv downloader](https://gitlab.com/HubsNuitDebout/StreamDebout) which automatically records some live broadcasts for replay (so that they can't be deleted for example). We then upload them back into some online archives (youtube, maybe IPFS or anything) and it may be a great thing to upload them on the peertube network as well. The scaling may be an issue so I prefer asking here before we do anything serious: Have you already done some heavy-duty tests of the pod server? Would you be interested in experimenting this?

Note: this stream recorder is WIP.

**Comment by Chocobozzz** [comment]
Hi @Lapin0t, I'll try to make a detailed answer.

## Videos upload scaling
More you add videos on the server, more the Electron process will consum CPU to keep seeding these files. For example, on a very small VPS with 2 vCore and 15 gigabytes of videos -> ~10-15% CPU load.

Moreover, when the server starts seeding a file it could be a long process depending on the server perf' and the video size. So if you restart the server, there might be a long time before you seed all your videos.

### Solution 1
Run small servers that would communicate between them through the PeerTube protocol.

### Solution 2
This would solve the two issues (slow seed/CPU consumption). The server would use webseed to seed the videos so we do not need WebRTC/Electron inside the server anymore. An implementation is  available on the [webseed branch](https://github.com/Chocobozzz/PeerTube/tree/webseed).
 

## Server bandwidth scaling
PeerTube uses WebTorrent and thus BitTorrent protocol. The only issue I would see is that many users watch different videos. So for each video, the server is the only peer that can send data to each user. 
Moreover, sending data through WebRTC consums CPU so there could be a CPU overhead.

### Solution
For the CPU issue, maybe the webseed implementation would solve this.

## Conclusion
These are the two scaling issues. I hope to solve them with the webseed solution. WebTorrent devs would like to improve its implementation in the library (https://github.com/feross/webtorrent/issues/650).

PeerTube is still a WIP prototype but if you would want to help me to make load tests I would be very happy. It's a little bit difficult to simulate traffic on WebRTC applications.

Do not hesitate to contact me to discuss further about it : https://keybase.io/chocobozzz

Cheers,
Chocobozzz

**Comment by Chocobozzz** [comment]
PeerTube is now using the webseed implementation.

The two issues are therefore fixed.

For example, with a Nginx reverse proxy I can see a video at 15MB/s and it consums only 2% of CPU on a small server with 2vCore.
