### ISSUE TITLE
"Cannot retrieve metadata of the file.

### ISSUE THREAD

**Issue by fredhampton** [Chocobozzz/PeerTube#80]
When I upload a video I receive an error meassage
"Cannot retrieve metadata of the file."

I have pasted console content below

Thanks !

info: [josephine.douglass.io:80] Database peertube_prod is ready.
(node:6930) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
debug: [josephine.douglass.io:80] Executing (default): SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type LIKE '%TABLE' AND table_name != 'spatial_ref_sys';
debug: [josephine.douglass.io:80] Executing (default): SELECT "migrationVersion" FROM "Applications" AS "Application" LIMIT 1;
debug: [josephine.douglass.io:80] Executing (default): SELECT count(*) AS "count" FROM "OAuthClients" AS "OAuthClient";
debug: [josephine.douglass.io:80] Executing (default): SELECT count(*) AS "count" FROM "Users" AS "User";
info: [josephine.douglass.io:80] Requests scheduler activated.
info: [josephine.douglass.io:80] Requests scheduler activated.
info: [josephine.douglass.io:80] Requests scheduler activated.
info: [josephine.douglass.io:80] Server listening on port 9000
info: [josephine.douglass.io:80] Webserver: https://josephine.douglass.io:80
debug: [josephine.douglass.io:80] Getting Client (clientId: x2rtdip398758ipailt593xpsthx9h47, clientSecret: zjbwUgsx5qO3m2ExHBU8MP8w9PW2kdIS).
debug: [josephine.douglass.io:80] Executing (default): SELECT "id", "clientId", "clientSecret", "grants", "redirectUris", "createdAt", "updatedAt" FROM "OAuthClients" AS "OAuthClient" WHERE "OAuthClient"."clientId" = 'x2rtdip398758ipailt593xpsthx9h47' AND "OAuthClient"."clientSecret" = 'zjbwUgsx5qO3m2ExHBU8MP8w9PW2kdIS' LIMIT 1;
debug: [josephine.douglass.io:80] Getting User (username: root, password: bumpkin62).
debug: [josephine.douglass.io:80] Executing (default): SELECT "id", "password", "username", "email", "displayNSFW", "role", "createdAt", "updatedAt" FROM "Users" AS "User" WHERE "User"."username" = 'root' LIMIT 1;
info: [josephine.douglass.io:80] ::1 - - [24/Aug/2017:16:49:49 +0000] "POST /api/v1/users/token HTTP/1.0" 400 91 "https://josephine.douglass.io/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"

debug: [josephine.douglass.io:80] Getting Client (clientId: x2rtdip398758ipailt593xpsthx9h47, clientSecret: zjbwUgsx5qO3m2ExHBU8MP8w9PW2kdIS).
debug: [josephine.douglass.io:80] Executing (default): SELECT "id", "clientId", "clientSecret", "grants", "redirectUris", "createdAt", "updatedAt" FROM "OAuthClients" AS "OAuthClient" WHERE "OAuthClient"."clientId" = 'x2rtdip398758ipailt593xpsthx9h47' AND "OAuthClient"."clientSecret" = 'zjbwUgsx5qO3m2ExHBU8MP8w9PW2kdIS' LIMIT 1;
debug: [josephine.douglass.io:80] Getting User (username: root, password: bumpkin62).
debug: [josephine.douglass.io:80] Executing (default): SELECT "id", "password", "username", "email", "displayNSFW", "role", "createdAt", "updatedAt" FROM "Users" AS "User" WHERE "User"."username" = 'root' LIMIT 1;
info: [josephine.douglass.io:80] ::ffff:127.0.0.1 - - [24/Aug/2017:16:49:50 +0000] "POST /api/v1/users/token HTTP/1.0" 400 91 "https://josephine.douglass.io/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"

debug: [josephine.douglass.io:80] Getting Client (clientId: x2rtdip398758ipailt593xpsthx9h47, clientSecret: zjbwUgsx5qO3m2ExHBU8MP8w9PW2kdIS).
debug: [josephine.douglass.io:80] Executing (default): SELECT "id", "clientId", "clientSecret", "grants", "redirectUris", "createdAt", "updatedAt" FROM "OAuthClients" AS "OAuthClient" WHERE "OAuthClient"."clientId" = 'x2rtdip398758ipailt593xpsthx9h47' AND "OAuthClient"."clientSecret" = 'zjbwUgsx5qO3m2ExHBU8MP8w9PW2kdIS' LIMIT 1;
debug: [josephine.douglass.io:80] Getting User (username: root, password: gothamcity).
debug: [josephine.douglass.io:80] Executing (default): SELECT "id", "password", "username", "email", "displayNSFW", "role", "createdAt", "updatedAt" FROM "Users" AS "User" WHERE "User"."username" = 'root' LIMIT 1;
debug: [josephine.douglass.io:80] Saving token ffd77e4f01ad5663e7295acc83ce84eb5e6aef31 for client 1 and user 1.
debug: [josephine.douglass.io:80] Executing (default): INSERT INTO "OAuthTokens" ("id","accessToken","accessTokenExpiresAt","refreshToken","refreshTokenExpiresAt","createdAt","updatedAt","userId","oAuthClientId") VALUES (DEFAULT,'ffd77e4f01ad5663e7295acc83ce84eb5e6aef31','2017-08-24 20:49:54.342 +00:00','3e431cc903563c012c7352091063d2ef39c71b61','2017-09-07 16:49:54.342 +00:00','2017-08-24 16:49:54.350 +00:00','2017-08-24 16:49:54.350 +00:00',1,1) RETURNING *;
-24 16:49:54.350 +00:00',1,1) RETURNING *;
info: [josephine.douglass.io:80] ::1 - - [24/Aug/2017:16:49:54 +0000] "POST /api/v1/users/token HTTP/1.0" 200 159 "https://josephine.douglass.io/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"

debug: [josephine.douglass.io:80] Getting access token (bearerToken: ffd77e4f01ad5663e7295acc83ce84eb5e6aef31).
debug: [josephine.douglass.io:80] Executing (default): SELECT "OAuthToken"."id", "OAuthToken"."accessToken", "OAuthToken"."accessTokenExpiresAt", "OAuthToken"."refreshToken", "OAuthToken"."refreshTokenExpiresAt", "OAuthToken"."createdAt", "OAuthToken"."updatedAt", "OAuthToken"."userId", "OAuthToken"."oAuthClientId", "User"."id" AS "User.id", "User"."password" AS "User.password", "User"."username" AS "User.username", "User"."email" AS "User.email", "User"."displayNSFW" AS "User.displayNSFW", "User"."role" AS "User.role", "User"."createdAt" AS "User.createdAt", "User"."updatedAt" AS "User.updatedAt" FROM "OAuthTokens" AS "OAuthToken" LEFT OUTER JOIN "Users" AS "User" ON "OAuthToken"."userId" = "User"."id" WHERE "OAuthToken"."accessToken" = 'ffd77e4f01ad5663e7295acc83ce84eb5e6aef31' LIMIT 1;
ser"."email" AS "User.email", "User"."displayNSFW" AS "User.displayNSFW", "User"."role" AS "User.role", "User"."createdAt" AS "User.createdAt", "User"."updatedAt" AS "User.updatedAt" FROM "OAuthTokens" AS "OAuthToken" LEFT OUTER JOIN "Users" AS "User" ON "OAuthToken"."userId" = "User"."id" WHERE "OAuthToken"."accessToken" = 'ffd77e4f01ad5663e7295acc83ce84eb5e6aef31' LIMIT 1;
debug: [josephine.douglass.io:80] Executing (default): SELECT "id", "password", "username", "email", "displayNSFW", "role", "createdAt", "updatedAt" FROM "Users" AS "User" WHERE "User"."username" = 'root' LIMIT 1;
info: [josephine.douglass.io:80] ::ffff:127.0.0.1 - - [24/Aug/2017:16:49:54 +0000] "GET /api/v1/users/me HTTP/1.0" 200 130 "https://josephine.douglass.io/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"

debug: [josephine.douglass.io:80] Checking pagination parameters 
{ parameters: { start: '0', count: '25', sort: '-createdAt' } }
debug: [josephine.douglass.io:80] Checking sort parameters 
{ parameters: { start: '0', count: '25', sort: '-createdAt' } }
(node:6930) DeprecationWarning: req.validationErrors() may be removed in a future version. Use req.getValidationResult() instead.
debug: [josephine.douglass.io:80] Executing (default): SELECT count(DISTINCT("Video"."id")) AS "count" FROM "Videos" AS "Video" LEFT OUTER JOIN "Authors" AS "Author" ON "Video"."authorId" = "Author"."id" LEFT OUTER JOIN "Pods" AS "Author.Pod" ON "Author"."podId" = "Author.Pod"."id" LEFT OUTER JOIN ("VideoTags" AS "Tags.VideoTag" INNER JOIN "Tags" AS "Tags" ON "Tags"."id" = "Tags.VideoTag"."tagId") ON "Video"."id" = "Tags.VideoTag"."videoId" WHERE "Video"."id" NOT IN (SELECT "BlacklistedVideos"."videoId" FROM "BlacklistedVideos");
info: [josephine.douglass.io:80] ::1 - - [24/Aug/2017:16:49:54 +0000] "GET /api/v1/videos/?start=0&count=25&sort=-createdAt HTTP/1.0" 304 - "https://josephine.douglass.io/videos/list" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"

debug: [josephine.douglass.io:80] Getting access token (bearerToken: ffd77e4f01ad5663e7295acc83ce84eb5e6aef31).
debug: [josephine.douglass.io:80] Executing (default): SELECT "OAuthToken"."id", "OAuthToken"."accessToken", "OAuthToken"."accessTokenExpiresAt", "OAuthToken"."refreshToken", "OAuthToken"."refreshTokenExpiresAt", "OAuthToken"."createdAt", "OAuthToken"."updatedAt", "OAuthToken"."userId", "OAuthToken"."oAuthClientId", "User"."id" AS "User.id", "User"."password" AS "User.password", "User"."username" AS "User.username", "User"."email" AS "User.email", "User"."displayNSFW" AS "User.displayNSFW", "User"."role" AS "User.role", "User"."createdAt" AS "User.createdAt", "User"."updatedAt" AS "User.updatedAt" FROM "OAuthTokens" AS "OAuthToken" LEFT OUTER JOIN "Users" AS "User" ON "OAuthToken"."userId" = "User"."id" WHERE "OAuthToken"."accessToken" = 'ffd77e4f01ad5663e7295acc83ce84eb5e6aef31' LIMIT 1;
debug: [josephine.douglass.io:80] Checking videosAdd parameters 
{ parameters: 
   { name: 'Star Spangled Banner',
     category: '1',
     nsfw: 'false',
     licence: '1',
     language: '1',
     description: 'Star Spangled Banner' },
  files: 
   { videofile: 
      [ { fieldname: 'videofile',
          originalname: 'The Star Spangled Banner.mp4',
          encoding: '7bit',
          mimetype: 'video/mp4',
          destination: '/home/peertube/PeerTube/videos/',
          filename: 'ae452dc98d927f5e23e914e72488708c.mp4',
          path: '/home/peertube/PeerTube/videos/ae452dc98d927f5e23e914e72488708c.mp4',
          size: 10746610 } ] } }
info: [josephine.douglass.io:80] ::ffff:127.0.0.1 - - [24/Aug/2017:16:50:55 +0000] "POST /api/v1/videos HTTP/1.0" 400 37 "https://josephine.douglass.io/videos/add" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"

**Comment by Chocobozzz** [comment]
Do you use `develop` branch?

**Comment by fredhampton** [comment]
I m using the master branch

**Comment by Chocobozzz** [comment]
Please try `develop`.

**Comment by fredhampton** [comment]
ok 

thanks !!

**Comment by fredhampton** [comment]
I'am using the develop branch and for some reason when I run build there are the following errors 
peertube@production:~/PeerTube$ npm run build

> peertube@0.0.1 build /home/peertube/PeerTube
> SCRIPTY_PARALLEL=true scripty


> peertube@0.0.1 tsc /home/peertube/PeerTube
> tsc


> peertube-client@0.0.1 webpack /home/peertube/PeerTube/client
> webpack "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"

  0% [0] compilingStarting compilation using the angular compiler.
server/helpers/core-utils.ts(77,56): error TS2345: Argument of type 'typeof writeFile' is not assignable to parameter of type '(arg1: string, arg2: any, cb: (err: any, result: void) => void) => void'.
server/middlewares/validators/pods.ts(17,66): error TS2339: Property 'isEachUniqueHostValid' does not exist on type 'Validator'.
server/middlewares/validators/pods.ts(39,47): error TS2339: Property 'isHostValid' does not exist on type 'Validator'.
server/middlewares/validators/remote/videos.ts(8,25): error TS2339: Property 'isEachRemoteRequestVideosValid' does not exist on type 'Validator'.
server/middlewares/validators/remote/videos.ts(16,25): error TS2339: Property 'isEachRemoteRequestVideosQaduValid' does not exist on type 'Validator'.
server/middlewares/validators/remote/videos.ts(24,25): error TS2339: Property 'isEachRemoteRequestVideosEventsValid' does not exist on type 'Validator'.
server/middlewares/validators/users.ts(12,61): error TS2339: Property 'isUserUsernameValid' does not exist on type 'Validator'.
server/middlewares/validators/users.ts(13,61): error TS2339: Property 'isUserPasswordValid' does not exist on type 'Validator'.
server/middlewares/validators/users.ts(56,72): error TS2339: Property 'isUserPasswordValid' does not exist on type 'Validator'.
server/middlewares/validators/users.ts(57,102): error TS2339: Property 'isUserDisplayNSFWValid' does not exist on type 'Validator'.
server/middlewares/validators/users.ts(65,73): error TS2339: Property 'isVideoIdOrUUIDValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(15,30): error TS2339: Property 'isVideoFile' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(16,53): error TS2339: Property 'isVideoNameValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(17,61): error TS2339: Property 'isVideoCategoryValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(18,59): error TS2339: Property 'isVideoLicenceValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(19,72): error TS2339: Property 'isVideoLanguageValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(20,63): error TS2339: Property 'isVideoNSFWValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(21,67): error TS2339: Property 'isVideoDescriptionValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(22,64): error TS2339: Property 'isVideoTagsValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(46,62): error TS2339: Property 'isVideoIdOrUUIDValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(47,64): error TS2339: Property 'isVideoNameValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(48,72): error TS2339: Property 'isVideoCategoryValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(49,70): error TS2339: Property 'isVideoLicenceValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(50,72): error TS2339: Property 'isVideoLanguageValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(51,74): error TS2339: Property 'isVideoNSFWValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(52,78): error TS2339: Property 'isVideoDescriptionValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(53,64): error TS2339: Property 'isVideoTagsValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(74,62): error TS2339: Property 'isVideoIdOrUUIDValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(84,62): error TS2339: Property 'isVideoIdOrUUIDValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(111,62): error TS2339: Property 'isVideoIdOrUUIDValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(112,57): error TS2339: Property 'isVideoAbuseReasonValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(122,62): error TS2339: Property 'isVideoIdOrUUIDValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(123,60): error TS2339: Property 'isVideoRatingTypeValid' does not exist on type 'Validator'.
server/middlewares/validators/videos.ts(133,62): error TS2339: Property 'isVideoIdOrUUIDValid' does not exist on type 'Validator'.
server/models/pod/pod.ts(146,16): error TS2314: Generic type 'FindOptions<T>' requires 1 type argument(s).
server/models/pod/pod.ts(180,24): error TS2345: Argument of type '{ attributes: string[]; order: string[][]; offset: number; limit: number; where: { id: { $in: lit...' is not assignable to parameter of type 'FindOptions<PodAttributes>'.
  Types of property 'where' are incompatible.
    Type '{ id: { $in: literal[]; }; }' is not assignable to type '(string | col | and | or)[] | fn | WhereOptions<PodAttributes>'.
      Type '{ id: { $in: literal[]; }; }' has no properties in common with type 'WhereOptions<PodAttributes>'.
server/models/user/user-video-rate.ts(69,18): error TS2314: Generic type 'FindOptions<T>' requires 1 type argument(s).
server/models/user/user.ts(215,23): error TS2345: Argument of type '{ where: { $or: ({ username: string; } | { email: string; })[]; }; }' is not assignable to parameter of type 'FindOptions<UserAttributes>'.
  Types of property 'where' are incompatible.
    Type '{ $or: ({ username: string; } | { email: string; })[]; }' is not assignable to type '(string | col | and | or)[] | fn | WhereOptions<UserAttributes>'.
      Type '{ $or: ({ username: string; } | { email: string; })[]; }' has no properties in common with type 'WhereOptions<UserAttributes>'.
server/models/video/video.ts(606,32): error TS2345: Argument of type '{ distinct: boolean; offset: number; limit: number; order: any[][]; include: any[]; where: { id: ...' is not assignable to parameter of type 'FindOptions<VideoAttributes>'.
  Types of property 'where' are incompatible.
    Type '{ id: { $notIn: any; }; }' is not assignable to type '(string | col | and | or)[] | fn | WhereOptions<VideoAttributes>'.
      Type '{ id: { $notIn: any; }; }' has no properties in common with type 'WhereOptions<VideoAttributes>'.
server/models/video/video.ts(736,16): error TS2314: Generic type 'FindOptions<T>' requires 1 type argument(s).

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "tsc"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! peertube@0.0.1 tsc: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the peertube@0.0.1 tsc script 'tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertube package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertube
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/peertube/PeerTube/npm-debug.log
/home/peertube/PeerTube/node_modules/scripty/cli.js:38
    if (er) { throw er }
              ^

Error: Error: scripty - script "fail" failed by exiting with a non-zero code (1).
    at ChildProcess.<anonymous> (/home/peertube/PeerTube/node_modules/scripty/lib/run/spawn-script.js:11:10)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! peertube@0.0.1 build: `SCRIPTY_PARALLEL=true scripty`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the peertube@0.0.1 build script 'SCRIPTY_PARALLEL=true scripty'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertube package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     SCRIPTY_PARALLEL=true scripty
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertube
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/peertube/PeerTube/npm-debug.log

**Comment by fredhampton** [comment]
I m in Jessie

**Comment by Chocobozzz** [comment]
Try `rm -r ./dist ./node_modules client/node_modules client/compiled client/dist && yarn install --pure-lockfile && npm run build`

**Comment by fredhampton** [comment]
I tired and the same errors appeared :-(

**Comment by fredhampton** [comment]
I have installed the latest develop branch and the build script completes  but when I try to run I receive the following 


> peertube@0.0.1 start /home/peertube/PeerTube
> node dist/server

/home/peertube/PeerTube/node_modules/config/lib/config.js:181
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "storage.cache" is not defined
    at Config.get (/home/peertube/PeerTube/node_modules/config/lib/config.js:181:11)
    at Object.<anonymous> (/home/peertube/PeerTube/dist/server/initializers/constants.js:53:60)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/peertube/PeerTube/dist/server/helpers/logger.js:8:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! peertube@0.0.1 start: `node dist/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the peertube@0.0.1 start script 'node dist/server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the peertube package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dist/server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs peertube
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls peertube
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/peertube/PeerTube/npm-debug.log

Thanks so much !!!

**Comment by Chocobozzz** [comment]
Your configuration file is not up to date: it miss some keys (in your case the `storage.cache` key). Please update it -> https://github.com/Chocobozzz/PeerTube/blob/develop/config/default.yaml

**Comment by fredhampton** [comment]
I made the suggested changes to the config file.
I'am still having issues adding a video with an error message 
"Cannot retrieve metadata of the file"
My console log is below

debug: [josephine.douglass.io:80] Executing (default): SELECT "OAuthToken"."id", "OAuthToken"."accessToken", "OAuthToken"."accessTokenExpiresAt", "OAuthToken"."refreshToken", "OAuthToken"."refreshTokenExpiresAt", "OAuthToken"."createdAt", "OAuthToken"."updatedAt", "OAuthToken"."oAuthClientId", "OAuthToken"."userId", "User"."id" AS "User.id", "User"."password" AS "User.password", "User"."username" AS "User.username", "User"."email" AS "User.email", "User"."displayNSFW" AS "User.displayNSFW", "User"."role" AS "User.role", "User"."createdAt" AS "User.createdAt", "User"."updatedAt" AS "User.updatedAt" FROM "OAuthTokens" AS "OAuthToken" LEFT OUTER JOIN "Users" AS "User" ON "OAuthToken"."userId" = "User"."id" WHERE "OAuthToken"."accessToken" = '800076ef5979bfbf307aa9b051d3acfeff159ef7' LIMIT 1; | [object Object]ms
debug: [josephine.douglass.io:80] Checking videosAdd parameters 
{ parameters: 
   { name: 'The Star Spangled Banner',
     category: '1',
     nsfw: 'false',
     licence: '1',
     language: '1',
     description: 'The Star Spangled Banner' },
  files: 
   { videofile: 
      [ { fieldname: 'videofile',
          originalname: 'The Star Spangled Banner.mp4',
          encoding: '7bit',
          mimetype: 'video/mp4',
          destination: '/home/peertube/PeerTube/videos/',
          filename: '925cf8b48cddad7b201666748d029095.mp4',
          path: '/home/peertube/PeerTube/videos/925cf8b48cddad7b201666748d029095.mp4',
          size: 10746610 } ] } }
(node:27911) DeprecationWarning: req.validationErrors() may be removed in a future version. Use req.getValidationResult() instead.
error: [josephine.douglass.io:80] Error in getting duration from file. Error: Cannot find ffprobe
    at /home/peertube/PeerTube/node_modules/fluent-ffmpeg/lib/ffprobe.js:145:31
    at /home/peertube/PeerTube/node_modules/fluent-ffmpeg/lib/capabilities.js:194:9
    at /home/peertube/PeerTube/node_modules/async/dist/async.js:421:16
    at next (/home/peertube/PeerTube/node_modules/async/dist/async.js:5302:29)
    at /home/peertube/PeerTube/node_modules/async/dist/async.js:906:16
    at /home/peertube/PeerTube/node_modules/fluent-ffmpeg/lib/capabilities.js:186:13
    at FfmpegCommand.proto._getFfmpegPath (/home/peertube/PeerTube/node_modules/fluent-ffmpeg/lib/capabilities.js:90:14)
    at /home/peertube/PeerTube/node_modules/fluent-ffmpeg/lib/capabilities.js:176:14
    at nextTask (/home/peertube/PeerTube/node_modules/async/dist/async.js:5297:14)
    at next (/home/peertube/PeerTube/node_modules/async/dist/async.js:5304:9)
    at /home/peertube/PeerTube/node_modules/async/dist/async.js:906:16
    at /home/peertube/PeerTube/node_modules/fluent-ffmpeg/lib/capabilities.js:166:11
    at /home/peertube/PeerTube/node_modules/fluent-ffmpeg/lib/utils.js:223:16
    at F (/home/peertube/PeerTube/node_modules/which/which.js:68:16)
    at E (/home/peertube/PeerTube/node_modules/which/which.js:80:29)
    at /home/peertube/PeerTube/node_modules/which/which.js:89:16
    at /home/peertube/PeerTube/node_modules/isexe/index.js:42:5
    at /home/peertube/PeerTube/node_modules/isexe/mode.js:8:5
    at FSReqWrap.oncomplete (fs.js:123:15)
info: [josephine.douglass.io:80] ::1 - - [28/Aug/2017:14:42:13 +0000] "POST /api/v1/videos HTTP/1.0" 400 37 "https://josephine.douglass.io/videos/add" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"

**Comment by Chocobozzz** [comment]
"Error: Cannot find ffprobe" -> you need ffprobe (part of ffmpeg).

https://packages.debian.org/fr/jessie-backports/ffmpeg

**Comment by fredhampton** [comment]
Thanks !!! That has helped !!!
I can upload video but now have an error 
Cannot connect to 
wss://josephine.douglas.io:80/tracker
