### ISSUE TITLE
Category ordering on video listings

### ISSUE THREAD

**Issue by sachaz** [Chocobozzz/PeerTube#800]
Hi

Maybe we can add a categories sorting for the "Trending, Recentrly added and Local" videos ?

**Comment by PhieF** [comment]
Already added : 

example category=1 for music

I don't know if it was already in last beta

**Comment by Chocobozzz** [comment]
You can search on categories and sort the result with the new search feature https://github.com/Chocobozzz/PeerTube/issues/60
