### ISSUE TITLE
Add zh-TW locale

### ISSUE THREAD

**Issue by s8321414** [Chocobozzz/PeerTube#801]
Please add zh-TW locale to your Zanata platform to translate, thank you :smiley:

**Comment by Chocobozzz** [comment]
Traditional or Simplified? Are there many differences with simplified chinese? :)

**Comment by s8321414** [comment]
Traditional, on Zanata should be zh-Hant-TW, and yes, they are very different. :smiley:

**Comment by Chocobozzz** [comment]
Done: https://trad.framasoft.org/iteration/view/peertube/develop/languages :)

**Comment by s8321414** [comment]
\o/
