### ISSUE TITLE
Allow channel selection in import_videos.js

### ISSUE THREAD

**Issue by eric-theitguy** [Chocobozzz/PeerTube#806]
Currently:
Videos pulled in by import_videos.js puts the video in the default/original channel.

Desired State:
When importing videos using the server tool, specify the PeerTube channel destination for the video.

**Comment by joshmorel** [comment]
Willing to take a stab at this @Chocobozzz

**Comment by Chocobozzz** [comment]
@joshmorel Are you still working on this?

**Comment by joshmorel** [comment]
Sorry for the late response @Chocobozzz .

I chatted with @eric-theitguy and we've decided to go with a custom CLI solution to meet our own needs - we'll import data via REST requests driven by an RSS feed. 

I might still be interested in contributing to this component if it is more largely useful. What is your vision now for the CLI tools?

**Comment by rigelk** [comment]
@joshmorel the CLI tools are definitely something we want to expand and make more featureful. So far I've gathered the tools under the umbrella of a simple single interface, but on the long run we want to allow the user and the admin alike to use the CLI as an alternative way to use/administer PeerTube.

**Comment by joshmorel** [comment]
@rigelk I could definitely see myself contributing later. I'd say close this issue as I'll be working a custom script for our use case (checking RSS feed via cron job via cron job). 

I'll keep monitoring for related issues to see if our work could benefit the CLI.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/1a12f66d631d28a5a58ebbcd274426f2e6e5d203
