### ISSUE TITLE
Thumbnail update not working

### ISSUE THREAD

**Issue by ChameleonScales** [Chocobozzz/PeerTube#807]
* **PeerTube version or URL:**
https://peertube.mastodon.host
* **Browser name/version:**
Google Chrome 67 and Firefox 61
* **NodeJS version:**
not installed on machine

* **Steps to reproduce:**
      1. upload a video and publish it
      2. go back to edit the video properties
      3. change the thumbnail and preview images and save

The change is not effective.
However, changing the thumbnail before publishing the video does work.

**Comment by Chocobozzz** [comment]
Thanks for the issue @ChameleonScales. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/57a81ff649fa8c0d17505e4a7c5ab1001887b22a

**Comment by Papillone** [comment]
Hello,
having the same problem: Thumbnail is not updated.

Peertube Version: 2.4.0
