### ISSUE TITLE
Error message when instance is down

### ISSUE THREAD

**Issue by yPhil-gh** [Chocobozzz/PeerTube#808]
Currently, when user on instance A tries to view a listed video hosted on instance B, that happens to be down, they stare at a black screen ; [live example](https://peertube.video/videos/search?sort=createdAt&page=2&search=yphil).

We should tell him what's going on: "This video is hosted on a machine that does not respond right now. Please try again later" :|

**Comment by Chocobozzz** [comment]
Fixed: https://github.com/Chocobozzz/PeerTube/commit/6d88de725321e77486788f64a2e2537f5e6ef0cd
