### ISSUE TITLE
Export an account across instances

### ISSUE THREAD

**Issue by yPhil-gh** [Chocobozzz/PeerTube#809]
The possibility for an admin (and even better, at the user level) to take an account, and export it to another instance, keeping the account assets: Descriptions, comments, page views, etc.

**Comment by rigelk** [comment]
It's a duplicate… of your own issue (#549) :sweat_smile:

I know it's not exactly about deleting the account right after like you mentioned in that issue, but the bulk of the implementation and purpose is essentially the same.
