### ISSUE TITLE
Access-Control on static files

### ISSUE THREAD

**Issue by DavidLibeau** [Chocobozzz/PeerTube#811]
While developing a front-end (JS) app, I faced CORS issues. I managed them by using webseed links (that's not seems to be blocked) and PHP functions for API, but it was getting worse when I wanted to use thumbnails.
Refering #731 and #741, is it possible to disable CORS on `/static/thumbnails`, `/static/previews/`, `/static/avatars/` and maybe, even for `/download/videos/`?

**Comment by rigelk** [comment]
Why don't we just add this to the head of `server/controllers/static.ts`:

```js
staticRouter.use(cors({
  origin: '*',
  methods: 'GET,HEAD,POST'
}))
```

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/commit/62945f067b90961d6947287014ef5b64781d7ca1

ping @rezonant

**Comment by DavidLibeau** [comment]
Hello,
In v1.0.0-beta.10.pre.1, API routes are working but static files are blocked by CORS.
For example : 
```
Failed to load https://videonaute.fr/static/thumbnails/87b8af73-ec0a-4b3b-8fb5-eff0f1b82061.jpg: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://dav.li' is therefore not allowed access.
```
Is `if (isTestInstance()) {` of [line 116](https://github.com/Chocobozzz/PeerTube/commit/62945f067b90961d6947287014ef5b64781d7ca1#diff-5c092da67283b0b787b618509fa7b96fR116) have something to do with it?

**Comment by DavidLibeau** [comment]
@Chocobozzz  Yep

**Comment by Chocobozzz** [comment]
Did you update it? (breaking changes in changelog)

**Comment by DavidLibeau** [comment]
Ok, I didn't understand that we need to manually update nginx conf. All is good now.
