### ISSUE TITLE
Minimal version of Peertube

### ISSUE THREAD

**Issue by sundowndev** [Chocobozzz/PeerTube#814]
If someone wants to be part of a network of instances but don't want to launch his own video sharing platform as they only want to contribute, I think it would be great if there was a minimal version of Peertube. Which means it only seeds videos of others instances with the server side only. So any web client.

This could reduce the performances/server cost as there would be no web client and database(?). Also I think this is impossible to share other instance's videos without showing them on the platform. I mean to seed the other instance's videos only. So if someone wants to increase his own network of seeders and contribute to others instances in the same time, he would need this kind of project.

In the mean time, this could be great for someone who only wants to get the server side of peertube (API) and the minimal things to get started on a fork of PeerTube, create his own client and his own license. For example that's what we want to do at [Dreamvo](https://github.com/Dreamvo). Some companies may like to be a instance of PeerTube with their own architecture, client and business model.

This could be a huge improvement because as soon as the techno and architecture behind PeerTube would become more flexible and accessible, a lot of companies would create their very own Peertube-based video sharing platform with their own client/design/business model and features. Instances would become more different each other and the number of "custom" instances will multiply, generating a lot of money out of PeerTube. I think that would be awesome for PeerTube ecosystem and a strong alternative to YouTube.

**Comment by fredsif** [comment]
That's a great idea.
Specially the API part.

**Comment by rigelk** [comment]
You can now (in develop) install server dependencies only via `NOCLIENT=1 yarn install --pure-lockfile` and start the server without the web client via `npm run start:server`.
