### ISSUE TITLE
Missing video on federated instances

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#815]
* **PeerTube version or URL:** https://www.yiny.org

Hello,
I apologize in advance for my approximate English. French translation at end of the message.

My instance has several followers. Everything works fine, except one thing...
I added a video the 13th july, and I can't find it on following instances.
I think it may be related to a migration from one server to another, with another IP. I uploaded the video just after the migration. I know that for some users there was a DNS cache problem for about one hour. Maybe it broke the activitypub sync ? Is there a way to re-publish the video to federated instances ?
Here is the link for this particular video : https://www.yiny.org/videos/watch/79ecdead-b97f-4d4d-b878-ac331411a007
All others videos are available on following instances.
One last thing : I follow my instance on mastodon (my mamot.fr account is following @peertube@www.yiny.org). In the peertube feed, this video il also missing.

**** FRENCH TRANSLATION ****
Mon instance est suivie par différentes instances. Tout marche bien, sauf une chose....
J'ai ajouté une vidéo le 13 juillet, et elle est introuvable depuis les instances fédérées.
Je pense que c'est lié à une migration de serveur, avec changement d'IP. J'ai uploadé la vidéo juste après la migration. Je sais que certains utilisateurs ont eu des problèmes de cache pendant environ 1h. Peut être que ça a pu casser la synchronisation activitypub ? Y'a t'il un moyen de republier la vidéo sur les instances fédérées ?
Le lien vers la vidéo en question : https://www.yiny.org/videos/watch/79ecdead-b97f-4d4d-b878-ac331411a007
Les autres vidéos de mon instance sont disponibles sur les instances fédérée, il n'y a que celle là qui manque.
Une dernière chose : je suis mon instance sur mastodon (mon compte sur mamot.fr est abonné à @peertube@www.yiny.org). Dans le flux, cette vidéo manque également.

**Comment by Chocobozzz** [comment]
> Is there a way to re-publish the video to federated instances ?

Try to update the video (add a tag for example). It will schedule a video update, and other peertube instances will create the video if it does not exist.

**Comment by JohnXLivingston** [comment]
It did not work.

It seems that peertube.nsa.ovh just followed my instance :
`{
  "uri": "https://peertube.nsa.ovh/accounts/peertube/inbox",
  "signatureActorId": 1,
  "body": {
    "type": "Accept",
    "id": "https://peertube.nsa.ovh/accounts/peertube/accepts/follows/1",
    "actor": "https://www.yiny.org/accounts/peertube",
    "object": {
      "type": "Follow",
      "id": "https://peertube.nsa.ovh/accounts/peertube/follows/1",
      "actor": "https://peertube.nsa.ovh/accounts/peertube",
      "object": "https://www.yiny.org/accounts/peertube"
    }
  }
}`

But... https://peertube.nsa.ovh/videos/search?search=yiny => this video is still missing.

Perhaps it has nothing to do with the migration... An encoding problem ? utf8 ? Logs seems ok...

**Comment by KRtekTM** [comment]
I have the same issue.
I'm using the develop version of PeerTube (with bull instead of kue) and the same follower (peertube.nsa.ovh) and all other followers have just a subset of Pirtube.cz local videos (and each follower has slightly different subset).
In log files, there are no errors - just followers trying to execute update sql query.

**Comment by Chocobozzz** [comment]
@JohnXLivingston Search in the log the string "79ecdead-b97f-4d4d-b878-ac331411a007" and potential error around these lines. It seems the peertube instance did not announced (shared) this particular video.

**Comment by JohnXLivingston** [comment]
I used rgrep on /var/log/*.3.gz (13th july). Did not find error messages

**Comment by JohnXLivingston** [comment]
Nothing relevant :(

**Comment by JohnXLivingston** [comment]
Hum...
When I edit this video, i got this : 
{"level":"info","message":"Updating 1 good actor follows and 0 bad actor follows scores.","splat":[1,0],"timestamp":"2018-07-16T16:15:38.698Z","label":"www.yiny.org:443"}


And with another video:
{"level":"info","message":"Updating 18 good actor follows and 5 bad actor follows scores.","splat":[18,5],"timestamp":"2018-07-16T16:14:23.645Z","label":"www.yiny.org:443"}


Only 1 actor for the first video !

**Comment by Chocobozzz** [comment]
Yes, because the video was not announced by the peertube instance for an unknown reason.

**Comment by JohnXLivingston** [comment]
Can I manually launch some script ?

**Comment by Chocobozzz** [comment]
No sorry

**Comment by KRtekTM** [comment]
yes, I also get the "Updating 1 good actor follows and 0 bad actor follows scores." messages

**Comment by Kelgors** [comment]
This is the same for me. 
10 follows, only 1 video on each instance (The second one i've posted).
When i update an absent video from following instances, nothing happen in the update for theses instances.

```
{"uris":["https://mastodon.social/inbox"],"level":"debug","message":"Creating broadcast job.","timestamp":"2018-07-17T14:26:44.962Z","label":"www.1ef51.com:443"}
{"level":"info","message":"Updating %d good actor follows and %d bad actor follows scores.","splat":[1,0],"timestamp":"2018-07-17T14:26:45.052Z","label":"www.1ef51.com:443"}
```

When i update an existing video, the video is updated on each remote instances.
```
{"uris":["https://exode.me/inbox","https://mastodon.social/inbox","https://meilleurtube.delire.party/inbox","https://pe.ertu.be/inbox","https://peertube.nipponalba.scot/inbox","https://peertube.nsa.ovh/inbox","https://peertube.pl/inbox","https://peertube.social/inbox","https://peertube.waifus.eu/inbox","https://tube.cccp.io/inbox"],"level":"debug","message":"Creating broadcast job.","timestamp":"2018-07-17T14:25:22.017Z","label":"www.1ef51.com:443"}
{"level":"info","message":"Updating %d good actor follows and %d bad actor follows scores.","splat":[10,0],"timestamp":"2018-07-17T14:25:23.599Z","label":"www.1ef51.com:443"}
```

**Comment by Nutomic** [comment]
I have the same problem, with [this video](https://video.blender.org/videos/watch/b37a5b9f-e6b5-415c-b700-04a5cd6ec205). I am following the instance, and [other videos](https://peertube.social/accounts/blender@video.blender.org/videos) from the same channel all show up. It also doesn't look like an issue with the source instance, because [videonaute.fr](https://videonaute.fr/videos/watch/b37a5b9f-e6b5-415c-b700-04a5cd6ec205) shows the videos correctly. 

I can't find the video ID in any of the logs in `/var/www/peertube/storage/logs`. And I also didn't do anything unusual with my instance, other than updating it.

**Comment by usbsnowcrash** [comment]
I have noticed the same thing for any new videos posted on my peertube instance.  They do not go out to my followers on mastodon UNLESS I also happen to comment on a video.  As soon as I comment on the video both my comment and the original message for the posting of the video seem to go out to my followers.

**Comment by popindavibe** [comment]
Also affected by this, none of my public videos (got only 3) show on instances following me. I can search them fine (at least partly).

**Comment by Chocobozzz** [comment]
Please, we can't help until you provide the instance URL, video URL, some logs (grep on the UUID of the video for example) and potential interesting jobs (try to find a job `activitypub-http-broadcast` containing your video).

**Comment by Nutomic** [comment]
@Chocobozzz I linked to a video in my comment above. The video UUID doesn't appear in any of the logs in `/var/www/peertube/storage/logs/`. But I can zip up all the logs and send them to you if that would help.

Is there any way to search jobs without going through them manually going through all of them on the website?

**Comment by Chocobozzz** [comment]
Closing this old issue, that should not happen again.
