### ISSUE TITLE
Delete channel confirmation already filled with previously deleted channel name

### ISSUE THREAD

**Issue by ldidry** [Chocobozzz/PeerTube#817]
* **PeerTube version or URL:** https://aperi.tube
* **Browser name/version:** FF Nightly (63)
* **NodeJS version:** v8.10.0

* **What is the expected behaviour?** After deleting a channel, the confirmation form to delete another channel should be empty.
* **What do you see instead?** The confirmation form contains the name (ie previous confirmation) of the previously deleted channel.

**Comment by Chocobozzz** [comment]
Thanks @ldidry, should be fixed in https://github.com/Chocobozzz/PeerTube/commit/a7dbc7dfc7a84b419a9b55d4a89e9a6e12384ae1
