### ISSUE TITLE
Blacklist local videos

### ISSUE THREAD

**Issue by FirePowi** [Chocobozzz/PeerTube#825]
* **PeerTube version or URL:** 1.0.0-beta.9

* **What is the wanted behaviour?**
The possibility for admin and modo to blacklist local videos so that they no more can be reached for a moment.
The goal is to give the possibility to moderate content, ask some things to add to description,… Before removing the video from the blacklist.

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/191764f30b0a812bf3a9dbdc7daf1d5afe25e12a
