### ISSUE TITLE
Log panel for admins / modo

### ISSUE THREAD

**Issue by FirePowi** [Chocobozzz/PeerTube#826]
* **PeerTube version or URL:** https://queertube.org 1.0.0bêta.9
* **Browser name/version:** Firefox 52.9

* **What is the wanted behaviour?**
When I go in « Administration » I want to have a "log" tab (With "Users","Manage Follows","Video abuses",… tabs).
What I want in it : 

    - New comments on videos : `[Comment] $author said "$commentFirst100digits…" in comment to video [$nameOfTheVideo]($linkToTheVideo) [*link*]($linkToTheComment) [administrationButtons][extendButton]`. When you click on "Extend" button you have : 
`[Comment]
From : $author
On : [$nameOfTheVideo]($linkToTheVideo)
Comment : $fullComment
[administrationButtons]
[shortenButton]`

    - New posted video : `[Video] $author posted [$nameOfTheVideo]($linkToTheVideo) [administrationButtons] [extendButton]`
Extend : 
`[Video]
From : $author
[$embeddedVideo]
[administrationButtons]
[shortenButton]`

This is open to discussion.

**Comment by Chocobozzz** [comment]
FYI RSS feeds can be used for now to get these information

**Comment by FirePowi** [comment]
Ok thanks.
I'll search for it :-)

**Comment by Nautigsam** [comment]
I think [audit logs](https://www.martinfowler.com/eaaDev/AuditLog.html) are what we want here. These are just another level of logs but they are emitted whenever a user do some writing action. They may be stored in a file different from other logs.

I checked the code of existing logger, and it seems that we could create a custom level with `winston`.

After this step, the admin would already have a clearer look on what is going on on his/her instance. Step 2 could be to send these logs to the front, but I think there is a lot to discuss before doing it.

**Comment by realityfabric** [comment]
There should definitely be audit logs for mod/admin actions at the very least. It's hard to hold people accountable if you have multiple moderators and no way to know who did what and when it happened.

Comprehensive logs would be good, too. But logs specifically for actions taken by mods and admins would be especially useful for instances with more than 2 moderators.

**Comment by Chocobozzz** [comment]
Done in https://github.com/Chocobozzz/PeerTube/commit/566c125d6eee3bd907404523d94e1e0b5e403a46
