### ISSUE TITLE
Bug in sorting and paging in administration

### ISSUE THREAD

**Issue by KRtekTM** [Chocobozzz/PeerTube#828]
* **PeerTube version or URL:** v1.0.0-beta9 (both production & develop)
* **Browser name/version:** Waterfox 56.2.1
* **NodeJS version:** 8.11.3

* **What is the expected behaviour?** Sorting and paging in administration works
* **What do you see instead?** When another sorting then "Created at" is used and switched to the other administration page with table where previously selected column isn't, it returns error 500 or something like that (it keeps the previous sorting column in cache so it tries to execute sql query with ordering by non-existing column).
When e.g. in Job list page switched to the page "7" on "Waiting" and then switch to the e.g. "active", where is just one page, it tries to read page 7th (as it keeps the page number in cache).

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

**Comment by Nautigsam** [comment]
I can't reproduce the "sorting bug" on Firefox 61. Here is what I did:
- Go on `/admin/users/list`
- Check that localStorage does not contain any preferences of sorting
- Sort by Username
- Go on `/admin/jobs/list`
Result: The grid is sorted by creation date. No error.

**Comment by KRtekTM** [comment]
https://pirtube.cz/videos/watch/d16c575b-4404-418a-865c-59f091a9ec71

**Comment by Nautigsam** [comment]
Okay so maybe it was fixed after you updated your instance. That would be great to know the last commit hash you have in order to compare with the current state of develop branch.

**Comment by KRtekTM** [comment]
This is the last commit I grabbed from develop: https://github.com/Chocobozzz/PeerTube/commit/3b492bff49bbab71e826cc4fe93db8c6a74a3391
as the TravisCI is failing for all next commits.

**Comment by Nautigsam** [comment]
I can't see any commit that could have fixed this bug. Maybe you could try with another browser.

**Comment by KRtekTM** [comment]
Reproducible also in Vivaldi 1.15.1147.42

**Comment by Chocobozzz** [comment]
I fixed the pagination issue: https://github.com/Chocobozzz/PeerTube/commit/6d8c70aa2dddd989f4605630a109db167128c1f5

For the sort I'm sorry but I could not reproduce either (thanks @Nautigsam btw). If someone else can reproduce feel free to comment, so we reopen this issue.
