### ISSUE TITLE
Transcoding thread error problem

### ISSUE THREAD

**Issue by zzoozzo1122** [Chocobozzz/PeerTube#831]
* **PeerTube version or URL:** v1.0.0-beta.9
* **Browser name/version:**  Google Chrome
* **NodeJS version:** 8.0

There are eight cpu threads.
I set four of them.
I uploaded the video after that.
However, only one image is being transcoded.

admin / jobs / list, 'Jobs'

Only one is shown in the active display.
Server performance is Intel Xeon D-1521-4c / 8t - 2.4GHz, RAM32G.

In conclusion, transcoding 1GB MP4 files to 480p, 720p will take too much time, even if the CPU is fast.

**Comment by Chocobozzz** [comment]
The CPU threads setting means how many threads ffmpeg will use to transcode a file, not how many concurrent transcoding jobs peertube runs.
