### ISSUE TITLE
Allow instance to set it's rules and show them on https://instances.joinpeertube.org/instances

### ISSUE THREAD

**Issue by thelastfantasy** [Chocobozzz/PeerTube#834]
What is allowed, and what is disallowed, position of the server, etc...

**Comment by Zig-03** [comment]
https://framagit.org/framasoft/peertube/joinpeertube

**Comment by Chocobozzz** [comment]
Hi @thelastfantasy, please could you open this issue in the appropriate repository? https://framagit.org/chocobozzz/instances-peertube

We already have a "terms" section so I don't think we need modifications on the PeerTube side.

Thanks!
