### ISSUE TITLE
Can I ask a question?

### ISSUE THREAD

**Issue by zzoozzo1122** [Chocobozzz/PeerTube#836]
* **PeerTube version or URL:** PeerTube v1.0.0-beta.9 
* **Browser name/version:** Chrome
* **NodeJS version:** v8.0

Can I ask a question?
I get into trouble when I upload a video with a capacity of 3 GB.

The conditions are as follows.
It has 3 GB of H.264/ACC/ and mp4 files.

If you click Enable Transcoding on the administrator's page and upload it, the transcoding speed is slow, so you can not quickly upload it.
At this time, the images are good.

However, if you disable transcoding and upload a file,
Video has been uploaded 100 %, but the video has not been released. 
It continues to take an infinite load.

In the old v10.0-beta.7, you can simply upload the file.
It worked normally.

How do I fix the problem in v10.0-beta.9?

**Comment by LecygneNoir** [comment]
Hello @zzoozzo1122 
In the beta9, an option was added to allow the uploader to wait for transcoding before publishing the video (mostly the comportment from Youtube)

You can uncheck this option when publishing the video, at the right bottom corner, where you also choose for NSFW.

You can also update an already published video to uncheck the option if transcoding take too much time

Hope it helps!

**Comment by zzoozzo1122** [comment]
I have already inactivated and uploaded that part.
However, there is no video.
Or, in about 10 minutes, the video comes out.

The video is H264, ACC coding and is an MP4 file.
However images are not output due to infinite loading.
New installations on new servers face the same problem.
It's about 3GB  in its old version of 0.7 beta. 
It's where there's no problem.
Sample site https://ts.oio.bz

**Comment by Chocobozzz** [comment]
Please try to reproduce your bug and pastbin your server log files so we can help you.

**Comment by zzoozzo1122** [comment]
On the server,
Where is the log file created?

1.https://ts.oio.bz/videos/watch/e26a79b4-6c02-4228-9d2a-d5de54655681
 Although Lee Young-sang is not playing.

2. (Register directly with Chrome browser)
https://ts.oio.bz/static/webseed/e26a79b4-6c02-4228-9d2a-d5de54655681-720.mp4
The picture works well.

What's the problem?
There's nothing wrong with beta 7.
This problem only occurs in beta 9.
It is not suitable for a new installation.

**Comment by Nautigsam** [comment]
@zzoozzo1122 Your logs are in `storage/logs/peertube.log`.

**Comment by zzoozzo1122** [comment]
After uploading the test image,
I checked the video on another computer.
The log messages are as follows :


{"level":"info","message":"Video with name h0005 and uuid 5326ef06-99b4-4cda-bc8a-bec74033e297 created.","splat":["h0005","5326ef06-99b4-4cda-bc8a-bec74033e297"],"timestamp":"2018-07-28T07:58:08.694Z","label":"ts.oio.bz:443"}
{"message":"108.61.183.181 - - [28/Jul/2018:07:58:08 +0000] \"POST /api/v1/videos/upload HTTP/1.0\" 200 65 \"https://ts.oio.bz/videos/upload\" \"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:58:08.701Z","label":"ts.oio.bz:443"}
{"level":"info","message":"Video with name h0005 and uuid 5326ef06-99b4-4cda-bc8a-bec74033e297 updated.","splat":["h0005","5326ef06-99b4-4cda-bc8a-bec74033e297"],"timestamp":"2018-07-28T07:58:26.819Z","label":"ts.oio.bz:443"}
{"message":"108.61.183.181 - - [28/Jul/2018:07:58:26 +0000] \"PUT /api/v1/videos/35 HTTP/1.0\" 204 - \"https://ts.oio.bz/videos/upload\" \"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:58:26.821Z","label":"ts.oio.bz:443"}
{"message":"108.61.183.181 - - [28/Jul/2018:07:58:27 +0000] \"GET /api/v1/videos/5326ef06-99b4-4cda-bc8a-bec74033e297 HTTP/1.0\" 200 2787 \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:58:27.130Z","label":"ts.oio.bz:443"}
{"message":"108.61.183.181 - - [28/Jul/2018:07:58:27 +0000] \"GET /api/v1/videos/?start=0&count=5&sort=-createdAt HTTP/1.0\" 200 3334 \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:58:27.163Z","label":"ts.oio.bz:443"}
{"message":"108.61.183.181 - - [28/Jul/2018:07:58:27 +0000] \"GET /api/v1/users/me/videos/35/rating HTTP/1.0\" 200 30 \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:58:27.495Z","label":"ts.oio.bz:443"}
{"message":"108.61.183.181 - - [28/Jul/2018:07:58:27 +0000] \"GET /static/previews/5326ef06-99b4-4cda-bc8a-bec74033e297.jpg HTTP/1.0\" 200 44717 \"https://ts.oio.bz/\" \"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:58:27.556Z","label":"ts.oio.bz:443"}
{"message":"108.61.183.181 - - [28/Jul/2018:07:58:27 +0000] \"GET /static/torrents/5326ef06-99b4-4cda-bc8a-bec74033e297-720.torrent HTTP/1.0\" 200 17869 \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:58:27.999Z","label":"ts.oio.bz:443"}
{"message":"108.61.183.181 - - [28/Jul/2018:07:58:59 +0000] \"POST /api/v1/videos/5326ef06-99b4-4cda-bc8a-bec74033e297/views HTTP/1.0\" 204 - \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:58:59.988Z","label":"ts.oio.bz:443"}
{"message":"210.114.215.113 - - [28/Jul/2018:07:59:50 +0000] \"GET /videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297 HTTP/1.0\" 200 5085 \"-\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:59:50.958Z","label":"ts.oio.bz:443"}
{"message":"210.114.215.113 - - [28/Jul/2018:07:59:51 +0000] \"GET /api/v1/config/ HTTP/1.0\" 304 - \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:59:51.758Z","label":"ts.oio.bz:443"}
{"message":"210.114.215.113 - - [28/Jul/2018:07:59:51 +0000] \"GET /api/v1/videos/categories HTTP/1.0\" 304 - \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:59:51.760Z","label":"ts.oio.bz:443"}
{"message":"210.114.215.113 - - [28/Jul/2018:07:59:51 +0000] \"GET /api/v1/videos/languages HTTP/1.0\" 304 - \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:59:51.764Z","label":"ts.oio.bz:443"}
{"message":"210.114.215.113 - - [28/Jul/2018:07:59:51 +0000] \"GET /api/v1/videos/licences HTTP/1.0\" 304 - \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:59:51.765Z","label":"ts.oio.bz:443"}
{"message":"210.114.215.113 - - [28/Jul/2018:07:59:51 +0000] \"GET /api/v1/oauth-clients/local HTTP/1.0\" 304 - \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:59:51.767Z","label":"ts.oio.bz:443"}
{"message":"210.114.215.113 - - [28/Jul/2018:07:59:51 +0000] \"GET /api/v1/videos/privacies HTTP/1.0\" 304 - \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:59:51.769Z","label":"ts.oio.bz:443"}
{"err":"invalid_token: Invalid token: access token has expired\n    at new InvalidTokenError (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/lib/errors/invalid-token-error.js:25:14)\n    at AuthenticateHandler.validateAccessToken (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:224:11)\n    at AuthenticateHandler.<anonymous> (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:74:19)\n    at PassThroughHandlerContext.finallyHandler (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/finally.js:57:23)\n    at PassThroughHandlerContext.tryCatcher (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:693:18)\n    at Async._drainQueue (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:794:20)\n    at tryOnImmediate (timers.js:752:5)\n    at processImmediate [as _immediateCallback] (timers.js:729:5)","level":"warn","message":"Cannot authenticate.","timestamp":"2018-07-28T07:59:51.780Z","label":"ts.oio.bz:443"}
{"message":"210.114.215.113 - - [28/Jul/2018:07:59:51 +0000] \"GET /api/v1/users/me HTTP/1.0\" 401 52 \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:59:51.782Z","label":"ts.oio.bz:443"}
{"message":"210.114.215.113 - - [28/Jul/2018:07:59:52 +0000] \"GET /api/v1/videos/5326ef06-99b4-4cda-bc8a-bec74033e297 HTTP/1.0\" 200 2787 \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:59:52.205Z","label":"ts.oio.bz:443"}
{"err":"invalid_token: Invalid token: access token has expired\n    at new InvalidTokenError (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/lib/errors/invalid-token-error.js:25:14)\n    at AuthenticateHandler.validateAccessToken (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:224:11)\n    at AuthenticateHandler.<anonymous> (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:74:19)\n    at PassThroughHandlerContext.finallyHandler (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/finally.js:57:23)\n    at PassThroughHandlerContext.tryCatcher (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:693:18)\n    at Async._drainQueue (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:794:20)\n    at tryOnImmediate (timers.js:752:5)\n    at processImmediate [as _immediateCallback] (timers.js:729:5)","level":"warn","message":"Cannot authenticate.","timestamp":"2018-07-28T07:59:52.213Z","label":"ts.oio.bz:443"}
{"message":"210.114.215.113 - - [28/Jul/2018:07:59:52 +0000] \"GET /api/v1/videos/?start=0&count=5&sort=-createdAt HTTP/1.0\" 401 52 \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:59:52.216Z","label":"ts.oio.bz:443"}
{"message":"210.114.215.113 - - [28/Jul/2018:07:59:52 +0000] \"POST /api/v1/users/token HTTP/1.0\" 200 159 \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:59:52.237Z","label":"ts.oio.bz:443"}
{"err":"invalid_token: Invalid token: access token is invalid\n    at new InvalidTokenError (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/lib/errors/invalid-token-error.js:25:14)\n    at /var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:203:15\n    at tryCatcher (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:693:18)\n    at Async._drainQueue (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/var/www/peertube/versions/peertube-v1.0.0-beta.9/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:794:20)\n    at tryOnImmediate (timers.js:752:5)\n    at processImmediate [as _immediateCallback] (timers.js:729:5)","level":"warn","message":"Cannot authenticate.","timestamp":"2018-07-28T07:59:52.566Z","label":"ts.oio.bz:443"}
{"message":"210.114.215.113 - - [28/Jul/2018:07:59:52 +0000] \"GET /api/v1/users/me/videos/35/rating HTTP/1.0\" 401 52 \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:59:52.571Z","label":"ts.oio.bz:443"}
{"message":"210.114.215.113 - - [28/Jul/2018:07:59:52 +0000] \"GET /static/previews/5326ef06-99b4-4cda-bc8a-bec74033e297.jpg HTTP/1.0\" 200 44717 \"https://ts.oio.bz/\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:59:52.948Z","label":"ts.oio.bz:443"}
{"message":"210.114.215.113 - - [28/Jul/2018:07:59:53 +0000] \"GET /api/v1/users/me HTTP/1.0\" 304 - \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:59:53.049Z","label":"ts.oio.bz:443"}
{"message":"210.114.215.113 - - [28/Jul/2018:07:59:53 +0000] \"GET /api/v1/videos/?start=0&count=5&sort=-createdAt HTTP/1.0\" 200 3334 \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:59:53.069Z","label":"ts.oio.bz:443"}
{"message":"210.114.215.113 - - [28/Jul/2018:07:59:53 +0000] \"POST /api/v1/users/token HTTP/1.0\" 200 159 \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:59:53.083Z","label":"ts.oio.bz:443"}
{"message":"210.114.215.113 - - [28/Jul/2018:07:59:53 +0000] \"GET /static/torrents/5326ef06-99b4-4cda-bc8a-bec74033e297-720.torrent HTTP/1.0\" 200 17869 \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:59:53.369Z","label":"ts.oio.bz:443"}
{"message":"210.114.215.113 - - [28/Jul/2018:07:59:53 +0000] \"GET /api/v1/users/me/videos/35/rating HTTP/1.0\" 200 30 \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T07:59:53.660Z","label":"ts.oio.bz:443"}
{"message":"210.114.215.113 - - [28/Jul/2018:08:00:24 +0000] \"POST /api/v1/videos/5326ef06-99b4-4cda-bc8a-bec74033e297/views HTTP/1.0\" 204 - \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T08:00:24.563Z","label":"ts.oio.bz:443"}
{"message":"220.73.1.4 - - [28/Jul/2018:08:00:48 +0000] \"GET /videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297 HTTP/1.0\" 200 5085 \"-\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T08:00:48.884Z","label":"ts.oio.bz:443"}
{"message":"220.73.1.4 - - [28/Jul/2018:08:00:49 +0000] \"GET /api/v1/config/ HTTP/1.0\" 304 - \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T08:00:49.302Z","label":"ts.oio.bz:443"}
{"message":"220.73.1.4 - - [28/Jul/2018:08:00:49 +0000] \"GET /api/v1/videos/categories HTTP/1.0\" 304 - \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T08:00:49.304Z","label":"ts.oio.bz:443"}
{"message":"220.73.1.4 - - [28/Jul/2018:08:00:49 +0000] \"GET /api/v1/videos/languages HTTP/1.0\" 304 - \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T08:00:49.307Z","label":"ts.oio.bz:443"}
{"message":"220.73.1.4 - - [28/Jul/2018:08:00:49 +0000] \"GET /api/v1/videos/licences HTTP/1.0\" 304 - \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T08:00:49.311Z","label":"ts.oio.bz:443"}
{"message":"220.73.1.4 - - [28/Jul/2018:08:00:49 +0000] \"GET /api/v1/videos/privacies HTTP/1.0\" 304 - \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T08:00:49.313Z","label":"ts.oio.bz:443"}
{"message":"220.73.1.4 - - [28/Jul/2018:08:00:49 +0000] \"GET /api/v1/oauth-clients/local HTTP/1.0\" 304 - \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T08:00:49.314Z","label":"ts.oio.bz:443"}
{"message":"220.73.1.4 - - [28/Jul/2018:08:00:49 +0000] \"GET /api/v1/videos/?start=0&count=5&sort=-createdAt HTTP/1.0\" 200 3334 \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T08:00:49.682Z","label":"ts.oio.bz:443"}
{"message":"220.73.1.4 - - [28/Jul/2018:08:00:49 +0000] \"GET /api/v1/videos/5326ef06-99b4-4cda-bc8a-bec74033e297 HTTP/1.0\" 200 2787 \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T08:00:49.687Z","label":"ts.oio.bz:443"}
{"message":"220.73.1.4 - - [28/Jul/2018:08:00:49 +0000] \"GET /static/previews/5326ef06-99b4-4cda-bc8a-bec74033e297.jpg HTTP/1.0\" 200 44717 \"https://ts.oio.bz/\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T08:00:49.952Z","label":"ts.oio.bz:443"}
{"message":"220.73.1.4 - - [28/Jul/2018:08:00:50 +0000] \"GET /static/torrents/5326ef06-99b4-4cda-bc8a-bec74033e297-720.torrent HTTP/1.0\" 200 17869 \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T08:00:50.286Z","label":"ts.oio.bz:443"}
{"message":"220.73.1.4 - - [28/Jul/2018:08:01:24 +0000] \"POST /api/v1/videos/5326ef06-99b4-4cda-bc8a-bec74033e297/views HTTP/1.0\" 204 - \"https://ts.oio.bz/videos/watch/5326ef06-99b4-4cda-bc8a-bec74033e297\" \"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36\"\n","level":"info","timestamp":"2018-07-28T08:01:24.215Z","label":"ts.oio.bz:443"}
