### ISSUE TITLE
Can not run tests (inside a Docker container)

### ISSUE THREAD

**Issue by Nautigsam** [Chocobozzz/PeerTube#839]
I try to run tests inside a docker container and I get this error:
```
Error: EACCES: permission denied, mkdir '/storage'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/app/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/app/node_modules/mkdirp/index.js:77:24)
    at Object.<anonymous> (/app/server/helpers/logger.ts:10:8)
```
Here is the command I used: `npm run travis -- api-fast`

I digged into the code and I found this [quite obscure way to return the root of the project](https://github.com/Chocobozzz/PeerTube/blob/develop/server/helpers/core-utils.ts#L40). In my case `__dirname` equals `/app/server/helpers` and `process.mainModule.filename` equals `/app/node_modules/mocha/bin/_mocha`, so the resulting path is `/`.

Wouldn't it be better to hard write the root path of the project in the configuration, or at least allowing to overwrite it?

**Comment by Chocobozzz** [comment]
What docker image do you use? I don't think we have docker images for development so we can't really run tests inside docker.

If you really want to do it, you'll have to create a `data/` directory at the root of the container for example so PeerTube has the rights to create automatically the directories it need (like we do for the [production image](https://github.com/Chocobozzz/PeerTube/blob/develop/support/docker/production/Dockerfile.stretch#L62).

**Comment by Nautigsam** [comment]
Actually I tried with a custom image. I wanted to build a lightweight image to code and run the tests and bind the files on the host with the container to avoid copies. However I realize this is too much to ask regarding the tests architecture.
