### ISSUE TITLE
Schedule uses date when the schedule is set as publishedAt instead of the scheduled date

### ISSUE THREAD

**Issue by LecygneNoir** [Chocobozzz/PeerTube#842]
Hello !

* **PeerTube version or URL:** v1.0.0-beta9 (https://videos.lecygnenoir.info/about)
* **NodeJS version:** v8.11.3

**Problem**:  
I have noticed when using the Schedule option that peertube doesn't use the scheduled data as published date.

Instead, it uses the date where you have uploaded the video and chosen your schedule.

For example, I have scheduled this video : https://videos.lecygnenoir.info/videos/watch/ca3030a5-f4d1-4e9d-8fdb-d16db5ff6d83 to be published at 20:00 (UTC+2), and indeed it has been set public at this date  
But the displayed published date is around 13:25, which is the date when I upload the video and configure its schedule.

The problem is also visible on mastodon notification. The notification is pushed at 20:00, but the hour inside the notification is 13:25:
![capture d ecran de 2018-07-24 10-59-37](https://user-images.githubusercontent.com/7755000/43127821-b00bfa04-8f30-11e8-84ca-e96fbfb66886.png)

You can see the bottom notification (from my bot) is 14 hours ago (20:00), thus the upper (from peertube instance) is 21h ago (13:25), although they are published exactly at the same minute in reality.

I guess there is some problem when filling the publishedAt field internally, the video should not be considered as published until the schedule is reached?
Or am I missing something about activitypub protocol?

Thank you!

Regards,

**Comment by Chocobozzz** [comment]
> and indeed it has been set public at this date

\o/ 

> But the displayed published date is around 13:25, which is the date when I upload the video and configure its schedule.

:'(

Fixed in https://github.com/Chocobozzz/PeerTube/commit/77de223a5f5aca1dc32e23ca22a8ac7d8b009c4f
