### ISSUE TITLE
Api following giving only 15 latest nodes

### ISSUE THREAD

**Issue by Jorropo** [Chocobozzz/PeerTube#844]
I'm making a program for advanced discovering of node ([github.com/Jorropo/peertube-autoDiscover/](https://github.com/Jorropo/peertube-autoDiscover/)) (this will ask each node her following and followers nodes list and redo for each new node).
But on [peertube.jorropo.ovh/api/v1/server/following](https://peertube.jorropo.ovh/api/v1/server/following) and all other nodes tested (NSA) it only give the 15 latest added node.
I would know how to get the full node list (I don't think this is a bug just only without the api doc this is difficult)

**Comment by Chocobozzz** [comment]
Use the `start` and `count` parameters: https://htmlpreview.github.io/?https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/api/html/index.html#operation--server-followers-get

**Comment by Jorropo** [comment]
This parameters is get or post ? (and thx for doc, very hard to find)
And can I set count -1 to get all ?

**Comment by Chocobozzz** [comment]
> This parameters is get or post ?

It's written: `in query` so GET parameters (?count=20&start=0)

> (and thx for doc, very hard to find)

It's in the readme https://github.com/Chocobozzz/PeerTube#api-rest-documentation  ^^

> And can I set count -1 to get all ?

nope

**Comment by Jorropo** [comment]
Ok thx, and sorry, maybe I need to see an eye doctor
