### ISSUE TITLE
WhiteBook of Best Encoding usages for PeerTube

### ISSUE THREAD

**Issue by warnerbryce** [Chocobozzz/PeerTube#849]
Hello to the team, 
Bravo for the good work you've made so far. 

I just create my Peertube instance and uploaded my first video. 

I see that i have transcoding waiting before my video will be avialable. 

I would like to know, what are the best encoding option i have to put in order to not have transcoding into my PeerTube instance ? 

I have a Canon 7D who makes 1080p 25(or 24)ips in .MOV format, so i transcode them into VEGAS into a .mp4 1080/25p 20Mbit/sMax - 10Mbits/sAverage.

**Comment by Jorropo** [comment]
if you would you can disable transcoding (with an admin account, administration > Configuration > Advanced Configuration > Here must be an check box with transcoding enable, don't forget to save).
But you SHOULDN'T do that, why ? transcoding is a way to reduce space taken by the video (if possible).
Not everybody have optical fiber 20 Mbit/s network.
Little computer and netbook may don't have the cpu or ram to manage 1080 ppx.

If you would you can publish the video while transcoding (while uploading on right down of your screen (if you don't see it scroll down) you normaly see "Wait transcoding before publishing the video" uncheck it and after upload video should be online but not with all resolution) uncheck.

If you don't have these option : update to last version (PeerTube v1.0.0-beta.9) can be see for any node in bottom of the page in about section.

**Comment by warnerbryce** [comment]
Thanks for the answer. 

So my workflow will be. 
Edit a video and export it as .mp4 with the best resolution and bitrate for web watching. 
Then upload it on my instance with : 
Upload after transcoded and choose those resolution 480p/720p/1080p. 

Thanks again

**Comment by rigelk** [comment]
@warnerbryce that is a sound workflow. Keep in mind 10Mbit/s is still quite a high average bandwidth. Try to keep it less than 3Mbit/s.

As for the concern of uploading videos in the right format and encoding profile so that the server doesn't need to transcode, we keep it in mind for after the first stable.
