### ISSUE TITLE
Rejected files remain in /store/videos/ folder.

### ISSUE THREAD

**Issue by kyrahabattoir** [Chocobozzz/PeerTube#851]
* **PeerTube version or URL:**
http://peertube.ethernia.net
* **Browser name/version:**
Firefox Quantum 61.0.1 (64 bits)
* **NodeJS version:**
net-libs/nodejs-8.11.1
* **What is the expected behaviour?**
Files that have been rejected by the upload system should be purged from the server.
* **What do you see instead?**
I tried to upload a MKV (out of curiousity), as expected the file format was rejected, however the file is still on the sever in storage/videos/ as "6690e52cffd5c7da7f58775c24a4ee8fundefined"

**Comment by Jorropo** [comment]
Bug reproduced with ppv format

**Comment by Jorropo** [comment]
Temporary file may should be uploaded in a peertube subdirectory of /tmp/ ?

**Comment by kyrahabattoir** [comment]
The thing is it's not "temporary" (I have no idea where 'in progress' uploads are stored). I can't read nodejs code but i assume the file gets copied as its format get detected, but 'undefined' should cause the file to be deleted.

**Comment by Chocobozzz** [comment]
Thanks for the issue.

Should be fixed in https://github.com/Chocobozzz/PeerTube/commit/cf7a61b5a2b68fd966c4a355e37e84b048ed296b
