### ISSUE TITLE
Upload fails if you browse the same instance in another tab.

### ISSUE THREAD

**Issue by kyrahabattoir** [Chocobozzz/PeerTube#853]
* **PeerTube version or URL:**
https://peertube.ethernia.net
* **Browser name/version:**
Firefox Quantum 61.0.1 (64 bits)
* **NodeJS version:**
net-libs/nodejs-8.11.1

* **What is the expected behaviour?**
It should work just fine.
* **What do you see instead?**
Everytime I have an upload in progress, if i browse the same peertube instance from another tab, the upload stops.

(I don't know how to provide a log of what is happening)

**Comment by Jorropo** [comment]
I haven't the problem on my instance,
With same version for all program (ubuntu 18 for client, debian 9 server ^^).
You have 2 logs :
- Peertube log ```/var/www/peertube/storage/log/peertube.log```
- Nginx reverse proxy log ```/var/log/nginx/peertube.example.com.[access|error].log```

**Comment by hellomotow** [comment]
Not sure how it works exactly but I had this issue also when I tried uploading multiple videos manually at the same time.

**Comment by kyrahabattoir** [comment]
Could it be something related to low upload speed? I only have 1Mb of upload.

**Comment by Jorropo** [comment]
@kyrahabattoir, no, I only have 200 kB/s.
This is surely due to nginx http2 (cause normally tab aren't linked

**Comment by Jorropo** [comment]
I reproduced the bug, and find a new one :
If uploading then watch a new video, the upload is cancelled (beta.11).
http2 enabled.

**Comment by kyrahabattoir** [comment]
@Chocobozzz Sent you the informations.

**Comment by Chocobozzz** [comment]
Sorry for the late. After a conversation with @kyrahabattoir, it seems to be related to Firefox and/or a specific extension.

**Comment by scanlime** [comment]
I'm not sure if it's related, or exactly what's behind the bug I'm seeing, but I've seen uploads fail while I'm interacting with the UI. I'm not sure whether it was a metadata editing dropdown or another tab, because every time it's failed that was while I was doing a lot of things at once and the error messages are vague and self-disappearing :D
