### ISSUE TITLE
Videos sometimes freeze when jumping along timeline

### ISSUE THREAD

**Issue by hellomotow** [Chocobozzz/PeerTube#855]
I used the following commands to encode the videos myself and skipped the transcoding option on PeerTube

ffmpeg -i '/home/videos/unprocessed/vid.mp4' -f mp4 -vcodec libx264 -preset fast -profile:v main -acodec aac -movflags +faststart '/home/videos/processed/vid.mp4'

Now I am facing issues with around half of my videos, sometimes when you go along the videos timeline and click a random point in the video that part just wont load. The white rotating circle just shows forever. This is especially true when I jump to the last 5-10% of the video. Is this because I skipped transcoding? or is it because my ffmpeg command is not correct?

**Comment by Jorropo** [comment]
* **PeerTube version or URL:**
* **Browser name/version:**
* **NodeJS version:**


* **What is the expected behaviour?**
* **What do you see instead?**


* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

**Comment by hellomotow** [comment]
@Jorropo 
PeerTube v1.0.0-beta.9
8.11.3

**Comment by hellomotow** [comment]
Is there a way to transcode videos that are already live?

**Comment by rigelk** [comment]
@hellomotow https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md#create-transcoding-jobjs

**Comment by hellomotow** [comment]
@rigelk Thanks, is there a quick way to do it for all videos? will * work?

**Comment by rigelk** [comment]
No, it doesn't support globbing. You have to script it. But let me ask some admin who has already been in your situation.

**Comment by Chocobozzz** [comment]
I think this issue should be fixed by https://github.com/Chocobozzz/PeerTube/commit/b224ddd88b767b9a6402e3648993b4f2707057ef
