### ISSUE TITLE
Can't watch video by Firefox

### ISSUE THREAD

**Issue by imtube** [Chocobozzz/PeerTube#86]
I'm useing Firefox 55.03, Under Firefox, it says
The media could not be loaded, either because the server or network failed or because the format is not supported.

There is no problem under Chrome.

**Comment by Chocobozzz** [comment]
Have you a link to this video?

**Comment by Vertux** [comment]
I am using Safari v11.0 (13604.1.38.1.6) under macOS 10.13 (17A360a) and I got the same issue.
With Chrome and Vivaldi it works without any problems.

![bildschirmfoto 2017-09-09 um 16 37 28](https://user-images.githubusercontent.com/10457918/30241149-f54c40c2-957d-11e7-97f4-d5e04232f192.png)

**Comment by Chocobozzz** [comment]
Safari is not supported (yet?).

**Comment by Chocobozzz** [comment]
@Vertux Safari works too?

**Comment by iShift** [comment]
have same on safari

**Comment by Vertux** [comment]
> @Vertux Safari works too?

@Chocobozzz sometimes, but not always, in most cases I get the error message "media could not...." and then it takes a couple of seconds till the video starts playing. But in some cases I get the additional red error message and the video does not work at all.

**Comment by Chocobozzz** [comment]
Okay I created a dedicated issue.
