### ISSUE TITLE
Caption menu choice empty on chromium

### ISSUE THREAD

**Issue by zeograd** [Chocobozzz/PeerTube#860]
with version beta10 pre1 supporting srt, I have an empty menu for subtitles on chromium Version 64.0.3282.119 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)
video URL: https://peertube.touhoppai.moe/videos/watch/39657280-20bc-44ca-8416-c099fb3ee1c6 (which has english subtitles)

It might not be useful, but nodejs version is v8.10.0

I would expect the list of language for which a caption exists to appear.
Instead, the panel where the list of language appears (as can be seen on firefox e.g) has no text inside (but there is the animation to show a show panel, and the semi transparent background, only missing text and interactivity with the mouse as I tried clicking where "english" should have been showing).

cf https://imgur.com/a/kWDGYXg for 2 screenshots before and after clicking on subtitle language selection

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/3ac046e2a478a88e24d5ce82d4c43cdd64dea1a2
