### ISSUE TITLE
subtitle freeze

### ISSUE THREAD

**Issue by zeograd** [Chocobozzz/PeerTube#861]
On video https://peertube.touhoppai.moe/videos/watch/39657280-20bc-44ca-8416-c099fb3ee1c6 using firefox 63.0a1 (2018-07-26) (64-bit), when selecting the caption language, the current caption shows as expected, but it stays indefinitely and never switches to the next line.

Later, when choosing "off" and the language again, it shows the expected, new, caption at this time, but still remains frozen in this state.

The expected behaviour is to have the caption shown as timed in the .srt

Attached is the .srt (extension changed to .txt to fit github)
[maid_souffrante_eng.txt](https://github.com/Chocobozzz/PeerTube/files/2232559/maid_souffrante_eng.txt)

**Comment by Chocobozzz** [comment]
It works en dev but not on production >< 

Related to https://github.com/videojs/video.js/issues/5224

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/videojs/video.js/pull/5346 & https://github.com/Chocobozzz/PeerTube/commit/f7714668917c7191a2d9d015d28c22baa92e32b4
