### ISSUE TITLE
Desktop application

### ISSUE THREAD

**Issue by Jorropo** [Chocobozzz/PeerTube#869]
I'm working on a desktop version working with electron and I need your view of subject.
Currently my goal is to be 95% like the web client but with somethings more, keeping the video after viewing (and seed it), faster (no virtualisation), faster to load (all the client is already downloaded).

This desktop version will keep seeding after viewing the video (user will allocate some disk space to that, and all last viewed video will be keep until there isn't more space (the list will be FIFO (first in first out))), is there a problem for privacy ? (Cause video maybe will be keeped for weeks, this isn't like in browser where when you leave the page you stop seeding)

For dev, right now you have ```/server/``` and ```/client/```, what I have do right now is a copy of ```/client``` to ```/desktop/```, but the problem is when you do a modification of ```/client/``` or ```/desktop/``` you must redo the same on the other. Have you a better idea to manage that ?

**Comment by Jorropo** [comment]
@rigelk 
- "trancoding" I where thinking to do that with BOINC, each node with a boinc wrapper and maybe node can propose work from other node. (with boinc I havn't to redo a distributed calculation protocol)
- "long term seeding" That the first things I will do after the last viewed list.

I forget to precise than the goal to be 95 % like the client is short term.

**Comment by rigelk** [comment]
@Jorropo just a note on BOINC: as you have pointed out, it's relying on distributed calculations. Transcoding is not something that goes well with distributed calculus, as algorithms rely more and more on prediction based on the overall (or clustered to a number of frames ahead at least) video analysis. Of course you can give chunks to transcode, but that would be suboptimal (maybe not significant).

**Comment by AnonymousWebHacker** [comment]
donde esta esa version desktop? 
 :V

**Comment by HuGo-Y** [comment]
@Jorropo why have you closed this issue? I think it's an important one. Even lbry has a desktop app https://flathub.org/apps/details/io.lbry.lbry-app and I think we should have one as well!

**Comment by Jorropo** [comment]
> @Jorropo why have you closed this issue? I think it's an important one. Even lbry has a desktop app [flathub.org/apps/details/io.lbry.lbry-app](https://flathub.org/apps/details/io.lbry.lbry-app) and I think we should have one as well!

I've lost time and interest, but if you think it would be worth opening again you will just need to find someone to do it :smile: .
