### ISSUE TITLE
Where to get torrent or magnet uri?

### ISSUE THREAD

**Issue by mitchtbaum** [Chocobozzz/PeerTube#873]
How do I get a torrent or magnet of a video from its watch page?

**Comment by mitchtbaum** [comment]
..for example, like https://github.com/fastcast/fastcast
![fastcast-demo](https://user-images.githubusercontent.com/584077/43349292-b284e55e-91b3-11e8-87c0-fc666b75ae97.png)

**Comment by rigelk** [comment]
A right clic or clicking on the download button.

P.S.: Fastcast sounds like a ripoff of instant.io, with coin miners in their support links…
