### ISSUE TITLE
error: Your configuration files miss keys: services.twitter.whitelisted

### ISSUE THREAD

**Issue by yopethop** [Chocobozzz/PeerTube#874]
Hello

I'm trying to install a peertube instance on my server
I did all the installation, when I want to run peertube and watch the log with this: journalctl - peertube fire

I got this: error: Your configuration files miss keys: services.twitter.whitelisted

Does anyone have any ideas?

Thank you for your help.

**Comment by rigelk** [comment]
@yopethop did you use the provided configuration as a base? See https://github.com/Chocobozzz/PeerTube/blob/develop/config/default.yaml

**Comment by yopethop** [comment]
hi,

no i just use production.yaml

this is my file production

[production.yaml.txt](https://github.com/Chocobozzz/PeerTube/files/2237987/production.yaml.txt)

@rigelk

**Comment by rigelk** [comment]
Your indentation level is wrong for the last line. Please use the TOML format documentation and our production.yml.example as reference.

**Comment by yopethop** [comment]
oh ty, i dont see this...

now i have this error : 
 "err": "SequelizeConnectionError: password authentication failed for user \"peertube"\

database:
  hostname: 'localhost'
  port: 5432
  suffix: '_prod'
  username: 'peertube'
  password: 'password'

this hostname is correct ?

when I go to my web page I have this redirection error

"The page is not redirected correctly"

this install is not easy. sorry for my incompetence

Ty for your help :)

**Comment by rigelk** [comment]
Well have you created the user 'peertube' in PostgreSQL with said password?

**Comment by yopethop** [comment]
Je viens de procéder à la modification de mon mot de passe et tout est bon ^^
La prochaine fois je serais plus prudent :)

Merci pour ton aide et pour le temps que tu m'as consacré :)

**Comment by rigelk** [comment]
Pas de soucis :)
