### ISSUE TITLE
Hosting with Cloudflare

### ISSUE THREAD

**Issue by hellomotow** [Chocobozzz/PeerTube#877]
Other than the obvious "ERR_TOO_MANY_REDIRECTS" which can be fixed https://support.cloudflare.com/hc/en-us/articles/115000219871-Why-does-Flexible-SSL-cause-a-redirect-loop- are there any other issues I may face using Cloudflare with PeerTube? I see another issue (closed) related to upload limits (https://support.cloudflare.com/hc/en-us/articles/201303340-How-can-I-change-the-client-maximum-upload-size-) but that wont be a problem for us as we will upload them direct and have signups disabled.

Is there any other known issues?

**Comment by hellomotow** [comment]
It looks like the torrents have stopped working I will try to find a work around and post back. I'm sure others will want to be using Cloudflare in the future too.

**Comment by kyrahabattoir** [comment]
I know it's a bit off topic but... what's the point of running a decentralised video system on a centralised system like cloudflare >_>.

**Comment by hellomotow** [comment]
@kyrahabattoir PeerTube right now is very centralised for me anyway, running my own private video collection. Hopefully that will change soon once I can add multiple HTTP video nodes. Cloudflare does actually have some really good advantages for video download speeds, also the obvious DDOS protection.

**Comment by Chocobozzz** [comment]
Hi, I'm sorry but I have no experience with cloudflare. You could ask to their support or a forum, peertube is just an API REST + a tracker (websocket) + an upload endpoint so it's not a very complex backend.
