### ISSUE TITLE
Latest Preview version breaks Peertube for new Users

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#879]
* **PeerTube version or URL:** https://peertube.social,  v1.0.0-beta.10.pre.2
* **Browser name/version:** Firefox 61, Chromium 68
* **NodeJS version:** v8.11.3

* **What is the expected behaviour?**
Peertube loads correctly under all circumstances and embeds work.
* **What do you see instead?**
When opening Peertube in a private tab or with cookies etc deleted, it shows a blank page. The browser console shows the following error:
```
Loading failed for the <script> with source “https://peertube.social/client/en_US/runtime.fe22f0d7de21d92db0e8.js”.
```
Additionally, embeds on other sites are not working, showing a very similar error in the browser console:
```
Loading failed for the <script> with source “https://peertube.social/client/standalone/videos/video-embed.bba71cf4d11bbae53a15.bundle.js”.
```

Edit: Here is a website where you can try the embeds: https://jahr1nachsnowden.de

**Comment by Nutomic** [comment]
So I just tried to reboot the server, and that fixed the problem. Still pretty bad, because there was no indication that anything was wrong.

**Comment by Chocobozzz** [comment]
![it](http://lutim.cpy.re/6QmR8rNu.jpg)

If anyone else see this kind of issue, feel free to comment!
