### ISSUE TITLE
Helper next to channel instead of owner

### ISSUE THREAD

**Issue by gegeweb** [Chocobozzz/PeerTube#882]
* **PeerTube version or URL:** 1.0.0-beta.10.pre.2

* **What is the expected behaviour?**

Helper that explains how to follow a user on the fediverse should be next to the user's badge.

* **What do you see instead?**

When a video is in a owner's channel then the helper is next to the channel and explains how to subscribe to the user and not to the channel.
Next to the channel he should explain how to subscribe to the channel (I think this feature is not implemented yet).

<img width="505" alt="capture d ecran 2018-07-29 a 08 00 18" src="https://user-images.githubusercontent.com/9108457/43363489-2bb864b6-9306-11e8-88b5-78af413a49c7.png">

**Comment by Chocobozzz** [comment]
Thanks, fixed in https://github.com/Chocobozzz/PeerTube/commit/b7f5b524756e8a30c396ae40a262884766ef6554
