### ISSUE TITLE
Infinite delete actor jobs creation

### ISSUE THREAD

**Issue by Jorropo** [Chocobozzz/PeerTube#884]
* **PeerTube version or URL:**
pre-10-2
* **NodeJS version:**
8.11.3

* **What is the expected behaviour?**
An ask of delete should be executed or refused but if is refused this shouldn't be retryed in loop for 10 h at 1 request per second.
* **What do you see instead?**
Spamming in loop.

* **Server log if useful (Gist/Pastebin...):**
[https://gist.github.com/Jorropo/901c93b1411dd64e5926db43ff61471f](https://gist.github.com/Jorropo/901c93b1411dd64e5926db43ff61471f)
I can't contact the admin of [tube.openalgeria.org](https://tube.openalgeria.org/) for get his log, I didn't find her mail.

**Comment by Chocobozzz** [comment]
I already saw this with peertube.pl instance. Maybe a bug with the queue migration, because we cannot delete `root` and he exists on the [origin instance](https://tube.openalgeria.org/accounts/root/videos).

Any log or queue state would be appreciated.

**Comment by OpenAlgeria** [comment]
Hii @Jorropo 

This is my current log https://gist.github.com/OpenAlgeria/862f96050b110a663c1c2b706ca0cd8c

**Comment by Jorropo** [comment]
If I correctly understand @OpenAlgeria logs (thx) that should by a problem with my node.
I were having issue with redis so I purge the redis db. (while peertube were stopped), this could be that ?

**Comment by Chocobozzz** [comment]
I have no clue on what happened here. So for now I just deleted the migration to bull: https://github.com/Chocobozzz/PeerTube/commit/05882211077a30e27ebbb79baff0cf8fb87b7ae2

It's not that bad if we loose some jobs.

**Comment by Chocobozzz** [comment]
It seems fixed, closing.
