### ISSUE TITLE
 error: Cannot execute migration 0230

### ISSUE THREAD

**Issue by anmol26s** [Chocobozzz/PeerTube#885]
Migration is failing on peertube@1.0.0-beta.10.pre.2

```

peertube@1.0.0-beta.10.pre.2 start /var/www/peertube
Jul 29 12:13:49 domain.tld peertube[23720]: > node dist/server
Jul 29 12:13:55 domain.tld peertube[23720]: [domain.tld:443] 2018-07-29 12:13:55.885 info: Begin migrations.
Jul 29 12:13:55 domain.tld peertube[23720]: [domain.tld:443] 2018-07-29 12:13:55.890 info: Executing 0230-kue-to-bull.js migration script.
Jul 29 12:13:56 domain.tld peertube[23720]: [domain.tld:443] 2018-07-29 12:13:56.382 error: Cannot execute migration 0230.
Jul 29 12:13:56 domain.tld peertube[23720]: npm ERR! code ELIFECYCLE
Jul 29 12:13:56 domain.tld peertube[23720]: npm ERR! errno 255
Jul 29 12:13:56 domain.tld peertube[23720]: npm ERR! peertube@1.0.0-beta.10.pre.2 start: `node dist/server`
Jul 29 12:13:56 domain.tld peertube[23720]: npm ERR! Exit status 255
Jul 29 12:13:56 domain.tld peertube[23720]: npm ERR!
Jul 29 12:13:56 domain.tld peertube[23720]: npm ERR! Failed at the peertube@1.0.0-beta.10.pre.2 start script.

```

**Comment by joshmorel** [comment]
After running each command you should see on stdout: `CREATE EXTENSION`.

Then if you jump to the end of the peertube logs after restarting you should see:

```bash
$ sudo journalctl -eu peertube
Jul 29 16:46:54 peertubetest peertube[4506]: > node dist/server
Jul 29 16:46:56 peertubetest peertube[4506]: [peertubetest.refactored.ca:443] 2018-07-29 16:46:56.207 info: Database peertube_prod is ready.
```

**Comment by anmol26s** [comment]
I have this message on running the commands again.

```
NOTICE:  extension "unaccent" already exists, skipping
NOTICE:  extension "pg_trgm" already exists, skipping
```

But I am getting same error mentioned in the first post.

**Comment by joshmorel** [comment]
Strange. I go the exact same error which was resolved by adding the extensions and restarting the service.

The only other thing I could think of... is the database named differently (i.e. not peertube_prod)?

The only reason the migrations would not be able to execute is because of the extensions were not created as far as I can tell.

**Comment by anmol26s** [comment]
My database is not peertube_prod, so I have changed the command according to my database name. But can the migration have error because of this?

**Comment by joshmorel** [comment]
As long as the database name is peertube{suffix} where suffix corresponds to the `production.yaml` `database.suffix` value all should be good. Haven't tested but assuming as all database related stuff (including migrations) use this config value.

**Comment by Chocobozzz** [comment]
The explanation should be better now: https://github.com/Chocobozzz/PeerTube/commit/6af6cf831f0c76bc4646b82047733d1b4ef5e26c

**Comment by anmol26s** [comment]
My database is peertube_peertube and its giving error.
