### ISSUE TITLE
After upgrading, thousands of activitypub-http-broadcast jobs

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#889]
* **PeerTube version or URL:** https://www.yiny.org (v1.0.0-beta.10.pre.2)

After upgrading from beta 9 to beta 10 pre.2, peertube is creating thousands of jobs like this one :  

`{
  "uris": [
    "https://dialup.express/inbox",
    "https://exode.me/inbox",
    "https://li1846-42.members.linode.com/inbox",
    "https://mamot.fr/inbox",
    "https://mastodon.host/inbox",
    "https://meilleurtube.delire.party/inbox",
    "https://pe.ertu.be/inbox",
    "https://peer.tube/inbox",
    "https://peertube.azkware.net/inbox",
    "https://peertube.duckdns.org/inbox",
    "https://peertube.jorropo.ovh/inbox",
    "https://peertube.live/inbox",
    "https://peertube.mastodon.host/inbox",
    "https://peertube.nipponalba.scot/inbox",
    "https://peertube.nogafa.org/inbox",
    "https://peertube.nsa.ovh/inbox",
    "https://peertube.pl/inbox",
    "https://peertube.snargol.com/inbox",
    "https://peertube.social/inbox",
    "https://peertube.unlimitedammo.de/inbox",
    "https://peertube.video/inbox",
    "https://peertube.waifus.eu/inbox",
    "https://peertube2.cpy.re/inbox",
    "https://peertube3.cpy.re/inbox",
    "https://queertube.org/inbox",
    "https://tube.cccp.io/inbox",
    "https://tube.guin.ovh/inbox",
    "https://tube.h3z.jp/inbox",
    "https://tube.kdy.ch/inbox",
    "https://video.4ray.co/inbox",
    "https://video.qoto.org/inbox"
  ],
  "signatureActorId": 14,
  "body": {
    "type": "Delete",
    "id": "https://www.yiny.org/accounts/johnlivingston/delete",
    "actor": "https://www.yiny.org/accounts/johnlivingston",
    "object": "https://www.yiny.org/accounts/johnlivingston"
  }
}`

The account is mine... And should not be deleted...

There is 19000 jobs, and it continues.

**Comment by Chocobozzz** [comment]
Related to https://github.com/Chocobozzz/PeerTube/issues/889
