### ISSUE TITLE
Extracts can be truncated on a markdown markup (and shouldn't)

### ISSUE THREAD

**Issue by ldidry** [Chocobozzz/PeerTube#891]
Extracts should not be truncated in the middle of a markdown markup: it can prevent markdown to be correctly interpreted, that makes markdown markup displayed.

* **PeerTube version or URL:** PeerTube v1.0.0-beta.9
* **Browser name/version:** Firefox nightly
* **NodeJS version:** irrelevant

* **What is the expected behaviour?**
I should not see markdown markup in extracts.
* **What do you see instead?**
I  see markdown markup in extracts.

Example:
![](https://screenshotscdn.firefoxusercontent.com/images/b722fb37-7f26-4059-85f8-c9755e901083.png)

**Comment by Chocobozzz** [comment]
Thanks, hope this is fixed in https://github.com/Chocobozzz/PeerTube/commit/040467f5c8cba429176423d5e4b83bf5379ad101
