### ISSUE TITLE
Add zh-Hant-TW locale for Join PeerTube

### ISSUE THREAD

**Issue by s8321414** [Chocobozzz/PeerTube#892]
Because #801 is done, so I think I may translate Join PeerTube website, could you open this for me?

**Comment by rigelk** [comment]
@s8321414 please open issues specific to the joinpeertube site on its dedicated tracker: https://framagit.org/framasoft/peertube/joinpeertube/issues

**Comment by s8321414** [comment]
Well...

**Comment by Chocobozzz** [comment]
Thanks for your work @s8321414! Sorry for the different bug tracker, but it's not the same developers that work on joinpeertube. I'll send them the info.

**Comment by Chocobozzz** [comment]
Done: https://trad.framasoft.org/iteration/view/join-peertube/master ;)

**Comment by s8321414** [comment]
Thank you!
