### ISSUE TITLE
List all instance video on https://myinstance/accounts/peertube/videos

### ISSUE THREAD

**Issue by JohnXLivingston** [Chocobozzz/PeerTube#893]
You can subscribe to the account @peertube@myinstance if order to be noticed for all new vidéos (for example from your mastodon account).
Very nice. But in mastodon, the link "view full profile" redirects to https://myinstance/accounts/peertube/videos. And this page doesn't show any vidéo. It would be very nice to redirect to the "local vidéos" page.

**Comment by Chocobozzz** [comment]
Another possibility is to redirect on the *Local Videos* page.

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/1a03bea0c42fa1064ce4770157b4fd2e3edd5565
