### ISSUE TITLE
Is peertube scalable?

### ISSUE THREAD

**Issue by andreaspeters** [Chocobozzz/PeerTube#894]
Hi, 

just one small question. Is peertube scalable? Means, can I just start one more (as example) container and use a LB at front of it or will it break videos and the database?

Best regards,
Andreas

**Comment by Chocobozzz** [comment]
No, PeerTube is not designed to have multiple nodes behind a LB. You should create another instance instead.

**Comment by andreaspeters** [comment]
ok, thanks for the answer @Chocobozzz and have a nice day.
