### ISSUE TITLE
Instance suspension

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#896]
A big tool I see missing in the "Better Moderation Tools" issue is suspension of whole instances. If an instance is incompatible with the COC of yours and/or doesn't deal with abuse well enough, you'd need to constantly keep watch over it's interactions (which becomes impossible fast).

Unfollowing doesn't do more than prevent the videos from being listed. The instance can still follow and comment on yours, including ones that aren't PeerTube. There's nothing to stop a raid on the comments or spam on a large scale.

**Comment by Chocobozzz** [comment]
Implemented muting in https://github.com/Chocobozzz/PeerTube/commit/b44164bb567fe7c9f65f1ac2908d44990a8ccc8e & https://github.com/Chocobozzz/PeerTube/commit/65b21c961c69c4a63c7c0c34be3d6d034a1176c7
