### ISSUE TITLE
Create a report view

### ISSUE THREAD

**Issue by rigelk** [Chocobozzz/PeerTube#897]
Right now an abuse report is just a line in a list. It's arguably not enough to:

- [x] ~keep track of the actions taken for that report~ Add moderation comment to abuse
- [x] ~keep track of the actions already taken relative to the incriminated user~ Add moderation comment to abuse
- [x] be able to stay within the report to view the reported part of the content
- [x] be able take action

That would need more thought, but we could certainly take inspiration from existing [reporting tools in other federated (or not) systems](https://app.presentator.io/fr/swbSZPC8).

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/efc9e8450a8bbeeef9cd18e3ad6037abc0f815c3
