### ISSUE TITLE
Comment approbation queue – Detect words

### ISSUE THREAD

**Issue by FirePowi** [Chocobozzz/PeerTube#898]
As an anti-harassment tool, I imagine a tool to detect some “bad” words to send to "approbation queue" (See #718 )
Exemple : 

Jane post a video called "VLOG – Vacations far away from internet"
A twitter guy, we'll call him "Dissident Lizard" make a call for harassment on his Twitter.

Many comments claim : "You have been lizarded" – As a response, we may add "lizard*" as "bad" word so that every comment on the platform OR on Jane videos are put in "approbation queue".

That fewture can be used by Jane themself of by Admin/Modo of the instance.
If Jane use it, only comments on Jane's videos are concerned.
If an Admin/Modo use it, they can choose if only Jane's videos are concerned or if everyone's videos are concerned.

Improve it : 
Possibility to impact comments that were post since [Date (JJ-MM-AA HH:MM)]
Possibility to choose between Approbation queue and direct deletion

I'm not sure I'm being understood (I'm really tired and my english go down), but if you have questions. Be free to ask.

**Comment by Bugsbane** [comment]
Might I suggest that admins be able to add a key for Akismet in the back end, and if so we run all comments through that?

Akismet is the seasoned, battle tested tool developed by the WordPress team (automatic) to fight comment spam on WordPress instances across the web. No, we shouldn't offer this as the *only* protection, but for a lot of people this would provide high grade protection for very little coding effort.

**Comment by Chocobozzz** [comment]
It could be interesting https://github.com/cedx/akismet.js

**Comment by Chocobozzz** [comment]
We designed the plugin system to allow this kind of feature. See https://docs.joinpeertube.org/#/contribute-plugins?id=spammoderation-plugin
