### ISSUE TITLE
Prioritize transcode jobs

### ISSUE THREAD

**Issue by itguyeric** [Chocobozzz/PeerTube#899]
Requested Functionality:
Ability set a priority for transcoding jobs

Current Condition:
All videos are trans-coded on a first-in-first-out basis.

Workaround:
For now, I am uploading the new content by hand and unchecking the transcode before publishing option, however, this doesn't provide the best experience for people watching the latest content.

Use Case:
I am managing the PeerTube instance for Jupiter Broadcasting, a Linux-centric podcasting company. We have 10 years of backlog shows we are importing into our server. However, every week we produce 6 or more new shows.

**Comment by Chocobozzz** [comment]
Merging this discussion in https://github.com/Chocobozzz/PeerTube/issues/1192
