### ISSUE TITLE
Incomplete translation - remove/delete video dialog

### ISSUE THREAD

**Issue by Vertux** [Chocobozzz/PeerTube#90]
If you delete a video the dialog box shows an incomplete/false translation (develop branch)

![bildschirmfoto 2017-09-09 um 16 16 18](https://user-images.githubusercontent.com/10457918/30241204-06598e50-957f-11e7-8fd0-8628c61b115d.png)

**EDIT:** I have find the same issue in the admin interface under "List friends" --> "Make friends":

![bildschirmfoto 2017-09-10 um 08 48 55](https://user-images.githubusercontent.com/10457918/30246844-55453696-9605-11e7-8f34-6cd587e86aeb.png)

**Comment by Chocobozzz** [comment]
Oop's

![http://lutim.cpy.re/aS90eNqP.jpg](http://lutim.cpy.re/aS90eNqP.jpg)

**Comment by Vertux** [comment]
Cute picture 😊

**Comment by Chocobozzz** [comment]
Fixed: https://github.com/Chocobozzz/PeerTube/commit/6599f096d5a26f2cc9624359d92cc501ec189586
