### ISSUE TITLE
Show quota occupation to the user

### ISSUE THREAD

**Issue by 22decembre** [Chocobozzz/PeerTube#900]
The users table in admin view should present the current space occupied by each users videos.

<strike>And each user should also see in their profile the space they use vs the space they are allocated.</strike>

**Comment by Chocobozzz** [comment]
> And each user should also see in their profile the space they use vs the space they are allocated.

It is: 
![screen_2018-08-08-09 46 39](https://user-images.githubusercontent.com/5180488/43823639-03f64f3c-9af0-11e8-8f09-864d0a487d92.png)

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/a76138ff56ad3ad2df926f59578a06b22fb1f93c
