### ISSUE TITLE
Don't have 'the right MANAGE_USERS to access to /token'

### ISSUE THREAD

**Issue by benjbrandall** [Chocobozzz/PeerTube#903]
I'm trying to authenticate my PeerTube account with the API through Ruby. I followed the documentation's format for the authentication:
 
```
    def authenticate
        url = "#{@domain}/api/v1/users/token"
        response = HTTParty.get(url, headers: { 'Authorization' => "Bearer #{@bearer_token}" })
        JSON.parse(response.body)
    end
```

Getting:

`{"error"=>"User username23423 does not have right MANAGE_USERS to access to /token."}`

**Comment by Chocobozzz** [comment]
Hello,

I don't understand you seem to already have the `bearer_token` so why do you `GET` `/api/v1/users/token`? `GET` on this route will match `/api/v1/users` and will list users on the instance, but your user does not have the right to do this.

**Comment by benjbrandall** [comment]
My mistake! Thanks. That's helped.
