### ISSUE TITLE
reset-password accepts different passwords

### ISSUE THREAD

**Issue by joshmorel** [Chocobozzz/PeerTube#906]
I would say this is lower priority as everything will still "work" but in doing dev work I noticed the reset password form accepts different passwords (and uses the first one). Haven't dug into the root cause but whatever `my-account-settings.my-account-change-password` is doing is the right way as that works as expected. 
 

* **PeerTube version or URL:** v1.0.0-beta.9
* **Browser name/version:** Chrome 68.0.3440.75
* **NodeJS version:** n/a (front-end Issue)

* **What is the expected behaviour?** If passwords entered in reset-password are different you will be shown an error and prevented from submitting
* **What do you see instead?** With different passwords entered, there is no error, the first is accepted

**Comment by rigelk** [comment]
Could it be that `[disabled]="!form.valid && isConfirmedPasswordValid()">` should be `[disabled]="!form.valid || !isConfirmedPasswordValid()">` at [@app/reset-password/reset-password.component.html#L29](https://github.com/Chocobozzz/PeerTube/blob/5e319fb7898fd0482c399cc3ae9dcfc20d274a58/client/src/app/reset-password/reset-password.component.html#L29)?

**Comment by Chocobozzz** [comment]
@rigelk :+1:

**Comment by LeoMouyna** [comment]
Why does reset password and change password logics are as much different ? Maybe reset password method could check if password and password-confirm are the same as change password does.

**Comment by joshmorel** [comment]
@LeoMouyna I agree. This seems like a good candidate for reusable component. The form is the same except for a few labels and the api route.

If no one else wants this I'll take it on. I'm chipping away at the account verification feature but the many involved pieces makes it is slow going for a first code contribution to this project. It would be nice get an easy win! I'll wait to hear from others before doing anything.

**Comment by joshmorel** [comment]
After some work on this - I start to see why not bothering with a reusable component may make sense here. I'm completely new to Angular and thought this would be a good first place to learn about it. However, inter-component communication with reusable component is complicated (not just for ANgular - you'd have similar challenge with React, Vue) and breaking the "not repeat yourself" rule IMHO is sensible here as this kind of logic is only used at max in these two places.

I'm going thinking I'll just apply the simple fix and move back into a more value added work. Unless @rigelk  you have a different idea?

**Comment by rigelk** [comment]
@joshmorel I'm not knowledgeable enough to have a definite opinion on this. Repeating oneself is acceptable if that simplifies things, and the quickfix seems simple enough

**Comment by Chocobozzz** [comment]
Fixed by @joshmorel in https://github.com/Chocobozzz/PeerTube/commit/970df082c03250604c9be087f74a9a70974507d0
