### ISSUE TITLE
unable to upload subtitles: "This caption file is not supported or too large"

### ISSUE THREAD

**Issue by theoden8** [Chocobozzz/PeerTube#907]
The website does not allow me to upload subtitles with an error message "file is not supported or too large".

* **Example**: [test.zip](https://github.com/Chocobozzz/PeerTube/files/2260301/test.zip)
* **Peertube version or URL**: [peertube.social](https://peertube.social)
* **Browser name/version**: Google chrome canary Version 70.0.3508.0 (Official Build) canary (64-bit)
* **Browser name/version**: Firefox developer edition Version 62.0b8 (64-bit)
* **What is expected behavior**: the subtitles should be approved.
* **What do you see instead**: an error:

```
Error
This caption file is not supported or too large. Please, make sure it is of the following type : .vtt, .srt
```

**Console log** in chrome: [pastebin](https://pastebin.com/raw/uHUjYPb7)

**Comment by rigelk** [comment]
I've already seen this kind of error report on IRC.

**Comment by Chocobozzz** [comment]
@theoden8 Please, copy the parameters of the `PUT` request on the `captions/:id` endpoint (network tab in the browser console). Example:

```
-----------------------------30940570513630115141903378002
Content-Disposition: form-data; name="captionfile"; filename="subtitle.vtt"
Content-Type: text/vtt

WEBVTT FILE

1
00:00:00.000 --> 00:00:10.000
<font size="20">subtitle</font>


-----------------------------30940570513630115141903378002--
```

**Comment by theoden8** [comment]
@Chocobozzz this is the request data:

```
------WebKitFormBoundaryEGtv8p64EsaY25iA
Content-Disposition: form-data; name="captionfile"; filename="subtitle.vtt"
Content-Type: application/octet-stream


------WebKitFormBoundaryEGtv8p64EsaY25iA--
```

**Comment by Chocobozzz** [comment]
@theoden8 What is your OS?

**Comment by theoden8** [comment]
@Chocobozzz Mac OS 10.12.6

**Comment by Chocobozzz** [comment]
Thanks, should be fixed https://github.com/Chocobozzz/PeerTube/commit/3d52b300ea79bec21f090e2447c4808307078618

**Comment by lstamellos** [comment]
I just encountered the same issue on PeerTube 1.4.1

Parameters of the PUT request:

`-----------------------------43127946614799078531291567768
Content-Disposition: form-data; name="captionfile"; filename="English-1.srt"
Content-Type: text/plain

﻿1
00:00:53,840 --> 00:00:56,910
Subtitle

-----------------------------43127946614799078531291567768--`

**Comment by Chocobozzz** [comment]
@lstamellos Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/2f26030dd2da121fb1d1701600e93f689141df40
