### ISSUE TITLE
File capacity error

### ISSUE THREAD

**Issue by zzoozzo1122** [Chocobozzz/PeerTube#908]
=
* **PeerTube version or URL:** PeerTube v1.0.0-beta.10.pre.3 
* **Browser name/version:** Chrome browser, last ver
* **NodeJS version:** 8.0

* **What is the expected behaviour?**
* **What do you see instead?**

File capacity error

Thank you for your response regarding the error. It went well.

It will stay sealed for less than 5 GB
Video files larger than 5 GB,6GB,7GB,8GB  (registered)
Only web seeds are connected (HTTP).

**Comment by Chocobozzz** [comment]
You need to update your [nginx configuration](https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube#L87)
