### ISSUE TITLE
File capacity error#2

### ISSUE THREAD

**Issue by zzoozzo1122** [Chocobozzz/PeerTube#909]
PeerTube version or URL: PeerTube v1.0.0-beta.10.pre.3

Browser name/version: Chrome browser, last ver

NodeJS version: 8.0

What is the expected behaviour?

What do you see instead?

File capacity error

Thank you for your response regarding the error. It went well.

It will stay sealed for less than 5 GB
Video files larger than 5 GB,6GB,7GB,8GB (registered)
Only web seeds are connected (HTTP).
----------------------------------------------------------------------------------------------------
 # Hard limit, PeerTube does not support videos > 8GB
    client_max_body_size 8G;
    proxy_connect_timeout       600;
    proxy_send_timeout          600;
    proxy_read_timeout          600;
    send_timeout                600;
  }

It is the same option.
It works.
However, it works as a web seed.

-------------------------------------------------------------------------------------------
You install the same version on different servers.
I uploaded more than 5.1GB
The results are the same. They are kept only in Web seeds.
There seems to be a problem.

**Comment by Chocobozzz** [comment]
Please, comment your previous issue instead of creating a new one. And I don't really understand what is your problem?

**Comment by zzoozzo1122** [comment]
The installation of the program was normal.
MP4 files that are less than 4GB will also operate normally.
However, other MP4 files are operated by a web seed (HTTP).

Sample address 

1.Files of less than 4 GB (peer wetorrent)
https://peer.vimax88.info/videos/watch/e76ffd79-93ab-458b-bf83-df278af57b53

2  .5GB 1080P (web seed)
https://peer.vimax88.info/videos/watch/ace068c9-f6d0-4723-b665-5a7a49e84ebe

3. 4.4GB-720P-60FPS (web seed)
https://peer.vimax88.info/videos/watch/a0732c40-3ac3-4a62-8189-808294bded7d


Why does it work as a web sheet if I upload a file that has more than 5 GB?
I set 8GB in the configuration.
vim /etc/nginx/sites-available/peertube
client_max_body_size 8G;
proxy_connect_timeout       600;
proxy_send_timeout          600;
proxy_read_timeout          600;
send_timeout                600;

**Comment by Chocobozzz** [comment]
Okay I understand now. You need to **enabled** transcoding.
