### ISSUE TITLE
Support Safari

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#91]
It seems there are issues when watching a video.

Originally reported here: https://github.com/Chocobozzz/PeerTube/issues/86#issuecomment-330928619

**Comment by aral** [comment]
<img width="789" alt="screen shot 2017-12-09 at 01 15 08" src="https://user-images.githubusercontent.com/41798/33790214-7e0e1c22-dc7e-11e7-9dd0-09ba387738b8.png">

**Comment by Chocobozzz** [comment]
Original issue: https://github.com/jhiesey/videostream/issues/24

**Comment by Chocobozzz** [comment]
It seems to work now HTTP fallback was implemented: https://github.com/Chocobozzz/PeerTube/commit/bf5685f0b7b1f23a1a3a972fc4d66061f31f9510

**Comment by rigelk** [comment]
Upstream fixed most of the playback issues in https://github.com/jhiesey/mp4-box-encoding/commit/acfbcd748277e4c9315add871474360eefd459b6 so the fallback to HTTP shouldn't be necessary anymore. (original comment [here](https://github.com/jhiesey/videostream/issues/24#issuecomment-382933996))
