### ISSUE TITLE
Yarn error upgrading Peertube from peertube-v1.0.0-beta.9 to peertube-v1.0.0-beta.10

### ISSUE THREAD

**Issue by ParleurA** [Chocobozzz/PeerTube#911]
Hello.

I tried to update peertube to peertube-v1.0.0-beta.10 from peertube-v1.0.0-beta.9.
I still use Debian Jessie.

And the automated install sent me the following message: 

    ~/versions/peertube-v1.0.0-beta.10$ sudo -H -u peertube yarn install --production --pure-lockfile
    yarn install v1.9.2
    [1/5] Validating package.json...
    [2/5] Resolving packages...
    warning Resolution field "@types/bluebird@3.5.21" is incompatible with requested version "@types/bluebird@3.5.18"
    [3/5] Fetching packages...
    info fsevents@1.2.4: The platform "linux" is incompatible with this module.
    info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
    [4/5] Linking dependencies...
    [5/5] Building fresh packages...
    $ cd client && yarn install --pure-lockfile
    yarn install v1.9.2
    [1/4] Resolving packages...
    success Already up-to-date.
    $ npm rebuild node-sass
    Done in 2.13s.
    Done in 8.60s.

And obviously, when I try to restart peertube, I get the following message:

    # systemctl restart peertube && sudo journalctl -fu peertube
    Warning: Unit file of peertube.service changed on disk, 'systemctl daemon-reload' recommended.
    -- Logs begin at dim. 2018-08-05 12:34:42 CEST. --
    août 07 20:27:34 example.tld systemd[1]: peertube.service: main process exited, code=exited, status=1/FAILURE
    août 07 20:27:34 example.tld systemd[1]: Unit peertube.service entered failed state.
    août 07 20:27:34 example.tld systemd[1]: peertube.service holdoff time over, scheduling restart.
    août 07 20:27:34 example.tld systemd[1]: Stopping PeerTube daemon...
    août 07 20:27:34 example.tld systemd[1]: Starting PeerTube daemon...
    août 07 20:27:34 example.tld systemd[1]: peertube.service start request repeated too quickly, refusing to start.
    août 07 20:27:34 example.tld systemd[1]: Failed to start PeerTube daemon.
    août 07 20:27:34 example.tld systemd[1]: Unit peertube.service entered failed state.
    août 07 20:40:20 example.tld systemd[1]: Starting PeerTube daemon...
    août 07 20:40:20 example.tld systemd[1]: Started PeerTube daemon.
    août 07 20:40:21 example.tld peertube[23651]: > peertube@1.0.0-beta.10 start /var/www/peertube/versions/peertube-v1.0.0-beta.10
    août 07 20:40:21 example.tld peertube[23651]: > node dist/server
    août 07 20:40:25 example.tld peertube[23651]: [peertube.example.tld:443] 2018-08-07 20:40:25.208 info: Database peertube_prod is ready.
    août 07 20:40:25 example.tld peertube[23651]: [peertube.example.tld:443] 2018-08-07 20:40:25.431 info: Using example.tld:465 as SMTP server.
    août 07 20:40:25 example.tld peertube[23651]: [peertube.example.tld:443] 2018-08-07 20:40:25.438 info: Testing SMTP server...
    août 07 20:40:25 example.tld peertube[23651]: [peertube.example.tld:443] 2018-08-07 20:40:25.521 info: Secure connection established to 123.123.123.123:465 {
    août 07 20:40:25 example.tld peertube[23651]: "component": "smtp-connection",
    août 07 20:40:25 example.tld peertube[23651]: "sid": "tEXejMkZe64",
    août 07 20:40:25 example.tld peertube[23651]: "tnx": "network",
    août 07 20:40:25 example.tld peertube[23651]: "localAddress": "123.123.123.123",
    août 07 20:40:25 example.tld peertube[23651]: "localPort": 35752,
    août 07 20:40:25 example.tld peertube[23651]: "remoteAddress": "123.123.123.123",
    août 07 20:40:25 example.tld peertube[23651]: "remotePort": 465
    août 07 20:40:25 example.tld peertube[23651]: }
    août 07 20:40:25 example.tld peertube[23651]: [peertube.example.tld:443] 2018-08-07 20:40:25.570 info: User "peertube_admin" authenticated {
    août 07 20:40:25 example.tld peertube[23651]: "component": "smtp-connection",
    août 07 20:40:25 example.tld peertube[23651]: "sid": "tEXejMkZe64",
    août 07 20:40:25 example.tld peertube[23651]: "tnx": "smtp",
    août 07 20:40:25 example.tld peertube[23651]: "username": "peertube_admin",
    août 07 20:40:25 example.tld peertube[23651]: "action": "authenticated",
    août 07 20:40:25 example.tld peertube[23651]: "method": "PLAIN"
    août 07 20:40:25 example.tld peertube[23651]: }
    août 07 20:40:25 example.tld peertube[23651]: [peertube.example.tld:443] 2018-08-07 20:40:25.572 info: Successfully connected to SMTP server.
    août 07 20:40:25 example.tld peertube[23651]: [peertube.example.tld:443] 2018-08-07 20:40:25.602 info: Server listening on 127.0.0.1:8001
    août 07 20:40:25 example.tld peertube[23651]: [peertube.example.tld:443] 2018-08-07 20:40:25.602 info: Web server: https://peertube.example.tld
    août 07 20:40:25 example.tld peertube[23651]: [peertube.example.tld:443] 2018-08-07 20:40:25.611 info: Connection closed
    août 07 20:40:25 example.tld peertube[23651]: [peertube.example.tld:443] 2018-08-07 20:40:25.624 error: Error in job queue activitypub-http-broadcast. {
    août 07 20:40:25 example.tld peertube[23651]: "err": {
    août 07 20:40:25 example.tld peertube[23651]: "stack": "Error: Redis version needs to be greater than 2.8.18. Current: 2.8.17\n    at /var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/bull/lib/queue.js:179:13\n    at tryCatcher (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/bluebird/js/release/promise.js:693:18)\n    at Async._drainQueue (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/var/www/peertube/versions/peertube-v1.0.0-beta.10/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:810:20)\n    at tryOnImmediate (timers.js:768:5)\n    at processImmediate [as _immediateCallback] (timers.js:745:5)",
    août 07 20:40:25 example.tld peertube[23651]: "message": "Redis version needs to be greater than 2.8.18. Current: 2.8.17"
    août 07 20:40:25 example.tld peertube[23651]: }
    août 07 20:40:25 example.tld peertube[23651]: }
    août 07 20:40:25 example.tld peertube[23651]: npm ERR! code ELIFECYCLE
    août 07 20:40:25 example.tld peertube[23651]: npm ERR! errno 255
    août 07 20:40:25 example.tld peertube[23651]: npm ERR! peertube@1.0.0-beta.10 start: `node dist/server`
    août 07 20:40:25 example.tld peertube[23651]: npm ERR! Exit status 255
    août 07 20:40:25 example.tld peertube[23651]: npm ERR!
    août 07 20:40:25 example.tld peertube[23651]: npm ERR! Failed at the peertube@1.0.0-beta.10 start script.
    août 07 20:40:25 example.tld peertube[23651]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    août 07 20:40:25 example.tld peertube[23651]: npm ERR! A complete log of this run can be found in:
    août 07 20:40:25 example.tld peertube[23651]: npm ERR!     /var/www/peertube/.npm/_logs/2018-08-07T18_40_25_653Z-debug.log
    août 07 20:40:25 example.tld systemd[1]: peertube.service: main process exited, code=exited, status=255/n/a
    août 07 20:40:25 example.tld systemd[1]: Unit peertube.service entered failed state.
    août 07 20:40:25 example.tld systemd[1]: peertube.service holdoff time over, scheduling restart.

Any idea how I can solve that?

**Comment by Chocobozzz** [comment]
Oup's, sorry about that. I updated the README and breaking changes section: https://github.com/Chocobozzz/PeerTube/commit/47c951b70b2303cb6111031c5db4bb65a36dd62f
