### ISSUE TITLE
follow issue with peertube-v1.0.0-beta.10

### ISSUE THREAD

**Issue by shiyoi** [Chocobozzz/PeerTube#916]
I installed two test environments, www.whatcn.com and node1.whatcn.com.cn, both in the local network, and when I performed the "follow node1.whatcn.com.cn" operation on www.whatcn.com, the following page could see the following results, but peertube.example.com.error.log show wrong and could not see videos on node1.whatcn.com.cn. The peertube.example.com.error.log are as follows:

2018/08/09 14:49:15 [error] 1811#1811: *1 connect() failed (111: Connection refu
sed) while connecting to upstream, client: 200.1.1.153, server: www.whatcn.com,
request: "GET /api/v1/oauth-clients/local HTTP/2.0", upstream: "http://[::1]:900
0/api/v1/oauth-clients/local", host: "www.whatcn.com", referrer: "https://www.wh
atcn.com/"
2018/08/09 14:49:53 [error] 1811#1811: *1 connect() failed (111: Connection refu
sed) while connecting to upstream, client: 200.1.1.153, server: www.whatcn.com,
request: "GET /api/v1/server/following?start=0&count=10&sort=createdAt HTTP/2.0"
, upstream: "http://[::1]:9000/api/v1/server/following?start=0&count=10&sort=cre
atedAt", host: "www.whatcn.com", referrer: "https://www.whatcn.com/admin/follows
/following-list"

config files are as follows:

[peertube.txt](https://github.com/Chocobozzz/PeerTube/files/2274869/peertube.txt)
[production.yaml.txt](https://github.com/Chocobozzz/PeerTube/files/2274870/production.yaml.txt)

**Comment by Chocobozzz** [comment]
I would need the peertube logs too (`storage/logs` directory).

**Comment by shiyoi** [comment]
From: Chocobozzz
Date: 2018-08-10 00:03
To: Chocobozzz/PeerTube
CC: shiyoi; Author
Subject: Re: [Chocobozzz/PeerTube] follow issue with peertube-v1.0.0-beta.10(#916)
I would need the peertube logs too (storage/logs directory).
