### ISSUE TITLE
Is it possible for PeerTube to remain functional even when users (for privacy & security reasons) disable JavaScript in their browsers?

### ISSUE THREAD

**Issue by Zig-03** [Chocobozzz/PeerTube#917]
**Note:** I'm not talking about 100% functional, since this is almost impossible, but at least to be able to watch videos.

**Comment by Chocobozzz** [comment]
No sorry, but you can use the rest api combined with a torrent application to watch peertube videos for example.

**Comment by Extarys** [comment]
@Zig-03 That is a good question since many people run NoScript for example. I hope this will be addressed eventually - At least watching videos :D
