### ISSUE TITLE
K-Meleon support?

### ISSUE THREAD

**Issue by Wikiwide** [Chocobozzz/PeerTube#919]
* **PeerTube version or URL:**
https://peertube.social/videos/watch/78a478af-355a-4191-802a-7b11f40bf141
* **Browser name/version:**
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0 K-Meleon/75.1
* **NodeJS version:**

* **What is the expected behaviour?**
Watch the video.
* **What do you see instead?**
We are sorry but it seems that PeerTube is not compatible with your web browser.
Please try with the latest version of Mozilla Firefox.
If you think this is a mistake, do not hesitate to report it.

* **Browser console log if useful (Gist/Pastebin...):**
Warning: The site specified an invalid Strict-Transport-Security header.
Source file: https://peertube.social/videos/watch/78a478af-355a-4191-802a-7b11f40bf141

Warning: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
Source file: https://peertube.social/client/en_US/polyfills.4681271c558dac50ac83.js
Line: 1

* **Server log if useful (Gist/Pastebin...):**

**Comment by Chocobozzz** [comment]
Like @tcitworld said, the web browser is too old.
