### ISSUE TITLE
Error status 210 CHROOT

### ISSUE THREAD

**Issue by yopethop** [Chocobozzz/PeerTube#922]
Bonjour,

J'ai installer sur un nouveau vps, une instance de peertube, cette fois-ci il me sort l'erreur suivante : 
peertube.service: Failed at step CHROOT spawning /usr/bin/npm: No such file or directory

J'ai installer peertube dans un autre dossier, home/peertube/ c'est peut-être ça qui pose soucis.
Merci pour votre aide.

Cordialement

Good morning,

I have installed on a new vps, a peertube instance, this time it gives me the following error : 
peertube.service: Failed at step CHROOT spawning /usr/bin/npm: No such file or directory

I installed peertube in another folder, home/peertube/ maybe that's the problem.
Thank you for your help.

Sincerely

**Comment by Chocobozzz** [comment]
Did you install nodejs? What is your OS? What is the output of `npm version`?

**Comment by yopethop** [comment]
Yes nodejs installed with this link : https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/dependencies.md

os : debian 9.5

![npm](https://user-images.githubusercontent.com/41811171/44115585-977f3da4-a00e-11e8-902d-57e574ffe320.png)

**Comment by Chocobozzz** [comment]
Please copy/paste the systemd service

**Comment by yopethop** [comment]
sorry for the late response.

Aug 20 20:09:33 vps systemd[1]: Started PeerTube daemon.
Aug 20 20:09:33 vps systemd[7240]: peertube.service: Failed at step CHROOT spawning /usr/bin/npm: No such file or directory
Aug 20 20:09:33 vps systemd[1]: peertube.service: Main process exited, code=exited, status=210/CHROOT
Aug 20 20:09:33 vps systemd[1]: peertube.service: Unit entered failed state.
Aug 20 20:09:33 vps systemd[1]: peertube.service: Failed with result 'exit-code'.
Aug 20 20:09:33 vps systemd[1]: peertube.service: Service hold-off time over, scheduling restart.
Aug 20 20:09:33 vps systemd[1]: Stopped PeerTube daemon.
Aug 20 20:09:33 vps systemd[1]: peertube.service: Start request repeated too quickly.
Aug 20 20:09:33 vps systemd[1]: Failed to start PeerTube daemon.
Aug 20 20:09:33 vps systemd[1]: peertube.service: Unit entered failed state.
Aug 20 20:09:33 vps systemd[1]: peertube.service: Failed with result 'exit-code'.

**Comment by Chocobozzz** [comment]
@yopethop I mean the systemd service file, not the logs :)

**Comment by yopethop** [comment]
Sorry for the question but where is this file? In the file where I have the peertube installation? Or is it in the /etc/systemd folder, I'm trying to understand :)

**Comment by rigelk** [comment]
@yopethop you can find the path to the systemd unit via `systemctl show -p FragmentPath peertube`

**Comment by Chocobozzz** [comment]
@yopethop Did you follow the production guide? https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#systemd

**Comment by yopethop** [comment]
je viens de voir mon erreur :)

En effet je n'avais pas fait attention à ce fichier mais en changeant le dossier de peertube dans mon cas /home/peertube/, il fallait faire le changement dans ce fichier.

Merci pour ton info rigelk et toi aussi Chocobozzz :)
Et merci pour votre travail sur Peertube ^^

I just saw my mistake:)

Indeed I had not paid attention to this file but by changing the peertube folder in my case /home/peertube/, it was necessary to make the change in this file.

Thanks for your rigelk info and you too Chocobozzz :)
And thank you for your work on Peertube ^^
