### ISSUE TITLE
how can i get the token when i use the API to upload video

### ISSUE THREAD

**Issue by ZTzha** [Chocobozzz/PeerTube#924]
* **PeerTube version or URL:**
* **Browser name/version:**
* **NodeJS version:**

* **What is the expected behaviour?**
* **What do you see instead?**

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

**Comment by rigelk** [comment]
Hi @ZTzha - you can find that information in the dedicated section of the [README](https://github.com/Chocobozzz/PeerTube#api-rest-documentation) as well as examples [in the wiki](https://github.com/Chocobozzz/PeerTube/wiki).
