### ISSUE TITLE
Display videos on upnp dlna renderer

### ISSUE THREAD

**Issue by vtexier** [Chocobozzz/PeerTube#93]
Hi,
It will be very cool to watch videos on TV via upnp dlna protocol sending the streaming URL to an upnp renderer. 

It can be a TV or a media center like Kodi...

Peertube on a big screen !

**Comment by Chocobozzz** [comment]
This can only be implemented with a native application no?

**Comment by vtexier** [comment]
W3C has a spec for this, but browsers don't get it yet except Opera and Chrome :  https://stackoverflow.com/questions/29227445/upnp-discovery-description-inside-javascript

But I found an implementation using sockets.

A nodejs command line tool :  https://github.com/xat/dlnacast
based on this : https://github.com/thibauts/node-upnp-mediarenderer-client

An angular example : 

https://github.com/CasaFan/Media-Control-Application

Searching "upnp" on github filtered by javascript language, you might find more.

I've done myself a python implementation so I can help on upnp aspect...

**Comment by Chocobozzz** [comment]
Since we are using classic torrents, I think you can use [WebTorrent app](https://github.com/webtorrent/webtorrent-desktop/issues/186) to have a PeerTube video on a big screen :)
