### ISSUE TITLE
what's the mean of this error??????????

### ISSUE THREAD

**Issue by liangmanxing** [Chocobozzz/PeerTube#931]
- [ ] 
![peertube-error](https://user-images.githubusercontent.com/21138879/44306066-a528ec80-a3b9-11e8-82a0-314ec39acba4.jpg)

**Comment by Chocobozzz** [comment]
It means you did not correctly configured PeerTube, in particular the [webserver section](https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L8)!!!!!!!!!!
