### ISSUE TITLE
Peertube behind nginx reverse proxy and under a subdirectory

### ISSUE THREAD

**Issue by jaarandaz** [Chocobozzz/PeerTube#933]
Hello!
I'm trying to set up an instance behind an nginx reverse proxy and under a subdirectory:

mydomain.com/peertube -> peertubeinstance:9000

My problem is that 'peertubeinstance' content is not considering this subdirectory, so it is trying to get mydomain.com/client'. Is there a variable to set up this scenario (so it returns urls to 'mydomain.com/peertube/client') or this is a enhancement?

Thank you!

**Comment by rigelk** [comment]
I don't feel this is an enhancement, considered this has already been discussed in https://github.com/tootsuite/mastodon/issues/5089 and we are basically in the same scenario, which per the WebFinger spec fobids it.

**Comment by jaarandaz** [comment]
Oh, I didn't know about that. Well, I can go with subdomains then. Thanks for your response!
