### ISSUE TITLE
Implement oEmbed protocol

### ISSUE THREAD

**Issue by Chocobozzz** [Chocobozzz/PeerTube#94]
Spec: https://oembed.com/

**Comment by Chocobozzz** [comment]
Implemented: https://github.com/Chocobozzz/PeerTube/commit/d8755eed1e452d2efbfc983af0e9d228d152bf6b

But most consumers use whitelist to accept or not HTML from OEmbed servers (for security reasons), so this does not really work. Since PeerTube can be installed under any domain, I don't think there is an easy way to have the player embedded on social networks (even on Diaspora, Mastodon...).

**Comment by tcitworld** [comment]
There's the OpenGraph `og:video` metadata that's missing and may be required to embeed videos on some websites.

**Comment by Chocobozzz** [comment]
Thanks @tcitworld -> https://github.com/Chocobozzz/PeerTube/commit/7ff7802aa0ee6dd4c90f3e1cef1993170e7807f2

**Comment by PeterAlfonsLoch** [comment]
The og:video tag is missing and should have a url to the file, not the embed url.

If you want to use the og:video:url and og:video:secure_url then it's the same thing it should be a url to the file and not the embed link.

Example: <meta property="og:video" content="http://example.com/bond/trailer.swf" />
source: https://ogp.me/#metadata

**Comment by Chocobozzz** [comment]
@PeterAlfonsLoch It's what dailymotion, youtube or vimeo already do. I don't say they are doing it correctly, but we need to keep consistency with existing video platforms.
