### ISSUE TITLE
Video transcoding jobs isn't printing

### ISSUE THREAD

**Issue by Jorropo** [Chocobozzz/PeerTube#943]
* **PeerTube version or URL:**
V1 beta 11 [peertube.jorropo.ovh](https://peertube.jorropo.ovh/)
* **NodeJS version:**
v8.11.4

* **What is the expected behaviour?**
With admin account in Administration > Jobs list, you should see pending and current jobs (like transcoding.)
* **What do you see instead?**
I have 2 video to trans code (transcoding is running for 1), but I don't see any job.

* **Browser console log if useful (Gist/Pastebin...):**
Nothings here
* **Server log if useful (Gist/Pastebin...):**
```json
{"message":"178.208.9.100 - - [22/Aug/2018:09:43:28 +0000] \"GET /api/v1/jobs/delayed?start=0&count=10&sort=createdAt HTTP/1.0\" 304 - \"https://peertube.jorropo.ovh/admin/jobs/list\" \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0\"\n","level":"info","label":"peertube.jorropo.ovh:443","timestamp":"2018-08-22T09:43:28.104Z"}
```

**Comment by Chocobozzz** [comment]
You need to filter on `active` jobs, not `delayed`
