### ISSUE TITLE
Do not federate unlisted videos

### ISSUE THREAD

**Issue by supermamie** [Chocobozzz/PeerTube#944]
**PeerTube version or URL:**

PeerTube v1.0.0-beta.10 

**Introduction:**

When a video is uploaded, it is always with federation in mind.
It is either private (only the uploader can see it), or federated (public or unlisted).

This is totally intended as PeerTube is a federated video tool.

**What is the behaviour I would like to have?**

But in some case, I want to upload a video to stay on my instance and not be federated.

(in my specific case, it is to upload family videos that should remain private and I am not 100% sure I can trust each and every one instance that is following mine)

Ideally, more granular rights could be added, but unlisted and not federated could be nice.

1. People on my instance with the link (unlisted, not federated)
2. People on my instance (public, not federated)
3. People with an account on my instance (I do not think it is possible now, see #520 )

* **What do you see instead?**

The normal behaviour of a federated tool :+1:

**Comment by Chocobozzz** [comment]
I don't think we want to add the "federation" notion in the video form. It's too complicated, and most users won't understand it. Let's try to keep things simple: maybe a private video with the ability to set other local account that can see your video would fit your needs. Or maybe https://github.com/Chocobozzz/PeerTube/issues/520

**Comment by supermamie** [comment]
#520 can do, I'll just have to create a "guest" account with no upload capacity and share it for the people I want to share the video to.
The problem is that I will have to create a new account each time I want to upload a new video with a limited audience (my family, at work, some people I talk to over the Internet, etc...)

I know it should be possible to "trust" other servers, but I already have seen some problems like this (between Mastodon and Pleroma I think) where unlisted/private toots became public.

I also know that the fediverse is not made to host private data and I should maybe install PeerTube and another video tool which is not federated instead of wanting to unfederate PeerTube.

I still have a question : why are unlisted videos sent to other servers ?
(I think the answer is "so they will become available to followers", but I follow my account via Mastodon and do not see unlisted video, but I see the number of post which is the exact total of video (public + unlisted))

**Comment by Chocobozzz** [comment]
> I know it should be possible to "trust" other servers

No you're right, you should not trust the federation.

> why are unlisted videos sent to other servers ?

Well :thinking: You make a good point. The only benefit is to share an unlisted video from different instance (`https://peertube.example1.com/videos/uuid` or `https://peertube.example2.com/videos/uuid`) is it really useful?

**Comment by rigelk** [comment]
Doesn't seem useful to me. Users will share the direct URL in all likelihood.

**Comment by Jorropo** [comment]
I think unlisted shared in federation is usefull cause I think an interesting add is an browser extension that replace all link to an peertube instances by your peertube instances, (for simply allow comment, ...) and if some videos start to be not listed by followers that requires to do a request before for verify that the peertube instances have this video

**Comment by supermamie** [comment]
Another 2 cent about this issue : https://glitch-soc.github.io/docs/features/local-only-toots/
In this Mastodon Fork, there is a feature for local only toots.

I totally agree with @Jorropo about comments and I currently see no way of having a video only in one server, and having a way to comment on it from another server.

But if someone want the video to be only on this server, it could be displayed "no comments will be possible from accounts on other servers" ?

**Comment by Lesterpig** [comment]
*For anyone interested about this issue:* currently, public federation outbox list unlisted videos.
To my understanding, this means that everyone able to read JSON can access unlisted videos without restriction, even with manual acceptance enabled. To protect my instance, I removed the [following line](https://github.com/Chocobozzz/PeerTube/blob/v2.1.0/server/models/video/video.ts#L1134) and updated [this one](https://github.com/Chocobozzz/PeerTube/blob/v2.1.0/server/models/video/video.ts#L1814). Seems sufficient, but not 100% sure for now 😉

**Comment by Tak** [comment]
I got here because I'm also interested in using peertube to share stuff like family videos (i.e. moderately privacy-sensitive, but not enough to guard behind a login) by url with non-tech-savvy people.

Is @Lesterpig 's proposed change sufficient to prevent federation of unlisted videos? Would a PR to make this an instance-level setting be accepted?

**Comment by Chocobozzz** [comment]
> Is @Lesterpig 's proposed change sufficient to prevent federation of unlisted videos? 

Yes I think

> Would a PR to make this an instance-level setting be accepted?

Yes it would be interesting (with unit tests :) )

**Comment by Chocobozzz** [comment]
Implemented by @Tak

**Comment by artlog** [comment]
what will happen for already exiting unlisted videos ? Is there a un-federate option ?

**Comment by sebilasse** [comment]
I am asking to reopen this issue as it is a privacy concern to me.
This caused some trouble for ActivityPub Conf, see this thread 
https://mastodon.social/@sl007/104951464627944946
and this
https://mastodon.social/@mastohost/104950285222324034

**Comment by Chocobozzz** [comment]
@sebilasse I created a dedicated issue: https://github.com/Chocobozzz/PeerTube/issues/3218
