### ISSUE TITLE
Video metadata should include created/published dates

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#946]
It would be really useful for video metadata to optionally include not just the date the content was uploaded, but the date it was originally produced or published.

Lots of people are using PeerTube to host archival content, but often I'll open a video and have no idea when it was from. Diligent uploaders could use the description to indicate this, but the current importer script doesn't do this. Without manual intervention, videos imported from YouTube for example have no information about when the content was produced.

It would be really useful to include date fields in the UI, defaulting to the current day. Later on, it would be great to search for archival content according to its production date rather than its upload date.

The metadata used by Archive.org is an inspiration to me, and might provide some other clues about data we may want to start collecting as early as we can.

**Comment by Chocobozzz** [comment]
Some students are working on this issue. :)

**Comment by am97** [comment]
I guess we should discuss the details about the implementation here :

At the moment, according to this [file](https://github.com/Chocobozzz/PeerTube/blob/4293e362af90fd61f22d5b88d926165e970e53db/shared/models/videos/video.model.ts#L40) a video has three dates : 
- `createdAt` 
- `updatedAt`
- `publishedAt`
    - When privacy changes from private to public/unlisted, this field is set to NOW ([more info](https://github.com/Chocobozzz/PeerTube/commit/2922e048de95738b3319054ce0778f873a34a0ee))

We want to add a field `producedAt`, which would be the date when a video was originally produced (e.g. 05/02/1936 for Charlie Chaplin - Modern Times)

**Comment by am97** [comment]
First question: should we add also a `uploadedAt` field? This would be the date when the video was uploaded on another platform, like YouTube. But we may end up having too much dates for a video.

**Comment by am97** [comment]
Second: what would be the right way to display the dates in the web UI? Both side by side? Or should the uploader choose the date to be displayed?

Displaying the dates side by side would be a bit ugly:
![screenshot_2018-10-22](https://user-images.githubusercontent.com/18473412/47303788-2c4a4900-d625-11e8-884e-449795b973cf.png)

**Comment by scanlime** [comment]
BO41, the point of having this in metadata other than description is we can use it as a sort key. I’d like to be able to sort channels and playlists by the original publication date. Otherwise episodes of a series will be out of order if they didn’t all transcode in order.

**Comment by BO41** [comment]
@scanlime ah I see. makes sense. :+1: 
Then @am97 I would add the information at the bottom, to the language and the license.

**Comment by clementbrizard** [comment]
> BO41, the point of having this in metadata other than description is we can use it as a sort key. I’d like to be able to sort channels and playlists by the original publication date. Otherwise episodes of a series will be out of order if they didn’t all transcode in order.

I was just thinking about naming it `originPublishedAt`

**Comment by scanlime** [comment]
I would think in most cases the UI should display the original publication date only

**Comment by clementbrizard** [comment]
> I would think in most cases the UI should display the original publication date only

Indeed on Archive.org given by @scanlime as an inspiration, the original publication date is first, just under the content, and the date of the upload is shown on the bottom right-hand corner, as on this 1980 video : https://archive.org/details/2358ReelWorldStringBand

**Comment by am97** [comment]
If we use the original publication date as the "main" date, we should also set it by default to the current date, otherwise, if the user does not add the original publication date, we would have an empty field.

**Comment by am97** [comment]
So, I propose this:
- Rename `publishedAt` to `publishedOnPeertubeAt`
- Add `originallyPublishedAt` (set to current date if not specified)
- Use `originallyPublishedAt` as the main date in the web UI, and display `publishedOnPeertubeAt` at the bottom. It would look like this: 
![screenshot_2018-10-23 sintel trailer 3](https://user-images.githubusercontent.com/18473412/47364848-8d802400-d6da-11e8-857f-9e5b8a795d6f.png)

@Chocobozzz is this OK for you ?

**Comment by rigelk** [comment]
@am97 Chocobozzz is going to be away for some time (a month?), but I would advise against renaming `publishedAt` to ensure we keep the information compatible with previous versions of PeerTube in the federation.

**Comment by clementbrizard** [comment]
Thank's @rigelk then we can go back to work :+1:

**Comment by ddeenniiss** [comment]
We are setting up an instance and the idea is to import videos from channels (Vimeo, Youtube) .

But we would like to have this "original" date defore the import. This option will be included in the next version? With the possibility of importing with peertube-import-videos.ts ?

**Comment by am97** [comment]
> We are setting up an instance and the idea is to import videos from channels (Vimeo, Youtube) .
> 
> But we would like to have this "original" date defore the import. This option will be included in the next version? With the possibility of importing with peertube-import-videos.ts ?

For the moment we have only implemented this in the Upload page (i.e. manual upload), but it would be great to implement it also in peertube-import-videos.ts

I'll deal with it, but I don't know when it will be ready...

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/pull/1285/commits
