### ISSUE TITLE
Sample nginx config doesn't include gzip

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#948]
I'm not an expert in any of this, please let me know if I've done something wrong... but if this is just an omission, I can write a pull request.

The configuration from the readme's production guide does not include gzip transfer encoding, which afaict needs to be enabled in the server section of the nginx config.

In my instance, I've added this configuration to reduce the bandwidth and time to load the initial javascript bundle, from over a megabyte down to about 300K.

  gzip on;
  gzip_types text/plain text/css text/html application/javascript application/json;
  gzip_vary on;

edit: added gzip_vary

**Comment by Jorropo** [comment]
Excellent idea, could you do a pull request ? :)

**Comment by scanlime** [comment]
https://github.com/Chocobozzz/PeerTube/pull/952
