### ISSUE TITLE
Peertube not working on Pale Moon

### ISSUE THREAD

**Issue by KostasMitropoulos** [Chocobozzz/PeerTube#953]
* **PeerTube version or URL:**https://share.tube/accounts/chriswere
* **Browser name/version:** Palemoon Version: 27.9.4 (64-bit)
* **NodeJS version:** ?

* **What is the expected behaviour?**site appears
* **What do you see instead?** I get the following message

We are sorry but it seems that PeerTube is not compatible with your web browser.

Please try with the latest version of Mozilla Firefox.

If you think this is a mistake, do not hesitate to report it.

* **Browser console log if useful (Gist/Pastebin...):**nil
* **Server log if useful (Gist/Pastebin...):**nil

**Comment by rigelk** [comment]
Hi @KostasMitropoulos ! Please look out for related issues before creating one, as #257 already covers this. You can then detail further your use case there.
