### ISSUE TITLE
Sub-directory AND other port are not supported

### ISSUE THREAD

**Issue by Bumbadawg** [Chocobozzz/PeerTube#954]
* **PeerTube version or URL:*v1.0.0-beta.11*
* **Browser name/version:*Firefox 61.0.1 (64-bit)*
* **NodeJS version:*v8.11.3*

* **What is the expected behaviour?*load tracker, assets*
* **What do you see instead?*wss:// connections are not directed at what nginx proxy passes to*

* **Browser console log if useful (Gist/Pastebin...):*https://gist.github.com/Bumbadawg/7c91eaa73425e41daee04ba2e84e15cf*
* **Server log if useful (Gist/Pastebin...):*no issue logged*

On NGINX, when using another port (let's say 8080), with SSL, 
doing a return 301 to the localhost:9000 app, the app doesn't take in account the referer request. And queries on :443 instead of 8080. Therefore, using another port breaks the websockets.

Also, it seems correlated but when using a sub-directory,
for instance, host:443/peertube (like with Nextcloud sub-dir Nginx configuration), URLs are directed at root / and not /peertube like it should.  In this case i tried to hack around with NGINX sub_filter (blerh) but it failed on parsing .js regexp, causing  slowdowns ofc, and failing to load the UI an error due to the regexps modifications by sub_filter.
E.g. [https://stackoverflow.com/questions/40624588/rewriting-paths-in-css-js-via-nginxs-sub-filter?rq=1](url)

**Comment by rigelk** [comment]
Hi @Bumbadawg ! #933 already covers the subdirectory issue.

**Comment by Chocobozzz** [comment]
> On NGINX, when using another port (let's say 8080), with SSL,
doing a return 301 to the localhost:9000 app, the app doesn't take in account the referer request. And queries on :443 instead of 8080. Therefore, using another port breaks the websockets.

I'm not sure to understand but did you update the peertube configuration according to your nginx port? https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L9

**Comment by Bumbadawg** [comment]
> I'm not sure to understand but did you update the peertube configuration according to your nginx port? 

Indeed @Chocobozzz, the production.yaml misconfiguration was the culprit, my mistake. Thanks for answering so quick.

> Hi @Bumbadawg ! #933 already covers the subdirectory issue.

Yes @rigelk, thanks for the link. Like a Mastodon's user puts it out: 
[https://github.com/tootsuite/mastodon/issues/5089#issuecomment-331840323](url)
> Mastodon forces "/" and nginx without complex sub_filter (reverse engineered) rules is not able to send it back to the correct URI. We need to be able to set, in Mastodon config file, a value which can be added to that "/". Then everything will be working and everyone will be happy.
There is no technical obstructions for that coming from any RFC.

IMHO, it's a simple design flaw in the WebFinger protocol. Which either can be skirted by heavy/wit sub_filter or simply "redesigned" with sub-dir redirection (via a parameter for instance). 
Anyway, to my knowledge, Nextcloud uses a similar /.well-known root API for WebFinger but supports sub-dir reverse proxy configuration.
e.g. [https://docs.nextcloud.com/server/13/admin_manual/installation/nginx.html#nextcloud-in-a-subdir-of-nginx](url)
