### ISSUE TITLE
More meaningful error when uploading a video in a not supported format

### ISSUE THREAD

**Issue by flyingrub** [Chocobozzz/PeerTube#96]
```
There have been validation errors: [ { param: 'videofile', msg: 'Invalid value', value: undefined } ]
```

I was having this error and couldn't find why. But reading FAQ.md I found that Peertube doesn't support .mkv format. We should perhaps tell the user what format we currently support and handle the error to display a meaningful message.

(I am willing to do a PR to fix this issue)

**Comment by Chocobozzz** [comment]
👍
