### ISSUE TITLE
Crash with error EMFILE: too many open files, uv_resident_set_memory

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#960]
* **PeerTube version or URL:** PeerTube v1.0.0-beta.11, https://peertube.social
* **NodeJS version:** v8.11.4

* **Server log if useful (Gist/Pastebin...):**
https://gist.github.com/Nutomic/cd33c192360300ac27630eeb90c8e7c0

Looks like it is this error: https://stackoverflow.com/q/8965606

As a workaround, I've added the following lines to `/etc/security/limits.conf`:
```
* soft nofile 100000
* hard nofile 100000
```

**Comment by rigelk** [comment]
We might want to debug this, as this is often synonym with opening too many sockets (not just regular file descriptors). Otherwise we could also use https://github.com/jprichardson/node-fs-extra to replace the `fs` module which doesn't know how to deal with EMFILE errors.

**Comment by Chocobozzz** [comment]
Weird, @Nutomic could you `# lsof -p peertube_pid` to see if this is peertube that opens too many files?

**Comment by Chocobozzz** [comment]
Okay so closing, feel free to reopen if you have this bug again (with the `lsof` command :) )

**Comment by Nutomic** [comment]
I'm keeping the higher file limit to be safe, so I probably won't.
