### ISSUE TITLE
Deleting imported video doesn't remove the video import backlog entry

### ISSUE THREAD

**Issue by DavidLibeau** [Chocobozzz/PeerTube#961]
* **PeerTube version or URL:** v1.0.0-beta.11
* **NodeJS version:** v8.11.2

* **What is the expected behaviour?**
Delete the video import.
* **What do you see instead?**
![screenshot_2018-08-25 account video imports - videonaute](https://user-images.githubusercontent.com/11574966/44616757-d0965600-a855-11e8-81c3-8e2166342459.png)

**Comment by Chocobozzz** [comment]
The table is bugged if you delete an imported video. I fixed it in `develop`.

This table is more like an import history so they are not deleted, even if the associated video is deleted.
