### ISSUE TITLE
Keep seeding video from an imported torrent (over TCP/UDP)

### ISSUE THREAD

**Issue by mitchtbaum** [Chocobozzz/PeerTube#962]
Video importing using torrent files and then swarming would be a nice feature.  What do you think?

**Comment by rigelk** [comment]
Hi @mitchtbaum ! Please look out for related issues before creating one, as #102 already covered this.

As a result, import from metainfo files and magnet URIs has been implemented as of https://github.com/Chocobozzz/PeerTube/commit/ce33919c24e7402d92d81f3cd8e545df52d98240 & https://github.com/Chocobozzz/PeerTube/commit/990b6a0b0c4fbebc165e5cf7cec8fbc1cbaa6c66

As for swarming features, no issue is currently open for it. I shortly discussed it in the previous issue ([see here](https://github.com/Chocobozzz/PeerTube/issues/102#issuecomment-410322967)):

> just note that importing from a torrent and keeping seeding it are two different things, as keeping sharing poses a few questions/problems:
>
> - keep the original file after transcoding is not something we do yet
> - do we share it over WebRTC when only its transcoded version will be streamed in PeerTube?
> - if we only share alone (without WebRTC only the server will share the file), then why implement it in PeerTube when there are dedicated clients?

**Comment by Chocobozzz** [comment]
I don't think it's a good idea because:
 * It could overload the server (ie importing a torrent with many leechers)
 * It involves privacy issues since we use an external tracker
 * The video or the tracker will probably not be compatible with the web

**Comment by Jorropo** [comment]
Maybe we can seed until reach a specific ratio, this ratio can be chosed in configuration.
So with that admin can chose to not keep seeding (ratio of 0), or repay your debt (ratio of 1), or to help the network with a bigger ratio.

**Comment by Chocobozzz** [comment]
> Maybe we can seed until reach a specific ratio, this ratio can be chosed in configuration.
So with that admin can chose to not keep seeding (ratio of 0), or repay your debt (ratio of 1), or to help the network with a bigger ratio.

This does not resolve point 2 and 3. And peertube is not designed to be a seedbox
