### ISSUE TITLE
Uploading video with import script fails somehow

### ISSUE THREAD

**Issue by mrflos** [Chocobozzz/PeerTube#963]
* **PeerTube version or URL:** 1.0.0-beta.11
* **Browser name/version:** Firefox 61.0.2 (but i was using cli)
* **NodeJS version:** v8.11.4

* **What is the expected behaviour?**
After uploading videos with the import script (a youtube video list), I was expecting seeing the videos in my local videos.

```bash
node dist/server/tools/import-videos.js -u https://video.colibris-outilslibres.org -U <user> -p <pass> -t https://www.youtube.com/playlist?list=PLreXU1pWZlWYJTuefzE2YRbXcvndZEj_9
```

* **What do you see instead?**
The user quota is changed, no errors during the script (if I run the script again, it starts again).
I have an error in my job queue (but this may come from former attempts to import youtube list from UI).
Screenshot 
![image](https://user-images.githubusercontent.com/124845/44619446-38b55e00-a88f-11e8-9b46-bf3462237329.png)

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**

**Comment by Chocobozzz** [comment]
@mrflos Is it the only job that failed? You imported many videos: do the other failed too?

**Comment by Chocobozzz** [comment]
@mrflos This is not the result of `hgetall` command

**Comment by mrflos** [comment]
sorry
```
hgetall bull-video.colibris-outilslibres.org:video-file:102
 1) "opts"
 2) "{\"backoff\":{\"delay\":60000,\"type\":\"exponential\"},\"attempts\":1,\"timeout\":172800000,\"delay\":0,\"timestamp\":1535119631784}"
 3) "timestamp"
 4) "1535119631784"
 5) "priority"
 6) "0"
 7) "delay"
 8) "0"
 9) "data"
10) "{\"videoUUID\":\"6587a7e1-d076-4447-bcb3-fdb521a525f6\",\"isNewVideo\":true}"
11) "processedOn"
12) "1535402763490"
13) "name"
14) "__default__"
```

**Comment by mrflos** [comment]
the id 7 is no more there, will close this issue, waiting for a way to reproduce it, thanks for your help @Chocobozzz
