### ISSUE TITLE
Login for blocked user sending 503 instead of 400

### ISSUE THREAD

**Issue by joshmorel** [Chocobozzz/PeerTube#975]
* **PeerTube version or URL:** local dev
* **Browser name/version:** n/a
* **NodeJS version:** 8.11.2

* **What is the expected behaviour?**
For `Test users: Should block and unblock a user:` to pass the expected status code for login of blocked user is 400. 

* **What do you see instead?**
503 is sent instead. Tried to figure this out on my own but got stuck - seems to relate to `oauth2-server` `AccessDeniedError` in `server/lib/oauth-model.ts` but I don't know why it's returning 503 instead of 400.

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/bfcef50db9c1c1d34ea550ea156c52cb327e160e
