### ISSUE TITLE
Occitan language name

### ISSUE THREAD

**Issue by Quenty31** [Chocobozzz/PeerTube#980]
Bonjour à tous,
j'ai traduit la liste des langues, étrangement et comme vu dans d'autres projets, la langue occitane s’appelle «Occitan (post 1500)». Je ne sais pas pourquoi =/
Parfois on voit aussi "Occitan or provençal", mais le nom est Occitan.
Peut-on corriger la liste ? Car j'ai vu que les traducteurs traduisaient ce qui suit.

Cordialement

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/db6d617dd2e578894661e57dafe02194e2b28f16

**Comment by Quenty31** [comment]
Grand mercé :)

Merci beaucoup ! Vivement octobre maintenant :D
