### ISSUE TITLE
large upload fails with Bad gateway 502 and does not cleanup files

### ISSUE THREAD

**Issue by uranixcz** [Chocobozzz/PeerTube#981]
* **PeerTube version or URL:**
PeerTube v1.0.0-beta.11
* **Browser name/version:**
Firefox ESR (60.1.0esr) win 64bit
* **NodeJS version:**
v8.11.4

* **What is the expected behaviour?**
Upload 6.5GB mp4 video (within 8GB limit).
* **What do you see instead?**
100% on upload and then Bad gateway 502.

* **Browser console log if useful (Gist/Pastebin...):**
* **Server log if useful (Gist/Pastebin...):**
2018/08/29 18:08:14 [error] 17447#17447: *1 upstream prematurely closed connection while reading response header from upstream, client: 109.239.77.230, server: video.sebesdileni.cz, request: "POST /api/v1/videos/upload HTTP/2.0", upstream: "http://127.0.0.1:9000/api/v1/videos/upload", host: "video.sebesdileni.cz", referrer: "https://video.sebesdileni.cz/videos/upload"
Nothing interesting in peertube.log
{"message":"109.239.77.230 - - [29/Aug/2018:16:08:14 +0000] \"POST /api/v1/videos/upload HTTP/1.0\" - - \"https://video.sebesdileni.cz/videos/upload\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0\"\n","level":"info","label":"video.sebesdileni.cz:443","timestamp":"2018-08-29T16:08:14.427Z"}

tried several times, and videos are not deleted from filesystem
-rw-r--r-- 1 peertube peertube 5.2G Aug 29 02:07 6583bdf2a7028110f4373812ce7d0277.mp4
-rw-r--r-- 1 peertube peertube 2.1G Aug 29 02:14 bcf12f395c999ede12600ca80638eccd.mp4
-rw-r--r-- 1 peertube peertube 3.2G Aug 29 14:46 9e8a218356612fd3c014aa9c4c407a82.mp4
-rw-r--r-- 1 peertube peertube 2.6G Aug 29 15:17 0996573a3829dd5c159f556b210aa3c6.mp4
-rw-r--r-- 1 peertube peertube 3.0G Aug 29 16:11 e9902e3bd7c7facb02d37da519466c12.mp4
-rw-r--r-- 1 peertube peertube 2.4G Aug 29 18:06 ca1a90a2de6d72749fe8787c1d2ec322.mp4

**Comment by Chocobozzz** [comment]
How long the upload took?

Do you use the same timeout values of our nginx template? https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube#L95

**Comment by uranixcz** [comment]
https://pastebin.com/0wrgPBXd

**Comment by Chocobozzz** [comment]
Do you still have the issue?

**Comment by uranixcz** [comment]
Unfortunately we deleted the VM with Peertube and plan to test it again in a year or so.
