### ISSUE TITLE
Add user option to disable 'instant' autoplay

### ISSUE THREAD

**Issue by Niquarl** [Chocobozzz/PeerTube#982]
For users experiencing buffering issues mainly due to slow internet it could be beneficial to have an option to not start playing the video instantly but rather to wait X seconds in order for the video to download a small buffer.

See also; https://mastodon.multimob.be/@tux/100634874333013647

**Comment by rigelk** [comment]
Hi @Niquarl ! Disabling autplay already exists as a setting for registered users as per https://github.com/Chocobozzz/PeerTube/pull/159. But explicitly disabling for some time is yet to be implemented, indeed.

**Comment by Chocobozzz** [comment]
The buffering issue should be fixed :+1:
