### ISSUE TITLE
admin create user no videoQuotaDaily form control 

### ISSUE THREAD

**Issue by joshmorel** [Chocobozzz/PeerTube#985]
* **PeerTube version or URL:** develop commit 2d9fea161fd4fc73994fc77951bafdccdc2071fd
* **Browser name/version:** Any
* **NodeJS version:** n/a

* **What is the expected behaviour?**

Can create a user via admin create user form

* **What do you see instead?**

* Console error: `ERROR Error: Cannot find control with name: 'videoQuotaDaily'`
* `Daily video quota` dropdown not populated, if any selected and user form submitted get `Should have a valid daily user quota` error

**Comment by rigelk** [comment]
@Nutomic that might be related to your recent PR.

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/d6ca951b3cc7cb19ad9f52249444fc68c5d81d50
