### ISSUE TITLE
I want to change the colors of my instance | theme engine

### ISSUE THREAD

**Issue by FirePowi** [Chocobozzz/PeerTube#988]
* **PeerTube version or URL:** beta 9

* **What is the expected behaviour?**
Possibility to modify the color of instance.
Maybe a doc of selectors for the CSS. 
Please, what's the selector of the loading bar ?

**Comment by Chocobozzz** [comment]
@rigelk The color is not defined by css in the [module we use](https://github.com/aitboudad/ngx-loading-bar), but by input Angular attribute.

**Comment by rigelk** [comment]
@Chocobozzz in the end no need for the input ¯\_(ツ)_/¯

Implemented as ed19bb9a3269a9edb247c10d1be1ea20a959f1cb.
