### ISSUE TITLE
upload.js : custom thumbnail and preview not processed

### ISSUE THREAD

**Issue by aerogus** [Chocobozzz/PeerTube#991]
* **PeerTube version or URL:**
beta 11

* **NodeJS version:**
v10.9.0

* **What is the expected behaviour?**
Upload a video with upload.js cli tool and set custom preview and thumbnail pictures

* **What do you see instead?**
Preview and thumbnail pictures are not imported, the autogenerated pictures from the video is used

command line invoked :

`
node dist/server/tools/upload.js --url=https://xxx --username=root --password=xxx --video-name="Video Name" --file=/data/my_local_video.mp4r -v "/data/my_local_image.jpg" -b "/data/my_local_image.jpg"
`

in blob/develop/server/tools/upload.ts, it seems that program['thumbnailPath'] and program['previewPath'] are waited but in the program array, the -b (or --thumnail) and -v (or --preview) parameters only populate preview and thumbnail fields

dirty hacking the upload.js script with :

```
console.log('Uploading %s video...', program['videoName']);
console.log(program);
program['thumbnailPath'] = program['thumbnail'];
program['previewPath'] = program['preview'];
```

solve the problem

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/d02911fadd7548b7bfbc2a1294b50930e27041cb
