### ISSUE TITLE
option for to admin verify user email

### ISSUE THREAD

**Issue by joshmorel** [Chocobozzz/PeerTube#992]
As discussed here #977  - this would allow the admin to verify a user's email to the console. This is mainly to address the edge case where a user registers when email verification is required and there are technical issues around emails that can't quickly be resolved.

**Comment by Chocobozzz** [comment]
As I said in https://github.com/Chocobozzz/PeerTube/pull/977#issuecomment-416868853 I think it would be better to have checkbox in the admin user form.

**Comment by joshmorel** [comment]
For sure - just a checkbox. Should be simple. You can assign me

**Comment by Chocobozzz** [comment]
Or add `emailVerified` to the `UserUpdate` model and use the update endpoint? https://github.com/Chocobozzz/PeerTube/blob/develop/server/controllers/api/users/index.ts#L258

**Comment by joshmorel** [comment]
Thanks. Glad I asked - that's definitely the simplest. I'll try to get this done by Wednesday latest.
