### ISSUE TITLE
Video importer does not always find matching videos with -publishedAt sort

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#996]
I'm importing many videos from YouTube using import-videos.ts, and I've been running into an issue where it fails to detect an already-uploaded video and reuploads it, because a search for the video title does not in fact return the video that was an exact match.

It looks like import-videos uses tests/utils/search/videos.ts to searchVideo(), but that function is hardcoded to sort the results by -publishedAt. In my case, this returns several videos that have similar but not identical titles, does not return the exact match, and the video gets reuploaded.

When I search for that same title in the web UI, I find the correct video. Looking at the requests, both search queries are identical but the web UI uses "-match" as its sort key. I'm going to work around this locally by modifying the tests/utils code to hardcode "-match", but I'd love advice from someone more familiar with the goals of this code architecture on what a clean fix might be.

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/ea853b72823b9daff8bfea7177436d22951eb7ef
