### ISSUE TITLE
Provide clarity on use of tools.md and `--production` flag

### ISSUE THREAD

**Issue by joshmorel** [Chocobozzz/PeerTube#998]
* **Browser name/version:** n/a
* **NodeJS version:** n/a

* **What is the expected behaviour?** Can use tools `tools/import-videos` or other scripts regardless of which doc I follow.

* **What do you see instead?**

On the instance I'm helping with we've been using the the `import-videos` tool. We upgraded to 1.0.0-beta.11 using `yarn install --production --pure-lockfile` and it stopped working. My friend who administrating the instance doesn't have any node background so it was not obvious at all why it wasn't working.

After I took a look it became clear that the issue was `supertest` is a dependency as test utils are used and since `supertest` is in `devDependencies` it wouldn't be installed with the `--production` flag.

The simplest resolution would be to remove the `--production` flag from the production.md docs for installing/upgrading. Because the footprint of the `devDependencies` is not of much significance I think this would be best.

**Comment by Chocobozzz** [comment]
Maybe we should say in the documentation users have to clone peertube in another directory than their prod install if they are on their production server.

> The simplest resolution would be to remove the --production flag from the production.md docs

The --production flag does not install client dependencies too (~600MB ;))

**Comment by joshmorel** [comment]
I think cloning peertube in another directory is a bit much. As a sys admin I would expect `server/tools` to work in production.

Another option is to move `supertest` from `devDependencies` to `dependencies`. This seems like it would be enough to allow at least the `import-videos.js` script to work when yarn run with `--production` flag.

**Comment by Chocobozzz** [comment]
> As a sys admin I would expect server/tools to work in production.

In fact these tools should not be packaged in the releases. They are not intended to be used in a production setup. In a perfect world, we should move these tools in another repository but I don't have enough time to do this.

> Another option is to move supertest from devDependencies to dependencies.

In this script we use functions from test `utils` directory, so it could break in the future if we use another test dependency in our unit tests.

**Comment by joshmorel** [comment]
If that is the intent I'll close the issue. I will say the tools are useful in our setup and use case but I can see how for most they shouldn't need to use them.

**Comment by Chocobozzz** [comment]
Anyway I tried to improve the documentation: https://github.com/Chocobozzz/PeerTube/commit/0292eb8c88e83b418db403144cbb3732d5721eaf

**Comment by Chocobozzz** [comment]
@joshmorel Why did you reopen this issue? Is the documentation still unclear?

**Comment by joshmorel** [comment]
Meant to put in the PR welcomed - 0292eb8c88e83b418db403144cbb3732d5721eaf -  immediately after re-opening. My bad :)
